### ISSUE TITLE
Web -Chat - The welcome message and error message are not scaled correctly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12335] opened 2022-11-01 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12150

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go offline
3. Click the green plus at the bottom->New chat
4. Enter 55555 as a phone number and select it in the results
5. Go back online
6. Click the search icon in the header
7. Enter 55555 and open this chat

## Expected Result:
The welcome message and the error message should be spread over the entire width of the chat page

## Actual Result:
The welcome message and error message are not scaled correctly

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.22.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![12150 Web](https://user-images.githubusercontent.com/93399543/199228401-8e2d769c-ac60-4171-84e4-3a6e78cbdd7f.png)

https://user-images.githubusercontent.com/93399543/199228403-d393e6c0-df2a-4285-8ea3-c34c0d7c9c85.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-11-01 18:18
I think I'm still unable to reproduce in Chrome, the error message _looks_ to be aligned properly
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/22508304/199308466-aedc895a-42e5-4ed4-8252-1472d1704b88.png">

**Comment by kbecciv** [comment] 2022-11-04 15:11
@mallenexpensify We are expecting to see the error message in one line in the main chat window. But if its expected behavior, please let us know.

**Comment by mallenexpensify** [comment] 2022-11-04 21:54
> expecting to see the error message in one line in the main chat window. 

@kbecciv I'm still unsure of what that's supposed to look like, do you have a screenshot example?

**Comment by mallenexpensify** [comment] 2022-11-07 15:48
@kbecciv when you get a min, can you address the above? (commenting cuz it's `Daily`)

**Comment by kbecciv** [comment] 2022-11-07 17:22
@mallenexpensify This is just an idea how it can look. If you think this this is expected layout, please let me know.

![2 ](https://user-images.githubusercontent.com/93399543/200373424-0139d96c-5744-40cb-a4f2-8652e0b58944.jpg)

**Comment by thesahindia** [comment] 2022-11-07 17:28
I believe this is expected. Let's close this.

**Comment by mallenexpensify** [comment] 2022-11-07 23:33
Thanks @thesahindia !  I agree that I think it's expected. 
Thanks @kbecciv for the feedback.  If you see any inconsistencies where the positional/location of the message isn't consistent with the above, please comment/reopen this issue or create a new GH

**Closed by mallenexpensify** 2022-11-07 23:33 UTC
Labels: Daily, Bug
