### ISSUE TITLE
[$250] Tags settings – Deleted tag offline reappears with empty name online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44466] opened 2024-06-26 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4671475
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new workspace
4. Navigate to the workspace editor
5. Navigate to "More Features"
6. Enable the tags toggle
7. Open Tags
8. Add a tag
9. Go Offline and delete tag
10. Go Online and wait a minute

## Expected Result:
You haven’t created any tags banner is visible

## Actual Result:
Deleted tag offline reappears with empty name online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a1ce2a91-feb9-4aaa-822d-41383920297c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment] 2024-06-26 14:42
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-26 14:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by ikevin127** [comment] 2024-06-28 18:56
Looking for proposals.

> Unable to auto-create job on Upwork. The BZ team member should create it manually for this issue.

Based on the comment quote above, looks like automation failed to create Upwork job and this means that the $250 bounty wasn't added to the issue title which might be part of the reason why contributors did not post proposals yet as they might be unsure of the issue status and whether it's open for proposals.

**Comment by ikevin127** [comment] 2024-07-01 18:03
Looking for proposals.

> Unable to auto-create job on Upwork. The BZ team member should create it manually for this issue.

Based on the comment quote above, looks like automation failed to create Upwork job and this means that the $250 bounty wasn't added to the issue title which might be part of the reason why contributors did not post proposals yet as they might be unsure of the issue status and whether it's open for proposals.

cc @abekkala

**Comment by ikevin127** [comment] 2024-07-02 22:10
Looking for proposals.

> Unable to auto-create job on Upwork. The BZ team member should create it manually for this issue.

Based on the comment quote above, looks like automation failed to create Upwork job and this means that the $250 bounty wasn't added to the issue title which might be part of the reason why contributors did not post proposals yet as they might be unsure of the issue status and whether it's open for proposals.

cc @abekkala

**Comment by abekkala** [comment] 2024-07-03 13:28
manually created job post
https://www.upwork.com/ab/applicants/1808493064874298225/job-details

**Comment by Tony-MK** [comment] 2024-07-03 14:18
@ikevin127, I tried to reproduce this issue but failed.

Are there any other missing steps?

Thanks

**Comment by ikevin127** [comment] 2024-07-03 20:54
@abekkala @Tony-MK I wasn't able to reproduce either, here are the vids:

| Test method 1 | Test method 2 |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/898a9fce-3c3c-4b15-a73c-d0fb8c0165ce"> | <video src="https://github.com/Expensify/App/assets/56457735/7f21b981-df05-4d52-aa31-10681cf0a527"> |

##

Must've been some back-end API / pusher related issue which possibly failed to remove the tag entry from the database, while we deleted the FE onyx data -> this could explain the empty tag data.

I'd ask for a re-test and if not reproducible, close it.

**Comment by ikevin127** [comment] 2024-07-09 19:55
Bump on ^ https://github.com/Expensify/App/issues/44466#issuecomment-2207263518.

**Comment by mvtglobally** [comment] 2024-07-11 03:51
Issue not reproducible during KI retests. (First week)

**Comment by ikevin127** [comment] 2024-07-15 18:25
Bump on ^ https://github.com/Expensify/App/issues/44466#issuecomment-2207263518 🎲

**Comment by abekkala** [comment] 2024-07-16 14:11
thanks! sorry, I missed that!

**Comment by mvtglobally** [comment] 2024-07-19 03:22
Issue not reproducible during KI retests. (Second week)

**Comment by ikevin127** [comment] 2024-07-19 07:47
So far issue not reproducible, we're currently re-testing.
More context in https://github.com/Expensify/App/issues/44466#issuecomment-2207263518.

**Comment by ikevin127** [comment] 2024-07-22 18:29
So far issue not reproducible, we're currently re-testing.
More context in https://github.com/Expensify/App/issues/44466#issuecomment-2207263518.

**Comment by abekkala** [comment] 2024-07-22 18:29
not overdue - we're retesting

**Comment by abekkala** [comment] 2024-07-25 15:52
waiting on one more retest - if not reproducible I'll close out

**Comment by ikevin127** [comment] 2024-07-25 19:47
> waiting on one more retest - if not reproducible I'll close out

**Comment by ikevin127** [comment] 2024-07-29 19:51
> waiting on one more retest - if not reproducible I'll close out

**Comment by ikevin127** [comment] 2024-08-02 18:23
> waiting on one more retest - if not reproducible I'll close out

**Comment by mvtglobally** [comment] 2024-08-03 04:08
Issue not reproducible during KI retests. (Third week)

**Closed** 2024-08-05 14:01 UTC
Labels: External, Daily, Help Wanted, Bug, retest-weekly
