### ISSUE TITLE
[$250] Search - Domain room chat is missing in "In" list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49055] opened 2024-09-12 10:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User is logged in with expensifail account.

1. Go to staging.new.expensify.com
2. Go to domain room chat #applause.expensifail.com
3. Send a message.
4. Go to Search > Chats.
5. Click Filters.
6. Click In.
7. Look for the domain room chat.

## Expected Result:
The domain room chat should be in the list.

## Actual Result:
The domain room chat is missing in "In" list.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2b884e0e-df34-4350-a09b-c96ff27637ba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834269100709626401</li>
        <li>Upwork Job ID: 1834269100709626401</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by Julesssss** [comment] 2024-09-12 14:10
> new feature, doesn't exist in prod

Removing blocker .

**Comment by NaveedShaikh78** [comment] 2024-09-12 20:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Domain room chat is missing in "In" list . 

### What is the root cause of that problem?
The '#' key is not present in room name. Hence it is not matching.

### What changes do you think we should make in order to solve the problem?
Searching should not be depend on exact match it should allow up to 80% to 90 % match even with some spelling mistake.

### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2024-09-13 08:37
On second thoughts I believe this is expected. We are also working on major changes to search, so I am closing.

**Closed by Julesssss** 2024-09-13 08:37 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
