### ISSUE TITLE
[$1000] Wrong number of replies is displayed when a reply is flagged as offensive

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20102] opened 2023-06-02 21:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in with user A
2. Send a comment to user B
3. Click "Reply in thread" icon
4. Send a reply comment
5. From user B, open the thread
6. Click on "Flag as offensive" icon for user A's reply
7. Choose any reason
8. Go back to the report
## Expected Result: 
Correct number of replies is displayed i.e. "2 Replies" in this case
## Actual Result: 
Wrong number of replies is displayed i.e. "3 Replies" in this case
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/881df58f-9165-49a3-863d-f3de15607041

https://github.com/Expensify/App/assets/43996225/9cbb3701-2238-424e-af40-7425bc6f1017

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685619366271189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d1d283fd8c2b42e</li>
        <li>Upwork Job ID: 1666480576213250048</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-06-07 05:34
I've pushed back on this one in the Slack thread: https://expensify.slack.com/archives/C049HHMV9SM/p1686116010341579?thread_ts=1685619366.271189&cid=C049HHMV9SM

I'm not quite sure this is a bug as it makes sense to me that we count the Concierge message as a reply in the thread.

**Comment by tjferriss** [comment] 2023-06-07 16:22
Alright, I got clarification in Slack. I can reproduce the issue.

<img width="795" alt="Screenshot 2023-06-07 at 09 19 33" src="https://github.com/Expensify/App/assets/8292562/aa8d9b8b-0bce-4f29-bb5e-025d0753bd54">
<img width="824" alt="Screenshot 2023-06-07 at 09 19 37" src="https://github.com/Expensify/App/assets/8292562/81ce2e3a-700e-4472-86c6-181fef48b123">

**Comment by Pujan92** [comment] 2023-06-08 11:16
I think this needs to handle in the backend as prop `childVisibleActionCount` which we are using to show as number of replies received from backend.

**Comment by tjferriss** [comment] 2023-06-09 03:32
@roryabraham based on @Pujan92 comment above, does this need to be worked on internally?

**Comment by dangrous** [comment] 2023-06-09 18:23
Thanks for the tag! So this one sounds a little different - is it due to the system message? Is it specifically for flagged messages? We should definitely include system messages in the count, but this bug is that - even including system messages - we're still one too high. It's counting the original, as a reply, maybe.

Hm or maybe it's counting both whispers - the whisper to the reporter AND the whisper to the reportee - which no one should be able to see both of. Okay sorry @pecanoro going to cc you here as well. Are whispers counted in the child action count, even if the current user can't see them?

**Comment by pecanoro** [comment] 2023-06-09 18:48
> Are whispers counted in the child action count, even if the current user can't see them?

No idea, when I implemented whispers/welcome messages, threads were not a thing so I guess whoever implemented threads didn't take it into account. We were going to remove welcome messages from threads I think, did that happen?

**Comment by roryabraham** [comment] 2023-06-13 02:33
Sorry I missed this one earlier. It appears to me like it will probably need to be a back-end fix, but it's a bit complicated since the value of `childVisibleActionCount` is actually different on a per-user basis. Getting close to the end of my day here, will strive to make progress on this one tomorrow.

**Comment by roryabraham** [comment] 2023-06-17 01:21
Sorry, have been heads-down on this due to deploy fires. Going to make this a weekly, internal since that feels appropriate for this issue.

**Comment by pecanoro** [comment] 2023-06-20 16:22
We noticed this same bug for other types of messages [here](https://expensify.slack.com/archives/C04QEB4MJEQ/p1687223688195309) so I am bumping this to daily since ideally, we should fix this for SNH. I think the problem is probably the query that computes `childVisibleActionCount `

**Comment by tjferriss** [comment] 2023-06-22 05:18
@roryabraham SNH is at the start of next week. Do we expect to get a fix for this one this week?

**Comment by pecanoro** [comment] 2023-06-22 15:23
Oh well, it seems @aldo is fixing it here https://github.com/Expensify/Auth/pull/8159 so because of that, I am going to reassign it so he can get credit for the contributions!

**Comment by tjferriss** [comment] 2023-07-12 06:12
@adeel0202 I just sent you the offer via Upworks: https://www.upwork.com/jobs/~012218104f422ffcc4

**Comment by tjferriss** [comment] 2023-07-12 20:48
Payment sent.

**Closed by tjferriss** 2023-07-12 20:48 UTC
Labels: Reviewing, Daily, Internal, Bug
