### ISSUE TITLE
[$500]  Web - Workspace - Default cursor is shown around the checkbox

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34821] opened 2024-01-19 17:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with an expensifail account
2. Crate a workspace
3. Invite a member
4. Go offline
5. Delete the member
6. Hover over the member near the checkbox

## Expected Result:
The "blocked" cursor should show everywhere while still hovering over the member

## Actual Result:
Default cursor is shown around the checkbox

## Workaround:
Unknonw

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5e38112f-0184-44db-9f7c-8fc0f7493a8c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108a839028e649652</li>
        <li>Upwork Job ID: 1748399188516872192</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2024-01-19 17:45
# Proposal

## Root cause
There is no cursor disable style on the parent view of checkbox view in `BaseListItem`

## What changes should be made to fix this?
We should add `item.isDisabled && styles.cursorDisabled,` to the parent `View` of `checkbox` `View`

**Comment by Pujan92** [comment] 2024-01-19 17:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor not allowed isn't shown on the right side of checkbox for disabled item

### What is the root cause of that problem?
Right margin and the cursor styles given to the same `View` which is the issue here where it won't apply cursor not allowed on the marginal area.
https://github.com/Expensify/App/blob/56fb81458582179196f2a5cedaf1a358bdbca48e/src/components/SelectionList/BaseListItem.js#L85

### What changes do you think we should make in order to solve the problem?
Move right margin style to the parent view.

**Comment by smart-tech-master** [comment] 2024-01-19 20:44
@lanitochka17 
Solved problem, please let me know if you still haven't solved the problem

**Comment by isabelastisser** [comment] 2024-01-22 13:17
@fedirjh I agree! Thanks for the input here. Closing!

**Closed by isabelastisser** 2024-01-22 13:17 UTC
Labels: External, Daily, Help Wanted, Bug
