### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] Track Expense - Blue Border Appears on the Track Expense Button

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45570] opened 2024-07-17 07:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to FAB > Track Expense.
2. Add an amount and press Enter to proceed.
3. Observe that a blue border appears on the Track Expense button.

## Expected Result:
The blue border should not appear on the Track Expense button when Enter is pressed.

## Actual Result:
A blue border appears on the Track Expense button when Enter is pressed.

Note: It is also reproducible on Submit expense flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e9ea89d8-acbd-47fc-80e7-43ed879cc6e6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137b996b36a246d89</li>
        <li>Upwork Job ID: 1813481853685332253</li>
        <li>Last Price Increase: 2024-07-17</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103180951</li>
<li>nkdengineer | Contributor | 103180952</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-07-17 07:50
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment] 2024-07-17 07:51
Production 

https://github.com/user-attachments/assets/b3a491be-d0b4-4639-816f-26e77915e1fc

**Comment by techievivek** [comment] 2024-07-17 07:52
Not a deploy blocker since it's just an UI concern.

**Comment by nkdengineer** [comment] 2024-07-17 08:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A blue border appears on the Track Expense button when Enter is pressed.

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/components/MoneyRequestConfirmationList.tsx#L747, we manually trigger focus on the confirm button, this causes the blue border.

### What changes do you think we should make in order to solve the problem?

There's no need to manually trigger the focus on confirm button because the button has `pressOnEnter` [here](https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/components/MoneyRequestConfirmationList.tsx#L763) so its `onPress` will be triggered if we press enter.

We should simply replace [this line](https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/components/MoneyRequestConfirmationList.tsx#L747) by `document.activeElement.blur();`, so it will not automatically focus on other elements, the confirm button will be triggered on `Enter` so it can be considered to have the focus already, no manual focus needed.

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-07-17 08:28
[Proposal](https://github.com/Expensify/App/issues/45570#issuecomment-2232716521) updated to add an alternative approach

**Comment by akinwale** [comment] 2024-07-19 04:17
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/45570#issuecomment-2232716521) works here.

🎀👀🎀 C+ reviewed.

**Comment by nkdengineer** [comment] 2024-07-22 06:35
@akinwale The PR is [here](https://github.com/Expensify/App/pull/45873).

**Comment by CortneyOfstad** [comment] 2024-07-31 13:35
@stephanieelliott I am heading OoO so reassigned so there is no delay in payment. 

At this stage, we're waiting on @akinwale to complete the checklist and the automatic offer links for both @nkdengineer an @akinwale can be found [here](https://github.com/Expensify/App/issues/45570#issuecomment-2256626875). Thanks!

**Comment by techievivek** [comment] 2024-08-05 14:58
Not overdue, waiting for the checklists and payment to be done.

**Comment by techievivek** [comment] 2024-08-05 15:19
Dummy comment to remove overdue label.

**Comment by akinwale** [comment] 2024-08-05 18:50
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

This was a regression from https://github.com/Expensify/App/pull/44932. [Comment](https://github.com/Expensify/App/pull/44932#issuecomment-2269692245).

> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify.
2. Navigate to the Self-DM chat report.
3. Click on the FAB and select Track expense.
4. Enter a valid amount and continue to the next step.
5. Verify that the confirm button does not have a blue border indicating active focus.

Do we agree 👍 or 👎?

**Comment by stephanieelliott** [comment] 2024-08-06 04:28
Summarizing payment on this issue: 

 - Contributor: @nkdengineer $250 via Upwork - PAID 
 - Contributor+: @akinwale $250 via Upwork - PAID 
 
Upwork job is here: https://www.upwork.com/jobs/~0137b996b36a246d89
Regression test is here: https://github.com/Expensify/Expensify/issues/418072

**Closed by stephanieelliott** 2024-08-06 04:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
