### ISSUE TITLE
[HOLD App#36948][$500] Windows - Settings - The textbox isn't auto focused

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37410] opened 2024-02-28 11:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when executing PR :** https://github.com/Expensify/App/pull/34925

**Version Number:** 1.4.44.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N, new feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Navigate to Settings - Switch to Expensify Classic
2. Choose any option
3. Click on the Next button

## Expected Result:
It should be focused and the keyboard should be visible.

## Actual Result:
The textbox isn't auto focused.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/38f0668d-909c-4b4a-ba1c-520a076ae68f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014abe2f898e817726</li>
        <li>Upwork Job ID: 1762803417818267648</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-28 11:35
We think that this bug might be related to #wave9-collect-signup
CC @MitchExpensify

**Comment by danieldoglas** [comment] 2024-02-28 11:54
This doesn't need to be a deploy blocker

**Comment by askavyblr** [comment] 2024-02-29 11:15
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**

The textbox isn't auto-focused.

**What is the root cause of that problem?**

need to pass autoFocus prop 

**What changes do you think we should make in order to solve the problem?**

https://github.com/Expensify/App/blob/cb58503cbb254648c46525b81e8fc96521c19178/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L122-L137
   

  
**What alternative solutions did you explore? (Optional)**

NA


https://github.com/Expensify/App/assets/125897912/2b0cc93f-33d4-4a26-a06f-255758bf30e5

**Comment by MitchExpensify** [comment] 2024-03-02 01:57
Are you recommending we close this @situchan ?

**Comment by danieldoglas** [comment] 2024-03-04 11:50
>  Are you recommending we close this @situchan ?

It will fixed on another issue, but it was not reported on that issue. Though I think since we're fixing all instances, I think it's safe to close.

**Comment by danieldoglas** [comment] 2024-03-04 16:15
Closing in favor of https://github.com/Expensify/App/issues/36948#issuecomment-1966866629

**Closed by danieldoglas** 2024-03-04 16:15 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
