### ISSUE TITLE
[HOLD] New text messages removes web preview links of all the previous chats

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24503] opened 2023-08-13 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: This issue is only with admin chat. Normal chat works fine.
1. Initiate a chat with admin page
2. Send a few web links messages. Type "www.google.com.", www.facebook.com
3. Send a normal message Eg. Hello (or create a dummy task)
4. Refresh the page (very important)
5. Verify that the web preview links disappear
## Expected Result: 
New messages should not affect previous messages
## Actual Result: 
New text message removed the web preview link of all previous texts
(Need couple refresh to reproduce)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7956bb92-4843-453a-a6fe-a43988963d49

https://github.com/Expensify/App/assets/43996225/9334fb94-f077-4980-9b11-5f5ca6316422

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690932505629539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2023-08-14 11:16
reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-14 12:03
Posting [here](https://expensify.slack.com/archives/C03U7DCU4/p1692014523738149) to confirm, but at first blush seems like a bug.

**Comment by jscardona12** [comment] 2023-08-14 13:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
New text messages removes web preview links of all the previous chats
### What is the root cause of that problem?
The root cause of the issue is that is not always calling the ExpandURLPreview because of this [condition](https://github.com/Expensify/App/blob/8e799dfe2f4396e6c6e7684f30753a473a5edd2e/src/pages/home/report/ReportActionItem.js#L158:L161) the api petition `ExpandURLPreview` to is always made eve if the the metadata is already set and the backend is sometimes returning null overwriting the linkMetadata. 

### What changes do you think we should make in order to solve the problem?
We should only make the petition to``ExpandURLPreview`  if the `linkMetadata`is null. 
    useEffect(() => {
        const urls = ReportActionsUtils.extractLinksFromMessageHtml(props.action);
        if (props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
            return;
        }
        if(urls.length > 0 && props.action.linkMetadata === null) {
            Report.expandURLPreview(props.report.reportID, props.action.reportActionID);
        }
    }, [props.action, props.report.reportID]);

### Solution Working

https://github.com/Expensify/App/assets/16781411/00b4e7c2-b563-4592-89ab-43c066d32006

**Comment by jscardona12** [comment] 2023-08-14 13:57
@dylanexpensify i thinkthe slack url that you put is not working. 
Although the bug is replicable and i found the root cause.

**Comment by dylanexpensify** [comment] 2023-08-14 14:53
@jscardona12 sorry, internal channel! We're potentially going to hold this as part of a larger project, but will update here as soon as I know if that's the case!

**Comment by jscardona12** [comment] 2023-08-14 15:07
@dylanexpensify thx for the update!

**Comment by marcaaron** [comment] 2023-09-19 05:46
Removing the Monthly tag here for focus. I think we will probably roll out the link preview feature again in the near future when it is a higher priority.

**Comment by marcaaron** [comment] 2023-10-25 02:43
Closing for now because Melvin doesn't understand what HOLD means 😄

**Closed by marcaaron** 2023-10-25 02:43 UTC
Labels: Planning
