### ISSUE TITLE
[$500] Chat - While edit comment, compose box not shown but after refreshing page it is shown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35501] opened 2024-01-31 18:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on any report with messages you sent/ or send a message
3. Long press the message and select edit comment
4. Note after edit comment box opened, below compose box not shown
5. Refresh the page
6. Now note, below compose box is shown

## Expected Result:
While edit comment, compose box is not shown and so the behavior must not change after refreshing the page.

## Actual Result:
While edit comment, compose box is not shown but after refreshing page compose box is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1dad5365-8334-4871-9d46-0b329549424a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123cdafc077265524</li>
        <li>Upwork Job ID: 1752759888491229184</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2024-01-31 18:28
This looks like an intended behavior: **_When there is no focused edit composer, we show the main composer_**

**Comment by s77rt** [comment] 2024-01-31 18:34
I don't see a bug here. Seems working as intended

**Comment by mollfpr** [comment] 2024-02-02 15:38
We have different behavior between Chrome and Safari. On Chrome we don't autofocus to the edit composer, but we do autofocus to edit composer on Safari after refresh.

https://github.com/Expensify/App/assets/25520267/edf5370d-3c37-4b56-ac7a-22d78b898d5d

**Comment by CortneyOfstad** [comment] 2024-02-05 16:10
Not overdue — just waiting on proposals 👍

**Comment by CortneyOfstad** [comment] 2024-02-08 16:49
No proposals yet

**Comment by CortneyOfstad** [comment] 2024-02-12 14:42
Still waiting on proposals

**Comment by CortneyOfstad** [comment] 2024-02-14 15:13
Not overdue!

**Comment by mollfpr** [comment] 2024-02-16 19:46
No proposals!

**Comment by CortneyOfstad** [comment] 2024-02-16 19:50
Going to reach out to CallStack to see if we can get this rolling as it has been ~2 weeks!

**Comment by CortneyOfstad** [comment] 2024-02-16 19:51
Reached out to the team [here](https://expensify.enterprise.slack.com/archives/C03UK30EA1Z/p1708113070372599)

**Comment by CortneyOfstad** [comment] 2024-02-20 14:51
@kbecciv I just tested this again and I am unable to recreate in staging in either Safari or Chrome on mobile. Can we confirm if this issue is still occurring?

Thank you!

**Comment by mollfpr** [comment] 2024-02-20 18:40
I can't reproduce it on production mobile web safari.

**Comment by kbecciv** [comment] 2024-02-20 19:40
@CortneyOfstad Checking with team

**Comment by mvtglobally** [comment] 2024-02-21 02:29
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2024-02-22 19:14
So we have multiple reports that this is not reproducible:

- [here](https://github.com/Expensify/App/issues/35501#issuecomment-1954380037)
- [here](https://github.com/Expensify/App/issues/35501#issuecomment-1954841426)
- [here](https://github.com/Expensify/App/issues/35501#issuecomment-1955757138)

Going to close this and if you find it is reproducible @kbecciv feel free to reopen. Thanks!

**Closed by CortneyOfstad** 2024-02-22 19:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
