### ISSUE TITLE
iOS/ND App - Login - Number keypad does not appear in magic code page

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#51767] opened 2024-10-30 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-9
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, and it's NOT reproducible on the Hybrid app. 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [Login - Email field and Keyboard behavior on mobile](https://expensify.testrail.io/index.php?/cases/view/1970849)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Issue reported by:** Applause - Internal team

## Action Performed:
1. Launch Newdot app
2. Enter any existing account email in login page (or use autofill feature)
3. Tap Continue button

## Expected Result:
Number keypad should automatically appear to enter magic code

## Actual Result:
Number keypad does not appear automatically in magic code page
User has to tap on any magic code fields for the number keypad to appear

Note: For the new account, the keypad collapse on magic code page & user has to tap any field for the keypad to display

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/489fcbb2-9ebf-4c90-910a-a63d47290628

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment] 2024-10-30 20:31
Note that this is ONLY reproducible on the ND app. Not reproducible in the Hybrid app as it's a different login page.

**Comment by anmurali** [comment] 2024-11-06 01:49
Checking on prioritization for New App bugs since hybrid is the focus now - https://expensify.slack.com/archives/C06ML6X0W9L/p1730856211393429

**Comment by anmurali** [comment] 2024-11-12 03:15
>Note that this is ONLY reproducible on the ND app. Not reproducible in the Hybrid app as it's a different login page.

Since we're depreciating New standalone app and it is not a bug on Hybrid app, I think we close this.

**Closed by anmurali** 2024-11-12 03:15 UTC
Labels: Daily, Overdue, Bug
