### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [HIGH] [API Reliability] The app assumes its offline when its on spotty connection

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42988] opened 2024-06-03 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1717393020259779

## Action Performed:
Break down in numbered steps

'm on a pretty good wifi network in that I can access the web normally for almost everything else.  But I can't get online with NewDot -- and it doesn't really seem to be trying.  I'm in a hotel so I feel like maybe it took a second to get through the wifi authentication, and perhaps it tried once and failed, and now it's not trying again?  I would think that it should try every minute or so even when it thinks it can't connect.  I'm going to try to refresh to see if that fixes it...  Yep, refresh fixed it.  So I think retrying every minute or so would also "fix" this

![image](https://github.com/Expensify/App/assets/36083550/dcd9e08c-e612-41dd-87ad-a1637206dc5b)

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by adhorodyski** [comment] 2024-06-04 16:45
I'm afraid we can't find the root cause here (easily) - I wasn't able to reproduce this in any way, the `net-info` module works as expected and picks up any changes well for me. 

What do we mean by `retrying every minute or so would also "fix" this`? Do I get this right that we can call NetInfo's [refresh method](https://github.com/react-native-netinfo/react-native-netinfo?tab=readme-ov-file#refresh) inside of [this if statement](https://github.com/Expensify/App/blob/1865aa8e1a2c6f5ecf6ccbbfcd44d91cf4fbb04a/src/libs/NetworkConnection.ts#L102)? This should notify all the subscribers and eventually switch back to the 'online' state that will get reflected on the UI. I can't imagine how we will test this though in a real life apart from seeing that it will we-check the connection state.

```diff
const intervalID = setInterval(() => {
        // Offline status also implies backend unreachability
        if (isOffline) {
+            NetInfo.refresh();
            return;
        }
```

Overall, I see the lack of `components <-> remote data` bounding being problematic here as we have to manually tell when to re-fire requests - this works as expected for failing ones.

@mountiny I will open up a PR with this update tomorrow morning, I think we can test a build against this behaviour, see if it retries picking up the connection correctly.

**Comment by techievivek** [comment] 2024-06-20 13:09
Looks good to me. @JmillsExpensify can we get this added to testRail? thanks.

**Comment by mountiny** [comment] 2024-06-25 07:37
I think $500 for the HIGH newdot-quality task is reasonable, we need to encourage people to work on these

**Comment by techievivek** [comment] 2024-06-25 14:48
Thanks, that makes sense. @JmillsExpensify can we please issue the payment here?

**Comment by techievivek** [comment] 2024-07-02 09:44
Not overdue, waiting for payment to complete. CC @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-07-02 13:24
$500 approved for @parasharrajat

**Comment by JmillsExpensify** [comment] 2024-07-02 13:27
Contract paid out and regression test created, so I'm closing out this issue.

**Closed by JmillsExpensify** 2024-07-02 13:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
