### ISSUE TITLE
Distance - IOU report for changed details, title is not shown in LHN when user re-login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32111] opened 2023-11-28 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on Fab
3. Tap request money - Distance
4. Enter start and finish waypoints
5. Tap next
6. Select a Workspace
7. Tap distance
8. Tap on distance request created to open distance request detail page
9. Tap description
10. Enter an description and save
11. Navigate to LHN and note IOU report created for changes made by "set description"
12. Tap profile icon
13. Tap sign out
14. Login as same user
15. Note the IOU report created for changes made by "set description"

## Expected Result:
When user log out and re-login again, the IOU report created for changes made by "set description" must be displayed with "title" in LHN.

## Actual Result:
The IOU report created for changes made by "set description" is displayed with "title" in LHN but when user log out and re-login again, the IOU report is displayed "without title" in LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/74d5f640-8906-4d53-a5be-bd6b9151f8ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment] 2023-11-28 14:21
@kbecciv , can you confirm this is not happening in production?

**Comment by s-alves10** [comment] 2023-11-28 14:54
This looks like a backend issue
When a user signs in, `openApp` API is called, but this API doesn't return transactions data. Transaction data is returned when `openReport` API is called and so some gap exists between them

As you can see below, we get report name of the transaction thread from the transaction
https://github.com/Expensify/App/blob/c03a541c909f3619390d6ead73c8df23cd964e62/src/libs/ReportUtils.ts#L1859C5-L1859C5

That's why the transaction thread title appears a bit later

**Comment by danieldoglas** [comment] 2023-11-28 15:09
I agree it sounds like a backend issue. I think adding transactions to the OpenApp call is in progress in the backend right now, so I don't think this needs to be a deploy blocker.

**Comment by danieldoglas** [comment] 2023-11-28 15:09
but my question remains, if this is not happening in production, it might mean that we had a change in our staging backend that caused this

**Comment by danieldoglas** [comment] 2023-11-28 17:22
Hm, this is very intersting. I couldn't find anything that was deployed in staging that could cause this.

**Comment by shubham1206agra** [comment] 2023-11-28 17:48
@danieldoglas This problem is already known and will be fixed with https://github.com/Expensify/App/pull/31302.
You can see this problem now because we make the title blank instead of a placeholder when the transaction is null or empty.

**Comment by danieldoglas** [comment] 2023-11-28 18:04
@shubham1206agra I think those are different issues. Looks like this one specifically was caused by the TS migration that was deployed to staging yesterday with https://github.com/Expensify/App/pull/29012. 

I'm removing the deploy blocker on this for now

CC @kubabutkiewicz

**Comment by kubabutkiewicz** [comment] 2023-11-29 06:52
@danieldoglas Checking

**Comment by kubabutkiewicz** [comment] 2023-11-29 14:44
@danieldoglas Didn't find the root cause yet, but have some observations.
Firstly I think on dev there is some bug (?) where I cannot find any users to send distance money request 

https://github.com/Expensify/App/assets/25230417/62256618-9e7d-4370-a72b-40f416d6ed8e


Secondly I think my PR just show hidden bug by adding this `if` statement which I think is related to bug reported here

https://github.com/Expensify/App/blob/2f9ae2d37354ce3335d16805d05c313ef3d25fa9/src/libs/ReportUtils.ts#L1858-L1863

Here are two videos , one for current `main` and second from before merging ReportUtils migration

https://github.com/Expensify/App/assets/25230417/6c100306-64fa-422b-92d7-7a7a7415c466


https://github.com/Expensify/App/assets/25230417/50cf3ebb-251a-44dc-bca6-232e644ab48b

My first guess is that at the begining before opening Report we dont have a data for transactions in Onyx 

https://github.com/Expensify/App/blob/2f9ae2d37354ce3335d16805d05c313ef3d25fa9/src/libs/TransactionUtils.ts#L18-L27

And before opening Report `allTransactions` are null and from here
https://github.com/Expensify/App/blob/2f9ae2d37354ce3335d16805d05c313ef3d25fa9/src/libs/TransactionUtils.ts#L389-L397C2

we will always get `{}` as a return value 
so here 
https://github.com/Expensify/App/blob/0a4985466fce930193290b38684f3c721db199be/src/libs/ReportUtils.ts#L1860C1-L1876
currently we will get `''` and previously we will get some not wanted value like `0$ request`.

I can revert my change for returning `''` but there will still be a bug. And I think @shubham1206agra was mentioning it earlier [here](https://github.com/Expensify/App/pull/29012#issuecomment-1824777575)

**Comment by danieldoglas** [comment] 2023-11-30 21:51
I understand the origin of the bug with the new check, and I think I agree that the real solution is to return the transaction.

We have a PR for that coming up next week, I think we can wait for it.

**Comment by danieldoglas** [comment] 2023-12-13 19:14
I think this is now in staging. @kbecciv can you please test this?

**Comment by kbecciv** [comment] 2023-12-18 18:21
Issue is not reproducible

https://github.com/Expensify/App/assets/93399543/c5c49c45-b15b-4732-b697-e4cfd4c241d4

**Comment by danieldoglas** [comment] 2023-12-20 18:32
Great, closing this

**Closed by danieldoglas** 2023-12-20 18:32 UTC
Labels: Engineering, Weekly
