### ISSUE TITLE
Expense - Decimal numbers appear in RHP after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46237] opened 2024-07-25 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4766431
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with HT account
3. Navigate to DM with any user
4. Tap on + Menu -> Submit expense -> Manual
5. Enter any amount -> Next
6. Navigate back to enter the amount "<"
7. Refresh the page

## Expected Result:
Decimal numbers should not appear after refreshing the page with open input of the amount of expense in the RHP

## Actual Result:
After refreshing the page with open input of the amount of expense, decimal numbers appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b9f208e7-0611-438e-b3cc-e30ac905d2da

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-25 20:48
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-07-26 05:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After refreshing the page with open input of the amount of expense, decimal numbers appear

### What is the root cause of that problem?
When we initial the amount, we always format the amount with decimals as the currency's decimals

https://github.com/Expensify/App/blob/61150f14e8346c8423af6d7660169377d1e72d01/src/pages/iou/MoneyRequestAmountForm.tsx#L153
### What changes do you think we should make in order to solve the problem?
In `convertToFrontendAmountAsString` function, we should get the current decimal of the amount and we can minimize the decimals format if the decimals of the amount are less than the currency's decimal

1. Create a `countDecimals` function that returns the decimals of the amount

```
function countDecimals(amount: number): number {
    const frontendAmount = Math.trunc(amount) / 100.0;
    if (Math.floor(frontendAmount) === frontendAmount) {
        return 0;
    }
    return frontendAmount.toString().split('.')[1].length || 0;
}
```

2. Add an extra param `shouldMinizeDecimal` in `convertToFrontendAmountAsString` function and if it's true we will minimize the decimals if need

```
function convertToFrontendAmountAsString(amountAsInt: number | null | undefined, currency: string = CONST.CURRENCY.USD, withDecimals = true, shouldMinizeDecimal = false): string {
    if (amountAsInt === null || amountAsInt === undefined) {
        return '';
    }
    const decimals = withDecimals ? getCurrencyDecimals(currency) : 0;
    const amountDecimals = countDecimals(amountAsInt);
    const finalDecimals = shouldMinizeDecimal ? Math.min(amountDecimals, decimals) : decimals;
    return convertToFrontendAmountAsInteger(amountAsInt, currency).toFixed(finalDecimals);
}
```

3. Pass `shouldMinizeDecimal` as `true` here

```
const frontendAmount = newAmount ? CurrencyUtils.convertToFrontendAmountAsString(newAmount, currency, true, true) : '';
```
https://github.com/Expensify/App/blob/61150f14e8346c8423af6d7660169377d1e72d01/src/pages/iou/MoneyRequestAmountForm.tsx#L153

OPTIONAL: We can also pass  `shouldMinizeDecimal` as `true` here. So the amount can be displayed the same on the confirmation page or add an extra param in this function to know whether we should minimize the decimals and only pass it as true on the confirmation page and other places that we need.


```
const convertedAmount = convertToFrontendAmountAsInteger(amountInCents, currency); 
```

https://github.com/Expensify/App/blob/61150f14e8346c8423af6d7660169377d1e72d01/src/libs/CurrencyUtils.ts#L116
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-07-30 23:27
Closing, posted in #expensify-open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1722381996695629)

1. [Expense - Decimal numbers appear in RHP after refreshing the page](https://github.com/Expensify/App/issues/46237#top)
2. Closing the above, seems frivolous and not worth fixing.
3. tl,dr: The amount initially shows ass 100 when submitting an expense, if you refresh the page with the RHP open it then shows as 100.00.
4. Comment and/or reopen if you disagree.

**Closed by mallenexpensify** 2024-07-30 23:27 UTC
Labels: Daily, Overdue, Bug
