### ISSUE TITLE
[HOLD for payment 2024-06-03] [QBO] Not all default settings & accounts are selected when establishing the connection to QBO

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41046] opened 2024-04-26 00:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-1
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714060188157459?thread_ts=1714057353.559839&cid=C036QM0SLJK & https://expensify.slack.com/archives/C036QM0SLJK/p1714091531288649?thread_ts=1713799261.297609&cid=C036QM0SLJK

## Action Performed:
1. Connect to QBO
2. Go to Export
3. Observe not all settings are selected by default
4. Choose an export method for, say, company card export
5. Observe the account selection is not selected

## Expected Result:

1. The following export settings should also be set by default when making a connection to QBO:

**Export page**

- `Preferred exporter` = `[policyOwner]`
- `Date` = `Export date`
- `Export out of pocket expenses as` = 
     - `Export as` = `Vendor bill`
     - `Accounts payable` = `[first applicable account in the list is selected]` **Note: This select list appears to be completely blank right now, let's fix that**
- `Export invoices as` = `[first applicable account in the list is selected]`
- `Export company cards as` = 
   -  `Export as` = `Credit card`
   - `Account` = `[first applicable account in the list is selected]`

2. Then when choosing alternative export options, let's make sure the first applicable account in the list is selected as well:

**"Export out of pocket expenses as" alt settings**

- `Export as` = `Journal entry`
- `Accounts payable` =  `[first applicable account in the list is selected]`

- `Export as` = `Check`
- `Accounts payable` = `[first applicable account in the list is selected]`

**"Export company cards as" alt settings**

- `Export as` = `Debit card`
- `Account` = `[first applicable account in the list is selected]`

- `Export as` = `Vendor bill`
- `Accounts payable` = `[first applicable account in the list is selected]`

- `Default vendor` (if enabled, disabled by default)
  - `Vendor` = `[first applicable account in the list is selected]`

3. Let's make sure we apply these changes on the "Advanced" page as well where applicable:

- `Sync reimbursed reports` (setting should be toggled on by default) =
  - `QuickBooks bill payment account` = `[first applicable account in the list is selected]`
  - `QuickBooks invoice collections account` = `[first applicable account in the list is selected]`

4. When someone changes a configuration setting (i.e updates exporting from `Credit card` to `Vendor bill`, make sure the value in the push input for the associated account selection is also updated along with the push label change. I.e 

-  `Export as` = `Credit card`
- `Account` = `Amex Card Account`

- `Export as` = `Vendor bill`
- `Accounts payable` = `[first applicable account in the vendor list is selected]`

## Actual Result:
1. Only the value in the `Preferred exporter` list looks to be selected by default on the export settings page
2. When choosing an export method (i.e `Credit Card`) the first value in the sub-account that's revealed is not selected
3. Sync reimbursed reports is not enabled by default on the Advanced page, and the two associated accounts with that setting aren't selected by default either
4. Previously selected values are not cleared from the push input as the push label updates

## Workaround:
Yes, they can select values and change values.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/baa09ca5-691b-4d0a-93b9-b923ea7d68fa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @hayata-suenaga @aldo-expensify @s77rt @teneeto @narefyev91 @zanyrenney 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by aldo-expensify** [comment] 2024-04-26 01:13
I think here is the OldDot code choosing the default settings: https://github.com/Expensify/Web-Expensify/blob/52310ff233e1bca38dd0c3238336646c1c66e640/site/deprecated/lib_policy_quickbooksOnline.js#L370-L409

**Comment by aldo-expensify** [comment] 2024-04-26 08:32
Created draft PR for the integration server to select the default values during the first import: https://github.com/Expensify/Integration-Server/pull/7882

**Comment by trjExpensify** [comment] 2024-04-29 18:31
Whoops! We need to assign Aldo here, he's actively working on PRs to address these. :)

**Comment by aldo-expensify** [comment] 2024-04-29 20:46
For choosing the defaults, what I did is:

1. Connect a QBO to a policy in OldDot
2. The configuration modal opens automatically after.
3. Save the configuration modal without touching it

The configuration at this point is what I used as a reference for the default in the QBO flow from NewDot. Do you think that is correct?

**Comment by trjExpensify** [comment] 2024-04-29 21:30
Okay, a few things just testing on staging with these changes: 

1. None of the export settings have been set: 

<img width="1311" alt="image" src="https://github.com/Expensify/App/assets/16232057/db3f01f6-2740-477a-b24b-dac9633a2ef2">

<img width="376" alt="image" src="https://github.com/Expensify/App/assets/16232057/b64c2460-227f-44ac-a51a-56bbed08b351">

2. There's now some odd label name issue on the `Date` field in the export settings:

<img width="376" alt="image" src="https://github.com/Expensify/App/assets/16232057/c3d457d5-99c5-4a37-b644-c0e6c24de689">

3. We aren't showing Chart of Accounts as `Imported` by default:

<img width="1945" alt="image" src="https://github.com/Expensify/App/assets/16232057/d1dea47e-9a60-46c0-a166-679ed271f323">

4. We've enabled `Classes` and `Customers & Projects` (which tbf, is like OldDot, so fine for now) but `Tags` isn't being added to the LHN of the workspace settings and I can't see them imported. 

<img width="1945" alt="image" src="https://github.com/Expensify/App/assets/16232057/476e92d1-d6a7-4ce9-a3e0-e1cc6174b198">

That might have something to do with the infinite spinner and `currency` crash I'm running into when establishing the connection.

**Comment by trjExpensify** [comment] 2024-05-01 01:46
^^ working theory on the above is that this PR will fix them: https://github.com/Expensify/App/pull/41155

**Comment by aldo-expensify** [comment] 2024-05-04 01:19
Haven't investigated this again. no updates

**Comment by trjExpensify** [comment] 2024-05-07 09:43
What's the plan? Wait for the other PRs to hit staging and re-test?

**Comment by trjExpensify** [comment] 2024-05-10 14:34
Sure! 

1. Credit card `Account` is not being selected by default

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/3bc8a635-e138-465f-9a67-b00e37472cf3">

2. Clicking the `Account` row navigates to a `Default vendor` page not `Account` page to select applicable credit card accounts:

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/fc11d647-73fa-4404-84eb-04d2805f1274">

(Same goes for if you switch to `Debit card`)

3. Selecting `Vendor bill` for company card export has `Default vendor` toggled on by default, when it shouldn't. The row is also bold for some reason?

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/16232057/85b9a610-39cb-4fd9-bc92-27b907552970">

Note: when you do toggle `Default vendor` the first vendor in the list of vendors should be selected

**Comment by trjExpensify** [comment] 2024-05-10 18:01
Aldo is working on it, chill Melv.

**Comment by trjExpensify** [comment] 2024-05-13 12:32
@aldo-expensify thoughts on [the above](https://github.com/Expensify/App/issues/41046#issuecomment-2104721718). Will we take care of them here?

**Comment by hayata-suenaga** [comment] 2024-05-13 16:05
- Credit card Account is not being selected by default
- Clicking the Account row navigates to a Default vendor page not Account page to select applicable credit card accounts:

@trjExpensify, let me quickly open a PR to fix this because this is just a front end adjustment.

- Selecting Vendor bill for company card export has Default vendor toggled on by default, when it shouldn't. The row is also bold for some reason?

Let me check on this. If this is a front end issue, I can handle it with the above PR. If this is not, I gonna ping Aldo. Otherwise, I'll handle these remaining issues myself so that Aldo can focus on the remaining QBO backend issue once he comes back from fixing the performance fire. 😄

**Comment by hayata-suenaga** [comment] 2024-05-13 19:24
> Selecting Vendor bill for company card export has Default vendor toggled on by default, when it shouldn't. The row is also bold for some reason?
Let me check on this. If this is a front end issue, I can handle it with the above PR. If this is not, I gonna ping Aldo. Otherwise, I'll handle these remaining issues myself so that Aldo can focus on the remaining QBO backend issue once he comes back from fixing the performance fire. 😄

I checked on this, and the value of `config.autoCreateVendor` is `true` when connected to accounting software. I think this is a backend issue.

**Comment by hayata-suenaga** [comment] 2024-05-13 19:43
The default value is set to `true` in the Integration Server. I think we made a mistake in this PR for the default value of `autoCreateVendor`.

https://github.com/Expensify/Integration-Server/blob/6053b252a5c9d33b8e1d06b38d36f69f8b17df51/src/expensify/beans/expensify/policy/integration/quickbooksonline/QuickbooksOnlineConfiguration.java#L47

I'll make a PR to fix this.

**Comment by hayata-suenaga** [comment] 2024-05-16 05:08
Once this PR hits production, I gonna test on staging to check if all default values are set correctly and then if it tests well, I'll close this issue

**Comment by trjExpensify** [comment] 2024-05-16 19:02
Yep, sounds good. Would be good to know how close we are!

**Comment by hayata-suenaga** [comment] 2024-05-20 18:45
the PR wasn't been deployed yet because of the freeze. I think the fire issue has been fixed, and once deployed, I'll test this 👍

**Comment by trjExpensify** [comment] 2024-05-24 00:35
https://github.com/Expensify/App/pull/42102 is deployed to staging.

**Comment by hayata-suenaga** [comment] 2024-05-27 17:35
tested well for me

https://github.com/Expensify/App/assets/98560306/8dc22541-2c32-407e-afe7-7cfe99667c29

**Comment by hayata-suenaga** [comment] 2024-05-29 05:47
We keep this issue open to handle the payment for @s77tr for [this App PR](https://github.com/Expensify/App/pull/42102).

**Comment by s77rt** [comment] 2024-05-29 06:58
- The PR that introduced the bug has been identified: I think this existed from the start. I found this PR https://github.com/Expensify/App/pull/41463 that changed the navigation logic but not the real culprit
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: No

**Comment by trjExpensify** [comment] 2024-06-03 19:59
Payment summary as follows:

- $250 to @s77rt for the C+ review 

Offer sent!

**Comment by s77rt** [comment] 2024-06-03 20:09
@trjExpensify Accepted! Thanks!

**Closed** 2024-06-03 20:11 UTC
Labels: Daily, Awaiting Payment, Bug
