### ISSUE TITLE
[$250] Room-A "workspace" visibility room is created via whisper from a "public" visibility room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49544] opened 2024-09-20 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- start chat
3. Create a public visibility room
4. Create 2 room via whisper by sending message - eg : `#35` `#799`
5. From the whisper message, tap yes
6. Note room created is highlighted
7. Now tap on room header -- settings -- visibility
8. Note room is a "public" visibility room
9. Now tap on any room highlighted ( created via whisper)
10. Now tap on room header -- settings -- visibility
11. Note room created is a workspace visibility room

## Expected Result:
A "public" visibility room must be created via whisper from a "public" visibility room.

## Actual Result:
A "workspace" visibility room is created via whisper from a "public" visibility room.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0a530875-069f-4910-97f5-2b17425bee92

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837194850505873695</li>
        <li>Upwork Job ID: 1837194850505873695</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104139929</li>
<li>nkdengineer | Contributor | 104139931</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by IuliiaHerets** [comment] 2024-09-20 17:10
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-09-20 18:19
I can reproduce this with the steps in the OP. I think this can be external - let's start there and see what we think!

**Comment by Christinadobrzyn** [comment] 2024-09-23 20:24
@DylanDylann, can you check out the proposal? Thanks!

**Comment by DylanDylann** [comment] 2024-09-24 03:47
I like @nkdengineer's [idea](https://github.com/Expensify/App/issues/49544#issuecomment-2364375050) to create the optimistic room data. With this approach, we have the ability to create a new room offline but still need to modify the visibility field on the BE side.

On the other hand, If we don't want to support this action offline, we can handle this issue on the BE totally by modifying the visibility field

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment] 2024-09-24 17:39
Heads up - I'm going to be ooo till 9/30. I'm not going to assign a BZ buddy to this since we're reviewing proposals. If you need someone in the meantime, feel free to reach out to the Bug team for a volunteer. thanks!

**Comment by justinpersaud** [comment] 2024-09-25 20:36
I think it's fine to support offline, proposal sounds good to me

**Comment by DylanDylann** [comment] 2024-09-26 03:45
@justinpersaud Could you give the final assignment to @nkdengineer ? Then we can start on PR

**Comment by nkdengineer** [comment] 2024-09-30 07:42
@justinpersaud We need to introduce a new param to send the list ID of new rooms when we create this via whisper action then BE can use this list ID to create new rooms on the backend side.

**Comment by justinpersaud** [comment] 2024-10-01 23:02
@nkdengineer do you have a suggested name for this new param you're proposing?

**Comment by nkdengineer** [comment] 2024-10-02 03:05
@justinpersaud I think it can be `reportIDList`

**Comment by nkdengineer** [comment] 2024-10-07 07:23
@justinpersaud friendly bump

**Comment by justinpersaud** [comment] 2024-10-08 13:27
Sorry I was out sick. I'll look into what we need to do for the backend changes to get this out.

**Comment by justinpersaud** [comment] 2024-10-10 16:40
Sorry, now that I am looking into this a bit more, what are we expecting the outcome will be in the event that there is a collision on the room name if we try to create a room offline and it was already created?

**Comment by Christinadobrzyn** [comment] 2024-10-15 08:46
@nkdengineer can you take a peek at these questions when you have a moment? TY! https://github.com/Expensify/App/issues/49544#issuecomment-2405586903

**Comment by nkdengineer** [comment] 2024-10-15 09:29
@justinpersaud If the report was created, please send the `preexistingReportID` as the existing `reportID` for the report data of the `reportID` according to the room name in the API param. And then frontend already have the logic the clear the optimistic report.

**Comment by DylanDylann** [comment] 2024-10-17 02:36
@justinpersaud Could you help to check the above comment? Thanks

**Comment by justinpersaud** [comment] 2024-10-22 12:55
I'm wrapping up some other tasks right now internally, but hoping to look at the backend changes required later this week

**Comment by DylanDylann** [comment] 2024-10-28 07:05
@justinpersaud Kindly bump

**Comment by justinpersaud** [comment] 2024-10-28 16:52
Looked at the backend change just now and see we are defaulting to workspace visibility as we reported here, but I am asking if there is a specific reason why in our product channel

**Comment by justinpersaud** [comment] 2024-10-28 18:05
@DylanDylann @nkdengineer I am newer to working on these proposals so you'll have to bear with me here, but why are we passing in `reportIDList`, implying we would pass a number of reportIDs to the backend, right?

Won't we ever only be sending a single reportID to the backend to be created? Or are we going to queue up a backend call to `ResolveActionableReportMentionWhisper` with multiple reportIDs?

**Comment by Christinadobrzyn** [comment] 2024-10-29 06:16
@DylanDylann and @nkdengineer can you follow up on this - https://github.com/Expensify/App/issues/49544#issuecomment-2442281063

**Comment by justinpersaud** [comment] 2024-10-29 17:10
Hey all,

I circled back internally and discovered this feature is actually working as designed. We want the visibility of rooms to always be set to workspace, regardless of where it is created by default.

Thanks for the initial work and investigation. I'll leave it with @Christinadobrzyn for any outstanding payment for work that was already done.

**Comment by DylanDylann** [comment] 2024-10-30 01:21
@Christinadobrzyn From https://expensify.slack.com/archives/C02NK2DQWUX/p1723055151068559?thread_ts=1723015261.405329&cid=C02NK2DQWUX, I think we should get full compensation

**Comment by Christinadobrzyn** [comment] 2024-10-30 01:47
Okay sounds reasonable since the proposals were reviewed and the PR was created. 

Payouts due:

- [X] Contributor: $250 @nkdengineer (paid in Upwork - https://www.upwork.com/nx/wm/offer/104139931)
- [X] Reviewer: $250 @DylanDylann (paid in Upwork - https://www.upwork.com/nx/wm/workroom/38546784/details)

No regression test needed. Closing this out!

**Closed by Christinadobrzyn** 2024-10-30 01:47 UTC
Labels: Reviewing, External, Weekly, Bug
