### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] BA - Part of the screen shakes when entering an address offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29030] opened 2023-10-06 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com or open Desktop or iOS or Android App
2. Login with expensifail account
3. Create new or go to existing workspace
4. Go to Workspace > Bank Account
5. Select any connection option
6. Follow the flow until 'Company information' and 'Personal Information' pages
7. Go Offline
8. Enter address in 'Company address' line on 'Company information' page
9. Enter address in 'Personal address' line on 'Personal Information' page

## Expected Result:
The user enters the address without any visible errors

## Actual Result:
Part of the screen under address line shakes when entering an address offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79.3

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/463e76cc-5b97-4b22-9168-1afbc62aec40

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fd62647afbb5093</li>
        <li>Upwork Job ID: 1710372606170464256</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27097586</li>
<li>shubham1206agra | Contributor | 27097587</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-06 19:13
Not reproduced in Prod

https://github.com/Expensify/App/assets/115492554/6d68710a-c37a-4da4-af88-ff871f927a25

**Comment by shubham1206agra** [comment] 2023-10-07 03:29
Well this is odd, I am unable to repro this. Can someone else repro this?
cc @CortneyOfstad @marcochavezf @mollfpr 
https://github.com/Expensify/App/assets/58412969/dfca3a5f-05a8-4220-b72d-f8e96917fcc5

**Comment by shubham1206agra** [comment] 2023-10-07 05:02
@tienifr I will handle this.

**Comment by shubham1206agra** [comment] 2023-10-08 06:30
@mountiny This upstream fix will fix the problem
https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/914

**Comment by mollfpr** [comment] 2023-10-09 05:31
@shubham1206agra Is this issue regression from your PR? If yes, then the assigned C+ in the PR should be assign to this issue.

cc @marcochavezf @CortneyOfstad

**Comment by shubham1206agra** [comment] 2023-10-09 05:39
Not really a regression
Cause problem is stemming from upstream and not directly related to our problem

**Comment by mountiny** [comment] 2023-10-09 09:52
This appeared after pr from @shubham1206agra so assigning to handle it without the bounty expectation.

I have removed a deploy blocker label too because the behaviour is very minor issue

**Comment by CortneyOfstad** [comment] 2023-10-18 20:14
I am heading OoO until Oct 25, so reassigning BZ to keep an eye on things while I am gone 👍

**Comment by CortneyOfstad** [comment] 2023-10-25 18:35
Hey, I am back @NicMendonca so I can take this over again — thanks for holding down the fort while I was gone!

**Comment by CortneyOfstad** [comment] 2023-10-31 15:29
@mollfpr @shubham1206agra just checking to see where we are at with this — thanks!

**Comment by mollfpr** [comment] 2023-11-01 15:06
@CortneyOfstad The PR is merged and it's on QA now.

**Comment by CortneyOfstad** [comment] 2023-11-08 15:25
Payment is set for tomorrow — @mollfpr and @shubham1206agra any update on the checklist above?

**Comment by mollfpr** [comment] 2023-11-08 16:59
> [] The PR that introduced the bug has been identified. Link to the PR:
 [] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. The fix is on the upstream.

> [] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[] Determine if we should create a regression test for this bug.
 [] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open Expensify App
2. Login with any account
3. Create a new or go to an existing workspace
4. Go to Workspace > Bank Account
5. Select any connection option
6. Follow the flow until the 'Company Information' and 'Personal Information' pages
7. Go Offline
8. Enter the address in the 'Company address' line on the 'Company information' page
9. Verify the form is not jumping
10. 👍 or 👎

**Comment by mollfpr** [comment] 2023-11-08 16:59
@CortneyOfstad Could you help with the payment summary? Thank you!

**Comment by CortneyOfstad** [comment] 2023-11-09 18:45
Had to create a new job posting in Upwork — https://www.upwork.com/jobs/~015d08915af33b19fc

@mollfpr @shubham1206agra I invited both of you to the knew job. Please let me know as soon as you both accept 👍

**Comment by mollfpr** [comment] 2023-11-09 18:57
Hi @CortneyOfstad I'll do manual request in NewDot, so I just need the payment summary. Thank you!

**Comment by shubham1206agra** [comment] 2023-11-10 02:56
> Had to create a new job posting in Upwork — https://www.upwork.com/jobs/~015d08915af33b19fc
> 
> @mollfpr @shubham1206agra I invited both of you to the knew job. Please let me know as soon as you both accept 👍

Done

**Comment by CortneyOfstad** [comment] 2023-11-13 17:56
Alright @shubham1206agra you have been paid! @mollfpr creating the payment summary now — sorry for the delay!

**Comment by CortneyOfstad** [comment] 2023-11-13 17:56
## Payment Summary

 Contributor that fixed the issue — @shubham1206agra paid $500 in Upwork as Contributor
 Contributor+ that helped on the issue and/or PR — @mollfpr to be paid $500 in NewDot as C+

**Comment by CortneyOfstad** [comment] 2023-11-13 17:59
Regression test completed here — https://github.com/Expensify/Expensify/issues/336021

**Closed** 2023-11-13 17:59 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-13 18:45
$500 payment approved for @mollfpr based on summary above.
