### ISSUE TITLE
[$2000] Chat - Previously enter password disappears after second tap on eye icon and 1 more character

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21730] opened 2023-06-27 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21367

## Action Performed:
1. Login to NewDot
2. Open chat
3. Tap password protected pdf
4. Tap Enter password
5. Type several characters
6. Tap Icon to view
7. Tap Icon to hide
8. Type one more additional character

## Expected Result:
Previously entered password should stay

## Actual Result:
Previously entered password disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e039c15e-0b76-41d8-9f80-1e6489592dc9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182f352a9471319ec</li>
        <li>Upwork Job ID: 1679228827688402944</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-07-10 12:23
@lanitochka17 are you still able to reproduce this behavior? If not, I'll close the issue.

**Comment by johncschuster** [comment] 2023-07-11 14:03
Ok cool. Thanks for calling that out, @aimane-chnaif!

**Comment by AirBorne04** [comment] 2023-07-13 00:13
Hi there,

after investigation the issue seems to be that the TextInput on iOS is automatically clearing the text when it is getting new focus, with `secureTextEntry` enabled. Therefore I propose not to use the native functionality but rather handle the text display in a way where the text is exchanged for bullets when the password is hidden.

**Comment by AirBorne04** [comment] 2023-07-13 00:17
Contributer details
Your Expensify account email: daniel.freese@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ffe0129c64229195

**Comment by abdulrahuman5196** [comment] 2023-07-13 20:25
Could you provide more information on how you intend to solve this issue? @AirBorne04 

Kindly propose the solution with the use of proposal template as per - https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by AirBorne04** [comment] 2023-07-14 08:45
## Proposal
[Updated](https://github.com/Expensify/App/issues/21730#issuecomment-1633358577)

updated as per guidelines @abdulrahuman5196

**Comment by shubham1206agra** [comment] 2023-07-14 11:06
@abdulrahuman5196 Can you wait some time before reviewing?
I am looking to fix the `TextInput` component by introducing some custom change in the default behavior.

**Comment by shubham1206agra** [comment] 2023-07-14 14:43
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Chat - Previously enter password disappears after second tap on eye icon and 1 more character

### What is the root cause of that problem?

Due to implementation of `secureTextEntry`, everytime `secureTextEntry` is `true`, iOS triggers clearing of input on beginEditing, that's why input text is getting cleared. Though, it might be security purposes, it may create problems to the user comfort.

### What changes do you think we should make in order to solve the problem?

By injecting (patching) the logic of `setSecureTextEntry` in `RCTUITextField` file by the following:

```objc
- (void)setSecureTextEntry:(BOOL)secureTextEntry
{
  if (self.secureTextEntry == secureTextEntry) {
    return;
  }

  [super setSecureTextEntry:secureTextEntry];

  // Fix for trailing whitespate issue
  // Read more:
  // https://stackoverflow.com/questions/14220187/uitextfield-has-trailing-whitespace-after-securetextentry-toggle/22537788#22537788
  NSAttributedString *originalText = [self.attributedText copy];
  self.attributedText = [NSAttributedString new];
  self.attributedText = originalText;

  if (self.isFirstResponder) {
    [self becomeFirstResponder];
  }
}

- (BOOL)becomeFirstResponder
{
  BOOL success = [super becomeFirstResponder];
  if (self.secureTextEntry && self.attributedText.string.length > 0)
  {
    NSAttributedString *originalText = [self.attributedText copy];
    [self deleteBackward];
    self.attributedText = originalText;
  }
  return success;
}
```

By doing this, we are making sure that on making `secureTextEntry` to `true`, we are restoring the value by first doing a backspace and then inserting the string correctly. 

This solution will have no impact on any other property and styles.

### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment] 2023-07-17 14:23
@abdulrahuman5196 what do you think of the above proposals? Are they sufficient, or should we keep looking?

**Comment by abdulrahuman5196** [comment] 2023-07-19 16:11
Taking another look into the proposals now

**Comment by abdulrahuman5196** [comment] 2023-07-19 16:26
@johncschuster Are you able to repro the issue? I tried in both ios safari and ios native, not seeing this issue. Do I need to have any iOS preference set?
Also @shubham1206agra @AirBorne04

**Comment by shubham1206agra** [comment] 2023-07-19 16:52
> @johncschuster Are you able to repro the issue? I tried in both ios safari and ios native, not seeing this issue. Do I need to have any iOS preference set? Also @shubham1206agra @AirBorne04

Still able to reproduce it on iOS native. This should be there as it is default nature on iOS by Apple.

**Comment by shubham1206agra** [comment] 2023-07-20 09:03
> > @johncschuster Are you able to repro the issue? I tried in both ios safari and ios native, not seeing this issue. Do I need to have any iOS preference set? Also @shubham1206agra @AirBorne04
> 
> Also not seeing this issue on IOS native or mweb.

I don't why you can't see this. This is the default behaviour of iOS of using `secureTextEntry`. For proof, I will attach the proof with timestamp.

https://github.com/Expensify/App/assets/58412969/3eddf51d-cf7f-45c4-97e0-5c804c731da0

**Comment by shubham1206agra** [comment] 2023-07-20 16:56
@abdulrahuman5196 Can you review now?

**Comment by johncschuster** [comment] 2023-07-22 12:16
bump @abdulrahuman5196

**Comment by shubham1206agra** [comment] 2023-07-22 15:36
> Thanks @shubham1206agra, I also see this happening. I did some digging and this is not actually a bug it is the way it is intended to work on iOS native. Changing this in some way will change the platforms expected behaviour.

I think it's not about iOS native implementation but cross platform experience should be the same, and clearing of textinput on switching 👁️ has different experience on different platforms

So we might classify this as bug

**Comment by shubham1206agra** [comment] 2023-07-22 15:57
> > > Thanks @shubham1206agra, I also see this happening. I did some digging and this is not actually a bug it is the way it is intended to work on iOS native. Changing this in some way will change the platforms expected behaviour.
> > 
> > 
> > I think it's not about iOS native implementation but cross platform experience should be the same, and clearing of textinput on switching 👁️ has different experience on different platforms
> > So we might classify this as bug
> 
> Not exactly, in many cases we let consistency go across platforms in order adhere to platform behaviour. If this is how other iOS apps are behaving the user on iOS will expect this and therfore no change is needed.
> 
> And I tend to agree with the iOS devs here, when you are typing into a secure textfield you only see the last character for a second. So if the user goes back to edit it he/she would have to remember exactly what they typed, which is not the case often. Hence, it clears everything to avoid users constantly sending wrong secure data.

Not really

I think if iOS safari does not enforce this rule, so user might get different experience on the same device depending where they are using the app.

And for the iOS devs thing, I think that if I want to see the password, it should not be cleared. If I got my textinput cleared for seeing the password, then whats the point of seeing it in the first place if I know it will be cleared on next character typing.

And I also think that Android does not enforce the same policy, and there's that.

**Comment by AirBorne04** [comment] 2023-07-23 06:28
@shubham1206agra it is not clearing on reveal, just clearing on hiding and than next key input

**Comment by shubham1206agra** [comment] 2023-07-23 06:29
> @shubham1206agra it is not clearing on reveal, just clearing on hiding and than next key input

Yes I know that

**Comment by abdulrahuman5196** [comment] 2023-07-26 16:09
Will check on repro steps again today and will do a another round of review

**Comment by shubham1206agra** [comment] 2023-07-27 07:16
<img width="690" alt="image" src="https://github.com/Expensify/App/assets/58412969/db1fcf73-469a-45ab-baca-5f9a4be60fc4">

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:47
Wasn't able to repro last time as well. Will Reviewing today and if not reproducible will set next steps based on the same

**Comment by johncschuster** [comment] 2023-08-01 23:27
@abdulrahuman5196 thanks for the additional review! What are the next steps here?

**Comment by abdulrahuman5196** [comment] 2023-08-03 14:58
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-03 15:00
Yeah. I am able to reproduce now. For me mostly if I do type and press icon faster I am able to reproduce this issue.

**Comment by abdulrahuman5196** [comment] 2023-08-03 15:26
On @AirBorne04 's proposal here https://github.com/Expensify/App/issues/21730#issuecomment-1633358577. It is one way to think of changing characters to bullets on typing. But it seems to be more of a work around solution IMO and defeats the purpose of secureTextEntry.

**Comment by abdulrahuman5196** [comment] 2023-08-03 15:38
@shubham1206agra 's proposal here. 
You have mentioned the input is cleared during `iOS triggers clearing of input on beginEditing` but in the proposal you are storing the attributedText on secureTextEntry change and setting it again in `becomeFirstResponder`, but this becomeFirstResponder will be called as soon as focused. 
Why would this fix something that is clearing on beginEditing as you had mentioned? The root cause and solution doesn't match or lagging more information. Could you kindly check and update accordingly?

**Comment by abdulrahuman5196** [comment] 2023-08-03 15:40
@johncschuster Since this issue is already crossed WAQ, should we involve expert contributors to check if they have any proposals?

Meanwhile @shubham1206agra could provide more information. Or should we wait?

**Comment by shubham1206agra** [comment] 2023-08-03 16:49
> @johncschuster Since this issue is already crossed WAQ, should we involve expert contributors to check if they have any proposals?
> 
> Meanwhile @shubham1206agra could provide more information. Or should we wait?

@abdulrahuman5196 I will post the clarification tomorrow.

**Comment by johncschuster** [comment] 2023-08-03 22:06
Do we feel the clarification will change the outcome of needing an expert contributor? If so, I'll wait, otherwise, let's get one assigned now.

**Comment by shubham1206agra** [comment] 2023-08-04 12:48
> Do we feel the clarification will change the outcome of needing an expert contributor? If so, I'll wait, otherwise, let's get one assigned now.

@johncschuster I don't think so the expert contributor will tell you a different solution for this. I have tried all kinds of solutions, and there are 2 kinds of solutions right now (apart from the bullet-like workaround suggested by @AirBorne04 ). 
One is mentioned here https://github.com/facebook/react-native/issues/35668, but this solution has many issues.
1. It circumvents RN's implementation of text updation completely, which has many event-related calls, such as `_onTextInput`, `_onChange`, and `_onSelectionChange`, which can be important to Native implementation.
2. It will be applied to all `TextInput`, whether single-line or multi-line TextInput, and has problems with some languages' text input.

I suggested another one. It overcomes the problems of the previous ones by doing some extra manipulation during `becomeFirstResponder` because this is the last place we have the value of text before toggling (more specifically, before marking the textinput to clear values on the next input).

On setting `secureTextEntry` or calling `becomeFirstResponder` kind of marks dirty, i.e., on the next input event it checks the value of `secureTextEntry`. If it is true, it will reset the input text. Otherwise, it will not.

@abdulrahuman5196 I think I have written beginEditing by mistake because I inferred the root cause incorrectly at that time. Now, I guess you got the root cause correct. 

About `you are storing the attributedText on secureTextEntry change and setting it again in becomeFirstResponder`

The first store you see happens to solve another issue, which is done by RN Team only. And another one is done by me. I think this has to happen in `becomeFirstResponder` as after this method, it is very difficult to distinguish between input events done by the user and inputs done as the result of `secureTextEntry`.

PS: We are calling `becomeFirstResponder` inside `setSecureTextEntry` only when the textinput is `firstResponder` to ensure that we don't accidentally change the focus of the input when not focused.

@johncschuster If you are satisfied with my answer, you can proceed with my proposal. If you have any other questions, please ask.

**Comment by johncschuster** [comment] 2023-08-07 21:42
@abdulrahuman5196 what are your thoughts on the above?

**Comment by abdulrahuman5196** [comment] 2023-08-08 18:01
@shubham1206agra I am still not convinced.
The reason is that the text is disappearing when we type a character not just pressing on the input(becomeFirstResponder would called as soon the component become focus). This means even normally after  becomeFirstResponder will have proper attributedText. So I doubt if the solution would work.
And why are we doing a `[self deleteBackward];` Was this solution working locally for you?

**Comment by shubham1206agra** [comment] 2023-08-09 01:26
> @shubham1206agra I am still not convinced.
> The reason is that the text is disappearing when we type a character not just pressing on the input(becomeFirstResponder would called as soon the component become focus). This means even normally after  becomeFirstResponder will have proper attributedText. So I doubt if the solution would work.

Yes, on focus it will call becomeFirstResponder. But it will try to clear text after typing any letter after focus. 

I will post an example today for the same.

> And why are we doing a `[self deleteBackward];` Was this solution working locally for you?

To trigger all clearing calls that happens on using secureEntryText. Then reinserting the text.
Yes it's working for me.

**Comment by shubham1206agra** [comment] 2023-08-09 06:27
@abdulrahuman5196 See this

https://github.com/Expensify/App/assets/58412969/96f60057-bad3-42c2-9880-4223fb4d7cbf

**Comment by SosenWiosen** [comment] 2023-08-09 12:28
Hi, I'm from Software Mansion, an expert agency. I will investigate this more closely and try to help you close out this issue :)

**Comment by johncschuster** [comment] 2023-08-09 14:56
Thanks for raising this, @SosenWiosen! I didn't realize this was native behavior. With that in mind, I agree that we can close this out.

**Closed** 2023-08-09 14:56 UTC
Labels: Engineering, Daily, Internal, Bug
