### ISSUE TITLE
[$500]  IOU - avatar icon & names are showing incorrectly in IOU title (after requesting an IOU amount and then changing the IOU amount after)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27398] opened 2023-09-14 01:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money
4. Enter an amount
5. Tap next
6. Select a contact
7. Tap request amount
8. Note there are 2 distinct avatar icon and user names above IOU transaction ("created" and "to whom" requested), which is expected! 
9. Tap on the IOU to open details page, and verify the 2 users avatars and names are unique and correct ✅ 
10. Again tap IOU in IOU report page
11. Tap amount
12. Change the amount
13. Save the amount
14. Navigate back to DM mentioned in step 5 by tapping header "from" field user
15. Note 2 profile avatars and user names above IOU transaction are now showing the same avatars/names.

## Expected Result:
Both user names and profile icons should show the unique individuals involved before/after making an IOU request or modifying the amount of IOU.

## Actual Result:
If you make an IOU request between user 1 and user 2, and then you modify the amount of the IOU, we show the same avatar and user name in the IOU title (e.g. from the chat itself).

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1103c410-654c-406a-bdef-a43327f84992

https://github.com/Expensify/App/assets/78819774/aad1bf0e-9fcd-4778-997e-baeda5165a0f

**Issue reported by:** Applause - Internal team

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e06448ae1b3d3b1b</li>
        <li>Upwork Job ID: 1704558260088233984</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26899972</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-09-14 03:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After change the amount of money request, requester's profile icon & name is shown twice in chat report

### What is the root cause of that problem?

We show avatars in [ReportActionItemSingle](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemSingle.js) component

In our case, we show IOU report preview in chat report. For IOU report preview, we should show avatars of manager(to whom) and owner(created).

Let's take a look at the component
In this issue, `displayAllActors` is true and `secondaryAvatar` would be the avatar of the owner of iou report. This is fine
https://github.com/Expensify/App/blob/8d7928d0172b83d465b8857922cd47a231b77c5d/src/pages/home/report/ReportActionItemSingle.js#L117-L125

The first avatar is the actor of the action
https://github.com/Expensify/App/blob/8d7928d0172b83d465b8857922cd47a231b77c5d/src/pages/home/report/ReportActionItemSingle.js#L129

This is wrong. The actor of the action is the creator of the money request and so same as the owner of iou report.
This is the root cause

**Note**: Why the avatars are shown correctly after the money request is sent?
We set the optimistic report action for chat https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/libs/actions/IOU.js#L462. As you can see, we set the `actorAccountID` correctly here, but `RequestMoney` API sets this value with the managerID. That's why we can see the correct avatars at the first.
After `EditMoneyRequest` API is called, it sets the right `actorAccountID` value and we can see this issue


### What changes do you think we should make in order to solve the problem?

We need to show the manager of the money request action for the first icon. If `displayAllActors` is true, change the first avatar with the manager's one

```
    if (displayAllActors) {
        // Show the manager avatar for IOU report preview
        if (props.iouReport.managerID && props.personalDetailsList[props.iouReport.managerID]) {
            actorAccountID = props.iouReport.managerID;
            const managerDetails = props.personalDetailsList[props.iouReport.managerID];
            avatarSource = UserUtils.getAvatar(managerDetails.avatar, props.iouReport.managerID);
            primaryDisplayName = lodashGet(managerDetails, 'displayName', '');
        }
        
        ... ...
    }
```

This works as expected

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/921b4e3f-7b7d-4169-a805-deabd558f77a

</details>


### What alternative solutions did you explore? (Optional)

**Comment by michaelhaxhiu** [comment] 2023-09-20 18:08
Reproduced, but this GH body needs a little clarification

**Comment by michaelhaxhiu** [comment] 2023-09-20 18:15
Updated GH details for clarity! @burczu we have a proposal above ready for review already from @s-alves10

**Comment by burczu** [comment] 2023-09-25 08:36
@michaelhaxhiu Sorry for the delay - I was dealing with an issue building the App for Android... but it's finally sorted, so I'll take a look at this one soon.

**Comment by burczu** [comment] 2023-09-25 11:56
I've just checked the proposal from @s-alves10 and it looks like it identifies the issue correctly and fixes it. I think we can proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment] 2023-09-27 07:56
This issue was fixed in [this PR](https://github.com/Expensify/App/pull/27912) already

**Comment by burczu** [comment] 2023-09-27 08:40
@s-alves10 Thanks for pointing this out - I'll try to confirm it later.

**Comment by michaelhaxhiu** [comment] 2023-09-28 14:23
I'm re-assigning this to another BZ as part of my preparation for Sabbatical (starting Friday).

**Next steps:**
- Let's confirm if this bug is still reproducible. @burczu [offered to ](https://github.com/Expensify/App/issues/27398#issuecomment-1736959974) do this 🙏 
- Depending on outcome of that verdict, there's to roads forward:
(A) If the bug was fixed, let's offer partial compensation to contributor and C+ (I would suggest 25% of bounty given the PR wasn't drafted yet). Then let's close this.
(B) If bug was not fixed, let's push this forward for a complete fix and pay like normla.

**Comment by michaelhaxhiu** [comment] 2023-09-28 14:23
cc @lanitochka17 if you don't mind reproducing this again too, that would be helpful

**Comment by s-alves10** [comment] 2023-09-28 14:50
[The PR](https://github.com/Expensify/App/pull/27912) I mentioned [here](https://github.com/Expensify/App/issues/27398#issuecomment-1736892232) wasn't deployed to staging yet.

**Comment by burczu** [comment] 2023-10-02 11:16
@s-alves10 @michaelhaxhiu @lschurr Just checked once again all the reproduce steps and it seems like it is indeed fixed now.

**Comment by lschurr** [comment] 2023-10-04 14:55
Ok, great. I'll take a look today and determine payout amounts.

**Comment by lschurr** [comment] 2023-10-09 16:52
@thienlnam ideas for this one?

**Comment by lschurr** [comment] 2023-10-12 15:33
Ah, I missed this: https://github.com/Expensify/App/issues/27398#issuecomment-1753477263

Closing.

**Closed by lschurr** 2023-10-12 15:33 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Overdue, Bug
