### ISSUE TITLE
Redbrick path broken for Settings > Workspaces

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#12327] opened 2022-10-31 23:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

The red dots showing the path of an error is interrupted

## Action Performed:
**Using an account that is a domain**
1. Create a workspace in New Dot
2. Go to old dot and set the workspace as the preferred policy of a domain's group
4. In new dot, try to delete the workspace, this will cause the API to throw an error
5. Check that the red bricks path is broken at the Settings level. The Workspaces entry should have a red dot.

https://user-images.githubusercontent.com/87341702/199128893-e4f819ab-7df2-428c-81c5-9ff939e46643.mov

## Expected Result:
The should have been a red dot next to the `Workspaces` entry in the Settings menu

## Actual Result:
No red dot there

## Workaround:
The user can use the app as normal, it is just bad feedback on where the error is.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment] 2022-11-01 12:16
hey Aldo - I'm just going through your steps to try and reproduce, what does this mean?

> Go offline with the incognito browser

How do I go offline on a specific browser window?

**Comment by trjExpensify** [comment] 2022-11-01 12:51
I typically use like web/mobile, but you can open the JS console in the incognito browser > Network tab > then next to the wifi symbol switch the dropdown to `Offline` to follow the steps here: 

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/16232057/199236106-1a7424d5-9019-41fa-bb2e-d76424a9414f.png">

**Comment by chiragsalian** [comment] 2022-11-01 18:00
Once the PR is merged let's remember to also add regressions steps for QA to test this flow since I've told them to test RBR on settings -> workspaces if there is a member error. So it will be nice if they add this flow as well to their regression testing.

**Comment by JmillsExpensify** [comment] 2022-11-01 19:56
+1000. Should we proactively open that issue back up?

**Comment by chiragsalian** [comment] 2022-11-01 20:13
Which issue, the one to add QA regression steps? If so then no. I would rather create new issues to add QA steps to keep the process cleaner and easier to process through. Steps mentioned [here](https://stackoverflow.com/c/expensify/questions/363).

**Comment by JmillsExpensify** [comment] 2022-11-01 23:10
Cool, yeah I was referring to the previous one.

**Comment by aldo-expensify** [comment] 2022-11-02 01:36
PR ready for review

**Comment by miljakljajic** [comment] 2022-11-04 12:07
Hey - just kicking off the above checklist. Which PR caused this bug? What do you think we could have done differently in the original PR to prevent this bug from being introduced - and who is responsible for adding the appropriate test?

**Comment by chiragsalian** [comment] 2022-11-04 17:57
> Which PR caused this bug?

My PR here - https://github.com/Expensify/App/pull/11784 caused the bug

> What do you think we could have done differently in the original PR to prevent this bug from being introduced

Not sure, I missed testing for this usecase. There are a number of error usecases and while we did test for RBR I didn't realize this one would show up visually different.

> and who is responsible for adding the appropriate test?

I think its best for @aldo-expensify to add this scenario to our regression tests since he found it. Is that alright with you aldo?

**Comment by aldo-expensify** [comment] 2022-11-04 18:09
> I think its best for @aldo-expensify to add this scenario to our regression tests since he found it. Is that alright with you aldo?

Sure! we already have a test that triggers an error at the level of the workspace: https://github.com/Expensify/Expensify/issues/233249#issuecomment-1282947636

I think we just have add step to it to verify that the red brick path is fine at each level.

do you think that makes sense?

**Comment by aldo-expensify** [comment] 2022-11-04 22:25
Created issue requesting applause to update the test: https://github.com/Expensify/Expensify/issues/240986

**Comment by aldo-expensify** [comment] 2022-11-04 22:25
Should we close this?

**Comment by aldo-expensify** [comment] 2022-11-04 22:35
Hmm, just saw that this other PR https://github.com/Expensify/App/pull/12117/files from @Justicea83 fixed it the other way I mentioned [here](https://github.com/Expensify/App/issues/9971#issuecomment-1297811429). This ended up making the workspace have an extra red dot here:

<img src="https://user-images.githubusercontent.com/87341702/199128189-f05ee54f-a52b-45f0-97ce-49ab6a17af87.png">

I think we should revert change because the dot there means to me that there will be an error when we go in that workspace.

**Comment by chiragsalian** [comment] 2022-11-04 23:30
> Should we close this?

**Comment by aldo-expensify** [comment] 2022-11-04 23:48
> Unless maybe he had a workspace and member error?

> > Should we close this?
> 
> It should auto-close when your PR hits production so nothing extra needs to be done here. If it doesn't close once your code is live then yeah we can manually close this.

Lol, you are right

> I don't think it should be both since that is confusing. Unless maybe he had a workspace and member error?

I agree. I'll ask in the slack you linked https://expensify.slack.com/archives/C01GTK53T8Q/p1666955764560879

**Comment by aldo-expensify** [comment] 2022-11-05 00:23
Fixing red indicator: https://github.com/Expensify/App/pull/12491

**Comment by aldo-expensify** [comment] 2022-11-16 17:34
No overdue, the PR was merged yesterday

**Comment by miljakljajic** [comment] 2022-11-17 16:57
Apologies for the hold up on the regression test but I am about to go OOO until Tuesday. I will put the tests in then. Since there are no external contributors on this issue we don't need to pay anyone.

**Comment by aldo-expensify** [comment] 2022-11-17 18:04
@miljakljajic we have to pay the C+ for the PR reviews, more info here: https://github.com/Expensify/App/pull/12329#issuecomment-1317500038

**Comment by miljakljajic** [comment] 2022-11-18 10:12
Ah apologies I missed the linked PR. I have asked for help [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1668764863253439) but I haven't had an answer yet and I am OOO, I'll reassign so the C+ isn't waiting longer for payment.

**Comment by dylanexpensify** [comment] 2022-11-21 11:18
paid this out

**Closed by dylanexpensify** 2022-11-21 11:18 UTC
Labels: Reviewing, Daily, Internal, Bug
