### ISSUE TITLE
[$500] Assign Task - Task completion and reopening notification not translated in Share Somewhere section

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25633] opened 2023-08-21 23:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Assign Tasks".
2. Add a title, assignee, and share somewhere, then confirm the task.
3. Go to settings > preference > change language to Spanish.
4. Click on the plus sign again and select "Assign Tasks" > Title > Search for the email you assigned the task to in the Share Somewhere section

## Expected Result:
The task completion and reopening notification should be translated in the Share Somewhere section as per user preference, just like in LHN and Assigned Task

## Actual Result:
The task completion and reopening notification are not translated in the Share Somewhere section, causing inconsistency in language usage

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.56-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/46f8ab64-31e2-4a2a-9e94-8445a414f17e

https://github.com/Expensify/App/assets/78819774/f5288e6b-abf5-475b-bea3-223819d69865

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691775469383549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016eac5381208cd4cb</li>
        <li>Upwork Job ID: 1698533354550611968</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-08-21 23:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task completion and reopening notification not translated in Share Somewhere section

### What is the root cause of that problem?
The translation for complete task and re-open task work well in LHN because we have logic to update alternativeText in getOptionData for LHN options 

https://github.com/Expensify/App/blob/08b75f39d32ab5ecfa1577ebdbb79c3fb24797fb/src/libs/SidebarUtils.js#L300-L304

But when creating option for share destination, we don't have any logic to update the translation like we did in LHN
### What changes do you think we should make in order to solve the problem?
I suggest that when creating option for share destination, we should update translation if the last actionName is complete task or reopen task (It seems we miss translate cancelled task message in LHN)
1. we need to translate cancelled task in LHN 

https://github.com/Expensify/App/blob/08b75f39d32ab5ecfa1577ebdbb79c3fb24797fb/src/libs/SidebarUtils.js#L300-L304

add condition: 
```
else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.canceled')}: ${report.reportName}`;
            }
```
2. Update complete task, reopen task and cancel task in share destination options
In here: https://github.com/Expensify/App/blob/08b75f39d32ab5ecfa1577ebdbb79c3fb24797fb/src/libs/OptionsListUtils.js#L505
we should add 
```
if ((result.isChatRoom || result.isPolicyExpenseChat || result.isThread || result.isTaskReport)) {
            const lastAction = visibleReportActionItems[report.reportID];
            if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.RENAMED) {
                const newName = lodashGet(lastAction, 'originalMessage.newName', '');
                result.alternateText = Localize.translate(preferredLocale, 'newRoomPage.roomRenamedTo', {newName});
            } else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKREOPENED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.reopened')}: ${report.reportName}`;
            } else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.completed')}: ${report.reportName}`;
            } else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.canceled')}: ${report.reportName}`;
            }
}
```
With this approach, we need to define visibleReportActionItems as we did in SidebarUtils.
We also can consider to create utils function to update alternative text to avoid duplicated code
### Result



<img width="924" alt="Screenshot 2023-08-18 at 10 25 20" src="https://github.com/Expensify/App/assets/141406735/92654349-2f20-4f4c-97e7-44c3264be9a0">

**Comment by esh-g** [comment] 2023-08-21 23:47
# Proposal

## Please re-state the problem we are trying to fix
For task reports, actions like reopening and completing are not translated to Spanish in share options but are translated in LHN, therefore, an inconsistency.

**Disclaimer:** This proposal is a little lengthy because I went into a lot of detail for the explanation please be sure to ask about any part that might be doubtful, I will be happy to explain it further.

## What is the root cause of the problem?
When creating the options to display in RHP, we are using the `report.lastMessageText` property which (for task actions like opening and reopening) is always in English. So, how are they translated in the `LHN` then? Well it's because we explicitly translate them in `SideBarUtils.js`:
https://github.com/Expensify/App/blob/aaa12f4e37c92b95c42a090889e1e4301b487e2c/src/libs/SidebarUtils.js#L297-L308

But this translation is not happening when we create options to share because that uses the method `getLastMessageTextForReport`, which in-turn returns the `report.lastMessageText`
https://github.com/Expensify/App/blob/38ed41f7c72fc52ed5e2effec9a2b510fd632d82/src/libs/OptionsListUtils.js#L490

## What changes should we make in-order to solve this?
We should stop the differential use of the `lastMessageText` because even in `sideBarUtils.js` we are using `getLastMessageTextForReport()` and then the translations are made after that. But what we should be doing is making the translations in the `getLastMessageTextForReport()` function itself which would therefore mean moving the translation logic into `getLastMessageTextForReport()` and along the way, make some optimisations to the function as well.

So after moving that logic, this is how the `getLastMessageTextForReport()` function should look like:
```js
function getLastMessageTextForReport(report) {
    const lastReportAction = _.find(
        allSortedReportActions[report.reportID],
        (reportAction, key) => ReportActionUtils.shouldReportActionBeVisible(reportAction, key) && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
    );

    let lastMessageTextFromReport = report ? report.lastMessageText || '' : '';
    const lastNonWhisper = _.find(allSortedReportActions[report.reportID], (action) => !ReportActionUtils.isWhisperAction(action)) || {};

    if (ReportUtils.isReportMessageAttachment({text: report.lastMessageText, html: report.lastMessageHtml, translationKey: report.lastMessageTranslationKey})) {
        lastMessageTextFromReport = `[${Localize.translateLocal(report.lastMessageTranslationKey || 'common.attachment')}]`;
    } else if (ReportActionUtils.isReportPreviewAction(lastReportAction)) {
        const iouReport = ReportUtils.getReport(ReportActionUtils.getIOUReportIDFromReportActionPreview(lastReportAction));
        lastMessageTextFromReport = ReportUtils.getReportPreviewMessage(iouReport, lastReportAction);
    } else if (ReportActionUtils.isModifiedExpenseAction(lastReportAction)) {
        lastMessageTextFromReport = ReportUtils.getModifiedExpenseMessage(lastReportAction);
    } else if (ReportActionUtils.isPendingRemove(lastNonWhisper)) {
        const latestVisibleAction =
            _.find(
                allSortedReportActions[report.reportID],
                (action) => ReportActionUtils.shouldReportActionBeVisibleAsLastAction(action) && !ReportActionUtils.isCreatedAction(action),
            ) || {};
        lastMessageTextFromReport = lodashGet(latestVisibleAction, 'message[0].text', '');
    } else if (ReportUtils.isChatRoom(report) || ReportUtils.isThread(report) || ReportUtils.isPolicyExpenseChat(report) || ReportUtils.isTaskReport(report)) {
        if (lodashGet(lastReportAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.RENAMED) {
            const newName = lodashGet(lastReportAction, 'originalMessage.newName', '');
            lastMessageTextFromReport = Localize.translate(preferredLocale, 'newRoomPage.roomRenamedTo', {newName});
        } else if (lodashGet(lastReportAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKREOPENED) {
            lastMessageTextFromReport = `${Localize.translate(preferredLocale, 'task.messages.reopened')}: ${report.reportName}`;
        } else if (lodashGet(lastReportAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED) {
            lastMessageTextFromReport = `${Localize.translate(preferredLocale, 'task.messages.completed')}: ${report.reportName}`;
        } else if (lodashGet(lastReportAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED) {
            lastMessageTextFromReport = `${Localize.translate(preferredLocale, 'task.messages.canceled')}: ${report.reportName}`;
        } else {
            lastMessageTextFromReport = lastMessageTextFromReport.length > 0 ? lastMessageTextFromReport : Localize.translate(preferredLocale, 'report.noActivityYet');
        }
    }
    return lastMessageTextFromReport;
}
```
This might look like a lot of changes, so here is a summary of them:
1. The default value of the `lastMessageTextFromReport` is moved from the else part to the top during the declaration of the variable itself.
https://github.com/Expensify/App/blob/2e8e699a8ba629cb9124778fc8d438d65a06367f/src/libs/OptionsListUtils.js#L390-L392
2. The whisper moderation logic mas been moved out of the else block since the default value of `lastMessageTextFromReport` is already set beforehand.
3. The translation logic from `sideBarUtils.js` has been added as the last condition.
4. A translation for `CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED` has also been added which was not present in the `sideBarUtils.js` before.

This function now looks much cleaner than before and all the translation logic is also now at once place. Now, in `SideBarUtils.js`, the else condition after the translation should still remain. Therefore, the if-else block can be removed and only the following code spared: 
```js
if (!lastMessageText) {
        // Here we get the beginning of chat history message and append the display name for each user, adding pronouns if there are any.
        // We also add a fullstop after the final name, the word "and" before the final name and commas between all previous names.
        lastMessageText =
            Localize.translate(preferredLocale, 'reportActionsView.beginningOfChatHistory') +
            _.map(displayNamesWithTooltips, ({displayName, pronouns}, index) => {
                const formattedText = _.isEmpty(pronouns) ? displayName : `${displayName} (${pronouns})`;

                if (index === displayNamesWithTooltips.length - 1) {
                    return `${formattedText}.`;
                }
                if (index === displayNamesWithTooltips.length - 2) {
                    return `${formattedText} ${Localize.translate(preferredLocale, 'common.and')}`;
                }
                if (index < displayNamesWithTooltips.length - 2) {
                    return `${formattedText},`;
                }
            }).join(' ');
    }

    result.alternateText = lastMessageText || formattedLogin;
```
This code makes sure that we have `No activity Yet` text and `This is the beginning of your chat...` in the appropriate places.

**Comment by mallenexpensify** [comment] 2023-08-30 00:48
From what I can see in my tests, if the task was originally created in English, we leave it that way and don't update it.  
1. Is that true?
2. If so, is the bug or feature request to change historical data in chats from English to Spanish?

cc @tewodrosGirmaA who reported the issue

<img width="386" alt="image" src="https://github.com/Expensify/App/assets/22508304/3c0f8cf2-6882-4220-9b3f-c7249c4b6192">

**Comment by DylanDylann** [comment] 2023-08-30 02:04
@mallenexpensify 

If report action is reopened task message, the actionName is TASKREOPENED
If report action is completed task message, the actionName is TASKCOMPLETED
If report action is cancelled task message, the actionName is TASKCANCELLED
If report action is created task message (like "Assigned a task ..."), the actionName is CREATED

As I see that if the last message is TASKREOPENED, TASKCOMPLETED we will translate it in LHN (It seems that we missed TASKCANCELLED) because we can realize it by actionName of last report action. And we don't translate if the last message is "Assigned a task ..." because there is no way to know if it is a created task message

**Comment by mallenexpensify** [comment] 2023-09-04 03:09
Thanks @DylanDylann .  @Ollyws , can you please review @DylanDylann 's comment above https://github.com/Expensify/App/issues/25633#issuecomment-1698382159

Then, if you agree, can you please review their proposal above?  Thx

@slafortune  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by slafortune** [comment] 2023-09-07 14:18
It looks like we need some backend work done if this is something we will move forward with - 

>  If we want to translate "Assigned a task ..." we need to introduce new actionName for created task message with the change from BE

Adding engineering

**Comment by slafortune** [comment] 2023-09-08 17:06
Removing myself since @mallenexpensify will be back next week and I'm out on sabbatical.

**Comment by DylanDylann** [comment] 2023-09-09 15:27
@Ollyws 
>  Could we not for example check if the action is CREATED and that the current user is also the assignee then show the Assigned a task to you... message?

If user A creates a task in the chat between User A and User B and assigns to anyone. We will display "Created a task: ..." in the chat between User A and User B

If user A creates a task in the chat between User A and User B and assign to user C. We will display "Assigned a task to you ..." in the chat between user A and User C


From my view, we should support translate in 3 following cases in both LHN and Share Somewhere section:
- the actionName is TASKREOPENED
- the actionName is TASKCOMPLETED
- the actionName is TASKCANCELLED

In case the message is "Created a task: ..." or "Assigned a task to you...", currently It seems that we don't support translation from BE.

**Comment by mallenexpensify** [comment] 2023-09-11 06:23
@AndrewGable can you review the above to help decide if this can be external or not? It's *not* high priority.  Thx

**Comment by mallenexpensify** [comment] 2023-09-14 06:05
@AndrewGable, when you have a minute, can you review the above? Need to know if this should stay external or if it needs a backend fix,

**Comment by AndrewGable** [comment] 2023-09-18 09:30
@marcochavezf or @thienlnam - I'd be curious for your thoughts on how we should best handle this and if any of the existing solutions make sense.

I think the current discussion on whether we should do this translation on the front end or back end has probably been discussed previously and you might have some examples that will help us come to the correct decision in this case. Thank you!

**Comment by DylanDylann** [comment] 2023-09-18 10:09
For more information, currently from the FE side, we only support translating 3 cases:
the actionName is TASKREOPENED
the actionName is TASKCOMPLETED
the actionName is TASKCANCELLED

From FE, We don't support translating:
1. Created a task:
2. Assigned a task to

**Comment by thienlnam** [comment] 2023-09-19 04:33
There have been a few issues related to translation issues - we've largely decided to close them until we support localization in the backend as these are messages stored in the reportAction message itself

**Comment by DylanDylann** [comment] 2023-09-19 04:39
@thienlnam Currently, we are supporting translating 3 cases:
the actionName is TASKREOPENED
the actionName is TASKCOMPLETED
the actionName is TASKCANCELLED

in reportAction message, LHN. So I think we also should support translating these cases in share somewhere section for consistency.


> we support localization in the backend 

It means all task message will be translated from BE? and we will remove all translation for task message in FE, right?

**Comment by AndrewGable** [comment] 2023-09-19 06:26
Sounds like yes we should close this and when we move the translation to the backend we will remove the front end translation. 

@thienlnam - Should we be linking this case to a larger tracking issue?

**Comment by thienlnam** [comment] 2023-09-19 06:55
BE localization is a pretty far out project - I imagine when we start to support that we'll go through and address all existing cases we have now. I don't think there is a tracking issue though

**Comment by DylanDylann** [comment] 2023-09-19 08:01
I don't think this consistency is acceptable in the long time. It might confuse for user when with the same system message some places translate, some don't translate

**Comment by esh-g** [comment] 2023-09-21 00:58
@thienlnam I would ask you to once go through my [proposal](https://github.com/Expensify/App/issues/25633#issuecomment-1687208659) before deciding because in it, I have proposed to move the translation logic to `getLastMessageTextForReport()` and removing it from it's current place. Therefore, no new logic is being added and the `getLastMessageTextForReport()` is refactored to not include the "ugly" code as mentioned in a comment in that function.

**Comment by mallenexpensify** [comment] 2023-09-26 07:48
I'm unsure what the next best step is here.  Should we put this on hold pending backend localization? (then link to the tracking issue once it's created?)

**Comment by AndrewGable** [comment] 2023-09-27 19:36
Sounds like @thienlnam is saying we should not do a work around and should handle this via the API/back end. There is a question of when this will happen, but we don't know for now. So I'd close this and we can circle back on this via the API at a later date.

**Closed** 2023-10-02 13:52 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug

**Comment by tewodrosGirmaA** [comment] 2023-10-02 14:12
@mallenexpensify  am I eligible for payment ?

**Comment by mallenexpensify** [comment] 2023-10-03 19:38
@tewodrosGirmaA from [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=If%20it%27s%20a%20valid%20bug%20that%20we%20choose%20to%20resolve%20by%20deploying%20it%20to%20production%20%E2%80%94%20either%20internally%20or%20via%20an%20external%20contributor%20%E2%80%94%20then%20we%20will%20compensate%20you%20%2450%20for%20identifying%20the%20bug)
> If it's a valid bug that we choose to resolve by deploying it to production — either internally or via an external contributor — then we will compensate you $50 for identifying the bug

Since we didn't fix anything here yet, compensation is not due.  
The other consideration is, if this is already something we had planned to address at some point, then compensation isn't due.  This can be a lil tricky though because we won't always have something to point to to show proof.  It's also rare and doesn't happen that often.

**Comment by tewodrosGirmaA** [comment] 2023-10-03 19:53
@mallenexpensify OK Thank you for Replying,  No problem , I understand 😊
