### ISSUE TITLE
[$250]  WS - Receipt that was not scanned successfully is visible to WS admin 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51874] opened 2024-11-01 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5168981
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New expensify desktop app
2. go to a WS as an employee
3. submit a blurry scanned receipt
4. Log in as admin when scan is in progress
5. go to the same Ws

## Expected Result:
Only successfully scanned receipts should be visible to admins. So the blurry receipt shouldn't be available to admin in the WS while scanning

## Actual Result:
Blurry receipt is available for admin in the WS while scanning

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a542e0b2-27b2-4379-909a-eb8b221cca78

![Blurry incomplete receipt (1)](https://github.com/user-attachments/assets/c74aa1fa-efce-4046-b275-4ea7b9fec3c4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2024-11-04 11:07
@lanitochka17 what is the problem, is that the WS admin can see the receipt while it's scanning, or that the receipt is blurry? 

I don't have access to test rail so I can't check what the test is, but it doesn't seem like the admin seeing the scanning receipt that's on the workspace they're an admin for is an issue.

**Comment by lanitochka17** [comment] 2024-11-04 16:22
Screen TEst rail:
![screen 0411](https://github.com/user-attachments/assets/34e76e39-83b4-472f-a538-3bde15ef0fbd)

**Comment by sonialiap** [comment] 2024-11-06 10:56
Thanks for sharing the test :)

**Comment by FitseTLT** [comment] 2024-11-07 21:48
The test rail is expecting to not see the request that is pending scan from the admin side, in that case, we need to stop pushing the requests from BE until the scan in successful. And the title of the issue should also be updated accordingly.

**Comment by sonialiap** [comment] 2024-11-11 20:47
Team confirms that the expected behavior is 
- every chat participant can see the new receipt, even while scanning
- the admin should not be notified (chat should not be marked as unread) until they are supposed to take some action on it

@lanitochka17 based on the updated expected behavior this is not a bug, correct? The admin sees the receipt ✔️ there's a RBR for "review required" ✔️ 

If there's no bug, could we update the expected result for this test? Do you need me to open a `QA - Add/Update test to TestRail` issue?

**Comment by sonialiap** [comment] 2024-11-13 11:51
I've submitted a request to update the regression test steps in TestRail - https://github.com/Expensify/Expensify/issues/443817

**Closed by sonialiap** 2024-11-13 11:51 UTC
Labels: Daily, Bug
