### ISSUE TITLE
[HOLD for payment 2024-06-13] [HOLD for payment 2024-06-11] [HOLD #42911] Workspace chat - "Remove members" pop-up slides up from the bottom to the center

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42910] opened 2024-05-31 10:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has other members than yourself.
3. Click on the chat header.
4. Go to Members.
5. Select one user.
6. Click Remove.

## Expected Result:
"Remove members" pop-up will animate from the center (production behavior).

## Actual Result:
"Remove members" pop-up slides up from the bottom to the center.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1706c784-e64d-4d4a-8de6-15fd17ac5412

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01298e732611514290</li>
        <li>Upwork Job ID: 1797581230043860992</li>
        <li>Last Price Increase: 2024-06-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by izarutskaya** [comment] 2024-05-31 10:22
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-31 10:23
We think this issue might be related to the  #vip-vsb

**Comment by bernhardoj** [comment] 2024-05-31 12:17
The app hangs for me when pressing Remove, most likely the same root cause as https://github.com/Expensify/App/issues/42911.

**Comment by grgia** [comment] 2024-06-03 10:48
@getusha could you confirm 
https://github.com/Expensify/App/issues/42910#issuecomment-2141951312 so I can close this out, otherwise I will make external

**Comment by getusha** [comment] 2024-06-03 12:33
@grgia i think it has same root cause, we can close it and handle it one place.

**Comment by Med-azaza** [comment] 2024-06-03 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The "Remove Members" pop-up in the staging environment is animating incorrectly. It slides up from the bottom of the screen instead of animating from the center as it does in the production environment.

### What is the root cause of that problem?

The most likely cause is a discrepancy in the CSS or JavaScript code that controls the animation between the staging and production environments. This could be due to different CSS properties/incorrect javaScript trigger.

### What changes do you think we should make in order to solve the problem?

- Carefully review the CSS code responsible for the pop-up animation in both environments.
- Ensure that the staging environment's CSS matches the production environment's CSS, specifically the properties related to animating from the center.
- Examine the JavaScript code that initiates the pop-up animation.
- Confirm that it's calling the correct functions and manipulating the appropriate CSS classes to achieve the desired animation from the center.

**Comment by Med-azaza** [comment] 2024-06-03 14:27
Contributor details
Your Expensify account email: hamaaz666@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/medazaza

**Comment by mallenexpensify** [comment] 2024-06-03 19:07
Putting on hold pening
- https://github.com/Expensify/App/issues/42911

@Med-azaza , it looks like the above issue is accepting proposals, if you want to post yours there.

**Comment by roryabraham** [comment] 2024-06-03 22:14
Co-assigning because I think this will be fixed by https://github.com/Expensify/App/pull/43013. Will test to confirm.

**Comment by roryabraham** [comment] 2024-06-03 22:21
Tested, and this does not appear to be fixed by https://github.com/Expensify/App/pull/43013. It's also not hanging for me.

I'm not sure if we had any basis to think that this was related to `useResponsiveLayout` or if that's just a hunch.

**Comment by roryabraham** [comment] 2024-06-03 22:24
Ah, I see the problem. This is indeed a misuse of `useResponsiveLayout`. I can easily fix this as part of https://github.com/Expensify/App/pull/43013

**Comment by roryabraham** [comment] 2024-06-03 22:53
Updated https://github.com/Expensify/App/pull/43013 to fix this an a related (unreported) issue with the Popover component.

**Comment by roryabraham** [comment] 2024-06-06 17:05
Closing this out. It has been fixed and the only C+ payment that's due will be handled in https://github.com/Expensify/App/issues/42912

**Closed by roryabraham** 2024-06-06 17:05 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
