### ISSUE TITLE
[$1000] Opacity is too low on long Press for the links like "Forgot", "Go back" & "Back"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14467] opened 2023-01-23 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open two NewDot sessions.
2. In the first session, sign out (if you are signed in). 
3.  Enter email address and click continue. 
4. Now long press on the "Forgot" or "Go back" buttons.
5. Notice that the opacity of the buttons is very high (meaning the text fades away significantly when you long top. 
6. In the second session, go to Settings > Workspace > Click into a workspace > Connect Bank account. 
7. Click manual and enter the plaid test credentials. 
8. Click the "I accept terms of service" checkbox and notice the opacity is much more subtle than the login page. 
9. Click continue and scroll down to the bottom Company information step. Click the restricted industries checkbox and notice the opacity is similarly subtle to the step prior. 

## Expected Result:
Opacity in the application should be consistent, and more subtle than that shown on the login page. 

## Actual Result:
Opacity on login page buttons is inconsistent with other buttons in the app, and should be more subtle. 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.57-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214078333-22f3ea13-650d-41c8-9cc0-aca95790b74e.mp4

https://user-images.githubusercontent.com/43996225/214078408-cb1ac1e8-6ad0-4902-bef4-3c963f13410e.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674240052198959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144967451d0ce5878</li>
        <li>Upwork Job ID: 1619024958901145600</li>
        <li>Last Price Increase: 2023-01-27</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-01-23 18:30
Triaging: 

From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you're unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it's better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by joekaufmanexpensify** [comment] 2023-01-23 18:34
I can reproduce this on web. However, I do kind of like the feedback received when long clicking on the buttons here. Discussing further in Slack. 

![2023-01-23_13-30-11 (1)](https://user-images.githubusercontent.com/54866469/214121151-a7afe6b5-bba5-4ddf-a8ed-ac62c2a61d21.gif)

**Comment by joekaufmanexpensify** [comment] 2023-01-23 18:44
Discussing [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1674499478564499)

**Comment by joekaufmanexpensify** [comment] 2023-01-24 18:57
Adding view of opacity with checkbox on VBA flow for comparison: 

![2023-01-24_13-56-24 (1)](https://user-images.githubusercontent.com/54866469/214383599-4739f715-51ee-46ca-bcd3-7b4d3bf12e56.gif)

**Comment by joekaufmanexpensify** [comment] 2023-01-25 18:54
Still discussing in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-01-26 16:24
Okay, we discussed this in Slack, and we want to make the opacity on the back and forgot password buttons on the login page more subtle and consistent with opacity on buttons in the rest of the app. In the VBA onboarding flow (as described in OP), there are two buttons with much more subtle opacity. 

We want to standardize on that.

**Comment by joekaufmanexpensify** [comment] 2023-01-26 16:25
Thinking this can be external, but assigning to engineering to confirm!

**Comment by madmax330** [comment] 2023-01-27 17:29
Yep this can be external

**Comment by Pujan92** [comment] 2023-01-27 17:30
**Proposal**

We can apply the same `activeOpacity` to make it consistent like mentioned VBA flow checkbox label (Changed a variable name to make more generic).

```diff
diff --git a/src/styles/variables.js b/src/styles/variables.js
index 58b87782d5..c24eda3633 100644
--- a/src/styles/variables.js
+++ b/src/styles/variables.js
@@ -85,7 +85,7 @@ export default {
     INACTIVE_LABEL_TRANSLATE_Y: getValueUsingPixelRatio(16, 21),
     sliderBarHeight: 8,
     sliderKnobSize: 26,
-    checkboxLabelActiveOpacity: 0.7,
+    actionTextActiveOpacity: 0.7,
     avatarChatSpacing: 12,
diff --git a/src/components/CheckboxWithLabel.js b/src/components/CheckboxWithLabel.js
index 4c7123bd24..3ecf26eb42 100644
--- a/src/components/CheckboxWithLabel.js
+++ b/src/components/CheckboxWithLabel.js
@@ -100,7 +100,7 @@ class CheckboxWithLabel extends React.Component {
                     <TouchableOpacity
                         focusable={false}
                         onPress={this.toggleCheckbox}
-                        activeOpacity={variables.checkboxLabelActiveOpacity}
+                        activeOpacity={variables.actionTextActiveOpacity}
                         style={[
                             styles.ml3,
                             styles.pr2,
diff --git a/src/pages/signin/ChangeExpensifyLoginLink.js b/src/pages/signin/ChangeExpensifyLoginLink.js
index 8289a754d..32e02b0f5 100755
--- a/src/pages/signin/ChangeExpensifyLoginLink.js
+++ b/src/pages/signin/ChangeExpensifyLoginLink.js
@@ -41,6 +41,7 @@ const ChangeExpensifyLoginLink = props => (
         <TouchableOpacity
             style={[styles.link]}
             onPress={props.onPress}
+            activeOpacity={variables.actionTextActiveOpacity}
         >
             <Text style={[styles.link]}>
                 {props.translate('common.goBack')}
diff --git a/src/pages/signin/PasswordForm.js b/src/pages/signin/PasswordForm.js
index d984e6fd2..4c02c3b90 100755
--- a/src/pages/signin/PasswordForm.js
+++ b/src/pages/signin/PasswordForm.js
@@ -171,6 +171,7 @@ class PasswordForm extends React.Component {
                         <TouchableOpacity
                             style={[styles.mt2]}
                             onPress={this.resetPassword}
+                            activeOpacity={variables.actionTextActiveOpacity}
                         >
                             <Text style={[styles.link]}>
                                 {this.props.translate('passwordForm.forgot')}
diff --git a/src/pages/signin/ResendValidationForm.js b/src/pages/signin/ResendValidationForm.js
index 7753faa65..8887854cb 100755
--- a/src/pages/signin/ResendValidationForm.js
+++ b/src/pages/signin/ResendValidationForm.js
@@ -79,7 +79,7 @@ const ResendValidationForm = (props) => {
                 <DotIndicatorMessage style={[styles.mb5]} type="error" messages={props.account.errors} />
             )}
             <View style={[styles.mb4, styles.flexRow, styles.justifyContentBetween, styles.alignItemsCenter]}>
-                <TouchableOpacity onPress={() => redirectToSignIn()}>
+                <TouchableOpacity onPress={() => redirectToSignIn()} activeOpacity={variables.actionTextActiveOpacity}>
                     <Text style={[styles.link]}>
                         {props.translate('common.back')}
                     </Text>

```

**Comment by situchan** [comment] 2023-01-29 14:33
### **Proposal**

We can set `activeOpacity` default value of `TouchableOpacity` across the app in root level, without needing to set in every component.
I think [App.js](https://github.com/Expensify/App/blob/main/src/App.js) is a good place:
```diff
- import {LogBox} from 'react-native';
+ import {LogBox, TouchableOpacity} from 'react-native';

...

LogBox.ignoreLogs([
    // Basically it means that if the app goes in the background and back to foreground on Android,
    // the timer is lost. Currently Expensify is using a 30 minutes interval to refresh personal details.
    // More details here: https://git.io/JJYeb
    'Setting a timer for a long period of time',
]);

+ TouchableOpacity.defaultProps = TouchableOpacity.defaultProps || {};
+ TouchableOpacity.defaultProps.activeOpacity = 0.7;

const fill = {flex: 1};
```

Whether to set 0.7 or 0.8 depends on confirmation from design team.

However, I am not sure if this is worth fixing based on https://github.com/Expensify/App/issues/14589

**Comment by mollfpr** [comment] 2023-01-30 09:38
Thanks for the proposals! I'll review this issue tonight!

**Comment by mollfpr** [comment] 2023-01-30 14:53
@joekaufmanexpensify What do you think about this plan https://github.com/Expensify/App/issues/14589?

**Comment by joekaufmanexpensify** [comment] 2023-01-30 19:28
Hm, interesting. My 2c is that it seems like whatever we change in this issue will be redone in that issue. And we should therefore do nothing for now, and wait for a standardized system of pressables to be added in the app. Curious if you agree @mountiny ?

**Comment by mountiny** [comment] 2023-01-30 19:32
Yeah that makes sense to me, this is very minor issue and I see no reason in fixing this now if we will move away from the Touchables implementation

Thanks @mollfpr for bringing this up!

**Comment by joekaufmanexpensify** [comment] 2023-01-30 23:06
Cool, thanks for confirming! Going to go ahead and close this one then.

**Closed by joekaufmanexpensify** 2023-01-30 23:06 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
