### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] iOS - Chat - After going back from the sub-thread and editing the message, the Chat Composer is hidden behind the keyboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24555] opened 2023-08-14 20:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to Account A >> Open any chat report.
2. Send a message to the chat (if A hasn't sent any message before)
3. Long press on the message created at step 3 and select the "Reply in thread" option (KEY step).
4. Go back to the main chat.
5. Long press on the message again and select the "Edit comment" option.
6. Chat composer is hidden behind the keyboard.
(Note: The only way to make it work again is to leave the chat and reopen it)

## Expected Result:
The chat composer shouldn't be hidden behind the keyboard, so the user can see what they are typing.

## Actual Result:
The chat composer is hidden behind the keyboard, making it impossible for the user to see what they typed.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/29f045ec-752f-417d-85c9-e777e53ccb85

https://github.com/Expensify/App/assets/115492554/ef8f95d1-c022-4ee9-814d-d35a1050c15f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691173341567539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c49f282cc4a51c0a</li>
        <li>Upwork Job ID: 1696693806832926720</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26408299</li>
<li>ShogunFire | Contributor | 26408300</li>
<li>Tranvantoan-qn | Reporter | 26408301</li>
</ul></li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-08-15 03:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The composer is hidden behind the keyboard when we go to a child report

### What is the root cause of that problem?

In ReportScreen we set if the KeyboardAvoidingView should be enable here:
https://github.com/adamgrzybowski/App/blob/ff423aa61fde128e981ee071b01011238927516c/src/pages/home/ReportScreen.js#L294

The keyboard avoiding view is enabled only if we are in the top most report.

When we go to a child report the parent  is not the top most report anymore so the keyboard avoidingview is disabled. When we go back the parent should be notified that he is the top most report but this is not the case, he doesn't rerender.

### What changes do you think we should make in order to solve the problem?

In order for the parent report to rerender and update the behaviour of keyboard avoiding view, ReportScreen should subscribe to the onyx event withCurrentReportID that is firing when the top most report changes

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-08-15 08:29
This issue was reported already https://github.com/Expensify/App/issues/23423
I reported several times but @isabelastisser didn't reply

**Comment by ShogunFire** [comment] 2023-08-15 10:28
Maybe we can handle it here then ?

**Comment by tranvantoan-qn** [comment] 2023-08-15 10:42
I don't know what the best option is, as the previous issue is CLOSED; therefore, I couldn't determine if it had been reported earlier. And since it is CLOSED without a fix, I don't think it will ever get another chance to be checked/fixed unless someone reports it again.

So let @mallenexpensify check it first, and he will provide the option that best suits us.

**Comment by situchan** [comment] 2023-08-23 15:40
@mallenexpensify this is always reproducible on iOS after navigating back from thread

I found this while reviewing another PR

https://github.com/Expensify/App/pull/23994#issuecomment-1689819017

**Comment by s-alves10** [comment] 2023-08-23 15:47
We have `shouldEnableKeyboardAvoidingView` as props in `ScreenWrapper`
We can find all cases based on the fact navigating back(stack pop) doesn't remount the page.

**Comment by ShogunFire** [comment] 2023-08-23 15:51
> We have `shouldEnableKeyboardAvoidingView` as props in `ScreenWrapper` We can find all cases based on the fact navigating back(stack pop) doesn't remount the page.

Yes but that only happens when you open a report since the cause of this bug is the top most report id is not updated. I don't think you will find other cases than "opening a report"

**Comment by ShogunFire** [comment] 2023-08-23 15:53
Sorry I misunderstood

**Comment by mallenexpensify** [comment] 2023-08-30 01:18
Making External.  If anyone finds other instances we can fix at the same time, that'd be great!  If not... we can focus on fixing just this bug.

**Comment by cubuspl42** [comment] 2023-08-30 08:29
By looking at the source, the `withCurrentReportID` serves exactly this purpose: keeping up-to-date with the current top-most report ID.

```js
const withCurrentReportIDPropTypes = {
    /** Function to update the state */
    updateCurrentReportID: PropTypes.func.isRequired,

    /** The top most report id */
    currentReportID: PropTypes.string,
};
```

I believe that the approach suggested by @ShogunFire is the cleanest one.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-08-31 08:25
@tienifr While it's true that this might cause some extra re-renders, this is also the case for most other `with*` utils. I think that abusing `useMemo` should be kept to a minimum. Reacting to the property change felt cleaner to me.

**Comment by aldo-expensify** [comment] 2023-08-31 17:32
> @tienifr While it's true that this might cause some extra re-renders, this is also the case for most other with* utils. I think that abusing useMemo should be kept to a minimum. Reacting to the property change felt cleaner to me.

I agree with this, the suggested `[useMemo](https://github.com/Expensify/App/issues/24555#issuecomment-1698444937)` here is not watching everything it depends on, so to me it feels like it could lead to harder to see bugs.

**Comment by mallenexpensify** [comment] 2023-09-05 02:22
@greg-schroeder  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by mallenexpensify** [comment] 2023-09-11 06:25
PR is being worked on

**Comment by cubuspl42** [comment] 2023-09-11 08:46
PR is merged

**Comment by cubuspl42** [comment] 2023-09-13 09:36
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/23024
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/23024/files#r1324249166
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a new regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by mallenexpensify** [comment] 2023-09-21 05:35
Issue reporter: @tranvantoan-qn paid $250 via Upwork
Contributor: @ShogunFire paid $1000 via Upwork
Contributor+: @cubuspl42 paid $1000 via Upwork

  @cubuspl42 is the reasoning you have `N/A` for creating a regression test step because the bug was design related?

**Comment by cubuspl42** [comment] 2023-09-21 08:13
@mallenexpensify To be completely honest, I don't feel confident about filling out the regression test-related part of this checklist... Unless the bug is very serious, I just suggest not creating a regression test, because otherwise, the regression test list would grow infinitely? But I'm very open to suggestions here. Do you think we should create a regression test for this one?

**Comment by flodnv** [comment] 2023-09-25 05:13
Agreed

**Closed by flodnv** 2023-09-25 05:12 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2023-09-27 06:25
In general it's best practice to create the regression test steps GH because Applause/QA reviews them and either
- Adds to TestRail
- If it's an edge case, like this, they add it to a 'check every month' type list
- add to other lists like _design related_.   
- Close it/do nothing cuz it's so rare. 

I created one based on the PR steps
https://github.com/Expensify/Expensify/issues/320498

**Comment by cubuspl42** [comment] 2023-09-27 07:17
@mallenexpensify Thank you for this explanation. Would these steps differ from the "QA steps" from the PR template?

**Comment by mallenexpensify** [comment] 2023-10-02 13:41
@cubuspl42 , I _think_ they're most-often the exact same.  I can't think of instances where they're not.  So, starting with copy/pasting the QA steps is def the best start (then, do a quick double check to make sure they're still accurate).
