### ISSUE TITLE
[HOLD for payment 2024-03-05] [Contributor] Add Visit Expensify Classic Button to NewDot

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#32875] opened 2023-12-11 22:45 UTC
# Part of #wave9-collect-signups project
Main issue: Originated from this internal issue: https://github.com/Expensify/Expensify/issues/344901
Doc section: no design doc - this was pre-designed already. 
Project: #wave9-collect-signups

# Feature Description
Problem: As we start migrating users from OldDot to NewDot and point new signUps to NewDot, some users will require OldDot functionality to complete tasks, add secondary logins, use functionality not available on NewDot, access old expense/reports, and so on. If a user currently is in NewDot, the most straightforward way to access OldDot is to open a new tab and type in [expensify.com](http://expensify.com/) to get to OldDot, which causes confusion. If they have the tryNewDot redirect, typing in [expensify.com](http://expensify.com/) would not work and you’d have to send them a specific link or instructions how to do so.

Solution: Add a button in NewDot to allow user to easily navigate to OldDot.
- Note: some users have the tryNewDot NVP applied to their accounts which means if they type in [www.expensify.com](http://www.expensify.com/), they are redirected to OldDot. This will not remove the NVP but will allow the user to be taken to the inbox.

*Where will we add the button?*
You’d find the button by going to Avatar > Settings. Then above Sign Out we’ll add the button `Go to Expensify Classic` (Image in thread of where it will go). Mock up here: 

![image](https://github.com/Expensify/App/assets/2364487/e51da818-2e3f-46f7-b6b5-bcff2c6da582)

*What will the button do?*
- Web (desktop/mobile) - opens up a new tab for https://www.expensify.com/inbox
- NewDot App - leaves the app and opens up a new tab for https://www.expensify.com/inbox in your default browser
- [HOLD] HybridApp - stays in HybridApp and goes to settings in OldDot. The hybrid app is not ready yet so we do not need to account for this use case yet, but just accounting that it will be here later. 

I think this should have everything you need to complete this. Please feel free to ask me any questions. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183075eef93ad0483</li>
        <li>Upwork Job ID: 1734346213197549568</li>
        <li>Last Price Increase: 2023-12-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by neonbhai** [comment] 2023-12-11 23:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add Visit Expensify Classic Button to NewDot

### What is the root cause of that problem?
New Feature

### What changes do you think we should make in order to solve the problem?
We will be adding another menuItem here, before `Sign Out` button.
https://github.com/Expensify/App/blob/165caf526ffcd2d00dbed4995d25981c7ab04b17/src/pages/settings/InitialSettingsPage.js#L259-L265

```js
{
    translationKey: 'initialSettingsPage.goToExpensifyClassic',
    icon: Expensicons.Expensify,
    iconRight: Expensicons.NewWindow,
    action: () => {    
        Linking.openURL(CONST.OLDDOT_URL);
    },
},
```
And add this CONST variable:
```js
OLDDOT_URL: 'https://www.expensify.com/'
```

**Comment by AndrewGable** [comment] 2023-12-12 00:20
@neonbhai - This issue is labeled internal, which means it's not currently open to proposals. We will let you know if this changes in the future. Thanks!

**Comment by neonbhai** [comment] 2023-12-12 01:06
@AndrewGable ah right. Thanks!

**Comment by barttom** [comment] 2023-12-12 13:10
Hey, I'm Bartek from Callstack - expert contributor group - I would like to work on this issue

**Comment by barttom** [comment] 2023-12-12 21:11
I haven't found a needed icon for this item, so I've converted https://github.com/Expensify/App/blob/main/assets/images/expensify-logo-round-transparent.png as best as I could 🙈 
If exists that icon in SVG format or if You have it prepared please let me know

**Comment by kadiealexander** [comment] 2023-12-13 06:48
Hey @dubielzyk-expensify, could you please share a transparent svg of our round E logo? Like this one https://github.com/Expensify/App/blob/main/assets/images/expensify-logo-round-transparent.png but in SVG form. Thanks!

**Comment by barttom** [comment] 2023-12-13 08:37
What about label translation for Spanish, is `'Ir a Expensify Classic' ok?

**Comment by dubielzyk-expensify** [comment] 2023-12-14 01:02
@kadiealexander : Can we use [this](https://github.com/Expensify/App/blob/main/assets/images/new-expensify.svg)?

**Comment by danielrvidal** [comment] 2023-12-14 01:37
What about label translation for Spanish, is `'Ir a Expensify Classic' ok?

Yes, that works @barttom

**Comment by kadiealexander** [comment] 2023-12-14 01:47
@dubielzyk-expensify that should work great thanks!

**Comment by kadiealexander** [comment] 2023-12-14 01:47
@barttom let us know if you need anything else for this one!

**Comment by barttom** [comment] 2023-12-14 07:26
@kadiealexander Thanks a lot, that's all I need.

**Comment by danielrvidal** [comment] 2023-12-19 23:29
I saw in the other issue it doesn't look to be a blocker. @srikarparsi got assigned so I think should resolve shortly but I think we'll be okay to keep moving forward.

**Comment by danielrvidal** [comment] 2023-12-21 05:36
It looks like this worked on my expensify.com account when I'm already signed in to my www.expensify.com but when I signed up for a fresh account and tried to use the button, it is forcing me to sign into www.expensify.com when I would think I should just go right into expensify.com without needing to sign in. 

This is reproducable by doing these steps:
1. Sign up on new.expensify.com using a gmail account. This requires you to use a magic code, which should validate the account. 
2. Navigate to Settings > Go to Expensify Classic
3. Rather than than signing into expensify.com, it takes me to the below. The expected behavior would be that I'm signed in.
<img width="1211" alt="image" src="https://github.com/Expensify/App/assets/2364487/98ce72d1-4dbe-41a8-8753-3d43a9aade4b">

Can we confirm this should allow you to be signed in already? If so, we should update this to work properly.

**Comment by pecanoro** [comment] 2023-12-21 10:16
@danielrvidal I might be wrong but I think we don't have any functionality to support logging in from newdot to oldot, only the other way around.

**Comment by MitchExpensify** [comment] 2023-12-21 13:44
@barttom I reproduced the issue @danielrvidal is describing except I was required to enter another magic code when I clicked "Go to Expensify Classic" 

![image](https://github.com/Expensify/App/assets/36425901/4f2abfc6-e684-47d9-9f0d-b8daf77c48dd)

In a similar line to what @pecanoro mentioned, is this expected for new accounts? Or should we expected to be able to navigate from NewDot to OldDot from a fresh account without having to sign in again?

**Comment by barttom** [comment] 2023-12-21 14:24
As I understand, OldDot and New Dot are separated apps. Because of that, we have separated authentications.
If a user signed up in OldDot before, it should see inbox. In another case - it should be redirected to the inbox after login.
What I can do in NewDot is just redirect to another app.

**Comment by danielrvidal** [comment] 2023-12-21 23:29
@barttom we'll get back to you on next steps, it sounds like this might be expected behaviour.

**Comment by situchan** [comment] 2023-12-22 19:32
@barttom do you mind fixing these issues as follow-up? (as they're within regression period)
- https://github.com/Expensify/App/issues/33284
- https://github.com/Expensify/App/issues/33519

**Comment by barttom** [comment] 2023-12-22 19:37
@situchan  I'm OOO till the 1st January. If  they can wait I can take them when I’ll be back

**Comment by danielrvidal** [comment] 2023-12-23 21:29
Just for reference, my [comment here](https://github.com/Expensify/App/issues/32875#issuecomment-1865508551) does not actually apply. I looked at this with our engineering team and if you are not signed into OldDot already, you should need to still sign in so please disregard my comment. 

After the two fixes are done that @situchan I think it should be good.

**Comment by pecanoro** [comment] 2023-12-29 16:14
Not overdue, waiting for @barttom to come back from OOO to deal with the remaining issues

**Comment by dubielzyk-expensify** [comment] 2024-01-02 03:18
Not overdue, Melvin, see above comment

**Comment by barttom** [comment] 2024-01-02 11:04
@pecanoro @situchan Should I proceed [mentioned issues](https://github.com/Expensify/App/issues/32875#issuecomment-1868014118) here or send proposals for each issue separately?

**Comment by situchan** [comment] 2024-01-02 12:26
They're regressions and I don't think you need to send proposals but directly create follow-up PR linking those issues.
Or if needed, you can post proposal here.

**Comment by barttom** [comment] 2024-01-02 12:39
OK, so I go with PRs then

**Comment by danielrvidal** [comment] 2024-01-08 00:49
What is the status with this one? What do we still need to do to close it out?

**Comment by pecanoro** [comment] 2024-01-08 09:27
@danielrvidal PR is on review, I reassigned it to our original C+ instead so we can speed it up.

**Comment by kadiealexander** [comment] 2024-01-09 06:37
Please re-add the payment date to the GH title when this is ready to pay. :)

**Comment by kadiealexander** [comment] 2024-01-24 06:17
@thesahindia don't forget the checklist please!

**Comment by kadiealexander** [comment] 2024-01-28 21:43
@thesahindia bump!

**Comment by kadiealexander** [comment] 2024-01-31 23:42
@thesahindia is OOO sick, no update.

**Comment by kadiealexander** [comment] 2024-02-07 05:50
Not overdue, please switch back to daily when the regression fix is deployed.

**Comment by kadiealexander** [comment] 2024-02-29 01:38
Not overdue, regression was merged 2 days ago.

**Comment by kadiealexander** [comment] 2024-03-06 05:32
I have updated the payment amount to reflect the regression. @thesahindia please request payment via NewDot.

**Closed** 2024-03-06 05:31 UTC
Labels: Weekly, Internal, NewFeature, Design, Awaiting Payment
