### ISSUE TITLE
Not all IOU reports on LHN display target account's avatar

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19652] opened 2023-05-26 02:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Send money to any account
3. Go to LHN

## Expected Result:
All reports created should have target account's avatar

## Actual Result:
Only one report created has target account's avatar

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
Found when executing PR #19392

https://github.com/Expensify/App/assets/43995119/fc12b732-3dae-41ca-bc1e-1d0c00f7ee7a

https://github.com/Expensify/App/assets/43995119/8359e23b-d218-4640-b123-ed61d8e7719b

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment] 2023-05-26 03:53
Investigating this soon!

**Comment by yuwenmemon** [comment] 2023-05-26 06:29
@tienifr @thienlnam @thesahindia This is related to https://github.com/Expensify/App/pull/19392

Robert and I talked about this and we _think_ it's working as expected and thus removed the deploy blocker label ([thread](https://expensify.slack.com/archives/C07J32337/p1685071412327009))

But... please double check out logic 😅

**Comment by strepanier03** [comment] 2023-05-26 23:08
I'm not sure how to proceed here and it's getting pretty late on Friday so I'll check back in on Tuesday when I'm online. Feel free to assign any labels in the meantime so you're not held up on my OoO Monday.

**Comment by tienifr** [comment] 2023-05-29 09:22
@thesahindia Thanks for reminding! I think we've previously missed the case of sending money. This PR fixes both the issues: https://github.com/Expensify/App/pull/19735.

**Comment by strepanier03** [comment] 2023-06-01 01:43
@thienlnam will be back tomorrow. If he doesn't know the expected behavior I'll raise it in Slack.

**Comment by thienlnam** [comment] 2023-06-02 00:53
Yeah this is confusing, I'm not totally sure about the expected behavior but @luacmartins or @mountiny would know

**Comment by mountiny** [comment] 2023-06-02 00:58
@trjExpensify would you be bale to check this one out and confirm the expected avatars?

**Comment by strepanier03** [comment] 2023-06-07 23:34
@trjExpensify - Do you have any idea about the expected avatars?

**Comment by trjExpensify** [comment] 2023-06-09 00:20
Hey, thanks for the bump! I'm not exactly sure what I'm checking with "target account's avatar". But, we've had internal discussions recently about avatars and chat headers. That's just wrapped up, and @grgia is now moving forward with implementing the changes. 

It'll look like this: 
![image](https://github.com/Expensify/App/assets/16232057/4b5dd875-067a-4440-a038-32f81b99178a)

So if this issue is regarding the LHN/chat header avatars, I think we can actually probably close this as the changes are being implemented. 

If there's something else to clarify though, do let me know and we can move on to that :)

**Comment by mountiny** [comment] 2023-06-12 21:22
@thienlnam feel free to close this issue up

**Comment by strepanier03** [comment] 2023-06-12 22:20
@thienlnam - Looks like we can close this one. Since this was internally reported we don't need a bug payment and it never went external so we don't owe any contributors or C+. 

I'm going to close this now but if you think it needs to be reopened for anything please do it.

**Closed by strepanier03** 2023-06-12 22:20 UTC
Labels: Reviewing, Engineering, Daily, Bug
