### ISSUE TITLE
[Search v1] - Action field remains as "Paid" after expenses are unapproved until page is revisited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45001] opened 2024-07-08 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat as admin
3. Submit two expenses
4. Go to Search > Shared
5. Click on the grouped expenses
6. Pay elsewhere the expense
7. Go back to Search > Shared
8. Click on the grouped expenses
9. Click on the report header
10. Click Unapprove

## Expected Result:
The action field for the grouped expenses will turn to "Action"

## Actual Result:
The action field for the grouped expenses remains "Paid", until the Search page is revisited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e7e4f5c9-c7af-4fa9-8fc5-6990d12ebb44

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-08 20:02
@tylerkaraszewski  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-08 20:02
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment] 2024-07-08 21:10
cc @luacmartins

**Comment by luacmartins** [comment] 2024-07-08 22:01
hmm this is a tricky one. We save the `action` in its own key in snapshot_ so the live updates don't change this key since the live onyx data, e.g. report_ and transactions_ don't have the `action` key.

**Comment by luacmartins** [comment] 2024-07-08 22:08
This is not a blocker though since I was able to reproduce in production.

**Comment by tylerkaraszewski** [comment] 2024-07-18 18:39
@luacmartins - do you think we can make this external, or are you interested in working on it?

**Comment by amunim** [comment] 2024-07-19 06:55
![image](https://github.com/user-attachments/assets/3b99a100-d796-4212-9a2f-e9208ac95f2c)
broke during reproduction :)

**Comment by luacmartins** [comment] 2024-07-22 16:24
I can't reproduce this exact issue anymore since I don't see an option to `Unapprove`. I can reproduce with the `Cancel payment` option. 

This happens because we update the report's `statusNum` in Onyx and computing the new state when cancelling the payment, but the Search page uses the `action` key computed on the server to determine what the next action should be. I'm not really sure how to solve since it'd require a fundamental change to the Search design.

**Comment by tylerkaraszewski** [comment] 2024-08-02 23:10
@luacmartins What do you think should we just close this then?

**Comment by luacmartins** [comment] 2024-08-06 06:26
Yea, I think we can close this for now.

**Closed by luacmartins** 2024-08-06 06:26 UTC
Labels: Engineering, Daily, Internal, Hot Pick
