### ISSUE TITLE
[$1000] Transparent white image is not visible in image preview.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23739] opened 2023-07-27 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Upload transparent white logo
## Expected Result: 
Logo should be visible.
## Actual Result: 
Logo is not visible.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3d8fba67-53b5-4346-a46e-2f354f4af876

![Mahi Constructions White logo 2400x1800](https://github.com/Expensify/App/assets/43996225/07241153-754b-4283-8a63-ea16a43e25c4)

https://github.com/Expensify/App/assets/43996225/647acdaf-7a34-4257-9345-ee576ac15303

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690435397160039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019977a29ab3ac1565</li>
        <li>Upwork Job ID: 1684603374762098688</li>
        <li>Last Price Increase: 2023-08-10</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-07-27 15:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Transparent white logo is not visible in image preview.

### What is the root cause of that problem?

The problem is that we are pushing a png.jpg image extension instead of the original .png, reason seem to be making png images more visible. the problem is that a png image being made into a jpg will have a white background and as a result any png images that are white will end up blending with the white background, the reason jpg is being used is that we are using previewSource instead of source in the imageRenderer when passing the source to the ThumbnailImage component.
https://github.com/Expensify/App/blob/f8bc30500acaed95d4668657cf18558deee79194/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js#L67-L72

### What changes do you think we should make in order to solve the problem?

We should pass source to ThumbnailImage to pass the png original version of the image
```javascript
<ThumbnailImage
    previewSourceURL={source}
```

### Result

https://github.com/Expensify/App/assets/74202751/ec4f9333-8130-46a8-a0ac-6ea39d7e2fa1

**Comment by suneox** [comment] 2023-07-30 02:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Transparent white logo is not visible in image preview.

### What is the root cause of that problem?
The root cause happens when we upload an image and the response of the command 'AddAttachment' for the image source is always a JPG file
<img width="1503" alt="Screenshot 2023-07-30 at 08 37 19" src="https://github.com/Expensify/App/assets/11959869/c6589216-e342-4e22-9ed0-5d1f7855a6b8">

### What changes do you think we should make in order to solve the problem?
We have to fix it on the server side to keep the original mime type for the preview src and avoid displaying the original size for the preview image

**Comment by suneox** [comment] 2023-07-30 02:39
Contributor details
Your Expensify account email: ptcong411@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01db28c0b67552b8a7

**Comment by twisterdotcom** [comment] 2023-08-01 16:37
A few proposals to go at here @rushatgabhane when you have the chance.

**Comment by rushatgabhane** [comment] 2023-08-02 04:36
Asked a question on slack related to the format we store images in https://expensify.slack.com/archives/C01GTK53T8Q/p1690950935419129

**Comment by romitgithub** [comment] 2023-08-05 07:03
Contributor details
Your Expensify account email: [choudharyromit@gmail.com](mailto:choudharyromit@gmail.com)
Upwork Profile Link: https://upwork.com/freelancers/~01b7c2a45e48a0d1d1

**Comment by romitgithub** [comment] 2023-08-05 07:04
Contributor details
Your Expensify account email: choudharyromit@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~01b7c2a45e48a0d1d1

**Comment by romitgithub** [comment] 2023-08-05 07:09
Contributor details
Your Expensify account email: choudharyromit@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~01b7c2a45e48a0d1d1

**Comment by twisterdotcom** [comment] 2023-08-06 19:01
Let's tag @youssef-lr in on this from https://github.com/Expensify/App/issues/21795 too. It does sound like this should be internal right?

**Comment by twisterdotcom** [comment] 2023-08-09 12:58
@youssef-lr would love your opinion please.

**Comment by youssef-lr** [comment] 2023-08-09 13:56
@AmjedNazzal I think your proposal will defeat the purpose of the thumbnails we create to display a reduced size version of the original images we upload. 

@suneox I'm not sure if simply keeping the original PNG mime type will fix the issue, the image returned has already been converted to JPG in the backend and has lost its transparency.

**Comment by twisterdotcom** [comment] 2023-08-09 14:36
Ah okay, so we should either start storing images in their native file types, or we should close this as expected. I sort of think, if you upload a PNG, you should expect to be able to redownload that as a PNG. Can that be external?

**Comment by AmjedNazzal** [comment] 2023-08-09 16:10
@twisterdotcom if it's going to be png and optimized for the preview then it does sound like an internal fix I think.

**Comment by youssef-lr** [comment] 2023-08-10 16:05
@twisterdotcom  IMO we can close this, the image in the issue happens to have only white text, so when the transparent part is turned white all of the image looks white. But downloading the image will return back the original PNG image uploaded with transparency kept intact, which is why I'm inclined to :donothing: here.

**Comment by twisterdotcom** [comment] 2023-08-11 13:14
Okay, no pushback from #product. Let's close then. Apologies all, but given we won't be making any changes here, we won't pay anything out. I appreciate everybody's contributions here though - onto the next one!

**Closed by twisterdotcom** 2023-08-11 13:14 UTC
Labels: External, Daily, Help Wanted, Bug
