### ISSUE TITLE
[$500] Threads - 'n replies' appears under parent message in thread and it leads to not here page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32485] opened 2023-12-05 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread
5. Send a reply in thread
6. Click on 'n replies'

## Expected Result:
In Step 5, there should be no 'n replies' under the parent message in thread

## Actual Result:
In Step 5, there is 'n replies' under the parent message in thread. The 'n replies' link leads to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9d669487-edc6-42a5-8887-cd7b78543eb7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127edd78e0e28e371</li>
        <li>Upwork Job ID: 1732057684569538560</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-05 15:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We do not set the `childReportID` of the parent `reportActionItem` when creating the thread.

### What changes do you think we should make in order to solve the problem?
We should set the `childReportID` of the parent `reportActionItem` when starting a thread.

### What alternative solutions did you explore? (Optional)

**Comment by happy-devs** [comment] 2023-12-05 15:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user replies to a message in a chat thread, the message has an indicator showing 'n replies' appears under the parent message which should not show in thread view. Additionally, clicking on the 'n replies' link leads to a non-functional page (referred to as "not here page").

### What is the root cause of that problem?
The current `ReportActionItem` component has a `shouldDisplayThreadReplies` boolean to display the thread UI component which does not reflect the current view.

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by yh-0218** [comment] 2023-12-05 21:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "n replies" button redirects to a broken view when the user sends a reply inside a reply view.
### What is the root cause of that problem?
Because `report` of is not updated `ReportActionItem`.
we get report as `props.report` from `ReportActionItemParentAction`
### What changes do you think we should make in order to solve the problem?
We need to update `ReportActionItemParentAction` when reply.
```
memo(
        ReportActionItemParentAction,
        (prevProps, nextProps) =>
            lodashGet(prevProps.props, 'report.childReportID') === lodashGet(nextProps, 'report.childReportID')
)
```
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/503502b4-91c6-42f3-87b2-ca42dc4a8c40

**Comment by yh-0218** [comment] 2023-12-05 21:44
we need to add more conditions for memo (for edit, delete and etc)

**Comment by paultsimura** [comment] 2023-12-05 22:07
Seems like it's the same root cause as https://github.com/Expensify/App/issues/32485#issuecomment-1841032546 (BE regression).

**Comment by yh-0218** [comment] 2023-12-07 13:57
Hi, @conorpendergrast @allroundexperts
Now we have many issue because of this issue.
Please check my proposal. Thanks.

**Comment by rojiphil** [comment] 2023-12-07 15:25
As I understand, the approved proposal for [26511](https://github.com/Expensify/App/issues/26511) should solve the `not here page` issue. 
I would suggest to keep this on hold till then

**Comment by allroundexperts** [comment] 2023-12-07 23:02
I agree with @paultsimura and @dukenv0307's analysis that something got changed on the backend. We should ideally fix this from the backend but if not, then @dukenv0307's [proposal](https://github.com/Expensify/App/issues/32485#issuecomment-1842072840) would work just fine!

🎀 👀 🎀 C+ reviewed

**Comment by yh-0218** [comment] 2023-12-08 04:03
hi, @allroundexperts how about my proposal? I think that is main problem.

**Comment by yh-0218** [comment] 2023-12-08 06:07
I think this is not backend issue.
https://github.com/Expensify/App/assets/65789015/e674f842-e7d1-47d7-9736-67e70b849e5e

**Comment by allroundexperts** [comment] 2023-12-08 11:13
Hi @yh-0218!

Reason why I did not choose your proposal was that I wasn't able to find the pattern of setting success data with values other than `null` in our code. If you think this is not an issue with the backend, do you mind pointing to the piece of code we recently added which caused this? Thanks

**Comment by mallenexpensify** [comment] 2023-12-09 01:33
@Beamanator can you please prioritize reviewing this issue? It's a pretty nasty bug.  Thx

**Comment by conorpendergrast** [comment] 2023-12-11 12:22
@Beamanator waiting for your review of [the recommended proposal](https://github.com/Expensify/App/issues/32485#issuecomment-1846239242)!

**Comment by Beamanator** [comment] 2023-12-11 12:27
Yeah I've been investigating a bit, I feel like the main solution should be in the back-end, I asked for some help internally [here](https://expensify.slack.com/archives/C03SDMF9YJ2/p1702297494000589) since this mayyy have to do with recent reliable updates

**Comment by mallenexpensify** [comment] 2023-12-11 21:15
What can we do to prioritize this? It's happening on production and it's on EVERY post in a thread (at least, from what I can tell, just tested on both staging, Version 1.4.11-4 and web/production. 
<img width="867" alt="image" src="https://github.com/Expensify/App/assets/22508304/78c8f63e-2188-4925-be9e-4dfe86e239ca">


production
<img width="673" alt="image" src="https://github.com/Expensify/App/assets/22508304/28dacb67-5b8d-4c53-be3f-722dacde4843">

**Comment by mallenexpensify** [comment] 2023-12-11 22:05
Posted in #expensify-open-source too
https://expensify.slack.com/archives/C01GTK53T8Q/p1702332267668559

**Comment by mallenexpensify** [comment] 2023-12-11 22:30
This issue could be related 
- https://github.com/Expensify/App/issues/32812 

The main issue here is
> In Step 5, there should be no 'n replies' under the parent message in thread

Yes, clicking the `n replies` leads to a crash page but, the `n replies` shouldn't be there in the first place so it doesn't matter where it leads to.

**Comment by mallenexpensify** [comment] 2023-12-12 00:04
Also.. @paultsimura posted four days ago about the parent issue/s 
https://expensify.slack.com/archives/C01GTK53T8Q/p1701958341150879

**Comment by aldo-expensify** [comment] 2023-12-12 18:19
@Beamanator I just confirmed that this is also caused by https://github.com/Expensify/Web-Expensify/pull/39748/files. I'll continue working on a fix

**Comment by aldo-expensify** [comment] 2023-12-12 18:21
Changing to `Internal` since this was caused by the backend [PR](https://github.com/Expensify/Web-Expensify/pull/39748/files) and I believe it needs a backend fix

**Comment by mallenexpensify** [comment] 2023-12-12 21:36
Thanks @aldo-expensify !!!

**Comment by aldo-expensify** [comment] 2023-12-13 03:56
I left a draft PR for this issue here: https://github.com/Expensify/Auth/pull/9419, I'm not sure if it is the best way to fix it, so I'm asking there too

**Comment by allroundexperts** [comment] 2023-12-13 04:14
Maybe we can implement the fix on the client App as well by using the proposal above?

**Comment by aldo-expensify** [comment] 2023-12-13 23:29
Decided to fix this in the PHP layer: https://github.com/Expensify/App/issues/32485, PR is ready for review.

**Comment by aldo-expensify** [comment] 2023-12-18 15:01
https://github.com/Expensify/Web-Expensify/pull/40080 is in staging

**Comment by mallenexpensify** [comment] 2023-12-19 04:40
Tested on staging and wasn't able to reproduce (was only a few tests though)

**Comment by paultsimura** [comment] 2023-12-19 09:02
> Wasn't able to reproduce

Yes, now the API response returns a valid `childReportID` for the parent `reportAction`.
It already fixes a couple of thread-related issues: this one is not reproducible on Staging, and neither is https://github.com/Expensify/App/issues/32519

**Comment by aldo-expensify** [comment] 2023-12-19 13:08
PR https://github.com/Expensify/Web-Expensify/pull/40080 hit production yesterday

**Comment by aldo-expensify** [comment] 2023-12-19 13:24
Tested in production, the bug is not there anymore.

**Comment by mallenexpensify** [comment] 2023-12-22 16:10
It's back!!!! 
I'm on Desktop Version 1.4.16-2
<img width="825" alt="image" src="https://github.com/Expensify/App/assets/22508304/442e7fda-0860-4275-946a-ac3571cbcfd4">

In the past, when I've encountered the bug, it was when I sent a message, this time it's when someone else is.

**Comment by mallenexpensify** [comment] 2023-12-22 16:16
Updated app this morn then noticed. 
Logged out/in and it's still showing.

**Comment by aldo-expensify** [comment] 2023-12-22 16:25
Since it is present since you log in, it is not related to onyx updates sent through the pusher... it probably has a different cause

**Comment by aldo-expensify** [comment] 2024-01-02 14:02
We don't know if the issue at hand is `Internal` anymore. Should we create a new issue with reproduction steps to start a clean investigation?

**Comment by mallenexpensify** [comment] 2024-01-04 23:24
Pretty sure this is fixed, I'm unable to reproduce so I'm closing. Comment/reopen if you disagree

**Closed** 2024-01-04 23:29 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
