### ISSUE TITLE
QAB missing tooltip

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53777] opened 2024-12-09 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah 
**Slack conversation** (hyperlinked to channel name): [#expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1733768184773589)

## Action Performed:
Prerequisite: Browser resized to small window

1. Log in as a new user.
2. Submit a new expense to any user.
3. Press the FAB (Floating Action Button).
4. Verify that a tooltip is shown for the QAB (Quick Access Bar).
5. Verify that the tooltip auto-hides after 5 seconds.

## Expected Result:
 You will see a QAB with tooltip
## Actual Result:
You will see a QAB without tooltip
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/94e13db6-8f68-4242-80e1-83f1d627ef69

https://github.com/user-attachments/assets/edc710ff-f138-4ede-9153-ecd11221cc1d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment] 2024-12-09 20:38
Caused by https://github.com/Expensify/App/pull/53475
Reverted here https://github.com/Expensify/App/pull/53784

**Comment by luacmartins** [comment] 2024-12-09 22:46
Fixed in staging

Uploading Screen Recording 2024-12-09 at 3.46.20 PM.mov…

**Closed by luacmartins** 2024-12-09 22:46 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
