### ISSUE TITLE
[$1000] [HOLD for payment 2023-08-14] Dev: Offline Indicator duplicate

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24092] opened 2023-08-03 08:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB
2. Request money
3. Turn off network, Observe that offline Indicator appears 2 times

## Expected Result:
offline Indicator only appears 1 times

## Actual Result:
offline Indicator appears 2 times

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/846a571b-d674-4896-8a96-6faced5b2fdb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691026269347159?thread_ts=1691026269.347159&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ea26026f1b18139</li>
        <li>Upwork Job ID: 1691534812625043456</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-08-03 08:04
## Proposal from @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
Offline Indicator only appears 1 time in request money tab
### What is the root cause of that problem?
In the request money manual screen, we have 2 nested ScreenWrapper. That why it's show 2 times
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/pages/iou/MoneyRequestSelectorPage.js#L79-L83
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/pages/iou/MoneyRequestSelectorPage.js#L111
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/pages/iou/steps/MoneyRequestAmount.js#L424-L429
### What changes do you think we should make in order to solve the problem?
We should add `shouldShowOfflineIndicator = {false}` and remove `safeAreaPaddingBottomStyle` for ScreenWrapper in MoneyRequestAmount
```javascript
            <ScreenWrapper
                includeSafeAreaPaddingBottom={false}
                onEntryTransitionEnd={focusTextInput}
                shouldShowOfflineIndicator = {false}
            >
             <View style={[styles.flex1]}>
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Beamanator** [comment] 2023-08-03 08:41
Thanks for reporting and proposing a solution @namhihi237 ! Let's also try to find where this came from :D

**Comment by Beamanator** [comment] 2023-08-03 08:47
Yes true, it looks like @s77rt brought this up in the PR here: https://github.com/Expensify/App/pull/23046/files#r1278470491

**Comment by Beamanator** [comment] 2023-08-03 08:51
Hmm and this PR supposedly will clean up the nested ScreenWrappers: https://github.com/Expensify/App/pull/23979

**Comment by Beamanator** [comment] 2023-08-03 08:58
Discussing in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1691052873878459

**Comment by abdulrahuman5196** [comment] 2023-08-09 11:06
@greg-schroeder I think there has been some issue with melvin. This issue was deployed to production on Aug 7 https://github.com/Expensify/App/pull/24097#issuecomment-1668389742. This issue should turn to hold for payment till Aug 14. Can we update manually?

**Comment by greg-schroeder** [comment] 2023-08-09 16:59
updated

**Comment by abdulrahuman5196** [comment] 2023-08-12 18:57
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It was already brought up in the PR - https://github.com/Expensify/App/pull/23046/files#r1278470491

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I think there should be some general Offline regression test on the App level which should be fine for this as well IMO.

If there is none on app level use the below,

1) Click FAB
2) Press Money Request
3) Go Offline
4) Verify there is only one Offline Indicator at the bottom


cc: @greg-schroeder

**Comment by greg-schroeder** [comment] 2023-08-15 14:04
Processing this, sorry for the slight delay

**Comment by greg-schroeder** [comment] 2023-08-15 18:49
Issue Participants:

Issue reported by: @namhihi237
Contributor: @s77rt
C+: @abdulrahuman5196 

Was this issue merged in time to be eligible for the speed bonus? ✅ 
Were their any regressions? ❌ 

Payment summary:

Reporter: $250
Contributor: $1500
C+: $1500

**Comment by greg-schroeder** [comment] 2023-08-15 18:55
Adding `External` to create an Upwork job

**Comment by greg-schroeder** [comment] 2023-08-16 01:58
Offers sent, regression test filed. Closing!

**Closed by greg-schroeder** 2023-08-16 01:58 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by s77rt** [comment] 2023-08-16 13:22
No payment is due for me here. I'm assigned for https://github.com/Expensify/App/pull/23979. Payment will be handled there as this is a regression.

**Comment by greg-schroeder** [comment] 2023-08-17 00:27
Ohh, right right okay thanks for clarifying

**Comment by abdulrahuman5196** [comment] 2023-08-21 10:29
@greg-schroeder C+ review payment is due here.

**Comment by greg-schroeder** [comment] 2023-08-23 07:17
Hmm. My Upwork UI shows these as paid on the admin side.

**Comment by greg-schroeder** [comment] 2023-08-23 07:18
Weird. When I click into the contracts they don't show as Paid now. Sorry about that. I've paid them now.
