### ISSUE TITLE
[hold on prioritizing P2P] Web - Send Money -  Incorrect account order in IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20078] opened 2023-06-02 17:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send money from account A to account B
2. Open the IOU thread and observe the account order in the header
3. Observe the thread title in the LHN

## Expected Result:
The header should show "Account A to account B" and the LHN thread title should not be "Account A owes ..." since account A already sent money.

## Actual Result:
The IOU thread header shows incorrect order, it says "Account B to account A" even if account A sent the money. LHN thread title says "Account A owes ..." which is confusing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:**yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a716676b-aee3-4abf-a095-cdb2ef9af2bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685372217500419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment] 2023-06-05 17:43
I think this is a design flaw and not a bug per se. Discussing in the slack thread [here](https://expensify.slack.com/archives/C049HHMV9SM/p1685372217500419)

**Comment by Julesssss** [comment] 2023-06-08 14:42
I believe this was handled as a seprate issue by @mountiny already. Closing this. 

<img width="1149" alt="Screenshot 2023-06-08 at 15 41 24" src="https://github.com/Expensify/App/assets/10736861/cf14f9d2-f328-4c28-9293-56d39e7202ec">

**Closed by Julesssss** 2023-06-08 14:42 UTC
Labels: Daily, Overdue, Bug
