### ISSUE TITLE
[HOLD #36376] [$500] Workspace - Connect Bank account options appear when Bank account is added

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39319] opened 2024-03-30 16:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+workspacetests@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
Fully verified Bank account should be added on Workspace
1. Login with [applausetester+workspacetests@applause.expensifail.com](mailto:applausetester+workspacetests@applause.expensifail.com)
2. Profile> Workspace> Open the workspace from precondition
3. Go to Bank account and verify that Bank account is added
4. Go to Travel
5. Go back to Bank account> Dismiss the modal

## Expected Result:
On travel page there should be Issue and manage cards, Book travel with Concierge and Learn more option

## Actual Result:
Connect Bank account options appear when dismiss the Bank account modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/10db570e-8b51-46b9-b6e4-e07e117a85c6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174b2ed1d814e8b7a</li>
        <li>Upwork Job ID: 1774870771472609280</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-04-02 04:56
Another same issue/root cause as https://github.com/Expensify/App/issues/34919

**Comment by Christinadobrzyn** [comment] 2024-04-03 04:09
We're evaluating the root cause of this issue in https://github.com/Expensify/App/issues/36376#issuecomment-2032673029  since the root cause is the same as https://github.com/Expensify/App/issues/36376

**Comment by puneetlath** [comment] 2024-04-04 20:00
@Christinadobrzyn so do you think we should put this issue on hold for that one?

**Comment by Christinadobrzyn** [comment] 2024-04-05 01:53
yes, let's hold for [36376](https://github.com/Expensify/App/issues/36376) to see if we can fix these together. I'll add a Hold to this GH.

**Comment by puneetlath** [comment] 2024-04-08 23:06
Moving to weekly while this is on hold.

**Comment by puneetlath** [comment] 2024-05-01 16:08
Still on hold.

**Comment by puneetlath** [comment] 2024-05-03 18:54
Ah cool. Let me ask for a re-test: https://expensify.slack.com/archives/C9YU7BX5M/p1714762425554409

**Comment by puneetlath** [comment] 2024-05-06 18:02
Looks like it's confirmed no longer happening. Closing out!

**Closed by puneetlath** 2024-05-06 18:02 UTC
Labels: External, Weekly, Help Wanted, Bug
