### ISSUE TITLE
App displays "Hidden" instead of email for group members

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21035] opened 2023-06-19 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the plus sign.
2. Click "New group".
3. Add members using random emails.
4. Click on a member's profile and observe that the details pop up to the left. Note that instead of the email, the word "Hidden" is displayed.
## Expected Result: 
The email of the group member should be displayed.
## Actual Result: 
The word "Hidden" is displayed instead of the email for group members in newly created groups.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture (18).webm](https://github.com/Expensify/App/assets/43996225/64697253-ed68-4515-a335-eb064f26feab)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687111889634979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2023-06-19 19:31
Taking a look right now!

**Comment by PauloGasparSv** [comment] 2023-06-19 19:43
Replicated it locally, seems to happen to users that we don't have a current active chat with (in other words, users that don't have info loaded by the LNH)

![image](https://github.com/Expensify/App/assets/6564265/cf8731ad-625e-4ce7-8967-99f461b98782)

**Comment by PauloGasparSv** [comment] 2023-06-19 19:45
Btw pretty interestingly but makes total sense: Refreshing the page doesn't fix this which means `OpenApp` doesn't load this info. 

I guess the participants page should load this

**Comment by PauloGasparSv** [comment] 2023-06-19 19:54
I think this might have been introduced in https://github.com/Expensify/App/pull/20473 since the [faulty line](https://github.com/Expensify/App/blob/f55c5d730b8600edf06ad74d35df78f636cd13ee/src/pages/ReportParticipantsPage.js#L61) was changed/added there. Not 100% sure because that P.R. is pretty huge haha

**Comment by PauloGasparSv** [comment] 2023-06-19 19:57
Looks like there is a missing `login` property that is used there.

I compared the App changes and that `login` always came from the `personalDetails` list passed to `getAllParticipants`, I think I just need to understand why that property is missing.

**Comment by PauloGasparSv** [comment] 2023-06-19 20:08
Yup, I think that's the case.

@Beamanator can you give me a hand on this since you worked on this logic? I think the `login` property is missing in the personalDetails of the report's participants (when `openReport` is called it doesn't really return that).

I'm not sure if I should:
1. Add the `login` field in the API [around here](https://github.com/Expensify/Web-Expensify/blob/462f72ef7edf7462c8fff375ea0fc3e72b3d72b9/lib/PersonalDetail.php#L253-L257)
2. Coalesce `userLogin` to `userPersonalDetail.displayName` like this around [here](https://github.com/Expensify/App/blob/3b945c052e86e00ca363fa3f7f4a30f370a3483c/src/pages/ReportParticipantsPage.js#L62):
    ```js
    - const userLogin = Str.removeSMSDomain(userPersonalDetail.login || '') || 'Hidden';
    + const userLogin = Str.removeSMSDomain(userPersonalDetail.login || userPersonalDetail.displayName || '') || 'Hidden';
    ```

**Comment by PauloGasparSv** [comment] 2023-06-19 20:33
Discussed this bug in [this thread](https://expensify.slack.com/archives/C07J32337/p1687190223955589) a little further and turns out this problem is already known and is caused by `isKnownUser` as we do return the `login` if that is truthy.

Instead of implementing  one of those solutions let's close this as its NAB + this will be fixed in https://github.com/Expensify/Expensify/issues/292707

**Closed by PauloGasparSv** 2023-06-19 20:33 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug

**Comment by PauloGasparSv** [comment] 2023-06-19 20:35
Oh @kevinksullivan I closed this but I'm not sure if this needs compensation to who found the bug.

**Comment by kevinksullivan** [comment] 2023-06-20 13:34
checking this in bug zero
