### ISSUE TITLE
[$1000] Web - The workspace name is not changing dynamically in the search tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22978] opened 2023-07-16 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A (device 1)
2. Open the app and login with user A (device 2)
3. From device 1, open the search tab
4. From device 2, change the workspace name

## Expected Result:
The workspace name should be changed dynamically in the search tab

## Actual Result:
The workspace name is not changing dynamically in the search tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1b72b411-03c6-4281-853e-e24808e21caa

https://github.com/Expensify/App/assets/93399543/5c830cf3-9678-43ef-be31-89e66cb53e01

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689435641790829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b35c6a0eb7aedaab</li>
        <li>Upwork Job ID: 1681237447476277248</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by kaushiktd** [comment] 2023-07-18 13:40
### Please re-state the problem that we are trying to solve in this issue.
Web - The workspace name is not changing dynamically in the search tab


### What is the root cause of that problem?
Currently, on SearchPage.js you are re-rendering only when reports and personalDetails data have been changed.  If anything changes to policies (workspace data) nothing is to be re-rendered.


### What changes do you think we should make in order to solve the problem?
first, You need to fetch policies props from `withOnyx` using `policySelector` functions (need to pass its parameter which value has to be checked if changed). So you need to replace code on below mentioned file:
https://github.com/Expensify/App/blob/main/src/pages/SearchPage.js#L201-L215

with the below code:

```
const policySelector = (policy) =>
    policy && {
        type: policy.type,
        name: policy.name,
        avatar: policy.avatar,
    };

export default compose(
    withLocalize,
    withWindowDimensions,
    withOnyx({
        reports: {
            key: ONYXKEYS.COLLECTION.REPORT,
        },
        personalDetails: {
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
        },
        betas: {
            key: ONYXKEYS.BETAS,
        },
        policies: {
            key: ONYXKEYS.COLLECTION.POLICY,
            selector: policySelector,
        },
    }),
)(SearchPage); 
```

then you need to check if policies props have been changed or not for that you need to add below condition to `componentDidUpdate` function 

```
if (_.isEqual(prevProps.reports, this.props.reports) && _.isEqual(prevProps.personalDetails, this.props.personalDetails) && _.isEqual(prevProps.policies, this.props.policies)) {
            return;
        }
```

### Video:
https://drive.google.com/file/d/1UEsQpNpi6oIRwZIGBYTyAn_JyLC_RL7R/view?usp=sharing

**Comment by s77rt** [comment] 2023-07-18 23:05
@ginsuma Thanks for the proposal. I don't think your RCA is complete. Can you explain why this happens only when we use 2 different devices (and not when we use 2 different tabs). Also I have noticed something weird, the display name in the search page on the 2nd device is out of sync by 1 change i.e. if you change the name n time, you will get the name that you set at n-1 time.


https://github.com/Expensify/App/assets/16493223/bd84260d-13f8-44eb-8a68-05f99ceeff6b

**Comment by s77rt** [comment] 2023-07-18 23:06
@kaushiktd Thanks for the proposal. I think it's the same as @ginsuma. Feel free to update your proposal answering the above concerns.

**Comment by s77rt** [comment] 2023-07-19 13:34
@ginsuma Thanks for the update. Can you please explain why `updateOptions` run before `allPolicies` update?

**Comment by s77rt** [comment] 2023-07-19 13:38
@tienifr Thanks for the proposal. Your RCA makes sense. The solution should work but I think we can find a better shorter solution. As far as I can tell reports relies on policies but it's never the other way around (policies does not relay on reports). So theoretically we can fix this issue by simply changing the order of pusher events to have the policies get updated first then the reports. Would that be sufficient here?

**Comment by s77rt** [comment] 2023-07-19 18:06
@greg-schroeder I think we should make this `Internal`. The solution is to update the order of pusher events. Currently we get the reports updated first then the policies. Changing the order should fix this issue.

![Screenshot from 2023-07-19 19-05-11](https://github.com/Expensify/App/assets/16493223/22049be3-f28c-411e-8e6b-f9cbc882b658)

**Comment by s77rt** [comment] 2023-07-20 11:35
@tienifr Oh right, sorry I missed that. Any specific reason why we should pass policies to `getSearchOptions` instead of using the connected one (the one in `ReportUtils`)?

**Comment by s77rt** [comment] 2023-07-24 10:01
Not overdue. @tienifr can you please answer the above question?

**Comment by s77rt** [comment] 2023-07-24 17:03
@tienifr Thanks for the update. I think that makes sense but we will end up updating a lot? `getOptions` and every underlying function and so for `getPolicyName`. This looks too much given the scope of this issue. I think we should fix the pusher events this should at least fix the name change and will ask about the workspace image.

**Comment by s77rt** [comment] 2023-07-24 17:06
@greg-schroeder Please assign an internal engineer here. Task: On changing workspace name verify the policy object in pusher events comes first. - currently it's not:

![Screenshot from 2023-07-19 19-05-11](https://github.com/Expensify/App/assets/16493223/1a532cb7-81c8-4b83-b8aa-b4d4dd22c042)

**Comment by greg-schroeder** [comment] 2023-07-24 18:14
Following - I can assign an internal engineer if that's the way we go

**Comment by greg-schroeder** [comment] 2023-07-24 18:35
Closing per discussion as failure to dynamically update is not a bug

**Closed by greg-schroeder** 2023-07-24 18:35 UTC
Labels: External, Daily, Help Wanted

**Comment by s77rt** [comment] 2023-07-25 18:10
@tienifr Let's discuss in Slack.
