### ISSUE TITLE
[$500] Log in - New accounts on domain control that have had a bill split with them cannot login on a domain controlled account.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30121] opened 2023-10-21 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697856462347089

## Action Performed:
1. Split bill with new user that is using an email on a domain controlled account
2. Go try to sign up with that user you split a bill with in 1

## Expected Result:
User can sign up and get a magic code

## Actual Result:
Error message, blocked from signing in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![image (15)](https://github.com/Expensify/App/assets/93399543/2ab12dce-bb27-4fa8-a2bb-0480f325aff6)
![image (14)](https://github.com/Expensify/App/assets/93399543/1a50d408-f684-455b-bcdd-613a2ce51cad)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01237b5b3352b4c2e4</li>
        <li>Upwork Job ID: 1715751193396441088</li>
        <li>Last Price Increase: 2023-12-16</li>
    </ul>
</details>

**Comment by debragail** [comment] 2023-10-21 15:50
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

New users that have had a bill split with them cannot login to a domain controlled account.  This occurs on Get Started on the homepage on staging.


### What changes do you think we should make in order to solve the problem?

Make sure the bill split account are assigned a account id that belongs to the domain controlled account if the domains are the same.  It seems the account details are not able to be retrieved.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/ValidateLoginPage/index.js#L46

### What alternative solutions did you explore? (Optional)



Change error mess

**Comment by isabelastisser** [comment] 2023-10-24 16:14
Hey @0xmiroslav can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment] 2023-10-25 18:21
@0xmiroslav can you please review the proposal above?

**Comment by debragail** [comment] 2023-10-27 23:47
Please let me know if you accept since this is overdue.

**Comment by isabelastisser** [comment] 2023-10-30 16:13
@0xmiroslav, any updates?

**Comment by isabelastisser** [comment] 2023-11-03 18:27
Waiting for proposals.

**Comment by debragail** [comment] 2023-11-05 21:20
I am working on a new proposal.

**Comment by debragail** [comment] 2023-11-05 23:14
I need help recreating the issue:

https://expensify.slack.com/archives/C01GTK53T8Q/p1699217765377179

**Comment by isabelastisser** [comment] 2023-11-06 15:51
Hey @0xmiroslav can you please follow up on the commend above? Thanks!

**Comment by isabelastisser** [comment] 2023-11-09 16:49
Waiting for proposals!

**Comment by isabelastisser** [comment] 2023-11-13 19:30
Still waiting for proposals.

**Comment by isabelastisser** [comment] 2023-11-18 01:42
Still waiting for proposals.

FYI I'm OOO until Nov 27.

**Comment by isabelastisser** [comment] 2023-11-30 20:34
Still waiting for proposals!

**Comment by isabelastisser** [comment] 2023-12-04 16:59
Still waiting for proposals!

**Comment by isabelastisser** [comment] 2023-12-07 17:15
Still waiting for proposals!

**Comment by isabelastisser** [comment] 2023-12-11 15:18
@0xmiroslav @debragail, can you please clarify what scenarios the bug can occur in? Is this bug isolated to splitting a bill with someone?

**Comment by isabelastisser** [comment] 2023-12-14 18:03
Bump @0xmiroslav @debragail on my question above. thanks!

**Comment by isabelastisser** [comment] 2023-12-15 17:33
@0xmiroslav @debragail, can you please follow up on my questions above?

Thanks!

**Comment by Tony-MK** [comment] 2023-12-17 03:00
Hey, @isabelastisser and @0xmiroslav, I wanted to provide my investigation findings. I hope it helps. 

This issue requires a backend fix and possibly some frontend changes to match because the user of the Gmail-controlled account can solve it by inviting the user of the new domain-controlled account to the domain on Old Dot. The problem might be the server is incorrectly authenticating `optimistically` created domain-controlled accounts. Instead of splitting a bill, I started a chat and got the same error message from the server. 

Furthermore, I got the same error message when using a Gmail-controlled account to a domain-controlled employee account (like the description) and a Gmail-controlled admin account to a domain-controlled employee account.

Could you verify that my analysis is correct? Thanks 😄 

#### Error message from server
![macOS - Chrome](https://github.com/Expensify/App/assets/22982173/02890438-1086-489f-b3e4-d5eff6c4e770)

**Comment by Tony-MK** [comment] 2023-12-17 03:02
Hey, @isabelastisser and @0xmiroslav, I wanted to provide my investigation findings. I hope it helps. 

This issue requires a backend fix and possibly some frontend changes to match because the user of the Gmail-controlled account can solve it by inviting the user of the new domain-controlled account to the domain on Old Dot. 

The problem might be the server is incorrectly authenticating `optimistically` created domain-controlled accounts.

Instead of splitting a bill, I started a chat and got the same error message from the server. 

Furthermore, I got the same error message when using a Gmail-controlled account to a domain-controlled employee account (like the description) and a Gmail-controlled admin account to a domain-controlled employee account.

Could you verify that my analysis is correct? 
Thanks 😄 

#### Error message from server
![macOS - Chrome](https://github.com/Expensify/App/assets/22982173/02890438-1086-489f-b3e4-d5eff6c4e770)

**Comment by isabelastisser** [comment] 2023-12-18 15:48
Thanks for the details @Tony-MK! @0xmiroslav, can you please review and follow up on the explanation above?

**Comment by isabelastisser** [comment] 2023-12-18 16:59
Do we need an Expensify engineer to work on this @0xmiroslav ?

**Comment by debragail** [comment] 2023-12-19 01:49
@isabelastisser should I still work on the issue?

**Comment by blimpich** [comment] 2023-12-19 17:26
> yes, at least on backend part. Hope @blimpich would help with this issue 🙏

Acknowledging this. I think this is worth working on but I am currently prioritizing other issues. Thank you @0xmiroslav for summarizing the state of this issue at the moment. I don't know when I'll have time to work on this, but hopefully sometime next week.

**Comment by isabelastisser** [comment] 2023-12-22 16:25
This will be reviewed next week.

**Comment by blimpich** [comment] 2023-12-22 17:23
Demoting to weekly until I know that I can work on this daily.

**Comment by mvtglobally** [comment] 2023-12-31 06:10
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-01-02 17:56
Not overdue.

**Comment by mvtglobally** [comment] 2024-01-11 06:03
Issue not reproducible during KI retests. (Second week)

**Comment by blimpich** [comment] 2024-01-11 18:18
Not overdue. Not reproducing so might be a non-issue. Will let this sit for now.

**Comment by isabelastisser** [comment] 2024-01-11 18:56
@blimpich I'll close this since it cannot be reproduced.

**Closed by isabelastisser** 2024-01-11 18:56 UTC
Labels: External, Engineering, Weekly, Internal, Help Wanted, Bug
