### ISSUE TITLE
IOS - Search - List of users is hidden after tap on Search icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10105] opened 2022-07-26 03:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Tap on Search icon

## Expected Result:
List of users is hidden after tap on Search icon

## Actual Result:
Users are visible after tap on Search icon

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.86.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180914380-13cc74d0-5b84-49e2-b964-ebf2511809b2.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-07-26 17:40
I could reproduce this and it seems related to the KeyboardAvoidingView changes @jasperhuangg

**Comment by luacmartins** [comment] 2022-07-26 17:56
Removing the `KeyboardSpacer` component from [here](https://github.com/Expensify/App/blob/92186e50db3d37064a07d0a5c9ddcf81df39d3ad/src/pages/SearchPage.js#L192) fixes the issue, but I suspect this was caused by changes in `ScreenWrapper`.

**Comment by jasperhuangg** [comment] 2022-07-26 18:16
@luacmartins Ah, I bet the problem is caused by the KeyboardSpacer being wrapped inside of a KeyboardAvoidingView.

**Comment by luacmartins** [comment] 2022-07-26 21:18
This seems to be fixed with this revert - https://github.com/Expensify/App/pull/10113. Closing this issue.

**Closed by luacmartins** 2022-07-26 21:18 UTC
Labels: DeployBlockerCash, Engineering, Hourly
