### ISSUE TITLE
[$2000] Web/mweb - Chat -  LHN does not display after signing out/signing in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11011] opened 2022-09-15 14:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11006

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with user applausetester+0901abb@applause.expensifail.com, using the password Feya86Katya

## Expected Result:
Chat list is loading without refreshing the page

## Actual Result:
Chat list displays after refreshing

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web
- Desktop

**Version Number:** 1.2.0.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190432950-a06c4214-0b0b-458f-a6a3-0b1082d63f32.mp4

https://user-images.githubusercontent.com/93399543/190436777-c3655c14-952c-4369-8c31-d4debd5cbf76.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-09-15 14:49
I can't reproduce this on `v1.2.0-4`, with my own account, or with the tester credentials provided. Tested on web (Chrome) and mWeb (Android).

**Comment by kbecciv** [comment] 2022-09-15 14:52
Adding Desktop as well for environment list
![Screen Shot 2022-09-15 at 10 28 02 AM](https://user-images.githubusercontent.com/93399543/190436299-d8131947-88b0-4b90-bf62-f97b572801a3.png)

**Comment by Julesssss** [comment] 2022-09-15 15:05
Asked [here](https://expensify.slack.com/archives/C03SSAQ7P/p1663253492702379) for someone else to confirm, as I wasn't able to reproduce

**Comment by Julesssss** [comment] 2022-09-15 15:05
Asked [here](https://expensify.slack.com/archives/C03SSAQ7P/p1663253492702379) for someone else to confirm, as I wasn't able to reproduce

**Comment by mountiny** [comment] 2022-09-15 15:21
Updating the title to be more accurate.

**Comment by johnmlee101** [comment] 2022-09-15 17:09
This happens while OpenApp is processing, and the result of OpenApp looks fine, so its the render that follows thats failing?

**Comment by francoisl** [comment] 2022-09-15 17:13
I can consistently reproduce on web with the account applausetester+0901abb@applause.expensifail.com. Should we just revert https://github.com/Expensify/App/pull/10784 for now?

**Comment by luacmartins** [comment] 2022-09-15 17:21
@francoisl can we confirm that reverting https://github.com/Expensify/App/pull/10784 fixes the issue?

**Comment by francoisl** [comment] 2022-09-15 17:32
No because I don't think anyone was able to reproduce the issue in dev in the first place, but the idea is:

- this blocker was introduced by #11006 
- https://github.com/Expensify/App/pull/11006 was an attempt to fix an issue introduced by https://github.com/Expensify/App/pull/10784

**Comment by johnmlee101** [comment] 2022-09-15 18:07
We'd have to revert the CP as well if we go this route, right?

**Comment by francoisl** [comment] 2022-09-15 18:12
Yes we'd either revert the CP first, or there would be a conflict if we directly revert https://github.com/Expensify/App/pull/10784. We can do both reverts in one PR though, it's not really a problem.

**Comment by johnmlee101** [comment] 2022-09-15 18:19
Okay I'd say to prevent blocking another deploy let's do that. Order of operations is
1. Create the revert for https://github.com/Expensify/App/pull/11006
2. Add the revert for https://github.com/Expensify/App/pull/10784 into the mix
3. CP to staging label
4. Test 

Correct?

**Comment by francoisl** [comment] 2022-09-15 18:29
Yes and we can make steps 1 and 2 in one PR - give me a second to double check.

**Comment by francoisl** [comment] 2022-09-15 19:48
We can reproduce this in production too - it _might_ be related to a recent Web-E change though, let's keep this open as a high-priority issue.

**Comment by johnmlee101** [comment] 2022-09-20 21:33
No update, still keeping this in mind as we move forward (I haven't checked reproducibility today)

**Comment by mallenexpensify** [comment] 2022-09-23 01:18
@kbecciv can you see if you can reproduce? Thx

**Comment by kbecciv** [comment] 2022-09-23 14:31
@mallenexpensify Chat list displays after signing in

https://user-images.githubusercontent.com/93399543/191984602-c5250da7-da02-485b-a924-7b9dba6d417a.mp4

**Comment by mallenexpensify** [comment] 2022-09-23 22:11
@kbecciv weird, it looks like, in the vid in the OP, that NOTHING loaded on the page til refresh.  For the test yesterday, it appears LHN loads but the main chat window doesn't.  Any idea why that might be different? 
I tested with your credentials in a Chrome incognito window and had the same result as your vid above, LHN loaded but nothing in the main chat. Not sure why. 

When I tested with my expensicorp.com account LHN and main chat were loading (with/without a pinned chat at top) ¯\_(ツ)_/¯

**Comment by francoisl** [comment] 2022-09-26 20:21
The issue is when you sign out and then sign in again. So essentially, this:

1. Open new incognito window, go to https://staging.new.expensify.com/
2. Sign in to the account applausetester+0901abb@applause.expensifail.com / Feya86Katya (this step should work)
3. Sign out
4. Sign in to the same account again
     - The LHN won't be displayed correctly

I checked the API requests and responses and they're identical (minus request IDs and such) in the two sign ins. I also tried clearing cookies and data from Onyx before signing in again, but the issue persists.

I noticed that if you refresh the page before attempting to sign in a second time though, the app will load correctly. Not sure what to make of it, could it mean that some component's state could be messed up on the sign-in page, and that borks the app when signing in again?

**Comment by johnmlee101** [comment] 2022-10-03 17:30
Feeling a bit lost in debugging this, going to open this up to external to help debug and solve this issue

**Comment by luacmartins** [comment] 2022-10-04 17:39
lol why does Melvin keep assigning internal engineers? Am I the CME for this issue?

**Comment by mallenexpensify** [comment] 2022-10-04 23:34
Yeah, @luacmartins , you're the CME, John and Francois aren't on the CME team.

**Comment by Christinadobrzyn** [comment] 2022-10-05 05:26
Created job in Upwork: 

Internal posting: https://www.upwork.com/ab/applicants/1577530367682449408/job-details
External posting: https://www.upwork.com/jobs/~01f8b292800ec04b69

**Comment by Christinadobrzyn** [comment] 2022-10-07 06:50
Waiting for proposals

**Comment by luacmartins** [comment] 2022-10-11 16:39
Gonna move this to a weekly while we wait for proposals.

**Comment by Christinadobrzyn** [comment] 2022-10-17 05:36
Doubling price to $500

**Comment by Christinadobrzyn** [comment] 2022-10-25 08:06
doubled price - still waiting on proposals

**Comment by luacmartins** [comment] 2022-11-02 16:55
Still looking for proposals

**Comment by Christinadobrzyn** [comment] 2022-11-03 06:24
Price doubled $2000

**Comment by luacmartins** [comment] 2022-11-03 20:08
I'm unable to reproduce this. @kbecciv could you please ask the team to try to reproduce on the latest build?

**Comment by kbecciv** [comment] 2022-11-04 15:05
Issue is not reproduced in build v1.2.23-9

https://user-images.githubusercontent.com/93399543/200008078-feb14692-3656-4f75-b3ff-c3d2c5b5c252.mp4

**Comment by luacmartins** [comment] 2022-11-04 18:22
Thanks @kbecciv! Ok, I'm gonna close this since we can't reproduce the issue. My guess is that the performance improvements we made to the LHN fixed this somehow. Please reopen if this happens again.

**Closed by luacmartins** 2022-11-04 18:22 UTC
Labels: External, Engineering, Weekly, Improvement, Help Wanted, Bug
