### ISSUE TITLE
[$500] [Ideal Nav] Web - Web-OldDot Transition - Not here page shown when opening a free policy from OD

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38476] opened 2024-03-18 15:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4428043
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to https://staging.expensify.com/
with an account with at least on Free policy (can be added from ND)
2. Hover over Settings > Workspaces
3. Click on the Free policy

## Expected Result:
You're redirected to NewDot, you're logged in with the same account as in OldDot and that the Workspace settings page is displayed

## Actual Result:
Not found page is shown

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4b0a86b2-091c-460f-bd74-7c79795e6c2a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e87bdd27eb99701d</li>
        <li>Upwork Job ID: 1770087739223650304</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-18 15:12
@johncschuster I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-03-19 11:46
The transition has a `exitTo` params that contains a workspace route, `workspace/{workspaceID}`, but the recent ideal nav 2 [PR](https://github.com/Expensify/App/pull/37421) updates the route to be `settings/workspaces/{workspaceID}`.

**Comment by johncschuster** [comment] 2024-03-19 13:47
@kbecciv is this bug reproducible only when selecting a **Free Plan**? I ask because we intend on deprecating the Free Plan in Q1, so I'm not sure it's worth fixing this one unless the behavior is reproducible when opening a non-Free Plan.

Can you try testing that?

**Comment by trjExpensify** [comment] 2024-03-19 13:54
Yeah, let's fix this. We're going to deploy the same method of redirecting different workspace plan types from OldDot to NewDot in short order. Starting with those that were formally of `TYPE_FREE`. CC: @WojtekBoman @adamgrzybowski @mountiny

**Comment by trjExpensify** [comment] 2024-03-19 14:02
@WojtekBoman is going to look at this: https://expensify.slack.com/archives/C036QM0SLJK/p1710856720495139?thread_ts=1710800292.533099&cid=C036QM0SLJK

**Comment by WojtekBoman** [comment] 2024-03-19 14:16
Path to the workspace settings has been changed from `/workspace/:id` to `settings/workspaces/:id`, so we should update `exitTo` param when we open ND from OD. This problem might occur also when we navigate from OD to other workspace pages in ND which url starts with `settings/workspaces/:id`

**Comment by Piyush-Desai** [comment] 2024-03-19 14:39
Hello @trjExpensify, 

I hope this message finds you well. 

I recently sent an email to request access to the Slack channel at contributors@expensify.com from my email address superherotigerfish@gmail.com. 

I'm eager to contribute to resolving this bug, but I'm also quite new to this platform. If it's feasible on your end, could you kindly add me to the channel? 

Your assistance would be greatly appreciated. 

Thank you for considering my request.

**Comment by trjExpensify** [comment] 2024-03-19 16:00
We're going to need both internal and external changes for this one, so @WojtekBoman & @mountiny are going to pick it up as a ideal nav v2 follow-up.

**Comment by trjExpensify** [comment] 2024-03-19 16:01
> Hello @trjExpensify,
> 
> I hope this message finds you well.
> 
> I recently sent an email to request access to the Slack channel at [contributors@expensify.com](https://www.expensify.com/_support/?supportEmail=contributors%40expensify.com&comment=better%20supportal%20issue%20nubmer%3A%2038476&location=_support/)![](chrome-extension://bjeimjfbfekhidogekjmbbejcokfnkcc/clipboard.png) from my email address [superherotigerfish@gmail.com](https://www.expensify.com/_support/?supportEmail=superherotigerfish%40gmail.com&comment=better%20supportal%20issue%20nubmer%3A%2038476&location=_support/)![](chrome-extension://bjeimjfbfekhidogekjmbbejcokfnkcc/clipboard.png).

👋 Hey @Piyush-Desai, thanks for joining our community! Someone will be in touch as a reply to your email to contributors@expensify.com in due course. In the meantime, feel free to check out our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by mountiny** [comment] 2024-03-19 22:20
@WojtekBoman I think that the new route is being used for a while and the web transition should take you to the latest version so I think we can just move ahead without holding or waiting on anything. I made the backend PR for this

**Comment by mountiny** [comment] 2024-03-19 22:45
The backend PR is merged and it will direct to the correct path now

**Comment by mountiny** [comment] 2024-03-19 23:14
@WojtekBoman I am actually wondering if any App changes are needed here. again, this transition takes you to web, I feel like at the moment we do not have to worry that much about the old routes.

Basically that would be someone with desktop up which was not updated in 2+ weeks where they might get not found page. I dont think we have some standardized approach for this but I feel like we dont have to add more fixes for this

**Comment by WojtekBoman** [comment] 2024-03-20 14:07
Ok, if anything happens, I have a branch with the solution ready

**Comment by trjExpensify** [comment] 2024-03-25 19:07
@mountiny can we close this?

**Comment by mountiny** [comment] 2024-03-29 23:30
yes

**Closed by mountiny** 2024-03-29 23:30 UTC
Labels: Reviewing, External, Daily, Bug
