### ISSUE TITLE
Software keyboard covers part of the submit button on login page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11701] opened 2022-10-10 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the login page
1. Tap on the text input to enter text
2. Click Continue
3. Password field will be shown

## Expected Result:
The software keyboard should open, and the text input, submit button, etc... should shift up such that it's completely in view

## Actual Result:
The submit button is partially covered.

## Workaround:
n/a – just ignore the visual bug

## Platform:
Where is this issue occurring?

- Mobile Web (Android Chrome)

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-10-10 16:59
Interestingly, if you scroll the page up and down with the keyboard open, then this bug no longer happens. You can completely close the keyboard, scroll back to the top, and then tap on the TextInput and it does not happen again. If you then refresh the page, then it will happen again.

**Comment by tgolen** [comment] 2022-10-13 17:05
I removed the HOLD on this and assigned it to me because this is fixed in https://github.com/Expensify/App/pull/11586

**Comment by JmillsExpensify** [comment] 2022-11-03 03:51
Linked PR hit production 12 hours ago. I tested this and all looked good. @tgolen are you seeing the same?

**Comment by tgolen** [comment] 2022-11-03 13:21
hey @JmillsExpensify, thanks for testing that! I had originally thought that this was fixed by my PR, and included it in the list of fixes. However, after some testing, we found that there was still an issue on Android Chrome. You can see here, on the password form, the sign in button is still partially covered:

![image](https://user-images.githubusercontent.com/1228807/199731643-f806e7f9-4e64-4999-a96a-bf802eaaeb4e.png)

**Comment by JmillsExpensify** [comment] 2022-11-03 13:24
Oh nice! I tested on iOS and wasn't able to see it anymore. I'll update the testing reproduction steps and remove Safari so this issue focuses on Android wWeb moving forward. What do you think?

**Comment by tgolen** [comment] 2022-11-03 13:30
Yeah, sounds great! I also saw that it was working on iOS 👍

**Comment by JmillsExpensify** [comment] 2022-11-03 14:34
Nice, done! In other news we really need a way for Bug Zero to test Android. The majority of the team doesn't have a way to do it right now.

**Comment by JmillsExpensify** [comment] 2022-11-03 18:18
That would be really awesome, thanks for the heads up.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:15
Contributors - this issue is open for proposals! The related Upwork job is here: https://www.upwork.com/jobs/~010b091da824bb7cb2.

**Comment by AmanuelAsfaw** [comment] 2022-11-07 12:52
we can customize the login form height  by using eventListener in the keyboard show and hide status, using the windows height size decrease the size of keyboard and show the login form.

> at show status will decrease the size of keyboard from window-height 

> at hide status we will use the full window-height for the login-form


we use Animated and UIManager class( components) from 'react-native'

**Comment by tgolen** [comment] 2022-11-07 15:31
When I was initially looking at this, I felt like the root cause of the problem came from this style:

https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/styles/styles.js#L943

I think the top margin is always going to be a % of the page height, and the page height doesn't change when the keyboard is open, then the `marginTop` is the wrong way to implement the spacing in the design.

Could we instead look at changing that `marginTop` style to something which is based on `flex` layout and maybe has a max height that is equal to whatever the 40% margin height was adding?

**Comment by tgolen** [comment] 2022-11-07 16:02
Maybe it was actually this style:

https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/styles/styles.js#L952

I think it's maybe one of them, if not both

**Comment by JmillsExpensify** [comment] 2022-11-08 19:43
Still waiting for proposals that address the root cause and issue.

**Comment by AmanuelAsfaw** [comment] 2022-11-11 13:21
Very sorry for being too late to respond, I clone the source code from git
and try to test from my local machine but when I try to run a command for
web `npm run web` it doesn't work for me. I corrected my npm(8.11.0) and
node(16.15.1) version but it still does not work for me.

I see a helper component which is a HOC to solve this problem in your
source code
https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js
 WithKeyboardState
<https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js>
it give the status of keyboard showing or not, using that status we can
change the  style using props in the line
https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/pages/signin/SignInPageLayout/SignInPageContent.js#L63
 SignInPageContent
<https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/pages/signin/SignInPageLayout/SignInPageContent.js#L63>

in my proposal we have to use the state of keyboard showing or not status
in the  SignInPageContent
<https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/pages/signin/SignInPageLayout/SignInPageContent.js#L63>
  page

if the keyboard shows get first we calculate windows-height,
keyboard-height, currently-focused-field-height then decrease the
keyboard-height and  currently-focused-field-height from the
windows-height we can get the top marginTop for that KeyboardAvoidingView

or we use the calculated proportional value of marginTop using % for the
above value we get.

I put a snippet code on git
https://gist.github.com/AmanuelAsfaw/1e87af061927fd21f92be7527a3d5e93
Source-code
<https://gist.github.com/AmanuelAsfaw/1e87af061927fd21f92be7527a3d5e93>

**Comment by JmillsExpensify** [comment] 2022-11-11 19:53
Thanks for the response. A quick heads up that @tgolen is out of office until next week, though for the sake of clarity, we do require that for a proposal to be accepted, it has to follow [our guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job). Here's an [example of a proposal](https://github.com/Expensify/App/issues/11236#issuecomment-1256398719) that was later accepted. Thank you!

**Comment by AmanuelAsfaw** [comment] 2022-11-12 12:10
Thank you for the clarification. I wait for the response

**Comment by JmillsExpensify** [comment] 2022-11-14 19:53
Open source community - we're still awaiting for approved proposals! It's been a week, so we're doubling the price to $500. Upwork job is here: https://www.upwork.com/jobs/~010b091da824bb7cb2.

**Comment by AmanuelAsfaw** [comment] 2022-11-15 08:26
Great, thanks for the update, I think I finished the process on github, so
I can submit the proposal on Upwork?

**Comment by AmanuelAsfaw** [comment] 2022-11-16 14:30
### Proposal

To get the Keyboard height and showing status using this higher order component [App/src/components/withKeyboardState.js](https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js) and add some features on the [below line 8](https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js#L8) 
https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js#L8
 add this [code](https://gist.github.com/AmanuelAsfaw/1e87af061927fd21f92be7527a3d5e93#file-withkeyboardstate-js-L5-L6) 
`keyboardHeight: PropTypes.number.isRequired,`

,  change [line 15 ](https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js#L15-L17) https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js#L15-L17 to this [code ](https://gist.github.com/AmanuelAsfaw/1e87af061927fd21f92be7527a3d5e93#file-withkeyboardstate-js-L12-L15) 

`
           this.state = {
                isShown: false,
                keyboardHeight: 0,
            };
`
 and change [line 23 - 25](https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js#L23-L25) https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/components/withKeyboardState.js#L23-L25 to [code](https://gist.github.com/AmanuelAsfaw/1e87af061927fd21f92be7527a3d5e93#file-withkeyboardstate-js-L21-L23) 
`
                (event) => {
                    this.setState({isShown: true, keyboardHeight: event.endCoordinates.height });
                },
`
now we get the height of Keyboard, now we can access the keyboard height form [SingInPage](https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/pages/signin/SignInPageLayout/SignInPageContent.js)

**Now access height and change `mirginTop` in side the page while the keyboard showing**
On [line 63](https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/pages/signin/SignInPageLayout/SignInPageContent.js#L63) https://github.com/Expensify/App/blob/debeb86a0a1134c578331499a25bb9096b8dc8b0/src/pages/signin/SignInPageLayout/SignInPageContent.js#L63 check the status of keyboard showing and if showing use the calculate `marginTop` value this [code](https://gist.github.com/AmanuelAsfaw/1e87af061927fd21f92be7527a3d5e93#file-signinpagecontent-js-L24-L26)
`          props.isShown? {
                marginTop: getCalculateMarginTop(),
           }: styles.signInPageNarrowContentMargin : {},`
prepare function to get the calculate `marginTop `value

```
function getCalculateMarginTop(){
    const windows_height = Dimensions.get('window').height;
    const keyboard_height = props.keyboardHeight ? props.keyboardHeight : 0;
    let current_focused_field_height = 0;
    
    const { State: TextInputState } = TextInput;
    const current_focused_field = TextInputState.currentlyFocusedField();

    UIManager.measure(current_focused_field, (originX, originY, width, height, pageX, pageY) => {
        current_focused_field_height = height;
    });

    const margin_top = windows_height - keyboard_height - current_focused_field_height;
    return margin_top;
}

**Comment by tgolen** [comment] 2022-11-16 22:32
@AmanuelAsfaw Thank you for the proposal. I think that is kind of on the wrong track though. I'm going to take this over and explore my theory that I posted here: https://github.com/Expensify/App/issues/11701#issuecomment-1305784305

**Comment by JmillsExpensify** [comment] 2022-11-17 05:36
Thanks for closing the loop @tgolen.

**Comment by tgolen** [comment] 2022-11-17 23:15
I got some good progress on this today and have a WIP PR here: https://github.com/Expensify/App/pull/12848

I should be able to wrap it up tomorrow. 

It basically entailed an entire refactoring of how that view is laid out, and it's much better now.

**Comment by JmillsExpensify** [comment] 2022-11-18 08:12
@tgolen Super great to hear! 

@rushatgabhane done.

**Comment by tgolen** [comment] 2022-11-18 15:11
I've got the PR mostly wrapped up. As I was creating screenshots, I noticed a regression on the sign-in form for iOS, so I'll be chasing that down today.

**Comment by JmillsExpensify** [comment] 2022-11-22 07:05
@rushatgabhane I invited you to this issue via Upwork, but actually, looking at the linked PR I think we handled the testing internally. Is that right?

**Comment by JmillsExpensify** [comment] 2022-11-26 22:31
Thanks for jumping into the PR. I see your review/comments in testing now.

**Comment by JmillsExpensify** [comment] 2022-11-28 19:26
@tgolen Do you think you'll have time to circle back and merge this PR this week?

**Comment by tgolen** [comment] 2022-11-28 23:06
Yeah! I was able to work on it this afternoon and it's all ready for review again! I think having it merged this week is looking good.

**Comment by tgolen** [comment] 2022-11-30 15:56
This is looking really close. Only one minor issue was found in yesterday's reviews (and a few bugs were found which also happen in `main`, but I am not addressing those in the PR).

**Comment by JmillsExpensify** [comment] 2022-12-01 06:02
Awesome, everything is ready for C+ payment, so now is a good time to circle back on regression testing. We have a pretty extensive QA test in the linked PR, which I'm copying below. 

1. Be signed out
2. Have your email address entered so that you see the password form
3. For native platforms, verify the password form is not covered by the software keyboards
4. For all other platforms, verify that the form and page layout looks correct (best to compare it to production).

For web specifically:
1. Test the page at widths less than 800 (form should always be centered and have a max width of 400px. The form should NOT span the entire width of the page for widths between 400 and 800). 
2. Test the page at widths between 801 and 1024 (the form should no longer take up the top half of the page and it should look just like any width greater than 1024)
3. Test the page at widths greater than 1024 (form should be a fixed width of ~400px on the left side of the page)

Test keyboard dismissing on native (iOS and Android):
1. On both the enter email and enter password forms, tap into the text input
2. Tap outside of the input and verify the keyboard is dismissed and verify the input does not have focus (it does not have a blue border)
3. On the enter email form, enter the email of an existing account and either tap continue or press enter
4. Verify the keyboard remains shown on the password form and the password text input has focus
5. On the email form, enter an email address that doesn't have an account yet and press enter (or click continue)
6. Verify that you are shown the message that a link has been sent to you and verify the keyboard has been dismissed

- [ ] Verify that no errors appear in the JS console

### Offline tests
1. Go offline
2. Verify there is an offline indicator under the sign in button
3. Go online
4. Verify the offline indicator goes away

I checked TestRail and we lack a general Sign-in test that tests a variety of things, so I actually think we should create a new test as as result. @tgolen let me know if you agree and I'll get that in motion.

**Comment by tgolen** [comment] 2022-12-01 18:03
Yeah, I think it's a good idea to get some regression tests created around this form.

**Comment by tgolen** [comment] 2022-12-02 15:53
Seems like there are not many changes being requested in the PR anymore. There was a conflict that I needed to solve, but it looks promising to get merged today.

**Comment by JmillsExpensify** [comment] 2022-12-08 02:55
PR is merged.

**Comment by JmillsExpensify** [comment] 2022-12-10 02:09
I went ahead and paid out C+ for the internal PR review. We'll close this issue when it hits production.

**Comment by puneetlath** [comment] 2022-12-13 15:03
@aimane-chnaif sorry for the confusion. I think @JmillsExpensify probably didn't realize there were two C+ on this one. I sent you a hiring offer.

**Comment by puneetlath** [comment] 2022-12-13 15:17
That was the bounty for this issue at the time, since this pre-dates the increase to $1000.

**Closed** 2022-12-14 15:20 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Bug
