### ISSUE TITLE
Web - #room-Red dot with message "A room with this name already exists"very close to the border

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20420] opened 2023-06-07 23:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Sign in with any account with a workspace room
3. Disable the internet connection in the device
4. Click the header of the workspace room to open the room details page
5. Click "Settings"
6. Rename the room and hit save
7. Sign into the same account on another device or incognito window
8. Create another workspace room on the same workspace with the same name
9. In the main testing device - enable the internet connection

## Expected Result:
Error message and red dot aligned with other room settings.

## Actual Result:
Red dot very close to the border of settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.3

**Reproducible in staging?:** Yes

**Reproducible in production?:**Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6084132_Untitled (1)](https://github.com/Expensify/App/assets/78819774/eea9eeaf-c970-447c-9c21-203947cf6fba)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-06-07 23:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - #room-Red dot with message "A room with this name already exists"very close to the border
### What is the root cause of that problem?
there `errorRowStyles` is no here
https://github.com/Expensify/App/blob/5157478af049d7b35456a8355ffaca60571e72df/src/pages/settings/Report/ReportSettingsPage.js#L118-L122
### What changes do you think we should make in order to solve the problem?
add `errorRowStyles={styles.mh4}` to OfflineWithFeedback

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2023-06-08 00:52
I'm OOO, reassigning!

**Comment by joekaufmanexpensify** [comment] 2023-06-08 14:09
@isabelastisser I think we're supposed to keep ourselves assigned as well when re-assigning issues for OOO now, per [this update](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799). So going to add you back as an additional assignee for when you're back from OOO!

**Comment by joekaufmanexpensify** [comment] 2023-06-08 14:09
I will triage this today!

**Comment by joekaufmanexpensify** [comment] 2023-06-08 19:04
I don't really think this is a bug/that we need to do anything here. The error message is correct, and while the red dot is near the border, it doesn't quite touch it. Going to close this one for now. But LMK if anyone else feels differently about this!

**Closed by joekaufmanexpensify** 2023-06-08 19:04 UTC
Labels: Daily, Bug

**Comment by ahmedGaber93** [comment] 2023-06-09 18:57
@joekaufmanexpensify 
I think it will be more consistent if we apply the input same margin for both input view and error view.

![Screenshot 2023-06-09 at 8 52 27 PM](https://github.com/Expensify/App/assets/41129870/e55f1bc8-1b40-4419-b30c-7ad12c00f598)
