### ISSUE TITLE
[HOLD on regression test ] Workspace - Crash when removing a user offline in Manage members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13508] opened 2022-12-10 21:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into any valid account
3. Tap on Profile > Workspace > Manage members
4. Invite any member
5. Turn off the internet connection
6. Remove a user from the workspace while offline

## Expected Result:
User expects the name to get crossed out and then afterwards removed when the connection is reestablished.

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.38.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206875368-df02123c-4a65-40c3-be0f-c9685f286d3c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2022-12-11 06:36
### **Proposal**

This is a regression from #13398, especially this change:
![image](https://user-images.githubusercontent.com/108292595/206889906-4f4e7a5f-8451-49ef-8f43-1af6e3eec198.png)

so crash happens on these 2 lines:
https://github.com/Expensify/App/blob/10dd188fea5793648da7dcf6d113361b35fed866/src/components/OptionRow.js#L85-L86
When offline, `props.style` is set like this:
![Screenshot](https://user-images.githubusercontent.com/108292595/206889472-c8e63fce-f1b5-4e8f-91ac-7643033992f1.png)
So `{} inside [] inside []` in style doesn't work and it crashes on web

**Solution:**
We should flatten those styles:
```diff
- const displayNameStyle = [styles.optionDisplayName, ...textUnreadStyle, props.style];
+ const displayNameStyle = StyleSheet.flatten([styles.optionDisplayName, ...textUnreadStyle, props.style]);
- const alternateTextStyle = [textStyle, styles.optionAlternateText, styles.textLabelSupporting, props.style];
+ const alternateTextStyle = StyleSheet.flatten([textStyle, styles.optionAlternateText, styles.textLabelSupporting, props.style]);
```
or we can use original code which uses StyleUtils.combineStyles:
```diff
- const displayNameStyle = [styles.optionDisplayName, ...textUnreadStyle, props.style];
+ const displayNameStyle = StyleUtils.combineStyles([styles.optionDisplayName, ...textUnreadStyle], props.style);
- const alternateTextStyle = [textStyle, styles.optionAlternateText, styles.textLabelSupporting, props.style];
+ const alternateTextStyle = StyleUtils.combineStyles([textStyle, styles.optionAlternateText, styles.textLabelSupporting], props.style);
```

**Comment by aldo-expensify** [comment] 2022-12-12 19:33
@situchan thanks!, that indeed seems to be the cause and what you proposed fixes it. I wondering a bit now when do we choose to use `StyleUtils.combineStyles` and when `StyleSheet.flatten`. I tested the second and it also works and I see we are using a few lines below.

**Comment by aldo-expensify** [comment] 2022-12-12 20:16
Ready for review: https://github.com/Expensify/App/pull/13525

**Comment by chiragsalian** [comment] 2022-12-13 22:02
The CP PR passed QA. Removing deploy blocker label.

**Comment by aldo-expensify** [comment] 2022-12-15 23:31
@kbecciv was this issue catch while running the test suite or doing QA?

**Comment by stephanieelliott** [comment] 2022-12-22 20:49
Erm this was fixed internally, no payments needed here! 

Will leave this open til we've agreed on how to handle the regression test -- I've started the discussion for the test case here: https://expensify.slack.com/archives/C01SKUP7QR0/p1671741994888809

**Comment by situchan** [comment] 2022-12-22 21:27
I appreciate if I can get compensation here since I found the exact root cause and my solution was used.
cc: @aldo-expensify

**Comment by stephanieelliott** [comment] 2023-01-03 16:20
Hey @situchan, thanks for raising that point! Chatted with @aldo-expensify and we agree that your comment did help save us quite a bit of time with the investigation. I created an Upwork job to pay you out for this, can you please claim it when you get a chance? https://www.upwork.com/jobs/~01d6c0e9c64b2148e8

**Comment by situchan** [comment] 2023-01-04 03:06
@stephanieelliott applied. Thank you

**Comment by situchan** [comment] 2023-01-06 09:43
@stephanieelliott accepted your offer

**Comment by stephanieelliott** [comment] 2023-01-06 14:49
Thanks @situchan, I've paid you in Upwork! 

No regression test needed for this one (context [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1671834567374889?thread_ts=1671741994.888809&cid=C01SKUP7QR0)), so we can close this one out!

**Closed by stephanieelliott** 2023-01-06 14:49 UTC
Labels: Reviewing, Daily, Internal, Bug
