### ISSUE TITLE
[$250] [HOLD #43494][Search v1] Category field does not stay put when clicking on To title after enabling it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44198] opened 2024-06-22 13:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Account has only one workspace.
- Categories, Tags and Taxes features are disabled.
- Account has at least one p2p expense.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Click To title a few times.
4. Go to workspace settings > More features.
5. Enable Categories.
6. Return to Search.
7. Click `To` title a few times.
8. Go to workspace settings > More features.
9. Disable Categories.
10. Return to Search.
11. Click `To` title a few times.

## Expected Result:
When Categories feature is enabled/disabled, Category title will not disappear/appear when clicking on To field.

## Actual Result:
When Categories feature is enabled/disabled, Category title disappears/appears when clicking on To field.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9d03e2e4-6a8f-4453-88e2-0c0b6def9740

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012db531b3b7860fba</li>
        <li>Upwork Job ID: 1805205019945269990</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by m-natarajan** [comment] 2024-06-22 13:05
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-22 13:05
We think that this bug might be related to  #vip-vsb

**Comment by tsa321** [comment] 2024-06-23 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - transaction search category column doesn't stay put when clicking on header to sort the search.

### What is the root cause of that problem?

In here:

https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/components/Search.tsx#L84

We set the searchResults as lastSearchResult when onyx data isn't available. 
The  search metadata={searchResults?.search} stored in `search` field which contains `columnsToShow`.
When user sort the search list using other header the search result doesn't exist in onyx. and the columnsToShow will be reset to empty (set by useRef declaration) and not from previous searchResult `columnsToShow`. 
This will make the category hidden until search result retrieved.

### What changes do you think we should make in order to solve the problem?

We could use useRef of (`columnsToShow`) and set it when  and assign it to `searchResults?.search?.columnsToShow` 
which will be used in SearchTableHeader metadata.

**Comment by mountiny** [comment] 2024-06-24 11:43
I think we can demote this one, its quite an edge case and it does not block user

**Comment by luacmartins** [comment] 2024-06-25 15:49
FWIW I think this issue will fix it - https://github.com/Expensify/App/issues/43494

**Comment by kevinksullivan** [comment] 2024-06-26 15:34
That ^ Pr is on prod. @m-natarajan reopen if you see an issue like this again. Thanks!

**Closed by kevinksullivan** 2024-06-26 15:34 UTC
Labels: External, Engineering, Daily, Bug
