### ISSUE TITLE
Expense - Transaction thread with violation does not appear in LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37405] opened 2024-02-28 11:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/35449

**Version Number:** v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has Category and Tag set to "Required".

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request without category and tag.

## Expected Result:
The transaction thread with violation will appear in LHN.

## Actual Result:
The transaction thread with violation does not appear in LHN unless it is visited.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/64d8f97f-965f-4bd1-a6f8-37690df97f9b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-02-28 11:05
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-02-28 11:06
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by MitchExpensify** [comment] 2024-03-05 05:29
Not sure how the quarterly release impacts this issue's priority, I still think confirming if its a wave 6 related issue is a good first step so bumpin ya for an opinion there @greg-schroeder

**Comment by MitchExpensify** [comment] 2024-03-10 21:56
Wave collect worthy Señor Wave Collect, @trjExpensify ?

**Comment by cead22** [comment] 2024-03-11 18:20
I think this has been fixed. Can anyone still reproduce? I just tried and things worked correctly
![](http://g.recordit.co/livPJPOgtc.gif)

**Comment by MitchExpensify** [comment] 2024-03-12 21:01
I also can no longer reproduce - Closing!

**Comment by izarutskaya** [comment] 2024-03-13 13:18
This issue is reproducible again, but now it's not reproducible in production. I added `DeployBlockerCash` label, remove please if need.
Build v1.4.51-3

Steps the same:
User is an employee of Collect workspace.
The Collect workspace has Category and Tag set to "Required".

1. Go to staging.new.expensify.com
2. Go to workspace chat. (employee)
3. Create a manual request without category and tag.


https://github.com/Expensify/App/assets/115492554/05890d4a-9586-4fe5-8a23-4ce63616a307

Staging 

![image (1)](https://github.com/Expensify/App/assets/115492554/3bec4e4b-f0cd-47bd-b11e-0d46f36c5045)


Production

![image](https://github.com/Expensify/App/assets/115492554/a3243760-ee0f-4e25-8dda-7cfe9af791ec)

**Comment by izarutskaya** [comment] 2024-03-13 13:20
@danieldoglas I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors. Thanks

**Comment by danieldoglas** [comment] 2024-03-13 13:30
@cead22 I remember you said you found 2 issues last Friday. Is this related?

**Comment by luacmartins** [comment] 2024-03-13 15:49
I don't think this is a blocker since Violations is still in a beta. Additionally, I think this might be because we [reverted this PR](https://github.com/Expensify/App/pull/35907) due to performance issues since that PR added report errors to the LHN.

**Comment by cead22** [comment] 2024-03-14 17:21
I couldn't repro on v1.4.52-1 staging desktop web

https://github.com/Expensify/App/assets/165133/d08c1620-459d-4d77-92f1-e00901884958

**Closed** 2024-03-14 17:21 UTC
Labels: Engineering, Daily, Bug
