### ISSUE TITLE
[C+ Checklist Needs Completion] [$250]  Android - Deep link - staging.new.expensify.com/a/hello loads twice when navigate via link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34543] opened 2024-01-15 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/a/hello
while app is open

## Expected Result:
Page not found should be displayed

## Actual Result:
When navigate to non-existing profile page is loaded twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8ec0223a-a510-4463-be73-9ce097f317dd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012fdfa325d3bd25e5</li>
        <li>Upwork Job ID: 1747053448950476800</li>
        <li>Last Price Increase: 2024-05-16</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by mountiny** [comment] 2024-01-16 00:29
Minor bug/ flow, demoting and marking as external

**Comment by joelbettner** [comment] 2024-01-19 06:17
Given that I've not been asked to review any proposals by @akinwale yet, I'm going to unassign myself from this for focus on other things.

**Comment by akinwale** [comment] 2024-01-19 07:04
> Given that I've not been asked to review any proposals by @akinwale yet, I'm going to unassign myself from this for focus on other things.

Somehow, I missed the notifications for this earlier. I'll review shortly.

**Comment by akinwale** [comment] 2024-01-19 16:27
We can move forward with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/34543#issuecomment-1892922658) here.

🎀👀🎀 C+ reviewed.

**Comment by MonilBhavsar** [comment] 2024-01-22 13:07
Looking

**Comment by MonilBhavsar** [comment] 2024-01-22 13:31
route path can have valid query string parameters in some cases?
Example: settings/profile/contact-methods/new?backTo=somepage

**Comment by MonilBhavsar** [comment] 2024-01-23 12:32
How we're ensuring the ignored ones are only being removed.

> This can be done in many ways like using Regex, split and merge based on separator like &, ? with vanilla JS (like [how react-navigation does it](https://github.com/react-navigation/react-navigation/blob/5975e35887a8d4fa4b46873059c24c373f8037bc/packages/core/src/getStateFromPath.tsx#L422)), ...

And also what approach we're using - regex or a mix of regex and split functions?

**Comment by greg-schroeder** [comment] 2024-01-26 18:54
Bump @dukenv0307 on the above

**Comment by MonilBhavsar** [comment] 2024-01-29 12:42
Proposals in review

**Comment by mvtglobally** [comment] 2024-01-30 04:57
Issue not reproducible during KI retests. (First week)

**Comment by MonilBhavsar** [comment] 2024-01-30 05:32
Okay thanks for clarifying. Using only regex sounds good!
Also, any idea on above comment. Why the issue seems fixed?

**Comment by MonilBhavsar** [comment] 2024-01-31 06:49
Can you please suggest reproduction steps so that this issue gets triggered.
Since this issue is not reproducible now, we should create and move to new issue

**Comment by MonilBhavsar** [comment] 2024-02-05 05:56
Bumping to weekly as issue is not reproducible

**Comment by greg-schroeder** [comment] 2024-02-06 01:03
All right if this isn't reproducible, then I'm going to close this. If we need to create a new issue for a different case, let's do that.

**Comment by lanitochka17** [comment] 2024-04-24 20:18
Issue is still reproducible on the latest build 1.4.64-6


https://github.com/Expensify/App/assets/78819774/c92980b3-8d03-4c21-8771-7d616d1a29fd

**Comment by MonilBhavsar** [comment] 2024-04-29 08:52
@dukenv0307 are you still interested to work on this issue?

**Comment by MonilBhavsar** [comment] 2024-04-30 09:47
Thanks a lot!

**Comment by MonilBhavsar** [comment] 2024-05-06 11:47
Same ^

**Comment by greg-schroeder** [comment] 2024-05-08 19:56
Okay thanks @dukenv0307

**Comment by greg-schroeder** [comment] 2024-05-13 12:21
@dukenv0307 should have an update this week!

**Comment by greg-schroeder** [comment] 2024-05-15 22:32
No problem, thanks for your effort here!

**Comment by akinwale** [comment] 2024-05-21 06:12
> @akinwale @MonilBhavsar [Proposal updated](https://github.com/Expensify/App/issues/34543#issuecomment-1892922658) to address the latest root cause.

I think the solution looks solid.

@dukenv0307 The issue happens for non-existent profile pages, but can you also verify that existing profile pages still work as expected?

**Comment by MonilBhavsar** [comment] 2024-05-21 09:26
Thanks @dukenv0307!

**Comment by greg-schroeder** [comment] 2024-05-22 00:16
Awesome, good progress!

**Comment by greg-schroeder** [comment] 2024-06-01 02:19
Looks set to go for payment

**Comment by greg-schroeder** [comment] 2024-06-06 15:01
Paid! @akinwale can you complete [the checklist](https://github.com/Expensify/App/issues/34543#issuecomment-2140889383) so we can close this out? Thanks.

**Comment by akinwale** [comment] 2024-06-06 15:57
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. It's more of an edge-case which wasn't handled.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify app
2. Navigate to a non-existent profile URL within the app, e.g. `/a/hello` while the app is open. If testing using the simulator, navigate to the URL using the command, `npx uri-scheme open new-expensify://a/hello --android` (`--ios` for iOS).
3. Verify that the destination page isn't loaded twice. When navigation back occurs, it should return to the previous screen.

Do we agree 👍 or 👎?

**Comment by greg-schroeder** [comment] 2024-06-06 22:03
Thanks! Filing and closing

**Closed by greg-schroeder** 2024-06-06 22:03 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
