### ISSUE TITLE
[$500] Request - Participant deep link opens Participant page briefly and keyboard opens in Scan

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30127] opened 2023-10-21 17:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/26149

## Action Performed:
Precondition: Make sure Scan tab is selected when Request money tab is opened
1. Navigate to https://staging.new.expensify.com/
2. Paste the link https://staging.new.expensify.com/request/new/participants/
in chat
3. Tap on the link

## Expected Result:
User is redirected to Request money selector page without opening Participants page and keyboard

## Actual Result:
The link opens Participants page briefly with keyboard showing up. Sometimes Participants page is not shown but keyboard still appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/4cccc6b0-8711-4b8f-bdf9-88f83c679a77

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014061867ab191f52d</li>
        <li>Upwork Job ID: 1715778155199119360</li>
        <li>Last Price Increase: 2023-11-18</li>
    </ul>
</details>

**Comment by chiragkcodes** [comment] 2023-10-22 18:42
We already have #26538 to remove support for money request deep links.
I believe the issue would not invalid after these changes, we should hold this issue.
Can you please confirm if this would be still valid issue after planned changes under #26538 ? @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2023-10-23 02:15
can you check if the refactoring issue is really removing the deep link? If I remember correctly, I think @tgolen is making change in a way that still supports deep linking to money-request related pages

**Comment by chiragkcodes** [comment] 2023-10-23 05:33
You are right, looks like we are doubling down on supporting money requests as I read discussion further. my bad.
In that case, We can continue to investigate further. Thanks @hayata-suenaga !

**Comment by benomatis** [comment] 2023-10-23 10:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If Scan option is originally selected (where the keyboard is not normally needed), coming there using a Participant deep link opens the keyboard briefly.

### What is the root cause of that problem?
With the introduction of the `autoFocus` prop in `BaseOptionsSelector.js`, which appears to have originally aimed to fix a focus issue in web and desktop (relevant commits: 4c478d3f, 90b96de0, f45b2ca2, 7ff6e00e, 0d2d5604, 70beac8b, 5d28fdb5, 57882919), the relevant platform specific constraint (`[CONST.PLATFORM.DESKTOP, CONST.PLATFORM.WEB].includes(getPlatform())`) to allow `this.textInput.focus()` to execute inside `setTimeout` was only introduced in `componentDidUpdate` and is missing from `componentDidMount`.

### What changes do you think we should make in order to solve the problem?
The same platform specific constraint (`[CONST.PLATFORM.DESKTOP, CONST.PLATFORM.WEB].includes(getPlatform())`) should be introduced in `componentDidMount` to `this.textInput.focus()` inside `setTimeout`.

### What alternative solutions did you explore? (Optional)
NA

### Additional note
Note that `shouldDelayFocus` in `src/components/OptionsSelector/index.android.js` could be removed as part of this change as it appears to be unnecessary, it's not being used in `BaseOptionsSelector.js` at all.

Also note that I could not reproduce the part where the participant list appeared briefly first, but I do believe this solution should resolve the issue of the keyboard unnecessarily opening in that case as well, otherwise it should probably be investigated as a separate issue.

**Comment by benomatis** [comment] 2023-10-23 11:02
Contributor details
Your Expensify account email: benomatis@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/benomatis

**Comment by chiragkcodes** [comment] 2023-10-23 11:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. For deeplink - ```/request/new/participants/``` and iouType = ```Manual``` or ```Scan```.
When deeplink is used to navigate to participants page, app is redirecting to new request page.
Issue is not present for ```Distance``` iouType
When we click on same link again, participant page opens successfully. (does not work on first click)

2. For deeplink -``` /request/new/participants/${reportID}```
Same issue exists, except when App is trying to navigate back and crashing.

### What is the root cause of that problem?

#### 1. Considering deeplink  - ```/request/new/participants/```
Below condition which is causing re-direction -
https://github.com/Expensify/App/blob/05ed9f2a8812c81e19deed1e01b7eb79ae88bc44/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L97-L99

- ```amount``` will be '0' (in case of manual request)
- ```receiptPath``` will be blank in case of scan request

States when above code is called:
```js
prevMoneyRequestId.current: "request4849254365733268"
iou.id: "request4849254365733268"
reportID: ""
moneyRequestId: "request"
```

This also triggers reset to iou and iou.id becomes "request" [here](https://github.com/Expensify/App/blob/05ed9f2a8812c81e19deed1e01b7eb79ae88bc44/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L95)
Due to above mentioned condition, app routes back to ```/request/new/{manual/scan}``` url

Even after we remove this condition to prevent navigation, once ```Onyx``` updated ```iou.id```, same useEffect is called and below code causes back navigation -
https://github.com/Expensify/App/blob/05ed9f2a8812c81e19deed1e01b7eb79ae88bc44/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L83-L89

States when above code is called:
```js
prevMoneyRequestId.current:  "request4849254365733268"
iou.id: "request"
reportID: ""
moneyRequestId: "request"
```

#### 2. Further when checked for - -/request/new/participants/${reportID}
Found that same sequence of events is causing back navigation to occur.
But, due to ```undefined``` check missing, its crashing the app even before navigation completes.
https://github.com/Expensify/App/blob/73d966d8c9c44b8bc6d5cc0fad037f5c123b4635/src/libs/Navigation/Navigation.js#L126-L129

### What changes do you think we should make in order to solve the problem?

Remove the back navigation mechanism altogether and re-use similar logic while deciding whether to reset ```IOU```
New code for useEffect
```js
const moneyRequestId = `${iouType.current}${reportID.current}`;
const shouldReset = iou.id && iou.id !== moneyRequestId && !isDistanceRequest && !isSplitRequest;
if (shouldReset) {
       IOU.resetMoneyRequestInfo(moneyRequestId);
       prevMoneyRequestId.current = moneyRequestId;
}
return () => { <same as before> }
```

To fix crashing issue for url - ```/request/new/participants/${reportID}```, adding undefined check for ``` lastRoute.state```
```js
if (lastRoute.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR && lastRoute.state && lastRoute.state.index > 0) {
```
After these changes its working and we are able to open participants page successfully.

### What alternative solutions did you explore? (Optional)
NA

**Comment by abdulrahuman5196** [comment] 2023-10-24 18:55
Will check today

**Comment by abdulrahuman5196** [comment] 2023-10-27 14:56
Reviewing now. Sorry for the delay.

**Comment by abdulrahuman5196** [comment] 2023-10-30 12:50
Working on the review today. If not complete by today, will re-assign to fast up the issue.

**Comment by abdulrahuman5196** [comment] 2023-10-31 11:31
Checking now

**Comment by abdulrahuman5196** [comment] 2023-10-31 11:41
@benomatis I am able to understand the root cause and solution mentioned here https://github.com/Expensify/App/issues/30127#issuecomment-1774943851. Could you provide more update on the same?

**Comment by benomatis** [comment] 2023-10-31 11:48
@abdulrahuman5196 basically a fix for desktop and web forces the focus, which is forcing the keyboard to appear on mobile even when it should not. That fix (to force focus) for desktop and web has later been set up so it only kicks in on those platforms when something changes in the component, but it kicks in for ALL platforms (including mobile) upon first render of the component. So my fix is about introducing the same constraits to only target desktop and web already existing for component update for component first render as well.

**Comment by abdulrahuman5196** [comment] 2023-10-31 11:54
@HezekielT I was testing out the proposal here https://github.com/Expensify/App/issues/30127#issuecomment-1775279331

It is working if the app is in quit state, but if we have the app open/background state the fix is not working.

**Comment by abdulrahuman5196** [comment] 2023-10-31 11:59
> @abdulrahuman5196 basically a fix for desktop and web forces the focus, which is forcing the keyboard to appear on mobile even when it should not. That fix (to force focus) for desktop and web has later been set up so it only kicks in on those platforms when something changes in the component, but it kicks in for ALL platforms (including mobile) upon first render of the component. So my fix is about introducing the same constraits to only target desktop and web already existing for component update for component first render as well.

AFAIK, when we have a draft request like Request -> fill something -> participants page, quit app. Now if you deeplink to the participants page it should stay there and open the keyboard. So I am not sure if hiding is the keyboard is the best way.
Now I think the issue, the condition to trigger the navigateBack is delayed and the page with keyboard is rendered. After that the page is navigating back causing the flicker or keyboard to slowly come down.
Let me know if i am misunderstanding the proposal in any way

**Comment by benomatis** [comment] 2023-10-31 13:25
> > @abdulrahuman5196 basically a fix for desktop and web forces the focus, which is forcing the keyboard to appear on mobile even when it should not. That fix (to force focus) for desktop and web has later been set up so it only kicks in on those platforms when something changes in the component, but it kicks in for ALL platforms (including mobile) upon first render of the component. So my fix is about introducing the same constraits to only target desktop and web already existing for component update for component first render as well.
> 
> 
> 
> AFAIK, when we have a draft request like Request -> fill something -> participants page, quit app. Now if you deeplink to the participants page it should stay there and open the keyboard. So I am not sure if hiding is the keyboard is the best way.
> 
> Now I think the issue, the condition to trigger the navigateBack is delayed and the page with keyboard is rendered. After that the page is navigating back causing the flicker or keyboard to slowly come down.
> 
> Let me know if i am misunderstanding the proposal in any way

Isn't the participant list hidden here because it's not needed? It's not even offered as an option, unless I'm missing something. If it does need to be hidden, the forced focus is redundant as the relevant input would not be present.

**Comment by abdulrahuman5196** [comment] 2023-11-02 17:07
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-11-02 18:05
@HezekielT Just now tested with latest main. I am not able to see the keyboard. But its doing double navigation.



https://github.com/Expensify/App/assets/46707890/815c903a-8052-4fb2-a92a-dc48f81f97aa

**Comment by tgolen** [comment] 2023-11-03 14:44
Hi! I was looking at this, and I think the problem is solved [in my PR](https://github.com/Expensify/App/pull/28618) that refactors these components. This can probably be closed as `won't fix` for now.

**Comment by abdulrahuman5196** [comment] 2023-11-03 15:26
> Hi! I was looking at this, and I think the problem is solved [in my PR](https://github.com/Expensify/App/pull/28618) that refactors these components. This can probably be closed as `won't fix` for now.

cc: @anmurali / Or we can keep in hold also

**Comment by abdulrahuman5196** [comment] 2023-11-06 18:13
Just back from weekend
@anmurali  to  check on this

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:51
> > Hi! I was looking at this, and I think the problem is solved [in my PR](https://github.com/Expensify/App/pull/28618) that refactors these components. This can probably be closed as `won't fix` for now.
> 
> cc: @anmurali / Or we can keep in hold also

Gentle Ping @anmurali

**Comment by anmurali** [comment] 2023-11-21 17:48
Closing per https://github.com/Expensify/App/issues/30127#issuecomment-1792573605

**Closed by anmurali** 2023-11-21 17:48 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
