### ISSUE TITLE
Chat - "Don't have access to this chat" page is shown for a brief moment while creating a new chat reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11555] opened 2022-10-04 02:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.  Search new user
2.  Tap on the contact

## Expected Result:
Don't have access to this chat" shouldn't be shown

## Actual Result:
Don't have access to this chat" page appears for a brief moment

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android (I am not able to repro)
- Desktop App
- Mobile Web

**Version Number:** 1.2.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/193722007-c938dfd4-87a0-40ce-bd0b-64b7ffaaf1d0.mp4
https://user-images.githubusercontent.com/43996225/193722023-4ba0066a-a1f4-42b5-abcc-dd938e83922e.mp4 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664839563641319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2022-10-04 07:08
This is happening as the Onyx merge isn't complete when we try to navigate to the chat leading to a brief Not Found page.  I didn't see any of the PRs that updated this recently but this will also be fixed in the refactor https://github.com/Expensify/Expensify/issues/213315 which should be coming out soon

Going to remove the deploy blocker label since this will be fixed with the refactor PR cc @stitesExpensify

**Comment by mountiny** [comment] 2022-10-04 09:03
This one is a duplicate of a deploy blocker create previously, I will close this one in favour of the first one https://github.com/Expensify/App/issues/11503

**Closed by mountiny** 2022-10-04 09:03 UTC
Labels: Engineering, Weekly

**Comment by thesahindia** [comment] 2022-10-21 08:15
@mountiny, It is still reproducible.  Is https://github.com/Expensify/Expensify/issues/213315 not merged yet?

**Comment by stitesExpensify** [comment] 2022-10-21 14:54
It was just merged last night. It hasn't been deployed yet

**Comment by thesahindia** [comment] 2022-11-09 18:25
I believe it was fixed since I wasn't able to repro this a week ago but I am seeing this issue again. It's too minor now.


https://user-images.githubusercontent.com/83179295/200911113-b234b2b1-9725-4242-bc1a-c265e855f9db.mov
