### ISSUE TITLE
[HOLD for payment 2023-12-28] [$1000]  Attachments - Different level of image scaling before and after sending the image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28159] opened 2023-09-25 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in with any account
3. Navigate to any conversation
4. Upload this long image to a conversation [https://drive.google.com/file/d/18-C7XPRHJbb91kJ2U3l5T-rjf8h1y-sT/view?usp=share_linkм](https://drive.google.com/file/d/18-C7XPRHJbb91kJ2U3l5T-rjf8h1y-sT/view?usp=share_link%D0%BC)
5. In the preview, try scaling the image to the largest possible size
6. Send the image to the conversation
7. Open the image you just sent in a conversation
8. In the preview window, try scaling the image to the largest possible size

## Expected Result:
The zoom function should work the same way and scale both in the preview before sending and in the preview of the already sent image

## Actual Result:
The zoom function has a smaller degree of image enlargement in the preview before sending than in the preview of an already sent image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bdc2fb5f-360b-4a4c-b7be-a0801a41a081

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f162d19099da7570</li>
        <li>Upwork Job ID: 1709264175049048064</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment] 2023-09-28 18:14
reviewing

**Comment by dylanexpensify** [comment] 2023-10-03 17:48
took a bit to repro, but got it with that image

**Comment by dylanexpensify** [comment] 2023-10-09 14:09
waiting on proposals - doubling

**Comment by thienlnam** [comment] 2023-10-09 19:25
Upwork has been pooping out - should work now

**Comment by paultsimura** [comment] 2023-10-10 09:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When uploading an image, the max scaling on preview is smaller than when viewing the same attachment.

### What is the root cause of that problem?

We use different Image wrappers for the attachment preview and attachment view scenarios:
`ImageZoom` and `ImageTransformer` accordingly.

While `ImageTransformer` uses some more complicated logic, its max scale is set to 20 (with bouncing it's 30 which still bounces back to 20).

In ImageZoom we don't explicitly set the max scale, so it uses the default value (10):

<img width="739" alt="image" src="https://github.com/Expensify/App/assets/12595293/24f08aa0-4e1f-4776-8a36-706c41229a72">

### What changes do you think we should make in order to solve the problem?

We should explicitly set max scale of `ImageZoom` to the same as in `ImageTransformer` (using constant, but that's just details):

```diff
                <ImageZoom
                   ref={zoom}
+                   maxScale={20}
                    onClick={onPress}
                    cropWidth={windowWidth}
                    cropHeight={calculatedWindowHeight}
                    imageWidth={imageDimensions.width}
                    ...
```

https://github.com/Expensify/App/blob/edc4821567cdbfd531a73cf57257c7a6112a040c/src/components/ImageView/index.native.js#L195-L224



### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2023-10-10 18:38
@ntdiary mind reviewing ^ 🙇‍♂️

**Comment by paultsimura** [comment] 2023-10-11 08:46
@ntdiary this makes sense, although needs a deeper investigation for potential bugs. I'll update shortly 👍

**Comment by paultsimura** [comment] 2023-10-11 13:38
@ntdiary it seems like there isn't a simple way to use this transformer in both carousel & plain view, as it is tightly dependent on `AttachmentCarouselPagerContext`, and I don't think we'd want to provide this context to the images used outside of the carousel: 

https://github.com/Expensify/App/blob/a5dc51c750030cad34dc1ae3e4654b98382cca3b/src/components/Attachments/AttachmentCarousel/Pager/AttachmentCarouselPage.js#L35

https://github.com/Expensify/App/blob/de521f30cb857ab3e9fe11a904d4899a8c042ebf/src/components/Attachments/AttachmentCarousel/Pager/ImageTransformer.js#L63

However, I might look into separating some functions (e.g. dimension and scale calculations) used in the ImageTransformer into some Utils, and reuse it in both `ImageTransformer` and `ImageView`.

**Comment by dylanexpensify** [comment] 2023-10-16 09:37
@HezekielT @ntdiary where are we at here?

**Comment by dylanexpensify** [comment] 2023-10-18 08:25
Waiting on better proposals

**Comment by dylanexpensify** [comment] 2023-10-30 09:48
@ntdiary you might be on the hook 😆

**Comment by dylanexpensify** [comment] 2023-11-06 10:53
sounds good! Looking forward to hearing what you found!

**Comment by dylanexpensify** [comment] 2023-11-07 09:59
bump @ntdiary!

**Comment by chrispader** [comment] 2023-11-09 15:18
Hey, sorry for the late response on this!

Yes, so the reason for the difference in zoom scale is due to the different components used for the image preview.

I agree with @ntdiary, that we should try to use only one of these components for both the attachment carousel as well as the preview. Since we'll have to use the custom `ImageTransformer` component for the carousel anyway, i'd suggest to also use the `ImageTransformer` component for the preview and in other locations.

I can easily update the `ImageTransformer` component to not necessarily rely on the `AttachmentCarouselPagerContext` and be **non-swipable**...

Should i start working on this or do you want somebody else to further work on this issue? Lmk @ntdiary @dylanexpensify :))

**Comment by pecanoro** [comment] 2023-11-10 15:39
Assigning @chrispader! 🙇‍♀️

**Comment by pecanoro** [comment] 2023-11-13 15:27
@chrispader Any updates?

**Comment by chrispader** [comment] 2023-11-13 17:53
Going to look into this now! Expect a finished PR by either tomorrow or thursday 👍

**Comment by dylanexpensify** [comment] 2023-11-14 09:57
Woooot! Thanks @chrispader!

**Comment by chrispader** [comment] 2023-11-14 10:07
@pecanoro should we use this opportunity to also migrate the `ImageTransformer` component to Typescript? Maybe someone from the TS migration team wants to chime in too?

**Comment by chrispader** [comment] 2023-11-14 13:43
Created a PR here, which is almost ready 🚀 

https://github.com/Expensify/App/pull/31308

**Comment by chrispader** [comment] 2023-11-15 11:12
> ### Updates:
> Firstly, I think it's feasible to make some tweaks to `ImageTransformer` and `AttachmentCarouselPagerContext`. However, the currently `AttachmentCarouselPage` causes the app to crash when loading huge images (#24337), I need more time to investigate this further.

It was mentioned, that the in certain cases with very large images the Attachment Gallery can crash. I left a comment in #24337 [here](https://github.com/Expensify/App/issues/24337#issuecomment-1812307416), because there's an ongoing PR that could fix this problem..

I don't think it's that urgent, but anways, there might already be a fix for this :)

**Comment by chrispader** [comment] 2023-11-15 15:38
My PR is ready for review: https://github.com/Expensify/App/pull/31308 🚀🎉 

The PR fixes this issue and also improves and abstracts the components used for attachments.

There is now a `MultiGestureCanvas` component (previously the `ImageTransformer`), which can be used for any kind of view, not only images. It handles all sorts of common gestures, like pinch to zoom, double tap to zoom, panning, out of bounds detection...

There is also a new `Lightbox` component which uses `MultiGestureCanvas` specifically for images. In the native implementation of `ImageView` we now directly use the `Lightbox` component instead of `ImageZoom`.

**Comment by chrispader** [comment] 2023-11-15 15:41
Lmk if i can help on this any further!

cc @ntdiary @pecanoro @dylanexpensify

**Comment by chrispader** [comment] 2023-11-16 13:20
> > Lmk if i can help on this any further!
> > cc @ntdiary @pecanoro @dylanexpensify
> 
> My main concern is the crash problem. Previously, although the app would crash when users open the high-resolution image (e.g. 9000px*9000px), at least they could successfully upload. If we merge this PR first, they will no longer be able to upload high-resolution images. From this perspective, it would be better to wait for the downsampling fix first. 🤔

yes, i agree. We don't maintain forks anymore, so we'll have to wait for this to be fixed upstream: https://github.com/Expensify/react-native-fast-image/pull/6#issuecomment-1812426082

**Comment by chrispader** [comment] 2023-11-21 15:15
We should therefore be able to merge the PR! 🚀

https://github.com/Expensify/App/pull/31308

**Comment by dylanexpensify** [comment] 2023-12-05 19:42
@ntdiary update please?

**Comment by chrispader** [comment] 2023-12-06 11:42
> @ntdiary update please?

Yes, the main part of the PR that solves THIS issue is completed. Also the crashes are fixed. Only thing left is fixing this stutter/shake/lag reported here: https://github.com/Expensify/App/issues/32110#issuecomment-1841088682

**Comment by chrispader** [comment] 2023-12-06 11:42
i can hopefully finish this today!

**Comment by dylanexpensify** [comment] 2023-12-11 07:58
Nice! @chrispader how we looking?

**Comment by dylanexpensify** [comment] 2023-12-20 09:26
NICE!

**Comment by chrispader** [comment] 2023-12-20 09:45
PR is already merged btw!

**Comment by iwiznia** [comment] 2023-12-27 17:03
It seems this issue caused [this regression](https://github.com/Expensify/App/issues/33635#issuecomment-1870148679)

**Comment by chrispader** [comment] 2023-12-28 10:37
> It seems this issue caused [this regression](https://github.com/Expensify/App/issues/33635#issuecomment-1870148679)

Yes unfortunately. There's already a fixing PR though https://github.com/Expensify/App/pull/33695

**Comment by chrispader** [comment] 2024-01-03 11:35
I think this can be closed? :)

**Comment by pecanoro** [comment] 2024-01-08 10:08
I think we need to handle payment for @ntdiary but I think we also need to complete the checklist [here](https://github.com/Expensify/App/issues/28159#issuecomment-1865489009). We had a regression in the regression period, right? @dylanexpensify Can you handle this?

**Comment by dylanexpensify** [comment] 2024-01-09 12:08
Payment summary:

- Contributor+: @ntdiary $250

Please apply!

**Comment by dylanexpensify** [comment] 2024-01-15 10:38
ahh @ntdiary my mistake! I'll update that on our side's documentation!

**Comment by dylanexpensify** [comment] 2024-01-15 10:41
@ntdiary just sent you an upwork job invite!

**Comment by dylanexpensify** [comment] 2024-01-15 12:41
offer sent!

**Comment by dylanexpensify** [comment] 2024-01-15 12:49
sent!! TY!!

**Closed by dylanexpensify** 2024-01-15 12:49 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
