### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Expense - Report turns to skeleton after deleting expense with comments offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45461] opened 2024-07-16 09:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with any user that has no unsettled expense.
3. Submit an expense.
4. Click on the expense preview.
5. Send a few comments.
6. Go offline.
7. Click on the report header.
8. Click Delete expense.
9. Delete the expense.

## Expected Result:
Report will not turn to skeleton after deleting the expense offline.

## Actual Result:
The part above the comments turns to skeleton after deleting the expense offline.
This issue only happens when there is only one expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a673afeb-e0c9-45d5-9b0f-138a75ad74b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d020bfa76c4b7e26</li>
        <li>Upwork Job ID: 1813325690168936392</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103162922</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by izarutskaya** [comment] 2024-07-16 09:38
We think this issue might be related to the #collect project.

**Comment by thienlnam** [comment] 2024-07-16 21:31
Taking this over since Georgia is offline

**Comment by chiragsalian** [comment] 2024-07-16 21:34
Not a blocker for backend. The issue purely happens when offline in newDot so its most likely purely a frontend issue.
Removed deployblocker label

**Comment by thienlnam** [comment] 2024-07-16 23:21
Going to remove the blocker since this is an edge case flow

**Comment by nkdengineer** [comment] 2024-07-17 06:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The part above the comments turns to skeleton after deleting the expense offline.
This issue only happens when there is only one expense.

### What is the root cause of that problem?

In 

https://github.com/Expensify/App/blob/24d05adfaa5644248a8f164043ffdf36bdbe65e0/src/libs/ReportActionsUtils.ts#L418-L422

We have the logic to remove the duplicated create action

But after delete request, we also delete the transaction thread -> transactionThreadCreatedAction will be undefined -> `filteredTransactionThreadReportActions` doesn't contain create action

-> The else block will be executed -> we remove the created action in `filteredParentReportActions`

-> combinedReportActions doesn't contain create action

-> isReportLoadedUntilBeginning is true 

-> Skeleton is shown

### What changes do you think we should make in order to solve the problem?


We shouldn't remove create action in `reportActions` when transactionThreadCreatedAction is null (If we do that, there's no create action)

```
...else if(transactionThreadCreatedAction){
        filteredParentReportActions = reportActions?.filter((action) => action.actionName !== CONST.REPORT.ACTIONS.TYPE.CREATED);
    }
```
### What alternative solutions did you explore? (Optional)

We can consider to update the parent report action of expense report optimistically in deleteMoneyRequest-> [Deleted message] will be shown

<img width="375" alt="Screenshot 2024-07-17 at 13 17 00" src="https://github.com/user-attachments/assets/ef52a5ff-ed94-4fde-8d28-c0322cf1c8d5">

**Comment by Christinadobrzyn** [comment] 2024-07-17 15:33
I'm not sure if this should be resolved as part of https://github.com/Expensify/App/issues/44798 - if it should then we don't need to spend time reviewing proposals. @shubham1206agra can you review this to see if it relates to issue 44798>

**Comment by Christinadobrzyn** [comment] 2024-07-23 23:44
PR is under review - https://github.com/Expensify/App/pull/45665

**Comment by Christinadobrzyn** [comment] 2024-07-30 16:56
PR is under review - https://github.com/Expensify/App/pull/45665

**Comment by Christinadobrzyn** [comment] 2024-08-07 15:32
Preparing for payment. 

Regression test - https://github.com/Expensify/Expensify/issues/418512

Payouts due:

- [ ] Contributor: $250 @nkdengineer (upwork offer - https://www.upwork.com/nx/wm/offer/103162922)
- Contributor+: $250 @parasharrajat - paid through NewDot

**Comment by Christinadobrzyn** [comment] 2024-08-08 16:44
payment scheduled for tomorrow

**Comment by Christinadobrzyn** [comment] 2024-08-09 17:40
payday is here! Paid out based on this payment summary - https://github.com/Expensify/App/issues/45461#issuecomment-2273752473

@parasharrajat please make sure to request a payment through NewDot. Thank you! Closing

**Closed by Christinadobrzyn** 2024-08-09 17:40 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-09-02 11:56
$250 approved for @parasharrajat
