### ISSUE TITLE
🔴 [$500] App crashes when opening the second distance request as a reviewer

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26925] opened 2023-09-07 05:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account.
2. Create a workspace and invite User B.
3. Open the workspace room from User B.
4. As User B, create a distance request (workspace chat -> + -> Request money -> Distance -> add waypoints -> Next -> Request
5. Return to User A's account.
6. Open the Requested Distance sent from User B. Confirm that the app doesn't crash
7. Switch back to User B's account and send a distance request again.
8. As User A, try to open the new distance request sent by User B.

## Expected Result:
User A should be able to view the new distance request

## Actual Result:
App crashes

## Workaround:
N/A

## Platforms:

_Only tested on web. Not sure if the issue is present on other platforms, too_
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail: N/A
**Email or phone of affected tester (no customers): N/A
**Logs:** N/A
**Notes/Photos/Videos:**
Please refer to [this video](https://expensify.slack.com/archives/C049HHMV9SM/p1694062092113889?thread_ts=1694035685.129389&cid=C049HHMV9SM) (I couldn't upload the video)
**Expensify/Expensify Issue URL: N/A
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694035685129389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b20f43c302788fe</li>
        <li>Upwork Job ID: 1699652736794378240</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-07 05:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when opening the second distance request as a reviewer.

### What is the root cause of that problem?
Attempting to call a method on the suggestionsRef in the onBlur method results in the error when the ref is null.

### What changes do you think we should make in order to solve the problem?
Add a null check on suggestionsRef.current to prevent access to the null reference.

### What alternative solutions did you explore? (Optional)
None.

**Comment by imranaalam** [comment] 2023-09-07 05:58
---

**Problem Statement:**  
The application crashes when trying to open the second distance request as a reviewer. The crash can also occur when opening the first distance request on a newly created workspace.

**Root Cause:**  
The crash is triggered within the `ReceiptUtils#getThumbnailAndImageURIs` method while trying to determine if the file is an image. In certain scenarios, the filename passed as a parameter to the method can be null or undefined. When operations (like `split`, etc.) are attempted on this null or undefined filename, it leads to a crash.

**Proposed Solution:**  
To prevent the crash, an early return should be added in the `getThumbnailAndImageURIs` function to check if the filename is null or undefined. If it is, the function should return default values for the thumbnail and image. Here's the modification:

```python
if not filename:
    return {'thumbnail': None, 'image': 'ReceiptGeneric'}
```

This ensures that when the filename is eventually retrieved, the preview will re-render, and the image (if any) will be correctly displayed.

**Test:**  
1. For a valid filename:
```python
test_filename = "test.jpg"
test_path = "https://example.com/test"
assert getThumbnailAndImageURIs(test_path, test_filename) == {'thumbnail': 'https://example.com/test.1024.jpg', 'image': 'https://example.com/test'}
```

2. For a null or undefined filename:
```python
test_path = "https://example.com/test"
assert getThumbnailAndImageURIs(test_path, None) == {'thumbnail': None, 'image': 'ReceiptGeneric'}
```

**Alternative Solution:**  
While the current proposed solution focuses on handling null or undefined filenames, an alternative approach could involve a more comprehensive validation mechanism. This mechanism would not only check for null or undefined values but also for empty strings, filenames with invalid characters, and other potential anomalies. However, this might introduce additional complexity and may be unnecessary unless there's a broader issue with how filenames are being managed in the application.

---

**Comment by mountiny** [comment] 2023-09-07 08:11
@akinwale How will the money request action component look like until the receipt is loaded?

**Comment by akinwale** [comment] 2023-09-07 08:12
> @akinwale How will the money request action component look like until the receipt is loaded?

It displays the default generic receipt image (the green placeholder) until the image loads. I can make a video to demo this.

**Comment by akinwale** [comment] 2023-09-07 08:25
@mountiny Demo video. My connection is a bit slow so it takes a while to load.

https://github.com/Expensify/App/assets/4160319/84bc7eae-a29c-4171-bd4a-ea353f7f4f30

**Comment by pradeepmdk** [comment] 2023-09-07 08:29
@mountiny we already discussed this issue backend should be sent as a `filename` property in  pusher and API 
https://github.com/Expensify/App/issues/26585#issuecomment-1704803718

https://github.com/Expensify/App/issues/26585#issuecomment-1704381989
https://github.com/Expensify/App/issues/26585#issuecomment-1703976018
https://github.com/Expensify/App/issues/26585#issuecomment-1704399604

**Comment by hayata-suenaga** [comment] 2023-09-11 03:19
@ArekChr could you review the proposals?

**Comment by neil-marcellini** [comment] 2023-09-11 16:28
I'm taking over as requested internally in Slack [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1694412791697559)

**Comment by pradeepmdk** [comment] 2023-09-12 09:39
@ArekChr this will help you reproduce [this video](https://expensify.slack.com/archives/C049HHMV9SM/p1694062092113889?thread_ts=1694035685.129389&cid=C049HHMV9SM) but now the issue was changed pusher not sending the `transcation_ 2023636921105531794`   data so its keeps loading


https://github.com/Expensify/App/assets/16595846/36c226ae-8710-4f3f-8d00-ca164016d509

**Comment by pradeepmdk** [comment] 2023-09-12 10:20
@neil-marcellini  @ArekChr  could you check this on the Backend side.

**Comment by ArekChr** [comment] 2023-09-13 11:29
@pradeepmdk I couldn't load the video. Could you optimize it and send it in a smaller size?

**Comment by pradeepmdk** [comment] 2023-09-13 11:40
@ArekChr which one

**Comment by akinwale** [comment] 2023-09-13 11:43
> @pradeepmdk I couldn't load the video. Could you optimize it and send it in a smaller size?

@ArekChr You can also check out the demo video I posted here: https://github.com/Expensify/App/issues/26925#issuecomment-1709698115

At the time, I was able to reliably reproduce if I tried to open the request before the image loaded.

**Comment by ArekChr** [comment] 2023-09-14 10:32
@akinwale, @pradeepmdk Thanks for videos! I tested that scenario again and It seems the app is not crashing anymore on the main branch and staging, there is a different issue with no loaded distance request which is not related to this issue.

**Comment by ayazhussain79** [comment] 2023-09-14 21:53
@ArekChr  @akinwale Do you know which PR has fixed this bug?

**Comment by pradeepmdk** [comment] 2023-09-15 00:47
@ayazhussain79 this is not yet fixed. previously pusher sent the wrong data so it crashed. now Pusher not sending that whole object so the issue has changed now.

**Comment by ArekChr** [comment] 2023-09-15 08:33
@pradeepmdk, The bug with the crash issue, is not reproducible anymore

**Comment by pradeepmdk** [comment] 2023-09-15 08:44
@ArekChr Yes I agree, I am just explaining @ayazhussain79 to the issue that has changed now. The crash issue is no more here. Maybe one pusher is fixed and again `filename`  property is missed means this issue will reproduce. now this issue is closed or hold that is your choice @ArekChr.

**Comment by ArekChr** [comment] 2023-09-15 09:26
I think we can close this issue, for the infinite skeleton loading bug, there is a separate issue created [here](https://github.com/Expensify/App/issues/27200)

**Closed** 2023-09-15 23:16 UTC
Labels: External, Daily, Help Wanted, Bug
