### ISSUE TITLE
[HOLD for payment 2023-02-08] [$2000] Copy to clipboard not working for deleted message in offline mode.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14325] opened 2023-01-16 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat room.
2. Turn off network (Go offline).
3. Delete any message.
4. It should show as strikethrough.
5. Hover message and click on copy to clipboard from context menu.
6. Try to send message in composer by Ctrl+v or right click and paste.

## Expected Result:
To be deleted message should be add in clipboard if press on copy to clipboard.

## Actual Result:
To be deleted message not adding in Clipboard when we press on copy to clipboard.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212743827-1d91487b-b54f-49a7-bd25-bb06ab7028e5.mp4

https://user-images.githubusercontent.com/43996225/212743854-5fcb5e6d-cb00-4343-8c0f-c5fa204c9410.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673792669557199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba340387059f1757</li>
        <li>Upwork Job ID: 1615339911454900224</li>
        <li>Last Price Increase: 2023-01-24</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-01-17 04:47
Please see my comment in Slack.

**Comment by twisterdotcom** [comment] 2023-01-17 13:26
I agree with context in Slack - it makes sense to **not** show a comment action menu when the comment has been deleted offline.

From: https://stackoverflowteams.com/c/expensify/questions/14418

- [x] The "bug" is actually a bug.
- [x] The bug is not a duplicate report of an existing GH
- [x] The bug is reproducible, following the reproduction steps.
- [x] The GH template is filled out as fully as possible
- [x] The GH was created by an Expensify employee or a QA tester.
- [x] The bug is an /App issue

---

Adding `External`

**Comment by jayeshmangwani** [comment] 2023-01-17 13:27
### Proposal

When we delete a comment offline at that time we are setting reportAction message's html and text to empty string and setting previousMessage to reportAction message here,

https://github.com/Expensify/App/blob/25522089aabdf1d72d022b19cf225c59903bf139/src/libs/actions/Report.js#L639-L651

so at that time, we are using reportAction messages html here, we will get the empty string so what we can do here is that when pendingAction is equal to delete then get data from previousMessage rather than message

https://github.com/Expensify/App/blob/25522089aabdf1d72d022b19cf225c59903bf139/src/pages/home/report/ContextMenu/ContextMenuActions.js#L99-L101

```diff
-            const message = _.last(lodashGet(reportAction, 'message', [{}]));
+            let message = _.last(lodashGet(reportAction, 'message', [{}]));
+            if(reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
+                message = _.last(lodashGet(reportAction, 'previousMessage', [{}]));
+            }
```

**Comment by jayeshmangwani** [comment] 2023-01-17 13:29
Video after Applying after [this](https://github.com/Expensify/App/issues/14325#issuecomment-1385424320) fix 

https://user-images.githubusercontent.com/35371050/212911237-88ba44a1-1e11-4946-af73-6805e7a6e670.mov

**Comment by jatinsonijs** [comment] 2023-01-17 13:41
As discussed in Slack we can hide context menu when pending action is delete

Proposal
```diff
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index fe0b804905..af93ad7e39 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -113,7 +113,7 @@ class ReportActionItem extends Component {
      */
     showPopover(event) {
         // Block menu on the message being Edited
-        if (this.props.draftMessage) {
+        if (this.props.draftMessage || this.props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
             return;
         }
 
@@ -251,8 +251,8 @@ class ReportActionItem extends Component {
                                 reportAction={this.props.action}
                                 isArchivedRoom={ReportUtils.isArchivedRoom(this.props.report)}
                                 displayAsGroup={this.props.displayAsGroup}
-                                isVisible={
-                                    hovered
+                                isVisible={this.props.action.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
+                                    && hovered
                                     && !this.state.isContextMenuActive
                                     && !this.props.draftMessage
                                 }
```

**Comment by s77rt** [comment] 2023-01-17 14:45
### Proposal
```diff
diff --git a/src/pages/home/report/ContextMenu/ContextMenuActions.js b/src/pages/home/report/ContextMenu/ContextMenuActions.js
index 9dc44986b5..50d778fa4f 100644
--- a/src/pages/home/report/ContextMenu/ContextMenuActions.js
+++ b/src/pages/home/report/ContextMenu/ContextMenuActions.js
@@ -16,13 +16,24 @@ import * as ContextMenuUtils from './ContextMenuUtils';
 import * as Environment from '../../../../libs/Environment/Environment';
 import Permissions from '../../../../libs/Permissions';
 
+/**
+ * Gets the message of an action
+ * @param {Object} reportAction
+ * @param {Any} defaultValue
+ * @return {Object}
+ */
+function getActionMessage(reportAction, defaultValue) {
+    return reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
+        ? _.last(lodashGet(reportAction, 'previousMessage', defaultValue)) : _.last(lodashGet(reportAction, 'message', defaultValue));
+}
+
 /**
  * Gets the HTML version of the message in an action.
  * @param {Object} reportAction
  * @return {String}
  */
 function getActionText(reportAction) {
-    const message = _.last(lodashGet(reportAction, 'message', null));
+    const message = getActionMessage(reportAction, null);
     return lodashGet(message, 'html', '');
 }
 
@@ -40,14 +51,14 @@ export default [
         successTextTranslateKey: 'common.download',
         successIcon: Expensicons.Download,
         shouldShow: (type, reportAction) => {
-            const message = _.last(lodashGet(reportAction, 'message', [{}]));
+            const message = getActionMessage(reportAction, [{}]);
             const isAttachment = _.has(reportAction, 'isAttachment')
                 ? reportAction.isAttachment
                 : ReportUtils.isReportMessageAttachment(message);
             return isAttachment && reportAction.reportActionID;
         },
         onPress: (closePopover, {reportAction}) => {
-            const message = _.last(lodashGet(reportAction, 'message', [{}]));
+            const message = getActionMessage(reportAction, [{}]);
             const html = lodashGet(message, 'html', '');
             const attachmentDetails = getAttachmentDetails(html);
             const {originalFileName} = attachmentDetails;
@@ -91,13 +102,13 @@ export default [
         successIcon: Expensicons.Checkmark,
         shouldShow: (type, reportAction) => (type === CONTEXT_MENU_TYPES.REPORT_ACTION
             && reportAction.actionName !== CONST.REPORT.ACTIONS.TYPE.IOU
-            && !ReportUtils.isReportMessageAttachment(_.last(lodashGet(reportAction, ['message'], [{}])))),
+            && !ReportUtils.isReportMessageAttachment(getActionMessage(reportAction, [{}]))),
 
         // If return value is true, we switch the `text` and `icon` on
         // `ContextMenuItem` with `successText` and `successIcon` which will fallback to
         // the `text` and `icon`
         onPress: (closePopover, {reportAction, selection}) => {
-            const message = _.last(lodashGet(reportAction, 'message', [{}]));
+            const message = getActionMessage(reportAction, [{}]);
             const messageHtml = lodashGet(message, 'html', '');
 
             const isAttachment = _.has(reportAction, 'isAttachment')
@@ -134,7 +145,7 @@ export default [
         successIcon: Expensicons.Checkmark,
         successTextTranslateKey: 'reportActionContextMenu.copied',
         shouldShow: (type, reportAction, isArchivedRoom, betas, menuTarget) => {
-            const isAttachment = ReportUtils.isReportMessageAttachment(_.last(lodashGet(reportAction, ['message'], [{}])));
+            const isAttachment = ReportUtils.isReportMessageAttachment(getActionMessage(reportAction, [{}]));
 
             // Only hide the copylink menu item when context menu is opened over img element.
             const isAttachmentTarget = lodashGet(menuTarget, 'tagName') === 'IMG' && isAttachment;
```

### RCA

I agree with @jayeshmangwani analysis however his proposal only handles the specific case of copy to clipboard action while the issue exists for other actions too such as attachments. I have covered that in my proposal above.

As for @jatinsonijs proposal I think as long as the user have access to the message he should be able copy it so the context menu should not be hidden. Besides there is an inconsistency in your design where you hide the context menu of the reportActions but the user can still open the context menu of the links that are inside that reportAction.

**Comment by s77rt** [comment] 2023-01-17 14:50
### Proposal 2
```diff
diff --git a/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js b/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
index e48e68e329..662d942e3e 100644
--- a/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
+++ b/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js
@@ -37,6 +37,10 @@ const BaseAnchorForCommentsOnly = (props) => {
             inline
             onSecondaryInteraction={
                 (event) => {
+                    if (props.action.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
+                        return;
+                    }
+
                     ReportActionContextMenu.showContextMenu(
                         Str.isValidEmail(props.displayName) ? ContextMenuActions.CONTEXT_MENU_TYPES.EMAIL : ContextMenuActions.CONTEXT_MENU_TYPES.LINK,
                         event,
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index be4eb73886..d78ad8abfc 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -112,7 +112,7 @@ class ReportActionItem extends Component {
      */
     showPopover(event) {
         // Block menu on the message being Edited
-        if (this.props.draftMessage) {
+        if (this.props.draftMessage || this.props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
             return;
         }
 
@@ -238,8 +238,8 @@ class ReportActionItem extends Component {
                                 reportAction={this.props.action}
                                 isArchivedRoom={ReportUtils.isArchivedRoom(this.props.report)}
                                 displayAsGroup={this.props.displayAsGroup}
-                                isVisible={
-                                    hovered
+                                isVisible={this.props.action.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
+                                    && hovered
                                     && !this.state.isContextMenuActive
                                     && !this.props.draftMessage
                                 }
```

### Details
Extending @jatinsonijs proposal to hide the context menu correctly.

**Comment by jatinsonijs** [comment] 2023-01-17 14:51
Proposal

```diff
diff --git a/src/pages/home/report/ContextMenu/ReportActionContextMenu.js b/src/pages/home/report/ContextMenu/ReportActionContextMenu.js
index 6d14773a8f..bb4dee4a72 100644
--- a/src/pages/home/report/ContextMenu/ReportActionContextMenu.js
+++ b/src/pages/home/report/ContextMenu/ReportActionContextMenu.js
@@ -1,4 +1,5 @@
 import React from 'react';
+import CONST from '../../../../CONST';
 
 const contextMenuRef = React.createRef();
 
@@ -26,7 +27,7 @@ function showContextMenu(
     onShow = () => {},
     onHide = () => {},
 ) {
-    if (!contextMenuRef.current) {
+    if (!contextMenuRef.current || reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
         return;
     }
     contextMenuRef.current.showContextMenu(
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index fe0b804905..af93ad7e39 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -113,7 +113,7 @@ class ReportActionItem extends Component {
      */
     showPopover(event) {
         // Block menu on the message being Edited
-        if (this.props.draftMessage) {
+        if (this.props.draftMessage || this.props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
             return;
         }
 
@@ -251,8 +251,8 @@ class ReportActionItem extends Component {
                                 reportAction={this.props.action}
                                 isArchivedRoom={ReportUtils.isArchivedRoom(this.props.report)}
                                 displayAsGroup={this.props.displayAsGroup}
-                                isVisible={
-                                    hovered
+                                isVisible={this.props.action.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
+                                    && hovered
                                     && !this.state.isContextMenuActive
                                     && !this.props.draftMessage
                                 }
```

**Comment by jatinsonijs** [comment] 2023-01-17 14:55
@s77rt there is actually various place to call showContextMenu so I have added it upper level.

**Comment by s77rt** [comment] 2023-01-17 14:59
@jatinsonijs You can remove the extra code in `ReportActionItem`. I didn't test but I think it will work still fine

**Comment by jatinsonijs** [comment] 2023-01-17 15:01
Yes I haven't removed it exist from previous proposal will remove it

**Comment by tienifr** [comment] 2023-01-17 16:59
# Proposal

Beside hiding the context menu, we should also remove the hover background in case the message was deleted. If we keep the hover background, it will indicate to the user that there's some actions that can be taken on that message, which is not recommended since there's no such action available.

```diff
diff --git a/src/pages/home/report/ContextMenu/ReportActionContextMenu.js b/src/pages/home/report/ContextMenu/ReportActionContextMenu.js
index 6acb7d5c33..2b226fda3f 100644
--- a/src/pages/home/report/ContextMenu/ReportActionContextMenu.js
+++ b/src/pages/home/report/ContextMenu/ReportActionContextMenu.js
@@ -1,4 +1,5 @@
 import React from 'react';
+import CONST from '../../../../CONST';
 
 const contextMenuRef = React.createRef();
 
@@ -30,7 +31,7 @@ function showContextMenu(
     isArchivedRoom = false,
     isChronosReport = false,
 ) {
-    if (!contextMenuRef.current) {
+    if (!contextMenuRef.current || reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
         return;
     }
     contextMenuRef.current.showContextMenu(
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index f4a871078e..e86264498a 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -113,7 +113,7 @@ class ReportActionItem extends Component {
      */
     showPopover(event) {
         // Block menu on the message being Edited
-        if (this.props.draftMessage) {
+        if (this.props.draftMessage || this.props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
             return;
         }
 
@@ -212,7 +212,7 @@ class ReportActionItem extends Component {
                             )}
                             <View
                                 style={StyleUtils.getReportActionItemStyle(
-                                    hovered
+                                    (hovered && this.props.action.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
                                     || this.state.isContextMenuActive
                                     || this.props.draftMessage,
                                     (this.props.network.isOffline && this.props.action.isLoading) || this.props.action.error,
@@ -255,6 +255,7 @@ class ReportActionItem extends Component {
                                 displayAsGroup={this.props.displayAsGroup}
                                 isVisible={
                                     hovered
+                                    && this.props.action.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
                                     && !this.state.isContextMenuActive
                                     && !this.props.draftMessage
                                 }
diff --git a/src/styles/StyleUtils.js b/src/styles/StyleUtils.js
index 548ef84c60..b2dc2335e9 100644
--- a/src/styles/StyleUtils.js
+++ b/src/styles/StyleUtils.js
@@ -424,15 +424,15 @@ function getLoginPagePromoStyle() {
 /**
  * Generate the styles for the ReportActionItem wrapper view.
  *
- * @param {Boolean} [isHovered]
+ * @param {Boolean} [shouldUseHoverStyle]
  * @param {Boolean} [isLoading]
  * @returns {Object}
  */
-function getReportActionItemStyle(isHovered = false, isLoading = false) {
+function getReportActionItemStyle(shouldUseHoverStyle = false, isLoading = false) {
     return {
         display: 'flex',
         justifyContent: 'space-between',
-        backgroundColor: isHovered
+        backgroundColor: shouldUseHoverStyle
             ? themeColors.hoverComponentBG
 
             // Warning: Setting this to a non-transparent color will cause unread indicator to break on Android

```

After the fix:

https://user-images.githubusercontent.com/113963320/212962925-3f0c154c-e69b-4472-b62d-99edde756b7f.mov

**Comment by s77rt** [comment] 2023-01-17 17:01
@tienifr I don't think hover have anything to do with the context menu. Hover should be active if you are hovering the item. And personally it does not look good that way.

**Comment by jatinsonijs** [comment] 2023-01-17 17:08
Yeah hover should be there as item is still active, and user can still copy text by select

**Comment by s77rt** [comment] 2023-01-17 17:10
@jatinsonijs Since the user can copy the text and view the attachment. Why would we disable the context menu?

**Comment by tienifr** [comment] 2023-01-17 17:11
@s77rt check Slack, any text that cannot be actioned on, does not have any hover effect. To me, hover effect indicates that some actions can be taken on the text. Imagine you hover over a button but cannot click or do anything with it, it's similar for texts.

@jatinsonijs any text you see anywhere can be copied without any hovering effect, unless someone purposefully make it uncopiable

**Comment by jatinsonijs** [comment] 2023-01-17 17:11
hmm it is team decision https://expensify.slack.com/archives/C049HHMV9SM/p1673930522391279?thread_ts=1673792669.557199&cid=C049HHMV9SM

**Comment by jatinsonijs** [comment] 2023-01-17 17:14
@tienifr I'm not sure about it. It is just personal preference (design decision).

**Comment by jayeshmangwani** [comment] 2023-01-17 18:13
> 
> ### RCA
> I agree with @jayeshmangwani analysis however his proposal only handles the specific case of copy to clipboard action while the issue exists for other actions too such as attachments. I have covered that in my proposal above.
> 
> As for @jatinsonijs proposal I think as long as the user have access to the message he should be able copy it so the context menu should not be hidden. Besides there is an inconsistency in your design where you hide the context menu of the reportActions but the user can still open the context menu of the links that are inside that reportAction.

@s77rt can you wait until someone from internal or c+ can check my proposal?
My proposal is working fine here as the issue was only for "Copy to clipboard" only and what you did here is just took my proposal and used it for all three actions FYI this can be done in the PR process too, and you should comment your proposal and wait for the c+ rather than rejecting other's proposal

**Comment by s77rt** [comment] 2023-01-17 20:00
@jayeshmangwani Sorry I didn't mean to reject your proposal at all. With respect but the missed points are not something that could be caught on the PR.
Anyway, as @jatinsonijs pointed, we are looking to hide the context menu if the message is deleted.

FWIW, I have hide my comment.

**Comment by s77rt** [comment] 2023-01-18 13:54
### Proposal 2
```diff
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index fe0b804905..58ddfae1df 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -196,6 +196,7 @@ class ReportActionItem extends Component {
         }
         return (
             <PressableWithSecondaryInteraction
+                disabled={this.props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE}
                 ref={el => this.popoverAnchor = el}
                 onPressIn={() => this.props.isSmallScreenWidth && DeviceCapabilities.canUseTouchScreen() && ControlSelection.block()}
                 onPressOut={() => ControlSelection.unblock()}
```

### Details
Since we don't want to show the context menu at the first place we can simple make the `<PressableWithSecondaryInteraction />` disabled. This will make the report action inaccessible:
- no hover
- no mini context menu (the one visible on hover)
- no context menu (the one visible on right click / secondary interaction)

**Comment by s77rt** [comment] 2023-01-18 14:19
### Proposal 3
```diff
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index fe0b804905..48f8e262eb 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -196,6 +196,7 @@ class ReportActionItem extends Component {
         }
         return (
             <PressableWithSecondaryInteraction
+                pointerEvents={this.props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ? 'none' : 'auto'}
                 ref={el => this.popoverAnchor = el}
                 onPressIn={() => this.props.isSmallScreenWidth && DeviceCapabilities.canUseTouchScreen() && ControlSelection.block()}
                 onPressOut={() => ControlSelection.unblock()}
```

### Details
Same as my previous proposal, but I think the use of `pointerEvents` has better support because `<PressableWithSecondaryInteraction />` on native uses either `<Pressable />` or `<Text />`. The latter does not respect/support `disabled` but works fine with `pointerEvents`.

The real impact between `disabled` and `pointerEvents` is unnoticeable, going with any would be fine but I think `pointerEvents` is safer.

**Comment by s77rt** [comment] 2023-01-18 14:24
@thesahindia It's 2 (Don't show the context menu)
https://expensify.slack.com/archives/C049HHMV9SM/p1673961953972409?thread_ts=1673792669.557199&cid=C049HHMV9SM

**Comment by jatinsonijs** [comment] 2023-01-18 14:30
@s77rt I think its not good, with this user cannot do anything complete sections is disabled

**Comment by s77rt** [comment] 2023-01-18 14:31
@jatinsonijs He does not have to, he deleted the comment.

**Comment by jatinsonijs** [comment] 2023-01-18 14:35
I don't think, user should still able to press on user profile, user name to open detail page.

**Comment by jatinsonijs** [comment] 2023-01-18 16:10
Yes @s77rt but same dimmed ui present for new message in offline also.

**Comment by jatinsonijs** [comment] 2023-01-18 16:22
But I think your solution is good, as it will block further navigation etc..., it will not allow to open attachment where download button present. Also its clean and blocking code is on right place where it should be.

**Comment by thesahindia** [comment] 2023-01-18 16:38
@s77rt, thanks for the link!

@jatinsonijs, please comment in the [thread](https://expensify.slack.com/archives/C049HHMV9SM/p1673961953972409?thread_ts=1673792669.557199&cid=C049HHMV9SM). Let's move the discussion there.

**Comment by thesahindia** [comment] 2023-01-19 20:38
Asked for [confirmation](https://expensify.slack.com/archives/C049HHMV9SM/p1674160542148579?thread_ts=1673792669.557199&cid=C049HHMV9SM) before proceeding.

**Comment by twisterdotcom** [comment] 2023-01-23 17:23
I've commented in Slack my opinion. I think given there's a strikethrough, it will make sense to the end user that they're limited here.

**Comment by cristipaval** [comment] 2023-01-24 20:20
> I am not sure about the expected behaviour.
> 
> @cristipaval, what should be the expected behaviour when the message deletion is pending ?
> 
> 1. Copy the message when user clicks on copy to clipboard in context menu
> 2. Don't show the context menu

@thesahindia So sorry for missing this comment 🙇

**Comment by cristipaval** [comment] 2023-01-24 20:25
> @s77rt's [proposal](https://github.com/Expensify/App/issues/14325#issuecomment-1387148577) looks good to me. It's much simpler and aligns with the expected results.
> 
> C+ reviewed 🎀👀🎀
> 
> cc: @twisterdotcom

👍

**Comment by thesahindia** [comment] 2023-01-25 11:31
Let's hire and assign @s77rt here, so that they can start with the PR.

**Comment by twisterdotcom** [comment] 2023-01-30 09:30
Sorry sorry, my bad entirely! Just getting into the swing of doing these, thanks for the bump @thesahindia.

**Comment by s77rt** [comment] 2023-01-30 15:52
Applied in [Upwork](https://www.upwork.com/jobs/~01ba340387059f1757).
[PR](https://github.com/Expensify/App/pull/14655) is ready.

**Comment by twisterdotcom** [comment] 2023-02-08 15:12
Assigned: https://github.com/Expensify/App/issues/14325#event-8385919328 Jan 30 9:29
Merged: https://github.com/Expensify/App/pull/14655#event-8399237184 Jan 31 13:12

50% bonus!

**Comment by twisterdotcom** [comment] 2023-02-09 23:44
>I think we can leave the first three items in the checklist since it was implemented like this.

@cristipaval do you agree?

**Comment by cristipaval** [comment] 2023-02-10 20:37
> I think we can leave the first three items in the checklist since it was implemented like this.

**Comment by cristipaval** [comment] 2023-02-13 10:25
Oh, ok, I get it now. Yes I do agree it doesn't make a lot of sense to take those steps. @twisterdotcom

**Comment by twisterdotcom** [comment] 2023-02-14 14:37
Slack: https://expensify.slack.com/archives/C01SKUP7QR0/p1676385174643779

**Comment by twisterdotcom** [comment] 2023-02-14 15:19
QA Issue: https://github.com/Expensify/Expensify/issues/262437

**Closed** 2023-02-14 15:19 UTC
Labels: External, Daily, Awaiting Payment, Bug
