### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] Chat - "as copilot for" is displayed in avatar tooltip

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43800] opened 2024-06-15 19:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a message.
4. Hover over self avatar.

## Expected Result:
The tooltip for self avatar will just display the user name.

## Actual Result:
The tooltip for self avatar displays "as copilot for x".

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/34a32469-2b64-4d7c-b6ce-325ca92efa85

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by m-natarajan** [comment] 2024-06-15 19:25
@luacmartins FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-15 19:26
We think that this bug might be related to  #vip-vsb

**Comment by neonbhai** [comment] 2024-06-15 19:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"as copilot for" is displayed in avatar tooltip

### What is the root cause of that problem?
Since now the default value for Onyx is '-1' this statement always evaluates to `true`
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L34



### What changes do you think we should make in order to solve the problem?
We will add a check for `-1` here:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L34

```jsx
if (delegateAccountID === -1) {
    ...
}
````

**Comment by mountiny** [comment] 2024-06-16 21:49
Gonna take over

**Comment by mountiny** [comment] 2024-06-16 22:12
Thank you @neonbhai for urgency I raised the pr myself but you would get partial reward for identifying the fix

**Comment by MitchExpensify** [comment] 2024-06-19 23:02
No payment needed here, closing

**Comment by neonbhai** [comment] 2024-06-20 06:04
@MitchExpensify hi, I'm eligible for compensation here as noted in https://github.com/Expensify/App/issues/43800#issuecomment-2171906666

**Comment by mountiny** [comment] 2024-06-20 11:53
Yeah let's do partial payment of $50 for identifying the fix

**Comment by MitchExpensify** [comment] 2024-06-24 00:24
Ah yes, offer sent here: https://www.upwork.com/nx/wm/offer/102848809

**Comment by mountiny** [comment] 2024-06-24 12:50
@neonbhai have you confirmed? 

I dont think we need a regression test for this

**Comment by MitchExpensify** [comment] 2024-07-01 20:52
Paid and contract ended!

**Closed by MitchExpensify** 2024-07-01 20:52 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
