### ISSUE TITLE
Request Money -  'Manual', 'Scan', and 'Distance' is not grayed out when they are not selected

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29624] opened 2023-10-14 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697234831059319

## Action Performed:
1. Click on FAB
2. Request Money

## Expected Result:
'Manual', 'Scan', and 'Distance' is grayed out when they are not selected

## Actual Result:
 'Manual', 'Scan', and 'Distance' is not grayed out when they are not selected

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details> cannot verify - crash

<details>
<summary>Android: mWeb Chrome</summary>

 
![sc](https://github.com/Expensify/App/assets/93399543/00a1bc54-ae60-439d-bc02-16490cf37345)

</details>

<details>
<summary>iOS: Native</summary>

</details> cannot verify - app freezes

<details>
<summary>iOS: mWeb Safari</summary>

 
![IMG_8172](https://github.com/Expensify/App/assets/93399543/eccc1b3b-a131-47ce-9bd9-48f4eb4fdac9)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary> 
![image (8)](https://github.com/Expensify/App/assets/93399543/6223ecfa-9416-48ab-83df-44c8d15754a9)
![image (7)](https://github.com/Expensify/App/assets/93399543/8f0f308e-f759-4c0c-bd95-e27a15babdcf)

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/0c9b7526-33b9-41e6-b182-3b481c06f005

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment] 2023-10-15 05:58
This will be fixed by https://github.com/Expensify/App/pull/29629 ig

**Comment by sakluger** [comment] 2023-10-18 16:50
@mountiny just to confirm, https://github.com/Expensify/App/pull/29629 will fix this issue? If so, it looks like the [bug report](https://expensify.slack.com/archives/C049HHMV9SM/p1697210216244469) for https://github.com/Expensify/App/issues/29611 was made before the [bug report](https://expensify.slack.com/archives/C049HHMV9SM/p1697234831059319) for this one, so I would think we would just close this as a duplicate and pay that reporting bonus.

Do you think we should pay this reporting bonus as well even if it's the same root cause?

**Comment by mountiny** [comment] 2023-10-18 17:04
I agree we can close this even this was very similar reports and same rootcause

**Closed by mountiny** 2023-10-18 17:04 UTC
Labels: Engineering, Daily, Bug
