### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Web - Hover effect is lost when hovering on a task checkbox

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23182] opened 2023-07-19 17:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Assign task
3. Move the hover on the checkbox

## Expected Result:
The item should remain hovered

## Actual Result:
The hover effect will be lost

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5983520b-61b4-4d23-80da-2b37d47c7fe9

https://github.com/Expensify/App/assets/93399543/9e839093-6afa-45dd-8e37-7d3ac51fdb9b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1689691271038109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d688951b4b39f55</li>
        <li>Upwork Job ID: 1682036256059990016</li>
        2023-07-20<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>getusha | Reporter | 25724516</li>
</ul></li>
    </ul>
</details>

**Comment by StanislavLavrenchuk** [comment] 2023-07-21 07:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On the task title, hover effect lost when mouse is on the checkbox 
### What is the root cause of that problem?
Checkbox has no hover effect normally. 
### What changes do you think we should make in order to solve the problem?
We can simply add mouse hover event listener on checkbox parent react component.

### What alternative solutions did you explore? (Optional)

Uploading hoverEfeectofCheckbox.mov…

**Comment by alanleungcn** [comment] 2023-07-22 05:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Hover effect is lost when hovering on the checkbox in task title.

### What is the root cause of that problem?

The parent component of checkbox does not know its hover state.

### What changes do you think we should make in order to solve the problem?

We should introduce the props `onHoverIn` and `onHoverOut` in the `Checkbox` component, applying to `PressableWithFeedback` [here](https://github.com/Expensify/App/blob/main/src/components/Checkbox.js#L88), which already handles the hover logic.

Therefore, we could introduce a state in the parent component `TaskView` to determine if the checkbox is being hovered, something on the lines of `const [isCheckboxHovered, setIsCheckboxHovered] = useState(isCompleted);`. Then, we could use the said state to determine the style of the title [here](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/TaskView.js#L66).

I believe it is a more general way to fix any similar issues because we could have have information on the hover state of the checkbox.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by ArekChr** [comment] 2023-07-24 07:42
The [proposal](https://github.com/Expensify/App/issues/23182#issuecomment-1642584044) from @allroundexperts looks good to me 
🎀 👀 🎀 C+ reviewed

**Comment by ArekChr** [comment] 2023-07-26 15:56
PR reviewed 🙌

**Comment by bfitzexpensify** [comment] 2023-08-10 14:24
Please complete the BZ checklist when you get a moment @ArekChr - thank you!

**Comment by ArekChr** [comment] 2023-08-11 10:41
- [x] The PR that introduced the bug has been identified. Link to the PR: No PR found.
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: no comment.
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [x] Determine if we should create a regression test for this bug: We can create a simple regression test.

1. Open any chat
2. Assign task
3. Move the hover on the checkbox

Do we agree 👍 or 👎

**Comment by bfitzexpensify** [comment] 2023-08-11 11:32
Agreed @ArekChr — I just added a 4th point to instruct the behaviour we're looking for:

1. Open any chat
2. Assign task
3. Move the hover on the checkbox
4. Confirm the task is still highlighted

Opened https://github.com/Expensify/Expensify/issues/307528. 

We're all done here, closing this one out - thanks everyone!

**Closed by bfitzexpensify** 2023-08-11 11:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
