### ISSUE TITLE
[$500] Chat- Tapping header on new group, "members" section is updated to "share code"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34933] opened 2024-01-22 23:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211281
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab--- Start chat
3. Select few users and tap "add to group"
4. Tap header

## Expected Result:
Members section should not be displayed and should show "share code" instead 

## Actual Result:
The "members" section is shown for a second and then replaced with "share code" section. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9a8a397a-4110-4cfc-a5eb-2ce4229737b0

https://github.com/Expensify/App/assets/78819774/a9d34f4f-07f4-4945-bb4b-816195a7fdd3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9e33b8b7fdb77be</li>
        <li>Upwork Job ID: 1749568058423840768</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-22 23:26
This is a BE issue: when opening a new group report, we optimistically set the correct `report.visibleChatMemberAccountIDs` value, but the `OpenReport` API response resets it to an empty list:

<img width="1258" alt="image" src="https://github.com/Expensify/App/assets/12595293/2ade55d5-ebc5-4f5e-9652-74034dffedd1">

However, on the page reload, the second `OpenReport` API call returns correct list of account IDs here.
So we need to fix on the BE the value returned for `report.visibleChatMemberAccountIDs` when opening a new group report.

**Comment by rlinoz** [comment] 2024-01-23 16:48
You are correct, the backend should send this property on `OpenReport`

**Comment by dragnoir** [comment] 2024-01-24 18:04
From the video posted by the QA and reproducing the issue. I can see that the data is correct for just few seconds then it change to an empty array for `visibleChatMemberAccountIDs`.
I think some part of the code is changing the value of `visibleChatMemberAccountIDs` in Onyx.

**Comment by dragnoir** [comment] 2024-01-24 18:12
> No, the correct data you see is the optimistic data, which is set correctly. After a while, it gets replaced by the data from server API response, which should be fixed on the BE.

then why if you refresh the page(or login/logout), you get right data!

**Comment by paultsimura** [comment] 2024-01-24 18:14
> if you refresh the page(or login/logout), you get right data!

I've explained it above:

> However, on the page reload, the second OpenReport API call returns correct list of account IDs here.


These are different API calls, and they return different data

**Comment by laurenreidexpensify** [comment] 2024-01-29 11:40
WAiting for an internal engineer to pick up

**Comment by laurenreidexpensify** [comment] 2024-02-02 12:07
Needs internal fix

**Comment by laurenreidexpensify** [comment] 2024-02-05 11:44
![Screenshot_20240205-114241](https://github.com/Expensify/App/assets/62073721/cc737379-54f7-48d0-bb77-c9702a26c8f0)

Still reproducible on v1.4.36-0

**Comment by laurenreidexpensify** [comment] 2024-02-09 11:27
Still waiting for internal engineer to pick up

**Comment by laurenreidexpensify** [comment] 2024-02-14 10:21
Still waiting for internal eng to pick up

**Comment by tgolen** [comment] 2024-02-14 17:39
I'll look into this.

**Comment by tgolen** [comment] 2024-02-14 22:02
I discussed with @marcaaron @srikarparsi and @rlinoz and the general consensus was to close this issue as `won't fix` because the code is being refactored to not have these different variables (everything will be in `participants`) and the value of fixing this bug now is quite low without a very good solution.

**Closed by tgolen** 2024-02-14 22:02 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick

**Comment by tgolen** [comment] 2024-02-14 22:33
The GH for refactoring the participants is here: https://github.com/Expensify/Expensify/issues/341000
