### ISSUE TITLE
[LOW] [Splits] [$500] IOU - App returns to participant selection page when hitting Save with Tab on Description page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37464] opened 2024-02-29 03:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Manual.
3. Enter amount and select participant.
4. On confirmation page, press Tab.
5. Navigate to Description and hit Enter.
6. Enter description and save it with Tab and Enter key.

## Expected Result:
The description will be saved and app will land on confirmation page.

## Actual Result:
The description is saved and app returns to participant selection page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0fb64f28-a879-431f-9c7c-73f8545689d9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010769f678e16c288e</li>
        <li>Upwork Job ID: 1767859361668382720</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-29 03:23
@techievivek FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-02-29 04:32
This has the same root cause as https://github.com/Expensify/App/issues/33502#issuecomment-1907604187

**Comment by techievivek** [comment] 2024-02-29 07:32
Not a blocker for sure. Also, not sure if we really want to fix this. Or as per this comment https://github.com/Expensify/App/issues/33502#issuecomment-1909057724 we can solve all this together.

**Comment by dragnoir** [comment] 2024-02-29 16:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Save button clicked by keyboard go back twice

### What is the root cause of that problem?

The issue is whith all the button components on the app. Every action via keyboard enter key will trigger double the action.

https://github.com/Expensify/App/blob/0cc58170ec003d20b606b118afaba62a906c3160/src/components/Button/index.tsx#L281-L284

The condition above doesn't check if there's a keyboard enter key event.

### What changes do you think we should make in order to solve the problem?

We need to add `event.type = 'keyup'` to the condition check.

```diff
- if (event?.type === 'click') {
+ if (event?.type === 'click' || event?.type === 'keyup') {
  const  currentTarget = event?.currentTarget  as  HTMLElement;
  currentTarget?.blur();
}
```

### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment] 2024-03-02 02:06
Not worth fixing at this time

**Comment by dragnoir** [comment] 2024-03-04 07:19
@MitchExpensify the issue is within all buttons on the app and there's an easy fix [here](https://github.com/Expensify/App/issues/37464#issuecomment-1971486442)

**Comment by MitchExpensify** [comment] 2024-03-06 06:16
If there is a general solution its worth considering reopening, @techievivek does the solution linked above look like it will fix _all_ cases of this?

**Comment by dragnoir** [comment] 2024-03-08 17:02
@techievivek can you please check [my proposal](https://github.com/Expensify/App/issues/37464#issuecomment-1971486442)?  Thank you

**Comment by techievivek** [comment] 2024-03-13 10:24
Adding a C+ so they can help review the proposal.

**Comment by techievivek** [comment] 2024-03-13 10:26
@mkhutornyi Can you please help review the proposal here https://github.com/Expensify/App/issues/37464#issuecomment-1971486442 and see if that can fix all the keyboard navigation related bugs? Thanks

**Comment by nkdengineer** [comment] 2024-03-13 10:31
We also need to consider @bernhardoj `s comment [here](https://github.com/Expensify/App/issues/37464#issuecomment-1970377323)

**Comment by dragnoir** [comment] 2024-03-13 10:40
@mkhutornyi The issue is old, it was there even before. Every button now on the app triggers action twice if you navigate to it via the TAB key then you hit the ENTER key from the keyboard. We can't catch it easily because triggering twice an action does not cause issues in most cases. But if you log the onClick with a console message, you will see it twice.

@nkdengineer on the comment you mentioned, bernhardoj think it's an issue from react native web and it needs to be fixed upstream. You can check here https://github.com/Expensify/App/issues/33502#issuecomment-1971614956 I fixed the issue [there](https://github.com/Expensify/App/issues/33502) with the same proposal here.

**Comment by nkdengineer** [comment] 2024-03-13 10:42
@dragnoir Oh, got it. Thanks for your information

**Comment by MitchExpensify** [comment] 2024-03-16 18:46
@mkhutornyi What are our next steps here?

**Comment by nkdengineer** [comment] 2024-03-17 08:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- IOU - App returns to participant selection page when hitting Save with Tab on Description page
### What is the root cause of that problem?
- When we focus on the button component and then press on ENTER key, there are three events triggered: "keydown", "click", "keyup". It is the default behavior.

- In the case of react-native-webs, generally, we handle two event, "click" and "keyup". 
- [Here](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L418-L435) is logic to handle "click" and [here](L328) is the logic to handle "keup"
- When we focus on "Save" button and press ENTER, the "click" event listener is called first. Then, the "keyup" event listener is called. In the "keyup" event listener, we have the logic to not call the ```onPress``` function if the current target element is ```button``` in [here](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L313-L326), but the ```elementType``` in this case is ```body``` (because we call ```Navigation.goBack``` in the ```onPress```), so ```isNativeInteractiveElement``` is ```false```. So the ```onPress``` is called one more time.
- This bug is not occur if the ```onPress``` function does not contain the logic ```Navigation.goBack```
### What changes do you think we should make in order to solve the problem?
- Generally, we need to make sure the onPress function is only called one time.
- First, create a flag in [here](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L236), named ```isOnPressCalled``` (default value is ```false```) to know whether the onPress function is already called or not.
- Then, add to [here](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L428) the below logic:
```
             if(event.detail === 0){
                 this.isOnPressCalled = true
             }
```
- Finally, update [this](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L324) to:
```
        if (onPress != null && !isNativeInteractiveElement && (!this.isOnPressCalled)) { 
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by bernhardoj** [comment] 2024-03-18 15:30
I tested your solution and it throws a console error, that's why the second `onPress` isn't triggered. Blurring the element on the second press event doesn't cancel the press event itself.

> I think the expected behavior should be to trigger onPress on Up event like other views.

Most of the buttons on the apps use ROLE.BUTTON which renders it as `<button>`. Native `<button>` will trigger `onclick` by pressing it down with the keyboard and `react-native-web` calls `onPress` from the `onclick` event.

https://github.com/Expensify/App/assets/50919443/dd52aeaf-8958-44e9-958b-5882c7e550c9

The MenuItem role is `menuitem` which will render it as a `div` and react-native-web manually handles the click/press event in `keyup` event and it makes sure the element is not a native interactive element (for example button).
https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L305-L328

**Comment by nkdengineer** [comment] 2024-03-18 15:39
@mkhutornyi Do you have any comment proposal](https://github.com/Expensify/App/issues/37464#issuecomment-2002357953) ?

**Comment by bernhardoj** [comment] 2024-03-19 08:17
I have bumped the upstream PR. If the maintainer approves the PR (or if we want to create a patch), can we reopen https://github.com/Expensify/App/issues/33502 instead and include both issues in the App PR test step?

**Comment by mallenexpensify** [comment] 2024-03-27 21:33
@mkhutornyi is unexpectedly going to be OOO for a while, @akinwale , can you please take over as C+ here? If it doesn't work for you, please post in #contributor-plus

**Comment by nkdengineer** [comment] 2024-03-27 21:34
I see that the selected solution does not work in case three dot header button

**Comment by nkdengineer** [comment] 2024-03-27 22:08
@akinwale I updated my main solution (you can ignore alternative solution) in [proposal](https://github.com/Expensify/App/issues/37464#issuecomment-2002357953)

**Comment by bernhardoj** [comment] 2024-03-28 07:17
@akinwale let me know if you are interested in fixing this upstream instead of a workaround.

**Comment by bernhardoj** [comment] 2024-03-28 10:05
> Also, we proved that it's not an upstream issue. You can check here for details https://github.com/Expensify/App/issues/37464#issuecomment-2004939788

The proof isn't valid at all. The test that you provide doesn't try to replicate the reproduction behavior. In this issue, pressing the description save button navigates the user back, while the test code you wrote just logs a text. Try adding a navigateBack and you will see the issue.

The button component uses Pressable under the hood, so the issue happens on every component that uses Pressable. So, we need to fix it globally. It's not about event propagation either.

Do you have any other proof that I might be missed?

> Your upstream PR has been rejected

Just because the PR will cause a regression doesn't mean I don't have a chance to fix it 😄

**Comment by bernhardoj** [comment] 2024-03-28 11:38
https://github.com/Expensify/App/assets/50919443/19450efe-8fc0-41a8-9fde-e851168a7d4e

Btw, let's wait for @akinwale

**Comment by bernhardoj** [comment] 2024-03-30 15:10
But the accessibilityRole is also gone which will render it as a div instead of a button. You can read on the upstream [PR](https://github.com/necolas/react-native-web/pull/2632) for the short explanation of why the issue happens with a button role.

**Comment by techievivek** [comment] 2024-04-01 12:16
Gentle bump @akinwale, can you please take a look at the above comments and see if we really have a solution here. Thanks.

**Comment by nkdengineer** [comment] 2024-04-03 07:52
@akinwale Do you have any feedback about my [proposal](https://github.com/Expensify/App/issues/37464#issuecomment-2002357953)?

**Comment by nkdengineer** [comment] 2024-04-03 08:02
@akinwale My proposal also fix the case when we focus on "Three dot" button then press on "ENTER"

**Comment by bernhardoj** [comment] 2024-04-03 08:17
@akinwale we need a solution to fix both this and https://github.com/Expensify/App/issues/33502. It's not a critical issue, so I don't think waiting the upstream is a big problem instead of using a workaround. There is already a progress on the upstream PR.

**Comment by MitchExpensify** [comment] 2024-04-09 04:06
What's our ETA on the PR @dragnoir ?

**Comment by techievivek** [comment] 2024-04-19 07:40
Hmm, not sure why automation didn't work here. @MitchExpensify Can we look into the payments here? Thanks.

**Comment by mallenexpensify** [comment] 2024-04-19 23:35
Still hasn't hit production, so payment isn't due for at least a week.

**Comment by MitchExpensify** [comment] 2024-04-22 22:02
Still holding on PR to hit production to start the 7 day countdown to payment

**Comment by bernhardoj** [comment] 2024-04-23 15:58
Since we are not fixing this globally, can I request to reopen https://github.com/Expensify/App/issues/33502, please? I already have an accepted proposal there but gets closed. The upstream PR is already merged, so the plan is to:
1. Update rn-web to 0.19.11
2. Remove the workaround

The fix will fix this GH, https://github.com/Expensify/App/issues/40602, https://github.com/Expensify/App/issues/33502, and other unrecorded keyboard enter issues.

@techievivek @akinwale 

cc: @roryabraham as the assigned engineer for the tab accessibility issue

**Comment by roryabraham** [comment] 2024-04-23 16:46
@bernhardoj why don't you post your proposal on https://github.com/Expensify/App/issues/40602 ?

**Comment by bernhardoj** [comment] 2024-04-24 11:59
@roryabraham I'm hoping to get the bounty from that issue 😄. I really don't like how it's handled in that issue. The [first discussion](https://github.com/Expensify/App/issues/33502#issuecomment-1868138280) decided to fix the issue, I got assigned, then the 2nd [discussion](https://github.com/Expensify/App/issues/33502#issuecomment-1909057724) decided to close the issue 😞.

**Comment by roryabraham** [comment] 2024-04-24 22:44
@bernhardoj I reopened https://github.com/Expensify/App/issues/33502 - let's proceed with the RNW upgrade

**Comment by MitchExpensify** [comment] 2024-04-30 10:56
*Payment summary*:

C $500 @dragnoir 
C+ $500 @akinwale 

Both paid via Upwork, contracts ended also

**Closed by MitchExpensify** 2024-04-30 10:56 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
