### ISSUE TITLE
Android - Error shown even when a workspace is selected on android

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21576] opened 2023-06-26 15:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to android
2. Create a new workspace
3. Click on FAB icon and click on new room
4. Enter the room name
5. On workspace, select the newly created workspace from the dropdown and notice that even when we have selected the workspace, it throws an error 'Please select a workspace'
6. If you again select a new workspace from the dropdown, this time no error will be shown

## Expected Result:
 Error should not be shown when a workspace is selected on android

## Actual Result:
Error shown even when a workspace is selected on android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6cdbbd03-7a2b-4b93-aa04-010cccae4171

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687430155296719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment] 2023-06-27 18:35
Applause could not reproduce this. since neither Applause nor I could repro, I'm going to close this one. 

https://github.com/Expensify/App/assets/38016013/32dcc714-2395-4812-8768-fc464ef765cf

**Closed by maddylewis** 2023-06-27 18:35 UTC
Labels: Daily, Needs Reproduction, Bug
