### ISSUE TITLE
Desktop - App is stuck with blank screen when logout from expensifail and login with gmail account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8015] opened 2022-03-05 01:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue was found when executing the PR #7805**
## Action Performed:
1. Logging in and logging out as fast as possible a few times between two account: applausetester+092021fish@applause.expensifail.com and [rybkina@gmail.com]

## Expected Result:
App should load with chats and user able to browse

## Actual Result:
Gmail account stuck with blank page when logout from expensifail and log in to gmail account
Or Chats are not loading when logout from gmail  and log in to expensifail  account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** v1.1.41-4
**Reproducible in staging?:** Y
**Reproducible in production?:**  N
**Email or phone of affected tester (no customers):** applausetester+092021fish@applause.expensifail.com and rybkina@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/156861090-cdeaa195-9c30-4980-aa18-7d8e9c15604b.mp4

https://user-images.githubusercontent.com/43996225/156861092-09d2aa2e-86d4-4d80-8db4-4d28508de56e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2022-03-07 18:47
I think this is expected, in the sense that the app has to load a lot of chat data after signing in. I can reproduce the same issue with the production desktop app and the web app, so I'd say it's most likely not a deploy blocker.

I don't know if it would have anything to do with https://github.com/Expensify/App/pull/7805 though (or if that PR could have made the problem worse) - @kidroca curious what you think.

**Comment by kidroca** [comment] 2022-03-07 22:33
Oh wow this is very interesting:
![image](https://user-images.githubusercontent.com/12156624/157128344-5a18f463-3720-4d1c-b9e8-8886ae6300a7.png)
_Second video around the 15 sec mark_

Can we see the network tab and the amount of requests pending?
Almost instantly queuing 121 requests in parallel - seems we should stop fetching IOUs one by one if they are that many

Not sure this have anything to do with the Logout fix.
It's just the insane amount of data having to be fetching after login, re-launch
Until these 121 are over we do not continue to create Simplified reports used for rendering LHN content

**Comment by francoisl** [comment] 2022-03-08 22:26
@kavimuru would you be able to test signing out and back into the account rybkina@gmail.com on the production app too, please? I'd like to see if we get the same result (which I suspect we will). I think your account just has a lot of test IOUs, and we end up fetching a lot of that data from the backend after signing in. It's definitely something we could improve on, but might not be a blocker per se.

**Comment by francoisl** [comment] 2022-03-10 21:20
Ok so I ran some tests with the account rybkina@gmail.com (thanks for sending the password over), and I don't see a lot of differences between the production and staging builds, namely:

- It takes around 30 seconds to get everything fully loaded and ready to interact with
- Each app makes roughly the same number of requests in the Networks tab (I made sure to clear everything in Onyx before each try)
- The issue is not reproducible on web (staging nor prod), the app takes around 2 seconds to load max


----

- **Prod app**

https://user-images.githubusercontent.com/2229301/157755954-9c0c30c9-0edb-4b02-ae93-f99567a7e061.mov


- **Staging app**

https://user-images.githubusercontent.com/2229301/157755982-ed02e619-b143-4ad6-aca3-fa1838c34a8f.mov



With that said, I'd say we can keep this open as improvement to look into for the desktop app, but remove the deploy blocker?
cc @roryabraham for second opinions

**Comment by roryabraham** [comment] 2022-03-10 22:38
@francoisl I agree that this doesn't seem like a blocker because the production app is borked too.

**Comment by mvtglobally** [comment] 2022-04-05 02:35
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-04-12 03:33
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-04-19 04:01
Issue not reproducible during KI retests. (Third week) Closing

**Closed by mvtglobally** 2022-04-19 04:01 UTC
Labels: Monthly
