### ISSUE TITLE
[$250] Deeplink - Infinite loading after pasting deep link to conversation and logging in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43763] opened 2024-06-14 12:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4629009&group_by=cases:section_id&group_id=229066&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+omq1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
in browser
2. Navigate to any conversation (1:1 DM)
3. Copy the link of a conversation
4. Sign Out
5. Paste the link browser
6. Sign In with the same account

## Expected Result:
User should be signed in and navigated to the conversation from deeplink

## Actual Result:
Infinite loading displayed when user pasted deeplink and Signed In with the same account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c37206ca-d8e5-4110-8fbe-657820824674

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed62ec300a68feb4</li>
        <li>Upwork Job ID: 1802492966706573824</li>
        <li>Last Price Increase: 2024-06-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by lanitochka17** [comment] 2024-06-14 12:04
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment] 2024-06-16 23:52
Hey @lanitochka17 - I was able to recreate the issue, but wanted to add that once I clicked anywhere on the New Expensify page, the chat loaded:



https://github.com/Expensify/App/assets/54568958/68920700-a142-4d2d-bd30-e30b5aa9078f

But I agree this is a bug that's worth fixing

**Comment by ramya72002** [comment] 2024-06-17 03:50
i was unable to recreate it

**Comment by lanitochka17** [comment] 2024-06-19 14:22
Issue isn't reproducible on the latest build 1.4.85-6

https://github.com/Expensify/App/assets/78819774/7aea868f-7e00-4475-bce5-d1f02b7b955a

**Comment by VictoriaExpensify** [comment] 2024-06-19 22:02
Since this is not reproducible in the latest release, I'm closing it out. Thanks, everyone.

**Closed by VictoriaExpensify** 2024-06-19 22:02 UTC
Labels: External, Daily, Help Wanted, Bug
