### ISSUE TITLE
[Awaiting payment] [$125] [P2P Distance] Dupe detection - Distance rate is editable on the confirmation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46954] opened 2024-08-07 10:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two same distance expenses.
4. Go to transaction thread of any submitted expense.
5. Click Review duplicates.
6. Click Keep this one (any).
7. Proceed to confirmation page.
8. Click Rate.

## Expected Result:
Distance rate should not be editable on the confirmation page (like other fields).

## Actual Result:
Distance rate is editable on the confirmation page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/20efdbcb-969a-495e-a47c-8d2eed7028f0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa94659fe7b3028a</li>
        <li>Upwork Job ID: 1821151696845785168</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103588098</li>
<li>dominictb | Contributor | 103588104</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-08-07 10:30
We think that this bug might be related to #wave-collect - Release 2

**Comment by etCoderDysto** [comment] 2024-08-07 10:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Distance rate is editable on the confirmation page
### What is the root cause of that problem?
In MoneyRequest view we are only checking canEditDistanceRate prop before we are making the button interactive and displaying right icon
https://github.com/Expensify/App/blob/2c60fc937881a77062f0e07a405fa0380cc847b3/src/components/ReportActionItem/MoneyRequestView.tsx#L349-L353
### What changes do you think we should make in order to solve the problem?
We should check for readonly prop too 
```
interactive={canEditDistanceRate && !readonly}
shouldShowRightIcon={canEditDistanceRate && !readonly}
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-07 10:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Distance rate is editable on the confirmation page
### What is the root cause of that problem?
In `MoneyRequestview` we are only checking `canEditDistanceRate` prop before we are making the button interactive and displaying right icon
https://github.com/Expensify/App/blob/2c60fc937881a77062f0e07a405fa0380cc847b3/src/components/ReportActionItem/MoneyRequestView.tsx#L349-L353
### What changes do you think we should make in order to solve the problem?
We should check for readonly prop too 
```javascript
interactive={canEditDistanceRate && !readonly}
shouldShowRightIcon={canEditDistanceRate && !readonly}
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-07 10:36
I can raise a quick PR if needed.

**Comment by trjExpensify** [comment] 2024-08-07 11:28
@pecanoro dupe detection is behind a beta, this isn't a deploy blocker right?

**Comment by pecanoro** [comment] 2024-08-07 11:48
Yes, removing the blocker

**Comment by pecanoro** [comment] 2024-08-07 11:48
This one is also pretty easy so I am going to change the initial price to $125

**Comment by trjExpensify** [comment] 2024-08-07 11:48
Perf, thanks!

**Comment by trjExpensify** [comment] 2024-08-07 11:49
Adding `External` to get a C+ assigned to review https://github.com/Expensify/App/issues/46954#issuecomment-2273158439.

**Comment by sakluger** [comment] 2024-08-16 00:19
Rocio is on vacation until next week - she'll review once she's back.

**Comment by pecanoro** [comment] 2024-08-19 15:00
Just came back today, thank you for waiting! Assigning @dominictb to the issue

**Comment by sakluger** [comment] 2024-09-03 23:16
Summarizing payment on this issue:

Contributor: @dominictb $125, paid via Upwork
Contributor+: @ishpaul777 $125, paid via Upwork 

@ishpaul777 do we need regression steps or are we good as is?

**Comment by sakluger** [comment] 2024-09-04 18:05
Friendly bump @ishpaul777 I think we may need a regression test for this one.

**Comment by sakluger** [comment] 2024-09-04 23:35
Looks great, thanks!

**Closed by sakluger** 2024-09-04 23:35 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
