### ISSUE TITLE
[$500] Room - Hmm... it's not here page appears when leaving the room on another device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26136] opened 2023-08-28 22:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24111
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any Expensifail account in 2 different device
3. Create the room with WS that have some members
4. Send a simple text message, a picture and request to split bill
5. Exit the room on another device

## Expected Result:
You get navigated to concierge

## Actual Result:
Hmm... it's not here page appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2ac3359a-4de3-4d34-b78a-5fc8a5603775

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a94d6a85e6b14ed3</li>
        <li>Upwork Job ID: 1699144974222155776</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-09-12 13:54
I raised a thread in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1694526849370509) so we can sync up on next steps.

**Comment by ayazalavi** [comment] 2023-09-12 14:42
@johncschuster is this still open for working?

**Comment by sobitneupane** [comment] 2023-09-13 07:44
@ayazalavi Yup. This is still open.

**Comment by johncschuster** [comment] 2023-09-13 14:52
Yes! We'd love a proposal if you've got one, @ayazalavi!

**Comment by ayazalavi** [comment] 2023-09-14 04:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
As soon as user leaves the room then if same room is open in some other device app doesnt redirect to concierge

### What is the root cause of that problem?
Root cause of the problem exists in 

https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/home/ReportScreen.js#L303-L310

As soon as **`report.reportID`** gets undefined then app shows FullPageNotFoundView. So when we leave room then report gets deleted from the server end and gets synced immediately on all other devices. There is no handling of such case in relevant file.

### What changes do you think we should make in order to solve the problem?
Add following code in [ReportScreen](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js)

```
useEffect(() => {
        if (!report.reportID)
            Report.navigateToConciergeChat()
    }, [report.reportID])
```

### What alternative solutions did you explore? (Optional)
Throughly investigate how each UI is getting effected because of multiple device and api syncing happening in real time issue. Solve all those generically.

**Comment by pradeepmdk** [comment] 2023-09-14 05:40
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
As soon as user leaves the room then if same room is open in some other device app doesnt redirect to concierge

### What is the root cause of that problem?
```javascript
[info] [Report] Handled multipleEvents event sent by Pusher - {"updates":[{"data":[{"onyxMethod":"set","key":"report_7296831135232026","value":null}],"eventType":"onyxApiUpdate"}]}
``` 
The problem is whenever we are leave the room pusher send a onyxcommand for remove the data. so the at the time we are setting the default param in 
```javascript
report: {
        hasOutstandingIOU: false,
        isLoadingReportActions: false,
    },
``` 
so at the time report ID is not there so we are again read report id from route param and calling the         `Report.openReport(reportIDFromPath);` and open report api will return 403  and update the report in to {isLoadingReportActions: false } its showing the hmm.its not there page
https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/home/ReportScreen.js#L304


### What changes do you think we should make in order to solve the problem?
we should change the pusher event whenever leave the room We need to send one more prop {isLeaveRoom: true} so that we can identify the user is leaving the room Based on that we can call    `navigateToConciergeChat()`; to redirect the `concierge` chat. after navigating we can update the isLeaveRoom false. so that when a user tries to access the page we will show the again hmm.. screen.

**Comment by ayazalavi** [comment] 2023-09-14 06:15
### Proposal
[Updated](https://github.com/Expensify/App/issues/26136#issuecomment-1718729888)

**Comment by pradeepmdk** [comment] 2023-09-14 06:45
@ayazalavi  we need some different key for when they leave room
```javascript
useEffect(() => {
        if (!report.reportID)
            Report.navigateToConciergeChat()
    }, [report.reportID])
``` 
when we use this regression will create an invalid report.

when user enter invalid phone number we need show `You don't have access to this chat` this will happen for both money request and split bill.

**Comment by ayazalavi** [comment] 2023-09-16 14:41
### Proposal updated
[Updated](https://github.com/Expensify/App/issues/26136#issuecomment-1718729888)

**Comment by ayazalavi** [comment] 2023-09-16 14:43
@sobitneupane, please review my proposal and let me know if it is feasible for creating a PR. If there are any missing conditions that should be included, please inform me, and I will make the necessary additions to my proposal.

**Comment by sobitneupane** [comment] 2023-09-18 09:16
Thanks for the proposal @pradeepmdk 

> we should change the pusher event whenever leave the room We need to send one more prop {isLeaveRoom: true} so that we can identify the user is leaving the room Based on that we can call navigateToConciergeChat(); to redirect the concierge chat. after navigating we can update the isLeaveRoom false. so that when a user tries to access the page we will show the again hmm.. screen.

Your idea looks good.

Can you please add more details to your solution? What are the files that will be affected? What sort of change will be required. Pseudo code along with some explanation will be helpful.

**Comment by sobitneupane** [comment] 2023-09-18 09:19
Thanks for the update @ayazalavi

I don't think that's the right way to deal with the issue. We want to navigate to concierge only when user leaves the room. So, we should make sure to do so. The condition you are adding might be true in other conditions as well.

**Comment by ayazalavi** [comment] 2023-09-18 11:32
@sobitneupane Have you looked at my updated proposal. https://github.com/Expensify/App/issues/26136#issuecomment-1718729888

This condition:

```
 if (!report.reportID && isRoom && hasAccess) {
        Report.navigateToConciergeChat();
    }
```
will only be true if user leaves the room.

**Comment by pradeepmdk** [comment] 2023-09-20 03:55
@sobitneupane i think this pr solve this issue https://github.com/Expensify/App/pull/24407/files#diff-dd4bfa50713397aca8cb40145317936ab0affe19abc2a9c24d6c8849ed75dc9b

**Comment by sobitneupane** [comment] 2023-09-25 10:39
@pradeepmdk The PR you mentioned has merged. Is this issue still reproducible in your end?

**Comment by pradeepmdk** [comment] 2023-09-25 15:36
@sobitneupane Its working now

**Comment by sobitneupane** [comment] 2023-09-26 03:56
> some blink is there before navigating to navigateToConciergeChat Can we fix it here?

Yes. I think we should fix it. Do you have proposal?

**Comment by johncschuster** [comment] 2023-10-04 21:33
bump @pradeepmdk!

**Comment by pradeepmdk** [comment] 2023-10-05 08:53
@johncschuster Sorry I missed the notification. let me update you now.

**Comment by pradeepmdk** [comment] 2023-10-05 16:02
@johncschuster @sobitneupane this issue was pusher sending delay response. before sending `USER_IS_LEAVING_ROOM` its send the `multipleEvents` so that its showing `Hmm...`page after getting the `USER_IS_LEAVING_ROOM` events its redirected to `ConciergeChat`.

but at the code level we are sending the `USER_IS_LEAVING_ROOM` first even though its sending the `multipleEvents` first.
https://github.com/Expensify/App/blob/035ee44762e656874c764f1efb1b85cd14958506/src/libs/actions/Report.js#L1916


https://github.com/Expensify/App/assets/16595846/e7c75319-71bd-42e4-8043-1ca6eec94784

so currently i don't have any idea how to boost `USER_IS_LEAVING_ROOM` pusher event first.

Note: sometime  `USER_IS_LEAVING_ROOM` is triggered first at the time we don't have this issue.

https://github.com/Expensify/App/assets/16595846/845e0035-fa2f-436e-98f1-f2d129f49039

**Comment by johncschuster** [comment] 2023-10-10 21:19
@sobitneupane bump!

**Comment by sobitneupane** [comment] 2023-10-11 03:30
Thanks for the update @pradeepmdk

**Comment by sobitneupane** [comment] 2023-10-11 03:30
The nature of the issue has changed a bit. The "Hmm... it's not here page" appears only for short duration. We are looking on proposals to see if we can get rid of the Not found page.

**Comment by johncschuster** [comment] 2023-10-13 20:33
Thanks for that, @sobitneupane! How would you re-title this issue to better reflect what we're looking for?

Also, do the reproduction steps still match?

**Comment by ayazalavi** [comment] 2023-10-17 12:34
> The nature of the issue has changed a bit. The "Hmm... it's not here page" appears only for short duration. We are looking on proposals to see if we can get rid of the Not found page.

This bug is not reproducible anymore, page is directly going to concierage page.

**Comment by johncschuster** [comment] 2023-10-17 20:49
Thanks, @ayazalavi! It sounds like this behavior may have been resolved by a different issue/PR. I'm going to go ahead and close it.

**Closed by johncschuster** 2023-10-17 20:49 UTC
Labels: Engineering, Daily, Internal, Bug
