### ISSUE TITLE
[HOLD for payment 2023-05-29] [$1000] Contact suggestion focus/selection does not reset after selecting a contact

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18844] opened 2023-05-12 16:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat and write “@” only to mention a contact
2. Use the down arrow key on the keyboard to navigate through the contact suggestion list and select the second contact in the suggestion list and hit enter key
3. Write "@" again

## Expected behavior:
The contact suggestion selection should start from the first contact again
## Actual behavior:
The contact suggestion selection remains on the previously selected contact

NOTE : This behavior is inconsistent with the emoji suggestion functionality (video attached)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/115b9458-67de-4334-b671-c3dcf92133b5

https://github.com/Expensify/App/assets/43996225/81afc7e1-8915-494c-8aa0-cae3f7857376

https://github.com/Expensify/App/assets/43996225/07ba40ce-c2c9-49aa-9fde-6518a2c0f27f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683803719905009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013072759f95d2c09f</li>
        <li>Upwork Job ID: 1657773872119492608</li>
        <li>Last Price Increase: 2023-05-14</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-12 16:45
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Contact suggestion focus/selection does not reset after selecting a contact.

### What is the root cause of that problem?
When we press enter it will run this code.
https://github.com/Expensify/App/blob/101a3e2e990c395879f578e520a9f60b6e95f5d4/src/pages/home/report/ReportActionCompose.js#L749-L758

We can see we are not resetting the index after suggesting. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
We have to reset index as shown in code below i.e. `this.setState({highlightedMentionIndex: 0});`
```javascript
if ((e.key === CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey || e.key === CONST.KEYBOARD_SHORTCUTS.TAB.shortcutKey) && suggestionsExist) {
    e.preventDefault();
    if (this.state.suggestedEmojis.length > 0) {
        this.insertSelectedEmoji(this.state.highlightedEmojiIndex);
    }
    if (this.state.suggestedMentions.length > 0) {
        this.insertSelectedMention(this.state.highlightedMentionIndex);
        this.setState({highlightedMentionIndex: 0});     // ***  Add this
    }
    return;
}
```

This will solve the issue.

### What alternative solutions did you explore? (Optional)
None

**Comment by PrashantMangukiya** [comment] 2023-05-12 16:59
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Contact suggestion focus/selection does not reset after selecting a contact.

### What is the root cause of that problem?
When we press enter it will run this code.
https://github.com/Expensify/App/blob/101a3e2e990c395879f578e520a9f60b6e95f5d4/src/pages/home/report/ReportActionCompose.js#L749-L758

We can see we are not resetting the index after suggesting. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
We have to reset index as shown in code below i.e. `this.setState({highlightedMentionIndex: 0});`
```javascript
if ((e.key === CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey || e.key === CONST.KEYBOARD_SHORTCUTS.TAB.shortcutKey) && suggestionsExist) {
    e.preventDefault();
    if (this.state.suggestedEmojis.length > 0) {
        this.insertSelectedEmoji(this.state.highlightedEmojiIndex);
    }
    if (this.state.suggestedMentions.length > 0) {
        this.insertSelectedMention(this.state.highlightedMentionIndex);
        this.setState({highlightedMentionIndex: 0});     // ***  Add this
    }
    return;
}
```

This will solve the issue as shown in result video.

### What alternative solutions did you explore? (Optional)
If we have to match code similar to emoji suggestion then we have to add `highlightedMentionIndex: 0` for next state here.
https://github.com/Expensify/App/blob/101a3e2e990c395879f578e520a9f60b6e95f5d4/src/pages/home/report/ReportActionCompose.js#L541-L545

So updated code looks as under
```javascript
const nextState = {
    suggestedMentions: [],
    highlightedMentionIndex: 0, // *** ADD THIS ***
    atSignIndex,
    mentionPrefix: prefix,
};
```

This will also solve the issue and give same results.

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/7823358/c74bf2a2-6cd2-4b50-8feb-2eab85e49266

</details>

**Comment by isabelastisser** [comment] 2023-05-12 19:56
I won't be able to act on this until next Tuesday (Compliance deadlines), reassigning!

**Comment by alexpensify** [comment] 2023-05-13 16:20
I started an internal discussion here: https://expensify.slack.com/archives/C049HHMV9SM/p1683994795740649?thread_ts=1683803719.905009&cid=C049HHMV9SM

**Comment by alexpensify** [comment] 2023-05-14 15:45
I confirmed this is a bug and I can replicate it. With that said, the team confirmed the expectations: 

>the list selection should start at the top for a new mention input.

For now, I'm marking it as `External`.

**Comment by mananjadhav** [comment] 2023-05-14 18:18
Thanks for confirming it @alexpensify. I think we should use @PrashantMangukiya's alternative approach of resetting it in `nextState`. It is inline with our current approach, we do for `EmojiSuggestions`.

@amyevans All yours.

**Comment by dukenv0307** [comment] 2023-05-15 04:24
@mananjadhav Sorry for my lateness but I see that the selected proposal is not exhaustive and it doesn't cover all cases

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Contact suggestion focus/selection does not reset after selecting a contact 

### What is the root cause of that problem?
We don't reset suggestion in both calculateMentionSuggestion function and insertSelectedMention function
### What changes do you think we should make in order to solve the problem?
1. We should reset suggestion when the selection change
For consistency with emoji suggestion, on `calculateMentionSuggestion` function we should reset `highlightedMentionIndex`, `shouldShowMentionSuggestionMenu`, `isAutoSuggestionPickerLarge` in the next state
```
const hasEnoughSpaceForLargeSuggestion = this.props.windowHeight / this.state.composerHeight >= 6.8;
const isAutoSuggestionPickerLarge = !this.props.isSmallScreenWidth || (this.props.isSmallScreenWidth && hasEnoughSpaceForLargeSuggestion);

        const nextState = {
            suggestedMentions: [],
            atSignIndex,
            mentionPrefix: prefix,
            highlightedMentionIndex: 0, // ADD HERE
            shouldShowMentionSuggestionMenu: false, // ADD HERE
            isAutoSuggestionPickerLarge, // ADD HERE
        };
```
2. If we want to remain highlightedMentionIndex when the user changes the selection, we can set `highlightedMentionIndex: 0 ` in `insertSelectedMention` function and do the same thing in the emoji suggestion

### Additional Bug
I mentioned it here because it relates to the original issue and the original issue is so straightforward. So I think we should fix this issue
The mentioned suggestion still displays when the cursor is in the first place
https://github.com/Expensify/App/assets/129500732/82c16339-cd81-4020-ba0f-29bfd9c3117e
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/6c10bb2b36069b74e2dfcc5a97c42c2be6e767e1/src/pages/home/report/ReportActionCompose.js#L517-L520
We don’t reset suggestions when this.state.selection.end < 1
### Solution for Additional Bug

when this.state.selection.end < 1, we should call this.resetSuggestions()
### What alternative solutions did you explore? (Optional)

**Comment by PrashantMangukiya** [comment] 2023-05-15 14:05
My proposed solution and root cause analysis is according to the expected result of the issue and solves the problem. So technically my proposal is complete according to the expected result. 

There could be many ways to suggest additional changes with proposal, but if I did not suggest additional changes it doesn't mean that my proposal is incomplete. During PR review time we can do other adjustment if decided by reviewer team.

Also if any additional bug is found then there is a procedure to report that bug on Slack and then move forward. By just mentioning that bug and solution in a proposal with current issue does not mean that other proposals are incomplete.

This is just my understanding. I am happy with whatever decision taken by C+ member.

cc: @mananjadhav

**Comment by alexpensify** [comment] 2023-05-15 22:19
@amyevans and @mananjadhav - any feedback here?

**Comment by amyevans** [comment] 2023-05-16 00:21
Hiring @PrashantMangukiya, you can get a PR started please!

**Comment by PrashantMangukiya** [comment] 2023-05-16 00:33
@amyevans @mananjadhav @alexpensify Thank you, I will prepare and submit pr within few hours asap.

**Comment by alexpensify** [comment] 2023-05-17 17:42
@dylanexpensify - this one is moving forward, but assigning if a BZ team member is needed to step in while I'm OOO.

**Comment by dylanexpensify** [comment] 2023-05-19 08:55
Nice work everyone! Looking forward to paying you all out that bonus! 🤑

**Comment by dylanexpensify** [comment] 2023-05-22 07:40
Hmm, shouldn't the BZ checklist and Payment Due items have populated? cc @amyevans

**Comment by alexpensify** [comment] 2023-05-24 21:08
@johncschuster and @dylanexpensify - I appreciate your help here! I'm back online and removing your assignment.

**Comment by alexpensify** [comment] 2023-05-27 01:08
@mananjadhav - when you get a chance can you please fill out the checklist: https://github.com/Expensify/App/issues/18844#issuecomment-1558173892

Thanks!

**Comment by alexpensify** [comment] 2023-05-27 01:11
@mananjadhav and @PrashantMangukiya - To prepare for the payment date, please apply to the job in Upwork: 

 https://www.upwork.com/jobs/~013072759f95d2c09f

Thanks!

**Comment by PrashantMangukiya** [comment] 2023-05-27 05:36
@alexpensify Can you please invite me for the job. I have not enough Upwork connect balance to submit proposal. This is my Upwork profile https://www.upwork.com/freelancers/~01c718889ed7821f82  Thank you for your time.

**Comment by mananjadhav** [comment] 2023-05-27 20:59
We added the Mentions support in this PR https://github.com/Expensify/App/pull/18469, where we didn't reset the index. I don't see any need for a regression test, nor updating the checklist. This can be categorized as  missing test case/mistake.

I've commented on the offending PR to let the contributors know.

@amyevans do you think we need a regression test here?

**Comment by alexpensify** [comment] 2023-05-28 15:49
Thank you for that update @mananjadhav!

**Comment by mananjadhav** [comment] 2023-05-29 23:10
@alexpensify this is ready for payout.

**Comment by amyevans** [comment] 2023-05-30 14:44
> @amyevans do you think we need a regression test here?

No I think we're fine without.

**Comment by alexpensify** [comment] 2023-05-30 14:47
Sorry, I should have flagged that I was offline yesterday for the US Bank Holiday but most of the team was offline too. I will work on the payment process today.

**Comment by alexpensify** [comment] 2023-05-30 20:52
Flagging the urgency bonus here: https://github.com/Expensify/App/issues/18844#issuecomment-1551756000

**Comment by PrashantMangukiya** [comment] 2023-05-30 22:31
@alexpensify Offer accepted on Upwork.

**Comment by Nathan-Mulugeta** [comment] 2023-05-31 04:42
Just accepted offer @alexpensify

**Comment by alexpensify** [comment] 2023-05-31 19:47
Alright, @mananjadhav, @PrashantMangukiya, and @Nathan-Mulugeta have been paid via Upwork. Great work here!

**Closed by alexpensify** 2023-05-31 19:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
