### ISSUE TITLE
[HOLD - should be resolved by #23755][$500] [Distance] - User is able to request money from an archived workspace using link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27113] opened 2023-09-10 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money -> distance
2. Fill start and finish points
3.  Select a workspace
4. Copy link
5. Delete that workspace
6. Past the copied link

## Expected Result:
Users should not have the ability to request money from an archived workspace

## Actual Result:
The User is able to request money from an archived workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[distance-archive.webm](https://github.com/Expensify/App/assets/93399543/57f2e29e-119b-4b4d-b470-68e391cc68fd)

https://github.com/Expensify/App/assets/93399543/3bb79d2a-3cc9-4a56-95ce-f572db19ed77

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693924665226099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144d881c5d2a1b34f</li>
        <li>Upwork Job ID: 1700942638080782336</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-10 18:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Distance] user is able to request money from an archived workspace using link

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/911fe99c56116f1a36c38fb596251bbce5fc1b33/src/components/MoneyRequestConfirmationList.js#L361

This is the condition to disable the Request button. We don't check if the policy is archive or not

### What changes do you think we should make in order to solve the problem?
In MoneyRequestConfirmationList, we should add a condition to check if workspace is deleted. If that we should disable button and display a error message like this 

<img width="976" alt="Screenshot 2023-09-08 at 14 52 33" src="https://github.com/Expensify/App/assets/141406735/48c542e6-ecd4-4dd9-81ab-0fa0afa5754f">

To do that, in herehttps://github.com/Expensify/App/blob/911fe99c56116f1a36c38fb596251bbce5fc1b33/src/components/MoneyRequestConfirmationList.js#L361
we should update the condition like that
```
const shouldDisableButton = selectedParticipants.length === 0 || (props.isDistanceRequest && ReportUtils.isArchivedRoom(selectedParticipants[0]));
```

and in here, https://github.com/Expensify/App/blob/911fe99c56116f1a36c38fb596251bbce5fc1b33/src/components/MoneyRequestConfirmationList.js#L264

add an error message 

```
brickRoadIndicator: (props.isDistanceRequest && ReportUtils.isArchivedRoom(selectedParticipants[0])) ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : null,
allReportErrors:  (props.isDistanceRequest && ReportUtils.isArchivedRoom(selectedParticipants[0])) ? ['Please select a valid participant']  : null,   // need to use translation here
``` 

The completed code change will be implemented in the PR phrase

### What alternative solutions did you explore? (Optional)
If the selected workspace is deleted, we will redirect to the distance request page. To do that, 
https://github.com/Expensify/App/blob/911fe99c56116f1a36c38fb596251bbce5fc1b33/src/pages/iou/steps/MoneyRequestConfirmPage.js#L75 
Add condition and logic to redirect to distance page
```
if (isDistanceRequest && ReportUtils.isArchivedRoom(participants[0])) {
            Navigation.goBack(ROUTES.getMoneyRequestRoute(iouType.current, reportID.current), true);
        }

```

**Comment by johncschuster** [comment] 2023-09-12 13:57
Thanks for the heads up, @dukenv0307!

**Comment by garrettmknight** [comment] 2023-09-21 11:39
Still waiting on https://github.com/Expensify/App/issues/23755

**Comment by garrettmknight** [comment] 2023-10-03 17:09
Still waiting on https://github.com/Expensify/App/issues/23755

**Comment by garrettmknight** [comment] 2023-10-11 20:12
Still holding.

**Comment by garrettmknight** [comment] 2023-10-16 16:13
Still holding.

**Comment by garrettmknight** [comment] 2023-10-25 18:16
Moving daily to retest - there was a regression on the issue we were holding on so it still might be an issue.

**Comment by garrettmknight** [comment] 2023-10-31 17:16
Haven't had a chance to retest today - will do tomorrow.

**Comment by garrettmknight** [comment] 2023-11-01 18:52
This has been fixed, once you reload the distance request you're required to select a new workspace.

@hichamcc accept the offer and I'll pay the reporting bonus.

Upwork job for my reference: https://www.upwork.com/en-gb/ab/applicants/1719789138652127232/hired

**Comment by hichamcc** [comment] 2023-11-01 19:10
Done

**Comment by garrettmknight** [comment] 2023-11-01 19:38
Paid, closing

**Closed by garrettmknight** 2023-11-01 19:38 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
