### ISSUE TITLE
[HOLD for payment 2024-03-20] HIGH: [$1000] MacOS App does not update via 'Check for Updates' when an update is available

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36522] opened 2024-02-14 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.40-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707839105781559

## Action Performed:

Prereq: Must be running an out-of-date version of the MacOS app + have an update to the MacOS app available
1. Open MacOS app
2. Ignore any 'update available' pop up
3. Select New Expensify > Check for Update in the menu bar
4. You'll see a notification titled "Update Available"

## Expected Result:
If an update is available, there should be an option to update the app.

## Actual Result:
There isn't a way to update the app in the message. The button just says 'Sounds Good' and clicking it only closes the 

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/4f4221ee-f1d9-47df-8226-377c6a8b1f7d

https://github.com/Expensify/App/assets/38435837/53bca25e-e967-4257-9b58-9e78172e1685

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cdfd41c70cb0eeb</li>
        <li>Upwork Job ID: 1757798834716602368</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by garrettmknight** [comment] 2024-02-14 19:15
@johncschuster just reassigning in case this needs help while I'm OOO this week - will be back 2/21 to pick it back up

**Comment by mallenexpensify** [comment] 2024-02-16 16:35
@johncschuster and @eVoloshchak , are you able to reproduce this on Desktop?  It's still happening for me, trying to suss out how common the bug is (and what the specific work-around is to get the app to update).

**Comment by dangrous** [comment] 2024-02-16 17:26
I think this is happening to me on Desktop staging - v 1.4.40-0

**Comment by eVoloshchak** [comment] 2024-02-20 15:28
I'm able to reproduce this on Desktop
I agree with @kameshwarnayak's [comment](https://github.com/Expensify/App/issues/36522#issuecomment-1944440351), the modal itself should just close and do nothing
> The message clearly says "The new version will be available shortly. We'll notify you when we're ready to update." It is not supposed to do anything I suppose.
(what is the purpose of this modal?)

However, I think the real problem is the app not updating. My Desktop app is stuck on 1.4.8-1, pressing 'Update New Expensify' does nothing

**Comment by dangrous** [comment] 2024-02-20 16:09
yeah thanks for the clarification @eVoloshchak - I think usually there is some delay between clicking that and the update itself, so the update is the issue not the button.

I am struggling to figure out a way to fix stuck versions, though. Because even if we fix this, how do we update the versions that won't update in order for them to update?

**Comment by mallenexpensify** [comment] 2024-02-21 01:49
> The message clearly says "The new version will be available shortly. We'll notify you when we're ready to update." It is not supposed to do anything I suppose.
(what is the purpose of this modal?)

@kameshwarnayak , @eVoloshchak , For the past couple years, the flow was a version of
- Click `Check for Updates`
- Click button to Update
- Pop surfaces asking if you'd like to update
- App closes, updates, reopens. 

It seemed to make more sense that way than the way it is now where the version can get stuck and not updated for a while.  Albeit... this is only for Desktop and I think most users are on web, so it's likely not the highest priority.

**Comment by garrettmknight** [comment] 2024-02-21 18:22
Back and picking this one up - @mallenexpensify I think this is might be working as expected. When an update is available, the menu item reads something differently than 'Check for updates'. I think it's 'Update New Expensify' or something like that. When you click it, it updates.

To make sure I'm repro'ing correctly, what's the initial scenario we need to test?
- Must have updated NewDot Desktop version available
- Must have ignored the initial pop-up? Or is this before the pop-up happens?

**Comment by garrettmknight** [comment] 2024-02-21 18:23
Setting to `Needs reproduction` until I can figure out how to test.

**Comment by dangrous** [comment] 2024-02-22 16:26
Yesterday I decided to just redownload from the staging dmg, so it's a totally new app - but I'm still having this issue... Might it be an account setting for some reason?

**Comment by garrettmknight** [comment] 2024-02-22 19:36
Taking `Needs Repro` off since we have multiple instances, but I'm not really sure how to test this without having downloaded an older version of the app. Posted a question about downloading an older version of the app to test with [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1708630505069469) but if you've got any ideas I'm happy to test and see if/why it gave me a different option when I had an update available.

**Comment by garrettmknight** [comment] 2024-02-26 12:05
Ok, tested and confirmed on 1.4.43-3.

**Comment by garrettmknight** [comment] 2024-02-28 18:09
Adding to vip-vsp to get some more eyes on it.

**Comment by garrettmknight** [comment] 2024-02-29 19:30
Still waiting on some help.

**Comment by puneetlath** [comment] 2024-02-29 20:16
Shall we increase the bounty?

**Comment by garrettmknight** [comment] 2024-03-01 16:03
Sure!

**Comment by mallenexpensify** [comment] 2024-03-01 18:26
I just updated Zoom and the process was
- Clicked `Check for Update"
- Update was available so it **automatically** started updating, and showing a progress bar. 
- App updated. 

That seems like a better process than what we're using, especially to ensure people are on the latest version (vs having to click 'update' an additional time).  I think that, for anyone who clicks 'check for update', they want to update the app vs just wondering if an update is available. 

Does anyone know if we're discussing the updating progress as part of a project?  
Caveat... it's only for Desktop which is only Mac (for now) so maybe it's not a high priority for us in the near term. 

<img width="884" alt="image" src="https://github.com/Expensify/App/assets/22508304/bccbd0d8-7be1-4156-840d-00283cbf70d6">

**Comment by badeggg** [comment] 2024-03-02 12:43
I can't even find where to download the desktop app 🥲

**Comment by s77rt** [comment] 2024-03-04 23:52
Testing this I _think_ the problem is related to code signing, I'm getting the following error messages:
```
00:13:02.903 › Error: Code signature at URL file:///Users/s77rt/Library/Caches/com.expensifyreactnative.chat.ShipIt/update.dD164rv/New%20Expensify.app/ did not pass validation: code failed to satisfy specified code requirement(s)
00:13:02.903 › Error: Error: Code signature at URL file:///Users/s77rt/Library/Caches/com.expensifyreactnative.chat.ShipIt/update.dD164rv/New%20Expensify.app/ did not pass validation: code failed to satisfy specified code requirement(s)
```

However I'm testing against a local build so that ^ may be irrelevant. I have asked in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1709595734067259) to get an old version to test accurately.

 I found this PR https://github.com/Expensify/App/pull/30599 which could be the culprit.

**Comment by garrettmknight** [comment] 2024-03-05 19:20
@eVoloshchak any thoughts on the PR @s77rt highlighted?

**Comment by garrettmknight** [comment] 2024-03-07 20:07
@eVoloshchak can you give these proposals a review?

**Comment by garrettmknight** [comment] 2024-03-08 19:29
Bumped in slack.

**Comment by eVoloshchak** [comment] 2024-03-08 23:03
> Does anyone know if we're discussing the updating progress as part of a project?
Caveat... it's only for Desktop which is only Mac (for now) so maybe it's not a high priority for us in the near term.

@mallenexpensify, I cannot find anything related to this in the Expensify slack workspace, looks like there isn't a discussion (external one, at least)


@suneox, @ikevin127, I agree the current logic isn't ideal and we should alight it with what is described in https://github.com/Expensify/App/issues/36522#issuecomment-1973714163. However, the update process itself seems to be broken, since it was working before with the current flow, let's focus on that first. But i agree we should have a discussion on whether the current flow needs to be changed

@s77rt, [this](https://github.com/Expensify/App/issues/36522#issuecomment-1977687431) is an interesting finding
I wonder if there's a way to test this in DEV?
When https://github.com/Expensify/App/issues/36758 is done we will be able to have historical artifacts from all our deploys (so we could pinpoint the exact version in which the bug first occurs), but it won't be applied retroactively

**Comment by garrettmknight** [comment] 2024-03-09 07:21
I don't think we've discussed updating this function anywhere recently. The "bug" in this case is that it doesn't seem like anything is actually happening when you check for updates. There's definitely a design improvement to indicate what happens next a la "downloading update", but I'm also curious about why this stopped working now. Can we dig into the PR that @s77rt flagged to see if that change is the issue to start and I'll get a convo going for the design update on Monday?

**Comment by s77rt** [comment] 2024-03-09 11:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Broken app update feature

### What is the root cause of that problem?
The supposedly imported `checkForUpdates` function is not imported correctly. This is a regression from https://github.com/Expensify/App/pull/35473 https://github.com/Expensify/App/commit/21e645d7a45afd49a9828e0847db78f1d9c62b3f

### What changes do you think we should make in order to solve the problem?
Fix the function importation 

```js
const checkForUpdates = require('../src/libs/checkForUpdates').default;
```

### What alternative solutions did you explore? (Optional)
None

**Comment by s77rt** [comment] 2024-03-09 11:57
Adding to ^ checkForUpdates function is used to initialize the electron updater to listen to update events so that when the download is completed, the new version will get installed or ask the user to install it ([ref1](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/desktop/main.js#L623), [ref2](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/desktop/main.js#L185-L205)).

**Comment by abzokhattab** [comment] 2024-03-09 11:59
good catch @s77rt !

**Comment by garrettmknight** [comment] 2024-03-11 10:59
@eVoloshchak do we have a complete proposal from @s77rt yet?

**Comment by eVoloshchak** [comment] 2024-03-11 22:45
@suneox, I agree the flow could be changed, but there are a lot of valid points listed in https://github.com/Expensify/App/issues/36522#issuecomment-1973714163. This is desktop only, so probably not a high priority. Let's focus on fixing the root cause for the bug itself in this issue and discuss possible improvements to the update flow in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1707839105781559)

@s77rt, [this](https://github.com/Expensify/App/issues/36522#issuecomment-1986835565) is a great catch!
@s77rt's proposal looks good to me

🎀👀🎀 C+ reviewed!

**Comment by lakchote** [comment] 2024-03-12 13:05
Nice find @s77rt, your proposal LGTM 👍

**Comment by s77rt** [comment] 2024-03-18 14:37
Issue is resolved now (by ts migration) https://github.com/Expensify/App/pull/37615

**Comment by garrettmknight** [comment] 2024-03-18 18:49
Will test once that gets to prod.

**Comment by garrettmknight** [comment] 2024-03-19 19:01
I just tested and 'Check for updates' didn't notify me when the download was complete. I waited for 30 mins before closing/reopening the app to confirm that the udpate completed. @s77rt should that change have gone into effect immediately or do I need to wait for another release to test again?

**Comment by s77rt** [comment] 2024-03-19 19:13
@garrettmknight On which version you tested? You need at least version 1.4.54-0 to test on

**Comment by garrettmknight** [comment] 2024-03-19 20:11
I'm on 1.4.54-1 now - will wait for the next update to test in that case.

**Comment by lakchote** [comment] 2024-03-20 07:39
> @garrettmknight On which version you tested? You need at least version 1.4.54-0 to test on

@s77rt It should have worked for Garrett, no? Since he was on version 1.4.54-1.

It has now been [deployed to production](https://github.com/Expensify/App/pull/37615#issuecomment-2008323547) @garrettmknight, could you test again please?

**Comment by garrettmknight** [comment] 2024-03-20 12:50
I wasn't on 1.4.54-1 when I tested, that's what it updated to from the older version. Annnnnddd my computer restarted so the new version installed automatically when I reopened. WIll hold to test on the next release - unless you have an earlier version and can test now @lakchote ?

**Comment by puneetlath** [comment] 2024-03-20 12:53
I was just able to update my Desktop app from 1.4.54-1 to 1.4.55-0.

**Comment by lakchote** [comment] 2024-03-20 13:14
> I wasn't on 1.4.54-1 when I tested, that's what it updated to from the older version. Annnnnddd my computer restarted so the new version installed automatically when I reopened. WIll hold to test on the next release - unless you have an earlier version and can test now @lakchote ?

Understood, thanks for the precision Garrett. Unfortunately, I already have the latest version.

But it looks like it works since @puneetlath just test it successfully!

**Comment by garrettmknight** [comment] 2024-03-20 13:22
Nice, thanks @puneetlath. We can finish this one up then. Since this got fixed without the work here, but we had a pretty active PR going I'm going to partially pay out at 50%.

**Comment by garrettmknight** [comment] 2024-03-20 13:27
@s77rt offer out to you.

**Comment by garrettmknight** [comment] 2024-03-20 13:27
**Summary of payment:**
- Contributor: @s77rt $500 to be paid via Upwork
- Reviewer: @eVoloshchak $500

**Comment by s77rt** [comment] 2024-03-20 14:40
@puneetlath Just to confirm, you saw a popup or a notification informing you that the update is downloaded right? Because the update was never broken, it was just silent

**Comment by s77rt** [comment] 2024-03-20 14:41
@garrettmknight Accepted

**Comment by puneetlath** [comment] 2024-03-20 15:04
Hmm, I don't remember if I saw the popup 😅. I can check again next time. When I do "check for updates" now I get this, which I wasn't getting before, so that seems good. 

<img width="499" alt="Screenshot 2024-03-20 at 10 03 05 AM" src="https://github.com/Expensify/App/assets/1371996/760ff300-d3f0-43ca-8c42-d0143a689ba5">

**Comment by garrettmknight** [comment] 2024-03-20 20:30
Will complete the payment summary tomorrow when I test to double-confirm things are working.

**Comment by garrettmknight** [comment] 2024-03-21 15:15
Noting that I just clicked check for updates and got the update available message + now I can't click check for updates:

![Uploading Screenshot 2024-03-21 at 3.14.55 PM.png…]()

**Comment by garrettmknight** [comment] 2024-03-21 15:16
And just got the pop-up:
<img width="456" alt="Screenshot 2024-03-21 at 3 16 02 PM" src="https://github.com/Expensify/App/assets/1529980/4d59809a-caa3-40e4-8983-64dee9ede2ec">

**Comment by JmillsExpensify** [comment] 2024-03-22 21:51
$500 approved for @eVoloshchak based on summary.

**Closed by JmillsExpensify** 2024-03-22 21:51 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
