### ISSUE TITLE
[HOLD for payment 2024-11-07] [$250] Task description is covered by the keyboard pop up 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50346] opened 2024-10-07 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728321152515439

## Action Performed:

1. Signed up for a new account
2. Selected Get paid by my employer
3.Tap into the Concierge DM
4.Tap into the first task

## Expected Result:think 
Keyboard should not pop up by default
## Actual Result:
keyboard is pulled up by default, which makes the task description unreadable.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![IMG_6596](https://github.com/user-attachments/assets/35f6394d-4af4-4a4a-af7b-f97883213167)
![IMG_6597](https://github.com/user-attachments/assets/e2b9b76d-7ca0-4761-8f98-c9ff241d2d10)

https://github.com/user-attachments/assets/cf7200ab-61e2-4b30-b447-77c63584179a

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843564581975607149</li>
        <li>Upwork Job ID: 1843564581975607149</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 104340068</li>
<li>nkdengineer | Contributor | 104340070</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment] 2024-10-08 06:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
keyboard is pulled up by default, which makes the task description unreadable.

### What is the root cause of that problem?
`shouldAutoFocus` is `true` for the onboarding task report because this is an empty chat that focuses on the composer and keyboard

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L302-L307


### What changes do you think we should make in order to solve the problem?
We can add the check if the report is a task report, and we can prevent autofocus on the composer

```
const [report] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT}${reportID}`);
const shouldAutoFocus =
    !modal?.isVisible &&
    Modal.areAllModalsHidden() &&
    isFocused &&
    (shouldFocusInputOnScreenFocus || (isEmptyChat && !ReportActionsUtils.isTransactionThread(parentReportAction) && !ReportUtils.isTaskReport(report))) &&
    shouldShowComposeInput;
```

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L302-L307

### What alternative solutions did you explore? (Optional)

Or we can only prevent auto-focus if the task report is the onboarding task report. To do that we can get the onboarding data from `nvp_introSelected` and check if the current `reportID` is in the list value of `nvp_introSelected` data.

**Comment by rojiphil** [comment] 2024-10-09 04:32
Thanks for your proposals.
@shahinyan11 `parentReportAction` would have an action name `ADDCOMMENT`. So, using `isTaskAction` would not work here.
@nkdengineer [proposal](https://github.com/Expensify/App/issues/50346#issuecomment-2398949822) LGTM as we can use `isTaskReport`.
Additionally, we can migrate to `useOnyx` from `withOnyx` for the Onyx values used in `ComposerWithSuggestions`
🎀👀🎀 C+ reviewed

**Comment by lakchote** [comment] 2024-10-09 14:18
@nkdengineer's proposal LGTM.

**Comment by nkdengineer** [comment] 2024-10-10 17:06
@lakchote I created the [PR](https://github.com/Expensify/App/pull/50544) here but this issue was just fixed by this [PR](https://github.com/Expensify/App/pull/50279) 2 hours ago.

**Comment by nkdengineer** [comment] 2024-10-15 04:03
Looks like this [PR](https://github.com/Expensify/App/pull/50279) has been reverted, I will open my PR soon

**Comment by anmurali** [comment] 2024-10-22 02:01
@nkdengineer - do you have an update here?

**Comment by danielrvidal** [comment] 2024-10-24 18:24
@nkdengineer can you please update this one asap? @lakchote if we don't hear back soon with an update can we look for another proposal please?

**Comment by lakchote** [comment] 2024-10-25 05:44
@danielrvidal sure! 

@nkdengineer if you don't raise your PR today/give updates I'll put the label to look for proposals this afternoon.

**Comment by nkdengineer** [comment] 2024-10-25 05:47
@lakchote We're waiting for your response in the PR.

**Comment by lakchote** [comment] 2024-10-25 06:12
> @lakchote We're waiting for your response in the PR.

Answered [here](https://github.com/Expensify/App/pull/50544#discussion_r1816054608)

**Comment by lakchote** [comment] 2024-10-25 12:10
Reached out in DM to @nkdengineer to see if he can push [the fix](https://github.com/Expensify/App/pull/50544#discussion_r1816183784) that should make his PR mergeable today.

**Comment by nkdengineer** [comment] 2024-10-25 12:29
@lakchote I will be available in a few hours.

**Comment by nkdengineer** [comment] 2024-10-25 16:28
@lakchote I updated. waiting for the running test.

**Comment by danielrvidal** [comment] 2024-10-29 03:04
Awesome, thank you!

**Comment by rojiphil** [comment] 2024-11-11 14:20
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    [Link to comment](https://github.com/Expensify/App/pull/29086/files#r1836742676): 

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not Required. The existing checklist is good enough to capture such issues.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Precondition:


### Test:
Note: The tests are applicable only for mWeb and native platforms.
1. Sign up with a new account
2. Complete onboarding step using `Track and budget expenses`
3. Navigate to Concierge DM if needed
4. Tap on `Track an expense` task to navigate to the task report
5. Verify that the keyboard is not displayed

Do we agree 👍 or 👎

**Comment by lakchote** [comment] 2024-11-13 10:40
Has the payment been processed here @JmillsExpensify?

**Comment by JmillsExpensify** [comment] 2024-11-13 13:15
Contributors paid out and regression test linked to this issue. Closing this out.

**Closed by JmillsExpensify** 2024-11-13 13:15 UTC
Labels: External, Weekly, Awaiting Payment, Bug
