### ISSUE TITLE
[$500] [Distance] Wrong navigation after editing distance in request money page.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27053] opened 2023-09-08 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with any account.
2. Click FAB icon> request money> distance.
3. Set start point and finish point and click next.
4. Select a user and in confirmation page edit the distance then click next button.
5. Notice that it takes you to select a user page instead of request money confirmation page.

## Expected Result:
App should navigate to request money confirmation page after editing the distance.

## Actual Result:
App navigate to select a user page after editing the distance.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d57a58cb-2274-4482-98f2-869bbd2f25c1

https://github.com/Expensify/App/assets/93399543/eefdf123-f9e7-47ae-8cb6-82e5e7f84d21

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693859673360709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01547e807068812813</li>
        <li>Upwork Job ID: 1700233284744568832</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-08 19:48
Dupe of #26909

**Comment by ayazalavi** [comment] 2023-09-08 20:02
@ArekChr shall I add my proposal here or is this getting handled in duplicate ticket @b4s36t4 mentioned?

**Comment by b4s36t4** [comment] 2023-09-08 20:05
@ayazalavi I'm pretty sure it a dupe.

**Comment by ayazalavi** [comment] 2023-09-08 20:15
Yes it is dupe, i just verified it. Let me put my proposal here.

**Comment by b4s36t4** [comment] 2023-09-08 20:16
here?, @ayazalavi I think your proposal should go there.

**Comment by garrettmknight** [comment] 2023-09-11 09:10
Closing this and continuing in the other issue that was reported earlier.

**Closed by garrettmknight** 2023-09-11 09:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
