### ISSUE TITLE
[HOLD #227410]  iOS - Chat - The name stops being bold until a new message is read

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10551] opened 2022-08-24 20:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to App and login with any chat device A)
2. Disable your internet connection on the device A
3. On another device (can be any), send a message to the account logged in device A

## Expected Result:
The name should be bold until the message is read

## Actual Result:
The name stops being bold until a new message is read

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186512497-d410b236-e12f-4302-8be5-e84ac070ee59.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment] 2022-08-25 09:48
Setting as external!

**Comment by laurenreidexpensify** [comment] 2022-08-25 13:07
https://www.upwork.com/jobs/~0140b90c6c44a36984

**Comment by marcaaron** [comment] 2022-08-28 21:00
myself and @sketchydroide have made some changes to report page stuff recently and more changes are coming. Once they are all done if this is still happening we can accept proposals. But I'd recommend making this `Internal` until then as it's not clear if this is front end or backend issue.

**Comment by mallenexpensify** [comment] 2022-08-29 21:37
Reported a similar/same issue this morn, dropped a comment in there and tagged you Marc and Andre (Thanks @rushatgabhane for linking back to this one)
https://expensify.slack.com/archives/C01GTK53T8Q/p1661808976682059?thread_ts=1661807702.326749&cid=C01GTK53T8Q

**Comment by aldo-expensify** [comment] 2022-09-01 14:34
Changed to `Internal` for now as Marc suggested

**Comment by mananjadhav** [comment] 2022-09-03 23:42
Now that it is `Internal`, I've unassigned myself from the issue

**Comment by aldo-expensify** [comment] 2022-09-11 17:10
I'm going to return this to the pool to give it more visibility because I'm going on vacation.

**Comment by aldo-expensify** [comment] 2022-09-11 17:11
I won't look for another CME as this is `internal` for now.

**Comment by mallenexpensify** [comment] 2022-09-12 23:34
Droppin' a HOLD on this til https://github.com/Expensify/Expensify/issues/227410 hits production. Assigned to myself to keep 👀 on

**Comment by mvtglobally** [comment] 2022-09-13 04:34
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2022-09-15 00:14
@kbecciv @mvtglobally can you try to reproduce? I think this is fixed with https://github.com/Expensify/Expensify/issues/227410

If it's not reproducible, please close.

**Comment by mvtglobally** [comment] 2022-09-15 00:23
@mallenexpensify We will check and confirm in the morning

**Comment by mvtglobally** [comment] 2022-09-16 03:00
@mallenexpensify Issue is not repro 

https://user-images.githubusercontent.com/43995119/190547408-d7121cc8-f9a7-4032-a03c-8d3767c3d7aa.mp4

**Comment by mallenexpensify** [comment] 2022-09-16 19:00
Sweet, thanks @mvtglobally , closing

**Closed by mallenexpensify** 2022-09-16 19:00 UTC
Labels: Exported, Engineering, Weekly, Improvement, Internal
