### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500]  Chat - Focus on edit even when reaction emoji picker is opened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30119] opened 2023-10-21 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697815510057299

## Action Performed:
1. Open the app
2. Open any report
3. Send few messages
4. React on one message
5. Edit another message
6. Click on Emoji in edit
7. While emoji picker is open, click on Add reaction besides reacted message on step 4
8. Observe that even though reaction emoji picker is open, app displays focus on edit message

## Expected Result:
 App should focus on emoji picker search when any emoji picker is opened

## Actual Result:
App displays focus on edit message even when reaction emoji picker is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/b440f76c-b8db-40ba-8d5f-b156ff532b03

https://github.com/Expensify/App/assets/93399543/1dd5657e-0658-4cce-b224-f66b6d148897

https://github.com/Expensify/App/assets/93399543/9a4e7625-313c-4bf9-bac4-df7f0f20c475

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/db523cd1-7665-4360-a472-367862dd8133

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e9799a4fab4eacb</li>
        <li>Upwork Job ID: 1715738367180136448</li>
        <li>Last Price Increase: 2023-10-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by ahmedGaber93** [comment] 2023-10-21 14:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Open emojiPicker while another emojiPicker is open the edit composer is focus rather than emojiPicker search input
### What is the root cause of that problem?
We have two conflicts behavior at the same time when react emojiPicker open while composer emojiPicker is visible.
1. when composer emojiPicker hide composer input will focus.
2. when react emojiPicker open emoji search input will focus.
Regardless who called first, focus two input at the same time is a bug.
### What changes do you think we should make in order to solve the problem?
we should stop focus composer emojiPicker if the react emojiPicker will show.
https://github.com/Expensify/App/blob/15aee9d588866754047fa946e470f79704411e4a/src/pages/home/report/ReportActionItemMessageEdit.js#L430-L433
```javascript
onModalHide={() => {
    InteractionManager.runAfterInteractions(() =>  {
        // check if any emojiPicker is open before focus the input
        if (!EmojiPickerAction.isEmojiPickerVisible()) {
            setIsFocused(true);
            focus(true);
        }
    })
}}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s-alves10** [comment] 2023-10-21 15:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Edit composer gets focused when open `EmojiPicker` using emoji bubble button while `EmojiPicker` is opened in edit composer

### What is the root cause of that problem?

When open `EmojiPicker` using emoji bubble button while `EmojiPicker` is opened in edit composer, `focus(true)` is called [onModalHide](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.js#L430-L433). And `EmojiPicker` is opened again and [focusEmojiSearchInput](https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/components/EmojiPicker/EmojiPicker.js#L84-L89) is called to set focus to the search input.

The problem is in `focus(true)`. `input.focus()` is called in `InteractionManager.runAfterInteractions` callback as you can see in `focusWithDelay`
https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/libs/focusWithDelay.ts#L16-L31

So the `focus()` function of edit composer is called after the `focus()` of search input in `EmojiPicker`

This is the root cause

### What changes do you think we should make in order to solve the problem?

This issue happens for the main composer as well. We need to fix both
There are 2 options:
1. Don't set focus on the composer when other emoji picker is opened
2. Call the focus() of search input in `InteractionManager.runAfterInteractions` callback

With the second solution, the search input would flicker because it gets blurred and gets focused again. So I prefer the first option.

In order to fix both issues, we can prevent focusing of composer if emoji picker is visible in `focusWithDelay`
Update the below code
https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/libs/focusWithDelay.ts#L17
to
```
            if (!textInput || EmojiPickerAction.isEmojiPickerVisible()) {
```

`focusWithDelay` function is used only for composer and this works as expected without any side effect

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/840b4a16-fc79-47da-a1fe-e1d935f2b1e3


</details>

### What alternative solutions did you explore? (Optional)

**Comment by iiredalert** [comment] 2023-10-22 13:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The emojipicker text field is not in focus when opening the emoji picker from the "Add Reaction" button after the emoji picker was already open from the compose's "Emoji" button.

### What is the root cause of that problem?

We are using the onModalHide callback to focus on the compoer's textinput.  In this case onModalHide is happening because we are clicking on another button.

### What changes do you think we should make in order to solve the problem?

We should only focus on the composer text input if the emoji picker dialog is closed by pressing the "Emoji" button.

Add a specific callback for that in  EmojiPickerButton.js: 

```
                onPress={() => {
                    if (!EmojiPickerAction.emojiPickerRef.current.isEmojiPickerVisible) {
                        EmojiPickerAction.showEmojiPicker(props.onModalHide, props.onEmojiSelected, emojiPopoverAnchor.current, undefined, () => {}, props.emojiPickerID);
                    } else {
                        EmojiPickerAction.emojiPickerRef.current.hideEmojiPicker();
                        props.onModalHideDueToPress();
                    }
                }}
```

Then use that call back to focus on the composer text input in ReportActionItemMessageEdit.js:

```
                            onModalHideDueToPress={() => {
                                setIsFocused(true);
                                focus(true);
                            }}
```


ReportActionCompose.js also has this problem if you click somewhere else on the screen (i.e. another textfield) it will force the focus on the ReportActionCompose's textfield



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by iiredalert** [comment] 2023-10-22 13:27
Contributor details
Your Expensify account email: iiredalert@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014796bffcf5c1a24f

**Comment by twisterdotcom** [comment] 2023-10-24 15:57
@cubuspl42 just waiting for your take on these proposals please

**Comment by cubuspl42** [comment] 2023-10-25 08:05
@s-alves10 I like the fact that you noticed that this affects both edit and main composer.

I'm wondering if the function `focusWithDelay` has a clear contract, and if we're not making its contract even less clear. Its comment docs states...

> Create a function that focuses a text input.

...while the implementation is aware of the composer (it refers to `ComposerFocusManager`). After our change, it will be also aware of the global emoji picker.

Do you have any thoughts on that? An open option is just updating the comment so it better reflects what this function does. Figuring it out will provoke us to investigate its usages and actual contract.

**Comment by s-alves10** [comment] 2023-10-25 08:11
@cubuspl42 

Yeah. We use this function only for the composer. I think we need to update the comment and function name accordingly

**Comment by ahmedGaber93** [comment] 2023-10-25 12:28
@cubuspl42 What do you think of my [proposal](https://github.com/Expensify/App/issues/30119#issuecomment-1773811387)? we can do the same for the main composer

**Comment by cubuspl42** [comment] 2023-10-26 09:31
@ahmedGaber93 Selecting a proposal based on the order of filing is a last resort. The first and most important property of a proposal should be its overall quality.

**Comment by cubuspl42** [comment] 2023-10-26 09:32
While all the proposals provided a solution that would potentially work, I prefer the proposal by @s-alves10 for the following reasons:
- the `focusWithDelay` function, with a potential change of the comment doc, seems like the right place for adding this logic, as it's already composer-aware
- a relatively clean structure of the proposal
- the fact that it was ensured that the solution works both on the main and the edit composer

C+ reviewed 🎀 👀 🎀

**Comment by s-alves10** [comment] 2023-10-27 08:50
@cubuspl42 
PR is ready for review https://github.com/Expensify/App/pull/30483

**Comment by cubuspl42** [comment] 2023-11-08 10:33
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/7580
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/7580/files#r1386407066
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Open ND and log in using any account.
    - Navigate to any chat.
    - Send message A.
    - Send message B.
    - React to message A with any emoji.
    - Switch message B to edit mode.
    - Open EmojiPicker by tapping the emoji button in the message B edit composer.
    - Open the EmojiPicker again by tapping the emoji bubble button in message A.
    - Verify that the focus is on EmojiPicker.
    - Open EmojiPicker by tapping the emoji button in the main composer.
    - Reopen EmojiPicker by tapping the emoji bubble button in message A.
    - Confirm that the focus remains on EmojiPicker.

**Comment by twisterdotcom** [comment] 2023-11-09 23:07
Payment summary:

- [[$500] Chat - Focus on edit even when reaction emoji picker is opened #30119 - Expensify](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/27601856) - Waiting for Jakub to approve
- [[$500] Chat - Focus on edit even when reaction emoji picker is opened #30119 - Expensify](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/27601840) - Waiting for Sangar to approve
- [[$50] Chat - Focus on edit even when... #30119 - Bug Reporter (Old process)](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/27601828) - Waiting for Dhanashree to approve

**Comment by dhanashree-sawant** [comment] 2023-11-12 05:25
Thanks @twisterdotcom, I have accepted the offer.

**Comment by twisterdotcom** [comment] 2023-11-13 13:07
All paid.

**Closed by twisterdotcom** 2023-11-13 13:07 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
