### ISSUE TITLE
[$1000] IOS -  New line marker does not disappear when returning back to the chat. But disappears when going to another chat and return back.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20975] opened 2023-06-17 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Go to previous chats with reply
3. Mark the reply as unread
4. Go back to the main page
5. Return to the chat
6. Notice the new line marker is not dismissed
7. Go back to the main page
8. Go to other chats
9. Now Return to the first chat and notice that the new line marker is dismissed

## Expected Result:
The new line marker should be dismissed when going back to the chat

## Actual Result:
The new line marker is not dismissed when going back to the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/61e65710-22d7-4e58-8022-0ae4139a7117

https://github.com/Expensify/App/assets/93399543/d61f40b1-a965-49d6-9114-60b9862fbb71

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686417755398269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017161cf6b9259967e</li>
        <li>Upwork Job ID: 1670916446014144512</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-06-19 22:07
Reviewing

**Comment by qispark** [comment] 2023-06-20 06:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Items in the chat do not have their unread status cleared, despite being viewed.

### What is the root cause of that problem?

We use a state variable called `newMarkerReportActionID` to determine the position of the new marker. However, this is only updated in a few instances (such as in the component lifecycle methods), however, is not updated when the item is viewed.

### What changes do you think we should make in order to solve the problem?
We should be using the flatlist prop method of `onViewableItemsChanged` to run some logic, and determine if the item is visible. If so, we can immediately update the state.

Codeblock added to ReportActionsView:335:

```javascript
    onViewableItemsChanged(tokens) {
      const ids = _.map(tokens.viewableItems, item => item.item.reportActionID)

      if (ids.indexOf(this.state.reportActionId > -1)) {
        this.setState({newMarkerReportActionID: ''});
      }
    }

``` 

Of course we must also ensure that the onViewableItemsChanged prop is added to ReportActionsList.js, and that it is referenced inside ReportActionsView.js.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by greg-schroeder** [comment] 2023-06-20 19:22
Next up is C+ review of proposal(s)

**Comment by qispark** [comment] 2023-06-21 05:28
Hi @rushatgabhane, it will be called on the initial render/layout of the page, then afterwards whenever the viewable items have changed.
Therefore, it will also be called when leaving the report and returning to it. I have tested this.

BTW, I've just updated the proposal with an additional optimisation, so it won't call additional logic if there is no newMarkerReportActionID set.

```
      if (this.state.newMarkerReportActionID === '') {
        return;
      }
```

**Comment by qispark** [comment] 2023-06-21 05:57
@rushatgabhane The tricky thing is that:
- The constructor defines the initial state of `newMarkerReportActionID`
- The component lifecycle methods actually define some listeners, which then update the `newMarkerReportActionID` upon a response to particular events

I believe this creates a race condition, where a component is initially rendered with the New line, only to be updated during particular events (via openReportIfNecessary). We could perhaps add a new subscription in the lifecycle events, but see below for an edge case:

One other avenue I tried exploring is to reset the variable `newMarkerReportActionID` in the function `openReportIfNecessary()`. The only problem here is if the particular message isn't viewed (say if the unread message is further up in the chat), then we shouldn't trigger clearing of `newMarkerReportActionID`.

There is one issue with my proposal that I found, where marking a message as unread would immediately make it read upon scrolling the view. I will update my proposal and add a state variable to prevent the message being marked as read while the report is still open.

**Comment by qispark** [comment] 2023-06-21 06:48
@rushatgabhane For your consideration later. I've added a state variable which ensures `newMarkerReportActionID` is only updated once, which means if a message is marked as Unread, it cannot be marked as read until a user goes back into the same report.

**Comment by greg-schroeder** [comment] 2023-06-26 18:22
This issue is on hold for #20451

**Comment by greg-schroeder** [comment] 2023-06-28 20:26
This held

**Comment by greg-schroeder** [comment] 2023-07-08 00:43
Still on hold

**Comment by rushatgabhane** [comment] 2023-07-13 05:18
This can be removed from hold. We went with a different implemenation in #20451

**Comment by rushatgabhane** [comment] 2023-07-13 05:20
We need more proposals tho. @qispark's [proposal](https://github.com/Expensify/App/issues/20975#issuecomment-1598191336) isn't fixing the root cause

**Comment by qispark** [comment] 2023-07-14 23:49
@rushatgabhane Let me explain my perspective and see if you agree with the below points:
- When a new item is viewed on the screen, its status should be updated
- By opening the chat, it doesn't guarantee that the new item is viewed (if the new item is further up in the chat)
- By using the `onViewableItemsChanged`, it determines whether or not an item is viewed

Therefore, I think the most accurate way to resolve this issue is to update the status via `onViewableItemsChanged`.

The other option I see is to clear the status as soon as the chat is open - however, we do not guarantee that the user has viewed the new item. Hence why I think this is less accurate.

What are your thoughts on the above, and do you think there is yet another alternative not explored?

**Comment by greg-schroeder** [comment] 2023-07-18 09:48
Okay back to proposal review, removed from hold

**Comment by greg-schroeder** [comment] 2023-07-21 09:48
@rushatgabhane thoughts on @qispark's most recent comment?

**Comment by greg-schroeder** [comment] 2023-07-24 16:56
Bump @rushatgabhane

**Comment by greg-schroeder** [comment] 2023-07-25 15:17
Got it!

**Comment by qispark** [comment] 2023-07-25 21:33
@rushatgabhane I'm keen to update my proposal to fit, however I wanted to get your thoughts on my earlier comment to see if I missed anything. What are your thoughts?

**Comment by greg-schroeder** [comment] 2023-07-28 09:22
bump on the above

**Comment by greg-schroeder** [comment] 2023-07-31 13:05
@rushatgabhane thoughts on the above proposal from @WikusKriek or the updated one from @qispark?

**Comment by greg-schroeder** [comment] 2023-08-02 10:35
Friendly bump

**Comment by rushatgabhane** [comment] 2023-08-02 16:43
Not gonna lie, there are so many `useEffects` in [ReportActionsView](https://github.com/Expensify/App/blob/24ed1bebf19539d27878ed419f7cc10ae942531f/src/pages/home/report/ReportActionsView.js#L212) and they're hard to read.

**Comment by rushatgabhane** [comment] 2023-08-02 16:45
I like @WikusKriek's [proposal](https://github.com/Expensify/App/issues/20975#issuecomment-1656280646).
C+ reviewed 🎀 👀 🎀

**Comment by qispark** [comment] 2023-08-04 10:07
@WikusKriek I agree with you. I have been trying to explain that it should only be dismissed after the particular message has been viewed, rather than just simply opening the report.

**Comment by rushatgabhane** [comment] 2023-08-07 06:18
being discussed here - https://expensify.slack.com/archives/C01GTK53T8Q/p1691388353720289?thread_ts=1691388353.720289&cid=C01GTK53T8Q

**Comment by cead22** [comment] 2023-08-08 17:23
Closing as agreed on slack discussion

**Closed by cead22** 2023-08-08 17:23 UTC
Labels: External, Daily, Help Wanted, Bug
