### ISSUE TITLE
[HOLD for payment 2023-09-15] [$1000] Adding any invalid text/string as contact method through URL

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24521] opened 2023-08-14 01:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to the following link and write anything you want in "HERE"
 https://staging.new.expensify.com/settings/profile/contact-methods/HERE/details
 For example:
2. https://staging.new.expensify.com/settings/profile/contact-methods/Yooooo/details
3. Notice it shows a magic code validation tab
4. Click on resend code quickly to stay in the incorrect validation page and bypass error page.
5. If you don't click an error page will be thrown later

## Expected Result: 
It should immediately says PageNotFound and not preview Contact Validation with Magic Code sent

## Actual Result: 
It shows validation page with magic code and you can stay in it if you click on resend code
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/9e96f047-2760-4949-be1b-2ea7910222a5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MAkiour
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691207772114549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d8b6c25b7efa6cc</li>
        <li>Upwork Job ID: 1691192278548029440</li>
        <li>Last Price Increase: 2023-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>makiour | Contributor | 26292086</li>
<li>MAkiour | Reporter | 26292087</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-08-14 20:57
Reproduced. I kind of wonder whether we should be including the specific contact method as part of the URL at all? It doesn't seem realistic that an actual user would ever need to deep link to this specific page. 

And if we removed deep linking to a specific contact method, that would largely obviate this issue.

**Comment by Thanos30** [comment] 2023-08-15 01:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hardcoding contact method details URL with a non existent contact method shows magic code verification for a brief amount of time before showing not found page.

### What is the root cause of that problem?
The root cause of this problem is on `ContactMethodDetailsPage.js` file, lines 212-215:
```
const loginData = this.props.loginList[contactMethod];
        if (!contactMethod || !loginData || !loginData.partnerUserID) {
            return <NotFoundPage />;
        }
```
An existent contact method object will have a bunch of properties when created, one of them being  `partnerUserID` which I will use for the solution of the problem. A non existent contact method object will only have the `validateCodeSent` property set to false, getting it from our `resetContactMethodValidateCodeSentState` method.

On the above code section, we are only checking if the `loginData` object exists, and it does, with the `validateCodeSent` property I mentioned above.

This of course is not the correct check to do to determine if the contact method is found, which leads to showing the Magic Code validation page later on the code, which we show when that condition is true:
`!loginData.validatedDate && !isFailedAddContactMethod`, and of course, since `loginData` only has the `validateCodeSent` it becomes true.

### What changes do you think we should make in order to solve the problem?
On lines 212-215 , we should add a check for `partnerUserID` in the condition:
```
if (!contactMethod || !loginData || !loginData.partnerUserID) {
            return <NotFoundPage />;
        }
```

https://github.com/Expensify/App/assets/32620770/2e538c28-3cc0-4c34-bad4-84b431ce2f21

**Comment by joekaufmanexpensify** [comment] 2023-08-15 20:31
Proposals pending review.

**Comment by joekaufmanexpensify** [comment] 2023-08-17 22:02
Proposals still pending review

**Comment by kaushiktd** [comment] 2023-08-18 13:02
### Please re-state the problem that we are trying to solve in this issue.
Adding any invalid text/string as a contact method through URL. It goes to the magic code validation tab but it should immediately says PageNotFound and not preview Contact Validation
with Magic Code sent

### What is the root cause of that problem?
When we go through the URL using an invalid string, initially it will be rendered the component and check for validation on below file:
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L245-L259

```
{!loginData.validatedDate && !isFailedAddContactMethod && (
<View style={[styles.ph5, styles.mt3, styles.mb7]}>
<DotIndicatorMessage
type="success"
style={[styles.mb3]}
messages={{0: ['contacts.enterMagicCode', {contactMethod: formattedContactMethod}]}}
/>
<ValidateCodeForm
contactMethod={contactMethod}
hasMagicCodeBeenSent={hasMagicCodeBeenSent}
loginList={this.props.loginList}
ref={this.validateCodeFormRef}
/>
</View>
)}
```

### What changes do you think we should make in order to solve the problem?
To solve this issue you need to wrap up the complete component in below mentioned condition on
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js 

```
<>
{!loginData.validatedDate ? (
<NotFoundPage />
) : (
<ScreenWrapper onEntryTransitionEnd={() => this.validateCodeFormRef.current && this.validateCodeFormRef.current.focus()}>
<!-- all content from page inside screen wrapper -->
</ScreenWrapper>
)}
</>
```

Video
https://drive.google.com/file/d/1EJ5oEk_3MTHlBjNxWxrru3-ozDweRemo/view?usp=sharing

**Comment by joekaufmanexpensify** [comment] 2023-08-18 18:00
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1692381635539559)

**Comment by eVoloshchak** [comment] 2023-08-18 21:29
> I kind of wonder whether we should be including the specific contact method as part of the URL at all? It doesn't seem realistic that an actual user would ever need to deep link to this specific page.
And if we removed deep linking to a specific contact method, that would largely obviate this issue.

@joekaufmanexpensify, there are legitimate use cases in theory. For example, if you want to open the current page (in this case details for a contact method) in a different browser (we do it all the time when testing PRs). Of course, this is an edge case (there are no other pages like this as far as I know) and even if we remove the deep linking, it will only add one extra click in this specific scenario, but I think we might want to fix this, even the rare cases are possible

**Comment by eVoloshchak** [comment] 2023-08-18 21:58
@makiour, wow, thank you for such a thorough explanation!
I think we should proceed with option 1.1 of @makiour's [proposal](https://github.com/Expensify/App/issues/24521#issuecomment-1676549762), which is changing
https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L110-L112
to 
```js
componentDidMount() {
    const contactMethod = this.getContactMethod();
    const loginData = this.props.loginList[contactMethod];
    if (loginData) {
        User.resetContactMethodValidateCodeSentState(contactMethod);
    }
}
```
I think we should also set `NotFoundPage` to say "Back to contact methods" instead of "Back to home" (and change the actual navigation action). If we navigate back from contact details, we should end up on the contacts page, not just dismiss the modal 

🎀👀🎀 C+ reviewed!

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:57
Pending internal engineering sign off

**Comment by joekaufmanexpensify** [comment] 2023-08-22 13:11
@AndrewGable mind taking a look at [this proposal](https://github.com/Expensify/App/issues/24521#issuecomment-1684474309) when you have a sec? TY!

**Comment by joekaufmanexpensify** [comment] 2023-08-23 19:43
Bumped Andrew 1:1

**Comment by joekaufmanexpensify** [comment] 2023-09-11 13:39
@eVoloshchak mind completing the BZ checklist so we can prep to issue payment?

**Comment by joekaufmanexpensify** [comment] 2023-09-11 15:06
Thanks for bumping! I'll review, and we'll definitely take any internal delays into account when calculating whether a bonus is warranted.

**Comment by joekaufmanexpensify** [comment] 2023-09-14 13:20
[Bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1694697617257759) BZ checklist in Slack so we can prep to issue payment soon.

**Comment by eVoloshchak** [comment] 2023-09-14 15:40
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23601
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23601/files#r1326128384
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, we already have a checklist item to cover failure scenarios: `I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)`
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
It's kind of an edge case since it requires a user to manually edit a URL with an invalid contact method, but the same can happen in case there are issues with the back end, so I think we need a regression test

**Comment by eVoloshchak** [comment] 2023-09-14 15:51
**Regression Test Proposal**

1. Go to Settings > Profile > Contact Methods
2. Verify there is at least one contact method
3. Open the following link: https://staging.new.expensify.com/settings/profile/contact-methods/invalidContactMethodName/details
4. Verify that you're presented with 'Hmm... it's not here' page
5. Press on 'Go back to contact methods'
6. Select a contact method, verify you're navigated to an according contact method page

**Do we agree 👍 or 👎**

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:22
Great, ty! I'll finish up the checklist so we can issue payment asap.

**Comment by joekaufmanexpensify** [comment] 2023-09-18 02:32
Checklist is all set!

**Comment by joekaufmanexpensify** [comment] 2023-09-18 02:35
We discussed this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694699103713639?thread_ts=1694698119.666629&cid=C01SKUP7QR0) and confirmed this qualifies for a speed bonus. This means we need to issue the following payments: 

- @makiour - $1,750 ($1,000 for PR, $500 speed bonus, $250 reporting bonus). Paid via upwork. 
- @eVoloshchak - $1,500 ($1,000 for C+ and $500 speed bonus). Paid via NewDot.

**Comment by joekaufmanexpensify** [comment] 2023-09-18 02:36
@eVoloshchak could you please request $1,500 via NewDot and confirm here once complete?

**Comment by joekaufmanexpensify** [comment] 2023-09-18 02:40
@makiour I sent your $1,750 in two payments, since you had two roles for this one.

**Comment by eVoloshchak** [comment] 2023-09-18 15:28
@joekaufmanexpensify, requested the payment!

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:00
Awesome, ty! @eVoloshchak closing this out for now. If your request hasn't been paid in 7 days LMK, and I'll look into it on my end.

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:01
Payment summary message is [here.](https://github.com/Expensify/App/issues/24521#issuecomment-1722678926)

**Closed by joekaufmanexpensify** 2023-09-19 03:01 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-21 10:05
$1,500 payment for @eVoloshchak approved based on BZ summary.
