### ISSUE TITLE
Web -  Incorrect Tooltip Displayed When Hovering Over Avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26337] opened 2023-08-30 20:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to settings and select "Workspace." If no workspace exists, create one.
2. Click on the plus sign and choose "Request Money."
3. Enter the desired amount and select the created workspace.
4. Go to the header and hover over the two avatars.
5. Observe that the wrong tooltip is displayed and does not show the email associated with the avatar.

## Expected Result:
When hovering over the avatar, the correct tooltip should be displayed showing the email associated with the avatar.

## Actual Result:
The wrong tooltip is displayed when hovering over the avatar after requesting money in a workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/664dd260-3872-4306-a2c8-a5294cdda772

https://github.com/Expensify/App/assets/93399543/5134b1e5-e4dc-4747-8cc9-ce022c639a18

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692870954388439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by im-adithya** [comment] 2023-08-30 22:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip doesn't appear in `SubscriptAvatar` component 

### What is the root cause of that problem?
The styles should be applied to the `View` component (like in [MultipleAvatars](https://github.com/Expensify/App/blob/main/src/components/MultipleAvatars.js#L254)) but instead, they are applied to the `Avatar` directly

### What changes do you think we should make in order to solve the problem?
We apply the styles `[isSmall ? styles.secondAvatarSubscriptCompact : subscriptStyle]` to the View [here](https://github.com/Expensify/App/blob/main/src/components/SubscriptAvatar.js#L70)

### What alternative solutions did you explore? (Optional)
--

### Working demo/screenshot
<img width="335" alt="Screenshot 2023-08-31 at 3 40 18 AM" src="https://github.com/Expensify/App/assets/64399555/6a776c74-9168-41db-a2c6-1c47dde84084">

**Comment by im-adithya** [comment] 2023-08-30 22:14
Contributor details
Your Expensify account email: imadithyavardhan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01546f32a755cacd96

**Comment by im-adithya** [comment] 2023-08-30 22:15
@johncschuster, can this please be labelled as external?

**Comment by im-adithya** [comment] 2023-09-01 06:20
Solved with #26329, can be closed!

**Comment by johncschuster** [comment] 2023-09-05 19:38
Sweet! Thanks for the heads up, @im-adithya! Closing!

**Closed by johncschuster** 2023-09-05 19:38 UTC
Labels: Daily, Overdue, Bug
