### ISSUE TITLE
[$250] Web – Emoji Picker – One emoji is with a square in "Animals & Nature" category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48210] opened 2024-08-28 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4898690
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any chat
4. Open the emoji picker
5. Scroll down the list to the "Animals & Nature" category

## Expected Result:
All emojis are without square

## Actual Result:
One emoji is with a square

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/39405948-07f9-473c-b58e-88b861e082b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114e4624a2c986c2b</li>
        <li>Upwork Job ID: 1830177152023910708</li>
        <li>Last Price Increase: 2024-09-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment] 2024-08-28 19:57
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isogit123** [comment] 2024-08-29 01:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
One of the emojis is with a black square.

### What is the root cause of that problem?
The blackbird emoji consists of a bird and a black square that are combined to form the blackbird. In Windows, the browser uses `"Expensify Neue", "Windows Segoe UI Emoji", "Noto Color Emoji"` font family for the blackbird emoji, and the `Windows Segoe UI Emoji` font doesn't support the blackbird emoji so it is displayed incorrectly.
The font is included in the `font.css` file as shown below:
https://github.com/Expensify/App/blob/2fd5bbe6f4e553b11ec3550daca9d12767dcd9b7/assets/css/fonts.css#L57-L61
The video below shows that removing `Windows Segoe UI Emoji` from the `font-family` CSS property of the Blackbird using dev tools fixes the issue:

https://github.com/user-attachments/assets/30abb3af-6ef0-400b-a58c-a8ebe2696a78



### What changes do you think we should make in order to solve the problem?
We need to avoid using the `Windows Segoe UI Emoji` font for the emojis. We can do that by not using a font family for the emojis by passing a `null` or empty string value to the `family` prop in the `Text` component in
https://github.com/Expensify/App/blob/2fd5bbe6f4e553b11ec3550daca9d12767dcd9b7/src/components/EmojiPicker/EmojiPickerMenuItem/index.tsx#L79
and handling it in the `Text` component.
Below is a screenshot after applying the solution:
![image](https://github.com/user-attachments/assets/2b9960f5-3108-47f6-a4a4-d079eb5d1cb4)

### What alternative solutions did you explore? (Optional)
I tried replacing the  `Windows Segoe UI Emoji` font with the one in my Windows machine and it fixed the issue.

**Comment by isogit123** [comment] 2024-08-29 01:24
<a href='#issuecomment-2316534585'>Proposal updated</a>
Improved the proposal's clarity.

**Comment by raza-ak** [comment] 2024-09-03 08:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Emoji Picker – One emoji is with a square in "Animals & Nature" category
### What is the root cause of that problem?
The problem stems from a corrupted or incorrect emoji code in the assets/emojis .ts files, which is causing the emoji to render improperly.
### What changes do you think we should make in order to solve the problem?

To resolve this issue, we should update the emoji code in the common.ts, en.ts, and es.ts files. This will involve correcting the defective emoji code, ensuring that the black square is removed. Once these changes are made, restarting the app will refresh the emoji list and display the updated, correct emojis.
Following changes will fix the issue.
<img width="453" alt="image" src="https://github.com/user-attachments/assets/8f04bb2a-3924-4cba-9bc1-0fb9e849e9a3">
<img width="532" alt="image" src="https://github.com/user-attachments/assets/2b827bd3-01ea-4fac-8ca3-d51ac86f523d">
<img width="416" alt="image" src="https://github.com/user-attachments/assets/7a8e103a-f681-40a4-a3a1-574f9c076bd2">

https://github.com/user-attachments/assets/908338e4-3e87-4def-b0ef-2ac270e601b0

**Comment by muttmuure** [comment] 2024-09-10 17:27
Closing

**Closed by muttmuure** 2024-09-10 17:26 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
