### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Cannot select a word in native iOS composer if composed message have an emoji

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44495] opened 2024-06-26 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1719405668302249

## Action Performed:
1. Launch the app
2. Initiate a DM with any user
3. Compose a message with emoji
4. Try selecting a word by long press or double tab
## Expected Result:
Able to select word by long press or by double tapping
## Actual Result:
Unable to select by long press or by double tapping
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari

https://github.com/Expensify/App/assets/38435837/05f9d34d-e019-45a6-bde3-e89d0c3e5db3

https://github.com/Expensify/App/assets/38435837/e4f0067b-b30c-4928-9784-b2ccc8a75760

- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a59336e899fcaa47</li>
        <li>Upwork Job ID: 1806116311980257786</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>QichenZhu | Contributor | 102976322</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by mountiny** [comment] 2024-06-27 21:58
cc @BartoszGrajdek @tomekzaw

**Comment by BartoszGrajdek** [comment] 2024-06-28 11:22
Let's add this to the Live Markdown project @mountiny

**Comment by sandipanghos** [comment] 2024-06-28 15:36
@mountiny is this still open for proposal? I am working on it

**Comment by QichenZhu** [comment] 2024-06-28 15:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cannot select a word in the native iOS composer if the message contains an emoji.

### What is the root cause of that problem?
Originally, React Native had an [issue](https://github.com/facebook/react-native/issues/21243) with `TextInput` when using emojis.

> All emoji characters are automatically given an AppleColorEmoji NSFont attribute and the original font is moved to NSOriginalFont attribute.
>
> This causes an issue when we call isEqualToAttributedString when we set the attributedText, since it will always be false if an emoji is present.

React Native fixed this by ignoring all attributes in such cases.

https://github.com/facebook/react-native/blob/9269429bb955d47088793a2e32454fddb712152b/packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.mm#L130-L167

<img width="519" alt="Screenshot 2024-06-29 at 3 13 09 AM" src="https://github.com/Expensify/App/assets/57348009/0f1f4f73-afba-4987-9a68-4a0c36875b75">


However, this fix caused Expensify/react-native-live-markdown#293 and #41390, and was reverted by Expensify/react-native-live-markdown#318.

### What changes do you think we should make in order to solve the problem?
Making clones of `newText` and `oldText` and removing the `NSOriginalFont` and `NSFont` attributes from them before calling `isEqualToAttributedString`.

https://github.com/Expensify/react-native-live-markdown/blob/1153e0d8e5aeed980ba47146b7f980dad3172a63/ios/RCTTextInputComponentView%2BMarkdown.mm#L50-L58

<img width="733" alt="Screenshot 2024-06-29 at 3 20 41 AM" src="https://github.com/Expensify/App/assets/57348009/da3431d8-842f-402e-8d55-bb0d777fc6b8">

### What alternative solutions did you explore? (Optional)
N/A

**Comment by lschurr** [comment] 2024-07-02 20:01
@mountiny is this open for proposals? Should @mollfpr be reviewing?

**Comment by QichenZhu** [comment] 2024-07-03 11:38
## Proposal
@tomekzaw Sure, here's the [updated proposal](https://github.com/Expensify/App/issues/44495#issuecomment-2197194378). Thanks!

**Comment by tomekzaw** [comment] 2024-07-03 11:42
Thanks, sounds good to me. Can we proceed with the PR so we can test out the changes?

**Comment by mollfpr** [comment] 2024-07-03 11:49
I don't have much experience with objective-c, but I believe @tomekzaw reviewed.

Probably @QichenZhu can provide a video of the result before the assignment?

**Comment by QichenZhu** [comment] 2024-07-03 12:07
@mollfpr

Before:

https://github.com/Expensify/App/assets/57348009/64c3a205-2541-4c64-a87e-f2202a4990ca

After:


https://github.com/Expensify/App/assets/57348009/b0900df6-a29c-48d4-a822-2ce1a74e9d9a

**Comment by mollfpr** [comment] 2024-07-03 12:11
Thanks, @QichenZhu. It looks good to me!

Let's move forward with @QichenZhu [proposal](https://github.com/Expensify/App/issues/44495#issuecomment-2197194378) then!

🎀 👀 🎀 C+ reviewed!

**Comment by QichenZhu** [comment] 2024-07-04 03:30
@tomekzaw @mollfpr The [PR](https://github.com/Expensify/react-native-live-markdown/pull/416) is ready for review.

**Comment by tomekzaw** [comment] 2024-07-08 19:52
I will review the PR tomorrow.

**Comment by lschurr** [comment] 2024-07-10 19:18
Any update @tomekzaw?

**Comment by tomekzaw** [comment] 2024-07-15 14:44
Reviewing the PR

**Comment by tomekzaw** [comment] 2024-07-17 07:51
[PR](https://github.com/Expensify/react-native-live-markdown/pull/416) has been reviewed and merged ✅

**Comment by QichenZhu** [comment] 2024-07-17 12:49
There is a PR #45556 to update `react-native-live-markdown` to `0.1.105`. Should we wait until it's merged and then bump the version to `0.1.107`?

**Comment by tomekzaw** [comment] 2024-07-18 07:57
@QichenZhu Let's ask @thienlnam

**Comment by thienlnam** [comment] 2024-07-18 12:20
Yeah. since that PR has already been reviewed let's wait to bump it until after that is merged. Then it can go through another series of tests since we've seen issue things pop up when jumping versions before

**Comment by lschurr** [comment] 2024-08-01 17:03
Payment summary:

- Contributor: @QichenZhu $250 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/37726723/overview))
- Reviewer: @mollfpr $250 (to be paid in NewDot)

**Closed by lschurr** 2024-08-01 17:03 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by mollfpr** [comment] 2024-08-05 19:41
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR!

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good!

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Launch the app
2. Initiate a DM with any user
3. Compose a message with an emoji
4. Try selecting a word by long-pressing or double-tapping
5. Verify that the word is selected
6. 👍 or 👎

**Comment by lschurr** [comment] 2024-08-05 20:53
Thanks @mollfpr - adding QA test request

**Comment by JmillsExpensify** [comment] 2024-08-05 20:55
$250 approved for @mollfpr
