### ISSUE TITLE
[$250] Expense - Unapprove system message changes format after unapproving a scanning expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50305] opened 2024-10-06 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Add approvals feature is enabled in Workflows.

1. Go to staging.new.expensify.com
2. Go to workspace chat (must have no unsettled expense).
3. Submit a scan expense.
4. While the receipt is scanning, go to expense report.
5. Click Approve.
6. Click on the report header.
7. Click Unapprove while the receipt is still scanning.
8. Note that the unapprove system message is "unapproved x".
9. Refresh the page.

## Expected Result:
The unapprove system message should remain "unapproved x".

## Actual Result:
The unapprove system message changes to
You
unapproved this report

This issue only happens when the expense is a scan expense and the receipt is scanning.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6626203_1728226188696!Screenshot_2024-10-06_at_22 49 31" src="https://github.com/user-attachments/assets/0862cf78-45b4-4867-9c15-90f7c43bd773">

https://github.com/user-attachments/assets/7aad5489-a754-43c2-a8e6-c2254e24d09f

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843641880485944632</li>
        <li>Upwork Job ID: 1843641880485944632</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by IuliiaHerets** [comment] 2024-10-06 17:22
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-10-06 17:23
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment] 2024-10-07 02:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The unapprove system message changes to
You
unapproved this report

### What is the root cause of that problem?
- We don't have logic to handle UNAPPROVED system message.
### What changes do you think we should make in order to solve the problem?
1. Add a UNAPPROVED else if in [this](https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/home/report/ReportActionItem.tsx#L690):

```
 } else if (ReportActionsUtils.isActionOfType(action, CONST.REPORT.ACTIONS.TYPE.UNAPPROVED)) {
            const amount = ReportActionsUtils.getOriginalMessage(action)?.amount;
            const currency = ReportActionsUtils.getOriginalMessage(action)?.currency;
            children = <ReportActionItemBasicMessage message={`Unapproved ${CurrencyUtils.convertToDisplayString(amount, currency)}`} />;

```


2. The same logic should be applied when displaying message in LHN, copy message, report title, ...
### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-10-14 07:10
This issue is fixed in [this PR](https://github.com/Expensify/App/pull/49831). 
Let's close this @bfitzexpensify 

https://github.com/user-attachments/assets/12825e4e-dd68-4b59-9c67-815e1b241794

**Closed** 2024-10-15 10:35 UTC
Labels: External, Daily, Help Wanted, Bug
