### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Distance - Blue dot does not set to current location after enabling location access

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43113] opened 2024-06-05 12:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-6
**Reproducible in staging?:** y
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4597262
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
precondition: location access is disabled
1. Open the app and log in
2. Tap the FAB > Submit expense >Distance
3. Select do not allow on the pop-up and wait for the map to load
4. Tap the start point and select Use current location
5. Allow location access

## Expected Result:
The blue dot is displayed as user's current location and replaces the start point on the map

## Actual Result:
The blue dot is still displayed over San Francisco while the start point is set to the current location

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/a7b50510-d9e8-424f-a8c9-08bc989e9e0b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194e3d6c394ce03d6</li>
        <li>Upwork Job ID: 1798364343763573802</li>
        <li>Last Price Increase: 2024-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 102783101</li>
<li>ZhenjaHorbach | Contributor | 102783102</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by m-natarajan** [comment] 2024-06-05 12:06
@dangrous FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-05 12:06
We think that this bug might be related to #wave-collect - Release 1

**Comment by dangrous** [comment] 2024-06-05 14:37
Oh wait lol there is an obvious PR - https://github.com/Expensify/App/pull/40759 - let me review.

**Comment by nkdengineer** [comment] 2024-06-05 15:05
- IMO, I don't think this bug is related to [PR](https://github.com/Expensify/App/pull/40759) because as we can see in the OP, the blue dot (current location) and the 1st waypoint are very far apart, so that is why the blue dot cannot replace the start point on the map. 

I am still investigating the RCA ...

**Comment by neil-marcellini** [comment] 2024-06-05 17:20
@dangrous thanks for adding the external label. In the future please also remove the DeployBlocker label when doing so, to signal that we don't need to block the Web deploy.

**Comment by dangrous** [comment] 2024-06-05 20:38
@parasharrajat doesn't it sort of have to be? To say another way - did #40759 introduce the blue dot in the first place? From the issue description it seems like the blue dot did not exist previously, and so if 40759 created it it MUST be where we can fix the code, right?

Let me know if I am misunderstanding anything

**Comment by nkdengineer** [comment] 2024-06-05 22:06
@dangrous 

### RCA:

- It looks like we only called the function ```setCurrentPositionToInitialState``` one time:
https://github.com/Expensify/App/blob/952d844d1a72d88c445c3c517a44ac21cf8a669a/src/components/MapView/MapView.website.tsx#L93

- So that leads to in the OP steps, after step 5, it does not update the current location, so it still displays the San Francisco as the current location.

#### Solution:
- We can create a hook, named ```usePermissionLocation```, that will return the location permission state in ```true | false```.
- Then in [here](https://github.com/Expensify/App/blob/952d844d1a72d88c445c3c517a44ac21cf8a669a/src/components/MapView/MapView.website.tsx#L65):
```
        const permission = usePermissionLocation();
        const prevPermission = usePrevious(permission);
        useEffect(() => {    
            if (!!permission !== !!prevPermission) {
                shouldInitializeCurrentPosition.current = true;
            }
        }, [permission, prevPermission]); 


```

- Then we can remove ```error?.code !== GeolocationErrorCode.PERMISSION_DENIED``` from this [condition](https://github.com/Expensify/App/blob/952d844d1a72d88c445c3c517a44ac21cf8a669a/src/components/MapView/MapView.website.tsx#L74)

**Comment by nkdengineer** [comment] 2024-06-05 22:12
I just updated this [comment](https://github.com/Expensify/App/issues/43113#issuecomment-2151037566)

**Comment by roryabraham** [comment] 2024-06-06 01:16
@nkdengineer this bug occurs on iOS/Android, but your last proposal targets web-specific code

**Comment by nkdengineer** [comment] 2024-06-06 01:37
@roryabraham While investigating the issue, I was able to reproduce it on the web. Therefore, I focused on debugging it in the web environment for easier troubleshooting.

**Comment by roryabraham** [comment] 2024-06-06 04:27
> We can create a hook, named usePermissionLocation, that will return the location permission state in true | false.

I like the idea, but it's not clear to me how exactly we'd trigger a re-render when location permissions change.

**Comment by roryabraham** [comment] 2024-06-06 04:29
When trying to dig into this, I wrote a `useCurrentPosition` hook that I think nicely DRYs up the MapView across native and web: https://github.com/Expensify/App/pull/43160

**Comment by nkdengineer** [comment] 2024-06-06 04:34
> how exactly we'd trigger a re-render when location permissions change.

Sorry, could you please provide more details about your concern? I'm not fully understanding what you mean.

**Comment by nkdengineer** [comment] 2024-06-06 05:01
> how exactly we'd trigger a re-render when location permissions change.

- Ah, got it. In ```usePermissionLocation```, we will create an state:
```
    const [permissionState, setPermissionState] = useState(null)

```
- Then add an event listener when the permission changed.
- Below is the example code in web:

```
import { useState, useEffect } from 'react';

const useLocationPermission = () => {
    const [permissionState, setPermissionState] = useState(null);

    useEffect(() => {
        let permissionStatus;

        const checkPermission = async () => {
            try {
                permissionStatus = await navigator.permissions.query({ name: 'geolocation' });

                // Update state with the initial permission status
                setPermissionState(permissionStatus.state === 'granted');

                // Set up the event listener for permission changes
                permissionStatus.onchange = () => {
                    setPermissionState(permissionStatus.state === 'granted');
                };
            } catch (error) {
                console.error('Error checking location permission:', error);
            }
        };

        checkPermission();

        // Cleanup function
        return () => {
            if (permissionStatus) {
                permissionStatus.onchange = null;
            }
        };
    }, []);

    return permissionState;
};

export default useLocationPermission;

```

**Comment by Julesssss** [comment] 2024-06-06 10:56
I'm removing the blocker label as this is an edge case and so we can speed up QA. More context [here](https://expensify.slack.com/archives/C07J32337/p1717671190816029?thread_ts=1717648387.742439&cid=C07J32337) (internal comment)

**Comment by dangrous** [comment] 2024-06-06 16:21
is there a performance hit from just removing `shouldInitializeCurrentPosition` entirely, and just always doing it in case? Seems like that fixes the issue.

https://github.com/Expensify/App/blob/95591d9328e94023d63974ef40165a8cfd811311/src/components/MapView/MapView.website.tsx#L88-L92

**Comment by nkdengineer** [comment] 2024-06-08 01:31
@dangrous It looks like we cannot remove shouldInitializeCurrentPosition as it leads to the getUseLocation function calls many times. Once it calls, the ask permission location will pop up.

**Comment by dangrous** [comment] 2024-06-11 17:40
@nkdengineer what's the `getUseLocation`? I'm not seeing it in the App. I played around with a simulator and it seems like it still only asks the one time?

**Comment by nkdengineer** [comment] 2024-06-11 18:26
@dangrous 

> what's the getUseLocation? I'm not seeing it in the App

- Ah, sorry, my bad. I mean ```getCurrentPosition``` here:
https://github.com/Expensify/App/blob/1d7ed051629b9f0dd593e8337578689bb65e14fb/src/components/MapView/MapView.website.tsx#L100

> I played around with a simulator and it seems like it still only asks the one time?

- Here is the PR where we make sure it only asks permission once https://github.com/Expensify/App/pull/33157

**Comment by sakluger** [comment] 2024-06-12 16:01
Hey @fedirjh, could you also please review the proposal that's being discussed?

**Comment by dangrous** [comment] 2024-06-12 16:06
@nkdengineer so if we have code to ensure it only asks permission once, is there a problem with running `getCurrentPosition` many times? (Also, testing on web I only noticed one additional call, which shouldn't really cause much of an issue). @fedirjh let us know what you think too!

**Comment by dangrous** [comment] 2024-06-13 17:58
Oh I like that idea!

**Comment by dangrous** [comment] 2024-06-18 17:20
Yeah, that would be great - I haven't been in this situation before, though - should we grab another C+ to review your proposal (and then the PR) officially?

**Comment by sakluger** [comment] 2024-06-18 17:24
Yeah let's get another C+ volunteer and assign them manually. I'll post in Slack!

**Comment by sakluger** [comment] 2024-06-18 17:31
The automation thinks that @ZhenjaHorbach is the Contributor and @fedirjh is the C+, and there's no easy way to change it, so we'll just remember that it's the other way around.

**Comment by dangrous** [comment] 2024-07-03 10:05
just noting for my own purposes since it's been a while - the PR is merged and on staging, hasn't yet gone to prod.

**Comment by sakluger** [comment] 2024-07-10 18:33
@fedirjh I withdrew the Upwork offer since you can now request payment via NewDot. I'll post the payment summary below.

**Comment by sakluger** [comment] 2024-07-10 18:33
Summarizing payment on this issue:

Contributor: @fedirjh $250, please request on Newdot
Contributor+: @ZhenjaHorbach $250, paid via Upwork

**Closed by sakluger** 2024-07-10 18:33 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-11 00:12
$250 approved for @fedirjh
