### ISSUE TITLE
[$500] Distance - App crashes when creating request and opening Ereceipt offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36853] opened 2024-02-20 10:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR:** https://github.com/Expensify/App/pull/36147

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go offline.
3. Go to workspace chat.
4. Create a distance request.
6. Navigate to request details page.
7. Tap on the receipt.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5b8b97a2-684b-41b8-9998-440801e2fbbe

[Bug6385296_1708401671302!QA.txt](https://github.com/Expensify/App/files/14342638/Bug6385296_1708401671302.QA.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01708fc8b78a286518</li>
        <li>Upwork Job ID: 1759880711547600896</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-20 10:02
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by situchan** [comment] 2024-02-20 10:38
Crash log from QA:

<img width="798" alt="Screenshot 2024-02-20 at 4 37 21 PM" src="https://github.com/Expensify/App/assets/108292595/d096b820-8cd5-476f-98c5-09468cb18789">

**Comment by situchan** [comment] 2024-02-20 10:39
I am not able to reproduce on main.
@izarutskaya can you please confirm if this is still reproducible on v1.4.43-2?

**Comment by Timmotal** [comment] 2024-02-20 10:52
Hello Expensify.
I am Hammed Olatunde, A Full-Stack Developer and Mobile Developer.
I can quickly fix this TypeError Bug, assign it to me here and on Upwork
I will resolve the error message ASAP
 you can contact me via email timmortaltech@gmail.com

**Comment by Timmotal** [comment] 2024-02-20 10:57
Contributor details
Your Expensify account email: [timmortaltech@gmail.com](mailto:timmortaltech@gmail.com)
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~01c75914a4cfbb6470)

**Comment by Timmotal** [comment] 2024-02-20 10:59
Contributor details
Your Expensify account email: timmortaltech@gmail.com](mailto:timmortaltech@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c75914a4cfbb6470

**Comment by Timmotal** [comment] 2024-02-20 11:05
Contributor details
Your Expensify account email: [timmortaltech@gmail.com](mailto:timmortaltech@gmail.com)
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~01c75914a4cfbb6470)

**Comment by Timmotal** [comment] 2024-02-20 11:10
Contributor details
Your Expensify account email: <timmortaltech@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01c75914a4cfbb6470>

For some reason, I am unable to get my details verified by the Melvin_bot

**Comment by Julesssss** [comment] 2024-02-20 11:20
@Timmotal you're missing an UpWork profile link: 

> Missing/invalid email or upwork profile link.

Also, we'd need a proposal.

**Comment by Julesssss** [comment] 2024-02-20 11:20
This issue doesn't seem reproducible, at least not for me on Android which is shown in the original video capture:

![Screenshot_20240220_111933](https://github.com/Expensify/App/assets/10736861/3a22ce88-d049-4e35-9269-68c0fa4b08f2)

**Closed** 2024-02-20 11:22 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by Timmotal** [comment] 2024-02-20 11:34
Hello [Julesssss](https://github.com/Julesssss)

I did send my upwork link but for some reason it is getting omitted.
I see you have closed the issue, will that be all or do you still need help with other issues?

Regards,
Timmortal.

**Comment by Julesssss** [comment] 2024-02-20 11:42
Ah, in all of your [comments ](https://github.com/Expensify/App/issues/36853#issuecomment-1953976487)I see it missing 😕 MMaybe there is an extra space or formatting that removes it? 

> I see you have closed the issue, will that be all or do you still need help with other issues?

Yeah this must have been fixed elsewhere, but we have [hundreds](https://github.com/Expensify/App/labels/External) of other paid tasks for you to work on. Please just read through our [contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) documentation first.

Issues labeled with deployBlocker might be taken over by internal employees, but anmy other issue without an assigned contributor is open for proposals 👍

**Comment by Timmotal** [comment] 2024-02-20 12:26
Ok thank you [Julesssss](https://github.com/Julesssss)
I am reading the documentation now.

The way I added my Upwork link is by, putting it in-between the greater and less than symbols <my upwork profile link>
I also tried adding the link directly without the symbols, Nonetheless, I got the same error message from theMelvin_bot
![image](https://github.com/Expensify/App/assets/43627445/09451f9f-f9f7-4289-af7d-87ded82b6aa2)
