### ISSUE TITLE
[HOLD on #17870] Android - Chat - Black screen is displayed after split bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19325] opened 2023-05-19 22:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login with HT account
2. Click on the green plus button (FAB) > select Request Money
3. Select a couple of attendees from the list
4. Tap/click the Next confirmation button
5. Add a comment, then select the Split Bill confirmation button

## Expected Result:
Verify that the modal closes and that you land in the Group DM with exactly the same set of users you just split the bill with. Data about split bill is visible.

## Actual Result:
Land to black screen without data.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/e83a2f50a547ee3b67308b29e67bcd8cc26e00048b0ef3e02a939845a70fb33e

https://platform.applause.com/services/links/v1/external/effd5b2af3dad6ea2e1d20c93c5bc794d211817d1e3d6f6c284963a5cbbe14bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by therealsujitk** [comment] 2023-05-21 18:49
This could be a duplicate of #17870

**Comment by twisterdotcom** [comment] 2023-05-22 13:07
Sorry, I don't have my Android device with me at the moment, but I'll be back from travel by Weds morning.

@kbecciv - What is a HT Account?

Having said that, this does very much seem like it's the same as https://github.com/Expensify/App/issues/17870, so I'm going to HOLD it on that. cc @alex-mechler

**Comment by alex-mechler** [comment] 2023-05-22 16:20
> What is a HT Account?

High Traffic

> Having said that, this does very much seem like it's the same as https://github.com/Expensify/App/issues/17870, so I'm going to HOLD it on that.

It likely has the same underlying root cause. I would be surprised if it did not

**Comment by twisterdotcom** [comment] 2023-05-25 21:28
This has a HOLD, so making it Weekly.

**Comment by twisterdotcom** [comment] 2023-06-05 16:02
Still held on https://github.com/Expensify/App/issues/17870. Going to put back to Monthly as this is still being investigated: https://github.com/Expensify/App/issues/17870#issuecomment-1572561467

**Comment by twisterdotcom** [comment] 2023-07-07 16:58
Still held.

**Comment by twisterdotcom** [comment] 2023-08-08 08:47
Still Held.

**Comment by twisterdotcom** [comment] 2023-08-18 10:42
Held.

**Comment by twisterdotcom** [comment] 2023-10-02 13:34
Looks like https://github.com/Expensify/App/issues/17870 is resolved without any action. I'm going to close this one too.

**Closed by twisterdotcom** 2023-10-02 13:34 UTC
Labels: Monthly, Overdue, Bug
