### ISSUE TITLE
Expense - Expense preview displays "fragment.text" when the expense is invalid

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50553] opened 2024-10-10 10:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with Expensifail account.
3. Submit an expense to any user.
4. Send a message to the same user.
5. Open another report and send a message.
6. Go to Account settings > Troubleshoot > Clear cache and restart.
7. Select Reset and refresh.
8. Submit another expense to the user in Step 3 via FAB (do not open the chat with that user).

## Expected Result:
Expense preview will still display the sender & receiver name when the expense is invalid.

## Actual Result:
Expense preview displays "fragment.text" when the expense is invalid.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6630207_1728522633705!Screenshot_2024-10-10_at_09 07 04" src="https://github.com/user-attachments/assets/1ad75b49-0061-41fd-acf1-7f0de8dc5152">

https://github.com/user-attachments/assets/34b504be-b43a-4fd5-84c5-927d89217d09

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lakchote** [comment] 2024-10-10 11:05
It's directly related to https://github.com/Expensify/App/pull/50341

cc @grgia @puneetlath @eh2077 

https://github.com/user-attachments/assets/38f6715a-99cc-43ae-83fb-a04f7777956d

**Comment by bernhardoj** [comment] 2024-10-10 11:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report preview display name text shows fragment.text when the report is invalid.

### What is the root cause of that problem?
I don't know why the report becomes invalid when requesting a new expense after Clear cache and restart, but I want to focus on the specific issue we have, that is the fragment.text shows.

In ReportActionItemFragment, if the type is empty, then we show `fragment.text`.
https://github.com/Expensify/App/blob/ab5175c3d48061cd8fb422bab448a4a61caf018b/src/pages/home/report/ReportActionItemFragment.tsx#L191-L192

When the report becomes invalid, the report preview action has an undefined `person`.
<img width="420" alt="Screenshot 2024-10-10 at 19 00 40" src="https://github.com/user-attachments/assets/a15d0174-c2d4-4048-924b-073bdf3a2f70">

This causes the array here to contain undefined as the item. `[undefined]`
https://github.com/Expensify/App/blob/ab5175c3d48061cd8fb422bab448a4a61caf018b/src/pages/home/report/ReportActionItemSingle.tsx#L166-L174

Then, we map the array here and pass the fragment type with empty string as the fallback. Because the array item is undefined, the type is also undefined, so empty string is passed.
https://github.com/Expensify/App/blob/ab5175c3d48061cd8fb422bab448a4a61caf018b/src/pages/home/report/ReportActionItemSingle.tsx#L287-L293

### What changes do you think we should make in order to solve the problem?

I believe what we want to do here is that, if the person is undefined, then return an empty array. To do that, we need to update the code to
```
const person = action?.person?.at(0);
const baseArray = displayName
    ? [
            {
                type: 'TEXT',
                text: displayName,
            },
        ]
    : person ? [person] : [];

OR

const baseArray = displayName
    ? [
            {
                type: 'TEXT',
                text: displayName,
            },
        ]
    : [action?.person?.at(0)].filter(Boolean);
```

OR

Instead of fallback to empty string, fallback it to TEXT.
https://github.com/Expensify/App/blob/ab5175c3d48061cd8fb422bab448a4a61caf018b/src/pages/home/report/ReportActionItemSingle.tsx#L293

or just do both.

This will show an empty text.
<img width="451" alt="Screenshot 2024-10-10 at 19 09 15" src="https://github.com/user-attachments/assets/a367643d-954f-4142-9ca9-aa7bafd1e403">

**Comment by lakchote** [comment] 2024-10-10 11:21
Thanks @bernhardoj for your proposal.

However, I'll be asking for a revert since I don't have the whole context here and it's tied to another blocker (https://github.com/Expensify/App/issues/50547).

**Comment by mountiny** [comment] 2024-10-10 12:22
Revert PR was merged https://github.com/Expensify/App/pull/50557

**Comment by grgia** [comment] 2024-10-14 05:18
👀

**Comment by grgia** [comment] 2024-10-14 05:43
Closing out since we reverted the PR and I've addressed in a follow up (and this bug technically doesn't exist anymore)

**Closed by grgia** 2024-10-14 05:43 UTC
Labels: Engineering, Daily, Bug
