### ISSUE TITLE
[$250] Accounting - Xero syncing stuck on Checking Xero connection & it shown connected after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46989] opened 2024-08-07 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/46480
## Action Performed:
1. Open the app and log in
2. Open the workspace settings
3. Tap More features and enable Accounting
4. Navigate to Accounting and select Xero integration
5. Enter Xero credentials
6. Wait for Xero to complete syncing

## Expected Result:
Xero is connected and the message "Last synced <> minutes ago" is displayed

## Actual Result:
Xero syncing is stuck on "Checking Xero connection", and the integration is only shown as connected after re-login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/13699d8d-0a9b-4579-b15e-2d4bec2a4717

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140eb31cd35ebadc8</li>
        <li>Upwork Job ID: 1825754480856760461</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by lanitochka17** [comment] 2024-08-07 17:35
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-08-09 05:30
No problem for me on web:

![image](https://github.com/user-attachments/assets/9051464b-e1b0-47b6-b5ff-0baca57b3100)

Mobile is borked, so I will have to attempt again on Monday.

**Comment by RachCHopkins** [comment] 2024-08-20 04:38
Sorry, last week was a total write-off. Just picked this up again. It's definitely sitting on "syncing customers" for a long time. 
![IMG_3898](https://github.com/user-attachments/assets/12fafce5-847f-4524-85e8-e2684379a83c)

manager.rach+BZ@expensicorp.com is my testing account.  Workspace ID 8CEDF0D4BB7FC051.

When I go into OldDot suppotal, it's ready to configure:

![image](https://github.com/user-attachments/assets/61c08516-d3c4-4f8e-92aa-70af74fcbab8)

Logs definitely indicate that the "job finished"

![image](https://github.com/user-attachments/assets/14c0984e-d0f2-4360-81f4-8ffc04330bed)

And my app still says syncing customers. Something is not updating the app end.

**Comment by trjExpensify** [comment] 2024-08-30 00:41
CC: @hungvu193 @arosiclair I wonder if this is related to the recent sync woes with Xero.

**Comment by hungvu193** [comment] 2024-08-30 00:47
I don't think so but let me take a look

**Comment by hungvu193** [comment] 2024-08-30 09:34
Is this issue account-specific? I don't think I can reproduce it. (Please ignore the error at the end, we had a PR to fix it already).

https://github.com/user-attachments/assets/cca03f0d-665a-477f-8311-c3a9a3d97477

**Comment by trjExpensify** [comment] 2024-08-30 11:00
Maybe, or we fixed it! @RachCHopkins can you retest on your account?

**Comment by arosiclair** [comment] 2024-08-30 16:59
> CC: @hungvu193 @arosiclair I wonder if this is related to the recent sync woes with Xero.

Don't think so either. Seems to be more-so an issue with some connection sync progress updates not being received. Or possibly the app just isn't re-rendering with those updates.

**Comment by trjExpensify** [comment] 2024-09-02 23:00
> > CC: @hungvu193 @arosiclair I wonder if this is related to the recent sync woes with Xero.
> 
> Don't think so either. Seems to be more-so an issue with some connection sync progress updates not being received. Or possibly the app just isn't re-rendering with those updates.

Alright cool, well maybe let's start with a repro on this account of Rach's and see if we can go from there if it's reliably reproducible using that account.

**Comment by rojiphil** [comment] 2024-09-03 16:43
> Alright cool, well maybe let's start with a repro on this account of Rach's and see if we can go from there if it's reliably reproducible using that account.

Yeah. I too can't reproduce this. Here is a test video demonstrating this. Maybe we can close this out. 

https://github.com/user-attachments/assets/3fd16be3-05b5-4955-aabd-0d6dfed0176d

**Comment by RachCHopkins** [comment] 2024-09-09 03:29
Completely different experience this time. Lightening fast, no waiting for anything. I think we can close this out!

**Closed by RachCHopkins** 2024-09-09 03:29 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
