### ISSUE TITLE
[$250] BUG: No RBR occurs when invalid credentials used to connect to Sage Intacct

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#45938] opened 2024-07-22 19:24 UTC
Testing doc: [here](https://docs.google.com/document/d/1AdHIz229Ze3BovRRR5YLW7nx8I2slf7greYkpV0SifI/edit?usp=sharing) (request, will share)

Pre-testing steps

- Make sure the email address does not already have existing workspaces/policies
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)
- Create a new collect policy on OldDot and; 
- Set the approval mode to “submit and approve”
- Enable scheduled submit with a frequency of `Daily` or “slower”
- Invite an additional user to the policy to play the member role in these testing flows
- Run the script stated [here](https://stackoverflowteams.com/c/expensify/questions/17518) to enable workspace chat creation for a paid plan.

Pre-testing steps

- Make sure that your test account is on the intacctOnNewExpensify beta
- Make sure you have Sage Intacct web services user ID, password and Company ID to initiate a connection
- Make sure you create a new workspace/policy for each test run
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)

Steps:
1. Head to Workspace settings
2. Head to Accounting
3. Under Sage Intacct Connection click `Connect`
4. Enter incorrect validation tokens

Expected result: A RBR is shown on Accounting in LHN and on the Connections card in Accounting. 
Actual result: No RBR is present, and the #admins page shows that the connection occurred 

Screenshot LHN:
<img width="1512" alt="Screenshot 2024-07-22 at 8 31 20 PM" src="https://github.com/user-attachments/assets/43c3ffef-3741-4b5a-8943-9e6366fd035f">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f23c70a65cf3f85e</li>
        <li>Upwork Job ID: 1815806620903385053</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103316519</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @NikkiWines</details>

**Comment by kabeer95** [comment] 2024-07-23 23:33
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
 When invalid credentials are used to connect to Sage Intacct, no Retry, Backup, and Retry (RBR) mechanism is triggered, resulting in an "invalid credentials" or "authentication failure" error.

## What is the root cause of that problem? 
The root cause of this problem is likely due to an incorrect implementation of the Sage Intacct API or a misconfiguration of the connection settings, which prevents the RBR mechanism from kicking in when invalid credentials are used.

## What changes do you think we should make in order to solve the problem? 
To solve this problem, we need to review and adjust the Sage Intacct API implementation to ensure that it correctly handles invalid credentials and triggers the RBR mechanism. Specifically, we should:

Verify Sage Intacct credentials and connection settings.
Set API endpoint and headers correctly.
Set XML payload to retrieve subsidiary information.
Send request to Sage Intacct API and check if response is invalid credentials error.
If invalid credentials error, trigger RBR mechanism.
Here is an example code snippet to illustrate the solution:
```
// Verify Sage Intacct credentials and connection settings
const sageIntacctCredentials = {
  userId: 'your_user_id',
  password: 'your_password',
  companyId: 'your_company_id'
};

// Set API endpoint and headers
const endpoint = 'https://api.intacct.com/ia/xml/xmlgw.aspx';
const headers = {
  'Content-Type': 'application/xml',
  'Authorization': `Basic ${sageIntacctCredentials.userId}:${sageIntacctCredentials.password}`
};

// Set XML payload to retrieve subsidiary information
const payload = `
<?xml version="1.0" encoding="UTF-8"?>
<request>
  <control>
    <senderid>${sageIntacctCredentials.companyId}</senderid>
    <password>${sageIntacctCredentials.password}</password>
    <controlid>string</controlid>
    <uniqueid>false</uniqueid>
    <dtdversion>3.0</dtdversion>
  </control>
  <operation>
    <authentication>${sageIntacctCredentials.companyId}</authentication>
    <get>
      <object>subsidiary</object>
    </get>
  </operation>
</request>
`;

// Send request to Sage Intacct API
const response = await fetch(endpoint, {
  method: 'POST',
  headers,
  body: payload
});

// Check if response is invalid credentials error
if (response.status === 401) {
  // Trigger RBR mechanism
  console.log('Invalid credentials, triggering RBR...');
  // Implement RBR logic here
} else {
  console.log('Error:', response.statusText);
}

**Comment by situchan** [comment] 2024-07-24 06:39
@kabeer95 Can you please familiarize yourself with our codebase and some old proposals on closed issues to understand what is expected in a proposal?

**Comment by situchan** [comment] 2024-07-25 05:06
Waiting for proposals

**Comment by jayeshmangwani** [comment] 2024-07-25 20:34
@dylanexpensify @stephanieelliott [Script link](https://github.com/Expensify/App/issues/45938#:~:text=Run%20the%20script%20stated%20here%20to%20enable%20workspace%20chat%20creation%20for%20a%20paid%20plan.) is of internal SO and is not accessible to everyone. Is there any way to add(or access script) the for adding/testing the test Sage Intacct?

**Comment by SzymczakJ** [comment] 2024-07-29 10:20
I was implementing this so you can assign me.
This is probably caused by the way we handle incorrect credentials on Sage Intacct. @NikkiWines should have more context.
I guess our solution to incorrect credentials has some downsides 😅

**Comment by situchan** [comment] 2024-07-29 20:24
@stephanieelliott please assign @SzymczakJ from SWM

**Comment by NikkiWines** [comment] 2024-08-01 09:28
This one's a backend bug so i'll try and patch it when I've got some spare cycles - adjusting the labels accordingly

**Comment by situchan** [comment] 2024-08-13 06:08
Not overdue

**Comment by NikkiWines** [comment] 2024-08-15 19:22
Sorry guys, been swamped with competing priorities these last few weeks, will try to prioritize this as soon as i have time

**Comment by NikkiWines** [comment] 2024-08-23 14:48
🤔 Seems to be a RBR for me when I enter invalid creds locally, but I do see the `connected to Sage Intacct` message still. I'll update it so we don't send that message if the connection fails 

https://github.com/user-attachments/assets/374aab41-69c6-4676-b8c0-a13068ca8122

**Comment by NikkiWines** [comment] 2024-08-23 16:14
Not overdue

**Comment by stephanieelliott** [comment] 2024-09-11 02:56
Seems like both linked PRs are on prod now -- @NikkiWines are we ok to close this, or is there more to do?

**Comment by NikkiWines** [comment] 2024-09-11 18:13
Thanks for the bump @stephanieelliott  -vI just re-tested the flow and I see a RBR and I don't see the double notification, so this one should be all good.

**Closed** 2024-09-11 19:21 UTC
Labels: Reviewing, Weekly, Internal, Bug
