### ISSUE TITLE
[$1000] mWeb - The color of bottom side is  different when entering for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21192] opened 2023-06-21 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to Settings > Workspace

## Expected Result:
The color of bottom side is not different when entering for the first time

## Actual Result:
The color of bottom side is  different when entering for the first time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![photo_2023-06-14 12 36 10 (1)](https://github.com/Expensify/App/assets/93399543/4fab5f89-648b-4d8c-b4e6-42478fa9a119)

![photo_2023-06-14 12 36 08 (1)](https://github.com/Expensify/App/assets/93399543/05040165-9806-4c01-8370-c72cbb5646d7)

https://github.com/Expensify/App/assets/93399543/0c06c9d0-de9e-40bf-a20a-ce4e3f7532e0

https://github.com/Expensify/App/assets/93399543/b47aa47c-0e66-4961-bc35-3c9a04397136

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686727996859449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0a65c77a9c778a1</li>
        <li>Upwork Job ID: 1672350582085713920</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-06-21 19:49
> when entering for the first time

@narzullome Entering what specifically? The website?

**Comment by narzullome** [comment] 2023-06-22 00:14
@NicMendonca Entering workspace

**Comment by narzullome** [comment] 2023-06-22 00:21
1 Open app
2 Go to Settings > Workspace
3 Notice that the color of bottom side is different 
Then if u enter to Settings and exit with the "<" button
The all color will be the same (that's why I wrote entering for the first time )
If you exit from Workspace and then re enter - Notice that  the color of bottom side is again  different

**Comment by NicMendonca** [comment] 2023-06-23 00:28
@narzullome I can't reproduce. I *only* ever see the grey bottom bar: 

https://github.com/Expensify/App/assets/24947345/74c21848-2b16-4f05-922f-6e25d3203804

**Comment by narzullome** [comment] 2023-06-23 04:25
@NicMendonca sorry , after entering to workspace click to say workspace then u will see the different color on bottom side

**Comment by NicMendonca** [comment] 2023-06-23 19:37
@narzullome Still can't reproduce 😅 I only ever see the grey bottom. cc @shawnborton for design input

https://github.com/Expensify/App/assets/24947345/e3557505-f084-4760-9ea9-f1784e82b535

**Comment by NicMendonca** [comment] 2023-06-23 19:39
@puneetlath I am going OOO until Wednesday. Can you watch this while I am away? I'll unassign you when I am back. As mentioned, I still [can't reproduce this](https://github.com/Expensify/App/issues/21192#issuecomment-1604790443) but I agree that if we can get rid of the native iOS grey bottom banner, that would be great. But I only ever get the grey banner.

Thank you!

**Comment by puneetlath** [comment] 2023-06-23 21:06
I'm able to reproduce it. 
![IMG_B2A6EAEBC22D-1](https://github.com/Expensify/App/assets/1371996/aba5a201-8f6c-41d4-a50d-bee3cccd9346)

**Comment by seniordev0425** [comment] 2023-06-24 02:58
I can't reproduce on both simulator and device. Is this probably device or expensify account specific issue?

**Comment by narzullome** [comment] 2023-06-24 06:00
> I can't reproduce on both simulator and device. Is this probably device or expensify account specific issue?
No  its not  specific expensify issue - 
 after entering to workspace did u  click to any workspace ?

**Comment by seniordev0425** [comment] 2023-06-24 09:34
Contributor details
Your Expensify account email: seniordev40425@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c15f4d925571c52c

Yes, @narzullome . After entering to workspaces I clicked one of my workspace. But it didn't happen on both simulator and device.

**Comment by narzullome** [comment] 2023-06-24 18:46
@seniordev0425  I don't know why u can't repro but its reproducible and there are peoples who was able to repro

**Comment by Piotrfj** [comment] 2023-06-26 13:08
I was also not able to reproduce it

**Comment by shawnborton** [comment] 2023-06-29 16:28
This isn't actually a bug. The bottom native iOS browser bar is just depending on the system theme - so in this case, the user is using light mode and thus the native browser bar is light. 

@narzullome there are virtually no details provided in the bug report. For next time, can you try to be more descriptive with exactly what the bug is and what you are expecting would be the correct case? "The color of bottom side is different when entering for the first time" feels too vague to be able to extrapolate what the bug could even be. 

Either say, I say we just close this one out.

**Comment by narzullome** [comment] 2023-06-30 14:35
@shawnborton Ok understandable next time I will be more descriptive 
When opening workspace from mWeb safari as its visible on the screenshot the color of bottom side is different 
Is it considered not as a bug ?

**Comment by shawnborton** [comment] 2023-06-30 14:51
I’m still not quite understanding. Can you outline more clear steps?

**Comment by narzullome** [comment] 2023-06-30 15:02
1 Go to Settings > Workspace
2 Enter to any workspace 
Notice that the color of bottom side is different (
![](https://user-images.githubusercontent.com/93399543/247536576-4fab5f89-648b-4d8c-b4e6-42478fa9a119.jpeg)
)

**Comment by NicMendonca** [comment] 2023-06-30 20:35
There isn't any change in the safari native iOS browser bar. And as @shawnborton mentioned would be theme specific. Going to close this.

https://github.com/Expensify/App/assets/24947345/6bfcdad1-70cc-40ec-acc5-8b0bd844b6f8

**Closed by NicMendonca** 2023-06-30 20:35 UTC
Labels: External, Daily, Help Wanted, Bug
