### ISSUE TITLE
[HOLD backend change][$250] whisper message stuck in unread loop

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40063] opened 2024-04-11 02:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712748859641039

## Action Performed:
1. Head to a new room
2. Verify the system  whisper is at the bottom
3. Verify `New messages` icon at top for the whisper message
4. Click New messages
## Expected Result:
Taken to the new message and `New message` icon disappears and no green line is shown
## Actual Result:
Not going to the bottom of the page and the new message icon flashes, then stays w/green line still showing you have unread messages
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f01f08e5-37d6-4e78-a375-33e1097d4eae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5d5668f182f7627</li>
        <li>Upwork Job ID: 1781373405194547200</li>
        <li>Last Price Increase: 2024-05-17</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2024-04-19 17:24
Putting into VSB and moving to external, since this is affecting new chat room invites.

**Comment by kevinksullivan** [comment] 2024-04-30 22:30
Waiting on proposals

**Comment by kevinksullivan** [comment] 2024-05-09 21:20
Same, waiting on proposals

**Comment by MrMuzyk** [comment] 2024-05-15 10:00
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment] 2024-05-16 10:45
After investigating it seems to me that the issue is on the BE side. On the screenshot below we can see that response returned from BE has `lastVisibleActionCreated` that has date of last message visible to everyone in this chat rather than to current user. 

<img width="1920" alt="undread loop" src="https://github.com/Expensify/App/assets/23487612/7aabb896-5609-4c1d-afbd-9f55cb883003">

This date is then compared with `sortedVisibleReportActions[0]` creation date. `sortedVisibleReportActions` is an array that stores all actions minus the filtered one that are not meant to be displayed (unsupported, markedAsReimbursed, pending for deletions etc.)

https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/pages/home/report/ReportActionsList.tsx#L214

That flag is later used in a handler that is being fired upon clicking on `New messages` banner. Because dates are different, `hasNewestReportAction` is false and handler enters first `if` condition which causes the loop.

https://github.com/Expensify/App/blob/4499fa244a209bfe709b803864b23e6eae65f56c/src/pages/home/report/ReportActionsList.tsx#L406-L415


To fix that BE should return correct `lastVisibleActionCreated` date - it should be equal to creation date of last message visible to current user rather than date of last message visible to everyone in the chat.

**Comment by getusha** [comment] 2024-05-19 13:32
🎀 👀 🎀 pulling internal engineer as this seems something to be fixed from the BE https://github.com/Expensify/App/issues/40063#issuecomment-2114872278

**Comment by techievivek** [comment] 2024-05-21 14:28
This issue should be resolved with the backend change I am already working on, which addresses the whisper message behavior in newDot. We will return the correct lastVisibleActionCreated value for the whisper action to whispered users.

**Comment by techievivek** [comment] 2024-05-27 07:26
Adding HOLD in the title until we have the backend PR merged.

**Comment by techievivek** [comment] 2024-06-05 16:16
No update, Xerocon is taking all the priorities.

**Comment by kevinksullivan** [comment] 2024-06-07 20:45
Not overdue, just not a top priority right now.

**Comment by kevinksullivan** [comment] 2024-06-13 18:55
Assuming no update @techievivek ?

**Comment by techievivek** [comment] 2024-06-25 06:12
Yeah, no update needed for now. This doesn't seem very critical to me, so I can look into it once the higher priority tasks on my plate have been taken care.

**Comment by techievivek** [comment] 2024-07-05 16:20
No updates, I will resume working on the backend PR next week.

**Comment by techievivek** [comment] 2024-07-15 14:32
Not overdue, resuming work on the backend PR.

**Comment by techievivek** [comment] 2024-07-24 06:06
PR is in progress https://github.com/Expensify/Auth/pull/11753, https://github.com/Expensify/Web-Expensify/pull/42861 but still doing some testing.

**Comment by kevinksullivan** [comment] 2024-08-01 23:49
@techievivek can you provide an update here? THanks

**Comment by techievivek** [comment] 2024-08-14 11:53
Sorry, no progress on above PRs since I had to shift my focus to milestone PRs, I will get back to this very soon.

**Comment by kevinksullivan** [comment] 2024-08-26 22:39
Assuming no update, but @techievivek can let me know if we've done anything here.

**Comment by techievivek** [comment] 2024-09-05 06:34
Prioritizing API refactors and optimizing auth command, I had the PR up but couldn't work on it any further.

**Comment by kevinksullivan** [comment] 2024-09-12 19:33
Looping in a BZ member to handle payment as I'm going OOO

**Comment by techievivek** [comment] 2024-09-16 08:42
Not overdue, handling it this week.

**Comment by greg-schroeder** [comment] 2024-09-17 00:52
Thanks @techievivek!

**Comment by greg-schroeder** [comment] 2024-09-19 01:07
Vivek is still on this one this week

**Comment by greg-schroeder** [comment] 2024-09-23 03:00
Any update on this one @techievivek? Should it still be `daily`?

**Comment by greg-schroeder** [comment] 2024-09-25 19:19
Bump @techievivek

**Comment by greg-schroeder** [comment] 2024-10-01 01:46
Per this discussion and the pausing of #vip-vsb, I think we can close this issue now. Please reopen if you disagree @techievivek:

https://expensify.slack.com/archives/C066HJM2CAZ/p1727455774700809

**Closed by greg-schroeder** 2024-10-01 01:46 UTC
Labels: Weekly, Internal, Bug
