### ISSUE TITLE
[$1000]  Profile - Entering country abbreviation UK returns only Ukraine

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24451] opened 2023-08-11 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Go to Settings > Profile > Personal details > Home address > Country
3. Clear the search field and enter "Uk"

## Expected Result:
Countries that contain "Uk" (Ukraine) or have this combination as an abbreviation (United Kingdom) are shown

## Actual Result:
Only Ukraine is displayed. It works as expected with other country abbreviations, e.g. US or VA (Vatican city)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/31751d15-4a57-4f82-8e6a-236d7ec6fa6f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc3fcd9971555f99</li>
        <li>Upwork Job ID: 1691070318439432192</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-08-14 14:36
Shouldn't be overdue

**Comment by Pluto0104** [comment] 2023-08-16 02:35
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The problem is that when entering the country abbreviation "UK" in the profile, it only returns "Ukraine" instead of "United Kingdom".

### What is the root cause of that problem?
The root cause of the issue is that the ISO code for United Kingdom is "GB" instead of "UK".
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/CONST.js#L1593
In our code, we are searching for "uk" in "gbunitedkingdom".
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/components/CountryPicker/CountrySelectorModal.js#L50

### What changes do you think we should make in order to solve the problem?
To solve this problem, we can make the following changes:
- In the `App/src/CONST.js` file, create constants for additional country codes and use it in the `CountrySelectorModal`. For example:
```
ALL_COUNTRY_CODES: {
  GB: ["UK", "GBR"]
},
```
- In the `App/src/components/CountryPicker/CountrySelectorModal.js` file, update the `searchValue` to include the additional country codes:
```
searchValue: StringUtils.sanitizeString(`${(CONST.ALL_COUNTRY_CODES[countryISO] || []).join('')}${countryISO}${countryName}`),
```

This way, we can easily add unofficial but popular country codes like "UK" and maintain them easily.

#### Result
![Screenshot 2023-08-15 212140](https://github.com/Expensify/App/assets/136573674/4d723850-e260-484b-9741-587b2f0e733f)


### What alternative solutions did you explore? (Optional)
I explored two alternative solutions:

Option 1: We can use the initial characters of the country name in the search value. This can be implemented by modifying the code in the `CountrySelectorModal.js` file. However, this approach has some drawbacks, such as only using ISO country codes and initial characters, which can make maintenance and modification difficult.
```
 const countries = useMemo(
        () =>
            _.map(translate('allCountries'), (countryName, countryISO) => {
                const words = countryName.split(' ');
                const initialChars = _.map(words, word => _.first(word)).join('');
                
                return {
                    value: countryISO,
                    keyForList: countryISO,
                    text: countryName,
                    isSelected: currentCountry === countryISO,
                    searchValue: StringUtils.sanitizeString(`${initialChars}${countryISO}${countryName}`),
                };
            }),
        [translate, currentCountry],
    );
```
Option 2: We can modify the `ALL_COUNTRIES` constant in the `CONST.js` file to include unofficial country codes. For example, `'GB': 'United Kingdom'` would be `GB: ['United Kingdom', 'UK', 'U.K']`. This approach also requires modifying the existing constant and may not be as flexible for future use.
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/CONST.js#L1355-L1606

And then we can modify in CountrySelectorModal like this:
```
searchValue: StringUtils.sanitizeString(`${countryISO}${countryNames.join("")}`),
```

In my opinion, the proposed solution is more maintainable and clear. It allows us to easily add unofficial country codes while maintaining the existing code structure.

**Comment by Pluto0104** [comment] 2023-08-17 10:29
@mananjadhav could you please review my proposal?

**Comment by garrettmknight** [comment] 2023-08-17 10:37
@0xmiroslav can you give these proposals a look when you get a minute?

**Comment by Pluto0104** [comment] 2023-08-26 02:47
> Trying to find simple solution without changing tons of code

I'm trying to find a simple solution without changing tons of code. @0xmiroslav, perhaps this is the most straightforward approach:
```
searchValue: StringUtils.sanitizeString(`${countryISO === 'GB' ? 'UK' : ''}${countryISO}${countryName}`),
```
But I'm not sure about your preferences. I think [my primary suggested solution](https://github.com/Expensify/App/issues/24451#issuecomment-1679876646) is more scalable and consistent. Though, this alternative isn't too bad. If you have any thoughts or questions, please feel free to inform me.

**Comment by garrettmknight** [comment] 2023-08-28 16:54
@0xmiroslav how are @Nodebrute or @Pluto0104 's suggestions?

**Comment by garrettmknight** [comment] 2023-08-30 19:22
@0xmiroslav bump

**Comment by Pluto0104** [comment] 2023-09-04 16:09
@0xmiroslav, that's great! So, are you suggesting that we need to completely modify the entire data structure for `ALL_COUNTRIES`, correct? If that's the case, it seems like there are numerous country entries without keywords. What are your thoughts on this?

**Comment by Pluto0104** [comment] 2023-09-04 16:14
Yeah, I understand what you mean by `XX: {name: 'xxx'}`. In my opinion, it does seem a bit redundant. Using `XX: 'xxx'` would be simpler, don't you think?

**Comment by Pluto0104** [comment] 2023-09-04 16:23
I'm not sure if my solution is the best but I think it offers greater consistency and simplicity. Could you please review it? https://github.com/Expensify/App/issues/24451#issuecomment-1679876646

**Comment by Pluto0104** [comment] 2023-09-04 16:28
Of course, it's scalable. We can add additional keywords to the `ALL_COUNTRY_CODES` constant. For example:
{
  GB: ["UK", "GBR"],
  US: ["USA"]
},

**Comment by Pluto0104** [comment] 2023-09-04 16:54
Hey @Nodebrute, it's important to clarify that this behavior is intentional because we are omitting whitespaces. Both @allroundexperts's solution and your perspective are in line with this logic. Could you please clarify your concern or what specific behavior you'd like to see?

**Comment by Pluto0104** [comment] 2023-09-04 17:00
@0xmiroslav, do you think my first option lacks scalability? The second option doesn't have scalability, but I was referring to the first option.

**Comment by napster125** [comment] 2023-09-05 02:06
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The problem is that when entering the country abbreviation "UK" in the profile, it only returns "Ukraine" as a suggestion instead of the expected "United Kingdom".

### What is the root cause of that problem?
The root cause of this issue lies in the fact that the ISO code for the United Kingdom is "GB," not "UK" as initially expected.
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/CONST.js#L1593
This discrepancy is evident in our codebase, where we are searching for "uk" within "gbunitedkingdom."
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/components/CountryPicker/CountrySelectorModal.js#L50

### What changes do you think we should make in order to solve the problem?
To solve this problem, we can make the following changes:

- In the App/src/CONST.js file, we recommend modifying the data structure of `ALL_COUNTRIES` as follows:
```
ALL_COUNTRIES: {
  // ...
  GB: {name: "United Kingdom", keywords: ["UK"], dialingCode: 44, currencyCode: "GBP"}
  // ...
},
```
- In the `App/src/components/CountryPicker/CountrySelectorModal.js` file, update the `searchValue` to include the additional country codes:
```
searchValue: StringUtils.sanitizeString(`${(countryKeywords || []).join('')}${countryISO}${countryName}`),
```

This approach allows us to easily include unofficial but popular country codes like "UK" while maintaining flexibility. I believe this solution is highly scalable, as it also provides room for adding further data, such as `dialingCode` and `currencyCode` if needed, in the future.

#### Result
![Screenshot 2023-08-15 212140](https://github.com/Expensify/App/assets/136573674/4d723850-e260-484b-9741-587b2f0e733f)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pluto0104** [comment] 2023-09-05 19:40
Ah, @0xmiroslav did you mean [this](https://github.com/Expensify/App/issues/24451#issuecomment-1705845948)? If so, you're right. Such structure is more efficient than my solution. 👍

**Comment by Pluto0104** [comment] 2023-09-06 22:19
Ah, got it. @0xmiroslav do you prefer this structure?
```
{
  ...
  GB: {name: "United Kingdom", keywords: ["UK"], dialingCode: 44, currencyCode: "GBP"}
  ...
}
```
or
```
[
  ...
  {name: "United Kingdom", keywords: ["UK"], isoCode: "GB", dialingCode: 44, currencyCode: "GBP"}
  ...
]
```
Yes, I think the second structure is more maintainable and scalable. I've updated [my proposal](https://github.com/Expensify/App/issues/24451#issuecomment-1679876646). if you don't mind, could you please review again?

**Comment by Pluto0104** [comment] 2023-09-07 20:46
@0xmiroslav I'll go with former one.

**Comment by garrettmknight** [comment] 2023-09-11 09:04
@0xmiroslav can you give this one some attention?

**Comment by madmax330** [comment] 2023-09-11 16:59
As discussed in Slack, we won't be fixing this because it opens a can of worms to have ever abbreviation for every country.

**Closed by madmax330** 2023-09-11 16:59 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by garrettmknight** [comment] 2023-09-12 23:14
I think it's less about common and more about what's standard. For the United Kingdom, GB is the standard two-letter country code so rather than take on updating all common abbreviations (if others exist, I'm sure some do) we're going to use the standard list of assigned ones vs. colloquial ones. Ex. https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
