### ISSUE TITLE
[HOLD for payment 2024-01-24] [HOLD for payment 2024-01-22] iOS - App get crashed on iPad during Sign In flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34383] opened 2024-01-11 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be Sign In
1. Open app
2. Write a private domain email (expensifail)
3. Tap on Sign In
4. Write a magic code from email

## Expected Result:
User should be successfully signed in

## Actual Result:
App get crashed. If user kill and launch app the app will be crashed again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native -IPad
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0085d319-684a-4b60-8586-faffcbf018be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abzokhattab** [comment] 2024-01-11 17:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes on ipad 
### What is the root cause of that problem?
 
this line throws cannot access findindex of undefined
https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/src/libs/Navigation/FreezeWrapper.tsx#L20-L24


### What changes do you think we should make in order to solve the problem?

we need to safely access it

**Comment by situchan** [comment] 2024-01-11 17:34
@abzokhattab are you able to find offending PR?

There was similar crash in the past where TS check didn't catch it - #32515. Fixed in #32525

**Comment by abzokhattab** [comment] 2024-01-11 17:41
@situchan  my proposal is not working so i removed .. if i got a clue on what is happening will post here

**Comment by dangrous** [comment] 2024-01-11 17:52
Based on a simulator build, the same crash happens on production so I don't think this is a blocker, but it would be great to confirm that

**Comment by dangrous** [comment] 2024-01-12 20:15
This has been resolved on staging with https://github.com/Expensify/App/pull/34396, once that's on production we'll be able to close

**Comment by dangrous** [comment] 2024-01-23 15:17
No payment needed here, I'm going to close it out.

**Closed by dangrous** 2024-01-23 15:17 UTC
Labels: Engineering, Daily, Awaiting Payment
