### ISSUE TITLE
[HOLD for payment 2024-05-22] Bottom button on missing padding 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40827] opened 2024-04-23 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-3
**Reproducible in staging?:** y
**Reproducible in production?:** couldn't check
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Jonvrebdubielzyk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713832272368439

## Action Performed:
1. Click on Profile photo in botton navigation bar
2. Click on Wallet
3. Under "Assigned cards", click on one of the cards
4. Click on "Report virtual card fraud" or "Report physical card loss / damage"
5. Look at the footer button that has no padding

## Expected Result:
On step 5 I would expect the footer button to have correct padding of 20px on both sides and bottom
## Actual Result:
On step 5 it didn't have any padding. See screenshots in thread
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
<img src="https://github.com/Expensify/App/assets/38435837/574e71a0-593e-4e0b-ac02-746a1473cb96" width="40%" height="40%">
<img src="https://github.com/Expensify/App/assets/38435837/124baf33-1ecc-42ec-9e6b-ca66b0524330" width="40%" height="40%">
<img src="https://github.com/Expensify/App/assets/38435837/b99f3196-fe7c-4a99-a973-b6e022b909c7" width="40%" height="40%">
<img src="https://github.com/Expensify/App/assets/38435837/dee10c22-3a68-45b1-b740-68413be452dc" width="40%" height="40%">
![Snip - (4) New Expensify](https://github.com/Expensify/App/assets/38435837/93cce2b7-7d29-410c-aac6-b45812734a01)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by neonbhai** [comment] 2024-04-23 20:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bottom button on missing padding

### What is the root cause of that problem?
We are missing `containerStyles` in the `FormAlertWithSubmitButton` the reported pages

https://github.com/Expensify/App/blob/6b18ee91e8f7e498096b1ce04027a830f118ad12/src/pages/settings/Wallet/ReportCardLostPage.tsx#L200

### What changes do you think we should make in order to solve the problem?
We will pass `styles.mb5` and `styles.ph5` as the `containerStyles` in the reported pages:

https://github.com/Expensify/App/blob/6b18ee91e8f7e498096b1ce04027a830f118ad12/src/pages/settings/Wallet/ReportCardLostPage.tsx#L200

https://github.com/Expensify/App/blob/6b18ee91e8f7e498096b1ce04027a830f118ad12/src/pages/settings/Wallet/ReportVirtualCardFraudPage.tsx#L75

https://github.com/Expensify/App/blob/6b18ee91e8f7e498096b1ce04027a830f118ad12/src/pages/settings/Wallet/TransferBalancePage.tsx#L211

**Comment by luacmartins** [comment] 2024-04-23 21:43
@lukemorawski it seems like https://github.com/Expensify/App/pull/38039 caused a regression in a few other places. Could you please take a look at this issue and work on a fix?

**Comment by lukemorawski** [comment] 2024-04-24 09:41
@luacmartins sure, though I need to add some fake cards, as I don't have access to those pages now.

**Comment by shawnborton** [comment] 2024-04-29 20:06
Another case to consider is the View debug console page:
![image](https://github.com/Expensify/App/assets/2319350/19cd6a54-194b-42a5-9f86-57eb634cd472)

**Comment by shawnborton** [comment] 2024-05-07 15:17
What's the latest on this one?

**Comment by MrMuzyk** [comment] 2024-05-07 15:24
I've been asked to take over this issue. I've pushed latest changes to the branch that was previously created and uploaded [screenshots with fixed screens](https://github.com/Expensify/App/pull/40912#issuecomment-2097814542)

**Comment by shawnborton** [comment] 2024-05-07 16:24
Thanks! This regression has been live for a couple of weeks now, so I would love to get this cleaned up ASAP.

**Comment by trjExpensify** [comment] 2024-05-16 11:39
@mollfpr was the C+ on this one! Checklist when you're ready.

**Comment by luacmartins** [comment] 2024-05-27 15:36
@mollfpr could you please complete the checklist?

**Comment by mollfpr** [comment] 2024-05-28 15:57
> The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/38039

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/38039/files

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

We already have the check when updating a generic component, we should do the test diligently.

> Determine if we should create a regression test for this bug.
> If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

I don't think we need to add a new test case here.

**Comment by trjExpensify** [comment] 2024-05-30 01:41
Alrighty, thanks. Confirming payment summary as follows: 

$250 to @mollfpr for the C+ review. Go ahead and submit an expense. 

Closing!

**Closed by trjExpensify** 2024-05-30 01:41 UTC
Labels: Daily, Awaiting Payment, Bug
