### ISSUE TITLE
[$500] both bank accounts are labeled as default after adding another BA for a moment

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36944] opened 2024-02-20 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** need to have real bank data
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1708419649536799

## Action Performed:
Account Settings > Wallet > Add Bank account
Add the first BA (checking)
Add the second BA (saving)

## Expected result: 
Only one of the accounts should be labeled as default

## Actual result: 
Both accounts are labeled as default

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/59841f74-46cd-47c1-a952-fbddac9a090a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8029498cae4b95a</li>
        <li>Upwork Job ID: 1760040653618905088</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by omarnagy91** [comment] 2024-02-20 23:36
## Proposal

### Problem Statement

We are currently experiencing an issue where both bank accounts are momentarily labeled as default after a user adds a second bank account in the Expensify app. This behavior is unexpected and can lead to confusion for the user, as only one bank account should be labeled as default at any given time.

### Root Cause

I have reviewed the provided files and believe that the root cause of this issue is a bug in the state management within the components that interact with the bank account addition process. Specifically, the logic responsible for updating the default status of bank accounts is not handling the addition of new bank accounts correctly.

### Proposed Solution

To address this issue, I propose that we combine the following two solutions:

1.  **Revise the state management logic in the components responsible for adding bank accounts.**  This includes ensuring that when a new bank account is added, the default status is only assigned to the newly added account if no other default exists, or it is explicitly set by the user.
2.  **Add proper checks and balances to prevent multiple accounts from being labeled as default simultaneously.**

Here is an example of how this could be implemented in the  `AddPersonalBankAccountPage.tsx`  file:

```
const handleSetDefaultAccount = (bankAccountID) => {
  const bankAccounts = getBankAccounts();
  const defaultBankAccountID = getDefaultBankAccountID();

  // Check if the account being set as default is already the default account.
  if (bankAccountID === defaultBankAccountID) {
    return;
  }

  // Check if there is already a default account.
  if (defaultBankAccountID) {
    // If there is already a default account, unset it.
    set({
      defaultBankAccountID: null,
    });
  }

  // Set the new account as the default account.
  set({
    defaultBankAccountID: bankAccountID,
  });
};
```

### Benefits

The proposed solution is relatively straightforward to implement and maintain. It also aligns with the existing logic for managing default bank accounts in the app.

### Conclusion

I believe that the proposed solution is the best approach to resolving this issue. It is simple to implement, aligns with the existing codebase, and effectively addresses the root cause of the problem.

**Comment by brunovjk** [comment] 2024-02-22 19:46
I believe this issue has the same cause as [#34774](https://github.com/Expensify/App/issues/34774) and https://github.com/Expensify/App/issues/35788. @stitesExpensify is dealing with a [backend solution](https://github.com/Expensify/App/issues/35788#issuecomment-1952466682) that will resolve them.

**Comment by s101d1** [comment] 2024-02-24 22:47
I'm trying to reproduce this issue locally, but I can't add and log-in the personal bank account in local expensify app (https://dev.new.expensify.com:8082/) with [Fidelity Bank method](https://expensify.slack.com/archives/C01GTK53T8Q/p1680124196915209?thread_ts=1680123321.639259&cid=C01GTK53T8Q) (it shows invalid credentials message when I tried to log-in), I can only log-in the Fidelity Bank account successfully in the [staging](https://staging.new.expensify.com/). Is there a way to add and log-in the personal bank account in local dev environment?

**Comment by abdulrahuman5196** [comment] 2024-02-26 11:48
> I believe this issue has the same cause as [#34774](https://github.com/Expensify/App/issues/34774) and #35788. @stitesExpensify is dealing with a [backend solution](https://github.com/Expensify/App/issues/35788#issuecomment-1952466682) that will resolve them.

@miljakljajic Seems to be a duplicate issue. We can close this.

**Comment by abdulrahuman5196** [comment] 2024-03-01 11:33
> > I believe this issue has the same cause as [#34774](https://github.com/Expensify/App/issues/34774) and #35788. stitesExpensify is dealing with a [backend solution](https://github.com/Expensify/App/issues/35788#issuecomment-1952466682) that will resolve them.
> 
> @miljakljajic Seems to be a duplicate issue. We can close this.

@miljakljajic gentle ping

**Comment by miljakljajic** [comment] 2024-03-19 13:31
Apologies for missing this - closing!

**Closed by miljakljajic** 2024-03-19 13:31 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
