### ISSUE TITLE
[$500] Chat - Backspace does not trigger focus back on composer like normal letters do

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30204] opened 2023-10-23 20:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698064299267999

## Action Performed:
Action Performed:
1. Open the app
2. Open any report
3. Lose focus from composer
4. Type in any letters, it will focus back on composer
5. Again lose focus from composer
6. Use backspace to delete letters and observe that app does not focus back on composer

## Expected Result:
 App should focus back and remove letter if available on backspace as it does for other letters

## Actual Result:
App does not focus back and remove letter if available on backspace when there is no focus on composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/6beee819-9976-4e68-87c8-e71e1fb3ce70

https://github.com/Expensify/App/assets/93399543/58b5eedf-2266-4b59-90d3-61e5ddbad26e

https://github.com/Expensify/App/assets/93399543/ff4f2e4d-d561-44dd-bdc5-e7c1eb5c1dce

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/51d5d10d-d782-4b02-806f-31bfcd246b40

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01439e135348add7a7</li>
        <li>Upwork Job ID: 1716551231904194560</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-10-23 20:35
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pressing backspace on a page with the composer does not focus the composer like alphabetic characters

### What is the root cause of that problem?
The callback that detects keypresses and triggers a focus on the composer does not handle backspaces correctly

```
    const focusComposerOnKeyPress = useCallback(
        (e) => {
            const isComposerVisible = checkComposerVisibility();
            if (!isComposerVisible) {
                return;
            }

            // If the key pressed is non-character keys like Enter, Shift, ... do not focus
            if (e.key.length > 1) {
                return;
            }

            // If a key is pressed in combination with Meta, Control or Alt do not focus
            if (e.metaKey || e.ctrlKey || e.altKey) {
                return;
            }

            // If the space key is pressed, do not focus
            if (e.code === 'Space') {
                return;
            }

            // if we're typing on another input/text area, do not focus
            if (['INPUT', 'TEXTAREA'].includes(e.target.nodeName)) {
                return;
            }

            focus();
            replaceSelectionWithText(e.key, false);
        },
        [checkComposerVisibility, focus, replaceSelectionWithText],
    );
```

### What changes do you think we should make in order to solve the problem?
Edit the filter which excludes all non-character keys to ensure that backspaces get captured
Before:
```
            if (e.key.length > 1) {
                return;
            }
```
After:
```
            if (e.key.length > 1 && e.key !== 'Backspace') {
                return;
            }
```

**Comment by FitseTLT** [comment] 2023-10-23 20:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose doesn't refocus for backspace
### What is the root cause of that problem?
This code doesn't make it refocus for backspace
https://github.com/Expensify/App/blob/844b3b96b5bcd80c5c7bd376648a921939e25d10/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L419-L477
### What changes do you think we should make in order to solve the problem?

We should change it to 

`

    const focusComposerOnKeyPress = useCallback(
        (e) => {
            const isComposerVisible = checkComposerVisibility();
            if (!isComposerVisible) {
                return;
            }

            // If the key pressed is non-character keys like Enter, Shift, ... do not focus
            if (e.key.length > 1 && e.key !== 'Backspace') {
                return;
            }

            // If a key is pressed in combination with Meta, Control or Alt do not focus
            if (e.metaKey || e.ctrlKey || e.altKey) {
                return;
            }

            // If the space key is pressed, do not focus
            if (e.code === 'Space') {
                return;
            }

            // if we're typing on another input/text area, do not focus
            if (['INPUT', 'TEXTAREA'].includes(e.target.nodeName)) {
                return;
            }

            focus();
            if (e.key !== 'Backspace') replaceSelectionWithText(e.key, false);
        },
        [checkComposerVisibility, focus, replaceSelectionWithText],
    );
`
### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-10-23 21:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose doesn't refocus for backspace
### What is the root cause of that problem?
This code doesn't make it refocus for backspace
https://github.com/Expensify/App/blob/86e75ad6c95cd5927800bb62b848857716da52f6/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L419
### What changes do you think we should make in order to solve the problem?
1. We should change it to
```
 const focusComposerOnKeyPress = useCallback(
        (e) => {
            const isComposerVisible = checkComposerVisibility();
            if (!isComposerVisible) {
                return;
            }

            // If the key pressed is non-character keys like Enter, Shift, ... do not focus
            if (e.key.length > 1 && e.key !== 'Backspace') {
                return;
            }

            // If a key is pressed in combination with Meta, Control or Alt do not focus
            if (e.metaKey || e.ctrlKey || e.altKey) {
                return;
            }

            // If the space key is pressed, do not focus
            if (e.code === 'Space') {
                return;
            }

            // if we're typing on another input/text area, do not focus
            if (['INPUT', 'TEXTAREA'].includes(e.target.nodeName)) {
                return;
            }

            focus();
            if (e.key !== 'Backspace') {
                replaceSelectionWithText(e.key, false);
            } else {
                removeLastLetterFromText();
            }
        },
        [checkComposerVisibility, focus, replaceSelectionWithText, removeLastLetterFromText],
 );
``` 
2. we need to add removeLastLetterFromText function
```
    const removeLastLetterFromText = useCallback(
        () => {
            updateComment(commentRef.current.slice(0, commentRef.current.length- 1));
            // We may add more
        },
        [updateComment],
    );
```
### What alternative solutions did you explore? (Optional)

https://github.com/Expensify/App/assets/65789015/87909659-9dae-48a0-94af-e32ccfe4352f

**Comment by joekaufmanexpensify** [comment] 2023-10-23 22:01
I don't think this is a bug. We do automatically refocus the composer when you type numbers or letters, but we consistently don't do that for non-number/letter keys on the keyboard for things like delete, or shift + return (which breaks a new line).

It feels like the pattern for this is consistent now, so I don't think we should change it. Closing for now!

**Closed by joekaufmanexpensify** 2023-10-23 22:01 UTC
Labels: External, Daily, Help Wanted, Bug
