### ISSUE TITLE
[$500] Can't remove/add members from workspace after switching to focus mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33185] opened 2023-12-15 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MonilBhavsar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702639886992049

## Action Performed:

1. Create workspace as user A, invite User B read newly created announce and admins room
2. Have some chats with another user
3. Turn on focus mode
4. Logout and login
5. Go to Workspace > Member and try to remove User B
6. Or try to invite a new member

## Expected Result:
Able to add or remove the the members

## Actual Result:
Unable to add or remove the member

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3800c1cd-e2b3-4be5-93c0-d8a133c16b0c

![Screenshot 2023-12-15 at 4 59 21 PM](https://github.com/Expensify/App/assets/38435837/80b36dd5-4577-482f-af5b-c22a26329b0b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0157c650b5d29d1542</li>
        <li>Upwork Job ID: 1735730275253252096</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by namhihi237** [comment] 2023-12-15 18:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can not invite member when focus mode after login
### What is the root cause of that problem?
Because after login the `announceReport` is null, we don't have `reportID`
### What changes do you think we should make in order to solve the problem?
We can call API to update the recent mode before

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2023-12-19 21:21
https://github.com/Expensify/App/issues/32682 has been added to wave 8, so I am closing this as a dupe.

**Closed by anmurali** 2023-12-19 21:21 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
