### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Dev: Web  -  Room name field does not automatically focus when returning from the chat option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27607] opened 2023-09-16 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the "Send message" feature.
2. Click on Room.
3. Then Click on the "Chat" option.
4. Return back to the room.
5. Observe that the room name field does not auto-focus.

## Expected Result:
Upon returning from the chat option, the room name field should automatically receive focus

## Actual Result:
 The room name field does not auto-focus when returning from the chat option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6ffa9526-e4ef-4928-881d-e5d3be494fcd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694798666830459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183b28b14d01b5fa6</li>
        <li>Upwork Job ID: 1703147323818520576</li>
        <li>Last Price Increase: 2023-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26984474</li>
<li>akinwale | Contributor | 26984475</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-16 20:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The room name field does not automatically gain focus when returning from the chat option.

### What is the root cause of that problem?
The screen transition end event is not fired at this point.

### What changes do you think we should make in order to solve the problem?
1. Add the timeout ref and the `useFocusEffect` hook.
```
const focusTimeoutRef = useRef(null);
useFocusEffect(useCallback(() => {
    focusTimeoutRef.current = setTimeout(() => textInput.current && textInput.current.focus(), CONST.ANIMATED_TRANSITION);
    return () => {
        if (!focusTimeoutRef.current) {
            return;
        }
        clearTimeout(focusTimeoutRef.current);
    };
}, []));
```

2. Remove the `onEntryTransitionEnd` prop from the root `ScreenWrapper` for cleanup.

### What alternative solutions did you explore? (Optional)
None.

**Comment by MitchExpensify** [comment] 2023-09-18 21:01
This is on dev and not reproducible on staging (v1.3.71-5) or prod (v1.3.70-8). I think we should close this until its reproducible on either staging or prod

**Comment by c3024** [comment] 2023-09-22 12:02
This is now on staging v1.3.72-9. @MitchExpensify

**Comment by MitchExpensify** [comment] 2023-09-26 04:32
@abdulrahuman5196 how does @c3024 's proposal look to you?

**Comment by abdulrahuman5196** [comment] 2023-09-28 14:07
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-09-29 11:58
Re-checking again

**Comment by abdulrahuman5196** [comment] 2023-09-29 13:35
@c3024 's proposal here https://github.com/Expensify/App/issues/27607#issuecomment-1722400583 is more like a generic PR version of the same proposal here https://github.com/Expensify/App/issues/27607#issuecomment-1722314235. So I wouldn't be able to take it as a separate proposal.

**Comment by abdulrahuman5196** [comment] 2023-09-29 13:40
@akinwale 's proposal here https://github.com/Expensify/App/issues/27607#issuecomment-1722314235 looks good and works well. Kindly make the implementation generic enough during PR.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment] 2023-10-02 09:14
Not overdue. Pending on @robertjchen Review.

**Comment by robertjchen** [comment] 2023-10-02 17:35
Agreed with @akinwale 's proposal as well 👍

**Comment by akinwale** [comment] 2023-10-02 19:22
@abdulrahuman5196 My [PR](https://github.com/Expensify/App/pull/28646) is ready for review. Thanks.

**Comment by abdulrahuman5196** [comment] 2023-10-16 18:37
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be misses from latest UI rewamps.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Open the global create menu and select Send message
2) Click on the Room tab if it is not the active tab.
3) Verify that the room name input field gains focus.
4) Click on the Chat tab.
5) Click on the Room tab.
6) Verify that the room name input field regains focus.
7) Repeat steps 6 through 8 a few more times.

**Comment by akinwale** [comment] 2023-10-18 12:07
@MitchExpensify Just checking in here for payment. Thanks.

**Comment by MitchExpensify** [comment] 2023-10-18 21:21
**Payment summary:**

All Upwork: 
- $750 @akinwale requires payment [offer](https://www.upwork.com/nx/wm/offer/26984475) (Contributor) 
- $750 @abdulrahuman5196 requires payment [offer](https://www.upwork.com/nx/wm/offer/26984474) (Reviewer)
- $250 @ayazhussain79 requires payment

**Comment by MitchExpensify** [comment] 2023-10-18 21:25
Paid and contract ended, thanks for the bump!

Just waiting on test rail updates (On me)

And @ayazhussain79 to accept Upwork offer

**Comment by ayazhussain79** [comment] 2023-10-19 01:36
@MitchExpensify offer accepted, Thank you

**Comment by MitchExpensify** [comment] 2023-10-20 20:42
Mind sharing the offer/contract with me @ayazhussain79, I cannot find it in Upwork 😅  (Their search is terrible)

**Comment by MitchExpensify** [comment] 2023-10-20 20:45
https://github.com/Expensify/Expensify/issues/328389

**Comment by ayazhussain79** [comment] 2023-10-20 20:54
@MitchExpensify I think there is no option to copy contract URL so sent you message on upwork.

**Comment by MitchExpensify** [comment] 2023-10-22 19:04
Paid! Thanks @ayazhussain79

**Closed by MitchExpensify** 2023-10-22 19:04 UTC
Labels: External, Daily, Awaiting Payment
