### ISSUE TITLE
[$500] Thread - Main chat is in a different section when returning from thread via browser back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37662] opened 2024-03-03 00:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Log in.
3. Go to the public room https://staging.new.expensify.com/r/6776919265133947
4. Scroll to the top to reveal all the conversation.
5. Scroll down and open any thread (better visit newer thread).
6. Click browser back button.

## Expected Result:
App will return to the same part of the main chat as before going to the thread

## Actual Result:
App will return to the same part of the main chat as before going to the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a41ae77a-0c28-4edf-8e56-2dc62ceb19c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123cd735ed53880ac</li>
        <li>Upwork Job ID: 1765499258797154304</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-03 00:26
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-03 00:26
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by slafortune** [comment] 2024-03-04 13:45
@CortneyOfstad is OOO until 3/11 - reassigning

**Comment by joekaufmanexpensify** [comment] 2024-03-05 15:26
Reproduced. This affects any chat, not just public rooms. @hayata-suenaga I see you worked on [this](https://github.com/Expensify/App/issues/35626). I feel like this could be related to ideal nav. Curious if you agree?

**Comment by hayata-suenaga** [comment] 2024-03-05 17:05
@joekaufmanexpensify, thank you for informing us about this issue. It appears to be related to the preservation of chat list position, rather than the back navigation behavior.

Just in case, I'm tagging @getusha and @adamgrzybowski from [the linked issue](https://github.com/Expensify/App/issues/35626).

**Comment by jacobkim9881** [comment] 2024-03-06 09:14
Hi. I found a way round that doesn't make the bug.

https://github.com/Expensify/App/assets/46774300/d73803b5-1e51-4052-a831-4f51e4f7e8d4

**Comment by jacobkim9881** [comment] 2024-03-06 09:18
I tried to find how two actions(clicking thread and clicking forward button) different. I found clicking the thread makes this log.

```
The log before clicking any thread, which made the bug(OpenReport command is executed)


[Debug] [info] Called API write - {"command":"OpenReport","reportID":"6962315901589981","emailList":"","accountIDList":"","parentReportActionID":"0","idempotencyKey":"OpenReport_6962315901589981","clientLastReadTime":"2024-03-06 08:01:35.422"}
```

It seems `OpenReport` cause the bug. I wanted to know how the OpenReport works. I found this comments on the code.

``
 // If you already have a report open and are deeplinking to a new report on native,
 // the ReportScreen never actually unmounts and the reportID in the route also doesn't change.
// Therefore, we need to compare if the existing reportID is the same as the one in the route
// before deciding that we shouldn't call OpenReport.
``

It is when any thread clicked. That means clicking threads urges ReportScreen to unmount current reportID to mount new reportID for the thread.

**Comment by joekaufmanexpensify** [comment] 2024-03-06 22:07
Looking for proposals

**Comment by ahmedGaber93** [comment] 2024-03-07 02:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread - Main chat is in a different section when returning from thread via browser back button

### What is the root cause of that problem?
when we back to the main thread and the component [MVCPFlatList](https://github.com/Expensify/App/blob/main/src/components/FlatList/MVCPFlatList.js)  is not complete layout the `firstVisibleViewOffset` will calculated wrong because `firstVisibleView.offsetTop` be 0 here until the component complete layout.
https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/components/FlatList/MVCPFlatList.js#L95

and after the component complete layout `onLayout` we missed calculate to `firstVisibleViewOffset` again  


### What changes do you think we should make in order to solve the problem?
we need to call `prepareForMaintainVisibleContentPosition()` inside [onLayout](https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/components/FlatList/MVCPFlatList.js#L193) to calaculate `firstVisibleViewOffset` correctly

### What alternative solutions did you explore? (Optional)

**Comment by jacobkim9881** [comment] 2024-03-09 09:26
Seems it will be fixed [here](https://github.com/Expensify/App/pull/30269).

**Comment by joekaufmanexpensify** [comment] 2024-03-11 14:36
Not overdue

**Comment by joekaufmanexpensify** [comment] 2024-03-11 19:21
@mkhutornyi curious if you agree this will be fixed in [this PR](https://github.com/Expensify/App/issues/37662#issuecomment-1986805790)?

**Comment by jacobkim9881** [comment] 2024-03-12 10:02
Let me clear [this](https://github.com/Expensify/App/issues/37662#issuecomment-1986805790). I tested it with [this PR](https://github.com/Expensify/App/pull/30269) and checked the issue is solved.

**Closed** 2024-03-12 14:10 UTC
Labels: External, Daily, Help Wanted, Bug
