### ISSUE TITLE
Android - Chat - Badge "stg" is missing  in the chat list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9465] opened 2022-06-15 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the internal tester program New Expensify app
2. Login with any user

## Expected Result:
Must be marked "stg" badge in the sign in page and in the chat list page

## Actual Result:
There is no "stg" badge in the sign in page and in the chat list page

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.77-2

**Reproducible in staging?:** Y

**Reproducible in production?:** -

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/173848540-0f748514-b384-4f66-b900-6b872c993ab4.png" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/173848553-7180b8f3-5845-41a4-8d26-12d36f3f913f.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment] 2022-06-20 20:23
Setting as internal, since external collaborators can't really access the staging environment, and monthly, since it is not a big deal.

**Comment by mvtglobally** [comment] 2022-08-16 04:47
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-08-23 04:08
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-08-30 15:17
Issue not reproducible during KI retests. (Third week)Closing

**Closed by mvtglobally** 2022-08-30 15:17 UTC
Labels: Reviewing, Engineering, Monthly, Improvement, Internal
