### ISSUE TITLE
[$250] Web - Attachment - Onyx and DataCloneError console rrrors when sending an image attachment

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50780] opened 2024-10-15 07:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5084384&group_by=cases:section_id&group_order=asc&group_id=292107
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Navigate to FAB - Start chat
4. Start a 1:1 DM with any account
5. Send any image attachment to the chat

## Expected Result:
There shouldn't be any console errors.

## Actual Result:
Onyx and DataCloneError console errors when sending an image attachment to a 1:1 DM.
Expensify.tsx:50 [Onyx] Attempted to set invalid data set in Onyx. Please ensure all data is serializable.

index.js:40 Uncaught (in promise) DataCloneError: Failed to execute 'put' on 'IDBObjectStore': function arrayBuffer() { [native code] } could not be cloned.
at index.js:40:15
at index.js:13:51

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[1510.txt](https://github.com/user-attachments/files/17374251/1510.txt)

https://github.com/user-attachments/assets/389e439f-d7ec-4f4a-91d1-f6f815351388

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846724620826087266</li>
        <li>Upwork Job ID: 1846724620826087266</li>
        <li>Last Price Increase: 2024-12-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rlinoz</details>

**Comment by IuliiaHerets** [comment] 2024-10-15 07:26
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-10-16 03:40
I can't repro this, I don't get any errors at all. I note the steps are very specific - does the account need to be brand new and also need to be gmail @IuliiaHerets ?

**Comment by RachCHopkins** [comment] 2024-10-17 01:27
Strange, no, I can't repro. But I trust you @daledah, if you can, then that's good enough for me!

**Comment by RachCHopkins** [comment] 2024-10-22 22:56
@Pujan92 can you check out the above proposal, please?

**Comment by huult** [comment] 2024-10-24 17:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Onyx and DataCloneError console errors when sending an image attachment

### What is the root cause of that problem?

This issue related RCA with issue [49329](https://github.com/Expensify/App/issues/49329) and [44114](https://github.com/Expensify/App/issues/44114)

This issue occurs on the backend because when we call the `AddAttachment` request, the `lastUpdateIDFromClient` is less than the `previousUpdateID` received. As a result, the `responseToApply` ends up using the wrong function to store the `responseToApply`, which is [`OnyxUpdates.saveUpdateInformation(responseToApply)`](https://github.com/Expensify/App/blob/main/src/libs/Middleware/SaveResponseInOnyx.ts#L39). In this case, we expect to use [`OnyxUpdates.apply(responseToApply);`](https://github.com/Expensify/App/blob/main/src/libs/Middleware/SaveResponseInOnyx.ts#L35) to save the response. Additionally, when we use this function, the `responseToApply` from `AddAttachment` needs to be serialized first; otherwise, it will throw an error log in this ticket.

> {"lastUpdateIDFromClient":2571094520,"previousUpdateID":2571094574} 

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we need to make a change on the backend so that the `previousUpdateID` is less than the `lastUpdateIDFromClient` in this case, or we should always update `ADD_ATTACHMENT` to the most current state. Something like this:

```diff
//.src/libs/Middleware/SaveResponseInOnyx.ts#L12
const requestsToIgnoreLastUpdateID: string[] = [
    WRITE_COMMANDS.OPEN_APP,
    SIDE_EFFECT_REQUEST_COMMANDS.RECONNECT_APP,
    WRITE_COMMANDS.CLOSE_ACCOUNT,
+    WRITE_COMMANDS.ADD_ATTACHMENT,
    WRITE_COMMANDS.DELETE_MONEY_REQUEST,
    SIDE_EFFECT_REQUEST_COMMANDS.GET_MISSING_ONYX_MESSAGES,
];
```

**Comment by RachCHopkins** [comment] 2024-10-25 05:39
@Pujan92 how do you feel about these proposals?

**Comment by Pujan92** [comment] 2024-10-28 12:23
As both proposals stated, I think this needs to be fixed in the BE if possible, to correct the values of `previousUpdateID` and `lastUpdateIDFromClient`. So that the correct function `OnyxUpdates.apply` gets called. Adding an internal engineer for the quick look.

🎀👀🎀 C+ reviewed

**Comment by rlinoz** [comment] 2024-10-28 13:37
Im not very familiar with the updateIDs logic, but I will try to take a look today.

**Comment by huult** [comment] 2024-10-28 14:14
If the backend doesn't have a solution to update it, I think we can still fix this on the frontend, and we can add it to `requestsToIgnoreLastUpdateID` because, upon checking, it seems we don't need to wait for any requests to update fields in the add attachment request.

**Comment by rlinoz** [comment] 2024-10-28 18:50
Im not being able to repro this 🤔

**Comment by huult** [comment] 2024-10-29 01:40
@rlinoz , I would like to share the video with you so you know how I reproduced this issue
<details><summary>Video</summary>

https://github.com/user-attachments/assets/e62819a0-408d-487b-a16f-a59d203d293e

</details>

1. Log in with a new account.
2. Start a direct message.
3. Send an image.
4. Observe the error message after sending the image.

**Comment by Pujan92** [comment] 2024-10-29 05:28
> 1. Log in with a new account.

No need to log in with a new account, sending an image as the first message to a new contact also resulted in a console error.

https://github.com/user-attachments/assets/d189e077-f1d3-4c16-ac23-fa7f2bb4399c

**Comment by rlinoz** [comment] 2024-10-29 18:14
If I follow https://github.com/Expensify/App/issues/50780#issuecomment-2443249515

<img width="2182" alt="image" src="https://github.com/user-attachments/assets/71224f78-6c5a-4951-8d80-90032a44d818">

Let me try this: https://github.com/Expensify/App/issues/50780#issuecomment-2442990320

**Comment by rlinoz** [comment] 2024-10-29 18:17
same thing, are you trying in staging?

<img width="2164" alt="Screenshot 2024-10-29 at 15 17 04" src="https://github.com/user-attachments/assets/1aa36a2b-8975-4cc0-ac1b-fd5ab39b082f">

**Comment by huult** [comment] 2024-10-30 06:18
@rlinoz I'm still able to reproduce this issue on staging.

https://github.com/user-attachments/assets/b5d11d4f-0782-499a-82cd-9a77645c340a

**Comment by rlinoz** [comment] 2024-10-30 12:57
I am having a really hard time trying to reproduce this, let me know if I am missing something in the video

https://github.com/user-attachments/assets/78944310-5abc-4660-8f62-e2b5039edd9b

Looking at the logs that I think are from the [comment above](https://github.com/Expensify/App/issues/50780#issuecomment-2446655924) I see the previousUpdateID higher than the clientUpdateID

clientUpdateID: 2660128276
previousUpdateID: 2660128284

And looking at the logs from my own request the same thing happens but no console error

clientUpdateID: 2660954499
previousUpdateID: 2660954506

But looking at random `AddComment` requests this seems to often be true, so I am not sure the updateID is wrong here.

**Comment by rlinoz** [comment] 2024-11-01 12:24
Nothing on latest chrome version:

<img width="2191" alt="image" src="https://github.com/user-attachments/assets/c258afdb-b146-4cb9-97b8-202d36c404c1">

Anyway, maybe we can make sure that this comment is corret: https://github.com/Expensify/App/issues/50780#issuecomment-2441712805

**Comment by huult** [comment] 2024-11-01 15:38
> Anyway, maybe we can make sure that this comment is corret: https://github.com/Expensify/App/issues/50780#issuecomment-2441712805

@rlinoz I tested DM, IOU and sent an attachment there. I see that `ADD_ATTACHMENT` doesn’t wait for any request to update the field in the add attachment request

**Comment by rlinoz** [comment] 2024-11-01 21:29
@Pujan92 thoughts on the above? https://github.com/Expensify/App/issues/50780#issuecomment-2452089309

**Comment by Pujan92** [comment] 2024-11-02 18:36
@rlinoz I think we can proceed with what @huult suggested which is to add command in `requestsToIgnoreLastUpdateID`.

**Comment by rlinoz** [comment] 2024-11-04 14:15
So we basically shouldn't be trying to set a File into the OnyxDB right?

**Comment by wildan-m** [comment] 2024-11-07 03:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Console errors, Onyx and DataCloneError, occur when sending an image attachment on the web.

### What is the root cause of that problem?

We are trying to store blob file here:

https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/libs/Middleware/SaveResponseInOnyx.ts#L38-L39

### What changes do you think we should make in order to solve the problem?

> [!NOTE]  
> If this solution has not been officially proposed, I propose it; if it is considered a duplicate, I vote for it.

If we can't store a file in Onyx, we shouldn't do so. Preprocessing the file is unnecessary if we don't actually use it later.

We can create `filterFiles` function to recursively filter files in `request.data`

```tsx

function filterFiles(obj: any): any {
    if (Array.isArray(obj)) {
        return obj.map(filterFiles);
    } else if (obj && typeof obj === 'object') {
        return Object.keys(obj).reduce((acc, key) => {
            if (obj[key] instanceof File) {
                return acc;
            }
            acc[key] = filterFiles(obj[key]);
            return acc;
        }, {} as any);
    }
    return obj;
}

```

And modify `responseToApply`

```tsx

        const filteredRequest = {
            ...request,
            data: filterFiles(request.data),
        };

        const responseToApply = {
            type: CONST.ONYX_UPDATE_TYPES.HTTPS,
            lastUpdateID: Number(response?.lastUpdateID ?? 0),
            previousUpdateID: Number(response?.previousUpdateID ?? 0),
            request: filteredRequest,
            response: response ?? {},
        };

```


[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/50780-filter-files-for-onyx?expand=1)
### What alternative solutions did you explore? (Optional)
By following the YAGNI principle, we can whitelist stored request.data to avoid storing unnecessary data.

Add to CONST

```tsx

    ONYX_ALLOWED_REQUEST_DATA: ['apiRequestType', 'returnValueList', 'nvpNames', 'shouldRetry', 'apiRequestType', 'skipReauthentication', 'shouldProcessImmediately', 'canCancel'], // this just example

```

Modify `responseToApply`

```tsx

const filterAllowedRequestData = (data: any, allowedKeys: string[]) => {
    const regex = new RegExp(`^(${allowedKeys.join('|')})$`);
    return Object.keys(data)
        .filter(key => regex.test(key))
        .reduce((obj, key) => {
            obj[key] = data[key];
            return obj;
        }, {});
};

...

        const filteredRequestData = filterAllowedRequestData(request.data, [...CONST.ONYX_ALLOWED_REQUEST_DATA]);

        const responseToApply = {
            type: CONST.ONYX_UPDATE_TYPES.HTTPS,
            lastUpdateID: Number(response?.lastUpdateID ?? 0),
            previousUpdateID: Number(response?.previousUpdateID ?? 0),
            request: {
                ...request,
                data: filteredRequestData,
            },
            response: response ?? {},
        };

```


[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/50780-fix-whitelist-stored-onyx-data?expand=1)

**Comment by Pujan92** [comment] 2024-11-08 14:15
> If we can't store a file in Onyx, we shouldn't do so

@wildan-m I see the file object stored for the onyx key `networkRequestQueue` if we try to send an attachment offline.

<img width="1230" alt="Screenshot 2024-11-08 at 19 43 39" src="https://github.com/user-attachments/assets/b5317444-8052-4864-8e02-b5e1a431410c">

**Comment by wildan-m** [comment] 2024-11-08 14:52
@Pujan92 I can no longer reproduce it. Can you?

**Comment by Pujan92** [comment] 2024-11-09 10:46
Yes, I am still able to reproduce it.

**Comment by rlinoz** [comment] 2024-11-13 11:29
so why are we not being able to save a file in this case? 🤔

**Comment by RachCHopkins** [comment] 2024-11-20 07:48
@rlinoz do you understand what is happening here?

**Comment by rlinoz** [comment] 2024-11-20 12:34
I would say we are still looking for a proposal, but I will also add the retest label since I was never able to reproduce.

Also, it seems that we are fixing the IDs order over here https://github.com/Expensify/App/pull/51712#discussion_r1839090153

**Comment by rlinoz** [comment] 2024-11-25 13:50
Waiting for proposals.

**Comment by rlinoz** [comment] 2024-11-28 13:04
Still watiting

**Comment by rlinoz** [comment] 2024-12-02 13:12
Waiting for proposals and retest

**Comment by rlinoz** [comment] 2024-12-05 13:35
Waiting for proposals and retest

**Comment by rlinoz** [comment] 2024-12-05 13:36
Might get fixed here though https://github.com/Expensify/App/issues/53417

**Closed** 2024-12-09 13:44 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug, retest-weekly

**Comment by kubabutkiewicz** [comment] 2024-12-13 15:32
Hi, wanted to ask if this is still reproducible? I was trying today and no luck but I see that fix to backend about order of ids  from here https://github.com/Expensify/App/pull/51712#discussion_r1839090153 is deployed so maybe its also fixed that issue?

**Comment by rlinoz** [comment] 2024-12-13 15:38
I was never really able to reproduce this, can you please try @Pujan92?

**Comment by Pujan92** [comment] 2024-12-13 15:45
I tried when @rlinoz closed the issue and couldn't reproduce it. so it might be fixed with the backend fix as mentioned by @kubabutkiewicz.
