### ISSUE TITLE
[$1000] [Awaiting bug report payment on June 5th] Blank page is displayed on closing account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19814] opened 2023-05-30 13:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' icon
2. Click on 'Security' link
3. Click on 'Close account' link
4. Enter default contact method & click on 'Close account' button
## Expected Result: 
Sign in page should be displayed with 'Account closed successfully ' page
## Actual Result: 
A blank page is displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ed9a484d-cec3-42a3-88a4-b3e657e71feb

https://github.com/Expensify/App/assets/43996225/35da39c0-f49a-43af-91f5-ffae3e6c48ac

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685438957019449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010159d91a372ae576</li>
        <li>Upwork Job ID: 1671626559125729280</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-05-30 14:12
I'm unable to reproduce this on web ([see Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1685438957019449)). Asked clarifying questions there.

**Comment by Julesssss** [comment] 2023-05-30 14:49
I confirmed locally, and discovered that [this PR](https://github.com/Expensify/App/pull/18293#issuecomment-1568574904) is the cause of the regression. 

We might have a potential fix, but if not we'll need to revert.

**Comment by kavimuru** [comment] 2023-05-30 17:58
@grgia @marcochavezf we have the same black screen for a moment in android app when sign out. Should we need a separate GH issue created?

https://github.com/Expensify/App/assets/43996225/bbf237ec-978e-45e4-9aa0-d82f3322b4d7

**Comment by marcochavezf** [comment] 2023-05-30 18:04
Hi @kavimuru, yeah let's create another GH for that. Also, is that only happening on Android?

**Comment by marcochavezf** [comment] 2023-05-30 18:06
And assign it to me, please

**Comment by Julesssss** [comment] 2023-05-31 11:14
Marking closed now that we have [CPd the PR](https://github.com/Expensify/App/pull/19841).

**Comment by Natnael-Guchima** [comment] 2023-05-31 11:28
Hello @Julesssss, I haven't been paid for reporting bonus yet.

**Comment by Julesssss** [comment] 2023-05-31 11:32
Ah sorry, we didn't follow the full process with this one so I missed it.

**Comment by Julesssss** [comment] 2023-05-31 11:33
We'll need to wait a week for payment, but I'll add a not to the title.

**Comment by Natnael-Guchima** [comment] 2023-05-31 11:34
No problem✌. And Thanks.

**Comment by Natnael-Guchima** [comment] 2023-06-13 12:22
@grgia @Julesssss @marcochavezf a gentle bump for reporting payment. 

Thanks.

**Comment by Julesssss** [comment] 2023-06-13 12:43
Hey @johncschuster, can you please pay out @Natnael-Guchima? Thanks!

**Comment by johncschuster** [comment] 2023-06-21 21:09
Sorry, team! I let this slip! Working on this now!

**Comment by johncschuster** [comment] 2023-06-21 21:10
Sorry for the ping, @0xmiroslav – I just needed to create the job. Nothing to see here.

**Comment by Natnael-Guchima** [comment] 2023-06-22 05:30
@johncschuster I have applied to the job. Thanks.

**Comment by johncschuster** [comment] 2023-06-22 14:29
@Natnael-Guchima I've extended the offer! Let me know when you accept and I'll get the payment issued!

**Comment by Natnael-Guchima** [comment] 2023-06-22 14:30
@johncschuster I have accepted the offer. Thanks.

**Comment by Natnael-Guchima** [comment] 2023-06-26 13:17
@johncschuster a gentle bump

**Comment by johncschuster** [comment] 2023-06-26 17:45
Payment issued! Thanks for your patience, @Natnael-Guchima!

**Closed** 2023-06-26 17:46 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Task, Bug
