### ISSUE TITLE
[HOLD for payment 2023-06-07] does not bold the mention in heading style

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18892] opened 2023-05-13 16:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open a chat
2. send a mention
3. send a mention in heading style (# @ddddd)

## Expected results: 
should bold the mention
## Actual results: 
padding is added but same font-weight in heading

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.4
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/39432985-ed04-4daf-892b-7d525acf447c

https://github.com/Expensify/App/assets/43996225/154208e9-6ba2-4108-bf4c-829ea90516e3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683924161722189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragxarora** [comment] 2023-05-15 07:39
It's about the new mention style present in staging where it adds background to email

**Comment by bernhardoj** [comment] 2023-05-15 08:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Heading style (bold, bigger font size) is not applied to mention text. Also, other markdown style (bold, italic) is not applied to the mention on native.

### What is the root cause of that problem?
We have a custom renderer for mention, MentionUserRenderer and MentionUserRenderer. In web, when we wrap the mention with bold markdown for example, the style will be inherited to the mention text. However, with heading text, we will have multiple nested element as you can see below.
<img width="421" alt="image" src="https://github.com/Expensify/App/assets/50919443/e7fa1e98-780b-414a-b6cb-9e0137705a03">

If you look at the css style, you can see the `font` style is set to inherited, which means it will inherit the style from it's parent, which is a div, not the h1. I found we have the extra div because of the outer Text here.
https://github.com/Expensify/App/blob/b01caf6bb4d288e0f6ed199026bada9024819c7f/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L38-L53

But, even though we remove the outer Text, the `font` style will have `font-weight` set to `normal` which will override the style from h1. All of these styles is handled by react-native-render-html.

In native, style is not inherited (except for nested text).

### What changes do you think we should make in order to solve the problem?


We should append the mention style with the style from the props.

https://github.com/Expensify/App/blob/b01caf6bb4d288e0f6ed199026bada9024819c7f/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L43-L47

So, the new style will be 

```
style={[props.style, StyleUtils.getMentionStyle(isOurMention)]}
```

We need to do the same in MentionHereRenderer.

**Comment by zanyrenney** [comment] 2023-05-16 17:23
thanks @bernhardoj lets get this reviewed by our team.

**Comment by s-alves10** [comment] 2023-05-16 18:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mention in heading style doesn't bold.

### What is the root cause of that problem?

When we use @ symbol to mention user in the comment, HTMLRenderer uses `MentionUserRenderer` to render the element. Here is the component
https://github.com/Expensify/App/blob/51dff315ab65bc5266425de0b43d4fe1cd0cdbe7/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js

This component uses `Text` component defined here
https://github.com/Expensify/App/blob/51dff315ab65bc5266425de0b43d4fe1cd0cdbe7/src/components/Text.js

The root cause of this issue is in `Text` component. Please check the below code

https://github.com/Expensify/App/blob/51dff315ab65bc5266425de0b43d4fe1cd0cdbe7/src/components/Text.js#L63-L73

`RNText` component has its own `font` style and this overrides the `font-weight` of `h1` parent element.
![image](https://github.com/Expensify/App/assets/126839717/55e0a2b9-166b-49a4-ac9e-39de29ff45e6)


### What changes do you think we should make in order to solve the problem?
We need to override the default `font` style of `RNText` component by adding the following line
```
    font: 'inherit',
```
to the component style.
https://github.com/Expensify/App/blob/51dff315ab65bc5266425de0b43d4fe1cd0cdbe7/src/components/Text.js#L51-L57

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/adcc6ce2-c178-45ad-abbf-887012c9fba2


</details>

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-05-19 09:52
hey @madmax330 let me know which proposal you think looks best.

**Comment by zanyrenney** [comment] 2023-05-22 11:44
bump @madmax330 curious who you think we should hire for this job please!

**Comment by madmax330** [comment] 2023-05-22 15:54
@aimane-chnaif can you review the proposals?

**Comment by s-alves10** [comment] 2023-05-23 17:17
@aimane-chnaif 
I think my solution is the simplest one and let the `Text` component work as expected because it makes the parent `font` inherited. 
Will you point out the drawbacks of my [proposal](https://github.com/Expensify/App/issues/18892#issuecomment-1550186414)?

**Comment by zanyrenney** [comment] 2023-05-25 14:32
@chiragxarora invite sent!

**Comment by zanyrenney** [comment] 2023-05-25 14:36
paid @bernhardoj @aimane-chnaif !

**Comment by bernhardoj** [comment] 2023-05-25 14:39
@aimane-chnaif PR is ready.

@zanyrenney thanks, I just want to point the same thing as @aimane-chnaif 😄

**Comment by zanyrenney** [comment] 2023-05-25 14:40
🙈

**Comment by zanyrenney** [comment] 2023-05-25 14:42
Oh no! let me try and resolve this!!

**Comment by zanyrenney** [comment] 2023-05-25 14:45
Just chatting internally about the best thing to do here.

**Comment by zanyrenney** [comment] 2023-05-25 14:59
Okay @bernhardoj and @aimane-chnaif - yep, we won't go the refund route, instead we will leave this with the payment done ahead of the PR being merged. I appreciate this is the incorrect order of things, so apologies.

When the PR is merged we can handle penalty or bonus. 

Assigning @laurenreidexpensify who will watch over this whilst I am out of office. 

the upwork issue is [here]([ttps://www.upwork.com/jobs/~01cc8b5696c56a0d6c](https://www.upwork.com/jobs/~01cc8b5696c56a0d6c))

C+ and contributor have been paid. 
Reporting bonus has not yet been paid. 

Thanks!

**Comment by laurenreidexpensify** [comment] 2023-06-07 10:48
Bonus payments issued to @aimane-chnaif @bernhardoj ✔️

Remaining Steps: 

- Waiting for @chiragxarora to accept offer in Upwork for reporting bonus so we can issue payment
- Waiting for @aimane-chnaif to confirm regression steps above

@zanyrenney I am OOO from tomorrow til 19 June so am going to unassign myself for you to cover those last 2 steps thanks

**Comment by chiragxarora** [comment] 2023-06-07 10:56
Accepted

**Comment by zanyrenney** [comment] 2023-06-09 14:35
@aimane-chnaif bump on the regression steps please so we can close this out.

**Comment by madmax330** [comment] 2023-06-12 08:51
Agreed I don't think we need regression steps for this

**Comment by chiragxarora** [comment] 2023-06-12 09:33
Release the payment @zanyrenney

**Closed** 2023-06-13 15:37 UTC
Labels: External, Daily, Awaiting Payment, Bug
