### ISSUE TITLE
[HOLD for payment 2024-06-13] CRITICAL: [P2P Distance] [$250] Add blue dot showing current location, and center-on-me button.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40209] opened 2024-04-13 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
There is no blue dot to show where the user is on the location in the map

## Solution:
Should see a "blue dot" where I am on the map when doing Track distance, along with a button to center the map on my location and orient the top to be North

## Context/Examples/Screenshots/Notes:

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712974874670609

Add any screenshot/video evidence

</details>

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4462a45d6a637d7</li>
        <li>Upwork Job ID: 1780349889093390336</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify / @kadiealexander</details>

**Comment by nkdengineer** [comment] 2024-04-14 06:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- New feature:  Add blue dot showing current location, and center-on-me button.
### What is the root cause of that problem?
### What changes do you think we should make in order to solve the problem?
- We can add the below component to [this](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/MapView/MapView.website.tsx#L199):
```
                  <Marker
                   
                        longitude={currentPosition?.longitude}
                        latitude={currentPosition?.latitude}
                    >
                        <View style={{backgroundColor: 'blue', width: 12, height: 12, borderRadius: 12}} />
                    </Marker>
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by shahinyan11** [comment] 2024-04-14 19:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add blue dot showing current location, and center-on-me button.
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
1. Add `GeolocateControl` component imported from `react-map-gl` in [here](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/MapView/MapView.website.tsx#L198C1-L199C77)
```
<GeolocateControl ref={geoControlRef} showAccuracyCircle={true} />
```
2. Add below `useEffect` in [MapView](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/MapView/MapView.website.tsx#L30) component
```
  useEffect(() => {
      // Activate as soon as the control is loaded
      geoControlRef.current?.trigger();
  }, [geoControlRef.current]);
```
### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2024-04-16 21:38
Couple of proposals ready for review @parasharrajat - this one is CRITICAL so please review asap, thank you!

**Comment by nkdengineer** [comment] 2024-04-17 10:12
@parasharrajat Thanks for your feedback. I updated the [proposal](https://github.com/Expensify/App/issues/40209#issuecomment-2053922914) to explain the results of the changes.

**Comment by shahinyan11** [comment] 2024-04-17 15:15
## Proposal
[Updated](https://github.com/Expensify/App/issues/40209#issuecomment-2054155551) Added videos for different platforms .
@parasharrajat The web package supports centering on user location functionality  but the native package not. And that's why I left the default UI for the `web` and use random icon for `native` just to show functionality. And since the description of the problem does not indicate a single icon, I did not pay attention to it

**Comment by nkdengineer** [comment] 2024-04-17 23:45
@parasharrajat I updated [alternative solution](https://github.com/Expensify/App/issues/40209#issuecomment-2053922914)

**Comment by shahinyan11** [comment] 2024-04-18 02:57
@parasharrajat Just note that @nkdengineer's alternative solution is taken from my comment above.

**Comment by nkdengineer** [comment] 2024-04-18 03:09
@shahinyan11 @parasharrajat I add the alternative solution to address the comment:
> just render it on the map using native controls

Both my primary and alternative solutions share the same concept of displaying the blue dot based on the [currentPosition](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/MapView/MapView.website.tsx#L52). The difference lies in how we implement it: in my primary solution, I use Marker, whereas in my alternative solution, I use Layer. As mentioned, the choice between Marker and Layer does not significantly impact performance, since we're only displaying a single dot. Performance concerns would arise if we were to display hundreds of dots.

**Comment by nkdengineer** [comment] 2024-04-18 03:27
> Just note that @nkdengineer's alternative solution is taken from my comment above.

I haven't had the chance to keep up with other contributors' comments. I've simply updated my proposal based on your latest one, and I've noticed that our main ideas are quite different. 
Additionally, since you mentioned using Layer to display a blue dot, I don't think it's accurate to say that my alternative was derived from yours

**Comment by bfitzexpensify** [comment] 2024-04-19 13:55
Just want to add some context from an internal discussion, this is the ideal behaviour:

Blue dot at current location + "center" button that either goes:
- To your location if there is no route
- To contain the current route if there is one

**Comment by nkdengineer** [comment] 2024-04-19 15:05
I update [proposal](https://github.com/Expensify/App/issues/40209#issuecomment-2053922914)

**Comment by shahinyan11** [comment] 2024-04-19 19:04
@parasharrajat No. @nkdengineer's solution for centering is good.

**Comment by nkdengineer** [comment] 2024-04-19 20:29
@parasharrajat Yeah. I tested and it will unzoom and center the map

**Comment by nkdengineer** [comment] 2024-04-19 20:52
I updated the proposal to add more detail about how can we get the ```bounds``` data.
Also, I am building the native app to make sure it works cross-platform. Will update the screenshot once done.

**Comment by nkdengineer** [comment] 2024-04-19 22:20
@parasharrajat I updated the evidence videos.

**Comment by quinthar** [comment] 2024-04-21 22:30
Is this assigned to @nkdengineer?  what is the ETA?  This is very urgent.  Thanks!

**Comment by bfitzexpensify** [comment] 2024-04-22 12:47
@pecanoro can you check this ASAP so @nkdengineer can get the PR submitted?

**Comment by pecanoro** [comment] 2024-04-22 16:21
I was assigned during the weekend, I was still getting through my daily notifications. Assigning @nkdengineer to solve the issue!

**Comment by bfitzexpensify** [comment] 2024-04-22 16:23
@nkdengineer please consider this as your top priority - thank you!

**Comment by nkdengineer** [comment] 2024-04-23 02:11
Sure. I am working on it

**Comment by nkdengineer** [comment] 2024-04-23 04:12
In the next 2 hours. I need to test a few cases

**Comment by nkdengineer** [comment] 2024-04-23 07:06
Can anyone give me a design for the "Blue dot" and "Center" button? @bfitzexpensify @pecanoro

**Comment by pecanoro** [comment] 2024-04-23 08:31
We can tag the design team in the PR and have them review it in case we need to make changes

**Comment by nkdengineer** [comment] 2024-04-23 09:18
@parasharrajat PR https://github.com/Expensify/App/pull/40759 is ready. I will fulfill the checklist once the design team supply the design

**Comment by pecanoro** [comment] 2024-05-16 18:19
Still in review!

**Comment by bfitzexpensify** [comment] 2024-05-30 22:50
Still in review. Adding a BZ buddy as I'll be OOO until June 11th.

**Comment by bfitzexpensify** [comment] 2024-06-14 15:55
Regression steps proposed in https://github.com/Expensify/Expensify/issues/404901

**Payment summary:**

$250 to @parasharrajat for C+ work to be paid via manual request
$250 to @nkdengineer for contributor work to be paid via Upwork

Previous posting is closed and I'm getting constant errors trying to post on Upwork. Will try again in a bit

**Comment by nkdengineer** [comment] 2024-06-14 17:17
@bfitzexpensify This is a `CRITICAL`-priority issue but it seems to miss the `High Priority` label,  could you help to add it same as [this case](https://github.com/Expensify/App/issues/40213#issuecomment-2093879555)

Thank you

**Comment by bfitzexpensify** [comment] 2024-06-17 10:51
Appreciate the clarification @nkdengineer. 

Payment summary updated, and job offer sent via Upwork

**Comment by nkdengineer** [comment] 2024-06-17 11:12
Thanks @bfitzexpensify I accepted the offer!

**Comment by bfitzexpensify** [comment] 2024-06-17 11:35
Payment complete, closing this one out. Thanks everyone!

**Closed by bfitzexpensify** 2024-06-17 11:35 UTC
Labels: External, Daily, NewFeature, Awaiting Payment, High Priority

**Comment by JmillsExpensify** [comment] 2024-07-02 13:20
$500 approved for @parasharrajat
