### ISSUE TITLE
[$500] Task-  [Delete message] shows only for the creator after cancel the task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27939] opened 2023-09-21 12:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 accounts on 2 browsers
2. Both accounts open chat together
3. User A create a task
4. User A click header to back chat report
4. User B open and cancel task
5. From user A Observe task preview disappears but user B still show task report on chat report

## Expected Result:
Deleted task] should show with both users after canceling the task

## Actual Result:
Only the user, who cancels the task see [Delete message]. 
Task preview disappears for users who are not the one who canceled the task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/97c758a6-4475-44ad-8f51-08ccf365fc12

https://github.com/Expensify/App/assets/93399543/84a947b2-2cd3-4d15-9294-72d9f181100b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695181722185619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132a403c700f46782</li>
        <li>Upwork Job ID: 1704836851861000192</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by kbecciv** [comment] 2023-09-21 12:46
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
After canceling the task, the task preview should show [Deleted task] for everyone, Who can access it.
### What is the root cause of that problem?
We are displaying TaskPreview through ReportActionView here:
https://github.com/Expensify/App/blob/c806bcabf0da05c46a5a606219bd95acc7dc3c19/src/pages/home/ReportScreen.js#L376-L383
https://github.com/Expensify/App/blob/c806bcabf0da05c46a5a606219bd95acc7dc3c19/src/pages/home/ReportScreen.js#L431-L436
We have a function to filter which reportActions can be displayed through:
https://github.com/Expensify/App/blob/c806bcabf0da05c46a5a606219bd95acc7dc3c19/src/libs/ReportActionsUtils.js#L450-L453
In function [shouldReportActionBeVisible](https://github.com/Expensify/App/blob/c806bcabf0da05c46a5a606219bd95acc7dc3c19/src/libs/ReportActionsUtils.js#L325C1-L353C1) We are filtering all reportActions that have been deleted https://github.com/Expensify/App/blob/c806bcabf0da05c46a5a606219bd95acc7dc3c19/src/libs/ReportActionsUtils.js#L349-L352
So when the task is canceled, TaskPreview will not be shown.
In owner task still shows deleted tasks because we have not set pendingAction = null in `successData`. So it has pendingAction = 'update'.
### What changes do you think we should make in order to solve the problem?
Here we should add the condition that if reportAction is a task then we will still display it:
```js
return !isDeleted || isPending || isDeletedParentAction(reportAction) || reportAction.childType === CONST.REPORT.TYPE.TASK;
```
Also, we should update pendingAction = null of action report after complete the API.
```js
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${parentReport.reportID}`,
            value: {
                [parentReportAction.reportActionID]: {
                    pendingAction: null,
                },
            },
        },
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by rojiphil** [comment] 2023-09-21 14:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a task is created between two users (say User A and User B) and the task is cancelled by one user (say User A), User A is displayed with `[Deleted task]` in Report Screen whereas User B does not see the `[Deleted task]` in the Report Screen 
Here, the expected behaviour does not seem like both the users should see `[Deleted task]`. Instead, I think, the expected behaviour seems to be that both users should not see `[Deleted task]`. I think, the additional reason why it should be deleted is that there is no motivation for the user to see the text `[Deleted task]`. The text itself does not give any value added information nor does the user have any actionable step with the `[Deleted task]` entry in Report Screen.

### What is the root cause of that problem?

When the Task Cancellation is initiated within `cancelTask` function, we set `pendingAction` to `update` [here](https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Task.js#L769). However, once the cancellation task is successfully done, we do not set back `pendingAction` to null. As the `pendingAction` is still not cleared, the [Deleted task] message keeps getting displayed in User A’s Report Screen. This is the root cause. Since `pendingAction` will be null for User B, User B will not be shown with [Deleted task] entry.  

### What changes do you think we should make in order to solve the problem?

We need to set the `pendingAction` back to null on success response from API as follows in [this location](https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Task.js#L830)

        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${parentReport.reportID}`,
            value: {
                [parentReportAction.reportActionID]: {
                    pendingAction: null,
                },
            },
        },

### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment] 2023-09-22 03:12
I wasn't able to recreate this, delete task shows for both users for me, but they do not have the same formatting. 

<img width="1058" alt="image" src="https://github.com/Expensify/App/assets/10925636/0228c2e4-5ae8-4eeb-9fa5-c1aab171a644">

I've posted on the OG bug report [post](https://expensify.slack.com/archives/C049HHMV9SM/p1695181722185619).

**Comment by rojiphil** [comment] 2023-09-22 03:21
> I wasn't able to recreate this, delete task shows for both users for me, but they do not have the same formatting.

@strepanier03 On User B account, please check the Chat Report Screen with User A. It seems you are looking at the Task Report on User B account.

**Comment by DylanDylann** [comment] 2023-09-22 05:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Delete task] shows only for the creator after cancel the task
### What is the root cause of that problem?
1. Firstly, we have an inconsistency: [Delete task] shows only for the creator after canceling the task. The root cause is that we are setting pendingAction in optimistic data for parentReportAction when canceling task
https://github.com/Expensify/App/blob/d0b49122d07ed51b974acce3981883e9b049a30c/src/libs/actions/Task.js#L812-L816
But we don't reset it in successData and failureData

2. Secondly, after making behavior consistency we aren't displaying [Deleted Task] in the chat
https://github.com/Expensify/App/blob/0e9a1c1b77cccb6de54d0484d2db3e3e4846b250/src/libs/ReportActionsUtils.js#L67-L69
This function only returns true if childVisibleActionCount > 0. It corrects with [Deleted message] but not right for [Deleted task]
### What changes do you think we should make in order to solve the problem?
1. Sure that we need to fix
Reset pendingAction for parentReportAction when canceling the task in successData and failureData
2. We need to confirm this case: when cancelling task, what we need to display in parent report action:
**Option 1: Always display [Deleted Task]** 
We need to update isDeletedParentAction like that:
```
    return lodashGet(reportAction, ['message', 0, 'isDeletedParentAction'], false) && (lodashGet(reportAction, 'childVisibleActionCount', 0) > 0 ||  lodashGet(reportAction, 'childtype', undefined) === 'task')

```
**Option 2: Only display [Deleted Task] if the count message of task report > 0 like we did with [deleted message]** 
With this approach, we need to update to calculate system message in childVisibleActionCount

**Option 3: Display nothing ** 
With this approach, we need to update for [deleted message]. If we agree this approach, I will detail it later
### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2023-09-27 11:18
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-09-29 09:37
Checking again

**Comment by abdulrahuman5196** [comment] 2023-09-29 10:22
@strepanier03 What is the expected behavior?

it seems we are intentionally not showing the [Delete message] message. What should we do for tasks?

Should we show the deleted message or should we not show it? What is the case for tasks with threaded messages?

**Comment by abdulrahuman5196** [comment] 2023-09-29 11:16
Thank you @namhihi237. Got it.

**Comment by abdulrahuman5196** [comment] 2023-09-29 11:23
@namhihi237 's proposal here https://github.com/Expensify/App/issues/27939#issuecomment-1729496386 looks good and works well as per the expectation.

@namhihi237 Can you post a proposal from your GH for reference?

🎀 👀 🎀
C+ Reviewed

**Comment by rojiphil** [comment] 2023-09-29 11:27
@strepanier03 @abdulrahuman5196

Can you please share your comment at this [proposal here too](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466). 
I think, the expected behaviour should be different i.e. we should not show [Deleted task]. 
Or, am I missing something here?

**Comment by abdulrahuman5196** [comment] 2023-09-29 11:53
@rojiphil The expected behaviour is to show the [Deleted task] message as per here https://expensify.slack.com/archives/C049HHMV9SM/p1695258831467899?thread_ts=1695181722.185619&cid=C049HHMV9SM

**Comment by rojiphil** [comment] 2023-09-29 12:06
> @rojiphil The expected behaviour is to show the [Deleted task] message as per here https://expensify.slack.com/archives/C049HHMV9SM/p1695258831467899?thread_ts=1695181722.185619&cid=C049HHMV9SM

@abdulrahuman5196  
Thanks for sharing the source of this decision. I was not aware of that. 
Can we wait until we have feedback from @strepanier03 and @thienlnam on my reasoning? 
I will resend my reasoning again for clarity.
I think, the RCA in [proposal here](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466) also seem to correctly explain why [Deleted task] does not disappear.

**Comment by rojiphil** [comment] 2023-09-29 12:09
@strepanier03 @thienlnam @abdulrahuman5196 

An excerpt from the problem statement description from [proposal here](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466)

> Here, the expected behaviour does not seem like both the users should see [Deleted task]. Instead, I think, the expected behaviour seems to be that both users should not see [Deleted task]. I think, the additional reason why it should be deleted is that there is no motivation for the user to see the text [Deleted task]. The text itself does not give any value added information nor does the user have any actionable step with the [Deleted task] entry in Report Screen.

Doesn’t this make sense? or am I missing something here?

**Comment by DylanDylann** [comment] 2023-09-29 12:13
@abdulrahuman5196 What do think about option 1 in [my proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473) I think it is more accuracy and avoid the same bug in other places

**Comment by abdulrahuman5196** [comment] 2023-09-29 14:14
> @abdulrahuman5196 What do think about option 1 in [my proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473) I think it is more accuracy and avoid the same bug in other places

It is more like a different/PR version of the accepted proposal. So I wouldn't able to consider it as a separate proposal.

**Comment by abdulrahuman5196** [comment] 2023-09-29 14:15
@flodnv Just to note: C+ accepted comment is here https://github.com/Expensify/App/issues/27939#issuecomment-1740734861

**Comment by DylanDylann** [comment] 2023-10-02 05:08
@flodnv @abdulrahuman5196 Just to note 

> It is more like a different/PR version of the accepted proposal. So I wouldn't able to consider it as a separate proposal.

The RCA is the logic of isDeletedParentAction function. If we don't fix that RCA, we can face this bug in other places. Whichever proposal is chosen, I think we still fix in isDeletedParentAction function as option 1 of [my proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473)

**Comment by thienlnam** [comment] 2023-10-02 08:08
Adding this here - but whichever direction we decide to go we should keep it consistent with threads.

So if there are no comments on the task report, we delete it entirely so it doesn't show the [Deleted task]

But if there are comments, we'll continue to show the [Deleted task] for all participants so you can open it and see the task thread

**Comment by abdulrahuman5196** [comment] 2023-10-02 08:16
@thienlnam Show **[Deleted task]** alwasy was the expectation i have approved. The expected proposal shows the [Deleted Task] always, regardless of other data based on your comment here https://expensify.slack.com/archives/C049HHMV9SM/p1695258831467899?thread_ts=1695181722.185619&cid=C049HHMV9SM

But if we want to change the expectation do let me know, I will re-check the proposals on the same. 

The expectation mentioned on your above comment is

**Only show [Deleted task] if there is any threaded message on the task**, Is this the new expectation?

**Comment by thienlnam** [comment] 2023-10-02 08:20
Ah yeah, my comment [here](https://expensify.slack.com/archives/C049HHMV9SM/p1695258831467899?thread_ts=1695181722.185619&cid=C049HHMV9SM) was more regarding the bug that if someone saw it then everyone should see it. But yeah please re-check the proposal that handle 

> Only show [Deleted task] if there is any threaded message on the task

and that if there is a threaded message on a deleted task, everyone can see the [Deleted task] in the parent reportAction

**Comment by abdulrahuman5196** [comment] 2023-10-02 08:24
Thank you @thienlnam for re-confirming. Will check on the proposals.

@flodnv Kindly do wait, I will re-check the proposals and do the needful accordingly.

**Comment by abdulrahuman5196** [comment] 2023-10-02 08:25
@DylanDylann Can you add more information on how you would achieve this option?

>Option 2: Only display [Deleted Task] if the count message of task report > 0 like we did with [deleted message]
With this approach, we need to update to calculate system message in childVisibleActionCount

**Comment by DylanDylann** [comment] 2023-10-02 08:26
Sure, update immediately

**Comment by rojiphil** [comment] 2023-10-02 13:32
> Adding this here - but whichever direction we decide to go we should keep it consistent with threads.

That goes well with my thought process as well. @thienlnam Thanks for the feedback.

**Comment by rojiphil** [comment] 2023-10-02 13:39
> @DylanDylann Can you add more information on how you would achieve this option?
> 
> > Option 2: Only display [Deleted Task] if the count message of task report > 0 like we did with [deleted message]
> > With this approach, we need to update to calculate system message in childVisibleActionCount

Also, curious to know on this.

**Comment by DylanDylann** [comment] 2023-10-02 13:57
Can't reproduce on lastest main

**Comment by abdulrahuman5196** [comment] 2023-10-03 15:07
@DylanDylann Still reproducible in main. Just now checked.

**Comment by rojiphil** [comment] 2023-10-03 16:54
@abdulrahuman5196
I am also looking at this issue currently. 
Can you please share the version that was used in the test video [here](https://github.com/Expensify/App/issues/27939#issuecomment-1745187901)?

**Comment by abdulrahuman5196** [comment] 2023-10-03 17:03
> @abdulrahuman5196 I am also looking at this issue currently. Can you please share the version that was used in the test video [here](https://github.com/Expensify/App/issues/27939#issuecomment-1745187901)?

@rojiphil Latest main branch at that time

**Comment by thienlnam** [comment] 2023-10-04 04:53
> This is behaviour currently I am seeing in main. For non-threaded task [Deleted task] message goes away after a while, I think this could be after the API call. IMO it seems weird.

> Could you check and let us know what is the expected behaviour in terms of task being deleted message? Is the current behaviour itself fine.

Yeah my guess is it that when the reportActions are re-fetched on a report, it ends up removing the deleted task with no thread. I agree it's kind of disrupting so I think the change we need to make here is on the front-end following that functionality (delete entirely if no threaded reports), and then possible an internal change to make sure other clients are updated as well when a task is deleted

**Comment by DylanDylann** [comment] 2023-10-04 05:11
@thienlnam You mean that we need to hide empty task report (that don't have any message) from LHN

**Comment by DylanDylann** [comment] 2023-10-04 05:19
[updated proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473)

**Comment by rojiphil** [comment] 2023-10-04 06:07
## Proposal

[Updated](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466)
@abdulrahuman5196 Kindly review

**Comment by rojiphil** [comment] 2023-10-04 10:37
> ## Proposal
> [Updated](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466) @abdulrahuman5196 Kindly review

Further updated the proposal and also added a test video for review.

**Comment by rojiphil** [comment] 2023-10-05 09:44
## Proposal

[Updated](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466) 
@abdulrahuman5196 
Updated the proposal to resolve flashing issue using `pendingAction`.
Kindly review

**Comment by abdulrahuman5196** [comment] 2023-10-05 11:58
Will re-review the proposals in my morning

**Comment by abdulrahuman5196** [comment] 2023-10-06 15:14
> @abdulrahuman5196. My proposal included a fix for the update set pendingAction: null. If we update expect to go with just deleting the entire task when deleting the message without any message, we just need to set pendingAction: null.

@namhihi237  Just setting pendingAction alone won't solve the issue. In fact its already added as part of this PR https://github.com/Expensify/App/pull/28211/files

**Comment by rojiphil** [comment] 2023-10-06 16:12
> I checked the network calls and the cancelTask call is not updating/removing the message, I think openReport is updating/removing the message.

@abdulrahuman5196 
I just tested after disabling `OpenReport`. I think, `cancelTask` API response is removing the message. 
Attaching test video for reference:

https://github.com/Expensify/App/assets/3004659/cec3842e-d6a0-449b-902b-9d4643e67db5

**Comment by DylanDylann** [comment] 2023-10-06 18:25
@abdulrahuman5196 [Updated proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473)

**Comment by rojiphil** [comment] 2023-10-07 08:14
## Proposal

[Updated](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466)

@abdulrahuman5196 
Updated solution for hiding canceled reports in LHN. Rest all remains the same.

**Comment by strepanier03** [comment] 2023-10-09 16:11
Proposals are being reviewed.

**Comment by abdulrahuman5196** [comment] 2023-10-10 16:31
TAL now

**Comment by abdulrahuman5196** [comment] 2023-10-10 17:22
@rojiphil 
I think setting the pendingAction to Delete is first step in fixing the issue. But I doubt we need to add child count check there itself. I was comparing with how chat messages are deleted since we want the same behaviour. 

For chat message we are blindly setting the Delete as pendingAction regardless of the child count. I think somewhere down the line during rendering, we are checking for childCount and deciding to render the message. We should do the same logic to solve our task cancel case as well.
https://github.com/Expensify/App/blob/2f60c2754a7bef69b86fe261c2f9cd73333e6f2e/src/libs/actions/Report.js#L1021

**Comment by DylanDylann** [comment] 2023-10-10 17:27
@abdulrahuman5196 Could you help to take a look [my proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473)

**Comment by abdulrahuman5196** [comment] 2023-10-10 17:35
> @abdulrahuman5196 Could you help to take a look [my proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473)

I missed to tag you as well in the above comment. 
At the moment, I am not super aligned to create new methods. Currently, I am checking how the deleting message is working and it would be better to do the same for task cancel as well. If you have information on the same do kindly provide the same.

**Comment by DylanDylann** [comment] 2023-10-10 19:07
@abdulrahuman5196 [Updated proposal](https://github.com/Expensify/App/issues/27939#issuecomment-1730825473) My update will explain why this problem doesn't happen with the normal thread message and propose the same way to fix

**Comment by abdulrahuman5196** [comment] 2023-10-11 09:55
@DylanDylann Thank you for the information. 
But I am not aligned on the solution suggested. Maybe we should make the optimisticReport of task cancel as `delete` and create a new function to check if the message has children and its of chat or task type and use in the `shouldHideOnDelete` function. This way both task and message will have the same flow.

Or any other way of refractor is also fine with me based on our current codebase.

**Comment by rojiphil** [comment] 2023-10-11 10:05
@abdulrahuman5196 
I have been having a look at this issue for the past couple of hours.
What do you think of this?

```
shouldHideOnDelete={ReportActionsUtils.isCreatedTaskReportAction(props.action) ?  (ReportUtils.isCanceledTaskReport({},props.action) && !ReportActionsUtils.isDeletedParentAction(props.action))
 : !ReportActionsUtils.isThreadParentMessage(props.action, props.report.reportID)
}
```

**Comment by rojiphil** [comment] 2023-10-11 10:18
@abdulrahuman5196 

## Proposal

[Updated](https://github.com/Expensify/App/issues/27939#issuecomment-1729683466) using `DELETE` instead of `UPDATE`

**Comment by rojiphil** [comment] 2023-10-11 10:25
> @rojiphil I think setting the pendingAction to Delete is first step in fixing the issue. But I doubt we need to add child count check there itself. I was comparing with how chat messages are deleted since we want the same behaviour.
> 

@abdulrahuman5196 

While I agree that `deleteReportComment` uses DELETE only, the approach of using DELETE or UPDATE is there in `deleteMoneyRequest` [here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/libs/actions/IOU.js#L1712). I have mentioned this as an alternate solution in the proposal.

**Comment by DylanDylann** [comment] 2023-10-11 10:57
@abdulrahuman5196 
1. In my proposal, I suggested creating new function to check isCancelledEmptyTaskReportAction. I see It is so difficult to create a function for both flows as you say here

> and create a new function to check if the message has children and its of chat or task type and use in the shouldHideOnDelete function. This way both task and message will have the same flow.

Because the logic to check in 2 flows is diferent

2. I also think about updating pendingAction === DELETE when canceling a task but I worry that It causes regression in other places. But If you see It is better, I will check carefully to avoid regression in PR phrase

**Comment by rojiphil** [comment] 2023-10-11 11:29
> This way both task and message will have the same flow.

@abdulrahuman5196 
imho, it is better not to have the same flow. `isDeletedParentAction` and `childVisibleActionCount` is also used actively by money request reports along with task and regular chat threads. So, it is better not to unify them as the implementation of these reports is not similar. Also, the implementation itself is not in a nascent stage. I think, the best is to have context-specific implementation here.

**Comment by abdulrahuman5196** [comment] 2023-10-14 07:43
**The current issue:** When we delete a task the message in the chat shows for sometime and disappears after that as mentioned in this comment https://github.com/Expensify/App/issues/27939#issuecomment-1745187901, @strepanier03 kindly do update the issue description outlining the same.

**For the fix:**
I like @rojiphil 's proposal here - https://github.com/Expensify/App/issues/27939#issuecomment-1729683466
First item is to make the optimistic data to have `delete`
Second item is to have the `shouldHideOnDelete` value updated to handle both chat thread and task with children. I would drive towards a common function for these. But we can see it in PR stage as well.


And there is an **extended fix** proposed by contributor to hide the Cancelled task from LHN which we don't show in the chat itself. IMO it seems to be another issue, since now even after server sync is successful, the deleted task is not removed from LHN. So I am not sure if its intentional or not, anyways I think it should be handled as a different issue. Correct me if wrong @thienlnam and want to handle it here. 


On the whole @rojiphil 's proposal here - https://github.com/Expensify/App/issues/27939#issuecomment-1729683466 looks good and works well. 
cc: @flodnv 

🎀 👀 🎀
C+ Reviewed

**Comment by DylanDylann** [comment] 2023-10-14 09:56
@abdulrahuman5196 how about my proposal? I find the root cause of problem first here https://github.com/Expensify/App/issues/27939#issuecomment-1756068564 . And @rojiphil update proposal based on my comment

**Comment by rojiphil** [comment] 2023-10-14 12:01
> I find the root cause of problem first here [#27939 (comment)](https://github.com/Expensify/App/issues/27939#issuecomment-1756068564) . After that @rojiphil updated the proposal based on my comment.

@DylanDylann 
As mentioned in my proposal, the root cause is that the `pendingAction` was set to `update` which was causing the problem. This was recorded in my proposal much before (i.e. on Oct 5) your comment was posted (i.e. on Oct 10/11). My initial proposal was to decide on using `update` or `delete` at the time of setting `pendingAction` value. 
But, then, @abdulrahuman5196  had the clarity to use `delete` pending action to align with the chat thread and wanted to adjust the logic accordingly. Here, I agree that you were the first to comment on `shouldHideOnDelete` which is also part of the solution. Anyways, as I understand, neither the root cause nor the primary solution of using `delete` came from you. In fact, even the condition used within `shouldHideOnDelete` is different. So, honestly, I am not sure if your statement is fully justified.

**Comment by rojiphil** [comment] 2023-10-15 20:24
> And there is an extended fix proposed by contributor to hide the Cancelled task from LHN which we don't show in the chat itself. IMO it seems to be another issue, since now even after server sync is successful, the deleted task is not removed from LHN. So I am not sure if its intentional or not, anyways I think it should be handled as a different issue. Correct me if wrong [@thienlnam](https://github.com/thienlnam) and want to handle it here.

@thienlnam  @abdulrahuman5196 

The reasoning for the extended fix is this. 
Currently, we hide the thread chat in LHN (I think to avoid clutter) when there is an empty deleted thread chat. 
Similarly, I think, we can hide a canceled task report in LHN with no child visible comments as it does not seem to have any meaningful existence in the LHN. Also, we are removing such canceled tasks from the chat report itself. So, it may be better to also avoid the clutter of such canceled tasks in LHN.  This also goes along with the approach of keeping chat threads and tasks as similar as possible. 
Also attaching a video to demonstrate this.

https://github.com/Expensify/App/assets/3004659/ab5f6943-aa1e-436c-821e-db5a34392285

**Comment by flodnv** [comment] 2023-10-16 12:24
@thienlnam what are your thoughts on the above? 

>we can hide a canceled task report in LHN with no child visible comments as it does not seem to have any meaningful existence in the LHN. 

This should be done in the backend though, right?

**Comment by thienlnam** [comment] 2023-10-17 18:02
> And there is an extended fix proposed by contributor to hide the Cancelled task from LHN which we don't show in the chat itself. IMO it seems to be another issue, since now even after server sync is successful, the deleted task is not removed from LHN. So I am not sure if its intentional or not, anyways I think it should be handled as a different issue. Correct me if wrong @thienlnam and want to handle it here.

There's a few issues that I've seen that have some related issue to the cancel task flow - but yeah we're updating the functionality so it aligns with threads where if you delete a task and there are no comments inside it then we just delete it from the view entirely. However, if there are existing comments we'll still show the [Deleted task] and the thread for it.

So I do agree with removing it from the LHN if there are no visible comments.

I _think_ this is being handled in a different PR though so yeah I don't think we need to address this here


> This should be done in the backend though, right?

Yeah ideally we also fix this in the back-end so it doesn't return deleted task reports

**Comment by abdulrahuman5196** [comment] 2023-10-17 18:06
Thank you for the confirmation. @flodnv Then I think we can proceed as per here https://github.com/Expensify/App/issues/27939#issuecomment-1762703334 if you have no objections.

**Comment by rojiphil** [comment] 2023-10-18 01:30
@abdulrahuman5196  @flodnv 

> I think this is being handled in a different PR though so yeah I don't think we need to address this here

I am bringing this to your notice so that we are all on the same page. 
The [PR here](https://github.com/Expensify/App/pull/28364) is for the display of [Deleted task] in LHN of the parent chat report when the task is canceled and there are visible actions left in the task report.
The improvement mentioned here is for the removal of LHN entry of the task report when the task is canceled and there are no more visible comments. 
These are both different.

**Comment by rojiphil** [comment] 2023-10-18 01:42
@abdulrahuman5196  @flodnv 

> So I do agree with removing it from the LHN if there are no visible comments.

> Then I think we can proceed as per here [#27939 (comment)](https://github.com/Expensify/App/issues/27939#issuecomment-1762703334) if you have no objections.

Just wanted to be doubly sure about the scope. Does the scope include the extended fix or it does not?

**Comment by thienlnam** [comment] 2023-10-19 21:47
We can do nothing right now since it's handle in a different PR. Not super motivated to handle in the BE right now but if / when we do, we should probably do it for all these reports because AFAIK muted chat report, deleted threads are all hidden via the FE currently

**Comment by rojiphil** [comment] 2023-10-20 01:33
> I am bringing this to your notice so that we are all on the same page.
> The [PR here](https://github.com/Expensify/App/pull/28364) is for the display of [Deleted task] in LHN of the parent chat report when the task is canceled and there are visible actions left in the task report.
> The improvement mentioned here is for the removal of LHN entry of the task report when the task is canceled and there are no more visible comments.
> These are both different.

@thienlnam 
Sorry, I should have addressed you as well in my comment above. As mentioned, the PR (I was the owner there) and the improvement here are both different. 

> We can do nothing right now since it's handled in a different PR. Not super motivated to handle in the BE right now but if / when we do, we should probably do it for all these reports because AFAIK muted chat report, deleted threads are all hidden via the FE currently

@flodnv @thienlnam 
We can do the improvement via another PR if we want to do nothing here. But, since it can be done in FE, wouldn't be better to add the improvement here as it would help us move faster?

**Comment by flodnv** [comment] 2023-10-20 11:51
I guess... thoughts @thienlnam ?

**Comment by thienlnam** [comment] 2023-10-20 18:23
Yeah I mean if you can add it as an improvement for the same PR here that would be great

**Comment by abdulrahuman5196** [comment] 2023-10-23 11:26
Not overdue just back from weekend update Melvin.
We are confirming on the alignment of the extended fix of LHN.

**Comment by flodnv** [comment] 2023-10-23 16:30
Ok so let's proceed like that

**Comment by rojiphil** [comment] 2023-10-25 14:42
@abdulrahuman5196 
Gentle bump on review of [PR here](https://github.com/Expensify/App/pull/30236)

**Comment by abdulrahuman5196** [comment] 2023-10-30 13:00
Hey sorry for the delay. Will close it out today.

**Comment by rojiphil** [comment] 2023-10-31 03:58
> Will close it out today.

@abdulrahuman5196 
Seems like you could not take this further yesterday
Is it possible to prioritize this today?

**Comment by abdulrahuman5196** [comment] 2023-10-31 03:59
Yes.

**Comment by flodnv** [comment] 2024-01-19 17:39
I have no idea 😅 do you, @thienlnam ?

**Comment by thienlnam** [comment] 2024-01-22 03:44
I thought the same, but can someone see if they can still reproduce? I just tested this and it seems to work as expected to me

**Comment by thienlnam** [comment] 2024-01-23 06:54
@flodnv I will take this over since it requires a back-end PR

**Comment by thienlnam** [comment] 2024-09-03 19:13
VSB is paused for the time being - so going to close and we can re-address once it's a priority again

**Comment by rojiphil** [comment] 2024-09-04 02:04
> VSB is paused for the time being - so going to close and we can re-address once it's a priority again

@thienlnam @strepanier03 Since the [PR](https://github.com/Expensify/App/pull/30236) was extensively worked upon for this issue, can we please consider compensation for this issue as per this [section](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit?pli=1#bookmark=id.wfm6lkgp0c6) in C+ process doc?

**Comment by abdulrahuman5196** [comment] 2024-09-23 15:24
> > VSB is paused for the time being - so going to close and we can re-address once it's a priority again
> 
> @thienlnam @strepanier03 Since the [PR](https://github.com/Expensify/App/pull/30236) was extensively worked upon for this issue, can we please consider compensation for this issue as per this [section](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit?pli=1#bookmark=id.wfm6lkgp0c6) in C+ process doc?

Gentle ping

**Comment by thienlnam** [comment] 2024-09-23 17:41
Looks like we can do partial compensation here - @strepanier03 could you please take care of that here?

**Comment by abdulrahuman5196** [comment] 2024-09-26 17:30
> Looks like we can do partial compensation here - @strepanier03 could you please take care of that here?

Seems as per latest update, after a PR is reviewed, its full compensation as per [C+ doc]( https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit?pli=1#bookmark=id.by6zfdtawcqn).

**Comment by mallenexpensify** [comment] 2024-09-26 18:39
Contributor: @rojiphil  paid $ via Upwork
Contributor+: @abdulrahuman5196  

can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021839373723506825459

**Comment by abdulrahuman5196** [comment] 2024-09-26 18:42
@mallenexpensify Accepted the offer. Thank you.

**Comment by namhihi237** [comment] 2024-09-26 18:45
@mallenexpensifyâcn i check how about with reporter since this issue create when the report issue still accept

**Comment by rojiphil** [comment] 2024-09-27 02:08
> can you please accept the job and reply here once you have?

@mallenexpensify Accepted the offer. Thanks.

**Comment by mallenexpensify** [comment] 2024-09-28 00:03
@namhihi237 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021839373723506825459

Apologies for missing that, crazy this issue is over a year old

**Comment by namhihi237** [comment] 2024-09-28 00:31
@mallenexpensify seems can not apply job, i apply but response not found

**Comment by mallenexpensify** [comment] 2024-10-01 22:40
@namhihi237 paid! Payment comment above is updated, thx all!

**Closed by mallenexpensify** 2024-10-01 22:40 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
