### ISSUE TITLE
[HOLD for payment 2023-06-13] Polish codes screen in managing 2FA in newdot

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#19180] opened 2023-05-18 08:29 UTC
### Problem

Here in the 2FA codes screen, we have Copy and Download buttons. We need to add an icon that turns into a check box and provides response that code has been copied or downloaded.
In the main PR, we discussed we'll make a follow up PR to address those issues as it requires updating main Button component.

<img width="377" alt="Screenshot 2023-05-18 at 1 47 45 PM" src="https://github.com/Expensify/App/assets/32012005/05ec53a2-6f95-4e28-ba33-b10609d37505">

### Solution

~Discuss design~ Done!
and Implement that.

We need to make our button component accept icons on the right hand side, and once pressed, turn that icons into a check icon indicating that the action succeeded.

Mockups here

https://user-images.githubusercontent.com/2319350/239196300-67a7d86f-79b3-41c6-ba5b-02b5b6af1d0c.png

### Why it is important

Provide proper response on user action is an important part of the UX
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a61f676ec916b6ec</li>
        <li>Upwork Job ID: 1670753035689127936</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment] 2023-05-18 08:31
@shawnborton can we please get thoughts on the design.
Also, keeping it daily for now. Feel free to bump it to weekly.

**Comment by shawnborton** [comment] 2023-05-18 09:26
Yup, let's just use buttons with icons and the copy icon can turn into a green check once it has been copied:
![image](https://github.com/Expensify/App/assets/2319350/67a7d86f-79b3-41c6-ba5b-02b5b6af1d0c)

**Comment by MonilBhavsar** [comment] 2023-05-18 09:44
Thanks! Should we only turn update copy button or download button too?
I would say both.

**Comment by shawnborton** [comment] 2023-05-18 09:50
Yeah, let's do both!

**Comment by MonilBhavsar** [comment] 2023-05-18 09:51
Thanks sounds good 👍

**Comment by BeeMargarida** [comment] 2023-05-18 11:17
Hi, Ana from Callstack here 👋 , as mentioned in Slack, I can pick this up!

**Comment by BeeMargarida** [comment] 2023-05-18 14:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Make the buttons in 2FA screens have an icon and change icons when they have been pressed

### What is the root cause of that problem?

There are two things that need change:

1. Fix an bug in `Button` where the `iconRight` is not being shown if no `icon` is provided
2. New component that uses `Button` and `WithDelayToggleButtonState` to allow changing the button icon and text when it has been pressed (similar to `CopyTextToClipboard` but more general and using `Button`)

### What changes do you think we should make in order to solve the problem?

1. Fix the bug in `Button`
   1. The conditional for `this.props.icon` should also include `this.props.shouldShowRightIcon`
   2. Should apply left margin for the right icon, pass the `iconStyles` and also apply the `small` prop to the right icon
2. Make a new component called `ButtonWithDelayToggle` that uses `WithDelayToggleButtonState` and allows passing a checked icon, style and text.

### What alternative solutions did you explore? (Optional)

We could go without a new component, but it would require implementing the delay toggle logic directly on the page.


https://github.com/Expensify/App/assets/25725586/1eadddfa-1643-47e9-96d9-07f0896ec3ba

**Comment by MonilBhavsar** [comment] 2023-05-18 14:33
@BeeMargarida thank you for the proposal. Looks good to me!
Just curious if we can reuse this component `src/components/ContextMenuItem.js`
As we are using this to copy user's personal details on "Details" page

**Comment by BeeMargarida** [comment] 2023-05-18 14:42
> @BeeMargarida thank you for the proposal. Looks good to me! Just curious if we can reuse this component `src/components/ContextMenuItem.js` As we are using this to copy user's personal details on "Details" page

Hum, we could refactor and make both `ContextMenuItem` and `CopyTextToClipboard` use the same base component that contains this logic and then use that same component in this use case.
A question that I have is if we want this new component to be based upon the `Button` component, or if it's alright to just use `Pressable` (like in `ContextMenuItem` and `CopyTextToClipboard`).

**Comment by BeeMargarida** [comment] 2023-05-18 14:42
> Just curious if we can reuse this component `src/components/ContextMenuItem.js` As we are using this to copy user's personal details on "Details" page

@MonilBhavsar Hum, we could refactor and make both `ContextMenuItem` and `CopyTextToClipboard` use the same base component that contains this logic and then use that same component in this use case.
A question that I have is if we want this new component to be based upon the `Button` component, or if it's alright to just use `Pressable` (like in `ContextMenuItem` and `CopyTextToClipboard`).

**Comment by MonilBhavsar** [comment] 2023-05-18 15:45
Sounds good to me 👍 
It is fine using Pressable. There is no necessary requirement to use Button component.

**Comment by BeeMargarida** [comment] 2023-05-18 15:55
Got it, I'll use pressable instead then. Do you want me to still fix the `iconRight` problem mentioned in the proposal?

**Comment by MonilBhavsar** [comment] 2023-05-19 06:22
Yes, let's fix it. We can then test it to avoid regression, to be safe.

**Comment by BeeMargarida** [comment] 2023-05-19 07:35
Got it, on it!

**Comment by BeeMargarida** [comment] 2023-05-22 09:18
@MonilBhavsar After checking better, I think migrating `ContextMenuItem` to this new component is probably not the best idea for several reasons:
- The component uses two components: `MenuItem` and `BaseMiniContextMenuItem` - this last one is the one that is similar to the new component and that obvious choice to migrate to the new component
- The `BaseMiniContextMenuItem` uses additional style for specific pressable state and does not always include the checked feedback logic
- The `BaseMiniContextMenuItem` is also used in another component `MiniQuickEmojiReactions`

What do you think?

**Comment by MonilBhavsar** [comment] 2023-05-22 14:34
I see. It makes sense to me. So we go with a new component, in your opinion?

**Comment by BeeMargarida** [comment] 2023-05-22 14:50
> I see. It makes sense to me. So we go with a new component, in your opinion?

A new component makes sense since it would require code duplication and usage of `withDelayToggleButtonState`. We can reuse that new component in `CopyTextToClipboard` as well

**Comment by MonilBhavsar** [comment] 2023-05-22 14:51
Sounds good to me 👍 Let's do it

**Comment by michaelhaxhiu** [comment] 2023-05-31 17:56
@MonilBhavsar and @BeeMargarida - is it fair to say you will handle this issue https://github.com/Expensify/App/issues/19459 as part of fixing this?

I'd like to close that bug if so.

**Comment by MonilBhavsar** [comment] 2023-06-05 15:19
@michaelhaxhiu yes, the issue will be fixed/or is fixed, as PR is merged

**Comment by shawnborton** [comment] 2023-06-19 11:10
What's the latest here team? Can we close this?

**Comment by MonilBhavsar** [comment] 2023-06-19 11:20
We need to issue payment to @rushatgabhane for reviewing a PR

**Comment by MonilBhavsar** [comment] 2023-06-19 11:21
@adelekennedy I added a bug-zero label as we need to issue payment to @rushatgabhane for reviewing PR.

**Comment by adelekennedy** [comment] 2023-06-19 18:45
@rushatgabhane sent offer!

**Comment by adelekennedy** [comment] 2023-06-21 20:57
contract sent just waiting it being accepted

**Comment by MonilBhavsar** [comment] 2023-06-29 06:22
Not overdue, waiting for @rushatgabhane to accept the contract.

**Comment by MonilBhavsar** [comment] 2023-07-03 13:11
@rushatgabhane 👋

**Comment by MonilBhavsar** [comment] 2023-07-03 14:46
Oh thanks! So I think we can close this out, correct?

**Comment by adelekennedy** [comment] 2023-07-03 17:33
This is new for me - let me see how this works

**Comment by adelekennedy** [comment] 2023-07-03 17:35
<img width="481" alt="Screenshot 2023-07-03 at 10 34 32 AM" src="https://github.com/Expensify/App/assets/60450566/64071685-b327-48f2-bd99-1327d28f21d2">
hmm - I don't think I have access, let me get clarity on how we're supposed to pay these out

**Comment by adelekennedy** [comment] 2023-07-03 18:04
@rushatgabhane do you mind resubmitting or posting your steps here? For some reason I can't access it!

**Comment by adelekennedy** [comment] 2023-07-05 02:15
thread started [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1688406080120749) waiting fro Anu and Jason to follow up on next steps

**Comment by adelekennedy** [comment] 2023-07-05 20:04
@rushatgabhane anu and jason will approve these! closing for now

**Closed by adelekennedy** 2023-07-05 20:04 UTC
Labels: Daily, Improvement, Awaiting Payment, Bug
