### ISSUE TITLE
[$250] Thread - Unable to upload photo for thread avatar from group chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40470] opened 2024-04-18 15:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Create a group chat.
4. Send a message in the group chat.
5. Right click on the message > Reply in thread.
6. Click on the thread header.
7. Click on the avatar > Upload photo.
8. Upload a photo.
## Expected Result:
If thread supports custom avatar, photo should be successfully uploaded. If not, there should not be an option to upload avatar.

## Actual Result:
After uploading photo, there is no changes in the thread avatar.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f9153b4c-6a7f-4626-8344-1e21b280c84a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017775876faefcb133</li>
        <li>Upwork Job ID: 1781032489627934720</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 0</li>
<li>eh2077 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-04-18 15:38
@sonialiap FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-04-18 15:38
We think this bug might be related to #vip-vsb

**Comment by marcaaron** [comment] 2024-04-18 18:49
>If thread supports custom avatar, photo should be successfully uploaded. If not, there should not be an option to upload avatar.

Threads don't support custom avatars.

This feels like something we should fix.

**Comment by marcaaron** [comment] 2024-04-18 18:50
@neonbhai your solution looks good. Can you get something up soon?

**Comment by marcaaron** [comment] 2024-04-18 18:51
@hayata-suenaga grabbing this from you since it's related to Group Chats.

**Comment by neonbhai** [comment] 2024-05-13 19:59
PR was merged and deployed to prod 3 weeks ago. Friendly bump to finish payments and close the issue 

cc: @sonialiap

**Comment by sonialiap** [comment] 2024-05-13 21:39
Thanks for the bump. Looks like melvin's automation didn't work here. Reviewing for payment now

**Comment by sonialiap** [comment] 2024-05-13 21:48
PR https://github.com/Expensify/App/pull/40563
No regressions 

Payment summary
- @neonbhai contributor - paid ✔️ 
- @eh2077 reviewer $250 - paid ✔️

**Closed by sonialiap** 2024-05-13 21:48 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
