### ISSUE TITLE
Android - Attachment - Unable to scroll PDF files in preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20879] opened 2023-06-16 00:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Click on the PDF file.
4. Scroll down the file.

## Expected Result:
User is able to swipe to scroll down the file.

## Actual Result:
User is unable to scroll down the file, unless pinching in while scrolling is performed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1b93a9f1-25fb-4ad3-86c0-951caa4241b2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2023-06-16 08:58
Looks like an exact dupe of https://github.com/Expensify/App/issues/20867

**Closed by Beamanator** 2023-06-16 08:58 UTC
Labels: DeployBlockerCash, Engineering, Hourly
