### ISSUE TITLE
[$1000] Web - Reply in thread - The parent message does not appear immediately

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20120] opened 2023-06-03 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Login with any account
3. Go to any chat
4. Send a message
5. Click on the message for opening the additional menu -> Reply in thread
## Expected Result:
The main message appears immediately

## Actual Result:
The main message is NOT appearing immediately

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.23-6

**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f7924d66-c575-42d6-ba75-3eba1cf0d435

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01971bf51adfe1fc4c</li>
        <li>Upwork Job ID: 1665804006809968640</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-06-05 19:33
I was able to repro this on MacOS/Chrome

**Comment by bernhardoj** [comment] 2023-06-06 05:21
I think it's already being handled here https://github.com/Expensify/App/issues/19490

cc: @s77rt

**Comment by s77rt** [comment] 2023-06-06 14:57
https://github.com/Expensify/App/pull/19580 has been merged. Is this still reproducible?

**Comment by stephanieelliott** [comment] 2023-06-07 16:05
Yeah, I am still able to repro it on both Chrome and Safari. When you click `Reply in thread`, there is still ~3-4 second delay before the message appears

**Comment by s77rt** [comment] 2023-06-07 16:08
Ah I see, I think this is a different issue then as the skeleton loader is not seen either

**Comment by abdulrahuman5196** [comment] 2023-06-09 13:21
@stephanieelliott I don't see this issue now. Could you kindly check and close if the issue is fixed?

**Comment by abdulrahuman5196** [comment] 2023-06-12 16:52
@stephanieelliott Could you check on this? https://github.com/Expensify/App/issues/20120#issuecomment-1584567362

**Comment by stephanieelliott** [comment] 2023-06-12 21:15
Unable to reproduce, will go ahead and close!

**Closed by stephanieelliott** 2023-06-12 21:15 UTC
Labels: External, Daily, Help Wanted, Bug
