### ISSUE TITLE
[$250]  LHN - Expense submitted offline doesn't appear in LHN.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48596] opened 2024-09-04 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customers):** biruknew45+624@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go offline
3. Click on the FAB > Enter a user you haven't previously chatted with > Select it
4. In the chat, click the plus button in the compose box
5. Submit an expense
6. Navigate back to the Inbox page and observe
7. Go online

## Expected Result:
When submitting an expense offline, it should appear in the Inbox with 50% opacity. Upon going online, it should update to 100% opacity

## Actual Result:
The expense does not appear in the LHN in the Inbox while offline and after going online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d7c5c6a5-a935-4a58-ba7a-07e07c5d9938

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833031002469120796</li>
        <li>Upwork Job ID: 1833031002469120796</li>
        <li>Last Price Increase: 2024-09-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment] 2024-09-04 20:39
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment] 2024-09-09 06:33
Nex up is proposal review

**Comment by greg-schroeder** [comment] 2024-09-12 18:23
Bump @mollfpr

**Comment by greg-schroeder** [comment] 2024-09-13 19:33
You around @mollfpr?

**Comment by greg-schroeder** [comment] 2024-09-16 07:57
Bump @mollfpr

**Comment by mollfpr** [comment] 2024-09-16 07:59
Sorry for the delay 🙏

Reviewing now!

**Comment by mollfpr** [comment] 2024-09-16 08:54
I can't reproduce the issue.

@dominictb Is it because `notificationPreference` is hidden in the report not show in the LHN?

>Issue should be fixed in BE as well.

What's BE fix we should apply?

**Comment by greg-schroeder** [comment] 2024-09-17 01:01
I am not sure - do you know @mollfpr? Or we can ask the team as a whole perhaps in Slack?

**Comment by mollfpr** [comment] 2024-09-17 06:29
I'm afraid I don't have a clue either, but I think the correct one should be data from BE.

> Currently, when creating a new conversation with a new email, the backend returns the notificationPreference as hidden (via report.participants.[accountID] data), but the frontend is setting it to always

@dominictb Does this mean that the preference got overridden on the FE? Could you still get the notification after the BE return hidden?

**Comment by mollfpr** [comment] 2024-09-18 08:03
@dominictb are you still able to reproduce the issue?

**Comment by greg-schroeder** [comment] 2024-09-23 03:07
What do you think of [this](https://github.com/Expensify/App/issues/48596#issuecomment-2357798287) @mollfpr ?

**Comment by greg-schroeder** [comment] 2024-09-25 19:20
Bump @mollfpr

**Comment by greg-schroeder** [comment] 2024-10-01 01:50
I'm going to close this as #vip-vsb is now paused and it doesn't really fit into #newdot-quality. Please reopen if you disagree.

**Closed by greg-schroeder** 2024-10-01 01:50 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
