### ISSUE TITLE
[$1000] Web - Chat - 'Uploading attachment' shows infinitely after reconnecting network

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20715] opened 2023-06-13 21:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a chat.
3. Go offline.
4. Upload a PDF file.
5. Refresh the page.
6. Reconnect network.
7. Wait for the page to refresh on its own.

## Expected Result:
PDF file is uploaded successfully.

## Actual Result:
PDF file is not uploaded. Uploading attachment is shown infinitely.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3cedf705-686b-4f05-9363-de438e4fad4d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f5b3ed320b84519</li>
        <li>Upwork Job ID: 1669105547092180992</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-06-14 22:12
Was able to repro

**Comment by spcheema** [comment] 2023-06-15 03:38
.

**Comment by petromoldovan** [comment] 2023-06-15 19:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
'Uploading attachment' message shows infinitely after reconnecting network. Document is not shown.

### What is the root cause of that problem?
ReportActionItem component is not updated when the network state is changing. Component is wrapped into React.memo that specifies the props changes in which trigger component update. The prop `network`(where network status is updated) is not one of them.

https://github.com/Expensify/App/blob/a2d074b1964d754b3dbf10fedee954e746670221/src/pages/home/report/ReportActionItem.js#L518-L530

It is important to fix it as it could potentially cause problems in other types of ReportActionItems.

### What changes do you think we should make in order to solve the problem?

I will add the following line to `memo` method:
```
lodashGet(prevProps.network, 'isOffline') === lodashGet(nextProps.network, 'isOffline')
```
I tested. Document appears as expected after the fix is applied.

### What alternative solutions did you explore? (Optional)
NA

**Comment by stephanieelliott** [comment] 2023-06-15 19:18
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @kadiealexander,  I'll grab this back from you when I return!

**Comment by kadiealexander** [comment] 2023-06-19 06:15
I'm also going OOO, sorry for the weird assignments team! @mallenexpensify thanks for keeping an eye on this for Steph!!

**Comment by petromoldovan** [comment] 2023-06-19 06:32
hello @eVoloshchak @mallenexpensify @grgia ! what do you guys think about my [proposal](https://github.com/Expensify/App/issues/20715#issuecomment-1593588779) 👀?

**Comment by eVoloshchak** [comment] 2023-06-19 17:06
@grgia, @petromoldovan's proposal looks good to me too

However, I do wonder if we should proceed with the fix since there are [plans](https://expensify.slack.com/archives/C049HHMV9SM/p1686573072745239?thread_ts=1684419239.615069&cid=C049HHMV9SM) to completely remove the "Uploading attachment" label 

> Yeah, [there’s an issue](https://github.com/Expensify/App/issues/9402#issuecomment-1270431340) for this improvement to replace that uploading attachment… string with a preview of the attachment. It has a long history, but it’s held on the improvements to image caching which is now in turn held on the server migration project

**Comment by bernhardoj** [comment] 2023-06-20 09:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Uploading attachment..." shows infinitely while uploading it offline and reloading the page. It's showing infinitely because the request is never retried after reloading. This also happens to every request, but it's just easier to reproduce it with an attachment because the attachment will show "Uploading attachment..." until it completes. To test the other cases like sending a plain message, you can verify the message does not get sent to the receiver side. Also, to test it on all platforms, simply send the attachment/message offline, then close and reopen the app. It's just the same as we reload the web app.

### What is the root cause of that problem?
When we initiate a request, it will get saved to PERSISTED_REQUEST Onyx and skipped if we are currently offline.
https://github.com/Expensify/App/blob/b274dbde740cebfee62246a48c7148512c31a368/src/libs/Network/SequentialQueue.js#L105-L112

PERSISTED_REQUEST: [AddAttachment]

Every time we reload/reopen/open the app, a new SendPerformanceTiming request is initiated from EmojiTrie.
https://github.com/Expensify/App/blob/b274dbde740cebfee62246a48c7148512c31a368/src/libs/EmojiTrie.js#L6-L35

We might expect that the SendPerformanceTiming will be appended to our current PERSISTED_REQUEST, but that's not the case here. When the SendPerformanceTiming request is initiated, the PERSISTED_REQUEST Onyx will only contain SendPerformanceTiming.

PERSISTED_REQUEST: [SendPerformanceTiming]

Why is that?

The answer lies in PersistedRequests itself.

When SendPerformanceTiming request is initiated, we will concat it with the current `persistedRequests` that is available from PERSISTED_REQUESTS Onyx and then set it as the new value.
https://github.com/Expensify/App/blob/b274dbde740cebfee62246a48c7148512c31a368/src/libs/actions/PersistedRequests.js#L21-L29

The problem is, `persistedRequests` is not "ready" yet. The `SendPerformanceTiming` is initiated earlier than the callback of the `Onyx.connect` here:
https://github.com/Expensify/App/blob/b274dbde740cebfee62246a48c7148512c31a368/src/libs/actions/PersistedRequests.js#L7-L12

So, the SendPerformanceTiming request will concat with an empty array because the data from Onyx is not ready yet, thus the previous AddAttachment (or any) request is lost.

### What changes do you think we should make in order to solve the problem?

Wait for PERSISTED_REQUESTS is ready before calling the SendPerformanceTiming request of EmojiTrie.

Details:
1. In PersistedRequests.js, add a new promise as we did in SequentialQueue:
https://github.com/Expensify/App/blob/b274dbde740cebfee62246a48c7148512c31a368/src/libs/Network/SequentialQueue.js#L12-L15
2. Call `resolveIsReadyPromise` inside the `Onyx.connect` callback
3. Create a "getter" (called `waitForReady`) that returns `isReadyPromise` and export it
4. In EmojiTrie, invoke `Timing.end` after the promise (`waitForReady`) is resolved:
`PersistedRequests.waitForReady().then(() => Timing.end(CONST.TIMING.TRIE_INITIALIZATION));`

### What alternative solutions did you explore? (Optional)
Wait for PERSISTED_REQUEST is ready before executing `save`, `remove`, and `getAll` function of PersistedRequests.js.

The first and second steps are the same as the main solution. In each function, wait for `isReadyPromise` to resolve, example:
**PersistedRequests.js**
```
function save(requestsToPersist) {
    return isReadyPromise.then(() => {
        HttpUtils.cancelPendingReconnectAppRequest();
        persistedRequests = ...
        Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequests);
    });
}
```

This will convert all 3 functions to a Promise, thus we need to chain the promise in all usage (usage in SequentialQueue) of those functions, for example:
**SequentialQueue.js**
```
function push(request) {
    PersistedRequests.save([request]).then(() => {
        if (NetworkStore.isOffline()) ...
        if (isSequentialQueueRunning) ...
        flush();
    });
}
```

**Comment by mallenexpensify** [comment] 2023-06-22 00:11
@eVoloshchak , please review @bernhardoj 's proposal 
https://github.com/Expensify/App/issues/20715#issuecomment-1598451082

**Comment by eVoloshchak** [comment] 2023-06-27 12:17
I think the issue description should be changed/or this issue put on hold and a new one opened, since the whole image uploading flow will be changed (https://github.com/Expensify/App/issues/9402), so "Uploading attachment" bug won't be present after that probably. 

@bernhardoj's [proposal](https://github.com/Expensify/App/issues/20715#issuecomment-1598451082) surfaced a bigger, more widespread problem, which I can reproduce. I'll post a review tomorrow, but this will also need a discussion on slack, since that's a pretty big change (I'll start one when I finish my own review)

**Comment by eVoloshchak** [comment] 2023-06-29 15:37
Huh, I can't reproduce this in both Safari and Chrome

https://github.com/Expensify/App/assets/9059945/fe045f51-8f3a-4053-8d75-1390d8e9d895

https://github.com/Expensify/App/assets/9059945/225f918c-3657-415b-aca0-c48759fb99e1




@stephanieelliott, could you please check if this is still reproducible?

**Comment by bernhardoj** [comment] 2023-06-29 15:52
I think the issue becomes unreproducible related to the app splash screen showing indefinitely after reload (there is a report of [this](https://expensify.slack.com/archives/C049HHMV9SM/p1688029383392899) and I experience it too). I'm guessing there is a recent change that somehow makes this issue unreproducible.

**Comment by grgia** [comment] 2023-07-03 14:13
@mallenexpensify @stephanieelliott how should we proceed if not reproducible anymore?

**Comment by mallenexpensify** [comment] 2023-07-04 19:34
Since @kbecciv reported it, if they're unable to reproduce then we should close it.   @kbecciv, adding you as assignee, can you test again please?

**Comment by grgia** [comment] 2023-07-10 15:48
^ is internal, I might try to get a volunteer to update the BE- I'm unlikely to get to this this week

**Comment by stephanieelliott** [comment] 2023-07-12 20:54
`^ is internal, I might try to get a volunteer to update the BE-`

@grgia I can try and help to source a volunteer -- what is `the BE`?

Maybe I am missing some context not on this issue, but since this is not reproducible anymore I think we should just close it, no? Do we need to update anything if no one is experiencing an issue?

**Comment by grgia** [comment] 2023-07-13 12:26
@stephanieelliott Yes I agree, closing!

**Closed by grgia** 2023-07-13 12:26 UTC
Labels: Engineering, Daily, Internal, Bug
