### ISSUE TITLE
[$250] Category rules - Description for Individual expense in "Flags amount over" is truncated

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48979] opened 2024-09-11 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Rules feature is enabled.

1. Go to staging.new.expensify.com
2. Go to Workspace settings > Categories.
3. Click on any category.
4. Click Flag amounts over.
5. Click Type.

## Expected Result:
The description for Individual expense should not be truncated.
We can compare this long description with "Smart Limit" description in Expensify Card > Limit type page, which is not truncated.

## Actual Result:
The description for Individual expense is truncated.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e236cbb3-decb-4f73-94a0-339288feff52

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834225539612184157</li>
        <li>Upwork Job ID: 1834225539612184157</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by IuliiaHerets** [comment] 2024-09-11 12:03
We think that this bug might be related to #wave-control

**Comment by etCoderDysto** [comment] 2024-09-11 12:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Description for Individual expense in "Flags amount over" is truncated
### What is the root cause of that problem?
We are not passing `isAlternateTextMultilineSupported` and alternateTextNumberOfLines={0} here
https://github.com/Expensify/App/blob/e9642dc7829f912bbb20be6c0d89b3e6529df7b6/src/pages/workspace/categories/ExpenseLimitTypeSelector/ExpenseLimitTypeSelectorModal.tsx#L61-L65
### What changes do you think we should make in order to solve the problem?
Pass `isAlternateTextMultilineSupported` and alternateTextNumberOfLines={0}
```
<SelectionList
                    sections={[{data: expenseLimitTypes}]}
                    alternateTextNumberOfLines={0}
                    ListItem={RadioListItem}
                    onSelectRow={(item) => onExpenseLimitTypeSelected(item.value)}
                    shouldSingleExecuteRowSelect
                    containerStyle={[styles.pt3]}
                    initiallyFocusedOptionKey={currentExpenseLimitType}
                    isAlternateTextMultilineSupported
                    ```

### What alternative solutions did you explore? (Optional)

**Comment by arosiclair** [comment] 2024-09-11 15:21
Looks like this was just implemented in https://github.com/Expensify/App/pull/48171. @WojtekBoman can you clean this up?

**Comment by WojtekBoman** [comment] 2024-09-12 06:28
Sure, I'll fix that :)

**Comment by VictoriaExpensify** [comment] 2024-09-24 05:21
@arosiclair - if this has been fixed [here](https://github.com/Expensify/App/pull/48171) are we ok to close this out?

**Comment by arosiclair** [comment] 2024-09-24 19:32
Yeah looks like that PR fixed both issues. Lets leave the other issue to issue payment for the review.

**Closed by arosiclair** 2024-09-24 19:32 UTC
Labels: Reviewing, External, Daily, Bug
