### ISSUE TITLE
[$250] BUG: Cannot see GL Accounts as an option in Sage Intacct NewDot Integration

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#45936] opened 2024-07-22 19:24 UTC
Testing doc: [here](https://docs.google.com/document/d/1AdHIz229Ze3BovRRR5YLW7nx8I2slf7greYkpV0SifI/edit?usp=sharing) (request, will share)

Pre-testing steps

- Make sure the email address does not already have existing workspaces/policies
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)
- Create a new collect policy on OldDot and; 
- Set the approval mode to “submit and approve”
- Enable scheduled submit with a frequency of `Daily` or “slower”
- Invite an additional user to the policy to play the member role in these testing flows
- Run the script stated [here](https://stackoverflowteams.com/c/expensify/questions/17518) to enable workspace chat creation for a paid plan.

Pre-testing steps

- Make sure that your test account is on the intacctOnNewExpensify beta
- Make sure you have Sage Intacct web services user ID, password and Company ID to initiate a connection
- Make sure you create a new workspace/policy for each test run
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)

Steps:
1. Head to Workspace settings
2. Head to Accounting
3. Under Sage Intacct Connection click `Import`

Expected result: you cannot disable GL Accounts (only when exporting as Vendor Bills)
Actual result: you do not see `GL Accounts`

Screenshot:
<img width="836" alt="Screenshot 2024-07-22 at 8 28 20 PM" src="https://github.com/user-attachments/assets/71afe277-609c-419f-94f3-73ec85ae56a1">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c8c9b57288ec553</li>
        <li>Upwork Job ID: 1815835911881380661</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by SzymczakJ** [comment] 2024-07-29 09:54
You can assign me as I was implementing this.
What is GL accounts @dylanexpensify? I don't see anything like this on Sage Intacct [design doc](https://docs.google.com/document/d/1k3ZFw8KB55yPUSCG6KYZlwpwEtmRt3eUshwxs7bZq5I/edit) or [figma](https://www.figma.com/design/qTudIfntotMj7ep1pBKXc1/%23wave-control%3A-Sage-Intacct?node-id=1-88&t=nUD6SvJWRERBJR3G-0)

**Comment by greg-schroeder** [comment] 2024-07-31 15:05
GL accounts can be synonymous with categories in many cases as we generally bring of the GL from accounting as categories

**Comment by SzymczakJ** [comment] 2024-07-31 16:23
So if the current UI matches Figma then this is not a bug? We just have a little different design. Also there's this [discussion](https://swmansion.slack.com/archives/C06ML6X0W9L/p1722353866378299?thread_ts=1722319775.851439&cid=C06ML6X0W9L) on Slack.

**Comment by JmillsExpensify** [comment] 2024-08-01 20:00
I don't see any bug for this issue. I think we should close it.

**Closed** 2024-08-02 13:27 UTC
Labels: External, Daily, Overdue, Bug
