### ISSUE TITLE
[$1000] Users list not showing on split confirm

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#19235] opened 2023-05-18 23:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This is a follow up issue from https://github.com/Expensify/App/pull/17349#issuecomment-1537823597

## Action Performed:
1. Open any group chat on web app
2. Click + icon > Split bill
3. Copy url from address bar (url should be like this format: `http://localhost:8080/split/new/xxx`)
4. Open desktop app
5. Paste url in new tab and open desktop app from popup
6. Enter any amount and click Next

## Expected Result:
User list is present

## Actual Result:
User list is missing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/96077027/212e466f-79c8-4663-93a0-18afffef70d3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aimane-chnaif 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108aaabc2bc8e4aeb</li>
        <li>Upwork Job ID: 1665886572966985728</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by amyevans** [comment] 2023-05-18 23:31
@jczekalski please comment on the issue so I can assign you

**Comment by jczekalski** [comment] 2023-05-19 10:20
@amyevans

**Comment by miljakljajic** [comment] 2023-05-23 08:55
Apologies - I have been at EC3 so only just getting to this today. I am OOO reapplying the label so that we can reproduce this - can we get some more detailed reproduction steps for the next BZ member @amyevans - I have tried to reproduce this using your comment above but I'm not able to. Can you break it down step by step for the next person?

I'll assign it to you for now and then can you reapply the label when you've updated the steps?  Thank you!

**Comment by kowczarz** [comment] 2023-05-25 14:41
Hey, I've also tried to reproduce it and I didn't manage to do so.

**Comment by amyevans** [comment] 2023-05-25 14:48
@aimane-chnaif are you able to clarify reproduction steps for this issue? Otherwise I'm going to close it out. Thanks!

**Comment by amyevans** [comment] 2023-05-25 23:25
FYI: I'll be OOO tomorrow and Monday.

**Comment by amyevans** [comment] 2023-05-30 15:33
Closing for now due to lack of reproducible steps, we can reopen if needed

**Comment by amyevans** [comment] 2023-05-31 14:32
Reapplied the `Bug` label to draft a BZ team member to handle reporter bonus payout (when the time comes).

**Comment by kowczarz** [comment] 2023-05-31 14:48
Yep I managed to reproduce the issue.

**Comment by mallenexpensify** [comment] 2023-06-06 01:01
@kowczarz any luck with the proposal? Added `External` to create the Upwork job.

**Comment by kowczarz** [comment] 2023-06-06 09:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users list not showing on split confirm

### What is the root cause of that problem?
In (`MoneyRequestModal` we are setting state)[https://github.com/Expensify/App/blob/main/src/pages/iou/MoneyRequestModal.js#L107-L111], that is acquired from onyx, but we are not setting any dependencies arrays to the local state, so if onyx state changes, the local state doesn't update.

### What changes do you think we should make in order to solve the problem?
We can add effect that will update the state if `report` or `personalData` props are updated. That will cause that as soon as users list will be fetched it will cause a re-render and it will be displayed on split confirm.

### What alternative solutions did you explore? (Optional)
NA

**Comment by amyevans** [comment] 2023-06-20 20:15
The PR is awaiting review from @aimane-chnaif 🙏

**Comment by mallenexpensify** [comment] 2023-06-30 03:15
@kowczarz and @aimane-chnaif , can you provide an update?  Is the issue not reproducible?

**Comment by mallenexpensify** [comment] 2023-07-05 23:54
Thanks @aimane-chnaif , for auditing purpose, if you think you are due payment, can you please provide reasoning and and what amount you believe you're due? Please use 25%, 50% or 100% for determining the amount. Thx

**Comment by mallenexpensify** [comment] 2023-07-12 01:14
@aimane-chnaif I don't see a 🎀 above, are C+ still using those?  It makes it easier to find approved proposals. 

I think compensation should either be 50 or 100% for C+, @amyevans , since you reviewed the PR, which do you think?

**Comment by amyevans** [comment] 2023-07-12 13:45
@mallenexpensify I think 50 makes sense here (plus the reporter bonus), there was certainly some effort involved but the PR didn't get through full review/testing prior to closing and there was only one proposal to evaluate as opposed to multiple

**Comment by mallenexpensify** [comment] 2023-07-14 22:01
Thanks @amyevans, @aimane-chnaif , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ef8163337d32b284

**Comment by mallenexpensify** [comment] 2023-07-17 20:31
@aimane-chnaif paid $750, thanks!

**Closed by mallenexpensify** 2023-07-17 20:31 UTC
Labels: External, Daily, Overdue
