### ISSUE TITLE
[$250] Tag - Tag list scrolls up when selecting a tag from the list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40410] opened 2024-04-18 09:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Collect workspace has a long list of categories or tags.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Start manual request flow.
4. Click Tag.
5. Select a tag from the list.
6. Click Tag again.
7. Quickly scroll down after opening tha Tag list.
8. Click on any tag.

## Expected Result:
The tag will be selected and app will redirect to confirmation page.

## Actual Result:
Tag list scrolls up instead.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0074fb2e-cd0d-4a3c-9014-4ef70be9fb70

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190130b274ac53836</li>
        <li>Upwork Job ID: 1781306795380563968</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>fedirjh | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-18 09:39
@miljakljajic I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 09:39
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-18 09:39
Production


https://github.com/Expensify/App/assets/115492554/c2394b0a-2a7a-43b6-b1c1-e7a241c291a1

**Comment by miljakljajic** [comment] 2024-04-18 16:58
@cristipaval do you agree this is a deploy blocker?

**Comment by roryabraham** [comment] 2024-04-19 00:22
this looks like a legit blocker to me

**Comment by cristipaval** [comment] 2024-04-19 13:03
I'm not sure what is the offending PR, I am investigating to see if [this one](https://github.com/Expensify/App/pull/39186)

**Comment by cristipaval** [comment] 2024-04-19 17:19
I'm suspecting [this PR](https://github.com/Expensify/App/pull/39201) as being the offending one. Still investigating.

**Comment by mountiny** [comment] 2024-04-20 20:38
I could not repro really, not sure if there has to be some specific minimum number of tags

**Comment by climax0916** [comment] 2024-04-21 20:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag - Tag list scrolls up when selecting a tag from the list

### What is the root cause of that problem?
The root cause of this problem is that the `onPress` event of the `BaseListItem` component is not triggered, while the `onMouseDown` event is. This occurs due to the possibility of parent components intercepting touch events or disrupting the propagation of the `onPress` event.

### What changes do you think we should make in order to solve the problem?
To mitigate this issue, I propose setting the `e.preventDefault()` for `onMouseDown` event handling. This action will effectively prevent ancestors from intercepting the touchable events of the component, thereby resolving the problem at hand. And that works well as you can see from attached file.


https://github.com/Expensify/App/assets/167291339/cecb46c5-34c1-45ba-a1f3-a2c56ae74df5

**Comment by cristipaval** [comment] 2024-04-22 07:57
I figured out that you don't have to scroll down quickly. You just need to scroll enough to make the selection from the top go out of the visible part of the component.

**Comment by WojtekBoman** [comment] 2024-04-22 08:00
I'm working on that

**Comment by cristipaval** [comment] 2024-04-22 08:00
Thanks a lot @WojtekBoman! 🙏

**Closed** 2024-05-06 12:34 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
