### ISSUE TITLE
[$250] Expense - Unable to create a new line in description field with SHIFT+ENTER

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48061] opened 2024-08-27 09:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Click + > Submit expense > Manual.
4. Enter amount > Next.
5. Click Description.
6. Enter some text, then press SHIFT+ENTER (enter key for mweb).

## Expected Result:
A new line will be created with SHIFT+ENTER.

## Actual Result:
A new line is not created with SHIFT+ENTER. The description is saved instead.

This issue happens in IOU, task and room description.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9ad442b1-da9f-4220-be89-ac6a407cc24e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140f764621c9cb74a</li>
        <li>Upwork Job ID: 1828427517631808725</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment] 2024-08-27 09:22
We think that this bug might be related to #wave-collect - Release 1

**Comment by Gonals** [comment] 2024-08-27 13:38
I don't think this needs to be a blocker, as it is a fairly minor bug.

@bernhardoj, I think this may have been caused by https://github.com/Expensify/App/pull/46172. Could you take a look?

**Comment by bernhardoj** [comment] 2024-08-27 13:40
I don't think it's caused by that PR since that's deployed to prod a month ago.

**Comment by s77rt** [comment] 2024-08-27 20:47
@bernhardoj Thanks for the proposal. I think this one should be fixed by the PR author given it's a new regression https://github.com/Expensify/App/pull/47705. cc @Krishna2323 @ZhenjaHorbach

**Comment by bernhardoj** [comment] 2024-08-28 02:13
Since the help wanted label is added, I think we can apply my solution instead of reintroducing deprecated ACCESSIBILITY_ROLE constant and also applying additional changes from my proposal.

**Comment by s77rt** [comment] 2024-08-28 15:54
@bernhardoj 

> Add "textbox" back to CONST.ROLE.

The `textbox` is not a valid role value according to [this list](https://github.com/facebook/react-native/blob/3077db32ef060aba85d9b56bd2a9f81a7afba985/packages/react-native/Libraries/Components/View/ViewAccessibility.d.ts#L339-L404)

> the live markdown input only accepts `accessibilityRole` props. Regarding this one, maybe we can update it to accept `role` instead

This makes sense but it won't fix the problem as if we do that now the role will be `presentation` and the enter shortcut will still not be disabled

**Comment by bernhardoj** [comment] 2024-08-28 16:07
> The textbox is not a valid role value according to [this list](https://github.com/facebook/react-native/blob/3077db32ef060aba85d9b56bd2a9f81a7afba985/packages/react-native/Libraries/Components/View/ViewAccessibility.d.ts#L339-L404)

Looks like it's different between RN and RN-web since [RN-web supports all ARIA roles](https://necolas.github.io/react-native-web/docs/accessibility/#:~:text=role%3A%20%3Fstring,to%20role.). Maybe on native, it's not explicitly needed to set the role to an input, similar to web where it's recommended to use input without any role.

> as if we do that now the role will be presentation and the enter shortcut will still not be disabled

Yes, that's why I suggest this.

> But actually, if we see the [doc](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role) here, it's mentioned that it's better to use input with type text or textarea instead of using role. The input in our app already uses those tags, except live markdown which needs to use a div with the role of textbox. So, it's better if we remove all role props from all input.

**Comment by s77rt** [comment] 2024-08-28 16:38
@bernhardoj If we remove the role prop from all input, including single-line inputs, then the enter key press won't be captured but it's needed in that case.

**Comment by s77rt** [comment] 2024-09-20 20:50
@kadiealexander @Gonals Let's close this. Fixed on https://github.com/Expensify/App/pull/48128

**Closed** 2024-09-25 08:51 UTC
Labels: Reviewing, External, Engineering, Monthly, Help Wanted, Bug
