### ISSUE TITLE
[$500] [MEDIUM] IOU report - Preview in LHN shows "This is beginning" instead of message after deleting request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33823] opened 2024-01-01 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Intenrnal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual
2. Create a manual request
3. Click on IOU preview to go to IOU report
4. Send a message
5. Click + > Request money
6. Create another manual request
7. Delete the latest request created in Step 6

## Expected Result:
The preview for IOU report in LHN shows the latest message

## Actual Result:
The preview for IOU report in LHN shows "This is the beginning of" instead of the latest messag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d2fb4771-6011-4345-8ba9-8ec0ec622663

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195409aa97ba1a78e</li>
        <li>Upwork Job ID: 1741890940222001152</li>
        <li>Last Price Increase: 2024-01-01</li>
    </ul>
</details>

**Comment by aim-salam** [comment] 2024-01-01 19:46
why I cant see Preview LHN?
@
![Uploading Screenshot 2024-01-02 at 3.45.20 AM.png…]()

**Comment by aim-salam** [comment] 2024-01-01 20:08
@gijoe0295 thank you :)

**Comment by jayeshmangwani** [comment] 2024-01-01 21:20
Issue seems to be from backend, 

1. when we call the `command=DeleteComment` for deleting comment, we get the `lastMessageHtml` and `lastMessageText` values from the response, like below:

<details>
  <summary>Server Response</summary>

``` 
{
    "key": "report_2351381375056893",
    "onyxMethod": "merge",
    "value": {
        "isEdited": false,
        "lastActorAccountID": 12863805,
        "lastMessageHtml": "hey",
        "lastMessageText": "hey",
        "lastVisibleActionCreated": "2024-01-01 20:07:04.922"
    }
},

```

</details>

2. when we call the `command=DeleteMoneyRequest` for deletion Request, we getting the empty values for the  `lastMessageHtml` and `lastMessageText` from the server response , from the frontend logic looks correct as we can see the the lastMessageText in LHN for a moment ,but after the server response we're getting empty values like below:


<details>
  <summary>Server Response</summary>
  
```
{
    "key": "report_2351381375056893",
    "onyxMethod": "merge",
    "value": {
        "chatReportID": "1471915178991979",
        "chatType": "",
        "currency": "INR",
        "description": null,
        "hasOutstandingChildRequest": false,
        "hasOutstandingIOU": true,
        "hasParentAccess": true,
        "iouReportID": null,
        "isCancelledIOU": false,
        "isDeletedParentAction": null,
        "isOwnPolicyExpenseChat": false,
        "isPinned": true,
        "isWaitingOnBankAccount": false,
        "lastActorAccountID": 12863805,
        "lastMentionedTime": null,
        "lastMessageHtml": "",
        "lastMessageText": "",
        "lastReadSequenceNumber": 0,
        "lastReadTime": "2024-01-01 20:40:28.944",
        "lastVisibleActionCreated": "2024-01-01 20:40:28.944",
        "lastVisibleActionLastModified": "2024-01-01 20:40:28.944",
        "managerID": 12863805,
        "nonReimbursableTotal": 0,
        "notificationPreference": "always",
        "oldPolicyName": "",
        "ownerAccountID": 12685245,
        "parentReportActionID": "1721506457813118433",
        "parentReportID": "1471915178991979",
        "participantAccountIDs": [
            12863805,
            12685245
        ],
        "policyID": "DF9EA7D78F88CD06",
        "policyName": null,
        "reportID": "2351381375056893",
        "reportName": "IOU",
        "stateNum": 1,
        "statusNum": 1,
        "submitterPayPalMeAddress": "jey62",
        "total": 28000,
        "type": "iou",
        "visibility": null,
        "visibleChatMemberAccountIDs": [
            12863805,
            12863805
        ],
        "welcomeMessage": "",
        "writeCapability": "all"
    }
},
```

</details>

**Comment by sabalach** [comment] 2024-01-02 04:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When following a specific sequence of actions mentioned in this issue, there's an issue observed in the Left Hand Navigation (LHN) preview. Instead of displaying the most recent message, the preview shows the text "This is the beginning of...". The aim is to resolve this problem by ensuring that the latest message content is reflected there.

### What is the root cause of that problem?
- On this file: `src/components/LHNOptionsList/OptionRowLHNData.js`, the `optionItem` object is being created on line 88, which contains the property `alternateText` which is returning the incorrect value `This is the beginning of your chat....` instead of the last message.
- The `SidebarUtils.getOptionData(...)` function is called to create the `optionItem` object.
- Looking at the definition of the `SidebarUtils.getOptionData`, it is calling `OptionsListUtils.getLastMessageTextForReport(report)` to get the last message text.
- Looking at the definition of `OptionsListUtils.getLastMessageTextForReport(...)`, I can verify that it is returning an empty string which is then handled by the `getOptionData` function which always returns `This is the beginning of your chat....` instead of the last message if an empty string is returned from `getLastMessageTextForReport` function.

### What changes do you think we should make in order to solve the problem?
Modifying the `OptionsListUtils.getLastMessageTextForReport(...)` function to return the last message contained in the `message[0].text` of the `lastReport` object instead of returning an empty string.

### What alternative solutions did you explore? (Optional)

**Comment by sabalach** [comment] 2024-01-02 05:00
Contributor details
Your Expensify account email: sabalachh@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01918256b311db937c

**Comment by sabalach** [comment] 2024-01-02 06:21
## Proposal
[Updated](https://github.com/Expensify/App/issues/33823#issuecomment-1873619910)

**Comment by rushatgabhane** [comment] 2024-01-02 19:57
@sabalach i need help here. Could you please help me understand why this issue isn't reproducible when deleting the request in offline mode?

**Comment by sabalach** [comment] 2024-01-02 23:13
> @sabalach i need help here. Could you please help me understand why this issue isn't reproducible when deleting the request in offline mode?

@rushatgabhane Sure here's what's happening:

When `?command=DeleteMoneyRequest` is called, the response from the server is as follows:
```json
{
  "key": "report_238980293449923",
  "onyxMethod": "merge",
  "value": {
    "chatReportID": "7700341779348851",
    "chatType": "",
    "currency": "CAD",
    "description": null,
    "hasOutstandingChildRequest": false,
    "hasOutstandingIOU": true,
    "hasParentAccess": true,
    "iouReportID": null,
    "isCancelledIOU": false,
    "isDeletedParentAction": null,
    "isOwnPolicyExpenseChat": false,
    "isPinned": false,
    "isWaitingOnBankAccount": false,
    "lastActorAccountID": 16193456,
    "lastMentionedTime": null,
    "lastMessageHtml": "",
    "lastMessageText": "",
    "lastReadSequenceNumber": 0,
    "lastReadTime": "2024-01-02 22:51:09.964",
    "lastVisibleActionCreated": "2024-01-02 22:51:09.964",
    "lastVisibleActionLastModified": "2024-01-02 22:51:09.964",
    "managerID": 16192928,
    "nonReimbursableTotal": 0,
    "notificationPreference": "always",
    "oldPolicyName": "",
    "ownerAccountID": 16193456,
    "parentReportActionID": "6113201632662045236",
    "parentReportID": "7700341779348851",
    "participantAccountIDs": [
      16192928,
      16193456
    ],
    "policyID": "D830C261E4EBF7B8",
    "policyName": null,
    "reportID": "238980293449923",
    "reportName": "IOU",
    "stateNum": 1,
    "statusNum": 1,
    "submitterPayPalMeAddress": "",
    "total": 10000,
    "type": "iou",
    "visibility": null,
    "visibleChatMemberAccountIDs": [
      16193456
    ],
    "welcomeMessage": "",
    "writeCapability": "all"
  }
}
```
Since `lastMessageText` is empty here, it causes the report object stored in the Onyx to have empty `lastMessageText` as well. But in offline mode, there is no response from the server hence the optimistic data is used instead.
Here's the optimistic data for the same report:
```json
{
    "onyxMethod": "merge",
    "key": "report_238980293449923",
    "value": {
        "type": "iou",
        "cachedTotal": "CA$100.00",
        "chatReportID": "7700341779348851",
        "currency": "CAD",
        "managerID": 16192928,
        "ownerAccountID": 16193456,
        "participantAccountIDs": [
            16192928,
            16193456
        ],
        "reportID": "238980293449923",
        "state": "SUBMITTED",
        "stateNum": 1,
        "statusNum": 1,
        "total": 10000,
        "reportName": "IOU",
        "notificationPreference": "always",
        "parentReportID": "7700341779348851",
        "lastVisibleActionCreated": "2024-01-02 06:02:04.370",
        "parentReportActionID": "6113201632662045236",
        "lastMessageText": "hello",
        "lastMessageHtml": "CA$88.00 request",
        "lastActorAccountID": 16193456,
        "lastReadTime": "2024-01-02 22:51:09.964",
        "maxSequenceNumber": 6,
        "chatType": "",
        "hasOutstandingChildRequest": false,
        "hasOutstandingIOU": true,
        "hasParentAccess": true,
        "isCancelledIOU": false,
        "isOwnPolicyExpenseChat": false,
        "isPinned": false,
        "isWaitingOnBankAccount": false,
        "lastReadSequenceNumber": 0,
        "lastVisibleActionLastModified": "2024-01-02 22:51:09.964",
        "nonReimbursableTotal": 0,
        "oldPolicyName": "",
        "policyID": "D830C261E4EBF7B8",
        "submitterPayPalMeAddress": "",
        "visibleChatMemberAccountIDs": [
            16193456
        ],
        "welcomeMessage": "",
        "writeCapability": "all",
        "hasDraft": false,
        "pendingFields": {},
        "errorFields": {},
        "isOptimisticReport": false,
        "lastMessageTranslationKey": ""
    }
}
```
As we can see here the optimistic data has the `"lastMessageText": "hello"` which is the last message. Thus in offline mode, this issue is not reproducible because the optimistic data has a value for `lastMessageText` whereas the response from the server has an empty value for it.

**Comment by rushatgabhane** [comment] 2024-01-02 23:22
> As we can see here the optimistic data has the "lastMessageText": "hello" which is the last message. Thus in offline mode, this issue is not reproducible because the optimistic data has a value for lastMessageText whereas the response from the server has an empty value for it.

@sabalach so can we conclude that this is a backend issue?

**Comment by sabalach** [comment] 2024-01-02 23:33
@rushatgabhane Yes if there's a correct response from the backend this issue should be fixed. However, some corrections on the frontend could also fix it but I believe that the better way is to fix it on the backend.
looking at the source code, on `/src/libs/OptionsListUtils.js` line `414`:
```js
    } else if (
        lastActionName === CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED ||
        lastActionName === CONST.REPORT.ACTIONS.TYPE.TASKREOPENED ||
        lastActionName === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED
    ) {
        lastMessageTextFromReport = lodashGet(lastReportAction, 'message[0].text', '');
    } else if (ReportActionUtils.isCreatedTaskReportAction(lastReportAction)) {
        lastMessageTextFromReport = TaskUtils.getTaskCreatedMessage(lastReportAction);
    } else {
        lastMessageTextFromReport = report ? report.lastMessageText || '' : '';
    }
    return lastMessageTextFromReport;
```
For actions like `CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED`, `CONST.REPORT.ACTIONS.TYPE.TASKREOPENED`, `CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED`, it is handled on the frontend.

**Comment by rushatgabhane** [comment] 2024-01-03 08:06
@sabalach thank you for the proposal.

🎀 👀 🎀 
Let's ask internal assignee if this is a backend/frontend bug

**Comment by sakluger** [comment] 2024-01-08 20:15
@Beamanator is traveling today.

**Comment by Beamanator** [comment] 2024-01-10 11:29
Yep this def is a backend bug... We're somehow getting the last action as the CREATED IOU action 👎

**Comment by Beamanator** [comment] 2024-01-10 12:04
Hmm the bug is in `OpenReport`, which could mean it's in `Report::getChats` which is a bit horrendous, so will take some time to debug. I don't think this is a daily, I'll make it weekly for now - i've got some other more important things to work on for now

**Comment by Beamanator** [comment] 2024-01-10 12:06
So far I've found that, after deleting the money request we can OpenReport [here](https://github.com/Expensify/Web-Expensify/blob/6b5703a13f2460e2241245c39d0e0cafe819befa/lib/ReportUtils.php#L2037), which has been returning the wrong "lastActionMessage" & "lastActionType" - I'm seeing it's returning an IOU type, even though I just deleted that one - I think the last "type" should be a standard report comment

**Comment by sakluger** [comment] 2024-01-15 19:18
I think this is a Wave 5, just asked in Slack so I can add to the correct project board.

**Comment by sakluger** [comment] 2024-01-23 23:47
Hey @Beamanator just confirming - are you able to work on this one? Or should we ask for another volunteer?

**Comment by Beamanator** [comment] 2024-01-24 11:06
I added hot pick a few days ago for some reason, i thought we posted in slack to see if others were interested, but it seems i didn't? 😅

**Comment by dylanexpensify** [comment] 2024-01-26 12:24
posting today!

**Comment by dangrous** [comment] 2024-01-30 19:49
I will try to look into this!

**Comment by dangrous** [comment] 2024-01-30 21:47
So I have determined where the issue is happening, but I'm trying to figure out the best solution

It's because of the query Report::getChats uses to pull the info for a report. Specifically, it's [getLastReportActionSubQuery](https://github.com/Expensify/Auth/blob/3b2263c480af478c26f90e1f20fdd03e9c853b8c/auth/lib/Report.cpp#L5903-L5929). It automatically includes any action that's not a chat. Since on deletion of a money request, all we’re doing is editing the html to be an empty string instead of removing it, then that still gets returned as the last action.

I think the best way to fix is to modify that query so that it doesn't return actions that are ious with blank html. I made a draft that seems to work okay but honestly I don't think it should (it in theory just filters out all IOUs... but in practice it seems to only filter out the empty ones, so I'm not sure how that's happening). So, work in progress, but should be able to get something up this week!

**Comment by dangrous** [comment] 2024-01-31 17:29
At @Beamanator's suggestion, asked for some help in Slack! https://expensify.slack.com/archives/C03TQ48KC/p1706722009797169

**Comment by dangrous** [comment] 2024-02-01 22:03
working on a PR!

**Comment by dangrous** [comment] 2024-02-05 15:15
PR is in review but need to figure out some bugs I introduced.

**Comment by dangrous** [comment] 2024-02-08 15:44
This should be fixed! Can we retest to confirm?

**Comment by sakluger** [comment] 2024-02-09 15:40
I added the retest-weekly label so QA can retest. Moving to weekly while we wait for them to retest.

@dangrous it looks like all the PR reviewers were internal. Will we need to pay @rushatgabhane or any other contributors for this one?

**Comment by rushatgabhane** [comment] 2024-02-09 16:28
that's right we can close this. no pay due

**Comment by mvtglobally** [comment] 2024-02-13 04:58
Issue not reproducible during KI retests. (First week)

**Comment by dangrous** [comment] 2024-02-13 15:28
I think we can go ahead and close this, if it's tested as good to go, right? Let me know if you disagree @sakluger, or if we should wait for another test.

**Comment by dangrous** [comment] 2024-02-21 15:48
I'm going to go ahead and close this given that it's no longer reproducible and no payment is needed, feel free to reopen or comment if needed!

**Closed by dangrous** 2024-02-21 15:48 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug, retest-weekly
