### ISSUE TITLE
 Able to input Special characters like %, $, #, @  in the rate field in a new UI

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19779] opened 2023-05-29 22:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a workspace and go to reimbursements
3. Go to the rate field and add special characters( except . and , which are needed) and notice that it allows to add special characters. (Previously, the rate field allowed only numbers in the previous UI). Even though it throws an error on entering special characters, but we shouldn't be allowed to enter such characters like that of the year field in calendar.
4. If we check the year field in the calendar, it only allows numbers and not even spaces.

## Expected Result: 
Special characters should not be allowed in the rate field (as it was earlier in the previous versions)
## Actual Result: 
Special characters like #, @, ^, &  are allowed in the rate field

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0f964490-55cf-4eb9-a832-e23e6a4ae201

https://github.com/Expensify/App/assets/43996225/d86edf6f-2313-4095-b57c-9b58992248fa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685091868689749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sethraj14** [comment] 2023-05-29 22:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Rate Input allows special characters in the rate field.

### What is the root cause of that problem?

No validation of rate input while text input, only checking on submit.

### What changes do you think we should make in order to solve the problem?

We can put validation on text input while the rate input is being changed and only allow the valid rate input.

Adding this code to this file - `src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js` will resolve the issue.

```javascript
  onChangeText={(rate) => {
                                    if (!rateValueRegex.test(rate) && Number.isNaN(this.getNumericValue(rate))) {
                                        this.setState({rate: ''});
                                    } else {
                                        this.setState({rate});
                                    }
                                }}
                                value={this.state.rate}
``` 

Working solution - 


### What alternative solutions did you explore? (Optional)

**Comment by bogoroh** [comment] 2023-05-30 01:59
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Rate Input allows special characters in the rate field.
> 
> ### What is the root cause of that problem?
> No validation of rate input while text input, only checking on submit.
> 
> ### What changes do you think we should make in order to solve the problem?
> We can put validation on text input while the rate input is being changed and only allow the valid rate input.
> 
> Adding this code to this file - `src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js` will resolve the issue.
> 
> ```js
>   onChangeText={(rate) => {
>                                     if (!rateValueRegex.test(rate) && Number.isNaN(this.getNumericValue(rate))) {
>                                         this.setState({rate: ''});
>                                     } else {
>                                         this.setState({rate});
>                                     }
>                                 }}
>                                 value={this.state.rate}
> ```
> 
> Working solution -
> 
>  Screen.Recording.2023-05-30.at.4.29.15.AM.mov 
> ### What alternative solutions did you explore? (Optional)

I wouldn't setState twice. I would just only set it if it's valid.

**Comment by sethraj14** [comment] 2023-05-30 05:53
@bogoroh Right will be implementing the optimized solution in the PR, this was just pseudo code for logic and issue explanation. Thanks for pointing this!

**Comment by strepanier03** [comment] 2023-05-30 22:54
Raised for discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1685487184419559).

**Comment by JmillsExpensify** [comment] 2023-05-31 02:10
Thanks @strepanier03!

**Comment by JmillsExpensify** [comment] 2023-05-31 02:11
I agree with @dhairyasenjaliya that this isn't a bug and now is more in line with our form framework.

**Comment by JmillsExpensify** [comment] 2023-05-31 16:21
Closing per this [slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1685487184419559).

**Closed by JmillsExpensify** 2023-05-31 16:21 UTC
Labels: Daily, Bug
