### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] Distance - Rate on confirmation page shows 3 decimal value for a 4-digit decimal value rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49929] opened 2024-09-30 13:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates
3. Click on any distance rate
4. Change the distance rate to 4-digit decimal value (non-zero) and save it
5. Go to workspace chat
6. Click + > Submit expense > Distance
7. Enter waypoints and proceed to confirmation page
8. Click Rate
9. Select the 4-digit decimal value rate in Step 4
10. Note that the rate list only shows 3 decimal value instead of 4
11. Submit the distance expense
12. Go to transaction thread and open the receipt
13. Note that the expense preview and distance receipt shows the complete rate which is 4-digit decimal value

## Expected Result:
In Step 10, the rate list should show the complete decimal value (eg, 1.2345)

## Actual Result:
In Step 10, the rate list only shows 3 decimal value (eg, 1.234)
In Step 13, the expense preview and distance receipt shows 4 decimal value which is the complete rate (eg, 1.2345)
The rate format is not consistent in the rate list and distance receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5e3c5ab5-93de-46b4-b012-47cb78559ad3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841311378926667676</li>
        <li>Upwork Job ID: 1841311378926667676</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 104470034</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander / @kadiealexander</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @kadiealexander</details>

**Comment by NJ-2020** [comment] 2024-09-30 14:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Rate on confirmation page shows 3 decimal value for a 4-digit decimal value rate
### What is the root cause of that problem?
Right here the Rate Decimal for displaying Rate is 3 which is wrong
https://github.com/Expensify/App/blob/0e3b82cc9d5e5425bf7dae5652538fdb494c7799/src/CONST.ts#L2402
And same here
https://github.com/Expensify/App/blob/decf5154ec7b08722d98e4c9124bfe673d30d405/src/libs/PolicyUtils.ts#L148
### What changes do you think we should make in order to solve the problem?
We should change it to 4
### Result

https://github.com/user-attachments/assets/a4f42c68-c603-4b63-bec2-5a33f1131b13

### What alternative solutions did you explore? (Optional)

**Comment by thelullabyy** [comment] 2024-10-01 04:13
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue.
We have an inconsistency in the number of decimal places for the distance rate.



### What is the root cause of that problem?
In this PR https://github.com/Expensify/App/pull/49773, we decided to always display 4 decimals for all currencies. But we haven't updated this function `getRateDisplayValue` function.





### What changes do you think we should make in order to solve the problem?
Update to display 4 decimals

https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/libs/PolicyUtils.ts#L149

```
        return Number(numValue).toFixed(CONST.MAX_TAX_RATE_DECIMAL_PLACES).toString().replace('.', toLocaleDigit('.'));
```

https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/libs/PolicyUtils.ts#L122

```
       return numValue.toFixed(CONST.MAX_TAX_RATE_DECIMAL_PLACES);
```

I see one more edge case when rate is 166.9800 (There are some zeros in the end), should we display zeros? Currently, we also display inconsistency in this case 

1. If yes, (we need to update how we display rates in the money request flow)

https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/libs/PolicyUtils.ts#L152

Remove `.substring(0, value.toString().length);`


2. If no, (we need to update how we display rates distance rate page)

https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/libs/CurrencyUtils.ts#L167

```
        minimumFractionDigits: 2,
        maximumFractionDigits: 4,
```

Another problem in the update rate message, the rate only display 2 decimals. But this data is get from originalMessage. If we want to update it, we need to fix on the BE side or make a workaround on FE (detail later if needed)

<img width="836" alt="Screenshot 2024-10-01 at 10 48 19" src="https://github.com/user-attachments/assets/a3ba269e-19b5-4bac-a8d0-d4b12e2ea727">


### What alternative solutions did you explore? (Optional)

**Comment by thelullabyy** [comment] 2024-10-01 04:29
Contributor details
Your Expensify account email: the.lullaby2@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011321051436417521

**Comment by thelullabyy** [comment] 2024-10-01 04:31
Contributor details
Your Expensify account email: the.lullaby2@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011321051436417521

**Comment by DylanDylann** [comment] 2024-10-03 04:00
@parasharrajat Hmm, In https://github.com/Expensify/App/pull/49773, we decided to mirror the Olddot behavior and always use a 4-digit decimal on the rate value. 

About this bug, I think this is a new requirement for the update distance rate on the request money flow to use of 4-digit decimals, because this issue also happens on the Olddot

https://github.com/user-attachments/assets/1d144d86-8e44-47fe-92e0-644a94b552cc

**Comment by DylanDylann** [comment] 2024-10-03 04:02
I just glanced at proposals and noticed that @thelullabyy mentioned a valuable point 

> I see one more edge case when rate is 166.9800 (There are some zeros in the end), should we display zeros? Currently, we also display inconsistency in this case

**Comment by ChavdaSachin** [comment] 2024-10-05 23:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Rate on confirmation page shows 3 decimal value for a 4-digit decimal value rate

### What is the root cause of that problem?
- On this PR https://github.com/Expensify/App/pull/49773#issue-2549802815 we decided to use 4 decimal digits for distance rate(irrespective of currency)
- We need some additional tough up for the change.

### What changes do you think we should make in order to solve the problem?

- First update `RATE_DECIMALS: 4`
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/CONST.ts#L2411
- Now update `fixedDecimalPoints` logic here, based on if we want to hide appending zeroes or not.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/PolicyUtils.ts#L149
- An additional problem we face after such update is for currency which do not support decimals.(ex. ALL)
<details><summary>check this video</summary>
<h4>parameter: currency- ALL, rate-0.6799, distance-74.59mil, from New York to New Jersey.</h4>

https://github.com/user-attachments/assets/c54cbe01-0385-498a-9baf-1ef5cb53f896


</details>

- When we display amount on report page we roundoff the amount according to currency. but when we try to edit the amount, edit amount page actually rips off the digits after decimal points for currencies which do not support decimals. which causes inconsistency between amount displayed on report page and amount displayed on edit amount page.


To solve this problem we need to start rounding off amount on IOUStepAmount instead of ripping of the digits after decimal point.
```js
        setNewAmount(Number(currentAmount).toFixed());
```
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/components/MoneyRequestAmountInput.tsx#L236

And some cleanup.
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by kadiealexander** [comment] 2024-10-08 03:17
@parasharrajat bump on the reviews!

**Comment by ChavdaSachin** [comment] 2024-10-10 20:04
@parasharrajat 
here in my [Proposal](https://github.com/Expensify/App/issues/49929#issuecomment-2395229730) I have mentioned an additional problem which will arise afterwards , If you think that issue is out of scope here, then we could raise a new issue for the same. Otherwise I request you to assign this issue to me or at least let me and @thelullabyy work here collaboratively.
cc. @puneetlath

**Comment by kadiealexander** [comment] 2024-10-14 23:35
@thelullabyy could you please provide an update here? Thank you!

**Comment by thelullabyy** [comment] 2024-10-15 08:08
@thelullabyy I'll open a PR soon.

**Comment by thelullabyy** [comment] 2024-10-15 08:08
@kadiealexander I'll open a PR soon.

**Comment by thelullabyy** [comment] 2024-10-15 10:28
@parasharrajat This [PR](https://github.com/Expensify/App/pull/50783) is ready for review.

**Comment by puneetlath** [comment] 2024-10-17 18:29
@allgandalf are you ok with splitting the C+ bounty since @parasharrajat already did the proposal review? If so, please go ahead.

**Comment by thelullabyy** [comment] 2024-11-14 05:24
@allgandalf I'll open the PR today.

**Comment by thelullabyy** [comment] 2024-11-15 11:08
@allgandalf [PR](https://github.com/Expensify/App/pull/52609) is ready for review.

**Comment by kadiealexander** [comment] 2024-12-12 04:42
Payments due ([50% reduction](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#regressions) due to [regression](https://github.com/Expensify/App/issues/52342)):

- [ ] Contributor: @thelullabyy paid $125 via Upwork (please apply!)
- [ ] Reviewer: @parasharrajat owed $62.50 via manual request (agreed to split [here](https://github.com/Expensify/App/issues/49929#issuecomment-2420249659))
- [ ] Reviewer: @allgandalf owed $62.50 via Upwork ([offer](https://www.upwork.com/nx/wm/offer/new/34585528?team=8577561)) (agreed to split [here](https://github.com/Expensify/App/issues/49929#issuecomment-2420249659))

@allgandalf or @parasharrajat please complete the [checklist](https://github.com/Expensify/App/issues/49929#issuecomment-2508969509)!

**Comment by JmillsExpensify** [comment] 2024-12-16 10:23
$62.50 approved for @parasharrajat

**Comment by kadiealexander** [comment] 2024-12-16 23:40
@parasharrajat @allgandalf please complete the checklist!

**Comment by kadiealexander** [comment] 2024-12-17 23:16
@parasharrajat @allgandalf @thelullabyy bump on the above please.

**Comment by thelullabyy** [comment] 2024-12-19 04:41
@kadiealexander Is it possible to send the offer to me? https://www.upwork.com/freelancers/~011321051436417521

Upwork requires Connects to apply which I don't have any.

Thank you in advance.

**Comment by kadiealexander** [comment] 2024-12-19 05:59
I've sent offers to @thelullabyy and @allgandalf, please let me know when you've accepted.

**Comment by thelullabyy** [comment] 2024-12-19 06:07
@kadiealexander I'm done too, thx

**Closed** 2024-12-19 06:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
