### ISSUE TITLE
 Error while uploading bmp file

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19502] opened 2023-05-23 22:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. upload bmp file

## Expected Result: 
should not show any error
## Actual Result: 
error appears and not able to upload bmp file
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f86c5858-64b1-4270-9632-4dbd41cbc9fd

https://github.com/Expensify/App/assets/43996225/168ddc3c-9495-45d5-9bd4-25a1fbc35bee

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684385464228429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2023-05-24 10:55
hey @kavimuru why have you said this is reproducible on staging / production? the reporter even noted this is fixed on production. Thanks!

**Comment by zanyrenney** [comment] 2023-05-24 10:57
Actually - regardless of if this is fixed, bmp is [not a supported file type](https://github.com/Expensify/App/blob/3780e0fe79a96bcfc86e1ac72e12814e5e981633/src/CONST.js#L16-L18):  

// Same as the PHP layer allows
        ALLOWED_EXTENSIONS: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'html', 'txt', 'rtf', 'doc', 'docx', 'htm', 'tiff', 'tif', 'xml', 'mp3', 'mp4', 'mov'],

**Closed by zanyrenney** 2023-05-24 10:57 UTC
Labels: Daily, Bug

**Comment by gadhiyamanan** [comment] 2023-05-24 11:00
@zanyrenney If bmp file is not allowed, in that case, we have to show below popup
![Screenshot 2023-05-24 at 4 29 06 PM](https://github.com/Expensify/App/assets/54790231/0dd494b1-1560-4c18-bc9e-dfda294d7720)

**Comment by zanyrenney** [comment] 2023-05-24 11:01
Cool, that would be a different issue though - if you can report that in the channel we can get it tested and written up to an issue.

**Comment by youssef-lr** [comment] 2023-05-24 12:01
We have started supporting all common filetypes, including `.bmp`, it looks like in this case we are failing to process BMP files in the backend while trying to create a thumbnail for them. I'll investigate this and report back here.

**Comment by youssef-lr** [comment] 2023-05-24 20:12
@kavimuru could you please attach the BMP image in this issue so I can test locally? I just tried with a few BMP images from https://filesamples.com/ and they worked.

**Comment by youssef-lr** [comment] 2023-05-25 13:58
@kavimuru the fix is live in staging, could you try again with the same file as in the recording?

**Comment by gadhiyamanan** [comment] 2023-05-25 13:59
@youssef-lr working for me

**Comment by youssef-lr** [comment] 2023-05-25 16:32
We can close this out once the fix is deployed to production.

**Comment by youssef-lr** [comment] 2023-06-09 22:00
@zanyrenney have we issued bug report payment for @gadhiyamanan?

**Comment by gadhiyamanan** [comment] 2023-06-10 01:52
@youssef-lr reporting bonus is pending

**Comment by zanyrenney** [comment] 2023-06-19 09:51
Will get an upwork job offer over to you asap @gadhiyamanan - there are some access issues with Upwork currently: **
![2023-06-19_10-50-52](https://github.com/Expensify/App/assets/56830058/32d33977-d20b-46ab-b2c2-b56771d9cade)
**

**Comment by zanyrenney** [comment] 2023-06-19 10:34
Job post here https://www.upwork.com/jobs/~01154c72fc516f5d28

@gadhiyamanan you've been invited for the reporting bonus.

**Comment by gadhiyamanan** [comment] 2023-06-19 10:34
@zanyrenney applied

**Comment by zanyrenney** [comment] 2023-06-19 10:36
please accept the offer @gadhiyamanan

**Comment by gadhiyamanan** [comment] 2023-06-19 10:36
@zanyrenney accepted, thanks!

**Comment by zanyrenney** [comment] 2023-06-19 14:06
Closing this out as its in Prod and reporting bonus is paid out.
