### ISSUE TITLE
Expense - Track expense button displayed instead of Submit when creating expense in self DM

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50826] opened 2024-10-15 18:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49.0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50239
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify/
and log in
2. Enable combinedTrackSubmit beta
3. Navigate to Self DM
4. Click on + > Create expense > Manual
5. Enter the amount and proceed to the next screen

## Expected Result:
The "Submit" button is displayed on the confirmation screen

## Actual Result:
The "Track expense" button displayed on the confirmation screen

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/29062a3a-187e-426f-9bb1-115fcde53562

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment] 2024-10-15 18:36
@grgia do you know what the behavior is supposed to be here? cc  @trjExpensify

**Comment by nkdengineer** [comment] 2024-10-15 18:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Track expense" button displayed on the confirmation screen

### What is the root cause of that problem?

In [here](https://github.com/Expensify/App/blob/4f1224cf21f3fa0aeb816b29eeb75d0935e5f035/src/components/MoneyRequestConfirmationList.tsx#L440), we are display button text  is `translate('iou.trackExpense')` for all cases

https://github.com/Expensify/App/blob/4f1224cf21f3fa0aeb816b29eeb75d0935e5f035/src/components/MoneyRequestConfirmationList.tsx#L440

### What changes do you think we should make in order to solve the problem?


We should display `translate('iou.submitExpense')` when `canUseCombinedTrackSubmit = true`


```
 const {canUseCombinedTrackSubmit} = usePermissions();

else if (isTypeTrackExpense) {
     text = canUseCombinedTrackSubmit ? translate('iou.submitExpense') : translate('iou.trackExpense');
}
```

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-10-15 19:01
yeah doesn't look like a deploy blocker.  We can wait for the confirmation on the behavior but I checked the code.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- We always show "Track expense" when using "Create expense".

### What is the root cause of that problem?

In `AttachmentPickerWithMenuItems` we're updating the text `text: canUseCombinedTrackSubmit ? translate('iou.createExpense') : translate('iou.trackExpense'),` based on the canUseCombinedTrackSubmit. The button is still track expense and hence the track flow is triggered.

https://github.com/Expensify/App/blob/e8a8c53c89de9644b855f718f663b61ef9110047/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx#L162-L166


### What changes do you think we should make in order to solve the problem?

In the `ReportUtils.ts` we should add the check for the permissions  when we check for isSelfDM.

```

if (isSelfDM(report)) {
    if (canUseCombinedTrackSubmit) {
        options = [CONST.IOU.TYPE.SUBMIT];
    } else {
        options = [CONST.IOU.TYPE.TRACK];
    } 
}

```

https://github.com/Expensify/App/blob/e8a8c53c89de9644b855f718f663b61ef9110047/src/libs/ReportUtils.ts#L6784-L6786








### What alternative solutions did you explore? (Optional)

**Comment by cead22** [comment] 2024-10-15 20:46
Thanks @paultsimura. Closing for now

**Closed by cead22** 2024-10-15 20:46 UTC
Labels: Engineering, Daily, Bug
