### ISSUE TITLE
[$1000] DEV: Console Error after changing language

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23201] opened 2023-07-19 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Settings -> Preferences -> Language
2. Change the language
## Expected Result: 
No Console Errors
## Actual Result: 
Console Errors

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Main
**Reproducible in staging?:** dev only
**Reproducible in production?:** dev only
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0a50f33f-5ea3-4260-952c-b162925c4542

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689622361234249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f609577c2c19546</li>
        <li>Upwork Job ID: 1686493417986031616</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26054368</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-07-20 21:06
@tienifr are you suggesting that we should consolidate this one into https://github.com/Expensify/App/issues/23208? Thanks for clarifying!

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 21:13
This is reported first we should handle it here!

**Comment by alexpensify** [comment] 2023-07-21 19:52
@Santhosh-Sellavel are you still able to replicate the experience? I tested in Chrome and my Console returns a different number of errors when changing the language. 

![image](https://github.com/Expensify/App/assets/8107070/fac80a3b-56c0-4e73-9423-163d435e18c5)

**Comment by Santhosh-Sellavel** [comment] 2023-07-21 19:59
Yes, this still happens to me try refreshing the page and changing the language, thanks!

**Comment by alexpensify** [comment] 2023-07-23 16:07
Ok, I'll need to test some more tomorrow.

**Comment by Santhosh-Sellavel** [comment] 2023-07-23 16:30
@alexpensifyFYI This can be seen only on Dev

**Comment by daordonez11** [comment] 2023-07-25 21:05
Hey this happens to me on first login in incognito window with a high traffic account. Also it happens after pressing sign out @alexpensify

**Comment by alexpensify** [comment] 2023-07-25 21:48
@daordonez11 are you on dev too or in prod?

**Comment by daordonez11** [comment] 2023-07-25 21:49
I'm on dev too, directly on localhost, since the console error is a props warning you can only see it on dev.

**Comment by alexpensify** [comment] 2023-07-26 21:48
@yuwenmemon - I need help here to test on Dev since I can't replicate on prod/staging. Thanks!

**Comment by alexpensify** [comment] 2023-07-27 15:50
@kaushiktd - this one is still under review. If it is confirmed, then a job will be created for it.

**Comment by kaushiktd** [comment] 2023-07-28 03:35
In that case here is my proposal if you guys decide to add bounty!

### Please re-state the problem that we are trying to solve in this issue.
DEV: Console Error after changing language

### What is the root cause of that problem?
1. `ReactDOM.render` is no longer supported in React 18.
This issue is related to core dependencies in the `node_modules` folder on below path after installing all dependencies.
node_modules/react-dom/cjs/react-dom.development.js line#86

2. Failed prop type: Invalid prop `priorityMode` of value `gsd` supplied to `SidebarLinks`, expected one of ["compact","default"].
3. Failed prop type: Invalid prop `forwardedRef` supplied to `withOnyx(Component)`.

### What changes do you think we should make in order to solve the problem?

For point 1, you need to comment out line#86 below file, or need to create a patch file.
node_modules/react-dom/cjs/react-dom.development.js line#86
Function.prototype.apply.call(console[level], console, argsWithFormat);

For Point 2, this error need to pass `priorityMode` value to be compact or default. You need to change in below file
https://github.com/Expensify/App/blob/main/src/pages/home/sidebar/SidebarLinksData.js#L93 replace with below code
priorityMode={priorityMode === CONST.PRIORITY_MODE.GSD ? CONST.OPTION_MODE.COMPACT : CONST.OPTION_MODE.DEFAULT} //code need to change
 
For Point 3, the issue occurs beacuse `forwardedRef` value is `null` to solve this issue you have create a variable and set it in `ref` in below file
https://github.com/Expensify/App/blob/main/src/components/withNavigationFocus.js
```
const ref = props.forwardedRef === null ? false : props.forwardedRef;
return (
<WrappedComponent
// eslint-disable-next-line react/jsx-props-no-spreading
{...props}
ref={props.ref}//add here
isFocused={isFocused}
/>
);
```

### Video:
https://drive.google.com/file/d/1pVZy925RkNQrAwtO5MFpWTBA2KDkhGwD/view?usp=drive_link

**Comment by alexpensify** [comment] 2023-07-28 20:53
@yuwenmemon - were you able to test this one on Dev? Thanks!

**Comment by alexpensify** [comment] 2023-07-31 22:54
@MonilBhavsar - I need help testing on DEV. Yuwen is OOO until mid-August and don't want to delay this one. Thanks for helping test here!

**Comment by MonilBhavsar** [comment] 2023-08-01 09:53
Reproducible on dev. If this is recently introduced, then I think we can ask the author to make a follow up fix.

**Comment by alexpensify** [comment] 2023-08-01 21:46
Thank you @MonilBhavsar for confirming! I've added the external label. @mananjadhav can you please review the proposals and identify if one will correct the issue here? Thank you!

**Comment by mananjadhav** [comment] 2023-08-02 05:26
Allow me a day to review. I'll reproduce, check the console errors and then review the proposals. Thanks for the patience here.

**Comment by alexpensify** [comment] 2023-08-02 17:04
Thank you @mananjadhav for the update!

**Comment by mananjadhav** [comment] 2023-08-02 20:15
Was assigned only yesterday. I'll take a look at the issue tomorrow.

**Comment by mananjadhav** [comment] 2023-08-03 18:33
Okay so I tried reproduce this. I don't think we should be fixing `Warning: ReactDOM.render is no longer supported in React 18.` error.

I don't see the second console error about `priorityMode`.

But I see two errors `forwardedRef` for `withOnyx` and `wihNavigation`. @kaushiktd Could you explain why these references are null? and could've have updated references instead of handling these `false`?

**Comment by kaushiktd** [comment] 2023-08-04 03:45
Sure, @mananjadhav 

```
const ref = props.forwardedRef === null ? false : props.forwardedRef;
return (
<WrappedComponent
// eslint-disable-next-line react/jsx-props-no-spreading
{...props}
ref={props.ref}//add here
isFocused={isFocused}
/>
);
```

We cannot give any other value than props to the ref variable, and it returns null by default. If we try to send a static value, we get issues, thus to address this problem, we need to set the value to false if the value is null, else the value of `props.ref` receives `forwardedRef`.

**Comment by alexpensify** [comment] 2023-08-06 16:59
@mananjadhav when you get a chance, can you please review the updated proposals? Thanks!

**Comment by mananjadhav** [comment] 2023-08-06 18:17
Thanks for the proposal @tienifr. Your [proposal](https://github.com/Expensify/App/issues/23201#issuecomment-1666372780) looks good. 


🎀 👀 🎀 C+ Reviewed.

**Comment by kaushiktd** [comment] 2023-08-07 05:03
@mananjadhav I recently tested the above proposal by tienifr. Changed the `forwardedRef` value in both `withOnyx.js` and `withNavigation.js`, it is not working and continues to produce the problem. See here,
https://drive.google.com/file/d/1MPDMGTqigiB-2ceXt9ECntNkgK0FymQt/view?usp=sharing

If you change the `withNavigation.js` file, you may get issues in other files. 

In this case, the `forwardedRef.current` value is null and does not satisfy the criterion that `PropTypes` is any object or anything else, so we must check the condition listed below, as indicated in my proposal.
https://github.com/Expensify/App/issues/23201#issuecomment-1654939786

**Comment by kaushiktd** [comment] 2023-08-07 05:27
I've already check with re build dist folder. It didn't work still for me.

**Comment by kaushiktd** [comment] 2023-08-07 08:16
In your attached video files, you erased all console logs before changing languages to hide the error. You need to reload the page and check again without clearing any current errors. The error will be displayed.

**Comment by alexpensify** [comment] 2023-08-08 23:17
@deetergp - can you please review the proposal and the feedback? Thanks!

**Comment by hayata-suenaga** [comment] 2023-08-09 17:04
I haven't read this issue so closely but seems like the fix for [this issue](https://github.com/Expensify/App/issues/22929#issuecomment-1671765166) might fix this one too

**Comment by hayata-suenaga** [comment] 2023-08-09 18:05
> How about @kushu7 fixing react-native-onyx and @tienifr fixing app console errors?

@aimane-chnaif yes I agree we can do that

**Comment by deetergp** [comment] 2023-08-09 23:04
> How about @kushu7 fixing react-native-onyx and @tienifr fixing app console errors?

I agree, that sounds like a good plan 👍

**Comment by alexpensify** [comment] 2023-08-10 16:56
@mananjadhav, @deetergp, and @hayata-suenaga - please confirm who we are assigning this GH to or are we putting it on hold until https://github.com/Expensify/App/issues/22929 is in production? Thanks!

**Comment by hayata-suenaga** [comment] 2023-08-10 17:10
@aimane-chnaif so I should assign @tienifr in #22929 too with @kushu7 ?

**Comment by hayata-suenaga** [comment] 2023-08-10 17:12
thank you for the confirmation 🙂 are we closing this issue?

**Comment by hayata-suenaga** [comment] 2023-08-10 17:14
sorry wrong issue assigning Tienifr to the other issue https://github.com/Expensify/App/issues/22929

**Comment by hayata-suenaga** [comment] 2023-08-10 17:17
sorry sorry this is a mistake 🙇 @tienifr please go to https://github.com/Expensify/App/issues/22929 I assigned you there

**Comment by alexpensify** [comment] 2023-08-12 16:19
@mananjadhav and @deetergp - it looks like the party is happening in https://github.com/Expensify/App/issues/22929, let me know if you agree with @aimane-chnaif and I'll close this one. Thanks!

**Comment by mananjadhav** [comment] 2023-08-13 11:32
Looks like yes it would be fixed with #22929.

**Comment by deetergp** [comment] 2023-08-14 17:13
Agreed! I think we can go ahead and close this one out.

**Closed** 2023-08-16 18:49 UTC
Labels: External, Engineering, Daily, Bug

**Comment by alexpensify** [comment] 2023-08-16 19:00
I've closed the job in upwork too

**Comment by alexpensify** [comment] 2023-08-21 16:23
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - N/A 
-  Contributor+ that helped on the issue and/or PR - @mananjadhav $500 

Upwork Job: N/A 

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There was a discussion here: https://expensify.slack.com/archives/C02NK2DQWUX/p1692376106935809. @mananjadhav was part of the review process and there should be a partial payment for the reviews. 

cc: @JmillsExpensify and @anmurali

**Comment by JmillsExpensify** [comment] 2023-08-24 05:36
Reviewed the details for @mananjadhav. $500 approved for payment via NewDot.
