### ISSUE TITLE
Expense - submitted $0.00 is shown when submitting expense in OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48598] opened 2024-09-04 21:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4919013
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: Create a workspace with Workflows enabled and Delay submission set to Manually
1. Navigate to a workspace chat as employee in ND
2. Create an expense
3. Go to OD > reports > summit the expense create in step 2
4. As the employee in NewDot - Navigate to the workspace chat
5. Click on the submitted report

## Expected Result:
System message that reads: “submitted %reportTotal%”

## Actual Result:
System message that reads: “submitted $0”

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/17d03f00-59ae-4541-a754-cc593b4dcae0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2024-09-09 20:45
Looks like a dupe of https://github.com/Expensify/App/issues/48107

**Comment by Beamanator** [comment] 2024-09-09 20:47
agreed

**Comment by youssef-lr** [comment] 2024-09-09 20:51
yeah we can close this, PR should be merged soon.

**Closed by youssef-lr** 2024-09-09 20:51 UTC
Labels: Daily, Overdue, Bug
