### ISSUE TITLE
[HOLD for payment 2022-05-25][$1000] Non-unique keys React warning. Possibly related to RenderHTML ?

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#8655] opened 2022-04-15 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Build the app on dev in iOS

## Expected Result:
1. No console warnings are seen

## Actual Result:
1. Console is complaining with this:

![2022-04-15_11-56-20](https://user-images.githubusercontent.com/32969087/163637810-cf958303-000f-438e-a8ca-ff25dc29a950.png)

## Workaround:

Yes. This doesn't seem to affect app performance, but may indicate a serious problem.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** Pretty sure the warning is silenced there.
**Reproducible in production?:** Pretty sure the warning is silenced there.
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-04-18 22:11
Wow, interesting find. Posted the upwork job here for proposals: https://www.upwork.com/jobs/~01e7b5db822c3f7489

**Comment by muas19** [comment] 2022-04-22 11:46
Where is this happening?

**Comment by parasharrajat** [comment] 2022-04-22 16:15
This is what needs to be debugged and solved.

**Comment by JmillsExpensify** [comment] 2022-04-25 01:36
Doubling price to $500.

**Comment by eVoloshchak** [comment] 2022-04-26 17:38
1. I'm unable to obtain [logs](https://stackoverflow.com/c/expensify/questions/4856) without the `@expensify` e-mail. Is there a way to register such an email to get access to logs?
2. If it's possible, could we get screenshot/video of full Component Stack?

**Comment by JmillsExpensify** [comment] 2022-05-02 15:16
Doubling the price to $1000.

**Comment by eVoloshchak** [comment] 2022-05-02 15:18
I was able to reproduce this problem when chat contains a message with two (or more) code blocks with the line break between them. For example, if you paste and send the following into the composer:
![Screenshot from 2022-05-02 13-51-47](https://user-images.githubusercontent.com/9059945/166226614-f4344471-9d7b-4db8-9545-f38f6b6d0876.png)


The problem occurs inside the [renderChildren](https://github.com/meliorence/react-native-render-html/blob/cfc10e3151b519f7df27e1e1c6b2e83cba849874/packages/render-html/src/renderChildren.tsx#L40) function of `react-native-render-html`. It calls [mapCollapsibleChildren](https://github.com/meliorence/react-native-render-html/blob/cfc10e3151b519f7df27e1e1c6b2e83cba849874/packages/render-html/src/renderChildren.tsx#L9) function for every child, inside of which every child is assigned the [key](https://github.com/meliorence/react-native-render-html/blob/cfc10e3151b519f7df27e1e1c6b2e83cba849874/packages/render-html/src/renderChildren.tsx#L21)
```javascript
const key = childTnode.nodeIndex;
```
The problem is, `TPhrasing` render nodes always have a nodeIndex = 0
![Screenshot from 2022-05-02 13-57-21](https://user-images.githubusercontent.com/9059945/166226661-21d14ef1-81a0-4c2a-a883-83aa3acc77e9.png)


**Proposal:**
Use element's index additionally to nodeIndex when assigning keys to children
```javascript
const key = `${childTnode.nodeIndex}_${n}`
```
This ensures that every child always has a unique key
![Screenshot from 2022-05-02 14-00-13](https://user-images.githubusercontent.com/9059945/166226679-9263ced0-7176-4575-ac29-8b239c0174fb.png)

Before:

https://user-images.githubusercontent.com/9059945/166226748-c38e449f-5a03-4069-b239-b296d1044005.mp4

After:


https://user-images.githubusercontent.com/9059945/166226778-4141c92c-7b75-4774-b3ae-359cc85919bf.mp4

**Comment by parasharrajat** [comment] 2022-05-02 16:41
Good catch @eVoloshchak.  @eVoloshchak did you try upgrading the lib version to see if this issue still exists?

**Comment by eVoloshchak** [comment] 2022-05-02 16:53
> @eVoloshchak did you try upgrading the lib version to see if this issue still exists?

Yup, tried upgrading to the latest version (`6.3.1 -> 6.3.4`), issue is still present

**Comment by parasharrajat** [comment] 2022-05-02 16:59
Ok, Thanks. I am fine with @eVoloshchak 's proposal. The next steps would be: 
1. Create the issue on the `react-native-render-html` repo.
2. Create a PR with the fix on the `react-native-render-html` repo.
3. Upgrade the lib on this repo. 

cc: @AndrewGable 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by AndrewGable** [comment] 2022-05-03 02:30
Sounds good to me!

**Comment by eVoloshchak** [comment] 2022-05-03 07:09
Submitted proposal on Upwork

**Comment by eVoloshchak** [comment] 2022-05-05 18:04
Created the [issue](https://github.com/meliorence/react-native-render-html/issues/562) on `react-native-render-html` repo.
BTW, while creating minimal reproducible example I found out, that the issue occurs only if you set [dangerouslydisablewhitespacecollapsing](https://meliorence.github.io/react-native-render-html/api/renderhtmlprops#dangerouslydisablewhitespacecollapsing) prop to `true`

**Comment by eVoloshchak** [comment] 2022-05-12 07:04
@parasharrajat, it's been a week and the issue has no response from the maintainer. Should we wait more?

**Comment by parasharrajat** [comment] 2022-05-12 08:11
I thought you created the PR as well. https://github.com/Expensify/App/issues/8655#issuecomment-1115123550

**Comment by eVoloshchak** [comment] 2022-05-12 08:12
> I thought you created the PR as well. [#8655 (comment)](https://github.com/Expensify/App/issues/8655#issuecomment-1115123550)

Ok, will do that shortly

**Comment by parasharrajat** [comment] 2022-05-12 08:14
Also, the maintainer is very active on the repo. He must be busy with some stuff but he will take a look. Try joining the discord and mention this issue.

**Comment by mdneyazahmad** [comment] 2022-05-12 13:23
I earlier posted this issue https://expensify.slack.com/archives/C01GTK53T8Q/p1644402310844119.  Am I eligible for reporting bonus?

**Comment by eVoloshchak** [comment] 2022-05-14 13:26
So I've received an [answer](https://github.com/meliorence/react-native-render-html/pull/563#issuecomment-1126708809) from repo maintainer
> The real issue is that dangerously (which means in this context: not really tested) disabling whitespace collapsing would cause @native-html/transient-render-engine to produce a faulty tree in certain situations, where indexes are not reflecting real position. Hence, this should be fixed in this repository instead of implementing a hack around here: https://github.com/native-html/core/tree/master/packages/transient-render-engine.
As a side note regarding using this not-so-recommended prop, in most of the cases you'll be better off with a global style which sets white-space: pre

So I searched and found out that `dangerouslyDisableWhitespaceCollapsing` was set to true in order to fix https://github.com/Expensify/App/issues/3859.
So, as was suggested, I set `dangerouslyDisableWhitespaceCollapsing` to `false` and added a `whiteSpace: 'pre'` to `TRenderEngineProvider's` [baseStyle](https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L53) and it worked. It resolves this issue without breaking https://github.com/Expensify/App/issues/3859. Tested on web and native. So if there is no other issues besides https://github.com/Expensify/App/issues/3859 that require `dangerouslyDisableWhitespaceCollapsing` to be enabled, we can resolve this.

**Comment by parasharrajat** [comment] 2022-05-15 11:12
@eVoloshchak Could you share a video showing the effect of the new change? Please use a combination of messages in any chat and scroll to show those messages in the video. Thanks.

**Comment by eVoloshchak** [comment] 2022-05-15 18:30
> @eVoloshchak Could you share a video showing the effect of the new change? Please use a combination of messages in any chat and scroll to show those messages in the video. Thanks.

Sure thing

Web:

https://user-images.githubusercontent.com/9059945/168488195-55528d52-1540-4123-a1f2-0f9080120089.mp4

Android

https://user-images.githubusercontent.com/9059945/168488217-981e5d12-2328-4d44-b09e-0b149d25b10e.mp4

**Comment by parasharrajat** [comment] 2022-05-16 13:53
Ok, looking good to me. Go ahead create the PR.

**Comment by eVoloshchak** [comment] 2022-05-16 15:40
> Ok, looking good to me. Go ahead and create the PR.

PR is up

**Comment by JmillsExpensify** [comment] 2022-05-25 20:51
Payment issued for @eVoloshchak. @parasharrajat I'll circle back on you tomorrow, as I just sent the offer. Thanks both!

**Comment by JmillsExpensify** [comment] 2022-05-26 03:19
@parasharrajat is now covered, so I'm closing this out.

**Closed by JmillsExpensify** 2022-05-26 03:19 UTC
Labels: Exported, External, Weekly
