### ISSUE TITLE
[$250] Avatar - Avatar position moves after error appears (web), incorrect error position (native)

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48244] opened 2024-08-29 08:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh270801@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile.
3. Upload a large photo.

## Expected Result:
Avatar position will not move after the error appears.

## Actual Result:
On web and desktop app, avatar position moves after the error appears.
On Android and iOS app, the avatar position does not move but the error message is not placed correctly.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/33ff4370-0b5a-4b03-a859-f9d698a37d48

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831363479706276077</li>
        <li>Upwork Job ID: 1831363479706276077</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by Julesssss** [comment] 2024-08-29 08:54
We'll fix, but this is not a blocker.

**Comment by etCoderDysto** [comment] 2024-08-29 08:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar position moves after the error appears
### What is the root cause of that problem?
We are using `styles.alignSelfCenter` for avatar
https://github.com/etCoderDysto/App/blob/b9af3d1f7ab160f7d817102d081b0e6186ba2d02/src/components/AvatarWithImagePicker.tsx#L375
### What changes do you think we should make in order to solve the problem?
We should use `styles.alignSelfStart`

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-29 08:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar position moves after error appears (web), incorrect error position (native)
### What is the root cause of that problem?
We are using `styles.alignSelfCenter` for avatar
https://github.com/Expensify/App/blob/b9af3d1f7ab160f7d817102d081b0e6186ba2d02/src/components/AvatarWithImagePicker.tsx#L375
### What changes do you think we should make in order to solve the problem?
We should use `styles.alignSelfStart`

### What alternative solutions did you explore? (Optional)

**Comment by haris-ali9211** [comment] 2024-09-04 23:09
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The avatar position moves after the error appears on the web and desktop app. On Android and iOS apps, the avatar position does not move, but the error message is not placed correctly.

### What is the root cause of that problem?

- ### Bug Causing in webApp

```tsx
<PressableWithoutFeedback
    onPress={() => onPressAvatar(openPicker)}
    accessibilityRole={CONST.ROLE.BUTTON}
    accessibilityLabel={translate('avatarWithImagePicker.editImage')}
    disabled={isAvatarCropModalOpen || (disabled && !enablePreview)}
    disabledStyle={disabledStyle}
    style={[styles.pRelative, avatarStyle, type === CONST.ICON_TYPE_AVATAR && styles.alignSelfCenter]}
    ref={anchorRef}
>
```
- **Why It Is Causing**

```tsx
style={[styles.pRelative, avatarStyle, type===CONST.ICON_TYPE_AVATAR && styles.alignSelfCenter]}
```

  - Here on the style, we are using `styles.alignSelfCenter`, which is why, when an error arises, the container's size becomes greater than the avatar. Consequently, the avatar centers itself due to the `alignSelfCenter` property.

---

- ### Bug Causing in Native

```tsx
<View style={[styles.pt3, styles.pb6, styles.alignSelfStart]}>
    <MenuItemGroup shouldUseSingleExecution={false}>
        <AvatarWithImagePicker
            isUsingDefaultAvatar={UserUtils.isDefaultAvatar(currentUserPersonalDetails?.avatar ?? '')}
            source={avatarURL}
            avatarID={accountID}
            onImageSelected={PersonalDetails.updateAvatar}
            onImageRemoved={PersonalDetails.deleteAvatar}
            size={CONST.AVATAR_SIZE.XLARGE}
            avatarStyle={styles.avatarXLarge}
            pendingAction={currentUserPersonalDetails?.pendingFields?.avatar ?? undefined}
            errors={currentUserPersonalDetails?.errorFields?.avatar ?? null}
            errorRowStyles={styles.mt6}
            onErrorClose={PersonalDetails.clearAvatarErrors}
            onViewPhotoPress={() => Navigation.navigate(ROUTES.PROFILE_AVATAR.getRoute(String(accountID)))}
            previewSource={UserUtils.getFullSizeAvatar(avatarURL, accountID)}
            originalFileName={currentUserPersonalDetails.originalFileName}
            headerTitle={translate('profilePage.profileAvatar')}
            fallbackIcon={currentUserPersonalDetails?.fallbackIcon}
            editIconStyle={styles.profilePageAvatar}
        />
    </MenuItemGroup>
</View>

```

- **Why It Is Causing**

```tsx
style={[styles.pt3, styles.pb6, styles.alignSelfStart]}
```
  - Here we are not applying `styles.w100` (full width) to the View component that encloses AvatarWithImagePicker. Because of this, the inner View component inherits a width that does not extend fully across the container, leading to layout issues.

### What changes do you think we should make in order to solve the problem?

- **For WebApp**
  - Apply `styles.alignSelfStart` to the avatar to resolve the centering issue.

- **For Native Mobile**
  - Add `styles.w100` to the view component to correct the layout

**Comment by haris-ali9211** [comment] 2024-09-04 23:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The avatar position moves after the error appears on the web and desktop app. On Android and iOS apps, the avatar position does not move, but the error message is not placed correctly.

### What is the root cause of that problem?

- ### Bug Causing in webApp

```tsx
<PressableWithoutFeedback
    onPress={() => onPressAvatar(openPicker)}
    accessibilityRole={CONST.ROLE.BUTTON}
    accessibilityLabel={translate('avatarWithImagePicker.editImage')}
    disabled={isAvatarCropModalOpen || (disabled && !enablePreview)}
    disabledStyle={disabledStyle}
    style={[styles.pRelative, avatarStyle, type === CONST.ICON_TYPE_AVATAR && styles.alignSelfCenter]}
    ref={anchorRef}
>
```
- **Why It Is Causing**

```tsx
style={[styles.pRelative, avatarStyle, type===CONST.ICON_TYPE_AVATAR && styles.alignSelfCenter]}
```

  - Here on the style, we are using `styles.alignSelfCenter`, which is why, when an error arises, the container's size becomes greater than the avatar. Consequently, the avatar centers itself due to the `alignSelfCenter` property.

---

- ### Bug Causing in Native

```tsx
<View style={[styles.pt3, styles.pb6, styles.alignSelfStart]}>
    <MenuItemGroup shouldUseSingleExecution={false}>
        <AvatarWithImagePicker
            isUsingDefaultAvatar={UserUtils.isDefaultAvatar(currentUserPersonalDetails?.avatar ?? '')}
            source={avatarURL}
            avatarID={accountID}
            onImageSelected={PersonalDetails.updateAvatar}
            onImageRemoved={PersonalDetails.deleteAvatar}
            size={CONST.AVATAR_SIZE.XLARGE}
            avatarStyle={styles.avatarXLarge}
            pendingAction={currentUserPersonalDetails?.pendingFields?.avatar ?? undefined}
            errors={currentUserPersonalDetails?.errorFields?.avatar ?? null}
            errorRowStyles={styles.mt6}
            onErrorClose={PersonalDetails.clearAvatarErrors}
            onViewPhotoPress={() => Navigation.navigate(ROUTES.PROFILE_AVATAR.getRoute(String(accountID)))}
            previewSource={UserUtils.getFullSizeAvatar(avatarURL, accountID)}
            originalFileName={currentUserPersonalDetails.originalFileName}
            headerTitle={translate('profilePage.profileAvatar')}
            fallbackIcon={currentUserPersonalDetails?.fallbackIcon}
            editIconStyle={styles.profilePageAvatar}
        />
    </MenuItemGroup>
</View>

```

- **Why It Is Causing**

```tsx
style={[styles.pt3, styles.pb6, styles.alignSelfStart]}
```
  - Here we are not applying `styles.w100` (full width) to the View component that encloses AvatarWithImagePicker. Because of this, the inner View component inherits a width that does not extend fully across the container, leading to layout issues.

### What changes do you think we should make in order to solve the problem?

- **For WebApp**
  Apply `styles.alignSelfStart` to the avatar to resolve the centering issue.

- **For Native Mobile**
  Add `styles.w100` to the view component to correct the layout

**Comment by kevinksullivan** [comment] 2024-09-12 18:59
Closing out since we have that PR fixing this and other issues.

**Closed by kevinksullivan** 2024-09-12 18:59 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted, Bug
