### ISSUE TITLE
[HOLD for payment 2022-11-16] [$250] Chat - App is crashed after click on expensifail account which is closed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12487] opened 2022-11-04 23:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition:
Create a group conversation with account A and B ( should be expensifail account)
Close the expensifail account under domain account
1. Go to staging.new.expensify.com
2. Log in with account A
3. Select the created conversation between account A and B from LHN
4. Click on user's B avatar 

## Expected Result:
Details for account B should be displayed.

## Actual Result:
 App is crashed after click on expensifail account which is closed

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.24.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 508-221-1196/applausetester+0709abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200086853-928294af-2397-425c-a3c6-1ac2e6231f11.mp4

![image (29)](https://user-images.githubusercontent.com/93399543/200086855-a6b4ada1-5f92-40ac-bd8b-55291cea323e.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-11-04 23:07
Issue is not reproducible in production 
![image (30)](https://user-images.githubusercontent.com/93399543/200087266-de979e75-86c4-4acd-ba25-7001af109e7d.png)

**Comment by marcaaron** [comment] 2022-11-05 00:03
>Go to staging.new.expensify.com
>Log in with account A
>Select the created conversation between account A and B from LHN
>Click on account B

Not able to reproduce this. Please list the **exact** testing steps that were performed in order to trigger the bug.

**Comment by kbecciv** [comment] 2022-11-05 01:27
1. Go to staging.new.expensify.com
2. Log in with account A (50821-11-96/Feya86Katya
3. Select the chat conversation with applausetester+0709abb@applause.expensifail.com
4. Click on applausetester+0709abb@applause.expensifail.com avatar

**Comment by tgolen** [comment] 2022-11-07 15:09
Ah yes, it looks like when I changed the signature of `getDisplayNameForParticipant()` that I missed a spot. The proposal from @0xmiroslav looks like a good fix for it.

**Comment by marcaaron** [comment] 2022-11-07 18:50
@tgolen to clarify, are you saying that @0xmiroslav should be hired to fix it or that you are going to raise a PR with that solution?

**Comment by tgolen** [comment] 2022-11-07 19:24
If @0xmiroslav can do it now, then I'll let him do it. I'm in the middle of a few other things. I'll go ahead and assign

**Comment by joekaufmanexpensify** [comment] 2022-11-07 19:57
About to jump on a call, but will create this in upwork right after.

**Comment by parasharrajat** [comment] 2022-11-07 20:33
This is DP, Do you need to me test it now

**Comment by joekaufmanexpensify** [comment] 2022-11-07 20:52
Job is [here](https://www.upwork.com/jobs/~01fa9f8905b38cc2bb) in upwork!

**Comment by joekaufmanexpensify** [comment] 2022-11-07 21:02
@0xmiroslav offer sent via upwork!

**Comment by joekaufmanexpensify** [comment] 2022-11-07 21:03
@parasharrajat offer sent!

**Comment by yuwenmemon** [comment] 2022-11-08 16:44
@0xmiroslav 👋 What's our status on this one?

**Comment by yuwenmemon** [comment] 2022-11-08 16:48
@0xmiroslav Sorry, what I mean to ask is if this is completed with https://github.com/Expensify/App/pull/12533 or if there's still something left to do here? In terms of fixing the issue in the description.

**Comment by yuwenmemon** [comment] 2022-11-08 18:36
Sounds good - removing the Deploy Blocker Label then

**Comment by joekaufmanexpensify** [comment] 2022-11-08 18:43
Removing the hourly label as well given the PR is merged.

**Comment by joekaufmanexpensify** [comment] 2022-11-09 18:12
PR still on staging. 7 day payment pending period will begin as soon as it's on prod.

**Comment by mvtglobally** [comment] 2022-11-16 02:24
Issue not reproducible during KI retests. (First week)

**Comment by joekaufmanexpensify** [comment] 2022-11-16 21:55
This just hit 7 days with no reported regressions. Going to work on bug zero checklist now!

**Comment by joekaufmanexpensify** [comment] 2022-11-16 22:18
Discussing two new regression tests I think we should add [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1668637071846579)

**Comment by joekaufmanexpensify** [comment] 2022-11-17 21:15
Regression test sent to applause to be added! Linked in BZ checklist above.

**Comment by joekaufmanexpensify** [comment] 2022-11-17 21:26
Okay, I updated the bug zero checklist above to reflect who is responsible for which tasks (as the checklist itself was just [updated](https://github.com/Expensify/Expensify/issues/243037), before after it was posted to this issue). 

@marcaaron / @parasharrajat let me know if I can help with commenting on the offending PR and beginning the discussion in Slack. 

In the interim, I am going to pay everyone.

**Comment by joekaufmanexpensify** [comment] 2022-11-17 21:40
@parasharrajat Mind accepting [the offer](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/22223406) for this one so we can pay you?

**Comment by marcaaron** [comment] 2022-11-17 22:01
@joekaufmanexpensify it is done!

**Comment by parasharrajat** [comment] 2022-11-17 22:09
@joekaufmanexpensify Done.

**Comment by joekaufmanexpensify** [comment] 2022-11-18 20:06
Great ty! Since this PR was merge the same day the contributor was assigned to the issue, both @parasharrajat and @0xmiroslav get a 50% bonus. 

Going to issue payment of $375 to both of you now!

**Comment by joekaufmanexpensify** [comment] 2022-11-18 20:11
@parasharrajat $375 sent!

**Comment by joekaufmanexpensify** [comment] 2022-11-18 20:13
@0xmiroslav $375 sent!

**Comment by joekaufmanexpensify** [comment] 2022-11-18 20:14
Applause found this, so no reporting payment to make.

**Comment by joekaufmanexpensify** [comment] 2022-11-18 20:14
Job closed.

**Comment by joekaufmanexpensify** [comment] 2022-11-18 20:26
This is all set. [Confirming](https://expensify.slack.com/archives/C01SKUP7QR0/p1668802587771989) whether the issue needs to remain open until applause adds regression test.

**Comment by joekaufmanexpensify** [comment] 2022-11-18 20:38
Okay, confirmed we don't need to wait for applause to actually add the regression test. Opening the issue for them is sufficient. 

Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2022-11-18 20:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
