### ISSUE TITLE
[HOLD for payment 2023-05-29] [$1000] On the "Confirm Task" page, the vertical alignment alignment is off compared with all the previous page ("Next")

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18739] opened 2023-05-10 20:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app -> Login in account
2. Click on FAB button -> Click on Assign task option
3. Enter title & description
4. Which will navigate to Confirm task page here notice the green Confirm Task button is vertically off compare to rest of the app

## Expected Result:  
Green submit button of Confirm Task Should have same vertically spacing as other pages
## Actual Result:   
Green submit button of Confirm Task is aligned towards bottom doesn't match with other screen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Snip - (28) New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/43996225/e48c2eaa-d71c-4516-abd6-b4b173177edd)

<img src="https://github.com/Expensify/App/assets/43996225/bcd7633a-0706-424d-baa4-44dd6badc2f7" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/b6fcf563-da75-4e44-8dec-1cfd1c15b45d" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683697149428889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d16acfe194106a4a</li>
        <li>Upwork Job ID: 1656796284387614720</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-11 00:01
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
On confirm task page the submit button Confirm task vertically alignment is off as compared with all the other page

### What is the root cause of that problem?
On confirm task page Confirm task button rendered via this code.
https://github.com/Expensify/App/blob/9fcbeba4f0adce3b2e71a895cf0bb57576725412/src/pages/tasks/NewTaskPage.js#L197-L204

That button is wrapped within Screenwrapper as shown below
https://github.com/Expensify/App/blob/9fcbeba4f0adce3b2e71a895cf0bb57576725412/src/pages/tasks/NewTaskPage.js#L153

We can see it consist `includeSafeAreaPaddingBottom={false}` So it will not show padding at bottom for that button.


### What changes do you think we should make in order to solve the problem?
We have to set `includeSafeAreaPaddingBottom={true}` at line 153, it will solve the issue as shown in result video.

### What alternative solutions did you explore? (Optional)
None

<details>
<summary>Results</summary>

#### Before
https://github.com/Expensify/App/assets/7823358/65f1f0bd-3476-435c-b45b-18c5ad16e8c1 

#### After
https://github.com/Expensify/App/assets/7823358/78f68fa3-131c-490b-924e-6df134295203 

</details>

**Comment by jliexpensify** [comment] 2023-05-11 03:01
@kavimuru I'm not seeing Tasks on my end. Is there a beta I need to be added to, in order to access them? Keep in mind I'm not an Engineer so I don't have a DEV environment.

**Comment by PrashantMangukiya** [comment] 2023-05-11 06:03
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
On confirm task page the submit button Confirm task vertically alignment is off as compared with all the other page

### What is the root cause of that problem?
On confirm task page Confirm task button rendered via this code.
https://github.com/Expensify/App/blob/9fcbeba4f0adce3b2e71a895cf0bb57576725412/src/pages/tasks/NewTaskPage.js#L197-L204

This button is wrapped within Screenwrapper as shown below
https://github.com/Expensify/App/blob/9fcbeba4f0adce3b2e71a895cf0bb57576725412/src/pages/tasks/NewTaskPage.js#L153

For other pages like [NewTaskDetailsPage.js](https://github.com/Expensify/App/blob/1ee8cf84d60e0f60baae33f9016f6b585e869387/src/pages/tasks/NewTaskDetailsPage.js#L70) there is a `Form` component included on the page, so it will apply `safeAreaPaddingBottomStyle` via `Form` component  so we can keep includeSafeAreaPaddingBottom as false.

But for `NewTaskPage.js` page there is no Form component, so `FormAlertWithSubmitButton` does not have safe area bottom padding applied anyhow.  This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
We have to pass includeSafeAreaPaddingBottom as true at line 153 as shown below. 
```javascript
<ScreenWrapper includeSafeAreaPaddingBottom>
```
it will solve the issue as shown in result video.

### What alternative solutions did you explore? (Optional)
None

<details>
<summary>Results</summary>

#### Before
https://github.com/Expensify/App/assets/7823358/65f1f0bd-3476-435c-b45b-18c5ad16e8c1 

#### After
https://github.com/Expensify/App/assets/7823358/78f68fa3-131c-490b-924e-6df134295203 

</details>

**Comment by jliexpensify** [comment] 2023-05-11 22:59
Chatted to Jack, who's leading up the tasks project/implementation. He said this is fine to go to External.

**Comment by jliexpensify** [comment] 2023-05-12 03:08
Apologies, I misunderstood Jack (he meant it can go to external but we have a Task beta) - I added myself to the beta to test this, and it looks like this isn't an issue in v1.3.12-1 anymore:

![image](https://github.com/Expensify/App/assets/30815269/74757c93-bbab-4fe3-b751-049bec704714)

**Comment by jliexpensify** [comment] 2023-05-12 03:10
Video proof:

https://github.com/Expensify/App/assets/30815269/03174b48-e321-400b-a9d7-84fdf3e57dc8

**Comment by PrashantMangukiya** [comment] 2023-05-12 03:44
@jliexpensify This issue still exist in in v1.3.12-1. It can be reproducible in Native iOS only as shown in video.

https://github.com/Expensify/App/assets/7823358/4b22b7cd-6177-47fa-97f2-a0eeb540c8b6

**Comment by jliexpensify** [comment] 2023-05-12 04:44
Thanks @PrashantMangukiya , have edited the GH issue to reflect your findings.

**Comment by flodnv** [comment] 2023-05-12 14:45
Thanks, sounds good to me

**Comment by PrashantMangukiya** [comment] 2023-05-12 14:51
@sobitneupane @flodnv Thanks. I will prepare and submit PR within two hours asap.

**Comment by PrashantMangukiya** [comment] 2023-05-12 16:13
@sobitneupane @flodnv PR is ready for review.

**Comment by jliexpensify** [comment] 2023-05-15 01:27
Hired @PrashantMangukiya , @sobitneupane and @dhairyasenjaliya

**Comment by flodnv** [comment] 2023-05-17 19:15
PR merged

**Comment by jliexpensify** [comment] 2023-05-30 22:50
Paying today - @sobitneupane can you please complete the checklist? Thanks!

**Comment by jliexpensify** [comment] 2023-05-30 23:01
Everyone is paid and job is closed.

**Comment by sobitneupane** [comment] 2023-05-31 04:30
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/17322

> * [x]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/17322#issuecomment-1569476960

> * [x]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1685507445902049

**Comment by sobitneupane** [comment] 2023-05-31 04:32
**Regression Test Proposal**

1. Click FAB > Assign Task
2. Enter Task title and description and click Next button (at bottom)
3. It will navigate to Confirm task screen.
4. Verify that "Confirm task" button has bottom margin similar to previous page button.

Do we agree 👍 or 👎

**Comment by flodnv** [comment] 2023-05-31 15:26
👎 because we could write a hundred tests like this.

I think instead we need a new QA guideline if it does not yet exist, something like "ensure alignment of UI items is consistent throughout the app".

**Comment by jliexpensify** [comment] 2023-06-02 02:27
@sobitneupane if you agree with Florent, do you have a new Regression Test Proposal? Thanks!

**Comment by flodnv** [comment] 2023-06-02 16:14
@jliexpensify `we need a new QA guideline`

**Comment by jliexpensify** [comment] 2023-06-05 01:07
@flodnv sorry, I misunderstood! I'm not familiar with QA Guidelines: I searched in SO but couldn't find anything. 

Do I need to arrange anything for this QA guideline? (maybe adding it to this doc? - https://docs.google.com/document/d/1UaWlcieiwLnsKfeKw7iwLF7vgYRmdw_-K8OcY5aPBRU/edit)

**Comment by flodnv** [comment] 2023-06-05 14:43
I think this is a discussion we need to have with our QA team members

**Comment by jliexpensify** [comment] 2023-06-06 02:03
Ok great, thanks for the guidance Flo - posted here: https://expensify.slack.com/archives/C9YU7BX5M/p1686016991001429

**Comment by jliexpensify** [comment] 2023-06-06 02:03
Closing this out now, lets convene on that thread for discussion!

**Closed by jliexpensify** 2023-06-06 02:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
