### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Distance - "Center" button has no hover and press effect

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43058] opened 2024-06-04 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/40759
## Action Performed:
Precondition:
- App location permission is allowed
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Distance
3. Hover over "Center" button
4. Click on the "Center" button

## Expected Result:
There should be hover and press effect on the button when hovering over and pressing on the button

## Actual Result:
"Center" button has no hover and press effect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c2cdc98c-b4a5-4623-ba05-121d4ac6e5c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba9155072ebd3afb</li>
        <li>Upwork Job ID: 1798088916367302656</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 102678374</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-06-04 19:09
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcochavezf** [comment] 2024-06-04 20:25
There's no center button in production:

<img width="417" alt="Screenshot 2024-06-04 at 2 20 12 p m" src="https://github.com/Expensify/App/assets/6829422/2c2c4781-76d9-48c0-b58f-541644745deb">

I don't think this is a deploy blocker, but I will make it external

**Comment by etCoderDysto** [comment] 2024-06-04 20:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Center" button has no hover and press effect
### What is the root cause of that problem?
The root cause is that we are not checking hover state [here](https://github.com/Expensify/App/blob/a1fc168e2e6e5df8a400c375298e64d7ec35b7db/src/components/MapView/MapView.tsx#L247) and the website extension file too and we are not applying hover effect when hover state is true. 
### What changes do you think we should make in order to solve the problem?
We should change this component to a call back function that returns a component [here]([url](https://github.com/Expensify/App/blob/a1fc168e2e6e5df8a400c375298e64d7ec35b7db/src/components/MapView/MapView.tsx#L247)). And apply theme.iconMenuHovered or theme.iconHovered to the icons fill property when hovered is true. 
The hover color can be decided based on the design choice. 

### What alternative solutions did you explore? (Optional)

Result:

https://github.com/Expensify/App/assets/171434916/65a2a8e6-60a2-4f04-9c64-21b44276d3ac

**Comment by truph01** [comment] 2024-06-04 23:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Center" button has no hover and press effect

### What is the root cause of that problem?
- We are using ```PressableWithoutFeedback``` in that button.
### What changes do you think we should make in order to solve the problem?
- We should use ```PressableWithFeedback```

### What alternative solutions did you explore? (Optional)
NA

**Comment by truph01** [comment] 2024-06-04 23:27
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.
"Center" button has no hover and press effect

### What is the root cause of that problem?
- We are using ```PressableWithoutFeedback``` in that button:
https://github.com/Expensify/App/blob/9b179ce3c63899262da82eee052eb61091880c12/src/components/MapView/MapView.website.tsx#L256
### What changes do you think we should make in order to solve the problem?
- We should use ```PressableWithFeedback``` with prop ```hoverDimmingValue``` (based on design) instead and we should apply the change in both .web and .native file.

- We use the similar logic in a lot of pages, for example InitialSettingsPage:
https://github.com/Expensify/App/blob/9b179ce3c63899262da82eee052eb61091880c12/src/pages/settings/InitialSettingsPage.tsx#L387-L388

### What alternative solutions did you explore? (Optional)
- NA

**Comment by kaushiktd** [comment] 2024-06-05 07:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - "Center" button has no hover and press effect 

### What is the root cause of that problem?
You have just placed an Icon inside the `PressableWithoutFeedback` component without checking its hover and press (active) states. This is the primary root cause of the issues.

### What changes do you think we should make in order to solve the problem?
To address this issue, you should modify the `PressableWithoutFeedback` component in the [MapView.website.tsx](https://github.com/Expensify/App/blob/main/src/components/MapView/MapView.tsx) and [MapView.tsx](https://github.com/Expensify/App/blob/main/src/components/MapView/MapView.website.tsx) files. Check the hover and active states for the component, ensuring the Icon's fill parameter reflects these states to display different colors. for that you need to add below condition [here](https://github.com/Expensify/App/blob/main/src/components/MapView/MapView.website.tsx#L266).
```
fill={hovered || pressed ? theme.iconMenuHovered : theme.icon}
```
Additionally, add a hover stylesheet to the View component inside `PressableWithoutFeedback` to make it hoverable [here](https://github.com/Expensify/App/blob/main/src/components/MapView/MapView.website.tsx#L261). This will ensure the component properly responds to user interactions.
```
(hovered || pressed) && StyleUtils.getButtonBackgroundColorStyle(getButtonState(hovered, pressed))
```
You need to encapsulate the child component of `PressableWithoutFeedback` with hover and press states, as shown below:
```
{({ hovered, pressed }) => (
  // Child component goes here..
)}
```

### What alternative solutions did you explore? (Optional)
You can also use the hoverStyle to activate the hover state. However, for this, you need to use the `PressableWithFeedback` component instead of the `PressableWithoutFeedback` component.


<details>
<summary>Recording for Press(Active) and Hover State</summary>



https://github.com/Expensify/App/assets/43398804/fa4b650c-4e30-46ba-a71f-5cd3e4af38e6

</details>

**Comment by etCoderDysto** [comment] 2024-06-05 08:47
Contributor details
Your Expensify account email: dystovskycoder@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135b3a84ec2709c21

**Comment by etCoderDysto** [comment] 2024-06-05 08:48
Contributor details
Your Expensify account email: [dystovskycoder@gmail.com](mailto:dystovskycoder@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0135b3a84ec2709c21

**Comment by etCoderDysto** [comment] 2024-06-05 08:50
Contributor details
Your Expensify account email: dystovskycoder@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135b3a84ec2709c21

**Comment by etCoderDysto** [comment] 2024-06-05 08:58
Contributor details
Your Expensify account email: dystovskycoder@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135b3a84ec2709c21

**Comment by etCoderDysto** [comment] 2024-06-05 09:06
Contributor details
Your Expensify account email: dystovskycoder@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ea78e0164390eb79

**Comment by jjcoffee** [comment] 2024-06-05 15:10
@codinggeek2023 I don't _think_ your [proposal](https://github.com/Expensify/App/issues/43058#issuecomment-2148376439) of passing `hoverStyle` and/or `pressStyle` will do anything in `PressableWithoutFeedback`, but happy to be proven wrong if you add a recording of the result.

@etCoderDysto From your [proposal](https://github.com/Expensify/App/issues/43058#issuecomment-2148387710):
> I don't think there is a need to apply press effect since the press action is immediately followed by a feedback of map navigating to center.

I'm pretty sure we do actually want the press effect here as it's useful feedback (especially if you imagine on a slower device, if something goes wrong, or if you just tap the button when it's already centered).

@truph01 Your [proposal](https://github.com/Expensify/App/issues/43058#issuecomment-2148573170) to switch to `PressableWithFeedback` makes sense to me! Would you mind adding a video of the result so we can check with the design team?

@dragnoir @kaushiktd Appreciate [your](https://github.com/Expensify/App/issues/43058#issuecomment-2149482768) [proposals](https://github.com/Expensify/App/issues/43058#issuecomment-2149056261), but I think going with `PressableWithFeedback` is probably simpler and cleaner.

@dragnoir I think you're basically [proposing](https://github.com/Expensify/App/issues/43058#issuecomment-2149482768) to turn `PressableWithoutFeedback` into `PressableWithFeedback`, when it makes more sense to just use the latter.

**Comment by kaushiktd** [comment] 2024-06-06 04:48
> @dragnoir @kaushiktd Appreciate [your](https://github.com/Expensify/App/issues/43058#issuecomment-2149482768) [proposals](https://github.com/Expensify/App/issues/43058#issuecomment-2149056261), but I think going with `PressableWithFeedback` is probably simpler and cleaner.

@jjcoffee [Proposal updated.](https://github.com/Expensify/App/issues/43058#issuecomment-2149056261) You can check the solution with `PressableWithFeedback` as my alternative solution.

**Comment by truph01** [comment] 2024-06-06 11:07
@jjcoffee I added video to [proposal](https://github.com/Expensify/App/issues/43058#issuecomment-2148573170)

**Comment by jjcoffee** [comment] 2024-06-06 13:56
Thanks all! 

@Krishna2323 That's another way of doing it, but I don't think it's necessary to use `Button` here (it just uses `PressableWithFeedback` under the hood).

I'm happy to go with @truph01's [proposal](https://github.com/Expensify/App/issues/43058#issuecomment-2148573170), pending a quick look over by @Expensify/design.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2024-06-06 13:57
@marcochavezf Actually @truph01 can probably just be assigned already and we can get a design review on the PR, so we keep things moving smoothly!

**Comment by shawnborton** [comment] 2024-06-06 15:02
From a technical perspective I'm not sure what is best, but as long as we make this behave exactly like our other standard buttons, that works for me.

**Comment by marcochavezf** [comment] 2024-06-10 22:19
Thanks @jjcoffee for the review and also thanks guys for your proposals! I lean towards @jjcoffee's decision which points to a straight solution for this issue. 

@Krishna2323 thanks for bringing that perspective, I also think that's another way to solve this issue and possibly we'd need to discuss with the community how/when to use Button instead of PressableWithFeedback, but for the scope of this issue and for a straightforward solution let's just use PressableWithFeedback with hoverDimmingValue for now :)

Said that let's assign @truph01 🚀

**Comment by truph01** [comment] 2024-06-11 03:16
@marcochavezf @shawnborton what is the expected hover and press value we should use in this case? Should we use the same values as the "Status" and the "Share code" button below:

![image](https://github.com/Expensify/App/assets/170341821/4dffdbb0-cbcb-48b3-ad5c-4dae7ccafcdf)

**Comment by truph01** [comment] 2024-06-12 02:17
@jjcoffee Here is how it looks like in the PR now:

https://github.com/Expensify/App/assets/170341821/722e0ed8-36d0-45c3-9ab2-d7d9ee6877aa

**Comment by jjcoffee** [comment] 2024-06-12 09:43
@Expensify/design Any strong feelings on using the values from [here](https://github.com/Expensify/App/issues/43058#issuecomment-2159702252), resulting in [this](https://github.com/Expensify/App/issues/43058#issuecomment-2161976315)? Looks fine to me, but just want to get a confirmation before we go ahead!

**Comment by shawnborton** [comment] 2024-06-12 13:43
Can we use the same :hover and :active values from these buttons in Troubleshoot? 
![CleanShot 2024-06-12 at 15 42 41@2x](https://github.com/Expensify/App/assets/2319350/2d2e1c54-d53a-4cc5-bfb3-b0f9cb4b3aa1)

They seem to be correct at least from my perspective.

**Comment by shawnborton** [comment] 2024-06-12 13:57
Indeed, that looks correct!

**Comment by mountiny** [comment] 2024-06-20 21:18
There was a regression from the PR https://github.com/Expensify/App/issues/44074 so we should have a penalty on the payment

**Comment by jjcoffee** [comment] 2024-06-26 09:42
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40759
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40759/files#r1654477558
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to FAB > Submit expense > Distance
2. Hover over "Center" button and verify that the button style changes
3. Tap and hold on the "Center" button and verify that the button style changes

Do we agree 👍 or 👎

**Comment by adelekennedy** [comment] 2024-07-01 04:15
@marcochavezf to review the regression test proposal above, also changing the total price to $125 for the [regression](https://github.com/Expensify/App/issues/43058#issuecomment-2181579540)

**Comment by adelekennedy** [comment] 2024-07-01 04:19
Payouts due:

- [ ] Contributor: $125 @truph01 
- [ ] Contributor+: $125 @jjcoffee 

@truph01 will you share your upwork profile with em so I can extend a manual offer?

**Comment by truph01** [comment] 2024-07-01 05:17
@adelekennedy Here's my Upwork: https://www.upwork.com/freelancers/~01c880ca813fdd85ec

Thanks

**Comment by adelekennedy** [comment] 2024-07-01 21:56
https://github.com/Expensify/Expensify/issues/409496

**Comment by adelekennedy** [comment] 2024-07-01 21:58
offer sent @truph01

**Comment by truph01** [comment] 2024-07-02 02:47
@adelekennedy Accepted thanks!

**Comment by adelekennedy** [comment] 2024-07-02 05:06
Payments made! Closing

**Closed by adelekennedy** 2024-07-02 05:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
