### ISSUE TITLE
[HOLD for payment 2024-06-24] [$250] The FAB or Search category selector are narrow 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43657] opened 2024-06-13 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718283502781369

## Action Performed:
Break down in numbered steps

1. Click on the + green button
2. Or go to Search page and select Expenses to choose different category to show

## Expected Result:
Describe what you think should've happened

The modal show take the entire width of the screen

## Actual Result:
Describe what actually happened

The modal is very narrow

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/36083550/aadee1b0-1da0-4cad-adbb-a6a309420e2c

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163f71b7719038ed3</li>
        <li>Upwork Job ID: 1801238352430390753</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102723522</li>
<li>bernhardoj | Contributor | 102723525</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by bernhardoj** [comment] 2024-06-13 13:20
I think it's better to move the FocusTrapForModal as ModalContent children. No need extra view.
https://github.com/Expensify/App/blob/f6de195ffee0c145926dfe529d2fa819dafb346e/src/components/Modal/BaseModal.tsx#L255-L266

```

```

**Comment by bernhardoj** [comment] 2024-06-13 13:37
It works fine as far as I tested

https://github.com/Expensify/App/assets/50919443/ee85a16d-7e95-4b9d-8d10-dcdde8eddcff

**Comment by jnowakow** [comment] 2024-06-13 15:56
@bernhardoj's proposal seems to be better option than applying style to this additional view. It's important to have `View` as a child of `FocusTrapForModal` but there's no problem in placing it inside `ModalContent`.

**Comment by dangrous** [comment] 2024-06-13 15:58
That makes sense to me as well as long as it doesn't break the focus trap, which I defer to @jnowakow and @fedirjh to confirm. Seems like we're okay?

**Comment by luacmartins** [comment] 2024-06-13 16:50
@bernhardoj are you available to work on the PR?

**Comment by bernhardoj** [comment] 2024-06-13 17:14
Yes, I'll open the PR quickly!

**Comment by bernhardoj** [comment] 2024-06-13 17:30
@luacmartins PR is ready

**Comment by mountiny** [comment] 2024-06-14 12:57
This was CPed and fixed

$250 to @bernhardoj and to @allroundexperts

**Comment by johncschuster** [comment] 2024-06-24 16:18
Discussing in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1719241991045089) to make sure I'm understanding the correct payment date

**Comment by johncschuster** [comment] 2024-06-25 14:48
# Payment Summary:
Contributor+: @allroundexperts   - $250 - paid via Manual request
Contributor: @bernhardoj  - $250 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/102723525)

@allroundexperts, can you complete the BZ Checklist when you get a moment? Thank you!

**Comment by luacmartins** [comment] 2024-06-27 15:26
I think the due date here is the 24th. Updated the title to reflect that.

**Comment by johncschuster** [comment] 2024-06-27 15:29
Yep! Payment has already been issued via Upwork. We're just waiting on the BZ Checklist to be completed.

**Comment by johncschuster** [comment] 2024-06-28 13:18
@allroundexperts can you complete the BZ Checklist above? Once finished, we can close this up.

**Comment by allroundexperts** [comment] 2024-06-30 13:42
## Checklist

1. https://github.com/Expensify/App/pull/39520
2. The software mansion team was aware of this issue already [here](https://github.com/Expensify/App/issues/43657#issuecomment-2166082429).
3. N/A
4. I think that the FAB and search category selector are being covered in other regression tests so a new one is not needed.

**Comment by johncschuster** [comment] 2024-07-01 14:55
Thanks, @allroundexperts! Please go ahead and request [payment](https://github.com/Expensify/App/issues/43657#issuecomment-2189169106) if you haven't already!

**Closed by johncschuster** 2024-07-01 14:55 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-20 17:19
$250 approved for @allroundexperts
