### ISSUE TITLE
[$500] mWeb - "Connect online with plaid" page is shown first instead of "connect Bank account"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32356] opened 2023-12-01 14:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap Workspaces
4. Tap on a Workspace
5. Tap Bank account
6. Tap connect online with plaid
7. Tap continue and Select Regions Bank
8. Enter credentials and submit
9. Tap continue
10. Tap allow

## Expected Result:
"Connect online with plaid" page must not be shown and "connect Bank account" page must be displayed

## Actual Result:
Instead of showing "connect Bank account" page, "Connect online with plaid" page is shown for a second and then only "connect Bank account" page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8c27b320-469c-4fe0-bd04-c55c7d8fb60b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a029613cdb55a03</li>
        <li>Upwork Job ID: 1730598635612438528</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-12-06 01:06
Lets get this fixed!

**Comment by MitchExpensify** [comment] 2023-12-12 23:37
How do these proposals looks to you @eVoloshchak ?

**Comment by eVoloshchak** [comment] 2023-12-13 15:44
@neonbhai [proposal](https://github.com/Expensify/App/issues/32356#issuecomment-1836471964): 
doesn't resolve the issue for me, the behavior can still be observed on web, could you double-check please?



https://github.com/Expensify/App/assets/9059945/c1e76005-9deb-476f-8b9b-fd9460412ae8

@bernhardoj's [proposal](https://github.com/Expensify/App/issues/32356#issuecomment-1836289901) does resolve the issue and the general approach is better, since we're fixing it in one place for the whole app. 

However, I think we need to dig a bit deeper to figure out exactly **why** this happens. Is this a problem with our codebase or something that should be addressed in `react-plaid-link`? 
Also, this might be partially related to https://github.com/plaid/react-plaid-link/issues/325

**Comment by MitchExpensify** [comment] 2023-12-18 16:17
Any suggestions at this point to help move this along @eVoloshchak ?

**Comment by grgia** [comment] 2023-12-21 18:01
bump @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-12-22 21:00
> The issue we have is the onExit callback is called even though we complete the setup which is caused by multiple plaid link open calls.

Seems like it's not a problem with our codebase, but with a package we're using, is that correct? In that case, we should fix the package itself

> I can't find the plaid link core source code

Correct me if it's the wrong repo: https://github.com/plaid/react-plaid-link
cc: @bernhardoj

**Comment by MitchExpensify** [comment] 2023-12-27 10:50
Firneldy bump on checking out @bernhardoj's[ comment](https://github.com/Expensify/App/issues/32356#issuecomment-1868192448), @eVoloshchak

**Comment by shubham1206agra** [comment] 2023-12-28 13:24
@mountiny Can you put this on hold for VBBA refactor?

**Comment by mountiny** [comment] 2023-12-28 18:30
Sorry everyone, I think this is very minor and we are very close to finishing the bank account refactor https://github.com/Expensify/App/issues/30442 which might fix this so putting it on hold for that

**Comment by MitchExpensify** [comment] 2024-01-01 00:37
On hold, Melvin

**Comment by grgia** [comment] 2024-01-04 16:50
moving to weekly until off hold

**Comment by grgia** [comment] 2024-01-12 21:31
still on hold

**Comment by MitchExpensify** [comment] 2024-01-23 00:00
still on hold

**Comment by eVoloshchak** [comment] 2024-02-15 19:44
Still on hold for https://github.com/Expensify/App/issues/30442

**Comment by mountiny** [comment] 2024-02-16 14:58
of HOLD

**Comment by MitchExpensify** [comment] 2024-02-18 23:41
Flagged here: https://expensify.slack.com/archives/C01GTK53T8Q/p1708299689924259

**Comment by MitchExpensify** [comment] 2024-02-26 01:15
@dylanexpensify Is this wave 5 worthy?

**Comment by MitchExpensify** [comment] 2024-03-05 18:49
Checking in with @dylanexpensify to see if wave 5 worthy, not sure how this might fit into the quarterly release plan but that seems like a good first step

**Comment by MitchExpensify** [comment] 2024-03-05 18:53
Seems like a LOW wave collect issue, what d'you reckon @trjExpensify ?

**Comment by trjExpensify** [comment] 2024-03-06 03:14
It would go in the `Polish` section, yeah. Quick questions though: 

1. When was this last tested? It was on hold for the VBBA refactor, came off hold, but I can't see if it has been retested and if it stills occurs? 
2. I don't think it's [mWeb specific](https://github.com/Expensify/App/issues/32356#issuecomment-1836471964) judging by this proposal showing it happen on Web?

**Comment by MitchExpensify** [comment] 2024-03-10 20:48
> 1. When was this last tested? It was on hold for the VBBA refactor, came off hold, but I can't see if it has been retested and if it stills occurs? 

Can't reproduce on Android using Browserstack - @lanitochka17 can you please let me know if you are still seeing this on Android? 

mWeb on Browsterstack is also not playing nice for me. Can't log in:

<img width="412" alt="image" src="https://github.com/Expensify/App/assets/36425901/c3c43b49-8eb5-4d2a-b8fd-ab0e9886a7cd">


<img width="483" alt="image" src="https://github.com/Expensify/App/assets/36425901/2febfa98-8e26-4cc9-a720-1195b61d5546">

> 2. I don't think it's [mWeb specific](https://github.com/Expensify/App/issues/32356#issuecomment-1836471964) judging by this proposal showing it happen on Web?

Web is proving weird for me too - I'm getting booted from the VBA flow altogether on Safari v1.4.49-4

https://github.com/Expensify/App/assets/36425901/bfbeef27-81b1-44f1-99ac-e14bbb4c2147

Same on Chrome v1.4.49-4

https://github.com/Expensify/App/assets/36425901/2478338e-81b6-4ecd-98f9-604bf18e4fc2

@lanitochka17 Can you let me know what you are seeing when trying to take the reproduction steps on web too please?

**Comment by bernhardoj** [comment] 2024-03-11 05:23
Here is how it looks for me, the issue still persists. The plaid page is flashing and the connect step is shown for a few seconds.

https://github.com/Expensify/App/assets/50919443/f2ef636b-91ee-4478-a7b5-7bff6e0ea20c

> Web is proving weird for me too - I'm getting booted from the VBA flow altogether

Maybe try re-login to have fresh data.

**Comment by MitchExpensify** [comment] 2024-03-14 19:27
Oh wait.. is this issue a dupe of https://github.com/Expensify/App/issues/38069#issuecomment-1989615167 @abzokhattab / @eVoloshchak ?

**Closed** 2024-03-16 19:53 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted, Bug
