### ISSUE TITLE
[$1000] Inconsistent blurring of parent message in offline mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26036] opened 2023-08-27 14:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to staging new dot
2. Turn force online on
3. Go to any chat and send a message
4. Long press the message and click on reply on a thread
5. Send a message in the thread
6. Long press the parent message in the thread and click on edit and observe that even in edit mode the message is blurred
7. Go back to main chat and long press parent message and open edit mode
8. Observe that the parent message is not blurred when opened in edit mode

## Expected Result:
Parent message blurring should be consistent
## Actual Result:
Parent message is blurred out in thread but not in main chat when edited
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/ce04a722-5066-4f2e-8224-db87a38e028c

https://github.com/Expensify/App/assets/38435837/7ec470a5-401a-4013-a0fc-59acf4e8d4a9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692431934822249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c804b9b7ce7b7a1d</li>
        <li>Upwork Job ID: 1696153710008893440</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-08-30 13:14
@aimane-chnaif thoughts on the proposals above? TIA!

**Comment by CortneyOfstad** [comment] 2023-09-01 15:45
@aimane-chnaif Bump ^^^

**Comment by CortneyOfstad** [comment] 2023-09-05 14:01
@aimane-chnaif Bump on the above proposals ^^^ TIA!

**Comment by CortneyOfstad** [comment] 2023-09-11 15:05
@aimane-chnaif ^^^ TIA!

**Comment by CortneyOfstad** [comment] 2023-09-14 18:08
bump @aimane-chnaif ^^^

**Comment by shawnborton** [comment] 2023-09-15 01:48
Wow, I am having a hard time wrapping my head around this. What do you think @aimane-chnaif ?

**Comment by CortneyOfstad** [comment] 2023-09-18 20:06
Not overdue 👍

**Comment by CortneyOfstad** [comment] 2023-09-21 15:34
@aimane-chnaif bump on the questions above — TIA!

**Comment by shawnborton** [comment] 2023-09-22 00:56
> I am thinking "not blur in edit mode always"

Works for me!

**Comment by CortneyOfstad** [comment] 2023-09-27 13:02
@aimane-chnaif bump on the comment above ^^^ TIA!

**Comment by mvtglobally** [comment] 2023-09-28 03:13
Issue not reproducible during KI retests. (First week)

**Comment by SofoniasN** [comment] 2023-10-02 04:32
Hey @CortneyOfstad If this bug was solved by another PR i should still get the reporting bonus right? As this was a legitimate bug,  and created a month ago it would have been fixed here if it was not for all the delays. Let me know what you think. TIA

**Comment by CortneyOfstad** [comment] 2023-10-04 12:14
@SofoniasN bump on @aimane-chnaif's comment above ^^^

**Comment by CortneyOfstad** [comment] 2023-10-05 16:07
@SofoniasN bump ^^^

**Comment by CortneyOfstad** [comment] 2023-10-09 13:34
I was under the impression that if a PR fixed multiple bugs, the reporting bonus was not provided on any subsequent GHs. Can you confirm @madmax330?

**Comment by madmax330** [comment] 2023-10-10 16:45
@CortneyOfstad maybe ask in bug-zero or c+ I haven't heard of this either

**Comment by CortneyOfstad** [comment] 2023-10-16 15:12
> I was under the impression that if a PR fixed multiple bugs, the reporting bonus was not provided on any subsequent GHs. 

@sakluger I believe you and I talked about this on another GH. I believe that to be the case, but need a gut-check. Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-18 18:56
Bump @sakluger ^^^ Thank you!

**Comment by CortneyOfstad** [comment] 2023-10-18 19:58
I am heading OoO until Oct. 25 so reassigning BZ to keep an eye on this while I'm gone 👍

**Comment by joekaufmanexpensify** [comment] 2023-10-18 20:02
@CortneyOfstad as an fyi, I think [we are supposed to](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799) leave ourselves assigned to chores when going OOO, so you can take them back once you're back from OOO. So going to re-assign you back. 

Happy to watch this while you're out though!

**Comment by joekaufmanexpensify** [comment] 2023-10-18 20:08
I think the case here is covered well by the contributing guidelines that @aimane-chnaif [referenced above](https://github.com/Expensify/App/issues/26036#issuecomment-1742632061). 

It [sounds like ](https://github.com/Expensify/App/issues/26036#issuecomment-1749316673) this bug was fixed in [this PR. 
](https://github.com/Expensify/App/pull/26213) That PR is linked to [this issue 
](https://github.com/Expensify/App/issues/24263), and the bug in that issue was reported several weeks before the bug in this issue. Based on the guidelines, the reporter in this issue would not be eligible for a reporting bonus here.

**Comment by joekaufmanexpensify** [comment] 2023-10-18 20:10
Closing, as this bug is fixed, and no payment is needed here!

**Closed by joekaufmanexpensify** 2023-10-18 20:10 UTC
Labels: Engineering, Daily, Internal, Bug
