### ISSUE TITLE
Group Chat Not Returned in Search Results When Using Partial Match for Group Name

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52652] opened 2024-11-15 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1731679266749979)

## Action Performed:
1. Create a group chat with users 
2. Name the group as nyc crew in group details
3. Click the search icon and select Chats from LHN
4. Click the search from top right 
5. Enter nyc 
## Expected Result:
The chat group (nyc crew) displayed to select
## Actual Result:
Group chat not returned in search result using partial match
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

<img src="https://github.com/user-attachments/assets/d2a6face-8fec-476c-aea5-56bb8a8e8938" width="40%" height="40%">

https://github.com/user-attachments/assets/b996a11a-000b-4831-b049-ebdc948ed9dd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2024-11-15 20:11
This is an internal issue @trjExpensify FYI. It has to do with what reports are returned by the back-end in the SearchForReports command.

**Comment by trjExpensify** [comment] 2024-11-18 14:00
Makes sense! I have a feeling @luacmartins has a proposal out for this. Is that right?

**Comment by luacmartins** [comment] 2024-11-18 17:01
Yes, I do. Although, I'm not able to reproduce the issue in the OP.

**Comment by puneetlath** [comment] 2024-11-18 22:22
@luacmartins maybe it has something to do with the emoji in the name? 

<img width="705" alt="Screenshot 2024-11-18 at 4 22 17 PM" src="https://github.com/user-attachments/assets/6db1a5ec-1c65-4bc4-b7ea-20d371124b4e">

When I search `nyc` I get a bunch of reports returned, but not 8392053182833997. RequestID: 8e4b552baffde7df-DFW

And then this is when I search `nyc crew` I get just one report returned, which is 8392053182833997. RequestID: 8e4b5789ebd8e7df-DFW

I sent you both API responses on Slack.

**Comment by luacmartins** [comment] 2024-11-18 22:24
Cool, yea I imagine it's how we're prioritizing the results we send back.

**Comment by puneetlath** [comment] 2024-11-18 22:28
Right that makes sense. Since when I search "nyc" I only see 1 result in the search results, I assumed it was only returning one. But I see now it is returning a bunch that we don't end up showing.

**Comment by trjExpensify** [comment] 2024-11-22 13:33
> Yes, I do. Although, I'm not able to reproduce the issue in the OP.

Okay, do we need this issue then?

**Comment by luacmartins** [comment] 2024-11-22 18:17
We can probably close it since we have a project that'll fix this.

**Closed by luacmartins** 2024-11-22 18:17 UTC
Labels: Daily, Bug
