### ISSUE TITLE
mWeb - Login -Offline indicator is missing in "Resent link" page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11637] opened 2022-10-06 19:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. On the login screen - create a new account
3. Tap "Continue" button
4. Disable the internet connection in the device

## Expected Result:
The user should see a notification that user is offline.

## Actual Result:
Missing notification that user is offline.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web 

**Version Number:** v1.2.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194399863-28605d79-418e-416e-8187-232de6ffbdc4.mp4
<img src="https://user-images.githubusercontent.com/43996225/194400163-01101e95-5814-49c4-b747-b9dc35244b3e.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2022-10-06 19:47
@kavimuru can you re-test?

**Comment by AndrewGable** [comment] 2022-10-06 22:20
Also cannot reproduce, closing

**Closed by AndrewGable** 2022-10-06 22:20 UTC
Labels: DeployBlockerCash, Engineering, Hourly
