### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] mWeb - Cursor jumps back to the start when adding an emoji in edit

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28563] opened 2023-10-01 16:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report on staging ND
2. Send a text message
3. Hold on the message and tap on edit the message
4. Click the emoji button in the text input
5. select an emoji

## Expected Result:
The cursor should stay after the emoji when an emoji is added

## Actual Result:
The cursor jumps to the start of the text when an emoji is added while editing

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75.8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/62c422e0-4123-4310-97f4-d9b2b153d38d

https://github.com/Expensify/App/assets/93399543/ce03feb3-a78b-444e-8051-4d24d5e46207

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696174769247349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01edb4567dee0b0a57</li>
        <li>Upwork Job ID: 1708949538648821760</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-02 16:12
I cannot repro this in ios

**Comment by neil-marcellini** [comment] 2023-10-02 16:15
I'll check if I can reproduce it on Android Chrome now.

**Comment by jo-ui** [comment] 2023-10-02 17:58
@neil-marcellini @mountiny It is still reproducible on android chrome but not on ios. Please check again with cleared cookies.

**Comment by mountiny** [comment] 2023-10-02 19:01
Reopening to confirm

**Comment by sakluger** [comment] 2023-10-02 20:58
Since @jo-ui confirmed it is broken on android only, and Applause confirmed it's reproduceable on android, I'm going to add labels.

**Comment by sakluger** [comment] 2023-10-02 21:05
My bad, I missed the deploy blocker. I can't test via Browserstack - I just get an endless spinner after entering my email and tapping continue.

@neil-marcellini could you please help trying to reproduce again?

**Comment by neil-marcellini** [comment] 2023-10-03 18:20
@sakluger @jo-ui I'm not able to reproduce this on Android Chrome even after clearing all site data. I'm pretty sure it's not a problem. @jo-ui please upload a video reproducing the bug, if you still can. Maybe the test steps need to be more clear.

**Comment by jo-ui** [comment] 2023-10-03 18:26
@neil-marcellini https://github.com/Expensify/App/assets/57154082/3a7adb2b-4725-434e-b4d2-3d3896ace72b

**Comment by neil-marcellini** [comment] 2023-10-03 18:29
Ah yes I see thank you. I'm able to reproduce as well if I add the emoji by clicking the button in the text input. I'll update the test steps to be extra clear lol.

**Comment by abdulrahuman5196** [comment] 2023-10-06 12:45
Will review tonight

**Comment by abdulrahuman5196** [comment] 2023-10-06 13:41
TAL now

**Comment by abdulrahuman5196** [comment] 2023-10-06 14:33
@tienifr 's solution here https://github.com/Expensify/App/issues/28563#issuecomment-1746252206 feels like a workaround to avoid the mentioned native behaviour like added a new selectionAfterFocus ref. So I am not aligned on it totally, will wait for better proposals.
I am curious, is this bug happening recently due to any changes?

**Comment by abdulrahuman5196** [comment] 2023-10-06 14:33
To contributors, I am curious, is this bug happening recently due to any changes?

**Comment by neil-marcellini** [comment] 2023-10-13 16:36
Not overdue. I'll post to open source to get more eyes on it.

**Comment by sakluger** [comment] 2023-10-13 17:37
Thanks Neil. Hopefully we get some more proposals!

@bernhardoj it looks like you made a bit of progress but couldn't find the root cause. Any chance you were able to figure out what the issue was here?

**Comment by s-alves10** [comment] 2023-10-14 06:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Cursor moves to the first position when adding an emoji in edit composer box in mobile chrome

### What is the root cause of that problem?

Emoji item is a `Pressable` with style `user-select: 'none'`. This looks like a bug of Android chrome: When clicking an element with css `user-select: 'none'`, it disables the text selection of the element, but it causes the cursor of the last focused input element jump to the start position.

### What changes do you think we should make in order to solve the problem?

We can fix this issue by preventing default action of mouse events of `Pressable` element
Add the following props to the [EmojiPickerMenuItem](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenuItem/index.js)
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/EmojiPicker/EmojiPickerMenuItem/index.js#L72
```
        onMouseDown={(e) => e.preventDefault()}
        onMouseUp={(e) => e.preventDefault()}
```

This update works as expected

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/e59fdf25-9f64-439e-8732-aef20977c2d6

</details>


### What alternative solutions did you explore? (Optional)
We can prevent `onSelectionChange` event handler when composer is not focused

**Comment by abdulrahuman5196** [comment] 2023-10-15 07:55
@bernhardoj @s-alves10 

It seems you had mentioned the addition of `user-select: 'none'` is causing this issue. 

Why is the style added and what is required for? Will it cause any issue if we remove. It seems you added that style @s-alves10 


@s-alves10 Regarding the proposal here https://github.com/Expensify/App/issues/28563#issuecomment-1762647105 it seems to be hacky without proper root cause. I think we should investigate on root cause and avoid any regressions in future.

**Comment by abdulrahuman5196** [comment] 2023-10-16 16:39
As far as now we don't have any proposals to approve.
@sakluger

**Comment by sakluger** [comment] 2023-10-16 17:51
Asked for help in #expensify-callstack: https://expensify.slack.com/archives/C03UK30EA1Z/p1697478673562329.

**Comment by pac-guerreiro** [comment] 2023-10-17 09:20
I think this issue is similar to this one - https://github.com/Expensify/App/issues/21727

But the root cause is definitely different. I would debug the state of the TextInput from react-native-web when the emoji is introduced and check what is getting changed and force it to keep the position.

**Comment by pac-guerreiro** [comment] 2023-10-17 09:32
I'm able to reproduce this on desktop chrome if I toggle the device toolbar from the inspect menu!

https://github.com/Expensify/App/assets/48553277/08e47c07-9d96-455d-9301-86afff92127f

**Comment by sakluger** [comment] 2023-10-18 16:28
Started a discussion [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1697646428432589), hopefully we can get closer to understanding the root cause.

**Comment by sakluger** [comment] 2023-10-18 20:45
I think this bug is pretty low priority since it only affects Android Chrome, and the only bad side effect is that the user needs to move the cursor again. I'm going to close the issue so we can focus on higher priority bugs. Thanks everyone for looking into this one!

**Comment by jo-ui** [comment] 2023-10-19 05:05
@sakluger @neil-marcellini Shouldn't the reporting bonus be paid for this legit bug?

**Comment by situchan** [comment] 2023-10-19 05:20
If the bug is **not** fixed, not eligible for reporting bonus

**Comment by sakluger** [comment] 2023-10-20 23:32
Okay, opening back up because we're still discussing whether we should fix or not. But moving to weekly.

**Comment by sakluger** [comment] 2023-10-23 20:27
Asked CallStack for help to see if they can think of any solutions that fix both bugs.

**Comment by roksanaz** [comment] 2023-10-24 10:53
I am Roksana from Callstack - expert contributor group. I’d like to work on this job.

**Comment by sakluger** [comment] 2023-10-27 01:55
Thanks @roksanaz! Appreciate you digging into this one, and understand that it may take a little while to figure out. Keep us updated.

**Comment by roksanaz** [comment] 2023-10-27 15:59
Daily update: still work in progress.

**Comment by abdulrahuman5196** [comment] 2023-10-30 12:56
No update yet.

**Comment by roksanaz** [comment] 2023-10-30 20:10
Daily update: I'm investigating focus behavior for `ReportActionItemMessageEdit` and other reported issues connected with it, no interesting findings yet.

**Comment by roksanaz** [comment] 2023-10-31 16:48
Daily update: working on a proposal.

**Comment by roksanaz** [comment] 2023-11-03 16:20
Daily update: proposal almost ready.

**Comment by barros001** [comment] 2023-11-03 18:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When inserting an Emoji via Emoji Picker while editing a message, the cursor jumps back to the start of the input text. This only happens on Chrome on Android.

### What is the root cause of that problem?

I did a lot of experimentation and debugging around this issue, leaving only the barebones of composer and the issue was still there. My conclusion is that it's some odd bug that affects how chrome interacts with the react native input component. Being completely honest here, I can't really point specifically to the root cause of this issue but I decided to write a proposal anyways as I found out a way to solve it.

### What changes do you think we should make in order to solve the problem?

While experimenting, I exposed `setDraft` to the `window` object so that I could play around in console. I noticed that if I have the input text unfocused, then I call `setDraft` manually, then `document.querySelector('#messageEditInput').focus()`, it would focus, keyboard would show and cursors at the end, which is the expected result. I then stripped down `ReportActionItemMessageEdit.js` as much as I could to replicate that. Basically clicking an emoji would simply call `setDraf`, without anything else. I removed several other `useEffect` calls to avoid any possible side effects. To my surprise, it would still move the cursor to the start of the input.

Following line by line, clicking an emoji was doing exactly the same thing I was doing manually. I also tried remove the `setDraft` call after selecting an Emoji just to make sure the interaction with the Emoji selector popup wasn't causing anything. It still worked after calling `focus` via console. 

My conclusion: there's some odd race condition happening with the way things are rendered in React. Here's what I tried:

```js
    const addEmojiToTextBox = (emoji) => {
        window.setTimeout(() => {
            setSelection((prevSelection) => ({
                start: prevSelection.start + emoji.length + CONST.SPACE_LENGTH,
                end: prevSelection.start + emoji.length + CONST.SPACE_LENGTH,
            }));
            updateDraft(ComposerUtils.insertText(draft, selection, `${emoji} `));
        }, 0);
    };
```

I wrapped the `addEmojiToTextBox` in a `setTimeout` (note the 0, I'm not counting on timing anything, just giving the JS engine time to flush everything out by letting the current thread run its course before executing the method). It did work. 

See video below.

I understand this look like a workaround, but after spending a lot time trying to figure this one out, this is the only thing I could come up with, so I decided to post it as a proposal to see what the team thinks. Totally understandable if this is not an acceptable solution.


https://github.com/Expensify/App/assets/765936/88fb1e02-732c-46c1-91e4-2b73f0eae573





### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by sakluger** [comment] 2023-11-03 23:38
Adding another BZ member since I'm OOO all next week.

**Comment by trjExpensify** [comment] 2023-11-06 11:06
Cool, cool. It's helpful if you can to provide a quick summary of where we're at and the next steps for the BZ covering, especially on issues with a bunch of history. 

Am I right in thinking we've assigned this issue to @roksanaz and we're awaiting the output of the investigation to sense check it and proceed with a PR?

**Comment by trjExpensify** [comment] 2023-11-09 00:24
Same question as above for @roksanaz

**Comment by roksanaz** [comment] 2023-11-09 08:45
I'm sorry for taking so long. I did extensive tests and tried to really dig into this logic to understand the root cause. I also consulted this with the team. I think I understood what's going on. Here is the proposal:

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
In the chrome browser on Android devices when the user edits the message and chooses an emoji from the emoji modal, the cursor jumps back at the beginning of the input.
### What is the root cause of that problem?
As it was mentioned before, after the input refocuses, the selection is reset to the start of the input.
In terms of the code, this could be observed in the `Composer` component in the method called `addCursorPositionToSelectionChange`:
https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/components/Composer/index.js#L208-L231
When the modal closes and the input is focused `addEmojiToTextbox` method is called. It updates the input text and sets new `selection` (position of the cursor).
https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/pages/home/report/ReportActionItemMessageEdit.js#L329-L335
Although selection in the `ReportActionItemMessageEdit` was set correctly, `event.nativeEvent.selection` in `addCursorPositionToSelectionChange` was reset to {start: 0, end: 0}.
### What changes do you think we should make in order to solve the problem?
Because	we force focus method with delay here:
https://github.com/Expensify/App/blob/69227b43eef8ce958468df0b0696662aaaa2aaa5/src/pages/home/report/ReportActionItemMessageEdit.js#L361
setting the cursor position before all the animations and interactions finish caused the `selection` being reset to 0.
Moreover, from comparing the edit composer with the new message composer (https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js) I learnt that the input should be updated before setting new selection.
Therefore, `addEmojiToTextbox` method should be refactored, so that the new input is set first and then we should wait until the animations end to set the new selection:

```
const addEmojiToTextBox = (emoji) => {
    updateDraft(ComposerUtils.insertText(draft, selection, `${emoji} `));
    InteractionManager.runAfterInteractions(() => {
      setSelection((prevSelection) => ({
        start: prevSelection.start + emoji.length + CONST.SPACE_LENGTH,
        end: prevSelection.start + emoji.length + CONST.SPACE_LENGTH,
      }));
    });
  };
```

**Comment by roksanaz** [comment] 2023-11-09 08:50
Also, I'd like to let you know that @artus9033 will take over this issue.

**Comment by trjExpensify** [comment] 2023-11-09 10:42
Oh, okay. @artus9033, I'm assigning you. @abdulrahuman5196 can you review the above in the meantime? Thanks!

**Comment by trjExpensify** [comment] 2023-11-09 10:43
Ah, @artus9033 you'll need to comment on this issue for me to assign you.

**Comment by artus9033** [comment] 2023-11-09 11:14
Sure, thank you @trjExpensify

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:42
Hi, Will review today, just back from weekend

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:44
Melvin not removing overdue for some reason

**Comment by trjExpensify** [comment] 2023-11-13 14:19
Ah, I think that's probably because someone starred me on the issue. :) Looking forward to your review!

**Comment by abdulrahuman5196** [comment] 2023-11-13 18:17
@roksanaz / @artus9033 InteractionManager.runAfterInteractions doesn't work properly with the web as per docs https://reactnative.dev/docs/interactionmanager


https://github.com/Expensify/App/assets/46707890/af502b6a-62c6-4b5e-ae94-d91a721b2b03

**Comment by artus9033** [comment] 2023-11-16 09:39
Thanks @abdulrahuman5196, I investigated this and am working on a modified proposal

**Comment by artus9033** [comment] 2023-11-16 14:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In the chrome browser on Android devices when the user edits the message and chooses an emoji from the emoji modal, the cursor jumps back at the beginning of the input.

### What is the root cause of that problem?

As it was mentioned before, after the input refocuses, the selection is reset to the start of the input.

In terms of the code, this could be observed in the `Composer` component in the method called `addCursorPositionToSelectionChange`:

https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/components/Composer/index.js#L208-L231

When the modal closes and the input is focused addEmojiToTextbox method is called. It updates the input text and sets new selection (position of the cursor).

https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/pages/home/report/ReportActionItemMessageEdit.js#L329-L335

Although selection in the `ReportActionItemMessageEdit` was set correctly, `event.nativeEvent.selection` in `addCursorPositionToSelectionChange` was reset to `{start: 0, end: 0}`.

### What changes do you think we should make in order to solve the problem?

Because	we force focus method with delay here:

https://github.com/Expensify/App/blob/69227b43eef8ce958468df0b0696662aaaa2aaa5/src/pages/home/report/ReportActionItemMessageEdit.js#L361

setting the cursor position before all the animations and interactions finish caused the selection being reset to 0.

Moreover, from comparing the edit composer with the new message composer (https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js) it is visible that the input should be updated before setting new selection.

Finally, it turns out that on mWeb runAfterInteractions's callback is invoked with such a delay that allows `Composer` to call `onSelectionChange` inbetween and reset selection to `{ start: 0, end: 0 }`. This can be solved by copying the value of selection and hoisting it in the outer scope wrapping runAfterInteractions.

Therefore, `addEmojiToTextbox` method should be refactored, so that the new input is set first and then we should wait until the animations end to set the new selection:

```typescript
const addEmojiToTextBox = (emoji) => {
    updateDraft(ComposerUtils.insertText(draft, selection, `${emoji} `));

    // the below evades a problem occurring on mobile devices, where onSelectionChange fires with { start: 0, end: 0 } before runAfterInteractions's callback is invoked
    const prevSelectionSnapshot = { ...selection };
    InteractionManager.runAfterInteractions(() => {
        setSelection({
            start: prevSelectionSnapshot.start + emoji.length + CONST.SPACE_LENGTH,
            end: prevSelectionSnapshot.start + emoji.length + CONST.SPACE_LENGTH,
        });
    });
};
```

**Comment by abdulrahuman5196** [comment] 2023-11-20 15:56
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-11-20 16:10
@artus9033 latest proposal here https://github.com/Expensify/App/issues/28563#issuecomment-1814500908 looks good and works well 

🎀 👀 🎀
C+ Reviewed

cc: @neil-marcellini

**Comment by sakluger** [comment] 2023-11-21 22:42
@neil-marcellini friendly bump for your review.

**Comment by neil-marcellini** [comment] 2023-11-22 19:26
> @artus9033 latest proposal here [#28563 (comment)](https://github.com/Expensify/App/issues/28563#issuecomment-1814500908) looks good and works well
> 
> 🎀 👀 🎀 C+ Reviewed
> 
> cc: @neil-marcellini

I agree. Thanks for the bump Sasha!

**Comment by neil-marcellini** [comment] 2023-11-22 19:27
@artus9033 please go ahead and raise a PR

**Comment by barros001** [comment] 2023-11-22 20:50
> @artus9033 does your proposal fix [#30835 (comment)](https://github.com/Expensify/App/pull/30835#issuecomment-1812689152) as well?

Just wanted to point out that this should no longer be an issue since merging https://github.com/Expensify/App/pull/31279

**Comment by artus9033** [comment] 2023-11-23 15:16
> @artus9033 does your proposal fix [#30835 (comment)](https://github.com/Expensify/App/pull/30835#issuecomment-1812689152) as well?

No, these are separate problems

**Comment by artus9033** [comment] 2023-11-23 17:54
> > @artus9033 does your proposal fix [#30835 (comment)](https://github.com/Expensify/App/pull/30835#issuecomment-1812689152) as well?
> 
> Just wanted to point out that this should no longer be an issue since merging #31279

@barros001  Tested just now and both the original issue addressed in https://github.com/Expensify/App/pull/30835#issuecomment-1812689152 and the new one on iOS are still reproducible after pulling the latest changes from `main`, both with and without the fix.

**Comment by artus9033** [comment] 2023-11-23 17:59
> @artus9033 please go ahead and raise a PR

Absolutely, it will be there tomorrow

**Comment by artus9033** [comment] 2023-11-23 18:03
> @artus9033 please go ahead and raise a PR

Absolutely, it will be there shortly

**Comment by artus9033** [comment] 2023-11-23 20:18
@abdulrahuman5196 the PR is ready for review

**Comment by barros001** [comment] 2023-11-24 00:44
> > > @artus9033 does your proposal fix [#30835 (comment)](https://github.com/Expensify/App/pull/30835#issuecomment-1812689152) as well?
> > 
> > 
> > Just wanted to point out that this should no longer be an issue since merging #31279
> 
> @barros001 Tested just now and both the original issue addressed in [#30835 (comment)](https://github.com/Expensify/App/pull/30835#issuecomment-1812689152) and the problem on iOS are still reproducible after pulling the latest changes from `main`, both with and without the fix.

My bad, I see now that it’s a different root cause that only affect iOS.

**Comment by abdulrahuman5196** [comment] 2023-12-18 07:56
@neil-marcellini to check on this - https://github.com/Expensify/App/pull/31611#issuecomment-1845696403

**Comment by trjExpensify** [comment] 2023-12-18 13:14
@sakluger I'm dropping off this issue as [you're back](https://github.com/Expensify/App/issues/28563#issuecomment-1793242916).

**Comment by neil-marcellini** [comment] 2024-03-01 21:52
Closing the old PR, per [this comment](https://github.com/Expensify/App/pull/31611#issuecomment-1971479388), and re-assigning this to @MrRefactor. Sorry for the delay, it got lost in all the noise! Thanks for the DMs to raise it back to my attention.

**Comment by neil-marcellini** [comment] 2024-03-01 21:53
@MrRefactor would you please comment so myself or @sakluger can assign you?

**Comment by MrRefactor** [comment] 2024-03-02 00:21
> @MrRefactor would you please comment so myself or @sakluger can assign you?

Hey! I will open new pr soon

**Comment by abdulrahuman5196** [comment] 2024-04-01 12:50
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Send a message to a chat
2. Long-press it and select "Edit comment" in the context menu
3. Append a new emoji from the emoji picker sliding menu - repeat this in several edge cases: in-between existing text, after text, before text
4. Ensure the cursor position is each time in the expected position and does not jump to the start of the text

**Comment by sakluger** [comment] 2024-04-08 15:31
Summarizing payment on this issue:

Bug reporter: @jo-ui $50, sent [offer](https://www.upwork.com/nx/wm/offer/101780974) via Upwork
Contributor: @MrRefactor, No payment required
Contributor+: @abdulrahuman5196 $500, sent [offer](https://www.upwork.com/nx/wm/offer/101780930) via Upwork

**Comment by abdulrahuman5196** [comment] 2024-04-08 15:42
@sakluger  accepted the offer

**Comment by jo-ui** [comment] 2024-04-10 19:28
@sakluger I accepted the offer

**Comment by sakluger** [comment] 2024-04-12 17:45
Thanks everyone! I paid out all contracts and created a separate issue for the new regression test steps.

**Closed by sakluger** 2024-04-12 17:45 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
