### ISSUE TITLE
[$500] Compose - The list of users in mentions does not disappear when using the Shift+Enter

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35518] opened 2024-01-31 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4257656
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Navigate to any conversation
4. Paste the text "@boss" into the Compose Box
5. Press Shift+Enter 5-6 times

## Expected Result:
When using the Shift+Enter keyboard shortcut, the list of users should disappear or remain above the Compose Box and not overlap it

## Actual Result:
The list of users in mentions does not disappear when using the Shift+Enter keyboard shortcut.

## Workaround:
Unknow

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native - the user menu flickers
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/27408a51-5ac0-468b-87b5-337b0498ae10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d7b4a51ced33c18</li>
        <li>Upwork Job ID: 1752806230104039424</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-31 21:30
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by Tony-MK** [comment] 2024-01-31 23:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Compose - The list of users in mentions does not disappear when using the Shift+Enter

### What is the root cause of that problem?

We are not handling `SHIFT+ENTER` in [`triggerHotkeyActions`](https://github.com/Expensify/App/blob/995902a7fda139b95c60849a85a292f593623ddf/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L110-L126) found in the [`SuggestionMention`](https://github.com/Expensify/App/blob/995902a7fda139b95c60849a85a292f593623ddf/src/pages/home/report/ReportActionCompose/SuggestionMention.js) component.

https://github.com/Expensify/App/blob/995902a7fda139b95c60849a85a292f593623ddf/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L110-L126

### What changes do you think we should make in order to solve the problem?


Just like how we handled the `ESC` shortcut, let's handle the `SHIFT+ENTER` by inserting the following code snippet in [`triggerHotkeyActions`](https://github.com/Expensify/App/blob/995902a7fda139b95c60849a85a292f593623ddf/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L110-L126).

```
if (e.shiftKey && e.key === CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey && suggestionsExist){
  resetSuggestions();
}
```

**Comment by abdulrahuman5196** [comment] 2024-02-05 13:53
Will work on review today

**Comment by zanyrenney** [comment] 2024-02-07 16:04
did you review yet please @abdulrahuman5196

**Comment by zanyrenney** [comment] 2024-02-09 18:58
bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:23
Hi, Sorry for the delay reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:54
The issue can be reproduced with any mentions like `@a` and just pressing shift + enter. 
I had an initial review on the proposals. I would need some more time on this. Will check and update on the progress tomorrow.

**Comment by zanyrenney** [comment] 2024-02-14 17:35
hey @abdulrahuman5196 have you been able to look into this in more detail? And review the proposal you think is viable?

**Comment by abdulrahuman5196** [comment] 2024-02-14 18:28
I haven't been confirm on it. Will try to close it out in a day

**Comment by abdulrahuman5196** [comment] 2024-02-15 09:41
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-15 12:10
On @Krishna2323 's proposal to `We should update the if check here to return false if we have a empty string at the end`, this wouldn't viable since currently we do consider space between words as part of suggestion search string. 

On @Tony-MK 's proposal here https://github.com/Expensify/App/issues/35518#issuecomment-1920190097, the solution doesn't seem work consistently. The suggestions close up when we press the keys, but popup again when we go to the new line.

**Comment by abdulrahuman5196** [comment] 2024-02-15 12:12
@dukenv0307 's proposal here https://github.com/Expensify/App/issues/35518#issuecomment-1920503529 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by zanyrenney** [comment] 2024-02-16 15:38
bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-02-16 16:15
FYI: Just to make sure its visible. 
C+ approved comment is here https://github.com/Expensify/App/issues/35518#issuecomment-1945976022

**Comment by abdulrahuman5196** [comment] 2024-02-19 09:05
Waiting on PR

**Comment by abdulrahuman5196** [comment] 2024-03-05 09:18
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be regression. It was the same case for sometime.

>Determine if we should create a regression test for this bug.

Yes.

> If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Log in under your HT account
2) Navigate to any conversation
3) Paste the text "@BOSS" into the Compose Box
4) Press Shift+Enter 5-6 times
5) Verify that: the list of users disappears

@zanyrenney Completed checklist and this issue is on payment due for 7th March. Seems melvin didn't update here.

**Comment by abdulrahuman5196** [comment] 2024-03-23 14:59
@zanyrenney Bump on the above. Seems this issue is pending for 2 weeks.

**Comment by zanyrenney** [comment] 2024-04-02 11:57
I've been OOO since payment was due. I will take a look now.

**Comment by zanyrenney** [comment] 2024-04-02 12:00
@abdulrahuman5196 you ended the contract ? 
![2024-04-02_12-59-33](https://github.com/Expensify/App/assets/56830058/ae2a7de5-7f68-4f03-a8fb-3a0a795aeb8f)
 How come? 

If payment was still due, you've now made it impossible for me to pay through the correct workflow 😅

**Comment by zanyrenney** [comment] 2024-04-02 12:01
payment summary:
@dukenv0307 paid $500 through upwork. 🎉 

@abdulrahuman5196 you have ended the contract so not sure how you wanted / expected me to pay?

**Comment by abdulrahuman5196** [comment] 2024-04-02 12:40
@zanyrenney Sorry, could have ended it by mistake.

I applied again - https://www.upwork.com/ab/proposals/1775141076017627137?success

**Comment by zanyrenney** [comment] 2024-04-02 14:21
![2024-04-02_15-21-18](https://github.com/Expensify/App/assets/56830058/0aec6b37-daf5-478c-868a-ae255948425b)

**Comment by zanyrenney** [comment] 2024-04-02 14:22
Using a bonus as payment as easier than restarting a new contract

paid @abdulrahuman5196 $500 through Upwork.

**Closed by zanyrenney** 2024-04-02 14:22 UTC
Labels: Reviewing, External, Weekly, Bug
