### ISSUE TITLE
[$500] Desktop - Reload - ''Hmm... it's not here'' when reloading the desktop app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31592] opened 2023-11-20 22:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the desktop app
2. Press Cmd + R or click on the View menu, then select ''Reload''

## Expected Result:
No errors should be encountered when reloading the app

## Actual Result:
When reloading the app, a 'page not found' error is displayed
Hmm... it's not here
Oops, this page cannot be found
Go back to home page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  @

https://github.com/Expensify/App/assets/78819774/da9e5fee-acae-469b-bd0f-9cd281197670

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc65658e91d3dd1c</li>
        <li>Upwork Job ID: 1726776353641140224</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-11-20 22:55
Production:

https://github.com/Expensify/App/assets/78819774/648ba9f7-af05-44da-9f13-73f080322030

**Comment by luacmartins** [comment] 2023-11-20 23:35
I can reproduce this and see the following logs. It seems like we're intentionally navigating to that page.

```
[info] Navigating to route - {"path":"/not-found"}
```

**Comment by erquhart** [comment] 2023-11-21 02:33
Likely same root cause as https://github.com/Expensify/App/issues/28495, may be a dupe.

**Comment by situchan** [comment] 2023-11-21 08:55
Not able to reproduce on main. Or does this happen only in release build?

**Comment by situchan** [comment] 2023-11-21 08:56
@tienifr this is deploy blocker so there must be offending PR recently merged. https://github.com/Expensify/App/issues/28495 was open for a while.

**Comment by situchan** [comment] 2023-11-21 14:58
For me, this happens on android chrome as well. Still interesting that not reproducible on iOS safari.


https://github.com/Expensify/App/assets/108292595/55ec7e30-d3d7-44fd-87a7-897b5b0590a7

**Comment by situchan** [comment] 2023-11-21 15:50
I just reproduced this today. I have been testing with https://127.0.0.1/ so far after https integration but used to work fine.

**Comment by situchan** [comment] 2023-11-21 15:51
So I can conclude that @tienifr's solution is just workaround without fixing the root cause.
We should really find out the offending PR.

**Comment by s77rt** [comment] 2023-11-21 17:16
This may be a dupe. I think this issue existed for a while but due to another factor the bug is constantly reproducible now.

I tested this on v1.3.83-0. The bug is there but not very easy to reproduce


https://github.com/Expensify/App/assets/16493223/2b1856b3-58da-4d0d-8cdc-5715aa1c64e2

**Comment by mallenexpensify** [comment] 2023-11-21 17:17
Been working on a similar issue for weeks that might be related.  I'm also getting the 'hmm' error after every time I've updated the app the past two days. 
https://github.com/Expensify/App/issues/28495

**Comment by mallenexpensify** [comment] 2023-11-21 17:56
From Tim G in[ this internal thread](https://expensify.slack.com/archives/C03SSAQ7P/p1700580653535909?thread_ts=1700526752.405659&cid=C03SSAQ7P), in case it's helpful:

1. If there is a reportID in the URL, load that report. (if you do not have access to that report, you are shown "not found")
2. Sort all reports in Onyx by their lastReadTime
3. if openOnAdminRoom param is in the URL, then fine the first report where the chat type is policyAdmins and assign it to the variable adminReport
4. If isFirstTimeNewExpensifyUser and there is only 1 sorted report, load that report
5. If there is more than 1 sorted report, and there is adminReport, load the first sorted report that is not concierge
6. If they are not in the domain rooms beta
7. filter the sorted reports to only contain non-domain chats, workspace chats, chats with their guides
8. If adminReport exists, load it
9. else load the last sorted report

The bulk of that logic is here: https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L596-L631

**Comment by luacmartins** [comment] 2023-11-21 18:54
This seems to be a dupe of https://github.com/Expensify/App/issues/28495 and given the [video](https://github.com/Expensify/App/issues/31592#issuecomment-1821337867) @s77rt shared, it seems like a race condition that was made worse with the last deploy. I'm gonna remove the deploy blocker label since this is already happening in previous versions, just not as noticeable. We need to keep investigating and fix this though.

**Comment by s77rt** [comment] 2023-11-24 18:48
@luacmartins Shouldn't we close this one?

**Comment by luacmartins** [comment] 2023-11-24 20:32
Yea, we should be good to close.

**Closed by luacmartins** 2023-11-24 20:32 UTC
Labels: External, Engineering, Daily, Help Wanted
