### ISSUE TITLE
Web - Split Bill -  Infinite navigation loop

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21076] opened 2023-06-19 19:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any 1:1 chat
1. Hit the `+` button in the composer, then select `Request Money`
1. Enter an amount, then hit `Save` to get to the next step
1. Press `<` in the header to return to the amount page
1. Press `<` in the header.

## Expected Result:
 The RHP should close and you should return to your chat

## Actual Result:
You are taken back to the confirmation step.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/946c835d-9c96-412d-8226-d3e5d6dbe635

**Expensify/Expensify Issue URL:**

**Issue reported by:** Rory Abraham

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686440796898279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AmjedNazzal** [comment] 2023-06-19 19:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Split Bill -  Infinite navigation loop

### What is the root cause of that problem?

I'm not sure if this is by design or just a simple error made during coding but the behaviour stems from navigateBack registering isEditingAmountAfterConfirm as true and calling navigateToStep when currentStepIndex is 0, in other words we call navigateToStep instead of navigateToPreviousStep when the index is 0 which prevents the modal from closing.
https://github.com/Expensify/App/blob/8456d27561414caf7467d5861ee42a48a3f034f0/src/pages/iou/MoneyRequestModal.js#L328-L329

### What changes do you think we should make in order to solve the problem?

We could change the rule for isEditingAmountAfterConfirm to be true if currentStepIndex is not 0. by doing this we ensure that the modal closes on back button if the index of the steps is 0.
```javascript
const isEditingAmountAfterConfirm = currentStepIndex !== 0 && previousStepIndex === _.indexOf(steps, Steps.MoneyRequestConfirm);
```

### Result

https://github.com/Expensify/App/assets/74202751/d62bf468-f76a-4b56-aede-2292577ad912

**Comment by s-alves10** [comment] 2023-06-19 21:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Money Request/Split bill modals fall in infinite navigation loop

### What is the root cause of that problem?

In the current code, previousStepIndex and currentStepIndex are previous and current step indices. In the case we open the money request dialog from the composer `+` button, we have only 2 pages in the modal stack(amount and confirmation) and the index of confirmation page is 1.

https://github.com/Expensify/App/blob/9559a54b0ee5e718f14cc0d05afc143f9d5cf073/src/pages/iou/MoneyRequestModal.js#L328-L329

Selecting amount in the confirmation page(index = 1) goes to the amounts page(index = 0). In this case previousStepIndex = 1, currentStepIndex = 0, and isEditingAmountAfterConfirm becomes true in the above code. This is right. But isEditingAmountAfterConfirm becomes true in the case back button is clicked in confirmation page as well. This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

We need to change the role of `previousStepIndex`.
1. Define `previousStepIndex` as the index of previous page for the unusual navigation such as confirmation -> amount. In other cases its value is -1.
2. Change the `navigateToPreviousStep` so that goes to `previousStepIndex` if it has value, or goes to `currentStepIndex - 1` page
3. Change the `navigateToNextStep` so that goes to `previousStepIndex` if it has value, or goes to `currentStepIndex + 1` page
4. `Back` button calls `navigateToPreviousStep` and `Next` button calls `navigateToNextStep`

These definition and logic are clear than before and works perfect


<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/acb4e967-2e7e-49aa-8149-575092fe337c

</details>

### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-06-20 04:18
Oh interesting @hungvu193 - I had a look at the current split bill issues and couldn't pinpoint the GH. @bernhardoj if this is a dupe, could you link the other GH? Cheers!

**Comment by bernhardoj** [comment] 2023-06-20 04:22
Yes, it's a dupe of https://github.com/Expensify/App/issues/17637.

**Comment by jliexpensify** [comment] 2023-06-21 07:01
Great, thanks @bernhardoj ! Going to close this one in favour of the other issue, which is currently on hold for now.

**Closed by jliexpensify** 2023-06-21 07:01 UTC
Labels: Daily, Bug
