### ISSUE TITLE
[$500] Room - First workspace becomes highlighted by default when creating new room for 2nd time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34393] opened 2024-01-11 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB > New Chat > room > workspace
2. Observe no workspace is highlighted
3. Select the first workspace
4. Click outside of the panel to close it
5. Re do step 1

## Expected Result:
No workspace should be highlighted by default

## Actual Result:
The first workspace becomes highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/83916383-75bf-4971-92b0-6d04d0c234e3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc4717bf898902a4</li>
        <li>Upwork Job ID: 1745546481285779456</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by BriniM** [comment] 2024-01-11 21:17
### Please re-state the problem that we are trying to solve in this issue.
Open and close the add new room UI, after filling in some information ofcourse. on reopening, the workspace field still has the previously selected value. (which should be discarded).
### What is the root cause of that problem?
The workspace input field (with id PolicyID), is not reset when reinitializing the component.
### What changes do you think we should make in order to solve the problem?
In WorkspaceNewRoomPage.js, 
```js
        useEffect(() => {
          Report.clearNewRoomFormError();
          // add this, line 138.
          setPolicyID(null);
    }, []);
```
### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment] 2024-01-11 21:34
## Please re-state the problem that we are trying to solve in this issue.
In selection list, the focusedIndex is set as `0` even tho it should be `-1`

## RCA
This happens because when `sections` change after first render of `SelectionList`, `updateAndScrollToFocusedIndex` is called. 

It sets the index focused index to `0`.
https://github.com/Expensify/App/blob/c080ccca3e7d93183ea951303aac8171ee92e967/src/components/SelectionList/BaseSelectionList.js#L375-L377

## Solution

Change the dependency array of the useEffect to update only when its length changes `[sections?.length]`

https://github.com/Expensify/App/blob/c080ccca3e7d93183ea951303aac8171ee92e967/src/components/SelectionList/BaseSelectionList.js#L379

**Comment by DylanDylann** [comment] 2024-01-12 03:36
I think we should hold for https://github.com/Expensify/App/issues/29080

**Comment by sophiepintoraetz** [comment] 2024-01-14 23:41
@aimane-chnaif - do you agree?

**Comment by sophiepintoraetz** [comment] 2024-01-25 02:31
No update here - linked holding PR is still in review.

**Comment by lschurr** [comment] 2024-02-05 16:22
Any update @aimane-chnaif?

**Comment by lschurr** [comment] 2024-02-19 19:51
Looks like this PR is merged but not yet on Prod - are we still waiting on that @aimane-chnaif?

**Comment by lanitochka17** [comment] 2024-02-23 17:57
@aimane-chnaif Hello. The first workspace always becomes highlighted


https://github.com/Expensify/App/assets/78819774/c3d090d2-ff0e-49d9-9898-46121ee44d51

**Comment by lschurr** [comment] 2024-02-28 16:09
@aimane-chnaif any update on this one?

**Comment by lschurr** [comment] 2024-03-07 20:13
@aimane-chnaif - Can you please provide an update on this one?

**Comment by lschurr** [comment] 2024-03-11 15:03
So we're waiting on proposals, is that right @aimane-chnaif?

**Comment by lschurr** [comment] 2024-03-18 15:38
Still waiting on proposals.

**Comment by lschurr** [comment] 2024-03-19 17:46
@aimane-chnaif - Should this be open to proposals externally? Is the original bug still happening?

**Comment by lschurr** [comment] 2024-03-19 21:20
Discussing here - https://expensify.slack.com/archives/C01GTK53T8Q/p1710877793579389

**Comment by lschurr** [comment] 2024-03-20 15:36
Based on the Slack thread, I think we're going to ask QA to test again. @lanitochka17 can you confirm this bug is still reproducible?

**Comment by lschurr** [comment] 2024-03-25 15:37
Asking for help from QA: https://expensify.slack.com/archives/C9YU7BX5M/p1711381040209419

**Comment by kavimuru** [comment] 2024-03-25 16:05
@ishpaul777 bug is not rproducible

https://github.com/Expensify/App/assets/43996225/722cc83d-391c-4c1f-98ae-922fbc3e19f2

**Comment by lschurr** [comment] 2024-03-25 16:07
Closing since we're unable to reproduce.

**Closed by lschurr** 2024-03-25 16:07 UTC
Labels: Engineering, Daily, Internal, Bug
