### ISSUE TITLE
[HOLD for payment 2023-10-25] [ECard Transactions] Update Report Preview Logic to support rendering JSX

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28830] opened 2023-10-04 15:26 UTC
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=id.zalljxs7o0fd

### Overview 

**Goal:** 
Add support for displaying [ReceiptBackground](https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.ccj1ab3m8lq) component to the current logic for displaying receipts that is used in the [ReportPreview](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/ReportPreview.js#L186), [MoneyRequestAction](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyRequestAction.js#L80)/[MoneyRequestPreview](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyRequestPreview.js#L140), and [MoneyRequestView](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyRequestView.js#L56) components. Currently we only support images, docX, and SVG from the Scan Receipt project. Most of this logic will be handled by updating  [ReportActionItemImages](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/ReportActionItemImages.js#L66) / [ReportActionItemImage](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/ReportActionItemImage.js#L36).

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f38c76665e594519</li>
        <li>Upwork Job ID: 1709591008839544832</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-10-16 13:14
@burczu please let us know if you can prioritize reviewing this one today, as this is related to a project with a deadline coming up EOW.

**Comment by puneetlath** [comment] 2023-10-17 02:17
@joekaufmanexpensify going to re-assign BZ role to you since this is for wave8.

**Comment by joekaufmanexpensify** [comment] 2023-10-23 14:03
@burczu mind proposing a new regression test for this? Once that's done, we can close this one (since no direct payment is required here)

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:08
Bumped [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1698242910310589).

**Comment by joekaufmanexpensify** [comment] 2023-10-26 12:30
Switching assignees based on [this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1698315838648109?thread_ts=1698242910.310589&cid=C02NK2DQWUX), since Rushat reviewed this PR.

**Comment by joekaufmanexpensify** [comment] 2023-10-30 13:47
Not overdue. @rushatgabhane is anything needed for the BZ checklist here?

**Comment by joekaufmanexpensify** [comment] 2023-11-01 13:39
Still pending input

**Comment by joekaufmanexpensify** [comment] 2023-11-03 13:38
Okay got it. We will add regression tests for the entire issue holistically once it's implemented then. Closing as this is otherwise all set!

**Closed by joekaufmanexpensify** 2023-11-03 13:38 UTC
Labels: Daily, Internal, NewFeature, Awaiting Payment
