### ISSUE TITLE
IOS / Android - Extra spacing above the header at additional details page

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10367] opened 2022-08-11 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Fab icon > 
2. Send money > 
3. onfido verification > 
4. Additional details page

## Expected Result:
There shouldn't be extra space above the header

## Actual Result:
There's extra space above the header on native

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.86-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="301" alt="180059933-052973c1-b676-46ba-be29-5679d5c319de" src="https://user-images.githubusercontent.com/43995119/184224577-dcf79e8c-ff1a-47fa-8231-fcffe74b2b4b.png">
![180063394-2ead695b-eb00-4ad2-b489-1c2fd7988b02](https://user-images.githubusercontent.com/43995119/184224579-a509c5e3-615a-495d-bbf3-ffeddeb54d7a.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659042770219849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2022-08-12 17:22
I can't triage this properly because I have "UK" wallet so can only opt to send money outside expensify.

**Comment by MitchExpensify** [comment] 2022-08-12 22:32
Can you provide more specific reproduction steps please @thesahindia, not sure exactly how you are getting to that screen

**Comment by MitchExpensify** [comment] 2022-08-15 23:54
Bump on the above request @thesahindia

**Comment by thesahindia** [comment] 2022-08-16 14:39
I tested it by rendering this page at a different route. But there are two ways to reach this page ( I found them on some other issues )

1st way (not really sure about this but you have to in some beta for this) -

1. Click on Fab icon
2. Send money
3. Complete the Onfido verification

2nd -
1. Go to Settings
2. Go to Payments
3. Click on Transfer Balance (you must have some balance available)

@mvtglobally, please help if you have the exact steps to repro

**Comment by thesahindia** [comment] 2022-08-22 04:50
Found the steps -
1. The account already has a bank account added.
2. Hit green plus button
3. Send money
4. Enter amount
5. Enter email
6. Pay with Expensify

cc: @MitchExpensify

**Comment by MitchExpensify** [comment] 2022-08-22 17:18
Thanks @thesahindia, I followed those steps and still cannot reproduce this

**Comment by MitchExpensify** [comment] 2022-08-25 23:38
@mvtglobally mind giving this a buddy check for me? Are you able to reproduce this?

**Comment by MitchExpensify** [comment] 2022-08-29 21:07
Lil bump @mvtglobally, thank you!

**Comment by mvtglobally** [comment] 2022-08-30 02:55
@MitchExpensify I was not able to repro, but asked the team as well to see if anyone can repro

**Comment by MitchExpensify** [comment] 2022-08-31 08:18
Thank you! Will see if they can and go from there

**Comment by MitchExpensify** [comment] 2022-09-05 16:16
Nobody able to reproduce, closing

**Comment by thesahindia** [comment] 2022-09-19 19:23
@MitchExpensify, this is still reproducible 
(ss from latest main branch build)
![Simulator Screen Shot - iPhone 13 - 2022-09-20 at 00 50 26](https://user-images.githubusercontent.com/83179295/191098661-9baf4c43-b17f-4acc-9059-656c8ed518f9.png)

**Comment by roryabraham** [comment] 2022-09-24 01:13
Got a PR up to fix this and a few related bugs: https://github.com/Expensify/App/pull/11257

**Comment by thesahindia** [comment] 2022-09-30 09:51
Can we reopen as this is eligible for the reporting?

**Comment by roryabraham** [comment] 2022-09-30 19:06
@MitchExpensify Let's make sure @thesahindia gets his reporting bonus here. Thanks

**Comment by MitchExpensify** [comment] 2022-09-30 19:13
Offer sent -[ Upwork Job ](https://www.upwork.com/ab/applicants/1575926256585416704/suggested)

**Comment by thesahindia** [comment] 2022-09-30 19:15
> Offer sent -[ Upwork Job ](https://www.upwork.com/ab/applicants/1575926256585416704/suggested)

Accepted 🚀

**Comment by MitchExpensify** [comment] 2022-09-30 19:24
Paid, thanks @thesahindia !

**Closed by MitchExpensify** 2022-09-30 19:24 UTC
Labels: Engineering, Weekly, Improvement
