### ISSUE TITLE
[HOLD for payment 2024-09-16] [$250] [Critical] [UX reliability] The plaid modal is taking long to load in the bottom up flow and not found page is shown

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42756] opened 2024-05-29 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1716940673539529

## Action Performed:
Break down in numbered steps

BUG: Plaid connection is taking a very long time when I click Pay with Expensify for the first time
1. [daniel@expensify.com](mailto:daniel@expensify.com) submitted [danrvidal+upgradetest7@gmail.com](mailto:danrvidal+upgradetest7@gmail.com) an IOU.
1. [danrvidal+upgradetest7@gmail.com](mailto:danrvidal+upgradetest7@gmail.com) got the email and clicked Pay , is taken to the sign in page, gets the magic code and logs in
1. I navigate to the IOU in our DM and click Pay with Expensify
1. It just seems to load for a long time showing a screen “We’re taking a look at your information. You will be able to continue with next steps shortly.”
1. I’ve instances where I can’t currently get this to load with a test account OR it takes a long time. It should be taking me to Connect with Plaid.

____

1. Underneath the overlay though you can see it says Hm… it’s not here.
1. If I then leave the Plaid setup, I see the Hm… it’s not here flow, which is incorrect.
1. If I click the link to “You don’t have access to this chat”, it opens the DM.

Having it take a long time is reproducible for me right now. I my first experience was here, and I’ll put another video and logs in :thread:.

## Expected Result:
Describe what you think should've happened

The bank account flow should open after a bit. Real report remains open under the moda.

## Actual Result:
Describe what actually happened

User is stuck on the plaid modal flow and there is not found page shown in the report screen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://expensify.slack.com/archives/C05LX9D6E07/p1716940740586069?thread_ts=1716940673.539529&cid=C05LX9D6E07

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1cf25507f28de79</li>
        <li>Upwork Job ID: 1796654190900498432</li>
        <li>Last Price Increase: 2024-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102615217</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by goldenbear101** [comment] 2024-05-31 17:37
Hello, is there a bounty for this issue, regardless, I want to work on this.

**Comment by mountiny** [comment] 2024-05-31 21:25
Yes there is a bounty, making it 500 since its critical task

**Comment by goldenbear101** [comment] 2024-06-01 21:23
Okay here's what I think: The issue described involves the Plaid modal taking a long time to load in the bottom-up flow, eventually leading to a "Not Found" page in Expensify's app. Here’s a detailed look into potential causes and how to fix them:

Potential Causes
1, Network Latency:
Slow network responses from the Plaid API could be causing delays in loading the modal.

2, Integration Issues:
There might be issues with the integration between Plaid and Expensify’s system, possibly due to incorrect API calls, misconfigured endpoints, or problems with API keys.

3, Timeouts:
The application might be hitting a timeout period while waiting for the Plaid modal to load, resulting in a fallback to the "Not Found" page. 

4, React Native Specific Issues:
React Native might be having trouble rendering the Plaid modal efficiently due to compatibility issues or performance bottlenecks.

5, Error Handling:
Poor error handling in the code could be leading to a "Not Found" page instead of a more appropriate error message or retry logic.

Steps I plan to take on fixing the Issue
1, Check Network Conditions:
Monitor network requests to Plaid’s API using tools like Fiddler or Chrome Developer Tools to check for high latency or failed requests.

2, Review Integration Code:
Ensure that API endpoints and keys are correctly configured.
Verify that the API calls to Plaid are correctly formed and handle the responses properly.

3, Implement Retry Logic:
Implement retry logic for the API calls to handle transient network issues

4, Optimize React Native Performance:
Ensure that the React Native components used to display the Plaid modal are optimized for performance.
Use performance profiling tools to identify and resolve bottlenecks.

5, Improve Error Handling:
Enhance error handling to provide user-friendly error messages or fallback options instead of a "Not Found" page.

Finally, I will:
1, Diagnose the problem: Use network monitoring and error logging to identify the root cause.
Improve integration: Ensure API calls and configurations are correct.
2, Enhance user experience: Implement retry logic and better error handling to provide a smoother user experience.
3, Optimize performance: Use React Native performance tools to resolve any rendering issues.

By addressing these areas, you can significantly improve the loading time and reliability of the Plaid modal within the Expensify app.

**Comment by goldenbear101** [comment] 2024-06-01 21:29
Pardon me but I am not able to write a proposal for the job on Upwork. That said, If you give me the job to work on, I will submit it for your verification through telegram or even GitHub and only then you can give me what you deem fit for my work.

**Comment by goldenbear101** [comment] 2024-06-03 20:32
Proposal
Problem Statement
The issue at hand is that the Plaid connection takes a very long time when a user clicks "Pay with Expensify" for the first time. Users experience prolonged loading times and are sometimes stuck on a screen saying, "We’re taking a look at your information. You will be able to continue with the next steps shortly.” Underneath the overlay, there is a message saying, "Hm… it’s not here." If the user leaves the Plaid setup, they see the incorrect "Hm… it’s not here" flow. Clicking the link "You don’t have access to this chat" incorrectly opens the DM.

Root Cause
The root cause of the problem appears to be related to delays and potential missteps in the Plaid setup and connection process. The system does not transition smoothly from initiating the Plaid connection to the bank account flow, resulting in users being stuck in a loading state.

Proposed Changes
To solve the problem, the following changes are recommended:

1. Improve Plaid Connection Initialization
Ensure that the connection to Plaid is initiated correctly and that any initial checks or setups are handled promptly.

```
// Ensure proper initialization and error handling
async function initiatePlaidConnection() {
    try {
        const response = await startPlaidConnection();
        if (response.error) {
            handlePlaidError(response.error);
        } else {
            proceedToPlaidFlow(response.data);
        }
    } catch (error) {
        handlePlaidError(error);
    }
}
```
2. Enhance Loading and Transition Experience
Improve the user experience by ensuring that loading states are accurately represented and that users are transitioned correctly to the next steps.

```
// Manage loading state and transition
function proceedToPlaidFlow(data) {
    setLoading(false);
    navigateToPlaidSetup(data);
}

// Show a user-friendly loading state
function setLoading(isLoading) {
    if (isLoading) {
        showLoadingScreen("We’re taking a look at your information. You will be able to continue with next steps shortly.");
    } else {
        hideLoadingScreen();
    }
}
```
3. Handle Errors and Incorrect Flows
Ensure that errors and incorrect flows are handled gracefully and provide appropriate feedback to the user.

```
// Handle Plaid errors and incorrect flows
function handlePlaidError(error) {
    setLoading(false);
    showErrorMessage("There was an issue connecting to Plaid. Please try again later.");
}

// Navigate to the correct report after error
function navigateToCorrectReportAfterError() {
    navigateToReport();
}
```
4. Correct Message Display and Navigation
Fix the issues with incorrect message displays and navigation to ensure users do not see misleading information.

```
// Correct message display and navigation
function showErrorMessage(message) {
    displayOverlayMessage(message);
    // Additional logic to handle incorrect flows
    if (message.includes("not here")) {
        navigateToCorrectReportAfterError();
    }
}
```
5. Update Error Messages and Flow Handling
Ensure that error messages are clear and provide useful information to the user. Update the flow handling logic to avoid incorrect states.

```
// Update error messages and flow handling
function displayOverlayMessage(message) {
    // Display the message on the overlay
    overlayElement.innerText = message;
}

// Additional flow handling for errors
function navigateToReport() {
    // Logic to navigate to the correct report
    window.location.href = '/report';
}
```
Expected Result
The bank account flow should open after a brief loading period, with the real report remaining open under the modal. The transition should be smooth, and users should not encounter misleading messages or incorrect navigation.

By implementing these changes, the connection to Plaid should be more reliable and the user experience significantly improved, avoiding prolonged loading times and incorrect flows.

**Comment by ashuvssut** [comment] 2024-06-04 02:52
The screenshot/video link is not accessible

<img width="1265" alt="image" src="https://github.com/Expensify/App/assets/60546840/237b13bb-3f45-4557-8288-5c2e88c39288">


Was that screenshot/video shared in #expensify-open-source channel?

**Comment by mountiny** [comment] 2024-06-04 16:53
Here is the video
https://github.com/Expensify/App/assets/36083550/129bb65a-0884-4fd9-920d-30c4d2469eea

**Comment by mallenexpensify** [comment] 2024-06-04 19:10
[Posted in #contributor-plus](https://expensify.slack.com/archives/C02NK2DQWUX/p1717528184112999) to see if a C+ can take this over since it's been a week and @getusha has commented

**Comment by getusha** [comment] 2024-06-04 19:23
Still waiting for proposals, both proposals posted by @goldenbear101 are AI generated.

**Comment by goldenbear101** [comment] 2024-06-04 22:26
Really sorry about that but they aren't AI-generated, It's a suspicion fine-tuned by AI. And I could prove iT as you will.

**Comment by getusha** [comment] 2024-06-05 12:01
@goldenbear101 get yourself familiarized with the codebase and try writing a detailed proposal on where & what to change. and it's important to put accurate and detailed RCA.

**Comment by lauridskern** [comment] 2024-06-05 15:29
Hi, Laurids from Margelo here. I will be working on this issue.

**Comment by muttmuure** [comment] 2024-06-05 22:07
Thanks!

**Comment by MonilBhavsar** [comment] 2024-06-13 10:32
Holding on https://github.com/Expensify/Expensify/issues/350724 and https://github.com/Expensify/App/issues/43492 as discussed here https://expensify.slack.com/archives/C05R2V5GM1S/p1718259305669389?thread_ts=1716984044.957689&cid=C05R2V5GM1S

**Comment by MonilBhavsar** [comment] 2024-06-17 08:42
on HOLD

**Comment by kevinksullivan** [comment] 2024-06-26 16:42
still held

**Comment by muttmuure** [comment] 2024-07-09 15:26
If it's still happening, we will need to wait for - https://github.com/Expensify/Expensify/issues/350724

**Comment by MonilBhavsar** [comment] 2024-07-10 16:21
A conversation is happening here https://expensify.slack.com/archives/C07BLGL7GBX/p1720554518831649?thread_ts=1720547161.965499&cid=C07BLGL7GBX

**Comment by MonilBhavsar** [comment] 2024-07-12 13:42
Closing this as this is fixed https://expensify.slack.com/archives/C07BLGL7GBX/p1720554518831649?thread_ts=1720547161.965499&cid=C07BLGL7GBX

**Comment by mountiny** [comment] 2024-08-23 17:38
This seems to be still a problem but the API speed has improved a bunch so we might have to look somewhere else a bit

**Comment by hannojg** [comment] 2024-08-23 17:50
Hey, Hanno from Margelo here, I am available to look into this 👋

**Comment by MonilBhavsar** [comment] 2024-08-23 18:06
This is the bug report from the user

https://github.com/user-attachments/assets/5cf9eafd-7909-4b0c-ab56-1a865b7a43c8


As we can see, the internet strength is not great. Perhaps that could be also one of the reason.

**Comment by danielrvidal** [comment] 2024-08-24 18:50
I agree the internet is likely slow but it loads for like 15 seconds while the rest of the app seems to function still. So if we could improve anything in this flow, it feels like an important one.

**Comment by mountiny** [comment] 2024-08-26 15:47
@hannojg started a PR with some improvements

**Comment by kevinksullivan** [comment] 2024-09-12 19:27
Looping in a BZ member to handle payment as I'm going OOO

**Comment by mountiny** [comment] 2024-09-15 23:19
$250 to @getusha for this one cc @zanyrenney 

the automation seems to have failed

**Comment by zanyrenney** [comment] 2024-09-16 20:45
thanks @mountiny

**Comment by zanyrenney** [comment] 2024-09-16 20:45
I will pay now!

**Comment by zanyrenney** [comment] 2024-09-16 20:48
ah @getusha is paid via manual requests.

**Comment by zanyrenney** [comment] 2024-09-16 20:48
**payment summary**

$250 owed to @getusha via NewExpensify. Please request payment there. 

Thank you!

**Closed by zanyrenney** 2024-09-16 20:48 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug, retest-weekly, AutoAssignerNewDotQuality

**Comment by garrettmknight** [comment] 2024-09-19 12:34
$250 approved for @getusha
