### ISSUE TITLE
[$500]  IOU - 'You marked this report...' message only appears on the second visit to IOU report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34003] opened 2024-01-05 01:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. From user A, make an IOU request to user B
2. Sign in with user B
3. Open the IOU request from user A
4. Click on the IOU preview component
5. Click on 'Pay elsewhere' button
6. Navigate back to the parent report
7. Click on the IOU preview component of the settled request

## Expected Result:
'You marked this report as manually reimbursed. This report will be reimbursed outside of Expensify' should be displayed in IOU report on step 5

## Actual Result:
'You marked this report as manually reimbursed. This report will be reimbursed outside of Expensify' is displayed in IOU report in step 7

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8f1c530d-8733-4a31-9376-b867440c1ba9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01913119946e4f8e1d</li>
        <li>Upwork Job ID: 1743143357085888512</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2024-01-05 05:32
This appears to be a back-end issue. It seems like we're notifying of the latest IOU action `paid $XXX elsewhere` [here](https://github.com/Expensify/Web-Expensify/blob/e66e94ab1c67774844cf5780ac5df20b00cd5d8a/lib/ReportAPI.php#L5122-L5128), but we're not notifying of the MARK_REIMBURSED action.

**Comment by jasperhuangg** [comment] 2024-01-05 05:41
Ah wait, after taking another look it seems we're not setting an optimistic `MARKED_REIMBURSED` in Onyx

**Comment by brunovjk** [comment] 2024-01-05 12:28
Can we still make proposals here? :)

**Comment by brunovjk** [comment] 2024-01-06 23:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report doesn't immediately reflect the 'You marked this report as manually reimbursed. This report will be reimbursed outside of Expensify' message when a user marks an IOU as paid elsewhere.

### What is the root cause of that problem?
There is a missing optimistic update for the `MARKEDREIMBURSED` action in the client-side application, specifically within the `getPayMoneyRequestParams` function. Therefore, the Onyx data isn't updated optimistically, and the UI awaits the server response to reflect the change.

### What changes do you think we should make in order to solve the problem?
Implement the optimistic update for the `MARKEDREIMBURSED` action in the `getPayMoneyRequestParams` function. This includes creating a new optimistic action, updating the `optimisticData` array, and ensuring correct handling in the `successData` and `failureData` arrays.

### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2024-01-08 03:22
@brunovjk Looks good, let's move forward with your proposal

**Comment by shubham1206agra** [comment] 2024-01-08 04:02
@jasperhuangg Didn't I get assigned here first as C+ before you unassigned?

**Comment by brunovjk** [comment] 2024-01-08 10:04
Preparing the PR.

**Comment by brunovjk** [comment] 2024-01-09 19:21
Hello @jasperhuangg, I still working on our PR, but have some a question to you.
I think we need some kind of `IOU.buildOptimisticMARKEDREIMBURSEDReportAction` function to build the 'You marked this report...' message, and add to the `optimisticData` if the payment is 'Elsewhere' (also clean this action if success and failure) at `getPayMoneyRequestParams`.
So far, so good. But in order to do that we need to add some ` | 'MARKEDREIMBURSED'` and `OriginalMessageMarkedReimbursed` at `src/types/onyx/OriginalMessage.ts`.

I've been investigating, and since this [PR](https://github.com/Expensify/App/pull/33730/files), some issues have come up: [#34003](https://github.com/Expensify/App/issues/34003), [#34045](https://github.com/Expensify/App/issues/34045), and [#34051](https://github.com/Expensify/App/issues/34051) about 'MARKEDREIMBURSED'.

For #34003, As you approved:
"Implement the optimistic update for the "MARKEDREIMBURSED" action in the 'getPayMoneyRequestParams' function."
For #34045, There is some proposals about:
"Add logic to copy the type "MARKEDREIMBURSED" of the message in 'src/pages/home/report/ContextMenu/ContextMenuActions.js'."
For #34051, Also has some proposals:
"Cover the case of MARKEDREIMBURSED in 'getReportName' in 'src/libs/ReportUtils.ts'."

But we believe this isn't enough.
I believe this `OriginalMessageMarkedReimbursed` will be useful in those issue as well.
What do you think? Make sense?

**Comment by bfitzexpensify** [comment] 2024-01-11 17:35
I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.

- PR is being worked on

**Comment by abekkala** [comment] 2024-01-11 20:21
@jasperhuangg it looks like @brunovjk has some questions for you above irt the PR, if you have a moment: https://github.com/Expensify/App/issues/34003#issuecomment-1883643591

**Comment by brunovjk** [comment] 2024-01-13 17:35
Still working on the PR.

**Comment by jasperhuangg** [comment] 2024-01-17 15:47
Thanks! Was OOO, sorry for the delay.

@brunovjk is your concern that we're going to need the `OriginalMessageMarkedReimbursed` in the PRs raised for those other issues as well, and that your changes are going to conflict?

**Comment by brunovjk** [comment] 2024-01-17 19:25
> Thanks! Was OOO, sorry for the delay.
> 
> refactor those changes to use that type

Exactly!  :D
I'll go back to preparing the PR right now, and we'll discuss it further there. I'll be back when I have it, for now if you need anything tell me.

**Comment by youssef-lr** [comment] 2024-01-18 01:47
@jasperhuangg @Beamanator shouldn't the `You marked this report reimbursed...` an OldDot report action only? I think we have the equivalent of it in NewDot which is `Paid elsewhere`. I thinnk it would be redundant if we displayed both. cc @JmillsExpensify @trjExpensify

**Comment by Beamanator** [comment] 2024-01-18 08:06
Ooh that's a good point @youssef-lr - I was under the impression that we only added the `You marked this report reimbursed...` when marking as reimbursed `from OldDot`, but it seems we add that action even when we choose `Pay elsewhere` from NewDot? 

I think we need to make this consistent in both places, so if:
1. User clicks `Pay elsewhere` from NewDot, we need to show some action in both NewDot & OldDot
2. Similarly, if user clicks `Mark Reimbursed` from OldDot, we need to show some action in both NewDot & OldDot

**Comment by trjExpensify** [comment] 2024-01-18 13:20
Yep, ideally we're consistent with the system messages we show and never duplicate them. I believe the idea was: 

- Regardless of which platform you click pay, you'd see: 
   - Only "Paid $10.00 elsewhere" on NewDot 
   - Only "Marked this report as reimbursed" on OldDot

CC: @garrettmknight @JmillsExpensify

**Comment by brunovjk** [comment] 2024-01-18 14:30
@trjExpensify Please correct me if I'm wrong, however I think we need this 'MARKEDREIMBURSED ' at the moment, https://github.com/Expensify/App/pull/33730#issue-2058943353, and then we will eventually remove it altogether?

The problem [here](https://github.com/Expensify/App/issues/34003) is about inconsistency I believe.
Today we can only receive this 'MARKEDREIMBURSED' report_action from the backend when we leave the report preview and return.

https://github.com/Expensify/App/assets/95647348/0b7fba30-5ac9-485d-8692-24e039779d67


If the message "Marked this report as reimbursed..." should appear 'Only on OldDot', we must redo the backend response so that it does not send report_action with the 'MARKEDREIMBURSED' tag

Or if we're going to show this message in NewDot **add an event pusher to the report preview + optimisc data**.

I'm working on `Implement the optimistic update for the MARKEDREIMBURSED action in the getPayMoneyRequestParams function`, I'm just finishing some tests and today I finish the PR, but I think we need [that](https://github.com/Expensify/App/issues/34003#issuecomment-1878156321) pusher:

https://github.com/Expensify/App/assets/95647348/323fbad7-32a5-4157-ad3d-c8224df1ad6e

**Any feedback/guidance is welcome**.

**Comment by JmillsExpensify** [comment] 2024-01-18 16:19
> Yep, ideally we're consistent with the system messages we show and never duplicate them. I believe the idea was: 
> 
> 
> 
> - Regardless of which platform you click pay, you'd see: 
> 
>    - Only "Paid $10.00 elsewhere" on NewDot 
> 
>    - Only "Marked this report as reimbursed" on OldDot
> 
> 
> 
> CC: @garrettmknight @JmillsExpensify 

Agree with this. We should never show "you manually marked this report as reimbursed" on NewDot.

**Comment by brunovjk** [comment] 2024-01-18 16:37
https://github.com/Expensify/App/issues/34003#issuecomment-1898588636:
> update backend response so that it does not send report_action with the 'MARKEDREIMBURSED' tag

@JmillsExpensify  It makes sense? Thank you.

**Comment by trjExpensify** [comment] 2024-01-18 17:38
yeah, we don't want to send two report actions when a report is paid.

**Comment by brunovjk** [comment] 2024-01-18 18:00
Nice! Can we close this then?

**Comment by brunovjk** [comment] 2024-01-18 18:01
Nice! So can we close this?

**Comment by jasperhuangg** [comment] 2024-01-18 21:41
Hmm so we don't ever want mark reimbursed actions to display in newdot? we're currently still sending those when we query for all report actions. We should probably remove them from the list of known report actions so we don't display them at all.

I see @Beamanator recently added a lot of logic for marked reimbursed messages in NewDot, was this intentional?

**Comment by trjExpensify** [comment] 2024-01-18 21:51
When a report is paid, these are the variations of the "paid" system message that should get added to NewDot: 

- paid $50.00 elsewhere
- paid $50.00 using Expensify

**Comment by Beamanator** [comment] 2024-01-19 09:34
So yes it was "intentional" as that's what I understood we wanted, according to my convo w/ @JmillsExpensify in [this slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1701876923291429). But now it's sounding like I misunderstood? 😅 

We already have a report action that we "Mark as reimbursed" in OldDot, which I thinkkk is different than "Paid elsewhere" -> So IMO have to either:
1. Be ok with this "you manually marked this report as reimbursed" action for now (since it's only and OldDot flow, which will be removed eventually); OR
2. In this flow, create 2 actions:
    1. The "you manually marked this report as reimbursed" action (which we'll show in OldDot only)
    2. The "Paid $<amount> elsewhere" action, which will show in NewDot (& we'll have to make sure this doesn't show in OldDot)

**Comment by jasperhuangg** [comment] 2024-01-19 14:59
Cool, I'm going to close this revert for now in the interest of keeping things consistent: https://github.com/Expensify/Web-Expensify/pull/40581.

**Comment by brunovjk** [comment] 2024-01-19 15:25
> remove the MARKED_REIMBURSED

maybe revert this https://github.com/Expensify/App/pull/33730?

**Comment by Beamanator** [comment] 2024-01-22 08:36
> It sounds like all we need to do in order to prevent this report action from showing (quickly) is to remove the MARKED_REIMBURSED action from [here](https://github.com/Expensify/App/blob/d4fc5e928b8424cc9cffbea0783b4bb7fa1d0e2d/src/CONST.ts#L520). This should cause it to get filtered out.

That should prevent the old "Marked reimbursed" action from showing in NewDot, yes - but we'll still want _something_ to show in NewDot (`Paid $ elsewhere`) right?

**Comment by trjExpensify** [comment] 2024-01-22 21:47
When a report is manually reimbursed? Yeah, that's the reportAction we use.

**Comment by jasperhuangg** [comment] 2024-01-31 20:17
@Beamanator can I get a second look at this issue? I'm not entirely sure if it's been solved yet.

**Comment by Beamanator** [comment] 2024-02-01 14:27
Yeah sorry @jasperhuangg are you asking if we think the bug still exists or if we've agreed on the solution we want to move forward with? 😅  I believe I've seen the bug when testing in main yesterday, and I think the agreed upon solution is [here](https://github.com/Expensify/App/issues/34003#issuecomment-1903494167)? Def let me know if I'm missing something in your question :D 26155

**Comment by brunovjk** [comment] 2024-02-04 12:24
## Proposal
[Updated](https://github.com/Expensify/App/issues/34003#issuecomment-1879868908) following discussion above. @jasperhuangg and @Beamanator  can you take a look please? Thanks.

**Comment by bfitzexpensify** [comment] 2024-02-15 06:25
Are we good to move forward with @brunovjk's proposal @Beamanator / @jasperhuangg?

**Comment by Beamanator** [comment] 2024-02-15 09:14
I was waiting on @jasperhuangg to confirm we're on the same page with next steps 😅

**Comment by jasperhuangg** [comment] 2024-02-16 18:23
@Beamanator ah sorry, I misunderstood. I think the proposal makes sense–as long as the `Paid $ elsewhere` report actions appear then that should be the expected behavior, correct?

**Comment by jasperhuangg** [comment] 2024-02-16 18:23
@brunovjk feel free to move forward with your proposal!

**Comment by brunovjk** [comment] 2024-02-16 19:58
Thank you. I aim to have a PR for your review by 02/23 and will notify if it's ready sooner.
I should not raise the PR until I am assigned. Correct?

**Comment by Beamanator** [comment] 2024-02-17 06:09
> @Beamanator ah sorry, I misunderstood. I think the proposal makes sense–as long as the `Paid $ elsewhere` report actions appear then that should be the expected behavior, correct?

Ok cool we're on the same page then! Yes exactly - I mean, as long as we we don't have any flow from OldDot that results in NO report action shown in NewDot, right?

**Comment by brunovjk** [comment] 2024-02-17 11:05
I'll start working on this this week, and I'll follow the conversation here to make sure we're aligned, then we'll be able to discuss it further there :D

**Comment by brunovjk** [comment] 2024-02-20 11:52
> I should not raise the PR until I am assigned. Correct?

Still waiting for confirmation.

**Comment by brunovjk** [comment] 2024-02-20 14:14
I'm still waiting for confirmation to start. Thanks.

**Comment by jasperhuangg** [comment] 2024-02-20 23:18
@brunovjk go for it! You've been assigned to the issue.

**Comment by brunovjk** [comment] 2024-02-21 00:03
Sorry, I hadn't noticed, let's get to work :D

**Comment by brunovjk** [comment] 2024-02-21 22:24
[PR](https://github.com/Expensify/App/pull/37051) ready for review.

@jasperhuangg This [PR](https://github.com/Expensify/App/pull/34719#issuecomment-1931992496) sort of fixes the issue here, but we still need to remove the `getMarkedReimbursedMessage` function to gracefully complete my [proposal](https://github.com/Expensify/App/issues/34003#issuecomment-1879868908), since we never meant to show the message on NewDot.

**Comment by brunovjk** [comment] 2024-03-12 10:27
@jasperhuangg and @bfitzexpensify Can you confirm if this issue/PR is valid for payment? Thanks.

**Comment by jasperhuangg** [comment] 2024-03-12 18:06
@brunovjk ah yes, sorry I think our automated messages were broken for a bit– @bfitzexpensify do you mind handling payouts here? We need to pay out @brunovjk for implementing the fix and @akinwale for PR review

**Comment by bfitzexpensify** [comment] 2024-03-13 13:46
You bet - offers sent @brunovjk and @akinwale

**Comment by akinwale** [comment] 2024-03-13 13:48
@bfitzexpensify Accepted. Thanks!

**Comment by brunovjk** [comment] 2024-03-13 13:49
Accepted. Thanks!

**Closed** 2024-03-13 14:29 UTC
Labels: Reviewing, Engineering, Daily, Internal, Help Wanted, Bug
