### ISSUE TITLE
[$500] Profile - Notification preference displayed when no comment in report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34176] opened 2024-01-09 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.24
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33387

## Action Performed:
1. Launch app
2. Tap fab
3. Tap start chat
4. Select a new user with whom no previous chat history
5. Tap on header

## Expected Result:
In profile page, notification preference must not be displayed when there is no comment in report.

## Actual Result:
In profile page, notification preference section is displayed when there is no comment/chat in report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/68ca2a92-2cc0-4364-bdb3-fa45cf4eb2e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb16322001847cf2</li>
        <li>Upwork Job ID: 1744792621694226432</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-09 18:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When deciding whether to show the notification preference, we only check it to be not hidden, and the report object to be not empty:

https://github.com/Expensify/App/blob/ffbf5da2c04fe9812c206f75213481c2998bd664/src/pages/ProfilePage.js#L137

### What changes do you think we should make in order to solve the problem?
We should explicitly check if the chat is not empty, similar to how we do it on the HeaderView:

```js
const lastVisibleMessage = ReportActionsUtils.getLastVisibleMessage(props.report.reportID);
    const isEmptyChat = !props.report.lastMessageText && !props.report.lastMessageTranslationKey && !lastVisibleMessage.lastMessageText && !lastVisibleMessage.lastMessageTranslationKey;
    const shouldShowNotificationPreference = !_.isEmpty(props.report) && !isEmptyChat && props.report.notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN;
```

https://github.com/Expensify/App/blob/ffbf5da2c04fe9812c206f75213481c2998bd664/src/pages/ProfilePage.js#L137

### What alternative solutions did you explore? (Optional)

**Comment by dragnoir** [comment] 2024-01-10 11:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Notification preference displayed when no comment in report

### What is the root cause of that problem?
The profile page is not checking:
- if the chat is empty
- if there's no old deleted conversation

### What changes do you think we should make in order to solve the problem?
1- We need to check if the chat is empty same as in `HeaderView`
https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/pages/home/HeaderView.js#L114

2- We need to check if there was a discussion before
```js
function  areDatesEqual(lastReadTime, lastVisibleActionCreated) {
  // Removing the milliseconds part from the date-time strings
  const  lastReadTimeWithoutMillis  =  lastReadTime.substring(0, 19);
  const  lastVisibleActionCreatedWithoutMillis  =  lastVisibleActionCreated.substring(0, 19);
  
  // Creating Date objects
  const  lastReadDate  =  new  Date(lastReadTimeWithoutMillis);
  const  lastVisibleActionCreatedDate  =  new  Date(lastVisibleActionCreatedWithoutMillis);
  
  // Returning true if dates are equal, false otherwise
  return  lastReadDate.getTime() ===  lastVisibleActionCreatedDate.getTime();
}

const  result  =  areDatesEqual(props.report.lastReadTime, props.report.lastVisibleActionCreated);
```

3- Add to `shouldShowNotificationPreference` those 2 checks to make sure we can display the notifications setting.
https://github.com/Expensify/App/blob/ad583bb9605fa9ecf38312eba271fcdb49cbfafd/src/pages/ProfilePage.js#L137

### Explaining:
The bug reported here is for the 1st time conversation, but I noticed if there's an old conversation and it's deleted, checking only if the chat is empty will not allow editing notifications settings.
And I think if someone receive a lot of messages (with lots of notifications) then those  messages got deleted by the sender, I think the receiver still get the right to mute (or edit) notification.

I am not sure what's the righ way to do this (checking if there's an old deleted conversation) but I noticed there's a difference between `lastReadTime` and `lastVisibleActionCreated` in report details. I will try to ask the team on Slack about this.

### What alternative solutions did you explore? (Optional)

Add an utility on `ReportUtils` to handle this case.

**Comment by Victor-Nyagudi** [comment] 2024-01-10 12:58
I'm a little confused about the expected result here. 

Could someone kindly explain how showing the notification preference when no messages have been sent is a bad thing? Does someone have to chat first before you can adjust the preference?

**Comment by dragnoir** [comment] 2024-01-10 13:25
@Victor-Nyagudi check https://github.com/Expensify/App/pull/33387

**Comment by paultsimura** [comment] 2024-01-10 14:39
> And I think if someone receive a lot of messages (with lots of notifications) then those messages got deleted by the sender, I think the receiver still get the right to mute (or edit) notification.


At first, I was thinking about this scenario as well, but it looks super unlikely considering the sender will have to remove each message manually. Moreover, if the chat report is empty, it disappears from LHN in both "Last seen" and "Focus" modes, so in such a case the recipient will have to go to the search, type in the sender's details, and mute them.
Therefore, making such a calculation for a super edge case each time a profile page is opened looked like an overkill for me.

**Comment by dragnoir** [comment] 2024-01-10 14:55
@paultsimura Let's agree to disagree :)

> I was thinking about this scenario as well

It's not mentioned in your proposal even in the alternative solution

> it looks super unlikely considering the sender will have to remove each message manually

it can be just one msg, mistake, wrong file..

> it disappears from LHN

You can see on the video I attached, it doesn't disappear. The chat is open, msg removed and user (receiver) is not able to mute cayse msg deleted.

> such a calculation

I don't see any calculation, it's just a condition.

> super edge case 

This is how great apps are built. Most of the issues areb super edge case  but we enroll to make the app perfect.

Thanks for the details, I have confidance that the C+ will take the right decision.

**Comment by sonialiap** [comment] 2024-01-15 12:03
@akinwale what do you think of the above proposals?

**Comment by akinwale** [comment] 2024-01-17 09:46
@dragnoir I reviewed both proposals, and the expected behaviour here is that there shouldn't be a notification preference displayed whenever the report is empty, so it doesn't matter if there were previous chats that have been deleted. As long as the report is empty, the preference should not be displayed. 

After reviewing the proposals, we can move forward with @paultsimura's [proposal](https://github.com/Expensify/App/issues/34176#issuecomment-1883612915).

🎀👀🎀 C+ reviewed.

**Comment by Beamanator** [comment] 2024-01-17 11:45
Hmm @srikarparsi do you mind taking over this one since it has a lot to do with https://github.com/Expensify/Expensify/issues/330506, and specifically your changes in these two PRs?
- https://github.com/Expensify/Auth/pull/9531
- https://github.com/Expensify/App/pull/33387

**Comment by dragnoir** [comment] 2024-01-17 12:07
@akinwale I don't agree with you. For an app like expensify, perfection and focus on details is very important. The video I posted show the UX issue when someone is spamming then removing messages. Even when the app and the chat is open.

I totally repect you decision but I don't agree with you. It will be another issue opened later for sure.

**Comment by srikarparsi** [comment] 2024-01-19 22:24
Hey! I don't believe this is reproducible anymore since the [Auth PR ](https://github.com/Expensify/Auth/pull/9531) hit production yesterday. This makes sure that new DMs are set to hidden by default and the [App PR](https://github.com/Expensify/App/pull/33387) ensures we don't show the `hidden` notification preference in the settings pane.

<img width="828" alt="image" src="https://github.com/Expensify/App/assets/48188732/4c859cdb-3add-4de9-ba35-f82dd3e7d98a">

I believe we should be able to close this out?

**Comment by paultsimura** [comment] 2024-01-20 19:38
That's sad but seems like you're right @srikarparsi, I cannot reproduce either 🙂

**Comment by Beamanator** [comment] 2024-01-22 08:38
That's great! Happy to close this out

**Closed by Beamanator** 2024-01-22 08:38 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by dragnoir** [comment] 2024-01-25 18:36
@paultsimura that was a nice debate, thx for the spirit :)

**Comment by paultsimura** [comment] 2024-01-25 20:14
> @paultsimura that was a nice debate, thx for the spirit :)

You too, man 💪
