### ISSUE TITLE
[$250] Group Chat - View scrolls to Recents header when unselecting users from group conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9918] opened 2022-07-14 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found during executing PR** https://github.com/Expensify/App/pull/9798

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with any use
3. Tap on Fub menu
4. Tab Group Chat
5. Scroll and select the user
6. Select a couple more users
7. Unselect one of the user from the list

## Expected Result:
View does not scroll after unselecting a user from a group conversation

## Actual Result:
View scrolls down to the `Recents` header (hiding currently selected users) after unselecting a user from a group conversation

## Workaround:

Yes, they can scroll up to see the users again

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.84.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179050372-edb3c97a-9f9b-4987-b62c-96ca998a441f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2022-07-15 01:40
Hmm @kbecciv I'm unable to reproduce this on staging v1.1.84-11. The users look like they're being added and removed correctly with no users being hidden: 

https://user-images.githubusercontent.com/16747822/179129575-599bf9d9-6f4b-41ac-8c28-d6cee9a0ffef.mov

**Comment by kbecciv** [comment] 2022-07-15 12:45
@NikkiWines Sorry, for confusion. But when you unselecting one of your users - the rest of them is hidden on top of the list. You can see them only when you're scrolling. App behavior should be the same when you selecting and deselecting users.

**Comment by NikkiWines** [comment] 2022-07-15 16:00
Ah, @kbecciv, I see! The issue is that it scrolls down to the `Recents` heading when you select a user instead of staying at the currently selected user's section. I've updated the issue to make that a bit clearer. 

This looks good for a contributor to pick up. Marking as external. cc: @roryabraham though just cause it seems like it might be tied to the `OptionsSelector` (and `focusedIndex`) logic that was changed recently.

**Comment by jliexpensify** [comment] 2022-07-17 22:55
Posted:

Internal - https://www.upwork.com/ab/applicants/1548801896295538688/job-details
External - https://www.upwork.com/jobs/~0157999e8dc1517dd0

**Comment by jeet-dhandha** [comment] 2022-07-18 06:23
### Proposal
1. Setting Focused Index to default "0" fixes the issue. And also we are focusing 0th index and 0th sectionIndex, on each user select. 
<img width="1018" alt="Screenshot 2022-07-18 at 11 44 36 AM" src="https://user-images.githubusercontent.com/78416198/179454850-234e33eb-2628-4b91-a4d7-6b7c28f807aa.png">

(Note: The above issue is also reproducible on Android Build also. So i have tested in android as i am not able to run app on web from main branch. Getting some issue i have send errors on this slack conversation https://expensify.slack.com/archives/C01GTK53T8Q/p1658122959811569 )

Fixed App Video:

https://user-images.githubusercontent.com/78416198/179454991-7b3c61b8-a04e-4d26-9648-fe5d535adf66.mp4

**Comment by jeet-dhandha** [comment] 2022-07-18 06:57
@rushatgabhane @jliexpensify @roryabraham Please check.

**Comment by jliexpensify** [comment] 2022-07-18 07:06
Thanks @jeet-dhandha - no need to tag us, as we'll see the GH comment. The Contributor+ person (i.e. Rushat) or assigned Engineer will review this.

**Comment by jeet-dhandha** [comment] 2022-07-18 07:07
Okay 😅

**Comment by roryabraham** [comment] 2022-07-18 17:59
@jeet-dhandha the first unselected option should be focused, so the logic for the new selected index is correct as-is. Instead we should change [this callback](https://github.com/Expensify/App/blob/e9ff99c0127b25d1b0d191d0e2abdcc5fc771e5e/src/components/OptionsSelector.js#L223-L227):

```diff
- // If we just selected a new option on a multiple-selection page, scroll to the top
+ // If we just selected or deselected an option on a multiple-selection page, scroll to the top
- if (this.props.selectedOptions.length > prevProps.selectedOptions.length) {
+ if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
    this.scrollToIndex(0);
    return;
}
```

**Comment by jeet-dhandha** [comment] 2022-07-19 01:28
@roryabraham your proposed solution will work for selected but I don’t know about other scenarios. I have already tested mine with other scenarios and each one is working fine.

**Comment by jeet-dhandha** [comment] 2022-07-19 01:59
@roryabraham Your changes also works same as mine for each scenario. But from what i have seen throughout the app we are taking user on each select/deselect or search - at the top (0th index) only. So whatever works for the expensify team we will go with that one.

**Comment by rushatgabhane** [comment] 2022-07-19 04:02
@jeet-dhandha like @roryabraham said, the first unselected option should be focused.

**Comment by jeet-dhandha** [comment] 2022-07-19 04:23
So to be clear when i deselect a user i should get focused at the position where the user was before selecting it ?

**Comment by rushatgabhane** [comment] 2022-07-19 04:54
When a user is deselected, the first unselected option should be **focused** but I think the scroll position should be 0

**Comment by jliexpensify** [comment] 2022-07-22 00:31
bump @jeet-dhandha - any progress/additional questions?

**Comment by jeet-dhandha** [comment] 2022-07-23 20:47
### Another Proposal:

<img width="1018" alt="Screenshot 2022-07-24 at 2 14 00 AM" src="https://user-images.githubusercontent.com/78416198/180622290-f6fd09af-d287-42eb-a13b-75c8997edf8e.png">

As i have understood we want to scroll user to top of the screen when there are selected options.
When there aren't any selected users it will stay at last available Section's index.
So the above code is what we need.

**Comment by rushatgabhane** [comment] 2022-07-25 06:10
@jeet-dhandha I think @roryabraham's logic is better. It reads something like - "If options list has changed, then scroll to 0"

**Comment by jeet-dhandha** [comment] 2022-07-25 14:57
Well I can’t change your perception about solutions but whatever’s best for the firm is all we need if @roryabraham’s solution is best we will go with that. 😊👍

**Comment by roryabraham** [comment] 2022-07-27 19:00
While I think @jeet-dhandha's solution is equivalent, let's just go with the solution I laid out above.

**Comment by jliexpensify** [comment] 2022-07-27 23:20
@jeet-dhandha - can you share your Upworks profile please? I can't seem to find you.

**Comment by jeet-dhandha** [comment] 2022-07-28 04:07
Upwork profile - https://www.upwork.com/freelancers/~01921c050b587a3859

**Comment by roryabraham** [comment] 2022-08-02 23:07
PR merged

**Comment by jeet-dhandha** [comment] 2022-08-03 04:12
Upwork link : https://www.upwork.com/freelancers/~01921c050b587a3859

**Comment by jliexpensify** [comment] 2022-08-03 05:43
I've had to take some unexpected time off, so assigning to Kadie (my leave buddy) to manage!

**Comment by mvtglobally** [comment] 2022-08-09 04:43
Issue not reproducible during KI retests. (First week)

**Comment by jeet-dhandha** [comment] 2022-08-09 12:31
@jliexpensify when does merged PR(s) get deploy to production ?

**Comment by mvtglobally** [comment] 2022-08-16 04:49
Issue not reproducible during KI retests. (Second week)

**Comment by kadiealexander** [comment] 2022-08-22 11:17
Not overdue, waiting for PR to be deployed to production.

**Comment by mvtglobally** [comment] 2022-08-23 04:11
Issue not reproducible during KI retests. (Third week)

**Comment by mvtglobally** [comment] 2022-08-30 15:19
Issue not reproducible during KI retests. (Fourth week)

**Comment by kadiealexander** [comment] 2022-09-01 15:19
@roryabraham @rushatgabhane could one of you please confirm what day this was deployed to production?

**Comment by roryabraham** [comment] 2022-09-02 11:02
Yep, lets pay this out now

**Comment by kadiealexander** [comment] 2022-09-02 13:40
Both paid! Thanks team :)

**Closed by kadiealexander** 2022-09-02 13:40 UTC
Labels: Exported, External, Engineering, Weekly, Improvement
