### ISSUE TITLE
[HOLD for payment 2023-10-13] [$1000] mWeb - LHN - Click and long pressing a user report with lot of messages opens mark as unread popup inside report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25460] opened 2023-08-18 09:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android chrome
2. Click on user report which has many messages in it
3. Quickly long press to observe that it displays 'mark as unread' popup inside the report

## Expected Result:
App should not display mark as unread popup inside report

## Actual Result:
On opening user report with lots of messages and quickly long press, mark as unread popup gets opened inside the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856 

**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/115492554/ca751249-5f02-4bf5-bba9-c13376b48ef0

https://github.com/Expensify/App/assets/115492554/9fc1cea1-9fe0-4014-b605-2bac67ab14ce

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691495713340339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01404d8d81934e3635</li>
        <li>Upwork Job ID: 1693977568321503232</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>Dhanashree-Sawant | Reporter | 26646326</li>
</ul></li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-08-22 13:24
OK, let's get some proposals for this one.

**Comment by ishpaul777** [comment] 2023-08-22 13:49
what's the expected behaviour here? should we disreagard user long press if navigation in progress?

**Comment by anukcr7** [comment] 2023-08-22 14:49
Where should I send initial proposal?

**Comment by carlosalmonte04** [comment] 2023-08-22 14:51
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Prevent long press action to take place if user navigated to another screen.

## What is the root cause of that problem?
The user technically long presses on item before navigation occurs therefore triggering the pop up to appear. This can be prevented by detecting if the chat item was pressed (short pressed) before the long press and prevent the pop up to appear.

## What changes do you think we should make in order to solve the problem?
Detect if there was a short tap before the long press and preventing the pop up to appear.

```javascript
// pseudocode
onLongPress() {
  if(navigationInProgress) return; // this to be added
  performLongPressAction();
}
```

## What alternative solutions did you explore? (Optional)
1. Dismissing the pop up in the next screen, this is undesirable given that it may result in a flicker.
2. Listening to navigation and preventing the pop up to appear if navigation taking place.

Reminder: Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Anmolverma19** [comment] 2023-08-22 14:57
Contributor details
Your Expensify account email: annieemporium16@gmail.com
Upwork Profile Link: (https://www.upwork.com/freelancers/anmolv3)

**Comment by Anmolverma19** [comment] 2023-08-22 14:59
I have submitted the proposal on Upwork already

**Comment by carlosalmonte04** [comment] 2023-08-22 15:19
@anukcr7 and @Anmolverma19 information on how to submit proposals is in this document [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).

**Comment by Anmolverma19** [comment] 2023-08-22 15:33
Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Prevent long press action to take place if user navigated to another screen.

**What is the root cause of that problem?**
According to me, Root cause lies in how touch and gesture events are handled and how UI/UX elements are hovered or triggered on certain user movement or usage

**What changes do you think we should make in order to solve the problem?**
Here's what I initially plan to do to resolve it:
To fix the issue where the "Mark as Unread" option appears when a user performs a long press on the left side of the screen while inside a report, I will need to make changes to the React Native codebase. Below are the steps to address this problem:
Step 1: Locate the Code Responsible for the Long Press Gesture
1. Open the Expensify/App GitHub repository.
2. Navigate to the specific file or component that handles the long press gesture within a report. This can often be found in the component responsible for rendering reports or in a separate gesture handler component.

Step 2: Identify the Event Handling Logic
1. Inspect the code to find the event handling logic for the long press gesture on the left side of the screen. Look for code related to touch or gesture recognition that triggers the "Mark as Unread" option.

Step 3: Modify or Remove the Event Handling Logic
1. Once located the event handling logic, one can either modify it to prevent the "Mark as Unread" option from appearing or remove it entirely, depending on project's requirements.
- To modify: If there is a condition that checks for the long press event and then displays the "Mark as Unread" option, I can update this condition to prevent the option from appearing when a long press occurs on the left side of the screen.
- To remove: If the event handling code is unnecessary for the left side of the screen long press, I can delete or comment out the relevant code block.

Step 4: Test Extensively
1. After making changes, thoroughly test the application on all relevant platforms to ensure that the "Mark as Unread" option no longer appears when doing a long press on the left side of the screen within a report.

Step 5: Document Changes
1. It's essential to document the changes I will make to the codebase. Update comments or documentation within the code to explain the purpose of my modifications. This documentation will help other developers understand changes in the future.

Step 6: Create a Pull Request
1. Once confident that code changes have resolved the issue, create a pull request in the Expensify/App GitHub repository to merge the changes into the main codebase. Include a clear description of the problem and my solution in the pull request.


**What alternative solutions did you explore? (Optional)**
Step 1: Identify the UI Element
1. Inspect the user interface (UI) of the report screen in the application to locate the “Mark as Unread” option or the element that triggers it.

Step 2: Apply CSS or Styling Changes
1. one can use CSS or styling changes to hide the “Mark as Unread” option when certain conditions are met. Specifically, want to target this option when it appears as a result of a long press on the left side of the screen.
2. Use CSS to hide the element or set its visibility to “hidden” or “display: none;” within the report screen’s styling.
3. To target the left side of the screen specifically, may need to apply CSS based on the screen’s layout or structure. For instance, could use CSS classes, element IDs, or parent-child relationships to identify the left side of the screen.


**_Reminder: Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job._**

**Comment by carlosalmonte04** [comment] 2023-08-22 18:28
Does anyone here know how to run the **web** app on an android emulator? I'm getting the screen below.
![Screen Shot 2023-08-22 at 2 28 33 PM](https://github.com/Expensify/App/assets/25206487/8c837ea6-bc55-4d01-befe-011bee38236c)

**Comment by carlosalmonte04** [comment] 2023-08-23 14:02
Here is how it looks with my proposed solution.
https://github.com/Expensify/App/assets/25206487/9f4e9ed3-5a37-404c-8019-581a9a3c0c66

**Comment by ishpaul777** [comment] 2023-08-24 06:13
@carlosalmonte04 Only raise a PR once your proposal is selected by C+ reviewer.

**Comment by ishpaul777** [comment] 2023-08-24 06:26
we are implementing `useSingleExecution` in this PR - https://github.com/Expensify/App/pull/24173, we can use the hook in this case once PR is merged

**Comment by sobitneupane** [comment] 2023-08-24 09:17
Hello everyone. Thanks for your proposals. I would suggest everyone here to go through existing proposals in other issues (like: https://github.com/Expensify/App/issues/24420) to get idea of expected proposals. 

We expect your proposal to include the root cause and link the permalink for the code where issue exists. Also, in your solution you are expected to link the code/file where you are suggesting the change and what sort of change are you suggesting.

Will wait for your updates.

cc: @carlosalmonte04 @Anmolverma19 @ishpaul777

**Comment by carlosalmonte04** [comment] 2023-08-24 17:03
I tested the changes from https://github.com/Expensify/App/pull/24173 and it fixed this bug on my end.

**Comment by ishpaul777** [comment] 2023-08-25 19:07
tested #24173 on physical devide this issue is still reproducable

**Comment by ishpaul777** [comment] 2023-08-25 19:38
@sobitneupane Updated the [comment](https://github.com/Expensify/App/issues/25460#issuecomment-1688227421) to a  formal propsal, let me know you thoughts once you get a chance.

**Comment by carlosalmonte04** [comment] 2023-08-25 20:20
I take my last comment back, I tested again and the changes from the `useSingleExecution` PR do not fix this bug on its own. Also, the new `useSingleExecution` hook changes the flag (`isExecuting`) too fast. By the time the long press triggers the flag is already `false` so it proceeds to show the pop up.

**Comment by carlosalmonte04** [comment] 2023-08-25 20:32
I think `useSingleExecution` should accept an `idleDuration` argument and change the flag (`isExecuting`) to `false` after the given `idleDuration`.

**Comment by sobitneupane** [comment] 2023-08-28 10:49
Will review the proposals today.

**Comment by sobitneupane** [comment] 2023-08-29 07:53
Thanks for the proposal everyone.

We have recently implemented a PR introducing a hook for single execution as mentioned by @ishpaul777. I believe we can make use of the hook here as well. [Proposal](https://github.com/Expensify/App/issues/25460#issuecomment-1688227421) from @ishpaul777 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by ishpaul777** [comment] 2023-08-29 20:57
Hi @sobitneupane, I was testing my proposal on other platflorms and found it does not work as expected and issue still persisted. I came up with other solution to use `useFocusEffect` hook - https://reactnavigation.org/docs/navigation-lifecycle/

implementation in OptionRowLHN -

```jsx
const [isNavigating, setIsNavigating] = useState(false);
    useFocusEffect(
        React.useCallback(() => {
            setIsNavigating(false);

            return () => {
                setIsNavigating(true);
            };
        }, [])
    );
 ```
 ```jsx
 const showPopover = (event) => {
        if (isNavigating) {
            return;
        }
 ```
 
 Result - 
 
<details><summary>Before changes</summary>

https://github.com/Expensify/App/assets/104348397/43e899c2-95f7-4179-bff8-7e181b9a6edc


</details> 
<details><summary>After changes</summary>

https://github.com/Expensify/App/assets/104348397/14292cae-7920-49ae-b8e5-6829c3a446e3

</details>

**Comment by carlosalmonte04** [comment] 2023-08-29 23:53
Hey @ishpaul777 that will trigger a re-render on every OptionRowLHN when navigation changes focus. I'd use `Navigation.getActiveRoute` to compare routes if you must use navigation.

```javascript
    const showPopover = (event) => {
        const route = Navigation.getActiveRoute();
        if (route !== '/') {
            return;
        }
```

**Comment by ishpaul777** [comment] 2023-08-30 05:03
@carlosalmonte04 I don't think there's a rerender of optionRowLHN useFoucussedEffect sets isNavigating to true as soon as navigation starts (screen loose focus) and setIsNavigating to false when screen is focussed, can you link me to docs where it says it rerender component.

**Comment by ishpaul777** [comment] 2023-08-30 17:10
As far as i know, using setState dont have any performance regression in the case it rerenders the part of dom that is concerned with the state. i'll love to know @sobitneupane thoughts here. I have 2 alternative solutions here

1. https://github.com/Expensify/App/issues/25460#issuecomment-1698131395
2. handling this the same way we are preventing clicking on multiple LHN reports on mobile screen devices [here](url).
```jsx
const showPopover = (event) => {
        if(isSmallScreenWidth && Navigation.getTopmostReportId()) {
            return;
        }
```

**Comment by sobitneupane** [comment] 2023-09-01 10:50
@ishpaul777 what were [the issue](https://github.com/Expensify/App/issues/25460#issuecomment-1698131395) you found with your proposal? In which platform and browser? Can you share the screen recording?

I cannot regularly reproduce the issue. Is there any way to reproduce the issue regularly?

**Comment by ishpaul777** [comment] 2023-09-01 10:51
Easily reproduce able on safari

**Comment by sobitneupane** [comment] 2023-09-05 09:09
Thanks for the update @ishpaul777. I tested it and it didn't work for me as well. It is supposed to work for same user action. But we are dealing with different user actions (press and long press). So, it should be dealt uniquely.

@ishpaul777 Your [proposal](https://github.com/Expensify/App/issues/25460#issuecomment-1698131395) is similar to [this propsoal](https://github.com/Expensify/App/issues/25460#issuecomment-1688345649).

**Comment by ishpaul777** [comment] 2023-09-05 09:18
I have other working solution too.
const showPopover = (event) => {
        if(isSmallScreenWidth && Navigation.getTopmostReportId()) {
            return;
        }

**Comment by ishpaul777** [comment] 2023-09-05 12:39
Gentle bump @sobitneupane

**Comment by sobitneupane** [comment] 2023-09-05 14:57
We might go with [this proposal](https://github.com/Expensify/App/issues/25460#issuecomment-1688345649). I am yet to test it.

**Comment by sobitneupane** [comment] 2023-09-06 15:26
I tested [the proposal](https://github.com/Expensify/App/issues/25460#issuecomment-1688345649) from @redpanda-bit. 

> However, I would like to know if the changes I am proposing would cause the entire list to be re-rendered when navigating since useIsFocused() is updated when navigation occurs.

It turns out the above suspicion of re-rendering was correct and the entire list re-renders.

**Comment by redpanda-bit** [comment] 2023-09-06 15:52
## Proposal
[Updated](https://github.com/Expensify/App/issues/25460#issuecomment-1688345649)

**Comment by ishpaul777** [comment] 2023-09-06 16:51
@redpanda-bit You proposal implemented the useFocusEffect in a wrong way and doesn't solve the issue.
I updated my changes https://github.com/Expensify/App/issues/25460#issuecomment-1698131395, Indeed i used your idea to useRef for preventing rerender, but using `useFocusEffect` was my idea in first place, hope you dont have any objection here?

**Comment by bfitzexpensify** [comment] 2023-09-11 10:46
@sobitneupane is there a proposal here we can move forward with?

**Comment by sobitneupane** [comment] 2023-09-13 05:15
[Proposal](https://github.com/Expensify/App/issues/25460#issuecomment-1688345649) from @redpanda-bit looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by dhanashree-sawant** [comment] 2023-09-13 06:34
Hi @bfitzexpensify, the following issue is raised on 18 August but melvin bot has provided 50$ offer, can you check once you are available?

**Comment by bfitzexpensify** [comment] 2023-09-13 11:46
That should be fixed up now @dhanashree-sawant

**Comment by dhanashree-sawant** [comment] 2023-09-13 11:50
Thanks @bfitzexpensify, It is fixed now and have accepted the offer.

**Comment by redpanda-bit** [comment] 2023-09-13 21:38
> 📣 @redpanda-bit You have been assigned to this job! Please apply to the [Upwork job](https://www.upwork.com/jobs/~01404d8d81934e3635) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

I tried applying for the job at Upwork but it shows as no longer available. Am I still working on this? I can submit a PR as soon as tomorrow (9/14). Can someone please clarify.

**Comment by dhanashree-sawant** [comment] 2023-09-14 05:39
Yes @redpanda-bit, your proposal was selected so you are still working on it, go ahead raise a PR, don't worry about the payment issue, they will clear it out once they are available.

**Comment by redpanda-bit** [comment] 2023-09-14 19:48
## Proposal
[Updated](https://github.com/Expensify/App/issues/25460#issuecomment-1688345649)

I am unable to use the approach listed in my proposal. The `useFocusEffect` hook (and any of [the other navigation events](https://reactnavigation.org/docs/function-after-focusing-screen)) doesn't work properly when resizing the window. `blur` gets called even though the component is still visible.

## Bad 
```javascript
    useFocusEffect(
        useCallback(() => {
            isFocusedRef.current = true;
            return () => {
                // THIS GETS CALLED WHEN IT SHOULDN'T
                isFocusedRef.current = false;
            };
        }, []),
    );

    const showPopover = (event) => {
        if (!isFocusedRef.current) {
            return;
        }
        // ... show popover code
    }
```

## Good
```javascript
    const showPopover = (event) => {
        const isSmallScreenWidth = Dimensions.get('window').width <= variables.mobileResponsiveWidthBreakpoint;
        const isReportRoute = !!Navigation.getActiveRoute().match(CONST.REPORT_ROUTE_REGEX);
        if (isSmallScreenWidth && isReportRoute) {
            return;
        }
        // ... show popover code
    }
```

Please let me know if ok @sobitneupane to proceed with the new solution.

**Comment by bfitzexpensify** [comment] 2023-09-18 10:33
@sobitneupane it looks like @redpanda-bit has changed the solution in https://github.com/Expensify/App/issues/25460#issuecomment-1720047264 - will that still work?

**Comment by sobitneupane** [comment] 2023-09-19 08:28
@redpanda-bit Can you please elaborate more on the problem with the previous solution? Screen Recording will be helpful.

**Comment by redpanda-bit** [comment] 2023-09-19 14:50
So the `useFocuseEffect` function has two functions
1. Do something when component is focused
2. Do something when component is **not** focused

However, the 2nd one runs even though the component **is** focused.

```javascript
    useFocusEffect(
        useCallback(() => {
            // do something when component is focused/on the screen
            Log.client(`Nav: focus = true`);
            isFocusedRef.current = true;
            return () => {
                // do something when component is not focused/not on the screen
                // however, this code runs even though the component is visible
                Log.client(`Nav: focus = false`);
                isFocusedRef.current = false;
            };
        }, []),
    );
```

This is noticeable on ipad mini when rotating the screen (~00:20 in the video below).

https://github.com/Expensify/App/assets/25206487/39cd32c5-b85c-42de-bb23-ee81131eb816

**Comment by sobitneupane** [comment] 2023-09-20 07:28
@redpanda-bit How about using isSmallScreenWidth along with `useFocusEffect`?

**Comment by redpanda-bit** [comment] 2023-09-21 00:07
Thanks @sobitneupane. That approach worked. PR submitted!

**Comment by bfitzexpensify** [comment] 2023-10-13 23:11
Payment summary:

Reporter: @dhanashree-sawant $250 to be paid via Upwork - offer sent
Contributor: @redpanda-bit $1000 to be paid via Upwork - please apply here - https://www.upwork.com/jobs/~0131d1e4274cbc8262
C+: @sobitneupane to be paid $1000 via manual request

**Comment by redpanda-bit** [comment] 2023-10-14 01:11
@bfitzexpensify applied thanks.

**Comment by dhanashree-sawant** [comment] 2023-10-14 06:00
Hi @bfitzexpensify, melvin bot already had sent offer for this job 1 month back and I have also accepted this without cross checking so now I have 2 offers for this job. I have one more job which is ready for payment and I don't have offer in it and it was raised 29 August so would be compensated 250$ for it. 
Link to the job: https://github.com/Expensify/App/issues/26131
To solve this 2 offer issue, can we communicate with @kevinksullivan once and pay that jobs reporting bonus in one of the 2 offers?

Summary would be that @kevinksullivan won't have to send me offer in that job and we can approve both the offers for this job.

**Comment by Gonals** [comment] 2023-10-17 09:47
not overdue

**Comment by bfitzexpensify** [comment] 2023-10-17 17:15
@dhanashree-sawant it's better for our audit trails to link payments to the correct job rather than double-paying against a single job, so we'll keep the usual process in place and have you get paid via https://github.com/Expensify/App/issues/26131. 

Also a friendly reminder @sobitneupane to complete the BZ checklist when you get a moment - thanks!

**Comment by bfitzexpensify** [comment] 2023-10-24 22:47
Bump on the BZ checklist @sobitneupane - thank you!

**Comment by sobitneupane** [comment] 2023-10-27 12:51
Sorry for the delay. I was OOO. I will try to get to this issue in the weekend.

**Comment by sobitneupane** [comment] 2023-10-30 07:33
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

I believe it was present from the very beginning with the introduction of the feature.
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It is an edge case and very difficult to catch.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-30 07:37
**Regression Test Proposal:**

- Long Press (on IOS, Android and mWeb) an option row from LHN.
- Verify pop up shows
- Dismiss the pop up by tapping outside
- Tap on one of the items and quickly long press on the same item
- Verify pop up does not show while on the report screen

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-10-30 13:52
Requested payment on newDot.

https://github.com/Expensify/App/issues/25460#issuecomment-1762366808

**Comment by bfitzexpensify** [comment] 2023-10-31 22:23
Cool, I agree with that checklist summary. Opened regression test proposal in https://github.com/Expensify/Expensify/issues/331848. We're all done here - thanks everyone!

**Closed by bfitzexpensify** 2023-10-31 22:23 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:14
$1,000 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/25460#issuecomment-1762366808).
