### ISSUE TITLE
[HOLD for payment 2024-06-13] More feature Popup - Text under "not so fast" quickly disappears & slightly shrinks popup

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42903] opened 2024-05-31 09:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/42662
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Access new.staging.expensify.com
2. Sign into a valid account
3. Open any workspace with an existing accounting integration - say, Xero or QBO..
4. Click on More Features.
5. Go to Organize section and try clicking on any of the switches.
6. Verify that you see a modal with the following content & click on "Cancel" (Observe the popup dimension size)

## Expected Result:
User expects the popup to simply disappear instanly

## Actual Result:
The popup ever so slightly resizes (The text under "not so fast" simply disappears). before the popup goes away. Making it to where it slightly changes size before going away.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7a3d3ad4-c3e9-4be3-a91c-9eb09f25e245

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by izarutskaya** [comment] 2024-05-31 09:57
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-31 09:57
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-31 09:58
Production 

https://github.com/Expensify/App/assets/115492554/47270b75-1075-4e3b-b6cd-e832eb653632

**Comment by MariaHCD** [comment] 2024-05-31 10:23
Looks like this can be a followup from https://github.com/Expensify/App/pull/42662

cc: @lakchote @mananjadhav 

I don't think this should block the deploy

**Comment by MariaHCD** [comment] 2024-05-31 10:24
@mananjadhav would you be able to handle this improvement?

**Comment by mananjadhav** [comment] 2024-05-31 10:40
@MariaHCD Yes I can handle this as a follow up. Quick question though (may be even for @lakchote). I am using the same modal for Organize and Integrate section. 

I had intentionally put this behavior because when I set the state to false for the modal, it doesn't immediately close the popup. If had the content `organize description` in if block and `integrate description` as false, then while closing the organize modal it would show up the integrate description momentarily. One solution I have is separate modals for both the sections. Are we okay with that?

**Comment by MariaHCD** [comment] 2024-05-31 10:53
> One solution I have is separate modals for both the sections. Are we okay with that?

@mananjadhav If separate modals is the only way to implement this improvement, I think it should be fine. cc: @lakchote for thoughts too.

**Comment by MariaHCD** [comment] 2024-05-31 10:54
@ShridharGoel Thanks for the proposal but I think we'll likely keep this assigned to @mananjadhav since it is followup polish from https://github.com/Expensify/App/pull/42662

**Comment by mananjadhav** [comment] 2024-05-31 10:59
> @ShridharGoel Thanks for the proposal but I think we'll likely keep this assigned to @mananjadhav since it is followup polish from #42662

Yes. This need not be external.


> > One solution I have is separate modals for both the sections. Are we okay with that?
> 
> @mananjadhav If separate modals is the only way to implement this improvement, I think it should be fine. cc: @lakchote for thoughts too.

I wouldn't say the only way. We would anyway need to add some or the other state variable to track it, then why not just keep the modals separate, instead of complicating it with multiple state or side effect checks.

**Comment by MariaHCD** [comment] 2024-05-31 11:31
Keeping it simple sounds good to me 👍🏼

**Comment by lakchote** [comment] 2024-05-31 15:15
I do agree with you both @MariaHCD @mananjadhav , let's not complicate it and bloat code with different states/checks. I'm in favor of the separate modals 👍

**Comment by mananjadhav** [comment] 2024-05-31 15:20
I added a PR but i have some power issues. I’ll finish the checklist as soon as I have it back.

**Comment by mananjadhav** [comment] 2024-06-04 10:24
@MariaHCD, @lakchote is OOO, could you take a look at this PR?

**Comment by MariaHCD** [comment] 2024-06-04 10:27
Yes, can do 👀

**Comment by MariaHCD** [comment] 2024-06-04 10:29
Merged the PR: https://github.com/Expensify/App/pull/42919

**Comment by CortneyOfstad** [comment] 2024-06-07 17:00
@mananjadhav when you have a chance can you complete the checklist above so there is no delay in issuing payment? Thanks!

**Comment by mananjadhav** [comment] 2024-06-07 17:31
@CortneyOfstad There won't be any payout for this issue. This was more of a follow up from https://github.com/Expensify/App/pull/42662 which was worked by me only. 

No further action needed here. Just need to wait for the regression period and close it out.

**Comment by CortneyOfstad** [comment] 2024-06-13 15:39
Sounds good @mananjadhav! Thanks!

**Closed by CortneyOfstad** 2024-06-13 15:39 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
