### ISSUE TITLE
[$250] VBA - Each of the Workspace option setting is showing locked after refresh

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9535] opened 2022-06-22 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing:** https://github.com/Expensify/App/pull/9490

## Action Performed:
1. Go to staging.new.expensify.com and go to settings
2. Enable Staging Setting
3. Go to any Workspace and click Connect bank account
4. Select Connect by Plaid and add the Bank account
5. Go to Setting - Payments
6. Verify the Bank account is displayed
7. Go to OldDot with the same account
8. Go to Setting - Account - Payments
9. Delete the VBA
10. Go to New Expensify app
11. Tap on Setting - Workspace
12. Check each of the Workspace option settings

## Expected Result:
Each of the Workspace option setting is showing locked after delete the VBA from OldDot

## Actual Result:
Each of the Workspace option setting is showing locked after refresh.

## Workaround:
Unknown

## Additional Information:
Also after deleted the VBA from the Payment option page - VBA is still present

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.78.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/175103247-78bd0dfd-a7cd-4207-9525-79fd57a803b9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment] 2022-06-22 19:51
For the first video, going outside of NewDot, making a change in OldDot, and having not reflect in NewDot without a refresh is a pretty edge case flow that we aren't looking to solve at this time. Going to remove it from the main issue to prevent confusion

The second video does seem like something we need to fix, since we should not be showing it on that list after we have selected delete. Should be solvable externally.

**Comment by kaushiktd** [comment] 2022-06-23 05:34
For that when you have removed your bank account then maybe props is not getting 
refreshed so it is showing still locked. We need to find whether the redux props value is getting 
updated or not.

**Comment by kaushiktd** [comment] 2022-06-23 14:30
@Santhosh-Sellavel Can you please explain what you mean by making a proposal? I checked that examples link which shows a list of HOLD FOR PAYMENT tasks. If you can guide me, will be very helpful.

**Comment by kaushiktd** [comment] 2022-06-24 13:22
@Santhosh-Sellavel When we are adding a new bank detail, Plaid is redirected to Bank sever to authenticate, and we don't have any bank account listed in the Plaid account list.
We can't check it with test credentials because the backend API is returning the production server token, so it is not working.

Without adding any bank account we can't find why it is locked after even being removed. Is there anyway I can add the bank?

See the recording: https://drive.google.com/file/d/1FD0b3I5K1keqX0SbVil4kEFE7mkuOWo8/view?usp=sharing

**Comment by mvtglobally** [comment] 2022-06-28 04:12
Issue not reproducible during KI retests. (First week)

**Comment by arielgreen** [comment] 2022-07-01 22:18
let's give it another week before closing

**Comment by mvtglobally** [comment] 2022-07-05 04:43
Issue not reproducible during KI retests. (Second week)

**Comment by stitesExpensify** [comment] 2022-07-11 23:10
When do we usually close issues? This is the third week right?

**Comment by arielgreen** [comment] 2022-07-16 18:01
Closing

**Closed by arielgreen** 2022-07-16 18:01 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
