### ISSUE TITLE
[$500] Web - Chat - "Fire" is missing from the suggested emojis

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35199] opened 2024-01-25 22:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4237630&group_by=cases:section_id&group_id=292106&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Send any text in a chat
2. Hover over the text

## Expected Result:
"Fire" emoji should be visible.

## Actual Result:
"Fire" is missing from the suggested emojis. It's still available if you right click a message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/773daa48-d14d-453d-8f95-ccbc66acc96d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb30dd161d0ef71b</li>
        <li>Upwork Job ID: 1750641036398268416</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-25 22:05
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by laurenreidexpensify** [comment] 2024-01-26 10:23
cc @Expensify/design

**Comment by shawnborton** [comment] 2024-01-26 11:09
Hmm yeah, cc @dubielzyk-expensify @JmillsExpensify in case this was related to some of the mini menu improvements that were made recently. Was it intentional to remove the fire emoji?

**Comment by mananjadhav** [comment] 2024-01-26 11:12
And also what would be the expected behavior? Do we want to maintain consistency? or do nothing?

**Comment by dannymcclain** [comment] 2024-01-26 14:01
> Hmm yeah, cc @dubielzyk-expensify @JmillsExpensify in case this was related to some of the mini menu improvements that were made recently. Was it intentional to remove the fire emoji?

I don't think this is a bug. I think this is an intended update as part of the comment action menu updates we recently rolled out. Here's a mock from the Figma file/design doc:

![image](https://github.com/Expensify/App/assets/7516624/9d494b0d-e3d3-429a-bdca-2b1289abdb77)

**Comment by dubielzyk-expensify** [comment] 2024-01-28 22:50
Like Danny said, yep it's part of us reducing the amount of cognetive load and therefor less items. One had to go sadly. I think at a later stage we'll allow to chose your favorite 3 like Slack does or just put the most commonly used

**Comment by mananjadhav** [comment] 2024-01-29 00:46
@laurenreidexpensify Based on the comments above, best we close this one out?

**Closed** 2024-01-29 11:32 UTC
Labels: External, Daily, Help Wanted, Bug
