### ISSUE TITLE
[$500] Private Note -  "hmm... it's not here" page is shown when reloading in Private Notes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30211] opened 2023-10-23 21:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698067117518239

## Action Performed:
1. Go to Private notes > My notes > notes
2. Reload page
3. Click on the back button

## Expected Result:
Navigates back to the previous page

## Actual Result:
 "hmm... it's not here" page is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/93399543/5c1f4160-477b-4552-ba55-8eefa6fe633a

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/4f61b9e1-c905-4932-bc67-68dde585120b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/15100ada-e6b8-4508-b06e-e41a8f755c4b

https://github.com/Expensify/App/assets/93399543/6e405968-312d-4c11-90b0-39e8b101ca64

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018db0726a7be74290</li>
        <li>Upwork Job ID: 1716562302714707968</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27475744</li>
<li>c3024 | Contributor | 27475746</li>
<li>daveSeife | Reporter | 27475748</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-23 21:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Reloading the private notes edit page and clicking on back icon shows not found page.
### What is the root cause of that problem?
We have a typo here for `reportID`
https://github.com/Expensify/App/blob/e968637a35b19dfbd7ad7f437b68fda57fc16d63/src/pages/PrivateNotes/PrivateNotesEditPage.js#L134
### What changes do you think we should make in order to solve the problem?
Fix the typo and change that to `reportID`
### What alternative solutions did you explore? (Optional)
<details>
<summary>Result</summary>


https://github.com/Expensify/App/assets/102477862/214e239d-34df-4988-a728-a64d1bd3be8b






</details>

**Comment by graylewis** [comment] 2023-10-23 21:23
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When opening a specific private note and reloading, pressing back triggers a 404.

### What is the root cause of that problem?
While on other similar routes a goBack url parameter is utilized to ensure that this specific issue doesn't happen in modals, in this one there is no goBack parameter.

The private notes view routing: 
```
    PRIVATE_NOTES_VIEW: {
        route: 'r/:reportID/notes/:accountID',
        getRoute: (reportID: string, accountID: string | number) => `r/${reportID}/notes/${accountID}`,
    },
```

The currency request edit view routing: 
```
    EDIT_CURRENCY_REQUEST: {
        route: 'r/:threadReportID/edit/currency',
        getRoute: (threadReportID: string, currency: string, backTo: string) => `r/${threadReportID}/edit/currency?currency=${currency}&backTo=${backTo}`,
    },
```
### What changes do you think we should make in order to solve the problem?
Add a back to parameter in the private notes view routing. This would also entail passing the proper report ID to the backTo parameter when calling getRoute on the private notes view.

    const trimmedSearchValue = StringUtils.sanitizeString(searchValue);
    if (!trimmedSearchValue) {
        return countriesData;
    }

**Comment by lschurr** [comment] 2023-10-26 15:51
@aimane-chnaif could you review the proposal here?

**Comment by lschurr** [comment] 2023-11-01 15:37
Any update @aimane-chnaif?

**Comment by lschurr** [comment] 2023-12-08 15:53
Looks like the automation didn't work for this one. I'll review today.

**Comment by lschurr** [comment] 2023-12-08 16:01
All are paid in Upwork. Closing.

**Closed by lschurr** 2023-12-08 16:01 UTC
Labels: External, Daily, Bug
