### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Characters missing when typing message in compose box

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#37356] opened 2024-02-27 21:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from [here](https://github.com/Expensify/App/issues/34467) where we were able to document reliable reproduction steps.

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** [here](https://expensify.slack.com/archives/C049HHMV9SM/p1705090464307259)

## Reproduction Steps
1. Open Script Editor (Mac)
2. New Document > Paste the following script
```bash
on run
	set textToType to "JUMP "
	repeat
		emulateTyping(textToType)
		delay 1
	end repeat
end run

on emulateTyping(textToType)
	tell application "System Events"
		repeat with i from 1 to count of characters of textToType
			set currentChar to character i of textToType
			keystroke currentChar
			delay 1
		end repeat
	end tell
end emulateTyping
```
3. Press the play button (run the script)
4. Focus the desktop newDot app composer
5. Wait until you observe that a letter from the word 'JUMP' is being omitted after being typed.

**Expected result:**
The word 'JUMP' needs to be typed with consistency in the composer. **ignore the first word it is because we had a delay when focusing the input.**

**Actual result:**
After a few tries character gets omitted and the word becomes inconsistent. i.e. `JUMP JUMP JMP`

https://github.com/Expensify/App/assets/75031127/65090f16-9610-456c-8490-201064151216

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
View the [other issue](https://github.com/Expensify/App/issues/34467#issuecomment-1958976159). 

## Additional Deliverable 
From [here](https://github.com/Expensify/App/issues/37356#issuecomment-1994193412)
> FWIW the issue also occurred when editing the message, I think that should also be fixed in this post.

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104493dfd4225a65e</li>
        <li>Upwork Job ID: 1763648489851805696</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2024-02-27 22:54
@johncschuster, I'll take this, I have context from the issue this came form, and the bug.

**Comment by wildan-m** [comment] 2024-02-29 03:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Characters missing when typing message in compose box

### What is the root cause of that problem?

Seems we can't directly use underscores debounce with react setState. Through [this snack](https://snack.expo.dev/@muhliswildan/debounce-x-usestate). I can reproduce the issue with a minimal example.

Result:

https://github.com/Expensify/App/assets/11847279/d7ae91fa-8a8c-4d2d-a7dd-e6f6ecf4faf5

I'm not quite sure how react's setState works internally, but I think it's related to how underscore's debounce works.

In a debounce function, "leading" determines whether the function should run immediately at the start, and "trailing" determines if it should run after the delay following the last event.

By default, lodash's debounce has the `leading` property set to `false` and `trailing` set to `true`, which means it will hold the method invocation at the trailing phase of the debounce interval.

This situation makes the `setState` miss important keystroke events at the initial invocation.

### What changes do you think we should make in order to solve the problem?

**What if we set the `trailing` to `false` and `leading` to `true`?** 

It means the debounced function will be invoked immediately when the event occurs, and then it will be debounced for subsequent calls.

It will not miss a keystroke, but the onyx `saveReportComment` data will not be properly updated, as it will not call the method at the end of the debounce trailing phase.

The issue illustrated in this video

https://github.com/Expensify/App/assets/11847279/23b4d62b-6106-4012-8d8c-57f173f3cb83


**Better solution**

We can trigger the `saveReportComment` function in both the `leading` and `trailing` phases to ensure setState doesn't missed important invocation.

Change this lines:

https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L322-L328

To

```
....

    const debouncedSaveReportComment = useMemo(
        () =>
            lodashDebounce(
                (selectedReportID, newComment) => {
                    Report.saveReportComment(selectedReportID, newComment || '');
                }
                , 1000, { leading: true, trailing: true }),
        [],
    );
```

Test with 'JUMP' at 1-second typing interval.
https://github.com/Expensify/App/assets/11847279/7e7570a0-9fad-4f72-bc43-fba37dbc0e01

Test with paragraph at 100 millisecond typing interval
https://github.com/Expensify/App/assets/11847279/16487c03-dd25-41b7-a6c5-6077d93e8f05


### What alternative solutions did you explore? (Optional) 
We can remove the `shouldDebounceSaveComment` feature and its function `debouncedSaveReportComment`. Though it functions, it will revert us to the pre-optimized state, resulting in noticeable lag as the method will be executed for each character.

https://github.com/Expensify/App/assets/11847279/d7b518f0-20f7-45cc-8b51-2cb7fa557000

**Comment by jeremy-croff** [comment] 2024-02-29 05:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We lose characters when typing

### What is the root cause of that problem?
I was able to pinpoint this early on and documented it [here](https://github.com/Expensify/App/issues/34467#issuecomment-1948663698) in the original thread.

Debouncing in a functional component is actually well known to cause this issue, 
Other documented cases:
https://stackoverflow.com/questions/60789246/react-use-debounce-with-setstate
https://stackoverflow.com/questions/47809666/lodash-debounce-not-working-in-react/64856090#64856090
https://rajeshnaroth.medium.com/using-throttle-and-debounce-in-a-react-function-component-5489fc3461b3

Local variables expire when the component get's re-evaluated, leading to stale and missing data.

The solution for this is to leverage useCallBack, so that the reference to the call is stored. 

### What changes do you think we should make in order to solve the problem?
I verified that replacing useMemo with useCallback like so:
`const debouncedSaveReportComment = useCallback(() => _.debounce((selectedReportID, newComment) => Report.saveReportComment(selectedReportID, newComment || ''), 1000), []);`
mitigates this issue, and stress tested it at 100 ms with the script to confirm.

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-29 05:30
As an additional note to my proposal, we have code that clears the draft in a reset flow. We will slightly have to tweak this when using useCallBack, by clearing the values in a similar way.

**Comment by jeremy-croff** [comment] 2024-02-29 05:57
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Characters missing when typing message in compose box
> 
> ### What is the root cause of that problem?
> Seems we can't directly use default lodash debounce config with react setState. Through [this snack](https://snack.expo.dev/@muhliswildan/debounce-x-usestate). I can reproduce the issue with a minimal example.
> 
> Result:
> 
>  GMT20240229-025010_Clip_Wildan.M.s.Clip.02_29_2024.mp4 
> I'm not quite sure how react's setState works internally, but I think it's related to how default lodash's debounce works.
> 
> In a debounce function, "leading" determines whether the function should run immediately at the start, and "trailing" determines if it should run after the delay following the last event.
> 
> By default, lodash's debounce has the `leading` property set to `false` and `trailing` set to `true`, which means it will hold the method invocation at the trailing phase of the debounce interval.
> 
> This situation makes the `setState` miss important keystroke events at the initial invocation.
> 
> ### What changes do you think we should make in order to solve the problem?
> **What if we set the `trailing` to `false` and `leading` to `true`?**
> 
> It means the debounced function will be invoked immediately when the event occurs, and then it will be debounced for subsequent calls.
> 
> It will not miss a keystroke, but the onyx `saveReportComment` data will not be properly updated, as it will not call the method at the end of the debounce trailing phase.
> 
> The issue illustrated in this video
> 
>  GMT20240229-031351_Clip_Wildan.M.s.Clip.02_29_2024.mp4 
> **Better solution**
> 
> We can trigger the `saveReportComment` function in both the `leading` and `trailing` phases to ensure setState doesn't missed important invocation.
> 
> Change this lines:
> 
> https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L322-L328
> 
> To
> 
> ```
> ....
> 
>     const debouncedSaveReportComment = useMemo(
>         () =>
>             lodashDebounce(
>                 (selectedReportID, newComment) => {
>                     Report.saveReportComment(selectedReportID, newComment || '');
>                 }
>                 , 1000, { leading: true, trailing: true }),
>         [],
>     );
> ```
> 
> Test with 'JUMP' at 1-second typing interval.
> 
>  GMT20240229-023310_Clip_Wildan.M.s.Clip.02_29_2024.mp4 
> Test with paragraph at 100 millisecond typing interval
> 
>  GMT20240229-022734_Clip_Wildan.M.s.Clip.02_29_2024.mp4 
> ### What alternative solutions did you explore? (Optional)
> We can remove the `shouldDebounceSaveComment` feature and its function `debouncedSaveReportComment`. Though it functions, it will revert us to the pre-optimized state, resulting in noticeable lag as the method will be executed for each character.
> 
>  GMT20240229-024116_Clip_Wildan.M.s.Clip.02_29_2024.mp4

I would like to explain why your solution is a regression and does not mitigate the bug.

Specifically note from the [docs](https://lodash.com/docs/4.17.15#debounce) the following:
`If leading and trailing options are true, func is invoked on the trailing edge of the timeout only if the debounced function is invoked more than once during the wait timeout.` 

If you type 1 character per second, and the wait is 1 second, **it will now never call the debounce.**
Looking at the console from the example video you sent, we no longer see the following action ` merge() called for key: reportDraftComment_239993415390396`, hence the bug is not reproduced  but also caused the regression of not saving a draft.

**Comment by wildan-m** [comment] 2024-02-29 06:10
@jeremy-croff Thanks for your comment. To help readers stay focused, I filter my console log with the 'wildebug' keyword. This is my personal debug code.

**Comment by jeremy-croff** [comment] 2024-02-29 07:36
> @jeremy-croff Thanks for your comment. To help readers stay focused, I filter my console log with the 'wildebug' keyword. This is my personal debug code.

Thank you and my apologies, I edited my wording a bit in the same train of thought. I also deleted my original proposal and have a new one to consider:

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are missing characters when typing

### What is the root cause of that problem?
1. We have an async report draft saving lifecycle to the onyx store, that will rerender the component with what's in the store.
2. At the same time we have an async setTimeout, with the debounce which can reset the draft text in the store
3. We have a state variable in the Composer component with the current text value that we set [here](https://github.com/Expensify/App/blob/48b24ec69b585d4fc660e9569a59d72aeb21c637/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L252) 

These three compete with what's on the screen, what should get debounced, and what's in the store.

To reproduce the bug, we we maximize the draft saving lifecycles, to trigger rerenders, which occur each time you wait >1 sec because the debounce, Let's say you type a character before that change is reflected on the input 1. a debounce will save it, but it gets wiped while it repaints from onyx. And after the repaint 2. changeText is detected and now the debounce will just simply save the text with the missing character. 

I was able to isolate the related code early on [here](https://github.com/Expensify/App/issues/34467#issuecomment-1948663698) in the original thread.

### What changes do you think we should make in order to solve the problem?
When reviewing a solution, I wanted to decouples these 3 factors, 
I came up with the following:
1. one source of truth for what we try to save as a draft, which is what's in the components state variable, not in a debounced memory
2. Example: `useEffect(() => _.debounce((selectedReportID) => Report.saveReportComment(selectedReportID, value || ''), 1000), [value]);`
note: value is the existing state variable that we set on text update [here](https://github.com/Expensify/App/blob/48b24ec69b585d4fc660e9569a59d72aeb21c637/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L252)

**Comment by mallenexpensify** [comment] 2024-03-01 19:35
@getusha  , can you please review the above proposals? Assigning to you since [you're also on the issue for documenting reproducible steps. ](https://github.com/Expensify/App/issues/34467)

@sobitneupane , sorry about adding you by mistake via the `Internal` label.

**Comment by getusha** [comment] 2024-03-03 16:51
Thanks @mallenexpensify,
Testing proposals i will update soon.

**Comment by getusha** [comment] 2024-03-04 22:32
@jeremy-croff thanks for the proposal, could you add a little more details to the solution you're proposing?

**Comment by jeremy-croff** [comment] 2024-03-04 23:11
> @jeremy-croff thanks for the proposal, could you add a little more details to the solution you're proposing?

I would add `useEffect(() => _.debounce((selectedReportID) => Report.saveReportComment(selectedReportID, value || ''), 1000), [value]);`
and delete this line: https://github.com/Expensify/App/blob/780e2ac33b74f8a4c5d7123729bd7753a3c90508/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L429

Since that line is uses "newCommentConverted" variable that is getting out of sync with the state variable being set here newCommentConverted

This simplifies the component lifecycles, and saves the report on state variable changes that happend as the effect of the user typing, not the callback from user typing.

Is that enough detail?

**Comment by mallenexpensify** [comment] 2024-03-07 00:22
@getusha can you please respond to @jeremy-croff 's post above? Thx

**Comment by getusha** [comment] 2024-03-07 07:08
@jeremy-croff it is not clear how you plan to pass `selectedReportID` to the `useEffect`?

**Comment by jeremy-croff** [comment] 2024-03-07 14:04
> @jeremy-croff it is not clear how you plan to pass `selectedReportID` to the `useEffect`?

Reported is available in the scope as a component prop

**Comment by jeremy-croff** [comment] 2024-03-07 14:25
`useEffect(() => _.debounce(() => Report.saveReportComment(reportID, value || ''), 1000), [value]);` is the valid implementation with the right variable name

**Comment by mallenexpensify** [comment] 2024-03-07 15:56
Added to #vip-vsb room.

**Comment by mallenexpensify** [comment] 2024-03-10 22:06
@getusha , 👀 plz on @jeremy-croff 's comment above.  I'd love to get this resolved soon, if only cuz I personally run in it semi-frequently.

**Comment by getusha** [comment] 2024-03-11 04:33
>If you type 1 character per second, and the wait is 1 second, it will now never call the debounce. I think we see a few of those occurrences in your video.

@jeremy-croff i checked this and doesn't seem to experience this issue & mind sharing your test branch?

**Comment by jeremy-croff** [comment] 2024-03-11 04:54
> > If you type 1 character per second, and the wait is 1 second, it will now never call the debounce. I think we see a few of those occurrences in your video.
> 
> @jeremy-croff i checked this and doesn't seem to experience this issue & mind sharing your test branch?
If you review the video from @wildan-m 

<img width="797" alt="Screenshot 2024-03-10 at 11 42 31 PM" src="https://github.com/Expensify/App/assets/157416545/68865c85-026c-4e88-af0c-4a797f222cc1">
Between JU and JUMP the save for JUM is skipped because it met that condition.
After 30 seconds of the video it doesn't seem to log anymore at all - but I'm not sure if that was his console freezing or anything with the code.

**Comment by jeremy-croff** [comment] 2024-03-11 05:36
> > If you type 1 character per second, and the wait is 1 second, it will now never call the debounce. I think we see a few of those occurrences in your video.
> 
> @jeremy-croff i checked this and doesn't seem to experience this issue & mind sharing your test branch?

Here is the draft branch:
https://github.com/Expensify/App/pull/38029/files

**Comment by jeremy-croff** [comment] 2024-03-11 06:32
@getusha 
Draft is here: https://github.com/Expensify/App/pull/38029
Admittedly, this is a different implementation from what I posted.
I uploaded it here. https://drive.google.com/file/d/1J8WJ384xhkVqVIwTvwqUawDo329QrASi/view?usp=sharing (It's a bit over 10mb)

I try to respond promptly when you message, but it's very late for me in my timezone. So I will have to come back tomorrow with more details. Thanks.

I wrapped the existing implementation in a callback, since it has the dependency on the state value of value ( text value ), to handle the state variable as the source of truth.

**Comment by wildan-m** [comment] 2024-03-11 06:39
> Between JU and JUMP the save for JUM is skipped because it met that condition. After 30 seconds of the video it doesn't seem to log anymore at all - but I'm not sure if that was his console freezing or anything with the code.

@jeremy-croff have you seen this video? It will save the draft during the last debounce interval as we have set trailing to true.

> Test with paragraph at 100 millisecond typing interval

> https://private-user-images.githubusercontent.com/11847279/308779325-16487c03-dd25-41b7-a6c5-6077d93e8f05.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzc4MzcsIm5iZiI6MTcxMDEzNzUzNywicGF0aCI6Ii8xMTg0NzI3OS8zMDg3NzkzMjUtMTY0ODdjMDMtZGQyNS00MWI3LWE2YzUtNjA3N2Q5M2U4ZjA1Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNDkxNjBlN2RhZDJjOTEwOGI3YzY1MzNkNTEyNzNhOTI4NTU1NjNmYzFmM2I0MWNhNzc2YjRjODhlN2QyNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xFnpuWXqXgNuxz5qRmkqSl7RX8u0eozCU1sBNc7WxBU

In my opinion, the middle call is not as important because we need to debounce them to maintain optimization. What is important is the leading and trailing edge: leading to ensure the value stays in sync with the React state and trailing to ensure all draft values are stored.

Here is another way to demonstrate how it works. The debounced function will be called at least twice, at the start and end of invocation.

https://github.com/Expensify/App/assets/11847279/3c00054f-fe8a-4eaf-b9a3-57da908cf8ed

[Codesandbox Link](https://codesandbox.io/p/sandbox/debounce-trailing-leading-true-lfldqw?file=%2Fsrc%2Findex.js%3A6%2C37)

**Comment by jeremy-croff** [comment] 2024-03-11 07:00
> , { leading: true, trailing: true }
![Screenshot 2024-03-11 at 1 59 19 AM](https://github.com/Expensify/App/assets/157416545/4bdd3282-6769-46d7-84f0-5b96a1184d2b)
Effectively with leading and trailing true you are shifting the time intervals debounce is called, making it much harder to reproduce to race condition programatically, but it still exists. Attached is a screenshot with the following script:

`on run
	set textToType to "JUMP JUMP JUMP JUMP JUMP JUMP JUMP"
	repeat
		emulateTyping(textToType)
		delay 1
	end repeat
end run

on emulateTyping(textToType)
	tell application "System Events"
		repeat with i from 1 to count of characters of textToType
			set currentChar to character i of textToType
			keystroke currentChar
			delay 0.1
		end repeat
	end tell
end emulateTyping
` with the leading and trailing changes you suggest.

Are you able to reproduce the same?

**Comment by wildan-m** [comment] 2024-03-11 07:17
> you are shifting the time intervals debounce is called

@jeremy-croff I don't understand how setting the leading to true causes the time intervals to shift. Could you clarify?

I couldn't reproduce it using the script either. I can only reproduce missing spaces due to a space error in your test script. Did you mean
```
set textToType to "JUMP JUMP JUMP JUMP JUMP JUMP JUMP " <-- with space before double quote
```

I almost had to hard reset my device because your script delay is too short 😆

**Comment by jeremy-croff** [comment] 2024-03-11 07:23
> > you are shifting the time intervals debounce is called
> 
> 
> 
> @jeremy-croff I don't understand how setting the leading to true causes the time intervals to shift. Could you clarify?
> 
> 
> 
> I couldn't reproduce it using the script either. I can only reproduce missing spaces due to a space error in your test script. Did you mean
> 
> ```
> 
> set textToType to "JUMP JUMP JUMP JUMP JUMP JUMP JUMP " <-- with space before double quote
> 
> ```
> 
> 
> 
> I almost had to hard reset my device because your script delay is too short 😆
> 
> 
> 
> Perhaps you could share a screen recording for better clarification.

In order to reproduce the bug we want to maximize the draft saves, and enter a character right during that time period. The script was consistently able to do so at the set interval.

But then adding trailing and leading would reduce the draft saves, and stretch the time to greater than the typing interval

This timeline here shows the reduction in draft saves as well:
https://ellenaua.medium.com/throttle-debounce-behavior-lodash-6bcae1494e03

**Comment by jeremy-croff** [comment] 2024-03-11 07:24
> > you are shifting the time intervals debounce is called
> 
> 
> 
> @jeremy-croff I don't understand how setting the leading to true causes the time intervals to shift. Could you clarify?
> 
> 
> 
> I couldn't reproduce it using the script either. I can only reproduce missing spaces due to a space error in your test script. Did you mean
> 
> ```
> 
> set textToType to "JUMP JUMP JUMP JUMP JUMP JUMP JUMP " <-- with space before double quote
> 
> ```
> 
> 
> 
> I almost had to hard reset my device because your script delay is too short 😆
> 
> 
> 
> Perhaps you could share a screen recording for better clarification.

Hindsight I don't know if 100ms makes sense for draft saves :P but that's great if you can't reproduce it.. I did not add a space but in the screenshot a few other characters got jumbled besides the space.

**Comment by jeremy-croff** [comment] 2024-03-12 05:41
Hi @getusha and @mallenexpensify!
I have a fresh take on this problem that I think is really going to provide the clarity here!

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are losing characters intermittently

### What is the root cause of that problem?
In our composer, we have  a [SilentComponentUpdater](https://github.com/janicduplessis/Expensify-App/blob/9ce52d1ed818f739e29818311c121976b72df17f/src/pages/home/report/ReportActionCompose/SilentCommentUpdater.js#L41) component that connects to the onyx store, and saves the draft to the composer. It's purpose is to sync drafts between tabs. 

What is happening is that we save debounced drafts. Then the SilentComponentUpdater listens to this change, and tries to save the draft AGAIN if the composers' value does not equal that of the new draft it's trying to save.  If we have successfully reproduced the bug, the composers' value will not match the draft value, and we will try to save it again. However this time it only saves the stale draft. This exact logic is on [this line](https://github.com/janicduplessis/Expensify-App/blob/9ce52d1ed818f739e29818311c121976b72df17f/src/pages/home/report/ReportActionCompose/SilentCommentUpdater.js#L55). Where you can see it compares `value !== comment` where value is the composer value, and comment the debounced draft value

-If we typed and waited, the composers' value would equal the saved draft, and it would skip trying to re-save.
-If we typed faster than the debounce interval, it wouldn't save the draft and not hit the SilentComponentUpdater.
-There's a magic zone in between both of these: Right after 1 second, when the draft saves async,  and when SilentComposer receives the draft, we can have typed something quickly and met the criteria for the composer not to match the draft, and it tries to resave the stale draft. Thinking it's syncing tabs, as it's original intent was.


### What changes do you think we should make in order to solve the problem?
So, how should we fix this?
Well, since the specific purpose of the SilentComponentUpdater is only to sync the report drafts between tabs, we should enhance the checks here to also only call this on the windows that are NOT focused so as not to interfere with the current typing. This will also reduce rerenders on the current screen!

We have a good set of Visibility API's, that are implemented cross-platform here: https://github.com/Expensify/App/tree/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/libs/Visibility

Which we can leverage to update the existing check 

```
        const shouldSyncComment = prevCommentProp !== comment && value !== comment **&& !Visibility.hasFocus();**
```



Note: this SilentUpdater has been in the app for approx 8 months!
I'm completely able to mitigate any occurrences of the characters missing with this code, and verified that drafts are still syncing between tabs as intended.


### What alternative solutions did you explore? (Optional)

**Comment by getusha** [comment] 2024-03-12 16:25
will be reviewing @jeremy-croff's proposal.

@mallenexpensify could we add external label to see if we can see more proposals?

**Comment by jeremy-croff** [comment] 2024-03-12 19:42
As an additional enhancement it might be prudent to only render the SilentComponentUpdater component only when not a focused window, to further improve the components performance a bit.

**Comment by wildan-m** [comment] 2024-03-13 11:45
FWIW the issue also occurred when editing the message, I think that should also be fixed in this post.

**Comment by mallenexpensify** [comment] 2024-03-14 00:38
Thanks @wildan-m , nice catch!  I added this to the OP

## Additional Deliverable 
From [here](https://github.com/Expensify/App/issues/37356#issuecomment-1994193412)
> FWIW the issue also occurred when editing the message, I think that should also be fixed in this post.

**Comment by jeremy-croff** [comment] 2024-03-14 05:37
Thank you @tienifr  for your analysis!

In order to handle to edge case you mentioned leveraging focus we should just flush out the debounce immediately
`  useEffect(() => {
        //if unfocusing
        debouncedSaveReportComment.flush();
    }, [Visibility.hasFocus()]);`

@getusha Can you include that as part of my proposal?
   
I confirmed that this immediately syncs the draft to the new tab and improves the user experience. Otherwise, there is a one-second delay for syncing the tab. Note that this entire circumstance is a hyper-edge case and would only exist if the user uses some shortcut, like keyboard keys, to navigate back and forth.

I also confirmed Implementing the overall solution inside of SilentComponentUpdater using focus APIs will handle all cases such as edit without needing additional code per each implementation to pass the saving state.

**Comment by jeremy-croff** [comment] 2024-03-14 13:36
> I think relying on another state is unnecessary performance overhead, considering there's another potential approach that doesn't rely on any such new state.
> 
> 
> 
> > useEffect(() => { //if unfocusing debouncedSaveReportComment.flush(); }, [Visibility.hasFocus()]);
> 
> 
> 
> Also I doubt implementing it the way you're doing here will work, since `Visibility.hasFocus()` is not a state.
> 
> 
> 
> And visibility changes are on many different cases, not just when switching tabs, so debounce flushing will happen more frequently than necessary, also will impact performance. Eg. When I'm typing and open another Mac app, it will also trigger flushing (although it doesn't need to)

We are actually improving the performance and re-renders here by not setting a new and unnecessary draft state on the tab we are working on for a feature that is intended to sync other tabs only.

The flushing of the debounce will only perform a draft save if there something unsaved and we are navigating away, it now just does it immediately, this is not a performance overhead.

If you're referring to a no-op call being a performance overhead when navigating away then I disagree.

The visibility API being used for my intended purpose can by done in multiple ways as we have an on change call back available in the visibility utils, we can leverage as well

**Comment by jeremy-croff** [comment] 2024-03-14 13:43
On another note: if we have an app instance id or key to differentiate the tabs internally then we can leverage that instead to determine whether or not I need to sync my own draft using SilentComponentUpdater. I think this would be the ultimate solution.

**Comment by wildan-m** [comment] 2024-03-14 18:47
@getusha I've updated [my proposal](https://github.com/Expensify/App/issues/37356#issuecomment-1970333851).

I moved my original main solution to **Alternative 2** and added a new main solution that utilizes a typing tracking hook.

If anything is unclear in the explanation, I have created a [branch](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/37356-missing-char-when-typing?expand=1) for my new solution.

**Comment by getusha** [comment] 2024-03-17 10:15
@jeremy-croff after applying your solution the draft is not syncing between tabs consistently.

https://github.com/Expensify/App/assets/75031127/30b7341c-79ae-4765-8c5a-b5ab785e5b13

**Comment by jeremy-croff** [comment] 2024-03-18 06:31
> useEffect(() => { //if unfocusing debouncedSaveReportComment.flush(); }, [Visibility.hasFocus()]);

I pushed some POC code to my branch so that you can review the code that makes it sync:
https://github.com/jeremy-croff/App/tree/37356
diff https://github.com/Expensify/App/compare/main...jeremy-croff:App:37356?expand=1

https://github.com/Expensify/App/assets/157416545/6e4697be-f255-4bf0-9f47-37d9241d9f0b

**Comment by getusha** [comment] 2024-03-18 12:53
>FYI the approach of only sync comment if the tab is not visible, will not work because if we type in a tab then quickly change to another tab, that "another tab" will not have the comment synced (regression), because at the time that tab is visible.

@tienifr your solution works well but i was concerned about this regression, testing it now.

**Comment by mallenexpensify** [comment] 2024-03-20 00:58
@getusha , what were the results from testing @tienifr 's proposal?

**Comment by getusha** [comment] 2024-03-20 05:32
i think the side effect you mentioned is not that much noticeable and the draft seems to sync anyway. @tienifr am i missing anything?

**Comment by wildan-m** [comment] 2024-03-20 06:29
@getusha Try testing with this test case.

Compare side by side and type back and forth between the windows, move quickly before 1 second.

https://github.com/Expensify/App/assets/11847279/11900aa9-9cd7-47f3-9b96-7168ff94701d

**Comment by getusha** [comment] 2024-03-20 13:04
@wildan-m there may be performance implications associated with introducing debounce and throttle functions for tracking typing status.

@tienifr's [proposal](https://github.com/Expensify/App/issues/37356#issuecomment-1994112425) works really well and is the cleanest one out there. We can move forward with it.
🎀 👀 🎀 C+ Reviewed.

**Comment by getusha** [comment] 2024-03-20 13:04
🎀 👀 🎀 C+ Reviewed

**Comment by mallenexpensify** [comment] 2024-04-17 02:39
Contributor: @tienifr  paid $500 via Upwork
Contributor+: @getusha paid $500 via Upwork

I created the [TestRail GH](https://github.com/Expensify/Expensify/issues/388366) with the test steps below from the PR, comment if there are better steps. 


### Tests

1. Open Script Editor (Mac)
2. New Document > Paste the following script
```
on run
	set textToType to "JUMP "
	repeat
		emulateTyping(textToType)
		delay 1
	end repeat
end run

on emulateTyping(textToType)
	tell application "System Events"
		repeat with i from 1 to count of characters of textToType
			set currentChar to character i of textToType
			keystroke currentChar
			delay 1
		end repeat
	end tell
end emulateTyping
```
3. Press the play button (run the script)
4. Focus the desktop newDot app composer
5. Wait until you observe that a letter from the word 'JUMP' is being omitted after being typed.
6. The word 'JUMP' needs to be typed with consistency in the composer. ignore the first word it is because we had a delay when focusing the input.

**Closed** 2024-04-23 23:01 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
