### ISSUE TITLE
Able to send multiple emoji by drag and drop

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25525] opened 2023-08-19 12:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Open any chat from LHN
3. click emoji picker
4. drag and drop multiple emoji in the composer
## Expected Result: 
Multiple emoji shouldn't be sent
## Actual Result: 
Able to send multiple emoji by drag and drop

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/05563f26-5213-471e-b3f2-b92396519342

https://github.com/Expensify/App/assets/43996225/4d38479a-f256-4eda-be9a-1a4d7f1011d5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692436999667899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment] 2023-08-19 13:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Able to send multiple emoji by drag and drop

### What is the root cause of that problem?

The Text is selectable by default. When we are selecting the emojis by dragging, it selects the emojis as text here.

https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/EmojiPicker/EmojiPickerMenuItem/index.js#L83

### What changes do you think we should make in order to solve the problem?

Just add userSelect style to `none` by doing this
```js
<Text style={[styles.emojiText, styles.userSelectNone]}>{this.props.emoji}</Text>
```

### What alternative solutions did you explore? (Optional)

**Comment by b4s36t4** [comment] 2023-08-19 14:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Able to send multiple emoji by drag and drop 
### What is the root cause of that problem?
This happened after the issue which we've managed to prevent the Drop for unwanted things like links, text etc.

Ex: If we drag text into composer we would be getting the DnD banner we show for files.

Before that also this could happen, but it didn't because of the banner we show on Drop.
This issue happens when we drop the dragged content to into textinput only. which is causing the issue because we're not handling any drop events for textinput and textinput defaulty accept any content dropped into it.

## Demo

https://github.com/Expensify/App/assets/59088937/e4a43fce-c0c5-46ac-95af-bae89b6b5279

If you observe the above video when we drag emoji content into the input it's getting unwanted focus which is causing the issue here.

### What changes do you think we should make in order to solve the problem?
One solution could be disabling the input here, but that could cause the regressions like when we click on the input while the emoji modal is opened it won't close actually it should because of the disabled state input won't process any events causing the emoji modal to keep opened.

As a normal user who is using the composer, will select the input after they completed their work with emoji so this wouldn't solve the entire issue.

Another solution is that we let the composer get focused and prevent drop event so that even composer is focused content won't get pasted.

```jsx
useEffect(() => {
    if (!textInput.current) return;
    const listener = textInput.current.addEventListener('drop', (event) => {
        event.preventDefault();
        return false;
    });
    return () => {
        textInput.current.removeEventListener('drop', listener);
    };
}, [textInput]);
```


### What alternative solutions did you explore? (Optional)
NA

## Result

https://github.com/Expensify/App/assets/59088937/ca80999c-2e9b-4343-be6a-24928a886bec

**Comment by ShogunFire** [comment] 2023-08-20 15:45
Yes it looks like a cool feature actually

**Comment by trjExpensify** [comment] 2023-08-21 10:47
I don't really see this as a problem to fix either, tbh. @arosiclair, what do you think?

**Comment by b4s36t4** [comment] 2023-08-21 10:52
It doesn't only happen with emojis.. what ever you drag into composer it's get pasted.

https://github.com/Expensify/App/assets/59088937/72ce3920-e64a-42eb-bcf2-c7e816e1e842

**Comment by shubham1206agra** [comment] 2023-08-21 11:12
> It doesn't only happen with emojis.. what ever you drag into composer it's get pasted.
> Kapture.2023-08-21.at.16.21.54.mp4

We should not stop everything from getting pasted.
I think it should be upto the engineering team to decide which text is selected.

**Comment by arosiclair** [comment] 2023-08-21 14:03
> I don't really see this as a problem to fix either, tbh. @arosiclair, what do you think?

Agreed this looks more like a feature not a bug. I'd say we close this out

**Comment by trjExpensify** [comment] 2023-08-21 14:15
Cool, closing it out then! :)

**Closed by trjExpensify** 2023-08-21 14:15 UTC
Labels: Engineering, Daily, Bug
