### ISSUE TITLE
[$250] Web - Workspace - App is crashed when trying to delete a new member in the specified account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11814] opened 2022-10-13 18:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login in the specified account - applausetester+1312@applause.expensifail.com/Yulia1986Gerets
3. Go to Settings->Workspace->Manage members
4. Invite new member, then remove it
5. Click invite button again

## Expected Result:
No crash should be expected

## Actual Result:
App is crashed when trying to delete a new member in the specified account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+1312@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195672414-4339d672-14ee-4a81-a710-bd2f886ba335.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment] 2022-10-17 09:08
I cannot reproduce this, maybe it's been fixed by something else.

**Comment by kbecciv** [comment] 2022-10-17 13:13
@tylerkaraszewski Checking with team, will update your shortly

**Comment by kbecciv** [comment] 2022-10-17 15:59
@tylerkaraszewski Unable to reproduce the issue with latest build 1.2.16.4

https://user-images.githubusercontent.com/93399543/196226111-cc286a17-ef5c-43d5-8ec4-315eaa195a10.mp4

**Comment by tylerkaraszewski** [comment] 2022-10-24 13:31
I can replicate this now. I do not know where the error it throws comes from, but it looks like it originates inside react somewhere. I'm going to mark it as external.

<img width="1624" alt="Screen Shot 2022-10-24 at 15 14 18" src="https://user-images.githubusercontent.com/705000/197537627-4150c56f-9b29-4caf-b59b-3541d793c305.png">

**Comment by greg-schroeder** [comment] 2022-10-26 12:34
Internal: https://www.upwork.com/ab/applicants/1585248360435494912/job-details
External: https://www.upwork.com/jobs/~01bf2b0127ab488fa9

**Comment by ctkochan22** [comment] 2022-10-31 17:52
Not overdue

**Comment by mvtglobally** [comment] 2022-11-03 03:11
Issue not reproducible during KI retests. (First week)

**Comment by ctkochan22** [comment] 2022-11-04 05:07
Not overdue. Lowering priority

**Comment by mvtglobally** [comment] 2022-11-09 03:37
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment] 2022-11-15 03:37
If no one else can reproduce this issue, we should close. QA hasn't been able to reproduce it for two weeks straight.

**Comment by greg-schroeder** [comment] 2022-11-15 03:47
Sounds good. I'll close it and close the Upwork issue.

**Comment by kavimuru** [comment] 2022-11-16 14:19
@greg-schroeder Tester is able to reproduce this bug today with newly created expensifail account. Tester said it's reproducible only after creating a new account and next day the crash does not happen. 
Credentials : [applausetester+1611@applause.expensifail.com](mailto:applausetester+1611@applause.expensifail.com) / Yulia1986Gerets

https://user-images.githubusercontent.com/43996225/202204791-c8576fce-eda9-4fc6-a570-d632b199191b.mp4

[crash_1116.txt](https://github.com/Expensify/App/files/10022559/crash_1116.txt)

**Comment by mvtglobally** [comment] 2022-11-30 05:00
Issue not reproducible during KI retests. (Third week). This is not very consistently repro

**Comment by robertjchen** [comment] 2022-12-01 11:28
Closing for now given the lack of reproducibility. Let's revisit if it happens again 👍

**Closed by robertjchen** 2022-12-01 11:28 UTC
Labels: External, Engineering, Weekly, Overdue, Bug
