### ISSUE TITLE
[Hold PR#26307] [$500] Android - Distance - Start and Finish points blink when navigate to Distance tab

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28752] opened 2023-10-03 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to ND app
2. Tap on + button> Request money > Distance tab

## Expected Result:
Distance tab should be displayed without any errors and blinking

## Actual Result:
Start and Finish points blink for a second when User navigate to Distance tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77.2

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6a7a0b18-3e6d-4b38-a8ce-7371cda2c2cd

https://github.com/Expensify/App/assets/115492554/6b07effb-5129-462b-a3de-db1d8d3cfe04

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b68d47c6a36a025</li>
        <li>Upwork Job ID: 1709317169412087808</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-03 21:19
Not reproduced on Prod 

https://github.com/Expensify/App/assets/115492554/92ab3bc5-e221-48e9-bf84-3e0ab72b117c

**Comment by abdulrahuman5196** [comment] 2023-10-04 05:22
Taking a look into this

**Comment by abdulrahuman5196** [comment] 2023-10-04 05:50
Testing. Will update.

**Comment by abdulrahuman5196** [comment] 2023-10-04 07:24
@ZhenjaHorbach The suggested solution is working. Can you provide more information root cause?
I don't see any recent changes in the root cause code mentioned?

Is this regression from some PR? Or why is it happening ?

**Comment by abdulrahuman5196** [comment] 2023-10-04 07:34
@ZhenjaHorbach Sorry, I tested again. And the solution is causing other issues like, If I click on finish before I enter a start point, its leading to NotFound page. And after inputting start, finish just disappears.



https://github.com/Expensify/App/assets/46707890/8e588ff5-bc3d-4062-a33d-fb1e6dabd46a

**Comment by abdulrahuman5196** [comment] 2023-10-04 09:08
@puneetlath We don't have any worthy fix proposals yet. But does this need to be a deploy blocker?

**Comment by situchan** [comment] 2023-10-04 11:38
This will be fixed in #26307

**Comment by trjExpensify** [comment] 2023-10-04 12:10
Oh hm, okay. In which case, we probably need to let this one go to prod because the other PR allegedly fixing it can’t be CP’d to staging now that it has merged, IIRC.

**Comment by puneetlath** [comment] 2023-10-04 13:21
It can be CP'd to staging, not prod. 

But I think this bug isn't one worth CP'ing that over. What do you think @mountiny? I'm thinking we just remove this as a deploy blocker, but leave it open to ensure that https://github.com/Expensify/App/pull/26307 fixes it.

**Comment by puneetlath** [comment] 2023-10-04 14:02
Yep! We got rid of the label and all CPs have to be triggered manually now.

**Comment by abdulrahuman5196** [comment] 2023-10-09 11:38
No worthy proposals yet 

cc: @trjExpensify

**Comment by trjExpensify** [comment] 2023-10-09 12:04
Allegedly it's going to be fixed by https://github.com/Expensify/App/pull/26307?

**Comment by abdulrahuman5196** [comment] 2023-10-09 12:22
@trjExpensify  thank you for that. Missed the message. 
I think it could be. Can we put this issue on hold for that PR?

**Comment by trjExpensify** [comment] 2023-10-09 12:48
Yup! It's on staging as well, I think. @izarutskaya Applause should be able to retest this one on an Android device now.

**Comment by kbecciv** [comment] 2023-10-13 15:45
Unable to reproduce it on build 1.3.83.10

https://github.com/Expensify/App/assets/93399543/d3afca30-4c8d-40f5-8de8-af796ab45674

**Comment by puneetlath** [comment] 2023-10-13 15:46
Great, sounds like it was fixed!

**Closed by puneetlath** 2023-10-13 15:46 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
