### ISSUE TITLE
[HOLD for payment 2024-10-07][$250] Loading skeleton for Settings header is slightly off

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49548] opened 2024-09-20 18:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726813572232319

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Account settings > Trouble shooting
3. Click Clear cache and restart > Reset and Refresh
4. Observe the Avatar and Username in LHN

## Expected Result:
No visual issues 
## Actual Result:
When the account is loading on Settings, the location of the loading skeleton is slightly off from where the actual avatar and username will go

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/aa5fa5d1-16ad-4d0e-867c-e4a19757e83a

https://github.com/user-attachments/assets/a41403be-2807-4ced-b04b-0e1341b539bd

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838488394004973335</li>
        <li>Upwork Job ID: 1838488394004973335</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104109595</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by nkdengineer** [comment] 2024-09-20 19:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the account is loading on Settings, the location of the loading skeleton is slightly off from where the actual avatar and username will go

### What is the root cause of that problem?

Styles change

### What changes do you think we should make in order to solve the problem?


We should add margin-left with negative value [here](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/styles/index.ts#L2828-L2830)

https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/styles/index.ts#L2828-L2830

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-09-23 16:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The setting avatar skeleton loader is not aligned to the left.

### What is the root cause of that problem?
The cx value here is set to 30.
https://github.com/Expensify/App/blob/a5ca9b81ef84ecd57487a98954df52113717eaec/src/components/AccountSwitcherSkeletonView/index.tsx#L35-L36
https://github.com/Expensify/App/blob/a5ca9b81ef84ecd57487a98954df52113717eaec/src/components/AccountSwitcherSkeletonView/index.tsx#L25

The cx value tells the position of the x center of the circle. If we set it to 0, then only the right half of the circle will be shown. 
<img width="268" alt="image" src="https://github.com/user-attachments/assets/0573c5ba-2b54-45a3-93de-a3276def1767">

### What changes do you think we should make in order to solve the problem?

To align the circle to the left of the view, then we need to set the cx to be the half size of the circle, which is the same as its radius. So, we can put the radius value here as the `startPositionX`.
https://github.com/Expensify/App/blob/a5ca9b81ef84ecd57487a98954df52113717eaec/src/components/AccountSwitcherSkeletonView/index.tsx#L25

```
const startPositionX = avatarPlaceholderRadius;
```

<img width="266" alt="image" src="https://github.com/user-attachments/assets/794ea32e-9fbe-4b08-b624-145bb014a442">

**Comment by QasimBham** [comment] 2024-09-24 10:19
Proposal
Please re-state the problem that we are trying to solve in this issue.
The setting's icon is not aligned to the left.
What is the root cause of that problem?
The cx value is set to 30
What changes do you think we should make in order to solve the problem?
The cx value should be set to half of it's original value so that it'll be aligned to left perfectly.
What alternative solutions did you explore? (Optional)

**Comment by QasimBham** [comment] 2024-09-24 10:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The setting's avatar is not left aligned

### What is the root cause of that problem?
The cx value. is set to 30
### What changes do you think we should make in order to solve the problem?
The cx value should be set to half of the original value. This should solve the left alignment icon issue

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

<!---

**Comment by c3024** [comment] 2024-09-24 12:34
Thank you all for your proposals. All correctly identified the Avatar Skeleton Circle centre position as the reason for the mismatch.

As far as my experience and understanding w.r.t. CSS/SVG issues goes, identifying the correct attribute and its accurate value (considering other existing styles/attributes) is seen valuable enough to prioritise a proposal over others.

@bernhardoj 's proposal identifies the circle position exactly to match the loaded avatar position. I think we can go with his proposal.

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment] 2024-09-25 04:28
PR is ready

cc: @c3024

**Comment by kadiealexander** [comment] 2024-10-08 03:25
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@c3024] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@c3024] Determine if we should create a regression test for this bug.
- [ ] [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-10-08 03:27
Payouts due:

- [ ] Contributor: $250 @bernhardoj via manual request
- [ ] Reviewer: $250 @c3024 ([Offer link](https://www.upwork.com/nx/wm/offer/104109595))

Upwork job is [here](https://www.upwork.com/jobs/~021838488394004973335).

**Comment by bernhardoj** [comment] 2024-10-08 04:15
Requested in ND.

**Comment by c3024** [comment] 2024-10-08 10:09
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #47338
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/47338/files#r1791590530
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Go to Settings > Troubleshoot
2. Press Clear cache and restart > Reset and Refresh
3. Go back to Settings if it is narrow layout
4. Verify that the skeleton circle position is same as the real avatar position

**Closed** 2024-10-14 05:41 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-10-15 11:44
$250 approved for @bernhardoj
