### ISSUE TITLE
[$1000] #admins room name in a new workspace shows as "Unavailable Workspace" for a few seconds after scanning QR code

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21398] opened 2023-06-23 12:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Ensure you're logged in on both the web and Android app using the same account.
2. Ensure the app is closed on mobile.
3. Create a new workspace on either Mac Safari or Chrome.
4. Go to the #admins room of the newly-created workspace and click on the large shield icon above the "Say hello!" title.
5. Click on "Share code".
6. Scan the QR code using an Android device (I used the built-in QR code scanner).
## Expected Result: 
When the link is opened on the Android app, the correct #admins room's workspace name is shown as soon as possible.
## Actual Result: 
There's a delay before the workspace name is shown - it's replaced by "Unavailable workspace".
The workspace name in the message below the "Say hello!" title also is replaced by "Unavailable workspace".
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:**  N/A
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f628b37b-209e-4495-9b90-26a44b8c220e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686817966175659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ead90233e62f70ef</li>
        <li>Upwork Job ID: 1673195691241046016</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-26 04:52
Grabbing this since I have an actual Android and Sophie can't replicate on browserstack.

**Comment by jliexpensify** [comment] 2023-06-26 05:01
Ah, I can replicate this on v.1.3.32-5 - there's definitely a few seconds of delay. Here is what happens immediately after the Workspace is loaded via QR code:

![image](https://github.com/Expensify/App/assets/30815269/481dd910-3ce0-458d-a648-f367eb0b77f9)

**Comment by jliexpensify** [comment] 2023-06-26 05:28
Hi @spcheema - at the moment, you're welcome to submit a proposal on how you'd fix this issue. The C+ assigned (i.e. @rushatgabhane) will review these and select the best/most suitable proposal. 

You can review the Proposal template in the .MD [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) - thanks!

**Comment by jliexpensify** [comment] 2023-06-30 01:14
Still looking for proposals!

**Comment by jliexpensify** [comment] 2023-07-03 22:22
Still looking for proposals!

**Comment by ShogunFire** [comment] 2023-07-07 14:54
I don't reproduce

**Comment by jliexpensify** [comment] 2023-07-09 22:29
@ShogunFire Hi, are you saying you're not able to reproduce on the latest version? Can you share a video/the version and platform? Cheers.

**Comment by ShogunFire** [comment] 2023-07-10 01:45
> @ShogunFire Hi, are you saying you're not able to reproduce on the latest version? Can you share a video/the version and platform? Cheers.

I couldn't reproduce on prod, I don't know how to test in dev because to scan the qr code I use my real device and I don't know how to connect to localhost with it.

Also I don't know how to take a video of my device.

Sorry :/

**Comment by jliexpensify** [comment] 2023-07-10 02:33
No worries - I just tested myself on v1.3.38-3 and it looks like this issue is resolved: I see the room name update instantly.

I'll pay out @Victor-Nyagudi , and in the meantime, @kavimuru can you please retest this issue and update us?

**Comment by jliexpensify** [comment] 2023-07-10 02:52
Hi @Victor-Nyagudi looks like I'm running into some issues with Upworks inviting you: can you apply here? https://www.upwork.com/jobs/~01ead90233e62f70ef

Thanks!

**Comment by Victor-Nyagudi** [comment] 2023-07-10 03:59
Hello, @jliexpensify . 

I've applied.

**Comment by jliexpensify** [comment] 2023-07-10 04:18
Thanks @Victor-Nyagudi , accepted!

**Comment by jliexpensify** [comment] 2023-07-10 04:26
Victor paid, job removed. Closing as I can't repro but please re-open @kavimuru if you can still repro this issue.

**Closed by jliexpensify** 2023-07-10 04:26 UTC
Labels: External, Daily, Help Wanted, Bug
