### ISSUE TITLE
 iOS - App Crashed when tap on request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38504] opened 2024-03-18 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+fish101123@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Launch App
2. Navigate to WS Chat
3. Tap on [+] sign and select request money

## Expected Result:
The request money page should be open

## Actual Result:
App crashed when tap on request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/230e2069-767a-4f91-8b17-872f27ef0a1d

[log.txt](https://github.com/Expensify/App/files/14640859/log.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-18 18:26
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-03-18 19:15
It seems like https://github.com/Expensify/App/issues/38502#issuecomment-2004717215 has the same root cause as this issue. Given that https://github.com/Expensify/App/issues/38502 was demoted to NAB, could we also test https://github.com/Expensify/App/issues/38502 when we solve this one and close it if it's fixed?

**Comment by mountiny** [comment] 2024-03-18 19:30
lets just revert that PR and handle these issues found in a v2. 

We incorrectly assumed this will not be needed

**Comment by mountiny** [comment] 2024-03-18 19:30
I would like to not rush these decisions

**Comment by mountiny** [comment] 2024-03-18 19:32
I have made a revert PR here https://github.com/Expensify/App/pull/38508

**Closed** 2024-03-18 21:40 UTC
Labels: Reviewing, Engineering, Weekly
