### ISSUE TITLE
[$250] Web - Email Mention Displays Number Instead of Email When Edited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46426] opened 2024-07-29 16:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to self DM
2. Write an email with a mention (e.g., [betelihemasfaw14@gmail.com](mailto:betelihemasfaw14@gmail.com)
).
3. Use the up arrow to edit the message

## Expected Result:
The email should be displayed when attempting to edit the mentioned email

## Actual Result:
When trying to edit the mentioned email, a number with the mention is displayed instead of the email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cdbb4518-478e-4108-873b-1452c123b3cf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d8db50900d91088</li>
        <li>Upwork Job ID: 1818341999146391970</li>
        <li>Last Price Increase: 2024-07-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by jp928** [comment] 2024-07-31 04:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When edit a mentioned user, the user name turns into account number.

### What is the root cause of that problem?
In the following code
https://github.com/Expensify/App/blob/881c5482facc08af709f047025c863ad67b6d5b3/src/libs/Parser.ts#L18

the account id is saved into `accountIDToNameMap`

While editing a message, the parser in the following code

https://github.com/Expensify/App/blob/881c5482facc08af709f047025c863ad67b6d5b3/src/libs/Parser.ts#L34

would use `String(personalDetails.accountID)` to parse the mentioned user.
### What changes do you think we should make in order to solve the problem?
use `accountIDToNameMap[personalDetails.accountID] = personalDetails.login ?? personalDetails.displayName;`

### What alternative solutions did you explore? (Optional)

Add `login` attribute in the payload of `personalDetialsList`
![Screenshot 2024-07-31 at 2 37 53 PM](https://github.com/user-attachments/assets/9a679669-d089-42fb-8e20-6c5e1a86cad6)

**Comment by DylanDylann** [comment] 2024-08-01 10:42
This issue is fixed by [this PR](https://github.com/Expensify/App/pull/45352)

@lschurr Let's close this issue

**Closed** 2024-08-01 18:03 UTC
Labels: External, Daily, Help Wanted, Bug
