### ISSUE TITLE
Rooms - Notification preference changes back after refresh/reload under Settings

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9805] opened 2022-07-08 16:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR** https://github.com/Expensify/App/pull/9501

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Open an #announce workspace chat
3. Click on the chat header to go to the details
4. Go to the settings
5. Change the notification preferences from any option to mute
6. Refresh the page

## Expected Result:
Сhanging preferences works correctly

## Actual Result:
Drop down works inconsistently after changing Daily notifications to Mute under Settings

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.82.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/178033105-c4594711-ad5c-4226-8bfd-78482a150c8a.mp4

https://user-images.githubusercontent.com/93399543/178046227-64467842-1e3b-4240-bc6a-d99011d84a01.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-07-12 00:40
>when I change the notification preference and refresh the browser quickly, but the bug is not happening consistently

Hard to say what is happening without looking at the network traffic.

**Comment by marcaaron** [comment] 2022-07-12 00:42
Though it seems pretty consistently broken on my end. Did we check logs for any errors?

**Comment by marcaaron** [comment] 2022-07-12 00:49
I think the problem is something to do with this. Must not be sending the `notificationPreferences` rNVP.

https://github.com/Expensify/App/blob/75c0ed3b5ebebe4dc5bc3b46a8ae7449ee25892d/src/libs/actions/Report.js#L185-L185

**Comment by marcaaron** [comment] 2022-07-12 00:56
Tried to update a room then looked to see if this rNVP is returning with my accountID and it is not there. Even though the request returned 200

![2022-07-11_14-55-12](https://user-images.githubusercontent.com/32969087/178385076-c210ba10-6fb2-4e89-8bf2-f3a754d4dd5d.png)

So something weird is happening on the API side.

**Comment by marcaaron** [comment] 2022-07-12 00:58
Here, we are calling setNVP() after returning the onyx data and need to do it before... 

https://github.com/Expensify/Web-Expensify/blob/84be775cff58ca3a32dc3d504093cd462fc2a54a/lib/ReportAPI.php#L3553-L3562

**Comment by marcochavezf** [comment] 2022-07-12 20:07
I will continue with this issue after https://github.com/Expensify/Web-Expensify/pull/34260 is merged (more context in this [comment](https://github.com/Expensify/Web-Expensify/pull/34260#discussion_r919199871)).

**Comment by marcochavezf** [comment] 2022-07-15 00:51
The error seems to be fixed on https://github.com/Expensify/Web-Expensify/pull/34260, I can't reproduce it anymore.

**Closed by marcochavezf** 2022-07-15 00:51 UTC
Labels: Engineering, Daily
