### ISSUE TITLE
[$1000] Request money - Tabs jump back and forth when swiping through tabs

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26407] opened 2023-08-31 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26022
## Action Performed:
1. Go to staging.new.expensify,com
2. Go to + > Request money
3. Swipe through the tabs in Request money page

Note: I believe the key to reproduce the issue is to swipe to another tab before the animation has finished.

## Expected Result:
The tab does not jump back and forth

## Actual Result:
The tab jumps from Scan > Distance > Scan > Manual when swiping from Scan to Manual

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5f15b93f-6798-468f-bd7c-a86498b96108

https://github.com/Expensify/App/assets/78819774/3dfc6ec2-e1d4-44dc-944e-39a9d7144bba

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015402cabc0571ff40</li>
        <li>Upwork Job ID: 1697381434343821312</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-08-31 15:53
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request money - Tabs jump back and forth when swiping through tabs.
### What is the root cause of that problem?
The underlying reason for this behavior stems from the asynchronous nature of how the `selectedTab` and `setSelectedTab` are derived from the OnyxDB. This asynchronicity is leading to the erratic behavior observed during tab swiping.

https://github.com/Expensify/App/blob/main/src/libs/Navigation/OnyxTabNavigator.js

### What changes do you think we should make in order to solve the problem?
To resolve this issue, it is proposed that we incorporate the use of the `useRef` hook. This can be achieved by maintaining the `selectedTab` value within a `useRef` and accessing it via the `selectedTab.current`. Subsequently, upon component mounting and unmounting, the `setSelectedTab` function can be employed to store the value into the Onyx database.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by b4s36t4** [comment] 2023-08-31 16:11
@hannojg maybe you've worked on it? after the patch with `material tab view` patch?

**Comment by aldo-expensify** [comment] 2023-08-31 21:09
@Pluto0104 

Thanks for the proposal: https://github.com/Expensify/App/issues/26407#issuecomment-1701303819

I'm trying it, but I still see the bug. I did this:

<img width="1190" alt="image" src="https://github.com/Expensify/App/assets/87341702/aed3aa49-5043-433a-8c13-0b28eaa2a6eb">

This makes me thing that there may be a bug in the external library, but I haven't been able to test that.

**Comment by aldo-expensify** [comment] 2023-08-31 21:11
Lol, this is very broken in production, much worse than this:


https://github.com/Expensify/App/assets/87341702/0e304493-eef5-4a3e-b5bf-bc507c9bbce3

Considering that, I think we should remove the `DeployBlocker` label and investigate with lower priority

**Comment by luacmartins** [comment] 2023-08-31 21:14
Agree this is not a blocker since it happens in production too!

**Comment by s77rt** [comment] 2023-09-01 17:02
@Pluto0104 Thanks for the proposal. I don't think your RCA is correct, onyx does not seem to be the root cause here.

**Comment by b4s36t4** [comment] 2023-09-01 17:17
Can anyone help me with re-production steps here? Do we need to use the swipe or clicks on tabs?

**Comment by Pluto0104** [comment] 2023-09-01 17:26
@s77rt I have already seen @aldo-expensify's explanation. it may be caused by module issue.

**Comment by aldo-expensify** [comment] 2023-09-01 17:40
> Can anyone help me with re-production steps here? Do we need to use the swipe or clicks on tabs?

@b4s36t4 

You need to swipe, no clicking. It is reproducible using Chrome with dev tools open to simulate a small screen.
Steps:
1. Start in tab 1 (Manual)
2. Swipe left to move to tab 2 (Scan)
3. Before the animation has completed, swipe right to go back to tab 1 (Manual)

**Result:**

- Tab 3 (Distance) becomes briefly active and you also see briefly the map.

https://github.com/Expensify/App/assets/87341702/972d58f0-39f3-49ba-994f-cdf805666e2d




**Expected Result:**

- Should have moved back to Tab 1 without seeing the content of tab 3 or highlighting tab 3

**Comment by s77rt** [comment] 2023-09-04 11:28
Not overdue. Waiting for proposals

**Comment by napster125** [comment] 2023-09-05 20:55
@aldo-expensify @s77rt, currently, this issue might be related to the 'react-native-tab-view' module. I have tested the module and it seems to be causing this error. Since I haven't encountered this condition before, should we consider patching the module? Could you please provide your input on this matter? Thank you!

**Comment by s77rt** [comment] 2023-09-05 20:59
@napster125 If the bug is upstream, then yeah we should fix it upstream. Patching is the least option, we should try to raise a PR fixing the bug if possible.

**Comment by napster125** [comment] 2023-09-05 21:01
@s77rt, I have a potential solution, but it appears to be more of a workaround. I'm uncertain if it's suitable for this situation.

**Comment by s77rt** [comment] 2023-09-05 21:35
@napster125 Feel free to post the proposal but please focus on the root cause not the solution. Workarounds are mostly discouraged.

**Comment by napster125** [comment] 2023-09-05 21:37
@s77rt is it good solution for us to prevent fast swiping?

**Comment by s77rt** [comment] 2023-09-05 21:47
@napster125 Like using a debouncer? I don't think so but it all comes to the root cause

**Comment by napster125** [comment] 2023-09-05 21:57
Same here, that's why I can't post the proposal.

**Comment by aldo-expensify** [comment] 2023-09-05 22:17
I think that blocking swiping until the animation/navigation finishes is a last resource because it leads to a worse experience where you have to wait to swipe again, maybe it is even better to have the bug compared to blocking the swiping.

**Comment by s77rt** [comment] 2023-09-11 11:03
Not overdue. Looking for proposals

**Comment by Pluto0104** [comment] 2023-09-14 16:26
I think it's not an easy problem. we should patch the react navigation library.

**Comment by s77rt** [comment] 2023-09-14 20:34
Not overdue. Still looking for proposals

**Comment by aldo-expensify** [comment] 2023-09-18 09:59
> I think it's not an easy problem. we should patch the react navigation library.

Yes, I was just able to confirm that this is a problem with the library by reproducing it in their sample: https://snack.expo.dev/?platform=web


https://github.com/Expensify/App/assets/87341702/e96e202f-3d3a-4911-8bf1-3b7d67aef188

**Comment by s77rt** [comment] 2023-09-20 20:49
Not overdue. Looking for proposals

**Comment by mvtglobally** [comment] 2023-09-21 03:35
Issue not reproducible during KI retests. (First week)

**Comment by s77rt** [comment] 2023-09-21 15:49
Still looking for proposals Melvin

**Comment by greg-schroeder** [comment] 2023-09-25 07:20
I will double bounty I guess considering no proposals have been found

**Comment by devrari** [comment] 2023-09-25 19:51
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request money - Tabs jump back and forth when swiping through tabs
### What is the root cause of that problem?
This is the issue with stack navigator from react navigation. It make use of poptotop method to  navigate to tab, when the animation  is enabled, it  will  cause the error in case we move from tab 1 to tab 3 ,  either by swiping or by clicking directly to 3rd tab.

### What changes do you think we should make in order to solve the problem?
Since this might require patching the react navigation library , one solution we have is to disable the animation in MoneyRequestSelectorPage.js .
Pass below screenOptions to  OnyxTabNavigator  in  MoneyRequestSelectorPage
```
       screenOptions={{animationEnabled: false}}
```    
### What alternative solutions did you explore?
None

### Video  after animation is disabled

https://github.com/Expensify/App/assets/4333876/6f4a6d36-7ac4-44a1-9259-32f3f94af629

**Comment by s77rt** [comment] 2023-09-25 20:50
@devrari Thanks for the proposal. Although the issue seems related to animation, I don't think disabling it is the way to go. This is more like a workaround.

**Comment by devrari** [comment] 2023-09-26 04:10
@s77rt  ,  yeah the  actually  solution might require  to patch  react navigation itself,  because  of  which I  suggested  this. 
and moreover  I didn't see much difference  with  and without  animation.

**Comment by mvtglobally** [comment] 2023-09-28 03:24
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment] 2023-09-28 07:33
Still looking for proposals. Although now QA is saying not reproducible? hmmm

**Comment by aldo-expensify** [comment] 2023-09-28 07:46
> Although now QA is saying not reproducible?

I just reproduced it. They are not probably following well the steps:
1. Swipe from "Manual" to "Scan"
2. Swipe back to "Manual" before the animation has completely finished

**Comment by aldo-expensify** [comment] 2023-10-02 13:09
I think we should just start by reporting this in `react-native-tab-view`'s repo

**Comment by s77rt** [comment] 2023-11-02 14:41
@aldo-expensify Should this be set back External?

**Comment by aldo-expensify** [comment] 2023-11-08 01:08
I found that this was reported on Oct 2021 in the external library repo: https://github.com/react-navigation/react-navigation/issues/10072

I don't think this will be fixed anytime soon in the library code. What would be the next step? Should we just close this issue? I think we should close it because I see it as a pretty minor thing (low ROI) and could be quite complex to fix.

**Comment by greg-schroeder** [comment] 2023-11-09 11:31
All right - thanks Aldo. I'll close this then.

**Closed by greg-schroeder** 2023-11-09 11:31 UTC
Labels: External, Engineering, Monthly, Help Wanted, Bug
