### ISSUE TITLE
[HOLD for payment 2022-09-01] [$250] Whitespace on screen where keyboard used to be

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10188] opened 2022-08-02 05:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Press on the composer (open keyboard)
3. Put the app in the background
4. Open again with the keyboard open
5. Press back immediately
6. You should see the bottom space same as the keyboard height 

## Expected Result:
No white space should display 

## Actual Result:
Whitespace on screen where keyboard used to be

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Image from iOS (18)](https://user-images.githubusercontent.com/43995119/182299740-cbc939b7-b90c-4a64-9ed4-17c6ab12fd63.png)

**Upwork URL:** https://www.upwork.com/jobs/~012bd08b740a4f2ffa
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659026555000119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-08-02 23:00
Not sure if we have bulletproof reproduction steps here. We should try to nail that down a bit before making this external, imo.

**Comment by roryabraham** [comment] 2022-08-02 23:01
I've definitely seen this happen a number of times in the wild on a physical device though

**Comment by luacmartins** [comment] 2022-08-02 23:39
Agreed! I'll try to reproduce this some time this week

**Comment by dhairyasenjaliya** [comment] 2022-08-03 08:31
I actually have this issue thought it was some local issue so didn't report it on slack, but it seems to be a real issue

**Steps to reproduce** 

1. Open any chat
2. Press on the composer (open keyboard)
3. Put the app in the background
4. Open again with the keyboard open
5. Press back immediately 
6. You should see the bottom space same as the keyboard height 


https://user-images.githubusercontent.com/47522946/182562239-020d5015-5a9f-40c2-8971-ed83dec43c85.mp4

**Comment by luacmartins** [comment] 2022-08-03 15:57
Hmm I can't reproduce this on the latest main (1.1.87-8) or staging (1.1.86-5). We reverted [this PR](https://github.com/Expensify/App/pull/10113) which was causing a lot of similar issues and that was deployed in v1.1.86-2. Is this still happening on v1.1.86-2 or higher (this issue mentions 1.1.86-0)?

**Comment by dhairyasenjaliya** [comment] 2022-08-03 16:17
@luacmartins I can reproduce in latest code 1.1.87-8

**Comment by luacmartins** [comment] 2022-08-04 15:00
@dhairyasenjaliya I tried your steps above, while I couldn't repro on dev, I did see the behavior on a physical device on staging. The one caveat is that the white space goes away after a little bit. The events are something like:

1. Open chat and focus on the compose box (keyboard will open)
2. Navigate away from chat (keyboard closes), but whitespace remains
3. Whitespace animates away after a few seconds

So something seems to be blocking the JS thread and making the UI hang. I'll apply the external label!

**Comment by trjExpensify** [comment] 2022-08-04 21:14
I'm unable to attempt to reproduce this because I'm suffering some serious issues on iOS at the moment (being looked at elsewhere). 

The action steps in the OP are pretty light, I'm going to update them to @dhairyasenjaliya ones from here: 

> 1. Open any chat
> 2. Press on the composer (open keyboard)
> 3. Put the app in the background
> 4. Open again with the keyboard open
> 5. Press back immediately
> 6. You should see the bottom space same as the keyboard height

**Comment by trjExpensify** [comment] 2022-08-04 21:19
Job on upwork here: https://www.upwork.com/jobs/~012bd08b740a4f2ffa

**Comment by trjExpensify** [comment] 2022-08-04 21:20
Hm, why did @ctkochan22 also get assigned here?

**Comment by dhairyasenjaliya** [comment] 2022-08-05 08:46
**Proposal**

**Root Cause**

- Here on the `SidebarLinks.js` page we have added one package (component) `<KeyboardSpacer />` that is actually cause for this issue

- When we follow about steps to reproduce the issue, Here what happens is once we are on `SidebarLinks.js`  `<KeyboardSpacer />` this package does add one listener that mainly indicates keyboard status along with its height based on the status it adds height view in `SidebarLinks.js` here when we go to any chat and minimize the app and open again then we navigate back from chat screen along with keyboard open sometime's the height view gets delay to reset most probably we are updating data that call multiple API I believe it blocks for few seconds that makes a delay to reset the view

**Solution**

- Main aim for `<KeyboardSpacer />`  is to add a view with keyboard height in order to avoid text input hiding behind a keyboard but since there is no text input `SidebarLinks.js` so we need to remove and this issue will be resolved 

- Removing the `<KeyboardSpacer />` does not affect any other platform since currently it's only configured for iOS (app)

- Remove this component 

https://github.com/Expensify/App/blob/ba5a38f4a8f8eca2fdc63eb2b45aaccc85fe7997/src/pages/home/sidebar/SidebarLinks.js#L319



- **Here is my current PR referring to another issue** https://github.com/Expensify/App/pull/10162 we are removing `<KeyboardSpacer />` from `SidebarLinks.js` which will resolve this issue as well 



- **Note**: This is a very edgy case I tried 12-15 times in order to reproduce this issue

**Result (With Removed `<KeyboardSpacer />`)**

https://user-images.githubusercontent.com/47522946/183033977-067ac049-caf5-4244-a443-0c08aa5a9731.mp4

**Result (Without Removing `<KeyboardSpacer />` current behavior)**

https://user-images.githubusercontent.com/47522946/183033996-722ff608-96ce-4797-aa01-05aae4b93ccd.mov

**Comment by mountiny** [comment] 2022-08-05 09:13
I can take this on as CME 🙇 seems like the issue I worked on with @dhairyasenjaliya has similar cause and his PR which was linked csn fix this too.

**Comment by trjExpensify** [comment] 2022-08-05 09:42
>seems like the issue I worked on with @dhairyasenjaliya has similar cause and his PR which was linked csn fix this too.

Oh, so this should be fixed elsewhere you mean?

**Comment by mountiny** [comment] 2022-08-05 11:38
> Oh, so this should be fixed elsewhere you mean?

Based on @dhairyasenjaliya proposal it seems like removing the KeyboardSpacer as he tried in [this PR](https://github.com/Expensify/App/pull/10162) worked.

This issue is valid, not a duplicate though if that is what you asked for.

**Comment by mountiny** [comment] 2022-08-05 11:38
@rushatgabhane What do you think of the proposal?

**Comment by mountiny** [comment] 2022-08-05 11:58
> So I don't see why we shouldn't go with their proposal.

I was able to reproduce multiple times (it is really annoying) 😄 

Thank you!

**Comment by trjExpensify** [comment] 2022-08-05 12:23
Cool, @dhairyasenjaliya let me know when you've applied on Upwork!

**Comment by dhairyasenjaliya** [comment] 2022-08-05 12:25
@trjExpensify I can't access Upwork link maybe set to private

**Comment by dhairyasenjaliya** [comment] 2022-08-05 12:27
hm @trjExpensify can't apply links seems to private

**Comment by trjExpensify** [comment] 2022-08-05 12:28
Interesting.. I wonder why that is. Can you try this link? https://www.upwork.com/jobs/~012bd08b740a4f2ffa

**Comment by dhairyasenjaliya** [comment] 2022-08-05 12:29
@trjExpensify latest one works applying now thank you :)

**Comment by dhairyasenjaliya** [comment] 2022-08-05 12:30
@trjExpensify still I can't apply 
Only invited users can find, view and apply to the job

**Comment by trjExpensify** [comment] 2022-08-05 12:32
Ah yeah okay, so that setting was invited users only. Changed it and it should be good now.

**Comment by dhairyasenjaliya** [comment] 2022-08-05 12:37
applied thank you :) 
@trjExpensify

**Comment by trjExpensify** [comment] 2022-08-18 11:55
👋 Where are we at on [the PR](https://github.com/Expensify/App/pull/10162#issuecomment-1216749084). Have we completed the retests?

**Comment by luacmartins** [comment] 2022-08-18 16:11
No updates on the retests. @mountiny asked for one not too long ago.

**Comment by dhairyasenjaliya** [comment] 2022-09-05 03:28
hello @trjExpensify can we close this one as this is in production

**Comment by trjExpensify** [comment] 2022-09-05 13:08
Yep, paid @dhairyasenjaliya. Rushat, I need you to accept the offer for C+.

**Comment by trjExpensify** [comment] 2022-09-05 13:16
Kewl, paid @rushatgabhane now as well. Closing it out!

**Closed by trjExpensify** 2022-09-05 13:16 UTC
Labels: Reviewing, Exported, External, Engineering, Daily, Awaiting Payment
