### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Web -  Workspace - Unable to navigate the invite list by using the arrow keys

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41906] opened 2024-05-09 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create workspace
2. Go to Members> Invite member
3. In the invite members use the keyboard arrow keys
5. Go back to Members page
6. Go to Invite member
7. Try to use the keyboard arrow keys

## Expected Result:
User should navigate the list by using the arrow keys every time Invite new members page open

## Actual Result:
User is not able to navigate the invite list by using the arrow keys when open Invite new members page

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/553645be-01cc-4e53-b8a8-6a9576ba0fc2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015abf6304380bd09f</li>
        <li>Upwork Job ID: 1790448510304206848</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 102482440</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by kbecciv** [comment] 2024-05-09 13:02
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by alexpensify** [comment] 2024-05-10 22:54
On my testing list, I'll get to it soon.

**Comment by alexpensify** [comment] 2024-05-13 22:10
I wasn't able to get to this one over the weekend, still on my radar.

**Comment by alexpensify** [comment] 2024-05-14 18:26
I confirmed that this is an issue and couldn't find another duplicate of this issue. We need proposals here.

**Comment by alexpensify** [comment] 2024-05-16 15:29
@abdulrahuman5196 - can you please confirm if the proposal above will fix this issue? Thanks!

**Comment by abdulrahuman5196** [comment] 2024-05-16 17:27
Hi I will check on this in my morning.

**Comment by Christinadobrzyn** [comment] 2024-05-21 05:15
@abdulrahuman5196 can you take a peek at the above [proposal](https://github.com/Expensify/App/issues/41906#issuecomment-2103257894)? or let me know if should reach out to SWM to see if someone might be able to grab this! TY!

**Comment by abdulrahuman5196** [comment] 2024-05-22 19:48
Checking now

**Comment by abdulrahuman5196** [comment] 2024-05-22 19:58
@dragnoir 's proposal here https://github.com/Expensify/App/issues/41906#issuecomment-2103257894 looks good and works well. Even other keyboard hooks use the same way in BaseSelectionList.

🎀 👀 🎀
C+ Reviewed

**Comment by Christinadobrzyn** [comment] 2024-05-24 03:19
@luacmartins can you take a peek at this review? https://github.com/Expensify/App/issues/41906#issuecomment-2125644638

Thank you!

**Comment by luacmartins** [comment] 2024-05-27 14:57
Sorry, was ooo for the last few days. I agree that @dragnoir's proposal looks good.

**Comment by alexpensify** [comment] 2024-05-28 19:32
Thanks, @Christinadobrzyn, for the help here. I'm back online and taking over again as the BZ member here.

**Comment by alexpensify** [comment] 2024-05-30 23:14
Update: The PR is ready for review

**Comment by alexpensify** [comment] 2024-06-05 22:44
Weekly Update: The PR is waiting to go to Production

**Comment by alexpensify** [comment] 2024-06-12 23:29
Okay, we are ready to pay via Upwork tomorrow. @dragnoir, I had to manually send an Upwork offer. Please accept, and I can complete the process tomorrow. Thanks!

**Comment by alexpensify** [comment] 2024-06-13 21:45
### Paid via Upwork! 

Payouts due: 2024-06-13

- [ ] Contributor: $250 @dragnoir 
- [ ] Contributor+: $250 @abdulrahuman5196 

Upwork job is [here](https://www.upwork.com/jobs/~015abf6304380bd09f).

**Closed by alexpensify** 2024-06-13 21:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
