### ISSUE TITLE
[$500]  Name Field - There is a character limit error in personal name but not in teachers name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31873] opened 2023-11-26 00:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Settings > Profile > Personal Details
2. Click on the Legal name
3. Enter a long name that has more than 40 characters
Notice that an error is shown. And the maximum limit is 40 Characters
4. Go back to the main page
5. Click on FAB > Save the world > I know a teacher
6. Enter a long name in the first name. Notice that an error is not shown and the maximum limit is 50 Characters

## Expected Result:
Consistency in the maximum characters allowed and also displaying errors

## Actual Result:
Inconsistency in the maximum characters allowed and displaying errors

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/760e2d2a-6420-4ac3-b939-4d333b1b95cb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c40e0f7c1e9d7d70</li>
        <li>Upwork Job ID: 1728570246199914496</li>
        <li>Last Price Increase: 2023-11-26</li>
    </ul>
</details>

**Comment by giltron** [comment] 2023-11-26 01:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The input field for the business name can be of any length and is beyond reasonable.  
(over 1600 characters in the example which is beyond what a legal business name could be)

### What is the root cause of that problem?

[InputWrapper in CompanyStep]
(https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/ReimbursementAccount/CompanyStep.js#L165)

has no input character limit. 

### What changes do you think we should make in order to solve the problem

Set a reasonable maximum limit with the InputWrapper in CompanyStep.  This value should go in  CONST.ts with the explanation on the limit (ie. 40)

```
<InputWrapper
                    InputComponent={TextInput}
                    label={translate('companyStep.legalBusinessName')}
                    accessibilityLabel={translate('companyStep.legalBusinessName')}
                    role={CONST.ACCESSIBILITY_ROLE.TEXT}
                    inputID="companyName"
                    containerStyles={[styles.mt4]}
                    disabled={shouldDisableCompanyName}
                    maxLength={CONST.MAX_BUSINESS_NAME_LENGTH}
                    defaultValue={getDefaultStateForField('companyName')}
                    shouldSaveDraft
                    shouldUseDefaultValue={shouldDisableCompanyName}
                />
```



### What alternative solutions did you explore? (Optional)

**Comment by jaimishg2098** [comment] 2023-11-26 03:47
### Proposal

**What is the problem?**
In below file there is problem in validation function

[https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/TeachersUnite/KnowATeacherPage.js#L121C25-L121C66](https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/TeachersUnite/KnowATeacherPage.js#L121C25-L121C66)

We need to add length validation condition in [src/pages/TeachersUnite/KnowATeacherPage.js] 

We don't need to change any CONST variable

**Comment by jaimishg2098** [comment] 2023-11-26 03:49
Contributor details
Your Expensify account email: Golakiyajaimish20@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/golakiyajaimish

**Comment by kenny-luk** [comment] 2023-11-26 04:11
### Please re-state the problem that we are trying to solve in this issue.
The defined input length maximums for legal name and the teacher name are inconsistent.

### What is the root cause of that problem?
On the legal name page, the validation of `firstName` - limit by 40 characters is done here:
![image](https://github.com/Expensify/App/assets/151805841/48a23c4f-bcf6-4e91-ba30-460ce8727317)

https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L64

And the actual allowed max length of this `firstName` is done here. Note that we can't input more than 540 characters here. (limited by 40 + 500 = 540):
![image](https://github.com/Expensify/App/assets/151805841/cae809bb-14e3-41c1-a6fc-51f17f775d9c)
https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L109

On the other hand, on the KnowATeacherPage we don't have length validation here for the firstName:
https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/TeachersUnite/KnowATeacherPage.js#L70-L74

That's why we don't see any length validation here.

But we have max length limit of 50 for the `firstName` here:
![image](https://github.com/Expensify/App/assets/151805841/95e0801f-5ce5-4382-b953-c5f0ff09e2fb)

https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/TeachersUnite/KnowATeacherPage.js#L121

### What changes do you think we should make in order to solve the problem?

To make it consistence, we should set same validation and max length for both pages. Make it both 40 or 50.
And we should set same max length for both pages too.

### What alternative solutions did you explore? (Optional)

**Comment by codeweb05** [comment] 2023-11-26 10:41
Contributor details
Your Expensify account email: sj40863@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0156b9266f895d8ff3

**Comment by codeweb05** [comment] 2023-11-26 10:49
Proposal 

The problem can be solved by fixing the validation logic in  [src/pages/TeachersUnite/KnowATeacherPage.js]

**Comment by NICK-XoX** [comment] 2023-11-26 21:29
Contributor details
Your Expensify account email: [nick@starxox.com](mailto:nick@starxox.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d42bc0d03cedf157

**Comment by NICK-XoX** [comment] 2023-11-26 21:30
Contributor details
Your Expensify account email: nick@starxox.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d42bc0d03cedf157

**Comment by strepanier03** [comment] 2023-11-28 21:09
This may be relevant - https://github.com/Expensify/App/pull/31876

**Comment by rushatgabhane** [comment] 2023-11-29 07:50
I'm sorry, why is this a bug?

**Comment by rushatgabhane** [comment] 2023-11-29 07:53
i think we should do nothing

**Comment by strepanier03** [comment] 2023-12-01 22:34
Sounds good to me, closing out!

**Closed by strepanier03** 2023-12-01 22:34 UTC
Labels: External, Daily, Help Wanted, Bug
