### ISSUE TITLE
[$250] High:Chats don’t load when logging in using Google SSO from public room banner.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41246] opened 2024-04-29 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714391455919649

## Action Performed:

1. Go to staging on Chrome - log out if you need to
2. Access public room - https://staging.new.expensify.com/r/2376199970894587
3. Navigate to the self DM that populates in LHN
4. Click ‘Sign in’ in the banner
5. Sign in w/ Google
## Expected Result:
Your signed in profile’s chats load
## Actual Result:
No additional chats load, ‘Hmm…’ flashes
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/Expensify/App/assets/38435837/faf8e560-0869-4fd9-b9ab-f7ac8ed5156a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140408c8876b6a1dd</li>
        <li>Upwork Job ID: 1785085627943718912</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nitinigi2** [comment] 2024-04-30 11:10
Just add a page reload once user's SSO signIn is done. That will do the job.

**Comment by lschurr** [comment] 2024-05-02 21:04
Hi @alitoshmatov - Can you take a looksie at this one?

**Comment by alitoshmatov** [comment] 2024-05-05 17:03
Reproduced, couldn't find root cause yet

**Comment by lschurr** [comment] 2024-05-08 16:08
Any update @alitoshmatov? Are we just waiting for proposals?

**Comment by alitoshmatov** [comment] 2024-05-08 18:55
Yes waiting for proposals here

**Comment by lschurr** [comment] 2024-05-10 21:26
Still waiting on proposals.

**Comment by lschurr** [comment] 2024-05-13 15:27
Still waiting on proposals.

**Comment by rezkiy37** [comment] 2024-05-15 11:41
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-05-15 13:13
Hey!
I confirm that the bug is replicable. Moreover, the bug repeats for Apple SSO as well. 

I've investigated data that the app gets from the backend for the `SignInWithGoogle` and `SignInWithApple` commands. Actually, there is a huge difference between responses for `SigninUser` and SSO. The backend does not return reports and many other data. 

<details><summary>Details</summary>
<p>

<img width="867" alt="Screenshot 2024-05-15 at 14 47 00" src="https://github.com/Expensify/App/assets/57314631/85021870-db69-420a-aa9a-09f25cf2a5b3">
<img width="1728" alt="Screenshot 2024-05-15 at 14 48 11" src="https://github.com/Expensify/App/assets/57314631/e8c26ce9-63cd-4c14-ad95-2ccb603e33b6">
<img width="1728" alt="Screenshot 2024-05-15 at 14 51 47" src="https://github.com/Expensify/App/assets/57314631/025f3801-c143-41e9-9b46-09a17e48cd24">


</p>
</details> 

There are 2 obvious solutions:
1. Sync responses for all kinds of authorization and send the same data.
2. For the SSO authorizations, the app can call `OpenApp` or `ReconnectApp` right after the authorization has happened.

I read [contributingGuides/APPLE_GOOGLE_SIGNIN.md](https://github.com/Expensify/App/blob/main/contributingGuides/APPLE_GOOGLE_SIGNIN.md). I've not found any info that this type of authorization omits some data to send to the app. Also, it requires some additional configs to test the development mode due to the SSO restrictions. However, it is not required here, because I assume the bug should be fixed on the backend side. 

So we need an internal engineer to help with the issue.

**Comment by lschurr** [comment] 2024-05-16 15:20
@alitoshmatov - what do you think?

**Comment by lschurr** [comment] 2024-05-20 14:47
@rezkiy37 @alitoshmatov - Do we also need to make this internal?

**Comment by alitoshmatov** [comment] 2024-05-21 20:08
Sorry for late response. 

Yes we need internal engineer here based on @rezkiy37 [observation](https://github.com/Expensify/App/issues/41246#issuecomment-2112485692)

**Comment by lschurr** [comment] 2024-05-24 21:35
Added Internal here to find an engineer to work on this.

**Comment by lschurr** [comment] 2024-05-27 18:11
No update on this one.

**Comment by lschurr** [comment] 2024-05-30 15:58
Asked in Slack - https://expensify.slack.com/archives/C066HJM2CAZ/p1717084703979449

**Comment by lschurr** [comment] 2024-06-03 15:07
Bumped the Slack thread.

**Comment by lschurr** [comment] 2024-06-05 19:23
No update.

**Comment by lschurr** [comment] 2024-06-10 21:25
Still don't have an internal eng volunteer.

**Comment by lschurr** [comment] 2024-06-13 15:37
Asking in newdot-quality: https://expensify.slack.com/archives/C05LX9D6E07/p1718293036755239

**Comment by alitoshmatov** [comment] 2024-06-13 17:24
@rezkiy37 It has been a while but can you take a look at it again: reports data is being received with `openApp` request, any idea why it is not being applied?

<img width="884" alt="Screenshot 2024-06-13 at 10 22 49 PM" src="https://github.com/Expensify/App/assets/59907218/f8d0ce65-925f-4d21-8c36-df4e402c0346">

**Comment by rezkiy37** [comment] 2024-06-14 17:12
Yes, I can confirm that the bug no longer exists.

<details><summary>Details</summary>
<p>


https://github.com/Expensify/App/assets/57314631/6e3144c7-7005-46b9-a972-8ac43e162e5b


https://github.com/Expensify/App/assets/57314631/badc98d8-f607-42e9-a211-637ba5800ee9



</p>
</details> 

cc @lschurr

**Comment by lschurr** [comment] 2024-06-17 15:34
Ah, perfect thanks! Closing.

**Closed by lschurr** 2024-06-17 15:34 UTC
Labels: Daily, Internal, Overdue, Bug, Hot Pick

**Comment by alitoshmatov** [comment] 2024-06-18 10:52
@rezkiy37 I think you missed couple of steps to reproduce. It is still reproducible for me. I was just sharing my finding [here](https://github.com/Expensify/App/issues/41246#issuecomment-2166387337)


https://github.com/Expensify/App/assets/59907218/4bf97842-dc40-402b-bcc6-b24bf1bbbe8b

cc: @lschurr

**Comment by rezkiy37** [comment] 2024-06-18 11:37
Ah, exactly. My bad. Let's reopen the issue. Seems like the app should call **OpenApp** for this scenario.

**Comment by rezkiy37** [comment] 2024-06-18 15:10
I've found out why the app does not show much data alongside reports. 

The app calls **OpenApp** right after **Google** or **Apple** authorization. However, the app initially calls **ReconnectApp**. It sets `lastUpdateID` from the very beginning. It is `438474121` in my case. The **OpenApp** response has `lastUpdateID` as well. It is `438465717`.

<details><summary>Screenshoots</summary>

<img width="1168" alt="Screenshot 2024-06-18 at 16 52 33" src="https://github.com/Expensify/App/assets/57314631/b3205e67-bdff-44cd-a215-0d041fde5fbc">
<img width="1037" alt="Screenshot 2024-06-18 at 16 52 58" src="https://github.com/Expensify/App/assets/57314631/826251f1-deaa-4dc4-b283-872fc12e0e14">


</details> 

There is a condition in how the app checks whether it should apply new coming onyx data. It compares the current `lastUpdateID` with the last one.

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/libs/actions/OnyxUpdates.ts#L101

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/libs/actions/OnyxUpdates.ts#L115-L116

As we can see above, if there was an update with greater `lastUpdateID`, the app omits onyxData.

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/libs/actions/OnyxUpdates.ts#L104-L105

Therefore we can see that the **OpenApp's** `lastUpdateID` is less when **ReconnectApp's** `lastUpdateID`.

```typescript
438465717 < 438474121 // true
``` 

The app does not take Onyx data into account.

Regarding this comment - https://github.com/Expensify/App/issues/41246#issuecomment-2168447420. I tested with the primary login page. The app does not call **ReconnectApp** from the very beginning on the login page. That's why the app applies **OpenApp's** Onyx data.

Please re-open the issue 🙂 

cc @alitoshmatov @lschurr

**Comment by alitoshmatov** [comment] 2024-06-19 09:53
Thank you @rezkiy37 for pretty in-depth explanation 👍, that makes sense. @lschurr Looks like we do need internal engineer after all, since we have problem with backend response.

**Comment by lschurr** [comment] 2024-06-21 19:34
Bumped the Slack thread - https://expensify.slack.com/archives/C05LX9D6E07/p1718293036755239

**Comment by rezkiy37** [comment] 2024-06-26 11:36
@flodnv, because it requires changes on the backend side.

**Comment by flodnv** [comment] 2024-06-26 12:33
Right, I read your comment 3 times and I'm sorry but I still don't understand which change we need on the backend side. If you had access to the backend code, what change would you make? Or maybe you can present this in a Problem/Solution form so I can understand better?

**Comment by alitoshmatov** [comment] 2024-06-27 20:34
@flodnv I think the main issue we are struggling [here](https://github.com/Expensify/App/issues/41246#issuecomment-2176347102) is that even though `reconnectApp` is called first it is getting higher `lastUpdateID` then `openApp` request which is called after this and its changes are not applied due to its lower `lastUpdateID`. These `lastUpdateID`s are issued from backend. I think naturally request order should also reflect `lastUpdateID`. 

Maybe there is a race condition going on?

**Comment by flodnv** [comment] 2024-07-01 12:21
Okay, thanks for the (re)explanation, I can look into that. My first step is obviously to reproduce myself.

>Go to staging on Chrome - log out if you need to
>Access public room - [staging.new.expensify.com/r/2376199970894587](https://staging.new.expensify.com/r/2376199970894587)
>Navigate to the self DM that populates in LHN

Note: I don't see a self DM.

>Click ‘Sign in’ in the banner
>Sign in w/ Google

I was able to reproduce though. 

@rezkiy37 @alitoshmatov do we call the same set of APIs (in the same order) from the App when signing in via Google as when signing in via magic code in this specific flow? It's surprising to me that this bug only exists on Google Signin.

**Comment by flodnv** [comment] 2024-07-01 13:26
>the app initially calls ReconnectApp

I tested a few times watching the network console and I do not see a call to ReconnectApp

<details><summary>Screenshot</summary>
<p>

<img width="665" alt="image" src="https://github.com/Expensify/App/assets/4164921/b6297a55-bf26-4174-a4ad-b8865a8f34b4">


</p>
</details> 

However, I do see 2 calls to OpenApp. @rezkiy37 @alitoshmatov what are your thoughts?

**Comment by rezkiy37** [comment] 2024-07-01 15:51
@flodnv, it does call **ReconnectApp** for me on the dev, but it does not call on the staging. So I tried to test the staging and what I found. There is an **OpenReport** response that has the same `lastUpdateID` as **OpenApp** has. This **OpenReport** has been called before and sets its own `lastUpdateID`. The next **OpenApp** is skipped due to the condition:

https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/libs/actions/OnyxUpdates.ts#L101

<details><summary>Screenshots</summary>

<img width="1728" alt="Screenshot 2024-07-01 at 17 45 24" src="https://github.com/Expensify/App/assets/57314631/d3fec7b0-56d6-425f-bcf8-75155d02312b">

<img width="1073" alt="Screenshot 2024-07-01 at 17 45 54" src="https://github.com/Expensify/App/assets/57314631/d06f6d1a-959c-46e4-84f1-86bd28cf07f3">

<img width="1091" alt="Screenshot 2024-07-01 at 17 46 11" src="https://github.com/Expensify/App/assets/57314631/db6191ee-ffef-4663-b091-357a5e5f4c7a">

</details> 

Does it make sense now?

**Comment by lschurr** [comment] 2024-07-03 19:10
Any update here @alitoshmatov @flodnv?

**Comment by lschurr** [comment] 2024-07-08 01:56
Just bumping again for an update @alitoshmatov @flodnv :)

**Comment by flodnv** [comment] 2024-07-09 10:32
No update, I'm focused on more important tasks.

**Comment by alitoshmatov** [comment] 2024-07-09 19:27
I don't have anything to add to @rezkiy37 's findings

**Comment by rezkiy37** [comment] 2024-07-10 12:11
Hello!
FYI: I have a vacation from 11.07 to 26.07. Meanwhile, someone from Callstack can help with this issue.

**Comment by muttmuure** [comment] 2024-07-11 11:49
If Flo is working on #fast-apis then let's ask someone else to work on this internally

**Comment by lschurr** [comment] 2024-07-15 14:48
Hey @jasperhuangg - let me know if this is something you have the space to pick up. Thanks!

**Comment by jasperhuangg** [comment] 2024-07-15 18:02
Hmm my plate is pretty full at the moment, sorry!

**Comment by lschurr** [comment] 2024-07-17 19:06
Talking in the original Slack thread - Still trying to get an engineer assigned. https://expensify.slack.com/archives/C049HHMV9SM/p1714391455919649

**Comment by cristipaval** [comment] 2024-07-22 10:37
I'll look into this one today.

**Comment by garrettmknight** [comment] 2024-07-23 13:49
I can't reproduce this anymore - the original link to the public room is on a deleted workspace so I used a new public room.

1. Go to staging on Chrome - log out if you need to
2. Access public room - https://staging.new.expensify.com/r/6997181192654972
3. Navigate to the self DM that populates in LHN
4. Click ‘Sign in’ in the banner
5. Sign in w/ Google


https://github.com/user-attachments/assets/837da8d2-4834-4025-b248-1fe9d31913e4

**Comment by m-natarajan** [comment] 2024-07-23 23:11
Issue reproducible

https://github.com/user-attachments/assets/5422df9e-0cc3-4ef1-a46d-aedf2ec8554f

**Comment by cristipaval** [comment] 2024-07-25 13:48
my top priority today. I'll first try to reproduce in my local env.

**Comment by puneetlath** [comment] 2024-07-25 14:56
Wait, I don't follow. From looking at that video, it seems like everything worked, no?

**Comment by cristipaval** [comment] 2024-07-25 15:02
As far as I understand, the problem is that the chats that should come in the LHN don't appear.

**Comment by puneetlath** [comment] 2024-07-25 15:49
Ohh I see.

**Comment by cristipaval** [comment] 2024-07-25 22:01
Okay, interesting bug! The app's wrong behavior is because we haven't implemented anonymous account claiming when signing with Google/Apple SSO. It was implemented only for regular sign-in.

The backend PRs are ready for review: [Web-E](https://github.com/Expensify/Web-Expensify/pull/42896) and [Auth](https://github.com/Expensify/Auth/pull/11797).

**Comment by cristipaval** [comment] 2024-08-01 18:34
The fix is in production. Is there any payment due for this issue or should we just close?

**Comment by rezkiy37** [comment] 2024-08-02 09:01
I am a contractor from Callstack. So no payments for me.

**Comment by lschurr** [comment] 2024-08-02 15:11
I think we're good to close. Thanks @cristipaval!
