### ISSUE TITLE
[HOLD] [$4000] DatePicker doesn't have green border while choosing the date.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14140] opened 2023-01-09 17:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account .
2. Go to any page that has DatePicker (Connect Bank Account Manually step 2,3), try to click on the DatePicker to select the date.
3. Notice that the DatePicker doesn't have any green border

## Expected Result:
DatePicker should have green border while selecting date.

## Actual Result:
DatePicker doesn't have any green border while selecting date.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] MacOS / Safari

**Version Number:** 1.2. 50-14
**Reproducible in staging?:** y
**Reproducible in production?:** Couldn't check
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211370573-8bc2492f-e8f3-482e-a0dd-ad6e61a74372.mov

https://user-images.githubusercontent.com/43996225/211371416-8e089e09-141a-4fbb-aff4-d086625ec557.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hung
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672886700954479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca0f291e348dd8e1</li>
        <li>Upwork Job ID: 1612915729497415680</li>
        <li>Last Price Increase: 2023-01-24</li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-01-10 16:00
@shawnborton I _think_ there have been some other design PR's for fixing design issues. By chance, is something like this included in a fix already in the works?
Or does this one need it's own Upwork job and proposals for fix?

**Comment by Luke9389** [comment] 2023-01-10 20:04
Yeah, I think this will still occur after my inputs pr is merged. Let's keep this issue open for now

**Comment by abekkala** [comment] 2023-01-10 20:11
@Luke9389 is this type of stuff done internally or externally?

**Comment by shawnborton** [comment] 2023-01-10 20:23
I think this can be external.

**Comment by priyeshshah11** [comment] 2023-01-10 21:06
Not reproducible

**Comment by shawnborton** [comment] 2023-01-11 07:45
Oh interesting, so maybe this is not a bug then is what you are saying?

**Comment by getusha** [comment] 2023-01-11 08:07
The issue is we're not updating the state after focusing the input
can be fixed as following

```diff --git a/src/components/TextInput/BaseTextInput.js b/src/components/TextInput/BaseTextInput.js
index 85fc38d5c..41cf4c11a 100644
--- a/src/components/TextInput/BaseTextInput.js
+++ b/src/components/TextInput/BaseTextInput.js
@@ -112,6 +112,7 @@ class BaseTextInput extends Component {

         if (!event.isDefaultPrevented()) {
             this.input.focus();
+            this.setState({isFocused: true});
         }
     }
```

**Comment by priyeshshah11** [comment] 2023-01-11 10:36
@getusha your recording doesn't show the erroneous state, it only shows what already works. Also, do you know why it is working fine on Chrome but not Safari if we're not updating the focus state?

**Comment by getusha** [comment] 2023-01-11 10:56
>  it only shows what already works. 

@priyeshshah11 it's was not working on safari, that's this issue for can you read the description?

**Comment by priyeshshah11** [comment] 2023-01-11 11:17
> > it only shows what already works.
> 
> @priyeshshah11 it's was not working on safari, that's this issue for can you read the description?

my comment already says that it was not working on Safari but you hadn't provided a reason for why it was not working, I can see the note now after you updated your comment above 👍

**Comment by Santhosh-Sellavel** [comment] 2023-01-11 17:33
@deetergp Can you assign another C+ to continue, I am unassigning myself here due to limited availability.

**Comment by s77rt** [comment] 2023-01-11 18:02
May I just point that what @getusha said is right about the existing problem with Safari and the programmatic `focus`.
But what the proposed solution does is actually making a fake focus which I think it's not worth it.

What we should do:
- Make the input actually focusable
- Ignore the issue (it's too complicated given the returned value)


PS: I didn't check the issue in depth, just giving my initial thoughts based on the comments

**Comment by getusha** [comment] 2023-01-11 18:07
>But what the proposed solution does is actually making a fake focus which I think it's not worth it.

i suggest you to see the issue & code on depth, and i don't know how you call it fake focus since we're calling `focus()` right above it

>PS: I didn't check the issue in depth, just giving my initial thoughts based on the comments

Thank you for your concern and can we wait for C+ review because i don't think your concern is right.

**Comment by s77rt** [comment] 2023-01-11 18:18
The call of `focus()` is doing nothing, and you are using `this.setState({isFocused: true});` to make the the input looks as it's focused (fake focus).

Ideally the call of `focus()` should be enough. (but it's not due to how safari restrict `focus` calls). You can find more info in this similar issue here https://github.com/Expensify/App/issues/10414

**Comment by getusha** [comment] 2023-01-11 18:25
> The call of focus() is doing nothing

`this.input.focus();` focuses the input on press
if it is doing nothing why is it doing here then? and it's so obvious it's doing something, can we please wait for C+ reviewer? 
FYI if you have proposals you can post here Thank you!

**Comment by allroundexperts** [comment] 2023-01-11 21:27
@getusha In my opinion, @s77rt is saying the correct thing. There's really no competition going on here. We're just helping each other and the community.

**Comment by getusha** [comment] 2023-01-12 04:37
>There's really no competition going on here.

@allroundexperts I know that and i am not saying it, i am saying i don't agree with the concern it doesn't have ground for me.

**Comment by Luke9389** [comment] 2023-01-12 19:51
Hi folks! 
Thank you all for the spirited discussion here. Let's remember that collaborating is important, and disagreements should always be handled with respect, and by assuming the best intentions of others.

Recommendation: any time we claim a fact (e.g. 'X doesn't work on Safari'), we should try to provide links to documentation that supports that. 

Example: Here is some [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus) claiming that this is "by design". 
Clicking [the link](https://bugs.webkit.org/show_bug.cgi?id=22261) in that paragraph shows a page that says "RESOLVED WONTFIX".

So it looks like we will have to settle for some sort of workaround, because it does not seem that a fix will come from Safari. In other words, we need to make a choice, `do nothing` or `apply a workaround`. 

Does this sound correct to you all?

**Comment by ali-thowfeek** [comment] 2023-01-13 13:46
First off, we have to fix `showDatepicker` function on the `Datepicker` component. Because this causes it to send another click event after focussing. Since the doc of the function states that its only needed in mobile web browsers we should add a check for it:
*/src/components/DatePicker/index.js*
```diff
 import './styles.css';
+import {isMobile} from '../../libs/Browser';
...
...
     /**
     * Pops the datepicker up when we focus this field. This only works on mWeb
     * On mWeb the user needs to tap on the field again in order to bring the datepicker. But our current styles
     * don't make this very obvious. To avoid confusion we open the datepicker when the user focuses the field
     */
    showDatepicker() {
        if (!this.inputRef) {
            return;
        }

+        if (isMobile()) {
            this.inputRef.click();
+        }
    }
```
This way we are not dealing with multiple click events on desktop. 

Next, the main issue was, even the `focus` event is fired upon the `<input>` element, it was not calling back `onFocus` specifically for `date` type. So, we add a `focus` listener to the underlying `<input>` element, and call the `onFocus` method on it.

Also we will have to stop propagation of the event. `event.stopImmediatePropagation();` Because adding a log within the focus event revealed that the focus event is being fired multiple times. Each time we re-focus, the number of this function getting called is getting multiplied, sometimes gets to crazy numbers, which also adds to this issue. This behaviour is present in text inputs as well, but they don't give any issues because of it. So we should target only date inputs like this `getAttribute('type') === 'date'`

## Solution

*src/components/TextInput/BaseTextInput.js*
``` diff 
 import FormHelpMessage from '../FormHelpMessage';
+import * as Browser from '../../libs/Browser';
 
                                    <RNTextInput
                                         ref={(ref) => {
                                             if (typeof this.props.innerRef === 'function') { this.props.innerRef(ref); }
                                             this.input = ref;
+
+                                            if (Platform.OS === 'web' && !Browser.isMobile() && ref && ref.getAttribute && ref.getAttribute('type') === 'date') {
+                                                ref.addEventListener('focus', (event) => {
+                                                    this.onFocus();
+                                                    event.stopImmediatePropagation();
+                                                });
+                                            }
                                         }}
                                         // eslint-disable-next-line
                                         {...inputProps}
```

**Comment by s77rt** [comment] 2023-01-13 15:27
### Proposal
```diff
diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index 2983ce7620..269af4502f 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js
@@ -3,6 +3,7 @@ import moment from 'moment';
 import _ from 'underscore';
 import TextInput from '../TextInput';
 import CONST from '../../CONST';
+import * as Browser from '../../libs/Browser';
 import {propTypes, defaultProps} from './datepickerPropTypes';
 import withWindowDimensions, {windowDimensionsPropTypes} from '../withWindowDimensions';
 import './styles.css';
@@ -59,7 +60,9 @@ class DatePicker extends React.Component {
             return;
         }
 
-        this.inputRef.click();
+        if (Browser.isMobile()) {
+            this.inputRef.click();
+        }
     }
 
     render() {
@@ -73,6 +76,7 @@ class DatePicker extends React.Component {
                         this.props.innerRef(el);
                     }
                 }}
+                useNativeFocusEvent={CONST.BROWSER.SAFARI === Browser.getBrowser()}
                 onFocus={this.showDatepicker}
                 label={this.props.label}
                 onInputChange={this.setDate}
diff --git a/src/components/TextInput/baseTextInputPropTypes.js b/src/components/TextInput/baseTextInputPropTypes.js
index b18c1fe6cd..867e456963 100644
--- a/src/components/TextInput/baseTextInputPropTypes.js
+++ b/src/components/TextInput/baseTextInputPropTypes.js
@@ -70,6 +70,11 @@ const propTypes = {
 
     /** Whether we should wait before focusing the TextInput, useful when using transitions  */
     shouldDelayFocus: PropTypes.bool,
+
+    /** (Web) Whether to listen for "focus" event and create "focusin" event manually or not.
+     * React only listens for "focusin" event and there may be cases where "focusin" does not fire but "focus" fires.
+     * USE WITH CAUTION: This may results in double focusin events if used improperly */
+    useNativeFocusEvent: PropTypes.bool,
 };
 
 const defaultProps = {
@@ -101,6 +106,7 @@ const defaultProps = {
     prefixCharacter: '',
     onInputChange: () => {},
     shouldDelayFocus: false,
+    useNativeFocusEvent: false,
 };
 
 export {propTypes, defaultProps};
diff --git a/src/components/TextInput/index.js b/src/components/TextInput/index.js
index 4cbed48ce3..9ace1bb534 100644
--- a/src/components/TextInput/index.js
+++ b/src/components/TextInput/index.js
@@ -5,6 +5,12 @@ import BaseTextInput from './BaseTextInput';
 import * as baseTextInputPropTypes from './baseTextInputPropTypes';
 
 class TextInput extends React.Component {
+    constructor(props) {
+        super(props);
+
+        this.handleNativeFocusEvent = this.handleNativeFocusEvent.bind(this);
+    }
+
     componentDidMount() {
         if (this.props.disableKeyboard) {
             this.textInput.setAttribute('inputmode', 'none');
@@ -13,6 +19,18 @@ class TextInput extends React.Component {
         if (this.props.name) {
             this.textInput.setAttribute('name', this.props.name);
         }
+
+        if (this.props.useNativeFocusEvent) {
+            this.textInput.addEventListener('focus', this.handleNativeFocusEvent);
+        }
+    }
+
+    componentWillUnmount() {
+        this.textInput.removeEventListener('focus', this.handleNativeFocusEvent);
+    }
+
+    handleNativeFocusEvent() {
+        this.textInput.dispatchEvent(new FocusEvent('focusin', {bubbles: true}));
     }
 
     render() {
```

### RCA
I agree with @ntdiary analysis, just wanted to add that React uses `focusin` / `focusout` instead of `focus` / `blur` just to comply with native behaviours as the former events bubbles (just as in native) where the latter do not.

The fix is to listen for `focus` event and manually fire `focusin` event (a proxy or a forward technique).
I have added `useNativeFocusEvent` prop to enable that behaviour and I have only added this to our `DatePiicker` and it's only enabled if the browser is safari.
I have also fixed the double click where the DatePicker shows up and hides immediately, this has been also noted by @ali-thowfeek 

### Results

https://user-images.githubusercontent.com/16493223/212356500-67537bc2-62d0-421c-a4ad-4cbd0706df53.mp4

**Comment by getusha** [comment] 2023-01-13 16:01
Is Manually dispatching an event a good practice towards this issue? Dispatching events manually is considered bad practice. after all we land on `isFocused: false`.

**Comment by s77rt** [comment] 2023-01-13 16:16
@ntdiary I'm just saying that you should consider posting new proposals in new comments just to avoid confusion. As for this issue, chronologically speaking I got to that approach first.

@getusha I'm trying to provide the best solution given the scenario that we are at, if we have a missing event we can create it. Not only we land on `isFocused: true` but we also land on focused input. TAB navigation also works this way.

**Comment by s77rt** [comment] 2023-01-13 16:16
@ntdiary I'm just saying that you should consider posting new proposals in new comments just to avoid confusion. As for this issue, chronologically speaking I got to that approach first.

@getusha I'm trying to provide the best solution given the scenario that we are at, if we have a missing event we can create it. Not only we land on `isFocused: true` but we also land on focused input. TAB navigation also works this way.

**Comment by s77rt** [comment] 2023-01-13 16:39
### Proposal 2
```diff
diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index 2983ce7620..4d4cdb86fd 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js
@@ -3,6 +3,7 @@ import moment from 'moment';
 import _ from 'underscore';
 import TextInput from '../TextInput';
 import CONST from '../../CONST';
+import * as Browser from '../../libs/Browser';
 import {propTypes, defaultProps} from './datepickerPropTypes';
 import withWindowDimensions, {windowDimensionsPropTypes} from '../withWindowDimensions';
 import './styles.css';
@@ -18,6 +19,7 @@ class DatePicker extends React.Component {
 
         this.setDate = this.setDate.bind(this);
         this.showDatepicker = this.showDatepicker.bind(this);
+        this.forwardFocusEvent = this.forwardFocusEvent.bind(this);
 
         /* We're using uncontrolled input otherwise it wont be possible to
         * raise change events with a date value - each change will produce a date
@@ -31,6 +33,14 @@ class DatePicker extends React.Component {
         // Adds nice native datepicker on web/desktop. Not possible to set this through props
         this.inputRef.setAttribute('type', 'date');
         this.inputRef.classList.add('expensify-datepicker');
+
+        if (CONST.BROWSER.SAFARI === Browser.getBrowser()) {
+            this.inputRef.addEventListener('focus', this.forwardFocusEvent);
+        }
+    }
+
+    componentWillUnmount() {
+        this.inputRef.removeEventListener('focus', this.forwardFocusEvent);
     }
 
     /**
@@ -59,7 +69,13 @@ class DatePicker extends React.Component {
             return;
         }
 
-        this.inputRef.click();
+        if (Browser.isMobile()) {
+            this.inputRef.click();
+        }
+    }
+
+    forwardFocusEvent() {
+        this.inputRef.dispatchEvent(new FocusEvent('focusin', {bubbles: true}));
     }
 
     render() {
```

### Details
Same as the [first proposal](https://github.com/Expensify/App/issues/14140#issuecomment-1382017319).
The first proposal is generic and offers the functionality to every `<TextInput />` so it's future proof and we should go with that. Just for the sake of simplicity I'm submitting another proposal with the minimalist changes. This proposal only effects `<DatePicker />`

**Comment by ali-thowfeek** [comment] 2023-01-13 18:26
Same Proposal as my first https://github.com/Expensify/App/issues/14140#issuecomment-1381873872. Forgot to add cleanup for listener. So here it goes:

*/src/components/DatePicker/index.js*
```diff
 import './styles.css';
+import {isMobile} from '../../libs/Browser';
...
...
     /**
     * Pops the datepicker up when we focus this field. This only works on mWeb
     * On mWeb the user needs to tap on the field again in order to bring the datepicker. But our current styles
     * don't make this very obvious. To avoid confusion we open the datepicker when the user focuses the field
     */
    showDatepicker() {
        if (!this.inputRef) {
            return;
        }

+        if (isMobile()) {
            this.inputRef.click();
+        }
    }
```

*src/components/TextInput/BaseTextInput.js*
``` diff 
 import {
-    Animated, View, TouchableWithoutFeedback, AppState, Keyboard,
+    Animated, View, TouchableWithoutFeedback, AppState, Keyboard, Platform,
 } from 'react-native';
 ...
 import FormHelpMessage from '../FormHelpMessage';
+import * as Browser from '../../libs/Browser';

   constructor(props) {
      super(props);
      this.togglePasswordVisibility = this.togglePasswordVisibility.bind(this);
      this.dismissKeyboardWhenBackgrounded = this.dismissKeyboardWhenBackgrounded.bind(this);
      this.storePrefixLayoutDimensions = this.storePrefixLayoutDimensions.bind(this);
+      this.onDatePickerFocus = this.onDatePickerFocus.bind(this);
   }
...
...
     componentWillUnmount() {
        if (this.focusTimeout) {
            clearTimeout(this.focusTimeout);
        }

+        if (this.input) {
+            this.input.removeEventListener('focus', this.onDatePickerFocus);
+        }
+
        if (!this.props.disableKeyboard || !this.appStateSubscription) {
            return;
        }

        this.appStateSubscription.remove();
    }
...
...
onBlur(event) {
        if (this.props.onBlur) { this.props.onBlur(event); }
        this.setState({isFocused: false});
        this.deactivateLabel();
    }

+    onDatePickerFocus(event) {
+        this.onFocus();
+        event.stopImmediatePropagation();
+    }
+
...
...

<RNTextInput
    ref={(ref) => {
        if (typeof this.props.innerRef === 'function') { this.props.innerRef(ref); }
        this.input = ref;

+        if (Platform.OS === 'web' && !Browser.isMobile() && ref && ref.getAttribute && ref.getAttribute('type') === 'date') {
+            ref.addEventListener('focus', this.onDatePickerFocus);
+        }
    }}
```

**Comment by deetergp** [comment] 2023-01-13 19:12
@abekkala I threw caution to the wind and re-applied the `External` label and it doesn't seem to have broken anything and it added @eVoloshchak as the new C+. 

@eVoloshchak are you available to review these proposals?

**Comment by eVoloshchak** [comment] 2023-01-13 20:25
> @eVoloshchak are you available to review these proposals?

Yes, I can do that tomorrow (in ±14 hours)

**Comment by ali-thowfeek** [comment] 2023-01-14 04:53
In my first [proposal](https://github.com/Expensify/App/issues/14140#issuecomment-1381873872) I had included `event.stopImmediatePropagation();` to stop the focus event from firing multiple times. Realized it was the anonymous function that I passed to the listener causing that 🤦‍♂️. Fixing that made me realize that I can target only safari on desktop in this case. So I've fixed them, and refactored the code to look nicer in the following proposal:

## Updated Proposal
**src/components/DatePicker/index.js**
``` diff
 import withWindowDimensions, {windowDimensionsPropTypes} from '../withWindowDimensions';
 import './styles.css';
+import * as Browser from '../../libs/Browser';
...
...
     /**
     * Pops the datepicker up when we focus this field. This only works on mWeb
     * On mWeb the user needs to tap on the field again in order to bring the datepicker. But our current styles
     * don't make this very obvious. To avoid confusion we open the datepicker when the user focuses the field
     */
    showDatepicker() {
        if (!this.inputRef) {
            return;
        }

+        if (isMobile()) {
            this.inputRef.click();
+        }
    }
 
     render() {
         return (
             <TextInput
                 forceActiveLabel
+                shouldFixSafariFocusEvent={Browser.getBrowser() === CONST.BROWSER.SAFARI && !Browser.isMobile()}
                 ref={(el) => {
                     this.inputRef = el;
```

**src/components/TextInput/BaseTextInput.js**
``` diff
    componentWillUnmount() {
        if (this.focusTimeout) {
            clearTimeout(this.focusTimeout);
        }

+        if (this.input) {
+            this.input.removeEventListener('focus', this.onFocus);
+        }
+
         if (!this.props.disableKeyboard || !this.appStateSubscription) {
             return;
         }
@@ -271,6 +275,10 @@ class BaseTextInput extends Component {
                                         ref={(ref) => {
                                             if (typeof this.props.innerRef === 'function') { this.props.innerRef(ref); }
                                             this.input = ref;
+
+                                            if (ref && this.props.shouldFixSafariFocusEvent) {
+                                                ref.addEventListener('focus', this.onFocus);
+                                            }
                                         }}
                                         // eslint-disable-next-line
                                         {...inputProps}
```

**src/components/TextInput/baseTextInputPropTypes.js**
``` diff
const propTypes = {
...
...
     /** Whether we should wait before focusing the TextInput, useful when using transitions  */
     shouldDelayFocus: PropTypes.bool,
+
+    /** Safari on Desktop doesn't fire the event 'focusin' on <input> with 'date' type.
+     * rather it will only fire 'focus' event. Thus, react will not callback the onFocus callback.
+     * Passing `true` to this prop will ensure, that the onFocus callback is called regardless.
+     */
+    shouldFixSafariFocusEvent: PropTypes.bool,
 };
 
 const defaultProps = {
     ...
     ...
     prefixCharacter: '',
     onInputChange: () => {},
     shouldDelayFocus: false,
+    shouldFixSafariFocusEvent: false,
 };
 
 export {propTypes, defaultProps};
```

**Comment by eVoloshchak** [comment] 2023-01-14 15:16
I agree with @Luke9389 on [this](https://github.com/Expensify/App/issues/14140#issuecomment-1380926314)
> In other words, we need to make a choice, `do nothing` or `apply a workaround`.

We need to make that choice first, there are a couple of great proposals, but all of them are workarounds.
And if we decide to apply a workaround, should we find an approach that would fix it on all pages?

**Comment by getusha** [comment] 2023-01-14 16:34
### Proposal 2 Updated
My first proposal had doubts about tab navigation not giving the element green border. This solution completely eliminates that doubt. and works perfectly https://github.com/Expensify/App/issues/14140#issuecomment-1378372498

```diff --git a/src/components/TextInput/BaseTextInput.js b/src/components/TextInput/BaseTextInput.js
index 824d32c765..d0b99b190e 100644
--- a/src/components/TextInput/BaseTextInput.js
+++ b/src/components/TextInput/BaseTextInput.js
@@ -53,6 +53,7 @@ class BaseTextInput extends Component {
     }

     componentDidMount() {
+        this.input.onfocus = () => {this.setState({isFocused: true})}
         if (this.props.disableKeyboard) {
             this.appStateSubscription = AppState.addEventListener(
                 'change',
```


https://user-images.githubusercontent.com/75031127/212483642-cfe1bcf2-cfd2-478d-83de-e28fe5b04ac0.mov

cc: @eVoloshchak

**Comment by deetergp** [comment] 2023-01-17 18:56
I'm actually on the fence and leaning toward `do nothing` since this appears to be "by design" in Safari. @Luke9389 @shawnborton a penny for your thoughts?

**Comment by Luke9389** [comment] 2023-01-17 19:14
I think we should try and figure out _why_ this is by design in Safari. 

Maybe we're just holding something wrong? 

Surely Safari should be supporting focusing all sorts of inputs, right? 
What do you think @eVoloshchak?

**Comment by getusha** [comment] 2023-01-17 19:46
It does support the focus, even it focuses the date picker sometimes on safari (with green border). I.e. when clicking exactly on the date text, tab navigating with `shift + tab`. It's not just updating the state based on the focus event and can be completely fixed applying https://github.com/Expensify/App/issues/14140#issuecomment-1382846827 or my previous proposal.

**Comment by deetergp** [comment] 2023-01-23 19:39
> but to me personally different behavior when using Chrome and Safari feels like a bug

The more I think about it, the more I think I agree with this. I like @getusha's simple one-liner proposal, unless @eVoloshchak disagrees, I think we should go with that.

**Comment by s77rt** [comment] 2023-01-23 19:42
@deetergp I disagree since I think it will **probably** break native.
I don't think native have `onFocus` method on any element.

**Comment by s77rt** [comment] 2023-01-24 07:13
Since this is a bug in Safari. The current approach is to do nothing.

**Comment by deetergp** [comment] 2023-01-24 17:15
Interesting @ntdiary, so it looks like they are aware of the bug and will address it at some point soon. That makes me even more inclined to do nothing for the time being.

**Comment by ali-thowfeek** [comment] 2023-01-24 17:24
@deetergp well i you look at the [bug report](https://bugs.webkit.org/show_bug.cgi?id=22261#c68) which @eVoloshchak already shared, this issue has been there for more than a decade, plus if you see the status of the bug, it says `RESOLVED WONTFIX` So i dont think this issue (behaviour?) is going to be fixed in safari.

**Comment by getusha** [comment] 2023-01-24 17:39
as @ali-thowfeek stated this is not going to be fixed any time soon from safari and the issue was open for a long period of time.
@deetergp i believe it should be consistent around browsers, specially when we are able to fix it.

**Comment by eVoloshchak** [comment] 2023-01-24 18:39
> The more I think about it, the more I think I agree with this. I like @getusha's simple one-liner proposal, unless @eVoloshchak disagrees, I think we should go with that.

@deetergp, I also think this approach is the best one, however, it results in setState being called twice on Chrome (but not on Safari). This doesn't affect anything for now, but might in the future. I'll try to play around with this and other proposals tomorrow. 
I also noticed that this line might be partially responsible for our problem (in Safari, but not in Chrome)

https://github.com/Expensify/App/blob/25b47dadefb53a1863d2802f51105e20fede0654/src/components/DatePicker/index.js#L63

**Comment by getusha** [comment] 2023-01-24 19:03
@eVoloshchak this can be problematic sometimes, as the video below
https://github.com/Expensify/App/blob/25b47dadefb53a1863d2802f51105e20fede0654/src/components/DatePicker/index.js#L63

https://user-images.githubusercontent.com/75031127/214383496-6669be80-7ca2-4c16-8603-54dddaa7c0d4.mov

* This is producible in prod

we can easily fix that
```diff 
diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index e25cc90ce1..a47c931004 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js
@@ -55,12 +74,13 @@ class DatePicker extends React.Component {
      * On mWeb the user needs to tap on the field again in order to bring the datepicker. But our current styles
      * don't make this very obvious. To avoid confusion we open the datepicker when the user focuses the field
      */
-    showDatepicker() {
-        if (!this.inputRef) {
+    showDatepicker(e) {
+        if (!this.inputRef || e.target === this.inputRef) {
             return;
         }
```

> it results in setState being called twice on Chrome

We can target a platform since this is a specific issue on safari

**Comment by s77rt** [comment] 2023-01-24 22:38
@eVoloshchak Am I missing something? As this [proposal](https://github.com/Expensify/App/issues/14140#issuecomment-1382110497) seems to do exactly what's required with regards to:
- focus / setState is not called twice.
- addresses the `this.inputRef.click` call

**Comment by getusha** [comment] 2023-01-25 07:47
### Proposal 1 (Updated)

```diff --git a/src/components/TextInput/BaseTextInput.js b/src/components/TextInput/BaseTextInput.js
index 1788476ed9..6447494be1 100644
--- a/src/components/TextInput/BaseTextInput.js
+++ b/src/components/TextInput/BaseTextInput.js
@@ -19,6 +19,8 @@ import Checkbox from '../Checkbox';
 import getSecureEntryKeyboardType from '../../libs/getSecureEntryKeyboardType';
 import CONST from '../../CONST';
 import FormHelpMessage from '../FormHelpMessage';
+import getPlatform from "../../libs/getPlatform";
+import { getBrowser } from "../../libs/Browser";

 class BaseTextInput extends Component {
     constructor(props) {
@@ -117,6 +119,14 @@ class BaseTextInput extends Component {

         if (!event.isDefaultPrevented()) {
             this.input.focus();
+            if (getPlatform() === CONST.PLATFORM.WEB &&
+                getBrowser() === CONST.BROWSER.SAFARI &&
+                this.props.inputType === CONST.INPUT_TYPES.DATE) {
+                // on safari the onFocus event listener is not functioning as expected when an element receives focus.
+                // This issue may prevent the associated functionality from being executed.
+                // more details: https://github.com/Expensify/App/issues/14140
+                this.setState({ isFocused: true });
+            }
         }
     }
```

```diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index e25cc90ce1..8ac2e7fbef 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js

@@ -84,6 +84,7 @@ class DatePicker extends React.Component {
                 containerStyles={this.props.containerStyles}
                 disabled={this.props.disabled}
                 onBlur={this.props.onBlur}
+                inputType={CONST.INPUT_TYPES.DATE}
             />
         );
     }
```

```diff --git a/src/components/TextInput/baseTextInputPropTypes.js b/src/components/TextInput/baseTextInputPropTypes.js
index b18c1fe6cd..d132b5c686 100644
--- a/src/components/TextInput/baseTextInputPropTypes.js
+++ b/src/components/TextInput/baseTextInputPropTypes.js
@@ -70,6 +70,9 @@ const propTypes = {

     /** Whether we should wait before focusing the TextInput, useful when using transitions  */
     shouldDelayFocus: PropTypes.bool,
+
+    /**The type is used to identify the input type in a form (i.e. checkbox, date) */
+    inputType: PropTypes.string,
 };

 const defaultProps = {
@@ -101,6 +104,7 @@ const defaultProps = {
     prefixCharacter: '',
     onInputChange: () => {},
     shouldDelayFocus: false,
+    inputType: ''
 };
```

```diff --git a/src/CONST.js b/src/CONST.js
index 9c05e4d716..cf30af0d25 100755
--- a/src/CONST.js
+++ b/src/CONST.js
@@ -126,6 +126,9 @@ const CONST = {
         SOLE_PROPRIETORSHIP: 'Sole Proprietorship',
         OTHER: 'Other',
     },
+    INPUT_TYPES: {
+        DATE: "date",
+    },
     BETAS: {
         ALL: 'all',
         CHRONOS_IN_CASH: 'chronosInCash',
```


* Proactively addressed and resolved any potential concerns that may have arisen.
* Made enhancements to the solution to ensure optimal efficiency.

**Comment by getusha** [comment] 2023-01-25 07:47
### Proposal 2 (Updated)

```diff --git a/src/components/TextInput/BaseTextInput.js b/src/components/TextInput/BaseTextInput.js
index 1788476ed9..59091683ce 100644
--- a/src/components/TextInput/BaseTextInput.js
+++ b/src/components/TextInput/BaseTextInput.js
@@ -19,6 +19,8 @@ import Checkbox from '../Checkbox';
 import getSecureEntryKeyboardType from '../../libs/getSecureEntryKeyboardType';
 import CONST from '../../CONST';
 import FormHelpMessage from '../FormHelpMessage';
+import getPlatform from "../../libs/getPlatform";
+import { getBrowser } from "../../libs/Browser";

 class BaseTextInput extends Component {
     constructor(props) {
@@ -53,6 +55,14 @@ class BaseTextInput extends Component {
     }

     componentDidMount() {
+        if (getPlatform() === CONST.PLATFORM.WEB &&
+            getBrowser() === CONST.BROWSER.SAFARI &&
+            this.props.inputType === CONST.INPUT_TYPES.DATE) {
+            // on safari the onFocus event listener is not functioning as expected when an element receives focus.
+            // This issue may prevent the associated functionality from being executed.
+            // more details: https://github.com/Expensify/App/issues/14140
+            this.input.onfocus = () => this.setState({isFocused: true});
+        }
         if (this.props.disableKeyboard) {
             this.appStateSubscription = AppState.addEventListener(
                 'change',
```

Remember to incorporate the values from the above diff
cc: @eVoloshchak @deetergp

**Comment by situchan** [comment] 2023-01-25 17:11
According to https://github.com/Expensify/App/issues/14322#issuecomment-1403943585, I wonder this GH might be put on HOLD.
cc: @JmillsExpensify @luacmartins

**Comment by luacmartins** [comment] 2023-01-25 17:36
Yes, let's put this on Hold for the datepicker refactor.

**Comment by abekkala** [comment] 2023-01-26 20:17
melvin, this is on hold for now

**Comment by eVoloshchak** [comment] 2023-02-06 12:51
Not overdue, on HOLD for the datepicker refactor

**Comment by deetergp** [comment] 2023-02-14 22:05
same as the above

**Comment by abekkala** [comment] 2023-02-20 13:10
this is on hold

**Comment by abekkala** [comment] 2023-02-28 20:42
Still on Hold

**Comment by abekkala** [comment] 2023-03-08 21:39
still on hold

**Comment by abekkala** [comment] 2023-03-15 17:35
I'm assuming this is still on Hold.

**Comment by abekkala** [comment] 2023-03-21 14:02
PR for datepicker refactor is still being worked on. 
Hold continues

**Comment by abekkala** [comment] 2023-03-23 14:42
@deetergp I am going ooo and will return on Tuesday April 04. This can remain assigned to me until I get back. (as I'm not sure how much longer this will remain on Hold)
However, if the datepicker refactor completes before then and this gets taken off hold please reassign the Bug label to get a new BZ member assigned to get this one trucking along and not be delayed until my return.

**Comment by deetergp** [comment] 2023-04-12 18:33
Still on Hold

**Comment by abekkala** [comment] 2023-04-21 16:13
Still on hold

**Comment by eVoloshchak** [comment] 2023-05-01 09:43
Still on hold

**Comment by abekkala** [comment] 2023-05-10 12:32
@deetergp should this _still_ be on hold?

**Comment by abekkala** [comment] 2023-05-17 18:36
@deetergp @eVoloshchak can this be taken off Hold? And should the rate remain at $4000?

**Comment by eVoloshchak** [comment] 2023-05-21 17:13
@abekkala, we're still not using the new date picker in connect bank account steps, this should remain on hold i think

**Comment by deetergp** [comment] 2023-05-29 22:23
Still on hold

**Comment by deetergp** [comment] 2023-06-08 00:47
Same. Same.

**Comment by deetergp** [comment] 2023-06-21 05:18
We are still holding.

**Comment by abekkala** [comment] 2023-06-29 14:24
In preparation for Sabbatical I'm reassigning the label to get a BZ manager on this. 

@jliexpensify **Current status of this issue:** 

This has been on HOLD since January for the datepicker refactor

**Comment by deetergp** [comment] 2023-07-04 00:54
AFAIK this is still on hold and should still be `Weekly` at most.

**Comment by deetergp** [comment] 2023-07-12 20:23
Still on hold.

**Comment by jliexpensify** [comment] 2023-07-24 00:51
On hold

**Comment by DevWizard0000** [comment] 2023-07-24 15:54
### Proposal
The main problem of this issue is because of using HTML DatePicker Component.
You can simply fix this issue with styling css to native HTML component.

**Comment by jliexpensify** [comment] 2023-07-26 23:36
No overdue, still on Hold

**Comment by deetergp** [comment] 2023-08-04 21:47
Still on hold

**Comment by eVoloshchak** [comment] 2023-08-14 13:14
Not overdue, still on hold

**Comment by deetergp** [comment] 2023-08-23 20:41
Still on hold

**Comment by eVoloshchak** [comment] 2023-09-03 19:41
Still on hold, not overdue

**Comment by deetergp** [comment] 2023-09-13 01:24
Still holding

**Comment by jliexpensify** [comment] 2023-09-21 23:43
Oh hold

**Comment by shubham1206agra** [comment] 2023-11-10 03:15
We are migrating to NewDatePicker in BA flow. 
@shawnborton Can you confirm the places where the old date picker is available?
cc @jliexpensify

**Comment by shawnborton** [comment] 2023-11-10 11:54
Hmm I'm not entirely sure where exactly it is being used in that flow. Can we just close this issue out and handle all of the date picker stuff in the issue/project for updating the VBA flow? This one is quite old at this point.

**Closed** 2023-11-10 16:35 UTC
Labels: External, Monthly, Help Wanted, Overdue, Bug
