### ISSUE TITLE
[HOLD for payment 2024-04-05] Chat - Video does not resume playing after regaining internet connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36903] opened 2024-02-20 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to chat
3. Upload a video
4. Go offline after upload is complete
5. Play the video
6. Go online
7. Note that it loads infinitely
8. (Web and desktop app only) Open the video in full screen
9. Note that it loads
10. Return to chat view

## Expected Result:
In Step 6, after returning online, the video should load without issue
In Step 10, the video in the chat view will play because it loads successfully in Step 8

## Actual Result:
In Step 6, after returning online, the video still loads infinitely
In Step 10, the video in the chat view does not load

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a954b3bf-7603-48d8-9ddc-1a3b774b08a3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-02-20 15:26
I do feel like this is a new feature and it would not have to be a deploy blocker @francoisl

**Comment by mountiny** [comment] 2024-02-23 21:50
@kowczarz any updates

**Comment by Skalakid** [comment] 2024-02-26 16:52
Hey, I will continue @kowczarz's investigation and take a look on it :D

**Comment by Skalakid** [comment] 2024-03-04 11:45
Hi, I investigated the issue and created a fix for it https://github.com/Expensify/App/pull/37674. The problem is probably connected to expo-av implementation, however we can simply fix it by forcing video player to restart video loading by changing its uri inside

**Comment by mountiny** [comment] 2024-03-29 22:17
I beelive we can close this one now

**Closed by mountiny** 2024-03-29 22:17 UTC
Labels: External, Engineering, Weekly, Awaiting Payment

**Comment by eVoloshchak** [comment] 2024-04-25 20:35
- The PR that introduced the bug has been identified. Link to the PR: this is a problem with `expo-av` implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, we already have the following item in PR reviewer checklist: I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)

**Regression Test Proposal**

1. Navigate to `staging.new.expensify.com`
2. Go to chat
3. Upload a video
4. Go offline after the upload is complete
5. Play the video
6. Go online
7. Verify that the video loads
8. (Web and desktop app only) Open the video in full screen
9. Verify that the video loads

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2024-04-25 20:37
@mountiny, I forgot to finish this one, could you post a payment summary please?

**Comment by mallenexpensify** [comment] 2024-11-18 20:12
Contributor+: @eVoloshchak due $500 via NewDot

**Comment by JmillsExpensify** [comment] 2024-11-19 09:12
$500 approved for @eVoloshchak
