### ISSUE TITLE
[HOLD for payment 2024-11-07] [$125] Update the Onboarding steps for "Chat and split bills with friends"

### ISSUE THREAD

**Issue by zsgreenwald** [Expensify/App#51215] opened 2024-10-22 02:05 UTC
## Problem

The steps presented currently expose dated functionality and that isn't available in-app anymore. This causes user-confusion for anyone that selects that onboarding intent.

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/556c571e-c654-42fa-8818-4fad06bc12d7">

## Solution

Update the onboarding steps for the Task - `Split an expense` to:

Split an expense right in your chat with one or more friends.

Here’s how to request money:

1. Hit the green + button
2. Choose "Start chat"
3. Enter any email, SMS, or name of who you want to split with
4. From within the chat, hit the + button on the message bar, and hit Split expense
5. Create the expense by selecting Manual, Scan or Distance

Feel free to add more details if you want, or just send it off. Let’s get you paid back!

cc: @mallenexpensify @vitHoracek as we'll be tapping C+ for this

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854295488284084894</li>
        <li>Upwork Job ID: 1854295488284084894</li>
        <li>Last Price Increase: 2024-11-06</li>
    </ul>
</details>

**Comment by ChavdaSachin** [comment] 2024-10-22 05:38
## Proposal




### Please re-state the problem that we are trying to solve in this issue.

Update the Onboarding steps for "Chat and split bills with friends"



### What is the root cause of that problem?

General Update



### What changes do you think we should make in order to solve the problem?
I propose to include this task with Spanish translation, and translate all the other  onboarding tasks to Spanish as well(could be handled as separate PR if needed).
Something like....
```js
                {
                    type: 'splitExpense',
                    autoCompleted: false,
                    title: Translate('onboardingTasks.splitExpense.title'),
                    description:
                        Translate('onboardingTasks.splitExpense.description'),
                },
```
https://github.com/Expensify/App/blob/04214cdb3e35816fd28a640f1b3c1b23bd7407b0/src/CONST.ts#L4819-L4834

- And of add update en.ts and es.ts accordingly.



### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mallenexpensify** [comment] 2024-10-22 19:26
@danielrvidal , added `Waiting for copy` for 👀 on copy in the OP.  
@ikevin127 are you doing the work here as the contributor or will you be reviewing proposals and the PR?

I assigned myself as BZ since I was tagged and have context

**Comment by ikevin127** [comment] 2024-10-22 19:44
@mallenexpensify I will be taking over as C+ reviewing the proposals. While we're waiting for confirmation on copy, I will start reviewing the proposals.

**Comment by mallenexpensify** [comment] 2024-10-22 22:04
One more thing @ikevin127 this looks like a simple text update so I set it at $125. Let me know if I'm missing something

**Comment by ikevin127** [comment] 2024-10-22 22:41
Given that there's no mention about translations in the OP, the codebase shows no indication of translating any of the [`ONBOARDING_MESSAGES`](https://github.com/Expensify/App/blob/e74eb8e705bce3e8791e3eb043fe5cbb1cbaecea/src/CONST.ts#L4651-L4857) as we keep them in CONST instead of translation files, I'd say let's go with @nyomanjyotisa's [proposal](https://github.com/Expensify/App/issues/51215#issuecomment-2428072984) as this is a simple copy replacement task.

I think moving / translating all [`ONBOARDING_MESSAGES`](https://github.com/Expensify/App/blob/e74eb8e705bce3e8791e3eb043fe5cbb1cbaecea/src/CONST.ts#L4651-L4857) would be out of scope for this issue. @ChavdaSachin if you want to do that you'd have a better chance in [this issue](https://github.com/Expensify/App/issues/50978), so I'd recommend you to post a proposal there.

🎀👀🎀 C+ reviewed

**Comment by danielrvidal** [comment] 2024-10-23 02:47
The copy looks good in the proposals. I was going to note **Split expense** should be bolded in #4 but it looks like the proposals account for that. I'm unassigning myself but please add me back if needed.

**Comment by mallenexpensify** [comment] 2024-10-25 17:45
@nkuoch , plz review @nyomanjyotisa 's [proposal above](https://github.com/Expensify/App/issues/51215#issuecomment-2428072984) , thx

**Comment by ikevin127** [comment] 2024-11-04 23:33
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by mallenexpensify** [comment] 2024-11-06 22:59
Contributor: @nyomanjyotisa owed $125 via Upwork
Contributor+: @ikevin127 paid $125 via Upwork

@VictoriaExpensify I'm off the next week, can you please keep an eye on this issue til I'm back? Thx @nyomanjyotisa needs to accept the upwork job and @ikevin127 needs to propose details for the test case.

**Comment by ikevin127** [comment] 2024-11-06 23:06
@mallenexpensify Offer accepted, thank you!

Regarding regression test, I mentioned in the checklist https://github.com/Expensify/App/issues/51215#issuecomment-2455914091:

> I don't think regression test is needed here because this was a copy update change, but if required I'd be happy to provide the PRs testing steps.

If what you mean above is that we indeed need to regression test then I'll write it up before payment is due.

**Comment by mallenexpensify** [comment] 2024-11-06 23:28
ah.. sorry, def missed that @ikevin127 

I paid @nyomanjyotisa so we're good to close, thx Vic! ;)

**Closed by mallenexpensify** 2024-11-06 23:28 UTC
Labels: External, Daily, Help Wanted, Waiting for copy, Awaiting Payment, Bug
