### ISSUE TITLE
[Payment due 2024-05-15][$250] Status expiry time does not show correctly when hovering the user in the chat report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40733] opened 2024-04-22 22:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @yuwenmemon 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713818046569569

## Action Performed:
1. Open profile > Status > Set up time to clear the status in 30 min
2. Open any chat report and hover over the status icon
## Expected Result:
Should show the correct status expiry time
## Actual Result:
Showing as "until tomorrow"
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e38034f7-50ec-46f4-9f3b-8e9a042a8a73

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ca471a846444b3a</li>
        <li>Upwork Job ID: 1782651620772831232</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Krishna2323</details>

**Comment by Nodebrute** [comment] 2024-04-22 22:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We should check for ``If the date is equal to the end of today`` first

https://github.com/Expensify/App/blob/0575c561c479c822b782b52b359dc950722d5c32/src/libs/DateUtils.ts#L536-L544
### What changes do you think we should make in order to solve the problem?

We should switch positions of these functions like this
```
    // If it's a time on the same date
      if (isSameDay(input, now)) {
        return translateLocal('statusPage.untilTime', {time: format(input, CONST.DATE.LOCAL_TIME_FORMAT)});
    }

    // If the date is equal to the end of today
    if (isSameDay(input, endOfToday)) {
        return translateLocal('statusPage.untilTomorrow');
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by Nodebrute** [comment] 2024-04-22 23:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Status expiry time does not show correctly when hovering the user in the chat report
### What is the root cause of that problem?
Any time within today will display the message 'until tomorrow.'
https://github.com/Expensify/App/blob/5832dba36ff4f646a64975c81414c9db4f4b8324/src/libs/DateUtils.ts#L536-L539
### What changes do you think we should make in order to solve the problem?

We should use isEqual here
https://github.com/Expensify/App/blob/5832dba36ff4f646a64975c81414c9db4f4b8324/src/libs/DateUtils.ts#L536-L539
```
  // If the date is equal to the end of today
    if (isEqual(input, endOfToday)) {
        return translateLocal('statusPage.untilTomorrow');
    }
```

With just the above change, isEqual will return false for statuses set to today. This is because isEqual compares milliseconds, and since the milliseconds are different, the result is false.

1. The endOfToday has 999 milliseconds. We can set the milliseconds to 0 to make both dates(input & endOfToday) the same.
```
let endOfToday = endOfDay(now);
endOfToday = setMilliseconds(endOfToday, 0)
```
2. Alternatively, we can set the input's milliseconds to match those of endOfToday to ensure they are the same.
3. Another approach is to set the milliseconds for both dates(input & endOfToday) as a safer option.
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-04-23 23:46
@DylanDylann reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by kaushiktd** [comment] 2024-04-24 07:32
### Please re-state the problem that we are trying to solve in this issue.
Status expiry time does not show correctly when hovering the user in the chat report
### What is the root cause of that problem?
The original issue was related to displaying the correct status expiry time based on a comparison between inputDate and the end of the current day (endOfToday). When inputDate matched the end of today, the requirement was to display the time from inputDate instead of a predefined message.
### What changes do you think we should make in order to solve the problem?
to solve this issue we need to update this line of code
https://github.com/Expensify/App/blob/0575c561c479c822b782b52b359dc950722d5c32/src/libs/DateUtils.ts#L536-L539
```
  if (isSameDay(input, endOfToday)) {
        // If inputDate is the end of today, format and return the current time
        const currentTimeFormatted = format(input, "hh:mm a");
        return `status expired at:${currentTimeFormatted}`;
      } else {
        // Handle other cases or return a default status message
        return translateLocal('statusPage.untilTomorrow');
      }
```
video:-https://drive.google.com/file/d/1nUm7BmV6ysaE-gV3jVDjBpo58zU5KYHo/view?usp=sharing

**Comment by DylanDylann** [comment] 2024-04-25 07:55
From my point of view, we only display "until tomorrow" if the user selects `today` option

**Comment by shawnborton** [comment] 2024-04-25 12:25
@tienifr for your first point, how does that relate to the bug at hand? It seems like the bug reported is that if you set a custom status to expire in 30 minutes, we say it will expire "tomorrow" rather than giving an exact time.

**Comment by DylanDylann** [comment] 2024-04-25 12:30
@shawnborton I also think @tienifr's question will help us to make a better solution

**Comment by shawnborton** [comment] 2024-04-25 12:32
> This bug relate to my question because this bug is that tooltip display "Until tomorrow" when setting status to expire in 30 minutes

Right, I'm saying that if you set your status to expire in 30 minutes, the tooltip should very clearly show the exact time that it would expire.

**Comment by kaushiktd** [comment] 2024-04-25 13:08
**Expected Result:**
When configuring a status expiry time, the application should accurately display the specified time for status expiration.
**Actual Result:**
The application currently displays "until tomorrow" instead of the expected custom time set by the user.

**So here is the question:**
Why is there a requirement to set custom times for status expirations in our application?

My proposal shows the expiry time.

**Comment by DylanDylann** [comment] 2024-04-26 10:35
Thanks everyone for your update

**Comment by DylanDylann** [comment] 2024-04-26 10:52
I would love to go with @tienifr's proposal because it is simple and matches our expectation

@kaushiktd I don't think your proposal will match our expectation at this point

> I would think we only show "Until tomorrow" if you chose to use "Today" as your expiration time.

@Krishna2323 Your proposal is close to @tienifr's alternative solution. But I prefer to retain `isSameDay` 

@dragnoir @Nodebrute I don't think isEqual is suitable for this case, It also makes a complicated change

**Comment by DylanDylann** [comment] 2024-04-26 10:58
@Krishna2323 You mean that isSameSecond also check the same day, same hour and same minute

**Comment by DylanDylann** [comment] 2024-04-26 11:02
@dragnoir I am not sure your mean

> For a user typing 11:59 PM as custom date the output will be
endOfToday: Thu Apr 25 2024 23:59:00 GMT+0100 (Central European Standard Time)

input isn't related to endOfToday

If you see there is a regression when applying the selected proposal, please post a video for more understandable

**Comment by DylanDylann** [comment] 2024-04-26 11:02
@Krishna2323 Ohh, good point. Let's me check again

**Comment by DylanDylann** [comment] 2024-04-26 11:08
@dragnoir Yes. It is our [expectation](https://github.com/Expensify/App/issues/40733#issuecomment-2077108808). Do you see any problem with this?

**Comment by kadiealexander** [comment] 2024-04-30 03:31
@youssef-lr bump!

**Comment by youssef-lr** [comment] 2024-05-01 00:13
Sounds good @DylanDylann , assigned @Krishna2323!

**Comment by kadiealexander** [comment] 2024-05-14 03:03
Payouts due:

- [ ] Contributor: $250 @Krishna2323
- [ ] Contributor+: $250 @DylanDylann

Upwork job is [here](https://www.upwork.com/jobs/~016ca471a846444b3a).

**Comment by kadiealexander** [comment] 2024-05-20 05:38
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@DylanDylann] Determine if we should create a regression test for this bug.
- [ ] [@DylanDylann] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by DylanDylann** [comment] 2024-05-20 07:12
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24446
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24446#discussion_r1606348227
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Open profile > Status > Clear after > Select Today and save
2. Open any chat report and hover over the status icon
3. Verify it tooltip shows (Until tomorrow)
4. Open profile > Status > Clear after > Custom > Time > Set 11:59PM and save.
5. Open any chat report and hover over the status icon
6. Verify it tooltip shows (Until 11:59PM)


Do we agree 👍 or 👎

**Closed** 2024-05-28 04:01 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
