### ISSUE TITLE
[HOLD for payment 2023-06-05] Web - Track distance - Drop-down overlaps with Save button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19704] opened 2023-05-26 21:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18454

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Reimbursements -> Rate
4. Click on the unit for opening drop-down menu

## Expected Result:
Drop-down NOT overlaps with the Save button

## Actual Result:
Drop-down overlaps with the Save button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/ff173d20e3374b2c49449d21bd684f3849d68fb329f9682acd822f3d4d0acac8

https://platform.applause.com/services/links/v1/external/8affa9170a635e2eda14fa388e76a3ea2793a7d93cc443c2adb38d4f2594ca4b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6e7cc1637c2ff86</li>
        <li>Upwork Job ID: 1663567916604751872</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-05-28 19:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track distance - Drop-down overlaps with Save button
### What is the root cause of that problem?
Inconsistent position for form button submit between track distance view form and other views.

![Screenshot 2023-05-28 at 9 11 57 PM](https://github.com/Expensify/App/assets/41129870/687ee3ad-27be-440b-82dd-efa26c81944f)


### What changes do you think we should make in order to solve the problem?
Change button save position to bottom by removing `shouldUseScrollView` here

https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L108



### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2023-05-28 23:17
Hi @eVoloshchak and @youssef-lr - @kbecciv has indicated this issue was from your PR https://github.com/Expensify/App/pull/18454. Do you mind taking a look at this one? Thanks!

**Comment by ShogunFire** [comment] 2023-05-29 01:31
I will make a PR for this

**Comment by luacmartins** [comment] 2023-05-29 17:31
This is being addressed [here](https://github.com/Expensify/App/pull/19748) already

**Comment by jliexpensify** [comment] 2023-05-30 00:23
Hi @luacmartins - can I check what's going on with payments here? Are we paying @eVoloshchak (+ the bonus)? Or did you handle this yourself and we don't need to pay? Cheers.

**Comment by luacmartins** [comment] 2023-05-30 15:29
@jliexpensify no payment needed here. This was reported by Applause and it was all handled internally. Thanks for checking. Gonna close the issue!

**Closed by luacmartins** 2023-05-30 15:29 UTC
Labels: Weekly, Internal, Awaiting Payment, Bug
