### ISSUE TITLE
Emoji - Cursor is missing in the emoji search bar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24602] opened 2023-08-15 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Open any chat
4. Open the emoji picker

## Expected Result:
Cursor is present

## Actual Result:
Cursor is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.54.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6166054_Screenshot_2023-08-15-20-33-19-34_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/78819774/836d18be-4b95-4bf8-9735-50709b0ec40a)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-08-16 03:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji - Cursor is missing in the emoji search bar

### What is the root cause of that problem?
The code disables `autoFocus` on touch devices
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/components/EmojiPicker/EmojiPickerMenu/index.js#L64
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/canFocusInputOnScreenFocus/index.js#L3
### What changes do you think we should make in order to solve the problem?
Allow it on touch devices

**Comment by isabelastisser** [comment] 2023-08-17 16:04
This is expected behavior! I just checked in Slack and it's the same. Closing!

**Closed by isabelastisser** 2023-08-17 16:04 UTC
Labels: Daily, Bug
