### ISSUE TITLE
[$250] Workspace-The announce room of the deleted workspace is not pinned

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51826] opened 2024-10-31 18:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**  N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5167707
**Email or phone of affected tester (no customers):** applausetester+bk4@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to http://www.staging.new.expensify.com/
2. Create a workspace if needed and send some messages in the #announce channel
3. Pin the #announce conversation to the LHN
4. Navigate to Workspaces list
5. Click/tap on the 3 dots menu next to a workspace
6. Click/tap on delete workspace
7. Navigate to the #announce room of the deleted workspace in LHN

## Expected Result:
#announce conversation should be pinned in the LHN

## Actual Result:
The announce room of the deleted workspace is not pinned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5d46721d-0cc4-4858-bc65-2161c1ae436d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852450988559100754</li>
        <li>Upwork Job ID: 1852450988559100754</li>
        <li>Last Price Increase: 2024-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by lanitochka17** [comment] 2024-10-31 18:44
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment] 2024-11-01 20:42
@situchan - can you help confirm this is a BE issue?

**Comment by situchan** [comment] 2024-11-04 18:45
Agree BE issue, though I am not sure why it's bug.
🎀👀🎀

**Comment by situchan** [comment] 2024-11-04 20:06
I am going to be on parental leave. Please reassign C+

**Comment by MonilBhavsar** [comment] 2024-11-08 14:39
Will be taking a look

**Comment by MonilBhavsar** [comment] 2024-11-11 11:10
Chats were unpinned on purpose. More discussion is here https://expensify.slack.com/archives/C01GTK53T8Q/p1682344024237229
This is a feature and not a bug. Closing.

**Closed by MonilBhavsar** 2024-11-11 11:10 UTC
Labels: External, Daily, Internal, Overdue, Bug

**Comment by promorthy** [comment] 2024-11-15 11:37
hi

**Comment by promorthy** [comment] 2024-11-15 11:38
Contributor details
Your Expensify account email: morthypro@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f2688de896109865
