### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Profile - App crashes when uploading profile picture

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45162] opened 2024-07-10 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+uo0710@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify and open profile
2. Tap profile picture and tap "upload photo"
3. Select "choose from gallery" and select and photo

## Expected Result:
New profile picture is uploaded

## Actual Result:
The app crashes on edit profile picture screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/515d1072-afba-4c01-a9f5-aac9e70ad95b

https://github.com/Expensify/App/assets/78819774/24424bb1-0bfe-4d20-9b0c-0e12a67925c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a2b40164b680402</li>
        <li>Upwork Job ID: 1811767351593075552</li>
        <li>Last Price Increase: 2024-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>Ahmed-Abdella | Contributor | 103120778</li>
<li>QichenZhu | Contributor | 103123196</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by yuwenmemon** [comment] 2024-07-10 18:38
Able to reproduce.

**Comment by yuwenmemon** [comment] 2024-07-10 18:45
Installing a fresh simulator to give this a test

**Comment by yuwenmemon** [comment] 2024-07-10 20:12
Seems like this is coming from reanimated, and the ImageCropView component

**Comment by yuwenmemon** [comment] 2024-07-10 20:20
@roryabraham Could [this](https://github.com/Expensify/App/pull/45098) somehow have affected the reanimated patch that we apply on staging?

**Comment by yuwenmemon** [comment] 2024-07-10 20:21
We renamed the reanimated patches here and I'm not sure why 🤔 - but it looks awfully sus

**Comment by danieldoglas** [comment] 2024-07-11 09:18
I don't think this is related to backend, removing the `DeployBlocker` tag

**Comment by Julesssss** [comment] 2024-07-11 11:42
> @roryabraham Could [this](https://github.com/Expensify/App/pull/45098) somehow have affected the reanimated patch that we apply on staging?

Tagging the other PR reviewers who are also familiar with the changes: @AndrewGable @fabioh8010

**Comment by yuwenmemon** [comment] 2024-07-11 15:02
Damn, I can't reproduce on dev with the iOS simulator 🤔

**Comment by yuwenmemon** [comment] 2024-07-11 15:10
Ah, we renamed them to reflect the latest version of reanimated.

**Comment by roryabraham** [comment] 2024-07-11 15:29
No, I don't think that PR would have affected the Reanimated patch. All that PR does is fail patch-package if it has an errors or warnings.

For the Reanimated patches, they produced warnings because we had updated the version of Reanimated we were using without updating the patches accordingly. This was a mistake easily missed by reviewers, but my PR would have prevented it. In order to get ✅ on the PR, I had to rename the Reanimated patches to suppress the warning(s).

Why do I say this likely did not cause the crash? Because patch-package was already applying the reanimated patches despite the version mis-match. So app should have been unaffected

**Comment by roryabraham** [comment] 2024-07-11 15:37
The warning that I fixed looks like this:

```
Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    react-native-reanimated@3.7.2

  applied to

    react-native-reanimated@3.8.1
  
  At path
  
    node_modules/react-native-reanimated

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package react-native-reanimated

  to update the version in the patch file name and make this warning go away.
```

**Comment by yuwenmemon** [comment] 2024-07-11 18:07
We're trying a revert of Rory's PR here: https://github.com/Expensify/App/pull/45312

**Comment by yuwenmemon** [comment] 2024-07-12 14:19
Let's see if anyone from the community has an idea how to fix.

**Comment by QichenZhu** [comment] 2024-07-13 12:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when uploading an avatar.

### What is the root cause of that problem?
Just as the error message states, tried to synchronously call non-worklet functions on the UI thread.

### What changes do you think we should make in order to solve the problem?
In addition to @yuwenmemon's PR https://github.com/Expensify/App/pull/45314, we need to make the function below a worklet too.
https://github.com/Expensify/App/blob/fef8ef8c30e69b1807c9ec958e744dbc37816597/src/components/AvatarCropModal/ImageCropView.tsx#L59-L67

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Ahmed-Abdella** [comment] 2024-07-13 19:35
## Proposal
 ### Please re-state the problem that we are trying to solve in this issue.
 App crashes when uploading an avatar.
 
 ### What is the root cause of that problem?
 The issue happens inside the Slider component.
 
![Screenshot 2024-07-13 at 10 20 09 PM](https://github.com/user-attachments/assets/7b3a82b7-766f-4a11-afc6-430e84170e0b)

 in `useAnimatedStyle` function we didn't add the dependencies array
 
 https://github.com/Expensify/App/blob/4ae133db275f32b59592e40a54ef6727c8f4891e/src/components/AvatarCropModal/Slider.tsx#L33-L35
 

 ### What changes do you think we should make in order to solve the problem?
 
 We need to add the dependencies array and add the `SliderValue` inside it.
 
 ```js
   const rSliderStyle = useAnimatedStyle(() => ({
        transform: [{translateX: sliderValue.value}],
    }), [sliderValue]); 
 ```
 
### Result

https://github.com/user-attachments/assets/49e653ca-9fe6-4518-80f6-a520cf0f3d89






 ### What alternative solutions did you explore? (Optional)
 N/A

**Comment by Ahmed-Abdella** [comment] 2024-07-13 19:47
I think my solution also fixes this issue #45164 maybe partially. it makes the slider moves after click to show that the image is zoomed.

**Comment by Julesssss** [comment] 2024-07-15 08:57
Exellent find @Ahmed-Abdella. This is the much simpler solution and I'm going to go ahead with it now due to the high priority. Assigning you for the bounty. 

@QichenZhu I would be interested to hear more about your proposals perhaps it is a secondary fix that should be made on top of the simpler changes?

**Comment by Julesssss** [comment] 2024-07-15 08:58
Again, no need for the PR here.

**Comment by Julesssss** [comment] 2024-07-15 08:59
> I think my solution also fixes this issue #45164 maybe partially. it makes the slider moves after click to show that the image is zoomed.

If I remember correctly, that is the same behaviour that we saw last week.

**Comment by Pujan92** [comment] 2024-07-15 09:16
Commenting for the assignment

**Comment by QichenZhu** [comment] 2024-07-15 09:43
> @QichenZhu I would be interested to hear more about your proposals perhaps it is a secondary fix that should be made on top of the simpler changes?

@Julesssss Thanks for your interest. My proposal is on top of @yuwenmemon's PR https://github.com/Expensify/App/pull/45314.
Regarding the simpler solution by adding a dependencies array, it was also my initial thought. Unfortunately, it didn't fix the crash on iOS native.

**Comment by Ahmed-Abdella** [comment] 2024-07-15 12:32
Thanks @Julesssss for your words and offer accepted.
Looks like there are some changes happened in the behavior of the `useAnimatedStyle` and the `Reanimated` package in 3.8.0. Maybe this [PR in react-native-reanimated](https://github.com/software-mansion/react-native-reanimated/pull/5333) and it's related issue help us to understand. I also found many other issues around the `usAnimatedStyle` dependencies Array.
I will keep working on this  trying to solve the other issue #45164

**Comment by Pujan92** [comment] 2024-07-15 12:40
@Ahmed-Abdella for iOS it is still throwing an error `[Reanimated] Tried to synchronously call a non-worklet function on the UI thread.`

**Comment by Ahmed-Abdella** [comment] 2024-07-15 12:41
Will check Now

**Comment by Julesssss** [comment] 2024-07-15 12:47
@QichenZhu -- yeah, I missed that the accepted proposal didn't work on iOS. 

Do you think your solution would work alongside the accepted proposal?

**Comment by QichenZhu** [comment] 2024-07-15 12:49
@Julesssss Tested and it doesn't work with the accepted proposal, but works with https://github.com/Expensify/App/pull/45314.

**Comment by Julesssss** [comment] 2024-07-15 12:54
> I will keep working on this trying to solve the other issue https://github.com/Expensify/App/issues/45164

Okay thanks, in the meantime I'll need to switch proposals as this issue is a major blocker for us internally. We can sort out bounties later.

**Comment by Julesssss** [comment] 2024-07-15 12:54
> @Julesssss Tested and it doesn't work with the accepted proposal, but works with #45314.

@QichenZhu could you please go ahead with your proposal? I have just merged @yuwenmemon's PR, so pleasepull main before you branch from it.

**Comment by QichenZhu** [comment] 2024-07-15 12:56
Thanks, @Julesssss! Starting now.

**Comment by Ahmed-Abdella** [comment] 2024-07-15 13:36
> Okay thanks, in the meantime I'll need to switch proposals as this issue is a major blocker for us internally. We can sort out bounties later.

@Julesssss Sure thing. I just couldn't test it on iOS because there was a bug causing an iOS build failure.

**Comment by Julesssss** [comment] 2024-07-15 14:13
Hey @Pujan92, @QichenZhu's [PR](https://github.com/Expensify/App/pull/45400) is ready for testing now/ Let us know if you aren't available. thanks

**Comment by muttmuure** [comment] 2024-07-29 12:47
@Pujan92 can you clarify if we need a regression test?

**Comment by JmillsExpensify** [comment] 2024-07-29 22:19
$250 approved for @Pujan92

**Comment by muttmuure** [comment] 2024-08-06 11:30
Everyone is paid and regression test requested

**Closed by muttmuure** 2024-08-06 11:30 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
