### ISSUE TITLE
[HOLD for payment 2022-12-08] [$1000] Incorrect pasted text on copied HTML snippet reported by @kerupuksambel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12271] opened 2022-10-28 21:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send this HTML snippet to someone  : `<a href="takia.html">asd</a>`
3. Right click on the message and select the option "Copy to clip board" and paste it to either an external text editor or Expensify textbox

## Expected Result:
The pasted text is the same as the copied text

## Actual Result:
The pasted text on the external text editor is only asd while the pasted text on the Expensify textbox is `[asd](https://staging.new.expensify.com/r/takia.html)`

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.21-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198734005-732d98ad-0705-4c1c-9ff2-81ae0bf09688.mp4

https://user-images.githubusercontent.com/43996225/198734012-14442e5a-b09d-4d0e-896c-ea25f7b830b7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @kerupuksambel

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666969406840619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~015b92dc642f298147
- Upwork Job ID: 1595305377206034432

**Comment by Christinadobrzyn** [comment] 2022-11-02 01:41
@kavimuru can you try to reproduce this again to see what we are doing differently?

**Comment by kerupuksambel** [comment] 2022-11-02 02:51
@Christinadobrzyn Could I try to elaborate? My step to generate the error is :
1. Type` <a href="takia.html">asd</a>` in a chat in [staging](https://staging.new.expensify.com/r/68947221)
2. _Copy the code with highlighting the code and pressing Ctrl+C / Cmd+C_ 
3. _Paste it with Ctrl+V / Cmd + V on your text editor._

The bug is remained the same in my side. I also just realized the difference between copying the code from Copy To Clipboard button and using Ctrl/Cmd + C.

**Comment by Christinadobrzyn** [comment] 2022-11-08 02:42
Hi @kerupuksambel! Thank you so much for the insight - testing this: 

Using Copy to Clipboard

1. Type `<a href="takia.html">asd</a>` in a chat in [staging](https://staging.new.expensify.com/r/68947221)
2. Copy the code by clicking the Copy to Clipboard button 
3. Paste it with Ctrl+V / Cmd + V on your text editor.
4. You get `<a href="takia.html">asd</a>` in text editor

Using Ctrl+C / Cmd+C

1. Type `<a href="takia.html">asd</a>` in a chat in [staging](https://staging.new.expensify.com/r/68947221)
2. Copy the code with highlighting the code and pressing Ctrl+C / Cmd+C
3. Paste it with Ctrl+V / Cmd + V on your text editor.
4. You get `asd` in text editor

So the Copy to Clipboard is pasting the `<a href="takia.html">asd</a>` code into text edit whereas the Ctrl+C / Cmd+C & Ctrl+V / Cmd + V is pasting the result of the code `asd`. Interesting! 

I think this might be similar to this issue https://github.com/Expensify/App/issues/10262 - @parasharrajat would you be able to take a peek at this and see if you think it will be fixed with the changes you're working on in https://github.com/Expensify/App/issues/10262

**Comment by parasharrajat** [comment] 2022-11-10 00:33
Investigated this one, it seems like root cause might be same. We are tackling the `SetHTML` function in the other issue. It is good to know on more bug caused by the same `navigator.clipboard.write`. 

@b1tjoy This might be related to https://github.com/Expensify/App/issues/10262.

**Comment by Christinadobrzyn** [comment] 2022-11-10 00:49
Thanks @parasharrajat, I think we should probably hold this until https://github.com/Expensify/App/issues/10262 is resolved to see if that fixes this issue. Let me know if there's a better option.

**Comment by parasharrajat** [comment] 2022-11-10 00:52
Good call @Christinadobrzyn.

**Comment by parasharrajat** [comment] 2022-11-16 00:11
Thanks, @b1tjoy for looking. I will definitely review this proposal beside https://github.com/Expensify/App/issues/10262.

**Comment by Christinadobrzyn** [comment] 2022-11-17 03:07
If we think this was a regression of https://github.com/Expensify/App/pull/11905#issuecomment-1289779832 I think we can remove the hold label and start working on this?

**Comment by Christinadobrzyn** [comment] 2022-11-22 05:31
@deetergp would you be able to lend some insights into if this could be `External` or needs to be `Internal`?

**Comment by deetergp** [comment] 2022-11-22 20:42
@Christinadobrzyn I agree, this can definitely be external.

**Comment by Vishrut19** [comment] 2022-11-23 07:13
Hey Guys ! can I give it a try ?

**Comment by thesahindia** [comment] 2022-11-23 14:22
Great finding @b1tjoy👏

@deetergp, I like @b1tjoy's [proposal](https://github.com/Expensify/App/issues/12271#issuecomment-1312326623)

C+ reviewed 🎀👀🎀

**Comment by thesahindia** [comment] 2022-11-23 14:25
> Hey Guys ! can I give it a try ?

Thanks for showing interest @Vishrut19. You can check other issues with the help wanted label. You can visit [this link](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+label%3A%22Help+Wanted%22).

**Comment by Prottoy2938** [comment] 2022-11-25 04:12
Is this issue still going on? or @b1tjoy 's solution works fine?

**Comment by thesahindia** [comment] 2022-11-25 14:41
> @b1tjoy 's solution works fine?

Yeah, it works fine.

**Comment by thesahindia** [comment] 2022-11-25 14:41
> @deetergp, I like @b1tjoy's [proposal](https://github.com/Expensify/App/issues/12271#issuecomment-1312326623)
> 
> C+ reviewed 🎀👀🎀

Bump @deetergp

**Comment by danieldoglas** [comment] 2022-11-28 15:16
@thesahindia let's move forward with @b1tjoy's proposal.

**Comment by thesahindia** [comment] 2022-11-28 15:39
@Christinadobrzyn, please hire @b1tjoy.

**Comment by JmillsExpensify** [comment] 2022-11-28 19:36
@thesahindia Can you also please assign @b1tjoy to this issue. Thanks!

**Comment by Christinadobrzyn** [comment] 2022-11-29 00:19
Thanks @thesahindia! I hired: 

- @b1tjoy $1000 for the fix 
- @thesahindia $1000 as C+
- @kerupuksambel $250 for reporting 

job posting here - https://www.upwork.com/jobs/~015b92dc642f298147

@thesahindia can you please let me know if the PR is merged in 3 days for the 50% bonus?

**Comment by JmillsExpensify** [comment] 2022-11-29 21:17
2 more days before we exit the 50% bonus period for merged PRs!

**Comment by thesahindia** [comment] 2022-11-29 21:18
The PR got merged.

**Comment by JmillsExpensify** [comment] 2022-11-29 22:06
Oh whoops, I'm flying through too many issues. Thanks!

**Comment by thesahindia** [comment] 2022-12-01 16:06
> The PR that introduced the bug has been identified. Link to the PR:

As mentioned by @b1tjoy, it was a regression from https://github.com/Expensify/App/pull/11905

**Comment by thesahindia** [comment] 2022-12-09 10:16
@Christinadobrzyn, this is ready for payment

**Comment by Christinadobrzyn** [comment] 2022-12-15 04:22
So sorry for the payment delay, I wasn't sure if there was a regression and I was ooo for a bit. Paid and closed the job. 

@b1tjoy $1000 for the fix & $500 bonus (PR in 3 days)
@thesahindia $1000 as C+ & $500 bonus (PR in 3 days)
@kerupuksambel $250 for reporting

**Comment by Christinadobrzyn** [comment] 2022-12-19 07:33
@thesahindia @danieldoglas can you please complete the checkboxes here and close this GH?

https://github.com/Expensify/App/issues/12271#issuecomment-1333984867

**Comment by thesahindia** [comment] 2022-12-19 18:35
>The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/11905

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/11905#issuecomment-1358063814

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1671474832197629

>A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test [here](https://github.com/Expensify/Expensify/issues/250303) Slack chat about this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1671078443556079)

Need help with this one @danieldoglas

**Comment by danieldoglas** [comment] 2023-01-02 14:16
Closing this since regression test was created already

**Closed by danieldoglas** 2023-01-02 14:16 UTC
Labels: External, Engineering, Weekly, Overdue, Bug
