### ISSUE TITLE
[HOLD for payment 2024-06-20] Stop highlighting report mentions in non policy rooms in the Composer

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#41597] opened 2024-05-03 16:38 UTC
**Problem:**
While typing a report mention in the composer in a DM or group chat the mention is highlighted, even though it is not possible to mention a report in this types o chats.

<img width="606" alt="image" src="https://github.com/Expensify/App/assets/5201282/b4a76ea8-93b0-4c07-99dd-a59425f141c8">

**Solution:**
We need to stop applying the markdown style to report mentions in reports that don't belong to a group policy.

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by robertKozik** [comment] 2024-05-06 08:45
Hi @rlinoz! I'll look into it

**Comment by nkdengineer** [comment] 2024-05-06 11:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/942cad969430f17c5477ae519bf6c3508cb761f8/src/hooks/useMarkdownStyle.ts#L52), we apply the ```mentionReport``` style without checking if the report is policyRoom or not.

### What changes do you think we should make in order to solve the problem?
- We should create a new function to check if the typed text matches the [suggestedMentions](https://github.com/Expensify/App/blob/942cad969430f17c5477ae519bf6c3508cb761f8/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L331). 

- For example, assume that the ```suggestedMentions``` contains a few options: ```[announce, admin, room-1, room-2, room-3]``` then if user types ```#room-1```, the typed text is highlighted. If user types ```room-4```, the typed text is not highlighted because there is no option is ```room-4```.

- Here is the implementation:
1. Create a function:
```
function doesRoomExisted(roomName: string, listRoomName: string[]) {
    return listRoomName.includes(roomName);
} 
```
which its inputs is the ```roomName``` and ```listRoomName```, and return the boolean value. In there above example, ```doesRoomExisted('room-1', ['announce', 'admin', 'room-1', 'room-2', 'room-3'])``` returns ```true```

2. Then update [this](https://github.com/Expensify/App/blob/942cad969430f17c5477ae519bf6c3508cb761f8/src/hooks/useMarkdownStyle.ts#L52) to:
```
            mentionReport: doesRoomExisted(message, listRoomName) ? {
                color: theme.mentionText,
                backgroundColor: theme.mentionBG,
            }: { },
```
this step is straightforward so I do not implement the detail. The main idea of this step is we will check if the typed text exists in the list room that can be mentioned. If true, apply the highlight style.


### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment] 2024-05-06 11:35
I updated the [proposal](https://github.com/Expensify/App/issues/41597#issuecomment-2095764625)

**Comment by rlinoz** [comment] 2024-05-06 12:02
Sorry we aligned on Slack that this one should go to Robert since he was the one adding the styling to report mentions.

**Comment by nkdengineer** [comment] 2024-05-06 12:11
@rlinoz I found another related bug: In policy room chat, when typing any room name that does not belong to the policy, the typed text is still highlighted. Then send a message. That message is still highlighted until the API AddComment is successful.

Can you confirm if it is a bug? Thanks

**Comment by robertKozik** [comment] 2024-05-07 08:09
Hi @nkdengineer I think it's not actually a bug - If there is no rrom with such a name, we will send actionable whisper with an option to create it. Checking for the room existance is not a valid one in this case. CMIIW

**Comment by nkdengineer** [comment] 2024-05-07 08:56
> we will send actionable whisper with an option to create it

@robertKozik  This feature is not implemented in staging, right? (So I think It will be handled in the future).

Thanks for your information!

**Comment by robertKozik** [comment] 2024-05-07 09:41
I believe frontend implementation is already merged, only backend part is not yet in staging. But I'm not so up-to-date on it 😄

**Comment by robertKozik** [comment] 2024-05-07 11:46
@rlinoz I've created [draft PR for this one](https://github.com/Expensify/App/pull/41731). I went with more general solution and implement the rule excluding mechanism. Feel free to test and comment - I'll add the remaining screenshots and the rest later today.

**Comment by rlinoz** [comment] 2024-05-29 23:40
Checking if we should close here https://github.com/Expensify/App/issues/42523#issuecomment-2138421943

**Comment by SzymczakJ** [comment] 2024-06-04 14:26
The PR that solved this issue was reverted. I'll be taking care of this issue now 😄

**Comment by SzymczakJ** [comment] 2024-06-06 14:27
Correct. There is a lot going on in `react-native-live-markdown`, so we will have to wait , but I'm pinging `react-native-live-markdown` team to merge this fix ASAP 😄

**Comment by SzymczakJ** [comment] 2024-06-07 12:45
Fix was merged into `react-native-live-markdown` so I'm putting the reverted PR back, but let us merge [bump of react native live markdown in a separate PR](https://github.com/Expensify/App/pull/43255), because it fixes A LOT of other issues. This should get merged pretty easily and in the meantime we can test this PR.

**Comment by SzymczakJ** [comment] 2024-06-10 13:28
`react-native-live-markdown` bump was merged. PR fixing this issue is ready to test and review.

**Comment by JmillsExpensify** [comment] 2024-06-19 21:52
@mollfpr would you like to get us kicked off for the BZ checklist?

**Comment by mollfpr** [comment] 2024-06-22 03:51
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Enter to group chat from the group policy
2. Try typing the report mention (for example `#room-name`)
3. **Verify** that the report mentioned is styled
4. Enter to 1:1 chat which is not part of group policy
5. Try typing report mention (for example `#room-name`)
6. **Verify** that the report mentioned is not styled
7. 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-06-22 17:10
Confirming the payment summary above for $250 for @mollfpr. Regression test is also added, so closing this issue.

**Closed by JmillsExpensify** 2024-06-22 17:10 UTC
Labels: Daily, Improvement, Overdue, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2024-06-24 20:32
Contributor: @mollfpr due $250 via NewDot

**Comment by JmillsExpensify** [comment] 2024-06-25 03:02
$250 approved for @mollfpr
