### ISSUE TITLE
[$500]  Compose - The send button is inactive after deleting text with more than 10,000 characters

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35534] opened 2024-02-01 01:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4257780
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisites:
You may use this site to copy the text
https://www.lipsum.com/feed/html
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Navigate to any conversation
4. Quickly paste 5-6 times text of more than 3000 characters into Compose Box
5. Press Enter until the error about exceeding the limit of 10000 characters appears
6. Highlight the inserted text
7. Enter any message

## Expected Result:
The send message button should become active after deleting text containing more than 10,000 characters

## Actual Result:
The send message button is inactive after deleting text with more than 10,000 characters

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/354a15c2-5c19-45ac-b137-6f0038d19dea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a5065c30f70c29b</li>
        <li>Upwork Job ID: 1752871278488870912</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-01 01:48
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by jeremy-croff** [comment] 2024-02-01 02:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We run into an issue where the use cannot send a message because the input thinks it's disabled

### What is the root cause of that problem?
A performance optimization was implemented here:
https://github.com/Expensify/App/blob/dc3c39609700909cedea4655bad13900d6305e69/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L268 
That prevents the setIsCommentEmpty callback from updating unnecessarily if it didn't change.

We are stuck in an use case where isCommentEmpty is true here: https://github.com/Expensify/App/blob/dc3c39609700909cedea4655bad13900d6305e69/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L341

While there's text in the input, and when you keep on typing, it fails the "changed" check to actually call setIsCommentEmpty with the correct state.

The root cause is that we use a debounced method for max length check: https://github.com/Expensify/App/blob/dc3c39609700909cedea4655bad13900d6305e69/src/hooks/useHandleExceedMaxCommentLength.ts#L22 and it allows us to hit "send" before we actually finished validating the max length. Which falsy  sets the comment state as empty here https://github.com/Expensify/App/blob/dc3c39609700909cedea4655bad13900d6305e69/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L351 
Conflicting with the change check down stream to update isEmpty back to false.


### What changes do you think we should make in order to solve the problem?
We can remove the performance optimization, so that it will reupdate the empty state on text change.

Alternatively, if we want to keep the performance optimization, we can pass the isEmpty state as a prop to ComposerWithSuggestions, and update it only if the current state is different from the prop.



### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment] 2024-02-02 22:13
Still reviewing the proposals.

**Comment by allroundexperts** [comment] 2024-02-05 21:39
Reviewing again now!

**Comment by allroundexperts** [comment] 2024-02-05 22:41
Thanks for your proposal @jeremy-croff. I don't think we should remove the optimisation in place. The alternate solution that you've suggested doesn't seem ideal to me as well since we will be having a useless render cycle ie `isCommentEmpty` set as `true`, and then from the child, being set as `false`.

I like @dukenv0307's [proposal](https://github.com/Expensify/App/issues/35534#issuecomment-1920382010) of making the check inside `handleSendMessage` rely on the length of the message synchronously. That would prevent us from removing any optimisation.

**Comment by allroundexperts** [comment] 2024-02-05 22:41
Thanks for your proposal @jeremy-croff. I don't think we should remove the optimisation in place. The alternate solution that you've suggested doesn't seem ideal to me as well since we will be having a useless render cycle ie `isCommentEmpty` set as `true`, and then from the child, being set as `false`.

I like @dukenv0307's [proposal](https://github.com/Expensify/App/issues/35534#issuecomment-1920382010) of making the check inside `handleSendMessage` rely on the length of the message synchronously. That would prevent us from removing any optimisation. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by jeremy-croff** [comment] 2024-02-05 23:43
> Let's 

Good analysis

**Comment by mallenexpensify** [comment] 2024-02-06 23:16
@youssef-lr this one slipped through the cracks.  I didn't add it to a project and I'm unsure of the value of implementing the fix, it's seems rare that posts with 10k added/removed will happen.  What do you think? 

@dukenv0307 will you proposed fix help in other instances outside of just add/remove 10k characters?

**Comment by youssef-lr** [comment] 2024-02-07 22:13
@mallenexpensify yeah I'm with you on this, I don't think this is worth fixing right now, especially that there is easily a workaround, for example in the recording below I managed to easily send another comment after removing the 10k text.

https://github.com/Expensify/App/assets/9680864/1d8de98e-64fc-4598-925b-9d01719f9795

**Comment by jeremy-croff** [comment] 2024-02-08 13:37
> @mallenexpensify yeah I'm with you on this, I don't think this is worth fixing right now, especially that there is easily a workaround, for example in the recording below I managed to easily send another comment after removing the 10k text.
> 
>  Screen.Recording.2024-02-07.at.23.11.41.mov

It seems this  recording doesn't reproduce the bug mention in OP. The bug occurs if you pasted 10k+ text, hit send immediately, then clear it and type before the text limit debounce happens. Then you cannot send your text input anymore. The only way to get out of that state is to clear your message and start over. It's edge case for sure, but is a clear bug that's identified and fixable, even if it just improves one customers experience down the line. If we stack ranked it, it would be low priority for sure because of the difficulty to get in this state.

**Comment by mallenexpensify** [comment] 2024-02-09 19:48
Thanks for the context @dukenv0307 and @jeremy-croff .  @allroundexperts , can you please review and chime in? 

> Expand the composer to full size

@dukenv0307 can you... err... expand on this? Or outline reproducible steps?  Curious how frequently this might happen

> IMO
> (Rare occurence x big impact when occuring) = worth fixing
> (Rare occurence x low impact when occuring) = not worth

@dukenv0307 I like this framing.

**Comment by allroundexperts** [comment] 2024-02-09 20:26
@mallenexpensify In my opinion, if something is clearly faulty in the code (like the case here), we should fix it regardless if its small or large. Although, I'd agree that someone would get into this state rarely.

**Comment by mallenexpensify** [comment] 2024-02-09 22:41
Thanks @allroundexperts ,   We started the contributor program by fixing EVERY bug we could find, now we're focusing on bugs that we can assign to our roadmap projects.  For this one, the likely project would be #vip-vsb, and with so many issues already in/on that project, I'm unsure the fix here would be viewed as valuable enough to add.

**Comment by mallenexpensify** [comment] 2024-02-12 18:13
Thanks @dukenv0307 , I'm pausing for a sec, trying to think of the next best step here, more in a day or two.

**Comment by mvtglobally** [comment] 2024-02-13 04:58
Issue not reproducible during KI retests. (First week)

**Closed** 2024-02-13 22:46 UTC
Labels: External, Daily, Help Wanted, Bug
