### ISSUE TITLE
[HOLD for Payment 2024-09-25] [Search v2.1][$250] The “Enter” key on the search page randomly opens the workspace switcher or the RHP 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49080] opened 2024-09-12 12:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726117464938269

## Action Performed:
1. Go to the search page
2. Click Enter
3. Observe the workspace switcher opens
4. Click out of the workspace switcher
5. Click Chats
6. Click Expenses
7. Click Outstanding
8. Click Enter
9. Observe the RHP opens. 

## Expected Result:
The workspace switcher or the RHP does not open when clicking Enter on the search page. 

## Actual Result:
The workspace switcher and RHP open when clicking Enter

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/79d7e623-c1bb-459e-98b1-2edee2492330

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/1427a6dd-b389-41fa-a61c-c186d3bc5c9a

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834395341977846523</li>
        <li>Upwork Job ID: 1834395341977846523</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103975534</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by suneox** [comment] 2024-09-12 15:11
I think the expected behavior at step 6 is that the report detail page should not be shown, due to the lack of context to select which expense from the list.

**Comment by trjExpensify** [comment] 2024-09-13 00:09
Hm, I'm not sure about this actually. Why would we open anything at all when Enter is clicked? We don't do that on other pages. @luacmartins am I missing something on why the Enter key is opening the workspace switcher here?

**Comment by luacmartins** [comment] 2024-09-13 00:11
My best guess is that we have focus trap on some button and we're triggering that onPress behavior when pressing enter

**Comment by trjExpensify** [comment] 2024-09-13 00:54
Yeah, so I think the expected behaviour here is that the workspace switcher nor the expense RHP opens when you randomly click Enter on the search page.

**Comment by bernhardoj** [comment] 2024-09-13 19:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing enter while on the search page opens the workspace switcher page.

### What is the root cause of that problem?
When we open the search page, the focus trap for the search bottom tab screen is activated which will focus on the workspace switcher page. So, pressing enter will open the ws switcher page. But actually, we have a code to disable the focus trap for bottom tab screens.
https://github.com/Expensify/App/blob/50cc54846361bd360882b7bd213d5a41d25c929b/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L18-L25

However, the bottom tab screens don't include the search bottom tab screen yet.
https://github.com/Expensify/App/blob/4039a12cfb06f2bf47d11f86a6da6482e61fc05a/src/components/FocusTrap/BOTTOM_TAB_SCREENS.ts#L4

### What changes do you think we should make in order to solve the problem?

Add the search bottom tab screen to the list.
```
const BOTTOM_TAB_SCREENS = [SCREENS.HOME, SCREENS.SETTINGS.ROOT, NAVIGATORS.BOTTOM_TAB_NAVIGATOR, SCREENS.SEARCH.BOTTOM_TAB];
```

**Comment by ikevin127** [comment] 2024-09-14 03:12
@bernhardoj Thanks for your proposal. While your solution does seem to fix the fact that `Enter` opens the workspace switcher, we're still left with the issue of the RHP opening (see video below).


https://github.com/user-attachments/assets/6123ba72-d2d8-4416-a5b3-d2f0abda738b

**Comment by bernhardoj** [comment] 2024-09-14 16:33
Oh, I was trying to repro it on the Chats type but no success. Turns out it's reproducible on the Expenses and Invoices tab. Updated my proposal!

**Comment by ikevin127** [comment] 2024-09-14 23:57
🎉 Thanks for the update! @bernhardoj's [updated proposal](https://github.com/Expensify/App/issues/49080#issuecomment-2349937236) looks good to me - the RCA is correct and the updated solution fixes the issue according to the **Expected result** 👍 

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-09-16 03:40
PR is ready

cc: @ikevin127

**Comment by ikevin127** [comment] 2024-09-18 23:25
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-09-25]** according to today's production deploy from [Deploy Checklist: New Expensify 2024-09-17](https://github.com/Expensify/App/issues/49356#top) which was shipped to production today.

cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-09-18 23:52
Thanks!

**Comment by trjExpensify** [comment] 2024-09-25 16:22
Payment summary as follows: 

- $250 to @ikevin127 for the C+ review (paid!)
- $250 to @bernhardoj for the fix (go ahead and request)

Closing!

**Closed by trjExpensify** 2024-09-25 16:22 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-09-25 16:42
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-25 17:27
$250 approved for @bernhardoj
