### ISSUE TITLE
[$250] Android - Chat - If we alter transaction details, new message green line disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41211] opened 2024-04-29 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4522562
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report with more than one expense
3. Tap on a expense
4. Enter merchant and save it
5. Mark as unread the system message displayed for entering merchant
6. Note green line with new message tag above system message
7. Now edit the merchant and save it
8. Note green line with new message tag above system message disappears

## Expected Result:
In transaction details page, after mark as unread, if we alter transaction details, new message green line must not disappear

## Actual Result:
In transaction details page, after mark as unread, if we alter transaction details, new message green line disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f65f916e-15b8-4346-b18b-16895f7e29c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152b49882e3aa4a66</li>
        <li>Upwork Job ID: 1792850190027993088</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102600483</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment] 2024-04-29 14:02
@dylanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's bug and can be handled by external contributors

**Comment by dylanexpensify** [comment] 2024-05-01 07:35
Reviewing today!

**Comment by dylanexpensify** [comment] 2024-05-07 11:20
Trying again today

**Comment by dylanexpensify** [comment] 2024-05-14 12:30
Couldn't repro. @lanitochka17 can you confirm if you can?

**Comment by dylanexpensify** [comment] 2024-05-21 09:29
made external!

**Comment by dylanexpensify** [comment] 2024-05-21 19:39
@rushatgabhane to review!

**Comment by rushatgabhane** [comment] 2024-05-22 08:13
@dylanexpensify @tienifr why is this a bug? after editing transaction details, we come back to the IOU page and it clears the unread marker because we're on the page.

What do you think?

**Comment by rushatgabhane** [comment] 2024-05-22 08:13
I think we can close this issue

**Comment by dylanexpensify** [comment] 2024-05-29 06:34
@rushatgabhane thoughts [on this](https://github.com/Expensify/App/issues/41211#issuecomment-2124471098)?

**Comment by rushatgabhane** [comment] 2024-06-04 21:24
https://github.com/Expensify/App/issues/41211#issuecomment-2122370121
 
@tienifr 's proposal looks good 🎀👀🎀

**Comment by dylanexpensify** [comment] 2024-06-17 18:24
Ongoing!

**Comment by rushatgabhane** [comment] 2024-07-17 08:12
PR on production

**Comment by rushatgabhane** [comment] 2024-07-23 01:00
PR on production last week. Payment due today.

cc: @dylanexpensify could you please attach payment summary 🙇

**Comment by JmillsExpensify** [comment] 2024-07-23 02:24
Do we need a regression test for this one?

**Comment by rushatgabhane** [comment] 2024-07-25 18:10
This was caught by QA and is a very minor bug. So I think not needed.


But in case you disagree -


1. Tap on a report with more than one expense
2. Tap on a expense
3. Enter merchant and save it
4. Mark as unread the system message displayed for entering merchant
5. Note green line with new message tag above system message
6. Now edit the merchant and save it
7. Verify the green line with new message tag above system message does not disappear

**Comment by JmillsExpensify** [comment] 2024-07-25 22:09
Bump on that last comment

**Comment by mallenexpensify** [comment] 2024-07-26 16:59
Contributor: @tienifr due $250 via NewDot 
Contributor+: @rushatgabhane due $250 via NewDot

TestRail GH (I prefer to create them then let QA decide what to do with them, if anything (cuz we have the option to check monthly for edge cases))

**Closed by mallenexpensify** 2024-07-26 16:59 UTC
Labels: External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-07-29 22:39
$250 approved for @rushatgabhane

**Comment by JmillsExpensify** [comment] 2024-08-14 18:39
$250 approved for @tienifr
