### ISSUE TITLE
[HOLD for payment 2023-09-07] [$500] [HOLD for payment 2023-09-06] Web - App crashes for user B when user A deletes IOU request while both users opens the same request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26251] opened 2023-08-29 19:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Click on FAB on user A
2. Click on request money and send request to user B
3. Open the same request on both user A and user B
4. Delete the request from user A side

## Expected Result:
The app should handle the deleted request by showing the "Hmm...it's not here" message

## Actual Result:
 The app crashes on user B side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f253722e-4c03-4920-806c-46a2ec11da83

![Screenshot 2023-08-29 230106](https://github.com/Expensify/App/assets/93399543/52a896ff-c2e4-425d-9ff2-74a6f3fabed5)

https://github.com/Expensify/App/assets/93399543/694aa51d-43c8-4518-895f-441c21c3dea4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693338346189599
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f5cb1b3e1c47695</li>
        <li>Upwork Job ID: 1696999715134431232</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-08-29 20:32
I can't reproduce this issue

https://github.com/Expensify/App/assets/22219519/abe619bc-721a-4b0c-a491-ec67cdf108f7

**Comment by luacmartins** [comment] 2023-08-29 21:14
Fix is merged and being CPed. Removing blocker label. Gonna add Bug label to process report bonus payment.

**Comment by kevinksullivan** [comment] 2023-08-30 21:34
adding external for the upwork automation

**Comment by kevinksullivan** [comment] 2023-08-30 21:36
Hi @jo-ui can you submit an app for this job so I can pay out reporting?

https://www.upwork.com/jobs/~012f5cb1b3e1c47695

**Comment by jo-ui** [comment] 2023-08-31 03:57
@kevinksullivan I've applied for the job on upwork.

**Comment by kevinksullivan** [comment] 2023-09-06 21:59
accepted offer @jo-ui . Let me know when you've accepted and I'll pay this out.

**Comment by jo-ui** [comment] 2023-09-07 02:20
@kevinksullivan I've accepted the offer.

**Comment by kevinksullivan** [comment] 2023-09-07 22:05
All set

**Closed by kevinksullivan** 2023-09-07 22:05 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
