### ISSUE TITLE
Workspace - No message is visible for the admin about the flagged invite message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42540] opened 2024-05-23 16:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #41622 

**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** n (New Feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Admin: Log in with an expensifail account
2. Admin: Create a new workspace
3. Admin: Invite a Gmail account to the workspace with "MODERATION_TEST" invite message
4. Member: Log in as the invited Gmail account
5. Member: Navigate to the workspace chat
6. Member: Right click on the invite message and click on "Flag as offensive"
7. Member: Choose any reason
8. Admin: Navigate to the workspace chat with the member
## Expected Result:
The admin should receive a message about it.

## Actual Result:
No message is visible for the admin about the flagged invite message.

## Workaround:
none

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/837fbaa5-8a00-4d51-8c24-875a55852e69

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-05-23 16:53
@blimpich FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by blimpich** [comment] 2024-05-23 18:24
I think this shouldn't be a deploy blocker because its largely a new feature not a regression, but also I think the fact that its not working is related to our recent fires. This feature [was dependent on an Auth PR](https://github.com/Expensify/Expensify/issues/389347#issuecomment-2116230193) that I think got reverted. So this probably doesn't work because of that.

@dangrous @jasperhuangg can you confirm that this is a result of the Auth PR revert? And if so @dangrous could you pick this up and close it out once you can confirm that all the requisite code is deployed that it isn't an issue?

**Comment by dangrous** [comment] 2024-05-23 21:34
Actually, not due to the revert! It's due to https://github.com/Expensify/Auth/pull/10829 - we removed the admin (flaggee) whisper. So this is working as expected. Apologies on not updating the testing steps.

(Let me know if I'm interpreting the bug right @blimpich!)

**Comment by blimpich** [comment] 2024-05-23 22:12
Its a feature! Not a 🐛! My favorite 🙂

That makes sense to me, lets close this out

**Closed by blimpich** 2024-05-23 22:12 UTC
Labels: Engineering, Daily, Bug
