### ISSUE TITLE
[Hold for payment: 2024-09-24] [$250] Task - Unable to remove task description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46111] opened 2024-07-24 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4760280
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM
3. Create a task with description
4. Go to task report
5. Click Description
6. Remove the description and save it

## Expected Result:
User will be able to remove the task description

## Actual Result:
User is unable to remove the task description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bef37746-51ad-4711-aca8-8d45abf76db1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01059741d391e013aa</li>
        <li>Upwork Job ID: 1823259419206003933</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103704842</li>
<li>FitseTLT | Contributor | 103704845</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment] 2024-07-24 13:29
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-24 13:30
We think that this bug might be related to #vip-vsp

**Comment by etCoderDysto** [comment] 2024-07-24 13:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to remove task description
### What is the root cause of that problem?
When description is empty string we are assigning the old description value (`report.description`) to `newDescription`. This will prevent new description from being assigned `undefined` when user edits task title that has an existing description, and remove existing description in the process. This is because `description` is `undefined` when user edits task title.  But when the user removes existing description, the old description value (`report.description`) is assigned to `newDescription` since empty string is regarded as false when we use `?` instead of `??`.
https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/actions/Task.ts#L502
### What changes do you think we should make in order to solve the problem?
We should assign `description` to `newDescription` when `description` is an empty string and assign `report.description` when `description` is `undefined` 
```javascript
    const newDescription = description ? ReportUtils.getParsedComment(description) : description ?? report.description;
```

### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2024-07-24 14:16
Will repro today!

**Comment by dylanexpensify** [comment] 2024-08-05 09:41
reviewing today!

**Comment by dylanexpensify** [comment] 2024-08-07 09:41
Confirming behavior

**Comment by dylanexpensify** [comment] 2024-08-13 07:24
Forgot to hit external!

**Comment by FitseTLT** [comment] 2024-08-14 18:58
> Thanks for proposals everyone 🙏 , all you guys have the correct RCA!
> 
> Coming to solution:
> 
> @etCoderDysto I feel your solution is a little over-engineering and not a correct way to approach.
> 
> @FitseTLT , though your solution would solve this but the `description` would always be of string type and that check is not needed as we only call `editTask` for editing description when we have one (some value / empty string).
> 
> With that said, lets go with @eucool 's [proposal](https://github.com/Expensify/App/issues/46111#issuecomment-2287969831) here, their solution seems more appropriate for this bug
> 
> 🎀👀🎀 C+ reviewed

No U totally misunderstood the situation here @allgandalf we use the function to set `title` too that's why we need the check
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/pages/tasks/TaskTitlePage.tsx#L52-L53

**Comment by etCoderDysto** [comment] 2024-08-14 19:01
@allgandalf we use `editTask` action when editing task title and task description. While editing title, `undefined` for `description` field, and if don't fall back to report.description the description will be removed. I have stated this in my [proposal](https://github.com/Expensify/App/issues/46111#issuecomment-2247965154)

I will attache a video

https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/actions/Task.ts#L494-L503

**Comment by etCoderDysto** [comment] 2024-08-14 19:03
> thanks for mentioning that @etCoderDysto , I will re-review the proposals tomorrow morning

Great!

**Comment by deetergp** [comment] 2024-08-21 08:41
Any updates @allgandalf?

**Comment by etCoderDysto** [comment] 2024-08-21 13:39
@allgandalf @FitseTLT's last edit and [my proposal](https://github.com/Expensify/App/issues/46111#issuecomment-2247965154) came at the same time (4:39). And my propsal has details of how description field becomes undefined when editing title. This is to ask if having a clear, and detailed RCA would make my proposal a better choice. 
Thanks!

**Comment by etCoderDysto** [comment] 2024-08-25 19:40
@allgandalf can you please comment on my question [here](https://github.com/Expensify/App/issues/46111#issuecomment-2302088630).

Thanks!

**Comment by dylanexpensify** [comment] 2024-09-18 10:45
TY!

**Comment by dylanexpensify** [comment] 2024-09-25 10:45
Nice will pay today!

**Comment by FitseTLT** [comment] 2024-10-03 12:03
@dylanexpensify payment Ooooverdue here

**Comment by dylanexpensify** [comment] 2024-10-07 12:21
Payment summary:

Contributor: @FitseTLT $250 via Upwork
Contributor+: @allgandalf $250 via Upwork

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-10-07 12:21
Paid!

**Closed by dylanexpensify** 2024-10-07 12:21 UTC
Labels: Reviewing, External, Weekly, Bug
