### ISSUE TITLE
[HOLD for #10273] Login - Password field becomes hidden after entering wrong 2FA code

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10526] opened 2022-08-24 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test app
2. In the log in screen enter an account that has 2FA enabled
3. Enter the correct password in the password field
4. Enter an incorrect 2FA code in the code field.
5. Verify you're unable to log in and a friendly message about an incorrect field is displayed
6. Select the Password field
7. Try to make it visible with a swipe

## Expected Result:
The Password field stays visible and the user is able to select it.

## Actual Result:
The Password field becomes hidden after trying to log in with the wrong 2FA code.
Unable to make the Password field visible with a swipe.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS 

**Version Number:** 1.1.89.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/186439006-93a1c499-77b8-4882-a3b6-21092c2fb8b3.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2022-08-29 08:44
@roryabraham - Without digging too deep, should this be held as a part of the overall keyboard improvements issue?

**Comment by bfitzexpensify** [comment] 2022-08-30 10:42
I'll update this to hold and subscribe to that issue, but I'm having trouble finding it - mind sharing a link @AndrewGable / @roryabraham?

**Comment by roryabraham** [comment] 2022-08-30 11:21
https://github.com/Expensify/App/issues/10273

**Comment by bfitzexpensify** [comment] 2022-09-08 11:48
Adding Reviewing label to stop this going overdue - I'm subscribed to https://github.com/Expensify/App/issues/10273 and I'll take this off hold when that's complete

**Comment by mvtglobally** [comment] 2022-09-13 04:33
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2022-09-19 10:05
Reassigning this since I'm heading ooo for 2 weeks

**Comment by mvtglobally** [comment] 2022-09-20 05:06
Issue not reproducible during KI retests. (Second week)

**Comment by kevinksullivan** [comment] 2022-09-21 21:51
Not reproducible for two weeks so going to close out.

**Closed by kevinksullivan** 2022-09-21 21:51 UTC
Labels: Reviewing, External, Engineering, Monthly, Planning
