### ISSUE TITLE
Subscribe state is not displayed correctly on the Profile page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22391] opened 2023-07-07 03:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out if you're signed in
2. Sing into an account that has a personal subscription
3. Setting > profile (don't click the avatar, but click the profile text item)
4. Confirm that you don't have a message that says you're a subscriber
5. Go back to the setting page and click the avatar
6. Confirm that you have a message that says you're a subscriber
7. Once you click the avatar, even if you click profile text to the profile page, the message shows up correctly.
## Expected Result: 
After logging in and clicking avatar, you should see the subscribe proof message
## Actual Result: 
For the specific flow described above, the message is not shown.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction (don't have personal subscription)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hayata-suenaga 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688598402087229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-07-07 19:07
Asking some questions to test here - https://expensify.slack.com/archives/C049HHMV9SM/p1688756803630889?thread_ts=1688598402.087229&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-07-10 22:47
I can't reproduce - looks like it was fixed - closing based on - https://expensify.slack.com/archives/C049HHMV9SM/p1689028566376659?thread_ts=1688598402.087229&cid=C049HHMV9SM

**Closed by Christinadobrzyn** 2023-07-10 22:47 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
