### ISSUE TITLE
[HOLD] CRITICAL: reportAction chain is broken in rooms and expense reports

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42214] opened 2024-05-15 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

`reportActions` continue to break `getOlderActions` under specific circumstances, which we need to fix holistically

## What is the impact of this on end-users?
List specific user experiences that will be improved by solving this problem e.g. app boot time, time to for some interaction to complete, etc.

If `getOlderActions` fails, we do not load the full chat history or expense report history, and the chat history flickers infinitely: 

![Image](https://github.com/Expensify/App/assets/46995600/c7ddc574-5dad-4c54-af9a-400b636fd7f2)

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

I've reported it here: https://expensify.slack.com/archives/C05LX9D6E07/p1715709384419139?thread_ts=1715699398.771909&cid=C05LX9D6E07

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

@janicduplessis is working on a PR here which we believe will fix all known issues: https://github.com/Expensify/App/pull/41962 

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by muttmuure** [comment] 2024-05-21 09:58
Still in need of a fix: 

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/323f0e53-57eb-437c-a5f7-08029d96a0a8">

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/8725c40b-a3be-4a95-99ce-4d5e486201f4">

**Comment by roryabraham** [comment] 2024-05-23 20:26
This is essentially a dupe of https://github.com/Expensify/App/issues/41254 btw, so I'm making both `CRITICAL` and putting this one on HOLD since Janic is also assigned to the other one and we're working together on it.

**Comment by roryabraham** [comment] 2024-05-29 22:35
Remains tied for my top priority, still on HOLD. Updates [in slack](https://expensify.slack.com/archives/C05LX9D6E07/p1714656403682529)

**Comment by roryabraham** [comment] 2024-06-11 00:28
Recent activity in https://github.com/Expensify/App/pull/41962, latest updates starting [here](https://expensify.slack.com/archives/C05LX9D6E07/p1718046651127819?thread_ts=1714656403.682529&cid=C05LX9D6E07)

**Comment by muttmuure** [comment] 2024-07-05 15:03
Not overdue

**Closed** 2024-07-11 09:13 UTC
Labels: Reviewing, Engineering, Weekly
