### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Tags - After deleting a Tag, the select button is not showing the correct amount

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42271] opened 2024-05-16 11:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/42086
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the New Expensify App
2. Sign into a valid account
3. Click on WS > Tags (Enable if needed)
4. Add a couple of tags (Two are fine)
5. Select the two tags (Notice it says 2 are selected)
6. Delete one of the tags
7. Add a new tag quickly so there are 2 again
8. Select "All" button to select both tags

## Expected Result:
User expects the correct number of tags to be shown in the selected area

## Actual Result:
The incorrect number of tags is shown, "3 selected" is shown instead of "2 selected"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b32af56a-68eb-4d4a-b209-c6b2c953bfe1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010953527677d8e414</li>
        <li>Upwork Job ID: 1791581466256613376</li>
        <li>Last Price Increase: 2024-05-17</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by izarutskaya** [comment] 2024-05-16 11:11
We think this issue might be related to the #collect project.

**Comment by RandikaSilva** [comment] 2024-05-18 21:53
### Proposal: Fix for Incorrect Tag Count After Deletion

**Overview:**
The current issue arises because tags pending deletion are still considered in the selection logic, leading to an incorrect tag count.

**Technical Explanation:**
To address this issue, I will modify the `toggleAllTags` function to exclude tags that have a `pendingAction` set to `CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE`.

**Proposed Code Change:**
The revised `toggleAllTags` function will look as follows:
```javascript
const toggleAllTags = () => {
    const isAllSelected = tagList.every((tag) => selectedTags[tag.value] && tag.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE);
    setSelectedTags(isAllSelected ? {} : Object.fromEntries(tagList.filter(tag => tag.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE).map((item) => [item.value, true])));
};
```

>[!NOTE]
>This update ensures that tags pending deletion are not considered when determining if all tags are selected and when toggling all tags. I recommend applying the same correction to other pages.

**After changes done:**

https://github.com/Expensify/App/assets/52340920/52841c72-f449-4707-8970-a9748800007c

**Comment by RandikaSilva** [comment] 2024-05-18 22:03
Contributor details
Expensify account email: <mlasitharandika@gmail.com>
Upwork Profile Link: <[Upwork Profile](https://www.upwork.com/freelancers/~01b82526e9f84143a7)>

**Comment by stephanieelliott** [comment] 2024-05-21 23:56
Hey @Krishna2323, can you update on when we can expect a PR?

**Comment by stephanieelliott** [comment] 2024-05-29 07:35
PR was merged earlier today

**Comment by stephanieelliott** [comment] 2024-06-04 00:00
Hey @thesahindia can you please complete the BZ checklist?

**Comment by stephanieelliott** [comment] 2024-06-04 00:03
Summarizing payment on this issue: 

 - Contributor: @Krishna2323 $250 via Upwork - PAID 
 - Contributor+: @thesahindia $250 via NewDot - please request 
 
 Upwork job is here: https://www.upwork.com/jobs/~010953527677d8e414

**Comment by stephanieelliott** [comment] 2024-06-07 07:11
Thanks @thesahindia! Issue for regression test created here: https://github.com/Expensify/Expensify/issues/402937

**Closed by stephanieelliott** 2024-06-07 07:11 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-17 17:49
$250 approved for @thesahindia
