### ISSUE TITLE
[HOLD for payment 2023-12-04] [$500] Workspace - Long workspace name is not truncated in room details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30725] opened 2023-11-01 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.94-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace and give it a long name
3. Go to #announce
4. Click on the room header

## Expected Result:
The workspace name will be truncated as it is too long to fit the screen

## Actual Result:
The workspace name is not truncated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/60192c71-ddeb-46fd-99a4-81b6b8da369c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01abbbecc2ef5a40ec</li>
        <li>Upwork Job ID: 1719768973795090432</li>
        <li>Last Price Increase: 2023-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>saranshbalyan-1234 | Contributor | 27700639</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by ATG-Tamim** [comment] 2023-11-01 21:24
**Proposal: Workspace Name Truncation Issue Resolution**

---

**Issue Description:**
The issue at hand involves the incorrect truncation of long workspace names within the #announce room in the Expensify application. When workspace names exceed the available screen space, they are not being adequately truncated, leading to a display problem.

**Proposed Solution:**
To resolve this issue and enhance the user experience, the following solution is proposed:

1. **Limit Display Length:** We will establish a maximum character limit for displaying workspace names in the #announce room. This limit will be determined based on the available space within the user interface.

2. **Workspace Name Length Check:** Before displaying a workspace name in the #announce room, we will perform a length check to ascertain whether it exceeds the character limit.

3. **Truncate Long Names:** In cases where a workspace name exceeds the character limit, we will implement a truncation mechanism to ensure it fits within the defined space. An ellipsis (...) will be added to indicate that the name has been truncated.

4. **Tooltip or Hover Feature:** To provide users with access to the complete workspace name, we will introduce a tooltip or hover feature. When users hover over a truncated name, a tooltip will display the full name, ensuring they have the complete information.

5. **Responsive Design:** We will ensure that the truncation and tooltip features are fully responsive and function effectively across a variety of devices and screen sizes.

**Testing:**
Thorough testing of the proposed solution will be conducted to ensure that workspace names are correctly truncated and that the tooltip or hover feature functions as intended.

**Expected Results:**
Upon the successful implementation of this solution, workspace names in the #announce room will be accurately truncated when they exceed the character limit. Users will also have access to the full workspace name via the tooltip or hover feature, enhancing the user experience.

By addressing this issue, we aim to improve the visual management of workspace names, providing users with a more user-friendly and responsive interface.

Please note that the final code implementation will be carried out by the development team following the acceptance of this proposal.

**Comment by ATG-Tamim** [comment] 2023-11-01 21:27
Contributor details
Your Expensify account email: at.ahmad.tamim@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fdc2a3e4c9df7db9

**Comment by yatinj30** [comment] 2023-11-02 06:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a work space name is too long, it is not truncated in the room details page.

### What is the root cause of that problem?
We are using <PressableWithoutFeedback> component to display the work space name. Inside that, we didn't provide style to truncate the text. 

### What changes do you think we should make in order to solve the problem?
We can provide style to <PressableWithoutFeedback> component that truncate the too long text.

### What alternative solutions did you explore? (Optional)
- After truncating the work space name, we should provide a hover option. So, by hovering on it, we can see the full workspace name.
- Another option is there, we are not going to show the workspace name at all. Instead, we can show any emoji or image, by hovering on it, it should display the full-name in nice animated pop-up on the same place.

**Comment by yatinj30** [comment] 2023-11-02 06:05
Contributor details
Your Expensify account email: yatinj.sutariya30@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/yatinjsutariya

**Comment by szulqarnain** [comment] 2023-11-02 07:09
### Proposal

The current issue revolves around the non-truncation of lengthy workspace names on the room details page. The root cause lies in the absence of a text truncation style within the component responsible for displaying workspace names.

### **Proposed Solution:**

- To address this, we propose implementing a style for the component that truncates excessively long workspace names. Additionally, we can enhance the user experience through two alternative solutions:

- Hover Option with Full Name Display: After truncation, introduce a hover option that reveals the complete workspace name when users hover over it.

- Emoji/Image Representation: Instead of displaying the full workspace name, consider using an emoji or image. Upon hovering, trigger a visually appealing animated pop-up revealing the complete name.

- This multi-faceted approach aims to not only resolve the truncation issue but also adds user-friendly features for an improved interface.

**Comment by szulqarnain** [comment] 2023-11-02 07:11
Contributor details
Your Expensify account email: szulqarnain143@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/zulqarnainh13

**Comment by DylanDylann** [comment] 2023-11-02 08:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Workspace - Long workspace name is not truncated in room details page

### What is the root cause of that problem?
- We are not applying ```styles.w100``` to the ```PressableWithoutFeedback``` when displaying ```chatRoomSubtitle```  as we did in other sections
https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/ReportDetailsPage.js#L216

### What changes do you think we should make in order to solve the problem?
- **Firstly**, we need to apply ```styles.w100``` to the ```PressableWithoutFeedback``` as we did in other sections to display the ```Ellipsis``` when the text is too long.
- **Secondly**, we need to wrap the ```chatRoomSubtitle``` inside the [DisplayNames](https://github.com/Expensify/App/blob/main/src/components/DisplayNames/index.js) component with ```tooltipEnabled: true``` to display all the text when hovering over the Ellipsis.
- **Thirdly**, need to apply the max length error when user input more than characters. This is implementing in [other PR](https://github.com/Expensify/App/issues/1864)
- **Fourthly** (**important**), we already have the component called [ParentNavigationSubtitle](https://github.com/Expensify/App/blob/main/src/components/ParentNavigationSubtitle.js) that we used to navigate user to the parent report. But this one and the ```chatRoomSubtitle``` are using separately however both of them navigate user to other screens. So i think we should handle case ```chatRoomSubtitle``` in  ```ParentNavigationSubtitle``` for consistency and reducing duplicate logic. For example, we can update:
https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/pages/ReportDetailsPage.js#L215-L235
to
```
  <ParentNavigationSubtitle
                                    parentNavigationSubtitleData={parentNavigationSubtitleData}
                                    parentReportID={props.report.parentReportID}
                                    pressableStyles={[styles.mt1, styles.mw100]}
                                />
```
In [ParentNavigationSubtitle](https://github.com/Expensify/App/blob/main/src/components/ParentNavigationSubtitle.js), we will handle all the case the display the subtitle properly
### What alternative solutions did you explore? (Optional)
- NA

**Comment by trjExpensify** [comment] 2023-11-03 11:51
👋 @robertKozik can you review the proposals, please? Thanks!

**Comment by trjExpensify** [comment] 2023-11-06 11:43
No change from Friday, Melv. Awaiting proposal reviews from @robertKozik.

**Comment by robertKozik** [comment] 2023-11-09 12:21
@DylanDylann Could you provide a little more details about extending the `ParentNavigationSubtitle` implementation? I'm worried about getting this component too complicated after implementing handling of new cases

**Comment by DylanDylann** [comment] 2023-11-09 18:27
@robertKozik Currently, the ```ParentNavigationSubtitle``` is just handle case ```!_.isEmpty(parentNavigationSubtitleData) && isMoneyRequestReport```, and does not contain the case ```chatRoomSubtitleText```. So I plan to handle the case ```chatRoomSubtitleText``` inside ```ParentNavigationSubtitle```

**Comment by robertKozik** [comment] 2023-11-10 19:50
In this case do you agree we should also change the function which generates parentNavigationSubtitleData?
https://github.com/Expensify/App/blob/a941a6a7f4af36b926f524f119969076e9b42956/src/libs/ReportUtils.js#L2190-L2201

Then we return correct object based on which we would render everything inside `ParentNavigationSubtitle`

**Comment by DylanDylann** [comment] 2023-11-11 00:22
@robertKozik no I think we should not change the parentNavigationSubtitleData

**Comment by robertKozik** [comment] 2023-11-13 09:36
Ok, got it. Could you @DylanDylann  update your proposal with details of changing `ParentNavigationSubtitle`? So we will have every datail in one proposal

**Comment by DylanDylann** [comment] 2023-11-13 15:42
@robertKozik After re-checking, I think we should not refactor the ParentNavigationSubtitle in this issue, because it can lead to regression

**Comment by DylanDylann** [comment] 2023-11-13 16:31
@robertKozik 
- After re-checking and trying to implement, I think we should not refactor the ```ParentNavigationSubtitle``` in this issue because it not only does not help us to reduce the number of lines but also can lead to regression.
- Updated my [proposal](https://github.com/Expensify/App/issues/30725#issuecomment-1790253658) to reduce the unnecessary change

**Comment by robertKozik** [comment] 2023-11-13 16:44
Thanks for updating me. I just want to inform you that without the `ParentNavigationSubtitle` change, your proposal is very simmilar to @saranshbalyan-1234 one.  I'll later go once more through the proposals and came buck with conclusion 👌🏼

**Comment by DylanDylann** [comment] 2023-11-13 16:47
@robertKozik my proposal handle the two case: The current user is admin (in this case, allow to click on text and navigate to workspace page) and the current user is not admin (cannot click on text)

**Comment by DylanDylann** [comment] 2023-11-13 17:31
@saranshbalyan-1234 Yeah. But in case the user is not admin, we need to handle the ellipsis hover as well

**Comment by DylanDylann** [comment] 2023-11-13 17:35
@saranshbalyan-1234 I mean that your proposal is missing the case "user is not admin hover over the elipsis"

**Comment by DylanDylann** [comment] 2023-11-13 17:40
@saranshbalyan-1234 yeah. I agree with you. It based on reviewer `s viewpoint

**Comment by robertKozik** [comment] 2023-11-14 11:18
Hi again! I've implemented the solution from @saranshbalyan-1234 proposal on my end and tooltip is displaying for both admin and non-admin on lengthy workspace names. And I think we should go with his [Proposal](https://github.com/Expensify/App/issues/30725#issuecomment-1789733201) - it was the first one to introduce this kind of solution

on a side note @DylanDylann after implementing your proposal, disabling the pressable when user is not admin leads to cursor change to `disabled` which is not ideal here.

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2023-11-14 11:36
@saranshbalyan-1234 If can, you can try to handle the case "user is not admin hover over the elipsis" in your future PR

**Comment by robertKozik** [comment] 2023-11-14 11:40
@DylanDylann it's actually covered imo, whether user is admin or not, we are rendering workspace name  via `DisplayNames` components which comes with tooltip on hovering ellipsis

**Comment by DylanDylann** [comment] 2023-11-14 11:42
@robertKozik  But the @saranshbalyan-1234 proposal does not handle the case isPolicyAdmin: true

**Comment by DylanDylann** [comment] 2023-11-14 11:43
Also I just want to notice him that should consider this case if it is not handled

**Comment by robertKozik** [comment] 2023-11-14 11:57
<details>
<summary>How it looks on my end</summary>
https://github.com/Expensify/App/assets/61146594/3ea42b8a-583d-4296-98be-dad78fac2e63
</details>

Yeah I'll double check that case on the PR review. Thanks for heads up, really appreciate that 🚀

**Comment by DylanDylann** [comment] 2023-11-14 12:16
> on a side note @DylanDylann after implementing your proposal, disabling the pressable when user is not admin leads to cursor change to disabled which is not ideal here.

Just want to note, that we can just use ```style={[styles.w100, !isPolicyAdmin && styles.cursorText]}``` in ```PressableWithoutFeedback``` (Because I do not write the detail in my proposal)

**Comment by bondydaa** [comment] 2023-11-16 15:44
melvin, cool your jets.

**Comment by robertKozik** [comment] 2023-11-27 21:42
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **N/A**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **This interaction was not implemented for this screen. Because of that I don't think we need any regression tests**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by trjExpensify** [comment] 2023-12-04 11:50
👋 @robertKozik on this: 

>This interaction was not implemented for this screen. Because of that I don't think we need any regression tests

I'm curious if there's anything we can do to avoid forgetting about truncating long workspace names when they get added to places in the app? The checklist, style guide, something else? etc.

**Comment by trjExpensify** [comment] 2023-12-06 12:08
bump on the q above @robertKozik.

**Comment by trjExpensify** [comment] 2023-12-06 13:16
Yep, we're totally cool with doing things like that. Do you want to submit a PR to the checklist file? Then I think we're done here. 

As for payment to @saranshbalyan-1234, I think it's $250 because of the regression right?

**Comment by trjExpensify** [comment] 2023-12-06 21:10
Perfect - thanks! So confirming on this, there was a regression right? 

As for payment to @saranshbalyan-1234, I think it's $250 because of the regression right?

**Comment by trjExpensify** [comment] 2023-12-11 11:11
I've gone ahead and paid this out at $250 to avoid any further delay. Closing!

**Closed by trjExpensify** 2023-12-11 11:11 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug
