### ISSUE TITLE
[HOLD for payment 2024-07-02] [Details Revamp] Update ReportDetailsPage for Money Reports/Requests

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42075] opened 2024-05-13 14:24 UTC
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.h5iso7k2jwwq

Held on https://github.com/Expensify/App/issues/42071

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by kevinksullivan** [comment] 2024-05-21 22:22
Looks like we're still held here, so not overdue.

**Comment by shawnborton** [comment] 2024-05-30 05:38
The PromotedActions bar PR is merged, so maybe we can move forward with this one now?

**Comment by cdOut** [comment] 2024-06-03 09:10
Hi, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I'm working on this issue.

**Comment by ikevin127** [comment] 2024-06-27 23:01
@kevinksullivan @grgia I require payment as C+ reviewer of PR: https://github.com/Expensify/App/pull/43251#issuecomment-2177380414.

##

**Notes:**
1. The PR had some regressions, Georgia should be able to confirm this.
2. There are 2 other issues as part of this PR ([42074](https://github.com/Expensify/App/issues/42074), [42076](https://github.com/Expensify/App/issues/42076)) where the hold for payment was added as well.

**Comment by trjExpensify** [comment] 2024-07-02 15:38
Let's consolidate to one issue to handle payment for the PR that took care of these issues. As the regression period is over, I'm closing this issue and centralising on the one I'm assigned to: https://github.com/Expensify/App/issues/42076

**Closed by trjExpensify** 2024-07-02 15:38 UTC
Labels: Reviewing, Weekly, NewFeature, Awaiting Payment
