### ISSUE TITLE
[$250] Fix onboarding modal in macOS Chrome/Safari

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#53724] opened 2024-12-06 22:24 UTC
The onboarding modal seems to have issues being displayed in macOS in Chrome and Safari ([conversation](https://github.com/Expensify/App/issues/53326#issuecomment-2524085623), GH [comment](https://github.com/Expensify/App/issues/53326#issuecomment-2524085623)). Seems like there is an issue with screen size and/or refresh. Please fix it and ensure it's always displayed in all possible platforms. We found this while working on this issue: https://github.com/Expensify/App/issues/53326
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865160679237341916</li>
        <li>Upwork Job ID: 1865160679237341916</li>
        <li>Last Price Increase: 2024-12-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-12-07 02:11
Coming from https://github.com/Expensify/App/issues/53326#issuecomment-2524085623. I’ll work on this, thanks!

**Comment by Shahidullah-Muffakir** [comment] 2024-12-08 03:25
@carlosmiceli as per https://github.com/Expensify/App/issues/53284#issuecomment-2523889800 and after testing with same steps, the onboarding modal works as expected in staging when signing up through staging.expensify.com, after redirecting to staging.new.expensify.com the onboarding flow modal appears as expected. However, the issue persists in prod.
Considering this, should we wait for the next production deploy to see if the issue resolves? Thank you.

**Comment by carlosmiceli** [comment] 2024-12-09 15:47
> should we wait for the next production deploy to see if the issue resolves?

Yes, that sounds like a good idea.

**Comment by carlosmiceli** [comment] 2024-12-09 17:30
Not overdue.

**Comment by carlosmiceli** [comment] 2024-12-13 18:42
Still discussing details in the PR.

**Comment by carlosmiceli** [comment] 2024-12-16 20:33
@Shahidullah-Muffakir is this still occurring?

**Comment by hungvu193** [comment] 2024-12-17 10:10
little bump @Shahidullah-Muffakir

**Comment by Shahidullah-Muffakir** [comment] 2024-12-18 08:41
> @Shahidullah-Muffakir is this still occurring?

Yes, still occurring.

**Comment by Shahidullah-Muffakir** [comment] 2024-12-18 08:42
> little bump @Shahidullah-Muffakir

PR will be ready by tomorrow.

**Comment by Shahidullah-Muffakir** [comment] 2024-12-18 11:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Fix onboarding modal in macOS Chrome/Safari.

### What is the root cause of that problem?
1. In the `hasCompletedGuidedSetupFlowSelector` function, when the `onboardingFlow` object is empty or `hasCompletedGuidedSetupFlowSelector` is undefined, we are returning `true`:
   https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/onboardingSelectors.ts#L14-L20
2. This results in the `useOnboardingFlowRouter` hook returning `true`:
   https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L243
   and as the `isOnboardingCompleted` is `true`, this condition fails:
   https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L538-L542
   Hence, the Onboarding Modal is not shown.

### What changes do you think we should make in order to solve the problem?

The same way we return `false` when the onboarding object is empty in the case of:
   https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/src/libs/onboardingSelectors.ts#L51-L54,
   we should return `false` in the case of `hasCompletedGuidedSetupFlowSelector` as well if the `onboarding ` is undefined.
as:
```diff
function hasCompletedGuidedSetupFlowSelector(onboarding: OnyxValue<typeof ONYXKEYS.NVP_ONBOARDING>): boolean | undefined {
    // Onboarding is an empty object for old accounts and accounts migrated from OldDot
    if (Array.isArray(onboarding) || isEmptyObject(onboarding)) {
-         return true;
+        return false;
    }

    if (!isEmptyObject(onboarding) && onboarding?.hasCompletedGuidedSetupFlow === undefined) {
-        return true;
+       return false;
    }
```

@hungvu193  Before making the PR, could you review the changes I proposed, thanks.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
We need to updated these tests as well, to return false instead of true:
https://github.com/Expensify/App/blob/1466c022e3bb0ab2ffaaab12f78822a2aca827c8/tests/unit/OnboardingSelectorsTest.ts#L10-L22

**Comment by mountiny** [comment] 2024-12-18 19:19
@Shahidullah-Muffakir We cannot return false there, its intentional that we do not show the onboarding modal for users that do not have the nvp or of the nvp is an empty object

**Comment by Shahidullah-Muffakir** [comment] 2024-12-18 19:33
> We cannot return false there, its intentional that we do not show the onboarding modal for users that do not have the nvp or of the nvp is an empty object

Got it. Thanks for confirming

**Comment by mountiny** [comment] 2024-12-18 20:46
Lets close this in favour of https://github.com/Expensify/App/issues/54322

**Closed by mountiny** 2024-12-18 20:46 UTC
Labels: External, Daily, Bug
