### ISSUE TITLE
[$250]  Tax - Split scan - Selected rate from confirmation page does not show up in split detail view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42643] opened 2024-05-27 15:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40240
## Action Performed:
Precondition:
- Workspace is tax-enabled
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Split expense > Scan
4. Upload a receipt
5. On confirmation page, click Tax rate
6. Select any rate
7. Click Split expense
8. Click on the split preview

## Expected Result:
The selected tax rate will show up in Tax rate row in split details view

## Actual Result:
The selected tax rate does not show up in Tax rate row in split details view. The row is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b133585f-2336-49b7-9782-db0ed700653e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b6987c10090fc2e</li>
        <li>Upwork Job ID: 1795297947813523456</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by lanitochka17** [comment] 2024-05-27 15:34
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bondydaa** [comment] 2024-05-27 21:54
the revert https://github.com/Expensify/App/pull/42670 has been deployed, please retest and confirm this is no longer reproducible.

**Comment by kavimuru** [comment] 2024-05-28 00:21
Issue is not fixed. 

https://github.com/Expensify/App/assets/43996225/d39549af-782f-4f01-9309-1c226d56d8f2

**Comment by nkdengineer** [comment] 2024-05-28 04:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected tax rate does not show up in Tax rate row in split details view. The row is empty

### What is the root cause of that problem?
We have two bug here

1. When we start split bill here, we don't accept `taxCode` and `taxAmount` param in this function to create optimistic transaction and pass it to param of `StartSplitBill` API

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L342

2. When we edit tax rate and tax amount, we're calling `UpdateMoneyRequestTaxRate` API because we don't have the case for edit split bill here

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/iou/request/step/IOURequestStepTaxRatePage.tsx#L76
### What changes do you think we should make in order to solve the problem?
1. Accept `taxCode`, `taxAmount` param in `startSplitBill` function and then use this to create optimistic transaction [here](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/IOU.ts#L4296).

2. Pas `taxCode` as `transactionTaxCode` and `taxAmount` as `transactionTaxAmount` into `startSplitBill` function here

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L342

3. Pass `taxCode` and `taxAmount` as param of `StartSplitBill` API here. We also need BE change to return `taxCode` and `taxAmount` of the transaction when we call `StartSplitBill` API

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/IOU.ts#L4540

4. When we edit split bill tax rate, we should call `setDraftSplitTransaction` as the revert PR here https://github.com/Expensify/App/pull/42670/files#diff-2d4b9c38f6fb668f527da301a60d3c9bb05c865f33aa475d29148bbda45e3cc0

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/iou/request/step/IOURequestStepTaxRatePage.tsx#L76

### What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment] 2024-05-29 17:05
This should be hold https://github.com/Expensify/App/issues/39690

cc @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2024-05-30 11:50
We can close this. This is new feature and not a bug

**Closed by MonilBhavsar** 2024-05-30 11:50 UTC
Labels: External, Daily, Help Wanted, Bug
