### ISSUE TITLE
[HOLD for payment 2024-10-22] iOS - IOU - Page flickers when selecting different payment option on IOU preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#50722] opened 2024-10-14 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5077885
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the Hybrid app/NewDot app and log in as user A
2. On a secondary device as user B send an IOU to user A
3. On main device as user A open the chat with user B
4. Select a different payment option on the IOU preview

## Expected Result:
The page does not flicker when changing a payment option

## Actual Result:
The page flickers when changing a payment option. It also occurs on the transaction details.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/96f6fd24-151c-45fb-865a-357cf1f66381

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by izarutskaya** [comment] 2024-10-14 12:51
Production

https://github.com/user-attachments/assets/962c62f1-d2b2-454c-b7fe-b0faa5c723eb

**Comment by izarutskaya** [comment] 2024-10-14 12:54
I'm not sure what labels is needed since there is no option `Use Staging Served` in the Hybrid App

**Comment by dangrous** [comment] 2024-10-14 14:07
@izarutskaya does this also happen on the App itself? or only in Hybrid App? Thanks!

**Comment by dangrous** [comment] 2024-10-14 16:24
thats helpful thank you! working on reproducing, will investigate

**Comment by dangrous** [comment] 2024-10-14 16:49
hrm i'm not able to reproduce on a simulator. I also don't see an obvious PR. Will keep looking.

**Comment by dangrous** [comment] 2024-10-14 17:15
oh okay figured out what it is related to - it's something about the software keyboard. I'm now able to reproduce locally so should be able to get this figured out soon.

**Comment by dangrous** [comment] 2024-10-14 17:16
Removing backend blocker, seems to happen equivalently on prod

**Comment by dangrous** [comment] 2024-10-14 17:24
it's due to https://github.com/Expensify/App/pull/50279, figuring out why

**Comment by dangrous** [comment] 2024-10-14 18:28
I think we might want to revert, it looks like #50279 also would reopen https://github.com/Expensify/App/issues/50636 so that would be two bugs.... I also haven't figured out the specific cause yet, though I'm guessing it's the withOnyx / useOnyx because that seems to keep causing weird bugs

**Comment by kavimuru** [comment] 2024-10-14 23:19
Bug is fixed

https://github.com/user-attachments/assets/fffb3bf2-65cc-44f4-9284-5c0568b756d2

**Comment by dangrous** [comment] 2024-10-15 15:08
Closing this, it was a revert (and internal) so no regression period needed.

**Closed by dangrous** 2024-10-15 15:08 UTC
Labels: DeployBlockerCash, Engineering, Weekly, Awaiting Payment, Bug
