### ISSUE TITLE
[$250] Changing code on Desktop backend, does not hot reload the app - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10351] opened 2022-08-11 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run the dev server for desktop app via npm run desktop.
2. Make changes to main.js file.

## Expected Result:
App does not show changes in realtime.

## Actual Result:
App is refreshed and new changes takes place without rerunning the command. 
Changing the main process code, used to rebuild the whole app (changing desktop backend restarts the app). This was fine as main process needs to restart.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.82-5
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658339926582439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2022-08-11 21:27
Adding engineering label for help triaging this per this [discussion](https://expensify.slack.com/archives/C03TQ48KC/p1660253041898609?thread_ts=1660250804.557069&cid=C03TQ48KC).

**Comment by pecanoro** [comment] 2022-08-12 08:30
@parasharrajat Is this only for the `main.js` file? Because if I make changes for other files, it works just fine

**Comment by laurenreidexpensify** [comment] 2022-08-16 17:44
https://www.upwork.com/jobs/~010ce302e7fd355b75

**Comment by roryabraham** [comment] 2022-08-16 20:04
Yeah, this is a dupe of https://github.com/Expensify/App/issues/8061. Removing `Help Wanted` label because we've already got @kidroca assigned.

@laurenreidexpensify please take down the Upwork job when you get a chance and then close this issue. Thanks!

**Comment by kidroca** [comment] 2022-08-17 13:07
I'll give this another go, there were other updates as well and perhaps the newer versions would allow `main.js` reloading to work

**Comment by laurenreidexpensify** [comment] 2022-08-22 11:28
Sorry missed this last week - job on Upwork removed and closing issue now.

**Closed by laurenreidexpensify** 2022-08-22 11:28 UTC
Labels: Exported, External, Engineering, Weekly, Improvement
