### ISSUE TITLE
Room - Workspace member is not automatically added to created room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29393] opened 2023-10-11 21:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to New Expensify app
2. In workspace settings - invite User B who has never interacted with the account you're logged in
3. Create Room on the Workspace from Step 2
4. Navigate to User B account

## Expected Result:
Workspace member should be automatically added into the room

## Actual Result:
Workspace member is not automatically added into the room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/e6edaed0-818a-4a94-820e-99e9221612fd

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-10-12 09:27
@lanitochka17 Hey! I wasn't able to find the test case for this in TestRail to confirm the correct behaviour, could you link to that please? I'm not confident that the expectation here (that the workspace member will be automatically added to a created room) is correct, and want to check that. Thanks!

**Comment by conorpendergrast** [comment] 2023-10-16 12:28
@lanitochka17 Bump on this request please!

**Comment by lanitochka17** [comment] 2023-10-16 13:57
@conorpendergrast Hello
The issue was found when following the steps: https://expensify.testrail.io/index.php?/tests/view/3794302

There is no way to add participants through the room, so all participants who are in the workspace are automatically added to the room. But I could be wrong

**Comment by conorpendergrast** [comment] 2023-10-16 15:02
Thank you! I don't think workspace members will be added to the room by-default, but I can see where you would assume that! It's implied but not explicit, as the sub-text is _"People in your workspace can find this room"_ rather than that they will added to the room. 

The TestRail implies this (but again, it's not explicit), in saying:
8. Log in as the other workspace member that was added in step 1
9. Search the room name
10. **Verify** it's displayed in the search results
11. Tap on the room
12. **Verify** the room opens and you can access it as another member of the workspace

I'm 90% sure that workspace members should be able to find the new restricted room, but will not be added to it by default. So, I'll close this as not a bug for now - thanks for raising it!

**Closed by conorpendergrast** 2023-10-16 15:02 UTC
Labels: Daily, Bug

**Comment by lanitochka17** [comment] 2023-10-19 23:19
@conorpendergrast  Hello
Thanks for the detailed explanation
