### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] [WAVE 5][LOW] Settings - Year change by months does not change selection

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33006] opened 2023-12-13 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Open settings->profile->personal details->date of birth
3. Click on the year and select a year, observe that after value is changed, both background colour and green tick location are on the selected year
4. Click year again > now click the forward arrow of the month (>) until you get to January 
5. Click on the year again and notice that the green checkmark is on the previously selected year and the highlight year is the new year

## Expected Result:
App should change background color as well as green tick position for the selected or current calendar year

## Actual Result:
App changes background color but does not change green tick position on change of year value by changing months value in calendar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/487e5060-ac97-425c-afd1-aa057e146c64

![image](https://github.com/Expensify/App/assets/51066321/9361b32c-e9a6-4ab5-b680-f6e5c400382b)

![image](https://github.com/Expensify/App/assets/51066321/322ce195-fcac-4081-b092-a5ee426f669f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102b1c7f6c3df6359</li>
        <li>Upwork Job ID: 1735031332000718848</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28064580</li>
<li>ishpaul777 | Contributor | 28064581</li>
</ul></li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-12-13 21:05
I can reproduce this - I think it's a low priority but I think it could be part of [[ECARD] LOW: Settings - Remove unnecessary requirement for dateOfBirth when creating physical cards in Marqeta#316704](https://github.com/Expensify/Expensify/issues/316704)

Adding it to that Wave to evaluate this change!

**Comment by Christinadobrzyn** [comment] 2023-12-14 20:44
Hi @ishpaul777 it looks like this job will be treated with our normal priority. 

@mollfpr feel free to evaluate the provided proposal to see if any will work. Thanks!

**Comment by flodnv** [comment] 2023-12-15 17:20
>I think it could be part of https://github.com/Expensify/Expensify/issues/316704

FWIW this is unrelated

**Comment by mollfpr** [comment] 2023-12-18 07:52
I feel the [proposal](https://github.com/Expensify/App/issues/33006#issuecomment-1854655489) from @ishpaul777 is the correct way to handle this issue. It makes it easier to maintain the prev/next month's function. 

🎀 👀 🎀 C+ reviewed!

**Comment by Christinadobrzyn** [comment] 2023-12-19 22:21
still working on a review - @danieldoglas when you have a moment can you check on this decision - https://github.com/Expensify/App/issues/33006#issuecomment-1859715285

**Comment by mollfpr** [comment] 2023-12-20 03:52
@Christinadobrzyn, I think we already let @ishpaul777 work on the issue. We need to wait for the PR to be ready.

**Comment by Christinadobrzyn** [comment] 2023-12-22 00:58
hi @mollfpr just checking on the PR review!

**Comment by mollfpr** [comment] 2023-12-22 12:17
@Christinadobrzyn Yup, working on it!

**Comment by mollfpr** [comment] 2024-01-18 16:50
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/21792

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/21792/files#r1457723732

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Sign in to the App
2. Navigate to settings -> profile -> DOB
3. Click the forward arrow of the month (>) until you get to January. Note that the year has changed. Now open the year picker and **_verify_** the changed year is highlighted
4. Click the backward arrow of the month (<) until you get to December; note the year has changed. Now open the year picker and **_verify_** the changed year is highlighted

---

@Christinadobrzyn Could you give the payment summary for the manual request in NewDot? Thank you!

**Comment by danieldoglas** [comment] 2024-01-22 20:27
Just awaiting payment, not overdue. cc @Christinadobrzyn

**Comment by Christinadobrzyn** [comment] 2024-01-23 20:26
Sorry for the delay here

Regression test here- https://github.com/Expensify/Expensify/issues/363007

Payouts due:

Issue Reporter: NA
Contributor: $500 @ishpaul777 (Paid in Upwork)
Contributor+: $500 @mollfpr - you get paid in NewDot or Upwork?

Eligible for 50% #urgency bonus? NA

Upwork job is [here](https://www.upwork.com/ab/applicants/1735031332000718848/job-details). The upwork job is now closed so let me know if you need payment through Upwork and I'll create a new job

**Comment by mollfpr** [comment] 2024-01-24 12:57
Thanks @Christinadobrzyn I'll request the payment in NewDot.

**Comment by JmillsExpensify** [comment] 2024-01-24 15:59
$500 approved for @mollfpr based on summary above.

**Comment by Christinadobrzyn** [comment] 2024-01-25 23:58
awesome! I think we're good to close this. Thanks all!

**Closed by Christinadobrzyn** 2024-01-25 23:58 UTC
Labels: External, Daily, Awaiting Payment, Bug, ECard
