### ISSUE TITLE
Android - Workspace settings - Input fields are not grayed out when made changes offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10825] opened 2022-09-05 19:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App and login
2. Click on Create a New Workspace
3. Navigate to the General settings page
4. Disable the internet connection
5. Change the workspace currency and name
6. Save the changes

## Expected Result:
Input fields should be grayed out when saved changes offline

## Actual Result:
Input fields are not grayed out when made changes offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.97.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188506121-f9de9e14-213a-49c5-a80e-b999c56ffe35.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2022-09-05 22:34
Not really a blocker. I think this is fine since we'll now allow updating the workspace name optimistically even when offline so this seems normal to me. cc @neil-marcellini as well since you made this change.

I tested on staging and it looks good to me as is.

**Comment by luacmartins** [comment] 2022-09-06 09:46
I agree that this is not a blocker since it's just UI and doesn't prevent the user from using the App. I was also not able to reproduce this locally. Removing the blocker label.

**Comment by neil-marcellini** [comment] 2022-09-06 10:12
Was cellular data turned off when "going offline"? The offline indicator did not appear. @kbecciv can you please try again and make sure that cellular data is off?

**Comment by kbecciv** [comment] 2022-09-06 12:45
@neil-marcellini Checking with team, will update you shortly.

**Comment by kbecciv** [comment] 2022-09-06 12:52
@luacmartins @neil-marcellini Not able reproduced with build 1.1.97.2

https://user-images.githubusercontent.com/93399543/188639962-54d4c26e-5ede-4ca6-aef4-e824c4f55244.mp4

**Comment by luacmartins** [comment] 2022-09-06 13:07
Cool, thanks for confirming! gonna close this issue!

**Closed by luacmartins** 2022-09-06 13:07 UTC
Labels: Engineering, Daily
