### ISSUE TITLE
[HOLD #39432][$500] Report - Offline deleted message is not struck through

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39307] opened 2024-03-29 22:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4467827
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any report
2. Apply offline mode
3. Delete a message

## Expected Result:
Message should be grayed out, and struck through

## Actual Result:
Message disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/878be84c-f887-4d93-9b10-6ee07461dd8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123d5e156c38fe58b</li>
        <li>Upwork Job ID: 1775662468195880960</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-29 22:25
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-03-30 07:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Report - Offline deleted message is not struck through 
### What is the root cause of that problem?
- The logic [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/home/report/ReportActionsList.tsx#L191) always returns ```false``` in offline mode because ```shouldReportActionBeVisible``` do not handle offline case.
### What changes do you think we should make in order to solve the problem?
 - We just need to update above to:
```
  isOffline || ((reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || reportAction.errors) && ReportActionsUtils.shouldReportActionBeVisible(reportAction, reportAction.reportActionID)),
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment] 2024-04-01 05:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Message disappears

### What is the root cause of that problem?


### What changes do you think we should make in order to solve the problem?
When we delete a message that isn't a thread parent message, the current request is included and then we merge the `successData` into Onyx. That is the root cause of the issue

https://github.com/Expensify/App/blob/272b05f087c19baaeeb7b37dc8619c89c8ca572c/src/libs/actions/Report.ts#L1321


https://github.com/Expensify/App/blob/272b05f087c19baaeeb7b37dc8619c89c8ca572c/src/libs/actions/PersistedRequests.ts#L40

### What alternative solutions did you explore? (Optional)
We should handle merge the optimistic data of the request after we handle conflicting request

https://github.com/Expensify/App/blob/272b05f087c19baaeeb7b37dc8619c89c8ca572c/src/libs/API/index.ts#L67-L69

To do that we should move this [block](https://github.com/Expensify/App/blob/272b05f087c19baaeeb7b37dc8619c89c8ca572c/src/libs/API/index.ts#L67-L69
) after we push the request [here](https://github.com/Expensify/App/blob/272b05f087c19baaeeb7b37dc8619c89c8ca572c/src/libs/API/index.ts#L97)

**Comment by strepanier03** [comment] 2024-04-03 23:09
Raising this [internally](https://expensify.slack.com/archives/C03U7DCU4/p1712185741786039) because I'm finding contradicting expected behavior.

https://github.com/Expensify/App/issues/17081

**Comment by strepanier03** [comment] 2024-04-03 23:11
Okay "greyed out and struck through" is the expected behavior.

**Comment by hungvu193** [comment] 2024-04-04 03:25
Hey @roryabraham, I believe this issue is a regression from your [recent PR](https://github.com/Expensify/App/pull/39024), do you want to fix this as a separate issue or treat it as a regression?

<details>
<summary>Revert PR</summary>


https://github.com/Expensify/App/assets/16502320/5ed1a0db-a74f-4fc2-93d6-f70a46171b95



</details>

**Comment by roryabraham** [comment] 2024-04-04 05:23
I'd be happy to fix this in a follow-up, I don't think we should revert this, as the bug(s) I fixed were worse than this one.

**Comment by hungvu193** [comment] 2024-04-04 06:23
Thanks, @nkdengineer. I'm not convinced by the solution of moving the updating optimisticData after `SequentialQueue.push(request)`. Also, it didn't work when you turned off and then turned on your internet connection few times.

https://github.com/Expensify/App/assets/16502320/f8f72a92-377c-4a8d-b144-f1eebc797d19

**Comment by hungvu193** [comment] 2024-04-05 03:02
Can you please link that similar issue here? 

> Hello @hungvu193
> 
> Can you please hold this issue on another similar issue?
> 
> Thanks

**Comment by hungvu193** [comment] 2024-04-05 03:07
Awesome, @strepanier03 let's put this on hold for https://github.com/Expensify/App/issues/39432

**Comment by hungvu193** [comment] 2024-04-08 09:27
hold for https://github.com/Expensify/App/issues/39432

**Comment by roryabraham** [comment] 2024-04-08 19:02
HOLD, should be fixed in https://github.com/Expensify/App/issues/39432

**Comment by strepanier03** [comment] 2024-04-23 20:18
Still on hold, good to keep pausing.

**Comment by roryabraham** [comment] 2024-05-03 07:22
Still on HOLD, will resume https://github.com/Expensify/App/issues/39432 as soon as I can

**Comment by strepanier03** [comment] 2024-05-14 23:08
Thanks Rory!

**Comment by roryabraham** [comment] 2024-05-23 20:31
still on hold

**Comment by strepanier03** [comment] 2024-06-14 03:45
Currently on hold.

**Comment by strepanier03** [comment] 2024-06-26 23:08
VSB is on hold. Thinking of moving this to monthly.

**Comment by strepanier03** [comment] 2024-07-17 01:16
Moving to monthly for now.

**Comment by strepanier03** [comment] 2024-09-03 19:32
Going to retest this, it's been quite some time since it was created and tested.

**Comment by strepanier03** [comment] 2024-09-03 19:38
On v9.0.28-2, I am unable to repro. Going offline and deleting a message strikes the message through as expected. 

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/43ff70e3-875a-4cd8-a790-d214c0b8a25a">

I'm going to close this out as already fixed. Reopen if you disagree.

**Closed by strepanier03** 2024-09-03 19:38 UTC
Labels: Reviewing, External, Weekly, Bug
