### ISSUE TITLE
Missing update currency modal on the invoices page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50678] opened 2024-10-11 21:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728681970960009

## Action Performed:
1. Create a workspace
2. Change the currency to a value other than USD.
3. Enable Invoices
4. Go to the Invoices page and click the button 'Connect bank account'
## Expected Result:
Update currency modal should be displayed as we did with other places

## Actual Result:
We navigate to page with error `Oops! It appears that your workspace currency is set to a different currency than USD.`

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3451bf3c-6aae-4d88-b35e-f3e99d98dd39

https://github.com/user-attachments/assets/611c7e8d-9eee-4d9f-ade5-54454018839d

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2024-10-13 15:55
I'm pretty sure this issue is a dupe of an old issue, where we decided this is an expected behavior.

**Comment by stephanieelliott** [comment] 2024-10-14 23:13
Yea I think we :do-nothing: here, I am going to close this

**Closed by stephanieelliott** 2024-10-14 23:13 UTC
Labels: Daily, Overdue, Bug
