### ISSUE TITLE
[$500] Split Bill - 1:1 DM with attendees you split a bill with are not bolded in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29190] opened 2023-10-10 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com and login with any account
2. Click the FAB button and select Request Money>Manual
3. Enter an amount in BNP & tap on the next button
4. Tap on "Split" button next to few users & tap "Add to split" button

## Expected Result:
There should be an unread 1:1 DM between you, and each attendee you just split a bill with

## Actual Result:
1:1 DM with attendees you split a bill with are not bolded in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/78819774/80b80ae4-064d-4ec7-a772-9a48f4bedcdb

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/78819774/80ab5d57-312c-43e8-b3c9-c790563bea84

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2019f2ea37cb259</li>
        <li>Upwork Job ID: 1712815168206192640</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-10-10 20:19
@CortneyOfstad Did you check video linked in MacOS: Chrome / Safari above?   


![image](https://github.com/Expensify/App/assets/78819774/180f04db-6a4a-4d17-adbc-ca2210d6520f)

**Comment by CortneyOfstad** [comment] 2023-10-16 12:17
@burczu any thoughts on the proposal above?

**Comment by burczu** [comment] 2023-10-17 12:26
@CortneyOfstad I'm sorry, I was busy reviewing PR's - I'll be reviewing proposals soon.

**Comment by burczu** [comment] 2023-10-18 07:45
I've checked [the proposal](https://github.com/Expensify/App/issues/29190#issuecomment-1761538406) from @tienifr and I think it does make sense, so I think we could proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by nkuoch** [comment] 2023-10-18 08:56
@tienifr can you add some links on your proposal so we we know better on which parts of the code you intend to do your changes? Also, let's make sure we don't introduce any regression for normal DMs where they should be unread when creating them as we indeed saw them at the same time as creating them. So I guess this is specific to splits. Which makes me think in this case, do we actually want to set lastReadTime? Can't it just be empty as we didn't ever actually read those.

**Comment by nkuoch** [comment] 2023-10-18 08:57
Also cc @trjExpensify to double check we do want to show each new split as bold when creating them.

**Comment by trjExpensify** [comment] 2023-10-18 11:16
Hm, I don't understand this issue actually. The request is added to the chat by the creator of the request, why would the chat then be unread for them for their own action? 

The chat would be unread for the recipient of the request, but I don't think it would be unread for the creator of the request.

**Comment by nkuoch** [comment] 2023-10-18 14:21
yes I kind of agree with you too @trjExpensify .

From the video in the PR description under `MacOS: Chrome / Safari`, I do see 1 of the splits shows as unread though? So maybe the fix would be just to have them all consistent, all showing as read?

**Comment by trjExpensify** [comment] 2023-10-18 14:27
Oh yeah, nice eye. Yup, I agree. Unread for the recipient, read for the creator. 👍

**Comment by CortneyOfstad** [comment] 2023-10-18 20:15
I am heading OoO until Oct. 25, so reassigning BZ to have someone keep an eye on things while I am gone 👍

**Comment by CortneyOfstad** [comment] 2023-10-25 18:55
I am back from OoO @trjExpensify so I can take this back! Thanks for holding down the fort while I was out!

**Comment by mvtglobally** [comment] 2023-10-27 00:43
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2023-10-30 10:47
Sounds good, @CortneyOfstad. I can drop off. 

On [this](https://github.com/Expensify/App/issues/29190#issuecomment-1782123124), @mvtglobally are you saying that now all the DMs are showing up **as unread** for the person that took the action to split?

**Comment by CortneyOfstad** [comment] 2023-10-31 16:08
@mvtglobally bump on the question above ^^^ thanks!

**Comment by mvtglobally** [comment] 2023-10-31 16:09
Will update shortly

**Comment by CortneyOfstad** [comment] 2023-11-06 16:34
@mvtglobally any update? TIA!

**Comment by mvtglobally** [comment] 2023-11-06 16:58
We are seeing the following flows now 
https://github.com/Expensify/App/assets/43995119/d69d988e-b9ff-403a-9390-13c2e6ccf861


https://github.com/Expensify/App/assets/43995119/5b1cb9db-60e8-4818-8c72-c8990b787341

**Comment by trjExpensify** [comment] 2023-11-06 23:11
Okay, so to confirm what you're seeing because the emails are truncating: 

After you split with three members, all three DMs with the participants are appearing unread for the requestor. I don't think any of those should be unread personally for the requestor given it was their own action to create the split. The chat should only be unread for the other participant of the DM. CC: @JmillsExpensify @puneetlath

**Comment by puneetlath** [comment] 2023-11-07 23:08
My vote would be to leave bill split as-is while we focus on Collect/Request.

**Comment by trjExpensify** [comment] 2023-11-09 00:32
Haha, by that comment I take it wave6 and the higher context chat stuff isn't fixing this? I feel like it's in the same bucket as an expense report showing unread in the LHN after you create a new request. Ideally both request/split work the same and don't do that.

**Comment by JmillsExpensify** [comment] 2023-11-09 00:35
> Okay, so to confirm what you're seeing because the emails are truncating:
> 
> After you split with three members, all three DMs with the participants are appearing unread for the requestor. I don't think any of those should be unread personally for the requestor given it was their own action to create the split. The chat should only be unread for the other participant of the DM. CC: @JmillsExpensify @puneetlath

I agree with this logic.

**Comment by JmillsExpensify** [comment] 2023-11-09 00:36
> Haha, by that comment I take it wave6 and the higher context chat stuff isn't fixing this? I feel like it's in the same bucket as an expense report showing unread in the LHN after you create a new request. Ideally both request/split work the same and don't do that.

And yeah, I thought that the point of wave6 was to remove double notification right? I get that split isn't as important as expense, though I would think that getting rid of double notification everywhere is still pretty important, high-level goal we should address now.

**Comment by CortneyOfstad** [comment] 2023-11-09 18:48
@nkuoch @burczu Does that work for you guys ^^^ Thanks!

**Comment by burczu** [comment] 2023-11-13 10:05
@CortneyOfstad I'm not sure what is the final conclusion here - are we leaving this as is as @puneetlath suggested, are we leave it to be done while working on wave6 along with expenses, or do we want to fix splits and expenses here in this issue?

**Comment by CortneyOfstad** [comment] 2023-11-20 14:35
@burczu my thought is that if wave 6 is not going to fix this, we should fix it now in this issue. @nkuoch does that work for you as well?

**Comment by CortneyOfstad** [comment] 2023-11-27 14:12
@burczu any updates on this? Thanks!

**Comment by burczu** [comment] 2023-11-30 08:46
@CortneyOfstad As requirements has changed slightly I think we should ask @tienifr to update their proposal to address the updated issue, or maybe we should wait for more proposals here?

**Comment by CortneyOfstad** [comment] 2023-12-08 14:51
@burczu update on the proposal above ^^^

**Comment by CortneyOfstad** [comment] 2023-12-11 14:32
@burczu bump ^^^ TIA!

**Comment by burczu** [comment] 2023-12-12 09:19
@CortneyOfstad I'm sorry for the delay - I've missed this one... I've checked the updated proposal from @tienifr and I think we should give it a try. As their solution requires BE changes, I believe we need to switch to `Internal` for now to address this part of the fix first, and then get back to the FE part.

**Comment by CortneyOfstad** [comment] 2023-12-12 13:41
Sorry for the trouble here! Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759), we can close any bugs that are not related to Waves, so closing this out 👍 We can re-address once those waves are completed.

**Closed by CortneyOfstad** 2023-12-12 13:41 UTC
Labels: Engineering, Weekly, Internal, Bug
