### ISSUE TITLE
[C+ Checklist Needs Completion] [$1000] Task is not being reflected on LHN if task is created after sending an attachment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23664] opened 2023-07-26 16:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat from the LHN
2. Send an attachment
3. Create a task inside the chat by clicking the plus icon inside the composer > assign task
4. Input the required fields and confirm the task
5. Observe the LHN of the opened report
## Expected Result:
 "Created task ..." should show up and the created task should also be reflected on the LHN
## Actual Result: 
Only "[Attachment]" is being shown in the LHN of the opened report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b20117c5-0cfb-41f8-9623-103ffb2a9c98

https://github.com/Expensify/App/assets/43996225/a449ee43-0a58-4135-8a60-6c0e0721bbae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690282010882909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146558a1a58c98ea3</li>
        <li>Upwork Job ID: 1684536150741610496</li>
        <li>Last Price Increase: 2023-07-27</li>
<li>Automatic offers: </li>
<ul>
<li>StevenKKC | Contributor | 25993947</li>
<li>nathan-mulugeta | Reporter | 25993948</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-07-27 11:48
Reviewing

**Comment by greg-schroeder** [comment] 2023-07-27 11:59
Kinda seems similar to https://github.com/Expensify/App/issues/22937

**Comment by Nathan-Mulugeta** [comment] 2023-07-27 12:02
Hey @greg-schroeder did you check [this](https://expensify.slack.com/archives/C049HHMV9SM/p1690283572905449?thread_ts=1690282010.882909&cid=C049HHMV9SM) conversation?

**Comment by greg-schroeder** [comment] 2023-07-31 14:52
@NikkiWines do you mind helping out with Sibtain's question?

>Should we be showing the updated task state in the LHN for parent report as well? If so, then should that be part of this issue?

I lean towards saying we should show the updated task state in both locations

**Comment by StevenKKC** [comment] 2023-07-31 19:34
> Should we be showing the updated task state in the LHN for parent report as well? If so, then should that be part of this issue?

It seems to BE does not send the updated task state for the parent report and should be fixed by BE.

**Comment by NikkiWines** [comment] 2023-08-01 02:09
Hmm, yeah I think this is probably better answered by @thienlnam since he headed up implementing tasks and probably knows the ideal behavior here. I would assume the same @greg-schroeder and that we'd want to show the updated task state in both locations

**Comment by thienlnam** [comment] 2023-08-01 02:28
Yeah I agree this should be fixed in the BE - we're updating the parent in the Complete/Re-open flows but seems like not in the Create Task flow.

**Comment by StevenKKC** [comment] 2023-08-01 05:30
I think showing the updated task state for parent report is an another issue and is not part of this issue.

**Comment by greg-schroeder** [comment] 2023-08-02 10:38
Okay. So let's keep this issue focused on what's listed in the OP. If we need to create a separate issue for the BE part, let's do that

**Comment by greg-schroeder** [comment] 2023-08-07 15:08
@NikkiWines I think that means we're good to assign @StevenKKC per https://github.com/Expensify/App/issues/23664#issuecomment-1656900447, no? Have you had a chance to confirm that is the way to go?

**Comment by NikkiWines** [comment] 2023-08-07 17:55
Ah yep, let's go with @StevenKKC's solution 👍

**Comment by StevenKKC** [comment] 2023-08-07 20:08
@allroundexperts PR https://github.com/Expensify/App/pull/24233 is ready for review.

**Comment by greg-schroeder** [comment] 2023-08-17 08:32
Issue Participants:

Issue reported by: @Nathan-Mulugeta
Contributor: @StevenKKC
C+: @allroundexperts 

Was this issue merged in time to be eligible for the speed bonus? [Yes](https://github.com/Expensify/App/issues/23664#issuecomment-1670236851)
Were their any regressions? ❌ 

Payment summary:

Reporter: $250
Contributor: $1,500 ($500 bonus)
C+: $1,500 ($500 bonus)

**Comment by greg-schroeder** [comment] 2023-08-17 08:32
Please request payment via NewDot @allroundexperts - all that's left here is taking care of the checklist!

**Comment by greg-schroeder** [comment] 2023-08-24 02:22
Filed regression test, closing!

**Closed by greg-schroeder** 2023-08-24 02:22 UTC
Labels: Daily, Internal, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:13
Reviewed the details for @allroundexperts. $1,500 approved for payment in NewDot based on BZ summary above.
