### ISSUE TITLE
[$250]  Workspace - Emoji is cut off in workspace description

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46448] opened 2024-07-29 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Profile.
3. Tap Description.
4. Clear the description.
5. Enter an emoji.

## Expected Result:
The emoji will not appear cut off.

## Actual Result:
The emoji is cut off.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/88181dfe-769f-4baa-bbc4-9688a52b1e24

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b019349deac75487</li>
        <li>Upwork Job ID: 1818038948071955386</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by chiragsalian** [comment] 2024-07-29 21:36
doesn't look web-e related. removing deployblocker label.

**Comment by jasperhuangg** [comment] 2024-07-29 21:38
This is a super minor display bug that I don't think warrants blocking app deploy, I'm gonna see if it was caused by any of the PRs in the checklist but removing the label

**Comment by c3024** [comment] 2024-08-14 12:46
This is not reproducible anymore.

https://github.com/user-attachments/assets/d8eacf8c-1648-4123-a28a-2055f18823b9

This can be closed. @kevinksullivan

**Comment by jasperhuangg** [comment] 2024-08-20 17:51
Thanks for taking a look @c3024, apologies for the delay was OOO recently. We can go ahead and close this out.

**Closed by jasperhuangg** 2024-08-20 17:51 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted, Bug
