### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Workspace-Long press Subscriptions/Cards not showing copy to clipboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36011] opened 2024-02-07 12:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Long press "Go to expensify classic"
4. Note "copy URL to clipboard" shown below
5. Go to Workspace settings
6. Long press "Subscriptions"
7. Long press " Cards & domains"

## Expected Result:
Across the app, the behavior must be same. Long pressing "Go to expensify classic" shows "copy URL to clipboard".Similarly, it must show "copy URL to clipboard" when user long press "Subscriptions" & " Cards & domains".

## Actual Result:
Long pressing "Go to expensify classic" shows "copy URL to clipboard" but long pressing "Subscriptions" & " Cards & domains" is not showing "copy URL to clipboard" 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a0e9bbfb-ea71-4ced-9a91-7229344aebd1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0cdfa2f6dd2a940</li>
        <li>Upwork Job ID: 1755205613428862976</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28148970</li>
<li>bernhardoj | Contributor | 28148971</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-07 12:23
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-02-07 12:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long pressing the subscription/cards menu doesn't show the copy to clipboard context menu.

### What is the root cause of that problem?
It will show if we pass the link attribute.
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/components/MenuItemList.tsx#L47

We already define it here
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/home/sidebar/AllSettingsScreen.tsx#L63

https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/home/sidebar/AllSettingsScreen.tsx#L75

But we forget to pass it to the array map here
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/pages/home/sidebar/AllSettingsScreen.tsx#L78-L91

### What changes do you think we should make in order to solve the problem?

Pass the link attribute to the array map
`link: item.link,`

**Comment by mollfpr** [comment] 2024-02-07 15:04
The proposal from @bernhardoj looks good to me!

Also, I would like to propose additional improvements on the link change with `Link.buildOldDotURL()` so it will show properly.

![Screenshot 2024-02-07 at 22 01 57](https://github.com/Expensify/App/assets/25520267/90298ea8-6fa6-4b1b-87e1-99e3cae039a5)

🎀 👀 🎀 C+ reviewed!

**Comment by amyevans** [comment] 2024-02-07 19:19
Proposal looks good, assigning @bernhardoj 

> Also, I would like to propose additional improvements on the link change with Link.buildOldDotURL() so it will show properly.

👍

**Comment by bernhardoj** [comment] 2024-02-08 06:28
PR is ready

cc: @mollfpr

**Comment by sakluger** [comment] 2024-02-20 18:00
Summarizing payment on this issue:

Contributor+: @mollfpr $500, please request on Newdot
Contributor: @bernhardoj $500, paid via Upwork

**Comment by sakluger** [comment] 2024-02-20 18:01
@mollfpr could you please complete the BZ checklist?

**Comment by mollfpr** [comment] 2024-02-20 18:34
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/33280

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/33280/files#r1496316367

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open all settings page (the wrench icon)
2. Right-click (web/desktop) or long-press (iOS/Android/mWeb) the subscriptions and cards menu
3. Verify a copy to clipboard menu shows and works correctly
4. 👍 or 👎

**Comment by sakluger** [comment] 2024-02-21 02:35
Thanks! I made a few changes to the testing steps:

- I separated Subscriptions from Cards & Domains into different steps
- In step 3, I used the exact menu copy (`Copy URL to clipboard`)
- In step 3, I clarified what the correct behavior is (ie. it should bring you to the corresponding settings page in OldDot).

We're good to close this one, thanks again!

**Closed by sakluger** 2024-02-21 02:35 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-02 13:59
$500 approved for @mollfpr based on summary above.
