### ISSUE TITLE
Unable to focus to the Cancel button using tab press - reported by @Santhosh-Sellavel 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9415] opened 2022-06-13 04:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app in web/desktop
2. Go to any chat
3. Send a message
4. Try to delete
5. Confirm option will appear
6. Try to focus Cancel button using by pressing tab key

## Expected Result:
Able to focus using tab

## Actual Result:
Unable to focus using tab

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173280116-8982db29-c142-4c16-b007-e824cbad67e3.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653423248591889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-06-21 17:01
You can close the modal by pressing `ESC`

**Comment by arosiclair** [comment] 2022-06-21 17:18
I agree. I reproduced the issue but I think `ESC` is a good enough work around for anyone trying to navigate this way. Closing.

**Closed by arosiclair** 2022-06-21 17:18 UTC
Labels: Engineering, Daily

**Comment by Santhosh-Sellavel** [comment] 2022-06-22 03:12
@arosiclair Issue is not about triggering cancel, focus should be set on 'Cancel' button while navigating with 'tab' or 'shift + tab'

cc: @luacmartins

**Comment by luacmartins** [comment] 2022-06-22 14:50
I agree with @roryabraham and @arosiclair here. As of now, we are making sure that 'tab' + 'shift + tab' is supported when navigating form inputs only. We do not support it everywhere else in the App yet.

**Comment by Santhosh-Sellavel** [comment] 2022-06-22 16:16
@luacmartins  or @roryabraham  or @arosiclair 

Cool for me, then if we are good to close #7968 too right?

Since this issue was an regression caused by #9093 I've added a comment there to put it on hold due until this one is fixed. 

Can anyone of you share a comment on #7968 too, Thanks!

**Comment by luacmartins** [comment] 2022-06-23 14:26
@Santhosh-Sellavel maybe I'm mistaken but the other issue seems to be different. I see that the Cancel button is focused, but pressing 'enter' still deletes the Workspace. I think we should fix that behavior.

**Comment by luacmartins** [comment] 2022-06-23 15:42
Ah I see! Since we can't select the Cancel button anymore I think it's ok to use 'Escape' to close the modal and 'Enter' to confirm deleting the Workspace. I'll leave a comment in the other issue.
