### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Prevent requesting money from domain emails

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#44429] opened 2024-06-26 07:55 UTC
Domain emails are in format `+@<domain>` like `+@expensify.com`.

### Problem
We allow users to request money from domains in newDot. Update the code so we don't allow this action.

<img width="383" alt="Screenshot 2024-06-26 at 1 10 52 PM" src="https://github.com/Expensify/App/assets/35863227/b3e8b748-0056-43e4-9fa1-40aa7e372610">
<img width="365" alt="Screenshot 2024-06-26 at 1 09 48 PM" src="https://github.com/Expensify/App/assets/35863227/51ef5a69-5fa5-415d-8220-b31873f3d873">

### Steps to reproduce:
1. From the global create button, select `Split expense`.
2. In the search field enter `+@applause.expensifail.com'` and confirm you are able to select that email as an option.

### Solution
Update the code to prevent users from requesting money from domain emails.
### Solution
Update the code to prevent users from requesting money from domain emails.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e28879d82637e16</li>
        <li>Upwork Job ID: 1805872485147678962</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 102895687</li>
<li>nkdengineer | Contributor | 102895688</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by nkdengineer** [comment] 2024-06-26 08:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We'd like to prevent requesting money from domain emails

### What is the root cause of that problem?
There's no logic to exclude domain emails when `getOptions`

### What changes do you think we should make in order to solve the problem?

Add a param `includeDomainEmail` to `getOptions` https://github.com/Expensify/App/blob/57e5d0e7197a9c21e6f221389bed87870c90ef0a/src/libs/OptionsListUtils.ts#L1769, default to `true`

In https://github.com/Expensify/App/blob/57e5d0e7197a9c21e6f221389bed87870c90ef0a/src/libs/OptionsListUtils.ts#L1915
add 
```
if (Str.isDomainEmail(email) && !includeDomainEmail) {
    return;
}
```

In the money request participants page, pass `includeDomainEmail` as `false`

### What alternative solutions did you explore? (Optional)

**Comment by techievivek** [comment] 2024-06-27 05:22
> So, I think all flows should be considered.

Yeah, we want to exclude them from all the flows as as they are not real users.

**Comment by iwiznia** [comment] 2024-06-27 08:36
Whatever we do here, we will ALSO need to update the backend @techievivek

**Comment by nkdengineer** [comment] 2024-06-27 08:38
@rayane-djouah this [PR](https://github.com/Expensify/App/pull/44525) is ready for preview

**Comment by techievivek** [comment] 2024-07-03 04:17
@iwiznia Yeah, backend already handles this exception correctly.
<img width="680" alt="Screenshot 2024-07-03 at 9 47 00 AM" src="https://github.com/Expensify/App/assets/35863227/f8a044d3-3d49-45a9-ada0-031f5a446a91">

**Comment by trjExpensify** [comment] 2024-07-03 14:32
@nkdengineer @techievivek did the PR for this also take care of preventing starting a chat, a group, assigning a task, inviting to a workspace.. basically filtering the domain account out of the participant selector everywhere? 

<img width="445" alt="image" src="https://github.com/Expensify/App/assets/16232057/32725b53-880c-41f8-9ac8-ee4ed6060970">

**Comment by techievivek** [comment] 2024-07-10 07:34
@trjExpensify Yeah, we have handled this for all cases; C+ confirmed this here: https://github.com/Expensify/App/issues/44429#issuecomment-2192166488.

**Comment by trjExpensify** [comment] 2024-07-10 17:43
> @trjExpensify Yeah, we have handled this for all cases; C+ confirmed this here: [#44429 (comment)](https://github.com/Expensify/App/issues/44429#issuecomment-2192166488).

Great stuff!

**Comment by isabelastisser** [comment] 2024-07-18 19:18
Bump @rayane-djouah to complete the BZ list, thanks!

**Comment by isabelastisser** [comment] 2024-07-18 19:21
The payments were processed in Upwork.

**Comment by isabelastisser** [comment] 2024-07-18 19:24
I will be OOO tomorrow and next week, so I am reassigning this until I return on July 29. Thanks, @adelekennedy!

Status:

- @rayane-djouah needs to complete the BZ list.

**Comment by techievivek** [comment] 2024-07-22 04:32
The regression test looks good to me; @adelekennedy, can we please get that added? Thanks.

**Comment by techievivek** [comment] 2024-07-22 04:46
Not overdue, completing the BZ list.

**Comment by adelekennedy** [comment] 2024-07-22 19:51
https://github.com/Expensify/Expensify/issues/414452

**Closed by adelekennedy** 2024-07-22 19:51 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by isabelastisser** [comment] 2024-07-29 14:27
Thanks, @adelekennedy !
