### ISSUE TITLE
[HOLD for payment 2024-05-08] CRITICAL: [Track expense] [$250] Make SmartScanning expense-level thread less confusing

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#40366] opened 2024-04-17 17:39 UTC
Problem:
====
When you scan a receipt, it shows this in the selfDM:

<img width="428" alt="image" src="https://github.com/Expensify/App/assets/575186/f5290ea2-61f0-40a0-829e-2e33eb283546">

When you click into it (sorry, different receipt) it looks like:

![image](https://github.com/Expensify/App/assets/575186/151d19b3-b9bf-4a48-b75c-e1b5a6020cf5)

This is pretty confusing as:

* The title is `Tracking $0.00`
* It shows `Amount * Cash` and `Merchant` fields, even though they are blank

Solution:
===
Please:
1. Make the header show `Scan in progress...` as the title while scanning, to match the scan preview in the parent chat
2. Show `Scanning...` inside `Amount * Cash` and `Merchant` fields while scanning
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145ed848b68697b8d</li>
        <li>Upwork Job ID: 1782614171256602624</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by dannymcclain** [comment] 2024-04-22 15:31
Here's a mock showing the UI with the updates:

![image](https://github.com/Expensify/App/assets/7516624/595dc1d0-d320-4677-86c9-c1588200b541)

> [!NOTE]
> The scanning "next steps" are being updated as part of [this issue](https://github.com/Expensify/App/issues/38688)—no need to worry about that here
> ![CleanShot 2024-04-22 at 10 30 20@2x](https://github.com/Expensify/App/assets/7516624/269abd74-4a0b-46cd-b84c-f9d187abf25f)
> ![CleanShot 2024-04-22 at 10 30 38@2x](https://github.com/Expensify/App/assets/7516624/53527237-a264-4023-ab55-34e0952c2660)

**Comment by Nodebrute** [comment] 2024-04-23 04:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make SmartScanning expense-level thread less confusing
### What is the root cause of that problem?
Feature Request
### What changes do you think we should make in order to solve the problem?

We can move this block of code above this [line](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/libs/ReportUtils.ts#L2619)
https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/libs/ReportUtils.ts#L2639-L2641

We should add in MoneyRequestView
```
 const isScanning = TransactionUtils.hasReceipt(transaction) && TransactionUtils.isReceiptBeingScanned(transaction);
```
https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/ReportActionItem/MoneyRequestView.tsx#L194-L195

Then we can use this to add scanning... in merchant and amount field. We can do something like this (Pseudocode)
```
const isScanning = TransactionUtils.hasReceipt(transaction) && TransactionUtils.isReceiptBeingScanned(transaction);
    const merchantTitle = isScanning ? translate('iou.receiptStatusTitle') : isEmptyMerchant ? '' : transactionMerchant
```

And then we can use merchantTitle here
https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/ReportActionItem/MoneyRequestView.tsx#L406
### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment] 2024-04-23 04:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
show "receipt being scanned" while the tracking receipt is scanning 
### What is the root cause of that problem?
1. Make the header show `Scan in progress`... as the title while scanning, to match the scan preview in the parent chat
2. Show Scanning... inside `Amount * Cash` and `Merchant` fields while scanning

### What changes do you think we should make in order to solve the problem?

- The request report title is calculated in the [getTransactionReportName](https://github.com/Expensify/App/blob/bde100174589e75ec3c84a305fc9745587a5fb56/src/libs/ReportUtils.ts#L2604) function, in this function we check if the request is track then return the title without considering if the receipt is still scanning. 
To fix that we can move the istrack [check](https://github.com/Expensify/App/blob/bde100174589e75ec3c84a305fc9745587a5fb56/src/libs/ReportUtils.ts#L2615-L2624) to be after the `hasMissingSmartscanFields` [check](https://github.com/Expensify/App/blob/bde100174589e75ec3c84a305fc9745587a5fb56/src/libs/ReportUtils.ts#L2642) 

- then to show `scanning ...`, we need to check if the transaction is scanning using:
```js
    const hasReceipt = TransactionUtils.hasReceipt(transaction);
    const isScanning = hasReceipt&& TransactionUtils.isReceiptBeingScanned(transaction);
```

then inside the [amount](https://github.com/Expensify/App/blob/62ef4b8b524c9bb345a9978297c8e65db7143c59/src/components/ReportActionItem/MoneyRequestView.tsx#L374) and [merchant title](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/ReportActionItem/MoneyRequestView.tsx#L406)  we should show  `receiptStatusTitle` if the isScanning is true

**Comment by abzokhattab** [comment] 2024-04-23 04:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
show "receipt being scanned" while the tracking receipt is scanning 
### What is the root cause of that problem?
1. Make the header show `Scan in progress`... as the title while scanning, to match the scan preview in the parent chat
2. Show Scanning... inside `Amount * Cash` and `Merchant` fields while scanning

### What changes do you think we should make in order to solve the problem?

- The request report title is calculated in the [getTransactionReportName](https://github.com/Expensify/App/blob/bde100174589e75ec3c84a305fc9745587a5fb56/src/libs/ReportUtils.ts#L2604) function, in this function we check if the request is track then return the title without considering if the receipt is still scanning. 
To fix that we can move the istrack [check](https://github.com/Expensify/App/blob/bde100174589e75ec3c84a305fc9745587a5fb56/src/libs/ReportUtils.ts#L2615-L2624) to be after the `hasMissingSmartscanFields` [check](https://github.com/Expensify/App/blob/bde100174589e75ec3c84a305fc9745587a5fb56/src/libs/ReportUtils.ts#L2642) 

- then to show `scanning ...`, we need to check if the transaction is scanning using:
```js
    const hasReceipt = TransactionUtils.hasReceipt(transaction);
    const isScanning = hasReceipt&& TransactionUtils.isReceiptBeingScanned(transaction);
```

then inside the [amount](https://github.com/Expensify/App/blob/62ef4b8b524c9bb345a9978297c8e65db7143c59/src/components/ReportActionItem/MoneyRequestView.tsx#L374) and [merchant title](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/components/ReportActionItem/MoneyRequestView.tsx#L406)  we should show  `receiptStatusTitle` if the isScanning is true

**Comment by Nodebrute** [comment] 2024-04-23 04:48
**[Proposal Updated](https://github.com/Expensify/App/issues/40366#issuecomment-2071384242)**
Alternative solution added

**Comment by Nodebrute** [comment] 2024-04-23 22:30
Hey, @fedirjh thank you. Just a suggestion, If we're moving the hasMissingSmartscanFields and hasReceipts checks above, then we'll need to move this [isEmptyObject](https://github.com/Expensify/App/blob/b386889b0f37c27351c08bc8c1af633c571c22be/src/libs/ReportUtils.ts#L2630-L2633) check as well. This will make the [isEmptyObject](https://github.com/Expensify/App/blob/b386889b0f37c27351c08bc8c1af633c571c22be/src/libs/ReportUtils.ts#L2620-L2622) check within the `isTrackExpenseAction` code redundant. To address this, let's make the following changes: update the isEmptyObject check, and remove the one from `isTrackExpenseAction`
```
  if (isEmptyObject(transaction)) {
        // Transaction data might be empty on app's first load, if so we fallback to Expense
        return ReportActionsUtils.isTrackExpenseAction(reportAction) ? Localize.translateLocal('iou.trackExpense') : Localize.translateLocal('iou.expense');
    }
```

**Comment by quinthar** [comment] 2024-04-25 00:43
Is this officially assigned to @Nodebrute ? If so, what is the ETA for completion?

**Comment by marcochavezf** [comment] 2024-04-25 01:04
Thanks for the review @fedirjh, assigning @Nodebrute 🚀

**Comment by quinthar** [comment] 2024-04-26 16:47
@Nodebrute what is your ETA?

**Comment by Nodebrute** [comment] 2024-04-26 18:57
@quinthar I'm working on a few minor adjustments to the PR. It won't take long; I'll have it done soon.

**Comment by JmillsExpensify** [comment] 2024-05-12 20:33
Payment summary:

 - Contributor: @Nodebrute $250 
 - Contributor+: @fedirjh $250

Note that this issue was created after the new pricing tiers went into effect. @fedirjh I also think we need to add a regression test for this issue, since the behavior of the app has changed. Do you mind suggesting one?

**Comment by Nodebrute** [comment] 2024-05-12 20:34
@JmillsExpensify this is a critical issue.

**Comment by JmillsExpensify** [comment] 2024-05-12 20:35
I understand, though it was a simple change.

**Comment by Nodebrute** [comment] 2024-05-12 20:38
As per [this](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1712256409152489) announcement, critical bugs are valued at $500

**Comment by JmillsExpensify** [comment] 2024-05-12 20:55
@mallenexpensify this isn't the first time I've seen confusion around CRITICAL issues. Can you chime in to help clear this up. I think we also probably need to consider another announcement for clarity.

**Comment by JmillsExpensify** [comment] 2024-05-14 22:23
Thanks for your patience on this issue. Everyone has been paid out based on the summary above, and @mallenexpensify expects to circle back on this later this week.

**Comment by JmillsExpensify** [comment] 2024-05-20 18:05
Circling back on this issue, I'm going to issue new Upwork contracts for the remaining $250 for each of C and C+. So $500 in total. We'll clarify our HIGH//CRITICAL process separately. Thanks everyone for their patience.

**Comment by JmillsExpensify** [comment] 2024-05-20 20:39
All Contributors paid $500 in total, so closing this issue out!

**Closed by JmillsExpensify** 2024-05-20 20:39 UTC
Labels: External, Daily, Improvement, Awaiting Payment
