### ISSUE TITLE
Web -  When click on requested IOU, the message "This is the beginning of the chat" is displayed for a brief period

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26116] opened 2023-08-28 19:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open a chat.
2. Navigate to the request money feature.
3. Enter a specific amount and request it.
4. Click on the requested money.
5. Then click on IOU to open its detail

## Expected Result:
When clicking on IOU for detail, the message "This is the beginning of the chat" should not be displayed

## Actual Result:
When click on requested IOU, the message "This is the beginning of the chat" is displayed for a brief period

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/460728f4-75cd-46f9-9af4-c4923f85496f

https://github.com/Expensify/App/assets/93399543/1e2463b8-60fe-4b32-93f4-70fce9d7f0c6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692982304284909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Ahmed-Abdella** [comment] 2023-08-28 23:21
This issue is dupe of https://github.com/Expensify/App/issues/26028, It is already reported and the PR https://github.com/Expensify/App/pull/26118 is done and ready for review

**Comment by luacmartins** [comment] 2023-08-28 23:46
Agree that it's a dupe and we can close this one!

**Closed by luacmartins** 2023-08-28 23:46 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by ayazhussain79** [comment] 2023-08-29 10:58
@luacmartins I have reported this issue https://github.com/Expensify/App/issues/26116 4 days ago before this one https://github.com/Expensify/App/issues/26028 which is reported 2 days ago

Can you please check that you can verify that on slack

**Comment by ayazhussain79** [comment] 2023-08-31 16:45
Thank you
