### ISSUE TITLE
[HOLD for payment 2024-11-14] [$500] Android - Avatar - Profile avatar can be seen only if tap on blank screen

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49553] opened 2024-09-20 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to any chat
2. Tap on user's avatar> Open the Avatar
3. Verify there is a blank screen and Avatar is not displayed
4. Tap on black screen

## Expected Result:
Profile avatar should be displayed when open it

## Actual Result:
Profile avatar can be seen only if tap on blank screen
Same issue occurs when Take photo

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/05367f4d-e64f-48cd-bf85-9ab211629dcb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837227522028493087</li>
        <li>Upwork Job ID: 1837227522028493087</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104697422</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment] 2024-09-20 19:28
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by huult** [comment] 2024-09-21 10:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android - Avatar - Profile avatar can be seen only if tap on blank screen

### What is the root cause of that problem?

The layout is not changing, so `onLayout` is not being called, which prevents `updateCanvasSize` from being triggered.
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Lightbox/index.tsx#L204-L207

So, the `canvasSize` will be `undefined`, and `isCanvasLoading` will be set to `true`.
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Lightbox/index.tsx#L94-L95

`isCanvasLoading` is `true`, the image component will not render, resulting in a blank screen, and this issue occurs
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Lightbox/index.tsx#L208

### What changes do you think we should make in order to solve the problem?

We should use a ref so that the measurement occurs after the component has mounted, something like this:
```diff
// .src/components/Lightbox/index.tsx#L167
+    const viewRef = useRef<View>(null);

// .src/components/Lightbox/index.tsx#L172
+    useEffect(() => {
+        viewRef?.current?.measure((x, y, width, height, pageX, pageY) => {
+            setCanvasSize({width: PixelRatio.roundToNearestPixel(width), height: PixelRatio.roundToNearestPixel(height)});
+        });
+    }, []);

// .src/components/Lightbox/index.tsx#L204
        <View
            style={[StyleSheet.absoluteFill, style]}
            onLayout={updateCanvasSize}
+            ref={viewRef}
        >

```

<summary>
<details>POC

https://github.com/user-attachments/assets/765c8d29-8bcb-44da-9b88-64ca2639efb8

</details>
</summary>

**Comment by struc** [comment] 2024-09-21 11:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Avatar image does not show up or load.
### What is the root cause of that problem?
On mobile, we use Lightbox to render the avatar image, however `onLayout` is never called because the view does not have a defined size yet.

Which also means the image view is never mounted and `ImageView.onload` is also never called.
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Lightbox/index.tsx#L204-L207

### What changes do you think we should make in order to solve the problem?
Initialize canvasSize with any value (i.e 0x0) will force a layout and mount the image view and thus load the image.

so we replace

https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Lightbox/index.tsx#L94

with

```typescript
const [canvasSize, setCanvasSize] = useState<CanvasSize>({width: 0, height: 0});
```
### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment] 2024-09-23 11:00
## [Updated Proposal](https://github.com/Expensify/App/issues/49553#issuecomment-2365137733)

- Add a new RCA.
- Update the new solutions.
- Adjust the alternative solution.

**Comment by huult** [comment] 2024-09-27 16:26
@dukenv0307 ,
I believe this issue is related to the rendering process in Android React Native. According to my RCA, the `AttachmentView` is rendered last, after all other components. I'm unsure why the `onLayout` is being prevented in `AttachmentView`.

With the solution I provided, rendering the `Send Button` at the same time as the `AttachmentView` seems reasonable and fixes the issue. I also tested it on the web and iOS, and it is still working well.

**Comment by puneetlath** [comment] 2024-10-06 19:34
@huult are you still interested in trying to find a solution for this?

**Comment by huult** [comment] 2024-10-07 02:13
@puneetlath , Currently, I have found a workaround solution to fix this issue by rendering the `Send Button` at the same time as the `AttachmentView`. However, I have not yet found the exact root cause of why this issue only occurs on Android. 

With the change below, I tested it and it's working as expected.

```diff
// .src/components/AttachmentModal.tsx#L580
- {!!onConfirm && !isConfirmButtonDisabled && (
+ {!!onConfirm && !isConfirmButtonDisabled && shouldLoadAttachment && (
```

**Comment by puneetlath** [comment] 2024-10-07 16:29
Ah ok I see. I think we should ideally try to figure out the root cause before proceeding with that solution.

**Comment by huult** [comment] 2024-10-07 16:35
Yes, I've been debugging this many times, but I still haven't figured it out yet. =]] I'll post the exact RCA if I can find it

**Comment by puneetlath** [comment] 2024-10-15 14:57
Increasing to $500 to see if we can get more proposals.

**Comment by wildan-m** [comment] 2024-10-17 10:07
@dukenv0307, @IuliiaHerets Can you consistently reproduce it? I initially experienced it, but now it's not reproducible after retrying the steps.

Which Android device/version are you using?

**Comment by wildan-m** [comment] 2024-10-21 10:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Profile avatar can be seen only if tap on blank screen

### What is the root cause of that problem?

The onLayout behavior differs between iOS and Android due to various factors. https://github.com/facebook/react-native/issues/28775#issuecomment-668831226 I believe `isCanvasLoading` is preventing the child component from being displayed, thus not triggering `onLayout` due to the lack of changes in the child component.

### What changes do you think we should make in order to solve the problem?

React Native Pager View faced a similar issue, which they addressed by manually refreshing the children layout in the Android code.
https://github.com/callstack/react-native-pager-view/pull/351

Use `PagerView` instead of creating a new container for the single attachment view in `src/components/AttachmentModal.tsx`. Wrap `AttachmentView` with `PagerView` and disable scrolling to prevent image stretching.

```tsx

                                        <PagerView
                                            useNext={shouldUseNewPager()}
                                            style={[styles.imageModalImageCenterContainer]}
                                            scrollEnabled={false}
                                        >
                                            <AttachmentView
                                                containerStyles={[styles.mh5]}
                                                source={sourceForAttachmentView}
                                                isAuthTokenRequired={isAuthTokenRequiredState}
                                                file={file}
                                                onToggleKeyboard={setIsConfirmButtonDisabled}
                                                onPDFLoadError={() => {
                                                    isPDFLoadError.current = true;
                                                    setIsModalOpen(false);
                                                }}
                                                isWorkspaceAvatar={isWorkspaceAvatar}
                                                maybeIcon={maybeIcon}
                                                fallbackSource={fallbackSource}
                                                isUsedInAttachmentModal
                                                transactionID={transaction?.transactionID}
                                                isUploaded={!isEmptyObject(report)}
                                            />
                                        </PagerView>

```


[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/49553-android-child-not-updated-pagerview-approach?expand=1)
### What alternative solutions did you explore? (Optional)

Prevent `isCanvasLoading` from blocking the child component render in `src/components/Lightbox/index.tsx`

We've already provide logic to show loading indicator and show fallback image, we don't need to hide all child components
We can disable MultiGestureCanvas if it's not loaded yet

change the render logic to:
```tsx

        <View
            style={[StyleSheet.absoluteFill, style]}
            onLayout={updateCanvasSize}
        >
            <>
                {isLightboxVisible && (
                    <View style={[StyleUtils.getFullscreenCenteredContentStyles(), StyleUtils.getOpacityStyle(Number(shouldShowLightbox))]}>
                        <MultiGestureCanvas
                            isActive={isActive && !isCanvasLoading}
                            canvasSize={canvasSize}


```

canvas size will require initial value
```tsx

    const [canvasSize, setCanvasSize] = useState<CanvasSize>({width: 0, height: 0});
    const isCanvasLoading = canvasSize.height === 0 && canvasSize.width === 0;

```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/49553-set-init-approach)

**Comment by wildan-m** [comment] 2024-10-22 04:27
[Proposal Updated](https://github.com/Expensify/App/issues/49553#issuecomment-2426256591)
- Wrap pagerview childs with View
- Update branch

@dukenv0307 Ah, forgot this warning

> Attention: Note that you can only use View components as children of PagerView
https://github.com/callstack/react-native-pager-view?tab=readme-ov-file#usage

We should wrap inner element with `View` based on their guide

**Comment by wildan-m** [comment] 2024-10-22 05:06
I've created PagerView wrapper for native specific code, non native will render it as standard View, so it won't error in non native

**Comment by s77rt** [comment] 2024-10-28 21:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The avatar is not displayed unless you tap on the screen

### What is the root cause of that problem?
This is a bug in RN. The `onLayout` event is not called in time because after the app is put on background (which happens after opening the attachment picker) the `AndroidEventBeat` ticker no longer ticks for every frame even after the app is on foreground. This is due to a stale flag ([`mShouldStop`](https://github.com/facebook/react-native/blob/3111473d571a8315d11753f8c6acddd2ba301f8f/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/FabricEventDispatcher.java#L174)) that is set to `true` on host pause and never reset on host resume. 

### What changes do you think we should make in order to solve the problem?
Reset `mShouldStop` to `false` on host resume. 

### What alternative solutions did you explore? (Optional)
Use the experimental event batching mechanism ([`useOptimizedEventBatchingOnAndroid`](https://github.com/facebook/react-native/blob/92d743a9ab5d9f9b57725b6e6b86178a6c2a1549/packages/react-native/scripts/featureflags/ReactNativeFeatureFlags.config.js#L456-L464)) (not tested - not for production)

**Comment by s77rt** [comment] 2024-10-28 21:30
I have raised a RN PR for feedback from Meta https://github.com/facebook/react-native/pull/47264

**Comment by s77rt** [comment] 2024-10-28 21:34
https://github.com/user-attachments/assets/60536c58-9fec-48fc-a765-01461c6b033e


https://github.com/user-attachments/assets/8db3f797-3965-4e1d-a569-c4ce7b55be38

**Comment by s77rt** [comment] 2024-10-29 23:14
The RN PR https://github.com/facebook/react-native/pull/47264 is merged 🎉

**Comment by danieldoglas** [comment] 2024-11-01 16:31
Assigned @s77rt !

**Comment by s77rt** [comment] 2024-11-07 19:27
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [X] 1z. Other: Upstream bug (react-native)

Where bug was reported:
  - [X] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: n/a (upstream bug)

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: I don't think this would resurface since it's not from our side (we can't break the logic)

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by puneetlath** [comment] 2024-11-14 22:10
Payment summary: 
- C - $500 - @dukenv0307 - to be paid via Upwork
- C+ - $500 - @s77rt - to be paid via NewDot

@dukenv0307 can you please accept the Upwork offer and ping me here when you have?

**Comment by puneetlath** [comment] 2024-11-18 16:38
All paid. Thanks y'all!

**Closed by puneetlath** 2024-11-18 16:38 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
