### ISSUE TITLE
[HOLD for payment 2024-01-24] [$250] Workspace members - Members deleted offline are not crossed out

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28807] opened 2023-10-04 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with account
3. Go to Settings -> Workspace -> Open any WS -> Invite several members
4. Turn off the internet connection
5. Delete WS member

## Expected Result:
Members deleted offline crossed out

## Actual Result:
Members deleted offline are not crossed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.77-2

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/773a5260-8d25-4ba6-9a53-048647e0a73b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d912d0feb7321c7</li>
        <li>Upwork Job ID: 1709541114926034944</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27291935</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-04 12:10
Not repro on Prod 

https://github.com/Expensify/App/assets/115492554/716d13ea-0386-418a-9bf9-e5dd6a5c25c6

**Comment by izarutskaya** [comment] 2023-10-04 12:14
Not repro on Prod

https://github.com/Expensify/App/assets/115492554/30931c43-aa2f-43c4-b0b9-e02cdb5fa244

**Comment by kbecciv** [comment] 2023-10-04 13:09
@mountiny I'm able to reproduce the issue in staging and production in IOS app. 

https://github.com/Expensify/App/assets/93399543/10ad0998-64a4-41ba-89c4-99f6e9d9de22


https://github.com/Expensify/App/assets/93399543/6c579e72-a3d1-4a5f-9de4-83dfb92d1123

**Not able to reproduce on Android production build v1.3.69-2**


https://github.com/Expensify/App/assets/93399543/f218458f-6e86-46f7-8069-15416e3b46e7

Would you like us to keep the DB label or remove it?

**Comment by mountiny** [comment] 2023-10-04 13:23
Same for mweb 
<img width="565" alt="image" src="https://github.com/Expensify/App/assets/36083550/7d4818b8-730b-44dd-987b-fc13b526e3c3">


I am going to remove the blocker label, lets see if people can reliably reproduce this one

**Comment by mountiny** [comment] 2023-10-09 15:02
I think its a minor issue, the user is removed, but on native its not strikethrough. It also has been a deploy blocker which makes finding the root cause a bit easier. if nobody will be willing to solve this for that bounty eventually we increase the price

**Comment by Li357** [comment] 2023-10-09 16:16
@mountiny Since this isn't a deploy blocker anymore, can I remove my assignment and wait for contributor proposals here?

**Comment by mountiny** [comment] 2023-10-09 17:49
I would stay assigned, you dont have to act on this, but since you have already been autoassigned, if you remove yourself, then this will autoassign someone else. I think its fine to stay assigned just monitor the issue. Thats what I usually do but there is no strict guideline, up to you

**Comment by Swor71** [comment] 2023-10-10 09:01
Hey, I'm Marcin from Callstack - expert contributor group - I would like to help resolve this issue

**Comment by Swor71** [comment] 2023-10-13 12:09
Update: Hey, I'm still looking into this issue, however no luck so far in finding the root cause

**Comment by miljakljajic** [comment] 2023-10-17 16:13
We can assign to @Swor71 !

**Comment by Swor71** [comment] 2023-10-20 07:05
hey, apologies for lack of updates, I am still looking into this and I think I know why this is happening, currently trying to find the best approach to fixing this

**Comment by Swor71** [comment] 2023-10-25 13:23
hey, I have been assigned to the Wave6 project, which is very high priority at the moment, therefore someone from Callstack will most likely take this one over from me

**Comment by koko57** [comment] 2023-10-27 14:47
@hoangzinh I'm taking over this issue from Marcin

**Comment by koko57** [comment] 2023-11-02 07:55
Sorry for no updates - I'm still working on my other issues - I will look at it soon

**Comment by miljakljajic** [comment] 2023-11-02 14:44
Confirming [here](https://expensify.slack.com/archives/C9YU7BX5M/p1698936224603969) what the actual expected behaviour is.

**Comment by miljakljajic** [comment] 2023-11-02 14:56
So from my understanding and from discussing with the Applause team - this is actually expected behaviour. We'd expect the users to disappear from the list when we reconnect to the internet, crossed out and greyed out are patterns only seen when the action you took has not been processed by the server.

Feel free to reopen if I've misunderstood or missed anything but based on the steps and outcomes in the OP the product is working correctly.

**Comment by koko57** [comment] 2023-11-07 07:28
Hello @hoangzinh @miljakljajic what's the status of this issue? Should it be reopened?

**Comment by lanitochka17** [comment] 2023-11-15 13:56
Issue reproducible on the latest build 1.3.99-0


https://github.com/Expensify/App/assets/78819774/2da4e8bf-273a-4d00-9b18-57bb97e35039

**Comment by miljakljajic** [comment] 2023-12-08 15:37
@mountiny - does this seem like expected behaviour to you? When I raised this in QA they told me it was working as expected but perhaps I've misunderstood something? https://expensify.slack.com/archives/C9YU7BX5M/p1698936224603969

**Comment by mountiny** [comment] 2023-12-08 15:47
Maybe there is misunderstanding, in you post I see you have asked about the state when you go abck online, in such case the member/ workspace should disappear as its deleted also  in backend

But if action is taken offline and you are still offline, then until you come back online and the request can get synced with the backend it should be crossed out as pending

**Comment by miljakljajic** [comment] 2023-12-08 15:55
Ahhh thank you Vit! Alright, we're good to work on this!

**Comment by keisyrzk** [comment] 2023-12-11 10:11
@hoangzinh Hey, I am from Callstack and will take over this issue from Agata (koko57). Will send proposal soon.

**Comment by keisyrzk** [comment] 2023-12-11 12:03
Proposal
**Please re-state the problem that we are trying to solve in this issue.**
If the invited user in workspace members is deleted staying in offline mode - this user's row is not crossed out but should be.

**What is the root cause of that problem?**
There is no styling condition for crossing out the text if "delete" action is pending.

**What changes do you think we should make in order to solve the problem?**
Add the condition for pending "delete" action in BaseListItem as follows:

```js
item.pendingAction === 'delete' ? styles.offlineFeedback.deleted : null
```
for both textStyles and alternateTextStyles in here
```js
<ListItem
                        item={item}
                        textStyles={[
                            styles.optionDisplayName,
                            isFocused ? styles.sidebarLinkActiveText : styles.sidebarLinkText,
                            isUserItem || item.isSelected ? styles.sidebarLinkTextBold : null,
                            styles.pre,
                            item.pendingAction === 'delete' ? styles.offlineFeedback.deleted : null,
                        ]}
                        alternateTextStyles={[
                            styles.optionAlternateText, 
                            styles.textLabelSupporting, 
                            isFocused ? styles.sidebarLinkActiveText : styles.sidebarLinkText, 
                            styles.pre,
                            item.pendingAction === 'delete' ? styles.offlineFeedback.deleted : null,
                        ]}
(...)
```

**What alternative solutions did you explore? (Optional)**
NA

**Comment by keisyrzk** [comment] 2023-12-12 12:31
@hoangzinh I suspect that this is about multiple styling for `ListItem` and the parent components as well. Lets add to this `textDecorationLine` that might be rendered not the same way on the web and mobile.
We consider the `offlineFeedback.deleted` that is applied with
```js
offlineFeedback: {
            deleted: {
                textDecorationLine: 'line-through',
                textDecorationStyle: 'solid',
            }
```
I found that `textDecorationLine` should be applied directly to the Text component to make it work properly on ios and android as it does not work if expected to inherit this styling from aprent.
I believe it indeed might be the thing.

**Comment by keisyrzk** [comment] 2023-12-14 06:28
@hoangzinh @Li357 up^ :)

**Comment by keisyrzk** [comment] 2023-12-15 12:39
In theory yes but we see that it is not and this is why the style is not applied.
I checked what happens in the `applyStrikeThrough` function and the `line-through` is "trying" to be applied but in the result it in set to "none".
The reason might albo be the fact that in this particular place the compiler sees `View` not `Text` or ListItem` and `line-through` applying fails just because of the child's type.

**Comment by keisyrzk** [comment] 2023-12-18 06:16
@hoangzinh It looks like that this works as well.
Here are the necessary changes in `UserListItem` then:

```js
(...)
import useStyleUtils from '@styles/useStyleUtils';

function UserListItem({item, textStyles, alternateTextStyles, showTooltip, style}) {
     const StyleUtils = useStyleUtils();
     (...)

     <Text
           style={StyleUtils.combineStyles(textStyles, style)}
           numberOfLines={1}
       >

      (...)

     <Text
          style={StyleUtils.combineStyles(alternateTextStyles, style)}
          numberOfLines={1}
      >
}
```

Your decision which way we go then :)

**Comment by keisyrzk** [comment] 2023-12-18 10:10
@hoangzinh ah ok :)
Well, both are fine fot me. 
I am not sure if the `BaseListItem` is more general component than `UserListItem` or not. `BaseListItem` seems to be more accurate candidate from my perspective.
Do you have a wider perspective which of these two is more general in app context? I woudl apply the "fix" to that one :)

**Comment by keisyrzk** [comment] 2023-12-18 10:37
I have not found any solution so we could apply some changes to the `applyStrikeThrough` itself unfortunately.
So to conclude - you prefer your suggestion right?

**Comment by keisyrzk** [comment] 2023-12-18 12:26
@hoangzinh 
Indeed. 
Having that discussed, do you believe applying changes to `UserListItem` as discussed is satisfying solution then?

**Comment by situchan** [comment] 2023-12-22 14:32
FYI: @Li357 is no longer on Expensify

**Comment by miljakljajic** [comment] 2023-12-22 14:40
Thanks @hoangzinh! Sorry for missing the tag for Andrew earlier.

**Comment by madmax330** [comment] 2024-01-03 06:27
This solution looks good to me: https://github.com/Expensify/App/issues/28807#issuecomment-1858252635

**Comment by madmax330** [comment] 2024-01-03 07:48
Done

**Comment by keisyrzk** [comment] 2024-01-08 08:21
@hoangzinh @madmax330 
To conclude - is the solution (posted below as reminder) accepted so I could make a PR?

```js
Changes in `UserListItem` as follows

(...)
import useStyleUtils from '@styles/useStyleUtils';

function UserListItem({item, textStyles, alternateTextStyles, showTooltip, style}) {
     const StyleUtils = useStyleUtils();
     (...)

     <Text
           style={StyleUtils.combineStyles(textStyles, style)}
           numberOfLines={1}
       >

      (...)

     <Text
          style={StyleUtils.combineStyles(alternateTextStyles, style)}
          numberOfLines={1}
      >
}
```

**Comment by miljakljajic** [comment] 2024-01-22 11:50
@hoangzinh I sent you a new offer, the previous one expired. Accept it when you can so I can pay promptly on the 24th!

**Comment by miljakljajic** [comment] 2024-01-22 11:55
new offer to pay on 24: https://www.upwork.com/nx/wm/offer/100561859

**Comment by miljakljajic** [comment] 2024-01-24 14:58
Paid and closing

**Closed by miljakljajic** 2024-01-24 14:58 UTC
Labels: Engineering, Weekly, Internal, Awaiting Payment, Bug
