### ISSUE TITLE
 “Almost done!” screen flashes for a moment while navigating back from ‘Connect bank account’ screen reported by @aswin-s

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9308] opened 2022-06-03 11:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspace settings.
2. Tap on reimburse expense/pay bills/ send invoice menu and tap on ‘connect bank account’ and then tap on ‘connect manually’
3. Now navigate back to workspace settings home by tapping on back button.

## Expected Result:
Should be able to navigate back to workspace settings page without any flashing

## Actual Result:
Notice the ‘Almost done!’ screen flashing in between the navigation.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** v1.1.71-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/171841646-5b68d1f4-bcbb-4bf6-ab08-146b56caab62.mp4
<img width="264" alt="Screenshot (367)" src="https://user-images.githubusercontent.com/43996225/171842215-32b0172f-4b3e-43cd-8f0e-56742ff6b833.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  @aswin-s

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-06-03 11:07
dupe of https://github.com/Expensify/App/issues/8541

**Comment by kadiealexander** [comment] 2022-06-06 23:03
Closing as dupe of https://github.com/Expensify/App/issues/8541

**Closed by kadiealexander** 2022-06-06 23:03 UTC
Labels: Daily, Overdue
