### ISSUE TITLE
[HOLD for payment 2024-06-11] [$500] Private notes - Hmm its not here page displayed when clicking on thumbnail

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38835] opened 2024-03-22 20:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37566
## Action Performed:
1. Navigate to any report
2. Click on header > Private notes
3. Add markdown image to private notes: holla ![off](https://images.unsplash.com/photo-1705467648979-f66c9584827a?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
)
4. Click on 'Private notes'
5. Click on the image

## Expected Result:
* Image should be opened in the attachment carousel just like any image added to Expensify Chat 

## Actual Result:
* Hmm its not here page is displayed.
* And markdown images are rendered in Private notes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/babb6b39-c2f7-4739-a88c-dd90e35844e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c6ef0c33505c63ef</li>
        <li>Upwork Job ID: 1771446597185703936</li>
        <li>Last Price Increase: 2024-03-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by lanitochka17** [comment] 2024-03-22 20:34
@chiragsalian  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by situchan** [comment] 2024-03-22 20:37
Don't think this is blocker since markdown image is new feature and still WIP of polish

cc: @kidroca

**Comment by chiragsalian** [comment] 2024-03-22 21:40
Yup, I agree too. This does not feel blocker-worthy since it's a new feature. A simple resolution would be to revert the feature here - https://github.com/Expensify/App/pull/37566 but I would prefer if move forward and tidy up this bug.

**Comment by roryabraham** [comment] 2024-03-23 00:20
edge case that I wouldn't consider much of a blocker, but what I would recommend is that it opens an attachment carousel that only includes attachments in the `private notes` message.

**Comment by roryabraham** [comment] 2024-03-23 00:21
in my opinion the value of inline images way outweighs the downside of this bug, so I wouldn't want to see us revert that because of this

**Comment by nkdengineer** [comment] 2024-03-23 05:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Private notes - Hmm its not here page displayed when clicking on thumbnail
### What is the root cause of that problem?
- We use [ImageRenderer](https://github.com/Expensify/App/blob/main/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx) to display image
- When clicking on an image to open the attachment modal, [onPress](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L83) is called, it works well with report attachments. But in case of private note, the not here page is displayed
### What changes do you think we should make in order to solve the problem?
- We need to create a new attachment page to display image for other images that do not belong to report.
1. Create a CommonAttachments page:
```
function CommonAttachments({route}: ReportAttachmentsProps) {
    const source = Number(route.params.source) || route.params.source;
    const imageSource = tryResolveUrlFromApiRoot(source);
    return (
        <AttachmentModal
            allowDownload
            defaultOpen
            source={imageSource}
            onModalClose={() => {
                Navigation.goBack();
            }}
            onModalHide={() => {
                Navigation.dismissModal();
                // This enables Composer refocus when the attachments modal is closed by the browser navigation
                ComposerFocusManager.setReadyToFocus();
            }}

        />
    );
}
```
2. In [here](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/SCREENS.ts#L13), add:
```
    ATTACHMENTS: 'attachments',
```
3. In [here](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/ROUTES.ts#L14), add:
```
    ATTACHMENTS: {
        route: '/attachment',
        getRoute: (source: string) => `attachment?source=${source}` as const
    }
```
4. In [here](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L263), add:
```
                 <RootStack.Screen
                    name={SCREENS.ATTACHMENTS}
                    options={{
                        headerShown: false,
                        presentation: 'transparentModal',
                    }}
                    getComponent={loadCommonAttachments}
                    listeners={modalScreenListeners}
                />
```

5. In [here](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/Navigation/linkingConfig/config.ts#L11), add:
```
        [SCREENS.ATTACHMENTS]: ROUTES.ATTACHMENTS.route,
```

6. Update [this](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L83-L86) to:
```
                    onPress={() => {
                       if(report?.reportID){
                        const route = ROUTES.REPORT_ATTACHMENTS.getRoute(report?.reportID ?? '', source);
                        Navigation.navigate(route);
                       }
                       else {
                        const route = ROUTES.ATTACHMENTS.getRoute(source)
                        Navigation.navigate(route)
                       }
                    }}
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by MitchExpensify** [comment] 2024-03-25 01:32
Switching to daily as [not deemed](https://github.com/Expensify/App/issues/38835#issuecomment-2016216142) a blocker

**Comment by kidroca** [comment] 2024-03-25 11:21
When viewing attachments in a chat, we can easily navigate between them through the attachment modal. However, for notes with multiple images, it seems we have to close and reopen the modal for each image. The presence of both `attachments` and `chat-attachments` could lead to confusion. A generic component like the `ImageRenderer` would require additional logic to differentiate between them, increasing the dependency on specific details. Wouldn't it be more efficient to consolidate them into a single route, either `attachments` or `chat-attachments`, and use parameters (source, reportID, noteID) to:
- Display a single image if only `source` is provided.
- Show report attachments and begin from the source when `reportID` is available.
- Display note attachments if `noteID` is specified.

This approach could simplify the process and reduce complexity.

**Comment by roryabraham** [comment] 2024-03-25 17:21
I agree with @kidroca - it sounds like a good way to DRY things up and simplify.

**Comment by chiragsalian** [comment] 2024-03-25 17:27
Just catching up here too and I like @kidroca's suggestion as well.

**Comment by nkdengineer** [comment] 2024-03-25 17:36
What I am concerned is that, with other inputs like, task title, task description, ... we can also use image markdown. So what does the route look like?

**Comment by MitchExpensify** [comment] 2024-03-26 16:59
I am unsure who if anyone uses private notes especially for images which is causing me pause with regards to which wave or VIP this fits under. This seems super low priority to me

**Comment by chiragsalian** [comment] 2024-03-26 18:14
I think its VIP-vsb right, same as the issue that created this bug - [this one](https://github.com/Expensify/App/issues/37246). Even if its rare since our product support inline images i feel like we should solve this bug. Because now a user can add an image to notes and if we don't fix this then whenever they click on the image they'll get an error screen.
I feel like we should solve this.

I feel like we should build a solution to support clicking markdown images besides for just notes. Like maybe even for an expense description and other spots if needed.

We could discuss in #product if we would prefer to disable clicking images or image markdown anywhere besides on chats. But if we have them then i think allowing them to be clickable might be the better user experience.

**Comment by nkdengineer** [comment] 2024-03-26 19:42
@chiragsalian With this [suggestion](https://github.com/Expensify/App/issues/38835#issuecomment-2017780596), what will the route look like? Currently, the report attachment has route: ```r/:reportID/attachment?source={source}```

**Comment by chiragsalian** [comment] 2024-03-26 20:03
From kidroca suggestion i think the idea is to modify `REPORT_ATTACHMENTS` ([code](https://github.com/Expensify/App/blob/c809723d0bb4161ac0a0d135eeadf592f83356d8/src/ROUTES.ts#L205-L208)) into something more generic like `ATTACHMENTS`. 

As for how the route will look. I'm unsure, maybe something like this,
```
ATTACHMENTS: {
    route: 'a/:ID/attachment',
    getRoute: (ID: string, source: string, sourceURL: string) => `r/${ID}/attachment?source=${source}&sourceURL=${encodeURIComponent(sourceURL)}` as const,
},
```
ID could be reportID, noteID, reportActionID (for expense description)
source could be 'report', 'note', 'reportActionID' etc so that the attachment component would know what logic to fall into.
sourceURL is the image URL

@kidroca, since you are more aware of this can you double-check and lend us your thoughts.

**Comment by MitchExpensify** [comment] 2024-03-27 04:11
> I think its VIP-vsb right, same as the issue that created this bug - https://github.com/Expensify/App/issues/37246.

Good shout! Thanks for the buddy check

**Comment by MitchExpensify** [comment] 2024-03-27 04:13
> We could discuss in #product if we would prefer to disable clicking images or image markdown anywhere besides on chats. But if we have them then i think allowing them to be clickable might be the better user experience.

That sounds like a great next step to me! Are you planning to post or should I grab?

**Comment by chiragsalian** [comment] 2024-03-27 19:55
Can you post and ask @MitchExpensify

**Comment by nkdengineer** [comment] 2024-03-28 14:48
I am still waiting for final decision before creating PR

**Comment by MitchExpensify** [comment] 2024-03-30 21:10
Brought to Slack here, will report back https://expensify.slack.com/archives/C066HJM2CAZ/p1711833001511819

**Comment by MitchExpensify** [comment] 2024-04-01 21:21
Would expense comments with markdown images break exports @chiragsalian ?

**Comment by MitchExpensify** [comment] 2024-04-01 22:01
So hold on this is what you are thinking @chiragsalian ? [HIGH: [Polish] Add support for image-only (no alt text) inline image Markdown](https://github.com/Expensify/App/issues/38952#top)

**Comment by chiragsalian** [comment] 2024-04-01 22:56
> Would expense comments with markdown images break exports @chiragsalian ?

No clue, do you mean would it break export like pdf export? 
If so then no I don't think so exactly. I'm pretty sure markdown images gets converted to regular attachments in the database. So for export functionality like pdf export, once implemented it loads in the image URLs from the database so if it has issues displaying inline images it will have issues with attachments too. Both of which would be handled in a separate issue specific to export IMO.

> So hold on this is what you are..

No not exactly, that issue is about removing the need for alt text in inline image.
This would be the issue to HOLD on - https://github.com/Expensify/App/issues/39275

**Comment by kidroca** [comment] 2024-04-03 12:31
> @kidroca, since you are more aware of this can you double-check and lend us your thoughts.

Apologies for the delayed response. Your understanding was close; here's the precise implementation I had in mind:

```js
ATTACHMENTS: {
    route: '/attachment(s)',
    getRoute: (id, type, url) => 
        `/attachments?type=${type}&uri=${encodeURIComponent(url)}${id ? `&id=${id}` : ''}`,
},
```

Here's a quick breakdown:
- The `id` parameter is optional, which is why I decided against using `/attachments/:id`. It could refer to various IDs like report, comment, or note ID, allowing us to include attachments only for the given item.
- The `type` parameter is intended to be an enum, indicating the attachment's context, such as a report, report action, note, or a single attachment:
    ```ts
    enum AttachmentType {
       Report = 'r',
       ReportAction = 'a',
       Note = 'n',
       Single = 's',
    }
    ```
- The `uri` parameter is the source link. I'm currently exploring options to either eliminate or shorten the `uri`, as it tends to fill the address bar with a lengthy string. Moreover, if it becomes excessively long, we may encounter limitations. However, this should not block the current issue and can be addressed later.

---

Consider the above a working draft that can be further tailored to suit our needs. For example, the `type` parameter can be optional, its absence meaning we're dealing with a single attachment.

**Comment by MitchExpensify** [comment] 2024-04-08 02:24
What is the latest on our proposals here?

**Comment by MitchExpensify** [comment] 2024-04-12 00:31
Friendly bump @shubham1206agra

**Comment by nkdengineer** [comment] 2024-04-12 01:48
I see that this issue is hold on #39275

**Comment by chiragsalian** [comment] 2024-04-16 22:55
Issue is off hold

**Comment by chiragsalian** [comment] 2024-04-19 19:16
i would say that we should display the note's attachment in a carousel. Such that if there are multiple attachments they can easily navigate between them in the carousel.

**Comment by MitchExpensify** [comment] 2024-04-22 22:00
How is the PR coming along @nkdengineer ?

**Comment by nkdengineer** [comment] 2024-04-24 00:29
I am working on it. The draft PR is [here](https://github.com/Expensify/App/pull/40844)

**Comment by nkdengineer** [comment] 2024-04-25 08:05
@shubham1206agra PR https://github.com/Expensify/App/pull/40844 is ready

**Comment by MitchExpensify** [comment] 2024-05-22 19:47
@shubham1206agra how is the PR review coming along? https://github.com/Expensify/App/pull/40844

**Comment by MitchExpensify** [comment] 2024-06-13 22:19
Payment summary:

- $500 @shubham1206agra requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer)
- $500  @nkdengineer requires payment (Needs manual offer from BZ)

**Comment by MitchExpensify** [comment] 2024-06-13 22:23
paid and contract ended, @shubham1206agra 🙇

**Comment by MitchExpensify** [comment] 2024-06-15 20:58
> Am I missing something here. Why the payout is decreased here?

I saw the Upwork job created a $250 amount automatically so I was basing it off that. I will update if $500 is correct

**Comment by MitchExpensify** [comment] 2024-06-15 21:14
I think I got my wires crossed with this similar looking job on Upwork: https://www.upwork.com/nx/wm/workroom/37532304/details

Sorry about that @shubham1206agra !

**Comment by MitchExpensify** [comment] 2024-06-17 03:14
Paid and contract ended, thanks! Do we need BZ steps here?

**Comment by chiragsalian** [comment] 2024-06-19 19:37
@MitchExpensify anything pending here or can we close this out.

**Closed** 2024-06-20 00:30 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by nkdengineer** [comment] 2024-07-01 12:11
Sorry @MitchExpensify It seems I wasn't paid here, could you please reopen the issue to help with this?

TIA

**Comment by MitchExpensify** [comment] 2024-07-02 17:07
Oh weird, it looks like the automation flagged you as due to be paid via New Expensify so I thought we were all done:

> @nkdengineer requires payment (Needs manual offer from BZ)

Here's a new offer to resolve this https://www.upwork.com/nx/wm/offer/102961478

**Comment by MitchExpensify** [comment] 2024-07-02 17:10
Paid and contract ended, thanks for the catch @nkdengineer
