### ISSUE TITLE
[HOLD for payment 2023-08-02] Task - Long task description is truncated in chat and overlapped by expand button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23410] opened 2023-07-22 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23246
## Action Performed:
1. Navigate to staging.new.expensify.com and log in
2. On the home screen, open a any report
3. Create a task with a long description
4. Open task detail and then go the the chat view

## Expected Result:
Task details must be fully visible in chat and details view

## Actual Result:
Long task description is completely truncated in chat and overlapped by expand button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4f5b5ed2-e8c6-4264-9cc2-5b695bf1d841

<img width="1440" alt="Bug6137880_long_description" src="https://github.com/Expensify/App/assets/78819774/e10e064c-9cf2-4aaa-9377-60f2dc7fa2ee">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Inernal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-07-22 22:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Long task description is truncated in chat and overlapped by expand button

### What is the root cause of that problem?
We have not added the styles for `MenuItemWithTopDescription` to wrap the text in `TaskView` component.

### What changes do you think we should make in order to solve the problem?
We can create a new style (that involves giving word break and maxWidth)for wrapper - 
```
    taskDescriptionMenuItemWrapper: {
        maxWidth: '100%',
        ...wordBreak.breakWord,
    },
```

And add that for wrapper style in `MenuItemWithTopDescription` in `TaskView`
```
wrapperStyle={[styles.pv2,styles.taskDescriptionMenuItemWrapper]}
```

<details>
  <summary>Result</summary>
  
<img width="1151" alt="Screenshot 2023-07-23 at 3 52 11 AM" src="https://github.com/Expensify/App/assets/27822551/75f4a58f-e137-4cb7-aa5f-a14778acebdd">

</details>

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-07-24 13:52
@namhihi237 @stitesExpensify @mananjadhav  this seems like this is a regression from PR you have worked on, can you have a look?

**Comment by mananjadhav** [comment] 2023-07-24 13:55
Yes @mountiny. I'll comment on the issue.

**Comment by bondydaa** [comment] 2023-07-24 15:13
approved the PR in question

**Comment by bondydaa** [comment] 2023-07-24 15:13
@namhihi237 can you left a comment so I can assign you?

**Comment by marcaaron** [comment] 2023-07-24 19:07
Chatting with @bondydaa [here](https://expensify.slack.com/archives/C07J32337/p1690224383145509) we are going to drop the **Deploy Blocker** label from this one because the regression is extremely minor and the follow up fix can go out with the regularly scheduled deploys.

**Comment by mananjadhav** [comment] 2023-07-28 19:15
This is a regression issue and there won't be any payout as reporting is also Internal QA.

**Comment by mananjadhav** [comment] 2023-08-01 04:00
@mallenexpensify We can close this one out.

**Comment by mananjadhav** [comment] 2023-08-06 17:58
@mallenexpensify quick bump

**Comment by mananjadhav** [comment] 2023-08-08 16:56
@mallenexpensify friendly reminder

**Closed** 2023-08-11 00:55 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
