### ISSUE TITLE
[$250] Send money - User can send money to group by modifying the URL to ../send/new/..

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29367] opened 2023-10-11 19:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No. Send money is not available on prod

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:**  Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any group chat
3. Modify the link to staging.new.expensify.com/send/new/<groupchat_ID>
4. Proceed with sending money process

## Expected Result:
When navigating to staging.new.expensify.com/send/new/<groupchat_ID>, error should show up

## Actual Result:
When navigating to staging.new.expensify.com/send/new/<groupchat_ID>, user can proceed with sending money to the group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/40f4c6e7-f350-499b-9c13-e8d1e9836285

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018efda0f6a36aaf1e</li>
        <li>Upwork Job ID: 1712345985658458112</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-10-11 20:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Send money - User can send money to group by modifying the URL to ../send/new/..
### What is the root cause of that problem?
This problem exists for all kind of iou requests. We have not implemented any conditions to prevent such cases.
I found this comment describing a function which is used to show available `iou` actions in report `+` button. Based on this comment we can see which combinations are not allowed, like send request in non 1:1 chats, or split in 1:1 chats
https://github.com/Expensify/App/blob/8c73c2bc0728d2bb56c3036406949120d0167d0b/src/libs/ReportUtils.js#L3353-L3376
### What changes do you think we should make in order to solve the problem?
We can leverage this `getMoneyRequestOptions` function to check if iou request is valid or not and show `NotFoundPage` in corresponding places
https://github.com/Expensify/App/blob/main/src/pages/iou/MoneyRequestSelectorPage.js#L92
like this:

```javascript
                <FullPageNotFoundView shouldShow={!IOUUtils.isValidMoneyRequestType(iouType) || (!isFromGlobalCreate && !ReportUtils.getMoneyRequestOptions(props.report,props. report.participantAccountIDs).includes(iouType))}>
```
This will ensure that combination of current report and iou type is allowed one, and prevent from unwanted cases.
Note that, we only apply this check if route has report params, not creating new without selecting report yet.
### What alternative solutions did you explore? (Optional)
If this usage is confusing or overloads a function usage, we can create similar function which will check for above cases based on conditions similar to `getMoneyRequestOptions` conditions

**Comment by alitoshmatov** [comment] 2023-10-11 20:40
I don't think this is Deploy blocker since we can reproduce similar issue using `.../split/new/...`  in 1:1 chats.

**Comment by jasperhuangg** [comment] 2023-10-11 22:35
cc @techievivek since this seems related to your recent Send Money PR

**Comment by neil-marcellini** [comment] 2023-10-11 22:46
I'm removing the blocker label because this is a new feature we’re bringing back, we can’t easily revert it, and the fix won’t be super quick, so we should not block everything on it. Also the reproduction steps for this one are pretty weird.

**Comment by neil-marcellini** [comment] 2023-10-11 22:47
I'm assuming we don't want to allow sending money to a group because it's unclear who the money is being sent to. If that's correct we should fix it on the backend too. I'm re-assigning this to @techievivek because it's related to a project he is working on.

**Comment by techievivek** [comment] 2023-10-12 02:39
As mentioned by Ali this seems to happen for all iou requests so it makes sense not to hold this as a blocker, thanks for handling it.

>  If that's correct we should fix it on the backend too.

We expect to only see a singe user for send money requests so we are already handling this.

**Comment by techievivek** [comment] 2023-10-12 05:56
I think a minor fix is required here to prevent users from accessing send money or any other IOU flow, and we have the logic in the backend to help us deny such requests, so I have updated the bounty to only $100.

**Comment by techievivek** [comment] 2023-10-12 12:49
@hannojg  Update it to 250, but I think these are minor fixes with no edge case(hopefully) and shouldn't take long other than just verifying it across platforms.

can you please review the proposal posted by Ali, thanks.

**Comment by esh-g** [comment] 2023-10-12 13:01
@techievivek @muttmuure This issue is a dupe and will get fixed here: https://github.com/Expensify/App/issues/26523

**Comment by hannojg** [comment] 2023-10-12 14:01
@techievivek did you tag me by accident? I don't see why I was tagged

**Comment by techievivek** [comment] 2023-10-13 16:46
@hannojg 

> did you tag me by accident? I don't see why I was tagged

Sorry, I tagged you by accident 😄

**Comment by techievivek** [comment] 2023-10-13 16:47
> The issue https://github.com/Expensify/App/issues/26523 is requesting money, this issue is sending money. But because they share the same component. So looks like we can fix them together.

Yes, that will be great.

**Comment by techievivek** [comment] 2023-10-13 16:49
@alitoshmatov Do you mind posting your proposal to the other issue so we can tackle them all together.

**Comment by alitoshmatov** [comment] 2023-10-13 17:25
@techievivek Looks like proposal(https://github.com/Expensify/App/issues/26523#issuecomment-1703288168) provided in that issue is very similar to mine and solve the issue. So I think there is no need for my proposal

**Comment by techievivek** [comment] 2023-10-16 10:44
This is a duplicate of https://github.com/Expensify/App/issues/26523 so I will close this one.

**Closed by techievivek** 2023-10-16 10:44 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
