### ISSUE TITLE
[$1000] Web -  "Hmm... it's not here" page is displayed when creating task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21896] opened 2023-06-29 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1, Click on 'FAB' icon
2. Click on 'Assign task'
3. Enter title & click on 'Next' button
4. Click on 'Assignee'
5. Search for a user you don't have existing chat history with & select the user
6. Close RHN without clicking on 'Confirm task' button
7. Repeat step 1 - 4
8. Select the user you have selected on step 5
9. Click on 'Confirm task' button

## Expected Result:
Task should be created successfully

## Actual Result:
"Hmm... it's not here" page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2d89dcb9-3485-45d9-87e4-dfafcb900d44

https://github.com/Expensify/App/assets/93399543/60207f20-e0f8-446f-884c-006f49f38b75

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687964002479529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b7700439dabc7bc</li>
        <li>Upwork Job ID: 1674562524992471040</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-06-29 23:36
A weird one but one we should fix

**Comment by mentamarindos** [comment] 2023-06-29 23:51
how can I join slack? I've already sent an email requesting access

**Comment by mentamarindos** [comment] 2023-06-29 23:52
Contributor details
Your Expensify account email: windenclientes@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01728ee2a0cd0cd747

**Comment by jonrin0213** [comment] 2023-06-30 02:11
The problem is that Expensify assigns the task when the user selects an assignee, even if the user doesn't click the 'confirm task' button. The task should not be assigned when the user selects an assignee.

**Comment by jonrin0213** [comment] 2023-06-30 02:14
Contributor details
Your Expensify account email: jonathan.rincon0213@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012e242cba86659023

**Comment by crystal6117** [comment] 2023-06-30 02:54
Reproduced.

**Comment by Ahmed-Abdella** [comment] 2023-06-30 11:31
Contributor details
Your Expensify account email: abdellaa921@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~014640fcd762b61d2f

**Comment by alexxxwork** [comment] 2023-06-30 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report not found when creating a task second time with the same new assignee

### What is the root cause of that problem?

The root cause of the problem is that a new report is created on choosing an assignee and before user presses "create task" button.
here 
https://github.com/Expensify/App/blob/5009b8d5d8edd5e9bb6f4f6def88c5acaea8bc3c/src/pages/tasks/TaskAssigneeSelectorModal.js#L187
`selectReport` calls `TaskUtils.setAssigneeValue` and it calls `ReportUtils.buildOptimisticChatReport` if assignee hasn't open chat with task assigner.

This leads us to a problem when we cancel task creation after choosing an assignee - the report is created dummy accountID and would be created again on the second and further attempts

### What changes do you think we should make in order to solve the problem?


We could do this chat(report) creation logic right before the task creation here
https://github.com/Expensify/App/blob/5009b8d5d8edd5e9bb6f4f6def88c5acaea8bc3c/src/pages/tasks/NewTaskPage.js#L107

**Comment by abdulrahuman5196** [comment] 2023-07-02 08:44
From @dukenv0307 's proposal here https://github.com/Expensify/App/issues/21896#issuecomment-1614051733

The root cause is correct we are requesting to create a task that has invalid reportID which results in failure.

On solution: 

>(Related to 1) We need to update the dummy account ID key in personalDetailsList to null in successData when openReport

Yes. We should remove the optimistic personal data from onyx after getting proper data from openReport.

>(Related to 2) When back-end returns personalDetailsList in OpenReport, it should return the login as well so we can remove the condition in 3

I don't think we can do this, since the login is intentionally removed from unknown users data currently.

Tagging @jasperhuangg for the below questions since he was the original creator of the PR - https://github.com/Expensify/App/pull/21159

We are not allowing personalDetails without login(i.e unknown users) to come up during task assignee process. Then it also means it shouldn't come up during searching on the list as well right?
This means a task can never be created with a user whose email login information is unknown?

It is not just the above OP case, **creation of tasks with users without login information is broken currently AFAIK**. Like just create a new chat with unknown user. Relogin so that the onyx data won't have stale email login data for that user, create a task for that user and it will also fail the same way.

**Comment by adelekennedy** [comment] 2023-07-05 20:27
pending @jasperhuangg on the above

**Comment by jasperhuangg** [comment] 2023-07-07 18:58
Hmm this is actually a known issue and will be addressed internally. https://github.com/Expensify/Expensify/issues/294203. We have a few parts of Tasks that need to be cleaned up. I think we're good to close this out.

**Closed** 2023-07-10 20:28 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
