### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250]  Public room - Two RHPs appear briefly after clicking on any option in group details RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43806] opened 2024-06-16 01:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log out if logged in
3. Go to a public room
4. Click on the chat header
5. Click any option (Invite, Settings, Private notes)

## Expected Result:
Sign in modal will animate smoothly

## Actual Result:
Two RHPs appear briefly after clicking on any option in group details RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/80ea7d3e-3c08-4659-99f0-da76e05b8277

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9bd9f1e714cb88f</li>
        <li>Upwork Job ID: 1803182365680551956</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 102792321</li>
<li>bernhardoj | Contributor | 102792322</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment] 2024-06-16 01:02
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-16 01:02
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-06-16 12:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Two RHPs briefly appear when open the sign in modal from an RHP as anon user.

### What is the root cause of that problem?
This issue has happened before in https://github.com/Expensify/App/issues/28610. The root cause is the same. In login form, we auto focus to the field which interrupts the screen animation. We previously fixed it by adding a delay just like on other pages,
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/signin/LoginForm/BaseLoginForm.tsx#L170-L175

but the auto focus is still happened immediately. It happens after this [PR](https://github.com/Expensify/App/pull/43752) which adds the `autoFocus` prop to the text input. It's to fix this [issue](https://github.com/Expensify/App/issues/43664) where the focus trap initial focus cause the issue.

### What changes do you think we should make in order to solve the problem?

First, remove the `autoFocus` prop from the text input.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/signin/LoginForm/BaseLoginForm.tsx#L271

To fix https://github.com/Expensify/App/issues/43664, add the sign in modal screen (SCREENS.SIGN_IN_ROOT) to the SCREENS_WITH_AUTOFOCUS list.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/FocusTrap/SCREENS_WITH_AUTOFOCUS.ts#L4-L13

This perfectly fits our needs because we don't want the focus trap initial focus override the page auto focus.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L50-L55

**Comment by DylanDylann** [comment] 2024-06-19 08:06
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/43806#issuecomment-2171576319) looks good to me

The autoFocus prop and the initial focus from focus trap implementation are unnecessary on this page. Let'e remove it 

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-06-19 11:03
PR is ready

cc: @DylanDylann

**Comment by bernhardoj** [comment] 2024-07-10 12:39
I'll request in ND once payment is due.

**Comment by johncschuster** [comment] 2024-07-10 13:46
# Payment Summary:
Contributor: @bernhardoj - $250 - via Manual Request
Contributor+: @DylanDylann - $250 - via [Upwork](https://www.upwork.com/nx/wm/offer/102792321)

**Comment by bernhardoj** [comment] 2024-07-16 02:04
The payment should be due [tomorrow](https://github.com/Expensify/App/issues/43806#issuecomment-2220197330) (07-17)

**Comment by johncschuster** [comment] 2024-07-16 13:30
# Payment Summary:

Contributor: @bernhardoj owed $250 via NewDot
Contributor+: @DylanDylann paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/102792321)

**Comment by bernhardoj** [comment] 2024-07-17 03:01
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-19 02:24
$250 approved for @bernhardoj

**Comment by DylanDylann** [comment] 2024-07-19 02:50
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43752
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43752#discussion_r1683709183
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **No**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Do we agree 👍 or 👎

**Closed** 2024-07-19 14:44 UTC
Labels: External, Daily, Awaiting Payment, Bug
