### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] IOS - Showing two different avatars for the same Phone Number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20930] opened 2023-06-16 19:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to settings
3. Create work space
4. Invite members with phone number.
5. Write the phone number from the auto suggested list

## Expected Result:
When writing a phone number that is Same with the suggested phone number below, it should have only listed one phone number with an Avatar

## Actual Result:
Shows two Avatars with the same phone number. And also sends invitation for both, with the same phone numbers but different avatars

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.7

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9566c2c4-ffdd-4640-b080-3c69fddb7364

**Expensify/Expensify Issue URL:**

**Issue reported by:**@daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686275913577249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164f70b47c75e0691</li>
        <li>Upwork Job ID: 1670937084692242432</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-06-19 23:32
Was able to reproduce on iOS, not sure if it's repro on other platforms.  I think it can be External 
<img width="498" alt="image" src="https://github.com/Expensify/App/assets/22508304/2060a9bf-2632-4e28-a8f1-3be4281562a5">

**Comment by yakubbaev** [comment] 2023-06-20 13:37
### Problem:
GIVEN user has a personalDetails (contact?) registered with a phone number 
WHEN the user searches for that phone number
THEN two options with the same phone number appears on the screen

Note: it works ok when this contact is selected.

### Root cause:
There's a userToInvite state, which is an option for optimistically generated account.
It was getting appended to the end of the list always (except when it was selected - see note above).

### Solution:
Enhance hasUnselectedUserToInvite with shouldIncludeUserToInvite that checks whether userToInvite is already included in the list.

**Comment by mollfpr** [comment] 2023-06-20 14:08
@yakubbaev Could you update your proposal following the [template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md)? Thanks!

**Comment by yakubbaev** [comment] 2023-06-20 14:24
@mollfpr I used that template when writing my initial proposal. Could you please elaborate on what should I update?

**Comment by yakubbaev** [comment] 2023-06-20 14:33
@mollfpr updated by copying and editing the template. Let me know if that works. Thanks!

**Comment by yakubbaev** [comment] 2023-06-20 14:43
@mollfpr updated with the alternative solutions explored

**Comment by yakubbaev** [comment] 2023-06-21 10:10
## Proposal
[Updated](https://github.com/Expensify/App/issues/20930#issuecomment-1598809664)

**Comment by pasyukevich** [comment] 2023-06-21 15:13
Hi! I'm from Callstack and investigate this issue. 

Looks like this issue is related to the BE side. 

The current proposal is not solving the issue as it is not related to the userToInvite state.  Reproduced and checked on web and ios.

**Comment by mallenexpensify** [comment] 2023-06-22 00:10
@mollfpr can you review @yakubbaev 's proposal please?
https://github.com/Expensify/App/issues/20930#issuecomment-1600564267

**Comment by mollfpr** [comment] 2023-06-22 01:03
I think this issue can be done in FE.

The root cause from @yakubbaev might be correct, but I'm unsure of the solution.

@yakubbaev Could you attach a video result from your solution?

**Comment by yakubbaev** [comment] 2023-06-22 03:20
Sure, @mollfpr 

https://github.com/Expensify/App/assets/430769/d6534fe8-1de5-4c79-b289-9759e94c914e

**Comment by yakubbaev** [comment] 2023-06-26 08:05
What is the status on this? @mollfpr @mallenexpensify

**Comment by mollfpr** [comment] 2023-06-26 08:08
Sorry for the delay. I'll give you an update soon.

**Comment by yakubbaev** [comment] 2023-06-26 14:41
Posted the [proposal in Upwork](https://www.upwork.com/ab/proposals/1673339390017404929).

Waiting for it to be accepted to submit the code with my implementation. 

Please correct me if I'm wrong. Thanks!

**Comment by mollfpr** [comment] 2023-06-26 14:47
@yakubbaev internal engineer will review it first and then assign the issue to you. It's better to start working on the PR after getting assigned to get the deadline bonus. The Upwork contract will be created between working on the PR and the payout time (7 days after the PR hit production).

**Comment by mallenexpensify** [comment] 2023-06-26 22:21
@Gonals , can you please review the above proposal? 
@yakubbaev , if/once you're assigned, I'll hire you ASAP in Upwork to make things _official_.  With us managing so many contributors, sometimes it takes a while to hire in Upwork.  GH is our source of truth (but we try to abide by Upwork's rules too)

**Comment by yakubbaev** [comment] 2023-06-29 03:44
@Gonals @mallenexpensify any news on this?

**Comment by yakubbaev** [comment] 2023-06-30 01:49
My [proposal](https://github.com/Expensify/App/issues/20930#issuecomment-1598809664) is still pending review.

**Comment by mallenexpensify** [comment] 2023-06-30 16:27
@Gonals 👀 please.  Pinging in NewDot too :)

**Comment by yakubbaev** [comment] 2023-07-03 01:19
I'm going on vacation today afternoon and will be back in 5 days. 

To get the bonus, should I raise PR now, before assigning? I'd rather not to take laptop with me :)

**Comment by Gonals** [comment] 2023-07-03 07:36
Proposal looks good to me! Assigning!

**Comment by yakubbaev** [comment] 2023-07-03 17:55
I should be able to raise PR by tomorrow

**Comment by MonilBhavsar** [comment] 2023-07-04 06:05
@Gonals @mollfpr Just a heads up that PR is ready for review

**Comment by yakubbaev** [comment] 2023-07-07 11:20
@MonilBhavsar @mollfpr  @Gonals PR is ready for re-review

**Comment by yakubbaev** [comment] 2023-07-10 08:47
@MonilBhavsar @mollfpr @Gonals PR is ready for re-review

**Comment by yakubbaev** [comment] 2023-07-11 12:02
@MonilBhavsar @mollfpr @Gonals PR is ready for re-review

**Comment by yakubbaev** [comment] 2023-07-12 09:52
PR is ready for re-review. @mollfpr thanks for revealing the root cause! Not sure whether I deserve to be paid now :)

**Comment by yakubbaev** [comment] 2023-07-24 01:01
Is there anything I should do to proceed with payment on this? @mollfpr @Gonals

**Comment by mollfpr** [comment] 2023-07-24 06:02
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

The closest PR I could find is https://github.com/Expensify/App/pull/8375 but this is a 15-month PR, so something else could make the issue that hard to track.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I believe that this issue is not something that will came up often, so the regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Precondition:
Account (user A) has been chatting with a phone number user (user B)

1. Open the app
2. Go to settings
3. Create or open a workspace
4. Click on the Invite members button
5. Click on the search Input to bring it into focus
6. Enter the phone number of the user B
7. Verify that only one option with that phone number is displayed
8. 👍 or 👎

**Comment by mollfpr** [comment] 2023-07-24 06:03
@yakubbaev Nothing. You just need to wait for @mallenexpensify to end the Upwork contract.

**Comment by yakubbaev** [comment] 2023-07-26 04:50
@mallenexpensify any updates?

**Comment by mallenexpensify** [comment] 2023-07-30 15:27
Apologies it took a bit @yakubbaev .  

Issue reporter: @daveSeife $250
Contributor: @yakubbaev paid $1000 via Upwork
Contributor+: @mollfpr paid $1000 via Upwork

@daveSeife can you please accept the job and reply here once you have?

**Comment by daveSeife** [comment] 2023-07-30 16:39
@mallenexpensify Accepted the offer. Thank you

**Comment by mallenexpensify** [comment] 2023-08-01 23:11
@daveSeife paid.  comment above updated to reflect. 
TestRail update GH created, thanks @mollfpr 
- https://github.com/Expensify/Expensify/issues/304784

**Closed by mallenexpensify** 2023-08-01 23:11 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
