### ISSUE TITLE
[Hold #45548] [Landing page] Update UseDot to direct "individual" and "1-9" traffic to NewDot rather than Expensify Classic

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#45361] opened 2024-07-12 23:28 UTC
As part of the August earnings, we're going to start directing traffic to expensify.com to land on New Expensify ([GH](https://github.com/Expensify/Expensify/issues/389378)). 

The above covers most of the sign-ups and thus is CRITICAL for moving sign-ups to NewDot. But another signup source is UseDot. Thus, we need to update UseDot so that we direct traffic to newDot as well. Currently, if you sign up on useDot, we will redirect you if you sign up with a public email. This will update it so we do private domains as well. 

In addition, we will be [updating UseDot to have qualifying questions added](https://github.com/Expensify/App/issues/45360) like the home page. Thus, we will want to mirror the logic from that project when the time come. But if we end up doing this first, we would send all users to NewDot. 

For background, please [go here](https://expensify.slack.com/archives/C036QM0SLJK/p1720801933579369?thread_ts=1720723258.872159&cid=C036QM0SLJK). I do not think this is going to be CRITICAL to move new signups to NewDot but @trjExpensify wanted to create an issue so we can add this as polish once the homepage is launched.

**Comment by kabeer95** [comment] 2024-07-13 00:24
# Proposal: Update Landing Page to Redirect Traffic to NewDot

## Problem Statement
Currently, the landing page directs traffic to Expensify Classic. We need to update it to redirect all traffic to NewDot instead.

## Root Cause
The current landing page configuration is set to point to Expensify Classic. This does not align with our goal to transition users to NewDot.

## Changes to Solve the Problem

### Update Redirection Logic
Change the landing page redirection logic to point to NewDot instead of Expensify Classic.

### Verify URL Configuration
Ensure that all relevant URL configurations and endpoints are updated to reflect the new redirection target.

## Code Changes

### JavaScript
```javascript
// Redirection logic in landing page script
const redirectToNewDot = () => {
    window.location.href = "https://new.expensify.com";
};

// Call the redirection function when the page loads
window.onload = redirectToNewDot;

```

## Alternative Solutions Explored
Gradual Rollout
Implement a feature toggle to gradually redirect users from Expensify Classic to NewDot. This allows for a controlled transition and monitoring of any issues that may arise.

User Prompt
Instead of automatic redirection, prompt users on the landing page with an option to navigate to NewDot. This provides users with a choice and eases the transition.

**Comment by neil-marcellini** [comment] 2024-07-23 21:22
Jumping in on this because I was told it was CRITICAL [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1721767441509929?thread_ts=1721754652.775229&cid=C06ML6X0W9L)

**Comment by trjExpensify** [comment] 2024-07-23 21:41
Niceee, thanks! If you could get this prepped and ready to rock, that would be awesome, Neil. We might time the merge with going live with the new home page on expensify.com and routing new sign-ups from there as well, but we can chat about that in channel.

**Comment by trjExpensify** [comment] 2024-07-23 22:24
Put the hold on for https://github.com/Expensify/App/issues/45360, as per [here](https://expensify.slack.com/archives/C036QM0SLJK/p1721772636779369?thread_ts=1721770821.587279&cid=C036QM0SLJK).

**Comment by trjExpensify** [comment] 2024-08-13 23:03
Just updated the title to reflect the current plan now that we're adding qualifiers to Usedot.

**Comment by neil-marcellini** [comment] 2024-08-15 01:15
Head's up, I'll be working 50% for the rest of this week and next 🌲

**Comment by trjExpensify** [comment] 2024-08-23 11:53
Ah interesting, why? Aren't we still going to hold the "individual" and "1-9" redirect on UseDot until the HybridApp rollout like we are the new home page on expensify.com?

**Comment by neil-marcellini** [comment] 2024-08-23 18:32
Oh, I wasn't aware that we wanted to hold the UseDot qualifier question redirect until the HybridApp rollout. I assume the project team is aware of and agrees with that? If so then I think it would make sense to put this under a beta, deploy it, and then add everyone to the beta when we want to launch it. Or some similar approach.

**Comment by trjExpensify** [comment] 2024-08-23 18:37
>I assume the project team is aware of and agrees with that?

Yeah, we've been operating on that for weeks and why this particular issue has a hold for a HybridApp rollout to new users in the title and it's nested in the list of issues held in the updates: https://expensify.slack.com/archives/C036QM0SLJK/p1723483522773169?thread_ts=1723483502.541039&cid=C036QM0SLJK

> If so then I think it would make sense to put this under a beta, deploy it, and then add everyone to the beta when we want to launch it. Or some similar approach.

Why don't we just deploy the code to redirect everyone that selects the individual or 1-9 options in a second PR like we are the new home page?

**Comment by trjExpensify** [comment] 2024-09-09 13:16
@neil-marcellini shall we close this? It's in place, and we have the issue to remove the beta to release it to the masses. So we're tracking that issue as being held on flicking the switch for new sign-ups.

**Closed** 2024-09-30 15:51 UTC
Labels: Reviewing, Weekly, Internal
