### ISSUE TITLE
[$1000] Chat - Error message displayed when using 2 rows with four backticks

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14030] opened 2023-01-05 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13941

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Select any conversation
4. Type 2 rows with 4 brackets

## Expected Result:
No error message should be seen; message should match Slack's behavior (a single backtick on two lines, within a `<pre>` block)

<img width="594" alt="image" src="https://user-images.githubusercontent.com/5487802/211092031-9298db08-9bfe-4877-a434-54d191e4c05c.png">

## Actual Result:
Error message displayed when using 2 rows with four brackets

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210864970-daa7ed3e-e0f1-46d4-8fb7-fa485820f8c5.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c69ea8eddb49796</li>
        <li>Upwork Job ID: 1611395276911079424</li>
        <li>Last Price Increase: 2023-01-06</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-01-05 22:17
cc @tgolen since it seems related to https://github.com/Expensify/App/pull/13941

**Comment by tgolen** [comment] 2023-01-06 00:41
Well, will wonders never cease? That's a backend error, right? Let's be sure to fix it there. I wonder what the error could be...

**Comment by isabelastisser** [comment] 2023-01-06 16:10
I'm able to reproduce this:

https://user-images.githubusercontent.com/31258516/211051540-26ffb2dc-6efd-46de-a118-82df762c0271.mp4

**Comment by Prince-Mendiratta** [comment] 2023-01-06 17:32
# Proposal
## Rootcause
The reason behind this issue is the text being parsed as `<pre><code></pre></code>`. This behaviour is also seen by inputting four backticks, any number of spaces, newline, followed by four backticks.

## Background
The cause of such a unique combination of HTML is because of the following regex rules -

This rule is applied first, converting the text to `<pre>&#x60;</pre>&#x60;`
https://github.com/Expensify/expensify-common/blob/55c208315e04246b548a4009d35466c100d9de7c/lib/ExpensiMark.js#L20-L36

Now, this rule is applied to  `<pre>&#x60;</pre>&#x60;`, converting the text to `<pre><code></pre></code>` -
https://github.com/Expensify/expensify-common/blob/55c208315e04246b548a4009d35466c100d9de7c/lib/ExpensiMark.js#L42-L49

# Solution
Depending on the output we want to show the users when such a case is presented, we can modify the regexes to show that result.

**Comment by dangrous** [comment] 2023-01-06 18:01
Both of y'all are right on the cause! Not sure what we want to have as expected behavior here, though. I'll bring it up in Slack and see what we think.

**Comment by Prince-Mendiratta** [comment] 2023-01-06 19:45
# Updated Proposal 
based on [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1673028150695209)

## Expected Behaviour
After discussion and analysis of backticks behaviour on Slack, we concluded that for codeFence, we can interpret the functionality so that anything that is enclosed between three starting backticks and three ending backticks, can be interpreted as enclosed within `<pre>` block.

## Fix
As suggested by @dangrous in the [comment](https://expensify.slack.com/archives/C01GTK53T8Q/p1673031455366149?thread_ts=1673028150.695209&cid=C01GTK53T8Q), we can use the regex to obtain the following results for the current issue -

## Code
```diff
diff --git a/lib/ExpensiMark.js b/lib/ExpensiMark.js
index f63b22a..7ad35f6 100644
--- a/lib/ExpensiMark.js
+++ b/lib/ExpensiMark.js
@@ -21,7 +21,7 @@ export default class ExpensiMark {
                 name: 'codeFence',
 
                 // &#60; is a backtick symbol we are matching on three of them before then after a new line character
-                regex: /(&#x60;&#x60;&#x60;[\n]?)((?:\s*?(?![\n]?&#x60;&#x60;&#x60;)[\S])+\s*?)([\n]?&#x60;&#x60;&#x60;)/g,
+                regex: /(&#x60;&#x60;&#x60;[\n]?)((?:\s*?(?![\n]?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?)([\n]?&#x60;&#x60;&#x60;)/g,
 
                 // We're using a function here to perform an additional replace on the content
                 // inside the backticks because Android is not able to use <pre> tags and does

```

### Output
**Web**
![image](https://user-images.githubusercontent.com/54077356/211086693-f85b4cb4-e66e-49df-bb0c-6aecf53ecd6b.png)

**Android**
![image](https://user-images.githubusercontent.com/54077356/211086862-18fde7b4-2dd5-41ba-9b06-01709a9ce4dc.png)


### Text Conversion / Flow
![image](https://user-images.githubusercontent.com/54077356/211086741-851342c9-07ce-4f31-9a04-ad1a92229503.png)

## Impact
I believe this should not affect the use of quoteBlocks since the ideology that anything between opening and closing three backticks should be considered as the content to be enclosed in the code blocks sounds good to me.

**Comment by dangrous** [comment] 2023-01-06 20:21
@aimane-chnaif let us know what you think of that regex change! I can't really review since it was my code haha. I think the main issue will be whether or not it adds any bugs for other uses of backticks in messages.

We can sort out the payment/bonus/PR author stuff discussed in Slack once we confirm that this is the direction we want to go in.

**Comment by dangrous** [comment] 2023-01-09 17:48
Okay thank you for testing! Yeah I think those all look weird but marginally make more sense in the new version.

As discussed in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1673040717390229?thread_ts=1673028150.695209&cid=C01GTK53T8Q), I think we'll move forward with this change that fixes this specific issue, and let any other weird edge case behavior be dealt with when/if it comes up.

**Comment by aldo-expensify** [comment] 2023-01-09 19:42
I just wanted to make sure that [this is](https://github.com/Expensify/expensify-common/pull/487#event-8184788989) how we want to solve it because there are other ways of interpreting more than 3 backticks together.

From my understanding, the "fenced" code block using 3 (or more backticks) is not part of markdown, but and extension that some markdown flavors add. I.e. Github flavor: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks, or you can play with this page: https://markdownlivepreview.com/

From that, I understand that you can really start the code fence with 4 backticks and then you can close it with 4 backticks. This is useful in case you wanted to put 3 backticks inside the code block without closing it. This can be done with 5, 6, etc backticks (the number of backticks at the start should match the ones at the end).

I wouldn't use `Slack` as a guide because the `Slack` composer immediately creates a code block as soon as you type 3 backticks, it is a WYSIWYG editor.  Our composer doesn't work like this... our markdown isn't interpreted immediately, our composer works similar to the GH composer where you see the result after saving.

Here is another example where the fence can be done with 3 or **more backticks**: https://python-markdown.github.io/extensions/fenced_code_blocks/#:~:text=Fenced%20Code%20Blocks%20are%20defined,on%20a%20line%20by%20themselves.

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/87341702/211394086-5f59023e-b8fa-4819-b226-a181356d6d47.png">

**Comment by dangrous** [comment] 2023-01-09 20:04
ah interesting @aldo-expensify - so a couple thoughts:
* The Slack example was done when turning off their WSIWYG editor, so that at least is still a reasonable example
* I think what you're saying totally makes sense - but, it does seem particular to that certain (GH and I guess Python) flavor of markdown, e.g not Slack, not [Markdown Guide](https://www.markdownguide.org/basic-syntax/#escaping-backticks), [Discord](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-) etc. That's not to say it's wrong, just that we can sort of do whatever we want. It seems like it's a bit more of a "power-user" feature than what would be needed in most cases.
* The particular issue here was being caused by the parser not grabbing the right set of backticks and so not actually correctly containing _anything_ within the code block - it was previously `<pre><code></pre></code>`. Again, this isn't saying your comment is wrong, just that it is functionality that didn't already exist in the product.
All in all, I think I'm leaning towards just fixing this in this method and maybe if we choose to go the (honestly probably better, though rarely used) route of allowing multiple numbers of backticks in the future, it shouldn't be too hard. But would love to hear your thoughts!

**Comment by aldo-expensify** [comment] 2023-01-10 15:57
> The Slack example was done when turning off their WSIWYG editor, so that at least is still a reasonable example

I always forget you can turn it off :P

> it does seem particular to that certain (GH and I guess Python) flavor of markdown, e.g not Slack, not [Markdown Guide](https://www.markdownguide.org/basic-syntax/#escaping-backticks), [Discord](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-) etc. That's not to say it's wrong, just that we can sort of do whatever we want.

Yeah, it looks like there isn't like a standard for this

> It seems like it's a bit more of a "power-user" feature than what would be needed in most cases.

Agreed, wanting to put three backticks inside a code block is not a common case

> All in all, I think I'm leaning towards just fixing this in this method and maybe if we choose to go the (honestly probably better, though rarely used) route of allowing multiple numbers of backticks in the future, it shouldn't be too hard. But would love to hear your thoughts!

Ok!, I'm fine with fixing the current problem at hand, specially since:
- 3 backticks (or more) isn't really part of the markdown standard and we would have to decide which way we want to go
- supporting 3 backticks **or more** as the limits of the code fence may not be so easy and I think it has little value

**Comment by aldo-expensify** [comment] 2023-01-10 16:13
@dangrous I'm wondering if we should try to fix other cases like:

Three backticks 
<img width="116" alt="image" src="https://user-images.githubusercontent.com/87341702/211603182-7b01dce7-06da-4549-a036-bbfd800b5855.png">

turn into two separate code (not code blocks) with one backtick each instead of a single empty codeblock:

<img width="105" alt="image" src="https://user-images.githubusercontent.com/87341702/211603321-6a2fcb18-2e22-4c5c-bd7b-2e56e99220e5.png">

I know the example is not part of this GH issue description, but maybe we should try to fix it too

**Comment by dangrous** [comment] 2023-01-10 16:26
@aldo-expensify So that's an interesting case, I think. Because we shouldn't let the user send an empty code block, right, since it's an empty message? (Confirmed that Slack won't let you send that either). But we could go either way:
* Interpret it as it was probably meant, and give an error/disallow sending.
* Be "generous" and let the user send it the only way it could actually be a valid message - that is, two code blocks with a single backtick inside them.

I'm not sure which I prefer!

**Comment by aldo-expensify** [comment] 2023-01-10 16:30
```
```

**Comment by aldo-expensify** [comment] 2023-01-10 16:32
> Because we shouldn't let the user send an empty code block, right, since it's an empty message? (Confirmed that Slack won't let you send that either). But we could go etither way:

Interesting point... I honestly don't know which way is better. My feeling about this is that it is of little importance (just like this GH issue itself)... so I don't lean hard to any and maybe I would :donothing if it is too much work

**Comment by dangrous** [comment] 2023-01-10 16:37
yeah I figured out how I could fix the regex to match that.

BUT

I also found this: https://github.com/Expensify/expensify-common/pull/443 and https://github.com/Expensify/expensify-common/blob/55c208315e04246b548a4009d35466c100d9de7c/__tests__/ExpensiMark-HTML-test.js#L519-L523

Looks like we explicitly chose not to allow that. So I think we move forward with the code in the PR

**Comment by aldo-expensify** [comment] 2023-01-10 17:52
Cool, thanks for finding that.

> Looks like we explicitly chose not to allow that. So I think we move forward with the code in the PR

👍

**Comment by isabelastisser** [comment] 2023-01-13 15:51
Hey @aldo-expensify can I go ahead and hire @aimane-chnaif and the contributor who fixed the issue and @dangrous and the C+ for this[ Upwork job](https://www.upwork.com/jobs/~014c69ea8eddb49796)?

**Comment by Prince-Mendiratta** [comment] 2023-01-13 16:38
Hello @aimane-chnaif , @dangrous glad to see this issue resolved! I was wondering if I am eligible for a bonus for this as well? I helped out in the RCA, testing and fix. I was working on the regex solution myself and was testing it out but @dangrous sent his regex in the Slack thread so I went on to test that out instead. I would appreciate if it's possible but thanks anyways :D

**Comment by dangrous** [comment] 2023-01-13 16:52
Hey @Prince-Mendiratta (and @aimane-chnaif) I think that makes sense to me - you were helpful in getting this sorted out. We can definitely send over a bit of a bonus! cc @isabelastisser

**Comment by isabelastisser** [comment] 2023-01-20 20:18
Update: Invited @aimane-chnaif and @Prince-Mendiratta to[ this job](https://www.upwork.com/jobs/~014c69ea8eddb49796) in Upwork.

**Comment by isabelastisser** [comment] 2023-01-23 16:53
Update: @aimane-chnaif and @Prince-Mendiratta were paid. All set!

**Comment by dangrous** [comment] 2023-01-24 17:39
Do we still do the 7-day window for these if it's an internal PR? If not, I think we can go ahead and close, right? I don't remember what our process is for that.

**Comment by dangrous** [comment] 2023-01-26 19:49
I'm going to go ahead and close this since I believe everyone is paid and we've passed 7 days - should anyone disagree (or I do not have the right information), feel free to reopen!

**Closed by dangrous** 2023-01-26 19:49 UTC
Labels: Reviewing, Daily, Internal, Bug
