### ISSUE TITLE
[HOLD for Payment 2024-09-06][$250] mWeb - Video - In welcome video, all playback speed options is not shown in normal mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47205] opened 2024-08-11 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login as a Gmail account
3. In the Welcome Expensify video, tap 3 dots
4. Select playback speed
5. Note the number of playback speed options
6. Go to full screen mode
7. Tap 3 dots - playback speed
8. Note the number of playback speed options

## Expected Result:
In the welcome video, all playback speed options shown is full screen mode must be shown in normal mode.

## Actual Result:
In the welcome video, all playback speed options shown is full screen mode is not shown in normal mode.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7b786d01-cf13-4576-b4f9-d480de7d4569

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d75aeb575f9f1ea</li>
        <li>Upwork Job ID: 1823445367470479721</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103548572</li>
<li>neonbhai | Contributor | 103548574</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by IuliiaHerets** [comment] 2024-08-11 19:48
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-11 19:48
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment] 2024-08-13 19:47
Adding BZ again - I'll be out until 8/21

**Comment by greg-schroeder** [comment] 2024-08-14 11:21
Awaiting proposal review by @ikevin127

**Comment by ikevin127** [comment] 2024-08-14 22:28
♻️ Reviewing proposals today.

**Comment by ikevin127** [comment] 2024-08-15 00:36
@daledah Thank you for the proposal. While I appreciate the more detailed proposal, unfortunately it came **after** the first one which I think was detailed enough since this issue has a simple root cause / solution.

ℹ️ Keep in mind the [contributor guidelines (6.)](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) which state:

> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

Otherwise you could get a ⚠️ warning, which after 2 (same month) or 3 (per year) you risk being removed from the contributor program.

**Comment by ikevin127** [comment] 2024-08-15 00:36
@neonbhai's [proposal](https://github.com/Expensify/App/issues/47205#issuecomment-2282923395) looks good to me even though it's not extremely detailed, since this issue has a simple root cause / solution. The root cause was pointed out correctly and the proposed solution fixes the issue, even though it does not mention all the details, it mentions enough to be acceptable.

**Notes for PR** (if assigned):
1. Make sure to adjust the types as well based on the new added values.
2. Make sure to adjust the initial state variable `currentPlaybackSpeed` to match the `Normal` speed, given the new values.
3. To fully fulfil the **Expected result**, please have the value `1` show the label `Normal` in order to match the native player.
    **Note:** The label `Normal` should be translated (en/es) and placed in translations at `videoPlayer.playbackSpeedNormal` (or similar).

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-08-15 03:49
@daledah Don't worry - you will not get a warning in this case, I was just mentioning to be mindful of that contributor guideline in the future as it **might** lead to warnings.

Of course it's subjective, there are cases in which a more detailed RCA and solution are required - I don't consider this one to be that case.

**Comment by ikevin127** [comment] 2024-08-20 18:34
> Please accept the offer and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻

Currently awaiting for @neonbhai to give a timeline on the PR.

**Comment by ikevin127** [comment] 2024-08-30 22:13
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @slafortune

**Comment by ikevin127** [comment] 2024-09-03 20:24
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-06]** according to 4 days' ago production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @slafortune @techievivek

**Comment by slafortune** [comment] 2024-09-04 16:46
@ikevin127 Thanks! - Can you  please complete the checklist - 
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@ikevin127   ] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@ikevin127   ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@ikevin127   ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@ikevin127   ] Determine if we should create a regression test for this bug.
- [ ]  [@ikevin127   ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ]  [@slafortune ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by ikevin127** [comment] 2024-09-05 00:26
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30829
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30829/files#r1744646106
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Open Expensify app and login.
2. Open a chat and send a video attachment.
3. Click on Expand (to make video fullscreen).
4. Click on three dots -> Playback speed.
5. Verify that the 1x speed is labeled `Normal`.
6. Verify that all playback speed options (0.25, 0.5, 0.75, Normal, 1.25, 1.5, 1.75, 2) can be observed.

Do we agree 👍 or 👎.

**Comment by slafortune** [comment] 2024-09-06 11:22
Regression Test - https://github.com/Expensify/Expensify/issues/426444
@ikevin127 @neonbhai Paid ✅ ✅

**Closed by slafortune** 2024-09-06 11:22 UTC
Labels: Reviewing, External, Weekly, Bug
