### ISSUE TITLE
[$500] Distance - 0 miles distance can be created with "Your location" history and current location

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35245] opened 2024-01-26 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create a distance request using "Use current location" for Start and a different address for Stop.
3. Navigate to request details page.
4. Click Distance.
5. Change Stop address to "Use current location".
6. Save the edit.

## Expected Result:
Error will show up because duplicate addresses are used.

## Actual Result:
The new distance with duplicate waypoints is saved. The new amount remains the same as the previous distance and the new distance is 0 miles.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5161b723-d544-4e3d-81b9-d7c56331ed96

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb896320dd7073a5</li>
        <li>Upwork Job ID: 1750881635152072704</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-26 14:02
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by FitseTLT** [comment] 2024-01-26 14:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 0 miles distance can be created with "Your location" history and current location

### What is the root cause of that problem?
We are not validating if the waypoints are similar and display error message as we did for creating the distance request
### What changes do you think we should make in order to solve the problem?

We should validate if the waypoints are different before updating waypoints same as we did here
https://github.com/Expesnsify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/pages/iou/request/step/IOURequestStepDistance.js#L137-L143
### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-01-27 03:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - 0 miles distance can be created with "Your location" history and current location

### What is the root cause of that problem?

Recently, while handling this [issue](https://github.com/Expensify/App/issues/34233), we introduced reverse geocoding in BE for `your location` coordinates. However, there are cases when the reverse geocoding does not result in arriving at an address. In such cases, plain coordinates are used as `address` with the format `Lat: xxx Lng: yyy`, and the `name` will be set to an empty string. It does not make sense to show location coordinates in the recent list as the user is most likely not going to expect plain coordinates. So, it seems that the root cause is that we are not ignoring unresolved `your location` in the recent list.  

### What changes do you think we should make in order to solve the problem?

We can skip such plain coordinates by filtering such recent ones. 
This can be done by replacing the selector [here](https://github.com/Expensify/App/blob/9dbc389ea01748f61f39f4412cbbc804cf306a58/src/pages/iou/request/step/IOURequestStepWaypoint.js#L285C1-L295C21) like this

```
            selector: (waypoints) => {
                const validWaypoints = _.filter(waypoints, (waypoint) => !waypoint.name && !waypoint.address.startsWith(`Lat:`));
                return _.map(validWaypoints ? validWaypoints.slice(0, 5) : [], (waypoint) => ({
                    name: waypoint.name,
                    description: waypoint.address,
                    geometry: {
                        location: {
                            lat: waypoint.lat,
                            lng: waypoint.lng,
                        },
                    },
                }));
            }
```

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-01-27 18:00
@Tanvi654 Thanks for the proposal. Your RCA is not correct.

**Comment by s77rt** [comment] 2024-01-27 18:04
@abzokhattab Thanks for the proposal. Your RCA is correct. The suggested solution makes sense but I think we should calculate the distance between the two addresses and if it's below a set threshold we consider them the same. This is more reliable than having to deal with lat/lng precision.

(Will raise a slack thread soon)

**Comment by s77rt** [comment] 2024-01-27 18:06
@Krishna2323 Thanks for the proposal. Your RCA is correct. The suggested solution is more like a feature request but it will fix this issue as well.

(Will raise a slack thread soon)

**Comment by s77rt** [comment] 2024-01-27 18:11
@rojiphil Thanks for the proposal. Your RCA is not correct. This has nothing to do with the recent list. You can choose "Use current location" regardless of the recent waypoints.

**Comment by s77rt** [comment] 2024-01-27 19:21
Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1706383208599399

**Comment by rojiphil** [comment] 2024-01-29 04:26
> This has nothing to do with the recent list. You can choose "Use current location" regardless of the recent waypoints.

@s77rt I am not sure if I understood you on this. 
Can you please share the steps without using `Lat *** Lng ***` in recent list and by using the `Your location`? 
Looks like I am missing something simple here.

**Comment by rojiphil** [comment] 2024-01-29 04:42
## Proposal

@s77rt 
[Updated](https://github.com/Expensify/App/issues/35245#issuecomment-1912952384) with an alternate solution if this issue is looked at from the perspective of `0` resultant distance

**Comment by iwint** [comment] 2024-01-29 05:43
Contributor details
Your Expensify account email: iwinissacofficial@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c640d5c10341bb7e

**Comment by conorpendergrast** [comment] 2024-01-29 17:05
Checking which wave to include this in, through [this internal channel](https://expensify.slack.com/archives/C05DWUDHVK7/p1706547895967229)

**Comment by s77rt** [comment] 2024-01-29 18:07
@rojiphil Edit a waypoint, clear the input then you will get the option to use your location.

**Comment by s77rt** [comment] 2024-02-01 22:21
Not overdue. Just bumped the slack thread

**Comment by s77rt** [comment] 2024-02-05 14:46
🎀 👀 🎀 Can you please check https://expensify.slack.com/archives/C01GTK53T8Q/p1706383208599399

**Comment by dangrous** [comment] 2024-02-05 16:32
🫡 adding to the thread!

**Comment by dangrous** [comment] 2024-02-06 21:04
See https://expensify.slack.com/archives/C01GTK53T8Q/p1707252640390959?thread_ts=1706383208.599399&cid=C01GTK53T8Q - we're going to close this out for now, as it seems minor and not worth the #focus

**Closed by dangrous** 2024-02-06 21:04 UTC
Labels: External, Daily, Help Wanted, Bug
