### ISSUE TITLE
[HOLD FOR #26538][$500] Web - Date/Merchant is disabled for split, but still accessible with deeplink

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27565] opened 2023-09-15 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click plus button => Split, enter amount, press Next.
2. Choose few members, press Next.
3. At Confirmation Page, change the link from `/split/new/confirmation/` to `/split/new/date/` or `/split/new/merchant/`
4. Notice these pages are accessible.

## Expected Result:
 Merchant and Date shouldn't be accessible through deeplink

## Actual Result:
Merchant and Date are  accessible through deeplink

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/875654cc-1a74-4e9c-a816-2cc736900fb9

https://github.com/Expensify/App/assets/93399543/5590bf53-9212-40a3-af8f-3f5a0eb2ee58

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694749185834509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c67f584444b66580</li>
        <li>Upwork Job ID: 1702782136315203584</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-16 14:04
Proposal by: @hungvu193
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694749185834509

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Date/Merchant is disabled for split, but still accessible with deeplink
### What is the root cause of that problem?
We only disabled the `MenuItem` for the split but didn't have the logic to goBack or prevent user from accessing the `MoneyRequestDatePage` and `MoneyRequestMerchantPage` when they create the split then access the merchant, date deeplink
https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/components/MoneyRequestConfirmationList.js#L490
https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/components/MoneyRequestConfirmationList.js#L510
### What changes do you think we should make in order to solve the problem?
Create a new variable `isTypeRequest`.
```javascript
 const isTypeRequest = iouType === CONST.IOU.MONEY_REQUEST_TYPE.REQUEST;
```

Update our `useEffect` to goBack when our request is not money request.
```javascript
if (!isDistanceRequest && (_.isEmpty(iou.participants) || (iou.amount === 0 && !iou.receiptPath) || shouldReset || !isTypeRequest)) {
  Navigation.goBack(ROUTES.getMoneyRequestRoute(iouType, reportID), true);
}
```
We can do it similar to other pages like merchant, distance.


We can also wrap our view with FullScreenNotFound when the request is not money request.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bfitzexpensify** [comment] 2023-09-18 15:58
@ntdiary yes, I think we have a well-established principle of using the "it's not here" page when a link is incorrect, so that should be fine here too

**Comment by puneetlath** [comment] 2023-09-18 20:18
We're having a bit of a discussion in this thread about a broader solution to the issue of using a direct link to go to a specific page on a form that you shouldn't be able to access without filling in prior info: https://expensify.slack.com/archives/C049HHMV9SM/p1695064187785649?thread_ts=1694439235.983099&cid=C049HHMV9SM

**Comment by bfitzexpensify** [comment] 2023-09-20 10:36
Nice. Looks like that thread ended without a solid conclusion, so bumped Tienifr to move their proposal forward to get a consensus. Once that's reached, I'll come back here to clarify the expected behaviour for this issue

**Comment by bfitzexpensify** [comment] 2023-09-26 09:38
We're still figuring out in https://expensify.slack.com/archives/C01GTK53T8Q/p1695209109095579 if we can standardize on a single form of UX

**Comment by bfitzexpensify** [comment] 2023-09-28 15:30
Same update

**Comment by bfitzexpensify** [comment] 2023-10-02 21:12
Bumped that thread again

**Comment by bfitzexpensify** [comment] 2023-10-06 18:32
OK, from that thread, it sounds like there's general buy-in to go with this approach:

> create a useScreenGuard(validationRule, fallbackScreen) hook. This will also use the same props and Onyx data available to the page to validate.

Essentially, the idea is that if you deep link to page 2 but page 1 isn’t filled, we'll fall back on page 1 

@tienifr as the author of that proposal, does that sound correct?

**Comment by bfitzexpensify** [comment] 2023-10-09 22:54
Bump on the above @tienifr

**Comment by bfitzexpensify** [comment] 2023-10-13 00:27
OK, so we'll want to use a similar approach as shared by @tienifr in https://github.com/Expensify/App/issues/27572#issuecomment-1756999099. I'm guessing we'll need proposals rewritten given that context @ntdiary?

**Comment by bfitzexpensify** [comment] 2023-10-18 15:46
@ntdiary just seeing your latest comment in that Slack thread - do you feel we have enough of a consensus to move forward with a particular approach?

**Comment by bfitzexpensify** [comment] 2023-10-20 18:23
Cool - updating title. I agree this isn't an urgent issue. Going to move this to weekly to match that holding issue

**Comment by bfitzexpensify** [comment] 2023-11-01 00:21
Still holding on https://github.com/Expensify/App/issues/26538 - though that itself has been taken off hold now, which is good

**Comment by bfitzexpensify** [comment] 2023-11-09 21:04
PR being review in the holding issue, we're closing to testing this again

**Comment by bfitzexpensify** [comment] 2023-11-21 23:21
Testing about to start on that PR in the holding issue

**Comment by bfitzexpensify** [comment] 2023-12-03 12:48
still held

**Comment by bfitzexpensify** [comment] 2023-12-12 21:16
Still on hold, that issue is moving

**Comment by bfitzexpensify** [comment] 2023-12-22 13:30
With the refactor, this is no longer happening. Closing this out.

**Closed by bfitzexpensify** 2023-12-22 13:30 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
