### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] Console error on clicking on download icon on deleted message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19413] opened 2023-05-22 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on web chrome
2. Open console
3. Send an image in a chat. 
4. Click reply in the image to open a thread. 
5. Delete the image while in the thread. Wait until the image deletes. 
6. Hover over the deleted message and you can see the download option
7. Click on it and notice that nothing happens, and you see an error in the console. 

## Expected Result:
We shouldn't show download option after deleting a message. 

## Actual Result:
We show option to download the image after the image is deleted. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/94084ce8-e3f5-4886-81e7-9bacb5f23d00

https://github.com/Expensify/App/assets/43996225/e826652c-c20b-4d7e-bbbb-baa722fff87c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684489220942129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8f88bf5b41b887d</li>
        <li>Upwork Job ID: 1661110256348393472</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by bogoroh** [comment] 2023-05-23 01:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When deleting an attachment there download button is still present which causes console.log errors.

### What is the root cause of that problem?
ContextMenuActions.js has logic on if it should display the `download button` yes or no. The logic doesn't check if the attachment is still present. So a deleted attachment will still return true.

```
shouldShow: (type, reportAction) => {
            const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const isAttachment = _.has(reportAction, 'isAttachment') ? reportAction.isAttachment : ReportUtils.isReportMessageAttachment(message);
            return isAttachment && reportAction.reportActionID && false;
        },
```

### What changes do you think we should make in order to solve the problem?
Add some additional code checks to make sure the parentAction was actually removed.

https://github.com/Expensify/App/blob/846d593baa82da52e7dc1cdfddb773b8254d60d7/src/pages/home/report/ContextMenu/ContextMenuActions.js#L91

Should become :
`return isAttachment && reportAction.reportActionID && !reportAction.originalMessage.isDeletedParentAction;`

<img width="1354" alt="Screenshot 2023-05-22 at 8 10 01 PM" src="https://github.com/Expensify/App/assets/4615263/0aaccf4c-314b-4017-93d7-07107a770e45">

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by bogoroh** [comment] 2023-05-23 01:22
Contributor details
Your Expensify account email: <mrtedits@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01043555e50efb5444>

**Comment by bogoroh** [comment] 2023-05-23 01:23
Contributor details
Your Expensify account email: mrtedits@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01043555e50efb5444

**Comment by Pujan92** [comment] 2023-05-23 02:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on trying to download the deleted attachment

### What is the root cause of that problem?
On deleting the attachment we are cleaning the `html` prop of the message and on click of the delete it should throw an error here bcoz the `sourceURL` will be null here. So accessing the `match` on null will cause the issue.
https://github.com/Expensify/App/blob/846d593baa82da52e7dc1cdfddb773b8254d60d7/src/pages/home/report/ContextMenu/ContextMenuActions.js#L94-L99

### What changes do you think we should make in order to solve the problem?
We should not show the delete option in the context actions as the image url is being removed from the `html` prop of the message. To achieve this we need to add 1 more condition ` && !message.isDeletedParentAction` here.

https://github.com/Expensify/App/blob/846d593baa82da52e7dc1cdfddb773b8254d60d7/src/pages/home/report/ContextMenu/ContextMenuActions.js#L91

<img width="494" alt="Screenshot 2023-05-23 at 7 51 11 AM" src="https://github.com/Expensify/App/assets/14358475/bedae844-2dfe-482b-8a82-59a8df36ccc8">

**Comment by hungvu193** [comment] 2023-05-23 04:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on clicking on download icon on deleted message
### What is the root cause of that problem?
When we deleted the attachment thread message, we remove the text and html. So when we tried to download the deleted attachment, it will be crashed since `sourceURL` will be null:
https://github.com/Expensify/App/blob/846d593baa82da52e7dc1cdfddb773b8254d60d7/src/pages/home/report/ContextMenu/ContextMenuActions.js#L99
### What changes do you think we should make in order to solve the problem?
Since `isAttachment` inside `reportAction` isn't updated when we deleted the thread attachment message and we already had a function to check if the current message is attachment, I think we can hide the download button by updating the condition of `isAttachment` inside `shouldShow` function of Download button to this:
```javascript
 const isAttachment = ReportUtils.isReportMessageAttachment(message);

// Optional: we can also update isReportMessageAttachment 
export default function isReportMessageAttachment({text, html, isDeletedParentAction}) {
    if (isDeletedParentAction || !text || !html) {
        return false;
    }

    const regex = new RegExp(` ${CONST.ATTACHMENT_SOURCE_ATTRIBUTE}="(.*)"`, 'i');
    return text === CONST.ATTACHMENT_MESSAGE_TEXT && !!html.match(regex);
}
```

### What alternative solutions did you explore? (Optional)
We can also still allow the download button with deleted attachment, but we should add an early return and showing an error for user to let them know, this attachment is no longer exist, they can't download them:

```javascript
// inside onPress function 
const {originalFileName, sourceURL} = attachmentDetails;
 if (!sourceURL) {
  Grow.show(' this attachment is no longer exist'....);
   hideContextMenu(true, ReportActionComposeFocusManager.focus);
}
```

**Comment by LiaKim07** [comment] 2023-05-23 11:14
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on trying to download the deleted attachment

### What is the root cause of that problem?
When click the download on deleting the attachment, sourceURL will be `null `value. That's why it shows console error when click the download icon.
![image](https://github.com/Expensify/App/assets/93604038/c16ca584-1970-4345-b311-5212528ef539)


### What changes do you think we should make in order to solve the problem?
In fact, the tooltip part should not be shown for deleted attachments and deleted messages like Slack and other chatting apps.
![image](https://github.com/Expensify/App/assets/93604038/dcd505e5-5a55-4e2a-9db0-1fc24f94a2c6)

![image](https://github.com/Expensify/App/assets/93604038/11359cd4-5d2d-497d-baf5-e6afc1d3fa10)
I think, it's the right way in the chatting app.

We can implement that functionality based on whether the message or attachment is deleted.

**Comment by joekaufmanexpensify** [comment] 2023-05-23 20:41
I was able to reproduce this on web. However, the bug here isn't the console error IMO. It's that we show a download icon after deleting the image. We shouldn't show this. 

Also, this doesn't just apply to workspaces. It applies to any type of message in the app. Cleaned up the reproduction steps to reflect this.

**Comment by joekaufmanexpensify** [comment] 2023-05-24 19:45
@0xmiroslav could you please review the above proposals when you have a chance?

**Comment by victornnaji** [comment] 2023-05-25 00:22
And we need reactions for the Deleted message?

**Comment by LiaKim07** [comment] 2023-05-25 00:24
@0xmiroslav , we need reactions for the [Deleted Message]?

**Comment by bondydaa** [comment] 2023-05-25 21:14
Hmm I agree we should def not show the download button - I think we could just focus on that part for now and get a solution done just scoped to that.

I'm not exactly sure about the `Delete` and `Copy` buttons, if I had to guess this has to do with a message being threaded and I think trying to address that here could lead to some scope creep and complexity. Said differently I think changing when the Delete and Copy icons show is more of a feature request than a bug but 🤷 .

cc @chiragsalian since I think you helped with the Threads feature.

**Comment by joekaufmanexpensify** [comment] 2023-05-25 21:23
If we know how we want to proceed with the `Delete` and `Copy` I kinda feel like no reason not to handle them here too personally. 

It makes sense to me to prob get rid of delete. As at that point, the user has already deleted the message, no? So there isn't anything else to delete. 

`Copy` is just meant to copy the text of the message, right? If so, I don't feel super strongly about removing it. Because technically, there is still text there `[deleted message]`. It seems like we treat that like any other message, so not sure why the user wouldn't be able to copy that text. Although, right now, the `copy` button seems to do nothing for this.

**Comment by joekaufmanexpensify** [comment] 2023-05-26 18:27
Adding an additional assignee here as I'm OOO next week (until June 5th). We have a few proposals here, and should be close to selecting one relatively soon!

**Comment by bogoroh** [comment] 2023-05-27 14:42
Thank you, I'll have a PR by the end of the day (Saturday May 27th)

**Comment by dukenv0307** [comment] 2023-05-29 01:25
@0xmiroslav @bogoroh's [proposal](https://github.com/Expensify/App/issues/19413#issuecomment-1558315695) will make the app crash when uploading the attachment because isDeletedParentAction is undefined 
<img width="1440" alt="Screenshot 2023-05-29 at 08 24 55" src="https://github.com/Expensify/App/assets/129500732/543c4cd4-10b5-4891-8a51-2bf328ee6268">

Could you take a look [My proposal here](https://github.com/Expensify/App/issues/19677#issuecomment-1565459236)? It works well

**Comment by bondydaa** [comment] 2023-06-01 20:16
I merged the PR today so should get deployed soon, maybe tomorrow or next week. i haven't kept up with our deploy status this week.

**Comment by joekaufmanexpensify** [comment] 2023-06-04 16:14
@jliexpensify I'm back from OOO, so removing your assignment. Thanks for covering!

**Comment by joekaufmanexpensify** [comment] 2023-06-12 13:18
@0xmiroslav Could you please complete your steps for the C+ checklist? Then, we can issue payment here.

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:01
>I think regression test needs to be migrated into https://github.com/Expensify/App/issues/20074 which handles all context menu actions, not only download icon.

@0xmiroslav Isn't that issue just for regular messages though? Vs this being images specifically. I agree they are related, but it feels like a slightly different case. Or do you mean just have the image case as a 1b regression test to the 1a in the above linked issue?

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:09
>So comprehensive regression test step will be:

Cool those steps makes sense. I'll comment them on the other issue to save them the work!

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:22
BZ checklist is complete, all set to issue payment here!

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:23
@bogoroh $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:25
@0xmiroslav $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:25
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-06-12 19:25
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-06-12 19:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
