### ISSUE TITLE
[$500] Compose-Profile in header is shown when tapping on deep link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32905] opened 2023-12-12 10:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. From slack tap on this deep link
https://staging.new.expensify.com/a/hello

## Expected Result:
When user taps on this deep link, "profile" must not be shown as title in header.

## Actual Result:
When user taps on this deep link, "profile" is shown as title in header.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/cfc97f86-897a-4a10-9515-b5f0b3dcee17

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3a5ca00ba4560c8</li>
        <li>Upwork Job ID: 1734517364121460736</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by apps-ferreiro** [comment] 2023-12-12 10:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Compose-Profile in header is shown when tapping on deep link

### What is the root cause of that problem?

The root problem of the issue is that the link used in the example is used for opening a user profile in the Right modal:

[Here](https://github.com/Expensify/App/blob/main/src/ROUTES.ts#L28-L31)

Since the userId is not found we are shown the error screen.

### What changes do you think we should make in order to solve the problem?
We could validate userIds before navigation. We have the helper function `isValidAccountRoute` that we could use.

### What alternative solutions did you explore? (Optional)

**Comment by apps-ferreiro** [comment] 2023-12-12 10:44
Contributor details
Your Expensify account email: isidoro.ferreiro@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~018bd6ae4efe8f4b52

**Comment by apps-ferreiro** [comment] 2023-12-12 10:45
Contributor details
Your Expensify account email: isidoro.ferreiro@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018bd6ae4efe8f4b52

**Comment by samilabud** [comment] 2023-12-13 04:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose-Profile in header is shown when tapping on deep link

### What is the root cause of that problem?
Currently when the profile page loads we validate only if the account ID in the URL is a number, and if so we add the [default data to Onyx](https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/pages/ProfilePage.js#L145) (this also causes another issue, showing the profile as hidden when the profile does not exist). Also, the bug reported only happens when the account  ID has text or the ID is very large. See the video:

https://github.com/Expensify/App/assets/5216036/6e4aea82-d069-4281-a04a-effdfe92e1f2



### What changes do you think we should make in order to solve the problem?
We should look into props.personalDetails in [ProfilePage.js](https://github.com/Expensify/App/blob/main/src/pages/ProfilePage.js) and verify if AccountID is in the list, with this we can determinate if the user exists in our DB, something like:

```
const [profileExists, setProfileExists] = useState(null);
    // eslint-disable-next-line es/no-optional-chaining
    const shouldShowProfileError = props.personalDetails[accountID]?.shouldShowProfileError;
    useEffect(() => {
        const setProfileStatus = () => {
            // The props.personalDetails has all the valids accountIDs
            const validAccountIds = _.keys(props.personalDetails);
            const profileFound = _.filter(validAccountIds, (id) => id === accountID.toString()) >= 1;
            setProfileExists(profileFound);
        };
        setProfileStatus();
    }, [accountID, props.personalDetails]);
``` 

Then we can determine better if we should openPublicProfilePage and if not we'll need to set the isLoading variable in Onyx as false like:

```
useEffect(() => {
        if (profileExists && ValidationUtils.isValidAccountRoute(accountID) && !hasMinimumDetails) {
            PersonalDetails.openPublicProfilePage(accountID);
        } else if (profileExists !== null && !profileExists) {
            // eslint-disable-next-line rulesdir/prefer-actions-set-data
            Onyx.set(ONYXKEYS.PERSONAL_DETAILS_LIST, {
                ...props.personalDetails,
                [accountID]: {
                    ...props.personalDetails[accountID],
                    shouldShowProfileError: true,
                },
            });
        }
    }, [accountID, hasMinimumDetails, profileExists, props.personalDetails]);
```

Finally, we should show the warning in this way:

```
{shouldShowProfileError && (
                    <BlockingView
                        icon={Illustrations.ToddBehindCloud}
                        iconWidth={variables.modalTopIconWidth}
                        iconHeight={variables.modalTopIconHeight}
                        title="The user profile does not exist"
                        shouldShowLink
                        link={props.translate('notFound.goBackHome')}
                    />
                )}
```
If shouldShowProfileError is true, we should hide the other components like:

```
{!shouldShowProfileError && shouldShowBlockingView && (
                    <BlockingView
                        icon={Illustrations.ToddBehindCloud}
                        iconWidth={variables.modalTopIconWidth}
                        iconHeight={variables.modalTopIconHeight}
                        title={props.translate('notFound.notHere')}
                        shouldShowLink
                        link={props.translate('notFound.goBackHome')}
                    />
                )}
```


See the final result:

https://github.com/Expensify/App/assets/5216036/a1637ba8-62b8-4b5c-ae97-e136341b3a7f

**Comment by getusha** [comment] 2023-12-15 10:30
Reviewing

**Comment by getusha** [comment] 2023-12-15 11:32
Raised a discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1702639941065949, to determine if this is worth fixing.

**Comment by sonialiap** [comment] 2023-12-15 14:18
This doesn't fit into any of the waves. I agree with the votes to :donothing:. Closing out

**Closed by sonialiap** 2023-12-15 14:18 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by cartersteinhoff** [comment] 2023-12-15 18:48
@sonialiap, just curious, if the issue is closed out as completed and "donothing" is the course of action taken, is there a bounty awarded to any of the proposals?

**Comment by cartersteinhoff** [comment] 2023-12-15 18:50
Contributor details
Your Expensify account email: cartersteinhoff@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011e73a62e9be4d45c

**Comment by KevinBlakeLopez** [comment] 2023-12-22 17:12
@sonialiap I am interested in contributing proposals to issues that are raised for this app, but when I see instances such as these it is discouraging because as contributors we can do everything right on our end and propose good solutions, but as it turns out there is no real potential for payout.  This kind of situation decreases the expected value of answering these issues with proposals.  Hopefully, these kinds of situations are kept to minimum with plans to reduce their occurrences in the future?
