### ISSUE TITLE
[HOLD for payment 2024-03-22] [$250] Settings - Back button looped when navigated on Contact Methods page several

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38296] opened 2024-03-14 11:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/35446

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+omadm28@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: for Desktop or Web user should resize window to mobile view
1. Open app
2. Tap on Profile icon in bottom
3. Tap on Profile
4. Tap on "Contact Method"
5. Tap on Back button
6. Repeat 4-5 steps three or more times in a row
7. Tap on back button

## Expected Result:
User should be navigated back on account Settings page

## Actual Result:
User remains on the Profile settings page when tapped on back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/66073e98-938f-4889-bfb9-a6594c888f83

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9704b9b31d6d994</li>
        <li>Upwork Job ID: 1768267455977009152</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by izarutskaya** [comment] 2024-03-14 11:57
@danieldoglas I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-14 11:58
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by mountiny** [comment] 2024-03-14 12:45
@kosmydel

**Comment by mountiny** [comment] 2024-03-14 12:46
cc @abzokhattab @ntdiary from the linked PR too

**Comment by pasyukevich** [comment] 2024-03-14 12:57
Hi,
I'm Eugene from Callstack - an expert contributor group
I’d like to work on this issue

**Comment by mountiny** [comment] 2024-03-14 13:11
@danieldoglas I think this might be related to the ideal nav PR I have managed with @kosmydel so going to take it over from you if you do not mind

**Comment by mountiny** [comment] 2024-03-14 13:18
@abzokhattab are you available to raise the PR now? Are you happy with $250 compensation given this is a blocker?

**Comment by kosmydel** [comment] 2024-03-14 14:48
Hey, I'm from Software Mansion. This regression comes from ideal nav v2 so I will fix it.

**Comment by akinwale** [comment] 2024-03-14 15:25
@abzokhattab Following the conversation, just to clarify, there are no further changes needed on the PR?

**Comment by luacmartins** [comment] 2024-03-14 18:20
This is fixed on staging.

**Comment by akinwale** [comment] 2024-03-20 18:34
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/37421 was identified as the source of the regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify NewDot on mobile (mWeb or native iOS/Android).
2. Tap on the Profile icon.
3. Tap on Profile.
4. Select "Contact methods".
5. Navigate back.
6. Navigate back a second time.
7. Verify that the Profile page does not display after the second back navigation action.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-03-20 18:37
@kadiealexander Just noting that the correct payment due date is 2024-03-22 since this was deployed to production on [2024-03-15](https://github.com/Expensify/App/pull/38308#issuecomment-1999346501).

Also, there's an error with the automatic offers. I am unable to accept mine on Upwork.

**Comment by kadiealexander** [comment] 2024-03-21 00:49
Payouts due:

Contributor: $250 @abzokhattab
Contributor+: $250 @akinwale

Upwork job is [here](https://www.upwork.com/ab/applicants/1768267455977009152/job-details).

Please accept the Upwork offers we've sent across!

**Comment by akinwale** [comment] 2024-03-21 01:08
> Upwork job is [here](https://www.upwork.com/ab/applicants/1768267455977009152/job-details).
> 
> Please accept the Upwork offers we've sent across!

I think new offers may need to be sent.

**Comment by kadiealexander** [comment] 2024-03-21 02:33
I've manually sent offers just now, can you both check and see if you're able to accept them?

**Comment by kadiealexander** [comment] 2024-03-21 02:36
Awesome! Will pay out on the 22nd :)

**Comment by akinwale** [comment] 2024-03-21 09:24
> I've manually sent offers just now, can you both check and see if you're able to accept them?

Accepted. Thanks!

**Closed** 2024-03-22 03:24 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
