### ISSUE TITLE
 Login with existing account–After login via link user redirect on "Hmm... it is not here" page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30206] opened 2023-10-23 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open [https://staging.new.expensify.com/.](https://staging.new.expensify.com/)
2. Log out
3. Navigate to this link - https://staging.new.expensify.com/concierge
4. Log in with [ponikarchuks+2@gmail.com.](mailto:ponikarchuks+2@gmail.com.)

## Expected Result:
Navigated to the concierge chat after login

## Actual Result:
"Hmm... it is not here" page opens when navigate via deeplink https://staging.new.expensify.com/concierge
and log in with [ponikarchuks+2@gmail.com](mailto:ponikarchuks+2@gmail.com)
account
"Hmm... it is not here"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/c6f5d9bb-b902-4e75-812d-c6283412c252

[logs2.txt](https://github.com/Expensify/App/files/13079072/logs2.txt)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment] 2023-10-23 21:38
I could not reproduce this problem with my account:
<img width="955" alt="Screenshot 2023-10-23 at 14 35 44" src="https://github.com/Expensify/App/assets/705000/b390e05b-35a4-4a53-9997-483553a61493">

**Comment by tylerkaraszewski** [comment] 2023-10-23 21:48
@zanyrenney - do you want to see if this happens for you?

**Comment by marcaaron** [comment] 2023-10-23 21:52
I can't repro either. Let's demote.

**Comment by zanyrenney** [comment] 2023-10-24 10:36
I don't know why this was assigned to me at 00.45 😓 @tylerkaraszewski

**Comment by zanyrenney** [comment] 2023-10-24 10:36
I have tried now and I also can't reproduce, should we make this daily instead?

**Comment by tylerkaraszewski** [comment] 2023-10-24 15:30
I'm gonna close it since nobody can make it happen.

**Closed by tylerkaraszewski** 2023-10-24 15:30 UTC
Labels: Engineering, Hourly, Bug
