### ISSUE TITLE
IOU - IOU details page crashes after refreshing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26195] opened 2023-08-29 12:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Request money from another user
3. Click IOU preview twice to open IOU details page
4. Refresh the page

## Expected Result:
The page does not crash

## Actual Result:
The app crashes after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3e02c300-5ddb-4b46-9acb-5fc6a96b3241

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-08-29 12:40
I think same RCA with https://github.com/Expensify/App/issues/26181#issuecomment-1697282687

**Comment by luacmartins** [comment] 2023-08-29 18:08
Agree. It has the same root cause as https://github.com/Expensify/App/issues/26181#issuecomment-1697282687 and it's caused by an API regression https://github.com/Expensify/Web-Expensify/pull/38626. So this is not a blocker for App.

**Comment by luacmartins** [comment] 2023-08-29 20:13
Fix here - https://github.com/Expensify/Web-Expensify/pull/38665. The fix is in Web-E, so this is not an App blocker.

**Comment by chiragsalian** [comment] 2023-08-29 20:56
Resolved on staging with a web-E CP. Closing issue. If it persists feel free to reopen.

**Closed by chiragsalian** 2023-08-29 20:56 UTC
Labels: Engineering, Hourly
