### ISSUE TITLE
[HOLD ON #11182] Web - Task report - Deleted task report can't be chatted on

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43962] opened 2024-06-18 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nahummelaku9+cd@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to Staging.new.expensify.com
2. Click on FAB
3. Click on Assign task
4. Assign task to yourself
5. Navigate to task report
6. Add a comment on the task
7. Click on the 3 dot menu
8. Cancel the task

## Expected Result:
The task report can still be chatted on (Should act like a regular chat thread)

## Actual Result:
The task report is archived and can't be chatted on. A banner is displayed saying the chat room has been archived

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3fb9402a-a57f-4a6d-96eb-182ed24a7bf1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2024-06-18 22:33
Can repro - just checking behaviour internally:

![image](https://github.com/Expensify/App/assets/30815269/ccbf72b4-c42f-4bd7-a3d2-ce482e70432c)

**Comment by jliexpensify** [comment] 2024-06-19 00:04
This is being worked on atm: https://github.com/Expensify/Auth/pull/11182

**Comment by jliexpensify** [comment] 2024-06-28 03:55
Waiting for re-test

**Comment by jliexpensify** [comment] 2024-08-01 03:20
Hi @srikarparsi - assigning you this because Applause are reporting that this issue wasn't fixed by your project. Should we make this `External`? 

Sorry for the delay, this got lost amongst my other GH's.

**Comment by srikarparsi** [comment] 2024-08-01 15:59
Hey, I'm not able to reproduce this. I'm able to comment on deleted tasks. Do you think you could check @jliexpensify

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/756ec3b6-a982-43f1-af1b-f693fc7d82f0">

**Comment by srikarparsi** [comment] 2024-08-01 16:04
Hm, actually the behavior does seem to be weird for tasks within DMs but it's a different issue.

Deleted tasks with comments on them are no longer accessible.
1. Click FAB
2. Assign a task to yourself and share it in a DM
3. Comment on the task
4. Delete the task
After a second, the task will not be accessible.

I don't think this is expected based on this [comment](https://expensify.slack.com/archives/C03TQ48KC/p1717776068685189?thread_ts=1717696303.543429&cid=C03TQ48KC). I think we want deleted tasks that have comments on them to be accessible. Is that right @puneetlath?

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/78afe16e-5d0d-40ef-bbe4-ff208b0fc122">
The bottom says `[deleted task]` even though it originally had comments on it.

**Comment by jliexpensify** [comment] 2024-08-01 23:53
Hmm yesterday, I was seeing a spinner when trying to assign a task to myself (apologies @srikarparsi should have added this in my comment too 😅 )

However, it looks like this is now working (i.e. I can chat on a deleted Task)

I also tested against an older task and it worked:

![image](https://github.com/user-attachments/assets/12f3f3af-1a7a-4cab-b72b-1a503087c56f)

**Comment by puneetlath** [comment] 2024-08-02 16:12
>I don't think this is expected based on this [comment](https://expensify.slack.com/archives/C03TQ48KC/p1717776068685189?thread_ts=1717696303.543429&cid=C03TQ48KC). I think we want deleted tasks that have comments on them to be accessible. Is that right @puneetlath?

I think in an ideal world yes. Though I don't think we necessarily need to focus on this right now.

**Comment by jliexpensify** [comment] 2024-08-06 01:28
Should we close this then @puneetlath @srikarparsi?

**Comment by srikarparsi** [comment] 2024-08-06 01:36
I just checked [this](https://github.com/Expensify/App/issues/43962#issuecomment-2263432392) again and am not able to reproduce it anymore. So I think we can close this out anyway

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/d60214db-7e3a-4d90-887a-ca3eb43119d2">

**Closed by srikarparsi** 2024-08-06 01:36 UTC
Labels: Monthly, Bug
