### ISSUE TITLE
[PAID] [$250] The preference setting doesn’t work when navigating between chat and settings.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47273] opened 2024-08-12 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723478204237729

## Action Performed:
1. Go to setting/preferences
2. Navigate to chat
3. Navigate back to setting tab
(If issue doesn’t occur, try again few times)

## Expected Result:
Setting animation should work and user can select option from preference setting.
## Actual Result:
Setting animation doesn’t work and user can’t select option from preference setting.

This issue also happen on setting/security setting/about setting/Troubleshoot setting/Save the world
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS:  Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6e197126-aaeb-492e-ade1-5d6a3679c9c0

https://github.com/user-attachments/assets/dff37113-1f37-46f6-b28c-0c90734fbde2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fa6be05e532f86f</li>
        <li>Upwork Job ID: 1825658706975919362</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 103646524</li>
<li>QichenZhu | Contributor | 103646535</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by QichenZhu** [comment] 2024-08-17 07:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pages with animated illustrations become unresponsive after switching to another page and back.

### What is the root cause of that problem?
The root cause is similar to https://github.com/Expensify/App/issues/36645#issuecomment-1971281335.

When you switch to another page, the animated illustration keeps running in the background, adding tasks to a queue.

When you switch back, the browser has to process these tasks first, making it unresponsive to actions using the same queue, such as opening a settings dialog.

### What changes do you think we should make in order to solve the problem?

Follow @hoangzinh's [suggestion](https://github.com/Expensify/App/issues/36645#issuecomment-1987240519). The previous [fix](https://github.com/Expensify/App/pull/38093) didn’t implement it because it wasn’t quite relevant to that issue, but it does resolve this issue.

> Moreover, if we can combine `useIsFocused` and `useAppState` hooks, I think it would improve performance here.

https://github.com/Expensify/App/blob/76158981580aa046592df17c940fb6b289b0924d/src/components/Lottie/index.tsx#L36

```TSX
import {useIsFocused} from '@react-navigation/native';
```

```TSX
const isFocused = useIsFocused();
if (isError || !isFocused || appState.isBackground || !animationFile || !isSplashHidden) {
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by strepanier03** [comment] 2024-08-19 22:17
Confirmed this occurred on v9.0.22-5 after 3 tries.

**Comment by hungvu193** [comment] 2024-08-20 02:30
Go ahead please @suneox  😄

**Comment by aldo-expensify** [comment] 2024-08-23 05:33
Contributor role: @QichenZhu 
C+ role: @suneox

**Comment by QichenZhu** [comment] 2024-08-23 06:49
Thanks for reviewing this.

@suneox Could you double-check if the drawback of the main solution described in my [proposal](https://github.com/Expensify/App/issues/47273#issuecomment-2294733914) is acceptable? The alternative solution solves this drawback but adds complexity.

cc: @strepanier03 @aldo-expensify 

> The drawback of the main solution is that the animated illustration disappears when the right-side modal is open.

https://github.com/user-attachments/assets/69831606-523c-4e8b-9f40-1dfbd70fc32b

**Comment by hungvu193** [comment] 2024-08-29 13:49
Coming from [here](https://github.com/Expensify/App/pull/48040)
I think that's better to keep these animations to run on the background or at least when we still can see it through backdrop.

Cc @shawnborton and @dannymcclain, @dubielzyk-expensify

**Comment by dannymcclain** [comment] 2024-08-29 13:52
>I think that's better to keep these animations to run on the background or at least when we still can see it through backdrop.

Agree. I think if you can see the animations, we should let them run. Alternatively we could _replace_ the animation with a static frame/illustration... but that kinda feels like the juice wouldn't be worth the squeeze to me.

**Comment by hungvu193** [comment] 2024-08-29 14:39
@suneox can you please try to test it with https://github.com/Expensify/App/pull/48040#issuecomment-2316539919?

**Comment by QichenZhu** [comment] 2024-08-29 15:08
> @suneox can you please try to test it with [#48040 (comment)](https://github.com/Expensify/App/pull/48040#issuecomment-2316539919)?

The animations under the backdrop can still play when a right-side modal is open because it was explicitly enabled in [this line](https://github.com/Expensify/App/blob/e77f20458ad13d94c7b0188acc2ed1a91bd8ccbd/src/components/Lottie/index.tsx#L47). Similarly, we could add logic to `src/components/Lottie/index.tsx` to allow animations to play in the background in the scenario of #48040.

**Comment by QichenZhu** [comment] 2024-08-29 15:09
> > I think that's better to keep these animations to run on the background or at least when we still can see it through backdrop.
> 
> Agree. I think if you can see the animations, we should let them run. Alternatively we could _replace_ the animation with a static frame/illustration... but that kinda feels like the juice wouldn't be worth the squeeze to me.

The problem is that sometimes playing animations in the background causes issues, and sometimes it doesn’t. Previously, when something went wrong, such as in #36645 and this issue, we added logic to `src/components/Lottie/index.tsx`. Ideally, though, it would be better to handle all these scenarios in a unified way.

**Comment by hungvu193** [comment] 2024-08-30 09:01
Btw, https://github.com/Expensify/App/pull/48283 was reverted, so I think that's ok to create another PR to cover both case. @QichenZhu

**Comment by suneox** [comment] 2024-09-05 06:15
@QichenZhu I think we should check `navigationRef.isReady()` before access navigation to resolve regression issue

**Comment by suneox** [comment] 2024-09-05 06:25
> Btw, #48283 was reverted, so I think that's ok to create another PR to cover both case. @QichenZhu

@hungvu193 The PR for this issue has been reverted on the latest main, and the [PR](https://github.com/Expensify/App/pull/48040) you’re working on is still in draft. So I think we shouldn’t handle issue not ready within the scope of this issue.

**Comment by QichenZhu** [comment] 2024-09-05 08:13
@suneox @hungvu193 I agree that it's too early to consider it at this stage, as both #48040 and our new PR #48444 are in progress. After whichever PR is merged first, I think the other side might need to retest if the issue still exists and avoid it if needed.

**Comment by hungvu193** [comment] 2024-09-05 08:16
https://github.com/Expensify/App/pull/48040 only updates the UI and we found [this bug](https://github.com/Expensify/App/issues/47273#issuecomment-2317717050) while testing.

**Comment by QichenZhu** [comment] 2024-09-05 08:36
@hungvu193 Yeah, but it's tested with the old PR.

Is there a plan when #48040 will be merged?

If so, @suneox could we hold this on it?

**Comment by hungvu193** [comment] 2024-09-05 08:38
I don't think we should hold this issue for it, please go ahead and continue with the PR, but please also fix https://github.com/Expensify/App/issues/47273#issuecomment-2317717050

**Comment by suneox** [comment] 2024-09-05 09:13
> #48040 only updates the UI and we found [this bug](https://github.com/Expensify/App/issues/47273#issuecomment-2317717050) while testing.

@hungvu193 Could you please help me confirm the [reference issue](https://github.com/Expensify/App/pull/48040#issuecomment-2316539919) do not happen on the latest main after revert #48283?

**Comment by suneox** [comment] 2024-09-10 18:23
@hungvu193 I’ve verified the new PR for this issue, and it also resolves [#47273 (comment)](https://github.com/Expensify/App/issues/47273#issuecomment-2317717050). So we will proceed without holding for your [referenced issue](https://github.com/Expensify/App/pull/48040#issuecomment-2316539919)

**Comment by suneox** [comment] 2024-09-25 10:37
@strepanier03  This issue has been [deployed to production](https://github.com/Expensify/App/issues/48954) two weeks ago, and the checklist is completed, so we can proceed with payment for this issue.

**Comment by suneox** [comment] 2024-10-07 17:57
@strepanier03 Friendly bump for payment

**Comment by QichenZhu** [comment] 2024-10-21 09:28
Gentle bump @strepanier03

**Comment by strepanier03** [comment] 2024-10-21 23:48
Sorry for missing this one, the automation to update the title helps so much and when it fails 🤦‍♀️ it makes it tough. Handling this now.

**Comment by strepanier03** [comment] 2024-10-21 23:56
This is paid and contracts closed. Sorry again.

**Closed** 2024-10-21 23:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
