### ISSUE TITLE
[Keyboard Initiative] mWeb/safari -Chat - When creating a new group the keyboard randomly disappears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10830] opened 2022-09-06 00:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Navigate to staging.new.expensifail.com
2. Log in with expensifail account
3. Tap the green + button
4. Click on the "New group" option
5. Select several random users from the search list
6. Tap to search bar
7. And start typing any user name

## Expected Result:
The user can enter a search query and tag to the new group

## Actual Result:
Unable to enter a search user because the keyboard randomly disappears

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.97.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188522549-589a0271-3b65-438f-849c-1131960724bc.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2022-09-06 11:02
Updating this to external, weekly. Only outstanding question is to confirm which platforms it's happening on (since this lists Web, Desktop App, which are platforms without a virtual keyboard to disappear - we should make sure the list is correct to make testing possible).

**Comment by thienlnam** [comment] 2022-09-06 11:02
I think we have a bug where the labels are being overwritten after adding certain labels - putting it back to weekly

**Comment by adelekennedy** [comment] 2022-09-07 11:39
[internal](https://www.upwork.com/ab/applicants/1567477540485226496/job-details)
[external](https://www.upwork.com/jobs/~01f38e05e26392be82)

**Comment by Beamanator** [comment] 2022-09-07 14:16
Hmm what I'm seeing is the keyboard hides when the user starts scrolling down the list of participants, are y'all seeing this in a different way? If that's the case, I'd go with this is expected 🤔

**Comment by Beamanator** [comment] 2022-09-07 14:16
And if it's "not" expected, I'd put this on hold for the upcoming Keyboard initiative

**Comment by Beamanator** [comment] 2022-09-07 14:43
Oh interesting! I didn't actually notice that, it looks like that's the 2nd thing that happens in the video? So yeah I think this will be good to put on hold for a bit since "we" (someone) is planning to lead up a rework of keyboard shenanigans in the near future, what do you think?

**Comment by Beamanator** [comment] 2022-09-12 09:04
Took away `Help Wanted` and added HOLD so we don't get any proposals for this while we're waiting for someone to take over the keyboard issues initiative :D

**Comment by adelekennedy** [comment] 2022-09-22 04:38
holding!

**Comment by Beamanator** [comment] 2022-10-03 10:48
Still on hold

**Comment by Beamanator** [comment] 2022-10-12 10:28
Still on hold

**Comment by mvtglobally** [comment] 2022-10-18 11:19
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2022-10-24 00:42
@Beamanator are we still holding even if it's not reproducible? Can we close this?

**Comment by Beamanator** [comment] 2022-10-24 07:49
@adelekennedy good question! Usually we'll wait for a 2nd or 3rd week of it not being reproducible, then applause will close it out

**Comment by Beamanator** [comment] 2022-11-01 16:12
Hmm haven't heard anything in a while, @mvtglobally would you mind having your team try to reproduce this again this week?

**Comment by mvtglobally** [comment] 2022-11-09 03:29
Issue not reproducible during KI retests. (Second week)

**Comment by Beamanator** [comment] 2022-11-10 14:12
Looks like it's possible this isn't reproducible anymore which would be nice 😅 Let's confirm one more week or someone else can test before closing

**Comment by parasharrajat** [comment] 2022-11-10 15:14
It seems like the root cause of this might be the keyboard closing feature on scroll. A feature was added on this page where when user scrolls the list, keyboard is closed for the user to see the full list. 

It may be possible that the list is scrolling while you are typing. But AFAIK, it reacts to user interactions not programmatic scrolls.

**Comment by adelekennedy** [comment] 2022-11-10 23:39
reassigning to @kevinksullivan to bug sit while I'm ooo

**Comment by kevinksullivan** [comment] 2022-11-14 20:34
Should this still be held @Beamanator ? We'll also see if this was not reproducible for a second week soon, which may mean we close it.

**Comment by Beamanator** [comment] 2022-11-14 21:42
I guess it's only "not on hold" if someone can reproduce, if it's still reproducible @parasharrajat mentioned a possible cause [here](https://github.com/Expensify/App/issues/10830#issuecomment-1310442119) but if it's not reproducible I think we should close

**Comment by parasharrajat** [comment] 2022-11-18 23:07
No update

**Comment by Beamanator** [comment] 2022-11-22 07:58
Coming back to [this comment](https://github.com/Expensify/App/issues/10830#issuecomment-1310442119) @parasharrajat - I see what you mean, in the OP it looks like the keyboard is disappearing when the list scrolls - If the scrolling wasn't happening because of the user manually scrolling around, that's a problem. But if the user starts typing, then scrolls - I think we're ok with the keyboard hiding there

**Comment by mvtglobally** [comment] 2022-11-22 20:45
Issue not reproducible during KI retests. (Third week)

**Comment by Beamanator** [comment] 2022-11-23 10:22
Looks like it's not so reproducible, let's close & we can reopen if it becomes a problem in the future

**Closed by Beamanator** 2022-11-23 10:22 UTC
Labels: External, Engineering, Daily, Bug
