### ISSUE TITLE
[$500] When tapping ESC the cancel button is highlighted briefly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35379] opened 2024-01-30 11:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Create money request then add receipt.
4. Open the receipt modal
5. Click three dots menu and click delete receipt
6. The delete confirm modal will appear
7. Press ESC

## Expected Result:
User expects the modal to close, with no highlighting from the ESC key. On other parts of the app like "Delete message" popup modal, there is no highlighting of the "Cancel" key when tapping ESC.

## Actual Result:
The ESC key does in fact close the module, however the "Cancel" button is briefly highlighted in blue.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/cf8b3e95-41cf-4842-984e-9eb008953994

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d3bb2275559995b</li>
        <li>Upwork Job ID: 1752286385771995136</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by divyanshugarg36** [comment] 2024-01-30 11:56
Hey 
I can solve this issue.

The issue must be caused by the focus css of the button and the key event triggering the focus event on the button
The easiest way to fix this can be tracking the key down event and disabling the focus functionality of the button using the appropriate class and CSS (Can be handled with JS)

Please let me know if you find the solution appropriate and I can start working on this...

Thank you

**Comment by divyanshugarg36** [comment] 2024-01-30 12:09
Contributor details
Your Expensify account email: divyanshugarg36@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0156d9b4eeb4a9c789?viewMode=1

**Comment by trjExpensify** [comment] 2024-01-30 15:24
Hm, this is incredibly minor. I had to watch the video back in the OP a few times at x0.75 playback speed to actually see it. 

I can't repro it on `v1.4.33-4` either. @akinwale I'm inclined to close this issue. You are effectively cancelling the action, so I don't think it's worth our time. Let me know if you think otherwise though!

**Comment by trjExpensify** [comment] 2024-01-30 15:42
Ah yeah, I'm on Mac Chrome. Tried the desktop app too!

**Comment by davidgelhar** [comment] 2024-01-31 01:53
@trjExpensify for what it's worth, I can reproduce it on both Safari & Chrome (prod). Agree that it's extremely minor

**Comment by akinwale** [comment] 2024-01-31 07:23
@trjExpensify I agree that we can close this, unless we want to maintain consistency with other parts of the app as indicated in the Expected Result in the OP.

> On other parts of the app like "Delete message" popup modal, there is no highlighting of the "Cancel" key when tapping ESC.

**Comment by trjExpensify** [comment] 2024-01-31 17:39
Cool, glad we agree it's super minor. I'm going to close this out, we have bigger fish to fry!

**Closed by trjExpensify** 2024-01-31 17:39 UTC
Labels: External, Daily, Help Wanted, Bug
