### ISSUE TITLE
Sign In - App crashes when sign in new account via magic link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30016] opened 2023-10-19 19:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account
3. Copy the Magic link from e-mail and change it to staging
4. Open a new tab and navigate to the staging magic link (abracadabra page is displayed)
5. Navigate to the original tab

## Expected Result:
The user is logged in with the new account

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/63ea19c3-7df2-4c1e-acf9-28e13a5e40db

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2023-10-19 19:30
Might be a dupe of https://github.com/Expensify/App/issues/29965

**Comment by tylerkaraszewski** [comment] 2023-10-19 20:22
I'm watching to see the progress on the other issue here for a minute.

**Comment by francoisl** [comment] 2023-10-19 21:22
This is fixed on v1.3.87-2 as well, it was indeed the same issue.

**Closed by francoisl** 2023-10-19 21:22 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
