### ISSUE TITLE
[$1000] Web - User details is not displayed when starting a chat with  a phone number account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22977] opened 2023-07-16 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'FAB'  menu
2. Click on 'New chat' icon
3. Search a valid phone number & select the user

## Expected Result:
User detail should be displayed on report screen

## Actual Result:
Describe what actually happened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 2023-07-16 18-22-02.webm](https://github.com/Expensify/App/assets/93399543/595fb981-b8a7-45e7-a3b0-98d03a8e3ad2)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689357276782499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5263bd75d7a601a</li>
        <li>Upwork Job ID: 1681046898779193344</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by Natnael-Guchima** [comment] 2023-07-16 18:47
Updated test step to better reproduce the issue 

Action Performed:
1. Click on 'FAB'  menu
2. Click on 'New chat' icon
3. Search for a phone number account that has no prior chat history with your current account
4. select the user

**Comment by lschurr** [comment] 2023-07-17 21:02
I reproduced this in Chrome.

**Comment by Thanos30** [comment] 2023-07-18 00:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Searching and creating a new chat using a phone number doesn't display user info.

### What is the root cause of that problem?
I believe this must have something to do with the backend logic, but here's the deal:

The root cause of this issue is on `navigateToAndOpenReport` function on `Report.js` file. When this function calls the `openReport` function with a phone number (without the format), it doesn't seem to be able to render the data, until a refresh or re-render in general.


### What changes do you think we should make in order to solve the problem?
On `navigateToAndOpenReport` function, we use the `addSMSDomainIfPhoneNumber` function to format the phone number. Sending the formatted number into `openReport` instead of the original phone number seems to solve the issue.

On line 545 of `Report.js`, we change it to be like this:

```
    openReport(reportID, formattedUserLogins, newChat);
```
This solves the issue.

**Comment by alitoshmatov** [comment] 2023-07-18 06:38
Looks like backend is sending two conflicting data for `openReport` request

Backend is sending these onyx updates.
<img width="735" alt="Screenshot 2023-07-18 at 11 35 41 AM" src="https://github.com/Expensify/App/assets/59907218/5690cd8f-32d2-4a8e-bc37-3e32417bd5da">

Onyx update in index 0
<img width="479" alt="Screenshot 2023-07-18 at 11 33 50 AM" src="https://github.com/Expensify/App/assets/59907218/c24da051-f784-4a4e-8359-87b7b8b70144">

Onyx update in index 3. As you can see, this one is clearing all data of this report, including participants which is resulting in blank screen.
<img width="487" alt="Screenshot 2023-07-18 at 11 35 21 AM" src="https://github.com/Expensify/App/assets/59907218/c593fdc6-d0b6-4cc4-ab80-5aa73124d0e2">

**Comment by lschurr** [comment] 2023-07-20 20:29
@eVoloshchak could you review the proposals and comments here?

**Comment by lschurr** [comment] 2023-07-24 15:11
Bump @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-07-26 19:16
I think this was resolved, I can't reproduce using the steps in the issue description

https://github.com/Expensify/App/assets/9059945/910d365f-a954-4c23-ae13-a7efbc837648

@Thanos30, @alitoshmatov, could you check if you can still reproduce this? Thanks

**Comment by Thanos30** [comment] 2023-07-26 19:42
@eVoloshchak Same for me, can't reproduce

**Comment by lschurr** [comment] 2023-07-26 19:47
Great! Do we know what fixed it? Should we issue payment to the bug reporter? @eVoloshchak

**Comment by lschurr** [comment] 2023-07-28 20:31
Will review and close on Monday.

**Comment by eVoloshchak** [comment] 2023-07-30 20:18
> Should we issue payment to the bug reporter? 

@lschurr, the rules in [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#raising-jobs-and-bugs) state the following

> If the bug is fixed by a PR that is not associated with your bug report, then you will not be eligible for the corresponding compensation unless you can find the PR that fixed it and prove your bug report came first

cc: @Natnael-Guchima

**Comment by lschurr** [comment] 2023-07-31 16:49
Great, closing!

**Closed by lschurr** 2023-07-31 16:49 UTC
Labels: External, Daily, Help Wanted, Bug
