### ISSUE TITLE
[HOLD App#35519] Android - Bank account - App crashes after filling out personal info offline killing app&go online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35974] opened 2024-02-06 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37.0
**Reproducible in staging?:** y
**Reproducible in production?:** cannot verify in production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Create a workspace if there is no one
3. Navigate to the workspace settings > Bank account
4. Tap Continue online with Plaid
5. Select the bank, e.g. Regions
6. Continue with the Plaid flow
7. Select the savings 1111 account in the drop-down and continue
8. Enter the company information and tap "Continue"
9. On the "Personal information" disable the internet connection
10. Fill out the personal information form
11. Kill the app and open it again
12. Return online and tap "Save and continue"

## Expected Result:
User is able to proceed to the next screen

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dd74acbe-5538-4a87-b841-ccad5022a786

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-06 22:51
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by marcaaron** [comment] 2024-02-07 00:03
This feels like a non-blocker to me and is likely happening on production already.

**Comment by trjExpensify** [comment] 2024-02-08 00:31
@greg-schroeder we're refactoring the VBBA flow in wave6 aren't we? So I think I agree this issue goes there. It would be good for the peeps working on it to make sure this crash gets cleaned up.

**Comment by trjExpensify** [comment] 2024-02-08 00:35
CC: @gedu do you agree on putting this on hold for the VBA refactor?

**Comment by trjExpensify** [comment] 2024-02-14 22:12
Reached out to @gedu for his input.

**Comment by gedu** [comment] 2024-02-15 15:32
Hey, this bug maybe is not valid anymore, given that the flow changed. 
I give a try with the new flow and you can't move forward without internet, if you reach the confirmation page, then go offline, kill the app and open it again, all keeps working. I would double check if still happens or close this issue @trjExpensify

**Comment by gedu** [comment] 2024-02-15 16:28
This is how the new UI looks, so this and the #35519 has the old UI, I checked the new UI using dev build and was working ok. 

<img width="1070" alt="Screenshot 2024-02-15 at 17 27 30" src="https://github.com/Expensify/App/assets/1676818/c8381026-4a61-41ad-8750-cd8c405b1bf8">

**Comment by trjExpensify** [comment] 2024-02-19 12:52
This is a dupe of #35519, so let's consolidate there.

**Closed by trjExpensify** 2024-02-19 12:52 UTC
Labels: Engineering, Daily, Overdue, Bug
