### ISSUE TITLE
 Bank account label in Workspace > Workflows > Make or track payments is too small

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40204] opened 2024-04-13 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712858899464959

## Action Performed:
1. Go to Workspace Settings > Workflows and enable the "Make or track payments" toggle

## Expected Result:
When there is no bank account added, the label for "Bank account" should be 15px in size

## Actual Result:
The label is too small and is 13px in size

## Workaround:
unknonw

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-04-11 at 20 06 20@2x](https://github.com/Expensify/App/assets/38435837/bea873f8-b886-4a50-ac34-d1816d3574b5)

https://github.com/Expensify/App/assets/38435837/db82020b-89e3-429b-bc5c-c4e3e4952f8a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2024-04-13 19:34
This issue will fix here https://github.com/Expensify/App/issues/39947, it has the same root cause. The style condition is correct  `hasVBA ? 13 : 15` but the issue is the `hasVBA` declaration is not correct after disable and then enable the "Make or track payments" for the first time, and this will fix here https://github.com/Expensify/App/issues/39947.

Tested in last main.

https://github.com/Expensify/App/assets/41129870/07b630bb-1a79-4595-ba7d-921530c20cab

**Comment by ikevin127** [comment] 2024-04-14 22:58
I can confirm that this issue will be fixed as part of the already open PR https://github.com/Expensify/App/pull/40182 from issue:
- https://github.com/Expensify/App/issues/39947.

Specifically the following lines of code:
1. [Line 89](https://github.com/Expensify/App/blob/f9a31989c006a63ab36749dd33b7f8054d0a709e/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L89): Fixed `hasVBA` check.
2. [Line 90](https://github.com/Expensify/App/blob/f9a31989c006a63ab36749dd33b7f8054d0a709e/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L90): Added `shouldShowBankAccount` variable.
3. [Line 191](https://github.com/Expensify/App/blob/f9a31989c006a63ab36749dd33b7f8054d0a709e/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L191): Passed `titleStyle` correctly based on `shouldShowBankAccount`.

**Comment by slafortune** [comment] 2024-04-15 16:31
Thanks @ikevin127 , in that case, let's close this 👍

**Closed by slafortune** 2024-04-15 16:31 UTC
Labels: Daily, Bug
