### ISSUE TITLE
[HOLD for payment 2022-11-11] [$250] Andriod/IOS - Connect Bank Account - Company page displayed instead Personal Information Page after tap back button on Onfido flow, error message displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11461] opened 2022-09-30 01:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with the expensifail account
3. Go to Setting - Workspace
4. Connect Bank account
5. Select Connect manually
6. Put routing number and account number
7. Follow the flow until you hit Onfido flow
8. Tap back button

## Expected Result:
Personal page displayed instead company Information Page after tap back button on Onfido flow, no error message

## Actual Result:
Company page displayed instead Personal Information Page after tap back button on Onfido flow, error message displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.10.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193170438-a5df5569-20f2-48d6-a985-36c4f412fe92.mp4

**Upwork URL:** https://www.upwork.com/jobs/~010e6ad9c23c041b36

**Issue reported by:** Applause - Internal Team (originally @thesahindia)
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stitesExpensify** [comment] 2022-09-30 18:00
I'm pretty confident this can be fixed externally by passing a different prop to the onFido component

**Comment by trjExpensify** [comment] 2022-09-30 18:31
👋 The contributor will need an account number and routing number to test with, no?

**Comment by mananjadhav** [comment] 2022-10-03 11:51
I tested this flow, but are we sure this is what we want?

I can see comments in `RequestorStep.js` which says we're explicitly sending them back to the `CompanyStep`,

```
// We're taking the user back to the company step. They will need to come back to the requestor step to make the Onfido flow appear again.
```

**Comment by akshayasalvi** [comment] 2022-10-03 12:12
**Proposal**
This is happening because in the following lines of `RequestorStep`,

https://github.com/Expensify/App/blob/6748e8a6c5363a626490e436c84ecd53df7266c6/src/pages/ReimbursementAccount/RequestorStep.js#L189-L197

We're setting the step as `CONST.BANK_ACCOUNT.STEP.COMPANY`, which we need to set it to `CONST.BANK_ACCOUNT.STEP.REQUESTOR`

But just updating the step doesn't help as the onFido component is set o the `RequestorStep` itself, so on back press it shows a blank page. To fix this we need to move the `this.props.achData.sdkToken` to state.

```diff
    this.state = {
      ...
+   onfidoToken: this.props.onfidoToken,
    };
  
On L166
-     const shouldShowOnfido = achData.useOnfido && this.props.onfidoToken && !this.state.isOnfidoSetupComplete;
+     const shouldShowOnfido = achData.useOnfido && this.state.onfidoToken && !this.state.isOnfidoSetupComplete;





<Onfido
+      sdkToken={this.state.onfidoToken}
-      sdkToken={this.props.onfidoToken}
      onUserExit={() => {
+           this.setState({ onfidoToken: undefined });
-          BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.COMPANY);
+.        BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.REQUESTOR);
      }}
      onError={() => {
          Growl.error(this.props.translate('onfidoStep.genericError'), 10000);
+           this.setState({ onfidoToken: undefined });
-          BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.COMPANY);
+.        BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.REQUESTOR);

      }}
````

**Comment by trjExpensify** [comment] 2022-10-03 12:32
> @stitesExpensify @trjExpensify I tested this flow, but are we sure this is what we want?
>
> I can see comments in RequestorStep.js which says we're explicitly sending them back to the CompanyStep

Oh, interesting! 🤔 I wonder why that is? The step before Onfido is personal details, so why do we skip over that page and go back to CompanyStep instead? @kevinksullivan & @marcaaron might know as they worked on this originally, I believe.

**Comment by kevinksullivan** [comment] 2022-10-03 16:09
Hmm trying to scroll back in my DM with @marcaaron because I believe this was part of the original design since it was easier at the time. I _think_ we kick the user back to the company info step because we don't create the VBA until after a certain point, so this may have to do with that timing and the need to re-submit the info. @marcaaron can you fill in the large gaps in my explanation?

**Comment by mananjadhav** [comment] 2022-10-03 16:23
>  so this may have to do with that timing and the need to re-submit the info.

Can you elaborate on resubmitting the info?

I did a basic test on @akshayasalvi's proposal and it seems to be working. But I haven't tested thoroughly so if there's something specific to be considered when doing this, it'll be helpful if can be linked to the issue.

**Comment by mananjadhav** [comment] 2022-10-05 05:00
@kevinksullivan @marcaaron @stitesExpensify Quick bump.

**Comment by Uros787** [comment] 2022-10-05 10:02
### Proposal

The problem is with the error messages we check on catching errors. We don't want to display the error when messages are one of these:
`USER_CANCELLED: 'User canceled flow'`
`USER_TAPPED_BACK: 'User exited by clicking the back button.',`
`USER_EXITED: 'User exited by manual action.',`

Currently, we are missing `USER_EXITED` message, I'm guessing since it was implemented in some of the later versions on react native onfido SDK.

Solution:

- Add a new onfido error message in [CONST.js:](https://github.com/Expensify/App/blob/11c2d496c3528ee00634440076ed8000bdcea3cb/src/CONST.js)

`USER_EXITED: 'User exited by manual action.',`
https://github.com/Expensify/App/blob/11c2d496c3528ee00634440076ed8000bdcea3cb/src/CONST.js#L587-L606


- Add check for this message in [index.native.js](https://github.com/Expensify/App/blob/2f5603d8441b4ad05b2e7bcdd277051508c04088/src/components/Onfido/index.native.js) where we are conditional asking on should we display the error(did user exit the flow or something else happened)

https://github.com/Expensify/App/blob/2f5603d8441b4ad05b2e7bcdd277051508c04088/src/components/Onfido/index.native.js#L44-L54
```
if (
  _.contains(
    [
      CONST.ONFIDO.ERROR.USER_CANCELLED,
      CONST.ONFIDO.ERROR.USER_TAPPED_BACK,
      CONST.ONFIDO.ERROR.USER_EXITED,
    ],
    errorMessage
  )
) {
  this.props.onUserExit();
  return;
}

```

And now there is no error anymore

- Also clear onfido token on [RequestorOnfidoStep.js](https://github.com/Expensify/App/blob/a8f673f35a8e54ef3b6ea53e73ef43fb40ad651a/src/pages/ReimbursementAccount/RequestorOnfidoStep.js)
```
<Onfido
  sdkToken={this.props.onfidoToken}
  onUserExit={() => {
    BankAccounts.clearOnfidoToken();
    BankAccounts.goToWithdrawalAccountSetupStep(
      CONST.BANK_ACCOUNT.STEP.REQUESTOR
    );
  }}
  onError={() => {
    // In case of any unexpected error we log it to the server, show a growl and return the user back to the company step so they can try again.
    Growl.error(this.props.translate("onfidoStep.genericError"), 10000);
    BankAccounts.clearOnfidoToken();
    BankAccounts.goToWithdrawalAccountSetupStep(
      CONST.BANK_ACCOUNT.STEP.REQUESTOR
    );
  }}
  onSuccess={(onfidoData) => {
    this.submit(onfidoData);
  }}
/>;

```

VIDEO:

https://user-images.githubusercontent.com/70144379/194034961-d9226719-c3d5-49be-b5e9-ffc1df0b2ccb.mov

**Comment by mananjadhav** [comment] 2022-10-06 04:15
@trjExpensify Based on @kevinksullivan's comment it seems we did that only because it was easier that time. Should I evaluate the proposal?

**Comment by trjExpensify** [comment] 2022-10-06 13:06
Yeah, at a minimum we want to fix the error appearing when navigating back. I do also think it makes more sense to navigate back to the personal information step instead of the company info step, but I don't have enough insight as to whether there's a show stopper in this: 

>I think we kick the user back to the company info step because we don't create the VBA until after a certain point, so this may have to do with that timing and the need to re-submit the info

If the proposal encompasses these things, then I don't see a reason why that isn't fine: 

1. No error message when clicking back from Onfido 
2. navigates back to the personal information step 
3. navigating forward again to Onfido to complete it, the request to create the VBA works correctly (i.e you don't run into errors and need to go and re-enter any info in the company step etc)

**Comment by mananjadhav** [comment] 2022-10-06 17:21
@trjExpensify In that case @Uros787's proposal seems to be fixing the error part. Should we go ahead and fix atleast that part?

**Comment by trjExpensify** [comment] 2022-10-06 20:11
https://github.com/Expensify/App/issues/11461#issuecomment-1268219826 - the video seems to navigate back to the personal info page as well though?

**Comment by Uros787** [comment] 2022-10-06 20:16
@trjExpensify correct, the problem stated that we should navigate to the personal info page
although as @mananjadhav said we can just fix the error part if we don't want to navigate to the personal info page

**Comment by trjExpensify** [comment] 2022-10-06 21:24
Yeah cool, I was just clarifying we seemingly solve both problems with the proposal. Did you test this as well? 

- Navigating forward again to Onfido to complete it, the request to create the VBA works correctly (i.e you don't run into errors and need to go and re-enter any info in the company step etc)

**Comment by mananjadhav** [comment] 2022-10-07 05:41
Yeah I tested the same code when @akshayasalvi proposal's earlier. It does solve both the issues. I thought if we're not sure whether to move back to Personal Information.

If we do plan to solve the transition too, then I am a little confused here because @akshayasalvi also proposed the same solution.

**Comment by Uros787** [comment] 2022-10-07 09:11
@mananjadhav I'm sorry but @akshayasalvi proposal does not solve the issue with the error. 
I double-checked, and his proposal only solves the navigating to the personal info page

**Comment by mananjadhav** [comment] 2022-10-07 09:16
Yes you're right @Uros787. What I meant is your proposal solves both the problems - error message and the navigation. But just to be fair to everyone, you as well as @akshayasalvi, I said I am a little confused because part 2 of both your proposals is exactly the same.

**Comment by trjExpensify** [comment] 2022-10-11 13:10
I'm going to tag a few other people that I think are familiar with this flow. 

@MariaHCD @nkuoch @ctkochan22 - is there a technical reason why we can't navigate back to the personal step here, instead of skipping over it and navigating back to the company step?

**Comment by MariaHCD** [comment] 2022-10-11 13:39
I don't think there's a reason why we can't navigate back to the personal step here. We'd already did that for the back button in the header in this PR: https://github.com/Expensify/App/pull/11232

But looks like we missed changing the navigation for the Onfido component: https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/ReimbursementAccount/RequestorStep.js#L189-L192

**Comment by trjExpensify** [comment] 2022-10-11 14:05
Awesome, thanks @MariaHCD!

**Comment by mananjadhav** [comment] 2022-10-13 17:18
Yes @trjExpensify and @stitesExpensify , good with @Uros787's proposal.


🎀 👀 🎀 
C+ reviewed

**Comment by Uros787** [comment] 2022-10-13 17:54
Cool thanks, let me know where I should apply

**Comment by Uros787** [comment] 2022-10-13 18:54
Applied.

**Comment by thesahindia** [comment] 2022-10-13 19:35
Hey, I wanted to know if this is eligible for reporting. I had reported the error part on slack ([thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1664306399540379)) but we decided to do nothing.

**Comment by Uros787** [comment] 2022-10-14 14:17
@mananjadhav @trjExpensify pr created.

**Comment by mananjadhav** [comment] 2022-10-17 12:05
@Uros787 @trjExpensify @stitesExpensify Based on the comment [here](https://github.com/Expensify/App/pull/11842#discussion_r996922476) I feel we should put this on hold until https://github.com/Expensify/App/pull/11719 gets merged.  This is to avoid rework for @Uros787.

Let me know if anyone thinks otherwise.

**Comment by stitesExpensify** [comment] 2022-10-17 15:54
I agree. Updated the title.

**Comment by trjExpensify** [comment] 2022-10-18 15:40
Yep, makes sense. Updated the title to reflect what PR it's held on.

**Comment by stitesExpensify** [comment] 2022-10-21 15:05
The PR this was held on in merged. Removing the hold. @Uros787 based on the changes in that PR do you see your proposal changing at all?

**Comment by mananjadhav** [comment] 2022-10-25 08:08
PR changes are fine, I'll finish the testing by tomorrow.

**Comment by trjExpensify** [comment] 2022-10-31 15:32
The [PR has gone through C+ review,](https://github.com/Expensify/App/pull/11842#issuecomment-1297167109) it's now over to @MariaHCD & @ctkochan22 for review. Actually, @stitesExpensify why aren't you also assigned the PR to review as the CME? 🤔

**Comment by mananjadhav** [comment] 2022-11-02 05:14
PR was merged, but I am not sure about `BugZero Checklist`.  Can you take a look at it @trjExpensify ?

**Comment by trjExpensify** [comment] 2022-11-03 19:55
Sure, that's the new checklist for BugZero to ensure we square all these items away. Obviously, the last three won't happen until we hit +7 days from the production deploy, but I can get going on the suggested regression tests to add to TestRail once we hit staging and it passes QA regression testing. 

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

For this one. IIRC, this wasn't actually a regression, we just implemented it to return to the `Company` step instead of the `Personal` step. Is that right? What about the Onfido error though, do we know what PR caused that one?

**Comment by mvtglobally** [comment] 2022-11-09 03:34
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2022-11-09 11:53
>What about the Onfido error though, do we know what PR caused that one?

Bump on this. If I understand it, we think the `USER_EXITED` error was added to the Onfido SDK later than when we initially implemented it, and therefore we didn't suppress showing it like we did `USER_CANCELLED` and `USER_TAPPED_BACK`. Is that correct?

**Comment by MariaHCD** [comment] 2022-11-09 12:28
> we think the `USER_EXITED` error was added to the Onfido SDK later than when we initially implemented it, and therefore we didn't suppress showing it like we did `USER_CANCELLED` and `USER_TAPPED_BACK`. Is that correct?

That sounds correct to me.

**Comment by mananjadhav** [comment] 2022-11-14 03:54
@trjExpensify This is due for payment

**Comment by trjExpensify** [comment] 2022-11-14 13:48
I've settled up with @Uros787. Sent you an offer to accept for C+, and @thesahindia for reporting.

**Comment by thesahindia** [comment] 2022-11-14 13:54
Accepted, thanks!

**Comment by trjExpensify** [comment] 2022-11-14 13:55
^^ Settled!

**Closed** 2022-11-14 15:13 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
