### ISSUE TITLE
[$500] Web - Notification- Missing info in pushup notification title that it’s from the #Admin Room if create WS in Old

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35661] opened 2024-02-02 13:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new account in New Expensify in the testing device, validate it and stay logged in
3. Navigate to another tab and leave the New Expensify tab in the background
4. In another tab Navigate to OldDot with the same account
5. In Old dot create a Control or Collect policy - this will assign a Guide to the account for policy setup
6. Verify a notification is received in the main testing device from the #Admin Room

## Expected Result:
Notification is received in the main testing device from the #Admin Room with information in the title that it’s from the #Admin Room

## Actual Result:
Notification is received in the main testing device but missing information in the title that it’s from the #Admin Room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a3d05e40-f2d9-45f0-b44e-51044f6b410d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8b05c1c13411ee1</li>
        <li>Upwork Job ID: 1753411155905912832</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2024-02-08 16:26
still waiting on proposals.

**Comment by zanyrenney** [comment] 2024-02-15 19:18
amending to be internal. will seek out the appropriate wave/VIP.

**Comment by mvtglobally** [comment] 2024-02-21 02:29
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment] 2024-02-21 15:54
Also can't reproduce anymore, closing!

**Closed by zanyrenney** 2024-02-21 15:54 UTC
Labels: Daily, Internal, Help Wanted, Overdue, Bug
