### ISSUE TITLE
[$500] Distance IOU - Address field is focused after tapping Cancel on Delete confirmation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28921] opened 2023-10-05 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/28677
## Action Performed:
1. Launch New Expensify app
2. Go to + > Request money > Distance
3. Enter Start and Finish address
4. Tap Add stop and add another address
5. Tap on the newly created Stop > three-dot menu > Delete
6. Tap Cancel

## Expected Result:
The address field is not focused

## Actual Result:
The address field is focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b65eecee-421c-4ea3-a357-50e3901d40f0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efd9ab51a81deed3</li>
        <li>Upwork Job ID: 1711418091040071680</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-05 17:36
cc @0xmiroslav is this worth fixing regarding your autofocus discussion?

**Comment by Beamanator** [comment] 2023-10-06 06:15
Hoping we can fix this at the same time as https://github.com/Expensify/App/issues/27182

Also adding to this main focus tracker issue: https://github.com/Expensify/App/issues/15992

**Comment by chira37** [comment] 2023-10-09 19:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Address field is focused after tapping Cancel on Delete confirmation

### What is the root cause of that problem?
AddressSearch input is not blurring when clicking the three dot menu

### What changes do you think we should make in order to solve the problem?

we can call input blur function when user click on three dot menu
there is prop called **onThreeDotsButtonPress** in **HeaderWithBackButton** component

`onThreeDotsButtonPress={() => textInput.current && textInput.current.blur()}`


https://github.com/Expensify/App/blob/d4b0a245a4f7ab41d67bf718ea078cb7859cb748/src/pages/iou/WaypointEditor.js#L207-L215

## result

Uploading Screen Recording 2023-10-10 at 00.53.05.mov…

**Comment by chira37** [comment] 2023-10-09 19:26
Contributor details
Your Expensify account email: chirancjr@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/chiran

**Comment by abdulrahuman5196** [comment] 2023-10-10 17:37
> Hoping we can fix this at the same time as #27182
> 
> Also adding to this main focus tracker issue: #15992

@Beamanator Can I review the proposals and handle this issue separately or is it expected to be fixed part of the tracking issue?

**Comment by Beamanator** [comment] 2023-10-12 15:03
@abdulrahuman5196 I think this should be fixed either in https://github.com/Expensify/App/issues/27182 or https://github.com/Expensify/App/issues/15992 so I say let's close this one out

**Closed by Beamanator** 2023-10-12 15:03 UTC
Labels: External, Daily, Help Wanted, Bug
