### ISSUE TITLE
[HOLD for payment 2023-09-04] [mWeb Safari] Date is trimmed on small devices when creating manual requetst

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25561] opened 2023-08-21 09:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from https://github.com/Expensify/App/pull/25449#pullrequestreview-1585229938

Device: iPhone SE 3rd gen.

Steps: 
1. Create a manual request
2. Set the date as 2023-08-01

Expected: `2023-08-01` is visible on confirm money request page
Actual: `2023-08-...` is shown on confirm money request page

<img width="149" alt="image" src="https://github.com/Expensify/App/assets/29673073/fbb6d5b8-0dd3-4fbc-b60b-be70f6155778">

https://github.com/Expensify/App/assets/29673073/3312c279-a3e7-40f7-a04f-c8e7b70a6bce

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rushatgabhane 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BeeMargarida** [comment] 2023-08-21 09:45
Hi, I'm Ana from Callstack - expert contributor group - I would like to work on this issue

**Comment by akinwale** [comment] 2023-08-21 09:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Date is trimmed on small devices (e.g. iPhone SE 3rd gen) when requesting money manually.

### What is the root cause of that problem?
flexShrink1 in titleTextStyle is causing the date to get truncated.

### What changes do you think we should make in order to solve the problem?
Change the `flexShrink1` style to `flex1`.

### What alternative solutions did you explore? (Optional)
None.

**Comment by BeeMargarida** [comment] 2023-08-21 10:31
@rushatgabhane @mountiny I can't seem to replicate this, it seems fixed. Can you replicate? (I've used both @mountiny branch and the main branch)


| iPhone SE 3rd generation  | devTools to simulate a Galaxy S5 |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/25725586/b5ad8708-997c-4fed-a34a-6fac2cd6d95e" />  | <video src="https://github.com/Expensify/App/assets/25725586/a8aa03e7-bc5d-4721-bc11-1d5eb30cc61a" /> |

**Comment by akinwale** [comment] 2023-08-21 10:34
@BeeMargarida It's reproducible in the iOS 16.2 simulator.

**Comment by mountiny** [comment] 2023-08-21 10:40
@BeeMargarida Can you test on the PR where @rushatgabhane found it too? Its in the Create money request flow

**Comment by mountiny** [comment] 2023-08-21 10:40
Oh Ok I see you have done that

**Comment by BeeMargarida** [comment] 2023-08-21 10:46
Yap, I checked. I checked now in ios 16.2 simulator, as @akinwale mentioned, I can reproduce.

**Comment by mountiny** [comment] 2023-08-21 10:54
I am curious tho whats the root cause then? Probably dont have to spend much time on this, is the styling change @akinwale suggested enough and wont it introduce other regressions?

**Comment by BeeMargarida** [comment] 2023-08-21 11:05
It might have been changes to WebKit in Safari 16.4. I checked the [changelog](https://webkit.org/blog/13966/webkit-features-in-safari-16-4/), there are some mentions to overflow and flex, but no direct mention to this issue. Found a [similar issue in StackOverflow](https://stackoverflow.com/questions/35012943/text-overflow-hides-text-when-it-shouldnt-in-safari).
I think @akinwale solution works, although I would suggest leaving the `flexShrink1` and instead add `flex1` or `w100` to the `titleTextStyle` in `MenuItem`. It seems like it has no side-effects in other places where `MenuItem` is used.

**Comment by mountiny** [comment] 2023-08-21 13:38
@BeeMargarida would you be able to raise a PR with these changes please?

**Comment by BeeMargarida** [comment] 2023-08-21 13:44
Yap, on it!

**Comment by BeeMargarida** [comment] 2023-08-21 14:13
It's perhaps better to apply the flex on the confirmationList, since it seems like this was previously fixed in some other places like this: https://github.com/Expensify/App/issues/21404. I'll open a PR and we can discuss this there

**Comment by BeeMargarida** [comment] 2023-08-21 14:16
It's perhaps better to apply the flex on the MoneyRequestConfirmationList usage of `MenuItem` since it seems like this was previously fixed in some other places like this: https://github.com/Expensify/App/issues/21404. I'll open a PR and we can discuss this there

**Comment by isabelastisser** [comment] 2023-09-05 19:21
Payment summary:

- Issue reported by @rushatgabhane. $250 (Eligible for Manual Requests)
- @BeeMargarida does not require payment (Contractor)
- @akinwale accepted proposal, $1000, urgency bonus: $500.

@mountiny and @BeeMargarida Please complete the checklist so I can close the issue. Thanks!

**Comment by akinwale** [comment] 2023-09-06 06:30
> Payment summary:
> 
> * Issue reported by @rushatgabhane. $250 (Eligible for Manual Requests)
> * @BeeMargarida does not require payment (Contractor)
> * @akinwale accepted proposal, $1000, urgency bonus: $500.
> 
> @mountiny and @BeeMargarida Please complete the checklist so I can close the issue. Thanks!

I did not submit a PR for this, and while I'm not opposed to the idea, I'm not sure if a bonus would be applicable here.

**Comment by mountiny** [comment] 2023-09-06 08:29
@isabelastisser Lets do the classic 25% of the original price so $250 to @akinwale as his proposal was implemented internally

**Comment by isabelastisser** [comment] 2023-09-06 17:29
Thanks for clarifying, @mountiny and @akinwale! The payment was made in Upwork; all set.

@mountiny and @BeeMargarida, Do you still need to complete the BZ checklist?

**Comment by mountiny** [comment] 2023-09-07 08:32
No I think this is fine it was a new feature

**Comment by isabelastisser** [comment] 2023-09-07 13:27
Thanks, we should be all set!

**Closed by isabelastisser** 2023-09-07 13:27 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-07 15:14
$250 payment approved for @rushatgabhane based on BZ summary.
