### ISSUE TITLE
[HOLD for payment 2024-10-08] [$75] Migrate withWritableReportOrNotFound from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49110] opened 2024-09-12 17:37 UTC
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/pages/iou/request/step/withWritableReportOrNotFound.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834285173135937117</li>
        <li>Upwork Job ID: 1834285173135937117</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103949076</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by abhinaybathina** [comment] 2024-09-12 17:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate from withOnyx HOC to useOnyx hook

### What is the root cause of that problem?
withOnyx HOC is deprecated

### What changes do you think we should make in order to solve the problem?
Whatever props are coming from withOnyx HOC in withWritableReportOrNotFound should be replaced with useOnyx hook

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment] 2024-09-13 05:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Migrate withWritableReportOrNotFound from withOnyx to useOnyx

### What is the root cause of that problem?

Migration

### What changes do you think we should make in order to solve the problem?


In [`withWritableReportOrNotFound`](https://github.com/Expensify/App/blob/04762acb53f446708d6f649cbb6b527abbf72889/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L92-L101), we should migrate the code below and use `useOnyx` for `report`, `isLoadingApp`, `reportDraft`.

https://github.com/Expensify/App/blob/04762acb53f446708d6f649cbb6b527abbf72889/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L92-L101

**Comment by brunovjk** [comment] 2024-09-13 12:11
Reviewing proposals today

**Comment by roryabraham** [comment] 2024-09-13 16:27
going to treat these migrations on a first-come-first-serve basis while avoiding assigning the same person to multiple

**Comment by abhinaybathina** [comment] 2024-09-13 18:11
Hi team, thanks for assigning this to me. I've checked upwork but I didn't receive any job offer. Can you please look into it? @roryabraham . Thanks!

**Comment by abhinaybathina** [comment] 2024-09-14 02:27
Sorry never mind, I've applied to the Upwork job. Please expect the PR to be ready for review by today EOD. Thanks!

**Comment by abhinaybathina** [comment] 2024-09-14 06:14
Here is the PR, please review. Thanks!

https://github.com/Expensify/App/pull/49200

**Comment by brunovjk** [comment] 2024-09-14 09:41
> going to treat these migrations on a first-come-first-serve basis while avoiding assigning the same person to multiple

Thank you @roryabraham and @abhinaybathina. I will review the PR first thing on Monday.

**Comment by abhinaybathina** [comment] 2024-09-26 16:38
Hi @roryabraham. Thanks for reviewing the PR and merging it. I've applied for this Upwork job but there is no update on Upwork. Can you please check?

**Comment by roryabraham** [comment] 2024-09-29 01:03
@abhinaybathina @garrettmknight will help handle the payment on Upwork. Thanks. As stated in our [contributing guidelines](https://github.com/Expensify/App/blob/c5aa39c331188db1e3a70f5b5bcccd15c5df9ed6/contributingGuides/CONTRIBUTING.md), jobs are typically paid out after the code has been on production for a week without causing regressions.

[This PR](https://github.com/Expensify/App/pull/49200) was deployed to staging yesterday.

**Comment by brunovjk** [comment] 2024-09-30 19:07
PR on [staging](https://github.com/Expensify/App/issues/49855)

**Comment by abhinaybathina** [comment] 2024-09-30 20:04
I have tested on staging, working fine

**Comment by garrettmknight** [comment] 2024-10-01 11:59
**Payment Summary:**
- @abhinaybathina $250
- @brunovjk $250

**Comment by garrettmknight** [comment] 2024-10-01 12:01
@abhinaybathina please accept the offer.

**Comment by abhinaybathina** [comment] 2024-10-01 12:03
@garrettmknight Accepted

**Comment by brunovjk** [comment] 2024-10-01 12:07
I will complete the BZ checklist before payday. Thanks.

**Comment by brunovjk** [comment] 2024-10-07 13:41
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: No PR introduce the issue, since is a migration from `withOnyx` to `useOnyx`.
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
* [x]  [@brunovjk] Determine if we should create a regression test for this bug: **No**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by garrettmknight** [comment] 2024-10-08 18:45
Paid out!

**Closed by garrettmknight** 2024-10-08 18:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
