### ISSUE TITLE
[$1000] Web - Task name and description  isn't saved while changing from Second User

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21579] opened 2023-06-26 15:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On user A
2. Go to '+" -> create group -> add user B
3. Now, on the group page go to assign task
4. Type name -> next and confirm, ( leave share somewhere to default)
5. Now on user B, go to that created group page -> go to task page
6. Try to edit task name and description,
7. Notice that the edit isn't saved.

## Expected Result:
If task name and description details are to be edited from other users too, changes must be saved.

## Actual Result:
Task name and description  isn't saved while changing from Second User

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/29239dcf-2ff3-4947-885d-b607ee147d16

https://github.com/Expensify/App/assets/93399543/b957a43c-cf30-4f62-9e8d-f33a124a4e70

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687430614337549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d7ba771488256e5</li>
        <li>Upwork Job ID: 1674187408510738432</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-06-26 16:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task name and description  isn't saved while changing from Second User

### What is the root cause of that problem?
We are getting error from backend if we are trying to change the name or description. if we are just the member of that group in which the task is created - 
![image](https://github.com/Expensify/App/assets/27822551/87dc2bf5-7a85-4c86-b693-6f01ec8d7349)
That's why this issue is happening.

### What changes do you think we should make in order to solve the problem?
- We shall disable the description button or task name item if the current user has permission to change the given field
`MenuItemWithTopDescription` takes `disabled` prop, that can be set as `true` or `false` based on the current user's permission.
- Also we shall display the error message that is being provided by the backend on the screen
We can add the error in `failureData` here - 
https://github.com/Expensify/App/blob/9bef5074ae858e7efb0d757473409ef099dac309/src/libs/actions/Task.js#L383-L387

### What alternative solutions did you explore? (Optional)
None

**Comment by alexpensify** [comment] 2023-06-28 22:47
Labeling as `external` I confirmed that if you edit as the Second User from a web browser like Chrome, this edit does not save. Now, if you edit in the desktop app then it saves.

**Comment by alexpensify** [comment] 2023-06-28 22:48
Out the gate, @fedirjh it looks like we have a proposal. Can you review it when you get a chance? Thank you!

**Comment by BhuvaneshPatil** [comment] 2023-06-29 08:42
Hi @fedirjh - there can be a design doc or something that describes who have permission to edit which field of task. Based on that we can check those permission with current user.
example - If only creator of task has permission to edit the description - we can add check for that.
Because the report provides us with that field - `ownerAccountID`
![image](https://github.com/Expensify/App/assets/27822551/2f306182-88c9-46a0-883c-79ca95acab88)

Once we understand the permission levels we can add extra checks from data we have.

**Comment by thienlnam** [comment] 2023-06-29 20:19
<img width="655" alt="Screenshot 2023-06-29 at 1 19 00 PM" src="https://github.com/Expensify/App/assets/30609178/11695861-8e23-4dc1-9722-4ee941f25e43">

**Comment by thienlnam** [comment] 2023-06-29 20:19
We just need to better handle the error when a you don't have access to take an action - it should show an error on the reportAction that comes from 'Completing a task'

**Comment by alexpensify** [comment] 2023-06-29 22:19
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back then if it's not closed by then. 

Required action from the 🐛 team: Make sure we are making progress and moving forward

**Comment by joekaufmanexpensify** [comment] 2023-06-30 17:36
@thienlnam I saw you assigned this one. Are you planning to fix internally, or should we leave help wanted?

**Comment by thienlnam** [comment] 2023-06-30 17:47
Just assigned to keep better visibility over it, let's keep help wanted for right now

**Comment by thienlnam** [comment] 2023-06-30 17:55
We should display the error returned from the backend. When you complete / re-open a task, it attempts to create an optimistic reportAction that says '___ completed task: task'. Since the reportAction doesn't actually get created successfully (because the command failed), we'll need to create a new generic error on the front end and add it to the failure data on the reportAction.

**Comment by BhuvaneshPatil** [comment] 2023-06-30 18:38
@fedirjh I am afk now. Will do first thing in the morning.

**Comment by BhuvaneshPatil** [comment] 2023-07-01 11:15
@fedirjh Updated the proposal above

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:09
Not overdue, pending review of proposals.

**Comment by abdulrahuman5196** [comment] 2023-07-04 15:40
If the root cause here is that non-authorized users are changing the name and description. It will be fixed part of this - https://github.com/Expensify/App/issues/21580#issuecomment-1614907480

**Comment by abdulrahuman5196** [comment] 2023-07-04 16:20
@fedirjh 

>It looks the same issue but split into 2 parts

Yes. We should merge the issues.

>my understanding is that we should only improve errors handling , which means that we shouldn’t disable the actions

I am not sure on this. Why should we allow user to change when they don't have permission and it will ultimately result in exception.

> I think the limitation that we don't have permissions utils to check if user has a permission or not, and the selected proposal doesn’t answer how they will plan to implement the permission ?

We have a utils function to check if the user is a assignee or creator, I think only the policy admins check needs to be added. But I think it should be possible since we know the parent report and check on its policy permission. But that is a good question,  I will ask the same in that issue.

**Comment by joekaufmanexpensify** [comment] 2023-07-05 18:26
@abdulrahuman5196 it sounds like it may make sense to close this issue (and merge it into the one referenced above). Is that right?

**Comment by thienlnam** [comment] 2023-07-05 18:34
The user shouldn't be required to go online to edit the task. We handle it optimistically, and then handle the error when it fails.

Though there have actually been some discussions about changing the access paradigm of tasks so we may allow anyone that has access to view the task modify it

**Comment by abdulrahuman5196** [comment] 2023-07-05 18:39
@thienlnam 
>Though there have actually been some discussions about changing the access paradigm of tasks so we may allow anyone that has access to view the task modify it

If this comes true, both of the bugs become invalid. let us know if this is the path.


But as of current questions
>The user shouldn't be required to go online to edit the task. We handle it optimistically, and then handle the error when it fails.

I agree on this. But `Why should we allow user to change when they don't have permission and it will ultimately result in exception?`, It is like we are intentionally allowing the user modify something which is expected to not work for them.

For similar case for room rename , we disable room rename for non-allowed user.

So, I propose to disable inputs with the current available information, and also handle errors optimistically if the permission changes happen offline.

**Comment by abdulrahuman5196** [comment] 2023-07-05 18:42
> @abdulrahuman5196 it sounds like it may make sense to close this issue (and merge it into the one referenced above). Is that right?

I think so. If its fine with @fedirjh 

Ultimately both should be solved by a common solution.

**Comment by thienlnam** [comment] 2023-07-05 18:43
> So, I propose to disable inputs with the current available information, and also handle errors optimistically if the permission changes happen offline.

This is what I'm also proposing here. When we have the available information of a user not being able to modify something we can block the input, but when we don't such as in the case they are offline and haven't received pusher updates then we handle the failure

**Comment by thienlnam** [comment] 2023-07-05 18:43
Though, it is looking like we are going to update this so let's put these issues on hold

**Comment by joekaufmanexpensify** [comment] 2023-07-10 14:01
On hold

**Comment by alexpensify** [comment] 2023-07-10 20:59
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

On hold

**Comment by alexpensify** [comment] 2023-07-17 20:02
Still on hold

**Comment by alexpensify** [comment] 2023-07-22 00:27
Weekly Update: On hold

**Comment by alexpensify** [comment] 2023-07-25 20:50
Weekly update: On hold

**Comment by alexpensify** [comment] 2023-08-01 21:25
Weekly Update: On hold

**Comment by alexpensify** [comment] 2023-08-08 23:02
Weekly update: On hold

**Comment by alexpensify** [comment] 2023-08-16 23:36
@thienlnam looks like the other PRs are live now. Can we take this one off hold?

**Comment by thienlnam** [comment] 2023-08-17 15:58
Yup - let's see if this is still a bug

**Comment by BhuvaneshPatil** [comment] 2023-08-17 16:37
Not reproducible

**Comment by alexpensify** [comment] 2023-08-23 17:51
Thanks, based on this news, I'm going to close this GH since it was fixed in #296932

**Closed by alexpensify** 2023-08-23 17:51 UTC
Labels: External, Weekly, Help Wanted, Bug
