### ISSUE TITLE
 IOU - Save button is not above keyboard when waypoint input is in focus

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42758] opened 2024-05-29 12:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/42464
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Recent destinations list has a few addresses
1. Go to staging.new.expensify.com
2. Go offline
3. Go to FAB > Submit expense > Distance
4. Tap Start
5. Tap on the input
6. Note that Save button does not appear above the keyboard
7. Tap system back button (or swipe) to dismiss the keyboard while the input is still in focus

## Expected Result:
In Step 5, Save button will appear above the keyboard (production behavior)
In Step 7, Save button will appear at the bottom when keyboard is dismissed and input is still in focused

## Actual Result:
In Step 5, Save button does not appear above the keyboard (production behavior)
In Step 7, Save button is missing at the bottom when keyboard is dismissed and input is still in focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/102574c5-553c-4820-8c1f-2f67d156bf93

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-29 12:17
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-29 12:17
We think that this bug might be related to #wave-collect - Release 1

**Comment by arosiclair** [comment] 2024-05-29 14:04
The `Start` and `Stop` inputs don't work at all for me 🤨 

https://github.com/Expensify/App/assets/6833644/380c3a8d-ded3-4383-9dad-f71d3cb7c701

Same thing online or offline.

**Comment by trjExpensify** [comment] 2024-05-29 14:30
Yeah, I've got an infinite spinner after entering the waypoints when online. 

![IMG_0127](https://github.com/Expensify/App/assets/16232057/086cd641-0648-4fb3-a48e-dea4fb4cf15c)

**Comment by trjExpensify** [comment] 2024-05-29 14:33
^^ looks like that might be similar to another deploy blocker reported [here](https://github.com/Expensify/App/issues/42752) and potentially related to [this PR](https://github.com/Expensify/App/pull/42509).

**Comment by arosiclair** [comment] 2024-05-29 16:03
Alright this is caused by https://github.com/Expensify/App/pull/35045. Reverting fixes the issue:

https://github.com/Expensify/App/assets/6833644/1b4036c4-1822-4f64-a99a-43c7963bfe94

**Comment by arosiclair** [comment] 2024-05-29 16:57
> @arosiclair Looks like the submit button is being hidden intentionally.

That's definitely not true. We always show submit buttons above the keyboard.

**Comment by arosiclair** [comment] 2024-05-29 20:12
Revert was merged and CP'd so this is all set

**Closed by arosiclair** 2024-05-29 20:12 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
