### ISSUE TITLE
[HOLD #227234] Receiving Notifications from chats sent months ago

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13140] opened 2022-11-29 17:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat with Gabi
2. Start chatting

## Expected Result:
Notifications received would be from our chats happening now

## Actual Result:
Received notifications from chats received months ago. When I look at those chats they also show “Invalid Date”

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.30-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="288" alt="Screenshot 2022-11-29 at 5 21 54 PM" src="https://user-images.githubusercontent.com/43996225/204600642-af4fd17a-d2d2-46eb-a67e-daf5f394df99.png">
<img width="287" alt="Screenshot 2022-11-28 at 4 41 38 PM" src="https://user-images.githubusercontent.com/43996225/204600643-69b86193-8a6c-4ec3-a973-ba23b5f4715a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669654070339909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2022-11-30 10:02
Updated to v1.2.33-7, 'invalid date' persists:
<img width="276" alt="Screenshot 2022-11-30 at 10 01 29 AM" src="https://user-images.githubusercontent.com/1529980/204766714-d8d547af-0e17-46a3-ade4-841b745dd016.png">

**Comment by dylanexpensify** [comment] 2022-11-30 11:14
working on reproducing now

**Comment by dylanexpensify** [comment] 2022-11-30 11:15
@garrettmknight is this only with your chat with Gabi?

**Comment by garrettmknight** [comment] 2022-11-30 15:56
There's another chat with her that has the 'Invalid Date' text on the same day, but no others.

**Comment by garrettmknight** [comment] 2022-11-30 20:51
Happened to @RobertLadue as well:
<img width="281" alt="Screenshot 2022-11-30 at 8 51 33 PM" src="https://user-images.githubusercontent.com/1529980/204905444-d4fb8bba-2993-417c-8616-00bce7a2aa0f.png">

**Comment by marcaaron** [comment] 2022-12-01 04:33
possible theory - something in the API layer changed and is sending an invalid `action.created`

We render the date here -> 

https://github.com/Expensify/App/blob/820e876d5e4a8cbffe272220c1182c8942ed93cf/src/pages/home/report/ReportActionItemDate.js#L15-L19

So like the UI says it is _probably_ invalid...

Seeing the browser notifications makes sense too since we use the `created` field to determine whether to show a notification. The `created` being invalid means the front end interprets it as "new"

https://github.com/Expensify/App/blob/820e876d5e4a8cbffe272220c1182c8942ed93cf/src/libs/actions/Report.js#L1330-L1331

IMO this is in part of a consequence of [this issue](https://github.com/Expensify/Expensify/issues/228194) (needs a better general design) and in part due to some API change that we haven't connected to this bug yet (which seems more urgent to solve).

**Comment by dylanexpensify** [comment] 2022-12-02 14:13
Ah very interesting @marcaaron. Should we put this on hold then while we work on the linked issue? Or can we work on this externally in the meantime?

**Comment by marcaaron** [comment] 2022-12-02 20:21
I don't think it should be on HOLD, no. It seems like an API change has triggered this and we should make this `Internal` so someone on the team can prioritize it.

**Comment by dylanexpensify** [comment] 2022-12-05 09:48
Sounds good! Thanks!

**Comment by arosiclair** [comment] 2022-12-06 01:28
I'll take a stab at tracing where this API issue could be coming from

**Comment by dylanexpensify** [comment] 2022-12-07 11:43
Amazing, thanks @arosiclair !

**Comment by dylanexpensify** [comment] 2022-12-09 19:50
@arosiclair any update here?

**Comment by arosiclair** [comment] 2022-12-11 18:46
Not sure where this could be coming from but here's what I've found so far.

Several months ago we started using timestamps with millisecond precision in [this PR](https://github.com/Expensify/Auth/pull/7002). At the time we weren't depending on the `created` timestamp very much. This was deployed on Aug 29th.

A couple weeks ago we changed logic on how we generate and use `created` timestamps in NewDot  in [this PR](https://github.com/Expensify/App/pull/12540). These changes were deployed in **v1.2.30** which matches the affected versions in the OP. 

If these were breaking changes, I'd think old messages sent before the above deploys would have this Invalid Date issue but that isn't the case for me. I've also tried trimming off the millisecond portion of the `created` string to reproduce Invalid Dates in dev but that didn't cause any issues.

@luacmartins @roryabraham @tylerkaraszewski Any ideas if they (or anything else) might be the source of this issue?

It might also be worth running a CQ to find what the `created` timestamps on these report actions actually look like in the DB.

**Comment by dylanexpensify** [comment] 2022-12-15 11:38
bump @lucas-neuhaus-dev @roryabraham @tylerkaraszewski ?

**Comment by roryabraham** [comment] 2022-12-17 07:49
> It might also be worth running a CQ to find what the created timestamps on these report actions actually look like in the DB.

We could also just grab the data from Onyx

**Comment by dylanexpensify** [comment] 2022-12-19 09:33
@arosiclair any updates by chance?

**Comment by luacmartins** [comment] 2022-12-19 20:27
Sorry I completely missed the ping here. It seems like the PRs Andrew linked are probably the cause. I agree that we could run a CQ to get the created dates for those reports to see how we are storing the date and then fix it.

**Comment by joekaufmanexpensify** [comment] 2022-12-19 20:38
I know I did experience this issue at some point in the past, but I don't remember which report, and didn't record it. Sorry! For me, signing out and back in resolved the issue at the time.

**Comment by arosiclair** [comment] 2022-12-26 17:02
No real updates atm. Signing out and back in resolving the issue suggests that Onyx might have had an invalid `created` value cached and the API was only able to replace it with a valid one after signing out and clearing Onyx. 

Bumping @garrettmknight @RobertLadue for those report IDs

**Comment by JmillsExpensify** [comment] 2022-12-27 16:04
A couple of things: 

 - Given the relation to sequence numbers PRs, I'm going to proactively add a HOLD on that project and simultaneously take this issue over (I'm the BZ person assigned and responsible for SQN bugs). 
 
 - Let's still have @garrettmknight and @RobertLadue share their reportIDs when they are both back from vacay. 

 - Even then, given that signing in and out resolves the issue, that indicates that this is temporary, so I could equally see the argument that we should close this for focus. Leaving that up to @arosiclair.

**Comment by arosiclair** [comment] 2022-12-27 17:18
Yeah let's just close this out for now as this may never come up again after sequence numbers is finished. If it does, we can just reopen and take another look.

**Closed by arosiclair** 2022-12-27 17:18 UTC
Labels: Daily, Internal, Needs Reproduction, Bug
