### ISSUE TITLE
[$250] Web - Tags - 3-dot menu in tag RHP animation stutters

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42908] opened 2024-05-31 10:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Tags.
4. Click on any tag.
5. Click 3-dot menu.

## Expected Result:
3-dot menu will animate smoothly (production behavior).

## Actual Result:
3-dot menu animation slightly stutters. It seems to animate The menu seems to appear in two sizes when animating - small size first then regular size.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/95e8e2ba-d36c-403b-99f3-c66b41a84809

<img width="958" alt="Bug6497080_1717138403645!Screenshot_2024-05-31_at_14 53 04" src="https://github.com/Expensify/App/assets/115492554/f6480ef5-3c13-4425-8ff4-d1566991be07">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124d96a65b48fcae1</li>
        <li>Upwork Job ID: 1796501094393847808</li>
        <li>Last Price Increase: 2024-05-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by izarutskaya** [comment] 2024-05-31 10:16
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-31 10:17
We think this issue might be related to the #collect project.

**Comment by Beamanator** [comment] 2024-05-31 11:17
I don't think this is a big enough problem to be a blocker so demoted it

**Comment by ikevin127** [comment] 2024-05-31 20:50
Coming from https://github.com/Expensify/App/issues/42911, looks like the offending PR was identified as https://github.com/Expensify/App/pull/36292, hence both issues have the same root cause and the solution from there should fix this issue as well since the issue comes from the same component.

Therefore I'd suggest having this put on **Hold for https://github.com/Expensify/App/issues/42911**.

**Comment by ikevin127** [comment] 2024-06-06 18:33
The issue is not reproducible anymore since it was fixed in https://github.com/Expensify/App/issues/42911 by PR https://github.com/Expensify/App/pull/43013, therefore I suggest closing as fixed.
cc @Beamanator @kevinksullivan

**Comment by Beamanator** [comment] 2024-06-07 08:24
Thanks so much for keeping track of that, I agree let's close this out 🚀

**Closed by Beamanator** 2024-06-07 08:24 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
