### ISSUE TITLE
[$2000] Web- URL previews disappears on switching chats

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21187] opened 2023-06-21 11:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chats
2. Send links
3. Switch between chats

## Expected Result:
It should show URL previews

## Actual Result:
Some previews will hide on switching chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/21eb3c64-64a2-457f-816a-dc8b217c30a7

https://github.com/Expensify/App/assets/93399543/d1746a8d-a8cc-4918-8ad8-4cf2d2e848d6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686726398290419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c4b1a0420cda3e5</li>
        <li>Upwork Job ID: 1673307522098319360</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-06-26 12:29
So my issue is that in some cases, the links just don't appear at all, which is related. 

![2023-06-26_07-22-37 (1)](https://github.com/Expensify/App/assets/10926327/b16c8a3f-3f15-45e8-b264-2fc564006703)

Going to get some eyes on this 👍

**Comment by ygshbht** [comment] 2023-06-26 23:37
I too am unbale to see the previews at all. Could the whole issue be rather in react-native-render-html library?

`src/components/RenderHTML.js
`
```
import React from 'react';
import PropTypes from 'prop-types';
import {RenderHTMLSource} from 'react-native-render-html';
import useWindowDimensions from '../hooks/useWindowDimensions';

const propTypes = {
    /** HTML string to render */
    html: PropTypes.string.isRequired,
};

// We are using the explicit composite architecture for performance gains.
// Configuration for RenderHTML is handled in a top-level component providing
// context to RenderHTMLSource components. See https://git.io/JRcZb
// The provider is available at src/components/HTMLEngineProvider/
function RenderHTML(props) {
    const {windowWidth} = useWindowDimensions();
    return (
        <RenderHTMLSource
            contentWidth={windowWidth * 0.8}
            source={{html: props.html}}
        />
    );
}

RenderHTML.displayName = 'RenderHTML';
RenderHTML.propTypes = propTypes;
RenderHTML.defaultProps = {};

export default RenderHTML;

```

**Comment by mollfpr** [comment] 2023-06-27 15:59
> Could the whole issue be rather in react-native-render-html library?

It might be. We also could push a fix upstream if we had a solution for that.

**Comment by CortneyOfstad** [comment] 2023-06-30 14:05
Just checking to see where we are at with this. Thanks!

**Comment by CortneyOfstad** [comment] 2023-06-30 19:37
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by mollfpr** [comment] 2023-07-03 15:14
No proposals

**Comment by adelekennedy** [comment] 2023-07-05 20:22
doubling

**Comment by kashn11** [comment] 2023-07-05 22:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
while sending link in chat url preview didn't show 
### What is the root cause of that problem?
To get url preview we are calling `ExpandURLPreview` that is not return data.
[Here](https://github.com/Expensify/App/blob/cb7988c50ad048a40a62d7139b0ea44e186d6695/src/pages/home/report/ReportActionItem.js#L146-L147) is the link where api is calling and didn't get data on this component `     <LinkPreviewer linkMetadata={_.filter(props.action.linkMetadata, (item) => !_.isEmpty(item))} />`

### What changes do you think we should make in order to solve the problem?
just to verify api return metadata of url 

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-07-06 09:13
`ExpandURLPreview` API doesn't return link metadata. This is the root cause.
I'm not sure why `addComment` API doesn't return metadata. Should we need `ExpandURLPreview` API?

**Comment by mollfpr** [comment] 2023-07-10 14:07
I couldn't get the preview at all in DEV and staging. Is anyone having the same?

**Comment by mollfpr** [comment] 2023-07-13 16:01
It's working fine for me on DEV with staging API.

https://github.com/Expensify/App/assets/25520267/5294e369-5894-4ce6-90e9-6d5aab303bdf

**Comment by adelekennedy** [comment] 2023-07-13 18:12
It's working for me on staging chrome, on desktop prod I'm not seeing previews at all

**Comment by adelekennedy** [comment] 2023-07-17 20:10
coming back to this @mollfpr previews now work for me on prod desktop - I think this has already been fixed by something else. Since no one was assigned I think @gadhiyamanan is due the reporting bonus and some comp for you for reviewing proposals. Thoughts?

**Comment by adelekennedy** [comment] 2023-07-17 20:36
@gadhiyamanan will you apply [here](https://www.upwork.com/jobs/~015c4b1a0420cda3e5) for the reporting bonus? @mananjadhav I believe you're on the list for new dot payments - I think you're due 25% for reviewing proposals

**Comment by mananjadhav** [comment] 2023-07-17 20:44
@adelekennedy Not me. I think you meant @mollfpr.

**Comment by gadhiyamanan** [comment] 2023-07-18 02:19
@adelekennedy applied, thanks!

**Comment by mollfpr** [comment] 2023-07-18 02:36
>coming back to this @mollfpr previews now work for me on prod desktop - I think this has already been fixed by something else. Since no one was assigned I think @gadhiyamanan is due the reporting bonus and some comp for you for reviewing proposals. Thoughts?

👍

**Comment by marcaaron** [comment] 2023-07-19 18:05
Sorry, I think this is happening because we were hitting the rate limit? I don't think this is something that actually needs someone to look into.

**Closed by marcaaron** 2023-07-19 18:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
