### ISSUE TITLE
Web - Closing App download links page in settings page is causing incorrect URL settings/about instead of r/reportId - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11350] opened 2022-09-27 18:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in web app.
2. Open settings page > profile > click add phone number
3. Click on back arrow on this page to navigate to profile page.
4. Click on back arrow to navigate to settings page.
5. Click on about > app download links.
6. Click on cross (x) to close app download links page.

## Expected Result:
URL should be r/reportId.

## Actual Result:
URL is settings/about

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.5-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192607859-6d5828dd-70cc-407f-84a5-d9bf28a4dfbe.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662818840728789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aneequeahmad** [comment] 2022-09-27 20:52
@mallenexpensify, I think this should be added to https://github.com/Expensify/App/issues/11111  as per @parasharrajat comment. Thanks

**Comment by mallenexpensify** [comment] 2022-09-27 22:05
Thanks @aneequeahmad .  @jasperhuangg , since you created lucky issue #11111 , do you agree?  if so... wanna add to that then update this issue, inc. adding `[HOLD #11111]` to the beginning of the title?

**Comment by mallenexpensify** [comment] 2022-10-04 17:45
@jasperhuangg , do you  think this should be added to https://github.com/Expensify/App/issues/11111?

**Comment by jasperhuangg** [comment] 2022-10-04 17:46
@mallenexpensify good call, this is exactly the same issue as described in #11111

**Comment by mallenexpensify** [comment] 2022-10-04 23:37
Thanks @jasperhuangg , I updated the OP for https://github.com/Expensify/App/issues/11111  @jasperhuangg should I put this on hold dependent on https://github.com/Expensify/App/issues/11111 ?

**Comment by mallenexpensify** [comment] 2022-10-10 16:41
Unable to reproduce and seems like a low-value edge case.  Closing, comment if anyone disagrees

**Comment by JmillsExpensify** [comment] 2023-06-26 20:36
Re-opening this issue now that we're done with the react navigation refactor.

**Comment by JmillsExpensify** [comment] 2023-06-26 20:43
Here's my summary:

 - We've deprecated the close button, so that's not longer a relevant part of the testing steps
 - Further, when I following the remaining testing steps, the URL is correct in each case. 
 
Accordingly, I think we're good to go here and we'll pay out @aneequeahmad $250 for reporting.

**Comment by mallenexpensify** [comment] 2023-06-30 00:41
@aneequeahmad, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0194114032474252c5

**Comment by aneequeahmad** [comment] 2023-07-04 04:48
@mallenexpensify I accepted the offer thankyou

**Comment by JmillsExpensify** [comment] 2023-07-05 12:40
Sent the offer via the link Matt provided above.

**Comment by mallenexpensify** [comment] 2023-07-11 04:55
@aneequeahmad paid!  Closing

**Closed by mallenexpensify** 2023-07-11 04:55 UTC
Labels: Daily, Overdue
