### ISSUE TITLE
[$500] [Distance] - mWeb - Focus is missing on the input  Distance.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27202] opened 2023-09-11 21:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click plus sign
2. Select Request money
3. Click Distance, click Start & End and select a location
4. Click Next button

## Expected Result:
Should focus on the input Distance.

## Actual Result:
The focus appears and disappears instantly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c211a356-d533-4667-ab1b-9e826ad55794

https://github.com/Expensify/App/assets/93399543/271dcdea-efb2-4708-9702-5294669c009f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694186307956829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018884aaf0dffcfd73</li>
        <li>Upwork Job ID: 1701343243554549760</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26637305</li>
<li>Mauri-salazar | Reporter | 26637307</li>
</ul></li>
    </ul>
</details>

**Comment by papergliff** [comment] 2023-09-11 21:47
Proposal

Please re-state the problem that we are trying to solve in this issue.

[Distance] - Focus is not setting when input distance appears

What is the root cause of that problem?

There is no focus setting within the MoneyRequestParticipantsSelector component, that is responsible for choosing the user 

What changes do you think we should make in order to solve the problem?

basically add focus to componentDidUpdate hook:
```js
if (this.optionsSelectorRef.current && this.optionsSelectorRef.current.focus) {
          this.optionsSelectorRef.current.focus();
}
```

and create reference in the MoneyRequestParticipantsSelector component itself, for it to pass to the OptionsSelector Component

**Comment by papergliff** [comment] 2023-09-11 21:51
Contributor details
Your Expensify account email: nixkid16@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013fd4f74b41c52e11

**Comment by akinwale** [comment] 2023-09-11 23:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The input when trying to select a Workspace during the Distance Request flow does not automatically gain focus.

### What is the root cause of that problem?
This seems to be intentional. However, if that's not the case, the MoneyRequestParticipantsPage component makes use of an OptionSelector, and we're not passing the `autoFocus` prop to this. Since `autoFocus` will be false in this case, the text input does not get automatically focused.

### What changes do you think we should make in order to solve the problem?
1. Add the `autoFocus` and `shouldDelayFocus` props to the MoneyRequestParticipantsPage, along with the corresponding prop types.

2. Pass these props on to the `OptionsSelector` in the component.
```diff
<OptionsSelector
  ...
+  autoFocus={this.props.autoFocus}
+  shouldDelayFocus={this.props.shouldDelayFocus}
/>

### What alternative solutions did you explore? (Optional)
None.

**Comment by rizalalfandi123** [comment] 2023-09-12 03:45
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
The input when trying to select a Workspace during the Distance Request flow does not autofocus.

### What is the root cause of that problem ?
in the [MoneyRequestParticipantsSelector.js](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) file, loads the OptionsSelector component as input. On the other hand, the OptionsSelector component already has an autoFocus prop ready to use, but the [MoneyRequestParticipantsSelector.js](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) does not implement the autoFocus props.

### What changes do you think we should make in order to solve the problem ?
only adds the autoFocus and shouldDelayFocus props to the OptionsSelector component in [MoneyRequestParticipantsSelector.js](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) rather than passing the props to the parent component.

`<OptionsSelector ... autoFocus shouldDelayFocus />`

[Screencast from 2023-09-12 10-42-52.webm](https://github.com/Expensify/App/assets/90819361/e1b15def-8d06-4d39-9765-46b142be06af)

### What alternative solutions did you explore? (Optional)
none

**Comment by narefyev91** [comment] 2023-09-12 06:56
Proposal from @tienifr looks good to me - in case we should use standard approach inside project for focusing inputs with onEntryTransitionEnd https://github.com/Expensify/App/issues/27202#issuecomment-1714937852
🎀 👀 🎀 C+ reviewed

**Comment by Mauri-salazar** [comment] 2023-09-12 18:55
I was paid 50 USD for this mistake, is this correct?

**Comment by Mauri-salazar** [comment] 2023-09-12 20:30
Excuse me, when an error is valued at 500 USD, would the payment for the reporter be 50 USD and not 250 USD?

**Comment by amyevans** [comment] 2023-09-12 20:34
@Mauri-salazar yes, $50 is correct. Check out [this announcement in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649) and let us know if you have any additional questions

**Comment by dylanexpensify** [comment] 2023-09-13 13:07
Same as prior issue - distance related!

**Comment by gadhiyamanan** [comment] 2023-09-18 04:34
This is dupe of https://github.com/Expensify/App/issues/24314 and that issue is eligible for reporting bonus because it was reported first

**Comment by amyevans** [comment] 2023-09-18 04:54
Hmm @dylanexpensify I think you should still be assigned here as BZ, right? (and not @neil-marcellini)

**Comment by luacmartins** [comment] 2023-09-18 07:27
FYI this issue was a dupe of https://github.com/Expensify/App/issues/24314. Since https://github.com/Expensify/App/issues/24314 was reported first, we should pay the reporting bonus to @gadhiyamanan.

**Comment by neil-marcellini** [comment] 2023-09-21 02:53
> Hmm @dylanexpensify I think you should still be assigned here as BZ, right? (and not @neil-marcellini)

Yes I think BZ is all that remains to be done here.

**Comment by amyevans** [comment] 2023-09-25 12:51
@dylanexpensify can you handle payments please? 🙏

**Comment by dylanexpensify** [comment] 2023-09-25 16:32
on it @amyevans!

**Comment by dylanexpensify** [comment] 2023-09-25 16:34
Payment summary:
- Reporter: @gadhiyamanan $50
- Contributor: @tienifr $750
- Contributor+: @narefyev91 $750

**Comment by gadhiyamanan** [comment] 2023-09-25 16:37
@dylanexpensify it is eligible for $250 reporting bonus because it was [reported](https://github.com/Expensify/App/issues/24314) before 30 August

**Comment by dylanexpensify** [comment] 2023-09-25 16:47
ah yep - updating! nice catch

**Comment by dylanexpensify** [comment] 2023-09-25 16:47
@narefyev91 @gadhiyamanan please apply [here](https://www.upwork.com/jobs/~018884aaf0dffcfd73)!

**Comment by narefyev91** [comment] 2023-09-25 16:49
> @narefyev91 @gadhiyamanan please apply [here](https://www.upwork.com/jobs/~018884aaf0dffcfd73)!

Hey @dylanexpensify - I'm from Callstack - no need any payment from Upwork :-)

**Comment by gadhiyamanan** [comment] 2023-09-25 16:49
@dylanexpensify applied, thanks!

**Comment by dylanexpensify** [comment] 2023-09-25 17:53
done!

**Closed by dylanexpensify** 2023-09-25 17:53 UTC
Labels: External, Daily, Bug
