### ISSUE TITLE
[$500] Android - Login - Custom avatars show placeholder avatar when app is relaunched offline after login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31365] opened 2023-11-15 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Log in to HT account that has a custom avatar and chats with users that have custom avatar.
3. After the app is loaded, close the app from the background.
4. Go offline.
5. Relaunch app.

## Expected Result:
The custom avatars that are rendered successfully after login should not have a placeholder avatar when app is killed and relaunched in offline mode.

## Actual Result:
The custom avatars that are rendered successfully after login have a placeholder avatar when app is killed and relaunched in offline mode.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4272e1c7-d0b7-43ce-a43f-39edea349dac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8e10986aac01237</li>
        <li>Upwork Job ID: 1724779711333421056</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by samilabud** [comment] 2023-11-15 14:41
As far as I can see this seems to be the expected behavior, when the user gets back to online mode the image/avatar should be loaded like this:

https://github.com/Expensify/App/assets/5216036/410c8124-6842-4dcc-81fd-a405e3937e9d

But just in case the need should be always keep the user Avatar here my proposal:

## Proposal

### Please re-state the problem that we are trying to solve in this issue. 
Android - Login - Custom avatars show placeholder avatars when the app is relaunched offline after login

### What is the root cause of that problem?
The Avatar image is downloaded when the user logs in and it is not saved in the mobile as a physical image.

### What changes do you think we should make to solve the problem?
We should save the image in the user's mobile, display that image when the user is offline, and update that image when the user is back online.

**Comment by Ggdroid** [comment] 2023-11-15 15:32
### Root Cause
There can be two probable causes - 

1. Wrong/default placeholder image being used. So when internet is off, the default image is being used instead since image cannot be loaded
2. Issue with caching of image itself. Either wrong strategy is used or local caching of images is not impkemented.

Fix -

As seen in your gradle file , fresco is being used so we should do two things 

1.  Fix any default images being passes in case of error & network issues
2. Implement correct cache stratergy using fresco

**Comment by s77rt** [comment] 2023-11-15 21:58
Is this still reproducible? I can't reproduce from my end


https://github.com/Expensify/App/assets/16493223/75011484-bd2d-4078-96e1-51e5c5a7bef0

**Comment by samilabud** [comment] 2023-11-16 00:05
> Is this still reproducible? I can't reproduce from my end
> 
>  Screen.Recording.2023-11-15.at.10.40.08.PM.mov

It seems to be happening only just after login

**Comment by s77rt** [comment] 2023-11-16 16:34
@samilabud Thanks for the proposal. Your RCA does not look complete. Can you explain why this bug is only reproducible after login?

**Comment by s77rt** [comment] 2023-11-16 16:35
@Ggdroid Thanks for your interest here. Can you please update your proposal to follow our [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md). Also there should be only one root cause.

**Comment by samilabud** [comment] 2023-11-16 17:00
> @samilabud Thanks for the proposal. Your RCA does not look complete. Can you explain why this bug is only reproducible after login?

Yes of course this is because Android creates a cache for all data/images of any application that is in use, in our case just after login android has not created the cache yet, but this is also reproducible when you clear the cache the cache, please see this video for a better explanation:

https://github.com/Expensify/App/assets/5216036/cecb2a58-14d9-4c17-9662-467894e51b94

**Comment by s77rt** [comment] 2023-11-16 18:24
@samilabud Ah I see thanks. In this case I don't think there is a need for Onyx here. How is that cache populated/managed? Is it time related? i.e. if we keep the App opened long enough before closing would the image be in the cache or what triggers caching the images?

**Comment by samilabud** [comment] 2023-11-16 18:54
The cache is populated and managed by Android (in this scenario) it seems to be related to the time of using (as far as I can see about 1 minute). This bug only going to happens on users that goes offline immediately after signing.

**Comment by s77rt** [comment] 2023-11-17 01:08
@samilabud Thanks for checking. In this case I doubt if we can fix that issue. Also it seems a low priority at this point.

**Comment by samilabud** [comment] 2023-11-17 01:24
> @samilabud Thanks for checking. In this case I doubt if we can fix that issue. Also it seems a low priority at this point.

Got it, I tried doing what I said in the proposal and it works. But I understand your point of view thanks 👍

**Comment by s77rt** [comment] 2023-11-17 14:37
I have asked in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1700231845490979) for confirmation

**Comment by s77rt** [comment] 2023-11-20 13:28
Not overdue. I just bumped the slack thread for more :eyes:

**Comment by s77rt** [comment] 2023-11-22 16:58
Not overdue. Gonna wait a little more for Slack input

**Comment by abekkala** [comment] 2023-11-22 21:36
I'm heading out for the Thanksgiving holiday and will be back bright and early Monday morning. 
If something pops up that needs urgent attention please reapply label or ask in slack.

**Comment by s77rt** [comment] 2023-11-27 14:05
Posted this on https://expensify.slack.com/archives/C02NK2DQWUX/p1701093875753589 for more :eyes:

**Comment by s77rt** [comment] 2023-11-29 13:47
@abekkala I think we can close this. This is not a bug on App but it's just how Android handle its cache.

**Comment by samilabud** [comment] 2023-11-29 14:09
Hi, in my understanding this is at least a minor issue because of our _Motivation & Philosophy_ (https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md):

_We expect that in offline mode all the features look normal and work as expected or the feature looks like it did whenever the connection was lost._

But maybe I'm misinterpreting 😅

**Comment by s77rt** [comment] 2023-11-29 14:15
@samilabud 

> We expect that in offline mode all the features look normal and work as expected or the feature looks like it did whenever the connection was lost.


That's already the case. But this offline behavior depends on your online presence. You need to stay online for at least few minutes so the images are downloaded and cached by Android.

**Comment by samilabud** [comment] 2023-11-29 14:34
Got it!, well if it doesn't matter that the user loses his avatar in the first minutes before going offline I agree that we should close this. Thank you!

**Closed** 2023-11-30 21:30 UTC
Labels: External, Daily, Help Wanted, Bug
