### ISSUE TITLE
Web - Chat creation - App crashes when creating group with new user and clicking on members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31654] opened 2023-11-21 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on Global FAB menu > start chat
2. Input a new user you didn't have a chat before
3. Click on add to group on the user
4. Input another user you have a previous chat with
5. Click on add to group on the user
6. Click on create group
7. Click on the group header
8. Click on members

## Expected Result:
App should show the list of the members

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ea576c47-2eca-495d-bf83-8968c692ca3f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-11-21 19:46
Issue is not reproduced on production

https://github.com/Expensify/App/assets/93399543/ee93463a-21df-4e2e-bba8-50f8375e2e1a

**Comment by pecanoro** [comment] 2023-11-21 19:53
This happens when people are not known between each other and show as hidden:

![image](https://github.com/Expensify/App/assets/6474442/a2a48721-a4e4-4902-8fcb-db8399489e96)

**Comment by pecanoro** [comment] 2023-11-21 19:53
I will try to look for the PR that broke it

**Comment by pecanoro** [comment] 2023-11-21 20:02
If not reproducible on main, we still need to look for the PR that fixed it and CP it 😄

**Comment by pecanoro** [comment] 2023-11-21 20:34
I think this could be something related to the back-end since it's not returning the display name.

**Comment by pecanoro** [comment] 2023-11-21 20:39
@puneetlath I think the changes [here](https://github.com/Expensify/Web-Expensify/pull/39684) caused the deploy blocker since the front-end is expecting a display name.

**Comment by luacmartins** [comment] 2023-11-21 23:24
We CPed a fix for this, so I'm gonna remove the blocker label

**Comment by puneetlath** [comment] 2023-11-22 16:10
This is fixed and CP'd. No payment needed. Going to go ahead and close.

**Closed by puneetlath** 2023-11-22 16:10 UTC
Labels: Reviewing, Engineering, Hourly
