### ISSUE TITLE
[$250] Login - "Get Started! Submit your first expense" message is displayed over Concierge Chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49566] opened 2024-09-21 06:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Create a workspace
2. Add a new user(not created account before) to the workspace.
3. Login with the new user

## Expected Result:
"Get Started! Submit your first expense" message is displayed over the workspace chat

## Actual Result:
"Get Started! Submit your first expense" message is displayed over the Concierge Chat,

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/58723d62-fccb-4c16-bc6c-8071d1e2e44b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838998888284432415</li>
        <li>Upwork Job ID: 1838998888284432415</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @srikarparsi</details>

**Comment by NJ-2020** [comment] 2024-09-21 06:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Get Started! Submit your first expense" message is displayed over Concierge Chat
### What is the root cause of that problem?
Right here we do not show if it is a concierge chat
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L424-L426
### What changes do you think we should make in order to solve the problem?
We can exclude if it is a concierge chat by using `!ReportUtils.isConciergeChatReport(report)`
Or we can show the tooltip by using `ReportUtils.isWorkspaceChat(report.chatType)`
### What alternative solutions did you explore? (Optional)
We can show only if we can request money inside the report by using `canRequestMoney` function

**Comment by NJ-2020** [comment] 2024-09-21 06:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Get Started! Submit your first expense" message is displayed over Concierge Chat
### What is the root cause of that problem?
Right here we do not exclude if it is a concierge chat
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L424-L426
### What changes do you think we should make in order to solve the problem?
We can exclude if it is a concierge chat by using `!ReportUtils.isConciergeChatReport(report)`
Or we can only show the tooltip by using `ReportUtils.isWorkspaceChat(report.chatType)`
### What alternative solutions did you explore? (Optional)
We can show only if we can request money inside the report by using `canRequestMoney` function

```ts
ReportUtils.canRequestMoney(report, policy, report.participantAccountIDs)
```

**Comment by kevinksullivan** [comment] 2024-09-25 17:49
Moving to collect since this is affecting the core flow of a newly invited user. Could go in control as well though

**Comment by NJ-2020** [comment] 2024-09-27 08:15
### [Proposal Updated](https://github.com/Expensify/App/issues/49566#issuecomment-2365030253)
- Small Changes

**Comment by RachCHopkins** [comment] 2024-10-03 00:30
@eVoloshchak do you like the look of any of the proposals here?

**Comment by situchan** [comment] 2024-10-03 04:50
I can help if needed, since I have been reviewing [related issue](https://github.com/Expensify/App/issues/49737)

**Comment by eVoloshchak** [comment] 2024-10-07 12:09
@NJ-2020's [proposal](https://github.com/Expensify/App/issues/49566#issuecomment-2365030253) looks good to me!

> We can exclude if it is a concierge chat by using !ReportUtils.isConciergeChatReport(report)

Let's proceed with this option rather than showing the tooltip for workspaces exclusively, you can submit expenses to users too

🎀👀🎀 C+ reviewed!

**Comment by mkzie2** [comment] 2024-10-07 12:13
@eVoloshchak As described in the doc here https://github.com/Expensify/App/issues/45046, this tooltip is exclusive to workspace chats.

**Comment by srikarparsi** [comment] 2024-10-09 18:13
Hm, I kind of like the alternate here:

> As described https://github.com/Expensify/App/issues/45046#:~:text=when%20they%20respond%20to%20the%20invitation%20email%2C%20they%20should%20be%20signed%20directly%20into%20the%20app%20and%20taken%20to%20their%20workspace%20chat, when user clicked the invitation link attached in the email, they should be directed to the workspace chat, not the default Concierge one.

@RachCHopkins what do you think?

**Comment by RachCHopkins** [comment] 2024-10-10 01:30
@srikarparsi would that have any impact on the guided setup process? That process happens in the Concierge chat. 

![image](https://github.com/user-attachments/assets/c1202348-0d2f-4b3a-b632-39e7500d7adc)

(sorry I poached the image from a slide)

**Comment by srikarparsi** [comment] 2024-10-14 09:20
> @srikarparsi would that have any impact on the guided setup process?
Hm, I'm not sure, I'll try to make some time to look into this today or Tuesday

**Comment by RachCHopkins** [comment] 2024-10-15 02:39
Pending more investigation

**Comment by RachCHopkins** [comment] 2024-10-16 20:34
This issue owner thing can be a real pain. Not overdue by 8 days Melvin. Maybe 2.

**Comment by srikarparsi** [comment] 2024-10-21 08:52
Hey sorry, I'll take a look at this today. I'm not too familiar with the guided setup process so need to take sometime to get familiarized with it.

**Comment by srikarparsi** [comment] 2024-10-22 02:51
I'm no longer able to reproduce this. @eVoloshchak can you see if this is still reproducible for you?

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/5f21e6ae-2c57-4c00-88ea-eb28072ea21b">

**Comment by mkzie2** [comment] 2024-10-22 04:16
@srikarparsi I can reproduce this. Steps:

1. Login with ANY account
2. After logging in, quickly open any report (Concierge, DM...)
3. Observe the tooltip shows

![Screenshot 2024-10-22 at 11 08 44](https://github.com/user-attachments/assets/a0094f94-0d06-4476-8845-45d689f180a8)

We have 2 more problems:

1. The `workspaceTooltip` is now retuned be the BE for EVERY accounts on EVERY sign-ins. Should be on [FIRST sign-in only](https://github.com/Expensify/App/issues/45046#:~:text=The%20NVP%20will%20no%20longer%20be%20sent%20on%20subsequent%20sign%2Dins.). That's why we can see the tooltip in every accounts and on every sign-ins.
2. If user manually opens any other reports, the tooltip still shows. So my alternative proposal which is to enforce opening workspace chat does not work.

**Comment by srikarparsi** [comment] 2024-10-29 05:02
> The workspaceTooltip is now retuned be the BE for EVERY accounts on EVERY sign-ins. Should be on https://github.com/Expensify/App/issues/45046#:~:text=The%20NVP%20will%20no%20longer%20be%20sent%20on%20subsequent%20sign%2Dins.. That's why we can see the tooltip in every accounts and on every sign-ins.
If user manually opens any other reports, the tooltip still shows. So my alternative proposal which is to enforce opening workspace chat does not work.

I'm not able to reproduce this either. @RachCHopkins, do you think you could check if you are and if not I think we can't either I think we can close out this issue.

**Comment by RachCHopkins** [comment] 2024-10-30 03:04
Same for me. Unable to repro.

**Closed by RachCHopkins** 2024-10-30 03:04 UTC
Labels: External, Daily, Help Wanted, Bug
