### ISSUE TITLE
[HOLD for #26498][$1000] Chat - It's not here" displayed when click on back bin after all request money was deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24490] opened 2023-08-12 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should be logged in
1. Open app
2. Tap on any 1:1 conversation with user
3. Make a two request money in a row
4. Tap on the requested money fiend in chat
5. Tap on the first requested money
6. Tap on 3 dots button > delete
7. Tap on back button
8. Tap on the remaining requested money
9. Tap on 3 dots button > delete
10. Tap on back button

## Expected Result:
User should be navigated back to the DM

## Actual Result:
Step 8: has navigated to the same page
Step 10: user has navigated to the "It's not here" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ec15eef5-6f54-4518-8753-98533638d447

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c14c4b05f0985c77</li>
        <li>Upwork Job ID: 1694085407589380096</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by tymatein** [comment] 2023-08-13 00:25
Proposal

Please re-state the problem that we are trying to solve in this issue.
When deleting the requested money, the navigation is set incorrectly.

What is the root cause of that problem?
The first problem with the duplicate screen is caused by redundant navigation to the report route with reportID.
The second problem with the error screen is caused by the omission of the second call to the goBack function. This leaves an invalid ID in the navigation stack.

What changes do you think we should make in order to solve the problem?
Make additional call of Navigation.goBack if needed and avoid useless navigation to avoid redundancy in the navigation stack.

```diff
diff --git a/src/libs/actions/IOU.js b/src/libs/actions/IOU.js
index 5660bc31a8..65357e22a8 100644
--- a/src/libs/actions/IOU.js
+++ b/src/libs/actions/IOU.js
@@ -965,14 +965,21 @@ function deleteMoneyRequest(transactionID, reportAction, isSingleTransactionView
     if (isSingleTransactionView && shouldDeleteTransactionThread && !shouldDeleteIOUReport) {
         // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
         Navigation.goBack();
-        Navigation.navigate(ROUTES.getReportRoute(iouReport.reportID));
+        if (!Navigation.isActiveRoute(ROUTES.getReportRoute(iouReport.reportID))) {
+            Navigation.navigate(ROUTES.getReportRoute(iouReport.reportID));
+        }
         return;
     }
 
     if (shouldDeleteIOUReport) {
         // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
         Navigation.goBack();
-        Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID));
+        if (Navigation.isActiveRoute(ROUTES.getReportRoute(iouReport.reportID))) {
+            Navigation.goBack();
+        }
+        if (!Navigation.isActiveRoute(ROUTES.getReportRoute(iouReport.chatReportID))) {
+            Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID));
+        }
     }
 }
```

What alternative solutions did you explore? (Optional)
No one.
Introduced by commit dc343ddda052893688174035392eb76dd1a0ac0a. As that commit is revert of the PR 22787 it would be safer to just fix this issue than do revert.

Reminder: Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by luacmartins** [comment] 2023-08-13 18:22
This is not a blocker. It's been the case since we introduced the feature.

**Comment by ShogunFire** [comment] 2023-08-14 00:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The navigation is wrong when we delete iou transaction

### What is the root cause of that problem?

1. When we delete a transaction in single transaction view we go back and navigate to the iou report instead of just going back

2. When we delete the last transaction we don't differentiate between context menu and single transaction view so the navigation is right for the context menu but not for the single transaction view

### What changes do you think we should make in order to solve the problem?

1. When we delete a transaction from the transaction view we can just go back in the stack, I put the default route just in case.

```
if (isSingleTransactionView && shouldDeleteTransactionThread && !shouldDeleteIOUReport) {
    Navigation.goBack(ROUTES.getReportRoute(iouReport.reportID));
    return;
}
```


2. When we delete the last transaction we must go back twice if we are in the single transaction view and only one time if we come from the context menu

```
if (shouldDeleteIOUReport) {
    if(isSingleTransactionView)
        Navigation.goBack();
    Navigation.goBack(ROUTES.getReportRoute(iouReport.chatReportID));
}
```


### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment] 2023-08-14 00:40
Actually we can simplify it even more by not returning in the first if like this:

```
if (isSingleTransactionView && shouldDeleteTransactionThread) {
    Navigation.goBack(ROUTES.getReportRoute(iouReport.reportID));
}

if (shouldDeleteIOUReport) {
    Navigation.goBack(ROUTES.getReportRoute(iouReport.chatReportID));
}
```

**Comment by grgia** [comment] 2023-08-22 17:59
@luacmartins is this a bug or something that is going to be cleaned up internally? Or can I make this external

**Comment by luacmartins** [comment] 2023-08-22 20:33
You can make this external

**Comment by DylanDylann** [comment] 2023-08-23 04:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - It's not here" displayed when click on back bin after all request money was deleted

### What is the root cause of that problem?
When we delete the last transaction
https://github.com/Expensify/App/blob/79ea92345e48599d6663ef20213f8c64bb0568c1/src/libs/actions/IOU.js#L1264-L1268
We will go back to IOU Report and then navigate to the chat report. In this time, the previous screen is IOU Report. So when clicking back button in the chat report, the App will go back to IOU Report (IOU report is removed) and display not found page
### What changes do you think we should make in order to solve the problem?
When deleting the last transaction, both transaction report and IOU report will be removed. So in here
https://github.com/Expensify/App/blob/79ea92345e48599d6663ef20213f8c64bb0568c1/src/libs/actions/IOU.js#L1264-L1268
I suggest we should use Navigation.goBack instead of `Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID)); `
like this
```
    if (shouldDeleteIOUReport) {
       
        Navigation.goBack();
      
        Navigation.goBack();
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment] 2023-08-24 11:44
@tymatein I tried your solution, but I still see the not found page in the background, is this a different issue? Even though the back button on step 10 is correctly navigated to LHN.

https://github.com/Expensify/App/assets/25520267/7159cc60-54b5-4078-b5e8-b27dfb7342a5

@DylanDylann Your solution basically the same with @tymatein and I still not convince calling `Navigation.goBack()` twice.

**Comment by ShogunFire** [comment] 2023-08-24 11:50
@mollfpr Hello, have you been able to review my solution too ? This is the same idea but better implemented and for me there was not page not found page https://github.com/Expensify/App/issues/24490#issuecomment-1676509023

**Comment by mollfpr** [comment] 2023-08-24 11:55
@ShogunFire I tried your solution, and it seems clearer than the other. So far, I haven't found any problem. I'll give an update after, testing it on all platforms.

**Comment by ShogunFire** [comment] 2023-08-24 12:16
Sorry but I tried many times and was not able to reproduce on either branch

**Comment by mollfpr** [comment] 2023-08-24 14:57
Thanks @tymatein for the confirmation. I'll try all the proposals thoroughly, and see which of the solution is a better approach.

**Comment by tymatein** [comment] 2023-08-24 16:33
@mollfpr IMHO we should create a new bug for the animated not found page problem. I can't find a nice solution for this. E.g. I don't know whether mobile app can temporarily disable the animation feature.

**Comment by mollfpr** [comment] 2023-08-25 05:40
@tymatein You're right. @ShogunFire's proposal didn't cover the above case. Could you explain why we need to call `Navigation.goBack()` twice?

```diff
+        if (Navigation.isActiveRoute(ROUTES.getReportRoute(iouReport.reportID))) {
+            Navigation.goBack();
+        }
+        if (!Navigation.isActiveRoute(ROUTES.getReportRoute(iouReport.chatReportID))) {
+            Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID));
+        }
```

Also, why do we need to check the currently active route on the second condition? Isn't `Navigation.isActiveRoute` will return false after the second `Navigation.goBack()`?

**Comment by tymatein** [comment] 2023-08-25 08:55
Yes, sure. Because 2 items in the navigation routes became invalid (records do not exist anymore).
So we need to do double goBack actions. See image
<img width="835" alt="Screenshot 2023-08-25 at 10 48 55" src="https://github.com/Expensify/App/assets/134623449/8d419eff-5c6e-4486-9081-6396b1d9047f">

**Comment by tymatein** [comment] 2023-08-25 09:29
I've been debugging it for hours.
I like the simplicity of @ShogunFire's design. 

There are 2 aspects involved:

1. In some situations the DM chat is not displayed after money request is deleted. If the user arrived by another way, e.g. by clicking on Money Request in LHN. The user will actually be navigated back to where she was originally. It's an edge case, but we could consider it a feature. I like it.

2. Unfortunately, the goBack function with fallback path doesn't work at all as I would expect. The fallback path is never used. This leads to the fact that after the money request is deleted:
- LHN (main) navigation is displayed on the mobile,
- NotFound page is displayed on desktop

Lets study desktop case:
Steps to reproduce:
1. Create money request in chat with PersonB
2. Go to money request
3. Refresh browser
4. Via context menu delete the money request
5. See that NotFound page is displayed
Why? The Desktop App recognizes that it can no longer navigate backwards, so it keeps the currently used path there. Which is the money request screen.
But if the `Navigation.navigate` function is called right after `Navigation.goBack`, then the Desktop App displays the requested screen, and at the same time the money request screen has been removed from the navigation stack. Therefore @tymatein proposal works well in all cases.

I think we need an expert on App Navigation, and investigate if the goBack function contains a bug.

**Comment by ShogunFire** [comment] 2023-08-25 09:49
If we want to ensure we are going to the chat report we can use navigate(fallbackRoute, CONST.NAVIGATION.TYPE.UP) instead of goBack(fallbackRoute)

**Comment by mollfpr** [comment] 2023-08-25 12:22
>IMHO we should create a new bug for the animated not found page problem. I can't find a nice solution for this. E.g. I don't know whether mobile app can temporarily disable the animation feature.

Let's put this aside; looks like out of the scope of this issue.

@tymatein Have you looked over the [NAVIGATION.md](https://github.com/Expensify/App/blob/main/contributingGuides/NAVIGATION.md)?

The double call `Navigation.goBack()` seems to be a workaround; maybe we can replace it with `Navigation.dismissModal(reportID)` as suggested in the doc?

**Comment by ShogunFire** [comment] 2023-08-25 12:29
dismissModal is just used for the RHP I think

**Comment by tymatein** [comment] 2023-08-25 13:33
@ShogunFire is correct. `dismissModal` is not intended to be called for screens in `NAVIGATORS.CENTRAL_PANE_NAVIGATOR`. 

BTW I re-read the [NAVIGATION.md](https://github.com/Expensify/App/blob/main/contributingGuides/NAVIGATION.md) but still I don't see any other way then 2x goBack.

**Comment by ShogunFire** [comment] 2023-08-25 13:47
Here https://github.com/Expensify/App/issues/24490#issuecomment-1693095224 I meant navigate(route,*UP*), not the const.At least that's not two goBack but two navigate if we do this ahah, I think it´s working and very clean solution

**Comment by ShogunFire** [comment] 2023-08-25 13:53
## Proposal
[Updated](https://github.com/Expensify/App/issues/24490#issuecomment-1676509023)

I think this is a mix of the best between @tymatein and my former solution so maybe we can share the bounty if this is chosen

**Comment by tymatein** [comment] 2023-08-25 14:02
It is not working at all. The browser freezes. Did you test that? Actually the `navigate(route, "UP")` is not working for me. I am not sure whether I am doing something wrong on my side.

**Comment by tymatein** [comment] 2023-08-25 14:05
For:
```
    if (isSingleTransactionView && shouldDeleteTransactionThread) {
        Navigation.navigate(ROUTES.getReportRoute(iouReport.reportID), 'UP');
    }

    if (shouldDeleteIOUReport) {
        Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID), 'UP');
    }
```
https://github.com/Expensify/App/assets/134623449/167cdd36-7530-46ec-88df-6ab3e23eca49

**Comment by tymatein** [comment] 2023-08-25 14:26
Also not working.
```
    if (isSingleTransactionView && shouldDeleteTransactionThread && !shouldDeleteIOUReport) {
        // ...
        return;
    }

    if (shouldDeleteIOUReport) {
        Navigation.goBack();
        Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID), 'UP');
    }
```

https://github.com/Expensify/App/assets/134623449/2d5d79c5-6720-4723-a331-874b969015aa

**Comment by ShogunFire** [comment] 2023-08-25 14:31
They have made so many changes in the linkTo method, it no longer does what it is supposed to,https://github.com/Expensify/App/blob/f3af8ce1ccecc013670798fe2e8118c7f0c1a525/src/libs/Navigation/linkTo.js#L65-L66

**Comment by tymatein** [comment] 2023-08-25 16:08
Actually there is also this condition.
https://github.com/Expensify/App/blob/f3af8ce1ccecc013670798fe2e8118c7f0c1a525/src/libs/Navigation/linkTo.js#L74C1-L75C64
But still it does not work properly. We should create another bug to verify and fix that. Can you please do that, @ShogunFire ? Thanks

Anyway back to our original issue. If I'm not mistaken, swapping screens using `Navigation.navigate(...,UP)` doesn't help us much, because it creates another problem. There will be two identical DM chat screens with Person B in a row in the navigation stack.

**Comment by ShogunFire** [comment] 2023-08-25 16:12
Yes then I don't see any alternative to two goBack

**Comment by shubham1206agra** [comment] 2023-08-25 17:36
Can you try after pulling the main now?

**Comment by tymatein** [comment] 2023-08-25 18:26
@shubham1206agra Sorry, what exactly we should try again?
Without any change to the origin/main there is still displayed NotFound page or eventually there is 2 same screens in the row in the navigation stack.

https://github.com/Expensify/App/assets/134623449/afa57a6e-1d3b-4bd5-a083-ef4ab54fc8fd


https://github.com/Expensify/App/assets/134623449/8ea13a01-fc8b-4936-9c45-3bed2033df45

**Comment by tymatein** [comment] 2023-08-25 18:29
I don't see any change in behaviour of `Navigation.navigate(<path>, 'UP');` in comparison to `Navigation.navigate(<path>);`

**Comment by tymatein** [comment] 2023-08-25 19:37
Proposal https://github.com/Expensify/App/issues/24490#issuecomment-1676159350 is still valid. All edge cases are OK.

**Comment by adelekennedy** [comment] 2023-08-26 18:50
chill melvin - we didn't actually make this external until 4 days ago

**Comment by mollfpr** [comment] 2023-08-27 09:44
@tymatein I tried your solution again; it's working fine on Android, but it's not navigating me anywhere on the Web, so it's showing me the not found page.

https://github.com/Expensify/App/assets/25520267/3d9e18d6-3530-4427-99b1-1c4ed3cbb7e2

**Comment by tymatein** [comment] 2023-08-27 12:22
@mollfpr Are you sure that you changed your code correctly? It is working for me also in the web. Be careful especially with this condition:
`if (isSingleTransactionView && shouldDeleteTransactionThread && !shouldDeleteIOUReport) {`

**Comment by tymatein** [comment] 2023-08-28 15:43
@mollfpr Yes, I did it yesterday for commit c029dc509d03fd13ece058ba89ab25c4318a9050
Should I record video with fresh main?

**Comment by ShogunFire** [comment] 2023-08-28 15:48
Honestly I think my goBack(fallBackRoute) method should work and every other method is a workaround, I have asked on slack https://expensify.slack.com/archives/C01GTK53T8Q/p1693231187280079?thread_ts=1693168254.867579&cid=C01GTK53T8Q if someone can look at it. Maybe the issue with @tymatein method is that I am not sure if calling isActiveRoute just after goBack always work, maybe it takes some time to update the active route

**Comment by tymatein** [comment] 2023-08-28 19:12
@mollfpr The error you found on the web looks strange. There are two money requests in the IOU, so it should only navigate back one screen. In the code, the first function called is `Navigation.goBack`, so it should work. What browser/operating system are you using?

**Comment by mollfpr** [comment] 2023-09-01 16:55
Need more time to review the proposals. I'll give an update tomorrow.

**Comment by shubham1206agra** [comment] 2023-09-01 17:38
Can anyone test the repro of this issue after pulling the latest main?
It looks like this is a navigation-related issue.
Thanks

**Comment by ShogunFire** [comment] 2023-09-01 19:15
@mollfpr following the slack discussion I opened, they are improving the goBack method so that the fallback route works for report. They are doing that here: https://github.com/Expensify/App/pull/26283 Maybe we can wait for that PR to be merged and see if my proposal works after that.

**Comment by mollfpr** [comment] 2023-09-04 17:41
It seems the proposal from @ShogunFire is used in the PR https://github.com/Expensify/App/pull/26498 for navigation 🥲

@adelekennedy We should hold this in favor of the above PR.

**Comment by ShogunFire** [comment] 2023-09-04 17:56
@mollfpr Yes I agree we should hold, it's almost my proposal but not exactly, I think there will still be a problem because with that PR we only do one goBack (we need 2 when we delete the last transaction)

**Comment by adelekennedy** [comment] 2023-09-11 09:18
on hold still

**Comment by adelekennedy** [comment] 2023-09-14 03:32
still holding

**Comment by adelekennedy** [comment] 2023-09-18 08:54
@mollfpr is this still on hold?

**Comment by mollfpr** [comment] 2023-09-18 10:18
@adelekennedy Yes!

**Comment by adelekennedy** [comment] 2023-09-21 10:35
deprioritizing for the hold

**Comment by adelekennedy** [comment] 2023-10-24 00:48
I believe this is still on hold!

**Comment by adelekennedy** [comment] 2023-11-26 19:52
@mollfpr it looks like the connected PR was deployed a bit ago - are we still on hold here?

**Comment by mollfpr** [comment] 2023-12-19 12:08
I can't reproduce the issue on `1.4.14-0 Develop`.

**Comment by adelekennedy** [comment] 2024-01-19 19:49
hmm - I also can't reproduce @lanitochka17 will you see if you're still running into this?

**Closed** 2024-02-20 17:06 UTC
Labels: External, Engineering, Monthly, Help Wanted, Overdue, Bug
