### ISSUE TITLE
[HOLD for payment 2023-10-25] [$1000] Web - App maintains focus but does not scroll to bottom at cursor position on reload

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27153] opened 2023-09-11 14:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send big message that enables scroll
4. Reload and observe that focus is on composer but it does not scroll to cursor position
5. Click on any user profile to open details page and reload
6. Click on back and observe that now app scrolls to bottom to cursor position

## Expected Result:
 App should scroll to cursor position if focus is maintained on composer box

## Actual Result:
 App maintains focus but does not scroll to bottom at cursor position in compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/21dd79e4-111e-41a8-81f3-a05d5a8ab980

https://github.com/Expensify/App/assets/93399543/d64d8eab-5a34-4622-9472-c940d98b3598

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694063310399689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01048bbbaff6031064</li>
        <li>Upwork Job ID: 1701240589171867648</li>
        <li>Last Price Increase: 2023-09-28</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27014842</li>
<li>jeet-dhandha | Contributor | 27014844</li>
<li>dhanashree-sawant | Reporter | 27014846</li>
</ul></li>
    </ul>
</details>

**Comment by usafhassan** [comment] 2023-09-11 15:48
### Proposal
**Problem:** App maintains focus but does not scroll to bottom at cursor position on reload
**Root Cause:** Its refreshing, that is why it losing the state

**Changes required to resolve:**
We need to add a single line of code to set scrollTop:
textInput.current.scrollTop = textInput.current.scrollHeight;

Here is the complete solution code

```
import React, { useEffect, useState, useRef } from "react";

export default function Msg() {
  // get the message from local storage if it is not there set it to empty
  const [msgText, setMsgText] = useState(localStorage.getItem("msg") || "");
  const textareaRef = useRef();

//   on reload check if there is reference to textarea and message is there
//  then scroll the textarea to the end
  useEffect(() => {
    if (textareaRef.current && msgText) {
      textareaRef.current.scrollTop = textareaRef.current.scrollHeight;
    }
  }, []);

//   save msg to localstorage
  useEffect(() => {
    localStorage.setItem("msg", msgText);
  }, [msgText]);

  return (
    <div>
      <textarea
        ref={textareaRef}
        value={msgText}
        onChange={(e) => setMsgText(e.target.value)}
      />
    </div>
  );
}
```

Upwork Profile: https://www.upwork.com/freelancers/~0141ec503adff92d50

**Comment by usafhassan** [comment] 2023-09-11 15:51
Contributor details
Your Expensify account email: usafhassan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0141ec503adff92d50

**Comment by jjcoffee** [comment] 2023-09-12 14:58
@usafhassan Welcome :wave: and thanks for your proposal! Please read our [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and use the proposal template there.

For both proposals I think it'd be nice to add to the RCAs why steps 5 & 6 work to set the correct scroll position. @usafhassan @binary3oul

**Comment by binary3oul** [comment] 2023-09-12 16:36
# [Updated Proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1714118413)

**Comment by jjcoffee** [comment] 2023-09-13 07:49
@binary3oul Thanks, I'm still interested in why steps 5 & 6 work to set the correct scroll position though :smile:

**Comment by binary3oul** [comment] 2023-09-13 12:22
When we refresh the page, Composer component saves the position of the cursor whereas don't save scrollTop property.
In Composer component, we missed to set scrollTop propery of textInput.

**Comment by jjcoffee** [comment] 2023-09-13 12:31
Specifically why does this step currently work though:

> Click on back and observe that now app scrolls to bottom to cursor position

**Comment by usafhassan** [comment] 2023-09-13 13:31
@jjcoffee 
The step 5 and 6 works because when we go back to the report page where we are writing a long message, 
that page is still maintaining it's state (or getting from a global store/redux store), as we did not reload that page(report page), 
even though we reloaded the details page, it does not affect the state of report page and we still go to cursor position.

**Comment by jjcoffee** [comment] 2023-09-15 15:11
@usafhassan Thanks, but my point is even if I scroll up to the top of the message and then perform the same steps (open details page, reload, go back), the input is scrolled to the bottom. I think it'd be useful to understand what's happening there as presumably we could use the same on reload to keep things nice and clean!

**Comment by usafhassan** [comment] 2023-09-15 22:52
@jjcoffee when we close the side menu, the `useEffect` runs which calls the `focus()` function

**Comment by usafhassan** [comment] 2023-09-16 05:58
@jjcoffee also we can add another dependency variable for reload and set it to true in initial state, then add it in dependency array of  useEffect where we are setting the scroll position, this will set it to correct position on reload

**Comment by jjcoffee** [comment] 2023-09-18 16:01
Reviewing tomorrow!

**Comment by dylanexpensify** [comment] 2023-09-19 15:04
@jjcoffee reminder on the review! 🙇‍♂️

**Comment by jjcoffee** [comment] 2023-09-19 15:29
@usafhassan That's what I was getting to, if `focus()` works fine to "set" the correct scroll position in the context of closing the side menu, the RCA isn't really that we're refreshing and not saving state.

Still waiting for a proposal with a good RCA here @dylanexpensify. I don't know how you feel about raising the bounty to attract more proposals?

**Comment by dylanexpensify** [comment] 2023-09-21 17:34
Let's double! Also, @jjcoffee mind replying to above when you have a moment? 🙇‍♂️

**Comment by jeet-dhandha** [comment] 2023-09-21 19:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- On reloading the page the composer is not scrolled to the bottom when long text is there.

### What is the root cause of that problem?
- The composer is rendered with the height of 30px initially and then the height is increased to fit the content. So even if composer is focused the page is not scrolled to the bottom.

### What changes do you think we should make in order to solve the problem?

- We can use logic of `Paste` function to scroll to the bottom of the composer.

https://github.com/Expensify/App/blob/65fd4350829a60399aa36693a4731ac69b8e2b70/src/components/Composer/index.js#L235-L243

- We can make use of the `useEffect` hook to check if the text input is focused and overflowing. 
- We will use `InteractionManager` to wait till the whole component is rendered and then check if the text is overflowing or not. If the text is not overflowing then we don't need to scroll to the bottom.
- If the text is overflowing then we will `blur` and `focus` the text input which will scroll the composer to the bottom.

<details>

<summary>Code Implementation:</summary>

```js
useEffect(() => {
    // If the text input is not focused then we don't need to scroll to the bottom.
    if (!willBlurTextInputOnTapOutside || !isFocused || !textInputRef.current) {
        return;
    }
    // This waits till the whole component is rendered and then checks if the text is overflowing or not.
    InteractionManager.runAfterInteractions(() => {
        const {clientHeight, scrollHeight} = textInputRef.current;
        const shouldScroll = scrollHeight > clientHeight; // 550 (Scrollable height) > 330 (Viewable height)
        
        // If the text is not overflowing then we don't need to scroll to the bottom.
        if (!shouldScroll) {
            return;
        }
        blur();
        focus(false);
    });
}, [focus, blur, isFocused]);
```

</details>

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by iamuddeshya** [comment] 2023-09-21 19:56
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
App does not scroll down to the cursor point when the text is large on refresh but it does when sidebar is opened and then closed or emoji picker is opened and then closed or in similar cases. 

## What is the root cause of that problem?
The function `focus()` is not getting called when we are refreshing the page. 
https://github.com/Expensify/App/blob/65fd4350829a60399aa36693a4731ac69b8e2b70/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L346-L348

But this get's called when a Modal is closed, see here https://github.com/Expensify/App/blob/65fd4350829a60399aa36693a4731ac69b8e2b70/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L444

To verify this, you can also see that the cursor get's focused if you even open the Emoji Picker and close it. 

This is the useEffect where you will notice that after two `if` conditions the `focus` function is called.
https://github.com/Expensify/App/blob/65fd4350829a60399aa36693a4731ac69b8e2b70/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L432

See the video to understand more on what is happening and please assume a new case each time I clear the logs. That said, there are 3 cases here in the video Case 1 (Page Refreshed), Case 2 (Sidebar Open) and Case 3 (Sidebar Closed, focus back to input ) 

https://github.com/Expensify/App/assets/19757182/52de73c5-24fc-4e92-8c21-89b761553c0a

#### Observations:

1. **Case 1 (Page Refreshed)**:
    - `setUpComposeFocusManager` is called twice before any check on modal visibility.
    - There's no `FOCUS true {shouldDelay: false}` log here, indicating that the `focus` event didn't occur.

2. **Case 2 (Sidebar Open)**:
    - There's a repetition in the pattern of `setUpComposeFocusManager` followed by checks on modal visibility.
    - Again, no `FOCUS true {shouldDelay: false}` log, indicating `focus` wasn't applied.
  
3. **Case 3 (Sidebar Closed)**:
    - `setUpComposeFocusManager` is called initially.
    - Later, we see the `FOCUS true {shouldDelay: false}` log, indicating that the `focus` event occur and the cursor was indeed focused.

#### Potential Cause:

The unique event in Case 3, which isn't present in the other cases, is the `FOCUS true {shouldDelay: false}` log. This is the most apparent reason why the cursor is getting focused in Case 3 i.e. when closing slider or the emoji picker and coming back.

Also, the sequence of the events in Case 3 is different. After the `setUpComposeFocusManager`, there's an immediate `prevIsModalVisible`, which might be crucial. The fact that `setUpComposeFocusManager` is called immediately after the check might trigger the subsequent focus event.

## What changes do you think we should make in order to solve the problem?
We can make sure that the `focus` event is fired when page is refreshed or any other navigation is made. 

## What alternative solutions did you explore? (Optional)
We can also add in a useEffect that can run on each render and scroll to the position where the cursor is.

**Comment by iamuddeshya** [comment] 2023-09-21 19:58
> @usafhassan That's what I was getting to, if `focus()` works fine to "set" the correct scroll position in the context of closing the side menu, the RCA isn't really that we're refreshing and not saving state.
> 
> Still waiting for a proposal with a good RCA here @dylanexpensify. I don't know how you feel about raising the bounty to attract more proposals?

Hii @jjcoffee My proposal [here](https://github.com/Expensify/App/issues/27153#issuecomment-1730209609) might answer your question :)

**Comment by jjcoffee** [comment] 2023-09-22 15:23
@usafhassan Your [proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1714152786) is missing a clear enough RCA that explains why the behaviour happens and points us to the solution that's most correct and not just a workaround.

@jeet-dhandha Thanks for your [proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1730190932), it sounds good to me, but could you explain your RCA a bit more? Why do we not scroll to the bottom in that case (and only on web apparently)? I'm guessing we focus on the input before we change the height or something like that? My only concern with your solution is the delay before we scroll to the bottom. Ideally we'd just be at the bottom on page load, I think (that's how Slack does it, at least!).

@iamuddeshya Thanks for the [proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1730209609)! The input _does_ get focused (at least some of the time!), which you can verify by logging from `onFocus`, so your RCA isn't quite right I don't think. I'd also encourage you to keep your proposal concise so that it's easy for others to read (for example it's not the easiest to read your log statements :wink: - it would be better to just explain your results).

**Comment by iamuddeshya** [comment] 2023-09-22 19:07
> @usafhassan Your [proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1714152786) is missing a clear enough RCA that explains why the behaviour happens and points us to the solution that's most correct and not just a workaround.
> 
> @jeet-dhandha Thanks for your [proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1730190932), it sounds good to me, but could you explain your RCA a bit more? Why do we not scroll to the bottom in that case (and only on web apparently)? I'm guessing we focus on the input before we change the height or something like that? My only concern with your solution is the delay before we scroll to the bottom. Ideally we'd just be at the bottom on page load, I think (that's how Slack does it, at least!).
> 
> @iamuddeshya Thanks for the [proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1730209609)! The input _does_ get focused (at least some of the time!), which you can verify by logging from `onFocus`, so your RCA isn't quite right I don't think. I'd also encourage you to keep your proposal concise so that it's easy for others to read (for example it's not the easiest to read your log statements 😉 - it would be better to just explain your results).

Noted! Thanks for the suggestion. Will definitely consider it in future proposals. 🙌🏻

**Comment by jeet-dhandha** [comment] 2023-09-23 02:02
@jjcoffee Updated Proposal : https://github.com/Expensify/App/issues/27153#issuecomment-1730190932. 
- Added an alternative approach, which I believe is more effective because it prevents the scroll animation from occurring and ensures that the initial state of composer is displayed with content scrolled to the bottom.

**Comment by dylanexpensify** [comment] 2023-09-25 10:37
@jjcoffee let's review updated proposal, please!

**Comment by jjcoffee** [comment] 2023-09-25 14:21
@jeet-dhandha your alternative approach looks like it would be a partial rework of [`UpdateMultilineInputRange`](https://github.com/Expensify/App/blob/main/src/libs/UpdateMultilineInputRange/index.js) which we're already using to solve a similar problem for a few other screens, e.g. in https://github.com/Expensify/App/issues/21654. I don't think there's any good reason not to use that here.

Also, would you be able to clear up your RCA so that we have a nice clear relation between RCA and solution?

Still open for any proposals that satisfy the requirement for clear RCA & solution!

**Comment by jeet-dhandha** [comment] 2023-09-26 01:39
RAC In Detail:

Reproduction code in HTML:
- In below code when we call `setData` on `window.onload` (where whole page is rendered) the textarea is focused and selection is at bottom, but the scroll is still at top. 
- In our app we are using `autofocus` to focus and `selection` prop to set initial selection, but its setting everything after component is rendered which causes this issue.

```html
<html lang="en">
  <body>
    <textarea name="text" id="text" style="height: 330px; width: 500px" autofocus>
asdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfjakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsfasdfiajsdlfk jakldsfj lkadsjflka djsflkajsdflkjalsdfkjlakdsf</textarea
    >
  </body>
  <script>
    const setData = () => {
      const len = document.getElementById("text").value.length;
      document.getElementById("text").setSelectionRange(len, len);
      document.getElementById("text").scrollTop = document.getElementById("text").scrollHeight;
    };

    const logData = (prefix) => {
      const { scrollHeight, scrollTop, style } = document.getElementById("text");
      console.log(prefix, "scrollHeight: ", scrollHeight, "scrollTop: ", scrollTop, "style.height: ", style.height);
      document.getElementById("text").scrollTop = document.getElementById("text").scrollHeight;
    };

    logData("initial"); // Before the textarea is rendered 

    window.onload = () => {
      logData("onload"); // After the textarea is rendered 
    };
  </script>
</html>
```

- Now if we set `selectionRange` and `scrollTop` when ref is initialised then the `selection` and `scrollTop` is set before textarea is rendered which fixes the issue.

https://github.com/Expensify/App/blob/c6b7eaecc76691a2f944c688e49b045eede22356/src/components/Composer/index.js#L458

```js
ref={(el) => {
    textInput.current = el;
    const {scrollTop, scrollHeight} = textInput.current;
    
    // Don't want unnecessary focus on composer, thus checking autoFocus and scrollTop
    if (autoFocus && scrollTop === 0) { 
        textInput.current.scrollTop = scrollHeight;
        textInput.current.setSelectionRange(value.length, value.length);
    }
}}
```

**Comment by jeet-dhandha** [comment] 2023-09-26 01:41
@jjcoffee Had to write RAC in details in different comment as Proposal would have got longer.

**Comment by bfitzexpensify** [comment] 2023-09-28 15:27
How does the updated proposal look @jjcoffee?

**Comment by jjcoffee** [comment] 2023-09-29 15:22
Just to summarise, I think we're looking for a solution that immediately loads with the composer scrolled to the bottom. @jeet-dhandha your [proposal's](https://github.com/Expensify/App/issues/27153#issuecomment-1730190932) alternative solution appears to do this, but could you respond to my [comment](https://github.com/Expensify/App/issues/27153#issuecomment-1733811246)?

I don't think the RCA you [posted](https://github.com/Expensify/App/issues/27153#issuecomment-1734699090) is particularly concise. Please could you write something simpler that clearly explains the root cause in a few lines?

**Comment by jeet-dhandha** [comment] 2023-09-29 15:48
Brief RCA:
- HTML's `textarea` by default doesn't support `bottom-scroll` when its focus. 

Brief Solution:
- Which is why to achieve that we are using javascript for accessing dom element and its attributes `scrollTop` and `scrollHeight`.
- We are setting `scrollTop` to `scrollHeight` before element is focused.
- We are setting its selection to end of the text.

**Comment by jeet-dhandha** [comment] 2023-09-29 15:48
Please check @jjcoffee

**Comment by jjcoffee** [comment] 2023-10-03 11:33
Reviewing today!

**Comment by jjcoffee** [comment] 2023-10-03 12:49
Thanks for the more concise RCA, @jeet-dhandha! Could you update your proposal with that? 

I'm also waiting for your response to this [comment](https://github.com/Expensify/App/issues/27153#issuecomment-1733811246), but I'd like to avoid blocking this any longer, so I think we can address that in the PR. If you agree I think we can go ahead and use [UpdateMultilineInputRange](https://github.com/Expensify/App/blob/main/src/libs/UpdateMultilineInputRange/index.js) here.

Let's go with @jeet-dhandha's [proposal](https://github.com/Expensify/App/issues/27153#issuecomment-1730190932), since they've got the most developed RCA.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by dylanexpensify** [comment] 2023-10-03 17:45
bump @jeet-dhandha

**Comment by jeet-dhandha** [comment] 2023-10-03 18:08
Updated Proposal - https://github.com/Expensify/App/issues/27153#issuecomment-1730190932. 
- With the Brief RCA and Solution. 
- Will use [UpdateMultilineInputRange](https://github.com/Expensify/App/blob/main/src/libs/UpdateMultilineInputRange/index.js) , in the PR. 

I will create PR tomorrow. Its a bit late here. 👍

**Comment by jjcoffee** [comment] 2023-10-04 09:09
@jeet-dhandha No rush on the PR, we're still waiting for you to get assigned by @nkuoch!

**Comment by jeet-dhandha** [comment] 2023-10-04 16:49
@jjcoffee - There's an issue with Mobile Safari its auto-focusing by default. This is happening in `main` also. Should we handle it in a different PR ?

**Comment by jeet-dhandha** [comment] 2023-10-04 16:57
https://github.com/Expensify/App/assets/78416198/8de39923-0b2c-4305-b4ab-2e6ae1b61d9b

**Comment by jjcoffee** [comment] 2023-10-05 13:04
@jeet-dhandha Yeah I would say if there's a general issue on native devices that the composer isn't focused (whether intentional or not), that would be out of scope for this issue. Feel free to report it!

**Comment by jeet-dhandha** [comment] 2023-10-09 16:33
WTH 😵‍💫 it was not working previously as the scroll to bottom animation was coming. But now its working probably due to the removal on `InteractionsManager`. 

@jjcoffee Removing all the unnecessary code.

**Comment by dylanexpensify** [comment] 2023-10-10 11:13
@jeet-dhandha @jjcoffee mind giving us an update?

**Comment by jjcoffee** [comment] 2023-10-10 11:20
@dylanexpensify PR is under review - just needed quite a bit of back and forth to get the code in shape!

**Comment by dylanexpensify** [comment] 2023-10-24 22:53
payment tomorrow!

**Comment by jeet-dhandha** [comment] 2023-10-26 03:30
Bump for payment

**Comment by jjcoffee** [comment] 2023-10-26 08:33
- The PR that introduced the bug has been identified. Link to the PR: **N/A - we've never handled this**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression test proposal**

1. Open any report
2. Enter a long enough text to make composer take full height and scroll bars appear
3. Refresh the page of that report.
4. Verify that the composer is scrolled to the bottom for all platforms except iOS.

Do we agree 👍 or 👎

**Comment by bfitzexpensify** [comment] 2023-10-27 01:39
Payments complete - will review the proposed regression steps tomorrow

**Comment by bfitzexpensify** [comment] 2023-10-27 16:41
Regression steps look good, opened an issue to get it updated. We're all done here, thanks everyone

**Closed by bfitzexpensify** 2023-10-27 16:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
