### ISSUE TITLE
[HOLD for payment 2024-10-22] [$250] mWeb - Chat - The welcome group message doesn't update when a user is removed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49933] opened 2024-09-30 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49618
## Action Performed:
1. FAB > start chat
2. Select a few members and create a group chat
3. Press on members and remove one user from the group
4. Navigate to the group chat

## Expected Result:
The removed user is not displayed in the welcome group message

## Actual Result:
The removed user is still displayed in the welcome group message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/29d62e4a-022e-4c08-b543-f4eefb949305

![Message_not_updated](https://github.com/user-attachments/assets/6dfebc45-8540-409c-8319-49cd02ea439d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841455012379899950</li>
        <li>Upwork Job ID: 1841455012379899950</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104310823</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by bernhardoj** [comment] 2024-09-30 14:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The group welcome text doesn't immediately update its members/participant.

### What is the root cause of that problem?
When we remove participant from the group, we don't immediately remove it from `participants`, but rather put it in `pendingChatMembers` list. After the request is success, the member will be removed.

Currently, we show the list of the participants from the `participants` without filtering the pending delete members.
https://github.com/Expensify/App/blob/e84dab77b7bf3481961d590e1f547b8f7ff1b944/src/components/ReportWelcomeText.tsx#L43
https://github.com/Expensify/App/blob/e84dab77b7bf3481961d590e1f547b8f7ff1b944/src/libs/ReportUtils.ts#L2110-L2112

So, the text will still shows the pending delete member for a while.

### What changes do you think we should make in order to solve the problem?

To not show the deleted member, we need to pass `shouldExcludeDeleted` as true.
```
const participantAccountIDs = ReportUtils.getParticipantsAccountIDsForDisplay(report, undefined, true);
```

`I think we can make the default to true, but not sure why we made it false.`

**Comment by alitoshmatov** [comment] 2024-10-06 09:54
@bernhardoj Thank you for your proposal, your RCA is correct. Looks like fairly simple solution.

We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/49933#issuecomment-2383446895)

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment] 2024-10-08 06:07
PR is ready

cc: @alitoshmatov

**Comment by sonialiap** [comment] 2024-10-17 15:55
I'm OOO on the 22nd so adding a buddy to make payment

Payment summary:
- @bernhardoj $250 please request in ND
- @alitoshmatov $250 [upwork](https://www.upwork.com/nx/wm/offer/104310823) - please complete the [checklist](https://github.com/Expensify/App/issues/49933#issuecomment-2412783423)

**Comment by bernhardoj** [comment] 2024-10-17 16:53
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-21 11:08
$250 approved for @bernhardoj

**Comment by alitoshmatov** [comment] 2024-10-23 10:16
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/49919
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/49919/files#r1812414693
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. Straightforward fix, no need

**Comment by alitoshmatov** [comment] 2024-10-23 10:16
@JmillsExpensify Checklist done

**Comment by sonialiap** [comment] 2024-10-23 16:05
@alitoshmatov thanks! Payment completed ✔️

**Comment by tgolen** [comment] 2024-10-23 21:52
@sonialiap can you please copy the checklist answers from @alitoshmatov into the checklist comment above and then complete your checklist item?

**Comment by sonialiap** [comment] 2024-10-24 09:01
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@alitoshmatov] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/49919
- [x] [@alitoshmatov] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/49919/files#r1812414693
- [x] [@alitoshmatov] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **No need**
- [x] [@alitoshmatov] Determine if we should create a regression test for this bug.: **Straightforward fix, no need**
- [x] [@alitoshmatov] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. : **no need for regression test**
- [x] [@sonialiap] Link the GH issue for creating/updating the regression test once above steps have been agreed upon: **no need for regression test**

**Closed by sonialiap** 2024-10-24 09:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
