### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] 2FA "Disable Authentication" page comes up again if we navigate back to the page in Offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21568] opened 2023-06-26 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open account with 2FA enabled
2. Go offline
3. Go to Settings -> security -> Two-factor authentication
4. "Disable Authentication" page will be shown
5. Disable the 2FA
6. Offline page with no action will be shown
7. Close settings and come back to same page

## Expected Result:
Offline page with no action should be shown

## Actual Result:
 "Disable Authentication" page will be shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/119e4b8c-940f-43f3-9d9c-970fd5e885e6

https://github.com/Expensify/App/assets/93399543/c9b8d9fb-df32-43ef-b77f-ac76cb1547cd

**Expensify/Expensify Issue URL:**
**Issue reported by:** abdulrahuman5196
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687424270135549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164903c489572791c</li>
        <li>Upwork Job ID: 1673598551156371456</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-27 13:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
2FA "Disable Authentication" page comes up again if we navigate back to the page in Offline mode 

### What is the root cause of that problem?
As we are not blocking the View when the user is offline causing the issue.

### What changes do you think we should make in order to solve the problem?
We should wrap the `ScrollView` with the `FullPageOfflineBlockingView` component, which will show the offline blocking View to the user and not allow to disabling the 2FA in offline mode. 

https://github.com/Expensify/App/blob/9604ac7ea8c94f13008da23fd39247387bdee16b/src/pages/settings/Security/TwoFactorAuth/IsEnabledPage.js#L26

**Comment by abekkala** [comment] 2023-06-28 14:21
@bfitzexpensify I think this one would be a dupe of an issue reported first: https://github.com/Expensify/App/issues/21431

**Comment by bfitzexpensify** [comment] 2023-06-29 05:39
I had the same hesitation, but landed on the same conclusion as @0xmiroslav. Let's see what Chirag says.

**Comment by chiragsalian** [comment] 2023-07-03 22:20
Yup, i'm on the same boat as @0xmiroslav. Plus when the user does not have 2FA enabled and visits 2FA page when offline they see "You appear to be offline" message. I think its fine showing the same message for the same page when 2FA is enabled as well.

I like @Pujan92's proposal as well. Free free to create the PR @Pujan92.

**Comment by Pujan92** [comment] 2023-07-04 17:15
@0xmiroslav @chiragsalian [PR](https://github.com/Expensify/App/pull/22202) is ready for review!

**Comment by bfitzexpensify** [comment] 2023-07-19 08:30
@0xmiroslav reminder to complete the BZ checklist when you get a moment - thanks!

**Comment by bfitzexpensify** [comment] 2023-07-21 12:38
@0xmiroslav another reminder - once the BZ checklist is complete here I'll pay out the C+ payment

**Comment by bfitzexpensify** [comment] 2023-07-24 12:16
Sure, moving this to monthly - @0xmiroslav, please comment here when you'd like me to issue payment.

**Comment by chiragsalian** [comment] 2023-08-30 22:31
any update here @0xmiroslav?

**Comment by bfitzexpensify** [comment] 2023-10-03 22:37
Guessing this is still being figured out @0xmiroslav?

**Comment by chiragsalian** [comment] 2023-10-05 22:36
Cool, closing.

**Closed by chiragsalian** 2023-10-05 22:36 UTC
Labels: External, Monthly, Awaiting Payment, Bug
