### ISSUE TITLE
[$500] mWeb/Safari - Workspace - Expensify site is visible while doing the Plaid bank account steps

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33556] opened 2023-12-23 22:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check the Plaid connection in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Create a workspace
4. Start adding a bank account (Connect with Plaid)

## Expected Result:
It shouldn't be visible until the Plaid process is finished

## Actual Result:
Expensify site is visible for a short time while doing the Plaid bank account steps

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7718431a-6aa2-400c-bf8f-dbf7f6b50139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd088023ec934a0c</li>
        <li>Upwork Job ID: 1738686198818414592</li>
        <li>Last Price Increase: 2024-01-06</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-12-25 21:55
I dont think this is a deploy blocker but leaving this open to check into the root cause

**Comment by s77rt** [comment] 2023-12-26 17:48
This seems to be dependent on the selected bank. I tried to reproduce this but it worked just fine. Either way I think we should close this.

https://github.com/Expensify/App/assets/16493223/de6ffa11-c95a-44e8-b960-706d1eb1144a

**Comment by s77rt** [comment] 2023-12-29 16:11
Not overdue. To be closed

**Comment by s77rt** [comment] 2024-01-01 11:19
Same ^

**Comment by s77rt** [comment] 2024-01-03 20:33
Same ^ To be closed

**Comment by s77rt** [comment] 2024-01-06 20:26
@anmurali or @hayata-suenaga Can you please close this? (not a bug)

**Comment by hayata-suenaga** [comment] 2024-01-08 16:18
sorry I have been OOO. Yes I agree we can close this

**Closed by hayata-suenaga** 2024-01-08 16:18 UTC
Labels: External, Engineering, Daily, Help Wanted
