### ISSUE TITLE
[HOLD for payment 2024-06-11] [Wave Collect] [Xero] Disable Taxes when connecting to QBO that doesn't enable Taxes by default

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42466] opened 2024-05-22 10:57 UTC
We need to remove `Taxes` from the LHN when we're disconnecting from Xero and we had taxes sync enabled.

**Comment by mountiny** [comment] 2024-06-04 12:14
@trjExpensify based on the comment this was not fully fixed, I think we need to find someone to look into this / retest and fix if its not done yet https://github.com/Expensify/App/pull/42467#issuecomment-2142992295

**Comment by trjExpensify** [comment] 2024-06-04 12:48
Cool, I can retest after the next deploy.

**Comment by trjExpensify** [comment] 2024-06-11 17:42
Can't repro this. Asking for a retest.

**Comment by trjExpensify** [comment] 2024-06-18 09:19
Still waiting for a retest. CC: @mvtglobally @m-natarajan

**Comment by lakchote** [comment] 2024-07-01 08:25
@mvtglobally @m-natarajan can you please retest as per @trjExpensify's [comment](https://github.com/Expensify/App/issues/42466#issuecomment-2175617512) above ?

**Comment by kbecciv** [comment] 2024-07-01 16:20
By following steps from https://github.com/Expensify/App/issues/42466#issuecomment-2147590323 - Taxes are enabled when connecting to QBO

https://github.com/Expensify/App/assets/93399543/09dedcc9-f6b0-4217-8646-1bf2f9eb12ce

**Comment by lakchote** [comment] 2024-07-02 14:50
> #42466 (comment)

I found the culprit, and pushed a PR to fix it [here](https://github.com/Expensify/App/pull/44736)

cc @trjExpensify once you'll see why we weren't seeing the bug... ah 😄

**Comment by trjExpensify** [comment] 2024-07-02 15:14
Dang, nice sleuthing!

**Comment by mvtglobally** [comment] 2024-07-03 15:01
Issue is reproducible during KI retests.

**Comment by lakchote** [comment] 2024-07-08 11:21
> Fix disconnect QBO on native devices #44952

[PR](https://github.com/Expensify/App/pull/44952) to fix this is up for review.

**Comment by allroundexperts** [comment] 2024-07-08 20:31
Comment for assignment

**Comment by bondydaa** [comment] 2024-07-08 20:32
assigned @allroundexperts since they're helping to test the PR https://github.com/Expensify/App/pull/44952

**Comment by trjExpensify** [comment] 2024-07-24 23:16
The regression period is over on this. Confirming payment summary as follows:

- $250 to @allroundexperts for the C+ review

Go ahead and request! Closing.

**Closed by trjExpensify** 2024-07-24 23:16 UTC
Labels: Reviewing, Engineering, Weekly, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-10-04 11:04
$250 approved for @allroundexperts
