### ISSUE TITLE
IOS - New message label Concierge message (whisperer) is overlapped

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22427] opened 2023-07-07 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Account A starts a new chat with other new account
2. Account A will received a message from Concierge - the  whisperer with the label “Only visible to you”
3. Long press on the Concierge’s message and select Reply in thread
4. Concierge will response with new message
5. Long press on the new message and select “Mark as unread”
6. Check the New label on that message

## Expected Result:
The New label should not be overlapped with other content

## Actual Result:
The New label is overlapped with previous message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/87a83b45-46ba-455f-bf78-ca7442bfe70f

https://github.com/Expensify/App/assets/93399543/552d1eeb-02d3-4aaf-9012-93b5153d02c2

![IMG_4289](https://github.com/Expensify/App/assets/93399543/f7a492fa-0945-46bb-bc2d-b6cff3108f9a)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688664187109959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-07-07 14:25
dupe of https://github.com/Expensify/App/issues/20451

**Comment by trjExpensify** [comment] 2023-07-10 10:40
Agree this is a dupe, closing!

**Closed by trjExpensify** 2023-07-10 10:40 UTC
Labels: Daily, Overdue, Bug
