### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] text cannot be wrapped in < > , in welcome message in new room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20874] opened 2023-06-15 21:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to a new room -> give a valid name and create it.
2. got to room settings
3. Go to the welcome message
4. Type the following :
     < code >
Notice that the prompt says invalid character.
## Expected Result: 
Ability to wrap text inside angle brackets . i.e
< code > should be a valid welcome message.
## Actual Result: 
text cannot be wrapped in < > , in welcome message in new room

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a90c3e78-f218-4928-93ff-fdc25ec6cf66

<img width="957" alt="Screenshot (367)" src="https://github.com/Expensify/App/assets/43996225/9281fa3c-c81f-4dd5-889d-57eb523f6d89">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686300197977749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc4ef19a44f6c31f</li>
        <li>Upwork Job ID: 1671498328823910400</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by ashimsharma10** [comment] 2023-06-16 12:05
Dear All, 
Such issue occurs throughout the application , like in invite text ( while adding members in workspace) and also while closing account. 
![Screenshot_2023-06-16-17-47-48-12_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/43598308/72a69a26-d919-4182-ac71-d59076114fc9)

**Comment by flaviadefaria** [comment] 2023-06-20 20:54
I'll handle this tomorrow.

**Comment by matsp41** [comment] 2023-06-21 18:52
Make sure you know the specific reason on why this problem was added in the first place before removing it. Letting users fill in html tags can also be a bad thing., they can do stuff like <script></script>. So make sure this is no issue

**Comment by narefyev91** [comment] 2023-06-22 07:54
Proposal of @hoangzinh https://github.com/Expensify/App/issues/20874#issuecomment-1593890453 - looks good for me, It's correctly indicate a root case - our regexp is too strict, we need to correctly identified html tags
🎀 👀 🎀 C+ reviewed

**Comment by iwiznia** [comment] 2023-06-22 19:02
hmmmm I would think that the solution is to remove that constrain from the backend and the frontend, no @narefyev91 @hoangzinh ?

**Comment by narefyev91** [comment] 2023-06-23 06:51
> hmmmm I would think that the solution is to remove that constrain from the backend and the frontend, no @narefyev91 @hoangzinh ?

I think we should have validation to prevent sending any real html tags (to be save in case it will be any script injections), but have less strict check

**Comment by ShogunFire** [comment] 2023-06-24 23:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We don't allow < > in multiple inputs in the app

### What is the root cause of that problem?

The regex for html is too restrictive here:
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/CONST.js#L755


### What changes do you think we should make in order to solve the problem?

We can specifically search for any html tag that exist inside "< >" as long as it's a standalone word
`<[ \n]*(br|basefont|hr|input|source|frame|param|area|meta|!--|col|link|option|base|img|wbr|!DOCTYPE|a|abbr|acronym|address|applet|article|aside|audio|b|bdi|bdo|big|blockquote|body|button|canvas|caption|center|cite|code|colgroup|command|datalist|dd|del|details|dfn|dialog|dir|div|dl|dt|em|embed|fieldset|figcaption|figure|font|footer|form|frameset|head|header|hgroup|h1|h2|h3|h4|h5|h6|html|i|iframe|ins|kbd|keygen|label|legend|li|map|mark|menu|meter|nav|noframes|noscript|object|ol|optgroup|output|p|pre|progress|q|rp|rt|ruby|s|samp|script|section|select|small|span|strike|strong|style|sub|summary|sup|table|tbody|td|textarea|tfoot|th|thead|time|title|tr|track|tt|u|ul|var|video)([ \n]+.*)*>`

Test:
- <    script  > => MATCH
- <script vg> => MATCH
- \<scriptvg>  => DON'T MATCH
- \<toto>       => DON'T MATCH


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by flaviadefaria** [comment] 2023-06-26 13:52
@narefyev91 what's the latest here? Do we have a final proposal?

**Comment by iwiznia** [comment] 2023-06-26 16:58
> I think we should have validation to prevent sending any real html tags (to be save in case it will be any script injections), but have less strict check

Why? Sending HTML is completely valid. What's not correct is rendering the HTML as HTML tags.

**Comment by iwiznia** [comment] 2023-06-26 17:16
Is that code that applies to any form? That seems wrong to me (though not 100% sure)

> We can send html in the report comment, maybe we can do the same here ?

Yeah, we definitely send HTML in comments already.

**Comment by ShogunFire** [comment] 2023-06-26 23:42
## Proposal
[Updated](https://github.com/Expensify/App/issues/20874#issuecomment-1605781746)

**Comment by ShogunFire** [comment] 2023-06-26 23:44
For context, I found the issue and the PR responsible for the current behaviour:

Issue: https://github.com/Expensify/App/issues/14610

PR: https://github.com/Expensify/App/pull/15315

**Comment by iwiznia** [comment] 2023-06-27 17:13
Damn, I am not sure what to do. Seems this is kind of wrong already, so let's just update the regex to be a bit less wrong and move on.

**Comment by flaviadefaria** [comment] 2023-07-10 20:34
@narefyev91 please fill out the comment above so that I can issue payment. Thanks!

**Comment by narefyev91** [comment] 2023-07-11 07:20
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21821
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments were addressed
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussion happened
- Determine if we should create a regression test for this bug - i think we fully good with test cases inside merged PR

**Comment by flaviadefaria** [comment] 2023-07-13 15:58
>Determine if we should create a regression test for this bug - i think we fully good with test cases inside merged PR

@narefyev91 so just to confirm you think we should create a regression test, right? Can you post the test cases from the PR here so that it's easy to identify them? Thanks!

**Comment by flaviadefaria** [comment] 2023-07-14 09:41
Previously @narefyev91 had written so I guess that got me confused:
>The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21821

Updated amounts below, I'll send the offers now:
@ashimsharma10 = $250 reporting bonus
@hoangzinh = $1000 + $500 (bonus) = $1500
@narefyev91 = $1000 + $500 (bonus) = $1500

**Comment by flaviadefaria** [comment] 2023-07-14 09:47
@ashimsharma10 I see more than 1 UW profile for Ashim S can you please link your profile here so that I don't send the offer to the wrong one? Thanks!

@narefyev91 I can't find you in UW can you please send me your profile link? Thanks!

**Comment by narefyev91** [comment] 2023-07-14 10:17
> @ashimsharma10 I see more than 1 UW profile for Ashim S can you please link your profile here so that I don't send the offer to the wrong one? Thanks!
> 
> @narefyev91 I can't find you in UW can you please send me your profile link? Thanks!

@flaviadefaria No worries - I'm from Callstack - no needs for any additional payments :-)

**Comment by ashimsharma10** [comment] 2023-07-14 13:56
@flaviadefaria This is my upwork. https://www.upwork.com/freelancers/~018a92cf13e1e88eed

**Comment by ashimsharma10** [comment] 2023-07-17 08:37
@flaviadefaria haven't got any offer.

**Comment by flaviadefaria** [comment] 2023-07-17 08:59
Ah thanks for clarifying @narefyev91! @ashimsharma10 I just sent you the offer.

**Closed** 2023-07-17 08:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
