### ISSUE TITLE
 Scan - "Receipt scanning failed" is shown when "Unknown merchant" is not considered an error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33418] opened 2023-12-21 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33220
## Action Performed:
1. Create a Scan request using a receipt with Amount but no Merchant
2. When smartscanning is complete, open request details view

## Expected Result:
Since "Unknown merchant" is no longer considered an error, it will not show "Receipt scanning failed" message

## Actual Result:
It still shows "Receipt scanning failed" message when "Unknown merchant" is not considered an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6322794_1703169662003!bandicam_2023-12-21_21-09-28-161](https://github.com/Expensify/App/assets/78819774/f0f0075f-2a07-4897-b208-fa8d4cf54078)

 
![Bug6322794_1703169661975!receipt_no_merchant](https://github.com/Expensify/App/assets/78819774/d8a4a8ac-5119-444b-8846-25ec4de33cb0)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2023-12-22 03:15
It looks like this error is being displayed here: https://github.com/Expensify/Auth/blob/main/auth/command/EditMoneyRequest.cpp#L375-L403

@Gonals @sobitneupane is this the expected behavior when the user selects "Merchant is unclear"? I feel like it's a bit awkward, since they already specified that they weren't able to get a merchant from the receipt.

Regardless, I'm not going to block deploy on this–this can be fixed in a subsequent PR.

**Comment by Gonals** [comment] 2023-12-27 10:40
> It looks like this error is being displayed here: https://github.com/Expensify/Auth/blob/main/auth/command/EditMoneyRequest.cpp#L375-L403
> 
> @Gonals @sobitneupane is this the expected behavior when the user selects "Merchant is unclear"? I feel like it's a bit awkward, since they already specified that they weren't able to get a merchant from the receipt.
> 
> Regardless, I'm not going to block deploy on this–this can be fixed in a subsequent PR.

You are very right. I'll fix that

**Comment by Gonals** [comment] 2024-01-04 11:59
This is done

**Closed by Gonals** 2024-01-04 11:59 UTC
Labels: Reviewing, Engineering, Daily, Improvement
