### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [HOLD Mentions v2] Support mentions in editing comments

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#39550] opened 2024-04-03 20:13 UTC
We want to update the edit comment flow to support editing/adding mentions. This does not mean adding support for the auto-complete component. Just parsing the mentions in both directions. This means that when someone goes to edit a comment with a user or report mention we should: 
1. convert that from html to markdown so that it can be edited
2. perform the proper markdown to html conversion when the edited comment is saved so that if mentions have been added/removed we properly send that to the API 

This is covered in the mentions v2 design doc [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#heading=h.llsjbn9eeufr).

HOLD for https://github.com/Expensify/App/issues/39549 

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by MitchExpensify** [comment] 2024-04-15 22:02
Held on https://github.com/Expensify/App/issues/39549

**Comment by puneetlath** [comment] 2024-04-19 15:10
Sounds good. Just FYI, the back-end for this hasn't been done yet.

**Comment by war-in** [comment] 2024-04-30 09:09
@puneetlath any update on the backend? I think my PR works as expected but would like to get confirmation from your side :)

**Comment by puneetlath** [comment] 2024-04-30 13:25
Not yet! Will probably be a few more days before I can start the back-end. Are you ready for a review?

**Comment by war-in** [comment] 2024-05-06 09:31
Yup, already marked PR as ready for review, but I wonder if the backend is a blocker for this 🤔 If not I'll notify the reviewer :)

**Comment by war-in** [comment] 2024-05-10 08:05
> Yup, already marked PR as ready for review, but I wonder if the backend is a blocker for this 🤔 If not I'll notify the reviewer :)

@puneetlath kind bump :)

**Comment by puneetlath** [comment] 2024-05-10 19:44
Does it work without the back-end? Like when you refresh the page, is it still shown as mentions?

**Comment by war-in** [comment] 2024-05-13 11:12
@puneetlath Yup, you can see it here or in the PR description :)

https://github.com/Expensify/App/assets/61014013/70ac925c-460d-443a-8bed-7ae3d58b3d25

**Comment by Beamanator** [comment] 2024-05-14 11:16
@war-in are you aware of some "Cannot read properties of undefined (reading '`accountIDToName`')" errors ? I believe a few people are seeing this, not sure exactly the flow

**Comment by iwiznia** [comment] 2024-05-14 15:14
Putting all the details in slack here https://expensify.slack.com/archives/C04878MDF34/p1715699038416249 please @war-jump there if you can, as this is breaking the app in production

**Comment by war-in** [comment] 2024-05-17 08:22
@puneetlath @Beamanator mentioned issue will be resolved in [this PR](https://github.com/Expensify/App/pull/42176). Can I mark mine as ready for review? I've shown [here](https://github.com/Expensify/App/issues/39550#issuecomment-2107297437) that it works without the backend

**Comment by puneetlath** [comment] 2024-05-21 19:20
Yes, sounds good for me. Let's get it in review.

**Comment by MitchExpensify** [comment] 2024-06-11 03:53
this looks like it can be closed at this point

**Comment by war-in** [comment] 2024-06-11 09:24
Hi @MitchExpensify 
Sorry for not updating here 🙏 We are working on the PR closing this issue [here](https://github.com/Expensify/App/pull/40565#issuecomment-2158979897) (updates were posted there)

**Comment by war-in** [comment] 2024-06-17 16:22
@puneetlath I think we can close it now since #40565 was merged :)

**Comment by puneetlath** [comment] 2024-06-17 18:36
@rlinoz mind confirming that we're all done here?

**Comment by rlinoz** [comment] 2024-06-17 19:07
Let's wait until it gets deployed to prod, but also we might have a case we didn't account for https://github.com/Expensify/App/issues/42521#issuecomment-2173848054

**Comment by rlinoz** [comment] 2024-06-18 13:46
@eh2077 was the C+

**Comment by MitchExpensify** [comment] 2024-06-19 23:16
**Payment summary:**

- $250 C+ @eh2077 (Upwork)

**Comment by eh2077** [comment] 2024-07-01 11:32
### Checklist

- [x] [@eh2077] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases. _**This is a new feature and I don't think we need a regression test here**_

**Comment by MitchExpensify** [comment] 2024-07-01 21:02
@eh2077 Upwork job created here: https://www.upwork.com/jobs/~012066a1fb40a4a923, offer sent!

**Comment by MitchExpensify** [comment] 2024-07-02 23:44
Paid and contract ended

**Closed by MitchExpensify** 2024-07-02 23:44 UTC
Labels: Daily, NewFeature, Awaiting Payment
