### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] Bank account - User is able to edit account number but the change does not take affect

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49786] opened 2024-09-26 12:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/5009304
**Email or phone of affected tester (no customers):** applausetester+vd_ios092524@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must have created a Workspace and have enabled Workflows
1. Go to Settings > Workspaces > Workspace > Workflows
2. Click on "Connect bank account"
3. Select "Connect manually"
4. Enter "011401533" in routing number field
5. Enter "1111222233334444" in account number field and confirm
6. Go back by clicking on the arrow on the top left of the modal
7. Verify the user is able to edit the account number
8. Delete the "4444" part and enter "1111", then confirm
9. Go back again
10. Verify the account number has not changed

## Expected Result:
Behavior should be consistent, if the user is able to edit the account number, the change should take affect

## Actual Result:
Behavior is not consistent, the user is able to edit the account number but the changed does not take effect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/43b732e6-cb79-44e9-9a33-c43233db4eef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840583568266999203</li>
        <li>Upwork Job ID: 1840583568266999203</li>
        <li>Last Price Increase: 2024-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104229719</li>
<li>DylanDylann | Contributor | 104533160</li>
<li>cretadn22 | Contributor | 104533363</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by bernhardoj** [comment] 2024-09-26 13:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account number is editable but reverted to previous value when saved.

### What is the root cause of that problem?
When we try to edit the bank account number, the BE will return back the previous entered value.
<img width="380" alt="image" src="https://github.com/user-attachments/assets/22692067-d247-478c-b90d-cd80bfcdf78f">

So, it looks like we are not allowed to change the number after we entered it and need to start over the process.

### What changes do you think we should make in order to solve the problem?

Disable the bank account number field if we already entered it. We can check using `hasBankAccountData` to disable it.
https://github.com/Expensify/App/blob/da37289fe24c8d92cdf63da9de7320b7c3f08bca/src/pages/ReimbursementAccount/BankInfo/substeps/Manual.tsx#L78-L101

```
disabled={hasBankAccountData}
```

**Comment by suneox** [comment] 2024-09-30 06:26
@jliexpensify  I would like to confirm if we allow users to edit their bank account numbers during the setup process.  If not, we should disable the account bank number field when editing. If we do allow editing, the backend needs to be updated to handle this, and the frontend also validate the bank account number when edit to avoid submitting data with placeholders like `XXXXXXXXXXXX1111`.

![Screenshot 2024-09-30 at 13 08 08](https://github.com/user-attachments/assets/ce3be3bd-f18a-4e20-8295-9323fb84419f)

**Comment by jliexpensify** [comment] 2024-09-30 09:59
Great call out @suneox - I am not sure myself. It makes sense that you should be able to edit, in case you make a mistake - but actually, on Old.Dot, I don't think you can so maybe the behaviour mirrors this? 

Asking - https://expensify.slack.com/archives/C036QM0SLJK/p1727690352864979

**Comment by KashifAhmed** [comment] 2024-09-30 20:46
![image (1)](https://github.com/user-attachments/assets/1ab9ceea-956c-43fd-86b2-e948c66f33e4)


I’d recommend adding a "Start Over" button and disabling both fields when necessary. Otherwise, on the server side, we can update the new value and ensure the old value isn't retained. This should make the user experience smoother.

**Comment by KashifAhmed** [comment] 2024-09-30 20:51
Contributor details
Your Expensify account email: imrkash@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/imrkash

**Comment by jliexpensify** [comment] 2024-10-01 00:34
Got a quick update @suneox - we want to mirror the behaviour of Expensify Classic for editing bank accounts, which is the ability to edit the account number prior to it being verified. Can you evaluate based off this?

[(Slack thread for internal engineer's reference)](https://expensify.slack.com/archives/C036QM0SLJK/p1727690352864979)

Also, I am OOO from the 3rd to 14th October, but going to keep myself assigned as I don't think payment will be needed before the 14th.

**Comment by suneox** [comment] 2024-10-01 05:15
> which is the ability to edit the account number prior to it being verified. Can you evaluate based off this?

@jliexpensify If we want to allow users to edit the account number, BE needs to accept  the new value via the `ConnectBankAccountManually` API, instead of retaining the previous value. On the frontend (FE), we will handle preventing the submission of invalid account numbers with patterns like XXXXX....


https://github.com/user-attachments/assets/ed9af829-e8bf-4572-8a56-d44e4d816391



cc: @bernhardoj  @cretadn22  We're waiting updated proposal for preventing the submission of invalid account numbers

**Comment by bernhardoj** [comment] 2024-10-01 05:39
> we want to mirror the behaviour of Expensify Classic for editing bank accounts, which is the ability to edit the account number prior to it being verified.

I think the point here is that we don't want to allow the user to edit the number if it's verified. In Expensify Classic, the number will be verified after submitting "Company information".
<img width="912" alt="image" src="https://github.com/user-attachments/assets/a09855a2-3eaa-4e58-baf0-ae6eb66c1bd2">

But in New Expensify, the number is immediately verified. So, if we disable it using `hasBankAccountData`, the behavior will be the same with Expensify Classic. This is the behavior too before this PR https://github.com/Expensify/App/pull/48767.

**Comment by jliexpensify** [comment] 2024-10-01 05:41
Oh interesting @bernhardoj, so are you saying if we count this issue as a bug, then this is technically a regression from https://github.com/Expensify/App/pull/48767?

**Comment by jliexpensify** [comment] 2024-10-01 09:42
Great, thanks!

Assigning @mountiny to this issue for review - it looks like https://github.com/Expensify/App/pull/48767 changed the behaviour of the account flow, [but it now doesn't mirror Classic.](https://github.com/Expensify/App/issues/49786#issuecomment-2384554040)

Is this intended? It sounds like we want to keep the flows the same.

**Comment by suneox** [comment] 2024-10-01 14:46
@jliexpensify  In the manual bank connection flow from oldDot users can still edit their account numbers. 

https://github.com/user-attachments/assets/3cb98588-34fa-4a3b-96e5-f562c4d75383

It seems that @bernhardoj may be using the online connection method and users cannot edit their account numbers.
So, I think the scope of this issue should handle disabling the account number edit option when connecting online and allowing edits when connecting manually.

**Comment by bernhardoj** [comment] 2024-10-01 14:47
> In Expensify Classic, the number will be verified after submitting "Company information".

I'm doing the manual flow. You need to submit the Company Information first

**Comment by suneox** [comment] 2024-10-01 15:21
> I'm doing the manual flow. You need to submit the Company Information first

Ah, I got it. But in NewDot the company information step runs after verifying with Onfido, so I think the user should be able to edit their own information before the verification process.

Anyway, we're still waiting new confirmation from internal team instead of [this one](https://github.com/Expensify/App/issues/49786#issuecomment-2384554040)

**Comment by mountiny** [comment] 2024-10-02 11:57
Ah yeah I believe @koko57 might be working on making the fields uneditable, is that right?

**Comment by koko57** [comment] 2024-10-02 12:03
yes, these fields should not be editable (check this [comment](https://github.com/Expensify/App/issues/49447#issuecomment-2373942169) for reference). They're disabled in this PR https://github.com/Expensify/App/pull/49687

**Comment by mountiny** [comment] 2024-10-02 12:17
handled in the PR from @koko57 making this weekly

**Comment by koko57** [comment] 2024-10-11 04:33
the PR https://github.com/Expensify/App/pull/49687 was merged, so this issue can be retested and closed. Now the inputs won't be editable

**Comment by suneox** [comment] 2024-10-11 06:19
> the PR #49687 was merged, so this issue can be retested and closed. Now the inputs won't be editable

The input can still be edited during the manual connection flow, and the value retains the previous input after submit.

https://github.com/user-attachments/assets/c25332ce-6615-450d-898d-c45bf9da01b3

**Comment by koko57** [comment] 2024-10-11 06:32
@suneox during the manual connection? You haven't started the connection via Plaid? The inputs were disabled for a case when we're connecting via Plaid and going back shows you a step for manual connection.

**Comment by suneox** [comment] 2024-10-11 07:28
> @suneox during the manual connection? You haven't started the connection via Plaid? The inputs were disabled for a case when we're connecting via Plaid and going back shows you a step for manual connection.

I got it! I’ve just reproduced the actions performed for this issue and would like to confirm the expected behavior. When connecting manually, should we allow users to edit the account number after saving and going back?

cc: @jliexpensify @mountiny

**Comment by koko57** [comment] 2024-10-11 07:35
@suneox ok, sorry my mistake, I was focused on my case with Plaid connection - so the inputs should be disabled for both manual and Plaid connection, is that right? If so I can make a PR for that

**Comment by koko57** [comment] 2024-10-11 13:34
I'll be ooo 14-15 Oct (Mon-Tue) so if you confirm that we need to disable the inputs for manual flow as well and it's necessary to raise a PR for that earlier you can ping Callstack team.

**Comment by suneox** [comment] 2024-10-11 16:21
I’m not sure about the current expected behavior for this issue. If we decide to disable it for both cases, we can proceed with @bernhardoj  [proposal](https://github.com/Expensify/App/issues/49786#issuecomment-2376952296). So let’s wait for confirmation from the internal team

**Comment by mountiny** [comment] 2024-10-14 10:12
For manual flow it makes sense to let the user still edit it.

**Comment by koko57** [comment] 2024-10-16 07:55
So what are the next steps here?

**Comment by jliexpensify** [comment] 2024-10-16 08:07
Sorry, coming back from OOO - for Plaid connections, I posted the desired behaviour [here](https://github.com/Expensify/App/issues/49786#issuecomment-2384554040): we want users to be able to edit the account numbers before any sort of verification happens.

Tagging in @joekaufmanexpensify @anmurali for the manual case - when adding an account manually, at what point do we "lock" the details? I would assume that we'd always be able to go back and manually edit a bank account until the details are saved.

**Comment by mountiny** [comment] 2024-10-16 09:32
@jliexpensify I remember from discussing with @nkuoch that we do not allow you to edit the details if you have started the flow through plaid - then we lock the account and routing number to those from plaid and if you exit the flow and come back, you are in the manual flow with those locked in numbers. You would have to restart the flow to be able to edit them.

if you start in manual flow, you can edit the numbers.

I do not have much background on that though.

**Comment by joekaufmanexpensify** [comment] 2024-10-16 13:01
Hmm, yeah I am not quite sure when we perform the actual API verification on the account and routing numbers. But what Vit said above makes sense to me. If the account/routing come from Plaid, you shouldn't be able to edit them. (I think there is a special case with Chase bank, where even if you connect with Plaid, we ask you to manually enter account and routing, as Chase only passes us dummy account/routing numbers). 

But if you add the account manually, being able to edit them up until we verify them via API makes sense to me. We could maybe even allow editing them even after we initially call the API to check them, we'd just need to rerun the API check again. 

Once the bank account has been verified by our team (meaning it is moved from the `verifying` to `pending`/`open` state), we definitely shouldn't allow them to be edited anymore.

**Comment by nkuoch** [comment] 2024-10-18 06:05
No matter if it's from plaid or manually, once it's been inserted in db (by calling `ConnectBankAccountWithPlaid` or `ConnectBankAccountManually`), Back End will prevent modifying the account numbers. So Front End should do the same.

**Comment by mountiny** [comment] 2024-10-18 07:17
Thanks! Ok that clarifies the behaviour then. @koko57 would you be willing to take this one?

**Comment by koko57** [comment] 2024-10-18 08:23
@mountiny yes, of course!

**Comment by mountiny** [comment] 2024-10-22 10:02
@suneox sorry adding @DylanDylann who was working on the workspace feeds project as the main c+ here to help choose the right proposal now that we figured out the correct behaviour

**Comment by DylanDylann** [comment] 2024-10-22 10:08
Let's go with @cretadn22's [proposal](https://github.com/Expensify/App/issues/49786#issuecomment-2377019563) if we want to disable both routing number and bank account. I prefer this because we just did that on PLAID flow

If we only want to disable the bank account, let's go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/49786#issuecomment-2376952296) because they go first

🎀 👀 🎀 C+ reviewed

**Comment by mountiny** [comment] 2024-10-22 10:12
@cretadn22 what is your eta for the PR?

**Comment by DylanDylann** [comment] 2024-10-22 10:12
@cretadn22 Please help to raise a quick PR

**Comment by bernhardoj** [comment] 2024-10-22 10:45
> If we only want to disable the bank account, let's go with @bernhardoj's https://github.com/Expensify/App/issues/49786#issuecomment-2376952296 because they go first

Hmm, I didn't explicitly mention both the account and routing number, but you can see in my proposal that I include the routing number too from the permalink.

<img width="879" alt="image" src="https://github.com/user-attachments/assets/cf6e3ecd-0498-4367-8200-c27adf061323">

**Comment by DylanDylann** [comment] 2024-10-22 11:19
@bernhardoj I appreciate your contribution. If we have the same case in the future, please help to elaborate it by word for a clear and enough proposal

**Comment by jliexpensify** [comment] 2024-10-25 02:33
Ok, little bit confusing - but is this Payment Summary correct?

- C: @cretadn22 $250 (to be paid via Upworks)
- C+: @DylanDylann $250 (to be paid via ND)

**Comment by DylanDylann** [comment] 2024-10-30 15:36
@jliexpensify Done

**Comment by jliexpensify** [comment] 2024-10-31 01:55
Thanks, any checklist needed here @DylanDylann?

**Comment by DylanDylann** [comment] 2024-10-31 03:42
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: This is more like a new requirement, not a bug
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
Pre-requisite: user must have created a Workspace and have enabled Workflows

1. Go to Settings > Workspaces > Workspace > Workflows
2. Click on "Connect bank account"
3. Select "Connect manually"
4. Enter "011401533" in routing number field
5. Enter "1111222233334444" in account number field and confirm
6. Go back by clicking on the arrow on the top left of the modal
7. Verify both routing number and bank account are disabled


Do we agree 👍 or 👎

**Comment by DylanDylann** [comment] 2024-10-31 03:43
@jliexpensify Posted the checklist

**Comment by jliexpensify** [comment] 2024-11-04 02:36
Paid both, and job closed.

**Closed by jliexpensify** 2024-11-04 02:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
