### ISSUE TITLE
[HOLD for payment 2023-12-08] [HOLD for payment 2023-12-07] Contact method - App crashes when removing secondary contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32181] opened 2023-11-29 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to Settings > Profile > Contact methods.
3. Go to Contact methods > New contact method.
4. Add a new contact method and save.
5. Tap on the new contact.
6. Remove the new contact method.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari -console error
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bbc582c0-a593-4774-aa66-770d8d463a78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by ZhenjaHorbach** [comment] 2023-11-29 14:18
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Contact method - App crashes when removing secondary contact method

## What is the root cause of that problem?

It looks like when this code is executed, the ref is not yet available
As a result, we turn to a non-existent method

## What changes do you think we should make in order to solve the problem?


We can update code like 

```
                        onModalHide={() => {
                            InteractionManager.runAfterInteractions(() => {
                                this.validateCodeFormRef.current && this.validateCodeFormRef.current.focusLastSelected();
                            });
                        }}
```

## What alternative solutions did you explore? (Optional)
NA

**Comment by dangrous** [comment] 2023-11-29 14:45
Ah, from a PR I reviewed I think. Working on a quick fix

**Comment by dangrous** [comment] 2023-11-29 18:26
PR has been merged, requested a CP

**Comment by dangrous** [comment] 2023-11-29 22:53
This is confirmed fixed on staging! I believe regressions are not paid out, is that correct @situchan? If so I will go ahead and close this.

**Comment by situchan** [comment] 2023-11-29 23:08
> I believe regressions are not paid out

yes correct if regression fixed by offending PR author/reviewer.
I am not involved in original issue / PR so I am still eligible

**Comment by dangrous** [comment] 2023-11-30 18:46
Ah my bad, misread the GH handle! I'll get a BZ for this one.

**Comment by dangrous** [comment] 2023-11-30 18:47
No action right now @garrettmknight, just assigning a BZ for @situchan's review payment once it's time.

**Comment by dangrous** [comment] 2023-12-01 19:40
Checklist updated for when we're ready

**Comment by garrettmknight** [comment] 2023-12-08 17:53
@situchan offer out to you - I'll pay when you accept

**Comment by garrettmknight** [comment] 2023-12-08 17:57
Paid - closing!

**Closed by garrettmknight** 2023-12-08 17:57 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
