### ISSUE TITLE
 iOS - IOU badge icon disappears after user re-login

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10423] opened 2022-08-17 02:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App on device A
1. Send money request to any chat from device B
2. IOU badge icon appeared on the selected chat on device A
3. Log out and log in again on device A

## Expected Result:
The IOU badge icon still shows up in the correct chat

## Actual Result:
The IOU badge icon has disappeared and is no longer visible. The Pay button is still present.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:**  1.1.88-13
**Reproducible in staging?:** Y
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** fischer9966+081622s@gmail.com / Qwerty123
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/185024890-8aecc4bb-909e-421c-b64a-23eb4ba58544.png" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/185024886-27be9d6f-70e4-4d1a-a091-5109c752ffc0.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment] 2022-08-17 12:19
Going to see if someone else can pick this one because I have a hard time bringing my Simulator online.

**Comment by francoisl** [comment] 2022-08-18 17:32
Hi @youssef-lr, were you able to look into this?

**Comment by youssef-lr** [comment] 2022-08-18 17:42
Hi @francoisl. Yes I could reproduce it on the simulator. I was trying this afternoon to go back to previous commits to see when did it break but for some reason I could never `npm install` to work. Still working on it but I'm AFK right now and will be back in a couple of hours.

**Comment by youssef-lr** [comment] 2022-08-19 11:28
The IOU badge does not appear to me at all when running the app locally on any platform. Still looking into it.

<img width="1800" alt="Screen Shot 2022-08-19 at 12 24 52" src="https://user-images.githubusercontent.com/9680864/185608409-4e4d3e8d-a7bb-4eac-90e2-c1062ed84f3c.png">

**Comment by JmillsExpensify** [comment] 2022-08-23 14:42
I don't think this should be a deploy blocker. We are deprecating the IOU badge in an upcoming release.

**Comment by youssef-lr** [comment] 2022-09-28 00:50
No update yet, haven't had the time to look into this.

**Comment by mvtglobally** [comment] 2022-11-03 02:57
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-11-09 03:27
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-11-16 02:08
Issue not reproducible during KI retests. (Third week) Closing

**Closed by mvtglobally** 2022-11-16 02:08 UTC
Labels: Engineering, Monthly, Overdue, Bug

**Comment by JmillsExpensify** [comment] 2022-11-18 07:45
Thanks you for closing!
