### ISSUE TITLE
Request Money - Text written with line breaks is connected together when Editing Description

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26279] opened 2023-08-30 12:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat.
2. Click the (+) icon > click request money.
3. On description input write something with a line break.
4. Click on Save> Request Money
5. Go to the Money Request thread and Notice that the Description Text with linebreaks is shown properly.
6. Click on the description to edit. Notice that text written with line breaks a connected together.

## Expected Result:
Text written with line breaks is not connected together.

## Actual Result:
Text written with line breaks is connected together.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.59-0

**Reproducible in staging?:** Y

**Reproducible in production?:**  N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b0bb9c84-cb1e-4709-a736-571f0bbbeb16

https://github.com/Expensify/App/assets/115492554/75b17b84-1517-4890-ab48-70259c2ef8c5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693375111880949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-08-30 13:03
It seems dupe of https://github.com/Expensify/App/issues/25494

**Closed** 2023-08-30 13:16 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
