### ISSUE TITLE
Web - Workspace name missing after #announce or #admins

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22647] opened 2023-07-11 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace if not created
2. Check workspace name in LHN

## Expected Result:
It should show workspace name after #announce or #admins to identify policy

## Actual Result:
The workspace name missing after #announce or #admins

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-11 at 7 02 40 PM](https://github.com/Expensify/App/assets/93399543/9e4bfe1d-535b-4288-87fb-d3197198f390)

https://github.com/Expensify/App/assets/93399543/edb5fa6f-8e1d-4890-99d1-03facb7238e6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689081311895289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cubuspl42** [comment] 2023-07-11 15:37
Not reproducible on `main`, so I guess we'll have to wait for a deployment?

**Comment by cubuspl42** [comment] 2023-07-11 16:05
This is from https://github.com/Expensify/App/pull/20512. The specific commit is `6bc4f8c27c658fa4836b13d687a75182b93b11b6`. The change looks intentional, but I cannot understand the reasoning.

**Comment by cubuspl42** [comment] 2023-07-11 16:11
@0xmiroslav @grgia Pragmatically speaking, how is the user expected to know which workspace is which?

My workspaces look like this now:

![image](https://github.com/Expensify/App/assets/2590174/b0fdd248-73d4-43e4-8a1d-a0b98b85dcc5)

I know that we, the contributors and testers, are not typical real users, but now I'm basically left with colors to distinguish my workspaces.

And I'm colorblind.

**Comment by shawnborton** [comment] 2023-07-11 16:19
Keep in mind that most people will only have one workspace, and people can also upload a custom avatar.

**Comment by bondydaa** [comment] 2023-07-11 16:59
coolio sounds like this isn't a blocker and is expected then. 

Once https://github.com/Expensify/App/pull/20512 goes to prod it'll post the comment about updating testing steps so let's make sure we get those updated.

Going to close this out for now.

**Closed by bondydaa** 2023-07-11 16:59 UTC
Labels: DeployBlockerCash, Engineering, Hourly
