### ISSUE TITLE
[$500] mWeb - Settings > Workspaces - The loading screen is not being displayed from the beginning on the 'Connect Bank Account' page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28239] opened 2023-09-26 08:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging
2. Navigate to Settings > Workspaces and select any Workspace.
3. Choose "Cards" > Connect bank account
4. The loading screen is not displayed from the beginning

## Expected Result:
The loading screen should be initially displayed, as it is on other platform

## Actual Result:
Loading screen appears after a few ms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.74-2 

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/457d8360-ad94-4b01-a323-31c5e40d68dd

https://github.com/Expensify/App/assets/115492554/d72e577b-efcf-4e3b-a301-67780271ea02

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aman-atg

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695551201158969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c41f32fc44c2ffd</li>
        <li>Upwork Job ID: 1706590125107269632</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-09-26 09:05
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
the isLoadingReportData is by default false here /src/pages/ReimbursementAccount/reimbursementAccount.js
```javascript
const defaultProps = {
    reimbursementAccount: ReimbursementAccountProps.reimbursementAccountDefaultProps,
    reimbursementAccountDraft: {},
    onfidoToken: '',
    plaidLinkToken: '',
    isLoadingReportData: false,
    account: {},
    session: {
        email: null,
    },
    route: {
        params: {
            stepToOpen: '',
            policyID: '',
        },
    },
};
``` 
### What changes do you think we should make in order to solve the problem?
Just need to change the isLoadingReportData as true in default props, that way loading screen will be enabled by default.
The solution would look something like this

```javascript
const defaultProps = {
    reimbursementAccount: ReimbursementAccountProps.reimbursementAccountDefaultProps,
    reimbursementAccountDraft: {},
    onfidoToken: '',
    plaidLinkToken: '',
    isLoadingReportData: true,
    account: {},
    session: {
        email: null,
    },
    route: {
        params: {
            stepToOpen: '',
            policyID: '',
        },
    },
};
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by isabelastisser** [comment] 2023-09-28 14:36
@aimane-chnaif please review the proposal above, thanks!

**Comment by isabelastisser** [comment] 2023-10-02 19:05
Hey @aimane-chnaif can you please review the proposal above? Thanks!

**Comment by saranshbalyan-1234** [comment] 2023-10-03 20:41
hi @aimane-chnaif  could you please check this https://github.com/Expensify/App/issues/28239#issuecomment-1735131456 proposal as well?

**Comment by saranshbalyan-1234** [comment] 2023-10-04 04:42
> @saranshbalyan-1234 yes, checked already. The root cause is not correct.

Oops, and did you try the solution as well? Is it working?

**Comment by isabelastisser** [comment] 2023-10-16 20:39
Hey @aimane-chnaif what's the update here?

**Comment by isabelastisser** [comment] 2023-10-23 16:11
@aimane-chnaif, can this still be reproduced? Let's close this issue if not since we're still waiting for proposals.

**Comment by isabelastisser** [comment] 2023-10-23 16:21
@aman-atg I sent you the offer for reporting the issue, please accept it and I will process the payment.

Closing!

**Closed by isabelastisser** 2023-10-23 16:21 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
