### ISSUE TITLE
[HOLD for payment 2024-04-15] [$750] mWeb - Click on back button from country picker page redirects to wrong page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23725] opened 2023-07-27 11:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem

The country picker in Personal Details > Home Address is made of a component which is controlled in state and it does not have its own route. This was made to simplify reusing the component in various places in the app as its easier to just plug it into some page and let its open/ closed state be controlled from within the parent component as well as take the selected value and save it in the parent form.

This however leads to unexpected navigation behaviour with the back button in browser or in android, because the component is not its own page hence its not a screen in the browser history either.

Now that we got a good solution pattern in place with the `IOUCurrencySelection` component reused for 1. creating money request, 2. Confirming creation of money request and 3. Editing money request amount, all done using the same component and having its own path which allows for correct and predictable navigation.

### Solution

Lets build the Country picker page as we did `IOUCurrencySelection` using its own route accepting `goBack` as url param, and making sure the AddressPage will consume the country picked from the `?country` url param same as we do with `?currency` in the other case.

## Action Performed:
1. Go to Settings > Profile > Personal details > Home address > Country
2. Click back button of device

## Expected Result:
 Should navigates to Home address screen

## Actual Result:
Navigates to Personal details screen

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d13f4059-135f-49cc-83ce-ca87721f93b9

https://github.com/Expensify/App/assets/93399543/c594bd2f-f16a-4f6c-876b-c0b38a1c089d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690380615025549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111fe2b2f552059b7</li>
        <li>Upwork Job ID: 1697712669744525312</li>
        <li>Last Price Increase: 2023-09-28</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 26488219</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-07-27 12:44
@MariaHCD This is not a blocker. This is same for Year picker and similar parts of the form. The Year page or in this case the State or Country picker are not its own route/ page in the stack hence when you click back it takes you to the personal details.

I think its something we might have to look at as a general solution as I think we would like this fixed for consistency, but its not a blocker. 

I will demote this and add it to the navigation follow ups tracking project.

**Comment by MariaHCD** [comment] 2023-07-27 12:48
Perfect, thanks @mountiny! Not familiar with the `NewFeature` assigner, how do we move this issue forward? Will we eventually apply the `External` label here?

**Comment by mountiny** [comment] 2023-07-27 12:53
@MariaHCD I will post this in SWM channel to let the guys know an dI think they will take it

posting NewFeature as I think its more true than bug

**Comment by WoLewicki** [comment] 2023-07-27 13:04
Isn't it the same for web when clicking browser back button @kbecciv ?

**Comment by kbecciv** [comment] 2023-07-28 16:37
Hey @WoLewicki! I only checked mWeb on triaging moment. But let me check on Web in latest build.

**Comment by kbecciv** [comment] 2023-07-28 16:39
Web has the same behaviour as mWeb, please attach the video.

https://github.com/Expensify/App/assets/93399543/cd60b035-94f8-499e-b422-80e51097a372

**Comment by ygshbht** [comment] 2023-07-29 17:12
## Proposal
I could make it a page  https://github.com/Expensify/App/issues/23852#issuecomment-1656723924

**Comment by greg-schroeder** [comment] 2023-07-31 14:53
Posted in the thread to see if SWM is going to take this on or not

**Comment by greg-schroeder** [comment] 2023-07-31 15:16
Assigning @WoLewicki per team discussion

**Comment by WoLewicki** [comment] 2023-08-07 16:30
@mountiny I am not sure what should we do about it really. Even if we hijacked the back button of Android to somehow work in this case, the browser's back button is not going to work correctly if it is not a different url. Maybe we should just leave it as it is? Or introduce some different animation for the pages that are not separate urls, so the users have the feeling that it is desired behavior?

**Comment by mountiny** [comment] 2023-08-15 17:31
Yeah I am honestly not sure about this either. Having it NOT its own page is making the code easier, but this is another complication. 

I guess the best solution would be to figure out how to make these Form pages its own pages and be reusable just fine

**Comment by greg-schroeder** [comment] 2023-08-16 02:13
Hmm - should we loop in some other folks to help decide?

**Comment by mountiny** [comment] 2023-08-16 16:30
@MariaHCD Would you like to do that or should I take over, either way due to other priorities I would make this weekly for sure

**Comment by MariaHCD** [comment] 2023-08-16 16:34
Feel free to take over, @mountiny 🙌🏼

**Comment by puneetlath** [comment] 2023-09-01 14:52
>We had bunch of discussions before when we had it its own page and the problem was reusability, so I think this just boils down to what we prefer more.

Would you mind explaining this a bit more? What reusability problem does it create to make these their own page?

**Comment by mountiny** [comment] 2023-09-01 15:40
@puneetlath The discussions mainly revolved around the Datepicker (selecting a year for example) and basically the way the component has been written before made it complicated to select the value and return it successfully to the previous page if the datepicker was reused in different from (you got Expense date field, date of birth, bank flows etc).

Similarly we had the issue with Currency selector in amount page but @koko57 has refactor the Money request flow and made the Currency selection bit easier to reuse while having its own route.

Hence I think we can come back to working on these as its own pages now that we got a patten in place. 

We would create a new country page which will take the `goBack` param which will be used to know where to navigate when the Country is selected or Up button is clicked. I would say we would have to make it similar as the `IOUCurrencySelection` page.

I will update the OP to correcly describe the problem:

### Problem

The country picker in Personal Details > Home Address is made of a component which is controlled in state and it does not have its own route. This was made to simplify reusing the component in various places in the app as its easier to just plug it into some page and let its open/ closed state be controlled from within the parent component as well as take the selected value and save it in the parent form.

This however leads to unexpected navigation behaviour with the back button in browser or in android, because the component is not its own page hence its not a screen in the browser history either.

Now that we got a good solution pattern in place with the `IOUCurrencySelection` component reused for 1. creating money request, 2. Confirming creation of money request and 3. Editing money request amount, all done using the same component and having its own path which allows for correct and predictable navigation.

### Solution

Lets build the Country picker page as we did `IOUCurrencySelection` using its own route accepting `goBack` as url param, and making sure the AddressPage will consume the country picked from the `?country` url param same as we do with `?currency` in the other case.

**Comment by puneetlath** [comment] 2023-09-01 18:28
Sounds good to me! Let's also do it with the State picker, which is part of that same form.

**Comment by puneetlath** [comment] 2023-09-01 18:31
@lewis-n made a proposal to do that in [this issue](https://github.com/Expensify/App/issues/23852#issuecomment-1689738305), so you could hire him for the job if that works for you. But you guys are in charge of the issue so I'll leave it to you to decide who is best to implement it.

**Comment by daordonez11** [comment] 2023-09-01 20:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Custom navigation causes issues when trying to go back with the native button both browser and android, in this case Country does not send back to home address.

### What is the root cause of that problem?

Navigation is managed custom instead of using React-Navigation library, hence there are 2 modals active at the same time RHP and CountryPicker modal. Instead of calling `hidePickerModal` pressing back on the native button calls the `Navigation.goBack` method.

### What changes do you think we should make in order to solve the problem?
Same as MONEY_REQUEST_CURRENCY, we can create a new option in linkingConfig and create a reusable route that opens the `CountryPicker` as a page instead of a modal. Hence, creating a new `CountrySelectorPage`

### What alternative solutions did you explore? (Optional)
As I have created previously in other proposals we could create a library for handling the native navigation and handling this custom navigations inside of expensify but it is better to keep it standard and create routes. using the navigation library for all scenarios.
I have created proposals using new pages:
https://github.com/Expensify/App/pull/24083 like RHP navigation

Here is old proposal using custom navigation:
https://github.com/Expensify/App/pull/20733/files This does work but is custom code to override navigation.

**Comment by mountiny** [comment] 2023-09-01 20:47
Just making it external then @lewis-n do you also wanna share your proposal?

**Comment by ygshbht** [comment] 2023-09-01 20:48
@mountiny What do you say about https://github.com/Expensify/App/issues/23725#issuecomment-1656792082 ?

**Comment by mountiny** [comment] 2023-09-01 20:52
@ygshbht thanks, could you update the proposal? 

> One solution could be to adjust the behavior of the hidePickerModal function to also dismiss the modal upon closing the country picker. One example is by adding Navigation.dismissModal() to the hidePickerModal function. Or by nullifying the dimensions of the modal's backdrop so click happens on the RHN modal.

I dont think this would solve the browser back button problem, right?

We would like to make it a new page

@parasharrajat can then help decide which proposal is better

**Comment by ygshbht** [comment] 2023-09-01 20:55
Yes, that was specific for that issue. For this issue, I do mention at top to make it page. I didn't describe the process of making it a page because its not a bug and I'm not sure what to describe. It just have to be like other pages. Do you want me to add something anyway?
![image](https://github.com/Expensify/App/assets/65986357/9e05bafe-2bf8-4697-86d3-09721986e991)

**Comment by mountiny** [comment] 2023-09-01 21:02
@ygshbht I see, yeah I am just not sure how @parasharrajat will decide is other proposal will be more detailed than that 😅 I agree that the actual proposal might be quite repeptitive

**Comment by ygshbht** [comment] 2023-09-01 21:16
Yep, the decision might not be very starightforward. Anyway, I have added more details to the proposal for him to review

## Proposal
[Updated](https://github.com/Expensify/App/issues/23725#issuecomment-1656792082)

**Comment by mountiny** [comment] 2023-09-04 10:31
@parasharrajat Please could you review the  proposals above once you get time, thanks!

**Comment by mountiny** [comment] 2023-09-04 11:57
Thanks!

**Comment by ygshbht** [comment] 2023-09-04 12:13
Thanks! @mountiny Do you think the price could be adjusted to $1500? The work here involves a bit more than standard bug fixes. A new page needs to be created, while the existing component must remain in place. Additionally, we'll have to modify the state for handling data on both the new and old pages. Rigorous testing and any required adjustments will be necessary to ensure cross-platform compatibility on all six platforms. In the end, the choice is yours, and I'll happily abide by whatever you think is fair.

**Comment by ygshbht** [comment] 2023-09-05 03:35
@parasharrajat I've created the [PR](https://github.com/Expensify/App/issues/23725#issuecomment-1656792082) if you'd like to review. I'll fill the checklist and the screenshots soon after waking up

**Comment by greg-schroeder** [comment] 2023-09-12 14:15
Looks like additional testing is going on in the linked PR - @parasharrajat appears to be next up based on the last comment: https://github.com/Expensify/App/pull/26742#issuecomment-1710441599

**Comment by mountiny** [comment] 2023-09-18 02:56
@parasharrajat I think it would be great to fix the StatePicker for sure.

Year picker can be a separate issue

**Comment by Nathan-Mulugeta** [comment] 2023-09-18 07:42
Hey @mountiny and @parasharrajat so this means a separate ticket should be created for [this issue](https://expensify.slack.com/archives/C049HHMV9SM/p1694691923038999?thread_ts=1694691923.038999&cid=C049HHMV9SM) right?

**Comment by mountiny** [comment] 2023-09-28 06:32
Increasing the price to 750 lets do the same thing for statePicker in the address page in a new pr

**Comment by ygshbht** [comment] 2023-09-28 09:24
Should I start working on it? Is it $750 + $750 or total of $750 for both Country and State picker?

**Comment by DylanDylann** [comment] 2023-10-06 05:46
This change caused [the regression](https://github.com/Expensify/App/issues/28743). Could you guys help to verify?

**Comment by mountiny** [comment] 2023-10-06 13:28
I would say $750 total because again we are just adding what was implemented for the country, not inventing new thing

And yeah lets prevent crashes

**Comment by ygshbht** [comment] 2023-10-06 13:30
What do you think about https://github.com/Expensify/App/issues/23725#issuecomment-1705164047 https://github.com/Expensify/App/issues/23725#issuecomment-1705182476 @mountiny?

**Comment by mountiny** [comment] 2023-10-06 13:36
@ygshbht I dont think the scope increased so much to triple the price.

Do you want to handle this in the State PR https://github.com/Expensify/App/issues/28743 and total for everything would be $1250?

**Comment by ygshbht** [comment] 2023-10-06 13:38
Yes, it's better

**Comment by mountiny** [comment] 2023-10-06 13:56
Perfect thanks!

**Comment by mountiny** [comment] 2023-10-11 14:03
Waiting for the state update.

**Comment by greg-schroeder** [comment] 2023-10-18 23:15
Okay @parasharrajat https://github.com/Expensify/App/pull/29541 was deployed to prod

**Comment by greg-schroeder** [comment] 2023-11-26 19:46
This is still on hold, right @parasharrajat?

**Comment by greg-schroeder** [comment] 2023-12-19 01:29
still on hold for VBA refactor

**Comment by mountiny** [comment] 2024-01-11 23:23
Still on hold, the refactor is in its last phase though

**Comment by mountiny** [comment] 2024-02-05 12:54
on hold

**Comment by mountiny** [comment] 2024-02-14 00:46
The refactor has been merged @parasharrajat @ygshbht what would be the next steps

**Comment by ygshbht** [comment] 2024-02-14 23:44
Thats great news. Was this [the reason](https://github.com/Expensify/App/pull/29053#pullrequestreview-1710105619) this PR was was kept on hold? I still see two state picker though @mountiny  @parasharrajat 
![image](https://github.com/Expensify/App/assets/65986357/7857d059-d165-4811-aa5f-95aec4d9a928)

**Comment by mountiny** [comment] 2024-02-15 00:10
@ygshbht the reason was simply that the refactor has changed the flow a lot. To be honest initially we hoped the refactor would take less time 😬 in the hindsight I think we did not have to hold, but that was hard to know in advance.

**Comment by ygshbht** [comment] 2024-02-15 00:43
Yes. I see the flow is different on the staging website and i dont see two state pickers together at places. Would you prefer me to keep the [code snippet](https://github.com/Expensify/App/pull/29053#pullrequestreview-1710105619) for futureproofing/ having places which may require it in two palces or remove it and continue with the merge conflicts? 
![image](https://github.com/Expensify/App/assets/65986357/9101091f-a548-4ba0-87bc-3aab33eecfff)

**Comment by mountiny** [comment] 2024-02-15 12:36
@ygshbht remove it, lets not futureproof when we dont know about it

**Comment by ygshbht** [comment] 2024-02-15 20:03
Okay. Given the significant changes over the past several months since the pull request was submitted, I'll need a few days to review the updates, ensure a smooth merge, and conduct testing. Does that work for you?

**Comment by mountiny** [comment] 2024-02-16 12:32
I see that handling both Country and State picker was suggested as $1250 https://github.com/Expensify/App/issues/28743

I think that the changes to the codebase are natural thing we need to expect and we are paying for completed work. I suggest we can increase the total to $1500 for completing the state + country picker, but I dont think at this point we can justify basically doubling the price. It's not how we handle other jobs even if the contributors have to spend considerable time on exploring options which turn out to be not accepted. 

I hope this works.

**Comment by greg-schroeder** [comment] 2024-04-05 21:29
Merged, awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment] 2024-04-15 02:16
Okay this issue is crusty AF, gonna take some time to review who did what along the way here

**Comment by greg-schroeder** [comment] 2024-04-15 02:29
@gadhiyaman reported this issue 2023-07-26 - $250 - Reporter
@ygshbht assigned 2023-09-04 - $1500 - Contributor
@parasharrajat - $1500 - C+

**Comment by greg-schroeder** [comment] 2024-04-15 02:30
I'm going to create manual offers for this one as the original Upwork issue is long since closed, stand by

**Comment by mountiny** [comment] 2024-04-15 15:00
I think we should add a test for this but one should be enough.

I would say lets use the `For Personal Address:`

@greg-schroeder would you be able to add this one? thanks!

**Comment by greg-schroeder** [comment] 2024-04-15 22:48
Added, closing!

**Closed by greg-schroeder** 2024-04-15 22:48 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-05-12 13:55
Asked for confirmation on the intended amount in New Expensify.

**Comment by greg-schroeder** [comment] 2024-05-13 16:08
Hey @JmillsExpensify - yes, I was going off of pricing that Vit laid out here:

https://github.com/Expensify/App/issues/23725#issuecomment-1948307119

**Comment by JmillsExpensify** [comment] 2024-05-13 22:47
Thanks! $1,500 approved for @parasharrajat
