### ISSUE TITLE
[$1000] Web - A newly created workspace name follows the sequence of the numbers present in the last workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23449] opened 2023-07-23 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website.
2. Navigate to the settings page, then to the workspaces page.
3. Edit the name of the last work space from the workspace general settings and add a numerical value at the end of the name (i.e., Workspace 111).
4. Create a new workspace.
5. Observe that the newly created workspace name follows the sequence of the number present in the last workspace (i.e., Workspace 112).

## Expected Result:
 A newly created workspace name should equal the number of workspaces present in the workspaces list, so if the newly created workspace is third in the list, its name should have the number 3 at the end.

## Actual Result:
A newly created workspace name follows the sequence of the numbers present in the last workspace; if the last created workspace name ends with 111, then the newly created workspace name ends with 112.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0.
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/be60ddec-3740-48fa-9f80-49cf56975a49

https://github.com/Expensify/App/assets/93399543/dc20ad82-15f2-4cc3-bdfe-0af51289e7c4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ad-eeb
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689984658585249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166a81173ade6bb41</li>
        <li>Upwork Job ID: 1683534701023903744</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by joh42** [comment] 2023-07-25 10:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A newly created workspace name follows the sequence of the numbers present in the last workspace.
### What is the root cause of that problem?
New workspaces are named based on arbitrary numbers at the end of existing workspace names.
### What changes do you think we should make in order to solve the problem?
I suggest we consider another approach to naming workspaces - using the number of existing workspaces, as opposed to just going off whatever arbitrary number is at the end of existing workspace names.

 For example
```
["myWorkspace", "myWorkspace1"] > "myWorkspace2"
["myWorkspace100"] > "myWorkspace1" // Would have been myWorkspace101 at present
```

We only need to care about the number at the end of existing workspaces if there is a direct conflict. In the below example, the default option would have been `myWorkspace2` since there are 2 existing workspaces. However, since `myWorkspace1` has been renamed to `myWorkspace2`, that name is already used, so we increment the end number to 3. Crucially, this is the only scenario where we would care about the ending numbers of existing workspace names.
```
["myWorkspace", "myWorkspace2"] > "myWorkspace3"
```

I think this approach is closer to optimal than going off minimum numbers. Consider the following scenario:
We have 3 workspaces
```
["myWorkspace", "myWorkspace1" "myRenamedWorkspace"] 
```

`myRenamedWorkspace` was initially called `myWorkspace2`, but has been renamed. If we were to go off minimum numbers, we would end up with yet another `myWorkspace2`, which could be confusing to users. It would, in my opinion, be better to name the new workspace `myWorkspace3`.

### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment] 2023-07-26 09:46
Let's be clear on expected output first. 

Personally, I don't think it's a bug and I am okay to leave it at present state. But if we want to make some improvement, my preference will be to add either 'total number of workspaces having default name' or 'total number of workspaces' and use it. But the preference can vary from person to person.

@maddylewis Can you please confirm the expected output here?

**Comment by sobitneupane** [comment] 2023-07-26 09:50
@samh-nl Regarding your [proposal](https://github.com/Expensify/App/issues/23449#issuecomment-1649542670), I will suggest you to start a discussion on slack. If everyone agrees, we can implement the customization flow. I personally like the idea. Nevertheless, I think even if we implement the flow, we should suggest a default name for workspace.

**Comment by maddylewis** [comment] 2023-07-29 12:48
@sobitneupane - let us know the direction you'd like to go based on this convo https://expensify.slack.com/archives/C01GTK53T8Q/p1690621380575829?thread_ts=1690377659.722669&cid=C01GTK53T8Q

**Comment by maddylewis** [comment] 2023-07-31 16:46
@sobitneupane - another bump on this one. let me know if you'd like me to assign another Contributor+ to lead this one. thanks!

**Comment by sobitneupane** [comment] 2023-08-01 08:27
@maddylewis even if we prompt user to name the workspace along with it's creation as suggested by @samh-nl, I believe we will be suggesting some default name which can be edited by the user. So, It will be a different Feature Request.

For handling this issue, we are not sure what should be the expected output? My suggestions are [here](https://github.com/Expensify/App/issues/23449#issuecomment-1651393603).

**Comment by joh42** [comment] 2023-08-01 08:40
In that case naming the new workspace would be a requirement, not an option @samh-nl, adding one more step to the creation of every workspace. If allowing users to set a name when creating a workspace is desired, the optimal solution IMO would be to not autofocus that input, rather to have an unfocused input with a default name, that is cleared when a user clicks on it.

**Comment by sobitneupane** [comment] 2023-08-02 12:23
Started discussion regarding the expected output: https://expensify.slack.com/archives/C01GTK53T8Q/p1690978953836909

**Comment by maddylewis** [comment] 2023-08-02 18:22
based on this comment, i'm going to close this out since it sounds like we decided to _Do Nothing_ in this case - https://expensify.slack.com/archives/C01GTK53T8Q/p1690982790796029?thread_ts=1690978953.836909&cid=C01GTK53T8Q

**Closed by maddylewis** 2023-08-02 18:22 UTC
Labels: External, Daily, Help Wanted, Bug
