### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] Task - No error of exceeding limit when changing title of existing task & system message posted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38451] opened 2024-03-17 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Navigate to any report
3. Click on "+" > Assign task
4. Enter title and finish creating a task
5. Open the created task
6. Click on Title and change to anything > 100 characters
7. Click on "Save"

## Expected Result:
The error is displayed in the title editor that the field is exceeding limit of 100 characters, and user can not save the long title

## Actual Result:
The error is not displayed in in the title editor, the title gets updated briefly, user is returned to the task report, and the system message of updated title is posted. There is only one error message in the task report that the title is too long

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7009c399-32b6-4595-8b56-701c751f082f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141fff112dde5aafe</li>
        <li>Upwork Job ID: 1770200502191382528</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment] 2024-03-17 19:38
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-03-18 11:31
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment] 2024-03-19 21:27
I would put this in VIP-VSB, since it's tied to task management. I would put this as a LOW issue in terms of priority though, because this is only an issue AFTER the task is created, and the error works well when creating the task with > 100 characters

**Comment by nkdengineer** [comment] 2024-03-20 06:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Task - No error of exceeding limit when changing title of existing task & system message posted
### What is the root cause of that problem?
- We do not validate the task title length if its length is greater than 100.
### What changes do you think we should make in order to solve the problem?
- The exceeding limit character is a common error, and is used in whole the app, but currently, we handle it manually. For example, with the task description, we need to handle it in the validate function as below:
https://github.com/Expensify/App/blob/ddf9e7ae25fcc9b0a2516ed341947ad38130b36f/src/pages/tasks/TaskDescriptionPage.tsx#L38-L46
- And we need to do a similar thing with other forms we need to limit the character, leading to duplicate logic.
- So my solution is, we will let the [FormProvider](https://github.com/Expensify/App/blob/main/src/components/Form/FormProvider.tsx) component handle it automatically. below is the details.
- First, we need to create a new variable, named ```maxLengthError```, to differentiate itself from the ```maxLength```
- Then, add the below logic to this [one](https://github.com/Expensify/App/blob/ddf9e7ae25fcc9b0a2516ed341947ad38130b36f/src/components/Form/FormProvider.tsx#L109):
```
            Object.entries(trimmedStringValues).forEach(([inputID, inputValue]) => {
                if (inputValue && inputPropsRef.current[inputID].maxLengthError && inputValue.length >inputPropsRef.current[inputID].maxLengthError ) {
                    ErrorUtils.addErrorMessage(validateErrors, inputID, ['common.error.characterLimitExceedCounter', {length: inputValue.length, limit: inputPropsRef.current[inputID].maxLengthError}]);
                }
                })
```
- In the above, ```inputPropsRef``` stores all the input props.
- Then, if we need to limit the character, for example, in this case is task title, just need to use:
```
                            <InputWrapper
                                maxLengthError={100}
```
### What alternative solutions did you explore? (Optional)
- Also, we can just need to add ```maxLength={100}``` to this [one](https://github.com/Expensify/App/blob/15aac1ca8ffbafb63346056265f544ef1e1a7a7d/src/pages/tasks/TaskTitlePage.tsx#L86) to prevent user from typing more than 100 characters

**Comment by nkdengineer** [comment] 2024-03-25 10:28
@thesahindia Do you have any feedback about my [proposal](https://github.com/Expensify/App/issues/38451#issuecomment-2008715837) (which will reduce redundant code in future)?

**Comment by blimpich** [comment] 2024-03-25 16:42
@thesahindia can you elaborate on why the selected proposal was chosen? I'm not particularly knowledgeable on our standards for forms and would be curious to hear if there was anything specifically that made you choose one proposal over the other?

@Krishna2323 please refrain from using accusatory language. This is a community and everyone deserves to be given the benefit of the doubt so we can make the best software possible.

**Comment by blimpich** [comment] 2024-03-25 17:08
Reducing the price of this since it is a low priority bug and is a fairly simple.

**Comment by nkdengineer** [comment] 2024-03-25 17:15
@blimpich Currently, the logic to validate the max length limit is handled separately. Or to put it another way, we need to call it for each input field we need to limit length. That leads to the duplicate logic. So we also should consider handling it generally, as I mentioned [here](https://github.com/Expensify/App/issues/38451#issuecomment-2008715837)

**Comment by blimpich** [comment] 2024-03-25 17:20
Yes I think we should consider handling it generally, though I'm not sure how big of a lift that would be. If we went with that we would ideally also change all existing instances of where we create limits for text inputs to use the new format you propose right? I'm not sure how big of a change that would be or if it would be high risk for regressions. Again, I'd like @thesahindia's thoughts on this.

**Comment by nkdengineer** [comment] 2024-03-25 17:32
If we do like that, IMO, I suggest 2 options:
- Option 1: There are ~15 existing instances and we can update them to use the new format.
- Option 2: Only apply the new format to fix the current issue, and will use that format in future components

**Comment by nkdengineer** [comment] 2024-03-27 11:24
@thesahindia What about this [comment](https://github.com/Expensify/App/issues/38451#issuecomment-2018514990)? Can you help check it

**Comment by nkdengineer** [comment] 2024-03-27 11:39
Yes. I think we should handle this generally ASAP because, in the future, there will be more and more similar inputs created, in that time, it is difficult for us to refactor the max length logic. There are two options for us mentioned [here](https://github.com/Expensify/App/issues/38451#issuecomment-2018538533)

**Comment by kevinksullivan** [comment] 2024-04-19 17:19
Payment summary:
- @thesahindia - $250
- @Krishna2323 - $250 (completed in NewDot)

**Comment by kevinksullivan** [comment] 2024-04-19 17:19
@thesahindia please complete the checklist above and we can close this out, thanks!

**Closed** 2024-04-30 20:59 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-19 14:11
$250 approved for @thesahindia
