### ISSUE TITLE
Pronouns - pronoun not translated when language changes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27343] opened 2023-09-13 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25846
## Action Performed:
Pre-conditions: Pronoun option selected he/Him/His/They/Them/Theirs
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap preferences
4. Tap language ---> Spanish
5. Navigate back to Settings
6. Tap Profile
7. Tap pronouns

## Expected Result:
The pronoun options shown outside must be shown inside with dropdown below of selected pronouns with a tick mark

## Actual Result:
The pronouns are shown outside in selected Spanish language correctly but inside displayed in English and "no results found" message displayed instead of showing dropdown below of selected pronouns with a tick mark

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2ef097b4-5de8-4fb3-bac0-3460d7f72ae5

https://github.com/Expensify/App/assets/78819774/ccd20884-6f48-4086-ac0f-6e60a6186d0c

https://github.com/Expensify/App/assets/78819774/0c2c6613-21cc-435f-8e44-40a72c5e9abe

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan/ Applause - Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694594697108839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-09-13 13:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect pronoun search displayed

### What is the root cause of that problem?
It is a regression from https://github.com/Expensify/App/pull/25846 where we iterate through the array `PRONOUNS_LIST` consisting of the keys and found key value we are setting in the serachValue instead of the text. 
https://github.com/Expensify/App/pull/25846/files#diff-2becc643119bc669cba2992bd64114fa69691d2a7d3fe265026322b57f4c75fdL29-L32

https://github.com/Expensify/App/blob/9675a77fc073b6197dd844b29e4ac27faf1e480f/src/pages/settings/Profile/PronounsPage.js#L30-L34

### What changes do you think we should make in order to solve the problem?
Making a proposal as I think we can set the value directly.

We already have the `currentPronounsKey` which we can use directly instead of finding the key again.
```
const [searchValue, setSearchValue] = useState(currentPronounsKey ? translate(`pronouns.${currentPronounsKey}`) : '')
```
https://github.com/Expensify/App/blob/9675a77fc073b6197dd844b29e4ac27faf1e480f/src/pages/settings/Profile/PronounsPage.js#L27

cc: @BeeMargarida 

### What alternative solutions did you explore? (Optional)

With the current implementation, we can translate the found key for setting the search value.

```
       const pronounKey = _.chain(CONST.PRONOUNS_LIST)
            .find((_value) => _value === currentPronounsKey);
        
        return pronounKey ? translate(`pronouns.${pronounKey}`) : '';
```

**Comment by Pluto0104** [comment] 2023-09-13 13:23
I can consider this issue as dup of https://github.com/Expensify/App/issues/27326.

**Comment by AndrewGable** [comment] 2023-09-13 16:58
This is going to be fixed by https://github.com/Expensify/App/pull/27358

**Comment by gadhiyamanan** [comment] 2023-09-26 06:58
this is eligible for reporting bonus because this is the first issue which was reported in slack

**Comment by gadhiyamanan** [comment] 2023-10-09 10:49
@Li357 can you assign BZ member for reporting bonus

**Comment by gadhiyamanan** [comment] 2023-10-27 08:32
bump @Li357

**Comment by gadhiyamanan** [comment] 2023-11-07 05:37
Bump @Li357

**Closed** 2023-12-05 23:47 UTC
Labels: Reviewing, Engineering, Monthly

**Comment by gadhiyamanan** [comment] 2023-12-18 05:00
@Li357 reporting bonus is pending here, can you please reopen the issue ..
