### ISSUE TITLE
[$500] Profile-Previously selected time zone can be seen for a second.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35650] opened 2024-02-02 10:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.5.35
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1.Launch app
2. Tap profile icon
3. Tap profile
4. Tap time zone
5. Toggle off Automatic determine your location
6. Tap timezone
7. Scroll and select a new location

## Expected Result:
Previously selected time zone must not be shown, only newly selected time zone should be displayed.

## Actual Result:
Previously selected time zone can be seen for a second before newly selected time zone displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/df4395c3-a4da-4ab9-a6f8-131b949225fb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123db13222afff0e2</li>
        <li>Upwork Job ID: 1753366206950236160</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-02-02 12:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile-Previously selected time zone can be seen for a second.
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/ef0bf6748de9adac69935323d84aeb8a94b6cbfb/src/libs/actions/PersonalDetails.ts#L292C1-L308C49) the navigation back works faster than updating Onyx
### What changes do you think we should make in order to solve the problem?
Change `API.write` to `API.makeRequestWithSideEffects` and call navigation back in `.then`
```
API.makeRequestWithSideEffects(WRITE_COMMANDS.UPDATE_SELECTED_TIMEZONE, parameters, {
    optimisticData: [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
            value: {
                [currentUserAccountID]: {
                    timezone,
                },
            },
        },
    ],
}).then(()=>{
    Navigation.goBack(ROUTES.SETTINGS_TIMEZONE);
});
```
### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment] 2024-02-03 12:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigate to timezone selector and select timezone, the user is navigated to timezone page but the previously selected timezone is displayed for second before the selected timezone is displayed.

### What is the root cause of that problem?
In the TimezoneSelectPage, after the user selects timezone, saveSelectedTimezone calls PersonalDetails.updateSelectedTimezone 
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/pages/settings/Profile/TimezoneSelectPage.js#L58

The updateSelectedTimezone calls API.write
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/libs/actions/PersonalDetails.ts#L293

The Navigation.goback is called right after and the user is navigated to the timezone page.
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/libs/actions/PersonalDetails.ts#L308

The problem occurs because the Api.write has not finished but the user is navigated back to the profile page so the previously selected timezone is displayed.

### What changes do you think we should make in order to solve the problem?

To resolve the issue, The StatusPage has similar setup where the api call is made to change the status and the user is navigated back to the settings profile page.
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/pages/settings/Profile/CustomStatus/StatusPage.js#L82

The updateSelectedTimezone function should not be navigating back after the api.write call
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/libs/actions/PersonalDetails.ts#L308

Similar to updateAutomaticTimezone
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/libs/actions/PersonalDetails.ts#L250

The Navigation.goBack would be removed for updateSelectedTimezone
```
Navigation.goBack(ROUTES.SETTINGS_TIMEZONE);
```

The saveSelectedTimezone function call should use the useCallback hook similar to the StatusPage. Then after the call to updateSelectedTimezone, call InteractionManager.runAfterInteractions. The click event on the selected timezone would be processed and then the Navigation.goback would be called.

```
    const saveSelectedTimezone = useCallback((tz) => {
        PersonalDetails.updateSelectedTimezone(tz.text);
        InteractionManager.runAfterInteractions(() => {
            Navigation.goBack(ROUTES.SETTINGS_TIMEZONE);
        });
    },[timezone.selected]);
```

Also after the user has selected the timezone, the list scrolls to the top. The PR https://github.com/Expensify/App/pull/30438 introduced the [bug](https://github.com/Expensify/App/pull/30438/commits/fe37ab7fef491eedcc7295aa015cbec1d14bac03)


```
       if (sections.length > 0) {
            updateAndScrollToFocusedIndex(0);
        }
```
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/components/SelectionList/BaseSelectionList.tsx#L358

The original requirement for PR 30438 if the search input has some value to navigate to top of the list. The list scrolls to the top even without any searchInput. Add textInputValue to useEffect dependency array.
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/components/SelectionList/BaseSelectionList.tsx#L350

Then in the if condition for sections.length > 1 also check if textInputValue is non-empty.

```
        // Focus on the first item of the selection list when user changes the search input
        if (sections.length > 0 && textInputValue !== "") {
            updateAndScrollToFocusedIndex(0);
        }
```

After the user has selected the timezone, the user taken back to the settings profile page only after the click interaction is finished and the correct timezone is displayed.

### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2024-02-06 21:36
Will check this by tomorrow, somehow this missed in my list

**Comment by Santhosh-Sellavel** [comment] 2024-02-07 17:47
Still couldn't get to it, so unassigning this one to move this forward! Can you reassign @sonialiap!

**Comment by situchan** [comment] 2024-02-08 09:45
I can take over

**Comment by sonialiap** [comment] 2024-02-14 16:45
Just got back from OOO, assigning to you @situchan

**Comment by shahinyan11** [comment] 2024-02-15 09:16
@sonialiap Why an offer has been sent to @situchan  as Contributor ? He has not any proposal

**Comment by situchan** [comment] 2024-02-15 09:22
Melvin comment is wrong. I was assigned as C+. I am reviewing proposals.

**Comment by situchan** [comment] 2024-02-15 18:06
@sourcecodedeveloper your solution of using `runAfterInteractions` causes regression of double transition animation

**Comment by situchan** [comment] 2024-02-15 18:07
I don't see any viable proposals yet.

If similar issue existed before and fixed in other pages, please link to the issue or PR.
Otherwise, this needs to be fixed globally.

**Comment by sourcecodedeveloper** [comment] 2024-02-15 18:29
@situchan I did not notice any double transition animation. Please provide video or more details. The runAfterInteractions would be safe and follow existing pattern e.g. statuspage.

https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/pages/settings/Profile/CustomStatus/StatusPage.js#L89

Another approach would be to add the save button on the timezone selection page and only save after the user clicks on the save button not after the user selects the timezone. The approach would be inline with the statuspage.

**Comment by situchan** [comment] 2024-02-15 18:35
@sourcecodedeveloper 

https://github.com/Expensify/App/assets/108292595/937067a4-0f12-4dda-8eca-20d02ff733d7

**Comment by shahinyan11** [comment] 2024-02-15 19:50
@situchan What about my proposal ?

**Comment by situchan** [comment] 2024-02-15 19:51
@shahinyan11 have you found such pattern in other place of the app?

**Comment by shahinyan11** [comment] 2024-02-15 19:55
> @shahinyan11 have you found such pattern in other place of the app?

@situchan No. But I think it's not necessary to find such pattern and just need to propose a good solution

**Comment by sourcecodedeveloper** [comment] 2024-02-15 20:59
@situchan Thanks but for some reason I am not getting the double transition animation. I have included video but I am not able to get any double transition.

Try using the navigateBacktoPreviousScreen in useCallback similar to statuspage.
try replacing saveSelectedTimezone. the navigation go back would be handled inside navigateBacktoPreviousScreen . 
```
    const navigateBackToPreviousScreen = useCallback(() => Navigation.goBack(), []);
    const saveSelectedTimezone = useCallback((tz) => {
        PersonalDetails.updateSelectedTimezone(tz.text);
        InteractionManager.runAfterInteractions(() => {
            navigateBackToPreviousScreen();
        });
    },[timezone.selected]);
```
Also do not forget to comment out 
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/libs/actions/PersonalDetails.ts#L308
```
 Navigation.goBack(ROUTES.SETTINGS_TIMEZONE);
```

also do not forget to replace the if condition in BaseSelectionList
https://github.com/Expensify/App/blob/751e6fb5a6567bc462e94a3b82d653d398f8ff69/src/components/SelectionList/BaseSelectionList.tsx#L357
```
        if (sections.length > 0 && textInputValue !== "") {
            updateAndScrollToFocusedIndex(0);
        }
```

**Comment by situchan** [comment] 2024-02-19 15:36
Still discussing solutions

**Comment by sonialiap** [comment] 2024-02-21 16:22
@situchan Bumping Tien's question

**Comment by sonialiap** [comment] 2024-02-26 14:45
@situchan bumping

**Comment by situchan** [comment] 2024-02-28 11:26
@shahinyan11 your solution works but it causes navigation delay. I don't think we want that behavior.


https://github.com/Expensify/App/assets/108292595/f782f9ad-229d-47f7-a0fe-5a763b334bbc

**Comment by situchan** [comment] 2024-02-28 11:34
This happens in all other places of the app.

i.e. when update display name

https://github.com/Expensify/App/assets/108292595/fc525d46-b5f3-4513-a52a-81a6cb230b05




@sonialiap I vote to close this as not worth fixing.

**Comment by situchan** [comment] 2024-02-28 14:57
@tienifr I already checked your both solutions but result in the [same concern](https://github.com/Expensify/App/issues/35650#issuecomment-1968793115).
You don't wanna apply your approach to all pages where this issue happening, right?

**Comment by sonialiap** [comment] 2024-03-05 12:31
While this behavior is noticeable, it is pretty brief so I think we can punt it in favor of higher value issues since we don't have a proposal that would fix it without causing other undesirable behaviors. Feel free to reopen if you disagree

**Closed by sonialiap** 2024-03-05 12:31 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
