### ISSUE TITLE
[HOLD for payment 2023-09-04] Wrong edit message shown in IOU report description when editing date

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25715] opened 2023-08-22 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to staging new dot
2. Click on + icon and select request money
3. Enter an amount and click next
4. Select ann account to request from and click on request
5. Click on the IOU report and go to IOU report description
6. Click on date and change date to any other date
7. Observe that the whisper message "removed the merchant... " rather than "changed date..."

## Expected Result: 
Displayed message should be "changed date..."
## Actual Result: 
"Removed merchant previously..." Message is displayed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9b2a9694-e477-4976-8976-7410817acd58

![Snip - (91) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/574bfd04-0046-4697-b2a3-09b40d67dd86)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692732220565619

https://expensify.slack.com/archives/C049HHMV9SM/p1692712587744049?thread_ts=1692712587.744049&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by daordonez11** [comment] 2023-08-22 19:48
This is a BE issue:

Initially we create a request with empty merchant here is the body:
![image](https://github.com/Expensify/App/assets/13544910/c997debc-df25-4501-a54a-d14d7e9465d1)


Then we send an "EditRequest" command with empty merchant and backend is saying that we changed the merchant from "Request" to "".

Here is the body of the request:
![image](https://github.com/Expensify/App/assets/13544910/c3da944a-c091-4ed5-9eed-0cfdeea4d32a)

And the failed response:
![image](https://github.com/Expensify/App/assets/13544910/98bfd0c5-8bd9-4b1d-9ef3-747cdcd65022)

It seems like the default merchant is bein wrongly setup.

cc @mountiny

**Comment by Pujan92** [comment] 2023-08-22 19:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Shows incorrect merchant change on edit money request

### What is the root cause of that problem?
Seems we are not setting the current value of merchant while calling `EditMoneyRequest` api call.
https://github.com/Expensify/App/blob/7640a6f2357852f1c58849c4d377b3945c268f75/src/libs/actions/IOU.js#L1035-L1045

### What changes do you think we should make in order to solve the problem?
Add field `merchant` for getting transaction details and pass that to the api call body.
```
const {created, amount, currency, comment, merchant} = ReportUtils.getTransactionDetails(updatedTransaction);
```

**Comment by jasperhuangg** [comment] 2023-08-22 20:11
Hey guys, sorry in the interest of urgency I'm going to be addressing this internally, thank you for the proposals

**Comment by jasperhuangg** [comment] 2023-08-22 20:13
Hmm this doesn't seem to be happening locally. Could there be a mismatch between the versions of NewDot and Web-E that have been deployed to staging?

**Comment by jasperhuangg** [comment] 2023-08-22 20:14
cc @mountiny

**Comment by Pujan92** [comment] 2023-08-22 20:18
It happens locally for me.

https://github.com/Expensify/App/assets/14358475/a984e3e1-81a1-4877-a24b-8ffe730110d2

**Comment by jasperhuangg** [comment] 2023-08-22 20:21
@Pujan92 I meant to say happens locally with our local version of the PHP API, you're testing it against the staging version of the PHP API

**Comment by Pujan92** [comment] 2023-08-22 20:23
Oh, ok. I think it should occur as merchant value we are changing for `editMoneyRequest` and needs to be corrected from frontend pass but not very sure as it is not happening on your side.

**Comment by jasperhuangg** [comment] 2023-08-22 20:26
Ah hmm, I'm actually able to reproduce it on my side now, sorry for the false alarm.

**Comment by Pujan92** [comment] 2023-08-22 20:30
Cool, you can check my [proposal](https://github.com/Expensify/App/issues/25715#issuecomment-1688833472) if it makes sense.

**Comment by jasperhuangg** [comment] 2023-08-22 20:36
@Pujan92 thanks for the proposal, but I think it makes more sense to add back-end validation here

**Comment by jasperhuangg** [comment] 2023-08-22 20:45
Asked some clarifying questions [here](https://expensify.slack.com/archives/C02HWMSMZEC/p1692736907100829)

**Comment by Pujan92** [comment] 2023-08-22 21:18
No issues @jasperhuangg , Thanks :)

**Comment by jasperhuangg** [comment] 2023-08-22 23:48
We CPd a fix and this is fixed on staging!

**Comment by jasperhuangg** [comment] 2023-08-23 04:08
@sophiepintoraetz

**Comment by sophiepintoraetz** [comment] 2023-09-04 06:19
offer sent @ayazhussain79!

**Comment by ayazhussain79** [comment] 2023-09-04 08:02
@sophiepintoraetz offer accepted, Thank you

**Comment by sophiepintoraetz** [comment] 2023-09-04 23:42
Paid!

**Closed by sophiepintoraetz** 2023-09-04 23:42 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
