### ISSUE TITLE
[$500] Web-Bank Account-Error message disappears when navigate back to Company information page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34193] opened 2024-01-09 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33865
## Action Performed:
1. Go to Workspace > Bank account > Connect manually
2. Enter routing and account number >> Continue
3. Enter emojis in Legal business name, Company address and City fields
4. Verify that Invalid errors show for these fields
5. Navigate back to Connect bank account page
6. Click Continue

## Expected Result:
Error messages Company information page should remain when user navigates back there

## Actual Result:
Error message disappears when navigate back to Company information page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/510bba3b-82fc-44b8-bb9f-a92c176030cd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aac2f98317031f8d</li>
        <li>Upwork Job ID: 1745116901033091072</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by AndrewGable** [comment] 2024-01-09 21:57
This does not happen on production from my testing, so it seems like a legit deploy blocker if we want to block on it.

**Comment by AndrewGable** [comment] 2024-01-09 21:58
@grgia @parasharrajat @tienifr - Would we like to move forward with a fix or revert?

**Comment by thienlnam** [comment] 2024-01-10 04:29
I don't think this needs to be a blocker - I'm not sure if it ever retained the error if you navigate to a different page since I can reproduce on production with a different field error

This is what happens on production with a different error (not emojis). We have the same outcome
https://github.com/Expensify/App/assets/30609178/0974abfa-e2dc-4608-8b09-c6ef334c860a

**Comment by AndrewGable** [comment] 2024-01-10 16:14
Adding @kevinksullivan to figure out if/how we want to fix this!

**Comment by abdulrahuman5196** [comment] 2024-01-11 17:01
Thank you. Do let me know if we want to fix this issue.

**Comment by AndrewGable** [comment] 2024-01-16 22:13
@kevinksullivan any thoughts?

**Comment by DylanDylann** [comment] 2024-01-22 10:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web-Bank Account-Error message disappears when navigate back to Company information page
### What is the root cause of that problem?
- Once we navigate back to Company information page, the validate function is not called (because there is no blur, submit actions, ... that will trigger the validate function), so the error message disappears. (Need to confirm the expected behavior [here](https://github.com/Expensify/App/issues/34193#issuecomment-1885162530))


**There is an additional bug**: 
- When we navigate back to Company information page, then focus on Company address, then focus on Phone number, only the Company address is validated, and the Legel business name is not validated. 
- RCA: We only validate the input that we have touched, in this case, the Legal business name was not touched before, so it is not validated. 
### What changes do you think we should make in order to solve the problem?
- This change will fix the **There is an additional bug** that I mentioned above.
- We have a logic that will set the initial value for the inputs below:
https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/components/Form/FormProvider.js#L120
- So, with the input having not empty initial value, we should treat it as is touched. Do it by update the above to:
```
        const [inputValues, setInputValues] = useState(() => {
            const draftValuesKeys = _.keys(draftValues);
            draftValuesKeys.forEach((key) => {
                if (draftValues[key]) {
                    setTouchedInput(key);
                }
            });
            return {...draftValues};
        });
```
- Then 
### What alternative solutions did you explore? (Optional)

- NA

**Comment by abdulrahuman5196** [comment] 2024-01-28 17:55
> Adding @kevinksullivan to figure out if/how we want to fix this!

@kevinksullivan Could you kindly check on this?

**Comment by DylanDylann** [comment] 2024-02-21 14:23
@kevinksullivan Please help check this [comment](https://github.com/Expensify/App/issues/34193#issuecomment-1913674611) once you have a chance

**Comment by abdulrahuman5196** [comment] 2024-02-22 13:26
Bump @kevinksullivan / @AndrewGable

**Comment by kevinksullivan** [comment] 2024-02-22 19:11
Sorry I missed this. But I don't think this is worth fixing, as these patterns are being changed to one-be-one in other projects as is. Going to close this out.

**Closed by kevinksullivan** 2024-02-22 19:11 UTC
Labels: Engineering, Weekly, Internal, Bug
