### ISSUE TITLE
Dev: IOS -  Getting Font error on login (Might be dev only)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21080] opened 2023-06-19 20:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on iOS.
2. Enter email of a user.
3. Press Continue.

## Expected Result:
No error is shown for the font.

## Actual Result:
There is a font error is shown on the login page. This does not crash the app but should be solved.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-13 at 7 23 21 PM](https://github.com/Expensify/App/assets/93399543/1e055380-6b83-40d3-91f3-cbad2ecbab41)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @parasharrajat 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686664543856289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-06-20 16:18
Can't reproduce - asking for more information on the testing steps - https://expensify.slack.com/archives/C049HHMV9SM/p1687277841338779?thread_ts=1686664543.856289&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-06-20 17:06
Based on the slack convo - this might have already been fixed - closing for now - https://expensify.slack.com/archives/C049HHMV9SM/p1687279957353719?thread_ts=1686664543.856289&cid=C049HHMV9SM

**Closed by Christinadobrzyn** 2023-06-20 17:06 UTC
Labels: Daily, Needs Reproduction, Bug
