### ISSUE TITLE
Submit expense - Enable camera permission popup is not displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51142] opened 2024-10-20 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3272233
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: on mWeb, go to staging.expensify.com, choose 'Organize my own expenses', enter new Gmail email and proceed sign up.
Remove camera access from Expensify on mobile browser level

1. On staging.new.expensify.com, click on FAB
2. Click on Submit Expense
3. On defaults Scan tab > click Continue

## Expected Result:
Popup with camera permission is displayed. User can enable permission.

## Actual Result:
No popup with camera permission is displayed

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/59bc3ff2-8f57-451e-8f9b-599806091479

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-20 19:38
We think that this bug might be related to #wave-collect - Release 1

**Comment by Christinadobrzyn** [comment] 2024-10-21 03:50
I don't exactly know what issue this could be related to but asking if it's related to - https://github.com/Expensify/App/issues/50980

**Comment by mkzie2** [comment] 2024-10-21 04:22
I cannot reproduce this issue on the lasted `main`.

**Comment by aldo-expensify** [comment] 2024-10-21 19:15
Can't reproduce in staging using Android web

**Comment by aldo-expensify** [comment] 2024-10-21 19:16
I see that if I reject the permissions, and then tap "Continue" again, nothing happens anymore

**Comment by aldo-expensify** [comment] 2024-10-21 19:21
I think this is expected behaviour, closing.

**Closed by aldo-expensify** 2024-10-21 19:21 UTC
Labels: Engineering, Daily, Bug
