### ISSUE TITLE
[HOLD for payment 2024-01-24] LOW: [$500] Android-Thread-In Android, with uneven spacing as text entered, displayed in reply thread title

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32555] opened 2023-12-06 10:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a chat
3. Send a message with uneven spacing
4. Long press the message sent and select Reply in thread
5. Note the header in mweb
6. Launch app
7. Perform step 2-step4
8. Note the header in Android

## Expected Result:
In reply thread page, in both mweb and Android, the title must be shown in a consistent way.

## Actual Result:
In reply thread page, in mweb, text title is shown with normal spacing but in Android, with uneven spacing as text entered, it is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e465a3ec-f634-4345-bf2e-9bc5cc4db0d5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01208eb9280d67b191</li>
        <li>Upwork Job ID: 1732348414892351488</li>
        <li>Last Price Increase: 2023-12-27</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28088147</li>
<li>tienifr | Contributor | 28088148</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-06 18:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The thread title in header have a different white space behavior between native and mWeb.
### What is the root cause of that problem?
On mWeb, we use `styles.noWrap` and this make several space to one space.
https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L50
On native, we don't have that and that doesn't work on native.
https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/components/DisplayNames/index.native.tsx#L12
### What changes do you think we should make in order to solve the problem?
We need add new function for native
```
const title = String(fullTitle).trim().replace(/\s\s+/g, ' ').trim();
```
And use `title` instead of `fullTitle`
https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/components/DisplayNames/index.native.tsx#L15
### What alternative solutions did you explore? (Optional)

<img width="386" alt="Screenshot 2023-12-06 at 8 53 01 PM" src="https://github.com/Expensify/App/assets/65789015/cdd1d457-72ed-4d13-8a65-c2e024847fc1">

**Comment by quinthar** [comment] 2023-12-07 20:58
Let's keep this, cross-platform consistency ftw.  Adding to VIP.

**Comment by strepanier03** [comment] 2023-12-08 18:27
@quinthar - Is Daily still the right priority for this one or can we move it to at least weekly since it's low?

**Comment by strepanier03** [comment] 2023-12-11 18:12
Moving this to weekly since it's Low priority. Please feel free to update labels as needed when priority changes.

**Comment by alitoshmatov** [comment] 2023-12-13 17:25
Reviewing

**Comment by alitoshmatov** [comment] 2023-12-20 09:45
@strepanier03 Can you clarify what is the expected outcome here.

If text with multiple consequent spaces are enter(`hello    world`), how we should show it? 

a) Collapse spaces - `hello world`
b) Keep them and display them as it is

**Comment by strepanier03** [comment] 2023-12-21 22:12
> Can you clarify what is the expected outcome here.

@alitoshmatov - I'm unsure which of the two behaviors will be the final one we decide to go with when this becomes a priority to work on. 

Since right now this is set to LOW, I'd recommend focusing on other higher-priority bugs. @quinthar will update the priority on this bug as the #vip-vsb project progresses and when we're ready to focus on this we can confirm the expected behavior. 

If anyone feels differently, feel free to chime in and share the context I'm missing. But it makes sense to me to focus elsewhere until this becomes higher priority or more relevant.

**Comment by strepanier03** [comment] 2023-12-28 19:20
@tienifr - Thank you!

**Comment by alitoshmatov** [comment] 2024-01-02 11:13
We can proceed with @tienifr [proposal](https://github.com/Expensify/App/issues/32555#issuecomment-1842636943) and make all platforms consistent by showing all spaces and not collapsing them.

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment] 2024-01-02 11:15
@bernhardoj Thank you for your proposal. Your proposal is very similar to @tienifr 's and have the same approach

**Comment by alitoshmatov** [comment] 2024-01-02 11:16
@yh-0218 Thank you for your proposal, we decided to preserve spaces on all platforms.

**Comment by alitoshmatov** [comment] 2024-01-03 17:08
Waiting for @techievivek's take on @tienifr's proposal

**Comment by strepanier03** [comment] 2024-01-03 21:07
Flopping back to External since automation switched it over and we're waiting for a review of @tienifr's proposal from @techievivek.

**Comment by techievivek** [comment] 2024-01-08 09:11
Ooops sorry, I missed the ping.

**Comment by strepanier03** [comment] 2024-01-10 22:45
Thanks @techievivek - @tienifr will you submit the draft PR soon?

**Comment by strepanier03** [comment] 2024-01-10 23:01
All good Melvin.

**Comment by alitoshmatov** [comment] 2024-01-24 14:05
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21664
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21664/files#r1464963197
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- Determine if we should create a regression test for this bug. No need

**Comment by strepanier03** [comment] 2024-01-26 22:29
Dang, another one where the automation didn't work to move this over to Daily. I'll work on this now.

**Comment by strepanier03** [comment] 2024-01-26 22:54
All paid up and contracts closed. Thanks everyone!

**Closed by strepanier03** 2024-01-26 22:54 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
