### ISSUE TITLE
[$500] Task - Canceled task disappears from the conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28658] opened 2023-10-02 21:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account
3. On LHN, click on the FAB button
4. Select Assign Task
5. Enter a title or description
6. Assign the task to yourself and Share Somewhere with another user you have access to
7. Click on the 3 dot menu and cancel the task

## Expected Result:
The task is unmarked in the 1:1 chat where the task was shared

## Actual Result:
Canceled task disappears from the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
- [x] Windows / Chrome

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fc8e527d-ed89-45d6-8fc8-523b09702360

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d268a31fa534112</li>
        <li>Upwork Job ID: 1708977327264219136</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by nebiyuelias1** [comment] 2023-10-03 00:03
How to reproduce this locally?

**Comment by rojiphil** [comment] 2023-10-03 03:04
Isn’t this an expected behavior for the [Deleted task] to disappear from the conversation? That way, it would be consistent with how threads behave.

**Comment by pasala-krishna** [comment] 2023-10-03 03:30
### Proposal
**issue:**
Canceled task disappears from the conversation
The issue is the way cancel task task action is handled, we can change values [here](https://github.com/Expensify/App/blob/94002fbd83b96d7dd53598f88557f3c0550fcb37/src/libs/actions/Task.js) to make task not show deleted in the chat.

**Comment by pasala-krishna** [comment] 2023-10-03 03:36
Contributor details
Expensify account email: pasala.krishna14@gmail.com
upwork profile link: https://www.upwork.com/freelancers/~01242a758658bf605d

**Comment by nebiyuelias1** [comment] 2023-10-03 05:43
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Canceled task disappears from the conversation
> 
> ### What is the root cause of that problem?
> We're excluding `deleted action` from the list of report actions [here](https://github.com/Expensify/App/blob/94002fbd83b96d7dd53598f88557f3c0550fcb37/src/libs/ReportActionsUtils.js#L353).
> 
> The cancelled task satisfies that condition so it also disappears. This is incorrect since we still want to show cancelled task because we still keep the thread for it in the LHN, so it'll be confusing to the user when they go back from the thread to the parent report and do not see any task-related information.
> 
> ### What changes do you think we should make in order to solve the problem?
> Update [this condition](https://github.com/Expensify/App/blob/94002fbd83b96d7dd53598f88557f3c0550fcb37/src/libs/ReportActionsUtils.js#L353) to allow cancelled tasks to be visible
> 
> Like below
> 
> ```
> const isDeleted = isDeletedAction(reportAction) && !ReportUtils.isCanceledTaskReport(allReports[reportAction.reportID], reportAction);
> ```
> 
> We might need to modify the optimistic data when cancelling the task for it to show accordingly in LHN as well.
> 
> ### What alternative solutions did you explore? (Optional)
> NA

I wonder how you're able to test this locally? Because I wasn't able to reproduce it.

**Comment by mountiny** [comment] 2023-10-03 08:59
@dukenv0307 Thanks for the proposal, reminding that if the issue is a deploy blocker, lets always link the offending PR.

Looking at this again though, I am not sure if this is intended or no, probably ont but does not feel like a blocker. @thienlnam from this PR https://github.com/Expensify/App/pull/28128 might have better idea what the expected behaviour is here

**Comment by thienlnam** [comment] 2023-10-04 05:19
Yeah this is intended in some situations, we've also been discussing this in this [issue](https://github.com/Expensify/App/issues/27939), so I'm going to close this to consolidate the discussion there

**Closed by thienlnam** 2023-10-04 05:19 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
