### ISSUE TITLE
[$1000] task name does not updated in LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20613] opened 2023-06-12 19:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. click on + icon
3. select Assign task option
4. type title and click on Next button
5. click on confirm task
6. Go to task thread
7. change task title
8. go back to previous chat and check the LHN
## Expected Result: 
task name should be update in LHN
## Actual Result: 
task name updates but not in LHN
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5a5463d3-cffb-4020-be04-f54b2cb27400

https://github.com/Expensify/App/assets/43996225/e3aa2a85-6a44-4b75-aadb-8f6cf774cd45

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686128527516329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159a021714aafe0fa</li>
        <li>Upwork Job ID: 1668655419668803584</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-06-13 16:19
Reviewing

**Comment by greg-schroeder** [comment] 2023-06-13 16:23
I reproduced this: 
![image](https://github.com/Expensify/App/assets/29386373/68bdad44-0a97-483f-828d-bc324959322f)

I don't see any duplicate reports. Sending it through.

**Comment by greg-schroeder** [comment] 2023-06-13 16:25
Hey @abdulrahuman5196 - we have an early bird proposal here: https://github.com/Expensify/App/issues/20613#issuecomment-1587935077

**Comment by greg-schroeder** [comment] 2023-06-16 16:21
bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-06-16 17:31
@greg-schroeder We had older discussion related to LHN subtitles and its consistency, I will create a slack for it to discuss in the slack channel. That information would be useful here as well.

**Comment by greg-schroeder** [comment] 2023-06-16 17:39
Ah, awesome, I'd love to follow that

**Comment by abdulrahuman5196** [comment] 2023-06-19 10:33
Will create a slack thread today night. Got similar issue - https://github.com/Expensify/App/issues/20633

**Comment by greg-schroeder** [comment] 2023-06-19 17:09
thanks @abdulrahuman5196

**Comment by greg-schroeder** [comment] 2023-06-21 20:26
Thread discussion still ongoing

**Comment by abdulrahuman5196** [comment] 2023-06-23 20:03
Update from slack. Its seems for now we can handle the LHN reports on the issue basis. So reviewing the proposals currently

**Comment by abdulrahuman5196** [comment] 2023-06-23 20:05
@dukenv0307 From proposal here https://github.com/Expensify/App/issues/20613#issuecomment-1587935077
Could you add information on where you would make the change? What change would that be? 
The proposal has very high level of information

>We also need to update BE with this implementation.

And why do you think we need BE implementation?

**Comment by abdulrahuman5196** [comment] 2023-06-26 15:54
@dukenv0307, I am not sure if backend is setting the lastmessageText, we are actually setting it as part of optimistic report at multiple places in frontend

**Comment by abdulrahuman5196** [comment] 2023-06-26 16:34
@dukenv0307 I am not saying that is the fix. I am saying that now in create task flow we are setting lastMessageText as optimistic data and during API call and it is working currently. Correct me if wrong. So shouldn't the same be enough, we make `editTaskAndNavigate` to update lastMessageText as well.

Asked the above since i am still not sure on the question **And why do you think we need BE implementation?**

Or is it like we are setting correct lastMessageText in frontend and backend is return wrong data?
Or you are trying  to say even if we set  lastMessageText in frontend if its not done now, even then BE will return wrong data?

**Comment by greg-schroeder** [comment] 2023-06-28 20:26
@abdulrahuman5196 is @dukenv0307's update on a good track?

**Comment by abdulrahuman5196** [comment] 2023-07-03 18:12
Hi, @greg-schroeder , sorry for the delay. Yes, @dukenv0307  is on the right track.



>**Or is it like we are setting correct lastMessageText in frontend and backend is return wrong data?**
@abdulrahuman5196 Yes. I've tested the logic to update lastMessageText in optimistic data.It works well and display correctly in LHN. But after going back to main report, openReport is called and it displays wrong like this video.


@Gonals This might require backend changes as well, could you kindly confirm? Even if we set correct data as lastMessageText during edit task flow, backend returns wrong information.

I don't think we should start on frontend fix before confirming on backend.

**Comment by Gonals** [comment] 2023-07-04 10:18
Hmm. It does seem like we'll need some backend changes to make sure this works correctly.

@greg-schroeder, I think we should swap this to internal (or partially internal), but I probably don't have the bandwidth to get it fixed in the next few days.

**Comment by abdulrahuman5196** [comment] 2023-07-05 15:54
Hi, @Gonals @greg-schroeder Yes. I think partially internal should be fine IMO, if others are fine.
@dukenv0307 Could do the frontend changes based on their proposal here https://github.com/Expensify/App/issues/20613#issuecomment-1587935077 since they already spend effort on the proposal and confirmation. I think the proposal needs some polishes but should be fine on high level IMO and we can update the proposal once backend changes are complete and the Frontend expectation is set.

**Comment by greg-schroeder** [comment] 2023-07-08 00:41
Okay - so sounds like the proposed flow would be:

- Set to `Internal`
- Let @Gonals work on the backend changes when he can prioritize next week
- Once backend is complete, allow @dukenv0307 to polish proposal for frontend changes
- Get approval from @abdulrahuman5196 and @Gonals 
- Proceed with frontend changes per normal process

**Comment by greg-schroeder** [comment] 2023-07-10 19:04
Last update is where we stand ☝️

**Comment by greg-schroeder** [comment] 2023-07-12 20:32
@Gonals do you have thoughts on the timeline for this one?

**Comment by Gonals** [comment] 2023-07-17 21:04
Honestly, I am swamped right now. I don't see myself having time for this in the foreseeable future, as whatever time I have left after chores will have to go to W4 development. I'll post this tomorrow on Slack to see if someone has the bandwidth to take it

**Comment by Beamanator** [comment] 2023-07-18 12:54
@thienlnam or I could probably take over in the next day or two!

**Comment by Gonals** [comment] 2023-07-19 07:48
That would be awesome! @Beamanator, @thienlnam, who wants it? 😁

**Comment by thienlnam** [comment] 2023-07-19 21:13
Coming in late, but I don't really know if we want to fix this. This bug only really occurs when the created task reportAction was the last message in the chat and then you update the title name. This is mostly an edge case but would require us to update the EditTask flow to find _all_ cases where the task reportAction was created and then update them all. Same applies to when we decide to cancel the task.

Imagine the case where you create a task in a room
Change the assignee like 10 times
Edit the task title
All of those chats now have an outdated task title in the LHN

We could fix this, but I don't know if it is worth adding all that logic for

**Comment by Beamanator** [comment] 2023-07-20 11:05
I think that's fair, but I'm more of the opinion that it would be an easy front-end optimistic fix, and not necessary to find alllll those chat reports in the backend to update all clients 🤷

**Comment by thienlnam** [comment] 2023-07-20 18:04
> I think that's fair, but I'm more of the opinion that it would be an easy front-end optimistic fix, and not necessary to find alllll those chat reports in the backend to update all clients 🤷

That would only update it for the user changing the task name and not anyone else that sees it in the LHN which is maybe fine?

**Comment by Beamanator** [comment] 2023-07-21 08:26
Yes exactly - maaaybe, yes? Maybe we can post in slack to see if more people have stronger opinions that this actually needs to get fixed

**Comment by greg-schroeder** [comment] 2023-07-21 09:47
Hmm - [this](https://github.com/Expensify/App/issues/20613#issuecomment-1644366177) doesn't seem that worth it to me? The BE fix seems better but way more intensive imo

**Comment by abdulrahuman5196** [comment] 2023-07-21 13:34
Yeah. I agree it could end up a complex change in backend. 

But we are already providing pusher event to user to update report action items in case of task change which is a similar requirement to what we have now. Then wouldn't we able to reuse the same to update lastMessageText as well?
Note: I don't know how backend is implemented but just providing some thought which could be wrong from backend perspective as well.

**Comment by greg-schroeder** [comment] 2023-07-24 17:08
@Beamanator @thienlnam where do we think we go with this? Maybe it's a close 🤔

**Comment by thienlnam** [comment] 2023-07-24 21:16
> But we are already providing pusher event to user to update report action items in case of task change which is a similar requirement to what we have now. Then wouldn't we able to reuse the same to update lastMessageText as well?

It's a good instinct - this is true but the thing is because you can change the assignee as many times as you want, we're pushing the update separately to many different reports that have different participants each time.

Actually, another idea is we could use the reportAction data to show what the completed task was in the FE so we don't have to make any BE modifications.

In any case though, this seems minor enough I don't know if we need to spend any more time on it

**Comment by greg-schroeder** [comment] 2023-07-26 21:15
All right, in that case, I'm going to close per Jack's comment above.

**Closed by greg-schroeder** 2023-07-26 21:15 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
