### ISSUE TITLE
Category - Selected item is no longer selected after renaming the category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54486] opened 2024-12-23 23:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+909608@applause.expensifail.com
**Issue reported by:** Applause - Internal Team
**Component** Workspace Settings

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories
3. Click Select all checkbox
4. Click on any selected category
5. Click Name
6. Edit the name and save it
7. Note that the renamed category is now unselected
8. Go to Taxes
9. Click Select all checkbox
10. Click on the selected rate
11. Click Name
12. Rename and save it
13. Note that the renamed tag remains selected

## Expected Result:
There should be consistency in the item selection after renaming category and tax rate while they are selected

## Actual Result:
In Step 7, after renaming the selected category, it is unselected
In Step 9, after renaming the selected tag, it remains selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/924263dd-3957-4650-8861-233cf5811cdc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2024-12-24 21:45
@truph01 I think the category should stay selected when its name changes. The category object/row is shown as selected in the UI, so it doesn't make sense to me that changing one field would remove the object and create a totally new one.

I like [the proposal](https://github.com/Expensify/App/issues/54486#issuecomment-2560501431) from @BhuvaneshPatil.

It looks like the issue is not reproducible on production because if you select all categories and then click on one, it clears the selection. After that was fixed with [this PR](fix: when selecting categories, the selected categories get reset)[fix: when selecting categories, the selected categories get reset](https://github.com/Expensify/App/pull/53519#top), it uncovered this bug that we didn't see before. I wouldn't say the PR I linked caused this regression and I don't think it should be reverted. Instead let's fix it quickly.

**Comment by BhuvaneshPatil** [comment] 2024-12-25 02:29
@neil-marcellini This is what we get in response for categories page
<img width="881" alt="Screenshot 2024-12-25 at 7 58 01 AM" src="https://github.com/user-attachments/assets/937d26e8-0749-4da6-a2b0-66c3f6626cfb" />
Is it possible to send id?

**Comment by neil-marcellini** [comment] 2024-12-26 16:33
Yeah, I think this is going to require a backend change. I tried making it work by adding an id field on the frontend and storing it on the component, but the problem is that when a category is modified, added, or deleted, there's no way to tell how the selectedCategories should be updated. I was thinking that ids could be added when the component mounts, and then if a category is added or deleted the necessary ID updates would get made, but that's problematic because adding and deleting categories happens in another component. There's no way to differentiate between adding a category and modifying one. To make this work on the frontend only it would probably have to be managed with a separate Onyx key, and then that's pretty messy and complicated.

It's also a fairly large amount of work to change this on the backend, so maybe the separate frontend Onyx key is a viable approach. I'll ask for some advice from the team internally.

**Comment by neil-marcellini** [comment] 2024-12-26 17:51
CP [requested here](https://expensify.slack.com/archives/C07J32337/p1735235391984029). I'll close when that's done.

**Comment by neil-marcellini** [comment] 2024-12-26 18:05
Done https://expensify.slack.com/archives/C07J32337/p1735235507979819?thread_ts=1735235391.984029&cid=C07J32337

**Closed by neil-marcellini** 2024-12-26 18:05 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
