### ISSUE TITLE
[HOLD for payment 2024-05-03] [Guided Setup Stage 2] Use new `CompleteGuidedSetup` API to create tasks and messages (Phase 1)

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#38771] opened 2024-03-21 20:06 UTC
## Part of the "wave-collect – Build Stage 2 of Guided Setup" project
Main issue: https://github.com/Expensify/Expensify/issues/356685
Doc section: https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.f1df48czr1vu
Project: https://github.com/orgs/Expensify/projects/129

### Feature Description
- Use the new API command `CompleteGuidedSetup` and pass new tasks and message's optimistic data, on behalf of Concierge
- Redirect user to root screen ([doc section](https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.focxs4y26zr5))

cc @barttom 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b15d65c2978eba6c</li>
        <li>Upwork Job ID: 1770904809640124416</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by barttom** [comment] 2024-03-22 08:35
Hello! I'm Bartek from Callstack, an expert contributor group, and I would like to work on this issue.

**Comment by joekaufmanexpensify** [comment] 2024-03-25 14:18
@barttom is there an ETA for the PR here?

**Comment by barttom** [comment] 2024-03-25 14:31
> @barttom is there an ETA for the PR here?
There is no set date for that, however I need 5-6 days to finish that.

to start working on that I need merged stage 1 (in review) and new API command (in progress)

**Comment by joekaufmanexpensify** [comment] 2024-04-01 15:00
Sounds good. TY!

**Comment by joekaufmanexpensify** [comment] 2024-04-08 14:14
Looks like PR is now WIP

**Comment by rezkiy37** [comment] 2024-04-09 15:18
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-04-11 15:17
**Updates:**
1. Minor fixes of onboarding messages and text.
2. Integrated a `CompleteGuidedSetupParams` type for the API command.
3. Integrated a `setDisplayName` function to update the user's names locally without sending a request to the backend.
4. Updated a couple of functions in **ReportUtils.ts** to support new passed arguments.
5. Improved the `completeOnboarding` function to:
a. Pass all necessary optimistic data.
b. Hide tasks in **LHN**.
c. Generate a top-mention comment to highlight the Concierge chat.
d. Other changes.

**Note:** All changes have been pushed to the [PR](https://github.com/Expensify/App/pull/39951/files).

Plans for tomorrow:
1. Fix the ordering of actions in the Concierge chat.
2. Fix a mention message preview to exclude an email domain.

<details><summary>Details</summary>
<p>


https://github.com/Expensify/App/assets/57314631/cb97883a-119b-41c3-beb5-59a0920df988



</p>
</details>

**Comment by rezkiy37** [comment] 2024-04-12 15:15
**Updates:**
1. Fixed the ordering of actions in the Concierge chat.
2. Fixed a mention message preview to exclude an email domain.
3. Changed the ordering of the pages.
4. Added task replies optimistically.
5. Fixed text escaping.
6. Prettified codebase.
7. Other changes.

We can do the first review stage for the [draft PR](https://github.com/Expensify/App/pull/39951). I still need to test on all platforms.

<details><summary>Videos</summary>
<p>

https://github.com/Expensify/App/assets/57314631/196a3bb3-9e56-4da1-a098-ee809846841f


https://github.com/Expensify/App/assets/57314631/ec72852f-96f6-400c-886f-4bde483d4eb8

</p>
</details>

**Comment by joekaufmanexpensify** [comment] 2024-04-15 14:03
@rezkiy37 is there an ETA to have a PR in review here?

**Comment by rushatgabhane** [comment] 2024-04-28 20:35
@joekaufmanexpensify could you please assign me this issue for C+ https://github.com/Expensify/App/pull/40688#issuecomment-2073259326

**Comment by joekaufmanexpensify** [comment] 2024-04-29 14:25
Payment due later this week!

**Comment by joekaufmanexpensify** [comment] 2024-05-03 21:02
@francoisl do we need to add adhoc regression tests here? i see a detailed set of manual testing instructions in the design doc, and thought we'd probably pass those all along to applause at once.

**Comment by joekaufmanexpensify** [comment] 2024-05-06 13:09
still pending more discussion

**Comment by joekaufmanexpensify** [comment] 2024-05-06 14:07
Hmm, I see two PRs linked to this issue (https://github.com/Expensify/App/pull/39951 and https://github.com/Expensify/App/pull/40688). 

I think the former is actually the one we want to issue payment for here, and then the latter payment should be handled [here](https://github.com/Expensify/App/issues/40725) (especially since they have separate C+). 

Going to align on this in slack

**Comment by joekaufmanexpensify** [comment] 2024-05-06 14:13
[Discussing ](https://expensify.slack.com/archives/C01SKUP7QR0/p1715004809109359)

**Comment by francoisl** [comment] 2024-05-06 17:11
> do we need to add adhoc regression tests here? i see a detailed set of manual testing instructions in the design doc, and thought we'd probably pass those all along to applause at once.

Yeah it would be great to add. The steps in the design doc were more manual test steps, to make sure everything's implemented as intended.
We're also going to start using the system DM soon for the intro tasks, so we'll need to make a few changes to the steps above. For now I'd recommend holding on adding the regression tests.

**Comment by joekaufmanexpensify** [comment] 2024-05-07 14:47
Sounds good! I will hold for now.

**Comment by joekaufmanexpensify** [comment] 2024-05-07 14:49
We landed on paying out only https://github.com/Expensify/App/pull/39951 in this issue. 

https://github.com/Expensify/App/pull/40688 is going to be paid out in https://github.com/Expensify/App/issues/40725 . As such, @rushatgabhane I am unassigning you here, since the payment for your PR will be handled in that other issue. LMK if you have any questions.

**Comment by joekaufmanexpensify** [comment] 2024-05-07 14:50
That means only payment we need to make here is $250 to @rayane-djouah for C+ review via Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-05-07 14:53
OG job closed, so opened a new one: https://www.upwork.com/jobs/~019187a065e7cd3e15

**Comment by joekaufmanexpensify** [comment] 2024-05-07 14:54
@rayane-djouah offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2024-05-08 13:38
Yes, good call! Payment here should be $500 since this opened before the base payment changed.

**Comment by joekaufmanexpensify** [comment] 2024-05-08 13:39
@rayane-djouah $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-05-08 13:39
Upwork job closed.

**Closed** 2024-05-08 13:39 UTC
Labels: Daily, Internal, NewFeature, Awaiting Payment
