### ISSUE TITLE
[$500] Task - The "Chat Report" briefly displays when the receiver clicks on a sent task before loading the task details and returns to the chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29036] opened 2023-10-06 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account
2. Open User B's chat
3. Go to the "Assign task" section
4. Create a task by entering a title
5. Open another browser and log in to User B's account
6. Click on the sent task for details and then click on User A’s chat before the task details have fully loaded
## Expected Result: 
Chat report should not be displayed when the receiver clicks on a sent task before loading the task details and returns back to the chat
## Actual Result: 
The chat report briefly appears when the receiver clicks on the sent task before the task details have fully loaded and then returns back to the chat

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native - emulator not working for the contributor
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/f3ab8cca-2d09-46ea-8c1e-6419abd84e72

https://github.com/Expensify/App/assets/38435837/21c15601-3a65-4916-a2ff-a655ccc1d61f

https://github.com/Expensify/App/assets/38435837/bd259f1f-e56d-42ef-a498-2d1e0ba9e004

https://github.com/Expensify/App/assets/38435837/3152f2f6-d3f3-4a4f-a734-ac27d6ba6083

https://github.com/Expensify/App/assets/38435837/ef6b0e3d-cece-4fbf-96cc-05e553f82fd0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696617667600819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bf63c7fac0f0222</li>
        <li>Upwork Job ID: 1710393474434949120</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-10-06 23:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The "Chat Report" briefly displays when the receiver clicks on a sent task before loading the task details and returns to the chat

### What is the root cause of that problem?
`TaskPreview` is trying to use the default `reportName` from its optimistic data when the detail is still being loaded.

https://github.com/Expensify/App/blob/1b93fc90abc831c118577a67beb960b6b9c4e2cb/src/components/ReportActionItem/TaskPreview.js#L73-L74

When detail is loading, the taskTitle is rendering from this data:
https://github.com/Expensify/App/blob/1b93fc90abc831c118577a67beb960b6b9c4e2cb/src/libs/actions/Report.js#L459-L461

### What changes do you think we should make in order to solve the problem?
Prefer to use `childReportName` from action first, since that information is already available to the user.

Change this line:

https://github.com/Expensify/App/blob/1b93fc90abc831c118577a67beb960b6b9c4e2cb/src/components/ReportActionItem/TaskPreview.js#L74

to:

```
const taskTitle = props.action.childReportName || props.taskReport.reportName;
```

### What alternative solutions did you explore? (Optional)

Return the bank error earlier at the `ConnectBankAccountManually` API.

**Comment by abhikam395** [comment] 2023-10-06 23:31
It reads value from reportName variable inside value object

**Comment by paultsimura** [comment] 2023-10-06 23:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a tack recipient opens the task report, its name is set to "Chat Report" for a moment.

### What is the root cause of that problem?
In the `TaskPreview` component, we are building the `taskTitle` this way:

https://github.com/Expensify/App/blob/7130361eb309046440ec9f820ddf69731ccb61ec/src/components/ReportActionItem/TaskPreview.js#L74

It should take `props.action.childReportName` if the `props.taskReport.reportName` is absent.

However, when the recipient opens the task report, we send an `OpenReport` API command, and in it we set the default report name "Chat Report" optimistically:

https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/libs/actions/Report.js#L454-L462

So when the user opens the report, the `props.taskReport.reportName` is already present, but it has value "Chat Report".

### What changes do you think we should make in order to solve the problem?
We should rely not only on the `taskReport.reportName` being present, but it also having a reportID, which will mean that the report is loaded:

```diff
-   const taskTitle = props.taskReport.reportName || props.action.childReportName;
+   const taskTitle = props.taskReport.reportID && props.taskReport.reportName ? props.taskReport.reportName : props.action.childReportName;
```



### What alternative solutions did you explore? (Optional)

**Comment by Victor-Nyagudi** [comment] 2023-10-07 13:29
Possible dupe of https://github.com/Expensify/App/issues/24460 or maybe similar root cause.

**Comment by ayazhussain79** [comment] 2023-10-07 13:37
This https://github.com/Expensify/App/issues/24460 bug is not reproducible

**Comment by Victor-Nyagudi** [comment] 2023-10-07 13:48
Edited.

**Comment by joekaufmanexpensify** [comment] 2023-10-10 19:23
Not overdue. I will triage today

**Comment by joekaufmanexpensify** [comment] 2023-10-10 20:33
I can't reproduce this on my end. The skeleton UI isn't used when I try to click into a task, so there is no chance to click the task, and then click the parent chat in LHN before the task loads. 

https://github.com/Expensify/App/assets/54866469/b28b5b4f-def9-4f53-bb9a-9b37a545d15e

**Comment by situchan** [comment] 2023-10-10 20:42
@joekaufmanexpensify that's because report data is already cached locally. Can you try again after logout and re-login?

**Comment by paultsimura** [comment] 2023-10-10 20:42
@joekaufmanexpensify I've just reproduced it in prod. It's not inconsistent – all you should do is just test on slow internet (you can mimic it on the Network tab, similar to going offline).

Also, make sure that you share the task with user B, but don't assign it to them. Just for the experiment's clarity.

https://github.com/Expensify/App/assets/12595293/dd5bcf7a-8714-4eaf-be44-d9cc59e7d9f7

**Comment by joekaufmanexpensify** [comment] 2023-10-16 19:06
Got it. I will try both of those and see if I can reproduce.

**Comment by joekaufmanexpensify** [comment] 2023-10-18 21:12
I still can't consistently reproduce this, even after trying right after signing in, and throttling my network requests to slow 3G. 

https://github.com/Expensify/App/assets/54866469/df37d471-7552-4dbc-b133-2458128902fd

**Comment by joekaufmanexpensify** [comment] 2023-10-18 21:14
Even if this was consistently reproducible though, I'm not sure this would warrant doing anything. Since it seems like right after the report data is cached locally, this doesn't happen. 

Which would mean someone would need to have either just signed in/have bad network connection, and then click into a task and quickly try and click the parent chat before the task loads. Which doesn't really seem like a super user action, unless someone is trying to test this.

**Comment by joekaufmanexpensify** [comment] 2023-10-18 21:14
Closing for now!

**Closed by joekaufmanexpensify** 2023-10-18 21:14 UTC
Labels: External, Daily, Help Wanted, Bug
