### ISSUE TITLE
Contact Method – Received email twice when add new Contact Method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46723] opened 2024-08-02 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4808025
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to account settings > Profile
4. Click on "Contact Method"
5. Click on "New Contact method"
6. Add a email you have access to
7. Go back to the contact method list and click on the previously added email
8. Open email and observe number of new messages for this account
9. Copy the Magic Code included in the validation email

## Expected Result:
Received one email Verify secondary email

## Actual Result:
Validation code is expired. Received email twice: Verify secondary email and a Magic sign-in code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8a12a7c3-d7f1-4793-9acf-35bf51e137bd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-02 13:54
We think that this bug might be related to #vip-vsp

**Comment by Julesssss** [comment] 2024-08-02 15:09
@arosiclair @dangrous -- I see changes to Auth which seem a likely cause of this regression: https://github.com/Expensify/Auth/pull/11815

This other Web PR could be related [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/42909), but I think this is less likely than the Auth PR above.

**Comment by Julesssss** [comment] 2024-08-02 15:10
If this was App I'd remove the blocker label, but I think this could effect OldDot too.

**Comment by dangrous** [comment] 2024-08-02 21:33
yeah i agree with @arosiclair, ours might change the template but wouldn't change the number of emails, as far as I can tell

**Comment by Julesssss** [comment] 2024-08-05 11:00
Ah, okay thanks for sharing. I'll keep looking.

**Comment by thienlnam** [comment] 2024-08-06 01:37
Caused by https://github.com/Expensify/App/pull/45395
Fixed in https://github.com/Expensify/App/pull/46846

**Comment by trjExpensify** [comment] 2024-08-06 01:38
Thread [here](https://expensify.slack.com/archives/C07J32337/p1722893579636489) in #deployers for reference.

This [App PR](https://github.com/Expensify/App/pull/45395) is the culprit firing off two API calls to `RequestContactMethodValidateCode` when re-visiting the contact page, so shouldn't be a web deploy blocker. 

Reverted it on an adhoc build to test:

https://github.com/user-attachments/assets/95c397a0-9a4d-45af-add9-cf8b0a8ee4ec

**Comment by marcaaron** [comment] 2024-08-06 03:55
No C+ on this one so gonna close it out.

**Closed by marcaaron** 2024-08-06 03:55 UTC
Labels: Engineering, Daily
