### ISSUE TITLE
[Hold] Chat - Attachments thumbnail becomes blank for a moment in the preview when loading spinner appears 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8501] opened 2022-04-05 23:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/[](javascript:)
2. Log in with any account
3. Click on Plus button
4. Attach any picture

## Expected Result:
Attachment is visible all the time while uploading

## Actual Result:
Attachment is blank for a moment while uploading

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Mobile Web

**Version Number:** 1.1.51.0
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/161866786-b4766449-d13b-4477-a682-fe5d8bc57583.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment] 2022-04-11 21:26
Whoops didn't mean to remove Overdue directly

**Comment by johnmlee101** [comment] 2022-04-11 21:27
This seems like a minor issue that we could open up to be fixed. The issue is when we switch the local version of the photo to the uploaded version. We should make sure its ready to be fully rendered before removing the thumbnail and spinner.

**Comment by thesahindia** [comment] 2022-04-11 22:14
I think this will be fixed here https://github.com/Expensify/App/issues/8590

**Comment by JmillsExpensify** [comment] 2022-04-13 03:38
Let's go ahead and put a hold on it then, and if it can't be reproduced in testing once #8590 goes live, we can close.

**Comment by JmillsExpensify** [comment] 2022-04-18 21:57
Keeping open until the related issue gets further along in the PR process.

**Comment by JmillsExpensify** [comment] 2022-04-25 01:34
All the action is still in #8590

**Comment by JmillsExpensify** [comment] 2022-05-02 15:14
Still working out linked issue above.

**Comment by JmillsExpensify** [comment] 2022-05-10 21:12
Contributor hired in the linked issue above.

**Comment by JmillsExpensify** [comment] 2022-05-17 04:24
Still working through the considerations in the linked issue.

**Comment by JmillsExpensify** [comment] 2022-05-23 15:30
Same same in the linked issue. I'm still keeping a weekly on this one since we've landed at C+ PR review.

**Comment by JmillsExpensify** [comment] 2022-05-31 02:57
Still discussing in the linked issue.

**Comment by JmillsExpensify** [comment] 2022-06-07 13:54
Great discussion in the linked issue, still going.

**Comment by JmillsExpensify** [comment] 2022-06-15 13:21
@michaelhaxhiu Looks like https://github.com/Expensify/App/issues/8590 is in production now and nearly through the hold for the regression period. What do you think about taking this issue now? Did we end up resolving this, or should we take this issue off hold?

**Comment by michaelhaxhiu** [comment] 2022-06-16 13:26
@JmillsExpensify nice timing 😃 .

Ok so - this is actually an obsolete bug report now, as far as I can see! The fix in #8590 changed the behavior of uploading images and now we don't show a blank white screen. [This PR fix](https://github.com/Expensify/App/pull/9346#issue-1263887504) has some videos of uploads to demonstrate.

I think we can close this now!

**Closed** 2022-06-20 14:17 UTC
Labels: External, Engineering, Monthly
