### ISSUE TITLE
Room-After sending room name as mention, header & title changed as html

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48995] opened 2024-09-11 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap fab-- start chat
3. Create a room
4. Tap on header -- room description
5. Paste @[jaihanumanblog+0876@gmail.com](mailto:jaihanumanblog+0876@gmail.com)
and save it
6. Enter #room name and send the message

## Expected Result:
After sending room name as mention, header & title must not change.

## Actual Result:
After sending room name as mention, header( {"html":"","mentionedAccountIDs":[18306611]})
&title ( {"html":"@hidden) changed as HTML
<img width="852" alt="image" src="https://github.com/user-attachments/assets/12c7d02c-9244-4d98-8699-4000e0ea1e62">

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/564a1326-101f-4413-a3da-c9d57e439c33

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-09-11 17:22
Odd BE bug

**Comment by slafortune** [comment] 2024-09-13 20:03
I wasn't able to recreate this the same - I get the HTML - but not "hidden"
@FitseTLT @izarutskaya are you still able to recreate this? or has it been partially fixed?
![Screenshot_20240913_150051_New Expensify](https://github.com/user-attachments/assets/605c3d20-1a49-44ff-b12d-c396895fc19c)

**Comment by FitseTLT** [comment] 2024-09-13 20:06
> I wasn't able to recreate this the same - I get the HTML - but not "hidden" @FitseTLT @izarutskaya are you still able to recreate this? or has it been partially fixed? ![Screenshot_20240913_150051_New Expensify](https://private-user-images.githubusercontent.com/11725910/367431285-605c3d20-1a49-44ff-b12d-c396895fc19c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTgxNTIsIm5iZiI6MTcyNjI1Nzg1MiwicGF0aCI6Ii8xMTcyNTkxMC8zNjc0MzEyODUtNjA1YzNkMjAtMWE0OS00NGZmLWIxMmQtYzM5Njg5NWZjMTljLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDIwMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MjZlYTZjYjVmMzcwODE3ZTUzZmI4MzIzOGMzOTI1OTU3MjRhZWQ5NzA0YmVlYmZkNTE5ZjVmZTI4M2IxNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c5rVxp2ejKwbM41pwh-TjnoC_FRyg_1YXNTC7ZEgTvU)

@slafortune  Still it is a bug and a backend one; better to get engineering :eyes:

**Comment by slafortune** [comment] 2024-09-13 20:36
Yep - I will but making sure that the reported bug is correct!

**Comment by slafortune** [comment] 2024-09-16 18:20
Updated and added Internal and Hotpick for this BE bug

**Comment by slafortune** [comment] 2024-09-23 15:58
Updating the vip-vsb internal issue to weekly

**Comment by muttmuure** [comment] 2024-09-24 15:36
Dupe of https://github.com/Expensify/App/issues/49355

**Closed by muttmuure** 2024-09-24 15:36 UTC
Labels: Weekly, Internal, Bug, Hot Pick
