### ISSUE TITLE
After changing the currency when you IOU again the currency get's back to the default one - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8936] opened 2022-05-11 03:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Send or Request money from someone
 2. You will see a page to add amount click on the currency sign and choose a different currency
 3. Now go through the flow and again try to send or request money, check the currency won't be the one that you chose earlier

## Expected Result:
It should stay at the chosen currency

## Actual Result:
It keeps changing back to default

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.57-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/167765811-5ed4e092-7204-41ae-b75a-03dd6cb05f28.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650136064733399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2022-05-11 09:29
I was able to reproduce this, but disagree that it's an issue or a change we want to make. From the original design doc, the design of this (from a currency perspective) is:

> We’ll determine a user’s default currency using the same logic as we do on E.com today. For the avoidance of doubt that’s:
> * First, based on the GPS location, if location services are enabled
> * Next, based on the IP address (obtained on app load)
> * If both of those fail, then we’ll fallback on the default currency of the user’s primary policy 

So, this is working by-design, and at the moment I don't think that we should change it to make the currency "sticky" across requests. Closing for now, but anyone should feel free to re-open with a problem/solution statement if they feel this should be changed!

**Closed by conorpendergrast** 2022-05-11 09:29 UTC
Labels: Daily

**Comment by Puneet-here** [comment] 2022-05-11 09:53
**Problem**: Let's say a user lives in US and he goes to a different country, now because of his IP the currency will change but because most of the people he request or send money to are in US so now he has to change the currency every time he sends/request money or if a user has most of his clients in US but the user lives in a different country. 

**Solution**: We can set the currency based on IP for the first time and if the user changes the currency it will stay changed.
I think this is a good solution because this way the user can keep a currency sticky in which he makes most of his transactions.

cc: @conorpendergrast

**Comment by Puneet-here** [comment] 2022-05-19 10:36
Bump @conorpendergrast
