### ISSUE TITLE
[Waiting for payment] [$500] Members - Invite message doesn't remain when User navigate back to Invite members page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27902] opened 2023-09-20 23:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new Workspace
2. Navigate to Members
3. Tap on Invite button
4. Invite few users
5. Tap Next
6. Edit the Invite message and put new message
7. Navigate back to Invite Members page
8. Tap Next button

## Expected Result:
Invite message should remain when User come back to final Invite page

## Actual Result:
Invite message doesn't remain when User navigate back to Invite members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/331d7c25-7476-445b-a0bf-fe8b0d51b121

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111f805abe8b69c9a</li>
        <li>Upwork Job ID: 1714431162859646976</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-09-21 17:51
I'm unable to test right now due to the site issues and will be traveling for work later today. If I get plane wifi, then I'll try to test either tonight or this weekend.

**Comment by alexpensify** [comment] 2023-09-25 08:22
I'm back online and will try to test soon.

**Comment by alexpensify** [comment] 2023-09-28 07:12
Not overdue, CM tasks are a higher priority right now. I'll test this one soon.

**Comment by alexpensify** [comment] 2023-09-29 06:29
I confirmed this experience but I'm asking in the Open Source room to verify if the lack of stickyness is on purpose.

**Comment by alexpensify** [comment] 2023-10-02 22:51
No update in the Slack convo. I will try bumping again tomorrow.

**Comment by alexpensify** [comment] 2023-10-04 22:18
I bumped the thread again

**Comment by alexpensify** [comment] 2023-10-06 22:31
Only one response so far: 

>Just my opinion (not based on any expected behaviour that I know of) but to me it would make sense to reset the message if the list of users invited changes and keep it sticky if nothing changes

**Comment by alexpensify** [comment] 2023-10-06 22:31
I'm going to keep shopping around for feedback early next week.

**Comment by alexpensify** [comment] 2023-10-09 17:21
I'm OOO today but will work on getting more feedback tomorrow

**Comment by alexpensify** [comment] 2023-10-11 20:31
I've sent another bump in the Slack thread.

**Comment by alexpensify** [comment] 2023-10-13 18:24
Following some feedback that I received, I'm adding a screenshot to clarify the section of the product that this update would change: 

![image](https://github.com/Expensify/App/assets/8107070/47ff12f5-95c2-409c-9351-c78d6f73ccf0)

**Comment by alexpensify** [comment] 2023-10-16 23:26
I asked again here for feedback: https://expensify.slack.com/archives/C03U7DCU4/p1697498602091889

**Comment by alexpensify** [comment] 2023-10-18 00:01
Assigning the external label, after much discussion, it's been decided that the copy sent in an invite should be saved for the next invite even if the tab is closed. If there are edits, then those are saved for the next invite. 

@allroundexperts keep us posted if the proposal will work or if we need to wait for more.

**Comment by alexpensify** [comment] 2023-10-18 14:55
Making this `external` again since the solution took time to get a clear path forward on how we wanted this section to work.

**Comment by alexpensify** [comment] 2023-10-20 21:14
@allroundexperts can you review if the proposal will fix this issue?

**Comment by alexpensify** [comment] 2023-10-23 16:15
Daily Update: waiting for @allroundexperts to review

**Comment by cead22** [comment] 2023-10-25 18:27
Thanks @neonbhai for the proposal. I actually think this is more a feature than it is a bug, and I don't think it's worth it to implement the proposed solution, because it'll add a logic and complexity that imo is not worth the effort or the maintenance, for what imo is a big edge case.

I think we should close this issue

**Comment by cead22** [comment] 2023-10-26 15:51
Ah yes I like that proposal better, I don't know how I missed it yesterday, maybe GH hid it. Does the solution support multiple workspace, ie, if you type something in the draft, and that gets saved in Onyx, and you go back and switch to another workspace and try to invite people, does the draft from the other workspace show up?

---

> @cead22 I think it's confirmed [here](https://github.com/Expensify/App/issues/27902#issuecomment-1767376580) that it's a joint decision to make it sticky.

One clarification I want to make is that what was agreed there, and discussed on slack, was to save the welcome message **after people get invited**, not in this back and forth flow of selecting people, editing the messages, and going back to select more people.

Given that, I was going to insist we didn't fix this, but after reading @tienifr 's proposal, and seeing that we must already have some "magic" for saving drafts with `shouldSaveDraft`, I'm more inclined to fix this

**Comment by mallenexpensify** [comment] 2023-10-27 19:07
@alexpensify you're going to need to hire folks manually for the job, for some reason auto-hiring isn't working right now.  Discussing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1698433508049909?thread_ts=1698428062.757319&cid=C01SKUP7QR0)

**Comment by alexpensify** [comment] 2023-10-27 19:11
Ok, I'll do so on Monday since I'm OOO today. Thanks for flagging @mallenexpensify!

**Comment by alexpensify** [comment] 2023-11-01 18:33
@tienifr - can you please apply for this job, so I can prepare for the payment date: 

https://www.upwork.com/jobs/~0111f805abe8b69c9a

Thanks!

**Comment by alexpensify** [comment] 2023-11-03 16:46
Awesome and it looks like the PR is ready for review by @allroundexperts.

**Comment by alexpensify** [comment] 2023-11-07 00:26
Now we wait for the automation to kick in here.

**Comment by mountiny** [comment] 2023-11-07 20:39
Whoops wrong issue disregard!

**Comment by alexpensify** [comment] 2023-11-09 01:00
Reassigning another 🐛  team member, I'm going OOO until Tuesday, November 14, and will take it back if it's still open by my return date.

@muttmuure   - Required action from the team: 

Please keep an eye out, I haven't been able to review the deploy blocker and it will delay the payment process for this one. Thanks!

**Comment by alexpensify** [comment] 2023-11-15 01:39
I'm back and unassigning my buddy. 

--- 

@allroundexperts - can you please confirm if there is regression here? I want to complete the payment process this week. Thanks!

**Comment by alexpensify** [comment] 2023-11-16 20:42
@allroundexperts - any update here? I would like to close this one out tomorrow before I'm OOO again next week. Thanks!

**Comment by cead22** [comment] 2023-11-16 21:29
Agreed

**Comment by alexpensify** [comment] 2023-11-19 16:55
Reassigning another team member, I'm going OOO until Monday, November 27, and will take it back if it's still open by my return date.

@strepanier03  - Required action from the team:

I didn't get a chance to start the payment process and input a payment summary here. This one is ready for the payment process. Thanks for helping to make sure everyone here is paid out. Thanks!

**Comment by allroundexperts** [comment] 2023-11-27 21:23
Requested @strepanier03!

**Comment by JmillsExpensify** [comment] 2023-11-28 02:21
$500 payment approved for @allroundexperts based on summary above.

**Closed** 2023-11-28 22:38 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
