### ISSUE TITLE
Web -  App crashes when splitting bill with email "—-@—-.com"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21813] opened 2023-06-28 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Tap on the plus sign
2. Select "Split Bill" and input the desired number of money, then tap "Next"
3. Enter the email "—-@—-.com" and tap "Next"
4. Observe that the app crashes

## Expected Result:
The app should not crash when splitting the bill with the email "—-@—-.com"

## Actual Result:
The app crashes when splitting the bill with the email "—-@—-.com"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/88ca9ca7-c7e7-47f4-85bc-43809f50997e

https://github.com/Expensify/App/assets/93399543/e04fafdc-1336-4ac4-a228-2a5060474156

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687860215891219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment] 2023-06-28 17:16
looks to be a dupe of https://github.com/Expensify/App/issues/21268

**Closed by abekkala** 2023-06-28 17:16 UTC
Labels: Daily, Bug
