### ISSUE TITLE
[HOLD #35006] Images are being posted multiple times in task report

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35017] opened 2024-01-23 23:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-9
**Reproducible in staging?:** Unknown
**Reproducible in production?:** Unknown
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705456916327209

## Action Performed:
1. Post image in a conversation
2. Chat with another user in the same conversation

## Expected Result:
The image to only post once

## Actual Result:
Image initially posts then two other of the same chat show after a few messages (other user confirmed they see the images too)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/49fdc8d2-3f55-4f29-80d3-8fc8a64f4c5f)

![image](https://github.com/Expensify/App/assets/44479856/add2b947-955d-4f83-8dd1-a7d733736695)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2024-01-23 23:38
@isagoico mentioned this might be related to
- https://github.com/Expensify/App/issues/35006#issuecomment-1907093768

Putting it on hold pending that, since upload comes in the process before viewing multiple images. (and/or.. one could be closed to consolidate if someone's confident they're directly related and should be fixed together)

**Comment by strepanier03** [comment] 2024-01-26 21:21
Got it, thanks Matt. I'm moving to weekly for now and will check on it next week.

**Comment by strepanier03** [comment] 2024-02-14 04:24
Hold GH is still open, pausing here for another week.

**Comment by strepanier03** [comment] 2024-02-23 05:31
Closing until this is reproduced. The GH this was held on was closed for the same reason.

**Closed by strepanier03** 2024-02-23 05:31 UTC
Labels: Weekly, Needs Reproduction, Overdue, Bug
