### ISSUE TITLE
[CVP] [CRITICAL] Sending a new IOU to a closed account doesn't trigger a notification.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44615] opened 2024-06-28 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719489439658019

## Action Performed:
1. As user A submit an IOU  via `ConvertTrackedExpenseToRequest` to a user B (Account status in closed condition or account that does not exist in expensify)
## Expected Result:
User B should receive an email after a closed account is created inviting them to use Expensify.
## Actual Result:
No email received for user B
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ab81741b-e250-4f02-afee-04a254e3574c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8f4506a30d10a8c</li>
        <li>Upwork Job ID: 1810338375835149529</li>
        <li>Last Price Increase: 2024-07-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by DylanDylann** [comment] 2024-07-09 08:54
@isabelastisser It seems this is a BE bug, please add an internal label to get an eye from the internal engineer

**Comment by isabelastisser** [comment] 2024-07-12 19:17
Waiting for engineering assignment.

**Comment by isabelastisser** [comment] 2024-07-15 18:38
@mallenexpensify, can you please confirm that I applied the correct labels to get the internal engineering assignment? Thanks!

**Comment by mallenexpensify** [comment] 2024-07-15 22:28
You can't auto-assign an engineer by adding the `Internal` label anymore 😿 
Can you post in #vip-vsb in to get 👀 on the issue to see how it should be prioritized? I think alll VIPs are paused right now, so this might be as well.

**Comment by isabelastisser** [comment] 2024-07-16 14:48
Thanks, @mallenexpensify! I will start a discussion now.

**Comment by isabelastisser** [comment] 2024-07-16 14:50
[Slack discussion](https://expensify.slack.com/archives/C066HJM2CAZ/p1721141444168859)

**Comment by isabelastisser** [comment] 2024-07-18 19:53
I bumped the discussion now.

**Comment by isabelastisser** [comment] 2024-07-18 20:03
I will be OOO tomorrow and next week, so I am reassigning this until I return on July 29. Thanks, @slafortune!

Status: Waiting for proposals.

**Comment by garrettmknight** [comment] 2024-07-19 16:07
Changing priority to Critical since this is stopping the critical viral path.

**Comment by slafortune** [comment] 2024-07-23 16:46
Critical Hot Pick - waiting for an internal engineer

**Comment by trjExpensify** [comment] 2024-07-25 10:40
@puneetlath @twisterdotcom I was looking at the [logs for this](https://staging.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2289963b46bf5a43e9-EWR%22)+AND+timestamp:%5B2024-06-25T15:11:06.752Z+TO+2024-06-25T17:11:06.752Z%5D&index=logs_expensify-029093) as I was intrigued. 

Seems like we call the `ConvertTrackedExpenseToRequest` command. 

Then we got to the `CreateReportAction` command, and that's where we hit the error: 

```
Throwing exception with message: '408 Unauthorized - Account closed' from auth/lib/AuthToken.cpp:1211
Error processing command 'CreateReportAction' (408 Unauthorized - Account closed), ignoring.
```

which seems like it's throwing [here](https://github.com/Expensify/Auth/blob/f4cc21d2c4d84d440063545f0994537ad0a9e1f1/auth/lib/AuthToken.cpp#L1223-L1225). 

But I'm not sure why there isn't a valid `authTokenType` here. 🤔 

@thienlnam, I believe you built this flow with Track expense. Any ideas?

**Comment by thienlnam** [comment] 2024-07-25 19:57
Not sure 🤔 it looks like the command completed successfully but then as part of the command it forwarded a CreateReportAction command. I wonder if this is because the account is unvalidated, and it's trying to create a chat with another new user

**Comment by trjExpensify** [comment] 2024-07-25 21:28
Yeah, why is the account created in the closed state in this case? I thought we only did that for Concierge/support cases and maybe domain control or something.

**Comment by thienlnam** [comment] 2024-07-25 22:20
> Yeah, why is the account created in the closed state in this case?

I am pretty sure we normally create closed accounts in those cases. Like when you try to chat with a user that doesn't exist it will create the account in a closed state. Probably just so they have to validate it before they actually want to use it

**Comment by trjExpensify** [comment] 2024-07-25 22:25
>Probably just so they have to validate it before they actually want to use it

Doesn't an open account in an unvalidated state achieve the same thing though? 🤔

**Comment by thienlnam** [comment] 2024-07-25 22:37
Yeah that does, I am not entirely sure why we create closed accounts - maybe it's so they don't get the newsletter emails?

**Comment by trjExpensify** [comment] 2024-07-26 00:00
I just sent an IOU via the standard `Submit expense` flow to an email address that doesn't have an account and they received it on email: 

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/1455d0c9-7753-4ed2-9dd0-b6eef111ce0c">

The account was created in the closed state as well, so can't be the sole reason: 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/711219aa-8f44-4948-b4ce-d9f041864dd2">

**Comment by quinthar** [comment] 2024-07-26 05:46
Hm, I'm trying to test the CVP and have had Alice (quinthar+cvp.alice0@gmail.com) send an IOU to Bob (quinthar+cvp.bob0@gmail.com) and Bob never got any IOU email.  I was able to get a magic link sent to Alice (which is itself a bug: I don't know why Alice was signed out), and I manually sent test emails to make sure it was possible to receive on those addresses.  But I'm not receiving any IOU to Bob.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ba8ca1ee-9af7-4277-b136-9e640d8f372c">

**Comment by quinthar** [comment] 2024-07-26 06:00
I even tried having Alice send a "custom subject line" message to Bob to see if the email would go through, still nothing.  When I go to sign into Bob's account, it recognizes it:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/758b954a-a8be-4f18-9297-3048c9eb6800">

And it correctly sent the magic code:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e11776ee-a5c6-4276-8151-b6c6a2495a7d">

**Comment by trjExpensify** [comment] 2024-07-26 14:54
>Hm, I'm trying to test the CVP and have had Alice ([quinthar+cvp.alice0@gmail.com](https://www.expensify.com/_support/?supportEmail=quinthar%2Bcvp.alice0%40gmail.com&comment=better%20supportal%20issue%20nubmer%3A%2044615&location=_support/)) send an IOU to Bob ([quinthar+cvp.bob0@gmail.com](https://www.expensify.com/_support/?supportEmail=quinthar%2Bcvp.bob0%40gmail.com&comment=better%20supportal%20issue%20nubmer%3A%2044615&location=_support/)) and Bob never got any IOU email.

Was that the same scenario as Puneet & Ted here hitting the`ConvertTrackedExpenseToRequest` Track > selfDM > submit flow? 

Or did you straight-up just global create > submit expense > Bob?

**Comment by quinthar** [comment] 2024-07-26 21:07
Same scenario

**Comment by isabelastisser** [comment] 2024-07-29 15:29
I'm back, taking this. Thanks, @slafortune!

**Comment by danielrvidal** [comment] 2024-07-29 22:28
I also just went through the CVP test and experienced this. I think we should update the title or problem that this is not happening to all IOUs, it's happening to IOUs when you Track Expense > Create the expense > Submit it to someone else.

**Comment by DylanDylann** [comment] 2024-08-06 10:35
@isabelastisser Awaiting an internal engineer to address this issue (applied Hot Pick label)

**Comment by thienlnam** [comment] 2024-08-09 23:55
We'll just need to add an email template to the auth method that creates the account - looks like @dangrous actually has to do this for a different issue so we'll just use that as well https://expensify.slack.com/archives/C03TQ48KC/p1723235974705039

**Comment by dangrous** [comment] 2024-08-12 13:39
(I'll be adding that to [this PR](https://github.com/Expensify/Auth/pull/11989) which should hopefully be up for review by EOD today, so merged... later this week?) Glad I happened to reach out about that haha and it can be useful elsewhere!

**Comment by isabelastisser** [comment] 2024-08-12 20:01
Not overdue.

**Comment by thienlnam** [comment] 2024-08-19 13:07
Both PRs merged, we're just waiting for the Web-PR to deploy to production now

**Comment by isabelastisser** [comment] 2024-08-21 19:11
Not overdue.

**Comment by DylanDylann** [comment] 2024-08-26 09:05
@thienlnam Could you please give an update on this issue?

**Comment by trjExpensify** [comment] 2024-08-26 12:58
Web PR hit prod 5 days ago, so we should be good to close @isabelastisser if the issue is resolved.

**Comment by isabelastisser** [comment] 2024-08-27 00:17
No payments are required. All set!

**Closed by isabelastisser** 2024-08-27 00:17 UTC
Labels: Daily, Internal, Bug
