### ISSUE TITLE
[HOLD for payment 2022-08-04] [$250] App crashes when navigating back from bank account page - reported by @Puneet-here

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#10133] opened 2022-07-27 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click on any workspace
3. Click bank account > connect manually
4. Press back arrow

## Expected Result:
The site shouldn't crash

## Actual Result:
The site crashes

## Workaround:

None

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

https://expensify.slack.com/files/U037WGYT199/F03RBB7DB4L/screen_recording_2022-07-27_at_10.32.07_pm.mov

**Version Number:** v1.1.86-4
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658941553744969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-07-27 17:58
Added External Label, since this deploy blocker was reported by a contributor 🙌

**Comment by mountiny** [comment] 2022-07-27 17:59
@Puneet-here shared an error from condole:
![image](https://user-images.githubusercontent.com/36083550/181340771-c1450ba6-29ba-4f9f-9c2d-e8022aa80d4a.png)

**Comment by stitesExpensify** [comment] 2022-07-27 18:48
@nkuoch it looks like this is related to your PR here https://github.com/Expensify/App/pull/9423/files

**Comment by mountiny** [comment] 2022-07-27 18:54
I think Nathalie is and will be OOO for a while (based on looking into a calendar)

**Comment by stitesExpensify** [comment] 2022-07-27 18:55
NP, i'm looking into it right now. I'm unable to reproduce though.

**Comment by neil-marcellini** [comment] 2022-07-27 18:57
I'm also unable to reproduce on Web dev staging, but I can reproduce it on staging.

**Comment by stitesExpensify** [comment] 2022-07-27 19:00
Based on that error my guess was [this line](https://github.com/Expensify/App/pull/9423/files) but like Neil said, it's working correctly on dev.

**Comment by stitesExpensify** [comment] 2022-07-27 19:02
Confirmed on staging that that line is the problem, still unsure why it isn't working there but is working on dev. 

I think the fix might just be removing `this` from that line and calling the function directly

**Comment by neil-marcellini** [comment] 2022-07-27 19:04
Totally, may I put up a quick PR for that?

**Comment by stitesExpensify** [comment] 2022-07-27 19:06
Go for it. Feel free to tag me as the reviewer. 

No promises on it working though, just a guess haha

**Comment by neil-marcellini** [comment] 2022-07-27 19:07
Awesome thanks. The error message calls out that line specifically so I think it's very likely the problem.

**Comment by Puneet-here** [comment] 2022-07-27 22:08
Is this eligible for the reporting?

**Comment by mountiny** [comment] 2022-07-27 22:26
I think it should as it was a valid problem and actually very valuable since we dont want to get the bugs all the way to production.

@laurenreidexpensify has been assigned as CM and she will help us to sort this out! 

Thank you Puneet!

**Comment by laurenreidexpensify** [comment] 2022-07-28 13:33
@Puneet-here I'll create an upwork job now and get you paid 👍🏽

**Comment by laurenreidexpensify** [comment] 2022-07-28 13:37
https://www.upwork.com/ab/applicants/1552649042546278400/job-details

**Comment by laurenreidexpensify** [comment] 2022-08-02 07:00
@kadiealexander 👋 I'm OOO from tomorrow so reassigning for payment. TLDR is that @Puneet-here reported a critical bug that we expedited for a fix so it didn't get a chance to go through the normal flow with C+ etc as Brandon and Neil fixed it internally. Assuming there's no regression, this is all good to pay on 4 august - job in Upwork here https://www.upwork.com/ab/applicants/1552649042546278400/job-details. Thanks!

**Comment by kadiealexander** [comment] 2022-08-05 02:14
Reporting bonus paid! Thanks for your help @Puneet-here.

**Closed by kadiealexander** 2022-08-05 02:14 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Awaiting Payment
