### ISSUE TITLE
[$250] Web - Tasks - Red error dot doesn't disappear after removing the error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46778] opened 2024-08-03 21:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+angddsddaidns@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Navigate to any chat
3. Click on the plus icon in the compose box
4. Select "Assign Task
5. Add a title, then click "Next
6. Add yourself as the assignee
7. Confirm the task
8. Open the task
9. Reassign it to another user (Account B)
10. Reassign it again to a non-existing/new user
11. Log in as Account B
12. Navigate to the task assigned to account B on step 9
13. Open the task and mark it as complete
14. An error message appears; click the "x" button

## Expected Result:
After clicking on the "x" to close the error the red dot in the LHN should disappear

## Actual Result:
The red dot does not disappear after clicking on the "x" and closing the error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cbbb9d15-6958-4bd4-82d4-e6079343bcd7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fad8c0dfda58f0e</li>
        <li>Upwork Job ID: 1820572529440277405</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103469183</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment] 2024-08-03 21:23
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-03 21:23
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-08-04 12:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The RBR doesn't disappear after dismissing the report action error message.

### What is the root cause of that problem?
The RBR will show if there are report action errors or report errors. When we complete the task in our case, the BE returns a "Report no longer exists" that is set to the report error fields, but actually, the complete task request is success. This can be verified by looking at the other device and see that the task is completed. So, this is the first issue and needs to be fixed on the BE.
<img width="507" alt="image" src="https://github.com/user-attachments/assets/9b666362-c6c7-4e9a-a1b7-b1bc0ec8b6e9">

The second issue is, that the failure data for the complete task always says that the user doesn't have permission.
https://github.com/Expensify/App/blob/862d4aaddf06e79072d8db298a2169435cb4f0fe/src/libs/actions/Task.ts#L375-L377
https://github.com/Expensify/App/blob/862d4aaddf06e79072d8db298a2169435cb4f0fe/src/languages/en.ts#L3571

The error message can be misleading.

So, we have 2 errors, 1 report `errorFields` and 1 report action error.

Last, when we dismiss the report action error, the RBR still shows because the report `errorFields` still exists. The issue here is that the RBR still shows but the user can't see what is wrong with the chat/report. So, the RBR still shows is not the issue, but rather, there is no error message shown for the report `errorFields`.

### What changes do you think we should make in order to solve the problem?

We need to add the complete task `errorFields` to the task view OfflineWithFeedback.
https://github.com/Expensify/App/blob/862d4aaddf06e79072d8db298a2169435cb4f0fe/src/components/ReportActionItem/TaskView.tsx#L66-L68

```
errors={report.errorFields?.editTask ?? report.errorFields?.createTask ?? report.errorFields?.completeTask}
```

This way, the user will be able to dismiss the report `errorFields` and the RBR will be gone from the LHN.

<img width="773" alt="image" src="https://github.com/user-attachments/assets/05b9c018-a6a8-47c2-8462-30a8526197e9">

For the failure data message (You don't have permission...), I think we can have a more generic error message if needed, or we can leave it as it's if the current message is fine.

**Comment by johncschuster** [comment] 2024-08-05 21:27
Hmm... this might fit better under #tasks now that I think about it.

**Comment by johncschuster** [comment] 2024-08-09 21:29
Oh! I just realized the fix we need to apply is a BE fix (sorry – I didn't register that). @MonilBhavsar, given this is part of #vip-vsb, we will likely be closing this since that project has been deprioritized. Can you think of an argument to keep this open?

**Comment by bernhardoj** [comment] 2024-08-10 04:11
@johncschuster it's actually BE and FE issue. The FE issue is that we are not showing the report-level error (RBR), so we can't dismiss it and the RBR in LHN stays.

**Comment by MonilBhavsar** [comment] 2024-08-12 16:34
@johncschuster I think we should fix this bug. May be I missed the discussion where it says we are not prioritising it. Could you please link it

**Comment by johncschuster** [comment] 2024-08-19 21:46
Sorry I missed your comment, @MonilBhavsar!

I'm not sure I can find the original conversation about deprioritizing #vip-vsb, but David (the curator of the project) has confirmed it in a bunch of threads. Here's [one](https://expensify.slack.com/archives/C066HJM2CAZ/p1721729395916419)!

That said, I also notice this is related to #tasks, but that seems to have also been deprioritized.

**Comment by MonilBhavsar** [comment] 2024-08-19 21:53
No worries. I see...
Let's pause for now. If we encounter again and it needs to prioritized. We can reopen.

**Closed by MonilBhavsar** 2024-08-19 21:53 UTC
Labels: External, Daily, Bug
