### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] IOU-User is shown option to submit expense using group.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42261] opened 2024-05-16 10:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap start chat
3. Add a user and create group
4. Tap header -- member -- invite
5. Invite user A
6. Login in mweb as user A
7. As user A, note group chat in lhn
8. As group admin, in Android app remove another user (not user A)
9. In mweb, as member note green dot shown in LHN for removed user
10. In mweb, tap on the chat and navigate to members page
11. In Android app, as group admin tap back and "Leave group"
12. In mweb, note in members page, now member is shown as "admin"
13. Navigate to LHN
14. Tap fab -- submit expense
15. Enter an amount and tap next
16. Select group shown in recent
17. Tap submit

## Expected Result:
User must not be shown option to submit expense using group.

In group user's LHN, when user removed green dot is shown.

## Actual Result:
User is shown option to submit expense using group.

In group user's LHN, when user removed green dot must not be shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4d114db3-faa7-4454-82ea-2b6e84c8a3c2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01099fb6a88b2692fc</li>
        <li>Upwork Job ID: 1791216875339001856</li>
        <li>Last Price Increase: 2024-05-16</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102546813</li>
<li>nkdengineer | Contributor | 102546815</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by izarutskaya** [comment] 2024-05-16 10:17
We think this issue might be related to the #vip-vsb.

**Comment by sakluger** [comment] 2024-05-16 21:20
@joekaufmanexpensify I'm assigning to you while I'm OOO for the next two weeks. I'll take it back over if it's still open after May 31.

**Comment by nkdengineer** [comment] 2024-05-17 10:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is shown option to submit expense using group.

### What is the root cause of that problem?
When we generate the option from `report` [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/OptionsListUtils.ts#L761), we're setting the `login` incorrectly.

In the case of group chat with 1 member, `hasMultipleParticipants` is `false` but it's still a group chat so should not have `login` or `accountID` in the `result` like 1-1 chat.

### What changes do you think we should make in order to solve the problem?

Update [this](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/OptionsListUtils.ts#L761) to 
```
if (!hasMultipleParticipants && !ReportUtils.isGroupChat(report)) {
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment] 2024-05-17 14:23
I can reproduce both parts of the bug. Fixing both makes sense to me!

**Comment by joekaufmanexpensify** [comment] 2024-05-20 13:54
Waiting for @ishpaul777 review

**Comment by nkdengineer** [comment] 2024-05-21 16:57
Thanks for the video @ishpaul777, I can reproduce now.

That 1st issue's a back-end issue. [Proposal updated](https://github.com/Expensify/App/issues/42261#issuecomment-2117247061) to mention how to fix it.

**Comment by joekaufmanexpensify** [comment] 2024-05-23 22:24
Sounds good! Perhaps @chiragsalian can handle the BE portion too after reviewing the proposal?

**Comment by joekaufmanexpensify** [comment] 2024-05-28 14:10
Pending @chiragsalian review of selected proposal

**Comment by joekaufmanexpensify** [comment] 2024-05-29 14:45
@chiragsalian will you be able to review the proposal soon?

**Comment by joekaufmanexpensify** [comment] 2024-05-31 14:35
Bumped Chirag 1:1

**Comment by chiragsalian** [comment] 2024-05-31 20:37
Proposal LGTM. 
Feel free to create a PR to tackle item 2 in your proposal @nkdengineer.

@joekaufmanexpensify could you create another issue to handle issue 1 mentioned by nkdengineer which is backend related?

**Comment by joekaufmanexpensify** [comment] 2024-06-03 13:37
>could you create another issue to handle issue 1 mentioned by nkdengineer which is backend related?

@chiragsalian is the bug not fixed until both of these issues are handled? If so, I kinda feel like it makes sense to handle them both in this issue, since otherwise the bug won't necessarily be fixed when we close the external portion. If you agree, happy to just add this to hot picks, and clarify it needs an internal volunteer (unless you wanted to tackle it).

**Comment by joekaufmanexpensify** [comment] 2024-06-04 13:16
@sakluger I see you're back from OOO, so gonna let you take this one back over. Here's a summary of where we're at: 

- We[ determined](https://github.com/Expensify/App/issues/42261#issuecomment-2117247061) that this bug has both a frontend and backend portion. 
- We [selected a proposal](https://github.com/Expensify/App/issues/42261#issuecomment-2125349645) for the frontend portion, and a PR is now in review. 
- We're [determining how](https://github.com/Expensify/App/issues/42261#issuecomment-2145228603) to proceed with the backend portion. 

LMK if there's anything else I can help with!

**Comment by chiragsalian** [comment] 2024-06-10 22:38
> is the bug not fixed until both of these issues are handled?

Correct, both of these mentioned [here](https://github.com/Expensify/App/issues/42261#issuecomment-2117247061).

> since otherwise the bug won't necessarily be fixed when we close the external portion.

Correct, the bug won't be fixed when we finish just the external portion. But this issue is the externally marked issue so i don't quite follow the statement here.

> If so, I kinda feel like it makes sense to handle them both in this issue

I think i disagree because this issue is marked external so in my K2 it shows up as greyed out. So during busy times its very easy to overlook this issue. Since its gray in my K2 i feel like there is nothing immediately actionable for me and so i miss it easily. But now with the fire's hopefully dying out i don't mind either.

> unless you wanted to tackle it

I don't think i can get to it until late of next week or the week after. If its needed sooner we might have to look for someone else.

**Comment by chiragsalian** [comment] 2024-06-26 20:50
Not overdue, hold for payment.

**Comment by sakluger** [comment] 2024-06-26 22:22
The actual payment date is 6/28.

**Comment by sakluger** [comment] 2024-06-28 14:31
Summarizing payment on this issue:

Contributor: @nkdengineer $250, paid via Upwork
Contributor+: @ishpaul777 $250, paid via Upwork

@ishpaul777 could you please complete the BZ checklist today? Thanks!

**Comment by sakluger** [comment] 2024-06-28 20:25
Thank you!

**Closed by sakluger** 2024-06-28 20:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
