### ISSUE TITLE
[$1000] Web - The focus on timezone is highlighted in full in compared to year option on date of birth

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21262] opened 2023-06-21 20:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Settings > Profile >Personal details
3. Select date of birth and select the year field and notice that when you hover over the date years, the focus is not fully covered
4. But now go back and select the timezone and hover over the different options and notice that the timezone options focus are fully covered
5. Thus, there's inconsistency between two areas in the same application

## Expected Result:
The focus on timezone should not be highlighted in full in a similar way how the focus on the year option on date of birth does to maintain consistency OR vice versa

## Actual Result:
The focus on timezone is highlighted in full in compared to year option on date of birth

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4dbd1bf2-f106-4f1f-9cbd-44414179d5fc

https://github.com/Expensify/App/assets/93399543/eeaa350e-661d-4184-b9fb-67741c4dd177

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686757443117449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192d5df321e7923f8</li>
        <li>Upwork Job ID: 1671654443150655488</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by nikhiln** [comment] 2023-06-22 16:26
### Proposal
----

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent UX Behaviour between the dropdown selector i.e. focusing the timezone and year dropdown are different

### What is the root cause of that problem?
The unncessary padding provided as the value of `contentContainerStyles` prop in the `OptionsSelector` used in the `YearPickerPage.js` component is causing this.
 
### What changes do you think we should make in order to solve the problem?
To resolve the issue, we can simply remove the `contentContainerStyles` prop from the `OptionsSelector` as an easy fix.

**However, upon further reviewing the `OptionSelector` component, I realized that its simply wrapping the `BaseOptionsSelector` by passing the same set of props and ref. I feel that there is lot more code written there making it little heavy at the moment. The component itself need some love in terms of the refactoring and can be trimmed down along with moving it from using a class based component to functional component along with moving the logic to its own hook (following the separation of concern philosophy).**

### What alternative solutions did you explore? (Optional)
None

**Comment by lschurr** [comment] 2023-06-22 22:30
@sobitneupane can you review these proposals?

**Comment by aliammar1995** [comment] 2023-06-23 08:01
### Proposal 

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent : The focus on timezone is highlighted in full in compared to year option on date of birth

### What is the root cause of that problem?

   It is because in OptionsSelector of TimezoneSelectPage component, we did  
   not put  custom style as  prop (contentContainerStyles)
  
### What changes do you think we should make in order to solve the problem?
We have to add prop contentContainerStyles as a prop OptionsSelector in. TimezoneSelectPage component.

`<OptionsSelector
                            textInputLabel={this.props.translate('timezonePage.timezone')}
                            value={this.state.timezoneInputText}
                            onChangeText={this.filterShownTimezones}
                            onSelectRow={this.saveSelectedTimezone}
                            optionHoveredStyle={styles.hoveredComponentBG}
                            sections={[{data: this.state.timezoneOptions, indexOffset: 0, isDisabled: this.timezone.automatic}]}
                            shouldHaveOptionSeparator
                            safeAreaPaddingBottomStyle={safeAreaPaddingBottomStyle}
                            initiallyFocusedOptionKey={_.get(_.filter(this.state.timezoneOptions, (tz) => tz.text === this.timezone.selected)[0], 'keyForList')}
                            contentContainerStyles={[styles.ph5]}
                        />`

It worked well.

**Comment by sobitneupane** [comment] 2023-06-23 15:28
@chiragxarora's [proposal](https://github.com/Expensify/App/issues/21262#issuecomment-1601610678) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment] 2023-06-23 15:59
No padding in yearpicker

**Comment by NikkiWines** [comment] 2023-06-23 18:41
Yep, agreed we can use @chiragxarora's proposal in this case

**Comment by shawnborton** [comment] 2023-06-23 18:43
I think so - basically all list views are getting refactored. Does that sound right @thiagobrez?

**Comment by shawnborton** [comment] 2023-06-23 19:11
Honestly I think we can just close this one out because the refactor is coming. Let's wait for Thiago to confirm.

**Comment by thiagobrez** [comment] 2023-06-26 08:42
> I think so - basically all list views are getting refactored. Does that sound right @thiagobrez?

@shawnborton That's correct. We currently have a variety of lists being rendered by different components with different styles. In [this tracker issue](https://github.com/Expensify/App/issues/11795) we discussed about it, and we're creating whole new components ([here](https://github.com/Expensify/App/issues/20352), [here](https://github.com/Expensify/App/issues/20353) and [here](https://github.com/Expensify/App/issues/20354)) to make it easier to use from a developer perspective, and maintain consistency from a design perspective

Both the Timezone list and the Year Picker list were already addressed in the first PR. The separator lines were also removed: https://github.com/Expensify/App/pull/21048

I don't think it's worth fixing `OptionsSelector`, `OptionsList` or `OptionRow` components as they're getting completely replaced soon

**Comment by shawnborton** [comment] 2023-06-26 12:09
Awesome thanks for confirming. So sounds like maybe we just close this one out then.

**Comment by NikkiWines** [comment] 2023-06-29 22:24
Agreed, let's close this out for now 👍

**Closed by NikkiWines** 2023-06-29 22:24 UTC
Labels: Reviewing, External, Daily, Bug
