### ISSUE TITLE
Assign Task - Input not highlighted when we go back from confirm task page to new task page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25535] opened 2023-08-19 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start Assign task workflow
2. Give some name
3. Click on Next
4. Click on back arrow in header
5.  Notice the name input is not autofocussed

## Expected Result:
Input for Name should be autofocussed

## Actual Result:
Not auto focussed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/26405083-557d-4310-b632-3ffdd87864d4

https://github.com/Expensify/App/assets/78819774/ee0974e5-0014-44d5-9fca-e9506d4717b8

**Expensify/Expensify Issue URL:**

**Issue reported by:** @BhuvaneshPatil

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691346531750989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-08-21 00:55
Was able to reproduce this, but I don't think it's a bug. It's in line with how other multi-page flows work in NewDot (see my video to show the VBA setup flow as an example).

https://github.com/Expensify/App/assets/59587260/f3f09435-af74-49fa-a188-fd09114b974e

Closing as `not a bug`.

**Closed by kadiealexander** 2023-08-21 00:55 UTC
Labels: Daily, Bug
