### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] Submit Expense - Contacts section is missing participants

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48114] opened 2024-08-27 18:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4890824&group_by=cases:section_id&group_order=asc&group_id=229066
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign up for a new account on staging.new.expensify.com 
2. Create DMs with 7 new contacts 
3. Go to Global Create > Submit Expense 
5. Enter an amount and click `Next`
6. Observe the missing participants from the `Contacts` section. 

## Expected Result:
During the expense submitting or splitting process, the search list, should be divided in "Recents" and "Contacts"

All of your DM contacts should be in the contacts section.

## Actual Result:
Some contacts are missing. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1440" alt="Screenshot 2024-10-16 at 9 33 01 PM" src="https://github.com/user-attachments/assets/ce18997f-7b7c-4eb0-aa0f-e3935f159dc0">

</details> 

https://github.com/user-attachments/assets/b49ba44f-920c-4162-be8e-d708b8e1806f

![ontacts-Recent (1)](https://github.com/user-attachments/assets/d95b5e6d-d68a-468d-a0a8-bc03a33972b0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d2f5d8be09bffb6</li>
        <li>Upwork Job ID: 1829406098502441268</li>
        <li>Last Price Increase: 2024-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 104318599</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment] 2024-08-27 18:58
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by c3024** [comment] 2024-09-01 16:36
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Contacts section is missing in the participant selector though they are not included in Recents.
### What is the root cause of that problem?
We get `defaultOptions` here
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L85
with
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L99
and we pass `maxRecentReportsToShow` as `0`  here
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L123
which means we do not limit the max recent reports for the result from this function.

`getFilteredOptions` calls `getOptions`
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/libs/OptionsListUtils.ts#L2138
which in turn keeps adding the recent reports and continues adding all because `maxRecentReportsToShow` is zero.
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/libs/OptionsListUtils.ts#L1930-L1931
Along with this it also excludes the personal detail of these report logins here
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/libs/OptionsListUtils.ts#L1980-L1982
Since, we are not limiting the recent reports to show so all these reportOption logins are excluded when processing personal details into options here. So, the default options returned from here includes all recent reports but do not include these personal details.

Back here in the `MoneyRequestParticipantsSelector`
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L167
we restrict the reports only to `MAX_RECENT_REPORTS_TO_SHOW` so only those reports show up and many personal details were already excluded earlier in the default options because of addition of all recent reports as explained earlier.

### What changes do you think we should make in order to solve the problem?
We use `defaultOptions` only to get `newOptions` in `MoneyRequestParticipantsSelector` so the restriction of max recent reports can be moved here to `getFilteredOptions`
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L123
and change it to 
```js
CONST.IOU.MAX_RECENT_REPORTS_TO_SHOW
```
With this when the recent reports are added with `getOptions` here
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/libs/OptionsListUtils.ts#L1930-L1932
it only adds `MAX_RECENT_REPORTS_TO_SHOW` reports and logins of only these `MAX_RECENT_REPORTS_TO_SHOW` reports are excluded in the options to exclude when processing personal details here
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/libs/OptionsListUtils.ts#L1980-L1982

So, all the personal details (except those included in the recent reports) are correctly added to `defaultOptions` and hence in the final options shown.

It can be fixed in similar way at other places for whichever function is used in place of `getFilteredOptions`.
### What alternative solutions did you explore? (Optional)
We seem to use the max recent reports to show restriction in the `filterOptions` function in most places. We can consider moving the logic of excluding the personal details for the recent reports added to options to the `filterOptions` function.

**Comment by eh2077** [comment] 2024-09-02 18:40
Reviewing proposals

**Comment by eh2077** [comment] 2024-09-02 20:56
Thanks for your proposals!

I think @c3024 pointed out the correct root cause of this issue. Their solution also looks good to me. So, let's go with @c3024 's [proposal](https://github.com/Expensify/App/issues/48114#issuecomment-2323418693)

🎀👀🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2024-09-02 23:36
Do we know which PR broke this?

**Comment by c3024** [comment] 2024-09-03 07:44
>With @c3024's proposal, some reports are missing (notice the missing workspace reports):

Yes, I missed that.

I think the better solution is the alternative solution proposed. That is to remove this logic 

https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/libs/OptionsListUtils.ts#L1981-L1984

of excluding personal details for included reports from `getOptions` and move that to `filterOptions` with something like this

```js
if (searchInputValue.trim() === '' && maxRecentReportsToShow > 0) {
        // return {...options, recentReports: options.recentReports.slice(0, maxRecentReportsToShow)};
        const recentReports = options.recentReports.slice(0, maxRecentReportsToShow);
        const excludedLogins = new Set(recentReports.map(report => report.login));
        const filteredPersonalDetails = options.personalDetails.filter(personalDetail => !excludedLogins.has(personalDetail.login));
        return {
            ...options,
            recentReports,
            personalDetails: filteredPersonalDetails,
        };
            
    }
``` 
at
https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/libs/OptionsListUtils.ts#L2393-L2395

and

```js
    if (maxRecentReportsToShow > 0 && recentReports.length > maxRecentReportsToShow) {
        recentReports.splice(maxRecentReportsToShow);
    }

    const excludedLogins = new Set(recentReports.map(report => report.login));
    const filteredPersonalDetails = personalDetails.filter(personalDetail => !excludedLogins.has(personalDetail.login));
    personalDetails = filteredPersonalDetails;

```
at
https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/libs/OptionsListUtils.ts#L2467-L2469

This does not require any changes in the individual pages and corrects the common logic.

**Comment by eh2077** [comment] 2024-09-05 15:33
@tsa321 I just tested using a high traffic account and it works well, see
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a3545eb2-1e91-4116-a30f-5eb13e80c343">

Are you still able to reproduce it?

**Comment by eh2077** [comment] 2024-09-09 12:37
@tsa321 Thanks for pointing out that! 

That's interesting, I think it must be a recent PR broke this - Are you able to figure out the PR? So we can understood the root cause better.

**Comment by MonilBhavsar** [comment] 2024-09-11 23:59
Looks like we're still trying to find the root cause here @eh2077 ? And is there anything that I can help with?

**Comment by c3024** [comment] 2024-09-13 03:29
I think the Root Cause is identified.

1. As it exists now, the `getFilteredOptions` for this case has no limit on maxReportsToShow so it includes all reports in its result but does not include all personal details for these DMs. 
2. And in `filteredOptions` we restrict the maxReportsToShow to five and the remaining reports are discarded and since we also did not include the contacts of these discarded DMs, these are not included in Contacts section.
3. While passing the maxReportsToShow limit to the `getFilteredOptions` works when there is no search term, it does not work correctly when there is a search term because `debouncedSearchTerm` is not passed to this function. The search results get returned from this function as if there is no search term.
4. I do not think it makes much sense to pass this `debouncedSearchTem` to `getFilteredOptions` also because we will do the same filtering in both `getFilteredOptions` and `filterOptions`.
5. So, I felt it is better to move the logic of moving the exclusion of personal details to the `filterOptions` function as suggested [here](https://github.com/Expensify/App/issues/48114#issuecomment-2325820879). 

#40235 is the PR that moved the `debouncedSearchTerm` to `filterOptions` with some other changes for performance reasons but missed this case of omitting contacts when there is no search term.

**Comment by eh2077** [comment] 2024-09-15 16:04
@c3024 Thanks for your comment. Let me take sometime to look into it and will update soon.

cc @MonilBhavsar

**Comment by eh2077** [comment] 2024-09-16 15:20
@c3024 I think your RCA is right but I have concerns about your solution here https://github.com/Expensify/App/issues/48114#issuecomment-2325820879 - Will it break the logic to calculate `userToInvite`.

> 4. I do not think it makes much sense to pass this `debouncedSearchTem` to `getFilteredOptions` also because we will do the same filtering in both `getFilteredOptions` and `filterOptions`.

I agreed with you it's not ideal to do the filtering in both methods. But passing `debouncedSearchTem` to `getFilteredOptions` does fix the effect right?

**Comment by eh2077** [comment] 2024-09-16 15:25
@tsa321 I doubted your RCA according to the subsequent discussions above. And your solution only covers the `MoneyRequestParticipantsSelector.tsx` page while the issue occurs in other pages, like new chat search page.

**Comment by c3024** [comment] 2024-09-16 16:10
>But passing debouncedSearchTem to getFilteredOptions does fix the effect right?

Yes. I tried some searching on a high traffic account. I think it is fine to pass the `debouncedSearchTerm` to `getFilteredOptions` since the search for matching reports happen on backend and only the ordering is done on the front-end which does not appear to be intensive.

**Comment by c3024** [comment] 2024-09-16 16:24
>Will it break the logic to calculate userToInvite.

I tried again with the changes [here](https://github.com/Expensify/App/issues/48114#issuecomment-2325820879) also.

It works fine for me for inviting a user.

https://github.com/user-attachments/assets/41b6f9e2-8985-44d3-884f-4b117f9ffcfc

What am I missing?

**Comment by eh2077** [comment] 2024-09-17 13:23
@c3024 I'm not sure what changes exactly you made on your client but according the change you suggested to remove 
https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/libs/OptionsListUtils.ts#L1981-L1984

It's possibly to break the logic to calculate `userToInvite`, like including already invited users etc

Would you like to update your proposal? So that it'll be easier to follow both the RCA and solution, Thanks

**Comment by eh2077** [comment] 2024-09-19 11:48
@c3024 Thanks for the update! 

> So, when we remove that code block duplicates are passed to this canCreateOptimisticPersonalDetailOption function and this will not affect the userToInvite.

But we do pass `optionsToExclude ` to method `getUserToInviteOption` right? So, I think removing 
https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/libs/OptionsListUtils.ts#L1981-L1984
will impact the result returned by the method, see also

https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/libs/OptionsListUtils.ts#L2002-L2019

**Comment by c3024** [comment] 2024-09-19 13:58
@eh2077 

Yes, `getUserToInviteOption` might return a different result with the code removed. But I don't think that `getUserToInviteOption` body is what is preventing from showing an optimistic user invite option for an existing user. The `canCreateOptimisticPersonalDetailOption` is what is blocking from getting to this function altogether. 

Even now without making any changes, the `maxRecentReportsToShow` is what influences what needs to be included in the `optionsToExclude` part of the code block. Say if the `maxRecentReportsToShow` is 5 then only five personal details are included in the `optionsToExclude`. The other personal details are not included in this `optionsToExclude`. Then this function `getUserToInviteOption ` can return an optimistic user to invite for a personal detail not included in the `optionsToExclude`. But the if block of `canCreateOptimisticPersonalDetailOption` is what is preventing it from getting to this `getUserToInviteOption` altogether.

The existing implementation itself can pass different `optionsToExclude` for different `maxRecentReportsToShow` values. Still, the optimistic user to invite option is shown correctly. So, even after the removal the user to invite will be shown correctly even though a different `optionsToExclude` might be passed thanks to the stopping by the `canCreateOptimisticPersonalDetailOption` `if` check. This is evident from testing the code changes also.

**Comment by c3024** [comment] 2024-09-19 14:07
We can pass the `debouncedSearchTerm` to the `getFilteredOptions` if we want a simpler solution instead of moving the code across functions.

**Comment by c3024** [comment] 2024-09-19 16:06
Thanks for digging that out. 

Then I think moving the personal details exclusion logic to `filteredOptions` is the way to go. Any comment on this [explanation](https://github.com/Expensify/App/issues/48114#issuecomment-2361066927)?

**Comment by eh2077** [comment] 2024-09-20 15:25
@c3024 Thanks for your patience!

I think we can go with @c3024 's [proposal](https://github.com/Expensify/App/issues/48114#issuecomment-2325820879). Their comment https://github.com/Expensify/App/issues/48114#issuecomment-2361066927 addresses my concerns about breaking how we calculate `userToInvite`. The change will be made in key search functions, so we'll need to do extensive tests in PR to avoid breaking things.


🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment] 2024-09-24 12:26
We're waiting for @MonilBhavsar to review https://github.com/Expensify/App/issues/48114#issuecomment-2363986911

**Comment by eh2077** [comment] 2024-09-27 15:01
We're waiting for @MonilBhavsar to review https://github.com/Expensify/App/issues/48114#issuecomment-2363986911

**Comment by MonilBhavsar** [comment] 2024-09-27 17:49
Reviewing now... Apologies for delay

**Comment by MonilBhavsar** [comment] 2024-09-28 06:28
Okay the rca and proposal makes sense. Thanks all for digging into it. Great team work 🙌 
This issue seems to be reported from a regression test stating that the functionality already existed. I am bit skeptical about the major refactor, and if we did check any recent PR's that broke this

**Comment by c3024** [comment] 2024-09-30 11:46
1. #40235 caused this regression. In this PR, we changed the `maxRecentReportsToShow` passed to `getFilteredOptions` to 0 in `MoneyRequestParticipantsSelector`. As a result, all recent reports are returned from this function, and all personal details that have reports are excluded. Previously, we passed `undefined`, so the default value of 5 was used for `maxRecentReportsToShow`. This meant only 5 personal details were excluded, and the rest were returned. 

I think this issue was not identified earlier by the QA team, even though it was deployed to production on June 26. This is because, for accounts with contacts that do not have DMs, not all personal details are excluded in `getFilteredOptions`, as these contacts have no reports. Therefore, if QA tested with an account containing such contacts, like a High Traffic Account, the test would not fail with the existing code because the contacts without reports are not excluded and still appear in the Contacts section, satisfying the TestRail expected result.

2. The potential regression from this change is that `getOptions` might return both a report and a contact for the same user. Since we are moving this exclusion code to `filterOptions`, this will not be an issue if we use `filterOptions` consistently wherever `getOptions` is used with reports. `getOptions` with reports is used in `getFilteredOptions`, `getShareDestinationOptions`, `getMemberInviteOptions`, `getSearchOptions`, and `getShareLogOptions`. In all instances where these functions (with reports passed to them) are used in the repo, they are followed by the `filterOptions` function to obtain the final options. Therefore, I have not found anything that could break due to this refactor.

**Comment by MonilBhavsar** [comment] 2024-10-02 05:27
Makes sense! Thanks for clarifying! 🙌 

> This meant only 5 personal details were excluded, and the rest were returned.

So, this was not functioning correctly before too? 

> Since we are moving this exclusion code to filterOptions, this will not be an issue if we use filterOptions consistently wherever getOptions is used with reports. 

Do we plans to ensure it get's used correctly? Or we'll create a similar issue if we use getOptions on a new page, right?

**Comment by c3024** [comment] 2024-10-03 10:32
> So, this was not functioning correctly before either?

No, it was functioning correctly before.

> Do we plan to ensure it gets used correctly, or will we create a similar issue if we use `getOptions` on a new page?

We can add a lint rule for `getOptions` so that either `searchInputValue` or `options` can be passed to it, but not both.

**Comment by eh2077** [comment] 2024-10-07 14:43
Not overdue, the discussion is ongoing

**Comment by kadiealexander** [comment] 2024-10-08 02:56
Not overdue.

**Comment by MonilBhavsar** [comment] 2024-10-08 11:05
Ok thanks for clarifying and all for working through the details! 🙌 
Assigning @c3024

**Comment by trjExpensify** [comment] 2024-10-16 10:02
I'm a bit confused by this issue. Looking at the OP and the title it doesn't seem to be a bug anymore. I've got `Contacts` in the Submit expense participant selector:

![Image](https://github.com/user-attachments/assets/971b7c07-36f9-4ea6-96e6-987bb36d2e88)

**Comment by c3024** [comment] 2024-10-16 10:08
These are the Contacts that are in your contacts but with whom you do not have a DM with. (Like groups etc that you share with other participants)

Our existing logic filters contacts of all DM reports and they are missing in the Contacts section.

This is clearer with a new account with more than 5 DM reports (say 10) and no group chats etc. The Contacts section will be empty though the Recents section shows only 5 reports. The other 5 contacts should appear in the Contacts section but they will not.

**Comment by trjExpensify** [comment] 2024-10-16 12:00
Sorry, you're going to have to rephrase that. The OP of the bug report has this for expected/actual result:

**Expected result**
During the expense submitting or splitting process, the search list, should be divided in "Recents" and "Contacts"

**Actual result**
Search list when submitting or splitting an expense, only displays the "Recents" section and not the "Contacts" one


There is a contacts section on production, so what's the bug and why isn't that reflected in the bug report OP?

**Comment by eh2077** [comment] 2024-10-16 13:39
@trjExpensify Thanks for checking this. Yes, this issue isn't easy to notice in an old or high traffic account. While if you're using a new account with only a few DM contacts, you'll be able notice that some contacts with DM chats are not shown in the contact section. See follow screenshot for example

<img width="1440" alt="Screenshot 2024-10-16 at 9 33 01 PM" src="https://github.com/user-attachments/assets/ce18997f-7b7c-4eb0-aa0f-e3935f159dc0">

**Comment by eh2077** [comment] 2024-10-16 13:48
I also agree the bug report can be improved to make it easier to follow. For example, adding a precondition - login with a new account and send DM chats to 7 different users.

**Comment by trjExpensify** [comment] 2024-10-16 14:01
>See follow screenshot for example

I see, much clearer! 

>I also agree the bug report can be improved to make it easier to follow. For example, adding a precondition - login with a new account and send DM chats to 7 different users.

Yes please, the OP and even the title is confusing. It's not really about the whole contacts section not being there.

**Comment by eh2077** [comment] 2024-10-16 14:28
@trjExpensify Ah, I can't edit the bug report and the title. Can you help update them?

**Comment by trjExpensify** [comment] 2024-10-16 14:50
Done!

**Comment by kadiealexander** [comment] 2024-10-25 06:49
Reassigning for someone to handle payment as I'm OOO for the next two weeks.

**Comment by RachCHopkins** [comment] 2024-10-28 22:05
@c3024 / @eh2077 can you complete the above [checklist](https://github.com/Expensify/App/issues/48114#issuecomment-2428237614), please?

**Comment by RachCHopkins** [comment] 2024-11-04 05:37
@c3024 @eh2077 I would really love to pay you. Can someone please complete the checklist?

**Comment by eh2077** [comment] 2024-11-04 05:43
@RachCHopkins Sorry for the late response! I put it on my list and will complete it by EOD.

**Comment by eh2077** [comment] 2024-11-04 13:51
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40235
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40235/files#r1827762062
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_Yes_**

### Regression test

1. Sign up for a new account on staging.new.expensify.com
2. Create DMs with 7 new contacts
3. Go to Global Create > Submit Expense
4. Enter an amount and click Next
5. Verify that all participants can be found in the Contacts section or the Recents section.

**Comment by RachCHopkins** [comment] 2024-11-08 04:34
Thank you - I will get this sorted out on my Monday!

**Comment by MonilBhavsar** [comment] 2024-11-08 05:12
Thank you!

**Comment by RachCHopkins** [comment] 2024-11-10 22:42
Payment Summary:

- Contributor: @c3024 paid $250 via Upwork
- Contributor+: @eh2077 to be paid $250 via NewDot manual requests

Upwork job [here](https://www.upwork.com/jobs/~016d2f5d8be09bffb6)

**Comment by RachCHopkins** [comment] 2024-11-10 22:43
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by RachCHopkins** 2024-11-10 22:43 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by eh2077** [comment] 2024-11-11 14:01
Requested payment in NewDot

**Comment by JmillsExpensify** [comment] 2024-11-11 14:30
$250 approved for @eh2077
