### ISSUE TITLE
[Ready for payment] Account switcher - No spacing between account switcher icon and the status icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48261] opened 2024-08-29 12:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:**  Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh270803a@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account is a copilot
- Account has a very long name
1. Launch New Expensify app
2. Go to Account settings

## Expected Result:
There will be spacing between account switcher icon and the status icon

## Actual Result:
There is no spacing between account switcher icon and the status icon
On Android, the icons overlap with each other

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1bea100a-2055-4e78-936f-51ec25e8e28e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by puneetlath** [comment] 2024-08-29 14:23
demoting since Copilot is under beta cc @rushatgabhane

**Comment by arosiclair** [comment] 2024-08-29 15:50
Looks like the account switcher was added in https://github.com/Expensify/App/pull/47338. @dangrous can you take a look? @rushatgabhane should probably fix this.

**Comment by rushatgabhane** [comment] 2024-08-29 16:17
hello please assign it to me.

**Comment by dangrous** [comment] 2024-08-29 16:32
Assigned! there are a couple other ones that came through, I'm going to review and then probably assign those as well if that's okay!

**Comment by dangrous** [comment] 2024-08-30 15:02
@rushatgabhane setting flex-shrink here should fix it up, do you think you can add that in to the other fixes? Thanks!

**Comment by rushatgabhane** [comment] 2024-08-30 15:08
yes, one mega fix is needed

**Comment by dangrous** [comment] 2024-09-03 14:41
let us know if it would be best to open this for a contributor @rushatgabhane, I know you've got a lot going on

**Comment by dylanexpensify** [comment] 2024-09-04 14:46
@rushatgabhane we on track to raise today?? 🙏

**Comment by rushatgabhane** [comment] 2024-09-09 16:42
sorry, forgot to update the issues.
PR above - https://github.com/Expensify/App/pull/48517

**Comment by dylanexpensify** [comment] 2024-09-10 20:03
ty!

**Comment by rushatgabhane** [comment] 2024-09-18 06:38
@mkhutornyi i think we saw your slack status as `out sick` so we swapped c+

**Comment by rushatgabhane** [comment] 2024-09-18 06:39
anyway, you reviewed 6/10 bugs and 4/10 were reviewed by @allgandalf 

so i guess you both can split the payment? i know this isn't ideal but what do you think

**Comment by dylanexpensify** [comment] 2024-09-18 10:26
> @mkhutornyi i think we saw your slack status as out sick so we swapped c+

It was for this reason

**Comment by dylanexpensify** [comment] 2024-09-18 10:26
agree with split

**Comment by rushatgabhane** [comment] 2024-09-19 12:33
oops! looks like we caused a regression

**Comment by dangrous** [comment] 2024-09-19 13:33
Ack! based on the proposal though seems like an easy fix

**Comment by dylanexpensify** [comment] 2024-09-25 10:43
Nice, let's get it done!

**Comment by rushatgabhane** [comment] 2024-09-25 10:48
all fixed

**Comment by dangrous** [comment] 2024-09-30 14:46
Do I need to assign @mkhutornyi and @allgandalf to this one to handle C+ payment? cc @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-10-04 09:38
@rushatgabhane @allgandalf @mkhutornyi let's break this down for payment! Who handled which issues (that were priced at $250), and which issues had a regression attached (so $125)?

**Comment by rushatgabhane** [comment] 2024-10-05 04:39
@dylanexpensify they shouldn't be priced at $250 per issue. The issues were one liners and that is why I created a single PR for them

**Comment by dylanexpensify** [comment] 2024-10-07 13:06
Payment summary:

Contributor: @allgandalf $250 via Upwork
Contributor: @mkhutornyi $250 via Upwork
Contributor+: @rushatgabhane $250 via NewDot

Please apply/request!

**Comment by sscodez** [comment] 2024-10-07 13:24
```
 <View style={[styles.flexRow, styles.justifyContentBetween, styles.alignItemsCenter, styles.pb3, styles.gap3]}> 
     <AccountSwitcher style={{flex:3}}  /> 
     <Tooltip  style={{flex:5}} > 
         <PressableWithFeedback {{flex:2}}
              </PressableWithFeedback >
              </View>
```
              
 Follow this way make parent view flex 1

**Comment by rakshwinder** [comment] 2024-10-07 15:34
There are several ways to achieve the desired layout. One approach is to allocate 70% of the width for the user's email. If the email length exceeds the 70% container width, you can make it scrollable. Alternatively, you can break the text if needed to fit within the allocated space. In the remaining 30% of the width, display both icons, ensuring there is a 10% gap between them for proper spacing.

**Comment by dylanexpensify** [comment] 2024-10-18 13:03
@allgandalf @mkhutornyi offers sent!

**Comment by dylanexpensify** [comment] 2024-10-18 18:24
Hey @VictoriaExpensify! I'm heading out on parental leave so reassigning this! All that's left is paying out @mkhutornyi once he's accepted the offer! Job post found [here](https://www.upwork.com/ab/applicants/1843277239220500343/hired)! TY! 🙇‍♂️

**Comment by dangrous** [comment] 2024-10-24 14:41
What's the action here? What do we need still to close this out - has payment completed?

**Comment by VictoriaExpensify** [comment] 2024-11-01 04:24
Sorry, i missed this! Finalising payments now!

**Comment by VictoriaExpensify** [comment] 2024-11-01 04:29
Payment summary:
@allgandalf paid $250 via Upwork (was already paid)
@mkhutornyi paid $250 via Upwork

**Closed by VictoriaExpensify** 2024-11-01 04:29 UTC
Labels: Reviewing, Engineering, Daily, Bug
