### ISSUE TITLE
[HOLD for payment 2023-01-11] [$2000] [Dark mode] Scrollbars should have a dark color

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#12914] opened 2022-11-22 01:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In the comment composer, click the Emoji button
2. Verify that the scroll bar looks "well" in the dark mode

## Expected Result:
Scrollbar should be darker

## Actual Result:
Scrollbar color is toooo light

![image](https://user-images.githubusercontent.com/87341702/203194597-292c60a9-7b6f-486c-98e1-16f371bb144d.png)

## Workaround:
N/A this is just cosmetic

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019481609abc2ae0b8</li>
        <li>Upwork Job ID: 1603152076507746304</li>
        <li>Last Price Increase: 2022-12-21</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2022-11-22 01:33
cc @shawnborton do we have a color for the scrollbars?

**Comment by aldo-expensify** [comment] 2022-11-22 01:35
Do we have a tracking issue for things related to dark mode?

**Comment by shawnborton** [comment] 2022-11-22 01:37
Oh interesting, I would think we would hide the scroll bar in that particular piece of UI. Thoughts?

**Comment by shawnborton** [comment] 2022-11-22 01:39
Otherwise I would make the scroll background the same color as the darkest app BG color, and the tracking button the same color as our default buttons. 

I don't think we have a tracking issue for things related to dark mode... yet? I am not sure if we need one though, we can just handle bugs on a 1:1 basis. Now that I see the scroll bar some more, I can see why it would be useful given how long the emoji list is.

**Comment by aldo-expensify** [comment] 2022-11-22 01:45
> Oh interesting, I would think we would hide the scroll bar in that particular piece of UI. Thoughts?

Maybe, but you still have the scrollbar in other views

![image](https://user-images.githubusercontent.com/87341702/203196677-f93232f2-2e44-43f1-b886-72dff8e3dc8b.png)

**Comment by shawnborton** [comment] 2022-11-22 01:47
Good point. Okay, so let's try with my color suggestions above?

**Comment by aldo-expensify** [comment] 2022-11-22 01:50
> Good point. Okay, so let's try with my color suggestions above?

sounds good to me!

**Comment by grgia** [comment] 2022-11-22 02:05
I could bundle these dark mode color fixes into one PR for faster QA, mind if I take this one too?

**Comment by aldo-expensify** [comment] 2022-11-22 02:18
> I could bundle these dark mode color fixes into one PR for faster QA, mind if I take this one too?

Feel free to take them if there is no engineer assigned ;)

**Comment by grgia** [comment] 2022-11-28 23:29
Haven't gotten to this one yet

**Comment by grgia** [comment] 2022-12-02 18:21
Looking into this, will update with what I find

**Comment by grgia** [comment] 2022-12-02 19:48
https://dev.to/shayanypn/anything-about-customizing-native-scrollbar-59hm dropping this here to reference later

**Comment by grgia** [comment] 2022-12-02 20:56
@marcaaron I saw you updated some WebKit styles, do you have insight on modifying the scrollbar colors

**Comment by marcaaron** [comment] 2022-12-02 21:06
Scrollbars... I would check this for information about web -> 

https://css-tricks.com/the-current-state-of-styling-scrollbars-in-css/

I am not really sure about react native... 

I found this -> https://reactnative.dev/docs/scrollview#indicatorstyle-ios

But it's iOS only.

There's also a package someone created to customize the indicators [here](https://github.com/mishabelokon/react-native-scroll-indicator#readme). Which could be a sign that this is not an easy thing to do. But I'd be surprised if we are the first people to ever try to implement a "dark mode" in a React Native app 😅

**Comment by grgia** [comment] 2022-12-06 17:09
Thanks for the direction, Marc! 
For later reference, this is the GitHub dark mode scrollbar hover:
<img width="267" alt="Screenshot 2022-12-06 at 9 06 51 AM" src="https://user-images.githubusercontent.com/38015950/205976533-dfb5b523-719b-48be-b880-46cbbc89841b.png">

**Comment by grgia** [comment] 2022-12-12 16:52
Working on a few other issues, if I can't get to this in the next day or so, I'll make external

**Comment by grgia** [comment] 2022-12-14 22:14
Gonna make this external

**Comment by grgia** [comment] 2022-12-14 22:16
Not sure what happened with the overdue label

**Comment by getusha** [comment] 2022-12-15 06:11
it is not possible to change the color of a scrollbar in a FlatList in React Native on Android.
for the IOS i see dark scroll bar, 

https://user-images.githubusercontent.com/75031127/207785742-d66ce5c8-e452-4b61-9486-e2e73c368dfd.mov

so we can implement this only for the web / desktop?
What's your thoughts on this @marcaaron

**Comment by bernhardoj** [comment] 2022-12-15 06:57
**Proposal**

We can add scrollbar styling to the `html` in `web/index.html` inside `<style>` tag.
```diff
html,
body,
#root,
#root > div,
#root > div > div {
+   scrollbar-color: #061B09 #184E3D;
    height: 100% !important;
}
+::-webkit-scrollbar {
+    background-color: #061B09;
+}
+::-webkit-scrollbar-thumb {
+    background: #184E3D;
+}
```

`scrollbar-color` only works on Firefox, so we need to also add `-webkit-scrollbar-*` for Chromium and WebKit browser.

**Result**

https://user-images.githubusercontent.com/50919443/207793452-8e6d41e0-0803-4e27-bd00-5148098be0bb.mov

**Comment by getusha** [comment] 2022-12-15 07:01
@bernhardoj how do you handle the switch to the light theme?

**Comment by dhanashree-sawant** [comment] 2022-12-15 07:06
@getusha Working on the CSS fix, can you let me know how do I change it to light theme on web?

**Comment by dhanashree-sawant** [comment] 2022-12-15 07:11
**Proposal**

Include the following CSS inside style of web/index.html. It works for chrome and safari:

`*::-webkit-scrollbar {		     	width: 10px;
}

*::-webkit-scrollbar-thumb {
    	background-color: rgba(255,255,255,0.5);
    	border-radius: 10px;
	border: 1px solid rgba(255,255,255,0.6);
}

*::-webkit-scrollbar-track {
	background-color: rgba(255,255,255,0.05);
	border: 1px solid grey;
	border-radius: 10px;
}`
![Screenshot 2022-12-15 at 12 38 38 PM](https://user-images.githubusercontent.com/87513216/207795769-b1b14d38-32a6-42ef-b97a-ef4a1b570c85.png)

Will modify the proposal once I get to know how to switch between light and dark mode

**Comment by getusha** [comment] 2022-12-15 07:19
Proposal

```diff

diff --git a/src/styles/styles.js b/src/styles/styles.js
index baac1d8f33..8c5b7b0aef 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -19,6 +19,7 @@ import pointerEventsNone from './pointerEventsNone';
 import pointerEventsAuto from './pointerEventsAuto';
 import overflowXHidden from './overflowXHidden';
 import CONST from '../CONST'; 
 
+    scrollbarDark: {
+        scrollIndicatorInsets: {
+          top: -10,
+          right: -10,
+          bottom: -10,
+          left: -10,
+        },
+        backgroundColor: '#333',
+      }
``` 

```diff

diff --git a/src/components/EmojiPicker/EmojiPickerMenu/index.js b/src/components/EmojiPicker/EmojiPickerMenu/index.js
index 2d97a24439..268746dc50 100755
--- a/src/components/EmojiPicker/EmojiPickerMenu/index.js
+++ b/src/components/EmojiPicker/EmojiPickerMenu/index.js
@@ -1,5 +1,5 @@
 import React, {Component} from 'react';
-import {View, FlatList} from 'react-native';
+import {View, FlatList, StyleSheet} from 'react-native';
 import {withOnyx} from 'react-native-onyx';
 import PropTypes from 'prop-types';
 import _ from 'underscore';
@@ -502,6 +502,7 @@ class EmojiPickerMenu extends Component {
                             style={[
                                 styles.emojiPickerList,
                                 this.isMobileLandscape() && styles.emojiPickerListLandscape,
+                                styles.scrollbarDark
                             ]}
                             extraData={
                               [this.state.filteredEmojis, this.state.highlightedIndex, this.props.preferredSkinTone]
```

**Result** :tada:

https://user-images.githubusercontent.com/75031127/207797277-d2d5f6ea-5a71-4d07-a5d4-7fcc183f8365.mov

**Comment by priyeshshah11** [comment] 2022-12-17 10:01
## Proposal 

OG proposal here https://github.com/Expensify/App/issues/13592#issuecomment-1354451969

On iOS it is already dark, so this only needs to be fixed on web. The solution below works for all browsers including Safari, Chrome & Firefox. I have put in light green colour below as per #13592 but we can substitute it with any colour the design team wants.

In `src/web/index.html`
```diff
diff --git a/web/index.html b/web/index.html
index d7074a03d..1f1083030 100644
--- a/web/index.html
+++ b/web/index.html
@@ -63,6 +63,22 @@
             -webkit-text-fill-color: #ffffff;
             caret-color: #ffffff;
         }
+        /* Customize scrollbar color & width for firefox */
+        body {
+            scrollbar-width: thin;
+            scrollbar-color: #03d47c transparent;
+        }
+        /* Customize scrollbar color & width for most browsers except firefox */
+        ::-webkit-scrollbar {
+            width: 4px;
+        }
+        ::-webkit-scrollbar-track {
+            background-color: transparent;
+        }
+        ::-webkit-scrollbar-thumb {
+            background-color: #03d47c;
+            border-radius: 4px;
+        }
     </style>
     <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1">
     <link rel="shortcut icon" id="favicon" href="/favicon.png">
```

@grgia @aimane-chnaif

**Comment by getusha** [comment] 2022-12-17 10:19
In the future we need to switch between themes and we don't want to have same scroll bar colors for themes right? how are we going to change the style dynamically if we're applying this on index.html?

**Comment by priyeshshah11** [comment] 2022-12-17 10:28
> In the future we need to switch between themes and we don't want to have same scroll bar colors for themes right? how are we going to change the style dynamically if we're applying this on index.html?

@getusha I didn't know that was a requirement, could you please point me to where that requirement is listed?

**Comment by getusha** [comment] 2022-12-17 10:32
@priyeshshah11
I am just asking. IMO even if it is not listed it's obvious to think about that, don't you think?

**Comment by priyeshshah11** [comment] 2022-12-17 10:48
> @priyeshshah11 I am just asking. IMO even if it is not listed it's obvious to think about that, don't you think?

No I don't think it's obvious, and I don't think that's in the scope of this issue as it applies to a lot of things in the app which are currently not catered for changing themes, but it's good that you're thinking ahead. To answer your initial question, the styles can be overwritten from anywhere within the app but the exact solution would depend on how theme switching is implemented.

**Comment by getusha** [comment] 2022-12-17 10:56
Does that work on desktop?

**Comment by priyeshshah11** [comment] 2022-12-17 11:23
> @priyeshshah11 Does that work on the desktop app?

yes, works on desktop too.


<img width="1202" alt="Screen Shot 2022-12-17 at 10 22 05 PM" src="https://user-images.githubusercontent.com/38547776/208239283-6083d6ce-08ff-4c62-ab05-31bfc469ea1a.png">

**Comment by s77rt** [comment] 2022-12-17 19:19
Should we hold this until theme-switching is implemented?

**Comment by shawnborton** [comment] 2022-12-19 13:25
I agree that we don't need to worry about theme switching for the moment.

**Comment by sakluger** [comment] 2022-12-20 21:47
@grgia @aimane-chnaif it looks like we've gotten a few proposals, do you think we should accept any of these proposals?

**Comment by bernhardoj** [comment] 2022-12-22 03:41
### **Updated Proposal [1]**
So, I find another way to change the scrollbar color (for web) similar to GitHub. We can apply `color-scheme: dark` to the `root`.

![image](https://user-images.githubusercontent.com/50919443/209049677-ab93faf7-2c45-4195-ba45-e788692f2d1b.png)

**Comment by priyeshshah11** [comment] 2022-12-22 06:42
> Option 3: ([#12914 (comment)](https://github.com/Expensify/App/issues/12914#issuecomment-1356150080)) ![test3](https://user-images.githubusercontent.com/96077027/209006950-711d6553-d8a6-4692-a777-054925fe51b2.png)
>
> I'd like to hear @shawnborton's suggestions.

@aimane-chnaif Just wanted to highlight here that my original proposal was for #13592 which was to have a light green coloured scrollbar but I guess the exact colour, width & border-radius can be changed once the design team confirms what they actually want but the idea would still be the same.

@grgia @shawnborton

**Comment by shawnborton** [comment] 2022-12-22 17:11
Yup, I think ideally we use something like [Option 1 from here](https://github.com/Expensify/App/issues/12914#issuecomment-1362152024) in regards to scroll thumb color and track width, but hopefully we can round the scroll thumb.

**Comment by shawnborton** [comment] 2022-12-22 17:22
I commented this above, but something that is similar in width to Option 1 but uses a perfectly round scroll thumb.

**Comment by priyeshshah11** [comment] 2022-12-23 09:37
@aimane-chnaif @shawnborton which looks like this. The default width is 16px

<img width="144" alt="Screen Shot 2022-12-23 at 8 25 32 PM" src="https://user-images.githubusercontent.com/38547776/209310512-5b426385-1cf9-4a68-ac15-7bb62e304aa6.png">

**Comment by shawnborton** [comment] 2022-12-23 15:38
Nice, I think that looks good.

One point of clarification separate from styling - this would only be for when scrollbars are visible, right? Like right now on my MacBook, I really don't see scroll bars in NewDot, I just want to make sure this wouldn't force scroll bars on everyone?

**Comment by priyeshshah11** [comment] 2022-12-23 15:41
> Nice, I think that looks good.
> 
> One point of clarification separate from styling - this would only be for when scrollbars are visible, right? Like right now on my MacBook, I really don't see scroll bars in NewDot, I just want to make sure this wouldn't force scroll bars on everyone?

Do you mean on desktop or web?

**Comment by shawnborton** [comment] 2022-12-23 15:42
Both. Ideally we just stylize scrollbars when they are visible, but I don't think we need to change the behavior of if/when we show them.

**Comment by priyeshshah11** [comment] 2022-12-23 15:44
I can currently see the scrollbars on both desktop & web only when scrolling. So I assume we want to keep the same behaviour.

**Comment by getusha** [comment] 2022-12-23 15:50
`color-scheme: dark;`
works perfectly keeping the behavior and it looks good.

**Comment by priyeshshah11** [comment] 2022-12-23 16:27
> > I can currently see the scrollbars on both desktop & web only when scrolling. So I assume we want to keep the same behaviour.
> 
> can you share videos of both before-fix and after-fix on Windows chrome?

Sorry I do not have windows. There's a setting on Mac where you can hide the scrollbar when not scrolling. However, that gets ignored with my solution above i.e. it always shows the scrollbar thumb which I guess makes it consistent with other platforms.

As @getusha pointed out `color-scheme: dark;` keeps the current behaviour but does not allow the scrollbar thumb colour to be customised.

**Comment by shawnborton** [comment] 2022-12-23 18:15
> As @getusha pointed out color-scheme: dark; keeps the current behaviour but does not allow the scrollbar thumb colour to be customised.

I think I would prefer this after thinking on it some more. Rather than trying to do anything overly customized, I would prefer we just respect native platform shapes/colors, but in the very least let's try to make them darker.

**Comment by getusha** [comment] 2022-12-23 18:23
It will look like this.
It inherits the theme color from the parent background.
isn't that great?
<img width="472" alt="Screenshot 2022-12-23 at 10 23 09 AM" src="https://user-images.githubusercontent.com/75031127/209391289-3a286d11-77f0-4f90-900a-b32d914d0c41.png">

**Comment by shawnborton** [comment] 2022-12-23 18:57
I like it!

**Comment by grgia** [comment] 2022-12-23 20:19
I think we have some great proposals here, do you have a suggestion for which we should move forward with @aimane-chnaif before I assign?

**Comment by JmillsExpensify** [comment] 2022-12-23 21:44
As we still work through proposals I wanted to flag that this issue recently hit the 30 day mark. As a result, if we can't find a comprehensive proposal that we're comfortable approving, then I think we need to take this issue `internal`.

**Comment by bernhardoj** [comment] 2022-12-24 02:29
### **Updated Proposal [2]**
Following my previous [proposal](https://github.com/Expensify/App/issues/12914#issuecomment-1362372536), because we are okay with the `color-scheme: dark`, I'm adding the iOS solution to apply the `indicatorStyle` globally.

**_AppDelegate.mm_**
We need to add below code inside `didFinishLaunchingWithOptions` function on any line.
```
[[UIScrollView appearance] setIndicatorStyle: UIScrollViewIndicatorStyleWhite];
```

**Result**

**Comment by grgia** [comment] 2022-12-26 21:14
I agree, I think we can accept @0xmiroslav's proposal. Shawn is out today, so we can either wait for 🟢 on design when he's back or assign now to move this forward. 

cc @JmillsExpensify do you think it's best to move this along or wait?

**Comment by sakluger** [comment] 2022-12-26 21:23
@grgia I'd prefer to get Shawn's opinion on that proposal before moving forward. If he doesn't comment by tomorrow, I can add a hold to the issue so that the price isn't doubled again (which I believe would happen on Wednesday if no action is taken).

**Comment by JmillsExpensify** [comment] 2022-12-26 21:41
Shawn mentioned to me that he'd be working some this week, so I went ahead and let him know via DM. @0xmiroslav's proposal is pretty thorough though, I think it's good.

**Comment by bernhardoj** [comment] 2022-12-27 02:02
Just want to add some info here, the iOS solution of @0xmiroslav proposal works for iOS >= 13 and our minimum iOS version is 11. I think we can combine with my iOS solution to make the scrollbar darker through all version.

What do you think? @aimane-chnaif

**Comment by bernhardoj** [comment] 2022-12-27 02:32
Okay. Got it. 👍

**Comment by sakluger** [comment] 2022-12-27 19:14
Adding Added `[HOLD]` to the title to prevent the price from doubling again while we wait for Shawn's feedback.

**Comment by shawnborton** [comment] 2022-12-27 22:37
Hey everyone, thanks for being patient. I still think we should try to utilize native scroll bars here if possible so that this way we don't change the behavior of if/when we actually show them. That being said, let's just use the system's native dark theme for these if possible. So sounds like we go with something like @0xmiroslav's proposal?

**Comment by sakluger** [comment] 2022-12-27 23:50
Thanks Shawn! Sounds like we're good to accept @0xmiroslav's proposal.

**Comment by JmillsExpensify** [comment] 2022-12-28 17:58
@aimane-chnaif @grgia would you like to see an updated version of @0xmiroslav proposal before we move to the PR phase? If not, let's get them assigned building on @sakluger's last comment.

**Comment by JmillsExpensify** [comment] 2022-12-28 18:08
Yes

**Comment by grgia** [comment] 2022-12-28 18:14
I think that we are good to move forward. I'll assign @0xmiroslav

**Comment by syedsaroshfarrukhdot** [comment] 2023-01-03 09:43
This PR solving this issue is causing a [`Deploy Blocker`](https://github.com/Expensify/App/issues/13951) https://github.com/Expensify/App/issues/13951 Currently as the issue is locked so commenting here and tagging the issue. Already proposed solution on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1672724600298329?thread_ts=1672703161.629009&cid=C01GTK53T8Q). 

To fix it we need to set color  to colorBackgroundFloating to fix the issue in styles.xml because applying background color dark to android app also causes Modals to be Dark.

As it is a [`Deploy Blocker`](https://github.com/Expensify/App/issues/13951) I know the urgency to fix the issue so I will be available to raise a PR in next few minutes if assigned to the job.

``` git diff

diff --git a/android/app/src/main/res/values/styles.xml b/android/app/src/main/res/values/styles.xml
index a804c14ab..b30501c5b 100644
--- a/android/app/src/main/res/values/styles.xml
+++ b/android/app/src/main/res/values/styles.xml
@@ -10,6 +10,7 @@
         <item name="android:statusBarColor">#061B09</item>
         <item name="colorAccent">@color/accent</item>
         <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
+        <item name="colorBackgroundFloating">@color/white</item>
     </style>
 
     <!-- Themes unique to the boot splash page -->

``` 
    
After Fix :-

https://user-images.githubusercontent.com/81307212/210307867-943023cb-54eb-4854-a483-69785fe08d55.mp4

**Comment by sakluger** [comment] 2023-01-05 17:36
The issue was deployed to production, but it seems like some of the automation isn't triggering, so I updated the title manually.

For payment:

- [ ] **Issue reporter:** There is no external issue reporter
- [ ] **Contributor:** @0xmiroslav I've sent an offer through Upwork
- [ ] **C+ reviewer:** @aimane-chnaif I've sent an offer through Upwork

It looks like the linked PR was merged within 3 days, so I believe that this is eligible for a 50% bonus.

It also looks like there may have been a regression from the PR, but I can't tell if that was actually a regression or a false positive. @grgia @aimane-chnaif could you please confirm if there was a regression or not that would affect payment?

**Comment by sakluger** [comment] 2023-01-11 20:00
Hey everyone, I discussed with my team regarding the payments, and I have an update. For this issue, we still consider the regression to be an actual regression - the PR doesn't necessarily need to be reverted to be deemed a regression. For that reason, we will be applying the 50% penalty for the regression.

Additionally, we do not pay the "efficiency" bonus for a fast merge when there is a regression.

Given the above info, here are the payments that I will be sending out today:

- Contributor: @0xmiroslav - $2000 payment
- C+ reviewer: @aimane-chnaif  - $1000 payment

**Closed** 2023-01-11 20:10 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2023-01-17 01:47
Late to this but...  for the timeliness bonus, @0xmiroslav was hired on hired on 12/28 and the PR was merged on 12/30.   [CONTRIBUTING.md just got updated ](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=If%20the%20PR%20causes%20a%20regression%20within%207%20days%20of%20being%20deployed%20to%20production%2C%20contributors%20are%20not%20eligible%20for%20the%2050%25%20bonus.)today to state
> If the PR causes a regression within 7 days of being deployed to production, contributors are not eligible for the 50% bonus.

Before then we didn't make clearly state that a regression (reverted or not) would affect the timeliness bonus. With CONTRIBUTING.md being the source of truth, we need to always be able to point to it (which we can now).  I've issued @0xmiroslav and @aimane-chnaif each $1000 bonus for timeliness.  

For "If a regression is found but not reverted, does it still affect compensation?" the answer is yes for C+, per our internal process doc for C+, the regression is the trigger, regardless if it's reverted or not. 
> the PR has been deployed to production with no regressions. If regressions are found that “should have”* been caught after the PR has been approved
