### ISSUE TITLE
Sign up - Infinite skeleton loader when navigating from abracadabra tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40038] opened 2024-04-10 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2616817
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Enter new gmail account
3. Copy the Magic link from email and change it to staging link
4. Open link in a new tab
5. Navigate to the original tab

## Expected Result:
User is logged in with the new account.
The engagement modal "Welcome to Expensify" is displayed

## Actual Result:
User is logged in with the new account.
Infinity skeleton loader in a chat history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/968218f9-99af-410b-952b-752b8dd4c218

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-10 20:38
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-04-11 03:52
Dupe of https://github.com/Expensify/App/issues/37351?

**Comment by sonialiap** [comment] 2024-04-12 15:16
Agreed, that looks like a dupe

**Closed by sonialiap** 2024-04-12 15:16 UTC
Labels: Daily, Bug
