### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Command + left/right arrow to go back/forward stopped working on desktop

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35628] opened 2024-02-02 04:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-5
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706724719541289

## Action Performed:
1. Open RHP in desktop app
2. Use `cmd` + left/right arrow
## Expected Result:
Able to navigate between screens 
## Actual Result:
nothing happens
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1a29edd5-e66b-4a49-b1a6-91320d31ef93

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017be8ae464b81915b</li>
        <li>Upwork Job ID: 1753269207737479168</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28143786</li>
<li>bernhardoj | Contributor | 28143787</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-02-02 04:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cmd+arrow key doesn't work to go forward/back on the desktop.

### What is the root cause of that problem?
The shortcut to go back/forward is cmd+] and cmd+[ and it's been like that for a long time.

https://github.com/Expensify/App/blob/d9fd412e85be642e7b4115cd8c15ceda8424740e/desktop/main.js#L406-L416

### What changes do you think we should make in order to solve the problem?

If we want to update it with the arrow key, then we can just replace [] with Left/Right.
```
Cmd+Left / Shift+Left
Cmd+Right / Shift+Right
```

**Comment by rafecolton** [comment] 2024-02-02 17:44
I don't think we should replace `[]`, they should both work. Also I don't know where shift + left/right is coming from - is that a windows thing? That doesn't work for me in browsers or in slack, so afaik that is not a standard key combination for going back/forward.

**Comment by akinwale** [comment] 2024-02-02 18:29
Looking at the [official Apple Safari shortcuts](https://support.apple.com/en-gb/guide/safari/cpsh003/mac) (assuming this is the intended behaviour we want to emulate here), `Cmd+]` and `Cmd+[` are the keyboard shortcuts to navigate forward and back respectively, so I think we can close this one.

**Comment by rafecolton** [comment] 2024-02-02 18:44
@akinwale I don't agree that we should close this. Using cmd + arrow keys is pretty universal back/forward behavior across many apps, including Slack and Google Chrome. It also works in Safari.

**Comment by akinwale** [comment] 2024-02-02 19:06
@rafecolton In that case, I suppose it makes sense to implement support for new shortcuts instead of replacing the existing ones.

@bernhardoj Could you update your proposal to take this approach?

**Comment by bernhardoj** [comment] 2024-02-03 02:05
> Also I don't know where shift + left/right is coming from - is that a windows thing? 

It's for the left and right arrow

> Could you update your proposal to take this approach?

> if we want to support both, we need to use a [workaround](https://www.github.com/electron/electron/issues/5256#issuecomment-692068367) because electron doesn't support multiple shortcuts

There is already a linked workaround to allow both shortcuts in my proposal

**Comment by rafecolton** [comment] 2024-02-03 20:31
> It's for the left and right arrow

I meant the shift part specifically. But then I saw the ternary checking for darwin, so that clarifies that shift + &lt;whatever&gt; is for non-macos systems

**Comment by bernhardoj** [comment] 2024-02-04 06:34
Ah sorry, yes, the shift is for non-macos.

**Comment by isabelastisser** [comment] 2024-02-05 14:34
Hey @rafecolton @akinwale, can we accept @bernhardoj proposal? Does it fix the issue? Thanks!

**Comment by akinwale** [comment] 2024-02-05 14:56
@isabelastisser Yes, we can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/35628#issuecomment-1922798375).

🎀👀🎀 C+ reviewed.

**Comment by cead22** [comment] 2024-02-05 20:41
@isabelastisser I think we should confirm in #expensify-open-source or #product that we want to do this, as this isn't a bug but a new feature from what I understand

**Comment by isabelastisser** [comment] 2024-02-05 21:02
Thanks for the heads up, Carlos! Asking [here](https://expensify.slack.com/archives/C03U7DCU4/p1707166897615539).

**Comment by isabelastisser** [comment] 2024-02-06 01:34
@bernhardoj, we can move forward with the proposal. Thanks!

**Comment by bernhardoj** [comment] 2024-02-06 06:11
PR is ready

cc: @akinwale

**Comment by isabelastisser** [comment] 2024-02-21 17:20
Hey @akinwale, please complete the checklist above so we can close the issue. Thanks!

**Comment by isabelastisser** [comment] 2024-02-21 17:21
Payment summary:

@akinwale [automatic offer](https://www.upwork.com/nx/wm/offer/28143786) (Reviewer) $500
@bernhardoj [automatic offer](https://www.upwork.com/nx/wm/offer/28143787) (Contributor) $500

**Comment by akinwale** [comment] 2024-02-21 17:37
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This functionality was not implemented for desktop.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the desktop app.
2. Open any number of chat reports.
3. Press Cmd+Left arrow key on the keyboard (make sure no text input is focused and no modal is open before pressing the keys).
4. Verify that the app navigates back.
5. Press Cmd+Right arrow key on the keyboard (make sure no text input is focused and no modal is open before pressing the keys).
6. Verify that the app navigates forward.

Do we agree 👍 or 👎?

**Comment by isabelastisser** [comment] 2024-02-22 16:00
All set!

https://github.com/Expensify/Expensify/issues/371836

**Closed by isabelastisser** 2024-02-22 16:00 UTC
Labels: External, Daily, Awaiting Payment, Bug
