### ISSUE TITLE
Start chat - App crashes when pressing keyboard up key in Start chat list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40401] opened 2024-04-18 08:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Press keyboard down key.
4. Press keyboard up key.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/81ca0f1b-211e-4599-b5f1-97bcc77ec594

[Bug6453279_1713425262915!crash.txt](https://github.com/Expensify/App/files/15022036/Bug6453279_1713425262915.crash.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-18 08:29
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 08:29
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-18 08:30
Production 


https://github.com/Expensify/App/assets/115492554/7f59b358-b49a-499b-98c3-7a05e11ff76e

**Comment by danieldoglas** [comment] 2024-04-18 12:12
@ShridharGoel thanks for pointing out where the issue came from. Your proposal was great, but in cases like this (where the issue was caused by a PR that was recently deployed < 7 days ago), it is expected that the contributor who originally did the changes fixes the regressions as part of the original issue. I suggest you look for issues that have `Help Wanted` labels, where you would be assigned to a situation like this.

@WojtekBoman  this is a regression from your PR that was merged deployed 7h ago. Please look into it as well!

cc @roryabraham

**Comment by WojtekBoman** [comment] 2024-04-18 13:45
[The PR](https://github.com/Expensify/App/pull/40439) with the fix for this issue is ready for review

**Comment by roryabraham** [comment] 2024-04-19 00:14
fix is being CP'd [here](https://github.com/Expensify/App/actions/runs/8746337139)

**Comment by roryabraham** [comment] 2024-04-19 00:20
confirmed this is fixed on staging, no payments due, closing this out

**Closed by roryabraham** 2024-04-19 00:20 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
