### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Web - Close message error button can be clicked but nothing happens

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23066] opened 2023-07-18 10:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Go announce room
3. Chat any message
4. Delete above workspace
5. Hover on above message in the announce room
6. Click reply in thread
7. Hover on message in thread, click delete icon, Observe that an error message appears
8. Click the close button at the error message

## Expected Result:
After click close the error message disappear

## Actual Result:
After click close the error message not disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7e460fad-9a8d-4056-ab58-8dc21d759c38

https://github.com/Expensify/App/assets/93399543/15887bbe-5dbe-407c-ab85-558a08bd8c40

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689506265018749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d5aa7db1e165a4f</li>
        <li>Upwork Job ID: 1683597910586687488</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26488191</li>
<li>namhihi237 | Contributor | 26488192</li>
<li>namhihi237 | Reporter | 26488195</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-18 10:19
## Proposal
by @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
After clicking close the error message disappears
### What is the root cause of that problem?
Khi click the close button to it will call the function `clearReportActionErrors` at [here](https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/pages/home/report/ReportActionItem.js#L491C1-L492C123)
This is function [clearReportActionErrors](https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/libs/actions/ReportActions.js#L10C1-L10C59) We have a reportID params to remove error.
But in case we delete or edit the parent message of the thread, the value passed here is not the reportID of the parent message. That's why when I click it, nothing happens.
### What changes do you think we should make in order to solve the problem?
We can update onClose [here](https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/pages/home/report/ReportActionItem.js#L492C33-L492C33) like this, to get correct reportID
```javascript
onClose = {
    () => {
        if (ReportUtils.isThreadParent(props.action)) {
            const childReport = ReportUtils.getReport(props.action.childReportID);
            ReportActions.clearReportActionErrors(childReport.parentReportID, props.action)
            return;
        }
        ReportActions.clearReportActionErrors(props.report.reportID, props.action)
    }
```
### What alternative solutions did you explore? (Optional)
We can hide the delete and edit button for a parent when a message on the thread if room was archived

**Comment by HLEDYA** [comment] 2023-07-18 13:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For archived rooms, comments can be replied in a new thread and when the new thread is opened comment cannot be deleted or closed.

### What is the root cause of that problem?
The root cause of the problem is showing not applicable menu context icons when the room is archived.

### What changes do you think we should make in order to solve the problem?
I suppose, only copy context menu action can be shown for the archived rooms. In order to that `ContextMenuAction` list can be updated accordingly.

https://github.com/Expensify/App/blob/11e9f85175f97f5e9de2d5df50e31e469c86d676/src/pages/home/report/ContextMenu/ContextMenuActions.js#L46

The line above can be changed as the following:

```JS
        shouldShow: (type, reportAction, isArchivedRoom) =>
            type === CONTEXT_MENU_TYPES.REPORT_ACTION && _.has(reportAction, 'message') && !ReportActionUtils.isMessageDeleted(reportAction) && !isArchivedRoom,
```
Related changes can be seen [here](https://github.com/Expensify/App/compare/main...HLEDYA:Expensify-App:fix-web-close-message-error-23066)

Result is (when hovered over the comment):

<img width="1421" alt="Screenshot 2023-07-18 at 16 36 53" src="https://github.com/Expensify/App/assets/77512248/fc80dc39-4f9c-490f-bddc-11dc07984580">


### What alternative solutions did you explore? (Optional)
`ContextMenuAction` can be hidden totally when the room is archived. But keeping at least `copy` action seems more reasonable.

**Comment by alexpensify** [comment] 2023-07-20 21:19
I need an extra day to continue testing this one.

**Comment by alexpensify** [comment] 2023-07-22 15:40
I ran out of time yesterday, I'll review soon.

**Comment by alexpensify** [comment] 2023-07-24 22:00
At this point, I don't think it's a dupe which I originally thought last week. I've assigned the `external`. @abdulrahuman5196 when you get a chance, can you please review the proposals? Thank you!

**Comment by alexpensify** [comment] 2023-07-26 21:51
@abdulrahuman5196 - checking in to see if you were able to review the proposals. Thanks!

**Comment by alexpensify** [comment] 2023-07-28 20:55
No update yet

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:55
Reviewing today

**Comment by alexpensify** [comment] 2023-08-05 00:24
@abdulrahuman5196 - checking to see if you have any feedback for this comment [here](https://github.com/Expensify/App/issues/23066#issuecomment-1660128626)? Thanks!

**Comment by alexpensify** [comment] 2023-08-06 17:01
Update: Waiting for a comment update.

**Comment by alexpensify** [comment] 2023-08-08 23:16
@abdulrahuman5196 - any update to the @namhihi237 comment? Thanks!

**Comment by alexpensify** [comment] 2023-08-10 17:00
Since there is no recent movement, I'll test again and confirm if we should close

**Comment by alexpensify** [comment] 2023-08-12 16:10
As it stands, you can chat in a closed chat room. I still get the experience that I can't click the Close button. With that said, I need to go back to the team to identify if this is on purpose.

![2023-08-12_09-08-48](https://github.com/Expensify/App/assets/8107070/7236a92f-62f1-4e5b-8e6c-13033f009af2)

**Comment by abdulrahuman5196** [comment] 2023-08-13 13:38
@alexpensify I was able to repro the issue. 
There are couple of question on the expected behaviour itself.

1) for The parent message we don't even show the `Delete` icon in the archived chat, but when we create a thread of it we show the `Delete` icon and it ultimately fails. 

2) You are unable to close the error message on the thread, but if you go the archived chat you can close the error.


https://github.com/Expensify/App/assets/46707890/eed55e03-ee8f-4a4d-8685-5c585f0985b0

What is the expected behaviour here? Should we hide the delete icon? Or should we show it and handle the error and handle the close properly as well?

**Comment by alexpensify** [comment] 2023-08-16 23:51
Tomorrow, I'm going to bump the thread with these questions

**Comment by kosmydel** [comment] 2023-08-17 13:07
Hey :wave:
I'm from Software Mansion, an expert agency, and I will help close this issue out, let me go through the existing proposals. I have also started a Slack thread here(link), where I have tagged the contributor+ and BugZero and we can discuss any progress regarding this issue there in a faster manner. Thanks!

---

As [someone mentioned](https://github.com/Expensify/App/issues/23066#issuecomment-1640029682) before we should consider treating any subthread as archived (i.g. right now in the subthreads we can send a reply or delete messages). But I believe that should be treated as a new issue.

For now, let's focus on this one. I've prepared my proposal, which addresses the root cause of the issue.

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The user can't close the error message of the first message in the subthread.

### What is the root cause of that problem?
We use the incorrect `reportID` when clearing the error message of the first action of the subthread. We use the children's `reportID` instead of the original one.

### What changes do you think we should make to solve the problem?
We should fix the root cause of this issue, that is fixing closing the error message, because there might be other error messages.

In the `deleteReportComment` function, first what we do, we do is `ReportUtils.getOriginalReportID(reportID, reportAction)`, which gets us a correct reportID.

https://github.com/Expensify/App/blob/0bdf18378356d6f4d5dd0aada5182b3c1648fa4e/src/libs/actions/Report.js#L897-L898

We should use a similar approach in the [`clearReportActionErrors`](https://github.com/Expensify/App/blob/0bdf18378356d6f4d5dd0aada5182b3c1648fa4e/src/libs/actions/ReportActions.js#L10) function. We should use here the [`getOriginalReportID`](https://github.com/Expensify/App/blob/0bdf18378356d6f4d5dd0aada5182b3c1648fa4e/src/libs/ReportUtils.js#L2966) method to get the correct `reportID`. In that way, we will correctly clear the error message.

<details>
<summary>
Video presenting the solution
</summary>

https://github.com/Expensify/App/assets/104823336/fc794392-7966-49a6-a7ff-c794d35821b5

</details>

We should consider also hiding the `Delete` button, where it is not needed (where the backend prevents the user from deleting the message). But it is **not** enough because the backend might return other error messages than this one in some other scenarios.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexpensify** [comment] 2023-08-17 22:48
I followed up in the discussion here: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1692312485065409?thread_ts=1692277687.190129&cid=C01GTK53T8Q

**Comment by alexpensify** [comment] 2023-08-18 21:18
@abdulrahuman5196 - when you get a chance, can you review the proposal and the Slack thread? I'd like to keep this one moving forward. Thanks!

**Comment by kosmydel** [comment] 2023-08-21 06:50
Hey, just a quick update. Apparently, [another PR](https://github.com/Expensify/App/pull/24404) will update the context menu (i.g. hide the `Delete` button).

Regarding this matter, my suggestion is to prioritize resolving the error alerts that occur when closing the first thread message. I am ready to create the PR for this issue.

**Comment by alexpensify** [comment] 2023-08-21 17:50
@abdulrahuman5196 - when you get a chance, please confirm if you agree with the plan from @kosmydel or reply in the thread to keep this one moving forward. Thanks!

**Comment by kosmydel** [comment] 2023-08-23 06:29
Hey, quick update. [The other PR](https://github.com/Expensify/App/pull/24404) was merged and the `Delete` button doesn't show anymore. But I believe that we should still resolve this issue since another error message might appear here.

**Comment by abdulrahuman5196** [comment] 2023-08-23 16:23
@kosmydel Got it. I too think it might be good to fix the cause.

But instead of simulating by code, is there possible usecase where this could occur?

**Comment by kosmydel** [comment] 2023-08-24 12:02
> But instead of simulating by code, is there possible usecase where this could occur?

Yes, we should look for real use cases. But those errors are generated on the BE side, so it might be hard to find something without access to its source code.


> I think we have a case:

I couldn't reproduce it locally. Could you record a video of it?

**Comment by alexpensify** [comment] 2023-08-28 23:09
@abdulrahuman5196 were you able to review the recent questions? I'm catching up from being OOO and trying to catch up here. Thanks for the update!

**Comment by alexpensify** [comment] 2023-08-30 22:21
@abdulrahuman5196 any update here?

**Comment by abdulrahuman5196** [comment] 2023-09-04 10:06
> Hey, quick update. [The other PR](https://github.com/Expensify/App/pull/24404) was merged and the `Delete` button doesn't show anymore (for the first message of reply in the archived workspace). But I believe that we should still resolve this issue. A different error message might appear here and the user will not be able to close it as before.
> 
> We can still simulate this error by passing `false` [here](https://github.com/Expensify/App/blob/4f412db5e26782740529eb0ef17b5db157628413/src/pages/home/report/ReportActionItem.js#L553).

I agree on the point made by @kosmydel . Any error message which comes on thread parent action will be affected by this issue. 

**So I suggest to fix the`clearReportActionErrors` by using the `getOriginalReportID`**. Now the multiple proposals which suggested the same are almost similar with more of PR level improvements. So I am going with the first proposal which suggested this fix.

Proposal by @namhihi237 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by mountiny** [comment] 2023-09-04 13:10
@namhihi237 yes just remind yourself once payment will be done

**Comment by alexpensify** [comment] 2023-09-19 22:54
The payment date is set for tomorrow. @abdulrahuman5196 can you please complete the checklist? Thanks!

**Comment by alexpensify** [comment] 2023-09-19 22:58
Here is the payment summary: 

-  External issue reporter @namhihi237 $250 
-  Contributor that fixed the issue @namhihi237 $1000 
-  Contributor+ that helped on the issue and/or PR @abdulrahuman5196 $1000 

Upwork Job: https://www.upwork.com/jobs/~015d5aa7db1e165a4f

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: No urgency bonus here but it was completed in time for no deductions either.

**Comment by alexpensify** [comment] 2023-09-20 22:58
Alright everyone has been paid in Upwork. @namhihi237 I added a bonus to cover the missing amount for the reporter payment. 

@abdulrahuman5196 - please complete the checklist so we can close this GH. Thanks!

**Comment by alexpensify** [comment] 2023-09-25 07:55
@abdulrahuman5196 bumping this GH, please complete the checklist. Thanks!

**Comment by abdulrahuman5196** [comment] 2023-09-27 15:04
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Minor case, which is hard to reproduce in UI.

**Comment by abdulrahuman5196** [comment] 2023-09-27 15:04
@alexpensify Sorry for the delay. Added the checklist.

**Comment by alexpensify** [comment] 2023-09-29 01:36
Thank you! Closing for now.

**Closed by alexpensify** 2023-09-29 01:36 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
