### ISSUE TITLE
[$500] Android(Dev)- console error on opening app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29466] opened 2023-10-12 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev
**Reproducible in staging?:** Reproduced on Dev only
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697089386857229

## Action Performed:
1. open the app
## Expected Result:
should not show console error
## Actual Result:
console error appears (`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.)
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/b9c32063-213d-4b95-93b1-8ec70cc7976b

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/221a788e-5e14-4534-a1cd-6942bc75ea2b

</details>

<details>
<summary>iOS: Native</summary>

</details>

https://github.com/Expensify/App/assets/38435837/5e88ff2c-30d7-4060-9434-241a2d37c64f

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/63b7a697-771d-46d9-afd8-1d25c72e6c70

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/8c7a1bfe-83cc-4cf6-87b6-66594d664f0a

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/3411b99d-a893-4162-ad93-8795f5497861

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efa9431d43c0d6da</li>
        <li>Upwork Job ID: 1712501752503910400</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-10-12 19:26
This is not an issue, in #29119 we have upgraded the Clipboard package which does uses `NativeEventEmitter`. To remove this error rebuild android app and it goes away.

After building the android app this issue won't come, so we can close this.

**Comment by Rupen-project** [comment] 2023-10-12 21:42
Hello sir
I want to propose one solution to this.
For this, I have to check If you are using third-party libraries, especially those that bridge React Native with native code, and review their documentation and issues on their GitHub repository. It's possible that the library you are using has a known issue, or there might be specific instructions to follow.

**Comment by Rupen-project** [comment] 2023-10-12 21:48
Contributor details
Your Expensify account email: rupen.rakholiya.official@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c5b478a9054aecb9

Hello sir
I want to propose one solution to this.
For this, I have to check If you are using third-party libraries, especially those that bridge React Native with native code, and review their documentation and issues on their GitHub repository. It's possible that the library you are using has a known issue, or there might be specific instructions to follow.

**Comment by graylewis** [comment] 2023-10-12 23:10
## Proposal
## Please re-state the problem that we are trying to solve in this issue.
There is an unrecognized console.log() error when the app is opened

### What is the root cause of that problem?
There is a known issue on the current version of react-native-blob-util causing this error message. It's set to be fixed soon https://github.com/RonRadtke/react-native-blob-util/issues/274

### What changes do you think we should make in order to solve the problem?
Once the library is updated to fix this problem (a commit was pushed 2 weeks ago and should be released soon) this message shouldn't be shown anymore. In the meantime, the solution is to hide the warning: 

In App.js:
```
import { LogBox } from 'react-native';
LogBox.ignoreLogs(['new NativeEventEmitter']);
```

**Comment by alexpensify** [comment] 2023-10-13 17:16
@rushatgabhane do you agree with the feedback to close? Thanks!

**Comment by alexpensify** [comment] 2023-10-16 23:31
@rushatgabhane any feedback on whether we close or review the proposals here? Thanks!

**Comment by alexpensify** [comment] 2023-10-17 23:57
Alright, thank you everyone for the feedback. I'm going to close for now.

**Closed by alexpensify** 2023-10-17 23:57 UTC
Labels: External, Daily, Help Wanted, Bug
