### ISSUE TITLE
[Help Wanted] [$250] Split - 1:1 DM from split members in LHN changes to split creator after bill is split

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39268] opened 2024-03-29 17:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Manual
3. Create a split manual with two users that have no chat history
4. Note tha 1:1 DM in LHN created from the split

## Expected Result:
In LHN, 1:1 DM will show the split member name and avatar

## Actual Result:
Initially, 1:1 DM shows the split member name and avatar in LHN. After a while, it changes to the split creator

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/26100da2-85fa-428a-b559-c7dfaa7f9ec4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb9c7261bfe39aa2</li>
        <li>Upwork Job ID: 1775611147171434496</li>
        <li>Last Price Increase: 2024-04-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-29 17:33
We think that this bug might be related to #vip-split

**Comment by lanitochka17** [comment] 2024-03-29 17:33
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment] 2024-04-03 19:47
Able to repro, plus the OP comment steps and video are really well done. 

Went through Slack for Splits and can't find a dupe of this or a reason to hold it. I'll let the curator assign priority.

**Comment by burczu** [comment] 2024-04-08 08:09
Hello, I am Bartek from Callstack - expert contributor group. I’d like to work on this issue.

**Comment by burczu** [comment] 2024-04-12 07:39
@parasharrajat Hi! I'm sorry for not posting updates hare - I'm involved in the Guided Setup project right now and was asked to prioritise it. I think I've managed to identify the issue in this ticket which probably is caused by the mismatch between the response of the `SplitBillAndOpenReport` and regular `OpenReport` API endpoints, but I had no time right now to dig deeper and propose the solution.

**Comment by burczu** [comment] 2024-04-17 10:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After splitting expense, the LHN shows correct member name and its avatar for a while, to switch to `Hidden` (or split creator name) after few seconds.

### What is the root cause of that problem?

The root cause of the issue is the mismatch between the response of the `SplitBillAndOpenReport` called when splitting expense and regular `OpenReport` API endpoints used to open the 1:1 DM. When we split, we optimistically set the LHN entry with the correct name and avatar, but when the `SplitBillAndOpenReport` returns the response it does not contain correct data. Later, when we click on the LHN entry, the `OpenReport` endpoint is called, returning the correct data and updating the Onyx key (`personalDetailsList`).

Here's the difference between these two responses:

- `SplitBillAndOpenReport` - we get update for the `personalDetailsList` Onyx key that contain too few information:

![Screenshot 2024-04-17 at 12 04 42](https://github.com/Expensify/App/assets/7771498/597a0da0-7771-4629-a68f-3823ba2aa479)

- `OpenReport` - the same `personalDetailsList` Onyx key contains additional information used in the LHN entry like `login` or `displayName`:

![Screenshot 2024-04-17 at 12 05 11](https://github.com/Expensify/App/assets/7771498/756364fa-7a24-4336-bac5-6d33c70d7c4e)

### What changes do you think we should make in order to solve the problem?


I think the issue should be fixed on the backend side - the `SplitBillAndOpenReport` endpoint should respond with correct data for the LHN entry (the `personalDetailsList` Onyx key).

### What alternative solutions did you explore? (Optional)

n/a

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by cristipaval** [comment] 2024-04-22 08:22
yes, this seems to be an issue that needs to be fixed internally

**Comment by cristipaval** [comment] 2024-04-22 08:41
I don't know why Melvin added Overdue label 2 mins later after removing it

**Comment by strepanier03** [comment] 2024-04-25 00:59
@burczu - Any update you can share to appease Melvin?

**Comment by burczu** [comment] 2024-04-25 07:13
@strepanier03 no updates but, as I wrote in the proposal, the issue should be checked by someone from the backend team, so nothing to do for me, at least for now

**Comment by strepanier03** [comment] 2024-04-30 02:24
@cristipaval - Just checking, is this something you're working on or should I put the Help Wanted label back on this?

**Comment by cristipaval** [comment] 2024-04-30 14:04
This is internal. It needs to be fixed in the backend. I'm head down with the Invoicing project so it would help if you recruited another engineer with context on the split. Maybe @youssef-lr if he has time.

**Comment by strepanier03** [comment] 2024-05-02 19:42
Thank you Cristi, I appreciate the info. I'll see if we can find someone else for this. @youssef-lr - if you have time and desire to work on it, feel free to assign yourself and remove the help wanted label.

**Comment by strepanier03** [comment] 2024-05-07 20:16
Help wanted for now while everyone is heads down on release work. Likely won't get worked on for another week or so at best.

**Comment by mvtglobally** [comment] 2024-05-13 14:17
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment] 2024-05-15 23:59
No worries @cristipaval - Good luck with invoicing 🤞 

Thanks for the heads up @mvtglobally.

**Comment by strepanier03** [comment] 2024-05-21 19:36
Looking for ownership still, it's labeled correctly for visibility.

**Comment by strepanier03** [comment] 2024-05-24 20:29
No update.

**Comment by strepanier03** [comment] 2024-05-29 20:42
Hasn't been picked up internally yet, no update.

**Comment by mvtglobally** [comment] 2024-05-30 01:27
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2024-07-03 14:32
Issue not reproducible during KI retests. (Third week)

**Comment by mvtglobally** [comment] 2024-07-11 03:52
Issue not reproducible during KI retests. (Fourth week)

**Comment by strepanier03** [comment] 2024-07-16 00:24
In light of 4 weeks of testing, I'm closing.

**Closed by strepanier03** 2024-07-16 00:24 UTC
Labels: Monthly, Internal, Help Wanted, Overdue, Bug, Hot Pick
