### ISSUE TITLE
[$250] Android – Task – Workspace #Admin is missing in Share somewhere when create task via FAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46210] opened 2024-07-25 16:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4768436
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new Workspace
4. Tap on FAB and select Assign task
5. Enter title and press Next button
6. Tap on Share somewhere

## Expected Result:
Workspace #Admin is present in Share somewhere list

## Actual Result:
Workspace #Admin is missing in Share somewhere list. Admin room is missing in LHN when creating a new WS

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/53f1ebc8-01db-402e-82a5-eb9e8a4a0452

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107a104c210fb6f47</li>
        <li>Upwork Job ID: 1816553628393769523</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-07-25 16:37
We think that this bug might be related to #vip-vsp

**Comment by AndrewGable** [comment] 2024-07-25 16:47
Doesn't really look like any changes to `SearchForReports` in 2+ months on the backend, so thinking this might be a front end change

**Comment by francoisl** [comment] 2024-07-25 19:12
Can't repro on Android native 9.0.12-0

https://github.com/user-attachments/assets/b56f6eff-7b77-454d-b655-de49362f9536

**Comment by AndrewGable** [comment] 2024-07-25 19:18
If it's not reproducible every time and it's a smaller feature (tasks), let's not block on it. We will treat it as a normal bug.

**Comment by bernhardoj** [comment] 2024-07-26 03:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The WS #admin room doesn't show in LHN or in the task share somewhere.

### What is the root cause of that problem?
> Don't show the #admins room in the LHN till there is (1) another admin (2) there is a policy audit log to review. (3) The user clicks on chat with your guide link in onboarding

This happens after https://github.com/Expensify/App/pull/45048 where we hide #admins room if it's "empty". 
https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/libs/ReportUtils.ts#L5580-L5583

This works well for LHN, however, `shouldReportBeInOptionList` is being used in 3 places. 1 for the LHN (SidebarUtils), 
1 for the unread indicator updater, to count how many unread
https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/libs/UnreadIndicatorUpdater/index.ts#L11-L23

and the last one is in `getOptions`, to get the list of options of search, share somewhere, etc.
### What changes do you think we should make in order to solve the problem?

We can add a new param called `excludeEmptyAdmins` which defaults to true and set it to false for `getOptions`.
```
if (excludeEmptyAdmins && isAdminRoom(report) && !shouldAdminsRoomBeVisible(report)) {
    return false;
}
```

We can set it to true for the unread indicator updater too, but I think we don't want to count unread from reports that don't show in LHN.

**Comment by bernhardoj** [comment] 2024-07-30 02:08
> but I just want to try to understand what is different and why you'd like to add a new one.

I think the only other difference is that in UnreadIndicatorUpdater, we include empty chat when calculating unread reports. But this doesn't affect the current empty chat because if it's empty, then it won't affect the unread count.

I think we can use excludeEmptyChats but also update UnreadIndicatorUpdater to exclude empty chat.

**Comment by puneetlath** [comment] 2024-07-30 13:54
Wait, hmm. Is this actually a bug? Can they post directly in the #admins room in this scenario? If not, I think it'd make sense that they also can't share tasks to it.

**Comment by bernhardoj** [comment] 2024-07-30 14:26
We currently can't access the #admins room from the search page, but we can still open it from the workspace page Go to #admins.
<img width="581" alt="image" src="https://github.com/user-attachments/assets/82cf3528-da6c-4f60-8c4b-ebcedef0b498">

**Comment by puneetlath** [comment] 2024-08-01 18:13
I'm sorry y'all, after thinking about it more, I don't actually think we should do this. If we aren't showing the #admins room in the chat switcher, then it makes sense to me that you also can't share tasks to it. I'm gonna close this out, but feel free to comment/reopen if you disagree!

**Closed by puneetlath** 2024-08-01 18:13 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
