### ISSUE TITLE
Tick mark is not horizontally aligned with text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18811] opened 2023-05-12 02:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send money or request money and settle it
2. Observe the tick mark and the text on the left side of it

## Expected Result:
The tick mark should be horizontally aligned with the text on the left side of it
## Actual Result:
The tick mark is slightly lower than the text on the left side of it and looks misaligned

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [] Android / native
- [x] Android / Chrome
- [] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13-1
**Reproducible in staging?:** y
**Reproducible in production?:**  
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5f891374-44a8-4f0f-a47f-87fb46ddc312

https://github.com/Expensify/App/assets/43996225/56032558-400f-4bf2-b837-ef98e56aa235

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683795373375449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by payal-lathidadiya** [comment] 2023-05-12 10:45
Unable to reproduce in staging as well as production.

Alignment looks good.

<img width="527" alt="image" src="https://github.com/Expensify/App/assets/130229379/35a24e96-bf84-40a7-b8d0-6aa3cbdcb6aa">

**Comment by alexpensify** [comment] 2023-05-13 16:32
Closing - I'm unable to replicate 
![image](https://github.com/Expensify/App/assets/8107070/c20f0d6e-3de8-465d-a455-94cbc79e835c)

**Closed by alexpensify** 2023-05-13 16:32 UTC
Labels: Daily, Bug
