### ISSUE TITLE
[HOLD for payment 2024-08-02]  Dupe detection - Confirm button is below the content instead of page bottom

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45831] opened 2024-07-20 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/42571
**Version Number:**  9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Preconditon:
- Device font size may need to be reduced.

1. Launch New Expensify app.
2. Go to workspace chat.
3. Submit two same expenses (same amount and merchant).
4. Go to transaction thread of any expense.
5. Tap Review duplicates.
6. Tap Keep this one (any).
7. Proceed to confirmation page.

## Expected Result:
Confirm button will be docked to the bottom.

## Actual Result:
Confirm button is below the content.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f8777359-3478-401d-8ed8-551a64d577ff

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by mountiny** [comment] 2024-07-20 20:06
cc @pecanoro @JmillsExpensify @parasharrajat

**Comment by mountiny** [comment] 2024-07-20 20:13
Lets get that confirmed, I can see the reasoning but its against our patterns in the app

**Comment by mountiny** [comment] 2024-07-20 20:34
Asked [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1721506437934299?thread_ts=1721483585.040009&cid=C01GTK53T8Q)

**Comment by mountiny** [comment] 2024-07-20 22:27
Discussed in Slack this is not a blocker as the feature is behind beta.

We should however dock this to the bottom @kubabutkiewicz @parasharrajat

**Comment by kubabutkiewicz** [comment] 2024-07-22 08:31
Hi, I will create PR to fix that issue soon @mountiny @parasharrajat @pecanoro

**Comment by pecanoro** [comment] 2024-07-22 17:10
@grgia  I am reassigning the issue to myself so I can review and track the fixes since this is for the duplicate detection project that I am handling.

**Comment by sonialiap** [comment] 2024-08-02 11:51
@pecanoro @parasharrajat looks like payment will be handled [here](https://github.com/Expensify/App/issues/45815#issuecomment-2240902410), is that correct?

**Closed** 2024-08-02 12:49 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
