### ISSUE TITLE
[$250] Distance rates - Distance rate is not grayed out when workspace is created offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43559] opened 2024-06-12 12:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
#issue found when validating #43071
**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Create a new workspace.
4. Go to Categories.
5. Note that all categories are grayed out.
6. Go to More features.
7. Enable Distance rates.
8. Go to Distance rates.

## Expected Result:
The distance rate in the list will be grayed out.

## Actual Result:
The distance rate in the list is not grayed out when workspace is created offline.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/b0a5dffb-62a0-4445-9c73-e358451c9f52

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bdb049912130299</li>
        <li>Upwork Job ID: 1800954285340721751</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by m-natarajan** [comment] 2024-06-12 12:49
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-12 12:50
We think that this bug might be related to #wave-collect - Release 1

**Comment by isabelastisser** [comment] 2024-06-13 13:34
Bump @ahmedGaber93 to review the proposals above. Thanks!

**Comment by ahmedGaber93** [comment] 2024-06-14 08:49
Reviewing

**Comment by ahmedGaber93** [comment] 2024-06-14 21:40
@etCoderDysto Thanks for the proposal, adding `pendingAction: 'add'` in optimistic data will fix the issue, but you missed to mention remove it in success and failure data, and this will cause a regression when user back again to offline, the item color will back gray again.



<details>
<summary>regression video</summary>

https://github.com/Expensify/App/assets/41129870/cd61361b-92ce-4190-98bf-118da1e38b36

</details>

I think we can move forward with @Krishna2323's [alternative solutions](https://github.com/Expensify/App/issues/43559#issuecomment-2163297639) which cover remove `pendingAction: 'add'` in success and failure data.

🎀 👀 🎀 C+ reviewed

**Comment by etCoderDysto** [comment] 2024-06-15 03:25
You are right, @ahmedGaber93. But I am not sure how adding 'pendingAction' is success data can be possible since we have to add it to `customUnits:{ customUnitID: {rates: customUnitRateID { pendingAction: null}}}`. How can we access customUnits and  customUnitRateID values for the current policy in success data? And this logic might not cover a scenario where the user creates workspace in online mode, and then toggles distance rate in offline mode. I don't think success data will clear the pending action in this scenario.

**Comment by ahmedGaber93** [comment] 2024-06-15 23:21
> How can we access customUnits and customUnitRateID values for the current policy in success data?

We don't handle it manual, we just need to pass it to `API` lib, and it will merge them. successData here not mean the API response data, but it means merge this when api success, and it mostly used to remove optimisticData
```javascript
API.write(WRITE_COMMANDS.CREATE_WORKSPACE, params, {optimisticData, successData, failureData});
```

**Comment by etCoderDysto** [comment] 2024-06-16 01:23
Got it! Thanks for the explanation 🙏

**Comment by ahmedGaber93** [comment] 2024-06-19 18:24
Ready to assignment

**Comment by etCoderDysto** [comment] 2024-06-19 18:28
This issue seems to be fixed [here](https://github.com/Expensify/App/pull/43849)

**Comment by tylerkaraszewski** [comment] 2024-06-20 16:25
Can we check and see if this is already fixed and close this if so?

**Comment by ahmedGaber93** [comment] 2024-06-20 16:58
checking

**Comment by ahmedGaber93** [comment] 2024-06-20 17:06
I can't reproduce the issue in the latest main

https://github.com/Expensify/App/assets/41129870/92bbf569-72d9-447f-a98d-cec9e652b3b6

**Comment by tylerkaraszewski** [comment] 2024-06-20 17:24
@isabelastisser - do we need to do anything special here for the C+ who's looked at this so far or can we just close it?

**Comment by isabelastisser** [comment] 2024-06-22 01:27
I believe we can close this. @ahmedGaber93 please let us know if you disagree. Thanks!

**Closed by isabelastisser** 2024-06-22 01:27 UTC
Labels: External, Daily, Help Wanted, Bug
