### ISSUE TITLE
[$250] CRITICAL: [Track expense] Self DM OpenReport isn’t returning transaction

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#42587] opened 2024-05-24 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @quinthar 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/397848
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C066HJM2CAZ/p1716188511708689?thread_ts=1716187933.546269&cid=C066HJM2CAZ

## Action Performed:
1. Created an expense in OldDot, and it was auto-reported
2. Unreported it in OldDOt

## Expected Result:
- The expense loads clearly in NewDot without clicking on it
- The self DM OpenReport returns  the transaction
- The transaction thread OpenReport is doesn't return the self DM OR returns it for a valid reason

## Actual Result:
- The expense skeleton flashes in the self DM until it's clicked, then it corrects.
- The self DM OpenReport isn't returning transaction
- The transaction thread OpenReport is returning the self DM for no reason

## Workaround:
N/A - clicking on the transaction makes it show, but the extraneous API calls can't be fixed or stopped by the user.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Screenshots and more context in thread.](https://expensify.slack.com/archives/C066HJM2CAZ/p1716187933546269)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @techievivek</details>

**Comment by garrettmknight** [comment] 2024-05-24 13:02
@shubham1206agra @ishpaul777  can you investigate as a follow up to [this slack thread?](https://expensify.slack.com/archives/C066HJM2CAZ/p1716187933546269)

**Comment by garrettmknight** [comment] 2024-05-28 12:51
@shubham1206agra said he was going to look into it today.

@ishpaul777 this is a unique issue where we've got a C+ (you) proposing a fix. I think we should mark this as C+ reviewed to get an internal engineer to review. Can you C+ review for yourself?

**Comment by marcaaron** [comment] 2024-05-28 21:57
@thienlnam Any chance you or someone working on the self DM project can look into this? My hands are tied with other tasks at the moment and it's at a CRITICAL priority. Preemptively adding the `Hot Picks` label here anyway 😄

**Comment by thienlnam** [comment] 2024-05-28 22:11
Catching up on a few things after OOO and fire-rooms, so currently cannot but should have more time next week if no one else can get to it

**Comment by marcaaron** [comment] 2024-05-31 21:13
@thienlnam Is there someone else from the project team that can look into this?

**Comment by thienlnam** [comment] 2024-05-31 22:38
cc @techievivek Since you're the most familiar with the self-DM do you have the free cycles to investigate?

**Comment by techievivek** [comment] 2024-06-03 05:17
Yes, I can investigate, thanks.

**Comment by garrettmknight** [comment] 2024-06-10 20:56
@techievivek We make any headway on the investigation?

**Comment by garrettmknight** [comment] 2024-06-11 08:47
Looks like Vivek is OOO today - we'll keep an eye out for an update tomorrow.

**Comment by techievivek** [comment] 2024-06-13 13:05
Ok, I was able to reproduce and it seems like we don't explicitly return any transactions for selfDM report. We only return the current report, reportactions and personaldetails data.

**Comment by techievivek** [comment] 2024-06-19 09:49
Not overdue, will take a closer today after QSP is done.

**Comment by techievivek** [comment] 2024-06-25 14:44
Pushed a PR to fix the behaviour, will add the integration tests shortly.

**Comment by techievivek** [comment] 2024-07-04 07:06
Stil on review with Jack.

**Comment by techievivek** [comment] 2024-07-12 14:30
This issue has been fixed in this PR: https://github.com/Expensify/Auth/pull/11358. We can close this since no payment is needed; it was resolved internally.

**Closed by techievivek** 2024-07-12 14:30 UTC
Labels: Reviewing, Daily, Internal, Bug, Hot Pick
