### ISSUE TITLE
[$250]  IOU - The first time you log into IOU and load details, the application crashes

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41195] opened 2024-04-29 10:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4520559
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in to your HT account
3. Open a DM with any existing HT account
4. Send any message
5. Send 3 IOUs
6. Re-enter with the login from step 2
7. Go to the conversation with the sent IOUs
8. Open the sent IOUs

## Expected Result:
When loading data from the IOU, there should be no application crashes.

## Actual Result:
The first time you log into IOU and load details, the application crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a8e40b06-8abe-49a4-8dcf-526836f7c744

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01595f837f9698af69</li>
        <li>Upwork Job ID: 1784931771874824192</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-29 10:03
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-29 10:03
We think this issue might be related to the #vip-bills.

**Comment by izarutskaya** [comment] 2024-04-29 10:04
Production


https://github.com/Expensify/App/assets/115492554/3dabb078-7f24-45e3-84a9-bd4bd92a9ae4

**Comment by danieldoglas** [comment] 2024-04-29 13:04
This one is really a deploy blocker. Adding external label

**Comment by thienlnam** [comment] 2024-04-29 21:06
I can't reproduce this on staging anymore - I'm guessing this was fixed by one of the other PRs that fixed a crash

**Closed by thienlnam** 2024-04-29 21:06 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
