### ISSUE TITLE
[$250] Thread - App shows join button after user joined offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46004] opened 2024-07-23 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4753350
**Email or phone of affected tester (no customers):** bezawitgebremichael+100@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team *

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB
3. Click on start chat
4. Insert an email address and start a chat
5. Send a message
6. Hover over the message and click on reply in thread
7. Send some messages
8. Open the network tab and go offline
8. Click on thread header
9. Click on leave
10. Click on Join
11. Go online

## Expected Result:
The user stays joined back in the thread

## Actual Result:
The join button reappears again and user has to click join again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/409bbf72-3098-492b-8544-44da574833f0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114c22d59f2094554</li>
        <li>Upwork Job ID: 1815812057496731128</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by izarutskaya** [comment] 2024-07-23 12:29
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-07-23 12:30
Production 

https://github.com/user-attachments/assets/99a5064e-36a8-448a-a4ca-21a9b39e2295

**Comment by MariaHCD** [comment] 2024-07-23 14:35
At first glance, this seems like a frontend issue 🤔 I see LeaveRoom was called when the user got back online but maybe we should have also called the Api command to rejoin the thread?

**Comment by srikarparsi** [comment] 2024-07-23 18:11
This looks frontend, going to try applying the external label

**Comment by brunovjk** [comment] 2024-07-23 19:23
Reviewing proposal

**Comment by Zakpak0** [comment] 2024-07-24 00:27
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
After creating a thread, if a user was to go offline then leave the thread and then rejoin, the join button will appear on the screen when it is not supposed to be there.
### What is the root cause of that problem?
When the user is brought back online the **Sequential Queue** processes the requests that weren't able to be made while the user is offline.
This means:
User leaves thread -> User rejoins thread
In that order.
So after the **User Left Thread** request, there is a period that the **User Rejoined Thread** request had not been completed.
 
### What changes do you think we should make in order to solve the problem?
Add a pending field to our notification update function so we have a flag to look for while we're processing actions.
[src/libs/actions/Report.ts](https://github.com/Expensify/App/blob/main/src/libs/actions/Report.ts#L1685-L1699)
```typescript
    const optimisticData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: {
                notificationPreference: newValue,
                pendingFields: {
                    notificationPreference: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE
                }
            },
        },
    ];
    const successData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: {
                pendingFields: {
                    notificationPreference: null
                }
            },
        },
    ];
```
Then modify our canJoin boolean to read that flag and be patient.
[src/pages/home/HeaderView.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/HeaderView.tsx#L107)
```typescript
    const isPendingNotificationUpdate = report?.pendingFields?.notificationPreference
    const canJoin = useMemo(() => {
        if (isPendingNotificationUpdate) {
            return false
        }
        return ReportUtils.canJoinChat(report, parentReportAction, policy);
    }, [isPendingNotificationUpdate]) 
```
[Here](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2346004) is a test branch with my changes

### What alternative solutions did you explore? (Optional)
N/A

**Comment by srikarparsi** [comment] 2024-07-24 08:50
To clarify from the issue body, the join button does disappear after a moment. The leave button isn't currently in prod so it's a little difficult to compare. @mountiny do you know if this is expected with the sequential queue or should this be fixed?

https://github.com/user-attachments/assets/0058c098-636f-46c5-b503-17d4453c1632

**Comment by francoisl** [comment] 2024-07-24 17:30
Thanks for the proposals so far. Can you identify which PR from [the checklist](https://github.com/Expensify/App/issues/45991) caused the regression? Anyway, going to demote as a polish issue since it's for offline behavior that doesn't break any critical flow.

**Comment by mountiny** [comment] 2024-07-25 23:34
I think this is happening as we process the API commands in the backend and we queue the relevant onyx updates. First, the app processes, leaving the thread so it gets hidden and then it joins again.

I think we do not have to worry about this one too much and might even close it

**Comment by srikarparsi** [comment] 2024-07-29 01:41
I agree, closing this one out since the expected behavior (the join button not showing) does occur, it just takes a second because of the sequential queue.

**Closed by srikarparsi** 2024-07-29 01:41 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
