### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] Link to a Broken/Unfunctional Page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19396] opened 2023-05-22 16:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to setting > Help > Playbook > Expensify Playbook for US Based Bootstrapped Startups
2. Notice the "Step 1: Create your Expensify account" title
3. In the article under the title "Step 1: Create your Expensify account" Click the link "new.expensify.com"
4. notice the resulting page

## Expected Result:
A new sign-up Page
## Actual Result:
Broken image with error reporting and a "The page is no where to be found." text

1. [This line](https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#L8) has a broken URL
2. [This line](https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#LL17C63-L17C63) has a typo on Expensify in the URL, and needs to be prefixed by https://
3. [This line](https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#L28) needs to be made into a hyperlink to https://new.expensify.com
4. [This line](https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-Small-to-Medium-Sized-Businesses.md?plain=1#L17) needs to be made into a hyperlink to https://new.expensify.com
5. [This line](https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-based-VC-Backed-Startups.md?plain=1#L18) needs to be made into a hyperlink to https://new.expensify.com

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5d017025-e00e-4d8e-a943-ca904d1078d6

https://github.com/Expensify/App/assets/43996225/ac0a4f33-eb9a-467a-9712-00d47cc8ba5a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @amanuel-arega
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684485277897929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bbc1f4dbe451c351</li>
        <li>Upwork Job ID: 1660718109505835008</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-05-22 17:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Link to a Broken/Unfunctional Page
### What is the root cause of that problem?
The link is not given correctly here
https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#L17
It should start with `https://
### What changes do you think we should make in order to solve the problem?


Update it to be `https://new.expensify.com`

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-05-22 17:12
Updated with alternative solution - https://github.com/Expensify/App/issues/19396#issuecomment-1557593993

**Comment by conorpendergrast** [comment] 2023-05-22 18:45
@zsgreenwald Hey! Looks like you were last to touch this help page, so FYI there's some broken links in here. 
eg, [this line](https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#L8): 
```
- See our *[Playbook for Small to Medium-Sized Businesses]([url](https://help.expensify.com/articles/playbooks/Expensify-Playbook-for-Small-to-Medium-Sized-Businesses))* if you are more concerned with maintaining profitability than growing top-line revenue.
```

Should be: 
```
- See our *[Playbook for Small to Medium-Sized Businesses](https://help.expensify.com/articles/playbooks/Expensify-Playbook-for-Small-to-Medium-Sized-Businesses)* if you are more concerned with maintaining profitability than growing top-line revenue.
```

**Comment by conorpendergrast** [comment] 2023-05-22 18:51
@alitoshmatov Nice spot with the other two pages too. I updated the OP to list out the five things I've found so far

**Comment by alitoshmatov** [comment] 2023-05-22 19:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Link to a Broken/Unfunctional Page
### What is the root cause of that problem?
The link is not given correctly here
https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#L17
It should start with `https://
### What changes do you think we should make in order to solve the problem?

1.
https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#LL17C63-L17C63
Should remove mismatched brackets and `url` word, and fixed.
2.
https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#LL17C63-L17C63
We should have a valid url beginning with `https://`
3. new.expensify.com should be hyperlink
4, 5. We should update old link to new `new.expensify.com`


### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-05-22 19:51
Posted updated proposal to cover all cases - https://github.com/Expensify/App/issues/19396#issuecomment-1557864567

**Comment by alitoshmatov** [comment] 2023-05-22 20:18
@aimane-chnaif 
Here is instructions to run docs locally
https://github.com/Expensify/App/blob/4067c0f382b55ec6797d851cf957bec706fdc4f3/docs/README.md#L35-L42

**Comment by alitoshmatov** [comment] 2023-05-22 20:22
@aimane-chnaif Yes

**Comment by marcaaron** [comment] 2023-05-23 00:47
Moving forward with the assignment. I will need someone to take this over if we can reapply the `Engineering` label. 🙇

**Comment by alitoshmatov** [comment] 2023-05-23 09:46
@conorpendergrast 
Should I also update this to be clickable links
1. https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#L90
2. https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-Based-Bootstrapped-Startups.md?plain=1#L34
3. https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-Small-to-Medium-Sized-Businesses.md?plain=1#L283
4. https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-based-VC-Backed-Startups.md?plain=1#L32
5. https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks/Expensify-Playbook-for-US-based-VC-Backed-Startups.md?plain=1#L208

**Comment by conorpendergrast** [comment] 2023-05-23 09:47
Yep, please. For 1 and 2, as they're mentioning Concierge, please link to https://new.expensify.com/concierge

**Comment by conorpendergrast** [comment] 2023-05-26 13:48
PR is reviewed and on Staging

**Comment by conorpendergrast** [comment] 2023-06-06 20:03
Paid, with urgency bonus, @aimane-chnaif and @alitoshmatov. Waiting for contract to be accepted to pay amanuel-arega

**Comment by conorpendergrast** [comment] 2023-06-07 14:20
Paid amanuel-arega!

**Comment by conorpendergrast** [comment] 2023-06-07 14:21
Final step is [the bugzero checklist](https://github.com/Expensify/App/issues/19396#issuecomment-1567590021)

**Comment by conorpendergrast** [comment] 2023-06-09 19:00
I would tend to agree, yes. Closing out!

**Closed by conorpendergrast** 2023-06-09 19:00 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
