### ISSUE TITLE
[$250] Emoji appears as larger when writing with a text in the composer 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39867] opened 2024-04-08 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712399898397189
 
## Action Performed:
1. Open any chat
2. Write some text and add an emoji

## Expected Result:
Emoji should not appear as bigger in size

## Actual Result:
Emoji appears bigger and after sending the emoji reduced in size.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/38435837/13859e49-fc24-4176-af80-f4b20bcacd57)

https://github.com/Expensify/App/assets/38435837/614417e5-f1c9-4033-90d3-8c6f211f52a7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133c309a7b0cbb650</li>
        <li>Upwork Job ID: 1778610583524839424</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2024-04-09 00:16
Is this actually a bug? This is how Whatsapp works

**Comment by greg-schroeder** [comment] 2024-04-09 00:17
Oh nevermind I see what you mean, it's larger in the composer than when inline, not that it's larger with no text accompanying it in general (which is expected I think)

**Comment by bernhardoj** [comment] 2024-04-09 08:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The emoji is shown larger in live markdown preview when it should be normal size when there is a text other than emoji, just like in the sent message.

### What is the root cause of that problem?
When there is an emoji, we wrap it with `<emoji>` tag. For the emoji tag, we set the font size to 20.
https://github.com/Expensify/react-native-live-markdown/blob/4a87a7a83898091f6c4521f895cbb1949a9dd39d/src/styleUtils.ts#L26-L28

The style is applied without checking whether the text contains only emojis or not, compared to the sent message where we only make the emojis larger if the text only contains emojis (by passing the `islarge` attribute).
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/comment/TextCommentFragment.tsx#L59-L60

### What changes do you think we should make in order to solve the problem?

We also should conditionally applied the emoji only font size if the text only contains emoji. We can do the simplest fix in our App by passing the custom markdown style.
```
const customMarkdownStyle = useMemo(() => ({
    ...markdownStyle,
    ...(!EmojiUtils.containsOnlyEmojis(value ?? '') ? {emoji: {fontSize: undefined}} : {}),
}), [markdownStyle, value]);

<RNMarkdownTextInput markdownStyle={customMarkdownStyle}
```

### What alternative solutions did you explore? (Optional)
If we want to go with a hard path, we can update expensify-common by adding `islarge` attribute to the emoji tag when parsing the markdown and then update react-native-live-markdown to conditionally apply the emoji font size when `islarge` is present.

**Comment by greg-schroeder** [comment] 2024-04-12 02:26
Sending through to External

**Comment by greg-schroeder** [comment] 2024-04-15 03:02
Pending proposal review from @Santhosh-Sellavel :)

**Comment by twisterdotcom** [comment] 2024-04-16 09:19
Please review these now @rayane-djouah.

**Comment by bernhardoj** [comment] 2024-04-16 11:21
It's already fixed in https://github.com/Expensify/App/pull/39597

**Comment by twisterdotcom** [comment] 2024-04-22 20:43
Let's close.

**Closed by twisterdotcom** 2024-04-22 20:43 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
