### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Bank account - BA icon broken, it is square instead of round

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30215] opened 2023-10-23 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.89-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Bank account -> Connect online with Plaid
4. Complete the process adding BA (use any bank)

## Expected Result:
BA icon has a round form

## Actual Result:
BA icon is broken, it is in square form

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/d971a3ae-76a9-42da-b3cf-f00639d58afe

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ceaebf5fa7a3b700</li>
        <li>Upwork Job ID: 1716575098200141824</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-10-23 23:47
Yeah, @lanitochka17 this doesn't seem to match the bug report. Can you clarify please? :)

**Comment by trjExpensify** [comment] 2023-10-24 09:53
Perf, thanks! @grgia was this intentional to make them squares or something?

**Comment by lanitochka17** [comment] 2023-10-24 13:15
@trjExpensify Sorry for the confusion, I have attached the correct screenshot

![Bug6247985_1698093656920!2310 (1)](https://github.com/Expensify/App/assets/78819774/370cc5a1-4e2e-48dc-adbd-a8c487c2be5a)

**Comment by grgia** [comment] 2023-10-24 14:40
No, this was not intentional. I can fix this, but it looks like the proposal covers the root cause @trjExpensify. Although I think @burczu should assess

**Comment by burczu** [comment] 2023-10-26 11:23
I've just checked [the proposal](https://github.com/Expensify/App/issues/30215#issuecomment-1777109238) from @neonbhai and I think it identifies the root cause correctly. Also the proposed solution does fix the issue so I think we can proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2023-10-30 11:09
@neonbhai how are you getting on with the PR?

**Comment by trjExpensify** [comment] 2023-11-10 18:21
👋 @burczu checklist, please. Thanks!

**Comment by trjExpensify** [comment] 2023-11-13 14:25
Samesies. Awaiting the checklist before proceeding to payments.

**Comment by burczu** [comment] 2023-11-14 12:35
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:

**I don't think it is regression made by any PR - it looks like this icon was just added without rounding and no one has changed this afterwards.**

* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

**n/a**

* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**n/a**

* [x]  [@burczu] Determine if we should create a regression test for this bug.

**I don't think the regression test is necessary here - it was just simple style adjustment.**

* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@trjExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by trjExpensify** [comment] 2023-11-14 21:44
Confirming payments as follows: 

$500 to @neonbhai for the bug fix. Sent an offer to you!

**Comment by trjExpensify** [comment] 2023-11-15 01:32
Paid!

**Closed by trjExpensify** 2023-11-15 01:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
