### ISSUE TITLE
[$1000] Other users see Alaska timezone if the timezone is set to America / Antigua

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18450] opened 2023-05-04 21:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Set timezone as America / Antigua in user A
2. Log in as user B and view the details of User A
## Expected Result:
Should show America / Antigua
## Actual Result:
Showing Alaska timezone
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (3)](https://user-images.githubusercontent.com/43996225/236337966-17e410a8-d9de-4239-9454-3459af406371.png)
![image (2)](https://user-images.githubusercontent.com/43996225/236337968-18d0f2e7-6a53-4963-8931-cd2c3cdab06a.png)
![image (1)](https://user-images.githubusercontent.com/43996225/236337969-fea0d561-65a6-4cfe-a34c-f87ee6a2f25e.png)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683211388772199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01adadc9ebe12f23b6</li>
        <li>Upwork Job ID: 1659248453808365568</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-05-05 17:26
FYI, possibly related: https://github.com/Expensify/App/issues/16871

**Comment by flodnv** [comment] 2023-05-08 20:23
@adelekennedy did you check if it's related?

**Comment by adelekennedy** [comment] 2023-05-10 22:25
Hmm, it looks like the fix for the linked issue was made[ last week ](https://github.com/Expensify/Web-Expensify/pull/37008#issuecomment-1531931804) let's see if still reproducible

**Comment by adelekennedy** [comment] 2023-05-10 22:26
@kavimuru will you try to reproduce this again?

**Comment by flodnv** [comment] 2023-05-18 14:42
2 people have reported to me this week that this bug is back (my timezone makes no sense to them, but it is set to the correct thing)

**Comment by adelekennedy** [comment] 2023-05-18 17:25
I'm moving this to external as it's reproducible and wasn't fixed by the linked issue above!

**Comment by kamaljitSharma21** [comment] 2023-05-18 19:02
@adelekennedy can you please share reproducible steps along with some videos? As it is not reproducing on my system.

**Comment by johnmlee101** [comment] 2023-05-18 20:32
I do not see this on Florent's account, can't reproduce :/

**Closed** 2023-05-19 15:02 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by flodnv** [comment] 2023-05-25 16:40
I'm being told by @danieldoglas and others that this bug is back? 😂 can someone try to reproduce again? What's up with this ghostly bug lol?

**Comment by adelekennedy** [comment] 2023-05-29 20:44
wow - this is the bug that just won't die! I see Flo is still in AKDT but can't figure out how to reproduce myself 😬 @johnmlee101 @eVoloshchak any thoughts?

**Comment by flodnv** [comment] 2023-05-29 21:57
But what time do you see for me? If you see earlier than PDT, it's a bug. If you see EST, then the bug is not there.

**Comment by adelekennedy** [comment] 2023-05-29 21:59
<img width="181" alt="Screenshot 2023-05-29 at 2 59 33 PM" src="https://github.com/Expensify/App/assets/60450566/603c26da-d314-4e12-8233-1e85ad8ed3f0">

**Comment by johnmlee101** [comment] 2023-05-30 14:22
<img width="359" alt="image" src="https://github.com/Expensify/App/assets/5258036/26d63bbd-5ed9-493d-86a4-29ea751d27ef">
😬

**Comment by flodnv** [comment] 2023-05-30 14:58
lol, yes, still a bug

**Comment by johnmlee101** [comment] 2023-06-01 11:23
I will never understand this bug
<img width="361" alt="image" src="https://github.com/Expensify/App/assets/5258036/bcec09be-185c-41e7-af94-95252b8ae4c6">

**Comment by flodnv** [comment] 2023-06-01 14:56
hahaha me neither but it's hilarious 

Maybe next steps are about looking at how we display this? I am 90% sure my timezone is not changing in the App (I am 100% sure the timezone I am in has not changed in 8 weeks 😄 )

**Comment by adelekennedy** [comment] 2023-06-05 21:59
we've moved this to internal but what are next steps to start working on this bug?

**Comment by flodnv** [comment] 2023-06-06 14:19
>what are next steps to start working on this bug?

https://github.com/Expensify/App/issues/18450#issuecomment-1573788708

**Comment by johnmlee101** [comment] 2023-06-06 14:37
https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22timezone%3A%20'%7B%5C%22automatic%5C%22%3A%5C%22true%5C%22%2C%5C%22selected%5C%22%3A%5C%22%22%20AND%20NOT%20blob%3A%22Antigua%22%20AND%20email%3A%22florent%40expensify.com%22%20AND%20timestamp%3A%5B2023-05-07T00%3A00%20TO%202023-06-07T23%3A59%5D 

[y8LXef](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22y8LXef%22)+AND+timestamp:[2023-06-05T12:37:43.100Z+TO+2023-06-05T14:37:43.100Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:37:43 100	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:37:43.100Z+TO+2023-06-05T14:37:43.100Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[UkpxIB](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22UkpxIB%22)+AND+timestamp:[2023-06-05T12:38:29.218Z+TO+2023-06-05T14:38:29.218Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:38:29 218	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:38:29.218Z+TO+2023-06-05T14:38:29.218Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[dIYlxe](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22dIYlxe%22)+AND+timestamp:[2023-06-05T12:39:15.417Z+TO+2023-06-05T14:39:15.417Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:39:15 417	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:39:15.417Z+TO+2023-06-05T14:39:15.417Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[zn0k6d](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22zn0k6d%22)+AND+timestamp:[2023-06-05T12:39:17.043Z+TO+2023-06-05T14:39:17.043Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:39:17 043	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:39:17.043Z+TO+2023-06-05T14:39:17.043Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[IiDUpM](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22IiDUpM%22)+AND+timestamp:[2023-06-05T12:39:23.239Z+TO+2023-06-05T14:39:23.239Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:39:23 239	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:39:23.239Z+TO+2023-06-05T14:39:23.239Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[mYbFFm](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22mYbFFm%22)+AND+timestamp:[2023-06-05T12:41:54.575Z+TO+2023-06-05T14:41:54.575Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:41:54 575	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:41:54.575Z+TO+2023-06-05T14:41:54.575Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[ulwA26](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22ulwA26%22)+AND+timestamp:[2023-06-05T12:41:55.923Z+TO+2023-06-05T14:41:55.923Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:41:55 923	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:41:55.923Z+TO+2023-06-05T14:41:55.923Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[xTxUw1](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22xTxUw1%22)+AND+timestamp:[2023-06-05T12:41:59.244Z+TO+2023-06-05T14:41:59.244Z]&index=logs_expensify-022662)	staging-www1.lax	2023-06-05 13:41:59 244	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T12:41:59.244Z+TO+2023-06-05T14:41:59.244Z]&index=logs_expensify-022662)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[7d28f577be7b0a16-MIA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d28f577be7b0a16-MIA%22)+AND+timestamp:[2023-06-05T13:03:24.990Z+TO+2023-06-05T15:03:24.990Z]&index=logs_expensify-022662)	virt2.rno	2023-06-05 14:03:24 990	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T13:03:24.990Z+TO+2023-06-05T15:03:24.990Z]&index=logs_expensify-022662)	 displayName: 'Jason' pronouns: '' timezone: '[automatic: '1' selected: 'America/Merida']' firstName: 'Jason' lastName: '' payPalMeAddress: 'jasefm' phoneNumber: '' validated: '1']' 5: '[accountID: '2234069' login: 'joanie@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/dbc604c97b65886c42f20e97585f08879d53c84c_128.jpeg' displayName: 'Joanie Wang' pronouns: '__predefined_sheHerHers' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'Joanie' lastName: 'Wang' payPalMeAddress: '' phoneNumber: '' validated: '1']' 6: '[accountID: '4974958' login: 'jschuster@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/272b32cadb0d0f2977f204cc042b27e3c6b797f5_128.jpeg' displayName: 'John Schuster - Online CST business hours' pronouns: '' timezone: '[automatic: '1' selected: 'America/Chicago']' firstName: 'John Schuster' lastName: '- Online CST business hours' payPalMeAddress: '' phoneNumber: '' validated: '1']' 7: '[accountID: '297463' login: 'scott@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/16076ff62541d4bbaed461b6c512a233d2c64e1d_128.jpeg' displayName: 'Scott Deeter' pronouns: '__predefined_heHimHis' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'Scott' lastName: 'Deeter' payPalMeAddress: 'deetergp' phoneNumber: '' validated: '1']' 8: '[accountID: '5356024' login: 'ted@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/5e35961c744c07fd07bb6d7bde5985c4c1874374_128.jpeg' displayName: 'Ted Harris' pronouns: '__predefined_heHimHis' timezone: '[automatic: '1' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e_128.jpeg' avatarHighResolution: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e.jpeg' displayName: 'Ted Harris - at XeroCon until Friday' firstName: 'Ted Harris' lastName: '- at XeroCon until Friday' localCurrencyCode: 'GBP' login: 'ted@expensify.com' payPalMeAddress: '' phoneNumber: '' pronouns: '__predefined_heHimHis' selected: 'Europe/London' timezone: '[automatic: 'true' selected: 'Europe/London']']' firstName: 'Ted' lastName: 'Harris' payPalMeAddress: 'teddharris' phoneNumber: '' validated: '1']' 9: '[accountID: '2267637' login: 'tj@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/2156b54e52fcb0408c8242aa1f26d34cbb5478ff_128.jpeg' displayName: 'T.J. Ferriss' pronouns: '' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'T.J.' lastName: 'Ferriss' payPalMeAddress: '' phoneNumber: '' validated: '1']']']'
[7d28f57ea9cd0a16-MIA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d28f57ea9cd0a16-MIA%22)+AND+timestamp:[2023-06-05T13:03:26.033Z+TO+2023-06-05T15:03:26.033Z]&index=logs_expensify-022662)	virt2.rno	2023-06-05 14:03:26 033	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T13:03:26.033Z+TO+2023-06-05T15:03:26.033Z]&index=logs_expensify-022662)	 displayName: 'Jason' pronouns: '' timezone: '[automatic: '1' selected: 'America/Merida']' firstName: 'Jason' lastName: '' payPalMeAddress: 'jasefm' phoneNumber: '' validated: '1']' 5: '[accountID: '2234069' login: 'joanie@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/dbc604c97b65886c42f20e97585f08879d53c84c_128.jpeg' displayName: 'Joanie Wang' pronouns: '__predefined_sheHerHers' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'Joanie' lastName: 'Wang' payPalMeAddress: '' phoneNumber: '' validated: '1']' 6: '[accountID: '4974958' login: 'jschuster@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/272b32cadb0d0f2977f204cc042b27e3c6b797f5_128.jpeg' displayName: 'John Schuster - Online CST business hours' pronouns: '' timezone: '[automatic: '1' selected: 'America/Chicago']' firstName: 'John Schuster' lastName: '- Online CST business hours' payPalMeAddress: '' phoneNumber: '' validated: '1']' 7: '[accountID: '297463' login: 'scott@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/16076ff62541d4bbaed461b6c512a233d2c64e1d_128.jpeg' displayName: 'Scott Deeter' pronouns: '__predefined_heHimHis' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'Scott' lastName: 'Deeter' payPalMeAddress: 'deetergp' phoneNumber: '' validated: '1']' 8: '[accountID: '5356024' login: 'ted@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/5e35961c744c07fd07bb6d7bde5985c4c1874374_128.jpeg' displayName: 'Ted Harris' pronouns: '__predefined_heHimHis' timezone: '[automatic: '1' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e_128.jpeg' avatarHighResolution: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e.jpeg' displayName: 'Ted Harris - at XeroCon until Friday' firstName: 'Ted Harris' lastName: '- at XeroCon until Friday' localCurrencyCode: 'GBP' login: 'ted@expensify.com' payPalMeAddress: '' phoneNumber: '' pronouns: '__predefined_heHimHis' selected: 'Europe/London' timezone: '[automatic: 'true' selected: 'Europe/London']']' firstName: 'Ted' lastName: 'Harris' payPalMeAddress: 'teddharris' phoneNumber: '' validated: '1']' 9: '[accountID: '2267637' login: 'tj@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/2156b54e52fcb0408c8242aa1f26d34cbb5478ff_128.jpeg' displayName: 'T.J. Ferriss' pronouns: '' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'T.J.' lastName: 'Ferriss' payPalMeAddress: '' phoneNumber: '' validated: '1']']']'
[7d28f5fb8a9e0a16-MIA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d28f5fb8a9e0a16-MIA%22)+AND+timestamp:[2023-06-05T13:03:46.013Z+TO+2023-06-05T15:03:46.013Z]&index=logs_expensify-022662)	virt1.lax	2023-06-05 14:03:46 013	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T13:03:46.013Z+TO+2023-06-05T15:03:46.013Z]&index=logs_expensify-022662)	 displayName: 'Jason' pronouns: '' timezone: '[automatic: '1' selected: 'America/Merida']' firstName: 'Jason' lastName: '' payPalMeAddress: 'jasefm' phoneNumber: '' validated: '1']' 5: '[accountID: '2234069' login: 'joanie@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/dbc604c97b65886c42f20e97585f08879d53c84c_128.jpeg' displayName: 'Joanie Wang' pronouns: '__predefined_sheHerHers' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'Joanie' lastName: 'Wang' payPalMeAddress: '' phoneNumber: '' validated: '1']' 6: '[accountID: '4974958' login: 'jschuster@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/272b32cadb0d0f2977f204cc042b27e3c6b797f5_128.jpeg' displayName: 'John Schuster - Online CST business hours' pronouns: '' timezone: '[automatic: '1' selected: 'America/Chicago']' firstName: 'John Schuster' lastName: '- Online CST business hours' payPalMeAddress: '' phoneNumber: '' validated: '1']' 7: '[accountID: '5356024' login: 'ted@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/5e35961c744c07fd07bb6d7bde5985c4c1874374_128.jpeg' displayName: 'Ted Harris' pronouns: '__predefined_heHimHis' timezone: '[automatic: '1' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e_128.jpeg' avatarHighResolution: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e.jpeg' displayName: 'Ted Harris - at XeroCon until Friday' firstName: 'Ted Harris' lastName: '- at XeroCon until Friday' localCurrencyCode: 'GBP' login: 'ted@expensify.com' payPalMeAddress: '' phoneNumber: '' pronouns: '__predefined_heHimHis' selected: 'Europe/London' timezone: '[automatic: 'true' selected: 'Europe/London']']' firstName: 'Ted' lastName: 'Harris' payPalMeAddress: 'teddharris' phoneNumber: '' validated: '1']']']'
[7d28f5ff884e0a16-MIA](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d28f5ff884e0a16-MIA%22)+AND+timestamp:[2023-06-05T13:03:46.627Z+TO+2023-06-05T15:03:46.627Z]&index=logs_expensify-022662)	virt1.lax	2023-06-05 14:03:46 627	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-05T13:03:46.627Z+TO+2023-06-05T15:03:46.627Z]&index=logs_expensify-022662)	 displayName: 'Jason' pronouns: '' timezone: '[automatic: '1' selected: 'America/Merida']' firstName: 'Jason' lastName: '' payPalMeAddress: 'jasefm' phoneNumber: '' validated: '1']' 5: '[accountID: '2234069' login: 'joanie@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/dbc604c97b65886c42f20e97585f08879d53c84c_128.jpeg' displayName: 'Joanie Wang' pronouns: '__predefined_sheHerHers' timezone: '[automatic: '1' selected: 'America/Los_Angeles']' firstName: 'Joanie' lastName: 'Wang' payPalMeAddress: '' phoneNumber: '' validated: '1']' 6: '[accountID: '4974958' login: 'jschuster@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/272b32cadb0d0f2977f204cc042b27e3c6b797f5_128.jpeg' displayName: 'John Schuster - Online CST business hours' pronouns: '' timezone: '[automatic: '1' selected: 'America/Chicago']' firstName: 'John Schuster' lastName: '- Online CST business hours' payPalMeAddress: '' phoneNumber: '' validated: '1']' 7: '[accountID: '5356024' login: 'ted@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/5e35961c744c07fd07bb6d7bde5985c4c1874374_128.jpeg' displayName: 'Ted Harris' pronouns: '__predefined_heHimHis' timezone: '[automatic: '1' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e_128.jpeg' avatarHighResolution: 'https://d1wpcgnaa73g0y.cloudfront.net/8a17e3a4b100eea3b7549ca476c2c81b7e1b141e.jpeg' displayName: 'Ted Harris - at XeroCon until Friday' firstName: 'Ted Harris' lastName: '- at XeroCon until Friday' localCurrencyCode: 'GBP' login: 'ted@expensify.com' payPalMeAddress: '' phoneNumber: '' pronouns: '__predefined_heHimHis' selected: 'Europe/London' timezone: '[automatic: 'true' selected: 'Europe/London']']' firstName: 'Ted' lastName: 'Harris' payPalMeAddress: 'teddharris' phoneNumber: '' validated: '1']']']'
[aioOCR](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22aioOCR%22)+AND+timestamp:[2023-06-06T11:45:18.538Z+TO+2023-06-06T13:45:18.538Z]&index=logs_expensify-022680)	staging-www1.lax	2023-06-06 12:45:18 538	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-06T11:45:18.538Z+TO+2023-06-06T13:45:18.538Z]&index=logs_expensify-022680)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[TYjDJO](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22TYjDJO%22)+AND+timestamp:[2023-06-06T11:47:13.289Z+TO+2023-06-06T13:47:13.289Z]&index=logs_expensify-022680)	staging-www1.lax	2023-06-06 12:47:13 289	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-06T11:47:13.289Z+TO+2023-06-06T13:47:13.289Z]&index=logs_expensify-022680)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'
[0AtOxy](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%220AtOxy%22)+AND+timestamp:[2023-06-06T12:00:06.857Z+TO+2023-06-06T14:00:06.857Z]&index=logs_expensify-022680)	staging-www1.lax	2023-06-06 13:00:06 857	[florent@expensify.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22florent@expensify.com%22)+AND+timestamp:[2023-06-06T12:00:06.857Z+TO+2023-06-06T14:00:06.857Z]&index=logs_expensify-022680)	 Done building personal details onyx data ~~ personalDetails: '<REDACTED>' personalDetailsList: '[onyxMethod: 'merge' key: 'personalDetailsList' value: '[2082326: '[accountID: '2082326' login: 'florent@expensify.com' avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/19eb4b3000878b25be326c6b5c676642b8e5563c_128.jpeg' displayName: 'Florent De'Neve' pronouns: '' timezone: '[automatic: 'true' selected: 'America/Anchorage']' firstName: 'Florent' lastName: 'De'Neve' payPalMeAddress: 'Testfli' phoneNumber: '' validated: '1']']']'

**Comment by johnmlee101** [comment] 2023-06-06 14:39
Okay so it was set to anchorage at some point for real. 👀

**Comment by johnmlee101** [comment] 2023-06-06 14:40
lol @flodnv its your android app 
https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d2bae18ffe8da83-MIA%22)+AND+timestamp:[2023-06-05T20:58:58.904Z+TO+2023-06-05T22:58:58.904Z]&index=logs_expensify-022671

**Comment by flodnv** [comment] 2023-06-06 15:07
Hilarious 😂

**Comment by adelekennedy** [comment] 2023-06-19 18:16
@johnmlee101 is investigating this

**Comment by johnmlee101** [comment] 2023-06-27 20:47
No update at the moment!

**Comment by johnmlee101** [comment] 2023-07-11 22:04
This might require doing some changes on the mobile app, not sure how we should prioritize this 😓

**Comment by flodnv** [comment] 2023-07-12 12:44
Honestly since it only affects me, I would say very low priority...

**Comment by johnmlee101** [comment] 2023-07-25 21:38
Demoting to monthly because of the priority then!

**Comment by JmillsExpensify** [comment] 2023-07-26 03:11
For what it's worth, I faced a timezone issue related to Mexico not to long ago and we fixed it. I do think we should fix this one too, though monthly is fine for now.

**Comment by mallenexpensify** [comment] 2023-09-18 03:39
@johnmlee101 @eVoloshchak I'm on the #expensify-open-source this week, this is one of the oldest 10 bugs and hasn't been updated for 3 weeks, can y'all please provide an update?

**Comment by johnmlee101** [comment] 2023-09-18 03:45
This is an OldDot issue, so I would not necessarily say this is worth fixing as a priority. It only affects @flodnv because of the OldApp implementation, so I think we can dupe this in our Expensify issues to at least keep it alive

**Comment by johnmlee101** [comment] 2023-09-18 03:45
Unassigning and transferring
