### ISSUE TITLE
[PAID] [$1000] Bug: Link with multiline text loses markdown when edited

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#14060] opened 2023-01-06 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Note: Originally identified in this expensify-common [PR review comment](https://github.com/Expensify/expensify-common/pull/486#issuecomment-1373746593). The solution will be within that repository.

## Action Performed:
1. Login with any account and go to any chat room
2. Send this message:
```
[multiline
text](https://google.com/)
```
4. Edit this message

## Expected Result:
In the edit input field, the original message should be autofilled
```
[multiline
text](https://google.com/)
```

## Actual Result:
In the edit input field only the link text is shown without the original markdown
```
multiline
text
```
## Workaround:
Don't edit the message or re-write the link.

## Platforms:

All platforms

**Version Number:** v1.2.49.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/26260477/211064992-4ee041aa-d8f9-41a3-bef7-e7ac00542b3a.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673025066209189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4669fd1f66776d8</li>
        <li>Upwork Job ID: 1612959960562159616</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-01-10 23:40
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by strepanier03** [comment] 2023-01-10 23:55
I was able to reproduce this exactly as in the OG comment following the steps. 

![2023-01-10_15-52-12 (1)](https://user-images.githubusercontent.com/10925636/211686693-65b1711a-6ea1-45ec-ac95-1138714ea68d.gif)

**Comment by tienifr** [comment] 2023-01-11 00:50
Proposal

***Problem***
This is due to in the following regex for `anchor` in `node_modules/expensify-common/lib/ExpensiMark.js`, the `.*` matches any character but new line. So in the case the `<a>` tag spans 2 lines (have a new line character in between), it will not match and replace the correct markdown
```
{
                name: 'anchor',
                regex: /<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi,
                replacement: (match, g1, g2, g3, g4) => {
                    const email = g3.startsWith('mailto:') ? g3.slice(7) : '';
                    if (email === g4) {
                        return email;
                    }
                    return `[${g4}](${email || g3})`;
                },
            },
```

***Solution***
Add the `s` modifier to the regex so that it becomes
`/<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gis` (notice the added `s` at the end in `/gis`). Then it will work.

We'll be fixing it in the `expensify-common` module

**Comment by tienifr** [comment] 2023-01-11 00:53
It's working after the fix:

https://user-images.githubusercontent.com/113963320/211692845-487b92bc-df58-4612-95f0-c66553d53735.mov

**Comment by Luke9389** [comment] 2023-01-11 00:57
@tienifr's proposal looks spot on to me.
@mananjadhav if you like the proposal, react to this post with a 👍, and @tienifr, if you see that, go ahead and spin up a PR.

**Comment by tienifr** [comment] 2023-01-11 01:01
Alternatively, we can use this regex instead
```/<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi```

-> use `([\s\S]*?)` instead of `(.*?)`, I see we're using this in other regex like for 'bold', so it might be more consistent with our styles

**Comment by tienifr** [comment] 2023-01-11 01:12
Alternative solution to original proposal in https://github.com/Expensify/App/issues/14060#issuecomment-1378091074

Alternatively, we can use this regex instead
/<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>([\s\S]*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi

-> use ([\s\S]*?) instead of (.*?), I see we're using this in other regex like for 'bold', so it might be more consistent with our styles

**Comment by tienifr** [comment] 2023-01-11 01:14
Alternative solution to original proposal in https://github.com/Expensify/App/issues/14060#issuecomment-1378091074

Alternatively, we can use this regex instead
```/<(a)[^><]*href\s*=\s*(['"])(.*?)\2(?:".*?"|'.*?'|[^'"><])*>([\s\S]*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi```

-> use `([\s\S]*?)` instead of `(.*?)`, I see we're using this in other regex like for 'bold', so it might be more consistent with our styles

**Comment by mananjadhav** [comment] 2023-01-11 04:37
Yeah I think using `[\s\S]` would be better as we're already using similar pattern for HTML to markdown, bold, etc. 

@tienifr You can create the PR with [this proposal](https://github.com/Expensify/App/issues/14060#issuecomment-1378110762)

**Comment by tienifr** [comment] 2023-01-11 17:32
@mananjadhav  I just created [a sample PR](https://github.com/Expensify/expensify-common/pull/489) in the expensify-common module. Please help to check and is it reasonable for me to use the PR template in the App repository to expensify-common repository

**Comment by mananjadhav** [comment] 2023-01-11 17:48
That should enough for the expensify-common package, though I'll recommend checking previous PRs.

We'll need another PR with the merged SHA commit and here we'll fill the whole checklist with platform screenshots.

Quick question though I thought we're going to implement the `\s\S` regex instead of appending `gis`  ?

**Comment by mananjadhav** [comment] 2023-01-12 14:17
@tienifr the expensify-common PR is merged. Can you create a PR for the App.

**Comment by tienifr** [comment] 2023-01-13 06:16
Hi @mananjadhav Can you help to review [the PR](https://github.com/Expensify/App/pull/14244)?

**Comment by mananjadhav** [comment] 2023-01-13 06:19
Thanks for the bump. I missed the notification for the PR. I'll review this in 1-2 hours.

**Comment by tienifr** [comment] 2023-01-16 02:32
@strepanier03 I've applied to the Upwork job, thanks

**Comment by mananjadhav** [comment] 2023-01-16 04:27
@strepanier03 I've applied too for C+ review. Thanks.

**Comment by strepanier03** [comment] 2023-01-18 00:47
Latest update: 🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3933822236) to staging by @Luke9389 in version: 1.2.55-0 🚀

**Comment by strepanier03** [comment] 2023-01-18 00:49
@mananjadhav - Accepted proposal and sent offer.

@tienifr - Accepted proposal and sent offer.

**Comment by strepanier03** [comment] 2023-01-19 01:45
Thanks for raising @aimane-chnaif.

@neil-marcellini - Just confirming this GH was made due to the report by @aimane-chnaif - The timing is within a 15 minutes so I wanted to confirm before adding them as the reporter because I also see their report received the Dupe reaction as well.

**Comment by neil-marcellini** [comment] 2023-01-19 17:16
@strepanier03 Yes @aimane-chnaif found the bug while reviewing my PR, as he pointed out. I had him post in Slack to follow our process and then I created the issue. I don't know why @kavimuru gave it a dupe reaction. I did a search and I don't think it's a duplicate so lets pay him.

**Comment by strepanier03** [comment] 2023-01-19 21:30
Awesome, thanks for confirming @neil-marcellini I appreciate it.

**Comment by strepanier03** [comment] 2023-01-20 22:48
Raised TR suggestion for buddycheck [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1674254859592739) - Awaiting feedback.

**Comment by strepanier03** [comment] 2023-01-20 22:52
@aimane-chnaif - Please apply for the reporting job [here](https://www.upwork.com/jobs/~01e356fdb4dfa9c076) and I'll accept and send the offer once you do. Cheers!

**Comment by strepanier03** [comment] 2023-01-23 17:50
@aimane-chnaif - Oh no I'm sorry about that! I just make it public and will keep an eye out for your application.

**Comment by strepanier03** [comment] 2023-01-24 22:51
Hmm, maybe the link doesn't automatically update. Here is a fresh one, can you give it a try? https://www.upwork.com/jobs/~01e356fdb4dfa9c076

**Comment by mananjadhav** [comment] 2023-01-25 22:59
@strepanier03 This is ready for payout with bonus applicable. Can you please help with the same?

**Comment by strepanier03** [comment] 2023-01-26 00:13
@aimane-chnaif That is the link I freshly copied from the job, which is what I meant. I will try to invite you manually. 

@mananjadhav Yup, today is the first day payment is possible so I will take care of it.

**Comment by strepanier03** [comment] 2023-01-26 00:17
@aimane-chnaif - Just sent you the invite.

**Comment by strepanier03** [comment] 2023-01-26 00:24
@mananjadhav and @tienifr - Both of you have been paid in Upwork.

**Comment by mananjadhav** [comment] 2023-01-26 00:32
Thanks @strepanier03. Appreciate the prompt action on this.

**Comment by strepanier03** [comment] 2023-01-26 19:04
@aimane-chnaif - I hired you for the job and the offer is waiting for your action. Please let me know here once you accept the offer and I'll pay it out.

**Comment by strepanier03** [comment] 2023-01-26 19:31
Paid out Aimane as well. 

Only step is to have the new RG added and once it is I'll close this GH as completed. 

----

Thank you @aimane-chnaif, @mananjadhav, @tienifr, and @Luke9389 for the communication and urgency fixing this, well done team!

**Comment by strepanier03** [comment] 2023-01-30 18:18
Following the TR addition [here](https://github.com/Expensify/Expensify/issues/258902), once it's added I'll close this GH.

**Comment by strepanier03** [comment] 2023-01-31 22:15
@aimane-chnaif - The job is closed already. 

<img width="458" alt="2023-01-31_14-14-24" src="https://user-images.githubusercontent.com/10925636/215895925-aa2af8e8-70ad-4ea8-9936-eaf6673092ca.png">

**Comment by strepanier03** [comment] 2023-02-02 22:48
This will stay open until the reg test is done.

**Comment by strepanier03** [comment] 2023-02-03 23:54
Bumped the reg test request.

**Comment by Luke9389** [comment] 2023-02-07 00:27
Waiting for reg test on [this issue](https://github.com/Expensify/Expensify/issues/258902). I notice that one is monthly, should we change the urgency of this one to match so that it's not going Overdue every day?

**Comment by strepanier03** [comment] 2023-02-07 15:59
I am going to change it to weekly so that I'm still checking in on it but we don't have to worry about daily updates for the sake of updates.

**Closed** 2023-02-07 17:16 UTC
Labels: External, Weekly, Bug
