### ISSUE TITLE
[Awaiting Payment August 17th] dev: Selecting image from file explorer doesn't open image previewer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24183] opened 2023-08-06 00:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Click on '+' icon
3. Click on 'Add attachment'
4. Select a picture
## Expected Result: 
Attachment preview should open
## Actual Result: 
File Explorer opened again
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1afd5054-5f42-4442-9192-6c5a21f13c05

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691178392967439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-08-07 11:01
Looks like @allroundexperts has a PR in review for this. Presuming it's a regression, I don't need to assign you to this issue. @aimane-chnaif though for the review, right?

**Comment by trjExpensify** [comment] 2023-08-14 10:21
Updated the title to reflect the payment date.

**Comment by trjExpensify** [comment] 2023-08-17 10:32
Okay, so confirming payments: 

- @Natnael-Guchima $250 for the bug report
- @aimane-chnaif $1,000 for the C+ review

Is that correct, @aimane-chnaif?

**Comment by trjExpensify** [comment] 2023-08-17 13:57
Looool. The party boat 😂 

We're all settled up here. Closing!

**Closed by trjExpensify** 2023-08-17 13:57 UTC
Labels: Reviewing, Engineering, Weekly, Bug
