### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Distance - Distance still shows Pending when preview and report header already show distance

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43569] opened 2024-06-12 13:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4620914
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a distance expense
4. Go to expense report while the receipt is being generated
5. Note that the distance is already computed in the expense preview
6. Go to transaction thread while the receipt is being generated
7. Note that the distance in transaction thread header is also computed
8. Note that the Distance row still shows "Pending" while it is computed in Step 6 and 7

## Expected Result:
The Distance row in transaction thread should display the distance when the distance is computed

## Actual Result:
The Distance row in transaction thread displays "Pending" when the expense preview and transaction thread header already display the distance

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/29318e87-4d14-4030-88ef-b34f03bc3f4c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01531942e35c6e84c9</li>
        <li>Upwork Job ID: 1801172514335645153</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment] 2024-06-12 13:44
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-12 13:44
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-12 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance value shows Pending... even though the distance is shown/calculated in the confirmation list and in the preview.

### What is the root cause of that problem?
If there is a pending action of waypoints, it will show Pending...
https://github.com/Expensify/App/blob/8563b9f77f21ded0dce09572ab6e1983c3f1fabd/src/components/ReportActionItem/MoneyRequestView.tsx#L283

When we create a new request, an ADD pending action is set, that's why the Pending... is shown.
https://github.com/Expensify/App/blob/8563b9f77f21ded0dce09572ab6e1983c3f1fabd/src/libs/actions/IOU.ts#L1963

It's to address this [comment](https://github.com/Expensify/App/pull/40711#issuecomment-2072082639) where the distance value still shows the old value after update, so Pending... is shown while waiting for the updated distance value.

### What changes do you think we should make in order to solve the problem?

In `main`, when we change the waypoints, the distance value is already updated from GetRoute request, so I don't think we need to show Pending... anymore by always showing the `distanceToDisplay` here.
https://github.com/Expensify/App/blob/8563b9f77f21ded0dce09572ab6e1983c3f1fabd/src/components/ReportActionItem/MoneyRequestView.tsx#L283
```
title={distanceToDisplay}
```

(or update the condition to specifically check for update pending action)

However, I see another issue. The distance shown is in meters even though the unit is in miles. 

https://github.com/Expensify/App/assets/50919443/a95ee41b-f76a-4568-9c63-afc54c0e2401

It's because, GetRoute API returns the distance in meters, but we try to convert it from miles to meters here,
https://github.com/Expensify/App/blob/8563b9f77f21ded0dce09572ab6e1983c3f1fabd/src/components/ReportActionItem/MoneyRequestView.tsx#L190

The reason we try to convert it from miles to meters is because after the transaction is created (RequestMoney)/waypoints is updated (UpdateMoneyRequestDistance), the distance value is in miles instead of meters which is different from GetRoute response. I think this needs to be discussed first how to fix it. Maybe we can update GetRoute to returns the distance value based on the workspace unit (miles/km).

**Comment by trjExpensify** [comment] 2024-06-13 08:39
Hm, I think this was a vip-vsb initiative originally. @paultsimura and @neil-marcellini I recall have the subject matter knowledge on this one.

**Comment by bernhardoj** [comment] 2024-06-17 14:52
> Other than this, @bernhardoj Did you check for the offline behaviour?

If we apply my suggestion and do the steps while offline, then we will see the distance as
```
{distanceInMeters} miles ❌ 
```

**Comment by madmax330** [comment] 2024-06-20 12:18
Hmm I'm not sure what the best way forward is here.

cc @neil-marcellini since you worked quite a bit on distance requests IIRC can you take a look?

**Comment by trjExpensify** [comment] 2024-06-26 19:24
I've asked Neil if he can take a look here.

**Comment by neil-marcellini** [comment] 2024-06-26 23:35
Thanks for the DM Tom! Wow, this is kind of a headache. Thanks for figuring out what's going in [your proposal](https://github.com/Expensify/App/issues/43569#issuecomment-2163457710) @bernhardoj!

I agree that we should show the distance optimistically for the request since it was already fetched with GetRoute. Regarding the distance being in meters instead of the proper unit, it's not currently a problem since we show Pending... instead. 

However, I probably made a mistake with updating the GetRoute api command to return distance and set in in Onyx under `transaction.comment.customUnit.quantity`. I didn't realize/remember that the distance is stored at that path in the user selected unit upon creation. It's a bad idea to have different units stored under the same path, even if we could determine the unit based on whether it's optimistic or not. Too messy.

We can't really convert into the proper unit for the GetRoute response because we don't know what policy the expense will be linked to yet. Therefore I think we'll probably have to go back to only getting the distance from `transaction.routes.route0.distance`. Luckily that data is still present in the response. I'll create a low priority cleanup issue to stop returning it under the customUnit eventually.

@bernhardoj would you please update your proposal to make the app always get the distance from that path for optimistic distance requests? Once the request is created the distance can come from customUnit.quantity. It would be nice to have some util functions for this with nice names to make it clear how it works, or maybe just modify TransactionUtils.getDistance to handle that logic. Whatever you feel is more reasonable.

@madmax330 I'm going to take this over, but let me know if you would rather handle it.

**Comment by bernhardoj** [comment] 2024-06-27 15:53
> We can't really convert into the proper unit for the GetRoute

GetRoute API is called when editing the distance, so maybe it's possible, idk though.

> would you please update your proposal to make the app always get the distance from that path for optimistic distance requests? Once the request is created the distance can come from customUnit.quantity

Ok, so if I understand correctly, I would do it like this:
```
const draftDistance = TransactionUtils.getDraftDistance(transaction);
const distance = draftDistance ?? DistanceRequestUtils.convertToDistanceInMeters(TransactionUtils.getDistance(transaction), unit);
```

`getDraftDistance` gets the distance from `transaction.routes.route0.distance`. `getDistance` stays the same.

But I see that after the distance request is created, `transaction.routes.route0.distance` is still exists, so we will never use the `transaction.comment.customUnit.quantity`. So, can we just use `transaction.routes.route0.distance` all the time instead?

**Comment by neil-marcellini** [comment] 2024-07-03 19:37
> Ok, so if I understand correctly, I would do it like this:
> 
> ```
> (in MoneyRequestView)
> const draftDistance = TransactionUtils.getDraftDistance(transaction);
> const distance = draftDistance ?? DistanceRequestUtils.convertToDistanceInMeters(TransactionUtils.getDistance(transaction), unit);
> ```
> 
> `getDraftDistance` gets the distance from `transaction.routes.route0.distance`. `getDistance` stays the same.
> 
> But I see that after the distance request is created, `transaction.routes.route0.distance` is still exists, so we will never use the `transaction.comment.customUnit.quantity`. So, can we just use `transaction.routes.route0.distance` all the time instead?

@bernhardoj thanks for the update. I'm thinking of something a bit different. You're right that `transaction.routes.route0.distance` doesn't get cleared. We can't use it all the time though, because it's not saved on the backend, so it will be cleared upon sign out. As a first step, let's merge `routes: null` on the transaction in the success data for createDistanceRequest and trackExpense for distance.

Next, let's try to make it really clear with the names of the functions/the JSDoc comments, what each value represents.

- `getDraftDistanceInMeters(transaction)` will get it from the route as you described
- `getDistanceInSavedUnit(transaction)` will get it from the customUnit.quantity
- `getDistance(transaction, unit)` will try to get it from the draft, then convert it into the provided unit. If that's not available it will get it in the saved unit.
- `getDistanceInMeters(transaction, unit)` will work like getDistance, but return the draft directly or convert the saved unit into meters.

Maybe we should only export the bottom two functions. What do you think about this? Please let me know if you spot any problems or have ideas how it could be more simple.

**Comment by bernhardoj** [comment] 2024-07-04 11:36
> We can't use it all the time though, because it's not saved on the backend, so it will be cleared upon sign out. As a first step, let's merge routes: null on the transaction in the success data for createDistanceRequest and trackExpense for distance.

I see. But if we merge `routes: null`, the coordinate is cleared too which caused the same issue as https://github.com/Expensify/App/issues/44156. 

https://github.com/Expensify/App/assets/50919443/37a4cb36-1b17-4eb5-80a4-608a27c79784

I think we can solve that first.

> Maybe we should only export the bottom two functions. What do you think about this? Please let me know if you spot any problems or have ideas how it could be more simple.

Looking through the current `getDistance` usages, all of them expect the distance in meters, so I think we only need `getDistanceInMeters`. Do you agree? And just to make sure I understand the description of `getDistanceInMeters`, does the pseudo-code below correct? (tested it and works fine so far)

```
fn getDistanceInMeters(transaction, unit):
    if route.distance:
        return route.distance
    if customUnit.quantity and unit:
        return toMeters(customUnit.quantity, unit)
    return 0 // fallback
```

**Comment by neil-marcellini** [comment] 2024-07-09 01:22
@bernhardoj great thanks that sounds like a good plan. I think on the money request view page we might want to get the distance in the save unit (mi or km), but most other places we want it in meters.

I will review your proposal on the other issue. Maybe we can branch off the PR for that issue when fixing this one, or just put it on HOLD.

Please update your original proposal so we can official review it and get you assigned.

**Comment by bernhardoj** [comment] 2024-07-09 10:32
> I think on the money request view page we might want to get the distance in the saved unit (mi or km)

MoneyRequestView actually expect it in meters too.

https://github.com/Expensify/App/blob/7c378869be503923539d096088fb8883fc2ccef3/src/components/ReportActionItem/MoneyRequestView.tsx#L210-L212

It gets the distance then convert it to meters which is passed to `DistanceRequestUtils.getDistanceForDisplay`. With the fix, instead of 
`DistanceRequestUtils.convertToDistanceInMeters(TransactionUtils.getDistance(transaction), unit)`, 
we just call 
`TransactionUtils.getDistanceInMeters(transaction, unit)`.

> Please update your original proposal so we can official review it and get you assigned.

Updated my [proposal](https://github.com/Expensify/App/issues/43569#issuecomment-2163457710)

**Comment by trjExpensify** [comment] 2024-07-11 15:08
Yes please, thanks!

**Comment by trjExpensify** [comment] 2024-07-12 15:00
How'd you get on with the review, @parasharrajat?

**Comment by trjExpensify** [comment] 2024-07-19 01:10
@neil-marcellini can you do the secondary review of the proposal so we can move this to a PR? Thanks!

**Comment by trjExpensify** [comment] 2024-07-22 21:01
Neil is back tomorrow to check out this proposal.

**Comment by neil-marcellini** [comment] 2024-07-23 19:39
I like @bernhardoj's [proposal](https://github.com/Expensify/App/issues/43569#issuecomment-2163457710) too, hiring.

**Comment by bernhardoj** [comment] 2024-07-24 17:45
I'll open the PR tomorrow.

**Comment by bernhardoj** [comment] 2024-07-25 06:31
PR is ready

cc: @parasharrajat

**Comment by trjExpensify** [comment] 2024-08-15 14:02
Checklist time!

**Comment by trjExpensify** [comment] 2024-08-15 17:15
Thanks! @neil-marcellini will regression tests for the P2P Distance project be added centrally when the project is wrapped?

**Comment by trjExpensify** [comment] 2024-08-15 17:16
Payment summary as follows: 

- $250 to @parasharrajat for the C+ review
- $250 to @bernhardoj for the fix

Feel free to go ahead and submit on ND!

**Comment by bernhardoj** [comment] 2024-08-15 21:49
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-21 11:00
$250 approved for @bernhardoj

**Comment by trjExpensify** [comment] 2024-08-23 09:08
I'm back, reached out to @neil-marcellini [on this](https://github.com/Expensify/App/issues/43569#issuecomment-2291754882) Q before closing this out.

**Comment by neil-marcellini** [comment] 2024-08-23 18:29
> Thanks! @neil-marcellini will regression tests for the P2P Distance project be added centrally when the project is wrapped?

Yes

**Comment by trjExpensify** [comment] 2024-08-23 18:47
Great, closing!

**Closed by trjExpensify** 2024-08-23 18:47 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-09-02 11:54
$250 approved for @parasharrajat
