### ISSUE TITLE
[$250] IPAD:  login screen  not organized - Reported by @ahmdshrif

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10353] opened 2022-08-11 18:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Open app ( iPad  portrait)

## Expected Result:
The login screen should be more organized  ( remove the image or keep  and make the login from bigger)

## Actual Result:
The screen looks like you have a small emulate inside the screen  

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS (IPad) 

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![simulator_screenshot_81A37B09-1232-49E1-A78C-0424BB94D998](https://user-images.githubusercontent.com/43995119/184210344-272ae7b7-a224-4c28-84b9-d0b715819d9b.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658376149413639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2022-08-11 22:11
Sending on, I do not have an iPad so I could not recreate though.

**Comment by neil-marcellini** [comment] 2022-08-11 23:48
Yes, I can confirm that this is ugly when running on the ipad. This would be a great external issue. The key will be to not break the layouts for any of the other platforms.
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2022-08-11 at 16 45 45](https://user-images.githubusercontent.com/26260477/184260523-e4df76fb-fb34-4dc9-bff8-612d8ae13400.png)

**Comment by MitchExpensify** [comment] 2022-08-12 22:19
[Upwork Job](https://www.upwork.com/jobs/~01c88aa69418a49ca3)

**Comment by muhammadazhariqbal** [comment] 2022-08-13 07:49
if this screen layout is not organized then we can use react-native-responsive-screen or native base library for solving this issue and make the layout of the app organized.

**Comment by ahmdshrif** [comment] 2022-08-13 09:54
my proposal.
is to  add `minHight` to be `screen.height` . to top part. 
the simple way to fix it

**Comment by ahmdshrif** [comment] 2022-08-13 22:01
# Proposal 

this line is the root cause. 

https://github.com/Expensify/App/blob/f420889213d69c3bb3e9523a1ff3bda3c50cfc49/src/pages/signin/SignInPageLayout/index.js#L65-L74

the solution is to remove them and 
this will make the  MediumScreen render with the same screen for the large screen. 

https://github.com/Expensify/App/blob/f420889213d69c3bb3e9523a1ff3bda3c50cfc49/src/pages/signin/SignInPageLayout/index.js#L76-L82
|  before  | after  |   
|---|---|
| ![Screen Shot 2022-08-13 at 11 53 52 PM](https://user-images.githubusercontent.com/21364901/184511970-af79e2ca-1ec1-4cf5-bfae-410b970a5461.png)  |  ![Screen Shot 2022-08-13 at 11 54 19 PM](https://user-images.githubusercontent.com/21364901/184511979-0b5234b1-3b66-43de-8fab-f54efc1a08f9.png)
 |   




there is another proposal is to delete  the image on the middle screen and on this case will need to do this change  also 

```diff
+ if (props.isSmallScreenWidth || props.isMediumScreenWidth) {
- if (props.isSmallScreenWidth) {
        return content;
    }
```

and this is the result of this proposal. 
|  before  | after  |   
|---|---|
| ![Screen Shot 2022-08-13 at 11 53 52 PM](https://user-images.githubusercontent.com/21364901/184511970-af79e2ca-1ec1-4cf5-bfae-410b970a5461.png)  | ![Screen Shot 2022-08-13 at 11 59 15 PM](https://user-images.githubusercontent.com/21364901/184512063-42a1c2b5-22cc-40b2-a4e9-03505e77ce4a.png)
 |

**Comment by ahmdshrif** [comment] 2022-08-14 10:57
Since I report this issue  my expectation was  to be one of the proposal result ... for me i vote for the first proposal.

**Comment by thesahindia** [comment] 2022-08-16 15:25
It is expected. The mockup was created by @megankelso. Here's the [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1646238505268409?thread_ts=1645823447.597149&cid=C01GTK53T8Q).

If we are changing it then the proposals should also be fixing https://github.com/Expensify/App/issues/8122 because the design change was made to fix that.

**Comment by stitesExpensify** [comment] 2022-08-16 15:37
bump @MitchExpensify

**Comment by Santhosh-Sellavel** [comment] 2022-08-16 17:12
Actually this is working as expected i.e its outcome of #8122.

If we are considering to change then we should check with @Expensify/design team first, thanks!

**Comment by shawnborton** [comment] 2022-08-16 17:58
This is not a bug. Can you please check with the design team in the Slack conversation first before creating a bug? I'm going to close this out for now.

**Closed by shawnborton** 2022-08-16 17:58 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Help Wanted

**Comment by shawnborton** [comment] 2022-08-16 17:59
Saying "make it more organized" is super vague so it doesn't give us a concrete path forward on how to fix something. All of this should be discussed and mocked up in Slack first before heading to a GH issue.

**Comment by MitchExpensify** [comment] 2022-08-16 18:03
Upwork job removed

**Comment by ahmdshrif** [comment] 2022-08-20 19:06
> Saying "make it more organized" is super vague so it doesn't give us a concrete path forward on how to fix something. 

I just think the image on the button is not something we expect. because that wasn't the behavior before. 

but anyway I think the iPad login form is still small than what you provided in the confirmed design. it's lookalike you use small mobile emulate inside the screen. 
what do you think ? @shawnborton 

 design from 8122 issue 

<img width="834" alt="158105168-bb527f56-5216-4f62-ac94-ebb5ce23ddfd" src="https://user-images.githubusercontent.com/21364901/185762609-a3857f07-14a1-4533-959e-5356f17e1ee1.png">

 
 and the current design of iPad : 
 
![184210344-272ae7b7-a224-4c28-84b9-d0b715819d9b](https://user-images.githubusercontent.com/21364901/185762562-324b3a95-69a7-4a3e-8dd7-50879df48d90.png)

**Comment by shawnborton** [comment] 2022-08-22 16:22
I don't think it's worth "fixing" this one, for a couple reasons:
- I don't think anything is actually broken
- We likely have low iPad usage at the moment
- Hopefully we'll have some new login page designs coming soonish
