### ISSUE TITLE
[$500][MEDIUM] Bank account - Fields are empty after navigating back to add BA modal

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36450] opened 2024-02-14 00:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace.

1. Go to Workspace > Bank account.
2. Select "Connect manually".
3. Enter the routing number and account number.
4. Tap on the back arrow.
5. Navigate back to the Add bank account modal > Manual option.
## Expected Result:
The data entered before should remain on the fields.

## Actual Result:
The fields are empty.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/1d235b1c-f693-4800-a701-b291a1952858

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f94e09a4ab6f001</li>
        <li>Upwork Job ID: 1757555443937619968</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-14 00:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are clearing the first screens bank info on initial load

### What is the root cause of that problem?
We starting doing this since: https://github.com/Expensify/App/pull/31121/commits/bf43cc444c161db9baa3fe321ffc5b10be606cc9
The code specifically instructs to clear the bank page screen on initial load.
because of: https://github.com/Expensify/App/pull/31121#issuecomment-1812313422

They wanted it to reset to prevent this scenario and being stuck. 

### What changes do you think we should make in order to solve the problem?
I think we should remove the removeExistingBankAccountDetails logic.
After reviewing the issue, it seems like an edge case that the user is able to recover from. 

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-14 00:54
We can handle that edge case in a seperate ticket if desired, to reset if the user is in that step and the information is not passing validation.

**Comment by mountiny** [comment] 2024-02-14 01:08
Thanks I agree this is an edge case for now.

**Comment by akinwale** [comment] 2024-02-14 05:50
@jeremy-croff Your proposed solution does not fix the core issue here which is that the data is not being saved after manually entering text in the input fields.

**Comment by jeremy-croff** [comment] 2024-02-14 06:45
> @jeremy-croff Your proposed solution does not fix the core issue here which is that the data is not being saved after manually entering text in the input fields.

@akinwale  
I believe it does.
You can confirm that we are correctly persisting the user entered information in the reimbursementAccountDraft keyspace of the onyx store.
When we explicitly call that method I mentioned, it wipes it. Which it will do on load of the the  first step.

I commented it out, and you will see we start retaining the draft now:


https://github.com/Expensify/App/assets/157416545/67854fcd-789f-44d4-954f-877dbeeb88eb

**Comment by jeremy-croff** [comment] 2024-02-14 06:47
I see how my fix addresses closing the modal, but not the exact flow of OP!. Checking :)

**Comment by jeremy-croff** [comment] 2024-02-14 06:58
OP is related to https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/pages/ReimbursementAccount/BankInfo/BankInfo.tsx#L117, also specifically coded for thinking we want to clean the input on back step.

**Comment by jeremy-croff** [comment] 2024-02-14 07:04
Rechecked, and confirmed that in conjuction with the previous line - we also have to remove https://github.com/Expensify/App/blob/023d62cba900f4333f73c52eb735402a994cbc4b/src/pages/ReimbursementAccount/BankInfo/BankInfo.tsx#L117 line for OP

**Comment by MrMuzyk** [comment] 2024-02-14 10:19
I believe this is intended behaviour.

@nkuoch Can you confirm that?

**Comment by mountiny** [comment] 2024-02-14 13:58
Checked again and I agree, we saving these values only once submitted so this would be a feature request more than a bug now

**Closed by mountiny** 2024-02-14 13:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
