### ISSUE TITLE
[$500] Login - "the email entered is invalid" error when start typing email address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34298] opened 2024-01-10 21:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Slack conversation:**

## Action Performed:
1. Open New Dot app
2. Tap on email field
3. Tap outside email field to trigger the error message "Please enter an email"
4. Start typing email address

## Expected Result:
There should be no error message when user start typing email address

## Actual Result:
"The email entered is invalid" error message appear when user start typing e-mail address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/409a07c7-1f9a-4ec2-9454-d80232c21db1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2b5a86ed68c3897</li>
        <li>Upwork Job ID: 1745199019459543040</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by aim-salam** [comment] 2024-01-10 22:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Login - "the email entered is invalid" error when start typing email address

### What is the root cause of that problem?

When `onTextInput` triggered, `firstBlurred.current` and `setFormError` keep value `false`

https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/pages/signin/LoginForm/BaseLoginForm.js#L142

### What changes do you think we should make in order to solve the problem?

```diff
    const onTextInput = useCallback(
        (text) => {

+            setFormError(false);
+           firstBlurred.current = false;
```

setFormError(null);

### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2024-01-10 22:08
@neonbhai it is a great solution, but when I tested with `continue` the error still remain.

**Comment by strepanier03** [comment] 2024-01-10 23:11
I feel like this should be closed as the behavior makes sense to me. I raised for a discussion in Slack hehttps://expensify.slack.com/archives/C01SKUP7QR0/p1704928206056239re, and will update this GH when I have a consensus.

**Comment by aim-salam** [comment] 2024-01-10 23:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Login - "the email entered is invalid" error when start typing email address

### What is the root cause of that problem?

When `onTextInput` triggered, 
1. `firstBlurred.current` will trigger `validate()`
2. `formError` keep value `true` for first error.

https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/pages/signin/LoginForm/BaseLoginForm.js#L142-L159

### What changes do you think we should make in order to solve the problem?

1. Prevent `validate()` to be trigger when `onTextInput`
2. When `onTextInput` triggered, set`setFormError` into `false`

```diff
 const onTextInput = useCallback( 
     (text) => { 
+.     setFormError(false);
         setLogin(text); 
-         if (firstBlurred.current) { 
-             validate(text); 
-        } 
```



https://github.com/Expensify/App/assets/142758714/f990895f-f8e8-4673-9935-6c2ab14c82d5





### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment] 2024-01-12 22:06
After [discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1704928206056239) in Slack, we've decided not to do anything or change this. Closing out.

**Closed by strepanier03** 2024-01-12 22:06 UTC
Labels: External, Daily, Help Wanted, Bug
