### ISSUE TITLE
[HOLD for payment 2024-05-06] [$250] Quick action - Group chat name and avatar does not update unless the page is refreshed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40536] opened 2024-04-19 09:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-5
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Create a group chat.
4. Split expense in the group chat.
5. Click on the chat header.
6. Go to Settings > Name.
7. Change the group chat name.
8. Also change the group chat avatar.
9. Click FAB.
10. Hover over the group chat avatar.

## Expected Result:
The group chat under Quick action in FAB will update to show the latest avatar and name.

## Actual Result:
The group chat under Quick action in FAB does not show the latest avatar and name (in the tooltip) unless the page is refreshed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3ef5c5f9-c27c-488d-ba1c-43d2296f7de2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158c8e7015a29644e</li>
        <li>Upwork Job ID: 1783268294358458368</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-19 09:30
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-19 09:30
We think this issue might be related to the #collect project.

**Comment by isabelastisser** [comment] 2024-04-19 16:51
@madmax330, can you please provide an update? Thanks!

**Comment by marcaaron** [comment] 2024-04-19 20:23
We can remove the blocker here. This issue is very minor and also related to a new feature not a regression.

**Comment by marcaaron** [comment] 2024-04-19 20:24
@madmax330 if you want to pass this to me I can takeover as it seems related to Group Chats.

**Comment by bernhardoj** [comment] 2024-04-21 09:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The group chat name (in the tooltip) and avatar in QAB don't update dynamically and need to refresh the app.

### What is the root cause of that problem?
The avatar and group name (in the tooltip) depend on the quick action report data.
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L154-L162

For the quick action report, we get the report ID from `quickAction` and use `ReportUtils.getReport`.
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L150

The useMemo only depends on `quickAction`, so when we do an update to the group report, the value won't change.

The reason the group chat name is updated below the quick action title is, when the FAB component re-renders, it will recalculate the `ReportUtils.getReportName` by passing the outdated `quickActionReport`
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L375

Even though the report passed to `getReportName` is outdated, the way we get the group chat name is by using the group chat report ID, 
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/libs/ReportUtils.ts#L2988-L2990

and then get the report object from the `allReports` variable as shown below that is coming from Onyx.connect inside the lib file.
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/libs/ReportUtils.ts#L1751-L1759

### What changes do you think we should make in order to solve the problem?

It's better to subscribe to the `quickActionReport` using `withOnyx`.
```
quickActionReport: {
    key: ({quickAction}) => `${ONYXKEYS.COLLECTION.REPORT}${quickAction?.chatReportID}`,
},
```

Then we don't need this anymore,

**Comment by isabelastisser** [comment] 2024-04-24 18:06
@madmax330 @marcaaron, can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment] 2024-04-24 18:27
Not overdue.

**Comment by marcaaron** [comment] 2024-04-24 22:54
Ah, we need to add the `External` label. A C+ will be assigned to review the proposals. I will do that now.

**Comment by bernhardoj** [comment] 2024-04-26 03:24
PR is ready

cc: @shubham1206agra

**Comment by isabelastisser** [comment] 2024-05-08 21:13
The payments were processed in Upwork.

@shubham1206agra, please complete the BZ list above before I can close the issue. Thanks!

**Comment by isabelastisser** [comment] 2024-05-14 20:41
Confirming that the payments were processed in Upwork on May 8:

<img width="325" alt="image" src="https://github.com/Expensify/App/assets/31258516/cbbcfc25-73bc-4f88-b337-842d30ccddee">

<img width="488" alt="image" src="https://github.com/Expensify/App/assets/31258516/1e5ab6e6-d8d8-49d0-bd34-29337ccc059f">

**Closed by isabelastisser** 2024-05-14 20:41 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
