### ISSUE TITLE
[$250] Web - Notification - User receives push notification when public room notification are daily

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47261] opened 2024-08-12 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4845236&group_by=cases:section_id&group_order=asc&group_id=295000
**Email or phone of affected tester (no customers):** gocemate+a917@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. User A creates Public room
2. User A invite User B to the public room
3. User A sends message to public room

## Expected Result:
User B should not receive notification since public room notifications are set to Daily by default

## Actual Result:
User receives push notification for new message when public room notification are set to daily by default
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c2a84121-a5ee-4f37-980c-cd79e2848f91

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01960943628ae9eb04</li>
        <li>Upwork Job ID: 1824172135055474776</li>
        <li>Last Price Increase: 2024-08-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by IuliiaHerets** [comment] 2024-08-12 20:00
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-12 20:01
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-08-15 19:51
Context on the status of the vip-vsb project.

https://expensify.slack.com/archives/C066HJM2CAZ/p1721760866963099?thread_ts=1721729395.916419&cid=C066HJM2CAZ

**Comment by Amoralchik** [comment] 2024-08-16 02:05
Can't reproduce on v9.0.21-0

**Comment by ikevin127** [comment] 2024-08-16 22:37
Not able to reproduce with the public room scenario on latest **staging v9.0.21-1.**

##

However, I was able to reproduce the same issue for the **WS chat** where if notification notice is changed to **Daily**, I still get notifications as if it's set to **Immediately**.

> [!tip]
> ## **Steps**
>1. User A creates a new workspace.
>2. User A invites User B to their (User A) WS chat.
>3. User A set their WS chat **Settings > Notify me about new messages** to **Daily**.
>3. User A sends message to their WS chat.

https://github.com/user-attachments/assets/3d1c4e22-a68e-4ca8-9e34-7def38d22d75

**Note:** The notification goes away as soon as I start the MacOS screen recorder and the notifications received while the screen recording is ongoing don't show up (this is MacOS / screen recorder related) -> issue should be tested / reproduced without screen recording on.

**Comment by Amoralchik** [comment] 2024-08-16 23:43
@ikevin127 Could you please record the entire process? I just tried to replicate it as you described, and it seems you’re receiving the notification because User B still has their "Notify me about new messages" setting on "Immediately."

**Comment by ikevin127** [comment] 2024-08-17 00:02
@Amoralchik You're correct, my bad. The issue is not reproducible, I updated my previous [comment](https://github.com/Expensify/App/issues/47261#issuecomment-2294406899) to remove the other found issue.

##

@isabelastisser Issue not reproducible!

**Comment by isabelastisser** [comment] 2024-08-19 15:37
@ikevin127, thanks for the update! Closing.

**Closed by isabelastisser** 2024-08-19 15:37 UTC
Labels: External, Daily, Help Wanted, Bug
