### ISSUE TITLE
[VIP-VSB][$500] Chat - Edit mode reopens after sending a message, press Up key and Enter key without delay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31242] opened 2023-11-12 02:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any chat
3. Send a message
4. Press Up key to edit > Press Enter without delay

## Expected Result:
expected result is the message being updated and the edit mode not opening again

## Actual Result:
The exit mode reopens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3840387d-2a3e-4852-8b46-3c8167a05110

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb41054c4531b21c</li>
        <li>Upwork Job ID: 1723521696324161536</li>
        <li>Last Price Increase: 2023-11-12</li>
    </ul>
</details>

**Comment by Falcowoski** [comment] 2023-11-12 06:54
I can only reproduce the issue after dozens of attempts. Is this to be expected? From the attached video, it seemed to be a more common occurrence.

**Comment by Falcowoski** [comment] 2023-11-12 06:56
Contributor details
Your Expensify account email: leonardo.falcoski@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0188a784bf7e6e55b1

**Comment by favourch** [comment] 2023-11-12 07:02
Hi Team,

I've conducted tests to replicate the issue based on the steps provided:

1. Navigated to staging.new.expensify.com.
2. Opened a chat conversation.
3. Sent a message.
4. Pressed the Up key to enter edit mode and then pressed Enter immediately.

In my tests, I found that the edit mode exits as expected upon pressing Enter without delay. My testing was conducted on the MacOS: Chrome browser.

Please let me know if there are additional steps or conditions I should consider.

**Comment by favourch** [comment] 2023-11-12 07:06
Contributor details
Your Expensify account email: [fchukwuedo@gmail.com](mailto:fchukwuedo@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01991be530319adf8d

**Comment by favourch** [comment] 2023-11-12 07:09
Contributor details
Your Expensify account email: [fchukwuedo@gmail.com](mailto:fchukwuedo@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/favourch

**Comment by favourch** [comment] 2023-11-12 07:09
Contributor details
Your Expensify account email: fchukwuedo@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/favourch

**Comment by favourch** [comment] 2023-11-12 07:10
Hi Team,

I've conducted tests to replicate the issue based on the steps provided:

1. Navigated to staging.new.expensify.com.
2. Opened a chat conversation.
3. Sent a message.
4. Pressed the Up key to enter edit mode and then pressed Enter immediately.

In my tests, I found that the edit mode exits as expected upon pressing Enter without delay. My testing was conducted on the MacOS: Chrome browser.

Please let me know if there are additional steps or conditions I should consider.

**Comment by Falcowoski** [comment] 2023-11-12 09:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When editing a message in a short space of time, the editing mode is exited as expected, but unwantedly, it is started again without any interaction on the part of the user. In addition, the text displayed is not the newly edited text, but the original text.

### What is the root cause of that problem?

The root cause of the problem is the invocation of the `debouncedSaveDraft` function that occurs in the mount of the `ReportActionItemMessageEdit` component.

![image](https://github.com/Expensify/App/assets/85199880/766af861-6bfd-406b-909a-67cda6998e54)

To be exact, there is a problem before that. In my opinion, there is no need to invoke the above function when mounting the component, because we are already setting the initial value of the *"state"* `draft` even before the component is mounted, i.e. in normal situations, this extra value setting is *"unnecessary"*.

![image](https://github.com/Expensify/App/assets/85199880/e8b9246a-23ef-4010-aff5-baa851b4e9e2)

Of course, I'm aware that the `updateDraft` function, which is responsible for invoking `debouncedSaveDraft` when the component is mounted, does other things besides setting the value of `draft`, but at least this particular part is unnecessary, because it's duplicated.

Returning to the root cause, it's very complicated to replicate the error in most cases, because we need to get the *"timing"* right!

We must edit the message and save it before the `debouncedSaveDraft` callback is triggered for the error to happen.

In addition to all this, it seems that the `debouncedSaveDraft.cancel` method invoked in `deleteDraft` is not working as it should, or at least not in this specific case, because it is being invoked and yet the `debouncedSaveDraft` callback is executing immediately afterwards.

```mermaid

flowchart TB
    A[Send message] --> B[Open edit mode with Up key]
    B -->|handleKeyDown| C[Invoke `saveReportActionDraft`]
    C -->|Set `draftMessage` value to last message| D[Mount `ReportActionItemMessageEdit`]
    D --> E[Run `preferredLocale` useEffect]
    E --> F[Invoke `updateDraft`]
    F -->|User add a new character| G[Invoke `triggerSaveOrCancel`]
    G -->|User press Enter key| H[Invoke `triggerSaveOrCancel` again]
    H --> I[Invoke `publishDraft`]
    I --> J[Invoke `editReportComment`]
    J --> K[Invoke `deleteDraft`]
    K -->|Set `draftMessage` value to empty string| L[Unmount `ReportActionItemMessageEdit`]
    L --> M[Close edit mode]
    M -->|`updateDraft` execute debounced callback| N[Set `draftMessage` to last original message]
    N -->|Mount `ReportActionItemMessageEdit`| O[Open edit mode]
```

### What changes do you think we should make in order to solve the problem?

#### A. Skip "setState" when it is first rendered

Prevent the invocation of `debouncedSaveDraft` when assembling the `ReportActionItemMessageEdit` component with a conditional, controlled by a variable `isFirstRenderRef.current`, created by `useRef`. 

I accept ideas for other ways to *"validate"* whether or not we're at the first rendering!

### What alternative solutions did you explore?

#### B. Fix cancel method

Understand why the `debouncedSaveDraft.cancel` method is not working as it should and fix it, so that the callback invocation is canceled.

#### C. "New" cancel method

Add another way to cancel the execution of the callback. So far, in this option, the only information I have is the **place** where we should cancel the execution, which is inside the `deleteDraft` method.

**Comment by Falcowoski** [comment] 2023-11-12 22:10
## Proposal
[Updated](https://github.com/Expensify/App/issues/31242#issuecomment-1807074643)

**Comment by ericuldall** [comment] 2023-11-13 17:19
# Proposal
`updateDraft` is called each time there is a change to the edit text. This creates a new instance of _.debounce every time so when we `publishDraft` we are only calling `.cancel()` on the most recently created version of `_.debounce`

I've fixed this issue locally but adding `debouncedSaveDraft.cancel()` to the `updateDraft` function.

**Comment by ericuldall** [comment] 2023-11-13 17:22
Contributor details
Your Expensify account email: ericuldall@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016428356daca87699

**Comment by Christinadobrzyn** [comment] 2023-11-20 05:10
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: reviewing PR

**Comment by JmillsExpensify** [comment] 2023-11-24 19:37
Looks like we're still open for proposals. @allroundexperts thoughts on the proposals so far?

**Comment by allroundexperts** [comment] 2023-11-26 23:57
Thanks for your elaborate proposal @favourch. It seems like to me that the real reason why this is not working is that the cancel method is broken. Do you mind explaining what's wrong with it and how we can fix it?

**Comment by Falcowoski** [comment] 2023-11-27 23:59
> Thanks for your elaborate proposal @Falcowoski. It seems like to me that the real reason why this is not working is that the cancel method is broken. Do you mind explaining what's wrong with it and how we can fix it?

Hi, @allroundexperts!

I do some extensive searches in this subject and sincerely, to me, is the me common issue possible: **The function reference was changed/updated and the `cancel` calls is not cancelling the right/last function.**

I'm aware that we are _wrapping_ the debounced function in a `useMemo` hook, but it is difficult for me to think of other causes.

I was thinking in focus in the `deleteDraft` dependencies and the own `debouncedSaveDraft` dependencies to find the issue.

**What do you think?**

### debouncedSaveDraft

- `props.reportID`
- `props.action`

### deleteDraft

_The `debouncedSaveDraft.cancel` function is called in this method._

- `props.action.message`
- `debouncedSaveDraft`
- `debouncedUpdateFrequentlyUsedEmojis`
- `props.preferredSkinTone`
- `preferredLocale`

**Comment by JmillsExpensify** [comment] 2023-11-29 00:21
Still working through proposals

**Comment by Christinadobrzyn** [comment] 2023-11-29 02:49
I'm back from ooo - Let us know if there are any updates on the proposal review @allroundexperts!

**Comment by Christinadobrzyn** [comment] 2023-12-04 23:02
@allroundexperts can you let us know if any of these proposals look good? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-12-08 01:35
DMd @allroundexperts and they are reviewing the proposals

**Comment by allroundexperts** [comment] 2023-12-10 19:03
Just tested this again on latest main and I am not able to reproduce this any longer. @Falcowoski Can you confirm if this is still happening for you?

**Comment by Christinadobrzyn** [comment] 2023-12-12 22:07
Just re-tested this too and I think it's resolved also. It seems like when you click the up-arrow the previous message is reopened to be edited and when you press enter the message closes. I think this is working as expected. 

@Falcowoski how does it look for you?

**Comment by Falcowoski** [comment] 2023-12-12 22:11
Sorry for the delay!

I just tested it a few times and unfortunately I replicated the issue, which is the editing menu opening automatically.

I tested in _new.expensify.com_

**Comment by Christinadobrzyn** [comment] 2023-12-12 23:56
Ah so the OP is wrong - it should be the following - is this correct @Falcowoski? 

## Expected Result:
The text can't be edited

## Actual Result:
The text is reopening to edit mode

**Comment by Falcowoski** [comment] 2023-12-13 00:11
Hmmmm, in my opinion, the expected result is the message being updated and the edit mode not opening again, like in the OP

Today, the edit mode opens again when updating the message very quick.

**Comment by Christinadobrzyn** [comment] 2023-12-14 22:40
Awesome, that does help @Falcowoski! Thanks!

**Comment by Christinadobrzyn** [comment] 2023-12-19 23:23
@allroundexperts were you able to test this based on the updated steps in the OP?

**Comment by Christinadobrzyn** [comment] 2023-12-22 19:44
I think we can move forward with reviewing proposals @allroundexperts!

**Comment by Christinadobrzyn** [comment] 2024-01-04 21:58
hi @allroundexperts can you provide an update on this?

**Comment by allroundexperts** [comment] 2024-01-05 06:58
Hi @Christinadobrzyn!
I'm still not able to reproduce this. Can you please update the video according to the new OP steps?

**Comment by Christinadobrzyn** [comment] 2024-01-08 00:45
I can't reproduce this either, I'm not sure if this is resolved but I also think it might be a low priority anyway. I think we should just close this for the time being as it's difficult to understand what the issue actually is.

**Comment by lanitochka17** [comment] 2024-01-17 15:07
Issue is still reproducible on the latest build 1.4.26-1


https://github.com/Expensify/App/assets/78819774/923ace3d-9b36-4065-a348-5d8899a38469

**Comment by quinthar** [comment] 2024-01-18 02:07
yes this feels too esoteric for right now, closing.

**Closed by quinthar** 2024-01-18 02:07 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
