### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] Attachment - Composer "+" menu get dismissed when attachment is completely uploaded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34297] opened 2024-01-10 21:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat
3. Click on + button> Add attachment> Click Send button
4. While the attachment is still uploading click on the + button from chat composer

## Expected Result:
Menu should not be dismissed when attachment is completed

## Actual Result:
Composer "+" menu gets dismissed when attachment is completely uploaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/715168ff-ed0c-4aed-8507-5d811f7ffaf8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e82e8141efc66782</li>
        <li>Upwork Job ID: 1746982705064349696</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28106726</li>
<li>dukenv0307 | Contributor | 28106727</li>
</ul></li>
    </ul>
</details>

**Comment by francoisl** [comment] 2024-01-10 22:07
I can repro on staging but not on dev, so it might have already been fixed in another PR. It also doesn't seem like it's breaking anything important, so I'll remove the blocker label for now and check again in a couple days.

**Comment by francoisl** [comment] 2024-01-15 19:47
This is reproducible in dev now (latest `main`), going to open up for external contributions.

**Comment by dylanexpensify** [comment] 2024-01-17 09:26
@akinwale to review

**Comment by akinwale** [comment] 2024-01-17 09:41
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/34297#issuecomment-1893347341) correctly identifies the root cause and the proposed solution is adequate.

🎀👀🎀 C+ reviewed.

**Comment by dylanexpensify** [comment] 2024-01-23 13:20
@dukenv0307 how's it going?

**Comment by dylanexpensify** [comment] 2024-01-29 11:55
payment upcoming!

**Comment by akinwale** [comment] 2024-01-29 20:13
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This is an edge case that was just recently discovered.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Navigate to Expensify in a desktop browser.
2. Open any chat report.
3. Click on the + button to open the add menu and select Add an attachment.
4. Select any reasonably sized attachment to upload.
5. While the attachment is still uploading, click the + button to open the add menu.
6. Verify that the add menu does not get dismissed when the attachment finishes uploading.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-02-02 10:47
@dylanexpensify bump for payment. Thanks.

**Comment by dylanexpensify** [comment] 2024-02-05 13:00
on it!

**Comment by dylanexpensify** [comment] 2024-02-05 13:03
All steps done!

**Closed by dylanexpensify** 2024-02-05 13:03 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
