### ISSUE TITLE
[HOLD for payment 2024-04-25] Tax - Maximum tax amount is 0 error msg on updating currency for non-default tax rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40036] opened 2024-04-10 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+1088ck@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39562
## Action Performed:
Precondition : Add tax rates for any WS apart from the default one
1. Tap on FAB button >> Request money
2. Select Manual option & enter amount
3. Select workspace with enabled taxes
4. On the confirm screen choose a different tax rate
5. Click on Tax amount option
6. Change currency to a different option & tap on Save button (Note: Error message appears)
7. Change back currency to USD & tap on save button

## Expected Result:
No error message appear & tax amount get saved on changing currency for a non-default rate

## Actual Result:
Maximum tax amount is 0 error msg on updating currency for non-default tax rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d3fc138a-c47b-4e4b-ae6a-06794593439f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-10 20:11
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-10 20:11
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment] 2024-04-10 20:55
@akinwale @ZhenjaHorbach can you please check as this might be coming from your PR. Thanks!

**Comment by luacmartins** [comment] 2024-04-10 21:36
I can reproduce on staging, but not locally anymore

**Comment by luacmartins** [comment] 2024-04-10 21:37
Hmm it only happens with certain currencies

**Comment by luacmartins** [comment] 2024-04-10 21:52
I think it might be coming from https://github.com/Expensify/App/pull/39723

**Comment by luacmartins** [comment] 2024-04-10 21:58
Yea, found the cause

**Comment by luacmartins** [comment] 2024-04-10 22:00
Left a comment here - https://github.com/Expensify/App/pull/39723#issuecomment-2048508256

**Comment by luacmartins** [comment] 2024-04-10 22:09
I put up a PR, but I'm unsure if the logic makes sense. Asked the original authors for a review

**Comment by MonilBhavsar** [comment] 2024-04-11 09:53
CP'ing here https://expensify.slack.com/archives/C07J32337/p1712828884534849

**Comment by luacmartins** [comment] 2024-04-19 16:56
This was fixed internally and there was no C+ review, so we can close this.

**Closed by luacmartins** 2024-04-19 16:56 UTC
Labels: Engineering, Weekly, Awaiting Payment
