### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250]  Login - Abracadabra page briefly displayed when login via 'Sign in here' link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41772] opened 2024-05-07 15:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2616811
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging
3. Open an new INCOGNITO window and navigate to the staging link
4. On "Here's your magic code" page click a link "Sign In here"

## Expected Result:
After a loading spinner user is logged in

## Actual Result:
A briefly Abracadabra page is displayed during logging

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a5becf03-78b2-41b1-85f0-db559f17802b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4cbaa3a58c2360d</li>
        <li>Upwork Job ID: 1790583339987804160</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102679418</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-05-07 15:07
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment] 2024-05-15 03:21
Opening this up for proposals.

**Comment by nkdengineer** [comment] 2024-05-15 04:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A briefly Abracadabra page is displayed during logging

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L73, we're always showing the `JustSignedInModal` even though the current session might or might not be the original sign in session.

### What changes do you think we should make in order to solve the problem?

Store the information of whether the current session is the original sign in session in a ref
```
const isOriginalSignInSessionRef = useRef(true);

useEffect(() => {
    isOriginalSignInSessionRef.current = !session?.authToken;
}, []);
```

Then in [here](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L73), show the `JustSignedInModal` only if the current session is not the original sign in session
```
{autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN && isSignedIn && !exitTo && !isOriginalSignInSessionRef.current && <JustSignedInModal is2FARequired={false} />}
```


### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-05-15 04:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A briefly Abracadabra page is displayed during logging

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L73, we're always showing the `JustSignedInModal` even though the current session might or might not be the original sign in session.

So there're 2 cases:
- If there's another login tab, then `JustSignedInModal` should show to direct the user to the original tab. This will happen when the magic link is open in the same browser of the original sign in tab. 
- If there's no other login tab, the user already presses `just sign in here` so the `JustSignedInModal` should not show and the user will be logged in right in the current tab. This GH issue falls into this case where the magic link is opened in Incognito mode.

### What changes do you think we should make in order to solve the problem?

Store the information of whether the current session is the original sign in session in a ref, [here](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L27)
```
const isOriginalSignInSessionRef = useRef(true);

useEffect(() => {
    isOriginalSignInSessionRef.current = !session?.authToken;
}, []);
```

The `!session?.authToken` is the same condition we use to check in order to show `just sign in here` [here](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/components/ValidateCode/ValidateCodeModal.tsx#L50)

Then in [here](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L73), show the `JustSignedInModal` only if the current session is not the original sign in session
```
{autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN && isSignedIn && !exitTo && !isOriginalSignInSessionRef.current && <JustSignedInModal is2FARequired={false} />}
```

We might need to do the same for [this case](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L72) or other similar cases.

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-05-20 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A briefly Abracadabra page is displayed during logging

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L73, we're always showing the `JustSignedInModal` even though the current session might or might not be the original sign in session.

So there're 2 cases:
- If there's another login tab, then `JustSignedInModal` should show to direct the user to the original tab. This will happen when the magic link is open in the same browser of the original sign in tab. 
- If there's no other login tab, the user already presses `just sign in here` so the `JustSignedInModal` should not show and the user will be logged in right in the current tab. This GH issue falls into this case where the magic link is opened in Incognito mode.

### What changes do you think we should make in order to solve the problem?

Use the `login` [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ValidateLoginPage/index.website.tsx#L22) to check whether the current session is the original sign in session. If `login` is available, that means there's another tab that the user attempted to login from, and the current session is not the original sign in session. 

So we should update [this](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ValidateLoginPage/index.website.tsx#L73) to
```
{autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN && isSignedIn && !exitTo && login && <JustSignedInModal is2FARequired={false} />}
```

We might need to do the same for [this case](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L72) or other similar cases.

### What alternative solutions did you explore? (Optional)
Store the information of whether the current session is the original sign in session in a ref, [here](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/pages/ValidateLoginPage/index.website.tsx#L27)
```
const isOriginalSignInSessionRef = useRef(true);

useEffect(() => {
    isOriginalSignInSessionRef.current = !session?.authToken;
}, []);
```

The `!session?.authToken` is the same condition we use to check in order to show `just sign in here` [here](https://github.com/Expensify/App/blob/edd1719f62d74663d52f4168db2fd7adfe0cdda3/src/components/ValidateCode/ValidateCodeModal.tsx#L50)

Then in [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ValidateLoginPage/index.website.tsx#L73), show the `JustSignedInModal` only if the current session is not the original sign in session
```
{autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN && isSignedIn && !exitTo && login && <JustSignedInModal is2FARequired={false} />}
```

**Comment by nkdengineer** [comment] 2024-05-20 20:05
> @nkdengineer Can you please give an ETA for a PR?

@rayane-djouah I can open the PR for this within a day. 

> I've just realized that @nkdengineer have multiple issues and PRs ongoing.

Most of those are not held on me (only 2 held on me the last time I check shortly ago). Most are held on the C+/internal engineers/merge freeze. I would be completely comfortable opening this PR in a day or half a day.

cc @tylerkaraszewski

**Comment by nkdengineer** [comment] 2024-05-24 04:22
@tylerkaraszewski Could you [assign me here](https://github.com/Expensify/App/issues/41772#issuecomment-2120989357) so I can start on the PR?

Thanks 🙇

**Comment by JmillsExpensify** [comment] 2024-06-05 05:27
Awaiting final confirmation from @tylerkaraszewski when he has a second.

**Comment by mvtglobally** [comment] 2024-06-05 21:21
Issue not reproducible during KI retests. (First week)

**Comment by tylerkaraszewski** [comment] 2024-06-11 00:25
This has been delayed significantly as I haven't been able to focus on it given the backend problems we've had lately. I am going to assign @nkdengineer as I think that proposal is still valid.

**Comment by nkdengineer** [comment] 2024-06-11 08:35
@rayane-djouah this [PR](https://github.com/Expensify/App/pull/43457) is ready for preview

**Comment by JmillsExpensify** [comment] 2024-06-26 19:41
Payment summary: 

- Contributor: @nkdengineer $250
 - Reviewer: @rayane-djouah $250

**Comment by JmillsExpensify** [comment] 2024-06-26 19:44
@rayane-djouah Just sent you an offer on Upwork. @nkdengineer I've paid out your offer on Upwork.

**Comment by JmillsExpensify** [comment] 2024-06-26 19:50
Thanks! All paid out. Regression test also created, so closing this out.

**Closed by JmillsExpensify** 2024-06-26 19:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
