### ISSUE TITLE
[$500] Chat - The video is reloaded every time you open it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37168] opened 2024-02-24 10:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/37036

**Version Number:** v1.4.43-18
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+ihchat4_2302_133c@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Login with any account
3. Go to any chat
4. Plus button -> Add attachment -> Send a video
5. Open the video that you just sent
6. Tap the back button
7. Open the video again

## Expected Result:
Loading spinner is displayed only when you open the video for the first time

## Actual Result:
The video is reloaded every time you open it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ed75e85e-dca4-4385-ad16-d4d8c69816ed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018db53b84762ad824</li>
        <li>Upwork Job ID: 1761342164490567680</li>
        <li>Last Price Increase: 2024-03-30</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-24 10:48
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by webbdays** [comment] 2024-02-24 12:25
This shows no caching.

**Comment by webbdays** [comment] 2024-02-25 11:20
**Note:**
Streaming the video is the best thing to do than download whole video at a time.
Its best to achieve this by doing things like when video plays for the first time we get the stream segments. As we get more and more segments we join them to form a video. This helps us to get the video and users sees the video without waiting long time instead of waiting for full long video to download at first.

Second when we add caching, cache invalidation is very important. Adding functionality like ask the server "is the video/file modified?" before asking for video. (This needs some server side changes(very minor)).

**Comment by Skalakid** [comment] 2024-02-26 15:43
@izarutskaya @DylanDylann @greg-schroeder I'm not sure if it is a bug, I think it is more like a new feature for the video player. The presented behavior is correct according to the video player design doc. Video caching wasn't planned during the predesign. I think it might be a great improvement! What do you think about it @francoisl?

@brandonhenry video player work differently depending on the screen size. On small screens, they are only usable inside the attachment modal. On large screens video players are available inside chat. When extending the video we are sharing the component to the attachment carousel to optimize video loadings (currently it is broken on main but I created a [fix](https://github.com/Expensify/App/pull/37202) for it). Because of that, I think we should cache only videos that have  `shouldUseSharedVideoElement` set to `false`

**Comment by greg-schroeder** [comment] 2024-02-27 03:51
Discussion ongoing

**Comment by DylanDylann** [comment] 2024-02-27 09:32
I agree with @Skalakid at this point

>  I'm not sure if it is a bug, I think it is more like a new feature for the video player. The presented behavior is correct according to the video player design doc. Video caching wasn't planned during the predesign. I think it might be a great improvement

@francoisl @Gonals Should we make an improvement to have a caching mechanism here?

**Comment by francoisl** [comment] 2024-02-27 19:06
Yes, that would make sense to me and sounds like a good improvement overall.

Are there any other libs than `react-native-cached-image` out there though? The [GH repo](https://github.com/kfiroo/react-native-cached-image) for that project looks dead, the latest release is 7 years old.

**Comment by webbdays** [comment] 2024-02-28 05:06
I think expensify already have the codebase for that. Providers code in react-native-onyx repo.

**Comment by DylanDylann** [comment] 2024-02-28 09:57
@brandonhenry Could you give a video after applying your change? And pushing your change to a branch then I can test your solution

**Comment by DylanDylann** [comment] 2024-03-01 09:04
I am not in favor of adding [react-native-cached-image](https://github.com/zhigang1992/react-native-video-cache/commits/master/) to our repo

**Comment by webbdays** [comment] 2024-03-04 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Problem Statement: Video in chat should play without load the second time. Which mean we need caching.

### What is the root cause of that problem?
The reason for the video still loading the second time is that there is no caching for the videos in chat. User need to wait until the browser gets video from the backend again.

### What changes do you think we should make in order to solve the problem?
Implementing cache mechanism for attachments (like videos) in the chat at AttachmentViewVideo component or even early or later in base component (BaseVideoPlayer).

I have implemented it using existing code in [react-native-onyx](github.com/expensify/react-native-onyx) codebase.
The code used is in "src/libs/Storage" folder. Cleaned it a bit to make it suitable for this case. Functionality remains the same. But use case is different.

The code provides an Storage Api to store key value pairs in both native and web platforms. It uses "idb-keyvalue" package for web. And "react-native-quick-sqlite" for native.
 
Moved this code to "src/libs/Storage" folder in Expensify/App repo and made some changes required.
Added some cacheUtils code to help in cache implementation. Also changes to clear cache when sign out.

But there is some points here (not related to implementation but for using it inside a component) :
1. Cache not happening in wide screen. Video is playing without attachment view popup. Maybe we need to move this cache mechanism to appropriate component. I am not fully aware of the codebase. Working when minimise the window. Tested on Edge Browser in windows os.
2. Not tested for android, ios. But still the changes will solve for android and ios too.

I am ready to make a pr.

### What alternative solutions did you explore?
We can use onyx with some modifications/by exposing storage API to allow create custom cache DB without default., but its intended use is different. This is another approach.

Note:
1. Still user need to wait until the video downloads for the first time. No fast play here. Still didn't found a proper way for this.
2. Cache Invalidation need backend changes for sure.

**Comment by webbdays** [comment] 2024-03-04 17:41
@DylanDylann
@brandonhenry

**Comment by webbdays** [comment] 2024-03-04 17:49
"idb-keyval" and  "react-native-quick-sqlite" i think these are already being used here.

**Comment by DylanDylann** [comment] 2024-03-06 09:04
I think it is better if we can use the existing implementation. 

> I have implemented it using existing code in [react-native-onyx](https://github.com/Expensify/App/issues/github.com/expensify/react-native-onyx) codebase.

@webbdays Could you help to point out which existing code we should apply for this case? It seems your link isn't correct

**Comment by webbdays** [comment] 2024-03-06 11:01
Sorry, it's expensify/react-native-onyx repo.

**Comment by DylanDylann** [comment] 2024-03-06 11:10
@webbdays Please give me a link to your reference. I can't find src folder in expensify/react-native-onyx repo.

**Comment by webbdays** [comment] 2024-03-06 11:23
https://github.com/Expensify/react-native-onyx/tree/main/lib%2Fstorage

**Comment by webbdays** [comment] 2024-03-06 11:31
> @webbdays Please give me a link to your reference. I can't find src folder in expensify/react-native-onyx repo.

@DylanDylann 
I have confused. Provided the link in comments.

**Comment by webbdays** [comment] 2024-03-07 09:23
If onyx is working with that storage API then this should work. Why not?

Below code files handles that on both android and ios.
1. https://github.com/Expensify/react-native-onyx/blob/main/lib/storage/index.native.ts ,
2. https://github.com/Expensify/react-native-onyx/blob/main/lib/storage/NativeStorage.ts ,
3. https://github.com/Expensify/react-native-onyx/blob/main/lib/storage/providers/SQLiteStorage.ts  (main logic is in this code file).

Note: I am not changing anything major in the Storage API, just cleaned and kept what is necessary.
Thank you.

**Comment by greg-schroeder** [comment] 2024-03-09 02:26
Discussion is still ongoing about a preferred solution, not overdue Melvin

**Comment by DylanDylann** [comment] 2024-03-09 02:49
Yeah, I am reviewing proposals

**Comment by webbdays** [comment] 2024-03-09 04:51
Is melvin-bot an AI bot or human on other side.

**Comment by webbdays** [comment] 2024-03-11 09:30
@DylanDylann
For indexed DB the max size is nearly equivalent to HDD allocated for browser.
For sqlite in Android and iOS storage limits is some GB's.
In web, We usually prefer indexed DB for data like these. Local storage is at max 10 to 12 MB.

I think storage is not that pivoting thing here.
Thank you.

**Comment by webbdays** [comment] 2024-03-11 09:32
@DylanDylann 
Anyway, We need have some threshold for this for cleanup purposes. Like cleaning oldest cached video. Or based on some other criteria. May be video size. Or mixed.

**Comment by webbdays** [comment] 2024-03-11 09:50
If you are talking of the type of data we can store.
We can download video as blob and convert video blob to base64 string and store in a json object and then store that in DB as key value pairs for cache mechanism.
Url -> json
I have done the same in my poc for web. It's working for web.

Thank you.

**Comment by greg-schroeder** [comment] 2024-03-13 20:24
Proposals still being reviewed

**Comment by DylanDylann** [comment] 2024-03-14 07:44
@brandonhenry 
1. It seems `expo-file-system` doesn't support mWeb
2. Why do you think we should remove the video from the cache in `modificationTime` order
3. The data in the cache could be outdated. How we can validate data on the cache? 

@webbdays I still don't understand your proposal. I don't think we can use the same logic on react-native-onyx for this case.  Could you help to detail your solution? Thanks

**Comment by webbdays** [comment] 2024-03-15 08:58
**Cache mechanism is as usual -> use cache if exists.**
### Details
Here is the detail overview what and how the storage API is used for caching and its compatibility.
#### Storage API in react-native-onyx repo:
1. It was written to be compatible for all the three platforms (web, Android, IOS). Its just wrapper around below two libraries.

      - idb-keyval
      - react-native-quick-sqlite

2. It uses "idb-keyval" to connect with indexedDB for web platforms. Store key value pairs data. Storage Capacity: some GB's
3. It uses "react-native-quick-sqlite" to store data in native sqlite DB in both android and ios platforms. Storage Capacity: Some GB's.
4. These libraries help us to store video data.
5. When the video is played first, we download as blob and convert that blob to base64 string, and build a json.
{base64:base64ofVideoblob}
store this in DB using storage API,
for web(Indexed DB) - key-value pairs are stored.  It don't care what inside it as far as the key - url is a string and value is in correct json format. This way of storage is compatible with mweb safari as well, no problem.
for native - here json is converted to string. and store in a keyvaluepairs table along with the key.

#### Mainly these methods are used.
```javascript

// example usage
import cacheStorage from "@libs/storageAPI";
cacheStorage.setItem(url, value_json)
cacheStorage.getItem(url)
// to know if any keys exist.
cacheStorage.getAllKeys()

// we use this way in our cache Implementation as usual.

``` 
##### for web
[this code is used by storage API](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/IDBKeyVal.ts)

[to get key value pair from db ](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/IDBKeyVal.ts#L43-L46)
[to set key value pair](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/IDBKeyVal.ts#L18)
[to get all keys in DB](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/IDBKeyVal.ts#L42)
##### for native
[this code is used by storage API](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/SQLiteStorage.ts)
[to get key value pair from db ](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/SQLiteStorage.ts#L24-L32)
[to set key value pair](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/SQLiteStorage.ts#L42-L44)
[to get all keys in DB](https://github.com/Expensify/react-native-onyx/blob/b0766c21e614b1e4bb1ec3f32e6daa043a8ef586/lib/storage/providers/SQLiteStorage.ts#L72-L77)
#### References:
1. [Storage API ](https://github.com/Expensify/react-native-onyx/tree/main/lib/storage)
2. [idb-keyval](https://github.com/jakearchibald/idb-keyval?tab=readme-ov-file#idb-keyval)
3. [react-native-quick-sqlite](https://www.npmjs.com/package/react-native-quick-sqlite)
4. [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)

**Comment by webbdays** [comment] 2024-03-15 09:42
commit to reference "lib/storage" in react-native-onyx : [d00b8cb8c777887a119188b7e71ec50a833f1e1f] (https://github.com/Expensify/react-native-onyx/tree/d00b8cb8c777887a119188b7e71ec50a833f1e1f)

**Comment by greg-schroeder** [comment] 2024-03-17 08:24
conversation ongoing

**Comment by DylanDylann** [comment] 2024-03-18 07:23
Discussing on [Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1710746338439909)

**Comment by webbdays** [comment] 2024-03-24 10:06
@DylanDylann
@brandonhenry
any outcome?|
Thank you.

**Comment by DylanDylann** [comment] 2024-03-25 02:59
Discussion on Slack

**Comment by greg-schroeder** [comment] 2024-03-26 22:01
This might be moved `Internal` per [discussion](https://expensify.slack.com/archives/C02NK2DQWUX/p1710746338439909) - at any rate it's definitely chat-related (but not expense related) so I'm going to put this into #vip-vsb

**Comment by DylanDylann** [comment] 2024-04-01 08:57
@francoisl Please keep updating this issue

**Comment by greg-schroeder** [comment] 2024-04-05 21:32
I'm going to close it per that discussion ... please reopen if you disagree.

**Comment by lanitochka17** [comment] 2024-05-15 17:29
Issue is still reproducible on the latest build 1.4.74-0


https://github.com/Expensify/App/assets/78819774/e5b82f2c-4119-4819-a5b3-23a9f96f7f28

**Comment by greg-schroeder** [comment] 2024-05-15 22:40
Thanks @lanitochka17 - we're just handling it in the linked issue above, so we can leave this closed.

**Closed by greg-schroeder** 2024-05-15 22:40 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
