### ISSUE TITLE
[$500] Android - Wallet - The keyboard does not open automatically when the debit card is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37325] opened 2024-02-27 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+ihchat4_0802_e@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34257
## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Wallet -> Add BA -> Debit card

## Expected Result:
The keyboard opens automatically

## Actual Result:
The keyboard does not open automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8d8de760-d200-4687-8057-d8b4699b6293

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4bb1353b2dd4f53</li>
        <li>Upwork Job ID: 1762533141580525568</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-02-27 17:44
This will be fixed after #37305 reach staging

**Comment by chiragsalian** [comment] 2024-02-27 19:51
I've asked qa to retest and clear deploy blocker [here](https://github.com/Expensify/App/issues/37224#issuecomment-1967441593).

**Comment by kavimuru** [comment] 2024-02-27 20:38
Removed the deployblocker label. Issue is not reproducible anymore.

**Comment by chiragsalian** [comment] 2024-02-28 00:17
awesome, since its not reproducible i'm going to go ahead and close out this issue to keep things clean.

**Closed by chiragsalian** 2024-02-28 00:17 UTC
Labels: External, Engineering, Hourly, Help Wanted

**Comment by cubuspl42** [comment] 2024-03-01 09:38
No payment due
