### ISSUE TITLE
[HOLD for payment 2023-06-30] [$1000] Text remains selected in a PDF attachment even after clicking on a blank space.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20098] opened 2023-06-02 20:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open new.expensify.com
2. Navigate to a chat and send a PDF attachment.
3. Open the attachment.
4. Highlight text within the PDF
5. Now click on blank space in the PDF 

## Expected Result: 
Clicking on a blank space should unselect the text within the PDF attachment.

## Actual Result: 
The text remains highlighted when clicking on a blank space.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5e690f0d-8ae4-4255-a6ff-e20e8818206d

https://github.com/Expensify/App/assets/43996225/34641da0-09ee-4ba3-8bd8-a40da67fff64

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685610012204549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011482fa67cb29b12b</li>
        <li>Upwork Job ID: 1665723287863721984</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by Thanos30** [comment] 2023-06-05 16:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We can't deselect the text highlighted inside a PDF when we click on an empty area

### What is the root cause of that problem?

The root cause of the issue is the styling of the `PageCanvas` which contains the following part:

` userSelect: 'none' `

, a styling option that prevents users from affecting the document.

### What changes do you think we should make in order to solve the problem?
Since I don't want to interfere with imported modules' code, my solution would be to add a `onMouseDown` event on the `Document` of our `PDFView` component, that will clear our previous selection.

```
 handleDocumentMouseDown() {
        const selection = window.getSelection();
        if (selection && !selection.isCollapsed) {
          selection.removeAllRanges();
        }
      }
```

and then append this to the Document props:

```
    onMouseDown={this.handleDocumentMouseDown} // Added onMouseDown event handler

```

**Comment by will0225** [comment] 2023-06-06 17:08
Can I work on this?

**Comment by puneetlath** [comment] 2023-06-12 13:30
@trjExpensify I'll be OOO this week, so if there's a proposal that ends up needing approval, please use the Engineering label to get someone else assigned. Thanks!

**Comment by trjExpensify** [comment] 2023-06-12 13:48
Okay, booting @puneetlath so I can add another engineer 👍

**Comment by puneetlath** [comment] 2023-06-21 20:52
@tylerkaraszewski I went ahead and reviewed/merged it since I'm back from vacay and was previously assigned. Thanks for handling it while I was out!

**Comment by tylerkaraszewski** [comment] 2023-06-30 16:50
@puneetlath - giving this one back to you as I'm heading out on sabbatical.

**Comment by trjExpensify** [comment] 2023-06-30 17:52
👋 @parasharrajat @allroundexperts can you guys get to the checklist so we can proceed to payments? Thanks!

**Comment by trjExpensify** [comment] 2023-07-03 10:27
No change since Friday, awaiting the checklist!

**Comment by trjExpensify** [comment] 2023-07-05 22:20
Same, require the checklist to be filled out ahead of payments!

**Comment by trjExpensify** [comment] 2023-07-10 09:58
@parasharrajat @allroundexperts can you guys complete the checklist so we can proceed with payments, please?

**Comment by trjExpensify** [comment] 2023-07-17 14:17
Cool, thanks! Outside of that, I've proceeded on Upwork with the following:

@Tushu17 - $250 for the bug report (Offer sent)
@allroundexperts - $1,000 for the bug fix (Paid!)

As for the regression test, I think we can modify one of the existing test scripts to accommodate this (bold for emphasis). Issue created [here](https://github.com/Expensify/Expensify/issues/300356).

> 1. On a conversation, click on the + button in the compose box
> 2. Click on add attachment
> 3. Upload a PDF
> 4. Verify a preview of the PDF is displayed before uploading to the conversation
> 5. Click on upload
> 6. Verify you can see the PDF in the conversation
> 7. Click on the PDF preview
> 8. Verify a larger preview of the PDF is displayed
> 9. Verify the width of the send button doesn't extend to the far edges of the screen on desktop, web and wide devices
> 10. Verify the modal background color matches the header dark green color (both should be the same shade)
> 11. **Highlight text within the PDF via cursor.**
> 12. **Click on the blank space in the PDF.**
> 13. **Verify the highlighted text is unhighlighted**
> 14. Close the PDF preview

**Comment by Tushu17** [comment] 2023-07-17 16:52
@trjExpensify offer accepted. Thank you.

**Comment by trjExpensify** [comment] 2023-07-17 17:20
@Tushu17 paid!

**Comment by anmurali** [comment] 2023-07-21 15:55
Approved $1000 to Rajat based on https://github.com/Expensify/App/issues/20098#issuecomment-1628626290 (checklist completed since)

**Comment by trjExpensify** [comment] 2023-07-21 16:14
Neeeat! Thanks, closing! :)

**Closed by trjExpensify** 2023-07-21 16:14 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
