### ISSUE TITLE
Sent money/requested money message disappears on refresh from LHN - Reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10620] opened 2022-08-29 02:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to a chat and send money
 2. Refresh the page

## Expected Result:
The message shouldn't disappear

## Actual Result:
The message disappear

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.89-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/187111133-13786dbb-6ded-4fdf-bf27-44ec4f4685eb.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660070110835229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cdraeger11** [comment] 2022-09-09 04:52
Sorry I was looking at the dashboard. The copy looks good!

**Comment by abekkala** [comment] 2022-09-09 12:39
@cdraeger11 Did you already triage this? Or did you reapply the triage label to have someone else triage?

**Comment by nkuoch** [comment] 2022-09-09 18:16
Double checking with @marcaaron Do you think it can be external?

**Comment by marcaaron** [comment] 2022-09-09 18:34
I would guess it's related to an API refactor. But without knowing the root cause a bit hard to say. Maybe we can put an `Internal` label on it for now and then `External` after someone looks into it a bit more.

**Comment by Puneet-here** [comment] 2022-09-17 07:10
We had a similar issue in past (https://github.com/Expensify/App/issues/5712) and it was fixed by this PR: https://github.com/Expensify/Web-Expensify/pull/31925

Just linking it here hoping it will help in the current issue.

**Comment by zanyrenney** [comment] 2022-10-18 19:07
This is not reproduceable on staging - just tested refreshing and the send money request is still there:
<img width="1403" alt="2022-10-18_20-05-33" src="https://user-images.githubusercontent.com/56830058/196521584-f3738835-fab8-41f7-a10e-8a38e52d93b7.png">

**Comment by Puneet-here** [comment] 2022-10-18 19:12
Hi @zanyrenney, the iou message disappears at the LHN (preview of message) not from the chat.

**Comment by Puneet-here** [comment] 2022-10-20 12:22
bump @zanyrenney

**Comment by Puneet-here** [comment] 2022-11-02 17:48
Bump @zanyrenney

**Comment by Puneet-here** [comment] 2022-12-06 10:43
This is reproducible even without refreshing.

**Comment by marcochavezf** [comment] 2022-12-07 02:27
Grabbing this one as internal, from @Puneet-here's comment [here](https://github.com/Expensify/App/issues/10620#issuecomment-1250017522) seems we're missing some data in Onyx.

**Comment by zanyrenney** [comment] 2022-12-07 17:11
Awesome, thanks for grabbing it @marcochavezf - let me know how I can help.

**Comment by JmillsExpensify** [comment] 2022-12-22 20:23
@marcochavezf Are there any additional PRs coming for this issue? The only linked PR I see hit production some time ago.

**Comment by marcochavezf** [comment] 2022-12-23 23:54
Yeah that was the only PR needed to fix this issue. Tested real quick and looks good:

https://user-images.githubusercontent.com/6829422/209414182-74f8d1b8-1433-4ced-9dc5-8a67fd914c28.mov

We can close this out.

**Comment by Puneet-here** [comment] 2022-12-27 08:37
Hi @JmillsExpensify, I think it's eligible for the reporting bonus.

**Comment by JmillsExpensify** [comment] 2022-12-27 16:49
Oh thanks. @zanyrenney is OOO so I'll take this over for her in the meantime. I just invited you to the [Upwork job](https://www.upwork.com/jobs/~01f948c7e31e63a26d).

**Comment by Puneet-here** [comment] 2022-12-27 18:29
@JmillsExpensify, applied!

**Comment by JmillsExpensify** [comment] 2022-12-27 19:18
Thanks! Offer sent

**Comment by Tushu17** [comment] 2022-12-27 21:15
Hello @JmillsExpensify, I know it's quite late to say this, but I had also reported the exact same issue: 
https://github.com/Expensify/App/issues/8125
Can you check if I'm still eligible for reporting compensation?

**Comment by JmillsExpensify** [comment] 2022-12-27 21:18
Huh, I'm glad you said something. Given that your issue was reported much earlier, and the reproduction steps are the same (in fact more thorough), I'm inclined to award you. I'm also not clear how this duplicate wasn't caught earlier. cc @mallenexpensify for a second opinion.

**Comment by mallenexpensify** [comment] 2022-12-27 21:54
Fun one!  I _think_ there are a few likely reasons here
1. #8125 was closed cuz it wasn't reproducible.  Maybe it was still reproducible but under a different set of circumstances. 
2. There's something new going on and it just so happens to mirror the older issue/s
3. There's a regression which caused this bug

I don't know the answer to the above but, I think @Puneet-here should be compensated for reporting because, had they not, we might not have fixed the bug (ie. commenting on an issue that was closed 6 months ago isn't likely to get much traction) .  I think we should also compensate @Tushu17 unless someone wants to go digging to somehow show #8125 isn't directly related (also... it's only $250, I'm impressed @Tushu17 happened to find this one, I appreciate the 👀 on repo issues and 🐛🐛).    

@Tushu17 and @Puneet-here , please accept and Mills or I will get you paid https://www.upwork.com/jobs/~01f948c7e31e63a26d

**Comment by JmillsExpensify** [comment] 2022-12-27 21:57
Nice, I agree with that. Both offers are pending in Upwork, so we'll close the loop on this one shortly.

**Comment by Puneet-here** [comment] 2022-12-27 22:12
Thank you for the consideration😄

**Comment by Puneet-here** [comment] 2022-12-27 22:12
I have accepted the offer

**Comment by Tushu17** [comment] 2022-12-27 22:32
@JmillsExpensify @mallenexpensify Thank you; Offer accepted, and I am grateful.

**Comment by mallenexpensify** [comment] 2022-12-27 23:46
@Puneet-here and @Tushu17 have been paid! Thanks!  re-re-closing :)

**Closed by mallenexpensify** 2022-12-27 23:46 UTC
Labels: Reviewing, Engineering, Daily, Internal
