### ISSUE TITLE
[$500] Chat - Skeleton is displayed at beginning, then a black area appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31189] opened 2023-11-10 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30774
## Action Performed:
re-requisite: must be logged in and have a chat with a lot of messages
1. Open a chat where you have a lot of messages
2. Scroll up many times to load previous messages on chat

## Expected Result:
Skeleton should appear every time the chat loads

## Actual Result:
Skeleton is displayed at beginning, then a black area appears and loading previous messages has an unusual behavior

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cf696881-054f-4a03-9f45-e3458c42e8a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f353b1fa07d8bce</li>
        <li>Upwork Job ID: 1723031808885907456</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

**Comment by adarkforce** [comment] 2023-11-11 17:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

1. Black area appears instead of skeleton.
2. Weird behaviour when loading new actions.

### What is the root cause of that problem?

1. `ReportActionsSkeletonView` is not rendering when `reportMetadata.isLoadingNewerReportActions` or `reportMetadata.isLoadingOlderReportActions` are `true`.
2. Messing up with `getItemLayout` in `BaseInvertedFlatList.js` causes rendering issues along with performance ones on my machine, the project was barely usable.

### What changes do you think we should make in order to solve the problem?
1. Add `reportMetadata.isLoadingNewerReportActions` or `reportMetadata.isLoadingOlderReportActions` in the rendering condition.
```
{(!isReportReadyForDisplay ||
                                    isLoadingInitialReportActions ||
                                    isLoading ||
                                    reportMetadata.isLoadingNewerReportActions ||
                                    reportMetadata.isLoadingOlderReportActions) && <ReportActionsSkeletonView />}
```
2. Removing `getItemLayout` and all the correlated functions from `BaseInvertedFlatList` fixed all the rendering and performance issues.

**Comment by adarkforce** [comment] 2023-11-11 17:59
Contributor details
Your Expensify account email: a.dellafortuna00@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b4d8d8ede39fdc74

**Comment by adarkforce** [comment] 2023-11-11 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

1. Black area appears instead of skeleton.
2. Weird behaviour when loading new actions.

### What is the root cause of that problem?

1. `ReportActionsSkeletonView` is not rendering when `reportMetadata.isLoadingNewerReportActions` or `reportMetadata.isLoadingOlderReportActions` are `true`.
2. Messing up with `getItemLayout` in `BaseInvertedFlatList.js` causes rendering issues along with performance ones on my machine, the project was barely usable.

### What changes do you think we should make in order to solve the problem?
1. Add `reportMetadata.isLoadingNewerReportActions` or `reportMetadata.isLoadingOlderReportActions` in the rendering condition.
```
{(!isReportReadyForDisplay ||
                                    isLoadingInitialReportActions ||
                                    isLoading ||
                                    reportMetadata.isLoadingNewerReportActions ||
                                    reportMetadata.isLoadingOlderReportActions) && <ReportActionsSkeletonView />}
```
2. Removing `getItemLayout` and all the correlated functions from `BaseInvertedFlatList` fixed all the rendering and performance issues.

**Comment by adarkforce** [comment] 2023-11-11 22:13
## Proposal

Unusual scrolling behaviour with performance degradation, causing weird jumps and inconsistent scroll behaviour. 
PS: on my machine it was VERY laggy.

### What is the root cause of that problem?

Performance degradation.
- `maxToRenderPerBatch` forced to 1.
- `BaseInvertedFlatList` using`getItemLayout`

### What changes do you think we should make in order to solve the problem?

The main issue was the `BaseInvertedFlatList` component having to measure items layout, removing all the related code along with forced `windowSize` made the component faster and more responsive. 

The list stopped in iOS Safari when reaching the top. This was mainly due to `maxToRenderPerBatch` set to `1` in `BaseInvertedFlatList` component, it could be safely removed because [#24482](https://github.com/Expensify/App/pull/24482) has been merged. 
This, along with removing `onEndReachedThreshold` and `onStartReachedThreshold` made the scrolling experience faster and more consistent.

After the fix, when scrolling fast, the component can result in showing blank rows.
Readjusting for example `maxToRenderPerBatch` could improve it, but I don't think there's an event signalling the fact that the view is full of items that are not ready to render (blank).  
The rows now appear faster, and It seems that the overall user experience is largely improved.

We can also render `ReportActionsSkeletonView` when  
 `reportMetadata.isLoadingNewerReportActions` or   `reportMetadata.isLoadingOlderReportActions` is true, to show the skeleton while loading new data, but it doesn't seem strictly necessary

**Comment by miljakljajic** [comment] 2023-11-13 14:23
This is linked to newDot performance issues which we're discussing internally - raised it in #newdot-performance and will share next steps soon

**Comment by getusha** [comment] 2023-11-19 05:07
Not able to reproduce this one
@lanitochka17 @miljakljajic @adarkforce

**Comment by miljakljajic** [comment] 2023-11-21 18:17
Checking with Applause as they reported this one!

**Comment by miljakljajic** [comment] 2023-11-21 19:05
Not reproducible: https://expensify.slack.com/archives/C9YU7BX5M/p1700590625655629

**Closed by miljakljajic** 2023-11-21 19:05 UTC
Labels: External, Daily, Help Wanted, Bug
