### ISSUE TITLE
Scan - Broken expense report is created when paying expense that have manual and scan requests

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32694] opened 2023-12-07 18:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: There are 2 manual and 2 scan requests in the workspace chat
1. [Admin] Pay the request in the workspace chat with member
2. [Member] Go to the workspace chat
3. [Member] Tap on the IOU preview which contains the scanning requests

## Expected Result:
The expense report appears normal without issue

## Actual Result:
The expense report is broken. One of the scanning preview is at the top of the page with infinite skeleton loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/467dc5e0-1bad-494f-8b5a-7496b90301e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2023-12-07 18:41
Production:

https://github.com/Expensify/App/assets/78819774/1af0b76f-82d8-4d55-bc1e-ce54da36b49a

**Comment by yuwenmemon** [comment] 2023-12-08 00:54
Unable to reproduce on staging from 3 different engineers so removing the label. Keeping the issue open though!

**Comment by stitesExpensify** [comment] 2023-12-13 19:05
Still unable to reproduce. Closing.

**Closed by stitesExpensify** 2023-12-13 19:05 UTC
Labels: Engineering, Daily, Overdue
