### ISSUE TITLE
Web - Task messages in Spanish are copied to clipboard in English

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26621] opened 2023-09-03 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging and from preferences change the language to Spanish
2. Create a task and assign someone to it
3. Click the task to open it
4. Click a bunch of times on the complete task check box
5. Notice the task system messages being in spanish
6. Hover over one of the task system messages and copy to clipboard
7. Paste the copied message to the composer and notice it's pasted in English

## Expected Result:
The pasted message should be in Spanish since we are already translating all these messages and making them available for the front end

## Actual Result:
The messages are pasted in English which is inconsistent since they are being viewed in Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2f8404c3-7d1b-4876-8624-715b16643378

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AmjedNazzal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693265369973669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-09-03 20:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task messages in Spanish are copied to clipboard in English
### What is the root cause of that problem?
Inconsistent between two text, the displayed text is the translated for actionName + task title, but the copied text is the originalMessage html
### What changes do you think we should make in order to solve the problem?
We need to copy **the translated for actionName + task title** instead of originalMessage html 





```javascript
function getTaskStatusMessageText(actionName, reportID) {
    let taskStatusText = '';
    switch (actionName) {
        case CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED:
            taskStatusText = Localize.translateLocal('task.messages.completed');
            break;
        case CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED:
            taskStatusText = Localize.translateLocal('task.messages.canceled');
            break;
        case CONST.REPORT.ACTIONS.TYPE.TASKREOPENED:
            taskStatusText = Localize.translateLocal('task.messages.reopened');
            break;
        default:
            taskStatusText = Localize.translateLocal('task.task');
    }

    return `${taskStatusText} ${allReports[reportID].reportName}`;
}
```


and use it [here](https://github.com/Expensify/App/blob/b226893b81f1e160bef4a6821cee19c8a03bcd24/src/pages/home/report/ContextMenu/ContextMenuActions.js#L190)
```javascript

onPress: (closePopover, {reportAction, selection, reportID}) => {
  // const messageHtml = isTaskAction ? lodashGet(originalMessage, 'html', '') : lodashGet(message, 'html', '');
  const messageHtml = isTaskAction ? ReportActionsUtils.getTaskStatusMessageText(reportAction.actionName, reportID) : lodashGet(message, 'html', '');
```

The function can use also in TaskAction.js
### What alternative solutions did you explore? (Optional)
we can use `reportAction.childReportName`  for task title and create a function in `ReportActionsUtils.js` to get translated value for actionName like the above (taskStatusText part).

**Comment by kbecciv** [comment] 2023-09-03 20:10
## Proposal
AmjedNazzal on GH
### Please re-state the problem that we are trying to solve in this issue.
Task messages in Spanish are copied to clipboard in English
### What is the root cause of that problem?
The root cause here is that we are copying the task messages from the originalMessage html coming from the backend directly which is a problem since the backend only returns English messages for tasks.
https://github.com/Expensify/App/blob/3f9f1e6e2ce91468a536755f8d5830a2f77d7eaa/src/pages/home/report/ContextMenu/ContextMenuActions.js#L190
### What changes do you think we should make in order to solve the problem?
To resolve this issue for this bug and related future bugs we can implement the method in TaskAction.js to start translating these task messages depending on the current language instead of getting it from the backend.
We can start by seperating the logic in TaskAction into a custom hook:
```javascript
export function useGetTaskStatusText(actionName, translateFn) {
    let taskStatusText = '';
    switch (actionName) {
        case CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED:
            taskStatusText = translateFn('task.messages.completed');
            break;
        case CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED:
            taskStatusText = translateFn('task.messages.canceled');
            break;
        case CONST.REPORT.ACTIONS.TYPE.TASKREOPENED:
            taskStatusText = translateFn('task.messages.reopened');
            break;
        default:
            taskStatusText = translateFn('task.task');
    }
    return taskStatusText;
}
```
We can call this hook within TaskAction and within BaseReportActionContextMenu and pass it the actionName and translate hook in order to get the translated message.
Inside of TaskAction:
```javascript
const taskStatusText = useGetTaskStatusText(props.actionName, props.translate);
```
Inside of BaseReportActionContextMenu:
```javascript
const taskActionText = useGetTaskStatusText(props.reportAction.actionName, props.translate)
//Existing code
{_.map(_.filter(ContextMenuActions, shouldShowFilter), (contextAction) => {
    const closePopup = !props.isMini;
    const payload = {
        ..
        taskActionText: taskActionText,
    };
```
Finally we can use it in ContextMenuActions to set the messageHtml:
```javascript
onPress: (closePopover, {reportAction, selection, taskActionText}) => {
..
    const messageHtml = isTaskAction ? taskActionText : lodashGet(message, 'html', '');
```
### Result
https://github.com/Expensify/App/assets/74202751/3f937c54-08c8-440b-a87f-a01699f8ed92

**Comment by trjExpensify** [comment] 2023-09-06 00:09
Reproducible: 

<img width="1130" alt="image" src="https://github.com/Expensify/App/assets/16232057/54c556f3-6e90-40c7-83df-637e4c2051df">

@thienlnam assigning you for input on this one as it could be backend related.

**Comment by thienlnam** [comment] 2023-09-06 18:24
Yeah definitely part of the problem is that the reportAction message is set in the back-end. 

We could do a workaround and fix it in the front-end, or just close and wait until we support localization in the back-end. I don't feel super strongly since it's not really something that will happen often (copying the task system message)

**Comment by trjExpensify** [comment] 2023-09-06 22:50
Are task system message the only ones translated? That's another inconsistency then really, isn't it? Why would we translate "completed task" but not "paid $xxx". 

CC: @JmillsExpensify has this come on your radar in Espanol?

**Comment by trjExpensify** [comment] 2023-09-11 11:16
Okay, I can see the `paid $x.xx` system messages on expense reports are translated. If you click the `Copy to clipboard` button it pastes in English as well: 

https://github.com/Expensify/App/assets/16232057/4822588c-d4c8-495a-ae64-540465e34ceb

So I think the solution to this is more holistic than just on taskReports. 

>We could do a workaround and fix it in the front-end, or just close and wait until we support localization in the back-end. I don't feel super strongly since it's not really something that will happen often (copying the task system message)

It doesn't feel that premium in the meantime, but I think I agree with preferring to hold off until we support localisation on the backend.

**Comment by thienlnam** [comment] 2023-09-12 06:12
Yeah sounds good, let's put this and related issues on hold then until we do back-end localization

**Comment by trjExpensify** [comment] 2023-09-13 13:52
I think we just close it. It's not a bug, it's a limitation of how our implementation of translations work at this time. Once we commit to supporting localisation in the backend, that'll be a project in itself and all of these considerations will be accounted for holistically.

**Closed by trjExpensify** 2023-09-13 13:52 UTC
Labels: Daily, Bug
