### ISSUE TITLE
[HOLD for payment 2023-10-23] Refactor Form to a custom hook

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#25397] opened 2023-08-17 13:54 UTC
# Problem
Although our Form component has been working great so far, the migration to functional components has surfaced some issues with our design. Coming from [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1691676066586829), our existing Form component either causes child functional components with hooks to crash the App or functional components without hooks don't work. Given that we're migrating the whole codebase to use hooks, we need to redesign Form to play nicely with child components with/without hooks.

# Why is this important
We migrated to functional components and we need Form to work with child functional components that have hooks.

# Solution
Redesign Form into a custom hook. This will be worked on by an external agency.

**Comment by luacmartins** [comment] 2023-08-17 13:55
No design changes are necessary here. Removing @shawnborton as an assignee

**Comment by lukemorawski** [comment] 2023-08-17 14:51
Hi it's Lucas from Callstack. Happy to have a go on that one :) I assume, given the app is currently being migrated to TS, this new custom form hook should be written in TS too?

**Comment by luacmartins** [comment] 2023-08-17 14:57
Thanks @lukemorawski! Assigned you to the issue. Writing it in TS sounds good.

**Comment by lukemorawski** [comment] 2023-08-17 15:01
Cool! Thanks @luacmartins. Starting the research :)

**Comment by luacmartins** [comment] 2023-08-17 18:54
Hey @lukemorawski, it seems like another external contributor is already working on this issue. I'll unassign you from it, sorry about the confusion.

**Comment by kowczarz** [comment] 2023-08-18 08:12
Hello, I'm from Software Mansion, and I would like to work on this task.

**Comment by lukemorawski** [comment] 2023-08-18 09:04
@luacmartins Cool, though it was a fun thing to work with :) Good luck!

**Comment by cubuspl42** [comment] 2023-08-18 13:16
Hey! During solving another issue, [we found a warning/error](https://github.com/Expensify/App/pull/24616#issuecomment-1682214824) which has its root in the `Form` component implementation. It appears on more than one screen. Could you check after this refactor if that warning/error is gone?

**Comment by strepanier03** [comment] 2023-08-21 23:44
As BZ, I'll follow this is being done and handle any actions or payment as needed. Feel free to ping me if I missed taking a needed action.

**Comment by luacmartins** [comment] 2023-08-25 16:06
Curious for your thoughts on the proposal above @marcaaron @tgolen

**Comment by tgolen** [comment] 2023-08-25 16:35
Looks kinda neat! Here are some of my initial thoughts:

1. Would there be a `registerX` method for every type of form element? I don't see how the current POC would work with other types of form elements.
2. I don't much care for the `...registerInput()` style and if we could make it look more like a normal component like you suggest, I think that would look nicer and be more approachable
3. Let's definitely avoid third party libs if we can :D

**Comment by marcaaron** [comment] 2023-08-25 23:03
Sorry just skimmed here, but the proposal is to switch to [`react-hook-form`](https://www.react-hook-form.com/)  ?

We considered this actually. There were two downsides:

1. We didn't use hooks.
2. Registering the references was kind of confusing and complicated.

1 is no longer a problem 🎉  
Is the second argument still valid? 

Our existing design looks better to me. But that's just my personal preference. I am more passionate that we have consistent UX practices here. As I briefly mentioned someplace else (Slack maybe) I wouldn't stand in anyone's way if they _really_ want to do this, but not passionate about changing this right now.

**Comment by kowczarz** [comment] 2023-08-28 09:27
@tgolen 
1. No, I would like to provide a generic function/component that will handle any input and I have in mind that the API needs to be TypeScript friendly.
2. I'm also fan of the component approach, but the approach with spreading the function output was the first thought and I came up with the idea with the component after preparing the POC.

@marcaaron 
The second argument is valid, but since we need to get rid of `React.cloneComponent` our API will become similar to the `react-hook-form` one, but anyway we could write an abstraction that will improve the developer experience.

**Comment by luacmartins** [comment] 2023-08-30 18:22
@kowczarz could you work on a POC for the component idea?

**Comment by kowczarz** [comment] 2023-08-31 09:25
Sorry, I was logged into my personal account, but as I told, I will work on this next week.

**Comment by kowczarz** [comment] 2023-09-05 09:32
I've just finished the [POC for component approach](https://github.com/Expensify/App/pull/26746) and now, when I'm looking at it, I like it much more than the one with exposing the register function

**Comment by strepanier03** [comment] 2023-09-05 22:44
Thanks for the update @kowczarz.

**Comment by kowczarz** [comment] 2023-09-06 14:59
@luacmartins do you have any objections to the [second POC](https://github.com/Expensify/App/issues/25397#issuecomment-1706272072), or is it fine so I can proceed with implementation?

And one more thing I would like to clarify, the migration to the new hook don't have to be done in the same PR, is that correct?

**Comment by luacmartins** [comment] 2023-09-07 00:16
I like the second POC a lot. I think we should be good to move to implementation. 

>And one more thing I would like to clarify, the migration to the new hook don't have to be done in the same PR, is that correct?

Correct

**Comment by strepanier03** [comment] 2023-09-11 12:20
Draft of the POC is up and we're making progress. Thanks Melvin.

**Comment by kowczarz** [comment] 2023-09-12 09:04
@luacmartins [the PR](https://github.com/Expensify/App/pull/27025) is ready for review.

**Comment by kowczarz** [comment] 2023-09-12 15:36
We also have to consider what will be the optimal way for the migration, since there are almost 40 old form usages and some of them are in class components. The problem is we can't wait until the end of migration to functional components because it's required in that migration. Additionally there are some components like [AddressForm](https://github.com/Expensify/App/blob/106abf25c3e6f85e22d44aa8abea8c0c2ac60001/src/pages/ReimbursementAccount/AddressForm.js#L94) which will require us to migrate couple components in one PR, or to create a copy of it with the new API, then migrate all usages of the AddressForm and then delete the old one.

**Comment by luacmartins** [comment] 2023-09-13 00:12
That's a good point. I think maybe we would:

1. Have both versions of Form coexist
2. Start migrating the existing functional components to the new Form hook
3. When we only have class components left, migrate those to functional components implementing the new Form hook
4. Remove the old implementation of Form

What do you think?

**Comment by kowczarz** [comment] 2023-09-22 09:30
@luacmartins this sounds good. Additionally I wanted to keep the logic of the new as close as possible with the old one, but with @sebryu we discussed about a of couple places where the form can be improved. I think the best way would be to make a separate PR with these changes after the migration, so in case of a potential regression we will be sure what caused it.

**Comment by luacmartins** [comment] 2023-09-25 00:56
Yea, that makes sense. The refactor PR was merged today, so we can start working on the improvements.

**Comment by kowczarz** [comment] 2023-10-02 15:49
Hey @luacmartins, I'm back from my holidays.

I prepared a PR with Form docs updates: https://github.com/Expensify/App/pull/28627 Should it be assigned to this task, r should we create new one for it?

And here is the list with the components that requires refactor before deleting old `Form` component:
- src/pages/settings/Security/CloseAccountPage.js
- src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js
- src/pages/settings/Profile/PersonalDetails/AddressPage.js
- src/pages/settings/Profile/PersonalDetails/LegalNamePage.js
- src/pages/settings/Profile/Contacts/NewContactMethodPage.js
- src/pages/settings/Profile/CustomStatus/StatusSetPage.js
- src/pages/settings/Wallet/AddDebitCardPage.js
- src/pages/settings/Report/RoomNamePage.js
- src/pages/EditRequestCreatedPage.js
  - src/components/NewDatePicker/index.js used in `DateOfBirthPage` and `MoneyRequestDatePage`
- src/pages/tasks/NewTaskDetailsPage.js
- src/pages/tasks/TaskDescriptionPage.js
- src/pages/tasks/NewTaskTitlePage.js
- src/pages/tasks/NewTaskDescriptionPage.js
- src/pages/tasks/TaskTitlePage.js
- [class] src/pages/AddPersonalBankAccountPage.js
  - src/components/AddPlaidBankAccount.js it's used in `BankAccountPlaidStep` also
- src/pages/PrivateNotes/PrivateNotesEditPage.js
- src/pages/workspace/WorkspaceNewRoomPage.js
- [class] src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js
- [class] src/pages/workspace/WorkspaceInviteMessagePage.js
- src/pages/workspace/WorkspaceSettingsPage.js
- src/pages/iou/MoneyRequestDatePage.js
- src/pages/iou/WaypointEditor.js
- src/pages/iou/MoneyRequestDescriptionPage.js
- src/pages/iou/MoneyRequestMerchantPage.js
- src/pages/EditRequestDescriptionPage.js
- src/pages/TeachersUnite/KnowATeacherPage.js
- src/pages/TeachersUnite/IntroSchoolPrincipalPage.js
- src/pages/EnablePayments/AdditionalDetailsStep.js
  - uses src/pages/ReimbursementAccount/AddressForm.js which is used also by `CompanyStep` and `IdentityForm`
  - src/pages/EnablePayments/IdologyQuestions.js
- src/pages/ReimbursementAccount/ACHContractStep.js
- src/pages/ReimbursementAccount/BankAccountManualStep.js
- src/pages/ReimbursementAccount/RequestorStep.js
  - src/pages/ReimbursementAccount/IdentityForm.js used also in `ACHContactStep` 
- src/pages/ReimbursementAccount/BankAccountPlaidStep.js
- src/pages/ReimbursementAccount/CompanyStep.js
- [class] src/pages/ReimbursementAccount/ValidationStep.js
- src/pages/ReportWelcomeMessagePage.js
- src/pages/EditRequestMerchantPage.js

**Comment by luacmartins** [comment] 2023-10-03 15:09
>I prepared a PR with Form docs updates: https://github.com/Expensify/App/pull/28627 Should it be assigned to this task, r should we create new one for it?

Yes, let's link all related PRs to this issue so we can keep track of them.

>I think that the components are still classes we should refactor to functional and to new form in the same PR, because there are some that depends on the refactor, like this one https://github.com/Expensify/App/issues/25397

That sounds good to me

**Comment by kowczarz** [comment] 2023-10-09 11:46
Hey @luacmartins! With @kosmydel we spotted a new issue in the new form, here is the PR with fix https://github.com/Expensify/App/pull/28821

**Comment by luacmartins** [comment] 2023-10-10 16:53
Thanks for the PR. I assigned myself as a reviewer

**Comment by kowczarz** [comment] 2023-10-24 10:32
Another followup:
We can consider getting rid of of [`setTimeout`](https://github.com/Expensify/App/blob/60576fe3d3a4c91cc33192c01ef213b59a336441/src/components/Form/FormProvider.js#L266-L271) in favour of `blurQueue`, so the behaviour will be more predictable.

**Comment by luacmartins** [comment] 2023-10-24 17:12
That sounds good to me!

**Comment by strepanier03** [comment] 2023-10-24 18:27
Hmm, this should have switched to Daily when the payment date came but I just found this in my weeklies still. 

Is there a payment that needs to happen with this though? The payment summary [comment](https://github.com/Expensify/App/issues/25397#issuecomment-1765339188) shows the only person doesn't need payment. 

I'll keep following along but right now I'm not sure the payment that is due.

**Comment by luacmartins** [comment] 2023-10-27 00:55
Working on the several individual issues

**Comment by luacmartins** [comment] 2023-10-30 16:35
Still working on the many implementation issues!

**Comment by situchan** [comment] 2023-11-02 16:06
@strepanier03 I am eligible for reviewing [PR](https://github.com/Expensify/App/pull/28821).
Can you please pay me and remove HOLD for payment in issue title?

**Comment by luacmartins** [comment] 2023-11-02 21:54
Still working through the multiple individual issues

**Comment by luacmartins** [comment] 2023-11-06 16:54
SWM is still working on these issues

**Comment by strepanier03** [comment] 2023-11-06 17:54
@situchan - Sure I can trace the progress here and handle payment. 

I believe this would be a $500 payment, although I'm not sure why we didn't automatically create a payment GH for the PR. 

----

Payment summary:

- C+ - Payment for https://github.com/Expensify/App/pull/28821 - @situchan  - $500 via Upwork.

**Comment by strepanier03** [comment] 2023-11-06 17:59
I've sent an offer, I'll check later to see if I can pay it.

**Comment by luacmartins** [comment] 2023-11-09 22:02
Pending payment

**Comment by strepanier03** [comment] 2023-11-17 00:15
The payment to @situchan is completed. @luacmartins can we close this now or does this need to stay open for the multiple individual issues you mentioned [here](https://github.com/Expensify/App/issues/25397#issuecomment-1791590786).

If it's ready to be closed go ahead and do that or let me know and I can do it.

**Comment by strepanier03** [comment] 2023-11-17 00:20
Actually going to close this one too. I realized I had another GH for one of the issues you mentioned and paid/closed that one so doing the same here. Feel free to reopen if I did it to early.

**Closed by strepanier03** 2023-11-17 00:20 UTC
Labels: Daily, NewFeature, Awaiting Payment

**Comment by DylanDylann** [comment] 2023-11-27 15:30
@luacmartins Do we have the issue to migrate this one https://github.com/Expensify/App/blob/main/src/components/AddressForm.js

**Comment by DylanDylann** [comment] 2023-11-27 17:14
@luacmartins I just checked the [PR](https://github.com/Expensify/App/pull/30568) that related to the issue you mentioned above but it does not contain the https://github.com/Expensify/App/blob/main/src/components/AddressForm.js

**Comment by luacmartins** [comment] 2023-11-27 17:26
Ah you're right, we refactored ReimbursementAccount/AddressForm in that one, not components/AddressForm. Created a new issue for it [here](https://github.com/Expensify/App/issues/32064)
