### ISSUE TITLE
[$1000]  Dev: Navigation to workspace from room leads to a different page while returning back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21839] opened 2023-06-28 20:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to '+' -> new room
2. add name -> select workspace ( lets say workspace A) here -> pick visibility
3. now on the room 's page , go to header and click on #rooms' name. Now it shows a details page on RHN
4. Now hover to workspace name and click, It will show Workspace page
5. IMPORTANT STEP, now click on settings, on settings page, hit back.
6. Now again click back from the workspace page.
7. Notice that now it shows the list of workspaces.
8. Now on clicking consecutive back, it leads to settings page of profile. i.e we can't back navigate the RHN room's details page.

## Expected Result:
On clicking consecutive back, it should lead to details  page of room i.e we can't back navigate the RHN room's details page.

## Actual Result:
 Navigation to workspace from room leads to a different page while returning back
 
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  DEV(v1.3.32-5) and staging(v1.3.33-3)
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4cb66664-96ef-4fc3-a014-6ae0e0e3fcd1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687880333737179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130170e7fe486522b</li>
        <li>Upwork Job ID: 1676172619682504704</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by ashimsharma10** [comment] 2023-06-29 07:38
Dear all,

Dont miss step 4 ( from actions performed above) . Step 4 & 5 are important !!

**Comment by StevenKKC** [comment] 2023-07-03 17:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking back button after clicking on menu gets back to list of workspace on admins channel.

### What is the root cause of that problem?
If the user clicks on the workspace name on the report detail page, the navigation will create a new item in the `RightModalNavigator` because [`Report_Details_Root`](https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/linkingConfig.js#L229) and [`Workspace_Initial`](https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/linkingConfig.js#L179-L181) are different screens in [`linkingConfig`](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig.js).
Therefore, there are two items in the `RightModalNavigator`.
![Annotation 2023-07-03 070335](https://github.com/Expensify/App/assets/131836113/9ac245e7-d058-491a-9533-88ab4712a53d)

When user click menu, the menu item and workspace initial page are on the same screen in `linkingConfig`, new item will be added to `Workspace_Initial`.
![Annotation 2023-07-03 064710](https://github.com/Expensify/App/assets/131836113/7f6d2b90-e9e5-40ce-92a9-04ba25f1c75a)

When the user clicks the back button, navigation will iterate `Workspace_Settings` screen routes and return 0.
https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/Navigation.js#L45-L61
And since `fallbackRoute` is set, `fallbackRoute` will be navigated accordingly.
https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/Navigation.js#L99-L102

`fallbackRoute` is set to `ROUTES.SETTINGS_WORKSPACES`, so we'll be returned to the list of workspaces.
https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/pages/workspace/WorkspaceInitialPage.js#L197-L197
### What changes do you think we should make in order to solve the problem?
We can modify [this line](https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/Navigation.js#L99) as below.
```js
-   if (shouldEnforceFallback || (!getActiveRouteIndex(navigationRef.current.getState()) && fallbackRoute)) {
+   if (shouldEnforceFallback || (getActiveRouteIndex(navigationRef.current.getState()) == null && fallbackRoute)) {
```

### What alternative solutions did you explore? (Optional)
We can remove `fallbackRoute` in [`WorkspaceInitialPage.js`](https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/pages/workspace/WorkspaceInitialPage.js#L197C96-L197C96).
```js
-   onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES)}
+   onBackButtonPress={() => Navigation.goBack()}
```

* I have posted [my proposal](https://github.com/Expensify/App/issues/22065#issuecomment-1617963920) in [here](https://github.com/Expensify/App/issues/22065).

**Comment by laurenreidexpensify** [comment] 2023-07-04 10:14
Not overdue, reveiwing

**Comment by b4s36t4** [comment] 2023-07-10 04:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Navigation to workspace from room leads to a different page while returning back
### What is the root cause of that problem?
RCA for this issue is navigating from one stack to another stack. As seen in the video, when we click on workspace we're navigating to the user to `Workspace_Initial` which lives in a different stack navigator `SettingsModalStackNavigator` than one of the screen from `ReportDetailsModalStackNavigator`. 

When we do this and when we try to come back we do calculate the `ActiveRouteIndex` https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/Navigation/Navigation.js#L54 here. If it's `0` means we reached the bottom of the navigation.

The logic is straight forward and working good unless if the route is from another stackNavigator it does create problems and because of `activeIndex` is `0` we're going to the fallbackRoute provided into the screen logic which shouldn't happen because the Navigation still holds some screens to goback. 

### What changes do you think we should make in order to solve the problem?
While calculating the activeIndex from https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/Navigation/Navigation.js#L54 this function we should return other `0` if it's a Stack instead of a screen.

```js

const getActiveRouteIndex = function (route, index) {
          // Existing code
          if (route.state && route.state.routes) {
               if(route.state.key.includes("stack"){ // Meaning the screen we're seeing is a stackNavigator
                      return 1; // Do the screen pop (going back)
               }
               const childActiveRoute = route.state.routes[route.state.index || 0];
               return getActiveRouteIndex(childActiveRoute, route.state.index || 0);
          }
          
          // Existing Code
}

```



### What alternative solutions did you explore? (Optional)
NA

**Comment by alitoshmatov** [comment] 2023-07-10 06:38
Duplicate of https://github.com/Expensify/App/issues/20164

**Comment by ashimsharma10** [comment] 2023-07-24 02:35
Updates on this?

**Comment by maddylewis** [comment] 2023-07-24 16:36
@laurenreidexpensify - just checking in to make sure you meant to close this one. there are some recent comments from contributors so i reopened to double-check!

**Comment by laurenreidexpensify** [comment] 2023-07-26 19:06
Sorry I completely missed the notifications here, I closed this in reaction to the dupe [comment](https://github.com/Expensify/App/issues/20164) here, but looks like that was a false positive. Thanks for reopening @maddylewis

**Comment by laurenreidexpensify** [comment] 2023-07-26 19:09
@aimane-chnaif sorry for the delays here - what are you thinking for next steps here?

**Comment by laurenreidexpensify** [comment] 2023-07-31 09:55
@aimane-chnaif bump for the above ^^

**Comment by laurenreidexpensify** [comment] 2023-08-07 15:47
@aimane-chnaif sorry for delay, but I agree with @bernhardoj yes that that is expected behaviour, but am going to tag a few others to confirm:

@zanyrenney @dylanexpensify @twisterdotcom do you agree?

**Comment by laurenreidexpensify** [comment] 2023-08-10 09:12
@zanyrenney @dylanexpensify @twisterdotcom can one of you buddy check and confirm this? Thanks!

**Comment by dylanexpensify** [comment] 2023-08-10 09:33
Yes, will do now @laurenreidexpensify !

**Comment by dylanexpensify** [comment] 2023-08-10 09:36
>Oh, I just realized that previously we were completely unable to go back to the room details and now we can, but yes I expect it to directly go to the room detail page. If we just open the workspace page and not go deeper into its subpages, the issue above won't happen.

Basically, we're missing this step, right? It's going back to all workspaces, not the "newnew" one created in the OP, right? If so, then I agree with the approach from @bernhardoj cc @aimane-chnaif @laurenreidexpensify

**Comment by adamgrzybowski** [comment] 2023-08-11 12:05
I can't create a room but I am assuming that workspaces have a similar flow. Is the recorded behavior as expected?

https://github.com/Expensify/App/assets/67908363/e04de053-1d63-4918-a4f0-810a5e5bf5a4

**Comment by adamgrzybowski** [comment] 2023-08-11 12:21
In theory this should be fixed by this PR https://github.com/Expensify/App/pull/23007

**Comment by laurenreidexpensify** [comment] 2023-08-15 07:30
@aimane-chnaif can you confirm @adamgrzybowski's theory above? Thanks

**Closed** 2023-08-21 09:17 UTC
Labels: Daily, Internal, Needs Reproduction, Bug
