### ISSUE TITLE
[$500] LHN - Banner remains opened when user taps outside the banner.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35583] opened 2024-02-01 17:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Login as new user
3. Note a big banner pops up
4. Tap on outside the banner and try to close it

## Expected Result:
Banner must be closed when user taps outside the banner.

## Actual Result:
Banner remains opened when user taps outside the banner.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/547dd9cc-4756-4dde-aadb-9fda1aec079f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f05f5a4a255e967f</li>
        <li>Upwork Job ID: 1753112755303374848</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-02-01 17:53
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Welcome to expensify banner remains opened when user taps outside the banner.

### What is the root cause of that problem?

Within the `PurposeForUsingExpensifyModal` component, we did not set the Modal's `shouldCloseOnOutsideClick` prop to true.

### What changes do you think we should make in order to solve the problem?

We should set Modal's `shouldCloseOnOutsideClick` prop to `true`.

**Comment by FitseTLT** [comment] 2024-02-01 18:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 LHN - Banner remains opened when user taps outside the banner.

### What is the root cause of that problem?
We are currently displaying modal which doesn't have `closeonClickOutside` feature
https://github.com/Expensify/App/blob/c8679c727db9755404599fa61943d3a36e1a1f68/src/components/PurposeForUsingExpensifyModal.tsx#L139-L156
### What changes do you think we should make in order to solve the problem?

If we need it to close on tap outside we need to use `Popover` instead 
### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-02-01 18:47
## Updated [proposal](https://github.com/Expensify/App/issues/35583#issuecomment-1921894667)
- added more details to RCA and solution + videos

**Comment by ikevin127** [comment] 2024-02-09 11:16
@hoangzinh I've hidden my proposal as I don't have capacity to take on it at the moment.
@tienifr can take this one and use anything useful from my proposal if needed.

**Comment by sonialiap** [comment] 2024-02-14 16:46
Thanks Vinh, closing

**Closed by sonialiap** 2024-02-14 16:46 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
