### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] The selected approver has no background color, and the search input field appears when there are less than 8 members to select

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49575] opened 2024-09-22 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dannymcclain 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726843553984039

## Action Performed:
Prerequisite: Control workspace with 3 members added
1. Go to staging.new.expensify.com
2. On a control workspace enable Workflows in more features 
3. Click Workflows > Add approval workflow
4. select any member
## Expected Result:
The selected approver shows the checkmark, background color and search field only if there are more than 8 members showing.

## Actual Result:
The selected approver shows the checkmark correctly but has no background color and search field displayed for less than 8 members 
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/41f7784e-d87a-4351-85aa-135c0b087ed3

https://github.com/user-attachments/assets/aae484b1-78b1-4b22-9980-0f2c03b234fb

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839025702753796102</li>
        <li>Upwork Job ID: 1839025702753796102</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104344108</li>
<li>truph01 | Contributor | 104344117</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by truph01** [comment] 2024-09-23 10:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The selected approver shows the checkmark correctly but has no background color and search field displayed for less than 8 members

### What is the root cause of that problem?
#### 1. The selected approver shows the checkmark correctly but has no background color.
- Page [WorkspaceWorkflowsApprovalsApproverPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L239) uses ```InviteMemberListItem``` to display its option. That component does not have ```pressableStyle={[[item.isSelected && styles.activeComponentBG]]}``` style:
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/InviteMemberListItem.tsx#L51
as we did in ```TableListItem```:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/TableListItem.tsx#L47

We can observe the ```TableListItem``` behavior in ```WorkspaceMembersPage```, where all the selected options are highlighted.

#### 2. Search field displayed for less than 8 members

- We don't have ```shouldShowTextInput``` prop in:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L239
### What changes do you think we should make in order to solve the problem?
#### 1. The selected approver shows the checkmark correctly but has no background color.

- In this:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/InviteMemberListItem.tsx#L51

we should add:

````
            pressableStyle={[[shouldHighlightSelectedItem && item.isSelected && styles.activeComponentBG]]}
````

The ```shouldHighlightSelectedItem``` is new prop to make sure the change does not break other pages. So in case of ```WorkspaceWorkflowsApprovalsApproverPage```, use ```shouldHighlightSelectedItem``` as ```true```.

#### 2. Search field displayed for less than 8 members
- In this:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L239

add:

```
    const shouldShowTextInput = flatMap(sections, (section) => section.data)?.length >= 8;
```

will fix the issue.

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-09-23 10:58
[Proposal updated](https://github.com/Expensify/App/issues/49575#issuecomment-2367834847)

**Comment by truph01** [comment] 2024-09-23 10:59
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue.
- The selected approver shows the checkmark correctly but has no background color and search field displayed for less than 8 members

### What is the root cause of that problem?
#### 1. The selected approver shows the checkmark correctly but has no background color.
- Page [WorkspaceWorkflowsApprovalsApproverPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L239) uses ```InviteMemberListItem``` to display its option. That component does not have ```pressableStyle={[[item.isSelected && styles.activeComponentBG]]}``` style:
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/InviteMemberListItem.tsx#L51
as we did in ```TableListItem```:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/TableListItem.tsx#L47

We can observe the ```TableListItem``` behavior in ```WorkspaceMembersPage```, where all the selected options are highlighted.

#### 2. Search field displayed for less than 8 members

- We don't have ```shouldShowTextInput``` prop in:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L239
### What changes do you think we should make in order to solve the problem?
#### 1. The selected approver shows the checkmark correctly but has no background color.

- In this:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/InviteMemberListItem.tsx#L51

we should add:

````
            pressableStyle={[[shouldHighlightSelectedItem && item.isSelected && styles.activeComponentBG]]}
````

The ```shouldHighlightSelectedItem``` is new prop to make sure the change does not break other pages. So in case of ```WorkspaceWorkflowsApprovalsApproverPage```, use ```shouldHighlightSelectedItem``` as ```true```.

#### 2. Search field displayed for less than 8 members
2.1 Option 1:
- Create new state to store all the available approver: 
```
const [allApprovers, setAllApprovers] = useState()
const shouldShowTextInput = allApprovers?.length >= 8
```

- In:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L116

call ```setAllApprover(approvers)```.

- Then pass ```shouldShowTextInput={shouldShowTextInput}``` to:
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L239


### What alternative solutions did you explore? (Optional)


2.2 Option 2:
- Note: With this solution, assume we have > 20 available approvers. Now the search input is displayed. Then we search any keyword so that the results 's length is less than 8. The search input is hidden.

- In this:

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L239

add:

```
    const shouldShowTextInput = flatMap(sections, (section) => section.data)?.length >= 8;
```

will fix the issue.

**Comment by abekkala** [comment] 2024-09-25 19:35
@akinwale we already have a couple proposals for review! 🎉

**Comment by abekkala** [comment] 2024-10-01 18:55
@akinwale have you been able to review the proposals above

**Comment by akinwale** [comment] 2024-10-01 23:24
We can move forward with @abzokhattab's [proposal](https://github.com/Expensify/App/issues/49575#issuecomment-2366813177) here.

🎀👀🎀 C+ reviewed.

**Comment by truph01** [comment] 2024-10-02 00:46
@akinwale The selected proposal have a few issues:

> The search input of the approver selector doesn't hide if the policy has fewer than 8 members.

 - With this requirement, it leads to the search input is displayed when the input is empty, and then hidden if the input is not empty.



> The selected approver has no background color.

- With this requirement, the solution only highlights the selected approver when the page is initially loaded. However, I believe the expectation is for the selected approver to remain highlighted consistently, not just upon initial load. cc @dannymcclain since you reported the bug.

**Comment by dannymcclain** [comment] 2024-10-02 13:45
Right, basically any time a list item like this is in the selected state it should have a background color. Think of the checkmark and background color as being **inseparable**.

**Comment by truph01** [comment] 2024-10-02 13:48
@akinwale I believe you should reassess the proposals in light of the above comment.

**Comment by truph01** [comment] 2024-10-03 02:27
@akinwale What do you think about my [thoughts](https://github.com/Expensify/App/issues/49575#issuecomment-2387360938)?

**Comment by abekkala** [comment] 2024-10-04 18:26
@akinwale are you able to address @truph01 [comments](https://github.com/Expensify/App/issues/49575#issuecomment-2387360938)?

**Comment by akinwale** [comment] 2024-10-05 16:09
I will re-evaluate and provide feedback.

**Comment by abekkala** [comment] 2024-10-08 18:36
@akinwale just a friendly bump on this one...

**Comment by carlosmiceli** [comment] 2024-10-09 02:24
Waiting for evaluation from @akinwale

**Comment by akinwale** [comment] 2024-10-09 06:17
@truph01 Could you post a video demo of your solution?

**Comment by truph01** [comment] 2024-10-09 09:51
@akinwale Here is my video demo:


https://github.com/user-attachments/assets/217f61bc-cdb9-4b21-8e57-53de77ae994d

**Comment by akinwale** [comment] 2024-10-09 16:46
After a second review, we can move forward with @truph01's [proposal](https://github.com/Expensify/App/issues/49575#issuecomment-2367880149) here.

cc: @carlosmiceli

**Comment by truph01** [comment] 2024-10-10 05:05
[PR](https://github.com/Expensify/App/pull/50541) is ready

**Comment by abekkala** [comment] 2024-10-11 14:49
I'm going ooo until Oct 18. Given that the PR has not deployed to production yet starting the 7 day waiting period I'm going to keep this assign to only me and I can process payment when I return

### Payment Summary [date, TBD]: 
- Fix: @truph01 [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104344117)
- PR Review: @akinwale [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104344108)

**Comment by abekkala** [comment] 2024-10-24 12:58
### PAYMENT SUMMARY FOR OCT 30

- Fix: @truph01 [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104344117)
- PR Review: @akinwale [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104344108)
please complete checklist above

**Comment by akinwale** [comment] 2024-10-25 15:26
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
_Workspace with fewer than 8 members_
1. Launch Expensify
2. Navigate to the settings of a control workspace with fewer than 8 members.
3. Enable Workflows in more features.
4. Navigate to Workflows > Add approval workflow
5. Select any member
6. Verify that a checkmark is shown beside the selected approver, the selected item has a background colour, and that the search field is not displayed

_Workspace with 8 members or more_
1. Launch Expensify
2. Navigate to the settings of a control workspace with 8 members or more.
3. Enable Workflows in more features.
4. Navigate to Workflows > Add approval workflow
5. Select any member
6. Verify that a checkmark is shown beside the selected approver, the selected item has a background colour, and that the search field is displayed

Do we agree 👍 or 👎?

**Comment by abekkala** [comment] 2024-10-30 15:17
@truph01 and @akinwale - payments sent and contracts ended - thank you! 🎉

**Closed** 2024-10-30 15:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
