### ISSUE TITLE
[HOLD for payment 2022-12-15] [$1000] My own message is prefixed with my name/email at LHN (only for room chats) reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12706] opened 2022-11-14 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a new workspace 
2. Search announce room
3. Send a message
4. Observe the LHN message preview

## Expected result: 
Name/email shouldn't prefixed for your own message like group chats

## Actual result: 
My own message is prefixed with name/email

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/201700676-825897a8-dca6-420c-ba42-344acb3a58ae.mov
<img width="960" alt="Screenshot (99)" src="https://user-images.githubusercontent.com/43996225/201700706-03e58d4b-a6d6-4464-be0a-425d4d7db546.png">
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668369685379099
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01e003307772c7b0fe
- Upwork Job ID: 1597689541572468736

**Comment by JmillsExpensify** [comment] 2022-11-16 04:45
Echoing my comment in the linked issue, I don't think this is a bug. It's our design. We take the front part of any given email (e.g. ABC123@acme.com) and use that to auto-name the workspace to ABC123. We can look into changing this in the future, though I think this is a feature request for now and we should close the issue.

**Comment by thesahindia** [comment] 2022-11-16 09:55
C/P my comment from slack here-

I did some research and I am sure this is a bug. We are getting lastActorDetails from personalDetailMap ( which is accessing report.participants ) if the lastActorDetails is available we prefix the last message with email at LHN if it's not available we will only see the message (without email as prefix) This logic works correctly for group chats because report.participants doesn't contain the current user's details that's why our own message doesn't get prefixed with the email. We are seeing this issue for rooms because for rooms we include the current user's details in report.participants
Code:-
https://github.com/Expensify/App/blob/6456bec297da828806bd7a48d55e99870d025dc6/src/libs/SidebarUtils.js#L250
https://github.com/Expensify/App/blob/6456bec297da828806bd7a48d55e99870d025dc6/src/libs/actions/Report.js#L69

**Comment by JmillsExpensify** [comment] 2022-11-18 08:37
@muttmuure Let's get this one going!

**Comment by muttmuure** [comment] 2022-11-22 13:28
On it, sorry!

**Comment by muttmuure** [comment] 2022-11-22 13:58
I can reproduce - I'm not sure why this is a problem but I follow the logic of the posters above

**Comment by muttmuure** [comment] 2022-11-25 17:02
Not overdue

**Comment by muttmuure** [comment] 2022-11-28 12:28
@tylerkaraszewski can we add external?

**Comment by JalalMitali** [comment] 2022-11-29 22:10
**Proposal :** 
let's add another condition to check if the chat is an announce room if so let's return only the report message without the display name and it's working! I
```diff
 --git a/src/libs/SidebarUtils.js b/src/libs/SidebarUtils.js
index b0932f85b1..58a78fe376 100644
--- a/src/libs/SidebarUtils.js
+++ b/src/libs/SidebarUtils.js
@@ -220,7 +220,7 @@ function getOptionData(reportID) {
     const personalDetailMap = OptionsListUtils.getPersonalDetailsForLogins(report.participants, personalDetails);
     const personalDetailList = _.values(personalDetailMap);
     const personalDetail = personalDetailList[0] || {};
-
+    result.isAnnounceRoom = ReportUtils.isAnnounceRoom(report);
     result.isChatRoom = ReportUtils.isChatRoom(report);
     result.isArchivedRoom = ReportUtils.isArchivedRoom(report);
     result.isPolicyExpenseChat = ReportUtils.isPolicyExpenseChat(report);
@@ -266,7 +266,11 @@ function getOptionData(reportID) {
         });
     }
 
-    if (result.isChatRoom || result.isPolicyExpenseChat) {
+    if(result.isAnnounceRoom) {
+        result.alternateText =  lastMessageTextFromReport;
+        ;
+    }
+    else if (result.isChatRoom || result.isPolicyExpenseChat) {
         result.alternateText = lastMessageText || subtitle;
     } else {
         if (hasMultipleParticipants && !lastMessageText) {
```
<img width="1792" alt="Screenshot 2022-11-29 at 23 09 11" src="https://user-images.githubusercontent.com/88791252/204659169-13757a40-9efb-4896-acdd-93c8553e15b9.png">

**Comment by JalalMitali** [comment] 2022-11-29 22:11
@JmillsExpensify can you please take a look at this solution so if it's not how we should fix it I will make some changes as long as I am working on this one **thanks**!

**Comment by JmillsExpensify** [comment] 2022-11-29 23:20
Ah let's have @mananjadhav take the first round of feedback on this proposal. Thanks!

**Comment by mananjadhav** [comment] 2022-11-30 03:17
Thanks for the proposals here. I liked @daraksha-dk's second [proposal](https://github.com/Expensify/App/issues/12706#issuecomment-1314061634) of removing the current user email from the `report.participants` when initializing `personalDetailsMap` .

@tylerkaraszewski All yours

🎀 👀 🎀 
C+ reviewed

**Comment by JalalMitali** [comment] 2022-11-30 09:35
my [proposal](https://github.com/Expensify/App/issues/12706#issuecomment-1331385114) requires minimal changes without modifying anything else in the logic it's just one condition that already exists in `ReportUtils` ( which is `isAnnounceRoom` ) but if we need to remove the user email and we will never need it later then I don't know 🤷‍♂️

**Comment by PauloGasparSv** [comment] 2022-11-30 18:02
Taking this over @tylerkaraszewski @mananjadhav

**Comment by daraksha-dk** [comment] 2022-11-30 18:06
@PauloGasparSv, I have already proposed a solution which was [approved](https://github.com/Expensify/App/issues/12706#issuecomment-1331593547).

**Comment by JalalMitali** [comment] 2022-11-30 18:11
> Taking this over @tylerkaraszewski @mananjadhav

all in good hands 🙌 please inform us with the next steps and chosen proposal thanks! 🙏

**Comment by PauloGasparSv** [comment] 2022-11-30 18:53
I think we should move forward with the first suggestion from @daraksha-dk since it adds the least amount of logic and we generally don't want to show the user's own email/name prefixed in any case.
@daraksha-dk could you please make a P.R. with those changes?

@JalalMitali I also think your proposal looks good and would work but it adds a bit more logic (to be specific to the Annouce room which is great but I don't think it's required this time). Thank you very much for the proposal!

@mananjadhav would love to hear your opinion on this and on why you liked the second suggestion from @daraksha-dk more, I think it is a very good solution but the first one is easier to read and understand at a glance so it will be easier for other engineers to find and modify in the future.

**Comment by daraksha-dk** [comment] 2022-11-30 21:14
Created a draft. The website isn't working smoothly (just loading or new message doesn't show)so I wasn't able to test this thoroughly. I will open this after testing once the problem gets resolved.

**Comment by mananjadhav** [comment] 2022-12-08 03:44
@PauloGasparSv @muttmuure Need help here. I was the assigned C+ here, and I reviewed the proposal. But it seems the PR got assigned to @aimane-chnaif. I didn't get any notification so I didn't review it.

How do we handle the compensation here.

**Comment by PauloGasparSv** [comment] 2022-12-08 14:43
Hey @mananjadhav, I talked to the team and this was probably a bug that was recently resolved where the P.R. reviewer was not assigned correctly.

In this case, would you and @aimane-chnaif be fine with halving the C+ bounty between you both?

**Comment by mananjadhav** [comment] 2022-12-09 02:21
I think what happened here is I was assigned C+ first when the proposals were reviewed, then we removed the External label. That's when I got unassigned (and got missed from my tracker too).

I think we should split this is 75/25. 75% to @aimane-chnaif because PR review requires more effort.

**Comment by daraksha-dk** [comment] 2022-12-20 17:57
@muttmuure, I have applied to the job.

**Comment by muttmuure** [comment] 2022-12-21 11:24
Suggested adding a regression step here https://expensify.slack.com/archives/C01SKUP7QR0/p1671621870001619

**Comment by muttmuure** [comment] 2022-12-21 11:34
@daraksha-dk @mananjadhav have been hired

@aimane-chnaif @thesahindia need to apply here https://www.upwork.com/jobs/~01e003307772c7b0fe

**Comment by thesahindia** [comment] 2022-12-21 12:11
Applied, thanks!

**Comment by mananjadhav** [comment] 2022-12-22 21:09
@muttmuure Quick bump on this one. This is due for payout

**Comment by muttmuure** [comment] 2022-12-23 21:56
@daraksha-dk @mananjadhav have been paid

@aimane-chnaif @thesahindia have been hired

**Comment by daraksha-dk** [comment] 2022-12-24 19:53
@muttmuure - I didn't get the 50% bonus (the PR was merged within 3 days)

**Comment by mallenexpensify** [comment] 2022-12-29 18:05
Wow, a rare 4 hires for a job.  I'm gonna help sort this out.  I appears that
@daraksha-dk compensation should be $1500 w/ bonus. Already paid $1000, I bonused $500 today - DONE
@thesahindia compensation should be $250 - Paid today - DONE
@aimane-chnaif already paid $1000
@mananjadhav already paid $750 

**For timeliness bonus**
- @daraksha-dk [hired on Nov 30](https://github.com/Expensify/App/issues/12706#issuecomment-1332624941)
- [PR merged on Dec 1](https://github.com/Expensify/App/pull/13212#event-7934634606)

FWIW @muttmuure , I'd recommend documenting the amounts due before paying and provide reasoning for any not-normal issues like this.  The confusing bit is C+ compensation.  What I think is fair is 
@mananjadhav $250 for proposal review - no bonus cuz bonuses are for timeliness of PR review and merge timeliness
@aimane-chnaif $1250 - $750 for PR review (since Manan got $250 for proposal review) and $500 for bonus. 

@mananjadhav and @aimane-chnaif do you agree? If so I'll update the payments to both of you.

**Comment by mananjadhav** [comment] 2022-12-30 01:20
@mallenexpensify I think one way would be to make it 500 and 500 for the proposal revjew and PR review. The whole bonus goes to @aimane-chnaif.

But I am fine with anything.

**Comment by mallenexpensify** [comment] 2022-12-30 01:25
I was basing the 25/75 split off your comment
> I think we should split this is 75/25. 75% to @aimane-chnaif because PR review requires more effort.

**Comment by mananjadhav** [comment] 2022-12-30 01:31
Sorry got confused with the issues(using phone). Yes for this issue correct. Because there weren’t many proposals to review. So no heavy lifting on that side. 

You’re right. 25/75 is good here (but can’t be a standard, as there might be cases where proposal review can take days through multiple conversations).

again sorry for the confusion

**Comment by mallenexpensify** [comment] 2022-12-30 21:39
Thanks @mananjadhav .  I agree the 25/75 is **not** a standard. 
I requested $500 refund from you @mananjadhav (so total paid will be $250)
I bonused @aimane-chnaif another $250, total paid is now $1250. 

And... closing!

**Closed by mallenexpensify** 2022-12-30 21:39 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug

**Comment by mananjadhav** [comment] 2022-12-31 01:09
Processed the refund from my side.
