### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Room-Description with mentions shown in preview but after saved disappeared

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49407] opened 2024-09-18 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a room chat
3. Tap header -- description
4. Enter description with mention and save it eg : #233

## Expected Result:
Description with mentions shown in preview and must be displayed after saved also.

## Actual Result:
Description with mentions shown in preview but after saved shown briefly and disappears.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7e15c3c8-e364-4359-9eeb-97990b375cf6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836660554703667076</li>
        <li>Upwork Job ID: 1836660554703667076</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104326440</li>
<li>truph01 | Contributor | 104326443</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by IuliiaHerets** [comment] 2024-09-18 17:44
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment] 2024-09-19 01:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Description with mentions shown in preview but after saved shown briefly and disappears.

### What is the root cause of that problem?
- ```shouldParseTitle``` is not added in this:

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/ReportDetailsPage.tsx#L729

while the description returned by BE is something like ```#description```.
### What changes do you think we should make in order to solve the problem?
- We should update that ```MenuItemWithTopDescription``` to:

````diff
+                          <MentionReportContext.Provider value={mentionReportContextValue}>
                                <MenuItemWithTopDescription
+                                  shouldParseTitle
-                                  shoudlRenderAsHTML
+                                 excludedMarkdownRules={!policy ? ['reportMentions'] : []}
                                />
+                          </MentionReportContext.Provider>
````
````diff
+  const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
````


### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-09-19 02:13
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue.
- Description with mentions shown in preview but after saved shown briefly and disappears.

### What is the root cause of that problem?
- When we save description ```"#123xxx"```, we sent to BE ```"<mention-report>#123xxx</mention-report>"``` but BE returns ```"#123xxx"```.


- And ```shouldParseTitle``` is not added in this:

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/ReportDetailsPage.tsx#L729

while the description returned by BE is something like ```#description```.
### What changes do you think we should make in order to solve the problem?
- We need to make sure when we send to BE ```"<mention-report>#123xxx</mention-report>"```, BE returns ```"#123xxx"``` as well.
- Then, update:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/ReportDetailsPage.tsx#L729

````diff
+                          <MentionReportContext.Provider value={mentionReportContextValue}>
                                <MenuItemWithTopDescription
                                    ...
+                                 excludedMarkdownRules={!policy ? ['reportMentions'] : []}
                                />
+                          </MentionReportContext.Provider>
````
````diff
+  const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
````


### What alternative solutions did you explore? (Optional)



#### Fix the description preview
- We should update that ```MenuItemWithTopDescription``` to:

````diff
+                          <MentionReportContext.Provider value={mentionReportContextValue}>
                                <MenuItemWithTopDescription
+                                  shouldParseTitle
-                                  shoudlRenderAsHTML
+                                 excludedMarkdownRules={!policy ? ['reportMentions'] : []}
                                />
+                          </MentionReportContext.Provider>
````
````diff
+  const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
````

#### Fix the description's form
- Next, we need to fix the ```RoomDescriptionPage``` so that it will send the markdown data to BE instead of HTML.

- First, update:

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/RoomDescriptionPage.tsx#L36

```
    const [description, setDescription] = useState(report?.description ?? '');
```
- Last, update:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/libs/actions/Report.ts#L2053
```
    const parsedDescription = Parser.htmlToMarkdown(ReportUtils.getParsedComment(newValue, {reportID}));
```

**Comment by truph01** [comment] 2024-09-19 02:16
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.
- Description with mentions shown in preview but after saved shown briefly and disappears.

### What is the root cause of that problem?
- When we save description ```"#123xxx"```, we sent to BE ```"<mention-report>#123xxx</mention-report>"``` but BE returns ```"#123xxx"``` - a MD string.


- And ```shouldParseTitle``` is not added in this:

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/ReportDetailsPage.tsx#L729

while the description returned by BE is a MD string.
### What changes do you think we should make in order to solve the problem?
- We need to make sure when we send to BE ```"<mention-report>#123xxx</mention-report>"```, BE returns ```"<mention-report>#123xxx</mention-report>"``` as well. It needs to be fixed on BE side.

- Then, update:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/ReportDetailsPage.tsx#L729

````diff
+                          <MentionReportContext.Provider value={mentionReportContextValue}>
                                <MenuItemWithTopDescription
                                    ...
+                                 excludedMarkdownRules={!policy ? ['reportMentions'] : []}
                                />
+                          </MentionReportContext.Provider>
````
````diff
+  const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
````


### What alternative solutions did you explore? (Optional)



#### Fix the description preview
- We should update that ```MenuItemWithTopDescription``` to:

````diff
+                          <MentionReportContext.Provider value={mentionReportContextValue}>
                                <MenuItemWithTopDescription
+                                  shouldParseTitle
-                                  shoudlRenderAsHTML
+                                 excludedMarkdownRules={!policy ? ['reportMentions'] : []}
                                />
+                          </MentionReportContext.Provider>
````
````diff
+  const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
````

#### Fix the description's form
- Next, we need to fix the ```RoomDescriptionPage``` so that it will send the markdown data to BE instead of HTML.

- First, update:

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/RoomDescriptionPage.tsx#L36

```
    const [description, setDescription] = useState(report?.description ?? '');
```
- Last, update:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/libs/actions/Report.ts#L2053
```
    const parsedDescription = Parser.htmlToMarkdown(ReportUtils.getParsedComment(newValue, {reportID}));
```

**Comment by truph01** [comment] 2024-09-19 04:32
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.
- Description with mentions shown in preview but after saved shown briefly and disappears.

### What is the root cause of that problem?
- When we save description ```"#123xxx"```, we sent to BE ```"<mention-report>#123xxx</mention-report>"``` but BE returns ```"#123xxx"``` - a MD string.


- And ```shouldParseTitle``` is not added in this:

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/ReportDetailsPage.tsx#L729

while the description returned by BE is a MD string.
### What changes do you think we should make in order to solve the problem?
- We need to make sure when we send to BE ```"<mention-report>#123xxx</mention-report>"```, BE returns ```"<mention-report>#123xxx</mention-report>"``` as well. It needs to be fixed on BE side.

- Then, update:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/ReportDetailsPage.tsx#L729

````diff
+                          <MentionReportContext.Provider value={mentionReportContextValue}>
                                <MenuItemWithTopDescription
                                    ...
+                                 excludedMarkdownRules={!policy ? ['reportMentions'] : []}
                                />
+                          </MentionReportContext.Provider> 
````
````diff
+  const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
````
to make sure the ```reportMentions``` markdown is only applied if the current report belongs to policy.

- Last, update:

https://github.com/Expensify/App/blob/ace39e86b7f6a5015f1cc5722f8b739ff99ebab9/src/pages/RoomDescriptionPage.tsx#L82

```
                            excludedMarkdownStyles={isReportInGroupPolicy ? ['mentionReport'] : []}
```
with:

```
    const isReportInGroupPolicy = !!report?.policyID && report.policyID !== CONST.POLICY.ID_FAKE;
```

to make sure the ```reportMentions``` markdown is only applied if the current report belongs to policy.
### What alternative solutions did you explore? (Optional)



#### Fix the description preview
- We should update that ```MenuItemWithTopDescription``` to:

````diff
+                          <MentionReportContext.Provider value={mentionReportContextValue}>
                                <MenuItemWithTopDescription
+                                  shouldParseTitle
-                                  shoudlRenderAsHTML
+                                 excludedMarkdownRules={!policy ? ['reportMentions'] : []}
                                />
+                          </MentionReportContext.Provider>
````
````diff
+  const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
````

#### Fix the description's form
- Next, we need to fix the ```RoomDescriptionPage``` so that it will send the markdown data to BE instead of HTML.

- First, update:

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/RoomDescriptionPage.tsx#L36

```
    const [description, setDescription] = useState(report?.description ?? '');
```
- Last, update:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/libs/actions/Report.ts#L2053
```
    const parsedDescription = Parser.htmlToMarkdown(ReportUtils.getParsedComment(newValue, {reportID}));
```

**Comment by FitseTLT** [comment] 2024-09-19 14:18
This is not a bug. If we mention a correct room the BE sets the description to the mention of that room and it is a correct clickable mention but if the BE doesn't get a room with that name it will consider it a normal text so the mention will disappear. In compose we have a option to deal with this case with a whisper message explaining that the room doesn't exist and ask if the user wants to create it but in this case I think it is unnecessary.

**Comment by truph01** [comment] 2024-09-19 17:07
@greg-schroeder Can you confirm the expected behavior here? In the preview, should we always highlight the text ```#any-text```, or we just highlight it if ```#any-text``` in the reportName of the existing report?

**Comment by truph01** [comment] 2024-09-19 17:33
[Proposal updated](https://github.com/Expensify/App/issues/49407#issuecomment-2359955382)

**Comment by truph01** [comment] 2024-09-23 03:55
@greg-schroeder Can you confirm [this comment](https://github.com/Expensify/App/issues/49407#issuecomment-2361698472)?

**Comment by dubielzyk-expensify** [comment] 2024-09-26 00:49
Looks like this is an issue on the main intro chat message too:

https://github.com/user-attachments/assets/98ba6f89-715e-4232-93da-8da834401a38

Since we respect all other forms of mention (user name) and links (urls), I kinda feel like we should respect the room mentions too, but it being unhighlighted makes me wonder if this is a deliberate decisions. Let's loop in @JmillsExpensify , @trjExpensify and @dannymcclain to hear if they know why this is happening. Otherwise I'd say that we should respect the mention of other rooms in the same way we do URLs and users.

![CleanShot 2024-09-26 at 10 47 32@2x](https://github.com/user-attachments/assets/ffcc6734-6e20-41cb-8851-419bcb8ef615)

**Comment by truph01** [comment] 2024-09-26 00:55
@dubielzyk-expensify FYI, we only highlight ```#xxx``` if ```xxx``` refers to an existing room. Otherwise, it's treated as regular text. The chat message serves as the correct reference for use in other sections.

**Comment by dubielzyk-expensify** [comment] 2024-09-26 01:10
Ahh right. I see what you mean. I don't think this is a huge deal then, but if we can understand that this isn't actually a room before we save and preview it, then that'd be ideal. So that we don't end up with this flicker

**Comment by truph01** [comment] 2024-09-26 01:20
> if we can understand that this isn't actually a room before we save and preview it, then that'd be ideal. So that we don't end up with this flicker

Yeah, my solution follows this approach.

**Comment by dannymcclain** [comment] 2024-09-26 14:00
>if we can understand that this isn't actually a room before we save and preview it, then that'd be ideal. So that we don't end up with this flicker

Totally agree. 👍

**Comment by truph01** [comment] 2024-10-05 14:43
@rayane-djouah The test branch [here](https://github.com/Expensify/App/compare/main...truph01:App:fix/49407)

**Comment by truph01** [comment] 2024-10-07 19:38
> Is it possible to also fix the bug related to the room description on the report page and to the set the room description to: action message using the same approach?


- I believe it's possible, but doing so would expand the scope of the issue.

- In general, we need to update the function:

https://github.com/Expensify/App/blob/fb4e24eca0905c8dec0c6dc69b4758aa66f2a791/src/libs/ReportUtils.ts#L4164

Currently, we only set ```disabledRules```: ```reportMentions``` if it is not policy report:

https://github.com/Expensify/App/blob/fb4e24eca0905c8dec0c6dc69b4758aa66f2a791/src/libs/ReportUtils.ts#L4181

that leads to the bug you mentioned above. To fix it, we need to make sure we also set ```disabledRules```: ```reportMentions``` if the mention data has a corresponding report ID.

**Comment by truph01** [comment] 2024-10-09 08:00
[PR](https://github.com/Expensify/App/pull/50490) is ready

**Comment by greg-schroeder** [comment] 2024-10-14 21:48
@rayane-djouah is up for review!

**Comment by greg-schroeder** [comment] 2024-10-25 09:33
Payment summary:

Contributor: @truph01 - $250 via Upwork
C+: @rayane-djouah - $250 via Upwork

**Closed by greg-schroeder** 2024-10-25 09:33 UTC
Labels: External, Weekly, Awaiting Payment, Bug
