### ISSUE TITLE
Thread - __fake__ member in thread for message in WS chat of Removed member

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20050] opened 2023-06-02 12:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot
2. Invite a member
3. Send a messages in WS chat
4. Create a thread for this message
5. Remove this member from workspace
6. WS chat is archived but thread stays in LHN
7. Go to thread chat and check members in settings

## Expected Result:
no fake accounts should be displayed

## Actual Result:
__fake__ member in thread for message in WS chat of Removed member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dfdf334c-79c2-4aeb-98d6-bc00d220435a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107070ca2f72b0d39</li>
        <li>Upwork Job ID: 1666100406786818048</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-06-06 15:11
@thienlnam This is looking Internal to me. Can you correct me and switch it to External if you think that's wrong?

**Comment by thienlnam** [comment] 2023-06-08 20:44
I can't reproduce on main anymore - closing!

**Closed by thienlnam** 2023-06-08 20:44 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
