### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Expense - Payment options displayed before submitting in thread created inside details page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41519] opened 2024-05-02 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4534255
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Open workspace chat
4. Submit an expense
5. Open expense details page
6. Send a message
7. Hover over the sent message and click on reply in thread

## Expected Result:
The expense preview component inside the thread doesn't show options to pay the expense

## Actual Result:
There are options to pay the expense on the expense preview component inside the thread and when clicked shows an RBR

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3c5a9f02-95a9-42da-8de4-64eced1f3b28

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01140896862273d9dc</li>
        <li>Upwork Job ID: 1787962387841482752</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>kmbcook | Contributor | 102440887</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger / @sakluger / @lschurr</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @sakluger / @lschurr</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @sakluger</details>

**Comment by izarutskaya** [comment] 2024-05-02 17:07
We think this issue might be related to the #vip-vsb.

**Comment by sakluger** [comment] 2024-05-03 15:45
I'm OOO today and Monday - assigning another BZ team member to help triage. I can take back over on Tuesday.

**Comment by kmbcook** [comment] 2024-05-03 19:06
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Payment options displayed before submitting in thread created inside details page

### What is the root cause of that problem?
The root cause stems from https://github.com/Expensify/App/pull/34640 where ReportUtils.getAllAncestorReportActions was written. That function returns an array of ancestors. The problem is that each ancestor in the array contains the incorrect report; the report action is correct, but the report is not the report which contains the action; instead it is the report created by the action.

### What changes do you think we should make in order to solve the problem?
Fix ReportUtils.getAllAncestorReportActions so that each ancestor contains the correct report, the one that contains the report action.

**Comment by sakluger** [comment] 2024-05-13 09:24
Hey @thesahindia, could you please take a look at the proposals that have been posted so far?

**Comment by sakluger** [comment] 2024-05-14 11:29
I'm going to re-assign another C+ to keep this one moving.

**Comment by sakluger** [comment] 2024-05-14 11:30
@rushatgabhane when you get a chance, please take a look at the proposals we've received so far. Thanks!

**Comment by kmbcook** [comment] 2024-05-20 18:52
This issue is currently hidden by https://github.com/Expensify/App/pull/40983, which no longer allows report preview actions to be displayed as ancestor actions. However, the problem I identified in my proposal still exists.

**Comment by rushatgabhane** [comment] 2024-05-20 20:29
reviewing

**Comment by rushatgabhane** [comment] 2024-05-21 16:12
hmm im a bit confused here.

I can see payment optin for the IOU -
![image](https://github.com/Expensify/App/assets/29673073/34527566-f781-49bb-9c8e-27314abb1170)

**Comment by kmbcook** [comment] 2024-05-21 21:08
The reproduction steps can be a little confusing, because there are two different kinds of submit buttons. The first is to create the expense. The second is to label the expense as submitted. Step 4 means to create the expense. After it is created a report preview will show in the the chat with a submit button in the preview. Don't press that submit button. The video shows the problem well. In the video you can see the parent action with the option to pay, even though the expense has not yet been marked as submitted.

**Comment by mvtglobally** [comment] 2024-05-22 04:40
Issue not reproducible during KI retests. (First week)

**Comment by rushatgabhane** [comment] 2024-05-22 14:19
> In the video you can see the parent action with the option to pay, even though the expense has not yet been marked as submitted

ahh yeah that's a good point! I agree that we need to fix this 👍

**Comment by rushatgabhane** [comment] 2024-05-22 16:05
> but the report is not; it is the report created by the action, but it should be the report containing the action


https://github.com/Expensify/App/blob/387ab0edd9d2c01c2a0be72950490c94b1b7d9d9/src/libs/ReportUtils.ts#L6171-L6175

@kmbcook what should the ancestor reportAction be replaced with `parentReport` ?

For nested threads, shouldn't the parent of a reportAction be the `parentReportAction`?
eg: consider this thread

Report_1
1. ReportAction_top_level
        1. ReportAction_nested

**Comment by kmbcook** [comment] 2024-05-22 16:39
Ancestor report should be replaced with `parentReport`, like this:
```
 allAncestors.push({ 
     report: parentReport, 
     reportAction: parentReportAction, 
     shouldDisplayNewMarker: isParentReportActionUnread, 
 }); 
```
We want each ancestor to reference the report and the action belonging to that report which is the action which created the child report.

**Comment by rushatgabhane** [comment] 2024-05-22 16:53
C+ reviewed 🎀👀🎀

I like @kmbcook's proposal - https://github.com/Expensify/App/issues/41519#issuecomment-2093608757

**Comment by kmbcook** [comment] 2024-05-23 21:14
@rushatgabhane PR https://github.com/Expensify/App/pull/42554 is ready

**Comment by rushatgabhane** [comment] 2024-05-27 23:03
testing in progress. this can cause regressions so being extra careful

**Comment by kmbcook** [comment] 2024-06-12 01:04
This issue actually has yet to be fully resolved, since the original PR was reverted due to regressions. In that PR I suggested that we keep the PR and fix the regressions, since the PR actually fixes a previous error.

[In one of the regressions](https://github.com/Expensify/App/issues/43175#issuecomment-2161300789) @dangrous suggested that I go ahead with my plan to keep the changes in the original PR and fix the regressions, which I am doing now.

The steps for reproducing this issue are no longer relevant because report preview actions are no longer displayed as a parent action in a thread. The root cause of this issue still exists, which causes inconsistency and confusion in the code.

I am raising a new PR which reinstates the changes of the original PR, and fixes the regressions. The purpose of doing so is to clean up the code.

**Comment by kmbcook** [comment] 2024-06-12 15:56
@rushatgabhane @dangrous https://github.com/Expensify/App/pull/43518 is ready.

**Comment by sakluger** [comment] 2024-06-18 18:10
I removed the payment hold since the new PR, https://github.com/Expensify/App/pull/43518, is still open.

@dangrous do you need to review that one too?

**Comment by dangrous** [comment] 2024-06-18 20:13
Yeah I think once @rushatgabhane gives it a look I'll review - and if the original team on the PR that was reverted wants to take over, they can do that too...

**Comment by sakluger** [comment] 2024-06-21 23:01
PR is still in review.

**Comment by puneetlath** [comment] 2024-07-01 18:42
@rushatgabhane @kmbcook how's this going?

**Comment by kmbcook** [comment] 2024-07-01 19:26
@puneetlath could you add me (kevincook13@gmail.com) to the travel beta? That will help me to see a problem which @rushatgabhane has pointed out.

**Comment by puneetlath** [comment] 2024-07-01 20:34
Added. It might take a couple hours for you to see it.

**Comment by kmbcook** [comment] 2024-07-02 17:03
@rushatgabhane I am on the travel beta now, but I am stuck.

When I attempt to book travel, I accept the terms of service and an AcceptSpotnanaTerms API call is made. The response is "507 Spotnana error". It looks like I need to wait until this error is resolved.

**Comment by sakluger** [comment] 2024-07-03 15:10
Another user ran into this same error here: https://github.com/Expensify/Expensify/issues/409744. It's an internal repo so you won't be able to view the issue @kmbcook, but linking your case will hopefully help us troubleshoot the issue.

**Comment by kmbcook** [comment] 2024-07-03 16:22
@sakluger there is something unusual about the state my account is currently in. When I create a new workspace there is no free trial. If I log in as another user, such as kevincook13+3@gmail.com, and create a new workspace then there is a free trial. If you add kevincook13+3@gmail.com to the travel beta I will check to see if that solves my Spotnana error issue.

**Comment by rushatgabhane** [comment] 2024-07-08 18:56
@kmbcook i've added your account [kevincook13@gmail.com](mailto:kevincook13@gmail.com) to a control policy. So maybe you can use that?

**Comment by sakluger** [comment] 2024-07-08 22:35
Thanks @rushatgabhane! @kmbcook let me know if you still need to be added to the travel beta.

**Comment by kmbcook** [comment] 2024-07-09 03:00
Thanks @rushatgabhane. Unfortunately, I'm still stuck. Here is what I am seeing:

On old dot
- Default workspace is set to Control Policy
- Book travel and accept terms
- API call is made to https://www.expensify.com/api/AcceptSpotnanaTerms?.
- Response is "507 Spotnana error"
- The page displays "Oops... an error has occurred!"

On staging
- Book travel and accept terms
- API call is made to https://staging.expensify.com/api/AcceptSpotnanaTerms?
- Response is OK and a spotnanaToken is returned.
- A new window opens.
- The URL search parameter of the new window contains an authorization code.
- The new window makes a call to https://api-ext-sboxmeta.partners.spotnana.com/v2/auth/token/companies/ sending the authorization code.
- That call returns "An invalid request was made."
- The new page displays "Expensify Travel  Something went wrong. Please try again"

**Comment by rushatgabhane** [comment] 2024-07-13 00:11
hmm, can you try booking a flight using oldDot?

1. staging.expenisfy.com
2. click travel from left hand side bar

**Comment by kmbcook** [comment] 2024-07-13 18:12
@rushatgabhane on staging.expenisfy.com I can start booking a flight, but then I get this error. 

![Screenshot 2024-07-13 at 11 53 14 AM](https://github.com/user-attachments/assets/e6577469-ea4c-4244-82a8-a4637424dfcc)

**Comment by rushatgabhane** [comment] 2024-07-13 19:03
okay that should be working and you're able to access the travel website

**Comment by kmbcook** [comment] 2024-07-14 02:46
I am able to move forward now. Thanks!

**Comment by kmbcook** [comment] 2024-07-15 20:09
Moving this conversation back to https://github.com/Expensify/App/pull/43518.

**Comment by kmbcook** [comment] 2024-07-23 20:08
PR is being reviewed.

**Comment by kmbcook** [comment] 2024-07-31 18:37
PR is being reviewed.

**Comment by sakluger** [comment] 2024-08-05 22:17
PR is still being reviewed.

**Comment by sakluger** [comment] 2024-08-07 16:46
The PR was merged yesterday!

**Comment by sakluger** [comment] 2024-08-19 16:35
Summarizing payment on this issue:

Contributor: @kmbcook $250, paid via Upwork
Contributor+: @rushatgabhane $250, please request on Newdot 

@rushatgabhane please complete the BZ checklist.

**Comment by rushatgabhane** [comment] 2024-08-21 21:45
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by sakluger** [comment] 2024-08-21 21:53
Thanks! I created the GH issue for new regression test steps.

**Closed by sakluger** 2024-08-21 21:53 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-22 09:07
$250 approved for @rushatgabhane
