### ISSUE TITLE
[$250] [Track Tax] Scan - Tax amount is 0.00 after scanning is complete when tax is not 0%

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43995] opened 2024-06-19 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4641717
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Taxes feature is enabled.
- Default tax rate is not 0%.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a scan expense with a valid receipt.
4. Wait for the scanning to complete.
5. Go to transaction thread.

## Expected Result:
Tax amount will be computed after the scanning is complete as the tax is not 0%.

## Actual Result:
Tax amount is 0.00 after the scanning is complete when the tax is not 0%.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7367bdc5-822b-4ef8-bcbf-6da51330e93b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127c88dbca703b410</li>
        <li>Upwork Job ID: 1803423227187261952</li>
        <li>Last Price Increase: 2024-06-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by izarutskaya** [comment] 2024-06-19 13:18
We think this issue might be related to the #collect project.

**Comment by trjExpensify** [comment] 2024-06-19 13:43
CC: @MonilBhavsar 👀

**Comment by MonilBhavsar** [comment] 2024-06-19 14:19
👍 Assigned. From the video, since we're displaying an error considering the correct tax amount. Looks like a bug in displaying the tax amount

**Comment by VickyStash** [comment] 2024-06-20 14:26
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by MonilBhavsar** [comment] 2024-06-20 14:43
Would be great, thanks!

**Comment by VickyStash** [comment] 2024-06-20 15:58
That's what I see as for now:
- `transaction.taxAmount` field value is used to display the tax value on the screen mentioned in the issue.
- `transaction.taxAmount` has `0` in Onyx.

It feels like the right `taxAmount` should be returned by the API after SmartScan.
<img width="1469" alt="Ex1" src="https://github.com/Expensify/App/assets/23176449/a9a13772-07e1-4d7b-840f-ffb18a928b89">

**Comment by VickyStash** [comment] 2024-06-21 08:52
> That's what I see as for now:
> 
> * `transaction.taxAmount` field value [is used](https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/ReportActionItem/MoneyRequestView.tsx#L134) to display the tax value on the screen mentioned in the issue.
> * `transaction.taxAmount` has `0` in Onyx.
> 
> It feels like the right `taxAmount` should be returned by the API after SmartScan.
> 
> <img alt="Ex1" width="1469" src="https://private-user-images.githubusercontent.com/23176449/341480847-a9a13772-07e1-4d7b-840f-ffb18a928b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjAyNDYsIm5iZiI6MTcxODk1OTk0NiwicGF0aCI6Ii8yMzE3NjQ0OS8zNDE0ODA4NDctYTlhMTM3NzItMDdlMS00ZDdiLTg0MGYtZmZiMThhOTI4Yjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA4NTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWExZTQ2MjY2NTBmNGRjNzlkMGRhZmY3YzMzYjRlYTBmOTYwNmFjMjQ0N2Q3OTNmMmVmZjg0MjI0NmNmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jji3y967pH3CRuSQ3JP5CW15QcjZt0o1JPA4T0E9KZk">

@allroundexperts Does it makes sense to you?

**Comment by VickyStash** [comment] 2024-06-23 19:59
Note: I'll be OOO on Monday (24.06) 🌴

**Comment by allroundexperts** [comment] 2024-06-23 20:36
> > That's what I see as for now:
> > 
> > * `transaction.taxAmount` field value [is used](https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/ReportActionItem/MoneyRequestView.tsx#L134) to display the tax value on the screen mentioned in the issue.
> > * `transaction.taxAmount` has `0` in Onyx.
> > 
> > It feels like the right `taxAmount` should be returned by the API after SmartScan.
> > <img alt="Ex1" width="1469" src="https://private-user-images.githubusercontent.com/23176449/341480847-a9a13772-07e1-4d7b-840f-ffb18a928b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjAyNDYsIm5iZiI6MTcxODk1OTk0NiwicGF0aCI6Ii8yMzE3NjQ0OS8zNDE0ODA4NDctYTlhMTM3NzItMDdlMS00ZDdiLTg0MGYtZmZiMThhOTI4Yjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA4NTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWExZTQ2MjY2NTBmNGRjNzlkMGRhZmY3YzMzYjRlYTBmOTYwNmFjMjQ0N2Q3OTNmMmVmZjg0MjI0NmNmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jji3y967pH3CRuSQ3JP5CW15QcjZt0o1JPA4T0E9KZk">
> 
> @allroundexperts Does it makes sense to you?

Yep. Are we optimistically updating it though?

**Comment by VickyStash** [comment] 2024-06-25 07:43
> Yep. Are we optimistically updating it though?

@allroundexperts Could you clarify what do you mean? When we use `Scan` option, we don't know the amount of money that will be detected in the receipt, so we can't optimistically calculate the `tax` amount.

**Comment by trjExpensify** [comment] 2024-06-26 12:42
^^ I agree with that. @allroundexperts can you clarify the question?

**Comment by allroundexperts** [comment] 2024-06-26 13:41
Ah, my bad. I did not take into account that this was a scan request.

**Comment by VickyStash** [comment] 2024-06-26 17:34
So it looks like the issue should be fixed on the API side - the tax amount should be calculated based on the detected amount during SmartScan and the right value should be returned to the app.
I can prepare a formal Proposal tomorrow.

**Comment by VickyStash** [comment] 2024-06-28 09:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tax amount is 0.00 after a Scan expense receipt scanning is completed when tax is set to 5%.

### What is the root cause of that problem?
The `transaction.taxAmount` field value [is used](https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/ReportActionItem/MoneyRequestView.tsx#L134) to display the tax value on the transaction thread screen view.
After the receipt scanning is completed the API returns the scanned information - amount, merchant. But the `transaction.taxAmount` has `0` in Onyx.

![image](https://github.com/Expensify/App/assets/23176449/fb1599ee-d5eb-43cd-9667-cbe0d607a654)


### What changes do you think we should make in order to solve the problem?
Since we initially don't know the amount of money in the receipt we can't optimistically calculate the `taxAmount`. The right `taxAmount` should be calculated and returned by the API after SmartScan is completed.

**Comment by trjExpensify** [comment] 2024-06-28 19:38
Is this a backend issue then, @MonilBhavsar?

**Comment by trjExpensify** [comment] 2024-07-01 09:49
Question for @MonilBhavsar above still stands, Melv.

**Comment by MonilBhavsar** [comment] 2024-07-01 10:29
Hey Tom! I'm going to be ooo until July 8th Monday. Can we please reassign or I can start working on this July 9th onwards

**Comment by trjExpensify** [comment] 2024-07-04 17:43
@MonilBhavsar will tackle it next week, Melv. Chill!

**Comment by trjExpensify** [comment] 2024-07-08 18:40
@MonilBhavsar you're back, right? :excited:

**Comment by MonilBhavsar** [comment] 2024-07-09 07:33
Yes, I'm back. I'll take the ownership and start working on it. 🙇

**Comment by MonilBhavsar** [comment] 2024-07-12 14:19
I spent some time setting up smart scan locally and investigating. I estimate to have PR in review early next week

**Comment by MonilBhavsar** [comment] 2024-07-15 12:59
^Working on a PR, soon.

**Comment by MonilBhavsar** [comment] 2024-07-17 14:48
Submitted PR for review

**Comment by MonilBhavsar** [comment] 2024-07-23 13:05
The automated tests are somehow failing on the github actions only and not locally. I am debugging the workflow 😭

**Comment by MonilBhavsar** [comment] 2024-07-26 07:21
The issue is fixed. I retested and worked fine.

**Closed by MonilBhavsar** 2024-07-26 07:21 UTC
Labels: Reviewing, Daily, Internal, Bug
