### ISSUE TITLE
Legal last name field gives error when clicking on the save btn, but don't give us an error when click on and out of it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24218] opened 2023-08-07 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and Settings > Profile > Personal details > Legal name
2. When you click on and out of the dirst field you are given an error but not given with second field. But there is error for second field when clicking on the save btn
## Expected Result: 
Legal last name field should give us an error when click on and out of it
## Actual Result: 
Legal last name field gives error when clicking on the save btn, but don't give us an error when click on and out of it

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/66252b04-0078-4fd3-a281-ac06c062e7bd

[screen-capture (71).webm](https://github.com/Expensify/App/assets/43996225/525baf0f-badb-40f6-9f3c-ccbced3c0fc9)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690889073145779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alphaboss1104** [comment] 2023-08-07 16:32
I agree with @hungvu193 's opinion.

**Comment by alphaboss1104** [comment] 2023-08-07 17:00
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error is shown as soon as app is put in background when creating a task.
### What is the root cause of that problem?

https://github.com/Expensify/App/blob/7b13f1123301f4783f630aa39af582a4d0dc6a1d/src/components/Form.js#L310-L318

In the above code `onValidate`function invoked follow by `shouldValidate`. And `shouldValidate`'s value is related to `lastValidatedValues`. 

When click on and out `legaFirstName` TextInput field `lastValidatedValues` is set as like this:
```{legalFirstName:'', legalLastName:''}```

https://github.com/Expensify/App/blob/7b13f1123301f4783f630aa39af582a4d0dc6a1d/src/components/Form.js#L151-L153

And then when we click on and out `legalLastName` TextInput field, `onValidate` function isn't invoked because `inputValues` and `lastValidatedValues.current` has same value and `shouldValidate` is `fasle`

This is the root cause of this problem.

It is independent of which TextInput field is clicked first.

### What changes do you think we should make in order to solve the problem?

To solve this issue we should set the `lastValidatedValues` with only clicked TextInput field.

```
            if (isAtLeastOneInputTouched) {
-                lastValidatedValues.current = values;
+                lastValidatedValues.current = values.inputID;
            }
```
### What alternative solutions did you explore? (Optional)

None

**Comment by lschurr** [comment] 2023-08-07 22:16
@eVoloshchak @techievivek - Do you agree this is a regression and should be placed on hold?

**Comment by techievivek** [comment] 2023-08-08 08:25
Yes, this looks like a regression from the PR https://github.com/Expensify/App/pull/23306(cc @joh42 @eVoloshchak), I think we can put this on HOLD for now.

**Comment by lschurr** [comment] 2023-08-08 16:45
Cool. Should we close or just put on hold?

**Comment by techievivek** [comment] 2023-08-10 04:40
We have reverted the original fix https://github.com/Expensify/App/issues/21838#issuecomment-1672542172 so we can close this now.

**Closed by techievivek** 2023-08-10 04:40 UTC
Labels: Daily, Bug
