### ISSUE TITLE
[HOLD for payment 2023-07-20] [$250] Migrate BankAccountManualStep.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16241] opened 2023-03-20 08:50 UTC
### Filenames
- [ ] [src/pages/ReimbursementAccount/BankAccountManualStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/BankAccountManualStep.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b077f22da76198c</li>
        <li>Upwork Job ID: 1673398854972256256</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-04-13 21:39
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by alitoshmatov** [comment] 2023-06-06 10:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate BankAccountManualStep.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should refactor [src/pages/ReimbursementAccount/BankAccountManualStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/BankAccountManualStep.js) to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by muxriddinmuqimov77** [comment] 2023-06-07 02:52
I'd like to work on this.

**Comment by Vishrut19** [comment] 2023-06-26 18:33
Can I work on it ??

**Comment by payal-lathidadiya** [comment] 2023-06-26 18:34
dibs?

**Comment by BhuvaneshPatil** [comment] 2023-06-26 18:55
Open to work on this one

**Comment by olexyt** [comment] 2023-06-26 18:59
I would like to work on this.

**Comment by wahaha999** [comment] 2023-06-26 19:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate BankAccountManualStep.js to function component

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
Here is the functional component migrated.
```
import React from 'react';
import {Image} from 'react-native';
import lodashGet from 'lodash/get';
import HeaderWithBackButton from '../../components/HeaderWithBackButton';
import CONST from '../../CONST';
import * as BankAccounts from '../../libs/actions/BankAccounts';
import Text from '../../components/Text';
import TextInput from '../../components/TextInput';
import styles from '../../styles/styles';
import CheckboxWithLabel from '../../components/CheckboxWithLabel';
import TextLink from '../../components/TextLink';
import withLocalize from '../../components/withLocalize';
import * as ValidationUtils from '../../libs/ValidationUtils';
import ONYXKEYS from '../../ONYXKEYS';
import exampleCheckImage from './exampleCheckImage';
import Form from '../../components/Form';
import shouldDelayFocus from '../../libs/shouldDelayFocus';
import ScreenWrapper from '../../components/ScreenWrapper';
import StepPropTypes from './StepPropTypes';

const propTypes = {
    ...StepPropTypes,
};

const BankAccountManualStep = props => {

    const validate = values => {
        const errorFields = {};
        const routingNumber = values.routingNumber && values.routingNumber.trim();

        if (
            !values.accountNumber ||
            (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) && !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim()))
        ) {
            errorFields.accountNumber = 'bankAccount.error.accountNumber';
        } else if (values.accountNumber === routingNumber) {
            errorFields.accountNumber = props.translate('bankAccount.error.routingAndAccountNumberCannotBeSame');
        }
        if (!routingNumber || !CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(routingNumber) || !ValidationUtils.isValidRoutingNumber(routingNumber)) {
            errorFields.routingNumber = 'bankAccount.error.routingNumber';
        }
        if (!values.acceptTerms) {
            errorFields.acceptTerms = 'common.error.acceptTerms';
        }

        return errorFields;
    }

    const submit = values => {
        BankAccounts.connectBankAccountManually(
            lodashGet(props.reimbursementAccount, 'achData.bankAccountID') || 0,
            values.accountNumber,
            values.routingNumber,
            lodashGet(props, ['reimbursementAccountDraft', 'plaidMask']),
        );
    }

    const shouldDisableInputs = Boolean(lodashGet(props.reimbursementAccount, 'achData.bankAccountID'));

    return (
        <ScreenWrapper includeSafeAreaPaddingBottom={false}>
            <HeaderWithBackButton
                title={props.translate('workspace.common.connectBankAccount')}
                stepCounter={{step: 1, total: 5}}
                shouldShowGetAssistanceButton
                guidesCallTaskID={CONST.GUIDES_CALL_TASK_IDS.WORKSPACE_BANK_ACCOUNT}
                onBackButtonPress={props.onBackButtonPress}
            />
            <Form
                formID={ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM}
                onSubmit={submit}
                validate={validate}
                submitButtonText={props.translate('common.continue')}
                style={[styles.mh5, styles.flexGrow1]}
            >
                <Text style={[styles.mb5]}>{props.translate('bankAccount.checkHelpLine')}</Text>
                <Image
                    resizeMode="contain"
                    style={[styles.exampleCheckImage, styles.mb5]}
                    source={exampleCheckImage(props.preferredLocale)}
                />
                <TextInput
                    autoFocus
                    shouldDelayFocus={shouldDelayFocus}
                    inputID="routingNumber"
                    label={props.translate('bankAccount.routingNumber')}
                    defaultValue={props.getDefaultStateForField('routingNumber', '')}
                    keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
                    disabled={shouldDisableInputs}
                    shouldSaveDraft
                    shouldUseDefaultValue={shouldDisableInputs}
                />
                <TextInput
                    inputID="accountNumber"
                    containerStyles={[styles.mt4]}
                    label={props.translate('bankAccount.accountNumber')}
                    defaultValue={props.getDefaultStateForField('accountNumber', '')}
                    keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
                    disabled={shouldDisableInputs}
                    shouldSaveDraft
                    shouldUseDefaultValue={shouldDisableInputs}
                />
                <CheckboxWithLabel
                    style={styles.mt4}
                    inputID="acceptTerms"
                    LabelComponent={() => (
                        <Text>
                            {props.translate('common.iAcceptThe')}
                            <TextLink href={CONST.TERMS_URL}>{props.translate('common.expensifyTermsOfService')}</TextLink>
                        </Text>
                    )}
                    defaultValue={props.getDefaultStateForField('acceptTerms', false)}
                    shouldSaveDraft
                />
            </Form>
        </ScreenWrapper>
    );
}

BankAccountManualStep.propTypes = propTypes;
export default withLocalize(BankAccountManualStep);
```

### What alternative solutions did you explore? (Optional)

**Comment by dayana7204** [comment] 2023-06-27 20:38
I am ready to work on this ticket :)

**Comment by marcaaron** [comment] 2023-06-27 23:12
@thienlnam did you mean to unassign everyone from this issue?

**Comment by thienlnam** [comment] 2023-06-27 23:16
Yikes - no I just meant to unassign shawn my bad

**Comment by thienlnam** [comment] 2023-07-03 19:25
@Vishrut19 Any update on the PR here?

**Comment by Vishrut19** [comment] 2023-07-03 19:27
Not overdue and also draft PR is ready. The final pr will be ready by tomorrow

**Comment by Vishrut19** [comment] 2023-07-03 19:28
Sorry for some delay because of my health issues @thienlnam

**Comment by Vishrut19** [comment] 2023-07-04 11:23
How to navigate to this page? @thienlnam

**Comment by vdem0115** [comment] 2023-07-04 15:49
@Vishrut19 
1. go to settings.
2. click the workspaces
3. create a workspace or click the already created workspace
4. click the Reimbursements
5. click the Connect Bank Account
6. click the Connect Manually
Please make sure you must set the currency as USD in workspace settings

**Comment by Vishrut19** [comment] 2023-07-05 03:36
I didn't receive offer for this on upwork. Someone please send

**Comment by Vishrut19** [comment] 2023-07-05 05:26
> @Vishrut19
> 
> 1. go to settings.
> 2. click the workspaces
> 3. create a workspace or click the already created workspace
> 4. click the Reimbursements
> 5. click the Connect Bank Account
> 6. click the Connect Manually
>    Please make sure you must set the currency as USD in workspace settings.
>    I just wanted to help you.

Truely appreciate it

**Comment by gadhiyamanan** [comment] 2023-07-05 05:39
@Vishrut19 is assigned to two migration issues ( https://github.com/Expensify/App/issues/16305 and https://github.com/Expensify/App/issues/16241 )at the same time 

@Vishrut19 I think you have to inform if you already assigned to another migration issue 

cc: @parasharrajat @thienlnam

**Comment by Vishrut19** [comment] 2023-07-05 05:41
I know but I have already completed this migration of bank account issue

**Comment by gadhiyamanan** [comment] 2023-07-05 05:42
> I know but I have already completed this migration of bank account issue

I don't see any merged PR for BankAccountManualStep.js

**Comment by Vishrut19** [comment] 2023-07-05 05:43
I am signing it on gpg and raising the PR

**Comment by gadhiyamanan** [comment] 2023-07-05 05:45
if you already know at a time time of the assignment in that case you have to inform C+ reviewer

**Comment by Vishrut19** [comment] 2023-07-05 06:41
How to Test this https://github.com/Expensify/App/pull/22245 PR for different devices?

**Comment by Vishrut19** [comment] 2023-07-05 07:06
> 1. Go to any workspace from Settings.
> 2. Click `Connect Bank account`.
> 3. Choose `connect manually` option.
> 
> Rest you can find the page related to `BankAccountManualStep` and navigate to it.

done and working perfectly fine for web but facing lot of issues to setup and run on other devices like android and stuff

**Comment by Vishrut19** [comment] 2023-07-05 07:52
The draft pr is ready just attaching the ss

**Comment by Vishrut19** [comment] 2023-07-05 18:03
Someone please review this PR https://github.com/Expensify/App/pull/22245

**Comment by Vishrut19** [comment] 2023-07-06 12:38
Hey ! I haven't received any offer on upwork and raised PR as well. Please send that too

**Comment by maddylewis** [comment] 2023-07-06 15:55
### Payments:
- [ ] $250 to @Vishrut19 
- [ ] $250 to @parasharrajat 

@parasharrajat - were you automatically sent an offer in Upwork for this one? lmk - thanks!

**Comment by Vishrut19** [comment] 2023-07-06 16:01
> ### Payments:
> * [ ]  $250 to @Vishrut19
> * [ ]  $250 to @parasharrajat
> 
> @parasharrajat - were you automatically sent an offer in Upwork for this one? lmk - thanks!

I haven't received offer and payment as well @maddylewis

**Comment by maddylewis** [comment] 2023-07-07 14:37
@Vishrut19 - yep, i understsand. you will be manually sent an offer in Upwork.

**Comment by Vishrut19** [comment] 2023-07-07 14:52
I have accepted your offer @maddylewis 

> @Vishrut19 - yep, i understsand. you will be manually sent an offer in Upwork.
> 
> offer sent to @Vishrut19

**Comment by Vishrut19** [comment] 2023-07-07 15:03
Received the payment. Thanks a lot! @maddylewis

**Comment by maddylewis** [comment] 2023-07-07 17:55
@Vishrut19 - as a heads up, payment should only be issued once a PR is finished/merged and there are no regressions (if applicable). 

before bumping an issue for payment in the future, please keep that timeline in mind - thanks!

**Comment by Vishrut19** [comment] 2023-07-07 17:56
Thanks for the heads up @maddylewis

**Comment by Vishrut19** [comment] 2023-07-07 17:57
> Thanks for the heads up @maddylewis



> @Vishrut19 - as a heads up, payment should only be issued once a PR is finished/merged and there are no regressions (if applicable).
> 
> before bumping an issue for payment in the future, please keep that timeline in mind - thanks!

Thanks for the heads up and letting me know this @maddylewis

**Comment by maddylewis** [comment] 2023-07-19 19:26
payment due tomorrow so moving to daily to make sure all the to-dos are completed 👍

**Comment by maddylewis** [comment] 2023-07-21 16:54
withdrew offer in Upwork. i think we're good to close this one since @parasharrajat will be paid via NewDot.

**Closed by maddylewis** 2023-07-21 16:54 UTC
Labels: External, Engineering, Daily, Improvement, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-07-27 05:08
Reviewed details for @parasharrajat. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
