### ISSUE TITLE
[HOLD for payment 2024-10-25] Migrate changes in `react-native-qrcode-svg-old` to `react-native-qrcode-svg`

### ISSUE THREAD

**Issue by grgia** [Expensify/App#47711] opened 2024-08-20 13:16 UTC
See https://expensify.slack.com/archives/C01GTK53T8Q/p1724159312329299?thread_ts=1697098846.087309&cid=C01GTK53T8Q

## Background 
- We took ownership of react-native-qrcode-svg and renamed our fork  react-native-qrcode-svg-old
- We had pushed changes to our fork and app has dependencies on these changes so this can be a breaking change

## Goal
- Let's point to old fork for now - https://github.com/Expensify/App/issues/47713
- Look at our forked changes and decide if any of them would be useful to the open source community
- Create a path forward to fully deprecate react-native-qrcode-svg-old

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by grgia** [comment] 2024-08-20 13:23
cc @Kicu - Do you think someone else from SWM would be interested in looking into this? Otherwise I can extend out to one of our other agencies

**Comment by grgia** [comment] 2024-08-20 17:56
Posted in SWM https://expensify.slack.com/archives/C04878MDF34/p1724176578092919

**Comment by Kicu** [comment] 2024-08-22 13:22
CC @grgia @luacmartins

**Comment by luacmartins** [comment] 2024-08-22 14:54
Agree with that. Let's do it.

**Comment by Kicu** [comment] 2024-08-23 10:35
PR that adds the Example app: https://github.com/Expensify/react-native-qrcode-svg/pull/206
Unsure who is responsible now for reviewing and merging this - is it anyone working in Expensify? I can call on some friends that work on Open Source in SWM to also take a look at the PR if you guys want it.

Will followup soon with another PR that adds the SVG changes that we need in Expensify App

**Comment by Kicu** [comment] 2024-08-23 13:50
I also have the SVG changes nicely cleaned up with like 2 extra commits locally, so I will open the 2nd PR with the SVG code on Monday, and this issue should be solved :)

**Comment by luacmartins** [comment] 2024-08-23 14:23
Nice! Thank you ❤️

**Comment by grgia** [comment] 2024-08-23 20:28
Thank you @Kicu !

**Comment by Kicu** [comment] 2024-08-26 12:15
And here is the SVG changes PR: https://github.com/Expensify/react-native-qrcode-svg/pull/207 - I tested via the (now built in) Example app and svg's still work correctly.

Also here is a super simple fix to Example App web version: https://github.com/Expensify/react-native-qrcode-svg/pull/209 please merge this one as well 🙏 - it requires no testing

**Comment by luacmartins** [comment] 2024-08-26 21:51
Merged both PRs

**Comment by luacmartins** [comment] 2024-08-27 16:00
I think we should go with a new release and then bump App. I'll check on how we can release this repo

**Comment by luacmartins** [comment] 2024-08-27 16:46
I created this PR to add a workflow to automatically publish the lib to npm - https://github.com/Expensify/react-native-qrcode-svg/pull/210

**Comment by Kicu** [comment] 2024-08-28 06:59
@luacmartins cool, nice job.

Just wanted to make sure that you intended to push to git a file called `.github/OSBotify-private-key.asc.gpg`? asking since it has private-key in the name 😅

**Comment by luacmartins** [comment] 2024-08-28 14:56
Yes, that key is required for the workflow to work. It's encrypted though and we have the same in our other repos.

**Comment by bfitzexpensify** [comment] 2024-09-06 15:11
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: being worked on.

**Comment by Kicu** [comment] 2024-09-09 07:38
Update:
this main part of the task:
> Migrate changes in react-native-qrcode-svg-old to react-native-qrcode-svg

is basically done, as all the code required to have on `main` in `react-native-qrcode-svg`. The only part we're missing is to have nice and clean dependencies is to release a new version of `react-native-qrcode-svg` and then use this new version in app.

**Comment by luacmartins** [comment] 2024-09-10 15:08
We ran into some issues with the automated workflow and we need to fix that first.

**Comment by dubielzyk-expensify** [comment] 2024-09-19 01:31
Any updates?

**Comment by Kicu** [comment] 2024-09-19 08:17
just wanted to suggest that we could do one release with the new updates manually just once. That would allow us to update `package.json` to a specific version, and close this issue.

Meanwhile the work to add automated workflow for releasing can be done separately.

**Comment by luacmartins** [comment] 2024-09-19 22:55
I pinged someone to look into the branch rules for the new repo, hopefully we can get this fixed soon.

**Comment by slafortune** [comment] 2024-09-23 15:54
Since you are back, I'll unassign myself @bfitzexpensify

**Comment by grgia** [comment] 2024-09-30 10:08
@luacmartins do you have an update on https://github.com/Expensify/App/issues/47711#issuecomment-2362338394

**Comment by luacmartins** [comment] 2024-09-30 15:45
Yea, we solved the branch rules but now we have the npm auth issue we were [discussing in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1727701099277309?thread_ts=1697098846.087309&cid=C01GTK53T8Q)

**Comment by grgia** [comment] 2024-10-14 05:00
bumped in slack

**Comment by Kicu** [comment] 2024-10-15 07:15
Is there any way I can help with this one?

**Comment by luacmartins** [comment] 2024-10-15 19:07
It seems like we still have permissions issues with npm. Asking infra if they have npm package access so we can update the permissions

**Comment by luacmartins** [comment] 2024-10-15 23:32
We published the latest version 6.3.11 to npm. Let's update App.

**Comment by Kicu** [comment] 2024-10-16 06:42
nice 👍 I can take care of that

**Comment by Kicu** [comment] 2024-10-16 10:27
@luacmartins @grgia this PR updates the version in `App` https://github.com/Expensify/App/pull/50875

**Comment by bfitzexpensify** [comment] 2024-10-25 11:55
This is back-end work that QA won't touch, so I don't see the need for a regression test. 

Payment not needed. Closing this out.

**Closed by bfitzexpensify** 2024-10-25 11:55 UTC
Labels: Daily, NewFeature, Awaiting Payment
