### ISSUE TITLE
[$250] Room - Old room name is displayed in the header until page refresh

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12143] opened 2022-10-26 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and on 2 devices and login with Expensifail accounts
2. Create room with both accounts in the room
3. Under one account change room name
4. Check room name under the other account

## Expected Result:
New room name of the room should be displayed in the header

## Actual Result:
Old room name is displayed in the header until page refresh

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.19.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198060126-881fd523-22b8-4ac6-b877-440e43313a59.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adeel0202** [comment] 2022-10-27 12:28
Hi. I was just about to report a bug where I'm not able to see the archived room's workspace name after deleting the workspace, but then I saw this issue. I think both these issues are related so I'm just reporting it here.


https://user-images.githubusercontent.com/13783842/198283918-525ca7be-20e1-41ea-9c98-2a662bb34129.mp4

**Comment by furkanuzundev** [comment] 2022-10-27 13:17
Guys, can someone tell me how to create a room? I want to deal with this bug.

**Comment by Santhosh-Sellavel** [comment] 2022-10-27 13:37
> Hi. I was just about to report a bug where I'm not able to see the archived room's workspace name after deleting the workspace, but then I saw this issue. I think both these issues are related and will have the same fix so I'm just reporting it here.
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/13783842/198283918-525ca7be-20e1-41ea-9c98-2a662bb34129.mp4
> 
> 
> 
> 

We have other issue raised by you already https://github.com/Expensify/App/issues/11895 that will/should be handled there.

**Comment by adeel0202** [comment] 2022-10-27 13:44
> We have other issue raised by you already https://github.com/Expensify/App/issues/11895 that will/should be handled there.

I don't think this is related to https://github.com/Expensify/App/issues/11895. https://github.com/Expensify/App/issues/11895 is about an extra/unnecessary archived room that appears after deleting the workspace and it just stays there. However, the one I reported [here](https://github.com/Expensify/App/issues/12143#issuecomment-1293453215) is about the room name that disappears after the workspace deletion and then re-appears after page refresh, so it is more likely related to this one.

**Comment by NicMendonca** [comment] 2022-10-27 17:29
Upwork job posting: https://www.upwork.com/jobs/~01b2dd1a5f3c9e6d40

**Comment by tgolen** [comment] 2022-10-28 13:46
@neil-marcellini Does this ring a bell at all?

**Comment by neil-marcellini** [comment] 2022-10-28 15:39
@tgolen it does not "ring a bell" in the sense that I've never seen an issue like this. There was an issue where the name wasn't updating in the side bar, but that was due to the component not updating when the name changed. I'm happy to fix this issue internally if it is indeed a problem with the api as suggested in the last comment https://github.com/Expensify/App/issues/12143#issuecomment-1293973854.

**Comment by tgolen** [comment] 2022-10-28 17:29
OK, thanks. I saw that you added the API call so I thought you might be
able to track this one down pretty quickly. I had a brief look at it, but I
couldn't tell where the pusher message or the data for it was coming from.
Could you please look into that and fix this?

**Comment by tgolen** [comment] 2022-10-31 15:43
@neil-marcellini can you please assign this to yourself and remove the `external` label if you're going to take this and fix it?

**Comment by neil-marcellini** [comment] 2022-11-01 18:39
I confirmed that I can still reproduce the issue on staging. Now I'll reproduce it on dev and work on a solution.

**Comment by neil-marcellini** [comment] 2022-11-01 20:05
Yep I'm seeing the issue pointed out here https://github.com/Expensify/App/issues/12143#issuecomment-1293973854 where the updated reportName is not sent via Pusher. I'll work on a fix for that.

Looking back at the [original issue](https://github.com/Expensify/Expensify/issues/212892) and [design doc](https://docs.google.com/document/d/1C97ih4SDuDdqNTzOfxnuMIEowB1VtmDMrunuNKUfzew/edit#heading=h.h16m8q8o9rr2), we never really considered Pusher and that was a total oversight.

**Comment by neil-marcellini** [comment] 2022-11-01 22:52
The PR is up for review now.

**Comment by sakluger** [comment] 2022-11-02 06:04
@neil-marcellini not sure if it's related, but just in case, [this issue](https://github.com/Expensify/App/issues/12000) looks similar.

**Comment by mvtglobally** [comment] 2022-11-09 03:41
Issue not reproducible during KI retests. (First week)

**Comment by neil-marcellini** [comment] 2022-11-09 17:12
The web fix was deployed to production and QA confirmed it's not reproducible so I'm closing this.

**Comment by neil-marcellini** [comment] 2022-11-09 17:26
@0xmiroslav I will re-assign @NicMendonca to handle the compensation if it's available.

**Comment by NicMendonca** [comment] 2022-11-09 22:17
I am about to go OOO for a week, so re-assigning.

**Comment by maddylewis** [comment] 2022-11-10 17:55
@neil-marcellini - just catching up here! 

is the outstanding request here to pay $250 to @0xmiroslav for this bug fix?

**Comment by neil-marcellini** [comment] 2022-11-10 18:24
@maddylewis, @0xmiroslav [identified](https://github.com/Expensify/App/issues/12143#issuecomment-1293973854) that the problem was on the back end and I fixed the problem myself. He pointed me in the right direction. Does he deserve any payment?

> Question: Is there any bounty for contributors who proposed solution to external issues which require backend fix?
> If yes, it would be very thankful.
> If no, it means contributors are not encouraged to submit proposal which seems backend issue because they won't be compensated?

**Comment by maddylewis** [comment] 2022-11-10 18:37
thank you for that context! let me confirm :)

**Comment by maddylewis** [comment] 2022-11-10 18:45
great news @0xmiroslav - you do get a reporting bonus of $250 for correctly identifying a bug/proposing a fix. 

I will get that payment out to you asap and then post in this issue once that's complete!

**Comment by maddylewis** [comment] 2022-11-14 17:56
@0xmiroslav - will you apply to the job in upwork? https://www.upwork.com/jobs/~01b2dd1a5f3c9e6d40

let me know once you've done that, and then i'll issue the payment - thanks!

**Comment by maddylewis** [comment] 2022-11-14 18:40
payment sent! 

@neil-marcellini - are we good to close this one out now?

**Closed** 2022-11-15 17:36 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
