### ISSUE TITLE
[HOLD for payment 2023-07-28] [HOLD for payment 2023-07-26] [$1000] IOU - No settlement button in the IOU report header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23083] opened 2023-07-18 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22484
## Action Performed:
1. Open staging.new.expensify.com
2. Receive an IOU from user A
3. On user B, click on the IOU request to open the report page

## Expected Result:
On Account B, ensure that the settlement button appears inline with the avatar in the header

## Actual Result:
No settlement button appear at the report header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**

![Bug6132149_22484](https://github.com/Expensify/App/assets/78819774/5a53b534-20e1-4c12-9c58-9013947c13e6)

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b09206b5c6870312</li>
        <li>Upwork Job ID: 1681403325956915200</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-07-18 14:20
This must be coming from here I think https://github.com/Expensify/App/pull/22484

cc @grgia

**Comment by mountiny** [comment] 2023-07-18 14:25
Taking this over, testing locally

**Comment by mountiny** [comment] 2023-07-18 14:29
Works fine for iou and expense reports.

Payer on left, payee on right

<img width="1726" alt="image" src="https://github.com/Expensify/App/assets/36083550/fe379418-c21c-4137-8a07-57a4d08d0227">

**Comment by mountiny** [comment] 2023-07-18 19:51
I can produce now so reopening in case

**Comment by mvtglobally** [comment] 2023-07-18 20:01
@mountiny Not seeing the button with my accounts as well 
![Screen Shot 2023-07-18 at 4 00 58 PM](https://github.com/Expensify/App/assets/43995119/08426da0-b713-4fec-b9af-4a23dafcce62)

**Comment by Nikhil-Vats** [comment] 2023-07-18 20:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - No settlement button in the IOU report header

### What is the root cause of that problem?
We are not showing settlement button on large screens due to the condition `!props.isSmallScreenWidth` -
https://github.com/Expensify/App/blob/a75e329ec4224b1b8ed2ebadba24722253c724a2/src/components/MoneyReportHeader.js#L89-L91

### What changes do you think we should make in order to solve the problem?
We need to show button on all screen sizes so we can remove the `!props.isSmallScreenWidth` from condition in line 88.

### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment] 2023-07-18 20:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - No settlement button in the IOU report header

### What is the root cause of that problem?
We are not rendering children in `HeaderWithBackButton` anymore -
https://github.com/Expensify/App/blob/a75e329ec4224b1b8ed2ebadba24722253c724a2/src/components/HeaderWithBackButton/index.js#L95-L97

This is a regression from [this PR](https://github.com/Expensify/App/pull/21852). They were shown before -
https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/components/HeaderWithBackButton.js#L202-L204

### What changes do you think we should make in order to solve the problem?
We need to destructure `children` from props after line 22 and render them after line 95.

### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment] 2023-07-18 20:25
@Nikhil-Vats Thanks for the proposal, the problem was a mixture of two PRs coming together. The Header componet is missing passing the `children`

**Comment by Nikhil-Vats** [comment] 2023-07-18 20:26
Yes @Nikhil-Vats, just updated the proposal. I will be happy to open a PR for this.

**Comment by mountiny** [comment] 2023-07-18 20:28
@Nikhil-Vats Thanks, already taking screenshots.

**Comment by mountiny** [comment] 2023-07-18 20:48
Sorry @Santhosh-Sellavel for the ping, handling this through other contributor

**Comment by mountiny** [comment] 2023-07-18 22:28
@johncschuster noting that we have agreed with @Nikhil-Vats on $500 for their first "C+ trial" PR review and checklist

**Comment by jasperhuangg** [comment] 2023-07-19 02:12
A [fix](https://github.com/Expensify/App/pull/23129) was CP'd for this to staging, and it looks like this isn't happening anymore, closing. Thanks @mountiny @luacmartins @Nikhil-Vats!

**Comment by Nikhil-Vats** [comment] 2023-07-19 03:12
We are still pending payments here @jasperhuangg

**Comment by mountiny** [comment] 2023-07-19 16:28
@johncschuster $500 payment for @Nikhil-Vats should be pending for review

**Comment by johncschuster** [comment] 2023-08-01 22:41
Sorry I missed your comment, @vitHoracek! I've left you a DM in NewDot for one clarifying point.

**Comment by johncschuster** [comment] 2023-08-01 22:44
### Summary for payment:

 External issue reporter - Applause
 Contributor that fixed the issue - Internal (@vitHoracek)
 Contributor+ that helped on the issue and/or PR - @Nikhil-Vats - $500 (to be paid via Upwork)

**Comment by johncschuster** [comment] 2023-08-02 23:42
Sent the invite!

**Comment by johncschuster** [comment] 2023-08-03 21:45
Paid! 🎉

**Closed by johncschuster** 2023-08-03 21:45 UTC
Labels: External, Engineering, Daily, Awaiting Payment
