### ISSUE TITLE
[Hold for payment] [2024-04-30][$250] Bank account - Random animations between steps transitions on bank account setup flow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40081] opened 2024-04-11 06:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4488988
**Email or phone of affected tester (no customers):** applausetester+vd_ios041024.2@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: user must be logged in, have created a Workspace and have enabled Workflows.

1. Go to Workspace > Workflows.
2. Tap on "Connect bank account".
3. Select "Connect manually" and enter the testing credentials for routing and account numbers, then confirm.
4. Verify that when "Personal info" page is displayed, a random and inconsistent animation is displayed on the "Legal first name" field.
5. Fill the form and continue.
6. Verify that when the date of birth page is displayed, a random and inconsistent animation is displayed on the calendar.
7. Select a date and continue.
8. Verify that when the SSN page is displayed, a random and inconsistent animation is displayed on the SSN field.
9. Tap on the back arrow until you reach the first and last name page.
10. Once more, tap on the back arrow, make sure to verify that when going to previous step (routing and account numbers), a random and inconsistent animation is displayed on the step numbers at the top.

## Expected Result:
There should be no random animations when transitioning between any steps.

## Actual Result:
There are some random and inconsistent animations when transitioning between steps.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6eabb711-1db6-4d8f-815f-0fad03135b5e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144ba5dc06cdd83b2</li>
        <li>Upwork Job ID: 1778359833678811136</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-11 06:52
@zanyrenney I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by zanyrenney** [comment] 2024-04-11 09:49
Yep can see the weird flash / animation. I agree this is a bug.

**Comment by Beamanator** [comment] 2024-04-11 12:51
I don't think this needs to be a blocker - the weird animations aren't so annoying for the user, and it looks like all the functionality still works fine

**Comment by Beamanator** [comment] 2024-04-11 14:10
Ok ya marking as NAB, but accepting proposals for the fix!

**Comment by ikevin127** [comment] 2024-04-11 23:10
# Proposal

### Please re-state the problem that we are trying to solve in this issue

There are some random and inconsistent animations when transitioning between steps on the bank account setup flow.

### What is the root cause of that problem?

Offending PR:
- https://github.com/Expensify/App/pull/13767

> [!caution]
> Native code ahead -> more details / context can be found on this `react-native` issue:
> - https://github.com/facebook/react-native/issues/42604
> 
> Specifically [#42604 (comment)](https://github.com/facebook/react-native/issues/42604#issuecomment-1922422779) and [#42604 (comment)](https://github.com/facebook/react-native/issues/42604#issuecomment-1954995049), which I'm not going to pretend I understand fully ->
> the gist being that there's an issue within:
> `node_modules/react-native/React/Fabric/Mounting/RCTMountingManager.mm`
> which has to do with mounting and `CATransaction` (from Apple docs):
> ```
> CATransaction
> A mechanism for grouping multiple layer-tree operations into atomic updates to the render tree.
> ```

The new architecture caused this iOS specific rendering issue of components with border style where the borders appear stretched while rendering a new screen, then animate to their default state shortly (where UI looks good again).

Check out the frame-by-frame of what's actually happening:

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/56457735/61d74c95-c968-4eed-8d81-69b2b57dd085

</details>

> [!note]
> This issue is not specific to the BA setup flow, but any page that mounts while having components with border styles (inputs, interactive step, etc).

### What changes do you think we should make in order to solve the problem?

As suggested in [#42604 (comment)](https://github.com/facebook/react-native/issues/42604#issuecomment-1954995049), in order to fix this issue as of right now we need to apply a `react-native` patch.

Did that, created the patch `react-native+0.73.4+014+iOSCoreAnimationBorderRendering.patch`, performed a clean install, rebuilt the iOS:Native app and the issue is gone! 🎉 

Here's a test branch: [test/40081](https://github.com/ikevin127/Expensify/tree/test/40081), and steps to test the fix:
1. Chekout test branch.
2. Run `npm ci` to perform a clean install.
3. Rebuild the iOS: Native app.
4. Test the fix using OP steps.

### Videos (before / after)

<details>
<summary>iOS: Native</summary>

| Before | After | After (OP Steps)|
| ------------- | ------------- | ------------- |
| <video src="https://github.com/facebook/react-native/assets/56457735/97fd60de-e7cc-4e5f-bf7f-52b720904b93"> | <video src="https://github.com/facebook/react-native/assets/56457735/f099abab-b6f7-4bc4-be2e-1ab826fab861"> | <video src="https://github.com/Expensify/App/assets/56457735/50a42c97-45a2-40b7-871a-3fc2c589d823"> |

</details>

**Comment by ikevin127** [comment] 2024-04-11 23:13
# Proposal

### Please re-state the problem that we are trying to solve in this issue

There are some random and inconsistent animations when transitioning between steps on the bank account setup flow.

### What is the root cause of that problem?

Offending PR:
- https://github.com/Expensify/App/pull/13767

> [!caution]
> Native code ahead -> more details / context can be found on this `react-native` issue:
> - https://github.com/facebook/react-native/issues/42604
> 
> Specifically [#42604 (comment)](https://github.com/facebook/react-native/issues/42604#issuecomment-1922422779) and [#42604 (comment)](https://github.com/facebook/react-native/issues/42604#issuecomment-1954995049), which I'm not going to pretend I understand fully ->
> the gist being that there's an issue within:
> `node_modules/react-native/React/Fabric/Mounting/RCTMountingManager.mm`
> which has to do with mounting and `CATransaction` (from Apple docs):
> ```
> CATransaction
> A mechanism for grouping multiple layer-tree operations into atomic updates to the render tree.
> ```

The new architecture caused this iOS specific rendering issue of components with border style where the borders appear stretched while rendering a new screen, then animate to their default state shortly (where UI looks good again).

Check out the frame-by-frame of what's actually happening:

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/56457735/61d74c95-c968-4eed-8d81-69b2b57dd085

</details>

> [!note]
> This issue is not specific to the BA setup flow, but any page that mounts while having components with border styles (inputs, interactive step, etc).

### What changes do you think we should make in order to solve the problem?

As suggested in [#42604 (comment)](https://github.com/facebook/react-native/issues/42604#issuecomment-1954995049), in order to fix this issue as of right now we need to apply a `react-native` patch.

Did that, created the patch `react-native+0.73.4+014+iOSCoreAnimationBorderRendering.patch`, performed a clean install, rebuilt the iOS:Native app and the issue is gone! 🎉 

Here's a test branch: [test/40081](https://github.com/ikevin127/Expensify/tree/test/40081), the [diff](https://github.com/Expensify/App/compare/main...ikevin127:Expensify:test/40081) and steps to test the fix:
1. Chekout test branch.
2. Run `npm ci` to perform a clean install.
3. Rebuild the iOS: Native app.
4. Test the fix using OP steps.

### Videos (before / after)

<details>
<summary>iOS: Native</summary>

| Before | After | After (OP Steps)|
| ------------- | ------------- | ------------- |
| <video src="https://github.com/facebook/react-native/assets/56457735/97fd60de-e7cc-4e5f-bf7f-52b720904b93"> | <video src="https://github.com/facebook/react-native/assets/56457735/f099abab-b6f7-4bc4-be2e-1ab826fab861"> | <video src="https://github.com/Expensify/App/assets/56457735/50a42c97-45a2-40b7-871a-3fc2c589d823"> |

</details>

**Comment by ikevin127** [comment] 2024-04-12 08:42
Posted https://github.com/Expensify/App/issues/37374#issuecomment-2051294049 in:
- https://github.com/Expensify/App/issues/37374
to let the people working on the RN v0.74 upgrade know about this issue.

I guess it's up to the team to decide whether to add the [proposed patch](https://github.com/Expensify/App/issues/40081#issuecomment-2050700497) and fix the issue now or HOLD until we're upgraded to v0.74 and see if the issue will be fixed by:
- https://github.com/facebook/react-native/commit/5fbdc994f945ee8d834632649e3b82451660e8fe

**Comment by ikevin127** [comment] 2024-04-15 09:31
PR will be ready in about 4 hours!

**Comment by ikevin127** [comment] 2024-04-15 15:28
PR https://github.com/Expensify/App/pull/40243 ready for review! 🎉

**Comment by ikevin127** [comment] 2024-04-25 02:38
Automation failed here -> this should be on **Hold for payment [2024-04-30]** according to yesterday's production deploy from https://github.com/Expensify/App/pull/40243.

**Closed** 2024-05-01 13:41 UTC
Labels: External, Engineering, Daily, Bug
