### ISSUE TITLE
[Unvalidated Sign-Up] Allow new account sign ins to not require account validation in NewDot

### ISSUE THREAD

**Issue by johnmlee101** [Expensify/App#30794] opened 2023-11-02 19:21 UTC
We want to replicate the similar flows as OldDot, where you can access the site without entering a validateCode or using Google.

Right now we fully support unvalidated accounts since you can sign into OldDot, deep link from the chat bubble into NewDot, then you can use it just fine. 

EDIT:

As an added bonus to this change, we will remove the very first "Here's your magic sign-in link" for both OldDot and NewDot since the user is brought straight into product.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9ff00ed2a89df20</li>
        <li>Upwork Job ID: 1790695759605694464</li>
        <li>Last Price Increase: 2024-05-15</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-11-20 17:10
@johnmlee101 what is the latest here?

**Comment by johnmlee101** [comment] 2023-11-20 17:15
Need to check in on this https://github.com/Expensify/Expensify/issues/281559 and https://github.com/Expensify/Expensify/issues/279833

**Comment by tjferriss** [comment] 2023-11-28 17:23
@johnmlee101 what is the latest here? Also, are the public emails who sign up on expensify.com and get the `classicRedirect` NVP to new.expensify.com also receiving this magic sign-in email upon sign up?

**Comment by johnmlee101** [comment] 2023-11-28 18:33
> Also, are the public emails who sign up on expensify.com and get the classicRedirect NVP to new.expensify.com also receiving this magic sign-in email upon sign up?

I haven't confirmed this one yet, would need to try on a personal account

Latest is there's some spread work and confusion about what we need to do. My existing PR needs to be closed and the other taken over

**Comment by francoisl** [comment] 2023-12-06 20:15
> are the public emails who sign up on expensify.com and get the classicRedirect NVP to new.expensify.com also receiving this magic sign-in email upon sign up?

At the moment, no. We just redirect you to NewDot after you click "Join" and you're signed in. No magic sign-in email gets sent.

**Comment by mallenexpensify** [comment] 2024-02-01 22:00
Following/subscribing in case I can ever help.  I'm a fan of minimizing steps for new users (and for us not having our emails end up in Spam)

**Comment by mallenexpensify** [comment] 2024-02-06 18:50
@hayata-suenaga , also adding me as assignee in case we move forward with this.  Discussion going on [here](https://expensify.slack.com/archives/C03U7DCU4/p1707146780772949?thread_ts=1706915359.531359&cid=C03U7DCU4) .    

Also checking on a discussion about this from a year+ ago
https://expensify.slack.com/archives/C01GTK53T8Q/p1707245429716789?thread_ts=1630952654.016000&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2024-02-06 19:09
All good from the checkin on that thread. 
<img width="927" alt="image" src="https://github.com/Expensify/App/assets/22508304/a32c3589-b130-4c55-bd85-3367aea9d201">

**Comment by hayata-suenaga** [comment] 2024-02-15 18:06
with the bulk email project, the priority of this project seems to have moved higher. Let me see if I can start working on this sooner.

**Comment by mallenexpensify** [comment] 2024-02-18 19:36
Thanks @hayata-suenaga , if you're checking in a Slack/NewDot thread, please post links in the GH issue so I can follow along.

**Comment by hayata-suenaga** [comment] 2024-02-19 16:29
ops sorry I forgot to link the thread

[here is the link](https://expensify.slack.com/archives/C01GTK53T8Q/p1707246046590549?thread_ts=1630952654.016000&cid=C01GTK53T8Q) 🙇

**Comment by mallenexpensify** [comment] 2024-02-21 00:02
ah... that thread, the one I started, ha.  
Thanks for sharing @hayata-suenaga .  It def sounds like something we want. I'm unsure of the exact priority.

**Comment by hayata-suenaga** [comment] 2024-03-04 19:14
[the latest slack discussion on the priority of this issue](https://expensify.slack.com/archives/C03U7DCU4/p1709506509893999)

**Comment by hayata-suenaga** [comment] 2024-03-12 20:48
will being reviewing the past incomplete PRs

**Comment by hayata-suenaga** [comment] 2024-03-26 16:46
still didn't have time to get around this

**Comment by hayata-suenaga** [comment] 2024-04-08 22:05
QBO project and fire are taking my time, and I don't have the bandwidth to work on this right now. 😓

**Comment by mallenexpensify** [comment] 2024-04-23 23:13
This is #wave-collect Release 3, so not a big priority right now, bumping to monthly.

**Comment by hayata-suenaga** [comment] 2024-04-24 17:42
As [discussed in Slack](https://expensify.slack.com/archives/C03TQ48KC/p1713742340822349?thread_ts=1709257767.867229&cid=C03TQ48KC), I'll work on this after the QBO project is done

**Comment by hayata-suenaga** [comment] 2024-05-14 23:41
as per [this comment](https://expensify.slack.com/archives/C036QM0SLJK/p1715728219376619?thread_ts=1715336674.469839&cid=C036QM0SLJK), I'm moving myself from this issue

**Comment by trjExpensify** [comment] 2024-05-15 11:09
As noted [here](https://expensify.slack.com/archives/C036QM0SLJK/p1715695213738489?thread_ts=1715336674.469839&cid=C036QM0SLJK), this has been brought into the XeroCon external commit for June 12th. Asking @johnmlee101 if he'd be willing to finish off his PRs or if @techievivek can take it over in thread.

**Comment by mallenexpensify** [comment] 2024-05-20 01:53
Posted [in thread](https://expensify.slack.com/archives/C036QM0SLJK/p1716169950055999?thread_ts=1715336674.469839&cid=C036QM0SLJK) to see if @johnmlee101 or @techievivek might be able to take the lead here.

**Comment by mallenexpensify** [comment] 2024-05-24 21:53
@techievivek to address soon, was recently assigned here.

**Comment by techievivek** [comment] 2024-05-27 11:24
Taking over John's PR [here](https://github.com/Expensify/Web-Expensify/pull/39507), I have resolved the conflicts and am continuing with the testing.

**Comment by danielrvidal** [comment] 2024-05-31 21:26
This is in review in review so I think we're making progress here: https://github.com/Expensify/Web-Expensify/pull/42216

**Comment by techievivek** [comment] 2024-06-06 21:02
Adding Rushat(C+) to GH since he helped review the App PR.

**Comment by sakluger** [comment] 2024-06-14 19:37
Hey folks, I got a payment issue ([GH](https://github.com/Expensify/App/issues/43039)) for the linked PR on this issue ([PR](https://github.com/Expensify/App/pull/42887)). Will someone be handling payment here, or should I handle payment in my issue?

**Comment by rushatgabhane** [comment] 2024-06-16 12:16
@sakluger here is fine

**Comment by JmillsExpensify** [comment] 2024-06-23 15:59
Can I get a payment summary so that I can approve payment?

**Comment by mallenexpensify** [comment] 2024-06-24 23:48
We're handling payment in this issue. Looks like Rushat's the only one due payment.  @thesahindia , I see you're assigned but it doesn't look like you've reviewed [the PR](https://github.com/Expensify/App/pull/42887), comment if you believe you're due compensation. 

Contributor+: @rushatgabhane due $250 via NewDot.

**Comment by JmillsExpensify** [comment] 2024-06-25 12:48
$250 approved for @rushatgabhane

**Comment by danielrvidal** [comment] 2024-07-02 03:28
@mallenexpensify do you know if this one still needs to be open. I don't think it's actually assigned to me but I was watching it as we prepared for XeroCon, but I think this is done but am not sure.

**Comment by mallenexpensify** [comment] 2024-07-03 00:21
I'm going to close and assume a regression test will be handled elsewhere, if needed.  Comment/reopen if you disagree.  cc @johnmlee101 since you drafted the OP.

**Closed by mallenexpensify** 2024-07-03 00:21 UTC
Labels: Daily, Internal, NewFeature
