### ISSUE TITLE
[$1000]  Country popup closes without proper animation

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22113] opened 2023-07-03 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings -> Click profile picture
2. Click Personal details -> Home address
3. Click on country to open picker
4. Click on Done button

## Expected Result: 
Country picker should animate in reverse of when it appears on click
## Actual Result: 
Country picker is closed without animation or in a less time.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a3830b9f-9ed2-40b9-bd60-929c9aaf2a49

https://github.com/Expensify/App/assets/43996225/38e2f633-e972-405b-b2ae-e136159b2b57

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1680905921684999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01211ae8265c0dc26e</li>
        <li>Upwork Job ID: 1676184726931918848</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by vmehar13** [comment] 2023-07-04 16:26
I've cloned the repository & checked the codebase too.

CountryPicker -> Picker -> BasePicker -> RNPickerSelect ('react-native-picker-select')

It means your project is using this package for picker "react-native-picker-select" & this package internally uses @react-native-picker/picker package.

This issue is in the package('react-native-picker-select') itself you can check in the below link.

https://github.com/lawnstarter/react-native-picker-select/blob/HEAD/ex-ios.gif

I've also send opinions to resolve the in upwork proposal.

**Comment by vmehar13** [comment] 2023-07-04 16:38
Contributor details
Your Expensify account email: vmehar13@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016d57470bf6167144?s=996364627857502209

**Comment by yh-0218** [comment] 2023-07-05 19:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Country popup closes without proper animation
### What is the root cause of that problem?
`react-native-picker-select` uses `Modal` of `react-native`.
we can't control modal close time on this modal.
### What changes do you think we should make in order to solve the problem?
we need to update `react-native-picker-select` npm packge.
we need to use `Modal` of `react-native-modal`.
### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2023-07-05 19:45
@vmehar13 Read our [guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) to understand our process. Leave a proposal using Template on the GitHub to get reviewed thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-07-05 19:46
@yh-0218 Can you add more explanation on the root cause and why we want to update the library, thanks!

**Comment by vmehar13** [comment] 2023-07-05 20:45
Proposal

Please re-state the problem that we are trying to solve in this issue.
Country popup closes without proper animation

What is the root cause of that problem?
```react-native-picker-select``` uses ```Modal``` of ```react-native``` which does not have any closing animations.

What changes do you think we should make in order to solve the problem?

We can create own picker component using ```react-native-modal``` & ```@react-native-picker/picker```. Because ```react-native-picker-select``` internally  uses ```@react-native-picker/picker``` Package. 

What alternative solutions did you explore? (Optional)

Fork ```react-native-picker-select``` Package. Replace ```Modal``` of ```react-native``` with ```Modal``` of ```react-native-modal```

**Comment by Santhosh-Sellavel** [comment] 2023-07-05 21:06
Is this something we could get done at` react-native-picker-select` upstream?

**Comment by vmehar13** [comment] 2023-07-06 03:11
It's not in our hands. Because ```react-native-picker-select``` not updated from last 3 years.

**Comment by yh-0218** [comment] 2023-07-06 04:00
Hi, @Santhosh-Sellavel 
My [Proposal](https://github.com/Expensify/App/issues/22113#issuecomment-1622384641) is updated. Thanks.

**Comment by dylanexpensify** [comment] 2023-07-10 09:40
@Santhosh-Sellavel let's get @yh-0218's updated proposal reviewed today if we can!

**Comment by Santhosh-Sellavel** [comment] 2023-07-10 19:26
Yeah, we can add hold or close this!

**Comment by Santhosh-Sellavel** [comment] 2023-07-11 21:26
@dylanexpensify Can you add hold and remove Helpwanted Label in favor of https://github.com/Expensify/App/issues/22113#issuecomment-1628604804

**Comment by dylanexpensify** [comment] 2023-07-12 08:43
Let's close!

**Closed by dylanexpensify** 2023-07-12 08:43 UTC
Labels: External, Daily, Help Wanted, Bug
