### ISSUE TITLE
[$500]  Task–Reply is not visible for user A and B if A create subtask in task in another device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34661] opened 2024-01-17 18:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Use Android as user A, Web as the same user A, Incognito Web as user B of the chat.
1. Go to https://staging.new.expensify.com/
2. On Web open chat between user A and B
3. On Android Create task as user A in a chat with user B and assign it to yourself
4. Navigate to the task report and create a subtask assign it to user B
5. Go back to 1:1 DM and verify that reply appears under the Task
6. On Web as user A observe the task in 1:1 DM
7. On Web as user B observe the task in 1:1 DM

## Expected Result:
On Web as user A observe the task in 1:1 DM with Reply
On Web as user B observe the task in 1:1 DM with Reply

## Actual Result:
On Web as user A observe the task in 1:1 DM without Reply.
On Web as user B observe the task in 1:1 DM without Reply

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a6c519f2-4fda-49a2-bf04-111941af3723

https://github.com/Expensify/App/assets/78819774/3858db2e-7862-4928-8314-16706d68dcd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01625c3043c756f75c</li>
        <li>Upwork Job ID: 1747683115411566592</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-17 18:18
This looks like a Pusher issue: the parent task report action's `childCommenterCount` is not updated on the User B side.
Once you open the parent task (OpenReport API call fetches fresh data) and go back to 1:1, the child replies counter becomes visible.

**Comment by Piyush-Kumar-Ghosh** [comment] 2024-01-17 18:32
**Proposal: Resolve Missing Reply in 1:1 DM Task Display Issue**

**Problem:**
The issue reported describes a discrepancy in the display of tasks in 1:1 Direct Messages (DM) on the web platform. Specifically, tasks created on Android by User A and assigned to User B with a subsequent subtask are not showing the expected "Reply" when viewed by both users on the web.

**Root Cause:**
Upon analysis, it seems that the web platform is not rendering the "Reply" associated with tasks in 1:1 DM correctly.

**Solution:**
To address this issue, I propose the following solution:

1. **Investigate Web Rendering Logic:**
   - Examine the web platform's rendering logic for tasks and replies in 1:1 DM.
   - Identify any discrepancies or missing components that could lead to the "Reply" not being displayed.

2. **Update Web Rendering Logic:**
   - Make necessary updates to the web platform's rendering logic to ensure that replies associated with tasks in 1:1 DM are correctly displayed.
   - Pay particular attention to the handling of tasks created on Android and any subsequent subtasks.

3. **Cross-Platform Testing:**
   - After implementing the changes, conduct thorough cross-platform testing on various supported platforms, including Android (Native, mWeb Chrome), iOS (Native, mWeb Safari), and MacOS (Chrome/Safari Desktop).
   - Verify that the display of tasks and replies in 1:1 DM is consistent and accurate across platforms.

4. **Integration and Regression Testing:**
   - Integrate the changes into the staging environment and perform comprehensive regression testing to ensure that the proposed solution does not introduce new issues.
   - If the proposed solution passes regression testing, deploy it to the production environment.

**Alternative Solutions:**
While the proposed solution focuses on investigating and updating the web platform's rendering logic, alternative solutions could involve:
- Reviewing the communication and data transfer between the Android and web platforms to ensure proper synchronization.
- Exploring the possibility of a server-side adjustment to provide the necessary task details to the web platform.

**Comment by jliexpensify** [comment] 2024-01-18 02:24
@paultsimura thanks for your input here: is this something that needs to be worked on Internally?

**Comment by jliexpensify** [comment] 2024-01-21 09:46
Bump @aimane-chnaif for your thoughts!

**Comment by marcaaron** [comment] 2024-01-24 02:44
I am having a hard time making out what problem we are solving here. Gonna unassign myself from this. If we feel like this needs to be fixed let's find a Wave or VIP and decide to prioritize it.

cc @thienlnam in case you are collecting task report bugs and stuff.

**Comment by thienlnam** [comment] 2024-01-24 03:00
Hahah yeah this is confusing - but I don't think there is a bug here at least from the video that is shown

The reply shows up under new task, but not under sub new which is correct since sub new does not have any new comments/tasks for it.

Anyways, since this involves subtasks which are not really being used - going to close this as it's not a focus right now

**Closed by thienlnam** 2024-01-24 03:00 UTC
Labels: External, Daily, Help Wanted, Bug
