### ISSUE TITLE
[HIGH] Update subheader to appear as From [invoiceSender workspace]

### ISSUE THREAD

**Issue by davidcardoza** [Expensify/App#42452] opened 2024-05-22 04:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Send invoice
2. Open invoice room
3. Tap invoice preview
4. Observe thread subheader

## Expected Result:
I would expect the "From" subheader to appear as "From [invoiceSender workspace]." The invoice receiver isn't sending anything, so they shouldn't be included.

## Actual Result:
In the invoice thread, the subheader is formatted as "From invoiceSender's workspace & invoiceReceiver displayName".

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment] 2024-05-22 04:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the invoice thread, the subheader is formatted as "From invoiceSender's workspace & invoiceReceiver displayName".

### What is the root cause of that problem?
We return `reportName` of parent subtitle of invoice room as `From invoiceSender's workspace & invoiceReceiver displayName` here

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L3300
### What changes do you think we should make in order to solve the problem?
We should remove invoice receiver display name here

```
return {reportName: `${getPolicyName(parentReport)}`};
```
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L3300
### What alternative solutions did you explore? (Optional)
NA

**Comment by cristipaval** [comment] 2024-05-22 11:36
Still waiting to align [internally](https://expensify.slack.com/archives/CSL3XBCCR/p1716377749487009?thread_ts=1716322720.441889&cid=CSL3XBCCR) on the expected behaviour.

**Comment by cristipaval** [comment] 2024-05-22 15:47
Closing, we don't want a specific subheader format for the invoices. Details [here](https://expensify.slack.com/archives/CSL3XBCCR/p1716392720622779?thread_ts=1716322720.441889&cid=CSL3XBCCR)

**Closed by cristipaval** 2024-05-22 15:47 UTC
Labels: Daily, Bug
