### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Web  - Adding extra number to Share Code, it throws error ' Auth GetEmailByAccountID returned an error"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27381] opened 2023-09-13 17:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> shareCode -> Copy URL
2. Now paste the URL and add one or two extra numbers in it
e.g : shareCode profile URL + '1' or shareCode profile URL + '5'
3. Go to message the hidden user
4. Notice that it throws error ' Auth GetEmailByAccountID returned an error"

## Expected Result:
Since the proflies are enumerated cronologically, for profile URLs that doesn't exits. ' Hmm,, not there ' or something equivalent must be shown.

## Actual Result:
Adding extra number to Share Code, it throws error ' Auth GetEmailByAccountID returned an error"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c5f4b9c2-0dea-4c0a-9a33-5b4893acd192

https://github.com/Expensify/App/assets/93399543/859482d8-eaa9-48b8-b3b7-847a109be430

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694426884818349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143309d373d417e8b</li>
        <li>Upwork Job ID: 1702015263918743552</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-09-13 18:14
### Please re-state the problem that we are trying to solve in this issue.
Attempting to access a non-existent user's profile by using the share link throws an error without redirecting to a 404 page.

### What is the root cause of that problem?
The code processing the API's response does not have a handler for redirecting to a 404 page.

### What changes do you think we should make in order to solve the problem?
Write a line of code which checks if the result from the method lodashGet is a valid response. If not, redirect to the 404 page.

What alternative solutions did you explore? (Optional)
Implementing a more strict validation function for Profile IDs

**Comment by graylewis** [comment] 2023-09-13 18:15
Contributor details
Your Expensify account email: grayjordann2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a2b8ad673e3ea542

**Comment by iamuddeshya** [comment] 2023-09-13 20:06
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Opening a non-existing user profile directly through the URL throws error ' Auth GetEmailByAccountID returned an error"

## What is the root cause of that problem?
The higher order function `applyHTTPSOnyxUpdates` returns  `onyxDataUpdatePromise`. This `onyxDataUpdatePromise` is only checking for a response of 200 if success, otherwise all other response codes are handled as error. 

https://github.com/Expensify/App/blob/c9580dae71597bd4978df1a60102f754c38e0378/src/libs/actions/OnyxUpdates.js#L35-L41

Since as per the current issue, the profile does not exist, hence the error code that is returned is 404 ( See Attached )

<img width="1728" alt="image" src="https://github.com/Expensify/App/assets/19757182/4961c9bd-ab82-4471-b28b-dc32239f63f8">

Hence, the error returns 404 which is not handled. The message also says "Email not found."

## What changes do you think we should make in order to solve the problem?
We can add another if block in the  `onyxDataUpdatePromise` that checks for the response code 404 and takes user to either a 404 page or shows a better error within the page user currently encountered the error in. [ Screenshot Attached ]

https://github.com/Expensify/App/blob/c9580dae71597bd4978df1a60102f754c38e0378/src/libs/actions/OnyxUpdates.js#L32-L42
<img width="844" alt="image" src="https://github.com/Expensify/App/assets/19757182/6b29b7d1-69c8-4531-b1c4-a264a31428c4">

Attached is the video POC



https://github.com/Expensify/App/assets/19757182/c2e1175e-87ab-478e-a2f5-aaaa4c89858c

**Comment by iamuddeshya** [comment] 2023-09-14 21:17
> I think this is a BE bug, we should return the avatar as null if the accountID doesn't exist.

No, because backend is returning 404 which is fine.

**Comment by maddylewis** [comment] 2023-09-15 15:47
@burczu - will you help me confirm whether or not [this recent bug report](https://expensify.slack.com/archives/C049HHMV9SM/p1694502293450659) will be fixed with whichever solution we move forward with for `#27381`?

**Comment by burczu** [comment] 2023-09-18 07:31
@maddylewis I don't think so - in this issue we change the ID that is in the URL address that causes error on the backend side - it can't find this ID in database. In the but report you've mentioned we add double slash to the URL (URLs with double slashes are in general still correct, that's why the App works correctly with it), and perhaps, we need to add some mechanism to remove it while navigating to other pages.

**Comment by burczu** [comment] 2023-09-18 07:33
@graylewis Could you please be more specific where exactly you want to make your changes and how?

**Comment by iamuddeshya** [comment] 2023-09-19 05:15
> @graylewis Could you please be more specific where exactly you want to make your changes and how?

@burczu Hi, did you get a chance to look at my Proposal?

**Comment by burczu** [comment] 2023-09-19 05:41
@iamuddeshya yes, I did, but I wanted some clarification from @graylewis as he was first with his proposal.

**Comment by graylewis** [comment] 2023-09-19 10:59
@burczu 
To clarify my solution, the profile data for a given user is requested in a useEffect call on line 103 (https://github.com/Expensify/App/blob/56271f0b1a60a2ea17b418b458648bbdf4fde483/src/pages/ProfilePage.js#L103)

This is loaded into state in the openPublicProfilePage method in actions/PersonalDetails.js (https://github.com/Expensify/App/blob/56271f0b1a60a2ea17b418b458648bbdf4fde483/src/libs/actions/PersonalDetails.js)

and subsequently is available in the props of ProfilePage as props.personalDetails.

Since visiting a non-existent user's profile should logically be treated as a 404 error, my solution is to check the value of props.personalDetails, and then use navigation.navigate to redirect the user to the 404 page if the result is not a valid PersonalDetails object.

**Comment by burczu** [comment] 2023-09-19 11:01
@graylewis Please update your original proposal instead adding additional comment. Thanks

**Comment by burczu** [comment] 2023-09-20 10:05
Since [the proposal](https://github.com/Expensify/App/issues/27381#issuecomment-1718099816) from @graylewis to handle the redirect in the component sound correct, I tend to recommend choosing [the proposal](https://github.com/Expensify/App/issues/27381#issuecomment-1718247438) from @iamuddeshya where we handle it in the action - I've checked the code and we use this approach extensively in the app.

🎀 👀 🎀 C+ reviewed

**Comment by iamuddeshya** [comment] 2023-09-20 12:30
> https://stackoverflow.com/c/expensify/questions/7972

Thankyou! 🎊

**Comment by madmax330** [comment] 2023-09-26 12:05
@burczu if I understand correctly, with @iamuddeshya's solution, each page would not be able to implement it's own logic for how to deal with a 404 right since `onyxDataUpdatePromise()` would handle it first?

If that's correct I'd rather go with @graylewis's proposal so that the profile screen can handle the 404 however we want. 
Then we can discuss in Slack a general response to the 404.

**Comment by burczu** [comment] 2023-09-26 12:11
@madmax330 Yes, correct - I thought we already have general approach to handling 404 errors. If you think choosing @graylewis's proposal in this case is better option, I'm ok with it too.

**Comment by madmax330** [comment] 2023-09-26 12:23
> I thought we already have general approach to handling 404 errors.

Do you know where that is in the code? (I don't so I'm wondering) 
Also I think it's a bit tricky to put in the `onyxDataUpdatePromise()` because maybe there's some 404s that don't really matter or for which we might not want to go to the full 404 page? 

I'll bring this up in Slack so we can discuss.

**Comment by burczu** [comment] 2023-09-26 12:27
@madmax330 Ahhh... sorry - I confused it a little bit. What I've checked is if we use `Navigation.navigate()` in actions and we do quite extensively. But you are right - we don't handle 404 errors in actions whatsoever...

**Comment by madmax330** [comment] 2023-10-02 12:19
Going to go with @graylewis proposal for now and bring up a bigger discussion about how we should handle 404s generally if at all later.

**Comment by graylewis** [comment] 2023-10-02 12:33
This is a fairly straightforward task, so expect a PR by Thursday. I went ahead and applied to the job on upwork.

**Comment by graylewis** [comment] 2023-10-03 12:22
When should I expect my proposal to be accepted on Upwork? @madmax330

**Comment by madmax330** [comment] 2023-10-03 12:23
@maddylewis can you accept the proposal on upwork?

**Comment by graylewis** [comment] 2023-10-05 12:14
I submitted my upwork proposal 3 days ago and it still hasn't been accepted. I also submitted the PR yesterday and it hasn't been reviewed. What should I expect the timeline for the upwork proposal and PR to be accepted and reviewed to be? @maddylewis @madmax330

**Comment by madmax330** [comment] 2023-10-05 12:23
@burczu can you review the PR please?
@maddylewis can you accept the upwork job?

**Comment by maddylewis** [comment] 2023-10-05 13:41
@graylewis - yep! that's normal. i will typically hire someone to the job in Upwork once the PR is in review or the issue is awaiting payment. i went ahead and hired you in Upwork early this time around 👍

**Comment by graylewis** [comment] 2023-10-05 14:49
OK, good to know! Thanks for making that exception.

**Comment by jasperhuangg** [comment] 2023-10-09 20:57
Sorry @graylewis @madmax330 but I'm going to revert the PR that was submitted for this since it created a deploy blocker https://github.com/Expensify/App/issues/29088

I think a better solution for this would to not throw in the back-end when someone tries to access the profile page of an accountID that doesn't exist.

**Comment by madmax330** [comment] 2023-10-10 03:41
> I think a better solution for this would to not throw in the back-end when someone tries to access the profile page of an accountID that doesn't exist.

@jasperhuangg and what would the front-end show?

**Comment by madmax330** [comment] 2023-10-10 03:41
@graylewis can you look into the deploy blocker and see what was missed?

**Comment by graylewis** [comment] 2023-10-10 14:29
@madmax330 yeah definitely, I'll take a look now

**Comment by graylewis** [comment] 2023-10-10 14:57
@madmax330 Alright, after looking into it it seems that public profiles are treated the same as a 404 on the backend. When I try to open my account using my share code from a brand new account and message myself, I get the "Auth GetEmailByAccountId returned an error" message from the original report. 

As I mention in my PR, the backend doesn't return a 404 for non-existent profiles. This is the primary issue, and my solution is a workaround to throw a 404 appropriately in the meantime. The patch I implemented should work given that a user's display name should be defined for existent profiles and undefined for non-existent profiles (when I looked into it, this seemed to be true). Unfortunately, it seems that the backend isn't returning any info for existent profiles that I don't already have in my contacts. 

This is the data returned from the backend for my share link:
"value": {
                "1566121632": {
                    "accountID": 1566121632,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_1.png",
                    "firstName": "",
                    "lastName": "",
                    "status": null
                }
}

This is identical to the data received when using a non-existent share code. I'm not sure if this is intended behavior (it feels wrong to me), but either way the fact that "Auth GetEmailByAccountId returned an error" is thrown even for valid share codes seems to indicate a deeper issue.

Reproduction steps:
1. Copy share code from account A
2. Open share code from account B that has never talked to account A
3. Click "message hidden"

**Comment by madmax330** [comment] 2023-10-18 12:45
> while on staging the correct avatar for the account is returned. I'm not sure why.

Because staging and production run two separate backend versions. So maybe the issue is fixed now?

**Comment by maddylewis** [comment] 2023-10-19 14:02
based on the status of this issue, does it make sense for @burczu to go through this checklist? https://github.com/Expensify/App/issues/27381#issuecomment-1753978060

**Comment by madmax330** [comment] 2023-10-23 14:58
> based on the status of this issue, does it make sense for @burczu to go through this checklist?

No since the changes were reverted I don't think it makes sense

**Comment by maddylewis** [comment] 2023-10-26 00:17
Leaving a note here for myself on where we are with this one:
- @ashimsharma10 was paid reporting bonus via Upwork
- @graylewis was paid contributor fee via Upwork

to clarify, are we waiting for @graylewis to share a new proposal for this same issue since the original changes were reverted?

**Comment by madmax330** [comment] 2023-10-30 17:10
Since there's no straightforward solution for this. I'm wondering if we should just close this. While I get the issue, I think that if you tamper with the url and the app throws an error I think that's fine, we could handle it better, but not really worth the effort IMO. There's no reason you should be tampering with the url anyways.

**Closed by madmax330** 2023-10-30 17:10 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
