### ISSUE TITLE
tooltip of LHN elements is WAY OFF for longer emails

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21737] opened 2023-06-27 19:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open any chat
2. scroll through LHN to find longer emails
3. hover over the names and observe the tooltip
## Expected Result: 
tootltip is rightwards in the main chat
## Actual Result: 
tootltip should be right above the element

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2c963ece-a631-44ed-a700-d39f84efc53a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686989358411139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<img width="960" alt="Screenshot (374)" src="https://github.com/Expensify/App/assets/43996225/5af87488-b897-4cc3-8cf2-2d20935c7e89">

**Comment by bernhardoj** [comment] 2023-06-28 08:31
Dupe of https://github.com/Expensify/App/issues/21105

**Closed** 2023-06-28 10:24 UTC
Labels: Daily, Bug

**Comment by kavimuru** [comment] 2023-07-04 14:37
This issue is still reproducible and reported in channel.
https://expensify.slack.com/archives/C049HHMV9SM/p1688368904317509
