### ISSUE TITLE
[$500] [HOLD for payment 2023-09-06] Dev - Unable to select a state

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25998] opened 2023-08-26 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open App ->Settings -> Workspace -> bank Account
2. Enter the required details and proceed to step 2.
3. Attempt to select your state.

## Expected Result: 
The user is able to select a state.
## Actual Result: 
The user cannot select a state.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9e072e52-2f04-4358-b6d6-40c46903b974

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nodebrute
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693058557198979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b84ce7e9fc17d03</li>
        <li>Upwork Job ID: 1701792992094031872</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-26 17:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On typing any char for statepicker the modal gets hide

### What is the root cause of that problem?
Seems regression from https://github.com/Expensify/App/pull/25672 where we migrate the `BaseModal` class component to the function component. I think we need to do the cleanup  It is doing the cleanup on the dependency changes which should occur on unmounting.
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/Modal/BaseModal.js#L84-L94

### What changes do you think we should make in order to solve the problem?
I think we need to add a new `useEffect` without any dependency and move this clean up there which acts like a `componentWillUnmount`.

**Comment by b4s36t4** [comment] 2023-08-26 19:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev - Unable to select a state
### What is the root cause of that problem?
This might be a regression from this PR #21049.

The component hierarchy is in this way `AddressPage -> CountryPicker -> CountrySelectorModal`

If we type anything in the `CountrySelectorModal` that update will be passed all the way to `CountryPicker` because of the state we have here https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/CountryPicker/index.js#L37.

After the state update tree render would be like this `CountryPicker -> CountrySelectorModal`
 
which means all the state in `CountrySelectorModal` will be wiped off(obsolete and causes re-render as stated in the above proposals) and component Modal get's re-rendered.

Which triggers this https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/Modal/BaseModal.js#L84-L93 that calls the `onModalHide`.


https://github.com/Expensify/App/assets/59088937/27e73421-1f33-43d0-8672-161e9de1923b


### What changes do you think we should make in order to solve the problem?
This happens with both `CountrySelectorModal` and `StateSelectorModal` because both of them following same kind of principles.

> Input is related to the Modal's component, handling the state outside of modal is certainly causing the 
> re-renders which is leading to close the modal

I think we need to move the state here https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/CountryPicker/index.js#L37 and here 
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/StatePicker/index.js#L41 should be moved to individual modal components so that component state is isolated and won't cause any re-renders.

> Even this approach is also causing the whole component re-render(only state update)  but it's only causing re-render for `CountrySelectorModal` which doesn't wipe the props which makes doesn't trigger this snippet here https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/Modal/BaseModal.js#L84-L93



### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/59088937/905a59db-e6ca-49a6-98f7-d1f5fd818875

**Comment by hayata-suenaga** [comment] 2023-08-27 21:28
sorry people for a lot of assignment and unassignments, but because is a deploy blocker and it's causing issues with other PRs that involve pop over behavior, I gonna handle this 🙇

**Comment by Pujan92** [comment] 2023-08-27 21:31
Ok, let me know in case my proposal makes sense and if I can do some help here.

**Comment by hayata-suenaga** [comment] 2023-08-27 22:58
@kevinksullivan I'm so sorry for confusing situation here. But there is the summary

- @allroundexperts Our C+
- @Pujan92 helped me make the PR throughout the PR review (Although I wrote the code, I just followed their instruction). Let's treat the case as if @Pujan92 made the PR (usual payment)

**Comment by luacmartins** [comment] 2023-08-28 15:30
Gonna remove the deploy blocker label, since this issue happened in dev only and we merged the fix.

**Comment by kevinksullivan** [comment] 2023-08-30 21:33
@allroundexperts please complete the checklist when you a get a chance. Thanks!

**Comment by kevinksullivan** [comment] 2023-09-13 03:00
Adding label to get upwork job created, not sure why that was skipped before.

**Comment by kevinksullivan** [comment] 2023-09-13 03:05
Offers sent to @Pujan92 @Nodebrute and @allroundexperts . Let me know when you accept!

**Comment by Pujan92** [comment] 2023-09-13 10:50
Accepted @kevinksullivan, Just to confirm this needs to be paid using the earlier payment price, right?

**Comment by kevinksullivan** [comment] 2023-09-14 16:44
Can you elaborate on that @Pujan92 ? what is the earlier payment price?

**Comment by Pujan92** [comment] 2023-09-14 16:52
> what is the earlier payment price?

@kevinksullivan I am referencing [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649?thread_ts=1693424078.129649&cid=C01GTK53T8Q) as this issue seems created before 30th aug.

**Comment by kevinksullivan** [comment] 2023-09-15 15:11
Payment summary:

- Reporter - @Nodebrute $250
- reviewer - @Pujan92 $1,000
- reviewer - @allroundexperts  $1,000 (newdot)

**Comment by kevinksullivan** [comment] 2023-09-21 06:18
Sorry @allroundexperts I missed that. Updated payment amounts

**Comment by kevinksullivan** [comment] 2023-09-21 06:22
Updated payment to @Pujan92 , just need to pay out @allroundexperts

**Comment by hayata-suenaga** [comment] 2023-09-25 07:16
@allroundexperts could you accept the offer?

**Comment by kevinksullivan** [comment] 2023-09-27 03:14
Asking @JmillsExpensify in DM about the newdot payment.

**Closed** 2023-09-27 04:06 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 12:57
$1,500 payment approved for @allroundexperts based on BZ summary.
