### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Dev: Web  - Linear Gradient on Lounge Access Page header is broken

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27600] opened 2023-09-16 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Make sure you have access to lounge access page.
2. Navigate to Lounge Access Page.

## Expected Result:
 Header Animation should have a animation overlay
 
## Actual Result:
Header Animation don't have a animation overlay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-15 at 10 43 41 PM](https://github.com/Expensify/App/assets/93399543/aa3b0eb2-0a8e-481c-97ec-3e8be6e9bedc)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694797951259709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d60a245e73bb23c0</li>
        <li>Upwork Job ID: 1703133462496907264</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-16 19:52
### Proposal
### Problem
Linear Gradient on Lounge Access Page header is broken

### Root cause
`themeColors.dark` Color used in in gradient is undefined

### Changes
we need to color `colors.blue800` instead of `dark`

**Comment by Pujan92** [comment] 2023-09-18 05:22
@grgia This seems to persist after theme [PR](https://github.com/Expensify/App/pull/22986) gets merged as `dark` variable removed from the `colors.js` file.

**Comment by grgia** [comment] 2023-09-18 05:56
I'll take this internally in that case. @Pujan92

**Comment by bfitzexpensify** [comment] 2023-10-02 21:15
Payment summary: 

Payment for @thesahindia for internal PR review - $500. 

No other payment required. Closing this one out.

**Closed by bfitzexpensify** 2023-10-02 21:15 UTC
Labels: External, Daily, Internal, Help Wanted, Awaiting Payment

**Comment by bfitzexpensify** [comment] 2023-10-02 23:43
Hey @ishpaul777, it is definitely eligible - I missed your mention in the OP, sorry about that. I've just sent an offer to you via Upwork.

**Comment by JmillsExpensify** [comment] 2023-10-25 17:04
$500 payment approved for @thesahindia based on BZ summary.
