### ISSUE TITLE
[Hold for Payment: 2022-12-09] [$2000] Bug: Blank page is shown for archived room with a message reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12045] opened 2022-10-20 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a workspace if you don't have any
2. Go to members page and remove the other admin ( Expensify setup specialist )
3. Search the announce room and send a message
4. Pin the room and delete the workspace
5. Wait for a few seconds (Reload if the chat is still visible)
6. Verify you are seeing a blank page

## Expected Result:
You should see the room

## Actual Result:
Blank page is shown

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/197026059-4c4b2a76-d71c-4614-a5fe-964fded0549f.mov

https://user-images.githubusercontent.com/43996225/197026076-98971bce-69d0-40a6-a348-595e1645a67d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666254716913509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0163a0872c1900089b
- Upwork Job ID: 1595054682309058560

**Comment by mallenexpensify** [comment] 2022-10-21 20:24
@dylanexpensify  new BZ chore SO is [here](https://stackoverflow.com/c/expensify/questions/14418), we want to ensure BZ stays assigned to all issues so we can get to BugZero,

**Comment by dylanexpensify** [comment] 2022-10-24 09:26
Reviewing today!

**Comment by dylanexpensify** [comment] 2022-10-24 10:11
Posted in slack for clarification

**Comment by dylanexpensify** [comment] 2022-10-24 10:49
Upwork: https://www.upwork.com/jobs/~01e18b2ee260ebaf80

**Comment by dylanexpensify** [comment] 2022-10-27 09:12
Not overdue, awaiting proposals

**Comment by dylanexpensify** [comment] 2022-10-31 09:18
reviewing today!

**Comment by dylanexpensify** [comment] 2022-11-02 15:01
Doubled two days ago

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:12
Hey [@dylanexpensify](https://github.com/michaelhaxhiu), just dropping a note as a reminder to [keep the pressure on](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) to find a contributor and get this one closed out!

**Comment by dylanexpensify** [comment] 2022-11-04 11:52
Price doubled!

**Comment by jayeshmangwani** [comment] 2022-11-05 07:48
Can anyone please confirm that issue is still reproducible, I am not able to reproducible on my side

**Comment by dylanexpensify** [comment] 2022-11-07 08:22
@thesahindia any updates?

**Comment by thesahindia** [comment] 2022-11-07 08:25
The issue is still reproducible.

**Comment by dylanexpensify** [comment] 2022-11-08 08:27
@jayeshmangwani ^

**Comment by AndreasBBS** [comment] 2022-11-08 21:10
I cannot reproduce this in the main branch or in the staging environment.

**Comment by dangrous** [comment] 2022-11-08 21:46
Figured I'd test too - I see the room as archived on staging, which I think is correct?
<img width="976" alt="Screen Shot 2022-11-08 at 16 46 18" src="https://user-images.githubusercontent.com/5487802/200682606-586823c4-c47b-4e35-b5ff-c75cad0f4ec4.png">

**Comment by thesahindia** [comment] 2022-11-08 22:01
Strange, I am able to repro 

https://user-images.githubusercontent.com/83179295/200684766-a1cb44f4-29e1-43c6-b61d-941a6e7a2755.mov

**Comment by AndreasBBS** [comment] 2022-11-08 22:03
> Strange, I am able to repro
> Screen.Recording.2022-11-09.at.3.27.54.AM.mov

What environment is this? Desktop app? If browser, which one?

**Comment by thesahindia** [comment] 2022-11-08 22:08
Staging at Chrome

**Comment by AndreasBBS** [comment] 2022-11-08 22:53
> Staging at Chrome

[cannot_reproduce (1).webm](https://user-images.githubusercontent.com/12399440/200693398-96f3e9f1-3edb-442c-8be3-c8f978aabac0.webm)

Just tried to replicate in 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit) to no success. Very odd. Can you try in an incognito tab? Sorry to bother.

**Comment by jayeshmangwani** [comment] 2022-11-09 08:01
> @jayeshmangwani ^

Sorry for the late reply but the issue is not happening on my side that's why I had ask for checking again, I will try again with other chrome versions/devices

**Comment by dylanexpensify** [comment] 2022-11-09 14:05
@thesahindia seems only you can repro - any ideas why that might be?

**Comment by thesahindia** [comment] 2022-11-09 14:40
I will look into it in a few hours.

**Comment by thesahindia** [comment] 2022-11-11 09:59
I was able to repro this every single time. 

Just a note that sometimes you won't see the blank page just after deleting the workspace. You will need to switch to another chat and navigate back to the archived room (or maybe also reload the page)

**Comment by s77rt** [comment] 2022-11-11 10:43
@thesahindia can you delete the stored database (Onyx) then try again?

**Comment by thesahindia** [comment] 2022-11-11 11:00
> @thesahindia can you delete the stored database (Onyx) then try again?

Still reproducible.

**Comment by dylanexpensify** [comment] 2022-11-14 08:27
reviewing today!

**Comment by thesahindia** [comment] 2022-11-14 08:31
The issue is reproducible and open for proposals.

**Comment by dangrous** [comment] 2022-11-16 21:49
I'm still not able to reproduce on staging...

<img width="1043" alt="Screen Shot 2022-11-16 at 16 49 49" src="https://user-images.githubusercontent.com/5487802/202301969-1842d242-ed5b-4b71-a2a7-6f2c0ea8e013.png">

**Comment by dylanexpensify** [comment] 2022-11-17 09:48
@thesahindia can you share a video of you reproducing this? Might help us

**Comment by thesahindia** [comment] 2022-11-17 10:06
Video here https://github.com/Expensify/App/issues/12045#issuecomment-1307883600

@kavimuru @Puneet-here, can you guys try reproducing this?

**Comment by kavimuru** [comment] 2022-11-18 00:24
@thesahindia I am not able to reproduce this in the build v1.2.29-5

https://user-images.githubusercontent.com/43996225/202588356-48a1633e-3960-4619-848d-959dfa7f6bfd.mp4

**Comment by dylanexpensify** [comment] 2022-11-21 10:49
reviewing today!

**Comment by dylanexpensify** [comment] 2022-11-22 08:31
Can we get an update here @thesahindia? Maybe @robertjchen @kavimuru @Puneet-here can try the new repro steps to confirm - regardless, doubled the issue

**Comment by Puneet-here** [comment] 2022-11-22 08:37
I am able to reproduce. The new steps are correct. We didn't have to remove the guide earlier because they weren't an admin.

**Comment by dylanexpensify** [comment] 2022-11-22 08:58
Great!

**Comment by railway17** [comment] 2022-11-22 09:32
> I am able to reproduce. The new steps are correct. We didn't have to remove the guide earlier because they weren't an admin.

@Puneet-here 
Did you reproduce the issue in the local environment?
I can reproduce it in staging, but not able to do it locally.

**Comment by railway17** [comment] 2022-11-22 09:36
Even though I try the same account and room, it is not working in only staging env.
https://www.loom.com/share/73d676d0d7ca415d971e351c4c51537a

Do you guess there maybe some other reasons?

**Comment by Puneet-here** [comment] 2022-11-22 12:48
Did you reproduce the issue in the local environment?

I just tried and I wasn't able to repro this locally. Maybe some PR fixed this.

**Comment by dylanexpensify** [comment] 2022-11-22 13:59
This issue is over 4 weeks old without a valid proposal approved. @dangrous @robertjchen  this is now assigned to you to complete. Please treat this with priority to help clear out the extensive backlog of /App bugs for WAQ. Any questions? Raise them in [#bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0). Thanks!

**Comment by railway17** [comment] 2022-11-22 14:01
> This issue is over 4 weeks old without a valid proposal approved. @dangrous @robertjchen this is now assigned to you to complete. Please treat this with priority to help clear out the extensive backlog of /App bugs for WAQ. Any questions? Raise them in [#bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0). Thanks!

Oh.. @dylanexpensify 
I've just started to work on this issue by reproducing in desktop version.
So, don't need external proposal anymore?

**Comment by mvtglobally** [comment] 2022-11-22 21:22
Issue not reproducible during KI retests. (First week)

**Comment by robertjchen** [comment] 2022-11-23 13:16
Was able to reproduce this on staging, but not locally by following these exact steps: https://github.com/Expensify/App/issues/12045#issuecomment-1320295813

**Comment by railway17** [comment] 2022-11-23 13:17
> Was able to reproduce this on staging, but not locally by following these exact steps: [#12045 (comment)](https://github.com/Expensify/App/issues/12045#issuecomment-1320295813)

Agreed!

**Comment by hellohublot** [comment] 2022-11-25 09:57
# Proposal

## Reproduce
It cannot be reproduced in the development environment because of conditional judgment
1. Create a new workspace (you can create more than one)
2. Delete the helper for this workspace
3. Delete this workspace
4. Navigate to this workspace


https://user-images.githubusercontent.com/20135674/203953774-8b6f5efa-6c98-4175-9f84-b80c78cdf160.mov




## Relevant Links

- https://github.com/Expensify/App/blame/39b2f9924060c7381b2ff37563a5af88360b0d9d/src/pages/home/ReportScreen.js#L198-L201
- https://github.com/Expensify/App/pull/9291
- https://github.com/Expensify/App/pull/10855


https://github.com/Expensify/App/blob/39b2f9924060c7381b2ff37563a5af88360b0d9d/src/pages/home/ReportScreen.js#L195-L204
```diff
if (!Permissions.canUseDefaultRooms(this.props.betas)
     && ReportUtils.isDefaultRoom(this.props.report)
     && ReportUtils.getPolicyType(this.props.report, this.props.policies) !== CONST.POLICY.TYPE.FREE
     && !ReportUtils.hasExpensifyGuidesEmails(lodashGet(this.props.report, ['participants'], []))
+    && !ReportUtils.isArchivedRoom(this.props.report)
) {
     return null;
}
````
## Finally
Previous project and issue discussions were deleted, so need more suggestions from you to make sure the logic is correct, Thanks

**Comment by cead22** [comment] 2022-11-25 17:57
- I can reproduce on dev by removing `!Permissions.canUseDefaultRooms(this.props.betas)` from the if in the comment above.
- After applying the fix, `&& !ReportUtils.isArchivedRoom(this.props.report)`, I can't reproduce anymore

**Comment by thesahindia** [comment] 2022-11-25 20:35
Ahh that's interesting, the solution will do the job. @hellohublot, thanks for looking into it!

@hellohublot's [proposal](https://github.com/Expensify/App/issues/12045#issuecomment-1327257836) looks good to me 

C+ reviewed 🎀👀🎀

cc: @robertjchen

**Comment by robertjchen** [comment] 2022-11-28 08:57
Great find! Please proceed with the solution @hellohublot 🙏

**Comment by thesahindia** [comment] 2022-11-28 15:41
@dylanexpensify, let's hire @hellohublot.

**Comment by hellohublot** [comment] 2022-11-29 07:44
Hi. I have created a PR: https://github.com/Expensify/App/pull/13124, please help me to check, Thanks

**Comment by cead22** [comment] 2022-11-30 00:39
Reviewed, and agreed on the PR to go with the original solution. Let us know when that's ready. Thanks!

**Comment by hellohublot** [comment] 2022-11-30 04:34
Hello, thank you very much for all your suggestions, I have submitted my original solution and tests, https://github.com/Expensify/App/pull/13124 Thanks !

**Comment by mvtglobally** [comment] 2022-11-30 05:09
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment] 2022-11-30 08:08
@hellohublot @thesahindia @Puneet-here please apply to the Upwork job when you can! https://www.upwork.com/jobs/~0163a0872c1900089b

**Comment by dylanexpensify** [comment] 2022-11-30 09:43
@mvtglobally it looks like we can still reproduce the bug

**Comment by thesahindia** [comment] 2022-11-30 09:45
@dylanexpensify, these are the new steps. Let's add update.

1. Create a workspace if you don't have any
2. Go to members page and remove the other admin ( Expensify setup specialist )
3. Search the announce room and send a message
4. Pin the room and delete the workspace
5. Wait for a few seconds (Reload if the chat is still visible)
6. Verify you are seeing a blank page

**Comment by dylanexpensify** [comment] 2022-12-01 15:56
thanks @thesahindia, updated!

**Comment by dangrous** [comment] 2022-12-01 23:06
This has been merged and is currently on staging! I'm not sure why the automated message didn't say that. But it has been.

**Comment by dylanexpensify** [comment] 2022-12-13 18:17
@hellohublot @thesahindia can we get you to apply to the upwork job please!

**Comment by hellohublot** [comment] 2022-12-14 02:31
@dylanexpensify Yes, I have applied on upwork, my upwork home page is https://www.upwork.com/freelancers/~01509ca2c74bfc7073

**Comment by dylanexpensify** [comment] 2022-12-14 15:46
hmmm, i don't see your application - it's for this one, yes? https://www.upwork.com/jobs/~0163a0872c1900089b

**Comment by thesahindia** [comment] 2022-12-14 16:01
@dylanexpensify, is this also eligible for the bonus since it was approved within 3 days?

**Comment by hellohublot** [comment] 2022-12-14 16:05
@dylanexpensify Yes, I encountered the same problem last time. My upwork account shows that it has been submitted, but you can't receive it. I really don't know what the problem is. 

Maybe you need to help send a offer directly like last time. Thank you.

**Comment by dylanexpensify** [comment] 2022-12-14 16:07
Oh interesting! Will send direct @hellohublot

**Comment by dylanexpensify** [comment] 2022-12-14 16:12
@thesahindia I see the PR raised Nov 29th, when did we merge it?

**Comment by dylanexpensify** [comment] 2022-12-14 16:12
@hellohublot sent an offer direct

**Comment by thesahindia** [comment] 2022-12-14 16:20
Dec 1st
<img width="912" alt="Screenshot 2022-12-14 at 9 49 52 PM" src="https://user-images.githubusercontent.com/83179295/207650515-2bfc1154-3e81-4521-93c3-807f4aa56190.png">

**Comment by dylanexpensify** [comment] 2022-12-14 16:22
Nice, then yes, this will qualify!

**Comment by dylanexpensify** [comment] 2022-12-15 14:10
Alright, all payments sent!

We still have this to do:

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist will need to be completed before the issue can be closed:

- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the updated test here:
- [ ] @thesahindia @dangrous @cead22 The PR that introduced the bug has been identified. Link to the PR:
- [ ] @thesahindia @dangrous @cead22 The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] @thesahindia @dangrous @cead22 A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [x] @dylanexpensify Payment has been made to the issue reporter (if applicable)
- [x] @dylanexpensify Payment has been made to the contributor that fixed the issue (if applicable)
- [x] @dylanexpensify Payment has been made to the contributor+ that helped on the issue (if applicable)

**Comment by dylanexpensify** [comment] 2022-12-15 14:20
posted regression test buddy check, waiting to hear back

**Comment by dangrous** [comment] 2022-12-19 18:18
Re: regression - is this actually a regression, or is it a case that was just previously missed? That is, was this *ever* working?

**Comment by thesahindia** [comment] 2022-12-19 22:05
> or is it a case that was just previously missed?

I believe so and since it was an edge case I highly doubt if this could have been prevented.

**Comment by JmillsExpensify** [comment] 2022-12-22 23:18
Anyone know where the regression test lives? I think we shouldn't wait until Dylan returns. Let's get this one closed out. I'm happy to jump in for him.

**Comment by mallenexpensify** [comment] 2022-12-24 01:41
I should be able to dig in next week to see what's going on, assigned myself

**Comment by thesahindia** [comment] 2023-01-02 18:37
Un-assigned myself since no actions are needed from me.

**Comment by mallenexpensify** [comment] 2023-01-03 01:07
Regression test steps discussion is here https://expensify.slack.com/archives/C01SKUP7QR0/p1671114011698279
@dylanexpensify when you're back can you comment here/there?

**Comment by dylanexpensify** [comment] 2023-01-05 14:06
Hi all! Back today, reviewing now!

**Comment by dylanexpensify** [comment] 2023-01-05 14:07
Commented in thread, creating QA test GH now

**Comment by dylanexpensify** [comment] 2023-01-05 14:15
Regression test update GH created [here](https://github.com/Expensify/Expensify/issues/253069), closing this out!

**Closed by dylanexpensify** 2023-01-05 14:15 UTC
Labels: Reviewing, External, Daily, Bug
