### ISSUE TITLE
[CRITICAL] Unable to paste 2FA code on android mobile web

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36036] opened 2024-02-07 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707282515325559

## Action Performed:
1. Enter email and magic code on android mobile on a 2FA enabled account
2. Copy the 2FA code from the authenticator
3. Paste the 2FA code on the field from the clipboard

## Expected Result:
Able to paste the code
## Actual Result:
It doesn't let me paste the code in.  I choose the first digit, then paste the number from the clipboard, and nothing appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment] 2024-02-07 15:58
@quinthar We were unable to reproduce this on Applause side. Wonder if this is specifically affecting your device model 🤔

**Comment by isabelastisser** [comment] 2024-02-08 21:32
@quinthar can you still reproduce this?

**Comment by isabelastisser** [comment] 2024-02-13 01:08
@isagoico, if you can no longer reproduce this, let's close the issue. Thanks!

**Comment by isabelastisser** [comment] 2024-02-14 16:40
Hey @quinthar @isagoico, can you still reproduce this?

**Comment by isabelastisser** [comment] 2024-02-16 03:37
Closing this.

**Closed by isabelastisser** 2024-02-16 03:37 UTC
Labels: Daily, Needs Reproduction, Bug
