### ISSUE TITLE
[$500]  Room - "Lurker" message shows multiple times

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34660] opened 2024-01-17 16:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/33715
## Action Performed:
1. Log in with an expensifail account
2. Create a workspace
3. Create a public room
4. Write a text message
5. Reply to it in a thread with a text message
6. Go back to the room
7. Write another text message
8. Reply to it in a thread with a text message

## Expected Result:
It should stop showing up after I post a message in the room

## Actual Result:
"Lurker" message shows multiple times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/786258aa-e6af-4a5a-b88e-7de181e54063

![Bug6345467_1705509331308!Message](https://github.com/Expensify/App/assets/78819774/9526f0cd-5104-4842-aab3-5cd8e1692838)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016be5a0629154baf4</li>
        <li>Upwork Job ID: 1747660728293187584</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by Piyush-Kumar-Ghosh** [comment] 2024-01-17 18:41
**Proposal: Resolving "Lurker" Message Duplication in Expensify Room**

**Problem Description:**
The reported issue involves the duplication of the "Lurker" message in Expensify rooms. This phenomenon occurs after specific actions in room threads, leading to an unintended repetition of the message.

**Root Cause Analysis:**
Upon review, it seems the problem surfaces when interacting with room threads, particularly after posting messages. This issue is observed across various platforms, including Android, iOS, and MacOS.

**Proposed Solution:**
To address the "Lurker" message duplication, the following technical changes are suggested:

1. **Thread Interaction Refinement:**
   - Analyze and refine the thread interaction logic to prevent unintended duplications of the "Lurker" message.
   - Ensure proper handling of message posting, threading, and subsequent actions to maintain a singular appearance of the "Lurker" message.

2. **Cross-Platform Testing:**
   - Conduct thorough cross-platform testing on Android, iOS, and MacOS (native and web) to confirm the resolution's effectiveness and consistency.

3. **Integration with PR #33715:**
   - Investigate any potential interactions with the changes introduced in PR #33715 that might be contributing to the observed issue.
   - Collaborate with the team to ensure seamless integration with the existing codebase.

4. **User Verification:**
   - Validate the solution from the user perspective, ensuring that the "Lurker" message behaves as expected after posting messages in room threads.

**Comment by slafortune** [comment] 2024-01-22 20:58
@situchan is the proposal one we can move forward with?

**Comment by situchan** [comment] 2024-01-22 21:00
The proposal above is completely wrong.
@slafortune I am not sure exactly what the bug is.

**Comment by situchan** [comment] 2024-01-29 14:45
@lanitochka17 kindly bump for reproduction

**Comment by lanitochka17** [comment] 2024-01-29 19:01
Issue is not reproducible on the latest build 1.4.32-3

https://github.com/Expensify/App/assets/78819774/5da00d7e-7029-44a9-a1d2-f5f82367efe5

**Comment by situchan** [comment] 2024-01-29 19:05
Thanks. Let's close this cc: @slafortune

**Closed** 2024-02-02 20:00 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
