### ISSUE TITLE
[HOLD for payment 2024-08-01] [$50] Group chat - Avatar loads infinitely when refreshing full screen avatar on confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45824] opened 2024-07-20 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
. Go to staging.new.expensify.com
2. Go to FAB > Start chat > Chat
3. Select a few users
4. Proceed to confirmation page
5. Add a group chat avatar
5. On confirmation page, click on the group chat avatar
6. Click View avatar
7. Refresh the page

## Expected Result:
Avatar will load after refreshing the page

## Actual Result:
Avatar loads infinitely when refreshing full screen avatar on confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d52a99e0-681c-4524-93ad-4811b972243e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163f99f868835a727</li>
        <li>Upwork Job ID: 1814779353535476997</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>Ahmed-Abdella | Contributor | 103224976</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment] 2024-07-20 13:37
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment] 2024-07-20 20:16
@mollfpr @b4s36t4 This one seems related to your PR https://github.com/Expensify/App/pull/44702 can you please confirm if revert fixes it?

**Comment by mountiny** [comment] 2024-07-20 21:48
Not fixed by the revert, going to mark this as external

**Comment by mountiny** [comment] 2024-07-20 21:48
In you proposals, you must include the offending PR. If you can highlight which PR caused it without a fix for the bug (the fix is a revert) a partial $50 reward will go your way

**Comment by Ahmed-Abdella** [comment] 2024-07-21 01:23
@mountiny ther is no option to view the group image in the confirm page in production so it looks like this come from this PR #41586 that add a feature to view a group chat custom avatar.

Also I noticed a behaviour :  If you wait for some time before viewing the image it works fine and display the image after the first refresh. Check the video below. ( but it doesn't work if you refresh it for one more time )

https://github.com/user-attachments/assets/2c8ee18a-2afb-402b-aa87-7a2497fc6388

So I think what happened is that:
After refreshing the page the app trying trying to fetch the image from the backend, but it seems that it didn't get uploaded yet so the file is not found. When I try with a small size image and wait for sometime before veiwing the image it works because the image has been uploaded.

And here is the error message from the console.

The not found file message

![Screenshot 2024-07-21 at 4 15 15 AM](https://github.com/user-attachments/assets/c1ba9b4a-8bf7-4214-b6d7-0277cdee4c83)

![Screenshot 2024-07-21 at 4 16 29 AM](https://github.com/user-attachments/assets/a643d510-337f-4715-8be5-cf2e9891548a)

**Comment by Ahmed-Abdella** [comment] 2024-07-21 01:28
Not Completely sure, but I think the same PR cause this issue #45842 too.

**Comment by s77rt** [comment] 2024-07-21 12:14
cc @nexarvo Can you check this one 👀

**Comment by NaveedShaikh78** [comment] 2024-07-21 17:32
I saw this issue in Upwork. I tried the same step but now it is not reproducible, is it fix or still reproducible ?

**Comment by NaveedShaikh78** [comment] 2024-07-21 17:36
Is it still reproducible?

**Comment by tsa321** [comment] 2024-07-21 17:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar spinner shown when refreshing full screen avatar page and on new group chat confirmation page

### What is the root cause of that problem?

PR https://github.com/Expensify/App/pull/41586 enables viewing group avatar in full screen. When user creates new group, the data is stored in onyx newChatDraft, but the avatar is stored as blob uri string. The blob uri string won't be available when the user refresh the app.


### What changes do you think we should make in order to solve the problem?

We could store the avatar image as base64 string in onyx and use it in new/chat/confirm page.
If we need to fix this issue quickly, I have made a draft PR.

**Comment by mountiny** [comment] 2024-07-21 20:23
Good points, I think this is minor issue and @nexarvo @s77rt should be able to handle this as not a blocker

**Comment by mountiny** [comment] 2024-07-22 12:56
We are proceeding with the revert here https://github.com/Expensify/App/pull/45863 so this will most likely be fixed after that

**Comment by Ahmed-Abdella** [comment] 2024-07-23 00:04
> In you proposals, you must include the offending PR. If you can highlight which PR caused it without a fix for the bug (the fix is a revert) a partial $50 reward will go your way

@mountiny  Based on this, will I get paid for highlighting the PR?

**Comment by mountiny** [comment] 2024-07-23 01:21
Yeah $50 to @Ahmed-Abdella

**Comment by Ahmed-Abdella** [comment] 2024-07-23 01:25
Offer accepted, Thanks @mountiny

**Comment by s77rt** [comment] 2024-07-30 17:06
No checklist needed ^ Offending PR has been reverted

**Comment by carlosmiceli** [comment] 2024-08-01 23:13
Can we close this?

**Comment by s77rt** [comment] 2024-08-02 01:45
@carlosmiceli, @Ahmed-Abdella is due payment for finding offending PR

**Comment by carlosmiceli** [comment] 2024-08-02 20:06
Understood!

**Comment by RachCHopkins** [comment] 2024-08-07 01:32
I'm here Melvin! Sorry, busy week last week!

**Comment by mountiny** [comment] 2024-08-07 07:48
Summary $50 to @Ahmed-Abdella for help with this deploy blocker and finding the offending PR.

As we have reverted the offending change the checklist can be skipped

**Comment by RachCHopkins** [comment] 2024-08-08 20:48
Payment Summary:

Contributor: @Ahmed-Abdella paid $50 via Upwork

**Closed by RachCHopkins** 2024-08-08 20:48 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by RachCHopkins** [comment] 2024-08-12 01:53
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
