### ISSUE TITLE
Chat – Unable to open any + menu option using Up keys and Enter, when open it first time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40399] opened 2024-04-18 08:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Navigate to any chat
4. Click on + button
5. Navigate via + menu using Up/Down keys and press Enter

## Expected Result:
Chosen menu opens

## Actual Result:
Nothing happens, unable to open + menu option using Up keys and Enter, when open it first time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d975dcf2-56d7-40ba-b20e-4f37c3a635f4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-18 08:11
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 08:12
Production 


https://github.com/Expensify/App/assets/115492554/eeac9492-3b5d-4a9a-b3a3-14dcf2e48089

**Comment by shahinyan11** [comment] 2024-04-18 09:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat – Unable to open any + menu option using Up keys and Enter, when open it first time 
### What is the root cause of that problem?
Here we set call onItemSelected function then set `selectedItemIndex.current`  value
### What changes do you think we should make in order to solve the problem?
Transfer  the code `selectedItemIndex.current = index;` above calling onItemSelected function

### What alternative solutions did you explore? (Optional)

**Comment by NikkiWines** [comment] 2024-04-18 09:09
Looks like it might be a result of https://github.com/Expensify/App/pull/39201 cc: @roryabraham @WojtekBoman

**Comment by WojtekBoman** [comment] 2024-04-18 11:08
I'll prepare a fix for that :)

**Comment by roryabraham** [comment] 2024-04-18 22:09
thanks for identifying the PR that caused this @NikkiWines 🙇🏼

**Comment by roryabraham** [comment] 2024-04-19 00:11
verified this is fixed on staging, no payments due, closing it out

**Closed by roryabraham** 2024-04-19 00:11 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly, Bug
