### ISSUE TITLE
Settings - Avatar mismatch in "Share Somewhere" feature.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35560] opened 2024-02-01 14:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Go to settings > share code
2, Observe the different avatars associated with shared code

## Expected Result:
The avatar in "Share Somewhere" should match the profile picture

## Actual Result:
Avatar in "Share Somewhere" differs from the profile picture

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/af95692a-c18f-4b29-93b9-e260833f87cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2024-02-01 16:50
The regression is coming from https://github.com/Expensify/App/pull/34486. @tienifr are you available to work on a fix ASAP? Otherwise I can open a revert PR, NBD. cc @arosiclair @sobitneupane

**Comment by amyevans** [comment] 2024-02-01 16:52
Okay great, thanks!

**Comment by sobitneupane** [comment] 2024-02-01 16:55
@tienifr Is [this issue](https://github.com/Expensify/App/issues/35570) also related to the PR?

**Comment by sobitneupane** [comment] 2024-02-01 17:10
Can you retry with a different email? I can reproduce the issue.

<img width="1177" alt="Screenshot 2024-02-01 at 22 54 33" src="https://github.com/Expensify/App/assets/25876548/9f248f78-47f0-4398-9ab0-c27791ce22dd">

**Comment by amyevans** [comment] 2024-02-01 17:22
Yeah, I was reproducing on `main`:
![Screenshot 2024-02-01 at 11 37 37 AM](https://github.com/Expensify/App/assets/7277067/8e36324e-2d5a-4765-966a-89a7d7a11ea8)

And with the PR reverted locally could no longer repro.

**Comment by sobitneupane** [comment] 2024-02-01 17:36
@amyevans I can reproduce the issue even after reverting the changes from [this PR](https://github.com/Expensify/App/pull/34486).

**Comment by amyevans** [comment] 2024-02-01 17:41
Hmm okay maybe it was coincidental that I couldn't repro after revert, not sure at this point. I'll keep testing

**Comment by situchan** [comment] 2024-02-01 17:45
I reproduced in production as well

**Comment by situchan** [comment] 2024-02-01 17:47
@tienifr can you try main against staging backend?

**Comment by sobitneupane** [comment] 2024-02-01 17:50
I could not reproduce it on production. @situchan Is [this issue](https://github.com/Expensify/App/issues/35570) also reproducible on production?

**Comment by situchan** [comment] 2024-02-01 17:56
I found interesting issue while testing https://github.com/Expensify/App/issues/35570

- At first, avatar was A
- I uploaded avatar and deleted
- Avatar changed to B (even not restored back to A)

Now I am not able to reproduce both https://github.com/Expensify/App/issues/35570 and https://github.com/Expensify/App/issues/35560. Both avatars are B

**Comment by sobitneupane** [comment] 2024-02-01 18:00
Same here. In production, avatar B persists. But in staging and main, avatar A gets restored.

IMO, if we only use production, we always get avatar B. Avatar A is due to the change made from staging/main.

**Comment by situchan** [comment] 2024-02-01 18:05
Agree this came from staging backend because I couldn't reproduce both issues at all against production backend.
No matter frontend code (main/staging/production)

**Comment by roryabraham** [comment] 2024-02-01 19:30
I don't think this should be treated as a deploy blocker, because it's not really breaking anything and is just a subtle UI bug.

**Comment by amyevans** [comment] 2024-02-01 19:46
> I don't think this should be treated as a deploy blocker, because it's not really breaking anything and is just a subtle UI bug.

Fair, and agreed!

**Comment by mallenexpensify** [comment] 2024-02-03 00:11
Assigned to @tienifr cuz they're working on it.

**Comment by amyevans** [comment] 2024-02-12 21:21
Finally got around to looking at this one again, and I see that [this Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40697), which made the default avatar accountID based in the BE, was on staging the day this regression was identified. Mind taking a look @rlinoz?

**Comment by rlinoz** [comment] 2024-02-13 20:32
Hey, sorry about this, I misinterpreted the FE code and didn't realize I had to also change it.

Just opened a PR to fix it.

**Comment by rlinoz** [comment] 2024-02-23 17:11
This is deployed in staging and will probably get deployed to prod next week.

**Comment by rlinoz** [comment] 2024-02-28 12:48
The PR has been deployed to production, so I think we can close this.

**Closed by rlinoz** 2024-02-28 12:48 UTC
Labels: Reviewing, Engineering, Daily, Bug
