### ISSUE TITLE
[HOLD for payment 2023-01-13] [HOLD for payment 2023-01-12] Login  - No error message when entering special characters in the 2FA field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13660] opened 2022-12-16 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed

1. Login using any account that has 2FA enable
2. Enter Email & password
3. Enter any wrong 2FA we will get error message
4. Add 2FA with any special character, it will not return an error message (e.g. 123-12 or 33334,)

## Expected Result:
it should also return an error message of the wrong 2FA

## Actual Result:
no error is showing

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208129424-44177aab-2f08-421e-b17c-94fb43f4a6fe.mov

https://user-images.githubusercontent.com/43996225/208129444-6c54986b-1ce3-4de0-8cb6-cd46a87f5ea4.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671136619287039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e136f5f7fdbd640</li>
        <li>Upwork Job ID: 1608167217448517632</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by arosiclair** [comment] 2022-12-28 16:27
I'll start looking into this and attempt repro today

**Comment by arosiclair** [comment] 2022-12-28 18:08
I can reproduce in staging v1.2.44-0 on web

**Comment by arosiclair** [comment] 2022-12-28 19:33
I don't want to loosen restrictions on `twoFactorAuthCode` in the API, so it looks like the best fix for this is to catch this with frontend validation like we do with the emails and passwords.

**Comment by JmillsExpensify** [comment] 2022-12-28 20:06
Yeah, I agree with that last point. Let's solve any errors on the front-end and keep the API untouched.

**Comment by arosiclair** [comment] 2023-01-11 16:33
I don't believe this was a regression as I don't think this ever worked. However, we should add QA steps to check for this in the future. I've already added a unit test for validating 2FA codes as well.

**Comment by jayeshmangwani** [comment] 2023-01-17 07:50
this issue is ready to be closed and reporting bonus
cc: @arosiclair @mateocole

**Comment by mateocole** [comment] 2023-01-18 02:23
Hey @jayeshmangwani so I can pay you out via upwork. Can you apply [here](https://www.upwork.com/ab/applicants/1615534983095033856/job-details)!

**Comment by jayeshmangwani** [comment] 2023-01-18 04:56
Hey @mateocole , I am not able to access this link

**Comment by mallenexpensify** [comment] 2023-01-20 16:33
@mateocole this wasn't going overdue cuz of the `Reviewing` label, I removed it and added `Hourly` so you can wrap it up.  Thx

**Comment by jayeshmangwani** [comment] 2023-01-23 16:47
@mateocole link is not working for me

**Comment by mallenexpensify** [comment] 2023-01-23 17:02
@jayeshmangwani @parasharrajat this one should work https://www.upwork.com/jobs/~01ba2474b485c5af2c

**Comment by jayeshmangwani** [comment] 2023-01-23 17:09
@mallenexpensify this job is Invite-Only, I am not able to apply

**Comment by mallenexpensify** [comment] 2023-01-23 17:25
Can you try again plz @jayeshmangwani ? 

Upwork is buggy af. The job shows "Make private" (which means to me it's currently public) in one spot and 'invite only' in another.

**Comment by jayeshmangwani** [comment] 2023-01-23 17:30
Thanks, Now its working @mallenexpensify

**Comment by mateocole** [comment] 2023-01-25 00:27
Alright @jayeshmangwani is paid, @parasharrajat, once you accept the offer I'll process your payment as well

**Comment by mateocole** [comment] 2023-01-31 00:38
Alright, payments complete!

**Closed by mateocole** 2023-01-31 00:38 UTC
Labels: Hourly, Internal, Overdue, Awaiting Payment, Bug
