### ISSUE TITLE
[HOLD for payment 2024-12-17] Handle blocked copilot and Expensify card flows gracefully

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#50796] opened 2024-10-15 13:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Similar to [this issue](https://github.com/Expensify/App/issues/50063), we need to prevent co-pilots from issuing new Expensify cards. 

> We should implement exact same solution for issue new Expensify card flow, additionally we need to check for company cards as well.

```
{ "code": 666, "jsonCode": 666, "type": "Expensify\\Libs\\Error\\ExpError", "UUID": "7D862FFF-854D-4AE0-B50B-6C8C96D37AB9", "message": "You must be a domain admin to create the virtual card.", "title": "", "data": [], "htmlMessage": "", "onyxData": [], "requestID": "8d2f62629dff8531-BOM" }
```

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
N/A

</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846678596552098944</li>
        <li>Upwork Job ID: 1846678596552098944</li>
        <li>Last Price Increase: 2024-10-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by Julesssss** [comment] 2024-10-15 13:05
Hey @jliexpensify we're going to hire @c3024 and @ChavdaSachin as discussed [here](https://github.com/Expensify/App/issues/50063#issuecomment-2413860811).

**Comment by jliexpensify** [comment] 2024-10-16 00:02
@Julesssss - just checking: are we paying $250 in this issue, or is Anu handling in the other one? Thanks!

**Comment by Julesssss** [comment] 2024-10-16 12:05
Lets keep them seperate

**Comment by jliexpensify** [comment] 2024-10-16 22:27
@ChavdaSachin @c3024 I think I hired the right people? 😅 Let me know if you didn't get an offer

**Comment by c3024** [comment] 2024-10-17 00:26
I got the offer on Upwork!

**Comment by ChavdaSachin** [comment] 2024-10-17 02:45
Got the offer ✅

**Comment by jliexpensify** [comment] 2024-10-17 08:51
@Julesssss are we following the timeline in the other GH? If so, that's set to pay on the 24th.

**Comment by Julesssss** [comment] 2024-10-17 09:39
> @Julesssss are we following the timeline in the other GH? If so, that's set to pay on the 24th.

Yeah 👍

**Comment by Julesssss** [comment] 2024-10-17 09:40
Wait, I have lost track of the PR now. 

> So could you raise an issue with same c+ here and I will raise a quick PR.
also could you please add my accounts to copilot beta

@ChavdaSachin I can't find the PR, can you share a link please?

**Comment by ChavdaSachin** [comment] 2024-10-17 09:45
@Julesssss I haven't raised PR here yet, coz I am testing other scenarios where we might need same implementation.
Like - copilot is able to close owner's account.
So let me prepare a complete list so we can solve this issue for once and all.

**Comment by ChavdaSachin** [comment] 2024-10-17 09:46
Will send you a list in a couple hrs, and after your confirmation will raise PR.

**Comment by Julesssss** [comment] 2024-10-17 10:29
No worries, thanks for confirming. I'll remove the payment date

**Comment by ChavdaSachin** [comment] 2024-10-17 10:59
hey @Julesssss could you take a look at the list below, I guess most of them should have the restriction for copilots.
Few already has restrictions implemented from BE.

Actions Copilot is able to perform on behalf of owner as of now.

From Profile Page
- [x] Is able to edit private profile credentials - Legal name, DOB, Address.

From Wallet page
- [x] Is able to add bank account using add bank account from wallet page.
- [x] Is able to start enable wallet flow (I don’t have test credentials to enable wallet and check whether BE returns error at the end or not)

From Security Page
- [x] Could start 2FA flow, but BE returns error on authentication code page.
- [x] Able to start Disable-2FA flow, and on flow completion arrived on - 2FA is disabled page, but 2FA was not disabled for actual account. And copilot profile went on loading state until clearing cache from troubleshoot.
- [x] Is able to close account.
- [x] From copilot list able to start change accessLevel flow for self and other copilots.
- [x] BE returns error but nothing on FE when trying to remove self or other copilots.

Subscription Page
- [x] Able to modify all subscription options.

Switch to Expensify Classic
- [x] Able to start flow, but ends up on dead link after submitting the reason.

**Comment by Julesssss** [comment] 2024-10-17 11:14
Hey @ChavdaSachin, thanks for collecting that list. Before moving forward I just want to [check](https://github.com/Expensify/Expensify/issues/382866#issuecomment-2419237535) with the people who implemented this project first - in case we had different plans for these cases.

**Comment by Julesssss** [comment] 2024-10-21 09:29
Hi @ChavdaSachin it looks we are good to move forward here. Your list looks good to me. I think we should also block TrynewDot as you suggested 👍

**Comment by ChavdaSachin** [comment] 2024-10-21 09:47
TryNewDot might be part of hybrid app, right?
I don't have access to hybrid app yet, do you think you could add me?

**Comment by Julesssss** [comment] 2024-10-21 10:01
Ah we can't invite external users yet. 

For now can you just handle it within App?

**Comment by ChavdaSachin** [comment] 2024-10-21 11:57
For our last PR, we used `shouldBeBlocked` with `AccessOrNotFoundWrapper` here. 
https://github.com/Expensify/App/blob/df3e1e435cf2fe1f4b731a4cbaadd598f40d0085/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L121

But since here we need to make use of it many times , as a general solution do you think we should make change to `AccessOrNotFoundWrapper` to add new ACCESS_VARIANT to check whether user is delegate or not.
And since it is about denying access to to delegate, we should rather create a new list - DENIED_ACCESS_VARIANTS to add check for delegate.

Thoughts?

cc. @c3024

**Comment by c3024** [comment] 2024-10-21 12:13
`AccessOrNotFoundWrapper` seems to be added [specifically](https://github.com/Expensify/App/issues/37898) for policies. I think `FullPageNotFoundView` or a new wrapper is more appropriate here.

**Comment by ChavdaSachin** [comment] 2024-10-21 12:28
The new wrapper makes more sense to me rather than using fullPageNotFound.

**Comment by jliexpensify** [comment] 2024-10-24 03:17
Not overdue

**Comment by ChavdaSachin** [comment] 2024-10-29 21:07
PR is nearly 80% done, but since it would be large PR - I am spending more time on testing and am focusing on making more scalable changes. Should be delivered within a day or two.

**Comment by jliexpensify** [comment] 2024-11-06 00:23
Not overdue, PR being worked on

**Comment by Julesssss** [comment] 2024-11-06 11:23
Hey @ChavdaSachin, just checking in on this task. Let me know if you need help with anything!

**Comment by ChavdaSachin** [comment] 2024-11-06 11:29
hi @Julesssss changes for noDelegateAccessWrapper, and subscription page are yet to be implemented, but I am raising a draft pr for rest of the work already done so you could review those changes in mean time.

**Comment by Julesssss** [comment] 2024-11-06 12:00
Thanks @ChavdaSachin

Hey @dubielzyk-expensify, @ChavdaSachin is trying to prevent users from performing actions as a copilot and has a good question about blocked actions that are accessed via the three-dot menu. [Here's](https://github.com/Expensify/App/pull/52103#issuecomment-2459549688) a link to the comment that has screenshots. 

> Quick question -
On security page in delegates section, both menu items are restricted actions, should we hide three dot menu there?

**Comment by dubielzyk-expensify** [comment] 2024-11-07 02:22
If you can't do any of the actions in the three dot menu, then yes, I think it makes sense to remove the icon altogether. @Expensify/design team for gut check

**Comment by shawnborton** [comment] 2024-11-07 07:42
Yup, that makes sense to me as well.

**Comment by shawnborton** [comment] 2024-11-07 16:13
Oh that's a totally fair point, I forgot about that pattern here.

**Comment by dubielzyk-expensify** [comment] 2024-11-08 01:41
Just for my education, where do we do that? I remember buttons like this, but not overflows. FWIW I think that's the right pattern if we have a button

**Comment by shawnborton** [comment] 2024-11-08 09:20
Yeah that's a fair point too... when you tap a button, you are told that the action of the button can't be taken:
![CleanShot 2024-11-08 at 10 19 22@2x](https://github.com/user-attachments/assets/87c92173-7a66-4b1a-81a9-c1027e6612fb)

For the overflow icon... it might feel weird if we throw a big modal in your face after simply tapping a small icon. So I could see where just hiding it is better, or don't hide the three dots and then throw the modal once one of the options from the menu is taken?

**Comment by dannymcclain** [comment] 2024-11-08 14:10
>don't hide the three dots and then throw the modal once one of the options from the menu is taken?

This is what I was imagining. Definitely don't want to throw the modal after tapping the overflow icon. But the menu items within don't really seem that different from a button to me.

Happy to defer to what you all think is best—just wanted to point out that pattern because I remember us using it elsewhere!

**Comment by shawnborton** [comment] 2024-11-08 14:15
> But the menu items within don't really seem that different from a button to me.

Yup, totally agree there - that would be my vote.

**Comment by dubielzyk-expensify** [comment] 2024-11-10 23:46
SGTM  👍

**Comment by Julesssss** [comment] 2024-11-12 10:04
In progress

**Comment by ChavdaSachin** [comment] 2024-11-14 10:17
Hey @dubielzyk-expensify I am here trying to block delegates from performing certain actions, and I need your view here.
please take a look at https://github.com/Expensify/App/pull/52103#issuecomment-2475944304

**Comment by dubielzyk-expensify** [comment] 2024-11-15 03:35
Looks like that's answered by the team already 👍

**Comment by jliexpensify** [comment] 2024-11-26 22:49
Looks like the Upworks job is still this one: https://github.com/Expensify/App/issues/50796#issuecomment-2418071859

**Comment by ChavdaSachin** [comment] 2024-12-03 09:38
@jliexpensify make sure to hold the payment,
The PR merged was just a supporting PR, The original PR is yet to be merged https://github.com/Expensify/App/pull/52103

**Comment by ChavdaSachin** [comment] 2024-12-06 18:01
@Julesssss could you give a thought to bounty amount here please?
@c3024 what you suggest?

**Comment by c3024** [comment] 2024-12-07 04:47
I agree. This grew into a large PR with handling all cases meticulously and building the wrapper. Great job!

**Comment by Julesssss** [comment] 2024-12-09 10:36
Yeah, I was going to suggest an increase here. 

Over the last month you have handled many cases, testing, and the necessary Onyx changes. This work extended from the original PR, so I think a 3x multiplier for **this** issue seems fair. That would make a $750 bounty.

**Comment by jliexpensify** [comment] 2024-12-09 22:45
https://github.com/Expensify/App/pull/52103 currently deployed to Staging

**Comment by c3024** [comment] 2024-12-10 00:30
@jliexpensify , I think it should be the [same](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit?tab=t.0#bookmark=id.qr9c929owwy8) for both.

cc: @Julesssss 

@jliexpensify Btw, I am eligible for payments on NewDot too.

**Comment by jliexpensify** [comment] 2024-12-10 00:34
Fixed, thanks!

**Comment by Julesssss** [comment] 2024-12-10 13:26
Yeah, that looks good @jliexpensify

**Comment by jliexpensify** [comment] 2024-12-13 02:50
Bumping @c3024 for the checklist

**Comment by c3024** [comment] 2024-12-13 05:51
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [x] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: This is related to design of copilot actions so specific PR can be held responsible.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: No discussion was started because this is not a bug that could be identified earlier.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


Tests 1 to 10 here in QA tests in this [PR](https://github.com/Expensify/App/pull/52103).

Do we agree 👍 or 👎

**Comment by jliexpensify** [comment] 2024-12-16 03:12
Payment Summary

- C: @ChavdaSachin $750 (to be paid via Upworks)
- C+: @c3024 $750 (to be paid via ND)

https://www.upwork.com/jobs/~021846678596552098944

**Comment by jliexpensify** [comment] 2024-12-16 03:14
@c3024 going to end the contract (but leave you positive feedback) so you cab request on ND

**Comment by ChavdaSachin** [comment] 2024-12-17 09:10
Not received

**Comment by jliexpensify** [comment] 2024-12-17 09:59
Paid and job closed!

**Closed by jliexpensify** 2024-12-17 09:59 UTC
Labels: External, Engineering, Weekly, Design, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-12-23 12:07
$750 approved for @c3024 based on [this summary](https://github.com/Expensify/App/issues/50796#issuecomment-2544452886).
