### ISSUE TITLE
[$500] Manage members - Page is blinking after removing user from Workspace 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8927] opened 2022-05-10 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Go to Setting > Workspace > Manage members
3. Invite few members(if you haven't)
3. Delete the member

## Expected Result:
Page is not blinking after removing user from Workspace 

## Actual Result:
Page is blinking after removing user from Workspace 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Desktop App
- Mobile Web

**Version Number:** 1.1.57.12

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167718604-608be40f-3ae8-406f-8e0b-e96cf02e1b14.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-05-14 13:42
### Proposal 
When we remove a member [removeMembers](https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/libs/actions/Policy.js#L287) function gets called and inside it we update the policy after removing the users using `Onyx.set` 
https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/libs/actions/Policy.js#L296-L302

We are doing the same thing again here. It's not needed and removing it will solve this.
https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/libs/actions/Policy.js#L519-L527

I propose that following changes -
```diff
function subscribeToPolicyEvents() {
-    _.each(allPolicies, (policy, key) => {
+    _.each(allPolicies, (policy) => {
        const pusherChannelName = `public-policyEditor-${policy.id}${CONFIG.PUSHER.SUFFIX}`;
        Pusher.subscribe(pusherChannelName, 'policyEmployeeRemoved', ({removedEmails, policyExpenseChatIDs, defaultRoomChatIDs}) => {
-            const policyWithoutEmployee = _.clone(policy);
-            policyWithoutEmployee.employeeList = _.without(policy.employeeList, ...removedEmails);
-
-            // Remove the members from the policy
-            Onyx.set(key, policyWithoutEmployee);

            // Refetch the policy expense chats to update their state
            if (!_.isEmpty(policyExpenseChatIDs)) {
                Report.fetchChatReportsByIDs(policyExpenseChatIDs);
            }
```

**Comment by mananjadhav** [comment] 2022-05-15 18:41
@thesahindia I went through your profile. Based on what I see, `policyEmployeeRemoved` is an event subscribed via `Pusher`, so I am guessing it is to sync between devices. If we remove this, it might not sync.

**Comment by deetergp** [comment] 2022-05-16 22:42
I agree with @mananjadhav — we're going to need that value in Onyx & for Pusher.

**Comment by deetergp** [comment] 2022-05-19 22:13
Switching this back to `Weekly` since we're still open to more proposals.

**Comment by grvsood** [comment] 2022-05-21 14:49
> Page is not blinking after removing the user from Workspace

what do we mean by "blinking" ? what's the expected CX here?

**Comment by grvsood** [comment] 2022-05-21 18:00
if by "blinking", the reference is to the reload/refresh of members list after a user is deleted, then it's not reproducible on the web app.

https://user-images.githubusercontent.com/26037206/169663776-db84c117-2522-43fe-93ea-6419b2a2709e.mp4

**Comment by mananjadhav** [comment] 2022-05-21 19:21
Thanks for the comment @grvsood. I am guessing you can reproduce it when you would have some more members than just the admin. Here's the video that I could reproduce.

https://user-images.githubusercontent.com/3069065/169666306-49b93c7f-c71b-40a8-b452-69df4b406fe8.mov

**Comment by grvsood** [comment] 2022-05-22 16:46
### Proposal 
When removeMembers method is called, we update the persistent storage. [code](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.js#L287-L318)

We are also subscribed to `policyEmployeeRemoved` policy to reflect the change on other devices. [code](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.js#L519-L542). 

Listening to this policy change and updating the storage is redundant when the change in employeeList attribute is on the same device as persistent storage is already updated when called by `removeMembers` method.

Hence adding below check we can skip updating the persistent storage  ( aka Onyx ) on current device. 

Changes to [subscribeToPolicyEvents](https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/libs/actions/Policy.js#L519) method

```diff
function subscribeToPolicyEvents() {
  _.each(allPolicies, (policy, key) => {
    const pusherChannelName = `public-policyEditor-${policy.id}${CONFIG.PUSHER.SUFFIX}`;
    Pusher.subscribe(
      pusherChannelName,
      'policyEmployeeRemoved',
      ({removedEmails, policyExpenseChatIDs, defaultRoomChatIDs}) => {
        const policyWithoutEmployee = _.clone(policy);
        policyWithoutEmployee.employeeList = _.without(
          policy.employeeList,
          ...removedEmails,
        );

+         Onyx.get(key).then((existingPolicyValue) => {
    
+           if (existingPolicyValue != undefined) { // I need to validate if this check is required or not. 
+             if ( existingPolicyValue.employeeList != undefined &&
+             JSON.stringify(existingPolicyValue.employeeList.sort()) !=
+              JSON.stringify(policyWithoutEmployee.employeeList.sort())
+           ) {
               Onyx.set(key, policyWithoutEmployee);
+            } 
+          } else {
+            Onyx.set(key, policyWithoutEmployee);
+          }
+         });
```


And thus accordingly we need to expose the `Onyx.get` method as well. 

We can do that by making following change to `Onyx.js` in [react-native-onyx](https://github.com/Expensify/react-native-onyx/blob/main/lib/Onyx.js#L852). 

```diff
const Onyx = {
    connect,
+   get,
    disconnect,
    set,
```

**Comment by thesahindia** [comment] 2022-05-24 18:57
> @thesahindia I went through your proposal. Based on what I see, `policyEmployeeRemoved` is an event subscribed via `Pusher`, so I am guessing it is to sync between devices. If we remove this, it might not sync.

Hi @mananjadhav, I think there's a misunderstanding. I am not suggesting the removal of `policyEmployeeRemoved`. I am suggesting that we remove line 523-527

https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/libs/actions/Policy.js#L523-L527

Because we are executing the same code already when [removeMembers](https://github.com/Expensify/App/blob/572f6cb1b161fbb90fad17569f10c4af4926e773/src/libs/actions/Policy.js#L287) gets called

**Comment by thesahindia** [comment] 2022-05-24 19:28
I didn't get the pushed notification part, can you explain why we need that particular code for pushed notification implementation as I was unable to find that use.

**Comment by adelekennedy** [comment] 2022-05-27 20:45
Doubling time!

**Comment by adelekennedy** [comment] 2022-05-30 22:35
not overdue

**Comment by deetergp** [comment] 2022-06-02 18:35
@mananjadhav Oooh, I think I understand what @thesahindia is getting at with his proposal. We were subscribed to changes on the policy to begin with, and that the `Onyx.set` on line 527 updates it again, which causes is to redraw it again, despite the fact that nothing has changed. Is that correct @thesahindia?

Would you please perform a test where you are logged into User A and User B who are both on the same policy, then as User A, remove User C, and verify that User B's user list reflects the change?

**Comment by thesahindia** [comment] 2022-06-02 18:40
@deetergp, yeah I have tested that and it's working fine.

**Comment by thesahindia** [comment] 2022-06-02 19:03
>Would you please perform a test where you are logged into User A and User B who are both on the same policy, then as User A, remove User C, and verify that User B's user list reflects the change?

I think we have another bug, while testing this I am sometimes seeing same user two times in the member list of the announce room and the removed member is still showing up even after tons of refreshes

**Comment by mananjadhav** [comment] 2022-06-02 19:54
Thanks for the clarification here @deetergp. Sorry about the confusion @thesahindia. 

> It doesn't work right now in Main so I guess we don't have this implemented.

@deetergp Could you shed some light on @thesahindia's comment that the sync doesn't exist as of now? I am not sure about that part of the feature.  


> I think we have another bug, while testing this I am sometimes seeing same user two times

@thesahindia If you have the reproducible steps for the bug, please post it on the slack channel to track and log an issue.

**Comment by adelekennedy** [comment] 2022-06-06 18:39
not overdue - we're still reviewing proposals

**Comment by deetergp** [comment] 2022-06-06 18:56
> It doesn't work right now in Main so I guess we don't have this implemented.

@thesahindia Okay, that's good to know. It's a feature we should add, but it is definitely out of scope for this issue. Just to confirm, with your  proposal, both the the user doing the removing and the user being removed see the change? The remover sees the the user being removed disappear from the list and the user being removed no longer sees the room?

**Comment by thesahindia** [comment] 2022-06-07 20:14
>The remover sees the the user being removed disappear from the list

@deetergp, I think the sync is broken or something. After removing a member, it won't go away from your room member list. It takes too much time to update. I tested this on main. 

>user being removed no longer sees the room?

Yeah this works fine.

**Comment by adelekennedy** [comment] 2022-06-08 20:49
not overdue, proposals are being reviewed

**Comment by deetergp** [comment] 2022-06-08 20:57
@thesahindia I'm not sure I understand. I'm checked out to `main` and logged in as the workspace admin. When I remove User B, I see that user drop off the list of workspace members, so that seems to be working correct. And if I am logged in as User B, I don't see myself having been removed as the removal occurs, but if I try to reply, refresh or do anything else in that chat, I see a message telling me that User B is no longer a part of that workspace. So that's working well enough in `main`. Though ideally it should probably happen immediately, it's outside of the scope of this issue.

If you proposal doesn't change how that works, then let's go with your proposal.

**Comment by mananjadhav** [comment] 2022-06-08 21:40
> Though ideally it should probably happen immediately, it's outside of the scope of this issue.

@deetergp I am guessing thats what @thesahindia meant here.

**Comment by thesahindia** [comment] 2022-06-09 05:54
>@thesahindia I'm not sure I understand. I'm checked out to main and logged in as the workspace admin. When I remove User B, I see that user drop off the list of workspace members.

Yeah, that works fine. I misinterpreted the question and thought it was about announce room's members list.

**Comment by mananjadhav** [comment] 2022-06-10 09:56
@deetergp Are we good here to accept @thesahiindia's proposal?

@grvsood Sorry I saw the comments I didn't give feedback on your proposal (I thought I did). While your solution might work, performing the process of `Onyx.get`, etc. doesn't look like a good solution for such a trivial case. Also, my experience with `JSON.stringify` with objects, dates, etc. is unreliable, and comparing them with `sort` is inefficient. We don't want to break something when we add more data to the objects or have complex structures like graphs with circular dependency.

**Comment by deetergp** [comment] 2022-06-13 13:27
> Are we good here to accept @thesahiindia's proposal?

@mananjadhav Yes, let's go with @thesahindia's solution. 👍

**Comment by thesahindia** [comment] 2022-06-14 15:07
@adelekennedy, the job is no longer available, can you please create a new one?

**Comment by deetergp** [comment] 2022-06-15 19:31
Not overdue. We've accepted a proposal so setting it back to weekly.

**Comment by deetergp** [comment] 2022-06-17 19:35
I missed adding the weekly label

**Comment by deetergp** [comment] 2022-06-17 19:36
Also, bumping @adelekennedy to re-add the job in Upwork so @thesahindia can start work on it.

**Comment by adelekennedy** [comment] 2022-06-22 03:26
reopened! @thesahindia do you mind applying [here](https://www.upwork.com/jobs/~01232d0b68c48ee76c)?

**Comment by thesahindia** [comment] 2022-06-22 14:33
> reopened! @thesahindia do you mind applying [here](https://www.upwork.com/jobs/~01232d0b68c48ee76c)?

Applied ✅

**Comment by mananjadhav** [comment] 2022-06-25 16:08
@thesahindia Any updates for me on this one?

**Comment by thesahindia** [comment] 2022-06-25 19:07
@mananjadhav, I have pushed the code now.

**Comment by mvtglobally** [comment] 2022-06-28 04:00
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2022-07-04 15:57
Still going through tests - not overdue

**Comment by mvtglobally** [comment] 2022-07-12 04:33
Issue not reproducible during KI retests. (Second week)

**Comment by deetergp** [comment] 2022-07-13 16:33
@adelekennedy It looks like this one is good to go and we should pay @thesahindia for their effort 👍

**Comment by adelekennedy** [comment] 2022-07-13 16:43
@deetergp ty ty, I'll pay this out in 7 days!

**Comment by mananjadhav** [comment] 2022-07-15 22:26
This hit production but the title wasn't updated

**Comment by mvtglobally** [comment] 2022-07-19 03:22
Issue not reproducible during KI retests. (Third week)

**Comment by mananjadhav** [comment] 2022-07-20 20:55
@adelekennedy  Quick bump. The regression period is complete. PR was deployed 8 days back.  For some reason title wasn't updated.

**Comment by mvtglobally** [comment] 2022-07-26 03:52
Issue not reproducible during KI retests. (Fourth week) Are we good to close this?

**Comment by mananjadhav** [comment] 2022-07-26 04:00
@mvtglobally Payments are pending for this one. We can close this out once that is through.

@adelekennedy quick reminder

**Comment by adelekennedy** [comment] 2022-07-26 18:40
Hmm, do we know why the title didn't change? Happy to pay out but I'm concerned that something is broken here @deetergp

**Comment by adelekennedy** [comment] 2022-07-26 18:42
No reporting bonus, C+: @mananjadhav, Contributor: @thesahindia

**Comment by thesahindia** [comment] 2022-08-04 15:44
Bump for upwork.
cc: @adelekennedy

**Comment by mananjadhav** [comment] 2022-08-09 19:24
bump @adelekennedy @deetergp for Upwork

**Comment by adelekennedy** [comment] 2022-08-09 19:50
Strange - I'm not getting any notifications from this GH, I just sent the payment through with a bonus for waiting

**Closed by adelekennedy** 2022-08-09 19:50 UTC
Labels: Reviewing, Exported, External, Engineering, Weekly, Help Wanted

**Comment by mananjadhav** [comment] 2022-08-09 20:26
Thanks @adelekennedy for the quick TAT and bonus 🤑
