### ISSUE TITLE
[$500] IOU - Unexpected error is displayed while editing IOU details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34817] opened 2024-01-19 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap in a Workspace chat
3. Tap plus icon near compose
4. Tap request money --- Manual
5. Enter an amount and tap next
6. Enter merchant and tap request
7. Pay elsewhere the newly created expense
8. Tap on newly created expense to open IOU details page
9. Tap category
10. Select a category
11. Again tap category and deselect it
12. Tap description
13. Enter description and tap save

## Expected Result:
Unexpected error while editing money request must not be displayed in IOU details page after user set description

## Actual Result:
Unexpected error while editing money request is displayed in IOU details page after user set description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1a3eb9cb-469d-4d0a-8179-f76244aeb187

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015cfd8609c6b2be50</li>
        <li>Upwork Job ID: 1748380895455809536</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-01-19 18:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unexpected error while editing money request is displayed in IOU details page after user set description

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/56fb81458582179196f2a5cedaf1a358bdbca48e/src/libs/ReportUtils.ts#L2010-L2013

We allow admin/manager to edit requests even though this request has been settled. So that in FE we admin/manager still can edit the description and category fields. But when editing the category field the BE return error

<img width="567" alt="Screenshot 2024-01-20 at 01 03 19" src="https://github.com/Expensify/App/assets/141406735/11c712ec-75d6-4325-9694-e2984921b493">

### What changes do you think we should make in order to solve the problem?
I think this bug should be fixed from BE side. 

But I think we should confirm the expected first which fields admin/manager can edit settled request

### What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment] 2024-01-19 18:05
@johncschuster Could you help to confirm this?
> But I think we should confirm the expected first which fields admin/manager can edit settled request

**Comment by mallenexpensify** [comment] 2024-01-24 03:29
@allroundexperts reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by allroundexperts** [comment] 2024-01-25 00:58
Thanks @mallenexpensify. I'll take this.

@johncschuster do we have an answer on [this](https://github.com/Expensify/App/issues/34817#issuecomment-1900860777) yet?

**Comment by allroundexperts** [comment] 2024-01-29 20:43
Bump @johncschuster on above!

**Comment by mvtglobally** [comment] 2024-01-30 04:59
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2024-02-01 22:55
@allroundexperts sorry I missed your question above. I don't have an answer to that. I would assume the admin should be able to edit the description and the category, but I can raise this for discussion if the behavior persists and we need to get to the bottom of it.

**Comment by johncschuster** [comment] 2024-02-02 22:32
Holding while we wait to see if this is reproducible.

**Comment by johncschuster** [comment] 2024-02-05 23:43
Waiting on the weekly retest.

**Comment by mvtglobally** [comment] 2024-02-13 04:56
Issue not reproducible during KI retests. (Second week)

**Comment by johncschuster** [comment] 2024-02-14 16:27
It looks like this behavior no longer persists. Let's give it one more re-test and then we can close it.

**Comment by johncschuster** [comment] 2024-02-21 00:29
Not overdue. We're waiting on a re-test.

**Comment by mvtglobally** [comment] 2024-02-21 02:28
Issue not reproducible during KI retests. (Third week)

**Comment by johncschuster** [comment] 2024-02-26 22:11
Thanks for retesting this, @mvtglobally! I think it's safe to close if the behavior is no longer reproducible.

**Comment by mvtglobally** [comment] 2024-02-27 15:34
Issue not reproducible during KI retests. (Fourth week)

**Closed** 2024-02-27 15:34 UTC
Labels: Engineering, Daily, Internal, Bug, retest-weekly
