### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] App only bolds text in quote when we use quote with multiline bold text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19607] opened 2023-05-25 12:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Send multiline bold text with quote in start (eg like in video)
4. Observe the sent text

## Expected Result: 
App should bold both, text inside the quote and text outside the quote
## Actual Result: 
App only bolds text inside the quote

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a4ef6ed0-4c88-438e-9527-5bb1ce7a53ad

https://github.com/Expensify/App/assets/43996225/dd443f23-2058-4712-8a75-5bf4f31e3530

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683197102883889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103b41c91900b4447</li>
        <li>Upwork Job ID: 1662275139638894592</li>
        <li>Last Price Increase: 2023-05-27</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-05-25 16:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App only bolds text in quote when we use quote with multiline bold text. The expected behaviour is that we should skip rendering bold style. For example, the following comment 

```
> *This is multiline
bold text*
```

should be rendered as 

<img width="169" alt="image" src="https://github.com/Expensify/App/assets/117511920/03fbf801-45a5-4cea-a681-0cfb958afdfa">

Instead of 

<img width="150" alt="image" src="https://github.com/Expensify/App/assets/117511920/ec02e84f-b770-4303-b216-284f8e7b0d53">

### What is the root cause of that problem?

We apply [bold-markdown-to-html](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L170-L177) rule before [quote-markdown-to-html](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L183-L199) rule. For example, the following comment

```
> *This is multiline
bold text*
```

is translated into html with `blockquote` tag and `strong` tag overlapping with each other

```html
<blockquote><strong>This is multiline</blockquote>bold text</strong>
```

by method ExpensiMark.replace and then backend corrects it to 

```html
<blockquote><strong>This is multiline</strong></blockquote>bold text
```

So the root cause the invalid parsing order of [bold-markdown-to-html](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L170-L177) rule and [quote-markdown-to-html](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L183-L199) rule. Note that we detect if the bold syntax is overlapping with other tags in this [line](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L176)

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should apply [quote-markdown-to-html](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L183-L199) rule before `italic`, `bold` and `strikethrough` rule. We can move [quote-markdown-to-html](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L183-L199) rule to the line before this [line](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L156). By doing so, we can skip rendering the invalid bold syntax like

<img width="169" alt="image" src="https://github.com/Expensify/App/assets/117511920/03fbf801-45a5-4cea-a681-0cfb958afdfa">

and won't break any existing unit test cases of Expensify-common lib.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by alexpensify** [comment] 2023-05-27 01:53
Assigning `External` -- I've been able to replicate 

![2023-05-26_18-49-58](https://github.com/Expensify/App/assets/8107070/6b443b0e-6c4d-4495-823d-c07a70999b7f)

![2023-05-26_18-50-41](https://github.com/Expensify/App/assets/8107070/39741b96-649b-443e-b7c8-efbf345ffab7)

![2023-05-26_18-50-14](https://github.com/Expensify/App/assets/8107070/54587af8-81a3-474e-95d4-92c9a25d72e5)

Something weird is when you click edit, notice that the test is surrounded by the `*`.

**Comment by alexpensify** [comment] 2023-05-28 15:51
Waiting for proposals

**Comment by alexpensify** [comment] 2023-05-30 21:41
Waiting for proposals

**Comment by AndrewGable** [comment] 2023-06-01 19:54
PR has been merged, let's update the app to use this new code

**Comment by alexpensify** [comment] 2023-06-02 20:23
The PR for this GH is ready or review!

**Comment by alexpensify** [comment] 2023-06-04 15:43
PR is waiting for review

**Comment by eh2077** [comment] 2023-06-06 14:55
Friendly bump @rushatgabhane , do you have a chance to review the PR https://github.com/Expensify/App/pull/20030 to update the version of expensify-common?

**Comment by alexpensify** [comment] 2023-06-08 22:58
Merged! Now we wait for automation!

**Comment by alexpensify** [comment] 2023-06-11 18:08
No automation yet

**Comment by alexpensify** [comment] 2023-06-14 19:30
@rushatgabhane and @eh2077 - Please apply for the job below to prepare for the payment period, thanks! 

https://www.upwork.com/jobs/~0103b41c91900b4447

**Comment by dhanashree-sawant** [comment] 2023-06-15 05:35
Hi @alexpensify, should I also apply to the job for reporting bonus?

**Comment by dhanashree-sawant** [comment] 2023-06-15 15:25
That's okay, I have applied to the job

**Comment by alexpensify** [comment] 2023-06-19 22:40
@rushatgabhane - Please apply for the job below, so I can prepare the payment. Thanks!

https://www.upwork.com/jobs/~0103b41c91900b4447

Heads up @eh2077 - I need another day here since I need to verify if there is an urgency bonus. I see two PRs for this assignment. One was merged quickly and the other one was delayed because of illness. I need an extra day to check my findings.

**Comment by alexpensify** [comment] 2023-06-20 22:24
I've prepared the payments for @dhanashree-sawant and @eh2077 within Upwork. Please accept and I can complete the process. 

@rushatgabhane - Please apply and I can start the process. Thank you!

**Comment by eh2077** [comment] 2023-06-20 23:02
@alexpensify  Accepted. Thank you!

**Comment by dhanashree-sawant** [comment] 2023-06-21 03:46
@alexpensify Accepted. Thank you!

**Comment by alexpensify** [comment] 2023-06-21 15:08
@eh2077 and @dhanashree-sawant - I've completed the process in Upwork for y'all. 

@rushatgabhane - I've started that process to pay you via Upwork. Please accept and I can finish the process. Also, can you complete this checklist: 

https://github.com/Expensify/App/issues/19607#issuecomment-1588262151

I can close this GH after those actions. Thank you!

**Comment by alexpensify** [comment] 2023-06-22 18:32
Alright, everyone has been paid out here via Upwork! Great work!

**Closed by alexpensify** 2023-06-22 18:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
