### ISSUE TITLE
[$1000] nothing happens on click of mark as unread option on welcome message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21512] opened 2023-06-25 14:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. from userA, go to Settings > Workspaces
2. click on New workspace button
3. go to #announce and send any message
4. click on header
5. go to Settings > Welcome message
6. add any message and click on save button
7. go to Settings > Workspaces >Members > Invite
8. invite userB
9. from userB, go to #announce
10. hover on welcome message and click on mark as unread option
## Expected Result: 
welcome message should be marked as unread
## Actual Result: 
nothing happens on click of mark as unread option
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/dde5dbe8-7301-4cfb-bc57-8594513e43cc

https://github.com/Expensify/App/assets/43996225/49155206-a793-4a79-8e0e-a55e9d2efeb5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687271371891569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01083dff0f4fba9afa</li>
        <li>Upwork Job ID: 1674784304639074304</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2023-06-27 16:30
I think this might be intended so will take this for discussion in Slack.

**Comment by flaviadefaria** [comment] 2023-06-30 14:18
We agreed this is a bug so I added the external label.

**Comment by flaviadefaria** [comment] 2023-07-03 13:19
The expected result hasn't changed:
>welcome message should be marked as unread

**Comment by MaciejSWM** [comment] 2023-07-05 08:29
Hey! I’m Maciej from Software Mansion, an expert agency, and I’d like to investigate this issue.

**Comment by flaviadefaria** [comment] 2023-07-05 21:31
Great @MaciejSWM! Feel free to submit a proposal and we'll then assign you to the issue!

**Comment by MaciejSWM** [comment] 2023-07-07 11:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User can't mark welcome message as unread.

### What is the root cause of that problem?

Backend doesn't handle welcome message correctly. See the following scenario:

I do have two messages in the chat. First one says *User A message*, second message is the welcome message.
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/85628901/6cf7cfba-c657-453a-8f48-34e8e1979ee1">

Backend's `lastVisibleActionCreated`, `lastVisibleActionLastModified` and `lastMessageText` fields are not taking the welcome message into consideration. Backend thinks that the *User A message* is the latest one (being created at `14:32:58:320`), where in fact the welcome message has a later date (`14:34:23:920`).

<img width="378" alt="image" src="https://github.com/Expensify/App/assets/85628901/f7d88057-c339-4a5e-85dd-f65913b91013">

This breaks both marking a welcome message as read, but also makes the `OptionRowLHN.js` render *User A message*, instead of the welcome message:
<img width="382" alt="image" src="https://github.com/Expensify/App/assets/85628901/69a34e3f-e300-4df6-b733-4550b31b3d8c">


The message list is where we can confirm that the welcome message is newer than the *User A message*, since it's created at `14:34:23:920`:
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/85628901/8718d770-9093-4f10-a11a-f14f3be6ad64">


### What changes do you think we should make in order to solve the problem?

Fix is needed on the backend side - In the `POST http://localhost:8080/api?command=OpenReport` - fields like `lastVisibleActionCreated`, `lastVisibleActionLastModified` and `lastMessageText` do not treat welcome message as the `last` message, they treat the message before welcome message as the last message, which is incorrect.

### What alternative solutions did you explore? (Optional)

**Comment by jscardona12** [comment] 2023-07-17 01:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Nothing happens on click of mark as unread option on welcome message
### What is the root cause of that problem?
The root cause is that the Welcome Message is not take into account on the `lastVisibleActionCreated` this is reflecting the creation of the channel but not the welcome message, so when it's just the welcome message in the report the `lastVisibleActionCreated` is always going to be bigger than the `reportActionCreated` but the `lastReadTime` is calculated taking a ms of the `reportActionCreated`.

https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/libs/actions/Report.js#L738-L745


### What changes do you think we should make in order to solve the problem?
in /src/libs/actions/Report.js  make a condition that if last `lastVisibleActionCreated` > `reportActionCreated` take `lastVisibleActionCreated` instead of `reportActionCreated` becasue that means that the reportAction wasn't take into account. 

The fix will be like this: 
`const lastVisibleActionCreated = lodashGet(allReports, [reportID, 'lastVisibleActionCreated'], '0');
 const actionCreationTime = reportActionCreated < lastVisibleActionCreated? reportActionCreated: lastVisibleActionCreated;`
##Fix Working


https://github.com/Expensify/App/assets/16781411/e306218b-b842-4010-bbb0-3342988535b4

**Comment by flaviadefaria** [comment] 2023-07-17 07:54
@parasharrajat do any proposals look good?

**Comment by jscardona12** [comment] 2023-07-17 12:38
Hi @parasharrajat, i just added an alternative solution to my proposal as well. Let me know what do oyu think about the [Proposal](https://github.com/Expensify/App/issues/21512#issuecomment-1637258507).

Thank you.

**Comment by jscardona12** [comment] 2023-07-18 14:14
Hi @parasharrajat i was testing and my principal solutions is not working on every solution but the Alternnative Solution is working. Please let me know what do you think about the altternative solution. 

Thank you.

**Comment by jscardona12** [comment] 2023-07-21 12:33
Hi @parasharrajat, what do you think about the proposal?

**Comment by flaviadefaria** [comment] 2023-07-24 12:18
@parasharrajat do you have an update here? Do we have a proposal?

**Comment by jscardona12** [comment] 2023-07-25 15:48
Hi @parasharrajat, Yeah this is what i mean `Here, it seems that you are saying, we do not update the lastVisibleActionCreated with the created time of welcome message action for a report.` 

I mean by bigger, older. 

The first solution have side effects, lets descart that and focus on the alternative solution. 

I will make some tests and get back with the results.

Thanks

**Comment by jscardona12** [comment] 2023-07-25 17:40
@parasharrajat just update the [Proposal](https://github.com/Expensify/App/issues/21512#issuecomment-1637258507) making the alternative solution the prncipal solution. I also tmake some tests and there where some edge cases, i updated  the proposal tto change the `lastVisibleActionCreatted` just when ` reportActionCreated > lastVisibleActionCreated` that is what indicates that the welcome message was not taken into account to update the `lastVisibleActionCreatted`.

With this changes there is no Sife effects ont he users that does not see the welcome message. 

Pls let me know what do you think.

Thanks

**Comment by jscardona12** [comment] 2023-07-25 22:50
@parasharrajat i was checking and didn't found another function to update `lastVisibleActionCreated`. 
Please let me know if you find better function to update.

Thanks!

**Comment by jscardona12** [comment] 2023-07-26 20:35
@parasharrajat with my proposal there would not be any side effects. It will just fix the data. Also the error only happens when the only visible message is the Welcome Message

**Comment by techievivek** [comment] 2023-07-27 09:45
@jscardona12 

Hey, I am going through the proposal and trying to understand it and have a few questions to start with.

> so when it's just the welcome message in the report the lastVisibleActionCreated is always going to be bigger than the reportActionCreated but the lastReadTime is calculated taking a ms of the reportActionCreated.

`when it's just the welcome message`, this is not true, right? If you look at the video in the description of the issue, there exists a different message as well from the policy owner, right? Or did you mean to assert something else? 

Also, why would `lastVisibleActionCreated is always going to be bigger than the reportActionCreated`, if we don't account for the welcome message then shouldn't both the things be same? I am having a bit of a hard time understanding this.

Can you explain this in terms of three things(created action, welcome message and any other message by the owner).

**Comment by jscardona12** [comment] 2023-07-27 13:37
Hi @techievivek, you are right it just happenns when the Welcome Message is the last action. 
about `lastVisibleActionCreated is always going to be bigger than the reportActionCreated` i re-read my explanation and i got a little tangled explaining this. so i'm going to explain it again: 

When the last action in the chat is the welcome message. the `lastVisibleActionCreated` should be the same or newer than the `reportActionCreated` but in this case the `lastVisibleActionCreated` is "bigger", i meant older, than the `reportActionCreated` , because it's not getting updated when a welcome message is created.  

So the fix consist in detect when the `lastVisibleActionCreated` is older that the `reportActionCreated` (`isReportLastAction`) so we can detect that the `lastVisibleActionCreated` wasn't updated, and this means that the reportAction is a Welcome Message. If this is the case we are setting `lastVisibleActionCreated` as `reportActionCreated` to correctly update the welcome message as the lastVisibleActionCreated.

Let me now if you have any doubts! 

Thanks

**Comment by techievivek** [comment] 2023-07-31 06:15
@jscardona12 It is still not clear to me why `lastVisibleActionCreated` would be older than `reportActionCreated` in any situation. 

There are 2 situations here:
1. If my report has only created action, then I expect both the `reportActionCreated` and `lastVisibleActionCreated` to be the same, right? 
2. Now, if it has 2 actions(created and welcome message), and if we don't consider the welcome message, then I would still guess both `reportActionCreated` and `lastVisibleActionCreated` would have the same value. If it were older, it must point to some action, right? What action is that?

Also, I feel like the root cause of this is the backend, and what you have suggested is just a hack from the front end to fix this issue. Let me know if I am misunderstanding this. Thanks

**Comment by techievivek** [comment] 2023-07-31 06:22
Added a comment on the slack thread https://expensify.slack.com/archives/C01SKUP7QR0/p1690784365313359?thread_ts=1687883762.263609&cid=C01SKUP7QR0 to confirm if we really want to show the unread option on the welcome message.

**Comment by flaviadefaria** [comment] 2023-07-31 08:19
Waiting for a final decision in the Slack thread.

**Comment by flaviadefaria** [comment] 2023-08-01 07:28
Closing this issue as per the [conversation in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1689188643810819).

**Comment by flaviadefaria** [comment] 2023-08-01 11:31
@parasharrajat given all the effort you put here in reviewing proposals we're going to give you 50% of the planned compensation. I'll sent you an offer in UW for $500, ok?

**Comment by flaviadefaria** [comment] 2023-08-01 14:30
Awesome, so I'll leave this open until you have been paid in ND.

**Comment by JmillsExpensify** [comment] 2023-08-02 23:43
Reviewed [details](https://github.com/Expensify/App/issues/21512#issuecomment-1660129072) for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Closed** 2023-08-03 07:39 UTC
Labels: Engineering, Weekly, Internal, Bug
