### ISSUE TITLE
[HOLD for payment 2024-01-03] [$500] Avatar - Updated User's B avatar is not visible in real time on User A search page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33353] opened 2023-12-20 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
1. User A and User B should have previous conversation
Steps:
1. User A navigates to Search page ( last conversation with User B should be visible)
2. User B update profile Avatar

## Expected Result:
Avatar from User B in 1:1 conversation in Search page should be updated in real time

## Actual Result:
Updated User's B avatar is not visible in real time on User A search page
User A must refresh the app or navigate to other page to see updated Avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b5638fdf-6c4e-4d9a-a0eb-f1b15c5c5000

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0216790020f8fbe</li>
        <li>Upwork Job ID: 1737458622592098304</li>
        <li>Last Price Increase: 2023-12-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28066439</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-12-20 14:23
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/33353#issuecomment-1864459689) looks good to me
🎀 👀 🎀 C+ reviewed

**Comment by blimpich** [comment] 2023-12-20 20:00
@situchan @bernhardoj that `!` was very recently added by @TMisiukiewicz for performance reasons. Please tell me how we will address the performance issue in the solution to this issue. See [this comment](https://github.com/Expensify/App/pull/32962/files#r1430195035) for context.

**Comment by situchan** [comment] 2023-12-20 20:14
@blimpich this is regression from [function migration refactor](https://github.com/Expensify/App/pull/28977)

class component:
<img width="820" alt="Screenshot 2023-12-21 at 2 10 47 AM" src="https://github.com/Expensify/App/assets/108292595/2e2346f4-c644-40ca-8f33-6b3e4fa5ed32">

function component:
<img width="820" alt="Screenshot 2023-12-21 at 2 10 35 AM" src="https://github.com/Expensify/App/assets/108292595/e1373cd3-8625-421e-8539-d2f455cf06d5">

As you see all conditions are inverted but only that line.

----

> @situchan @bernhardoj that `!` was very recently added by @TMisiukiewicz for performance reasons. Please tell me how we will address the performance issue in the solution to this issue. See [this comment](https://github.com/Expensify/App/pull/32962/files#r1430195035) for context.

This PR removed `!` (not added `!`) 😄  but it was [reverted](https://github.com/Expensify/App/pull/33297) due to regressions.

So all of us are going in right direction 🙂

**Comment by situchan** [comment] 2023-12-20 20:17
So in latest main (with `!`), `OptionRow` is re-rendered always whenever any prop is changed.
Removing `!` will fix 2 bugs:
- this performance issue (re-render) (not noticeable by user)
- this GH (clearly noticeable by user)

**Comment by TMisiukiewicz** [comment] 2023-12-20 20:24
PR with this change is open again after fixing regressions: #33347 🙂

**Comment by blimpich** [comment] 2023-12-20 20:27
Ah I see, I misunderstood. My `App` repo is a few days out of date and so when I looked at the git blame locally I was getting slightly out of date information. Thank you for the explanation @situchan.

Looks like https://github.com/Expensify/App/pull/33347 fixes this bug. @TMisiukiewicz can you add this issue to the list of issues fixed by your PR?

**Comment by situchan** [comment] 2023-12-20 20:29
I see that PR was already C+ reviewed but I can review again focusing on testing repro step in this GH.

**Comment by blimpich** [comment] 2023-12-20 21:43
@situchan That sounds good to me. Assigning @TMisiukiewicz since they have fixed the bug with their PR.

**Comment by TMisiukiewicz** [comment] 2023-12-21 06:32
Linked this issue in a PR ✅

**Comment by situchan** [comment] 2024-01-03 12:00
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28977
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28977/files#r1440372517
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This was purely PR author's mistake and could have been caught earlier during PR review.

We can skip regression test as caught by Applause team

**Comment by situchan** [comment] 2024-01-03 12:02
@trjExpensify I think you accidentally closed this issue

**Comment by trjExpensify** [comment] 2024-01-03 12:29
I did indeed!

**Comment by trjExpensify** [comment] 2024-01-03 12:33
Thanks, settled up $500 with @situchan for the C+ PR review.

**Closed by trjExpensify** 2024-01-03 12:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
