### ISSUE TITLE
[HOLD for payment 2024-02-05] [HOLD for payment 2024-02-01]  Group chat - Group chat shows only creator avatar in LHN and creator in member list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35075] opened 2024-01-24 16:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click FAB > Start chat
2. Select a few users and create the group chat
3. Click on the chat header
4. Click Members

## Expected Result:
In Step 2, the group chat will show the avatar of current user with +n indicator
In Step 4, member list will include all the members involved

## Actual Result:
In Step 2, the group chat only shows the group creator avatar
In Step 4, member list only includes the group creator

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2dbb04bf-7c45-4177-a578-f09291c6a1ca

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2024-01-24 17:38
Reproduced on staging **v1.4.31-4**

![Screenshot 2024-01-24 at 12 35 23 PM](https://github.com/Expensify/App/assets/6833644/f4a0ac49-6f75-40e8-9c20-b6fa3b54096e)

**Comment by arosiclair** [comment] 2024-01-24 17:40
Definitely seems to be a backend issue in `OpenReport` as there are a bunch of duplicate/unnecessary Onyx updates in there.

**Comment by arosiclair** [comment] 2024-01-24 20:20
Okay this seems to be caused by [ReportUtils.getVisibleMemberIDs](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L1520). It uses `report.visibleChatMemberAccountIDs` but this is empty for group chats. That doesn't seem right, but that is how both staging and prod APIs behave so this just seems to be a regression from https://github.com/Expensify/App/pull/34237.

Reverting the PR fixes the issue:

![Screenshot 2024-01-24 at 3 19 06 PM](https://github.com/Expensify/App/assets/6833644/2883b52e-18ad-4a1c-9008-0a1606aa7ada)

cc @FitseTLT @akinwale @MonilBhavsar

**Comment by arosiclair** [comment] 2024-01-24 20:51
Revert is [here](https://github.com/Expensify/App/pull/35099). 

@MonilBhavsar I don't have all of the context, but `ReportUtils.getVisibleMemberIDs` looks like data massaging and seems wrong to me. I think we should fix our Onyx updates to send this array correctly for all types of reports so there's no need for that function.

**Comment by thienlnam** [comment] 2024-01-25 05:33
Merged and CPed - thanks @arosiclair!

**Comment by arosiclair** [comment] 2024-01-29 19:40
This is all done

**Closed by arosiclair** 2024-01-29 19:40 UTC
Labels: Engineering, Weekly, Awaiting Payment
