### ISSUE TITLE
Add bank account page goes blank while trying to add the same account twice using Plaid

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12895] opened 2022-11-21 17:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Go to Settings > Payments
2. Click Add payment method > Bank account
3. Complete the process on Plaid to add a new bank account
4. On Add bank account page, choose the account
5. Click save & continue
6. Click Continue
7. Again click Add payment method > Bank account
8. Again complete the process on Plaid for the same bank account

## Expected Result:
Bank account is added

## Actual Result:
Blank page is displayed and an error also flashes for a second

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Can't check
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203124821-991cb98e-5f8a-46df-804f-bb124851ece1.mp4

Uploading Screen Recording 2022-11-21 at 2.18.45 PM.mov…

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669022852610099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2022-11-21 23:16
This is happening because we're running into [this exception](https://github.com/Expensify/Web-Expensify/blob/6826d80aa23f04f662c4999095db97243c49f375/lib/Plaid/API.php#L153-L155) (internal).

That said, it doesn't sound like an error per se - the user just selected a list of accounts that are already linked to Expensify. Maybe we could directly show the success panel instead? cc @nkuoch if you have an opinion - looks like you recently added that flow.

**Comment by francoisl** [comment] 2022-11-22 02:59
Alternatively we can show the error message as intended by fixing the `jsonCode` [here](https://github.com/Expensify/Web-Expensify/blob/7e7c1eb933d5688fbd457211ca104b89feaa6f9b/api.php#L1566-L1568), because right now we catch the exception and return a 200 response, so NewDot ends up applying the `successData` of the request, which removes the `error` field.

**Comment by nkuoch** [comment] 2022-11-22 14:25
We should show the error message "Could not find any bank accounts that you haven't already added.". So yes, let's fix the jsonCode

**Comment by kadiealexander** [comment] 2022-11-30 05:33
@francoisl since the PR above has merged, should I have the customer try again?

**Closed** 2022-11-30 18:07 UTC
Labels: Reviewing, Engineering, Daily, Bug

**Comment by francoisl** [comment] 2022-12-01 02:14
Yes for sure. @kadiealexander is it something you can assist with please?

**Comment by kadiealexander** [comment] 2022-12-14 01:49
Apologies, missed the pings on this! Upwork job is [here](https://www.upwork.com/jobs/~01f60b347e6a947e67), I've sent you a contract @adeel0202 please let me know once you've accepted.

**Comment by kadiealexander** [comment] 2023-01-25 17:10
Sorry @adeel0202!! I've just issued payment.
