### ISSUE TITLE
[Pay meow][$1000] Legal name - When tapping on the Legal Last Name field, the error message alternates between 'This field is required' and 'Name can only include Latin characters

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31391] opened 2023-11-15 17:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Profile - Personal details - Legal name
4. Try invisible characters from this site https://invisible-characters.com/3164-HANGUL-FILLER.html
5. Put it on both field
6. Click Save
7. Put cursor on legal first name than on Legal Last name

## Expected Result:
When tapping on the Legal Last Name field, the error message shouldn't switch between 'This field is required' and 'Name can only include Latin characters

## Actual Result:
When tapping on the Legal Last Name field, the error message alternates between 'This field is required' and 'Name can only include Latin characters

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e37f8ecf-37ce-4620-8b2c-a6fc447cb635

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df7fd3e27a4b1629</li>
        <li>Upwork Job ID: 1724836966037389312</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 27985228</li>
<li>bernhardoj | Contributor | 28072802</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-11-15 17:11
# Proposal

## WHat is the root cause of this problem
The root cause is that while validating, we don't trim the values and they contain non-latin charachters (spaces)

## What changes should be made to fix this?
We should trim the legal name values before validating

**Comment by 5war00p** [comment] 2023-11-15 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Switching between error messages when the message is empty in the legal name page
### What is the root cause of that problem?
Chained if conditions causing this error message switch, instead we can have if-else if-else blocks only.
### What changes do you think we should make in order to solve the problem?

```
        if (!ValidationUtils.isValidLegalName(values.legalFirstName)) {
            ErrorUtils.addErrorMessage(errors, 'legalFirstName', 'privatePersonalDetails.error.hasInvalidCharacter');
        } 
        else if (_.isEmpty(values.legalFirstName)) {
            errors.legalFirstName = 'common.error.fieldRequired';
        }
        else if (values.legalFirstName.length > CONST.LEGAL_NAME.MAX_LENGTH) {
            ErrorUtils.addErrorMessage(errors, 'legalFirstName', ['common.error.characterLimitExceedCounter', {length: values.legalFirstName.length, limit: CONST.LEGAL_NAME.MAX_LENGTH}]);
        }
        else if (!ValidationUtils.isValidLegalName(values.legalLastName)) {
            ErrorUtils.addErrorMessage(errors, 'legalLastName', 'privatePersonalDetails.error.hasInvalidCharacter');
        } else if (_.isEmpty(values.legalLastName)) {
            errors.legalLastName = 'common.error.fieldRequired';
        }
        else if (values.legalLastName.length > CONST.LEGAL_NAME.MAX_LENGTH) {
            ErrorUtils.addErrorMessage(errors, 'legalLastName', ['common.error.characterLimitExceedCounter', {length: values.legalLastName.length, limit: CONST.LEGAL_NAME.MAX_LENGTH}]);
        }
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by mananjadhav** [comment] 2023-11-16 19:20
> When tapping on the Legal Last Name field, the error message shouldn't switch between 'This field is required' and 'Name can only include Latin characters

@Christinadobrzyn I think before I choose any proposal we should clarify, which error should be shown exactly? The expected result doesn't mention this.

**Comment by Christinadobrzyn** [comment] 2023-11-17 23:42
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

**Comment by jasperhuangg** [comment] 2023-11-20 20:32
> Good question - Adding Engineering lable to get a [buddy check](https://github.com/Expensify/App/issues/31391#issuecomment-1815167959):
> 
> I think the error workflow should be the following @jasperhuangg can you provide feedback?
> 
> * User enters non-Latin characters, throw the `Name can only include Latin characters.` error
> * User entered non-Latin characters in one field, the other field has no error
> * User removes the non-Latin characters from one or both fields, throw the `This field is required.` error
> * The `Please fix the errors in the form before continuing.` error shows at the bottom of the page until the fields are correctly filled out
> 
> Example:
> 
>  2023-11-16_17-01-15.mp4

I think @Christinadobrzyn's ideas here seem fine. Let's move forward with solutions that follow them!

**Comment by Tony-MK** [comment] 2023-11-20 23:53
@jasperhuangg Can you recheck the bug? It seems to have changed. It accepts all types of characters without displaying an error message.

**Comment by Christinadobrzyn** [comment] 2023-11-27 18:44
Taking this back from @stephanieelliott as I'm back from ooo. 

Thanks for the review @jasperhuangg! 

@Tony-MK I can reproduce based on the steps in the original post (you need to use invisible characters like U+3164)

we'll wait for @mananjadhav to review! Thanks!

**Comment by Christinadobrzyn** [comment] 2023-11-29 18:45
hi @mananjadhav can you review the proposals to see if any will work?

**Comment by Christinadobrzyn** [comment] 2023-11-29 20:07
Okay, I'll increase the payment to see if that gets more proposals!

**Comment by shreyfirst** [comment] 2023-11-29 20:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Errors are alternating when there is an invisible (non-latin) character. The first error is that you cannot have any non-latin characters, the second error is that both fields are required.

### What is the root cause of that problem?
There isn't a standardization of the ErrorUtils.addErrorMessage() function and rather we are handling error messages differently for the two cases.

### What changes do you think we should make in order to solve the problem?
We should be using the ErrorUtils.addErrorMessage() whenever possible, and [replace lines 60 and 69](https://github.com/Expensify/App/blob/4618b398e9605f561bf3f295cfe1f4b0ae26b4fa/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L57-L74) with the correct error message handler.

**Comment by incognick** [comment] 2023-11-29 22:19
## Proposal
Errors are alternating between two different errors based on if the `validate` function is called or the `submit` button is called. 

### What is the root cause of the problem

When the form is saved, invisible characters are removed prior to checking validation. This causes a different flow compared to just calling validate (e.g. when tab or clicking away to change focus)

### Solution

First prepare the values by removing invisible characters before validation is called, then do validation.  The result is it will show "This field is required" for the invisible characters.  

```js
function LegalNamePage(props) {
    const styles = useThemeStyles();
    usePrivatePersonalDetails();
    const legalFirstName = lodashGet(props.privatePersonalDetails, 'legalFirstName', '');
    const legalLastName = lodashGet(props.privatePersonalDetails, 'legalLastName', '');
    const isLoadingPersonalDetails = lodashGet(props.privatePersonalDetails, 'isLoading', true);

    const validate = useCallback((values) => {
        const trimmedStringValues = ValidationUtils.prepareValues(values);
        ...
```

**Comment by incognick** [comment] 2023-11-29 22:20
Contributor details
Your Expensify account email: nsphilli@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d734b4cabc4ce3c5

**Comment by shubham1206agra** [comment] 2023-11-30 08:25
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Legal name - When tapping on the Legal Last Name field, the error message alternates between 'This field is required' and 'Name can only include Latin characters

### What is the root cause of that problem?

This is due to the value difference when executing `onValidate` in the `FormProvider` component when submitting the form or on input change.

We use non-trimmed values for validation in the onBlur and onInputChange methods, whereas when submitting the form, we use trimmed values. This creates a change in values, which changes the error in the form.

### What changes do you think we should make in order to solve the problem?

We can solve this in 2 steps:
1. Add a prop (says `required`) to InputWrapper to mark the fields that require input.
2. Start using the non-trimmed values in validation inside the submit function, and for required input, add the error inside the `onValidate` function instead of the validate function provided by the prop `validate` in `FormProvider`. For this step, use https://github.com/shubham1206agra/App/tree/test-validation branch).

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2023-11-30 13:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When tapping on the input fields with invisible characters, the error messages switch between `The field is required` and `Name can only include Latin characters`. We want to avoid the switch happening here. 

### What is the root cause of that problem?

In `FormProvider`, we do not remove the invisible characters during validation on blur [here](https://github.com/Expensify/App/blob/78162d09f3cf2c1ab9bf58087f381b277796bffb/src/components/Form/FormProvider.js#L303) whereas we remove the invisible characters during `submit` [here](https://github.com/Expensify/App/blob/78162d09f3cf2c1ab9bf58087f381b277796bffb/src/components/Form/FormProvider.js#L199). Since we directly pass the `values` to `validate` [here](https://github.com/Expensify/App/blob/78162d09f3cf2c1ab9bf58087f381b277796bffb/src/components/Form/FormProvider.js#L128), `submit` will have trimmed values and we will have input values in all other cases. This is the root cause.  

### What changes do you think we should make in order to solve the problem?

In order to solve the problem, we need to have consistency in the values passed in `validate` function [here](https://github.com/Expensify/App/blob/78162d09f3cf2c1ab9bf58087f381b277796bffb/src/components/Form/FormProvider.js#L128). Here, I would suggest that we always pass the trimmed values for validation like this.

            const validateErrors = validate(trimmedStringValues) || {};


### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2023-11-30 20:24
I believe @mananjadhav is unavailable so I'm going to assign another C+

**Comment by jasperhuangg** [comment] 2023-11-30 20:26
Got it, sorry for the confusion!

**Comment by jasperhuangg** [comment] 2023-12-04 18:28
@mananjadhav bump!

**Comment by Christinadobrzyn** [comment] 2023-12-05 18:26
just DMd @mananjadhav to see if we can get a a check on https://github.com/Expensify/App/issues/31391#issuecomment-1836012505

**Comment by sourcecodedeveloper** [comment] 2023-12-05 21:48
@mananjadhav please review proposal. I have tested for the three error handling criteria mentioned.

**Comment by mananjadhav** [comment] 2023-12-06 02:41
I am still unwell and not sure if I can get today. Best to reassign @jasperhuangg @Christinadobrzyn.

**Comment by shubham1206agra** [comment] 2023-12-06 05:57
@mananjadhav I can take it from here if you want.
And I will pass one issue whenever you feel good.
If I get this reassignment, please consider my proposal redacted.

**Comment by shubham1206agra** [comment] 2023-12-06 13:07
@Christinadobrzyn, Is there a specific reason we are not setting the trimmed value of the form on the submit operation? Do we need to retain the full value even after the submit operation?

**Comment by Christinadobrzyn** [comment] 2023-12-06 16:45
Sorry @shubham1206agra I'm not an engineer so I don't know what a trimmed value is. 

@jasperhuangg can you answer @shubham1206agra question - https://github.com/Expensify/App/issues/31391#issuecomment-1842846370 - it seems like we're deciding if we can use that or not?

**Comment by situchan** [comment] 2023-12-06 16:46
I think @luacmartins is best to handle this as Form manager

**Comment by sourcecodedeveloper** [comment] 2023-12-06 17:32
@shubham1206agra Please take look at [proposal](https://github.com/Expensify/App/issues/31391#issuecomment-1833996178). I have tested the proposal for the following
User enters non-Latin characters, throw the Name can only include Latin characters. error
User entered non-Latin characters in one field, the other field has no error
User removes the non-Latin characters from one or both fields, throw the This field is required. error
The Please fix the errors in the form before continuing. error shows at the bottom of the page until the fields are correctly filled out

**Comment by shubham1206agra** [comment] 2023-12-06 18:00
> @Christinadobrzyn, Is there a specific reason we are not setting the trimmed value of the form on the submit operation? Do we need to retain the full value even after the submit operation?

@luacmartins Can you answer this?

**Comment by shubham1206agra** [comment] 2023-12-07 05:18
I like @tienifr's proposal, but there is a minor edge case missing. What if I enter only space in first and last name, and press submit. And after an empty field error is shown, I again focus and blur on the fields. The error will be missing which I think should persist.

**Comment by sourcecodedeveloper** [comment] 2023-12-07 11:13
@shubham1206agra In the submit function for FormProvider the trimmedStringValues are being passed to validate, but onBlur inputValues are passed. If the trimmedStringValues are passed to validate onBlur, the space character error message shows but the invisible character does not show error message.
https://github.com/Expensify/App/blob/37ddb03a0e8fd85faf635446762064180ad6a88c/src/components/Form/FormProvider.js#L119
To persist the error message for only space character onBlur, in the validate function for LegalNamePage, the values for legalFirstName and legalLastName can be trimmed. Please review proposal.

**Comment by shubham1206agra** [comment] 2023-12-07 15:24
This is the actual behaviour I look for
* User enters non-Latin characters, throw the `Name can only include Latin characters.` error
* User entered non-Latin characters in one field, the other field has no error
* User removes the non-Latin characters from one or both fields, throw the `This field is required.` error if the field is empty.
* In case of Latin characters only, if the field only contains trimmable characters (space, new line, etc), throw the `This field is required.` error.
* Another case is of 40 space characters at beginning (or end) and entering some letters should not throw the `Max limit` error
* The `Please fix the errors in the form before continuing.` error shows at the bottom of the page until the fields are correctly filled out

**Comment by shubham1206agra** [comment] 2023-12-07 15:25
Please post the video showing all these cases.

**Comment by shubham1206agra** [comment] 2023-12-08 07:27
@Krishna2323 @sourcecodedeveloper Please provide a branch to test and also post a video covering all cases. Thanks

**Comment by sourcecodedeveloper** [comment] 2023-12-08 09:51
@shubham1206agra videos are included in [proposal](https://github.com/Expensify/App/issues/31391#issuecomment-1833996178). Please use [branch](https://github.com/sourcecodedeveloper/App/tree/validateFormProvider) for testing.

**Comment by shubham1206agra** [comment] 2023-12-08 12:22
> @shubham1206agra videos are included in [proposal](https://github.com/Expensify/App/issues/31391#issuecomment-1833996178). Please use [branch](https://github.com/sourcecodedeveloper/App/tree/validateFormProvider) for testing.

This didn't work.

**Comment by shubham1206agra** [comment] 2023-12-08 13:11
Enter the first name correctly and put only non Latin space given above in the last name and then try to press enter

**Comment by shubham1206agra** [comment] 2023-12-08 13:23
> > Enter the first name correctly and put only non Latin space given above in the last name and then try to press submit
> 
> @shubham1206agra 
> Entering non latin character and space throws 'Name can only include Latin characters.' That would be expected.
> 
> [poc.webm](https://github.com/Expensify/App/assets/141340971/e35c1cf8-71f6-44c8-8b63-43c7361d6733)
> 

I mean https://invisible-characters.com/3164-HANGUL-FILLER.html character

**Comment by sourcecodedeveloper** [comment] 2023-12-08 13:55
@shubham1206agra Please get latest from [branch](https://github.com/sourcecodedeveloper/App/tree/validateFormProvider). The inputID was not being set onInputChange.

**Comment by sourcecodedeveloper** [comment] 2023-12-11 07:40
@shubham1206agra I have included video in [proposal](https://github.com/Expensify/App/issues/31391#issuecomment-1833996178) covering the https://invisible-characters.com/3164-HANGUL-FILLER.html character and the [branch](https://github.com/sourcecodedeveloper/App/tree/validateFormProvider) can be tested. The error message triggers as expected. Please review.

**Comment by shubham1206agra** [comment] 2023-12-12 11:15
Will update today

**Comment by shubham1206agra** [comment] 2023-12-12 14:01
Thanks everyone for the proposals.
I have discussed the behaviour with @luacmartins internally, and we have agreed that we should only validate on trimmed values, whether on submit or blur. So, I am selecting @tienifr's [proposal](https://github.com/Expensify/App/issues/31391#issuecomment-1812962048) (specifically the earlier version where he recommended to do same).

🎀 👀 🎀 C+ reviewed

**Comment by shubham1206agra** [comment] 2023-12-12 14:02
@tienifr Can you update your proposal back to the earlier version?

**Comment by shubham1206agra** [comment] 2023-12-12 14:07
Yes

**Comment by shubham1206agra** [comment] 2023-12-12 14:39
We actually modify the values before submitting.

**Comment by s77rt** [comment] 2023-12-12 16:20
I think this will be fixed by https://github.com/Expensify/App/pull/32432

**Comment by shubham1206agra** [comment] 2023-12-12 16:39
@s77rt Partially, we still want to error out whenever we type non-Latin characters in the Legal name form as discussed above.

**Comment by shubham1206agra** [comment] 2023-12-12 16:53
There are some other cases where validation is wrong right now. So, I will open the issues again for proposals after getting https://github.com/Expensify/App/pull/32432 merged.

**Comment by shubham1206agra** [comment] 2023-12-12 16:54
@chrispader Can you put this issue on hold on https://github.com/Expensify/App/pull/32432?

**Comment by Christinadobrzyn** [comment] 2023-12-12 21:56
Updated the subject that this is on hold for https://github.com/Expensify/App/pull/32432

**Comment by chrispader** [comment] 2023-12-12 22:13
> @chrispader Can you put this issue on hold on https://github.com/Expensify/App/pull/32432?

@shubham1206agra i think i'm mentioned accidentally? :)

**Comment by shubham1206agra** [comment] 2023-12-13 01:30
Oh sorry

**Comment by cristipaval** [comment] 2023-12-21 14:04
This is off hold now.

**Comment by shubham1206agra** [comment] 2023-12-21 16:50
There are some other cases where validation is wrong right now. So, I will open the issues again for proposals.

The case is the following.
1. Enter `< 😶‍🌫️>`, and observe the error
2. Remove the space, and again observe the different error.
3. Enter spaces one by one and observe the error changing.

**Comment by Tony-MK** [comment] 2023-12-21 22:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


The legal name form validation doesn't fully agree to these validations [rules](https://github.com/Expensify/App/issues/31391#issuecomment-1845545936)

### What is the root cause of that problem?


1) The legal name form fields are not validated properly when U+3164 (Hangul Filler) is used because the [`removeInvisibleCharacters`](https://github.com/Expensify/App/blob/2b58bd705d95b60a695ccaf3103d933f8fe2b62d/src/libs/StringUtils.ts#L32) function doesn't expect to remove the U+3164 (Hangul Filler) Unicode.

2) The improper validation case for inputs that contain HTML tags, stated on this https://github.com/Expensify/App/issues/31391#issuecomment-1866636269, happens only because the line below is overriding the previous error in `validateErrors[inputID]` from `privatePersonalDetails.error.hasInvalidCharacter` to  'common.error.invalidCharacter'.

https://github.com/Expensify/App/blob/37ddb03a0e8fd85faf635446762064180ad6a88c/src/components/Form/FormProvider.js#L148-L149

### What changes do you think we should make in order to solve the problem?



1) Add the code below to remove U+3164(Hangul Filler) from the input `values` in [`removeInvisibleCharacters`](https://github.com/Expensify/App/blob/2b58bd705d95b60a695ccaf3103d933f8fe2b62d/src/libs/StringUtils.ts#L32) function.

`result = result.replace(/\u3164/gu, '')`

https://github.com/Expensify/App/blob/37ddb03a0e8fd85faf635446762064180ad6a88c/src/libs/StringUtils.js#L148-L149


2) Check if the `validateErrors` already contains the `inputID` key before validating if the `inputValue` contains HTML tags. We will add this condition to the group below.

https://github.com/Expensify/App/blob/37ddb03a0e8fd85faf635446762064180ad6a88c/src/components/Form/FormProvider.js#L148-L149

**Comment by cristipaval** [comment] 2023-12-22 12:05
I'm unassigning myself as I see that @jasperhuangg was already assigned last week when I got assigned to this.

**Comment by Christinadobrzyn** [comment] 2023-12-22 19:42
I think we're reviewing proposals, right? @shubham1206agra?

**Comment by shubham1206agra** [comment] 2023-12-22 19:44
Yes

**Comment by bernhardoj** [comment] 2023-12-28 13:34
> The case is the following.

> Enter < 😶‍🌫️>, and observe the error
> Remove the space, and again observe the different error.
> Enter spaces one by one and observe the error changing.

`<😶‍🌫️>` is detected as an HTML tag and the invalid character error message will be prioritized.
https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/components/Form/FormProvider.js#L131-L165

**Comment by shubham1206agra** [comment] 2023-12-28 14:12
> > The case is the following.
> 
> > Enter < 😶‍🌫️>, and observe the error
> > Remove the space, and again observe the different error.
> > Enter spaces one by one and observe the error changing.
> 
> `<😶‍🌫️>` is detected as an HTML tag and the invalid character error message will be prioritized.
> 
> https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/components/Form/FormProvider.js#L131-L165

Right, but `< 😶‍🌫️>` should also be inavlid character.

**Comment by bernhardoj** [comment] 2023-12-28 14:35
`< 😶‍🌫️>` is not an HTML tag based on the `VALIDATE_FOR_HTML_TAG_REGEX` regex (`<([^>\s]+)` expects to have a non space character after <).
https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/CONST.ts#L851-L853

The regex is the same as the BE, so if we want to change it, we need to change the BE too.

**Comment by shubham1206agra** [comment] 2023-12-28 14:46
Nope this is discussed earlier
This tag is not whitelisted. So it should not work

**Comment by shubham1206agra** [comment] 2023-12-28 14:50
Let me give you a hint here

    VALIDATE_FOR_LEADINGSPACES_HTML_TAG_REGEX has some issues 😊

**Comment by bernhardoj** [comment] 2023-12-28 15:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The legal name (all forms) has an inconsistent way of validating an HTML tag.
`< 😶‍🌫️>` is not detected as an HTML tag, but `< a>` is detected as an HTML tag.
 
### What is the root cause of that problem?
This issue comes from the regex we have to detect the HTML tag. We have 2 regex for that.
https://github.com/Expensify/App/blob/41f80fa31afa6c9e62d9b17d3bc0e35a0379e0e9/src/components/Form/FormProvider.js#L137-L138

The one that we want to focus on is `VALIDATE_FOR_LEADINGSPACES_HTML_TAG_REGEX`.

`VALIDATE_FOR_LEADINGSPACES_HTML_TAG_REGEX` regex will match any HTML tag that has a leading space inside the tag, for example, it will match `< a>`. The reason it doesn't match `< 😶‍🌫️>` is because `VALIDATE_FOR_LEADINGSPACES_HTML_TAG_REGEX` will only match a word, space, and special character after space, and because emoji unicode doesn't belong there, the regex won't match it.

But if we put `<  😶‍🌫️>` (2 leading spaces), then the regex will match it because it found a space after another space.

### What changes do you think we should make in order to solve the problem?

As the intention of the regex is to match an HTML tag with a leading space before it, I think we can simplify it like this:
```
/<([\s]+.+[\s]*)>/
```

The new regex will match a string if
1. It found a space after `<` opening tag at least one
2. Any character between `<` and `>`
3. Optional space before `>`

**Comment by shubham1206agra** [comment] 2023-12-29 09:13
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/31391#issuecomment-1871292151) looks good

🎀👀🎀 C+ reviewed

**Comment by shubham1206agra** [comment] 2023-12-29 09:14
@tylerkaraszewski We are looking to fix https://github.com/Expensify/App/issues/31391#issuecomment-1866636269 case also.

**Comment by bernhardoj** [comment] 2023-12-30 07:19
PR is ready

cc: @shubham1206agra

**Comment by Christinadobrzyn** [comment] 2024-01-23 23:27
working on PR

**Comment by shubham1206agra** [comment] 2024-01-24 09:18
@Christinadobrzyn I think the PR is merged already.

**Comment by mallenexpensify** [comment] 2024-01-31 17:34
@Christinadobrzyn this issue didn't auto update, nor remove the `Reviewing` label.  I updated, can you issue payment plz?  [PR hit production a few weeks ago. ](https://github.com/Expensify/App/pull/33793#issuecomment-1882429812)

**Comment by Christinadobrzyn** [comment] 2024-01-31 18:37
sorry for the delay, paying out now

Payouts due:

Contributor: $1000 @bernhardoj (paid in Upwork here - https://www.upwork.com/jobs/~01df7fd3e27a4b1629)
Contributor+: $1000 @shubham1206agra 

Eligible for 50% #urgency bonus? N

The original Upwork job is closed - @shubham1206agra can you accept my offer in this [Upwork job post](https://www.upwork.com/jobs/~01d23451bb0027d3fd)

**Comment by shubham1206agra** [comment] 2024-02-01 02:05
Accepted

**Comment by Christinadobrzyn** [comment] 2024-02-01 20:07
Paid out @bernhardoj and @shubham1206agra based on this payment summary - https://github.com/Expensify/App/issues/31391#issuecomment-1919708891

@bernhardoj do we need a regression test for this?

**Comment by bernhardoj** [comment] 2024-02-02 03:06
@Christinadobrzyn I think it's easy to be broken, so adding a test would be good

cc: @shubham1206agra

**Comment by shubham1206agra** [comment] 2024-02-02 18:44
@Christinadobrzyn Test case

1. Go to Setting - Profile - Personal details - Legal name
2. Press Save without any blank First Name.
3. Enter `< 😶‍🌫️>`, and observe the error
4. Remove the space(`<😶‍🌫️>`), and again observe the error.
5. Enter spaces one by one after `<` and observe the error.

**Comment by Christinadobrzyn** [comment] 2024-02-02 21:54
Created a regression test GH - https://github.com/Expensify/Expensify/issues/366323

Closing this as complete. Feel free to let me know if anything is needed.

**Closed by Christinadobrzyn** 2024-02-02 21:54 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
