### ISSUE TITLE
[$500] mWeb - IOU - The camera zooms in and out before showing the correct camera feed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34174] opened 2024-01-09 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to any conversation
2. Do a manual IOU
3. Add a receipt

## Expected Result:
It shouldn't zoom by itself.

## Actual Result:
The camera zooms in and out before showing the correct camera feed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8105bfbe-e578-4724-85cd-f2a04dd1bc99

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e326b54d051d789</li>
        <li>Upwork Job ID: 1744787505152335872</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by waterim** [comment] 2024-01-10 17:44
Cant reproduce it.

**Comment by waterim** [comment] 2024-01-10 17:53
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by waterim** [comment] 2024-01-10 18:54
Cant reproduce on IOS web

**Comment by laurenreidexpensify** [comment] 2024-01-12 10:56
@mollfpr are you able to reproduce?

**Comment by mollfpr** [comment] 2024-01-13 11:58
@laurenreidexpensify Yes! I can reproduce it.

https://github.com/Expensify/App/assets/25520267/02fcd434-3f2e-4ecc-8ad9-10265d9167f4

**Comment by waterim** [comment] 2024-01-13 12:38
I can see only a small black screen blink, without a zoom

**Comment by laurenreidexpensify** [comment] 2024-01-16 11:14
@waterim can you try repro again?

**Comment by laurenreidexpensify** [comment] 2024-01-19 12:50
@waterim do you have a proposal yet for a solution?

**Comment by waterim** [comment] 2024-01-19 12:51
Working on it, will update today

**Comment by waterim** [comment] 2024-01-19 19:23
Okay, found a root of this issue, this is not the issue in our code or 'react-webcam' library, this is an issue with webKit, added a link to the issue in react-webcam github:
https://github.com/mozmorris/react-webcam/issues/385

Also tested on the pure react-webcam component, same result, zoom for 1 second and fine after, also attaching link:
https://codepen.io/mozmorris/pen/JLZdoP

I think it can be closed or "in hold" before WebKit release.

**Comment by laurenreidexpensify** [comment] 2024-01-22 12:04
@mollfpr do you agree ^^

**Comment by mollfpr** [comment] 2024-01-22 13:07
@laurenreidexpensify I agree with @waterim. I also tested the snippet code, and it has the same issue on the fresh project. 

> A fix has been merged but I don't know what kind of release schedule WebKit has.

This will be fixed eventually, but we don't have the exact time. So I think we can close this issue.

**Closed** 2024-01-23 11:11 UTC
Labels: External, Daily, Help Wanted, Bug
