### ISSUE TITLE
Web - Attachment viewer shows blank white screen for few seconds

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23904] opened 2023-07-31 00:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Send a pdf or adobe illustrator file
3. Open the pdf after successfully sending it
4. Observe the blank white screen before loading the pdf

## Expected Result:
The attachment viewer should show a loader or the loaded attachment.

## Actual Result:
 It shows a blank white screen after loader and then the actual attachment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bd4ff967-6864-4ce7-b599-120d8acf779f

**Expensify/Expensify Issue URL:**
**Issue reported by:** krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690638809150699
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-07-31 04:27
Can't reproduce on v1.3.47-3 staging version, loading spinner shows for me:

https://github.com/Expensify/App/assets/59587260/c7bace2a-5b56-4828-a3e9-71a334ec4fee

@krishna2323 let me know if you can still reproduce this.

**Comment by kadiealexander** [comment] 2023-08-01 01:55
I can sort of reproduce this, but I don't feel like it's an actual bug:

https://github.com/Expensify/App/assets/59587260/3c6ba782-3d32-4af1-a576-4e3535dfbf94

Have checked in the Slack thread.

**Comment by kadiealexander** [comment] 2023-08-02 00:43
We've agreed in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1690886700362579?thread_ts=1690638809.150699&cid=C049HHMV9SM) that this is not a bug. We don't officially support .AI files yet, and therefore this would need to be requested as a new feature.

Closing for now.

**Closed by kadiealexander** 2023-08-02 00:43 UTC
Labels: Daily, Needs Reproduction, Bug
