### ISSUE TITLE
[HOLD for payment 2022-05-20] [$500] Remove Send Money when no members in room - reported by  @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8357] opened 2022-03-30 02:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Visit the Announce or Admins room of that policy ( it shouldn't have any other member except you )
3. Tap on :heavy_plus_sign: (on left side, near the composer)
4. Select send money/request money

## Expected Result:
It shouldn't show option to send money/ request money

## Actual Result:
It's showing the option and user is able to go through the flow and get error in the end as the user is trying to request/send money to himself

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.46-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/160736636-7f95aa72-9ea4-4a12-a62c-7c43388b9bb0.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647460332448239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2022-03-30 23:22
I agree that we shouldn't error out when this happens, but perhaps instead of completely removing the option we keep it and direct people to invite someone to the room instead.

**Comment by danieldoglas** [comment] 2022-03-31 18:04
Agreed with @tjferriss solution above.

**Comment by Christinadobrzyn** [comment] 2022-04-01 08:43
Posted in Upwork!

Internal Job - https://www.upwork.com/ab/applicants/1509813441766039552/job-details
External job - https://www.upwork.com/jobs/~0176081f4f95677487

**Comment by mollfpr** [comment] 2022-04-01 16:27
### Proposal

Base on https://github.com/Expensify/App/issues/8357#issuecomment-1083753541
We only need to check the `chatType` is `POLICY_ANNOUNCE` or `POLICY_ADMINS`. If either both return participants to empty array. In this way IOUModal will have participants page.

https://github.com/Expensify/App/blob/50496a0a0d7dd283f9936988cda95abf69741342/src/pages/iou/IOUModal.js#L110
```diff
-        const participants = lodashGet(props, 'report.participants', []);

+        const chatType = lodashGet(props, 'report.chatType');
+        const participants = [CONST.REPORT.CHAT_TYPE.POLICY_ADMINS, CONST.REPORT.CHAT_TYPE.POLICY_ANNOUNCE].includes(chatType) ? [] : lodashGet(props, 'report.participants', []);
```

If I'm not wrong `IOUModal` will add `Steps.IOUParticipants` if participants are empty.
https://github.com/Expensify/App/blob/50496a0a0d7dd283f9936988cda95abf69741342/src/pages/iou/IOUModal.js#L131-L137

---

https://user-images.githubusercontent.com/25520267/161304121-f764a27a-6759-4408-bc6e-243516fa89b0.mov

**Comment by Santhosh-Sellavel** [comment] 2022-04-01 17:45
@tjferriss or @danieldoglas Is this the expected OP here?

https://github.com/Expensify/App/issues/8357#issuecomment-1086113910

**Comment by Santhosh-Sellavel** [comment] 2022-04-07 19:32
@iwiznia can we get what is the expected OP here?

**Comment by danieldoglas** [comment] 2022-04-07 20:59
Sorry, I didn't see the tagging here before. 

I think the behavior we expect is to actually remove the "Send Money"/"Request Money" options in the menu in case there's no one in the chat with the user, not giving him the option to ask for anyone else, since the "+" in the chat is related to tasks on that chat.

**Comment by Santhosh-Sellavel** [comment] 2022-04-09 19:21
Thanks, @danieldoglas.

But I am confused here, you have agreed with  @tjferriss [solution](https://github.com/Expensify/App/issues/8357#issuecomment-1083753541) in https://github.com/Expensify/App/issues/8357#issuecomment-1084935322
and the above [comment](https://github.com/Expensify/App/issues/8357#issuecomment-1092194894) adds the negates it.

Is [this](https://github.com/Expensify/App/issues/8357#issuecomment-1086113910) expected OP or just remove the option if there are no users to chat. Thanks!

**Comment by danieldoglas** [comment] 2022-04-13 18:45
@Santhosh-Sellavel 

Yes, you are right. My mistake.

We should aim to do what was suggested by @tjferriss. But then I think the [solution](https://github.com/Expensify/App/issues/8357#issuecomment-1086113910) is not actually inviting people into the room as [suggested](https://github.com/Expensify/App/issues/8357#issuecomment-1083753541), it is actually letting me send/request money to people outside of that room.

**Comment by Santhosh-Sellavel** [comment] 2022-04-13 19:59
Thanks, @danieldoglas. 

> actually letting me send/request money to people outside of that room.

It would create some complications/confusion. Because whatever IOU operation we perform from the chat compose ➕  options is expected to create IOU for the specific chat report.

I think we should just hide those options instead because the user can always create IOU from LHN ➕ button.

@iwiznia What do you think?

**Comment by Christinadobrzyn** [comment] 2022-04-14 05:22
I'm going to be ooo until April 26th so I'm going to assign a new CM to this issue.

**Comment by iwiznia** [comment] 2022-04-18 14:59
Sorry, I was out for a few days. I agree with removing the option altogether when there are no participants other than you, but I don't think we should hack the participants like suggested [here](https://github.com/Expensify/App/issues/8357#issuecomment-1086113910).

**Comment by brianmuks** [comment] 2022-04-18 15:05
> Sorry, I was out for a few days. I agree with removing the option altogether when there are no participants other than you, but I don't think we should hack the participants like suggested [here](https://github.com/Expensify/App/issues/8357#issuecomment-1086113910).

@iwiznia what do you think of my proposal :https://github.com/Expensify/App/issues/8357#issuecomment-1085871230 ?

**Comment by mollfpr** [comment] 2022-04-18 15:38
Is this the expected behavior?

**When there's no one in the room (except myself)**

https://user-images.githubusercontent.com/25520267/163832224-9d0be678-c6a5-470a-a926-2d5860ff9aa9.mov

**When there are members in the room**

https://user-images.githubusercontent.com/25520267/163832251-5a4f7554-b8de-4eb6-bae8-97965d0a6393.mov

---
If so, it could be done by changing the condition when showing the option (split bill, request money, send money) when there are members in the room and show nothing when there's only you in the room.

https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/pages/home/report/ReportActionCompose.js#L452-L489

```js
                                                    ...(!hasExcludedIOUEmails && Permissions.canUseIOU(this.props.betas) && hasMultipleParticipants ? [
                                                        {
                                                            icon: Expensicons.Receipt,
                                                            text: this.props.translate('iou.splitBill'),
                                                            onSelected: () => {
                                                                Navigation.navigate(
                                                                    ROUTES.getIouSplitRoute(
                                                                        this.props.reportID,
                                                                    ),
                                                                );
                                                            },
                                                        },
                                                        {
                                                            icon: Expensicons.MoneyCircle,
                                                            text: this.props.translate('iou.requestMoney'),
                                                            onSelected: () => {
                                                                Navigation.navigate(
                                                                    ROUTES.getIouRequestRoute(
                                                                        this.props.reportID,
                                                                    ),
                                                                );
                                                            },
                                                        },
                                                        {
                                                            icon: Expensicons.Send,
                                                            text: this.props.translate('iou.sendMoney'),
                                                            onSelected: () => {
                                                                Navigation.navigate(
                                                                    ROUTES.getIOUSendRoute(
                                                                        this.props.reportID,
                                                                    ),
                                                                );
                                                            },
                                                        },
                                                    ] : []),
```

cc @iwiznia @danieldoglas  @Santhosh-Sellavel

**Comment by mollfpr** [comment] 2022-04-18 15:48
Btw I cannot send/request money in the room even where there are members inside. Is this the expected behavior?

**Comment by mollfpr** [comment] 2022-04-18 16:58
## Proposal

We need to change the condition when showing send/request money option. I think we only need to show both options for the non-admin/announce room.

https://github.com/Expensify/App/blob/6c53be1ea7a022e8a5e788cc7e7efd62c4573474/src/pages/home/report/ReportActionCompose.js#L452-L489

change with
```js
        const isAdminOrAnnounceRoom = ReportUtils.isAdminRoom(this.props.report) || ReportUtils.isAnnounceRoom(this.props.report);
```
```js
                                                    ...(!hasExcludedIOUEmails
                                                        && Permissions.canUseIOU(this.props.betas) && hasMultipleParticipants ? [
                                                            {
                                                                icon: Expensicons.Receipt,
                                                                text: this.props.translate('iou.splitBill'),
                                                                onSelected: () => {
                                                                    Navigation.navigate(
                                                                        ROUTES.getIouSplitRoute(
                                                                            this.props.reportID,
                                                                        ),
                                                                    );
                                                                },
                                                            },
                                                        ] : []),
                                                    ...(!hasExcludedIOUEmails && Permissions.canUseIOU(this.props.betas) && !hasMultipleParticipants && !isAdminOrAnnounceRoom ? [
                                                        {
                                                            icon: Expensicons.MoneyCircle,
                                                            text: this.props.translate('iou.requestMoney'),
                                                            onSelected: () => {
                                                                Navigation.navigate(
                                                                    ROUTES.getIouRequestRoute(
                                                                        this.props.reportID,
                                                                    ),
                                                                );
                                                            },
                                                        },
                                                    ] : []),
                                                    ...(!hasExcludedIOUEmails && Permissions.canUseIOUSend(this.props.betas) && !hasMultipleParticipants && !isAdminOrAnnounceRoom ? [
                                                        {
                                                            icon: Expensicons.Send,
                                                            text: this.props.translate('iou.sendMoney'),
                                                            onSelected: () => {
                                                                Navigation.navigate(
                                                                    ROUTES.getIOUSendRoute(
                                                                        this.props.reportID,
                                                                    ),
                                                                );
                                                            },
                                                        },
                                                    ] : []),
```

### Result


https://user-images.githubusercontent.com/25520267/163843642-6fc636e0-8388-4095-846a-98ac09da6d4d.mov

**Comment by kadiealexander** [comment] 2022-04-21 05:17
Doubled the job price!

**Comment by allroundexperts** [comment] 2022-04-21 20:58
### Proposal

First of all, we need to make sure that the `hasMultipleParticipants` variable has an accurate value. The `reportParticipants` variable contains the logged in user for `admins` and `announce` channels but ignores them for single or group channels. 

The `hasMultipleParticipants` variable is thus changed from:
https://github.com/Expensify/App/blob/8fda329c92559737d8040da5ab5eb01fd7b18d26/src/pages/home/report/ReportActionCompose.js#L395
to
https://github.com/allroundexperts/Expensify/blob/199033cbb626550aa5690b580709a945712526cd/src/pages/home/report/ReportActionCompose.js#L395

The condition which checks for the menu items to display also seems to be using `hasMultipleParticipants` in a wrong way. It was also changed from:
https://github.com/Expensify/App/blob/8fda329c92559737d8040da5ab5eb01fd7b18d26/src/pages/home/report/ReportActionCompose.js#L452-L489
to
https://github.com/allroundexperts/Expensify/blob/199033cbb626550aa5690b580709a945712526cd/src/pages/home/report/ReportActionCompose.js#L452-L489

### Result
https://user-images.githubusercontent.com/30054992/164551053-b4823f60-0832-497c-aade-3055499f32fb.mp4

**Comment by sobitneupane** [comment] 2022-04-22 09:24
**Proposal:**
Since reportParticipants includes logged in user in chat room but not in one-to-one or group chats. So, we must exclude logged in user from the reportParticipants while taking length. 
There are three different conditions.
1.  length < 1 -> show Nothing
2. length === 1 -> show Send Money and Request Money Options
3. length > 1 -> show Split bill

To implement this, we should make use of two different variables: `showSplitBill` or `hasMultipleParticipants` and `showSendRequestMoney`.
https://github.com/Expensify/App/blob/32d8f0261b825cb6e47e441b9cf08400340a164e/src/pages/home/report/ReportActionCompose.js#L395

```
        const hasMultipleParticipants = _.filter(reportParticipants, email => this.props.myPersonalDetails.login !== email).length > 1;
        const showSendRequestMoney = _.filter(reportParticipants, email => this.props.myPersonalDetails.login !== email).length === 1;
```
We can use these two variables `hasMultipleParticipants` and `showSendRequestMoney` to determine which items to be included in menuItems.

https://github.com/Expensify/App/blob/32d8f0261b825cb6e47e441b9cf08400340a164e/src/pages/home/report/ReportActionCompose.js#L451-L489
```diff
menuItems={[
    ...(!hasExcludedIOUEmails
+        && Permissions.canUseIOU(this.props.betas) && 
+       hasMultipleParticipants ? [
+            {
                icon: Expensicons.Receipt,
                text: this.props.translate('iou.splitBill'),
                onSelected: () => {
                    Navigation.navigate(
                        ROUTES.getIouSplitRoute(
                            this.props.reportID,
                        ),
                    );
                },
+            },
+        ]: []),
+    ...(!hasExcludedIOUEmails && Permissions.canUseIOUSend(this.props.betas) && showSendRequestMoney ? [
+        {
            icon: Expensicons.MoneyCircle,
            text: this.props.translate('iou.requestMoney'),
            onSelected: () => {
                Navigation.navigate(
                    ROUTES.getIouRequestRoute(
                        this.props.reportID,
                    ),
                );
            },
        },
        {
            icon: Expensicons.Send,
            text: this.props.translate('iou.sendMoney'),
            onSelected: () => {
                Navigation.navigate(
                    ROUTES.getIOUSendRoute(
                        this.props.reportID,
                    ),
                );
            },
        },
    ] : []),
```

**Comment by Santhosh-Sellavel** [comment] 2022-04-22 21:24
Will get to proposals by Monday!

@sobitneupane 
> I think most of us are not clear about the expected output. 

Then you should straight away ask questions to clarify things. So we could get this solved sooner.

**Comment by Santhosh-Sellavel** [comment] 2022-04-23 16:35
@sobitneupane 

I think this is the expected output,
>  Option 1: 
Show Send Money and Request Money Options if there is a participant other than the logged in User and Show Split Bill Option if there are more than one participants other than the logged in User. In this case, even rooms with a participant other than the logged-in user will have Send Money and Request Money options.

@iwiznia Can you confirm this?

If this is the expected, I see a few proposals but all look similar & partial solutions.

**Comment by iwiznia** [comment] 2022-04-25 11:48
> @iwiznia Can you confirm this?

Yes that sounds good, but not sure if we should show the options in places like the admins room

**Comment by sobitneupane** [comment] 2022-04-25 12:05
At present, Send Money and Request Money option is only present for one-to-one chats. Split Bill option is shown even for chat rooms having one participant other than the logged in user. Do we want to show Send Money and Request Money option in the chat room having one participant other than the logged in user? I think we are intentionally showing only split bill option in all the chat rooms.

**Comment by iwiznia** [comment] 2022-04-25 12:07
> Do we want to show Send Money and Request Money option in the chat room having one participant other than the logged in user? Do we want to show Send Money and Request Money option in the chat room having one participant other than the logged in user?

Honestly, I don't know, but since this is only about not showing send money when there are no other participants, let's leave all the other behavior untouched

**Comment by sobitneupane** [comment] 2022-04-25 12:14
In that case this should do the job.
> **Option 2 Proposal:** 
> https://github.com/Expensify/App/blob/32d8f0261b825cb6e47e441b9cf08400340a164e/src/pages/home/report/ReportActionCompose.js#L451-L489
> 
> ```js
> menuItems={[
>   ...(!hasExcludedIOUEmails
>       && Permissions.canUseIOU(this.props.betas)
>       && hasMultipleParticipants
>       ? [{
>           icon: Expensicons.Receipt,
>           text: this.props.translate('iou.splitBill'),
>           onSelected: () => {
>               Navigation.navigate(
>                   ROUTES.getIouSplitRoute(
>                       this.props.reportID,
>                   ),
>               );
>           },
>       }] : []),
>   ...(!hasExcludedIOUEmails
>       && Permissions.canUseIOU(this.props.betas)
>       && !hasMultipleParticipants
>       && !ReportUtils.isChatRoom(this.props.report)
>       ? [{
>           icon: Expensicons.MoneyCircle,
>           text: this.props.translate('iou.requestMoney'),
>           onSelected: () => {
>               Navigation.navigate(
>                   ROUTES.getIouRequestRoute(
>                       this.props.reportID,
>                   ),
>               );
>           },
>       }] : []),
>   ...(!hasExcludedIOUEmails && Permissions.canUseIOUSend(this.props.betas) && !hasMultipleParticipants
>       && !ReportUtils.isChatRoom(this.props.report) ? [
>           {
>               icon: Expensicons.Send,
>               text: this.props.translate('iou.sendMoney'),
>               onSelected: () => {
>                   Navigation.navigate(
>                       ROUTES.getIOUSendRoute(
>                           this.props.reportID,
>                       ),
>                   );
>               },
>           }] : []),
> ```

**Comment by allroundexperts** [comment] 2022-04-25 12:14
@iwiznia What about my proposal then?

**Comment by sobitneupane** [comment] 2022-04-25 12:24
> @iwiznia What about my proposal then?

If I am allowed to comment on your proposal, it looks like you are proposing to show all the options if there are multiple participants which I guess is not the intended behavior.

**Comment by Santhosh-Sellavel** [comment] 2022-04-25 16:20
@sobitneupane 
 > I think we are intentionally showing only the split bill options in all the rooms. I am not sure, though.
 
 No, It was accidentally showing because the report participant's value is wrong, which introduces this issue as well, fix should be the same for both.
 
 cc: @iwiznia

**Comment by Santhosh-Sellavel** [comment] 2022-04-25 16:24
@iwiznia 

Still looking for a better proposal.
As I said [here](https://github.com/Expensify/App/issues/8357#issuecomment-1107531193) `proposals are similar & partial``

**Comment by allroundexperts** [comment] 2022-04-25 16:30
@Santhosh-Sellavel The instructions are not clear. Can you specify what's missing in the above proposals?

**Comment by Santhosh-Sellavel** [comment] 2022-04-25 16:49
@allroundexperts 

This is the expected outcome,
> Show Send Money and Request Money Options if there is a participant other than the logged in User and Show Split Bill Option if there are more than one participants other than the logged in User. In this case, even rooms with a participant other than the logged-in user will have Send Money and Request Money options.

@sobitneupane Already comment what's wrong with your proposal [here](https://github.com/Expensify/App/issues/8357#issuecomment-1108504082)

**Comment by allroundexperts** [comment] 2022-04-25 18:09
@Santhosh-Sellavel Here's the updated proposal.

### Proposal

First of all, we need to make sure that the `hasMultipleParticipants` variable has an accurate value. The `reportParticipants` variable contains the logged in user for `admins` and `announce` channels but ignores them for single or group channels. 

The `hasMultipleParticipants` variable is thus removed and replaced with a new variable called `reportParticipantsOtherThanLoggedInUser `:
https://github.com/allroundexperts/Expensify/blob/fix-8357/src/pages/home/report/ReportActionCompose.js#L395

The condition which checks for the menu items to display is also changed such that if `reportParticipantsOtherThanLoggedInUser.length === 1`, we show the `send and request money` options. If `reportParticipantsOtherThanLoggedInUser.length > 1`, we show the `splitBill` option.
https://github.com/allroundexperts/Expensify/blob/fix-8357/src/pages/home/report/ReportActionCompose.js#L452-L492

### Result

https://user-images.githubusercontent.com/30054992/165148324-4b9cf5e3-5946-4bf2-a58a-8c874c657896.mov

**Comment by Santhosh-Sellavel** [comment] 2022-04-25 18:22
@allroundexperts 
Please try to include the exact code changes you are proposing instead of linking. Example like this https://github.com/Expensify/App/issues/8357#issuecomment-1108493490

**Comment by allroundexperts** [comment] 2022-04-25 18:32
@Santhosh-Sellavel Updated.

**Comment by Santhosh-Sellavel** [comment] 2022-04-26 16:01
@iwiznia 
Proposals are similar, so let's go with @sobitneupane here.
@sobitneupane **Option 1** proposal [here](https://github.com/Expensify/App/issues/8357#issuecomment-1106236099) looks good to me.
One suggestion, let's move the IOU options preparation logic to a new method. Since the code is not DRY & too clumsy in Render Block. 

🎀👀🎀 C+ reviewed.
Thanks!

**Comment by iwiznia** [comment] 2022-04-28 12:17
Proposal looks good to me and I agree about the new method. @kadiealexander can you hire @sobitneupane please?

**Comment by Santhosh-Sellavel** [comment] 2022-04-29 15:09
@sobitneupane Any update?

**Comment by Puneet-here** [comment] 2022-04-29 20:36
Hi the proposals above aren't complete if we only make the changes for actions we still be seeing our own contact whenever we try to send/reques/split bill as you can see in the screenshot.
<img width="1051" alt="Screenshot 2022-04-30 at 1 55 17 AM" src="https://user-images.githubusercontent.com/101883770/166064432-627e5606-c884-4155-a88c-84ec21e60df6.png">

As all the proposals are incomplete here's my proposal.

### Proposal

We need to filter out our own login from the participant using `_.filter ` https://github.com/Expensify/App/blob/66f0643df8e19d442e23b2c73c694c22b5390c1e/src/pages/iou/IOUModal.js#L110

We will use two variables and based on them we will be showing different options, if `showSplitBillOption` is true will be showing the split bills and when `showSendRequestMoney` is true we will show the options of send and request money 
( it is already proposed in the proposals above )

        const showSplitBillOption = _.filter(reportParticipants, email => this.props.myPersonalDetails.login !== email).length > 1;
        const showSendRequestMoney = _.filter(reportParticipants, email => this.props.myPersonalDetails.login !== email).length === 1;

We can create a new method `showActions` which will return an array of actions based on the conditions for different actions and we can just call it here
https://github.com/Expensify/App/blob/66f0643df8e19d442e23b2c73c694c22b5390c1e/src/pages/home/report/ReportActionCompose.js#L451

**Comment by Puneet-here** [comment] 2022-04-29 20:37
Hi the proposals above aren't complete if we only make the changes for actions we still be seeing our own contact whenever we try to send/reques/split bill as you can see in the screenshot.
<img width="1051" alt="Screenshot 2022-04-30 at 1 55 17 AM" src="https://user-images.githubusercontent.com/101883770/166064432-627e5606-c884-4155-a88c-84ec21e60df6.png">

As all the proposals are incomplete here's my proposal.

### Proposal

We need to filter out our own login from the participant using `_.filter ` https://github.com/Expensify/App/blob/66f0643df8e19d442e23b2c73c694c22b5390c1e/src/pages/iou/IOUModal.js#L110

We will use two variables and based on them we will be showing different options, if `showSplitBillOption` is true will be showing the split bills and when `showSendRequestMoney` is true we will show the options of send and request money 
( it is already proposed in the proposals above )

        const showSplitBillOption = _.filter(reportParticipants, email => this.props.myPersonalDetails.login !== email).length > 1;
        const showSendRequestMoney = _.filter(reportParticipants, email => this.props.myPersonalDetails.login !== email).length === 1;

We can create a new method `showActions` which will return an array of actions based on the conditions for different actions and we can just call it here
https://github.com/Expensify/App/blob/66f0643df8e19d442e23b2c73c694c22b5390c1e/src/pages/home/report/ReportActionCompose.js#L451

cc: @iwiznia @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2022-04-30 12:57
@Puneet-here Your proposal has nothing new here, what are you trying to say. 

Even your proposal is incomplete here.

**Comment by kadiealexander** [comment] 2022-05-02 06:34
@sobitneupane please let me know once you've applied on Upwork!

**Comment by sobitneupane** [comment] 2022-05-05 13:58
> @sobitneupane please let me know once you've applied on Upwork!

Applied.

**Comment by kadiealexander** [comment] 2022-05-09 05:45
Sent offers in Upwork to:
Hired contributor: @sobitneupane 
C+: @Santhosh-Sellavel 
Reporting bonus: @thesahindia

**Comment by kadiealexander** [comment] 2022-05-17 22:35
@sobitneupane could you please share an update here? Thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-05-18 01:46
@kadiealexander PR is merged & it's on production now!

**Comment by kadiealexander** [comment] 2022-05-18 02:41
Thanks @sobitneupane!!!

**Comment by kadiealexander** [comment] 2022-05-20 05:21
Everyone is paid! Thanks for your work, team.

**Closed by kadiealexander** 2022-05-20 05:21 UTC
Labels: Exported, External, Engineering, Weekly, Improvement
