### ISSUE TITLE
[HybridApp] Receipt thumbnails are blank for a new unvalidated account sign-up

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#50712] opened 2024-10-14 10:12 UTC
### Problem

Receipt scanning appears to be totally broken for a new account sign-up

[UploadReciept logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228d0fc590ea5b6347-LHR%22)+AND+timestamp:[2024-10-11T14:09:46.722Z+TO+2024-10-11T16:09:46.722Z]&index=logs_expensify-030671)

**Device:**
```
Version: v9.0.48-0
Device: iPhone 15 Pro, iOS 18.0.1
```

**Reproduction steps:**
- _Locate domain opted into `hybridAppRedirect ` beta_ 
- Download the latest TestFlight
- Sign-up as a new user
- Submit expense > Scan
- Take a picture of your feet
- Observe the thumbnail turn blank on upload
- Submit expense > Scan
- Add a legit receipt this time
- Observe the thumbnail turn blank on upload
- Observe “receipt scanning…” indefinitely

![IMG_0962](https://github.com/user-attachments/assets/9c87229f-d3e6-4220-a795-2729d8bc5e09)

https://github.com/user-attachments/assets/c86f5040-97f5-4cd5-808c-6fc8b1b3ec75

### Solution

investigate. 

From @AndrewGable : 
> I would assume this is it: We share auth tokens between Old and New Apps and the encrypted auth token is used to view thumbnails due to “secured receipts” project. For some reason the encrypted auth token is the one that sometimes gets out of sync.

From @mateuuszzzzz: 
> The good news is that migrating to NewDot login page should solve this issue for us. But it will take some time to finish it. I bet we will need to handle this bug separately. I started research some time ago and here is related draft [PR](https://github.com/Expensify/Mobile-Expensify/pull/13144)

From @trjExpensify:
> P.s - that flow is super rough though. Why don’t we show the magic code input on the home page for the unvalidated account?
On this btw, I think we need to do something about that in the name of #convert.

- Sign-up
- Get signed in for an unvalidated session
- Sign-out
- Re-enter the email address
- See a message saying to click the validation link in an email that never came
- Click “Resend link”
- Get the magic code email
- Click the link in the email
- Get taken to mWeb where you’re told to use the same device you requested from
- After step 4, why don’t we 1) send a magic code email and 2) show the magic code input screen? I’m basically stuck at this point.

**Comment by Julesssss** [comment] 2024-10-14 10:13
Just noting that this issue wil not block HybridApp [release](https://github.com/Expensify/Expensify/issues/433068) `9.0.47.4` as this is an existing authentication issue

**Comment by mateuuszzzzz** [comment] 2024-10-14 10:15
FYI: Here's draft PR where I was investigating this issue https://github.com/Expensify/Mobile-Expensify/pull/13144

**Comment by mateuuszzzzz** [comment] 2024-10-16 14:06
I merged the latest main branches to find potential problems, and it turns out that the app sometimes crashes during Sign Up. I'm going to investigate this.

**Comment by mateuuszzzzz** [comment] 2024-10-17 10:06
Hi, I have an update. It seems like we don’t return the `encryptedAuthToken` to the old app, which is causing the current PR to break. We’re having a discussion about the next steps for the PR

**Comment by mateuuszzzzz** [comment] 2024-10-18 14:54
Hi, I have a new update after another round of investigation.

I tried to implement another approach which was described [here](https://swmansion.slack.com/archives/C07HPDRELLD/p1729253146217929?thread_ts=1728999565.505529&cid=C07HPDRELLD). Unfortunately, there are some issues with authentication on NewDot side with credentials generated on OldDot side. 

I get the following error when I try to re-authenticate:
```
{"response": {"jsonCode": 404, "message": "404 No passwordless infinite login found.", "onyxData": [], "requestID": "8d4903949ac6b197-WAW"}
```

My guess is that we cannot make authentication request with HybridApp's `partnerName` (I compared how it behaves with NewDot `partnerName` and I did not encounter this issue). 

I think we need someone from Expensify to look into this as it seems like backend issue.

Alternatively, we could switch to using NewDot's `partnerName` in HybridApp, but I'm not sure what impact that might have on the existing backend logic.

**Comment by AndrewGable** [comment] 2024-10-18 15:19
@jasperhuangg - I think you were looking into this specific case on the backend correct?

**Comment by jasperhuangg** [comment] 2024-10-18 16:55
@AndrewGable, I don’t think the issue is related to partnerName. Both the PARTNER_ANDROID and PARTNER_IPHONE are being considered in [this condition](https://github.com/Expensify/Auth/blob/455ab3e611d9fa133a8cdc934e47530479644b23/auth/lib/Login.cpp#L650), which must pass before reaching [the logic that throws the exception](https://github.com/Expensify/Auth/blob/main/auth/command/Authenticate.cpp#L153-L155).

The problem @mateuuszzzzz is encountering seems to be because we aren’t creating a temporary login for the user when they sign into HybridApp, unlike what we do for NewDot, which makes [this](https://github.com/Expensify/Auth/blob/455ab3e611d9fa133a8cdc934e47530479644b23/auth/command/Authenticate.cpp#L149) check fail. When a temporary login is created, an NVP is also set, which is checked in situations like this.

This issue is similar to [this one](https://github.com/Expensify/App/issues/51042) because both involve differences in the HybridApp sign-in flow compared to NewDot. However, the root cause in each case is different, as different parts of the sign-in flow are inconsistent.

**Comment by Julesssss** [comment] 2024-10-21 12:52
I hope to have more time to help triage the backend issues soon.

**Comment by Julesssss** [comment] 2024-10-22 10:14
> I tried to implement another approach which was described [here](https://swmansion.slack.com/archives/C07HPDRELLD/p1729253146217929?thread_ts=1728999565.505529&cid=C07HPDRELLD).

Hey @mateuuszzzzz, this looks like an internal Slack, was there any useful info there you could share?

**Comment by trjExpensify** [comment] 2024-10-22 11:01
^^ It's actually just how Slack copies links when you share workspaces. Swap the `swmansion` portion for `expensify` and it'll work:

`https://swmansion.slack.com/archives/C07HPDRELLD/p1729253146217929?thread_ts=1728999565.505529&cid=C07HPDRELLD`

`https://expensify.slack.com/archives/C07HPDRELLD/p1729253146217929?thread_ts=1728999565.505529&cid=C07HPDRELLD`

**Comment by trjExpensify** [comment] 2024-10-22 14:40
I added my private test domain to the beta a while ago. Feel free to sign-up with any new account on `tom+<insertsomethinghere>@trj.chat`.

**Comment by Julesssss** [comment] 2024-10-22 15:48
Thanks. [Some logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22authtoken%22%20AND%20email%3A%22tom%2Bjules2%40trj.chat%22%20AND%20timestamp%3A%5B2024-10-22T00%3A00%20TO%202024-10-23T23%3A59%5D). 

As Jasper mentioned, `Login::isInfiniteLoginType` is returning true in this case. The Authenticate command fails because no temporary passwordless partnerID exists in the `temp...pass` NVP under that accountID. I wonder if accountID is being set correctly [here](https://github.com/Expensify/Auth/blob/a62642515113ec7e44e9ab7f3cabea247d5ba651/auth/command/Authenticate.cpp#L62)?

**Comment by mateuuszzzzz** [comment] 2024-10-23 11:24
I also noticed this week that If I invalidate auth token with button from troubleshooting section on NewDot then re-authentication works fine. On the other hand, calling `reauthenticate` function right after transition to NewDot (from code) results in failing request. I hope this helps

**Comment by Julesssss** [comment] 2024-10-24 14:17
I can see what looks like two different cases in the logs. The receiptUpload auth token sticks out, but we do also use this as a generic token.

**accountA)** `partnerID: 16, partnerUserID: 'google-pixel...', isValidated: false, isPasswordless: false`
**accountB)** `partnerID: 1, partnerUserID: '', type:: 'receiptUpload', isValidated: false, isPasswordless: true`

<img width="1076" alt="Screenshot 2024-10-22 at 16 35 10" src="https://github.com/user-attachments/assets/0c4c98fc-e8b9-44ad-8f51-afaf8cb56483">

My next step is to look further into the missing temporaryLogin NVP, but here are some initial notes:

- Mateusz shared a reproduction method: modify [setSessionDataAndOpenApp](https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/libs/actions/Session/index.ts#L498) so that we call `Authentication.reauthenticate()` before `App.openApp()`
    - Why does invalidation fail immediately after transition, but NOT when the token is manually invalidated???
    - I plan to use a debuggable HybridApp build to catch the failing request and check the params
- Using the [encryptedAuthToken](https://github.com/Expensify/Mobile-Expensify/pull/13071/files#diff-007ef92e341b570b3825b1bc626e0337e4d336c53b58efca21505a2d2a64ce2eR4756) fixed the post transition receipt loading issue for _validated accounts_
- PR to [share](https://github.com/Expensify/Mobile-Expensify/pull/12993) authToken with ND
- The transition is still occurring for initial sign in, so what is the difference? Is it that no encryptedToken is provided to an invalidated account?
- Why are we using these two different auth params?

**Comment by trjExpensify** [comment] 2024-10-24 19:58
Per [here](https://expensify.slack.com/archives/C07HPDRELLD/p1729590307243149?thread_ts=1729565763.405919&cid=C07HPDRELLD), I'm putting this back on `Daily` as a showstopper to putting new sign-ups on the NewDot experience on mobile sign-up.

**Comment by Julesssss** [comment] 2024-10-25 15:35
I have spent some time debugging HybridApp networking and Yapl flows. For now the plan is to ensure secureAuthToken is always set in HybridApp (with thanks to a hint from Marcin).

When `Authenticate` is called from HybridApp YAPL logic, we persist the returned `encryptedAuthToken` and then pass it during redirection. However, we don't appear to be doing this within the create account flow, meaning that the encrypted token isn't passed to NewDot during redirection.

_Note for Monday: Debug build `Expensify-oct25-logs-3.apk` and test the new logs against expected response._

**Comment by Julesssss** [comment] 2024-10-28 16:25
Chores and other tasks prevented me from having time for this today. I should have less blocking me from this task tomorrow.

**Comment by mateuuszzzzz** [comment] 2024-10-29 09:24
I'll be also looking into that issue today one more time 👍

**Comment by Julesssss** [comment] 2024-10-31 15:45
Back from OOO. Today I tested my backend changes that just hit staging against my WIP mobile changes and I'm pretty sure the issue is resolved 🎉 

https://github.com/user-attachments/assets/0f7883af-0a40-4a1c-9d13-1ab79b3f123a

_Thumbnails not blank after upload:_ 

![Screenshot 2024-10-31 at 15 42 50](https://github.com/user-attachments/assets/81225331-69d7-4ab8-8221-e486ce492366) ![Screenshot 2024-10-31 at 15 43 19](https://github.com/user-attachments/assets/156c98d2-2b07-48b3-b44b-b978fbcb624b)

**Comment by Julesssss** [comment] 2024-10-31 15:55
HybridApp PR submitted [here](https://github.com/Expensify/Mobile-Expensify/pull/13265).

**Closed** 2024-10-31 19:45 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Internal

**Comment by trjExpensify** [comment] 2024-11-01 09:32
Nice work here!! ❤️
