### ISSUE TITLE
[$500] [HOLD for payment 2023-12-29] [HOLD for payment 2023-12-28] Android - All message displayed instead of last 3 when switching to another chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33367] opened 2023-12-20 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31762

## Action Performed:
1. Log in
2. Accept prompt for notification permission
3. Open concierge chat
4. Send 3 messages to yourself
5. Verify notifications display for the messages
6. Switch to the chat
7. Verify those notifications are cleared
8. Switch away from the app
9. On native, go to the home screen
10. Send another 3 messages to yourself
11. Switch back to the app
12. Verify those notifications are cleared
13. Switch to the concierge chat
14. Send another 3 messages to yourself
15. Switch to other chats (not the one with the messages)
16. Verify those notifications are NOT cleared

## Expected Result:
Should be 3 messages displayed

## Actual Result:
All message displayed instead of last 3 when switching to another chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7c1dd3ee-dc63-40ab-9d59-95882760fbc2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d520e3b819d9956</li>
        <li>Upwork Job ID: 1745092726620999680</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by johnmlee101** [comment] 2023-12-20 17:33
So to clarify, switching to another chat should clear all of the previous notifications, is what you're saying?

**Comment by johnmlee101** [comment] 2023-12-20 17:33
cc @arosiclair not sure if this is relevant with the notifications, is that expected?

**Comment by arosiclair** [comment] 2023-12-20 17:48
I think this part is unexpected:

<img width="300" src="https://github.com/Expensify/App/assets/6833644/95f1f4d1-4ffd-4b81-bd7d-c33d2ae32925" />

The first 6 messages in that thread shouldn't be shown since they were cleared before. This is probably because they weren't cleared from the cache we have [here](https://github.com/Expensify/App/blob/main/android/app/src/main/java/com/expensify/chat/customairshipextender/NotificationCache.java).

**Comment by arosiclair** [comment] 2023-12-20 17:49
I can try reproducing this in dev and see if there's a quick fix

**Comment by johnmlee101** [comment] 2023-12-20 18:04
Good catch!

**Comment by johnmlee101** [comment] 2023-12-20 20:32
Any luck here?

**Comment by arosiclair** [comment] 2023-12-20 21:06
Sorry just getting back to this now

**Comment by arosiclair** [comment] 2023-12-20 21:57
I can reproduce this in dev. 

Honestly, I'm not sure there's an easy fix for this. Normally when notifications are dismissed our native callback runs and clears the notification from the cache [here](https://github.com/Expensify/App/blob/main/android/app/src/main/java/com/expensify/chat/customairshipextender/CustomNotificationListener.java#L51). However, when we use JS APIs to clear notifications when you open a report ([here](https://github.com/Expensify/App/blob/main/src/libs/Notification/PushNotification/index.native.ts#L220)), it looks like those native callbacks don't get called so the cache is not updated.

We could try adding a Native Module to clear the cache manually, but I don't think there's an easy way to get a reference to the `NotificationCache` from that context.

This functionality is working well on all other platforms, so I'm tempted to just disable the feature on Android and figuring out a fix later. What do you think @johnmlee101?

**Comment by johnmlee101** [comment] 2023-12-20 22:04
Yeah that works for me 👍 let's take the time to do it right

**Comment by arosiclair** [comment] 2023-12-20 23:20
Posted a PR, but gotta sign off and go OOO for the rest of the week

**Comment by arosiclair** [comment] 2024-01-02 16:22
@kevinksullivan can you just pay @fedirjh for his C+ review?

**Comment by kevinksullivan** [comment] 2024-01-10 14:40
Sorry for the delay. @fedirjh offer was sent, lmk when you accept!

**Comment by kevinksullivan** [comment] 2024-01-12 19:56
All set

**Closed by kevinksullivan** 2024-01-12 19:56 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
