### ISSUE TITLE
[HOLD for payment 2023-09-18] [$1000] mWeb - Split bill - 8 figure amounts cut off by avatar in split bill

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24321] opened 2023-08-09 15:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in to staging new dot
2. Click on + icon and select split bill
3. Enter an 8 figure amount and click next
4. Select more than 4 accounts to split with and click on split

## Expected Result:
Amount should be fully visible

## Actual Result:
Last digits of amount are cut off

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v 1.3.51-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d761e196-4784-49a7-9a5c-00a1e6b94288

https://github.com/Expensify/App/assets/115492554/4b899e07-a2fd-4a45-ad4b-0c22111b700c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690975999762419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01599e5ea723ba399a</li>
        <li>Upwork Job ID: 1691845401779220480</li>
        <li>Last Price Increase: 2023-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>DanutGavrus | Contributor | 26377376</li>
<li>sofoniasN | Reporter | 26377378</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-08-09 15:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
8 figure amounts cut off by avatar in split bill

### What is the root cause of that problem?
The `Text` which shows the amount has the same `fontSize` on both *large* & *small* screen widths, and also does not use the `numberOfLines` prop.

### What changes do you think we should make in order to solve the problem?
I would suggest to verify when we are on *small width devices* in order to use a smaller `fontSize` & to also set the  `numberOfLines` prop for the Text to 1 or 2. The smaller `fontSize` will ensure that the amount is visible on any small screen device, and the `numberOfLines` prop offers extra safety.

### What alternative solutions did you explore?
We could rely on only using the `numberOfLines` prop if we want to keep the amount to the same size.

**Comment by DanutGavrus** [comment] 2023-08-09 16:51
@s-alves10
> Isn't it impossible to show long amount fully in a small width device?  

I think it's possible to fully show long amounts if we use a smaller font size for small width devices. Currently, we use the same large one.

It's also possible to fully show long amounts if we use 2 lines, but I don't think that's desired.

**Comment by johncschuster** [comment] 2023-08-16 16:12
Ok! I can confirm that this behavior is not expected.

When entering 8+ numerals (ex: `12,345,678`, `123,456,789`, etc), we should expect the text to dynamically decrease in size to allow the characters to fit.

**Comment by johncschuster** [comment] 2023-08-16 16:13
@eVoloshchak, take a look at this [proposed solution](https://github.com/Expensify/App/issues/24321#issuecomment-1671635913) when you get a moment. It sounds in line with what we've discussed internally.

**Comment by Julesssss** [comment] 2023-08-16 16:23
Side note, the select participant's page seems very laggy in that video.

**Comment by Julesssss** [comment] 2023-08-16 16:24
The proposal looks good to me, but I'd love to see us go with this option: 

> We could also set the fontSize dynamically based on the number of digits in the amount(after n digits, set a smaller fontSize), or use a combination of device size & number of digits.

**Comment by DanutGavrus** [comment] 2023-08-16 16:54
@Julesssss Should I provide an implementation now, or that's something which we'll discuss in the PR? (If my Proposal gets chosen, of course). Thanks!

**Comment by Julesssss** [comment] 2023-08-16 17:21
Personally, I think the issue is simple enough that we don't need more details. But this varies by reviewer/issue and more details can only help. Maybe you could just add some details on which file we'll change or which condition we'd modify.

**Comment by Julesssss** [comment] 2023-08-20 20:11
_FYI I am OOO this week. Feel free to reassign in the meantime, or I will be back on Monday 28th_

**Comment by eVoloshchak** [comment] 2023-08-22 18:23
The [proposal](https://github.com/Expensify/App/issues/24321#issuecomment-1671635913) looks good to me too

> We could also set the fontSize dynamically based on the number of digits in the amount

@DanutGavrus, can't we use [adjustsFontSizeToFit](https://reactnative.dev/docs/text#adjustsfontsizetofit) prop for this?

**Comment by DanutGavrus** [comment] 2023-08-23 09:44
@eVoloshchak I see the same result with & without __adjustsFontSizeToFit__:  

<img src="https://github.com/Expensify/App/assets/56603839/028746ef-2c83-4de4-b119-a335faf0c463" width="500px">

I've also tried removing `allowFontScaling={false}` from `RNText`, but it made no difference either.

**Comment by johncschuster** [comment] 2023-08-25 21:33
@eVoloshchak it sounds like we're happy with @DanutGavrus's [proposal](https://github.com/Expensify/App/issues/24321#issuecomment-1671635913). Do we need any adjustments, or are we good to assign this out?

**Comment by eVoloshchak** [comment] 2023-08-28 17:47
@johncschuster, yeah, let's proceed with @DanutGavrus's proposal

🎀👀🎀 C+ reviewed!

**Comment by Julesssss** [comment] 2023-08-30 12:43
Hi @DanutGavrus, have you made progress with this PR?

**Comment by DanutGavrus** [comment] 2023-08-30 13:02
Hi, @Julesssss! I was just working on the Screenshots/Videos.

@eVoloshchak
PR ready for review: https://github.com/Expensify/App/pull/26280

**Comment by DanutGavrus** [comment] 2023-08-30 13:32
No problem! I wanted to finish the PR sooner anyway, but at least we synchronized 😁.

**Comment by DanutGavrus** [comment] 2023-09-11 08:45
Hi, @Julesssss! I was wondering how are we going to compute the days elapsed for this PR(as it was part of the merge block period). Thanks!

**Comment by Julesssss** [comment] 2023-09-12 03:03
>  I was wondering how are we going to compute the days elapsed for this PR(as it was part of the merge block period). Thanks!

I think our reviews/discussions had already extended for 4 days, so I don't think it would have applied for the bonus regardless. cc @pecanoro 

Assigned: Aug 28th
Review still in progress: September 1st

**Comment by DanutGavrus** [comment] 2023-09-12 09:10
> I think our reviews/discussions had already extended for 4 days, so I don't think it would have applied for the bonus regardless

Yes, they did, and no penalty applies either, right?

**Comment by Julesssss** [comment] 2023-09-12 10:07
Yeah, no penalty either 👍

**Comment by eVoloshchak** [comment] 2023-09-18 15:24
- The PR that introduced the bug has been identified. Link to the PR: Not applicable, this is how it was implemented initially
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: it's a visual bug, there isn't much we could do besides automated UI testing
- Determine if we should create a regression test for this bug. 
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No_
This isn't an impactful bug, more of a layout issue. It doesn't prevent users from using the app, in addition, it was reproducible only for amounts larger than "1,000,000.00", which is rare. I don't think a regression test is needed here

**Comment by johncschuster** [comment] 2023-09-19 20:42
# Summary for payment:

This issue was [assigned](https://github.com/Expensify/App/issues/24321#issuecomment-1696405979) prior to the [price change announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649) (Aug 30) so the payments should be as follows:

Bug Reporter: @SofoniasN Bug Reporter - $250 - paid
Contributor: @DanutGavrus - $1000 - paid
Contributor+: @eVoloshchak - $1000 - will request via NewDot

cc @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2023-09-21 10:03
$1,000 payment for @eVoloshchak approved based on BZ summary.

**Comment by pecanoro** [comment] 2023-09-22 15:28
@johncschuster Anything else missing here or can we close?

**Comment by johncschuster** [comment] 2023-09-27 00:13
Nope! We can close this up!

**Closed by johncschuster** 2023-09-27 00:13 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
