### ISSUE TITLE
[$250] [Search v2.2] Chat is scrolled to the bottom when refreshing the page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48808] opened 2024-09-09 18:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.31-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+shsb22ertt@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to Newdot
2. Go to Search option from bottom tab
3. Click on "Chat" type from LHP
4. Click on any message which is not at the bottom of a chat report
5. When the report view is opened in RHP refresh the browser
6. Now notice how the chat report is scrolled to the bottom

## Expected Result:
The chat report in RHP is not scrolled down to the bottom and stays in the same report action opened before refreshing the page

## Actual Result:
The chat report in RHP is scrolled down to the bottom and user has to scroll up to find the chat report opened before refreshing the page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2ec8a3e6-58eb-4939-915b-a47a0f04ef64

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833217065296959946</li>
        <li>Upwork Job ID: 1833217065296959946</li>
        <li>Last Price Increase: 2024-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 103886648</li>
<li>huult | Contributor | 104028956</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by luacmartins** [comment] 2024-09-09 18:52
I'll take this since it's part of Search

**Comment by luacmartins** [comment] 2024-09-09 18:53
We should navigate the user to the reportActionID as well, not only the report

**Comment by luacmartins** [comment] 2024-09-09 18:53
@shubham1206agra

**Comment by luacmartins** [comment] 2024-09-09 23:46
I'm gonna demote this to NAB since it's a minor issue.

**Comment by luacmartins** [comment] 2024-09-12 19:18
Looking for proposals

**Comment by alexpensify** [comment] 2024-09-16 23:05
Open for proposals here

**Comment by huult** [comment] 2024-09-18 17:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat is scrolled to the bottom when refreshing the page

### What is the root cause of that problem?

The report action list is missing the `initialScrollIndex` in the [`InvertedFlatList`](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.tsx#L646).

### What changes do you think we should make in order to solve the problem?

We should add `initialScrollIndex` to the `InvertedFlatList`. Instead of starting at the top with the first item, it should start at the `initialScrollIndex`.

```diff
// .src/pages/home/report/ReportActionsList.tsx#L202
+   const indexOfLinkedMessage = useMemo((): number => sortedVisibleReportActions.findIndex((obj) => String(obj.reportActionID) === String(linkedReportActionID)), [sortedVisibleReportActions, linkedReportActionID]);

// .src/pages/home/report/ReportActionsList.tsx#L646
 <InvertedFlatList
       ...
+   initialScrollIndex={indexOfLinkedMessage !== -1 ? indexOfLinkedMessage : undefined}
/>
```

### What alternative solutions did you explore? (Optional)

We can use reportScrollManager.scrollToIndex to scroll to the message index

```diff
+    useEffect(() => {
+        if (indexOfLinkedMessage > -1) {
+           InteractionManager.runAfterInteractions(() => {
+                reportScrollManager.scrollToIndex(indexOfLinkedMessage, false);
+           });
+       }
+    }, [indexOfLinkedMessage, reportScrollManager]);
```

<summary>
<details>
POC

https://github.com/user-attachments/assets/bbc6ec35-706c-4faa-a8c4-31c4c54a39be

</details>
</summary>

**Comment by alexpensify** [comment] 2024-09-18 19:31
@ikevin127 when you get a chance, can you review if this proposal fixes this issue? Thanks!

**Comment by ikevin127** [comment] 2024-09-18 19:58
@alexpensify Yes, will review today.

**Comment by ikevin127** [comment] 2024-09-18 22:49
@huult's [proposal](https://github.com/Expensify/App/issues/48808#issuecomment-2359081530) looks good to me. The suggested root cause is debatable in the sense that **it is true if we're looking at implementing the main solution** but it's not exactly answer to the **"why?"** is the issue currently occuring, what's causing the RHP to scroll to jump to the bottom of the report chat after browser refresh.

Given that the proposed main solution fixes our issue, I will accept the RCA as a package with the main solution because I approve of the functionality the solution is implementing.

##

**Note for PR (if hired):** If you watch the solution testing videos attached below, you can notice that after the refresh, while the highlighted message **does** stay in place, looks like there's some scroll jumping happening. This is not a requirement as it's slightly out of scope for this issue but it would be a **nice to have** if we could fix that scroll jump, specifically targeted for this case (RHP) such that it wouldn't affect any other parts of the `ReportActionsList` component.

<details>
<summary>Videos</summary>

| Test 1 | Test 2 |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/8dafbaed-96d9-4c63-a313-a6a1645552f4"> | <video src="https://github.com/user-attachments/assets/b9bf3442-3988-4339-b73d-3faf3550b4ab"> |

</details>

🎀👀🎀 C+ reviewed

**Comment by Pujan92** [comment] 2024-09-19 14:18
> The report action list is missing the initialScrollIndex in the [InvertedFlatList](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.tsx#L646).

@huult, I was just wondering if this is the issue then how it is working for the central pane ReportActionsList

**Comment by huult** [comment] 2024-09-19 15:56
## [Proposal updated](https://github.com/Expensify/App/issues/48808#issuecomment-2359081530)
- Added a new solution

Hi @ikevin127 , While creating the pull request, I found a better solution. The pull request is already open. Can you check it? Thanks!

**Comment by ikevin127** [comment] 2024-09-19 18:06
Thanks @Pujan92!

> I was just wondering if this is the issue then how it is working for the central pane ReportActionsList

@huult This is a valid question when it comes to the RCA, which I wasn't able to figure out. 

I checked out your updated proposal and to be honest I'm reluctant when it comes to adding more useEffects / timeouts in a component which is already complex because these can degrade performance.

I think the best way to go here would be to dig into why the link / scroll to message works when the list is in central pane but not when it's in RHP.

##

If you're wiling to dig deeper and update your proposal to expand on the RCA please let us know - otherwise we can re-open this for proposals 👍

**Comment by huult** [comment] 2024-09-19 23:37
## [Proposal updated](https://github.com/Expensify/App/issues/48808#issuecomment-2359081530)
- Updated RCA
- Updated solutions to fix this issue
- Added new POC based on the new solution

@ikevin127, I've updated the proposal. Can you help check it again? Thank you!

**Comment by ikevin127** [comment] 2024-09-19 23:39
♻️ Reviewing updated proposal.

**Comment by ikevin127** [comment] 2024-09-20 00:21
@huult 🟢 The latest [proposal update](https://github.com/Expensify/App/issues/48808#issuecomment-2359081530), RCA and solution are the perfect fix here, I tested it and can confirm that it works as expected without any scroll jumps, works exactly like on the central pane on browser refresh 👍 

You can proceed to implementing the latest solution in the opened PR and tag me there once it's ready for review.

**Notes for PR**:
- the `onStartReached` function could become:
```ts
const onStartReached = useCallback(() => {
    InteractionManager.runAfterInteractions(() => requestAnimationFrame(() => loadNewerChats(false)));
}, [loadNewerChats]);
```
which is preferred over the inline function suggested because of performance reasons.

**Comment by alexpensify** [comment] 2024-09-27 18:03
@ikevin127 are we waiting for an update here? Sorry, I don't see the extra PR. Thanks!

**Comment by ikevin127** [comment] 2024-09-27 18:58
@alexpensify PR https://github.com/Expensify/App/pull/49477 for this issue was just deployed to production, no extra PR needed. ⚠️ Automation failed, this should be on **[HOLD for Payment 2024-10-04]** according to today's production deploy from https://github.com/Expensify/App/pull/49477#issuecomment-2379773426.

**Comment by alexpensify** [comment] 2024-09-27 20:31
Thank you for flagging the payment date and clarifying the status.

**Comment by alexpensify** [comment] 2024-10-04 22:19
Payouts due: 10-04-24

- [ ] Contributor: $250 @huult 
- [ ] Contributor+: $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~021833217065296959946). 

Closing - I believe that I sent the payment via Upwork, but something looks off in Upwork. Please reply if you didn't get the payment and go through the payment process again.

**Closed by alexpensify** 2024-10-04 22:19 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by ikevin127** [comment] 2024-10-04 22:24
@alexpensify I only got $125, was that on purpose or a mistake ?

<img width="676" alt="Screenshot 2024-10-04 at 15 24 13" src="https://github.com/user-attachments/assets/6067c0da-e815-4581-af09-9d3938af1298">

**Comment by alexpensify** [comment] 2024-10-04 22:27
No, there was an issue in Upwork so I input a Bonus too. Let me know if that second payment didn't go through.

**Comment by ikevin127** [comment] 2024-10-04 22:34
@alexpensify Indeed, Upwork is acting weird today (reported in other issues too).

So far nothing changed, I got $125 for this issue, looks same as https://github.com/Expensify/App/issues/48808#issuecomment-2394744681 and in **Overwiew** I only see the $125 transaction:

<img width="1015" alt="Screenshot 2024-10-04 at 15 33 05" src="https://github.com/user-attachments/assets/1610b6fa-02b2-47c4-8a0a-f0c98f4088a5">

Contract details look like this right now:

<img width="1305" alt="Screenshot 2024-10-04 at 15 33 33" src="https://github.com/user-attachments/assets/22f4cafb-3c25-472c-bf96-d1ec7308010c">

**Comment by alexpensify** [comment] 2024-10-04 22:37
Ok, I have a note to check again on Monday. Maybe there is a delay or something on the Upwork side. All my payment states are not updating correctly in Upwork today. If there is still an issue on Monday, I'll reach out to their support since I input a Bonus to correct the price issue.

**Comment by ikevin127** [comment] 2024-10-04 22:43
Understood!

For context: the same thing happened in this issue: https://github.com/Expensify/App/issues/48161 and the BZ wasn't able to do anything with the payment once the initial contract was ended without me being paid anything, so I'm assuming that your additional $125 bonus did not go through once the initial contract was ended after the $125 payment.

In the other issue, the BZ sent me another contract [saying](https://github.com/Expensify/App/issues/48161#issuecomment-2394394631):

> No idea what happened there. It doesn't show as being paid either. I'll send you another offer, but if you happen to get a rogue $125 show up - I'll trust your honesty to let me know. :)

To which I replied with:

> Sure, I accepted the new contract and will let you know in case it comes twice 👍

**Comment by huult** [comment] 2024-10-06 17:46
@alexpensify , Can you also check for me on Upwork? My contract for this ticket has ended, but the status on Upwork is still 'work in progress. thank you

**Comment by ikevin127** [comment] 2024-10-06 21:06
@alexpensify I still did not get the other $125, only got half of the payment for this issue so far.

**Comment by alexpensify** [comment] 2024-10-07 16:46
Thanks for these updates! There is an issue an Upwork that is being investigated to address the payment process. I'm going to hold until there is a fix. Convo: https://expensify.slack.com/archives/C01GTK53T8Q/p1728319262830679

**Comment by ikevin127** [comment] 2024-10-08 18:20
✅ Confirmation that I just got the other $125, thanks **Al** !

**Comment by huult** [comment] 2024-10-09 04:04
It was sent to me. Thank you, @alexpensify

**Comment by alexpensify** [comment] 2024-10-09 15:07
Awesome, thank you for confirming! This bug is a wild one on the Upwork side, so I appreciate your patience.
