### ISSUE TITLE
Inviting someone via mention shows as "hidden" and does not show in the members list

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32445] opened 2023-12-04 20:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7.-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701632925886219

## Action Performed:
1. Open a room
2. Invite someone using mention

## Expected Result:
Should display the full email in the chat and updated in the members list

## Actual Result:
Invited email is showing as hidden and not updated in the members list
NOTE: When inviting using invite flow does not show as "hidden" and updates in the members list as well

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (4)](https://github.com/Expensify/App/assets/38435837/4af5d91a-178b-47a1-a040-05cbad5a93fd)

![Snip - (74) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/f58c8099-401f-43bf-b89e-b89e69972ef8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2023-12-04 20:37
I'm tackling this internally already!

**Comment by jasperhuangg** [comment] 2023-12-05 03:22
https://github.com/Expensify/Expensify/issues/342901 I think we can close this out since it's a dupe of an internal issue

**Closed by jasperhuangg** 2023-12-05 03:22 UTC
Labels: Daily, Bug
