### ISSUE TITLE
All - CC - "Expensify Card - Applause Backup" was declined when it was added

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50651] opened 2024-10-11 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5067792
**Email or phone of affected tester (no customers):** fischer9966+101024aat@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a new Gmail account
2. Create a new workspace and submit a expense to start the free trial
3. Navigate to Account settings > Subscription
4. Click on "Add payment card"
5. Enter the credentials of the Credit Card called "Expensify Card - Applause Backup"
6. Verify the user can add a payment card in the subscription page

## Expected Result:
User can add a payment card in the subscription page

## Actual Result:
"Expensify Card - Applause Backup" was declined when it was added in the subscription page

## Workaround:
Undroid

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1710" alt="Bug6631146_1728591933018!Screenshot_2024-10-09_at_7 12 51_PM" src="https://github.com/user-attachments/assets/f9df2245-8232-4475-804f-17afd074498e">

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-11 14:11
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment] 2024-10-14 09:23
Tested and this is specific to this card. I think maybe it got disabled. Working on figuring it out

**Comment by mallenexpensify** [comment] 2024-10-14 22:08
Went down a bit of a 🐰🕳  Chat's in #qa [here](https://expensify.slack.com/archives/C9YU7BX5M/p1728943587870569?thread_ts=1728930352.165369&cid=C9YU7BX5M) and [here](https://expensify.slack.com/archives/C9YU7BX5M/p1728942660745409?thread_ts=1715193129.476489&cid=C9YU7BX5M) 

It sounds like someone deleted it, intentionally (possibly while testing) or accidentally.  I propose we :donothing: until the backup card is needed. Then, when so, we assign them a new test card

**Comment by sonialiap** [comment] 2024-10-15 08:33
Thanks for looking into this, Matt! 

Closing out since we're doing nothing at the moment

**Closed by sonialiap** 2024-10-15 08:33 UTC
Labels: Daily, Bug

**Comment by isagoico** [comment] 2024-10-16 13:56
I have created a new virtual card for Applause to use in the regressions. Same as the one that was declined here
