### ISSUE TITLE
[HOLD for payment 2023-10-31] Web - Login - Chat report loads infinitely with /undefined URL when logging in with a new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30126] opened 2023-10-21 17:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Sign up and log in

## Expected Result:
Chat will open

## Actual Result:
The chat report loads infinitely with /undefined URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS : Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/036da6ab-5197-4104-a957-d2c4ff2cf93c

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2023-10-21 23:07
Taking this over so we can deploy monday morning

**Comment by thienlnam** [comment] 2023-10-21 23:17
For some reason, reverting https://github.com/Expensify/App/pull/29893 still gets you to an /undefined page but it doesn't load forever.

There still seems to be another thing that is making it so that on log in it defaults to undefined

**Comment by thienlnam** [comment] 2023-10-21 23:38
Found the PR that caused this regression https://github.com/Expensify/App/pull/29739

**Comment by MitchExpensify** [comment] 2023-10-22 19:23
Anything needed from me here @thienlnam ?

**Comment by mountiny** [comment] 2023-10-22 21:31
<img width="1264" alt="image" src="https://github.com/Expensify/App/assets/36083550/41548afb-7b98-411d-8242-6e7e2a094a8a">

worked

**Comment by thienlnam** [comment] 2023-10-23 17:54
@MitchExpensify We'll just need to do a payout of the C+ that reviewed the fix (@allroundexperts)

**Comment by mallenexpensify** [comment] 2023-10-24 21:41
Was hoping this fix might also fix
- https://github.com/Expensify/App/issues/28495 

But it didn't.  I'm still getting crashes after NewDot desktop updates.  Not sure if related, consider this post more for _reference_

**Comment by MitchExpensify** [comment] 2023-10-25 21:54
Reassigning as I'm OOO

**Comment by sophiepintoraetz** [comment] 2023-10-25 21:55
@MitchExpensify - can you please summarise what needs to happen here?

**Comment by MitchExpensify** [comment] 2023-10-28 21:29
> We'll just need to do a payout of the C+ that reviewed the fix (@allroundexperts)

Just this on the 31st, I'll take this back as I'm back from vacay now 👍

**Comment by thienlnam** [comment] 2023-11-01 17:21
Looks like tis is ready for payment!

**Comment by MitchExpensify** [comment] 2023-11-03 22:57
**Payment summary:**

- C+ review $500 to @allroundexperts via NewDot

**Closed by MitchExpensify** 2023-11-03 22:57 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
