### ISSUE TITLE
[HOLD][$500] The tricky emoji in the title and description seems to be inconsistent.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31389] opened 2023-11-15 16:52 UTC
Held while working on an upstream feature request: https://native-html.canny.io/features/p/allow-for-multiple-font-families-when-rendering-on-the-web-via-react-native-web

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31259

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Click on Plus button - Assign Task
4. Input with emojis, especially tricky ones (e.g. 😶‍🌫️, 🏴󠁧󠁢󠁥󠁮󠁧󠁿),‍‍

## Expected Result:
The tricky emoji in the title and description should be consistent.

## Actual Result:
The tricky emoji in the title and description seems to be inconsistent.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (24)](https://github.com/Expensify/App/assets/93399543/f626e2c6-78d6-4d6f-9d6d-b19a236fa613)

https://github.com/Expensify/App/assets/93399543/434d4066-36cf-44f3-b6ae-dd682dc7d1e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ade86ce4ff9db84</li>
        <li>Upwork Job ID: 1724832892698370048</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>barros001 | Contributor | 27984024</li>
</ul></li>
    </ul>
</details>

**Comment by barros001** [comment] 2023-11-15 20:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Certain emojis looks different when displayed on title and description when assigning a task.

### What is the root cause of that problem?

The problem is because description, when rendered in the confirm task screen, is rendered using `RenderHTML`.

https://github.com/Expensify/App/blob/1eb1f7259bb8e45c1aad3a040539ce367178090b/src/components/MenuItem.js#L276-L278

RenderHTML, when setting the font family of a text, only sets to ONE family, as per their [documentation](https://meliorence.github.io/react-native-render-html/docs/content/textual)

> CSS ​font-family and ​font properties allow a comma-separated list of fonts, but React Native styles fontFamily allows only one font name. With the ​TRE, you can instruct which fonts are available in the system (or fonts you have added), and it will pick the first match! The prop to achieve that is ​systemFonts.

This causes the app to drop two emoji related fronts when rendering on the web, causing this inconsistency. Inspecting the title element on the web, we see the following `font-family`:

```css
    font-family: ExpensifyNeue-Regular, "Segoe UI Emoji", "Noto Color Emoji";
```

But if you inspect the element on the description, we see this:

```css
    font-family: ExpensifyNeue-Regular;
```

It did drop the other two fonts, which causes emojis to look different on certain platforms.

### What changes do you think we should make in order to solve the problem?

As mentioned above, using only one font is the expected behavior as stated in their documentation. To remedy that, I propose we wrap all emojis on the text with `<emoji></emoji>` tags and then create a custom renderer for this custom tag that will wrap it in a `<Text>` component, which ensure proper font families are set.

Wrapping emojis with a custom tag can be implemented here:

https://github.com/Expensify/App/blob/1eb1f7259bb8e45c1aad3a040539ce367178090b/src/components/MenuItem.js#L127-L138

And the renderer would look like this:

```ts
function EmojiRenderer(props) {
    return <Text>{props.tnode.data}</Text>;
}
```

```ts
export default {
    // Standard HTML tag renderers
    a: AnchorRenderer,
    code: CodeRenderer,
    img: ImageRenderer,
    emoji: EmojiRenderer, // new custom renderer

    // Custom tag renderers
    edited: EditedRenderer,
    pre: PreRenderer,
    'mention-user': MentionUserRenderer,
    'mention-here': MentionHereRenderer,
};
```

This will force all emojis to be wrapped in `<span>` with the correct `font-family` applied.


### What alternative solutions did you explore? (Optional)


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by barros001** [comment] 2023-11-15 21:23
## Proposal

[Updated](https://github.com/Expensify/App/issues/31389#issuecomment-1813217107)

Added more information to the proposal as well as screenshots of before and after solution.

**Comment by 5war00p** [comment] 2023-11-15 22:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tricky emoji in the title and description seems to be inconsistent
### What is the root cause of that problem?

After some deep investigation, I was able to find the **real root-cause**. 

As per the documentation what we did is we provided custom font styles here https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L73

Here we're only providing the simple font i.e `ExpensifyNeue-Regular` which doesn't contain the font required to render the fonts.

### Ref1: 

https://github.com/Expensify/App/blob/bf35c29b74e548b9fa7128e51658df039fb6d492/src/styles/fontFamily/multiFontFamily.ts#L11

### Ref2:

https://github.com/Expensify/App/blob/df377f22e5820e6e524b065360e186f77a8e9625/src/styles/fontFamily/singleFontFamily.ts#L7

The font-family inside Ref2 we're passing it here https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L70

So to put things into perspective, we need to update the font-style we're passing to the `RenderHTML` component which should contain the font-family of emojis to.

> We should also need to update styles according to os which we're doing in `multiFontFamily.ts`

Even after adding the emoji font-family this issue won't be solved, because the underlying the HTMLEngine is stripping the font-family we're passing and only taking the first font-family we pass.

https://github.com/native-html/core/blob/4c37d2915feb8c071d060b08d54f5ef5fd9c9afc/packages/css-processor/src/validators/LongFontFamilyPropertyValidator.ts#L5-L22

The above code-snippet that is responsible for passing `fontFamily` css prop to the `Text` component.

If we observe the code carefully, the code split the font-family with comma `,` as a separator and check if the font is supported or not.

While checking the font is supported or not, by default every string is supported, we return the string.

Means if we have font-family `ExpensifyNeue-Regular, Seoge UI Emoji` the code block will just return `ExpensifyNeue-Regular` which doesn't give the OP we wanted.

https://github.com/native-html/core/blob/4c37d2915feb8c071d060b08d54f5ef5fd9c9afc/packages/css-processor/src/default.ts#L38-L40


### What changes do you think we should make in order to solve the problem?
Patch with our App repo.

#### Fix

Since React Native only supports one font-family, but web-browser does and as this issue only occurs in Windows (tried in mac, but never was able to repro)

We have two function that returns the font value `normalizeRawInlineCSSValue` and `normalizeNativeValue`

We can update the code detect if the environment it's running is weather the runtime is browser or application.

If the environment is application we can leave the code as is, or the environment is browser we could simply return the value which will return all the font-family.



### What alternative solutions did you explore? (Optional)
NA


https://github.com/Expensify/App/assets/57614947/b99ae4e3-9177-4f17-badc-aea0bec15068

**Comment by akamefi202** [comment] 2023-11-15 22:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tricky emoji in the title and description seems to be inconsistent.

### What is the root cause of that problem?
It is a regression from https://github.com/Expensify/App/pull/29158.

https://github.com/Expensify/App/blob/0b0518dde95d35f786fbf918a3b6e99424e0c6fa/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L73

We inputed `singleFontFamily` in `systemFonts` prop of `TRenderEngineProvider` component.
This means it will ignore alternative font families for emojis, while rendering text by `react-native-render-html` library.
It will only use first font family. For example, `ExpensifyMono-Regular`.

This is why we see inconsistency of emoji in some devices, if the emoji is rendered by `react-native-render-html` library.
And in reproduction steps of this issue, the description with emoji is rendered by `RenderHTML` component using `react-native-render-html` library.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/0b0518dde95d35f786fbf918a3b6e99424e0c6fa/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L82

We can add alternative font families by adding custom HTML render to `htmlRenderers` variable.

https://github.com/Expensify/App/blob/0b0518dde95d35f786fbf918a3b6e99424e0c6fa/src/components/MenuItem.js#L137

Since the text with emojis is wrapped by `<comment>` tags, I think we can add a custom render for this. For example, `CommentRenderer`.

I don't think we need to add extra tags to wrap emojis because it might cause another regression.
For example, if the user selects the text which contains emojis and copy & paste it, extra tags might be pasted too.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by barros001** [comment] 2023-11-15 23:01
## Proposal

[Updated](https://github.com/Expensify/App/issues/31389#issuecomment-1813217107)

Updated proposed location for wrapping emojis in a tag from `MenuItem` to the `RenderHTML` component itself as to encapsulate the logic in it, allowed for reusability and preventing possible side effects.

**Comment by barros001** [comment] 2023-11-16 02:07
## Proposal

[Updated](https://github.com/Expensify/App/issues/31389#issuecomment-1813217107)

Turns out there's a much simpler way to get this to work without creating new tag is custom renderers. its just a matter of setting the right `defaultTextProps`.

**Comment by barros001** [comment] 2023-11-16 11:59
## Proposal

[Updated](https://github.com/Expensify/App/issues/31389#issuecomment-1813217107)

Back at my original proposal, forcing font-family on all text nodes caused problems with code blocks and possibly other places.

**Comment by situchan** [comment] 2023-11-18 03:38
Based on https://github.com/Expensify/App/issues/31393#issuecomment-1817182124, should this be closed too?

**Comment by barros001** [comment] 2023-11-18 03:52
I believe this one is a little different in the sense that it affects the `RenderHTML` component in general, which is used in several other places around the app, not only the field described in the issue.

**Comment by sonialiap** [comment] 2023-11-20 15:00
I also think that this issue is different. https://github.com/Expensify/App/issues/31393 was specifically about expiration date and CVV fields which weren't important/useful to fix because banking data does not contain emojis so emojis shouldn't even be entered into those fields. The issue here is referring to tasks. Tasks can be created with emojis as there is no reason to prevent their entry so I think this can be fixed. If we can create a solution that will fix this for all fields in the app, even better.

**Comment by barros001** [comment] 2023-11-20 16:19
Fixing it in the `RenderHTML` component should fix it everywhere in the app, including report comments (which also have the same issue, entering the combination below will trigger the issue).

```
`something`😶‍🌫️
```

**Comment by sonialiap** [comment] 2023-11-23 11:40
Nice, sounds like we have a plan! Do we have a proposal that would do this? @robertKozik

**Comment by robertKozik** [comment] 2023-11-24 12:29
Sprry for keeping you waiting. Looking into proposals 👀

**Comment by barros001** [comment] 2023-11-24 12:48
## Proposal

[Updated](https://github.com/Expensify/App/issues/31389#issuecomment-1814306222)

I just added a new alternative approach to my proposal, to create a web specific component that would patch the element's fontFamilies after render.

**Comment by robertKozik** [comment] 2023-11-24 12:53
Is there any reliable way of reproducing it either on mac or emulators? I've tried on OSX/chrome and android emualtor with no luck:

<img width="416" alt="image" src="https://github.com/Expensify/App/assets/61146594/0343d6b1-977e-4029-86c1-390c3b84fff8">

**Comment by barros001** [comment] 2023-11-24 12:56
@robertKozik On desktop, I manually installed the "Noto Color Emoji" font on my Mac and I can reproduce it on Chrome.

**Comment by robertKozik** [comment] 2023-11-24 13:00
Thanks @barros001 is there any additional step after `Noto Color Emoji` instalation?

**Comment by barros001** [comment] 2023-11-24 13:12
As far as I remember, I just installed it and restarted chrome. Before I installed the font, my emoji looked like this on both Chrome and Safari.

![image](https://github.com/Expensify/App/assets/765936/0f10f04a-39b7-4a58-9c68-7e328f9fadea)

After it looked like this:

![image](https://github.com/Expensify/App/assets/765936/170eec27-c95c-4f4c-90df-fa38defa992d)

**Comment by robertKozik** [comment] 2023-11-24 14:14
As stated in `react-native-render-html` multiple font families are not working on `react-native`. So I believe this bug is web-exclusive, moreover it looks like it is very hard to reproduce on Macs as we need to manually install specific font... I'll be glad if someone would check me if I'm thinking right on this statements:
1. Bug can be described as windows web specific
2. Until now applying specific emoji font family worked only on web, especially on windows as on mac we need to install font family

**Comment by barros001** [comment] 2023-11-24 14:34
@robertKozik i believe you are correct.

- Native mobile are not affected as they can’t have multiple fonts in the first place.
- Mac does not have any of the extra fonts installed and for this reason it’s not really an issue unless someone installs it (could happen but not the base case)
- Mobile web seems to not be a problem either as androids default emoji font is already one of the extra fonts. Having it explicitly or not makes no difference. IOS doesn’t have them, same as above. 
- I do not have windows but it appears the original video on this issue was recorded on windows. Maybe windows does have one of the extra fonts but it’s not the default for emojis? That would explain it. 

I’m curious as to why exactly we have the 2 extra emoji fonts. Understanding the reasoning behind that could help us better understand the impact here.

**Comment by robertKozik** [comment] 2023-11-27 14:27
This can be the reason why we specify them: https://github.com/Expensify/App/blob/edcf8f8352dc5e80b07a249658c6fada0e88e180/src/styles/fontFamily/multiFontFamily.ts#L6-L7

**Comment by barros001** [comment] 2023-11-27 14:32
@robertKozik I see, so looks like it really only affects windows and Ubuntu users for the most part. Let me know your thoughts on my [proposal](https://github.com/Expensify/App/issues/31389#issuecomment-1813217107). I kinda like the alternate proposal as it doesn’t involve any new elements being added which could potentially cause regressions, although it might look a little hacky.

**Comment by robertKozik** [comment] 2023-11-27 21:19
I see that you consider fixing upstream as well @barros001 . I can't see any details about that approach and I'm wondering whether It would be a difficult task prone to regressions inside lib itself as I can imagine that it can be assumed the font will be single after validator runs on it.

**Comment by robertKozik** [comment] 2023-11-28 21:07
Yeah, It's clear to me that there is no ideal solution for this situation. I'll approve your proposal to get a fresh pair of internal eyes on this issue.
In my opinion patching this scenario upstream won't be an option as it is clearly stated as design choice of `react-native-render-html` and your solution should we quite efficient to cope with this problem without regressions.

But what bothers me is that problem could be quite niche and to actually cope with it we need to not so efficiently patch the html before rendering. To be honest I would actually opt for closing this issue as it requires very specific setup for reproduction on mac, and only occurs on windows.

🎀 👀 🎀 C+ reviewed

**Comment by barros001** [comment] 2023-11-29 04:20
## Proposal

[Updated](https://github.com/Expensify/App/issues/31389#issuecomment-1813217107)

@robertKozik I just modified my proposal to add yet another alternate solution (see the first solution within the "What alternative solutions did you explore"). It's **_almost_** perfect. It's simple and works great without any of the complexity of the other proposals. But as you will see, there's one caveat that might or might not be too big to ignore.

**Comment by 5war00p** [comment] 2023-11-30 13:24
Check this: https://github.com/Expensify/App/issues/31389#issuecomment-1813349167, I've already suggested an upstream fix.

**Comment by cristipaval** [comment] 2023-12-04 13:17
Who could open a PR to fix the upstream? Shall I assign @barros001 for this, @robertKozik?

**Comment by cristipaval** [comment] 2023-12-06 11:06
bump @robertKozik

**Comment by robertKozik** [comment] 2023-12-06 12:07
Yeah @barros001 has it in this alternative solutions so I think we can assign him

**Comment by barros001** [comment] 2023-12-07 18:38
I just wanted to get some clarify on how to handle this before I accept the Upwork offer, as this is somewhat out of our hands in the sense that we can start a discussion with the [native-html team](https://github.com/native-html/core/tree/master/packages/css-processor), potentially even propose a PR, but it's totally up to them whether they are open to it or not. I'd say the first step would be to raise an issue with the `css-processor` to get the discussion started and see what they think of the issue. They could acknowledge and decide to address it, or they might shut it down.

Thoughts on how to handle it in relation to Expensify/Upwork?

**Comment by sonialiap** [comment] 2023-12-11 13:17
@mountiny I think you've had past cases with issues that required upstream fixes. Do you have any thoughts on Carlos' question https://github.com/Expensify/App/issues/31389#issuecomment-1845907721?

**Comment by mountiny** [comment] 2023-12-11 13:34
I think we should definitely try to fix this upstream and I think we can wait some time too before creating some workaround for us as this is not really pressing issue

**Comment by cristipaval** [comment] 2023-12-13 11:34
> I just wanted to get some clarify on how to handle this before I accept the Upwork offer, as this is somewhat out of our hands in the sense that we can start a discussion with the [native-html team](https://github.com/native-html/core/tree/master/packages/css-processor), potentially even propose a PR, but it's totally up to them whether they are open to it or not. I'd say the first step would be to raise an issue with the `css-processor` to get the discussion started and see what they think of the issue. They could acknowledge and decide to address it, or they might shut it down.
> 
> Thoughts on how to handle it in relation to Expensify/Upwork?

@mountiny I think you missed our question. Could you please let us know your opinion about this 👆 ?

**Comment by mountiny** [comment] 2023-12-13 12:59
We would pay once this is fixed. Either through upstream or through a work around, in the mean time you dont have to be hired on upwork and thi issue can be put on hold for the outcome of the efforts to fix this upstream, if lets say in a month there is no traction you can try to fix this in App, then we would hire you.

**Comment by dragnoir** [comment] 2023-12-14 13:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Windows emojis change when there is markdown in the message.

### What is the root cause of that problem?

When there's any HTML (fragments/markdown..) on the comment, the `TextCommentFragment` will use `RenderHTMLSource` to render the element.

The `TRenderEngineProvider` from `RenderHTMLSource` use `baseStyle` to render the element inline style.
https://github.com/Expensify/App/blob/38b3990ce5a3823ee75ec32a56926befa592f47a/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L76-L81

Until here we have 2 issues:
- The font missing `Windows Segoe UI Emoji`, is not listed inside `systemFonts` props

![image](https://github.com/Expensify/App/assets/12425932/945a650b-b0ef-4943-88cb-3cbb15edc7e3)

- The TRE will pick the first match as mentioned [here](https://meliorence.github.io/react-native-render-html/docs/content/textual#font-selection)
If we provide ⇒ `font-family: 'ExpensifyNeue-Regular, Windows Segoe UI Emoji, Noto Color Emoji',` 
then the TRE will pick the 1st available font wih is ExpensifyNeue-Regular and will ignore the rest.

### What changes do you think we should make in order to solve the problem?

1- We need to add `Windows Segoe UI Emoji` to `systemFonts`
```js
const  emojiRenderfonts  = ['Windows Segoe UI Emoji', ..._.values(singleFontFamily)];
// rest of the code
systemFonts={emojiRenderfonts}
```

2- We need to change the baseStyle to something like
```js
baseStyle={styles.webViewStyles.RenderHTMLSourceFontStyle}
```
Where `RenderHTMLSourceFontStyle` is a new style inside src/styles/styles.ts (`Windows Segoe UI Emoji` must be the 1st passed font)
```js
RenderHTMLSourceFontStyle: {
            color: theme.text,
            fontSize: variables.fontSizeNormal,
            fontFamily: `Windows Segoe UI Emoji, ${fontFamily.EXP_NEUE}`,
            flex: 1,
            lineHeight: variables.fontSizeNormalHeight,
            ...writingDirection.ltr,
        },
```
### POC
![image](https://github.com/Expensify/App/assets/12425932/6cdb4400-1c61-43f1-8e3f-ceeca47e9f46)

**Comment by dragnoir** [comment] 2023-12-14 13:42
@sonialiap @robertKozik I worked on the same issue [here](https://github.com/Expensify/App/issues/32833).
I just noticed this one. Please check my proposal just posted. It's simple, easy fix and handle all similar issues.

**Comment by cristipaval** [comment] 2023-12-14 14:19
> @sonialiap @robertKozik I worked on the same issue [here](https://github.com/Expensify/App/issues/32833). I just noticed this one. Please check my proposal just posted. It's simple, easy fix and handle all similar issues.

Interesting! What do you think about this solution, @robertKozik?

**Comment by shubham1206agra** [comment] 2023-12-14 17:22
@cristipaval I have already proposed the same solution earlier than @dragnoir in the other issue. It has some problems right now.  Example - If you use `*text[emoji]*`, it will not work properly right now

Let me see if I can solve it, and will let you know here.

**Comment by dragnoir** [comment] 2023-12-14 22:16
@shubham1206agra this happen because the render-native-jtml will replace the <strong> with a style specified here
https://github.com/Expensify/App/blob/f10f7089e105e90db9982ca0a6dffc8a0f592969/src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js#L79

and the style is from here
https://github.com/Expensify/App/blob/f10f7089e105e90db9982ca0a6dffc8a0f592969/src/styles/index.ts#L143-L145

So when we have a <strong> ****** </strong> and will be rendered with `RenderHTMLSource`, another style will be applied, and this can simply be fixed by changinf the strong style to:
```js
strong: {
	fontWeight:  'bold',
},
```

POC:
![image](https://github.com/Expensify/App/assets/12425932/22ba4e3d-0518-4ef0-ae01-becfd75e9a82)

**Comment by shubham1206agra** [comment] 2023-12-15 05:24
@dragnoir I have listed only one case, there are many cases where this will break

**Comment by dragnoir** [comment] 2023-12-15 09:53
@shubham1206agra I did more testing and it's working good.
Pls check my alternative solutions, it's better and use the same concept.

**Comment by shubham1206agra** [comment] 2023-12-15 10:14
@dragnoir It still doesn't work properly

**Comment by dragnoir** [comment] 2023-12-15 10:17
@shubham1206agra pls share the snippet that you used for testing and it doesn't work!

**Comment by cristipaval** [comment] 2023-12-18 12:54
> We would pay once this is fixed. Either through upstream or through a work around, in the mean time you dont have to be hired on upwork and thi issue can be put on hold for the outcome of the efforts to fix this upstream, if lets say in a month there is no traction you can try to fix this in App, then we would hire you.

@barros001 are you fine with this? Have you worked on the upstream fix yet?

**Comment by barros001** [comment] 2023-12-19 09:50
@cristipaval yes, I'm totally fine with this. I have not yet worked on a upstream fix but I'll try and start the conversation over there.

**Comment by dragnoir** [comment] 2023-12-19 16:38
@cristipaval @robertKozik [proposal](https://github.com/Expensify/App/issues/31389#issuecomment-1855873297) updated with clean steps to follow

**Comment by cristipaval** [comment] 2023-12-19 16:44
Thanks for your proposal @dragnoir. We removed the `Help Wanted` label because we're going with the @barros001 proposal.

**Comment by cristipaval** [comment] 2024-01-02 19:21
@barros001, do you have any updates?

**Comment by s77rt** [comment] 2024-01-17 00:01
Will take this as C+
@cristipaval Can you please assign me here (assuming there is work left to do here?)

**Comment by s77rt** [comment] 2024-01-29 20:49
@cristipaval Why is this issue put on hold? There is no open PR.

Let's try to get someone to submit a PR then we can put this on hold

**Comment by dragnoir** [comment] 2024-01-30 07:06
@s77rt pls check [my proposal](https://github.com/Expensify/App/issues/31389#issuecomment-1855873297) when you have time, it solve all the issues, this one and others with the same problem like https://github.com/Expensify/App/issues/32833

The idea is not to assign any fonts to RenderHTMLSource and use the font from the app.

**Comment by s77rt** [comment] 2024-01-30 09:00
@dragnoir I think that's also a workaround. It's best to fix the root cause.

**Comment by cristipaval** [comment] 2024-01-30 11:01
> @cristipaval Why is this issue put on hold? There is no open PR.
> 
> Let's try to get someone to submit a PR then we can put this on hold

See [this](https://github.com/Expensify/App/issues/31389#issuecomment-1889865300)

**Comment by dragnoir** [comment] 2024-01-30 18:33
They are not actif there, https://native-html.canny.io/features?status=complete
Zero completed feature. Some requested from 2021 with 8 rates and nothing. I don't feel an update is coming soon.

Maybe a PR here will grab more attention https://github.com/meliorence/react-native-render-html/pulls !

**Comment by s77rt** [comment] 2024-01-31 00:05
@cristipaval I agree with @dragnoir here. We should push for a PR rather than wait for the maintainers to implement the feature.

**Comment by dragnoir** [comment] 2024-02-22 09:27
So, what's the next step here?

**Comment by s77rt** [comment] 2024-04-04 20:42
@barros001 Your PR is merged 🎉 Any plan on opening a PR on `react-native-render-html `

**Comment by cristipaval** [comment] 2024-05-07 12:39
@barros001 could you please post an update when you have time?

**Comment by cristipaval** [comment] 2024-05-22 18:58
Thanks @dragnoir! I'll close it then!

**Closed by cristipaval** 2024-05-22 18:58 UTC
Labels: Engineering, Monthly, Bug
