### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250] [TS Migration] Define a concise way to access or default to an inexistent record

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39125] opened 2024-03-27 22:58 UTC
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Define a concise way to access or default to an inexistent record (0, -1, etc)

Any more details for this one cc @blazejkustra @fabioh8010
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127e590dfa2accb42</li>
        <li>Upwork Job ID: 1780548153949810688</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>godofoutcasts94 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by fabioh8010** [comment] 2024-04-16 08:53
## Problem

Currently we have been defaulting nullable entity IDs to either `0` or `-1` when it doesn’t exist as we can see [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts) and [here](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.ts) (and many other files throughout the project). The lack of conciseness when defaulting such IDs leads to confusion between developers and increased chance of bugs.

## Solution

Standartise the default values of all Onyx entity IDs. Personally I think we should default all nullable entity IDs to `-1` as it is a negative ID and theoretically we would never have a negative one in the DB (@mountiny makes sense to you?):

1. For each Onyx type inside `src/types/onyx/`, look for properties that ends with `ID?: ...`, e.g. `managerID?: number;`, `parentReportID?: string;`, `iouReportID?: string;` inside [Report.ts](https://github.com/Expensify/App/blob/main/src/types/onyx/Report.ts)
2. For each property, look for its usage throughout the codebase.
3. If that property is being defaulted to either `0` or `-1`, change it to `-1`.
4. Test everything extensively.

**Comment by mountiny** [comment] 2024-04-16 20:34
@fabioh8010 this makes sense to me, but I think we need to bring this up to slack for broader agreement, can you post the proposal to open source channel before proceeding?

**Comment by fabioh8010** [comment] 2024-04-17 07:57
@mountiny Sure, I can post! But could you make this issue External? It was marked as External initially.

**Comment by godofoutcasts94** [comment] 2024-04-17 11:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Define a concise way to access or default to an inexistent record
### What is the root cause of that problem?
**Coming from TS Migration Issue**,  As discussed in the comment here - https://github.com/Expensify/App/issues/39125#issuecomment-2058578891, we need to look for properties that ends with ID?: ..., e.g. managerID?: number;, parentReportID?: string;, iouReportID?: string; inside [Report.ts](https://github.com/Expensify/App/blob/main/src/types/onyx/Report.ts)
### What changes do you think we should make in order to solve the problem?

We need to standartise the default values of all Onyx entity IDs. we need to change the property to `-1` in the codebase. We need to add tests for it as well.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by fabioh8010** [comment] 2024-04-17 14:30
> @fabioh8010 this makes sense to me, but I think we need to bring this up to slack for broader agreement, can you post the proposal to open source channel before proceeding?

Posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1713364208904719).

**Comment by fabioh8010** [comment] 2024-04-17 17:26
> > @fabioh8010 this makes sense to me, but I think we need to bring this up to slack for broader agreement, can you post the proposal to open source channel before proceeding?
> 
> Posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1713364208904719).

⚠️ Solution was approved, but let's consider this additional change:

> Change `TS_STYLE.md` to include this advice of using `-1` to default these kind of ID properties.

**Comment by jjcoffee** [comment] 2024-04-18 15:21
@godofoutcasts94 Thanks for your [proposal](https://github.com/Expensify/App/issues/39125#issuecomment-2061057860)! It's a bit copy & pastey as it stands, so could I ask you to provide an example of a change you would make so that I can make sure you understand the issue. Thanks!

**Comment by godofoutcasts94** [comment] 2024-04-23 13:19
Hey @jjcoffee sorry for late reply.  Updated [proposal](https://github.com/Expensify/App/issues/39125#issuecomment-2061057860)

**Comment by jjcoffee** [comment] 2024-04-24 15:42
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2024-04-25 08:59
Thanks for adding that @godofoutcasts94, your [proposal](https://github.com/Expensify/App/issues/39125#issuecomment-2061057860) LGTM! Just note that you should also cover this in your PR:

> Change TS_STYLE.md to include this advice of using -1 to default these kind of ID properties.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by godofoutcasts94** [comment] 2024-04-26 16:26
In the `TS_STYLE.md` should I add a point here :
https://github.com/Expensify/App/blob/8c076114b448a964b69c2c2102bb75c4f7ca4b90/contributingGuides/TS_STYLE.md?plain=1#L29
to include an advice of using `-1` to default these kind of ID properties.

**Comment by jjcoffee** [comment] 2024-04-29 09:48
@godofoutcasts94 Yup that sounds good!

**Comment by godofoutcasts94** [comment] 2024-04-29 15:14
Hey @jjcoffee! One more help please - Is this text fine ? 

>  [1.23](#inexistent-record) **Defining Inexisting Record**: Always use `-1` when defining inexisiting records instead of using `0`

**Comment by jjcoffee** [comment] 2024-04-30 09:54
@godofoutcasts94 Just add it to the PR and we'll handle it there :pray:

**Comment by godofoutcasts94** [comment] 2024-05-01 14:49
You will have the PR ready in a couple of days

**Comment by jjcoffee** [comment] 2024-05-02 11:08
Okay, just a heads up I'll be OOO 6-13th (I may have some time on the 6th), so would be good to get a PR up today or tomorrow if you can!

**Comment by fabioh8010** [comment] 2024-05-06 16:15
@godofoutcasts94 Any updates here?

**Comment by fabioh8010** [comment] 2024-05-06 16:19
Thanks for the update!

**Comment by johncschuster** [comment] 2024-05-08 21:35
This isn't overdue, Melvin. @godofoutcasts94 is working on it (welcome back!)

**Comment by godofoutcasts94** [comment] 2024-05-11 13:59
I am done with all the changes, now I need some guidance related to adding test

**Comment by fabioh8010** [comment] 2024-05-13 08:11
@godofoutcasts94 Could you create a PR (or Draft PR) with the changes in the meantime? Thanks

**Comment by godofoutcasts94** [comment] 2024-05-13 10:06
https://github.com/Expensify/App/pull/41775

**Comment by jjcoffee** [comment] 2024-05-14 10:23
> now I need some guidance related to adding test

@godofoutcasts94 Here if you need any help! It might be faster if you ask on Slack and tag us all.

**Comment by johncschuster** [comment] 2024-05-16 17:40
@godofoutcasts94 How's the PR going?

**Comment by blazejkustra** [comment] 2024-05-20 14:37
@godofoutcasts94 Bump 👀

**Comment by godofoutcasts94** [comment] 2024-05-20 14:42
Hello @blazejkustra having some queries and discussions on slack with @jjcoffee

**Comment by blazejkustra** [comment] 2024-05-21 06:38
@godofoutcasts94 Feel free to tag me if it's a thread on open source channel

**Comment by jjcoffee** [comment] 2024-05-21 13:29
@blazejkustra We are just discussing how to write the tests/take screenshots for the PR, so no need for you at this stage I don't think. Will ping you if we have any questions that come up, the PR will hopefully be ready soon!

**Comment by jjcoffee** [comment] 2024-05-21 13:32
@godofoutcasts94 has [agreed](https://expensify.slack.com/archives/C01GTK53T8Q/p1716298334320689?thread_ts=1715756431.322869&cid=C01GTK53T8Q) to get the PR ready for review by EOD tomorrow.

**Comment by mountiny** [comment] 2024-05-23 10:35
Its been over a month with very little progress here. I have gone ahead and after a short discussion in the PR unassigned @godofoutcasts94. Thank you for your help here, we need to move faster to get our focus on more important stuff.

**Comment by DylanDylann** [comment] 2024-05-23 11:02
@mountiny  If we still find a contributor, I am happy to take over this issue and create a quick PR

**Comment by mountiny** [comment] 2024-05-23 13:05
Thank you Dylan, I think we are going with @fabioh8010's team to get this sorted out

**Comment by kubabutkiewicz** [comment] 2024-05-24 08:38
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by kubabutkiewicz** [comment] 2024-05-28 08:45
Hi, I am still working on that, currently I am testing all changes and checking if there aren't any regressions

**Comment by fabioh8010** [comment] 2024-05-28 09:37
@kubabutkiewicz We can also ask for a full regression test when opening the PR, would be good to have it.

**Comment by johncschuster** [comment] 2024-06-24 16:18
Discussing in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1719241991045089) to make sure I'm understanding the correct payment date

**Comment by johncschuster** [comment] 2024-06-25 15:09
@jjcoffee do we need a regression test for this? If so, can you propose the steps?

**Comment by johncschuster** [comment] 2024-06-25 15:12
# Payment Summary:
Contributor: @kubabutkiewicz  - does not require payment
Contributor+: @jjcoffee  - $250 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/102030866) - PAID

**Comment by jjcoffee** [comment] 2024-06-26 08:49
> do we need a regression test for this? If so, can you propose the steps?

@johncschuster No I don't think so, since this is an app-wide change.

**Closed** 2024-06-26 14:31 UTC
Labels: External, Daily, NewFeature, Task, Awaiting Payment, Typescript Migration
