### ISSUE TITLE
 Share code - Share code RHN is shaking

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24581] opened 2023-08-15 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Share code.

## Expected Result:
Share code menu does not shake

## Actual Result:
Share code menu shakes. It seems to happen only when the page is slightly zoomed in (my browser is at 100% without the need to zoom in) and the Share code menu does not fit the screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a8591cb8-48a1-4418-9968-9a846799b1fc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-08-15 16:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Share code RHN is shaking.

### What is the root cause of that problem?
We does not disable `ScrollView`'s vertical scroll bar in `ShareCodePage`.

### What changes do you think we should make in order to solve the problem?
We can disable vertical scroll bar in [this line](https://github.com/Expensify/App/blob/1215c0381777b13d15381fd843e82905dcb0d130/src/pages/ShareCodePage.js#L63).
```js
    <ScrollView style={[styles.flex1, styles.mt3]} showsVerticalScrollIndicator={false}>
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by jfquevedol2198** [comment] 2023-08-16 12:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Share code - Share code RHN is shaking

### What is the root cause of that problem?
It happens scrollbar is enabled or not when Share code content's height gets smaller.
When there is no scrollbar, QRcode size calculates without scrollbar, but Share code content's height gets bigger, so scrollbar is enabled. If scrollbar is enabled, QRcode size recalculates and gets smaller, so scrollbar is not enabled again.
It gets loop of scrollbar enabled & not-enabled.

### What changes do you think we should make in order to solve the problem?
We always need to enable scrollbar in specific amount of screen size.
Update [ShareCode.js](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/ShareCodePage.js) so that scrollbar can be always enabled from the moment of scrollbar visibility gets shaking

```javascript
class ShareCodePage extends React.Component {
    qrCodeRef = React.createRef();

    contentRef = React.createRef();

    constructor(props) {
        super(props);
        this.state = {
            scrollbarEnabled: false,
        };
        this.onLayout = this.onLayout.bind(this);
    };

    onLayout() {
        const currentScrollViewHeight = this.contentRef.current.clientHeight;
        const scrollViewHeight = this.props.windowHeight - variables.contentHeaderHeight;

        if (this.state.scrollbarEnabled) {
            if (currentScrollViewHeight < scrollViewHeight - 16) {
                this.setState({scrollbarEnabled: false});
            }
            return;
        }
        if (currentScrollViewHeight > scrollViewHeight) {
            this.setState({scrollbarEnabled: true});
        }
    }

    render() {
        const isReport = this.props.report != null && this.props.report.reportID != null;
        const subtitle = ReportUtils.getChatRoomSubtitle(this.props.report);

        const urlWithTrailingSlash = Url.addTrailingForwardSlash(this.props.environmentURL);
        const url = isReport
            ? `${urlWithTrailingSlash}${ROUTES.getReportRoute(this.props.report.reportID)}`
            : `${urlWithTrailingSlash}${ROUTES.getProfileRoute(this.props.session.accountID)}`;

        const platform = getPlatform();
        const isNative = platform === CONST.PLATFORM.IOS || platform === CONST.PLATFORM.ANDROID;
        const formattedEmail = this.props.formatPhoneNumber(this.props.session.email);

        return (
            <ScreenWrapper>
                <HeaderWithBackButton
                    title={this.props.translate('common.shareCode')}
                    onBackButtonPress={() => Navigation.goBack(isReport ? ROUTES.getReportDetailsRoute(this.props.report.reportID) : ROUTES.SETTINGS)}
                />
                <ScrollView style={[styles.flex1, styles.mt3, {overflowY: this.state.scrollbarEnabled ? 'scroll' : 'hidden'}]} onLayout={this.onLayout}>
                    <View ref={this.contentRef}>
                        <View style={styles.shareCodePage}>
                            <QRShareWithDownload
                                ref={this.qrCodeRef}
                                url={url}
                                title={isReport ? this.props.report.reportName : this.props.currentUserPersonalDetails.displayName}
                                subtitle={isReport ? subtitle : formattedEmail}
                                logo={isReport ? expensifyLogo : UserUtils.getAvatarUrl(this.props.currentUserPersonalDetails.avatar, this.props.currentUserPersonalDetails.accountID)}
                                logoRatio={isReport ? CONST.QR.EXPENSIFY_LOGO_SIZE_RATIO : CONST.QR.DEFAULT_LOGO_SIZE_RATIO}
                                logoMarginRatio={isReport ? CONST.QR.EXPENSIFY_LOGO_MARGIN_RATIO : CONST.QR.DEFAULT_LOGO_MARGIN_RATIO}
                            />
                        </View>

                        <View style={{marginTop: 36}}>
                            <ContextMenuItem
                                isAnonymousAction
                                text={this.props.translate('qrCodes.copyUrlToClipboard')}
                                shouldShowRightIcon
                                icon={Expensicons.Copy}
                                successIcon={Expensicons.Checkmark}
                                successText={this.props.translate('qrCodes.copied')}
                                onPress={() => Clipboard.setString(url)}
                            />

                            {isNative && (
                                <MenuItem
                                    isAnonymousAction
                                    title={this.props.translate('common.download')}
                                    icon={Expensicons.Download}
                                    // eslint-disable-next-line es/no-optional-chaining
                                    onPress={() => this.qrCodeRef.current?.download()}
                                />
                            )}
                        </View>
                    </View>
                </ScrollView>
            </ScreenWrapper>
        );
    }
}

ShareCodePage.propTypes = propTypes;
ShareCodePage.defaultProps = defaultProps;

export default compose(withEnvironment, withLocalize, withCurrentUserPersonalDetails, withWindowDimensions)(ShareCodePage);
```

<details><summary>Result</summary>

https://github.com/Expensify/App/assets/137529618/8227c92b-9359-49e3-9496-0c237b12a8b3

</details> 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by muttmuure** [comment] 2023-08-29 13:33
It's not shaking but the Share Code page breaks when you resize the window

**Comment by jfquevedol2198** [comment] 2023-08-29 13:36
@muttmuure Its still sharing on prod (v1.3.57-6)

**Comment by muttmuure** [comment] 2023-08-29 13:47
Not seeing this for my own account

**Comment by jfquevedol2198** [comment] 2023-08-29 13:50
@muttmuure 

Uploading Screen Recording 2023-08-29 at 8.44.43 AM.mov…

**Comment by jfquevedol2198** [comment] 2023-08-29 13:50
@muttmuure 

https://github.com/Expensify/App/assets/137529618/82fcf2ed-f7a4-4cdd-831a-ffca1e9b4c20

**Comment by muttmuure** [comment] 2023-08-29 14:21
Sorry, I can't reproduce this. 

https://github.com/Expensify/App/assets/46995600/b48dc48b-a7d7-4bbb-9173-6f948afb7ac4

If you find it is reproducible and fixed somewhere else then we may be able to give you a reporting bonus. But for now I am going to close this out.

**Closed** 2023-08-29 14:22 UTC
Labels: Daily, Bug

**Comment by jfquevedol2198** [comment] 2023-08-29 14:31
@muttmuure 
<img width="967" alt="image" src="https://github.com/Expensify/App/assets/137529618/fe86e5b4-c3d4-4835-985e-7906da45c9ca">
You need to adjust screen size around the red square gradually.

**Comment by muttmuure** [comment] 2023-08-29 15:07
Thanks for clarifying. It seems like an over-optimization rather than a bug tbh
