### ISSUE TITLE
Expense - "Go to workspace" option is available when the workspace is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53767] opened 2024-12-09 17:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+23i0230@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace
3. Go to workspace chat
4. Submit an expense
5. Delete the workspace
6. Go back to workspace chat (now archived)
7. Click on the expense preview
8. Click on the report header
9. Click Go to workspace

## Expected Result:
"Go to workspace" option should be removed when the workspace is deleted

## Actual Result:
"Go to workspace" option is available when the workspace is deleted, which opens not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/79a4a663-7ba0-47ea-a3a3-8cc0f95486db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment] 2024-12-09 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Go to workspace" option is available when the workspace is deleted
### What is the root cause of that problem?
this does not considered deleted workspace: 
https://github.com/Expensify/App/blob/dc07fc67e8064b5941f7f8467d9bd5403c81f817/src/pages/ReportDetailsPage.tsx#L294
### What changes do you think we should make in order to solve the problem?
update this to: 
https://github.com/Expensify/App/blob/dc07fc67e8064b5941f7f8467d9bd5403c81f817/src/pages/ReportDetailsPage.tsx#L294
`    const shouldShowGoToWorkspace = policy && policy.type !== CONST.POLICY.TYPE.PERSONAL && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && !!PolicyUtils.getPolicyRole(policy, currentUserLogin);`

**Comment by nkdengineer** [comment] 2024-12-09 17:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Go to workspace" option is available when the workspace is deleted, which opens not here page

### What is the root cause of that problem?

We do not check the archived rooms in condition to show go to workspace [here](https://github.com/Expensify/App/blob/dc07fc67e8064b5941f7f8467d9bd5403c81f817/src/pages/ReportDetailsPage.tsx#L294)

https://github.com/Expensify/App/blob/dc07fc67e8064b5941f7f8467d9bd5403c81f817/src/pages/ReportDetailsPage.tsx#L294

### What changes do you think we should make in order to solve the problem?


We should add logic to check the archived rooms like we did with show hold option

```
const shouldShowGoToWorkspace = policy && policy.type !== CONST.POLICY.TYPE.PERSONAL && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && isArchivedRoom && !ReportUtils.isArchivedRoom(transactionThreadReportID ? report : parentReport, parentReportNameValuePairs);;
```
https://github.com/Expensify/App/blob/dc07fc67e8064b5941f7f8467d9bd5403c81f817/src/pages/ReportDetailsPage.tsx#L294

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mkzie2** [comment] 2024-12-09 18:00
It's a backend bug, after the policy is deleted, the backend still returns the policy data. But after clear cache and restart, this data doesn't exist.

<img width="1512" alt="Screenshot 2024-12-10 at 00 59 35" src="https://github.com/user-attachments/assets/b57ec188-9a44-4a99-8674-d4fc02d2976a">

**Comment by deetergp** [comment] 2024-12-09 19:56
Related to https://github.com/Expensify/App/pull/53076

**Comment by deetergp** [comment] 2024-12-09 20:40
Okay, I don't think that this is a blocker, but I also don't necessarily think we need to change the back end to get the desired result. Going mark External and tap a C+ for an extra set of eyes.

**Comment by deetergp** [comment] 2024-12-09 20:46
You can disregard this @stitesExpensify I was just added the label back while we discuss options.

**Comment by luacmartins** [comment] 2024-12-09 22:34
This is fixed in staging

**Closed by luacmartins** 2024-12-09 22:34 UTC
Labels: Reviewing, Engineering, Weekly
