### ISSUE TITLE
[$500]  DOB - Selected date doesn't persist when navigating back and returning to DOB picker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34294] opened 2024-01-10 21:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-01
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign up with a new account
2. Navigate to Settings > Profile > Personal details > Date of birth
3. Select Date/Moth/Year and don't save it
4. Navigate back to Personal Details page
5. Navigate back to 'DOB' picker

## Expected Result:
The selected date should persist

## Actual Result:
The selected date doesn't persist

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/12e55766-d610-4137-b6e7-1872a43f5129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d43c29e2861ed90</li>
        <li>Upwork Job ID: 1745192846174928896</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2024-01-10 21:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected date doesn't persist when navigating back and returning to DOB picker
### What is the root cause of that problem?
 the draft date is not saved because we dont pass the `shouldSaveDraft` here:

https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js#L85-L92
### What changes do you think we should make in order to solve the problem?

we need to pass `shouldSaveDraft`

**Comment by MelnykDmitro** [comment] 2024-01-10 21:29
I believe it supposed to not persist the DOB value without pressing "Save" button. Isn't it?

**Comment by abzokhattab** [comment] 2024-01-10 21:42
@MelnykDmitro  we already have this behavior in multiple areas in the project and according to the [Forms.md](https://github.com/Expensify/App/blob/7393ec51336c071b6c2e36c87dfada16eca2676c/contributingGuides/FORMS.md#form-drafts) documentation, saving drafts is highly desirable unless the data is sensitive.

**Comment by MelnykDmitro** [comment] 2024-01-10 21:48
> @MelnykDmitro we already have this behavior in multiple areas in the project and according to the [Forms.md](https://github.com/Expensify/App/blob/7393ec51336c071b6c2e36c87dfada16eca2676c/contributingGuides/FORMS.md#form-drafts) documentation, saving drafts is highly desirable unless the data is sensitive.

@abzokhattab Thank you for referencing and explaining. It makes sense.

**Comment by s77rt** [comment] 2024-01-11 08:36
This is not a bug. DOB is supposed to not have draft-enabled. Otherwise it would be confusing to tell if you are looking at the real saved date or the draft.

@miljakljajic This can be closed

**Comment by abzokhattab** [comment] 2024-01-11 12:13
@s77rt  but according to the documentation we have .. its highly recommended to enable save on draft unless the data is senstive  https://github.com/Expensify/App/blob/7393ec51336c071b6c2e36c87dfada16eca2676c/contributingGuides/FORMS.md#form-drafts

for reference we have this already enabled in multiple areas in the project https://github.com/Expensify/App/blob/2d06aa8fce765dd797433a3f2280166f53956a4b/src/pages/EnablePayments/AdditionalDetailsStep.js#L198 https://github.com/Expensify/App/blob/1234afe66bd182dad22f2d8ac1ce27045d6a0463/src/pages/ReimbursementAccount/ACHContractStep.js#L193 https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ReimbursementAccount/BankAccountManualStep.js#L122 https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ReimbursementAccount/BankAccountPlaidStep.js#L138 https://github.com/Expensify/App/blob/9ce24ae64f0328a4880714e219ae3c004fc944cb/src/pages/ReimbursementAccount/CompanyStep.js#L182 https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ReimbursementAccount/RequestorStep.js#L173 https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ReimbursementAccount/ValidationStep.js#L163 https://github.com/Expensify/App/blob/db37d3bae5dd8340deb1f4942fed69fddb09d20a/src/pages/settings/Wallet/Card/GetPhysicalCardAddress.js#L71 https://github.com/Expensify/App/blob/fda671cf5fd1b591e0b1ae9cc606a8560b25eb7b/src/pages/settings/Wallet/Card/GetPhysicalCardName.js#L85 https://github.com/Expensify/App/blob/680b45d3bca3fb2427bb43ebc9202bb9be65a1c7/src/pages/settings/Wallet/Card/GetPhysicalCardPhone.js#L76 https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/stories/Form.stories.js#L161

**Comment by s77rt** [comment] 2024-01-11 17:21
@abzokhattab This only applies if the form you are filling is write-only and/or multistep. If you are changing the display name, date of birth, a workspace name or a room name then we don't save drafts in this case.

**Comment by s77rt** [comment] 2024-01-14 23:28
@miljakljajic We can close this

**Comment by s77rt** [comment] 2024-01-17 21:35
To be closed

**Closed** 2024-01-22 14:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
