### ISSUE TITLE
[$250] Android - Chat - On editing text + attachment, text entered is displayed in delay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47714] opened 2024-08-20 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a [ch@t](mailto:ch@t)
3. Send a text + attachment (image)
4. Long press and select edit comment
5. Edit the text by typing any line

## Expected Result:
On editing text + attachment, text entered must not be displayed in delay

## Actual Result:
On editing text + attachment, text entered is displayed in delay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/efc2bee0-76c8-48c1-b73c-93de14b78b6b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01084bdfaf9d5d1394</li>
        <li>Upwork Job ID: 1828744727927604437</li>
        <li>Last Price Increase: 2024-10-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-08-20 13:30
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-08-20 13:30
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment] 2024-08-21 09:39
Reviewing today!

**Comment by eVoloshchak** [comment] 2024-09-09 12:07
Not overdue, this is awaiting proposals

**Comment by trjExpensify** [comment] 2024-09-10 01:11
This is a pure chat bug, moving to #vip-vsb.

**Comment by eVoloshchak** [comment] 2024-09-15 08:44
Not overdue, this is awaiting proposals

**Comment by JKobrynski** [comment] 2024-09-20 10:52
Hi! I'm Julian from Callstack and I started investigating this issue. While trying to reproduce it, I added a log to check the value of the message in the input throughout the process. The text I sent along with the attachment was there all along, it's just not visible initially as the whole message (text + ![attachment.pdf](path)) doesn't fit in the input, so to see/edit the message, you always have to scroll up. 

Am I getting this wrong? Would you expect a different behavior? Please let me know, I will be happy to help!

**Comment by eVoloshchak** [comment] 2024-10-01 10:17
> Unable to reproduce this issue since you can't edit a message containing an image

My original comment was wrong, you absolutely can edit a message that contains text and an attachment. 
However, I cannot reproduce the issue, for me, the text is entered without delay. 
Could this be device-specific? 
In the video attached to the issue description you can see a custom keyboard, is this issue reproducible when using the stock keyboard?

**Comment by dylanexpensify** [comment] 2024-10-04 08:59
Good question @eVoloshchak, cc @JKobrynski @lanitochka17 can you confirm?

**Comment by dylanexpensify** [comment] 2024-10-07 12:15
Bump @JKobrynski @lanitochka17

**Comment by JKobrynski** [comment] 2024-10-10 12:30
@dylanexpensify have you had the chance to take a look at my comment above? 🙏

**Comment by JKobrynski** [comment] 2024-10-15 08:05
Kindly bump @dylanexpensify @eVoloshchak

**Comment by eVoloshchak** [comment] 2024-10-18 12:17
@lanitochka17, what is the name of the custom keyboard used in [this](https://github.com/Expensify/App/issues/47714#issue-2475658602) video?

**Comment by dylanexpensify** [comment] 2024-10-18 13:01
Hey @jliexpensify! I'm heading out on parental leave so reassigning this! TY! 🙇‍♂️

**Comment by lanitochka17** [comment] 2024-10-18 19:41
Issue is not reproducible on the latest build 9.0.51-1


https://github.com/user-attachments/assets/28644de4-4251-420d-a970-c6313e55a4c2

**Comment by jliexpensify** [comment] 2024-10-20 06:03
Added the retest label for Applause. Going to keep this open for another week to see if the issue pops up again.

**Comment by fabioh8010** [comment] 2024-10-22 20:34
Hey 👋 Just FYI that @JKobrynski is on sick leave since yesterday and is expected to return next week.

**Comment by jliexpensify** [comment] 2024-10-24 02:18
Waiting on a retest, not overdue

**Comment by JKobrynski** [comment] 2024-10-24 10:32
Hey! FYI I'm back from the sick leave

**Comment by jliexpensify** [comment] 2024-10-24 22:29
@JKobrynski according to Applause, this issue doesn't exist anymore but just waiting on another re-test

**Comment by mvtglobally** [comment] 2024-10-30 09:41
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2024-10-31 01:22
Ok, I think we can close this since its not an issue anymore.

**Closed by jliexpensify** 2024-10-31 01:22 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug, retest-weekly
