### ISSUE TITLE
[$250] QAB split - Not here RHP opens when splitting expense via QAB after removing all group members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43316] opened 2024-06-07 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A*
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat
3. Split an expense in the group chat
4. Remove all members from the group chat
5. Wait until the members are really removed (app will present a system message)
6. Click FAB
7. Select Split expense under QAB

## Expected Result:
QAB will still allow split expense but it will instruct user to select split participant because the group is no longer valid

## Actual Result:
Split expense under QAB opens not here RHP
When clicking back button on the RHP, the animation of RHP dismissal is strange and the right panel becomes blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b7bd5ba7-3925-4fcc-af4f-624b9c6284ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d42ca8bdfee9753</li>
        <li>Upwork Job ID: 1801327424310575703</li>
        <li>Last Price Increase: 2024-06-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment] 2024-06-07 19:42
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-07 19:42
We think that this bug might be related to #vip-split

**Comment by bernhardoj** [comment] 2024-06-08 03:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
QAB split leads to not found page.

### What is the root cause of that problem?
When we remove all members from a group/room, we can't do a split expense anymore because it requires more than 1 participant, thus the not found page is shown.

The weird animation after going back is being fixed in [here](https://www.github.com/Expensify/App/pull/42976).

### What changes do you think we should make in order to solve the problem?

I think when we remove all members, we need to clear the QAB, similar to what we did here 
https://github.com/Expensify/App/blob/4176e95f4fa0867a56092af23193c6e2c8f4e23e/src/libs/actions/Report.ts#L2594-L2601

What we will do is to find the member left and if it's one left and the QAB is split, then clear it.
https://github.com/Expensify/App/blob/4176e95f4fa0867a56092af23193c6e2c8f4e23e/src/libs/actions/Report.ts#L2846
```
const memberLeft = Object.keys(report.participants ?? {}).length - (report.pendingChatMembers?.length ?? 0) - targetAccountIDs.length;
if (memberLeft === 1 && quickAction?.chatReportID?.toString() === reportID && quickAction?.action?.startsWith('split')) {
    optimisticData.push({
        onyxMethod: Onyx.METHOD.SET,
        key: ONYXKEYS.NVP_QUICK_ACTION_GLOBAL_CREATE,
        value: null,
    });
}
```

**Comment by kevinksullivan** [comment] 2024-06-13 18:55
Moving this forward and agree it should go to split.

**Comment by sobitneupane** [comment] 2024-06-17 09:44
This is the Expected output.
> QAB will still allow split expense but it will instruct user to select split participant because the group is no longer valid

@bernhardoj Can you please confirm what will be the output after your proposal? We will remove the QAB, right? 

What's your thought on EO?

**Comment by bernhardoj** [comment] 2024-06-17 11:12
> Can you please confirm what will be the output after your proposal? We will remove the QAB, right?

Correct

> What's your thought on EO?

I think it's weird if the QAB shows the group chat split but it behaves like a normal split flow.
<img width="198" alt="image" src="https://github.com/Expensify/App/assets/50919443/b703e4e1-6eeb-411d-b94c-1729c7fec976">

**Comment by kevinksullivan** [comment] 2024-06-17 18:12
What does it mean to remove the QAB? Can you elaborate on that @bernhardoj ?

**Comment by kevinksullivan** [comment] 2024-06-17 18:13
hey @VictoriaExpensify I am OOO the rest of the week so looping in another BZ member. Will pick it up when I return!

**Comment by bernhardoj** [comment] 2024-06-18 04:23
> What does it mean to remove the QAB? Can you elaborate on that @bernhardoj ?

It's to remove the quick action section here when all of the group members are removed.
<img width="198" alt="image" src="https://github.com/Expensify/App/assets/50919443/b703e4e1-6eeb-411d-b94c-1729c7fec976">

**Comment by sobitneupane** [comment] 2024-06-18 08:47
@kevinksullivan @VictoriaExpensify Is it okay to remove the Quick Action for Split Expense if all group members are removed?

**Comment by sobitneupane** [comment] 2024-06-24 07:21
https://github.com/Expensify/App/issues/43316#issuecomment-2175551952

Waiting for input from @kevinksullivan @VictoriaExpensify on expected output.

**Comment by kevinksullivan** [comment] 2024-06-26 15:42
checking on this one here

https://expensify.slack.com/archives/C05RECHFBEW/p1719416503863779

**Comment by kevinksullivan** [comment] 2024-06-26 16:40
Discussed internally and decided to do nothing.

**Closed by kevinksullivan** 2024-06-26 16:40 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
