### ISSUE TITLE
iPad - Login page is not appearing at the center and appears too close to top 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9121] opened 2022-05-20 23:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8752 
## Action Performed:
1. Launch the app
2. Verify that the login-form-layout is updated

## Expected Result:
Login form layout is centered

## Actual Result:
Log in page is located on the top of the header

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- iOS - iPad safari and app

**Version Number:** 1.1.65.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Image from iOS (20)](https://user-images.githubusercontent.com/93399543/169623807-b9685397-5c67-4f37-a965-6e2e4fe4f954.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-05-20 23:38
Also seems related to https://github.com/Expensify/App/pull/8752

**Comment by Santhosh-Sellavel** [comment] 2022-05-21 06:50
@aneequeahmad Check this one!
This seems like a breakage but not sure why the new design changes didn't reflect here.

**Comment by Julesssss** [comment] 2022-05-23 11:42
I asked [here](https://github.com/Expensify/App/issues/8122#issuecomment-1134566793) to confirm that we should expect to see the double panel layout on an iPad Pro

**Comment by Julesssss** [comment] 2022-05-23 13:47
@aneequeahmad there's a lot of comments to read through so I'm still a bit confused. The issue is that we're not seeing the [original vertically stacked design](https://github.com/Expensify/App/issues/8122#issuecomment-1066971554) on iPads. But please let me know if I misunderstood.

1) It sounds like the hardcoded cutoff had design approval ([this comment](https://github.com/Expensify/App/pull/8752#issuecomment-1121465770))
2) But at the same time, the [listed test case](https://github.com/Expensify/App/pull/8752#issuecomment-1133196935) is failing

My guess is that all iPad sizes are too small to meet the hardcoded cutoff (or require an alternate solution) to show the vertically stacked component. So I think we'll need another fix so that iPad matches the [original design](https://github.com/Expensify/App/issues/8122#issuecomment-1066971554). 

**iPad 12.9**
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-05-23 at 14 43 19](https://user-images.githubusercontent.com/10736861/169833138-1656ad57-0f15-4d96-afd9-7f092d0f98d6.png)

**Comment by Julesssss** [comment] 2022-05-24 16:24
Resolving the deployBlocker label as I submitted a hotfix which passed QA

**Comment by mvtglobally** [comment] 2022-05-31 03:19
Issue not reproducible during KI retests. (First week) @Julesssss  Can we close this?

**Comment by Santhosh-Sellavel** [comment] 2022-05-31 19:03
Melvin went mad I think!

**Comment by Santhosh-Sellavel** [comment] 2022-05-31 19:03
By the way, I think we are good to close this now!

**Closed** 2022-05-31 20:49 UTC
Labels: Reviewing, Engineering, Daily

**Comment by thesahindia** [comment] 2022-06-02 18:27
This issue is still reproducible 

https://user-images.githubusercontent.com/83179295/171700492-d48ed3c8-4bfd-43fa-9501-cde4a7dbdc3d.mov

cc: @Julesssss

**Comment by thesahindia** [comment] 2022-06-06 10:43
@Julesssss, should I report it on slack then?

**Comment by Julesssss** [comment] 2022-06-06 11:02
Yeah, I think so. Let's treat it as a new issue to solve.
