### ISSUE TITLE
[HOLD for payment 2023-11-29] [$500] Inconsistency bug - Assign Task - Task description does not remove empty quotes (works fine in private notes)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28342] opened 2023-09-27 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open task report or assign any user task and open the report
3. Open description
4. Enter text with multiple empty quotes eg:
```
> Hello
>
>
```
6. Save the description and observe that description displays only one quote with text on task page (which is correct)
7. Again open description and observe that extra greater then signs are not removed
8. Paste similar text in composer, send and edit and observe that extra greater then signs are removed
9. Similarly try the text in private notes of any user and observe that private notes too removes the extra signs

## Expected Result:
App should remove greater then signs with no text after it when description is saved like we do throughout the app

## Actual Result:
App does remove greater then signs with no text after it when description is saved in task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.74-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e73faad0-7050-47c0-afe2-6c111401c4b3

https://github.com/Expensify/App/assets/93399543/1e91fe16-3689-451b-86cf-4d3076294b02

https://github.com/Expensify/App/assets/93399543/2c3bc4a6-d324-4faf-acd0-496025996ce1

https://github.com/Expensify/App/assets/115492554/e4746bb4-5982-493c-ae8b-8d2ff5248307

https://github.com/Expensify/App/assets/115492554/055e5086-998b-42b7-883b-579e0cbd5a9b

https://github.com/Expensify/App/assets/115492554/c9a8b7d8-49dd-42dc-8ba0-b1cb402f0626

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695746974925629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbe475b72eea075d</li>
        <li>Upwork Job ID: 1707098020774612992</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27099861</li>
<li>dhanashree-sawant | Reporter | 27099863</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-09-27 18:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App should remove greater then signs with no text after it when description is saved like we do throughout the app
### What is the root cause of that problem?
We are trimming the description while saving the private notes here.
https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/PrivateNotes/PrivateNotesEditPage.js#L88-L95
### What changes do you think we should make in order to solve the problem?
We can directly save the privateNotes as we are saving description throughout the app.
```javascript
   const savePrivateNote = () => {
        Report.updatePrivateNotes(report.reportID, route.params.accountID, privateNote);
        Keyboard.dismiss();

        // Take user back to the PrivateNotesView page
        Navigation.goBack(ROUTES.HOME);
    };
``` 
### What alternative solutions did you explore? (Optional)

N/A

**Comment by saranshbalyan-1234** [comment] 2023-09-27 18:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In task description data is not trimmed
### What is the root cause of that problem?
While saving task description we are not trimming the description here.
https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/TaskDescriptionPage.js#L46-L53
and 
https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/NewTaskDescriptionPage.js#L64-L67
### What changes do you think we should make in order to solve the problem?
We need to trim the data before saving like this in TaskDescriptionPage
```javascript
  const submit = useCallback(
        (values) => {
            // Set the description of the report in the store and then call Task.editTaskReport
            // to update the description of the report on the server
             const editedDescription = parser.replace( values.description.trim());
            Task.editTaskAndNavigate(props.report, props.session.accountID, {description: editedDescription});
        },
        [props],
    );
``` 
and  in NewTaskDescriptionPage
```javascript
   const onSubmit = (values) => {
        const editedDescription = parser.replace( values.description.trim());
        Task.setDescriptionValue(editedDescription);
        Navigation.goBack(ROUTES.NEW_TASK);
    };
``` 
### What alternative solutions did you explore? (Optional)

N/A

**Comment by yh-0218** [comment] 2023-09-28 11:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency bug - Assign Task - Task description does not remove empty quotes
### What is the root cause of that problem?
Because we save origin description (user input).
Ex. `> Test \n >`
We need to update this to `> Test` before we save using `ExpensiMark`
https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/TaskDescriptionPage.js#L46-L53
and 
https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/NewTaskDescriptionPage.js#L64-L67
### What changes do you think we should make in order to solve the problem?
For `TaskDescriptionPage`, we need save `updatedDescription` instead of `values.description`.
```
            const parser = new ExpensiMark();
            const editedDescription = parser.replace(values.description.trim());
            const updatedDescription = parser.htmlToMarkdown(editedDescription);
            Task.editTaskAndNavigate(props.report, props.session.accountID, {description: updatedDescription});
```
For `NewTaskDescriptionPage`, we need save `updatedDescription` instead of `values.taskDescription`.
```
            const parser = new ExpensiMark();
            const editedDescription = parser.replace(values.taskDescription.trim());
            const updatedDescription = parser.htmlToMarkdown(editedDescription);
            Task.setDescriptionValue(updatedDescription); 
            Navigation.goBack(ROUTES.NEW_TASK); 
```
### What alternative solutions did you explore? (Optional)

**Comment by yurakurets** [comment] 2023-09-28 12:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Description text is saving just as plain text, while it can be displayed as markdown.

### What is the root cause of that problem?

There are 3 steps where it happens:

1. When user starts create task

https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/NewTaskDetailsPage.js#L64-L70

2. On the second step of creating

https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/TaskDescriptionPage.js#L46-L53

3. When user edits task description

https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/TaskDescriptionPage.js#L45-L54

### What changes do you think we should make in order to solve the problem?

We have to parse description field on each of these fields via ExpensiMark:

1. 
```
function onSubmit(values) {
        const parser = new ExpensiMark();
        const markdownDescription = parser.htmlToMarkdown(parser.replace(values.taskDescription.trim()))
        Task.setDetailsValue(values.taskTitle, markdownDescription);
        Navigation.navigate(ROUTES.NEW_TASK);
    }
```
2. 
```
const onSubmit = (values) => {
        const parser = new ExpensiMark();
        const markdownDescription = parser.htmlToMarkdown(parser.replace(values.taskDescription.trim()))
        Task.setDescriptionValue(markdownDescription);
        Navigation.goBack(ROUTES.NEW_TASK);
    };
```
3.
```
    const submit = useCallback(
        (values) => {
            const parser = new ExpensiMark();
            const markdownDescription = parser.htmlToMarkdown(parser.replace(values.description.trim()))
            // Set the description of the report in the store and then call Task.editTaskReport
            // to update the description of the report on the server
            Task.editTaskAndNavigate(props.report, props.session.accountID, {description: markdownDescription});
        },
        [props],
    );
```    

Last thing to take into account is state of NewTaskDetailsPage.js `const [taskDescription, setTaskDescription] = useState(props.task.description || '');`, because there is an option to go back to this screen and then user will be able to see old state with empty quotes. In order to fix it we should update state on focus, currently it's syncing in useEffect

https://github.com/Expensify/App/blob/f596e350faf8a914f053f1b5abeb469b00b17af1/src/pages/tasks/NewTaskDetailsPage.js#L44-L48

```
    useEffect(() => {
        setTaskTitle(props.task.title);
    }, [props.task]);

    useFocusEffect(useCallback(() => {
        setTaskDescription(props.task.description || '');
    }, [props.task.description]))
```    
   

https://github.com/Expensify/App/assets/26321483/534657eb-2049-4691-8018-3358f97694e1



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by yurakurets** [comment] 2023-09-28 12:55
Contributor details
Your Expensify account email: yura.kurets1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013589ef6319817fdf

**Comment by DylanDylann** [comment] 2023-09-28 13:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Inconsistency bug: Task description does not remove empty quotes (works fine in private notes)

### What is the root cause of that problem?
- Currently, with the description field, we are saving the input text directly: https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/pages/tasks/NewTaskDescriptionPage.js#L64-L67
- But for other logic like private notes, we will convert the user`s input to HTML and then save:
https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/pages/PrivateNotes/PrivateNotesEditPage.js#L89-L96

- There is no issue when we display these to content (description or private notes).
- But when editing, with the description, it uses the description that has been saved before as a default value. So if the user types:
```
> Hello
>
>
```
when creating a task, it still displays this text in the editing input, which lead to the bug.
- As I mentioned above, private notes save the HTML content, and when editing, it will convert this HTML content to raw text content, so it will set the default value as "> Hello", the remaining sections are removed.
https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/pages/PrivateNotes/PrivateNotesEditPage.js#L66
### What changes do you think we should make in order to solve the problem?
- We can handle the logic that saves the description as we did with private note: Convert the user input to html and then saves it. When editing, convert the saved html to raw text html and set as the default value:
- Firstly, update the onSubmit function:
https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/pages/tasks/NewTaskDescriptionPage.js#L64-L67
to 
```
    const onSubmit = (values) => {
        const parser = new ExpensiMark();
        const parsedTaskDescription = parser.replace(values.taskDescription);
        Task.setDescriptionValue(parsedTaskDescription);
        Navigation.goBack(ROUTES.NEW_TASK);
    };
```
- Secondly, add to 
https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/pages/tasks/NewTaskPage.js#L172-L180 to display description properly
- Then update https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/pages/tasks/NewTaskDescriptionPage.js#L94
to ``` defaultValue={parser.htmlToMarkdown(props.task.description)}```

### What alternative solutions did you explore? (Optional)
- NA

### Result

[Screencast from 28-09-2023 20:04:02.webm](https://github.com/Expensify/App/assets/141406735/ecd01dda-a0cb-403a-b9f8-c0d5681001e6)

**Comment by garrettmknight** [comment] 2023-10-03 17:08
Reproduced. @robertKozik can you take a look at these proposals?

**Comment by robertKozik** [comment] 2023-10-03 21:26
Hi all! Thank you for your proposals! I think we should go with the @DylanDylann proposal as it represents the most complete solution to unify the behaviour with the private notes approach. Other proposals are trying to parse both ways the description, which is in my opinion redundant and resource-consuming operation while saving the value.

Selected Proposal: https://github.com/Expensify/App/issues/28342#issuecomment-1739127073

🎀 👀 🎀 C+ reviewed

**Comment by iwiznia** [comment] 2023-10-04 10:31
I don't understand the bug, to me the current behavior is correct. Yes, it is not the same as in other places, but that's not a bug on itself. Are the users prevented from doing an action? Is something actually broken?
I think we should close this. @garrettmknight what are your thoughts here for accepting this as a bug?

**Comment by DylanDylann** [comment] 2023-10-04 11:30
@iwiznia I think this logic should be the same throughout the app so users are not confused. Additionally, if the logic is the same, we can create the util function to display, save, ... this type of input content and reuse it in the future

**Comment by garrettmknight** [comment] 2023-10-05 19:10
I'd agree that this is a clear inconsistency in how the two text areas work and without any reasoning for one to work differently (i.e. why is the text area in a task not removing erroneous pieces when the text composer?). It's a question of standardizing where the behavior should be the same, not whether the app is broken outright.

**Comment by DylanDylann** [comment] 2023-10-05 22:21
@garrettmknight Currently, these are a few components that will remove all the redundant ">":
1. Message composer
2. Private notes

**Comment by iwiznia** [comment] 2023-10-09 12:44
ok, assigned then

**Comment by DylanDylann** [comment] 2023-10-11 07:39
@garrettmknight Currently, we are having an issue related to the description in android native: It displays as 
```
> Hell
>
>
```

![image](https://github.com/Expensify/App/assets/141406735/6435efe0-0b62-4ec0-bc14-5f0696f2ca78)

rather than the proper HTML format
So should we create a separate issue?

**Comment by garrettmknight** [comment] 2023-10-11 17:53
Interesting - so Android isn't handling markdown. Is that a different way to describe the issue?

**Comment by DylanDylann** [comment] 2023-10-11 23:06
@garrettmknight 
> Android isn't handling markdown

I don't think so. We still can do as we did with the private notes, but it led to the other bug here https://github.com/Expensify/App/pull/29144#issuecomment-1756104373

**Comment by DylanDylann** [comment] 2023-10-12 17:26
> So I think we should create another issue to fix the issue "Android isn't handling markdown"

@garrettmknight please help confirm this one when you have a change. Many thanks

**Comment by DylanDylann** [comment] 2023-10-16 07:59
@garrettmknight friendly BUMP - please help confirm this one https://github.com/Expensify/App/issues/28342#issuecomment-1758665987

**Comment by garrettmknight** [comment] 2023-10-18 16:54
Sorry for the wait - If "Android isn't handling markdown" is the actual root cause, why don't we fix that and that will fix all these issues?

**Comment by DylanDylann** [comment] 2023-10-18 16:58
@garrettmknight  No. "Android isn't handling markdown" is another bug, that we have encountered in staging. The issue https://github.com/Expensify/App/issues/28342 is just: "Task description does not remove empty quotes" and has the difference root cause that I mentioned in my proposal

**Comment by DylanDylann** [comment] 2023-10-18 17:01
"Android isn't handling markdown" is related to the ```MenuItemWithTopDescription``` component, "Task description does not remove empty quotes" is related to ```TextInput``` component

**Comment by garrettmknight** [comment] 2023-10-18 20:25
Got it - feel free to propose the other bug in #expensify-bugs for Applause to vet - let's stick to the focus of this bug here.

**Comment by DylanDylann** [comment] 2023-10-19 12:53
@garrettmknight We need to confirm: 
- In my [original proposal](https://github.com/Expensify/App/issues/28342#issuecomment-1739127073), I let BE store the HTML, not mark down like the private notes logic.
  But when implementing the PR, I found out that if we let BE store the HTML, for example, 
```<blockscope>Hello <br/> 123</blockscope>```, it just stores as "Hello123". 
- So my [current implementation](https://github.com/Expensify/App/pull/29144) is: when submitting the description to BE, I keep using the original logic (let BE save the mark down string) rather than convert mark down to HTML.
- But @iwiznia thing that we need an additional fix from the BE side to store description as the html like others logic (for example, private note)
- So what do you think? (Should we follow my [current implementation ](https://github.com/Expensify/App/pull/29144) or request an additional fix from the BE side? )

**Comment by garrettmknight** [comment] 2023-10-24 11:07
Just catching up here - for consistency, I think we should aim to store these all the same (similar to private notes) and that sounds like it's going to require a BE change. @iwiznia do you agree?

**Comment by iwiznia** [comment] 2023-10-24 14:07
Yeah

**Comment by DylanDylann** [comment] 2023-10-24 14:11
I think do not need to update my proposal, just need to hold this issue until the BE side fixes the issue

**Comment by iwiznia** [comment] 2023-10-24 14:13
I think your proposal would not be needed at all if we change the backend, no?

**Comment by DylanDylann** [comment] 2023-10-24 14:15
No. We still need the FE change because as I mentioned in my proposal

> Currently, with the description field, we are saving the input text directly

**Comment by DylanDylann** [comment] 2023-10-26 02:59
@garrettmknight should we mark this issue as HOLD for BE change?

**Comment by garrettmknight** [comment] 2023-11-02 10:06
@iwiznia are you going to complete the backend change?

**Comment by iwiznia** [comment] 2023-11-02 16:48
Ah yeah, I ned to change that, need to look where it is exactly that I need to update it...
@DylanDylann can you confirm what API commands need updating? Is it `CreateTask` and `EditTask`?

But also, I am looking at the backend code and the `UpdateReportPrivateNote` API command is doing nothing with the passed note, same as `CreateTask` and `EditTask`....

**Comment by DylanDylann** [comment] 2023-11-02 17:06
@iwiznia Before, I found out that if we let BE store the HTML, for example, 
```<blockscope>Hello <br/> 123</blockscope>```, it just stores as "Hello123". 

Will re-check it today if it still appear

**Comment by DylanDylann** [comment] 2023-11-02 20:28
@iwiznia I just checked and the issue still appear:
1. When calling ```UpdateReportPrivateNote```, sending ```<blockquote>Hello</blockquote>``` will return ```<blockquote>Hello</blockquote>``` by BE (expected)
2. When calling ```EditTask```, sending ```<blockquote>Hello</blockquote>``` will return ```Hello``` by BE (unexpected)

**Comment by iwiznia** [comment] 2023-11-03 15:26
Sorry if I am being dense, but I am totally confused.
I am trying to save `<blockquote>Hello</blockquote>` there but I am getting an error:
<img width="369" alt="image" src="https://github.com/Expensify/App/assets/521248/a1b8b477-a6c4-4981-ab58-cf13d9746017">

**Comment by DylanDylann** [comment] 2023-11-03 15:29
@iwiznia yeah. It is our expected
![image](https://github.com/Expensify/App/assets/141406735/854fb28b-fdc6-467e-8d54-da32e9a44956)

**Comment by DylanDylann** [comment] 2023-11-03 15:46
@iwiznia 
- In my [original proposal](https://github.com/Expensify/App/issues/28342#issuecomment-1739127073), I will let BE store the HTML, not mark down like the private notes logic.
  But I found out that if we let BE store the HTML, for example, 
```<blockscope>Hello <br/> 123</blockscope>```, it just stores as "Hello123".

**Comment by iwiznia** [comment] 2023-11-03 15:48
Ahhhh, ok, can you push that out so I can test the backend changes with it... I am quite confused because I am not seeing anything in the code that would remove/change html.

**Comment by iwiznia** [comment] 2023-11-03 18:03
ok, I think I found why it is being removed... will need to do some tests on monday.
@DylanDylann how would we deploy this? If I deploy my change will things be broken till you deploy yours?

**Comment by DylanDylann** [comment] 2023-11-03 18:18
@iwiznia I am thinking about it. If you deploy your BE change the current app will be broken till I deploy FE change. Do you have any suggestions for this one @garrettmknight ?

**Comment by DylanDylann** [comment] 2023-11-08 00:22
@iwiznia Did you checke this https://github.com/Expensify/App/issues/28342#issuecomment-1792901470?

**Comment by iwiznia** [comment] 2023-11-10 20:57
That links to my own comment.
We need to figure out a way of deploying this without breaking it while one PR is deployed but not the other...

**Comment by DylanDylann** [comment] 2023-11-11 01:07
@garrettmknight do you have any suggestion for this one? https://github.com/Expensify/App/issues/28342#issuecomment-1806421725

**Comment by garrettmknight** [comment] 2023-11-13 15:25
@iwiznia I think he was referring to this part of your comment:
>ok, I think I found why it is being removed... will need to do some tests on monday.

**Comment by DylanDylann** [comment] 2023-11-14 14:54
@iwiznia Based on the discussion in slack channel, should we consider using my suggestion before? https://github.com/Expensify/App/pull/29144#issuecomment-1754417578

**Comment by iwiznia** [comment] 2023-11-14 17:37
Huh? If we deploy your change before the backend change is deployed, things will also be broken, no?

**Comment by DylanDylann** [comment] 2023-11-14 17:39
No. I mean that we do not need the BE change

**Comment by DylanDylann** [comment] 2023-11-15 02:30
@iwiznia Yeah, C+ has reviewed and approved this solution before

**Comment by iwiznia** [comment] 2023-11-15 20:04
Ah ok, if it does all that, then let's do it

**Comment by DylanDylann** [comment] 2023-11-16 02:41
@iwiznia yeah. I will update the PR and ping you review it

**Comment by garrettmknight** [comment] 2023-11-30 20:59
@robertKozik can you complete the checklist when you get a chance?

**Closed** 2023-12-11 19:15 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
