### ISSUE TITLE
[$500] Chat - New distance expense report does not remain at the bottom of the chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32827] opened 2023-12-11 16:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Interna l Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be a member of a workspace and have a previously created expense report on chat.
1. Go to the workspace chat where you have a previously created expense report.
2. Send some messages.
3. Send another distance expense report.

## Expected Result:
The new distance expense report should remain at the bottom of the chat.

## Actual Result:
The new distance expense report remains at the bottom of the chat for a while, but then jumps where the previously created expense was.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/320612e8-f0cb-493a-971a-f008942be793

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d93e87a2f59a556</li>
        <li>Upwork Job ID: 1734242458470187008</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28059371</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-12-11 16:51
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The root cause is this line in MoneyRequestSelectorPage.js.

```
if (prevSelectedTab === props.selectedTab) {
            return;
        }
```
### What changes do you think we should make in order to solve the problem?
If we delete this line, it will work.

**Comment by RAnis2017** [comment] 2023-12-12 00:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem to solve is related to the positioning of a new distance expense report within a workspace chat when there's an existing one as well. 
Specifically, when a user sends multiple messages and then creates a new distance expense report, the expected behavior is for the new report to remain at the bottom of the chat. 
However, the actual result is that, after a while, the new distance expense report jumps to a different position in the chat, specifically where the previously created expense report was located. 

### What is the root cause of that problem?

The root cause seems to be related to a piece of code that was adjusted 2 months back. In it, an older functionality is bypassed which I believe is necessary for an optimistic update for a distance report.

Commit # 1: [Create distance requests](https://github.com/Expensify/App/commit/6760c12917c72823626ca43ba50df1c1fa93696b)

[Commit # 1 IOU.js](https://github.com/Expensify/App/commit/6760c12917c72823626ca43ba50df1c1fa93696b#diff-17f969ae17c2a0f476494263758dbe0a535432f496b805345925e648d605915c)

[IOU.js Main Branch](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.js#L741)

```diff
// had an additional param @param {String} [transactionID]. Removed in above commit # 1.

function createDistanceRequest(
report, 
participant, 
comment,
- transactionID, 
created, 
category, 
tag, 
amount, 
currency, 
merchant, 
billable) {
```

Additionally, the `function getMoneyRequestInformation` is passed `undefined`.

This effects this code block further down the pipeline.
[IOU.js Main Branch Line 634 - 640](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.js#L634-L640)


```
    const existingTransaction = existingTransactionID && TransactionUtils.getTransaction(existingTransactionID);
    if (existingTransaction) {
        optimisticTransaction = {
            ...optimisticTransaction,
            ...existingTransaction,
        };
    }
```

### What changes do you think we should make in order to solve the problem?

Passing the required transactionID of any existing distance report should resolve the report jumping problem. Seems like an intended behaviour to create an optimistic transaction and show it as the newest.

createDistanceRequest is still passed a transactionID in one of the other components that seems to be unused MoneyRequestConfirmPage.

And in-case of a request failure it will show a failure message (with try again message) below the Distance Report without the jump and on a page or chat refresh we won't see the failed distance report again.

I've tried this fix and it is working for me in dev.

### What alternative solutions did you explore? (Optional)

**Comment by RAnis2017** [comment] 2023-12-12 00:37
Contributor details
Your Expensify account email: razaanis123@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f30e5c4501c57ad1

**Comment by mananjadhav** [comment] 2023-12-12 04:35
@adelekennedy I am working on limit capacity, can you please reassign this?

**Comment by adelekennedy** [comment] 2023-12-14 13:39
asked in Slack

**Comment by situchan** [comment] 2023-12-14 14:02
Thanks for the proposals everyone. Please update proposals based on latest codebase.
`MoneyRequestSelectorPage` component is deprecated. We now use `IOURequestStartPage`

**Comment by RAnis2017** [comment] 2023-12-14 15:49
> Contributor

The issue is not reproducible anymore on stage. It might have been fixed along with many other PRs.

I couldn't reproduce it on Prod or Stage, neither locally nor on deployed versions.

**Comment by situchan** [comment] 2023-12-14 16:15
@kbecciv would you mind retesting on staging?

**Comment by adelekennedy** [comment] 2023-12-18 12:54
@kbecciv any updates on testing here?

**Comment by adelekennedy** [comment] 2023-12-21 22:29
I also cannot reproduce this @situchan I think we should close

**Comment by situchan** [comment] 2023-12-25 11:11
@unicorndev-727 @cooldev900 any reason for linking this to `selectedTab`? This issue is never related to tab.

**Comment by situchan** [comment] 2024-01-03 17:15
Not overdue

**Comment by adelekennedy** [comment] 2024-01-05 21:02
@situchan we aren't getting any traction here, I also can't reproduce this on staging. Instead when I create multiple requests they bundle together which is expected behavior, I think we should close

**Comment by situchan** [comment] 2024-01-08 17:06
@adelekennedy let's close this for now.
I will bump here to reopen when I reproduced again.

**Closed** 2024-01-08 17:09 UTC
Labels: Engineering, Daily, Internal, Bug
