### ISSUE TITLE
[Wave Collect] [More Features] Update the Categories Add/Update methods in OldDot to enable the categories feature

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37370] opened 2024-02-27 23:28 UTC
Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.tlkva5w1tcas) of the design doc. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011880fac7ccc517ce</li>
        <li>Upwork Job ID: 1762620670869483520</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2024-02-28 23:01
PR merged

**Comment by alexpensify** [comment] 2024-03-01 02:01
Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by trjExpensify** [comment] 2024-03-05 23:28
Why didn't the issue close if it hit prod?

**Comment by luacmartins** [comment] 2024-03-06 02:15
Not sure, maybe because the PR was in Web-E and the issue is in App

**Comment by luacmartins** [comment] 2024-03-06 02:15
Closing this issue.

**Closed by luacmartins** 2024-03-06 02:15 UTC
Labels: Reviewing, Weekly, Internal, NewFeature

**Comment by alexpensify** [comment] 2024-03-06 14:47
I confirmed there is no contributor or C+ activity here that would trigger the payment process. Keeping this one closed.
