### ISSUE TITLE
[$500] Workspase - Open app banner not displayed in account settings pg when opened from WS settings pg

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37659] opened 2024-03-02 16:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** kiatest.78+mass@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Tap Profile option (top right corner) to go to account settings page
3. Observe Open app banner displayed
4. Go back to LHN
5. Tap bottom settings icon
6. Select Workspaces >> any WS to go to settings page
7. Tap on profile icon (avatar icon next to search bar)

## Expected Result:
Open app banner should be displayed in account settings page when accessed from WS settings page

## Actual Result:
Open app banner not displayed in account settings page when opened from WS settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/70b3c73a-a192-47cc-b1cc-430be07a2e63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af66a337e6b92621</li>
        <li>Upwork Job ID: 1764745823168827392</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2024-03-04 20:12
This feels related to #vip-vsb. I'm going to add to that project as a low priority issue.

**Comment by sakluger** [comment] 2024-03-04 20:13
I think this can be worked on externally, let me know if it needs to be made internal.

**Comment by godofoutcasts94** [comment] 2024-03-04 20:15
@sakluger I think the device should be mweb for both mac and ios. I can't see the same behaviour in mac chrome.

**Comment by sakluger** [comment] 2024-03-08 17:06
Still waiting for proposals.

@godofoutcasts94 thank you for clarifying, I think you're correct about the platform and I've updated the bug report. Do you have a proposal you'd like to share for how to fix this issue?

**Comment by godofoutcasts94** [comment] 2024-03-08 17:10
I will look into it now

**Comment by badeggg** [comment] 2024-03-09 11:47
The banner really looks like an iOS [small app banner](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners), but I can not find a meta tag like `<meta name="apple-itunes-app" content="app-id=myAppStoreID, app-argument=myURL">`, neither in the final html nor in the source code.

**Comment by godofoutcasts94** [comment] 2024-03-09 11:56
I am unable to reproduce it @sakluger

**Comment by badeggg** [comment] 2024-03-09 12:00
I believe the 'open app banner' only appears on safari on iOS. I reproduced the bug few days ago.

**Comment by nebiyuelias1** [comment] 2024-03-09 14:58
As @badeggg said, I don't see the meta tag inside the codebase or maybe some third party library is used for this. I'm not sure but I don't see the banner on iOS.

**Comment by sakluger** [comment] 2024-03-11 16:33
I reviewed the initial bug report again and changed my mind - I don't think this issue is worth solving at this time. It's such a limited issue, and I don't think user experience is negatively impacted because they can't switch from mWeb to the app in this one narrow use case. For that reason, I'm closing the issue.

**Closed by sakluger** 2024-03-11 16:33 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
