### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Android - Home - Time and other elements in phone header is not visible in light mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33674] opened 2023-12-27 21:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition open app in light mode
1. Launch app
2. Note header elements like phone time etc.,

## Expected Result:
Time and other elements in phone header must be visible in light mode

## Actual Result:
Time and other elements in phone header is not visible in light mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/eabdc99b-a335-490e-9ba2-5fc6ea85fbdb)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d884bdaeefe025ea</li>
        <li>Upwork Job ID: 1740123637523148800</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28080054</li>
<li>tienifr | Contributor | 28080055</li>
</ul></li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-12-29 17:26
Couple of proposals ready for review @jjcoffee - thank you!

**Comment by jjcoffee** [comment] 2024-01-02 14:49
@rayane-djouah seems to have the incorrect root cause as `dark-content` is the correct style to have here (per [the docs](https://reactnative.dev/docs/statusbar#statusbarstyle) this results in `Light background, dark texts and icons`).

@tienifr's [proposal](https://github.com/Expensify/App/issues/33674#issuecomment-1870717852) makes the most sense to me. I'm unsure if there would be any negative effects of initialising the status bar state to `undefined`, but we can test and deal with that on the PR.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by situchan** [comment] 2024-01-02 21:08
Dupe of https://github.com/Expensify/App/issues/33309
cc: @grgia @chrispader

**Comment by grgia** [comment] 2024-01-02 22:19
@madmax330 mind if I take this one?

**Comment by grgia** [comment] 2024-01-02 23:02
@tienifr does your proposal fix it for both light mode and dark (https://github.com/Expensify/App/issues/33309)

**Comment by chrispader** [comment] 2024-01-03 21:40
> ### What is the root cause of that problem?
> we are setting an incorrect status bar style here:

@rayane-djouah in the light theme `CONST.STATUS_BAR_STYLE.DARK_CONTENT` is correct. So this proposal is not valid

**Comment by chrispader** [comment] 2024-01-03 21:45
> ### What changes do you think we should make in order to solve the problem?
> We can simply initiate the status bar state to `undefined` [here](https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/components/CustomStatusBarAndBackground/index.tsx#L18) instead of initialize it with the theme current status bar.
> 
> ```
> const [statusBarStyle, setStatusBarStyle] = useState();
> ```
> 
> This will make sure initially when no status bar style is set, [this](https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/components/CustomStatusBarAndBackground/index.tsx#L61) will be evaluated to false and the status bar style will be set correctly.
> 
> Or in an `useEffect`, set the initial colors (same as initial value of `statusBarStyle` state) of the status bar by `updateStatusBarAppearance`, to make sure when we say, in the state, initial color of statusBar is something, it is correctly initialized like that.

@grgia i can confirm that this proposal by @tienifr is the way to go.

I would both set the initial value `statusBarStyle` to `undefined` and add a `useEffect` like this:

```js
useEffect(() => {
    if (statusBarStyle == null) {
        return;
    }

    updateStatusBarStyle();
}, [statusBarStyle, updateStatusBarStyle]);
```

This way, the effect will only be triggered after the first render and anytime (for whatever reason) the `statusBarStyle` might be undefined/null again.

**Comment by bfitzexpensify** [comment] 2024-01-08 13:12
@tienifr status of the PR?

**Comment by bfitzexpensify** [comment] 2024-01-10 19:09
PR is being worked on

**Comment by bfitzexpensify** [comment] 2024-01-11 17:31
I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.

- PR is currently being worked on

**Comment by JmillsExpensify** [comment] 2024-01-14 09:17
I'm not seeing a linked PR for this issue. Is a fix still being worked on?

**Comment by jjcoffee** [comment] 2024-01-24 11:01
Apologies this one fell off my radar somehow, it's back on my list!

**Comment by jjcoffee** [comment] 2024-01-25 14:21
Reviewing now!

**Comment by jjcoffee** [comment] 2024-01-25 14:48
PR reviewed, @tienifr just needs to work on a tweak.

**Comment by bfitzexpensify** [comment] 2024-02-07 06:36
How's this one going @tienifr?

**Comment by bfitzexpensify** [comment] 2024-02-21 07:07
Bump on this one @tienifr - how are the performance tests going?

**Comment by bfitzexpensify** [comment] 2024-03-06 05:37
Switching to Daily so that I action this when payment is due tomorrow

**Comment by bfitzexpensify** [comment] 2024-03-06 23:32
Payments all done - please complete the BZ checklist when you get a moment @jjcoffee - thank you!

**Comment by jjcoffee** [comment] 2024-03-07 09:54
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32672
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32672#issuecomment-1983134747
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Set app in light mode
2. Reopen app
3. Verify that the status bar renders correctly with the appropriate text colour for the theme
4. Sign out and verify 3
6. Sign in and verify 3
7. Repeat all steps with dark mode
8. Change theme from another device
9. Verify theme and status bar are updated accordingly

Do we agree 👍 or 👎

**Comment by bfitzexpensify** [comment] 2024-03-08 03:52
Looks good to me - proposed via https://github.com/Expensify/Expensify/issues/376686. Let's close this out - thanks everyone!

**Closed by bfitzexpensify** 2024-03-08 03:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
