### ISSUE TITLE
[HOLD for payment 2024-04-05] Web - Expense report - Approve button not disabled if selected before enabling Self-approval

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38889] opened 2024-03-23 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37348
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: user created a collect policy in OD, added a bank account, and set Direct reimbursements
1. Log in to OD as the admin of the collect policy
2. Navigate to the collect policy settings > Members
3. Enable the Prevent self-approval toggle
4. Log in to ND as the admin
5. Open the workspace chat and create a manual request
6. Disable the Prevent self-approval in OD
7. Refresh the page or open the report and submit the report in ND
8. Select Approve from the drop-down but do not click on it
9. Enable the the Prevent self-approval toggle in OD

## Expected Result:
The approve button is disabled both on the report preview and in the expense report

## Actual Result:
The approve button is not disabled if it was selected before enabling Self-approval. Clicking on the Approve button results in skeleton loading

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5d12077f-0107-49df-b538-7b4286dc20ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-23 21:47
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-03-23 21:52
We think that this bug might be related to #wave-collect - Release 1

**Comment by luacmartins** [comment] 2024-03-25 15:27
Seems to have come from https://github.com/Expensify/App/pull/37348

**Comment by francoisl** [comment] 2024-03-25 17:42
Guessing it's not a blocker since collect policies are not available to users on NewDot yet.

@barros001 @alitoshmatov - looks like it might be coming from https://github.com/Expensify/App/pull/37348 indeed – any idea on how we could fix this?

**Comment by francoisl** [comment] 2024-04-19 02:14
All done here, fix is on production. The regression was fixed by the author of the PR that originally caused it, so I believe no payment is needed, but let me know if that's wrong.

**Closed by francoisl** 2024-04-19 02:14 UTC
Labels: Engineering, Weekly, Overdue, Awaiting Payment
