### ISSUE TITLE
[HOLD for payment 2024-08-02] [Payment card / Subscription] - Subcriptions leads to not here page after Control workspace is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45720] opened 2024-07-18 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new account (to have an account with no trial)
3. Create a workspace
4. Go to More features
5. Toggle on Report fields
6. Click Upgrade to upgrade to Control
7. Go back to Account settings
8. Click Subscriptions
9. Note that the page opens without issue
10. Now delete the Control workspace
11. Go back to Account settings
12. Click Subscriptions

## Expected Result:
Subcriptions tab should disappear if it is not available when there is no Control workspace

## Actual Result:
Subcriptions leads to not here page after the Control workspace is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/941b1746-fe8f-46a4-bb94-87214394253c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-07-18 20:21
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-07-18 20:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Subcriptions leads to not here page after Control workspace is deleted
### What is the root cause of that problem?
We are checking if there is `privateSubscription` here before adding subscription menu item to `workspaceMenuItemsData`. When a workspace is deleted, `privateSubscription` have `autoRenewLastChangedDate` , `pendingFields` and `type` properties. Therefore the it is considered to be truthy value and `subscription` item will be added to `workspaceMenuItemsData`.
https://github.com/Expensify/App/blob/8e9c6811ac8dc2a9335bf0ceed9dffee661ed0bc/src/pages/settings/InitialSettingsPage.tsx#L206-L208
### What changes do you think we should make in order to solve the problem?
* We should use `useSubscriptionPlan();` to check if the user has active subscription (collect or control subscription)
```javascript
const subscriptionPlan = useSubscriptionPlan();
```
* Don't add `subscription` item to `workspaceMenuItemsData` if `subscriptionPlan === null`
```javascript
  if (subscriptionPlan) {
            items.splice(1, 0, {
                translationKey: 'allSettingsScreen.subscription',
```
Note: we will add subscriptionPlan to the useMemo dependency. 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by OfstadC** [comment] 2024-07-22 20:21
Looking at this now

**Comment by OfstadC** [comment] 2024-07-22 20:34
I don't have the option for Report Fields 🤔 so I can't reproduce.

**Comment by etCoderDysto** [comment] 2024-07-22 20:37
> I don't have the option for Report Fields 🤔 so I can't reproduce. 

You have to use expensifail account. The feature is under beta. That is why you are seeing the feature.

**Comment by OfstadC** [comment] 2024-07-23 16:05
I don't get the same result 
![2024-07-23_11-02-52 (1)](https://github.com/user-attachments/assets/0c8c4814-f36e-4700-a95b-43e50bc52c2e)

**Comment by kavimuru** [comment] 2024-07-23 17:05
@OfstadC Still reproducible by the tester

https://github.com/user-attachments/assets/ed7bde71-3c8f-4043-8911-1acdcaddbe9a

**Comment by OfstadC** [comment] 2024-07-23 17:35
Thanks @kavimuru !

**Comment by narefyev91** [comment] 2024-07-24 11:21
Please assign this to me - will pick this up

**Comment by trjExpensify** [comment] 2024-07-24 11:25
Done!

**Comment by blimpich** [comment] 2024-07-24 17:19
Assigning @rojiphil since they are the C+ reviewing the PR

**Comment by OfstadC** [comment] 2024-07-30 12:07
@rojiphil Could you please complete the checklist ?  Thank you! 😃

**Comment by OfstadC** [comment] 2024-07-31 14:37
I'll be OoO on 8/2 so adding another BZ team member here to issue payment on time

**Comment by OfstadC** [comment] 2024-07-31 14:38
@adelekennedy We're waiting on @rojiphil to complete BZ checklist - and then we need to issue payment on 8/2. I'll be fully offline on Friday so looping you in so we can pay this on time. Thank youuuu ❤️

**Comment by adelekennedy** [comment] 2024-08-02 19:44
Sent @rojiphil offer via Upwork

**Comment by rojiphil** [comment] 2024-08-03 16:57
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/45089)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/45089/files#r1702846991)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Since the changes are related to display/hide of subscription menu in LHN which is common usage, we can add a regression test.
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Test Steps
	1	Create a new account (to have an account with no trial)
	2	Create a workspace
	3	Go to More features
	4	Toggle on Report fields
	5	Click Upgrade to upgrade to Control
	6	Go back to Account settings
	7	Click Subscriptions
	8	Change subscription to "Pay-per-use"
	9	Note that the page opens without issue
	10	Now delete the Control workspace
	11	Go back to Account settings
	12	Verify that subscription is not shown anymore

**Comment by rojiphil** [comment] 2024-08-03 17:02
@adelekennedy @OfstadC Completed BZ Checklist and accepted offer too. Thanks.

**Comment by adelekennedy** [comment] 2024-08-05 22:55
Payment made @rojiphil!

**Comment by adelekennedy** [comment] 2024-08-05 23:01
https://github.com/Expensify/Expensify/issues/418028

**Closed by adelekennedy** 2024-08-05 23:01 UTC
Labels: Daily, Awaiting Payment, Bug
