### ISSUE TITLE
[CHECKLIST?][$250] [Search v2.1] [App] Create Keyword filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46027] opened 2024-07-23 15:10 UTC
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the `Keyword` filter only!

cc @adamgrzybowski @Kicu @WojtekBoman

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff6d0b9a0f6c02fb</li>
        <li>Upwork Job ID: 1819041159147930925</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 103358660</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2024-07-24 00:48
Hi @luacmartins, did you want me to assign the tagged people?

**Comment by luacmartins** [comment] 2024-07-24 14:40
I think they need to comment on the issue before we can assign it to them

**Comment by jliexpensify** [comment] 2024-07-28 22:45
Oh yeah, of course ha!

**Comment by luacmartins** [comment] 2024-07-31 15:46
Trying to get this assigned

**Comment by SzymczakJ** [comment] 2024-08-01 10:17
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by 289Adam289** [comment] 2024-08-02 10:26
Hi! I'm from SWM and I'd like to take this issue from @SzymczakJ. Could you assign it to me?

**Comment by jliexpensify** [comment] 2024-08-02 10:31
Done, thanks @289Adam289!

**Comment by 289Adam289** [comment] 2024-08-02 12:15
@luacmartins What should keyword filter page look like? I assumed it should be similar to merchant filter but "Has keywords" description in docs implies that page should allow for multiple keywords to be entered.

**Comment by luacmartins** [comment] 2024-08-02 13:57
It should be a text input. Users can enter any value in it

**Comment by ikevin127** [comment] 2024-08-14 22:35
⚠️ Production deploy automation failed here -> this should be on **[HOLD for Payment 2024-08-20]** according to yesterday’s production deploy confirmed in https://github.com/Expensify/App/pull/46799#issuecomment-2289860166 and [deploy checklist](https://github.com/Expensify/App/issues/47219).

cc @luacmartins @jliexpensify

**Comment by ikevin127** [comment] 2024-08-15 00:39
@jliexpensify Thank you!
Do you mind adding the `Bug` label as well for auto-assigned BZ team member to handle payment once due ?

**Comment by jliexpensify** [comment] 2024-08-15 01:10
@ikevin127 - I am BZ!

**Comment by ikevin127** [comment] 2024-08-15 01:13
My bad, was looking for that `Bug` label without checking 🤦‍♂️

**Comment by jliexpensify** [comment] 2024-08-15 01:27
All good, usually that label is applied but since its a `NewFeature`, BZ gets assigned.

**Comment by ikevin127** [comment] 2024-08-20 05:21
cc @jliexpensify

**Comment by jliexpensify** [comment] 2024-08-20 05:40
Thanks for the bump, but It's still the 19th in the US, right? 😅 that's the timezone that we go off for payments

**Comment by jliexpensify** [comment] 2024-08-20 10:19
@ikevin127 any checklist needed here?

**Comment by ikevin127** [comment] 2024-08-20 17:49
Thanks for the payment 💯 
Regarding checklist / regression tests, I was told by @luacmartins in a few of the search v2.1 issues ([ref](https://github.com/Expensify/App/issues/46038#issuecomment-2283520258)) that, quote:

> No, we'll add it as part of the project wrap up

**Comment by luacmartins** [comment] 2024-08-20 19:55
Correct ^

**Comment by jliexpensify** [comment] 2024-08-21 01:41
Awesome, all good. Closing!

**Closed by jliexpensify** 2024-08-21 01:41 UTC
Labels: Reviewing, External, Weekly, NewFeature
