### ISSUE TITLE
[$500] Web - Browser back and custom back bottom lead to different screens

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26751] opened 2023-09-05 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Misspell chat room and search
3. Misspell the whole page (change .../r/...)
4. Click the browser back
5. Click the browser forward
5. Click on the custom back button

## Expected Result:
The both should lead to the same place

## Actual Result:
The lead to two different places

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/0bd1c256-20b2-4179-87c0-4957a81a487f

https://github.com/Expensify/App/assets/115492554/910d9a96-0f86-4477-8b4b-0c353c087f14

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kassahun-asefa

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692660622855199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01385ce21d173ba391</li>
        <li>Upwork Job ID: 1699404746983936000</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-09-06 12:59
I'm not sure but I think it's expected behavior.

**Comment by imranaalam** [comment] 2023-09-07 05:40
### Problem Statement:
When users perform a sequence of navigation actions in the application, using both the custom back button and the browser's back/forward buttons, they encounter inconsistent navigation outcomes. Specifically, the custom back button and the browser's back button can lead to different locations, causing confusion and potential navigation errors.

### Root Cause:
The application's custom `goBack` function had been updated to introduce a fallback mechanism. In scenarios where the user was at the first route in the navigator and a standard back action might not yield a logical previous route, the app was designed to navigate to a fallback route using the `REPLACE` action. This behavior diverged from the browser's standard back button, which relies on its internal navigation history, leading to the observed discrepancies.

### Proposed Solution:
Retain the fallback mechanism but modify its behavior to ensure consistency with the browser's back button. Instead of using the `REPLACE` action to navigate to the fallback route, simply navigate to the fallback route, adding it to the browser's history.

**Proposed Code:**
```javascript
function goBack(fallback = ROUTES.HOME) {
    if (!canNavigate('goBack')) {
        return;
    }

    if (!navigationRef.current.canGoBack()) {
        Log.hmmm('[Navigation] Unable to go back');
        navigate(fallback);
        return;
    }

    navigationRef.current.goBack();
}
```

**Pros:**
- Retains the safety of the fallback mechanism, ensuring users are directed to a meaningful location when a logical previous route doesn't exist.
- Provides consistency between the custom back button and the browser's back button.
- Simplified and more predictable behavior.

**Cons:**
- The fallback navigation is added to the browser's history, which might not always be desired in all scenarios.

### Alternative Solution:
Completely remove the fallback mechanism from the `goBack` function, making its behavior strictly adhere to the standard back action. This ensures maximum consistency with the browser's back button but loses the flexibility of the fallback.

**Alternative Code:**
```javascript
function goBack() {
    if (!canNavigate('goBack')) {
        return;
    }

    if (!navigationRef.current.canGoBack()) {
        Log.hmmm('[Navigation] Unable to go back');
        return;
    }

    navigationRef.current.goBack();
}
```

**Pros:**
- Maximum consistency with the browser's back button.
- Simplified behavior and easier maintenance.

**Cons:**
- Loses the safety net of the fallback mechanism, potentially leading users to undesired or error pages in edge cases.

**Comment by imranaalam** [comment] 2023-09-09 14:04
it need to be confirmed that is this a bug or desired behavior. it looks like a bug to me.

**Comment by laurenreidexpensify** [comment] 2023-09-12 10:04
confirmed this expected behaviour, am closing

**Closed by laurenreidexpensify** 2023-09-12 10:04 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
