### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Web -  LHN of parent does not update immediately after delete task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27948] opened 2023-09-21 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon and select assign task
3. Enter title and create task
4. Go to task thread and delete the task
5. Check the LHN of parent

## Expected Result:
Create task message should be not show

## Actual Result:
Create task message appears in LHN and removed after click go to parent report screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72. 9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0473594c-3414-4bd4-9d78-3e466d9db0c9

https://github.com/Expensify/App/assets/93399543/62751a45-d9b6-4621-ac27-c23407ea4b71

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695192340496669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment] 2023-09-21 14:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Once the task is closed, the parent report last message is not updated in LHN

### What is the root cause of that problem?
When canceling a task, we optimistically update the parent report:

https://github.com/Expensify/App/blob/76b691482af9c8d9d798e0f53991d60a90ebebd0/src/libs/actions/Task.js#L797-L804

We explicitly tell the `ReportActionsUtils.getLastVisibleMessage` to ignore the "Created task" action: `{[parentReportAction.reportActionID]: null}`

However, this `null` is ignored here:

https://github.com/Expensify/App/blob/f6efb269a587aa664ee2a94366bb9aeedcc4cae2/src/libs/ReportActionsUtils.js#L381-L387

### What changes do you think we should make in order to solve the problem?
If the actionsToMerge contains explicit `null`, we should set the corresponding `updatedActionsToMerge` key to `null` instead of using the spread operator:

```diff
    if (actionsToMerge && Object.keys(actionsToMerge).length !== 0) {
        Object.keys(actionsToMerge).forEach(
-           (actionToMergeID) => (updatedActionsToMerge[actionToMergeID] = {...allReportActions[reportID][actionToMergeID], ...actionsToMerge[actionToMergeID]}),
        );
+           (actionToMergeID) => (updatedActionsToMerge[actionToMergeID] = lodashIsNull(actionsToMerge[actionToMergeID]) ? null : {...allReportActions[reportID][actionToMergeID], ...actionsToMerge[actionToMergeID]}),
        );
    }
```


### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2023-09-21 16:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN of parent chat report does not get immediately updated after a Task is Cancelled.

### What is the root cause of that problem?

When we initiate task cancellation, we update the Parent Report action with the updated optimistic data for message using `optimisticReportActions` [here](https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Task.js#L767C1-L784C7). However, while computing the new last visible action message for the parent report using `getLastVisibleMessage` and `getLastVisibleAction` [here](https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Task.js#L802C1-L804C1), we are not passing the `optimisticReportActions` into the functions. Instead, we pass `{[parentReportAction.reportActionID]: null})` which is the root cause of the problem. 

### What changes do you think we should make in order to solve the problem?

To solve the problem, let us pass `optimisticReportActions` in the `getLastVisibleMessage` and `getLastVisibleAction` functions like this [here](https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Task.js#L802C1-L804C1)

```
                lastMessageText: ReportActionsUtils.getLastVisibleMessage(parentReport.reportID, optimisticReportActions).lastMessageText,
                lastVisibleActionCreated: ReportActionsUtils.getLastVisibleAction(parentReport.reportID, optimisticReportActions).created,
```

### Test Result

https://github.com/Expensify/App/assets/3004659/c5295533-07fa-4b28-8ad2-478bc020534f

### What alternative solutions did you explore? (Optional)

**Comment by sophiepintoraetz** [comment] 2023-09-22 02:10
Unassigning @JmillsExpensify as I'm the first one here.

**Comment by sophiepintoraetz** [comment] 2023-09-25 11:21
Just needing @ArekChr to review the proposals.

**Comment by kaushiktd** [comment] 2023-09-26 13:25
### Please re-state the problem that we are trying to solve in this issue.
When the task is closed, LHN of parent does not update immediately after delete task

### What is the root cause of that problem?
when computing the new last visible action message for the parent report using `ReportActionsUtils.getLastVisibleMessage` and `ReportActionsUtils.getLastVisibleAction`, we initially pass `{[parentReportAction.reportActionID]: null}` instead of the updated `optimisticReportActions` object. Because of this, the functions `getLastVisibleMessage` and `getLastVisibleAction` are not aware of the optimistic data you added to `optimisticReportActions`, and they compute the last visible action message based on outdated or incomplete data.

### What changes do you think we should make in order to solve the problem?
We can update the `optimisticReportActions` object in place, and then use it when updating the parent report. Here's an example of how you can do that:
https://github.com/Expensify/App/blob/main/src/libs/actions/Task.js#L767
```
const optimisticReportActions = {
    ...optimisticReportActions, // Copy the existing data
    [parentReportAction.reportActionID]: {
        pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
        previousMessage: parentReportAction.message,
        message: [
            {
                translationKey: '',
                type: 'COMMENT',
                html: '',
                text: '',
                isEdited: true,
                isDeletedParentAction: true,
            },
        ],
        errors: null,
        linkMetaData: [],
    },
};
```
https://github.com/Expensify/App/blob/main/src/libs/actions/Task.js#L801

```
value: {
    lastMessageText: ReportActionsUtils.getLastVisibleMessage(parentReport.reportID, optimisticReportActions).lastMessageText,
    lastVisibleActionCreated: ReportActionsUtils.getLastVisibleAction(parentReport.reportID, optimisticReportActions).created,
},
```

### Video:
https://drive.google.com/file/d/1pivJIL70oigokuROjifF6Q36afx76sPs/view?usp=sharing

**Comment by sophiepintoraetz** [comment] 2023-10-02 02:25
[bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1696213516989869) @ArekChr in slack

**Comment by ArekChr** [comment] 2023-10-02 13:01
The [solution](https://github.com/Expensify/App/issues/27948#issuecomment-1729884212) proposed by @rojiphil addresses the problem correctly. In the `shouldReportActionBeVisibleAsLastAction` function, we filter out messages with empty content in the HTML field using the `isDeletedAction` function. It's not necessary to filter out reports that are null. Using the syntax {[parentReportAction.reportActionID]: null} to set reports seems to be not correct.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by paultsimura** [comment] 2023-10-02 13:06
@ArekChr could you please elaborate a bit on why it is not correct, if it's already used in multiple places across the App?

**Comment by ArekChr** [comment] 2023-10-02 13:30
@paultsimura My decision was based on the current structure and simplicity of the code. We already have logic inside the `shouldReportActionBeVisibleAsLastAction` function that filters out deleted actions based on empty HTML content. That's why I opted for a more straightforward proposal.

**Comment by paultsimura** [comment] 2023-10-02 13:37
@ArekChr understandable. I would still recommend checking if this (potential) regression doesn't affect other places that use optimistic null values

**Comment by paultsimura** [comment] 2023-10-02 14:40
> @paultsimura Could you check if any regression exists when passing  {[parentReportAction.reportActionID]: null} in different places than tasks, which makes this bug in LHN while displaying the last messages?

Will update by tomorrow👌

**Comment by paultsimura** [comment] 2023-10-02 22:14
@ArekChr here's another identical bug that my proposal fixes: it happens when the IOU request (and report accordingly) is deleted offline.

Current (broken) flow:

https://github.com/Expensify/App/assets/12595293/18604d4d-3bc9-4507-893a-d5d2204648e3

The same flow fixed by my proposal:

https://github.com/Expensify/App/assets/12595293/e8b63d6e-2b0e-4211-808f-74ef28064c03

**Comment by rojiphil** [comment] 2023-10-03 02:26
@paultsimura 
Please have a look at [this code here](https://github.com/Expensify/App/blob/39fbde168427eff1e1b2b3158512557791dab118/src/libs/actions/Report.js#L1043C1-L1045C122). For `deleteReportComment`, we use a similar approach.
Then, why not here?
Or are you suggesting that we implement your proposal in `deleteReportComment` also?

**Comment by paultsimura** [comment] 2023-10-03 11:31
@rojiphil I'm just saying that with my solution, all three `deleteReportComment`, `cancelTask`, and `deleteMoneyRequest` work properly, while with the other suggested solution, the `deleteMoneyRequest` flow remains broken. I'm OK with leaving the `deleteReportComment` flow as it currently is.

I don't see any good reason to stop supporting the `actionsToMerge: {[actionID]: null}` as it has been in use since at least July 2023: https://github.com/Expensify/App/pull/19095.

We surely can deliver the local solution by replacing the `{[parentReportAction.reportActionID]: null}` with `optimisticReportActions` here:

https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Task.js#L802-L803

But there's a bigger elephant in the room and as for me, we shouldn't ignore it.

**Comment by rojiphil** [comment] 2023-10-03 12:49
> while with the other suggested solution, the `deleteMoneyRequest` flow remains broken

@paultsimura 
Now I understand what you are saying.
But, to be honest, I don’t think using null is the way to fix in `deleteMoneyRequest` [here](https://github.com/Expensify/App/blob/94002fbd83b96d7dd53598f88557f3c0550fcb37/src/libs/actions/IOU.js#L1557C1-L1559C1).
Depending on the context there, I think, we need to set updated report preview action correctly.
To me, it looks like a separate issue.

**Comment by rojiphil** [comment] 2023-10-05 04:50
@sophiepintoraetz 
Gentle bump to review C+ comment [here](https://github.com/Expensify/App/issues/27948#issuecomment-1742973614)

**Comment by sophiepintoraetz** [comment] 2023-10-05 05:10
@rojiphil - there's nothing for me to "review" as such, if the C+ has chosen the proposal, then the auto assignments should happen. What are you specifically asking?

**Comment by paultsimura** [comment] 2023-10-05 05:14
@sophiepintoraetz we're actually having an ongoing discussion here after @ArekChr's approval. Which, I believe, should be addressed before the final Contributor assignment.

**Comment by rojiphil** [comment] 2023-10-05 05:17
> @rojiphil - there's nothing for me to "review" as such, if the C+ has chosen the proposal, then the auto assignments should happen. What are you specifically asking?

@sophiepintoraetz 
Sorry. Since only two of you were assigned to the issue, I thought, it was a pending action from you.
I think, the auto assignment feature is the reason for stalemate here.

**Comment by rojiphil** [comment] 2023-10-05 05:19
> @sophiepintoraetz we're actually having an ongoing discussion here after @ArekChr's approval. Which, I believe, should be addressed before the final Contributor assignment. Also, isn't the final assignment triggered manually by an Engineer? 🤔

Yes. You are right. What I have noticed is that an internal engineer gets assigned who does the honours 😄

**Comment by rojiphil** [comment] 2023-10-05 05:26
@MelvinBot 
Please trigger the assignment of an internal engineer to take this forward.

**Comment by ArekChr** [comment] 2023-10-05 09:11
After investigation, I'm still sticking to passing optitimistinReportActions with empty content of HTML content, which is subsequently filtered out in the getLastVisibleMessage function. I’ve noticed there seem to be two different approaches in use, and the strategy for filtering out removed messages may not have been explicitly defined. I suggest we align the way of setting optimisticData to prevent future confusion. It is essential that passing optimisticReportActions provides more context from fields like isEdited, isDeletedParentAction, etc., for future use in getLastVisibleMessage.

**Comment by sophiepintoraetz** [comment] 2023-10-05 11:37
Going to hijack our engineering label to get @hayata-suenaga assigned (Hayata, it looks like our auto-assigner logic for bugs is [down)](https://expensify.slack.com/archives/C01SKUP7QR0/p1696504307133379). Can you please review the C+ proposal here?

@paultsimura - for your information, our C+ are vetted by us and we tend to trust their judgment. 95% of the time, the internal engineer will approve the C+'s choice - so to continue the discussion such choice, or to question it, is counter-productive. @ArekChr made their rationale so really the only person that would (unlikely) override that is an internal engineer.

**Comment by sophiepintoraetz** [comment] 2023-10-05 11:40
@puneetlath - I need some help babysitting this issue while i'm OOO till 17 Oct! So far, C+ has chosen the proposal but the auto-assigner bugged out and [just got](https://github.com/Expensify/App/issues/27948#issuecomment-1748711903) an internal engineer to review this. Seeing as it's a potential double-up, not sure if you want to take on the C+ proposal review as well or leave that to Hayata?

**Comment by paultsimura** [comment] 2023-10-05 11:45
@sophiepintoraetz my comment was posted before [this one](https://github.com/Expensify/App/issues/27948#issuecomment-1748448389) from C+, so I wanted to stress out that the discussion was still ongoing. Now that we got a final response from @ArekChr, I have no objection 🙂

**Comment by rojiphil** [comment] 2023-10-06 07:02
@ArekChr 
[PR](https://github.com/Expensify/App/pull/28980) is ready for review.

**Comment by ArekChr** [comment] 2023-10-11 09:34
- [x] Link to the PR: Couldn't identify PR. It seems to have been there since the beginning.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I'm not sure if there is a similar test, but we could add it.

Regression test proposal:

1. Login to NewDot on the web as user A.
2. Open a new chat with user B.
3. Send a test message to user B.
4. Assign a task to user B.
5. Cancel the task.
6. Verify in the sidebar links if the last message displayed is the test message, not the task message.
7. Repeat steps 1-6 with turned offline mode before canceling the task (step 5).

Do we agree :+1: or :-1:

**Comment by sophiepintoraetz** [comment] 2023-10-18 03:19
Offers sent - regression test created.

**Closed by sophiepintoraetz** 2023-10-18 03:19 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by gadhiyamanan** [comment] 2023-10-18 06:49
@sophiepintoraetz offer accepted
Cam you please approve the payment
