### ISSUE TITLE
[$500] Workspace - Green dot appears in employee's workspace chat when employee creates an expense request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32914] opened 2023-12-12 11:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-9
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition: User must be an employee of a Collect workspace created from OD.

1. Go to the workspace chat.
2. Tap + > Request money > Manual.
3. Create a manual request.
4. Note that green dot shows up in LHN.
5. Click on the expense preview.
6. Return to the main workspace chat.
7. Note that the green dot disappears.

## Expected Result:
In Step 3, after creating an expense request as employee, green dot should not appear in the workspace chat for employee in LHN because employee cannot pay the request.

## Actual Result:
In Step 3, after creating the request, green dot appears next to the workspace chat in LHN. It disappears after opening expense report and revisiting workspace chat in Step 6.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/69efd1d3-0c29-4dfd-a188-707d2a37d5d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cfcd497243f2823</li>
        <li>Upwork Job ID: 1734540517716250624</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2023-12-12 16:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Green dot appears in employee's workspace chat when employee creates an expense request
### What is the root cause of that problem?
There is not check if the  request owner is current user
### What changes do you think we should make in order to solve the problem?
Add condition if `optionOrReport.ownerAccountID` equals to current user account id and return false in this case in `requiresAttentionFromCurrentUser` function

### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment] 2023-12-15 21:05
Closing this as it's not associated with a VIP, Wave, or high priority item.

**Closed by slafortune** 2023-12-15 21:05 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
