### ISSUE TITLE
[$250] Invoices - Unable to send invoice after signup for new account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52672] opened 2024-11-16 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @wildan-m 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_open_source](https://expensify.slack.com/archives/C01GTK53T8Q/p1727076209941879)

## Action Performed:

1. Go to staging.new.expensify.com and signup for a new account (Choose manage my team expenses)
2. Go to workspace settings > More features
3. Enable Invoices
4. Go to FAB > Send invoice
5. Enter all the details
6. Send an invoice 

## Expected Result:
Invoice send without any error

## Actual Result:
Unexpected error sending this invoice. Please try again later.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (4)](https://github.com/user-attachments/assets/b4ba5f06-9950-423d-abc2-f95033436b42)

```
Throw ExpException - 29cccff02d52fe47471ac14a90a716b0 ~~ message: '404 Report not found.' exceptionMessage: 'Auth Get returned an error' exceptionFile: '/git/releases/expensify.com/b15f15e/lib/Auth.php' exceptionLine: '132' exceptionCode: '404'
Push_API - User attempted to subscribe to a private report channel they do not have access to. Blocking the subscription. ~~ reportID: '287245849178656'
```
```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "5d2f6fd0-4a44-4ed7-87a0-c717df2f25a7",
    "message": "Forbidden",
    "title": "",
    "data": [],
    "htmlMessage": "",
    "onyxData": [],
    "requestID": "8c7cbff929d77241-CGK"
}
{
    "reportID": "4206368647827279",
    "chatReportID": "1797028634694650",
    "policyID": "C7CA901E563754A3",
    "type": "invoice",
    "ownerAccountID": 18358661,
    "managerID": 428650280,
    "currency": "IDR",
    "reportName": " owes IDR 122.00",
    "stateNum": 1,
    "statusNum": 0,
    "total": 12200,
    "participants": {
        "18358661": {
            "notificationPreference": "hidden"
        }
    },
    "parentReportID": "1797028634694650",
    "lastVisibleActionCreated": "2024-09-23 18:55:33.845",
    "parentReportActionID": "8380821801235338966",
    "lastMessageText": "submitted IDR 122.00",
    "lastMessageHtml": "submitted IDR 122.00",
    "errorFields": {
        "createChat": {
            "1727117733847000": "Unexpected error creating this chat. Please try again later."
        }
    }
}
{
    "1589945205417922759": {
        "reportActionID": "1589945205417922759",
        "actionName": "CREATED",
        "pendingAction": "add",
        "actorAccountID": 18358661,
        "message": [
            {
                "type": "TEXT",
                "style": "strong",
                "text": "wildevemail+1@gmail.com"
            },
            {
                "type": "TEXT",
                "style": "normal",
                "text": " created this report"
            }
        ],
        "person": [
            {
                "type": "TEXT",
                "style": "strong",
                "text": "sdfgsdfg"
            }
        ],
        "automatic": false,
        "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_6.png",
        "created": "2024-09-23 18:55:33.846",
        "shouldShow": true
    },
    "8380821801235338966": {
        "reportActionID": "8380821801235338966",
        "reportID": "1797028634694650",
        "actionName": "REPORTPREVIEW",
        "pendingAction": "add",
        "originalMessage": {
            "linkedReportID": "4206368647827279"
        },
        "message": [
            {
                "html": " owes IDR 122.00",
                "text": " owes IDR 122.00",
                "isEdited": false,
                "type": "COMMENT"
            }
        ],
        "created": "2024-09-23 18:55:33.846",
        "accountID": 428650280,
        "actorAccountID": 428650280,
        "childReportID": "4206368647827279",
        "childMoneyRequestCount": 1,
        "childLastMoneyRequestComment": ""
    }
}
{
    "transactionID": "8106987597567990091",
    "amount": 12200,
    "currency": "IDR",
    "reportID": "4206368647827279",
    "comment": {
        "comment": ""
    },
    "merchant": "(none)",
    "created": "2024-09-24",
    "receipt": {},
    "filename": "",
    "category": "",
    "tag": "",
    "taxCode": "",
    "taxAmount": 0,
    "billable": false,
    "reimbursable": true,
    "errors": {
        "1727117733847000": "Unexpected error sending this invoice. Please try again later."
    },
    "pendingFields": {}
}
```

![Snip - (1) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/08fa38a2-0743-4328-9b42-62f72dd08f4b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861310958955626418</li>
        <li>Upwork Job ID: 1861310958955626418</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @arosiclair</details>

**Comment by ijmalik** [comment] 2024-11-18 21:16
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
User cannot send invoices after signing up for a new account.

**What is the root cause of that problem?**

Response of SendInvoice API has message: "Invalid URL"
```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "8AC21F89-F1B2-4AE0-8CF6-09E00FBB775F",
    "message": "Invalid URL",
    "title": "",
    "data": [],
    "htmlMessage": "",
    "onyxData": [],
    "requestID": "8e4aeb5de8dd402f-SIN"
}
```

The issue stems from how the companyWebsite is being validated in the application. Specifically, the current validation logic fails to properly handle reserved domains that are not suitable as a company website address. The validation logic skips these domains, which results in the inability to proceed with the invoice submission.

https://github.com/Expensify/App/blob/8e1b0fde744d47298042991a8f52a3a0a04d0e53/src/pages/iou/request/step/IOURequestStepCompanyInfo.tsx#L59-L65

The existing check does not account for certain reserved domains, which are defined by standards such as RFC 2606 and RFC 6761. These domains include addresses that cannot be used for valid company websites (e.g., example.com, localhost, etc.).

```
Here is the list of some reserved domains:
const RESERVED_DOMAINS = [
    'example.com',
    'example.net',
    'example.org',
    'test',
    'localhost',
    '.invalid',
    '.local',
    '.example',
    '.test',
    'invalid',
] as const;
```

**What changes do you think we should make in order to solve the problem?**

To address the issue, we propose modifying the current domain validation logic to account for reserved domains.
https://github.com/Expensify/App/blob/8e1b0fde744d47298042991a8f52a3a0a04d0e53/src/pages/iou/request/step/IOURequestStepCompanyInfo.tsx#L59-L65

Replace it with
```
        const domain = Url.extractUrlDomain(companyWebsite);
    
        if (!domain || !Str.isValidDomainName(domain)) {
            errors.companyWebsite = translate('iou.invalidDomainError');
        } else if (ValidationUtils.isPublicDomain(domain)) {
            errors.companyWebsite = translate('iou.publicDomainError');
        } else if (ValidationUtils.isReserveDomain(domain)) {
            errors.companyWebsite = translate('iou.reserveDomainError');
        }
```

https://github.com/Expensify/App/blob/4829ac9c0566665b81e3f98ea5ae8b5b7437e59c/src/libs/ValidationUtils.ts#L2
replace with
```
import {PUBLIC_DOMAINS, RESERVED_DOMAINS, Str, Url} from 'expensify-common';
```

https://github.com/Expensify/App/blob/4829ac9c0566665b81e3f98ea5ae8b5b7437e59c/src/libs/ValidationUtils.ts#L252-L255
replace with
```
/** Checks if the domain is public */
function isPublicDomain(domain: string): boolean {
    return PUBLIC_DOMAINS.some((publicDomain) => publicDomain === domain.toLowerCase());
}

/** Checks if the domain is reserved */
function isReserveDomain(domain: string): boolean {
    return RESERVED_DOMAINS.some((reservedDomain) => reservedDomain === domain.toLowerCase());
}
```

Since PUBLIC_DOMAINS is already defined in the expensify-common package, we should also add the RESERVED_DOMAINS list to the same package for consistency and reuse. Here is the relevant definition of PUBLIC_DOMAINS for reference:

https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/CONST.ts#L984-L1057

We should define RESERVED_DOMAINS in the same manner and ensure it is exported for use in validation logic across the application.


**What alternative solutions did you explore? (Optional)**

Valid Domain:

https://github.com/user-attachments/assets/4becb461-33e4-42af-a40e-1e92b3c52b52

Reserved Domain:

https://github.com/user-attachments/assets/0320416c-10e5-4715-a4ee-06ac2cac3036

**Comment by arosiclair** [comment] 2024-11-27 20:34
> But in any case [This proposal](https://github.com/Expensify/App/issues/52672#issuecomment-2484148628) makes sense

This proposal doesn't seem related to the original bug which was a report access error ([source](https://expensify.slack.com/archives/C01GTK53T8Q/p1727083383314299?thread_ts=1727076209.941879&cid=C01GTK53T8Q)). The website validation error isn't really something that needs to be fixed.

@wildan-m is this issue still reproducible for you?

**Comment by arosiclair** [comment] 2024-12-02 15:32
Okay let's wait to hear from @wildan-m to see if he was testing with an invalid website to confirm. It sounds like his issue was different but it might be the same.

**Comment by wildan-m** [comment] 2024-12-02 15:43
I can confirm that utilizing another custom site, such as https://validcompany.com, does not trigger the error.

**Comment by arosiclair** [comment] 2024-12-02 16:38
> @arosiclair I use https://www.google.com If that is deemed invalid, perhaps it would be more helpful to display an error while typing.
>
> I can confirm that utilizing another custom site, such as https://validcompany.com/, does not trigger the error.

Thanks. So the root of the problem _is_ submitting an invalid company website URL. We can check for reserved domains, but that doesn't fully address the issue since Stripe still rejects other URLs like `https://www.google.com/`. It doesn't look like their URL rules are public, so we can't really predict when it will fail.

So instead, let's just do a better job surfacing the invalid website error in the app so the user knows what went wrong and can try again. This is gonna require some backend changes so I'll take this internal.

**Comment by arosiclair** [comment] 2024-12-03 22:28
PR is out

**Comment by ijmalik** [comment] 2024-12-04 09:24
I would like to highlight my contributions to this issue. After a thorough investigation, I identified the root cause as a gap in domain validation logic, particularly concerning reserved domains and URLs deemed invalid.

To address this, I proposed a comprehensive solution to enhance the frontend validation logic, which the team acknowledged as sensible. Additionally, my findings helped clarify the underlying problem, providing a clear path forward.

Given the time and effort I invested in diagnosing and resolving this issue, I respectfully request consideration for compensation, consistent with past practices for similar contributions. For reference, here is a related discussion: [Comment on Issue #51612](https://github.com/Expensify/App/issues/51612#issuecomment-2470941961).

Thank you for your time and consideration.

**Comment by arosiclair** [comment] 2024-12-04 14:51
Your efforts are appreciated @ijmalik, but ultimately your RCA and solution were not correct (frontend validation was not the issue) and it did not lead to the backend solution we landed on which uses a different approach.

**Comment by mvtglobally** [comment] 2024-12-07 05:12
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2024-12-09 17:07
Nope - nothing due here imo

**Closed by adelekennedy** 2024-12-09 17:07 UTC
Labels: Weekly, Internal, Bug
