### ISSUE TITLE
[HOLD for payment 2024-11-01] [$125] BUG: SelfDM is marked as unread even though there is no message

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#51066] opened 2024-10-18 01:05 UTC
BUG: SelfDM is marked as unread even though there is no message
1. I signed up and wen’t through onboarding modals
2. When I get to the Concierge chat my SelfDM is unread
3. But there is no message in the self DM
  - The first image is when I choose “Manage my team”
  - The second is the SelfDM when you choose “Track my expenses”
  - In both cases, I don’t think it should be unread.

We discussed this internally and can't think of any cases where the SelfDM should be unread. So let's please update the flow so that it is marked as read when users come in as new users. 

Some background from @trjExpensify: 
https://github.com/Expensify/App/pull/43489 - It looks like we did this in this PR. 

We need to remove the selfDM from this line: https://github.com/Expensify/App/blob/f180cbb97f7158ee6339215c9d5313b50f232c8c/src/libs/ReportUtils.ts#L6127

![image](https://github.com/user-attachments/assets/00e83436-7a90-400f-b864-cdcd506ad524)

![image](https://github.com/user-attachments/assets/b0400299-914d-42e4-bce5-b0f0aa1363e5)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847081858608334041</li>
        <li>Upwork Job ID: 1847081858608334041</li>
        <li>Last Price Increase: 2024-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 104524422</li>
<li>mkzie2 | Contributor | 104524424</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by mkzie2** [comment] 2024-10-18 01:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

SelfDM is marked as unread even though there is no message 

### What is the root cause of that problem?

We force showing unread for new selfDM (no message):

https://github.com/Expensify/App/blob/f180cbb97f7158ee6339215c9d5313b50f232c8c/src/libs/ReportUtils.ts#L6127

### What changes do you think we should make in order to solve the problem?


Remove the `isSelfDM` check from the above.

**Comment by trjExpensify** [comment] 2024-10-18 09:53
I'm dropping the price on this as a one-liner we've identified.

**Comment by trjExpensify** [comment] 2024-10-18 10:29
@zanyrenney when this is deployed, please make sure we remove this test case from QA: https://github.com/Expensify/Expensify/issues/412760

CC: @isagoico

**Comment by danielrvidal** [comment] 2024-10-29 01:23
Confirmed it's working on production as intended! 
<img width="654" alt="image" src="https://github.com/user-attachments/assets/d8e3432d-c29c-4c9f-922b-b8cd257e3622">

**Comment by zanyrenney** [comment] 2024-11-01 10:52
@mkhutornyi please complete the checklist (you can edit my comment here to do so) so that i can close this out and pay it.

**Comment by zanyrenney** [comment] 2024-11-01 10:53
I have DM'd @mkhutornyi

**Comment by zanyrenney** [comment] 2024-11-04 17:11
Cool, please can you also complete the checklist? this is past due for payment @mkhutornyi  Thanks!

**Comment by zanyrenney** [comment] 2024-11-04 17:12
@isagoico already replied to the comment about updating the test case here.

**Comment by zanyrenney** [comment] 2024-11-05 12:18
BZ checklist above!

**Comment by zanyrenney** [comment] 2024-11-05 13:59
**payment summary**

@mkhutornyi requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104524422) (Reviewer) - paid $125
@mkzie2 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104524424) (Contributor) - paid $125

**Closed by zanyrenney** 2024-11-05 13:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
