### ISSUE TITLE
[$1000] Money request - Second money request while offline is missed  if the other User pay the first one

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26099] opened 2023-08-28 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login as User A and User B in front of you at the same time.
2. As User A requests Money from User B ( make sure it works by avoiding the bugs around the IOU feature Now )
3. As User A go offline ( go to settings > preferences > turn on the offline mode ) - don't go offline as User B.
4. As User A Send another Money request.
5. As User B, Pay the first money request elsewhere.
6. Back to User A and Go online again.
7. Notice the Money request message for both users.

## Expected Result:
The Second Money Request ( while offline ) should still appear for User A in the money request message, and displayed as unpaid
- The second Money request ( while offline ) should be sent to User B, with a button to pay it elsewhere.

## Actual Result:
The Second Money request ( while offline ) is missed for both users.
- Second request desapair for  User A ( sender ), and just the first request is displayed as paid
- Second Money request is not sent for User B.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d0bc740c-f092-4d5e-aaeb-50816a0a009d

https://github.com/Expensify/App/assets/115492554/b1ef6ca2-8f17-4468-906c-4a6b3f843c50

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ahmed-Abdella

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692401728126839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018064a0ff10eb2db7</li>
        <li>Upwork Job ID: 1697306425103572992</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by AJV009** [comment] 2023-09-01 07:49
This might require some major rework as I see, when an app goes online here, fresh details are being fetched from the server I guess. 
An easy approach would be to store offline transactions or any message locally and then recreate them or add them to the stack when the device comes online. Then we will also have to work out messages and other things that are done offline. 
OR we can put a barrier and say to the user that they cannot request without network access.

**Comment by zanyrenney** [comment] 2023-09-01 14:01
@maddylewis what do you think about combining these two? they seem related and likely have the same root issue: https://github.com/Expensify/App/issues/25925

**Comment by zanyrenney** [comment] 2023-09-04 14:05
@maddylewis when you're back LMK !

**Comment by maddylewis** [comment] 2023-09-05 13:57
@zanyrenney - yes, i think what you're suggesting here makes sense! https://github.com/Expensify/App/issues/26099#issuecomment-1702797089

**Comment by zanyrenney** [comment] 2023-09-08 14:19
Awesome, yep let's close out the newer one (i.e. your one) also that's the fairest given the change in prices happened. If you can just add the additional workflow to my issue then close this one out and I'll handle! thanks @maddylewis

**Comment by maddylewis** [comment] 2023-09-08 14:43
great! combined with this one - https://github.com/Expensify/App/issues/25925

closing!

**Comment by zanyrenney** [comment] 2023-09-19 04:08
Hi @maddylewis sorry but we've uncovered these have different root causes (https://github.com/Expensify/App/issues/25925#issuecomment-1724705349) so will need to be tackled sepaartely, reopening for you to handle.

**Comment by maddylewis** [comment] 2023-09-19 20:16
Rushat is working on a project with a deadline atm, so re-added the external label to add a new C+.

**Comment by maddylewis** [comment] 2023-09-22 14:20
updated price

**Comment by mvtglobally** [comment] 2023-09-28 03:19
Issue not reproducible during KI retests. (First week)

**Comment by Ahmed-Abdella** [comment] 2023-09-28 04:27
I still can reproduce this on latest main

[Screencast from 28-09-23 07:24:04.webm](https://github.com/Expensify/App/assets/77763699/2548f4fd-3656-4067-bf35-145fc6209bb8)

**Comment by maddylewis** [comment] 2023-09-29 14:47
will confirm if this is still reproducible

**Comment by maddylewis** [comment] 2023-10-07 19:44
@0xmiroslav - are you still able to repro this on your end?

**Comment by maddylewis** [comment] 2023-10-16 19:33
@0xmiroslav - lmk what you found out!

**Comment by maddylewis** [comment] 2023-10-28 03:01
still waiting for proposals

**Comment by maddylewis** [comment] 2023-11-28 03:04
based on the lack of progress/age of this issue, im going to close this out for now.

**Closed by maddylewis** 2023-11-28 03:04 UTC
Labels: Weekly, Internal, Overdue, Bug
