### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] IOU - Site crashes when editing a description with numbers after changing amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29369] opened 2023-10-11 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/ in Chrome or Android App 
2. Click the Green '+' Icon in the LHN
4. Choose "Request Money"
5. Enter an Amount
6. Tap Next
7. Choose a Recipient
8. Tap "Request"
9. Tap on the IOU transaction to open IOU detail page
12. Enter a description with numbers only (ex 444) and save it
13. Tap the amount and change it
14. Tap the Description again

## Expected Result:
When user changes Amount and taps Description, the site must not crash

## Actual Result:
When user changes Amount and tap Description, the site crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/26fc8149-a906-45a4-b79d-7052873445fd

[logs.txt](https://github.com/Expensify/App/files/12873965/logs.txt)

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01651ddb346bd06cdb</li>
        <li>Upwork Job ID: 1716876781919485952</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-10-11 21:50
I just attempted this on staging and it didn't crash. 

<img width="779" alt="image" src="https://github.com/Expensify/App/assets/1371996/ee8b21e3-e495-489c-9117-b525fde13f56">

**Comment by Christinadobrzyn** [comment] 2023-10-11 22:49
I can't get a crash either... asking QA to test again - https://expensify.slack.com/archives/C9YU7BX5M/p1697064585308679

**Comment by izarutskaya** [comment] 2023-10-12 07:21
Hi @Christinadobrzyn, we can't repro this crash today.

https://github.com/Expensify/App/assets/115492554/fe98cbd8-c307-46c3-a16d-40b5cf8bcaf8

https://github.com/Expensify/App/assets/115492554/c045d08b-7158-4837-b9b5-4b32ae0cab51

**Comment by puneetlath** [comment] 2023-10-12 13:23
Seems fixed!

**Comment by lanitochka17** [comment] 2023-10-14 14:21
Issue reproducible on Build 1.3.84-0
Windows10/Chrome

https://github.com/Expensify/App/assets/78819774/8b45a803-2c29-482f-9516-0f4726ab392a

**Comment by Christinadobrzyn** [comment] 2023-10-17 22:27
Thanks @lanitochka17 can you update to version v1.3.85-4 and let us know if you still see the crash?

**Comment by lanitochka17** [comment] 2023-10-18 18:15
Issue reproducible on build 1.3.86-3
Windows10/Chrome (incognito)
Black screen is displayed

https://github.com/Expensify/App/assets/78819774/d5a57ab1-855d-4f00-b49a-03ef8eca87d3

**Comment by Christinadobrzyn** [comment] 2023-10-18 18:51
oh! @lanitochka17 you're seeing this only on Windows and not a Mac? I don't think we're deploying any fixes for Windows unless it's a major problem - which I don't think this is?

Can you test on a Mac with Chrome/iOS/Android and let me know if you see this issue?

I just tested on Mac Chrome v1.3.86-3 - incognito and can't reproduce.

**Comment by lanitochka17** [comment] 2023-10-18 21:23
@Christinadobrzyn Hello

I cannot repro in Iphone 14 Pro Max/ios17

https://github.com/Expensify/App/assets/78819774/9bf20525-fc86-4af4-9b5d-2c832a303fe7

Issue reproducible on MAC Ventura13.5/Chrome when pressed again

https://github.com/Expensify/App/assets/78819774/2f65f33a-85f3-4c7f-99cc-bc2482bfcc87

Issue reproducible on Samsung Galaxy A50/Android11

https://github.com/Expensify/App/assets/78819774/02e1eb27-9be7-4391-a7b0-91ce47a6e9c9

**Comment by Christinadobrzyn** [comment] 2023-10-23 21:01
Sorry, I still can't reproduce this with the steps in the OP...

Okay, sitting down and doing more testing, I can reproduce this when entering a Number (ex 444) as the Description (it doesn't seem to work when you enter text). Updated the OP with the reproducible steps. 

So this is still happening - @puneetlath can you let me know if we should fix this?

**Comment by Christinadobrzyn** [comment] 2023-10-24 17:58
I think this is a bug and since it's before our Oct 24th [announcement](https://expensify.slack.com/archives/C02NK2DQWUX/p1698106527175449), I assume we want to move forward with a fix? Adding External

**Comment by Jenemark** [comment] 2023-10-24 19:26
I had a look at this, the bug was introduced with the issue: 
https://github.com/Expensify/App/issues/21271

The issue is the propType not being a proper String, a number is passed to the BaseTextInput which fails on any string functions.

.endWith will fail so long a number is passed. Theres multiple ways to fix this.

I will make the changes to make sure it will always be a string passed to the baseTextInput. And therefor remove possibility of any string errors happening.

**Comment by Jenemark** [comment] 2023-10-24 19:28
Contributor details
Your Expensify account email: je.enemark96@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01623c443bdf3b7c13

**Comment by puneetlath** [comment] 2023-10-25 16:10
@Christinadobrzyn yes, I agree that we should fix this if it is reproducible. We definitely want to fix it if it causes a crash.

**Comment by burczu** [comment] 2023-10-26 12:00
Just checked [the proposal](https://github.com/Expensify/App/issues/29369#issuecomment-1777889234) from @Jenemark and I think it identifies the root cause correctly. The proposed solution to always cast the description to string in the `TransactionUtils.ts` file makes sense to me, so I think we could proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment] 2023-11-08 22:57
Payment is upcoming. Here's what I understand: 

Issue Reporter: NA - Applause Team
Contributor: $500 + $250 speed bonus @burczu (contractor so not paid through Upwork/New Expensify)
Contributor+: $500 + $250 speed bonus @Jenemark (through Upwork)

Eligible for 50% #urgency bonus? Y - looks like the PR was created Oct 27 and merged Oct 30th (3 days)

Upwork job is [here](https://www.upwork.com/jobs/~01651ddb346bd06cdb).

Let me know if any of this needs to change and a regression test when you have a moment @burczu

**Comment by Christinadobrzyn** [comment] 2023-11-10 22:54
@burczu can you let us know about a regression test?

**Comment by Jenemark** [comment] 2023-11-11 07:04
@Christinadobrzyn I accepted it on upwork, thank you :-)

**Comment by Christinadobrzyn** [comment] 2023-11-13 21:51
Awesome! Thanks @Jenemark - I paid you in Upwork. 

@burczu can you let us know about a regression test?

**Comment by burczu** [comment] 2023-11-14 12:29
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:

**I don't think it's a regression - this was done like this from the beginning.**

* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

**n/a**

* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**n/a**

* [x]  [@burczu] Determine if we should create a regression test for this bug.

**I don't think we need to add regression test here - this is quite uncommon case, so I think not very impactful. Also the test would have quite a lot of steps.**

* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@Christinadobrzyn] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Christinadobrzyn** [comment] 2023-11-14 23:15
thanks @burczu! 

I think this is good to close, please let me know if I'm missing anything!

**Closed by Christinadobrzyn** 2023-11-14 23:15 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
