### ISSUE TITLE
Compose box - Unable to enter edit mode when pressing ArrowUp

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48548] opened 2024-09-04 12:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4923707
**Email or phone of affected tester (no customers):** andreylazutkinutest+123@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to staging.new.expensify.com
2. Navigate to a conversation with a secondary user you have access to
3. Send two messages to the secondary user
4. As secondary user navigate to conversation and send a message to the primary user
5. As primary user press the ArrowUp while focusing on compose box

## Expected Result:
The last message sent by the primary user enters edit mode

## Actual Result:
The last message sent by the primary user doesn't enter edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9bc74d93-f2aa-4fd1-8251-f9daccaf5168

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2024-09-04 14:04
Able to repro on staging v9.0.29-1

**Comment by NikkiWines** [comment] 2024-09-04 14:28
Seems to be a dupe of https://github.com/Expensify/App/issues/48549 which has ongoing investigation. Closing this out.

**Closed by NikkiWines** 2024-09-04 14:28 UTC
Labels: DeployBlockerCash, Engineering, Hourly
