### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] mWeb - BNP-Dragging on right side is disappeared in BNP page after pasting few times.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34921] opened 2024-01-22 20:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4 29
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4209827
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to site in both mweb/ Android app and perform the below steps
2. Tap fab ---Request money
3. Type "22222"
4. Copy any single digit number "7"
5. Drag, select & try to replace last number in step 3 by pasting "7"
6. Drag, select & try to replace first number in step 3 by pasting "7"
8. Drag, select & try to replace middle number in step 3 by pasting "7"
9. Now drag, select & try to replace remaining digit by pasting "7"
10. Note, after pasting few times, drag option with "blue bubble down" disappeared on right side in mweb and user able to replace all digits in Android app

## Expected Result:
Dragging on right side ( "blue bubble down" ) must not be disappeared in BNP page after pasting few times

## Actual Result:
Dragging on right side ( "blue bubble down" ) is disappeared in BNP page after pasting few times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/5745bed2-07e8-4d69-9a53-d45ce86f96ed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8f90ef37ac00b1d</li>
        <li>Upwork Job ID: 1749522886703788032</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 28120584</li>
<li>wildan-m | Contributor | 28120586</li>
</ul></li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2024-01-23 16:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb - dragging on the right side disappeared in the BNP page after pasting a few times.

### What is the root cause of that problem?

Calculated text width is less than required to show the text selection handle

### What changes do you think we should make in order to solve the problem?
We need to add at least 1 more pixel to show the text selection handle.

We can change this code:

https://github.com/Expensify/App/blob/82fff8c54517ad2256ca2b7328fc04f538732012/src/components/TextInput/BaseTextInput/index.tsx#L447-L454

To: 
```
                    onLayout={(e) => {
                        let additionalWidth = 0;
                        if (Browser.isMobileSafari() || Browser.isSafari()) {
                            additionalWidth = 2;
                        }

                        If(Browser.isMobileChrome())
                        {
                            additionalWidth = 1
                        }

                        setTextInputWidth(e.nativeEvent.layout.width + additionalWidth);
                        setTextInputHeight(e.nativeEvent.layout.height);
                    }}
```

Or we can just add Browser.isMobileChrome() to the existing logic, some devices/phone resolution might need more than 1 pixel.

```
                    onLayout={(e) => {
                        let additionalWidth = 0;
                        if (Browser.isMobileSafari() || Browser.isSafari() || Browser.isMobileChrome()) {
                            additionalWidth = 2;
                        }


                        setTextInputWidth(e.nativeEvent.layout.width + additionalWidth);
                        setTextInputHeight(e.nativeEvent.layout.height);
                    }}
```


### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment] 2024-01-24 01:23
Thanks @mountiny, In case the C+ not being notified (@ishpaul777), I have [a proposal](https://github.com/Expensify/App/issues/34921#issuecomment-1906472127) ready for review

**Comment by wildan-m** [comment] 2024-01-25 00:45
@ishpaul777, @srikarparsi in case we want to proceed, I've prepared [a PR ready for review](https://github.com/Expensify/App/pull/35119).

**Comment by srikarparsi** [comment] 2024-01-25 00:47
Awesome thanks @wildan-m!

**Comment by alexpensify** [comment] 2024-01-26 18:31
Awesome, we are moving forward here and will wait for automation.

**Comment by wildan-m** [comment] 2024-02-07 22:20
@alexpensify @srikarparsi, @ishpaul777 is there any regression from the PR?

**Comment by alexpensify** [comment] 2024-02-08 00:50
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue @wildan-m $500 
-  Contributor+ that helped on the issue and/or PR @ishpaul777 $500 

Upwork Job: https://www.upwork.com/jobs/~01c8f90ef37ac00b1d

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: @wildan-m - there was no automation flagging regressions, so all clear here. 

--- 

Closing, everyone has been paid via Upwork and I closed the job there too.

**Closed by alexpensify** 2024-02-08 00:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
