### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Image opens in both a new tab and the app modal

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50260] opened 2024-10-04 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728035042470999

## Action Performed:
1. Copy the content from step 3 to step 4 in this issue #50006.
2. Open any chat and paste the copied content.
3. Click on the image.
## Expected Result:
The image should open only within the app modal.
## Actual Result:
The image opens in both the app modal and a new browser tab.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dbaa8768-284d-4a8b-99f4-232d13ec1904

https://github.com/user-attachments/assets/739017c9-6614-4004-9153-64d2cff9e78c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843737342052804907</li>
        <li>Upwork Job ID: 1843737342052804907</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104738185</li>
<li>huult | Contributor | 104738186</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by c3024** [comment] 2024-10-05 04:38
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When clicking on image added with markdown, it opens both in the modal and another tab.
### What is the root cause of that problem?
We are pasting the markdown as [!(oneLink)](anotherLink) here whereas the right markdown for this should be ![altText](imageLink) for this to correctly show the image.
Our markdown link handling handles []() as a link, so the pasted markdown becomes
The inside !(oneLink) is parsed as an image with no alt text with oneLink as image link and another a tag with anotherLink as the hyperlink for this previous no alt text with link.
So, the image tag causes it to open in the modal due to ImageRenderer and a tag causes it to open in a browser tab.
### What changes do you think we should make in order to solve the problem?
We can alter the markdown regex for link handling to not allow ! marks inside [].
### What alternative solutions did you explore? (Optional)
We can prevent browser default behaviour in such cases to not open a tags when there is an image because I think we do not want to hyperlink another link to an image.
Then we can prevent event default in ImageRenderer
```js
<PressableWithoutFocus
                            style={[styles.noOutline]}
                            onPress={(e) => {
                                e?.preventDefault();
```
and also pass this event to `PressableWithoutFocus`
```js
const pressAndBlur = (e) => {
        ref?.current?.blur();
        onPress?.(e);
    };
```
This way when both tags are present we prevent the a tag default behaviour of opening the other link in another tab.

**Comment by bernhardoj** [comment] 2024-10-05 04:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Image opens both the attachment modal and a new tab.

### What is the root cause of that problem?
The image copied is converted to an image link markdown, which when converted to HTML becomes,
```
<a><img/></a>
```

Pressing the image will trigger both the ImageRenderer preview and the AnchorRenderer `onPress`.

### What changes do you think we should make in order to solve the problem?

I think having an image link is a valid thing. It's mentioned in the ExpensiMark [comment](https://github.com/Expensify/expensify-common/blob/1373f28a673343fca026947ec42a6fad96e566d7/lib/ExpensiMark.ts#L243-L245) too.

If we create an image link markdown, then I believe pressing it should open the link only in a new tab. To do that, we can disable the image preview if the image is wrapped in an anchor tag.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L63

```
const isImageLink = tnode.parent?.tagName === 'a'; // maybe we can recursively look for an anchor tag parent, but for our case, this is enough
const imagePreviewModalDisabled = htmlAttribs['data-expensify-preview-modal-disabled'] === 'true' || isImageLink;
```

**Comment by c3024** [comment] 2024-10-05 05:04
>Converts markdown style images to image tags e.g. ![Expensify](https://www.expensify.com/attachment.png)

This ```![Expensify](https://www.expensify.com/attachment.png)``` is a valid thing but in this case, this is what is pasted [![Expensify](https://www.expensify.com/attachment.png)](somOtherLink.com). So, I am not sure if we want to parse this as a link when the inside is already parsed as an image.

**Comment by suneox** [comment] 2024-10-06 06:52
@CortneyOfstad  I've reported this issue, so I have more context on it and I can help review the proposal as a C+

**Comment by CortneyOfstad** [comment] 2024-10-08 19:37
Thanks @suneox!

**Comment by suneox** [comment] 2024-10-09 19:34
@CortneyOfstad  I'd like to confirm in the case where an image has an embedded link, should clicking it open the image or the link? or should we still open image and have a confirmation to open an external link

**Comment by CortneyOfstad** [comment] 2024-10-14 20:17
> or should we still open image and have a confirmation to open an external link

I believe we should open the image and then have confirmation as you stated 👍

**Comment by CortneyOfstad** [comment] 2024-10-15 19:55
Hey @dylanexpensify! I am heading OoO this afternoon (10/15 to 10/23) so reassigning this in the meantime to keep it moving! Thanks!

**Comment by dylanexpensify** [comment] 2024-10-17 20:28
Ah nice, I am heading out too! haha

**Comment by suneox** [comment] 2024-10-21 02:24
> I believe we should open the image and then have confirmation as you stated 👍 

Based on this expected behavior I have posted [slack](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1729475905364619) to get more eyes

**Comment by huult** [comment] 2024-10-21 05:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Image opens in both a new tab and the app modal

### What is the root cause of that problem?

Image Opens New Tab Because: This image is wrapped by Tag A in the original, so when we copy and paste it to ND, it remains wrapped by Tag A after reading the HTML. When we click on this image, it will open a new tab using the href of Tag A

https://github.com/Expensify/App/blob/13f41cbb09510cdf6b9e039ed121397676efc04e/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.tsx#L74

Image Opens Modal Because: The image will open a modal, which is the behavior of an attachment

### What changes do you think we should make in order to solve the problem?

> I believe we should open the image and then have confirmation as you stated 👍

We will update the behavior as mentioned in the comment above. Here’s what we will do:

1. We should prevent opening a new tab for images wrapped by Tag A, something like this:

```diff
//.src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L60
+    const hasImageInLink = tnode.tagName === 'a' && tnode.children.some((child) => child.tagName === 'img');

//.src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L75
        <AnchorForCommentsOnly
        ...
+        hasImageInLink={hasImageInLink}
        />
```

```diff
//src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.tsx#L65
-        <Tooltip text={!hasImageInLink ? href : undefined}>
+        <Tooltip text={href}>
                <Text
                    ...
+                    href={!hasImageInLink ? href : undefined}
                    ...    
                >
                    {children}
                </Text>
        </Tooltip>
```

2. We should show a confirmation modal to the user to allow opening this image in a new tab, something like this:
Note: We need to design the confirmation behavior. I suggest two behaviors:
- Show the confirmation modal simultaneously with the attachment modal
- Create a new icon next to the download icon

In this POC, I used the first behavior

```diff
//.src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L93
-       const route = ROUTES.ATTACHMENTS?.getRoute(reportID ?? '-1', type, source, accountID, isAttachmentOrReceipt);
+       const linkToOpen = tnode.parent?.attributes?.href;
+       const route = ROUTES.ATTACHMENTS?.getRoute(reportID ?? '-1', type, source, accountID, isAttachmentOrReceipt, linkToOpen);
```

```diff
//.src/ROUTES.ts#L313
    ATTACHMENTS: {
        ...
-        getRoute: (reportID: string, type: ValueOf<typeof CONST.ATTACHMENT_TYPE>, url: string, accountID?: number, isAuthTokenRequired?: boolean) => {
+        getRoute: (reportID: string, type: ValueOf<typeof CONST.ATTACHMENT_TYPE>, url: string, accountID?: number, isAuthTokenRequired?: boolean, imageWithExternalLink?: string) => {
            ...
+           const imageWithExternalLinkParam = imageWithExternalLink ? `&imageWithExternalLink=${encodeURIComponent(imageWithExternalLink)}` : '';

-            return `attachment?source=${encodeURIComponent(url)}&type=${type}${reportParam}${accountParam}${authTokenParam}` as const;
+            return `attachment?source=${encodeURIComponent(url)}&type=${type}${reportParam}${accountParam}${authTokenParam}${imageWithExternalLinkParam}` as const;
        },
    },
```

```diff
//.src/pages/home/report/ReportAttachments.tsx#L21
+ const imageWithExternalLink = route.params?.imageWithExternalLink;

//.src/pages/home/report/ReportAttachments.tsx#L29
    const onCarouselAttachmentChange = useCallback(
        (attachment: Attachment) => {
-            const routeToNavigate = ROUTES.ATTACHMENTS.getRoute(reportID, type, String(attachment.source), Number(accountID));
+            const routeToNavigate = ROUTES.ATTACHMENTS.getRoute(reportID, type, String(attachment.source), Number(accountID), !!isAuthTokenRequired, imageWithExternalLink);
            Navigation.navigate(routeToNavigate);
        },
-        [reportID, type, accountID, isAuthTokenRequired, imageWithExternalLink],
+        [reportID, type, accountID, isAuthTokenRequired, imageWithExternalLink],
    );

//.src/pages/home/report/ReportAttachments.tsx#L37
        <AttachmentModal
                ...
+                imageWithExternalLink={imageWithExternalLink}
        />      

```

```diff
//.src/components/AttachmentModal.tsx#L166
function AttachmentModal({
+    imageWithExternalLink = '',
}: AttachmentModalProps) 

/.src/components/AttachmentModal.tsx#L191
+   const [showConfirm, setShowConfirm] = useState(!!imageWithExternalLink);

/.src/components/AttachmentModal.tsx#L638
+        {!!imageWithExternalLink && (
+                <ConfirmModal
+                    title={'This image has an external link. Do you want to visit it?'}
+                    onConfirm={() => {
+                        setShowConfirm(false);
+                        Linking.openURL(imageWithExternalLink);
+                    }}
+                    onCancel={() => {
+                        setShowConfirm(false);
+                    }}
+                    isVisible={showConfirm}
+                    onModalHide={() => {
+                        setShowConfirm(false);
+                    }}
+                />
+            )}
```

**Comment by suneox** [comment] 2024-10-21 18:00
@huult Thank you for your proposal, but it doesn’t work on the native platform. Could you please double-check on iOS/Android native?​

**Comment by huult** [comment] 2024-10-22 04:58
hi @suneox I tested on the native platform and found that we can't copy and paste as described in this issue. Instead of rendering the image, it just shows text like the image below, right?

- <img width="297" alt="Screenshot 2024-10-22 at 11 51 10" src="https://github.com/user-attachments/assets/d44df80c-62d8-42f2-ae92-3956013a2560">

If yes, I think this issue exists and is not related to this issue.

Or, did you test like `![test](https://camo.githubusercontent.com/6e100123165bb572e6fb35bba1dc9936d6a4691971a607ad802d6ffb61c2221a/68747470733a2f2f64326b356e736c327a786c6476772e636c6f756466726f6e742e6e65742f696d616765732f616e696d6174696f6e732f616e696d6174696f6e5f736574757067756964652e676966)` and not show the confirm modal?

If yes, it’s still the old behavior. Should we still update this case?

Let me know which case you mentioned. Thank you!

**Comment by suneox** [comment] 2024-10-22 07:33
> Let me know which case you mentioned.

I tested with this case `[!(https://picsum.photos/200)](https://picsum.photos/200)`

**Comment by huult** [comment] 2024-10-22 07:44
@suneox Got it. In your case, if the source is not from Expensify, show a confirmation modal and allow it to open if the user clicks 'Yes', correct?

**Comment by suneox** [comment] 2024-10-22 18:42
> I tested on the native platform and found that we can't copy and paste as described in this issue. Instead of rendering the image, it just shows text like the image below, right?

Maybe the parser for native doesn't work like web, but I can still send an image with the link on both web/native

https://github.com/user-attachments/assets/f73d1868-7cb1-4131-bc4c-de29220cbea2

> if the source is not from Expensify, show a confirmation modal and allow it to open if the user clicks 'Yes', correct?

@huult  Yes, it’s the same expected behavior as mentioned in [this comment](https://github.com/Expensify/App/issues/50260#issuecomment-2412128459)

**Comment by huult** [comment] 2024-10-23 10:11
## [Proposal Updated](https://github.com/Expensify/App/issues/50260#issuecomment-2425617617)

- Updated the confirmation modal for both native and mWeb
- Updated the POC

@suneox Could you please review my proposal again? If you have any questions, please let me know.

**Comment by suneox** [comment] 2024-10-23 16:32
@Expensify/design Currently, the markdown input supports images with a link. This issue resolve the behavior where both the image and link open at the same time. What do you think of [this behavior](https://github.com/Expensify/App/issues/50260#issuecomment-2403285270)? 
The result will look like this

https://github.com/user-attachments/assets/964f4bc6-b673-45f2-bdbf-0c8997dcdea1


Or should we add a new icon somewhere on the modal to open the link (maybe next to the download button, as @huult suggested)?

cc: @CortneyOfstad

**Comment by dannymcclain** [comment] 2024-10-23 17:24
I honestly don't have strong feelings. I think I like the modal approach better than adding an icon... But I also don't know if I feel strongly that we need to do anything. Does this seem like it's going to be a common occurrence? Does our image markdown even _need_ to support a link as altText? 🤔 Curious what the other designers think. Maybe I'm missing something or not thinking about this hard enough.

**Comment by shawnborton** [comment] 2024-10-23 18:23
I think I would expect to just treat this image like any other image, and just open the attachment modal to view it. 

What happens when you press the download button on one of these image attachments in the modal viewer? Does it download the image?

**Comment by dubielzyk-expensify** [comment] 2024-10-24 03:22
I don't have super strong feelings here, but it feels a bit weird to not link to the original image when that's the point of that specific markdown syntax. Then again it does look like even GitHub pulls the image locally and then links to it, so maybe that's the right move

**Comment by suneox** [comment] 2024-10-24 14:38
> What happens when you press the download button on one of these image attachments in the modal viewer? Does it download the image?

The image is still downloadable.

> Then again it does look like even GitHub pulls the image locally and then links to it, so maybe that's the right move

The image from GitHub doesn’t have a “view detail” mode, so it always opens the image or link directly. However, in our application, opening both the image and the link at the same time could confuse the end user

**Comment by dannymcclain** [comment] 2024-10-24 15:16
>I don't have super strong feelings here, but it feels a bit weird to not link to the original image when that's the point of that specific markdown syntax. 

The interesting thing with ours though is that the altText link doesn't need to be related to the image at all though.

Like I could send this:
```
![https://google.com](https://UrlOfMyImage.png)
```

And it would be both showing the image AND the image would be a link to Google... That's the part that's kind of tripping me up.

**Comment by suneox** [comment] 2024-10-24 16:15
> Like I could send this:

Regarding the image with a link, you can try with this one

```
![Image](https://picsum.photos/200)

[![ImageWithLink](https://picsum.photos/200)](https://google.com)
```

**Comment by dubielzyk-expensify** [comment] 2024-10-25 00:03
If we wanted to do this in the most lightweight way possible, we could also add a globe icon to the top right that'll link out to the linked URL. This is kinda similar to when you open a webview in an app on iOS and it gives you the opportunity to open it in full Safari instead.

![image](https://github.com/user-attachments/assets/32a36d76-aa3c-4d6e-aacc-f777fddfb048)

Keen to hear what @Expensify/design thinks

**Comment by huult** [comment] 2024-10-25 00:21
@dubielzyk-expensify When the global icon is clicked, we will link the image URL without showing a confirmation modal, right?

**Comment by dubielzyk-expensify** [comment] 2024-10-25 00:55
That's the idea, but before we go ahead with it I'd love to hear if @Expensify/design agrees or not

**Comment by shawnborton** [comment] 2024-10-25 07:40
Hmm I don't love the idea of adding another icon up there, and the globe feels slightly ambiguous to me? 

Could another option be to just use the right-click/long press menu to expose an option to "Copy URL to clipboard" or something? Similar to what we do for messages that contain links...

**Comment by dannymcclain** [comment] 2024-10-25 13:47
Do we have the concept of a caption? Would it be insane to just always display the alt text provided for an image as a little caption below the image in the attachment view?

I'm also not super keep on adding another icon up in the header for this.

>Could another option be to just use the right-click/long press menu to expose an option to "Copy URL to clipboard" or something? Similar to what we do for messages that contain links...

Not against this idea either if we could make it work.

**Comment by huult** [comment] 2024-10-28 15:37
I did a POC and used a long press to copy the URL to the clipboard. What does everyone think about that?

Behavior:
If it's an external attachment, a long press will copy the URL to the clipboard and display a 'Copied' label, which will be hidden after 5 seconds.

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/f6e08399-6843-4f72-9d8a-c75196f51417

</details>

**Comment by dannymcclain** [comment] 2024-10-28 15:59
>I did a POC and used a long press to copy the URL to the clipboard. What does everyone think about that?

🤔 The thing about this though is that there is absolutely no indication that there's even a URL that _could_ be copied? How would a user ever possibly know?

>Do we have the concept of a caption? Would it be insane to just always display the alt text provided for an image as a little caption below the image in the attachment view?

Are we totally against this idea? ☝️ Maybe something like this? 🤷 
![image](https://github.com/user-attachments/assets/969fc52a-ffa2-4f45-a86a-6a571c580944)

**Comment by suneox** [comment] 2024-10-28 15:59
> I did a POC and used a long press to copy the URL to the clipboard. What does everyone think about that?

I think long press to copy link look like a hidden feature due to user can not get to know which of image has a link

I like Notion’s UX for images with a link where an anchor icon appears on the image thumbnail, allowing the user to choose between opening the image in detail or the link

![Screenshot 2024-10-28 at 22 43 37](https://github.com/user-attachments/assets/cd2c3af5-dab4-4632-ab26-89e1b673e5d7)

**Comment by huult** [comment] 2024-10-28 16:10
Looks good. @dannymcclain , what do you think about @suneox 's idea?

**Comment by dannymcclain** [comment] 2024-10-28 16:36
Feels very much in line with my suggestion. I proposed putting on the attachment modal because we already have the concept of that type of layout in some other situations, we won't have to fuss with creating a new UI pattern for thumbnails & messages, and it keeps it accessible without being super in your face.

@Expensify/design curious what y'all think about [this idea](https://github.com/Expensify/App/issues/50260#issuecomment-2441991207).

**Comment by shawnborton** [comment] 2024-10-28 17:11
> The thing about this though is that there is absolutely no indication that there's even a URL that could be copied? How would a user ever possibly know?

I think my thinking here is... do we actually know if people want or need this? I'm trying to think of how I would personally use this at least. I feel like my first instinct is to just download the image if I needed it for something else, or even right click and "Copy Image Address" to then use that address elsewhere. 

![CleanShot 2024-10-28 at 18 10 10@2x](https://github.com/user-attachments/assets/61095495-7600-4f4f-8c1f-93212a3f1e16)


Definitely not opposed to what you are proposing, but it feels like a heavier solution that I think most users would actually need, personally. And then just to clarify on your solution, would only images created via markdown get the link caption below them?

**Comment by dubielzyk-expensify** [comment] 2024-10-29 02:09
> I think my thinking here is... do we actually know if people want or need this?
I don't know, which is why I questioned even supporting this somewhere way up in the thread 😂

I thought it was more a completeness of the markdown syntax. Like if you specifically say that image should have a link to a place, but then the link doesn't go anywhere, it feels a bit weird given how much effort we've put into the markdown editor. But I could be misunderstanding. I'm okay if we wanna do nothing here given it already sounds like we haven't gotten many complains about this. Maybe we keep an eye out and revisit if it pops up again?

**Comment by shawnborton** [comment] 2024-10-29 08:20
Ah that's fair, I think maybe I was misunderstanding the issue at hand. I think if you intentionally use markdown to display an image and intentionally add a link to that image, part of me feels like clicking on the image should only ever open up a link? 

Or, I think I could get down with Danny's caption approach in that case too.

**Comment by huult** [comment] 2024-10-30 17:18
I voted for @dannymcclain's idea as well

**Comment by suneox** [comment] 2024-10-31 15:25
We’re still waiting for the @Expensify/design to select a solution for this issue, I think we can proceed with [this idea](https://github.com/Expensify/App/issues/50260#issuecomment-2441991207).

cc: @CortneyOfstad

**Comment by shawnborton** [comment] 2024-10-31 16:03
Cool, I like Danny's idea but I think I wouldn't do the alt text idea to start - I would just add the small caption if the image was inserted via markdown and includes a link.

**Comment by shawnborton** [comment] 2024-10-31 16:05
Also another thing that just occurred to me - have we considered just adding the link as small text right under "Attachment" in the header view? 

![image](https://github.com/user-attachments/assets/d9bc1e65-5382-46d5-85a9-1bd7f87e2a07)

**Comment by dannymcclain** [comment] 2024-10-31 16:07
>I think I wouldn't do the alt text idea to start - I would just add the small caption if the image was inserted via markdown and includes a link.

That works for me—I was just thinking it might be hard for us to know whether the alt text was a link or not 🤷 

>Also another thing that just occurred to me - have we considered just adding the link as small text right under "Attachment" in the header view?

I'm also into this idea!

**Comment by shawnborton** [comment] 2024-10-31 16:24
Yeah my thinking is that in other parts of the app we use a little blue link in the header sometimes... and this way it keeps a more consistent image viewing experience? Dunno, just riffin' man!!

**Comment by dubielzyk-expensify** [comment] 2024-11-01 01:17
Yeah, I don't mind that either

**Comment by dannymcclain** [comment] 2024-11-01 13:19
Alright let's go with [Shawn's idea](https://github.com/Expensify/App/issues/50260#issuecomment-2450257915) and get this moving along!

**To summarize:**
- If an image has a link as its altText, we'll display that link as a subtitle in the attachment modal below the `Attachment` title
- The link should use our `label` size text (like our other subtitles) and be displayed as a proper link
- If an image does not have a link as its altText (ie just has regular text) we will not display anything on the attachment modal

Sound good?

**Comment by shawnborton** [comment] 2024-11-01 14:13
Sounds great, let's do it!

**Comment by huult** [comment] 2024-11-02 06:25
## [Proposal updated](https://github.com/Expensify/App/issues/50260#issuecomment-2425617617)

- Updated POC
- Updated test branch
- Updated code example changes

Hi, I have updated the POC following [this comment](https://github.com/Expensify/App/issues/50260#issuecomment-2451859741). Could we check it? Let me know if you have any feedback. Thanks!

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/ab4a3efd-e80a-4ab0-abb5-e9d3175f47ea

</details>

**Comment by suneox** [comment] 2024-11-03 06:31
@huult proposal to prevent opening links with images and display the link as altText based on [this confirmation](https://github.com/Expensify/App/issues/50260#issuecomment-2425617617) LGTM. Code cleanup will be performed during the PR review.

🎀 👀 🎀 C+ reviewed

**Comment by huult** [comment] 2024-11-05 03:30
Thank you, everyone. I will create the pull request within 24 hours

**Comment by CortneyOfstad** [comment] 2024-11-05 14:01
Thank you @huult!

**Comment by CortneyOfstad** [comment] 2024-11-26 17:42
Due to the Thanksgiving holiday in the US this week, going to get this paid early 👍

**Comment by CortneyOfstad** [comment] 2024-11-26 17:45
## Payment Summary

@huult — paid $250 via Upwork
@suneox — paid $250 via Upwork (not sure why it linked it twice above, but confirmed it was a dupe and not two separate contracts)

## Regression Test

Not needed based on checklist [here](https://github.com/Expensify/App/issues/50260#issuecomment-2498586716)

**Closed by CortneyOfstad** 2024-11-26 17:45 UTC
Labels: External, Weekly, Awaiting Payment, Bug
