### ISSUE TITLE
Thread - Edited message is visible after refresh page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20905] opened 2023-06-16 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20336

## Action Performed:
1. Login with any account
2. Open a report
3. Send a markdown message e.g google.com
4. Clicking on reply in thread of this message
5. Edit the message

## Expected Result:
Edited message should be visible immediately.

## Actual Result:
Edited message is visible after refresh page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.5

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/16e3a0d4-4d69-4dd2-bbc1-cac0cc008419

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-06-16 22:25
I think this is a dupe of this https://github.com/Expensify/Expensify/issues/282991 Do you agree @chiragsalian?

**Comment by chiragsalian** [comment] 2023-06-19 23:24
Yes, its a dupe of https://github.com/Expensify/Expensify/issues/282991, im closing this out just so there is one issue to focus on.

**Closed by chiragsalian** 2023-06-19 23:24 UTC
Labels: Daily, Overdue, Bug
