### ISSUE TITLE
[HOLD for payment 2024-03-26] IOU - BNP buttons are smaller and narrower

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38287] opened 2024-03-14 10:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to FAB > Request money.
3. Go to Manual.

## Expected Result:
BNP buttons are not small and narrow.

## Actual Result:
BNP buttons are small and narrow (compared to production).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6413005_1710382031786!staging](https://github.com/Expensify/App/assets/115492554/1d472d21-14c5-41c2-b6c1-709829c71d0a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment] 2024-03-14 10:44
I'm going to demote this one to an NAB since it's a visual thing that doesn't affect the functionality. Tagging @Expensify/design in the meantime.

**Comment by izarutskaya** [comment] 2024-03-14 10:46
@cristipaval I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-14 10:48
Production 

![Bug6413005_1710382031784!PROD](https://github.com/Expensify/App/assets/115492554/4a67f355-e5b0-4649-9b43-61cc8581c850)

**Comment by cristipaval** [comment] 2024-03-14 10:49
> @cristipaval I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

Thanks @izarutskaya, I tagged the design team for now. Let's start from there

**Comment by narefyev91** [comment] 2024-03-14 10:55
just let me know which size those buttons should be - will add a fix for that

**Comment by shawnborton** [comment] 2024-03-14 12:52
cc @narefyev91 - can you follow up and fix this one too?

**Comment by dubielzyk-expensify** [comment] 2024-03-14 21:58
Yep, exactly what Shawn said :)

**Comment by jliexpensify** [comment] 2024-03-19 22:39
I'm headed OOO from the 21st to 31st, but I don't think this needs reassigning?

It seems like this is a conflict from this PR https://github.com/Expensify/App/pull/37966, so no payment is needed?

**Comment by jliexpensify** [comment] 2024-03-20 01:43
Hi @abekkala - I'm OOO from 21st to 31st March, so assigning a buddy.

[I don't think any payment is needed](https://github.com/Expensify/App/issues/38287#issuecomment-2008282543), but if I'm wrong, could you help out? Thanks!

**Comment by abekkala** [comment] 2024-03-20 17:03
### PAYMENT SUMMARY FOR MAR 26

- Fix: @narefyev91 - CallStack, no payment needed 
- PR Review: @sobitneupane [$500, if no regressions] Payment made via NEWDOT

It should be decided if a regression test is needed

**Comment by abekkala** [comment] 2024-03-22 18:13
@slafortune will be handling payment for me while I'm ooo

**Comment by cristipaval** [comment] 2024-03-25 16:09
payment not due yet

**Comment by slafortune** [comment] 2024-03-27 00:02
Fix: @narefyev91 - CallStack, no payment needed
PR Review: @sobitneupane [$500, if no regressions] Payment made via NEWDOT

**Closed by slafortune** 2024-03-27 00:02 UTC
Labels: Engineering, Daily, Design, Awaiting Payment, Bug

**Comment by jliexpensify** [comment] 2024-03-31 23:17
Thanks April and Stevie!

**Comment by JmillsExpensify** [comment] 2024-04-11 20:50
$500 approved for @sobitneupane
