### ISSUE TITLE
[$250] Category - Category name with long parent child relationship is truncated

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42671] opened 2024-05-27 21:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a97@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-conditions:
1. Create a workspace
2. Create a category name with long parent child relationship (e.g: "A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done: A: Very: Long: Category: List: Done"
3. Open workspace chat
4. Click on Plus icon inside compose box > Submit expense > Manual > Enter amount > Click next
5. Open category list and scroll down

## Expected Result:
Category name should be fully visible

## Actual Result:
When create expense category name with long parent child relationship is truncated and can not be fully seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6e743c4e-1270-42fa-967e-229e876ff0b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191043236868f0a79</li>
        <li>Upwork Job ID: 1796021149864828928</li>
        <li>Last Price Increase: 2024-05-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-05-27 21:24
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment] 2024-05-30 03:29
Able to repro.

**Comment by truph01** [comment] 2024-05-30 03:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When create expense category name with long parent child relationship is truncated and can not be fully seen

### What is the root cause of that problem?
The app is allowing categories with unlimited depths, if categories are nested at around 25 levels depth, we'll start to run out of space when rendering it with indentation, to the point where it's not possible to see the category name of the deepest level any more.

### What changes do you think we should make in order to solve the problem?

We should limit the maximum depths of categories nesting, I think 20 should be a good number. I don't see any realistic use case where a user would need more than 20 levels category parent-child depth.

When creating category, we can easily add a validation for the categories depth, we can extract the list of category levels by the separator (`:`), then count how many levels there is, if it's exceeding 20, show a front-end error.

### What alternative solutions did you explore? (Optional)
NA

**Comment by musabansari-1** [comment] 2024-05-30 09:06
Hi There,
Just wanted to ask whether there is a need to create nested categories with parent child relationship. Will the user be selecting only one subcategory at a time? If yes, why not display all the categories and subcategories without nesting them.

**Comment by s77rt** [comment] 2024-05-30 17:04
@truph01 Thanks for the proposal. Your RCA makes sense and so the solution 👍.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/42671#issuecomment-2138628273)

I am not totally sure if this is worth fixing but setting a limit makes sense to me. What should be the max depth?

**Comment by s77rt** [comment] 2024-05-30 17:06
@Tony-MK Thanks for the proposal. Your RCA is correct but displaying the category in one line defeats the purpose of the tree hierarchy.

**Comment by s77rt** [comment] 2024-05-30 17:13
@musabansari-1 Thanks for your interest! Please be sure to checkout the contributing guide linked above. 

> If yes, why not display all the categories and subcategories without nesting them

For better visual organization

**Comment by truph01** [comment] 2024-05-30 17:18
> What should be the max depth?

@s77rt IMO 20 is a reasonable max depth, it's small enough that will never cause this truncation issue (the deepest 20 level will be around 1/3 list width away from the right border of the list), and large enough that we don't have to worry that this limitation will impact any user.

**Comment by Julesssss** [comment] 2024-05-31 08:11
[Checking](https://expensify.slack.com/archives/C03TME82F/p1717143094367249) with the design team as we might not care about this edge case.

**Comment by Julesssss** [comment] 2024-05-31 09:06
This is quite an edge case, so I'm closing as will not fix (until we get customer reports)

**Closed by Julesssss** 2024-05-31 09:06 UTC
Labels: External, Daily, Help Wanted, Bug
