### ISSUE TITLE
[HOLD for payment 2024-08-01] Accounting - Non-reimbursable and Reimbursable expense options don't get auto focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45192] opened 2024-07-10 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44921
## Action Performed:
Pre-requisite
- Collect workspace with accounting enabled.
- NetSuite beta enabled for the user. (Use expensifail account)
- Setup NetSuite in OldDot.
1. Open the app with the pre-setup workspace.
2. Go to Accounting
3. Tap on the Advanced button.
4. Tap on Non-reimbursable expense option (Enable Custom form ID to access this field)
5. Tap on Reimbursable expense option

## Expected Result:
The input field gets auto focused

## Actual Result:
The input field does not get auto focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/602dc9c7-496a-45ac-bb38-a83c909edffe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-10 17:41
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-10 17:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by neonbhai** [comment] 2024-07-10 17:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting - Non-reimbursable and Reimbursable expense options don't get auto focused

### What is the root cause of that problem?
`NetSuitCustomFormIDPage` is missing logic to autofocus the TextInput

### What changes do you think we should make in order to solve the problem?
We will use `useAutoFocus` to configure autofocus on `NetSuitCustomFormIDPage`

**Comment by stitesExpensify** [comment] 2024-07-10 18:44
Posted here, I think that this is a direct result of this PR https://github.com/Expensify/App/pull/44921

**Comment by mananjadhav** [comment] 2024-07-10 18:51
Yes. @shubham1206agra and I will take care of this. You can assign this to us. Also this is behind beta so not a deploy blocker.

cc - @yuwenmemon

**Comment by stitesExpensify** [comment] 2024-07-15 21:14
Any update here?

**Comment by mananjadhav** [comment] 2024-07-16 16:47
I'll take care of this.

**Comment by mananjadhav** [comment] 2024-07-16 18:38
The PR is up and I've also added the fix to the Token Input page.

**Comment by mananjadhav** [comment] 2024-07-31 18:36
We can close this one out. The payout will be done centrally.

**Closed** 2024-08-02 11:45 UTC
Labels: Engineering, Daily, Awaiting Payment
