### ISSUE TITLE
[$500] mWeb - Focusing on display name inputs moves the save button downward

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27033] opened 2023-09-08 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on your avatar and open settings
2. open profile then display name
3. Now start focusing in the First name input then last name input (Try more than once)
## Expected Result: - 
The save button shouldn't move after focusing on the display name inputs
## Actual Result: 
Focusing on display name inputs moves the save button downward briefly.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/95aa00ce-cfb1-44ca-875b-10b46d2eaecf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693330266445729

https://github.com/Expensify/App/assets/43996225/683c2443-3495-4d49-91a6-6aefff61a325

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01024bce3028dfb4c7</li>
        <li>Upwork Job ID: 1701270958312742912</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 26876433</li>
<li>Ahmed-Abdella | Reporter | 26876437</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-11 17:28
### Proposal
## Problem
Focusing on display name inputs moves the save button downward

## Root cause
root cause here is a chrome default behaviour with the password bar rerendering everytime a input get focussed.
when a input blurred it dissapear the bar and quickly when the other input gains focus it rerender bar causing the jump effect. 

### Changes
Password Manager bar can be prevented either of these 2 ways
- explicitly setting type to 'search'  `ref.current.setAttribute('search')` when Browse.isChrome() and screenSmallWidth. 
- passing prop multilineto [TextInput](https://github.com/Expensify/App/blob/main/src/components/MagicCodeInput.js#L260C1-L263C1) will change the input to textarea and prevents the password manager bar to render as it is specifc to input only.

The changes

**Comment by Ahmed-Abdella** [comment] 2023-09-11 23:50
@puneetlath it is also reproducible in legal name inputs page

**Comment by eVoloshchak** [comment] 2023-09-18 16:51
This has the same root cause as https://github.com/Expensify/App/issues/23575 as @ishpaul777 [pointed out ](https://github.com/Expensify/App/issues/27033#issuecomment-1714300210)

This is a [known bug in Mobile Chrome](https://support.google.com/chrome/thread/167858494/password-bar-above-keyboard-on-android-phone-always-there?hl=en). It was reported a year ago, there seems to be no activity or plans to resolve it.

The root cause is unfixable, so we ended up applying a workaround for the magic code input only (this was causing severe glithing for a particular page with magic code input). 
Both approaches proposed by @ishpaul777 have accessibility tradeoffs, but we ultimately landed on setting the input type to 'search' using`ref.current.setAttribute('type', 'search')`. The only downside is the screen reader saying `Edit text. Search field` instead of a simple `Edit text`. This bug is present throughout the app, so I think resolving it is worth the accessibility tradeoff (though this will be fixed in Chrome at some point, do we have a process to monitor this?)

🎀👀🎀 C+ reviewed!

**Comment by puneetlath** [comment] 2023-09-19 10:18
Hmm, interesting. I'm going to raise this internally as this is an interesting tradeoff to consider.

**Comment by puneetlath** [comment] 2023-09-26 04:42
Ok I discussed internally. Let's go forward. It's not ideal, but let's do it.

**Comment by ishpaul777** [comment] 2023-09-27 08:48
hii @puneetlath @eVoloshchak, I just noticed changing the type="search" also changes the return key type to search icon, we will have to chnage the returnKeyType to "next" for the all inputs and for the last input we have to set "go", Moreover setting returnKeyType to "next" will not move the focus to next input because of this issue https://github.com/facebook/react-native/issues/31794 in React native, (work around given in issue is not working). So are we willing to make the tradeoff also?

**Comment by mvtglobally** [comment] 2023-09-28 03:19
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2023-09-28 04:03
Hmmmm, I'm not a big fan of that and starting to feel that this probably isn't worth it.

**Comment by ishpaul777** [comment] 2023-09-28 19:19
I think chrome just fixed the rerendering of password manager bar, the issue is no longer reproduceable

**Comment by eVoloshchak** [comment] 2023-10-02 09:47
Isn't reproducible for me too

https://github.com/Expensify/App/assets/9059945/192daa7f-2526-4c8f-a8f0-3679ab7c609e

**Comment by puneetlath** [comment] 2023-10-02 16:31
Thanks guys. That's great that Chrome fixed it and this is no longer an issue. Given the effort that went in here, I think a partial payment is still in order, so I'll go ahead and pay that and then we can close this out.

**Comment by puneetlath** [comment] 2023-10-03 18:55
Ok great. Payment summary: 

$50 - @Ahmed-Abdella (paid via Upwork)
$250 - @ishpaul777 - C (paid via Upwork)
$250 - @eVoloshchak - C+ (to be paid via NewDot)

@eVoloshchak let me know when you've requested and I'll close the issue out.

**Comment by eVoloshchak** [comment] 2023-10-05 09:36
@puneetlath , requested the payment, thanks!

**Comment by puneetlath** [comment] 2023-10-05 13:32
Thanks everyone!

**Closed by puneetlath** 2023-10-05 13:32 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:52
$250 payment approved for @eVoloshchak based on BZ summary.
