### ISSUE TITLE
[HOLD for Payment [2024-05-16][$250] Feature Request: Desktop app:  Clicking on `update` button shouldn't lead to re download it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39526] opened 2024-04-03 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
on the Mac Desktop app, have this "update" button update the current app directly, instead of leading you to re-download it.

## Solution:
User should be able to update without downloading again

## Context/Examples/Screenshots/Notes:
![Screenshot 2024-04-02 at 12 52 04 PM](https://github.com/Expensify/App/assets/38435837/6d5253aa-7c51-4268-807c-2cf9bf3654eb)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712096487518269

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c264c5555e17f971</li>
        <li>Upwork Job ID: 1777186397013553152</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2024-04-08 04:07
I think this can be external

**Comment by ordinall** [comment] 2024-04-08 05:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Feature Request: Desktop app: Clicking on update button shouldn't lead to re download it

### What is the root cause of that problem?
Following is the code where app is opening the download link in the browser

https://github.com/Expensify/App/blob/207385ad09ec9228e55a04f62654b47f57031548/src/libs/actions/AppUpdate/updateApp/index.desktop.ts#L5

### What changes do you think we should make in order to solve the problem?
Instead of opening the link, we can emit an update event in electron like so:

https://github.com/Expensify/App/blob/67aadf26bd90a80fe597355a3238ea5094b9654c/src/components/UpdateAppModal/index.desktop.tsx#L9

We already handle the update event in electron:

https://github.com/Expensify/App/blob/d22957d292661ef10ea539f49725c388b3237dc9/desktop/main.ts#L211

By this, the app would restart to install the update automatically.

### What alternative solutions did you explore? (Optional)
NA

**Comment by ordinall** [comment] 2024-04-08 05:10
Contributor details
Your Expensify account email: abdullah4abidansari@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e2212b454027f46b

**Comment by DylanDylann** [comment] 2024-04-08 10:50
@gijoe0295 Your proposal looks good, but how you can verify that it works well?

**Comment by DylanDylann** [comment] 2024-04-08 11:02
@gijoe0295  When testing your proposal, I see that `quitAndInstallWithUpdate` callback isn't triggered when we click `Update` button

**Comment by DylanDylann** [comment] 2024-04-10 09:32
@gijoe0295 After testing I see that ipcMain.on(ELECTRON_EVENTS.MANUALLY_CHECK_FOR_UPDATE, ....) isn't triggered after we call `window.electron.send(ELECTRON_EVENTS.MANUALLY_CHECK_FOR_UPDATE);`

**Comment by DylanDylann** [comment] 2024-04-10 09:51
@gijoe0295 Ohh, Cool

**Comment by DylanDylann** [comment] 2024-04-10 09:52
@gijoe0295's [proposal](https://github.com/Expensify/App/issues/39526#issuecomment-2044047518) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-04-15 02:04
@gijoe0295 Any update here?

**Comment by DylanDylann** [comment] 2024-04-17 00:34
@gijoe0295 Please prioritize this PR instead of proposing new issues

**Comment by DylanDylann** [comment] 2024-04-17 00:38
You proposed 2 hours ago  https://github.com/Expensify/App/issues/40316#issuecomment-2059982364

**Comment by Christinadobrzyn** [comment] 2024-05-03 10:04
Hi @DylanDylann could you provide an updated when you have a moment! Thank you!

**Comment by DylanDylann** [comment] 2024-05-03 10:05
Waiting for reviewing from @Beamanator

**Comment by Beamanator** [comment] 2024-05-05 05:42
sorry for the delay, just merged!

**Comment by Christinadobrzyn** [comment] 2024-05-14 08:59
getting ready for payment...

Payouts due:

- [ ] Contributor: $250 @gijoe0295 (Upwork offer - https://www.upwork.com/nx/wm/offer/101808656)
- [ ] Contributor+: $250 @DylanDylann (Upwork offer - https://www.upwork.com/nx/wm/offer/101808653)

Upwork job is [here](https://www.upwork.com/jobs/~01c264c5555e17f971).

Do we need a regression test for this?

**Comment by DylanDylann** [comment] 2024-05-15 15:55
Regression test
Precondition: The desktop app's outdated version and there is new update version
1. Open App
2. Press Update
3. Verify a dialog shows Update Available
4. Press Sounds good
5. Verify after a while, app is restarted
6. Press New Expensify menu >> About New Expensify
7. Verify the version is the latest production build

Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2024-05-16 08:34
Created regression test - https://github.com/Expensify/Expensify/issues/396639

Paid out based on this payment summary - https://github.com/Expensify/App/issues/39526#issuecomment-2109656088

I think we're good to close!

**Closed** 2024-05-16 08:36 UTC
Labels: Reviewing, External, Weekly, NewFeature

**Comment by DylanDylann** [comment] 2024-07-24 16:15
@Christinadobrzyn Apology for catching up late here, this issue was created from April 3 (prior to the base price change), as such according to [this announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489), it should remain as $500. So this [payment summary](https://github.com/Expensify/App/issues/39526#issuecomment-2109656088) needs adjustment.

Could you help to handle it (maybe as a bonus to the existing job), thanks!

**Comment by Christinadobrzyn** [comment] 2024-08-12 15:30
HI @DylanDylann so sorry I didn't see this comment. 

Thanks, @gijoe0295, for reaching out! I just added a $250 bonus to each of the [Upwork job payments](https://github.com/Expensify/App/issues/39526#issuecomment-2109656088) to account for the $500 price. Let me know if there's anything else!

**Comment by DylanDylann** [comment] 2024-08-12 16:37
@Christinadobrzyn No problem at all. Thanks for stepping in!
