### ISSUE TITLE
Chat - When sending a message to a new user, it is repeated and remains in the compose box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11526] opened 2022-10-02 19:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Log in any account
3. Click New chat
4. Open conversation with new user
5. Send message this new user.

## Expected Result:
Compose box must be empty after sending a message to a new user

## Actual Result:
When sending a message to a new user, it is repeated and remains in the compose box

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193472026-4fee3e6e-974b-4feb-a985-33a93bc41a4b.mp4

https://user-images.githubusercontent.com/93399543/193472027-84c60a91-33e6-4c34-b3d1-d2c7309035ee.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2022-10-04 19:33
Removing deploy blocker because fire room was created.

**Comment by mallenexpensify** [comment] 2022-10-04 23:15
@AndrewGable , it appears we have multiple 'message stays in compose box' GH issues. was this one _fixed_?  What's fireroom you mentioned above?

**Comment by AndrewGable** [comment] 2022-10-05 22:31
Fireroom: https://expensify.slack.com/archives/C04549KMEN6

This one was fixed via https://github.com/Expensify/App/pull/11552

**Comment by mallenexpensify** [comment] 2022-10-06 15:30
@youssef-lr since you're assigned to this issue, can you please do an RCA? The template is [here](https://docs.google.com/document/d/1UwXfA4ggO2h0XQJQlMEEQjT3zSphhSt12lpvuGSSFtw/edit?usp=sharing).  If you know the offending PR that caused the bug, the employee or C+ who worked on *that* PR should do the regression.  Reopening til the RCA is done

**Comment by youssef-lr** [comment] 2022-10-07 18:04
Server-side [fix](https://github.com/Expensify/Web-Expensify/pull/35072) has been deployed to staging and I can confirm I can longer reproduce this.

**Comment by mvtglobally** [comment] 2022-10-11 13:06
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-10-18 11:30
Issue not reproducible during KI retests. (Second week)

**Comment by youssef-lr** [comment] 2022-10-18 11:51
This has been fixed. Closing!

**Closed by youssef-lr** 2022-10-18 11:51 UTC
Labels: Reviewing, Engineering, Weekly
