### ISSUE TITLE
[HOLD for payment 2023-07-17] [HOLD for payment 2023-07-12] [$1000] Attachment Carousel closes on its own when a specific image is deleted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18451] opened 2023-05-04 22:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Have a chat with 2 users (User A, User B)
2. Have a few attachments posted by User B (Attachment 1, 2, 3)
3. Make User A press and open the latest attachment (Attachment 3)
4. Make User B delete Attachment 3

## Expected result:
Nothing disruptive should happen to User A’s experience. They continue to see that attachment until they close the window
## Actual result:
The whole attachment modal/carousel abruptly closes (even if they scrolled to another image)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
https://user-images.githubusercontent.com/43996225/236339219-067cdc95-1b40-4b29-9d3b-4da0cbbf4650.mov

https://user-images.githubusercontent.com/43996225/236339232-d710565b-6cf5-43ab-a40f-79c5c047dc4a.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kidroca 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683212386358629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afedd756887cbd8d</li>
        <li>Upwork Job ID: 1655921750675152896</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2023-05-09 13:05
Added the external label!

**Comment by NikkiWines** [comment] 2023-05-15 15:49
@rushatgabhane friendly bump here to review the above proposal ^^

**Comment by NikkiWines** [comment] 2023-05-18 19:24
Hmmm, for a change like this, I think it might be better to get some more thoughts on the behavior we want. I just tested this with @alex-mechler on Whatsapp and saw the follwoing after I sent two attachments. 

1.  User is not viewing the image that was deleted 

No change in behavior, user still sees the image their on 

2. User is viewing the image that was deleted 

User is scrolled to the previous attachment. 

I think we should probably follow that model and not continue to show the attachment as the "Expected Result" section of the OP shows. Gonna bring this to #expensify-open-source in slack for more discussion.

**Comment by kidroca** [comment] 2023-05-19 09:54
I agree that `AttachmentModal` should be removed from the `ImageRenderer`, though I would prefer an even more elegant approach than trying to use Context 

An approach that would allow deep linking to an attachment (I don't think App is capable of this basic feature right now)

The idea is to create a new path under the report route for attachments, something like: `/r/{reportID}/attachments/{attachmentID}` 

This way thumbnails rendered by the `ImageRenderer` would not render the modal, but a link (activated on press) to the appropriate path, which would open the Carousel with the particular attachment in place

**Comment by flaviadefaria** [comment] 2023-05-19 09:54
I'm OoO for 8 days so re-adding the BUG label, but keeping myself assigned. I'll be back at work on May 30th.

**Comment by NikkiWines** [comment] 2023-05-24 00:12
[DIscussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1684437905757379) in slack has concluded, looks like we're aligned on leaving the image up in the attachment carousel. Sorry for the delay here!

**Comment by dukenv0307** [comment] 2023-05-24 04:15
@NikkiWines so this aligns with the proposal which was [C+ reviewed](https://github.com/Expensify/App/issues/18451#issuecomment-1553190027) earlier. Are you good with that?

> The idea is to create a new path under the report route for attachments, something like: /r/{reportID}/attachments/{attachmentID}

I think the suggestion from @kidroca is great but seems out of scope for the issue, it should be more like a feature request. Even without the deeplinking it's already a quite big change.

**Comment by NikkiWines** [comment] 2023-05-25 00:45
It's a fairly large change, so I'm going to get a second opinion before approving this one! 

> I think the suggestion from @kidroca is great but seems out of scope for the issue, it should be more like a feature request. Even without the deeplinking it's already a quite big change.

I agree, that seems like a new feature 👍

**Comment by kidroca** [comment] 2023-05-25 06:47
I appreciate your input, but it seems there may be some misinterpretation of the scope of my suggestion. The addition of a modal route, as I've proposed, actually requires fewer changes than restructuring context/libraries and setting up component code for specific conditions.

While my suggestion does introduce a new feature, it serves as a more elegant and simpler solution to the core bug. We don't have to implement it all at once either. We can begin by extracting and linking the modal route with attachments, which would actually reduce complexity compared to managing another usage of the `AttachmentModal` alongside the `ReportActionsView`.

Essentially, even though this is a new feature, it offers a smoother and less convoluted path to resolving the bug compared to other proposed solutions.

The key question we need to consider isn't solely about the immediate issue at hand, but also whether we'd need to reverse these changes when we eventually consider implementing attachment linking as a feature.

If there's no plan to ever allow shareable links to attachments, then the current approach makes sense. However, if that's not the case, then we may find ourselves having to rework the changes and create a new route down the line. So why duplicate our efforts when we could set it up correctly right from the start?

**Comment by dukenv0307** [comment] 2023-05-25 07:21
> The addition of a modal route, as I've proposed, actually requires fewer changes than restructuring context/libraries and setting up component code for specific conditions.

@kidroca thanks for the explanation! I doubt that it's fewer changes, I think it's much larger. Apart from the addition of a modal route you mentioned, at least all these things that I imagine will need to be additionally handled:
1. Make sure deeplinking into the attachment works
2. When opening the attachment via link, we probably need to scroll the chat to the location of the message of that attachment so that when the attachment closes, we can see the preview
3. What if we deeplink into a not found attachment, we need to design what will be shown there
4. What to do in case we deeplink to an attachment when offline, what is the UX there, ...
5. If the attachment is only optimistically created while offline, the linking will need to show the local image
...

Thus I think it's a feature request that needs proper planning if we want to implement it, and the scope will be big. Also do we want to do all of that now, just in order to fix this issue? Moving the `AttachmentModal` out and using Context is not very complex so I think the rework is not much in case we want to do attachment linking in the future.

cc @NikkiWines

**Comment by kidroca** [comment] 2023-05-25 08:40
I understand your concerns, but it appears they are largely associated with the prospect of implementing deep linking right away, which isn't what I am suggesting. Instead, we should focus on building the modal route first and allowing the app to use it internally. This will not instantly open up a Pandora's box of potential issues related to deep linking.

Consider the Carousel component which already operates with `source: string` and `reportID: string` as serializable parameters. These parameters can be inferred from the route, meaning the existing functionality will remain unaltered. The Carousel will continue its current offline and optimistic handling, irrespective of whether these `strings` originate from a URL or from a parent component. 

The proposed step is straightforward: we simply take the Carousel component, place it in a modal route, and pass the `reportID` and `source` that are inferred from the route parameters. 

This approach not only addresses the current issue in a less complex manner but also sets us up for future extension to deep linking, should we choose to go down that path. But for now, we can resolve the present problem without opening up a multitude of potential new ones.

**Comment by dukenv0307** [comment] 2023-05-25 09:28
@kidroca I think if we have a new route but deeplinking to it doesn't work, then it's a bug on its own 😁

**Comment by NikkiWines** [comment] 2023-05-30 22:37
Sorry for the delay here, I've asked for a buddy check as mentioned in [this comment](https://github.com/Expensify/App/issues/18451#issuecomment-1562102539) but we've got a lot going on at the moment and haven't gotten a second set of eyes yet. @laurenreidexpensify bumped the request today so hopefully, someone gives it a look asap.

**Comment by chiragsalian** [comment] 2023-05-30 22:45
Currently, there is no plan of shareable links for attachments so I don't want to focus on it too much. A deep link is different than a shareable link, because a deep link will open the specific report and scroll to reportAction while a shareable link would open the attachment modal directly. We plan on working on deep linking in the near future but that should not affect the behavior of the proposals discussed here.

> We can begin by extracting and linking the modal route with attachments, which would actually reduce complexity compared to managing another usage of the AttachmentModal alongside the ReportActionsView.

I like this suggestion. But i don't see how @dukenv0307 proposal would duplicate our efforts. His proposal suggests to move AttachmentModal up a few layers i.e., to ReportActionsView.js. Once we decide our product needs shareable links for attachments then we predesign it to know exactly what we want and then on that day we either move AttachmentModal once again a few layers up and add a route or do something very different with it. 
I feel like making it too complex today without knowing about shareable links feels like it could be wasting effort. But this is my opinion so i prefer @dukenv0307 solution for now.

If we had a plan for shareable links in the near future i would have gone with your solution @kidroca 🙂

**Comment by kidroca** [comment] 2023-05-31 10:04
@chiragsalian 
I understand your perspective, and I agree that we want to avoid unnecessarily complex solutions. But I feel we may be looking at complexity from different angles, so allow me to provide a concrete comparison:

Both proposals have some common points: we need to add a single `AttachmentModal` somewhere and modify the `ImageRenderer` to trigger this modal.

The divergence lies in how we manage the `AttachmentModal`:

- @dukenv0307 suggests creating and using context to provide a `show` method, which involves creating additional logic to manage the `AttachmentModal` programmatically.

- I propose we place the `AttachmentModal` in a modal route, and use react-navigation's `navigation.navigate('ReportAttachments', { reportID, source })` to handle the modal. Since it's intended to be a stack route, closing the modal will naturally navigate us back to the place where we launched it from.

I am suggesting this approach not to discount the merits of @dukenv0307's proposal, but because I genuinely believe it's simpler—or at least not more complicated—and it leaves room for possible future extensions like deep linking. Additionally, if we decide to implement deep linking in the future, this approach would not require major code overhauls.

Let's take a moment to consider this: Even if we never need the navigation features, wouldn't it be more efficient to reuse react-navigation's built-in functionality instead of adding new code to create a specific context to manage the `AttachmentModal`?

No matter the decision, I believe I've made my case for this discussion. If the decision goes towards the other proposal, I'd like to point out that you only need `reportID` and `source`. There's no need to pass `isAuthTokenRequired` or `originalFileName` - the `AttachmentModal` is essentially a Carousel with multiple files. It has built-in logic to determine which attachments are authenticated and what the filenames are.

I value everyone's opinions in this discussion, and I'm sharing mine with the intent of reaching the most effective solution for our current issue. Thank you for considering this perspective.

**Comment by chiragsalian** [comment] 2023-06-01 19:29
Thanks for the thoughts @kidroca. I had to refresh my memory of how the carousel works. I thought with your suggestion of passing reportID and source that there would be a problem handling the prev/next attachment if we move it outside the reportActions components. 

But I see now that the AttachmentCarousal component connects to reportActions and uses that to determine prev/next attachment. So yeah I like your suggestion and thanks for sticking with it 🙂 

> If that's the case then does it work if we copy that URL then open..

i would suggest going with the simpler approach. Won't that mean clicking/pasting the URL would open the AttachmentModal as though the attachment was clicked on?

**Comment by chiragsalian** [comment] 2023-06-02 20:47
Hmm, i just read the additional issues you mentioned. A lot of it talks about deep linking.

Okay i want to step back for a second and talk about Expensify's plan for deep linking - The plan is that a URL like `r/{reportID}/{reportActionID}` is shared. The URL will have its own mini-preview for comments/attachments/expenses etc. If a user clicks on it, it will open the report and scroll to the specific reportAction. There is no plan to open the attachment directly besides from its source in our deep linking pipeline.

I think i can see us using either solution. I'm not too well versed with the react nuances to know which one is more efficient/performant though.

@dukenv0307 to answer some of your [concerns](https://github.com/Expensify/App/issues/18451#issuecomment-1562407251) in order here assuming we go with the navigation route,
1. Yes. 
2. No we should not scroll or open the report in the main chat view. That will be handled by the deep linking project. I don't really see kidroca suggestion to be related to deep linking. Its a link that opens the AttachmentModel.
3. We would reuse this which we currently have elsewhere in newdot.
![image](https://github.com/Expensify/App/assets/14356145/f0bda949-a24f-4c98-9c2d-24b03a5b8518)
(This can also be a separate follow up issue.)
4. Not in the scope of this issue so that means we keep whats currently there, i.e., an infinite spinner when offline and image is not cached
5. Also not in the scope of this issue, currently we do not show local image, the upload returns a URL and user only views this URL when they click the image. If we want to make this use local image it would be a separate issue.

I think kidroca solution is easier though because we won't have this part,
> which involves creating additional logic to manage the AttachmentModal programmatically.

**Comment by chiragsalian** [comment] 2023-06-02 22:05
When you say let's get it rolling which solution are you in favor of? 🙂

**Comment by NikkiWines** [comment] 2023-06-03 00:18
Thanks for lending your expertise @chiragsalian! Sounds like we're aligned on moving forward with @kidroca's solution 🚀

**Comment by kidroca** [comment] 2023-06-13 16:04
PR has conflicts, I'll be working on resolving them soon

**Comment by flaviadefaria** [comment] 2023-06-23 20:38
@kidroca @allroundexperts @rushatgabhane can you please give an update? Who is the C+ now responsible for this?

**Comment by flaviadefaria** [comment] 2023-06-26 11:10
Perfect, thanks for clarifying @allroundexperts!

**Comment by kidroca** [comment] 2023-06-27 21:03
The PR is approved but on HOLD due to a feature freeze: https://github.com/Expensify/App/pull/20167#pullrequestreview-1496163780

**Comment by chiragsalian** [comment] 2023-06-30 23:16
Merged the PR. As discussed in the PR. The URL does not update while switching between attachments and @kidroca requested if he can do this in a follow-up PR once his current PR was stable so that it's easier to test/review it and I said sure.

**Comment by kidroca** [comment] 2023-07-01 08:37
I'm a bit puzzled about the time calculation between when the PR was assigned and when it got merged:

> when @kidroca got assigned: 2023-06-03 00:18:28 Z
> when the PR got merged: 2023-06-30 23:14:32 UTC
> days elapsed: 19

By my count, there are actually 26 or 27 days between the 3rd and 30th of June, not 19. Could you shed some light on how this time was calculated?

Just wanted to add that I pushed the PR within 2 days of getting assigned. The review took some time due to stuff outside of my control. Also, any merge conflicts that came up were fixed promptly on my end.

I confirm that I'll be posting a follow-up PR soon to address the remaining updates regarding the URL.

**Comment by flaviadefaria** [comment] 2023-07-14 09:34
@kidroca please fill out the checklist above so that i can process the payment - thanks!

**Comment by kidroca** [comment] 2023-07-14 10:36
Thanks for the bump @flaviadefaria 

I don't think we need a regression test, because the component structure and usage changed in a way that prevents this kind of bug from happening again, furthermore it's rare, it's not super easy to test and it does not affect important functionality

**Comment by flaviadefaria** [comment] 2023-07-17 09:27
Ok this is what I think needs to be issued as payment:

>Merged PR more than 9 business days after assignment - 50% penalty

@kidroca = $1000 - 50% penalty = $500
@allroundexperts = $1000 - 50% penalty = $500

It seems fair to me to remove the penalty due to the initial C+ getting sick so will issue payment for the full $1000 for each of you.

@allroundexperts do you request payment via Expensify or should I pay you via UpWork?

**Comment by flaviadefaria** [comment] 2023-07-17 10:01
@kidroca I just sent you an offer. I also just realized you reported this bug so will issue a bonus of $250 to account for that once you accept the offer.

**Comment by anmurali** [comment] 2023-07-17 15:59
@allroundexperts is paid

**Closed** 2023-07-18 10:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
