### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Android - Track expense - Self DM with actionable whispers auto scrolls down when scrolling up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42967] opened 2024-06-02 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**(https://expensify.testrail.io/index.php?/tests/view/4591846)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify
2. Go to Self DM (better use a new account with no chat in self DM)
3. Track two or three expenses without dismissing actionable whisper for each expense
4. Scroll up

## Expected Result:
Chat will not auto scroll down when scrolling up

## Actual Result:
Chat with actionable whispers auto scrolls down when scrolling up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/d12081b7-fca7-4706-bbb1-ba7d4e093d16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01853953eae54c5779</li>
        <li>Upwork Job ID: 1797797752162476032</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102590743</li>
<li>c3024 | Contributor | 102590745</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by lanitochka17** [comment] 2024-06-02 16:58
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-06-02 16:59
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by c3024** [comment] 2024-06-03 20:07
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Scrolling up scrolls back down if the last report action is an unresolved actionable whisper on android.

### What is the root cause of that problem?
Here,
https://github.com/Expensify/App/blob/e6c89d9d06f77eca57faa8ef20b236bbfdbc1153/src/components/FlatList/index.android.tsx#L26
and
https://github.com/Expensify/App/blob/e6c89d9d06f77eca57faa8ef20b236bbfdbc1153/src/components/FlatList/index.android.tsx#L39
set the `scrollPosition` causing rerenders of `ReportScreen`, children and `useReportScrollManager`

Here,
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/hooks/useReportScrollManager/index.native.ts#L11
`scrollToIndex` is created as a new instance because it is not enclosed with useCallback and this `useEffect` gets triggered
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/pages/home/report/ReportActionItem.tsx#L365-L373
Here for whispers we use the `action.originalMessage.resolution` for `prevActionResolution`
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/pages/home/report/ReportActionItem.tsx#L223
and this `resolution` field does not exist for an unresolved whisper so `prevActionResolution` is `undefined` but it is compared with a value with fallback as `null` here
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/pages/home/report/ReportActionItem.tsx#L370
so though both resolution values here are `undefined` the inequality does not fail because the fallback value of `null` is taken for `action.originalMessage.resolution` on the right hand side because `action.originalMessage.resolution` is `undefined` and the inequality succeeds and it scrolls to index 0.
### What changes do you think we should make in order to solve the problem?
We should remove the fallback value of `null` here 
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/pages/home/report/ReportActionItem.tsx#L370
then the inequality fails and report is not scrolled to index 0.

This `useEffect` is applicable only for actionable whispers
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/pages/home/report/ReportActionItem.tsx#L366
and for actionable whispers `prevActionResolution` value is taken as `undefined` with no fallback
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/pages/home/report/ReportActionItem.tsx#L223
So, this dropping of `null` here
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/pages/home/report/ReportActionItem.tsx#L370
should not break anything.

### What alternative solutions did you explore? (Optional)
While the above change fixes the issue, we should also wrap this with a `useCallback` to ensure it is recreated only when the dependencies (the flatlist ref here) change
https://github.com/Expensify/App/blob/d3434cb1c37c217e19028fe9cf430b6b4ecfd836/src/hooks/useReportScrollManager/index.native.ts#L11
This change without the above mentioned change (that is removal of `null`) also fixes the bug.

**Comment by akinwale** [comment] 2024-06-04 02:37
We can move forward with @c3024's [proposal](https://github.com/Expensify/App/issues/42967#issuecomment-2146025412) here.

🎀👀🎀 C+ reviewed.

**Comment by c3024** [comment] 2024-06-05 05:24
@akinwale PR ready for review.

**Comment by stephanieelliott** [comment] 2024-06-11 21:03
PR was merged to main, should go to staging on next deploy!

**Comment by akinwale** [comment] 2024-06-19 02:09
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This case wasn't handled.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify app on Android.
2. Open the global create menu (FAB) and select Track expense.
3. Do not select any options from the whisper in the self-DM.
4. Track two or more additional expenses in the self-DM and do not select any of the whisper options.
5. Scroll to the top of the self-DM with the tracked expenses.
6. Verify that the self-DM does not autoscroll to the bottom to display the last whisper in the report.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-06-19 02:11
@stephanieelliott The PR was originally deployed to production on [2024-06-11](https://github.com/Expensify/App/pull/43085#issuecomment-2161775969), so the actual payment date is 2024-06-18 (since the bot got confused).

**Comment by stephanieelliott** [comment] 2024-06-20 22:04
Oh, thanks @akinwale! 

Summarizing payment on this issue: 

 - Contributor: @c3024 $250 PAID via Upwork
 - Contributor+: @akinwale $250 PAID via Upwork
 
 Upwork job is here: https://www.upwork.com/jobs/~01853953eae54c5779

Regression test here: https://github.com/Expensify/Expensify/issues/406478

**Closed by stephanieelliott** 2024-06-20 22:04 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
