### ISSUE TITLE
[Theme Switching] 🐛 (Status Bar) iOS - Login - Time and wifi indicators are black in dark mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33309] opened 2023-12-19 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out
2. Open the app

## Expected Result:
Time and wifi indicators should be white

## Actual Result:
Time and wifi indicators are black in dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6320042_1703008936419!1](https://github.com/Expensify/App/assets/78819774/a5a677fa-6974-4762-a494-166dcabbdffd)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2023-12-19 20:59
Production: 

![viber_image_2023-12-19_15-59-04-843](https://github.com/Expensify/App/assets/78819774/fc04c173-5ce4-414e-b3f2-31304f1679d9)

**Comment by marcochavezf** [comment] 2023-12-20 00:20
I'm not able to reproduce it in the version 1.4.14.1, also I think this is part of the iOS system

https://github.com/Expensify/App/assets/6829422/1f876ae4-2141-4beb-9220-b91d3e9547cf

**Comment by situchan** [comment] 2023-12-20 00:22
I am not able to reproduce either.
Btw, this is follow-up of theme-switching live. Not deploy blocker
cc: @grgia

**Comment by marcochavezf** [comment] 2023-12-20 00:23
I'm going to remove the deploy blocker label

**Comment by grgia** [comment] 2024-01-02 23:03
discussing in https://github.com/Expensify/App/issues/33674

**Comment by grgia** [comment] 2024-01-05 18:49
should be fixed, closing

**Closed by grgia** 2024-01-05 18:49 UTC
Labels: Engineering, Daily, Overdue
