### ISSUE TITLE
[HOLD for payment 2024-07-10] [$500] Workspace switcher - Selection disappears after erasing character with workspace selected

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36140] opened 2024-02-08 12:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-38.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- There is at least 8 workspaces.

~1. Go to staging.new.expensify.com~
~2. Open workspace switcher.~
~3. Select a workspace.~
~4. Open workspace switcher.~
~5. Type a valid search term.~

Latest reproduction steps: https://github.com/Expensify/App/issues/36140#issuecomment-2173797760
- Lets say the selected workspace name is `Workspace 1`

1. Enter `Work`, Observe the option is still focused.
2. Add a character `Workk`
3. Remove the extra `k`
4. Observe the first option is not focused.

## Expected Result:
The selection highlight will remain on the first item in the list.

## Actual Result:
The selection highlight moves to the second item in the list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ce2322fc-b895-4b31-babb-acc811f007ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e72ec1b032f8020</li>
        <li>Upwork Job ID: 1755568798530035712</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
<li>Krishna2323 | Contributor | 0</li>
<li>hoangzinh | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment] 2024-02-08 12:27
We think that this bug might be related to #wave8-collect-admins
 @zanyrenney

**Comment by situchan** [comment] 2024-02-18 14:35
I am interested in reviewing this as C+

**Comment by kevinksullivan** [comment] 2024-02-22 19:14
assigning @situchan for C+. Let us know what you tihnk of the proposals please!

**Comment by situchan** [comment] 2024-02-26 15:26
2 proposals are in review

**Comment by rlinoz** [comment] 2024-02-28 12:45
Thanks, assigning @Krishna2323 !

**Comment by rlinoz** [comment] 2024-03-05 14:32
@Krishna2323 I don't see where the discussion is happening, but I think this is fixed in main, if you want to pull the changes.

**Comment by rlinoz** [comment] 2024-03-08 11:33
@Krishna2323 @situchan can we consider migrating the workspace switcher to use `SelectionList` as a fix?

**Comment by situchan** [comment] 2024-03-08 12:12
> @Krishna2323 @situchan can we consider migrating the workspace switcher to use `SelectionList` as a fix?

Sure, if no one is working on this migration already

**Comment by rlinoz** [comment] 2024-03-08 12:31
Posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1709901064216199?thread_ts=1709156803.359359&cid=C01GTK53T8Q)

**Comment by rlinoz** [comment] 2024-03-12 14:01
From the thread above we can proceed with migrating the workspace switcher to use `SelectionList`

**Comment by situchan** [comment] 2024-03-19 21:04
yes, please make sure that similar regressions don't happen:
[New Chat page list refactor](https://github.com/Expensify/App/pull/34356) was reverted because of [multiple regressions](https://github.com/Expensify/App/pull/34356#issuecomment-1992606615)

**Comment by situchan** [comment] 2024-03-26 17:17
Sorry I think I am not able to get to this sooner. Please reassign.

**Comment by rlinoz** [comment] 2024-03-27 12:07
Disregard the last melvin message, @hoangzinh got assigned as a C+ to this.

Thanks for taking this!

**Comment by rlinoz** [comment] 2024-04-22 11:50
Hey @Krishna2323 sorry for the timeline of events on this one.

Let me add someone from the design team to help here.

**Comment by rlinoz** [comment] 2024-04-22 11:52
Hey @dubielzyk-expensify can you help us here?

Apparently we changed a little bit how the workspace switcher looks like, so what do you think is the best behavior for selection while searching?

https://github.com/Expensify/App/issues/36140#issuecomment-2069026547

**Comment by dubielzyk-expensify** [comment] 2024-04-23 00:52
Even the recording in the original description looks more correct visually. But obviously the selection highlight is wrong. To me it seems like that was the only issue, but now the search has moved around? Again, I might've missed something here. cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-04-23 00:59
I don't recall a conversation to move the search bar to the top of the page. I agree it should be in-line beneath "Workspaces" really.

**Comment by dannymcclain** [comment] 2024-04-23 13:08
Definitely agree. We need to keep it close to the list so the two are visually connected. At the top of the page just feels kinda confusing.

**Comment by rlinoz** [comment] 2024-04-23 18:45
Cool, I think we should create an issue to handle that specifically

Can I use this 2 images taken from [here](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=1199-46489&mode=design&t=E5XzYzsZsmQMwrYT-4) as examples?

![image](https://github.com/Expensify/App/assets/5201282/ad918992-0039-4e04-97f2-2572a79b9307)
![image](https://github.com/Expensify/App/assets/5201282/f68ae5ce-da20-49b6-adfd-fd13495f4def)

**Comment by dannymcclain** [comment] 2024-04-23 19:18
@rlinoz those look a little outdated, but I think [these ones](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3927-68503&mode=design&t=lqoaIVmayAi4pSde-11) should be good to use as reference.

![image](https://github.com/Expensify/App/assets/7516624/46478ddb-2b27-4d89-b997-f65d65015121)

**Comment by rlinoz** [comment] 2024-04-23 20:06
Issue is here: https://github.com/Expensify/App/issues/40826

**Comment by rlinoz** [comment] 2024-04-23 20:07
@Krishna2323 @hoangzinh regarding the original comment, I believe we all agree that the highlight should be the one after the fix here https://github.com/Expensify/App/issues/36140#issuecomment-2069026547

**Comment by rlinoz** [comment] 2024-04-25 22:16
Hmm is that because the other issue may change the list content and that affects the selection?

**Comment by rlinoz** [comment] 2024-04-26 12:35
That is fair, thanks for catching that.

**Comment by rlinoz** [comment] 2024-06-17 15:31
I kind of reproed it, but I can't anymore..

https://github.com/Expensify/App/assets/5201282/4efab9b3-83f1-4e6f-b533-038c6b485117

**Comment by rlinoz** [comment] 2024-06-21 14:49
Yeah, sorry for all the confusion in this issue, I can reproduce with your steps and the solution looks good, let's fix it.

I will also update the issue title to better acknowledge what we are doing

**Comment by kevinksullivan** [comment] 2024-07-15 23:18
@hoangzinh please complete the checklist in order to receive payment. Thanks

**Comment by kevinksullivan** [comment] 2024-07-19 23:09
all set

**Closed by kevinksullivan** 2024-07-19 23:09 UTC
Labels: External, Engineering, Daily, Design, Overdue, Awaiting Payment, Bug
