### ISSUE TITLE
[$500] Room settings-Members added/deleted in a room in offline mode are not grayed out/crossed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31764] opened 2023-11-22 23:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Open any room (or create it) -> Members
4. Turn off the internet connection
5. Invite some new members
6. Delete some members

## Expected Result:
Members added offline are grayed out
Members removed offline are crossed out
We expect the same behavior as when removing/adding members offline in the workspace

## Actual Result:
Members added offline are NOT grayed out
Members removed offline are NOT crossed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1d84f8fc-42ce-431d-8b8b-f9362bd7eb8d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f3cdcfb2a96a853</li>
        <li>Upwork Job ID: 1727466899004616704</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27957669</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @deetergp</details>

**Comment by thirtyfoura34** [comment] 2023-11-23 03:36
Contributor details
Your Expensify account email: thirtyfoura34@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01903eeeb0b0665a65

**Comment by thirtyfoura34** [comment] 2023-11-23 03:37
Contributor details
Your Expensify account email: [thirtyfoura34@gmail.com](mailto:thirtyfoura34@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01903eeeb0b0665a65

**Comment by thirtyfoura34** [comment] 2023-11-23 03:39
Contributor details
Your Expensify account email: thirtyfoura34@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01903eeeb0b0665a65

**Comment by burczu** [comment] 2023-11-27 13:26
Not overdue, I'll be reviewing this issue soon.

**Comment by burczu** [comment] 2023-12-05 10:03
Ahh, right @tienifr... Thanks for pointing this out. 

@bfitzexpensify so I think we should switch to `Internal` here to get an opinion from an internal engineer. What do you think?

**Comment by bfitzexpensify** [comment] 2023-12-05 19:22
@deetergp what do you think?

**Comment by deetergp** [comment] 2023-12-07 00:50
Hey @burczu, your suggestion sounds like a good one 👍  Do you happen to know which issue it was where we similar changes for Workspaces? If I can find the the internal issue related to those changes, it will make my life a lot easier, and speed up the process considerably.

**Comment by deetergp** [comment] 2023-12-19 16:21
Will try to dig back into this one today.

**Comment by burczu** [comment] 2023-12-22 13:42
Hey @bfitzexpensify! I'll be OOO till January 6th, and right after that I'm leaving the C+ role and joining Waves. Could you please assign another C+ engineer to handle this issue from now on? Thanks.

**Comment by deetergp** [comment] 2023-12-27 00:26
I'll try to dig back into this one tomorrow.

**Comment by alitoshmatov** [comment] 2024-01-02 11:05
Can anyone inform me with current status, and our next step. Thank you in advance.

**Comment by deetergp** [comment] 2024-01-03 06:15
I"m still catching up from being OOO, but will dig into this in the morning.

**Comment by deetergp** [comment] 2024-01-08 23:26
Getting back into this one. @tienifr Do you happen to remember where added the `roomMembers` onyx key for WS? https://github.com/Expensify/App/issues/31764#issuecomment-1839935418

**Comment by bfitzexpensify** [comment] 2024-01-11 18:07
I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.

- @deetergp is currently working on a solution

**Comment by Christinadobrzyn** [comment] 2024-01-16 15:27
I'm ooo for this week but still monitoring this, looks like we're working on a solution.

**Comment by deetergp** [comment] 2024-01-17 00:52
Thanks for the reply @tienifr. I'll pick this back up in the morning.

**Comment by deetergp** [comment] 2024-01-17 22:51
Okay, first off, forgive me for needing to be caught up on this, but I'm looking at what's in Onyx when we've got a room with a few members and we've got two separate lists of room participants: their accountIDs are at `report_<room reportID>.participantAccountIDs` and their emails at `report_<room reportID>.participants`. Is there a reason we can't use those to achieve the same goal, without any additional BE changes?

**Comment by Christinadobrzyn** [comment] 2024-01-22 17:22
Looks like we're reviewing @tienifr proposal https://github.com/Expensify/App/issues/31764#issuecomment-1903235661

**Comment by Christinadobrzyn** [comment] 2024-01-23 17:37
@deetergp could you check out this when you have a moment https://github.com/Expensify/App/issues/31764#issuecomment-1903235661

Also, should we move this to weekly or is it okay to keep as daily?

**Comment by deetergp** [comment] 2024-01-23 20:58
@tienifr Thanks for reminding me to re-check your proposal. Let's go with solution #2 and use what we've already got in Onyx.

@Christinadobrzyn let's go ahead and leave it daily.

**Comment by Christinadobrzyn** [comment] 2024-01-29 16:00
working on a PR

**Comment by Christinadobrzyn** [comment] 2024-02-06 23:50
working on PR - https://github.com/Expensify/App/pull/35355

**Comment by deetergp** [comment] 2024-02-24 00:25
I think the PR is getting pretty close.

**Comment by deetergp** [comment] 2024-03-05 19:01
Still some discussion going on in the PR.

**Comment by Christinadobrzyn** [comment] 2024-03-20 07:07
working on PR - on hold for https://github.com/Expensify/App/issues/16078

**Comment by Christinadobrzyn** [comment] 2024-03-22 00:38
Hi @tienifr! Thanks for reaching out about the extra work - what bonus do you think would be fair for the extra work you did?

**Comment by Christinadobrzyn** [comment] 2024-03-22 05:46
Sounds good @tienifr! We'll add a $500 bonus on payout (you might need to remind us)

**Comment by deetergp** [comment] 2024-03-25 15:48
> It's not my regression

Can you elaborate?

**Comment by deetergp** [comment] 2024-03-25 16:02
Ah, nice. Thanks for the extra context @tienifr.

**Comment by Christinadobrzyn** [comment] 2024-04-08 03:21
Yes, thanks for catching that @tienifr - looks like the payment trigger didn't happen. 

Payouts due:

- [X] Contributor: $500 @tienifr + [$500 bonus ](https://github.com/Expensify/App/issues/31764#issuecomment-2014400863) - (paid in Upwork - https://www.upwork.com/nx/wm/offer/27957669) 

Upwork job is [here](https://www.upwork.com/jobs/~013f3cdcfb2a96a853) the posting is now closed.

Internal so no regression test. I think this can be closed. Let me know if I missed anything!

**Comment by alitoshmatov** [comment] 2024-04-08 07:35
@Christinadobrzyn I worked as C+, I also require payment

**Comment by Christinadobrzyn** [comment] 2024-04-09 02:38
Ah so sorry for missing that @alitoshmatov - thank you for letting me know, can you accept the Upwork offer here - https://www.upwork.com/ab/applicants/1777525996418326528/offers

**Comment by Christinadobrzyn** [comment] 2024-04-11 02:57
Thanks, @alitoshmatov - I paid out the Upwork job based on this payment summary - https://github.com/Expensify/App/issues/31764#issuecomment-2041791986

Closing! Feel free to let me know if I missed anything else!

**Closed by Christinadobrzyn** 2024-04-11 02:57 UTC
Labels: Reviewing, External, Engineering, Weekly, Internal, Bug
