### ISSUE TITLE
[$500] IOU - In distance request paid transaction,receipt delete option is shown.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29475] opened 2023-10-12 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on any Workspace chat
3. Tap request money-- distance
4. Enter start and finish waypoints
5. Tap next
6. Tap request amount
7. Tap on the transaction
8. Tap pay elsewhere and pay it
9. Tap on the receipt and open 3dots
10. Tap delete receipt

## Expected Result:
In paid transaction, delete option must not be shown or if shown, receipt must be deleted if tapped on delete

## Actual Result:
In paid transaction,receipt delete option is shown. But, tapping on delete, neither receipt is not deleted nor does not trigger any action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/89a4525d-3ae7-4ac6-8b2e-cfc6850f70b6

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013adc8210e018e835</li>
        <li>Upwork Job ID: 1712627607226855424</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 27170142</li>
</ul></li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-10-12 23:53
@ishpaul777 are you available to submit a PR right now?

**Comment by jasperhuangg** [comment] 2023-10-13 00:04
@ishpaul777 Give me a second while I get another set of eyes on your proposal

**Comment by mountiny** [comment] 2023-10-13 08:49
CPed to staging

**Comment by peterdbarkerUK** [comment] 2023-10-17 10:47
Not 100% sure if I'm best manually updating this to hold-for-payment 2023-10-20, or adding it to [this one](https://github.com/Expensify/App/issues/29452). Checked in with @joekaufmanexpensify , switching to daily so I keep it up to date.

**Comment by peterdbarkerUK** [comment] 2023-10-24 13:47
@ishpaul777 - the root cause here as the same as https://github.com/Expensify/App/issues/29452 right?

**Comment by peterdbarkerUK** [comment] 2023-10-24 14:32
Thanks for the quick clarification. 

Summarizing payouts for this issue:

Contributor: @ishpaul777 $750 (inc. urgency bonus)

Upwork job: https://www.upwork.com/nx/wm/workroom/35123916/overview

**Comment by peterdbarkerUK** [comment] 2023-10-24 14:32
Ah shoot, I was confused about the step-ordering here across the two issues - I should not have paid this out until [this BZ Checklist](https://github.com/Expensify/App/issues/29452#issuecomment-1765335159) was completed. Keeping this open with an eye on that in the meantime.

**Comment by peterdbarkerUK** [comment] 2023-10-24 14:37
(I think it's fine as that checklist is waiting on the C+ - I'm just leaving a clear paper trail to save my poor, poor brain from having to remember things)

**Closed** 2023-11-06 17:16 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
