### ISSUE TITLE
[HOLD for payment 2023-01-25] Date inputs allow 5 to 6 digits as year in Manual journey of Connect Bank Account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13837] opened 2022-12-27 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any workspace
3. Choose Connect Bank Account
4. Choose Connect manually
5. Go to step 2 of the Form
6. Enter random values of "Incorporation date" and you'll notice the year part of the value can go upto 6 digits

## Expected Result:
Year value should only allow 4 digits

## Actual Result:
User can enter upto 6 digits

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/43996225/209688937-9df83a65-9f83-4890-ae52-853a0ba53b73.png)

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/209688979-3e3032cd-7287-4bfe-8341-225d91293617.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672076005803659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a092ee76a867ed09</li>
        <li>Upwork Job ID: 1613242559970676736</li>
        <li>Last Price Increase: 2023-01-11</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment] 2023-01-11 18:32
Oh yes, I've seen this one! Will take a look.

**Comment by Pujan92** [comment] 2023-01-12 02:23
**Proposal**

It seems `moment` will allow the 6 digits for the year and it considers it as a valid, if we pass `strict` to true in moment constructor then 5/6 digits in the year will be considered invalid but still it can takes 6 digit internally to overwrite year in the input text.
We can provide a max date to the datepicker which will resolve this issue.

```diff
diff --git a/src/CONST.js b/src/CONST.js
index ef02585f6..277c4daac 100755
--- a/src/CONST.js
+++ b/src/CONST.js
@@ -41,6 +41,7 @@ const CONST = {
     DATE: {
         MOMENT_FORMAT_STRING: 'YYYY-MM-DD',
         UNIX_EPOCH: '1970-01-01 00:00:00.000',
+        MAX_DATE: '9999-12-31',
     },
     SMS: {
         DOMAIN: '@expensify.sms',
diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index 2983ce762..29e2ee93c 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js
@@ -30,6 +30,7 @@ class DatePicker extends React.Component {
     componentDidMount() {
         // Adds nice native datepicker on web/desktop. Not possible to set this through props
         this.inputRef.setAttribute('type', 'date');
+        this.inputRef.setAttribute('max', CONST.DATE.MAX_DATE);
         this.inputRef.classList.add('expensify-datepicker');
     }
```

**Comment by yuwenmemon** [comment] 2023-01-12 02:50
Ah so simple! This makes sense to me. @mollfpr thoughts?

**Comment by fedirjh** [comment] 2023-01-12 02:52
#### Proposal 

we can pass the expected format parameter to `moment` when parsing the date, this will make `asMoment.isValid`  validates the format too before trigger `onInputChange`

```diff
diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index 2983ce7620..cd06957c4e 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js
@@ -43,7 +43,7 @@ class DatePicker extends React.Component {
             return;
         }
 
-        const asMoment = moment(text);
+        const asMoment = moment(text, CONST.DATE.MOMENT_FORMAT_STRING);
         if (asMoment.isValid()) {
             this.props.onInputChange(asMoment.format(CONST.DATE.MOMENT_FORMAT_STRING));
         }
```

**Comment by tienifr** [comment] 2023-01-12 02:53
# Proposal

Solution: I'll use `moment` strict mode so that the 6-digit year will not pass the validation

```diff
diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index 2983ce7620..8f114fb56c 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js
@@ -43,7 +43,7 @@ class DatePicker extends React.Component {
             return;
         }
 
-        const asMoment = moment(text);
+        const asMoment = moment(text, true);
         if (asMoment.isValid()) {
             this.props.onInputChange(asMoment.format(CONST.DATE.MOMENT_FORMAT_STRING));
         }
```

**Comment by mollfpr** [comment] 2023-01-12 03:04
@yuwenmemon Yes, @Pujan92 [proposal](https://github.com/Expensify/App/issues/13837#issuecomment-1379730211)'s looks good to me and it's working fine.

@fedirjh @tienifr Thank you for the proposals but as my test, the year still can be typed into 6 digits.

🎀 👀 🎀 C+ reviewed!

**Comment by tienifr** [comment] 2023-01-12 04:35
@mollfpr As far as I know the `max` attribute for input date does not work on Safari, I've also tried that approach but faces that issue. You might want to test that on Safari as well.

If you think we might need an alternative approach, would be good if you can provide more information on how you reproduce this `the year still can be typed into 6 digits.`

**Comment by yuwenmemon** [comment] 2023-01-12 04:54
@Pujan92 Would you be able to test/demonstrate your solution on Safari?

**Comment by mollfpr** [comment] 2023-01-12 05:00
@tienifr delete the date and months, click in the years.

https://user-images.githubusercontent.com/25520267/211981260-d0c4bf94-976c-4260-ba7a-0be9dd4e501b.mov

**Comment by mollfpr** [comment] 2023-01-12 05:02
@yuwenmemon @Pujan92 proposal not working on Safari 😬


https://user-images.githubusercontent.com/25520267/211981520-9abfe9df-eade-48e0-baa0-ddf513205efa.mov

**Comment by Pujan92** [comment] 2023-01-12 05:32
oh, yes. Seems the max attribute isn't supported in Safari yet.

**Comment by Pujan92** [comment] 2023-01-12 05:42
Yes, safari and firefox provide partial support for date.

https://caniuse.com/input-datetime
<img width="499" alt="Screenshot 2023-01-12 at 11 12 30 AM" src="https://user-images.githubusercontent.com/14358475/211986827-112bdd5d-a51c-4b95-b409-022fc5196c33.png">

**Comment by yuwenmemon** [comment] 2023-01-12 20:54
I tried exploring using `maxLength` on the DatePicker or TextInput - could that be a possible avenue to getting this thing to stop at 4 digits?

**Comment by yuwenmemon** [comment] 2023-01-12 20:58
Also, @Pujan92's proposal is better than nothing and makes a bunch of sense to me. So even if we can't get it to work on Safari I still think it's worth implementing.

**Comment by fedirjh** [comment] 2023-01-12 21:49
@0xmiroslav i agree with you . I was just about to comment that. This issue is relative to browser and can't be fixed.

**Comment by tienifr** [comment] 2023-01-13 01:10
# Updated Proposal

Since now we allow a 99% compromising solution, I updated my proposal
```diff
diff --git a/src/CONST.js b/src/CONST.js
index 8cd279eedb..e49385b8e4 100755
--- a/src/CONST.js
+++ b/src/CONST.js
@@ -46,6 +46,7 @@ const CONST = {
     DATE: {
         MOMENT_FORMAT_STRING: 'YYYY-MM-DD',
         UNIX_EPOCH: '1970-01-01 00:00:00.000',
+        MAX_DATE: '9999-12-31',
     },
     SMS: {
         DOMAIN: '@expensify.sms',
diff --git a/src/components/DatePicker/index.js b/src/components/DatePicker/index.js
index 2983ce7620..e25cc90ce1 100644
--- a/src/components/DatePicker/index.js
+++ b/src/components/DatePicker/index.js
@@ -30,6 +30,7 @@ class DatePicker extends React.Component {
     componentDidMount() {
         // Adds nice native datepicker on web/desktop. Not possible to set this through props
         this.inputRef.setAttribute('type', 'date');
+        this.inputRef.setAttribute('max', CONST.DATE.MAX_DATE);
         this.inputRef.classList.add('expensify-datepicker');
     }
 
@@ -43,7 +44,7 @@ class DatePicker extends React.Component {
             return;
         }
 
-        const asMoment = moment(text);
+        const asMoment = moment(text, true);
         if (asMoment.isValid()) {
             this.props.onInputChange(asMoment.format(CONST.DATE.MOMENT_FORMAT_STRING));
         }
```

Besides `the edge case of date and month values are cleared.`, this also has another issue that I'm not sure we'd like to fix: On Firefox/Safari, even when we type date and month first, when we type the year there's an inconsistent behavior: 
After the first 4 chars for year is typed in, when you type the 5th, 6th char it will not change any thing, but the 7th char you typed will reset the year to `000x`.

I've tried a way to fix that as well but it's more like a work around to patch the browser behavior in this case. Not sure if that's worth fixing.

**Comment by Pujan92** [comment] 2023-01-13 02:09
@tienifr seems your proposal already covered earlier with my proposal + @0xmiroslav suggestion.

**Comment by tienifr** [comment] 2023-01-13 02:52
@Pujan92 yeah, it's a combination of your and my proposals

**Comment by yuwenmemon** [comment] 2023-01-13 06:35
@Pujan92 can you make a PR for the fix?

Everyone else, @arielgreen and I will discuss how to divvy up compensation, if applicable.

**Comment by Pujan92** [comment] 2023-01-13 06:37
Sure @yuwenmemon

**Comment by arielgreen** [comment] 2023-01-15 23:37
@Pujan92 @0xmiroslav @tienifr since this was a collaborative effort, how does this sound for payment?

- $500 to @Pujan92 (also eligible for the bonus for the timely PR)
- $250 to @0xmiroslav 
- $250 to @tienifr 

Can you throw a 👍 if this sounds fair to you?

**Comment by tienifr** [comment] 2023-01-16 02:17
@arielgreen I think the split is fine. However if there's any bonus for the timely PR, it should be split as well. Since any of the 3 could have been able to do the timely PR if he's chosen to implement the PR. And @Pujan92 already got the (2x) bigger original split for the added effort of implementing the PR.
If the bonus only goes to the one implementing the PR, then the original split should be equal (a.k.a 1/3 for each).
Just my 2 cents.

**Comment by Pujan92** [comment] 2023-01-16 04:47
> **Proposal**
> 
> **It seems `moment` will allow the 6 digits for the year and it considers it as a valid, if we pass `strict` to true in moment constructor then 5/6 digits in the year will be considered invalid but still it can takes 6 digit internally to overwrite year in the input text.** We can provide a max date to the datepicker which will resolve this issue.

@tienifr just to point out I already mentioned your solution in my initial proposal with the drawback. Only thing I wasn't aware of the safari/firefox date support issue for which we would need to consider that as a partial solution.

**Comment by tienifr** [comment] 2023-01-16 06:19
@Pujan92 I interpret it as dismissing that solution, much like when I point out your proposal's potential issue [here](https://github.com/Expensify/App/issues/13837#issuecomment-1379802834), rather than you proposing an alternate proposal (which should have accompanied code change and clear indication of such, ...). So I assume my proposal is the first one recommending that solution.

Anyway, let's leave the team to make the call here.

Thanks!

**Comment by arielgreen** [comment] 2023-01-20 21:18
Not overdue, this is in its regression period.

**Comment by arielgreen** [comment] 2023-01-23 19:37
@mollfpr @yuwenmemon please be sure to complete the checklist [here](https://github.com/Expensify/App/issues/13837#issuecomment-1387396363).

**Comment by mollfpr** [comment] 2023-01-23 19:39
@arielgreen Thanks for the ping! Will finish the checklist today.

**Comment by yuwenmemon** [comment] 2023-01-24 19:14
Thanks @mollfpr - let me know if I can be of assistance.

**Comment by mollfpr** [comment] 2023-01-25 00:42
Previously we have `maximumDate` props to `DatePicker` where it's set to `new Date()` on the `CompanyStep` form. But before this PR, the props are removed to allow users to input any future dates and the Form will validate the value.

Here's the PR https://github.com/Expensify/App/pull/13702 that removes the `maximumDate`.

cc @yuwenmemon

**Comment by yuwenmemon** [comment] 2023-01-25 01:47
@arielgreen last in item in the checklist is all yours!

**Comment by mollfpr** [comment] 2023-01-26 18:26
Bump @arielgreen

**Comment by arielgreen** [comment] 2023-01-31 04:33
All payments have been issued. Discussing a test [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1675139585386009), then we can close this one out.

**Comment by arielgreen** [comment] 2023-02-03 03:31
Bumped thread for consensus

**Closed** 2023-02-06 01:04 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
