### ISSUE TITLE
[HOLD for payment 2021-10-30] Empty area left to a long message opens up the user details page - @parasharrajat 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5756] opened 2021-10-11 19:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a conversation
2. Send a long message that take at least a 5 lines (could be a long image) 
3. Click on the blank area left to the message and below the avatar

## Expected Result:
Area should not be clickable. 

## Actual Result:
Area is clickable and is opening the user details page. 

## Workaround:
None needed.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.7-0

**Reproducible in staging?:** yes 
**Reproducible in production?:** yes 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/44479856/136848263-28951166-b170-44f1-9afe-0f948fd5673e.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1633794013064200

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2021-10-11 20:16
Removing N6-Hold since this affects regular app functionality

**Comment by dylanexpensify** [comment] 2021-10-12 09:13
Posted!
Internal: https://www.upwork.com/ab/applicants/1447852870053113856/job-details
External: https://www.upwork.com/jobs/~018aca3a27d69b586c

**Comment by akash191095** [comment] 2021-10-12 18:13
I was able to reproduce this issue on my side as well, a simple fix would be to use align-self: flex-start; on the avatar element, I tried this on my browser and it fixed the issue, need to check if there are any consequences of this.

With fix: 
<img width="800" alt="Screenshot 2021-10-12 at 11 40 51 PM" src="https://user-images.githubusercontent.com/26057318/137007534-5d9b3ee2-c749-4856-8b79-d7e9dd6e3c7d.png">

Without fix (there is a pointer cursor):
<img width="800" alt="Screenshot 2021-10-12 at 11 41 06 PM" src="https://user-images.githubusercontent.com/26057318/137007608-1b74ed45-99d7-41c2-8c03-b839e4dcf0e8.png">

**Comment by parasharrajat** [comment] 2021-10-12 18:15
@thienlnam let's get this rolling. Should not hang this for long.

**Comment by thienlnam** [comment] 2021-10-12 19:01
Hmm, I thought another engineer would be assigned once the external label to review proposals but I guess I'll take care of it.

Your proposal is good 🟢, @dylanexpensify Could you please assign and hire @parasharrajat?

**Comment by parasharrajat** [comment] 2021-10-13 10:41
@dylanexpensify  Please assign this to me. Thanks

**Comment by dylanexpensify** [comment] 2021-10-13 10:57
@parasharrajat _done!_

**Comment by botify** [comment] 2021-10-23 00:23
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.8-9 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/5786


If no regressions arise, payment will be issued on 2021-10-30. :confetti_ball:

**Comment by dylanexpensify** [comment] 2021-11-01 08:25
getting payment sent today!

**Comment by dylanexpensify** [comment] 2021-11-01 08:33
Payment made with reporting bonus and job closed!

**Closed by dylanexpensify** 2021-11-01 08:33 UTC
Labels: Exported, External, Engineering, Weekly, Awaiting Payment
