### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] mWeb - Welcome to Expensify is shown for existing user after logging in from public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35531] opened 2024-02-01 01:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of New Expensify
2. Navigate to this link - https://staging.new.expensify.com/r/5408450846930023
3. Click on Sign In
4. Login in with an existing account

## Expected Result:
Public room chat history should be displayed.
Welcome to Expensify message should be either shown before logging in or not at all for existing users

## Actual Result:
Welcome to Expensify screen is shown after log in, user is forced to close it to view public room chat history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3f604c28-8b55-4362-a461-5ce749700fe1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01adefc3ca63c114f2</li>
        <li>Upwork Job ID: 1752868613105299456</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-01 01:38
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by aswin-s** [comment] 2024-02-01 05:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Welcome to Expensify is shown for existing user after logging in

### What is the root cause of that problem?

The check for showing engagement model is performed inside PurposeForUsingExpensifyModal in a useEffect. 

https://github.com/Expensify/App/blob/c6758578fb85e9eff6f9ccf5a52f3dd34e6e6383/src/components/PurposeForUsingExpensifyModal.tsx#L106

Welcome.show method waits for a promise to resolve before executing the check

https://github.com/Expensify/App/blob/c6758578fb85e9eff6f9ccf5a52f3dd34e6e6383/src/libs/actions/Welcome.ts#L35

By this time the report is already loaded and sign in button is visible on the screen. So if user taps on the signin button he gets navigated to sign-in modal. However the previous screen is still kept in memory by react-navigation and the effect continues to run. Finally when the promise resolves and engagement modal is shown for new user.

Now when the user logs in and returns to the previous report, the check runs again and the condition for showing the engagement modal fails since the user is an existing user, resulting in an early return

https://github.com/Expensify/App/blob/c6758578fb85e9eff6f9ccf5a52f3dd34e6e6383/src/libs/actions/Welcome.ts#L130-L132

Note that it simply returns control and doesn't hide the modal which was already open. This is the reason the welcome modal is shown to an exising user


### What changes do you think we should make in order to solve the problem?

When the screen gets refocused and effect reruns, engagement modal should be hidden if user is not a new user. This would ensure that the modal will not get shown to an existing user.

A possible fix is to pass a hideModal method to Welcome.show that can hide a modal that is already visible.
```tsx

/**
 * Shows a welcome action on first login
 */
function show(routes: NavigationState<RootStackParamList>['routes'], showEngagementModal = () => {}, hideEngagementModal = () => {}) {
    isReadyPromise.then(() => {
        if (!isFirstTimeNewExpensifyUser) {
            // hide the modal before returning
	          hideEngagementModal();
            return;
        }

```


### What alternative solutions did you explore? (Optional)

None

**Comment by sakluger** [comment] 2024-02-06 00:11
I asked in #vip-vsb if this is a bug or expected behavior: https://expensify.slack.com/archives/C066HJM2CAZ/p1707178252015419

**Comment by Santhosh-Sellavel** [comment] 2024-02-09 15:26
> I asked in #vip-vsb if this is a bug or expected behavior: https://expensify.slack.com/archives/C066HJM2CAZ/p1707178252015419

Any update @sakluger

**Comment by sakluger** [comment] 2024-02-12 18:10
Yes, sorry for the delay. This is confirmed as a bug - we should only show the welcome message to new users.

**Comment by mvtglobally** [comment] 2024-02-13 04:58
Issue not reproducible during KI retests. (First week)

**Comment by Santhosh-Sellavel** [comment] 2024-02-13 20:07
@sakluger Seems the issue is not reproducible, if any C+ assistance please reassign it, thanks!
Unassigning due to low bandwidth, planning for OOO

**Comment by situchan** [comment] 2024-02-13 22:07
I can take over since I already have context while reviewing original [PR](https://github.com/Expensify/App/pull/32154) of this new feature

----

I am not able to reproduce on Step 4 (after sign in).

But instead I am seeing welcome page on Step 2 (after deep link). Is this expected or bug? I believe bug


https://github.com/Expensify/App/assets/108292595/2af9a455-7ed4-41c7-975d-80983acc147e

**Comment by sakluger** [comment] 2024-02-15 22:22
@situchan thanks for taking over!

Did you see the welcome message before signing in? Yes, that's definitely a bug.

**Comment by situchan** [comment] 2024-02-15 22:28
yes, I am seeing welcome message as anonymous user. Just tested again on latest staging


https://github.com/Expensify/App/assets/108292595/edf19842-a06b-4254-87f7-78847b6060f7

**Comment by situchan** [comment] 2024-02-19 15:35
Looking for proposals

**Comment by aswin-s** [comment] 2024-02-19 16:42
@situchan Any comments on this proposal : https://github.com/Expensify/App/issues/35531#issuecomment-1920555540

**Comment by situchan** [comment] 2024-02-19 16:59
@aswin-s your proposal was posted 3 weeks ago. Was it supposed to fix Step 4 issue or Step 2 issue or both?

**Comment by sakluger** [comment] 2024-02-21 21:40
@aswin-s could you clarify which issue your proposal was fixing? Was it step 2 or 4 of the reproduction steps?

**Comment by aswin-s** [comment] 2024-02-22 03:36
@situchan @sakluger The app behaviour has changed since I posted my proposal. I can no longer reproduce the issue at Step 4. However engagement modal is being shown for anonymous user. I've [updated my proposal](https://github.com/Expensify/App/issues/35531#issuecomment-1920555540) to address this issue.

**Comment by sakluger** [comment] 2024-02-25 19:12
Thanks @aswin-s! @situchan what do you think of the updated proposal?

**Comment by situchan** [comment] 2024-02-28 10:44
@luacmartins 
Bug not reproducible on Step 4 (after sign in) which was OP.
But instead seeing welcome page on Step 2 (after deep link). This is the bug to fix.

**Comment by sakluger** [comment] 2024-03-13 22:05
Summarizing payment on this issue:

Contributor: @aswin-s $500, sent offer via Upwork (https://www.upwork.com/nx/wm/offer/101367608/)
Contributor+: @situchan $500, paid via Upwork


@situchan could you please complete the BZ checklist?

**Comment by sakluger** [comment] 2024-03-14 19:29
Thanks! I paid out all the offers and created the regression test issue.

**Closed by sakluger** 2024-03-14 19:29 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
