### ISSUE TITLE
Workspace - App crashed when send attachment offline and delete workspace from other device

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41573] opened 2024-05-03 11:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4538783&group_by=cases:section_id&group_order=asc&group_id=306202
**Email or phone of affected tester (no customers):** applausetester+omq76@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open app
2. Create a workspace
3. Navigate to announce room
4. Send any message to the room
5. Disable internet connection
6. Send an image attachment to the room
7. Sign in with the same account on other device and delete recently created workspace
8. Enable internet connection on main device

## Expected Result:
Error should be displayed

## Actual Result:
App crashed when user sent attachment offline, deleted workspace from other device and returned online on main device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9b5beaad-2f01-4a4e-9393-5f70516d3514

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-05-03 12:02
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-03 12:03
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-03 12:03
Production 


https://github.com/Expensify/App/assets/115492554/79c88301-f4d3-4dd2-8bea-b3ea42da5572

**Comment by iwiznia** [comment] 2024-05-03 14:11
I don't think that solution makes sense. You should be able to go back and load all the older messages from an archived chat and the solution proposed will break that, no?

Did anyone find the actual code that makes it crash?

**Comment by iwiznia** [comment] 2024-05-03 14:12
@izarutskaya why is there no desktop video? Also, desktop can't crash, so not sure what is happening in desktop... 
Is it also not working on web? If so, can you share console logs?

**Comment by iwiznia** [comment] 2024-05-03 14:46
ok did the reproduction steps and not seeing a crash in web, seeing the loading older action issues described above (this is on staging, not main).

**Comment by iwiznia** [comment] 2024-05-03 15:20
Posted in slack here https://expensify.slack.com/archives/C01GTK53T8Q/p1714747609951879

**Comment by iwiznia** [comment] 2024-05-03 15:28
@izarutskaya I don't see any email in the issue. You should always include the email and other relevant data in the issue report (such as workspaceID, reportID, etc). That way I can retrieve logs for cases where I can't reproduce the issue like this one.

**Comment by iwiznia** [comment] 2024-05-03 15:29
@suneox did you see this:
> I don't think that solution makes sense. You should be able to go back and load all the older messages from an archived chat and the solution proposed will break that, no?

**Comment by janicduplessis** [comment] 2024-05-03 16:14
I think this might be fixed by https://github.com/Expensify/App/pull/41558. Would someone be able to test out that PR?

My other theory is that the chat doesn't have a CREATED action as the last one for some reason so we don't know that we are at the end of the chat (see https://github.com/janicduplessis/Expensify-App/blob/10fbd6a53177685702bdfa90e102163506e263cf/src/pages/home/report/ReportActionsView.tsx#L320-L321). I have a proposal to have the backend return whether more data is available but it is more of a medium term fix (https://github.com/Expensify/App/issues/41153).

**Comment by iwiznia** [comment] 2024-05-03 19:26
> +       if (isArchivedRoom && filteredReportActions.length === 1 && filteredReportActions[0].actionName === CONST.REPORT.ACTIONS.TYPE.CLOSED) {

I think this part is wrong as it only works if the actions is of length 1 but if the other app adds a comment before deleting the workspace I still see the broken behavior. 
I also don't quite understand what that code is doing exactly.

**Comment by janicduplessis** [comment] 2024-05-04 17:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

`GetOlderActions` is called in a loop and new messages are never loaded.

### What is the root cause of that problem?

There is a bug in `getContinuousReportActionChain` where if there is an optimistic action in the middle of a chat we incorrectly detect a gap in the chat. This causes a smaller array to be returned and then this incorrect array is used for pagination.

New messages loaded by `GetOlderActions` are never included in the chat because of the incorrect gap so we keep calling `GetOlderActions` in a loop since we never reach the `CREATED` action, which is the first message in all chats.

For more context and debugging of this problem you can read through [this chat in Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1714656403682529).

### What changes do you think we should make in order to solve the problem?

We need to fix `getContinuousReportActionChain` to properly ignore optimistic actions since the backend does not know about them and `previousReportActionID` will be wrong.

### What alternative solutions did you explore? (Optional)

**Comment by janicduplessis** [comment] 2024-05-04 17:28
I already have a PR ready for the fix since I think this is a deploy blocker https://github.com/Expensify/App/pull/41644

**Comment by izarutskaya** [comment] 2024-05-06 10:09
@iwiznia Tester login credentials (email) - applausetester+omq76@applause.expensifail.com. 
Let me please include a console logs..

**Comment by roryabraham** [comment] 2024-05-07 00:44
Verified that this is fixed and we didn't use any C+ services so I'm closing this out

**Closed by roryabraham** 2024-05-07 00:44 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Daily, Bug
