### ISSUE TITLE
[$250]  "Cannot get account details, please try again or contact concierge@expensify.com" message displayed for new customer account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46845] opened 2024-08-06 00:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Christinadobrzyn 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722892132773719

## Action Performed:

1. Go to NewDot
2. Send an Invoice or submit an expense to a new customer who doesn't already have an account.
3. Sign in to the new customer's account (linked to a private or public domain)

## Expected Result:
You should be able to sign into the new customer account
## Actual Result:
Getting "Cannot get account details, please try again or contact [concierge@expensify.com](mailto:concierge@expensify.com)"
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b2622813-b5f2-40af-858c-d49827304c71

https://github.com/user-attachments/assets/e8e4c21f-a8bb-4084-b5f0-46ecc0dcdb57

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea2b8c2a849d5b76</li>
        <li>Upwork Job ID: 1820987950074782073</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by kpadmanabhan** [comment] 2024-08-06 02:38
@m-natarajan : unable to reproduce this in staging now. could it be that anoyther build was deployed? where can i check the deploy status of staging?
i am able to successfully login to a fresh account and see the expense submitted from old account.
![image](https://github.com/user-attachments/assets/41231d5a-d7b7-46b4-bf63-ce32abf47d3d)

**Comment by Julesssss** [comment] 2024-08-06 10:03
Lets continue to treat this as a new issue. During triage the [previous fix](https://github.com/Expensify/App/issues/45252) might be a helpful reference.

**Comment by jaydamani** [comment] 2024-08-07 18:44
The issue looks similar to [before](https://github.com/Expensify/App/issues/45252#issuecomment-2226009336) from front-end side. The BeginSignIn request for account with error and without error is same so this is likely a back-end issue. Let me know if this needs to be a formal proposal or requires further investigation
API request with error:
```
email: xxxxxx+n3@gmail.com
apiRequestType: read
referer: ecash
platform: web
api_setCookie: false
isFromDevEnv: false
appversion: 9.0.17-2
clientUpdateID: -1
```
![image](https://github.com/user-attachments/assets/28f27c4e-e2e2-4e08-96ed-7a0c31311571)


API request without error:
```
email: xxxxxx+3n@gmail.com
apiRequestType: read
referer: ecash
platform: web
api_setCookie: false
isFromDevEnv: false
appversion: 9.0.17-2
clientUpdateID: -1
```
![image](https://github.com/user-attachments/assets/bdb2055a-b847-4aa4-9e70-1891708a1dab)

**Comment by isabelastisser** [comment] 2024-08-08 20:46
@aimane-chnaif, can you please review the comment above and provide an update? Thanks!

**Comment by Julesssss** [comment] 2024-08-09 08:48
Yeah I agree this is backend.

**Comment by isabelastisser** [comment] 2024-08-19 15:38
Waiting for internal engineer assignment.

**Comment by isabelastisser** [comment] 2024-08-28 01:50
still waiting for internal engineer assignment.

**Comment by isabelastisser** [comment] 2024-08-29 20:40
waiting for the assignment!

**Comment by isabelastisser** [comment] 2024-09-04 16:41
Still waiting for the assignment.

**Comment by mvtglobally** [comment] 2024-10-30 09:46
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-10-30 17:25
Not overdue.

**Comment by isabelastisser** [comment] 2024-11-04 16:11
@mvtglobally, can this still be reproduced?

**Comment by mvtglobally** [comment] 2024-11-08 15:17
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2024-11-16 01:57
Issue not reproducible during KI retests. (Third week)

**Comment by mvtglobally** [comment] 2024-11-23 03:30
Issue not reproducible during KI retests. (Fourth week)

**Comment by isabelastisser** [comment] 2024-11-25 15:25
Not reproducible. Closing!

**Closed by isabelastisser** 2024-11-25 15:25 UTC
Labels: Monthly, Internal, Bug, Hot Pick
