### ISSUE TITLE
[$1000] Web - Workspace- The green background does not completely cover the Delete Workspace button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13134] opened 2022-11-29 15:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log with any account
3. Setting>Workspaces>choose any Workspace>Click three dot>Click Delete Workspace

## Expected Result:
The green background completely covers the Delete Workspace button

## Actual Result:
The green background does not completely cover the Delete Workspace button

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.33.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204576358-49b23335-1345-4be4-94f0-9a733b616921.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01b7a07fdf3c9cf5db
- Upwork Job ID: 1598018322506989568

**Comment by hungvu193** [comment] 2022-11-29 16:03
<b>Proposal</b>
There's a `padding: 12` `createMenuContainer` style `BasePopoverMenu.js`.
<img width="1182" alt="Screen Shot 2022-11-29 at 23 01 34" src="https://user-images.githubusercontent.com/16502320/204579926-4348deeb-98b0-43d2-ba7c-426bf78dc161.png">

We need to remove that padding and it will fix the issue.

Result:

<img width="908" alt="Screen Shot 2022-11-29 at 23 02 54" src="https://user-images.githubusercontent.com/16502320/204580250-6592d79a-ead0-4530-a6b9-56012776448d.png">

**Comment by allroundexperts** [comment] 2022-11-30 02:02
### Proposal

We can move the padding to the `popoverMenuItem` itself so that the height doesn't change visually.

## Fix

```diff
diff --git a/src/components/ScreenWrapper/BaseScreenWrapper.js b/src/components/ScreenWrapper/BaseScreenWrapper.js
index 83408e6a3..d3d9bf9d8 100644
--- a/src/components/ScreenWrapper/BaseScreenWrapper.js
+++ b/src/components/ScreenWrapper/BaseScreenWrapper.js
@@ -86,6 +86,7 @@ class BaseScreenWrapper extends React.Component {
                                 ...this.props.style,
                                 styles.flex1,
                                 paddingStyle,
+                                !this.props.isSmallScreenWidth ? styles.borderLeft : undefined,
                             ]}
                         >
                             <KeyboardAvoidingView style={[styles.w100, styles.h100]} behavior={this.props.keyboardAvoidingViewBehavior}>
diff --git a/src/styles/styles.js b/src/styles/styles.js
index adedd13af..a33a5df90 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1087,7 +1087,6 @@ const styles = {
 
     createMenuContainer: {
         width: variables.sideBarWidth - 40,
-        paddingVertical: 12,
     },
 
     createMenuHeaderText: {
@@ -1100,7 +1099,7 @@ const styles = {
         flexDirection: 'row',
         borderRadius: 0,
         paddingHorizontal: 20,
-        paddingVertical: 12,
+        paddingVertical: 24,
         justifyContent: 'space-between',
         width: '100%',
     },
```

## Result

https://user-images.githubusercontent.com/30054992/204689456-fcba67ea-dc90-427c-ae1d-9fe4b588f60f.mov

**Comment by mananjadhav** [comment] 2022-11-30 18:21
I am not sure if I would treat this as a bug. Also there's only one item hence it looks like this. If it were 3-4 items in the Popover, then they don't need to cover the  curved corners.

Tagging @Expensify/design for their inputs.

**Comment by allroundexperts** [comment] 2022-11-30 18:27
Agreed with @mananjadhav. We can create a separate component for this though. But I'd wait for confirmation from design team.

**Comment by arosiclair** [comment] 2022-11-30 18:39
I'd agree with the comments above. This is a context menu with 1 item. So only the item gets highlighted on hover not the entire menu.

**Comment by shawnborton** [comment] 2022-11-30 19:06
This is expected behavior - we have top and bottom padding for the context menu wrapper. Going to close this out.

**Closed by shawnborton** 2022-11-30 19:06 UTC
Labels: External, Daily, Help Wanted, Bug
