### ISSUE TITLE
[$500] Assign task -Previous user can complete reassigned task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33183] opened 2023-12-15 18:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
Preconditions : User is a group member and was previously assigned a task.
1. Log in to a Staging.new.expensify.com
2. Navigate to task report
3. Complete the task

## Expected Result:
Previous assignee cannot complete a reassigned task.

## Actual Result:
Previous assignee can complete a reassigned task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6313062_1702560852247!bugtask](https://github.com/Expensify/App/assets/115492554/b87a26d5-e426-4768-b13d-e9c623643c06)

https://github.com/Expensify/App/assets/115492554/1e94338c-001c-4a30-8999-4e58643bbd66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121982621f19f646e</li>
        <li>Upwork Job ID: 1735723521909280768</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-15 18:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assign task -Previous user can complete reassigned task

### What is the root cause of that problem?
Currently we are allowing a user to modify a task if he can comment on the parent report here
https://github.com/Expensify/App/blob/8bef4bbd123fb6aa8d36e91c3012677208670793/src/libs/actions/Task.js#L881-L882

### What changes do you think we should make in order to solve the problem?

We should disallow the user to modify the task if it is not the current assignee
```
if (sessionAccountID !== getTaskAssigneeAccountID(taskReport)) {
        return false;
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment] 2023-12-15 18:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Previous user can mark reassigned task as complete/uncomplete

### What is the root cause of that problem?

In the canModfiy function we call we return try if the user is allowed to comment 
https://github.com/Expensify/App/blob/63a53805e65c17767c4328eab817415147a56cfa/src/libs/actions/Task.js#L870-L884

The isAllowedToComment function checks if the user has the write capability  or if the user is an admin in a workspace. 


In this case the report capability is “ALL” thus it returns true 



 
### What changes do you think we should make in order to solve the problem?
 Change this: 
```js
   // If you don't have access to the task report (maybe haven't opened it yet), check if you can access the parent report
    // - If the parent report is an #admins only room
    // - If you are a policy admin
    const parentReport = ReportUtils.getParentReport(taskReport);
    return ReportUtils.isAllowedToComment(parentReport);
}
```

To: 

```js
    const parentReport = ReportUtils.getParentReport(taskReport);
    return isPolicyExpenseChatAdmin(parentReport);
}
```

**Comment by namhihi237** [comment] 2023-12-15 18:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Anyone can comment allow edit the task
### What is the root cause of that problem?
Currently we allow everyone, who can write access to the report can modify the task [here](https://github.com/Expensify/App/blob/668af1c97b095f87237c12534e7bb4c5412f4f6e/src/libs/actions/Task.js#L871C1-L891C1)
### What changes do you think we should make in order to solve the problem?
We should update logic only to allow the creator and assignee, admin can modify
### What alternative solutions did you explore? (Optional)
N/A

**Comment by thienlnam** [comment] 2023-12-15 19:00
@izarutskaya Where are these issues being created from? This is intended functionality - you don't have to be the assignee to mark it as complete

**Closed by thienlnam** 2023-12-15 19:00 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by mvtglobally** [comment] 2023-12-18 04:34
@thienlnam apologize for the confusion. We have a bit of the backlog. 
Can you pls confirm what else needs to be updated here?

https://expensify.testrail.io/index.php?/cases/view/2649468  

![Screen Shot 2023-12-17 at 11 31 46 PM](https://github.com/Expensify/App/assets/43995119/d30547f5-4b3a-419a-b1a3-344f97db2bf1)

**Comment by thienlnam** [comment] 2023-12-20 22:01
Let's delete this test case as anyone can modify a task now as long as they have access to it - I consolidated the updates here 
https://github.com/Expensify/Expensify/issues/353149
