### ISSUE TITLE
[$250] GRP chat - Invalid group chat name error still persists after clearing group name text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40587] opened 2024-04-19 16:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** [ttps://github.com/Expensify/App/pull/39757](https://github.com/Expensify/App/pull/39757)
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition : User [A] created group chat with group name
1. User A - Go the created group chat
2. Tap on header >> Settings option
3. Enter over 255 characters in the Name text input field & tap on Save button (Note : error message appears)
4. Remove all the text & tap on save (Note : Report name becomes a default with emails + first name in alphabetical order , but the error message still displayed)

## Expected Result:
When maximum characters entered & later removing all the group name text, error message "Invalid group chat name" should be cleared as well. Only the group name with default with emails + first name in alphabetical order should be shown

## Actual Result:
"Invalid group chat name" error message still displayed after clearing group name text

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/139c3829-cd21-44ef-8e94-0c4862149e8c

![image](https://github.com/Expensify/App/assets/93399543/ffa99fa0-41ea-4d18-ae0e-359414a4fb9c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155d31c13ca9e9680</li>
        <li>Upwork Job ID: 1781375437507940352</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-19 16:21
We think that this bug might be related to #vip-vsb

**Comment by neonbhai** [comment] 2024-04-19 16:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invalid group chat name error still persists after clearing group name text

### What is the root cause of that problem?
We don't clear the error fields when setting new name optimistically here:
https://github.com/Expensify/App/blob/09ad46816dcd944cafd041e6626c15bb6dbc1527/src/libs/actions/Report.ts#L572-L579

### What changes do you think we should make in order to solve the problem?
We should clear `errorFields` for `reportName` when setting it in `optimisticData`

```jsx
errorFields: {
    reportName: null,
},
```

We do the same when updating room names here:
https://github.com/Expensify/App/blob/09ad46816dcd944cafd041e6626c15bb6dbc1527/src/libs/actions/Report.ts#L2030-L2032

**Comment by saifelance** [comment] 2024-04-20 02:31
To solve this issue, you should clear the error field for the report name when setting it optimistically. Ensures that any previous error state related to the report name is cleared when a new name is set optimistically.

In the function updateGroupChatName:

```
const optimisticData: OnyxUpdate[] = [
    {
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
        value: { reportName },
        errorFields: {
            reportName: null,
        },
    },
];
```


 when updating room names:


```
errorFields: {
    reportName: null,
},
```

**Comment by saifelance** [comment] 2024-04-22 03:39
> Let's go with @neonbhai's [solution](https://github.com/Expensify/App/issues/40587#issuecomment-2066909808). I think we should call `updateGroupChatName` when the name is actually changed.
> 
> 🎀👀🎀 C+ reviewed

@dukenv0307 Ofcourse

**Comment by saifelance** [comment] 2024-04-22 04:01
@dukenv0307 @neonbhai  Ensure that any previous error state is reset when setting a new name optimistically.

**Comment by yuwenmemon** [comment] 2024-04-25 17:27
SGTM!

**Comment by neonbhai** [comment] 2024-05-03 15:06
[PR](https://github.com/Expensify/App/pull/41588) ready for review!

**Comment by neonbhai** [comment] 2024-06-17 10:16
[PR](https://github.com/Expensify/App/pull/41588) was merged in May, seems like the automation failed here. Bump to finish payments and close the issue!

cc: @yuwenmemon

**Comment by yuwenmemon** [comment] 2024-06-21 16:25
@JmillsExpensify Looks like we need to do payment on this one

**Comment by JmillsExpensify** [comment] 2024-07-04 04:35
Payment summary:

 - Contributor: $250 @neonbhai 
 - Contributor+: @dukenv0307

**Comment by JmillsExpensify** [comment] 2024-07-04 04:35
@dukenv0307 do we need to add a regression test for this issue?

**Comment by JmillsExpensify** [comment] 2024-07-04 04:37
Thanks! Everyone has been paid via Upwork and checklist complete, so closing this one out.

**Closed by JmillsExpensify** 2024-07-04 04:37 UTC
Labels: Reviewing, External, Engineering, Daily, Improvement
