### ISSUE TITLE
Web - Unable to edit legal business name after adding it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26907] opened 2023-09-06 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Go to Settings > Workspace
3. Select a workspace from the list
4. Click bank account
5. Click connect manually
6. Pass step 1 by filling in the information
7. Pass step 2 by filling in all required information
8. Click the back button from step 3 and go to step 2
9. Try to edit the legal business name

## Expected Result:
Able to edit legal business name

## Actual Result:
Unable to edit legal business name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8f9c9487-558e-4dff-8f1a-70dcfeeeb7ef

https://github.com/Expensify/App/assets/93399543/46d84744-9dec-44ca-87bf-e8435fae49a1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693594590742959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-09-07 03:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to edit legal business name after adding it, similar happens with tax id number

### What is the root cause of that problem?
we are setting `disabled` prop to equal in case we have company name. But look wise it is same. That's why user doesn't know if the input is disabled or not.

### What changes do you think we should make in order to solve the problem?
- We can add disabled style in case we pass the prop disabled here - 
https://github.com/Expensify/App/blob/d60c13e7437ec9d367a51ed75c39d8214599a09d/src/components/TextInput/index.js#L64

we can add `inputDisabled` style conditionally if we are passing disabled as true.
```js
inputStyle={[styles.baseTextInput, styles.textInputDesktop, isLabeledMultiline ? styles.textInputMultiline : {}, ...props.inputStyle, props.disabled ? styles.inputDisabled : {}]}
```
It will look something like - 
<img width="321" alt="Screenshot 2023-09-07 at 8 24 03 AM" src="https://github.com/Expensify/App/assets/27822551/c7ef3f5a-389b-4ce6-a102-0bb59ac00ffb">

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-09-07 05:22
I think there is a purpose on disabling these inputs. And it looks similar to https://github.com/Expensify/App/issues/25577 where disabled input is not obvious to the user, and will be solved in this PR https://github.com/Expensify/App/pull/25991

**Comment by puneetlath** [comment] 2023-09-07 22:12
Thanks for that @alitoshmatov. I'm going to go ahead and close this then, as it seems like we don't want these fields to be editable. Feel free to comment if you disagree or if I've misunderstood!

**Closed by puneetlath** 2023-09-07 22:12 UTC
Labels: Daily, Bug
