### ISSUE TITLE
[$500] Cha - Chat in offline with invalid no. & go online makes header disappear& keeps loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35290] opened 2024-01-28 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32.2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4206011
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab--- Start chat
3. Turn off mobile data
4. Search a voip number (+18183305299) & select it
4. Send some messages
5. Turn on mobile data

## Expected Result:
Starting chat with invalid number in offline, sending messages and turns online, header text must be displayed without loading

## Actual Result:
Starting chat with invalid number in offline, sending messages and turns online, header text disappears and keeps loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/b4347f96-45e4-4e35-b880-883ab06aa615

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e13f18c6953c14a</li>
        <li>Upwork Job ID: 1751623849106137088</li>
        <li>Last Price Increase: 2024-01-28</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-28 19:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat in offline with invalid no. & go online makes header disappear& keeps loading

### What is the root cause of that problem?

The `isLoading` boolean will always be `true` because the `title` of the report is an empty string.

https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/pages/home/HeaderView.js#L108

The root cause of the problem is that the `getDisplayNameForParticipant` function returns an empty string as the `formattedLogin`

https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/ReportUtils.ts#L1609-L1615

### What changes do you think we should make in order to solve the problem?


Create a null fallback condition if the `formattedLogin` is empty.

https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/ReportUtils.ts#L1613

**Update**

```
return formattedLogin ??  Localize.translateLocal('common.hidden');
```

**Comment by alitoshmatov** [comment] 2024-01-30 19:31
Will take a look at it tomorrow

**Comment by MitchExpensify** [comment] 2024-01-31 02:51
I don't quite understand the issue - What header are we referring to here for example?

**Comment by MitchExpensify** [comment] 2024-02-03 22:44
Ah got it! I think this is too edgy and not obviously a part of a wave or VIP project - Closing

**Closed by MitchExpensify** 2024-02-03 22:44 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
