### ISSUE TITLE
Chats show as bold and unread in LHN when sending a message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31463] opened 2023-11-16 23:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.0-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1700177279688189

## Action Performed:
1. Open app and login as account A
2. Open a report of account B
3. Send a message 
4. Observe the LHN

## Expected Result:
LHN should not be bold for account A

## Actual Result:
Chat in LHN shows bold, even though I'm the one who sent the most recent message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b2ba17f5-7025-471f-82c9-f57f64ac3052

![image (1)](https://github.com/Expensify/App/assets/38435837/a68156d2-4c08-448c-b40b-549ee09381ae)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fcba9af5589f5538</li>
        <li>Upwork Job ID: 1735254863746113536</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-16 23:59
Can't reproduce

**Comment by mallenexpensify** [comment] 2023-11-17 00:56
Here's a vid, in case it's helpful

https://github.com/Expensify/App/assets/22508304/86c7029d-5e33-4dee-85d1-b2d6f9459af3

**Comment by ikevin127** [comment] 2023-11-17 01:33
Possible duplicates of
- https://github.com/Expensify/App/issues/31276
- https://github.com/Expensify/App/issues/28536

Quoted from #31276
> I think that this issue is a possible duplicate of https://github.com/Expensify/App/issues/28536, or at least has a high chance of getting solved by the associated PR

To be sure, given the video above, when clicking to Scott Deeter, try clicking back to **mallen fail** - if it becomes read then that's confirmation it's a duplicate of the ones mentioned above.

**Comment by MonilBhavsar** [comment] 2023-11-17 06:28
Yes, co assigning and taking a look

**Comment by MonilBhavsar** [comment] 2023-11-17 06:38
Confirmed it's regression from staging server 👍

**Comment by MonilBhavsar** [comment] 2023-11-17 07:08
Issue created internally for blocking deploy https://github.com/Expensify/Expensify/issues/337349
Closing this one

**Comment by MonilBhavsar** [comment] 2023-11-17 09:52
This issue is fixed!

**Comment by izarutskaya** [comment] 2023-12-07 12:16
Issue is reproducible again 
build 1.4.9-0

https://github.com/Expensify/App/assets/115492554/960a8127-08be-4008-9311-fc8e65d7fc46

**Comment by MonilBhavsar** [comment] 2023-12-07 12:21
This does seem like issue when receiving messages? Can we please get steps to repro and is it only happening on iOS/mobile

**Comment by chiragsalian** [comment] 2023-12-07 18:28
Looks like this is not a blocker so no reason for it to be hourly. Demoting to daily. Also looks like monil is assigned the issue and I'll be OOO next week onwards so i'm removing my assignment here.

**Comment by sonialiap** [comment] 2023-12-12 10:32
@izarutskaya a few questions

1. Which platform is it happening on, only on iOS/mobile or web and android too?
2. Is it happening on staging and not on production?
3. What steps did you take to reproduce this issue? The same ones as in the original posit? I.e.
> 1. Open app and login as account A
> 2. Open a report of account B
> 3. Send a message
> 4. Observe the LHN

**Comment by MonilBhavsar** [comment] 2023-12-18 07:50
I am using newDot a lot and haven't experienced this bug. @sonialiap are you experiencing this bug or able to reproduce?

**Comment by MonilBhavsar** [comment] 2023-12-21 11:12
I haven't reproduced this issue while using new expensify daily. Feel free to reopen if you experience this issue

**Comment by lanitochka17** [comment] 2024-01-03 17:57
Issue is reproducible again (IOS)
Build 1.4.21-1


https://github.com/Expensify/App/assets/78819774/7ebdccd3-562d-43b0-a4c9-a968568a0f3f

**Comment by MonilBhavsar** [comment] 2024-01-03 18:16
@lanitochka17 this seems like different issue where message is marked as unread when received from different user.
Current Github issue is when message is marked as unread when sending a message. Looks like in the video no message was sent and only received. Can you please create different issue to keep conversation and findings separate. Please assign it to me. I am happy to take a look.

**Comment by MonilBhavsar** [comment] 2024-01-05 06:21
closing in favour of https://github.com/Expensify/App/issues/33974

**Closed by MonilBhavsar** 2024-01-05 06:21 UTC
Labels: Engineering, Daily, Internal, Bug
