### ISSUE TITLE
[HOLD on #33700] [$500] IOU - In WS, split bill distance request is shown as split request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33658] opened 2023-12-27 19:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon---Split bill---Distance
4. Enter start and finish waypoints
5. Tap next
6. Tap split
7. Tap on the newly created distance request to open details page

## Expected Result:
In workspace, split bill distance request must not be shown as split request. Both, distance request and split bill must not be mingled and shown.

## Actual Result:
In workspace, split bill distance request is shown as split request.
Distance request and split bill is mingled and shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9bfbb8ef-1b55-441c-8299-6c3d98d1f3b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment] 2023-12-28 08:38
## Proposal
### Please re-state the problem that we are trying to solve in this issue

In WS, split bill distance request is shown as split request

### What is the root cause of that problem?

Split request with distance should be disabled as we have not yet implemented this feature yet (Judging from FAB as we cannot split distance request with FAB).

### What changes do you think we should make in order to solve the problem?

Change this condition

https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/pages/iou/request/IOURequestStartPage.js#L100

to 

```js
const shouldDisplayDistanceRequest = (isExpenseChat || isExpenseReport || isFromGlobalCreate) && iouType !== CONST.IOU.TYPE.SPLIT;
```

This will disable the distance tab from tab selector in split request.

### What alternative solutions did you explore? (Optional)

We can implement this flow by changing the API request related to split bill so we can pass distance comment instead of string comment.

**Comment by garrettmknight** [comment] 2024-01-04 18:58
No update on that other comment, still holding and dropping to weekly while we wait.

**Comment by shubham1206agra** [comment] 2024-01-16 05:48
@jliexpensify Should we disable split distance here according to https://github.com/Expensify/App/issues/33700#issuecomment-1893030232?
cc @neil-marcellini

**Comment by garrettmknight** [comment] 2024-01-16 19:28
Closing based on the above post.

**Closed by garrettmknight** 2024-01-16 19:28 UTC
Labels: External, Weekly, Overdue, Bug
