### ISSUE TITLE
[$250] Distance - 3-dot menu does not open after returning from receipt view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38231] opened 2024-03-13 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an owner of Collect workspace
- The Collect workspace has tags
- "People must tag expenses" is enabled on Old Dot
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a distance request
4. Go to request details page
5. Click on the receipt
6. Close the receipt
7. Click 3-dot menu on the top right

## Expected Result:
3-dot menu will open

## Actual Result:
3-dot menu does not open after returning from receipt view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c303ac94-68c5-4f9d-b5eb-8c19a9653ef8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150ae440d66ece2be</li>
        <li>Upwork Job ID: 1768360310783438848</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by dragnoir** [comment] 2024-03-13 16:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

3-dot menu does not open after returning from receipt view

### What is the root cause of that problem?

Issue from https://github.com/Expensify/App/pull/34720

The check of `isBehindModal` is missing other parameters.
https://github.com/Expensify/App/blob/37a2dbb9dd5e89d61210feb0eb1de3a80cb6ca6d/src/components/ThreeDotsMenu/index.tsx#L86

### What changes do you think we should make in order to solve the problem?

We need also to check if the modal is still visible

```diff
- const  isBehindModal  =  modal?.willAlertModalBecomeVisible  &&  !modal?.isPopover  &&  !shouldOverlay;
+ const  isBehindModal  =  modal?.willAlertModalBecomeVisible  &&  !modal?.isPopover  &&  !shouldOverlay  &&  modal?.isVisible;
```
### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment] 2024-03-14 19:36
This is a bug we want to fix, although it seems like a low-priority issue and fairly easy to fix, so I've set the price to $250. @c3024 please let me know if you disagree.

**Comment by c3024** [comment] 2024-03-19 04:56
#37609 should fix this.

**Comment by sakluger** [comment] 2024-03-20 23:02
Good find! Closing this one out.

**Closed by sakluger** 2024-03-20 23:02 UTC
Labels: External, Daily, Help Wanted, Bug
