### ISSUE TITLE
[$1000] Profile - Esc click after profile visit changes chat in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21052] opened 2023-06-19 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report (except the first report)
3. Open settings
4. Open profile
5. Press ESC and observe the app changes selected report in LHN

## Expected Result:
 App should not switch chat in LHN when we use ESC to close any menu or popup

## Actual Result:
App switches chat in LHN when we use ESC to close profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/68dbce5b-20dd-4e49-aba1-97cd1276767e

https://github.com/Expensify/App/assets/93399543/94aa4701-c747-49dd-9795-e83178f3deb4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686475786727959
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf59e71d261cd6e0</li>
        <li>Upwork Job ID: 1671054154223763456</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by Santhosh-Sellavel** [comment] 2023-06-20 17:22
@laurenreidexpensify Is this occurring for you, unable to reproduce at my end

https://github.com/Expensify/App/assets/85645967/4e329362-b64f-4548-8f99-760841ff83a9

cc: @dhanashree-sawant

**Comment by dhanashree-sawant** [comment] 2023-06-21 04:11
Hi @Santhosh-Sellavel, yes it is not reproducible now.

**Comment by laurenreidexpensify** [comment] 2023-06-21 12:28
good catch @Santhosh-Sellavel, can confirm not reproducible my end. Closing

**Comment by Santhosh-Sellavel** [comment] 2023-06-21 12:29
@laurenreidexpensify We can close this as it should be handled somewhere while/before the issue was reported.

**Closed by laurenreidexpensify** 2023-06-21 12:28 UTC
Labels: External, Daily, Help Wanted, Bug
