### ISSUE TITLE
[AWAITING PAYMENT] [$250] iOS- Public room- RHP not opens smoothly after selecting any option from room details

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44812] opened 2024-07-04 10:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/43985
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log out ND if user is logged in
2. Navigate to a public room, e.g. https://staging.new.expensify.com/r/4865807136424891
3. Tap the header to open the details
4. Select any option

## Expected Result:
The RHP (sign-in modal) opens smoothly

## Actual Result:
The sign-in modal does not open smoothly, opening slows down when the modal almost gets to the left edge.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b859a9b3-8b0b-4c3e-b30d-2cc21c912dc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01176fb78ce72c5cfa</li>
        <li>Upwork Job ID: 1811805082507741105</li>
        <li>Last Price Increase: 2024-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 103702844</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by izarutskaya** [comment] 2024-07-04 10:05
@garrettmknight FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-04 10:06
We think this issue might be related to the  #vip-vsb

**Comment by izarutskaya** [comment] 2024-07-04 10:07
Production

https://github.com/Expensify/App/assets/115492554/d407bb25-097c-472b-a68f-919d7189f01c

**Comment by garrettmknight** [comment] 2024-07-04 16:24
Don't think this needs to be a deploy blocker. I'm going to open it up to be external to start.

**Comment by sobitneupane** [comment] 2024-07-10 07:16
Waiting for proposal.

**Comment by garrettmknight** [comment] 2024-07-12 16:50
Just retriggering the automation - still waiting for proposals.

**Comment by sobitneupane** [comment] 2024-07-16 07:05
Waiting for proposal.

**Comment by jacobkim9881** [comment] 2024-07-18 08:20
This issue can occur for loading background image `assets/images/home-background--mobile.svg`. After removing this component, sliding opens much smoothly. 

https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/signin/SignInPageLayout/index.tsx#L158

**Comment by mvtglobally** [comment] 2024-07-19 03:23
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2024-07-19 14:03
Just reproduced it so we'll keep this open. @jacobkim9881 can you put a proposal together [using our guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)?

**Comment by jacobkim9881** [comment] 2024-07-19 14:24
@garrettmknight Sure. Let me submit a proposal [using the guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by jacobkim9881** [comment] 2024-07-19 14:40
@garrettmknight 
I forgot to say I am currently on [other PR for now](https://github.com/Expensify/App/pull/45484). Can I take the issue here? Or should I submit a proposal first?

> New contributors are limited to working on one job at a time, do not submit proposals for new jobs until your first PR has been merged. Experienced contributors may work on numerous jobs simultaneously.

**Comment by jacobkim9881** [comment] 2024-07-19 16:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Without having an account, sliding RHP by clicking menus on room details isn't smooth.

### What is the root cause of that problem?
Loading SVG as a background for a modal makes sliding animation slow. On a report screen, loading a modal that will load an SVG file burdens mobile devices for a short time. The SVG file is loaded inside of this component below:

https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/signin/SignInPageLayout/index.tsx#L158

It's the SVG file to load as a background: `assets/images/home-background--mobile.svg`. It is used for loading on the home page too and without any condition it is loaded on the home page and sign-in modal. 

### What changes do you think we should make in order to solve the problem?
We can add a condition to load the SVG file on the home page only. The home page and sign-in modal for room details use the same component `src/pages/signin/SignInPage.tsx`. Here sign in modal uses `SignInPage` comp:

https://github.com/Expensify/App/blob/f69f858f614933759591b1f4ede42e8ed0781e1f/src/pages/signin/SignInModal.tsx#L44

This comp gets a prop like:

```js
<SignInPage 
shouldEnableMaxHeight={false}
isSignInModal={true}
/>
```

The `BackgroundImage` comp of `SignInPageLayout` of `SignInPage` will be used only on a wide screen and sign-in modal.

https://github.com/Expensify/App/blob/f69f858f614933759591b1f4ede42e8ed0781e1f/src/pages/signin/SignInPageLayout/index.tsx#L109

It will be written like:

```js
{isSignInModal && !isWideScreen ? null : <BackgroundImage .../> }
```

Then the background image will not be used on sign-in modal and on a small screen.

### What alternative solutions did you explore? (Optional)
Small-sized SVG file from 800kb can be resized into to 100kb as a background image on sign-in modal and on the small screen. 


W/O the SVG file:

https://github.com/user-attachments/assets/cefa10c0-b3a8-4d02-90e3-ccf38e615cdd


W small-sized SVG file (193kb) `eReceipt_background.svg` :

https://github.com/user-attachments/assets/72040b98-e93d-4b71-b92b-d68c83044cd6


Original :

https://github.com/user-attachments/assets/c4cad1e8-ee48-4b7c-b0e7-fd66b33e8367

**Comment by garrettmknight** [comment] 2024-07-19 18:04
@sobitneupane what do you think?

**Comment by sobitneupane** [comment] 2024-07-22 09:18
Thanks for your proposal @jacobkim9881. But I don't think we want to get rid of the background image. As you can notice, in [this video](https://github.com/Expensify/App/issues/44812#issuecomment-2208603896) there was no lag even with the background image. It was reported three weeks back as the [deploy blocker](https://github.com/Expensify/App/issues/44812#issuecomment-2208600944) which means some change must have been made around that time causing the issue.

**Comment by jacobkim9881** [comment] 2024-07-22 11:49
@sobitneupane Thanks for reviewing. Seems [the video](https://github.com/Expensify/App/issues/44812#issuecomment-2208603896) has no lag.

**Comment by sobitneupane** [comment] 2024-07-26 05:46
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-07-30 08:31
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-08-02 05:39
Waiting for proposal.

**Comment by jacobkim9881** [comment] 2024-08-02 10:00
@sobitneupane I updated my proposal. Could you check the proposal?

## Proposal
[Updated](https://github.com/Expensify/App/issues/44812#issuecomment-2239631941)

**Comment by sobitneupane** [comment] 2024-08-06 07:36
Thanks for the update @jacobkim9881 

Even in the case where you have used PNG image, RHP doesn't open smoothly. There is some lag in the [attached video](https://github.com/Expensify/App/issues/44812#issuecomment-2239631941).

**Comment by sobitneupane** [comment] 2024-08-12 10:34
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-08-16 04:21
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-08-20 06:12
Waiting for proposal.

**Comment by wildan-m** [comment] 2024-08-23 09:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The RHP in the iOS public room does not open smoothly after selecting an option from room details.

### What is the root cause of that problem?

There are two complex animation and heavy assets being loaded, it's not working smoothly when combined with react navigation 

### What changes do you think we should make in order to solve the problem?

We can load the assets after the interaction completed.

First for the background image
src/pages/signin/SignInPageLayout/BackgroundImage/index.ios.tsx
```tsx
   useEffect(() => {
        const interactionHandle = InteractionManager.runAfterInteractions(() => {
            setLoaded(true);
        });
        return () => {
            if (interactionHandle) {
                interactionHandle.cancel();
            }
        };
    }, []);
...
    return (loaded &&
        <Reanimated.View style={[styles.signInBackground, StyleUtils.getWidthStyle(width), animatedStyle]}>
....

```

And then for the lottie component, we can also create ios specific code for this component if required
src/components/Lottie/index.tsx
```tsx
    const [loaded, setLoaded] = useState(false);
    useEffect(() => {
        const interactionHandle = InteractionManager.runAfterInteractions(() => {
            setLoaded(true);
        });

        return () => {
            if (interactionHandle) {
                interactionHandle.cancel();
            }
        };
    }, []);

    if (isError || appState.isBackground || !animationFile || !isSplashHidden || !loaded) {
        return <View style={[aspectRatioStyle, props.style]} />;
    }
```

[Branch for this solution.](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/44812-react-navigation-lottie-transition?expand=1)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by sobitneupane** [comment] 2024-08-27 10:27
Thanks for the proposal @wildan-m 

[Proposal](https://github.com/Expensify/App/issues/44812#issuecomment-2306730884) from @wildan-m looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by wildan-m** [comment] 2024-08-28 06:41
@sobitneupane I've created [the PR](https://github.com/Expensify/App/pull/48143).

The desktop and android mweb videos isn't uploaded yet.

Desktop: I am unsure how to open a deeplink on desktop before logging in. Asking it here:
https://expensify.slack.com/archives/C01GTK53T8Q/p1724826778770759

Android mWeb: Public room not opened, the link always re-directed to login page.

**Comment by wildan-m** [comment] 2024-08-29 02:41
@sobitneupane the desktop and android videos has been uploaded.

I use deeplinking for desktop by setting window.location.href = '/r/4865807136424891' in the console tab, as explained in the PR for the desktop test step.

**Comment by wildan-m** [comment] 2024-09-20 21:54
@MelvinBot it hit production 7 days ago. we can close this issue

**Comment by garrettmknight** [comment] 2024-09-24 14:02
**Payment Summary:**
- Contributor: @wildan-m $250 via upwork
- Reviewer: @sobitneupane $250

@sobitneupane please complete the checklist and request payment

**Comment by garrettmknight** [comment] 2024-10-01 12:22
@sobitneupane please complete the checklist.

**Comment by sobitneupane** [comment] 2024-10-02 10:43
**Regression Test Proposal**

1. Log out ND if user is logged in
2. Navigate to a public room
3. Tap the header to open the details
4. Select any option
5. Verify that the sign-in modal(RHP) opens smoothly.

Do we agree 👍 or 👎

**Comment by garrettmknight** [comment] 2024-10-15 23:18
Closing - @sobitneupane submit for payment when you're ready.

**Closed by garrettmknight** 2024-10-15 23:18 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by trjExpensify** [comment] 2024-10-23 09:41
Confirming the payment summary here is correct: https://github.com/Expensify/App/issues/44812#issuecomment-2371386263

**Comment by garrettmknight** [comment] 2024-10-23 09:42
$250 approved for @sobitneupane
