### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] Increase table row and decrease table row gap

### ISSUE THREAD

**Issue by dubielzyk-expensify** [Expensify/App#49582] opened 2024-09-23 04:58 UTC
We recently decided to do some minor tweaks to our tables and would like that reflected in the product. The changes are as follows:
- Table rows should have a minimum height of `64px`
- The gap/space between each table row should be reduced to `8px` instead of `12px`. 

## Screenshots (before left, after right)

![image](https://github.com/user-attachments/assets/bd238be0-81cf-42a7-9f1d-ce9cb4f15ce7)
![image](https://github.com/user-attachments/assets/fea78d61-f6fd-48d1-8510-da7a5a4e8291)
![image](https://github.com/user-attachments/assets/e23d1f38-01b2-4b80-a39a-38493c309bc5)

This should apply to all tables (search, members, categories, tags, etc). cc @Expensify/design 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838357676436244247</li>
        <li>Upwork Job ID: 1838357676436244247</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104141061</li>
<li>abzokhattab | Contributor | 104141064</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by NJ-2020** [comment] 2024-09-23 07:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Increase table row and decrease table row gap inside Categories workspace page
### What is the root cause of that problem?
Right here the Categories Table list item had total height of 52px with padding top and bottom 16px including content
And for the gap here we use mb3 which is 12px `containerStyle={styles.mb3}`
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/TableListItem.tsx#L45-L49
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/styles/index.ts#L4639-L4647
### What changes do you think we should make in order to solve the problem?
We can increase the padding vertical (top and bottom) instead of adding the height because i think this is our way to increase the height to 21px instead of 16px and the total height will be 62px instead of 52px

And for mb3 `containerStyle={styles.mb3}` we can change to mb2 (8px) for gap space each item

### What alternative solutions did you explore? (Optional)

**Comment by NJ-2020** [comment] 2024-09-23 08:45
### [Proposal Updated](https://github.com/Expensify/App/issues/49582#issuecomment-2367413484)

- Update permalink link code

**Comment by alexpensify** [comment] 2024-09-23 23:07
@dubielzyk-expensify - are we ready to assign this as `External` or is there someone scheduled to work on this one?

**Comment by dubielzyk-expensify** [comment] 2024-09-23 23:20
Nobody assigned. Added the label

**Comment by NJ-2020** [comment] 2024-09-24 04:10
### [Proposal Updated](https://github.com/Expensify/App/issues/49582#issuecomment-2367413484)

- Small changes

**Comment by Gajendra-Gupta** [comment] 2024-09-24 09:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Increase table row and decrease table row gap

### What is the root cause of that problem?
new feature
### What changes do you think we should make in order to solve the problem?
For reducing the gap between rows need to change style containerStyle={styles.mb3} to
containerStyle={styles.mb2}
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/components/SelectionList/TableListItem.tsx#L45-L49
For increasing table row height need to change style
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/styles/index.ts#L4639-L4647
paddingVertical should be 16px to 22px so the style should be
```
selectionListPressableItemWrapper: { 
     alignItems: 'center', 
     flexDirection: 'row', 
     paddingHorizontal: 16, 
     paddingVertical: 22, 
     marginHorizontal: 20, 
     backgroundColor: theme.highlightBG, 
     borderRadius: 8, 
 },
```

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2024-09-25 21:39
@ikevin127 when you get a chance, can you please review these proposals? Thanks!

**Comment by ikevin127** [comment] 2024-09-25 21:44
@alexpensify Sure, will review today.

**Comment by ikevin127** [comment] 2024-09-26 01:53
@abzokhattab's [proposal](https://github.com/Expensify/App/issues/49582#issuecomment-2367413245) looks good to me. The proposed solution fulfils the expectations of the issue requirements which mention setting a minimum height of 64px and decreasing the margin between items.

I was testing whether increasing the padding or setting `minHeight` is the best way to go here in terms of increasing the item's height and I couldn't find any downsides to any method, therefore I made the choice based on first come, first served, plus took in consideration the issue requirements which says:

`Table rows should have a minimum height of 64px`

🎀👀🎀 C+ reviewed

**Comment by alexpensify** [comment] 2024-10-02 22:02
Weekly Update: The PR is still in review

**Comment by alexpensify** [comment] 2024-10-04 20:27
Update: waiting for this PR to go to production

**Comment by ikevin127** [comment] 2024-10-11 23:12
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: **Not caused by any offending PR as the issue was created to apply design modifications to existing UI.**
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Create a new workspace.
2. Submit a few expenses.
3. Open the search page and ensure that the height of each row is >= 64px and the gaps between the rows are 8px.
4. Go to the workspace settings.
5. Validate that the rows (including skeleton rows) in the tables for "Members," "Tags," "Categories," and "Report Fields" have the same height and gap as mentioned in point 3.

Do we agree 👍 or 👎.

**Comment by alexpensify** [comment] 2024-10-14 18:23
Payouts due: 2024-10-14

- [ ] Contributor: $250 @abzokhattab 
- [ ] Reviewer: $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~021838357676436244247). I've completed the payment process in Upwork.

**Closed by alexpensify** 2024-10-14 18:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
