### ISSUE TITLE
[$1000] Thread- Instead of " Deleted message ", LHN displays " No activity yet"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25928] opened 2023-08-25 12:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Open a task page
3. Send a message
4. Long press the message and create a reply in thread page
5. Send a message
6. Navigate back to LHN to note latest "parent message" for which thread created is shown
7. Open the task page
8. Delete the parent message
9. Navigate back to LHN

## Expected Result:
The task conversation must show " Deleted message" in LHN

## Actual Result:
The task conversation shows "no activity yet" instead of showing "deleted message"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f896fa51-e853-4c28-8386-22acd0604038

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc937c27f8af5295</li>
        <li>Upwork Job ID: 1695104090311036928</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-08-25 15:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread- Instead of " Deleted message ", LHN displays " No activity yet"

### What is the root cause of that problem?
In task report, we don't check if last action is deleted parent action to display "Deleted message"

### What changes do you think we should make in order to solve the problem?
In here 
https://github.com/Expensify/App/blob/e57200789dfccac68bb6519ca3a43c68aac20a5b/src/libs/OptionsListUtils.js#L392
We should add a condition to check if isDeletedParentAction is true we will display "Deleted message" else we will display lastMessageText 

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2023-08-25 18:07
This is Dupe of  #19722

**Comment by lschurr** [comment] 2023-08-25 18:36
Thanks @rojiphil! Closing this one out.

**Closed by lschurr** 2023-08-25 18:36 UTC
Labels: External, Daily, Help Wanted, Bug
