### ISSUE TITLE
[HOLD for payment 2024-07-22] [$250] Android - Report Fields - Cursor position jumps to the beginning of the name field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44868] opened 2024-07-04 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in prouring regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported bduction?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44275
## Action Performed:
1. Open new expensify app
2. Create a workspace
3. Enable report fields feature
4. Open report fields setting
5. Tap on add field
6. Tap on Name and add something and save it
7. Tap on Name again

## Expected Result:
The cursor positions itself at the end of the text

## Actual Result:
The cursor jumps to the beginning of the saved text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/03a437a3-e2e2-4a98-bfd9-d4b51ce08da8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ecace54576044ee5</li>
        <li>Upwork Job ID: 1808958862801435309</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102994077</li>
<li>dominictb | Contributor | 103082291</li>
<li>abzokhattab | Contributor | 103091472</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-07-04 19:32
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcochavezf** [comment] 2024-07-04 20:19
I don't consider it a deploy blocker, and can be fixed externally

**Comment by mountiny** [comment] 2024-07-04 22:30
I am managing this project so going to take over this issue to make sure it gets fixed. Thanks for helping!

**Comment by mountiny** [comment] 2024-07-04 22:33
@rezkiy37 @waterim Can you please have a look

**Comment by abzokhattab** [comment] 2024-07-05 00:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report Fields - Cursor position jumps to the beginning of the name field when reopened
### What is the root cause of that problem?
 
- The name field inside create report field uses the [TextPicker](https://github.com/Expensify/App/blob/257d48606187c6331b11340cf02e7ab425400bb7/src/pages/workspace/reportFields/WorkspaceCreateReportFieldPage.tsx#L123-L127) as the  `InputWrapper` for the user's input field 
- The TextPicker component uses the [TextSelectorModal](https://github.com/Expensify/App/blob/2fad56eb9b0a2c6962c5d65f3b87e0b12e6bf9d0/src/components/TextPicker/index.tsx#L43-L51) component in order to render the text field 
- The `TextSelectorModal` contains a prop `isVisible` that decides whether the input field page should be visible or not.
- in case the isVisible is false then true (page was reopened), the input field refocuses [here](https://github.com/Expensify/App/blob/f6c1cb0856c8601e2883b53924b19b8414f2896f/src/components/TextPicker/TextSelectorModal.tsx#L35-L52) in order to show the keyboard. 
- the `inputRef.current.focus()` doesn't preserve the cursor position, that's why it just places the cursor at the beginning 

PS: This issue occurs in the create new tax page as well 
### What changes do you think we should make in order to solve the problem?
 we should set the cursor selection at the end of the string after focusing, we should modify the `useFocusEffect` to be as follows:
```js
   useFocusEffect(
        useCallback(() => {
            focusTimeoutRef.current = setTimeout(() => {
                if (inputRef.current && isVisible) {
                    inputRef.current.focus();
                    if (currentValue) {
                        inputRef.current.setSelection(currentValue.length, currentValue.length);
                    }
                }
                return () => {
                    if (!focusTimeoutRef.current || !isVisible) {
                        return;
                    }
                    clearTimeout(focusTimeoutRef.current);
                };
            }, CONST.ANIMATED_TRANSITION);
        }, [isVisible]),
```

optionally, instead of always placing the cursor at the end when refocusing, we can save the cursor position in a ref and use it instead  



###  POC

https://github.com/Expensify/App/assets/59809993/5a82f5fe-1185-4a22-86b5-0d5e14f2c436

**Comment by rushatgabhane** [comment] 2024-07-08 02:32
Looks like @rezkiy37 / @waterim will work on this

**Comment by waterim** [comment] 2024-07-08 10:50
Hello, I will help with this issue

**Comment by rezkiy37** [comment] 2024-07-09 08:55
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-07-09 16:13
I've opened a PR (https://github.com/Expensify/App/pull/45074) for review 🙂

**Comment by rezkiy37** [comment] 2024-07-10 08:27
Just to clarify: the app does not use `useAutoFocusInput` for this scenario with the new report field name. It uses `TextSelectorModal` under the hood and this component handlers focusing.

**Comment by mountiny** [comment] 2024-07-10 16:19
$50 to @abzokhattab as the issue was labeled as Help Wanted and we have used their solution

**Comment by garrettmknight** [comment] 2024-07-11 17:49
@dominictb updated offer sent to you for $50

**Comment by abzokhattab** [comment] 2024-07-11 18:42
@garrettmknight  I believe there may be a mistake in the offer assignment,  can you please recheck [this comment](https://github.com/Expensify/App/issues/44868#issuecomment-2220953522) 
Thank you for your consideration!

**Comment by garrettmknight** [comment] 2024-07-12 10:35
Oops, @abzokhattab you're right. I'll drop the contract to pay $50 when the solution works on prod.

**Comment by abzokhattab** [comment] 2024-07-12 10:37
Yeah its 50$

**Comment by rushatgabhane** [comment] 2024-07-17 07:46
PR reviewed and merged

**Comment by garrettmknight** [comment] 2024-07-18 18:02
@abzokhattab all paid out!

**Comment by garrettmknight** [comment] 2024-07-22 15:34
Looks like this made it to prod on Monday. Just tested and it's fixed.

**Comment by garrettmknight** [comment] 2024-07-22 15:47
**Payment Summary:**
- Reviewer: @rushatgabhane $250

@rezkiy37 @mountiny is there a regression test for this already?

**Comment by garrettmknight** [comment] 2024-07-22 15:49
Dropping to weekly for payment

**Closed** 2024-07-22 18:43 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
