### ISSUE TITLE
[HOLD for payment 2023-06-30] Bank-account - The emply account number have 'The routing number and account number cannot be the same' instead of 'Please enter a valid routing number'

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21222] opened 2023-06-21 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20560
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a workspace
3. Go to Workspace > Travel > Connect bank account > Connect manually
4. Enter 074000078 as routing number and account number
5. Check the terms checkbox
6. Tap Back button
7. Clear account number, followed by routing number

## Expected Result:
The empty account number field should be 'Please enter a valid routing number' instead of 'The routing number and account number cannot be the same'

## Actual Result:
The empty account number field is 'Please enter a valid routing number' at first, until the routing number is cleared and it becomes 'The routing number and account number cannot be the same'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6101477_Screenshot_20230621_221143](https://github.com/Expensify/App/assets/78819774/1a57a914-09d9-44d1-b9a4-da90a87f6613)

https://github.com/Expensify/App/assets/78819774/dd9b33fa-f2b7-4cfb-8954-295d32c363b5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-06-21 16:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank-account - The emply account number have 'The routing number and account number cannot be the same' instead of 'Please enter a valid routing number'

### What is the root cause of that problem?
For the same field, we have 2 different if conditions separately with which 2nd truthy condition updates/overwrites the previous errorField `accountNumber`.

### What changes do you think we should make in order to solve the problem?
For the same field we can convert the same number condition to `else if`, so it will only validate the same number condition when `accountNumber` is not provided.

https://github.com/Expensify/App/blob/8a6fc7a219fbd15dc2e858ceefe47e11a7de19b2/src/pages/ReimbursementAccount/BankAccountManualStep.js#L40-L51

```
       if (
            !values.accountNumber ||
            (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) && !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim()))
        ) {
            errorFields.accountNumber = 'bankAccount.error.accountNumber';
        } else if (values.accountNumber === routingNumber) {
            errorFields.accountNumber = this.props.translate('bankAccount.error.routingAndAccountNumberCannotBeSame');
        }
```

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/7efd1851-7cf9-4dfb-8bc9-aa4fcfcdb6d0

</details>

**Comment by chiragsalian** [comment] 2023-06-21 19:43
Thank you for the proposals. I'm going ahead with @Nikhil-Vats solution since it makes sense to me. I've pushed up a PR for it since its required soon. Once accepted I'll ask around to figure out how payment should be handled.

**Comment by Pujan92** [comment] 2023-06-21 19:47
@chiragsalian isn't it good to put the conditions with if/else-if for same keys to avoid overlapping the errors, I thought we already checking `!values.accountNumber` and setting error required for it then we can easily put `else if` without checking `values.accountNumber` again?

**Comment by chiragsalian** [comment] 2023-06-21 20:01
I'm not too concerned about avoiding overwriting the errors because both solutions prevents overwriting the errors. Although now I understand your solution better and I like it more since it DRYs up the code and makes it easier to read imo.

**Comment by luacmartins** [comment] 2023-06-21 20:29
Removing the blocker label since we merged/CPed the fix.

**Comment by chiragsalian** [comment] 2023-06-30 21:48
Oops this slipped my radar. I thought someone was already assigned to help out here.
I've asked in [slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1688161678111149) if someone can handle the payment here.

**Comment by chiragsalian** [comment] 2023-06-30 23:51
@kadiealexander can you help to pay @Pujan92 since i used his proposal.

**Comment by kadiealexander** [comment] 2023-07-03 04:08
How much am I paying, @chiragsalian?

**Comment by chiragsalian** [comment] 2023-07-05 23:43
I'm not sure, i asked in #bug-zero on slack.

**Comment by kadiealexander** [comment] 2023-07-06 02:44
Have issued a [contract](https://www.upwork.com/ab/applicants/1676779961368735744/hired) to @Pujan92, please let me know once you've accepted :)

**Comment by Pujan92** [comment] 2023-07-06 02:56
Thanks. @kadiealexander accepted.

**Comment by kadiealexander** [comment] 2023-07-06 03:06
Thanks @Pujan92, I've paid this!

**Closed by kadiealexander** 2023-07-06 03:06 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
