### ISSUE TITLE
[$150] Distance - System message only displays the distance rate up to three decimal places

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54011] opened 2024-12-12 10:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Workspace Settings

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates.
3. Click Add rate.
4. Add a new rate with four decimal places.
5. Click on the added rate.
6. Click Rate.
7. Change to a different rate with four decimal places.
8. Go to #admins.

## Expected Result:
The system message should display the distance rate with all four decimal places.

## Actual Result:
The system message only displays the distance rate up to three decimal places.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/265a697d-455f-4aee-b6c8-d514681d1353

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867430804610224405</li>
        <li>Upwork Job ID: 1867430804610224405</li>
        <li>Last Price Increase: 2024-12-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by VictoriaExpensify** [comment] 2024-12-13 04:46
Oh yeah, let's fix that!

I think this seems like a low-effort fix, so I'm going to reduce the bounty. If I have missed something to do with the complexity of the fix, please let me know and I can revise.

**Comment by Anas8819** [comment] 2024-12-13 07:24
### **Proposal**
### **Please re-state the problem that we are trying to solve in this issue.**
When the user Changes the distance rate and adds 4 decimals, value only upto 3 decimals in shown in System Messages

What is the root cause of that problem?
The issue seems to be with the backend. When system messages are opened and it makes a call to OpenReports following is the problem with the response.
![image](https://github.com/user-attachments/assets/381bc678-2d17-45f2-bd0d-53138b0d5628)

The data in oldValue and newValue also need to be fixed

### **What changes do you think we should make in order to solve the problem?**
The only possible solution here is to fix the backend to get the full value.

What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
What alternative solutions did you explore? (Optional)

**Comment by Anas8819** [comment] 2024-12-13 07:28
Contributor details
Your Expensify account email: anasahmed8819@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/anasa41

**Comment by marcochavezf** [comment] 2024-12-13 16:02
Given the current priorities, I'm going to close it out for now. Feel free to re-open if you disagree

**Closed by marcochavezf** 2024-12-13 16:02 UTC
Labels: External, Daily, Help Wanted, Bug
