### ISSUE TITLE
Track - Tracked expense appears on Self-DM chat in LHN when share it offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50877] opened 2024-10-16 10:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+gm103116@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go offline
2. Go to LHN> Track expense> Complete the flow
3. Select Share with my accountant> Complete the flow
4. Go online
5. Take a look at Self DM chat at LHN

## Expected Result:
Tracked expense should not appear since it is already shared

## Actual Result:
Shared expense appears on Self-DM chat in LHN when user come back online

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/30eb893e-1fe8-4182-a6db-e49dd7e67ee2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-16 10:53
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lschurr** [comment] 2024-10-18 20:53
We've added the Hot Pick label + project - need to wait for an engineer to pick this up.

**Comment by lschurr** [comment] 2024-10-21 15:01
Hey @luacmartins - just using the auto-assigner since this is a BE issue. Are you able to investigate and work on this one?

**Comment by luacmartins** [comment] 2024-10-21 19:29
My plate is quite full atm. @thienlnam do you have bandwidth to look into this one since it seems related to tracked expenses?

**Comment by thienlnam** [comment] 2024-10-21 20:41
My plate is full for a while as well, so won't be able to pick this up either. Doesn't look like this bug impacts functionality or anything perhaps in a few weeks or something

**Comment by lschurr** [comment] 2024-10-22 18:56
Going to unassign myself since this is Internal. Please add me back if we end up needing BZ for payment!

**Comment by muttmuure** [comment] 2024-10-29 16:52
Unassigning engineers who are maxed out and will call out as hot pick

**Comment by tgolen** [comment] 2024-11-01 21:16
@muttmuure @FitseTLT I'm experimenting with improving how `internal` issues are reported and worked on. Could you please open a new issue for the backend fix and use [this template](https://github.com/Expensify/App/issues/new?assignees=&labels=Hot+Pick%2C+Daily%2C+Internal%2C+AutoAssignerNewDotQuality&projects=&template=Internal.md)? It's even OK if you assign it to me. Basically, it's just not clear to me what backend fix is required for this issue, and I see that in a lot of issues. I'm attempting to make the reporting of such problem more standard so it's easier and faster for me to pick it up and work on it.

**Comment by FitseTLT** [comment] 2024-11-01 21:23
Are you requesting me to open the issue?

**Comment by mvtglobally** [comment] 2024-11-08 15:25
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-11-20 16:54
Since this is no longer reproducible, let's close

**Closed by muttmuure** 2024-11-20 16:54 UTC
Labels: Weekly, Internal, Bug, Hot Pick, AutoAssignerNewDotQuality
