### ISSUE TITLE
[$250] LHN-Archived workspace shows green dot in LHN.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45881] opened 2024-07-22 09:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4751910
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap fab - create a new workspace
3. Tap on workspace chat
4. Submit a expense using plus icon near compose
5. Navite to LHN and note green dot next to workspace chat
6. Tap profile icon -- workspaces -- workspace
7. Tap 3 dots next to workspace and delete the workspace
8. Navigate to LHN

## Expected Result:
Archived workspace must not show green dot in LHN.

## Actual Result:
Archived workspace shows green dot in LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f98801f1-2905-46ae-b11d-261609611008

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017beae0c789f3f2ea</li>
        <li>Upwork Job ID: 1816740887268923324</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103412587</li>
<li>cretadn22 | Contributor | 103412589</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by izarutskaya** [comment] 2024-07-22 09:45
We think this issue might be related to the  #vip-vsb

**Comment by izarutskaya** [comment] 2024-07-22 09:47
Production 

https://github.com/user-attachments/assets/d97f5dcf-f350-46a6-aac6-120b7f259aa9

**Comment by mountiny** [comment] 2024-07-22 11:31
Discussing [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1721641499655229)

This is a consequence of the changes we made to archiving reports; when the workspace chat is archived, the expense reports are not closed but only marked as archived. So I think we need to find a solution for this, but it does not have to be a blocker imho

**Comment by abekkala** [comment] 2024-07-25 15:58
@mountiny is this an external fix?

**Comment by mountiny** [comment] 2024-07-25 22:59
Still not clear, asked what is the conclusion here https://expensify.slack.com/archives/C01GTK53T8Q/p1721948318212529?thread_ts=1721641499.655229&cid=C01GTK53T8Q

**Comment by srikarparsi** [comment] 2024-07-26 06:34
I just checked the code and we do currently [check if the report is archived](https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/ReportUtils.ts#L2400) before showing a green dot indicator on the LHN. And we [use the isArchived rNVP](https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/ReportUtils.ts#L1314) to do that so I'm not too sure what's going wrong.

Also, I followed the reproduction steps and I'm not able to reproduce this on mac chrome:
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/02b013f3-19f9-4349-9574-d38b375b7f54">

**Comment by techievivek** [comment] 2024-07-26 07:42
I am still able to reproduce this. Sending it to External to hide the GBR when the workspace is deleted and workspace chat is archived.

**Comment by techievivek** [comment] 2024-07-26 07:48
I was able to reproduce this on Firefox but not on Chrome.

**Comment by techievivek** [comment] 2024-07-26 07:50
@situchan Do you have an android device? Can you try reproducing this locally either on Android or Firefox?

**Comment by nkdengineer** [comment] 2024-07-26 08:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Archived workspace shows green dot in LHN.

### What is the root cause of that problem?
In LHN, we use `requiresAttentionFromCurrentUser ` function to check whether the user has require action

https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/components/LHNOptionsList/OptionRowLHN.tsx#L85

And in this function, we return early if the report is archived
https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/ReportUtils.ts#L2400

But `isArchivedRoom` function only returns `true` if `report. private_isArchived` is not empty
https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/ReportUtils.ts#L1314

For LHN `optionOrReport` only has `isArchived` field so `requiresAttentionFromCurrentUser` function still returns `true`
### What changes do you think we should make in order to solve the problem?
We should change this function to return `true` if `report.isArchived` is `true`

```
function isArchivedRoom(report: OnyxInputOrEntry<Report> | OptionData, reportNameValuePairs?: OnyxInputOrEntry<ReportNameValuePairs>): boolean {
    return !!report?.private_isArchived || (report && 'isArchivedRoom' in report && report.isArchivedRoom);
}
```
https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/ReportUtils.ts#L1314

### What alternative solutions did you explore? (Optional)

**Comment by srikarparsi** [comment] 2024-07-26 22:49
Hm, I'm not sure if that is the optimal solution. Here are my thoughts: `optionItem` is of type [OptionData](https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/ReportUtils.ts#L394) which includes [Report](https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/ReportUtils.ts#L447) which has the [private_isArchived](https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/types/onyx/Report.ts#L295) property. I think we might just not be updating it properly based on changes to Onyx. We do update report [here](https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/components/LHNOptionsList/OptionRowLHN.tsx#L45) but we're passing in `optionItem` into [requiresAttentionFromCurrentUser](https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/components/LHNOptionsList/OptionRowLHN.tsx#L85).

**Comment by nkdengineer** [comment] 2024-07-26 22:53
@srikarparsi We can have another solution: we can return an extra field in `getOptionData` by calling `requiresAttentionFromCurrentUser` function using the report data.

https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/SidebarUtils.ts#L238

**Comment by nkdengineer** [comment] 2024-07-27 12:54
### Updated [proposal](https://github.com/Expensify/App/issues/45881#issuecomment-2252223682)

- Add alternative solution based on this comment https://github.com/Expensify/App/issues/45881#issuecomment-2253613862

**Comment by srikarparsi** [comment] 2024-07-29 01:31
Hi @situchan, do you think you could take a look at these proposals. @cretadn22's proposal seems like it would work to me but I haven't tested it.

**Comment by nkdengineer** [comment] 2024-07-29 03:48
@srikarparsi we used the report data here to check the report is archived or not and we assign it to `isArchivedRoom` field of `optionItem` in LHN so I don't think we need to add an extra field `private_isArchived`. What do you think about my alternative solution?

https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/SidebarUtils.ts#L310

**Comment by nkdengineer** [comment] 2024-07-29 03:52
Additional information, this bug also reproduces on Web

https://github.com/user-attachments/assets/4b976e6d-a7fd-4ba9-a9de-9b7bb3ed32bd

**Comment by srikarparsi** [comment] 2024-07-29 04:26
Hm, I'm not really sure about the alternate solution. I don't think that change is needed?

I feel like the most straightforward solution is changing this [line](https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/SidebarUtils.ts#L310) to 

`result.private_isArchived = report.private_isArchived;`

But I'll let @situchan weigh in here before proceeding in case there's something I'm missing.

**Comment by nkdengineer** [comment] 2024-07-29 04:39
Thanks for your feedback. As I mentioned above, `result.isArchivedRoom` is already used `ReportUtils.isArchivedRoom(report, reportNameValuePairs)` to check whether the report is deleted. So if we want to have a solution to simply check the report is archived or not we can use `optionOrReport.isArchivedRoom` here and no need to update or add any other field. Updated [proposal](https://github.com/Expensify/App/issues/45881#issuecomment-2252223682)  to include this solution.

```
if (
    isArchivedRoom(optionOrReport, getReportNameValuePairs(optionOrReport?.reportID)) || ('isArchivedRoom' in optionOrReport && optionOrReport.isArchivedRoom) ||
    isArchivedRoom(getReportOrDraftReport(optionOrReport.parentReportID), getReportNameValuePairs(optionOrReport?.reportID))
) {
    return false;
}
```
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/ReportUtils.ts#L2418-L2419

**Comment by situchan** [comment] 2024-07-29 05:11
reviewing today

**Comment by techievivek** [comment] 2024-07-30 10:12
@srikarparsi I will let you handle this GH since you seem to have context over it. Thanks.

**Comment by nkdengineer** [comment] 2024-07-30 18:11
Add more explanations about my proposal:

1. If we get `isArchivedRoom` here we only need to call `isArchivedRoom` function one time and we can reuse this as we do [here](https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/SidebarUtils.ts#L399).

And `requiresAttentionFromCurrentUser` also accepts `optionOrReport` with type `OptionData`. So we can use `isArchivedRoom` here if this field exists in `optionOrReport` otherwise use `isArchivedRoom` function. With this, we can also reduce the unnecessary calling `isArchivedRoom` and `getReportNameValuePairs` function [here](https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/ReportUtils.ts#L2400)


https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/SidebarUtils.ts#L310

2. If we only want to accept `Report` type in `requiresAttentionFromCurrentUser` function, my alternative [solution](https://github.com/Expensify/App/issues/45881#issuecomment-2252223682) already suggested this

**Comment by situchan** [comment] 2024-07-31 07:53
I don't like passing `optionItem` to `ReportUtils.isArchivedRoom(report: OnyxInputOrEntry<Report>)` in current codebase. It's against TS.

`result.private_isArchived = report.private_isArchived;` - this is risky (might cause unexpected regression) since `result.isArchived` already used in many places.

> using optionItem.isArchivedRoom in requiresAttentionFromCurrentUser is safe and simplest solution

I am 👍 on ^ (@nkdengineer's [alternative solution 2](https://github.com/Expensify/App/issues/45881#issuecomment-2252223682))

**Comment by srikarparsi** [comment] 2024-08-01 03:18
I will try to get to this tomorrow, in the meanwhile @situchan can you please take a look at @cretadn22's comment?

**Comment by situchan** [comment] 2024-08-05 18:04
We're close

**Comment by srikarparsi** [comment] 2024-08-06 05:29
Reviewed both and I'm still in favor of @cretadn22's proposal. The [OptionData](https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/libs/ReportUtils.ts#L402) type currently has two properties that both refer to the same data: `isArchivedRoom` and `private_isArchived` (from the Report type). We should only have one property for a single piece of data and should have removed `isArchivedRoom` from OptionData when we introduced `private_isArchived` to Report because OptionData "extends" Report.

As for the risky and might cause regressions point, we should remove `isArchivedRoom` from OptionData so that type checks can help and can also search for something on the lines of "isArchivedRoom = ".

**Comment by nkdengineer** [comment] 2024-08-06 05:40
@srikarparsi Thanks for your feedback. I still have a concern [here](https://github.com/Expensify/App/issues/45881#issuecomment-2257691413). `report.private_isArchived` is only a temporary here https://github.com/Expensify/App/pull/45568 while `isArchivedRoom` always correct even we will be removed in the further since it's used `isArchivedRoom` function.

Finally, I'm happy with your decision.

**Comment by srikarparsi** [comment] 2024-08-06 06:05
Yeah I see what you're saying but I don't think we should ever have two properties that point to the same value (`private_isArchived` and `isArchivedRoom` in OptionReport). I agree that switching over to `private_isArchived` will require more changes once we switch `private_isArchived` to be a part of the `reportNameValuePairs` collection but I think it's a better approach as it avoids redundant variables.

**Comment by nkdengineer** [comment] 2024-08-06 06:22
Thanks.

**Comment by abekkala** [comment] 2024-10-02 17:53
@situchan @cretadn22 paymetns sent and contracts ended - thank you! 🎉

**Closed by abekkala** 2024-10-02 17:53 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
