### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000]  welcome message value not trimmed after click save.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20013] opened 2023-06-01 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new room.
2. Open room details.
3. Open setting then welcome message
4. Type welcome message start with new line or whitespaces.
## Expected Result: 
Welcome message should trimmed after click save.
## Actual Result:  
Welcome message not trimmed after click save.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bb635bfd-81ca-4c4f-aea2-72b6ae12e9bf

https://github.com/Expensify/App/assets/43996225/01cc2147-5451-4e96-9951-fab8d4c98696

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685483613790139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab72ee2de7dd767d</li>
        <li>Upwork Job ID: 1664655083435290624</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-06-01 22:04
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Welcome message value not trimmed after click save.
### What is the root cause of that problem?
There is no trim for `welcomeMessage` here before saving
https://github.com/Expensify/App/blob/a6e6fe9252af0d3cc19966abaf550e5eba5a466c/src/pages/ReportWelcomeMessagePage.js#L46-L48
### What changes do you think we should make in order to solve the problem?
We need to Trim `welcomeMessage` value before saving
```javascript
 const submitForm = useCallback(() => {
     Report.updateWelcomeMessage(props.report.reportID, props.report.welcomeMessage, welcomeMessage.trim());
 }, [props.report.reportID, props.report.welcomeMessage, welcomeMessage]);
```
### What alternative solutions did you explore? (Optional)

**Comment by sethraj14** [comment] 2023-06-01 22:16
@kavimuru @lschurr Already proposed this fix [here](https://github.com/Expensify/App/issues/19836#issuecomment-1569224674). Should I post the proposal here too?

**Comment by ahmedGaber93** [comment] 2023-06-01 23:36
## Proposal
My [proposal](https://github.com/Expensify/App/issues/20013#issuecomment-1572849783)

**Comment by SoftEverest** [comment] 2023-06-02 00:05
### How to solve that issue?
We should remove the space from the welcome message string before saving it.
To do that, we can use **Trim()** function.

**Comment by SoftEverest** [comment] 2023-06-02 00:10
Contributor details
Your Expensify account email: dbakanov65@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011e6669bf3894ee15

**Comment by lschurr** [comment] 2023-06-02 15:28
@eVoloshchak could you review the proposals here? Is this a duplicate report?

**Comment by SoftEverest** [comment] 2023-06-02 15:34
@lschurr could you possibly assign this issue to me? I want to contribute to Expensify app firstly with this issue.

**Comment by lschurr** [comment] 2023-06-02 18:18
@eVoloshchak @alex-mechler are you able to weigh in here?

**Comment by ahmedGaber93** [comment] 2023-06-02 18:34
@lschurr @alex-mechler @eVoloshchak 
I think this issue is not duplicated for two reasons.
1. the proposal [here](https://github.com/Expensify/App/issues/19836#issuecomment-1569224674) not follow the [guideline](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#raising-jobs-and-bugs) by report the issue in slack first, not report it in other GitHub issue.

2. if we accept (NO. 1) and I think it is not acceptable, if we compare the date of reporting the issue with proposal by comment in other issue [here](https://github.com/Expensify/App/issues/19836#issuecomment-1569224674), and the date of reporting the issue with proposal in slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1685483613790139) we will find slack issue is come first.

Thanks!

**Comment by sethraj14** [comment] 2023-06-02 18:40
@ahmedGaber93 I don't think this should be a valid reason to not accept my proposal. I have clearly mentioned the issue and the proposal [here](https://github.com/Expensify/App/issues/19836#issuecomment-1569224674). 

I am trying to contribute first time here, @alex-mechler @eVoloshchak @lschurr can you please look into my proposal and the mentioned comment.

Thanks!

**Comment by reinaldosg** [comment] 2023-06-02 19:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Whitespace on welcome message is not trimmed

### What is the root cause of that problem?
Welcome message isn't trimmed upon submitting to backend

### What changes do you think we should make in order to solve the problem?
Trimming `parsedWelcomeMessage` before update

```js
function updateWelcomeMessage(reportID, previousValue, newValue) {
    // No change needed, navigate back
    if (previousValue === newValue) {
        Navigation.goBack();
        return;
    }

    const parsedWelcomeMessage = ReportUtils.getParsedComment(newValue).trim();
```

### What alternative solutions did you explore? (Optional)
Since untrimmed welcome message could be already existed by now, so I also propose to trim any existing welcome message upon showing it on the page.
```js
<TextInput
    inputID="welcomeMessage"
    label={props.translate('welcomeMessagePage.welcomeMessage')}
    multiline
    numberOfLines={10}
    maxLength={CONST.MAX_COMMENT_LENGTH}
    ref={welcomeMessageInputRef}
    value={welcomeMessage.trim()}
    onChangeText={handleWelcomeMessageChange}
    autoCapitalize="none"
/>
```

**Comment by reinaldosg** [comment] 2023-06-02 19:37
Contributor details
Your Expensify account email: reinaldogunawan@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01467d35548de40b1e

**Comment by alex-mechler** [comment] 2023-06-02 22:10
>  Is this a duplicate report?

@lschurr this is not. https://github.com/Expensify/App/issues/19836 is related to the quick action buttons, not a trimmed value. While this issue was noticed while investigating https://github.com/Expensify/App/issues/19836, they are two separate issues. 

---

@sethraj14, @ahmedGaber93 is correct here. The [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#raising-jobs-and-bugs) clearly state to report bugs via Slack (see step 6). Even though you found the issue while investigating https://github.com/Expensify/App/issues/19836, different bugs should be reported through Slack. In addition, this bug had already been reported on Slack prior to you commenting on 19836.

--- 

@eVoloshchak can you please review the proposals here when you get a minute? Thanks!

**Comment by will0225** [comment] 2023-06-06 17:09
I want to work on this

**Comment by eVoloshchak** [comment] 2023-06-06 18:38
@kavimuru's [proposal](https://github.com/Expensify/App/issues/20013#issuecomment-1572849783) here looks good to me!
All of the proposals are essentially the same, (since we just need to call `.trim()`), so I think we should proceed with the first proposal

🎀👀🎀 C+ reviewed!
cc: @alex-mechler

**Comment by lschurr** [comment] 2023-06-15 22:21
@eVoloshchak @ahmedGaber93 - please apply for the job in Upwork: https://www.upwork.com/jobs/~01ab72ee2de7dd767d

**Comment by lschurr** [comment] 2023-06-15 22:21
@eVoloshchak do we need a regression test for this one?

**Comment by eVoloshchak** [comment] 2023-06-16 15:32
> do we need a regression test for this one?
I don't think we need a regression test here. The bug isn't impactful and kind of an edge case

**Comment by lschurr** [comment] 2023-06-20 15:27
Offers sent in Upwork.

**Comment by lschurr** [comment] 2023-06-20 18:31
I paid $1500 to both. Closing!

**Closed by lschurr** 2023-06-20 18:31 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by ahmedGaber93** [comment] 2023-06-20 18:40
@lschurr Sorry, it is my fault, but I am talking about issue reporter Bounty 250$
My offer should be $ 1750, not 1500$

**Comment by lschurr** [comment] 2023-06-20 18:46
Ah, gotcha! I didn't notice that you were also the reporter on this one @ahmedGaber93. I'll add that $250.

**Comment by ahmedGaber93** [comment] 2023-06-20 18:51
@lschurr I received it, Thanks!
