### ISSUE TITLE
[$500] Conversation - Time zone & email details are displayed for a user you have never interacted with

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32557] opened 2023-12-06 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open a conversation with a user that you have never interacted with
2. Click on the header to open detail page

## Expected Result:
The time zone and email details should not be displayed for the user

## Actual Result:
Time zone and email details are displayed in details page for a user you have never interacted with

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b0ebfa70-19ff-4af6-bb84-4d37f77a7b4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018046a7895201312e</li>
        <li>Upwork Job ID: 1732352542844977152</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-12-06 11:38
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Profile page shows email and timezone for non-validated user.

### What is the root cause of that problem?
Both email and timezone sections do not take validated user status into account. They only check whether the user data exists:

Email:
https://github.com/Expensify/App/blob/403182a1a716878d0b4a9ee0ed7a376881aedba8/src/pages/ProfilePage.js#L204-L205

Timezone:
https://github.com/Expensify/App/blob/403182a1a716878d0b4a9ee0ed7a376881aedba8/src/pages/ProfilePage.js#L230

### What changes do you think we should make in order to solve the problem?
Users that you have not interacted with has a flag of `validated = false`. We can use is to conditionally display those sections.

Add a new conditional:
```javascript
const isUserNotValidated = details?.validated === false
```

Then, conditionally render sections:
Email:
```javascript
login && !isUserNotValidated ? // rest of the email section
```

Timezone:
```javascript
{shouldShowLocalTime && !isUserNotValidated && <AutoUpdateTime timezone={timezone} />}
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by ZhenjaHorbach** [comment] 2023-12-06 11:38
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Conversation - Time zone & email details are displayed for a user you have never interacted with 

## What is the root cause of that problem?

We do not have additional conditions for hiding time zones and email details

## What changes do you think we should make in order to solve the problem?

In order to understand whether we interacted with the user or not, we can use `lastMessageText` from report 

const isNeverrInteracted = !!props.report.lastMessageText

And then add this condition for :

https://github.com/Expensify/App/blob/403182a1a716878d0b4a9ee0ed7a376881aedba8/src/pages/ProfilePage.js#L115

And 

https://github.com/Expensify/App/blob/403182a1a716878d0b4a9ee0ed7a376881aedba8/src/pages/ProfilePage.js#L204



## What alternative solutions did you explore? (Optional)
NA

**Comment by s77rt** [comment] 2023-12-06 14:35
I'm not sure if this is a bug. Discussing some related "hidden" functionality on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1701872319874829).

**Comment by puneetlath** [comment] 2023-12-06 15:31
@izarutskaya was this something you caught as part of a regression test? If so, we need to update the test as some of the logic has changed here: https://github.com/Expensify/Expensify/issues/342920

**Comment by lanitochka17** [comment] 2023-12-07 17:08
@puneetlath Yes, this is part of a regression test
https://expensify.testrail.io/index.php?/tests/view/4046427

**Comment by puneetlath** [comment] 2023-12-08 20:52
Thanks @lanitochka17 I've created an issue to update that test here: https://github.com/Expensify/Expensify/issues/345890

I'm going to go ahead and close this bug report out.

**Closed by puneetlath** 2023-12-08 20:52 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
