### ISSUE TITLE
Web -  LHN shows a message that has been flagged as Intimidation or Bullying as an "alternateText"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23570] opened 2023-07-25 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. From account B report the message as Intimidation or Bullying
3. Notice in the LHN the reported hidden message still shows as alternateText

## Expected Result:
 Like messages reported as Harrasment/Assault, messages flagged as Intimidation or Bullying should not be shown in LHN "alternateText" section

## Actual Result:
The flagged message still shows as an alternateText in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4cf8f596-822f-4302-9ca2-3378563106aa

https://github.com/Expensify/App/assets/93399543/eb1cf436-57d7-4813-8717-e7fe6a82e1c2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AmjedNazzal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690212523695399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-25 17:35
## Proposal
AmjedNazzal on GH
### Please re-state the problem that we are trying to solve in this issue.
LHN shows a message that has been flagged as Intimidation or Bullying as an "alternateText"
### What is the root cause of that problem?
The issue is that OptionsListUtils.getLastMessageTextForReport is only accounting for the case where MODERATOR_DECISION is PENDING_REMOVE and not PENDING_HIDE and so when a message is hidden but not deleted we still push it through to the LHN as "alternateText";
https://github.com/Expensify/App/blob/c1267cad27b38c2dd35a48823fb7a4c82fe029c6/src/libs/OptionsListUtils.js#L411-L417
### What changes do you think we should make in order to solve the problem?
We first need to make isPendingHide function in ReportActionUtils
```javascript
function isPendingHide(reportAction) {
    return lodashGet(reportAction, 'message[0].moderationDecisions[0].decision') === CONST.MODERATION.MODERATOR_DECISION_PENDING_HIDE;
}
```
We then can change OptionsListUtils.getLastMessageTextForReport to account for pending hide messages
```javascript
if (ReportActionUtils.isPendingRemove(lastNonWhisper) || ReportActionUtils.isPendingHide(lastNonWhisper)) {
    const latestVisibleAction =
        _.find(
            allSortedReportActions[report.reportID],
            (action) => ReportActionUtils.shouldReportActionBeVisible(action, action.reportActionID) && !ReportActionUtils.isWhisperAction(action) && !ReportActionUtils.isPendingHide(action),
        ) || {};
    lastMessageTextFromReport = lodashGet(latestVisibleAction, 'message[0].text', '');
}
```
We also need to account for the return of "\__fake__" in SideBarUtils in case the hidden message is in a thread where no other message is before it, this way it would return "No Activity Yet".
```javascript
result.alternateText = lastMessageTextFromReport.length > 0 && lastMessageTextFromReport !== '__fake__' ? lastMessageText : Localize.translate(preferredLocale, 'report.noActivityYet');
```
### What alternative solutions did you explore? (Optional)
### Result
https://github.com/Expensify/App/assets/74202751/efc63f18-e72e-472a-a7ab-45fb19c3f5d1





Kateryna Becciv
  [2 minutes ago](https://expensify.slack.com/archives/C049HHMV9SM/p1690306351265059?thread_ts=1690212523.695399&cid=C049HHMV9SM)
Reproduced
Recording #3898.mp4
 


Reply…
Also send to expensify-bugs

**Comment by sonialiap** [comment] 2023-07-28 14:40
Reproducible

Hmm looks like we should have fixed this in this issue https://github.com/Expensify/App/issues/21497, right @greg-schroeder ?

**Comment by sonialiap** [comment] 2023-07-28 14:48
Dupe of https://github.com/Expensify/App/issues/21890

**Closed by sonialiap** 2023-07-28 14:48 UTC
Labels: Daily, Bug
