### ISSUE TITLE
[HOLD for payment 2024-02-19] [$500] [Wave 8][Ideal Nav] Workspace - Workspace is opened with 3-dot menu when long clicking and dragging over options

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35681] opened 2024-02-02 17:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Workspaces
2. Click 3-dot menu on any workspace
3. Long click on the menu option and drag below the options

## Expected Result:
App will remain on the same page as user is not clicking on the workspace

## Actual Result:
App opens the workspace page and the 3-dot menu is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd85f2cc-8564-410c-b25e-037c21e3609a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018defc2f43eca6cda</li>
        <li>Upwork Job ID: 1753500981124509696</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 28142881</li>
<li>bernhardoj | Contributor | 28142882</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 17:32
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by dangrous** [comment] 2024-02-02 19:12
oh this is odd, huh. Will try to figure it out

**Comment by dangrous** [comment] 2024-02-02 19:27
Following the instructions [here](https://expensify.slack.com/archives/C03TQ48KC/p1706899377429909) - I don't think this needs to be a blocker, as it's very minor/unusual behavior.

**Comment by bernhardoj** [comment] 2024-02-03 09:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace detail page is open when clicking on the empty parts of the 3-dots menu.

### What is the root cause of that problem?
The 3-dots menu is put inside the workspace item pressable.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/workspace/WorkspacesListPage.tsx#L179-L187
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/workspace/WorkspacesListRow.tsx#L203-L204

Even with an absolute position, the popover menu press event will bubble up to the pressable (you can test this on a plain html) if it's not handled by any pressable. 

### What changes do you think we should make in order to solve the problem?

Stop the bubbling by using `stopPropagation`.
`onClick={e => e.stopPropagation()}`

We can put it in the three dots view wrapper
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/workspace/WorkspacesListRow.tsx#L203-L204

Or a more complex solution is by having a new props to decide whether we want to stop the propagation when the popover/modal is clicked.

**Comment by dangrous** [comment] 2024-02-05 15:39
Yep, I think that makes sense to me as well! Simple and quick. Will assign.

**Comment by bernhardoj** [comment] 2024-02-06 10:50
PR is ready

cc: @ishpaul777

**Comment by sonialiap** [comment] 2024-02-19 16:45
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@ishpaul777] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@ishpaul777] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@ishpaul777] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@ishpaul777] Determine if we should create a regression test for this bug.
- [ ] [@ishpaul777] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Closed** 2024-02-20 09:46 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
