### ISSUE TITLE
[HOLD for payment 2024-04-22] [$500] Group - All 8 participants are shown in header on creating group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38052] opened 2024-03-11 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/37907

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab ---- start chat
3. Add to group 8 participants with small user name
4. Tap create group

## Expected Result:
When creating group with 8 participants, the group conversation header must display only 5 participants

## Actual Result:
When creating group with 8 participants, the group conversation header displays all 8 participants

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6409738_1710168322316!IMG_20240311_201422](https://github.com/Expensify/App/assets/78819774/ead54f4c-a9fa-47a7-aca6-5ddf5556353a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019807d7b57314faa7</li>
        <li>Upwork Job ID: 1768350318226415616</li>
        <li>Last Price Increase: 2024-03-14</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-11 14:57
We think that this bug might be related to #vip-vsp 
CC @quinthar

**Comment by lanitochka17** [comment] 2024-03-11 14:58
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment] 2024-03-11 15:23
cc @jbroma @deetergp as this was found during QAing of PR you have been involved at, thanks!

**Comment by dragnoir** [comment] 2024-03-11 16:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

All selected participants are displayed on the header (names)

### What is the root cause of that problem?

The headerView  component display all the available 8 participants.

### What changes do you think we should make in order to solve the problem?

We can limit the number of participants to 5 here

https://github.com/Expensify/App/blob/2979c4f750252ed7d45fc9fd1097ec3939b70dec/src/pages/home/HeaderView.tsx#L79

**Comment by godofoutcasts94** [comment] 2024-03-11 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group - All 8 participants are shown in header on creating group
### What is the root cause of that problem?
The root cause of the problem is here we are displaying all the participants personal details 
https://github.com/Expensify/App/blob/54691988244d9c61e291b2162152d6bf52ad952f/src/pages/home/HeaderView.tsx#L79
and then in here : 
https://github.com/Expensify/App/blob/54691988244d9c61e291b2162152d6bf52ad952f/src/pages/home/HeaderView.tsx#L81
we are displaying it
### What changes do you think we should make in order to solve the problem?

We can limit it to just display 5 participants by doing this :
```
    const participantPersonalDetails = OptionsListUtils.getPersonalDetailsForAccountIDs(participants.slice(0, 6), personalDetails);
```
### What alternative solutions did you explore? (Optional)
N/A

### Result : 

https://github.com/Expensify/App/assets/158435970/cee9ba7a-c21a-4d47-936e-3616cbe25fb3

**Comment by godofoutcasts94** [comment] 2024-03-11 17:35
@deetergp Before you mentioned the issue, I already had that solution.

**Comment by deetergp** [comment] 2024-03-13 07:44
Still sorting this one out on the original GH.

**Comment by dragnoir** [comment] 2024-03-14 11:55
@deetergp I posted a comment here https://github.com/Expensify/App/pull/37907#issuecomment-1991219351 to explain how I think that the original GH is not solving the real issue

**Comment by DinCorp777** [comment] 2024-03-14 22:00
Proposal

Issue: This issue is being caused due to text overflowing in a given area. 

Proposed Solution: We can extract the first five Usernames within the chat participants and only display their names. We may want to add a way to trunc the concatenated names if the text overflows.

**Comment by Pujan92** [comment] 2024-03-15 10:11
@mountiny I am not sure whether we need to restrict to 5 here or not, Reason - Currently users can see all group users in the ellipsis tooltip if it overflows. Raised same point [here](https://github.com/Expensify/App/pull/37907#issuecomment-1999319506)

**Comment by mountiny** [comment] 2024-03-15 10:45
I think we want to keep only 5 members in the report name

**Comment by DinCorp777** [comment] 2024-03-15 10:50
Contributor details
Your Expensify account email: info@excel-pros.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018a4006af512d5d51

**Comment by Pujan92** [comment] 2024-03-16 15:20
@dragnoir's [proposal](https://github.com/Expensify/App/issues/38052#issuecomment-1988841154) is straightforward and looks good to me for limiting participants for the report header.

🎀👀🎀 C+ reviewed

**Comment by godofoutcasts94** [comment] 2024-03-16 16:14
> @dragnoir's [proposal](https://github.com/Expensify/App/issues/38052#issuecomment-1988841154) is straightforward and looks good to me for limiting participants for the report header.
> 
> 🎀👀🎀 C+ reviewed

Hey @Pujan92 ! I Want to know why not my [proposal](https://github.com/Expensify/App/issues/38052#issuecomment-1989035112)

**Comment by Pujan92** [comment] 2024-03-16 16:29
> Hey @Pujan92 ! I want to know why not my [proposal](https://github.com/Expensify/App/issues/38052#issuecomment-1989035112) ?

@dragnoir is the first to propose and applying a limit to `participantAccountIDs` is enough, kind of similar to what we did [here](https://github.com/Expensify/App/pull/37907).

**Comment by deetergp** [comment] 2024-03-27 04:17
PR has been merged and is currently being tested on staging.

**Closed** 2024-04-23 10:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
