### ISSUE TITLE
[$250] Web - Task - Contact number is not set as an assignee followed by @expensify.sms via [] method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40518] opened 2024-04-18 22:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39475
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any chat
3. Type [] @<contact number followed by @expensify.sms> <task_name> and send to chat

## Expected Result:
Task gets created with the contact number set as the assignee

## Actual Result:
No user is filled out as the assignee

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ff9a8042-91bb-436e-86a4-67abb513673f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107ae9ef02190251b</li>
        <li>Upwork Job ID: 1783250182918488064</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-18 23:00
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment] 2024-04-18 23:00
@johncschuster FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by nkdengineer** [comment] 2024-04-19 07:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No user is filled out as the assignee

### What is the root cause of that problem?
For the `mentionWithDomain` that we don't have the login data of it in `personalDetails`, `assignee` value is empty and then the task is created without assignee.

https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/pages/home/report/ReportFooter.tsx#L111


### What changes do you think we should make in order to solve the problem?
If `assignee` value here is empty object, we should create a optimistic personal detail for this and also create optimistic chat report as we do in `setAssigneeValue` function [here](https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/libs/actions/Task.ts#L658).

https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/pages/home/report/ReportFooter.tsx#L111

1. Create a util like `buildOptimisticTaskDataForNewAssingee` that will merge the optimistic data to Onyx and  return an optimistic personal detail and an optimistic assigneeChatReport

```
function buildOptimisticTaskDataForNewAssingee(assigneeLogin: string) {
    const assigneeAccountID = UserUtils.generateAccountID(assigneeLogin);
    let report: OnyxEntry<Report> | undefined = buildOptimisticChatReport([assigneeAccountID]);
    report.isOptimisticReport = true;

    // When assigning a task to a new user, by default we share the task in their DM
    // However, the DM doesn't exist yet - and will be created optimistically once the task is created
    // We don't want to show the new DM yet, because if you select an assignee and then change the assignee, the previous DM will still be shown
    // So here, we create it optimistically to share it with the assignee, but we have to hide it until the task is created
    if (report) {
        report.isHidden = true;
    }
    Onyx.set(`${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`, report);

    const optimisticPersonalDetailsListAction = {
        accountID: assigneeAccountID,
        avatar: allPersonalDetails?.[assigneeAccountID]?.avatar ?? UserUtils.getDefaultAvatarURL(assigneeAccountID),
        displayName: assigneeLogin,
        login: assigneeLogin,
    };
    Onyx.merge(ONYXKEYS.PERSONAL_DETAILS_LIST, {[assigneeAccountID]: optimisticPersonalDetailsListAction});
    return {assignee: optimisticPersonalDetailsListAction, assigneeReport: report}
}
```

2. Call the function above here if `assignee` is empty object to get the optimistic data.

```
let assignee: OnyxTypes.PersonalDetails | EmptyObject = {};
let assigneeChatReport = undefined;
if (mentionWithDomain) {
    assignee = Object.values(allPersonalDetails).find((value) => value?.login === mentionWithDomain) ?? {};
    if (!Object.keys(assignee).length) {
        const optimisticDataForNewAssignee = ReportUtils.buildOptimisticTaskDataForNewAssingee(mentionWithDomain);
        assignee = optimisticDataForNewAssignee.assignee;
        assigneeChatReport = optimisticDataForNewAssignee.assigneeReport;
    }
}
Task.createTaskAndNavigate(report.reportID, title, '', assignee?.login ?? '', assignee.accountID, assigneeChatReport, report.policyID);
```

https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/pages/home/report/ReportFooter.tsx#L111

### What alternative solutions did you explore? (Optional)
NA

**Comment by johncschuster** [comment] 2024-04-24 21:42
Agreed that this fits into #vip-vsb.

**Comment by s77rt** [comment] 2024-04-25 22:21
@nkdengineer Thanks for the proposal. Your RCA is correct. The solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/40518#issuecomment-2065884551)

**Comment by abzokhattab** [comment] 2024-04-25 23:07
I reported this bug [here](https://github.com/Expensify/App/pull/39475#issuecomment-2052611410).. wondering if I am eligible for reporting bounty.

cc @MonilBhavsar

**Comment by nkdengineer** [comment] 2024-04-28 15:45
@s77rt The PR is [here](https://github.com/Expensify/App/pull/41171).

**Comment by s77rt** [comment] 2024-05-21 19:48
PR was deployed to production 2 weeks ago

**Comment by nkdengineer** [comment] 2024-07-02 16:15
@johncschuster This has been on production for a while, could you help with payments here?

Thanks

**Comment by johncschuster** [comment] 2024-07-02 18:51
Payment has been issued. Thanks for your patience on this!

**Comment by johncschuster** [comment] 2024-07-03 15:41
@s77rt do you feel we need a regression test for this? If not, I think we can close this up!

**Comment by s77rt** [comment] 2024-07-03 20:01
@johncschuster I don't think this needs a regression test. It's unlikely for this to resurface again.

**Closed** 2024-08-30 18:25 UTC
Labels: Reviewing, External, Monthly, Bug
