### ISSUE TITLE
[HOLD for payment 2024-05-06] CRITICAL: [Marketing] [$500] Create training interstitial when you click `Track expense`

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#40156] opened 2024-04-12 02:40 UTC
Problem:
====
We are about to promote `Track expense` to 10MM+ existing users, most of whom have never used NewDot.  If we are lucky, they will see our marketing message and click through to check it out.  It's unlikely they have an actual expense to track at that moment, so it's more likely they are going to just sorta click around to see what's available.  Some unknown number of users will intuitively figure out our UI.  However, some number of users won't find it intuitive by itself, and will abandon the product.

Note: We are working on Stage 2 onboarding.  However, it doesn't exist today.  Additionally, even if it did, it only targets new signups -- not historical signups.  Furthermore, it only educates a single use case.

Solution:
====
Show "inline/on-demand training" the first time you use the `Track expense`, to:

1. Explain what this feature does from a functional basis
2. Preview how it works, to make it less scary and encourage them to give it a shot
3. Highlight the major use cases they should be using it for

It would work like this:

```
<gif combo roll>

[ ] Don't show me this again
(   Tell me more!    )
(     Got it!        )
```

The components are:

1. A modal interstitial that shows when you tap it
2. A looping Lottie animation walking through all the animations we've already made
3. A checkbox to cause this to be hidden in the future (which sets `dismissedTrackTraining=1` in Onyx locally)
4. A button that links to HelpDot for Track
5. A button to continue

![Image](https://github.com/Expensify/App/assets/575186/813d7110-1f98-4478-af7d-8a820a9f6b26)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01978ee6c0535caae9</li>
        <li>Upwork Job ID: 1778617803608776704</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by rushatgabhane** [comment] 2024-04-13 08:18
🎀 👀 🎀 

Let's assign @tienifr to implement this feature

**Comment by rushatgabhane** [comment] 2024-04-13 08:19
@yuwenmemon is OOO until 16th, so I've asked someone else to assign themselves to this urgent issue

**Comment by srikarparsi** [comment] 2024-04-13 19:12
Taking this over @yuwenmemon

**Comment by srikarparsi** [comment] 2024-04-13 19:18
@tienifr's proposal looks good to me as well. Assigning

**Comment by srikarparsi** [comment] 2024-04-16 00:50
Hey @tienifr, for this point in your proposal:

> and potentially call an NVP endpoint to mark this in the back-end

I created an NVP called HAS_SEEN_TRACK_TRAINING = "hasSeenTrackTraining" in the backend that you can set using SET_NAME_VALUE_PAIR in the frontend. Similar to how it is done [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/libs/actions/Report.ts#L3026).

**Comment by srikarparsi** [comment] 2024-04-16 18:47
cc @dubielzyk-expensify since I believe you were working on the video.

**Comment by dubielzyk-expensify** [comment] 2024-04-17 05:10
I'll add myself here so I can help with PRs and I'll upload the video when it's done. It's posted to TCW [here](https://expensify.slack.com/archives/C03KN50J0PM/p1712721664431799)

**Comment by shawnborton** [comment] 2024-04-17 10:19
Thanks Jon!

**Comment by srikarparsi** [comment] 2024-04-17 23:10
Hey @tienifr, do you think you could give an ETA for when the PR will be ready for review? Thanks!

**Comment by srikarparsi** [comment] 2024-04-19 04:09
Hey @tienifr! Friendly bump on the above :)

**Comment by dubielzyk-expensify** [comment] 2024-04-19 04:20
Update that TCW came back with videos. Only minor feedback so should get final files early next week :)

**Comment by srikarparsi** [comment] 2024-04-22 03:49
Hey @tienifr! We're trying to get the PR out by end of day Monday or early Tuesday. If you could mention me whenever you push the PR, I can help with an initial review along with @rushatgabhane :)

**Comment by srikarparsi** [comment] 2024-04-22 07:25
We should show this training every single time unless `Don't show me this again` is checked. Which means that we should only set the `HAS_SEEN_TRACK_TRAINING` when the checkbox is checked and `Got it` is pressed.

> I also need this because I couldn't find it in HelpDot. Is it [this one](https://help.expensify.com/articles/expensify-classic/expenses/Track-mileage-expenses)?

Hm, that looks like it's only for mileage. I'll check and get back to you on that but you can use that link for the initial PR for now.

**Comment by dubielzyk-expensify** [comment] 2024-04-22 22:45
Here's the video: 
[onboarding-track-video.mp4.zip](https://github.com/Expensify/App/files/15069223/onboarding-track-video.mp4.zip)

**Comment by srikarparsi** [comment] 2024-04-23 09:42
Hey! Yes, I believe so. I'm not exactly sure either how to do this but I checked internally. I'll upload the asset and give you the url.

**Comment by francoisl** [comment] 2024-04-23 17:11
Hi, the video is ready and available.

You can use the path `${CLOUDFRONT_URL}/videos/guided-setup-track-business.mp4` from the code.

**Comment by srikarparsi** [comment] 2024-05-09 04:18
Hi @rushatgabhane and @tienifr, this PR introduced this [bug](https://github.com/Expensify/App/issues/41148) which we fixed with a [300ms timeout](https://github.com/Expensify/App/pull/41244/files). I'm still not sure if this is the best way to do this so I wanted to ask if you guys had any other ideas.

**Comment by rushatgabhane** [comment] 2024-05-09 05:40
@srikarparsi please attach payment summary for this issue 🙇

**Comment by srikarparsi** [comment] 2024-05-12 16:58
Hey @rushatgabhane! Since this was a pretty big PR and it only caused one small regression, we can pay $250 for you and tienifr each without the deduction. It would be great though if you could take a look at this [comment](https://github.com/Expensify/App/issues/40156#issuecomment-2101905363) and check if there’s a better approach for fixing this [regression](https://github.com/Expensify/App/issues/41148). More information about the fix is [here](https://github.com/Expensify/App/issues/41148#issuecomment-2083496807) and we’re essentially looking for a good way to queue the next animation once the previous animation is complete.

**Comment by JmillsExpensify** [comment] 2024-05-12 19:22
Waiting for BZ checklist to be complete before approving payment, based on @srikarparsi's comment above.

**Comment by rushatgabhane** [comment] 2024-05-13 10:15
1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2024-05-13 10:24
>  I'm still not sure if this is the best way to do this so I wanted to ask if you guys had any other ideas.
@srikarparsi no, i don't know a better way yet. I spent time on this yesterday, but couldn't find much

**Comment by srikarparsi** [comment] 2024-05-13 21:23
Ok sounds good, @tienifr did you have a chance to look? The current solution is okay for me since we do the same thing in other [places](https://github.com/Expensify/App/blob/e6eb892e0ebe94ec63761906de3226fc3e52c059/src/components/OptionsSelector/BaseOptionsSelector.js#L371) but just want to check. If not, I believe we can proceed with payment @muttmuure since the regression steps look good to me.

**Comment by srikarparsi** [comment] 2024-05-17 17:08
Cool sounds good! I think this solution should work fine as well then. @muttmuure do you think you could help with payment or is there anything else that needs to be done? The regression steps [here](https://github.com/Expensify/App/issues/40156#issuecomment-2107184034) look good to me.

**Comment by JmillsExpensify** [comment] 2024-05-19 16:33
Still waiting for a payment summary so I can approve.

**Comment by dubielzyk-expensify** [comment] 2024-05-27 09:06
Any updates here?

**Comment by JmillsExpensify** [comment] 2024-05-31 03:49
I flagged with Matt Moore via DM but he's OOO until Monday

**Comment by JmillsExpensify** [comment] 2024-06-06 04:16
I don't see the `High Priority` label on this issue, right?

**Comment by JmillsExpensify** [comment] 2024-06-06 04:17
In any case, @muttmuure I need a summary on this issue when you're back from OOO.

**Comment by muttmuure** [comment] 2024-06-06 09:49
Going to give the benefit of the doubt that this is at least a HIGH issue, since it has CRITICAL status in the project

@rushatgabhane - C+ $500
@tienifr - C $500

**Comment by JmillsExpensify** [comment] 2024-06-06 20:46
$500 approved for @rushatgabhane

**Closed** 2024-06-12 10:12 UTC
Labels: External, Weekly, NewFeature, Task, Awaiting Payment
