### ISSUE TITLE
[$250] Desktop - App Redirection - Blank page is displayed when opening a deep link for Account B profile

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28717] opened 2023-10-03 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with account A in the desktop app
2. Login with account B in the web app
3. Navigate to the user profile page in the web app
4. Refresh the browser
5. A prompt should appear asking to 'Open the link in New Expensify'
6. Click on it and wait for the desktop app to open
7. Verify the user profile page for account B is displayed in the desktop app

## Expected Result:
At step 7, account B profile page is displayed in the desktop app

## Actual Result:
At step 7, when app is opened, a blank screen is displayed. Only when the app is quitted and relaunched then the user B will be logged in for the desktop app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/803b5069-cf2c-4ab4-9e3f-35386e0e4b8c

![Bug6223168_1696333932551!Screen_Shot_2023-10-03_at_2 51 46_PM](https://github.com/Expensify/App/assets/78819774/e122f297-8b1d-4742-8c23-0da1493db742)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014173143d046b938b</li>
        <li>Upwork Job ID: 1709202255470276608</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-03 14:57
Leaving this open in case people can still repro

**Comment by mountiny** [comment] 2023-10-03 18:08
QA was not able to repro now, might be related to the site slowness too https://expensify.slack.com/archives/C9YU7BX5M/p1696354755260329?thread_ts=1696340542.134169&cid=C9YU7BX5M

**Comment by lanitochka17** [comment] 2023-10-11 21:31
Hello 
Issue reproducible on Build 1.3.81-7

https://github.com/Expensify/App/assets/78819774/0f7bdd7b-40e0-42ce-bcd8-44413e968216

**Comment by koko57** [comment] 2023-10-16 08:13
This looks like the same root cause like https://github.com/Expensify/App/issues/27418. This probably will be fixed by this https://github.com/Expensify/App/pull/28984

**Comment by laurenreidexpensify** [comment] 2023-10-16 12:48
@mountiny do you agree ^^

**Comment by koko57** [comment] 2023-10-16 12:54
Checking on my branch - it should be working 😃 

https://github.com/Expensify/App/assets/28020445/28f9a950-e8e4-4cc3-b00c-97e147b91f1c

**Closed** 2023-10-16 13:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
