### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500]  Search - Focused account hidden by "Star a chat, get $250." when navigating with an arrow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34112] opened 2024-01-08 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to NEwDot
2. Click on the green + button
3. Click on the "Start chat" option
4. Go down the list around 10-15 accounts using keyboard arrows

## Expected Result:
Focused account should be visible

## Actual Result:
Focused account is hidden by "Star a chat, get $250." banner when navigating with an arrow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/764d82cf-3048-4747-a787-1cfc3dc0c629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010450be8409118daf</li>
        <li>Upwork Job ID: 1744446534096453632</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28120212</li>
<li>bernhardoj | Contributor | 28120213</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-08 19:58
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Focused account is hidden by "Star a chat, get $250." banner when navigating with an arrow.

## What is the root cause of that problem?

This happens because the ScrollView height does not account for the "Star a chat, get $250." banner's height.

## What changes do you think we should make in order to solve the problem?

We need to adjust the styling of the ScrollView to account for the "Star a chat, get $250." banner's height.

**Comment by jayeshmangwani** [comment] 2024-01-08 20:10
I am not able to reproduce this issue on mac chrome, @ikevin127  are you able to reproduce the issue ?

**Comment by ikevin127** [comment] 2024-01-08 22:40
@jayeshmangwani I'm on MacOS too and I can repro on Chrome, Firefox and Safari.

It can be easily reproduced by navigating from first to last item by pressing Up arrow once.

**Comment by bernhardoj** [comment] 2024-01-09 05:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When scrolling through the new chat list with a keyboard arrow, the bottom items are hidden by the referral section.

### What is the root cause of that problem?
In short: we scroll to the wrong index

Detail:
When we use the arrow key, it will call `scrollToIndex` for each item. We need a section and item index to scroll inside a SectionList. If we look at the scroll logic, we are reducing the section index for every empty section (section without data)
https://github.com/Expensify/App/blob/d1e1550f2f04d8cca735e775d18a6bb56d9575b7/src/components/OptionsSelector/BaseOptionsSelector.js#L394-L404

And the reason for that is written in the comment above. But if we log inside the `getItemLayout` (the data, 1st param), we can see that the empty sections are still available on the list data, not stripped out.

On the new chat page, we have one empty section (index 0) for selected users (if we haven't select anyone),
https://github.com/Expensify/App/blob/0c5a2cb87f422eb1fad2939cd9d517f66c1e02fb/src/pages/NewChatPage.js#L78-L80

and then we have the Recents (index 1) and Contacts (index 2) section.

So, every time we call `scrollToIndex`, it will scroll to the previous section location, for example, when we are navigating through the Contacts section with an arrow key, instead of scrolling to section 2, we scroll to section 1 because of the assumption that empty section is strips out from the list. That's why the scrolling location is wrong.

(we can verify this root cause by selecting at least one user (to group) and the scrolling will work fine)
### What changes do you think we should make in order to solve the problem?

The reducing section index logic was [added](https://github.com/Expensify/App/pull/7702) ~ 2 years ago, maybe the bug happened at that time, but looks like it's not relevant anymore with the proof of `getItemLayout` is still called for empty section. So, we can remove the reducing section index logic.
https://github.com/Expensify/App/blob/d1e1550f2f04d8cca735e775d18a6bb56d9575b7/src/components/OptionsSelector/BaseOptionsSelector.js#L397-L402

I have tested on all platforms and no error happens.

**Comment by zanyrenney** [comment] 2024-01-11 11:49
@c3024 please review the proposals.

**Comment by sourcecodedeveloper** [comment] 2024-01-14 14:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Click on Start Chat option, go down the list and notice the focused option is hidden by footer "Start chat, get $250" when navigating with arrow keys.

### What is the root cause of that problem?
The root cause is the scrollToLocation api does not take into account whether the scrolled item is in view or not and after calling scrolltolocation, the item is focused but behind or even underneath the footer banner.

https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/OptionsSelector/BaseOptionsSelector.js#L451

### What changes do you think we should make in order to solve the problem?
I would replace scrollToLocation with scrollIntoView api.

In BaseOptionsList component, add focusedOptionRef
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/OptionsList/BaseOptionsList.js#L79

```
const focusedOptionRef = useRef();
```

In renderItem, pass the focusedOptionRef to OptionRow as property

https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/OptionsList/BaseOptionsList.js#L202

```
<OptionRow
keyForList={item.keyForList}
option={item}
focusedOptionRef={focusedOptionRef}
```

In SectionList extraData prop pass focusedOptionRef

https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/OptionsList/BaseOptionsList.js#L286
extraData={focusedOptionRef}

In OptionRow.tsx, pass element ref to focusedOptoinRef
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/OptionRow.tsx#L167

```
ref={(el)=>{
    pressableRef.current = el;
    if(optionIsFocused)
    {
        focusedOptionRef.current = el;
    }
}}

```
The scrollToLocation call would get replaced by scrollIntoView api.
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/OptionsSelector/BaseOptionsSelector.js#L451

```
const element = this.list.props.extraData.current;
if (!element) {
    return;
}
element.scrollIntoView({behavior: 'smooth', block: 'center'});
```

block: 'center' centers the focused item in the view.

[poc.webm](https://github.com/Expensify/App/assets/141340971/ea213aeb-1620-481a-bc6a-a48523d7ecf1)

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2024-01-15 11:41
bump @c3024 please review the proposals? If you do not have capacity to work on this issue, please let me know and I can reassign it.

**Comment by c3024** [comment] 2024-01-15 16:26
Reviewing.

**Comment by c3024** [comment] 2024-01-17 12:13
Thanks for all your proposals. 

I think compensating for the referral CTA is a workaround. 

As the SectionList is not stripping away the empty sections, I think the simpler solution is to remove the code adjusting the index for scrolling.

So, @bernhardoj 's [proposal here](https://github.com/Expensify/App/issues/34112#issuecomment-1882222170) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by zanyrenney** [comment] 2024-01-22 15:58
reassigining the eng as @techievivek is OOO.

**Comment by zanyrenney** [comment] 2024-01-22 16:00
waiting on @techievivek

**Comment by zanyrenney** [comment] 2024-01-23 15:44
https://expensify.slack.com/archives/C01GTK53T8Q/p1706024665251019

**Comment by dangrous** [comment] 2024-01-24 20:28
@c3024 your analysis seems correct, I think @bernhardoj has the simplest solution here and we can move forward!

**Comment by bernhardoj** [comment] 2024-01-25 06:04
PR is ready

cc: @c3024

**Comment by c3024** [comment] 2024-02-04 15:17
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #7702
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/7702/files#r1477340685
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion has been started because there appears nothing that can be improved in the PR checklist that could have identified this earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
The QA steps specified [here](https://github.com/Expensify/App/pull/35129#issue-2099629283) is a suitable regression test
>1. Open new chat page
>2. Scroll down the list with the keyboard arrow down > 10 times
>3. Verify the list keeps scrolling to the bottom and that the focused user/option is not covered by the referral view (should be around the middle)

**Comment by zanyrenney** [comment] 2024-02-07 15:54
payment summary:

@bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28120213) (Contributor) PAID $500
@c3024 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28120212) (Reviewer) PAID $500

**Closed by zanyrenney** 2024-02-07 15:54 UTC
Labels: External, Daily, Internal, Awaiting Payment, Bug
