### ISSUE TITLE
[$1000] Web - Two users requesting money to each other at the same time at the same time causes console error and the second user lefts untested in the request room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26273] opened 2023-08-30 11:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open User A and User B on different tabs
2. Make sure there is no unpaid request between user A and User B
3. Click on the "+" from both user A nd user B
4. Click on request money from both user A and user B
5. Input different amount(one greater than the other) for both User A and User B
6. When the list to choose user from opens for both user A and user B, for user A choose user B and for user B choose user A
7. Request money from both user A and user B simultaneously
8. Observe the chat room when it opens the second user name will disappear after a while

## Expected Result:
Request money will appear calculating the amount that will be left to be paid with one of the users

## Actual Result:
Requested amount will cause one of the second users to disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/207cb8a3-c266-4e06-b360-e03d3f449b80

https://github.com/Expensify/App/assets/93399543/804254fa-723e-47ce-9939-ba03495bfe55

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lidiyakelay
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693385547687049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180129a6e4cab1ea2</li>
        <li>Upwork Job ID: 1705141269262184448</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by MariaHCD** [comment] 2023-08-30 12:45
At first glance, I don't think this is a deploy blocker. It's likely a race condition. From the videos, I do see that the IOU requests are being created correctly in the backend but the App isn't displaying them correctly? Or perhaps the API is not sending the correct data.

**Comment by MariaHCD** [comment] 2023-08-30 15:24
Ran out of time today but I don't think this should block the deploy so I can take a closer look tomorrow.

**Comment by luacmartins** [comment] 2023-08-30 17:59
Agree this is NAB.

**Comment by MariaHCD** [comment] 2023-09-04 09:14
We've recently deployed some changes around computing the IOU owner as part of this PR: https://github.com/Expensify/Auth/pull/8605

@lidiyakelay Can we retest this and see if the issue still persists?

**Comment by lidiyakelay** [comment] 2023-09-04 09:40
@MariaHCD I have been able to reproduce the issue on the latest version as well

https://github.com/Expensify/App/assets/59802743/b3a2b875-e2f2-44f9-9ab4-4b37fcd5f09d

**Comment by MariaHCD** [comment] 2023-09-11 10:01
Thanks, @lidiyakelay! I'll take another look at this.

**Comment by MariaHCD** [comment] 2023-09-14 10:25
Didn't get a chance to look into this just yet.

**Comment by MariaHCD** [comment] 2023-09-18 08:54
No updates just yet. Will look asap.

**Comment by MariaHCD** [comment] 2023-09-20 10:10
Focused on other priorities, getting to this asap.

**Comment by MariaHCD** [comment] 2023-09-22 08:45
Definitely looks like odd behavior:

https://github.com/Expensify/App/assets/12268372/0258c737-e718-4cab-b2cb-a02e42d7826c

It might be due to the optimistic data that we set? Because upon signing out and signing in again, the IOUs are displayed correctly:

<img width="848" alt="Screenshot 2023-09-22 at 4 44 00 PM" src="https://github.com/Expensify/App/assets/12268372/f01c931d-6408-45a4-a438-3c764bb30274">

Definitely warrants more investigation.

**Comment by situchan** [comment] 2023-09-25 10:36
No proposals yet

**Comment by MariaHCD** [comment] 2023-09-28 01:00
Still open for proposals!

**Comment by MariaHCD** [comment] 2023-10-02 07:14
Let's bump the bounty here, @muttmuure?

**Comment by MariaHCD** [comment] 2023-10-04 11:43
Just increased the bounty and we're still looking for proposals!

**Comment by s-alves10** [comment] 2023-10-05 12:40
This looks like a backend issue

Assume that `user A` sends money `request AA` to `user B` and `user B` sends money `request BB` to `user A`
When requesting money, we create an `iouReportID` and attach it to the request.
As you guess, `iouReportID AA` is different from `iouReportID BB` in general.
The backend works as below in this case
Supposing that `request AA` arrives at the backend earlier than `request BB`, the backend replaces the `iouReportID BB` with the `iouReportID AA` and returns report data for `iouReportID AA` instead of `iouReportID BB` as onyx data. The problem is that the backend doesn't returns the report actions data of the `iouReport AA` and the `chatReport` so that the user B can show correct data for `iouReport AA`.
I guess this is a backend-only issue

**Comment by MariaHCD** [comment] 2023-10-09 14:53
Hmm, interesting. I'll investigate this more.

**Comment by muttmuure** [comment] 2023-10-11 16:22
Should we take this internal @MariaHCD?

**Comment by MariaHCD** [comment] 2023-10-11 16:41
I think we should but I honestly don't have the bandwidth to investigate this right now since I'm focusing on #wave8 😅

**Comment by MariaHCD** [comment] 2023-10-16 10:06
Downgrading the priority for now. We shouldn't encounter this too often but it's still worth investigating and fixing.

**Comment by MariaHCD** [comment] 2023-10-25 14:26
Taking this internal for the time being.

**Comment by MariaHCD** [comment] 2023-11-08 14:13
Focusing on some higher priority issues, will aim to get to this asap.

**Comment by mvtglobally** [comment] 2023-11-09 21:02
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2023-11-24 13:45
Since this is no longer reproducible I'm going to close it.

**Closed by muttmuure** 2023-11-24 13:45 UTC
Labels: External, Engineering, Weekly, Internal, Help Wanted, Overdue
