### ISSUE TITLE
[$500] Web - Pin chat remains grayed out when create Split bill in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34920] opened 2024-01-22 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:**Y
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4209122
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Disable the internet connection in the device
2. From the global create menu +, select Request Money and Manual
3. Enter an amount and proceed
4. Select 2 users that don't have a existing conversation and complete the Split Bill flow
5. Navigate to one of the created individual chats
6. Pin the detail IOU page
7. Enable the internet connection

## Expected Result:
Individual chats and messages should no longer be grayed out

## Actual Result:
Individual chat remains grayed out when create Split bill in offline mode and pin individual chat ( two individual chats of same participant appears)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b9632e7c-8c5a-4a34-ab13-73f8690a4a41

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db92b9e6a35d57b1</li>
        <li>Upwork Job ID: 1749520952398688256</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2024-01-22 19:58
Maybe will get fixed here: https://github.com/Expensify/App/issues/31705

**Comment by isabelastisser** [comment] 2024-01-23 20:15
@abdulrahuman5196 is this a dupe of https://github.com/Expensify/App/issues/31705?

**Comment by isabelastisser** [comment] 2024-01-24 18:12
Bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-01-28 14:55
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-28 15:04
@esh-g I am not sure on how this issue can be fixed by #31705 . Could you add some information on the same?

**Comment by isabelastisser** [comment] 2024-01-30 18:21
Bump @esh-g on the comment above.

**Comment by isabelastisser** [comment] 2024-01-30 18:21
Waiting for proposals.

**Comment by abdulrahuman5196** [comment] 2024-01-31 11:39
We don't have any proposals yet and @esh-g also haven't confirmed. So we are keeping this issue open for proposals.

**Comment by isabelastisser** [comment] 2024-02-02 03:38
Waiting for proposals.

**Comment by isabelastisser** [comment] 2024-02-05 13:21
Still waiting for proposals.

**Comment by isabelastisser** [comment] 2024-02-07 17:25
No proposals yet.

**Comment by isabelastisser** [comment] 2024-02-13 14:22
Still waiting for porposals.

**Comment by abdulrahuman5196** [comment] 2024-02-15 09:38
Hi, @isabelastisser Could we raise in slack or reach out to expert groups since we still have no proposals?

**Comment by isabelastisser** [comment] 2024-02-16 03:28
I will raise this for discussion tomorrow.

**Comment by Tony-MK** [comment] 2024-02-19 00:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Pin chat remains grayed out when creating Split bill in offline mode

### What is the root cause of that problem?

The optimistic split transaction gets replaced by the realistic one from the backend and the ID of the report changes and the pinned report.

Hence, the [`togglePinnedReport`](https://github.com/Expensify/App/blob/39b575c6af3c1442e9452aadbb79b403b40964e6/src/libs/actions/Report.ts#L1033) function pines the optimistic report while the realistic report has returned.

https://github.com/Expensify/App/blob/39b575c6af3c1442e9452aadbb79b403b40964e6/src/libs/actions/Report.ts#L1028-L1033

### What changes do you think we should make in order to solve the problem?

Hence, the [`togglePinnedReport`](https://github.com/Expensify/App/blob/39b575c6af3c1442e9452aadbb79b403b40964e6/src/libs/actions/Report.ts#L1033) function pines the optimistic report while the realistic report has returned.

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2024-02-19 09:02
Will check on proposal we got recently today.

**Comment by isabelastisser** [comment] 2024-02-20 02:21
@abdulrahuman5196, can you please review the proposal and provide an update? Thanks!

**Comment by abdulrahuman5196** [comment] 2024-02-20 18:37
Hi, Will work on review in my morning

**Comment by abdulrahuman5196** [comment] 2024-02-22 11:46
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-23 15:38
Reviewing again

**Comment by abdulrahuman5196** [comment] 2024-02-23 15:44
@Tony-MK 's proposal here https://github.com/Expensify/App/issues/34920#issuecomment-1951503900 seems to be a reasonable one. 

@Tony-MK Could you kindly provide more information on how you would solve the issue?

Like code pointers to existing codebase? How to find the original reportID for the optimistic one?
If `togglePinnedReport` uses the optimistic information, wouldn't it affect all report types, not just split ones?

**Comment by abdulrahuman5196** [comment] 2024-02-26 10:33
@Tony-MK Could you kindly provide information on the above?

**Comment by isabelastisser** [comment] 2024-02-26 18:14
Hey @Tony-MK, please provide an update. Thanks!

**Comment by isabelastisser** [comment] 2024-02-27 21:34
Bump @Tony-MK

**Comment by Tony-MK** [comment] 2024-02-28 02:55
Hey @abdulrahuman5196 and @isabelastisser, sorry for the long delay.

I was testing the feasibility of my proposal on the current main before adding more details but encountered a problem.

Using `API.write`, the `togglePinnedState` request is sent sequentially.

However, I can't figure out how to process the `togglePinnedState` request sequentially with the use of `makeRequestWithSideEffects`. 

Weirdly, it sends the request immediately, even if the user is offline.

Could you check out my test [branch](https://github.com/Tony-MK/Expensify-App/tree/test/34920)?

#

Lastly, @abdulrahuman5196, If the request can not be sent sequentially with `makeRequestWithSideEffects`, it's more reasonable to fix this issue on the backend.

Thank you

**Comment by abdulrahuman5196** [comment] 2024-02-28 08:07
AFAIK `makeRequestWithSideEffects` is kind of last resort option which is discouraged for active use.

Anyways since we don't have any solid proposals, @isabelastisser should we reach out to expert groups to see if we have any  other proposal? Or next steps on this?

**Comment by isabelastisser** [comment] 2024-02-29 20:21
No updates in slack yet.

**Comment by teneeto** [comment] 2024-03-01 09:13
Hi, I'm Eto from Callstack - expert contributor group - and I would like to assist on this issue.

**Comment by isabelastisser** [comment] 2024-03-04 17:21
Hi @teneeto, any progress here? Thanks!

**Comment by teneeto** [comment] 2024-03-04 19:15
Hi @isabelastisser I'm still taking a look at this, Will post my update as soon as I come with a solution.

**Comment by teneeto** [comment] 2024-03-07 10:57
Hi @isabelastisser I needed to revisit an old task to add some more feature based on review. I'm making this task a priority today. Apologies for the delay.

**Comment by isabelastisser** [comment] 2024-03-07 16:59
Thanks for the update, @teneeto!

**Comment by isabelastisser** [comment] 2024-03-11 15:21
No updates yet!

**Comment by teneeto** [comment] 2024-03-12 16:22
Hi @isabelastisser, I have tried reproducing this issue severally and it's not happening at my end both on `dev` and `stage` environment.

Can we try one more time if this bug still exist?. Let me know and I'll come back to it ASAP.

https://github.com/Expensify/App/assets/22779249/3b7852d1-83d8-4630-879f-771d1ac467e1

**Comment by isabelastisser** [comment] 2024-03-14 19:21
Thanks @teneeto. I can't reproduce this either. Closing!

**Closed by isabelastisser** 2024-03-14 19:21 UTC
Labels: Engineering, Daily, Internal, Bug
