### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] mWeb - Attachment - Opened offline attachment directed to conversation page on online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48173] opened 2024-08-28 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat
3. Go offline
4. Upload a image
5. Open the image
6. Go online
7. Note User directed to conversation page

## Expected Result:
Upload and open attachment in offline, then going online user must stay in same attachment page

## Actual Result:
Upload and open attachment in offline, then going online user directed to conversation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/083f0cf4-a3a8-4dad-864d-7bb3184eda93

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e366edd029d4e402</li>
        <li>Upwork Job ID: 1829648417535865218</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 104146531</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by NJ-2020** [comment] 2024-08-28 13:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Attachment - Opened offline attachment directed to conversation page on online
### What is the root cause of that problem?
When we go to offline, we upload the attachment and click the attachment to see the detail, when we go back to online we invoke the `submitAndClose` because we send the attachment, and inside this function we will close the modal `setIsModalOpen(false)` after we sent the attachment
https://github.com/Expensify/App/blob/6697c267116daaa11c1a3c8a2c1009c90326451a/src/components/AttachmentModal.tsx#L257-L273
### What changes do you think we should make in order to solve the problem?
We can add new param inside the url or parameter inside the function i.e that tell the AttachmentModal if the user open the attachment by clicking the attachment i.e `?openType=openDetail` in case like this if user open the attachment and `?openType=submit` in case if the user just submit the attachment and invoke this code `setIsModalOpen(false)` if `openType` is equal to openDetail
### What alternative solutions did you explore? (Optional)

**Comment by NJ-2020** [comment] 2024-08-28 13:57
## Proposal
[Updated](https://github.com/Expensify/App/issues/48173#issuecomment-2315371907)

**Comment by s77rt** [comment] 2024-08-31 15:36
@NJ-2020 

> When we return online, we invoke `submitAndClose` function

This is not the case. The function is invoked as soon as you click the submit button (while offline)

**Comment by s77rt** [comment] 2024-08-31 15:38
@tsa321 Your RCA is correct. However the suggested solution is a workaround. The correct approach would be to make the comparison function correctly identify that we are viewing an image that does exist.

**Comment by s77rt** [comment] 2024-08-31 15:42
@daledah Your RCA is correct but same note as above regarding the solution. The attachment carousel should be able to tell that we are still viewing the same image even though the source did change. IOW `initialPage` should not be `-1` because the image we are viewing does exist.

**Comment by s77rt** [comment] 2024-08-31 15:44
It's worth mentioning that the `targetAttachments` values has a `reportAction` key which remains unchanged. We can make use of that.

**Comment by s77rt** [comment] 2024-08-31 19:29
@daledah A file name is not a unique identifier and thus we cannot use it for lookup.

**Comment by s77rt** [comment] 2024-09-01 07:59
@tsa321 Thanks, looks good overall

**Comment by s77rt** [comment] 2024-09-01 08:01
@daledah I'm not sure if multiple images in one report action is supported. So far I keep getting empty images, let me double check

**Comment by s77rt** [comment] 2024-09-01 08:13
@daledah It turns out we can send multiple images in one report action (although it seems a bit broken; the report action id for the second image is undefined)

```md
![image1.jpeg](https://img.freepik.com/free-photo/autumn-tree-forest-leaves-bright-yellow-generative-ai_188544-12668.jpg)

![image2.jpeg](https://img.freepik.com/free-photo/photorealistic-view-tree-nature-with-branches-trunk_23-2151478039.jpg)
```

Thus we can't use the report action id for image identification either cc @tsa321

**Comment by s77rt** [comment] 2024-09-02 04:56
@tsa321 The alternative solutions are still workarounds i.e. the correct image is still not being found and this is causing the component to have incorrect state (e.g. `attachments` is stale). One of the side effects is that on refresh we get the not found view, where we should have gotten the correct image.

**Comment by s77rt** [comment] 2024-09-02 04:57
@daledah Same note ^ The proposed solution is a workaround. We should focus on the root cause that is the image is not being found and not on the image being dismissed. Fixing the former will by nature fix the later.

**Comment by s77rt** [comment] 2024-09-06 01:26
Still looking for proposals

**Comment by s77rt** [comment] 2024-09-09 11:52
@dominictb Thanks for the proposal. The RCA makes sense but the solution does not feel right and having the BE deal with FE issues is not really something we want to implement.

**Comment by s77rt** [comment] 2024-09-11 19:14
Still no clear solution yet

**Comment by wildan-m** [comment] 2024-09-17 08:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Opened offline attachment redirected to conversation page when online.

### What is the root cause of that problem?
This check will be true when online, as the local blob url will be replaced with the remote url and `initialPage` will be `-1`

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/components/Attachments/AttachmentCarousel/index.tsx#L94-L96

### What changes do you think we should make in order to solve the problem?

Introduce a new reportAction field `optimisticUri` to store the optimistic (unuploaded blob) URL.

Fill the value when we `buildOptimisticAddCommentReportAction`

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/ReportUtils.ts#L4125

Extract value when we create targetAttachments:

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/components/Attachments/AttachmentCarousel/extractAttachments.ts#L41

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/components/Attachments/AttachmentCarousel/extractAttachments.ts#L76


```tsx
...
                    hasBeenFlagged: attribs['data-flagged'] === 'true',
                    optimisticUri: attribs['data-optimistic-uri'],
                });
....
```


Pass the value to the generated HTML.
https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/components/Attachments/AttachmentCarousel/extractAttachments.ts#L104

```tsx
....
        const optimisticUri = (action as OptimisticAddCommentReportAction).optimisticUri;
        const optimisticUriAttribute = optimisticUri ? `data-optimistic-uri="${optimisticUri}"` : '';
        const html = ReportActionsUtils.getReportActionHtml(action).replace('/>', `data-flagged="${hasBeenFlagged}" data-id="${action.reportActionID}" ${optimisticUriAttribute}/>`);
        htmlParser.write(html);
....
```

Modify `compareImage` in AttachmentCarousel for all platforms:

```tsx
    const compareImage = useCallback((attachment: Attachment) => attachment.source === source || (!!attachment.optimisticUri && attachment.optimisticUri === source), [source]);
```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/48173-attachment-modal-dismissed?expand=1)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s77rt** [comment] 2024-09-17 17:12
@wildan-m Thanks for the proposal. The RCA is correct. The suggested solution looks good to me but can we use `data-optimistic-src` attribute? That attribute is already being added to the report action html message.

**Comment by s77rt** [comment] 2024-09-17 20:54
@daledah I don't see why it wouldn't, each attachment would have its unique optimistic source

**Comment by wildan-m** [comment] 2024-09-17 20:59
[Proposal Updated](https://github.com/Expensify/App/issues/48173#issuecomment-2354920968)

@s77rt That works but the suggested changes need to be kept to preserve the optimisticSrc even if the main source URL changes.

**Comment by wildan-m** [comment] 2024-09-17 23:19
I think optimistic case only support single image upload at the moment, multiple image by markdown is not previewed when offline

**Comment by wildan-m** [comment] 2024-09-18 02:32
[Proposal Updated](https://github.com/Expensify/App/issues/48173#issuecomment-2354920968)

- Make isUploading value more accurate

**Comment by s77rt** [comment] 2024-09-18 11:50
@wildan-m Why are you still passing more data into `buildOptimisticAddCommentReportAction`? We already have what we need in `attachmentHtml`
https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/libs/ReportUtils.ts#L4134

**Comment by s77rt** [comment] 2024-09-18 11:54
@daledah The [`extractAttachments`](https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/components/Attachments/AttachmentCarousel/extractAttachments.ts#L15C10-L15C28) logic will extract attachments from a each report action independently based on its html message, if it contains 2 attachments, then two objects will be returned.

**Comment by wildan-m** [comment] 2024-09-18 12:07
> Why are you still passing more data into buildOptimisticAddCommentReportAction? We already have what we need in attachmentHtml

@s77rt that generated html will be overriden from server, so we need to store optimistic source differently and not removing it even if the main source uri replaced

**Comment by wildan-m** [comment] 2024-09-18 13:04
https://github.com/Expensify/App/issues/48173#issuecomment-2357165519

IMO currently optimistic preview only support for single image, then using optimisticSrc would be enough, but if the optimistic preview will support multiple images, we can modify the var to array e.g. optimisticSources and manipulate them in order

**Comment by s77rt** [comment] 2024-09-18 19:08
@wildan-m 

> that generated html will be overriden from server, so we need to store optimistic source differently

Ah I see. I'd really prefer to not save extra data in Onyx especially since it's data that we already have. In the attachment carousel the attachments array is updated through `useEffect` (side effect), at that time we can access both the old attachment (which contains the optimistic source) and the new attachment (from the server). Maybe we can find a way to link the two? (e.g. a way to know that this old attachment has become this new attachment)

**Comment by wildan-m** [comment] 2024-09-19 02:48
> Maybe we can find a way to link the two? (e.g. a way to know that this old attachment has become this new attachment)

@s77rt I doubt that's possible, there is no unique identifier for each attachment

- File name is not unique
- Report action ID can contain multiple attachments and some attachment report action id can be empty

**Comment by s77rt** [comment] 2024-09-19 09:13
@wildan-m The new field will make will increase the flow complexity and it requires maintenance. We are still looking for a more straightforward solution.

**Comment by wildan-m** [comment] 2024-09-19 10:40
[Proposal Updated](https://github.com/Expensify/App/issues/48173#issuecomment-2354920968)

- Add alternative solution using caching
- Branch link provided for more clarity

**Comment by s77rt** [comment] 2024-09-19 18:49
@wildan-m Thanks for the update. I don't think adding in-memory cache is the best option here. Maybe we can still use the report action id and add a sequence id to identify the correct attachment?

This will also require us to fix the empty report action ids that we get for additional attachments

**Comment by wildan-m** [comment] 2024-09-20 03:12
[Proposal updated](https://github.com/Expensify/App/issues/48173#issuecomment-2354920968)

- add alternative solution using sequence id

> Maybe we can still use the report action id and add a sequence id to identify the correct attachment?
@s77rt that's possible, but we need to also check if the `reportActionIsEdited` to avoid false positive result.

**Comment by s77rt** [comment] 2024-09-20 13:37
@wildan-m Ah this won't work well. We still need a way to identify attachments. The sequence id could change on edit.

**Comment by wildan-m** [comment] 2024-09-20 13:41
@s77rt when edit, optimistic attachment is not currently possible, that's way we need to check isEdited. Ideally attachment should have it's own unique id, but I think that's beyond the scope of this issue

**Comment by s77rt** [comment] 2024-09-20 17:39
@wildan-m I get it. Adding a id for each attachment would work but it may be an overkill. Maybe we can take another approach and rethink on which cases to dismiss the modal.

**Comment by wildan-m** [comment] 2024-09-21 04:12
> Maybe we can take another approach and rethink on which cases to dismiss the modal.
@s77rt even if we can avoid the modal from dismissed, the targetAttachments will be updated, Not found page will appear as the localurl updated.

In my opinion, using an in-memory cache solution is the most practical approach. We can clear the cache each time we open attachmentCarousel to prevent any performance regression.

**Comment by s77rt** [comment] 2024-09-21 23:49
@wildan-m Indeed the `attachments` state should be updated correctly. The cache approach still seems a little over-engineered (too much work compared to the bug impact). Yet I don't see a clear solution so far. Let's keep exploring for now

**Comment by wildan-m** [comment] 2024-09-23 06:50
[Proposal Updated](https://github.com/Expensify/App/issues/48173#issuecomment-2354920968)

- Add alternative 3 solution - dismiss when there is no attachment with the same pageIndex

@s77rt What are your thoughts?

**Comment by s77rt** [comment] 2024-09-23 19:16
@wildan-m I don't see how we can use the index to tell if the previous image is still available. This check `targetAttachments[prevInitialPageRef.current]` can always be true if the deleted attachment was not last.

**Comment by wildan-m** [comment] 2024-09-23 19:59
@s77rt yes, as described in the initial solution description, but the optional section of solution can do approximate match using report action id, file name and uploading status. we can't do exact match here

**Comment by wildan-m** [comment] 2024-09-23 22:16
[Proposal Updated](https://github.com/Expensify/App/issues/48173#issuecomment-2354920968)

- clarify optional check of alternative 3 solution by using `isAttachmentSimilar` function 

cc: @s77rt

**Comment by s77rt** [comment] 2024-09-24 16:36
@wildan-m I don't think using the "similar" approach is worth it. It's not a complete solution since we'd have some left edge cases.

**Comment by wildan-m** [comment] 2024-09-24 19:53
@s77rt Without a unique ID for the attachment, do you believe an exact match is feasible?

![image](https://github.com/user-attachments/assets/7c1afd00-51d2-4f54-bda9-37f96d586450)

**Comment by s77rt** [comment] 2024-09-25 02:30
@wildan-m I doubt matching optimistic attachment is possible. I'm hoping to find some other different approaches. If we don't get much going, I will raise this to Slack to see how we can deal with it (and to whether ignoring some edge cases is okay in that case)

**Comment by bernhardoj** [comment] 2024-09-25 14:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Opening an optimistic attachment and then the upload complete will close the carousel.

### What is the root cause of that problem?
When the attachment isn't found in the report action attachments list (by comparing the source), then the carousel will be dismissed.
https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/components/Attachments/AttachmentCarousel/index.tsx#L91-L95

This happens because the optimistic attachment source is a local file, but when the file is uploaded, the report action contains the remote source.

### What changes do you think we should make in order to solve the problem?

We need to have a unique ID for each attachment which we can use as the comparison, instead of only relying on the source.

What can we use as the ID? The report action ID. To cover multiple attachments in a single action, we can append a 0-index numbering to it, e.g., 1231512_0, 1251512_1, ...

The idea is to pass the generated ID as the route param, then, when extracting each attachment object (`extractAttachments`), also generate the ID. When comparing, we can use those ID as the fallback when comparing the source fails.

here are the steps:
1. In `getReportActionMessageFragments`, modify the HTML of each fragment to include the ID.
https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/libs/ReportActionsUtils.ts#L1338-L1355

```
function addIDToAttachmentHtml(item: Message, reportActionID: string): Message {
    let index = 0;
    return {
        ...item,
        html: item.html?.replace(/(<img.*?)(\/>)|(<video.*?)(>)/g, (_, g1, g2, g3, g4) => {
            return `${g1 || g3} data-id="${reportActionID}_${index++}"${g2 || g4}`;
        }),
    }
}

function getReportActionMessageFragments(action: ReportAction): Message[] {
    ...
    if (Array.isArray(actionMessage)) {
        return actionMessage.filter((item): item is Message => !!item).map((item) => addIDToAttachmentHtml(item, action.reportActionID));
    }
    return actionMessage ? [addIDToAttachmentHtml(actionMessage, action.reportActionID)] : [];
}
```

2. Since the HTML now contains the ID (data-id), we can access it and pass it to the route param. We need to update the ROUTE first to accept the `id` param. Do the same for VideoRenderer.
https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L93-L94

```
const route = ROUTES.ATTACHMENTS.getRoute(reportID ?? '-1', type, source, htmlAttribs['data-id'], accountID);
```

3. Next, generate the ID in `extractAttachments`. We already have the ID, but we only replace the first occurrences of `/>` and we use the `reportActionID` as the ID.
https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/components/Attachments/AttachmentCarousel/extractAttachments.ts#L97-L106
```
let index = 0;
const html = ReportActionsUtils.getReportActionHtml(action).replace(/(<img.*?)(\/>)|(<video.*?)(>)/g, (_, g1, g2, g3, g4) => {
    return `${g1 || g3} data-flagged="${hasBeenFlagged}" data-id="${action.reportActionID}_${index++}"${g2 || g4}`;
});
```

I notice that we haven't pass the ID to the video attachment object,
https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/components/Attachments/AttachmentCarousel/extractAttachments.ts#L33-L48

so, we need to pass it too.
```
reportActionID: attribs['data-id'],
```

Btw, I think we need to rename it from `reportActionID` to just `id` or `attachmentID`.

4. Now that the ID is ready, the left thing is to pass the ID route param down to AttachmentCarousel and do the comparison.
Pass it from ReportAttachments > AttachmentModal > AttachmentCarousel.

Then, compare the ID here
https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/components/Attachments/AttachmentCarousel/index.tsx#L72

```
const compareImage = useCallback((attachment: Attachment) => attachment.source === source || attachment.reportActionID === id, [source]);
```

5. Last, we need to pass the ID here every time the attachment changes.
https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/pages/home/report/ReportAttachments.tsx#L34-L40

```
const routeToNavigate = ROUTES.ATTACHMENTS.getRoute(reportID, type, String(attachment.source), String(attachment.reportActionID), Number(accountID));
```

**Comment by s77rt** [comment] 2024-09-25 18:58
@bernhardoj Thanks for the proposal. The RCA is correct. Regarding the id, the index cannot be used as id because it could change if any attachment is removed or added in between

**Comment by wildan-m** [comment] 2024-09-26 03:35
Curious with @Expensify/design opinion: @shawnborton @dubielzyk-expensify @dannymcclain 

**Context**
We have this modal dismissal issue when uploading an attachment while offline. The uploaded attachment modal preview will be dismissed when the network back online since the source url will be different:

| Before  | After |
| ------------- | ------------- |
| blob:https://...... (local blob url)  | https://staging.new..... (server url)  |

The current challenges are -- we can't exactly match the previous local attachment and uploaded attachment with the following reasons:
- File name is not unique
- Report action ID can contain multiple attachments and some attachment report action id can be empty

Adding a unique attachment id would be considered as overkill (https://github.com/Expensify/App/issues/48173#issuecomment-2364207534) since it might require backend change and not quite simple to implement especially when editing the images for multiple attachments case.

I want to know your opinion about my alternative 3 proposal https://github.com/Expensify/App/issues/48173#issuecomment-2354920968 (excluding optional logic), since it will change current behavior. With this solution, we don't need to compare the attachment to handle the dismissal, but it will change the dismissal behavior as explained in the following table:

| Before  | After |
| ------------- | ------------- |
|Dismiss if the exact image is deleted|Change the image to the image with the same index after deletion; otherwise, dismiss the modal|
|<video src=https://github.com/user-attachments/assets/198e21da-9e92-47e8-9ced-1f86f2de7983 />|<video src=https://github.com/user-attachments/assets/46b453e6-9811-47d9-9d69-ed8c36013759 />|

**Comment by bernhardoj** [comment] 2024-09-26 04:03
> Regarding the id, the index cannot be used as id because it could change if any attachment is removed or added in between

Do you found an issue with that approach?

**Comment by wildan-m** [comment] 2024-09-26 04:07
I checked Slack's behavior in this situation and found that it is similar to my proposed solution. The only difference is that Slack will revert to the initial index if there are no other attachments with the same index. We can follow that difference if needed.

I test it using private group, use personal self chat will not work, seems personal self chat not live synchronized to active devices.

https://github.com/user-attachments/assets/e3a42442-52a1-4684-bacc-e6d4d9b41249

**Comment by s77rt** [comment] 2024-09-26 11:48
@bernhardoj 

> Do you found an issue with that approach?

Not really but the idea of using a non-unique attribute as the id does not feel right

**Comment by dannymcclain** [comment] 2024-09-26 13:27
I don't think I have any issues with the behavior that you're showing [here in the After column](https://github.com/Expensify/App/issues/48173#issuecomment-2375792245). Both the before and after behavior feel pretty normal to me. So I think I would defer to engineers to decide what makes the most sense from a technical perspective.

**Comment by s77rt** [comment] 2024-09-26 14:13
@wildan-m The new behaviour seems to work well and does fix the issue. Let's go with alternative solution (3) without the `isAttachmentSimilar` and without `prevInitialPageRef` (it's same as `attachments.findIndex(compareImage)`)

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/48173#issuecomment-2354920968)

**Comment by wildan-m** [comment] 2024-09-27 07:16
@s77rt The PR is ready https://github.com/Expensify/App/pull/49832 Thanks!

**Comment by mallenexpensify** [comment] 2024-10-07 16:04
Note to self... PR hit staging on Oct 4th (posting as a reminder in case production deploy automation fails, it should be fixed now though)

**Comment by s77rt** [comment] 2024-10-11 14:12
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/20798 and https://github.com/Expensify/App/pull/44889
- The offending PR has been commented on: https://github.com/Expensify/App/pull/20798#discussion_r1797016934
- A discussion in #expensify-bugs has been started: Not needed. Unique bug
- Determine if we should create a regression test for this bug: Not yet, we still have another related [issue](https://github.com/Expensify/App/issues/50296) to fix then we can add the regression test.

**Comment by mallenexpensify** [comment] 2024-10-14 20:36
Contributor: @wildan-m  paid $250 via Upwork
Contributor+: @s77rt due $250 via NewDot

I posted in the other issue to state we need a regression test there
https://github.com/Expensify/App/issues/50296#issuecomment-2412230228

Thx!

**Closed by mallenexpensify** 2024-10-14 20:36 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-14 21:24
$250 approved for @s77rt
