### ISSUE TITLE
[$500] IOU - Description is not copied when copying IOU preview to clipboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36917] opened 2024-02-20 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to 1:1 DM.
3. Create an IOU with a description.
4. Go to IOU report.
5. Right click on the preview > Copy to clipboard.
6. Paste the content.
Note that the description is not copied anymore

## Expected Result:
The copied content will include the description, and it will be "requested $ for y".

## Actual Result:
The copied content does not include the description, and it is just "requested $".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/57494a41-7e0e-4437-93e3-105d6fb6cd72

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fae159a80486a6f8</li>
        <li>Upwork Job ID: 1759970659438272512</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-20 15:58
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by flodnv** [comment] 2024-02-20 16:40
Thanks, posted here: https://expensify.slack.com/archives/C01GTK53T8Q/p1708447230020939?thread_ts=1708444691.794139&cid=C01GTK53T8Q

**Comment by DylanDylann** [comment] 2024-02-20 17:25
@paultsimura Revert this change will re-introduce the original issue
@dukenv0307 Do you have any idea here?

**Comment by shahinyan11** [comment] 2024-02-20 18:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Old amount is copied to clipboard when the request amount is changed
### What is the root cause of that problem?
Regression as stated [above](https://github.com/Expensify/App/issues/36911#issuecomment-1954540861)
### What changes do you think we should make in order to solve the problem?
1. Define new variable `const isIOUTransactionAction = originalMessage?.IOUTransactionID` 
and replace the check of `shouldConsiderScanningReceiptOrPendingRoute` with  `(isIOUTransactionAction || shouldConsiderScanningReceiptOrPendingRoute)` in [this](https://github.com/Expensify/App/blob/8bfb26418c68c326a6043c1411917fad3f92d5f8/src/libs/ReportUtils.ts#L2345C5-L2345C160) condition 
```
const isIOUTransactionAction = originalMessage?.IOUTransactionID

if (!isEmptyObject(reportAction) && (isIOUTransactionAction || shouldConsiderScanningReceiptOrPendingRoute ) && reportAction && ReportActionsUtils.isMoneyRequestAction(reportAction)) {
```
2. Move definition of [originalMessage](https://github.com/Expensify/App/blob/8bfb26418c68c326a6043c1411917fad3f92d5f8/src/libs/ReportUtils.ts#L2357C5-L2357C85) above definition of `isIOUTransactionAction`
3. Add below code [here](https://github.com/Expensify/App/blob/6b413b241540d4257d25fd409737a250eeea6849/src/libs/ReportUtils.ts#L2405)
```
const transactionDetails = getTransactionDetails(!isEmptyObject(linkedTransaction) ? linkedTransaction : null);
```
4. Change [this](Localize.translateLocal('iou.requestedAmount', {formattedAmount: amountToDisplay})) code with below
```
Localize.translateLocal('iou.requestedAmount', {formattedAmount: amountToDisplay, comment: transactionDetails?.comment ?? ''})
```
### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-02-20 18:56
The offending PR is being reverted now

**Comment by shahinyan11** [comment] 2024-02-20 19:42
My [proposal](https://github.com/Expensify/App/issues/36917#issuecomment-1954864332) will fix this issue and  below issues
https://github.com/Expensify/App/issues/36924
https://github.com/Expensify/App/issues/36911

**Comment by flodnv** [comment] 2024-02-21 13:37
Leaving this to @srikarparsi - https://expensify.slack.com/archives/C01GTK53T8Q/p1708522618781829?thread_ts=1708444691.794139&cid=C01GTK53T8Q

**Comment by srikarparsi** [comment] 2024-02-22 01:43
Closing this out since the [revert PR](https://github.com/Expensify/App/pull/36932) takes care of it and has been CPed

**Closed by srikarparsi** 2024-02-22 01:43 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted
