### ISSUE TITLE
Android - Scan - Buttons on the scan tab of the submit expense are unresponsive

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47897] opened 2024-08-23 05:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4888928
**Email or phone of affected tester (no customers):** gatantm+88@gmail.com
**Issue reported by:**

## Action Performed:
1. Launch new expensify
2. Tap on FAB > Submit expense
3. Select Scan > Tap on any of the buttons

## Expected Result:
User can submit a scan expense

## Actual Result:
User can not submit a scan expense as all buttons are unresponsive

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/1c082ee5-f7c9-4cde-a917-27504e848232
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment] 2024-08-26 12:02
Reproducible due to [this PR](https://github.com/Expensify/App/issues/47897)

**Comment by puneetlath** [comment] 2024-08-26 19:04
QA has confirmed this is passing now. Demoting and closing.

**Closed** 2024-08-26 19:04 UTC
Labels: Reviewing, Engineering, Weekly, Bug
