### ISSUE TITLE
[$500] Assign task - Can not add assignee email that doesn't have a NewDot account yet

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33236] opened 2023-12-18 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to a Staging.new.expensify.com
2. Go to FAB
3. Click Assign Task
4. Enter title and description and navigate to next page
5. Click on Assignee
6. Enter an email that doesn't have a NewDot account yet

## Expected Result:
The assignee is added immediately and no error appears

## Actual Result:
Displays "No results found", can not add email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6315414_1702680643441!pas19-1](https://github.com/Expensify/App/assets/78819774/cd6339c5-bad9-49b5-aad1-271e37a9dfdb)

https://github.com/Expensify/App/assets/78819774/231c545c-b14d-4ae7-b8f0-2b46421ee9d8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b21a211b4e425fcc</li>
        <li>Upwork Job ID: 1736764006604431360</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-12-18 16:08
I think this is not just for users with ND account. One cannot assign a task to any user with whom they don't have a chat or a prior interaction.

This might be intended because this has been like this for as far as I remember.

**Comment by Christinadobrzyn** [comment] 2023-12-18 20:10
I think there is a reason why this doesn't work right now but I can't find the Slack chat about it.  

I don't think this is a but - it's planned but I assume it might be part of Wave 6, so going to add to Wave 6 project for a review on priority. cc @greg-schroeder

**Comment by greg-schroeder** [comment] 2023-12-18 20:15
Looking

**Comment by greg-schroeder** [comment] 2023-12-18 20:15
Think this belongs in #vip-vsb as this is related to tasks @Christinadobrzyn

**Comment by Christinadobrzyn** [comment] 2023-12-18 21:01
Asking about #vip-vsb here - https://expensify.slack.com/archives/C066HJM2CAZ/p1702933307602439

**Comment by quinthar** [comment] 2023-12-19 01:49
Dupe of https://github.com/Expensify/Expensify/issues/311912, but let's keep this one.

**Comment by Christinadobrzyn** [comment] 2023-12-19 20:45
Okay sounds good! We're collecting proposals but I wonder if this needs to be internal @c3024 what do you think?

**Comment by thienlnam** [comment] 2023-12-20 19:23
There were a few back end changes needed to allow this to happen, they should be deployed now so we can do the last FE change needed. I'll manage this issue

**Comment by mvtglobally** [comment] 2024-01-11 06:00
Issue not reproducible during KI retests. (First week)

**Comment by thienlnam** [comment] 2024-01-11 06:01
This is fixed!

**Closed by thienlnam** 2024-01-11 06:01 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
