### ISSUE TITLE
[$1000] User B still able to split the bill even when admin changes the settings

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21922] opened 2023-06-30 02:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new workspace and invite User B
3. Create a new room with the workspace created in restricted mode
4. On another window, login with User B and click on the room chat
5. Now from User B side, click on + icon and click on split bill. You are now on the Currency page of split bill (Do not close)
6. From User A side, click on header and go to settings. Change the 'Who can post' to 'Admins only'
7. Notice that on User B side, the currency page doesn't disappear. You can continue to split the bill even when admin have changed the functionality.
8. If you follow the same steps with attachment, then you can see as soon as the admin changes the 'Who can post' to 'Admins only', the picture gets disappeared on User B side which is not sent yet.
## Expected Result:
Split bill should get dismissed in a similar way how the attachment gets dismissed when admin changes the settings to 'Only admin'
## Actual Result:
User B still able to split the bill even when admin changes the settings
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bac7ebb3-a16b-4e79-9816-2f318146d00e

https://github.com/Expensify/App/assets/43996225/a1855d1c-fa97-4fee-a5fa-134e86ca5e67

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687785649051329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0a939934a385c11</li>
        <li>Upwork Job ID: 1674641490804539392</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-30 04:50
I can reproduce - adding external

**Comment by Pujan92** [comment] 2023-06-30 06:52
dupe of https://github.com/Expensify/App/issues/21902

**Comment by priya-zha** [comment] 2023-06-30 07:59
This is not a dupe. This issue was posted on Slack channel on June 26. Whereas #21902 was posted yesterday.

**Comment by Nikhil-Vats** [comment] 2023-06-30 08:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If a user is splitting bill/assigning task in a room and permissions are changed then RHN doesn't hide dynamically.

### What is the root cause of that problem?
We don't check for permission updates in the `componentDidUpdate` of `MoneyRequestAmountPage` or in the `useEffect` of `NewTaskPage`.

So if the room is archived, has any errors, or permission is changed to admin only then composer will be hidden but RHN for task or split bill won't hide.

### What changes do you think we should make in order to solve the problem?
We use the following function to hide the composer when room is archived, report has any errors or permissions are changed to admin only -
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/libs/ReportUtils.js#L2319-L2327

We should use the same function to navigate to the report dynamically in all 3 cases. To do that, we need to add the following code in `componentDidUpdate` of `MoneyRequestAmountPage` and `useEffect` of `NewTaskPage`,`NewTaskDetailsPage`, etc. so that the user is navigated to report regardless of whichever step they are on.


```javascript
if(ReportUtils.shouldHideComposer(report, reportErrors)) Navigation.navigate(ROUTES.getReportRoute(reportID));
```

I checked and `report` and `reportErrors` are available via props in both components.

We can make a new utility function for this and reuse it in both places to navigate to the parent report if permissions are changed/room is deleted or there are any errors.

### What alternative solutions did you explore? (Optional)
NA

Result -

https://github.com/Expensify/App/assets/31413407/c561eac2-2fa4-4085-9a82-8bdad3dedcd0

**Comment by mollfpr** [comment] 2023-07-03 13:41
Thank you guys for the proposals!

@Nikhil-Vats I try using `Navigation.navigate`, but it's adding a new stack to history. I can still press the browser back button, and it opens the money request page.

>- If you want to navigate to a certain report after completing a flow related to it, e.g. `RequestMoney` flow with a certain group/user, you should use `Navigation.dismissModal` with this `reportID` as an argument. If, in the future, we would like to navigate to something different than the report after such flows, the API should be rather easy to change. We do it like that in order to replace the RHP flow with the new report instead of pushing it, so pressing the back button does not navigate back to the ending page of the flow. If we were to navigate to the same report, we just pop the RHP modal.

Based on our NAVIGATION guidelines, we should use `Navigation.dismissModal` to navigate specific reports.

We can work on @namhihi237 [proposal](https://github.com/Expensify/App/issues/21922#issuecomment-1614022722), but I'd instead use `ReportUtils.shouldHideComposer` to check the report.


🎀 👀 🎀 C+ reviewed!

**Comment by Christinadobrzyn** [comment] 2023-07-03 16:21
@arosiclair will you let us know what you think of https://github.com/Expensify/App/issues/21922#issuecomment-1618293255

**Comment by Christinadobrzyn** [comment] 2023-07-06 19:57
@namhihi237 sorry to ask but I can't find your Upwork profile in our GHs. Can you send me a link to your Upwork profile so I can hire you? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-07-07 21:40
Awesome - hired you @namhihi237! @priya-zha & @mollfpr you were automatically hired. 

Internal Upwork job:  https://www.upwork.com/jobs/~01c0a939934a385c11
External Upwork job:

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:20
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing the PR and paying based on https://github.com/Expensify/App/issues/21922#issuecomment-1626188247

I'll take this back if it's still open when I return.

**Comment by sophiepintoraetz** [comment] 2023-07-24 04:25
Payments issued!

**Closed by sophiepintoraetz** 2023-07-24 04:25 UTC
Labels: Reviewing, External, Daily, Bug
