### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] propTypes warning - `policy` is marked as required in `MoneyRequestHeader`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#26991] opened 2023-09-07 19:59 UTC
![2023-09-07_09-58-32](https://github.com/Expensify/App/assets/32969087/25feced4-6546-4ce5-8bbb-146fab7ce28e)

Note this one is maybe just holding on the TS migration since we are deprecating propTypes IIRC cc @hayata-suenaga 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d965fee45c4003a6</li>
        <li>Upwork Job ID: 1700249043663089664</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-09-07 20:25
@marcaaron We're still requiring `propTypes` in JavaScript files. If there is an issue with what is specified in `propTypes` and the actual type being passed to a prop, we should keep fixing those errors 🙇 

Having correct `propTypes` will also aid TypeScript migration process as migration engineers can rely on `propTypes` when defining TypeScript types.

**Comment by azamuddin** [comment] 2023-09-09 02:15
After made a quick analysis to the related files, here's what I found and my proposed solution:

## Component Tree 
How the `policy` is used in the context of this issue: 

```
ReportScreen.js -> MoneyRequestHeader -> HeaderWithBackButton -> AvatarWithDisplayName 
```

- `policy` object is defined and first supplied in `<ReportScreen/>` 
```js
const policy = policies[`${ONYXKEYS.COLLECTION.POLICY}${report.policyID}`];
```
- `<MoneyRequestHeader/>` and `<HeaderWithBackButton/>` is only passing down the props
- Actual usage of `policy` object is in `<AvatarWithDisplayName/>` component

## propTypes Inconsistencies 
There is propTypes inconsistencies amongs components:

- Here is the `propTypes` `policy` in `<MoneyRequestHeader/>`:
```js
/** The policy which the report is tied to */
policy: PropTypes.shape({
    /** Name of the policy */
    name: PropTypes.string,
}).isRequired,
```

- Here is the `propTypes` `policy` in `<HeaderWithBackButton/>`: 
```js
/** The report's policy, if we're showing the details for a report and need info about it for AvatarWithDisplay */
policy: PropTypes.shape({
    /** Name of the policy */
    name: PropTypes.string,
}),
```

- Here is the `propTypes` `policy` in `<AvatarWithDisplayName/>`:
```js
/** The policy which the user has access to and which the report is tied to */
policy: PropTypes.shape({
    /** Name of the policy */
    name: PropTypes.string,
}),
```

As we can see from above codes, `<MoneyRequestHeader/>` marks `policy` as required, but `<HeaderWithBackButton/>` and `<AvatarWithDisplayName/>` is treating it as optional props.


## Proposed Solution

### Mark `policy` object as optional
If `policy` is actually not a required in the runtime usage, then the solution is simply remove `isRequired` mark  in the `<MoneyRequestHeader/>` `propTypes.policy`. 

This change will also fixes the `propTypes` inconsistencies amongs different components in the `Component Tree` I mentioned above.


#### Supporting evidence
If we are looking into the actual use of `policy` object in `<AvatarWithDisplayName/>` it is supplied to `ReportUtils.getIcons`, and if we open the method signature, it looks like this: 

```js
function getIcons(report, personalDetails, defaultIcon = null, isPayer = false, defaultName = '', defaultAccountID = -1, policy = undefined) {
  // the code
}
```

As we can see, `policy` here is supplied with default value of `undefined`, which means it is actually an optional parameter. So it makes sense to also mark `propTypes.policy` as optional.


## Beyond The Problem in This Component Tree

The original problem on this github issue should be solved with the proposed solution above. 

Here I just want to make an additional comments with regards to `policy` object usage in general. 

### More `propTypes` inconsistencies

In `src/pages/home/ReportScreen.js` policies propTypes is an array shape of `policy` shape that have property of `name` and `type` : 

```js
policies: PropTypes.objectOf(
    PropTypes.shape({
        /** The policy name */
        name: PropTypes.string,

        /** The type of the policy */
        type: PropTypes.string,
    }),
),
```

Meanwhile, in `src/pages/home/report/ReportActionsView.js` propTypes `policy` is defined as below: 

```js
policy: PropTypes.shape({
    /** The name of the policy */
    name: PropTypes.string,

    /** The URL for the policy avatar */
    avatar: PropTypes.string,
})
```

It has `avatar` property.


So far we have 3 different shape of the same `policy` object.

1. with `name` property only (in `<MoneyRequestHeader/>`, `<HeaderWithBackButton/>` and `<AvatarWithDisplayName/>`)
2. with `name` and `type` as in `src/pages/home/ReportScreen.js`
3. with `name` and `avatar` as in `src/pages/home/report/ReportActionsView.js`

If you are about to migrate to typescript, you will need to unify the `Policy` type / interface and shares this accross component, this will make consistent.

**Comment by azamuddin** [comment] 2023-09-09 02:19
Contributor details
Your Expensify account email: mas.azamuddin@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/muhammada1457

**Comment by yusuffindik7** [comment] 2023-09-09 19:24
During component transitions, we must prevent it from moving to the next component before the policy prop data arrives.

Contributor details
Your Expensify account email: yusuffindik7@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f0c399b94f4fb448

**Comment by abekkala** [comment] 2023-09-11 13:38
@sobitneupane have you had a chance to review the proposals that have come in?

**Comment by sobitneupane** [comment] 2023-09-14 07:23
Thanks for proposal everyone. If policy is an optional prop, it is better to remove `isRequired` and add a default value for it. [Proposal](https://github.com/Expensify/App/issues/26991#issuecomment-1712387389) from @azamuddin looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment] 2023-09-15 05:41
@tienifr I don't think your proposal is substantially different from the one selected. I think adding default value goes along with removing `isRequired`.

**Comment by sobitneupane** [comment] 2023-09-18 08:49
@tienifr It's the same change in a different file. I think that would have been caught and addressed in PR review if it also has the same console error.

If @puneetlath doesn't think otherwise, I would suggest going with https://github.com/Expensify/App/issues/26991#issuecomment-1718903800

**Comment by puneetlath** [comment] 2023-09-19 02:03
I agree with going with @azamuddin's proposal here. It seems sufficiently thorough to me for the situation. Thanks for your proposals everyone!

**Comment by sobitneupane** [comment] 2023-09-20 08:45
@azamuddin When can we expect a pull request from you?

**Comment by puneetlath** [comment] 2023-09-21 10:45
We assigned it to @azamuddin Melvin! 

@azamuddin ETA for a PR?

**Comment by puneetlath** [comment] 2023-09-24 09:21
@azamuddin I've sent you an offer on Upwork. 

For the issue you're seeing, I'm not quite sure I understand. Can you explain further? Or better yet, raise it in the #expensify-open-source channel and tag @sobitneupane and I? Thanks!

**Comment by azamuddin** [comment] 2023-09-25 02:24
Thanks @puneetlath, I have accepted the offer on Upwork. 

I run the app locally on web and ios platform, I still couldn't reproduce the issue since my account has "policy" data just fine thus the warning never appear. 

I need to ask how to reproduce the issue, but I could not join #expensify-open-source https://expensify.slack.com/archives/C01GTK53T8Q because my email is not a member, could you help me to be able to join the slack? my email is mas.azamuddin@gmail.com

**Comment by puneetlath** [comment] 2023-09-26 04:01
Hmm, interesting. So you're saying that you're no longer able to reproduce the issue? 

@sobitneupane are you able to?

**Comment by sobitneupane** [comment] 2023-09-26 06:32
I was able to reproduce the issue.

<img width="1440" alt="Screenshot 2023-09-26 at 12 13 37" src="https://github.com/Expensify/App/assets/25876548/81a39d8a-2baa-4857-a192-3a8b60be81da">

**Comment by azamuddin** [comment] 2023-09-26 14:14
@puneetlath I meant I didn't know how to reproduce it because there's no information in this GH issue (previously I just read the codebase to formulate the proposal)

But after you invited me to Slack, I read the message on how to reproduce it and I did reproduce it and make sure the issue is solved (https://expensify.slack.com/archives/C049HHMV9SM/p1693657079886579)

Already made PR here https://github.com/Expensify/App/pull/28213

**Comment by puneetlath** [comment] 2023-09-27 04:13
Ah ok, great!

**Comment by abekkala** [comment] 2023-10-10 14:41
### PAYMENTS FOR OCT 16

- @azamuddin (Contributor) - [$500 - no bonus]
- @sobitneupane (Reviewer) 🚫 Upwork payment (please request manually in Expensify Chat)

**Comment by abekkala** [comment] 2023-10-16 17:53
@sobitneupane can you complete the checklist above?

**Comment by abekkala** [comment] 2023-10-17 17:15
@azamuddin payment made and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2023-10-17 17:16
@sobitneupane can you complete the checklist above prior to requesting payment in Expensify Chat

**Comment by abekkala** [comment] 2023-10-20 13:58
Last action needed here: 

@sobitneupane  completes the checklist

Payment for: 
@sobitneupane (Reviewer) [$500 - no bonus] 🚫 Upwork payment (please request manually in Expensify Chat)

**Comment by abekkala** [comment] 2023-10-23 21:11
@sobitneupane can you complete the checklist above?

**Comment by sobitneupane** [comment] 2023-10-27 12:24
@abekkala Sorry for the delay. I was OOO. I will try to get it done in the weekend.

**Comment by sobitneupane** [comment] 2023-10-30 09:23
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/22484
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/22484/files#r1375904116
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It is an edge case and appears only for deleted workspace. It is quite difficult to catch such issues.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-30 13:57
https://github.com/Expensify/App/issues/26991#issuecomment-1772790978

Requested payment on newDot.

**Comment by abekkala** [comment] 2023-11-03 17:29
closing this as payment is handled in newdot and has already been requested

**Closed by abekkala** 2023-11-03 17:29 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:18
$500 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/26991#issuecomment-1755583673).
