### ISSUE TITLE
Subscription - Subscription settings and parts of details are missing

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43555] opened 2024-06-12 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/43128
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a Gmail account
3. Create a workspace
4. Navigate to https://staging.new.expensify.com/settings/subscription
5. Swipe up

## Expected Result:
The missing parts should be available.

## Actual Result:
Subscription settings is missing completely. Pay-per-use and Subscription size is missing from Subscription details on iOS and Android apps.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a8e9132d-4928-4d53-8352-a356652e41a0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-06-12 12:19
We think this issue might be related to the #collect project.

**Comment by jliexpensify** [comment] 2024-06-13 02:26
Heya @amyevans and @dannymcclain - sorry to assign you, but have we officially launched subscriptions on iOS and Android yet? If not, we could probably close this right?

If so, I guess we have a bug?

**Comment by dannymcclain** [comment] 2024-06-13 13:04
Yo @jliexpensify! We have not officially launched these yet—they are still in implementation.

Also, because of iOS and Android pricing/app rules, we do not show those sections or allow users to edit any information on the subscription page in native iOS and Android apps. So this is actually unreleased, expected behavior. Good to close! 🙂

**Comment by jliexpensify** [comment] 2024-06-13 23:57
Nice, thanks!

**Closed by jliexpensify** 2024-06-13 23:57 UTC
Labels: Daily, Bug
