### ISSUE TITLE
[CRITICAL][HOLD for payment 2024-05-03][Track Expense] [$500] Allow the self-DM to show up within the 'Start Chat' participant selector 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40259] opened 2024-04-15 22:31 UTC
Right now, you can only find the self-DM via the global chat search. This is not entirely intuitive that you have to search for your email / you to find the self-DM this way.

Let's allow you to select the self-DM in the chat search and have it open up the self-DM
From the global create, 
1. Click 'Start Chat'
2. Have the self-DM show up in the participant selector
3. When clicking on it, it opens up the self-DM

Note: You should not be able to add the self-DM to group

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112a1eb2ca973eaaa</li>
        <li>Upwork Job ID: 1780001898833866752</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-04-15 23:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
- When calling ReportUtils.shouldReportBeInOptionList, We do not set ```includeSelfDM: true```
### What changes do you think we should make in order to solve the problem?
 - Set ```includeSelfDM: true```
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by nkdengineer** [comment] 2024-04-15 23:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 
### What is the root cause of that problem?
- We do not call ```getFilteredOptions``` with ```includeSelfDM: true```
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ahmedGaber93** [comment] 2024-04-16 04:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Track Expense] Allow the self-DM to show up within the 'Start Chat' participant selector
### What is the root cause of that problem?
New feature.
### What changes do you think we should make in order to solve the problem?
We can follow task self assign  `SelectionList` design which create a new section at top to self assign (see attached picture below).
<details>
<summary>see task self assign design</summary>

![Screenshot 2024-04-16 at 2 32 37 AM](https://github.com/Expensify/App/assets/41129870/c6225ff6-411c-49da-9239-e3a13663e8d1)


</details>

the cases for showing section selfDM will be similar to self assign
 - section `selfDM` will display by default when search text is empty.
 - when user type search text it will displayed based on existing in search result, and under selfDM section.

 For that we need the following change:

1. we need to get `selfDM` independent in `getFilteredOptions` result, for that we need to pass `includeSelfDM` true in NewChatPage.tsx [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/NewChatPage.tsx#L71), and edit `OptionsListUtils.ts` return value to return `selfDM` independent [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/OptionsListUtils.ts#L1884)

```javascript
// NewChatPage.tsx pass `includeSelfDM` true
OptionsListUtils.getFilteredOptions(
  ... cureent params,
  false,
  false,
  {} as TaxRatesWithDefault,
  true,
);

// OptionsListUtils.ts return selfDM independent
let selfDM = allReportOptions.find(option => !!option.isSelfDM && !option.isThread);
if (searchValue && selfDM && !isSearchStringMatch(searchValue, selfDM.searchText)) {
    selfDM = undefined;
}

return {..., selfDM}

// of course we will update typesrcipt in PR
```



2. in NewChatPage.tsx [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/NewChatPage.tsx#L146) we need to add new section at the top (me)
```javascript
// recieve selfDM in useOptions
const {..., selfDM} = useOptions(...);

// add new section me at the top
if (selfDM) {
    sectionsList.push({
        title: translate('newTaskPage.me'),
        data: [selfDM],
        shouldShow: true,
    });
}
```

4. to hide add group for `selfDM`, we will update `itemRightSideComponent` [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/NewChatPage.tsx#L201) to return early null if option is `selfDM`
```javascript
const itemRightSideComponent = useCallback(...) => {
  if(item.isSelfDM) {
      return null;
  }
  ...
```

5. we also need to edit `no result found` to handle `selfDM` and hide this message when `selfDM` exist by adding `|| filteredOptions.selfDM` condition to `OptionsListUtils.getHeaderMessage` > `hasMatchedParticipant` [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/NewChatPage.tsx#L79)
```javascript
// selectedOptions.some((participant) => participant?.searchText?.toLowerCase?.().includes(debouncedSearchTerm.trim().toLowerCase())),
selectedOptions.some((participant) => participant?.searchText?.toLowerCase?.().includes(debouncedSearchTerm.trim().toLowerCase())) || filteredOptions.selfDM,
```
<details>
<summary>result</summary>

[![Screenshot 2024-04-16 at 2 32 37 AM](https://github.com/Expensify/App/assets/41129870/f5f32535-e11d-4a89-b1f8-60e8c5e29a14)](https://github.com/Expensify/App/assets/41129870/939c5054-7adb-4d75-b3b7-7fbd59f238f1)

</details>











### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-04-17 00:08
@s77rt , plz review the proposals above. 
I thought the details in the OP might be a bit too simplified but then I tested
<img width="428" alt="image" src="https://github.com/Expensify/App/assets/22508304/5b00a069-39c9-4c80-a581-b5337ef98d96">

Only other thought I had was that self DM shouldn't be prioritized any differently that whatever we're currently doing for the chats that show there.  @thienlnam , comment if you disagree.

**Comment by s77rt** [comment] 2024-04-17 02:14
@abzokhattab Thanks for the proposal. Your solution is not complete:
- Clicking on the self dm does not open the self dm
- Searching for `you` does not return the self dm

**Comment by s77rt** [comment] 2024-04-17 02:22
@ahmedGaber93 Thanks for the proposal. I don't see why we need to move the self dm to a separate section. Let's avoid that.

**Comment by nkdengineer** [comment] 2024-04-17 02:30
@s77rt Thanks for your feedback.

> Also searching for you should return the self dm
- Can you help check again. I re-tested my proposal and here is result:

https://github.com/Expensify/App/assets/161821005/df1c6d9a-7976-4f48-8425-b9c128a72600

> In step 3, we shouldn't call findSelfDMReportID because the id is already within the option item, we should do whatever we do with the Search case
- In step 3, we can update the [createChat](https://github.com/Expensify/App/blob/21ee1a3772253538bba74b2bc655213dc7bdb68a/src/pages/NewChatPage.tsx#L183) to:
````diff
const createChat = useCallback(
        (option?: OptionsListUtils.Option) => {
+          if (option?.isSelfDM) {
+              const report = getReport(option.reportID);
+              Navigation.dismissModalWithReport(report);
+              return;
            }
            ...
        },
        [selectedOptions],
    );
````

**Comment by ahmedGaber93** [comment] 2024-04-17 02:34
>  I don't see why we need to move the self dm to a separate section.

The main goal of this is ensuring display `selfDM` to the user Without having to search for it, and also this what we do in self assign task.

<details>
<summary>task self assign design</summary>

![Screenshot 2024-04-16 at 2 32 37 AM](https://github.com/Expensify/App/assets/41129870/c6225ff6-411c-49da-9239-e3a13663e8d1)


</details>

**Comment by nkdengineer** [comment] 2024-04-17 02:52
@s77rt I updated [comment](https://github.com/Expensify/App/issues/40259#issuecomment-2060227129). I have a question about your feedback:
> In step 2, updating the optionsToExclude is the correct approach and not adding more conditions to the if statement

Why is my initial solution from step 2 considered incorrect? I've tested both your suggestion and mine, and they both function correctly.

**Comment by nkdengineer** [comment] 2024-04-18 02:31
@s77rt I updated [comment](https://github.com/Expensify/App/issues/40259#issuecomment-2060227129) to address the bug you mentioned:

> Searching for you should return the self dm

**Comment by s77rt** [comment] 2024-04-18 03:54
@nkdengineer Thanks for looking into this. That makes sense! Can you please update your proposal to cover that? (all details should be in one comment)


> Why is my initial solution from step 2 considered incorrect?

Your solution was excluding the current user login and add a condition to "ignore" that exclusion. This could cause problems if we use `optionsToExclude` in other places (unless we use same condition) which kinda breaks the one source of truth logic. The correct solution is to just not exclude the current user login in the first place.

**Comment by s77rt** [comment] 2024-04-18 03:59
@ahmedGaber93 The goal is to be able to open self dm from chats.

**Comment by nkdengineer** [comment] 2024-04-18 04:02
> Can you please update your proposal to cover that

I updated the solution in step 6

**Comment by s77rt** [comment] 2024-04-18 04:03
@abzokhattab 

> We should disable the current user login in the personalDetails as the selfDM is already included in the recentReports list. This will prevent duplicate records

I'm not seeing duplicate records, do you have reproduction steps for this?

**Comment by s77rt** [comment] 2024-04-18 04:07
@nkdengineer The comment is still outdated e.g. step 3. Please clear up the proposal leaving only up-to-date steps. Also remove step 5 (the move to top suggestion)

**Comment by nkdengineer** [comment] 2024-04-18 04:14
@s77rt Oh sorry. I updated it

**Comment by ahmedGaber93** [comment] 2024-04-18 08:12
> The goal is to be able to open self dm from chats.

@s77rt Thanks for the feedback.

Let me ask @thienlnam for confirmation about that.

> 2. Have the self-DM show up in the participant selector.

@thienlnam In this point you mean showing up by search in 'Start Chat' or by default without having to search for it like self assign task?

<details>
<summary>task self assign design</summary>

![Screenshot 2024-04-16 at 2 32 37 AM](https://github.com/Expensify/App/assets/41129870/c6225ff6-411c-49da-9239-e3a13663e8d1)


</details>

Thanks!

**Comment by thienlnam** [comment] 2024-04-18 22:07
> @thienlnam In this point you mean showing up by search in 'Start Chat' or by default without having to search for it like self assign task?

It should not be like self-assign tasks - the intention here is that you should should up in the search results, and then clicking on yourself will open up the self-DM. But we shouldn't dock it with 'Assign to me', since this will not be a main use case for Start Chat

**Comment by s77rt** [comment] 2024-04-19 20:45
@nkdengineer Thanks for the update. This looks good to me 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/40259#issuecomment-2057972070)

**Comment by quinthar** [comment] 2024-04-21 06:26
This is great!  We're putting this feature out right away; can you get this done today?

**Comment by quinthar** [comment] 2024-04-21 22:26
@nkdengineer can you please give an ETA for this?  This is super urgent.  Thank you!

**Comment by nkdengineer** [comment] 2024-04-21 22:46
A pull request will be submitted within the next 6 hours.

**Comment by quinthar** [comment] 2024-04-23 03:36
Hi all, what's the next step?   @s77rt what is your ETA for review?

**Comment by s77rt** [comment] 2024-04-23 11:10
We have a failing test. Working on it atm...

**Comment by s77rt** [comment] 2024-04-23 13:04
Found a solution. Working on the implementation

**Comment by quinthar** [comment] 2024-04-25 00:45
Great!  @s77rt what's your ETA?

**Comment by s77rt** [comment] 2024-04-25 00:52
PR is merged

**Comment by s77rt** [comment] 2024-04-29 13:46
**Regression Test Proposal**

1. Press FAB then Start chat
2. In the search field, type your email, your name or the word "you" ("tù" if language is set to Spanish)
3. Verify you see the self dm report (a report with your name and avatar)
4. Press the self dm report
5. Verify you are navigated to the self dm report

**Comment by mallenexpensify** [comment] 2024-05-01 00:13
Thanks @s77rt , testrail GH created
- https://github.com/Expensify/Expensify/issues/392149

**Comment by mallenexpensify** [comment] 2024-05-06 18:48
Contributor: @nkdengineer owed $250 via Upwork
Contributor+: @s77rt paid $250 via Upwork

@nkdengineer can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0112a1eb2ca973eaaa

**Comment by nkdengineer** [comment] 2024-05-06 20:56
@mallenexpensify Based on this [comment](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489), the issue`s price should be updated to $500, right? Please correct me if I miss anything

**Comment by mallenexpensify** [comment] 2024-05-07 20:32
Yes @nkdengineer , I missed that (and automation doesn't appear to be working as I'd expect). 
can you please accept the job and reply here once you have?    I updated the amounts in the payment comment above.

**Comment by nkdengineer** [comment] 2024-05-09 17:33
> @nkdengineer can you please accept the job and reply here once you have?

Thanks @mallenexpensify 🙇  I've applied to the job

**Comment by mallenexpensify** [comment] 2024-05-09 19:01
@nkdengineer can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0112a1eb2ca973eaaa

Before submitting new offers, can you check next time to see if there are existing ones that we sent where we're just waiting for you to accept? There were two for this job awaiting acceptance.  Thx

**Comment by nkdengineer** [comment] 2024-05-10 18:54
@mallenexpensify Thanks 🙇  I accepted the offer!

> can you check next time to see if there are existing ones that we sent where we're just waiting for you to accept?

@mallenexpensify Got it, but those were for the wrong amount so I didn't accept

**Comment by mallenexpensify** [comment] 2024-05-12 19:59
Paid @nkdengineer , thx.  [Payment comment updated above. ](https://github.com/Expensify/App/issues/40259#issuecomment-2096689011)

**Closed by mallenexpensify** 2024-05-12 19:59 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment, Bug
