### ISSUE TITLE
[$500] IOU - "Please enter at least two different addresses" message remains

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35437] opened 2024-01-30 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4252136
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to FAB> Request money> Distance
2. Add location to Start
3. Add the same location to Finish
4. Error message should display
5. Navigate to other tab (Manual, Scan)
6. Enter new location to Start

## Expected Result:
Since user change the tab error message should disappear

## Actual Result:
"Please enter at least two different addresses" message remains when user change tab/start new point

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/aab3c63f-ca59-4740-a2ef-1aa297bc0d42

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d60398a3db9f6ba7</li>
        <li>Upwork Job ID: 1752430245964652544</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 28146143</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-30 20:36
We think that this bug might be related to #wave5. 
CC @dylanexpensify

**Comment by BhuvaneshPatil** [comment] 2024-01-30 21:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - "Please enter at least two different addresses" message remains

### What is the root cause of that problem?
We initially set `hasError` has false. But when changing tabs, the component `IOURequestStepDistance` isn't unmounted, that's why when we visit distance tab again. we still have `hasError` as true, thus we display the error message.
To display the error message we use this condition - 
https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/iou/request/step/IOURequestStepDistance.js#L141-L142

### What changes do you think we should make in order to solve the problem?
In this if condition(mentioned above) we are not considering if we have empty waypoints. We shall take that into account as well.
We shall calculate the non-empty endpoints. As we always set endpoints by default as 
```js
    const waypoints = useMemo(() => optimisticWaypoints || lodashGet(transaction, 'comment.waypoints', {waypoint0: {}, waypoint1: {}}), [optimisticWaypoints, transaction]);
```

We shall count the non empty endpoints -
```js
        const nonEmptyWaypoints = _.filter(_.keys(waypoints), (key) => !_.isEmpty(waypoints[key])).length;
```
and modify the above if condition to check if the length is greater than 0 and less than 2. That way we will errors as expected and we'll prevent showing error if the endpoints are empty.
```js
 if (nonEmptyWaypoints > 0 && nonEmptyWaypoints <= 2 && _.size(validatedWaypoints) < 2) {
            return {0: translate('iou.error.atLeastTwoDifferentWaypoints')};
        }
```

<details>
<summary> Result </summary>

Uploading Screen Recording 2024-01-31 at 2.50.47 AM.mov…

</details>



### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2024-01-30 21:23
@shubham1206agra 

I was able to repro this issue on v1.4.33-4


https://github.com/Expensify/App/assets/27822551/a280bdda-0c4a-467e-add9-5676a7db3e29

**Comment by Yokomon** [comment] 2024-01-30 22:18
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - "Please enter at least two different addresses" message remains

### What is the root cause of that problem?

Investigation made shows that the hasError state is not updated when a tab changes. During the creation of the [IOURequestStepDistance ](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/iou/request/step/IOURequestStepDistance.js#L48) the component behaves as a Tab.Child Component but the parent state is not notified of the child component changes. Currently the state(hasError) is constant and applied throughout the lifecycle of the the 3 tab child (**IOURequestStepAmount**, **IOURequestStepScan**, **IOURequestStepDistance**). 

Therefore, even though the **hasError** state is default to false, once the submit button is triggered, the error state now set to true would always be fixed throughout the **lifecycle** of the Tab component.

### What changes do you think we should make in order to solve the problem?

Implementation that would fix this issue, is to keep track of the changes of the tabs and also reset the error state, whenever a change occurs. I have made a useEffect hook that has a dependency fixed to the iouRequestType, which is gotten from the parent component.

<img width="372" alt="Screenshot 2024-01-30 at 23 11 45" src="https://github.com/Expensify/App/assets/47699250/238997e4-d746-4b1f-be42-5e46082b9e9a">

The above code would have the error state to reset to default (false) anytime there is a change in the Tab state.


### What alternative solutions did you explore? (Optional)

An alternative solution, would be to refactor the [OnyxTabNavigator](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/iou/request/IOURequestStartPage.js#L159) and make use of the useTransition hook from react, which is very useful for handling these kind of states. 

We can have an isPending state that can be used to signify the Tab.Child components, when a tab transition has occured. 

Reference: [useTransition](https://react.dev/reference/react/useTransition#displaying-an-error-to-users-with-error-boundary)

**Comment by DylanDylann** [comment] 2024-01-31 14:22
@Krishna2323 Could you help to detail this point ?
>  for the second issue we need to create a util function which returns the number of non empty waypoints so **we can validate and show error for 2 duplicate waypoints.**

**Comment by BhuvaneshPatil** [comment] 2024-01-31 14:27
@DylanDylann I have about that in my proposal above.
Way points are initially two empty objects, with two keys. we need to have that check as well.
Because currently we only check if there are two keys. We need to have check if the value for that key is empty or not

**Comment by DylanDylann** [comment] 2024-01-31 14:56
@Krishna2323 Please detail your change in codebase for this point

**Comment by Yokomon** [comment] 2024-01-31 16:13
Looking at the codebase, the way in which this bug can be resolved is to handle the update the state handling the error(hasError) whenever a change/transition occured in the Tab component. There should be no need for modifying the logic used to handle the getError.

Once the Distance tab is changed, the validatedWaypoints are reset to 0. So the logic used for generating error messages works fine. The only problem leading to this bug is the reset of the hasError state when there is a change/unmount of the Tab components.

**Comment by funny2code** [comment] 2024-02-01 03:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Please enter at least two different addresses" message remains when user change tab/start new point

### What is the root cause of that problem?
When user changes tab after setting the same addresses (start, finish) in "Distance" tab, the **wayspoints** are reset to {waypoint0: {}, waypoint1:{}} but **hasError** is still true. Thus, the reason is that the `hasError` isn't reset to false in default case when the start and finish points are reset.

### What changes do you think we should make in order to solve the problem?

To resolve this issue, I added a useEffect hook which reset the **hasError** to `false` when the start and finish points / **waypoints** are default value - {waypoint0: {}, waypoint1: {}}.
```
useEffect(() => {
        if (_.keys(waypoints.waypoint0).length == 0 && _.keys(waypoints.waypoint1).length == 0) {
            setHasError(false);
        }
}, [waypoints]);
```
Here is a video for the expected result;
https://www.loom.com/share/026f1f328b88481599e8e1989c2a8912?sid=c2c3bbe3-be4b-4feb-984c-c8bacf2bacdf

**Comment by DylanDylann** [comment] 2024-02-01 06:21
I think that we are making one logic 2 times and we should dry it:

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/iou/request/step/IOURequestStepDistance.js#L168

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/iou/request/step/IOURequestStepDistance.js#L214

**Comment by DylanDylann** [comment] 2024-02-01 06:32
Still waiting for a better proposal

**Comment by funny2code** [comment] 2024-02-01 16:00
``> I think that we are making one logic 2 times and we should dry it:
> 
> https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/iou/request/step/IOURequestStepDistance.js#L168
> 
> https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/iou/request/step/IOURequestStepDistance.js#L214

I think we can set the `hasError` using useMemo. Because the 2 conditions above depends on the `transaction` essentially, we can set one flag variable to `hasError`, I mean we can merge 2 conditions in one. Thus, we don't have to use `setHasError` setter in Next button event and the error messages will be evaluated/updated every the start/finsh/stop positions are changed.
The result is :
[Recorded Video](https://www.loom.com/share/5ac0862d968d427193329a9a3387b8bb?sid=ffb2a755-bf1b-48ad-82c6-4ae40cd0faa0)
```
// const [hasError, setHasError] = useState(false);
```
```
   const duplicateWaypointsError = useMemo(() => {
        return _.keys(waypoints).length > 2 && _.size(validatedWaypoints) !== _.keys(waypoints).length;
    }, [waypoints]);

    const atLeastTwoDifferentWaypointsError = useMemo(() => {
        return !(_.keys(waypoints.waypoint0).length == 0 && _.keys(waypoints.waypoint1).length == 0) && _.size(validatedWaypoints) < 2;
    }, [waypoints]);

    const hasError = useMemo(() => {
        return duplicateWaypointsError || atLeastTwoDifferentWaypointsError || hasRouteError || isLoadingRoute || isLoading;
    }, [waypoints]);
```
```
  const submitWaypoints = useCallback(() => {
        // If there is any error or loading state, don't let user go to next page.
        // if (_.size(validatedWaypoints) < 2 || (_.keys(waypoints).length > 2 && _.size(validatedWaypoints) !== _.keys(waypoints).length) || hasRouteError || isLoadingRoute || isLoading) {
        //     setHasError(true);
        //     return;
        // }
        navigateToNextStep();
    }, [waypoints, hasRouteError, isLoadingRoute, isLoading, validatedWaypoints, navigateToNextStep]);
```

```
                 <View style={[styles.w100, styles.pt2]}>
                    {/* Show error message if there is route error or there are less than 2 routes and user has tried submitting, */}
                    {hasError && (
                        <DotIndicatorMessage
                            style={[styles.mh4, styles.mv3]}
                            messages={getError()}
                            type="error"
                        />
                    )}
                    <Button
                        success
                        allowBubble
                        pressOnEnter
                        style={[styles.w100, styles.mb4, styles.ph4, styles.flexShrink0]}
                        onPress={submitWaypoints}
                        text={translate('common.next')}
                        isLoading={!isOffline && (isLoadingRoute || shouldFetchRoute || isLoading)}
                    />
                </View>
```

**Comment by ikevin127** [comment] 2024-02-01 17:03
![giphy](https://github.com/Expensify/App/assets/56457735/a9bea82f-3ec3-4f08-b195-27910dd7fa0f)

**Comment by DylanDylann** [comment] 2024-02-04 17:07
Will review on Monday

**Comment by DylanDylann** [comment] 2024-02-06 04:51
Thanks everyone. I like @funny2code's [update](https://github.com/Expensify/App/issues/35437#issuecomment-1921655996) to use `hasState` as a variable instead of a state. But It seems your change is a bit complicated, we can use 


🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-02-06 04:54
@funny2code Please bring [your update](https://github.com/Expensify/App/issues/35437#issuecomment-1921655996) to your original proposal

**Comment by DylanDylann** [comment] 2024-02-06 04:55
🎀 👀 🎀 C+ reviewed

**Comment by funny2code** [comment] 2024-02-06 04:59
@DylanDylann thanks for your reviewing. I can make it simpler in the PR phase. Please let me know the next step to do.

**Comment by DylanDylann** [comment] 2024-02-06 05:01
@funny2code We need to wait internal engineer to approve your proposal and officially assign you to this issue. Then you can make a PR to implement your solution
p/s: Please check my comment [here](https://github.com/Expensify/App/issues/35437#issuecomment-1928783387)

**Comment by funny2code** [comment] 2024-02-06 05:02
@DylanDylann Yes, I will

**Comment by funny2code** [comment] 2024-02-06 05:09
@DylanDylann I updated the [proposal](https://github.com/Expensify/App/issues/35437#issuecomment-1920447910)

**Comment by funny2code** [comment] 2024-02-06 16:29
@hayata-suenaga I just submitted a proposal on Upwork! I can have a PR ready by tomorrow.

**Comment by funny2code** [comment] 2024-02-07 02:37
@hayata-suenaga I am ready to make a PR, but I don't have permission to commit my changes for now.

**Comment by DylanDylann** [comment] 2024-02-07 03:42
@funny2code Please read the guideline [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)

**Comment by abekkala** [comment] 2024-02-08 18:42
@funny2code do you have your PR ready?

**Comment by hayata-suenaga** [comment] 2024-02-08 20:56
@funny2code @DylanDylann could you check the above comment ⬆️ ?

**Comment by funny2code** [comment] 2024-02-09 02:11
> @funny2code do you have your PR ready?

@abekkala I submitted a proposal on Upwork, but am not hired yet. And I couldn't commit my updates due to no-permission for the Expensify codebase.

**Comment by funny2code** [comment] 2024-02-09 02:52
@hayata-suenaga I checked the [new comment](https://github.com/Expensify/App/issues/35437#issuecomment-1934913274).
The [component ](https://github.com/Expensify/App/blob/067bfa88b7643a4d810ff51db692e88add0f7456/src/components/DistanceRequest/index.js) (/src/components/DistanceRequest/index.js) which @GandalfGwaihir mentioned above is not related to the main [issue](https://github.com/Expensify/App/issues/35437#issue-2108716820), I think. The error message "Please enter at least two different addresses" depends on the `hasError` state in the component IOURequestStepDistance. 
@GandalfGwaihir , I hope you please check out my code updates in my [proposal](https://github.com/Expensify/App/issues/35437#issuecomment-1920447910) and the [recorded video](https://www.loom.com/share/5ac0862d968d427193329a9a3387b8bb?sid=ffb2a755-bf1b-48ad-82c6-4ae40cd0faa0) again.

**Comment by DylanDylann** [comment] 2024-02-09 06:40
@GandalfGwaihir Maybe currently, the fix should be applied for both [DistanceRequest](https://github.com/Expensify/App/blob/067bfa88b7643a4d810ff51db692e88add0f7456/src/components/DistanceRequest/index.js) component and [IOURequestStepDistance](https://github.com/Expensify/App/blob/067bfa88b7643a4d810ff51db692e88add0f7456/src/pages/iou/request/step/IOURequestStepDistance.js). But note that, we have [a plan](https://github.com/Expensify/App/issues/34610) to use [IOURequestStepDistance](https://github.com/Expensify/App/blob/067bfa88b7643a4d810ff51db692e88add0f7456/src/pages/iou/request/step/IOURequestStepDistance.js) for all distance page and remove old distance component.

cc @hayata-suenaga

**Comment by DylanDylann** [comment] 2024-02-09 06:40
@funny2code You need to create a folk and push your branch to your folk

**Comment by funny2code** [comment] 2024-02-26 15:05
Contributor details
Your Expensify account email: dejanbuk.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018db8c60ae1459528

**Comment by funny2code** [comment] 2024-02-26 15:12
I have read the CLA Document and I hereby sign the CLA

**Comment by funny2code** [comment] 2024-02-27 00:14
@hayata-suenaga @DylanDylann Please check the [new PR](https://github.com/Expensify/App/pull/37231) out.

**Comment by funny2code** [comment] 2024-02-29 00:21
My PR is merged and deployed to staging successfully. @hayata-suenaga I've check it out at [staging](https://staging.new.expensify.com/) just now. Thank you. 👍👍👍

**Comment by funny2code** [comment] 2024-02-29 12:38
@DylanDylann,  My Proposal was accepted here and my PR was merged to staging successfully yesterday.
I've applied for the UpWork Job for this issue (https://www.upwork.com/jobs/~01d60398a3db9f6ba7), but I didn't receive any offer yet. Could you please take a look at this? Or who can I ask for that?
cc: @hayata-suenaga @lanitochka17 @abekkala

**Comment by DylanDylann** [comment] 2024-02-29 12:42
The payment will be processed 7 days after PR is deployed to production

**Comment by DylanDylann** [comment] 2024-02-29 12:43
@funny2code Currently, our PR isn't deployed to production. So let's wait

**Comment by funny2code** [comment] 2024-02-29 12:47
@DylanDylann Understood, thanks for letting me know!

**Comment by abekkala** [comment] 2024-02-29 23:05
@funny2code yes, as @DylanDylann mentioned, the PR hasn't merged to production yet. Once it does the regression period countdown begins and this GH title will auto-update with the payment date.

**Comment by funny2code** [comment] 2024-02-29 23:41
@abekkala thanks for your reply. The PR has merged to production a few minutes ago. I checked it out [here](https://github.com/Expensify/App/pull/37231#issuecomment-1972148384) just now.
CC: @hayata-suenaga @DylanDylann

**Comment by funny2code** [comment] 2024-02-29 23:52
@abekkala Could you please update me on upwork?
CC: @hayata-suenaga @DylanDylann

**Comment by abekkala** [comment] 2024-02-29 23:56
@funny2code an Upwork offer has been sent - it will be paid after regression period has ended.

**Comment by funny2code** [comment] 2024-02-29 23:59
@abekkala I've checked the Upwork offer just now. Thank you.

**Comment by funny2code** [comment] 2024-03-01 00:08
@abekkala I mean, can I submit a proposal to another issue?

**Comment by abekkala** [comment] 2024-03-01 13:58
@funny2code Yes - you can submit proposals

**Comment by funny2code** [comment] 2024-03-01 14:08
@abekkala Thanks for letting me know.

**Comment by funny2code** [comment] 2024-03-09 09:17
Hi @abekkala, Regarding the payment, I posted in Slack channel and Upwork chat box. I hope you check them out and let me know as soon as possible.
cc: @hayata-suenaga @DylanDylann

**Comment by funny2code** [comment] 2024-03-11 08:43
Hi @abekkala When could you update me on Upwork?

**Comment by funny2code** [comment] 2024-03-11 13:13
@abekkala

**Comment by abekkala** [comment] 2024-03-11 13:21
@funny2code payment sent and contract ended

@DylanDylann payment sent and contract ended

**Comment by funny2code** [comment] 2024-03-11 13:22
@abekkala Thank you

**Closed by abekkala** 2024-03-11 13:21 UTC
Labels: Reviewing, External, Weekly, Bug
