### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Expense report - Delete modal does not disappear immediately after deleting report field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43496] opened 2024-06-11 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.81-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43041
## Action Performed:
precondition: user is a member of a collect workspace
1. Go to OD as a workspace admin
2. Add some text reports fields
3. As a member of the workspace, open the ND app
4. Open the workspace chat
5. Submit some expense
6. As admin delete any report field in OD
7. Open the expense report in ND app as a member
8. Select the deleted report field and deleted

## Expected Result:
The delete modal disappears immediately before the user is returned to the report

## Actual Result:
The delete modal does not disappear immediately, it is still displayed a little after user is returned to the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ffe18822-0e7e-4b2a-b884-b8c499073640

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3ed03d5140d382f</li>
        <li>Upwork Job ID: 1800593700265731860</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 102768696</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-06-11 15:47
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-11 15:48
We think that this bug might be related to #wave-collect - Release 1

**Comment by TheGithubDev** [comment] 2024-06-11 20:17
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue:**
The delete modal does not disappear immediately after deleting a report field in the expense report. It remains visible for a short time even after the user is returned to the report.

### **What is the root cause of that problem?**
The root cause of this issue is a delay or mismanagement in the state updates or the modal dismissal logic. The delay could be due to asynchronous operations not being handled properly or the modal's visibility state not being updated in a timely manner.

### **What changes do you think we should make in order to solve the problem?**
To solve this problem, we need to ensure that the modal is dismissed immediately after the delete action is confirmed. This can be achieved by:
1. ### **Ensuring Proper State Update:**
- Make sure that the state controlling the modal's visibility is updated immediately upon the delete action.
2. ### **Synchronous Dismissal Logic:**
- Ensure that the modal dismissal logic runs synchronously and is triggered right after the deletion confirmation.

**Example of changes:**

1. **Update the State Immediately:**
- Ensure that the state managing the modal visibility is set to false right after the delete action.
   ```javascript
   const handleDelete = () => {
       // Perform delete operation
       deleteReportField()
           .then(() => {
               // Dismiss the modal immediately after the delete operation
               setIsModalVisible(false);
               // Navigate back to the report
               navigation.goBack();
           })
           .catch(error => {
               // Handle error
               console.error("Error deleting report field:", error);
           });
   };
   ```

3. **Ensure Synchronous Dismissal:**
- Ensure that the modal dismissal happens synchronously.
   ```javascript
   const handleDelete = async () => {
       try {
           // Perform delete operation
           await deleteReportField();
           // Dismiss the modal immediately
           setIsModalVisible(false);
           // Navigate back to the report
           navigation.goBack();
       } catch (error) {
           // Handle error
           console.error("Error deleting report field:", error);
       }
   };
   ```

### **Alternative solutions ?**
1. ### **Debouncing the Modal Dismissal:**
- Consider adding a short debounce delay to the modal dismissal logic to ensure smooth UI transitions without noticeable lag.
2. Optimistic UI Updates:
- Implement optimistic UI updates where the modal is dismissed immediately on the UI while the delete operation is performed in the background.
3. Separate Loading Indicator:
- Use a separate loading indicator for the delete operation while dismissing the modal immediately, providing clear feedback to the user.

_Please note that the above explanation outlines only the technical approach I plan to take. After my proposal gets accepted, I will submit the finalized solution, as mentioned._

_Thanks_!

**Comment by truph01** [comment] 2024-06-12 06:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The delete modal does not disappear immediately, it is still displayed a little after the user is returned to the report

### What is the root cause of that problem?
The RCA is [here](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/pages/EditReportFieldPage.tsx#L87-L90) when we delete a report field, we call `handleReportFieldDelete` function and in this function, we don't hide the confirm modal before we navigate back to the report screen. So the confirm modal will show until the `EditReportFieldPage` is unmounted.


### What changes do you think we should make in order to solve the problem?
In `handleReportFieldDelete`, we should hide the confirm modal before we navigate back to the report screen here

```
setIsDeleteModalVisible(false);
Navigation.dismissModal(report?.reportID);
```
https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/pages/EditReportFieldPage.tsx#L89
### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment] 2024-06-12 08:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense report - Delete modal does not disappear immediately after deleting the report field

### What is the root cause of that problem?

In the `EditReportFieldPage`, the `onSelected` function for the `delete` menu item for the three-dot menu doesn't dismiss the modal when selected.

https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/pages/EditReportFieldPage.tsx#L99

Hence, it will not dismiss the `delete` modal immediately until it navigates to the previous page

### What changes do you think we should make in order to solve the problem?


Therefore, `onSelected` function should include `Navigation.dismissModal(report?.reportID)` to immediately dismiss the modal after the `delete` menu item is clicked.

So, the changes in the `onSelected` function should look like this.

```
onSelected: () => {
    setIsDeleteModalVisible(true);
    Navigation.dismissModal(report?.reportID);
}
```

**Comment by jayeshmangwani** [comment] 2024-06-12 22:03
Thanks for the proposals. I didn't have a chance to review them today, but I will do so first thing in the morning.

**Comment by jayeshmangwani** [comment] 2024-06-13 06:28
> To solve this problem, we need to ensure that the modal is dismissed immediately after the delete action is confirmed. This can be achieved by:

@TheGithubDev Can you please explain more about where in the code we need to handle this logic?

**Comment by TheGithubDev** [comment] 2024-06-13 08:10
To address the issue of the delete modal not disappearing immediately after deleting a report field, we need to focus where the delete action and UI state updates are handled. Here’s a detailed explanation of the changes required:

**1. Locate the Delete Action Handler:**
- Where the delete API call is made or where the report field state is updated.

Let’s assume this logic resides in a component called `ReportFieldManager.js`:

   ```javascript
   // ReportFieldManager.js

   const handleDeleteField = (fieldId) => {
       // API call to delete the field
       deleteFieldAPI(fieldId)
           .then(() => {
               // Field deleted successfully
               updateReportFields();
           })
           .catch(error => {
               // Handle error
               console.error('Failed to delete field:', error);
           });
   };
   ```

**2. Update the UI State Immediately:**
   - Within the delete action handler, we need to update the UI state immediately after confirming the delete action. Specifically, we need to update the modal visibility state to ensure it disappears promptly.

   Here's how you can modify the `handleDeleteField` function:

   ```javascript
   // ReportFieldManager.js

   const handleDeleteField = (fieldId) => {
       // Immediately update the modal state to hide it
       setModalVisible(false);

       // API call to delete the field
       deleteFieldAPI(fieldId)
           .then(() => {
               // Field deleted successfully
               updateReportFields();
           })
           .catch(error => {
               // Handle error
               console.error('Failed to delete field:', error);
               // Revert modal visibility if deletion fails
               setModalVisible(true);
           });
   };
   ```

3. **Ensure Proper State Management:**
- Make sure that the modal visibility state (`isModalVisible`) and any related UI states are properly managed and updated in the component’s state management logic.

   ```javascript
   // ReportFieldManager.js

   const [isModalVisible, setModalVisible] = useState(false);

   const handleDeleteField = (fieldId) => {
       // Immediately update the modal state to hide it
       setModalVisible(false);

       // API call to delete the field
       deleteFieldAPI(fieldId)
           .then(() => {
               // Field deleted successfully
               updateReportFields();
           })
           .catch(error => {
               // Handle error
               console.error('Failed to delete field:', error);
               // Revert modal visibility if deletion fails
               setModalVisible(true);
           });
   };

   return (
       <Modal
           visible={isModalVisible}
           onRequestClose={() => setModalVisible(false)}
       >
           <View>
               <Text>Are you sure you want to delete this field?</Text>
               <Button title="Delete" onPress={() => handleDeleteField(fieldId)} />
           </View>
       </Modal>
   );
   ```

By making these changes, the delete modal will be dismissed immediately upon triggering the delete action, ensuring a smoother user experience.

**Comment by isabelastisser** [comment] 2024-06-13 13:40
@bondydaa, can you please review this?

https://github.com/Expensify/App/issues/43496#issuecomment-2164814187 

Thanks!

**Comment by jayeshmangwani** [comment] 2024-06-18 04:53
@truph01 You are assigned to the issue now. Please raise the PR

**Comment by truph01** [comment] 2024-06-18 09:28
@jayeshmangwani PR https://github.com/Expensify/App/pull/43892 is opened

**Comment by isabelastisser** [comment] 2024-06-28 14:42
Thanks, @jayeshmangwani!

@bondydaa, can you please review the regression steps? Thanks!

**Comment by bondydaa** [comment] 2024-06-28 14:51
regression steps seem fine though I think we're trying to focus more on just getting new users in new dot and perfecting their workflows vs worrying about users who are trying to cross-use both old and new dot.

**Comment by isabelastisser** [comment] 2024-06-28 17:14
@bondydaa thanks for checking! So do you think a regression test issue should be created or not?

**Comment by bondydaa** [comment] 2024-06-28 17:29
yeah I think since we've already done the work for getting it set up and also fixing this case might as well make sure it doesn't randomly break again.

might just be something to keep in mind going forward that bugs that require using old dot to get things into a specific use case might not need to be prioritize as much.

**Comment by isabelastisser** [comment] 2024-06-29 01:19
Payment summary:

@jayeshmangwani C+ review / $250 requires payment through NewDot Manual Requests / `PENDING`
@truph01 Contributor / $250 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102768696)

**Comment by isabelastisser** [comment] 2024-06-29 01:19
@truph01 please accept the offer and I will process the payment in Upwork. Thanks!

**Closed by isabelastisser** 2024-06-29 01:19 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by truph01** [comment] 2024-07-01 05:31
@isabelastisser I accepted the offer, thank you

**Comment by jayeshmangwani** [comment] 2024-07-02 05:36
Requested $250 on NewDot.

**Comment by JmillsExpensify** [comment] 2024-07-02 13:17
$250 approved for @jayeshmangwani
