### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Approver - Existing approver settings reverts to default after upgrading workspace plan

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50924] opened 2024-10-16 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is under Collect plan.
- Workspace has at least two members.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Enable Add approvals.
4. Click on the existing approval workflow.
5. Click Approver.
6. Select another member as approver and save it.
7. Click Additional approver.
8. Upgrade the plan.
9. Click Got it, thanks.

## Expected Result:
The existing approver settings in Step 6 will be preserved.

## Actual Result:
The existing approver settings in Step 6 reverts to default after upgrading workspace plan.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0ebb8d1c-91f2-428d-b2a0-4b1cbb47ed7a

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847030936559806669</li>
        <li>Upwork Job ID: 1847030936559806669</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 104559184</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by IuliiaHerets** [comment] 2024-10-16 16:25
We think that this bug might be related to #wave-control

**Comment by bernhardoj** [comment] 2024-10-16 16:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Edit to the approval workflow is reset after upgrading the workspace from the additional approver flow.

### What is the root cause of that problem?
When we go back from the upgrade page, we will call `dismissModal` which will dismiss the whole RHP including the ongoing edit approval flow.
https://github.com/Expensify/App/blob/19b489c8e51a125980c598849a64becf51bc2e6e/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L98-L101

Then, we call `goBack` which navigates to the `backTo` params, in our case, the edit approval flow.
https://github.com/Expensify/App/blob/19b489c8e51a125980c598849a64becf51bc2e6e/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L39-L46

Because the page is closed and then reopened, the flow is restarted.

### What changes do you think we should make in order to solve the problem?

Don't always call `dismissModal`. For the approval feature, just go back with the fallback route. For all other existing cases, keep the `dismissModal` to not change the other existing behavior.

```
switch (feature.id) {
    case CONST.UPGRADE_FEATURE_INTRO_MAPPING.approvals.id:
        Navigation.goBack();
        Navigation.navigate(route.params.backTo);
        return;
    case CONST.UPGRADE_FEATURE_INTRO_MAPPING.reportFields.id:
    case CONST.UPGRADE_FEATURE_INTRO_MAPPING.rules.id:
    case CONST.UPGRADE_FEATURE_INTRO_MAPPING.companyCards.id:
        Navigation.dismissModal();
        return Navigation.navigate(ROUTES.WORKSPACE_MORE_FEATURES.getRoute(policyID));
    default:
        Navigation.dismissModal();
        return route.params.backTo ? Navigation.navigate(route.params.backTo) : Navigation.goBack();
}
```

Then, we can remove the `dismissModal` from here.
https://github.com/Expensify/App/blob/19b489c8e51a125980c598849a64becf51bc2e6e/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L99-L111

**Comment by nkdengineer** [comment] 2024-10-16 16:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The existing approver settings in Step 6 reverts to default after upgrading workspace plan.

### What is the root cause of that problem?

After calling the `UpgradeToCorporate` function, we have updated the policy type and the `Workflow.setApprovalWorkflow` function will be called in this [useEffect](https://github.com/Expensify/App/blob/fd2e0cb1c0578f8d3252e2eccfb35fdeb55db1bd/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L105-L113) => it has reverted to default approver

https://github.com/Expensify/App/blob/fd2e0cb1c0578f8d3252e2eccfb35fdeb55db1bd/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L105-L113

### What changes do you think we should make in order to solve the problem?


We will not reset the approval workflow when the policy type changes. 
```
    const policyType = policy?.type;
    const previousType = usePrevious(policy?.type);


   if(policyType !== previousType){
            Workflow.setApprovalWorkflow({
                ...currentApprovalWorkflow,
                availableMembers: [...currentApprovalWorkflow.members, ...defaultWorkflowMembers],
                usedApproverEmails,
                action: CONST.APPROVAL_WORKFLOW.ACTION.EDIT,
                isLoading: false,
                errors: null,
            });
        }
```
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-10-17 21:44
Reproduced.

**Comment by joekaufmanexpensify** [comment] 2024-10-21 12:55
Pending @ishpaul777 review of proposals

**Comment by joekaufmanexpensify** [comment] 2024-10-22 17:50
Great. TY!

**Comment by MarioExpensify** [comment] 2024-10-23 16:27
Very well, proposal looks good @bernhardoj!! Thank you @ishpaul777, let's move forward.

**Comment by bernhardoj** [comment] 2024-10-24 04:45
PR is ready

cc: @ishpaul777

**Comment by joekaufmanexpensify** [comment] 2024-10-28 16:50
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-11-04 16:06
Payment due next week! @ishpaul777 could you tackle checklist this week?

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:28
[Bumped in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1731338867025039)

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:55
Will handle payment today

**Comment by joekaufmanexpensify** [comment] 2024-11-11 21:02
Checklist is all set here. We need to pay: 

- @bernhardoj - $250 for PR via NewDot. 
- @ishpaul777 - $250 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-11-11 21:03
@ishpaul777 $250 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2024-11-11 21:03
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-11-11 21:04
Closing as all that's left here is for @bernhardoj to request payment via NewDot. Please do this at your earliest convenience!

**Closed by joekaufmanexpensify** 2024-11-11 21:04 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-11-12 03:32
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-11-12 09:46
$250 approved for @bernhardoj
