### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] [Distance] - Ability to request money without filling start and finish points

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27383] opened 2023-09-13 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money -> distance
2. Change /distance in the URL to /participants
3. Choose a workspace then click request

## Expected Result:
The app should redirect the user to https://staging.new.expensify.com/request/new/distance

## Actual Result:
The app allows users to request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[participants-bug.webm](https://github.com/Expensify/App/assets/93399543/7b0a2407-02f0-4ef7-94bc-46ec447e1c89)

https://github.com/Expensify/App/assets/93399543/4a83af2a-84ef-4e3b-ba85-0377f809ef8e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694429194889109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf360a8a0ff38420</li>
        <li>Upwork Job ID: 1702018479558987776</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 26773601</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-13 18:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Ability to request money without filling start and finish points

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/7deca7a02a4f58bb1bb47b0689d478525558898f/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L79-L81

https://github.com/Expensify/App/blob/7deca7a02a4f58bb1bb47b0689d478525558898f/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L67-L69

Let's see this code, we only navigate back if itn't distance request. It seems that we want to prevent user come back in distance request
### What changes do you think we should make in order to solve the problem?
We should update the logic to allow users:
1. Coming back if it isn't distance request
2. Coming back if it is distance request and there are no waypoint (no route)

To do that we can get waypoint from transaction like this
```
const transaction = TransactionUtils.getTransaction(props.iou.transactionID);
const isEmptyWaypoint = _.isEmpty(lodashGet(transaction, 'comment.waypoint.waypoint0', {}))
```

and in here
https://github.com/Expensify/App/blob/7deca7a02a4f58bb1bb47b0689d478525558898f/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L79-L81

https://github.com/Expensify/App/blob/7deca7a02a4f58bb1bb47b0689d478525558898f/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L67-L69

 update the condition to 
```
(!isDistanceRequest || (isDistanceRequest && isEmptyWaypoint))
```

instead of only `!isDistanceRequest `
### What alternative solutions did you explore? (Optional)
Same like the main solution but we can use isEmptyRoute instead of isEmptyWaypoint
```
const isEmptyWaypoint = _.isEmpty(lodashGet(transaction, 'comment.routes', {}))
```

**Comment by joekaufmanexpensify** [comment] 2023-09-14 15:21
@tjferriss I'll grab this one as you were the second assignee, and this issue doesn't need two BZ assignees.

**Comment by joekaufmanexpensify** [comment] 2023-09-14 15:28
Reproduced and agreed that this is a bug. Makes sense to me that we'd just redirect back to  https://staging.new.expensify.com/request/new/distance, as that's what we seem to do for manual and scan in this same exact scenario. 

CC @neil-marcellini in case you have thoughts on this.

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:26
Proposals pending review.

**Comment by joekaufmanexpensify** [comment] 2023-09-18 08:06
Same

**Comment by joekaufmanexpensify** [comment] 2023-09-19 08:02
@allroundexperts Could you please take a look at the proposals on this issue? TY!

**Comment by DylanDylann** [comment] 2023-09-20 09:57
@allroundexperts The PR is ready for review: https://github.com/Expensify/App/pull/27826

**Comment by tgolen** [comment] 2023-09-26 05:15
Hi, the PR for this was reverted. Please see the comment [here](https://github.com/Expensify/App/pull/27826#issuecomment-1734690548)

**Comment by DylanDylann** [comment] 2023-09-26 05:33
I will create another PR to fix this bug

**Comment by joekaufmanexpensify** [comment] 2023-10-02 21:20
@allroundexperts mind taking care of the checklist this week?

**Comment by joekaufmanexpensify** [comment] 2023-10-09 20:28
Got it. And that's [this PR](https://github.com/Expensify/App/pull/28308)?

**Comment by joekaufmanexpensify** [comment] 2023-10-09 20:39
Great, ty! Changing this to weekly then in the meantime.

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:53
Still held

**Comment by joekaufmanexpensify** [comment] 2023-10-23 14:04
Held

**Comment by joekaufmanexpensify** [comment] 2023-10-30 14:05
Same

**Comment by joekaufmanexpensify** [comment] 2023-11-06 16:18
Follow up PR is merged and should be deployed this week!

**Comment by joekaufmanexpensify** [comment] 2023-11-13 14:56
@allroundexperts I see the PR this one was held on got deployed. We can make more progress on this now. Is that right?

**Comment by DylanDylann** [comment] 2023-11-14 11:08
@allroundexperts Yep, but It seems the regression is fixed by another PR

**Comment by DylanDylann** [comment] 2023-11-14 11:20
@allroundexperts The first regression is not caused our PR. You can check [this comment](https://github.com/Expensify/App/pull/27826#issuecomment-1736959608) for more detail

**Comment by joekaufmanexpensify** [comment] 2023-11-14 15:32
Got it. And https://github.com/Expensify/App/pull/28308 was the only thing remaining for this issue, so we're good to do BZ checklist now, issue payment (after 7 day hold) and close?

**Comment by joekaufmanexpensify** [comment] 2023-11-14 15:36
Sweet. Mind taking care of your portion of [the BZ checklist](https://github.com/Expensify/App/issues/27383#issuecomment-1743425242)?

**Comment by joekaufmanexpensify** [comment] 2023-11-20 14:29
[bumped in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1700490543589399)

**Comment by joekaufmanexpensify** [comment] 2023-11-21 15:23
Great, ty! BZ checklist is all set.

**Comment by joekaufmanexpensify** [comment] 2023-11-21 15:29
All set to issue payment. There was a regression here, so the county due here is: 

- @DylanDylann - $250 for PR (paid via upwork). 
- @allroundexperts - $250 for C+ (paid via NewDot). 
- @hichamcc - $50 for reporting (paid via Upwork).

**Comment by joekaufmanexpensify** [comment] 2023-11-21 15:33
Upwork job is closed, so opened new one to pay @hichamcc: https://www.upwork.com/jobs/~01282aaf23d83dd5cc

**Comment by joekaufmanexpensify** [comment] 2023-11-21 15:34
@hichamcc offer sent for $50!

**Comment by joekaufmanexpensify** [comment] 2023-11-21 15:34
@allroundexperts could you please request $250 via NewDot and confirm here once done?

**Comment by joekaufmanexpensify** [comment] 2023-11-21 15:43
@hichamcc $50 sent and contract ended!

**Comment by JmillsExpensify** [comment] 2023-11-22 18:47
$250 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/27383#issuecomment-1821149267).

**Closed** 2023-11-27 15:02 UTC
Labels: External, Weekly, Awaiting Payment, Bug
