### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] [Distance] - distance request money next button becomes clickable for few seconds just before throughing route exceeds maximum limitation allowing to request 0 amount

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27469] opened 2023-09-14 19:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to + FAB
2. Click on request money and go to distance tab
3. Choose to destinations that are too far
4. Click on the next button quickly before it becomes disabled

## Expected Result:
The next button doesn't become enabled

## Actual Result:
The next button doesn't become enabled

## Workaround:
The next button becomes enabled for few seconds allowing to request  0 amount

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7b8986e1-1544-4ec6-ac24-37170a13f8a1

https://github.com/Expensify/App/assets/93399543/845f3f9d-602c-4692-9ed5-f6ffa1345508

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lidiyakelay
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694542534742739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01410a271d5db355bf</li>
        <li>Upwork Job ID: 1702411311659782144</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26808405</li>
<li>lidiyakelay | Reporter | 26808406</li>
</ul></li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-09-15 15:15
clarifying if we are prioritizing distance issues

https://expensify.slack.com/archives/C05DWUDHVK7/p1694790927900289

**Comment by mananjadhav** [comment] 2023-09-17 18:41
@kevinksullivan I don't think I have access to the slack thread. Can you please confirm if we're prioritizing this now?

**Comment by ahmedGaber93** [comment] 2023-09-17 18:52
@mananjadhav is this slack issue https://expensify.slack.com/archives/C049HHMV9SM/p1694543469783499 will list here?
I think it is a different root cause.

**Comment by mananjadhav** [comment] 2023-09-17 19:25
@ahmedGaber93 I meant the slack link @kevinksullivan tagged in the previous comment.

**Comment by ahmedGaber93** [comment] 2023-09-17 19:31
@mananjadhav yes, I know, I am talking about another point, Kateryna Becciv ask you here to list [this slack bug](https://expensify.slack.com/archives/C049HHMV9SM/p1694543469783499) in this GH issue. 
I ask to add a proposal for both if it listed here.

**Comment by kevinksullivan** [comment] 2023-09-21 06:16
Yes we are @mananjadhav

**Comment by mananjadhav** [comment] 2023-09-21 17:58
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/27469#issuecomment-1720059036) seems to work. 

🎀 👀 🎀 C+ reviewed

**Comment by luacmartins** [comment] 2023-09-22 01:35
Agreed with the selected proposal

**Comment by mananjadhav** [comment] 2023-10-04 10:09
I couldn't pinpoint to a specific PR for this one as this was related to delay in the API response. I am also confused how do we do the payments for this one because of [this](https://github.com/Expensify/App/pull/27989#issuecomment-1736640882). @luacmartins @neil-marcellini.

**Comment by mananjadhav** [comment] 2023-10-06 03:45
@kevinksullivan @luacmartins @neil-marcellini quick bump on the previous comment.

**Comment by luacmartins** [comment] 2023-10-06 16:17
I agree with the PR assessment. Not sure about payment though, maybe @neil-marcellini has a better idea if this caused a regression or not

**Comment by mananjadhav** [comment] 2023-10-08 19:51
@neil-marcellini quick bump.

**Comment by luacmartins** [comment] 2023-10-10 23:53
still pending on the comment above

**Comment by neil-marcellini** [comment] 2023-10-11 18:11
> I couldn't pinpoint to a specific PR for this one as this was related to delay in the API response.

Yeah I agree it would be hard to find the PR that "caused" the regression. Let's not worry about it and pay as we do normally.

**Comment by mananjadhav** [comment] 2023-10-11 18:24
Thanks for the response @neil-marcellini. @kevinksullivan Can you please post the payout summary?

**Comment by mananjadhav** [comment] 2023-10-15 16:51
@kevinksullivan quick bump on this one.

**Comment by kevinksullivan** [comment] 2023-10-16 19:36
Reporter: @lidiyakelay ($50)
C+: @dukenv0307 ($750)
Contributor: @mananjadhav ($750 in NewDot)

**Comment by JmillsExpensify** [comment] 2023-10-16 19:42
$750 payment approved for @mananjadhav based on summary above.

**Comment by mananjadhav** [comment] 2023-10-19 16:38
@kevinksullivan Is the payout done for @dukenv0307 @lidiyakelay ? If yes then we can close this one out.

**Comment by luacmartins** [comment] 2023-10-23 17:33
Just waiting on payment

**Comment by luacmartins** [comment] 2023-10-26 17:18
Bump for payment @kevinksullivan

**Comment by luacmartins** [comment] 2023-10-30 16:34
Still waiting on payment

**Comment by luacmartins** [comment] 2023-11-02 21:52
Still pending payment

**Comment by luacmartins** [comment] 2023-11-02 21:52
Kevin is ooo until Monday. Gonna reassign a BZ member to process payment.

**Comment by luacmartins** [comment] 2023-11-02 21:53
Hi @jliexpensify! @kevinksullivan is ooo so I reassign this. Could you please assist with payment?

**Comment by jliexpensify** [comment] 2023-11-03 01:53
Ok catching up - here's Kevin's [Payment Summary](https://github.com/Expensify/App/issues/27469#issuecomment-1765150548)

[Previous Upworks job is closed](https://www.upwork.com/jobs/~01410a271d5db355bf), so will make a new one

**Comment by jliexpensify** [comment] 2023-11-03 01:58
New job post - https://www.upwork.com/jobs/~01da5d189add9def8a

Have invited @lidiyakelay ($50) and @dukenv0307 ($750)

**Comment by jliexpensify** [comment] 2023-11-06 01:46
@dukenv0307 please accept so I can pay and close the job, cheers!

**Comment by jliexpensify** [comment] 2023-11-06 06:03
Job closed, everyone paid.

@mananjadhav here's Kevin's [payment summary](https://github.com/Expensify/App/issues/27469#issuecomment-1765150548) for your payment.

**Closed by jliexpensify** 2023-11-06 06:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
