### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] [MEDIUM] [Backwards Compatibility] Expense with category can be created when admin disable the same category

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35236] opened 2024-01-26 12:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
Precondition:
User is an employee of Collect workspace on Old Dot which has categories set
Steps:
1. On collect workspace chat Employee starts manual request flow
2. On confirmation page select any category
3. Admin disable the same category on Old Dot
4. Employee complete the IOU flow successfully

## Expected Result:
Selected category on confirmation page should disappear/error message should be displayed

## Actual Result:
User can successfully create the IOU request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fd41d7f4-6810-49ad-8e91-868509965a08

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fa29b3491c11700</li>
        <li>Upwork Job ID: 1750851608721940480</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28131001</li>
<li>dukenv0307 | Contributor | 28131002</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-26 12:02
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 16:48
OOO Next week, So unassigning. Please assign a new C+ Issue here.

cc: @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-01-27 17:33
@c3024 plz review the proposal above.  Thx

**Comment by mallenexpensify** [comment] 2024-01-27 17:35
> We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

Agree with @kbecciv , added to Wave 6 project, comment if you disagree @greg-schroeder. Thx!

**Comment by c3024** [comment] 2024-01-27 18:13
I think the alternative solution is the way to go because before confirming the request we got the details of enabled categories. So, showing the error at category and the confirm button is the better solution.


https://github.com/Expensify/App/assets/102477862/760974be-2674-4ca3-afea-b3e012f64a7f



I think we should change the category page as well to include only the enabled categories notwithstanding the earlier selected category.

https://github.com/Expensify/App/assets/102477862/7863b87f-f6c0-46d4-9e13-2aaa457c009d

[Proposal here](https://github.com/Expensify/App/issues/35236#issuecomment-1911981908) by @dukenv0307 looks good to me.

**Comment by c3024** [comment] 2024-01-27 18:17
No internal engineer assigned. 🤔 

🎀 👀 🎀 C+ [Reviewed](https://github.com/Expensify/App/issues/35236#issuecomment-1913280732)

**Comment by mallenexpensify** [comment] 2024-01-30 00:54
@Gonals plz review when you have a minute.

**Comment by greg-schroeder** [comment] 2024-01-30 01:21
@amyevans given you worked on categories - do you know if this was considered or might be handled elsewhere already?

**Comment by amyevans** [comment] 2024-01-30 17:38
> @amyevans given you worked on categories - do you know if this was considered or might be handled elsewhere already?

Nope as far as I know this is an edge case we didn't consider/handle yet cc @yuwenmemon

**Comment by yuwenmemon** [comment] 2024-01-30 17:57
Yeah seems straightforward. @amyevans is correct. Assigning @dukenv0307

**Comment by c3024** [comment] 2024-02-27 12:09
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: This is a case where a user starts a money request flow and before it is completed, the admin removes a category from the policy on Old dot. The user can finish the money request and the money request page shows an error saying "The category is not valid". 
PR of this issue fixed it by resetting the category field if a category field is deleted during the request flow. As such, this is an edge case and no specific PR can be held responsible.
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not started because such discussion does not appear to be helpful for these cases.
* [x]  [@c3024] Determine if we should create a regression test for this bug. No because this is an edge case and does not appear to affect user experience adversely meaningfully.
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by mallenexpensify** [comment] 2024-03-06 00:45
Contributor: @dukenv0307 paid $500 via Upwork
Contributor+: @c3024 paid $500 via Upwork. 

@c3024 , what's the reason for thinking we don't want a regression test for this?

**Comment by c3024** [comment] 2024-03-08 06:45
@mallenexpensify 

This happens when a user is at the money request confirm page 

![Screenshot 2024-03-08 at 12 09 50 PM](https://github.com/Expensify/App/assets/102477862/67dd4ad9-5447-46de-8e7e-385aa475d51a)

and selects a category. Before this user presses the `Request` button, an admin of the workspace disables the same category from Old Dot. 

A user ordinarily stays on this page for a brief time. During that brief period an admin should remove/disable the same category that was chosen by the user for this bug to happen. It appeared to me as a rare case so I felt it does not need a regression test.

**Comment by mallenexpensify** [comment] 2024-03-10 22:54
Thanks @c3024 , I agree it's an edge case.  QA has a separate list for edge case tests (and design ones) that they only run monthly, I assume we'll want it for that, created an issue. 
https://github.com/Expensify/Expensify/issues/377286

**Closed by mallenexpensify** 2024-03-10 22:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
