### ISSUE TITLE
[LOW] [Splits] Web -  Request Money Action Item changes to $0.00 when requesting money from an account that is not on Expensify.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23038] opened 2023-07-17 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to + --> New chat --> Enter email address which is not registered (e.g [talha.97.mahmood+999@gmail.com](mailto:talha.97.mahmood+999@gmail.com))
2. Chat opens --> Click on + --> Request Money --> Enter amount --> Request money
3. Click on Requested money report action item.
4. It redirects to concierge.
5. Find the relevant chat from the LHN and open it
6. The requested money action item changes to $0.00 and paid even though the original requested amount and currency was different.
7. Click on the requested money action item.
8. 404 appears.

## Expected Result:
1. The requested money action item amount should not change to $0.00.
2. Clicking on requested money action item with $0.00 should not go to 404.

## Actual Result:
1. The requested money action item amount changes to $0.00.
2. Clicking on requested money action item with $0.00 goes to 404 screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ba317498-0acb-4ac8-a35f-fc65a387dd07

https://github.com/Expensify/App/assets/93399543/e5030293-99f4-4143-9efa-3f68f1e5692e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689517400786329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-07-17 20:56
This is mostly a back end issue.

**Comment by ShogunFire** [comment] 2023-07-19 16:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we request money from someone that is not on expensify the action item shows 0

### What is the root cause of that problem?

The backend return an error during RequestMoney call 
![image](https://github.com/Expensify/App/assets/19537677/b2f1eee3-e49a-43b1-b3fb-416bffd06b2d)

This error happens because we pass a debtorEmail that is undefined here:
https://github.com/Expensify/App/blob/40f354b36905d97513ccc52add7859cfd9c6aa9e/src/libs/actions/IOU.js#L413

The reason the debtor email is undefined is because here:
https://github.com/Expensify/App/blob/40f354b36905d97513ccc52add7859cfd9c6aa9e/src/libs/actions/IOU.js#L308

We set the payerEmail with the login of the participant, when the participant is not on expensify he doesn't have a login.

### What changes do you think we should make in order to solve the problem?

When the participant doesn't have a login, we should set payerEmail with participant.text. The code looks like this:
`const payerEmail = OptionsListUtils.addSMSDomainIfPhoneNumber(participant.login || participant.text);`

### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2023-07-24 22:19
I suspect this is the same core issue as https://github.com/Expensify/App/issues/20910. I'm going to file it in the Wave3 project for now and stick a hold on it, as this isn't a priority can be be something we tackle in cleanup. cc @mountiny @luacmartins

**Comment by ShogunFire** [comment] 2023-07-24 22:30
@JmillsExpensify I think this issue has also the same =root cause: https://github.com/Expensify/App/issues/22884

**Comment by JmillsExpensify** [comment] 2023-08-02 04:14
Still holding. If the root cause is the same, I'll close with no bounty.

**Comment by JmillsExpensify** [comment] 2023-08-16 13:50
Same same

**Comment by mountiny** [comment] 2023-08-21 21:25
I think @ShogunFire solution makes sense. Does this work fine in the chat even if you sign out and sign back in?

**Comment by ShogunFire** [comment] 2023-08-21 21:29
@mountiny I have a PR for this but we are not sure if this is the right way, can you check it out ? https://github.com/Expensify/App/pull/24348

**Comment by mountiny** [comment] 2023-08-21 23:04
looking at the PR

**Comment by mountiny** [comment] 2023-08-22 10:55
> @mountiny I don't think participant.text will make sense because it will be not an email if the user changes the display name.

@ShogunFire Could we additionally disable the request money option on the chat if there is no email? or the participant.text is not valid email. When going through the FAB then we always have the email there so we should be fine

**Comment by ShogunFire** [comment] 2023-08-22 11:00
I think we can, and for split in groups I would disable it if any participant doesn't have the login or text or I would just not put this particular b participant in the selected participant ? Otherwise I proposed a sketchy solution that works in the PR

**Comment by mountiny** [comment] 2023-08-22 12:37
Yeah lets avoid sketchy solution, I think its better to be actually more strict now that I see all these workaround which are just landmines for future. Could we instead hide the Reqeust Money option from the chat + menu when there are no login details (for unknown user) and basically you can keep requesting money from them using the blobal create as you have to type in the email but you cannot do it easily within the chat

**Comment by JmillsExpensify** [comment] 2023-08-22 15:01
Interesting, I think I agree with you. Basically, in the Global Create flow you can literally request from anyone, including creating an account for them. However, in order to request money from someone in a DM, they need to be known.

**Comment by mountiny** [comment] 2023-08-22 15:25
@ShogunFire @dukenv0307 What do you think, could you add this to your PR?

**Comment by ShogunFire** [comment] 2023-08-22 17:04
@mountiny yes I made the change already

**Comment by JmillsExpensify** [comment] 2023-08-23 23:45
This is a wave2 issue. Removing from the wave3 project.

**Comment by JmillsExpensify** [comment] 2023-09-07 02:07
Now that #22884 is closed, I'm going to remove the hold. What are the next steps?

**Comment by mountiny** [comment] 2023-09-07 09:49
I believe this should be solved by updating the money request flows to accept accountIDs instead of emails. @aldo-expensify has been working on that AFAIK

**Comment by Talha345** [comment] 2023-09-07 10:02
> I believe this should be solved by updating the money request flows to accept accountIDs instead of emails. @aldo-expensify has been working on that AFAIK

@mountiny In case, this is fixed by the backend change, would I be compensated for the bug report?

**Comment by mountiny** [comment] 2023-09-07 10:27
yes @Talha345 but once fixed

**Comment by JmillsExpensify** [comment] 2023-10-24 18:03
@aldo-expensify mind commenting on this one as soon as you're back?

**Comment by JmillsExpensify** [comment] 2023-11-24 17:02
Any thoughts on the comment above?

**Comment by aldo-expensify** [comment] 2023-11-24 18:04
Sorry, I completely missed your comments since I didn't go through emails when I got back 👀. I'll put it in my notes to take a look today.

**Comment by aldo-expensify** [comment] 2023-11-24 18:31
At the time I worked on it, I enabled to make money requests using the accountID, which you have for accounts that are "unknown" to you (assuming that you are online). I tried to test this now and the button is disabled:

<img width="1367" alt="image" src="https://github.com/Expensify/App/assets/87341702/fb9eb370-9f5f-4ec5-8e6a-b1977928a383">

It looks like we are disabling sending the money request?

**Comment by aldo-expensify** [comment] 2023-11-24 18:38
This [props.selectedParticipants](https://github.com/Expensify/App/blob/e355608a9e0ee107abe06f610031c80f74ed8fa8/src/components/MoneyRequestConfirmationList.js#L335) is empty when the other account is "unknown", and it contains the other account when it is known.

I don't know if this change is a bug or is it expected behaviour

**Comment by aldo-expensify** [comment] 2023-11-24 18:41
I think this change comes from this PR https://github.com/Expensify/App/pull/30342, 4 weeks ago.

@puneetlath do you know if we are intentionally not allowing to request money from unknown accounts now?

**Comment by JmillsExpensify** [comment] 2023-11-29 00:02
Hmm yeah I'm also unsure. Will wait for Puneet's confirmation.

**Comment by aldo-expensify** [comment] 2023-12-02 01:06
Sounds like we may be missing a test if QA missed this.

**Comment by JmillsExpensify** [comment] 2023-12-13 05:11
Agreed. I still think we should fix this one when time permits.

**Comment by puneetlath** [comment] 2023-12-14 17:14
Where should this fit? #vip-split-p2p?

**Comment by JmillsExpensify** [comment] 2024-01-24 02:41
Whoops, missed that last reply. I think your suggestion of #vip-split makes sense.

**Comment by JmillsExpensify** [comment] 2024-03-06 04:34
This one never got picked up, though I will re-float.

**Comment by JmillsExpensify** [comment] 2024-04-10 13:05
Still not a priority.

**Comment by JmillsExpensify** [comment] 2024-05-15 03:00
Still waiting for an internal volunteer

**Comment by JmillsExpensify** [comment] 2024-05-19 17:16
This still hasn't been picked up internally, which indicates to me it's just not a priority right now. I'm going to close and this can be re-opened when we have someone internal that is willing to take it on.

**Closed by JmillsExpensify** 2024-05-19 17:16 UTC
Labels: Monthly, Bug
