### ISSUE TITLE
Chat - If you reduce the browser window, emoji picker disappears in a chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12318] opened 2022-10-31 22:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to any chat
4. Shrink browser window (below 75%)

## Expected Result:
The user can use emoji picker.

## Actual Result:
User can't add emoji to his message.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.22-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5800659_12](https://user-images.githubusercontent.com/43996225/199120955-9555b4b0-0ceb-4c1c-8f93-6913a018489c.png)
![Bug5800659_3](https://user-images.githubusercontent.com/43996225/199120958-6c72ef91-2f14-4bd5-9803-ce7a12411ade.png)

https://user-images.githubusercontent.com/43996225/199120959-d1ccda28-7782-4dad-aeac-d2d28af7930e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2022-11-01 12:35
@stephanieelliott will check with the same tester and update you.

**Comment by kavimuru** [comment] 2022-11-01 13:34
@stephanieelliott Tester is able to reproduce still. 

https://user-images.githubusercontent.com/43996225/199245943-a5015b25-0694-4a88-a4d1-684254e0bcc3.mp4

**Comment by adityamatt** [comment] 2022-11-01 17:29
Unable to reproduce the bug 
![image](https://user-images.githubusercontent.com/33998232/199298723-925764f6-a9c6-4222-98d1-e4698744498d.png)

**Comment by stephanieelliott** [comment] 2022-11-02 14:52
Seems like this is occurring for only one tester, possibly a local issue. Gonna close this, we can reopen in the future if this turns out to be a widespread issue!

**Closed by stephanieelliott** 2022-11-02 14:52 UTC
Labels: Daily, Bug
