### ISSUE TITLE
[$500] Android - IOU – “Hmm.. it’s not here” appears when open existing scanning request.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33750] opened 2023-12-29 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Create a Scan Request in the 1:1 DM using a camera
4. Open IOU

## Expected Result:
IOU opens

## Actual Result:
“Hmm.. it’s not here” appears when open existing scanning request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2c1388e8-3689-4b12-850a-1df0acb9f73b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae77eeffa1097865</li>
        <li>Upwork Job ID: 1740696913839783936</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by bernhardoj** [comment] 2023-12-29 15:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat not found page shows when we open the ongoing scan request. This can happen on a manual request too.

### What is the root cause of that problem?
When we do a new money request and then press the request preview before the money request API completes, we will optimistically create a new transaction thread.
https://github.com/Expensify/App/blob/939632e1b1c0610daecf34e08ea12e1abcbce548/src/components/ReportActionItem/MoneyRequestAction.js#L106-L116

So, now the API request queue looks like this:
`[RequestMoney, OpenReport]`

If we optimistically create a new thread, it will set `childReportID` optimistically, but it will set the `childReportID` to 0 if fails.
https://github.com/Expensify/App/blob/939632e1b1c0610daecf34e08ea12e1abcbce548/src/libs/actions/Report.ts#L639-L651

Currently, from what I see, creating an optimistic transaction thread will always fail. 

From the log below, you can see that after the RequestMoney API completes, it will return a new `childReportID`, but different from the optimistic `childReportID`.
<img width="477" alt="image" src="https://github.com/Expensify/App/assets/50919443/0acaf5b2-024f-439f-983a-e6417aaf7a27">

But because the optimistic thread fails, the `childReportID` becomes "0".
<img width="460" alt="image" src="https://github.com/Expensify/App/assets/50919443/3b7a398a-603d-450a-8acc-656d3eaf9aa6">

If you go back to the parent report, the OpenReport will be requested again for the parent report and it will return the correct `childReportID`, but if you press the request preview again before the OpenReport completes, it will open a report with a report ID of 0. That's why we see the not found page.

### What changes do you think we should make in order to solve the problem?

Don't reset the `childReportID` to "0" (and `childType`) when the open report fails, only for money request transaction thread case.

### What alternative solutions did you explore? (Optional)
Fix the issue on the BE why the optimistic transaction thread always fail

**Comment by shubham1206agra** [comment] 2024-01-01 07:20
@bernhardoj Can you tell me why this problem only occurs on Android? Or is this problem occurs on other platforms?

**Comment by bernhardoj** [comment] 2024-01-01 09:53
@shubham1206agra it occurs on all platforms. I debug it on the web.

**Comment by shubham1206agra** [comment] 2024-01-03 03:30
Lets take this internal. 

🎀👀🎀 C+ reviewed

**Comment by shubham1206agra** [comment] 2024-01-03 03:31
@AndrewGable Can you take this internal to see why all request have different childReportID than optimistic one?

**Comment by tgolen** [comment] 2024-01-12 15:47
NM Chirag is on extended leave right now, so we gotta try to figure this out on our own.

**Comment by situchan** [comment] 2024-01-15 05:33
This seems to be dupe of https://github.com/Expensify/App/issues/33114

**Comment by laurenreidexpensify** [comment] 2024-01-15 11:45
oh interesting - let's hold on https://github.com/Expensify/App/issues/33114 and test when that is deployed

**Comment by laurenreidexpensify** [comment] 2024-01-15 11:46
Not overdue - changing track to see if https://github.com/Expensify/App/issues/33114 solves this

**Comment by laurenreidexpensify** [comment] 2024-01-22 12:12
Downgrading as #33114 is monthly

**Comment by laurenreidexpensify** [comment] 2024-02-20 12:16
hold on https://github.com/Expensify/App/issues/33114 which is currently on hold too 🙃

**Comment by laurenreidexpensify** [comment] 2024-03-21 16:39
#33114 is now on prod, so let's get this retested and confirm if it it's been resolved, so we can close

**Comment by laurenreidexpensify** [comment] 2024-03-25 14:19
Waiting for retesting, actually this can be a weekly

**Comment by mvtglobally** [comment] 2024-03-28 04:37
QA team is not able to confirm if this issue is still reproducible during KI retests as issue is Blocked to test by https://github.com/Expensify/App/issues/27691.

**Comment by AndrewGable** [comment] 2024-03-28 14:33
You can't test on a different Android device? I thought that issue was only a small amount of devices

**Comment by laurenreidexpensify** [comment] 2024-04-02 11:46
@shubham1206agra pls confirm thank you

**Comment by mvtglobally** [comment] 2024-04-04 03:24
Issue not reproducible during KI retests. (First week)

**Closed** 2024-04-08 11:36 UTC
Labels: Weekly, Internal, Bug, retest-weekly
