### ISSUE TITLE
[$500] Distance - Same location is allowed when it is entered in "Stop"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28477] opened 2023-09-29 13:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Request money
2. Change tab to distance
3. Click/tap on Add stop and enter location
4. Click/tap on Add stop and enter the same location again
5. Click/tap on Next

## Expected Result:
The same location should not be allowed in the "Stop" field

## Actual Result:
Adding the same location on stops is allowed if the values are entered in 'Stop' values not in Start and Finish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/91ffe546-7830-4d5f-8759-9df76fb9635c

https://github.com/Expensify/App/assets/93399543/b5137708-1ff8-47ee-b905-d676b86db721

https://github.com/Expensify/App/assets/93399543/b6c11396-ede8-43ed-b0fb-bc28fbdde99e

https://github.com/Expensify/App/assets/93399543/3a183df9-2421-438e-ac14-67b4c6c217b8

https://github.com/Expensify/App/assets/93399543/7a308eb4-d38c-4e1d-90ab-cd376bc902ef

https://github.com/Expensify/App/assets/93399543/41cf1bc1-2f91-462f-b01a-fcdfe6bba5ee

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695823418913709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01642f7f93e05ba24c</li>
        <li>Upwork Job ID: 1707744185233846272</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by rakshitjain13** [comment] 2023-09-29 13:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Next Button Activated with Same Stop and Finish Point in Request Money
### What is the root cause of that problem?
In
src/components/DistanceRequest.js
we check for validwaypoint and then decide wether we have to disable next button  or not . The logic is to check the size of validatedWaypoints array which is shown below .
https://github.com/Expensify/App/blob/71db96d8a77068220fac73ca0dc984796ff862f9/src/components/DistanceRequest.js#L300
Now to generate validatedWaypoints the code is in file
src/libs/TransactionUtils.js
https://github.com/Expensify/App/blob/71db96d8a77068220fac73ca0dc984796ff862f9/src/libs/TransactionUtils.js#L357-L390
This function fails in a edge case where starting waypoints are invalid because here lastWaypointIndex is equal to -1 in starting which suggests that first waypoint will always be valid when waypoints size > 1 .
### What changes do you think we should make in order to solve the problem?
We have to have increment lastWaypointIndex till we find some valid waypoint and then it is good to go . Here is my solution
    let lastWaypointIndex = -1;
    let foundFirstValidWaypoint = false;

    const validWaypoints = _.reduce(
        waypointValues,
        (acc, currentWaypoint, index) => {
            const previousWaypoint = waypointValues[lastWaypointIndex];
            console.log(lastWaypointIndex, !waypointHasValidAddress(currentWaypoint), currentWaypoint, previousWaypoint);

            // Skip all starting invalid waypoints
            if (foundFirstValidWaypoint == false && !waypointHasValidAddress(currentWaypoint)) {
                lastWaypointIndex += 1;
                return acc;
            } else {
                foundFirstValidWaypoint = true;
            }

            // Check if the waypoint has a valid address
            if (!waypointHasValidAddress(currentWaypoint)) {
                return acc;
            }
            // console.log(lastWaypointIndex, index, currentWaypoint, previousWaypoint);
            // Check for adjacent waypoints with the same address
            if (previousWaypoint && currentWaypoint.address === previousWaypoint.address) {
                return acc;
            }

            const validatedWaypoints = {...acc, [`waypoint${reArrangeIndexes ? lastWaypointIndex + 1 : index}`]: currentWaypoint};

            lastWaypointIndex += 1;

            return validatedWaypoints;
        },
        {},
    );
Here I have introduced a new variable named as foundFirstValidWaypoint which is false in starting and once we find a validwaypoint we will set it to true till the time we will increment lastWaypointIndex in each iteration .

### What alternative solutions did you explore? (Optional)
NA

**Comment by tewodrosGirmaA** [comment] 2023-09-30 16:46
@abekkala I reported  first here :https://expensify.slack.com/archives/C049HHMV9SM/p1695412007448899?thread_ts=1695412007.448899&cid=C049HHMV9SM could change my name , Thank you

**Comment by DylanDylann** [comment] 2023-10-02 07:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- There is no notification when selecting multiple Stop points with the same address

### What is the root cause of that problem?

- Currently, selecting multiple Stop points with the same address still allows to save and display in stop point list without notifications: https://github.com/Expensify/App/blob/db4d85bd937c9de78f9b95d3533050b9fb86f85d/src/pages/iou/WaypointEditor.js#L159-L167

### What changes do you think we should make in order to solve the problem?

- We need to add a validation to check if the selected stop point is the previous stop point or not, if yes, ignore the selected stop point like below:
```
 const isPreviousSelectedWaypoint = useCallback(
        (values) => {
            if (_.size(allWaypoints) > 0 && isEmpty(currentWaypoint)) {
                const lastWaypoint = lodashGet(allWaypoints, `waypoint${_.size(allWaypoints) - 2}`, {});
                return isEqual(lastWaypoint, values);
            } else if (!isEmpty(currentWaypoint)) {
                // Handle case edit waypoint
            }
            return false;
        },
        [allWaypoints],
    );

 const selectWaypoint = (values) => {
        if (!isPreviousSelectedWaypoint(values)) {
            saveWaypoint(waypoint);
        }
        Navigation.goBack(ROUTES.MONEY_REQUEST_DISTANCE_TAB.getRoute(iouType));
    };
```
- Also rather than just ignoring the selected stop point, we can disable the user clicking on this selection, or display the error (notification) to indicate that this stop point was already selected before. The expected behavior can be discussed in the future

### What alternative solutions did you explore? (Optional)

NA

### Result

[Screencast from 25-09-2023 18:33:06.webm](https://github.com/Expensify/App/assets/141406735/ef4bb92d-a9ec-4451-9e6b-64c9b72ed233)

**Comment by abekkala** [comment] 2023-10-02 16:18
@0xmiroslav can you please review the proposals that have come in? thanks!

**Comment by neil-marcellini** [comment] 2023-10-05 21:36
We have this issue https://github.com/Expensify/App/issues/27045 already which is going to handle this case so I'm going to close it.

**Closed by neil-marcellini** 2023-10-05 21:36 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by rakshitjain13** [comment] 2023-10-14 07:21
@neil-marcellini The above issue persists even after merging https://github.com/Expensify/App/issues/27045 . Can you please look at it ?

**Comment by jo-ui** [comment] 2023-10-19 07:47
@neil-marcellini @0xmiroslav @abekkala this issue is still reproducible, can you reopen it

**Comment by rakshitjain13** [comment] 2023-10-19 07:52
@jo-ui https://github.com/Expensify/App/issues/29895

**Comment by jo-ui** [comment] 2023-11-01 16:47
@0xmiroslav Yes it is still reproducible

**Comment by jo-ui** [comment] 2023-11-15 08:25
@abekkala @0xmiroslav the issue #29886 is fixed but it is dupe of this issue. can you reopen this issue and review please

**Comment by rojiphil** [comment] 2023-11-21 12:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

This proposal is brought from [29895 here](https://github.com/Expensify/App/issues/29895#issuecomment-1792954251). 

We are able to create two consecutive duplicate waypoints when there are `stops` added to the waypoints. So, we are trying to solve the problem of avoiding duplicates here.

### What is the root cause of that problem?

Currently, the logic supports consecutive duplicate waypoints when there are no `stops` added to the waypoints (i.e when only two waypoints are present). However, support for consecutive duplicate waypoints with additional `stops` in waypoints is not there. 

### What changes do you think we should make in order to solve the problem?

In the logic of determining `validatedWaypoints` [here](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/libs/TransactionUtils.ts#L429C1-L432C10), we already check if we have two consecutive duplicate waypoints and ignore such duplicates here. This means that the length of `waypoints` and `validatedWaypoints` will be different when there are duplicates. We can use this information to solve this problem.

1) First, let us ensure that on `submitWaypoints` [here](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/DistanceRequest/index.js#L185), we will prevent the user to go to the next page for two or more waypoints by comparing the lengths of `waypoints` and `validatedWaypoints` like this:

        if (_.size(validatedWaypoints) < 2 || (_.keys(waypoints).length > 2 && _.size(validatedWaypoints) !== _.keys(waypoints).length) || hasRouteError || isLoadingRoute || isLoading) {
            setHasError(true);
            return;
        }

2) Now, since we already have `hasError` set, let us ensure that the rendering also happen by replacing our condition [here](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/DistanceRequest/index.js#L225) like this:

                {((hasError && (_.size(validatedWaypoints) < 2) || (_.keys(waypoints).length > 2 && _.size(validatedWaypoints) !== _.keys(waypoints).length)) || hasRouteError) && (

3) Finally, we need to set the error message for duplicates [here](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/DistanceRequest/index.js#L157) like this:

        if (_.keys(waypoints).length > 2 &&  _.size(validatedWaypoints) !== _.keys(waypoints).length) {
            return {0: translate('iou.error.duplicateWaypointsErrorMessage')};
        }

**Comment by rushatgabhane** [comment] 2023-11-21 12:30
I think we should reopen the original  issue here - https://github.com/Expensify/App/issues/29895#issuecomment-1792954251

@rojiphil and I spent time on it

**Comment by DylanDylann** [comment] 2023-11-21 13:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users can go to the next page when entering two consecutive same endpoints

### What is the root cause of that problem?
We don't have logic to prevent user from clicking next button when they enter two consecutive same endpoints
### What changes do you think we should make in order to solve the problem?
Note that in `getValidWaypoints` function we had logic to remove a waypoint if 2 consecutive endpoints is same
In here 
https://github.com/Expensify/App/blob/bf2d545b5e2d40d7e72a51983112ef9fa9daf3f7/src/components/DistanceRequest/index.js#L180
we should check if `_.size(validatedWaypoints) < _.size(waypoints)` we will prevent user from submitting 

Also need to update here
https://github.com/Expensify/App/blob/bf2d545b5e2d40d7e72a51983112ef9fa9daf3f7/src/components/DistanceRequest/index.js#L220

In this function https://github.com/Expensify/App/blob/bf2d545b5e2d40d7e72a51983112ef9fa9daf3f7/src/components/DistanceRequest/index.js#L147
we also add a message like "please remove duplicated waypoints" if `_.size(validatedWaypoints) < _.size(waypoints)`  

We also prevent user going to next page by deeplink when they enter 2 consecutive same waypoints 
https://github.com/Expensify/App/blob/bf2d545b5e2d40d7e72a51983112ef9fa9daf3f7/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L98
In here we also need to add condition like we did in DistanceRequest Page (`_.size(validatedWaypoints) < _.size(waypoints)`)
