### ISSUE TITLE
[HOLD] Chat disappears in High Traffic account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23509] opened 2023-07-24 20:30 UTC
HOLD on https://github.com/Expensify/App/issues/23223

___

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to some HT channel (https://new.expensify.com/r/8292963527436014).Please do not post testing messages as this is a real channel with real customers.
2. Scroll upwards.
3. After a while the chat breaks and just a blank area appears.
4. Try scroll up and down and notice a hug gap appears between the chat messages
## Expected Result: 
While scrolling upwards the messages should load in order from and there should be no gap and chat should not break
## Actual Result: 
Chat breaks and a huge gap is introduced between messages

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6e4d7903-6c61-4252-9d06-84aa8897093f

https://github.com/Expensify/App/assets/43996225/807423e1-38bf-4ffd-a74c-4ef8acd37e55

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689786243613119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2023-07-28 08:13
I experience this issue all the time with my DMs. @marcaaron is this going to be handled by the pagination project? Should I close this?

**Comment by kavimuru** [comment] 2023-07-28 14:00
@mateocole I was not able to reproduce. It was reproduced only by the contributor @Talha345. So I created a GH ticket with `needs reproduction` label.

**Comment by marcaaron** [comment] 2023-07-28 18:55
This will likely be resolved by the **Comment Linking** project. 

cc @roryabraham and @perunt 

Do we have a milestone or GH Project that we can add this issue to and put it on HOLD? 

I think closing it is also reasonable - this has been a known problem for a very long time 🤷‍♂️

**Comment by perunt** [comment] 2023-07-29 09:40
we don't have a specific GH Project to tackle this issue directly. In V1 of comment linking, we use FlatList, which caused the same virtualization problem mentioned here. But in V2, we're planning to switch to WishList, and that should sort things out. The only problem is we don't have a set date for when WishList will be ready since it's still in the final stages of development and polishing.

**Comment by flaviadefaria** [comment] 2023-07-31 08:55
@perunt @roryabraham I'll assign this to you then. Feel free to keep it open, with the correct priority, if it makes sense or close it.

**Comment by roryabraham** [comment] 2023-08-09 20:37
Going to put this on HOLD for the [comment linking project](https://github.com/orgs/Expensify/projects/62/views/1). I don't think it will necessarily be directly addressed by anything planned for the comment linking project, but [this issue](https://github.com/Expensify/App/issues/23223) is a prerequisite for fixing this, so it makes sense to put this on HOLD

**Comment by roryabraham** [comment] 2023-08-09 20:39
Long-term I kind of think some form of eviction from the Onyx cache would be a way to solve this. i.e: once we have bidirectional pagination implemented, then we can drop reportActions from the Onyx cache and fetch them back page-by-page from the disk.

WishList might help but I do think that larger and larger chats will lead to longer and longer initial load times, even for WishList

**Comment by roryabraham** [comment] 2023-09-11 12:12
on HOLD

**Comment by roryabraham** [comment] 2023-10-17 16:23
on HOLD

**Comment by perunt** [comment] 2023-11-21 07:25
@kavimuru, could you please test it again? Recently, a few PRs were merged, which removed the old hack with the list in WEB and added some optimization. So, it should be way better now.

**Comment by roryabraham** [comment] 2023-12-22 18:00
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1703268042698819

**Comment by roryabraham** [comment] 2023-12-22 18:11
This issue can no longer be reproduced, closing this out 🎉

**Closed by roryabraham** 2023-12-22 18:11 UTC
Labels: Monthly, Needs Reproduction, Bug

**Comment by Talha345** [comment] 2023-12-26 16:17
@roryabraham would this issue be eligible for the reporting bonus as this was quite a peculiar bug?

Thanks!
