### ISSUE TITLE
Web - Remove user messages on #admin is broken on removing multiple users together and also on deleting workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23493] opened 2023-07-24 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. For this test, create new workspace
5. Open #admin room report of workspace
6. Again open settings->workspaces->workspace created on step 4->members
7. Invite multiple members, observe in #admin, messages are correct for adding members
8. Again visit members page of the workspace and delete all the invited members, now observe in #admin, removed messages are not displayed for all users and repeated for some
9. Repeat invite and remove process few time and delete workspace, observe that it again changes all removed user messages and even now, they have random repeats

## Expected Result:
App should display added and removed users messages as per our action properly in #admin room of workspace

## Actual Result:
On removing multiple users at once and deleting the workspace, app randomly repeats removed user messages and does not display removed user message for all users that were removed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/10992766-ac4b-41dd-ac5c-2fd1ae018f3b

https://github.com/Expensify/App/assets/93399543/813eaeef-7ac9-4db6-8075-bb6069b51a81

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690168747969629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf458e83d1c75708</li>
        <li>Upwork Job ID: 1683922394666582016</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-07-25 19:29
This looks like it's a back-end issue, so will need to be handled Internally.

**Comment by puneetlath** [comment] 2023-07-27 21:30
Moving to weekly. Will look into this soon.

**Comment by puneetlath** [comment] 2023-07-27 22:24
Actually, @yuwenmemon I believe you implemented workspace change logs, so I'm going to assign this over to you. Feel free to re-assign if I got that wrong. Thanks!

**Comment by yuwenmemon** [comment] 2023-07-28 12:37
@MonilBhavsar Can you take a look at this once since it's related to employees?

**Comment by MonilBhavsar** [comment] 2023-08-07 09:53
Looking this week

**Comment by MonilBhavsar** [comment] 2023-08-10 11:40
Looking today

**Comment by MonilBhavsar** [comment] 2023-08-21 14:50
Issue is identified. Doing some testing before submitting PR for review

**Comment by MonilBhavsar** [comment] 2023-08-28 20:57
@kbecciv can we please check if this issue is fixed

**Comment by kbecciv** [comment] 2023-09-01 11:20
Hey @MonilBhavsar Checking in latest build 1.3.61.0, will update you shortly

**Comment by kbecciv** [comment] 2023-09-01 11:28
Unable to reproduce on build 1.3.61.0, please attach the video.

https://github.com/Expensify/App/assets/93399543/dd365f5c-c2aa-4452-be0b-2b66e13d9fcc

**Comment by MonilBhavsar** [comment] 2023-09-01 11:32
Thanks, I am also not able to reproduce anymore.
So going to close it
Feel free to reopen if issue persists.

**Closed by MonilBhavsar** 2023-09-01 11:32 UTC
Labels: Reviewing, Daily, Internal, Bug
