### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Chat - Despite deleting the workspace, users still have access to Zoom and Google Meeting.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28959] opened 2023-10-05 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings and select Workspace.
2. If the workspace is not created, create a new one.
3. Delete the workspace by clicking on the three dots in the top right corner.
4. Go to admin> click on the three dots in the top right corner>Observe that the user still has access to Zoom and Google Meetings.

## Expected Result:
After deleting the workspace, users should no longer have access to Zoom and Google Meeting

## Actual Result:
 Even after deleting the workspace, users still have access to Zoom and Google Meetings.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a7f1be26-75c2-4ecf-81af-8c924733f358

https://github.com/Expensify/App/assets/93399543/d3729672-4c3a-4fc3-8825-340fd12a1bef

https://github.com/Expensify/App/assets/93399543/1ff76b3c-af94-4c2a-8c36-db86db3ba108

https://github.com/Expensify/App/assets/93399543/e7e32512-cb90-48c8-9fe3-d095cb59c1a4

https://github.com/Expensify/App/assets/93399543/46a54e4a-34e2-4752-9578-6fc4767da7fb

https://github.com/Expensify/App/assets/93399543/e6766e36-12a1-4ced-80b8-ffc192196b1d

https://github.com/Expensify/App/assets/93399543/81304b77-13c3-468a-8da4-f2d3e943390c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696487761131489
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abzokhattab** [comment] 2023-10-05 20:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 Even after the workspace is deleted, users still have access to Zoom and Google Meeting items in the menu chat.

### What is the root cause of that problem? 

 we don't check if the current room is archived or not when displaying the Zoom and Google meeting items in the menu

https://github.com/Expensify/App/blob/25f7ac14d3dcadbb60e24074494b12d181567ba3/src/pages/home/HeaderView.js#L163

### What changes do you think we should make in order to solve the problem?

add a condition to check if the current room is not archived before showing those items

```javascript
const isArchivedRoom = ReportUtils.isArchivedRoom(props.report);
```

and the line above to:
```javascript
    } else if (!isAutomatedExpensifyAccount && !isTaskReport && !isArchivedRoom) {
```

this way the Google and Zoom items will be shown in case the room is not archived

### POC

https://github.com/Expensify/App/assets/59809993/30de82ad-223c-4153-b457-7686277984f6

**Comment by saranshbalyan-1234** [comment] 2023-10-05 20:59
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Even after deleting workspace, users still have access to Zoom and Google Meeting
### What is the root cause of that problem?
We are checking whether the workspace has been deleted or not while showing the google meet and zoom in the menu.
Below is the code which explains this
https://github.com/Expensify/App/blob/42e22474aff3b929d98cf176876d43b14d4476c2/src/pages/home/HeaderView.js#L162-L179
### What changes do you think we should make in order to solve the problem?
we need to add this code to withOnyx HOC first
```javascript
    withOnyx({
        reportClosedAction: {
            key: ({report}) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.reportID}`,
            canEvict: false,
            selector: ReportActionsUtils.getLastClosedReportAction,
        },
``` 
and then add this same to the condition where we are pushing google meet and zoom link menu like this
```javascript
if (!isAutomatedExpensifyAccount && !isTaskReport && !props.reportClosedAction) {
        threeDotMenuItems.push({
            icon: ZoomIcon,
            iconFill: themeColors.icon,
            text: props.translate('videoChatButtonAndMenu.zoom'),
            onSelected: () => {
                Link.openExternalLink(CONST.NEW_ZOOM_MEETING_URL);
            },
        });
        threeDotMenuItems.push({
            icon: GoogleMeetIcon,
            iconFill: themeColors.icon,
            text: props.translate('videoChatButtonAndMenu.googleMeet'),
            onSelected: () => {
                Link.openExternalLink(CONST.NEW_GOOGLE_MEET_MEETING_URL);
            },
        });
    }
``` 
We can also add or remove these icons based upon the ARCHIVE_REASON, like for which archive reason to hide or for which to show according to the UX, which can be discussed.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2023-10-05 21:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Despite deleting the workspace, users still have access to Zoom and Google Meeting.
### What is the root cause of that problem?
Currently, in https://github.com/Expensify/App/blob/25f7ac14d3dcadbb60e24074494b12d181567ba3/src/pages/home/HeaderView.js#L163 We just render the Zoom and GG meet link when it's not `isAutomatedExpensifyAccount` and not `isTaskReport` 

### What changes do you think we should make in order to solve the problem?

In function `HeaderView` add check report is archived room
```
    const isArchivedRoom = ReportUtils.isArchivedRoom(props.report);
```
And add this to this condition

```
else if (!isAutomatedExpensifyAccount && !isTaskReport && !isArchivedRoom) {
        threeDotMenuItems.push({
            icon: ZoomIcon,
           ...
            },
        });
        threeDotMenuItems.push({
            icon: GoogleMeetIcon,
           ...
            }),
}
```

### What alternative solutions did you explore? (Optional)
- NA
### Result

<img width="1439" alt="Screenshot 2023-10-05 at 17 43 04" src="https://github.com/Expensify/App/assets/141406735/90d6b233-49cf-479f-8ac2-48c72c0b4204">

**Comment by abzokhattab** [comment] 2023-10-06 10:18
PR is ready

**Comment by techievivek** [comment] 2023-10-09 03:57
That's odd. You modified it before we merged the PR, right? I would expect it to post the comment here.

**Comment by abzokhattab** [comment] 2023-10-09 06:31
Yup it was modified before we merged

**Comment by abzokhattab** [comment] 2023-10-09 07:08
Also the offer was not sent on assigning the issue to me

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:51
@Ollyws could you please take care of the BZ checklist so we can prep to issue payment here?

**Comment by joekaufmanexpensify** [comment] 2023-10-17 20:03
@abzokhattab was assigned to the issue on 2023-10-06, and the PR was merged the same day, so this is eligible for a speed bonus. This means we need to pay: 

- @abzokhattab - $750 ($500 for PR and $250 speed bonus). Paid via Upwork. 
- @Ollyws - $750 ($500 for C+ and $250 speed bonus). Paid via Upwork. 
- @tewodrosGirmaA - $50 for reporting. Paid via upwork.

**Comment by joekaufmanexpensify** [comment] 2023-10-17 20:04
@Ollyws offer sent for $500 ($250 will be added as bonus)!

**Comment by joekaufmanexpensify** [comment] 2023-10-17 20:04
@abzokhattab  offer sent for $500 ($250 will be added as bonus)!

**Comment by joekaufmanexpensify** [comment] 2023-10-17 20:04
@tewodrosGirmaA offer sent for $50!

**Comment by joekaufmanexpensify** [comment] 2023-10-18 15:14
@abzokhattab $750 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-18 15:17
@Ollyws $750 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-10-18 15:17
@tewodrosGirmaA $50 sent and contract ended!

**Closed** 2023-10-18 15:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
