### ISSUE TITLE
[HybridApp] No notifications sent for IOU actions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32656] opened 2023-12-07 12:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Launch the app.
2. [User A] Background the app.
3. [User B] Send a money request.

## Expected Result:
User A receives app notification for the IOU request.

## Actual Result:
User A does not receive app notification for the IOU request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

Uploading Bug6304391_1701951931125!Screen_Recording_20231207_165213_One_UI_Home.mp4…

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d4949f0fdc96771</li>
        <li>Upwork Job ID: 1732743255318093824</li>
        <li>Last Price Increase: 2023-12-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28062411</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-12-12 06:43
Not overdue.

**Comment by Julesssss** [comment] 2023-12-14 16:33
I don't think this is still occurring, right?

**Comment by kadiealexander** [comment] 2023-12-15 04:35
@Julesssss I was able to reproduce it on my iOS device just now.

**Comment by Julesssss** [comment] 2023-12-15 08:53
Ah thanks, I can also reproduce on Android now (I thought this was related to a different notification issue we just resolved)

**Comment by artus9033** [comment] 2023-12-15 12:43
Hi, I'm Artur from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by Julesssss** [comment] 2023-12-15 14:40
Sounds good @artus9033, please go ahead

**Comment by artus9033** [comment] 2023-12-15 15:27
@kbecciv @Julesssss I tried to track the issue cause and found that the notification is properly handled, but is purposedly not shown since it has the `notificationPreference` set to `'hidden'`:

<img width="887" alt="image" src="https://github.com/Expensify/App/assets/10586109/6746c942-2d71-4b39-8681-e05d3b401132">

I saved the almost-full Pusher payload here (the rest was cut off by Flipper, probably it is too long, however what we need is in the captured part): https://gist.github.com/artus9033/1eae1602bc1905bce31956e3fb4283ea

<img width="603" alt="image" src="https://github.com/Expensify/App/assets/10586109/1ddc32c9-e8e7-45b6-871a-f579cd08b479">

The above can be found here: https://gist.github.com/artus9033/1eae1602bc1905bce31956e3fb4283ea#file-expensify-32656-log-json-L102

It seems to me that the problem resides in backend, since the data contains fields that inform the frontend not to show the notification and as far as I've been able to track it, there does not seem to be a single place in frontend that would modify it. Moreover, there is one more field, `childReportNotificationPreference` that also is set to `'hidden'`: https://gist.github.com/artus9033/1eae1602bc1905bce31956e3fb4283ea#file-expensify-32656-log-json-L29

I tried changing the notification settings for the private conversation with User B on UserA's side, but nothing helped - the preference field coming from Pusher is still `'hidden'`.

**Comment by Julesssss** [comment] 2023-12-15 16:07
Thanks @artus9033. This seems possibly related to the room notification preference somehow...

cc @arosiclair

**Comment by arosiclair** [comment] 2023-12-15 16:52
> I tried changing the notification settings for the private conversation with User B on UserA's side, but nothing helped - the preference field coming from Pusher is still 'hidden'.

So to clarify, you're seeing the default notification preference is `hidden` and you can't change it? Is this also an issue in workspace chats?

**Comment by artus9033** [comment] 2023-12-19 21:47
@arosiclair indeed, Pusher receives properly notifications in chats. One thing to note is that simply minimizing the app (I understand this is what @kbecciv meant in the [original post](https://github.com/Expensify/App/issues/32656#issue-2030686831) will not make the app use Airship to receive notifications. Going forward with this assumption, the logs state that the notification would be created (however it still is not since [`LocalNotification`](https://github.com/Expensify/App/blob/4b950101272fd9c73c160f40c4fc889ebb4b7b55/src/libs/Notification/LocalNotification/index.native.ts) does not carry an actual implementation on native
<img width="827" alt="image" src="https://github.com/Expensify/App/assets/10586109/aec96124-3e0f-428a-8784-cd17c06bb328">

**Comment by arosiclair** [comment] 2023-12-20 15:28
To clarify, push notifications are always delivered using Airship on native. On web and desktop, new messages are delivered through Pusher and trigger local notifications [here](https://github.com/Expensify/App/blob/bd7629edb5f1ce62d849348bb4d259b0502c9526/src/libs/actions/User.js#L529). That also happens on native but as you noticed, it is a no-op. 

You don't need to background the app to make them display on either platform, only ensure you're not already looking at the chat/report when you receive the message.

It sounds like this might need some internal repro/testing @Julesssss

**Comment by Julesssss** [comment] 2023-12-20 15:48
I'm ending my day now, but have loads of time to test this tomorrow if that's okay

**Comment by Julesssss** [comment] 2023-12-21 15:13
Okay, I looked into this today with a modified debuggable prod build and noticed two things:

1) No Android logs occur when a Request notification is sent, which suggests the Urban Airship push is getting entirely dropped, or is erroring. We need to investigate further [here](https://github.com/Expensify/Web-Expensify/blob/0ceb2a6a6a5b88dd1c3e972cee60e86bf62542a1/lib/UrbanAirshipAPI.php#L66-L67) -- we should also log failures, as I struggled to debug in Logsearch

2) here's an unrelated exception that occurs when sending a regular push notification that might be worth investigating: 

![Screenshot 2023-12-21 at 15 07 54](https://github.com/Expensify/App/assets/10736861/4e3e7e38-1a30-4fb8-9ab3-16aa71cca35f)

**Comment by Julesssss** [comment] 2023-12-21 15:18
There is also a good argument to be made that this should be attached to a wave

**Comment by Julesssss** [comment] 2024-01-04 10:07
I was OOO. No change here

**Comment by Julesssss** [comment] 2024-01-12 14:20
Working on some Wave 5 issues that are more critical, going to reduce priority here

**Comment by Julesssss** [comment] 2024-01-22 11:38
Aiming to pick this up after my current wave 5 issue

**Comment by Julesssss** [comment] 2024-02-02 15:12
Will pick up soon

**Comment by Julesssss** [comment] 2024-02-14 17:38
Not yet prioritised in a project

**Comment by Julesssss** [comment] 2024-02-28 16:01
Same as above

**Comment by Julesssss** [comment] 2024-03-13 13:51
Same as above

**Comment by Julesssss** [comment] 2024-03-14 13:21
We're going to prioritise this under wave-collect and get this fixed. First step is to build the the IOU string from the message/originalMessage data, then to call `UrbanAirshipAPI::sendPushNotification` for the IOU flows. 

I'll start work on it tomorrow 🤩

**Comment by Julesssss** [comment] 2024-03-20 09:43
Not 4 days overdue... stupid bot

**Comment by Julesssss** [comment] 2024-03-20 10:30
I wrote out a comment yesterday but must have forgot to send it. 

Yesterday I debugged the IOU commands and discovered that `accountsToNotify` doesn't include the receiver, it seems that they are marked as 'hidden'. Will continue my debugging today.

**Comment by Julesssss** [comment] 2024-03-20 15:15
We appear to be marking Chat Reports with `notificationPreference: 'hidden'`...

**Questions**
- When did this start happening
- Why doesn't the `notificationPreference` matter for comments?

**Comment by Julesssss** [comment] 2024-03-20 15:45
I think I have the answers:

- IOU reports have their `notificationPreferences` rNVP set to 'hidden' by default, whereas chat reports have the `notificationPreferences` rNVP set to 'always'
- This should be fine because users cannot modify the IOU notification preference
- The problem is that we're using the IOU report preference when sending notifications when instead we should be using the associated chatReport preference
-  As a follow-up, perhaps we should not be setting the rNVP for IOU reports, as this is useless

**Comment by Julesssss** [comment] 2024-03-26 16:07
I'm pausing work here to focus on more critical issues. But for my future reference: 

- [Here](https://github.com/Expensify/App/issues/32656#issuecomment-2009889533) is the cause and solution
- My branch has logs for debugging the NVP value: `jules-iouActionNotifications`

**Comment by Julesssss** [comment] 2024-03-26 16:12
I'm pausing work here to focus on more critical issues. But for my future reference: 

- [Here](https://github.com/Expensify/App/issues/32656#issuecomment-2009889533) is the cause and solution
- My branch has logs for debugging the NVP value: `jules-iouActionNotifications`
- Here are my most recent notes on the report default NVPs: 
    ![PXL_20240326_161039783](https://github.com/Expensify/App/assets/10736861/646a5f59-3ee5-47cf-b795-9dd60494effe)

**Comment by Julesssss** [comment] 2024-04-04 09:01
[Here's](https://expensify.slack.com/archives/C036QM0SLJK/p1711671592488769) a relevant discussions for the cause of this issue

**Comment by Julesssss** [comment] 2024-04-22 09:54
Tomorrow I will be back to catch up, clear chores/reviews, attend an interview. Then can continue here

**Comment by Julesssss** [comment] 2024-04-23 15:49
It's possible we'll bundle this into the wider notification project, but I still see this being a valid separate bug to be worked on simultaneously

**Comment by Julesssss** [comment] 2024-04-24 07:21
It's possible we'll bundle these changes into the 'send notifications to correct experience' project, holding for now

**Comment by Julesssss** [comment] 2024-04-29 08:14
Okay, the solution here will need to align with the wider changes. Holding.

**Comment by Julesssss** [comment] 2024-05-08 11:15
The dupe-notifications project is still blocking this. But we may not solve as part of the project

**Comment by Julesssss** [comment] 2024-05-20 13:09
Held on dupe notifications, which in turn is held on slow API fire

**Comment by Julesssss** [comment] 2024-05-29 15:53
Same as above, will be the case for at least the next month

**Comment by Julesssss** [comment] 2024-07-09 15:45
Attached to Hybrid project, but I have higher priority issues to work on.

**Comment by Julesssss** [comment] 2024-07-18 11:25
Less important than other Hybrid issues for now

**Comment by Julesssss** [comment] 2024-07-18 11:25
Less important than other Hybrid issues for now

**Comment by Julesssss** [comment] 2024-07-29 12:52
Less important than other Hybrid issues

**Comment by Julesssss** [comment] 2024-08-08 08:18
Way less important than other issues currently

**Comment by trjExpensify** [comment] 2024-08-09 01:37
I've kind of lost track of what we're actually going to do with this issue? Once we're notifying on the correct experience, won't this happen:

- The first expense added to a report creates the IOUPREVIEW in the workspace chat and notifies
- Every expense thereafter added to the report will not notify, because 1) the report preview doesn't move position anymore since comment linking and 2) the expense report's notificationPreference is `hidden` by default
- [Coming soon, @garrettmknight?] For workspaces using delayed submission, when the expense report is submitted, we'll add a whisper to the workspace chat for the approver which will notify them that they have a report to approve.

**Comment by Julesssss** [comment] 2024-08-09 10:30
I also am not certain this is still necessary. Let me get back to triaging this and verifying your points once other Hybrid issues have been resolved, as either way this is lower priority.

**Comment by trjExpensify** [comment] 2024-08-09 11:20
Sounds good!

**Comment by Julesssss** [comment] 2024-08-09 13:00
FYI I'm OOO most of next week, so will find time for triaging when in Savannah

**Comment by Julesssss** [comment] 2024-08-12 15:33
As above, this has to wait until next week at the earliest

**Comment by Julesssss** [comment] 2024-08-21 19:09
Delaying again. I can't yet find time to triage

**Comment by Julesssss** [comment] 2024-08-27 15:23
I'll be picking this up as we begin to work on the HybridApp notification polish issues

**Comment by Julesssss** [comment] 2024-09-05 08:45
Lower down the list of HybridApp priorities

**Comment by Julesssss** [comment] 2024-09-11 14:20
The initial issue was created so long ago that it might just apply to 1:1 money requests... One initial test would be to do the following: 

- I will set our DM to `Notify: Mute`
- You can then request money from me
- Lets see if I receive the money request notification

____________________________________

> Every expense thereafter added to the report will not notify, because 1) the report preview doesn't move position anymore since comment linking and 2) the expense report's notificationPreference is hidden by default

Then, we should be able to verify this with a senior-leader expense approver, right?

**Comment by trjExpensify** [comment] 2024-09-11 19:07
>Then, we should be able to verify this with a senior-leader expense approver, right?

Doesn't even need that. I just have to submit a second request to you.

**Comment by trjExpensify** [comment] 2024-09-11 19:08
>I will set our DM to Notify: Mute

Why would you do that? Just leave it as `Always`. You'll get a notification for the first expense that creates the REPORTPREVIEW. 

Then I'll send you another one, which adds to the same report and "updates in place" the REPORTPREVIEW, and you won't get notified about it. 

That's all by design with how it works now.

**Comment by trjExpensify** [comment] 2024-09-11 19:08
Drop me a message tomorrow and we can test.

**Comment by Julesssss** [comment] 2024-09-25 16:44
With HybridApp notifications working this one is closer to being prioritised. 

Here are some blockers: 
- https://github.com/Expensify/Expensify/issues/424424
- https://github.com/Expensify/Expensify/issues/428777

**Comment by arosiclair** [comment] 2024-09-30 19:17
This should be working already. I refactored it in [this PR](https://github.com/Expensify/Web-Expensify/pull/41766) a while ago. We have a test for it [here](https://github.com/Expensify/Web-Expensify/blob/367d86453703b0f71c42d661bca8b9c88cbf9f27/_tests/integration/lib/MobilePushNotificationsTest.php#L265) as well. I think we can just close this unless there is something else broken.

**Comment by trjExpensify** [comment] 2024-09-30 19:44
Works for me, but we can wait for Jules to see this tomorrow before we close.

**Comment by Julesssss** [comment] 2024-10-01 09:05
Great, lets close 👍

**Comment by trjExpensify** [comment] 2024-10-01 09:26
Cool, done.

**Closed** 2024-10-01 09:26 UTC
Labels: Engineering, Weekly, Internal, Bug
