### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] [P2P Distance] - Split amount is not recalculated when entering 0 as input & editing distance

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48302] opened 2024-08-29 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat.
3. Click + > Split expense > Distance.
4. Enter waypoints > Next.
5. Manually enter 0 on the split input field next to any participant.
6. Click RHP back button.
7. Edit the waypoints.
8. Click Next.

## Expected Result:
The individual split amount will be recalculated and equal split will be populated in the input field for each participant.

## Actual Result:
The input fields for the other participants become 0, while random amount is calculated for the user that has 0 in input field in Step 5.
Reset button also disappears.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a637a37d-e9d4-4ed9-9381-0478ede90013

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831341350520719367</li>
        <li>Upwork Job ID: 1831341350520719367</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103887821</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by IuliiaHerets** [comment] 2024-08-29 21:28
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment] 2024-09-03 21:08
I'm not really sure this behavior is something we will see, let alone something we should optimize. [Getting a sense check](https://expensify.slack.com/archives/C05RECHFBEW/p1725397522118029).

**Comment by johncschuster** [comment] 2024-09-04 14:39
Ok! We discussed this, and it sounds like we _do_ expect this behavior. I'll triage it.

**Comment by rushatgabhane** [comment] 2024-09-09 18:31
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/48302#issuecomment-2331127587) LGTM 🎀 👀 🎀

**Comment by nkdengineer** [comment] 2024-09-18 11:19
@rushatgabhane @Beamanator I had a problem when I tried to revert main on this [PR](https://github.com/Expensify/App/pull/48855) and it automatically closed and couldn't be reopened anymore. I created a new PR [here](https://github.com/Expensify/App/pull/49381). Sorry for the inconvenience.

**Comment by johncschuster** [comment] 2024-10-11 21:02
@rushatgabhane Do you feel we need a regression test step list? If so, can you provide one?

**Comment by johncschuster** [comment] 2024-10-11 21:29
Payment Summary:

Contributor: @nkdengineer paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/103887821) - PAID! 🎉 

Contributor+: @rushatgabhane due $250 via NewDot

Upwork job [here](https://www.upwork.com/nx/wm/offer/103887821)!

**Comment by garrettmknight** [comment] 2024-10-15 01:08
$250 approved for @rushatgabhane

**Comment by johncschuster** [comment] 2024-10-15 21:47
Looks like we can close this one up then. Thanks, everyone!

**Closed by johncschuster** 2024-10-15 21:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
