### ISSUE TITLE
[$250] "GBR" does not disappear from LHN after expense report get paid

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42424] opened 2024-05-21 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1716225295915829

## Action Performed:
1. User A submits a expense report as employee
2. Approver approves the report and pays the expense reports
## Expected Result:
GBR should disappear from the LHN
## Actual Result:
"GBR" does not disappear from LHN after expense report get paid
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f823f97a-501a-4ec3-b3a5-03fb8a5b719e

https://github.com/Expensify/App/assets/38435837/2667da17-0140-4fa4-8a36-f31640f192b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea373b9d67348f29</li>
        <li>Upwork Job ID: 1798111864646688768</li>
        <li>Last Price Increase: 2024-07-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by kevinksullivan** [comment] 2024-06-04 21:57
This one fits in collect since it's related to paying an expense report.

**Comment by jjcoffee** [comment] 2024-06-17 10:05
@kevinksullivan Were you ever able to reproduce this?

**Comment by jacobkim9881** [comment] 2024-06-17 12:53
> "GBR" does not disappear from LHN after expense report get paid

GBR doesn't work based on such logics from here below:

https://github.com/Expensify/App/blob/59e4f8b468631ad5d078a509f8c29f7069e2f095/src/libs/ReportUtils.ts#L1248-L1262

https://github.com/Expensify/App/blob/59e4f8b468631ad5d078a509f8c29f7069e2f095/src/libs/SidebarUtils.ts#L427-L431

Should GBR disappear after expense report get paid?

**Comment by jjcoffee** [comment] 2024-06-17 13:24
@jacobkim9881 It looks like the areas of code you're referring to relate to having a pending join request, not an expense report.

**Comment by jacobkim9881** [comment] 2024-06-17 14:29
@jjcoffee You are right! I bring related area of codes.

https://github.com/Expensify/App/blob/09ce6375914524757b8047f9ce1b1396cca30c38/src/libs/ReportUtils.ts#L2292-L2319

If expanse report is paid then this should work 

```js
     // Has a child report that is awaiting action (e.g. approve, pay, add bank account) from current user 
if (optionOrReport.hasOutstandingChildRequest) { 
         return true; 
     } 
```

If it has the issue then `optionOrReport.hasOutstandingChildRequest` isn't erased or some other not related the issue triggers `requiresAttentionFromCurrentUser`.

**Comment by jjcoffee** [comment] 2024-06-19 10:40
Chill Melv, we're still waiting for proposals :smile:

**Comment by mvtglobally** [comment] 2024-06-20 14:20
Issue not reproducible during KI retests. (First week)

**Comment by jjcoffee** [comment] 2024-06-25 09:13
No proposals and not reproducible currently. @kevinksullivan should we close this?

**Comment by jjcoffee** [comment] 2024-06-26 08:50
Unassigned as I'm going OOO soon. cc @kevinksullivan

**Comment by kevinksullivan** [comment] 2024-07-03 14:24
Not reproducible so going to close.

**Closed by kevinksullivan** 2024-07-03 14:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
