### ISSUE TITLE
[HOLD] [$1000] Faulty Back button: Still able to send messages after leaving the Public room- Android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21517] opened 2023-06-25 15:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with User A ( mobile number) > create a workspace with user B and C
2. Create a room in public mode
3. Send the public room link or QR code to User B and User C
4. Open User B in android and scan the QR code & join the room
5. From User B, send messages to the room
6. Leave the room
7. Click on the back button twice. You will be back in the room.
8. Send message again in room.
9. Verify if you are able to send messages.

## Expected Result:
Shouldn't be able to message in the room after leaving it
## Actual Result:
Was able to message in the room in spite of leaving it due to faulty back button . I shouldn’t be able to join by clicking the back button.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1d60f37d-4714-480f-9189-40d831f03512

https://github.com/Expensify/App/assets/43996225/4457b978-adc0-4b34-bf74-19272997612b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687046192591549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136d4ec118fd1440f</li>
        <li>Upwork Job ID: 1673753738983735296</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-06-27 18:03
OP is very detailed, looks like this reproducible - added `External` label so that a contributor can review the existing proposal.

**Comment by maddylewis** [comment] 2023-06-30 14:12
re-applied `External` label so that a new contributor could be assigned to review the existing proposal.

**Comment by sobitneupane** [comment] 2023-07-03 07:30
I think this issue is duplicate of https://github.com/Expensify/App/issues/20908

**Comment by maddylewis** [comment] 2023-07-05 13:21
holding based on this comment - https://github.com/Expensify/App/issues/21517#issuecomment-1618222208

**Comment by maddylewis** [comment] 2023-07-14 00:18
https://github.com/Expensify/App/issues/20908 is still open / still holding

**Comment by maddylewis** [comment] 2023-07-24 16:31
still holding - https://github.com/Expensify/App/issues/20908

**Comment by maddylewis** [comment] 2023-08-02 19:34
still holding - this issue is still open https://github.com/Expensify/App/issues/20908

**Comment by maddylewis** [comment] 2023-08-24 20:49
still on hold i believe - https://github.com/Expensify/App/issues/20908

**Comment by maddylewis** [comment] 2023-09-06 16:21
this has been fixed - https://github.com/Expensify/App/issues/20908

**Comment by maddylewis** [comment] 2023-09-08 14:58
@0xmiroslav - let me know if we're good to move forward with a fix for this one now - thx!

**Closed** 2023-09-22 17:39 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
