### ISSUE TITLE
[$500] Room - Admin room shows Workspace name changed in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33323] opened 2023-12-19 22:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Dot app
2. Create new workspace
3. Go offline
4. Navigate to workspace settings and change the workspace name
5. Go to LHN and notice the room behavior

## Expected Result:
Rooms should not change the name of the workspace while offline

## Actual Result:
Admin room shows Workspace name changed in offline mode even system message is not present yet ( it appear when come back online)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1c092876-f748-4533-a7ef-36f4b27d0123

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f38ac31593c63fb</li>
        <li>Upwork Job ID: 1737233297570545664</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-12-20 00:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
workspace rooms show the changed name in offline mode even though its not yet committed to the db


### What is the root cause of that problem?

Since the expected behavior here that rooms should not change the name of the workspace while offline. then we need to disable  editing the name while being offline

This behaviro is enabled here: https://github.com/Expensify/App/blob/c6208fe53a902a83bb49c7448f75874bda6cc682/src/pages/workspace/WorkspaceSettingsPage.js#L111



 
### What changes do you think we should make in order to solve the problem?


remove the `enabledWhenOffline` prop that is passed to the form provider

**Comment by Tony-MK** [comment] 2023-12-20 01:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Admin room shows Workspace name changed in offline mode

### What is the root cause of that problem?

The root cause of the problem is we are using the updated workspace name when it is fetched with the `ReportUtils.getPolicyName` function. Hence, the admin room will change immediately after the workspace name changes whether offline or online.

https://github.com/Expensify/App/blob/8a283f0e1fa292fe1a18c673b3e44fc5c4ad915a/src/libs/ReportUtils.ts#L448-L455

### What changes do you think we should make in order to solve the problem?


Create a temporary attribute on the policy onyx to store the previous name. We will delete it when the user goes online because `successData` will do it. It will not be name 
Then insert a condition in the code from [`ReportUtils.getPolicyName`](https://github.com/Expensify/App/blob/8a283f0e1fa292fe1a18c673b3e44fc5c4ad915a/src/libs/ReportUtils.ts#L439) to check to see if the attribute is present and use it, instead of the policy name.

https://github.com/Expensify/App/blob/8a283f0e1fa292fe1a18c673b3e44fc5c4ad915a/src/libs/ReportUtils.ts#L453-L453

**Comment by cubuspl42** [comment] 2023-12-20 10:44
@isabelastisser Would you consider this a bug?

**Comment by isabelastisser** [comment] 2023-12-20 20:03
Good question, asking [here.](https://expensify.slack.com/archives/C01SKUP7QR0/p1703102599618049)

**Comment by isabelastisser** [comment] 2023-12-20 20:17
Confirmed this is expected behavior. We can expect the Workspace room name to change for the member who edited it, but not for other members until they’re back online.

Closing!

**Closed by isabelastisser** 2023-12-20 20:17 UTC
Labels: External, Daily, Help Wanted, Bug
