### ISSUE TITLE
[HOLD on #11768] [$1000] ESC key exits from chat too when pressed to close edit composer in small screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18824] opened 2023-05-12 07:46 UTC
HOLD on https://github.com/Expensify/App/issues/11768

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open a chat
2. send a message
3. click edit
4. press ESC

## Expected results: 
should close edit composer
## Actual results: 
closes main chat too

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/db5acc72-794c-4bb1-9b70-de93fd7b8bcf

https://github.com/Expensify/App/assets/43996225/02917e06-dd92-4ed8-9f47-baeb48f2259b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683801698896399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101ca08a3d30b1843</li>
        <li>Upwork Job ID: 1658127483791474688</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by chiragxarora** [comment] 2023-05-12 09:42
@allroundexperts isn't it the ideal behaviour? problem is with edit composer where one ESC is taking effect two times

**Comment by chiragxarora** [comment] 2023-05-12 09:55
on full screen, ESC closes the edit composer completely, and not just un-focuses it

**Comment by lschurr** [comment] 2023-05-12 21:43
To confirm, are we saying that this is a bug or is expected @allroundexperts @chiragxarora? Could you start a convo in Slack if necessary?

**Comment by chiragxarora** [comment] 2023-05-13 08:12
It's a bug @lschurr 
ESC is supposed to only close the edit composer but first it's closing the edit composer and then it's closing the chat (as if ESC is pressed twice)

**Comment by lschurr** [comment] 2023-05-15 15:09
Got it, thanks!

**Comment by Colyail** [comment] 2023-05-15 15:33
I can help you. Invite me. Thanks.

**Comment by rzvc** [comment] 2023-05-16 10:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the escape key is pressed, the editor exits the chat, in small screen.

### What is the root cause of that problem?

The Escape key gets handled, but it keeps propagating up, to other event listeners.

### What changes do you think we should make in order to solve the problem?

We should add `e.stopPropagation();` after `e.preventDefault()` in triggerSaveOrCancel(), in ReportActionItemMessageEdit.js: https://github.com/Expensify/App/blob/a2c613b1e13bc9f76da46141de0499d59875b255/src/pages/home/report/ReportActionItemMessageEdit.js#L250

This will allow the event to be handled properly by the editor and prevent it from bubbling up.

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2023-05-16 18:27
@allroundexperts  Thank you for the proposal here - https://github.com/Expensify/App/issues/18824#issuecomment-1545435898

I think the Root cause might be correct. But I have to dive deep on the library to be sure if the root cause is correct.
Regarding the solution, I wouldn't like to patch the library for a behaviour expected from it, since its used in all our pages and works fine to go back when we press 'Esc' Key.

The solution of listening to keyup is working but the drawback it has is, it is not allowing me to go back even if I press esc from the main composer.
And the alternate solution to stop bubbling by sending param as false doesn't seem to work. 
Let me know if I missed any or I should try it different way

**Comment by abdulrahuman5196** [comment] 2023-05-16 18:28
@rzvc Thank you the proposal at https://github.com/Expensify/App/issues/18824#issuecomment-1549386194
But it doesn't seem to work for me. Let me know if I had to try it different way.

**Comment by lschurr** [comment] 2023-05-16 19:27
I'm headed OOO from May 17th-23rd. I re-added the Bug label to reassign and left myself assigned as well. If any action is needed when I return on May 24th, I'll take this back from you @conorpendergrast!

Latest: Still reviewing proposals.

**Comment by YousefKhawaga** [comment] 2023-05-17 08:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
ESC key exits from chat when pressed to close the edit composer
### What is the root cause of that problem?
React navigation listens to the key and handle the back
### What changes do you think we should make in order to solve the problem?
add navigation listener to check before closing if the edit is focused then stop going back as mentioned in there docs
```
navigation.addListener('beforeRemove', (e) => {
        if (textInput.isFocused()) {
        // Prevent default behavior of leaving the screen
          e.preventDevault();
        }}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by abdulrahuman5196** [comment] 2023-05-17 20:17
I did a dive deep and @allroundexperts  root cause is correct - https://github.com/Expensify/App/issues/18824#issuecomment-1545435898. It actually goes here and calls handleDrawerOpen which opens the LHN page.
https://github.com/react-navigation/react-navigation/blob/9fe34b445fcb86e5666f61e144007d7540f014fa/packages/drawer/src/views/DrawerView.tsx#L147-L149

The ESC key not just goes back a page like back button, if you are in any place it just brings back to the LHN page. 

Now the solutions will be tied to the react-navigation library(which I assume should be gone with the new navigation we are building) or its counterpart fix in our codebase in this case.

Should we move it to hold for navigation or fix it now? @Gonals

**Comment by abdulrahuman5196** [comment] 2023-05-19 18:24
@Gonals  Could you kindly provide your thoughts on the above? https://github.com/Expensify/App/issues/18824#issuecomment-1552006903

**Comment by Gonals** [comment] 2023-05-22 08:53
I think we can HOLD for now to avoid double-fixing this after the new navigation is done, unless we hear a lot of complaints. What do you think, @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment] 2023-05-22 08:53
@Gonals  Sounds good to me.

**Comment by conorpendergrast** [comment] 2023-05-22 14:09
@Gonals Do you have a link to what this is on-hold for?

**Comment by abdulrahuman5196** [comment] 2023-05-23 12:12
@conorpendergrast this is the navigation reboot tracking jira - https://github.com/Expensify/App/issues/11768
And we can move this issue to weekly

**Comment by lschurr** [comment] 2023-05-23 22:14
Thanks for jumping in @conorpendergrast - I'm back from OOO so I'll remove your assignment.

**Comment by lschurr** [comment] 2023-06-01 01:33
Looks like this is still on hold.

**Comment by lschurr** [comment] 2023-06-20 20:18
Still on hold.

**Comment by lschurr** [comment] 2023-06-28 20:27
Still on hold.

**Comment by lschurr** [comment] 2023-07-07 20:19
On hold.

**Comment by abdulrahuman5196** [comment] 2023-07-08 16:36
@lschurr  Navigation reboot is done, this issue should be taken off hold. 

And i am unable to reproduce this issue. Could you kindly check and close if this is not reproducible for you as well?

**Comment by lschurr** [comment] 2023-07-11 17:54
This got fixed elsewhere though right @chiragxarora?

**Comment by mountiny** [comment] 2023-07-13 17:26
Yep, this is eligible for the reporting bonus.

$250 to @chiragxarora and we can close this out

**Comment by lschurr** [comment] 2023-07-18 17:08
Oops! Could you put your Upwork profile here @chiragxarora?

**Comment by lschurr** [comment] 2023-07-18 17:20
Invited you to the job!

**Comment by lschurr** [comment] 2023-07-18 18:05
Paid! Closing this one out.

**Closed by lschurr** 2023-07-18 18:05 UTC
Labels: External, Weekly, Help Wanted, Bug
