### ISSUE TITLE
iOS - Chat - Crash when attempting to open chat started on another device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28068] opened 2023-09-23 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open and log into Account A on staging.new.expensify.com
2. On another device, use Account A and send message to any other account to begin chat
3. Open new chat on initial device

## Expected Result:
User is able to open chat to continue conversation

## Actual Result:
The page crashes and user is unable to access chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/51d8584b-c525-4b94-8f6f-96063dd00340

[logs ios.txt](https://github.com/Expensify/App/files/12706761/logs.ios.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2023-09-27 04:16
I think this might be a dupe of https://github.com/Expensify/App/issues/28066

**Comment by sonialiap** [comment] 2023-10-02 04:30
I believe this was resolved in https://github.com/Expensify/App/issues/28066 last week

**Closed by sonialiap** 2023-10-02 04:30 UTC
Labels: Daily, Overdue, Bug
