### ISSUE TITLE
Preferences- Use staging server is not on by default.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10963] opened 2022-09-13 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #10935
## Action Performed:
1. Open app
2. Log in any account
3. Go to Settings -> Preference
4. Verify that Use staging server switch in on by default

## Expected Result:
Use staging server should be enabled by default

## Actual Result:
Use staging server is not  on by default

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/189949587-8a01ab2d-9444-4184-b5aa-b3af1ef517ce.mp4

https://user-images.githubusercontent.com/43996225/189949602-3bd47291-2787-460f-9493-5c5d2ecb67a6.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Santhosh-Sellavel** [comment] 2022-09-13 16:45
Seems the changes are not updated.

Unsure why?

<img width="975" alt="Screenshot 2022-09-13 at 10 13 20 PM" src="https://user-images.githubusercontent.com/85645967/189959306-ee47412e-be2f-4ae4-b865-27c9a50b28cc.png">

I believe that's the reason for this regression!
 cc: @mountiny

**Comment by mountiny** [comment] 2022-09-14 09:23
This is a problem with our GH CD/CI which we encountered already once before. Discussing internally in [Slack here](https://expensify.slack.com/archives/C07J32337/p1663114901154789)

**Comment by MonilBhavsar** [comment] 2022-09-15 07:13
@mountiny the code didn't get deploy properly and caused this issue?

**Comment by mountiny** [comment] 2022-09-15 11:23
I can confirm now this should be fixed now 🙇

**Closed by mountiny** 2022-09-15 11:23 UTC
Labels: Engineering, Daily

**Comment by MonilBhavsar** [comment] 2022-09-15 11:40
Yes that's weird. Thanks for clarifying!

**Comment by mountiny** [comment] 2022-09-15 11:43
No problemo
