### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] Android - Workspace- WS invite message shows html message briefly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42668] opened 2024-05-27 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4578418
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap profile -- workspaces -- workspace
3. Tap members -- invite member
4. Select a user and tap next
5. Tap app's back button
6. Tap next

## Expected Result:
Workspace invite message must not show html message briefly

## Actual Result:
Workspace invite message shows html message briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9110fcb7-7bdd-465b-addf-009d9147113a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2c0cb41c6778335</li>
        <li>Upwork Job ID: 1796503664094650368</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 102917575</li>
<li>bernhardoj | Contributor | 102917576</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by lanitochka17** [comment] 2024-05-27 20:47
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-27 20:47
We think that this bug might be related to #vip-vsp

**Comment by neonbhai** [comment] 2024-05-27 21:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS invite message shows html message briefly 

### What is the root cause of that problem?
We don't parse to Markdown when setting default value here:
https://github.com/Expensify/App/blob/563f8c704bca0c271ad8b2b9454e07462039b416/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L202

### What changes do you think we should make in order to solve the problem?
We should call the parser when setting default value:

```jsx
defaultValue={parser.htmlToMarkdown(getDefaultWelcomeNote())}
```

**Comment by bernhardoj** [comment] 2024-05-28 05:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS invite message page shows a message with HTML briefly.

### What is the root cause of that problem?
The initial value of `welcomeNote` is empty, so it will use the `defaultValue`.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L202-L203

The default value will take the workspace.common.welcomeNote translation and convert it to HTML (replace).
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L82-L93
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/languages/en.ts#L1924-L1925

Then, this useEffect that is triggered on mount will update the `welcomeNote` state by taking the default value HTML and convert it to markdown.

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L95-L97

That's why we see the HTML form briefly before the markdown.

### What changes do you think we should make in order to solve the problem?

The only markdown in the default welcome note is the link and possibly the workspace name (if the workspace name contains a markdown),
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/languages/en.ts#L1924-L1925

and I don't think it's necessary to convert it to HTML and then back to markdown just to make the link shown as
`[use.expensify.com/download](https://use.expensify.com/download)`.

The ExpensiMark already has an auto link rule that will convert `use.expensify.com/download` to a link.

Also, let's say the workspace name is *b*, if we call `replace` and `htmlToMarkdown`, it will just become *b* again, so it does nothing.

So, I would prefer to remove the `replace` and `htmlToMarkdown` logic to keep it simple.

**Comment by sonialiap** [comment] 2024-05-30 12:20
Sounds buggy to me. Adding help wanted

**Comment by sonialiap** [comment] 2024-05-31 11:27
Thanks for the catch! Adding External, hopefully automation runs this time

**Comment by bernhardoj** [comment] 2024-06-06 06:33
I believe that's simply because the web perf is faster. You can put a delay here and notice the issue on web too.
https://github.com/Expensify/App/blob/0ae7febfa7f72d5c1563a23d3b8b05e576e12d68/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L96-L99

**Comment by narefyev91** [comment] 2024-06-14 06:51
> @bernhardoj so your solution is to revert [11916b5](https://github.com/Expensify/App/commit/11916b569b4648c8ea1013d94dbaee36de4f3e44), right? There must be a reason why parser was introduced. @narefyev91 appreciate if you can chime in here.

The problem was in link - at that time either ExpensiMark was not able to automatically convert link or response from BE changed. Hard to say - but generally speaking - root problem to add parser was to show a link for download correctly. Hope that helps!

**Comment by bernhardoj** [comment] 2024-06-29 04:11
PR is ready

cc: @mkhutornyi

**Comment by roryabraham** [comment] 2024-07-17 06:51
PR merged

**Comment by bernhardoj** [comment] 2024-07-19 05:22
A new PR to address https://github.com/Expensify/App/issues/45740 is up

cc: @mkhutornyi

**Comment by sonialiap** [comment] 2024-07-26 11:19
Payment summary:
- @bernhardoj $250 - paid ✔️ 
- @mkhutornyi $250 - paid ✔️ - please complete the [checklist](https://github.com/Expensify/App/issues/42668#issuecomment-2239977344)

**Comment by sonialiap** [comment] 2024-07-30 13:57
Thanks Mykhailo 🎉

**Closed by sonialiap** 2024-07-30 13:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
