### ISSUE TITLE
[$1000] Web - Assign task - Cancelled task shows 1 in reply even if there is not message on it.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20551] opened 2023-06-09 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app.
2. Create a task with someone in DM.
3. Assign the other user in the DM to the Task.
4. Cancel the Task.
5. Go back to the DM.
6. Observe the Main task message in the Chat.

## Expected Result:
As there was no message in the Task report, it should not say `reply 1` in the main Chat.

## Actual Result:
It says reply 1 for the archived tasks.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bebf6154-9cab-45d8-bb52-5982a96fa3f1

https://github.com/Expensify/App/assets/93399543/87601a56-2e81-4924-9834-ee44327473ca

**Expensify/Expensify Issue URL:**

**Issue reported by:** @parasharrajat

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686055628847919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016716974368a9a3ff</li>
        <li>Upwork Job ID: 1668412099502555136</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-06-13 00:17
@yuwenmemon and @Santhosh-Sellavel - Do you agree this should be [internal](https://github.com/Expensify/App/issues/20551#issuecomment-1585620215)? If not, let me know or feel free to reapply labels so this is external.

**Comment by Santhosh-Sellavel** [comment] 2023-06-13 20:18
Waiting for proposals

**Comment by Santhosh-Sellavel** [comment] 2023-06-15 19:25
Alright, this is not a bug, a reply is added for Cancelling task, and that's what is shown as 1 reply.

<img width="985" alt="Screenshot 2023-06-16 at 12 53 56 AM" src="https://github.com/Expensify/App/assets/85645967/6e029bc0-df2b-4e49-a0c3-d3c375057a4e">

**Comment by Santhosh-Sellavel** [comment] 2023-06-15 19:33
@parasharrajat Please check the second video in the issue description, it has the cancel message.

<img width="1288" alt="Screenshot 2023-06-16 at 1 01 45 AM" src="https://github.com/Expensify/App/assets/85645967/cc0b6785-9bed-4f39-bfa1-1855d54c7763">

**Comment by Santhosh-Sellavel** [comment] 2023-06-15 19:57
@parasharrajat 
I did follow the same steps. I see a new issue, redundant messages for the same task in the main.

https://github.com/Expensify/App/assets/85645967/ee1f7f18-6aec-48c1-8611-35b21fd5a809

**Comment by Santhosh-Sellavel** [comment] 2023-06-15 20:33
Reported that in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1686860992509259) to ensure it was not reported earlier. We can close this @strepanier03 one, thanks!

**Comment by strepanier03** [comment] 2023-06-15 21:07
Closing this task as not a bug. Thanks @Santhosh-Sellavel

**Closed by strepanier03** 2023-06-15 21:07 UTC
Labels: Engineering, Daily, Internal, Bug
