### ISSUE TITLE
HIGH: [UX Reliability] [$250] The loading spinner is not shown when a public room is accessed anonymously for the first time

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38718] opened 2024-03-20 22:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcochavez
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1710955781785969

## Action Performed:
Open chrome dev tools and click on Clear site data from Application tab
Navigate to a public room like https://staging.new.expensify.com/r/868417741568295
## Expected Result:
The loading spinner is shown when a public room is accessed anonymously for the first time
## Actual Result:
The loading spinner is not shown when a public room is accessed anonymously for the first time
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/25ec3067-0b6c-47d8-9538-2ab2a0aa014a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01094c26a6aa176e3f</li>
        <li>Upwork Job ID: 1784727625880760320</li>
        <li>Last Price Increase: 2024-04-28</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-03-21 08:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The loading spinner is not shown when a public room is accessed anonymously for the first time
### What is the root cause of that problem?
[Here](src/libs/Navigation/AppNavigator/index.tsx) we check if the user is authenticated and return protected or public screens. Since during the first login there is no token in the session yet, we navigate the user to sign in screen. 
### What changes do you think we should make in order to solve the problem?
1. Update [this](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L251C13-L251C78) line like below
```
{!initialUrl && shouldHideSplash && <SplashScreenHider onHide={onSplashHide} />}
```
2. Add finally method for [Navigation.waitForProtectedRoutes](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2221C1-L2243C11) which will call `BootSplash.hide`
```
Navigation.waitForProtectedRoutes().then(() => {
    const route = ReportUtils.getRouteFromLink(url);

    if (route && Session.isAnonymousUser() && !Session.canAnonymousUserAccessRoute(route)) {
        Session.signOutAndRedirectToSignIn(true);
        return;
    }

    // We don't want to navigate to the exitTo route when creating a new workspace from a deep link,
    // because we already handle creating the optimistic policy and navigating to it in App.setUpPoliciesAndNavigate,
    // which is already called when AuthScreens mounts.
    if (new URL(url).searchParams.get('exitTo') === ROUTES.WORKSPACE_NEW) {
        return;
    }

    if (shouldSkipDeepLinkNavigation(route)) {
        return;
    }

    Navigation.navigate(route as Route, CONST.NAVIGATION.ACTION_TYPE.PUSH);
}).finally(BootSplash.hide);
```
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-03-21 10:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The loading spinner is not shown when a public room is accessed anonymously for the first time
### What is the root cause of that problem?
The `SplashScreenHider` component calls `BootSplash.hide()` when rendering. [Here](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L251C13-L251C78) we hide the `SplashScreenHider` depended `shouldHideSplash` which is `true` as long as the opening of public room is in progress. ( Look at [these](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L115C1-L116C60) lines  ant notice that the `hasAttemptedToOpenPublicRoom` is updated in the above [useEffect](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L98C1-L103C32) with `isCheckingPublicRoom` in deeps ). 

But `isCheckingPublicRoom` will be set to `false` until the process of opening the public room is completed in [here](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2211C1-L2213C10) which causes `hasAttemptedToOpenPublicRoom` to be set to  `true` ahead of time

### What changes do you think we should make in order to solve the problem?
Remove [this](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2210C1-L2213C10) part of code.  it will always be set to `false`  in [openReport](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L727C13-L727C63) 

### What alternative solutions did you explore? (Optional)
1. Update [this](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L251C13-L251C78) line like below
```
{!initialUrl && shouldHideSplash && <SplashScreenHider onHide={onSplashHide} />}
```
2. Add finally method for [Navigation.waitForProtectedRoutes](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2221C1-L2243C11) which will call `BootSplash.hide`
```
Navigation.waitForProtectedRoutes().then(() => {
    const route = ReportUtils.getRouteFromLink(url);

    if (route && Session.isAnonymousUser() && !Session.canAnonymousUserAccessRoute(route)) {
        Session.signOutAndRedirectToSignIn(true);
        return;
    }

    // We don't want to navigate to the exitTo route when creating a new workspace from a deep link,
    // because we already handle creating the optimistic policy and navigating to it in App.setUpPoliciesAndNavigate,
    // which is already called when AuthScreens mounts.
    if (new URL(url).searchParams.get('exitTo') === ROUTES.WORKSPACE_NEW) {
        return;
    }

    if (shouldSkipDeepLinkNavigation(route)) {
        return;
    }

    Navigation.navigate(route as Route, CONST.NAVIGATION.ACTION_TYPE.PUSH);
}).finally(BootSplash.hide);
```

**Comment by shahinyan11** [comment] 2024-03-21 10:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The loading spinner is not shown when a public room is accessed anonymously for the first time
### What is the root cause of that problem?
The `SplashScreenHider` component calls `BootSplash.hide()` when rendering. [Here](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L251C13-L251C78) we hide the `SplashScreenHider` depended `shouldHideSplash` which is `true` as long as the opening of public room is in progress. ( Look at [these](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L115C1-L116C60) lines  ant notice that the `hasAttemptedToOpenPublicRoom` is updated in the above [useEffect](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L98C1-L103C32) with `isCheckingPublicRoom` in deeps ). 

But `isCheckingPublicRoom` will be set to `false` until the process of opening the public room is completed in [here](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2211C1-L2213C10) which causes `hasAttemptedToOpenPublicRoom` to be set to  `true` ahead of time

### What changes do you think we should make in order to solve the problem?
Remove [this](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2210C1-L2213C10) part of code. Since above we already call `openReport(reportID, '', [], {}, '0', true);` where the parameter `isFromDeepLink` is set `true`, Onyx.set(ONYXKEYS.IS_CHECKING_PUBLIC_ROOM, false) will always be called [here](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L727C13-L727C63).
### What alternative solutions did you explore? (Optional)
Set the default value of  `isOffline` in `ONYXKEYS.NETWORK` to `false`
### What alternative solutions did you explore? (Optional)
1. Update [this](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/Expensify.tsx#L251C13-L251C78) line like below
```
{!initialUrl && shouldHideSplash && <SplashScreenHider onHide={onSplashHide} />}
```
2. Add finally method for [Navigation.waitForProtectedRoutes](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2221C1-L2243C11) which will call `BootSplash.hide`
```
Navigation.waitForProtectedRoutes().then(() => {
    const route = ReportUtils.getRouteFromLink(url);

    if (route && Session.isAnonymousUser() && !Session.canAnonymousUserAccessRoute(route)) {
        Session.signOutAndRedirectToSignIn(true);
        return;
    }

    // We don't want to navigate to the exitTo route when creating a new workspace from a deep link,
    // because we already handle creating the optimistic policy and navigating to it in App.setUpPoliciesAndNavigate,
    // which is already called when AuthScreens mounts.
    if (new URL(url).searchParams.get('exitTo') === ROUTES.WORKSPACE_NEW) {
        return;
    }

    if (shouldSkipDeepLinkNavigation(route)) {
        return;
    }

    Navigation.navigate(route as Route, CONST.NAVIGATION.ACTION_TYPE.PUSH);
}).finally(BootSplash.hide);
```

**Comment by shahinyan11** [comment] 2024-03-25 16:52
@adelekennedy The issue is still reproducible, why was it closed as completed?

**Comment by shahinyan11** [comment] 2024-04-03 13:51
@adelekennedy Can you clarify ?

**Comment by marcochavezf** [comment] 2024-04-28 23:33
I'm going to re-open since it's impacting the experience for new users in our existing public rooms

**Comment by marcochavezf** [comment] 2024-04-28 23:34
Hi @rushatgabhane, could you evaluate @shahinyan11's proposal when you have a chance?

**Comment by marcochavezf** [comment] 2024-04-29 00:48
> And [here](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/actions/Report.ts#L2211C1-L2213C10) isNetworkOffline is true because the callback of [NetInfo.addEventListener](https://github.com/Expensify/App/blob/82065804528dc66daaa6ba652ab2dea84684c619/src/libs/NetworkConnection.ts#L103C30-L110C6) is called multiple times and state.isInternetReachable is null during the first few calls

@shahinyan11 Oh, interesting, this ^ seems to be the main reason why we show the sign-in page first. If we remove the code as proposed, what would happen if the user tries to load the public room in offline mode? Will the splash screen be loading indefinitely until there's a response from the server?

**Comment by quinthar** [comment] 2024-04-29 04:06
@rushatgabhane this suddenly became very, very important.  We are sending out a newsletter *tomorrow* that will have a link to a public room, and this bug will happen for everyone who click it.  Can we fix this *immediately*?  Thanks!

**Comment by quinthar** [comment] 2024-04-29 04:10
Thank you!!

**Comment by rushatgabhane** [comment] 2024-04-29 04:10
https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1714363843546369

**Comment by DylanDylann** [comment] 2024-04-29 04:11
I can take over this one

**Comment by quinthar** [comment] 2024-04-29 04:22
Great!!  @DylanDylann what is your ETA?

**Comment by DylanDylann** [comment] 2024-04-29 04:24
I am reviewing @shahinyan11's [proposal](https://github.com/Expensify/App/issues/38718#issuecomment-2011900339). I will give an update in an hour

**Comment by DylanDylann** [comment] 2024-04-29 05:40
@shahinyan11 Could you recheck your proposal? It has been a long time since the proposal was created and it doesn't seem to work at the moment. Still evaluating alternative solutions

**Comment by shahinyan11** [comment] 2024-04-29 16:44
> @shahinyan11 Could you recheck your proposal? It has been a long time since the proposal was created and it doesn't seem to work at the moment. Still evaluating alternative solutions

Certainly. I will give an update asap

**Comment by DylanDylann** [comment] 2024-04-29 17:54
@shahinyan11 It seems https://github.com/Expensify/App/pull/39595 will fix this issue

**Comment by shahinyan11** [comment] 2024-04-29 19:06
> @shahinyan11 It seems #39595 will fix this issue

@DylanDylann Yes, it's fixed now. But I want to say that my main solution works and solution https://github.com/Expensify/App/pull/39595 very close to my main solution. And I think that my solution is cleaner and does not require a lot of code.

**Comment by marcochavezf** [comment] 2024-05-01 18:53
Sounds good, closing it

**Closed by marcochavezf** 2024-05-01 18:53 UTC
Labels: External, Daily, Bug
