### ISSUE TITLE
[$250] Chat - Fub menu has only 3 option and Workspace is missing when log in with specific account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11061] opened 2022-09-16 15:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with account applausetester+0901abb@applause.expensifail.com/Feya86Katya
3. Click on Fub menu
4. Or go to Settings and check Workspace 

Additional steps 
- Open the private browser window.
- Now log in with account. (applausetester+0901abb@applause.expensifail.com/Feya86Katya)
- Go to the settings page.
- No workspaces. <== issue.
- Now refresh the page.
- Workspaces are back on the setting page.

## Expected Result:
Fub menu has all options and Workspace is displayed under Settings when log in with specific account

## Actual Result:
Fub menu has only 3 options and Workspace is missing when log in with specific account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190674439-2b5ee2f2-3b6a-4f07-a681-e764ca505352.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team\

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment] 2022-09-16 15:39
Can you include JS console errors, especially before/during the blank RHN?
Also, not clear, is this user an admin of a workspace? I don't get why you expect to see a workspace in the RHN otherwise

**Comment by iwiznia** [comment] 2022-09-21 10:36
Bump on the question above @kbecciv

**Comment by kbecciv** [comment] 2022-09-21 13:20
@iwiznia Updating you shortly

**Comment by kbecciv** [comment] 2022-09-21 13:28
@iwiznia This is currently behavior for account -applausetester+0901abb@applause.expensifail.com/FEya86Katya, tested on build 1.2.3.0.

https://user-images.githubusercontent.com/93399543/191516538-ee6d493a-7056-4041-bf2b-d9a1dbe4aaef.mp4

**Comment by sketchydroide** [comment] 2022-09-26 13:14
not overdue we are waiting on takers, @arielgreen should we bump up the price?

**Comment by arielgreen** [comment] 2022-09-29 00:32
https://www.upwork.com/jobs/~010b3563aad316549f

**Comment by mvtglobally** [comment] 2022-10-03 20:18
Issue not reproducible during KI retests. (First week)

**Comment by sketchydroide** [comment] 2022-10-04 12:20
Thanks @mvtglobally.
@arielgreen if we have no takers, we might be able to close it if QA continues to no reproduce it.

**Comment by arielgreen** [comment] 2022-10-05 05:07
@sketchydroide cool, maybe I'll give it a week and close it out.

**Comment by mvtglobally** [comment] 2022-10-11 13:00
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-10-17 18:57
Team is still not able to repro unfortunately. Not sure of this is maybe device specific issue ? 

https://user-images.githubusercontent.com/43995119/196259625-71ed2d9f-4da4-4539-8851-5fdd74e2507d.mp4

**Comment by parasharrajat** [comment] 2022-10-17 19:29
Seems to be working fine for me now too.

**Comment by mvtglobally** [comment] 2022-10-18 11:21
Issue not reproducible during KI retests. (Third week)

**Comment by arielgreen** [comment] 2022-10-18 15:49
Closing.

**Closed by arielgreen** 2022-10-18 15:49 UTC
Labels: External, Engineering, Weekly, Help Wanted
