### ISSUE TITLE
[Hold for payment 2022-12-06] [$250] `Terms of Service` link has to be clicked twice to open in bank account setup page reported by @mdneyazahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12715] opened 2022-11-14 18:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action performed:

1. Visit https://staging.new.expensify.com/bank-account/BankAccountStep
2. Click on routing number field
3. Click on Expensify Terms of Service

## Expected result: 
It should open the link on the first click

## Actual result: 
It takes two click to open the link

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-3

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201736605-2bd20e91-f4a7-427c-bd63-9c03c998ad84.mp4

https://user-images.githubusercontent.com/43996225/201736622-f6ea197a-aa49-4c92-8a8b-e6845436a080.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668425665585219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2022-11-14 21:01
Aaaah, I had a hard time reproducing this one but got to it in the end. The trick is you have to have a completely blank bank setup before trying to test. 

In this case, I was able to reproduce it after clearing out the info that was already there. If anything is in the fields, the link works the first time. This makes me believe the error (of not having a routing number) is taking precedence over the TOS click or that when clicking the TOS link, we're trying to validate the fields unnecessarily.

**My steps to reproduce:**

1. Visit https://staging.new.expensify.com/bank-account/BankAccountStep,
2. If you have a partial setup and numbers in the account or routing fields, delete them, close the setup, and then open it up again so it's blank,
3. Click on routing number field,
4. Click on Expensify Terms of Service,

I'll add the External label and make a job for it.

**Comment by strepanier03** [comment] 2022-11-14 21:07
Internal job post: https://www.upwork.com/ab/applicants/1592262964342812672/suggested

----

External job post: https://www.upwork.com/jobs/~0199da084980259e9d

**Comment by strepanier03** [comment] 2022-11-14 21:11
@mdneyazahmad - As the issue reporter, feel free to apply for the [job](https://www.upwork.com/jobs/~0199da084980259e9d) and share your Upwork profile with me so I can hire you for reporting.

**Comment by Delgee** [comment] 2022-11-14 23:17
### Proposal

### Root cause
In the form component, input is validated on 'blur' event and error text is added on the bottom of the element which changes the link's position before the mouse clicks release. So link click is not counted.
### Solution
Validating input on 'blur' event and adding error text bottom of input both of them are correct logic. I think changing these logic or jumping to the link on mouse press is the wrong way to fix this issue. So the simplest way to fix this is just moving checkbox to the bottom.

https://user-images.githubusercontent.com/6459339/201786560-bac47618-7a6e-4bfd-93bf-5652d6addd21.mov

**Comment by fedirjh** [comment] 2022-11-14 23:27
This is a regression from #12513

**Comment by peterklamka** [comment] 2022-11-14 23:57
### Proposal
### Root cause
Agree with @Delgee

### Solution
https://stackoverflow.com/questions/17769005/onclick-and-onblur-ordering-issue
Because OnMouseDown Event will be triggerred earlier than onBlur, we added onMouseDown event on TextLink component .



https://user-images.githubusercontent.com/118206313/201792619-9ae2311c-3acc-46b2-830c-991e649bc080.mp4

**Comment by mollfpr** [comment] 2022-11-15 05:52
Thank you guys, I'll review the proposal today!

**Comment by Puneet-here** [comment] 2022-11-15 07:18
I think we should do nothing because we will be moving away from the validation at onBlur event after the `Form` refactors, so the issue will be resolved. Discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1659440463665489).

**Comment by mollfpr** [comment] 2022-11-15 07:30
>we will be moving away from the validation at onBlur event

Thanks for the info @Puneet-here! I do not see any detail on what the `Form` refactor will look like in the thread, so I'm not a hundred percent sure about what you say.

I'll circle back to the team and get some thoughts about it.

cc @Gonals @strepanier03

**Comment by peterklamka** [comment] 2022-11-15 12:14
@mollfpr so my solution is not acceptable?

**Comment by mollfpr** [comment] 2022-11-15 15:03
@peterklamka Your proposal still valid.

**Comment by strepanier03** [comment] 2022-11-16 03:10
I'll hold on hiring anyone until we have confirming that we're going to fix this and that the proposal is officially being accepted. Will check tomorrow.

**Comment by mollfpr** [comment] 2022-11-17 15:15
@strepanier03 We can continue to receive proposals now, we don't have a plan to remove the `onBlur` validation in the refactor form.

@Delgee Can you provide the code for solution 2?

@peterklamka I don't think using `onMouseDown` is a great idea, I feel lost click feeling with `onMouseDown`. Do you have any solution?

**Comment by strepanier03** [comment] 2022-11-18 01:03
Great, thank you for the heads up @mollfpr. I'll continue to follow along and when we're ready to hire I'll be here to take the next steps. If I can help with anything else, just let me know.

**Comment by mollfpr** [comment] 2022-11-18 10:12
Thanks @Delgee, Is using Pressable will render as anchor tag on the web?

**Comment by Delgee** [comment] 2022-11-18 10:14
Yes it will.

**Comment by mollfpr** [comment] 2022-11-18 16:19
@Delgee We can't replace the `Text` with `Pressable` it will crash the native app. Mostly our `TextLink` usage with localized text children.

**Comment by Emz27** [comment] 2022-11-18 22:09
### Proposal
- use Text `onResponderRelease` as alternative to onPress (similar behavior but not the same) paired with `onStartShouldSetResponderCapture` to prevent the touchable container from hogging the TouchEvent.

### Cause
- the onPress did not trigger because the mouse cursor is already outside the touch box boundary by the time the user release the mouse click

### Impact
- once the user clicks it and release, it will surely trigger onPress regardless of the cursor position

```diff
diff --git a/src/components/TextLink.js b/src/components/TextLink.js
index 55344d987..40c0bf721 100644
--- a/src/components/TextLink.js
+++ b/src/components/TextLink.js
@@ -22,9 +22,12 @@ const propTypes = {
 
     /** Overwrites the default link behavior with a custom callback */
     onPress: PropTypes.func,
+
+    isRedirectOnTouchRelease: PropTypes.bool,
 };
 
 const defaultProps = {
+    isRedirectOnTouchRelease: false,
     href: '',
     style: [],
     onPress: undefined,
@@ -61,7 +64,13 @@ const TextLink = (props) => {
             style={[styles.link, ...additionalStyles]}
             accessibilityRole="link"
             href={props.href}
-            onPress={openLink}
+            // eslint-disable-next-line react/jsx-props-no-spreading
+            {...(props.isRedirectOnTouchRelease ? {
+                onResponderRelease: openLink,
+                onStartShouldSetResponderCapture: () => true,
+            } : {
+                onPress: openLink,
+            })}
             onKeyDown={openLinkIfEnterKeyPressed}
         >
             {props.children}
diff --git a/src/pages/ReimbursementAccount/BankAccountManualStep.js b/src/pages/ReimbursementAccount/BankAccountManualStep.js
index c42b0f718..7d23eabd2 100644
--- a/src/pages/ReimbursementAccount/BankAccountManualStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountManualStep.js
@@ -119,7 +119,7 @@ class BankAccountManualStep extends React.Component {
                                 <Text>
                                     {this.props.translate('common.iAcceptThe')}
                                 </Text>
-                                <TextLink href="https://use.expensify.com/terms">
+                                <TextLink href="https://use.expensify.com/terms" isRedirectOnTouchRelease>
                                     {`Expensify ${this.props.translate('common.termsOfService')}`}
                                 </TextLink>
                             </View>
                             ```
I added additional prop `isRedirectOnTouchRelease` because this is an edge case, probably wont happen on most cases and the TextLink was reused a lot of times so this is also to prevent regression on other components that uses this

**Comment by Emz27** [comment] 2022-11-18 22:19
https://user-images.githubusercontent.com/26669757/202812490-da6d3c7f-444a-4225-a643-4c64b9108320.mov

**Comment by Delgee** [comment] 2022-11-19 04:40
@mollfpr  We can change it this way to make it won't crash on native apps. It will also work okay on the browser.
```javascript
return (
        <Pressable
            onPressIn={openLink}
            onKeyDown={openLinkIfEnterKeyPressed}
        >
            <Text
                style={[styles.link, ...additionalStyles]}
                accessibilityRole="link"
                href={props.href}
            >
                {props.children}
            </Text>
        </Pressable>
    );
```

**Comment by mollfpr** [comment] 2022-11-20 15:41
Sorry for the wait! I just try the above proposals, and here are my thoughts.

@Emz27 Your proposal works on the first try, but on the second try, the link is open in the current tab and new tab.

https://user-images.githubusercontent.com/25520267/202910364-7e574c27-7873-432a-a774-1911304825e5.mov

@Delgee I feel your proposal impacted the native app. As you can see in the video, on native there's a highlight when clicking the link. We should not change that. Also, the behavior is similar to `onMouseDown`.

**With your proposal**

https://user-images.githubusercontent.com/25520267/202910981-808f8020-3a16-40dd-8763-c680ed84cecf.mov

**Current behavior**

https://user-images.githubusercontent.com/25520267/202911135-a1f8732c-3572-40c2-9843-94203dde1374.mov

**Comment by Delgee** [comment] 2022-11-20 16:24
@mollfpr 
### Updated Proposal
We can fix this issue by preventing the "mousedown" event. So blur event will not fire and the link will work as expected on both web and native devices. And preventing "mousedown" event will not cause any issue.

```diff
--- a/src/components/TextLink.js
+++ b/src/components/TextLink.js
@@ -22,12 +22,14 @@ const propTypes = {

     /** Overwrites the default link behavior with a custom callback */
     onPress: PropTypes.func,
+    shouldPreventMouseDownEvent: PropTypes.bool,
 };

 const defaultProps = {
     href: '',
     style: [],
     onPress: undefined,
+    shouldPreventMouseDownEvent: false,
 };

 const TextLink = (props) => {
@@ -61,6 +63,7 @@ const TextLink = (props) => {
             style={[styles.link, ...additionalStyles]}
             accessibilityRole="link"
             href={props.href}
+            onMouseDown={props.shouldPreventMouseDownEvent ? e => e.preventDefault() : undefined}
             onPress={openLink}
             onKeyDown={openLinkIfEnterKeyPressed}
         >

--- a/src/pages/ReimbursementAccount/BankAccountManualStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountManualStep.js
@@ -116,7 +116,7 @@ class BankAccountManualStep extends React.Component {
                                 <Text>
                                     {this.props.translate('common.iAcceptThe')}
                                 </Text>
-                                <TextLink href="https://use.expensify.com/terms">
+                                <TextLink href="https://use.expensify.com/terms" shouldPreventMouseDownEvent>
                                     {`Expensify ${this.props.translate('common.termsOfService')}`}
                                 </TextLink>
                             </View>
```

web 

https://user-images.githubusercontent.com/6459339/202913478-2413ff85-82ae-465d-8f60-6f6e3f48cc75.mov

native

https://user-images.githubusercontent.com/6459339/202913490-a2ba96f6-89e5-40ec-b433-9fe12b250677.mov

**Comment by Emz27** [comment] 2022-11-20 16:25
@mollfpr I have added 2 additional props
`onPress` and `hrefAttrs`

this should work as expected now

```diff
diff --git a/src/components/TextLink.js b/src/components/TextLink.js
index 55344d987..7221f0561 100644
--- a/src/components/TextLink.js
+++ b/src/components/TextLink.js
@@ -22,9 +22,12 @@ const propTypes = {
 
     /** Overwrites the default link behavior with a custom callback */
     onPress: PropTypes.func,
+
+    isRedirectOnTouchRelease: PropTypes.bool,
 };
 
 const defaultProps = {
+    isRedirectOnTouchRelease: false,
     href: '',
     style: [],
     onPress: undefined,
@@ -60,8 +63,18 @@ const TextLink = (props) => {
         <Text
             style={[styles.link, ...additionalStyles]}
             accessibilityRole="link"
+
             href={props.href}
-            onPress={openLink}
+            // eslint-disable-next-line react/jsx-props-no-spreading
+            {...(props.isRedirectOnTouchRelease ? {
+                hrefAttrs: {target: '_blank'},
+                onPress: (e) => { e.preventDefault(); },
+                onResponderRelease: openLink,
+                onStartShouldSetResponderCapture: () => true,
+            } : {
+                onPress: openLink,
+            })}
+
             onKeyDown={openLinkIfEnterKeyPressed}
         >
             {props.children}
diff --git a/src/pages/ReimbursementAccount/BankAccountManualStep.js b/src/pages/ReimbursementAccount/BankAccountManualStep.js
index c42b0f718..7d23eabd2 100644
--- a/src/pages/ReimbursementAccount/BankAccountManualStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountManualStep.js
@@ -119,7 +119,7 @@ class BankAccountManualStep extends React.Component {
                                 <Text>
                                     {this.props.translate('common.iAcceptThe')}
                                 </Text>
-                                <TextLink href="https://use.expensify.com/terms">
+                                <TextLink href="https://use.expensify.com/terms" isRedirectOnTouchRelease>
                                     {`Expensify ${this.props.translate('common.termsOfService')}`}
                                 </TextLink>
                             </View>
```

**Comment by Emz27** [comment] 2022-11-20 16:42
https://user-images.githubusercontent.com/26669757/202914401-bcfa0f70-a18c-4b0c-834e-ebf9fc185737.mov

https://user-images.githubusercontent.com/26669757/202914417-6201f9aa-fda4-4078-9cde-531e1ce1418f.mov

**Comment by mollfpr** [comment] 2022-11-21 05:05
Thank y'all for the proposals!

I like @Delgee [proposal](https://github.com/Expensify/App/issues/12715#issuecomment-1321173742) here, it's simple and works well on the web, mWeb, and desktop, and nothing changes on native.

🎀 👀 🎀  C+ reviewed

@Gonals

**Comment by mollfpr** [comment] 2022-11-21 07:20
@Delgee I think it's better if we add the `onMouseDown` prop to `TextLink` and call `e => e.preventDefault()` on `BankAccountManualStep` component.

cc @Gonals

**Comment by Delgee** [comment] 2022-11-21 07:35
Yes, I think that's a better way. Since this issue is unique to ```BankAccountManualStep``` component.

**Comment by strepanier03** [comment] 2022-11-22 04:21
@Gonals - Just a little nudge for the proposal by @Delgee [here](https://github.com/Expensify/App/issues/12715#issuecomment-1321173742) which has been selected by @mollfpr and is ready for your review.

**Comment by Gonals** [comment] 2022-11-22 10:57
Proposal looks good to me overall! Having the `onMouseDown` prop in `TextLink` makes sense to me too 👍

**Comment by mollfpr** [comment] 2022-11-22 11:06
Thanks, @Gonals! Let’s assigned it to @Delgee.

**Comment by joelbettner** [comment] 2022-11-22 16:49
I'm going to jump on this for urgency of our bug squashing campaign.

**Comment by mollfpr** [comment] 2022-11-22 17:29
@Delgee Yes, please.

**Comment by joelbettner** [comment] 2022-11-22 18:59
I will not work on it, then.

**Comment by mollfpr** [comment] 2022-11-23 03:57
@strepanier03 Applied!

**Comment by strepanier03** [comment] 2022-11-28 23:22
PR is on staging. Will continue following along as it progresses through QA and production merge.

**Comment by strepanier03** [comment] 2022-11-30 01:21
On staging still. Will check tomorrow.

**Comment by strepanier03** [comment] 2022-12-02 01:39
Still on staging.

----

I am OoO for jury duty tomorrow. If immediate action is needed on this GH please post in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) for assistance, thank you.

**Comment by mollfpr** [comment] 2022-12-02 02:25
The PR is already in production since six days ago, but Melvin misses that 🤷‍♂️

https://github.com/Expensify/App/releases/tag/1.2.31-8

---

Btw I think we are eligible for a 50% bonus since the PR got merged within two days after being assigned.

cc @strepanier03 @Gonals

**Comment by strepanier03** [comment] 2022-12-07 00:50
Sorry about the issues with the GH update everyone. I'm taking care of this now.

**Comment by strepanier03** [comment] 2022-12-07 01:06
BugZero checklist:

- [x] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the updated test here: Not making a TR for this edge case.
- [ ] The PR that introduced the bug has been identified. Link to the PR: @mollfpr this is your action item
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:@mollfpr this is your action item
- [ ] A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: @mollfpr this is your action item
- [x] Pay @Delgee $250+$125 bonus
- [ ] Pay @mollfpr $250+$125 bonus
- [x] Pay @mdneyazahmad $250

**Comment by strepanier03** [comment] 2022-12-07 01:07
@mollfpr I have accepted the application, sorry I thought I'd already done that. I'll check back in to pay you out as well.

**Comment by strepanier03** [comment] 2022-12-07 22:31
All BZ checklist items are complete and all parties have been paid as well. Going to close this one out, please reopen as needed and ping me if I missed something.

**Closed by strepanier03** 2022-12-07 22:31 UTC
Labels: External, Daily, Bug
