### ISSUE TITLE
[$500] Connect manually step show up when going back from the middle of the flow - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11317] opened 2022-09-27 04:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to bank account > add info > company step > personal details
2. Dismiss the modal by pressing cross
3. Now go to workspace > "connect bank account" > continue with the setup
4. Now keep going back

## Expected Result:
Connect manually step shouldn't be shown because we have already filled the info and we have option to start over or continue

## Actual Result:
Connect manually step show up and

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192430195-b4e130ce-604e-4242-8f1a-0e7a5c08751c.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662750200732219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2022-09-27 15:31
The workflow update is to show the Continue with Setup instead of showing the add manually option. Assigning to engineering for the next review.

**Comment by dangrous** [comment] 2022-09-28 00:00
Yep, this is pretty easily reproducible. i THINK this should be fully front end so I'm going to make it external; weekly because it's not a huge deal.

**Comment by adelekennedy** [comment] 2022-09-29 23:55
[internal](https://www.upwork.com/ab/applicants/1575635248817942528/job-details)
[external](https://www.upwork.com/jobs/~01cee89cc834ace277)

**Comment by adelekennedy** [comment] 2022-10-04 20:12
Still waiting for proposals!

**Comment by dangrous** [comment] 2022-10-06 23:41
I _believe_ this will actually be fixed by [https://github.com/Expensify/App/pull/11039 which includes ](https://github.com/Expensify/App/pull/11457) once that is completed and merged (so I'm not sure we need this externally). @marcochavezf can you confirm when you have a moment?

**Comment by tienifr** [comment] 2022-10-07 08:45
# Proposal

## Problem
When we change the text in rate input, the below function is executed. And if the user enters more than 8 character, it's not valid so `isInvalidRateValue` === true and it will update the old value again
in /App/src/pages/workspace/reimburse/WorkspaceReimburseView.js
```diff

setRate(value) {
        const decimalSeparator = this.props.toLocaleDigit('.');
        const rateValueRegex = RegExp(String.raw`^\d{1,8}([${getPermittedDecimalSeparator(decimalSeparator)}]\d{0,3})?$`, 'i');
        const isInvalidRateValue = value !== '' && !rateValueRegex.test(value);
        this.setState(prevState => ({
            unitRateValue: !isInvalidRateValue ? this.getRateDisplayValue(value) : prevState.unitRateValue,
        }), () => {
            // Set the corrected value with a delay and sync to the server
            this.updateRateValueDebounced(this.state.unitRateValue);
        });
    }
```

## Solution
We should add maxLength in TextInput component to prevent users from entering more than 8 characters
in /App/src/pages/workspace/reimburse/WorkspaceReimburseView.js
```diff
<TextInput
                                        label={this.props.translate('workspace.reimburse.trackDistanceRate')}
                                        placeholder={this.state.outputCurrency}
                                        onChangeText={value => this.setRate(value)}
                                        value={this.state.unitRateValue}
                                        autoCompleteType="off"
                                        autoCorrect={false}
                                        keyboardType={CONST.KEYBOARD_TYPE.DECIMAL_PAD}
                                        onKeyPress={this.debounceUpdateOnCursorMove}
+                                      maxLength={CONST.MAX_LENGTH_IN_RATE_INPUT}
/>
```
and in /App/src/CONST.js
```diff
+                                          MAX_LENGTH_IN_RATE_INPUT: 8,
```
Result: 

https://user-images.githubusercontent.com/113963320/194510919-7f456edf-c742-4d74-8112-54525589e19b.mov

**Comment by tienifr** [comment] 2022-10-07 08:56
@rushatgabhane Thanks for pointing that out, I just have updated the proposal to match [the correct issue](https://github.com/Expensify/App/issues/11352#issuecomment-1271312219)

**Comment by adelekennedy** [comment] 2022-10-10 15:31
@dangrous & @rushatgabhane are we [pending closing this](https://github.com/Expensify/App/issues/11317#issuecomment-1270846246)?

**Comment by dangrous** [comment] 2022-10-10 17:45
> @dangrous & @rushatgabhane are we [pending closing this](https://github.com/Expensify/App/issues/11317#issuecomment-1270846246)?

Yeah I think we can close - it's merged now but not yet on prod; however I don't think there's any reason not to close this now since we're not going to accept a proposal in the meantime.

**Closed** 2022-10-12 21:18 UTC
Labels: External, Engineering, Daily, Help Wanted

**Comment by Puneet-here** [comment] 2022-10-13 06:52
This is still reproducible at latest development build.

**Comment by dangrous** [comment] 2022-10-13 20:43
Hm, I'm seeing that too - okay, maybe we reopen? Looking again at the testing for the issue I thought was the same (see `Additionally, test the steps for this regression that reverted the original PR.` section of [this PR](https://github.com/Expensify/App/pull/11457) I guess it is slightly different. Apologies for that, maybe we should reopen?

**Comment by marcochavezf** [comment] 2022-10-18 21:43
Ah I think this is a different issue, and probably requires some discussion. 

In the PR we're navigating from the Workspace menu to Connect bank account, where in that case we show the page with the buttons `Continue with setup` and `Start over` which is correct. But here we're navigating back from step 1 to the page `Streamlined payments` when we should navigate directly to the page with the buttons `Continue with setup` and `Start over`. Is that correct @Puneet-here @mvtglobally?

**Comment by Puneet-here** [comment] 2022-10-18 21:49
Yes, correct 💯

**Comment by Puneet-here** [comment] 2022-11-23 13:01
@marcochavezf can we re-open?

**Comment by trjExpensify** [comment] 2022-11-23 15:10
Coming [from here](https://expensify.slack.com/archives/C049HHMV9SM/p1669215019745509?thread_ts=1669176630.046939&cid=C049HHMV9SM), let's reopen and fix this. 

@dangrous, in the future, let's make sure to re-test when an associated issue might fix another to confirm it does. While we wait, we can always pop a `[Hold #issueNumber]` in the title until then.

**Comment by hungvu193** [comment] 2022-11-23 15:39
<b> Proposal</b>
Since the `ContinueBankAccountSetup` (which contain StartOver and Continue with setup) is depended on the `shouldShowContinueSetupButton`, when press the `Continue` button this state is set to false but when goBack from other screen like `BankAccountManualStep` `BankAccountPlaidStep` this state isn't updated, that's why this issued happened.

<b>Solution</b>
Move `shouldShowContinueSetupButton` to Onyx, so we can update this state from anywhere like goBack from `BankAccountManualStep`.
Update this state when go back from `BankAccountManualStep` or `BankAccountPlaidStep` and when user confirm `Start Over`.

```diff
diff --git a/src/libs/actions/ReimbursementAccount/index.js b/src/libs/actions/ReimbursementAccount/index.js
index 40dc5835a..9758aeca3 100644
--- a/src/libs/actions/ReimbursementAccount/index.js
+++ b/src/libs/actions/ReimbursementAccount/index.js
@@ -20,6 +20,15 @@ function setBankAccountSubStep(subStep) {
     Onyx.merge(ONYXKEYS.REIMBURSEMENT_ACCOUNT, {achData: {subStep}});
 }
 
+/**
+ * Set the current sub step in first step of adding withdrawal bank account
+ *
+ * @param {String} shouldShowContinueSetupButton - One of {CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL, CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID, null}
+ */
+function setShowContinueButton(shouldShowContinueSetupButton) {
+    Onyx.merge(ONYXKEYS.REIMBURSEMENT_ACCOUNT, {shouldShowContinueSetupButton});
+}
+
 function hideBankAccountErrors() {
     Onyx.merge(ONYXKEYS.REIMBURSEMENT_ACCOUNT, {error: '', errors: null});
 }
@@ -58,4 +67,5 @@ export {
     requestResetFreePlanBankAccount,
     cancelResetFreePlanBankAccount,
     deleteFromBankAccountList,
+    setShowContinueButton,
 };
diff --git a/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js b/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
index 24a7919fe..8d88dfc0a 100644
--- a/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
+++ b/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js
@@ -43,6 +43,7 @@ function resetFreePlanBankAccount() {
                     value: {
                         achData: {},
                         shouldShowResetModal: false,
+                        shouldShowContinueSetupButton: false,
                     },
                 },
                 {
diff --git a/src/pages/ReimbursementAccount/BankAccountManualStep.js b/src/pages/ReimbursementAccount/BankAccountManualStep.js
index c42b0f718..007c578a2 100644
--- a/src/pages/ReimbursementAccount/BankAccountManualStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountManualStep.js
@@ -1,6 +1,7 @@
 import React from 'react';
 import {Image, View} from 'react-native';
 import {withOnyx} from 'react-native-onyx';
+import lodashGet from 'lodash/get';
 import HeaderWithCloseButton from '../../components/HeaderWithCloseButton';
 import CONST from '../../CONST';
 import * as BankAccounts from '../../libs/actions/BankAccounts';
@@ -18,6 +19,8 @@ import exampleCheckImage from './exampleCheckImage';
 import Form from '../../components/Form';
 import * as ReimbursementAccountUtils from '../../libs/ReimbursementAccountUtils';
 import shouldDelayFocus from '../../libs/shouldDelayFocus';
+import BankAccount from '../../libs/models/BankAccount';
+import {setShowContinueButton} from '../../libs/actions/ReimbursementAccount';
 
 const propTypes = {
     ...withLocalizePropTypes,
@@ -65,6 +68,12 @@ class BankAccountManualStep extends React.Component {
 
     render() {
         const shouldDisableInputs = Boolean(ReimbursementAccountUtils.getDefaultStateForField(this.props, 'bankAccountID'));
+        const achData = lodashGet(
+            this.props,
+            'reimbursementAccount.achData',
+            {},
+        );
+        const hasInProgressVBBA = achData.bankAccountID && achData.state !== BankAccount.STATE.OPEN;
 
         return (
             <>
@@ -74,7 +83,13 @@ class BankAccountManualStep extends React.Component {
                     shouldShowGetAssistanceButton
                     guidesCallTaskID={CONST.GUIDES_CALL_TASK_IDS.WORKSPACE_BANK_ACCOUNT}
                     shouldShowBackButton
-                    onBackButtonPress={() => BankAccounts.setBankAccountSubStep(null)}
+                    onBackButtonPress={() => {
+                        if (hasInProgressVBBA) {
+                            setShowContinueButton(true);
+                        } else {
+                            BankAccounts.setBankAccountSubStep(null);
+                        }
+                    }}
                     onCloseButtonPress={Navigation.dismissModal}
                 />
                 <Form
diff --git a/src/pages/ReimbursementAccount/ReimbursementAccountPage.js b/src/pages/ReimbursementAccount/ReimbursementAccountPage.js
index d15c905e4..7375926db 100644
--- a/src/pages/ReimbursementAccount/ReimbursementAccountPage.js
+++ b/src/pages/ReimbursementAccount/ReimbursementAccountPage.js
@@ -33,6 +33,7 @@ import ROUTES from '../../ROUTES';
 import HeaderWithCloseButton from '../../components/HeaderWithCloseButton';
 import reimbursementAccountPropTypes from './reimbursementAccountPropTypes';
 import WorkspaceResetBankAccountModal from '../workspace/WorkspaceResetBankAccountModal';
+import {setShowContinueButton} from '../../libs/actions/ReimbursementAccount';
 
 const propTypes = {
     /** Plaid SDK token to use to initialize the widget */
@@ -65,6 +66,8 @@ const propTypes = {
 const defaultProps = {
     reimbursementAccount: {
         isLoading: true,
+        shouldShowContinueSetupButton: false,
+
     },
     plaidLinkToken: '',
     route: {
@@ -78,12 +81,6 @@ class ReimbursementAccountPage extends React.Component {
     constructor(props) {
         super(props);
         this.continue = this.continue.bind(this);
-
-        const achData = lodashGet(this.props, 'reimbursementAccount.achData', {});
-        const hasInProgressVBBA = achData.bankAccountID && achData.state !== BankAccount.STATE.OPEN;
-        this.state = {
-            shouldShowContinueSetupButton: hasInProgressVBBA,
-        };
     }
 
     componentDidMount() {
@@ -171,9 +168,7 @@ class ReimbursementAccountPage extends React.Component {
     }
 
     continue() {
-        this.setState({
-            shouldShowContinueSetupButton: false,
-        });
+        setShowContinueButton(false);
     }
 
     render() {
@@ -182,6 +177,7 @@ class ReimbursementAccountPage extends React.Component {
         // display. We can also specify a specific route to navigate to via route params when the component first
         // mounts which will set the achData.currentStep after the account data is fetched and overwrite the logical
         // next step.
+        const shouldShowContinueSetupButton = lodashGet(this.props, 'reimbursementAccount.shouldShowContinueSetupButton', false);
         const achData = lodashGet(this.props, 'reimbursementAccount.achData', {});
         const currentStep = achData.currentStep || CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT;
         if (this.props.reimbursementAccount.isLoading) {
@@ -198,12 +194,8 @@ class ReimbursementAccountPage extends React.Component {
         }
 
         const hasInProgressVBBA = achData.bankAccountID && achData.state !== BankAccount.STATE.OPEN;
-        if (hasInProgressVBBA && this.state.shouldShowContinueSetupButton) {
-            return (
-                <ContinueBankAccountSetup
-                    continue={this.continue}
-                />
-            );
+        if (hasInProgressVBBA && shouldShowContinueSetupButton) {
+            return <ContinueBankAccountSetup continue={this.continue} />;
         }
 
         let errorComponent;

```

**Comment by tjferriss** [comment] 2022-11-23 18:21
Following instructions for the [weekly update chore](https://stackoverflow.com/c/expensify/questions/8208):

@AndrewGable this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:

- Decide whether any proposals currently meet our guidelines and can be approved as-is
- For any that can't, please take this issue internal and treat it as one of your highest priorities
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by allroundexperts** [comment] 2022-11-24 21:42
## Proposal

For each of the sub step of the `BankAccountStep` (Manual connection or Plaid connection), we can expose the back button handler in the parent `ReimbursementAccountPage.js` file. As such, we just need following changes:

```
diff --git a/src/pages/ReimbursementAccount/BankAccountManualStep.js b/src/pages/ReimbursementAccount/BankAccountManualStep.js
index c42b0f718..63b716293 100644
--- a/src/pages/ReimbursementAccount/BankAccountManualStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountManualStep.js
@@ -1,6 +1,7 @@
 import React from 'react';
 import {Image, View} from 'react-native';
 import {withOnyx} from 'react-native-onyx';
+import PropTypes from 'prop-types';
 import HeaderWithCloseButton from '../../components/HeaderWithCloseButton';
 import CONST from '../../CONST';
 import * as BankAccounts from '../../libs/actions/BankAccounts';
@@ -20,6 +21,7 @@ import * as ReimbursementAccountUtils from '../../libs/ReimbursementAccountUtils
 import shouldDelayFocus from '../../libs/shouldDelayFocus';
 
 const propTypes = {
+    onBack: PropTypes.func,
     ...withLocalizePropTypes,
 };
 
@@ -74,7 +76,7 @@ class BankAccountManualStep extends React.Component {
                     shouldShowGetAssistanceButton
                     guidesCallTaskID={CONST.GUIDES_CALL_TASK_IDS.WORKSPACE_BANK_ACCOUNT}
                     shouldShowBackButton
-                    onBackButtonPress={() => BankAccounts.setBankAccountSubStep(null)}
+                    onBackButtonPress={this.props.onBack}
                     onCloseButtonPress={Navigation.dismissModal}
                 />
                 <Form
diff --git a/src/pages/ReimbursementAccount/BankAccountPlaidStep.js b/src/pages/ReimbursementAccount/BankAccountPlaidStep.js
index 603a360b7..9a7d48bb8 100644
--- a/src/pages/ReimbursementAccount/BankAccountPlaidStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountPlaidStep.js
@@ -23,6 +23,8 @@ const propTypes = {
     /** During the OAuth flow we need to use the plaidLink token that we initially connected with */
     plaidLinkOAuthToken: PropTypes.string,
 
+    onBack: PropTypes.func,
+
     ...withLocalizePropTypes,
 };
 
@@ -69,7 +71,7 @@ class BankAccountPlaidStep extends React.Component {
                     shouldShowGetAssistanceButton
                     guidesCallTaskID={CONST.GUIDES_CALL_TASK_IDS.WORKSPACE_BANK_ACCOUNT}
                     shouldShowBackButton
-                    onBackButtonPress={() => BankAccounts.setBankAccountSubStep(null)}
+                    onBackButtonPress={this.props.onBack}
                     onCloseButtonPress={Navigation.dismissModal}
                 />
                 <Form
diff --git a/src/pages/ReimbursementAccount/BankAccountStep.js b/src/pages/ReimbursementAccount/BankAccountStep.js
index 3a71ac53b..0c1fae525 100644
--- a/src/pages/ReimbursementAccount/BankAccountStep.js
+++ b/src/pages/ReimbursementAccount/BankAccountStep.js
@@ -38,6 +38,10 @@ const propTypes = {
     /** During the OAuth flow we need to use the plaidLink token that we initially connected with */
     plaidLinkOAuthToken: PropTypes.string,
 
+    /** Once the user has selected a sub step, clicking on back button should redirect to the continue button screen. */
+    /** As such, we need to expose this handler */
+    onSubStepBack: PropTypes.func, 
+
     /** The bank account currently in setup */
     /* eslint-disable-next-line react/no-unused-prop-types */
     reimbursementAccount: reimbursementAccountPropTypes,
@@ -57,6 +61,7 @@ const defaultProps = {
     plaidData: {
         isPlaidDisabled: false,
     },
+    onSubStepBack: () => {},
     reimbursementAccount: {},
     user: {},
 };
@@ -71,11 +76,11 @@ const BankAccountStep = (props) => {
     const bankAccountRoute = `${CONFIG.EXPENSIFY.NEW_EXPENSIFY_URL}${ROUTES.BANK_ACCOUNT}`;
 
     if (subStep === CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL) {
-        return <BankAccountManualStep />;
+        return <BankAccountManualStep onBack={props.onSubStepBack} />;
     }
 
     if (subStep === CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID) {
-        return <BankAccountPlaidStep />;
+        return <BankAccountPlaidStep onBack={props.onSubStepBack}/>;
     }
 
     return (
diff --git a/src/pages/ReimbursementAccount/ReimbursementAccountPage.js b/src/pages/ReimbursementAccount/ReimbursementAccountPage.js
index d15c905e4..9207dd92a 100644
--- a/src/pages/ReimbursementAccount/ReimbursementAccountPage.js
+++ b/src/pages/ReimbursementAccount/ReimbursementAccountPage.js
@@ -245,6 +245,7 @@ class ReimbursementAccountPage extends React.Component {
                     <BankAccountStep
                         receivedRedirectURI={getPlaidOAuthReceivedRedirectURI()}
                         plaidLinkOAuthToken={this.props.plaidLinkToken}
+                        onSubStepBack={() => hasInProgressVBBA ? this.setState({ shouldShowContinueSetupButton: true }): BankAccounts.setBankAccountSubStep(null)}
                     />
                 )}
                 {currentStep === CONST.BANK_ACCOUNT.STEP.COMPANY && (
```

### Result

https://user-images.githubusercontent.com/30054992/203866428-294c8c11-5af3-41a9-9007-f08763fccf30.mp4

**Comment by adelekennedy** [comment] 2022-11-29 00:33
@AndrewGable what do you think of @rushatgabhane recommendation above?

**Comment by AndrewGable** [comment] 2022-11-29 00:38
Looks good!

**Comment by allroundexperts** [comment] 2022-11-29 12:09
@AndrewGable I'm getting this:
<img width="1439" alt="Screenshot 2022-11-29 at 5 08 52 PM" src="https://user-images.githubusercontent.com/30054992/204525269-3b321373-f65a-48ca-9364-a58a72ce915b.png">

**Comment by allroundexperts** [comment] 2022-11-29 13:02
@AndrewGable https://github.com/Expensify/App/pull/13126

**Comment by allroundexperts** [comment] 2022-12-01 21:56
@AndrewGable @rushatgabhane is done with his review. Your review is pending :)

**Comment by AndrewGable** [comment] 2022-12-01 22:33
Merged 👍

**Comment by adelekennedy** [comment] 2022-12-01 23:41
Ah - I think the job expired (Upwork is the worst with that) @allroundexperts @rushatgabhane I just hired you for C/C+ @Puneet-here just hired for the reporting bonus!

@allroundexperts You are eligible for the bonus! I'll add that on!

**Comment by adelekennedy** [comment] 2022-12-03 00:08
Note when paying out - 50% bonus
