### ISSUE TITLE
[HOLD for payment 2023-08-07] [HOLD for payment 2023-08-03] Unread not working on the LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23446] opened 2023-07-23 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open 2 accounts on 2 browsers
2. Both account open the chat
3. B send any message
4. B click another report
5. A send the message, Observed in report B not marked as unread on LHN
## Expected Result:
 in report B marked as unread on LHN, when B does not open the report
## Actual Result:
 in report B not marked as unread on LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1115bad0-0cf6-449b-9a70-bb2a2419d3c1

https://github.com/Expensify/App/assets/43996225/cbdd3513-a9eb-4939-893a-96cf29b2888b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690006349415999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-24 09:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unread not working on the LHN.

### What is the root cause of that problem?
If user B received a message from user A, the following code is executed, and then calculate new marker actions.
If the scroll position is 0, then call `Report.readNewestAction` in order to update report's `lastReadTime`.
https://github.com/Expensify/App/blob/c779139a4faec6e0e1ed478f942b272b2c843221/src/pages/home/report/ReportActionsView.js#L129-L153

In this issue, user B already navigates to another report, but previous report view is not unmounted, and still receive push event.
So when receive new action, `Report.readNewestAction` is called, and `lastReadTime` is updated.
Therefore, previous report does not marked as unread in LHN.
### What changes do you think we should make in order to solve the problem?
We should check whether the report is visible, and if visible, then call `Report.readNewestAction`
```js
-   } else if (isReportFullyVisible) {
+   } else if (isReportFullyVisible && Navigation.getTopmostReportId() === props.report.reportID) {
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by stephanieelliott** [comment] 2023-07-24 21:00
Hey @kavimuru can you please clarify the on the repro steps? 

> 1. Open 2 accounts on 2 browsers
 -  I open Account A on Chrome, and Account B on Safari 
> 2. Both account open the chat
 - On Account A I navigate to chat with Account B, on Account B I navigate to chat with Account A
> 3. B send any message
 - On Account B I send a message to Account A 
> 4. B click another report
 - What does this mean -- on Account B should I be clicking into a chat with a separate user (Account X?) If no, what navigation steps should I be following? 
> 5. A send the message, Observed in report B not marked as unread on LHN
 - On Account A I send a message to Account B. Is the expectation that Account B sees this chat as `unread`?

**Comment by mountiny** [comment] 2023-07-27 11:39
This was a fire and Hanno has been working on fixing it, pr is raised

**Comment by hannojg** [comment] 2023-07-27 11:39
👋

**Comment by mountiny** [comment] 2023-08-01 12:05
We will have to make a regression test for this @namhihi237 Are you able to suggest one please?

**Comment by mountiny** [comment] 2023-08-06 18:14
Thanks! @stephanieelliott could we add this as a regression test please?

**Comment by stephanieelliott** [comment] 2023-08-07 17:30
Issue for regression test here: https://github.com/Expensify/Expensify/issues/306359

**Comment by stephanieelliott** [comment] 2023-08-07 17:36
Seems like no payment is due on this issue since it was a regression? Will leave this open for comment for one more day in case payment needs to be made.

**Closed** 2023-08-08 20:44 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by stephanieelliott** [comment] 2023-08-09 13:17
Thanks @namhihi237, extended the offer to you in Upwork. 

Summarizing payment on this issue: 
 - Issue reporter: $250 @namhihi237, payment in Upwork 
 - Contributor: N/A, expert contrib
 - Contributor+: N/A, regression 
 
 Upwork job is here https://www.upwork.com/jobs/~01256709c3bd79ab23

**Comment by stephanieelliott** [comment] 2023-08-15 02:55
Thanks for the reminder and sorry for the delay @namhihi237, I issued your payment in Upwork!
