### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Chat – Requested money disappears from conversation in specific account and chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36582] opened 2024-02-15 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with [applausetester+jp_e_category@applause.expensifail.com](mailto:applausetester+jp_e_category@applause.expensifail.com)
3. Navigate to a chat with Admin
4. Click on the + in the compose box, select "Request money" and complete the flow

## Expected Result:
The IOU appears in the conversation

## Actual Result:
The IOU appears and disappears in the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1786f14a-8fbc-4415-a588-e79ee709eb06

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f81770ce9fdadcb</li>
        <li>Upwork Job ID: 1758127876420673536</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-15 13:56
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by allroundexperts** [comment] 2024-02-17 03:47
Looking for proposals.

**Comment by bernhardoj** [comment] 2024-02-17 05:37
The request preview doesn't disappear but moves up because the BE returns the `created` value smaller than what it should be. Today is 02-17 but BE returns 02-09
<img width="295" alt="image" src="https://github.com/Expensify/App/assets/50919443/8a5e45b7-f6ae-4b27-9b15-20c7a8734b9e">

**Comment by allroundexperts** [comment] 2024-02-19 03:04
Makes sense. Looks like this needs to be internal.

**Comment by rojiphil** [comment] 2024-02-19 03:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report Preview disappears from conversation in chat Report

### What is the root cause of that problem?

Recently, there was an intentional change in BE as mentioned [here](https://github.com/Expensify/App/pull/35431#issuecomment-1948313987) and [here](https://github.com/Expensify/App/pull/35431#issuecomment-1947730645) which prevents the Report Preview to move to the latest report action. The Report Preview will remain in the same place where it was earlier. This is the root cause.

### What changes do you think we should make in order to solve the problem?

We need to prevent updation of `created` in the Report Preview action during money request generation [here](https://github.com/Expensify/App/blob/39b575c6af3c1442e9452aadbb79b403b40964e6/src/libs/ReportUtils.ts#L3314) 

`-        created: DateUtils.getDBTime(),`

### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment] 2024-02-19 05:10
Thanks for the additional context @rojiphil. Removing the `created` key in the optimistic report should solve the issue as suggested by @rojiphil's [proposal](https://github.com/Expensify/App/issues/36582#issuecomment-1951629701).

🎀 👀 🎀 C+ reviewed

**Comment by alexpensify** [comment] 2024-02-21 01:44
@roryabraham - any update if you approve this proposal? Thanks!

**Comment by alexpensify** [comment] 2024-02-23 00:07
Bumped Rory in Chat, help is on the way.

**Comment by roryabraham** [comment] 2024-02-23 00:08
I'm not sure the long-term plan for report previews, but in the short-term @rojiphil's proposal LGTM 👍🏼

**Comment by rojiphil** [comment] 2024-02-26 04:54
@allroundexperts 
[PR](https://github.com/Expensify/App/pull/37187) is ready for review

**Comment by roryabraham** [comment] 2024-02-27 07:55
PR merged

**Comment by mvtglobally** [comment] 2024-02-27 15:49
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2024-03-01 02:03
Awesome, looks like automation kicked in here. 

--- 

Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Closed** 2024-03-08 00:41 UTC
Labels: External, Daily, Monthly, Awaiting Payment, Bug
