### ISSUE TITLE
Console error when refreshing the page after switching chats

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13893] opened 2022-12-29 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #13523

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Open any chat
4. Switch between chats
5. Verify that composer view doesn't disappear
6. Refresh the page

## Expected Result:
No console error 

## Actual Result:
Error appears in console after refresh the page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows  / Chrome

**Version Number:** 1.2.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210017752-ed25c5e4-d086-4d12-89c6-70d95da8b2d1.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2022-12-30 13:35
I can reproduce the error on staging

<img width="573" alt="image" src="https://user-images.githubusercontent.com/17131195/210075831-895e3a56-6a05-42a5-8422-17ea028e5ec1.png">

**Comment by johnmlee101** [comment] 2022-12-30 15:40
The 404 is definitely an odd one, and probably thats what follows up with the bad reportID loading in the following. Will investigate soon

**Comment by puneetlath** [comment] 2023-01-12 23:23
@johnmlee101 this issue was created 2 weeks ago. Are we close to approving a proposal? If not, what's blocking us from getting this issue assigned? Don't hesitate to create a thread in #expensify-open-source to align faster in real time. Thanks!

**Comment by johnmlee101** [comment] 2023-01-13 17:37
Got sidetracked but I'm looking at this now. I can't reproduce this locally so I'm thinking that this is an internal issue with our hosting and routing, but I can't nail what might be causing it yet

**Comment by johnmlee101** [comment] 2023-01-13 18:00
I think this has to deal with our configuration for redirects (403 goes to 404)
<img width="839" alt="image" src="https://user-images.githubusercontent.com/5258036/212388503-280f5391-845c-4a88-8b1f-55501c8ecabc.png">
So going to investigate why 403 happens

**Comment by johnmlee101** [comment] 2023-01-13 18:03
Asked https://expensify.slack.com/archives/C01SKUP7QR0/p1673632959045469

**Comment by johnmlee101** [comment] 2023-01-16 19:23
Seems fixed on staging after implementing the redirect code change, going to implement on prod if we get no hiccups

**Comment by johnmlee101** [comment] 2023-01-16 20:10
Set it on prod, we shouldn't see the 404 console error anymore

**Comment by johnmlee101** [comment] 2023-01-17 15:28
cool this is solved on prod. closing it out. The other console errors already have existing issues.

**Closed by johnmlee101** 2023-01-17 15:28 UTC
Labels: Engineering, Daily, Bug
