### ISSUE TITLE
[$250] Track-Transaction thread of track distance is empty when there is submitted expense previously

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45253] opened 2024-07-11 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace chat.
4. Submit a distance expense.
5. Go to self DM.
6. Create a track distance
7. Click Categorize it from the actionable whisper.
8. Select the same workspace from Step 2.
9. Select a category and submit to the workspace.
10. On workspace chat, navigate to the expense preview of the track distance from Step 9.

## Expected Result:
The transaction thread of track distance will open without issue.

## Actual Result:
The transaction thread of track distance is blank and the header shows skeleton loading.

This issue only happens when there is expense in the workspace chat and then categorizing track expense to the same workspace chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d2c0b5f6-f218-483e-922e-4058c7ec325a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011318b81d940afa56</li>
        <li>Upwork Job ID: 1813322834881552972</li>
        <li>Last Price Increase: 2024-08-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dangrous</details>

**Comment by izarutskaya** [comment] 2024-07-11 11:31
We think this issue might be related to the #collect project.

**Comment by trjExpensify** [comment] 2024-07-19 11:15
Track expense bugs go to #vip-vsb.

**Comment by sobitneupane** [comment] 2024-07-22 07:12
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-07-26 05:47
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-07-30 08:32
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-08-03 04:52
Waiting for proposal.

**Comment by sobitneupane** [comment] 2024-08-07 06:50
Waiting for proposal.

**Comment by slafortune** [comment] 2024-08-07 14:23
@sobitneupane are you able to recreate this still?

**Comment by teneeto** [comment] 2024-08-09 08:19
Hey! I'm Eto Olei from Callstack. I will like to look into this issue. Please assign it to me. Thanks!

**Comment by sobitneupane** [comment] 2024-08-09 11:19
@slafortune Yep. I can still reproduce the issue.

<img width="1440" alt="Screenshot 2024-08-09 at 17 03 37" src="https://github.com/user-attachments/assets/d1abc99c-1218-49bc-b494-b1c60aee3ea1">

**Comment by teneeto** [comment] 2024-08-13 09:01
Still investigating this.

**Comment by sobitneupane** [comment] 2024-08-13 09:15
https://github.com/Expensify/App/issues/45253#issuecomment-2285735618

**Comment by slafortune** [comment] 2024-08-13 20:02
Adding another BZ - I'll be out until 8/21 and will check in on this then.

**Comment by teneeto** [comment] 2024-08-15 07:35
Still working on this, will share more update by EOD.

**Comment by teneeto** [comment] 2024-08-21 09:50
I'm still on this Melvin

**Comment by teneeto** [comment] 2024-08-21 09:59
Currently found a trace to this, but still working on a solution for this.

**Comment by sobitneupane** [comment] 2024-08-22 06:41
https://github.com/Expensify/App/issues/45253#issuecomment-2301651476

**Comment by teneeto** [comment] 2024-08-23 08:28
Still actively looking into this...

**Comment by slafortune** [comment] 2024-08-23 16:29
I'm back from OOO so I'll unassign you @trjExpensify

**Comment by slafortune** [comment] 2024-08-26 18:41
@teneeto do you have an update to share?

**Comment by teneeto** [comment] 2024-08-26 22:13
Hi @slafortune, I'm still running through this. Have not fully catch all the details to share yet, but I hope soon I can share what I've realised so far.

**Comment by teneeto** [comment] 2024-08-28 17:00
Hi @slafortune, I am still working on this and hope to share a solution by tomorrow at EOD (I'm close).

**Comment by slafortune** [comment] 2024-08-28 18:42
Great - thanks for the heads up @teneeto

**Comment by teneeto** [comment] 2024-08-30 08:01
@sobitneupane, I wanted to provide you with an update as expected but unfortunately, I wasn’t able to meet the deadline I promised for the end of the day yesterday. My apologies.

I’m making progress and expect to have the updates ready by today instead.

Thanks for the patience.

**Comment by teneeto** [comment] 2024-09-02 09:04
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The transaction thread of track distance is blank and the header shows skeleton loading.

This issue only happens when there is expense in the workspace chat and then categorizing track expense to the same workspace chat.


### What is the root cause of that problem?
There's no data coming in for `parentReportAction` which is a required data to display both `Header` and `ReportActionsView` as used here in https://github.com/teneeto/Expensify/blob/e77f20458ad13d94c7b0188acc2ed1a91bd8ccbd/src/pages/home/ReportScreen.tsx#L791.

Note: _This only happens when there is expense in the workspace chat and then categorizing track expense to the same workspace chat._


### What changes do you think we should make in order to solve the problem?
This issue seems to be a backend update issue (I'll reach out for confirmation on this anyway). But for now I suspect it to be an issue that could be treated by BE as I was unable to figure out any FE issue leading to this problem.


### What alternative solutions did you explore? (Optional)
NIL

**Comment by sobitneupane** [comment] 2024-09-04 09:00
Thanks for the update @teneeto 

I agree with you; I cannot reproduce the issue offline, so it might be related to the backend or the successdata in the API handling.

🎀 👀 🎀 C+ reviewed

**Comment by teneeto** [comment] 2024-09-04 10:43
@sobitneupane, that's great! I'm still looking into this issue. Let me know if anything contrary comes up—I'll look into it ASAP.

**Comment by dangrous** [comment] 2024-09-04 14:55
I feel like we had another similar issue recently with moving an expense to a workspace, which might be related. I'll try to find that shortly, and/or post in Slack to see if anyone knows!

**Comment by dangrous** [comment] 2024-09-04 14:55
I think your assessment that this is backend is correct, though

**Comment by dangrous** [comment] 2024-09-06 22:13
No time today - will tackle after copilot!

**Comment by dangrous** [comment] 2024-09-11 22:12
Blargh haven't had time. Will definitely look this Friday if not earlier

**Comment by dangrous** [comment] 2024-09-11 22:14
taking the owner star from @sobitneupane since this is on me

**Comment by dangrous** [comment] 2024-09-13 23:58
hey @thienlnam @yuwenmemon I'm a little stumped on this one, and it looks like y'all worked on the related logic a couple months ago. Any thoughts on what's going on here? I tried to go through the flow and couldn't figure out where it was going wrong.

**Comment by thienlnam** [comment] 2024-09-16 16:14
Not sure, but based on this [comment](https://github.com/Expensify/App/issues/45253#issuecomment-2324209974) it seems like it might be related to when the expense is added to the an existing money request report where some key is not getting set correctly

**Comment by dangrous** [comment] 2024-09-17 22:24
oh okay I think I saw in the backend something where we only send a parentReportAction if x happens, maybe will need to update that conditional. That's helpful, thank you!

**Comment by dangrous** [comment] 2024-09-18 21:37
oh lol I think I figured it out - looking at the Onyx data:
* The existing transaction (good): `parentReportActionID: "8594564772339706339"`
* The newly moved transaction (bad): `parentReportActionID: 7554225325900250000`

It's coming through as a number not a string, that seems to be the issue? Any thoughts on where that's set @thienlnam? Or, is it something we can change from the front end @teneeto or @sobitneupane

**Comment by dangrous** [comment] 2024-09-20 19:27
I think I got it, PR up momentarily

**Comment by dangrous** [comment] 2024-09-24 16:26
@slafortune the fix for this is on prod, do you mind testing again to see if we're good to close?

**Comment by slafortune** [comment] 2024-09-25 16:39
Looks good - not able to recreate 🎉 

An internal engineer reviewed the PR so no payments due - closing

**Closed by slafortune** 2024-09-25 16:39 UTC
Labels: Reviewing, External, Daily, Bug
