### ISSUE TITLE
[HOLD for payment 2023-07-17] Bank account - Company name and connected account are shaded and hover shows a "Locked" icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22340] opened 2023-07-06 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Expensify App or go to staging.new.expensify.com
2. Login with expensifail account
3. Create workspace or go to existing workspace
4. Go to workspace > Bank account
5. Start and complete connection for any bank account
6. Check what a connected bank account looks like

## Expected Result:
The company name and account are white. Nothing happens when you hover the cursor

## Actual Result:
The company name and account are shaded and when you hover over them, the cursor has a “Locked” icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.37.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6118135_BA-Added-cursor-blocked](https://github.com/Expensify/App/assets/78819774/6bca6e8a-a3a6-4ef9-812d-9072518b5f60)

![Bug6118135_BA-Added-prod-staging](https://github.com/Expensify/App/assets/78819774/5e65f823-56ec-433f-a277-1a25c04e79ff)

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment] 2023-07-06 14:19
I think this was caused by this PR https://github.com/Expensify/App/pull/21372/files, but the `MenuItem` receives a prop disabled and it makes sense that it gets displayed like that. I'm not sure why though do we want to pass in `disabled` to the menu item displaying the bank account info. I'm creating a PR to remove it but also discussing this in Slack in case there might be a reason for it.

**Comment by Julesssss** [comment] 2023-07-06 15:48
[Not a blocker](https://github.com/Expensify/App/pull/22346#issuecomment-1623909674), so I'm not going to CP it.

**Comment by youssef-lr** [comment] 2023-07-21 21:04
No payments needed here, this was handled internally. Closing!

**Closed by youssef-lr** 2023-07-21 21:04 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
