### ISSUE TITLE
[HOLD for payment 2024-11-29] [HOLD for payment 2024-11-28] [$250] Attachment- Hmm it's not here page occur when expanding attached video

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52747] opened 2024-11-19 09:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52021
**Email or phone of affected tester (no customers):** testpayment935+641@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to http://www.staging.new.expensify.com/
2. Login into any account
3. Navigate to any 1:1 DM
4. Send any video/image attachment
3. Web -try to expand, mweb try to play the attached video

## Expected Result:
Video played without an error

## Actual Result:
Hmm it's not here page occur when expanding attached video

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/19f75f57-b900-4a16-a9c3-f5ab0d3f0a84

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858819849998561580</li>
        <li>Upwork Job ID: 1858819849998561580</li>
        <li>Last Price Increase: 2024-11-19</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 104967424</li>
<li>mkzie2 | Contributor | 104967756</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by mkzie2** [comment] 2024-11-19 10:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hmm it's not here page occur when expanding attached video

### What is the root cause of that problem?
When we expand a video, `attachmentLink` is an empty string, and `attachment.attachmentLink` is `undefined` so the `index` is `-1` which displays the not found page


https://github.com/Expensify/App/blob/f77087f02a42e17e7da7420528cc51b54003ca61/src/components/Attachments/AttachmentCarousel/index.tsx#L73

### What changes do you think we should make in order to solve the problem?
We should only compare the `attachmentLink` if `attachmentLink` param exists

```
const compareImage = useCallback((attachment: Attachment) => attachment.source === source && (!attachmentLink || attachment.attachmentLink === attachmentLink), [attachmentLink, source]); 

```

https://github.com/Expensify/App/blob/f77087f02a42e17e7da7420528cc51b54003ca61/src/components/Attachments/AttachmentCarousel/index.tsx#L73

### What alternative solutions did you explore? (Optional)

**Comment by Gonals** [comment] 2024-11-19 11:41
@mkzie2, all yours! Let's get that PR ready!

**Comment by mkzie2** [comment] 2024-11-19 12:11
@ishpaul777 The [PR](https://github.com/Expensify/App/pull/52757) is ready.

**Comment by Gonals** [comment] 2024-11-19 22:11
CP'd and tested. Removing blocker!

**Comment by trjExpensify** [comment] 2024-11-28 13:49
👋 checklist time!

**Comment by trjExpensify** [comment] 2024-12-02 13:14
> Not required this was caught in production deploy QA process we should have enough tests covering the flow

Makes sense! 

Payment summary as follows: 

- $250 to @ishpaul777 for the C+ review
- $250 to @mkzie2 for the fix 

Paid, closing!

**Closed by trjExpensify** 2024-12-02 13:14 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
