### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] Dupe detect - Tag name on the confirmation page follows custom tag name from other workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50662] opened 2024-10-11 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- There are two workspaces.
- Each workspace has enabled Tags and has custom tag name.

1. Go to staging.new.expensify.com
2. Go to workspace chat A.
3. Submit an expense.
4. Go to workspace chat B.
5. Submit the same expense as Step 3.
6. Submit another dupe expense on both workspaces (a different amount).
7. Go back to workspace chat A and open the transaction thread from Step 3 (because Keep this one button won't appear in Step 9 if this is not opened first).
8. Go to transaction thread of the expense from Step 5.
8. Click Review duplicates.
9. Click Keep this one on the second expense in the list (this expense is from Step 3).
10. Proceed to confirmation page.

## Expected Result:
The tag name on the confirmation page will show the custom tag name from workspace A, because the expense from workspace A is selected on review duplicates page (from Step 9).

## Actual Result:
The tag name on the confirmation page shows the custom tag name from workspace B, when the expense from workspace A is selected.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ca858588-cf72-414a-8b1b-f3ac4ad63786

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845671687760709934</li>
        <li>Upwork Job ID: 1845671687760709934</li>
        <li>Last Price Increase: 2024-10-14</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104426916</li>
<li>truph01 | Contributor | 104426918</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by IuliiaHerets** [comment] 2024-10-11 16:44
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-10-11 16:45
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment] 2024-10-12 06:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tag name on the confirmation page shows the custom tag name from workspace B, when the expense from workspace A is selected.

### What is the root cause of that problem?
- The ```policyTagList``` data comes from incorrect logic:

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/components/ReportActionItem/MoneyRequestView.tsx#L93

because policyID points to the policyID of the report that we are opening, caused the bug that confirmation page shows the custom tag name from workspace B, when the expense from workspace A is selected.
### What changes do you think we should make in order to solve the problem?
- We can change the logic to get the policy tag list from:
https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/components/ReportActionItem/MoneyRequestView.tsx#L93
to:

```
    const targetPolicyID = updatedTransaction ? ReportUtils.getReport(updatedTransaction?.reportID)?.policyID : policyID;
    const [policyTagList] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_TAGS}${targetPolicyID}`);
```
and apply it to other similar places.
### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2024-10-14 03:43
Oh interesting - I can reproduce this, I think this can be external so let's start there.

**Comment by suneox** [comment] 2024-10-14 18:21
The [proposal](https://github.com/Expensify/App/issues/50662#issuecomment-2408409804) from @truph01 LGTM. In this case, since we have an `updatedTransaction` so we should retrieve the target policy from the `updatedTransaction`


🎀 👀 🎀 C+ reviewed

**Comment by MariaHCD** [comment] 2024-10-15 12:11
Sounds good to me 👍🏼

**Comment by suneox** [comment] 2024-10-27 04:16
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: *N/A*
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. *There isn’t an offending PR in this case, as this issue cover an edge case in the update transaction process and the tag list was implemented a long time ago.*
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by Christinadobrzyn** [comment] 2024-10-29 02:02
Looks like payment is tomorrow. No regression test is needed. 

Payouts due:

- [ ] Contributor: $250 @truph01 (Upwork offer - https://www.upwork.com/nx/wm/offer/104426916)
- [ ] Reviewer: $250 @suneox (Upwork offer - https://www.upwork.com/nx/wm/offer/104426916)

**Comment by Christinadobrzyn** [comment] 2024-10-30 05:41
Paid this out - closing.

**Closed by Christinadobrzyn** 2024-10-30 05:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
