### ISSUE TITLE
[HOLD for payment 2024-12-07] [HOLD for payment 2024-12-05] iOS - Expense - Tapping Save button (from Merchant page) for the second time returns to BNP

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53152] opened 2024-11-26 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch the app.
2. Go to workspace chat.
3. Tap + > Submit expense.
4. Enter amount > Next.
5. Tap Merchant.
6. Enter merchant.
7. Tap Save.
8. Tap Save button again after the keyboard closes (merchant editor exits after delay).

## Expected Result:
- Merchant editor will exit instantly after tapping Save button (production behavior).
- App will return to confirmation page when tapping Save button for the second time.

## Actual Result:
- Merchant editor does not exit instantly after tapping Save button. It closes the keyboard first and exits after some delay, which allows Save button to be tapped for the second time.
- App returns to BNP when tapping Save button for the second time.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/835b8708-0db9-4b13-8038-cd92c2249a99

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by ChavdaSachin** [comment] 2024-11-26 19:26
## Proposal




### Please re-state the problem that we are trying to solve in this issue.
iOS - Expense - Tapping Save button (from Merchant page) for the second time returns to BNP




### What is the root cause of that problem?

When clicking save button twice, function call for `updateMerchant` is triggered twice.
And hence `updateMerchant` function function calls `navigateBack()` function twice here.
https://github.com/Expensify/App/blob/967cc5c21600d4706f40364cb6c7022ded0d6d8a/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L121
https://github.com/Expensify/App/blob/967cc5c21600d4706f40364cb6c7022ded0d6d8a/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L86-L108



### What changes do you think we should make in order to solve the problem?

To avoid this we should make use of `singleExecution` and `isExecuting`  from hook `useSingleExecution` to ensure updateMerchant function is executed only once. As we do here on `WorkspaceInitialPage`.
https://github.com/Expensify/App/blob/967cc5c21600d4706f40364cb6c7022ded0d6d8a/src/pages/workspace/WorkspaceInitialPage.tsx#L98
https://github.com/Expensify/App/blob/967cc5c21600d4706f40364cb6c7022ded0d6d8a/src/pages/workspace/WorkspaceInitialPage.tsx#L306
And disable the `save` button when `isExecuting` is true.
https://github.com/Expensify/App/blob/967cc5c21600d4706f40364cb6c7022ded0d6d8a/src/pages/workspace/WorkspaceInitialPage.tsx#L426-L439

### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mountiny** [comment] 2024-11-26 19:35
@ChavdaSachin can you please point what PR caused this regression from the checklist?

**Comment by mountiny** [comment] 2024-11-26 20:56
@kirillzyusko @c3024 could you please investigate this flow for a fix? this is in standalone app too so you should be able to test

**Comment by ChavdaSachin** [comment] 2024-11-26 21:01
Yes this is coming from #52392.
Specifically from this line
https://github.com/margelo/expensify-app-fork/blob/84175de2f85e89cee967b3f9c73153e115620a53/src/components/Form/FormProvider.tsx#L210

**Comment by ChavdaSachin** [comment] 2024-11-26 21:23
[Updated Proposal](https://github.com/Expensify/App/issues/53152#issuecomment-2501754258)
Added root cause and improvement around it.

**Comment by marcaaron** [comment] 2024-11-26 22:01
Yes, let's give some time to @kirillzyusko first since it is a regression.

**Comment by kirillzyusko** [comment] 2024-11-27 09:51
I agree with proposal from @ChavdaSachin 

Two things that I would do differently:
- for `isSubmitting` I would use `useRef` (to avoid unnecessary re-renders);
- we need to set the variable back to `false` in `KeyboardUtils.dismiss().then(() => { /*.set ref/state to false here */ onSubmit(trimmedStringValues); });`

@ChavdaSachin will you fix this problem? Or should I fix it because it was my changes that introduced a regression?

**Comment by ChavdaSachin** [comment] 2024-11-27 10:06
> @ChavdaSachin will you fix this problem?
I would be happy to fix this

**Comment by kirillzyusko** [comment] 2024-11-27 10:10
@ChavdaSachin then I'm happy to approve your proposal. Is there anything else required from my side?

**Comment by ChavdaSachin** [comment] 2024-11-27 10:18
As of now it's pretty straightforward, but I will let you know if I face any further complications.

**Comment by mountiny** [comment] 2024-11-27 11:17
@ChavdaSachin What is your ETA for raising the PR?

**Comment by mountiny** [comment] 2024-11-27 11:18
Assigned myself as I have co-reviewed the original PR

**Comment by ChavdaSachin** [comment] 2024-11-27 12:05
> * we need to set the variable back to `false` in `KeyboardUtils.dismiss().then(() => { /*.set ref/state to false here */ onSubmit(trimmedStringValues); });`

I tried to implement this suggestion but this is causing same issue of double execution somehow.
So, I am currently investigating the issue further.
Will provide next update within an hour.

**Comment by mountiny** [comment] 2024-11-27 15:11
@ChavdaSachin I am going to assign @kirillzyusko as this is one of the more challenging deploy blockers. Given the urgency, we will proceed with his help on this issue

**Comment by mountiny** [comment] 2024-11-27 15:11
Feel free to provide any more context and if your solutions will be used, we are happy to provide some compensation for your help

**Comment by ChavdaSachin** [comment] 2024-11-27 15:13
I have got it working

**Comment by ChavdaSachin** [comment] 2024-11-27 15:13
just testing on all the platforms 
And raising PR in few minutes

**Comment by mountiny** [comment] 2024-11-27 15:14
@ChavdaSachin Nice, please feel free to make a draft

**Comment by kirillzyusko** [comment] 2024-11-27 16:57
@IuliiaHerets I also discovered that a problem with double navigations happens on:
- Settings -> Profile -> Date of birth
- Settings -> Profile -> Phone number (you can close keyboard and then press submit)
- Settings -> Profile -> Address

**Comment by mountiny** [comment] 2024-11-27 21:28
CPing the fix, thanks @kirillzyusko

**Comment by c3024** [comment] 2024-12-03 13:25
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [x] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: NA. This was identified in regression testing and the blocker was fixed by offending PR author. 

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

Regression Test Proposal Template


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1. Launch the app.
2. Go to workspace chat.
3. Tap + > Submit expense.
4. Enter amount > Next.
5. Tap Merchant.
6. Enter merchant.
7. Tap Save.
8. Tap Save button again after the keyboard closes.
9. You should be redirected to the previous screen.

Do we agree 👍 or 👎

**Comment by mountiny** [comment] 2024-12-04 15:41
I dont think we need to add a regression test specifically for this, the QA will most likely catch some bug in normal testing

**Comment by mountiny** [comment] 2024-12-04 15:42
Given this came from a PR @c3024 reviewed and the author fixed it, I think we can just close it, thanks!

**Closed by mountiny** 2024-12-04 15:42 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
