### ISSUE TITLE
[HOLD][$250] Web - Compose Box - In the minimize window, one chat opens with weird behavior

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10243] opened 2022-08-04 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9706 
## Action Performed:
1. Click on one chat first
2. Minimize the window as much as possible
3. Maximize the window
4. Click another chat
5. Minimize window

## Expected Result:
When minimizing the window, the chat must stay in the browser to continue the conversation with the selected user.

## Actual Result:
When minimizing the window, one chat remains active, and the other either goes to the list of all chats and there is no possibility to chating with the selected user, or a window with a broken structure opens

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.87-9

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/182844993-6431165a-e059-4668-9ac1-0f403e19671a.mp4

https://user-images.githubusercontent.com/43996225/182845006-f569b921-8f81-4bca-8216-77b210afc02d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment] 2022-08-04 19:08
This does seem like some very strange behavior. Marking external

**Comment by arielgreen** [comment] 2022-08-04 23:21
https://www.upwork.com/jobs/~01ca63ca537eb8471e

**Comment by syedsaroshfarrukhdot** [comment] 2022-08-05 15:42
Is this issue still relevant and needs to be resolved? As, I have been working on it from last few hours but then by reference to PR #9706 found out that it has been put on hold by the team to find a more viable solution internally and the previous PR regarding this issue have been reverted. As it was newly marked external and the job was posted on Upwork. Not sure to work on it or not.

**Comment by mananjadhav** [comment] 2022-08-09 19:41
> still relevant and needs to be resolved?

Good point @syedsaroshfarrukhdot. @marcochavezf @arielgreen Are we treating this as a separate issue or regression of #9706.

Irrespective of whether or not being relevant or hold, @syedsaroshfarrukhdot, I didn't understand when you say you've been working on it since last few hours. Just fyi, as per the contributing guidelines please send in a proposal here to be reviewed before working on the actual solution.

**Comment by syedsaroshfarrukhdot** [comment] 2022-08-09 21:18
> > still relevant and needs to be resolved?
> 
> Good point @syedsaroshfarrukhdot. @marcochavezf @arielgreen Are we treating this as a separate issue or regression of #9706.
> 
> Irrespective of whether or not being relevant or hold, @syedsaroshfarrukhdot, I didn't understand when you say you've been working on it since last few hours. Just fyi, as per the contributing guidelines please send in a proposal here to be reviewed before working on the actual solution.

Yes, Thanks for highlighting the fact. I will definitely follow contributing guidelines next time and submit proposal to be reviewed before working on the actual solution.

**Comment by marcochavezf** [comment] 2022-08-10 19:44
Oh good point, yeah this seems to be a regression, but besides that, we're going to put on hold all the issues related to navigation. Thanks for pointing that out @syedsaroshfarrukhdot, this issue should not be resolved until we come up with a definitive and long-term solution as stated [here](https://github.com/Expensify/App/pull/9706#issuecomment-1194834689).

**Comment by marcochavezf** [comment] 2022-08-10 19:58
I found out the changes to the related https://github.com/Expensify/App/pull/9706 were reverted here https://github.com/Expensify/App/pull/10101, so it will be better to close this issue because we're going to have the same behavior until we fix the root cause.

@arielgreen could you remove the upwork job?

**Comment by arielgreen** [comment] 2022-08-11 22:50
Done.

**Closed by arielgreen** 2022-08-11 22:50 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
