### ISSUE TITLE
LHN - Chat with invalid number is not showing red dot in LHN when go online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34822] opened 2024-01-19 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab--- Start chat
3. Turn off mobile data
4. Search a voip number (+18183305299) & select it
4. Send some messages
5. Turn on mobile data
6. Wait till red error messages appear under the messages sent
7. Navigate back to LHN

## Expected Result:
For starting chat with invalid number in offline, sending messages and turn online, must show red dot in LHN

## Actual Result:
For starting chat with invalid number in offline, sending messages and turn online, not showing red dot in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c650951f-8a7b-4392-a998-42f7f8eaf337

https://github.com/Expensify/App/assets/78819774/88de6c19-b849-40d2-b6ed-6ea8493210d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-01-19 18:20
I think this is a dupe of https://github.com/Expensify/App/issues/34827

**Closed by mountiny** 2024-01-19 18:20 UTC
Labels: Engineering, Daily
