### ISSUE TITLE
[$1000] Workspace - Currency change notification is not translated to Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22003] opened 2023-06-30 22:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Preferences > Language > Spanish
3. Go to Configuración (Settings) > Espacios de trabajo (Workspace) > Workspaces > Configuración (Settings) > Moneda por defecto (Default currency)
4. Change the currency to other currency
5. Go to #admins

## Expected Result:
Currency change notification is translated to Spanish

## Actual Result:
Currency change notification is not translated to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b9d9dcd1-9054-46a6-a032-4789151d6c3a

<img width="1440" alt="Bug6112401_Screenshot_2023-07-01_at_03 31 59" src="https://github.com/Expensify/App/assets/78819774/6f9d8bc4-02bc-4b36-a690-4af77154c31d">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team /mahmudjontoraqulov

**Slack conversation:**

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e92bbb90aa2aab7</li>
        <li>Upwork Job ID: 1675942757935378432</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-01 03:30
BE returns currency change notification that is not translated to spanish.

**Comment by kbecciv** [comment] 2023-07-02 13:38
@Christinadobrzyn There is another area when the Distance Change Notification Not Translated to Spanish.
Reproduction steps:
1. Navigate to settings > workspace > Admin rooms.
2. Then go to settings again > Reimbursement > change the rate.
3. A notification will appear in the Admin rooms.
4. Go to settings > preference > change the language to Spanish.
5. Observe that the notification is not translated into Spanish.

https://github.com/Expensify/App/assets/93399543/25a3e069-2e8e-4363-afd7-8606bf5aceb2

Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1688200644988019

**Comment by Christinadobrzyn** [comment] 2023-07-03 19:00
I can reproduce - adding External label

**Comment by ishpaul777** [comment] 2023-07-04 17:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Workspace - Currency change notification is not translated to Spanish

### What is the root cause of that problem?
Currently a notification is renderend as it is received from backend. without any translation.
see full code [here](https://github.com/Expensify/App/blob/3e0d7dd28df5ebc104d6291aa7ceeb4cced65f65/src/pages/home/report/ReportActionItemFragment.js#L86C9-L131C41).
```
{convertToLTR(text)}
```
### What changes do you think we should make in order to solve the problem?
To handle it on clientside,  like we are muting text here
```
<ReportActionItemMessage
                                action={props.action}
                                isHidden={isHidden}
                                style={[
                                    !props.displayAsGroup && isAttachment ? styles.mt2 : undefined,
                                    _.contains([..._.values(CONST.REPORT.ACTIONS.TYPE.POLICYCHANGELOG), CONST.REPORT.ACTIONS.TYPE.IOU], props.action.actionName)
                                        ? styles.colorMuted
                                        : undefined,
                                ]}
                            />
 ```

we could have a prop passed in ReportActionItemMessage.
```
            const isNotification = _.contains([..._.values(CONST.REPORT.ACTIONS.TYPE.POLICYCHANGELOG), CONST.REPORT.ACTIONS.TYPE.IOU], props.action.actionName)
```
 if isNotification  use the translate prop
 const translatedText = props.isNotification ? text.split(' ').map(word => props.translate(`${word}`)).join(' ') : null;


### What alternative solutions did you explore? (Optional)
Alternatively we can handle on serverside, fragment.type could be "NOTIFICATION" and text could be a alias of actual message like "notification.currencyChange" or some regex pattern if there are variables in text like "notification.currencyChange {{prevCurrency}}-{{newCurency}}}" which later can be decoded on client side

**Comment by Christinadobrzyn** [comment] 2023-07-05 19:54
Sounds good - closing this

**Closed by Christinadobrzyn** 2023-07-05 19:54 UTC
Labels: External, Daily, Help Wanted, Bug
