### ISSUE TITLE
[HOLD for Payment 2024-08-22] [$250] Web - Expense - App navigates to not found page when paying part of an expense offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46600] opened 2024-07-31 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** [Yokabdk+new1@gmail.com](mailto:Yokabdk+new1@gmail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to settings and workspace and create a workspace
3. Go to FAB
4. Click on submit expense and click the workspace you created
5. Enter an amount (e.g 100) and click Next
6. Input a merchant and submit the expense
7. Create another expense with a different amount (e.g 50)
8. Navigate to the expense details page of the first expense (e.g 100)
9. Click on header and click on hold
10. Click on the subtitle "From" link to go back to the expense lists page (Important)
11. Click on the drop down of the green pay button at the top right corner
12. Click on "Pay elsewhere"
13. Click on "Pay only 50" on the confirmation pop up

## Expected Result:
App navigates to the expense lists page which is the behavior in online mode

## Actual Result:
App navigates to not here page when clicking on the pay only ... button while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/001fd447-46e1-4619-9ceb-18da691e009e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116c34258c5f026d6</li>
        <li>Upwork Job ID: 1818936321732205498</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103423828</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment] 2024-07-31 16:56
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-08-01 05:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page when paying partial report.

### What is the root cause of that problem?
The not found page is because the report action isn't found anymore. If we have a hold expense and then pay it partially, we will optimistically remove the hold expense and move it to a new expense report. This is introduced in https://github.com/Expensify/App/pull/42573.
https://github.com/Expensify/App/blob/bbaa9da776ea97c124fa5a24c8454493c36c1a3a/src/libs/actions/IOU.ts#L6564-L6572

If we link to the hold expense action, when it's moved to the new expense report, the not found page shows.
https://github.com/Expensify/App/blob/bbaa9da776ea97c124fa5a24c8454493c36c1a3a/src/pages/home/ReportScreen.tsx#L413-L421

### What changes do you think we should make in order to solve the problem?

We can follow a similar approach when deleting a comment by checking if the deleted action is the linked action, then clear the reportActionID from the params.
https://github.com/Expensify/App/blob/d69b203c298a879e609ebff4be249f550456f98e/src/libs/actions/Report.ts#L1498-L1502

https://github.com/Expensify/App/blob/bbaa9da776ea97c124fa5a24c8454493c36c1a3a/src/libs/actions/IOU.ts#L6564-L6572

```
for (const oldReportAction of holdReportOnyxData.optimisticHoldReportExpenseActionIDs) {
    if (Navigation.isActiveRoute(ROUTES.REPORT_WITH_ID.getRoute(iouReport.reportID, oldReportAction.oldReportActionID))) {
        Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(iouReport.reportID), true);
        break;
    }
}
```

_We will do the same for approving_

### What alternative solutions did you explore? (Optional)
In ReportScreen, if the linked action is previously available but is now deleted, clear the reportActionID.
https://github.com/Expensify/App/blob/d69b203c298a879e609ebff4be249f550456f98e/src/pages/home/ReportScreen.tsx#L391
```
const prevIsLinkedActionDeleted = usePrevious(isLinkedActionDeleted);

useEffect(() => {
    if (!prevIsLinkedActionDeleted && isLinkedActionDeleted) {
        Navigation.setParams({reportActionID: ''});
    }
}, [prevIsDeletedParentAction, isLinkedActionDeleted]);
```

But the user will notice a brief blink of the not found page because we clear the reportActionID not immediately and to prevent that, we can update the not found condition to only show if both the previous `prevIsLinkedActionDeleted` and `isLinkedActionDeleted` are true.

https://github.com/Expensify/App/blob/d69b203c298a879e609ebff4be249f550456f98e/src/pages/home/ReportScreen.tsx#L413-L414

```
const shouldShowNotFoundLinkedAction =
    (!isLinkedActionInaccessibleWhisper && isLinkedActionDeleted && prevIsLinkedActionDeleted) ||
```

**Comment by brunovjk** [comment] 2024-08-01 18:59
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/46600#issuecomment-2262047138) LGTM

 🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment] 2024-08-01 19:05
@neil-marcellini, what do you think of the proposed alternative solution? Thank you.

**Comment by twisterdotcom** [comment] 2024-08-06 09:25
Bump on this @neil-marcellini

**Comment by neil-marcellini** [comment] 2024-08-06 19:36
> @bernhardoj's [proposal](https://github.com/Expensify/App/issues/46600#issuecomment-2262047138) LGTM

I agree, we might need some tweaks in the PR, but we'll see.

**Comment by bernhardoj** [comment] 2024-08-07 08:15
PR is ready

cc: @brunovjk

**Comment by neil-marcellini** [comment] 2024-08-15 01:15
Head's up, I'll be working 50% for the rest of this week and next 🌲

**Comment by neil-marcellini** [comment] 2024-08-20 17:49
It's time to do payment and close this out

**Comment by brunovjk** [comment] 2024-08-21 12:40
> [!NOTE]  
> The production deploy automation failed: This should be on **[HOLD for Payment 2024-08-22]** according to https://github.com/Expensify/App/issues/47356 prod deploy checklist, confirmed in https://github.com/Expensify/App/pull/46942#issuecomment-2294135056.

cc: @twisterdotcom

**Comment by brunovjk** [comment] 2024-08-23 12:12
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: #42573
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42573#issuecomment-2306964637
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again:

**Regression Test Proposal:**

- Go to settings and create a workspace
- Go to FAB and click on submit expense
- Select the workspace you created
- Enter an amount (e.g., 100) and click Next
- Input a merchant and submit the expense
- Create another expense with a different amount (e.g., 50)
- Navigate to the expense details page of the first expense (e.g., 100)
- Click on the header and select "Hold"
- Click on the "From" link in the subtitle to return to the expense list page
- Click the dropdown of the green pay button at the top right corner
- Select "Pay elsewhere"
- Click on "Pay only 50" in the confirmation pop-up
- Verify that the app navigates to the expense lists page, which is the behavior in online mode

Do we agree 👍 or 👎

**Comment by brunovjk** [comment] 2024-08-26 11:22
Hey @twisterdotcom, just a heads up that the payment for this issue is still pending. When you have a moment, could you help process it so we can close this out? Appreciate it!

**Comment by twisterdotcom** [comment] 2024-08-26 11:59
Ahh! Yes. Sorry, I'm OOO atm but will log in this evening to process it and close. Thanks for the bump.

**Comment by twisterdotcom** [comment] 2024-08-26 21:19
Payment Summary:

- @bernhardoj paid $250 via Manual Requests (Contributor)
- @brunovjk paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/38026643/overview?nav_dir=pop) (C+)

**Closed** 2024-08-26 21:20 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-08-27 02:32
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-28 17:28
$250 approved for @bernhardoj
