### ISSUE TITLE
[$500]  RHP - A user in "Hidden" status has different data in Profile and Details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35617] opened 2024-02-02 00:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4265473
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Create a conversation with the user [unexistingperson@gmail.com](mailto:unexistingperson@gmail.com)
4. Paste the text "@[unexistingperson@gmail.com"](mailto:unexistingperson@gmail.com%22)
into the Compose Box
5. Send a message
6. Click @[unexistingperson@gmail.com](mailto:unexistingperson@gmail.com)
7. Click on "Hidden" in the welcome message.

## Expected Result:
The data in the Profile and Details tabs must be the same for a user in "Hidden" status

## Actual Result:
A user in "Hidden" status has different data in Profile and Details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/9fdb2bfc-5b20-4662-b1d4-dd7df5750afe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b82ea0bdbf069e1e</li>
        <li>Upwork Job ID: 1753215147974737920</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 00:34
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by stephanieelliott** [comment] 2024-02-04 18:40
Was able to repro this -- seems like the `hidden` status does not apply when viewing the profile for the hidden user from within the chat.

**Comment by Tony-MK** [comment] 2024-02-05 01:11
**Notes**

When creating a chat, the backend does not return `displayName` but the `firstName` and `lastName` are empty strings.

The backend returns `displayName` after mentioning the user.

A backend fix is reasonable because if mentioning a hidden person in another chat, creating a new chat with a hidden person will not display "hidden" as expected.

![Screenshot 2024-02-05 at 02 10 35](https://github.com/Expensify/App/assets/22982173/7e91ed9f-2e56-4a4c-aafa-b2beae4b99cd)

**Comment by eVoloshchak** [comment] 2024-02-06 14:44
Agree with @Tony-MK, this is a back-end issue
@stephanieelliott, what should be the expected result here?

> The data in the Profile and Details tabs must be the same for a user in "Hidden" status

Should the user remain "Hidden" after mentioning them (i.e. hidden from both "Profile" and "Details"), or it should be the other way around (non-existing user is not "Hidden" when first starting a conversation with them)

**Comment by stephanieelliott** [comment] 2024-02-12 07:23
> Should the user remain "Hidden" after mentioning them (i.e. hidden from both "Profile" and "Details"), or it should be the other way around (non-existing user is not "Hidden" when first starting a conversation with them)

I'm honestly not quite sure -- I'm going to need to dig into the design internally to see what the intended behavior is. I should be able to share some clarification tomorrow!

**Comment by stephanieelliott** [comment] 2024-02-14 08:59
Hmm so while I first thought this was a privacy issue, I actually think this is expected behavior and the logic may make sense given the behavior of the `@mentions` and `hidden` features. Posted in Slack to discuss: https://expensify.slack.com/archives/C01GTK53T8Q/p1707901044961849

**Comment by stephanieelliott** [comment] 2024-02-14 18:34
OK so the current behavior _is_ the expected behavior, and it's also something that we'll be reworking in https://github.com/Expensify/Expensify/issues/313934. Will close this and defer to the main issue

**Closed by stephanieelliott** 2024-02-14 18:34 UTC
Labels: External, Daily, Help Wanted, Bug
