### ISSUE TITLE
[$1000] Thread title briefly appears in LHN after deleting thread message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21630] opened 2023-06-26 20:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat
2. Send a message
3. Click on "Reply in thread"
4. React with emoji on thread message
5. Send message on thread
6. Delete that message
## Expected Result: 
After deleting the thread message, the thread title should not be displayed from LHN
## Actual Result: 
The thread title is briefly visible in LHN even after deleting the thread message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4123a85c-250c-4704-84cc-7bddc21a4287

https://github.com/Expensify/App/assets/43996225/87ac183e-f741-4dbd-a4c5-d62dbe668c04

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687373680904369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afe64c0c4da4cc48</li>
        <li>Upwork Job ID: 1673454536343728128</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-06-26 22:13
Blimey this is _niche_. It only appears for a second, and it's only a problem if the first message of the thread had an emoji reaction.

Let's fix, but I'm making it weekly. It doesn't even affect people who use #focus mode.

**Comment by s77rt** [comment] 2023-06-27 13:03
@ginsuma Thanks for the proposal. I don't think your RCA is correct. What you are looking at is the onyx **to be merged** data with the existing one in the IndexedDB. The created field does not have to be included because it's not going to change. We are adding a new report action but updating an existing one.

BTW, are you still able to reproduce the bug? It does not seem reproducible from my end

**Comment by s77rt** [comment] 2023-06-27 15:26
@twisterdotcom Can you please retest from your end as well? This seems to be fixed already

**Comment by ayazhussain79** [comment] 2023-06-27 17:36
@twisterdotcom @s77rt I found this bug six days ago, but what if someone else came across this issue after my post and resolved it.
Can you please check that when it was found and fixed ?

**Comment by twisterdotcom** [comment] 2023-06-27 19:51
Huh, weird yes. It is fixed. Okay, let's close. Does anybody know where we solved this?

@ayazhussain79 I sent you the bug reporting bonus contract. I'll close this now.

**Closed by twisterdotcom** 2023-06-27 19:51 UTC
Labels: External, Daily, Help Wanted, Bug, Upwork Automation

**Comment by ayazhussain79** [comment] 2023-06-27 19:53
@twisterdotcom offer accepted, Thank you
