### ISSUE TITLE
Android - Notification for an unread message isn't cleared even after the message is read on web

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25807] opened 2023-08-23 23:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in as "User A" on the Android app and Mac Chrome and as "User B" on Mac Chrome alone (this might have to be in an incognito browser).
2. Ensure the Android app is closed, and you have cleared all notifications.
3. As "User A" on web, open any chat report other than the one with "User B".
4. As "User B", open the chat report with "User A" and send a message.
5. As "User A" on web, open the chat report with "User B" so it's considered read.
6. Observe the status bar and Android app's icon on your Android device.

## Expected Result:
The unread message notification is cleared because the message has been read i.e. there's no banner in the status bar, and the Expensify app icon has no badge indicating there is a notification.

## Actual Result:
The unread message notification persists along with a badge on the Expensify app icon even after the message is read

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-21

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a017a700-4f4e-49a2-b8c0-b3cb54af0827

![Screenshot_20230814_095127_One UI Home](https://github.com/Expensify/App/assets/115492554/bd2d3b94-ec14-4008-a231-2969808c8b96)

https://github.com/Expensify/App/assets/115492554/3bdacb2c-5f9b-435d-a812-da8d597eee26

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Victor-Nyagudi

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691997099722319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-08-24 04:41
I don't think this is a valid bug. Notifications received on a mobile device require explicit user action on that device to clear them.

**Comment by strepanier03** [comment] 2023-08-24 23:01
I agree with @akinwale. The only time my Android notifications get cleared is if I click them to read the new message. 

Otherwise, just reading it in the app does nothing, I still have to interact with the notification to clear it. I am also in favor of closing this as "not a bug".

**Comment by strepanier03** [comment] 2023-08-24 23:04
I commented in the Bug Report thread and for now I'm going to close this. If the thread results in a discussion that ends with a different opinion we can reopen it.

**Closed by strepanier03** 2023-08-24 23:04 UTC
Labels: Daily, Bug

**Comment by Victor-Nyagudi** [comment] 2023-08-25 05:27
I've added a [comment](https://expensify.slack.com/archives/C049HHMV9SM/p1692940896074369?thread_ts=1691997099.722319&cid=C049HHMV9SM) in the Slack thread explaining why I think this is a bug.

**Comment by Julesssss** [comment] 2023-08-29 08:08
Agree this isn't a bug. We haven't yet implemented this feature.
