### ISSUE TITLE
[$250] LHN - Expense preview and GBR still displayed in LHN after deleting expense in search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49297] opened 2024-09-16 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open the FAB.
3. Tap on "Submit Expense"
4. Tap on "Manual"
5. Complete the expense amount.
6. Tap on "Next"
7. Select a workspace to submit the expense to.
8. Add a merchant to the expense.
9. Tap on "Submit"
10. Once redirected to workspace chat. tap on the arrown on the top left corner.
11. Verify the chat preview displays the expense information and a green dot.
12. Tap on the search section on the bottom of the screen.
13. Select the just created expense.
14. Tap on "1 selected" on the top of the screen.
15. Tap on "Delete"
16. Return to LHN.
17. Verify if the expense details and the green dot, disappeared from the workspace chat preview.

## Expected Result:
Once the expense is deleted on the search section, the expense details and the green dot, should disappear from the workspace chat preview in LHN.

## Actual Result:
After the user deletes the just created expense on the search section, the workspace chat preview on LHN still displays the expense details and the Green Dot.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6605687_1726505284432!LHN_Delete](https://github.com/user-attachments/assets/e561b1ae-9df1-4519-919e-c2953741a24c)

https://github.com/user-attachments/assets/bfa03d25-294e-4ff0-ae2d-37ae045e1d6a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836835077314050335</li>
        <li>Upwork Job ID: 1836835077314050335</li>
        <li>Last Price Increase: 2024-09-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 20:06
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-09-16 20:06
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment] 2024-09-19 18:30
search related bug.

**Comment by JKobrynski** [comment] 2024-09-23 12:03
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by rojiphil** [comment] 2024-09-24 08:50
Tagging @luacmartins since this is a search related bug. 
A Callstack member would like to work on this issue as mentioned [here](https://github.com/Expensify/App/issues/49297#issuecomment-2368015683).
Can we assign and take this further?

**Comment by luacmartins** [comment] 2024-09-24 14:04
I think we can take proposals for this one.

**Comment by zanyrenney** [comment] 2024-09-26 11:15
Just an FYI I'll be OOO until Tuesday 1st, please reapply the bug label if this needs urgent action in my absence. Otherwise I will get to it when I return. Thanks!

**Comment by JKobrynski** [comment] 2024-09-26 11:32
This actually happens on all platforms, the only difference is that on the bigger screens (web and desktop) it quickly changes as the reports list is rendered in LHN, but for a brief moment you can see it's still there.

iOS


https://github.com/user-attachments/assets/db21f8ec-656b-4140-8081-d2de2e91f778

Web


https://github.com/user-attachments/assets/7fcbc2ac-d78f-4d5d-b259-16f30053e293

**Comment by rojiphil** [comment] 2024-09-30 14:16
@luacmartins I could also reproduce this issue on small screen platforms. And on digging a little deeper, the root cause is that the report's `lastMessageText` is not updated in Onyx to reflect the deletion of the money request via `DeleteMoneyRequestOnSearch` API request. That is why it is not updated in LHN. 

This could have been resolved if the BE response included the updated `lastMessageText` in report. So, I am wondering if this can be considered a BE issue. What do you think?

**Comment by JKobrynski** [comment] 2024-10-01 08:58
The reason why the Green Dot Indicator is shown, is the `ReportUtils.requiresAttentionFromCurrentUser()` that returns **true** in `<OptionRowLHN />`. It returns true because of the `hasOutstandingChildTask` field on the report that is not updated after the request is deleted from the search tab. 

Do you think this could also be fixed on the backend?

**Comment by rojiphil** [comment] 2024-10-01 10:21
> Do you think this could also be fixed on the backend?

@JKobrynski I think so if the response from BE includes the updated `report` as well. This will ensure that there is no discrepancy between FE and BE report and the FE UI will display correctly. Do you think this will fix the issue?

**Comment by JKobrynski** [comment] 2024-10-01 11:07
As far as I'm aware that should fix it.

**Comment by luacmartins** [comment] 2024-10-01 12:55
>And on digging a little deeper, the root cause is that the report's lastMessageText is not updated in Onyx to reflect the deletion of the money request via DeleteMoneyRequestOnSearch API request.

Interesting. The `DeleteMoneyRequestOnSearch` command calls the `DeleteMoneyRequest` command under the hood, so I'd expect the API response in both cases to be the same. Is that not the case?

**Comment by luacmartins** [comment] 2024-10-02 18:25
Ok, I started working on a PR to make those updates the same.

**Comment by luacmartins** [comment] 2024-10-09 18:13
PRs still in draft. I'll get back to them tomorrow.

**Comment by luacmartins** [comment] 2024-10-11 23:38
PR in review

**Comment by luacmartins** [comment] 2024-10-17 21:24
Closing since the PR was deployed.

**Closed** 2024-10-17 21:25 UTC
Labels: Reviewing, Daily, Internal, Bug
