### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] [Wave Collect] [Ideal Nav] Chat list scroll position is reset on refocus

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35602] opened 2024-02-01 23:07 UTC
## Action Performed:
1. Click the Chat Button on the bottom tab
2. Make sure that you have enough number of chats so that the list can be scrolled. Scroll the list to a random position.
3. Click Settings Icon 🔧 to go to Settings page. Click the Chat icon again to navigate back to Chats page.

## Expected Result:
The scroll position of the chat list should be preserved.

## Actual Result:
The scroll position is reset.

## Additional Note
As part of a potential solution, [we can make sure that we don't reload the chat/report list](https://github.com/Expensify/App/pull/33280#issuecomment-1921929113) when switching between Chat and Settings on the Bottom Tab.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

video -> https://github.com/Expensify/App/pull/33280#issuecomment-1885789713

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af2fb1053774c16b</li>
        <li>Upwork Job ID: 1754565125866393600</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-06 04:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are not able to remember the state of the chats in the home route, when navigating to the all-settings page.

### What is the root cause of that problem?
This is because BOTTOM_TAB_NAVIGATOR is responsible for both routes and can only display one at a time. When navigating to all-settings it will unmount the chats home route and it's chat components. 

### What changes do you think we should make in order to solve the problem?
We could move the all-settings route, and place it in our existing RIGHT_MODAL_NAVIGATOR. This Navigator can render alongside the BOTTOM_TAB_NAVIGATOR. this navigator is a modal that would overlay the home chats. So that when you close it would show the previous underlying state.

This implementation requires correct verification of back buttons, as there will be some deeplinking in all the nested navigation routes of all-settings. Overall not a small bug fix but rather a new feature.

### What alternative solutions did you explore? (Optional)

**Comment by hayata-suenaga** [comment] 2024-02-08 19:59
still accepting proposals

**Comment by adamgrzybowski** [comment] 2024-02-09 15:26
Hey @hayata-suenaga this task may be something I should take a look at

**Comment by hayata-suenaga** [comment] 2024-02-12 16:23
@adamgrzybowski will take a look at this

**Comment by hayata-suenaga** [comment] 2024-02-15 18:03
@adamgrzybowski is going to take a look at this when they have time

changing the priority to weekly for now

**Comment by hayata-suenaga** [comment] 2024-02-16 19:45
> Another performance issue was reported by David
> -> [internal Slack thread where David posted the issue](https://expensify.slack.com/archives/C05LX9D6E07/p1708110054496159)
> 
> 1. Make sure your account has several workspaces with a lot of chats/reports
> 2. Open the Chat Switcher (Search Page) by pressing CMD + K
> 3. Switch to a different chat/person (possibly one in a different workspace
> 4. Observe that the LHN that displays the list of chats loads very slowly

This is probably related more to [this issue](https://github.com/Expensify/App/issues/35704), but I wanted to keep you in the loop 🙇 (I also posted this issue in that GH ticket)

**Comment by hayata-suenaga** [comment] 2024-02-22 16:33
@adamgrzybowski is OOO. They will work on this once they're back

**Comment by adamgrzybowski** [comment] 2024-03-06 16:34
I am back and looking at it @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2024-04-08 22:04
@situchan could you do the checklist when you have time? 😄

**Comment by muttmuure** [comment] 2024-04-17 19:29
Will get to this tomorrow

**Comment by muttmuure** [comment] 2024-04-18 13:02
@situchan paid $500 for C+

**Comment by muttmuure** [comment] 2024-04-18 13:02
@situchan waiting for you to complete the checklist

**Comment by hayata-suenaga** [comment] 2024-04-18 17:38
@muttmuure, I think situation is OOO for whole April. Let's wait for them to come back. I changed the priority of this issue to weekly 🙇

**Comment by muttmuure** [comment] 2024-04-29 16:53
Not overdue

**Comment by muttmuure** [comment] 2024-05-08 07:04
Looks like this was already paid out

**Closed by muttmuure** 2024-05-08 07:04 UTC
Labels: External, Engineering, Weekly, Overdue, Awaiting Payment, Bug
