### ISSUE TITLE
[$250] Workspace - Members upgraded to admin doesn't have admin label

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46543] opened 2024-07-30 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nahummelaku9+d46@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to staging.new.expensify.com
2. Navigate to settings > Workspace > Create new
3. Navigate to Workspace setting > Members
4. Invite a few members to the workspace
5. Click on an invited member
6. Change the role of the member to "Admin"
7. Navigate to workspace rooms
8. Click on the header > Members

## Expected Result:
Members with roles updated Admin should have an admin label in the members list

## Actual Result:
Members with roles updated to Admin doesn't have labels in the members list from the head of room conversations

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4a58f805-6c13-4926-93c8-816bcbc114f8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01756c69e61a298287</li>
        <li>Upwork Job ID: 1821194427863490937</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103707716</li>
<li>FitseTLT | Contributor | 103707719</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by lanitochka17** [comment] 2024-07-30 20:59
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-07-30 21:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Members upgraded to admin doesn't have admin label

### What is the root cause of that problem?
We are only using the role of the participant on the report the show the badge
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L71-L72
not the role the participant has on the workspace
### What changes do you think we should make in order to solve the problem?

We can get role of the participants from the policy linked to the room or report whenever the report is `isDefaultRoom` or `isAnnounceRoom` (or another condition as we need). 
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L71-L72

So first we get the policy using `report.policyID` then from `employeeList` of the policy using the login of the participant we can get the `role`.

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-30 21:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Members upgraded to admin doesn't have admin label

### What is the root cause of that problem?
We are only using the role of the participant on the report the show the badge
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L70
not the role the participant has on the workspace
### What changes do you think we should make in order to solve the problem?

We can get role of the participants from the policy linked to the room or report whenever the report is `isDefaultRoom` or `isAnnounceRoom` (or another condition as we need). 
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L70
So first we get the policy using `report.policyID` then from `employeeList` of the policy using the login of the participant we can get the `role`.

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-30 21:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Members upgraded to admin doesn't have admin label

### What is the root cause of that problem?
We are only using the role of the participant on the report to show the badge
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L70
not the role the participant has on the linked workspace
### What changes do you think we should make in order to solve the problem?

We can get role of the participants from the policy linked to the room or report whenever the report is `isDefaultRoom` or `isAnnounceRoom` (or another condition as we need). 
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L70
So first we get the policy using `report.policyID` then from `employeeList` of the policy using the login of the participant we can get the `role`.

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-30 21:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Members upgraded to admin doesn't have admin label

### What is the root cause of that problem?
We are only using the role of the participant on the report to show the badge
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L70
not the role the participant has on the linked workspace
### What changes do you think we should make in order to solve the problem?

We can get role of the participants from the policy linked to the room or report whenever the report is `isDefaultRoom` or `isAnnounceRoom` also `isPolicyExpenseChat`(or another condition as we need). 
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/ReportParticipantsPage.tsx#L70
So first we get the policy using `report.policyID` then from `employeeList` of the policy using the login of the participant we can get the `role`.

### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-08-07 14:39
Added to wave-collect as polish. We have proposals ready for review.

**Comment by Tony-MK** [comment] 2024-08-07 17:09
Thanks for the review @ZhenjaHorbach.

The proposal you picked has the condition below 👇 and is not necessary and will lead to regressions. Can you check on this? 

> We can get role of the participants from the policy linked to the room or report whenever the report is isDefaultRoom or isAnnounceRoom also isPolicyExpenseChat(or another condition as we need

This is crucial and the main difference between my proposal and your preferred proposal.

Can you reconsider your review?

Thanks

**Comment by FitseTLT** [comment] 2024-08-07 17:49
> Thanks for the review @ZhenjaHorbach.
> 
> The proposal you picked has the condition below 👇 and is not necessary and will lead to regressions. Can you check on this?
> 
> > We can get role of the participants from the policy linked to the room or report whenever the report is isDefaultRoom or isAnnounceRoom also isPolicyExpenseChat(or another condition as we need
> 
> This is crucial and the main difference between my proposal and your preferred proposal.
> 
> Can you reconsider your review?
> 
> Thanks

I only mentioned the conditions because it is the announce room that is being tested in the video of the OP and still we don't know if we want to show the badge whenever the report has a polcy linked to it, we need to confirm that from internal engineer, that's why I said `(or another condition as we need` 👍

**Comment by deetergp** [comment] 2024-08-08 01:01
In the video, when we go to the #announce room, the Admin users already has the admin badge. Why do they have it where the other two do not?

**Comment by Tony-MK** [comment] 2024-08-08 07:46
> In the video, when we go to the #announce room, the Admin users already have the admin badge. Why do they have it where the other two do not?

This happens because the roles of the other two members in the `report.participants` are not admin-labeled but empty.

https://github.com/Expensify/App/blob/ec38b0508184b9ef00c368c7c5f7e583edfb0bef/src/pages/ReportParticipantsPage.tsx#L70

https://github.com/Expensify/App/blob/ec38b0508184b9ef00c368c7c5f7e583edfb0bef/src/pages/ReportParticipantsPage.tsx#L79

Therefore, the `ReportParticipantsPage` will only show the badge for the user who have the admin role.

**Comment by Tony-MK** [comment] 2024-08-08 10:22
@ZhenjaHorbach, I believe we should update the `report.particpants` optimistically.

However, wouldn't this solution require also a backend fix as well?

**Comment by FitseTLT** [comment] 2024-08-08 12:20
>While writing the explanation I realized that as an alternative to the previous proposals we can update updateWorkspaceMembersRole and in addition to employeeList we can update participants for chat reports😅

That would involve BE changes and more work if we want to label all policy rooms and so on. I think the FE [changes](https://github.com/Expensify/App/issues/46543#issuecomment-2259263270) suggested to use role from employeeList is flexible and appropriate to deal with the current issue.

**Comment by deetergp** [comment] 2024-08-08 18:12
Actually, I think maybe the right thing to do here is get rid of the one `admin` label in policy rooms altogether. @JmillsExpensify do you have a strong opinion on this? I'm looking at the `#announce` room for the Expensify Chat policy with 99 people in it and not one of them is labeled `Admin`.

**Comment by FitseTLT** [comment] 2024-08-08 21:48
[Updated](https://github.com/Expensify/App/issues/46543#issuecomment-2259263270) Proposal with alternative solution which is to remove the optimistic role we are setting that doesn't align with the data the server is sending.

**Comment by deetergp** [comment] 2024-08-27 18:56
@ZhenjaHorbach I don't think we need to block on @JmillsExpensify, Let's just drop it altogether since new users never see it  and it isn't being sent by the server.

**Comment by JmillsExpensify** [comment] 2024-08-28 21:20
Apologies ya'll. I never got the notifications. Catching up now.

**Comment by JmillsExpensify** [comment] 2024-08-28 21:29
Alright, so thinking on this, I think I'm ok with your conclusion. Capturing my logic in case this comes up later: 

 - This change makes the "workspace member profile" the source of truth for who's an admin and who isn't
 - In the future, on an individuals personal profile, we're going to include a link to the workspace that any two individuals show together (it doesn't matter whether they are a `member` or `admin`). As part of linking to the workspace, it's possible to easily see the "workspace member profile."
  - Finally, plenty of chat apps don't show who and who isn't an admin in the member list, so I think you could argue that either showing it or not showing it works. Further, any member of a workspace can find the "owner" of the workspace, who's the ultimate "admin" if that piece of information is useful in practice for anyone.

**Comment by JmillsExpensify** [comment] 2024-08-28 21:29
Final question on the implementation: Are we going to go this consistently, across all room/chat types? Or just certain types?

**Comment by ZhenjaHorbach** [comment] 2024-09-10 17:02
BugZero Checklist

> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@ZhenjaHorbach] The PR that introduced the bug has been identified. Link to the PR:

Unfortunately, I did not find a suitable PR

> * [x]  [ @ZhenjaHorbach] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

NA

> * [x]  [@ZhenjaHorbach] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

NA

> * [x]  [@ZhenjaHorbach] Determine if we should create a regression test for this bug.
> * [x]  [@ZhenjaHorbach] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

- Login to staging.new.expensify.com
- Navigate to settings > Workspace > Create new
- Navigate to Workspace setting > Members
- Invite a few members to the workspace
- Navigate to workspace rooms (#announce or #admin)
- Click on the header > Members
- Verify that admin label is not shown on any of the members

Do we agree 👍 or 👎

**Comment by deetergp** [comment] 2024-09-10 18:20
Your regression test proposal looks good to me @ZhenjaHorbach 👍

**Comment by ZhenjaHorbach** [comment] 2024-09-10 18:34
@JmillsExpensify 
We are ready for payment !

https://github.com/Expensify/App/pull/48222#issuecomment-2325378403
<img width="612" alt="Снимок экрана 2024-09-10 в 20 33 36" src="https://github.com/user-attachments/assets/d2ef3706-4b0c-4f54-8a86-5612de5364bc">

**Comment by JmillsExpensify** [comment] 2024-09-11 21:08
Payment summary:

 - Contributor: @FitseTLT $250
 - Reviewer: @ZhenjaHorbach $250

**Comment by JmillsExpensify** [comment] 2024-09-11 21:13
Contributor contracts paid via Upwork and regression test created. Closing this one!

**Closed by JmillsExpensify** 2024-09-11 21:13 UTC
Labels: Reviewing, External, Weekly, Bug
