### ISSUE TITLE
[HOLD] Latest chat isn't showing in LHN after refresh

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10629] opened 2022-08-29 04:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Select chat with user B in NewDot
2. Ask user A to send you a message in 15 seconds
3. Close laptop lid
4. Notice new message shows on phone (or email)
5. Open computer
 
## Expected Result:
New message from user A to show in LHN  

## Actual Result:
Open lid, new chat doesn't show from user A in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="523" alt="image - 2022-08-29T000340 673" src="https://user-images.githubusercontent.com/43995119/187120987-7df347b5-4342-4313-945c-1ce2094eaea0.png">
[LHN still not updating.txt](https://github.com/Expensify/App/files/9441481/LHN.still.not.updating.txt)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661529262234949?thread_ts=1660913217.196589&cid=C01GTK53T8Q
https://expensify.slack.com/archives/C01GTK53T8Q/p1660897671083959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-08-29 09:33
@mvtglobally 

This looks like a nasty one. So the image shown definitely shows that its not showing the message in the LHN. Thats something we need to fix. 


And for the next part, when you say:
> Only seeing three chats in LHN and searching for users doesn't return anyone except the three users in LHN

I can't see on the image, but the left side only shows 3 users? It might be difficult, but can you get a video by chance?

**Comment by mallenexpensify** [comment] 2022-08-29 22:56
Updated OP with repro steps but... put on hold cuz I wasn't able to reproduce now and also running into an issue where chats are showing but new ones aren't bold.  
https://expensify.slack.com/archives/C01GTK53T8Q/p1661807702326749

**Comment by mallenexpensify** [comment] 2022-09-07 16:22
Still sussing out core issue and seeing if other issues are related

**Comment by mallenexpensify** [comment] 2022-09-07 19:13
Wasn't able to reproduce, just tested and message shows in LHN (and bold) in LHN when I opened laptop
<img width="404" alt="image" src="https://user-images.githubusercontent.com/22508304/188958699-d1eb7be4-ffec-42c8-aa9a-70d6fab36e26.png">

**Comment by mallenexpensify** [comment] 2022-09-07 22:45
Tried to reproduce 3 times today with no luck.  There are other existing issues with chats not showing or not being bolded, but this issue and/or the repro steps in the OP here are different. New issues should be created for the other issues, if they haven't been already

**Comment by marcaaron** [comment] 2022-09-08 07:43
I think this is related to https://github.com/Expensify/Expensify/issues/227410 but not entirely sure.

**Comment by mallenexpensify** [comment] 2022-09-15 00:06
Tested and unable to reproduce. Thinking/hoping https://github.com/Expensify/Expensify/issues/227410 fixed it so closing for now

**Closed by mallenexpensify** 2022-09-15 00:06 UTC
Labels: Weekly, Improvement, Internal
