### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Room settings - Edit room name tab is cut if edit and re-open it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22271] opened 2023-07-05 15:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/r/8721544721767866
2. Open a room chat
3. Click on room header to open "details"
4. Click on "Settings"
5. Click on "Room name"
6. Edit room name
7. Click on "Save"
8. Click on "Room name"
9. Repeat steps "6-8" several more times if the issue doesn't reproduce

## Expected Result:
"Edit room name" tab is completely visible after opening

## Actual Result:
"Edit room name" tab is shifted to the left and is partially cut
Issue is both reproducible offline and online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / ~Chrome~ / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6117297_Screenshot_2023-07-05_at_19 03 58](https://github.com/Expensify/App/assets/78819774/79c5afe3-1ea1-4bc2-b131-7523bad61253)

https://github.com/Expensify/App/assets/78819774/a3207e05-3d22-48b4-bf99-30e6538c9935

**Expensify/Expensify Issue URL:**

**Issue reported by:**  Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b1530b30a801399</li>
        <li>Upwork Job ID: 1676716588882231296</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-05 22:15
Yup, this is reproducible but only on Web Safari for me: 

<img width="1497" alt="image" src="https://github.com/Expensify/App/assets/16232057/d3d636c9-f137-4a1c-b95f-ff685fcb4fc6">

**Comment by b4s36t4** [comment] 2023-07-05 23:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room settings - Edit room name tab is cut if edit and re-open it
### What is the root cause of that problem?

Edit Room name page contains an Input which is auto-focusing itself. 
The Input is getting autofoucs without the completion of page rendering which is the main reason for this.
I see In safari the transition is getting half ended because of auto-focus. If you observe in chrome/firefox there won't be any transition cause of auto foucs.

https://github.com/Expensify/App/blob/7036597524476c8fe7c2baaff2047a568143c0c1/src/pages/settings/Report/RoomNamePage.js#L86
This autoFocus prop causing the issue.

### What changes do you think we should make in order to solve the problem?

We should delay the auto-focus so that by then Edit room page is full rendered.

## Changes Needed
Add `shouldDelayFocus` prop inside `RoomNamePage.js` and Pass `shouldDelayFocus` prop to `BaseInput` inside `RoomNameInput.js`

Here -> https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/components/RoomNameInput/index.js#L62

Fix Implementation Demo:

https://github.com/Expensify/App/assets/59088937/dd91eb24-d7d2-4172-8df1-19913d5f3862


### What alternative solutions did you explore? (Optional)
NA

**Comment by trjExpensify** [comment] 2023-07-07 10:37
@Santhosh-Sellavel let us know what you think! 

>We should not use shouldDelayFocus because it's a hack that use timeout.

❤️

**Comment by b4s36t4** [comment] 2023-07-07 11:25
I feel autofocus and shouldDelay focus are been there because we don't have to messup with the ref. I we want to take control of the focusing of an then I feel autoFocus prop doesn't have a meaning. Maybe we should consider a singular approach meaning to go with only one way.

**Comment by b4s36t4** [comment] 2023-07-07 18:58
@hoangzinh yes if I refresh the page input is not getting auto focus. Tried below method [Image 1] it did worked out pretty well in foucinsg. But it did thrown an error [Image 2]. Maybe going with `shouldDelayFocus`?

<img width="680" alt="Screenshot 2023-07-08 at 12 24 20 AM" src="https://github.com/Expensify/App/assets/59088937/6a7a17ca-f3d6-46a7-be9c-1baca90d8d65">
<img width="483" alt="Screenshot 2023-07-08 at 12 27 04 AM" src="https://github.com/Expensify/App/assets/59088937/61d3ce08-62fa-457f-a8c8-69ee06c91deb">

**Comment by Santhosh-Sellavel** [comment] 2023-07-09 20:26
@trjExpensify Can you assign a new C+ to take over this, as I'm low on bandwidth, thanks!

**Comment by trjExpensify** [comment] 2023-07-10 10:47
Sure! It's good to ask in C+ for someone else to take over btw. Done that [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1688986028381969).

**Comment by roryabraham** [comment] 2023-07-11 01:12
Thanks for the collaboration here everyone! @tienifr's proposal LGTM too 👍🏼

**Comment by bfitzexpensify** [comment] 2023-07-18 17:42
Seems like https://github.com/Expensify/App/issues/22973 might be a regression caused by the fix here - finding that the room name isn't brought into focus when using a deep link to access this settings page. No issue in Chrome but I can reliably reproduce in Safari cc @tienifr

**Comment by bfitzexpensify** [comment] 2023-07-18 17:55
Nice, thanks for the context @allroundexperts

**Comment by trjExpensify** [comment] 2023-07-21 16:21
Thanks, @allroundexperts! 

>Seems like we forgot to take into account the page transitions when auto focusing inputs. We are actively fixing all other instances of this issue as well.

Just on this. Do you think it could be avoided again in the future though, and perhaps be worthwhile documenting somewhere to make sure we don't forget going forward?

**Comment by trjExpensify** [comment] 2023-07-21 16:29
Confirming payment offers sent: 

- $1,500 - @tienifr for the fix + #urgency bonus 
- $1,500 - @allroundexperts for the C+ review + #urgency bonus

**Comment by trjExpensify** [comment] 2023-07-21 16:31
>I think we can add this into our Form guidelines. But in order to do that, we might need a consensus on what's the best way to focus an input. Right now, we're using shouldDelayFocus, InteractionManager.runAfterInteractions and onTransitionEnd property to trigger the focus.

Okay, so let's maybe have that discussion? Otherwise I think this is likely just going to crop up again for the next time we add a form etc.

**Comment by anmurali** [comment] 2023-07-23 07:42
Approved 1500 to Sibtain based on https://github.com/Expensify/App/issues/22271#issuecomment-1645950208

**Comment by trjExpensify** [comment] 2023-07-24 11:11
>Also, can you please withdraw the Upwork offer? I'll be getting paid through the app.

I'm getting 404s when I try to access the offer page. I've gone ahead and closed the job though anyhow. 

>Posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1689957344255689)

Thanks, let's keep the discussion going there 👍 

Everyone is paid, closing!

**Closed by trjExpensify** 2023-07-24 11:11 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
