### ISSUE TITLE
Dev: Web - Unable to send the PDF file, nothing happens on click of send button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22762] opened 2023-07-12 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Choose any PDF file
3. Click on send button

## Expected Result:
Able to send the PDF file, send button works
## Actual Result:
Unable to send the PDF file, nothing happens on click of send button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ced3fb0b-2202-4005-93ed-1c4bdc9dcd59

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689146586650129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-07-12 18:52
Will be fixed with https://github.com/Expensify/App/issues/22750#issuecomment-1632638487

**Comment by gadhiyamanan** [comment] 2023-07-13 05:27
@Pujan92 both are different issue

**Comment by gadhiyamanan** [comment] 2023-07-13 15:03
@multijump the proposal is correct for this  issue but the issue is different and according to https://github.com/Expensify/App/issues/22750#issue-1801057177, other issues is reproducible in production also and this issue is reproducible in dev

**Comment by Pujan92** [comment] 2023-07-13 19:17
> @multijump the proposal is correct for this issue but the issue is different and according to [#22750 (comment)](https://github.com/Expensify/App/issues/22750#issue-1801057177), other issues is reproducible in production also and this issue is reproducible in dev

@gadhiyamanan maybe by mistake they checked the production but it is not reproducible in the prod. So once this [PR](https://github.com/Expensify/App/pull/22836) gets merged this issue won't be exist.
<img width="1440" alt="Screenshot 2023-07-14 at 12 45 25 AM" src="https://github.com/Expensify/App/assets/14358475/60458641-2bbf-41d5-bb06-de09a939dd25">

**Comment by gadhiyamanan** [comment] 2023-07-14 04:55
@Pujan92 still I think both issues are different and your [PR](https://github.com/Expensify/App/pull/22836) will solve this issue https://github.com/Expensify/App/issues/22762

Here are the two reasons why I think both are different issues:

1. Another issue  https://github.com/Expensify/App/issues/22750 is reproducible in production(as per attachment added and i am not able to reproduce that issue ) and this issue is only reproducible in DEV

2. in [another issue](https://github.com/Expensify/App/issues/22750) receiver receives the message as per the attachment and in this issue receiver didn't receive the message 

<details> 
  <summary>Video which shows that receiver didn't receive message</summary>
https://github.com/Expensify/App/assets/54790231/25bf6c80-0770-4748-8218-c21feef237ba
</details>

3. I can't see the ` Uploading attachment...` message on click of send button with this issue as the user is not able to send a message and in [another issue](https://github.com/Expensify/App/issues/22750) ` Uploading attachment...` message shows as per attachment

@Julesssss what's your thought as you reported the issue https://github.com/Expensify/App/issues/22750 

Note: I am not able to reproduce https://github.com/Expensify/App/issues/22750 in production or staging and @Pujan92 's  [PR](https://github.com/Expensify/App/pull/22836) will solve this issue but not sure about  https://github.com/Expensify/App/issues/22750

**Comment by sakluger** [comment] 2023-07-18 18:06
How about we put this one on hold until https://github.com/Expensify/App/issues/23000 is deployed? That way we can verify if it fixes this one as well.

**Comment by gadhiyamanan** [comment] 2023-07-18 19:14
@sakluger it fixed by https://github.com/Expensify/App/pull/22836

**Comment by sakluger** [comment] 2023-07-21 02:12
That's great that it was fixed by that other issue 🎉 ! It looks like you reported this a few hours before @Julesssss created https://github.com/Expensify/App/issues/22750, so I think that you should get credit for the reporting bonus. I'll comment on that other issue so that you can get paid out the reporting bonus for that one.

**Comment by sakluger** [comment] 2023-07-21 02:14
I'm going to close this issue since it's fixed. I commented on the other issue asking that you get the reporting bonus.

**Closed by sakluger** 2023-07-21 02:14 UTC
Labels: Daily, Needs Reproduction, Bug
