### ISSUE TITLE
[$500] Mweb - Search - When user enters a text in search it shows loading symbol

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29633] opened 2023-10-14 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap send message
4. Enter a text

## Expected Result:
When user enters a text in search, it must not show loading symbol

## Actual Result:
When user enters a text in search, it shows loading symbol

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

  

https://github.com/Expensify/App/assets/78819774/c7fad19a-a472-4eb9-8c08-bc809d44fcd5

https://github.com/Expensify/App/assets/78819774/d6e5feb5-cbff-4706-bd1e-ec2bbe149374

![Bug6237344_1697314796770!Screenshot_2023-10-15-01-49-44-279_com android chrome](https://github.com/Expensify/App/assets/78819774/72873c0c-0462-46db-99fb-30ee624da2c3)

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fa65b305eb408fc</li>
        <li>Upwork Job ID: 1714096811092811776</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-10-17 01:51
Adding labels to get reviews on the proposal.

**Comment by eh2077** [comment] 2023-10-17 02:08
@stephanieelliott I think this is a new feature from PR https://github.com/Expensify/App/pull/27819. If it's a bug, can you help to clarify what the expected behaviour is?

**Comment by Santhosh-Sellavel** [comment] 2023-10-17 19:57
@stephanieelliott Seems like this is the expected behavior from https://github.com/Expensify/App/pull/27819

cc: @marcaaron @Beamanator Can you close this one if so, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-10-17 20:20
@Krishna2323 It's there already in the comment. Seems intentional
// we want to show the loading state right away.

**Comment by marcaaron** [comment] 2023-10-18 01:08
This is a feature not a bug.

**Comment by marcaaron** [comment] 2023-10-18 01:09
>@Santhosh-Sellavel, the loader is expected but it appears while typing. it should appear once loading is started.

Nope. It shows as soon as you start typing.

**Closed by marcaaron** 2023-10-18 01:08 UTC
Labels: External, Daily, Help Wanted, Bug
