### ISSUE TITLE
[$250] mweb Safari - Workspace - "Invite members" button is hidden by keyboard and user needs to tap "Done"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8507] opened 2022-04-06 14:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: Have a workspace already created
1. Access [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)[](javascript:)
2. Sign in with an applause.expensifail.com account
3. Tap on the profile icon on the top right
4. Tap "Workspace"
5. Scroll down and tap "Manage Members"
6. Tap on "Invite"
7. Tap on the "Search" bar and type in any user you have access to
8. Tap "Done"

## Expected Result:
The user expects to be able to see the "invite" button and the "Add personal message" text box after searching for an user

## Actual Result:
The "invite" button and the "Add personal message" text box is hidden by the pop up keyboard, therefore the user needs to tap "Done" so that it is visible

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Mobile Web (Safari)

**Version Number:** 1.1.51-0 - 1.1.54-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/161995947-d9ff4073-b0e4-4ab1-b609-e2901a5f4644.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-04-06 18:36
@kbecciv can you please explain what the actual issue is here? From the video, it looks like everything is working as we would expect. When the user clicks a user to invite to the workspace, then clicks "Done" on the keyboard, it looks like the keyboard hid as expected right?

**Comment by kbecciv** [comment] 2022-04-07 23:46
@Beamanator We want to check if this issue is expected if user will click "done" on the keyboard for seen the invite button. Or keyboard should dismissed and "Invite" button is visible after select a user.

**Comment by Beamanator** [comment] 2022-04-08 16:41
Aah thanks for the clarification @kbecciv - on the android app & mobile web (Chrome) I'm seeing the invite button & "Add a personal message" text box float above the keyboard, which is what we're thinking we should see in Safari in this issue, I believe

**Comment by kbecciv** [comment] 2022-04-08 17:39
@Beamanator Yes, we are seeing this issue in Safari.

**Comment by Beamanator** [comment] 2022-04-08 18:51
Thanks @kbecciv - it's useful to know if the issue is only happening in 1 platform, which is why I added that note to the issue title & to the original post :D

**Comment by Beamanator** [comment] 2022-04-11 21:45
Not overdue, just waiting to be exported :D

**Comment by Beamanator** [comment] 2022-04-14 22:44
Still waitin 😅 

Bump @stephanieelliott

**Comment by stephanieelliott** [comment] 2022-04-14 23:40
Oop sorry, I've been at a conference! 

Exported to Upwork: https://www.upwork.com/jobs/~015cbd0907cf5b8a05

**Comment by parasharrajat** [comment] 2022-04-15 06:02
I don't think we can fix this. I have mentioned this quite a few times that we can't have fixed button on the mWeb(Safari). I request QA team to take a note of this for future. cc: @Beamanator

**Comment by Beamanator** [comment] 2022-04-15 17:14
That does sound a bit familiar @parasharrajat 

How would you suggest we best keep people informed of this limitation? Is it documented somewhere already? If not, maybe it should be?

**Comment by Beamanator** [comment] 2022-04-15 17:14
Removing Help Wanted for now since it's likely this can't be fixed

**Comment by parasharrajat** [comment] 2022-04-15 17:19
I don't think this is documented somewhere. Currently, the safari M-web flexbox does not work the same as other browsers. But yeah, it would be good to document it or track it somewhere so if there is a solution to it, we can apply that.

**Comment by Beamanator** [comment] 2022-04-15 20:43
Would you mind trying to find some other resources showing Safari M-Web Flexbox doesn't work / doesn't work for our needs? Maybe other GH issues in this repo that you've seen? If you could do that & present an idea for documenting / tracking in #expensify-open-source I think we can compensate you $250 as if it's a normal job

**Comment by isagoico** [comment] 2022-04-19 16:25
To avoid reporting this in the future I have added the issue to our Applause Platform Known Issues List and will also inform the Team Leads on the matter.

**Comment by parasharrajat** [comment] 2022-04-19 17:53
I will look into this @Beamanator.

**Comment by stephanieelliott** [comment] 2022-04-26 14:48
Seeing as this issue is something we're not able to fix at the moment I'm gonna close this. Feel free to reopen if you disagree! Otherwise, let's bring the discussion re: future documentation to #expensify-open-source and then open a separate issue if it's needed.

**Closed by stephanieelliott** 2022-04-26 14:48 UTC
Labels: Exported, External, Engineering, Weekly

**Comment by Beamanator** [comment] 2022-04-26 15:03
That sounds like a good plan, thanks @stephanieelliott 👍
