### ISSUE TITLE
[HOLD][$250] Send Attachment - Pressing  "X" on attachment preview using on screen keyboard still uploading attachment reported by @syedsaroshfarrukhdot 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12372] opened 2022-11-02 15:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Chat Of Any User
2. Send An Attachment
3. Attachment Preview With In Modal Appears
4. Press `Tab ` to get `X` icon  highlighted using on screen keyboard
5. Press Enter

## Expected Result: 
The Attachment Should Not Upload

## Actual Result: 
The Attachment Still Uploads

NOTE: It works fine with laptop keyboard

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.22-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199531180-44c46a1a-b9ef-414c-9607-33bfa593ff83.mp4

https://user-images.githubusercontent.com/43996225/199531216-3fb1cf1b-3bbb-4cdb-8a45-84131a6e9285.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @syedsaroshfarrukhdot 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667346365313639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-02 16:10
### Proposal

I figured out the issue is because of `pressOnEnter` on `Send` Button in `AttachmentModal.js`

https://github.com/Expensify/App/blob/e5d766115babfe4fed51b97e8b7f65b6bec64f21/src/components/AttachmentModal.js#L277-L285

Removing It Solves The Issue But I Believe We Need To Figure Out Enter Key Accessibility In This Modal As `pressOnEnter` props Registers A Keyboard Shortcut For `Enter Key`  And When Navigating Via `Tab Key` To Other `Button` And `Links` In The Modal It Still Sends The Attachment With `Enter Key` Due To The Props Being Passed To The `Send Button`.

After Fix:-

https://user-images.githubusercontent.com/81307212/199540268-2e6ffa72-ed3d-4a85-947d-44668a86713a.mov

**Comment by lschurr** [comment] 2022-11-02 20:02
Tab + X doesn't do anything for me. Should that stop an attachment from uploading? Tagging Eng for another pair of triaging eyes on this.

**Comment by flodnv** [comment] 2022-11-03 08:43
Looks like this is a problem only with a virtual keyboard.

**Comment by flodnv** [comment] 2022-11-03 08:43
@lschurr it's Tab + Enter.

**Comment by flodnv** [comment] 2022-11-03 08:44
>But I Believe We Need To Figure Out Enter Key Accessibility In This Modal 

@syedsaroshfarrukhdot what do you mean exactly?

**Comment by flodnv** [comment] 2022-11-03 08:44
@Santhosh-Sellavel can you please review @syedsaroshfarrukhdot's proposal?

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-03 11:53
> > But I Believe We Need To Figure Out Enter Key Accessibility In This Modal
> 
> @syedsaroshfarrukhdot what do you mean exactly?

@flodnv I meant we need to first identify does keyboard `Enter Key` in this modal needs to send the attachment or pressing `Tab Key` and navigating to `Send Button` then pressing keyboard `Enter Key` should send attachment.

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-03 12:00
> Looks like this is a problem only with a virtual keyboard.

@flodnv I am able to reproduce it with `Physical Keyboard` not only `Virtual Keyboard` on `Production` can you please test again and update reproduction steps.
 
https://user-images.githubusercontent.com/81307212/199714614-a425073e-509f-4f10-9abc-baa7189d3e64.mov

**Comment by Santhosh-Sellavel** [comment] 2022-11-03 13:58
@flodnv Requesting put this on hold it's related to https://github.com/Expensify/App/issues/7968, as the root problem is pressing enter should perform button action when it's focused instead of "press enter" to submit action!

**Comment by flodnv** [comment] 2022-11-03 15:27
Excellent, thanks for the great eyes and suggestion!

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-24 06:57
@flodnv Am I eligible for reporting bonus here ?

**Comment by flodnv** [comment] 2022-11-24 09:00
Ah yeah we're closing this because it's not something we're interested in fixing at the moment.

I am not sure if you're eligible. @lschurr ?

**Comment by lschurr** [comment] 2022-11-28 17:10
Asked here - https://expensify.slack.com/archives/C01SKUP7QR0/p1669655418032769

**Comment by lschurr** [comment] 2022-11-28 17:30
Confirmed that since this is on hold/we won't be fixing, we won't be issuing payment. See [this section](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions) of the contributing guide.

**Comment by lschurr** [comment] 2022-11-28 17:30
Should this be closed @flodnv?

**Closed** 2022-11-29 10:44 UTC
Labels: External, Engineering, Monthly, Help Wanted, Bug
