### ISSUE TITLE
Search - "You appear to be offline" shown briefly before expenses appear when internet is off

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49406] opened 2024-09-18 17:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Turn off internet connection.
3. Navigate to search section.
4. Verifiy the expenses list is automatically displayed.

## Expected Result:
When navigating to search section, the expenses list should be automatically displayed, despite the user being in offline mode.

## Actual Result:
"You appear to be offline. This feature requires an active internet connection" message is displayed for a second, when navigating to search after turning internet connection off.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6607869_1726677031644!Offline_Search](https://github.com/user-attachments/assets/2e0c370b-9431-43aa-8a8f-fc9b1c32a84e)

https://github.com/user-attachments/assets/05c4929a-33c0-439b-9d9f-d978b1df54d8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-18 17:16
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-09-19 00:36
This is the intended behavior. Closing.

**Closed by luacmartins** 2024-09-19 00:36 UTC
Labels: Daily, Bug
