### ISSUE TITLE
[HOLD for payment 2024-05-08] [$250] Profile - Display name is not updating in "Share Somewhere" section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39607] opened 2024-04-04 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Profile.
2. Add or change the Display name.
3. Use FAB to assign a task.
4. Add a title and click "Next" to share somewhere.
5. Notice that the Display name isn't updated for the account email (email signed in).

## Expected Result:
When the Display name is changed, it should be updated in the "Share Somewhere" section for the account email (email signed in).

## Actual Result:
Display name is not updating in "Share Somewhere" section

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1e13bf7f-505d-4c75-b5b4-9d7fa56c5c3e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109207e4c67cd7686</li>
        <li>Upwork Job ID: 1776016111925432320</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by kbecciv** [comment] 2024-04-04 14:11
We think that this bug might be related to #vip-vsb

**Comment by bondydaa** [comment] 2024-04-04 18:20
I'm looking into this, nothing in the checklist stands out to me that might be something that broke this so having to dive into the code and see what exactly gets called.

**Comment by bondydaa** [comment] 2024-04-04 19:31
okay i don't think it's a problem with the API, i see the response coming back properly with the updated data 
![image](https://github.com/Expensify/App/assets/4073354/b2dc35d0-7da3-4aa8-9c31-c4398377cef6)

And I see in the onyx db that it's been updated there 
![image](https://github.com/Expensify/App/assets/4073354/1acd6beb-0fbc-4ee7-bb6c-cce9048930d8)

So this makes me think that for some reason the `Share Somewhere` component isn't properly subscribing to the onyx data or something so going to take a closer look at that.

**Comment by bondydaa** [comment] 2024-04-04 19:35
Hmm this PR is sus to me after looking at the components involved here: https://github.com/Expensify/App/pull/38207/

**Comment by bondydaa** [comment] 2024-04-04 20:17
okay yes I believe I've confirmed this by testing locally. 

checking out `1.4.60-1` locally I see the same behavior and then reverting it I can't reproduce it anymore. 

cc @grgia @hungvu193 @TMisiukiewicz can you take a look here?

**Comment by bondydaa** [comment] 2024-04-04 20:28
I guess what we need is a way to invalidate the option list cache when personal details are updated, if there is a way to do that in the PR can you let me know?

or if that's still to come then maybe we consider this not a blocker?

makes me think of my favorite tweet 😂 https://twitter.com/codinghorror/status/506010907021828096

**Comment by jasperhuangg** [comment] 2024-04-04 21:03
@bondydaa This seems like a pretty minor bug–and since we've already narrowed down which PR it's coming from I think we can just mark it NAB and have @TMisiukiewicz look into a fix

**Comment by bondydaa** [comment] 2024-04-04 21:35
alrighty, this might not be limited to only the Share Somewhere option so it the option list for many of the places updated in that PR could fail to properly update with new personal data. 

I do agree it's probably fairly minor for now and can be fixed in a follow up PR though.

**Comment by bondydaa** [comment] 2024-04-04 22:36
Chatted with Vit as well and we can also let this go through as external I think so throwing the label on. going to assign @hungvu193 as well though since you helped with the first PR.

**Comment by nkdengineer** [comment] 2024-04-05 04:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Display name is not updating in "Share Somewhere" section

### What is the root cause of that problem?
In here we have two `useEffect` to update the options when `reports` or `personalDetails` is changed. In this case, the self DM is a report option and when we change the display name, only `personalDetails` is changed and we only change the personal details option when it's changed so the report option isn't update.

https://github.com/Expensify/App/blob/860998b443d777995d56105db09e346b25ed7196/src/components/OptionListContextProvider.tsx#L47

https://github.com/Expensify/App/blob/860998b443d777995d56105db09e346b25ed7196/src/components/OptionListContextProvider.tsx#L74
### What changes do you think we should make in order to solve the problem?
In this useEffect, we should detect the personal that is changed and then update all related report options that contain this personal detail as participant.

https://github.com/Expensify/App/blob/860998b443d777995d56105db09e346b25ed7196/src/components/OptionListContextProvider.tsx#L74


1. Create a ref for `personalDetails`

```
const prevPersonalDetails = useRef(personalDetails);
```

2. In this useEffect, find the changed personal detail and update the related report option

```
let newReportOptions: {
    replaceIndex: number,
    newReportOption: OptionsListUtils.SearchOption<Report>
}[] = [];
Object.keys(personalDetails).forEach(accoutID => {
    if (deepEqual(personalDetails[accoutID], prevPersonalDetails.current[accoutID])) {
        return;
    }

    Object.values(reports ?? {}).filter((report) => report?.participantAccountIDs?.includes(Number(accoutID))).forEach(report => {
        if (!report) {
            return;
        }
        const newReportOption = OptionsListUtils.createOptionFromReport(report, personalDetails);
        const replaceIndex = options.reports.findIndex((option) => option.reportID === report.reportID);
        newReportOptions.push({
            newReportOption,
            replaceIndex
        })
    })
})
setOptions((prevOptions) => {
    const newOptions = {...prevOptions};
    newOptions.personalDetails = newPersonalDetailsOptions;
    newReportOptions.forEach(newReportOption => newOptions.reports[newReportOption.replaceIndex] = newReportOption.newReportOption)
    return newOptions;
});

prevPersonalDetails.current = personalDetails;
```


https://github.com/Expensify/App/blob/860998b443d777995d56105db09e346b25ed7196/src/components/OptionListContextProvider.tsx#L74
### What alternative solutions did you explore? (Optional)
NA

**Comment by hungvu193** [comment] 2024-04-05 10:11
I have some other higher priority issues to review. I'll review this tomorrow morning.

**Comment by tamachai** [comment] 2024-04-05 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report for personal details does not get updated due to state/reactivity issue.

### What is the root cause of that problem?

`OptionsListContextProvider` fails to rebuild the self DM report when personal details are updated.

### What changes do you think we should make in order to solve the problem?

- Make a call to `useEffect` with a dependency list containing only `[personalDetails]`. Update the self DM report as part of the effect.

```typescript
useEffect(() => {
    const selfDMReportId = ReportUtils.findSelfDMReportID();
    if (!selfDMReportId) {
        return;
    }

    setOptions({
        ...options,
        reports: options.reports.map((report) => {
            if (report.reportID === selfDMReportId) {
                return OptionsListUtils.createOptionFromReport(report, personalDetails);
            }

            return report;
        }),
    });
}, [personalDetails]);
```

### What alternative solutions did you explore? (Optional)

**Comment by hungvu193** [comment] 2024-04-08 08:39
Thanks for proposals everyone,
 @tamachai your RCA is not clear also your solution didn't work.

@nkdengineer Your RCA is correct, however your solution didn't work when user changed the policy room name. You're trying to update the second useEffect, in this case the first useEffect was trigged.

https://github.com/Expensify/App/assets/16502320/d6ca233c-247e-45d3-b465-c7bc16c508e7

**Comment by nkdengineer** [comment] 2024-04-08 08:47
> however your solution didn't work when user changed the policy room name. You're trying to update the second useEffect, in this case the first useEffect was trigged.


@hungvu193 Thanks for your feedback but I think this case isn't related to this issue. This issue is the case when the personal detail is changed meanwhile the case that you mentioned above is the policy is changed. If we want to fix that we should subscribe the policy and get the `latestUpdatePolicy` as we do for report and then updated all related reports of this workspace.

**Comment by hungvu193** [comment] 2024-04-08 08:49
Hey @bondydaa can you confirm the expected behavior here? Should we also fix the issue where policy is not updating here or treat it as a separate issue?

**Comment by bondydaa** [comment] 2024-04-10 23:37
hmm I think keeping it limited to the display name is probably best (scope creep). We can spin up another bug for the policy/workspace names.

**Comment by hungvu193** [comment] 2024-04-11 16:02
I'll give my decision tomorrow morning.

**Comment by hungvu193** [comment] 2024-04-12 07:28
@nkdengineer 's [proposal here](https://github.com/Expensify/App/issues/39607#issuecomment-2038912998) looks good to me. Just one question, because I think 2 nested loops are quite expensive, do you have any optimization for it, ie: early return if it's not self DM?

**Comment by nkdengineer** [comment] 2024-04-12 08:03
@hungvu193

> because I think 2 nested loops are quite expensive, do you have any optimization for it

For two loops, when `personalDetails` is changed only some personal details (or only one) are changed not all so the second loop is only called serval times.

> deepEqual

For deepEqual, we can only compare the fields that will make the option is changed like `displayName`, `firstName`, `login`, `avatar`, ...

**Comment by hungvu193** [comment] 2024-04-12 08:05
> @hungvu193
> 
> > because I think 2 nested loops are quite expensive, do you have any optimization for it
> 
> For two loops, when `personalDetails` is changed only some personal details (or only one) are changed not all so the second loop is only called serval times.
> 
> > deepEqual
> 
> For deepEqual, we can only compare the fields that will make the option is changed like `displayName`, `firstName`, `login`, `avatar`, ...

Make sense, can you please create a draft PR with your full implementation so I can test it carefully? Thank you. We have some recent changes in `OptionsListContextProvider`, I just want to make sure I tested your proposal correctly.

**Comment by nkdengineer** [comment] 2024-04-12 08:06
Sure update now.

**Comment by nkdengineer** [comment] 2024-04-12 08:27
@hungvu193 A draft PR here https://github.com/Expensify/App/pull/40167.

**Comment by hungvu193** [comment] 2024-04-12 08:59
Unfortunately, your draft PR didn't work. See the video below.

https://github.com/Expensify/App/assets/16502320/0492d081-72cd-4ac4-bb98-b5e86ce3f6e6

**Comment by nkdengineer** [comment] 2024-04-12 09:36
@hungvu193 The problem is when we login as new account and doesn't open the selfDM report, `participantAccountIDs` of this report is empty array so when we filter the related report, we don't find the selfDM.

<img width="1506" alt="Screenshot 2024-04-12 at 16 35 21" src="https://github.com/Expensify/App/assets/161821005/0a426a1a-74d6-4ce1-9cd3-d9de7a974615">

**Comment by hungvu193** [comment] 2024-04-12 09:53
> participantAccountIDs

This is valid case and I think we should cover it as well. I usually need to create a new account to test this issue, because with my high traffic account sometimes self DM doesn't display.

**Comment by nkdengineer** [comment] 2024-04-12 10:09
@hungvu193 Updated the draft to cover this case.

**Comment by hungvu193** [comment] 2024-04-12 10:27
@nkdengineer 's [proposal here](https://github.com/Expensify/App/issues/39607#issuecomment-2038912998) looks good to me.  🎀 👀 🎀  C+ reviewed

cc @bondydaa 

@nkdengineer Please update your proposal to include the latest code as well.

**Comment by nkdengineer** [comment] 2024-04-16 09:02
@hungvu193 The PR is [here](https://github.com/Expensify/App/pull/40167).

**Comment by hungvu193** [comment] 2024-05-01 03:10
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38207
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug: No

This is new feature, we can treat it as a follow up of https://github.com/Expensify/App/pull/38207

**Comment by hungvu193** [comment] 2024-05-14 03:04
Bump @JmillsExpensify for payment here

**Comment by JmillsExpensify** [comment] 2024-05-14 05:46
Payment summary: 

- Contributor: @nkdengineer $250
- Contributor+: @hungvu193 $250

**Comment by JmillsExpensify** [comment] 2024-05-14 05:48
Both Contributor contracts paid out via Upwork, so I'm closing this issue.

**Closed by JmillsExpensify** 2024-05-14 05:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
