### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000] Web - Pressing space key applies focus to composer & scrolls comments at the same time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23508] opened 2023-07-24 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report that has multiple, scrollable comments
2. Scroll to the bottom of comments
3. Remove focus from the main composer
4. Press 'Space' key

## Expected Result:
The composer should not be focused and the report page should be scrolled.

## Actual Result:
Composer is focused & report is scrolled making the function of space key less predictable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/96a8d17e-dc90-4e65-b9c0-02aa5642f85c

https://github.com/Expensify/App/assets/93399543/3d49a0a2-b7c2-40e5-a973-1bcfa0ee6631

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690196594809449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150e7ff18d1f62eb0</li>
        <li>Upwork Job ID: 1683892863293607936</li>
        <li>Last Price Increase: 2023-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 25928554</li>
<li>Natnael-guchima | Reporter | 25928556</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-25 14:02
@mountiny @JmillsExpensify I found this somewhat [similar issue](https://github.com/Expensify/App/issues/15631) when looking into this one. It's similar in that it's an issue with clicking the `space` bar. In terms of expected behaviour, I would think we scroll the chat page and don't focus the composer in this case here. Would you agree with that?

**Comment by mountiny** [comment] 2023-07-25 14:34
@trjExpensify I agree the expected behaviour should be no focus and just scroll down

**Comment by trjExpensify** [comment] 2023-07-25 17:31
Cool, updating the OP's `expected behaviour` to make that clear. 👍 Moving on!

**Comment by robertKozik** [comment] 2023-07-25 21:34
@samh-nl could you update your proposal to be in line with the expected behaviour as was stated [here](https://github.com/Expensify/App/issues/23508#issuecomment-1649964574). I see that you stated it inside the alternative solutions, but I want this to be more clear as it should be go-to solution

**Comment by JmillsExpensify** [comment] 2023-07-26 03:12
>In terms of expected behaviour, I would think we scroll the chat page and don't focus the composer in this case here. Would you agree with that?

I agree with this as well.

**Comment by robertKozik** [comment] 2023-07-26 08:15
Thank you @samh-nl . Your solution is straightforward and is in line with expected behaviour.

I would choose @samh-nl [proposal](https://github.com/Expensify/App/issues/23508#issuecomment-1648562144)

🎀 👀 🎀 C+ reviewed

**Comment by saalimzafar** [comment] 2023-07-26 23:27
## Proposal

### Problem Statement:
Pressing the space key applies focus to the composer and scrolls through comments simultaneously, leading to an undesirable user experience.

### Root Cause:
The root cause of this issue is that the function `focusComposerOnKeyPress(e)`, responsible for handling keypress events, lacks a specific condition to prevent focusing the composer and performing simultaneous comment scrolling when the space key is pressed.

### Proposed Changes:
To address the problem, I propose updating the `focusComposerOnKeyPress(e)` function to include a proper handling mechanism for the space key. By incorporating the necessary condition, we can prevent focusing the composer and avoid triggering the comment scrolling action when users press the space key.

### Alternative Solution:
NA

Please review and consider this proposal to resolve the issue.

**Comment by robertKozik** [comment] 2023-07-27 20:58
Thanks, @saalimzafar, for your proposal, but the other one has already been selected ([here](https://github.com/Expensify/App/issues/23508#issuecomment-1651201599)). Your proposal suggests the same fix as the chosen one.

bumping @grgia to review and assign contributor

**Comment by saalimzafar** [comment] 2023-07-27 21:15
It's okay @robertKozik

**Comment by trjExpensify** [comment] 2023-07-31 10:09
@grgia can you give this a secondary review please so we can keep it moving?

**Comment by grgia** [comment] 2023-08-03 14:48
Thanks for the bump, I got a chance to review and @samh-nls proposal looks good, thank you!

**Comment by saalimzafar** [comment] 2023-08-03 14:57
Hi @grgia 
I want to report a bug which I'm unable to do via github issue, I've already sent the emails  to constributors but got no response. Can you help me if possible?

**Comment by robertKozik** [comment] 2023-08-03 15:38
Hi @saalimzafar you can submit bug reports via `#expensify-bugs` channel on slack

**Comment by saalimzafar** [comment] 2023-08-03 16:04
It seems that my invitation is not getting accepted @robertKozik 
I already send the emails but no response so far.

**Comment by trjExpensify** [comment] 2023-08-14 10:22
PR is still in review, @grgia is back this week.

**Comment by trjExpensify** [comment] 2023-08-15 10:02
Yeah, we take into account things like the weekend and a delay on our internal review.

**Comment by robertKozik** [comment] 2023-08-23 12:33
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21583
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21583/files#r1302944466
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A -  it was rather unconsidered case of the PR, so I don't think we should extend the checklist or anything**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **N/A - same as above**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by trjExpensify** [comment] 2023-08-23 12:45
Okay perfect, thanks for confirming! 

I'm going to be out of pocket tomorrow, so settled up with @natnael-guchima & @samh-nl today. Closing this out, thanks everyone!

**Closed by trjExpensify** 2023-08-23 12:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
