### ISSUE TITLE
[$500] Room Name Input Prefix and TextInput are not aligned - reported by @sobitneupane

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8356] opened 2022-03-30 02:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create New Room
2. Type room name in RoomName Input Field.

## Expected Result:
RoomName and Prefix aligned in same line.

## Actual Result:
Prefix is 1px below TextInput in web and android but prefix is 1px above TextInput in IOS.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.46-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="135" alt="Screen Shot 2022-03-15 at 22 50 10" src="https://user-images.githubusercontent.com/43995119/160735829-f0317821-0f38-4095-a111-b32a4cd0f89f.png">
<img width="135" alt="Screen Shot 2022-03-15 at 23 06 42" src="https://user-images.githubusercontent.com/43995119/160735830-3ae8f7d6-af8f-41ed-9acd-0ccc5eee88f5.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @sobitneupane
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1647443680162049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-03-30 05:27
Wow, that's quite the catch. Adding the engineering label to keep the process moving.

**Comment by Gonals** [comment] 2022-03-30 08:23
I don't think I would have ever seen this!

Adding External label, although it i so simple it might not be woth it. What do you think, @JmillsExpensify?

**Comment by JmillsExpensify** [comment] 2022-04-07 05:04
Whoops, sorry missed this last week. Did you want to take it? Agree that it's simple, so if you'd like to then go for it.

**Comment by JmillsExpensify** [comment] 2022-04-13 03:35
I'll go ahead and put to Upwork.

**Comment by JmillsExpensify** [comment] 2022-04-13 03:37
Upwork job is here: https://www.upwork.com/jobs/~0162d006ee58de971d. We're open for proposals. Thank you!

**Comment by parasharrajat** [comment] 2022-04-13 06:03
@JmillsExpensify I think the exported label is missing.

**Comment by aneequeahmad** [comment] 2022-04-17 15:08
@mvtglobally Could you please provide a video that has steps to reproduce this issue? I can't find how to create a new room

**Comment by Santhosh-Sellavel** [comment] 2022-04-17 15:47
@sobitneupane Can you provide steps more clearly?

**Comment by JmillsExpensify** [comment] 2022-04-18 21:54
@Santhosh-Sellavel Is he on the beta? He'll need that to test rooms, as we haven't released to the entire userbase.

**Comment by Santhosh-Sellavel** [comment] 2022-04-19 06:04
@JmillsExpensify 
Usually, We have all betas enabled in the Local Dev Environment.

If they don't have beta access, then by making a small code change in SideBarScreen to reproduce this issue.

**Comment by JmillsExpensify** [comment] 2022-04-20 21:25
Ok great, thanks for the confirmation!

**Comment by huzaima** [comment] 2022-04-22 15:36
### Proposal

Removing the `line-height` from the prefix character solves the issue. In particular, removing the following line:

https://github.com/Expensify/App/blob/2038776a7ba86639906c4033f22de8b48d75fb1e/src/components/Text.js#L61-L63

Working example:
<img width="354" alt="Screenshot 2022-04-22 at 8 35 16 PM" src="https://user-images.githubusercontent.com/17503685/164747400-53af3b4c-b0da-49e4-892e-13cefd2cc522.png">

**Comment by Santhosh-Sellavel** [comment] 2022-04-22 21:14
Open to better proposals!

**Comment by aneequeahmad** [comment] 2022-04-22 21:27
@Santhosh-we need to remove `lineHeight` from `CSS` for textInputPrefix as it is making the height of prefix a little more than actual, or maybe give default `lineheight` for  mobile and web that is respectively 0 or 'normal'.

**Comment by Santhosh-Sellavel** [comment] 2022-04-29 14:05
Waiting for proposals here!

**Comment by aneequeahmad** [comment] 2022-04-29 20:39
### PROPOSAL

**Solution**

lineHeight of textInputPrefix is causing the issue and making the prefix to have more lineHeight than needed. 
So to fix this give `lineHeight: Platform.OS === 'web' ? 'normal' : 0 ` to `textInputPrefix` in styles.js line no 774.

Web UI after fix
<img width="380" alt="Screen Shot 2022-04-30 at 1 37 44 AM" src="https://user-images.githubusercontent.com/36359331/166066075-ae8dc63c-1925-490c-a90e-b0fd84e5a7cd.png">

IOS UI after fix
<img width="105" alt="Screen Shot 2022-04-30 at 1 38 22 AM" src="https://user-images.githubusercontent.com/36359331/166066118-40637a23-66c1-400e-bc49-3a5cf37805ae.png">

**Comment by JmillsExpensify** [comment] 2022-05-02 15:13
@Santhosh-Sellavel Thanks! Mind reviewing the latest proposal from @aneequeahmad? Thank you!

**Comment by Santhosh-Sellavel** [comment] 2022-05-02 17:10
> lineHeight of textInputPrefix is causing the issue and making the prefix to have more lineHeight than needed. So to fix this give `lineHeight: Platform.OS === 'web' ? 'normal' : 0 ` to `textInputPrefix` in styles.js line no 774.

>  have more lineHeight than needed 
making it `0` if not `web` I'm not okay with this proposal.  

Can you elaborate more about why it occurs, and how the solution addresses this issue with more details? Thanks!

@aneequeahmad

**Comment by JmillsExpensify** [comment] 2022-05-10 21:12
@aneequeahmad I thought I'd check in on the question from @Santhosh-Sellavel above. Thanks!

**Comment by JmillsExpensify** [comment] 2022-05-17 04:23
Still waiting on response from contributor. Maybe we should open this one back up to proposals, yeah?

**Comment by aneequeahmad** [comment] 2022-05-17 10:56
@JmillsExpensify Ahh yes i'll explain. So the issue is lineHeight is adding additional height to the prefix that is causing it to stretch a little bit more.

By assigning default lineHeight to the prefix it occupies the available space.

cc: @Santhosh-Sellavel

**Comment by mollfpr** [comment] 2022-05-23 12:28
### Proposal

Adding `display: flex` and aligning it center vertically with `align-items: center` to the prefix text component will make the component have the same height as the input text.

https://github.com/Expensify/App/blob/56213d07d5e10b5ecf1cb2fae2d82aff9360bb5a/src/components/TextInput/BaseTextInput.js#L235-L247
```diff
+ styles.dFlex,
+ styles.alignItemsCenter,
```
<img width="835" alt="Screen Shot 2022-05-23 at 19 27 01" src="https://user-images.githubusercontent.com/25520267/169819145-d503722d-a98c-4b03-95ab-d6010df911e2.png">

**Comment by JmillsExpensify** [comment] 2022-05-23 15:29
@marcochavezf Shall we go with @aneequeahmad's proposal [here](https://github.com/Expensify/App/issues/8356#issuecomment-1128724161)? Looks like @Santhosh-Sellavel is on board as well.

**Comment by marcochavezf** [comment] 2022-05-23 17:50
> I'm not on board with setting `lineHeight: 0` as in this proposal [#8356 (comment)](https://github.com/Expensify/App/issues/8356#issuecomment-1113709009)

Ah I think @Santhosh-Sellavel doesn't agree with that proposal, right? Also, I'm not totally convinced either, because seems that proposal is forcing the lineHeight value on web/android and another value on iOS, which IMO it doesn't solve the root of the problem

> So the issue is lineHeight is adding additional height to the prefix that is causing it to stretch a little bit more.
@aneequeahmad could you explain why lineHeight is adding that additional height on different platforms? I'm wondering if there's an upper CSS class that could be causing this issue 🤔

**Comment by Santhosh-Sellavel** [comment] 2022-05-23 21:14
Yes, I didn’t agree with the proposal!

**Comment by JmillsExpensify** [comment] 2022-05-25 20:57
Perfect, thanks for the clarification! Let's keep the discussion moving forward in that case.

**Comment by aneequeahmad** [comment] 2022-05-25 22:57
@marcochavezf ill explain how the lineHeight is adding more height as soon as i can run it the app

**Comment by marcochavezf** [comment] 2022-05-30 16:08
Changing it to `Weekly` priority.

**Comment by marcochavezf** [comment] 2022-05-30 16:10
Hi @Santhosh-Sellavel 👋🏽 what do you think about this [proposal](https://github.com/Expensify/App/issues/8356#issuecomment-1134612500)?

**Comment by Santhosh-Sellavel** [comment] 2022-05-30 16:19
@marcochavezf I missed that one completely. 
And as I will be OOO,  just gonna unassign myself from this one and let a new C+ decide on this.

Can you re-apply the exported label here?

**Comment by marcochavezf** [comment] 2022-05-30 16:28
Sure, no worries, re-applying the `Exported` label to assign a new C+

**Comment by JmillsExpensify** [comment] 2022-05-31 02:56
Still a bit stalled in terms of aligning on the proposal to move forward with.

**Comment by rushatgabhane** [comment] 2022-06-02 05:11
@mollfpr it still misaligned on iOS (by 1px)

<img width="560" alt="image" src="https://user-images.githubusercontent.com/29673073/171557232-a5055076-371e-41ae-ba6c-17056bf6e414.png">

**Comment by marcochavezf** [comment] 2022-06-13 21:09
Waiting for more proposals

**Comment by JmillsExpensify** [comment] 2022-06-20 13:53
Still waiting for more proposals.

**Comment by JmillsExpensify** [comment] 2022-06-24 20:49
I'm OOO next week so I'm going to re-assign this issue.

**Comment by marcochavezf** [comment] 2022-06-27 16:44
Still waiting for more proposals.

**Comment by mallenexpensify** [comment] 2022-06-28 00:01
(Now that Mills is on vacation...) Doubled price to $500 and created 
https://www.upwork.com/jobs/~01abbd864a31eaf164

**Comment by rushatgabhane** [comment] 2022-06-30 01:16
@mallenexpensify this might be a good `Monthly` candidate.

**Comment by mallenexpensify** [comment] 2022-07-01 00:55
If you say so @rushatgabhane :)

**Comment by jliexpensify** [comment] 2022-07-14 03:11
@rushatgabhane - can I close this? I'm on the latest version and it seems like this isn't an issue?

![image](https://user-images.githubusercontent.com/30815269/178889990-5a0886f8-1cd6-49a0-88f6-eb2e0a063d08.png)

**Comment by rushatgabhane** [comment] 2022-07-14 03:19
@jliexpensify it's barely noticeable, but it's still present.
We could still close this tho, it low-key looks nice and helps differentiate the prefix from the room name.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/29673073/178890449-caddc406-bc8d-4ee6-8e03-01bc817151be.png">

**Comment by jliexpensify** [comment] 2022-07-14 03:25
@rushatgabhane oh damn haha, good eyes! I honestly don't think the majority of people will notice - closing!

**Closed by jliexpensify** 2022-07-14 03:25 UTC
Labels: Exported, External, Engineering, Monthly, Improvement, Help Wanted
