### ISSUE TITLE
[HOLD for Payment 2024-09-6][$250] Android - Chat - Open a new room/WS chat, entering @ does not display user suggestions

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45008] opened 2024-07-08 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4704455
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a workspace or room with no activity
3. Enter @ in compose box
4. Note user suggestions are not displayed
5. Tap on header
6. Navigate back to conversation page
7. Keep cursor after @ and note now user suggestions are shown

## Expected Result:
Open a new room/WS chat, entering @ must display user suggestions

## Actual Result:
Open a new room/WS chat, entering @ does not display user suggestions. It is shown only after tapping header and navigate back to conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/34338215-a0aa-47b2-aa13-2be358871e08

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180b0b26a5f7f23c0</li>
        <li>Upwork Job ID: 1811721981798318944</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103480415</li>
<li>dominictb | Contributor | 103480416</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment] 2024-07-08 20:42
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-08 20:42
We think that this bug might be related to #vip-vsp

**Comment by ikevin127** [comment] 2024-07-13 17:49
📃 Issue is definitely reproducible, just reproduced on **production** as well. On **local dev** the behaviour might be even worse because of the recent introduction of React `StrictMode` which might interfere with the **react-native-live-markdown** implementation.

🔍 Looking for proposals!

**Comment by ikevin127** [comment] 2024-07-16 19:59
Callback to https://github.com/Expensify/App/issues/45008#issuecomment-2227008347 -> **Looking for proposals** 🎲

**Comment by ikevin127** [comment] 2024-07-19 17:36
Callback to https://github.com/Expensify/App/issues/45008#issuecomment-2227008347 -> **Looking for proposals** 🎲

**Comment by ikevin127** [comment] 2024-07-22 18:28
Callback to https://github.com/Expensify/App/issues/45008#issuecomment-2227008347 -> **Looking for proposals** 🎲

**Comment by ikevin127** [comment] 2024-07-26 18:37
Callback to https://github.com/Expensify/App/issues/45008#issuecomment-2227008347 -> Looking for proposals 🎲

**Comment by ikevin127** [comment] 2024-07-30 18:41
Callback to https://github.com/Expensify/App/issues/45008#issuecomment-2227008347 -> Looking for proposals 🎲

**Comment by ikevin127** [comment] 2024-08-02 18:22
Reviewing proposal.

**Comment by ikevin127** [comment] 2024-08-05 18:17
♻️ Will finish reviewing the proposal today.

**Comment by ikevin127** [comment] 2024-08-05 23:43
@dominictb Thank you for taking the time to come up with a quality proposal for fixing this 1 month old issue 👴 

**Dominic**'s [proposal](https://github.com/Expensify/App/issues/45008#issuecomment-2262153998) looks good to me. The root cause is well documented and every single point described in the RCA checks-out. The proposed solution fixes the issue accordingly, using the already existing `useAutoFocusInput` hook, aligning the Android behaviour with the one on iOS -> fulfilling the **Expected result** of the issue.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-08-10 19:00
We're currently awaiting @youssef-lr's contributor assignment based on proposal [review](https://github.com/Expensify/App/issues/45008#issuecomment-2270103269).

**Comment by sonialiap** [comment] 2024-08-16 12:46
@kadiealexander I'm OOO Aug 19-30, adding leave buddy. 
Satus: waiting on @youssef-lr to assign contributor

**Comment by ikevin127** [comment] 2024-08-16 17:29
**Status update:** PR is open, contributor is re-working solution because performance tests are failing with initial solution.

**Comment by ikevin127** [comment] 2024-08-21 00:47
**Status update**: PR is ready for merge, we're currently awaiting on CME for final 🟢 **Approve** and merge.

**Comment by ikevin127** [comment] 2024-08-30 20:29
**Status update**: PR was merged to **staging** 🟢, **did not get to production yet** ⚠️.

##


@youssef-lr do you happen to have more context on why the PR was not deployed to production yet ? Additionally, I noticed you closed a [revert](https://github.com/Expensify/App/pull/48181) PR recently, what happened - something wrong with the initial PR ?

**Comment by ikevin127** [comment] 2024-08-30 22:21
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @sonialiap @youssef-lr

**Comment by sonialiap** [comment] 2024-09-02 08:33
Thanks Kevin, I've updated the title

**Comment by ikevin127** [comment] 2024-09-05 00:57
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: **N/A**.
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Launch app.
2. Tap on a workspace or room with no activity.
3. Input `@` in the composer box.
4. Verify that user suggestions popup is displayed.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment] 2024-09-08 20:11
cc @sonialiap

**Comment by sonialiap** [comment] 2024-09-09 08:39
Payment summary:
- @ikevin127 $250 - paid ✔️ 
- @dominictb $250 - paid ✔️

**Closed** 2024-09-09 08:41 UTC
Labels: Reviewing, External, Daily, Bug
