### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Web - Request money - Users can modify the paid requested money amount using the URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27192] opened 2023-09-11 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account.
2. Create a workspace and invite User B.
3. Go to the workspace room(Expense room) from User B.
4. Navigate to the "Request money".
5. Enter a specific amount and initiate the request.
6. Return to User A's account.
7. Open the "Requested money" from the LHN sent by User B.
8. Open the detail page for the requested money.
9. Click on the "Amount" field.
10. Copy the URL associated with the amount.
11. Navigate back and select "Pay elsewhere."
12. Revisit the requested money detail page.
13. Paste the previously copied URL and modify the amount.
14. Observe that the amount has been successfully modified despite the IOU being marked as paid.

## Expected Result:
 Users should be unable to modify the amount of a paid requested money via URL

## Actual Result:
Users can modify the paid requested money amount using the URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b8f177a3-5d68-42ad-9d77-1452df69c3dd

https://github.com/Expensify/App/assets/93399543/374cfb10-864d-446c-92ae-68b486d167d6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694158187633499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc5f75afccaf359e</li>
        <li>Upwork Job ID: 1701323718123368448</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26661068</li>
<li>b4s36t4 | Contributor | 26661069</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-11 20:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Request money - Users can modify the paid requested money amount using the URL
### What is the root cause of that problem?

We already have a condition in which we're checking if the user can edit the request amount. If not we're dismissing modal but due the fact of we're opening page using URL. By the time when the condition run navigation is not yet fully completed so nothing is happening.

https://github.com/Expensify/App/blob/5f9bb2e1d901eb6dc0110d8214e679d4d2aa6822/src/pages/EditRequestPage.js#L90

This is where the issue of code snippet lies.

### What changes do you think we should make in order to solve the problem?
1. We can use `Navigation.isNavigationReady` to run the `Navigation.dismissModal()` call to make it run only after navigation is ready. (tested | recommended)

2. We can use `useFocusEffect` hook from `react-navigation` and build logic around it to run `Navigation.dismissModal` once again. (not-tested)



### What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment] 2023-09-12 03:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Request money - Users can modify the paid requested money amount using the URL
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/8032edd27d9e7918beee234c33428df21652fcb6/src/pages/EditRequestPage.js#L88-L93
We had logic to dismiss modal when the request is paid. But Navigation.dismissModal() is executed before the transition end
It causes this issue
### What changes do you think we should make in order to solve the problem?
we should wrap dismissModal function by InteractionManager.runAfterInteractions to ensure that it will be executed after transition
```
InteractionManager.runAfterInteractions(()=> {
            Navigation.dismissModal();
        })
```

### What alternative solutions did you explore? (Optional)

**Comment by needpower** [comment] 2023-09-12 21:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users can change the requested amount of money after completing a payment with the `Pay elsewhere` option.

### What is the root cause of that problem?
The `EditRequestPage`  component doesn't prevent modal appearance, despite there is a code that tries to do this:
https://github.com/Expensify/App/blob/3fe7ab1c7d860f40eeb9a52b911f8d7bc4781dd5/src/pages/EditRequestPage.js#L87-L88

### What changes do you think we should make in order to solve the problem?
1. Remove `useEffect` in the code referenced above cause it can make additional re-renders
2. Display the message `You can not edit amount after payment is completed` instead of an editable amount. The same should be done for other payment fields: Description, Date, Merchant.

### What alternative solutions did you explore? (Optional)
Block navigation to `Edit amount` page on the route level by checking all conditions and redirecting to a request view if an amount is not editable. (It's an untested assumption that the solution will work out)

The solution @DylanDylann proposed fixes the issue but causes RHP flickering, which may confuse a user:

https://github.com/Expensify/App/assets/9203524/dbd7dcc1-24dc-4f81-98e3-99acb53772f0

**Comment by chiragsalian** [comment] 2023-09-13 20:53
Proposal looks good to me. Feel free to create the PR.
@b4s36t4. 

One thing confuses me the video. After the expense is edited at the end i see the new amount reflected in both userA and userB, this means that the API request succeeded. That looks odd to me because i would think that `EditMoneyRequest` should fail on a paid expense. Testing locally i see that it failed so I'm confused why it did not for the tester. 

Can someone confirm this, because if `EditMoneyRequest` then we should open an issue to fix it internally, otherwise people can just modify their expense via postman and that would be bad.

**Comment by b4s36t4** [comment] 2023-09-14 15:15
@chiragsalian Yes, backend request is getting success even though request is settled. This needs fix from backend as well.

**Comment by chiragsalian** [comment] 2023-09-14 17:24
@luacmartins, i think you worked on `EditMoneyRequest`, can you verify that an expense amount can be modified even after the expense is settled. If so can you create a GH issue to fix this in PHP and auth layer.

**Comment by b4s36t4** [comment] 2023-09-14 17:27
@chiragsalian @0xmiroslav Raised PR here #27460. Thanks!

**Comment by luacmartins** [comment] 2023-09-15 00:23
@mountiny worked on `EditMoneyRequest` but I don't think we allow you to change the amount for a settled request.

**Comment by mountiny** [comment] 2023-09-15 04:04
@b4s36t4 is this only in case of expenses or IOU reports?

**Comment by b4s36t4** [comment] 2023-09-15 04:07
I have checked it for a distance request, not for manual or scan.

**Comment by b4s36t4** [comment] 2023-09-15 04:07
I think as per issue's description it happens with manual too.

**Comment by mountiny** [comment] 2023-09-15 04:09
But what about the requests made between two users?

**Comment by mountiny** [comment] 2023-09-15 05:20
@b4s36t4 I am trying but I cannot reproduce even in staging, when I edit the paid report, it reverts back

**Comment by b4s36t4** [comment] 2023-09-15 05:22
https://github.com/Expensify/App/assets/59088937/9622e4db-0782-40f5-b19b-7e66735306e5

@mountiny Just tried on the staging.

**Comment by mountiny** [comment] 2023-09-15 05:24
@b4s36t4 can you stry with normal cash  request?

**Comment by b4s36t4** [comment] 2023-09-15 05:31
https://github.com/Expensify/App/assets/59088937/b586956f-c8ec-408d-acb6-917d9f8d56b3

@mountiny

**Comment by b4s36t4** [comment] 2023-09-15 05:33
BTW header looks different this maybe a UI bug.

**Comment by mountiny** [comment] 2023-09-15 05:43
@b4s36t4 I am not seeing the same, for me it reverts automatically.

**Comment by b4s36t4** [comment] 2023-09-15 05:44
You're trying with any workspace? maybe try on a new workspace?

**Comment by b4s36t4** [comment] 2023-09-15 05:46
The above recordings are with workspace, maybe you're trying with 1:1 chats?

**Comment by mountiny** [comment] 2023-09-15 06:05
@b4s36t4 are you trying with an admin? I think I just reproduced on a new workspace when the requestor was an admin

**Comment by b4s36t4** [comment] 2023-09-15 06:07
I'm an admin.

**Comment by mountiny** [comment] 2023-09-15 06:14
okok so I have chatted with Jason and actually you can edit the expenses even after they are paid as an admin, however, currency, amount and date cannot be changed.

I will update the permissions on the backend

**Comment by mountiny** [comment] 2023-09-18 03:36
Put up a PR which updates the permissions

**Comment by flaviadefaria** [comment] 2023-10-02 11:58
@0xmiroslav can you please address the comment above so that I can proceed to making payments? Thanks!

**Comment by flaviadefaria** [comment] 2023-10-02 12:02
Payment summary:

>For reference, here are some details about the assignees on this issue:
@b4s36t4 requires payment [offer](https://www.upwork.com/nx/wm/offer/26661069) (Contributor)
@0xmiroslav requires payment [offer](https://www.upwork.com/nx/wm/offer/26661068) (Reviewer)
@ayazhussain79 requires payment

>The pull request got merged within 3 working days of assignment, so this job is eligible for a 50% #urgency bonus 🎉

@b4s36t4  (Contributor) = $500 + 50% bonus = $750
@0xmiroslav (Reviewer)  = $500 + 50% bonus = $750
@ayazhussain79 (Reporter) = $250

**Comment by flaviadefaria** [comment] 2023-10-02 16:00
@b4s36t4 and @0xmiroslav have been paid
@ayazhussain79 I'm waiting for you to accept my offer.

**Comment by ayazhussain79** [comment] 2023-10-02 16:15
@flaviadefaria offer accepted, Thank you

**Comment by flaviadefaria** [comment] 2023-10-03 09:39
Everyone has been paid so closing this.

**Closed by flaviadefaria** 2023-10-03 09:39 UTC
Labels: External, Daily, Awaiting Payment, Bug
