### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Cannot change assignee after task created

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23556] opened 2023-07-25 14:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any task report
2. Click + on composer > Assign task
3. Click back button to close modal
4. Click Assignee field
5. Select any contact
## Expected Result: 
Selected contact should be assigned to the task
## Actual Result: 
Nothing happens but console error shows - "Cannot read property 'reportID' of undefined"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a6c23f72-4e2f-42bc-9b85-39d8969980fa

https://github.com/Expensify/App/assets/43996225/258bba85-b614-4c10-84a6-aa4424f1d4da

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690261085014579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a286825668f899a</li>
        <li>Upwork Job ID: 1683968213928505344</li>
        <li>Last Price Increase: 2023-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 25863472</li>
<li>dukenv0307 | Contributor | 25863473</li>
<li>situchan | Reporter | 25863474</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-25 16:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cannot change assignee after task created.

### What is the root cause of that problem?
If click "assign task" from composer in `TaskView`, `Task.clearOutTaskInfoAndNavigate` is called.
https://github.com/Expensify/App/blob/74ae95c26ea84d2ac87e8c5d026c5cbcc79244fc/src/pages/home/report/ReportActionCompose.js#L461

This function clear `ONYXKEYS.TASK` `onyx` data, and navigate to new task page.
If close new task modal, `ONYXKEYS.TASK` `onyx` data does not reverted.

And when navigate to task assignee page, because there is no `props.task`, so the error is occured, and user cannot select task assignee.
https://github.com/Expensify/App/blob/74ae95c26ea84d2ac87e8c5d026c5cbcc79244fc/src/pages/tasks/TaskAssigneeSelectorModal.js#L167
https://github.com/Expensify/App/blob/74ae95c26ea84d2ac87e8c5d026c5cbcc79244fc/src/pages/tasks/TaskAssigneeSelectorModal.js#L223-L225

### What changes do you think we should make in order to solve the problem?
We can set `ONYXKEYS.TASK` `onyx` before navigating to task assignee modal in [this line](https://github.com/Expensify/App/blob/74ae95c26ea84d2ac87e8c5d026c5cbcc79244fc/src/components/ReportActionItem/TaskView.js#L121) and [this line](https://github.com/Expensify/App/blob/74ae95c26ea84d2ac87e8c5d026c5cbcc79244fc/src/components/ReportActionItem/TaskView.js#L131) as below.
```js
    onPress={() => {
        Task.setTaskReport({...props.report, isExistingTaskReport: true});
        Navigation.navigate(ROUTES.getTaskReportAssigneeRoute(props.report.reportID));
    }}
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by situchan** [comment] 2023-07-25 17:29
@adelekennedy I'd like to take this as C+ if possible, as this is a follow-up of [issue](https://github.com/Expensify/App/issues/22078) we (@robertjchen and @dukenv0307) worked on and we have full context.

**Comment by alitoshmatov** [comment] 2023-07-26 05:45
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Task assignee is not working if new task modal is opened and closed
### What is the root cause of that problem?
When `Assign task` is selected in plus button in compose box or FAB button, we are clearing out task data in onyx, and not setting it back when modal closes.
https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/pages/home/report/ReportActionCompose.js#L461
https://github.com/Expensify/App/blob/ccca9538aecfa1bf906ea4fb24aff56ad3220234/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L230
That is why assignee selection is not working because we have nothing in `props.task` here:
https://github.com/Expensify/App/blob/a656c82d0ebf1d3954575084555a004efc47035b/src/pages/tasks/TaskAssigneeSelectorModal.js#L167
### What changes do you think we should make in order to solve the problem?
This line is responsible of setting current task to onyx
https://github.com/Expensify/App/blob/85d84b8d42f1b345fe0804592d1bab8b07875948/src/components/ReportActionItem/TaskView.js#L42-L44
We can improve it by retrieving `ONYXKEYS.MODAL` value, and add it to `useEffect` dependecies.
```javascript
    useEffect(() => {
        Task.setTaskReport({...props.report, isExistingTaskReport: true});
    }, [props.report, props.modal.isVisible]);
```
### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-07-26 05:45
I have reported the same bug here - https://expensify.slack.com/archives/C049HHMV9SM/p1688321334107149

**Comment by adelekennedy** [comment] 2023-07-28 03:24
These do look the same @situchan are both issues stemming from [here](https://github.com/Expensify/App/issues/22078)?

I also want to raise that @thienlnam mentioned [here](https://github.com/Expensify/Expensify/issues/294203) that @alitoshmatov reported issue will be fixed by the assignee flow update - should we close this?

**Comment by situchan** [comment] 2023-07-28 03:27
> issue will be fixed by the assignee flow update

This didn't happen actually and still reproducible.
So let's continue fixing it here and reporting bonus goes to @alitoshmatov 
Sounds like a plan?

**Comment by adelekennedy** [comment] 2023-07-28 03:30
Works for me@ Thank you @situchan 🎉

**Comment by thienlnam** [comment] 2023-07-28 17:56
> This didn't happen actually and still reproducible.

Well the [App PR](https://github.com/Expensify/App/pull/22778) hasn't been merged yet, so it is still broken right now. But is fixed in that PR. Let's still handle this current issue here though

**Comment by situchan** [comment] 2023-07-28 19:46
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/23556#issuecomment-1650231285) looks good to me.
There's another case of `props.task` usage. `shareDestination` should not be changed while changing assignee after task created. Let's tackle them in PR.
https://github.com/Expensify/App/blob/5132a6eb077e524eee26a661bbe742e6aba273a1/src/pages/tasks/TaskAssigneeSelectorModal.js#L170

🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2023-07-31 09:58
I just got assigned and I need clarification about the state of things, is this PR https://github.com/Expensify/App/pull/22778 fixing the bug or it won't?

**Comment by situchan** [comment] 2023-07-31 10:04
I just tested #22778 branch locally and this issue is still reproducible.

**Comment by situchan** [comment] 2023-07-31 10:30
@dukenv0307 after `props.task` is cleared, `props.task.shareDestination` is undefined, it's passed to `Task.setAssigneeValue` param and this line resets shareDestination to the another report depending on selected assignee.
Current reportID where task is created should be passed so that it doesn't meet this condition - `!shareDestination`.
Please correct me if I am wrong.
https://github.com/Expensify/App/blob/8cdb506e97e8382f4bc55b0f48784f576fbb2789/src/libs/actions/Task.js#L538-L540

**Comment by situchan** [comment] 2023-07-31 14:53
I think we are good to go. There might be small code conflict but no logic conflict.

**Comment by pecanoro** [comment] 2023-08-08 18:26
I am sorry but this is not eligible for the bonus. By the time I got assigned, it was almost the end of the 3-day period and my work day was already done that day since it was 6pm. If I hadn't asked for changes, we could have forgotten about the one-day delay, but there was a pending bug and there were conflicts to be fixed, so I am sorry, but we can't make an exception here.

**Comment by adelekennedy** [comment] 2023-08-18 22:12
Payouts due:

Issue Reporter: $250 @situchan (Upwork)
Contributor: $1000 @dukenv0307 (Upwork)
Contributor+: $1000 @situchan (Upwork)

Eligible for 50% #urgency bonus? **N**

Upwork job is [here](https://www.upwork.com/jobs/~010a286825668f899a).

**Closed** 2023-08-28 15:52 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug

**Comment by alitoshmatov** [comment] 2023-08-28 16:22
Sorry for bothering this late, but looks like I should have received reporting bonus https://github.com/Expensify/App/issues/23556#issuecomment-1654929175
