### ISSUE TITLE
 IOU - Manual IOU amount doubles after requesting

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30607] opened 2023-10-30 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Click on the FAB button
4. Click on the "Request money" button
5. Click on the "Manual" button
6. Enter any amount
7. Click on the "Next" button
8. Enter an email address
9. Click on it
10. Click on the "Request" button

## Expected Result:
The requested amount should be the one I entered

## Actual Result:
After half a second, the requested amount doubles

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/ea1d2ac9-369f-40d3-b18e-d559036cfe8d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-10-30 20:07
Seems related to https://github.com/Expensify/App/pull/29566

**Comment by tylerkaraszewski** [comment] 2023-10-30 23:18
I've confirmed this happens.

**Comment by tylerkaraszewski** [comment] 2023-10-30 23:20
@s77rt - do you have any insight here?

**Comment by cryptosheepself** [comment] 2023-10-30 23:53
I am currently seeing a trail, is there a bounty for this on upwork? I believe I can get this fixed in a few hours.

**Comment by s77rt** [comment] 2023-10-31 08:05
@tylerkaraszewski This may be a backend bug. Is it expected that money requests return both `nonReimbursableTotal` and `total` set to the user's requested amount? cc @grgia

**Comment by Beamanator** [comment] 2023-10-31 10:20
@cryptosheepself yes, if you help diagnose the problem & suggest a solution that we go with, you will be compensated - but, as normal, if we don't agree with your solution, we may not compensate

@s77rt if you're right, do you see somewhere in App that we're adding the two?

**Comment by Beamanator** [comment] 2023-10-31 10:23
It looks like we're purposefully storing `total` and `nonReimbursableTotal` in Onyx in [this PR](https://github.com/Expensify/App/pull/29566) (see test steps) so I'd guess yes, we do expect to return both

**Comment by s77rt** [comment] 2023-10-31 10:23
@Beamanator Yes and it's expected to add the two based on the [linked PR](https://github.com/Expensify/App/pull/29566)
https://github.com/Expensify/App/blob/a31933a049b9a9aa4222a4d3edab19b54a4555b7/src/libs/ReportUtils.js#L1443

**Comment by Beamanator** [comment] 2023-10-31 10:30
Ya very interesting - lets try to confirm w/ onyx values from a real example

**Comment by grgia** [comment] 2023-10-31 10:31
Just to clarify, we only add the two for _spend_ total, not for the reimbursable total that a user would owe.

**Comment by Beamanator** [comment] 2023-10-31 20:52
The issue seems to be resolved for me, I'm confident moving forward with the deploy with this fix 👍

https://github.com/Expensify/App/assets/3885503/28fd1e13-b197-41f0-933c-7c05bc976585

**Closed** 2023-11-01 19:59 UTC
Labels: Engineering, Daily, Bug
