### ISSUE TITLE
Chat - The loading animation is not occurring when more messages need to be loaded in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14503] opened 2023-01-24 02:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with a HIGH traffic account.
2. Navigate to a 1:1 chat that has a lot of messages in the conversation history
3. Scroll to the top of the conversation

## Expected Result:
An short loading animation appears when more messages need to be loaded.

## Actual Result:
The loading animation is not occurring when more messages need to be loaded in chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.58.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![iss](https://user-images.githubusercontent.com/93399543/214197782-6b37bfdc-78d9-4574-8751-63a9ba03ed9d.png)

https://user-images.githubusercontent.com/93399543/214197784-9c166a22-2b71-4c76-b82d-be0034226f46.mp4

https://user-images.githubusercontent.com/93399543/214197786-9126fbf5-05f4-48e2-8961-80a89fbd9787.mp4

https://user-images.githubusercontent.com/93399543/214197787-f35c49fd-9a49-4055-bea9-e7ed1f66bb81.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause- Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2023-01-24 03:28
Discussing the intended behavior here  - https://expensify.slack.com/archives/D6Z2DV7U3/p1674530909393829

**Comment by mvtglobally** [comment] 2023-01-24 14:47
@iwiznia pls chime in if you have additional info here

**Comment by mallenexpensify** [comment] 2023-01-24 15:43
I think this is a dupe that's been happening in one way or another for over a year.  Checking in deprecate sequence number Slack room -[ link](https://expensify.slack.com/archives/C04DC6LU2UB/p1674574921870029). 

> There's been an issue for over a year where, when you scroll up, old chats don't load. The work-around is to scroll all the way down, then back up again but it doesn't work correctly all the time. I think it might be a pagination issue.   Will this bug be addressed/fixed as part of deprecate sequence number?

**Comment by davidcardoza** [comment] 2023-01-24 17:01
Reproducible on desktop, not on mobile. 
<img width="1483" alt="2023-01-23_20-24-05" src="https://user-images.githubusercontent.com/6643649/214358504-b80162ee-909b-4ea3-a8e2-d43f9070e0ef.png">

**Comment by luacmartins** [comment] 2023-01-24 18:17
This is not a blocker since we can reproduce in prod. I'm also gonna close this issue since it's being worked on as part of the deprecate sequence numbers project. More context [here](https://expensify.slack.com/archives/C049HHMV9SM/p1674583821962659?thread_ts=1674510639.270879&cid=C049HHMV9SM).

**Closed by luacmartins** 2023-01-24 18:17 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Needs Reproduction, Bug
