### ISSUE TITLE
Individual IOUs from bill split are not correctly sent to other devices

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41173] opened 2024-04-28 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.66-2
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @roryabraham @thienlnam 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @thienlnam 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714154876284589
 
## Action Performed:
1. Log into New Expensify on two devices, A and B.
2. Create a group on device A.
3. Upload a receipt to split a bill in the group.

## Expected Result:
On both devices, individual IOUs should be created with each member of the group for their portion.
## Actual Result:
Individual IOUs appear on the device where the receipt was uploaded. They do not appear on device B.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (14)](https://github.com/Expensify/App/assets/38435837/ac257718-d4df-4434-a71f-c742cc2aebfe)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128f10261fc2f1ffb</li>
        <li>Upwork Job ID: 1784659033584848896</li>
        <li>Last Price Increase: 2024-04-28</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2024-04-30 21:48
This was just triaged. Not overdue

**Comment by johncschuster** [comment] 2024-05-07 21:59
@mananjadhav what do you need from me on this one?

**Comment by mananjadhav** [comment] 2024-05-08 17:13
Waiting on proposals. I'll also try to reproduce it at my end

**Comment by johncschuster** [comment] 2024-05-10 20:58
Oh! It looks like this is an `Internal` issue so it's likely not going to be seen in the usual `Help Wanted` spaces. How can I help drum up proposals?

**Comment by johncschuster** [comment] 2024-05-14 21:03
Ok, I'm unsure the priority of this issue in the grander scheme (and thus, how aggressive I should be to get a volunteer). Raising the question [here](https://expensify.slack.com/archives/C05RECHFBEW/p1715720546468689)

**Comment by johncschuster** [comment] 2024-05-15 14:07
Ok! We [chatted](https://expensify.slack.com/archives/C05RECHFBEW/p1715720546468689) about the priority of this issue. Currently, this is a `MEDIUM` priority. It's important we get someone on this, but it's not the most urgent thing.

**Comment by johncschuster** [comment] 2024-05-16 17:39
Setting this to `Weekly` in the meantime.

**Comment by johncschuster** [comment] 2024-06-05 22:39
I couldn't action this today. I will pop back in tomorrow

**Comment by mananjadhav** [comment] 2024-06-10 16:47
Should we make this monthly @johncschuster ?

**Comment by johncschuster** [comment] 2024-06-18 21:45
@arielgreen, we haven't gotten any traction on this one. Do you feel we need to keep this at `Weekly` and pump the gas, or do you feel we can safely reduce the priority to `Monthly` for now?

**Comment by johncschuster** [comment] 2024-06-27 21:18
Reducing to `Monthly`. Please change the label if you disagree!

**Comment by johncschuster** [comment] 2024-07-29 21:29
Asking for help to get some engineering resources on this one.

**Comment by mvtglobally** [comment] 2024-08-09 04:28
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2024-08-30 23:04
It sounds like this may not be reproducible. Closing!

**Closed by johncschuster** 2024-08-30 23:04 UTC
Labels: Monthly, Internal, Overdue, Bug, retest-weekly
