### ISSUE TITLE
[$1000] Empty threads show in the LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19634] opened 2023-05-25 21:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any group DM.
1. Hover over or long-press someone else's message, then click the thread button to create a thread. Do not send a message in the thread yet.
## Expected Result: 
The sender of the root message of the thread you created should not see the empty thread in their LHN. It should only appear for them when you send a message in a thread.
## Actual Result: 
The sender of the root message of the thread you created sees the empty thread in their LHN before you send a message in it.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bbf1f4ef-e305-4fb7-aab0-eb74942c5312

**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684878218587529
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172f129da778218c2</li>
        <li>Upwork Job ID: 1663732602774986752</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-05-26 01:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Empty threads show in the LHN

### What is the root cause of that problem?

The root cause of this issue is that we don't skip option data for empty thread in method getOptionData

 https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/libs/SidebarUtils.js#L179-L185

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can return early in method getOptionData [here](https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/libs/SidebarUtils.js#L267) if report is thread and lastMessageTextFromReport is empty. We can add following check to achieve it

```js
// We want to return early if this is an empty thread
if (result.isThread && lastMessageTextFromReport === '') {
    return;
}
```

Then we won't show the empty thread in LHN, see

https://github.com/Expensify/App/blob/6f243fe60311bec9eff6976baceb384b56d53687/src/components/LHNOptionsList/OptionRowLHN.js#L54-L57

See demo video after fix

https://github.com/Expensify/App/assets/117511920/1241023b-4b64-4bce-9201-92627bd0145e

### What alternative solutions did you explore? (Optional)

N/A

**Comment by srikarparsi** [comment] 2023-05-31 02:22
not overdue

**Comment by srikarparsi** [comment] 2023-05-31 03:17
This issue actually already exists [here](https://github.com/Expensify/App/issues/19205) and is being worked on in this [PR](https://github.com/Expensify/App/pull/19375). Closing out this issue but feel free to reopen @johncschuster @thesahindia if there is something left to do.

**Closed by srikarparsi** 2023-05-31 03:17 UTC
Labels: Engineering, Daily, Help Wanted, Bug
