### ISSUE TITLE
IOS/Android - IOU - Error page is displayed after tap the iOU badge

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11995] opened 2022-10-19 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Open the test app and sign in to any account
3. Navigate to chat with any user
4. Complete the request money flow
5. Tap the IOU badge at the top of the chat screen

## Expected Result:
Expanded view of the IOU is displayed after tap the IOU badge

## Actual Result:
The Error page is displayed after tap the IOU badge.
The same after tap the IOU badge on LHN screen.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196763169-cbcf39df-7ab6-489f-82fe-24bbd15a785f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2022-10-19 18:29
Nothing in the recent PR list is jumping out to me as a likely culprit, so I'm going to run this locally and see if I can spot the problem in the logs.

**Comment by neil-marcellini** [comment] 2022-10-19 18:50
Hmm I tried running iOS staging locally against the staging server and I can't reproduce there.

**Comment by neil-marcellini** [comment] 2022-10-19 19:13
I found some [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22%5BalXt%5D%22%20AND%20email%3A%22neil%40expensify.com%22%20AND%20timestamp%3A%5B2022-10-19T00%3A00%20TO%202022-10-20T23%3A59%5D) of the error happening on my physical device. Now I should be able to identify the problem.

**Comment by neil-marcellini** [comment] 2022-10-19 19:52
It's really hard to tell where the problem with `'actionName'` is coming from since we use it in quite a few places. It's also odd that nothing on the IOUDetailsModal page seems to access actionName, it all comes from the ReportScreen.

Idk why I can't reproduce the error on dev.

**Comment by neil-marcellini** [comment] 2022-10-19 20:43
I'm asking for some help in Slack now.

**Comment by neil-marcellini** [comment] 2022-10-19 21:31
I found out that I wasn't actually pointing my dev environment to staging because our env.staging file is out of date and still points to the production api. However, after making that change I still can't reproduce. My next step is to try running from dev on my physical device or maybe running a release build as well.

**Comment by neil-marcellini** [comment] 2022-10-19 22:06
I need to update Xcode before I can run on my physical device and that's taking quite a while to download. I asked in #deployer if anyone can help test by running locally on a physical device and getting logs.

I ran a release build on the simulator and I didn't have any problems.

**Comment by neil-marcellini** [comment] 2022-10-19 22:55
Still waiting on Xcode.

**Comment by sketchydroide** [comment] 2022-10-20 10:48
This seems like a blocker, was able to reproduce, will ask in #deployer for help, will take a look as well

**Comment by Justicea83** [comment] 2022-10-20 11:40
Taking a look as well

**Comment by Justicea83** [comment] 2022-10-20 12:27
I think this may be due to the PHP 8.1 upgrade. I saw some CP'ed fixes from @iwiznia [here](https://github.com/Expensify/Web-Expensify/pull/35171/files).

**Comment by Justicea83** [comment] 2022-10-20 12:28
Can someone test the staging build with the current production API, to see if this issue is reproducible?

**Comment by Justicea83** [comment] 2022-10-20 12:37
This might be related

https://user-images.githubusercontent.com/26106822/196950499-918249cd-af0c-4954-86ac-4761c48c03b4.mp4

**Comment by neil-marcellini** [comment] 2022-10-20 17:33
I'm back to working on this now. I will first make sure that I can't reproduce this on prod. If I can then it's not a deploy blocker. I know it's mentioned in the description but it's good to double check.

Next, now that Xcode is up to date, I will try to run a dev build with the staging api on my physical device.

**Comment by neil-marcellini** [comment] 2022-10-20 17:39
> I think this may be due to the PHP 8.1 upgrade. I saw some CP'ed fixes from @iwiznia [here](https://github.com/Expensify/Web-Expensify/pull/35171/files) and [here](https://github.com/Expensify/Web-Expensify/pull/35178)

Those changes don't seem related to me. The problem is that we are accessing 'actionName' of undefined in App. See https://github.com/Expensify/App/issues/11995#issuecomment-1284459683.

**Comment by neil-marcellini** [comment] 2022-10-20 17:43
I'm not able to reproduce on my physical iOS device on prod.

**Comment by neil-marcellini** [comment] 2022-10-20 21:54
Xcode is up to date now. I [asked in Slack](https://expensify.slack.com/archives/C07J32337/p1666302778218049) for an Apple developer admin to help me get set up to run NewDot on my device.

**Comment by neil-marcellini** [comment] 2022-10-20 22:08
Weird, now I can't reproduce this bug.
https://user-images.githubusercontent.com/26260477/197067999-47d6d51b-a5c1-444e-a7cb-2453ce58a9fc.MP4

@sketchydroide @Justicea83 could you try to reproduce it again? If you can't also reproduce let's close this.

**Comment by neil-marcellini** [comment] 2022-10-20 22:50
Georgia confirmed that she also can not reproduce the issue [here](https://expensify.slack.com/archives/C07J32337/p1666303926458979?thread_ts=1666302778.218049&cid=C07J32337) so I'm closing it. Maybe it was a backend fix 🤔

**Closed by neil-marcellini** 2022-10-20 22:50 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Needs Reproduction, Bug
