### ISSUE TITLE
Chat -  All tooltips are dark in light theme

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33086] opened 2023-12-14 17:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:**Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Preferences -> Theme -> Light
4. Check tooltips view

## Expected Result:
All tooltips are light

## Actual Result:
All tooltips are dark

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6313330_1702573156581!image__195_](https://github.com/Expensify/App/assets/78819774/0494e01c-8734-4f98-a1b4-6d8a4e4e2aa6)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment] 2023-12-14 17:21
Not a deploy blocker per se, but should be addressed 👍

**Comment by situchan** [comment] 2023-12-14 17:28
I think this is known and will be fixed as follow-up of light theme live.
cc: @grgia @chrispader

**Comment by trjExpensify** [comment] 2023-12-14 23:32
Asking in the #deployers thread about light theme issues: https://expensify.slack.com/archives/C07J32337/p1702596738786639?thread_ts=1702578131.769549&cid=C07J32337

**Comment by grgia** [comment] 2023-12-14 23:35
Not a bug, this is the design!

**Closed by grgia** 2023-12-14 23:35 UTC
Labels: Engineering, Daily, Bug
