### ISSUE TITLE
[HOLD for payment 2023-07-26]  User can continue to enter magic code value while entered magic code value is being submitted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23087] opened 2023-07-18 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-in page (staging)
2. Enter email & click on continue
3. Enter a wrong, more than 6 digits value in the magic code input field quickly
## Expected Result: 
User shouldn't be able to enter magic code value while the 6-digit values are being submitted
## Actual Result: 
User is able to enter magic code value while the 6-digit values are submitted. The additional values the user enters are filled in the cleared magic code input field

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/299b76d3-8336-4689-bd59-c2db863272c1

https://github.com/Expensify/App/assets/43996225/9569400a-e5ac-433d-8332-90b57947eea2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689662332876779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by wojtus7** [comment] 2023-07-18 13:49
Hi!

Currently I refactor the Magic Code Input component to resolve the https://github.com/Expensify/App/issues/18244 and I think it should fix this issue as well 🤔

**Comment by ishpaul777** [comment] 2023-07-18 14:12
## Proposal

### Problem
User can continue to enter magic code value while entered magic code value is being submitted

### Root Cause
The root cause of this problem is that the `onChangetText` function is triggered even when the magic code is being submitted and the loading process is in progress. As a result, users can continue entering input while the submission is underway.

### Proposed Solution
To address this issue and prevent users from entering input while the submission is ongoing, we propose the following solution:

1. **Pass `isLoading` Prop to MagicInput:** We will modify the `MagicCodeInput` component to accept an additional prop called `isLoading`. This prop will be used to indicate whether the form is currently in a loading state or not. It will be passed from the parent component that handles the form submission process.
```jsx
<MagicCodeInput
   ......
    isLoading={props.account.isLoading}
    autoFocus
/>
```

2. **Check for `isLoading` in `onChangeText`:** Within the `onChangeText` method of the `MagicCodeInput` component, we will add a check to verify whether the `isLoading` prop is true. If it is true, the function will exit.

```jsx
const onChangeText = (value) => {
        if (_.isUndefined(value) || _.isEmpty(value) || !ValidationUtils.isNumeric(value) || props.isLoading) {
            return;
        }
        .........
 }
```

**Comment by jasperhuangg** [comment] 2023-07-18 18:14
It seems this was fixed by https://github.com/Expensify/App/pull/23023. I am unable to reproduce this on staging. Removing the deploy blocker label. I'm going to keep this open until https://github.com/Expensify/App/pull/23023 is on production.

**Comment by arosiclair** [comment] 2023-07-19 18:25
Sounds like @jasperhuangg is managing this so re-assigning

**Comment by garrettmknight** [comment] 2023-07-20 12:48
Sent an offer to @Natnael-Guchima https://www.upwork.com/en-gb/nx/wm/pre-hire/c/8577561/offer/25650765

**Comment by garrettmknight** [comment] 2023-07-21 16:17
@c3024 it does look like you reported earlier than this one so I'll give you the bug bounty. 

@Natnael-Guchima sorry for the confusion, we missed an earlier report so yours is actually a dupe. I'm going to pull the offer, but thanks for reporting all the same.

**Comment by garrettmknight** [comment] 2023-07-21 16:25
@c3024 offer sent. Accept and I'll pay.

**Comment by garrettmknight** [comment] 2023-07-21 16:27
Paid!

**Closed by garrettmknight** 2023-07-21 16:27 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by Natnael-Guchima** [comment] 2023-07-21 18:02
No worries @garrettmknight 🙌
