### ISSUE TITLE
[$500] Onboarding - Changing the URL during onboarding takes back to the first flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46104] opened 2024-07-24 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign out of the staging app if signed in already
2. Log in with a new Gmail address > Continue > Join
3. When the onboarding flow opens select any option in the "What do you want to do today?" flow
4. Click continue
5. Enter a first name in the next flow
6. Before clicking on continue, copy this link ( https://staging.new.expensify.com/settings/profile
) on your browser and hit enter

## Expected Result:
After the page re-loads the user is taken to the current process of the onboarding flow ("What's your name?")

## Actual Result:
The user is taken one step back in the onboarding flow("What do you want to do today?") and the previously filled-out name is displayed after clicking on continue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/691d57c5-a21c-4357-8449-5a88f16fd232

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f2e620ccc728274d</li>
        <li>Upwork Job ID: 1818010709256699718</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>tsa321 | Contributor | 103498083</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-07-24 12:41
We think that this bug might be related to #wave-collect - Release 1

**Comment by tsa321** [comment] 2024-07-24 13:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Onboarding reset to first page if user change URL address

### What is the root cause of that problem?

When user change the url  while in onboarding, in here:

https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/actions/Welcome.ts#L56-L57

The Welcome.isOnboardingFlowCompleted() will be executed again and will navigate back to the first page of onboarding. We don't store the progress in onyx.

### What changes do you think we should make in order to solve the problem?

We could add onboardingDraft in onyx and store the current address in the onboardingDraft. Then the onNotComppleted will navigate tot the last route stored in onBoardingDraft.

**Comment by alexpensify** [comment] 2024-07-26 22:16
I'll test it soon; this GH is on my testing list.

**Comment by alexpensify** [comment] 2024-07-29 19:45
I've tested this one and can confirm it happens. When you get to the name part, I think nothing has been saved, so I'm wondering if we can account for the page without the save action without clicking `Continue` on the first and last name tab. 

![2024-07-29_12-41-42](https://github.com/user-attachments/assets/b51d3c93-06e1-496f-99ef-cb4928093d2f)

**Comment by alexpensify** [comment] 2024-07-29 19:49
Assigning `External`, @mollfpr please review if the proposal will fix this issue. I think we should still take the person to the Name tab since they would click continue in the first tab of options what there account will be used for. Thanks for reviewing!

**Comment by mollfpr** [comment] 2024-07-29 20:48
@tsa321 Thanks for the proposal! I did a test but it seems the `Welcome.isOnboardingCompletedFlow` is not called after refresh.

Instead I found out that the route is set here.
https://github.com/Expensify/App/blob/ba25cb3400ab92ea3c2b618631da8e715b2c6644/src/libs/Navigation/NavigationRoot.tsx#L97-L99

**Comment by mollfpr** [comment] 2024-07-30 05:31
@tsa321 That will be great. Thank you!

**Comment by alexpensify** [comment] 2024-08-02 23:23
@mollfpr, when you get a chance, can you review the latest text? Thanks!

**Comment by mollfpr** [comment] 2024-08-05 19:08
Reviewing!

**Comment by mollfpr** [comment] 2024-08-07 07:04
@tsa321 Thank you for the test branch. It result great! I'm wondering if we can use `ONYXKEYS.LAST_VISITED_PATH` instead of creating a new one?

**Comment by mollfpr** [comment] 2024-08-12 14:32
Thanks @tsa321 for the update and it looks good now!

Let's go with @tsa321 [proposal](https://github.com/Expensify/App/issues/46104#issuecomment-2247880349) then!

🎀 👀 🎀 C+ reviewed!

**Comment by chiragsalian** [comment] 2024-08-12 20:03
Cool, proposal LGTM. Feel free to push up a PR @tsa321

**Comment by alexpensify** [comment] 2024-08-22 13:16
Weekly Update: PR is under review

**Comment by alexpensify** [comment] 2024-08-26 15:22
## Next Steps

This PR is going through the review process. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-09-03 23:16
Catching up from being OOO, I see the PR is moving along.

**Comment by chiragsalian** [comment] 2024-09-06 17:33
@alexpensify, can we increase the pricing of this PR to $500. The scope of the PR changed during development (discussed [here](https://github.com/Expensify/App/pull/48137#issuecomment-2322306030)) to solve two additional bugs on main. Contributor decided to solve it in this PR.

**Comment by alexpensify** [comment] 2024-09-06 18:23
Thanks for this context and done!

**Comment by alexpensify** [comment] 2024-09-18 19:33
Weekly Update: Waiting for this one to go to production

**Comment by alexpensify** [comment] 2024-09-20 22:26
Now we wait for this one to go through automation. It went into production yesterday.

**Comment by alexpensify** [comment] 2024-09-27 18:07
Automation didn't kick in, so I'll need to manually work on the payment process.

**Comment by alexpensify** [comment] 2024-09-30 20:01
Payouts due: 09-27-2024

- [x] Contributor: $500 @tsa321 
- [ ] Contributor+: $500 @mollfpr - please submit a request in Chat

Upwork job is [here](https://www.upwork.com/jobs/~021818010709256699718). 

Closing - I've completed the payment process via Upwork for @tsa321  and @mollfpr will submit a request in Chat.

**Closed by alexpensify** 2024-09-30 20:01 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by garrettmknight** [comment] 2024-10-02 15:15
$500 approved for @mollfpr
