### ISSUE TITLE
[$500] Debit Card - When adding a Card for the first time, an incorrect form of fill-in is loaded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30214] opened 2023-10-23 21:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Sign in with a new acccount
3. Navigate to Settings\Wallet
4. Navigate to the Add a Debit Card menu
5. Return back to Wallet
6. Navigate to the Add a Debit Card menu again

## Expected Result:

The first time you add a debit card you should be brought to the Add debit card page.

## Actual Result:

When adding a Debit Card for the first time you are directed to the "Add bank account" page. The second time you try you will get to the "Add debit card" page.

## Workaround:

Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Kind of... but it sucks.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/3b6c8df6-5827-4a27-bd4a-e2dd993648f4

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b98a768b454991e7</li>
        <li>Upwork Job ID: 1716606223516532736</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-10-23 22:46
>Logging in with a prepared account

What is a "prepared account" and "correct fill-in form"? 

I am not sure what the issue is. What are you expecting to happen @lanitochka17? Can you say it another way?

**Comment by marcaaron** [comment] 2023-10-23 22:50
Oh I see now. It's taking you to the page to add a bank account and not the debit card page.

**Comment by marcaaron** [comment] 2023-10-23 23:17
This can be reproduced on production. The catch is that you have to sign in with a new account. The second time you try to add a debit card it will bring you to the correct page.

**Comment by alexpensify** [comment] 2023-10-24 00:03
Alright with Marc's summary here: https://github.com/Expensify/App/issues/30214#issuecomment-1776175110

I'm going to assign it as an External

**Comment by saraelsa** [comment] 2023-10-24 04:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The first time (with respect to the lifetime of their log-in session) a user tries to add a debit card, they are instead taken to a page where they can link their bank account.

### What is the root cause of that problem?

The `DebitCard` page has two objects of interest: `props.formData.setupComplete` and `prevFormDataSetupComplete` (corresponding to the previous value of the property).

An effect has a filter such that the code of interests runs only if `prevFormDataSetupComplete` is `false` and `props.formData.setupComplete` is `true`. Effectively, if `props.formData.setupComplete` _changes to_ `true`, the code runs.

Immediately once the component initializes, the method `clearDebitCardFormErrorAndSubmit` is called which changes `setupComplete` to `true` and stores this in Onyx.

The first time the user navigates to this page, because `setupComplete` changes from its default `false` to `true`, this code runs. Subsequent navigations to this page do not lead to this because `setupComplete` had been `true` since the beginning.

`continueSetup` calls `kycWallRef.current.continue` where available which calls the `continue` method of the current KYC wall (`BaseKycWall.js`). According to the doc comments, this will:
- get them to add a payment method if none exists
- otherwise, send them to the enable payments page if they haven't completed KYC
- otherwise, send them to the action they requested

According to this logic, the user will be made to add a payment method and directed to add a bank account (there is more logic as to why specifically bank account but that is not relevant here).

It appears to me that `setupComplete` should only be set to `true` by the API once the debit card has successfully been set up to allow the user to complete the payments onboarding process, and that `clearDebitCardFormErrorAndSubmit` setting `setupComplete` to `true` is an error and it should set it to `false` instead. This is supported by the fact that the method is meant to reset the form back to its initial state as described by its documentation comments. The initial state is defined as `defaultProps` in `AddDebitCardPage` and has `setupComplete` set to `false`.

### What changes do you think we should make in order to solve the problem?

Change the value `setupComplete` is set to from `true` to `false` in `clearDebitCardFormErrorAndSubmit` (`PaymentMethods.ts`).

### What alternative solutions did you explore? (Optional)

None.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by alexpensify** [comment] 2023-10-24 22:06
Ahhh good catch @tienifr! I'm going to close this out.

**Closed by alexpensify** 2023-10-24 22:06 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
