### ISSUE TITLE
[$1000] Web - Assign task - User is able to receive a message even after assignee is changed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25404] opened 2023-08-17 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. click + icon from LHN
3. create a new task and assign a user
4. send a text and the text will appear on the other user's side
5. change the assignee for another user
6. send a new text

## Expected Result:
The new message should only send to the newly assigned user

## Actual Result:
The new message is sent to both users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/fb9029db-70e5-47f7-a150-c0c6a5cbfd34

https://github.com/Expensify/App/assets/115492554/e5408335-c8de-4305-bc1c-bcf50febc1eb

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691317679983749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192319bcafd729501</li>
        <li>Upwork Job ID: 1692657439460790272</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by alphaboss1104** [comment] 2023-08-17 18:33
As I see, this isn't a bug.

**Comment by adelekennedy** [comment] 2023-08-18 21:59
I think this is a bug - we don't want someone who was assigned incorrectly to keep receiving messages. Moving to external

**Comment by adelekennedy** [comment] 2023-08-21 17:38
@fedirjh do you agree with the above that this is BE?

**Comment by akamefi202** [comment] 2023-08-21 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is able to receive a message even after assignee is changed

### What is the root cause of that problem?
As long as the unassigned user can access to task page, he can send or receive messages in task page.

### What changes do you think we should make in order to solve the problem?
First, if the user is unassigned, we need to remove that task from LHN.
And navigates to parent report page or Concierge page if the task is unassigned while it's on focus.
I think we need to update `shouldReportBeInOptionList` function for this.
We can remove unassigned task from LHN by comparing `accountID` of user with `ownerAccountID` & `managerID` of the task.
https://github.com/Expensify/App/blob/d1cf9be0d28128e921c2ba606cde680f2fa537d7/src/libs/SidebarUtils.js#L84-L89

And we should block the user accessing the unassigned task page.
We need to update `canAccessReport` function for this and we can implement it by comparing IDs too.
So the user will see "no access" error page if he tries to access the task page again.
https://github.com/Expensify/App/blob/d1cf9be0d28128e921c2ba606cde680f2fa537d7/src/libs/ReportUtils.js#L2552-L2555

As a result, the unassigned user can't access the task page and he won't be able to send or receive messages.

### What alternative solutions did you explore? (Optional)
We can also use `participantAccountIDs` array of report for comparing.
But currently, `participantAccountIDs` array doesn't include `accountID` of the creator.
Also, BE doesn't remove unassigned user id from the array so it contains all previous assignee IDs.
So to use `participantAccountIDs` array, we need to fix BE too.

**Comment by thienlnam** [comment] 2023-08-28 17:15
@fedirjh Yes you're absolutely correct - this is not a bug 

Even though the assignee changed, they are still a participant of the task

**Closed by thienlnam** 2023-08-28 17:15 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
