### ISSUE TITLE
[HOLD for payment 2024-12-17] [$250] Implement tests for reports that should be displayed in LHN

### ISSUE THREAD

**Issue by OlimpiaZurek** [Expensify/App#52032] opened 2024-11-05 12:26 UTC
Tracking issue:  https://github.com/Expensify/App/issues/52031

Develop and implement unit tests to verify that the following report types are correctly displayed in the LHN:

1. Current report: Ensure the currently active report is highlighted appropriately.
2. Reports with violations (RBR): Confirm that reports with outstanding violations are displayed at the top of the list with a red dot indicator.
3. Reports requiring attention (GBR): Validate that reports needing user action display a green dot and are sorted correctly.
4. Report with draft comment: Check that reports with valid draft comments are indicated and sorted by name.
5. Pinned report: Verify that pinned reports are at the top of the list and sorted correctly.
6. Unread chat in Focus Mode: Ensure unread chats in focus mode are displayed with bold text.
7. Archived report in Default Mode: Confirm that archived reports are shown correctly in default mode, sorted by lastVisibleActionCreated.
8. Self-DM report: Verify that self-DM reports are included in the LHN when the corresponding setting is enabled.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857141648927609929</li>
        <li>Upwork Job ID: 1857141648927609929</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 105084341</li>
<li>mkzie2 | Contributor | 105084342</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-11-06 02:21
I take it I'm not needed here?

**Comment by trjExpensify** [comment] 2024-11-12 00:21
@OlimpiaZurek can you confirm what I'm doing with this? Should it be assigned to you? CC: @mountiny

**Comment by mountiny** [comment] 2024-11-12 12:20
We are going to export this issue to the community once the tests framework is setup, that is what we are holding for

**Comment by trjExpensify** [comment] 2024-11-14 17:04
Okay, so I'll drop it to `Weekly` for now.

**Comment by mountiny** [comment] 2024-11-14 19:21
Just like that, its not on hold anymore

**Comment by Tony-MK** [comment] 2024-11-15 13:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Implement tests for reports that should be displayed in LHN.

### What is the root cause of that problem?

LHN items have a historical record of rendering inconsistencies & regressions.

### What changes do you think we should make in order to solve the problem?


Write a unit test to test the [`shouldReportBeInOptionList`](https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/libs/ReportUtils.ts#L6663-L6665) function in [`ReportTestUtils`](https://github.com/Expensify/App/blob/main/tests/utils/ReportTestUtils.ts).

### What specific scenarios should we cover in unit tests to prevent reintroducing this issue in the future?


We'll need to create numerous random reports with these initial characteristics, and their negation(opposite), as either.

1. An expense report with outstanding violations and is not reimbursed.
2. An empty report.
3. A report that is currently viewing.
4. A valid draft comment in the report.
5. A self DM report.
6. A marked report as pinned.
7. A report is unread and is in focus mode.
8. A report is archived and is in default mode.

Then, we'll need to combine these initial characteristics and their negation(opposite) 
in different orders to create a permutation for random reports to ensure we have covered all edge cases the [`shouldReportBeInOptionList`](https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/libs/ReportUtils.ts#L6663-L6665) function be handle. 

For example, a combination of characteristics `3, 4, and negation of 5` will create a report that `is currently being viewed, has a valid draft comment, and is not a self-DM`.

**Comment by Tony-MK** [comment] 2024-11-15 13:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Implement tests for reports that should be displayed in LHN.

### What is the root cause of that problem?

LHN items have a historical record of rendering inconsistencies & regressions.

### What changes do you think we should make in order to solve the problem?


Write a robust unit test to test the [`shouldReportBeInOptionList`](https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/libs/ReportUtils.ts#L6663-L6665) function in [`ReportTestUtils`](https://github.com/Expensify/App/blob/main/tests/utils/ReportTestUtils.ts).

### What specific scenarios should we cover in unit tests to prevent reintroducing this issue in the future?


We'll need to create random reports based on these initial characteristics:

1. An expense report with outstanding violations and is not reimbursed.
2. An empty report.
3. A report that is currently viewing.
4. A valid draft comment in the report.
5. A self DM report.
6. A marked report as pinned.
7. A report is unread and is in focus mode.
8. A report is archived and is in default mode.

To create a robust unit test, we need to combine these initial characteristics and their opposite (negation) in different orders to form a permutation of random reports to ensure any edge case the [`shouldReportBeInOptionList`](https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/libs/ReportUtils.ts#L6663-L6665) function will handle is not left out. 

For example, a combination of characteristics `3, 4, and the opposite of 5` will create a report that `is currently being viewed, has a valid draft comment, and is not a self-DM`.

**Comment by Tony-MK** [comment] 2024-11-15 13:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Implement tests for reports that should be displayed in LHN.

### What is the root cause of that problem?

LHN items have a historical record of rendering inconsistencies & regressions.

### What changes do you think we should make in order to solve the problem?


Write a robust unit test to test the [`shouldReportBeInOptionList`](https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/libs/ReportUtils.ts#L6663-L6665) function in [`ReportTestUtils`](https://github.com/Expensify/App/blob/main/tests/utils/ReportTestUtils.ts).

### What specific scenarios should we cover in unit tests to prevent reintroducing this issue in the future?


We will need to create and test random reports based on these initial characteristics:

1. An expense report with outstanding violations and not reimbursed is displayed at the top of the list with a red dot indicator.
2. Reports needing user action display a green dot and are sorted correctly
3. A report that is currently being viewed and highlighted appropriately.
4. Archived reports, sorted by lastVisibleActionCreated, in default mode.
5. A self-DM report when the corresponding setting is enabled.
6. Unread reports in focus mode and displayed with bold text.
7. Reports with a valid draft comment sorted by name.
8. Marked reports as pinned.

To create a robust unit test, we need to combine these initial characteristics and their opposite (negation) in different orders to form a permutation of random reports to ensure any edge case the [`shouldReportBeInOptionList`](https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/libs/ReportUtils.ts#L6663-L6665) function will handle is not left out. 

For example, a combination of characteristics `3, 4, and the opposite of 5` will create a report that `is currently being viewed, has a valid draft comment, and is not a self-DM`.

**Comment by OlimpiaZurek** [comment] 2024-11-18 15:21
I agree that we need a more detailed proposal here.

**Comment by Tony-MK** [comment] 2024-11-22 00:13
## Proposal
Hi @ishpaul777, I updated my [proposal](https://github.com/Expensify/App/issues/52032#issuecomment-2478850029) and added more technical details based on your [comment](https://github.com/Expensify/App/issues/52032#issuecomment-2482943951).

**Comment by mkzie2** [comment] 2024-11-22 08:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Implement tests for reports that should be displayed in LHN

### What is the root cause of that problem?

This is a new feature
### What changes do you think we should make in order to solve the problem?
1. To verify each type of report in the requirement display in LHN, we need to create a test case with `getOrderedReportIDs` function. This function returns the list `reportID` displayed in LHN. We need to verify this function returns the correct list with the correct order as described in OP

https://github.com/Expensify/App/blob/5f483dc37ccfbb967d8eeb49302d3dfa010f93e9/src/libs/SidebarUtils.ts#L91

> Reports with violations (RBR): displayed at the top of the list with a red dot indicator.

> Pinned report: Verify that pinned reports are at the top of the list and sorted correctly.

> Reports requiring attention (GBR): Validate that reports needing user action display a green dot and are sorted correctly.

> Unread chat in Focus Mode: Ensure unread chats in focus mode are displayed with bold text.

2. For special cases, we can add a test in `tests/unit/SidebarOrderTest.ts`.

- For example for reports with violations (RBR), we can follow this step when creating a test

  1. Create a mock report that we expect it have RBR and merge the data to Onyx
  2. Get `getDefaultRenderedSidebarLinks` with the report above
  3. Use `screen.queryAllByTestId` to verify that we have a red dot


3. We can create some utils function in `LHNTestUtils` to create mock data for each type of report easier

- For example for reports with violations (RBR), we can create a util that returns the necessary Onyx data to expect this report has violation
### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment] 2024-11-25 09:45
@OlimpiaZurek We have some cases that will return early without checking `shouldReportBeInOptionList`. So I think `getOrderedReportIDs` is the best place that we can test. Additionally, we use this function to pass the data in `SidebarLinks`

https://github.com/Expensify/App/blob/51e25af3df2eef49c2ac87e0aef816099f9d3747/src/pages/home/sidebar/SidebarLinks.tsx#L90

https://github.com/Expensify/App/blob/51e25af3df2eef49c2ac87e0aef816099f9d3747/src/libs/SidebarUtils.ts#L139-L145

**Comment by OlimpiaZurek** [comment] 2024-11-25 10:11
@mkzie2 I agree that there are some cases that need to be considered, but I wanted to clarify that the main focus should be on the presence of items in the LHN, rather than their ordering. While `getOrderedReportIDs` plays an important role, the key objective is to ensure we're testing whether a report should appear in the LHN based on `shouldReportBeInOptionList`.

Additionally, we want to add all new tests exclusively to the `tests/ui/LHNItemsPresence.tsx file`, so there won’t be a need to include them in `tests/unit/SidebarOrderTest.ts` or `tests/unit/SidebarTest.ts`.

Once these two adjustments are made, I think we can move forward with your proposal.

**Comment by mkzie2** [comment] 2024-11-25 10:19
@OlimpiaZurek @ishpaul777 So what do I need to update in my proposal?

**Comment by OlimpiaZurek** [comment] 2024-11-25 10:53
@mkzie2 Just update it taking into account this [comment](https://github.com/Expensify/App/issues/52032#issuecomment-2497518926): 
- In the section describing the problem to solve, make sure to emphasize that the goal is to verify the presence of reports in the LHN (using `shouldReportBeInOptionList`), not just their order.
- Update the part about where the tests should be added. All new tests should go into `tests/ui/LHNItemsPresence.tsx` (move it from optional to main solution)

**Comment by mkzie2** [comment] 2024-11-25 11:05
@OlimpiaZurek Thanks, I updated my [proposal](https://github.com/Expensify/App/issues/52032#issuecomment-2493146883).

**Comment by mkzie2** [comment] 2024-12-02 14:47
@ishpaul777 The [PR](https://github.com/Expensify/App/pull/53369) is ready. cc @OlimpiaZurek

**Comment by trjExpensify** [comment] 2024-12-17 12:18
Can you complete the checklist then please, @ishpaul777?

**Comment by mountiny** [comment] 2024-12-17 13:48
@ishpaul777 please add the checklist for all the issues, we try to automate the analytics so we can get better insight into the issues. You can describe what you said in the checklist template

**Comment by trjExpensify** [comment] 2024-12-18 02:08
Thanks! Payment summary as follows: 
 
- $250 to @ishpaul777 for the C+ review
- $250 to @mkzie2 for the PR

Paid, closing!

**Closed by trjExpensify** 2024-12-18 02:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
