### ISSUE TITLE
[HOLD for payment 2024-08-27] [CVP] [$250] Always show primary workspace at the top when submitting an expense

### ISSUE THREAD

**Issue by zsgreenwald** [Expensify/App#46683] opened 2024-08-01 18:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.14-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** everyone
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** n/a
**Issue reported by:** Zach Greenwald
**Slack conversation:** https://expensify.slack.com/archives/C03U7DCU4/p1722529376302179

## Action Performed:
1. Log into Expensify, and make sure you are already tied to a workspace
2. Select Global Create button
3. Select Submit expense
4. Either scan a receipt if you have one, or select Manual
5. Then, under `Recents` underneath the search bar you'll see recents

## Expected Result:
In step 5 above, under Recents, the first option should show your Workspace name and that option should be static

## Actual Result:
In step 5 above, only my recent chats showed up. 

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![IMG_DB902F377E35-1](https://github.com/user-attachments/assets/928dacad-8666-4a9c-a6be-23f8e962f88a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2dd3d58e5ea6e4b</li>
        <li>Upwork Job ID: 1820986743163806073</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103521986</li>
<li>nkdengineer | Contributor | 103523822</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by FitseTLT** [comment] 2024-08-01 19:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Always show primary workspace at the top when submitting an expense
### What is the root cause of that problem?
New Feature Request
### What changes do you think we should make in order to solve the problem?

We already have ordereOptions function here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/OptionsListUtils.ts#L1658-L1671
We need to add an new config for the ordering along with `preferChatroomsOverThreads` to give an option to order policy expense chats then we can return low number if `shouldPrioritizeWorkspaceChat` is true and `option.isPolicyExpenseChat`
Then we can use the new config in `OptionsListUtils.filterOptions` we can pass the param `shouldPrioritizeWorkspaceChat` as true when the iou type is submit [here](https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L159-L160) and inside `OptionsListUtils.filterOptions` we order accordingly the `recentReports` before returning the options result [here](https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/OptionsListUtils.ts#L2491) and [here](https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/OptionsListUtils.ts#L2612).
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-01 20:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Always show primary workspace at the top when submitting an expense
### What is the root cause of that problem?
New Feature Request
### What changes do you think we should make in order to solve the problem?

We already have ordereOptions function here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/OptionsListUtils.ts#L1658-L1671
We need to add an new config like `shouldPrioritizeWorkspaceChat` for the ordering along with `preferChatroomsOverThreads` to give an option to order policy expense chats on top then we can return low number if `shouldPrioritizeWorkspaceChat` is true and `option.isPolicyExpenseChat` in the iteratee of the lodashOrderBy.
Then we can use the new config in `OptionsListUtils.filterOptions`. we can pass the param `shouldPrioritizeWorkspaceChat` as true when the iou type is submit [here](https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L159-L160) and inside `OptionsListUtils.filterOptions` we order accordingly the `recentReports` before returning the options result [here](https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/OptionsListUtils.ts#L2491) and [here](https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/OptionsListUtils.ts#L2612).

_We might need to add the `action` type into our condition may be to order only when it `create` type._
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-02 07:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In step 5 above, only my recent chats showed up.

### What is the root cause of that problem?

We don't prioritize the workspace chat option on the participant page of the money request flow
### What changes do you think we should make in order to solve the problem?
1. In `getOptions` function, we have a config param `sortByReportTypeInSearch` [here](https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/OptionsListUtils.ts#L1805) and if it's `true`, we will sort the recent report option [here](https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/OptionsListUtils.ts#L2136). So we should add an extra param `sortByReportTypeInSearch` with the default value is `false` in `getFilteredOptions` function and pass this param to `getOptions` function [here].(https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/OptionsListUtils.ts#L2246)

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L96
 
Then we pass this param as `true` here
 https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L96

2. Add another config `preferPolicyExpenseChat` in `orderOptions` here and then if it's true, prioritize the WS chat by returning  the minimum value for the policy expense option

```
if (option.isPolicyExpenseChat && preferPolicyExpenseChat) {
    return 0;
}
```

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/OptionsListUtils.ts#L1664

3. Then pass `preferPolicyExpenseChat` as `!!actions` here. We can do this because the action here is the `iouAction` and it only exists when we get the option in the money request flow. 

```
recentReportOptions = orderOptions(recentReportOptions, searchValue, {preferChatroomsOverThreads: true, preferPolicyExpenseChat: !!action});
```

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/OptionsListUtils.ts#L2136

We also need to update this condition here to always sort the recent report in money request flow even if the `searchValue` is empty.

```
if (sortByReportTypeInSearch && (searchValue !== '' || !!action)) {
```
https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/OptionsListUtils.ts#L2132
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-02 07:46
Proposal updated to fix the typo.

**Comment by strepanier03** [comment] 2024-08-07 00:53
I agree we should have the workspace be a default at the top if you're submitting an expense and part of one.

**Comment by JmillsExpensify** [comment] 2024-08-07 22:55
@trjExpensify should we just start by prioritizing the primary workspace?

**Comment by mountiny** [comment] 2024-08-08 23:40
> This would be an alt proposal to https://github.com/Expensify/App/issues/34227, which was aiming to build the recents list based on the action in question.

That one got really convoluted, and ideally, it would require a backend solution—something similar to the quick action NVP but for various types of flows. 

I think this is a bit simpler and we can see if it will be fine for now. Eventually, I guess we cannot avoid using some kind of NVP to store the recent target reports for the individual flows

**Comment by JmillsExpensify** [comment] 2024-08-08 23:52
Cool, I think optimizing for the primary policy would cover the mainline case. If it's easy, I say we go with it and get a quick win.

**Comment by mountiny** [comment] 2024-08-09 00:06
This one seems to be much smaller scope and easier for sure. Given it will cover the mainline case I think we should do this

**Comment by trjExpensify** [comment] 2024-08-09 21:10
Cool, then let's do this then for now. 👍

**Comment by trjExpensify** [comment] 2024-08-12 15:58
@Pujan92 can you review the proposals, please?

**Comment by Pujan92** [comment] 2024-08-13 13:35
I will review it max by tomorrow.

**Comment by trjExpensify** [comment] 2024-08-13 23:11
Great, thanks. We're keen to get this fixed ASAP as it's a critical path. 👍

**Comment by nkdengineer** [comment] 2024-08-14 13:49
> Make sure that the active policy is group policy, i.e. either collect or control, i guess there is a util function for this: to check for paid policies

@allgandalf  I know we have the check about the group paid policy

>  we should not do this for personal

I want to know what that means. For personal here is DM transaction or something else?

**Comment by mountiny** [comment] 2024-08-14 14:32
Thanks @nkdengineer what is your ETA for the PR?

**Comment by nkdengineer** [comment] 2024-08-14 14:37
@mountiny Thanks for assigning, will raise a PR in a few hours.

**Comment by mountiny** [comment] 2024-08-15 07:48
I have made a backend change that should ensure the policy expense chat update is queued when the active policy is changed in NewDot that should fix the issue @trjExpensify saw during his testing https://github.com/Expensify/Auth/pull/12062

**Comment by trjExpensify** [comment] 2024-08-15 09:12
Dope, thanks for that!

**Comment by mountiny** [comment] 2024-08-27 00:22
$250 to @allgandalf and to @nkdengineer please @strepanier03 

I assume we should add a regression test. @nkdengineer @allgandalf can you please propose one with steps that will verify for sure this logic works in the submit expense flow? Thanks

**Comment by strepanier03** [comment] 2024-08-27 19:25
### Payment summary

- $250 - @nkdengineer via Upwork ([offer](https://www.upwork.com/nx/wm/offer/103708020))
- $250 - @allgandalf via Upwork ([offer](https://www.upwork.com/nx/wm/offer/103708060))

**Comment by strepanier03** [comment] 2024-08-27 19:27
Offers sent and reg test created. Will check in this afternoon to take next steps.

**Comment by strepanier03** [comment] 2024-08-27 22:57
Contract paid and closed for @allgandalf. I'll check again in the morning for @nkdengineer's contract.

**Comment by strepanier03** [comment] 2024-08-28 19:18
Will check again later today.

**Comment by strepanier03** [comment] 2024-09-03 15:33
@nkdengineer - friendly bump on accepting the offer so I can pay it out and close this GH.

**Comment by nkdengineer** [comment] 2024-09-04 04:16
@strepanier03 Sorry, I accepted

**Comment by strepanier03** [comment] 2024-09-04 15:54
No worries, thanks for doing that. I'll finish up now and close out.

**Comment by strepanier03** [comment] 2024-09-04 15:56
Paid out the last contract and closed it. We're all set here. 

Thanks for all the hard work everyone!

**Closed by strepanier03** 2024-09-04 15:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
