### ISSUE TITLE
[$500] iOS - Notificiation - New messages are not shown until user is online after selecting notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31765] opened 2023-11-22 23:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login in primary and secondary device as User A and User B respectively.
2. Close app on primary device and send message to User A using the secondary device
3. After User A receives notification, disconnect device from internet
4. Wait 10 seconds and double tap on notification received on primary device

## Expected Result:
App opens to chat and new message is seen

## Actual Result:
App opens to chat and new message is not displayed until user reconnects to internet

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/34783dbc-896a-48d3-8424-b954324d5859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01241a0e0884e93cf1</li>
        <li>Upwork Job ID: 1727467769284608000</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by ta106** [comment] 2023-11-23 10:07
I could not recreate the issue using new expensify app in the app store nor in an ios simulator. can you provide more details

**Comment by promisingcoder** [comment] 2023-11-23 10:43
Proposal for Issue #31765: iOS - Notification - New Messages Not Displayed Until Online After Selecting Notification
Please re-state the problem that we are trying to solve in this issue.
In the iOS version of the app, when a user receives a push notification for a new message, selecting the notification does not display the new message until the user reconnects to the internet. This happens when the app was previously closed and the device is offline at the time of selecting the notification.

What is the root cause of that problem?
The issue likely stems from the app's handling of push notifications and local data synchronization when offline. The push notification handler (index.native.js) might not be updating the relevant Onyx keys (like ONYXKEYS.NETWORK) to reflect the arrival of new messages when offline. Additionally, there might be gaps in how the app manages AppState transitions and utilizes cached data in Expensify.js.

What changes do you think we should make in order to solve the problem?
To address this issue, several modifications are proposed:

Update Push Notification Logic: Enhance the push notification handling in index.native.js to ensure that relevant Onyx keys are updated properly when a notification is received, regardless of the online/offline status.
Optimize Onyx Local Storage Usage: Revise local storage handling to ensure that new messages are cached and retrieved effectively when the app is launched from a notification while offline.
Improve AppState Transition Management: In Expensify.js, refine the management of AppState transitions to check and update the UI with new messages when the app resumes from a notification.
Synchronize Messages with Session Data: Guarantee that session data (ONYXKEYS.SESSION) is correctly maintained or restored, especially for syncing messages related to the session.
Implement Offline Feedback: Utilize OfflineIndicator.js and OfflineWithFeedback.js to provide immediate feedback on the message's offline status and display messages correctly in offline mode.
What alternative solutions did you explore? (Optional)
N/A

By implementing these changes, we can ensure that the app correctly displays new messages when opened from a notification, even in offline scenarios. This approach aims to enhance the user experience by addressing the core issues related to push notification handling and data synchronization in offline mode.

**Comment by promisingcoder** [comment] 2023-11-23 10:45
Contributor details
Your Expensify account email: y95554393@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01169c49d59fd10b60

**Comment by adelekennedy** [comment] 2023-11-27 17:20
I think we're still waiting for more proposals here!

**Comment by adelekennedy** [comment] 2023-12-01 20:34
I don't think we should increase the price on this one as it's a bit of an edge case issue (offline > online with slight delay)

**Comment by adelekennedy** [comment] 2023-12-04 16:29
will give this one a but more time for proposals

**Comment by arhyp** [comment] 2023-12-05 00:32
Contributor details
Your Expensify account email: arkhypfreelancer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017ca78778741aa14c

To address this issue, I propose the following steps:  Offline Data Handling: Enhance the app's ability to cache data, ensuring that recent messages are stored locally. This will allow the app to display new messages even when offline. Notification Interaction: Modify the notification interaction so that tapping on a notification triggers the app to fetch and display the relevant message from local storage if an internet connection is unavailable. Data Sync: Implement a background sync mechanism to update the local cache when the app regains an internet connection, ensuring data consistency. Testing: Rigorous testing on all supported platforms (Android/iOS native and mWeb, MacOS Chrome/Safari, MacOS Desktop) to ensure the solution works seamlessly across all platforms. Implementation Plan:  Analysis & Design: Detailed analysis of the current React Native codebase to identify optimal points for integration of offline data handling and notification interaction enhancements. Development: Incremental development of the proposed solution, ensuring that each step is thoroughly tested. Collaboration: Regular communication with the Expensify team via GitHub and Slack to ensure alignment with project goals and coding standards. Testing & Documentation: Comprehensive testing across all platforms, along with clear documentation of changes made. Pull Request: Submission of a pull request with detailed descriptions, screenshots, and test results for review by Expensify engineers.

**Comment by cubuspl42** [comment] 2023-12-05 11:19
@arhyp

Welcome to Expensify! Please ensure to read the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and check out a few other issues with other contributors' proposals to get a feeling of how the Expensify process works.

**Comment by adelekennedy** [comment] 2023-12-07 21:01
@cubuspl42 any feedback on the two proposals above?

**Comment by cubuspl42** [comment] 2023-12-08 09:20
Neither of the proposal properly sticks to the template, which is just a tip of the iceberg. This is not the kind of the issue which I expect to be solved be newcomers, if it can be solved externally at all.

**Comment by arhyp** [comment] 2023-12-08 17:22
Messages got into spam, sorry. 
Yes, will check and reapply
Thanks

**Comment by cubuspl42** [comment] 2023-12-11 17:53
I guess that while the expected behavior is reasonable, any solution achieving it would be considered too complex to implement. Let's just ask for an internal engineer's opinion.

🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-12-11 17:58
@bondydaa Do you think that it's likely that we could implement a feature like this...

- The user receives a notification about a new message
- The user loses access to the Internet (or manually disables it)
- The user enters the previously received notification and opens the app, seeing it up-to-date with the messages they received the notifications about

...either....

- externally, having in mind the complexity
- internally, having in mind the current priorities

**Comment by adelekennedy** [comment] 2023-12-15 14:20
I think we should close this one - it seems complex and related to a larger question about offline mode and updates. I think we'll just have this sitting here for a while without getting traction

**Comment by bondydaa** [comment] 2023-12-15 17:34
Hmm yeah I'm not too up to date with our current plan for pushing all data out to user but I believe this is part of the Reliable Updates stuff that Ioni is working on is all about. 

I think we close this out for now in favor of waiting until that project is done... I agree that if you were able to get a notification that then we'd expect also that the data has been pushed to your device so it's strange but also a known problem we're working on fixing. 

I think in a scenario where this would actually happen to a user who is on a spotty connection the message would show up quick enough or they probably wouldn't receive the notification at first anyways so I think this is pretty minor.

**Closed by bondydaa** 2023-12-15 17:34 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
