### ISSUE TITLE
[$500] [Track Tax] App crashes when reselecting the same tax in confirmation page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39167] opened 2024-03-28 11:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has at least two tax rates.

1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Start manual request flow.
4. In confirmation page, tap Tax rate.
5. Select another tax.
6. Tap Tax rate again.
7. Tap on the same tax rate in Step 5.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.
On web, it shows console error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/45f6085f-8c24-4bd2-9b87-87c852034973

[Bug6429833_1711613479774!QA.txt](https://github.com/Expensify/App/files/14788892/Bug6429833_1711613479774.QA.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180f0901c994bc80b</li>
        <li>Upwork Job ID: 1775666188401147904</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-28 11:45
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-28 11:45
We think this issue might be related to the #collect project.

**Comment by abzokhattab** [comment] 2024-03-28 13:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when reselecting the same tax in confirmation page
### What is the root cause of that problem?
when selecting a tax in tax picker, we update the name of the selected tax to contain the `Default` word which is not correct. the default is specified by the admin in the tax page and thus the value shouldn't change after selecting another tax in the tax picker..

here we use `getTaxRatesSection` and wrongly pass the `defaultTaxKey` as `selectedTaxRate` that's why the name changes and causes the find not being able to find a tax with that name

https://github.com/Expensify/App/blob/062d53c0ce98185162d153ddd0b5c86e7925213c/src/components/TaxPicker.tsx#L55-L58 

https://github.com/Expensify/App/blob/58515c54afd2541ac439aad0995dfff89178622f/src/libs/OptionsListUtils.ts#L1268-L1271

https://github.com/Expensify/App/blob/58515c54afd2541ac439aad0995dfff89178622f/src/libs/OptionsListUtils.ts#L1236-L1237
### What changes do you think we should make in order to solve the problem?


we need to remove the `selectedTaxRate` when calling the `getTaxRatesSection` function [here](https://github.com/Expensify/App/blob/062d53c0ce98185162d153ddd0b5c86e7925213c/src/components/TaxPicker.tsx#L55-L58) because the `transformedTaxRates` will use the `taxRates?.defaultExternalID` if the defaultTax is not passed:

```js
    const sections = useMemo(() => OptionsListUtils.getTaxRatesSection(taxRates, selectedOptions as OptionsListUtils.Category[], searchValue), [taxRates, searchValue, selectedOptions]);
```

**Comment by bernhardoj** [comment] 2024-03-28 13:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crashes or does nothing on the web when selecting a selected tax rate.

### What is the root cause of that problem?
When we select a tax rate, it will try to find the selected tax rate on the policy tax rates collection by its name.
https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/pages/iou/request/step/IOURequestStepTaxRatePage.js#L43-L46

Every time we select a tax, it will append a `• Default` text to be shown. 
https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/components/TaxPicker.tsx#L57
https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/libs/OptionsListUtils.ts#L1219-L1221

It doesn't alter the real tax name, so when we try to find the tax, it can't find it. For example, if we have tax rate `test (2%)` and it's selected, comparing `test (2%)` with `test (2%) • Default` will always be false. That's why the code can't find anything and throws an error when trying to access the `value` property.

### What changes do you think we should make in order to solve the problem?

We can remove `• Default` from the name or add `• Default` when it's the selected tax, but I think the real problem here is that the `• Default` word shouldn't be appended to a selected tax. Default !== selected. The real problem is we are passing the selected tax rate as the default key,
https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/components/TaxPicker.tsx#L56-L57

and I'm pretty sure that's because we are passing the default rate as the selected tax rate here,
https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/pages/workspace/taxes/WorkspaceTaxesSettingsWorkspaceCurrency.tsx#L57-L58

and it makes sense since for the above page (and foreign currency tax rate), we select the default value, so the selected is the same as the default for both of those pages. To fix it, we should introduce a new props to TaxPicker called `defaultTaxKey`and we will use that instead of the selected value.
https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/components/TaxPicker.tsx#L56-L57

**Comment by sakluger** [comment] 2024-04-03 23:26
Added to the wave-collect project and added the external label.

**Comment by sakluger** [comment] 2024-04-09 22:39
Thanks for retesting @getusha. I'll close it for now.

**Closed by sakluger** 2024-04-09 22:39 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
