### ISSUE TITLE
[HOLD for payment 2023-10-24] [$250] Additional Details - Duplicate offline indicator in Enable Payment Page.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29438] opened 2023-10-12 13:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697012903021189

## Action Performed:
1. Login with any account
2. Go to Enable Payment page (/enable-payments).
3. Go offline
4. Observer the offline indicator.

## Expected Result:
Offline indicator shouldn't duplicate

## Actual Result:
Duplicate offline indicator is duplicate

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Screenshot 2023-10-11 at 15 31 17](https://github.com/Expensify/App/assets/93399543/bba510f6-9ad1-426a-ace4-493beb3af6b6)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
![Screenshot_20231012_085923_Chrome (1)](https://github.com/Expensify/App/assets/93399543/faea85c4-cd3e-4a9a-ac9c-ff76f45b6030)

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/4d09bff0-73b4-47d1-b5e8-0e8ebe05cbc0

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/45be9791-cc75-4abc-9227-0e2d2d40a4a4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![Screenshot 2023-10-11 at 15 32 03](https://github.com/Expensify/App/assets/93399543/52640011-6433-4e38-b19c-a66d0bafbf4b)

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![Screenshot 2023-10-11 at 15 31 37](https://github.com/Expensify/App/assets/93399543/12b4d2bf-a058-4769-ba53-81c43f632c45)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c703cecba895920</li>
        <li>Upwork Job ID: 1712458057448759296</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 27183809</li>
<li>hungvu193 | Contributor | 27183810</li>
<li>hungvu193 | Reporter | 27183812</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-12 13:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Offline Indicator is duplicate at Enable Payment page when offline.
### What is the root cause of that problem?
We're using ScreenWrapper to wrap our logic of EnablePaymentPage here, however inside `AdditionalDetailsStep` we also have the `OfflineIndicator` which caused this issue:
https://github.com/Expensify/App/blob/771b8c58e9faaa863a483aa8c2bf8bbf38b5f72b/src/pages/EnablePayments/EnablePaymentsPage.js#L49-L51
https://github.com/Expensify/App/blob/771b8c58e9faaa863a483aa8c2bf8bbf38b5f72b/src/pages/EnablePayments/AdditionalDetailsStep.js#L246
### What changes do you think we should make in order to solve the problem?
Since `ScreenWrapper` already had the `OfflineIndicator` itself. We can remove `OfflineIndicator` inside `AdditionalDetailsStep`.

Deep diving, `AdditionalDetailsStep` have another view with ScreenWrapper here:
https://github.com/Expensify/App/blob/771b8c58e9faaa863a483aa8c2bf8bbf38b5f72b/src/pages/EnablePayments/AdditionalDetailsStep.js#L148-L151
We should add `shouldShowOfflineIndicator={false}` to this ScreenWrapper, or replace it with View to avoid duplicate OfflineIndicator.

Also inside `OnfidoStep`, we have `FullPageOfflineBlockingView`, so when we render the `OnfidoStep` we will have both `FullPageOfflineBlockingView` and `OfflineIndicator` at the bottom:
https://github.com/Expensify/App/blob/771b8c58e9faaa863a483aa8c2bf8bbf38b5f72b/src/pages/EnablePayments/OnfidoStep.js#L64-L66
we should avoid that by adding props `shouldShowOfflineIndicator` to our `ScreenWrapper` of `EnablePaymentsPage` component with the condition that only show the OfflineIndicator when offline and the currentStep is not Onfido.


### What alternative solutions did you explore? (Optional)
N/A

**Comment by mountiny** [comment] 2023-10-12 14:10
decreasing the price as its minor issue

**Comment by gs3bopar** [comment] 2023-10-12 17:22
Contributor details
Your Expensify account email: gurkaransingh10@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0176028098f8a29acb

**Comment by sobitneupane** [comment] 2023-10-13 10:00
@laurenreidexpensify I will be unavailable next week. Therefore, I am unassigning myself from the issue. Please feel free to assign it to another C+.

**Comment by akinwale** [comment] 2023-10-13 14:40
@hungvu193's [proposal](https://github.com/Expensify/App/issues/29438#issuecomment-1759602696) correctly identifies the root cause and the suggested solution is comprehensive enough with attention to detail. I recommend moving forward with this.

🎀 👀 🎀 C+ reviewed.

**Comment by robertjchen** [comment] 2023-10-13 17:21
Thanks, the proposal makes sense to me 👍

**Comment by laurenreidexpensify** [comment] 2023-10-24 11:20
Payment Summary 

- @akinwale - C+ $250 + 50% urgency bonus -  payment issued in Upwork 
- @hungvu193 - Bug Report $50 - payment issued in Upwork 
- @hungvu193 - Issue Fix $250 + 50% urgency bonus - payment issued in Upwork

**Comment by laurenreidexpensify** [comment] 2023-10-25 10:00
@akinwale bump for checklist so we can close this one out. Thanks

**Comment by akinwale** [comment] 2023-10-25 10:02
> @akinwale bump for checklist so we can close this one out. Thanks

Will get to it in a few hours.

**Comment by akinwale** [comment] 2023-10-25 21:08
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This particular case was missed when the Additional Details page was added.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Launch Expensify
2. Navigate to the Enable Payment page (/enable-payments).
3. Turn off the network connection on the device to go offline.
4. Scroll to the bottom of the page (on smaller screens).
5. Verify that only one "network offline" message is visible.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2023-10-25 21:09
@laurenreidexpensify Done!

**Closed** 2023-10-26 10:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
