### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250]  Tags - App returns to tag page after tapping back button on workspace editor

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51414] opened 2024-10-24 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5123688
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has imported dependent tags (attached below).

1. Launch ND or hybrid app.
2. Go to workspace settings > Tags.
3. Tap on any main tag.
4. Tap app back button to go back to main tag page.
5. Tap app back button to return to workspace editor.
6. Tap app back button again.

## Expected Result:
App will return to workspace list

## Actual Result:
App returns to tag page after tapping back button on workspace editor.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/881ffdd1-843d-45a5-b634-eb864f53ab56

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849826177749803490</li>
        <li>Upwork Job ID: 1849826177749803490</li>
        <li>Last Price Increase: 2024-10-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by IuliiaHerets** [comment] 2024-10-24 13:56
We think that this bug might be related to #wave-collect - Release 1

**Comment by Julesssss** [comment] 2024-10-24 15:22
Regression, but not a blocker. Removing label.

**Comment by kadiealexander** [comment] 2024-10-25 05:02
Reassigning as I'm OOO for the next two weeks.

**Comment by Shahidullah-Muffakir** [comment] 2024-10-27 23:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app gets stuck on the same page after we click the back button.

### What is the root cause of that problem?
I believe it has the exact same root cause as this issue: https://github.com/Expensify/App/issues/50695
The issue stems from this code:
https://github.com/Expensify/App/blob/9508b1740083716708c3e6dd4cbfaf90254e7a98/src/libs/Navigation/linkTo/index.ts#L120-L127
1. We attempt to replace the current RHP (Right Hand Panel) screen with the fallback/backTo route (Tags page in this issue)
2. The replace operation correctly sets the "Tags page" as the current route
3. However, the Tags route already exists in our route stack at routes.at(-2)
4. When we perform the replace operation, we end up with duplicate Tags page routes:
       1. One from the existing stack
       2. Another from the replace operation
### What changes do you think we should make in order to solve the problem?
To resolve this issue and similar ones, we can change code to use navigate instead of replace when the RHP closes: [Here](https://github.com/Expensify/App/blob/9508b1740083716708c3e6dd4cbfaf90254e7a98/src/libs/Navigation/linkTo/index.ts#L127)

`action.type = CONST.NAVIGATION.ACTION_TYPE.NAVIGATE;`
This change will allow us to navigate to the existing fallback route without creating a duplicate. It brings the Tags page to the front of the stack while removing the current route.

https://github.com/user-attachments/assets/639d3d02-77f8-4dde-84be-2393039084bc

**Comment by mvtglobally** [comment] 2024-11-08 15:27
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-11-13 16:55
@Julesssss, was this an internal issue? It looks like no external contributor was involved.

**Comment by Julesssss** [comment] 2024-11-14 12:05
Hey, it looks like @twilight2294 was the PR author, and @paultsimura was the C+ reviewer.

**Comment by Julesssss** [comment] 2024-11-14 12:15
Aha, thank you!

**Closed by Julesssss** 2024-11-14 12:15 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
