### ISSUE TITLE
[$1000] New messages aren't showing up as unread and bold in LHN

### ISSUE THREAD

**Issue by sakluger** [Expensify/App#23599] opened 2023-07-25 22:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. I received a push notification of a new message
2. I looked in NewDot but the chat doesn't show up in the LHN (I'm in Focus mode)
3. When I switch to Most Recent mode, the chat shows up as read

## Expected Result:
New messages should always show up as unread and appear in the LHN

## Actual Result:
The message shows as read in the LHN in Most Recent mode, and doesn't show up at all in the LHN in focus mode.

## Workaround:
I get these messages as desktop notifications, but I still have missed some.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.45-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Not sure

**Email or phone of affected tester (no customers):** sasha@expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

Desktop notification:
![image](https://github.com/Expensify/App/assets/5997400/c2902cee-d6d3-4772-ad83-7e2cb6e2b107)

LHN in Most Recent mode:

![image](https://github.com/Expensify/App/assets/5997400/ab5dd9a3-0e46-49de-97e1-eea49667b4db)

**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690309413291369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01519e1ea6dde7dd1f</li>
        <li>Upwork Job ID: 1683968671592755200</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-07-25 22:33
@NikkiWines reproduced this, so I'm going to go ahead and add the external label myself to move it along.

**Comment by sakluger** [comment] 2023-07-26 16:35
@tienifr thanks for the proposal, do you know if this is a regression? I never noticed this behavior until yesterday (or maybe Monday at the earliest).

**Comment by StevenKKC** [comment] 2023-07-26 16:39
I think his issue has the same root cause as https://github.com/Expensify/App/issues/23446, and I have already posted my proposal in https://github.com/Expensify/App/issues/23446#issuecomment-1647592478.

**Comment by sakluger** [comment] 2023-07-26 17:43
FYI we're treating this as a fire and so I've applied the hourly label.

**Comment by mallenexpensify** [comment] 2023-07-26 20:12
Thanks for treating as a fire and assigning `hourly`, this is happening to me too.  I updated the title to include `and bold` since bold is what I searched for yesterday when I filed a similar bug report.

**Comment by lschurr** [comment] 2023-07-26 23:15
Should we take this internal @sakluger @mallenexpensify or are we waiting for proposals here?

**Comment by lschurr** [comment] 2023-07-26 23:16
@Santhosh-Sellavel are you able to review the proposal here?

**Comment by Santhosh-Sellavel** [comment] 2023-07-27 21:13
> I think it's a regression from #22645. Before that the new action subscriber was an object and allowed only one subscriber (i.e. `reportID`) at a time. Thus the later report subscriber would overwrite the previous ones. But then it was migrated to a list, which requires a manual un-subscription.

@mountiny @allroundexperts Seems its a regression from #22645, please take care.

**Comment by mountiny** [comment] 2023-07-27 21:40
The issue in op has been fixed by the PR from Hanno, right @allroundexperts ?

**Comment by lazar-stamenkovic** [comment] 2023-07-28 02:33
> @lazar-stamenkovic Can you please confirm this?

@allroundexperts confirming.  seemed it's related to #22645.  but while working on the PR #22645,  subscribeToNewActionEvent and unsubscribeFromNewActionEvent in ReportActionsView was correctly called and it doesn't have this issue. 

But now unsubscribeFromNewActionEvent isn't called and subscribeToNewActionEvent is called for previous report id when move to other pages. 
But I can see some properties and actions are updated in ReportActionsView.   not sure which PR it was updated in.
for example, unsubscribeFromNewActionEvent is removed in ReportActionsView. 
today i will check this in detail.

**Comment by lschurr** [comment] 2023-07-31 14:27
To clarify, are you working on this @allroundexperts? Should this GH be assigned to you?

**Comment by mountiny** [comment] 2023-07-31 15:26
I think we can close this issue now

**Comment by lschurr** [comment] 2023-07-31 16:48
Closing!

**Closed by lschurr** 2023-07-31 16:48 UTC
Labels: External, Daily, Help Wanted, Bug
