### ISSUE TITLE
[$500] Chat - Inconsistent in URL display while editing comment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28162] opened 2023-09-25 16:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter an url and send
4. Long press the sent message and tap edit comment
5. Delete the entire message and enter the same url and send
6. Note the url is not shown as link
7. Again perform step3-step4
8. Delete the entire message and enter different url and send

## Expected Result:
If an url is sent and edited with same url, then it is not shown as link. But if we enter different url while editing, then it is shown as link. There should not be inconsistent behaviour when user send url while editing comment

## Actual Result:
If an url is sent and edited with same url, then it is not shown as link. But if we enter different url while editing, then it is shown as link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/04fb764b-6ad0-40e0-a5fb-0a3680c02863

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bb50037929a38de</li>
        <li>Upwork Job ID: 1706695143749767168</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-25 22:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When editing a comment, any existing text that looks like a link will be transformed to a markdown link upon the save.

### What is the root cause of that problem?
Any URL looking text is not considered when editing a comment because   `parser.replace(newCommentText)` is called anytime a comment is editing, meaning that the previous text formatting will be lost and transformed to markdown. 

### What changes do you think we should make in order to solve the problem?

We should find  a better way to handle the URL intentional deletes from the comment done by this function 

https://github.com/Expensify/App/blob/f5409e72f3517022421a98c7b0a9d8f7f075f06c/src/libs/actions/Report.js#L1128-L1137

And at the same time, preserve any markdown that were only in the original comment. By finding which links that were actually added upon the current and the existing ones.

So before transforming the edited text to a markdown, we can run this function that will return an array of the added links vs what's been already there. 
```
const getAddedMarkdownLinks = (parser, newComment, oldComment) => {

    const linksInOld = parser.extractLinksInMarkdownComment(oldComment);
    const linksInNew = parser.extractLinksInMarkdownComment(newComment);


    return linksInOld === undefined || linksInNew === undefined ? [] : _.difference(linksInNew, linksInOld);
}
```

And the apply `handleUserDeletedLinksInHtml`. 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by agilejune** [comment] 2023-09-26 23:57
it's intentional behaviour , dupe of https://github.com/Expensify/App/issues/24258

**Closed** 2023-09-27 13:11 UTC
Labels: External, Daily, Help Wanted, Bug
