### ISSUE TITLE
Web - State field in connect bank account does not display selected value on revisit

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23792] opened 2023-07-28 13:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open bank account, click connect manually, fill in step 1 details and continue
6. Click on state, select any value
7. Reopen state and search for any non existing value or empty the search and go back
8. Reopen state field and observe that instead of current selected value (like we do on similar fields like timezone, pronouns), it displays value kept in step 7

## Expected Result:
App should display current selected value when we revisit state field in connect bank account like we do on timezone and pronouns page

## Actual Result:
App does not display current selected when we change search in state field and revisit in connect back account.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f6a53e64-8d19-4a18-b338-b25c1a0997b8

https://github.com/Expensify/App/assets/93399543/004ec691-06fd-4535-934c-92940fec379c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690527470539109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-07-28 13:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
State field in connect bank account does not display selected value on revisit.

### What is the root cause of that problem?
We are setting the value for `searchValue` in `StatePicker` component, and in the company step that component is not being unmounted. And whenever we are opening/clicking on state selector, we are just changing the value of `setIsPickerVisible` state.

And as that component is never unmounted, the state is preserved/not getting reset.

### What changes do you think we should make in order to solve the problem?
We need to set the state whenever we open or close the modal.
We have useEffect - https://github.com/Expensify/App/blob/a5373eb50f73bc8a33f7aa5e14059523c7645cf1/src/components/StatePicker/index.js#L38-L40

That sets the searchValue. We can add the `isPickerVisible` to dependency array.

Alternatively,
we can also set the state in `showPickerModal` and `hidePickerModal` method of `StatePicker` component

result - 

https://github.com/Expensify/App/assets/27822551/d877b238-8e97-4ccd-a2a4-5096c94dec7e


### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-07-28 13:17
Same RCA but different component - https://github.com/Expensify/App/issues/23768

I have submitted proposal there as well

**Comment by s77rt** [comment] 2023-07-28 18:05
We can close this as a dupe.

**Comment by zanyrenney** [comment] 2023-07-31 11:54
closing as dupe!

**Closed by zanyrenney** 2023-07-31 11:54 UTC
Labels: Daily, Overdue, Bug
