### ISSUE TITLE
[HOLD for payment 2024-07-10] [$1000] Double click enter to select value on pronouns and timezone edit pages navigates "back" twice

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24074] opened 2023-08-02 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to avatar > settings > profile > pronouns 
2. Search for a value that matches i.e "He / Him"
3. Double tap enter to select the value
4. Observe you're navigated back to the Settings page (i.e two pages in the nav stack)

Note: Same results on the `timezone` edit selection page. 

## Expected Result:
Use should only navigate back the one page in the nav stack when making a selection on the edit page.

## Actual Result:
"Multi-tapping" is recognised and navigates back as many pages as you press enter. E.g twice = two pages, three times = three pages etc. 

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
 

https://github.com/Expensify/App/assets/43995119/400af392-12ad-4ced-9220-681b9b876da6

 
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690794214667299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd11cd8ee50c8dff</li>
        <li>Upwork Job ID: 1691023835344474112</li>
        <li>Last Price Increase: 2023-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>huzaifa-99 | Contributor | 26238925</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by jfquevedol2198** [comment] 2023-08-02 23:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Double enter click to select value on pronouns and timezone navigates user to main page/main settings page

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/024d210bc0b5a0454b62a72de60057af67cdd045/src/components/SelectionListRadio/BaseSelectionListRadio.js#L190-L205

When click Enter key, its calling callback of `useKeyboardShortcut` every times.
Some components are doing update action on clicking `Enter` key and trying to run `Navigation.goBack`. So its trying to go back everytimes.

### What changes do you think we should make in order to solve the problem?
Wrap callback of `useKeyboardShortcut` by `_.debounce`
```javascript
    useKeyboardShortcut(
        CONST.KEYBOARD_SHORTCUTS.ENTER,
        _.debounce(() => {
            const focusedOption = flattenedSections.allOptions[focusedIndex];

            if (!focusedOption) {
                return;
            }

            props.onSelectRow(focusedOption);
        }, 500),
        {
            captureOnInputs: true,
            shouldBubble: () => !flattenedSections.allOptions[focusedIndex],
        },
    );
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by trjExpensify** [comment] 2023-08-07 10:34
Ah, this got assigned to me while I was OoO. Sorry for the delay! I can reproduce this one on desktop as well, so ticked that platform off and removed the `needs reproduction` label. 

I'd quite like an opinion from @mountiny on the expected result here. I don't really see the real world use of "multi-tapping" enter to go back multiple pages in the nav stack, whether that be two, three or ten pages. So IMO, we should just go back the once (because that's the behaviour after the selection on the page you're pushed to). What do you think?

**Comment by trjExpensify** [comment] 2023-08-11 16:25
Bump @mountiny, maybe @shawnborton you have an opinion on this one as well. :)

**Comment by shawnborton** [comment] 2023-08-11 16:44
"App should go back once on twice enter click to select value on pronouns or timezone page" - I don't think I understand what this means?

**Comment by trjExpensify** [comment] 2023-08-11 16:54
😅 TL;DR 

If you're a few pages deep in the nav, open up a push to page edit screen. "double tap" enter to select the value and it will navigate you back two pages in the app stack. If you triple tap, it goes back three pages etc.  

IMO, we should just go back the once (because that's the behaviour after the selection on the page you're pushed to) however gung-ho you are with the enter button to make the selection.

**Comment by shawnborton** [comment] 2023-08-11 16:57
Got it. Yup, I agree with that.

**Comment by trjExpensify** [comment] 2023-08-14 09:47
Cool, nice! Updated the OP to reflect that and moved this on.

**Comment by jfquevedol2198** [comment] 2023-08-14 10:48
Here is my [Updated Proposal](https://github.com/Expensify/App/issues/24074#issuecomment-1663109817)

**Comment by jfquevedol2198** [comment] 2023-08-14 13:37
@parasharrajat I added some explanations

**Comment by jfquevedol2198** [comment] 2023-08-14 13:46
@parasharrajat Please check [updated proposal](https://github.com/Expensify/App/issues/24074#issuecomment-1663109817)

**Comment by mountiny** [comment] 2023-08-15 17:53
LEts make sure the solution is applied to any place we navigate after enter ideally

**Comment by jfquevedol2198** [comment] 2023-08-18 16:31
debouncing was that I already proposed in the beginning.

**Comment by trjExpensify** [comment] 2023-08-21 11:30
@mountiny, does this work for you? https://github.com/Expensify/App/issues/24074#issuecomment-1684143811

**Comment by mountiny** [comment] 2023-08-21 12:29
Sounds good to me

**Comment by trjExpensify** [comment] 2023-10-30 11:56
Cool, updated the title to reflect that!

**Comment by trjExpensify** [comment] 2023-11-22 15:49
@parasharrajat https://github.com/Expensify/App/pull/29317 has been closed. What's the deal now?

**Comment by trjExpensify** [comment] 2023-12-18 13:16
Bump @parasharrajat? https://github.com/Expensify/App/issues/24074#issuecomment-1823025176

**Comment by trjExpensify** [comment] 2024-01-10 22:08
@parasharrajat can we close this? Whatever we're waiting on is super unclear and it's low value, so I vote we just close it.

**Comment by trjExpensify** [comment] 2024-01-11 21:59
@huzaifa-99 are you able to address the comments in [the PR](https://github.com/Expensify/App/pull/25604) next week?

**Comment by trjExpensify** [comment] 2024-01-30 13:54
👋 Can we get an update on this, please? Thanks!

**Comment by trjExpensify** [comment] 2024-02-27 12:34
@huzaifa-99 there are conflicts in the PR to resolve. :)

**Comment by trjExpensify** [comment] 2024-04-27 12:50
What's going with this PR? It hasn't been touched for over a month and it has a bunch of conflicts.

**Comment by trjExpensify** [comment] 2024-05-07 10:21
How'd that go?

**Comment by mountiny** [comment] 2024-05-23 09:57
Wowie, 👴 shots from the past

**Comment by mountiny** [comment] 2024-05-30 13:19
@huzaifa-99 QA mentioned that some parts of this bug were not resolved https://github.com/Expensify/App/pull/25604#issuecomment-2139412505

**Comment by trjExpensify** [comment] 2024-06-07 16:08
👋 checklist time!

**Comment by mountiny** [comment] 2024-06-12 12:36
@huzaifa-99 @parasharrajat can you bring the discussion back here from the PR please, what are the next steps?

**Comment by trjExpensify** [comment] 2024-06-19 19:41
Any luck?

**Comment by mountiny** [comment] 2024-06-20 22:17
@parasharrajat have you got around to this?

**Comment by trjExpensify** [comment] 2024-06-24 09:57
@huzaifa-99 how are you getting on here?

**Comment by mountiny** [comment] 2024-06-25 10:50
Merged, lets be on a look out to verify correct behaviour here, thanks!

**Comment by trjExpensify** [comment] 2024-07-02 15:41
Is this not on prod yet? 😕

**Comment by mountiny** [comment] 2024-07-03 20:06
I believe it just got deployed to production

**Comment by trjExpensify** [comment] 2024-07-10 17:52
Checklist time!

**Comment by trjExpensify** [comment] 2024-07-15 18:37
Okay and confirming [one regression](https://github.com/Expensify/App/issues/24074#issuecomment-2192540685)?

**Comment by mountiny** [comment] 2024-07-15 23:12
I am fine with keeping the full price on this one. This issue was created in August 2023, and it's been a long battle. There were regressions and I think we are still trying to find the ideal solution, but @huzaifa-99 's solution got us into a better place and it was lots of work and effort to do so $1000 seems fair.

**Comment by mountiny** [comment] 2024-07-16 15:58
For the regression tests, I think we just need one page like `PronounsPage -> /settings/profile/pronouns` and make sure the tester clicks really fast to see if the page opens/ navigates mulitple times.

I dont think its viable to test all these pages

**Comment by trjExpensify** [comment] 2024-07-17 14:26
Alright, so payment summary as follows: 

- $1,000 to @parasharrajat for the C+ review (go ahead and request)
- $1,000 to @huzaifa-99 for the fix (offer sent!)

**Comment by trjExpensify** [comment] 2024-07-17 14:28
As for the regression test, I agree with suggesting 1. Can you make this more readable and standardised in a format of numbered steps that a tester can repeatably follow if we were to add this to TestRail, @parasharrajat?

**Comment by trjExpensify** [comment] 2024-07-18 01:31
>But I can't list down steps for each page as each has separate functionality.

I thought we agreed on just the one, so we can focus on pronouns or something? 

>I think we just need one page like PronounsPage -> /settings/profile/pronouns

**Comment by trjExpensify** [comment] 2024-07-19 18:43
Cool done, closing!

**Comment by dhanashree-sawant** [comment] 2024-07-19 19:09
Hi @trjExpensify, @mountiny, @parasharrajat is this issue eligible for reporting bonus?

**Comment by trjExpensify** [comment] 2024-07-23 00:46
Oh yeah, this is old and I didn't spot the `reportedBy`. So yes, I believe this is still eligible for $50 for the bug report. Are you still on Upwork?

**Comment by dhanashree-sawant** [comment] 2024-07-23 02:50
Thanks @trjExpensify, Yes I am still on upwork, here is my profile link
https://www.upwork.com/freelancers/~016c7b8ae165dc0bda
Actually the issue was created before 31st August 2023 (the deadline after which we changed reporting bonus from 250 to 50 dollars) but at this stage of the project, I will be happy with whatever you decide.

**Comment by trjExpensify** [comment] 2024-07-23 11:11
Yep, that makes sense. We honour those. 

Payment summary as follows: 

- $250 to @dhanashree-sawant for the bug report 

Offer sent!

**Comment by dhanashree-sawant** [comment] 2024-07-23 11:13
Many Thanks @trjExpensify, I have accepted the offer.

**Comment by trjExpensify** [comment] 2024-07-23 11:22
Paid, closing.

**Closed by trjExpensify** 2024-07-23 11:22 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-03 19:08
$1,000 approved for @parasharrajat
