### ISSUE TITLE
[HOLD for payment 2024-06-28] [$125] [Search v1] No background color placeholder exists for receipt thumbnail

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#43393] opened 2024-06-10 15:39 UTC
Coming from [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1718032675442129), the receipt thumbnail doesn't have a placeholder background color.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019803a773929eed48</li>
        <li>Upwork Job ID: 1800191951832943611</li>
        <li>Last Price Increase: 2024-06-10</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102688635</li>
<li>Krishna2323 | Contributor | 102688638</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by shawnborton** [comment] 2024-06-10 15:41
The color should be the same that we use for the empty state thumbnail: 
![CleanShot 2024-06-10 at 17 41 16@2x](https://github.com/Expensify/App/assets/2319350/f16f055a-7a2c-48a3-8020-d3b9a119c0a4)

Which probably means we need to consider the hover state too - I think we bump that background color a shade up when the expense or report row is hovered.

**Comment by shawnborton** [comment] 2024-06-10 16:25
Ah okay, then if that's the case, let's just use that same exact BG color from your screenshot.

**Comment by TheGithubDev** [comment] 2024-06-10 20:56
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue:**
The problem is that no background color placeholder exists for the receipt thumbnail in the Search tab, resulting in a visually inconsistent user experience when the receipt thumbnail is not loaded.

### **What is the root cause of that problem?**
The root cause of this problem is that no background color is applied to the container of the receipt thumbnail. The relevant code snippet is:

```javascript
<View style={[StyleUtils.getWidthAndHeightStyle(variables.h36, variables.w40), StyleUtils.getBorderRadiusStyle(variables.componentBorderRadiusSmall), styles.overflowHidden]}>
```
The container lacks a background color style, which causes it to appear blank when the thumbnail is not loaded.

**What changes do you think we should make in order to solve the problem?**
We should add a background color to the container of the receipt thumbnail. The background color can be applied by modifying the style to include a background color from the existing styles. Here are the specific changes:

1. **Add Background Color Style:**
   - Apply a background color style to the container of the receipt thumbnail. This can be done by using a background color from the existing styles, such as `styles.activeComponentBG` or `styles.hoveredComponentBG`.

Example of how the changes might look:

```javascript
<View style={[
    StyleUtils.getWidthAndHeightStyle(variables.h36, variables.w40), 
    StyleUtils.getBorderRadiusStyle(variables.componentBorderRadiusSmall), 
    styles.overflowHidden,
    styles.activeComponentBG // Added background color
]}>
```

Alternatively, if you want to handle the hovered state:

```javascript
<View style={[
    StyleUtils.getWidthAndHeightStyle(variables.h36, variables.w40), 
    StyleUtils.getBorderRadiusStyle(variables.componentBorderRadiusSmall), 
    styles.overflowHidden,
    isHovered ? styles.activeComponentBG : styles.hoveredComponentBG // Conditional background color based on hover state
]}>
```

### **What alternative solutions did you explore?**
1. **Using a Default Image Placeholder:** Instead of a solid background color, a default image or icon could be used as a placeholder. This would provide a more visually appealing placeholder but might require additional assets and logic to handle the image.

2. **Implementing a Loading Spinner:** Adding a loading spinner or skeleton loader within the container until the thumbnail is fully loaded. This approach enhances user feedback but could complicate the loading logic.

3. **CSS Gradients:** Using CSS gradients as a background to provide a more visually interesting placeholder. This approach could improve aesthetics but might not be consistent with the rest of the app's design language.

After considering these alternatives, applying a simple background color using `styles.activeComponentBG` _**could be**_ deemed the most straightforward and consistent solution, ensuring a seamless user experience without introducing additional complexity.

_(Rayyan here from Upwork, I own an agency, so feedback would be beneficial)_

**Comment by luacmartins** [comment] 2024-06-11 14:50
I think the proposal looks good, but @Krishna2323 please note that we removed the hover state from the receipt component and are now just using `theme.border` color for the background, we should use that.

**Comment by trjExpensify** [comment] 2024-06-28 19:20
I don't think we need a regression test for this, and it was a cheeky bug in a new feature release. 

Payment summary as follows: 

- $125 to @Krishna2323 for the fix
- $125 to @dukenv0307 for C+ 

Paid both, closing!

**Closed by trjExpensify** 2024-06-28 19:20 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
