### ISSUE TITLE
Thread - Keyboard covers thread history if open thread for new message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23386] opened 2023-07-22 00:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition - User B has sent a new message to user A; User A has not yet read it; Login as user A
1. Open https://staging.new.expensify.com/
2. Open chat with user B from the precondition
3. Long press new message from user B
4. Tap on "Reply in thread"
5. Tap on message box to invoke keybaord

## Expected Result:
Chat history moves up when the keyboard is invoked so it doesn't overlap with the messages

## Actual Result:
Keyboard covers the recent messages in thread chat.
Reproduced the issue only when the thread was invoked for a new message (with "new" green marker above). Reproduced 5/8 times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0

**Reproducible in staging?:**Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ade7bfa0-b4f7-4e43-9e22-53f4ee420683

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2023-07-28 08:01
I'm unable to reproduce this. I tried 4 times and in all times the screen was correctly positioned at the right place so I'm going to close this for now.

**Closed by flaviadefaria** 2023-07-28 08:01 UTC
Labels: Daily, Overdue, Bug
