### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] Web - Thread - Console error ERR_FAILED 404 shows up when opening thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38174] opened 2024-03-12 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to any chat.
3. Send a message.
4. Right click on the message > Reply in thread.

## Expected Result:
No console error will show up.

## Actual Result:
Console error ERR_FAILED 404 shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ba188fd2-e232-4a3b-92d4-828256000e08

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bff0ded70edc9c84</li>
        <li>Upwork Job ID: 1768311805142413312</li>
        <li>Last Price Increase: 2024-03-14</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2024-03-13 10:05
Reviewing today!

**Comment by luacmartins** [comment] 2024-03-13 14:01
Found the issue in the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228637f0c02ed52da1-YVR%22)+AND+timestamp:%5B2024-03-12T23:34:49.015Z+TO+2024-03-13T01:34:49.015Z%5D&index=logs_expensify-027268). It seems like we're trying to subscribe to the report channel before the report is created, so there's a race condition somewhere.

**Comment by bernhardoj** [comment] 2024-03-14 16:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have authenticate pusher console error when opening a thread.

### What is the root cause of that problem?
We try to subscribe to the pusher before the report is created. We currently have 2 subscriptions, one in the report screen and one in the report actions view.
https://github.com/Expensify/App/blob/00315b1b3f8ee7a3adb86464f449d1c097a60f21/src/pages/home/ReportScreen.tsx#L437-L441
https://github.com/Expensify/App/blob/00315b1b3f8ee7a3adb86464f449d1c097a60f21/src/pages/home/report/ReportActionsView.tsx#L146-L150

The problem is in the report screen. When we open a new thread, it's possible that the report onyx data is not available yet, so the `didCreateReportSuccessfully` condition will return true because the pending fields are empty.

### What changes do you think we should make in order to solve the problem?

We can add a new check to make sure the report object has a report ID.
```
const didCreateReportSuccessfully = report.reportID && (!report.pendingFields || (!report.pendingFields.addWorkspaceRoom && !report.pendingFields.createChat));
```

### What alternative solutions did you explore? (Optional)
Move the subscription to the report actions view too because it's only rendered when the report is already loaded.

**Comment by Pujan92** [comment] 2024-03-15 13:48
Thanks for the proposals. Both have covered the RCA correctly which seems to be Report onyx data might not be available post navigating to the thread. Regarding the solutions @tienifr I don't think we need to compare the route report id and onyx report id, because if it is still old report then `didSubscribeToReportLeavingEvents` ref value is enough to identify and avoid subscribing the events. Validating reportID of report onyx data is enough and seems correct to me. With that, we can go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/38174#issuecomment-1997900612).

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-03-15 14:35
Just FYI, I actually prefer my alternative solution, that is moving the subscription down to ReportActionsView, so we won't need to check the reportID anymore, including this one.
https://github.com/Expensify/App/blob/ea1bbc387bc56062f04f414085bc830b80736c53/src/pages/home/ReportScreen.tsx#L430-L432

**Comment by Pujan92** [comment] 2024-03-15 14:36
> @Pujan92 This will be true only if `didCreateReportSuccessfully` was also true for the old report, only then, the `didSubscribeToReportLeavingEvents.current` of the old report will be set to `true` [here](https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/pages/home/report/ReportActionsView.tsx#L149). Although rarely, if the old report was also an optimistic report, it will not subscribe to the user leaving event, and in this case `didSubscribeToReportLeavingEvents` (of the old report) won't save us from the bug as you suggested.

@tienifr Sorry but I am not following exactly here, is this something we can reproduce? I tried to create nested threads offline and switch to online but I am not seeing any AuthenticatePusher error.

**Comment by Pujan92** [comment] 2024-03-15 14:51
> Just FYI, I actually prefer my alternative solution, that is moving the subscription down to ReportActionsView, so we won't need to check the reportID anymore, including this one.

Yes, I checked but forgot to mention it in the earlier comment. The only concern is why `ReportLeavingEvents` logic added specifically in the `ReportScreen` when there was similar `ReportTypingEvents` logic already presented in `ReportActionsView`. I believe it's good to combine both part over there but we need to confirm/find the reason of the split if any.

**Comment by bernhardoj** [comment] 2024-03-15 15:12
> The only concern is why ReportLeavingEvents logic added specifically in the ReportScreen when there was similar ReportTypingEvents logic already presented in ReportActionsView

I'm not sure, but I guess it's because the leaving redirection logic is put in ReportScreen, so they put the subscription in report screen too and not aware that we are doing a typing subscription in ReportActionsView. (here is the [PR](https://github.com/Expensify/App/pull/24407) that implements it)

About the concern of having the old report in a new report screen, that is not valid anymore. Each report screen is a separate screen. The onyx data are not shared between the screens. The issue have specifically here is that the report object is not available yet, thus the `reportID` is `undefined`. 

_The existing logic to compare the `reportID` from Onyx with the `reportID` from params is from the ancient code where we used MainDrawerNavigator, where there could only be one report screen._

**Comment by Pujan92** [comment] 2024-03-15 18:57
Thanks @bernhardoj for the explanation, club both events to one place makes sense to me.

**Comment by Pujan92** [comment] 2024-03-18 17:23
> There're certain scenarios where the `ReportActionsView` won't be rendered, see [here](https://github.com/Expensify/App/blob/37cde71374e005777c5fa43201ed4d04b8a713d0/src/pages/home/ReportScreen.tsx#L520). If the user was removed from the room while the `ReportActionsView` was not rendered, the leaving redirection logic won't work.

Thanks for flagging this @tienifr , I believe one use case where it fails is when user is leaving the room from the first device and on the second device the `ReportActionsView` is in a loading state then it might be possible that it won't navigate to Concierge. Because of the condition `!prevUserLeavingStatus && !!userLeavingStatus` won't be true which I think added for this multi device purpose only. This case might be rare but still I think it is a valid point. Thoughts @bernhardoj ?

@luacmartins Instead of breaking some other things I think it is better to validate only reportID here as a safer side.

**Comment by luacmartins** [comment] 2024-03-18 18:03
I agree that we should minimize these changes to avoid other regressions

**Comment by bernhardoj** [comment] 2024-03-19 03:36
> This case might be rare but still I think it is a valid point. 
> Instead of breaking some other things I think it is better to validate only reportID here as a safer side.

Oh yes, that's technically possible. I agree to just validate the reportID.

**Comment by Pujan92** [comment] 2024-03-19 14:14
@luacmartins Can you plz check the review [comment](https://github.com/Expensify/App/issues/38174#issuecomment-1999706809) and other followed comments to decide whom to assign? Also, both contributors have provided valuable inputs so we may consider the bounty split if you think the same.

**Comment by luacmartins** [comment] 2024-03-19 19:38
I agree that both contributors added value to this issue, so we can split the bounty. As for the proposal, I like @tienifr's solution more since it's stricter.

**Comment by dylanexpensify** [comment] 2024-03-20 11:43
nice!

**Comment by dylanexpensify** [comment] 2024-03-27 08:16
Merged, waiting for regression period then paying out!

**Comment by Pujan92** [comment] 2024-04-23 18:56
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24407
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24407/files#r1576748976
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
 - [X] [@Pujan92] Determine if we should create a regression test for this bug. Yes
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 
### Regression Test Steps

1. Open report
2. On any message(which isn't replied before) open context menu and select reply in thread
3. Verify thread report opens and isn't showing a AuthenticatePusher 404 error in the console

Do you agree 👍 or 👎 ?

**Comment by Pujan92** [comment] 2024-04-23 18:57
@dylanexpensify seems automation is broken for this issue.

**Comment by luacmartins** [comment] 2024-04-23 19:02
Updated the issue. Bump @dylanexpensify for payment

**Comment by dylanexpensify** [comment] 2024-04-29 10:25
Paid out!

**Comment by dylanexpensify** [comment] 2024-04-29 10:26
done!

**Closed by dylanexpensify** 2024-04-29 10:26 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
