### ISSUE TITLE
[$1000] Incorrect or misleading label text To instead of From while requesting money from user.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19204] opened 2023-05-18 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Click request money
3. Enter amount and click Next
4. Check the header in preview popup
5. See label text

## Expected Result: 
For request money action, it should show header title as "From"
## Actual Result:  
It shows header title as To instead of From while the action is for request money and not send money

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/43996225/b4771095-0db8-4917-9818-23f8e36514f3)

<img width="957" alt="1" src="https://github.com/Expensify/App/assets/43996225/135dce5f-235f-42d2-aa4c-7c95f09deddd">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @payal-lathidadiya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684245606906959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196d4da32658e1ab3</li>
        <li>Upwork Job ID: 1660571045282013184</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-18 18:36
## Proposal from payal-lathidadiya

### Please re-state the problem that we are trying to solve in this issue.
Incorrect or misleading label text `To` instead of `From` while requesting money from user.

### What is the root cause of that problem?
Currently, we use `common.to` text in section title within `MoneyRequestConfirmationList` component [here](https://github.com/Expensify/App/blob/main/src/components/MoneyRequestConfirmationList.js#L193) irrespective whether the request is for send money or request money.

### What changes do you think we should make in order to solve the problem?
We should conditionally show different text for section title based on type.
Add new label `from` in translation list (probably under common section) and use it as title for when action type is `Request money` option. 

### What alternative solutions did you explore? (Optional)
None

**Comment by Nikhil-Vats** [comment] 2023-05-18 21:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When requesting money from a user, in the final step, the label is 'To' instead of 'From' which is misleading.

### What is the root cause of that problem?
In `MoneyRequestConfirmationList`, both Send money and Request money use the same label (`common.to`) while showing participants sections of the request. There is no label added for 'From' in the the library right now.

The label -
https://github.com/Expensify/App/blob/f013fe2d26930bffb90e23620f8360743a0d2ea8/src/languages/en.js#L6-L13

Irrespective of whether the request type is `request` or `send`, the label shown is 'To'. The code below is executed when the prop `hasMultipleParticipants` is false.
https://github.com/Expensify/App/blob/f013fe2d26930bffb90e23620f8360743a0d2ea8/src/components/MoneyRequestConfirmationList.js#L191-L197

### What changes do you think we should make in order to solve the problem?
We should add a label for 'From' in `common` in all translation files.

Then in `MoneyRequestConfirmationList`, we can replace the code block mentioned above with the following code -
```javascript
const title = this.props.iouType === CONST.IOU.MONEY_REQUEST_TYPE.REQUEST ? this.props.translate('common.from') : this.props.translate('common.to');
const formattedParticipants = this.getParticipantsWithoutAmount(this.props.participants);
sections.push({
    title,
    data: formattedParticipants,
    shouldShow: true,
    indexOffset: 0,
});
```


We can also move the logic to get the title in a new method of the class.

**Comment by arielgreen** [comment] 2023-05-23 00:48
Waiting on proposals

**Comment by arielgreen** [comment] 2023-05-25 02:30
Awaiting proposals

**Comment by arielgreen** [comment] 2023-05-26 02:02
Reassigning, OOO tomorrow and Monday.

**Comment by kevinksullivan** [comment] 2023-05-26 18:15
taking to slack

https://expensify.slack.com/archives/C049HHMV9SM/p1685124899403269?thread_ts=1684245606.906959&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-05-26 18:29
Discussed in slack and this is not a bug

**Closed by kevinksullivan** 2023-05-26 18:29 UTC
Labels: External, Daily, Help Wanted, Bug
