### ISSUE TITLE
[PAID] [$500] Status - Custom time page loads infinitely in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33369] opened 2023-12-20 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in and do not visit custom time page
2. Go offline
3. Go to Settings > Profile > Status
4. Click Clear after
5. Click Custom
6. Click Time

## Expected Result:
Time selection page will open without issue

## Actual Result:
Time selection page loads infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cb93064d-23c2-4378-ab6c-37348ab0caab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab5fa243901ed9cb</li>
        <li>Upwork Job ID: 1737525375053193216</li>
        <li>Last Price Increase: 2023-12-20</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28067092</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-20 17:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In offline, the status timer is always loading.

### What is the root cause of that problem?
We are checking for the `privatePersonalDetails` to be loaded before showing the TimePicker and displaying the loader otherwise:

https://github.com/Expensify/App/blob/88631a09aedff62de0b45962d6d19837467b32a6/src/pages/settings/Profile/CustomStatus/SetTimePage.js#L36-L38
### What changes do you think we should make in order to solve the problem?

I've checked the code – the value of `privatePersonalDetails` is not used anywhere, seems like it is a redundant code that was added during development. We can remove this piece of code:

https://github.com/Expensify/App/blob/88631a09aedff62de0b45962d6d19837467b32a6/src/pages/settings/Profile/CustomStatus/SetTimePage.js#L36-L38

### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment] 2023-12-21 10:07
Proposal from @paultsimura looks good to me https://github.com/Expensify/App/issues/33369#issuecomment-1864877043
Seems we do not need that check, in case we do not use privatePersonalDetails anywhere in that flow
🎀 👀 🎀 C+ reviewed

**Comment by paultsimura** [comment] 2023-12-21 11:11
> we also need to get `clearAfter` from `currenPersonalDetail` if `customStatus` draft is empty

This looks more like re-inventing the wheel.
Here is the structure of the `PrivatePersonalDetails`, it stores exactly what it's meant to store – personal details – and has nothing to do with the status:

https://github.com/Expensify/App/blob/0a1bae4717ce9e1bc8176463d2ab793d8d77fad5/src/types/onyx/PrivatePersonalDetails.ts#L9-L19

The status has a dedicated Onyx key: 

https://github.com/Expensify/App/blob/278183e42390a8d550a2324ba2b6026f1337a7eb/src/types/onyx/CustomStatusDraft.ts#L1-L10

And if using this key causes trouble with deep links or whatever else, it should be handled properly in a separate task. But we clearly shouldn't mix personal details and status.

**Comment by paultsimura** [comment] 2023-12-21 11:40
The reason why `CUSTOM_STATUS_DRAFT` key was added is to allow setting the value of things like emoji, text, and clearAfter without holding to the previous value.
The corresponding values of `currentPersonalDetail` are correctly handled on pages that implement saving the draft status as a real status, and the draft value always takes priority:

https://github.com/Expensify/App/blob/08a967796d50023c354075a91d040f2a7a60df4c/src/pages/settings/Profile/CustomStatus/StatusPage.js#L49-L57

I don't see any benefit from using the `privatePersonalDetails` on this page, which will unnecessarily break the offline-first approach for the user.
Moreover, we don't use this key in [SetDatePage](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/CustomStatus/SetDatePage.js) either, which is equally related to the status.
That being said, I am still confident that my proposal fixes this issue correctly without any harm to the User.

**Comment by blimpich** [comment] 2023-12-21 18:39
I agree with @narefyev91. Thank you @paultsimura and @dukenv0307 for your proposal's and discussion, it has helped me understand this part of the codebase better. I think @paultsimura's proposal seems best for this particular situation. Assigning. Looking forward to the PR!

**Comment by paultsimura** [comment] 2023-12-21 19:58
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/33440

**Comment by strepanier03** [comment] 2024-01-03 21:51
Payment has been handled and part of the checklist. I'll check here tomorrow for the rest of the checklist responses and close when that's finished up.

**Comment by strepanier03** [comment] 2024-01-08 21:03
@paultsimura @narefyev91 - Do we need to do the regresssion test at all? I think not because an indefinite load would be caught with normal testing. 

I plan to close this tomorrow if I don't hear from you.

**Comment by paultsimura** [comment] 2024-01-08 21:07
From my POV, no regression test is needed here as the issue was caused by redundant code missed during the initial feature development

**Comment by strepanier03** [comment] 2024-01-09 21:27
Thank you @paultsimura - I'm going to close this and if a reg test is needed we can reopen and I'll take care of it.

**Closed by strepanier03** 2024-01-09 21:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
