### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Login - Abracadabra/2FA page displays but user can't login/continue until page is reloaded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26190] opened 2023-08-29 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with new account / existing account / 2FA account
3. Copy 'Magic Link' from validation email
4. Open a new tab and navigate to the staging magic link
5. Verify the 'Abracadabra' / '2FA required' page is displayed
6. Navigate to the original tab
7. Verify the user is logged in with the new / existing account or page for 2FA input is displayed

## Expected Result:
User is logged in with the new / existing account or page for 2FA input is displayed without reloading the page

## Actual Result:
The user should reload the page to login or to enter 2FA

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e80bff24-ac0a-460d-a744-bf62bb4b7fbd

https://github.com/Expensify/App/assets/78819774/df4afd2a-01b4-4726-bf6c-47ce9a108caf

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @Natnael-Guchima in https://github.com/Expensify/App/issues/25979

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186f5d4f5c7886b4e</li>
        <li>Upwork Job ID: 1700167803057692672</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by Natnael-Guchima** [comment] 2023-08-29 12:55
Hey guys, I reported this issue earlier [here](https://github.com/Expensify/App/issues/25979). this behavior is also observable on the 'unlink secondary contact method flow'

**Comment by arosiclair** [comment] 2023-08-29 14:25
Only related PRs I see are these, but I don't think they've broken anything

- https://github.com/Expensify/App/pull/25706
- https://github.com/Expensify/App/pull/25710

@johnmlee101 @NikkiWines any ideas?

**Comment by luacmartins** [comment] 2023-08-29 20:16
@arosiclair what's the latest here?

**Comment by arosiclair** [comment] 2023-08-29 21:43
No repro on dev here. It looks like the validate page and sign in commands are all working correctly. It seems like the 2FA page on the original tab is just not re-rendering after the session is updated in Onyx.

**Comment by luacmartins** [comment] 2023-08-29 22:48
I can reproduce in dev too. It seems like [this subscriber](https://github.com/Expensify/App/blob/c38ab0e19aaca72dcc883744e0dc01dc12de0197/src/Expensify.js#L243) is never getting the new value, so we don't re-render the navigator to redirect the user to the auth screens. I'm not sure why though.

**Comment by luacmartins** [comment] 2023-08-29 22:56
This seems to be a regression from https://github.com/Expensify/App/pull/25565. Reverting that PR fixes the issue. I'm gonna demote this issue to NAB since it's small, we have an easy workaround (refresh the page), we got a good performance improvement from that PR and the fix will likely be in Onyx.

@hannojg can you take a look at this since you worked on the Onyx improvements.

**Comment by luacmartins** [comment] 2023-09-01 17:20
@hannojg are we addressing the regressions from thee Onyx migration to idb-keyval anywhere?

**Comment by arosiclair** [comment] 2023-09-05 14:29
This seems like a pretty critical bug. And the root cause is in [react-native-onyx](https://github.com/Expensify/react-native-onyx/pull/280). 

I would assign @hannojg but I can't seem to do that. Either way, anyone could fix this and it should get fixed.

**Comment by stephanieelliott** [comment] 2023-09-06 23:14
> I would assign @hannojg but I can't seem to do that. 

@arosiclair FYI, external folks only show in the assignment dropdown once they comment in the issue! 

@hannojg any chance you want to pick this up? Otherwise will apply `Help Wanted` label tomorrow morning

**Comment by b4s36t4** [comment] 2023-09-08 15:25
I think @hannojg is OoO this week.

**Comment by conorpendergrast** [comment] 2023-09-11 08:33
Looks like I got assigned to this too, unassigning!

**Comment by luacmartins** [comment] 2023-09-13 09:18
Still waiting on @hannojg's update

**Comment by luacmartins** [comment] 2023-09-15 09:40
Still waiting on an update from @hannojg

**Comment by luacmartins** [comment] 2023-09-18 08:48
Same as above

**Comment by stephanieelliott** [comment] 2023-09-19 17:58
Looks like they just returned from OOO --  @hannojg can you pick this issue up for us? 🙏

**Comment by stephanieelliott** [comment] 2023-09-22 00:35
Posted in #expensify-margelo to reach Hanno and see if he'll pick this up for us.

**Comment by luacmartins** [comment] 2023-09-25 07:19
Issue is still reproducible in staging. Bumped the Slack thread

**Comment by mvtglobally** [comment] 2023-09-28 03:24
Issue not reproducible during KI retests. (First week)

**Comment by Natnael-Guchima** [comment] 2023-09-28 05:35
This seems to be reproducible on the latest main

**Comment by arosiclair** [comment] 2023-09-28 06:39
@ospfranco is working on changes that should fix this

**Comment by ospfranco** [comment] 2023-09-28 06:59
https://github.com/Expensify/react-native-onyx/pull/369 this should have fixed it. Tested it on main yesterday.

**Comment by ospfranco** [comment] 2023-09-28 07:05
https://github.com/Expensify/App/assets/1634213/c6dd593f-e78b-4fe5-941d-c98f07ea6439

Just retested this on main, it's working.

**Comment by ospfranco** [comment] 2023-09-29 05:33
https://github.com/Expensify/App/pull/28299 has been merged, you can test directly on `main` or wait for a deployment to staging.

**Comment by arosiclair** [comment] 2023-10-02 07:41
@abdulrahuman5196 can you verify this bug is fixed on staging?

**Comment by Natnael-Guchima** [comment] 2023-10-02 07:57
@arosiclair Yes it is fixed.

https://github.com/Expensify/App/assets/57330233/6466551f-ebc6-46b7-bbc8-25554e301a62

**Comment by arosiclair** [comment] 2023-10-03 08:54
Thank you @Natnael-Guchima. I think this is good to wait for the regression period 👍

**Comment by mvtglobally** [comment] 2023-10-05 03:01
Issue not reproducible during KI retests. (Second week)

**Comment by abdulrahuman5196** [comment] 2023-10-09 17:58
>The PR that introduced the bug has been identified. Link to the PR:

This issue was caused as a side effect of the onyx performance improvement - https://github.com/Expensify/react-native-onyx/pull/280

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/25565#issuecomment-1753427800

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Its a straightforward login usecase and regression test should be already present for the same.

**Comment by stephanieelliott** [comment] 2023-10-11 05:00
Summarizing payment on this issue -- @Natnael-Guchima @abdulrahuman5196 I've extended an offer to you on Upwork, can you please accept when you get a chance? 

 - Issue reporter: @Natnael-Guchima $250, pay via Upwork 
 - Contributor: @ospfranco (no payment due)
 - Contributor+: @abdulrahuman5196 $500, pay via Upwork 
 
 Upwork job is [here](https://www.upwork.com/jobs/~013cfc6838b63cf735), no bonus is included on final payout

**Comment by Natnael-Guchima** [comment] 2023-10-11 05:41
Accepted the offer. Thanks @stephanieelliott

**Comment by mvtglobally** [comment] 2023-10-12 03:41
Issue not reproducible during KI retests. (Third week)

**Comment by luacmartins** [comment] 2023-10-13 18:44
Just pending payment

**Comment by abdulrahuman5196** [comment] 2023-10-16 16:48
@stephanieelliott Gentle ping on payment processing. Pending for more than a week.

**Comment by stephanieelliott** [comment] 2023-10-17 01:14
All paid!

**Closed by stephanieelliott** 2023-10-17 01:14 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
