### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] IOU - Opening IOU receipt leads to not here page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39404] opened 2024-04-02 12:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money.
3. Create a manual request with receipt from user that has no unsettled IOU.
4. In 1:1 DM, click on the IOU preview.
5. Click on the receipt.

## Expected Result:
Receipt opens without issue.

## Actual Result:
Opening IOU receipt leads to not here page

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/19df7681-5aef-4569-9c6f-38420f14966d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170155bec83d697ff</li>
        <li>Upwork Job ID: 1775191991451828224</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-02 12:40
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-04-02 13:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Opening the money request receipt shows not found page.

### What is the root cause of that problem?
The condition to show the not found page is checking whether the report `parentReportID` is not the same as the transaction `reportID`.
https://github.com/Expensify/App/blob/a1801c829b446efcbcb0f91512655939c0535409/src/pages/TransactionReceiptPage.tsx#L62

When this code is made, we can only open the receipt from the transaction thread, so report `parentReportID` will point to the IOU/expense report, which is the same as transaction `reportID`.

However, after the one transaction report view [PR](https://github.com/Expensify/App/pull/36934), we are showing the receipt and other money request fields in the IOU report, so the condition is always false because IOU report `parentReportID` points to the chat report.

### What changes do you think we should make in order to solve the problem?

We should check whether the report is a money request report or not. If it's a money request report, we just take the `reportID`, otherwise take the `parentReportID`.
```
const moneyRequestReportID = ReportUtils.isMoneyRequestReport(report) ? report?.reportID : report?.parentReportID;

shouldShowNotFoundPage={(moneyRequestReportID ?? '') !== transaction?.reportID}
```

**Comment by bernhardoj** [comment] 2024-04-02 15:34
I don't see the problem with track expense

**Comment by bernhardoj** [comment] 2024-04-02 15:46
https://github.com/Expensify/App/assets/50919443/86cde24b-bf2e-494d-b81a-3b45952c5ef1


Works fine.

**Comment by bernhardoj** [comment] 2024-04-02 16:18
PR is ready

**Comment by NikkiWines** [comment] 2024-04-03 02:15
confirmed this works on staging as expected now 👍

**Comment by alexpensify** [comment] 2024-04-03 16:26
@dukenv0307 can we confirm if this blocker notice is valid or an error? Thanks!

**Comment by alexpensify** [comment] 2024-04-03 22:09
Perfect, thank you for the update!

**Comment by alexpensify** [comment] 2024-04-05 22:21
Update: We are waiting for this one to go into production

**Comment by alexpensify** [comment] 2024-04-12 19:49
@dukenv0307 and @bernhardoj - please submit a request here: 

https://www.upwork.com/jobs/~0170155bec83d697ff

On Monday, I can complete the payment process. Thanks!

**Comment by bernhardoj** [comment] 2024-04-13 05:06
Applied!

**Comment by alexpensify** [comment] 2024-04-15 21:35
@dukenv0307 and @bernhardoj - I've sent you offers via Upwork. Please accept and I can complete the payment process.

**Comment by bernhardoj** [comment] 2024-04-16 03:25
@alexpensify accepted

**Comment by alexpensify** [comment] 2024-04-16 19:46
Thanks, I was able to complete the payment to @bernhardoj. 

@dukenv0307, please accept the offer in Upwork, and I can complete the process. Thanks!

**Comment by alexpensify** [comment] 2024-04-17 17:48
Perfect, @dukenv0307 has been paid via Upwork. Closing since everyone has been paid via Upwork.

**Closed by alexpensify** 2024-04-17 17:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
