### ISSUE TITLE
[$1000] Settings - Welcome Message Inconsistency: Repetition

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21156] opened 2023-06-20 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Use a test account which already has any old room created in restricted mode with already written welcome message  (with Workspace already having Users )
2. Share the code from user A to user B and user C
3. Verify the welcome message

## Expected Result:
Welcome message would show once to the relevant User

## Actual Result:
Welcome message inconsistent. Some user see the same message upto 4 times with message ‘only visible to A’, ‘only visible to B’

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**1.3.29.7

**Reproducible in staging?:**y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4ff56567-168e-4774-ba33-0d1fcd906d91

https://github.com/Expensify/App/assets/93399543/48f93609-7a73-4790-9128-5fabc0e9c528

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686720741491599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01604db765ceb89953</li>
        <li>Upwork Job ID: 1672105233573134336</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-23 04:51
Definitely some weird stuff going on here with the welcome message!

**Comment by dragopicari** [comment] 2023-06-24 13:38
hello is this issue still active ? I'm currently testing but in my case i don't receive welcome messages, i'm using chrome browser and opera browser, 2 account with 2 different chrome browser, and 1 account with opera browser, even if set the welcome message on the room no one receives it when joining through the qr code link.

**Comment by dragopicari** [comment] 2023-06-24 13:42
Contributor details
Your Expensify account email: dragopicari98@icloud.com
Upwork Profile Link: https://www.upwork.com/freelancers/dragopicari

**Comment by nishancx** [comment] 2023-06-26 07:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome Message Inconsistency: Repetition

### What is the root cause of that problem?
In addition to welcome messages (whispers) being shown to relevant users, they are also being shown to the admin, this is the reason why multiple welcome messages are visible to the admin.

### What changes do you think we should make in order to solve the problem?
If the desired use case was to display all welcome messages to the admin then it seems good as it is, but if we donot want welcome messages for each new user to be shown to admin, we could approach in two ways:
- Not sending irrelevant welcome messages from backend. In this case, not sending welcome message for each new user as a report item to admin.
- Selectively filtering messages app side before displaying, so that each new user addition doesn't create a new message on admin's view.

First approach of not sending all the welcome messages seems more appropriate in my opinion, if doing this wouldn't create other unwanted effects.

### What alternative solutions did you explore?
Selectively filtering messages app side before displaying, so that each new user addition doesn't create a new message on admin's view.

**Comment by abdulrahuman5196** [comment] 2023-06-26 16:25
@nishancx  I am not able understand what is the issue and what should be done to solve it. The proposal is on high level of general statement which is already know.

For root cause and proposed changes. Kindly provide references on 
where the issue is present in the code? what causes the issue ? What should we do in, which piece of code should be changed to make it work.
Note: We don't expect full code to fix the issue. But we could always get permalink from app code and mention here.

**Comment by Incloodev** [comment] 2023-06-26 16:35
@abdulrahuman5196 which branch are you using ?

**Comment by nishancx** [comment] 2023-06-26 17:23
@abdulrahuman5196 
`Issue:` When a person creates a room with welcome message. Each newly added person is sent a copy of that welcome message as a whisper(to that one person only). The issue we are facing here is that the admin of the room is shown all the welcome messages sent to all the new members.
Eg. if someone(admin) creates a room, sets up welcome message then adds 5 people in the room, then those 5 people will receive a single welcome message, and the admin too sees all those 5 welcome messages.

If this isn't the expected behavior then, fixing response from back end so that those 5 welcome messages aren't sent as report items to the admin seemed like the better way to fix this issue, hence I couldn't propose any app side changes. But, if we want to approach this from app side then Ill get back with appropriate app side changes to filter out those message for admin's view.

**Comment by sakluger** [comment] 2023-06-27 00:49
@nishancx thanks for summarizing. When a new member joins a workspace, they should be the only person to see the welcome message (as a whisper message). The admin should not see the welcome message again when other people join the workspace.

**Comment by nishancx** [comment] 2023-06-27 03:02
@sakluger @abdulrahuman5196 Admin is receiving all the welcome messages (even those whispered to other members) from API when they fetch room messages and rather than fixing this on app, I feel like a better way to approach this would be to not send those whispers messages from API to admin in the first place.

**Comment by nishancx** [comment] 2023-06-28 17:29
@sakluger @abdulrahuman5196 I have update my [proposal](https://github.com/Expensify/App/issues/21156#issuecomment-1606867660) above to handle this issue app side.

**Comment by abdulrahuman5196** [comment] 2023-06-28 17:53
Thank you. Will provide updates within a day.

**Comment by sakluger** [comment] 2023-07-01 00:52
@abdulrahuman5196 have you had a chance to review the updated proposal yet?

**Comment by abdulrahuman5196** [comment] 2023-07-03 17:45
Thank you for the proposal @nishancx . But I don't think frontend fix is valid for this. There is no point in sending messages to the user which is not going to be shown ultimately.

@sakluger This issue should be fixed in backend ideally. Could you kindly check/assign an engineer to confirm this?

**Comment by shubham1206agra** [comment] 2023-07-04 14:22
> Thank you for the proposal @nishancx . But I don't think frontend fix is valid for this. There is no point in sending messages to the user which is not going to be shown ultimately.
> 
> @sakluger This issue should be fixed in backend ideally. Could you kindly check/assign an engineer to confirm this?

Hello

I want to ask one question
Do we have custom seperate welcome message for every user? Or is it the same message?

**Comment by sakluger** [comment] 2023-07-05 18:01
Hey @cristipaval, @abdulrahuman5196 thinks that this should be fixed on the backend, and I agree - we shouldn't send additional welcome messages to the Admin then hide them, instead, we should just not send multiple copies of the welcome message to the admin in the first place. What are your thoughts?

**Comment by sakluger** [comment] 2023-07-05 18:03
> Do we have custom seperate welcome message for every user? Or is it the same message?

@shubham1206agra a welcome message can be set for each room, but every person who joins that room will see the same welcome message - it's not possible to customize per-user.

**Comment by cristipaval** [comment] 2023-07-05 18:27
> Hey @cristipaval, @abdulrahuman5196 thinks that this should be fixed on the backend, and I agree - we shouldn't send additional welcome messages to the Admin then hide them, instead, we should just not send multiple copies of the welcome message to the admin in the first place. What are your thoughts?

yes, this totally has to be fixed in the backend.

**Comment by cristipaval** [comment] 2023-07-05 18:27
I'll create a fix PR soon.

**Comment by sakluger** [comment] 2023-07-07 21:45
Thanks @cristipaval - I've changed the issue to internal. Leaving daily for now.

**Comment by sakluger** [comment] 2023-07-10 20:46
@cristipaval I think this new GH issue is related (https://github.com/Expensify/App/issues/22255). Whatever fix you create here, can you make sure that if a new Workspace member creates a thread for the welcome message, that it doesn't show up for the admin in the LHN?

**Comment by pecanoro** [comment] 2023-07-11 15:14
Guys, this is by design, we can't remove these or 1:1 whispers will stop working as expected.

**Comment by pecanoro** [comment] 2023-07-11 15:15
I am sorry for the discussion and time invested here, but this is not a bug!

**Comment by cristipaval** [comment] 2023-07-11 15:26
Alright, closing the issue then.

**Closed by cristipaval** 2023-07-11 15:26 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
