### ISSUE TITLE
[$1000] User without permission is able to change the assignee in the front-end

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21691] opened 2023-06-27 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On user A,
2, Go to '+" -> assign task -> enter task name
3. <IMPORTANT STEP> assign task to self (i.e User A) and share to User B.
4. Now it displays a created task page
5. On User B,
6. Manually search on LHN, and go to shared task
7. Now on task page , ( notice that user B can't mark the task as completed) ,  change the asignee to some third user or any.
Say we changed to User C .
8. Meanwhile, on User A, notice that changes aren't shown.
9. Now, complete the task
10. On user B, notice the assignee is now auto changed from user C to A.

## Expected Result:
 If the task is just shared to a second user, say user B here. User B should not have authority to change assignee.

## Actual Result:
Changing assignee from shared to user , breaks the flow.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f10cbc11-a25f-40b0-ab17-d8cc951136b6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687517717620369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1e244f4640b0813</li>
        <li>Upwork Job ID: 1675910040234905600</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by ashimsharma10** [comment] 2023-06-27 15:46
@StevenKKC Have you reproduced on DEV?

**Comment by StevenKKC** [comment] 2023-06-27 15:55
@ashimsharma10 Yes, I can reproduce on DEV.

**Comment by alexpensify** [comment] 2023-06-29 22:40
Reassigning another bug team member, I'm going OOO until Monday, July 10, and will take it back if it's still open by my return date.

Required action from the 🐛 team: I've run out of time and haven't tested this one yet. This needs testing to confirm if it's a bug, check if it's a dupe, and then assign the applicable labels. Thank you!

**Comment by anmurali** [comment] 2023-07-03 16:50
Yea, this is kind of a mess. The shared user can seemingly reassign the task and a thread is accordingly created with the user that this person reassigned the task to. But the task itself is still shown as assigned in the original thread to the same first user

**Comment by thienlnam** [comment] 2023-07-03 17:02
The video in the OP does not appear to represent what the title is

**Comment by thienlnam** [comment] 2023-07-03 17:05
This works as expected - like Steven mentioned, User B tried to re-assign the task but did not have permission so it failed and did not actually change the assignee. We're blocking the user from completing the task, but not blocking the user from changing the assignee in the front end. However, we should hold on these changes until we finish the task re-design [here](https://github.com/Expensify/App/pull/20841)

**Comment by sobitneupane** [comment] 2023-07-05 10:22
@anmurali Let's hold this issue for now as suggested by @thienlnam [here](https://github.com/Expensify/App/issues/21691#issuecomment-1618896811). Task header is being changed by [this PR](https://github.com/Expensify/App/pull/20841).

**Comment by thienlnam** [comment] 2023-07-05 19:41
We're also having an internal discussion regarding allowing anyone that can view the task to edit the task so this issue may actually also be moot after that https://expensify.slack.com/archives/C01SKUP7QR0/p1688195284781699

**Comment by thienlnam** [comment] 2023-07-05 19:43
Going to close this though, since we have a few different related issues for it already (User lacks permissions for an action) https://github.com/Expensify/App/issues/21579

**Closed by thienlnam** 2023-07-05 19:43 UTC
Labels: External, Daily, Help Wanted, Bug
