### ISSUE TITLE
 [$250] Group chat title is different in header than in details.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47803] opened 2024-08-21 15:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724245884496689

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a group chat with a handful of people. 
## Expected Result:
The header and details page should include all the members of group

## Actual Result:
The header and details page differ and do not include all members of the group.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-08-21 at 9 09 10 AM](https://github.com/user-attachments/assets/eafb1385-b161-4808-84b2-cfa10c85c1f1)
![Screenshot 2024-08-21 at 9 09 19 AM](https://github.com/user-attachments/assets/4e85fd28-f4a2-477f-9147-adbeef526327)
![Snip - New Expensify - Google Chrome](https://github.com/user-attachments/assets/e84e7bed-ad78-46ca-b1fa-3dd196ec0b02)

Onyx Data:

``` {
    "reportID": "1104448895618589",
    "reportName": "",
    "type": "chat",
    "chatType": "group",
    "ownerAccountID": 0,
    "policyID": "_FAKE_",
    "participants": {
        "778531": {
            "hidden": false,
            "notificationPreference": "always",
            "role": "member"
        },
        "3107470": {
            "hidden": false,
            "notificationPreference": "always",
            "role": "admin"
        },
        "3149650": {
            "hidden": false,
            "notificationPreference": "always",
            "role": "member"
        },
        "3772464": {
            "hidden": false,
            "notificationPreference": "always",
            "role": "member"
        },
        "3806748": {
            "hidden": false,
            "notificationPreference": "always",
            "role": "member"
        },
        "4121216": {
            "hidden": false,
            "notificationPreference": "always",
            "role": "member"
        },
        "7906268": {
            "hidden": false,
            "notificationPreference": "always",
            "role": "member"
        }
    },
    "participantAccountIDs": [],
    "visibleChatMemberAccountIDs": [],
    "isPinned": false,
    "lastReadTime": "2024-08-21 13:13:34.449",
    "lastReadSequenceNumber": 0,
    "lastVisibleActionCreated": "2024-08-21 13:13:28.230",
    "lastVisibleActionLastModified": "2024-08-21 13:13:28.230",
    "lastMessageText": "Welcome back neighbor!!",
    "lastActionType": "ADDCOMMENT",
    "lastActorAccountID": "3806748",
    "notificationPreference": "always",
    "stateNum": 0,
    "statusNum": 0,
    "oldPolicyName": "",
    "private_isArchived": "",
    "isOwnPolicyExpenseChat": false,
    "lastMessageHtml": "Welcome back neighbor!!",
    "hasOutstandingChildRequest": false,
    "hasOutstandingChildTask": false,
    "writeCapability": "all",
    "description": "",
    "total": 0,
    "unheldTotal": 0,
    "currency": "USD",
    "isWaitingOnBankAccount": false,
    "nonReimbursableTotal": 0,
    "isCancelledIOU": false,
    "errorFields": {},
    "permissions": [
        "read",
        "write",
        "share"
    ],
    "welcomeMessage": "",
    "isLoadingPrivateNotes": false,
    "privateNotes": {
        "778531": {
            "note": ""
        }
    },
    "lastMessageTranslationKey": "",
    "managerID": 0
} 
```

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185f6c487fb4d1046</li>
        <li>Upwork Job ID: 1826298251163774653</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by FitseTLT** [comment] 2024-08-21 16:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group chat title is different in header than in details.

### What is the root cause of that problem?
We get header title from getReportName 
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/pages/home/HeaderView.tsx#L81-L82
which calls getGroupChatName with `shouldApplyLimit` true
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/libs/ReportUtils.ts#L3729-L3730
but the details page call it with shouldApplyLimit false
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/pages/ReportDetailsPage.tsx#L248-L249
### What changes do you think we should make in order to solve the problem?

We need to be consistent in the way we get group chat name
If we want to get with limit applied we can use getReportName here
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/pages/ReportDetailsPage.tsx#L248-L249
```
    const reportName = ReportUtils.isDeprecatedGroupDM(report) ? ReportUtils.getGroupChatName(undefined, true, report) : ReportUtils.getReportName(report);

```
or if we want without limit applied we can explicitly set it to getGroupChatName with shouldApplyLimit set to false for isGroupChat case here
https://github.com/Expensify/App/blob/a32da40e1017d2136389f05735bace7bc307e098/src/pages/home/HeaderView.tsx#L81-L82

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-21 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The header and details page differ and do not include all members of the group.

### What is the root cause of that problem?
In the header, we get the group chat report name with `shouldApplyLimit` as `true`

https://github.com/Expensify/App/blob/9757ae2e92ec40e7d2083977a240df539f8b51f4/src/pages/home/HeaderView.tsx#L81

https://github.com/Expensify/App/blob/9757ae2e92ec40e7d2083977a240df539f8b51f4/src/libs/ReportUtils.ts#L3739

In the report detail page we get the group chat report name with `shouldApplyLimit` as `false`
https://github.com/Expensify/App/blob/9757ae2e92ec40e7d2083977a240df539f8b51f4/src/pages/ReportDetailsPage.tsx#L250

The problem here is we sort the list of participant names after we slice `participantAccountIDs` then if the prioritized alphabet participant is in the last of the participant list, the name will be displayed differently.
https://github.com/Expensify/App/blob/9757ae2e92ec40e7d2083977a240df539f8b51f4/src/libs/ReportUtils.ts#L2145
### What changes do you think we should make in order to solve the problem?
I think in the header we slice the group chat report name because it maybe too long and the width of report detail page is small. So in this case we should sort the participant name list before we slice the list

```
if (isMultipleParticipantReport) {
    let participantDisplayNames = participantAccountIDs
        .map(
            (participantAccountID, index) =>
                getDisplayNameForParticipant(participantAccountID, isMultipleParticipantReport) || LocalePhoneNumber.formatPhoneNumber(participants?.[index]?.login ?? ''),
        )
        .sort((first, second) => localeCompare(first ?? '', second ?? ''))
        .filter(Boolean);
    if (shouldApplyLimit) {
        participantDisplayNames = participantDisplayNames.slice(0, 5);
    }
    return participantDisplayNames.join(', ');
}
```
https://github.com/Expensify/App/blob/9757ae2e92ec40e7d2083977a240df539f8b51f4/src/libs/ReportUtils.ts#L2139-L2145

### What alternative solutions did you explore? (Optional)
If we want to display the same, we can remove the check `ReportUtils.isDeprecatedGroupDM(report) || isGroupChat` here since `getReportName` already covers the group chat case

https://github.com/Expensify/App/blob/9757ae2e92ec40e7d2083977a240df539f8b51f4/src/pages/ReportDetailsPage.tsx#L250

**Comment by bernhardoj** [comment] 2024-08-21 17:36
We already have an issue [here](https://github.com/Expensify/App/issues/47564) to make the group name consistent.

**Comment by ChavdaSachin** [comment] 2024-08-22 15:51
> We already have an issue [here](https://github.com/Expensify/App/issues/47564) to make the group name consistent.

That issue looks different since it's for thread header

**Comment by nkdengineer** [comment] 2024-08-27 04:04
@puneetlath Can you confirm the expected about the group chat title

If the group has a list of participant names like `[E, F, G, H, J, A, B, C, D]`. When we display the group chat name with only 5 member what is the group chat name should be displayed

1. `E, F, G, H, J`
2. `A, B, C, D ,E`

**Comment by puneetlath** [comment] 2024-08-27 20:53
I'm not sure honestly and I don't really have a preference as long as we're consistent. What does getGroupChatName currently do?

**Comment by nkdengineer** [comment] 2024-08-28 05:35
@puneetlath `getGroupChatName` has a param `shouldApplyLimit`. If it's true, we will get 5 first participants from `participantAccountIDs` then get display name and re-order the list.

**Comment by nkdengineer** [comment] 2024-08-28 05:36
> If the group has a list of participant names like [E, F, G, H, J, A, B, C, D]. When we display the group chat name with only 5 member what is the group chat name should be displayed

With this example, it's returning option 1 now.

**Comment by puneetlath** [comment] 2024-08-28 14:12
Ok I say we just do that in all the scenarios then.

**Comment by stephanieelliott** [comment] 2024-08-30 01:39
Hey @eVoloshchak there are a few proposals here, can you review please?

**Comment by stephanieelliott** [comment] 2024-09-04 02:30
Bump on this @eVoloshchak 

> Hey @eVoloshchak there are a few proposals here, can you review please?

**Comment by ahmedGaber93** [comment] 2024-09-04 02:33
I think we need to put this on hold https://github.com/Expensify/App/pull/48046

**Comment by stephanieelliott** [comment] 2024-09-07 02:18
Thanks @ahmedGaber93, let's hold for https://github.com/Expensify/App/pull/48046

**Comment by stephanieelliott** [comment] 2024-09-11 02:48
PR https://github.com/Expensify/App/pull/48046 was merged to main, should be on staging soon

**Comment by stephanieelliott** [comment] 2024-09-24 22:59
I think this is fixed with https://github.com/Expensify/App/pull/48046 🎉 I can't repro this -- anyone able to reproduce? 

<img width="790" alt="image" src="https://github.com/user-attachments/assets/d7133453-96ee-4747-b762-cdde7ed1fb9f">

**Comment by stephanieelliott** [comment] 2024-09-25 19:27
I am going to close since I am still unable to repro, if you are able to repro this feel free to reopen it!

**Closed by stephanieelliott** 2024-09-25 19:27 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
