### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Pay someone - Add receipt placeholder is shown when receipt is not allowed when paying someone

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41489] opened 2024-05-02 10:30 UTC
<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by izarutskaya** [comment] 2024-05-02 10:32
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-02 10:32
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-02 10:32
Production 


https://github.com/Expensify/App/assets/115492554/6ec75617-9f45-454c-af84-881a3b6b4a31

**Comment by Nodebrute** [comment] 2024-05-02 11:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Add receipt placeholder is shown when receipt is not allowed when paying someone
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/components/ReportActionItem/MoneyRequestView.tsx#L331
### What changes do you think we should make in order to solve the problem?

We can get the type from parentReportAction which is pay in this case and use it here
[canEditFieldOfMoneyRequest](https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/components/ReportActionItem/MoneyRequestView.tsx#L331)

We can also create a utility function for future cases.
Pseudocode

```
 const isPay = parentReportAction?.originalMessage?.type
 const shouldShowReceiptEmptyState = !isPay && !hasReceipt && !isInvoice && (canEditReceipt || isAdmin || isApprover);

```
### What alternative solutions did you explore? (Optional)

**Comment by Nodebrute** [comment] 2024-05-02 11:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Add receipt placeholder is shown when receipt is not allowed when paying someone
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/components/ReportActionItem/MoneyRequestView.tsx#L331
### What changes do you think we should make in order to solve the problem?

We can get the type from parentReportAction which is pay in this case and use it here
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/components/ReportActionItem/MoneyRequestView.tsx#L331

We can also create a utility function for future cases.
Pseudocode

```
 const isPay = parentReportAction?.originalMessage?.type === 'pay'
 const shouldShowReceiptEmptyState = !isPay && !hasReceipt && !isInvoice && (canEditReceipt || isAdmin || isApprover);

```

We should also add this check here
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/components/ReportActionItem/MoneyRequestView.tsx#L339-L344

We can hide the above part (total + separator) to make the view similar to invoices 
### What alternative solutions did you explore? (Optional)

**Comment by MariaHCD** [comment] 2024-05-02 11:36
This is related to the shouldShowEmptyReceiptState logic implemented in https://github.com/Expensify/App/pull/37813

I think it makes sense to not show the receipt empty state if the IOU is already paid. cc: @cead22 @JmillsExpensify for confirmation on what the expected UI/UX should be here.

**Comment by MariaHCD** [comment] 2024-05-02 11:37
I also don't think this should necessarily block the deploy.

**Comment by cead22** [comment] 2024-05-02 17:02
If the receipt can't be added, then I agree we shouldn't show the empty state (cc @Krishna2323 @sobitneupane)

**Comment by cead22** [comment] 2024-05-02 17:11
Thanks

**Comment by trjExpensify** [comment] 2024-05-28 18:27
PR is in review, and close!

**Comment by MariaHCD** [comment] 2024-05-31 06:25
The PR has been approved and merged

**Comment by trjExpensify** [comment] 2024-05-31 10:53
Chill Melv, awaiting a deploy.

**Comment by trjExpensify** [comment] 2024-06-18 21:13
Apols, I've been OoO. Payment summary as follows:

- $250 to @sobitneupane for the C+ review
- $250 to @Krishna2323 for the fix 

@sobitneupane go ahead and request, @Krishna2323 I've sent you an offer.

**Comment by trjExpensify** [comment] 2024-06-18 21:16
Paid!

**Comment by sobitneupane** [comment] 2024-06-20 09:36
**Regression Test Proposal:**

1. Go to FAB > Pay someone > Enter amount > Select user > Submit
2. Open the paid IOU request > Verify Add receipt placeholder is not shown
3. Open any paid or approved IOU report in paid policy that doesn't have any receipt
4. Verify Add receipt placeholder is not shown

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-06-22 16:40
$250 approved for @sobitneupane. Reopeninf for the decision on the regression test.

**Comment by trjExpensify** [comment] 2024-06-24 10:02
Regression test created, closing again.

**Closed by trjExpensify** 2024-06-24 10:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
