### ISSUE TITLE
[PAID] [$250] [Search v1] - Sometimes blank space appears instead of skeleton loader when scrolling

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43396] opened 2024-06-10 16:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #43206
**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** no , new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Log in with an account that has a lot of expenses
3. Open Search
4. Scroll down multiple times

## Expected Result:
Skeleton loader should always show when it's loading data.

## Actual Result:
Sometimes blank space appears instead of skeleton loader when scrolling

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/71818193-f701-4151-ba03-031a42a37337

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb69abaa0bdb0869</li>
        <li>Upwork Job ID: 1800230851436781734</li>
        <li>Last Price Increase: 2024-06-10</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 102732933</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by m-natarajan** [comment] 2024-06-10 16:14
@aldo-expensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-06-10 18:17
hmm I think this might be a performance issue, where mobile clients struggle to keep up with a huge list of items. I'm gonna demote this to NAB since it doesn't break the feature.

**Comment by aldo-expensify** [comment] 2024-06-10 18:20
@m-natarajan do you know which account (email) was used to reproduce this?

**Comment by aldo-expensify** [comment] 2024-06-10 19:49
> hmm I think this might be a performance issue, where mobile clients struggle to keep up with a huge list of items. I'm gonna demote this to NAB since it doesn't break the feature.

Yeah, I believe the same

**Comment by TheGithubDev** [comment] 2024-06-10 20:46
### Proposal

### **Please re-state the problem that we are trying to solve in this issue:**
The problem is that sometimes a blank space appears instead of a skeleton loader when scrolling through expenses in the Search tab.

### **What is the root cause of that problem?**
The root cause of this problem is likely an issue with the rendering logic for the skeleton loader. When new data is being loaded, the condition to display the skeleton loader may not be consistently triggered, resulting in blank spaces. This can occur due to asynchronous data fetching or improper state updates that fail to notify the component to render the loader.

### **What changes do you think we should make in order to solve the problem?**
To solve this problem, we should ensure that the skeleton loader is always displayed during data loading by making the following changes:

1. ### **Ensure Proper State Management**: Make sure the state that controls the visibility of the skeleton loader is properly managed and updated. This involves checking the loading state before new data is fetched and ensuring the component re-renders correctly.

2. ### **Consistent Trigger for Skeleton Loader:**
   - Verify the conditions that trigger the skeleton loader's visibility. Ensure that the loader is shown as soon as a data fetch starts and remains visible until the data is fully loaded.
   - Implement or review the logic in the component's `render` method to ensure it checks the loading state properly.

### **_Example of how the changes might look:_**

```javascript
// State management in the component
const [isLoading, setIsLoading] = useState(false);
const [expenses, setExpenses] = useState([]);

// Fetching data function
const fetchData = async () => {
    setIsLoading(true);
    try {
        const data = await fetchExpenses();
        setExpenses(prevExpenses => [...prevExpenses, ...data]);
    } catch (error) {
        console.error('Error fetching expenses:', error);
    } finally {
        setIsLoading(false);
    }
};

// Render method or component JSX
return (
    <ScrollView onScroll={handleScroll}>
        {expenses.map(expense => (
            <ExpenseItem key={expense.id} data={expense} />
        ))}
        {isLoading && <SkeletonLoader />}
    </ScrollView>
);

// Handling scroll event to load more data
const handleScroll = (event) => {
    if (isNearBottom(event)) {
        fetchData();
    }
};
```

### **3. Ensure Correct Component Lifecycle Management:** 

Make sure the skeleton loader component is properly mounted and unmounted, and that the state updates are correctly propagated to trigger re-renders when data is loading.

### **What alternative solutions did you explore?**
1. **Debouncing Scroll Events**: Implementing a debounce mechanism for scroll events to ensure that the data fetching function is not called too frequently, which can help in maintaining a consistent loading state and preventing blank spaces.

2. **Using a Loading Indicator Library:** Utilizing a third-party library for handling loading indicators that offers more robust and tested components for displaying loaders. This can ensure a more consistent and reliable user experience.

4. **Lazy Loading with Placeholders:** Implementing a lazy loading mechanism with image or data placeholders that ensures a fallback visual element is displayed if the skeleton loader fails to render.

Each alternative was considered, but ensuring proper state management and consistent triggering of the skeleton loader within the existing framework was deemed the most effective and straightforward solution to address the issue without introducing additional dependencies or significant refactoring.

_(Rayyan here from Upwork)_

**Comment by m-natarajan** [comment] 2024-06-11 13:27
> @m-natarajan do you know which account (email) was used to reproduce this?

komaromalberlet@gmail.com and applausetester+mn03admin@applause.expensifail.com

**Comment by ahmedGaber93** [comment] 2024-06-12 16:27
@TheGithubDev Your proposal didn't have a clear root cause and solution, you should link where the root cause in our code, and the solution should contain the code changes and where we will add it.

**Comment by TheGithubDev** [comment] 2024-06-12 16:55
I will review the problem thoroughly again and share the precise locations in the code and the necessary changes, shortly. Thanks for your feedback!

**Comment by ahmedGaber93** [comment] 2024-06-13 11:52
Waiting on proposals

**Comment by TheGithubDev** [comment] 2024-06-13 15:59
### **Proposal**

### **Re-state the problem that we are trying to solve in this issue:**
Sometimes a blank space appears instead of the skeleton loader when scrolling on the Search page in the New Expensify app. This occurs after logging in with an account that has a large number of expenses and repeatedly scrolling down.

### **Root cause of that problem?**
Asynchronous nature of data fetching and how the loading state is managed within the component. Specifically, there is a race condition or a state update issue in the code responsible for displaying the skeleton loader. When the component's state isn't updated correctly or in a timely manner, it results in a blank space instead of the skeleton loader.

The issue likely resides in the file handling the Search page rendering, such as `SearchPage.js`, where the state for loading and the logic for displaying the skeleton loader are implemented.

### **What changes do you think we should make in order to solve the problem?**
To resolve this issue, we should ensure the state management and rendering logic are correctly implemented to always show the skeleton loader when data is being fetched. This can be done by- 

### **1. Identify and Update the Loading State Logic:**
- Ensure the loading state is properly set before and after data fetching.
- Make sure the skeleton loader is conditionally rendered based on the loading state.

2. **Modify the Component to Correctly Render the Skeleton Loader:**
- Update the component rendering logic to prevent any blank space.

### **Here is a code example showing where to make changes:**

**1. Locate the `SearchPage.js` or the relevant file:**

```javascript
// src/pages/SearchPage.js

import React, { useState, useEffect } from 'react';
import SkeletonLoader from '../components/SkeletonLoader'; // Assuming there's a SkeletonLoader component
import ExpenseItem from '../components/ExpenseItem'; // Assuming there's an ExpenseItem component

const SearchPage = () => {
    const [expenses, setExpenses] = useState([]);
    const [isLoading, setIsLoading] = useState(false);
    const [hasMore, setHasMore] = useState(true);

    useEffect(() => {
        loadExpenses();
    }, []);

    const loadExpenses = async () => {
        if (!hasMore) return;
        setIsLoading(true);
        
        try {
            const newExpenses = await fetchMoreExpenses(); // Function to fetch more expenses
            setExpenses(prevExpenses => [...prevExpenses, ...newExpenses]);
            if (newExpenses.length === 0) setHasMore(false);
        } catch (error) {
            console.error("Failed to load expenses:", error);
        } finally {
            setIsLoading(false);
        }
    };

    const handleScroll = (e) => {
        const bottomReached = e.target.scrollHeight - e.target.scrollTop === e.target.clientHeight;
        if (bottomReached && !isLoading) {
            loadExpenses();
        }
    };

    return (
        <div onScroll={handleScroll}>
            {expenses.map(expense => (
                <ExpenseItem key={expense.id} {...expense} />
            ))}
            {isLoading && <SkeletonLoader />}
            {!isLoading && hasMore && <SkeletonLoader />}
            {!hasMore && <p>No more expenses to load</p>}
        </div>
    );
};

export default SearchPage;
```

**2. Ensure Proper State Updates:**
- The loading state (`isLoading`) should be set to `true` before fetching data and set to `false` after the data has been fetched.
- Always render the `SkeletonLoader` component when `isLoading` is `true` or when there are more expenses to load (`hasMore`).

**3. Handle Edge Cases:**
   - Add a fallback to render a message when there are no more expenses to load, ensuring no blank spaces appear.

**Comment by Kicu** [comment] 2024-06-14 09:00
@TheGithubDev both your proposal are extremely generic and do not reflect the specific code in Expensify App. They also do not account for usage of Onyx in this project. I have a hard time reviewing them.

@luacmartins I think we have someone from SWM who could tackle this.

**Comment by zfurtak** [comment] 2024-06-14 09:35
Hello, I work for SWM agency and I would like to work on this.

**Comment by mountiny** [comment] 2024-06-14 10:15
Thanks, yeah I think this would be a good task for @zfurtak to dig into, please post your findings here daily and proposal for how to fix it for @luacmartins and @ahmedGaber93 to weigh in before creating a PR

**Comment by TheGithubDev** [comment] 2024-06-14 10:30
@Kicu Thanks for your feedback. I will revise my proposals to be more specific to the Expensify App's codebase and incorporate the usage of Onyx where applicable. I'll ensure the next proposal is detailed and tailored to the project's requirements. Thanks for pointing this out!

**Comment by zfurtak** [comment] 2024-06-14 14:48
Today I tried different cases and configurations of props. So far I think that the cause of this problem is inside `SelectionList`.

**Comment by ahmedGaber93** [comment] 2024-06-18 06:12
Not overdue, issue assigned and we wait @zfurtak's investigation.

**Comment by zfurtak** [comment] 2024-06-18 12:48
Hi there, as suspected I believe that the problem is inside `SelectionList` which is implemented with react native's `SectionList`. It is most likely connected to performance as the issue occurs when there are lots of elements on the list and scrolling is rather fast.
I found similar case in `WorkspaceCategoryPage` which also uses `SelectionList` (video below)

[![video](https://github.com/Expensify/App/raw/main/assets/92310164/d7af9109-bf64-4d4d-b122-7029f42f07fb.jpg)](https://github.com/Expensify/App/raw/main/assets/92310164/d7af9109-bf64-4d4d-b122-7029f42f07fb)

**Comment by luacmartins** [comment] 2024-06-18 15:54
Nice! Yea, thanks for confirming the suspicion. @zfurtak what steps will you take next to try to solve this issue?

**Comment by zfurtak** [comment] 2024-06-20 12:35
hi @luacmartins :) 
I did some more research, and also discussed this issue with @Kicu and @j-piasecki. 🕵️‍♂️
Ultimately, what causes this bug is the fact that components are being rendered too long. The idea we came up with is to memoize components in the list (which should help the performance), but this solution can't be applied, because these elements should be updated live (e.g. when `width` or data changes).
I also looked at other applications with lists (e.g. zalando) and found the same problem (in both cases it only appears when scrolling very fast 🏎️).
Also in the release build of Expensify App this list experience is much smoother (as there are some optimisations).

What do you think we should do next? 🤔

**Comment by luacmartins** [comment] 2024-06-20 19:55
Hmm I think the OP was reported on the staging build using a real device. We already had the memo solution in place but had to remove it because of live updates. I wonder if we could still use it and use a hash of the data values as key 🤔 might be flaky and the overhead of computing the hash might offset the gains of memoizing the component. Maybe we could explore this solution?

This is also a known limitation for other lists in App, e.g. LHN which on android gets completely unusable when we have ~200 reports in the list. Can we somehow evict the items not shown on the list?

**Comment by zfurtak** [comment] 2024-06-21 09:49
Today I'm focusing on a different issue, but I will be back to this case on Monday. 😊

**Comment by Kicu** [comment] 2024-06-27 09:47
@luacmartins I'll be taking over this from @zfurtak (shes going on vay-kay) and I'll drop a bigger comment later, because I think the slowness of this list is also connected to the ongoing changes we do in Search view.

**Comment by luacmartins** [comment] 2024-06-27 14:52
Cool, I assigned you to it!

**Comment by ahmedGaber93** [comment] 2024-07-04 18:19
We are still discussing the possible solution

**Comment by Kicu** [comment] 2024-07-09 15:26
**Some loose thoughts from me**
@luacmartins 

We know from investigation by @zfurtak with some help from @j-piasecki that what happens is definitely because the render of 1 list item takes a long time. (https://github.com/Expensify/App/issues/43396#issuecomment-2180562529).

There is no easy way to try to use `React.memo` to help with this, because basically whenever any prop changes we need to re-render. This is quite a heavy view with a lot of data. Whenever props like `isSelected` changes, any part of data of item etc we re-render. So the implementation of comparator for `memo` would be basically "check every prop" - which gives us nothing.

IMO unfortunately part of the problem is how the component `SelectionList` was written. There is no simple way to pass any extra props or functions to the rendered components. Every piece of data has to be added to the item being rendered itself. Because of that we have this function https://github.com/Expensify/App/blob/main/src/libs/SearchUtils.ts#L146-L151 that does a lot of work. It makes the whole search flow from `Search` component to the list itself to the items be less flexible, and its harder to experiment.

That being said the actual problem is still inside the render of Items, and I believe `Search` component itself doesn't rerender that often, and specifically it should not rerender when we scroll.
I have 2 new ideas:
 - memoize the calls to `.getSections()` and `getSorted` from SearchUtils - see if this changes
 - memoize (but via an actual memoize function, like lodash memoize) the value of this function: https://github.com/Expensify/App/blob/main/src/components/Search/index.tsx#L51 because this one is called multiple times by FlatList to count the size of the list component; 

If these 2 things give us nothing, then we might want to start considering usage of some other list implementation FlashList etc for Search.
`Search` is the list that has the most complex items inside I think. And within this items are interactive buttons, potentially images (receipts) etc - so this might be the use case for a different List component.

**Comment by luacmartins** [comment] 2024-07-09 23:09
Thanks for the detailed breakdown @Kicu! I think we can start with the memoize solutions you laid out and check if that improves anything. If that doesn't work, we might wanna profile this view and see which functions are taking the most resources and look for ways to improve those before we move to a different list component, since that's also not a guarantee that we'd fix the issue.

**Comment by ahmedGaber93** [comment] 2024-07-23 10:12
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43490
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **No need, current issue already fixed by them**
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. No
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**This is an improvement performance issue, I think no need for regression test.**

**Comment by strepanier03** [comment] 2024-07-24 17:42
Paid and closed the contract in Upwork, thank you for the checklist @ahmedGaber93!

**Closed by strepanier03** 2024-07-24 17:42 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
