### ISSUE TITLE
[$250] [Held requests] Unholding an expense isn’t optimistically reflected on the expense prevew

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42949] opened 2024-05-31 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717127248876809
 
## Action Performed:
1. Hold an expense via the three dots
2. Go back to the report and confirm that you see Hold and red dot on the expense preview
3. Go bak to the expense thread and unhold the expense via the three dots
4. Confirm that hold no longer shows in the header
5. Go back to the report

## Expected Result:
The expense preview does not show Hold anymore, or the red dot
## Actual Result:
The expense preview still shows Hold as well as the red dot
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-05-30 at 21 37 57](https://github.com/Expensify/App/assets/38435837/0729e618-89b3-4b89-9f2d-cbdced43824b)

https://github.com/Expensify/App/assets/38435837/246e6702-90da-4da2-b4e5-73014847ef84

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f2b43dc6db2ef2b</li>
        <li>Upwork Job ID: 1797663670980612096</li>
        <li>Last Price Increase: 2024-06-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by opalkmm** [comment] 2024-06-05 01:40
I have also tried reproducing this following the video/instructions but am not seeing this error in desktop (mac) or web. When I navigate to the expense page from the link at that top, it properly displays as unheld (no red dot)

**Comment by goldenbear101** [comment] 2024-06-05 20:11
I don't seem to be able to reproduce this, but I have some ideas on what may be the cause. But I can keep trying, maybe its not correctly linked to the ONYXKEY that changes when the expense is unheld, so we could try checking the ONYXKEY OR add logging in the action that handles unholding the expense to make sure the state is being updated.

**Comment by robertjchen** [comment] 2024-06-07 13:25
Thanks for all the tests here, given that we can't reproduce this we'll close this out for now

**Closed by robertjchen** 2024-06-07 13:25 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
