### ISSUE TITLE
[HOLD for payment 2023-10-16] [HOLD for payment 2023-10-10] [$500] Web -  City field is not clear when select another country

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28007] opened 2023-09-22 12:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to home address page
2. Select another country (Make sure the all fields is typed before)

## Expected Result:
City field should be clear when select another country

## Actual Result:
 City field is not clear when select another country

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6ba66f4d-5f76-4964-b27c-315cf358dead

https://github.com/Expensify/App/assets/93399543/b87398be-f322-4973-9db2-75d2c1cd33d5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695197139968609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5128ed81517974f</li>
        <li>Upwork Job ID: 1705190854472331264</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26911820</li>
<li>DylanDylann | Contributor | 26911821</li>
<li>DylanDylann | Reporter | 26911824</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-22 12:03
Proposal by: @DylanDylann
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695197139968609


## Proposal
### Please re-state the problem that we are trying to solve in this issue.
City field is not clear when select another country
### What is the root cause of that problem?
We only use useState for country and state fields because we need to re-set 2 fields when changing country
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L119-L129
I think the city field also should be clear after changing country like state field.
### What changes do you think we should make in order to solve the problem?
Firstly, we need to use useState for city field
```
const [city, setCity] = useState(address.city);
```
When country change we need to re-set city to empty like this
```
const handleAddressChange = (value, key) => {
        if (key !== ‘country’ && key !== ‘state’ && key !== ‘city’) {          // UPDATE HERE
            return;
        }
        if (key === ‘country’) {
            setCurrentCountry(value);
            setState(‘’);
            setCity(‘’);         // UPDATE HERE
            return;
        }
        setState(value);
        setCity(value);
    };
```
and then in here
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L211
we should use value instead of default value
```
value={city || ‘’}
```

**Comment by abzokhattab** [comment] 2023-09-22 13:12
```
    const handleAddressChange = (value, key) => {
        switch (key) {
            case 'country':
                setCurrentCountry(value);
                setState('');
                setCity('');
                setZipCode('');
                break;
            case 'state':
                setState(value);
                break;
            case 'city':
                setCity(value);
                break;
            case 'zipPostCode':
                setZipCode(value);
                break;
            default:
                break;
        }
    };

```

**Comment by zanyrenney** [comment] 2023-09-26 01:43
dupe assignment, so unassigning myself as i am the second assignee for @michaelhaxhiu to manage.

**Comment by DylanDylann** [comment] 2023-09-26 05:24
@abzokhattab This is another bug and I also suggest fixing it in my original proposal for both issues [here](https://github.com/Expensify/App/issues/27814#issuecomment-1727249608)

**Comment by DylanDylann** [comment] 2023-09-27 04:04
@AndrewGable Could you give some of your opinion on this issue when you have a chance?

**Comment by DylanDylann** [comment] 2023-09-28 08:23
@Ollyws PR https://github.com/Expensify/App/pull/28362 is ready for review

**Comment by michaelhaxhiu** [comment] 2023-09-28 14:12
Hang tight... this got the `external` before BZ review.

@Ollyws and @DylanDylann. I want to share some thoughts on why I'm suggesting we review this more carefully before we make any changes:

- I'm not convinced this is a bug yet. Why is it a bug? 
- What if you chose the wrong Country initially and don't want to clear all the other address values? I would think this can be useful basically. 
- I can see an argument for a parent <> child style relationship of sorts here between the `Country` & `City` / `Street` / `Zip`, but still I can see value in the current behavior too.
- With all of this in mind, I am almost leaning toward calling this a `feature request` > `bug` 🤔 

Do we have other examples of clearing subsequent related fields if/when the _parent_ selection is modified? Especially as it relates to addresses? Like maybe when adding a bank account can you test and let me know what you find?

**Comment by michaelhaxhiu** [comment] 2023-09-28 14:17
I'm re-assigning this to another BZ as part of my preparation for Sabbatical (starting Friday).

**Next steps for BZ (Zany):**
- Verify this bug is truly legit and worth fixing (see my post [above](https://github.com/Expensify/App/issues/28007#issuecomment-1739313901)) which I nudged @AndrewGable about in Slack about 2 min ago.
- Depending on verdict of that post, either sherpa this forward or punt.

Given that the PR is already done, this may be in a territory where we should just proceed even if it's more of a feature request. But let's ensure this same style of logic is cascaded/applied to any other areas of the product like adding a bank account.

**Comment by DylanDylann** [comment] 2023-09-28 15:26
@michaelhaxhiu I reported this bug because we also re-set state field when country change as in this issue https://github.com/Expensify/App/issues/23839

**Comment by michaelhaxhiu** [comment] 2023-09-28 15:28
Got it! Thanks for the added context @DylanDylann. You have my buy in for the sake of consistency in our app 👍 . Proceed like normal.

**Comment by michaelhaxhiu** [comment] 2023-09-28 15:34
I updated my comment above to reflect the latest agreement, and payment summary so Zany can quickly handle when it's time.

**Comment by ufumerfarooq** [comment] 2023-10-04 15:21
The PR linked to this issue is causing regression for this issue: https://github.com/Expensify/App/issues/27814

**Comment by DylanDylann** [comment] 2023-10-04 16:20
I don't this is a regression from our PR. I bring a discussion on https://github.com/Expensify/App/pull/28404

**Comment by eVoloshchak** [comment] 2023-10-04 16:38
@DylanDylann, this bug wasn't present when https://github.com/Expensify/App/pull/28404 was merged
(use `gh pr checkout 28404` to double-check)

https://github.com/Expensify/App/assets/9059945/078dcd2c-6d90-4690-9935-75ddf08b89ea

**Comment by DylanDylann** [comment] 2023-10-04 17:37
@AndrewGable  Just a note. In this issue https://github.com/Expensify/App/issues/27814, I proposed a solution to fix both bugs https://github.com/Expensify/App/issues/28007 and https://github.com/Expensify/App/issues/27814 (even though the regression https://github.com/Expensify/App/issues/27814#issuecomment-1745232092 ). But It is not selected because the C+ contributor doesn't think https://github.com/Expensify/App/issues/28007 is a bug. And then when https://github.com/Expensify/App/issues/28007 is accepted as a bug, I mentioned that we also need to fix the same case with the city field in [here](https://github.com/Expensify/App/issues/27814#issuecomment-1738683888) because It is same bug with [OP](https://github.com/Expensify/App/issues/28007) but there is no response.

**Comment by zanyrenney** [comment] 2023-10-16 13:48
**summary of payments**
@Ollyws requires payment [offer](https://www.upwork.com/nx/wm/offer/26911820) (Reviewer) - paid $750 ($500 + $250 urgency)
@DylanDylann requires payment [offer](https://www.upwork.com/nx/wm/offer/26911821) (Contributor) paid $750 ($500 + $250 urgency)
@DylanDylann requires payment [offer](https://www.upwork.com/nx/wm/offer/26911821) (Contributor) - paid $50 reporting bonus

**Closed** 2023-10-16 13:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
