### ISSUE TITLE
Seeing a bunch of old expenses and cannot dismiss them from my LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44696] opened 2024-07-01 19:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719600454036949

## Action Performed:
1. Log in to app
2. Click one of the LHN chat
3. Click on another chat 

## Expected Result:
Clicking on the chat on LHN should take to the chat with and sub header should show
## Actual Result:

- I click into them and notice they do not have a subheader
- If I click onto another one after viewing, the report I just read remains unread.
- I click into certain ones, there is not content above the system notification.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[logs-2024-06-28 18_46_11.975.txt](https://github.com/user-attachments/files/16058052/logs-2024-06-28.18_46_11.975.txt)

https://github.com/Expensify/App/assets/38435837/e8a6c777-d2d7-4bb4-806c-d15b133ab416

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-01 19:06
https://github.com/Expensify/App/issues/44683

**Comment by neil-marcellini** [comment] 2024-07-04 00:27
Ok, I'm getting a start on this. I actually have the same problem currently on staging with my Expensify account so that's a great opportunity to debug it.

I got all the report actions from the report with the snippet below, adapted from [this SO](https://stackoverflowteams.com/c/expensify/questions/15437). I won't post the data here in case it's sensitive.

<details>
<summary>Snippet to get all report actions</summary>

```js
function getAllDataByPrefix({prefix = 'report_', sensitiveKeys = ['lastMessageHtml', 'lastMessageText']} = {}) {
  const dbName = 'OnyxDB';
  const storeName = 'keyvaluepairs';

  return new Promise((resolve, reject) => {
    // Open the IndexedDB database
    const request = indexedDB.open(dbName);

    // Handle database opening success
    request.onsuccess = (event) => {
      const db = event.target.result;

      // Open a transaction on the specified store
      const transaction = db.transaction(storeName, 'readonly');
      const store = transaction.objectStore(storeName);

      // Open a cursor to iterate over all key-value pairs
      const data = [];
      const keyRange = IDBKeyRange.lowerBound(prefix);
      const requestGetData = store.openCursor(keyRange);

      requestGetData.onsuccess = (event) => {
        const cursor = event.target.result;
        if (cursor) {
          const key = cursor.key;
          if (key.startsWith(prefix)) {
            const value = removeSensitiveValues(cursor.value);
            data.push({ key, value });
          }
          cursor.continue();
        } else {
          // No more key-value pairs, resolve with the filtered data
          resolve(data);
        }
      };

      requestGetData.onerror = (event) => {
        reject(`Error getting data: ${event.target.error}`);
      };

      // Close the transaction and database
      transaction.oncomplete = () => {
        db.close();
      };
    };

    // Handle database opening error
    request.onerror = (event) => {
      reject(`Error opening database: ${event.target.error}`);
    };

    function removeSensitiveValues(obj) {
      for (const key of sensitiveKeys) {
        if (obj.hasOwnProperty(key)) {
          delete obj[key];
        }
      }
      return obj;
    }
  });
}

function getSortedReportActions(reportActions, shouldSortInDescendingOrder = false) {
    if (!Array.isArray(reportActions)) {
        throw new Error(`ReportActionsUtils.getSortedReportActions requires an array, received ${typeof reportActions}`);
    }

    const invertedMultiplier = shouldSortInDescendingOrder ? -1 : 1;

    const sortedActions = reportActions?.filter(Boolean).sort((first, second) => {
        // First sort by timestamp
        if (first.created !== second.created) {
            return (first.created < second.created ? -1 : 1) * invertedMultiplier;
        }

        // Then by action type, ensuring that `CREATED` actions always come first if they have the same timestamp as another action type
        if ((first.actionName === 'CREATED' || second.actionName === 'CREATED') && first.actionName !== second.actionName) {
            return (first.actionName === 'CREATED' ? -1 : 1) * invertedMultiplier;
        }
        // Ensure that `REPORT_PREVIEW` actions always come after if they have the same timestamp as another action type
        if ((first.actionName === 'REPORTPREVIEW' || second.actionName === 'REPORTPREVIEW') && first.actionName !== second.actionName) {
            return (first.actionName === 'REPORTPREVIEW' ? 1 : -1) * invertedMultiplier;
        }

        // Then fallback on reportActionID as the final sorting criteria. It is a random number,
        // but using this will ensure that the order of reportActions with the same created time and action type
        // will be consistent across all users and devices
        return (first.reportActionID < second.reportActionID ? -1 : 1) * invertedMultiplier;
    });

    return sortedActions;
}

// Example usage
getAllDataByPrefix({prefix: 'reportActions_2601020397631250', sensitiveKeys: []})
  .then((data) => {
    console.log('Retrieved data:', data);
    const sortedReportActions = getSortedReportActions(Object.values(data[0].value ?? {}));
    console.log('Sorted report actions:', sortedReportActions);
  })
  .catch((error) => {
    console.error('Error:', error);
  });
```
</details>


Next up I'm going to look into the code which determines if a report is shown in the LHN as unread, to pick out why these are showing as unread. I also notice that opening these reports causes GetOlderActions to loop, but that's probably a separate problem.

**Comment by neil-marcellini** [comment] 2024-07-04 01:08
So I think the type of action that made this report show up in the first place is the `EXPORTINTEGRATION` action. I heard rumors that these are now showing up in NewDot due to the system messages project. I'll look into that and also where these actions are created on the backend. If we want it to be viewable but not visible in NewDot I think the report notification preference has to be hidden, or mute, but I need to look into that.

Ah, I see this was [added to the enhanced system messages](https://github.com/Expensify/Auth/blob/b9fb949658672bb9d056ac814e48a61b3179db5c/auth/lib/ReportAction.cpp#L41) by @deetergp 2 days ago. Oh, and that commit is from a PR that fixed this issue.

This issue is a duplicate of that one. To fix the current problem in NewDot we just have to sign out and back in.

**Closed by neil-marcellini** 2024-07-04 01:08 UTC
Labels: Daily, Internal, Bug, AutoAssignerNewDotQuality
