### ISSUE TITLE
[$250] Tax code - Error shows up when attempting to save tax code without modifying it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45770] opened 2024-07-19 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is under Control plan
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Taxes
3. Click on any tax
4. Click Tax code
5. Without modifying the existing tax code, save the tax code

## Expected Result:
User will be able to save existing tax code when no changes are made

## Actual Result:
Error shows up when attempting to save tax code without modifying it - This tax code is already in use

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/38d088e0-a3b1-44e5-a625-8aaebf1030c6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100ee19e52f8bb5b6</li>
        <li>Upwork Job ID: 1814285898085752540</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by etCoderDysto** [comment] 2024-07-19 13:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error shows up when attempting to save tax code without modifying it
### What is the root cause of that problem?
On submit, we call `validateTaxCode` passing current input value and policy as params. And `validateTaxCode`, compares current value with existing tax code keys and returns error when finding a matching key in `policy.taxRates.taxes`
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/pages/workspace/taxes/WorkspaceTaxCodePage.tsx#L50-L55
### What changes do you think we should make in order to solve the problem?
We should check if the input value is equal to the `currentTaxCode` tax code. Then return empty object if they are equal before returning result of `validateTaxCode(policy, values);`
```javascript
if (values?.taxCode.trim() === currentTaxCode) return {};
return validateTaxCode(policy, values);
 ```


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-07-19 13:07
@dangrous @Gonals @rushatgabhane @dylanexpensify - heads up!

**Comment by trjExpensify** [comment] 2024-07-19 13:13
FWIW @puneetlath, I don't think this is a deploy blocker. I'll let you make that call, but get the proposal triaged to move in the direction of fixing it. 👍

**Comment by rushatgabhane** [comment] 2024-07-19 13:16
Fixing it as part of https://github.com/Expensify/App/issues/44258

**Comment by dangrous** [comment] 2024-07-19 13:22
removing deploy blocker label, minor issue

**Comment by dangrous** [comment] 2024-07-22 14:21
How are we looking on the fix for this? I know there's that other bug too, that feels backend to me so I think it's separate? But I'll confirm today.

**Comment by rushatgabhane** [comment] 2024-07-22 16:35
> How are we looking on the fix for this

@dangrous fixing it here - https://github.com/Expensify/App/pull/45866 because it was a one liner

**Comment by dangrous** [comment] 2024-07-23 15:30
oh okay great! ping me as a reviewer when it's ready if you could - thanks!

**Comment by dangrous** [comment] 2024-08-02 18:34
not overdue, solution has been deployed to prod. Didn't get the automation because the issue link didn't have `$`. I added it so hopefully we'll get it, but if not - payment due 8/8 i believe!

**Comment by rushatgabhane** [comment] 2024-08-12 15:29
this would be a regression @dangrous

**Comment by dangrous** [comment] 2024-08-12 21:28
okay cool i will go ahead and close then, if you need anything else let me know!

**Closed by dangrous** 2024-08-12 21:28 UTC
Labels: Reviewing, External, Engineering, Daily
