### ISSUE TITLE
[$500] Task - [Deleted task] is not grayed out in task report when the task is deleted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28190] opened 2023-09-25 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. click the green FAB button > Assign a Task
3. Add a Title and a Description
4. Assign a known user to the Task
5. Navigate to a task report 
6. Go offline
7. Click three-dot menu > Cancel (you should see [Deleted Task])
8. Return to the 1:1 DM where the task is shared

## Expected Result:
In Step 4, after deleting the task, [Deleted task] message is grayed out

## Actual Result:
In Step 4, after deleting the task, [Deleted task] message is not grayed out in the task report, while [Deleted task] is grayed out in 1:1 DM in Step 5

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/45ebae02-2d7d-490d-adeb-2db5c800e481

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140a361ebd43cf297</li>
        <li>Upwork Job ID: 1706757467311755264</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-26 08:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
[Deleted task] is not grey when cancelling task offline
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b9a2f625e45a9153fe927633d86b986fbd5c1f65/src/pages/home/report/ReportActionItem.js#L521-L536
We don’t wrap [Deleted task] message by OfflineWithFeedback Component
### What changes do you think we should make in order to solve the problem?
we should add OfflineWithFeedback Component as wrapper like this
```
<OfflineWithFeedback pendingAction={parentReportAction.pendingAction}>
```

**Comment by DylanDylann** [comment] 2023-09-26 08:53
My proposal post first in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1695713547152209)

**Comment by Christinadobrzyn** [comment] 2023-09-26 17:16
I can reproduce this but I'm not actually sure if this is a bug or a feature request. 

When you come back online, the [Deleted Task] is bold in both the chat and the Task Assignment. I don't know if this needs to be fixed now. What is expected when you're online? It should be bold right?
 
![2023-09-26_11-14-22 (1)](https://github.com/Expensify/App/assets/51066321/de00f516-f529-4f36-ad5f-4cb5a655afbf)

**Comment by Christinadobrzyn** [comment] 2023-09-26 17:20
Asking the team - https://expensify.slack.com/archives/C01SKUP7QR0/p1695748789919179

**Comment by Christinadobrzyn** [comment] 2023-09-26 19:47
Seems like polish so something we should move forward with fixing. Expensify Tasks [Design doc](https://docs.google.com/document/d/1uFj0Oh9qtFJ-EH-lg00oMflo8uhkV2yXUT8Tbg6cKws/edit#heading=h.olra4emh77tp) (not available for everyone) says we follow offline first. So that would indicate that the [Deleted Message] needs to be greyed out not bold.

**Comment by MichaelAwinda** [comment] 2023-09-26 20:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The [Delete task] message is not grayed out in the task report when the task was deleted offline. The message should be grayed out when the task is deleted offline.
### What is the root cause of that problem?
The task report component is not re-rendering when a task is deleted offline. This could happen if the component is using another variable that is not updated when a task is deleted offline.
### What changes do you think we should make in order to solve the problem?

We can use the state or props to render the tasks, and update them accordingly when a task is deleted offline. This way, the component will re-render and show the correct status of the tasks.
### What alternative solutions did you explore? (Optional)

**Comment by MichaelAwinda** [comment] 2023-09-26 20:58
Contributor details
Your Expensify account email: <michaelawinda1@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01d2d01066fd216588>

**Comment by MichaelAwinda** [comment] 2023-09-26 21:23
Contributor details
Your Expensify account email: michaelawinda1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d2d01066fd216588

**Comment by jjcoffee** [comment] 2023-09-28 13:07
Unsure of how to handle a proposal being [posted](https://github.com/Expensify/App/issues/28190#issuecomment-1735110747) on Slack earlier than the first proposal on the issue, but I _think_ since this issue wasn't created from the bug on Slack where the proposal was posted, that we unfortunately wouldn't take it into account in this case.

That being said, I prefer @hungvu193's [proposal](https://github.com/Expensify/App/issues/28190#issuecomment-1735088039) anyway as it feels a bit tidier to add the extra `pendingAction` rather than getting it from the `parentReportAction`.

 :ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2023-10-03 12:57
@DylanDylann I don't feel too strongly about it, it just makes sense to me to also update the `pendingAction` on the actual report you're deleting/cancelling.

**Comment by DylanDylann** [comment] 2023-10-03 13:51
@jjcoffee 
When canceling the task, we only change the parent action of task report and add a new comment "Delete task", the rest remains the same. If we add pendingAction for the task report, not only the first message on task report is grey out (this is mentioned in OP) but the task report in LHN is also greyed out. Is it expected?

**Comment by jjcoffee** [comment] 2023-10-03 13:56
@hungvu193 Do you want to weigh in on [this](https://github.com/Expensify/App/issues/28190#issuecomment-1745023587)?

**Comment by DylanDylann** [comment] 2023-10-03 14:01
One more thing, We want to grey out the first message of task report (It is a report action). IMO, It is more suitable if we use pending action of report action to grey out report action (this is way we use in other palces). we shouldn't use pending action of report to grey out the report action (don't use in other places).

**Comment by jjcoffee** [comment] 2023-10-03 14:26
@DylanDylann The task report is already greyed out in LHN for me on latest main. 

Remember that the point of `pendingAction` isn't only to grey things out :smile: We could also technically just pass `isDeletedParentAction` as the `pendingAction` in `OfflineWithFeedback`, since we already set that optimistically [here](https://github.com/Expensify/App/blob/e14e9ee2724cf61de9bf4d1bb6dea2b1dcb96995/src/libs/actions/Task.js#L795) but I think we're just splitting hairs here as any method works, unless @francoisl has a strong opinion otherwise!

**Comment by DylanDylann** [comment] 2023-10-03 14:41
> We want to grey out the first message of task report (It is a report action). IMO, It is more suitable if we use pending action of report action to grey out report action (this is way we use in other palces). we shouldn't use pending action of report to grey out the report action (don't use in other places).

Just a final note, some action to task report on offline will make the first message of task report is greyed out if we use pendingAction of report for it.

**Comment by Christinadobrzyn** [comment] 2023-10-03 16:54
hi @jjcoffee let me know if these proposals are looking good or if you'd like to see more!

**Comment by francoisl** [comment] 2023-10-04 04:10
Looks like we just did some refactoring for tasks with https://github.com/Expensify/App/issues/24601 / https://github.com/Expensify/App/pull/27827 and I'm not sure this is still an issue... in particular, after canceling a task while offline, we now still display the regular task view, with the task name / checkbox, description and assignee - and no `[Deleted task]` message as reported above.

https://github.com/Expensify/App/assets/2229301/70a78c43-7d2a-4ff9-be16-06b8f161b46d

Am I missing something, or is this no longer an issue?

**Comment by jjcoffee** [comment] 2023-10-04 08:58
Sorry I missed that! We're good to close this then @francoisl

**Comment by Christinadobrzyn** [comment] 2023-10-04 15:50
I'll ask QA to test just to make sure this is not happening anymore - https://expensify.slack.com/archives/C9YU7BX5M/p1696434612063849

**Comment by kbecciv** [comment] 2023-10-04 16:30
@Christinadobrzyn Issue is not reproduced on v1.3.77-5. We are seeing old UI task page instead of the new one. Is this expected? 

https://github.com/Expensify/App/assets/93399543/f6836f0c-4ed4-498d-af01-3e530b8923d4

**New UI task page** 
![Screenshot 2023-10-05 at 00 25 00](https://github.com/Expensify/App/assets/93399543/75765765-52b0-4e45-859b-d951b2b8696d)

**Comment by francoisl** [comment] 2023-10-05 00:19
I believe your "New UI task page" is from the video in the original post on an older version? Anyway, looks like this is no longer an issue, going to close.

Thanks for the proposals anyway everyone, and on to the next one 🚀

**Closed by francoisl** 2023-10-05 00:19 UTC
Labels: External, Daily, Help Wanted, Bug
