### ISSUE TITLE
Task - Clicking Confirm task few times creates multiple tasks

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41525] opened 2024-05-02 18:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0.
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a30@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to #announce room
2. Go to +> Assign Task> Add title> Click Next
3. Click on Confirm task button few times

## Expected Result:
Only one Task report should be created

## Actual Result:
Clicking Confirm task few times creates multiple tasks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c36c3274-5230-4145-8cfb-46bfb55c6d72

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-02 18:28
We think that this bug might be related to #vip-vsp

**Comment by neonbhai** [comment] 2024-05-02 18:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Clicking Confirm task few times creates multiple tasks

### What is the root cause of that problem?
We do not throttle the button clicks here, so Create Task runs multiple times

### What changes do you think we should make in order to solve the problem?
We should use the `useSingleExecution()` hook to carry out the create task presses

**Comment by neonbhai** [comment] 2024-05-02 18:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Clicking Confirm task few times creates multiple tasks

### What is the root cause of that problem?
We do not have the `useSingleExecution` hook for web:

Code presumes that the issue does not occur for web devices, but we can see that it is possible to run into multiple execution issues

### What changes do you think we should make in order to solve the problem?
Enable the `useSingleExecution()` native logic in web also.

- We can just use a single file since we now need it for both web and native.

**Comment by joekaufmanexpensify** [comment] 2024-05-03 14:06
I can reproduce this. However, reproducing this relies on clicking the button to create a task intentionally repeatedly before receiving feedback, and more quickly than an actual customer is likely to ever do IMO. 

I'm not sure it's likely that many/any customers will ever experience this.

**Comment by joekaufmanexpensify** [comment] 2024-05-03 14:07
I don't think this is something that should be prioritized right now. Closing.

**Closed by joekaufmanexpensify** 2024-05-03 14:07 UTC
Labels: Daily, Bug
