### ISSUE TITLE
 IOU- In split bill, user name not changed in header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24453] opened 2023-08-11 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon to note user first name
3. Tap Fab
4. Tap Split bill
5. Enter amount ₹25,800
6. Tap next
7. Select a user
8. Tap next
9. Tap split ₹25,800
10. Tap Users' individual split amount ₹12,900
11. Again tap on Users' individual split amount
₹12, 900
12. Note the header "From user owes ₹12, 900 in 54's Ex...
13. Navigate back to LHN
14. Tap profile icon twice
15. Tap display name
16. Change user first name from " 54" To "new" and "save"
17. Navigate to LHN
18. Tap on IOU report of users' split bill page
19. Note the changed user name "new" and tap Users' individual split amount ₹12, 900
20. Again note the changed user name "new" and tap Users' individual split amount ₹12, 900
21. Note the header

## Expected Result:
The header must show the current user name as "From user owes ₹12, 900 in New's Ex... and must not show old user name as "From user owes ₹12, 900 in 54's Ex... "

## Actual Result:
The header "From user owes ₹12, 900 in 54's Ex..." is showed instead of "From user owes ₹12, 900 in New's Ex..."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b70b0183-139a-4760-a90e-51b8d066927a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alphaboss1104** [comment] 2023-08-14 11:43
I can't reproduce it. I pull the latest code and tried to reproduce this issue but I couldn't do it.

[screen-capture.webm](https://github.com/Expensify/App/assets/137152763/1cd6c47b-f43c-43f3-b275-1231b12114a8)

**Comment by bfitzexpensify** [comment] 2023-08-16 09:42
I'm also struggling to reproduce this. @lanitochka17 was it only Android / Chrome that you were able to reproduce this on?

**Comment by lanitochka17** [comment] 2023-08-16 17:58
I am reproducible in Windows10/Chrome 


https://github.com/Expensify/App/assets/78819774/053993ef-80be-4e5c-bf5e-3da7e6812622

**Comment by alphaboss1104** [comment] 2023-08-16 18:09
@lanitochka17  Your account is connected to the bank?

**Comment by lanitochka17** [comment] 2023-08-16 21:17
the Same issue with connected bank account
![Снимок 222](https://github.com/Expensify/App/assets/78819774/ff23d50a-60c4-4a2b-9e34-1d0dddc429f1)

**Comment by bfitzexpensify** [comment] 2023-08-23 10:40
OK, need to spend some time today testing this then via browserstack

**Comment by bfitzexpensify** [comment] 2023-08-23 11:39
OK, the [guidance](https://expensify.slack.com/archives/C01SKUP7QR0/p1687266177434349) for windows issues is that we should only fix them if they make the platform unusable, which this doesn't qualify against. Closing this out

**Closed by bfitzexpensify** 2023-08-23 11:39 UTC
Labels: Daily, Bug
