### ISSUE TITLE
PAY on 06/03 - [$500] [Wave Collect] [Ideal Nav] Workspace - Workspace is not clickable after returning from error page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35690] opened 2024-02-02 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is invited to Collect workspace
1. Go to staging.new.expensify.com
2. Click Settings from the bottom
2. Click on the Collect workspace
3. Add /members to the end of URL and navigate to it
4. Click the back button on the top left of right hand page
5. Click on the Collect workspace

## Expected Result:
The workspace page for Collect workspace will open

## Actual Result:
The Collect workspace in Workspaces overview is no longer clickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a19a1413-0381-4fb2-afb2-8f447fd841ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159986817ac8b64d5</li>
        <li>Upwork Job ID: 1753494361146109952</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28146520</li>
<li>bernhardoj | Contributor | 28146521</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 18:24
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by blimpich** [comment] 2024-02-02 18:50
This is probably ideal nav related https://github.com/Expensify/App/pull/33280. Going to follow hayata's instructions as per [this slack thread](https://expensify.slack.com/archives/C03TQ48KC/p1706899377429909) (internal Expensify Slack channel).

**Comment by blimpich** [comment] 2024-02-02 18:56
Also not a blocker, at least not worth reverting ideal nav over.

**Comment by blimpich** [comment] 2024-02-02 19:04
> @blimpich, is this open for external proposals?

It is now 🙂. Thanks for the reminder

**Comment by bernhardoj** [comment] 2024-02-03 03:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't navigate to the same workspace after accessing the not found page of a workspace.

### What is the root cause of that problem?
When we press the go back button of the not found page, it will navigate to /settings/workspace.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/workspace/WorkspaceMembersPage.js#L428

It will update the central pane navigator screen with the workspace list, but notice that the bottom tab navigator on the left still shows the previous workspace settings.
<img width="1188" alt="image" src="https://github.com/Expensify/App/assets/50919443/b9f6f0b0-6469-432b-bcda-bfd9e8d6124e">

That is because the bottom tab navigator screen is not updated. When we click the same workspace, it will try to navigate to the workspace detail, but it will return early here because the workspace detail that we want to navigate is the same workspace that is currently shown on the bottom tab navigator on the left.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/linkTo.ts#L205-L210

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/linkTo.ts#L98-L102

### What changes do you think we should make in order to solve the problem?

We need to update the bottom tab navigator too. We already did this in `WorkspacePageWithSections`
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/workspace/WorkspacePageWithSections.tsx#L116-L121

where we use this component to wrap many workspace pages, like the workspace overview page.

We can either copy the go back code or wrap the members page with `WorkspacePageWithSections` too

**Comment by bfitzexpensify** [comment] 2024-02-06 06:44
How does @bernhardoj's proposal look @shubham1206agra?

**Comment by shubham1206agra** [comment] 2024-02-06 06:50
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/35690#issuecomment-1925042387) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-02-07 06:50
PR is ready

cc: @shubham1206agra

**Comment by bfitzexpensify** [comment] 2024-02-18 21:06
Bump on this one @shubham1206agra - thank you!

**Comment by bfitzexpensify** [comment] 2024-03-04 01:24
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@shubham1206agra ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@shubham1206agra ] Determine if we should create a regression test for this bug.
- [ ] [@shubham1206agra ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bfitzexpensify** [comment] 2024-03-06 00:30
Contracts paid out, BZ checklist complete, no need for a regression test - we're all done here.

**Closed by bfitzexpensify** 2024-03-06 00:30 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
