### ISSUE TITLE
[Payment due October 4]Remove any code that references or was used only for free workspaces (policies)

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#48345] opened 2024-08-30 15:56 UTC
# Problem
There was a [project this summer to deprecate and remove all of the free workspaces in Expensiy](https://github.com/Expensify/Expensify/issues/373964) and migrate them over to team workspaces. Now that there are no free workspaces in the database or in the backend, there is a lot of leftover code that is no longer necessary.

## Why is this important to solve?
Keeping the code up-to-date reduces technical debt and allows it to be more easily maintained.

# Solution
Find any code that references or was used only for the free plan in E/App and remove it.

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by tgolen** [comment] 2024-08-30 16:24
> Should we also remove the Personal Policy?

Nope, that one needs to stay there. 

While you are looking for the code that can be removed, I've heard reports that there are pages or routes that are still referencing the free plan somehow, so please try to track down any pages or URL routes of that nature too. They might not be references that constant, so they might be a little tricky to find.

**Comment by Christinadobrzyn** [comment] 2024-09-03 15:53
Just a heads up - I'm going to be ooo 9/4-9/11. I'll add a BZ teammate to watch this while I'm away! 

@anmurali - we are reviewing/discussing this [proposal](https://github.com/Expensify/App/issues/48345#issuecomment-2321984862). So I think you'll just need to monitor this but I don't expect anything will be needed while I'm away.

**Comment by tgolen** [comment] 2024-09-04 14:58
bump @situchan Can you please give the proposals a look?

**Comment by situchan** [comment] 2024-09-04 19:52
We can go with @cretadn22's [proposal](https://github.com/Expensify/App/issues/48345#issuecomment-2321830709).
Please add screenshots of all pages to be removed from route in PR. (opened from deep link)
🎀👀🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment] 2024-09-16 21:00
@tgolen, when you have a moment, can you please check out this proposal review? TY! https://github.com/Expensify/App/issues/48345#issuecomment-2329855079

**Comment by tgolen** [comment] 2024-09-20 15:28
@Christinadobrzyn Yeah, I had a look at it and assigned them a couple of weeks ago. It looks like they have a PR that is ready for review which I'm going to be taking a look at today.

**Comment by Christinadobrzyn** [comment] 2024-09-24 20:04
Thanks for the update @tgolen! 

It looks like this [PR](https://github.com/Expensify/App/pull/48700) was just merged to staging. 

heads up - I'm going to be ooo until 9/30. Since we're reviewing PRs I'm not going to assign a BZ teammate to monitor this while I'm gone. If you need someone while I'm gone please feel free to reach out in Slack for a volunteer. TY!

**Comment by Christinadobrzyn** [comment] 2024-09-30 05:34
[PR](https://github.com/Expensify/App/pull/48700) in production! Adding payment date to the title. 

Payouts due:

- [ ] Contributor: $250 @cretadn22 (upwork offer - https://www.upwork.com/nx/wm/offer/104189664)
- [ ] Contributor+: $250 @situchan (are you paid via NewDot?)

Do we need a regression test (I assume not?)

**Comment by situchan** [comment] 2024-09-30 06:17
No need regression test. I am paid via upwork

**Comment by Christinadobrzyn** [comment] 2024-10-04 07:12
Thanks @situchan can you accept this offer - https://github.com/Expensify/App/issues/48345#issuecomment-2382150454

TY!

**Comment by Christinadobrzyn** [comment] 2024-10-04 07:12
Moving to daily to pay this out.

**Comment by Christinadobrzyn** [comment] 2024-10-07 03:44
waiting on @situchan to accept the offer - https://www.upwork.com/nx/wm/offer/104260166

**Comment by Christinadobrzyn** [comment] 2024-10-08 03:48
This is paid out! Based on this payment summary https://github.com/Expensify/App/issues/48345#issuecomment-2382150454

Closing as complete

**Closed by Christinadobrzyn** 2024-10-08 03:48 UTC
Labels: Reviewing, External, Daily, Bug
