### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Web - Active 'Mask as Unread' button on messages that are already marked as unread. Reported by @chiragxarora

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22019] opened 2023-07-01 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. hover over the reaction and click on mark as unread. notice that a green Right sign :heavy_check_mark: is shown and the message is marked as Unread
3. Now hover again to the reaction menu and click on mark as unread again. Notice that the Green right sign is still shown even if the message is already marked as Unread.

## Expected Result:
The 'Mark as unread' button should not be active for messages that are already marked as Unread.

## Actual Result:
The 'Mark as unread' button is active for messages that are already marked as Unread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ac2429f4-8607-4b69-b231-53155268b660

https://github.com/Expensify/App/assets/93399543/bff34cd5-b16d-464b-801a-1a07072b7def

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688194742388519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d02fd6aaa798d3be</li>
        <li>Upwork Job ID: 1677363011307827200</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25990093</li>
<li>hungvu193 | Contributor | 25990095</li>
<li>daveSeife | Reporter | 25990097</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-07-04 08:08
reviewing

**Comment by dylanexpensify** [comment] 2023-07-04 08:15
Asking for confirmation

**Comment by dylanexpensify** [comment] 2023-07-07 08:41
not a bug

**Comment by dylanexpensify** [comment] 2023-07-07 17:04
Sorry about that @c3024, it seems I misinterpreted what was actually occurring. Agree this is a bug, and I can repro!

**Comment by dylanexpensify** [comment] 2023-07-10 09:40
@chiragxarora thanks for reminder! Will review

**Comment by dylanexpensify** [comment] 2023-07-12 08:46
@abdulrahuman5196 can we get these proposals reviewed today please?

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:18
Sorry for the delay. Will complete the review in the morning.

**Comment by abdulrahuman5196** [comment] 2023-07-15 13:07
@dylanexpensify  To clarify, i am little confused with the test steps.
- The test steps talk about green tick mark. But expectation means 'mark as unread' should not be active.

I am assuming the expectation is for the message which is having the 'new' maker, when hover we shouldn't should the mark as unread, is it?

**Comment by dylanexpensify** [comment] 2023-07-18 12:02
Reviewing!

**Comment by dylanexpensify** [comment] 2023-07-20 20:41
@abdulrahuman5196 that's correct!

**Comment by dylanexpensify** [comment] 2023-07-24 08:36
@abdulrahuman5196 mind reviewing the latest proposal? 🙇‍♂️

**Comment by abdulrahuman5196** [comment] 2023-07-26 21:02
Reviewing in my morning

**Comment by dylanexpensify** [comment] 2023-07-31 09:11
@abdulrahuman5196 mind reviewing

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:53
Reviewing today

**Comment by abdulrahuman5196** [comment] 2023-08-01 18:09
> This issue will be fixed in here: #23473. So we should put this on hold.

@hungvu193 I don't understand. That issue seems to be different.

**Comment by dylanexpensify** [comment] 2023-08-04 12:10
@c3024 and @hungvu193 mind replying today on the above?? 🙇‍♂️

**Comment by abdulrahuman5196** [comment] 2023-08-04 12:11
Still I have @hungvu193  proposal to review. Will do that as well from my end

**Comment by abdulrahuman5196** [comment] 2023-08-06 16:51
@hungvu193 's proposal here https://github.com/Expensify/App/issues/22019#issuecomment-1615986201 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by PauloGasparSv** [comment] 2023-08-07 14:33
> @hungvu193 's proposal here [#22019 (comment)](https://github.com/Expensify/App/issues/22019#issuecomment-1615986201) looks good and works well.
> 
> 🎀 👀 🎀 C+ Reviewed

Thks @abdulrahuman5196, makes sense to me too so I'm assigning @hungvu193 here!

**Comment by PauloGasparSv** [comment] 2023-08-07 14:37
Oh, this is [labeled as `Internal` ](https://github.com/Expensify/App/issues/22019#issuecomment-1656926098), changing it to `External` or else assigning @hungvu193 won't trigger the offer

**Comment by PauloGasparSv** [comment] 2023-08-07 14:43
> also, @PauloGasparSv can you update the original post and add me as the reporter, as per this [#22019 (comment)](https://github.com/Expensify/App/issues/22019#issuecomment-1625699927)
> 
> Looks like @dylanexpensify added me in the title but not in the reporter field and hence I didn't receive the automatic offer

Sure thing, didn't notice that!

@dylanexpensify can we edit [this offer](https://github.com/Expensify/App/issues/22019#issuecomment-1667992422) made to another reporter?

**Comment by BhuvaneshPatil** [comment] 2023-08-07 17:05
I have raised this issue way before, but was marked as `Not a Bug`.
https://expensify.slack.com/archives/C049HHMV9SM/p1685862962415139

**Comment by BhuvaneshPatil** [comment] 2023-08-07 17:13
I have mentioned that.

**Comment by dylanexpensify** [comment] 2023-08-11 20:01
Nice work!

**Comment by abdulrahuman5196** [comment] 2023-08-12 19:13
No BZ checklist, since the PR was reverted as an non-intended feature.

**Comment by dylanexpensify** [comment] 2023-08-18 19:17
Payment summary:
- Reporter: @chiragxarora $250
- Contributor: @hungvu193 $1,500
- C+: @abdulrahuman5196 $1,500

[Upwork job](https://www.upwork.com/jobs/~01d02fd6aaa798d3be). Please apply!

**Comment by abdulrahuman5196** [comment] 2023-08-18 19:20
@dylanexpensify  the upwork was auto sent. I had previously accepted the offer.

**Comment by dylanexpensify** [comment] 2023-08-25 11:49
Yes!

**Comment by dylanexpensify** [comment] 2023-08-25 11:54
@hungvu193 @abdulrahuman5196 payments w/bonus sent!
@chiragxarora sending invite!

**Closed** 2023-09-01 12:03 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
