### ISSUE TITLE
[$500]  Login - A black underlay appears when pulling down the welcome modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35547] opened 2024-02-01 13:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with a new account
2. Pull down the welcome modal

## Expected Result:
The background will reveal LHN

## Actual Result:
A black underlay appears when pulling down the welcome modal.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/273bc70a-0820-47be-aa30-ec0787634b02

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bbb767262af41b41</li>
        <li>Upwork Job ID: 1753042822704033792</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-02-01 13:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dragging down the welcome modal shows a black background.

### What is the root cause of that problem?
The modal is wrapped with a ScrollView
https://github.com/Expensify/App/blob/b6363778127003ce5ecb7375c30bb5d05d77b7d9/src/components/PurposeForUsingExpensifyModal.tsx#L147

and on iOS, you can "bounce" the scroll by dragging it at the edge. The bg color is black because we didn't set any bg color to it.

### What changes do you think we should make in order to solve the problem?

If we expect the bg color to be purple color, then we need to move the bg color from the child View to the scroll view.
https://github.com/Expensify/App/blob/b6363778127003ce5ecb7375c30bb5d05d77b7d9/src/components/PurposeForUsingExpensifyModal.tsx#L147-L148

Then, we need to wrap the menu items view with a new View that will has a bg app color.
https://github.com/Expensify/App/blob/b6363778127003ce5ecb7375c30bb5d05d77b7d9/src/components/PurposeForUsingExpensifyModal.tsx#L164-L176


### What alternative solutions did you explore? (Optional)
Disable the bounce

**Comment by shahinyan11** [comment] 2024-02-01 14:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login - A black underlay appears when pulling down the welcome modal

### What is the root cause of that problem?
Because the modal container takes the background color that matches the current theme.
### What changes do you think we should make in order to solve the problem?
Replace [this](https://github.com/Expensify/App/blob/dc748de8f2108a3f3014fb77a7b567317646ea4e/src/components/PurposeForUsingExpensifyModal.tsx#L143C13-L143C45) line with the code below
```
innerContainerStyle={{...styles.pt0, backgroundColor: 'transparent'}}
```
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-02-01 14:59
[Proposal](https://github.com/Expensify/App/issues/35547#issuecomment-1921304750) updated. Added another alt solution

**Comment by cubuspl42** [comment] 2024-02-05 12:13
@bernhardoj @shahinyan11 

> ## Expected Result:
> 
> The background will reveal LHN

How do your proposals relate to the stated expected behavior?

**Comment by bernhardoj** [comment] 2024-02-05 15:19
@cubuspl42 Oh my bad, I didn't read the expected result. I think the QA confuses the expected result. Our bottom docked modal never has the ability to swipe down to close. It's disabled.
https://github.com/Expensify/App/blob/20e144d5d10f0ec790948fb3db6cad51262f4ef2/src/styles/utils/generators/ModalStyleUtils.ts#L185

It gives a sense that the modal can be closed with a swipe, but it's because the modal is scrollable.

**Comment by shahinyan11** [comment] 2024-02-06 09:42
> How do your proposals relate to the stated expected behavior?

@cubuspl42 I don't see anything about closing the modal window in the expected result. As far as I understand, when moving the modal down, the LHN should be visible in the background.

**Comment by cubuspl42** [comment] 2024-02-06 09:44
@shahinyan11 Oh, so you actually had that the stated expected result mind. Would you add a video to your proposal, showing the achieved effect?

**Comment by shahinyan11** [comment] 2024-02-06 10:40
@cubuspl42 


https://github.com/Expensify/App/assets/46921547/2cf753c9-8009-49af-8248-e82f020a4828

**Comment by bernhardoj** [comment] 2024-02-07 11:39
@cubuspl42 do you have any thoughts on my previous comment? I don't think we really want to make it transparent.

https://github.com/Expensify/App/assets/50919443/21c1e2c4-52da-403c-9176-6744b03fc52a

We can additionally ask @stitesExpensify the expected behavior as he is the one who implements this page/modal.

**Comment by cubuspl42** [comment] 2024-02-07 11:56
> do you have any thoughts on my previous comment?

Not really. I question the expected behavior when I find it unintuitive; it wasn't the case here. It actually feels natural to see the LHN behind this modal.

**Comment by MonilBhavsar** [comment] 2024-02-07 12:02
Proposal looks good but would like to get extra set of eyes from @Expensify/design team. cc @stitesExpensify

**Comment by bernhardoj** [comment] 2024-02-07 12:08
I don't think it's natural for this case, right?

<img width="296" alt="image" src="https://github.com/Expensify/App/assets/50919443/b68e4794-4901-4928-968d-832ae904d4c9">

Also, making it transparent makes it even more sense that the modal is swipeable and can be closed, but in reality, is not possible which feels broken as a user.

IMO, it feels more natural if we allow the swipe on the modal.

**Comment by shawnborton** [comment] 2024-02-07 13:53
Yeah, I agree that this modal view shouldn't be able to be scrolled like that. @stitesExpensify can you take a look and weigh in here as well since you implemented this?

**Comment by shawnborton** [comment] 2024-02-07 13:54
We might consider just making this a full screen modal on mobile - I actually could have sworn that was the case? That would prevent a lot of this weirdness.

**Comment by shahinyan11** [comment] 2024-02-07 14:25
I just suggested a solution according to the expected result. If there should be another behavior  we can clarify it and provide another solution

**Comment by stitesExpensify** [comment] 2024-02-07 15:50
@shawnborton what do you mean by a full screen modal? Do you mean like the settings pages?

**Comment by shawnborton** [comment] 2024-02-07 15:54
Correct - I would think it would occupy the entire height/width of the mobile screen, and not appear as a bottom-docked modal.

**Comment by stitesExpensify** [comment] 2024-02-07 16:02
I think that is a significant refactor (a contributor can feel free to prove me wrong on that though). If I am correct, then I don't think it is worth changing given that we are going to replace it with Stage 1 Guided Setup soon. If we were not going to replace it, do you have a second favorite solution?

**Comment by stitesExpensify** [comment] 2024-02-07 16:10
Cool, it looks like the detailed design already has ~1/2 of its reviews, so I'm going to close this out.

**Closed by stitesExpensify** 2024-02-07 16:10 UTC
Labels: External, Daily, Help Wanted, Bug
