### ISSUE TITLE
BUG:  Loading chat preview stuck after creating new chat while offline 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12082] opened 2022-10-23 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log into Expensify on desktop with Device A
2. On Device B, any platform, log in to another account that has never chatted with account on device A
3. Disable your internet connection on Device A. WiFi > OFF
4. On Device B, send a message to the account logged in device A
5. On Device A, navigate to LHN (mobile) or to another conversation (Desktop/Web)
6. Enable the internet connection on Device A.
7. Ensure the message you sent via Device B is received on Device A
8. Disable the internet connection on Device A
9. Click/tap on the bold chat in LHN in Device A

## Expected Result:
Chat should load despite being offline and look like a normal chat

## Actual Result:
Chat is loading, but grey loading chat screen is stuck and will not go away after going back online or refreshing app

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.18-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/197409423-e292c80c-a09c-464d-939b-11ddde625d46.mp4

<img width="524" alt="Screen Shot 2022-10-21 at 4 20 47 PM" src="https://user-images.githubusercontent.com/43996225/197409441-2e3d71ae-53e7-435e-8f9d-e73be7350985.png">

https://user-images.githubusercontent.com/43996225/197409444-043ea75f-b57e-449a-879e-c502d3feac60.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @grgia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666395031582879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chauchausoup** [comment] 2022-10-24 13:27
Problem:
Issue is caused by this prop here in InvertedFlat list. Since we are removing the Skeleton effect in compose bar too as per this issue https://github.com/Expensify/App/issues/11962 removing the prop and adding null instead might help us overcome such scenarios. 

Solution:
https://github.com/chauchausoup/App/blob/0380b71edfaf095fd90a4c1a7daa8bed640ac434/src/pages/home/report/ReportActionsList.js#L192

**Comment by Julesssss** [comment] 2022-10-25 09:44
> I'm assuming we do that and this is a bug, dishing to a engineer quick for bonus 

The report data is received when the connection resumes (including the `lastMessageText`), but the reportAction data is not, which blocks us from viewing the chat.  Perhaps this is a bug, but it's also possible we never implemented this logic. 

**report data**
<img width="996" alt="Screenshot 2022-10-25 at 10 37 16" src="https://user-images.githubusercontent.com/10736861/197740873-c3a0d839-278a-4b6f-9b94-7fd109de0d56.png">


**reportAction data**
<img width="998" alt="Screenshot 2022-10-25 at 10 38 02" src="https://user-images.githubusercontent.com/10736861/197740683-43b77a18-b464-466f-a3f3-6c6775412e50.png">

**Comment by mallenexpensify** [comment] 2022-10-25 18:44
@Julesssss , I would think, with our goal being offline-first, that we'd want to load all report data when we _can_, vs waiting for an action to be taken. Do you agree? 

If so.. I imagine this might be a much larger undertaking. Do you remember who's been working on offline details lately?

**Comment by Julesssss** [comment] 2022-10-26 09:30
Yeah, though we should be careful to retrieve only a partial set of comments (like we do elsewhere with pagination). In this case, I think we should:

1) Start sending a single reportAction comment in the same onyxUpdate data. This ensures that when tapping into a chat, the bold message is shown. 

2) Go further, and investigate how we might send additional comments to back-fill the report. 


1 seems like a perfectly reasonable solution for now, and as you said 2 is a much larger task that will require discussion

**Comment by mallenexpensify** [comment] 2022-10-26 15:01
ooooh, so... for this issue we can just have the deliverable be #1 and that'll be finite-enough for someone to fix/update this?  If so, that's great.  Now, to find someone internally to work on ;)

**Comment by Julesssss** [comment] 2022-10-28 14:14
@mallenexpensify & @kavimuru can you try reproducing this again please? I looked into the code today and this does appear to be implemented correctly. When testing on dev, I could open the chat received while offline 😕 

The screenshots are from iOS, but the same thing happened on web.

![image0](https://user-images.githubusercontent.com/10736861/198637184-1f559932-cb26-4aec-8063-bd5677776b09.png)
![image1](https://user-images.githubusercontent.com/10736861/198637232-6a85e546-f4e5-49e5-8527-5d4b80061129.png)

**Comment by mallenexpensify** [comment] 2022-10-28 14:41
I'm able to reproduce the _bug_ on Desktop v1.2.21-4
@kavimuru , wanna test web?

**Comment by kavimuru** [comment] 2022-10-28 19:31
@Julesssss @mallenexpensify  I am still able to reproduce in Web / Chrome

https://user-images.githubusercontent.com/43996225/198717539-009a1687-0e4f-4378-85f1-cc0fe575b4bd.mp4

**Comment by Julesssss** [comment] 2022-10-31 10:41
Odd, there must be some other step/config that makes this unreliably reproducible.

**Comment by Julesssss** [comment] 2022-10-31 10:41
Keeping assigned until I can retest this again.

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:46
Setting this to `Daily` as per the new process for all bugs.

To help drive this forward I just bumped the original thread where this was reported. cc @grgia Slack [thread here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667511945832099?thread_ts=1666395031.582879&cid=C01GTK53T8Q)

**Comment by mallenexpensify** [comment] 2022-11-09 02:14
Reassigning as I'm heading OOO for a month

**Comment by sophiepintoraetz** [comment] 2022-11-11 02:36
@Julesssss - am I correct in that we're waiting on steps to reliably produce the error in order to solicit proposals?

**Comment by Julesssss** [comment] 2022-11-11 10:50
@kavimuru would you mind retesting and determining whether it's occurring on all accounts or just under specific circumstances? As we're not able to reproduce. Thanks

**Comment by kavimuru** [comment] 2022-11-12 13:52
@Julesssss Now in step 6 `Enable the internet connection on Device A` message appears in normal format then after a second it becomes bold. Bug is not reproducible.

https://user-images.githubusercontent.com/43996225/201477243-46fb2327-0bba-40a3-840e-1d9852a9f97a.mp4

**Comment by Julesssss** [comment] 2022-11-14 11:51
Thank you. Let's close this out. At best it was unreliably reproducible on some devices. If and when it is reliably reproducible we can investigate further.

**Closed by Julesssss** 2022-11-14 11:51 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
