### ISSUE TITLE
[$1000] IOU - After submitting IOU report as employee, in admin account in LHN,IOU report is shown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35664] opened 2024-02-02 13:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4263802
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre: condition: In other device, login as admin
1. Go to https://staging.new.expensify.com/
2. Lon in as employee
3. Tap Employee workspace chat
4. Tap plus icon --- request money
5. Enter an amount and tap next
6. Enter merchant
7. Tap request
8. Tap newly created request to open details page
9. Tap plus icon in receipt placeholder
10. Tap camera icon and upload a picture
11. After uploading receipt, navigate to Workspace chat page
12. Tap submit button under IOU report preview
13. Now note LHN of admin account which is kept opened in other device

## Expected Result:
After submitting IOU report as employee, in admin account in LHN, the IOU report must not be shown.

## Actual Result:
After submitting IOU report as employee, in admin account in LHN, the IOU report is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7391e06c-430c-446e-aa32-77e603a2e157

https://github.com/Expensify/App/assets/93399543/9579b659-0004-4cbb-9523-a121c023fe22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018180ccb76e9e1cde</li>
        <li>Upwork Job ID: 1753415845641039872</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-02 13:53
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-02-02 19:35
hmm, maybe wave 8 as it's collect admin experience? whaddya think Z? @zanyrenney

**Comment by anmurali** [comment] 2024-02-08 16:07
No proposals yet but we will wait till EoW and then decide if we might need to take this internal

**Comment by getusha** [comment] 2024-02-12 19:56
not overdue, waiting for proposals.

**Comment by anmurali** [comment] 2024-02-16 15:26
We might need to take this internal or increase the price. But I am OOO till 29th, so rotating the label so another BZ team member can handle in my absence.

**Comment by miljakljajic** [comment] 2024-02-20 17:05
Increased the price - I'll see if anyone internal could take this

**Comment by brandonhenry** [comment] 2024-02-20 17:55
Is this accepting proposals or should this be internal tag? 👀

**Comment by Victor-Nyagudi** [comment] 2024-02-21 16:08
Please forgive my naiveness, but why do we not want to show a submitted report in the admin's LHN?

Isn't that something the admin should be notified of when it happens. 

After following the steps, the IOU appeared on the admin's LHN with the message preview there of "submitted this report to you" for me.

**Comment by miljakljajic** [comment] 2024-02-27 15:41
Asking internally

**Comment by anmurali** [comment] 2024-03-05 23:44
<img width="1459" alt="image" src="https://github.com/Expensify/App/assets/14225673/647e3d93-cde3-4aeb-93c3-ddf465a24426">

It doesn't show the report separately in LHN. It just shows GBR in the workspace chat, by design. I also tested this on Staging. So I think we can close this.

**Closed by anmurali** 2024-03-05 23:44 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
