### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] Web - Reimbursable expense - The tooltip text doesn't change to copied @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11430] opened 2022-09-29 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to staging.new.expensify.com
2. Go to settings > workspace
3. Reimburse page
4. Hover over clipboard icon
5. Tap on it

## Expected Result:
The tooltip should change to copied like it does at other places

## Actual Result:
The tooltip doesn't change

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193104516-b65d330a-4a0e-4263-8c99-16522573cb3e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663268751574339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2022-09-29 18:01
**Proposal** 
replace `text={this.props.translate('reportActionContextMenu.copyToClipboard')}` with 
`text={
                this.state.showCheckmark
                  ? this.props.translate('reportActionContextMenu.copied')
                  : this.props.translate(
                    'reportActionContextMenu.copyToClipboard',
                  )
              }` to the below code
https://github.com/Expensify/App/blob/60d933ea4fe4ad5810d6b73d97080e8e664b2f95/src/components/CopyTextToClipboard.js#L62

**Comment by muttmuure** [comment] 2022-10-03 18:10
Reproduced on my workspace. Seems like standardized behavior we want everywhere.

**Comment by arosiclair** [comment] 2022-10-04 20:34
Also reproduced on staging and also in dev. Marking external.

**Comment by jayeshmangwani** [comment] 2022-10-04 20:57
### Proposal

we need to add copied text when showCheckMark is enabled 


```diff
-<Tooltip text={this.props.translate('reportActionContextMenu.copyToClipboard')}>
+<Tooltip text={this.state.showCheckmark ? this.props.translate('reportActionContextMenu.copied'):this.props.translate('reportActionContextMenu.copyToClipboard')}>

```

**Comment by Christinadobrzyn** [comment] 2022-10-05 05:52
Eng confirmed this issue isn't a dupe of https://github.com/Expensify/App/issues/9233 so creating a new job in Upwork. 

Internal job posting: https://www.upwork.com/ab/applicants/1577536989593255936/job-details
External job posting: https://www.upwork.com/jobs/~01fdadeeba74809569

**Comment by eVoloshchak** [comment] 2022-10-06 06:53
@jayeshmangwani, your [proposal](https://github.com/Expensify/App/issues/11430#issuecomment-1267570864) is identical to @gadhiyamanan's [proposal](https://github.com/Expensify/App/issues/11430#issuecomment-1262626809)

**Comment by eVoloshchak** [comment] 2022-10-06 06:54
@gadhiyamanan's [proposal](https://github.com/Expensify/App/issues/11430#issuecomment-1262626809) looks great and works as expected

cc: @Gonals 
🎀👀🎀 C+ reviewed!

**Comment by Gonals** [comment] 2022-10-06 08:41
@gadhiyamanan's proposal looks good to me! Assigning you to the issue. Feel free to go ahead and create a PR

**Comment by gadhiyamanan** [comment] 2022-10-06 09:16
@eVoloshchak  [PR](https://github.com/Expensify/App/pull/11626) raised

**Comment by Christinadobrzyn** [comment] 2022-10-07 06:47
Hired @gadhiyamanan for the fix, @eVoloshchak as C+, and @Puneet-here as the reporter

**Comment by Christinadobrzyn** [comment] 2022-10-21 07:09
Paid! 

$250 @gadhiyamanan for the fix
$250 @eVoloshchak as C+
$250 @Puneet-here as the reporter

Closed the job in Upwork and closing this GH.

**Closed by Christinadobrzyn** 2022-10-21 07:09 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
