### ISSUE TITLE
[HOLD for payment 2024-06-06] CRITICAL: [Actionable Whisper] [$250] After selection an option for a tracked expense, the LHN still shows 'What would you like to do with this expense?'

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#41183] opened 2024-04-28 22:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Track an expense
2. Select any of the actionable whisper options
3. One done, the actionable whisper and the tracked expense should no longer be in the self-DM

## Expected Result:
Describe what you think should've happened
The LHN should no longer show 'What would you like to do with this expense?', and instead whatever occurred last in the self-DM

## Actual Result:
Describe what actually happened
The LHN still shows 'What would you like to do with this expense?'

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Start a chat with the user first, before performing the steps

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/30609178/c59cec39-3230-45af-8c65-d97bb9ae87d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b488eb6e01215bbc</li>
        <li>Upwork Job ID: 1784717953358557184</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by thienlnam** [comment] 2024-04-28 22:55
This is likely an internal / external issue.

When we dismiss the actionable whisper, the BE should send an updated lastMessageText to the client. Additionally, there should be an optimistic update on the FE when this happens as well. When the "Dismiss for now" option is selected, it seems to work properly

**Comment by joekaufmanexpensify** [comment] 2024-04-29 14:01
@thienlnam if this is an internal / external, should I mark it as such so we get proposals for the external piece?

**Comment by joekaufmanexpensify** [comment] 2024-04-30 14:26
pending further discussion

**Comment by thienlnam** [comment] 2024-04-30 17:46
Let me double check to confirm my theory first, but yeah we can after that

**Comment by thienlnam** [comment] 2024-04-30 17:48
Yup, looks like this is correct - we'll need to do something optimistically and on the BE as well

**Comment by joekaufmanexpensify** [comment] 2024-05-01 14:34
Awaiting proposals

**Comment by joekaufmanexpensify** [comment] 2024-05-02 13:12
[Bumped in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1714655567913879) for proposals

**Comment by Nodebrute** [comment] 2024-05-02 14:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After selection an option for a tracked expense, the LHN still shows 'What would you like to do with this expense?
### What is the root cause of that problem?
Here last reportLastMessageText will be What would you like to do with this expense?
https://github.com/Expensify/App/blob/f851f575ef433c0a87cac2c6cf20951483887566/src/libs/actions/IOU.ts#L1478-L1479
### What changes do you think we should make in order to solve the problem?

Here we are hiding these actions we should also add `!isActionableTrackExpense(reportAction)`
https://github.com/Expensify/App/blob/f851f575ef433c0a87cac2c6cf20951483887566/src/libs/ReportActionsUtils.ts#L556-L572
### What alternative solutions did you explore? (Optional)

**Comment by quinthar** [comment] 2024-05-02 23:44
What's the next step here, and who is doing it?  When?

**Comment by c3024** [comment] 2024-05-03 03:58
We have the whisper in the sortedVisibleReportActions even after resolution but it is not displayed as a report action in the report screen because of this here
https://github.com/Expensify/App/blob/ee8f9c661f269f405a5ae8ba47ea07f42a306c6c/src/pages/home/report/ReportActionItem.tsx#L903-L905
so we should use the same logic for displaying in LHN as well.

So the [alternative solution here](https://github.com/Expensify/App/issues/41183#issuecomment-2090617822) by @Nodebrute looks good to me. 

🎀 👀 🎀 C+ Reviewed

**Comment by quinthar** [comment] 2024-05-04 01:11
Great!  @Nodebrute what is your ETA?

**Comment by Nodebrute** [comment] 2024-05-04 04:53
@quinthar I'll raise a PR today.

**Comment by Nodebrute** [comment] 2024-05-06 02:03
I am working on the PR currently testing all cases.

**Comment by joekaufmanexpensify** [comment] 2024-05-13 14:18
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-05-20 14:24
@Nodebrute I see there are several bumps for you on the PR. Can you address those asap?

**Comment by joekaufmanexpensify** [comment] 2024-05-28 14:28
PR still in review

**Comment by joekaufmanexpensify** [comment] 2024-06-03 13:50
@c3024 please handle BZ so we can issue payment this week

**Comment by c3024** [comment] 2024-06-04 13:09
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: No particular PR can be held responsible for this. This bug appears due to introduction of the new feature `Track Expense`. And these whispers as report actions work differently.
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this bug cannot be identified in prior.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.


### Regression Test Proposal
1. Track an expense
2. Select any of the actionable whisper options on the whisper received
3. Confirm that the LHN of self DM displays the last visible message of the report instead of `What would you like to do with this expense?` (This might change back to `What would you like to do with this expense?` after refreshing. That is a separate internal issue and is being fixed here #42727)

**Comment by c3024** [comment] 2024-06-06 13:39
@joekaufmanexpensify This is marked as a `CRITICAL` issue. Is $500 pay applicable for this issue similar to [this](https://github.com/Expensify/App/issues/40156#issuecomment-2151778964)?

**Comment by joekaufmanexpensify** [comment] 2024-06-06 21:44
[Checking ](https://expensify.slack.com/archives/C01SKUP7QR0/p1717710250363219)

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:23
Confirmed payment is $250 here, since the `high priority` was not added by the project leader here. There has been some confusion on this, but it was [clarified in Slack several days ago](https://expensify.slack.com/archives/C01GTK53T8Q/p1717451725980889?thread_ts=1712256409.152489&cid=C01GTK53T8Q) that the intent of the price doubling is to be specifically when  a project leader adds this label to the issue, not based on the status of the issue in the linked GH project.

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:30
All set to issue payment. We need to pay: 

- @Nodebrute $250 for PR via Upwork
- @c3024 $250 for C+ via Upwork

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:32
@Nodebrute $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:32
@c3024 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:33
All set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-06-07 14:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
