### ISSUE TITLE
[$500]  iOS - IOU - When adding a member to a group, a keyboard appears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33909] opened 2024-01-03 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in to your HT account
3. Tap on FAB
4. Tap on "Start chat"
5. Select a any user by clicking on "Add to group"
6. Close the keyboard by defocusing the input
7. Select a any user by clicking on "Add to group"

## Expected Result:
If the user has closed the keyboard and is adding members to a group, the keyboard should not appear until the user moves the focus to the search field

## Actual Result:
When adding a member to a group, a keyboard appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8863da7a-8871-4906-8457-35185f6eea33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e098dbcbebccaa99</li>
        <li>Upwork Job ID: 1742653519416479744</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by aim-salam** [comment] 2024-01-03 21:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

iOS - IOU - When adding a member to a group, a keyboard appears

### What is the root cause of that problem?

When add to selection, `textInput.focus()` triggered

### What changes do you think we should make in order to solve the problem?

remove `textInput.focus()` on `addToSelection(option)`



### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2024-01-10 09:38
@alitoshmatov what do you think of the above proposals?

**Comment by alitoshmatov** [comment] 2024-01-11 15:55
Sorry for a late response. 

I am having some trouble reproducing this issue. Can anyone confirm that this issue is still reproducible or am I missing some steps?

cc: @sonialiap

**Comment by kbecciv** [comment] 2024-01-12 22:33
Issue is not reproduced any more

https://github.com/Expensify/App/assets/93399543/b4299b3d-c8cd-45ec-b831-69cec86545a2

**Comment by situchan** [comment] 2024-01-13 00:52
There's nothing to fix here. We can close this.


FYI: `shouldPreventDefaultFocusOnSelectRow` means whether to prevent default focus on menu item, not on search bar so the prop name is accurate.

**Closed** 2024-01-18 13:04 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
