### ISSUE TITLE
[HOLD for payment 2024-12-05] [$50] Update copy on the wallet settings page

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#52789] opened 2024-11-19 17:55 UTC
# Problem
When users find it difficult to navigate our application's features due to interface clutter, it leads to decreased engagement and lower conversion and retention rates.

# Solution
Clean up some of the copy on the wallet settings page:

1. Change the title of the block from "Send and receive money with friends" to "Expensify Wallet"
2. Change the subtitle from "Your wallet has been enabled to send and receive money with friends." to "Send and receive money with friends."

![image](https://github.com/user-attachments/assets/7130fdcf-062e-4e76-b5a8-edc46ea6ef06)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859017641475961132</li>
        <li>Upwork Job ID: 1859017641475961132</li>
        <li>Last Price Increase: 2024-11-19</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 105008734</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by nkdengineer** [comment] 2024-11-19 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update copy on the wallet settings page

### What is the root cause of that problem?
This is an improvment
### What changes do you think we should make in order to solve the problem?
Change this translation to `Expense Wallet` and 

https://github.com/Expensify/App/blob/763215e0aa0ac256f5f129e7f62444a466e84e8f/src/languages/en.ts#L1410?

This to `Send and receive money with friends.`
https://github.com/Expensify/App/blob/763215e0aa0ac256f5f129e7f62444a466e84e8f/src/languages/en.ts#L1412

We also need to update the es.ts file
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-11-19 23:12
@tgolen did you want to send this external? If so, I think we reduce the price quite considerably to say $50 for a small copy change.

**Comment by tgolen** [comment] 2024-11-19 23:33
I think a reduced price makes a lot of sense!

**Comment by trjExpensify** [comment] 2024-11-19 23:35
> https://www.upwork.com/jobs/~021859017641475961132

Done!

**Comment by hungdannt** [comment] 2024-11-20 05:21
Hi, I'm Dan, a new contributor from Upwork - and I would like to work on this issue.
Thanks

**Comment by hunghinh2000** [comment] 2024-11-20 09:32
Contributor details
Your Expensify account email: hunghinh2000vn@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a2a6c6ca80bc50fa

**Comment by hunghinh2000** [comment] 2024-11-20 09:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users find it difficult to navigate the wallet settings page due to cluttered interface copy.
### What is the root cause of that problem?
The current wallet section title and subtitle are overly verbose and redundant.
### What changes do you think we should make in order to solve the problem?
Update translations in `src/languages/en.ts`:
```js
walletPage: {
    sendAndReceiveMoney: 'Expensify Wallet', // Changed from "Send and receive money with friends"
    walletEnabledToSendAndReceiveMoney: 'Send and receive money with friends', // Changed from "Your wallet has been enabled to send and receive money with friends"
}
```
### What alternative solutions did you explore? (Optional)

**Comment by prakashbask** [comment] 2024-11-20 14:50
# Proposal 

### Please re-state the problem that we are trying to solve in this issue.
Clean up some of the copy on the wallet settings page:

### What is the root cause of that problem?
UX improvement suggestion to reduce interface clutter and improve customer engagement and retention

### What changes do you think we should make in order to solve the problem?
1) To change the title of the block from "Send and receive money with friends" to "Expensify Wallet",  change title to use 
`title={translate('walletPage.expensifyWallet')}`. walletPage.expensifyWallet is already defined in the language translation files. The change will be done at
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L402
2) To change the subtitle from "Your wallet has been enabled to send and receive money with friends." to "Send and receive money with friends.", change subtitle to use `subtitle={translate('walletPage.sendAndReceiveMoney'')}`. The conditional check of hasActivatedWallet to display text will be removed at the following location
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L401
3) Remove all language translations for enableWalletToSendAndReceiveMoney and walletEnabledToSendAndReceiveMoney at
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/languages/en.ts#L1411
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/languages/en.ts#L1412
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/languages/es.ts#L1412
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/languages/es.ts#L1413

End Result is 
![Screenshot 2024-11-20 at 8 01 24 PM](https://github.com/user-attachments/assets/4c2eaf7e-a24d-4b94-90f3-f6283001e7f0)


### What alternative solutions did you explore? (Optional)
The current solution assumes that the title and subtitle for Wallet section remains the same in both activated and non-activated condition.
If we need to display different title and subtitle based on activated/non-activated check then following changes will be required
``subtitle={translate(`walletPage.${hasActivatedWallet ? 'sendAndReceiveMoney' : 'enableWalletToSendAndReceiveMoney'}`)}``
``title={translate(`walletPage.${hasActivatedWallet ? 'expensifyWallet' : 'sendAndReceiveMoney'}`)}
``

**Comment by trjExpensify** [comment] 2024-11-20 21:56
Hm, I don't like changing the title personally. I would think we just have this in both pre/post-enablement states? 

**Expensify Wallet**
Send and receive money with friends.

**Comment by prakashbask** [comment] 2024-11-21 18:13
I have applied to the job on Upwork and target to have the PR ready by 22-Nov

**Comment by prakashbask** [comment] 2024-11-22 05:17
PR #52942

**Comment by trjExpensify** [comment] 2024-12-05 13:06
Agreed, small copy update. 

Payment summary as follows: 

- $50 to @rayane-djouah for the C+ review (paid!) 
- $50 to @prakashbask for the fix (offer sent!)

**Comment by trjExpensify** [comment] 2024-12-05 13:08
Paid @prakashbask, closing!

**Closed by trjExpensify** 2024-12-05 13:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
