### ISSUE TITLE
[$1000] IOU - Attempting to pay for a remote IOU results in an error and remains in the chat history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23989] opened 2023-08-01 10:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions:
From user B, make a request for money to user A
1. Open https://staging.new.expensify.com/
2. Log in as user A
3. Enter the chat room with user B
4. Disconnect the internet on user A's device.
5. On the device with user B, delete the money request for user A
6. Click Pay Money Request (from User B) on User A's device.
7. Turn on the Internet on user A's device
8. Refresh the chat page with user B
9. Click on the "Pay" button that appears again

## Expected Result:
When user A deletes an IOU, user B should get a payment error(warning) when attempting to make a payment and the payment should not be made

## Actual Result:
When user A is offline and clicks pay for an IOU, and user B online deletes that IOU, then when user A connects to the internet, the IOU remains in user A's history until the user logs in again

On mWeb similar behavior, on PROD it also writes the error "Hmm.... it's not here", but the "Pay" button doesn't appear anymore. On Android the application crashes, but on Desktop the payment is forced and the user who deleted the payment receives a notification about the payment and the message "Unexpected error deleting the money request, please try again later", or Desktop behaves like Web, I haven't found a pattern

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ee23409a-8775-440d-8b06-98fc09e17e43

https://github.com/Expensify/App/assets/78819774/f326dcd9-dab4-4516-bd6c-d24630863eff

https://github.com/Expensify/App/assets/78819774/116a9f9a-af75-4b79-a5e1-110d5d38af79

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f39271ef156afeb6</li>
        <li>Upwork Job ID: 1686354273499406336</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-08-01 14:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

If user pays the IOU request in offline mode when the IOU was already deleted by other user and switches to onine, it still shows pay button unless the user sign in again

### What is the root cause of that problem?

In this case, `PayMoneyRequest` API is called for an already deleted IOU request. API call fails and the IOU preview action is updated with the below data
https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/libs/actions/IOU.js#L1324-L1332

As you can see, there is no error indicator. This is one reason of the issue

If user B deletes his requests, user A receives the event that notifies the request was deleted. This works fine when both users are online, but if user A switches to offline and to online again, he wasn't able to receives the event. This is another reason of the issue(maybe this is impossible to avoid?)

In contrast to general messages, IOU requests are removed instead of being marked as `deleted`. So if user A didn't receive the events, user A can't know if the request was deleted because onyx merge is returned from the `OpenReport` API call. This is another reason

### What changes do you think we should make in order to solve the problem?

1. We have to fill the failureData of the `PayMoneyRequest` API call with error, not `created` in the above code snippet.
2. We need to change the backend logic to handle IOU requests. We should not remove them, should mark them as deleted when delete IOU request. This should be applied to events for deleting IOU.

This issue looks like backend issue mostly with a small change in frontend.

### What alternative solutions did you explore? (Optional)

**Comment by grafaleg** [comment] 2023-08-01 19:35
Contributor details
Your Expensify account email: rafaelagg21@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018dd0024204076c3c

**Comment by jaylalakiya** [comment] 2023-08-02 09:23
Contributor details
Your Expensify account email: lalakiyajay18122001@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018ce7a315741412dc

**Comment by laurenreidexpensify** [comment] 2023-08-02 12:58
@Beamanator @mountiny @puneetlath can you take a look over @Ollyws's Q above? Thanks

**Comment by puneetlath** [comment] 2023-08-03 21:41
I think this would be addressed by the `GetMissingOnyxUpdates` changes we are making. But I guess if you are far enough out of date, the problem would still exist. So yes, I agree, this is a back-end issue.

**Comment by mountiny** [comment] 2023-08-06 18:41
@luacmartins I think this should be added to the DeleteMoneyRequest clean ups

**Comment by luacmartins** [comment] 2023-08-08 18:31
Yea, this should be internal. I can work on it.

**Comment by luacmartins** [comment] 2023-08-09 20:38
Prioritizing critical w4 issues. I'll get to this later in the week.

**Comment by luacmartins** [comment] 2023-08-14 14:46
Working on this issue this week.

**Comment by laurenreidexpensify** [comment] 2023-08-18 12:39
@luacmartins is there a draft PR yet?

**Comment by mountiny** [comment] 2023-08-18 19:08
🎉

**Closed by mountiny** 2023-08-18 19:08 UTC
Labels: Daily, Internal, Bug
