### ISSUE TITLE
[$500] LHN-Paid and 1:1 report missing in LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30427] opened 2023-10-26 11:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report eg:user B
3. Tap plus icon to select Request money
4. Enter an amount
5. Request money
6. Navigate back to LHN - Note 1:1 and IOU report in LHN
7. Open User B account and note only IOU report is displayed in LHN
8. Open the bold IOU report in LHN and pay elsewhere
9. When user B pay elsewhere, note the 1:1report in user A LHN disappears.
10.  When user B pay elsewhere and navigate to LHN, now both 1:1 and IOU report displayed but no paid transaction report shown
11. As user A, tap on IOU report and note request amount paid.
12. Navigate back to LHN and note the reports displayed

## Expected Result:
When a IOU is created, both 1:1 and IOU report must be displayed for user A and user B and after pay elsewhere, paid IOU report must be displayed in LHN for both users

## Actual Result:
For user A, the 1:1 report disappeared in LHN when user B pay elsewhere and paid IOU report not displayed in LHN.

For user B, after user A request money only IOU displayed in LHN and only after pay elsewhere and revisiting LHN 1:1 report is shown but paid IOU report not shown in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/cd65377d-ef45-4989-b662-3bb167976b19

https://github.com/Expensify/App/assets/115492554/2b45813a-2f74-4279-9a5c-36082ca812e4

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018dfeb9cdb5e3ad75</li>
        <li>Upwork Job ID: 1717503331739455488</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-26 12:04
There is an issue in the data coming from Pusher on the RequestMoney API call:

```json
{
    "onyxMethod": "merge",
    "key": "report_1776447671437860",
    "value": {
        "iouReportID": "6625022465297579",
        "participantAccountIDs": {
            "1": 15945552
        }
    }
}
```

It returns the `participantAccountIDs` as an object, while it is supposed to be an array:
```json
{
  "onyxMethod": "merge",
  "key": "report_1776447671437860",
  "value": {
    "iouReportID": "6625022465297579",
    "participantAccountIDs": [
      15945556
    ]
  }
}
```

**Comment by jliexpensify** [comment] 2023-10-27 05:07
Hi @paultsimura (not an engineer) are you saying this should be handled from the back-end?

**Comment by paultsimura** [comment] 2023-10-27 08:14
> Hi @paultsimura (not an engineer) are you saying this should be handled from the back-end?

@jliexpensify  I think so, yes. The Pusher now behaves weirdly with these requests.
Somehow, the "Request Money" flow got resolved for me, but the "Pay elsewhere" by user B still removes the 1:1 chat for user A.

These are the updates this user receives from Pusher:

```json
{
    "onyxMethod": "merge",
    "key": "report_6248612838888226",
    "value": {
        "iouReportID": null,
        "participantAccountIDs": []
    }
}
```

The `participantAccountIDs` is set to an empty array, so this report disappears from LHN because of this check:

https://github.com/Expensify/App/blob/6c2e08741475635713b71aa2ba47c2cc6e354d9e/src/libs/ReportUtils.js#L3258-L3276

**Comment by mananjadhav** [comment] 2023-10-27 18:41
I couldn't reproduce this on Mac Chrome. @jliexpensify Are you able to reproduce this?

**Comment by paultsimura** [comment] 2023-10-27 22:12
Just reproduced on latest `main`:

https://github.com/Expensify/App/assets/12595293/3f32e275-8dca-4c3f-ba62-e9b75ff6bad0

@mananjadhav

**Comment by jliexpensify** [comment] 2023-10-30 04:29
Hmm I can't repro on Staging v1.3.92-4: when I click on `Pay Elsewhere` everything seems to work as intended?
![image](https://github.com/Expensify/App/assets/30815269/fcc30a5c-97c3-44ad-bde1-9322927df922)

@izarutskaya can you repro on the newest version of Staging?

**Comment by jliexpensify** [comment] 2023-11-02 06:05
Bumo @izarutskaya !

**Comment by izarutskaya** [comment] 2023-11-02 11:25
Hi @jliexpensify, I cannot reproduce this on Web/mWeb. Build - v1.3.95-0

https://github.com/Expensify/App/assets/115492554/c66e0783-808c-4e14-a446-ba4bb76b14f1

**Comment by jliexpensify** [comment] 2023-11-03 02:02
Great, thanks! Lets close this one out.

**Closed by jliexpensify** 2023-11-03 02:02 UTC
Labels: External, Daily, Help Wanted, Bug
