### ISSUE TITLE
[$500] IOU - Request money cannot be completely deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27584] opened 2023-09-16 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Select an available chat
2. Click on the plus sign -> Request money -> type any number --> Next button
3. Reply in this Money Request thread
4. Delete this Request money and all responses, and observe the conversation

## Expected Result:
Request money will not display once deleted

## Actual Result:
Even though the Request money and its reply have been deleted, instead of disappearing, it is still displayed with the value 0

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[1.webm](https://github.com/Expensify/App/assets/78819774/d0d2a2f7-105b-44b8-999f-f7a06acbb438)

https://github.com/Expensify/App/assets/78819774/bd70e577-9a25-4b36-aaf8-852777987185

**Expensify/Expensify Issue URL:**

**Issue reported by:** @thuyle04

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694596117096459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ffc96c4935a830f</li>
        <li>Upwork Job ID: 1703096201040531456</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-09-17 16:59
Dupe of #25930

**Comment by maddylewis** [comment] 2023-09-18 18:05
this is a dupe

**Closed by maddylewis** 2023-09-18 18:05 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by rojiphil** [comment] 2023-11-06 05:01
> why do you say it's dupe?

@aimane-chnaif 
As I understand, this issue comes up when the money request is deleted first and, then, the normal comments are deleted in the IOU Report. 
This is the exact case we ended up handling in #25930 and we are awaiting an BE PR by the internal team member.
The title in #25930 may be misleading as the discussions finally reached towards handling the case mentioned here.
That is why I think this is a dupe. 
Or am I missing something here?

**Comment by rojiphil** [comment] 2023-11-06 06:20
> Always happens when delete money request even without any comment.

@aimane-chnaif 
Maybe then the description of this issue can be changed to reflect the disconnection with #25930.
Also, instead, let us put this issue on hold against #30219 as I think the decision on this will depend on the outcome of the discussion there.

**Comment by rojiphil** [comment] 2023-11-08 03:27
@aimane-chnaif 
Based on the [slack discussion here](https://expensify.slack.com/archives/C01GTK53T8Q/p1699251346849569), looks like we can keep this issue closed. What do you think?

**Comment by rojiphil** [comment] 2023-11-08 05:36
> @rojiphil based on https://expensify.slack.com/archives/C01GTK53T8Q/p1699286214017489?thread_ts=1699251346.849569&cid=C01GTK53T8Q, this is bug.

@aimane-chnaif 
Agreed. And, that is exactly what is getting fixed in #25930. 
Please also refer to my earlier [comment here](https://github.com/Expensify/App/issues/27584#issuecomment-1794089889).
Shouldn't we consider this issue as a dupe then?
