### ISSUE TITLE
[HOLD #13623] New Room - A red dot appears with an error when selecting a new room and then canceling

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13847] opened 2022-12-28 00:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Click menu Fab
4. Click New room
5. Click cancellation of new room creation

## Expected Result:
The error with the red dot should not appear when selecting a new room and then canceling

## Actual Result:
A red dot appears with an error when selecting a new room and then canceling

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209738189-27258b76-fc50-4d8a-bce5-32f91b680dd4.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause_- Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f71f0d04a9efdcc</li>
        <li>Upwork Job ID: 1608151229178265600</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2022-12-28 17:21
I'm able to reproduce this on iOS, but not on Chrome.

**Comment by thesahindia** [comment] 2022-12-28 17:26
@puneetlath, I think the root cause is same as https://github.com/Expensify/App/issues/13024 and we should add this to the tracking [issue](https://github.com/Expensify/App/issues/13623)

**Comment by puneetlath** [comment] 2022-12-31 00:12
Sounds good. Thanks @thesahindia.

**Comment by puneetlath** [comment] 2023-01-09 19:57
Still on hold.

**Comment by puneetlath** [comment] 2023-01-18 18:55
Still on hold.

**Comment by puneetlath** [comment] 2023-01-30 22:23
Still on hold.

**Comment by puneetlath** [comment] 2023-02-08 21:53
Still on hold. Posted an idea in https://github.com/Expensify/App/issues/13623 to try to keep the convo going.

**Comment by puneetlath** [comment] 2023-02-15 18:35
Closing this in favor of https://github.com/Expensify/App/issues/13623 since it'll be handled there.

**Closed by puneetlath** 2023-02-15 18:35 UTC
Labels: Weekly, Bug
