### ISSUE TITLE
Members - Back button on Members opens Members page after returning from member profile

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37941] opened 2024-03-08 00:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** no (clicking on a member in the list is a new feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is owner of Collect workspace.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Collect workspace.
3. Go to Member.
4. Click on any member.
5. Click back button on the top left.
6. Click back button on the top left again.
## Expected Result:
App will return to workspace settings.

## Actual Result:
App opens Members page again.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/a3d40083-3baa-40fb-9419-6db65b6461fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2024-03-08 00:48
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Tony-MK** [comment] 2024-03-08 01:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members - Back button on Members opens Members page after returning from member profile

### What is the root cause of that problem?

We use the `backTo` parameter if the member is not an admin and the policy is not free.

https://github.com/Expensify/App/blob/f550e841ee5404016d7201f9f5b7a5bec71a410f/src/pages/workspace/WorkspaceMembersPage.tsx#L269

### What changes do you think we should make in order to solve the problem?

Remove the `backTo` parameter.

Change the above code to the one below.

```
Navigation.navigate(ROUTES.WORKSPACE_MEMBER_DETAILS.getRoute(route.params.policyID, item.accountID));
```

Just like if the member is not a policy admin over [here](
https://github.com/Expensify/App/blob/f550e841ee5404016d7201f9f5b7a5bec71a410f/src/pages/workspace/WorkspaceMembersPage.tsx#L261).

**Comment by luacmartins** [comment] 2024-03-08 02:44
cc @burczu let's fix this along with https://github.com/Expensify/App/issues/37927

**Comment by roryabraham** [comment] 2024-03-08 17:54
> Precondition: User is owner of Collect workspace [in newdot]

AKA, NAB for now

**Comment by roryabraham** [comment] 2024-03-10 19:04
@luacmartins @burczu can you please confirm if this issue should be on HOLD, and if so, for what? Is this the correct link? https://github.com/Expensify/App/issues/37927

**Comment by luacmartins** [comment] 2024-03-11 17:45
We can close this one in favor of https://github.com/Expensify/App/issues/37927

**Closed by luacmartins** 2024-03-11 17:45 UTC
Labels: Engineering, Daily, Bug
