### ISSUE TITLE
Web - Room - First created Workspace is automatically selected when create Room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34544] opened 2024-01-15 22:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User have multiple Workspaces
1. Navigate to staging.new.expensify.com
2. Go to Start chat> Room

## Expected Result:
User should choose workspace where room should be created

## Actual Result:
First created Workspace is automatically selected when create Room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d95af01b-d47c-4089-9695-c311e959e8c7

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2024-01-15 23:06
Also can't reproduce on staging v1.4.25-4, it might have been fixed by something else since v1.4.25-1.


https://github.com/Expensify/App/assets/2229301/56915eb0-75ee-4255-8257-353ec797ec5a

**Comment by mountiny** [comment] 2024-01-16 00:32
This just seems weird, going to close this one

**Closed by mountiny** 2024-01-16 00:32 UTC
Labels: Engineering, Daily
