### ISSUE TITLE
[HOLD] Web -  Wrong URL when Paypal.me payments page is closed @aneequeahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10991] opened 2022-09-14 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3.  Open settings page > Workspace > Manage members
4.  Select Invite member and close the page
5. Open settings page > payments > Add payment method > Paypal
6. Close the page

## Expected Result:
Url should be r/reportId

## Actual Result:
Url is /settings/payments

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.0.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190194780-ef815573-4d3b-46ab-a735-adb1f8753c5f.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661466607294799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2022-09-19 14:36
I was able to reproduce the first part where the wrong URL appeared after closing the Invite member page. I was not able to reproduce the issue with the Paypal page. As mentioned above it looks like there might be similar issues with different pages https://github.com/Expensify/App/issues/10939#issuecomment-1247831362.

**Comment by MonilBhavsar** [comment] 2022-09-20 05:27
I'm able to reproduce the issue, but looks like a duplicate issue. @parasharrajat could you please confirm. Thank you!

**Comment by MonilBhavsar** [comment] 2022-09-22 05:23
Thank you! Then I think we can close this issue and keep only one tracking issue open

**Comment by JmillsExpensify** [comment] 2022-09-26 14:02
Going to close this issue in favor of https://github.com/Expensify/App/issues/10939, which @parasharrajat has highlighted as having the same root cause.

**Comment by JmillsExpensify** [comment] 2022-09-26 18:12
Sorry, what does "add this to $11111" mean?

**Comment by JmillsExpensify** [comment] 2022-09-26 18:18
Ok cool, same page. One concern though is that we need to keep track of the bug reporter. It looks like we're fine for the time being, in that I can add @aneequeahmad to the master issue since now reporter is currently listed there.

**Comment by JmillsExpensify** [comment] 2023-06-26 20:34
Here's my summary after running through the linked reproduction steps:

 - We've deprecated the close button, so that's not longer a relevant part of the testing steps
 - Further, when I navigate through the Workspace and Payments, the URL is correct each time. 

Accordingly, I think we're good to go here and we'll pay out @aneequeahmad $250 for reporting.

**Comment by MonilBhavsar** [comment] 2023-06-30 07:10
@JmillsExpensify agree!
Issue is not reproducible currently, but It was at that moment, so fair to pay reporting bonus

**Comment by aneequeahmad** [comment] 2023-06-30 14:11
@MonilBhavsar  I agree, this is not reproducible in production but it was reproducible at that moment. So it is fixed in production

**Comment by MonilBhavsar** [comment] 2023-07-03 13:13
Waiting for payment here

**Comment by MonilBhavsar** [comment] 2023-07-06 12:10
@JmillsExpensify let's extend the contract and close this issue?

**Comment by MonilBhavsar** [comment] 2023-07-11 09:38
Waiting for payment here

**Comment by aneequeahmad** [comment] 2023-07-21 22:54
@JmillsExpensify any update here on the payment ?

**Comment by MonilBhavsar** [comment] 2023-07-24 13:44
DM'ed Jason

**Comment by JmillsExpensify** [comment] 2023-07-24 21:43
We're working on these in bulk, as part of the react navigation project. I'll issue payment just as soon as I'm able to re-test and confirm all remaining issues are fixed. Thanks for your patience until then.

**Comment by MonilBhavsar** [comment] 2023-07-25 06:17
Thank you! I think it is fair to bump to this to weekly then

**Comment by JmillsExpensify** [comment] 2023-08-02 20:52
Still working on the testing issues.

**Comment by JmillsExpensify** [comment] 2023-08-30 05:42
Same

**Comment by MonilBhavsar** [comment] 2023-09-12 09:56
Still on hold

**Comment by JmillsExpensify** [comment] 2023-09-25 22:23
We're deprecating Paypal, so I'm going to issue payment for reporting and then we can close this issue.

**Comment by JmillsExpensify** [comment] 2023-09-25 22:26
@aneequeahmad I send you a report offer for this Upwork job: https://www.upwork.com/jobs/~01832a474eb99777e9. Let me know when you've accepted.

**Comment by aneequeahmad** [comment] 2023-09-26 03:24
@JmillsExpensify i have accepted the offer. Thank you for inviting

**Comment by aneequeahmad** [comment] 2023-09-27 23:29
@JmillsExpensify any update on this issue ? Lets close this one. 
Also, what about other navigation issues that i reported ? Should i test them all ? If they are reproducible or not

**Comment by MonilBhavsar** [comment] 2023-10-04 14:49
We're closing this issue as Paypal is being deprecated. Which other issue is being referred here?

**Comment by aneequeahmad** [comment] 2023-10-04 23:02
@MonilBhavsar im talking about other navigation issues that are listed in navigation project.

**Comment by aneequeahmad** [comment] 2023-10-07 08:00
@JmillsExpensify i accepted the offer its been 2 weeks. Please accept it and lets close this offer. Thanks

**Comment by JmillsExpensify** [comment] 2023-10-07 20:49
> @JmillsExpensify any update on this issue ? Lets close this one. Also, what about other navigation issues that i reported ? Should i test them all ? If they are reproducible or not

Yes please test them all and confirm if they are still reproducible or not.

**Comment by JmillsExpensify** [comment] 2023-10-07 20:50
> @JmillsExpensify i accepted the offer its been 2 weeks. Please accept it and lets close this offer. Thanks

Paid out.

**Closed by JmillsExpensify** 2023-10-07 20:50 UTC
Labels: Engineering, Weekly, Awaiting Payment
