### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] email is not shown in authenticator app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19366] opened 2023-05-22 01:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go Settings > Security >Two-factor authentication
2. clear step1 and go to step 2
3. scan QR code in authenticator app

## Expected Result: 
should show email in bracket(same as old dot) to identify account
## Actual Result: 
empty bracket shoes [Expensify()] . does not show email in authenticator app

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/94a29e8f-994b-42e0-84a6-21d44863ee55" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/a5bca34b-c8d8-4557-b1ad-560e7fc6db36" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684392781249369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5aa1ce9a00e8423</li>
        <li>Upwork Job ID: 1673302724686958592</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26858432</li>
<li>hungvu193 | Contributor | 26858435</li>
<li>gadhiyamanan | Reporter | 26858438</li>
</ul></li>
    </ul>
</details>

**Comment by tienifr** [comment] 2023-05-22 02:46
I cannot reproduce this. It's showing the email as expected (both on staging and the code's newest version)

**Comment by hungvu193** [comment] 2023-05-22 02:49
I also couldn't reproduce, worked as expected on latest main.

**Comment by gadhiyamanan** [comment] 2023-05-22 03:26
it’s reproducible only one time when user create new account. after logout and again login it’s working fine

**Comment by hungvu193** [comment] 2023-05-22 03:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Email is not shown in authenticator app
### What is the root cause of that problem?
With new account, after first login, the `primaryLogin` somehow is empty which causes this issue.
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js#L81-L83
### What changes do you think we should make in order to solve the problem?

We can use `session login` as a backup value for `primaryLogin` email.

```javascript
    function buildAuthenticatorUrl() {

        return `otpauth://totp/Expensify:${props.account.primaryLogin || props.session.email}?secret=${props.account.twoFactorAuthSecretKey}&issuer=Expensify`;
    }
```

### What alternative solutions did you explore? (Optional)
This issue can be fixed from backend.

**Comment by arielgreen** [comment] 2023-05-22 22:29
@kavimuru @gadhiyamanan I don't understand the reproduction steps. What does "clear step 1" mean? Applause, were you able to reproduce?

Closing until reproducible steps are added.

**Comment by gadhiyamanan** [comment] 2023-05-23 14:14
Please try these steps:

1. create a new account
2. Go to Settings > Security >Two-factor authentication
3. click on copy codes or download option
4. click on the Next Button
5. scan the QR code in the authenticator app

cc: @arielgreen

**Comment by gadhiyamanan** [comment] 2023-05-29 06:09
bump @arielgreen ^^

**Comment by gadhiyamanan** [comment] 2023-06-09 02:29
Bump @arielgreen ^^

**Comment by kbecciv** [comment] 2023-06-20 17:06
Issue is reproducible here https://expensify.slack.com/archives/C049HHMV9SM/p1686745548252899, reopening!

**Comment by arielgreen** [comment] 2023-06-21 00:25
reassigning, team change

**Comment by CortneyOfstad** [comment] 2023-06-22 11:56
So I'm having a heck of a time getting this to reproduce. Has anyone else had luck reproducing within the last 8 days?

**Comment by BeeMargarida** [comment] 2023-06-23 12:27
Yap, I could reproduce today running on the main branch. Only reproducible using a new account, as mentioned by @gadhiyamanan in this [comment](https://github.com/Expensify/App/issues/19366#issuecomment-1559487977).

**Comment by CortneyOfstad** [comment] 2023-06-26 12:08
@BeeMargarida Yes, that was the blocker on my side. Reviewing the proposal now!

**Comment by CortneyOfstad** [comment] 2023-06-29 12:21
Any thoughts on the idea above @0xmiroslav?

**Comment by CortneyOfstad** [comment] 2023-06-30 19:40
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by NicMendonca** [comment] 2023-07-05 20:27
[bump](https://github.com/Expensify/App/issues/19366#issuecomment-1618547248) @kushu7 ^

**Comment by NicMendonca** [comment] 2023-07-10 10:13
@0xmiroslav any update here? What can we do to get this pushed along?

**Comment by shubham1206agra** [comment] 2023-07-11 17:19
@NicMendonca I may have an idea. 
What If we ask user to fill in the name (kind of nickname), that user might want to identify his account with in Authenticator App in step 1 of 2FA process and then generate the QR code accordingly in step 2. We can pre-populate this new field with `primaryLogin`, and then user can change it.

**Comment by NicMendonca** [comment] 2023-07-18 13:21
@0xmiroslav bump on @hungvu193's previous comments ^^

**Comment by shubham1206agra** [comment] 2023-07-24 08:22
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Email is not shown in authenticator app
### What is the root cause of that problem?

With the new account, after the first login, the `primaryLogin` is empty.

#### Why `primaryLogin` is empty for new accounts?
It is due to it is getting supplied during `BeginSignIn` API call in response, which is called when we submit the login in `LoginForm`
https://github.com/Expensify/App/blob/6759a6cbfa77f1864b69b93b83ae1097ff1ac764/src/pages/signin/LoginForm.js#L149

Now for a new user, as the user is still not registered as a new user while inputting the login, we get `primaryLogin` as empty.

And as we are not updating the value of `primaryLogin` anywhere else, it never gets updated before login in again after sign out.

As `primaryLogin` is being used while generating link here, which causes this issue.

https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js#L81-L83

### What changes do you think we should make in order to solve the problem?

Update the API logic associated with `beginSignIn` here
https://github.com/Expensify/App/blob/6759a6cbfa77f1864b69b93b83ae1097ff1ac764/src/libs/actions/Session/index.js#L249

to 

```js
// eslint-disable-next-line rulesdir/no-api-side-effects-method
    API.makeRequestWithSideEffects(
        'BeginSignIn',
        {email: login},
        {optimisticData, successData, failureData}
    ).then((response) => {
        if (response.jsonCode !== 200) {
            return;
        }
        const onyxData = _.reduce(response.onyxData, (res, obj) => ({...res, [obj.key]: obj}), {});
        if (!_.isEmpty(onyxData[ONYXKEYS.ACCOUNT].value.primaryLogin)) {
            return;
        }
        Onyx.update([{
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.ACCOUNT,
            value: {
                primaryLogin: login,
            }
        }]);
    });
```

Now instead of `API.read`, we will use `API.makeRequestWithSideEffects` so that we can check for new user by checking whether `primaryLogin` is empty or not. If it is empty, then update it to login as it will be updated to login on backend as well.

### What alternative solutions did you explore? (Optional)
NA

**Comment by NicMendonca** [comment] 2023-07-24 18:35
@0xmiroslav any thoughts on [this proposal](https://github.com/Expensify/App/issues/19366#issuecomment-1647441147)?

**Comment by shubham1206agra** [comment] 2023-07-24 23:18
> > And as we are not updating the value of `primaryLogin` anywhere else, it never gets updated before login in again after sign out.
> 
> @shubham1206agra you still didn't explain where it gets updated after re-login

It comes from beginSignIn only in response from backend

**Comment by NicMendonca** [comment] 2023-07-27 18:38
Any update here, please?

**Comment by NicMendonca** [comment] 2023-08-07 12:20
@0xmiroslav any update here?

**Comment by pbkompasz** [comment] 2023-08-09 12:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Email is not shown in authenticator app

### What is the root cause of that problem?

When signing in with a new account the `BeginSignIn` API request sends back an empty string for 

### What changes do you think we should make in order to solve the problem?


1. The BE should response should include `primaryLogin`
Observation: When making the same request(`BeginSignIn`), the second response includes the valid `primaryLogin`.
![Screenshot from 2023-08-09 15-36-40](https://github.com/Expensify/App/assets/47194071/ad8b50b1-d953-436c-a515-3fe5cdd53f04)
![Screenshot from 2023-08-09 15-36-33](https://github.com/Expensify/App/assets/47194071/7b1cb593-8fbb-4a82-8783-c33fac07426c)

A hack around this would making the same request twice. 


### What alternative solutions did you explore? (Optional)

/-

**Comment by NicMendonca** [comment] 2023-08-09 15:22
@0xmiroslav proposals to review ^^ 🎉

**Comment by roryabraham** [comment] 2023-08-14 23:28
Ok, reviewing this I tend to agree that this looks like something that should be fixed in the back-end. So here's my proposal, patched together from a few people's previous proposal along with my access to the back-end code. @NikkiWines can you review please?

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a user first logs in their email does not show in 2FA Authenticator Apps. This is mostly problematic for testers or power-users with multiple separate Expensify logins, because it makes it more difficult for them to know which 2FA code to use when signing in.

### What is the root cause of that problem?

The `primaryLogin` is returned as an empty string during the initial authentication flow when requesting the `BeginSignIn` API command. Afterward, when accessing `BeginSignIn`, the correct value of `primaryLogin` is returned.

The `primaryLogin` is later used to generate the [authenticator URL](https://github.com/Expensify/App/blob/6d1b9922effa021056e208407da1f89f163b8771/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js#L85-L93) ❌  

### What changes do you think we should make in order to solve the problem?

Update `BeginSignIn` so it always returns a valid login email for the `primaryLogin` value.

1. Update [this function](https://github.com/Expensify/Web-Expensify/blob/fb457b5b5b84304e078202fc149b002d96037821/lib/PartnerList.php#L129-L132) to accept an optional default email, and use that instead of an empty string as a fallback.
1. Right [here](https://github.com/Expensify/Web-Expensify/blob/992cff1fb2249397c5471efc0a0fea334713541c/lib/UserAPI.php#L3582), pass the `email` param as a default

**Comment by NikkiWines** [comment] 2023-08-15 18:23
Hmm, @roryabraham, let me know if I'm misunderstanding something but if the email passed to `BeginSignIn` is the primary login, shouldn't we instead figure out why it's not being returned as the `primaryLogin` in the response for `getPartnerList()`? 

I don't love the idea of passing an `email` to `getPrimaryLogin()` because it's a getter and also because we don't have a guarantee that the email being passed to `BeginSignIn` is the primary login. The user could be using a secondary login to log in.

**Comment by roryabraham** [comment] 2023-08-15 19:28
@NikkiWines to be clear this only happens for new sign-ups. So `GetPartnerList` doesn't return anything as the `primaryLogin` because it's only a getter (all `peek`, no `process`).

**Comment by NikkiWines** [comment] 2023-08-15 19:36
Ahh, ok - thanks for clarifying. Then I think we can just update [this logic](https://github.com/Expensify/Web-Expensify/blob/992cff1fb2249397c5471efc0a0fea334713541c/lib/UserAPI.php#L3582) to `$partnerList->getPrimaryLogin() ?: $email`? Unless there're other cases we know of other cases that use `getPrimaryLogin()` and would benefit from the passed `$email` param?

**Comment by shubham1206agra** [comment] 2023-08-16 06:12
@roryabraham If you are going to update BE, then I think you need to mark this issue as internal

**Comment by roryabraham** [comment] 2023-08-17 01:07
Thanks for the buddy-check @NikkiWines, I'll work on a PR.

**Comment by NicMendonca** [comment] 2023-08-22 14:47
@roryabraham any update on this one?

**Comment by NicMendonca** [comment] 2023-08-25 21:19
bump @roryabraham

**Comment by roryabraham** [comment] 2023-09-05 17:08
Created PR: https://github.com/Expensify/Web-Expensify/pull/38748

**Comment by roryabraham** [comment] 2023-09-13 02:24
Back-end solution was deployed to the staging API, but this does not appear to be fixed

**Comment by roryabraham** [comment] 2023-09-13 02:25
Not going to prioritize this right now as it's very low-value. Most production users will typically only ever have 1 `Expensify` account in their 2FA app

**Comment by shubham1206agra** [comment] 2023-09-22 12:35
## Proposal

[Updated](https://github.com/Expensify/App/issues/19366#issuecomment-1647441147)

**Comment by shubham1206agra** [comment] 2023-09-22 12:40
I am gonna write another test case which will again break use of primaryLogin

### Steps

1. Login to any account.
2. Make any new account as secondary Login.
3. Make the newly added account as primary
4. (Optional) Delete the old account as secondary login
5. Now, go to 2FA and scan the QR code

### Expected
New login email is shown in authenticator

### Actual
No / old email is shown in authenticator

**Comment by roryabraham** [comment] 2023-09-25 15:15
ok, let's do it

**Comment by roryabraham** [comment] 2023-10-03 05:16
Yep agreed that's fair in this case

**Comment by NicMendonca** [comment] 2023-10-10 20:06
@0xmiroslav bump on BZ checklist ^^

**Comment by NicMendonca** [comment] 2023-10-10 20:10
Payment summary: 

- Reporter: @gadhiyamanan - $250 (reported prior to $$ changes)
- Contributor: @hungvu193  - $750
- Contributor+:  @0xmiroslav - $750

**Comment by NicMendonca** [comment] 2023-10-10 20:11
@gadhiyamanan @0xmiroslav can you both please accept the offer in Upwork?

**Comment by gadhiyamanan** [comment] 2023-10-11 02:52
@NicMendonca offer accepted, thanks!

**Comment by NicMendonca** [comment] 2023-10-11 12:51
update, and everyone has been paid!

**Closed by NicMendonca** 2023-10-11 12:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
