### ISSUE TITLE
[HOLD for payment 2022-11-16] [$250] Workspace settings - The "Save" button is unavailable offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12453] opened 2022-11-03 21:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to Settings->Workspaces
4. Click on any workspace->Workspace settings
5. Kill the internet connection

## Expected Result:
The "Save" button should be available

## Actual Result:
"Save" button is unavailable

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.23.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199837705-b67ee0d3-1f07-4adc-a7da-d7ba63da8133.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-11-03 21:32
### Proposal

We need to pass `enabledWhenOffline` at `Form` to keep it enabled

https://github.com/Expensify/App/blob/1dd71747ba2b0c8553d84d51d863d8ae4e12ef64/src/pages/workspace/WorkspaceSettingsPage.js#L82

**Comment by johnmlee101** [comment] 2022-11-04 16:51
Confirmed in open-source that we should support saving when offline. Marking external

**Comment by neil-marcellini** [comment] 2022-11-04 16:52
I'm guessing this regression happened here when we refactored this page to use a form? https://github.com/Expensify/App/pull/11615

**Comment by thesahindia** [comment] 2022-11-04 18:05
Yup I think so. We already have a [proposal](https://github.com/Expensify/App/issues/12453#issuecomment-1302686778) which will fix this. What's the next step here?

**Comment by Beamanator** [comment] 2022-11-07 07:58
It looks like this issue was created _after_ the 7 day regression period, so I believe we should review proposals in this issue, no need to have the author of the regression fix the issue.

However, I think we need an RCA since the regression made it all the way to production?

**Comment by mateocole** [comment] 2022-11-07 16:24
Job posting on upwork!
https://www.upwork.com/ab/applicants/1589654996264235008/job-details

**Comment by thesahindia** [comment] 2022-11-07 16:28
> However, I think we need an RCA since the regression made it all the way to production?

cc: @rushatgabhane (since you reviewed https://github.com/Expensify/App/pull/11615)

**Comment by Beamanator** [comment] 2022-11-08 10:04
Maybe this just needs to be added to TestRail, not sure if this is technically a "regression"

**Comment by mvtglobally** [comment] 2022-11-16 02:23
Issue not reproducible during KI retests. (First week)

**Comment by mateocole** [comment] 2022-11-16 20:57
@Beamanator is this eligible for payment now?

**Comment by Beamanator** [comment] 2022-11-21 12:12
Yessir @mateocole !

**Comment by Puneet-here** [comment] 2022-11-21 14:25
> Job posting on upwork! https://www.upwork.com/ab/applicants/1589654996264235008/job-details

@mateocole, the link is for the job details.

**Comment by mateocole** [comment] 2022-11-21 22:45
Following payment steps [here](https://stackoverflow.com/c/expensify/questions/7582)

Hey @Puneet-here can you apply directly to the upwork posting so I can document and hire from there

**Comment by thesahindia** [comment] 2022-11-22 07:52
I have applied as well, thanks!

@Puneet-here, this is the correct link https://www.upwork.com/jobs/~01961de86d5adc919f (you can always search the upwork posting through the issue number)

**Comment by Puneet-here** [comment] 2022-11-22 08:12
> @Puneet-here, this is the correct link https://www.upwork.com/jobs/~01961de86d5adc919f 

Thanks. 

@mateocole, I have applied to the job.

**Comment by Beamanator** [comment] 2022-11-28 09:56
Bump @mateocole - has everyone been paid? If so, let's close this out!

**Comment by Beamanator** [comment] 2022-12-01 09:20
Another bump @mateocole :D

**Comment by mateocole** [comment] 2022-12-02 02:49
Okay offers have been sent over, once accepted will pay out!

**Comment by thesahindia** [comment] 2022-12-02 07:27
Accepted, thanks!

**Comment by Puneet-here** [comment] 2022-12-02 08:11
Accepted the offer @mateocole 
Note: This is eligible for 50% bonus because the PR was merged within 3 days

**Comment by mateocole** [comment] 2022-12-02 14:42
Okay both payments are complete!

**Closed by mateocole** 2022-12-02 14:42 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by thesahindia** [comment] 2022-12-02 14:49
@mateocole, the 50% bonus is also applicable for C+ reviewer

**Comment by thesahindia** [comment] 2022-12-09 10:13
bump @mateocole ^
