### ISSUE TITLE
[HOLD for payment 2024-01-03] [$500] Distance - Save button is unresponsive when adding, saving, then removing new point offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32397] opened 2023-12-02 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**
**Issue found when executing PR** https://github.com/Expensify/App/pull/31340
## Action Performed:
1. Go to staging.new.expensify.com
2. Create a distance request
3. Open distance request details page
4. Click Distance
5. Go offline
6. Add a new stop and save it
7. Click Distance again
8. Remove the new stop added in Step 5
8. Click Save

## Expected Result:
The new distance will be saved

## Actual Result:
Nothing happens when clicking on Save button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/def6fb5d-4221-4c56-b416-d68f90a6cbca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1d8e03c3ce30d53</li>
        <li>Upwork Job ID: 1730948270789206016</li>
        <li>Last Price Increase: 2023-12-09</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28064597</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertKozik</details>

**Comment by VenusWhisperer** [comment] 2023-12-02 15:01
Hello, My name is Daniel Cooper, and I have checked your problem.

The root cause of the problem is that the save button is disabled when the isLoading flag is set to true. This is because the isLoading flag indicates that the app is currently loading data or performing a task, and the save button should not be enabled while this is happening. 
 
There are a few ways to solve this problem. One way would be to allow the save button to be enabled even when the isLoading flag is set to true, but to disable the save button's functionality. This would allow the user to click the save button, but the save button would not actually do anything. 
 
Another way to solve this problem would be to disable the edit address and save waypoint buttons when the isLoading flag is set to true. This would prevent the user from being able to change the waypoint or save the waypoint while the app is loading data or performing a task. 
 
I would recommend disabling the edit address and save waypoint buttons when the isLoading flag is set to true. This would prevent the user from accidentally saving a waypoint while the app is still loading data or performing a task.

If you interested in this, I will try further and check it in more detail, and you can contact me.

My gmail account is janislee1204@gamil.com

**Comment by DylanDylann** [comment] 2023-12-02 16:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Save button is unresponsive when adding, saving, then removing new point offline

### What is the root cause of that problem?
When editing distance request the first time, isLoading field will be true 
Let's see 
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/DistanceRequest/index.js#L179-L186

If isLoading is true we do nothing when clicking the save button.
### What changes do you think we should make in order to solve the problem?
1. We should remove isLoading condition here
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/DistanceRequest/index.js#L181
2. One more thing, if we don't allow the user clicking the save button we should disable it to avoid confusion to user
We can create new variable
```
const isDisableButton = _.size(validatedWaypoints) < 2 || hasRouteError || isLoadingRoute

```

use it in here
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/DistanceRequest/index.js#L181
and add isDisabled props like this `isDisabled={isDisableButton}` in save button
### What alternative solutions did you explore? (Optional)

**Comment by sophiepintoraetz** [comment] 2023-12-05 04:48
Hey @robertKozik - are you able to review these proposals?

**Comment by sophiepintoraetz** [comment] 2023-12-11 03:54
@allroundexperts is jumping in! 🙏

**Comment by allroundexperts** [comment] 2023-12-11 04:11
Thanks for the proposals everyone. All the proposals have the same RCA. 

@DylanDylann I think the idea was to never disable the save button in offline mode as can be seen clearly [here](https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/DistanceRequest/index.js#L235).

I like the solution [proposed](https://github.com/Expensify/App/issues/32397#issuecomment-1837158456) by @dukenv0307 since it is inline with how we're handling the disabling of button [here](https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/DistanceRequest/index.js#L235).

🎀 👀 🎀 C+ reviewed

**Comment by flodnv** [comment] 2023-12-12 13:37
Assigning this to @neil-marcellini since it's related to distance requests

**Comment by neil-marcellini** [comment] 2023-12-15 15:26
Oh just seeing this now. I'll review today.

**Comment by neil-marcellini** [comment] 2023-12-18 15:35
> I like the solution [proposed](https://github.com/Expensify/App/issues/32397#issuecomment-1837158456) by @dukenv0307 since it is inline with how we're handling the disabling of button [here](https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/DistanceRequest/index.js#L235).
> 
> 🎀 👀 🎀 C+ reviewed

I agree, hiring!

**Comment by sophiepintoraetz** [comment] 2024-01-04 00:10
@dukenv0307 has been paid.
@allroundexperts - feel free to raise a request once you have filled out the [checklist](https://github.com/Expensify/App/issues/32397#issuecomment-1870434518).

**Closed by sophiepintoraetz** 2024-01-04 00:10 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by allroundexperts** [comment] 2024-01-07 20:15
## Checklist
1. https://github.com/Expensify/App/pull/29125
2. https://github.com/Expensify/App/pull/29125/files#r1444065369
3. N/A
4. A regression test would be helpful here.

## Regression Test

1. Open the App and request money using distance request
2. On distance request details page, click Distance and then go offline
3. Add a new stop and save it
4. Click Distance again
5. Remove the new stop added previously
6. Verify that clicking save leads to the new distance being saved

Do we 👍 or 👎 ?

**Comment by sophiepintoraetz** [comment] 2024-01-24 23:02
Payment summary - $500 to @allroundexperts

**Comment by JmillsExpensify** [comment] 2024-01-24 23:05
$500 approved for @allroundexperts based on comment above.
