### ISSUE TITLE
[$500] Can't copy thread reply date

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29597] opened 2023-10-13 23:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697165870397769

## Action Performed:
1. Open any report
2. Reply to any message and go back to original report
3. Try to copy date of the thread reply
4. Observe you are unable to copy the date and the cursor is also not text
## Expected Result: 
Should be able to copy thread date.
## Actual Result: 
Unable to copy thread date.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/1a752b46-4798-4713-bdb0-4f70cfcba66c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/ef15027d-f3fd-4471-bed2-0a3f60f588ad

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/b6ae1457-98db-469d-bb72-ea8eb6258ba1

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/c4e31698-ce1a-432e-9a8e-946dafad30f3

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/17e5cc2d-1711-441c-8564-e08f68f9b2c7

https://github.com/Expensify/App/assets/38435837/ab4b9dfe-a9f9-4b5b-9256-62daf86670b8

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/971d5a0c-58af-43a3-b9e3-35f3c1026e45

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f61f3cffddfa31f2</li>
        <li>Upwork Job ID: 1712971738873679872</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-13 23:21
### Proposal from @krishna2323

### Please re-state the problem that we are trying to solve in this issue.
Can't copy thread reply date

### What is the root cause of that problem?
We are disabling text selection by passing false to `selectable` prop on text and passing `dataSet={{[CONST.SELECTION_SCRAPER_HIDDEN_ELEMENT]: true}}` prop to text.

### What changes do you think we should make in order to solve the problem?
### Option 1
If we want to make text selectable but clicking on text still takes to child report we can just remove `selectable` & `dataSet` prop.

### Option 2 
If we want to make date selectable and not pressable then we have to do few changes:

1. Remove date text component from `PressableWithSecondaryInteraction`
2. Add `styles.flexRow, styles.alignItemsCenter, styles.mt2` to first View element in the file.
3. Remove `mt2` from View element inside `PressableWithSecondaryInteraction`.
4. Remove `selectable` & `dataSet` prop from date Text element.
5. Add padding top of 2px to  date Text element.

### Result

**Comment by Victor-Nyagudi** [comment] 2023-10-14 13:21
Is this worth fixing?

A user can just as easily click on the thread and copy the timestamp from there. The thread timestamp updates with the latest message, so as even more messages come in, the first message users are shown will have the same timestamp as the one they initially wanted to copy. 

It's a small extra step, but I doubt it's enough to adversely affect the user experience. 

I propose to do nothing here.

**Comment by astrohunter62** [comment] 2023-10-14 13:26
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Can't copy thread reply date.
### What is the root cause of that problem?
 `selectable` is Disabled in `Text`.
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/home/report/ReportActionItemThread.js#L70
### What changes do you think we should make in order to solve the problem?
We can set `true`.
```js
selectable = {true}
```

**Comment by adelekennedy** [comment] 2023-10-16 19:31
looks like this was already made external? @ntdiary any thoughts on two proposals above?

**Comment by adelekennedy** [comment] 2023-10-17 15:07
Then let's close this

**Closed by adelekennedy** 2023-10-17 15:07 UTC
Labels: External, Daily, Help Wanted, Bug
