### ISSUE TITLE
[$500] iOS - Chat - LHN page displayed instead Address page if using deeplink

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29060] opened 2023-10-08 09:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing PR https://github.com/Expensify/App/pull/28845

## Action Performed:
1. Launch app
2. Go to Settings -> Profile -> Personal Details -> Home address
3. Fill all the details
4. Log out
5. Open https://staging.new.expensify.com/settings/profile/personal-details/address

## Expected Result:
Login and verify city fields are populated

## Actual Result:
LHN page displayed instead of Address page if using deeplink.

Link opens Address page when user login.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.79-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6e9a22ba-7f57-4780-9fa4-99d9726bf168

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Intrnal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019fb8ae8d717b70d3</li>
        <li>Upwork Job ID: 1710949802581405696</li>
        <li>Last Price Increase: 2023-10-29</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-08 09:28
Issue found when validating PR https://github.com/Expensify/App/pull/28845

**Comment by abdulrahuman5196** [comment] 2023-10-10 17:37
Will review the proposals tomorrow.

**Comment by abdulrahuman5196** [comment] 2023-10-13 14:24
Missed to review this. Will close over the weekends.

**Comment by abdulrahuman5196** [comment] 2023-10-14 08:18
@izarutskaya I tested in latest production(app store) build unable to reproduce the same if I input the magic otp directly.
Then I checked the video where the magic link is pressed directly, the issue is reproducible if only I press the magic link.


@JmillsExpensify Do we expect the deeplinks to work even if the user presses the magic link in email?
Currently none of the deeplinks work that way, as far as i tested.

**Comment by abdulrahuman5196** [comment] 2023-10-16 14:26
@tienifr 
>if the app is terminated (not backgrounded) before clicking the magic link, the issue will happen (even if you input the magic code directly)

I don't understand this. Could you share a video of this?

**Comment by mvtglobally** [comment] 2023-10-17 15:12
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2023-10-17 20:59
>@JmillsExpensify Do we expect the deeplinks to work even if the user presses the magic link in email?
Currently none of the deeplinks work that way, as far as i tested.

Good question: I don't think so. I think we always use the browser when clicking a link, and at that point we prompt if the desktop app if installed. Right?

**Comment by abdulrahuman5196** [comment] 2023-10-23 11:51
Got it @tienifr . The issue is actually happening for all the deeplinks if the app is not quitted. So I think that is a valid bug when app is not getting terminated.

I will review the proposal and update on the same sooner.

**Comment by JmillsExpensify** [comment] 2023-10-24 22:46
Still discussing

**Comment by abdulrahuman5196** [comment] 2023-10-27 14:57
Sorry for the delay. Will review proposal today.

**Comment by abdulrahuman5196** [comment] 2023-10-31 12:00
Re-Reviewing now.

**Comment by abdulrahuman5196** [comment] 2023-10-31 15:11
@tienifr 's solution is working when i tested in ios. But I have questions on proposal,

We have been navigating inside the `Session.waitForUserSignIn()` like sometime.

https://github.com/Expensify/App/blob/74b75041cf1f4ffff331d1b82ba79c66292886f2/src/libs/actions/Report.js#L1996-L2004

Is there some regression causing this issue? Or is it not working for sometime. 
It would be best to make the change after fully understanding since its a core navigation place.

**Comment by abdulrahuman5196** [comment] 2023-11-06 14:09
Reviewing now.

**Comment by abdulrahuman5196** [comment] 2023-11-06 14:46
@tienifr 's proposal here https://github.com/Expensify/App/issues/29060#issuecomment-1752274819 looks good and works well

🎀 👀 🎀
C+ Reviewed

**Comment by grgia** [comment] 2023-11-09 17:39
All yours @tienifr

**Comment by situchan** [comment] 2023-11-19 15:42
There's regression from https://github.com/Expensify/App/pull/31174:

![regression](https://github.com/Expensify/App/assets/108292595/d0773069-24c7-43e2-8a9e-0c36b2fe0d45)

**Comment by JmillsExpensify** [comment] 2023-11-24 17:34
Have we resolved the regression yet?

**Comment by JmillsExpensify** [comment] 2023-11-24 17:35
Then additionally, it's a little unclear where we're at with this issue as the automation looks to have failed.

**Comment by abdulrahuman5196** [comment] 2023-11-24 17:39
@tienifr could you kindly check on this? If we have a regression? https://github.com/Expensify/App/issues/29060#issuecomment-1817891979

I don't see any GH issues though.

**Comment by JmillsExpensify** [comment] 2023-11-29 00:13
Waiting for a response

**Comment by abdulrahuman5196** [comment] 2023-11-29 17:21
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be the case from beginning.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Log out of app
2) Navigate to /settings/profile/personal-details/address by deeplink
3) Verify Address page displays

@JmillsExpensify The melvin automation has failed. This issue for payment due today - https://github.com/Expensify/App/pull/31174#issuecomment-1821919953

**Comment by JmillsExpensify** [comment] 2023-12-13 05:26
Payment summary:

 - Issue reporter: QA
 - Contributor: @tienifr $500
 - Contributor: @abdulrahuman5196 $500

**Comment by JmillsExpensify** [comment] 2023-12-13 05:55
Sent both contributors an offer via Upwork

**Comment by abdulrahuman5196** [comment] 2023-12-13 07:30
@JmillsExpensify Accepted the offer.

**Comment by JmillsExpensify** [comment] 2023-12-13 16:41
All contributors paid out and regression test created. Closing this issue.

**Closed by JmillsExpensify** 2023-12-13 16:41 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
