### ISSUE TITLE
Group chat - Not here page is hidden behind chat member profile page when URL modified

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43212] opened 2024-06-06 18:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43027
## Action Performed:
1. Log in to New Expensify
2. Click FAB > Start chat
3. create a group chat
4. Open the group chat > Click on header > Members
5. Click on any member > Profile
6. Modify the url by adding a random string to the url

## Expected Result:
"Hmm... it's not here" should be displayed in RHP as it is the case in 1:1 chats

## Actual Result:
Member profile pages remains in RHP, not here page can be seen if you tap on back arrow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0cece4a6-75e0-40cd-9144-7ea362fe2062

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-06 18:45
@amyevans  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by amyevans** [comment] 2024-06-06 20:18
> Modify the url by adding a random string to the url

In this case of modifying the group chat profile URL (`/a/<accountID>?backTo=<reportID>/participants/<accountID>`), you are modifying the query string, not the actual route, so the behavior is expected in my opinion. Pressing the back button results in a Not Found page because that was the part that was modified.

So I think this can be closed as expected behavior.

cc @s77rt @marcaaron though since you have more context, feel free to reopen the issue if you disagree with me and think it should be treated as a bug.

**Closed by amyevans** 2024-06-06 20:18 UTC
Labels: Engineering, Hourly

**Comment by s77rt** [comment] 2024-06-06 20:44
Agree not a bug. @lanitochka17 FWIW in the test I meant to modify the url before clicking on the "Profile" button.
