### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] CRITICAL: [UX Reliability] [$1000] Chat - Chat does not scroll down when sending messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40724] opened 2024-04-22 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to empty chat.
3. Send a text.

## Expected Result:
The chat view will scroll down to show the latest message.

## Actual Result:
The chat view does not scroll down to show the latest message.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0006cc82-9880-42b6-8543-6c48e605ea0f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016dcc2d8605cc9198</li>
        <li>Upwork Job ID: 1782503029072748544</li>
        <li>Last Price Increase: 2024-05-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
<li>nkdengineer | Contributor | 102574769</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by kbecciv** [comment] 2024-04-22 20:07
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment] 2024-04-22 20:15
Looking for proposals

**Comment by luacmartins** [comment] 2024-04-22 20:18
Gonna look into this one

**Comment by mountiny** [comment] 2024-04-22 20:31
it might be related to https://github.com/Expensify/App/pull/40547

**Comment by climax0916** [comment] 2024-04-22 23:16
I found the issue, and looking for possible solutions.

**Comment by luacmartins** [comment] 2024-04-22 23:46
Cool, let us know what you find @climax0916

**Comment by climax0916** [comment] 2024-04-22 23:57
When adding comments, `shouldEnableAutoScroll` turns to `False` so `ReportActionsList` doesn't scroll to the latest message.

https://github.com/Expensify/App/blob/a43595b99ac4d8451b6cc147ae007315dce481da/src/pages/home/report/ReportActionsView.tsx#L488-L512

**Comment by climax0916** [comment] 2024-04-22 23:57
@luacmartins Am I right?

**Comment by luacmartins** [comment] 2024-04-23 00:05
Why does it become `false`?

**Comment by climax0916** [comment] 2024-04-23 00:12
When adding new transactions, this `API.write()` function is called:
https://github.com/Expensify/App/blob/a43595b99ac4d8451b6cc147ae007315dce481da/src/libs/actions/Report.ts#L604-L608

Then, `Onyx.update(optimisticData)` is called for update Onyx storage:
https://github.com/Expensify/App/blob/a43595b99ac4d8451b6cc147ae007315dce481da/src/libs/API/index.ts#L56-L63

After that, render again because of Onyx storage changed. But, here `hasNewestReportAction` will be `False`:
https://github.com/Expensify/App/blob/a43595b99ac4d8451b6cc147ae007315dce481da/src/pages/home/report/ReportActionsView.tsx#L235

Because of this, the scroll doesn't down to the latest message.

**Comment by DylanDylann** [comment] 2024-04-23 04:54
I think this issue have the same RCA with https://github.com/Expensify/App/issues/40664

**Comment by ikevin127** [comment] 2024-04-23 07:59
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Chat does not scroll down when sending messages.

### What is the root cause of that problem?

Two things which both cause our issue:

### 1.
Whenever we start a new chat there's this new action which I assume was introduced by BE recently: an additional new `ADDCOMMENT` action comes in right after the "CREATED" action, which is an automated message (one in the middle):

<img width="1165" alt="Screenshot 2024-04-23 at 05 43 37" src="https://github.com/Expensify/App/assets/56457735/12fa2590-c212-4c1a-9fc2-9c5b9b1aa177">

This addition causes [`hasNewestReportAction`](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/home/report/ReportActionsList.tsx#L203) to return `false` since sortedReportActions?.[0] is now the automated `ADDCOMMENT` action (first in sortedReportActions) instead of the user posted message like it used to be -> meaning that the the automated message's created date is not equal to the report's lastVisibleActionCreated date because the lastVisibleActionCreated date equals to the sortedReportActions?.[1] at index 1 (user's comment) hence the condition returns `false`.

This makes it such that the [`scrollToBottomForCurrentUserAction`](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/home/report/ReportActionsList.tsx#L326-L336) returns early because of the `!hasNewestReportActionRef.current` check being `true`.

### 2.
Due to recent new architecture being enabled, it looks like the native specific [`scrollToBottom`](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/hooks/useReportScrollManager/index.native.ts#L19-L30) function does not trigger the scrolling anymore even though it's called and this happens because there's a few things going on when we post a comment from JS's point of view and because `scrollToBottom` gets called while the stack is ongoing (not cleared yet), the function does not perform it's logic as expected.

### What changes do you think we should make in order to solve the problem?

We have a two part solution to address both parts of the RCA:

### 1.
Create a util function that we can apply to `reportActionsToDisplay` [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/home/report/ReportActionsView.tsx#L479) which is passed as prop `sortedReportActions` to `ReportActionsList`. A mock of the util function would look something like this:

```ts
actions.filter(action => action.actionName === 'ADDCOMMENT' && action.originalMessage?.type !== 'automated');
```

We will use this in order to filter out the automated `ADDCOMMENT` action based on `originalMessage.type === CONST.IOU.REPORT_ACTION_TYPE.AUTOMATED` (this const will be a new addition to `REPORT_ACTION_TYPE`).

By doing this, the current `hasNewestReportAction` check logic will work as expected since we filtered out the automated `ADDCOMMENT` action which messed up the logic mentioned above.

**2.**
In order to have the `scrollToBottom` function work as expected, similar to what I proposed in issue https://github.com/Expensify/App/issues/38855 and was selected / approved -> use `deferred execution` via `requestAnimationFrame` to wrap the contents of the function like so:

```ts
    const scrollToBottom = useCallback(() => {
        requestAnimationFrame(() => {
            if (!flatListRef?.current) {
                return;
            }
    
            setScrollPosition({offset: 0});
    
            flatListRef.current?.scrollToOffset({animated: false, offset: 0});
        });
    }, [flatListRef, setScrollPosition]);
```

This ensures that the code within `scrollToBottom` will be executed on the next tick, essentially telling the JavaScript runtime to execute this code after the current call stack has cleared.

Here's a test branch of the solution: [test/40724](https://github.com/ikevin127/Expensify/tree/test/40724) and it's [diff](https://github.com/Expensify/App/compare/main...ikevin127:test/40724).

### Videos (before / after)

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/e2bb979f-8fb4-43ab-89d7-9c4cf8b1ede9"> | <video src="https://github.com/Expensify/App/assets/56457735/cdec43a3-af77-4af3-a78b-726b1277aa0f"> |

</details>

**Comment by mountiny** [comment] 2024-04-23 09:00
Based on the previous comments this seems like it might not be a deploy blocker as if its related to the new architecture, that has already been deployed to production

**Comment by mountiny** [comment] 2024-04-23 09:57
I think we can demote this, please correct me if I am wrong. It looks like a minor UX issue to me.

It seems like from the analysis that its a mix of new architecture and backend changes which causes this bug. 

I am not sure how we decided to handle the whisper messages but it seems like they both have the same previous report action ID 
<img width="851" alt="image" src="https://github.com/Expensify/App/assets/36083550/256c5d3f-d6d0-40bc-a215-8a3803fea783">

and that might be causing the comment linking code to not be happy

**Comment by mountiny** [comment] 2024-04-23 10:00
making a build on the linked PR

@ikevin127 I can reproduce this in old chats too

**Comment by DylanDylann** [comment] 2024-04-23 13:48
> This addition causes [hasNewestReportAction](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/home/report/ReportActionsList.tsx#L203) to return false since sortedReportActions?.[0] is now the automated ADDCOMMENT action (first in sortedReportActions) instead of the user posted message like it used to be

@ikevin127 As I understand sortedReportActions?.[0] will be the latest comment then it should be user's comment (based on created field). Could you help to explain your point `sortedReportActions?.[0] is now the automated ADDCOMMENT action`

**Comment by DylanDylann** [comment] 2024-04-23 13:52
You mean that when [scrollToBottomForCurrentUserAction](https://github.com/Expensify/App/blob/ee5ab95f2c893738fb48756a9002e9d9dadd9a31/src/pages/home/report/ReportActionsList.tsx#L321-L331) function is triggered, the new comment has not been added yet to sortedReportActions

**Comment by luacmartins** [comment] 2024-04-23 19:42
It seems like the changes to `scrollToBottom` are enough to fix this issue. I'm not sure that I understand why the whisper message would be contributing to it.

**Comment by luacmartins** [comment] 2024-04-23 19:43
As @mountiny pointed out, it seems like we have two actions pointing to the same `previousReportActionID` which might mess up the logic for comment linking, but I don't think contributes to the scrolling issue

**Comment by luacmartins** [comment] 2024-04-23 19:43
@ikevin127 are you available to work on a fix with the solution for 2?

**Comment by mountiny** [comment] 2024-04-24 10:15
This seems to be not be fully fixed for me. It was on the adhoc build, but now in the 1.4.65-0 staging I can see a similar behaviour @ikevin127 can you please follow up with a fix as it was not completely fixed

https://github.com/Expensify/App/assets/36083550/1e3054c1-3e22-445c-909d-2aab435990fb

**Comment by ikevin127** [comment] 2024-04-24 18:53
> @ikevin127 As I understand sortedReportActions?.[0] will be the latest comment then it should be user's comment (based on created field). Could you help to explain your point sortedReportActions?.[0] is now the automated ADDCOMMENT action

@DylanDylann When opening a new chat with somebody, `sortedReportActions` contains report actions of actionName types `CREATED` and `ADDCOMMENT`. Since this new `type: 'automated'` action was added, now there are 2 `ADDCOMMENT` of which the first one (`sortedReportActions?.[0]`) is now the automated ADDCOMMENT action instead of the comment the user just posted.

> @ikevin127 are you available to work on a fix with the solution for 2?

@luacmartins Yes! I have to mention that PR https://github.com/Expensify/App/pull/40286 which was merged in hopes to fix this issue, was expected that **it would not fix this issue** because there are different root cause between issue https://github.com/Expensify/App/issues/38855 and this one.

I noticed that you edited my PR's description and mentioned that it also fixes this issue, I edited it back and removed that since it was not meant to fix this issue.

> This seems to be not be fully fixed for me. It was on the adhoc build, but now in the 1.4.65-0 staging I can see a similar behaviour @ikevin127 can you please follow up with a fix as it was not completely fixed

@mountiny As explained above, PR https://github.com/Expensify/App/pull/40286 was not meant to fix this issue. I think there was a misunderstanding here where because the issues are similar in terms of the scrolling-related bug, the root cause is different.

We shouldn't mix them up and consider a regression the fact that this issue wasn't fixed by PR https://github.com/Expensify/App/pull/40286, as this issue needs a different / separate fix based on the [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2071666884) posted here.

> We didn't test it against latest main so there might be some issue.

@parasharrajat Makes sense here as this issue (#40724) will still be reproduced regardless of PR https://github.com/Expensify/App/pull/40286 being merged since the RCA explained in the [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2071666884) above still stands, the new `ADDCOMMENT` action with `originalMessage.type: 'automated'` coming from BE creates this issue + the additional `deferred execution` part which is needed on certain platforms.

**Comment by ikevin127** [comment] 2024-04-24 20:43
I found the discrepancy between PR https://github.com/Expensify/App/pull/40286 and this issue's fix, there are two parts to it:

1. This specific line of PR https://github.com/Expensify/App/pull/40286, which is currently on main covers for the RCA problem number (1.) of [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2071666884) by making sure that the scrolling happens even if the first message is a whisper (automated) when the user posts their first comment.

✅ So this part of the PR is correct and handles [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2071666884)'s solution part (1.) more elegantly, instead of filtering out all whisper actions which would be bad as the whisper messages wouldn't show up anymore in reports.

2. Part two of the [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2071666884)'s solution (2.) was not applied yesterday before the PR was merged, specifically for `index.native.ts` (native only).

⚠️ This is why this issue is not fixed currently, even though the first part of the [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2071666884)'s solution (1.) was handled by PR https://github.com/Expensify/App/pull/40286, the second part was not.

Therefore the only thing left to do here in order to have this issue fixed and closed is to make sure we wrap the `index.native.ts`'s `scrollToBottom` function with `requestAnimationFrame` as well like we did in the `index.ts` file.

I'll open a PR for this issue where I will only implement the part (2.) of the [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2071666884)'s solution.

cc @mountiny @parasharrajat @luacmartins

**Comment by mountiny** [comment] 2024-04-24 20:48
Thanks Kevin!

**Comment by ikevin127** [comment] 2024-04-25 20:18
Looks like the `requestAnimationFrame` solution created a regression here:
- https://github.com/Expensify/App/issues/40911

Therefore we should find alternative solutions / proposals for fixing this issue as well since it was suggested that we revert PR https://github.com/Expensify/App/pull/40286, here https://github.com/Expensify/App/issues/38855#issuecomment-2078080833.

**Comment by luacmartins** [comment] 2024-04-29 18:58
@ikevin127 any luck finding a solution for this? Should we revert the [original PR](https://github.com/Expensify/App/pull/40286)?

**Comment by ikevin127** [comment] 2024-04-29 19:12
@luacmartins I don't have a solution for this issue, I tried applying defer execution to the `scrollToBottom` and this only solves the problem on iOS: Native, the issue persists on Android: Native.

Regarding PR https://github.com/Expensify/App/pull/40286, the only solution that works and would keep the original PR's fix and solve issue https://github.com/Expensify/App/issues/40911 would be to replace [original PR](https://github.com/Expensify/App/pull/40286/files)'s `requestAnimationFrame` with a 0 delay `setTimeout`. This is because we need to defer execution and `requestAnimationFrame` is problematic in the case of pressing the `New message` button.

**Comment by luacmartins** [comment] 2024-04-30 14:34
It seems like we reverted the original PR. Let's keep exploring solutions then.

**Comment by luacmartins** [comment] 2024-05-09 20:10
Gonna bump the price on this again.

**Comment by mountiny** [comment] 2024-05-10 14:40
@ikevin127 any more ideas here from your side?

**Comment by ikevin127** [comment] 2024-05-10 16:42
> I don't have a solution for this issue, I tried applying defer execution to the `scrollToBottom` and this only solves the problem on iOS: Native, the issue persists on Android: Native.
>
> This is because we need to defer execution and `requestAnimationFrame` is problematic in the case of pressing the New message button.

@mountiny So far, I stand by what I said in an earlier comment. I was planning to look deeper into this one but didn't get to it yet.

So far I went as deep as looking into the native flatlist scrolling function on Android: Native side, following it down from our `scrollToBottom`, but everything looks fine there.

Therefore, in no particular order I'd say, if we were to go with the 0 delay `setTimeout` for deferred execution, my take as to why Android: Native still doesn't work could be:
- some conflicting scrolling logic in our report actions list component which cancels out the scrolling
- new architecture related (found some changes to the native scrolling functions introduced with new arch, like if new_arch then return scrolling function which looks a bit different than the old way)

I'll keep digging and let you know in case I find anything.

**Comment by tsa321** [comment] 2024-05-12 17:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue

Chat doesn't scroll to bottom when sending message in empty chat room

### What is the root cause of that problem?

In [here](https://github.com/Expensify/App/blob/a9f9d459b393fb8f3940e0134b506a65a366ded8/src/pages/home/report/ReportActionsList.tsx#L352) we subscribe to newActionEvent with this callback:

https://github.com/Expensify/App/blob/a9f9d459b393fb8f3940e0134b506a65a366ded8/src/pages/home/report/ReportActionsList.tsx#L326-L335

When user sending a message, the addActions will be excuted and will call notifyNewAction, in [here](https://github.com/Expensify/App/blob/a9f9d459b393fb8f3940e0134b506a65a366ded8/src/libs/actions/Report.ts#L614). But the Onyx merge for optimistic data doesn't finished yet, the subscription callback (scrollToBottomForCurrentUserAction) is called when the new report actions isn't exist in onyx yet. This will cause `hasNewestReportActionRef` to be false and the `scrollToBottomForCurrentUserAction` will early returned without executing `reportScrollManager.scrollToBottom`. So the chat won't scroll.

### What changes do you think we should make in order to solve the problem?

We could add useRef `userActionIsComing`, set the value to be true inside the subscription callback. Then add useEffect that depend on lastActionIndex and will eventually execute reportScrollManager.scrollToBottom if passing the checks. The rough code could be:
The modified callback:

```javascript
const scrollToBottomForCurrentUserAction =  useCallback(
        (isFromCurrentUser: boolean) => {
            if (isFromCurrentUser) {
                userActionIsComming.current = true;
            }
        },[reportScrollManager]
);
 
```

Then rough useEffect code: 

```javascript
useEffect(() => {
    const reportAction = ReportActionsUtils.getReportAction(report.reportID, lastActionIndex);
    if (userActionIsComming.current &&
        previousLastIndex.current !== lastActionIndex

        // Check whether the report action from current user
        && reportAction?.actorAccountID === Report.getCurrentUserAccountID()

        // Check whether report action should be visible
        && ReportActionsUtils.shouldReportActionBeVisible(reportAction)
    ) {
        InteractionManager.runAfterInteractions(() => {
            reportScrollManager.scrollToBottom();
        });
        userActionIsComming.current = false;
    }

}, [lastActionIndex]);
```

**Comment by mountiny** [comment] 2024-05-13 10:18
@parasharrajat @hoangzinh @samilabud It seems like a fix in this PR https://github.com/Expensify/App/pull/42030 might also fix this issue, can you please test it on the PR? 

@tsa321 Thank you for the proposal @parasharrajat can you please check it out. Lets see if this bug is resolved by the aforementioned PR

**Comment by tsa321** [comment] 2024-05-17 14:26
I have updated my [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2106322218) if you need an another solution beside the existing PR...

**Comment by tsa321** [comment] 2024-05-17 14:52
I have updated my [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2106322218), in case you need another solution beside the existing PR...

**Comment by shawnborton** [comment] 2024-05-17 18:56
What's the latest on this one? cc @saracouto

**Comment by tsa321** [comment] 2024-05-19 00:30
## Proposal

[Updated](https://github.com/Expensify/App/issues/40724#issuecomment-2106322218), if you need another solution...

**Comment by mountiny** [comment] 2024-05-21 13:19
Also moving this to Newdot Quality, critical and UX reliability and assigning myself to keep the pressure up on this one

**Comment by tsa321** [comment] 2024-05-21 13:24
@mountiny How about my proposal? Is it not good?

**Comment by tsa321** [comment] 2024-05-21 14:50
@mountiny maybe on here: https://github.com/Expensify/App/pull/30269

The `hasNewestReportAction` is introduced. 
From this comment https://github.com/Expensify/App/pull/30269#issuecomment-2015964796, there seems a deploy blocker https://github.com/Expensify/App/issues/38839 because of the `hasNewestReportAction`.
The PR https://github.com/Expensify/App/pull/39665 in that issue trying to fix it, but it needs back end changes.
Also in here https://github.com/Expensify/App/pull/42406 and https://github.com/Expensify/App/pull/42030 trying to fix it too.

My suggestions in [here](https://github.com/Expensify/App/issues/41188#issuecomment-2119041378), instead of using exact time match down to millisecond, we compensate some milliseconds:

```javascript
const hasNewestReportAction = useMemo(() => {
   const reportAction = ReportActionsUtils.getReportAction(report.reportID, lastActionIndex);
   const timeDifference = new Date(report.lastVisibleActionCreated) - new Date(reportAction.created);
   if (timeDifference < 300) {
       return true;
   }
   return false;

}, [lastActionIndex, report.lastVisibleActionCreated, report.reportID]);
```

**Comment by filip-solecki** [comment] 2024-05-22 14:05
From my investigation I am 90% sure that new architecture doesn't cause this issue. I've spoken with guys more familiar with this topic than me and they are also almost sure that it is not caused by the new arch enablement. I am looking for the other root cause.

**Comment by rojiphil** [comment] 2024-05-25 05:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat does not scroll down when sending messages

### What is the root cause of that problem?

I think the root cause has to do with the refactor done in PR [here](https://github.com/Expensify/App/pull/39685). There we refactored the logic to make use of `hasNewestReportActionRef` instead of `hasNewestReportAction`. However, `hasNewestReportAction` is the true indicator of the newest report action status whereas `hasNewestReportActionRef` can be temporarily false until updated. This can cause `scrollToBottomForCurrentUserAction` to return early [here](https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/pages/home/report/ReportActionsList.tsx#L345C1-L347C14) thereby resulting in the skipping of scroll operation.

Offending PR: #39685

### What changes do you think we should make in order to solve the problem?

Use `hasNewestReportAction` instead of `hasNewestReportActionRef` [here](https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/pages/home/report/ReportActionsList.tsx#L345) and add `hasNewestReportAction` as a dependency [here](https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/pages/home/report/ReportActionsList.tsx#L350)

Here is a [draft branch](https://github.com/rojiphil/App/tree/40724-fix-newest-action-scroll-issue) for the changes.

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-05-25 05:34
@parasharrajat Does this [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2130786328) make sense to you?
I have also posted a query [here](https://github.com/Expensify/App/pull/39685#discussion_r1614367099) if the refactor was needed for the concerned issue fix there.

**Comment by nkdengineer** [comment] 2024-05-25 05:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New message button is not responsive and chat does not scroll down.

### What is the root cause of that problem?
When we add a comment, `lastVisibleActionCreated` of the report and `created` of the optimistic action are not sync because both of them are `DateUtils.getDBTimeWithSkew()` at the different times

https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/libs/actions/Report.ts#L478-L483

That makes `hasNewestReportAction` is `false` and then the chat doesn't scroll to the bottom
https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/home/report/ReportActionsList.tsx#L214

https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/home/report/ReportActionsList.tsx#L345
### What changes do you think we should make in order to solve the problem?
In here we should update `lastVisibleActionCreated` as `lastAction.created` instead of getting current time again. We should do the same when we add other actions like IOU, task, ... if it has the same problem.

https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/libs/actions/Report.ts#L483
### What alternative solutions did you explore? (Optional)
NA

**Comment by tsa321** [comment] 2024-05-25 05:44
@parasharrajat we could check on pendingAction of reportAction and we don't need to check on newestReportAction. The code could be:

```javasrcipt
useEffect(() => {
        const previousLastReportAction = ReportActionsUtils.getReportAction(report.reportID, previousLastIndex.current);
        const previousCreatedDate = new Date(previousLastReportAction.created);
        const previousIndex = sortedVisibleReportActions.findIndex((action) => new Date(action.created) < previousCreatedDate);
        const addedActions = sortedVisibleReportActions.slice(0, previousIndex === -1 ? -1 : previousIndex - 1);
        const userActionExist = addedActions.find((action) => action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);
        if (userActionExist) {
            InteractionManager.runAfterInteractions(() => {
                reportScrollManager.scrollToBottom();
            });
        }
    }, [lastActionIndex]);

**Comment by nkdengineer** [comment] 2024-05-25 05:46
> When we add a comment, lastVisibleActionCreated of the report and created of the optimistic action are not sync because both of them are DateUtils.getDBTimeWithSkew() at the different times

@parasharrajat I think the current RCA is here.

**Comment by rojiphil** [comment] 2024-05-27 09:02
> I am testing your proposal, but it looks like mentioned PR didn't cause this issue. Did you test it? I could still reproduce this issue after reverting changes from [#39685](https://github.com/Expensify/App/pull/39685)

@filip-solecki hmm... Interesting. I tried at least 15-20 times sending a text comment and it did work for me. Before the change, it use to fail quite often i.e. on sending every 3-4 text comments. Also, I had verified that `hasNewestReportAction`and `hasNewestReportActionRef` were out of sync temporarily whenever  `scrollToBottomForCurrentUserAction` failed to scroll. 
Can you please share a test video with the revert? Maybe I am missing something in the tests.

**Comment by filip-solecki** [comment] 2024-05-27 09:03
Looks like @nkdengineer's proposal is working fine, but did you find the root cause? The one you wrote sounds realistic, but it was not edited for a while so I am not sure if this is the real root cause.

**Comment by filip-solecki** [comment] 2024-05-27 09:04
From my investigation the real root cause is [this line ](https://github.com/Expensify/App/pull/39951/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811db:~:text=()%2C-,created%3A%20DateUtils.getDBTimeWithSkew(Date.now()%20%2B%20createdOffset)%2C,-isFirstItem%3A%20false) - probably `Date.now()` function execution takes too long and the current time and lastComment.created are different 
cc @mountiny

**Comment by nkdengineer** [comment] 2024-05-27 09:09
> When we add a comment, lastVisibleActionCreated of the report and created of the optimistic action are not sync because both of them are DateUtils.getDBTimeWithSkew() at the different times

@filip-solecki As I mentioned in my proposal, the RCA is we get the current time at two place, one in `buildOptimisticAddCommentReportAction`, one in [here](https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/libs/actions/Report.ts#L478). So it can have a small different between `create` of new action and `lastVisibleActionCreated` of the report that makes `hasNewestReportAction` is `false` and then the chat doesn't scroll to the bottom although `scrollToBottomForCurrentUserAction` is still called.

https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/home/report/ReportActionsList.tsx#L341

**Comment by nkdengineer** [comment] 2024-05-27 09:19
@filip-solecki Thanks for your feedback, I checked in `addActions`, `currentTime` is only used to update the `lastVisibleActionCreated` and `lastReadTime` of the report. If we change `lastVisibleActionCreated` from `currentTime ` to `lastComment.created`, it will not cause another regression because it will update `lastVisibleActionCreated` with the correct `created` time of last action.

**Comment by filip-solecki** [comment] 2024-05-27 09:23
Ok, sounds good. 
@mountiny IMO we can accept @nkdengineer's proposal right now
@parasharrajat WDYT?

**Comment by tsa321** [comment] 2024-05-27 10:14
@parasharrajat @filip-solecki  I have tested it on IOS native, removing this check:
https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/pages/home/report/ReportActionsList.tsx#L345-L348

and just execute the `InteractionManager.runAfterInteractions(() => reportScrollManager.scrollToBottom());` 

still doesn't work for me. Here is the video:


https://github.com/Expensify/App/assets/114975543/baf455ea-ce9a-40a6-b38b-cb1056be0bdc

**Comment by filip-solecki** [comment] 2024-05-27 10:29
@tsa321 I think this is not solution proposed by what you are testing @nkdengineer

**Comment by rojiphil** [comment] 2024-05-28 03:03
> Did you test it? I could still reproduce this issue after reverting changes

Ah! I could reproduce the issue on an iOS native platform. Looks like there is more to the story here.

**Comment by filip-solecki** [comment] 2024-05-28 18:54
Looks like one of them is just some kind of workaround and the second one is really solving the root cause but we have to find which one is the correct one. 
For me it looks like @nkdengineer's investigation is on point because we can find when it was changed and bug exists from almost the same date, but I will investigate more tomorrow

**Comment by tsa321** [comment] 2024-05-31 00:04
@parasharrajat for more robust code we could add `newestPendingActionTime` ref with initial value of `report.lastVisibleActionCrated`. We compare the ref with the added/new pending actions. If the new pending actions is newer, we scroll to bottom and update the ref. The code could be:

```javascript
const newestPendingActionTime = useRef(report.lastVisibleActionCreated);

const addedActions = useMemo(() => {
    const previousLastReportAction = ReportActionsUtils.getReportAction(report.reportID, previousLastIndex.current);
    const previousCreatedDate = new Date(previousLastReportAction.created);
    const previousIndex = sortedVisibleReportActions.findIndex((action) => new Date(action.created) < previousCreatedDate);

    return sortedVisibleReportActions.slice(0, previousIndex === -1 ? -1 : previousIndex - 1);
}, [lastActionIndex]);

useEffect(() => {
    const newCreatedUserActions = addedActions.filter((action) => (action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) && (new Date(action.created) > new Date(newestPendingActionTime.current)));
    if (newCreatedUserActions.length > 0) {
        InteractionManager.runAfterInteractions(() => {
            reportScrollManager.scrollToBottom();
        });

        newestPendingActionTime.current = newCreatedUserActions.reduce((a, b) => Math.max(new Date(a.created), new Date(b.created))).created;
    }
}, [addedActions]);
```

and put it above this [line](https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/pages/home/report/ReportActionsList.tsx#L234).

**Comment by nkdengineer** [comment] 2024-05-31 04:15
> @nkdengineer I was checking and found out that proposal matches with https://github.com/Expensify/App/pull/42030. How is it different from that solution?


@parasharrajat  I just checked https://github.com/Expensify/App/pull/42030 and I think we shouldn't add a new param like `currentTime`. Instead we should update `lastVisibleActionCreated` with the `created` of the new action that we're creating. That can make sure `lastVisibleActionCreated` is always match with the created of the last visible action. Beside If we pass `currentTime` like this PR, the bug can be happen in the feature if we miss to pass this param to the build optimistic function.

> Also, can you check for issues mentioned on that PR? Like https://github.com/Expensify/App/pull/42030#issuecomment-2110567443.

For this bug, it happens because in this PR we're updating `lastVisibleActionCreated` of chat report when we submit a new request in an exist report preview which makes `hasNewestReportAction` is `false` at the time we add a new message. We should only update `lastVisibleActionCreated` if we create a new report preview action. And we also need to update `lastVisibleActionCreated` of iou report when we submit a new request.

**Comment by nkdengineer** [comment] 2024-06-03 04:05
> Could you please confirm if your proposal is working for the following cases:

@parasharrajat Sure, my proposal is working for all following cases above:

1. for attachments, text messages, For whispers.


https://github.com/Expensify/App/assets/161821005/1b51abe7-d2aa-48f4-8f89-42968733d041


2. For IOU reports,  For IOU previews.


https://github.com/Expensify/App/assets/161821005/d3439edd-6fa3-474d-8dec-c035f70c969a

3. For thread replies



https://github.com/Expensify/App/assets/161821005/fa00f2d8-16ca-4e4a-adc8-9e6d7e04af85

4. For offline case 


https://github.com/Expensify/App/assets/161821005/212cf485-6a4c-438c-875b-943e1e320369


https://github.com/Expensify/App/assets/161821005/10dbfab1-ba0a-4f02-8550-38da08cd28c4


https://github.com/Expensify/App/assets/161821005/97080fdd-e0b8-4c8c-93ca-6509018c1a62

**Comment by tsa321** [comment] 2024-06-03 05:54
@nkdengineer the issue is reported for IOS and android native platform

**Comment by nkdengineer** [comment] 2024-06-03 06:00
> @nkdengineer the issue is reported for IOS and android native platform

This issue also happens on Web.

**Comment by nkdengineer** [comment] 2024-06-03 06:18
@parasharrajat Also work well on IOS and IOS safari

1. for attachments, text messages, For whispers.


https://github.com/Expensify/App/assets/161821005/1eecce7a-f17c-4c5f-9937-ad87c3636918

2. For IOU reports, For IOU previews.


https://github.com/Expensify/App/assets/161821005/30822668-18c4-4f43-8b0a-9fe7edff5329

3. For thread replies


https://github.com/Expensify/App/assets/161821005/2ca665a0-e3fa-46be-a008-07bca7f8dc6b

4. For offline cases


https://github.com/Expensify/App/assets/161821005/eaa08a7b-1a06-4cef-8870-dd2cc42c996b


https://github.com/Expensify/App/assets/161821005/61da35ed-c394-483d-864e-a17fa2029e72


https://github.com/Expensify/App/assets/161821005/fed8e71c-2e31-414d-84bf-40886f5c95ac

**Comment by puneetlath** [comment] 2024-06-03 20:48
@nkdengineer do you have an ETA for raising the PR?

**Comment by nkdengineer** [comment] 2024-06-04 02:04
I will raise the PR today.

**Comment by nkdengineer** [comment] 2024-06-04 06:10
@parasharrajat The PR is [here](https://github.com/Expensify/App/pull/43021).

**Comment by luacmartins** [comment] 2024-06-20 17:43
IMO we can skip TC in this case given that's such an obvious issue that many people would report it. I'm not too passionate about it though so also ok adding it.

**Comment by anmurali** [comment] 2024-06-21 01:47
Final payment summary
- [X] @nkdengineer $1000 via Upwork
- [ ] @parasharrajat request $1000 via ND approved

**Comment by m-natarajan** [comment] 2024-07-09 18:49
Reopening as per this https://expensify.slack.com/archives/C049HHMV9SM/p1720444720601389

**Comment by anmurali** [comment] 2024-07-10 04:08
Closing this again as per that thread we agreed to create a new issue.

**Closed by anmurali** 2024-07-10 04:08 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
