### ISSUE TITLE
[HOLD for payment 2024-09-09] [$250] Android & iOS Expense - Main chat becomes blank after returning from transaction thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48369] opened 2024-08-30 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace chat.
3. Submit two expenses.
4. Tap on the expense preview to go to expense report.
5. Tap on the expense preview again to go to transaction thread.
6. Tap back button twice to return to main chat.

## Expected Result:
The main chat will not be blank after returning from transaction thread.

## Actual Result:
The main chat becomes blank after returning from transaction thread.
The same issue also happens for 1:1 DM expense and when leaving thread.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/584f4ce1-2dc5-4536-ae9d-04e30933b03e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173629ca2a87d3e9d</li>
        <li>Upwork Job ID: 1829627147990471781</li>
        <li>Last Price Increase: 2024-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103785367</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by luacmartins** [comment] 2024-08-30 21:08
I'm having issue building the iOS app at the moment. Adding external label to get contirbutors help

**Comment by struc** [comment] 2024-09-01 08:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace chat content is hidden after navigating away two or more levels deep then go back to the chat page, like viewing expenses report and clicking one of the expenses.
It also happens when adding a banking account

### What is the root cause of that problem?

The chat view is initially hidden because of
https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/home/report/ReportActionsList.tsx#L167

However the animation will not run the second time since it does not have `isFocused` as a dependency.

https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/home/report/ReportActionsList.tsx#L303-L310

### What changes do you think we should make in order to solve the problem?
Add isFocused as a dependency to force a re-render, and reset the opacity to 0 before the running the animation.
```typescript
    useEffect(() => {
      opacity.value = 0;
      // eslint-disable-next-line react-compiler/react-compiler
      opacity.value = withTiming(1, {duration: 100});
    }, [opacity, isFocused]);

```


### What alternative solutions did you explore? (Optional)
Remove the animation, I think 100ms is hardly noticeable to the user.

https://github.com/Expensify/App/blob/fc849dda35628b8c6c8d6edfa66dd31b257e8e7a/src/pages/home/report/ReportActionsList.tsx#L303-L305

https://github.com/user-attachments/assets/803fb7cf-e43d-49e0-a5a2-8a49dc246e71

**Comment by hungvu193** [comment] 2024-09-02 15:05
> @hungvu193 could you please take a look at the proposal above?

I'm still trying to run native code, I tried to clean everything, upgrade xcode, mac version, but still no luck :(. If this is urgent please re-assign.

**Comment by struc** [comment] 2024-09-02 16:05
@hungvu193 if it helps this [my current setup](https://gist.github.com/struc/e2b0db8a8ceae1ac81c10be4e4dd11e0)
It did worked out of the box, though I did not have much luck with Xcode 14 and/or MacOS older than 14.

**Comment by hungvu193** [comment] 2024-09-02 16:08
> @hungvu193 if it helps this is [my current setup](https://gist.github.com/struc/e2b0db8a8ceae1ac81c10be4e4dd11e0) It worked out of the box, though I did not have much luck with Xcode 14 and/or MacOS older than 14.

Thanks. I'll give that a try.

**Comment by roryabraham** [comment] 2024-09-02 18:06
@OfstadC the automation got confused here. I reassigned to @ishpaul777 as the C+, not the contributor role.

**Comment by roryabraham** [comment] 2024-09-02 18:20
@struc are you in our slack room? We're discussing this issue in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1725300015155669)

**Comment by struc** [comment] 2024-09-02 18:47
> @struc Can you please point to offending PR, these LOC in proposal seems to be there from a while

@ishpaul777 yes, it's over a year old
https://github.com/Expensify/App/pull/18073/files#diff-9ac76d645ad53156c86195c1a8f5adb3bb9b71f78351e43c4e1b6d6896921c4eL84

I think it was not noticed before because it is only reproducible on iOS and the user has to navigate two pages or more for it to show up.

**Comment by struc** [comment] 2024-09-02 18:48
> @struc are you in the #expensify-open-source slack room? We're discussing this issue in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1725300015155669)

No, I am not on the channel, I have sent an email to be invited.

**Comment by struc** [comment] 2024-09-02 18:57
@ishpaul777  No, I have not tried yet on production, I will check now.

**Comment by struc** [comment] 2024-09-02 19:09
Yes, I believe so.

**Comment by roryabraham** [comment] 2024-09-02 19:38
@struc this is a pretty urgent issue because it's the last one we need to fix before I can deploy. Let's try to get a PR up ASAP

**Comment by struc** [comment] 2024-09-02 19:40
@roryabraham Please give 5 minutes or so, I am creating the PR now.

**Comment by roryabraham** [comment] 2024-09-02 22:57
Verified that this is fixed on staging ✅

**Comment by OfstadC** [comment] 2024-09-09 13:15
https://www.upwork.com/ab/applicants/1833130608126333165/job-details

@struc Could you you please link me your Upwork profile as I wasn't able to find it? Thank you!

**Comment by struc** [comment] 2024-09-09 13:22
@OfstadC Here is the link https://www.upwork.com/freelancers/~01b7e0705471825edf

**Comment by OfstadC** [comment] 2024-09-09 13:24
Thanks @struc! Could you accept [this offer ](https://www.upwork.com/nx/wm/offer/103880537)? Then I can issue payment😃

**Comment by OfstadC** [comment] 2024-09-09 13:26
## Payment Summary 
- @struc paid $250 via Upwork
- @ishpaul777 paid $250 via Upwork

**Closed** 2024-09-09 18:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
