### ISSUE TITLE
Web -  App does not focus on room name field when opened using deep link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22973] opened 2023-07-16 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open existing room or create new room
3. Click on room header to open room details page
4. Click on settings
5. Click on Room name, observe that room name field is in focus
6. Copy the URL and go back to home page
7. Paste the URL in browser and click enter to visit
8. Observe that room name field is not in focus

## Expected Result:
App should keep room name field in focus whenever that page is visited

## Actual Result:
App does not keep room name field in focus when we visit the page using deeplink

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0141ea75-01d4-4e09-b935-8ccedd52c903

https://github.com/Expensify/App/assets/93399543/f634f05f-d2ee-4853-86d0-a74df5992694

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689419446304309
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-07-16 12:32
Same regression from https://github.com/Expensify/App/pull/22621

**Comment by bfitzexpensify** [comment] 2023-07-18 17:41
OK, I can't reproduce in Chrome, but I can in Safari. Posting in https://github.com/Expensify/App/issues/22271

**Comment by bfitzexpensify** [comment] 2023-07-18 17:56
OK, this was discussed [here](https://github.com/Expensify/App/pull/22621#discussion_r1260166393) and was deemed not to be an issue. I agree with the thinking there, so let's close this out.

**Closed by bfitzexpensify** 2023-07-18 17:56 UTC
Labels: Daily, Bug
