### ISSUE TITLE
New Room - No limit to text for Welcome message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20137] opened 2023-06-03 23:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any Expensify account
3. Go to FAB button -> Create New Room
4. Go to Settings -> Welcome message
5. Enter the long text for Welcome message

## Expected Result:
There is a limit for entering text

## Actual Result:
No limit to text for Welcome message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9883b11b-d778-42a7-b351-0254504dffe0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-06-04 02:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New Room - No limit to text for Welcome message.
### What is the root cause of that problem?
We already have `maxLength` for the text input which equal normal chat message length, but we have empty function to show the error.

https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/ReportWelcomeMessagePage.js#L69

### What changes do you think we should make in order to solve the problem?
We need to handle validate callback to show the errors after click save.
```javascript
const validate = (values) => {
    const errorFields = {};
    const commentLength = ReportUtils.getCommentLength(values.welcomeMessage);

    if (commentLength > CONST.MAX_COMMENT_LENGTH) {
        errorFields.welcomeMessage = props.translate('common.error.characterLimit', {limit: CONST.MAX_COMMENT_LENGTH});
    }
    return errorFields;
}
```

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-06-05 21:31
@dhairyasenjaliya - are you flagging that this is a dupe of GH https://github.com/Expensify/App/issues/18647?

**Comment by alexpensify** [comment] 2023-06-07 20:34
@dhairyasenjaliya - when you get a chance, can you review my last comment? Thank you!

**Comment by alexpensify** [comment] 2023-06-08 23:01
Got it, so it sounds like we should close this GH. I'm going to close for now then.

**Closed by alexpensify** 2023-06-08 23:01 UTC
Labels: Daily, Bug
