### ISSUE TITLE
[$500] Scan - Green dot is displayed for workspace chat that has failed Scan preview with red dot

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31031] opened 2023-11-07 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30231
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Request money > Scan
4. Create a scan request
5. Fail the smartscanning by manually entering the amount
6. Return to the workspace chat

## Expected Result:
A red dot will be displayed for the workspace chat due to the failed scanning

## Actual Result:
A green dot is displayed for the workspace chat with failed scanning, while the workspace chat shows Scan preview with a red dot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/13b64363-71a8-4361-a4ea-4b48ecb03fd5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fd93f0c943296dc</li>
        <li>Upwork Job ID: 1721992037831143424</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-11-07 22:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green dot is displayed for workspace chat that has a preview error. 

### What is the root cause of that problem?
An error in the scan preview will not be considered as an error for the Chat Reports (1:1 or Workspace chats) as we only check for `report.errors` and `report.errorFields` in the [getAllReportErrors](https://github.com/Expensify/App/blob/c2e40423ac71fa67e65b570342c39e4c2b25a46f/src/libs/OptionsListUtils.js#L339) function that sets the `brickRoadIndicator` value for the LHN items. 

`getAllReportErrors` also perform some other checks when to check if the report `isTransactionThread` ,`isIOUReport` or `isExpenseReport` and none of these will work for the chat reports. 

Now, since the chat report is considered error free, this line here https://github.com/Expensify/App/blob/c2e40423ac71fa67e65b570342c39e4c2b25a46f/src/components/LHNOptionsList/OptionRowLHN.js#L119 will call `requiresAttentionFromCurrentUser`

Which will return true due to the report having an outstanding action in the case of pending payment. `hasOutstandingChildRequest`
https://github.com/Expensify/App/blob/c2e40423ac71fa67e65b570342c39e4c2b25a46f/src/libs/ReportUtils.js#L1445

Notice that now if we pay the request, the green dot will disappear as the `hasOutstandingChildRequest` is no longer present. 

### What changes do you think we should make in order to solve the problem?
If we want to show the red dot in case of a scan error. We need to perform the same logic used in the `ReportPreview.js`

For each report action, we need to find the `iouReportID` from the preview. Using 
`ReportActionUtils.getIOUReportIDFromReportActionPreview` and then check if that `iouReport` has a missing scan field using` const hasMissingField = ReportUtils.hasMissingSmartscanFields(iouReportID)`

### What alternative solutions did you explore? (Optional)

N/A

**Comment by DylanDylann** [comment] 2023-11-08 01:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan - Green dot is displayed for workspace chat that has failed Scan preview with red dot

### What is the root cause of that problem?
Let's see the logic to get error of LHNOptionRow we only get error of that report, that report actions and parent report action, we don't get error of child report

https://github.com/Expensify/App/blob/c2e40423ac71fa67e65b570342c39e4c2b25a46f/src/libs/OptionsListUtils.js#L339
### What changes do you think we should make in order to solve the problem?
We need to add logic to get error of child report like this 
```
 const reportActionErrors = _.reduce(
        reportActions,
        (prevReportActionErrors, action) => {
            if (action && !_.isEmpty(action.errors)) {
                _.extend(prevReportActionErrors, action.errors)
            }
            const childReportActions = lodashGet(allReportActions, [report.childReportID], {});
            const childReportActionErrors = _.reduce(
                childReportActions,
                (prevChildReportActionErrors, childAction) => {
                    const transactionID = lodashGet(childAction, ['originalMessage', 'IOUTransactionID'], '');
                    const transaction = allTransactions[`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`] || {};
                    if (TransactionUtils.hasMissingSmartscanFields(transaction)) {
                        _.extend(prevChildReportActionErrors, {smartscan: ErrorUtils.getMicroSecondOnyxError('report.genericSmartscanFailureMessage')});
                    }
                   return prevChildReportActionErrors
                },
                {},
            );
            return _.extend(prevReportActionErrors, childReportActionErrors)
        },
        {},
    );
```
It will check all report actions of child report and see that if there is any report action is error. 
We can add a condition to only run above logic if child report type is `expense`


One more thing, I want to suggest that we shouldn't display green dot if that request is scanning and there are no other request (only display green dot if the scan is successfull). To do that, in here
https://github.com/Expensify/App/blob/c2e40423ac71fa67e65b570342c39e4c2b25a46f/src/libs/actions/IOU.js#L167
we also need to set 
```
                hasOutstandingChildRequest: iouReport.total !== 0,
```
and also reset value in FailureData.

**Comment by akinwale** [comment] 2023-11-10 02:14
After reviewing the proposals, I recommend moving forward with @abdel-h66's [proposal](https://github.com/Expensify/App/issues/31031#issuecomment-1800332301) as the solution is simple and straightforward. @abdel-h66 The `optionItem` in `OptionRowLHN` already has an [`iouReportID`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L336) field, so there's no need to call `ReportActionUtils.getIOUReportIDFromReportActionPreview` to obtain the value.

@DylanDylann's proposed solution adds unnecessary complexity, and I imagine having to run a `_.reduce` on every option item in the LHN would cause some performance issues especially with accounts that have a large number of reports open.

🎀 👀 🎀 C+ reviewed.

**Comment by DylanDylann** [comment] 2023-11-10 03:06
@akinwale In [my proposal](https://github.com/Expensify/App/issues/31031#issuecomment-1800883035), I mean that 
in here
https://github.com/Expensify/App/blob/1928c95336e58bafed2357670c755123a35a4d94/src/libs/OptionsListUtils.js#L342-L347

we should update like that
```diff
const reportActionErrors = _.reduce(
        reportActions,
        (prevReportActionErrors, action) => {

            if (action && !_.isEmpty(action.errors)) {
                _.extend(prevReportActionErrors, action.errors)
            }
+     if (ReportUtils.hasMissingSmartscanFields(action.childReportID)) { // We can add a condition to only run this logic if + child report type is `expense`
+               _.extend(prevReportActionErrors, {smartscan: ErrorUtils.getMicroSecondOnyxError('report.genericSmartscanFailureMessage')});
+            }
           
            return prevReportActionErrors
        },
        {},
    );

```

**Comment by DylanDylann** [comment] 2023-11-10 03:08
> One more thing, I want to suggest that we shouldn't display green dot if that request is scanning and there are no other request (only display green dot if the scan is successfull)

@akinwale What do you think about this point?
cc @puneetlath

**Comment by puneetlath** [comment] 2023-11-10 21:26
Raised for discussion in an internal slack channel here: https://expensify.slack.com/archives/C036QM0SLJK/p1699651533409919

My opinion is that this actually isn't a bug, but we'll discuss and get back to you!

**Comment by DylanDylann** [comment] 2023-11-11 07:33
@puneetlath I can't access to Slack link, could you help to confirm [this point](https://github.com/Expensify/App/issues/31031#issuecomment-1805005976) in Slack. Thanks

**Comment by abdel-h66** [comment] 2023-11-11 14:43
I don't think we should show the red dot error for all type of actions. The `smartscan` error should only appear for Preview actions. Otherwise, it would be confusing if the user does not know where the error is coming from when opening the report with a red dot error.

**Comment by twisterdotcom** [comment] 2023-11-13 17:50
@puneetlath I think you landed on this being fine right? From the internal discussion:

> In this case the submitter and manager is the same person
> So I think it’s fine since they are getting both according to their dual role

**Comment by puneetlath** [comment] 2023-11-13 18:06
That's what I think yes. Thought it'd be good to have someone else in that thread agree with me 😄

**Comment by twisterdotcom** [comment] 2023-11-13 20:50
Ahah, I agree. Seems @JmillsExpensify does too.

**Comment by puneetlath** [comment] 2023-11-13 20:55
Sounds good. Closing!

**Closed by puneetlath** 2023-11-13 20:55 UTC
Labels: External, Daily, Help Wanted, Bug
