### ISSUE TITLE
[HOLD for payment 2023-11-06] [HOLD for payment 2023-11-02] [$500] iOS - IOU - Empty space below IOU preview in 1:1 DM after paying elsewhere

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30423] opened 2023-10-26 10:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.91-6

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. User A requests money from User B.
2. User B opens 1:1 DM with User A.
3. User B taps Pay elsewhere on the IOU preview.

## Expected Result:
There will be no empty space below IOU preview in 1:1 DM after paying elsewhere.

## Actual Result:
There is empty space below IOU preview in 1:1 DM after paying elsewhere.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/726605a4-ac48-418a-9b83-6758706ab84e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164ad99e31ac32a85</li>
        <li>Upwork Job ID: 1717495493237944320</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by izarutskaya** [comment] 2023-10-26 10:57
Not reproducible in production

https://github.com/Expensify/App/assets/115492554/aa884a56-75ce-49a9-9204-aa198565990f

**Comment by paultsimura** [comment] 2023-10-26 11:06
Just to add some context: the same happens when adding an attachment (the chat doesn't scroll to the end), and when removing an attachment – the space at the bottom remains.

**Comment by perunt** [comment] 2023-10-26 11:17
This stuff should be fixed with[ that changes ](https://expensify.slack.com/archives/C035J5C9FAP/p1695998111378719)
As a temporary solution, we can comment out fetching from the bottom, which causes that problem.

**Comment by iwiznia** [comment] 2023-10-26 15:52
I tested this on this branch https://github.com/Expensify/App/pull/30409 and can't reproduce the issue, so must've been caused by it.

**Comment by iwiznia** [comment] 2023-10-26 16:26
Asked here how to proceed https://expensify.slack.com/archives/C035J5C9FAP/p1698335858869399?thread_ts=1695998111.378719&cid=C035J5C9FAP

**Comment by roryabraham** [comment] 2023-10-26 19:03
Investigating a fix

**Comment by roryabraham** [comment] 2023-10-26 20:53
Confirmed this will be fixed by https://github.com/Expensify/App/pull/30461

**Comment by NicMendonca** [comment] 2023-11-02 19:39
> @narefyev91 does not require payment (Contractor)

all set here!

**Closed by NicMendonca** 2023-11-02 19:39 UTC
Labels: External, Engineering, Daily, Monthly, Awaiting Payment, Bug
