### ISSUE TITLE
[$500] BA - Bad performance of app after changing the company website to URL that ends with a dot

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35124] opened 2024-01-25 02:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** No, unable to check prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the account must be an Expensifail account and have created a Workspace
1. Go to Settings > Workspaces > Select Workspace > Bank account
2. Select add with Plaid and enter credentials
3. On Company information page, fill out the form as usually until you fill the date
4. Go back to Company website field and change it to something that ends with a dot, i.e.
"https://www.applause.expensifail.co.com."/
5. Try to keep filling the form, change the date

## Expected Result:
The app should keep running as usual, allowing the user to continue filling out the form and submit

## Actual Result:
The app has a slow behavior when trying to change date, and is not possible to submit the form

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0e764c8c-1624-456b-a795-a0fae5731f98

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb30b84358fd8f55</li>
        <li>Upwork Job ID: 1758394448509222912</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2024-01-25 05:53
Interesting - though I imagine this is a regex thing so probably also happening on prod. Going to remove the blocker

**Comment by roryabraham** [comment] 2024-02-06 21:30
@lanitochka17 requesting retest to see if this is still reproducible

**Comment by lanitochka17** [comment] 2024-02-07 14:18
Issue reproducible on the build 1.4.38-0


https://github.com/Expensify/App/assets/78819774/8becdb0a-7afa-4f06-9f8a-6a950bfed4d4

**Comment by roryabraham** [comment] 2024-02-16 07:34
Seems like this can be made external

**Comment by binumarcodes** [comment] 2024-02-16 09:18
Contributor details
Your Expensify account email: abdulrahmanbinumar178@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~01cc73b9bb1a693c5f

**Comment by roryabraham** [comment] 2024-02-20 19:36
Hi @binumarcodes. We have a proposal template [here](https://github.com/Expensify/App/blob/4f103255b77271d60666d39a0670104d113c44b5/contributingGuides/PROPOSAL_TEMPLATE.md). Can you please use that for this and any other proposals on `Help Wanted` issues in this repo?

**Comment by roryabraham** [comment] 2024-02-27 00:17
happy to assign to you @shubham1206agra since you expressed interest

**Comment by roryabraham** [comment] 2024-02-27 00:21
@binumarcodes yes, that's right. we need proposals to use the template. If you're unsure what I mean, look through some of the issues in this repo; there are plenty of examples to follow.

**Comment by roryabraham** [comment] 2024-02-27 08:42
I'm moving this back to external

**Comment by roryabraham** [comment] 2024-02-27 08:45
put out a call in #newdot-performance as well: https://expensify.slack.com/archives/C05LX9D6E07/p1709023485700669

**Comment by mvtglobally** [comment] 2024-02-27 16:15
Issue is reproducible during KI retests.

**Comment by gedu** [comment] 2024-02-28 13:43
I am from Callstack - I can take a look at this

**Comment by roryabraham** [comment] 2024-02-28 16:56
thanks @gedu

**Comment by roryabraham** [comment] 2024-03-06 06:47
great, I had seen markups but didn't realize that the new bank account forms were already implemented. Closing this out

**Closed by roryabraham** 2024-03-06 06:47 UTC
Labels: External, Engineering, Daily, Bug
