### ISSUE TITLE
[$1000] Chat- When reacting to a message, ask the other user for money, your reaction does not appear

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23315] opened 2023-07-20 21:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. First open two accounts with different users, in this case of user A and user B
2. Start chat and click in the plus sign, the user A
3. Click Request money the user B
4. Now with user B reacts to the money request message

## Expected Result:
That the user A view the reaction of user B at the exact moment

## Actual Result:
User A, to see user B's reaction, have to update the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8aa76606-c58b-43bf-871e-db5b3b1701f7

https://github.com/Expensify/App/assets/93399543/b8908fea-65ba-4ca6-8c35-2cbf45d932f6

https://github.com/Expensify/App/assets/93399543/f4fab24f-10d7-44a9-94e8-5d65d6705110

https://github.com/Expensify/App/assets/93399543/be67ff98-f10d-455f-b048-21f22beb809c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689862826572919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b7dc3e4e47914f3</li>
        <li>Upwork Job ID: 1683972426590973952</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-20 22:13
Looks like backend is not sending the socket event

**Comment by ygshbht** [comment] 2023-07-20 22:22
> 📣 @ygshbht! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

You already do. Restating again nonetheless

Contributor details
Your Expensify account email: ygshbht@gmail.com
Upwork Profile Link: [Link](https://www.upwork.com/freelancers/~01ca41cc1d47038084)

**Comment by twisterdotcom** [comment] 2023-07-25 22:48
Had some OOO followed by some unexpected OOO today. Just getting to this now.

**Comment by s-alves10** [comment] 2023-07-26 14:13
Not reproducible. Please clearly describe the reproduction steps

**Comment by s77rt** [comment] 2023-07-26 21:52
@s-alves10 Can you please ask for better reproduction steps in the corresponding slack thread https://expensify.slack.com/archives/C049HHMV9SM/p1689862826572919

**Comment by s77rt** [comment] 2023-07-31 18:33
Not overdue. Still looking for proposals (and possibly reproduction confirmation)

**Comment by mvtglobally** [comment] 2023-08-02 16:47
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment] 2023-08-03 21:19
Closing this: https://expensify.slack.com/archives/C049HHMV9SM/p1691097564955689?thread_ts=1689862826.572919&cid=C049HHMV9SM

**Closed by twisterdotcom** 2023-08-03 21:19 UTC
Labels: External, Daily, Help Wanted, Bug
