### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000]  Scan IOU - 1:1 DM disappears after opening IOU report page when Scan IOU is created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25770] opened 2023-08-23 14:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25613
## Action Performed:
1. Go to staging.new.expensify,com
2. Go offline
3. Create a Manual IOU with a user with no conversation history
4. Open 1:1 DM and IOU report page. Verify that both reports are not missing in LHN
5. Create a Scan IOU with another user with no conversation history
6. Open 1:1 DM and IOU report page

## Expected Result:
1:1 DM created in Step 5 will not disappear from LHN after opening IOU report page

## Actual Result:
1:1 DM created in Step 5 disappears from LHN after opening IOU report page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5e4f0ad4-99a4-4ee4-8993-9eecf2ed5ab4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team/

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016eaa15aa0f40ecf9</li>
        <li>Upwork Job ID: 1696697017540784128</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>StevenKKC | Contributor | 26617203</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-08-23 15:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan IOU - 1:1 DM disappears after opening IOU report page when Scan IOU is created offline

### What is the root cause of that problem?
If create a Scan IOU with a user with no conversation history, CREATED action and REPORTPREVIEW action for the chatReport are generated.
https://github.com/Expensify/App/blob/ebb6d3394df76aadfe04b84c52c2fa57665ba148/src/libs/actions/IOU.js#L418
https://github.com/Expensify/App/blob/ebb6d3394df76aadfe04b84c52c2fa57665ba148/src/libs/actions/IOU.js#L438
When build a REPORTPREVIEW action, we are setting `whisperedToAccountIDs` if has receipt.
https://github.com/Expensify/App/blob/ebb6d3394df76aadfe04b84c52c2fa57665ba148/src/libs/ReportUtils.js#L2065

So REPORTPREVIEW action is treated as whisper action, and then the last visible action for chat report is empty.
https://github.com/Expensify/App/blob/5d1d5f15a2f195a256d54aecb21c1c66d994f726/src/libs/ReportActionsUtils.js#L365

Therefore, `lastMessageText` for chat report is empty, and then chat report is treated as empty chat and disappears from LHN.

### What changes do you think we should make in order to solve the problem?
We can check whether wispher action is REPORTPREVIEW action or not in `ReportActionUtils.shouldReportActionBeVisibleAsLastAction`
```js
    return shouldReportActionBeVisible(reportAction, reportAction.reportActionID) && !(isWhisperAction(reportAction) && !isReportPreviewAction(reportAction)) && !isDeletedAction(reportAction);
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by mallenexpensify** [comment] 2023-08-30 01:31
Was able to reproduce, no idea why it's happening. 
https://github.com/Expensify/App/assets/22508304/525e2938-6d9c-4319-88b4-6d5fee6851cb

@rushatgabhane, if you agree this can be External, can you review @StevenKKC 's proposal above? Thx

**Comment by mallenexpensify** [comment] 2023-09-04 03:05
@rushatgabhane please review @StevenKKC 's proposal above

@sophiepintoraetz  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by mallenexpensify** [comment] 2023-09-11 06:18
@amyevans , plz review the below when you have a min
- https://github.com/Expensify/App/issues/25770#issuecomment-1690222072

**Comment by amyevans** [comment] 2023-09-11 19:25
Proposal looks good!

**Comment by StevenKKC** [comment] 2023-09-11 20:51
@rushatgabhane PR https://github.com/Expensify/App/pull/27197 is ready for review.

**Comment by amyevans** [comment] 2023-09-12 13:35
Self assigned and will review later today. Thanks!

**Comment by mallenexpensify** [comment] 2023-09-21 05:15
Issue reporter: Applause
Contributor: @StevenKKC paid $1500 via Upwork, inc. 50% urgency bonus
Contributor+: @rushatgabhane is due $1500 via NewDot

@rushatgabhane can you please fill out the BZ checklist above?

**Comment by mallenexpensify** [comment] 2023-09-29 16:03
@rushatgabhane please fill out the BZ checklist so I can close this

**Comment by amyevans** [comment] 2023-10-03 23:58
Bump @rushatgabhane

**Comment by JmillsExpensify** [comment] 2023-10-07 14:50
$1,500 payment approved for @rushatgabhane based on BZ summary.

**Comment by amyevans** [comment] 2023-10-09 14:38
@rushatgabhane friendly bump on the checklist, I think that's all that remains before we can close 🙏

**Comment by mallenexpensify** [comment] 2023-10-13 22:25
@rushatgabhane please finish the BZ checklist then we can close, I'll ping ya in NewDot too 
https://github.com/Expensify/App/issues/25770#issuecomment-1734618038

**Comment by mallenexpensify** [comment] 2023-10-16 18:18
Thanks @rushatgabhane 
https://github.com/Expensify/Expensify/issues/326587

**Closed by mallenexpensify** 2023-10-16 18:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
