### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] Hybrid iOS app –IOU –Approval button is missing after payment of the report with hold expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50932] opened 2024-10-16 18:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.49-0
**Reproducible in staging?:** N
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was repro when executing this PR:** https://github.com/Expensify/App/pull/49910
**Email or phone of affected tester (no customers):** applausetester+jp_1151024@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to Hybrid app
2. Log in with your Approver account
3. As employee Go to the room with the two expenses
4. As employee: hold one expense
5. As Approver: Approve just the pending amount
6. As Approver: back to room by click to the header

## Expected Result:
The approval button should load after payment of the report with hold expense

## Actual Result:
The approval button is missing after payment of the report with hold expense

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/67048841-44e5-4b1e-b58b-72f35b0f159f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848434780732463293</li>
        <li>Upwork Job ID: 1848434780732463293</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104595665</li>
<li>ikevin127 | Contributor | 104595666</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by IuliiaHerets** [comment] 2024-10-16 18:18
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment] 2024-10-19 01:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hybrid iOS app –IOU –Approval button is missing after payment of the report with hold expense
### What is the root cause of that problem?
Right here we check if the unheld total amount is not equal to 0 then we will show the approve button
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/libs/actions/IOU.ts#L6990-L6992
Since we hold the expense the unheld total amount become 0 which will not show the approve button
### What changes do you think we should make in order to solve the problem?
We should remove the `unheldTotalIsZero` variable and remove the return check condition
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/libs/actions/IOU.ts#L6990-L6992

**Comment by ikevin127** [comment] 2024-10-22 03:49
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Approval button is missing after payment of a report with two expenses, one on hold and the other not, once Approving the expense that's not on hold -> the Approve button is missing for the held expense once Submitted.

### What is the root cause of that problem?

- The [logic](https://github.com/Expensify/App/blob/b732301c0011ae982744bf58c27c30fc3b62f6eb/src/libs/actions/IOU.ts#L6991-L6993) which causes this behaviour was added by PR https://github.com/Expensify/App/pull/50817 on purpose in order to solve issue https://github.com/Expensify/App/issues/48590 where the `Approve` button was showing scan expense while still scanning.

This is what is causing our issue because the [logic](https://github.com/Expensify/App/blob/b732301c0011ae982744bf58c27c30fc3b62f6eb/src/libs/actions/IOU.ts#L6991-L6993) added by the above mentioned PR is deliberately hiding `Approve` in our case too, even though the steps in our issue don't mention scan expenses but rather manual expenses.

### What changes do you think we should make in order to solve the problem?

Given the RCA, we cannot simply remove the logic that the above mentioned PR added because it would revert the fix for which the logic was added as fix for [this issue](https://github.com/Expensify/App/issues/48590):

> Approver should not be able to approve scanning expense

Here's what only removing the mentioned logic would look like for the other issue vs how what I'm proposing would look:

| Only remove logic | Replace logic (below proposal) |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/c489cce3-93d7-496c-bd15-9f29ac57f280"> | <video src="https://github.com/user-attachments/assets/2da13c1c-1a73-45c3-a1aa-958313aea332"> |

**Therefore here's my proposal:**
1. Remove the `unheldTotalIsZero` logic implementation from here:

https://github.com/Expensify/App/blob/179d0f05e40744d08858778cf83aadf392334ad8/src/libs/actions/IOU.ts#L6991-L6993

2. Replace the above implementation with:

```ts
    let isTransactionBeingScanned = false;
    const reportTransactions = TransactionUtils.getAllReportTransactions(iouReport?.reportID);
    for (const transaction of reportTransactions) {
        const hasReceipt = TransactionUtils.hasReceipt(transaction);
        const isReceiptBeingScanned = TransactionUtils.isReceiptBeingScanned(transaction);

        // If a transaction has receipt (scan) and its receipt is being scanned, flag it
        if (hasReceipt && isReceiptBeingScanned) {
            isTransactionBeingScanned = true;
        }
    }

    return isCurrentUserManager && !isOpenExpenseReport && !isApproved && !iouSettled && !isArchivedReport && !isTransactionBeingScanned;
```

This ensures we don't show `Approve` for a scan expense that's still scanning, while fixing our issue of the `Approve` button not showing at all.

**Comment by jjcoffee** [comment] 2024-10-22 07:44
@ikevin127's [proposal](https://github.com/Expensify/App/issues/50932#issuecomment-2428153451) LGTM! I agree that we can't just remove the `unheldTotalIsZero` as the other [proposal](https://github.com/Expensify/App/issues/50932#issuecomment-2423454830) suggests. Also, I'm guessing this isn't limited to the hybrid app.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by M00rish** [comment] 2024-10-22 08:01
Hi guys, I just want to note that this [PR ](https://github.com/Expensify/App/pull/50817)was just pushed to production few hours ago and the issue was opened a few days ago, so maybe it has to do with something else I think..., also are not we supposed to unhold the expense before approving or paying? 

thanks

**Comment by ikevin127** [comment] 2024-10-22 18:14
@marcochavezf Looks like @M00rish's PR is still within the regression period as it was deployed to staging only 4 days ago - so they might want to fix this one as a follow-up.

**Comment by jjcoffee** [comment] 2024-10-23 12:01
@ikevin127 I think the RCA in your proposal goes back to https://github.com/Expensify/App/pull/49910 since there they optimistically added `unHeldTotal = 0`, which would then trigger the `unheldTotalIsZero` logic added in the other PR.

https://github.com/Expensify/App/blob/d82a253725c7a084a6b7cd7a2434dcd0d50fd8ab/src/libs/actions/IOU.ts#L6527-L6533

Is it possible to reproduce without the changes in https://github.com/Expensify/App/pull/50817? I'm wondering if the RCA might go a bit deeper.

**Comment by ikevin127** [comment] 2024-10-24 01:01
@jjcoffee I tried reproducing this issue with both https://github.com/Expensify/App/pull/49910 & https://github.com/Expensify/App/pull/50817 changes reverted and with that, our issue is not reproducible anymore:

https://github.com/user-attachments/assets/5d83c84c-543e-4062-9cef-eeac4256070b

You are right about the offending PR, looks like the `unHeldTotal = 0` addition is the root cause for our issue.

**Comment by jjcoffee** [comment] 2024-10-25 09:03
@marcochavezf I think we're good to proceed with @ikevin127's [proposal](https://github.com/Expensify/App/issues/50932#issuecomment-2428153451) still.

**Comment by marcochavezf** [comment] 2024-10-25 19:20
Ok sounds good, thanks for the resolution. Assigning @ikevin127 🚀

**Comment by ikevin127** [comment] 2024-10-25 19:23
PR will be ready for review in ~ 1 hour.

**Comment by ikevin127** [comment] 2024-11-01 21:10
♻️ **Status update**: Currently awaiting @marcochavezf's input on the PR to determine whether we're going to merge or not.

**Comment by ikevin127** [comment] 2024-11-18 21:41
cc @sonialiap for visibility 🙏

**Comment by ikevin127** [comment] 2024-11-19 05:23
cc @sonialiap for visibility as this was due on 18th

**Comment by jjcoffee** [comment] 2024-11-19 09:07
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by sonialiap** [comment] 2024-11-19 09:13
Payment summary:
- @jjcoffee $250 - payment will be released once the [checklist](https://github.com/Expensify/App/issues/50932#issuecomment-2485103619) is completed :)
- @ikevin127 $250 - paid in upwork ✔️ 

I was OOO on the 18th

**Comment by jjcoffee** [comment] 2024-11-19 09:44
@sonialiap Checklist complete! :pray:

**Comment by sonialiap** [comment] 2024-11-19 09:47
Thanks Joel! Payment completed

**Closed** 2024-11-19 09:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
