### ISSUE TITLE
Dev: Web - User can flag a message on admins only room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22237] opened 2023-07-05 01:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with userA account
2. Go to the “New room” section
3. Enter room name and select userA workspace
4. Select visibility to “Public”
5. Click on “Create room”
6. Send some messages in room chat
7. Go to the room detail
8. Share code > Copy URL to clipboard
9. Go back and click on Settings > Who can post
10. Select Admin only
11. Open other browser and login with userB account
12. Join the room by pasting URL
13. Hover or right click on userB comment
14. Verify that there's no Flag as offensive option.
15. Click on 'reply in thread' icon
16. Hover over the threaded message & click on 'flag as offensive' icon
17, Click on 'Harassment' link

## Expected Result:
 'Flag as offensive' option shouldn't be available on in the threaded message

## Actual Result:
'flag as offensive' option is available & system throws a technical error message (Auth CreateReprtAction returned an error) on flagging the message with harassment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.36-4
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d91ec0cf-f2cf-4e5b-8340-88b548b8ade6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688506126888419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment] 2023-07-05 06:51
> It's fixed here: https://github.com/Expensify/App/pull/22099

@hungvu193 flagging from a thread scenario doesn't seem to be handled on the pr you have linked.

**Comment by lschurr** [comment] 2023-07-07 20:23
Are we still working on this one? @allroundexperts - Should it be assigned to @hungvu193?

**Comment by lschurr** [comment] 2023-07-10 16:03
@puneetlath adding Eng for another set of eyes. Should I be adding External to this one or do we need to fix internally?

**Comment by puneetlath** [comment] 2023-07-10 16:06
This will need to be fixed internally. 

But we need to decide what the ideal behavior should be. Whether we allow a non-admin to flag messages in an admin-only chat. I'm thinking that we should allow a non-admin to flag messages, even though they aren't allowed to post in the channel. That would be a good discussion for you to start in Slack @lschurr. And I would recommend cc'ing @dangrous and @amyevans in that discussion since they worked on the moderations/admin-only features.

**Comment by dangrous** [comment] 2023-07-10 18:13
Ha! We have [the opposite bug](https://github.com/Expensify/App/issues/22311) also reported here.

[Slack conversation](https://expensify.slack.com/archives/C04QEB4MJEQ/p1688764123182969) to determine expected behavior is ongoing - hop in! Personally I think logged-in users should be able to flag anything they can see

**Comment by Natnael-Guchima** [comment] 2023-07-10 18:16
They are not opposite. They user roles are different on both reports. On the one you have shared a link to the user role is an admin, and in this issue the user role is member. The admin should be able to do anything since, they have a a write access on admins only access type.

**Comment by lschurr** [comment] 2023-07-12 17:12
Where are we at on this one @dangrous @puneetlath - Did we decide this issue is a bug or expected behavior?

**Comment by puneetlath** [comment] 2023-07-12 17:14
Based on the thread, it looks like it's currently the expected behavior but @jasperhuangg is opening a separate issue to update moderation for some more cases. So I think this is fine to close.

**Comment by lschurr** [comment] 2023-07-12 17:23
Cool, thanks! Going to close.

**Closed by lschurr** 2023-07-12 17:23 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
