### ISSUE TITLE
Web -  Completed/Uncompleted task checkbox should have the tooltips

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22022] opened 2023-07-01 18:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the web
2. Open a chat
3. Create a task if doesn't have any tasks before
4. Hover on the check box
5. Check if the Completed/Uncompleted task checkbox has the tooltip

## Expected Result:
It should have the tooltips for Completed/Uncompleted task checkbox

## Actual Result:
 It doesn't have tooltips for Completed/Uncompleted task checkbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/59dd399e-e0f8-4df3-848b-eee6823b7d24

https://github.com/Expensify/App/assets/93399543/afec6121-b79c-4870-9489-b0b8a77f3003

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gemma0110
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688203647874229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nvloc120** [comment] 2023-07-01 23:53
**Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
Completed/Uncompleted task checkbox should have the tooltips
**What is the root cause of that problem?**
We currently don't have tooltips under task checkbox for both completed and uncomplete states
**What changes do you think we should make in order to solve the problem?**
Add tooltips to task checkbox based on task status.
If the task status is "Uncomplete": we display the tooltip as "Complete"
If the task status is "Completed": we display the tooltip as "Reopen"
**What alternative solutions did you explore? (Optional)**

**Comment by nvloc120** [comment] 2023-07-01 23:56
Contributor details
Your Expensify account email: nvloc120@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013f9c6f3834040e33

**Comment by gemma0110** [comment] 2023-07-02 00:07
Contributor details
Your Expensify account email: miumiu.kyo2k@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01957ad64167a78c0f

**Comment by JmillsExpensify** [comment] 2023-07-05 12:43
Slammed with bug reports. I'll close the loop on these today.

**Comment by JmillsExpensify** [comment] 2023-07-12 12:43
I don't agree that the checkbox should have a tooltip. Closing. Please create an issue in open-source if you disagree.

**Closed by JmillsExpensify** 2023-07-12 12:43 UTC
Labels: Daily, Overdue, Bug

**Comment by nvloc120** [comment] 2023-07-12 12:46
@JmillsExpensify As a new user, when I see the Complete/UnComplete checkbox then I don't know what it is. That's better to have a tooltip to tell users know what it does.
