### ISSUE TITLE
[HOLD for payment 2023-09-07] [$1000] Chat - Opened chat does not show up in LHN when LHN is loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24596] opened 2023-08-15 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24204
## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with account with many conversations
3. Copy link to any chat
4. Log out
5. Navigate to the link in Step 1
6. Log in
7. Right after the chat is loaded, return to LHN

## Expected Result:
The opened chat in Step 6 will appear in LHN while the rest of the chats is loading

## Actual Result:
The opened chat in Step 6 does not appear in LHN even though it is opened prior

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dc16f2e6-b2d2-49c4-af58-52d67c2525e9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d3358a3bd902de6</li>
        <li>Upwork Job ID: 1691926354859388928</li>
        <li>Last Price Increase: 2023-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26165190</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-08-15 19:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Opened chat doesn't show up in LHN when LHN is loading

### What is the root cause of that problem?

Please check the below code
https://github.com/Expensify/App/blob/8472f035a0556c9d611e23fec6c9e1c053b1e467/src/pages/home/sidebar/SidebarLinks.js#L231-L251

As you can see, we show skeleton when `props.isLoading` is true, or show report list. Before this [PR](https://github.com/Expensify/App/pull/24204), `props.isLoading` is `true` when reports are not empty, so if any report was loaded, we don't show skeleton. We show report list(with preloaded) while loading all reports. But now, `isLoading` is false and `this.props.report` is also empty because `currentReportID` is `undefined`. So skeleton is shown full page.

This is the root cause

### What changes do you think we should make in order to solve the problem?

**Solution 1**
Replacing the `this.props.isLoading` condition above with the `this.props.isLoading && !this.props.optionListItems.length` would give the exactly same result as production


<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by ArekChr** [comment] 2023-08-16 08:49
> cc @tienifr @ArekChr the PR #24204 seems to have caused this regression according to @s-alves10 , can you help confirm that?
> 
> Thanks @s-alves10 for the help investigating.

@aldo-expensify Yes, this PR caused regression

**Comment by yuwenmemon** [comment] 2023-08-16 21:06
@tienifr any ETA on when you expect to have a PR up? If it's not going to be within the next few hours then should we revert the [offending PR](https://github.com/Expensify/App/pull/24204)?

**Comment by s-alves10** [comment] 2023-08-16 21:10
I can create a PR according to https://github.com/Expensify/App/issues/24596#issuecomment-1679450635 in 2~3 hours

**Comment by yuwenmemon** [comment] 2023-08-16 21:33
@s-alves10 great - you're hired.

**Comment by yuwenmemon** [comment] 2023-08-16 21:45
@s-alves10 please raise the PR with urgency as this is a deploy blcoker 🚀 thanks!

**Comment by s-alves10** [comment] 2023-08-16 23:11
Will create a PR in 2 hrs

**Comment by s-alves10** [comment] 2023-08-17 01:19
@narefyev91 

[PR](https://github.com/Expensify/App/pull/25159) is ready for review

**Comment by yuwenmemon** [comment] 2023-08-17 01:39
After looking at this again I would say it's not a deploy blocker and so will let this PR get reviewed at a normal pace by @narefyev91 and @grgia 

Thanks for the speedy work @s-alves10!

**Comment by s-alves10** [comment] 2023-08-17 06:12
@tienifr 

I think we need to show all existing reports while loading the whole chats. Please explain why you're assuming that we have at most one existing report. The order isn't a problem, I think. We will show the existing chats in order, you know it.

Solution 1 can be an option in [my proposal](https://github.com/Expensify/App/issues/24596#issuecomment-1679450635).
Expecting feedback from reviewers

cc @narefyev91 @yuwenmemon

**Comment by s-alves10** [comment] 2023-08-17 06:28
@tienifr 

I think showing all existing reports is what the previous version does. You're trying to show only one report, but this isn't a solution anyway, I think. Let me check your case

**Comment by narefyev91** [comment] 2023-08-17 07:43
@yuwenmemon @aldo-expensify We get in a situation where we have 2 open PR's to the same fix
PR from @tienifr already tested by @ArekChr and approved.
I can also start my part for PR from @s-alves10  - but do not want to have double work - and also based on Expected result "The opened chat in Step 6 does not appear in LHN even though it is opened prior" - i checked code from @tienifr and it fixes this issue.
And based on this comment https://github.com/Expensify/App/issues/24596#issuecomment-1681679531 - we will have 2 more issues - order problem and loading time
I will suggest to merge @tienifr PR and close for now @s-alves10 PR

**Comment by s-alves10** [comment] 2023-08-17 08:01
@narefyev91 

I was already assigned to this issue and created the PR. I'm not sure why my PR should be closed.
I think this kind of situations should be handled fairly.

PS: My solution behaves the same as the old version, but I guess @tienifr 's solution tries to show only one chats. This is not expected, I think.

**Comment by ArekChr** [comment] 2023-08-17 08:08
@s-alves10 Here is the original issue https://github.com/Expensify/App/issues/23735

**Comment by s-alves10** [comment] 2023-08-17 08:25
> The opened chat in Step 6 will appear in LHN while the rest of the chats is loading

This is the expected behavior of this issue. If we should avoid partial showing in wide-screen devices, we can add an additional condition `!!this.props.currentReportID` to the LHNOptionList. 

I don't think this can be a reason for closing the PR
Expecting others' thoughts here

**Comment by s-alves10** [comment] 2023-08-17 17:25
@yuwenmemon @aldo-expensify @narefyev91 

Please share your thoughts here. What should I do?

**Comment by s-alves10** [comment] 2023-08-17 20:50
Showing one report causes [this regression](https://github.com/Expensify/App/issues/24573) as well

**Comment by aldo-expensify** [comment] 2023-08-17 21:19
Sorry, for the delay, can we summarize what each PR is fixing and the pros and cons?

@tienifr 's PR https://github.com/Expensify/App/pull/24619 is fixing the issue reported here, right? I personally don't like much the solution using the state `firstLoadedReportID`... it feels like a workaround, but that doesn't mean it is not acceptable.

@s-alves10 's PR https://github.com/Expensify/App/pull/25159 feels better to me from a code perspective, and is fixing supposed to be fixing this issue and also the [other regression](https://github.com/Expensify/App/issues/24573). The problem is that this seem to cause some unwanted effects regarding the order of the reports in the LHN, did I get that?

Would be good to know:
- if @tienifr 's PR https://github.com/Expensify/App/pull/24619 also fixes [other regression](https://github.com/Expensify/App/issues/24573) or not?
- What are exactly the bad side effects that @s-alves10 's PR https://github.com/Expensify/App/pull/25159 causes and if they can be improved
-  Is there any bad side effect caused by @tienifr 's PR https://github.com/Expensify/App/pull/24619 ?

**Comment by aldo-expensify** [comment] 2023-08-18 01:08
I know I said I would come back to this later today, but I got caught in something I though would be simpler. I'll check in tomorrow!

**Comment by s-alves10** [comment] 2023-08-23 17:24
@aldo-expensify 

I've added some updates to the PR to fix the issue mentioned [here](https://github.com/Expensify/App/issues/24596#issuecomment-1681679531).

**Comment by narefyev91** [comment] 2023-08-24 07:38
@aldo-expensify after checking both PR's i think @s-alves10 PR looks preferable - we will not use state, and all logic will be inside optionListItems - which makes more sense. BTW let us know next steps here

**Comment by aldo-expensify** [comment] 2023-08-24 19:25
Agreed, I tested and seems to be solving both issues (commented with more details [here](https://github.com/Expensify/App/pull/25159#issuecomment-1692282198)).

Let's wait for @s-alves10 to update the PR with main and resolve conflicts, then we can do a final review.

**Comment by sakluger** [comment] 2023-09-12 04:25
**Summarizing payouts for this issue:**

Reporter: Applause (contractor, no payment)
Contributor: @s-alves10 $1000 (hired on Upwork)
Contributor+: @narefyev91 (contractor, no payment)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~0137e6674165abf18a

**Closed by sakluger** 2023-09-12 04:25 UTC
Labels: External, Engineering, Daily, Awaiting Payment
