### ISSUE TITLE
[$500] mWeb-Compose- Entering @ and scrolling and selecting an user shakens the message page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28694] opened 2023-10-03 09:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Enter @in compose box
4.From the user suggestions, scroll and select any user and observe the conversation page

## Expected Result:
Entering @ and scrolling and selecting an user from the user suggestions, must not shaken the message/conversation page

## Actual Result:
Entering @ and scrolling and selecting an user from the user suggestions, shakens the message/conversation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3 76-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/afe688e4-3b87-43db-84f9-a2e4689764ea

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110d95334e6200266</li>
        <li>Upwork Job ID: 1709132568616767488</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by martin12345678900** [comment] 2023-10-03 09:41
# **Proposal**

## **Please re-state the problem that we are trying to solve in this issue**
When we open some report in the text input below when we try to mention some user with ```@``` it displays it's email instead of his username.
## **What is the root cause of the problem**
[here](https://github.com/Expensify/App/blob/6e7de4e8376072529c768922ed0a6faf6ad7c6f9/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L76) we are using the ```mentionObject.alternateText``` for setting a selection.

```javascript
       const mentionCode = mentionObject.text === CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT ? CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT : `@${mentionObject.alternateText}`;
```
## **What changes do you think we should make in order to solve the problem?**
Instead of using ```mentionObject.alternateText``` we should use ```mentionObject.text``` property.

```javascript
            const mentionCode = mentionObject.text === CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT ? CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT : `@${mentionObject.text}`;
```
## **What alternative solutions did you explore? (Optional)**

**Comment by Christinadobrzyn** [comment] 2023-10-03 15:47
I'm not able to reproduce this Samsung Galaxy S22 NewExpesnify app or Android Chrome. I also am not sure if we need to fix this now or just wait to see if it's fixed with other jobs. 

I'll ask QA if they still see this.

**Comment by saad995** [comment] 2023-10-03 16:21
Just for clarification, the above issue surely is reproducible but not the way it has been reported. Here's my 2 cents on this after a few hours of analysis.

**Please re-state the problem that we are trying to solve in this issue**
Text input area gets shaken when selecting a user with **long** username.

**What is the root cause of the problem**
The actual issue here is not the selection of any user but the text input length.
Observe when the input lines get increased to 2 then only this shake appears. So even if you type till a new line you can clearly observe the shake.
The reason for this shaky behavior is 'padding' style added to the text input:
• default padding value is 5
• if number of lines is 1 then padding value is 9
• if number of lines is 3 then padding value is 8

![image](https://github.com/Expensify/App/assets/24203380/b9c9facc-974b-4bff-a19f-a2b4e215077c)

**What changes do you think we should make in order to solve the problem?**
IMO, we need to eliminate this padding change on line change handling.

**What alternative solutions did you explore? (Optional)**
The above solution might raise issues on other platforms like iOS, so a better approach would be to have platform specific code as mentioned in the react native docs,
https://reactnative.dev/docs/platform-specific-code

**Comment by Santhosh-Sellavel** [comment] 2023-10-03 18:22
> I don't actually think that is enough of an issue to fix now - we can spend time on other things but maybe there's a reason to fix it - @Santhosh-Sellavel?

I agree, it doesn’t feel like a issue at all. Really subtle, actually composer is just resizing to fit the content, there is no weird glitches.

**Comment by Christinadobrzyn** [comment] 2023-10-04 00:05
Sounds good! Thanks @Santhosh-Sellavel - I'm going to close this.

**Closed by Christinadobrzyn** 2023-10-04 00:05 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by saad995** [comment] 2023-10-06 10:36
Why posted on upwork? if it was not that big of an issue.
We spend our time to analyze this before taking the job as per your guidelines, please try to be just.
