### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Web -  Still able to access the deleted link on thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22888] opened 2023-07-14 11:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On staging dot on web chrome > Go to any chat and type any URL starting with www
2. Now after the URL description appears > Click on reply thread option so that a new thread page opens up
3. On the new thread page, now delete the URL
4. Notice that the URL description is still shown and if you try to click on it, we are still able to access it

## Expected Result:
Should not be able to access the deleted link on thread

## Actual Result:
Still able to access the deleted link on thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cb2d0324-66fb-4001-93c6-5cc3a48ff701

https://github.com/Expensify/App/assets/93399543/e4a66977-f70f-4ec7-883d-bb9d174519c3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689273337561749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ae5682486494f3c</li>
        <li>Upwork Job ID: 1679843925808099328</li>
        2023-07-21<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>StevenKKC | Contributor | 25748815</li>
<li>priya-zha | Reporter | 25748819</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-14 13:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Still able to access the deleted link on thread.

### What is the root cause of that problem?
When delete comment on thread, `Report.deleteReportComment` will be called.

But in this function, does not delete `linkMeatadata`, so the URL description is still shown and still able to access it

### What changes do you think we should make in order to solve the problem?
We should remove `linkMetadata` in `Report.deleteReportComment`.

### What alternative solutions did you explore? (Optional)
None.

**Comment by jaimishpatel5** [comment] 2023-07-15 13:51
**Proposal**
The problem we are trying to solve is that when a thread message containing a link is deleted, the link preview associated with that link still remains visible.

**What is root cause of that problem?**
The root cause of this problem is that the link preview is shown if the message contains linkMetadata. When a message is deleted, we do not clear the linkMetadata, which causes the link preview to persist even after deletion.

**What Changes do you think we should make in order to solve the problem?**

To solve this issue, we should make changes to the code in the file "ReportActionItem.js" (located at "App/src/pages/home/report/**ReportActionItem.js**"). **Specifically, we need to ensure that when a message is deleted, the linkMetadata is cleared.** This change should be implemented in the function responsible for deleting messages in the "Report.js" file (located at "App/src/libs/actions/Report.js"). By adding the line "linkMetadata: []" to the code that handles the deletion of messages, we can effectively clear the linkMetadata and prevent the link preview from persisting after the message is deleted.


https://github.com/Expensify/App/assets/20947611/e4fdf8d1-8b62-4807-9c91-222eebd25cce

**Comment by jaimishpatel5** [comment] 2023-07-15 13:56
Contributor details
Your Expensify account email: jaimishpatel5@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011ee82a8b878485e5

**Comment by jaimishpatel5** [comment] 2023-07-15 13:57
**Proposal**
The problem we are trying to solve is that when a thread message containing a link is deleted, the link preview associated with that link still remains visible.

**What is root cause of that problem?**
The root cause of this problem is that the link preview is shown if the message contains linkMetadata. When a message is deleted, we do not clear the linkMetadata, which causes the link preview to persist even after deletion.

**
https://github.com/Expensify/App/assets/20947611/c0585a28-6534-42a0-b58e-636418f3ab0a
**

To solve this issue, we should make changes to the code in the file "ReportActionItem.js" (located at "App/src/pages/home/report/ReportActionItem.js"). Specifically, we need to ensure that when a message is deleted, the linkMetadata is cleared. This change should be implemented in the function responsible for deleting messages in the "Report.js" file (located at "App/src/libs/actions/Report.js"). By adding the line "linkMetadata: []" to the code that handles the deletion of messages, we can effectively clear the linkMetadata and prevent the link preview from persisting after the message is deleted.

https://github.com/Expensify/App/assets/20947611/0fcd8b03-ea7a-4e14-b2c9-b01234c5932c

**Comment by dylanexpensify** [comment] 2023-07-17 09:18
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-07-20 08:38
@eVoloshchak can we get reviews on proposals today please? 🙇

**Comment by dylanexpensify** [comment] 2023-07-24 08:26
@eVoloshchak bump!

**Comment by eVoloshchak** [comment] 2023-07-24 08:36
Apologies for the delay, reviewing today

**Comment by eVoloshchak** [comment] 2023-07-24 21:35
@StevenKKC's [proposal](https://github.com/Expensify/App/issues/22888#issuecomment-1635865940) looks good to me!
All of the proposals are very similar, so let's proceed with the first one 

🎀👀🎀 C+ reviewed!

**Comment by marcaaron** [comment] 2023-07-25 20:01
Thanks for the review @eVoloshchak 🙇 no worry about the delay.

**Comment by StevenKKC** [comment] 2023-07-26 05:43
@eVoloshchak @marcaaron PR (https://github.com/Expensify/App/pull/23616) is ready for review.

**Comment by marcaaron** [comment] 2023-08-07 17:58
I think we're waiting for the checklist here @eVoloshchak

**Comment by marcaaron** [comment] 2023-08-09 20:28
Bump @eVoloshchak

**Comment by dylanexpensify** [comment] 2023-08-10 11:07
Payment summary:

- Issue reporter: @priya-zha $250
- Contributor: @StevenKKC $1,500
- Contributor +: @eVoloshchak $1,500

Upwork job [here](https://www.upwork.com/jobs/~013ae5682486494f3c).

**Comment by eVoloshchak** [comment] 2023-08-10 15:32
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/17288
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/17288#issuecomment-1673432367
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think any additional discussion is necessary, this is an edge case that was missed when implementing the link previews feature
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No_
This isn't impactful enough to require a regression test I think

**Comment by dylanexpensify** [comment] 2023-08-11 19:55
@eVoloshchak you're paid in NewDot, correct?

**Comment by dylanexpensify** [comment] 2023-08-14 08:27
Reviewing today!

**Comment by eVoloshchak** [comment] 2023-08-14 08:38
> @eVoloshchak you're paid in NewDot, correct?

@dylanexpensify, that is correct

**Comment by dylanexpensify** [comment] 2023-08-14 12:16
Ok perfect, once paid we'll close this out!

**Comment by StevenKKC** [comment] 2023-08-15 16:09
@dylanexpensify Could you please process payment?

**Comment by JmillsExpensify** [comment] 2023-08-15 16:48
Reviewed the details for @eVoloshchak. Approved for payment in NewDot based on BZ summary above.

**Comment by dylanexpensify** [comment] 2023-08-15 20:10
Payments all sent and completed!

**Closed by dylanexpensify** 2023-08-15 20:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
