### ISSUE TITLE
Android - Console error on login page when Phone or email text-input is focused. - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11194] opened 2022-09-22 04:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app on android.
2. Tap on Phone or email.

## Expected Result:
no console errors

## Actual Result:
 Console error:
 Error: Failed prop type: The prop `isChecked` is marked as required in `Checkbox`, but its value is `undefined`.
    at Checkbox (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:259205:36)
    in BaseTextInput

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Android
- Desktop App

**Version Number:** 1.2.1-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="569" alt="Screenshot 2022-09-01 at 10 25 22 PM" src="https://user-images.githubusercontent.com/43995119/191660004-ed4f3b76-6eda-4c8d-9860-ef0e960ba73a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662053176714619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment] 2022-09-22 07:49
This issue is resolved by https://github.com/Expensify/App/pull/10929/files#diff-6dc391ec60b205cb6a3aab3878552fc9e50c4494004d83aaa0797ea332a8d21a change in https://github.com/Expensify/App/pull/10929

**Comment by srikarparsi** [comment] 2022-09-27 01:51
yup thank you @sobitneupane, closing out the issue.

**Closed by srikarparsi** 2022-09-27 01:51 UTC
Labels: Engineering, Daily, Overdue

**Comment by mallenexpensify** [comment] 2022-10-12 00:27
We've recently started compensating for reporting console errors if they get fixed.  I think we should make it a best practice for QA to always (when possible) include logs when they create issues (ideally both from the contributor if they're submitted as well as from when QA reproduces).  

 For this issue specifically, it appears that QA reported https://github.com/Expensify/App/issues/10753 an hour before @aneequeahmad reported this and 
and [Marc's PR](https://github.com/Expensify/App/pull/10929) fixed it.  But.. there are no logs so it's hard to know if the bug has already been reported.   

late tl,dr: compensating for console errors opens up a bit of a can o' worms and might take time to research. If we're going to do continue to compensate, we should ask the contributor to do the digging if they think they're due compensation.

**Comment by aneequeahmad** [comment] 2022-10-27 05:18
@mallenexpensify How can i compare my report time with internal team's time. I didn't found any reported issue on slack neither any logged bug when i posted it.

Also, https://github.com/Expensify/App/issues/10753 `issue exist on all platforms and doesn't feel like root cause is this console error that I reported`. Thanks

cc: @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-10-27 18:44
@aneequeahmad The internal report time would be the time the E/App issue is created from QA if they found the issue.  
So... for #10753 I see
<img width="224" alt="image" src="https://user-images.githubusercontent.com/22508304/198372575-fb7b8cf9-f752-4c2f-97d6-4e3635ab49f1.png">

And for yours in Slack I see an hour later. 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/22508304/198372683-19188812-bb84-4ec0-a20a-7355dafce8f1.png">

The large majority of issues will be created in the E/App repo, let's consider it an edge case that you'd report and issue and someone would say 'oh, that's been reported internally' without there be a link they can provide (or... maybe screenshot). 

Does that answer your question/

**Comment by aneequeahmad** [comment] 2022-11-06 19:59
@mallenexpensify, Ummmm you're right that majority of the issues are reported in E/App repo. I'm afraid i've seen most the issues that i reported on slack expensify-open-source are not logged on E/App repo and Page not found error is shown. 

Also, the error i reported is console error and the other one mentioned above https://github.com/Expensify/App/issues/10753  root cause isn't this error because this error is in logged out state. 

Apologies if i'm missing something. Thanks

**Comment by mallenexpensify** [comment] 2022-11-07 22:50
> Also, the error i reported is console error and the other one mentioned above https://github.com/Expensify/App/issues/10753 root cause isn't this error because this error is in logged out state.

Would/did the fix for #10753 have fixed the 'logged out state' error you reported? 

Another thought, for any issues in the E/E repo that you don't have access too, you can request an employee take a look and screenshot the creation or _reporting_ time for those.

**Comment by aneequeahmad** [comment] 2022-11-08 01:15
@mallenexpensify Actually the logged out state error is fixed in this PR https://github.com/Expensify/App/pull/10929.

The one you mentioned #10753 issue is closed as this was also fixed by this PR https://github.com/Expensify/App/pull/10929 
as mentioned [here](https://github.com/Expensify/App/pull/10929#:~:text=as%20a%20fallback.-,Fixed%20Issues,-%24%20https%3A//github) in `Fixed issues`.

**Comment by mallenexpensify** [comment] 2022-11-08 20:04
The linked in issues in the OP of #10929 all have creation dates before you reported the issue @aneequeahmad , so I'm back to wondering "would this issue had been fixed if it hadn't been reported?"   I'm not sure that's the only justification for compensation though.  The reason I'm curious is because it's possibly to report a ton of _legitimate_ bugs while possibly knowing they likely have the same underlying problem. I'm not suggesting you've done so here, just _talking_ this through as I'm also trying to decide if the reporting bonus is due.

**Comment by aneequeahmad** [comment] 2022-11-08 21:13
That totally makes sense what you're [wondering](https://github.com/Expensify/App/issues/11194#:~:text=would%20this%20issue%20had%20been%20fixed%20if%20it%20hadn%27t%20been%20reported%3F). Now i'm wondering this too xD

Please let me explain the [PR](https://github.com/Expensify/App/issues/11194#:~:text=issues%20in%20the-,OP%20of%20%2310929,-all%20have%20creation) a bit more.

#10929 PR has 3 issues mentioned which are:

-  First issues is internal issue can't access the url.

-  2nd #10799 and the 3rd issue #10753 might have same root cause which is also not `console error` the one i reported here.

- These both issues are fixed by PR https://github.com/Expensify/App/pull/10764 as mentioned in the OP.

Let me know if this makes sense or not.
