### ISSUE TITLE
Close account- `Enter message here` place holder is not closer to the border

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14609] opened 2023-01-26 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #12447
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings - > Security -> Close account

## Expected Result:
The placeholder text should be closer to the border

## Actual Result:
It looks weird as this appears far from the border

## Workaround:
visual

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.60-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214968191-a105c309-7bb2-434b-9215-29dba1fb95d7.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2023-01-27 10:50
@shawnborton I'm not sure if this is a bug or it just hasn't been designed intentionally yet?

**Comment by shawnborton** [comment] 2023-01-27 12:58
This is intentional! This is a textarea, so the label is at the very top and there is a bigger space to add text. Going to close this out as it's not a bug.

**Closed by shawnborton** 2023-01-27 12:58 UTC
Labels: Daily, Design, Bug
