### ISSUE TITLE
DEV: Console error on Pressing invite button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21326] opened 2023-06-22 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Go to workspace > members
2 Click to invite
## Expected Result: 
should not show console error
## Actual Result: shows console error -  
Failed prop type: Invalid prop `sections[1].data[0].participantsList[0].accountID` of type `string` supplied to `BaseOptionsSelector`, expected `number`.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3. 30-5
**Reproducible in staging?:** DEV only
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Uploading Screen Recording 2023-06-22 at 17.10.19.mov…

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686844351186509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-06-22 17:42
Duplicate of https://github.com/Expensify/App/issues/20802#issuecomment-1596783710

**Comment by bfitzexpensify** [comment] 2023-06-23 07:48
Agreed this is a dupe, closing.

**Closed by bfitzexpensify** 2023-06-23 07:48 UTC
Labels: Daily, Needs Reproduction, Bug
