### ISSUE TITLE
[$250] Group chat - Group header 'Chat report' displayed briefly after creating a group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45838] opened 2024-07-20 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** shussain+chrome1@applausemail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44702
## Action Performed:
1. Open the app.
2. Click on the (+) plus icon and choose "Start Chat"
3. Select multiple people to add to the group.
4. Click on "Next"
5. Click on the avatar and upload an image.
6. After uploading, click on "View photo"
7. Remove the image and upload it again.
8. Create the group and check the header.

## Expected Result:
The group header should correctly display the group name immediately after the group is created, without any temporary display of 'Chat report'

## Actual Result:
Group header 'Chat report' displayed briefly after creating a group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/17d82af3-5ecb-478d-93b5-9ef27396bd73

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012281ce39f663be9d</li>
        <li>Upwork Job ID: 1815437242807531371</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment] 2024-07-20 14:23
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment] 2024-07-20 20:15
@b4s36t4 @mollfpr this was found when testing this PR https://github.com/Expensify/App/pull/44702 any chance its regression from it?

Removing the blocker labels as this is super minor issue

**Comment by mountiny** [comment] 2024-07-20 21:25
This is fixed in the revert

https://github.com/user-attachments/assets/a8e11612-352e-48d9-a930-a6316f23abd2

**Comment by mollfpr** [comment] 2024-07-22 10:54
https://github.com/user-attachments/assets/5fbc9aad-8750-482f-bbb7-fb82608303fb

@mountiny I tried the revert but it's not fix this issue.

**Comment by b4s36t4** [comment] 2024-07-22 11:29
Yea, @mollfpr I think our PR is not the offending PR for these issues.

**Comment by luacmartins** [comment] 2024-07-22 17:22
Gonna make this one external

**Comment by mountiny** [comment] 2024-07-22 21:54
@b4s36t4 @mollfpr you are right, I have done one step differently and it caused this issue to not be reproducible 🤦

**Comment by kabeer95** [comment] 2024-07-22 22:30
# Proposal
## Problem Statement 
When creating a new group chat, the "Chat Report" header is briefly displayed in the group header before being replaced with the correct group name.

## Root Cause
 The root cause of this problem is that the code is incorrectly setting the group header to "Chat Report" before updating it to the correct group name.

## Proposed Solution 
To solve this problem, I propose updating the code to ensure that the correct group name is displayed in the group header immediately after creating the group, without displaying the "Chat Report" header.

Changes To implement this solution, we need to make the following changes:

Update the code that sets the group header to use the correct group name instead of "Chat Report".
Ensure that the group name is displayed immediately after creating the group, without any delay or flickering.
Solution Code

javascript
```
// Update the group header to use the correct group name
const groupName = getGroupName(); // Get the correct group name
setGroupHeader(groupName); // Set the group header to the correct group name

// Ensure the group name is displayed immediately after creating the group
useEffect(() => {
  setGroupHeader(groupName); // Set the group header to the correct group name
}, [groupName]);
Expected Result The group header should correctly display the group name immediately after the group is created, without any temporary display of 'Chat report'.
```

Actual Result Group header 'Chat report' displayed briefly after creating a group.

## Alternative Solutions
I explored the following alternative solutions:

Delaying the display of the group header until the correct group name is available, but this may cause a brief delay in displaying the group header.
Displaying a loading indicator or placeholder text in the group header until the correct group name is available, but this may not provide a seamless user experience.

**Comment by dhruv-m-patel** [comment] 2024-07-24 05:22
## Proposal

### Problem Statement
When creating a new group chat, the "Chat Report" header is briefly displayed in the group header before being replaced with the correct group name.

### Root Cause

The `Report` action component seems to be opening chat report while report creation is in progress and is using defaults for faster creation while also using it for display which ends up briefly displaying wrong group name in header.

### Proposed Solution

Provide group name and use default header i.e. Chat Report as a fallback value when opening Chat Report for the newly created group while report is also being created.

### Changes To implement this solution, we need to make the following changes:

Update `Report` component's `openReport` to implement the above suggested fix.

### Alternative Solutions

After analyzing the reported issue, above suggested fix seems to work. The other alternative rather than using fallback would be to configure `optimisticReport` correctly beforehand without overrides done for new report if opening a group chat.

**Comment by dhruv-m-patel** [comment] 2024-07-24 05:27
Contributor details
Your Expensify account email: dhruvpatel.work@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135a9ff376a6b5913

**Comment by roryabraham** [comment] 2024-08-03 19:33
Applause reports this is not reproducible

**Comment by luacmartins** [comment] 2024-08-05 07:50
I think we can close this issue then.

**Comment by luacmartins** [comment] 2024-08-06 07:05
Closing. Thanks everyone!

**Closed by luacmartins** 2024-08-06 07:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
