### ISSUE TITLE
Input field does not clear when pressing "Create a New Account" link from footer.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19229] opened 2023-05-18 22:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app.
2. Navigate to the login screen.
3. Fill in the input field.
4. Click on the "Create a New Account" from the footer.

## Expected Result: 
After clicking the "Create a New Account", the input field should be cleared.
## Actual Result: 
The input field retains its value and is not cleared after clicking on "Create a New Account".

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/15878d7b-08f6-4b6f-ba61-a2cfe2465f14

https://github.com/Expensify/App/assets/43996225/1bab0d15-444b-46c9-bec0-729914392895

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Harshdeepjoshi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684258869914869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2023-05-18 22:42
Proposal by @Harshdeepjoshi 
# Proposal
This problem is caused because we have not cleared the username field when the click is handled for create a new account here
https://github.com/Expensify/App/blob/d20142be97e93c10e77f89d235718fcb0a513b61/src/pages/signin/SignInPageLayout/Footer.js#L140C1-L143
### Solution A
This issue can be simply solved by calling [clearLogin](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPageLayout/Footer.js#L140C1-L143) function
[here](https://github.com/Expensify/App/blob/8bf16eacc77e80efbd79b5cedccd8f67c4e9f828/src/pages/signin/SignInPageLayout/Footer.js#L140C6-L143) like this
``` Diff
            {
-                onPress: () => navigateHome(scrollPageToTop),
+                onPress: () => {
+                    navigateHome(scrollPageToTop);
+                    clearLogin();
+                },
                translationPath: 'footer.createAccount',
            },
```
### Explaination
The `clearLogin` function is defined inside [loginform.js](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm.js)
so to call this function from inside the [footer.js](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPageLayout/Footer.js) we need to create a Ref in `loginform`'s parent component i.e [SignInPage.js](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPage.js)
to do this we just need to make following changes [here](https://github.com/Expensify/App/blob/a5fc2e17350b2e34a0882a5f51b0d97bee8a10ea/src/pages/signin/SignInPage.js#LL59C37-L59C37) like this
``` diff
- class SignInPage extends Component {
+ class SignInPage extends React.Component {
+ signInPageRef = React.createRef();
```
After creating this ref we need to pass it as a prop in [LoginForm component](https://github.com/Expensify/App/blob/a5fc2e17350b2e34a0882a5f51b0d97bee8a10ea/src/pages/signin/SignInPage.js#L157-L160C23) like this
``` diff
 <LoginForm
 isVisible={showLoginForm}
 blurOnSubmit={this.props.account.validated === false}
+ref={this.signInPageRef}
 />
```
 now by using this ref we can pass [clearLogin](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPageLayout/Footer.js#L140C1-L143) function
function in [SignInPageLayout](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPageLayout/index.js) like this
``` diff
 <SignInPageLayout
 welcomeHeader={welcomeHeader}
 welcomeText={welcomeText}
 shouldShowWelcomeHeader={showLoginForm || showPasswordForm || showValidateCodeForm || showUnlinkLoginForm || !this.props.isSmallScreenWidth}
 shouldShowWelcomeText={showLoginForm || showPasswordForm || showValidateCodeForm}
+clearLogin={() => this.signInPageRef.current?.clearLogin()}
 >
```
now inside [SignInPageLayout](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPageLayout/index.js) we need to pass this(clearLogin) prop  to footer component [here](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/index.js#LL102C11-L102C11) and [here](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/index.js#LL130C6-L130C6)  like this
``` diff
- <Footer scrollPageToTop={scrollPageToTop} />
+ <Footer
+ scrollPageToTop={scrollPageToTop}
+ clearLogin={props.clearLogin}
+ />
```
after doing this footer have access to clearLogin function , to call it when `create a new account` is pressed we need to pass it [here](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/Footer.js#L37)
```diff
-const columns = ({scrollPageToTop}) => [
+const columns = ({scrollPageToTop, clearLogin}) => [
```
and we also need to change [this](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/Footer.js#LL171C23-L171C23) line like this
``` diff
-{_.map(columns({scrollPageToTop: props.scrollPageToTop}), (column, i) => (
+{_.map(columns({scrollPageToTop: props.scrollPageToTop, clearLogin: props.clearLogin}), (column, i) => (
```
after doing this we can call clearLogin function [here](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/Footer.js#L140-L143C15)
like this
``` Diff
            {
-                onPress: () => navigateHome(scrollPageToTop),
+                onPress: () => {
+                    navigateHome(scrollPageToTop);
+                    clearLogin();
+                },
                translationPath: 'footer.createAccount',
            },
```
if needed we can also clearLogin when login is pressed from the footer , we just need to call  clearLogin();
here
https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/Footer.js#L144-L147C13
### Solution B
This issue can be solved by using the [concept of lifting state up](https://react.dev/learn/sharing-state-between-components#lifting-state-up-by-example) , to do this we need to define [the login state](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/LoginForm.js#LL73C6-L76C11)
``` jsx
     this.state = {
            formError: false,
            **login: '',**
        };
```
and [this](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/LoginForm.js#LL124C1-L126C6) function
``` jsx
    clearLogin() {
        this.setState({login: ''}, this.input.clear);
    }
```
inside [SignInPage.js](https://github.com/Expensify/App/blob/main/src/pages/signin/SignInPage.js)
then these states and functions can be passed in LoginForm component as props [here](https://github.com/Expensify/App/blob/b54b16abfe9a8d03838b6a4817be7aa421eda898/src/pages/signin/SignInPage.js#LL157C1-L160C23) and used as used earlier inside the component (before lifting state up)
we also need to pass the clearLogin function in SigninPageLayout component[ here ](https://github.com/Expensify/App/blob/b54b16abfe9a8d03838b6a4817be7aa421eda898/src/pages/signin/SignInPage.js#LL149C1-L154C18)
like this
``` diff
 <SignInPageLayout
 welcomeHeader={welcomeHeader}
 welcomeText={welcomeText}
 shouldShowWelcomeHeader={showLoginForm || showPasswordForm || showValidateCodeForm || showUnlinkLoginForm || !this.props.isSmallScreenWidth}
 shouldShowWelcomeText={showLoginForm || showPasswordForm || showValidateCodeForm}
+clearLogin={clearLogin}
 >
```
 after doing this footer have access to clearLogin function , to call it when `create a new account` is pressed we need to pass it [here](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/Footer.js#L37)
```diff
-const columns = ({scrollPageToTop}) => [
+const columns = ({scrollPageToTop, clearLogin}) => [
```
and we also need to change [this](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/Footer.js#LL171C23-L171C23) line like this
``` diff
-{_.map(columns({scrollPageToTop: props.scrollPageToTop}), (column, i) => (
+{_.map(columns({scrollPageToTop: props.scrollPageToTop, clearLogin: props.clearLogin}), (column, i) => (
```
after doing this we can call clearLogin function [here](https://github.com/Expensify/App/blob/fa372fc82dff60cac2feed4f8a8ecafcabc197a5/src/pages/signin/SignInPageLayout/Footer.js#L140-L143C15)
like this
``` Diff
            {
-                onPress: () => navigateHome(scrollPageToTop),
+                onPress: () => {
+                    navigateHome(scrollPageToTop);
+                    clearLogin();
+                },
                translationPath: 'footer.createAccount',
            },
```

**Comment by trjExpensify** [comment] 2023-05-22 16:30
Sorry for the delay Melvin, I've been at EC3. Asking in this thread because I don't think it's a bug: https://expensify.slack.com/archives/C049HHMV9SM/p1684772974015809?thread_ts=1684258869.914869&cid=C049HHMV9SM

**Comment by trjExpensify** [comment] 2023-05-25 16:40
No response in the thread, bumped again.

**Comment by grgia** [comment] 2023-05-26 08:45
I posted in the slack thread, but I think this is not a bug

**Comment by trjExpensify** [comment] 2023-05-26 09:15
Cool, thanks. Closing!

**Closed by trjExpensify** 2023-05-26 09:15 UTC
Labels: Daily, Bug
