### ISSUE TITLE
[HOLD for payment 2023-06-08] [$1000] Authenticator field is partially covered by keyboard on iOS

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19387] opened 2023-05-22 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > security >Two factor authentication
2. click on copy codes and next button
3. check authenticator field

## Expected Result :  
authenticator field should be fully visible
## Actual Result : 
dashes (______) hidden behind keyboard

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.6
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bf67ba3c-9abb-45c5-96b1-56300dcfc708

https://github.com/Expensify/App/assets/43996225/64bc08a2-b637-4c80-8082-8827be168235

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684474528894489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109f2bfd6857fa236</li>
        <li>Upwork Job ID: 1660804364974141440</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by arielgreen** [comment] 2023-05-23 00:26
Good to be external

**Comment by qispark** [comment] 2023-05-23 02:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The authenticator fields are not visible, although autofocus has selected the field. This is because of the keyboard's apperance.

### What is the root cause of that problem?
The combination of the components on the screen (Scrollview with auth input, plus footer button) is causing the authenticator field to not appear fully after scrolling to the component.

### What changes do you think we should make in order to solve the problem?
This issue can simply be resolved by adding a `contentInset` to the ScrollView.

In `App/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js`, line 99, update the following:

```
<ScrollView style={styles.mb5} contentInset={{bottom: 10}}>
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by dukenv0307** [comment] 2023-05-23 06:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dashes (______) of the magic code input is hidden behind keyboard

### What is the root cause of that problem?

Let's look at how the magic code input field in here https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#L301 is structured:

<img width="172" alt="Screenshot 2023-05-23 at 13 46 00" src="https://github.com/Expensify/App/assets/129500732/786070fe-00db-45e3-b57f-d5e97593dc7c">

We have:
- a hidden input [here](https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#L301)
- the text container [here](https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#LL297C24-L297C24) which contains the bigger digit text that we can see being typed in.
- The outer container that wraps both the hidden input and text container [here](https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#L291)
- And there's the border of the text container which is 2px (it's the dash that we see), doesn't belong to the height of the hidden `TextInput`.

The autoscroll behavior of the device will only make sure the `TextInput` is fully visible, since the dash isn't included in the TextInput height, it will be hidden.

### What changes do you think we should make in order to solve the problem?

We need to make sure the dash is included in the `TextInput` height so that when the `TextInput` is fully visible, the dash will also be visible.

We can do that by making the text container height equal to the outer container heigh minus the bottom border width, then the text container height inclusive of the bottom border will be equal to the TextInput height. When the `TextInput` is fully visible, the dashes will also be fully visible.
<img width="356" alt="Screenshot 2023-05-23 at 13 51 53" src="https://github.com/Expensify/App/assets/129500732/3c0caf27-ba0b-4119-963a-30b2d7887583">

We can add `{ height: styles.magicCodeInputContainer.minHeight - styles.textInputContainer.borderBottomWidth}` to the list of styles [here](https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#LL297C19-L297C19). 

### What alternative solutions did you explore? (Optional)
> We need to make sure the dash is included in the `TextInput` height so that when the `TextInput` is fully visible, the dash will also be visible.

There're other ways to dot this like increasing the `TextInput` height by 2 (the bottom border width), moving the hidden text input down by 2 by using `{ bottom: 2}`, ... but basically the fix is the same.

**Comment by arielgreen** [comment] 2023-05-25 02:31
@rushatgabhane please review the above two proposals asap

**Comment by arielgreen** [comment] 2023-05-25 02:31
Pinged in Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1684981890925749?thread_ts=1684974522.735829&cid=C02NK2DQWUX).

**Comment by amyevans** [comment] 2023-05-25 23:15
Proposal looks great, with one minor clarifying question - shouldn't the new `height` be `styles.magicCodeInputContainer.minHeight + styles.textInputContainer.borderBottomWidth` (not `-`)?

Anyway, assigning so that we can move to the PR phase. Thanks!

**Comment by amyevans** [comment] 2023-05-25 23:17
Also, heads up that I'll be OOO tomorrow and Monday. I'll review the PR Tuesday if I'm unable to get to it before then. This shouldn't affect timeliness bonuses since Monday is a holiday in the US.

**Comment by arielgreen** [comment] 2023-05-26 02:12
I'm also OOO tomorrow and Monday, but I think no need to reassign for the same reasons @amyevans mentioned above. I'll just plan on checking back in on this Tuesday.

**Comment by dukenv0307** [comment] 2023-05-26 10:25
> Proposal looks great, with one minor clarifying question - shouldn't the new height be styles.magicCodeInputContainer.minHeight + styles.textInputContainer.borderBottomWidth (not -)?
> 
> Anyway, assigning so that we can move to the PR phase. Thanks!
@amyevans as I mentioned in my proposal
We have:



1. The outer container that wraps both the hidden input and text container [here](https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#L291)
2. the text container [here](https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#LL297C24-L297C24) which contains the bigger digit text that we can see being typed in.
3. a hidden input [here](https://github.com/Expensify/App/blob/1ab36df9fa03a3e85cb68c64de71eca3d559a3dd/src/components/MagicCodeInput.js#L301)
### The outer container include the text container and the hidden input

So when we decrease the height of the text container, the text container height inclusive of the bottom border will be equal to the TextInput height.

**Comment by arielgreen** [comment] 2023-06-09 02:25
Calculating payments:
5/25 -  issue [assigned](https://github.com/Expensify/App/issues/19387#issuecomment-1563620696) to @dukenv0307 
5/30 -  PR [merged](https://github.com/Expensify/App/pull/19653#event-9380621787)

3 business days =  50% bonus

$250 to @gadhiyamanan
$1000 + 50% = $1500 to @dukenv0307 
$1000 + 50% = $1500 to @rushatgabhane

**Comment by arielgreen** [comment] 2023-06-09 02:26
@gadhiyamanan @rushatgabhane @dukenv0307 please let me know when you have applied to the Upwork job: https://www.upwork.com/jobs/~0109f2bfd6857fa236

**Comment by gadhiyamanan** [comment] 2023-06-09 02:29
@arielgreen applied!

**Comment by arielgreen** [comment] 2023-06-13 20:32
Thanks guys. Offers sent.

@rushatgabhane this is still waiting on the checklist.

**Comment by arielgreen** [comment] 2023-06-14 22:51
@dukenv0307 bump on the above, I cannot issue payment until you have accepted the offer.

**Comment by arielgreen** [comment] 2023-06-14 22:51
@gadhiyamanan payment has been issued.

**Comment by arielgreen** [comment] 2023-06-14 22:51
@rushatgabhane checklist needs completing before payment issued.

**Comment by arielgreen** [comment] 2023-06-16 02:44
Thanks! Payment issued.

**Comment by arielgreen** [comment] 2023-06-16 02:44
Reassigning, team change

**Comment by lschurr** [comment] 2023-06-16 15:32
@rushatgabhane - Could you work through the checklist? Do we need a regression test for this?

**Comment by lschurr** [comment] 2023-06-19 16:57
Bump @rushatgabhane on this one. Can we close?

**Comment by lschurr** [comment] 2023-06-22 22:19
Bump @rushatgabhane - let's get this one complete so that we can close.

**Comment by lschurr** [comment] 2023-06-26 15:51
Thanks! Made a GH for the regression test. Closing this out!

**Comment by lschurr** [comment] 2023-06-26 17:29
Hmm it says it was already paid via this comment.. https://github.com/Expensify/App/issues/19387#issuecomment-1594012185

**Comment by lschurr** [comment] 2023-06-26 17:29
I will take another look.

**Comment by lschurr** [comment] 2023-06-26 17:31
Yep - that is already paid @rushatgabhane.

<img width="613" alt="image" src="https://github.com/Expensify/App/assets/33293730/8ebf0b54-4c9f-464d-aa35-35dfb74f113d">

**Comment by lschurr** [comment] 2023-06-26 17:32
Ah, I see. Some payments were made, but not all.

**Comment by lschurr** [comment] 2023-06-26 17:34
I sent the offer @rushatgabhane

**Comment by lschurr** [comment] 2023-06-26 18:50
Payment issued. This one should be done now!

**Closed by lschurr** 2023-06-26 18:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
