### ISSUE TITLE
Input lose focus when navigating back from Add message screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23096] opened 2023-07-18 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any workspace
2. Choose Members -> Invite, then click on any user
3. Notice that the Input box is focused
4. Click Next button to navigate to Add Message screen
5. Click Back button
6. Verify that the Input box lose focus
## Expected Result:
 The Input box is focused
## Actual Result: 
The Input box is not focused

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/28bf2dbf-feb2-4af2-84e1-4e7b0b58141a

https://github.com/Expensify/App/assets/43996225/331d0177-af54-4158-8e20-e544bc569942

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689587092828079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment] 2023-07-18 16:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Input lose focus when navigating back from Add message screen

### What is the root cause of that problem?
`BaseOptionsSelector` is not handling TextInput focus on component update.

### What changes do you think we should make in order to solve the problem?
Need to call `focus` method of `TextInput` in `componentUpdate` of `BaseOptionsSeelctor` component

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mateocole** [comment] 2023-07-19 14:33
Hmmm this looks similar to [this issue](https://github.com/Expensify/App/issues/22610). I want to confirm with engineering that this is indeed a separate issue.

**Comment by mateocole** [comment] 2023-07-19 14:34
hey @luacmartins! I wanted to confirm if you think this is or is not a duplicate of [this issue](https://github.com/Expensify/App/issues/22610)

**Comment by luacmartins** [comment] 2023-07-19 17:56
Agreed that it seems to have the same root cause and we can close this in favor of https://github.com/Expensify/App/issues/22610

**Comment by luacmartins** [comment] 2023-07-19 21:23
Sure, this seems like another instance of the same bug reported in https://github.com/Expensify/App/issues/22610. We probably wouldn't have fixed it in that issue if it wasn't for this report.

**Comment by mateocole** [comment] 2023-07-24 08:47
Looks like this was [already resolved](https://github.com/Expensify/App/issues/22610#issuecomment-1644349909) as the root cause was the same, so this would have been resolved regardless of reporting. Going to close this issue out now.

**Closed by mateocole** 2023-07-24 08:47 UTC
Labels: Engineering, Daily, Overdue, Bug
