### ISSUE TITLE
[$500] Multiple email notification received for one whisper message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#30405] opened 2023-10-26 02:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698240986447199

## Action Performed:
1. Open app
2. Refer a friend 
3. Check the inbox
## Expected Result:
One email received for a whisper message
## Actual Result:
Multiple emails are received
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![image (2)](https://github.com/Expensify/App/assets/43996225/66b56fab-4b56-4268-a9d4-fe2e234a7661)

![image (1)](https://github.com/Expensify/App/assets/43996225/24d53263-0b81-4726-b696-340b96854103)

![image](https://github.com/Expensify/App/assets/43996225/34a0bb2b-d378-4c16-929e-24349db38c98)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153df9cc58eb8a237</li>
        <li>Upwork Job ID: 1719360476600082432</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-10-31 14:27
Moving forward

**Comment by cooldev900** [comment] 2023-10-31 20:01
@kevinksullivan 
how do I refer a friend in app?

**Comment by puneetlath** [comment] 2023-11-01 15:27
@kevinksullivan this is likely a back-end issue since that's where emails are triggered from.

**Comment by kevinksullivan** [comment] 2023-11-07 22:25
Making internal based on @puneetlath 's comment

**Comment by mvtglobally** [comment] 2023-11-09 21:04
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment] 2023-11-14 00:19
Closing since this isn't reproducible.

**Closed by kevinksullivan** 2023-11-14 00:19 UTC
Labels: Daily, Internal, Help Wanted, Overdue, Bug
