### ISSUE TITLE
[$500] IOS - Sign out - App crashes if user sign out of new account after sending a message while offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29375] opened 2023-10-11 20:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Enter email address to create a new account
3. Enter magic code
4. Disable internet connection
5. Go to a new chat and send a few messages
6. Return to LHN
7. Tap on avatar
8. Tap on "Sign out" and confirm

## Expected Result:
Login page should be displayed without issues

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/e03a9a8c-c905-433f-a3ec-95ae35b395c7

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d857e28e5afd3179</li>
        <li>Upwork Job ID: 1714017865004101632</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by johncschuster** [comment] 2023-10-16 20:38
Triaged

**Comment by keisyrzk** [comment] 2023-10-18 12:24
Tried but could not reproduce on `main 1.3.86-1`.

**Comment by johncschuster** [comment] 2023-10-19 20:34
@keisyrzk ^^

**Comment by johncschuster** [comment] 2023-10-20 10:54
@hoangzinh thanks for giving that a try! @lanitochka17, are you still able to reproduce this behavior? If not, I'll close the issue.

**Comment by lanitochka17** [comment] 2023-10-26 16:55
@johncschuster @hoangzinh Hello
Still repro on 1.3.91-6 build

https://github.com/Expensify/App/assets/78819774/4f4d4a31-b9ee-43a6-a880-48c881d96bce

**Comment by johncschuster** [comment] 2023-10-26 19:28
Thanks for reproducing that! I've posted in Slack to get more proposals.

**Comment by pradeepmdk** [comment] 2023-10-27 04:00
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
IOS - Sign out - App crashes if user signs out of new account after sending a message while offline
### What is the root cause of that problem?

<img width="1730" alt="Screenshot 2023-10-27 at 9 15 15 AM" src="https://github.com/Expensify/App/assets/16595846/d22999bd-5e5b-4d94-b7ed-b44e4d92d192">

fullReport is undefined/ null so that app is crashed 
### What changes do you think we should make in order to solve the problem?
we need add condition like this 
https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/components/LHNOptionsList/OptionRowLHNData.js#L188-L204
to
```javascript
key: ({fullReport}) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${lodashGet(fullReport, 'parentReportID', '')}`,
++
                key: ({fullReport}) => `${ONYXKEYS.COLLECTION.POLICY}${lodashGet(fullReport, 'policyID', '')}`,
++
                  withOnyx({
            transaction: {
                key: ({fullReport, parentReportActions}) =>
                    `${ONYXKEYS.COLLECTION.TRANSACTION}${lodashGet(parentReportActions, [lodashGet(fullReport, 'parentReportActionID', ''), 'originalMessage', 'IOUTransactionID'], '')}`,
            },
        }),

```

**Comment by johncschuster** [comment] 2023-11-07 21:01
@hoangzinh what are your thoughts on the available proposals?

**Comment by lanitochka17** [comment] 2023-11-08 15:03
I could not reproduce this issue with the latest build 1.3.96-6
Iphone 14 Pro Max/ios17

https://github.com/Expensify/App/assets/78819774/7b21d775-b05e-4e23-a6f8-7b5c33ff2464

**Comment by johncschuster** [comment] 2023-11-22 22:18
> cc @johncschuster should we close this issue?

Yes, I think so. Thanks for calling that out, @hoangzinh!

**Closed by johncschuster** 2023-11-22 22:18 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
