### ISSUE TITLE
[HOLD for payment 2024-04-09] Web - Reimbursements - There is no offline indicator message on 'Reimbursements' page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39050] opened 2024-03-27 12:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Create a workspace
2. Appy offline mode
3. Navigate to 'Reimbursements' page of the workspace

## Expected Result:
'You appear to be offline.' should be displayed at the bottom of the page

## Actual Result:
'You appear to be offline.' is not displayed at the bottom of the page

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4248c3f1-c0fb-4fb6-935e-d1545a300b2c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Habtamu-Asefa** [comment] 2024-03-27 12:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Offline indicator is not visible on widescreen Reimbursements page when offline, 

### What is the root cause of that problem?
A defaultModalContainer style is not being passed to ScreenWrapper.
https://github.com/Expensify/App/blob/69a2849f163640021e3248eda536d2db112cb153/src/pages/workspace/WorkspacePageWithSections.tsx#L157-L163

### What changes do you think we should make in order to solve the problem?

Passing defaultModalContainer style to ScreenWrapper like in here:
https://github.com/Expensify/App/blob/69a2849f163640021e3248eda536d2db112cb153/src/pages/workspace/WorkspaceMembersPage.tsx#L543-L548

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-03-27 13:21
cc @ruben-rebelo as you worked on that PR

**Comment by danieldoglas** [comment] 2024-03-28 06:52
IMO we don't need to block the deploy on this though.

**Comment by Pujan92** [comment] 2024-03-28 12:19
@danieldoglas I think @Ollyws needs to review the regression fix PR. I can review in case they are not available.

**Comment by danieldoglas** [comment] 2024-04-11 09:14
This one is done, closing it.

**Closed by danieldoglas** 2024-04-11 09:14 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
