### ISSUE TITLE
[$500] Web - Workflows - After the page refreshes, the switch returns to the default value

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37363] opened 2024-02-27 22:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+ihchat4_0802_e@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36345
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in to account with the Collect policy (Admin or employee)
3. Navigate to Settings > Workspaces. You should see your Collect workspace, click on it
4. On the LHP, you should only see the menu items below, specific to paid policies
5. Click on Workflows
6. Click on Delay Submissions toggle
7. Refresh the page

## Expected Result:
The switch for Delay Submissions should be on

## Actual Result:
The switch for Delay Submissions returns to the default value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/76977da7-4d98-4b78-a431-e1adcafb6b16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113a3783dd1a2d250</li>
        <li>Upwork Job ID: 1762607856414375936</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by damadoko** [comment] 2024-02-27 23:33
Can not reproduce in MacOS: Chrome / Safari, dev environment (enabled staging server)

**Comment by dragnoir** [comment] 2024-02-28 14:28
Can't reproduce 🤔

**Comment by puneetlath** [comment] 2024-02-28 15:26
I'm able to repro, but I don't think it needs to be a blocker. @lakchote FYI this is likely coming from your PR.

**Comment by lakchote** [comment] 2024-02-28 16:20
@dukenv0307 thanks for your proposal I've already implemented the fix [here](https://github.com/Expensify/App/pull/37438)  and used the same solution.

@puneetlath @dukenv0307 should be eligible for a partial payment for their solution, thank you.

**Comment by mollfpr** [comment] 2024-03-04 14:21
>@mollfpr requires payment (Needs manual offer from BZ)

Not eligible for payment, since I'm not reviewing the PR.

**Comment by kevinksullivan** [comment] 2024-03-15 22:13
@dukenv0307 sending partial offer. Lmk when you accept

**Comment by lakchote** [comment] 2024-03-20 09:51
@kevinksullivan should we close this?

**Comment by lakchote** [comment] 2024-03-25 16:39
> @kevinksullivan should we close this?

friendly bump :)

**Comment by lakchote** [comment] 2024-04-01 09:51
The contributor has been paid (see [here](https://github.com/Expensify/App/issues/37363#issuecomment-2001512989)). Closing the issue.

**Closed** 2024-04-01 09:51 UTC
Labels: Engineering, Daily, Awaiting Payment
