### ISSUE TITLE
[REGRESSION] Android & iOS - Track tax - "Track tax" message does not scale according to device font size

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43202] opened 2024-06-06 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/42141
## Action Performed:
Precondition:
- Device font size is minimum (or smaller than the standard size)
- Workspace has not enabled taxes
1. Launch New Expensify app
2. Go to workspace settings
3. Go to Distance rates
4. Tap Settings

## Expected Result:
"Track tax" message will scale according to device font size

## Actual Result:
"Track tax" message does not scale according to device font size.
It appears large when the rest of the font is small

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e753f1fd-b8e0-48e9-80b9-539fd9381b54

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016209fd348bb29320</li>
        <li>Upwork Job ID: 1798774655174697872</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102637502</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by lanitochka17** [comment] 2024-06-06 17:01
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by AndrewGable** [comment] 2024-06-06 17:51
Not a deploy blocker, seems like it can be external for sure

**Comment by neonbhai** [comment] 2024-06-06 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track tax - "Track tax" message does not scale according to device font size

### What is the root cause of that problem?
We have extra text styles causing this behavior:
https://github.com/Expensify/App/blob/01c418d55fc2627153335bd49e592341bc249604/src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx#L128



### What changes do you think we should make in order to solve the problem?
We will remove the styles from the `Text` element here:
https://github.com/Expensify/App/blob/01c418d55fc2627153335bd49e592341bc249604/src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx#L128


This would also align the style with the Figma mockups, since colorMuted is also not needed here

**Comment by CharlsSH** [comment] 2024-06-06 21:38
it seems about font-size
so everyone knows well about font size.
if contact with me i'll  send you code right now.

**Comment by CharlsSH** [comment] 2024-06-06 21:43
Contributor details
Expensify account email: <CharlsStone0906@outlook.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~017390385257472222>

**Comment by CharlsSH** [comment] 2024-06-06 21:52
If you interstedof me, chat in upwork!

**Comment by nkdengineer** [comment] 2024-06-07 03:11
I'll raise PR soon to fix this regression

**Comment by jliexpensify** [comment] 2024-06-07 04:42
@rojiphil is this a regression? Cheers.

**Comment by rojiphil** [comment] 2024-06-07 04:57
> is this a regression?

@jliexpensify Yes. Regression from #41574

**Comment by jliexpensify** [comment] 2024-06-07 05:01
Than ks for confirming, `Help Wanted` label removed.

**Comment by CharlsSH** [comment] 2024-06-07 07:46
Then, Resolve it?

**Comment by CharlsSH** [comment] 2024-06-07 07:47
How can i help you?

**Comment by rojiphil** [comment] 2024-06-07 08:16
Unassigned as this is regression and will be fixed by the original authors. Please feel free to add me if needed.

**Comment by CharlsSH** [comment] 2024-06-07 08:22
So How do I do?

**Comment by jliexpensify** [comment] 2024-06-07 09:23
Thanks for your help here @rojiphil! 

@CharlsSH @ShridharGoel - this issue was created due to a regression so it is the responsibility of the original PR's Contributor and C+ to handle this regression. It looks like the `External` label was applied before I got online, so I apologise for the confusion.

**Comment by kavimuru** [comment] 2024-06-07 18:58
Issue fixed 

https://github.com/Expensify/App/assets/43996225/31d9e11a-2df3-4bc8-a6a8-24ef25c39a01

**Comment by jliexpensify** [comment] 2024-06-11 03:03
Awesome, thank you! Closing this one out.

**Closed by jliexpensify** 2024-06-11 03:03 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
