### ISSUE TITLE
[$250] Android – Chat is not marked as read when open message via notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46235] opened 2024-07-25 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a560@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. User A sends a message to User B (Android)
2. User B opens the new message via notification
3. User B go to other chat
4. Take a note at conversation between Users A & B on LHN

## Expected Result:
Chat should be marked as read ( should not be bold)

## Actual Result:
Chat is not marked as read (chat is bold) on LHN when open new message via notification and navigate to other chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1f7dbdd9-6b43-4865-b6bb-a78a17f845aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b91b4c4dfb3fb2e7</li>
        <li>Upwork Job ID: 1823060775661603736</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103652338</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by lanitochka17** [comment] 2024-07-25 20:44
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-25 20:45
We think that this bug might be related to #vip-vsp

**Comment by CortneyOfstad** [comment] 2024-07-31 14:13
VIP VSB is paused. And not able to recreate via testing. Feel free to reopen if issue persists!

**Comment by lanitochka17** [comment] 2024-08-06 15:48
Issue is still reproducible on the latest build 9.0.17


https://github.com/user-attachments/assets/75305a67-954c-4462-b743-d8913597f475

**Comment by CortneyOfstad** [comment] 2024-08-12 18:15
Okay, was able to recreate — going to get some eyes on this!

**Comment by rezkiy37** [comment] 2024-08-21 09:58
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment] 2024-08-22 08:03
Actively working on the issue.

**Comment by rezkiy37** [comment] 2024-08-22 12:27
The bug happens on IOS as well. 


https://github.com/user-attachments/assets/638baf07-e268-4843-b45a-ff663ab427f6

**Comment by rezkiy37** [comment] 2024-08-23 08:25
Looks like I've found the root cause of the bug. Posting a proposal today 🙂

**Comment by rezkiy37** [comment] 2024-08-23 10:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat is not marked as read (chat is bold) on LHN when opening a new message via notification and navigating to another chat.

### What is the root cause of that problem?

The app marks (_line 341_) a chat as read in this `useEffect`.

https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/home/report/ReportActionsList.tsx#L330-L350

Let's clarify the usage of `isFromNotification` to avoid confusion. It works only for the web and desktop. 

There is one more value in the condition - `Visibility.isVisible()`. It returns the app state (`'active' | 'background' | ...`). However, in most cases, it returns the value that the app is not visible (_inactive_). It happens because of the leverage of **outdated** value. 

https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/home/report/ReportActionsList.tsx#L171

https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/home/report/ReportActionsList.tsx#L178-L184

As we can see above, the component already has a state and listener to store the updated value. 

### What changes do you think we should make in order to solve the problem?

The app should use the correct visibility value. Replace `Visibility.isVisible()` with `isVisible` and add it to the dependencies array of `useEffect`. 

App state | Visibility.isVisible() | isVisible
-- | -- | --
Closed app | True | True
Collapsed app | False | True
Opened LHN | False | True
Collapsed Report Screen | False | True
Opened Report Screen | True | True

I created a table to demonstrate which value the app uses for the old `Visibility.isVisible()` and new `isVisible`. Everywhere where the app uses `false`, it does not mark the chat as read (_in most cases_). We can see that for native platforms (_IOS and Android_) it is always true. This is the correct behavior. However, it can be false for the web and desktop, when the user visits another tab or window.

### What alternative solutions did you explore? (Optional) 
N/A

**Comment by rezkiy37** [comment] 2024-08-26 11:47
I've opened the PR (https://github.com/Expensify/App/pull/47801) for review 🙂

**Comment by ZhenjaHorbach** [comment] 2024-09-06 13:23
PR was deployed to prod [30.08.2024](https://github.com/Expensify/App/pull/47801#issuecomment-2322122094)
So today is time to payment !

**Comment by CortneyOfstad** [comment] 2024-09-06 13:31
## Payment Summary

@ZhenjaHorbach — paid $250 via Upwork
@rezkiy37 — contracted position

**Comment by ZhenjaHorbach** [comment] 2024-09-06 13:36
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@ZhenjaHorbach] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/41484

> * [x]  [ @ZhenjaHorbach] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/41484/files#r1747135143

> * [x]  [@ZhenjaHorbach] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

NA

> * [x]  [@ZhenjaHorbach] Determine if we should create a regression test for this bug.
> * [x]  [@ZhenjaHorbach] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

Precondition : bug relevant for native apps (Android or IOS)

- User A sends a message to User B
- User B opens the new message via notification.
- User B goes to another chat.
- Take note of the conversation between Users A & B on LHN and Verify that chat should be marked as read (should not be bold)

Do we agree 👍 or 👎

**Comment by CortneyOfstad** [comment] 2024-09-06 17:47
## Regression Test

https://github.com/Expensify/Expensify/issues/426554

**Closed by CortneyOfstad** 2024-09-06 17:47 UTC
Labels: Reviewing, External, Weekly, Bug
