### ISSUE TITLE
Workspace - Second line in the error message for invalid phone number invite is incorrect

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8572] opened 2022-04-08 22:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com

2. Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)
3. Add a new invalid member to the workspace via Manage Members > Invite

## Expected Result:
Correct error message should appear

## Actual Result:
Incorrect error message in the 2nd line without any spacing too

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5525262_messageerror](https://user-images.githubusercontent.com/43996225/162538588-511aaeb9-7775-44bf-82fc-933c4a652673.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-04-08 23:16
### Proposal

Reason: This is happening because `workspace.invite.pleaseEnterValidLogin` doesn't exist there is no such key in en.js or es.js
https://github.com/Expensify/App/blob/43910fe5c20584b05fe56013005e8e59ba93e8a6/src/libs/actions/Policy.js#L352

Fix: we have multiple ways to solve this,
1. We can remove line 352 because we are already showing an error message so if we remove line 352 then only this error message will be shown:  "An error occurred inviting the user to the workspace, please try again."

2. We can add a key in en.js and es.js so the user will see the generic error message and the error message we will be adding.
https://github.com/Expensify/App/blob/43910fe5c20584b05fe56013005e8e59ba93e8a6/src/libs/actions/Policy.js#L350-L353

3. We can add the key but instead of including it with the generic message we can just show the new error message, like this:
```
 if (data.jsonCode === 402) {
     policyDataWithoutLogin.alertMessage = Localize.translateLocal('workspace.invite.pleaseEnterValidLogin');
}
```

**Comment by Julesssss** [comment] 2022-04-11 09:29
Thanks for the proposals, but I'm going to close this as this issue a a duplicate of [this issue](https://github.com/Expensify/App/issues/8495)

**Comment by luacmartins** [comment] 2022-04-12 15:17
@kavimuru could you please update the original reporter of this issue, since it seems to be reported by @thesahindia and not applause as per this [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1648323880003309) thread? Let me know once it's updated and we will move forward with paying the contributor.

**Comment by luacmartins** [comment] 2022-04-13 15:08
Adding `External` label to pay the reporting bonus. This issue was solved internally, so we can close it once the bonus is paid out.

**Comment by luacmartins** [comment] 2022-04-13 15:08
@MitchExpensify could you please pay the reporting bonus to @thesahindia and close this issue once done? Thank you!

**Comment by MitchExpensify** [comment] 2022-04-14 00:12
Cannn do! [Upwork Job](https://www.upwork.com/jobs/~01a8d563c6b73d9497) created and I've invited @thesahindia for reporting bonus payment

**Comment by thesahindia** [comment] 2022-04-14 17:31
Applied ✅

**Comment by MitchExpensify** [comment] 2022-04-14 22:40
Offer sent!

**Comment by thesahindia** [comment] 2022-04-15 07:55
Accepted the offer.
Thanks.

**Comment by MitchExpensify** [comment] 2022-04-15 18:59
Paid and contract ended! closing

**Closed by MitchExpensify** 2022-04-15 18:59 UTC
Labels: External, Engineering, Daily
