### ISSUE TITLE
[$500]  IOU - Request details page loads infinitely when request is created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37247] opened 2024-02-27 02:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to workspace chat
4. Create a manua; request
5. Navigate to request details page

## Expected Result:
The request details page will load when the request is created offline (production behavior)

## Actual Result:
The request details page loads infinitely when the request is created offline (production behavior).
This issue also occurs when:
- creating IOU with new user offline. The main chat loads infinitely.
- Same issue when opening thread offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6c07792e-7fc4-4280-95ff-9d305a6e361d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-27 02:09
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by youssef-lr** [comment] 2024-02-27 03:56
cc @bernhardoj I think this is related to your PR for this [issue](https://github.com/Expensify/App/issues/37247)

**Comment by youssef-lr** [comment] 2024-02-27 04:12
cc @bernhardoj I think this is related to your PR for this PRs [here](https://github.com/Expensify/App/pull/36996) & [here](https://github.com/Expensify/react-native-onyx/pull/470)

**Comment by bernhardoj** [comment] 2024-02-27 05:34
Checking

**Comment by bernhardoj** [comment] 2024-02-27 07:07
Okay, it's indeed reproducible after the Onyx version bump, but here is the real root cause.

What the recent Onyx PR does is to immediately render the report screen by fixing some `initialValue` that are not applied when they are falsey (false or null). Btw, this [PR](https://www.github.com/Expensify/App/pull/26772) is the first one that attempted to immediately render the report screen, but because we have the Onyx bug, it's not solved 100%.

1. Now, when we press the money request preview, we create an optimistic transaction thread and navigate to it.
https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/components/ReportActionItem/MoneyRequestAction.tsx#L96-L101

Because the report screen is now immediately rendered, the new report Onyx data is not available yet, so the code below will call `openReport`.
https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/pages/home/ReportScreen.js#L355-L362

2. In `openReport`, we have a logic to use SET method (for the optimistic report) when the report is not in the Onyx yet,
https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/libs/actions/Report.ts#L608-L613

The optimistic report looks like this
https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/libs/actions/Report.ts#L552-L556

So, the optimistic transaction thread is overwritten with the report above that only contains `reportName`, thus the infinite loading.

### How do we solve this?

I would remove the logic to change the onyx method to SET (in point 2). It was added in this [PR](https://www.github.com/Expensify/App/pull/20076) to solve [#19364](https://www.github.com/Expensify/App/issues/19364). The issue is that the not-found view is shown briefly (instead of skeleton loading) when opening a thread. 

If we read the root cause from the proposal, it's because when we don't have the report data yet, the default props of the report will have a value of `isLoadingReportActions` as `false` which makes the not found condition becomes true.
https://github.com/Expensify/App/blob/2157057bdc23aaf1eb48846c9a87cd33ff6645ae/src/pages/home/ReportScreen.js#L97-L100
https://github.com/Expensify/App/blob/2157057bdc23aaf1eb48846c9a87cd33ff6645ae/src/pages/home/ReportScreen.js#L266-L267

`isLoadingReportActions` will become `true` when the `openReport` optimistic data is merged.
https://github.com/Expensify/App/blob/2157057bdc23aaf1eb48846c9a87cd33ff6645ae/src/libs/actions/Report.js#L334-L339

Instead of using SET, we should just set the default value of `isLoadingReportActions` to true which is already the case today.
_`isLoadingReportActions` is `isLoadingInitialReportActions` in the latest code._
https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/pages/home/ReportScreen.js#L620-L623
https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/pages/home/ReportScreen.js#L495-L501

@youssef-lr should the solution be reviewed first or should I just immediately create the follow-up PR to fix this?

**Comment by youssef-lr** [comment] 2024-02-27 07:21
You can start on the PR, thanks!

**Comment by paultsimura** [comment] 2024-02-27 08:33
Hey, @bernhardoj just a note: a part of the root cause is that the money report actions have no `childReportID` when created offline – this is being fixed in https://github.com/Expensify/App/pull/37232

**Comment by bernhardoj** [comment] 2024-02-27 10:50
@paultsimura thanks, yep I noticed about that too, but not really sure whether it's intentional or not.

Here is the PR to fix this issue https://github.com/Expensify/App/pull/37269

**Comment by puneetlath** [comment] 2024-02-27 18:32
Looks like [this revert](https://expensify.slack.com/archives/C01GTK53T8Q/p1709050485476509) fixed it. Closing, but feel free to reopen if I'm mistaken.

**Closed by puneetlath** 2024-02-27 18:32 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted
