### ISSUE TITLE
Workspace deleted member added back if invite and delete in offline mode.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14327] opened 2023-01-16 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Setting => Workspaces.
2. Open any workspace or create if not exist.
3. Open Manage members.
4. Turn off network (Go offline).
5. Press on Invite and select 1 or more member for invitation.
6. Press Invite it will go back to members list.
7. Select newly added users and press on remove.
8. Confirm user deletion.
9. Turn on network and wait for few seconds.

## Expected Result:
Workspace deleted members shouldn’t added back if we perform Invite and delete in offline mode.

## Actual Result:
Workspace deleted members added back if we perform Invite and delete in offline mode.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.2.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212747790-d929297b-8f7b-4c6c-9e31-5985e263130a.mov

https://user-images.githubusercontent.com/43996225/212747810-d77d136c-2e64-428e-bd13-0747abb3c7e2.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673796299035539https://expensify.slack.com/archives/C049HHMV9SM/p1673796299035539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2023-01-17 04:46
Please see my comment in the GH issue. I don't think this is a bug.

**Comment by dylanexpensify** [comment] 2023-01-17 14:22
reviewing now!

**Comment by dylanexpensify** [comment] 2023-01-18 15:47
Agree, not a bug, closing

**Closed by dylanexpensify** 2023-01-18 15:47 UTC
Labels: Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-01-18 16:24
@dylanexpensify I believe following my earlier comment, others weren't able to reproduce the bug. Is that correct? I'm asking because that Slack link in the OP doesn't seem to work for me.

**Comment by dylanexpensify** [comment] 2023-01-18 16:29
@JmillsExpensify I can't access that link either - mind linking the slack post you referenced above?

**Comment by JmillsExpensify** [comment] 2023-01-18 17:34
Oh to clarify, I'm asking you the same question.

**Comment by dylanexpensify** [comment] 2023-01-18 18:25
AH - I see! Sorry, I was not able to reproduce this!
