### ISSUE TITLE
[$1000]  The chat room URL attached in the email sent by the system is missing the reportID.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23932] opened 2023-07-31 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to any account.
2. Send a message to Account A.
3. Wait for the system email sent to Account A's email with the subject "Expensify Chat between…"
4. Reply to that email.
5. Leave the email content EMPTY and click SEND.
6. Wait for the other system email stating "Unable to add comment or attachment to Concierge."
7. Check the link "in the chat room," which is included in the email

## Expected Result: 
The link should contain the correct reportID to ensure that users are redirected to the appropriate chat room.
## Actual Result: 
The link is missing the  reportID.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Steps](https://github.com/Expensify/App/assets/43996225/5a5fc204-1e99-459c-99ae-815ba908c711)

<img width="1280" alt="image" src="https://github.com/Expensify/App/assets/11725910/aa84712c-3e56-4c6c-8da8-a29ee90ec213">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690481747940079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0e397e5e063ddf9</li>
        <li>Upwork Job ID: 1686493388354629632</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment] 2023-07-31 16:20
> I wasn't able to add your comment or attachment in [in the chat room](https://new.expensify.com//r/)

The word "**in**" is doubled in the sentence too 😀

**Comment by jeet-dhandha** [comment] 2023-07-31 16:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The reportID is not available in link provided in response email from concierge@expensify.com

### What is the root cause of that problem?
- Don't know its in backend

### What changes do you think we should make in order to solve the problem?
- If we have the receiver's email like "replies+2173054415376820@expensify.com" and the sender's email "jeetcpu@gmail.com".
- Then we can get the report id corresponding to that chat. 

Note:
- This could cause an issue when sender's email was used as jeetcpu+1@gmail.com and thus giving wrong reportID.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by slafortune** [comment] 2023-08-01 21:45
I updated the screenshot - report looks good!

**Comment by s77rt** [comment] 2023-08-02 22:26
@slafortune This looks internal. Can you please apply `Internal` here.

**Comment by pecanoro** [comment] 2023-08-04 08:31
I will take a look next week, most people won't send an empty reply so I am moving it a weekly since it's unlikely people will trigger this.

**Comment by pecanoro** [comment] 2023-08-08 13:42
I am going on vacation for a few days so I will handle after.

**Comment by pecanoro** [comment] 2023-08-18 10:19
I am going to assign @s77rt since this is a fix in one of our private repos so we can't have a C+ to review it.

**Comment by slafortune** [comment] 2023-08-29 20:07
It looks like only the bug reporter @tranvantoan-qn needs to be paid here - is that correct @pecanoro ?

**Comment by pecanoro** [comment] 2023-08-29 20:31
@slafortune Yes!

**Comment by slafortune** [comment] 2023-08-29 21:36
Thanks!  Offer sent @tranvantoan-qn here -https://www.upwork.com/nx/wm/offer/26399899

**Comment by tranvantoan-qn** [comment] 2023-09-20 09:30
@slafortune This task is CLOSED but the Upwork payment has been pending since August 28th. Could you please release the payment so that we don't have to spend time checking it? 😊

**Comment by pecanoro** [comment] 2023-09-25 03:44
@tranvantoan-qn I will reassign it to someone else.

**Comment by pecanoro** [comment] 2023-09-25 03:46
@zanyrenney We only need to pay the reporting bonus. I am not sure if we only need to release the payment or send it again.

**Comment by zanyrenney** [comment] 2023-09-25 03:52
@pecanoro okay, on it now for you!

**Comment by tranvantoan-qn** [comment] 2023-09-25 03:55
I got the payment, thank you!

**Comment by zanyrenney** [comment] 2023-09-25 03:56
Woo, all good, closing again now payment complete.

**Payment summary:**

Reporting bonus - $250 @tranvantoan-qn  - PAID.

**Closed by zanyrenney** 2023-09-25 03:56 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
