### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Workspace - Highlight on text is displayed when email is pressed in Bills screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24591] opened 2023-08-15 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24244

## Action Performed:
1. Open app in iOS
2. Go to Settings > Workspaces > Select a Workspace > Bills
3. Tap on the email shown in the Manage your bills section

## Expected Result:
No highlight on text when email is pressed

## Actual Result:
Highlight is displayed when email is pressed
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.5

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/455abaaf-662e-436d-afe8-50538a6451da

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7076c95fa743b6d</li>
        <li>Upwork Job ID: 1692325576877830144</li>
        <li>Last Price Increase: 2023-08-18</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26302490</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-08-15 20:27
I'm unable to reproduce this at all on iOS (in either an expensifail account, or in a public domain account).

**Comment by joekaufmanexpensify** [comment] 2023-08-15 20:28
@allroundexperts could you please share what you're seeing in a public domain account?

**Comment by joekaufmanexpensify** [comment] 2023-08-15 20:40
I don't think that is a bug. There is nothing to select there purposefully as public domain emails do not have a bill intake email address to send in bills (as they don't have a private domain).

**Comment by joekaufmanexpensify** [comment] 2023-08-15 21:17
Got it, thanks for clarifying that!

**Comment by joekaufmanexpensify** [comment] 2023-08-15 21:18
Yeah, I cannot reproduce this at all on iOS v1.3.54-11. This is what I see: 

![7C81EB10-C019-4D62-971D-1DD90FBA4465-2023-08-15 21_17_40 744](https://github.com/Expensify/App/assets/54866469/edce2ffa-5e7f-4099-a485-de9f2c928f8f)

**Comment by joekaufmanexpensify** [comment] 2023-08-15 21:22
You mean long pressing on the bill intake email address? If so, doing that highlights the email (as long as I am long pressing). But does not result in the check mark appearing. Which feels like expected behavior IMO.

**Comment by joekaufmanexpensify** [comment] 2023-08-18 18:01
Awaiting proposals

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:52
Not overdue.

**Comment by joekaufmanexpensify** [comment] 2023-08-22 13:12
Still awaiting proposals

**Comment by joekaufmanexpensify** [comment] 2023-08-22 13:15
Ah, thanks! I had missed that one.

**Comment by mollfpr** [comment] 2023-08-22 14:24
@allroundexperts I think we don't need to make it platform-specific since `suppressHighlighting` is only for iOS.

I just tested the [proposal](https://github.com/Expensify/App/issues/24591#issuecomment-1679380927), and it fixed the issue. So let's go with @allroundexperts proposal.

🎀 👀 🎀 C+ reviewed!

**Comment by joekaufmanexpensify** [comment] 2023-08-23 19:43
Pending @MonilBhavsar's review

**Comment by MonilBhavsar** [comment] 2023-08-24 07:26
Reviewing now

**Comment by mollfpr** [comment] 2023-08-24 11:08
I think it's a regression from https://github.com/Expensify/App/pull/19391. Before that, we used `Text` with `suppressHighlighting` in the `CopyTextToClipboard` component.

**Comment by MonilBhavsar** [comment] 2023-08-24 11:14
Got it, thanks for looking!
It's been a while, so let's fix that here. Agree with not making platform specific

**Comment by joekaufmanexpensify** [comment] 2023-09-01 12:28
@mollfpr / @allroundexperts mind completing the BZ checklist here so we can prep to issue payment next week?

**Comment by joekaufmanexpensify** [comment] 2023-09-05 20:24
[Bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1693945428966069)

**Comment by joekaufmanexpensify** [comment] 2023-09-05 20:26
@allroundexperts was assigned to this issue on 2023-08-24, and the PR was merged on 2023-08-25, so this qualifies for a speed bonus. This means we need to issue the following payments: 

- @allroundexperts - $1,500 ($1000 for PR + $500 speed bonus). Paid via NewDot. 
- @mollfpr - $1,500 ($1000 for C+ review +$500 speed bonus). Paid via Upwork. 
- No reporting bonus here.

**Comment by mollfpr** [comment] 2023-09-06 04:40
Sorry for the delay @joekaufmanexpensify 

> [@mollfpr / @allroundexperts] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/19391

> [@mollfpr / @allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/19391/files#r1316716014

> [@mollfpr / @allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr / @allroundexperts] Determine if we should create a regression test for this bug.
 [@mollfpr / @allroundexperts] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Login with a expensify.cash email or reverse the condition [here](https://github.com/allroundexperts/Expensify/blob/4302f5c258151146fda8d88f36bf1e1b6259894d/src/pages/workspace/bills/WorkspaceBillsFirstSection.js#L66).
2. Go to Settings -> Work spaces -> Select Any workspace -> Bills.
3. Click on the email in the Manage your bills section 
4. Verify that the click does not highlight the email.
5. 👍 or 👎

**Comment by joekaufmanexpensify** [comment] 2023-09-06 16:13
This is a pretty minor bug that doesn't impact the user experience, so my 2c is no regression test is needed here.

**Comment by joekaufmanexpensify** [comment] 2023-09-06 16:17
@mollfpr $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-09-06 16:18
@allroundexperts could you please request $1,500 in NewDot and confirm here once complete?

**Comment by joekaufmanexpensify** [comment] 2023-09-06 17:45
Great, thanks! Going to close this out for now. If your request isn't paid within the next 7 days, LMK and I will look into it.

**Comment by joekaufmanexpensify** [comment] 2023-09-06 17:46
Note for the individual paying, that the payment summary message is [here. ](https://github.com/Expensify/App/issues/24591#issuecomment-1707264648)

**Closed** 2023-09-06 17:46 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-10 10:23
$1,500 approved for payment via NewDot based on BZ summary.
