### ISSUE TITLE
[HOLD for Payment 2024-09-06] [$250] Navigated back to the home screen after granting for Camera permission

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46422] opened 2024-07-29 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cristipaval 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722253630425759
## Action Performed:
1. Start Submit Expense flow from Global Create
2. Tap on the Scan tab
3. Go to the Phone settings from the system prompt asking for Camera permission
4. Go back to the App by tapping on `<- NewExpensify` on the top left corner of the iPhone
## Expected Result:
Should resume the Submit Expense flow from where I left
## Actual Result:
Landed on the home screen and I had to start the Submit Expense flow again
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/264bf230-249b-4786-bd29-69f93ecd840f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4e1ed614d93976d</li>
        <li>Upwork Job ID: 1818030342834766613</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103467157</li>
<li>ravindra-encoresky | Contributor | 103467159</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2024-07-29 21:06
Let's make sure to test this for other SmartScan flows where the user grants camera permission (i.e. track expense).

**Comment by DylanDylann** [comment] 2024-07-30 09:23
I can't reproduce this bug on IOS

**Comment by ravindra-encoresky** [comment] 2024-07-31 10:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On scan tab, alert for asking camera permission open System Setting app, coming back after grating camera permission reloads the app. It should resume from previous page
### What is the root cause of that problem?
if we change any app permission in iOS from System Setting, it reloads the app to apply it. As its iOS's default behaviour.
### What changes do you think we should make in order to solve the problem?

Since it’s OS' natural behaviour to reload the app when permissions changes in System Settings, we can use the Onyx database to track the last screen accessed before the settings change. When the app returns from the settings, we’ll retrieve the last screen from Onyx and navigate back to it if available.

1. We will create a action to save permission asked status
```tsx
function handlePermissionAfterRestart(status: boolean) {
    Onyx.merge(ONYXKEYS.HANDLE_PERMISSION_AFTER_APP_RESTART, status);
}
```
2. Set value to true below Linking.openSettings();
https://github.com/Expensify/App/blob/73ec7f8e3e3b34b81c5bbda91290ecb44aafc373/src/libs/fileDownload/FileUtils.ts#L74-L79

```tsx
handlePermissionAfterRestart(true);
```

3. Check this value after app reload and navigate to scan screen if value is true. Also reset value back to false in Onyx database
https://github.com/Expensify/App/blob/73ec7f8e3e3b34b81c5bbda91290ecb44aafc373/src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.tsx#L27-L30
```tsx
if (handlePermissions) {
            handlePermissionAfterRestart(false);
            interceptAnonymousUser(() =>
                IOU.startMoneyRequest(
                    CONST.IOU.TYPE.SUBMIT,
                    // When starting to create an expense from the global FAB, there is not an existing report yet. A random optimistic reportID is generated and used
                    // for all of the routes in the creation flow.
                    ReportUtils.generateReportID(),
                ),
            );
        }
```


### What alternative solutions did you explore? (Optional)

**Comment by ravindra-encoresky** [comment] 2024-07-31 10:35
Contributor details
Your Expensify account email: ravindra.singh@encoresky.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f09435e9ae8b77c7

**Comment by sakluger** [comment] 2024-08-01 18:18
@DylanDylann just to make sure, when you tried reproducing, did you remove camera permissions first?

**Comment by sakluger** [comment] 2024-08-01 18:42
Commenting for melvin

**Comment by DylanDylann** [comment] 2024-08-02 05:20
I can reproduce now. To reproduce we need to toggle on the permission before navigating back

https://github.com/user-attachments/assets/2bc08858-5bcd-4a82-b96d-4ec40c7e1958

**Comment by DylanDylann** [comment] 2024-08-02 05:27
More information for contributors, When an iOS app requests camera access and the user grants permission, the app restarts due to changes in the app's permission settings. We need to handle this more smoothly and avoid the appearance of a reload.

**Comment by ravindra-encoresky** [comment] 2024-08-02 07:13
@DylanDylann thanks for the more clarification, I've tried other solutions as well but somehow it had to take a little navigation before it re-opens the previous page like I added in proposal above.

thanks.

**Comment by DylanDylann** [comment] 2024-08-02 07:37
@ravindra-encoresky Thanks for your proposal. Will review soon

**Comment by DylanDylann** [comment] 2024-08-05 08:14
@ravindra-encoresky Could you please provide a testing branch for your solution?

**Comment by ravindra-encoresky** [comment] 2024-08-05 16:27
> @ravindra-encoresky Thanks for your idea. Could you please provide a testing branch for your solution?

Here is the branch with working sample - https://github.com/ravindra-encoresky/expensify/tree/46422-Navigated-home-after-camera-permission

Branch contain the code with basic working sample, we can improve it as our requirements

**Comment by DylanDylann** [comment] 2024-08-06 10:56
https://github.com/user-attachments/assets/b71ab0d4-2198-4eaf-82e0-e0522ff2ae6b

@ravindra-encoresky After going back to scanning page, an error happens

**Comment by ravindra-encoresky** [comment] 2024-08-06 17:09
https://github.com/user-attachments/assets/76950b43-82cc-444f-bd0f-99fa09ef6bdc

I am not facing this issue, please can you provide me more detail, on which ios version you are checking.

**Comment by ravindra-encoresky** [comment] 2024-08-07 05:40
@DylanDylann I think you are testing iOS simulator, camera is not available in iOS simulator thats why you are getting this issue. Also it has no relation to particular changes in this branch, this is existing behaviour

**Comment by DylanDylann** [comment] 2024-08-07 08:28
@ravindra-encoresky Thanks for your update. This is an edge case when the app restarts due to changes in the app's permission settings. Let's go with @ravindra-encoresky's [proposal](https://github.com/Expensify/App/issues/46422#issuecomment-2260196192)




🎀 👀 🎀 C+ reviewed

**Comment by ravindra-encoresky** [comment] 2024-08-07 09:43
hi @roryabraham proposal submitted on upwork.

**Comment by roryabraham** [comment] 2024-08-08 17:58
Thanks for the proposal @ravindra-encoresky, and good job finding the root cause (that the iOS app reloads with changed permissions). However, the solution you've proposed simply isn't flexible or reusable enough. There could be other flows that trigger permissions changes, and we won't always want to navigate to the scan receipt page.

I think you're on the right track though - when triggering a permissions change modal, we want to stash the current navigation state (is the route enough?) and then restore it when the app reopens on permissions change.

I'd also be curious to see if this is discussed in the React Navigation docs and perhaps has a prescribed solution?

**Comment by DylanDylann** [comment] 2024-08-09 03:05
> I think you're on the right track though - when triggering a permissions change modal, we want to stash the current navigation state (is the route enough?) and then restore it when the app reopens on permissions change.

Agree at this point, we already did that in the test branch by using a new Onyx key called lastScreen. In the PR phase, maybe we need to adjust to set the current route to `lastScreen` field when the user opens the permission setting and then use `lastScreen` to restore the old state

**Comment by DylanDylann** [comment] 2024-08-09 03:06
> I'd also be curious to see if this is discussed in the React Navigation docs and perhaps has a prescribed solution?

It sounds great to me

cc @ravindra-encoresky

**Comment by ravindra-encoresky** [comment] 2024-08-09 06:27
> I'd also be curious to see if this is discussed in the React Navigation docs and perhaps has a prescribed solution?

I have not found anything specific in React Navigation Docs but on multiple places same solution is recommended.

https://github.com/zoontek/react-native-permissions/issues/307
https://stackoverflow.com/questions/31706447/how-can-i-prevent-ios-apps-from-resetting-after-changing-camera-permissions

**Comment by ravindra-encoresky** [comment] 2024-08-12 07:57
> 📣 @ravindra-encoresky 🎉 An offer has been automatically sent to your Upwork account for the Contributor role 🎉 Thanks for contributing to the Expensify app!
> 
> [Offer link](https://www.upwork.com/nx/wm/offer/103467159) [Upwork job](https://www.upwork.com/jobs/~01a4e1ed614d93976d) Please accept the offer and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

Offer accepted. PR will be submitted by today 12 Aug 2024.

**Comment by ravindra-encoresky** [comment] 2024-08-27 05:05
hi @m-natarajan @sakluger since the PR is done, could you please close the job on Upwork ?

thanks.

**Comment by DylanDylann** [comment] 2024-09-06 07:45
@sakluger  The PR was deployed to production on August 31st. The payment should be issued on September 6th

**Comment by ravindra-encoresky** [comment] 2024-09-09 11:11
@DylanDylann @sakluger thanks, waiting for the job to be completed on upwork.

**Comment by sakluger** [comment] 2024-09-10 21:11
Thanks everyone and sorry for the delay - our usual automation failed, so I will handle the updates and payments manually now. @DylanDylann can you please let us know if you think we need regression test steps for this case?

**Comment by sakluger** [comment] 2024-09-10 21:13
Summarizing payment on this issue:

Contributor: @ravindra-encoresky $250, paid via Upwork
Contributor+: @DylanDylann $250, paid via Upwork

**Comment by DylanDylann** [comment] 2024-09-11 07:29
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


**Regression Test Proposal: Only for IOS native App**

1. Start Submit Expense flow from Global Create
2. Tap on the Scan tab
3. Go to the Phone settings from the system prompt asking for Camera permission
4. Go back to the App by tapping on <- NewExpensify on the top left corner of the iPhone
5. Verify that App navigate to scan screen


Do we agree 👍 or 👎

**Comment by sakluger** [comment] 2024-09-11 23:18
Looks good. Thanks!

**Closed by sakluger** 2024-09-11 23:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
