### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Task - Complete task and reopened task message color change offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22060] opened 2023-07-02 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select assign a task
2. Enter title and assign it to a user
3. Click Confirm Task
4. Go to task report screen
5. Click on mark as done button
6. Go to offline and check complete task message

## Expected Result:
Font color of complete task message greyed out

## Actual Result:
Font color should not be change

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f366ac1a-3653-4801-bba6-13f697b4d84e

https://github.com/Expensify/App/assets/93399543/096e7609-b8b5-499c-9eb5-f61e4aa2a6c2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688196702363109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165856583086f9238</li>
        <li>Upwork Job ID: 1675910001043406848</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-07-04 17:09
@abdulrahuman5196 how do these proposals look to you?

**Comment by abdulrahuman5196** [comment] 2023-07-07 20:15
Sorry for the delay. Will provide update in the morning

**Comment by abdulrahuman5196** [comment] 2023-07-08 09:20
@samh-nl 's proposal looks good and works well. We can only set the pending action null for Complete task and reopen task.
@samh-nl I don't think we need to set pending action null for other cases which is already working properly on offline. Unless there is some issue happening due to this. AFAIK there is none.

🎀 👀 🎀
C+ Reviewed

cc: @MitchExpensify

**Comment by abdulrahuman5196** [comment] 2023-07-08 09:22
@ChengDzun your proposal is same as the accepted proposal. Even if we had considered other cases, it would have been easily caught in PR review. So I am going with the first proposal in this issue.

**Comment by abdulrahuman5196** [comment] 2023-07-08 09:27
@luacmartins C+ approved comment is here - https://github.com/Expensify/App/issues/22060#issuecomment-1626965785
We can clear pendingActions on successData for Complete task and reopened task case. 

For extra cases of create,edit or cancel mentioned by contributors, there is no point in clearing as it doesn't have any effect currently AFAIK. If required for consistency purpose we can clear on those cases as well, but there won't be difference anyways. So opting not to do it to avoid any regressions.

**Comment by abdulrahuman5196** [comment] 2023-07-08 15:07
You have to wait till the proposal is accepted by internal engineer and the issue is assigned to you.

**Comment by luacmartins** [comment] 2023-07-10 17:20
Not overdue, just assigned a contributor.

**Comment by MitchExpensify** [comment] 2023-07-10 22:09
Mind applying to the Upwork job here for eventual payment @samh-nl ?https://www.upwork.com/jobs/~0165856583086f9238 

Thanks!

**Comment by abdulrahuman5196** [comment] 2023-07-13 18:24
>days elapsed: 3

Doesn't days elapsed 3 mean eligible for bonus?

I think this issue could be considered for urgency bonus

**Comment by luacmartins** [comment] 2023-07-13 18:47
@abdulrahuman5196 thanks for raising this. The threshold is **within** 72h (3 business days). I agree that the comment above/guidelines are confusing. We're working on it internally to make this less ambiguous.

**Comment by abdulrahuman5196** [comment] 2023-07-13 19:00
>The threshold is within 72h

@luacmartins 
Melvin message got me confused. Yeah I aware of this threshold.

Seems this issue missed the 72 hours mark by just 1.5 hours 😢

**Comment by MitchExpensify** [comment] 2023-07-18 20:55
Added a reminder to pay to my calendar 👍 

Friendly reminder to address the above steps when you get a chance @abdulrahuman5196 - Thanks!

**Comment by abdulrahuman5196** [comment] 2023-07-22 14:02
BZ Checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/17992#issuecomment-1646590558

>Determine if we should create a regression test for this bug.

Yes

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Click + icon and select assign a task
2) Enter title and assign it to a user
3) Click Confirm Task
4) Go to the task report screen
5) Click on the Mark as done button
6) Open the report menu and click the Mark as incomplete menu option
7) Open the report menu and click the Cancel menu option
8) Go offline
9) Verify that the task completion, task re-opening and task cancellation messages added to the report do not become grayed out

**Comment by abdulrahuman5196** [comment] 2023-07-22 14:02
Thanks for the ping @MitchExpensify. Completed the checklist.

**Comment by MitchExpensify** [comment] 2023-07-22 23:51
Thanks @abdulrahuman5196 https://github.com/Expensify/Expensify/issues/302117

**Comment by luacmartins** [comment] 2023-07-25 22:15
Just waiting for payment

**Comment by MitchExpensify** [comment] 2023-07-25 22:40
Paid reporting & C+!

Mind applying to this Upwork job and we'll close this out once I issue payment @samh-nl ?

**Comment by MitchExpensify** [comment] 2023-07-26 21:35
No worries! 👍 I noticed a "this account no longer exists" message in Upwork but wondered what was up. Will keep this issue open until we get payment over to you

**Comment by MitchExpensify** [comment] 2023-07-28 12:42
Great @samh-nl ! Offer sent.

**Comment by luacmartins** [comment] 2023-08-08 18:36
Seems like we're only pending payments here.

**Comment by MitchExpensify** [comment] 2023-08-08 22:49
Paid! thanks for the catch @luacmartins

**Closed** 2023-08-08 22:49 UTC
Labels: External, Weekly, Awaiting Payment, Bug
