### ISSUE TITLE
Infinite loading when navigating to a chat without access

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#19143] opened 2023-05-17 21:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot
2. From another app, click on the URL with the conversation ID to any combination of 1-4 numbers. E.g https://staging.new.expensify.com/r/1234
3. Verify You see a You don't have access to this chat message in the conversation history
4. Repeat with non-valid conversation ID (e..g, staging.new.expensify.com/r/sometxt)

## Expected Result:
User should be redirected to "Hmmm.. it's not here" page
![image](https://github.com/Expensify/App/assets/44479856/50a8b720-e929-4341-958a-252f605ee45d)

## Actual Result:
Infinite loading when navigating to a chat without access -  "Hmmm.. it's not here" page is never displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [X] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15-5

**Reproducible in staging?:** Yes
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 2 test cases are failing because of this issue: 

1. [Navigate to Chat without access (Valid and non valid ID)](https://expensify.testrail.io/index.php?/tests/view/3460952)
2. [Web/mWeb - Navigate to IOU via link](https://expensify.testrail.io/index.php?/tests/view/3460954)

**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/44479856/98bb93e3-73fb-4030-bac5-a2b1e665605c)

https://github.com/Expensify/App/assets/44479856/477bf7ea-35d9-4aa5-90b7-4c4cf5c7da5e

**Expensify/Expensify Issue URL:** N/A

**Issue reported by:** Applause - Internal team
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2023-05-17 21:42
Hmmm looks like it could be a backend issue, will investigate internally

**Comment by jasperhuangg** [comment] 2023-05-17 22:15
Looks like it was caused by https://github.com/Expensify/App/pull/19056, reverting the PR

**Comment by jasperhuangg** [comment] 2023-05-17 22:41
CPing a fix for this now, all good!

**Comment by jasperhuangg** [comment] 2023-05-17 23:38
Retested on staging and this is fixed, closing

**Closed by jasperhuangg** 2023-05-17 23:38 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly, Bug
