### ISSUE TITLE
[$500] IOU - LHN member avatar is bigger for an opened IOU details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34985] opened 2024-01-23 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal
**Slack conversation:**

## Action Performed:
1. Log in with a new gmail account
2. Create a workspace
3. Do a scan IOU in the workspace chat
4. Open the IOU
5. Open the IOU again
6. Click on the header to go back to the previous page
7. Open the IOU again

## Expected Result:
The avatar should be smaller.

## Actual Result:
LHN member avatar is bigger for an opened IOU details page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1bf178d0-c41a-48f3-9cc8-af4436bec7b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171b04298406816ee</li>
        <li>Upwork Job ID: 1749868382912253952</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Contributor | 28120108</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-23 18:56
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by Tony-MK** [comment] 2024-01-24 02:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `AvatartWithDisplayName`, `HeaderView`, `SidebarUtils`, and `OptionsListUtils` files use the `ReportUtils.shouldReportShowSubscript`.



It is to check if the `<SubscriptAvatar` component should be displayed.

https://github.com/Expensify/App/blob/bb86e24b78efbbc008aca3730d2a0394da3aa0dd/src/libs/ReportUtils.ts#L4111
Hence, the `ReportUtils.shouldReportShowSubscript` returns `true` in this case beacase `isExpenseRequest` is `true`.

Therefore, the `AvatartWithDisplayName` will display a subscript

### What changes do you think we should make in order to solve the problem?

The fact that `ReportUtils.shouldReportShowSubscript` is used in several components, i don't think is viable to change it.

We should create a prop, such as `shouldShowSubscriptAvatar`, which is passed to `HeaderWithButton` in the `MoneyRequestHeader`. 

Furthermore, by default, the `shouldShowSubscriptAvatar` prop will be set to `true`. 

Therefore, we will use `shouldShowSubscriptAvatar` in the `AvatarWithDisplayName` component as displayed below.

```
{shouldShowSubscriptAvatar && ReportUtils.shouldReportShowSubscript(report) ? (
        <SubscriptAvatar
// ReportUtils.shouldReportShowSubscript is also used below for styling
```

Finally, set the `shouldShowSubscriptAvatar` prop to `false` in `MoneyReqesutHeader` to ignore the output of `ReportUtils.shouldReportShowSubscript`.

**Comment by Tony-MK** [comment] 2024-01-24 02:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `AvatartWithDisplayName`, `HeaderView`, `SidebarUtils`, and `OptionsListUtils` files use the `ReportUtils.shouldReportShowSubscript`.

It is used to check if the `<SubscriptAvatar` component should be displayed.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111-L4113

Hence, the `ReportUtils.shouldReportShowSubscript` returns `true` in this case because [`isExpenseRequest`](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111) is `true` and is `false` for the IOU chat report.

Therefore, the `AvatartWithDisplayName` will display a subscript

### What changes do you think we should make in order to solve the problem?

The fact that `ReportUtils.shouldReportShowSubscript` is used in several components, I don't think is viable to change it.

We should create a prop, such as `shouldShowSubscriptAvatar`, which is passed to `HeaderWithButton` in the `MoneyRequestHeader`. 

Furthermore, by default, the `shouldShowSubscriptAvatar` prop will be set to `true`. 

Therefore, we will use `shouldShowSubscriptAvatar` in the `AvatarWithDisplayName` component as displayed below.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/components/AvatarWithDisplayName.tsx#L116-L117

```
{shouldShowSubscriptAvatar && ReportUtils.shouldReportShowSubscript(report) ? (
        <SubscriptAvatar
// ReportUtils.shouldReportShowSubscript is also used below for styling
```

Finally, set the `shouldShowSubscriptAvatar` prop to `false` in `MoneyReqesutHeader` to ignore the output of `ReportUtils.shouldReportShowSubscript`.

**Comment by Tony-MK** [comment] 2024-01-24 03:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `AvatartWithDisplayName`, `HeaderView`, `SidebarUtils`, and `OptionsListUtils` use the `ReportUtils.shouldReportShowSubscript` to determine if the `<SubscriptAvatar` component should be displayed.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111-L4113

Hence, the `ReportUtils.shouldReportShowSubscript` returns `true` in this case because [`isExpenseRequest`](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111) is `true` and is `false` for the IOU chat report.

Therefore, the `AvatartWithDisplayName` will display the subscript component.

### What changes do you think we should make in order to solve the problem?

Since `ReportUtils.shouldReportShowSubscript` and `AvatartWithDisplayName` are used in several components, it is not viable to change it.

We should create a prop, such as `shouldShowSubscriptAvatar`, which will be passed on to `HeaderWithButton` in the `MoneyRequestHeader`. 

Furthermore, by default, the `shouldShowSubscriptAvatar` prop will be set to `true`. 

Therefore, we will use `shouldShowSubscriptAvatar` in the `AvatarWithDisplayName` component.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/components/AvatarWithDisplayName.tsx#L116-L117

```
{shouldShowSubscriptAvatar && ReportUtils.shouldReportShowSubscript(report) ? (
        <SubscriptAvatar
// ReportUtils.shouldReportShowSubscript is also used in one more for style.
```

Finally, set the `shouldShowSubscriptAvatar` prop to `false` in `MoneyReqesutHeader` to ignore `ReportUtils.shouldReportShowSubscript`.

**Result**

https://github.com/Expensify/App/assets/22982173/6684490e-9a62-4d55-b766-be19a780b471

**Comment by Tony-MK** [comment] 2024-01-24 03:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `AvatartWithDisplayName`, `HeaderView`, `SidebarUtils`, and `OptionsListUtils` use the `ReportUtils.shouldReportShowSubscript` to determine if the `<SubscriptAvatar` component should be displayed.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111-L4113

Hence, the `ReportUtils.shouldReportShowSubscript` returns `true` in this case because [`isExpenseRequest`](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111) is `true` and is `false` for the IOU chat report.

Therefore, the `AvatartWithDisplayName` will display the subscript component.

### What changes do you think we should make in order to solve the problem?

Since `ReportUtils.shouldReportShowSubscript` and `AvatartWithDisplayName` are used in several components, it is not viable to change it.

We should create a prop, such as `shouldShowSubscriptAvatar`, which will be passed on to `HeaderWithButton` in the `MoneyRequestHeader`. 

Furthermore, by default, the `shouldShowSubscriptAvatar` prop will be set to `true`. 

Therefore, we will use `shouldShowSubscriptAvatar` in the `AvatarWithDisplayName` component.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/components/AvatarWithDisplayName.tsx#L116-L117

```
{shouldShowSubscriptAvatar && ReportUtils.shouldReportShowSubscript(report) ? (
        <SubscriptAvatar
// ReportUtils.shouldReportShowSubscript is also used in one more for style.
```

Finally, set the `shouldShowSubscriptAvatar` prop to `false` in `MoneyReqesutHeader` to ignore `ReportUtils.shouldReportShowSubscript`.

**Result**

https://github.com/Expensify/App/assets/22982173/6684490e-9a62-4d55-b766-be19a780b471

### What changes do you think we should make in order to solve the problem?

If we want the option in the sidebar to change as well, then it is much better to remove the [`isExpenseRequest`](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111) condition from the `ReportUtils.shouldReportShowSubscript` function.

**Comment by Tony-MK** [comment] 2024-01-24 03:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `AvatartWithDisplayName`, `HeaderView`, `SidebarUtils`, and `OptionsListUtils` use the `ReportUtils.shouldReportShowSubscript` to determine if the `<SubscriptAvatar` component should be displayed.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111-L4113

Hence, the `ReportUtils.shouldReportShowSubscript` returns `true` in this case because [`isExpenseRequest`](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111) is `true` and is `false` for the IOU chat report.

Therefore, the `AvatartWithDisplayName` will display the subscript component.

### What changes do you think we should make in order to solve the problem?

Since `ReportUtils.shouldReportShowSubscript` and `AvatartWithDisplayName` are used in several components, it is not viable to change it.

We should create a prop, such as `shouldShowSubscriptAvatar`, which will be passed on to `HeaderWithButton` in the `MoneyRequestHeader`. 

Furthermore, by default, the `shouldShowSubscriptAvatar` prop will be set to `true`. 

Therefore, we will use `shouldShowSubscriptAvatar` in the `AvatarWithDisplayName` component.

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/components/AvatarWithDisplayName.tsx#L116-L117

```
{shouldShowSubscriptAvatar && ReportUtils.shouldReportShowSubscript(report) ? (
        <SubscriptAvatar
// ReportUtils.shouldReportShowSubscript is also used in one more for style.
```

Finally, set the `shouldShowSubscriptAvatar` prop to `false` in `MoneyReqesutHeader` to ignore `ReportUtils.shouldReportShowSubscript`.

**Result**

https://github.com/Expensify/App/assets/22982173/2424def4-23bb-408b-ab30-bd72256d74f3


### What changes do you think we should make in order to solve the problem?

If we want the option in the sidebar to change as well, then it is much better to remove the [`isExpenseRequest`](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L4111) condition from the `ReportUtils.shouldReportShowSubscript` function.

**Comment by getusha** [comment] 2024-01-24 10:44
Taking this as a C+

**Comment by getusha** [comment] 2024-01-24 15:31
Opened a discussion
https://expensify.slack.com/archives/C01GTK53T8Q/p1706110187996059

**Comment by getusha** [comment] 2024-01-24 22:13
As per the discussion here https://expensify.slack.com/archives/C01GTK53T8Q/p1706110187996059
We're fine to close this one. @isabelastisser

**Closed** 2024-01-27 00:14 UTC
Labels: External, Daily, Bug
