### ISSUE TITLE
Web  - we are allowing modification of money request details in an inactive workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26302] opened 2023-08-30 15:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings and select "Create Workspace."
2. Click on the plus sign and choose "Request Money."
3. Enter the desired amount and select the created workspace.
4. Pin the workspace in the Left Hand Navigation (LHN) for easy access.
5. Go to settings > workspace and delete the created workspace.
6. Return to the LHN and open the deleted workspace. Navigate to the IOU section.
7. Observe that the unavailable workspace is still accessible, and it's possible to update the IOU (e.g., amount, etc.).

## Expected Result:
It should not be possible to update the IOU with an unavailable workspace.

## Actual Result:
Updating IOU Possible with Unavailable Workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/78d5fb5b-cb67-4220-b9f2-9668cd65249d

https://github.com/Expensify/App/assets/93399543/7209212b-6fee-43ea-8829-127dfe1757e7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692862098073539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-08-30 17:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We don't have any check to check if report(parent report) is archived or not.

### What changes do you think we should make in order to solve the problem?
We can change `canEdit` in `MoneyRequestView`. and use `isArchivedRoom()` and if the room is archived then we don't allow user to change description.
There is a function `canEditMoneyRequest`, in which we can add this additional check for archived room.

We can also add this check if user tried to change using deep link.
We can display `FullPageNotFoundView` for that pages.

### What alternative solutions did you explore? (Optional)

**Comment by michaelhaxhiu** [comment] 2023-09-08 12:24
This is reproducible for sure. But I want to confirm this is true:

>**Expected behavior:**
>It should not be possible to update the IOU with an unavailable workspace.

Like I'm partially sold this is true. But I want to make sure it's intentional.

**Comment by michaelhaxhiu** [comment] 2023-09-08 12:52
Discussing this internally a little and I'll follow up after. We are leaning toward locking down this behavior when a workspace because inactive.

**Comment by Christinadobrzyn** [comment] 2023-09-12 19:02
is this the same issue? https://github.com/Expensify/App/issues/27113

**Comment by michaelhaxhiu** [comment] 2023-09-13 14:22
@Christinadobrzyn I don't see these are duplicates personally. This GH is about modifying/actioning an **existing** money request in an archived workspace. Whereas https://github.com/Expensify/App/issues/27113 is about using a link to create a **new** money request from an archived workspace.

Both related to archived workspaces, but in a different way (e.g. existing vs new requests).

**Comment by michaelhaxhiu** [comment] 2023-09-13 16:16
We are discussing more and this may not be deemed a bug actually. I'll follow up when we reach a point of finality with internal convo, and I'll share those guidelines for visibility of course too.

**Comment by michaelhaxhiu** [comment] 2023-09-20 16:24
So far this is trending toward being a feature, and not a bug. I'm going to close this GH for that reason. We will start to refine our guidelines around archived workspaces and workspaces where members are removed, but for now I want to clarify this isn't a bug.

>expense reports should remain functional and a conversation between admin/approver/submitter should be possible within the expense report still to allow for collaborating on tying up any loose ends.

**Closed by michaelhaxhiu** 2023-09-20 16:24 UTC
Labels: Engineering, Daily, Overdue, Bug

**Comment by tewodrosGirmaA** [comment] 2023-09-20 16:33
@michaelhaxhiu , I am not eligible for payment?
