### ISSUE TITLE
Borders around members are missing - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10365] opened 2022-08-11 19:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click on any workspace
3. Click on members

## Expected Result:
You should be seeing border above and below all the members

## Actual Result:
There's no border around members

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="373" alt="Screenshot 2022-07-27 at 1 29 11 AM" src="https://user-images.githubusercontent.com/43995119/184222847-7129301e-206c-4864-9330-1f4011ad4aca.png">
<img width="373" alt="Screenshot 2022-07-27 at 1 29 04 AM" src="https://user-images.githubusercontent.com/43995119/184222851-c2c571c5-f0a9-4901-a699-9b44dc48ab2f.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658865768953769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DimitriLaw1** [comment] 2022-08-16 05:15
Hey! I solved this problem. This is my first time contributing, so im not sure of the process for submitting. Though i was looking for an upwork link on this thread. How do I go about contributing my solution? (photo below)

<img width="791" alt="Screen Shot 2022-08-16 at 1 11 16 AM" src="https://user-images.githubusercontent.com/43189758/184802936-c8a6e3bb-55fb-4b4e-b249-8cd3b3c6566f.png">
?

**Comment by jasperhuangg** [comment] 2022-08-16 19:27
Hey! @DimitriLaw1 I got assigned to your PR.

So contributors actually need to submit a proposal and have that proposal reviewed before you can open a PR that gets reviewed. You can read more about that [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).

Regardless @cristipaval looks like this should be good to and off to an external contributor so I'm adding the External label. @DimitriLaw1 feel free to write up a proposal explaining what your solution involves and how it solves the problem.

**Comment by jasperhuangg** [comment] 2022-08-16 19:28
@MitchExpensify @DimitriLaw1 already has a PR up but didn't know he had to write a proposal first. Once he writes a proposal feel free to ping me to review it and then we can create an Upwork job

**Comment by DimitriLaw1** [comment] 2022-08-16 19:33
> @MitchExpensify @DimitriLaw1 already has a PR up but didn't know he had to write a proposal first. Once he writes a proposal feel free to ping me to review it and then we can create an Upwork job

yay thanks! super excited about my first pull request!

**Comment by cristipaval** [comment] 2022-08-16 19:44
> 
> Regardless @cristipaval looks like this should be good to hand off to an external contributor so I'm adding the External label.
> 

Thank you @jasperhuangg !

**Comment by DimitriLaw1** [comment] 2022-08-16 20:35
**Proposal** 

**Issue**:
There's no borders appearing around under the components in Manage Members

**Solution**:
The "View" Component on WorkspaceMembersPage.js [line 236]. Controls each cell, but has no border attribute being passed through its properties. 
<img width="922" alt="Screen Shot 2022-08-16 at 4 29 50 PM" src="https://user-images.githubusercontent.com/43189758/184979404-39f8359a-7df8-4900-bf69-7baa6939523d.png">

So I added a top and bottom border to the cell.

**Before Fixing**
<img width="446" alt="Screen Shot 2022-08-16 at 4 33 56 PM" src="https://user-images.githubusercontent.com/43189758/184979931-0a882697-d20f-4b02-b4d6-9eacf51c9152.png">

**After Fixing**
<img width="486" alt="Screen Shot 2022-08-16 at 4 33 15 PM" src="https://user-images.githubusercontent.com/43189758/184980016-b41caba7-b753-4019-850d-824a72143582.png">

**Comment by DimitriLaw1** [comment] 2022-08-16 20:35
> **Proposal**
> 
> **Issue**: There's no borders appearing around under the components in Manage Members
> 
> **Solution**: The "View" Component on WorkspaceMembersPage.js [line 236]. Controls each cell, but has no border attribute being passed through its properties. <img alt="Screen Shot 2022-08-16 at 4 29 50 PM" width="922" src="https://user-images.githubusercontent.com/43189758/184979404-39f8359a-7df8-4900-bf69-7baa6939523d.png">
> 
> So I added a top and bottom border to the cell.
> 
> **Before Fixing** <img alt="Screen Shot 2022-08-16 at 4 33 56 PM" width="446" src="https://user-images.githubusercontent.com/43189758/184979931-0a882697-d20f-4b02-b4d6-9eacf51c9152.png">
> 
> **After Fixing** <img alt="Screen Shot 2022-08-16 at 4 33 15 PM" width="486" src="https://user-images.githubusercontent.com/43189758/184980016-b41caba7-b753-4019-850d-824a72143582.png">

@jasperhuangg

**Comment by jasperhuangg** [comment] 2022-08-16 20:45
@DimitriLaw1 It looks like your solution doesn't entirely match the expected design. Specifically, it looks like there needs to be more padding underneath "Select all". It also looks like the borders are varying thicknesses (when they should only be 1), and they also aren't the correct length.

We want it to look exactly like this:
![image](https://user-images.githubusercontent.com/31285285/184981600-85546afb-d0b9-4ec6-99b5-cfa29435867f.png)

**Comment by jasperhuangg** [comment] 2022-08-16 20:54
@DimitriLaw1, sorry to jump in, but I actually put up a PR really quickly that solves the problem, the solution was to reuse one of the styles we already had defined in styles.js. I'll open up a PR since it's already fixed. Feel free to look around for other issues to work on!

<img width="549" alt="Screen Shot 2022-08-16 at 1 54 32 PM" src="https://user-images.githubusercontent.com/31285285/184983328-2cb6cb4c-30ee-448e-a73b-3d61d091b7ad.png">

**Comment by DimitriLaw1** [comment] 2022-08-16 21:04
@jasperhuangg I saw in your pull request that you changed, 
`},peopleRowOfflineFeedback: {`

Do you mind sharing how you went about troubleshooting this?

**Comment by jasperhuangg** [comment] 2022-08-16 21:20
@DimitriLaw1 Yeah for sure! So normally when there are these types of style fixes they're regressions, meaning that it was working before but something was added that broke it. I looked into the commit history and couldn't find anything, but found these unused `peopleRowOfflineFeedback` styles which had the exact styles needed to add the bottom border. Since they're unused I decided to merge them with another style `peopleRow` that's only being used for the option rows.

**Comment by jasperhuangg** [comment] 2022-08-16 21:26
Ah sorry @MitchExpensify unassigned you before I realized this, does @Puneet-here get compensation for pointing out this bug?

**Comment by MitchExpensify** [comment] 2022-08-17 19:36
Did you fix it as a result of this issue @jasperhuangg ? If "yes" then I think @Puneet-here is due payment

**Comment by jasperhuangg** [comment] 2022-08-17 19:50
Yep! This issue pointed it out, but there's a comment in the PR since we're now entirely sure if the PR needs to be merged, so let's wait on that to get resolved first. @MitchExpensify

**Comment by MitchExpensify** [comment] 2022-08-18 16:06
Cool I'll reopen this so I'm reminded to pay out

**Comment by jasperhuangg** [comment] 2022-09-12 21:48
@MitchExpensify were you able to pay out @Puneet-here for discovering the issue?

**Comment by jasperhuangg** [comment] 2022-09-13 16:17
Yo @dylanexpensify! @MitchExpensify is OOO so I reassigned the External label to get another CM to pay out @Puneet-here for discovering this issue. I was the one who fixed the issue so no other payouts are needed.

**Comment by dylanexpensify** [comment] 2022-09-14 09:45
Yooo! You got it @jasperhuangg!

**Comment by dylanexpensify** [comment] 2022-09-14 09:47
internal: https://www.upwork.com/ab/applicants/1569985949529174016/job-details
external: https://www.upwork.com/jobs/~01fc46a11bac1b40f7

@Puneet-here mind applying to the job to get you paid 🤑 !?

**Comment by Puneet-here** [comment] 2022-09-14 10:24
> @Puneet-here mind applying to the job to get you paid 🤑 !?

Applied! Thanks.

**Comment by dylanexpensify** [comment] 2022-09-14 10:31
offer sent! @Puneet-here

**Comment by Puneet-here** [comment] 2022-09-14 10:34
> offer sent! @Puneet-here

Accepted.

**Comment by dylanexpensify** [comment] 2022-09-14 10:36
payment sent, contract closed, posting removed!

**Closed by dylanexpensify** 2022-09-14 10:36 UTC
Labels: Reviewing, Engineering, Daily, Improvement
