### ISSUE TITLE
Chat - Impossible to identify correct link in header as links are clickable across whole header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20857] opened 2023-06-15 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20484

## Action Performed:
1. Open any chat
2. Send message
3. Create thread
4. Click thread header to the right from header details - a bit higher and lower

## Expected Result:
It should be clear where it takes you if you click

## Actual Result:
Header links are both clickable across the whole width of header. So it is hard to identify what you click - thread settings or link back to parent chat. Click higher - go to settings, click lower - parent chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/59bb2917-01e0-4bbe-ae7d-59132409b905

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-06-16 09:24
I agree, this is not a bug or a blocker, I think I will go ahead and close this @francoisl feel free to reopen if you feel strongly about the improvements, I think they might as well just come up in slack and we can handle that separately there

**Closed by mountiny** 2023-06-16 09:24 UTC
Labels: Engineering, Daily
