### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Selecting all and pasting into the composer prompts user to send an attachment.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18583] opened 2023-05-08 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log into an account.
2. Open a 1-on-1/group chat and click outside the composer to blur it (remove focus).
3. Select everything by pressing Cmd  + A .
4. Click the Edit  option in the toolbar and select Copy .
5. Click on the composer and paste with Cmd  + V .

## Expected Result:
All selected text is pasted into the composer.
## Actual Result:
A new page/modal opens up prompting the user to send an attachment if you perform the steps above in a 1-on-1 chat. Clicking the "Send Attachment" button uploads the background shown on the page which appears in the chat and can be interacted with.
Until you select something else and copy it, pasting in the composer will open this page/modal, even if you're pasting in a different chat, whether that be a 1-on-1 or group chat.
However, if you perform the same steps in a group chat first, the selection is pasted but an error toast notification (see attached screenshot) briefly appears at the top right of the screen stating:
There was an error getting the image you posted.
Similarly, if you try pasting in a different chat after selecting all and copying from a group chat, the text will be pasted, but the error will also be shown, whether that be pasting in a subsequent group chat or 1-on-1.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3. 11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236868610-918a6d1e-4ca8-40d6-b725-2de16b77876c.mp4

![expensify-select-all-bug-error](https://user-images.githubusercontent.com/43996225/236868615-9c451cec-4118-4f21-9753-2fa49d0fc740.png)

https://user-images.githubusercontent.com/43996225/236868616-3ea93274-218e-4ac0-9f24-2167c9eb7b4d.mov

https://user-images.githubusercontent.com/43996225/236868629-519b6cfb-ad64-44c6-80bc-11875c323cf8.mov

https://user-images.githubusercontent.com/43996225/236869258-e6ac0c8b-f220-41ed-a323-912d01155326.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683394374441039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b727a2688d7bb8a9</li>
        <li>Upwork Job ID: 1659288933217681408</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-05-18 20:01
Reproducible

- Chrome
- When I press `Command C` then `Command V` - text pastes, no image
- When I click Edit > Copy then press `Command V` - text pastes, error about image. My reproduction did not specify which image, but there aren't any images in the chat I copied so the error is a bug.

https://github.com/Expensify/App/assets/17131195/3922e75f-ff22-4d14-8e74-9bd607871bc4

**Comment by sonialiap** [comment] 2023-05-18 20:04
The linked PR is in production but this error still shows up so it didn't fix it. Adding External

**Comment by qispark** [comment] 2023-05-19 10:37
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When pasting from a selection, it is showing the attachment dialog whenever an image is part of the selection.

### What is the root cause of that problem?
A block of code inside Composer detects whether an image is contained within the HTML content. If an image exists, then it is treated as an attachment.

What changes do you think we should make in order to solve the problem?
We should detect whether or not text is a part of that HTML content and the plaintext content. If there is text, then we should paste that instead.

We can add the following in `src/components/Composer/index.js` prior to the image HTML check stated above:

```
    handlePaste(event) {
        event.preventDefault();

        const {files, types} = event.clipboardData;
        const TEXT_HTML = 'text/html';
        const TEXT_PLAIN = 'text/plain';

        const plainText = event.clipboardData.getData(TEXT_PLAIN);

        // If paste contains files, then trigger file management
        if (files.length > 0) {
            // Prevent the default so we do not post the file name into the text box
            this.props.onPasteFile(event.clipboardData.files[0]);
            return;
        }

        if (types.includes(TEXT_HTML) && types.includes(TEXT_PLAIN) && plainText.trim() !== '') {
            const pastedHTML = event.clipboardData.getData(TEXT_HTML);
            this.handlePastedHTML(pastedHTML);
            return;
        }

        // If paste contains HTML
        if (types.includes(TEXT_HTML)) {
```

When doing this, pasting any content that contains text will now paste the text into the Composer.


### What alternative solutions did you explore? (Optional)
N/A

**Comment by techievivek** [comment] 2023-05-22 05:32
I can reproduce the same thing by copying GH comments, so IMO we can definitely improve the copy-paste logic here so it doesn't show an error. @parasharrajat, Interested to hear your thoughts on why you may have considered this issue not worth solving, if that was the case.

**Comment by techievivek** [comment] 2023-05-28 08:42
@parasharrajat I totally agree with the point that this issue may not be a critical concern, so perhaps we can consider closing it and prioritize more urgent bugs. But I think we can at least seek proposals to prevent showing the error message about not being able to fetch images. What do you think about it?

<img width="425" alt="Screenshot 2023-05-28 at 2 04 52 PM" src="https://github.com/Expensify/App/assets/35863227/4d7d26db-7c70-4d81-8c81-8cd78a4c5173">

**Comment by qispark** [comment] 2023-05-28 09:10
@techievivek @parasharrajat Have you considered my proposal above? It should be able to prevent showing the error message (on top of correcting the paste behaviour in most scenarios). If there is an expected behaviour for this action, I can tailor the proposal to suit.

**Comment by situchan** [comment] 2023-05-28 16:19
Here's helpful discussion on #14232 about the pasting behavior when mixed text and image in clipboard: https://expensify.slack.com/archives/C01GTK53T8Q/p1674760715010859
It finally landed on doing nothing.
So I vote to close the issue as well considering not critical bug.

**Comment by techievivek** [comment] 2023-05-30 03:55
@parasharrajat Waiting to hear your thoughts on the above comments, if you feel like this is not a critical bug then I am happy to close this out.

**Comment by techievivek** [comment] 2023-05-30 06:03
@parasharrajat I also wanted to hear your opinion on fixing just the error notification that shows up when pasting content https://github.com/Expensify/App/issues/18583#issuecomment-1566008985

**Comment by techievivek** [comment] 2023-06-01 11:14
Not overdue, waiting for @parasharrajat response to the above comment.

**Comment by qispark** [comment] 2023-06-01 22:35
@parasharrajat Yes, the proposal does. It does so by pasting only the text whenever a combination of text and images are copied. By doing this, it doesn't need to load the image, which is the cause for the error message.

**Comment by qispark** [comment] 2023-06-06 00:27
Thanks for the update @parasharrajat - I don't believe the expected behaviour is happening though. From my testing, it either is pasting text with the error modal coming up about the attachment, or it pastes the attachment only but does not send any text.

I'll review again and come up with a new proposal to address the error.

**Comment by qispark** [comment] 2023-06-06 08:33
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When pasted content contains an image, we attempt to get the image via fetch. If this fails, an error dialog appears if there is an error performing this fetch.

### What is the root cause of that problem?
Due to the server's content security policy, images from many domains cannot be fetched. This is why pasting in a local instance works, but on the live staging instance, it fails.

<img width="712" alt="Screen Shot 2023-06-06 at 5 56 38 pm" src="https://github.com/Expensify/App/assets/31749903/abcb8e0c-c299-41b4-bf3b-a5db65572215">


### What changes do you think we should make in order to solve the problem?
I will outline a few possible solutions to consider:

1. Update the content security policy, in particular, the directive related to `connect-src`. (Obviously there will be a security concern if we allow all domains for this policy).
2. Use a web worker to perform the fetch. Will need to update the server's CSP to allow the worker (and the worker only) to perform the fetch itself (giving it rights to all domains). Again, there could be security implications in doing so, but you are limiting it to one file.

I have tested this locally and it works, but it may require some coordination to implement on the server.

3. Use a backend service to fetch the image instead.
4. Exclude the image from the pasted content. Especially as I've found that sending an image as an attachment does not actually send any other text. It is possible to use my previous proposal for this option.


### What alternative solutions did you explore? (Optional)
N/A

**Comment by sonialiap** [comment] 2023-06-13 21:24
@techievivek bump :)

**Comment by techievivek** [comment] 2023-06-15 05:56
Apologies for the delay in responding, as I was ooo.

@qispark, thank you for identifying the root cause of the error. Currently, we are in the process of migrating newDot from AWS to our own server, so addressing CSP-related changes is not within the scope at the moment. However, we can put a hold on the issue and revisit it after the migration is complete.

Regarding the third point, while it is technically feasible to implement backend changes to support image fetching, it might require some effort. Moreover, we don't currently have any similar functionality in our codebase so I will need not to discuss this with the team members to see if this is an option open to us.

I believe the fourth point you suggested could be a temporary solution. We can strip the images from the pasted content, which would help us eliminate the error. If there is a need for image support in the future, we can implement the required backend changes accordingly.

I will also initiate a discussion in the engineering channel to gather input from others regarding the proposed solution.
CC @parasharrajat

**Comment by techievivek** [comment] 2023-06-15 06:20
@qispark, A quick question regarding the copy-paste behaviour. I'm curious to know how it works with images that are fetched from the network, as well as with local images. For example, if I upload an image in Microsoft Word from my computer and then copy-paste the content from the doc to newDot, will the image be displayed correctly?

**Comment by qispark** [comment] 2023-06-15 07:32
Thank you for the update @techievivek .

The behaviour of the paste in the browser really depends on the source application. For example, if copying text and inline images from a Word document, it will actually paste as a single image (and therefore be treated as an attachment). However, if pasting from the Notes app on Mac will treat the output as HTML, but excludes any local images.

From a brief test of iOS and Android. pasting from Chrome does different things:
- iOS, partial text and image: pastes text
- iOS: image only: pastes URL
- Android, partial text and image: pastes text (sometimes special character for the image)
- Android, image only: does nothing

Unsure if pasting behaviour would vary with android version as well.

**Comment by techievivek** [comment] 2023-06-19 15:22
Bought a [discussion](https://expensify.slack.com/archives/C03TQ48KC/p1687187729057429) to the eng-chat room for more thought on this. Thanks for your patience.

**Comment by techievivek** [comment] 2023-06-20 07:50
@qispark @parasharrajat We have agreed to fix the behaviour here by stripping the image part from the pasted content. @qispark, could you please provide an updated proposal outlining the steps to implement this solution? Thanks

**Comment by qispark** [comment] 2023-06-20 10:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

An error modal shows when trying to paste images embedded in HTML.

### What is the root cause of that problem?

This is because of a content security policy preventing the fetch of such images.

### What changes do you think we should make in order to solve the problem?

In `App/src/components/Composer/index.js`, in the handlePaste function, we can remove the part of the code which fetches external images. Instead, we can simply paste the plaintext from the copied contents.

Line 304:


```
        // If paste contains HTML
        if (types.includes(TEXT_HTML)) {
            const pastedHTML = event.clipboardData.getData(TEXT_HTML);

            const domparser = new DOMParser();
            const embeddedImages = domparser.parseFromString(pastedHTML, TEXT_HTML).images;

            // If HTML has img tag, then we strip the images from paste.
            if (embeddedImages.length > 0 && embeddedImages[0].src) {
                const plainText = event.clipboardData.getData('text/plain');
                this.paste(plainText);
                return;
            }

            this.handlePastedHTML(pastedHTML);
            return;
        }
```


### What alternative solutions did you explore? (Optional)

The above solution also has the effect of pasting the image's alt text, which may be undesirable.

One alternative way would be to paste the HTML content. However, if we are pasting images with links attached, it may lead to some formatting issues in the pasted content, such as pasting empty links, e.g:
```
[
](https://www.smh.com.au/national/nsw/bus-safety-set-to-be-boosted-in-nsw-following-horror-crash-20230620-p5di1b.html)
```

One final alternative would be to modify ExpensiMark to strip images.

**Comment by qispark** [comment] 2023-06-21 21:37
Thank you, I will try to create a PR later today.

**Comment by qispark** [comment] 2023-06-22 01:23
Actually, should I wait for the Upwork posting to be created first? @sonialiap @techievivek @parasharrajat

**Comment by qispark** [comment] 2023-06-23 04:35
PR initiated. I've made a request in Slack to turn my account into a high traffic account, currently blocked from testing until that is done.

**Comment by qispark** [comment] 2023-06-29 13:42
Hi @parasharrajat just wondering if you require any changes to the PR, thanks.

**Comment by techievivek** [comment] 2023-07-07 05:22
PR is still in review, and we had to HOLD it for another PR https://github.com/Expensify/expensify-common/pull/555, but since that is merged, we can move forward now.

**Comment by qispark** [comment] 2023-07-14 22:42
I've left a question for @parasharrajat in the PR, was waiting for a response before I continued.

**Comment by techievivek** [comment] 2023-07-25 04:33
@parasharrajat Can you take a look at the [PR](https://github.com/Expensify/App/pull/21476#issuecomment-1647158126) and provide an update, thanks.

**Comment by mvtglobally** [comment] 2023-07-25 04:43
Issue not reproducible during KI retests. (First week)

**Comment by techievivek** [comment] 2023-08-02 05:49
@parasharrajat Any updates here?

**Comment by qispark** [comment] 2023-08-07 06:00
Thank you @techievivek @parasharrajat for checking the PR. Please let me know if this is still eligible for payment and what I should do for that.

**Comment by techievivek** [comment] 2023-08-07 14:46
Yes, this was a tricky one, and we also had to HOLD it because of some parallel developments, so it makes sense that contributors get paid for it.

**Comment by mvtglobally** [comment] 2023-08-16 20:37
Issue not reproducible during KI retests. (Second week)

**Comment by Victor-Nyagudi** [comment] 2023-08-17 21:09
Has this been paid out yet? 

I'd usually wait a little longer before raising this, but since the weekend's almost here, I thought I'd ask now.

**Comment by qispark** [comment] 2023-08-17 21:25
@Victor-Nyagudi It hasn't been paid out yet.

**Comment by Victor-Nyagudi** [comment] 2023-08-22 04:49
Bump @sonialiap.

**Comment by sonialiap** [comment] 2023-08-29 18:37
Sorry guys, I was out. Sending offers out now

- @Victor-Nyagudi report $250
- @qispark fix + bonus $1500 - I can't find your Upwork handle, could you please [apply for the job here](https://www.upwork.com/jobs/~01ce8c946ba2e23476)
- @parasharrajat review + bonus $1500 - please request in newdot

**Comment by Victor-Nyagudi** [comment] 2023-08-29 18:46
@sonialiap I've already received and accepted an offer from @Christinadobrzyn a few minutes ago for the reporting bonus.

**Comment by qispark** [comment] 2023-08-29 22:54
@sonialiap I was getting this error:
`Only invited users can find, view and apply to the job`

My upwork profile is here: https://www.upwork.com/freelancers/~012ec968f7113a1b63

**Comment by sonialiap** [comment] 2023-08-30 13:11
@Victor-Nyagudi the offer process in upwork is
1. we send offer
2. contributor accepts offer
3. we make the payment. The payment can be issued by anyone on the Expensify team, it doesn't have to be the same person who sent the offer

Christina did #1 and I finished off the #3. I did not send an extra offer, but let me know if you got paid twice :)

**Comment by Victor-Nyagudi** [comment] 2023-08-30 13:48
@sonialiap I only got one offer, but the payment for the milestone hasn't been released yet.

Am I missing something?

**Comment by qispark** [comment] 2023-08-30 14:18
Hey @sonialiap just wondering if it is possible to get paid via an Upwork agency account? I have sent you a message on Upwork with the agency profile link.

**Comment by Victor-Nyagudi** [comment] 2023-08-30 14:33
The payment has gone through now. Thank you.

Strangely, I didn't get the confirmation of the milestone being approved yesterday, but everything's sorted out now.

**Comment by qispark** [comment] 2023-08-31 13:40
Thanks @sonialiap, I have accepted and requested a milestone payment now.

**Comment by sonialiap** [comment] 2023-09-01 09:20
Payment sent ✔️

**Closed by sonialiap** 2023-09-01 09:20 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-21 09:41
$1,500 payment for @parasharrajat approved based on BZ summary.
