### ISSUE TITLE
[$1000] Web - Cancelled task gets undone if the other user was offline and done some actions inside the task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25603] opened 2023-08-21 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
step 1: go to [new.expensify.com](http://new.expensify.com/)
Step 2: login as user A
Step 3: open another tab login as User B
step 4: from User A click on the + FAB and choose assign task
step 5: give the task a title and description and click next
step 6: for share somewhere choose User B to share task with and click 'confirm task'
step 7: go to User B and open the  task
step 8: from User B  inspect the website (ctrl+shift+c)
Step 9: go to networks tab  and in the trolling dropdown choose offline (make sure ur offline)
step 10: from User B and send a text to User A from that task room ( which won’t be sent cause user B is offline)
step 11: go to User A and cancel the task
step 12: now from User B browser disable the trolling from the network (get back online)
Step 13: observe the text sent from step 10 gets delivered
step 13: observe User A task room getting uncanceled (if it takes a while refresh)

## Expected Result:
task room gets canceled

## Actual Result:
task room doesn’t get canceled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-13

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3ff6e97d-1ee2-411b-9517-a16f7f20baab

https://github.com/Expensify/App/assets/115492554/df33a064-faa9-48d4-a3a4-ca7694ccde7d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @lidiyakelay

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691600181624639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153abfad31f49c26e</li>
        <li>Upwork Job ID: 1695166251454062592</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26375797</li>
</ul></li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-08-21 22:17
https://expensify.slack.com/archives/C049HHMV9SM/p1692656263051839?thread_ts=1691600181.624639&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-08-25 20:08
Confirmed reproducible, moving forward.

**Comment by kubabutkiewicz** [comment] 2023-08-28 11:01
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by kevinksullivan** [comment] 2023-08-28 19:09
Sorry I was a bit quick to hire @kubabutkiewicz . Can you put up a proposal here first so @0xmiroslav can review?

**Comment by kubabutkiewicz** [comment] 2023-08-29 08:27
Hi @kevinksullivan, I am from Callstack and I think the process for agencies is a little bit different, firstly we are getting assigned to issue and then we are putting proposals.

**Comment by mountiny** [comment] 2023-08-29 09:03
When it comes to agency workers we can assign them even without proposal at first.

However @kubabutkiewicz you still need to first provide the proposal and work with @0xmiroslav to ensure the solution is viable and we can use it before starting a PR.

Thanks!

**Comment by kubabutkiewicz** [comment] 2023-08-29 09:04
Yes of course !

**Comment by kubabutkiewicz** [comment] 2023-08-29 12:06
Hi Guys,
It looks like a problem on the backend side for me look at the video below.

https://github.com/Expensify/App/assets/25230417/d8b4a0e8-992c-41aa-a02a-b40dd7f1f0c3

Its not happening only after coming back from offline mode but every time when we cancel a task.
After getting new data from API `statusNum` and `stateNum` are 0 but suppose to be 2.
Second option is that we are not sending correct data from frontend but I would need to check API documentation for that. Do we have something like that @kevinksullivan or @mountiny ? 

Let me know what to you think.

**Comment by lidiyakelay** [comment] 2023-08-30 08:56
@mountiny or @kevinksullivan   I have applied for the job on upwork.

**Comment by thienlnam** [comment] 2023-08-31 23:39
https://expensify.slack.com/archives/C049HHMV9SM/p1692812499109599

**Closed by thienlnam** 2023-08-31 23:39 UTC
Labels: External, Daily, Bug
