### ISSUE TITLE
[HOLD for payment 2023-12-20] IOU - Add receipt header is missing in Add receipt page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32831] opened 2023-12-11 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Tap FAB > Request money.
3. Enter amount > Next.
4. Select a member > Next.
5. Tap 3-dot menu > Add receipt.

## Expected Result:
"Add receipt" header will not disappear.

## Actual Result:
"Add receipt" header is missing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/89ae5b54-bd10-4489-8f72-8917947e517c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-12-11 22:25
@bernhardoj are you available to work on a PR?

**Comment by luacmartins** [comment] 2023-12-11 23:25
Put up a PR with the fix.

**Comment by jjcoffee** [comment] 2023-12-12 15:01
@luacmartins Would you mind assigning me here as I reviewed the PR?

**Comment by luacmartins** [comment] 2023-12-12 16:19
@stephanieelliott we just need to pay @jjcoffee for the review and @bernhardoj for the proposal (I wrote the PR since they were unavailable at the time)

**Comment by luacmartins** [comment] 2023-12-12 18:04
This issue is still reproducible in staging. Gonna take a look

**Comment by luacmartins** [comment] 2023-12-12 18:06
I'm not sure why this is happening. It's fixed on the simulator, but not on a physical device

**Comment by shubham1206agra** [comment] 2023-12-12 18:08
@luacmartins Can you create an adhoc build to test this?

**Comment by luacmartins** [comment] 2023-12-12 18:10
Nvm this is fixed in the latest 1.4.11-20 build. Maybe the CP hadn't made it to -16.

**Comment by jjcoffee** [comment] 2023-12-21 10:08
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1433852688
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Tap FAB -> Request money.
2. Enter any amount and proceed.
3. Select any member and proceed.
4. Tap 3-dot menu > Add receipt.
5. Verify that the "Add receipt" header shows.

Do we agree 👍 or 👎

**Comment by luacmartins** [comment] 2023-12-21 10:22
We already have steps covering this flow, so I think we're good!

**Comment by stephanieelliott** [comment] 2023-12-21 16:56
Summarizing payment on this issue: 

 - Contributor: $500, @bernhardoj I extended the offer on Upwork, can you please accept?
 - Contributor+: $500, @jjcoffee I extended the offer on Upwork, can you please accept?
 
 Upwork job is here: https://www.upwork.com/jobs/~017a077bb53d8ea02c

**Comment by jjcoffee** [comment] 2023-12-22 11:56
@stephanieelliott Accepted, thanks!

**Comment by stephanieelliott** [comment] 2023-12-22 14:17
All paid, thanks everyone!

**Closed by stephanieelliott** 2023-12-22 14:17 UTC
Labels: Engineering, Daily, Awaiting Payment
