### ISSUE TITLE
[HOLD for payment 2024-02-01] [HOLD for payment 2024-01-31] [$250] Chat-No unread marker when chat with the latest text is from you and marked as unread from LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31748] opened 2023-11-22 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Mark a chat where the latest message is not from you, as unread
3. Open the chat
4. Note that it shows the unread marker
5. Send a few messages to the chat
6. Return to LHN
7. Long press on the chat and mark it as unread
8. Open the chat

## Expected Result:
The unread marker will be displayed

## Actual Result:
The unread marker is not displayed. This only happens when the latest message comes from the current app user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8cc92344-0e78-4cfd-9024-50e4823be06a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2b3a63cdf2318c4</li>
        <li>Upwork Job ID: 1727427415139188736</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28032969</li>
<li>dukenv0307 | Contributor | 28032971</li>
</ul></li>
    </ul>
</details>

**Comment by akamefi202** [comment] 2023-11-22 23:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No unread marker when chat with the latest text is from you and marked as unread from LHN.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/14abfa118d473baeba163f15e6042180892f71cf/src/pages/home/report/ReportActionsList.js#L341-L343

Currently, `shouldDisplayNewMarker` function prevents showing unread marker if the sender of last message is the current app user.
As a result, we can't see unread marker if the current user sent the last message.

### What changes do you think we should make in order to solve the problem?
We might delete this code part to show unread marker although the last messgae is sent by the current user.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2023-11-29 05:55
cc: @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-11-29 10:44
Thanks for the mention. I'll take a look

**Comment by MonilBhavsar** [comment] 2023-11-29 11:01
This issue is only reproducible on Mobile devices

> I'm still confused about the expected result. I think we shouldn't allow the user to unmark their message.

We need to allow users to unmark their own messages. Many chatting apps including slack has this ability. Reason: in case user wants to catch up from that later

**Comment by mollfpr** [comment] 2023-11-29 19:20
Thanks @MonilBhavsar, for confirming it.

@akamefi202 @dukenv0307 Why is it working fine on the Web and Desktop?

I found a different result for the `messageManuallyMarkedUnread` value between Web and mWeb. On the Web, we have the value timestamp, but on the mWeb it's remains `0`.

https://github.com/Expensify/App/blob/089ddf472cc1fb125d3b1153ede647f2c8737b5d/src/pages/home/report/ReportActionsList.js#L341-L343

I think that might be why it's checking the marker it's not displayed.

**Comment by akamefi202** [comment] 2023-11-29 21:12
@mollfpr Because LHN and Report page is separated in mobile app.
So Report component dismounts & remounts when the user navigates to LHN and back to Report page.
And this resets `messageManuallyMarkedUnread` as 0.

https://github.com/Expensify/App/blob/0863b6a36a1c4dce755b55d1922a669d5b2bd7f8/src/pages/home/report/ReportActionsList.js#L219-L220

**Comment by MonilBhavsar** [comment] 2023-12-01 16:00
> Can you also confirm that once unmarking their own message, we should do the same as Slack does, which is to mark the "latest message that doesn't come from current user" as unread?
(Slack will not show the marker above current user's message)

Pretty sure this has changed recently with Slack. One was able to mark any message as unread in slack previously. I think we should keep that out of scope for now, and handle in new issue. Not a priority though.

For this issue, we can mark the last message as read like Web

**Comment by mollfpr** [comment] 2023-12-02 03:33
@akamefi202 Do you propose removing the check for the current user `accountID`?

https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/pages/home/report/ReportActionsList.js#L340-L343

**Comment by MonilBhavsar** [comment] 2023-12-04 12:10
Proposals in review...

**Comment by MonilBhavsar** [comment] 2023-12-06 09:57
That line you mentioned in the code is for - we don't want to display unread markers above sender's message, except unread message. In unread message, currently user can mark any message as unread, including their own messages.

> Also why don't we fix so that it aligns with that intention and also aligns with Slack? https://github.com/Expensify/App/issues/31748#issuecomment-1823817127 is quite straight forward.

It is currently out of scope of this issue and we would need a major change for that? How straightforward are the code changes? Do we need to iterate over report actions to find the last message from the recipient?

**Comment by MonilBhavsar** [comment] 2023-12-08 12:21
Okay, let's do it 👍

**Comment by MonilBhavsar** [comment] 2023-12-08 12:24
@mollfpr, @dukenv0307's proposal looks good to me. let me know what do you think of it

**Comment by mollfpr** [comment] 2023-12-11 10:49
@MonilBhavsar The proposal from @dukenv0307 looks good to me too.

🎀 👀 🎀 C+ reviewed!

**Comment by miljakljajic** [comment] 2023-12-18 13:26
@mollfpr have you had a chance to review this yet?

**Comment by mollfpr** [comment] 2023-12-18 15:27
@miljakljajic Yup, we still discussing the other case for the mark to show.

**Comment by miljakljajic** [comment] 2024-01-10 14:06
@mollfpr seems like the offer expired without being accepted - can you accept the new offer and let me know here? Then I can get it paid right away.

@dukenv0307 - paid!

**Comment by mollfpr** [comment] 2024-01-10 14:07
@miljakljajic Could you give the payment summary for the manual request in NewDot? Also, I'm completing the checklist now.

**Comment by mollfpr** [comment] 2024-01-10 14:10
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR here. We do some improvement on the marking the user own message.


> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Launch the New Expensify app
2. Mark a chat where the latest message is not from you as unread
3. Open the chat
4. Note that it shows the unread marker
5. Send a few messages to the chat
6. Return to LHN
7. Long press on the chat and mark it as unread
8. Open the chat
9. Verify that the unread indicator appears in the latest report action that doesn't come from the current user.

**Comment by twisterdotcom** [comment] 2024-01-10 22:03
Did the test case @miljakljajic.

**Comment by miljakljajic** [comment] 2024-01-11 13:42
@mollfpr , of course - payment summary below:

@mollfpr is owed 500 USD for their work as a C+ on this issue.

**Comment by JmillsExpensify** [comment] 2024-01-14 08:25
$500 payment approved for @mollfpr based on comment above.

**Comment by situchan** [comment] 2024-01-14 15:23
FYI: there was [regression](https://github.com/Expensify/App/issues/33881#issuecomment-1876664149) which was caught during regression period

**Comment by youssef-lr** [comment] 2024-01-15 04:23
@dukenv0307 please check the regression linked by @situchan. Thank you!

**Comment by Santhosh-Sellavel** [comment] 2024-01-25 18:47
Seems this issue is not fully fixed please this issue https://github.com/Expensify/App/issues/35122

**Comment by miljakljajic** [comment] 2024-02-02 09:31
@MonilBhavsar what's your thoughts on this one?

**Comment by miljakljajic** [comment] 2024-02-12 19:49
@MonilBhavsar can I get some feedback on @Santhosh-Sellavel 's comment above - is https://github.com/Expensify/App/issues/35122 a regression from this issue?

**Comment by MonilBhavsar** [comment] 2024-02-23 11:07
> Seems this issue is not fully fixed please this issue https://github.com/Expensify/App/issues/35122
@Santhosh-Sellavel this issue involves marking the rpeort as unread from LHN and other issue does not involve marking as unread flow?
@dukenv0307  @mollfpr any thoughts on this.
Also cc @situchan since you're looking at the other issue.

**Comment by MonilBhavsar** [comment] 2024-02-23 11:49
Yes exactly, that's what I thought.

**Closed** 2024-02-23 12:28 UTC
Labels: External, Weekly, Awaiting Payment, Bug
