### ISSUE TITLE
[Awaiting payment 9 Sept] [$250]  Workspace - #admin is pinned when creating WS offline and unpinned after going online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44855] opened 2024-07-04 16:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4697892&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):** applausetester+gm1021@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create Workspace
2. Navigate to LHN

## Expected Result:
#Admin room should be pinned

## Actual Result:
#Admin room is not pinned
When create new Workspace in offline mode Admin room is pinned, coming back online unpin Admin room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9e470d74-0ec8-4d54-ac25-232daf52eed8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f6d780296cf43d7</li>
        <li>Upwork Job ID: 1810520412296791199</li>
        <li>Last Price Increase: 2024-08-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment] 2024-07-04 16:30
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-04 16:31
We think that this bug might be related to #vip-vsp

**Comment by RachCHopkins** [comment] 2024-07-05 01:40
I can't reproduce this online or offline. Please retest.

**Comment by RachCHopkins** [comment] 2024-07-09 03:44
Ok, I think the issue that I just don't understand how it should work. Yes, looks external to me.

**Comment by mananjadhav** [comment] 2024-07-10 11:05
@RachCHopkins Can you confirm the expected behavior? Should the chat be pinned or not pinned?

**Comment by mananjadhav** [comment] 2024-07-16 20:17
> @RachCHopkins Can you confirm the expected behavior? Should the chat be pinned or not pinned?

@RachCHopkins quick bump.

**Comment by mananjadhav** [comment] 2024-08-03 18:42
> Is not very descriptive. The reproduction steps don't mention being offline, so I did both. Same result for both. But perhaps I'm looking at the wrong thing.
> 
> Edit: To be clear, the admins rooms are not pinned in any state. Should they be?


@RachCHopkins I got a little confused by this comment, can you please confirm if they should be pinned/not pinned?

**Comment by RachCHopkins** [comment] 2024-08-06 04:55
Sorry @mananjadhav the issue has you as the "owner" and I don't pay close attention when I'm not the owner. I don't know the answer your question, which is why I asked it. I will go ask my team.

**Comment by RachCHopkins** [comment] 2024-08-07 01:07
Still waiting for response in [Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1722920360691679)

**Comment by RachCHopkins** [comment] 2024-08-07 23:23
Okily dokily I finally have a definitive answer. We do not pin #admins rooms upon creation of workspaces, only only after there is a policy audit log or another admin is added to the workspace. 

So maybe @mananjadhav see if it does this weird behaviour when you create a workspace offline and also invite an additional admin offline and then go back online.

**Comment by mananjadhav** [comment] 2024-08-14 17:13
Thanks for confirming. I was OOO. But I'll check the expected behavior and proposals again.

**Comment by mananjadhav** [comment] 2024-08-16 19:29
@daledah's [proposal](https://github.com/Expensify/App/issues/44855#issuecomment-2216474482) seems good to me. 

🎀 👀 🎀

**Comment by mananjadhav** [comment] 2024-08-20 14:46
Will review the PR.

**Comment by mananjadhav** [comment] 2024-09-04 17:10
The PR was deployed to production 5 days ago and should be ready for payout by Sept 06.

**Comment by mananjadhav** [comment] 2024-09-08 20:43
@RachCHopkins this is ready for payout. I don't have an offending PR for this one. I also don't think we need a regression test for this one.

Can you please post the payout summary? and take care of the payments. I'll be raising my request on NewDot.

**Comment by RachCHopkins** [comment] 2024-09-09 04:56
Upwork job is closed and I can't pay anything there. Adding external label again to try and get some way to pay @daledah

**Comment by RachCHopkins** [comment] 2024-09-09 05:06
Created new [Upwork Job](https://www.upwork.com/ab/applicants/1833007766135273803/job-details) and sent you an offer @daledah !

**Comment by mananjadhav** [comment] 2024-09-09 05:07
Thanks for adding the offer. @RachCHopkins for me I'll need a payout summary which I can then use to raise a request on NewDot. Could you help with that?

**Comment by RachCHopkins** [comment] 2024-09-09 05:07
Payment Summary:

Contributor: @daledah to be paid $250 via Upwork
Contributor+: @mananjadhav paid $250 via NewDot Manual Request
Upwork job [here](https://www.upwork.com/ab/applicants/1833007766135273803/job-details)

**Comment by RachCHopkins** [comment] 2024-09-09 05:08
Great minds think alike @mananjadhav!

**Comment by mananjadhav** [comment] 2024-09-09 05:10
Haha. Thanks for the help 🙏

**Comment by garrettmknight** [comment] 2024-09-11 19:19
$250 approved for @mananjadhav

**Comment by mananjadhav** [comment] 2024-09-12 17:23
I think we can close this one out if the contributor is paid as well.

**Comment by RachCHopkins** [comment] 2024-09-16 01:59
They are now!

Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by RachCHopkins** 2024-09-16 01:59 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
