### ISSUE TITLE
[$1000] Chat - The background size of the special emoji :face_in_clouds: is larger than other emojis

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21968] opened 2023-06-30 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Open any chat
4. Send any message
5. Hover over the message and click the button to select an emoji to react to the message
6. Choose :face_in_clouds: emoji

## Expected Result:
The background of the emoji is the same for every emoji

## Actual Result:
 The background size of the special emoji :face_in_clouds: is larger than other emojis

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**

https://github.com/Expensify/App/assets/78819774/7a30b191-0f32-451c-94f7-fc3d512b7cf3

![Bug6112201_IMG_20230630_173121](https://github.com/Expensify/App/assets/78819774/a543d919-ff47-4a50-b213-0575203300b7)

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016223b92b4c611126</li>
        <li>Upwork Job ID: 1678477195466743808</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-30 20:43
I cannot reproduce this on my end. This emoji is working for me as expected on android native. 


https://github.com/Expensify/App/assets/54866469/b5e3a629-b76a-499a-87a3-4a55ddc1659f

**Comment by joekaufmanexpensify** [comment] 2023-06-30 20:43
@lanitochka17 I'm going to close this for now since I cannot reproduce. Could you please try again and let me know if you still can? If so, could you please share your specific device type so I can try on that? Thanks!

**Comment by lanitochka17** [comment] 2023-06-30 21:14
@joekaufmanexpensify 
Reproduced on  3 devices:
Samsung Galaxy A30/Android11
Realme6/Android11
Samsung Galaxy A50/Android11

![Screenshot_2023-07-01-00-08-13-80_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/78819774/e90c458e-9b23-4aaa-b527-644e773ed622)

**Comment by joekaufmanexpensify** [comment] 2023-07-07 21:21
Sounds good. Thanks for confirming! I will try to reproduce on those 3 devices or ones similar.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 13:59
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-07-10 18:50
Okay, when I test on a RealMe8, I am able to reproduce: 

<img width="282" alt="image" src="https://github.com/Expensify/App/assets/54866469/c9b6b4a5-4077-4e08-80d3-7cb601cbeada">

**Comment by joekaufmanexpensify** [comment] 2023-07-11 18:46
Awaiting proposals.

**Comment by joekaufmanexpensify** [comment] 2023-07-12 18:51
Same

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:12
[Bumped for proposals in Slack. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1689271963360509)

**Comment by ShogunFire** [comment] 2023-07-13 19:03
Do modern emojis are supported for version of android <= 11 ? 
https://developer.android.com/develop/ui/views/text-and-emoji/emoji2#appcompat

**Comment by ShogunFire** [comment] 2023-07-13 19:05
It seems to be a problem with calculating the length of the emoji since 😶‍🌫️ has a length of 6 but when combined it is probably shorter

**Comment by joekaufmanexpensify** [comment] 2023-07-14 18:51
@ShogunFire Ah, interesting. So you think this could be related to an older version of Android?

**Comment by ShogunFire** [comment] 2023-07-14 19:42
Honestly I don't know but if I understand correctly if Android is 11 or below, they say you must use AppCompat, emoji2 or EmojiCompat, I don't know if we use one or if react native use one

**Comment by joekaufmanexpensify** [comment] 2023-07-17 12:40
@thesahindia Curious for your thoughts on this as well. I _think_ the above comment means we may not be able to easily fix this as it specifically relates to older Android devices?

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:16
Pending input from @thesahindia on the above question

**Comment by joekaufmanexpensify** [comment] 2023-07-19 13:05
Sure, I'll check now!

**Comment by joekaufmanexpensify** [comment] 2023-07-19 13:20
Yep, I'm seeing this on android 10. I also could not reproduce on newer devices. Going to close this per @thesahindia's above comment!

**Closed by joekaufmanexpensify** 2023-07-19 13:20 UTC
Labels: External, Daily, Help Wanted, Bug
