### ISSUE TITLE
[$500] Web - back tooltip is stuck on coming back from plaid connect bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27297] opened 2023-09-12 21:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->wallet
3. Click on Add payment method
4. Select Bank account
5. While loading, hover on back button of 'Add bank account' in header
6. Keep the cursor position same until plaid is loaded
7. Close the plaid popup and observe that app displays 'back' tooltip besides wallet even though cursor is not on the button

## Expected Result:
App should dismiss tooltip as soon as page is changed or cursor position is changed

## Actual Result:
App does not dismiss back tooltip even after plaid is opened and closed on wallet page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/400fc0c8-4ad5-4034-90e0-47f948ca3ea4

https://github.com/Expensify/App/assets/93399543/ba2e997c-8857-4ad7-854e-21b324f4de58

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694350731301379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb2a85fd90fcec8b</li>
        <li>Upwork Job ID: 1701710112708165632</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-09-12 23:11
Added second, dropping off.

**Comment by iamuddeshya** [comment] 2023-09-13 00:19
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Tooltip is not dismissed if it was in an opened state and the user navigated to external site and came back to the app. 

## What is the root cause of that problem?
The `onMouseEnter` is called as soon as we come back to the original page. This hence, calls the `onHoverIn` function that is a prop passed in the Hoverable component from ToolTip component. This finally triggers the `showToolTip` function, which makes the ToolTip appear back again.
https://github.com/Expensify/App/blob/0805f728f962d02eb254de457328f5914d31e9c6/src/components/Hoverable/index.js#L115
<img width="775" alt="image" src="https://github.com/Expensify/App/assets/19757182/862aadd2-2d1b-4500-a50c-692fd811d68c">

https://github.com/Expensify/App/blob/0805f728f962d02eb254de457328f5914d31e9c6/src/components/Tooltip/index.js#L155
<img width="891" alt="image" src="https://github.com/Expensify/App/assets/19757182/3d7174b6-fa3d-4cdd-9ff0-c57b6f66bce4">


## What changes do you think we should make in order to solve the problem?
We can either use a Flag Based Approach or an Event Based Approach to overcome this problem. Use a flag like `isScreenFocused` to determine if the tooltip should be shown.

or we can also use an Event Based Approach by adding a conditional statement in our showToolTip function to check whether the page is focused or not.

## What alternative solutions did you explore? (Optional)
I also compared both the click events that were being triggered and noticed a slight difference in both. One click event is triggered on SVG while the other is triggered on Div while coming back to the app from Plaid. The 2nd event can also be the cause of triggering the `onMouseEnter`.

**Comment by iamuddeshya** [comment] 2023-09-13 00:22
Contributor details
Your Expensify account email: ua@hyathi.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011b2c513d4b7b3536

**Comment by anyongjitiger** [comment] 2023-09-14 05:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

if tooltip was in an opened state and the user navigated to external site and came back, tooltip will show again 


### What is the root cause of that problem?

When the "Add bank account" button is clicked, it opens a Plaid page in an iframe. When the mouse moves within the iframe, the parent page does not receive any mouse events. Once the user closes the iframe and stops moving the mouse, the onMouseEnter function triggers automatically and sets setIsHovered to true, regardless of any other conditions.

https://github.com/Expensify/App/blob/e426b391e83eabe0c4fbf0cc5cbc4cb5fc19b32c/src/components/Hoverable/index.js#L115-L117

### What changes do you think we should make in order to solve the problem?

We can add an event listener to identify if the mouse has entered the iframe:

```
iframe.addEventListener('mouseenter', function () {
           this.setIsMouseEnterIframe(true);
     });
```

Add if block in the onMouseEnter that checks for the isMouseEnterIframe state:

```
onMouseEnter: (el) => {
                if (this.state.isMouseEnterIframe) {
                    return;
                }
                this.setIsHovered(true);
```
### What alternative solutions did you explore? (Optional)

replaced  
this.setIsHovered(true); 
To
this.setIsHovered(el.target === el.currentTarget)
But this will cause some other tooltips not to show up, such as FAB.

**Comment by robertKozik** [comment] 2023-09-14 10:38
Hi all!
@iamuddeshya - your solution blocks the tooltip on FAB (Floating Action Button)

@anyongjitiger - Can you provide me more details on how you will pass the iframe reference/state to `Hoverable` component? Coupling the `Hoverable` with an specific iframe (inside `WalletStatementModal.js`) feels not right as it should remain as generic component

**Comment by iamuddeshya** [comment] 2023-09-14 12:53
> Hi all! @iamuddeshya - your solution blocks the tooltip on FAB (Floating Action Button)
> 
> @anyongjitiger - Can you provide me more details on how you will pass the iframe reference/state to `Hoverable` component? Coupling the `Hoverable` with an specific iframe (inside `WalletStatementModal.js`) feels not right as it should remain as generic component

Hello, I have a solution. The solution can be more performant when I actually work on it, but here is what we can do. 

1. Adding a mutation observer in the Hoverable component that checks if there has been an iFrame added. If yes, then update the `isIframeAdded` as true.
<img width="697" alt="image" src="https://github.com/Expensify/App/assets/19757182/fd3164d0-a230-44f4-a311-d0be8b6641c9">

2. In the `onMouseEnter` function check if `isIframeAdded === true`, if yes then just return out from the function and update the `isIframeAdded` to be false. Otherwise render the toolitp. 
<img width="614" alt="image" src="https://github.com/Expensify/App/assets/19757182/cc4ef749-63e1-4760-8dc5-00fe86441fc1">

3. Result Video 

https://github.com/Expensify/App/assets/19757182/09e5276c-0962-4818-b9b4-6c0bf7d12654

**Comment by iamuddeshya** [comment] 2023-09-14 16:39
# Proposal [ Updated ] 

## Please re-state the problem that we are trying to solve in this issue.
Tooltip is not dismissed if it was in an opened state and the user navigated to external site and came back to the app. 

## What is the root cause of that problem?
If you look at the `onMouseEnter` function it is making the `setIsHovered` to always true no matter what. This `onMouseEnter` functions triggers automatically as soon as the user come's back to the screen. This function further calls the `onHoverIn` function because the `setIsHovered` becomes true and this results the Hoverable component to trigger the `showToolTip` function, which makes the ToolTip appear back again.
https://github.com/Expensify/App/blob/0805f728f962d02eb254de457328f5914d31e9c6/src/components/Hoverable/index.js#L116
https://github.com/Expensify/App/blob/0805f728f962d02eb254de457328f5914d31e9c6/src/components/Tooltip/index.js#L155


## What changes do you think we should make in order to solve the problem?
I have posted the solution to let the hover work on "Floating Action Buttons" [https://github.com/Expensify/App/issues/27297#issuecomment-1719396562](url)

1. Adding a mutation observer in the Hoverable component's `ComponentDidUpdate` that checks if there has been an iFrame added. If yes, then update the `isIframeAdded` variable to true.
<img width="697" alt="image" src="https://github.com/Expensify/App/assets/19757182/fd3164d0-a230-44f4-a311-d0be8b6641c9">

2. Then, in the same file in the `onMouseEnter` function check if `isIframeAdded === true`, if yes then just return out from the function and update the `isIframeAdded` to be false. This will avoid the setting the state of `setIsHovered` to true. Otherwise, if `isIframeAdded` is false then we render the toolitp as before.

<img width="614" alt="image" src="https://github.com/Expensify/App/assets/19757182/cc4ef749-63e1-4760-8dc5-00fe86441fc1">

3. Result Video 

https://github.com/Expensify/App/assets/19757182/09e5276c-0962-4818-b9b4-6c0bf7d12654 

## What alternative solutions did you explore? (Optional)
No, the above solved the problem.

**Comment by anyongjitiger** [comment] 2023-09-15 00:36
> Hi all! @iamuddeshya - your solution blocks the tooltip on FAB (Floating Action Button)
> 
> @anyongjitiger - Can you provide me more details on how you will pass the iframe reference/state to `Hoverable` component? Coupling the `Hoverable` with an specific iframe (inside `WalletStatementModal.js`) feels not right as it should remain as generic component

Hello @robertKozik , here are the details of the code:

Add a mutation observer in componentDidMount that checks if there is an iFrame.
```
    componentDidMount() {
        document.addEventListener('visibilitychange', this.handleVisibilityChange);
        const self = this;
        this.observer = new MutationObserver(function (mutations) {
            mutations.forEach(function (mutation) {
                mutation.addedNodes.forEach(function (node) {
                    if (node.tagName === 'IFRAME') {
                        node.addEventListener('mouseenter', function () {
                            self.setIsMouseEnterIframe(true);
                        });
                    }
                });
            });
        });
        this.observer.observe(document.body, {childList: true, subtree: false});
    }
```

Disconnect the mutation observer in componentWillUnmount:

```
componentWillUnmount() {
        document.removeEventListener('visibilitychange', this.handleVisibilityChange);
        if (this.observer) {
            this.observer.disconnect();
        }
    }
```
Check if state.isMouseEnterIframe is true in onMouseEnter:
```
onMouseEnter: (el) => {
                if (state.isMouseEnterIframe) {
                    this.setIsMouseEnterIframe(false);
                    return;
                }
                this.setIsHovered(true);
```

**Comment by robertKozik** [comment] 2023-09-20 16:04
Hmmm, I'm considering the performance implications of your proposals. Since we'd be creating a new MutationObserver for every hoverable component, and as far as I recall, all messages inside the chat are hoverable. This could potentially lead to a degradation in performance quite quickly. What are your thoughts on this?

Additionally, I'd like to discuss with you the fact that both of your solutions are almost identical, yet they differ from your initial proposals. If this solution is accepted, the contributor who was first to propose the MutationObserver will be chosen.

**Comment by iamuddeshya** [comment] 2023-09-20 19:05
> Hmmm, I'm considering the performance implications of your proposals. Since we'd be creating a new MutationObserver for every hoverable component, and as far as I recall, all messages inside the chat are hoverable. This could potentially lead to a degradation in performance quite quickly. What are your thoughts on this?
> 
> Additionally, I'd like to discuss with you the fact that both of your solutions are almost identical, yet they differ from your initial proposals. If this solution is accepted, the contributor who was first to propose the MutationObserver will be chosen.

A quick solution will be 
1. We can relocate the Mutation Observer to a new context provider, ideally at the root level, such as in `App.js`.

2. We can then include this new context provider within `ComposeProviders`, which already contains all the existing context providers in our application.

3. By positioning the Mutation Observer at the top level, it will only run once. This avoids performance issues while still notifying the `Hoverable Component` of any iFrame additions. To get this information in the `Hoverable Component`, we will simply utilize React's `useContext`.

4. The other benefit of this approach that we can detect iFrames universally across our app. Any component can now be made aware of iFrame additions just by leveraging `useContext`.

If we talk specifically about mentioning the "MutationObserver" it was me [ @iamuddeshya ]. Although @anyongjitiger mentioned about adding eventListeners to iFrames. 

If this sounds good to you @robertKozik , let me know and I will update my proposal.

Thanks!

**Comment by anyongjitiger** [comment] 2023-09-21 02:50
@robertKozik I believe that the root cause of this problem is that the mouse moved over an iframe. The solution is to monitor whether the mouse moves over the iframe, and the MutationObserver is just a means for the iframe to be detected. Please reconsider my proposal. Thanks!  ^-^

**Comment by JmillsExpensify** [comment] 2023-10-17 20:40
@robertKozik Thoughts on the latest response? Should we keep this open for proposals and external?

**Comment by robertKozik** [comment] 2023-10-18 14:18
@JmillsExpensify Keep open, I totally forgot about this - will take care of it immediately

**Comment by robertKozik** [comment] 2023-10-18 14:25
I'm considering whether we can potentially close this issue. It doesn't seem to impact user flows and requires a very specific setup (user needs to hover on the back button, open Plaid, close Plaid, and not move the cursor afterwards). The proposal from @iamuddeshya is ready, but personally, I believe it might be like using a cannon to deal with a small issue. What are your thoughts, @JmillsExpensify?

**Comment by JmillsExpensify** [comment] 2023-10-24 22:32
I agree with you. I actually think we should make a bolder move and remove most tooltips throughout the app. Going to close based on your comments above.

**Closed by JmillsExpensify** 2023-10-24 22:32 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
