### ISSUE TITLE
[Awaiting Payment 23rd April] [$250] Account Settings - When legal name change there is not reflect in other device

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39591] opened 2024-04-04 10:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** alexzamora1487+01042024@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. On deviceA go to settings > profile > personal details > legal first name
2. Enter a name that's 100+ characters long i.e `gfkfkfkfkfkfkkfkfkfkfkfkfkfkfkfkffkkfkgkgkgkkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkkgkgkgkgkgkkggkk`
3. Observe the error that the 100 character field length is exceeded
4. Now enter a name that's 10 characters long i.e `gkgkgkgkgk`
5. Switch to deviceB, observe that the legal first name updates
7. On deviceA, enter a name that's 41 characters long i.e `gfkfkfkfkfkfkkfkfkfkfkfkfkfkfkfkffkkfkfka`
8. Switch to device B, observe that the legal first name doesn't update
9. On deviceA, enter a name that's 40 characters long. i.e `gfkfkfkfkfkfkkfkfkfkfkfkfkfkfkfkffkkfkfk`
10. On deviceB, observe that the legal first name does update. 

## Expected Result:
The frontend and backend character limit for the legal name field should be the same. Let's update the character limit on the front-end to `40` to match the backend. 

## Actual Result:
The frontend character field limit is `100`, but the backend character limit is `40` characters. As a result, there's no error being displayed on the front-end when someone enters a value of 40+ characters and it doesn't get saved either. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a0e95ad1-fe85-418f-b2d9-fb4a12674d13

![Bug6434552_1711989970476!bug_-_other_devices1](https://github.com/Expensify/App/assets/115492554/c7a4305a-e255-44df-895e-00235159826c)

![Bug6434552_1711989970482!bug_-_other_devices](https://github.com/Expensify/App/assets/115492554/6433cd15-8035-4889-9bc4-abd3ff0c0a43)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2024-04-04 13:51
@izarutskaya the video uploaded just shows a tester opening the legal name field and circling it with a cursor then closing it again. Then there's two pictures showing a truncated long legal name entered which seems correct. It took me a while to piece this together. I've updated it quite a bit, but can we be vigilant about making it clear what's going on here. Thanks!


I can reproduce it. There's a mismatch between the 100 character limit for the field on the front-end and the limit on the backend -- which appears to be `40`. So we are saving it on the front-end, but not the backend.

https://github.com/Expensify/App/assets/16232057/d52920b6-4565-4e55-877d-6ab917a23e3f

I think the right course of action here is to update the character limit to `40` for this field to match the backend. CC: @joekaufmanexpensify

**Comment by ariefgp** [comment] 2024-04-04 14:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Legal name max length mismatch on FE and BE

### What is the root cause of that problem?
Current limit is being set to 100
https://github.com/Expensify/App/blob/0b2f55fefa8519b86f58730a85e851409f631524/src/CONST.ts#L1786C1-L1786C32

### What changes do you think we should make in order to solve the problem?
1. Use the existing Legal Names Max Length Limit Const:
https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/CONST.ts#L133C1-L135C7

2. Update the max length validation for legal first name and legal last name.
https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L52C1-L57C14

to 

```
else if (values.legalFirstName.length > CONST.LEGAL_NAME.MAX_LENGTH) {
                ErrorUtils.addErrorMessage(errors, 'legalFirstName', [
                    'common.error.characterLimitExceedCounter',
                    {length: values.legalFirstName.length, limit: CONST.LEGAL_NAME.MAX_LENGTH},
                ]);
            }
```

https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L68C1-L70C14

to

else if (values.legalLastName.length > CONST.LEGAL_NAME.MAX_LENGTH) {
                ErrorUtils.addErrorMessage(errors, 'legalLastName', ['common.error.characterLimitExceedCounter', {length: values.legalLastName.length, limit: CONST.LEGAL_NAME.MAX_LENGTH}]);
            }

3. Remove the unnecessary Const
https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/CONST.ts#L1780C1-L1780C38

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ariefgp** [comment] 2024-04-04 14:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Legal name max length mismatch on FE and BE

### What is the root cause of that problem?
Current limit is being set to 100
https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/CONST.ts#L1786

### What changes do you think we should make in order to solve the problem?
1. Use the existing Legal Names Max Length Limit Const:
https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/CONST.ts#L133-L135

2. Update the max length validation for legal first name and legal last name.
https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L52-L57

to 

```
else if (values.legalFirstName.length > CONST.LEGAL_NAME.MAX_LENGTH) {
                ErrorUtils.addErrorMessage(errors, 'legalFirstName', [
                    'common.error.characterLimitExceedCounter',
                    {length: values.legalFirstName.length, limit: CONST.LEGAL_NAME.MAX_LENGTH},
                ]);
            }
```

https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L68-L70

to

else if (values.legalLastName.length > CONST.LEGAL_NAME.MAX_LENGTH) {
                ErrorUtils.addErrorMessage(errors, 'legalLastName', ['common.error.characterLimitExceedCounter', {length: values.legalLastName.length, limit: CONST.LEGAL_NAME.MAX_LENGTH}]);
            }

3. Remove the unnecessary Const
https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/CONST.ts#L1780

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ariefgp** [comment] 2024-04-04 15:02
Contributor details
Your Expensify account email: [arief.gusti@gmail.com](mailto:arief.gusti@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01135779bc0035c9ae

**Comment by ariefgp** [comment] 2024-04-04 15:06
Contributor details
Your Expensify account email: arief.gusti@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01135779bc0035c9ae

**Comment by nkdengineer** [comment] 2024-04-04 15:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The frontend character field limit is 100, but the backend character limit is 40 characters. As a result, there's no error being displayed on the front-end when someone enters a value of 40+ characters and it doesn't get saved either.

### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L52-L55) and [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L68-L69), we're not using the correct max length character limits.
- In [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/ReimbursementAccount/PersonalInfo/substeps/FullName.tsx#L33-L37) where we validate legal names in bank account flow, we don't even have validations for the max length

### What changes do you think we should make in order to solve the problem?

- In [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L52-L55) and [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L68-L69), use `CONST.LEGAL_NAME.MAX_LENGTH` instead of `CONST.TITLE_CHARACTER_LIMIT`
- In [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/ReimbursementAccount/PersonalInfo/substeps/FullName.tsx#L33-L37), add validations for max length (using `CONST.TITLE_CHARACTER_LIMIT`, or if we want a completely different max length for bank account legal names, then define that new limit as a const and use here)

There're a few other places that are legal names-related but missing max length validation, like [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/EnablePayments/AdditionalDetailsStep.tsx#L169), we can consider fixing them too.

### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment] 2024-04-04 18:28
>I think the right course of action here is to update the character limit to 40 for this field to match the backend. CC: @joekaufmanexpensify

@trjExpensify is there a reason we wouldn't update the BE to match the FE limit of 100? There's no hard and fast rule here, but 100 for a field like this is [the standard](https://stackoverflowteams.com/c/expensify/questions/17034) we had landed on. So unless there's some specific benefit to 40, I feel like it could make sense to standardize on 100 personally.

**Comment by nkdengineer** [comment] 2024-04-05 01:54
@parasharrajat Could you give some feedback on [my proposal](https://github.com/Expensify/App/issues/39591#issuecomment-2037476493)? I think only mine fixes the issue fully in the app.

**Comment by chiragsalian** [comment] 2024-04-05 18:01
> Can you please reconsider the assignment, thanks

I'll defer to @parasharrajat since he has the most context here.

**Comment by trjExpensify** [comment] 2024-04-08 14:50
>@trjExpensify is there a reason we wouldn't update the BE to match the FE limit of 100? There's no hard and fast rule here, but 100 for a field like this is [the standard](https://stackoverflowteams.com/c/expensify/questions/17034) we had landed on. So unless there's some specific benefit to 40, I feel like it could make sense to standardize on 100 personally.

@joekaufmanexpensify we could do that, but I was assuming we had a `40` character limit on the backend for a reason. Perhaps @chiragsalian can help us find that and follow the trail to see if there was a documented reason for it?

**Comment by joekaufmanexpensify** [comment] 2024-04-08 15:00
Sounds good! When I'd investigated a lot of the field length limits previously, we had just picked a number we thought made sense for a lot of them. But def curious to here if there was a specific reason for the 40 for this one. If there was, totally fine with me to stick with that too.

**Comment by trjExpensify** [comment] 2024-04-09 20:38
I can find the commit in Web-E where we updated the [firstName](https://github.com/Expensify/Web-Expensify/commit/a5c3fc9a811c4279ef82466189d2a008c888898d) field to `100` characters, but I can't find the equivalent for the `legalFirstName`. CC: @luacmartins as that was your commit, maybe you know? 

[TL;DR](https://github.com/Expensify/App/issues/39591#issuecomment-2037280967) - There's a mismatch between the 100 character limit for the field on the front-end and the limit on the backend -- which appears to be 40. So we are saving it on the frontend, but not the backend (and not showing an error between 41-99 characters long. We're trying to figure out if we can follow the git blame for some reason as to why `40` is being set as the maxLimit of legalFirstName on the backend, or whether we should update it to `100` to match the front-end.

**Comment by luacmartins** [comment] 2024-04-09 21:17
My PR says `Increases display name max length to 100 chars for consistency with legal name.` So legal name must have the same limit?

**Comment by trjExpensify** [comment] 2024-04-09 21:23
Haha yeah, on the back-end that doesn't seem to be the case. Though I can't corroborate that by finding the maxLimit for legalName. 

The reason I think it's 40 and backend is because when I was testing (steps created below) in NewDot across two devices, 40 or 41 characters is the diff on whether it updates on the second device or not (suggesting it isn't updated on the backend, right?). 

> 1. On deviceA go to settings > profile > personal details > legal first name
> 2. Enter a name that's 100+ characters long i.e `gfkfkfkfkfkfkkfkfkfkfkfkfkfkfkfkffkkfkgkgkgkkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkkgkgkgkgkgkkggkk`
> 3. Observe the error that the 100 character field length is exceeded
> 4. Now enter a name that's 10 characters long i.e `gkgkgkgkgk`
> 5. Switch to deviceB, observe that the legal first name updates
> 6. On deviceA, enter a name that's 41 characters long i.e `gfkfkfkfkfkfkkfkfkfkfkfkfkfkfkfkffkkfkfka`
> 7. Switch to device B, observe that the legal first name doesn't update
> 8. On deviceA, enter a name that's 40 characters long. i.e `gfkfkfkfkfkfkkfkfkfkfkfkfkfkfkfkffkkfkfk`
> 9. On deviceB, observe that the legal first name does update.

**Comment by chiragsalian** [comment] 2024-04-09 21:56
Sorry for the delay, alright looks like there are two things here. 
1. Front end wants to set legalLastName limit to 100, And
2. Back end currently sets legalLastName limit to 40.

Alright i think you guys found the code for front end. Let me check **where** the code is in the backend.
It looks like we intentionally set the limit to 40 in the PHP code [here](https://github.com/Expensify/Web-Expensify/blob/06c4478f283bcefd55842876405ef5b29cc89db5/lib/PersonalDetailsAPI.php#L666-L669), code,
```
$invalidParams = array_filter(
    ['legalFirstName' => $legalFirstName, 'legalLastName' => $legalLastName],
    fn ($value) => mb_strlen($value) > self::MAX_LEGAL_NAME_LENGTH
);
```
And MAX_LEGAL_NAME_LENGTH is set to 40. Looks like this constant MAX_LEGAL_NAME_LENGTH is used just once i.e., in this spot. 
I don't see anywhere else in PHP or auth where we set the character limit for legalLastName. So if we update the constant MAX_LEGAL_NAME_LENGTH we should be good.

Next to find out **why** we chose 40 in backend, looking,
Apparently it used to be a length of 150 but we changed it to 40 [here](https://github.com/Expensify/Web-Expensify/pull/37289/files). The reasoning in the [PR](https://github.com/Expensify/Web-Expensify/pull/37289) says,
> This PR updates the length allowed for us to set a legal first name in the app. It was at 150 characters, but as you can see in the linked issue, Marqeta requires that the legal first name be between 0 and 40 characters.

So yeah we should not update the front end to 100 until we confirm with marqeta that they support 40+ characters in legal last name.

**Comment by chiragsalian** [comment] 2024-04-09 22:01
I've asked marqeta [here](https://expensify.slack.com/archives/CKR3B6ZFG/p1712699932396859). For now front end should set the same limit as the backend because if marqeta server processes this legal last name as before then if we give it a legal last name over 40 characters we'll get the error,
```
'500 Marqeta error (httpResponseCode: 400, errorCode: 400001, errorMessage: Invalid input(s): last_name size must be between 0 and 40,first_name size must be between 0 and 40)'
```
We can wait for marqeta to respond if things have changed but instead of waiting for them i feel like we should proceed with only allowing character limit to be 40 for now.

**Comment by chiragsalian** [comment] 2024-04-09 23:30
I was able to confirm in the marqeta docs that the last name character limit is 40 as well - [docs](https://www.marqeta.com/docs/core-api/users). 
![image](https://github.com/Expensify/App/assets/14356145/3422f5b4-95c0-4d53-b847-732cfd12e588)

So yeah front end should be updated to match this.

**Comment by nkdengineer** [comment] 2024-04-10 06:52
@parasharrajat Do you have any feedback for [my proposal](https://github.com/Expensify/App/issues/39591#issuecomment-2037476493)? 

I believe it's the only one to fix the issue fully in the app.

cc @chiragsalian

**Comment by chiragsalian** [comment] 2024-04-10 17:43
@GandalfGwaihir, your proposal LGTM. Feel free to create a PR.

@nkdengineer,  
> In [here](https://github.com/Expensify/App/blob/ce003b2ac3d0f5c407c6da38ec673011032e8395/src/pages/ReimbursementAccount/PersonalInfo/substeps/FullName.tsx#L33-L37), add validations for max length (using CONST.TITLE_CHARACTER_LIMIT, or if we want a completely different max length for bank account legal names, then define that new limit as a const and use here)

Nice attempt but we shouldn't be changing the limit of bank account first/last name. The only current issue is with details which is associated with an ecard since marqeta has a limit. Bank accounts and debit cards can have a much higher character limit.

> mentions a few more places that might also have the same issue. I am not currently sure if they are valid instances of the current problem

Yeah I'm pretty sure we don't need to update this elsewhere since this problem only exists in the reported flow for now. The legal last name in this flow will be used for expensify cards which is why we have a limit.

**Comment by nkdengineer** [comment] 2024-04-11 09:57
> Nice attempt but we shouldn't be changing the limit of bank account first/last name.

@chiragsalian The issue here is that we don't have any length limit at all on the bank account first/last name. So now the user can enter a name exceeding the max length limit, go all the way to the last submission step, then the back-end will throw an error there.

Do you think that behavior is fine or we should add client-side length validation for that field (like the rest of the app)?

**Comment by nkdengineer** [comment] 2024-04-11 09:57
> Nice attempt but we shouldn't be changing the limit of bank account first/last name.

@chiragsalian The issue here is that we don't have any length limit at all on the bank account first/last name. So now the user can enter a name exceeding the max length limit, go all the way to the last submission step, then the back-end will throw an error there.

Do you think that behavior is fine or we should add client-side length validation for that field (like the rest of the app)?

**Comment by chiragsalian** [comment] 2024-04-11 18:07
> user can enter a name exceeding the max length limit, go all the way to the last submission step, then the back-end will throw an error there.

If the backend does throw an error for that flow i think we should capture that as a separate issue. Because I'm pretty sure in the backend we don't have the 40 character limit for bank account names. So if an error is thrown we should investigate and find the cause of it.

**Comment by trjExpensify** [comment] 2024-04-24 23:50
Payment summary as follows: 

- $250 to @GandalfGwaihir for the bug fix - offer sent
- $250 to @parasharrajat for the C+ review - request through ND

**Comment by trjExpensify** [comment] 2024-04-24 23:53
@GandalfGwaihir paid, closing!

**Closed by trjExpensify** 2024-04-24 23:53 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by trjExpensify** [comment] 2024-05-20 13:35
Ah yes, the change was announced on the 4th April (when this issue was created), but went into effect on April 5th.

Feel free to request an extra $250 on ND. @GandalfGwaihir, I've sent you an offer for $250 as well.

**Comment by trjExpensify** [comment] 2024-05-21 10:08
Done and paid @GandalfGwaihir.

**Comment by JmillsExpensify** [comment] 2024-06-17 15:51
$500 approved for @parasharrajat
