### ISSUE TITLE
[HOLD for payment 2023-10-25] [$1000] Chat - Emoji suggestion list does not disappear when typing :+1: in the composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20998] opened 2023-06-19 00:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to any conversation
3. Type :+1: in the composer

## Expected Result:
When the emoji is rendered, the emoji suggestion list will disappear

## Actual Result:
When the emoji is rendered, the emoji suggestion list does not disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a92a37be-3fe5-43db-89df-7d5191b6f978

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c88e94973fd21352</li>
        <li>Upwork Job ID: 1671501364638490624</li>
        <li>Last Price Increase: 2023-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27373764</li>
<li>ShogunFire | Contributor | 27373765</li>
</ul></li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2023-06-21 12:53
The external label has been added.

**Comment by ShogunFire** [comment] 2023-06-23 17:14
Just to add to @allroundexperts proposal, the reason onSelectionChange is not called on Android is because onSelectionChange is called after OnChangeText on Android whereas on others platforms it is called before. And the selection doesn't change because the length of ":+1" is 3 and the length of "👍 " is also 3.

**Comment by flaviadefaria** [comment] 2023-06-23 20:17
@aimane-chnaif what are your thoughts here?

**Comment by flaviadefaria** [comment] 2023-06-26 13:53
Friendly bump @aimane-chnaif

**Comment by flaviadefaria** [comment] 2023-06-28 16:18
@aimane-chnaif just checking if you need any help?

**Comment by flaviadefaria** [comment] 2023-06-30 22:14
Cool I put this on hold and added it to the tracking issue so will now switch it monthly to wait until we can revisit this.

**Comment by flaviadefaria** [comment] 2023-06-30 22:33
Was meant to update a different issue and updated this one by mistake. We're still waiting for @aimane-chnaif here.

**Comment by flaviadefaria** [comment] 2023-07-05 21:28
@allroundexperts are you able to answer the above question or update your proposal?

**Comment by flaviadefaria** [comment] 2023-07-13 16:02
@aimane-chnaif do you have an update here? How can we move this forward?

**Comment by flaviadefaria** [comment] 2023-07-17 09:31
@aimane-chnaif what are your thoughts on @ShogunFire's proposal?

**Comment by ShogunFire** [comment] 2023-07-17 09:52
> But on some platforms onSelectionChanged is called after onChangeText.
Doesn't that answer this question ?

On native the selection (start end position) is changed before calling onChangeText so it goes to 4 before changing the text to 3 again

**Comment by ShogunFire** [comment] 2023-07-17 10:06
Because on web onChangeText is called before changing the selection and we change the text to a length of 3 before the selection is ever changed to 4, I think that's just how it works, you think our code is modifying this behaviour ?

I did find some issues on react native regarding similar  behaviours but they are closed:
https://github.com/facebook/react-native/issues/28865

https://github.com/microsoft/react-native-windows/issues/7740

**Comment by ShogunFire** [comment] 2023-07-17 10:37
Actually there is a difference between web and native in our code here:
https://github.com/Expensify/App/blob/25c8ae5212f433ea7679ba4bd040c79f151a282a/src/components/Composer/index.js#L237-L265

On web we calculate the position of the caret whereas we don't on native but I am not sure this is caused by this. To be honest on web I don't reproduce the issue, I only reproduce on mweb

**Comment by ShogunFire** [comment] 2023-07-17 12:18
I don't understand the question maybe... 
On web onChangeText is called before onSelectionChange and in it we change ":+1:" to "👍 " 
=> Both have the same lengths
=> Selection doesn't change
=> onSelectionChange is never called

Is your question "Why does onSelectionChange is called before onChangeText on native and not  on web ?" and do you think we should fix that (probably upstream) ?

**Comment by ShogunFire** [comment] 2023-07-17 13:13
I made a snack to show that when we change the text in onChangeText and keep the same length, onSelectionChange is never called on web whereas on android it is called:
Here is the snack:
https://snack.expo.dev/@moctrof/forlorn-truffle

On android:

https://github.com/Expensify/App/assets/19537677/ac66be6b-d275-4b20-b690-b6fcef708013

On web:

https://github.com/Expensify/App/assets/19537677/054e40c5-5e53-415a-bb25-2b4df6963be7

**Comment by flaviadefaria** [comment] 2023-07-18 10:16
@aimane-chnaif how are things looking? Melvin is suggesting we take this internally, are we close to a proposal or should I move this to our engineering team?

**Comment by makiour** [comment] 2023-07-18 10:54
Hey @aimane-chnaif,

I am Mohammed, an experienced full-stack developer and worked as SWE engineer intern at Google and Meta and currently working remotely as an SWE intern at a Fintech company in Dubai.

I am curious if this is still open. I would be more than happy to help with the root cause of this issue and collaborate on the same business day to fix it

Let me know if it is the case!
Mohammed

**Comment by ShogunFire** [comment] 2023-07-21 22:42
Hello @aimane-chnaif Is my explanation of the root cause enough to be Assigned ? Otherwise what else do you want me to do ?

**Comment by ShogunFire** [comment] 2023-07-22 01:43
Just to get a hint for what you expect, do you agree with this :

> And I think the behaviour on web is the good one, I think onSelectionChange should only be called after onChangeText and if the selection has really changed.

**Comment by flaviadefaria** [comment] 2023-07-24 11:40
@aimane-chnaif do we have an update here?

**Comment by flaviadefaria** [comment] 2023-07-26 08:28
Friendly bump here.

**Comment by flaviadefaria** [comment] 2023-07-31 08:15
@aimane-chnaif it's past a week since you last updated this issue. Can you please give an update? Thanks!

**Comment by flaviadefaria** [comment] 2023-08-07 11:16
@aimane-chnaif please update this today.

**Comment by Skalakid** [comment] 2023-08-10 10:51
Hey, I’m Michał from Software Mansion, an expert agency, and I will help close this issue out.

**Comment by Skalakid** [comment] 2023-08-10 11:59
Hi, @ShogunFire thanks for the proposal. After some investigation, I agree with @aimane-chnaif that the root cause you described is not correct for this issue. I tested all platforms and on each of them `onSelectionChange` is launching after `onChangeText`. On iOS and Android this feature works but on the web and mobile web it doesn't. Maybe it changed after updating react-native to `0.72.3` but it is not a root cause

**Comment by ShogunFire** [comment] 2023-08-10 12:14
@Skalakid I am still able to reproduce onSelectionChange not being called


https://github.com/Expensify/App/assets/19537677/27a0e241-745e-438c-b7df-f0c20b156732

**Comment by ShogunFire** [comment] 2023-08-10 12:24
And yes on android/ios it is called after but also before it is called twice. one time for `:+1:` and the other time for the smiley

**Comment by Skalakid** [comment] 2023-08-10 12:50
@ShogunFire oh thanks for the comment I think misunderstood you, sorry. In this case, I can agree with you. On android/ios `onSelectionChange` is called twice but on the web devices never 😅

**Comment by Skalakid** [comment] 2023-08-10 12:52
However I'm not sure about the solution

**Comment by Skalakid** [comment] 2023-08-10 12:57
@ShogunFire how about changing `this.setState({suggestedEmojis: [],});` to `this.calculateEmojiSuggestion();`? @aimane-chnaif what do you think about it?

**Comment by hannojg** [comment] 2023-08-11 13:58
(Thanks @aimane-chnaif <3 )

**Comment by flaviadefaria** [comment] 2023-08-14 13:25
Put this on hold and switched it to wweekly.

**Comment by Skalakid** [comment] 2023-08-21 09:57
@aimane-chnaif I think we can take it off hold since https://github.com/Expensify/App/pull/18648 was merged. The bug still occurs, so I checked the changes and updated my proposal

**Comment by Skalakid** [comment] 2023-08-22 08:10
@aimane-chnaif bump

**Comment by Skalakid** [comment] 2023-08-28 13:15
@aimane-chnaif @flaviadefaria bump

**Comment by Skalakid** [comment] 2023-09-04 08:04
@flaviadefaria can you remove hold tag, please?

**Comment by Skalakid** [comment] 2023-09-04 08:04
@aimane-chnaif were you able to reevaluate proposals again?

**Comment by flaviadefaria** [comment] 2023-09-04 08:29
Done! @aimane-chnaif what do you think about the submitted proposals?

**Comment by Skalakid** [comment] 2023-09-06 09:11
@aimane-chnaif bump

**Comment by flaviadefaria** [comment] 2023-09-11 10:15
Ok please give an update this week @aimane-chnaif thanks!

**Comment by Skalakid** [comment] 2023-09-14 13:10
@aimane-chnaif bump

**Comment by flaviadefaria** [comment] 2023-09-14 18:12
@aimane-chnaif should I assign this to another C+?

**Comment by flaviadefaria** [comment] 2023-09-15 10:58
@trjExpensify  I'm going OoO for a week so assigning this to you so that you can move it forward in the meantime. I'll take it back from you once I'm online again. Thanks!

**Comment by trjExpensify** [comment] 2023-09-15 11:27
Question: Why does this have the `internal` label on it, and if we're soliciting proposals still, shouldn't it have `help wanted`?

**Comment by trjExpensify** [comment] 2023-09-15 11:38
Right, but if it didn't actually come internal and we're looking for proposals, we should change that otherwise people won't find it. Anyway, let's focus [on this](https://github.com/Expensify/App/issues/20998#issuecomment-1673176449) while we're here. 

I can reproduce this issue on MacOS desktop, so its not an issue isolated to Android as stated above. 

@Skalakid I'm curious with your proposal where the root cause identifies why this is only a problem we see with the `:+1:` emoji shortcut and not something like `:heart:`?

**Comment by ShogunFire** [comment] 2023-09-15 11:49
@trjExpensify There are other proposals before @Skalakid one that are very similar, for example mine here https://github.com/Expensify/App/issues/20998#issuecomment-1634587754 where the explaination of the root cause might be better. I also made some comments and a snack here: https://github.com/Expensify/App/issues/20998#issuecomment-1638116621

**Comment by trjExpensify** [comment] 2023-09-18 09:50
Gotttcha, this is helpful:

>But on some platforms onSelectionChanged is called after onChangeText. And in onChangeText (updateComment for us) we change the text from ":+1" to "👍 " and both have the same length. Since they have the same length the selection doesn't change and onSelectionChanged is never called.

So this is actually a problem for any emoji shortcuts that have the same length. How bizarre! @aimane-chnaif this issue is hanging out, breaking WAQ, and sooo close to a proposal approval. Can you get to it today, please? Thanks!

**Comment by Skalakid** [comment] 2023-09-18 10:10
@trjExpensify Yes the problem is that `onSelectionChanged ` works differently on web and native devices. On the web, the event is not being launched when you replace text with a different one of the same length. In our case, we change ":+1" to "👍 " and both have a length of 3. I updated the root cause in my proposal and the solution (since many things changed after merge freeze)

**Comment by trjExpensify** [comment] 2023-09-20 11:26
Thanks, @Skalakid! @aimane-chnaif can you take a look today please?

**Comment by Skalakid** [comment] 2023-09-21 09:54
@aimane-chnaif bump

**Comment by trjExpensify** [comment] 2023-09-25 05:16
@aimane-chnaif can we get an update on progress since the 21st, please?

**Comment by trjExpensify** [comment] 2023-09-27 08:00
Bump, @aimane-chnaif.

**Comment by ShogunFire** [comment] 2023-09-27 23:37
@aimane-chnaif The proposal of @Skalakid is not up to date either because now emojis returned are not only new emojis.

**Comment by ShogunFire** [comment] 2023-09-28 01:05
## Proposal
[Updated](https://github.com/Expensify/App/issues/20998#issuecomment-1634587754)

A proposal that handle the new emojis only and not all emojis of the text

**Comment by trjExpensify** [comment] 2023-09-28 11:18
So are we proceeding with that proposal?

**Comment by trjExpensify** [comment] 2023-09-29 08:10
Sure, happy to pop it on hold but can you perhaps elaborate a touch on the dependency? Do we expect it to be fixed by that PR? Will there be a bunch of conflicts if we don't wait? or something else?

**Comment by trjExpensify** [comment] 2023-09-29 09:31
Cool, thanks. Updated!

**Comment by flaviadefaria** [comment] 2023-10-02 11:50
Thanks @trjExpensify! I'm back now so will take this off your plate.

**Comment by trjExpensify** [comment] 2023-10-02 20:26
Sounds good, all yours! ❤️

**Comment by flaviadefaria** [comment] 2023-10-05 11:49
Since this is on hold I'll switch to weekly.

**Comment by flaviadefaria** [comment] 2023-10-12 10:50
@NicMendonca I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by ShogunFire** [comment] 2023-10-12 13:34
@aimane-chnaif  https://github.com/Expensify/App/pull/27687 has been merged, can you review my [proposal](https://github.com/Expensify/App/issues/20998#issuecomment-1634587754)?

**Comment by ShogunFire** [comment] 2023-10-12 13:45
Yes

**Comment by NicMendonca** [comment] 2023-10-13 18:56
@Li357 proposal for you! ^

**Comment by Li357** [comment] 2023-10-16 13:56
Looks good @ShogunFire, all yours!

**Comment by NicMendonca** [comment] 2023-10-25 18:45
I was hoping that would recreate the since expired Upwork job 😄

**Comment by NicMendonca** [comment] 2023-10-25 18:49
@aimane-chnaif you hero!

**Comment by NicMendonca** [comment] 2023-10-25 18:50
can you both accept the offers please? 🙏

**Comment by ShogunFire** [comment] 2023-10-25 20:34
I accepted the offer

**Comment by NicMendonca** [comment] 2023-10-26 18:24
@aimane-chnaif just need you to accept the off please!

**Comment by NicMendonca** [comment] 2023-10-26 18:24
@ShogunFire you've been paid! 🎉

**Comment by NicMendonca** [comment] 2023-10-30 12:37
everyone has been paid! ✅

**Closed by NicMendonca** 2023-10-30 12:37 UTC
Labels: External, Engineering, Daily, Overdue, Bug

**Comment by ShogunFire** [comment] 2024-05-26 10:58
@NicMendonca Hello, sorry for the late request but could you put the upwork mission as completed ? Because it makes my upwork profile worse otherwise. Thanks

**Comment by stephanieelliott** [comment] 2024-05-30 21:52
> Hello, sorry for the late request but could you put the upwork mission as completed ? Because it makes my upwork profile worse otherwise. Thanks

I took care of this!
