### ISSUE TITLE
[$500] Request Money - The currency search field fails to auto-focus

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27100] opened 2023-09-10 07:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "Request Money" section.
3. Click on the currency option
4. Observe that the search field does not auto-focus.

## Expected Result:
The currency search field should automatically focus upon clicking, ready for user input

## Actual Result:
The currency search field does not auto-focus upon clicking, resulting in the need for click on search field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1,3,66,3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9dcbd8e8-942f-4fe3-8bcd-d8c1fba7f690

https://github.com/Expensify/App/assets/93399543/df7c50ac-5f5e-4fde-90cb-2b6e172542ab

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691438190303789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01885f56507c4e1e91</li>
        <li>Upwork Job ID: 1700780208323342336</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-10 08:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currency search field fails to autofocus.

### What is the root cause of that problem?
The selection list gains focus after the text input is initially focused which causes 

### What changes do you think we should make in order to solve the problem?
Add `shouldDelayFocus` prop to the `OptionsSelector` in IOUCurrencySelection.

### What alternative solutions did you explore? (Optional)
None.

**Comment by ishpaul777** [comment] 2023-09-10 08:10
Dupe of https://github.com/Expensify/App/issues/27030

**Comment by mallenexpensify** [comment] 2023-09-11 07:10
Closing as it appears to be a dupe of the below.  Thanks @ishpaul777 for the 👀 and comment
-  #27030

**Closed by mallenexpensify** 2023-09-11 07:10 UTC
Labels: External, Daily, Help Wanted, Bug
