### ISSUE TITLE
Submit expense - Empty space between input field and loading skeleton in participant list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47524] opened 2024-08-15 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual
3. Enter amount
4. Click Next

## Expected Result:
There should not be empty space between input field and the loading skeleton in participant list.

## Actual Result:
There is empty space between input field and the loading skeleton in participant list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8a3dbf6c-73dc-4d92-b530-ba04b7704ff2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-15 20:59
Production:

https://github.com/user-attachments/assets/62cf506d-30b3-4d56-940b-65f0d541ae67

**Comment by lanitochka17** [comment] 2024-08-15 20:59
We think that this bug might be related to #vip-vsp

**Comment by AndrewGable** [comment] 2024-08-15 21:21
Ah OK so it seems like this space

<img width="221" alt="Google Chrome 2024-08-15 at 15 20 27" src="https://github.com/user-attachments/assets/be9f207f-7496-4bf2-a32e-46d80b04eff6">

**Comment by AndrewGable** [comment] 2024-08-15 21:42
@mountiny @tienifr @allroundexperts - Seems like this is a regression from https://github.com/Expensify/App/pull/42413

**Comment by Beamanator** [comment] 2024-08-19 14:27
Looks like this was fixed in staging! https://expensify.slack.com/archives/C01GTK53T8Q/p1724077613257529?thread_ts=1723755541.991329&cid=C01GTK53T8Q

**Comment by Beamanator** [comment] 2024-08-19 14:28
closing b/c PR author & C+ were on the original PR that caused the regression (no payment needed)

**Closed by Beamanator** 2024-08-19 14:28 UTC
Labels: Reviewing, Engineering, Weekly
