### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Chat - Emoji Picker Doesn't Close on User B's Side When User A Deletes a Message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31727] opened 2023-11-22 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to User A's account
2. Open User B's chat
3. Send a message
4. Open User A’s chat from User B’s account in a different browser
5. Hover over the message and click on “Reply in thread”
6. Send a message in the thread
7. Click on “Add reaction” on the thread message
8. Go back to User A's account
9. Delete the sent message

## Expected Result:
The emoji picker should close on User B's side when User A deletes the message

## Actual Result:
The emoji picker does not close on User B's side when User A deletes the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6962f78b-cce9-4591-ab71-7713e8ee0a6e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012937eab50c4eb634</li>
        <li>Upwork Job ID: 1727376326080495616</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 27872062</li>
<li>s-alves10 | Contributor | 27872064</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-22 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Emoji Picker Doesn't Close on User B's Side When User A Deletes a Message

### What is the root cause of that problem?
We don't have logic to hide emoji picker when the message is delete 
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/pages/home/report/ReportActionItem.js#L183

In here we should add condition to check if the message is delete we will hide emoji picker


### What alternative solutions did you explore? (Optional)

**Comment by saikoaizen** [comment] 2023-11-22 17:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Emoji Picker Doesn't Close on User B's Side When User A Deletes a Message
### What is the root cause of that problem?
In the function where the delete message is handled, we are not checking if emoji picker is active.
### What changes do you think we should make in order to solve the problem?
We should add this line EmojiPickerAction.hideEmojiPicker(true); in the if condition below.
https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/pages/home/report/ReportActionItemFragment.js#L108C1-L110C14

**Comment by s-alves10** [comment] 2023-11-22 17:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji picker doesn't close on user B when user A deletes the parent message

### What is the root cause of that problem?

We are hiding the `EmojiPicker` when a message is deleted here
https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/pages/home/report/ReportActionItem.js#L183-L185

But when we delete a thread parent message, the message is not unmounted because deleted parent action is a visible action. 

This is the root cause

### What changes do you think we should make in order to solve the problem?

Now we hide the `EmojiPicker` on unmount. We need to hide the `EmojiPicker` for deleted parent action as well
Update
https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/pages/home/report/ReportActionItem.js#L175-L191
to
```
    const isDeletedParentAction = ReportActionsUtils.isDeletedParentAction(props.action);
    useEffect(
        () => {
            if (isDeletedParentAction && EmojiPickerAction.isActive(props.action.reportActionID)) {
                EmojiPickerAction.hideEmojiPicker(true);
            }
            return () => {
                ... ...
            };
        },
        [props.action.reportActionID, reactionListRef, isDeletedParentAction],
    );
```

This works as expected

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by getusha** [comment] 2023-11-24 14:14
@DylanDylann @saikoaizen  your RCA is not correct & complete, we already have a logic to handle cases when a message is deleted https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/pages/home/report/ReportActionItem.js#L184

@dukenv0307 i see the only difference in your proposal from @s-alves10's is prevIsDeletedParentAction can you explain why we need to check if they are equal and return early?

**Comment by s-alves10** [comment] 2023-11-24 14:52
@dukenv0307 

`reportActionID` would never change during the lifecycle of the `ReportActionItem` component.
And `reactionListRef` won't change once it's created

So the above effect callback will be called only when `isDeletedParentAction` changes
I just wrote the idea and make it clear later.

And as @getusha mentioned, `prevIsDeletedParentAction` isn't needed at all

**Comment by s-alves10** [comment] 2023-11-24 15:09
I didn't write the cleanup callback clearly because it isn't so important

That's a minor problem and can be handled while reviewing

**Comment by s-alves10** [comment] 2023-11-24 15:38
@dukenv0307 

AFAIK, adding minor optimization or fix doesn't have big impact on selecting a proposal as long as its RCA is correct and suggested solution can fix the issue. Possible regressions will be handled during the PR review. 

I don't want to argue anymore. Let @getusha decide.
Thanks

**Comment by adelekennedy** [comment] 2023-11-27 17:10
@getusha will review

**Comment by getusha** [comment] 2023-11-28 14:30
Thanks everyone for your proposals, Based on the solutions, there isn't much difference between them. Given that, @s-alves10's [proposal](https://github.com/Expensify/App/issues/31727#issuecomment-1823210410) looks good to me, as it was the first one to identify/state the right root cause. the solution works perfectly.

🎀👀🎀 C+ reviewed

**Comment by s-alves10** [comment] 2023-11-29 18:44
@getusha 

PR is ready for review https://github.com/Expensify/App/pull/32209

**Comment by adelekennedy** [comment] 2023-12-22 00:32
### Payouts due:

Contributor: $500 @getusha (Upwork)
Contributor+: $500 @s-alves10 (Upwork)

@getusha for the checklist when you get a chance!

**Comment by getusha** [comment] 2023-12-22 11:53
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@getusha] The PR that introduced the bug has been identified. Link to the PR: This is a case we missed to handle.
- [x] [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/a
- [x] [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- [x] [@getusha] Determine if we should create a regression test for this bug. Yes
- [x] [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Login to User A
2. Login to User B in a separate browser/private tab
3. Send message to User A
4. Reply in thread for the newly sent message
5. Add a new message and send it in thread
6. User A: Go to the chat and open the thread
7. Hover over the first message in the thread
8. Open emoji picker from the mini context menu
9. User B: Delete the threads first message 
10. Verify that the emoji picker is hidden after the parent message is deleted.

Do we agree 👍 or 👎

**Comment by adelekennedy** [comment] 2024-01-05 20:40
Back from ooo! thank you all for you patience, closing this out

**Closed by adelekennedy** 2024-01-05 20:40 UTC
Labels: External, Weekly, Awaiting Payment, Bug
