### ISSUE TITLE
[HOLD for payment 2023-09-18] [$1000] Waypoint Fade-out shade looks different on iOS 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#24447] opened 2023-08-11 18:02 UTC
Address the follow up items from this PR  https://github.com/Expensify/App/pull/23698

1. Fade-out shade looks different on iOS
2. https://github.com/Expensify/App/pull/23698#discussion_r1289405984
3. https://github.com/Expensify/App/pull/23698/files#r1287832648
4. https://github.com/Expensify/App/pull/23698/files#r1287834040

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4b4d5b8f32dc5f7</li>
        <li>Upwork Job ID: 1691262935970217984</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26494035</li>
<li>Pujan92 | Contributor | 26494037</li>
</ul></li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-08-15 01:37
I'm going to make this an external bug because I think it's super low value. Or I would recommend that we close it.

**Comment by Pujan92** [comment] 2023-08-15 03:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Waypoint fade out shade isn't looks correct for iOS

### What is the root cause of that problem?
Specific to this library the bg color `transparent` will not get applied with 0 opacity for iOS and that seems to be a cause for this issue. 
https://github.com/react-native-linear-gradient/react-native-linear-gradient/issues/358#issuecomment-432612745

### What changes do you think we should make in order to solve the problem?
We need to explicitly set the transparent background by applying a bg color with 0 opacity.
https://github.com/Expensify/App/blob/42757411e9d715ca77456242425677e47b522873/src/components/DistanceRequest.js#L126

```
colors={[`${theme.modalBackground}00`, theme.modalBackground]}
```
Or we can use the util function `getBackgroundColorWithOpacityStyle`.

**Comment by neil-marcellini** [comment] 2023-08-15 16:45
Ok sounds good. Let's also get a design review in that case.

**Comment by adelekennedy** [comment] 2023-08-18 21:41
checking here- this is kind of a catch all issue for some other waypoint design updates. Any proposals should cover all the issues @thienlnam linked?

**Comment by adelekennedy** [comment] 2023-08-21 17:39
Still pending proposals - I wonder if we should clarify the issue title?

**Comment by thienlnam** [comment] 2023-08-22 23:41
Looks like the design changes I had were addressed, so now it is just the fade out shade issue and the other clean up items mentioned in the issue description

**Comment by adelekennedy** [comment] 2023-08-25 19:28
pending more proposals

**Comment by neil-marcellini** [comment] 2023-08-28 16:35
@situchan please review the proposals today. If you can not, let us know and we will find a new C+.

**Comment by situchan** [comment] 2023-08-28 16:37
reviewing today

**Comment by situchan** [comment] 2023-08-29 15:45
> > As proposals are quite similar
> 
> @situchan do you prefer to do manual color manipulation as suggested in the selected proposal?

Fine to me. We don't necessarily use `polished` package even though it's already installed as dependency of another package.

**Comment by Pujan92** [comment] 2023-08-31 08:57
@dukenv0307 I am not actually getting your point, just to explain my proposal whatever the first gradient color we are using the same color with the 0 opacity we need to use to make the transparent. Ref - [lib readme](https://github.com/react-native-linear-gradient/react-native-linear-gradient#transparent-gradient)

**Comment by adelekennedy** [comment] 2023-09-01 22:59
not overdue

**Comment by neil-marcellini** [comment] 2023-09-04 16:40
I'm moving this to a weekly since it's very low priority

**Comment by neil-marcellini** [comment] 2023-09-04 16:40
I will review the proposal later today

**Comment by neil-marcellini** [comment] 2023-09-04 18:40
> @Pujan92 @dukenv0307 thanks for proposals.
> I agree with RCA and solutions also work.
> As proposals are quite similar, I think we should assign @Pujan92 as proposed first.
> cc: @neil-marcellini

I agree that @Pujan92's proposal is good. He was first, and although @dukenv0307  raises some good points, those problems are only hypothetical for now. I also agree that we should avoid another library dependency.

**Comment by adelekennedy** [comment] 2023-09-18 08:49
### Payouts due:

Issue Reporter: N/A
Contributor: $1000 @Pujan92 Upwork
Contributor+: $1000 @situchan Upwork

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/jobs/~01b4b4d5b8f32dc5f7).

**Closed** 2023-09-18 08:53 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
