### ISSUE TITLE
Web - User details message click button does not open user report page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22125] opened 2023-07-03 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user A should have 1 or more request money/task report with user B and after login, user B report should not be opened, user A should also have group with user B
1. Open the app and login with user A
2. Open request money/task report of user B
3. Click on search and open group report with user B in it
4. Click on group avatars to open group details
5. Click on user B to open user B details
6. Click on message and observe that app opens report opened in step 2 instead of opening main user B report

## Expected Result:
App should open user report on click on message in user details

## Actual Result:
App opens user request/task report on click on message in user details if we first open user request/task report  and then search for group with that user and from group, open user details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/413f30c3-befb-4e1b-97ff-597c8746980c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688204408974849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-04 10:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User details message click button does not open user report page

### What is the root cause of that problem?
If user A click message button on user B's detail page, `Report.navigateToAndOpenReport` is called, and then `ReportUtils.getChatByParticipants` is called.
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/pages/ProfilePage.js#L210
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/libs/actions/Report.js#L514-L525
`ReportUtils.getChatByParticipants` function will iterate all report actions and find the first report whose participant id is equal to user B's account id.
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/libs/ReportUtils.js#L1961-L1972
`ReportUtils.getChatByParticipants` does not filter out money requests and report actions are stored randomly in `Onyx`, so money requests whose participant id equal to user B's account id may be returned.
The task report may also be returned if user A creates a task and assigns it to user B, and then clicks the message button on user B's detail page.

### What changes do you think we should make in order to solve the problem?
We can add `onlyIncludeChatReport` parameter to `ReportUtils.getChatByParticipants` with `false` default value.
And pass `true` to `ReportUtils.getChatByParticipants` function.

```js
-	function getChatByParticipants(newParticipantList) {
+	function getChatByParticipants(newParticipantList, onlyIncludeChatReport = false) {
		newParticipantList.sort();
		return _.find(allReports, (report) => {
			// If the report has been deleted, or there are no participants (like an empty #admins room) then skip it
			if (!report || !report.participantAccountIDs || isThread(report)) {
				return false;
			}

+			if (onlyIncludeChatReport && !isChatReport(report)) {
+				return false;
+			}

			// Only return the room if it has all the participants and is not a policy room
			return !isUserCreatedPolicyRoom(report) && _.isEqual(newParticipantList, _.sortBy(report.participantAccountIDs));
		});
}
```

```js
function navigateToAndOpenReportWithAccountIDs(participantAccountIDs) {
    let newChat = {};
-   const chat = ReportUtils.getChatByParticipants(participantAccountIDs);
+   const chat = ReportUtils.getChatByParticipants(participantAccountIDs, true);
    if (!chat) {
        newChat = ReportUtils.buildOptimisticChatReport(participantAccountIDs);
    }
    const reportID = chat ? chat.reportID : newChat.reportID;

    // We want to pass newChat here because if anything is passed in that param (even an existing chat), we will try to create a chat on the server
    openReport(reportID, [], newChat, '0', false, participantAccountIDs);
    Navigation.dismissModal(reportID);
}
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by mallenexpensify** [comment] 2023-07-05 21:58
@dhanashree-sawant, I'm unable to reproduce, any idea what I should be doing differently? 

https://github.com/Expensify/App/assets/22508304/f62f0777-de1c-49cf-a8d6-28346a66ded8

**Comment by mallenexpensify** [comment] 2023-07-11 03:27
@dhanashree-sawant, I'm going to assign you to see if it helps get ya 👀 on the above, I'm unable to reproduce

**Comment by dhanashree-sawant** [comment] 2023-07-11 05:34
Hi @mallenexpensify, sorry for the delay, your steps seems to be perfectly fine. 1 thing to note is that it occurs only once after login so maybe that you can try. If still not reproducible, we can close it.

**Comment by mallenexpensify** [comment] 2023-07-15 00:25
Unable to reproduce again.  Are you able to consistently @dhanashree-sawant ?

**Comment by dhanashree-sawant** [comment] 2023-07-15 03:10
Hi @mallenexpensify, thanks for rechecking, the reproduction is slightly unreliable so I think we can close it for now.

**Closed** 2023-07-17 20:55 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
