### ISSUE TITLE
[HOLD for payment 2023-07-24] [$250] Migrate KeyboardShortcutsModal.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16172] opened 2023-03-20 08:39 UTC
### Filenames
- [ ] [src/components/KeyboardShortcutsModal.js](https://github.com/Expensify/App/blob/main/src/components/KeyboardShortcutsModal.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`, `componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01678291804db5d8d5</li>
        <li>Upwork Job ID: 1678837080014872576</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 06:57
I'd like to work on this issue

**Comment by disha-np** [comment] 2023-07-06 11:55
Can I work on this migration issue

**Comment by olexyt** [comment] 2023-07-07 13:54
I can work on this issue.

**Comment by payal-lathidadiya** [comment] 2023-07-11 18:46
dibs?

**Comment by alpeshl** [comment] 2023-07-11 18:48
Can I work on this?

**Comment by crazy-coding** [comment] 2023-07-11 18:49
I'd love to work on this.

**Comment by disha-np** [comment] 2023-07-11 18:49
I'd like to work on this

**Comment by yh-0218** [comment] 2023-07-11 18:49
I can work on this task. Thanks.

**Comment by kmwamasali** [comment] 2023-07-11 18:49
would like to work on this

**Comment by Talha345** [comment] 2023-07-11 18:52
I'd love to work on this.

**Comment by Vadym-33** [comment] 2023-07-11 18:53
I hope to work on this task.

**Comment by vadymbokatov** [comment] 2023-07-11 18:54
I'd love to work on this issue

**Comment by neonbhai** [comment] 2023-07-11 18:56
I woul love to work on this!

**Comment by KrAbhas** [comment] 2023-07-11 19:02
I would like to work on this

**Comment by Talha345** [comment] 2023-07-11 19:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We are trying to refactor `KeyboardShortcutsModal.js` from a class component to a function component.

### What is the root cause of that problem?

N/A

### What changes do you think we should make in order to solve the problem?

We should understand the existing class component and re-write it using functional syntax. Class states and lifecycle methods should be updated to use hooks (useState, useEffect) and references to props should be converted to prop arguments.

Finally, the references to the component should be updated and testing should be done to make sure everything is working correctly.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by to-ai** [comment] 2023-07-11 21:21
I am able to work on this task.

**Comment by mkhutornyi** [comment] 2023-07-11 21:33
I'd like to work on this.

**Comment by narefyev91** [comment] 2023-07-12 07:15
In case that for this items we do not require any proposals - first one was @muxriddinmuqimov77 - will you be able to work on this issue?

**Comment by disha-np** [comment] 2023-07-12 08:03
@narefyev91 as per [this guide](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119), i think the first to leave a comment after the issue is taken off HOLD and labeled as external should be eligible to get assigned.

**Comment by narefyev91** [comment] 2023-07-12 08:05
> @narefyev91 as per [this guide](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119), i think the first to leave a comment after the issue is taken off HOLD and labeled as external should be eligible to get assigned.

Makes sense - @rayane-djouah will you be able to work on this one?

**Comment by s-alves10** [comment] 2023-07-12 08:09
https://github.com/Expensify/App/issues/16172#issuecomment-1578385553

**Comment by narefyev91** [comment] 2023-07-12 08:11
> @narefyev91 yes I'm able to work on this one

We can assign @rayane-djouah
🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment] 2023-07-12 09:03
Woot, love it!

**Comment by iwiznia** [comment] 2023-07-21 20:19
Seems this is mostly ready, so not unassigning myself, but if this does not get closed, @dylanexpensify  please unassign and re-assign another engineer since I am going on sabbatical

**Comment by dylanexpensify** [comment] 2023-07-28 19:50
Sorry! Doing now!

**Comment by dylanexpensify** [comment] 2023-07-28 19:51
Paid! TY!

**Comment by arosiclair** [comment] 2023-07-28 21:28
I think this is all set so closing

**Closed by arosiclair** 2023-07-28 21:28 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment
