### ISSUE TITLE
[HOLD for payment 2023-07-20] Task Detailed View Redesign

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#19330] opened 2023-05-19 23:29 UTC
![image](https://github.com/Expensify/App/assets/30609178/8cec901e-3f4e-45a5-a098-5027efecd3b5)
![image](https://github.com/Expensify/App/assets/30609178/34ca233f-c6d4-4f86-84dd-a355142c01db)
![image](https://github.com/Expensify/App/assets/30609178/2ccabbd0-04da-4be4-a9d3-39bcbacbb3da)
![image](https://github.com/Expensify/App/assets/30609178/882d6ec6-1791-48d3-9c01-8d779fb4794b)

Update the task detailed view to look like the above mockups
This issue is mostly focusing on the detailed view within the task. There will be another issue for the LHN / header title view as well as the deleted view, so no need to worry about those here

- Move the 'Mark as done' button to the header
- The task details float above the comments in the report and can be scrolled out of screen if there are enough comments
- The task title now contains a checkbox that can be used
- When there is no assignee or description, it should middle align the input

![image](https://github.com/Expensify/App/assets/30609178/f3238348-c960-47f1-8498-843061ca9d3d)
![image](https://github.com/Expensify/App/assets/30609178/c6c01d9a-c7c1-4183-a5eb-7c453d4d30f1)

https://expensify.slack.com/archives/C04QEB4MJEQ/p1684396364608389

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184754c976c0dca40</li>
        <li>Upwork Job ID: 1666918061946351616</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-05-22 09:39
Oh cool, glad I randomly got assigned on this issue. I think those are good questions. Just a quick heads up that I'm out of office the remainder of this week.

**Comment by twisterdotcom** [comment] 2023-05-30 22:15
I'm not super sure what we should do with this. Do we both need to pre-design how to handle all these questions?

**Comment by thienlnam** [comment] 2023-06-01 16:58
Yup, looks like @JmillsExpensify and @shawnborton are leading up this new header view that works for tasks/money requests/threads

https://expensify.slack.com/archives/C04QEB4MJEQ/p1684777292283899

**Comment by thienlnam** [comment] 2023-06-01 16:59
Reassigning since this is holding on that pre-design conversation

**Comment by JmillsExpensify** [comment] 2023-06-08 03:43
Let's make sure that we don't include the icons! Those were removed

**Comment by JmillsExpensify** [comment] 2023-06-08 03:45
Also, I still have some reservations here? Can we take this back to Slack?

**Comment by thienlnam** [comment] 2023-06-08 21:19
This is ready now, updated the description with the latest convo from slack!

**Comment by thienlnam** [comment] 2023-06-08 22:13
Yes, the money request design is also getting updated in a similar vein as this. I would hold off on any updates to the existing design until the re-design is done. @JmillsExpensify Do you know if there is an issue for the manual request re-design?

**Comment by shawnborton** [comment] 2023-06-12 12:56
Okay, I think this is where we landed on this one:
<img width="1061" alt="image" src="https://github.com/Expensify/App/assets/2319350/93c1e76e-ba8c-4c89-9584-728ed318802c">

**Comment by shawnborton** [comment] 2023-06-12 12:57
Though I'm unsure if we want a right caret for the Created by row... that seems extraneous.

**Comment by thienlnam** [comment] 2023-06-12 16:38
Yeah agreed, I think we should remove it because you can't actually change the created by anyways

**Comment by jasperhuangg** [comment] 2023-06-15 12:38
Gonna get started on this today, was there another task header restyle issue that we wanted to tackle with this issue as well? cc @thienlnam

**Comment by thienlnam** [comment] 2023-06-15 18:43
> Gonna get started on this today, was there another task header restyle issue that we wanted to tackle with this issue as well?

Just created the issue here https://github.com/Expensify/App/issues/20844, don't mind taking it separately if that helps

**Comment by jasperhuangg** [comment] 2023-06-19 21:35
Tasks are broken on main... so I needa debug that before I can keep progressing with that PR

Otherwise ditto what Shawn said above, it's really close to getting merged and the design is basically done

**Comment by thienlnam** [comment] 2023-06-22 00:48
Jasper is handling this issue! I'm just here to help review and push along as needed

**Comment by jasperhuangg** [comment] 2023-06-22 17:21
Not overdue! Was sorting out some bugs with tasks that were introduced because of the SNH privacy changes so this got held back a bit.

**Comment by s77rt** [comment] 2023-06-28 20:35
@thienlnam 

> This issue is mostly focusing on the detailed view within the task. There will be another issue for the LHN / **header title view** as well as the deleted view, so no need to worry about those here

We have this issue https://github.com/Expensify/App/issues/21713 which is about the header title view, should we put it on hold or proceed?

**Comment by thienlnam** [comment] 2023-06-28 22:30
Please put that issue on hold until we resolve this!

**Comment by jasperhuangg** [comment] 2023-07-10 20:56
We deemed the regression wasn't a deploy blocker. I've also fixed it in this PR: https://github.com/Expensify/App/pull/22586

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:17
Hired @fedirjh in Upwork 

Internal job - https://www.upwork.com/ab/applicants/1666918061946351616/job-details
External job - https://www.upwork.com/jobs/~0184754c976c0dca40

@fedirjh or @jasperhuangg Should a regression test apply to this?

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:18
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing PR and prepping for payment based on https://github.com/Expensify/App/issues/19330#issuecomment-1636305260

**Comment by jasperhuangg** [comment] 2023-07-17 20:04
> Hired @fedirjh in Upwork
> 
> Internal job - https://www.upwork.com/ab/applicants/1666918061946351616/job-details External job - https://www.upwork.com/jobs/~0184754c976c0dca40
> 
> @fedirjh or @jasperhuangg Should a regression test apply to this?

No need for a regression test, the existing regression tests should cover this flow

**Comment by jasperhuangg** [comment] 2023-07-17 20:04
This is still on HOLD for payment not overdue

**Comment by jasperhuangg** [comment] 2023-07-21 21:08
@fedirjh were you paid out?

**Comment by jasperhuangg** [comment] 2023-07-22 00:11
@JmillsExpensify Can you help make sure @fedirjh gets paid out? It looks like @Christinadobrzyn has already hired them on Upwork: https://github.com/Expensify/App/issues/19330#issuecomment-1636305260

**Comment by jasperhuangg** [comment] 2023-07-24 21:14
@JmillsExpensify friendly bump! Can we get @fedirjh paid out for reviewing the PR?

**Comment by JmillsExpensify** [comment] 2023-07-24 21:52
Jumping in now! Thanks

**Comment by JmillsExpensify** [comment] 2023-07-24 21:54
Alright, @fedirjh is all paid out. I didn't see any automation related to a an urgency bonus, or any other mention of it, so I've paid the $1k standard amount.

**Closed by JmillsExpensify** 2023-07-24 21:55 UTC
Labels: Daily, Internal, NewFeature, Awaiting Payment, Bug
