### ISSUE TITLE
[$250] QBO - Lag in connecting to QBO integration to appear

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44225] opened 2024-06-23 23:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718998564033989

## Action Performed:
1. Go to workspace
2. Enable Accounting
3. Connect to QBO

## Expected Result:
After connected to QBO integration settings should appear (Export import and advanced)
## Actual Result:
User has to switch to another menu item and come back to appear or it lags to appear
## Workaround:
unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/44f0ab0d-6402-4369-938d-d8546289ba14

https://github.com/Expensify/App/assets/38435837/d0e934e1-3570-45de-9454-589dad82cab8

https://github.com/Expensify/App/assets/38435837/427e21de-11c2-4850-86b9-f964d7d63e53

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010007783bfe9633b1</li>
        <li>Upwork Job ID: 1806492121279205749</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103032600</li>
<li>nkdengineer | Contributor | 103032602</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by mallenexpensify** [comment] 2024-06-24 23:58
@s77rt , I see you've worked on the QBO project, any thoughts here?

**Comment by aldo-expensify** [comment] 2024-06-25 01:28
This is know, there is this slack conversation about it: https://expensify.slack.com/archives/C036QM0SLJK/p1718817925842049

We don't have a proposed solution yet.

**Comment by mallenexpensify** [comment] 2024-06-25 23:32
@aldo-expensify , can it be external?

**Comment by aldo-expensify** [comment] 2024-06-26 00:29
Don't know really, I'm not sure if it possible to solve this with a purely front end solution or if we need stuff done in the backend.

**Comment by aldo-expensify** [comment] 2024-06-26 00:30
Maybe we can add `External` and see if someone has a purely frontend proposal that can work?

**Comment by mallenexpensify** [comment] 2024-06-28 00:58
> Maybe we can add External and see if someone has a purely frontend proposal that can work?

I like it! @brunovjk , do you think it can be external!!?

**Comment by nkdengineer** [comment] 2024-06-28 08:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User has to switch to another menu item and come back to appear or it lags to appear

### What is the root cause of that problem?
When checking `isSyncInProgress` [here](https://github.com/Expensify/App/blob/main/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L137-L141)

We only check that `connectionSyncProgress.stageInProgress !== CONST.POLICY.CONNECTIONS.SYNC_STAGE_NAME.JOB_DONE`, we don't check if the connection data is already available in the app.

So there's a few seconds between "Job done" Pusher update and connection data Pusher update, and the loading indicator does not show and connection data also doesn't show up during this period.

### What changes do you think we should make in order to solve the problem?

When checking `isSyncInProgress`, if the `stageInProgress` is `JOB_DONE`, but the connection data for that specific connection is not there yet, `isSyncInProgress` will still be `true`

It will become false only after both `stageInProgress` becomes `JOB_DONE` and connection data becomes available.

We can update [this line](https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L139) to something like
```
(connectionSyncProgress.stageInProgress !== CONST.POLICY.CONNECTIONS.SYNC_STAGE_NAME.JOB_DONE || !policy.connections?.[connectionSyncProgress.connectionName]) &&
```

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-06-28 08:18
[Proposal updated](https://github.com/Expensify/App/issues/44225#issuecomment-2196376399) to add an alternative solution

**Comment by nkdengineer** [comment] 2024-06-28 08:37
[Proposal updated](https://github.com/Expensify/App/issues/44225#issuecomment-2196376399) to clarify the change

**Comment by brunovjk** [comment] 2024-06-28 15:44
> > Maybe we can add External and see if someone has a purely frontend proposal that can work?
> 
> I like it! @brunovjk , do you think it can be external!!?

@mallenexpensify I believe so. We need to update how we indicate the status to the user after connecting. I tested the main solution from @nkdengineer' [proposal](https://github.com/Expensify/App/issues/44225#issuecomment-2196376399), and it looks good to me. The update in `isSyncInProgress` appears to solve the issue well. We just need to confirm the copy for the warning **indicating that it's waiting for the connection data**, right?

🎀👀🎀 C+ reviewed

**Comment by jamesdeanexpensify** [comment] 2024-06-28 16:05
@deetergp I also just found the [Slack thread](https://expensify.slack.com/archives/C036QM0SLJK/p1718817925842049) where this was discussed recently, might have some helpful info for you!

**Comment by deetergp** [comment] 2024-07-01 22:17
Is confirmation or suggestions on `Waiting for connection data` from @Expensify/marketing what we need here?

**Comment by nkdengineer** [comment] 2024-07-02 17:11
@deetergp Yes, it's just text copy, we can handle it in PR phase. I can start on the PR once you [assign me](https://github.com/Expensify/App/issues/44225#issuecomment-2197208358)

**Comment by mallenexpensify** [comment] 2024-07-03 00:07
Added `Waiting for copy`.   @deetergp , @nkdengineer can start on the PR without the exact copy, right? If so, can you assign them?  Thx

**Comment by LLPeckham** [comment] 2024-07-03 09:10
Heya, I'm not seeing the context on where `Waiting for connection data` is supposed to go - can anyone share a screenshot or something so I can weigh in? Is it this screen that loads with no copy clues as to what's happening, or something else?

Thanks!


![Screenshot 2024-07-03 at 10 09 39 AM](https://github.com/Expensify/App/assets/6799061/6cff1016-c4f0-47a9-8ddc-78590aecd561)

**Comment by deetergp** [comment] 2024-07-03 15:10
@nkdengineer Can you help @LLPeckham with that? https://github.com/Expensify/App/issues/44225#issuecomment-2205494491

**Comment by nkdengineer** [comment] 2024-07-03 16:48
Of course, @LLPeckham below is the video, you can see the "Waiting for connection data" is the last step before the connection shows to the user. At this point in time, the connection was already successful (that's why the stage is called `jobDone`), but the data of the connection did not arrive at the front-end yet so we need to wait a little bit.

https://github.com/Expensify/App/assets/161821005/849df8b9-c6e6-4ee8-aebc-a2c1db6589a3

**Comment by deetergp** [comment] 2024-07-03 20:10
Nice, @nkdengineer thanks 👍

@LLPeckham does that work for you?

**Comment by LLPeckham** [comment] 2024-07-04 08:56
That's super helpful, thank you @nkdengineer! 

Would it make sense to say: "Waiting for imported data to load"

Or could do "Waiting for connection data to load"

**Comment by nkdengineer** [comment] 2024-07-04 16:29
> Would it make sense to say: "Waiting for imported data to load"

@LLPeckham That makes sense to me, thanks!

@deetergp Shall we move forward here?

**Comment by brunovjk** [comment] 2024-07-05 16:23
friendly bump @deetergp

**Comment by jamesdeanexpensify** [comment] 2024-07-08 12:49
We could also do something fun like 'Almost there...' on this last loading step - but don't let that suggestion be a blocker if nothing can be changed further!

**Comment by nkdengineer** [comment] 2024-07-09 04:49
@brunovjk this [PR](https://github.com/Expensify/App/pull/45041) is ready for review

**Comment by brunovjk** [comment] 2024-07-22 11:32
PR reached production [5 days ago](https://github.com/Expensify/App/pull/45041#issuecomment-2229342365), it looks like the automation didn't work here. @mallenexpensify can you help me, so I can fill out the checklist? Thank you.

**Comment by mallenexpensify** [comment] 2024-07-22 21:51
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @brunovjk paid $250 via Upwork 

@brunovjk plz complete the BZ checklist below. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by brunovjk** [comment] 2024-07-23 11:27
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

**Regression Test Proposal**
1. Go to a Workspace.
2. Enable Accounting.
3. Connect with an accounting provider.
4. Verify that the UI updates with status messages throughout the process.
5. Ensure that integration settings (Export, Import, Advanced) appear immediately after connection.

Do we agree 👍 or 👎

**Comment by brunovjk** [comment] 2024-07-26 11:07
Do you think we can close this issue @mallenexpensify ? Thank you :D

**Comment by mallenexpensify** [comment] 2024-07-30 23:20
Test case created, closing.  Thanks all!
- https://github.com/Expensify/Expensify/issues/416536

**Closed** 2024-07-30 23:21 UTC
Labels: External, Daily, Overdue, Bug
