### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] Chat–Name of message owner disappears from DM for a second when delete first message in Offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32101] opened 2023-11-28 11:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Disable the internet connection in the main testing device
4. Choose the first of several messages you already sent back-to-back
5. Verify the chat header with your name appears only on your first message
6. Hover over that first message to view the action menu
7. Click/Tap on the Trash icon to delete the message
8. Go Online

## Expected Result:
The message has been deleted

## Actual Result:
The name of the message owner disappears from conversation for a second when delete first message in Offline and go back to Online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/f496a976-f10e-4ff9-a143-7bb15b09a04a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bb87b742d38cd4b</li>
        <li>Upwork Job ID: 1729458938833915904</li>
        <li>Last Price Increase: 2023-11-28</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 28062142</li>
<li>tienifr | Contributor | 28062150</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by AmjedNazzal** [comment] 2023-11-28 11:40
Can you please check the screenshots/videos section, it seemed to have not uploaded correctly.

**Comment by Santhosh-Sellavel** [comment] 2023-11-29 19:21
@tienifr's proposal LGTM!
C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-12-04 18:03
@Julesssss Any update?

**Comment by Julesssss** [comment] 2023-12-05 09:08
It was discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1688630003862989), and it looks like we're aligned on the proposal to not use Onyx.connect. Lets pass required data to components with `withOnyx`.

**Comment by Julesssss** [comment] 2023-12-07 15:15
@tienifr good spot, that sounds reasonable.

**Comment by Julesssss** [comment] 2023-12-11 11:20
not overdue, in discussion...

**Comment by kevinksullivan** [comment] 2023-12-14 14:57
@Julesssss how should we decide the direction here? Sounds like the work will get done somewhere, but we're debating the issue? Or is the proposed solution still up for debate?

**Comment by Julesssss** [comment] 2023-12-14 15:31
Still need C+ approval. 

@Santhosh-Sellavel could you please based on this discussion and the updated proposals? Thanks

**Comment by shubham1206agra** [comment] 2023-12-14 18:42
I will take over here.

**Comment by Santhosh-Sellavel** [comment] 2023-12-14 18:48
Requested for a new C+ [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1702579265491999). @shubham1206agra volunteered, so please assign them!

**Comment by shubham1206agra** [comment] 2023-12-14 19:15
I have gone through the conversation, and I think @tienifr's [proposal](https://github.com/Expensify/App/issues/32101#issuecomment-1830261136) would be better to go in this case since it is optimized, and most probably will not introduce any performance regressions.
🎀 👀 🎀 C+ Reviewed

**Comment by shubham1206agra** [comment] 2023-12-14 19:15
@Julesssss Over to you

**Comment by Julesssss** [comment] 2023-12-21 15:40
PR merged, awaiting payment

**Comment by shubham1206agra** [comment] 2024-01-03 16:03
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27957
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27957/files#r1440618886
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need as they are optimizing performance and forgot to add offline tests.
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. Yes
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
1. Go to App
2. Send someone messages back-to-back.
3. Disable the internet connection.
4. Choose the first of several messages you already sent back-to-back
5. Verify the chat header with your name appears only on your first message
6. Hover over that first message to view the action menu
7. Click/Tap on the Trash icon to delete the message
8. Go Online

* [ ]  [@kevinksullivan] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by shubham1206agra** [comment] 2024-01-08 12:43
@kevinksullivan Bump for the payment here

**Comment by Julesssss** [comment] 2024-01-08 17:49
Not overdue, just awaiting payment

**Comment by Julesssss** [comment] 2024-01-12 14:11
Waiting for payment

**Comment by kevinksullivan** [comment] 2024-01-12 20:03
Thanks for your patience, everyone! Paid out.

**Closed by kevinksullivan** 2024-01-12 20:03 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
