### ISSUE TITLE
[$1000] mweb/Safari - Workspace - Invite button in invite message page hides behind keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33548] opened 2023-12-23 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Workspaces > any workspace
2. Go to Members > Invite
3. Select any member > Next
4. Focus on the invite message field

## Expected Result:
The Invite button will move above the keyboard

## Actual Result:
The Invite button is hidden behind the keyboard. In order to show the invite button while keyboard is open, user has to scroll down the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/694cdde3-7c07-4b2c-b89f-b46c1b67ef5a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e381cef3b4dde0b</li>
        <li>Upwork Job ID: 1738596942038294528</li>
        <li>Last Price Increase: 2024-02-19</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28078003</li>
<li>paultsimura | Contributor | 28107877</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-23 16:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The system keyboard visibility is not handled properly on the `WorkspaceInviteMessagePage`.

### What changes do you think we should make in order to solve the problem?
We should add the `shouldEnableMaxHeight` property to the `ScreenWrapper` here:

https://github.com/Expensify/App/blob/b74be723548d45d47dde7fe29aff5eafe16b290f/src/pages/workspace/WorkspaceInviteMessagePage.js#L131-L134

### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2023-12-25 01:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invite button in invite message page (Workspace) should appear on top keyboard, not hide behind keyboard.
( mweb/Safari - Workspace - Invite button in invite message page hides behind keyboard )

### What is the root cause of that problem?

=> WorkspaceInviteMessagePage.js

shouldEnableMaxHeight not setting to true in ScreenWrapper

### What changes do you think we should make in order to solve the problem?

Just add shouldEnableMaxHeight as true in ScreenWrapper's prop.

### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2023-12-26 16:19
@anmurali Unassigning this one due to low bandwidth please assign a new C+ here, thanks!

**Comment by situchan** [comment] 2023-12-26 20:02
I can take over

**Comment by anmurali** [comment] 2024-01-02 23:06
@situchan assigned to you. Can you review the proposals and pick one?

**Comment by situchan** [comment] 2024-01-08 17:10
All proposed to enable `shouldEnableMaxHeight`. I am checking if this doesn't cause any side effect.

**Comment by situchan** [comment] 2024-01-11 17:25
still validating solution

**Comment by situchan** [comment] 2024-01-15 17:19
Not overdue

**Comment by situchan** [comment] 2024-01-18 11:28
@paultsimura's [proposal](https://github.com/Expensify/App/issues/33548#issuecomment-1868326617) looks good to me.
I don't see the need of `viewportOffsetTop`. User can see header anyway by scrolling up. And this might cause the issue of message input being hidden on small devices like iPhone SE.
We already applied `shouldEnableMaxHeight` in tons of places without `viewportOffsetTop`.

🎀 👀 🎀 C+ reviewed

**Comment by paultsimura** [comment] 2024-01-20 19:25
Working on the PR now

**Comment by paultsimura** [comment] 2024-01-22 08:23
Hey @situchan,
After I started working on the PR, I think @tienifr was right about the need for `viewportOffsetTop`:
Without it, the header gets scrolled up, but the `shouldEnableMaxHeight` counts for it to be in-frame when calculating the height, therefore the following issue happens. The screen wrapper gets kinda cut off from the bottom, and requires an extra scroll to take its place:

https://github.com/Expensify/App/assets/12595293/2b97abd9-e59e-40f0-b6a9-19249597453c

However, when adding the `viewportOffsetTop`, the issue doesn't happen:

https://github.com/Expensify/App/assets/12595293/ad988307-f859-45e3-b3e7-01dab6d9bfe9

Other places, where we use `shouldEnableMaxHeight` without `viewportOffsetTop`, just don't have much content: it's mostly a single form input (e.g. edit money request description), so the issue doesn't happen on them.

WDYT, should we consider re-reviewing the proposals here in favor of @tienifr?

**Comment by situchan** [comment] 2024-01-22 08:25
@paultsimura how does it look with `viewportOffsetTop` on very small device like iPhone SE?

**Comment by paultsimura** [comment] 2024-01-22 08:59
> iPhone SE

https://github.com/Expensify/App/assets/12595293/fc8d570c-1257-4112-8ed2-7fa16341dc48

**Comment by paultsimura** [comment] 2024-01-23 08:14
Ping @situchan 🙋

**Comment by situchan** [comment] 2024-01-23 10:36
Agree it looks worse than current version. I think we should adjust top offset in that specific page.
@madmax330 what do you think about https://github.com/Expensify/App/issues/33548#issuecomment-1903474735?

**Comment by madmax330** [comment] 2024-01-29 11:34
@Expensify/design what do you think here?

**Comment by dubielzyk-expensify** [comment] 2024-01-29 22:38
Agree that we should have the button be fixed to the bottom like other screens

**Comment by shawnborton** [comment] 2024-01-30 12:50
And just to clarify, I'm not suggesting we permanently fix it to the bottom of the screen. I think we have a pattern that exists that allows the button to appear docked to the bottom of the screen but also can just sit right below the content if the content is a bit longer. This prevents the combination of keyboard + button from eating too much screen real estate, thus making a form hard to use. Here is the example I was referencing: 

https://github.com/Expensify/App/assets/2319350/3b4e43fc-ea75-4b86-8f2c-4b0cf85bcf66

**Comment by madmax330** [comment] 2024-02-05 09:59
Bump @situchan can you re-evaluate the proposals?

**Comment by situchan** [comment] 2024-02-08 15:50
@paultsimura @tienifr do you have updated solution as per https://github.com/Expensify/App/issues/33548#issuecomment-1916777757?

**Comment by paultsimura** [comment] 2024-02-08 16:48
> @paultsimura @tienifr do you have updated solution as per https://github.com/Expensify/App/issues/33548#issuecomment-1916777757?
> 
> 

Not from my side, unfortunately. Even our existing pages that @shawnborton mentioned are quite buggy in Safari — I won't be able to come up with a solid solution here

**Comment by situchan** [comment] 2024-02-12 16:02
I think we're waiting for new/updated proposal which meets https://github.com/Expensify/App/issues/33548#issuecomment-1916777757

**Comment by puneetlath** [comment] 2024-02-19 21:06
Updating the bounty to try and get some proposals.

**Comment by puneetlath** [comment] 2024-02-22 14:05
@situchan thoughts?

**Comment by situchan** [comment] 2024-02-26 15:31
@suneox thanks for the proposal. Does your solution resolve [this concern](https://github.com/Expensify/App/issues/33548#issuecomment-1916777757)? And mind sharing test branch?

**Comment by situchan** [comment] 2024-03-04 14:38
> So should we need to update into the scope of this issue or separate to another issue?

I don't think we will create separate issue for that.
But based on complexity, that might be considered out of scope.

So the solution should be
- demo approved by design team
- not complex or over-engineered

**Comment by anmurali** [comment] 2024-03-07 00:26
Discussing the proposal, not overdue.

**Comment by madmax330** [comment] 2024-03-13 07:11
@situchan thoughts on the above?

**Comment by shawnborton** [comment] 2024-03-13 13:15
Hmm this might be on purpose though since the invite message could potentially be quite long? Basically I think we did that to prevent having a moving/growing text input potentially grow to be below the fixed submit button. So I'm actually not sure if this is a bug, it might be intended behavior and thus we could close it out.

**Comment by shawnborton** [comment] 2024-03-13 13:16
Curious if @Expensify/design has an opinion though. I think we don't have a bulletproof approach for these kinds of bottom-of-the-view buttons.

I had long advocated for a system where if there is enough vertical space, the button stays in view docked to the bottom of the screen. But if the content above the button became long, it would push the button down and out of view. I think we did implement this kind of thing correctly on some of the profile details pages (like your display name), but not sure if that works well everywhere else.

**Comment by dannymcclain** [comment] 2024-03-13 13:58
@shawnborton I'm not sure I have much to add here—bottom-docked and then anchored to the top of keyboard feels pretty standard for buttons like this, but I'm honestly having a little trouble following this thread.

**Comment by shawnborton** [comment] 2024-03-13 14:00
All good! I guess my thinking is that when we anchor a big button to the top of the keyboard, we don't really give the user too much space to scroll in their viewport. Then if we add a scrollable/growing element in that remaining small space - in this case, it's a textarea that grows with a long invite message - I feel like we kinda set the user up for a tricky UI to interact with. 

That being said, you could argue that keeping the button fixed to the keyboard makes it so that you don't have to worry about awkward scroll issues to be able to submit.

**Comment by dannymcclain** [comment] 2024-03-13 15:00
Ahh I see what you're saying!

Now I understand and agree with your comment here:
>if there is enough vertical space, the button stays in view docked to the bottom of the screen. But if the content above the button became long, it would push the button down and out of view

If we implemented behavior like that, couldn't we also update the keyboard "go" button (I don't know what it's called, I'll point it out in a screenshot) to reflect whatever action is in the big green button (that would in this case be out of view)?

![Screenshot 2024-03-13 at 9 57 08 AM](https://github.com/Expensify/App/assets/7516624/7d98588c-191a-4731-8e4c-8f39f16c5291)

**Comment by shawnborton** [comment] 2024-03-13 16:12
> If we implemented behavior like that, couldn't we also update the keyboard "go" button (I don't know what it's called, I'll point it out in a screenshot) to reflect whatever action is in the big green button (that would in this case be out of view)?

Yes! Big fan of that.

**Comment by anmurali** [comment] 2024-03-18 23:49
Are we fixing this in https://github.com/Expensify/App/issues/35380 @situchan? Or vice versa?

**Comment by situchan** [comment] 2024-03-19 04:40
> Are we fixing this in #35380 @situchan? Or vice versa?

No, it's different issue

**Comment by situchan** [comment] 2024-03-22 15:26
What's the next step here?
Do nothing or something to fix?

**Comment by wildan-m** [comment] 2024-03-27 02:23
@situchan @paultsimura I am unable to replicate the bug mentioned [here](https://github.com/Expensify/App/issues/33548#issuecomment-1903474735) with the latest main version. I believe adding `shouldEnableMaxHeight` alone should work fine.

https://github.com/Expensify/App/assets/11847279/f8ccd92d-5711-4dc5-99b4-34cfc92f4a02

**Comment by situchan** [comment] 2024-03-28 02:11
@suneox thanks for the proposal but I wonder if this issue should just be closed as "do nothing" based on [feedback](https://github.com/Expensify/App/issues/33548#issuecomment-1994477269) from @Expensify/design.

@madmax330 what do you suggest?

**Comment by madmax330** [comment] 2024-03-29 13:27
Yeah I think we should just close

**Closed** 2024-04-01 14:12 UTC
Labels: External, Engineering, Daily, Internal, Help Wanted, Overdue, Bug
