### ISSUE TITLE
Web- Room - Hitting enter on create room generates space on the composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20129] opened 2023-06-03 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Click on + icon . Click on new room
3.Type a room name and fill every details
4. Now hit enter to create a room and notice that extra line of space is seen on the composer
5. While hitting enter, only a room should have been created. But it also generates a line of extra space on the composer

## Expected Result:
Hitting enter on create room should not generate space on the composer

## Actual Result:
Hitting enter on create room generates space on the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f78decaa-405a-4ead-96fc-8532ba37b1c2

https://github.com/Expensify/App/assets/93399543/bd51a443-e40a-4355-9131-a6b958d57c06

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685526899395409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sethraj14** [comment] 2023-06-03 21:20
I think this is the dupe of this [issue](https://github.com/Expensify/App/issues/19771).

**Comment by kbecciv** [comment] 2023-06-04 13:40
Yes, missed this duplicate

**Comment by sonialiap** [comment] 2023-06-06 22:32
Due to dupe and this comment https://github.com/Expensify/App/issues/19771#issuecomment-1569396127, closing

**Closed by sonialiap** 2023-06-06 22:32 UTC
Labels: Daily, Overdue, Bug
