### ISSUE TITLE
[HOLD for payment 2024-12-30] [$500] IOS - Compose Box - App crashes when pasting a text with an image

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52475] opened 2024-11-13 13:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51855
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2060@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open IOS app
2. Open any chat and paste this text inside of the compose box
![test](https://camo.githubusercontent.com/4848d0f965f332077b77a1a0488c3e66b4769032104f4de6890bae218b4add8d/68747470733a2f2f70696373756d2e70686f746f732f69642f313036372f3230302f333030
)_test
3. Try to send the message or go back

## Expected Result:
The text with the image gets sent

## Actual Result:
App freezes at first and crashes after a while

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/27701433-691f-49fe-b122-aec2738e57e5
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856775016601889974</li>
        <li>Upwork Job ID: 1856775016601889974</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by garrettmknight** [comment] 2024-11-13 14:59
Commented on the offending issue.

**Comment by garrettmknight** [comment] 2024-11-13 19:04
@ntdiary can you take a look at [this PR](https://github.com/Expensify/App/pull/51855) and see if it's causing the problem?

**Comment by badeggg** [comment] 2024-11-14 09:37
@IuliiaHerets Can you please comment the exact text that was pasted inside the compose box?

**Comment by garrettmknight** [comment] 2024-11-14 15:58
Thanks @ntdiary - we'll solve here then!

**Comment by IuliiaHerets** [comment] 2024-11-14 20:54
@badeggg Posted the exact text that was pasted inside the compose box. It is the same as @ntdiary mentioned
`![test](https://camo.githubusercontent.com/4848d0f965f332077b77a1a0488c3e66b4769032104f4de6890bae218b4add8d/68747470733a2f2f70696373756d2e70686f746f732f69642f313036372f3230302f333030
)_test`

**Comment by badeggg** [comment] 2024-11-15 10:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App stalls when pasting specific text inside the compose box.

### What is the root cause of that problem?
We are using few **huge** regexp when parse the text. Check how big it is, this is the regexp we are using to check image url:
<img width="1465" alt="Screenshot 2024-11-15 at 17 52 07" src="https://github.com/user-attachments/assets/24b449db-f55f-4bb2-8dde-902dca600211">

Similar regexp size with 'video' and 'link'. Huge regexp is consuming huge executing resource, which cause the stall. 

#### Relate codes:
- [regexp of link/image/video](https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/ExpensiMark.ts#L76-L82)
- most regexp parts are coming from [file Url.js](https://github.com/Expensify/expensify-common/blob/main/lib/Url.js)
- the huge part is coming from [tlds](https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/tlds.jsx#L1-L2), to be honest, this tlds file does not really make sense to me

#### Why only happen in iOS
- Web application works fine on web, I guess it's because web is javascript oriented which has a way better js runtime and hence works fine.
- While in iOS, this piece of code is running in [hermes runtime](https://github.com/Expensify/react-native-live-markdown/blob/c352064a2f6c71d457277d958a0270c9d989db5a/apple/RCTMarkdownUtils.mm#L39-L41), which has limit resource. 
- For android, this piece of code is running in [hermes runtime](https://github.com/Expensify/react-native-live-markdown/blob/c352064a2f6c71d457277d958a0270c9d989db5a/android/src/main/cpp/MarkdownUtils.cpp#L16-L18), which has limit resource too. The stall should happen on android too, though I didn't check it.


### What changes do you think we should make in order to solve the problem?
Though I don't really agree the existence of [file tlds.jsx](https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/tlds.jsx), for the sake of minimal change principle, I suggest change [regexp of link/image/video](https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/ExpensiMark.ts#L76-L82) to:
```jsx
const MARKDOWN_LINK_REGEX = new RegExp(`\\[([^\\][]*(?:\\[[^\\][]*][^\\][]*)*)]\\(${UrlPatterns.LOOSE_URL_REGEX}\\)(?![^<]*(<\\/pre>|<\\/code>))`, 'gi');
const MARKDOWN_IMAGE_REGEX = new RegExp(`\\!(?:\\[([^\\][]*(?:\\[[^\\][]*][^\\][]*)*)])?\\(${UrlPatterns.LOOSE_URL_REGEX}\\)(?![^<]*(<\\/pre>|<\\/code>))`, 'gi');
const MARKDOWN_VIDEO_REGEX = new RegExp(`\\!(?:\\[([^\\][]*(?:\\[[^\\][]*][^\\][]*)*)])?\\(((${UrlPatterns.LOOSE_URL_REGEX})\\.(?:${Constants.CONST.VIDEO_EXTENSIONS.join('|')}))\\)(?![^<]*(<\\/pre>|<\\/code>))`, 'gi');

```
That is saying to replace `UrlPatterns.MARKDOWN_URL_REGEX` with `UrlPatterns.LOOSE_URL_REGEX`, which has a reasonable regexp part.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by badeggg** [comment] 2024-11-16 09:01
> App still gets stuck. 

Yeah, it's frustrating. I noticed the size of the regexp is not the cause. I guess it's because some part of the regexp 'somehow' trigger an edge case  of regexp executor in hermes. I can find which part(or parts) if causing the stall, but it's definitely not the *root* cause.

**Comment by badeggg** [comment] 2024-11-16 13:58
I have updated [my proposal](https://github.com/Expensify/App/issues/52475#issuecomment-2478497680)

**Comment by badeggg** [comment] 2024-11-19 10:07
I have updated https://github.com/Expensify/App/issues/52475#issuecomment-2478497680, with a more accurate root cause.

**Comment by badeggg** [comment] 2024-11-21 08:02
I have updated [my proposal](https://github.com/Expensify/App/issues/52475#issuecomment-2478497680). Thank you for your patience.

I also updated my opinion. The  root cause is **regexp execution get stuck when too many possibilities before failing**, pattern `(\w*)*m` is just one of the cases, a simple case though. *Too many possibilities* is usually created in a regexp when set a quantifier inside a group and set another quantifier just after the group definition. 

We can find few cases in out project [here](https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/Url.js#L3-L18):
![Screenshot 2024-11-21 at 15 53 47](https://github.com/user-attachments/assets/8bdd9bd6-8541-49db-a7c2-d0e6ea69bee9)

**Comment by badeggg** [comment] 2024-11-21 08:53
The alternative solution in my proposal can solve this problem, change the super complicated url pattern to a simple url pattern like: `https?:\/\/[0-9a-z\.-\/?=&#]+`. But it's a big change, guess this solution needs an internal check.

I think there is not a perfect solution.

**Comment by badeggg** [comment] 2024-11-21 13:12
Hi, I have updated [my proposal](https://github.com/Expensify/App/issues/52475#issuecomment-2478497680), just added tech details for the alternative solution.

**Comment by badeggg** [comment] 2024-11-22 09:38
- Guess my description "regexp execution get stuck when too many possibilities before failing" has a formal name: catastrophic backtracking.
- I looked into the regex, the reason for catastrophic backtracking is two pairs of nesting quantifiers, we can flatten them to avoid 'too many possibilities', but few simple url patterns can not be covered.
- **From my view**
   - It's almost impossible to write a single regexp to cover all possibilities of the standard defined url, while avoid catastrophic backtracking in js
   - It's not necessary for us to accurately cover all possibilities of the standard defined url 
   - So I stand with the alternative solution of my proposal: use a simple regexp

**Comment by badeggg** [comment] 2024-11-23 10:07
> it would parse an image markdown link as video html tag

I think there is not a clear rule that define what kind of urls are video type and others are image type. The type of the content behind a url can only be determined after requested from server. We can only guess. Currently, we guess a link is video type by checking whether there is a video file extension string(e.g. .mp4) in the url string.

> or treat url like http://-77.com and http://test?test as valid

Yeah, It's a concession. I think it's user's responsibility to make sure a url is valid, not us. Just when I typing, I notice that github is recognizing http://test?test as a url link string.


Or maybe wait for more proposals.

**Comment by garrettmknight** [comment] 2024-11-26 13:07
Let's give this a little more time for proposals - I'll also increase the bounty. If we don't get more proposals in a week or so, we can consider @badeggg's current solution as a viable option.

@badeggg thanks for working on it thus far - these regex issues tend to get pretty tricky.

**Comment by garrettmknight** [comment] 2024-11-26 17:51
Shouldn't be overdue - just waiting for other proposals.

**Comment by s77rt** [comment] 2024-12-02 01:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Typing media markdown format causes app to lag


### What is the root cause of that problem?
The [`LOOSE_URL_WEBSITE_REGEX`](https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/Url.js#L15) is expensive and matching against long strings results in too many backtracks.


### What changes do you think we should make in order to solve the problem?

Change:
```js
([a-z0-9](?:[-a-z0-9]*[a-z0-9])?\\.)*(?:[a-z0-9](?:[-a-z0-9]*[a-z0-9])?)
```

To:
```js
((?!-)[-a-z0-9]+(?<!-)(?:\\.(?!-)[-a-z0-9]+(?<!-))*)
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
Writing a perf-test for this case may be tricky because the code must run in hermes as this bug is partially upstream (hermes's regex engine is slow compared to v8's).


### What alternative solutions did you explore? (Optional)

None

**Comment by badeggg** [comment] 2024-12-02 03:43
Friendly remind, nesting quantifiers still exist in regexp `((?!-)[-a-z0-9]+(?<!-)(?:\.(?!-)[-a-z0-9]+(?<!-))*)`. Nesting quantifiers is a typical reason for catastrophic backtracking.
![Screenshot 2024-12-02 at 11 37 52](https://github.com/user-attachments/assets/11cae325-00db-43d2-8479-218a4f558af9)

**Comment by dangrous** [comment] 2024-12-02 16:57
I'm checking to see if we have a minimum version for browsers - https://expensify.slack.com/archives/C01GTK53T8Q/p1733158498606189 but if not this solution sounds good!

**Comment by s77rt** [comment] 2024-12-02 17:23
I think we can proceed because the lookbehind assertions are already used in [ExpensiMark](https://github.com/Expensify/expensify-common/blob/302e37e40d9d7e718e7c1c3d98faaa644b51da9d/lib/ExpensiMark.ts). There is no gain in blocking this unless the other regex are refactored/planned to be refactored

- reportMentions (positive lookbehind)
- inlineCodeBlock (negative lookbehind)
- italic (negative lookbehind)
- bold (negative lookbehind)
- strikethrough (negative lookbehind)

**Comment by dangrous** [comment] 2024-12-02 20:22
ah okay, that works - I'll assign you now and we can always reevaluate if needed.

**Comment by s77rt** [comment] 2024-12-05 12:35
**Update:**
- expensify-common https://github.com/Expensify/expensify-common/pull/822: ✅ Merged 
- react-native-live-markdown PR https://github.com/Expensify/react-native-live-markdown/pull/557: ✅ Merged
- App PR https://github.com/Expensify/App/pull/53627: 🐞 Bugs... The App crashes. Will look into this asap, it seems related to reanimated worklet. I found this [PR](https://github.com/Expensify/react-native-live-markdown/pull/439) that may have some info. I also found that this [compatibility table](https://github.com/Expensify/react-native-live-markdown?tab=readme-ov-file#compatibility) states that RN 0.76 is required but we are still on 0.75 (though not sure how accurate the min version actually is)

**Comment by dangrous** [comment] 2024-12-05 16:18
let us know what you find out!

**Comment by s77rt** [comment] 2024-12-06 14:06
**Update**: Tried with RN 0.76 but the app still crashes. The crash is related to the new `parser` prop, using a custom parser works but using the default parser (the `ExpensiMark`) results in a crash. Will work on isolating the problem and report back.

**Comment by s77rt** [comment] 2024-12-06 22:02
**Update:** I found that the problem is related to this `useAnimatedStyle` hook https://github.com/Expensify/App/blob/b595f5d24141a403fcc3f44c73d00cd6951dca7d/src/pages/home/report/AnimatedEmptyStateBackground.tsx#L30-L45

More accurately it's the reference to the `CONST` object (which is is _imported_) (`CONST.ANIMATION_GYROSCOPE_VALUE`) that causes the crash. If we avoid referring the `CONST` object inside the worklet and instead define a scooped const in the function, it will work.

Still working on the root cause. FWIW this only occurs after [dispatching the markdown commit hook](https://github.com/Expensify/react-native-live-markdown/blob/9ad0acdc7ffcd2d0be23fb64031bcac2ebed872e/android/src/main/java/com/expensify/livemarkdown/LiveMarkdownModule.java#L25-L29).

**Comment by s77rt** [comment] 2024-12-08 19:07
**Update:** Still no clear root cause but the bug occurs because of the regex that is in `CONST`. I have provided a reproducible and raised an [issue](https://github.com/Expensify/react-native-live-markdown/issues/574) in `react-native-live-markdown`. Regardless, we shouldn't pass `CONST.ANIMATION_GYROSCOPE_VALUE` to the worklet as it could cause performance degradation [^1]. The next step is to write a lint rule to prevent passing objects to worklets so we avoid both problems (performance degradation and the crash).

[^1]: https://docs.swmansion.com/react-native-reanimated/docs/guides/worklets/#capturing-closure

**Comment by s77rt** [comment] 2024-12-08 21:52
**Update:** @tomekzaw Found the root cause and the solution for the crash and it's upstream in `react-native-reanimted`. Waiting for some inputs on https://github.com/software-mansion/react-native-reanimated/pull/6796 before creating a patch.

**Comment by s77rt** [comment] 2024-12-09 17:01
**Update:** Applied the `react-native-reanimated` patch and the app no longer crashes. However I'm running into a different bug, `![test](https://google.com)` does not work on E/App but it does in the `react-native-live-markdown` example. Gotta work on isolating the bug and find what's causing this problem.

**Comment by tomekzaw** [comment] 2024-12-09 22:03
@s77rt You'll also need to add `'worklet';` directive at the beginning of `node_modules/html-entities/index.js`.

**Comment by s77rt** [comment] 2024-12-09 22:54
@tomekzaw Thanks! That what I was missing! Please document that in `react-native-live-markdown`

**Comment by s77rt** [comment] 2024-12-10 02:30
**Update:** E/App PR https://github.com/Expensify/App/pull/53627 is ready for review.

**Comment by tomekzaw** [comment] 2024-12-10 08:29
@s77rt I've submitted a PR to `react-native-live-markdown` that throws an error if `html-entities` is not workletized:
* https://github.com/Expensify/react-native-live-markdown/pull/576

Thanks for the suggestion!

**Comment by tomekzaw** [comment] 2024-12-10 10:45
Yep, we should QA the composer input with various Markdown massages since we changed the way how ExpensiMark is run and there could be some regressions.

**Comment by Kicu** [comment] 2024-12-10 10:58
@ntdiary yeah and since you have done so much already I think I can wait with mine until yours gets merged. The good news is that I already did a lot of manual testing of passing the parser as worklet on my branch - which is the same version so they should apply.

I didn't notice anything big but we should be ready for some possible small mistakes and regressions.
Best to test it with multiple types of markdown syntax:
 - **bold**, _italic_, underline, strikethrough 
 - quotes, nested quotes, backticks, triple backtick
 - links 
etc

**Comment by dangrous** [comment] 2024-12-10 17:39
Thanks for all the hard work here! Let me know if/how I can help as we move this forward

**Comment by dangrous** [comment] 2024-12-17 19:13
Where are we at on this one?

**Comment by s77rt** [comment] 2024-12-17 21:15
PR is merged and waiting to hit production

**Comment by s77rt** [comment] 2024-12-28 21:18
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [X] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/expensify-common/pull/598#discussion_r1899000024

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1735420481256159

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

    Bug requires regression test: No (not a QA test). We may require to add an automated test but it's not clear if that is possible yet (see linked discussion above)

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by s77rt** [comment] 2024-12-30 14:22
Payment should be $500 ^

**Comment by garrettmknight** [comment] 2024-12-30 14:58
This is ready for payment. Submit when you're ready.

**Closed by garrettmknight** 2024-12-30 14:58 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-12-30 16:23
$500 approved for @ntdiary

**Comment by JmillsExpensify** [comment] 2024-12-30 16:27
$500 approved for @s77rt
