### ISSUE TITLE
 Payment - The default label is set automatically when closing the payment tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21732] opened 2023-06-27 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Go to Settings -> Payments
4. Add Chaise as the 1-st Payment method
5. Add Fiderily as the 2-nd Payment method
6. Close Payment tab
7. Reopen Payment tab

## Expected Result:
The default label is not set for any payment method

## Actual Result:
2-nd Payment method set automatically as default

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c48d64f1-96a3-48e8-abad-07f5f1ea97e1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Tea

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-06-27 20:36
I can reproduce this, but this is expected behavior. if you only have one payment method, it is always the default, so the label is not needed. 

When you add a second payment method, we add the default flag to your most recently added payment method, as there is now more than one, so we need to show the customer which is default. 

Closing as this is not a bug!

**Closed by joekaufmanexpensify** 2023-06-27 20:36 UTC
Labels: Daily, Bug
