### ISSUE TITLE
[HOLD for Payment 2024-05-15][$500] mWeb - Chat - Infinite loading on video preview before sending video

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39078] opened 2024-03-27 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4456414
**Email or phone of affected tester (no customers):** vdargentotest+mweb032724@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Tap on "+" button
3. Select "Add attachment" and any other option
4. Select a video

## Expected Result:
A video preview should be displayed before sending the video

## Actual Result:
The video preview page keeps loading infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce92fe38-e6dd-44ce-be51-7e00e4190a3f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c647e39b68ccf23</li>
        <li>Upwork Job ID: 1773758325269905408</li>
        <li>Last Price Increase: 2024-05-01</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-27 16:23
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-27 16:23
We think that this bug might be related to vip-vsp

**Comment by alexpensify** [comment] 2024-03-29 16:58
Tested with the website and confirmed that it does load. Now, going to try in an iOS web browser. 

![2024-03-29_09-57-39](https://github.com/Expensify/App/assets/8107070/78fc4f33-008f-4794-9794-087828d6a547)

**Comment by alexpensify** [comment] 2024-03-29 17:04
I tested and confirmed this issue is only on iOS: mWeb Safari. 

![2024-03-29_10-03-56](https://github.com/Expensify/App/assets/8107070/ca5f0863-5e11-4642-b0fe-df0250ea947b)

**Comment by alexpensify** [comment] 2024-03-29 17:05
Waiting for proposals here

**Comment by alexpensify** [comment] 2024-04-01 23:21
No update, we need proposals here.

**Comment by cleverjam** [comment] 2024-04-01 23:44
I have spent some time looking into this but can't reproduce this in dev server, this is making it harder to debug.

iOS: 17.2 

https://github.com/Expensify/App/assets/12721875/21969f92-c515-405f-a645-c629435bf0ed

**Comment by cleverjam** [comment] 2024-04-02 16:14
@paultsimura I have not been able to access local dev server from my physical device, it seems the dev server binds to 127.0.0.1 only? I may have missed the instructions to make this work (I am new here), but I followed this [README](https://github.com/Expensify/App/blob/main/README.md#ios-flow), would you mind sharing instructions to access local dev from physical device?

**Comment by ikevin127** [comment] 2024-04-02 17:09
# Proposal

### Please re-state the problem that we are trying to solve in this issue

The video preview keeps loading infinitely on iOS: mWeb.

### What is the root cause of that problem?

> [!note]
> This can only be reproduced on **real** iOS devices and it happens on all browser (Safari, Chrome, etc) since all iOS browsers use the WebKit engine.

The root cause comes from this code line:

https://github.com/Expensify/App/blob/35b4d1b5a91f222986d9a887ecd96ea1ede0f594/src/components/VideoPlayer/BaseVideoPlayer.js#L64-L65

The problem is that we're appending `#t=0.001` to the video blob URL in order to get a visible preview of the video before user interacts with it, instead of seeing nothing (transparent) until user plays the video.

Appending `#t=0.001` to the blob causes the following conosle log error:
`Failed to load resource: blob:https://...%23t=0.001`
`The operation couldn’t be completed. (WebKitBlobResource error 1.)`
this causes the infinite loading. Removing the time skip addition solves the console log error and the infinite loading.

This is most likely a WebKit browser engine limitation which does not allow us to skip the first milisecond of the video programatically, without user action like actually toggling play / pause of the video.

### What changes do you think we should make in order to solve the problem?

To fix the infinite loading issue and fulfil the **expected result** we have to do 2 things:
1. Remove the `#t=0.001` from `sourceURL` **only** if `isMobileSafari()` is true. We can do this [here](https://github.com/Expensify/App/blob/35b4d1b5a91f222986d9a887ecd96ea1ede0f594/src/components/VideoPlayer/utils.ts#L13-L21), by adding a `isMobileSafari` check there and skipping the addition - we're not messing with this logic on other platforms where the logic works as expected.
2. Within [this useEffect](https://github.com/Expensify/App/blob/35b4d1b5a91f222986d9a887ecd96ea1ede0f594/src/components/VideoPlayer/BaseVideoPlayer.js#L162-L169) perform a check such that if `isMobileSafari()` is true -> we use video's ref `setStatusAsync` (promise) to set `shouldPlay` to true then back to false as soon as the first `setStatusAsync` promise is fulfilled.

**We can code this in 2 different ways (as preferred):**
1. Change the `usePlaybackContext` -> [`playVideo`](https://github.com/Expensify/App/blob/35b4d1b5a91f222986d9a887ecd96ea1ede0f594/src/components/VideoPlayerContexts/PlaybackContext.tsx#L26-L34) function to return the `setStatusAsync` promise so we can then do:

```ts
        if (isMobileSafari()) {
            playVideo().then(() => pauseVideo());
        }
```

2. Calling `setStatusAsync` directly on the `currentVideoPlayerRef.current` like so:

```ts
        if (isMobileSafari()) {
            currentVideoPlayerRef.current.setStatusAsync({shouldPlay: true}).then(() => currentVideoPlayerRef.current.setStatusAsync({shouldPlay: false}));
        }
```

This emulates the `#t=0.001` behaviour by playing then pausing the video in very quick succession based on promise.

### Videos (before / after)

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/dbcf130c-f703-4e9d-8d81-975ed86c46fc"> | <video src="https://github.com/Expensify/App/assets/56457735/1ab4c9aa-34f6-4b8e-90b4-e876b602546b"> |

</details>

### What alternative solutions did you explore? (Optional)

Alternatively, we could only apply the first step (1) of the main solution:
1. Remove the `#t=0.001` from `sourceURL` **only** if `isMobileSafari()` is true. We do this so we're not messing with this logic on other platforms where the logic works as expected.

The downside with this is that it would only fix the infinite loading issue / console log error, leaving us with a transparent preview of the video until the user will interact with it (see video below).

<details>
<summary>Alternative solution result</summary>

https://github.com/Expensify/App/assets/56457735/678d9fc0-87a2-4913-8b4e-a79656343ff7

</details>

**Comment by ikevin127** [comment] 2024-04-02 17:23
> would you mind sharing instructions to access local dev from physical device?

@cleverjam Try [ngrok](https://www.sitepoint.com/use-ngrok-test-local-site/), once you instelled it and have the Expensify web app running locally, run the following command in a terminal: `ngrok http https://127.0.0.1:8082 --host-header="127.0.0.1:8082"`

This will create a tunnel to your web app running locally (given it's running on port 8082) and ngrok will give you a link of form: `https://5740-2a02-2f0c-5802-a600-fd16-b4f4-e331-cc4d.ngrok-free.app` which you can email yourself and navigate to it on your physical iOS device.

Once you do that you can debug / monitor your iOS device console logs from Safari (desktop) if the devices are connected via USB.

**Comment by cleverjam** [comment] 2024-04-02 17:39
thanks for sharing @ikevin127 - very helpful!

**Comment by ikevin127** [comment] 2024-04-03 10:15
## Updated [proposal](https://github.com/Expensify/App/issues/39078#issuecomment-2032602290)
- improved main solution by suggesting addition of `isIOSWebkitBrowser()` function in order to account for fixing the issue on all WebKit based browsers, not only Safari (`isMobileSafari()`)

**Comment by alexpensify** [comment] 2024-04-03 22:10
@paultsimura when you get a chance, can you review the recent proposals? Thanks!

**Comment by Skalakid** [comment] 2024-04-05 09:05
On the Huawei P40 Lite video doesn't get stuck on the full green screen

https://github.com/Expensify/App/assets/39538890/6fcf0c19-56fb-464e-8596-203fe522f51b

However, when you enter video preview you can notice that video is played and immediately paused by looking at play/pause icon. I think we can block it by using some kind of variable that locks icon button state change until the video is paused and the video preview is displayed. What do you think about it?

**Comment by ikevin127** [comment] 2024-04-05 11:08
> [!note]
> Just tested on a physical OnePlus 7T (Android 14) and I can confirm that the full green screen does not happen,
> (5/5 successful).

(the play/pause icon toggle can be noticed)
<details>
<summary>Android: Native (OnePlus 7T - Android 14)</summary>

https://github.com/Expensify/App/assets/56457735/8c083fb8-c366-4a8c-aaef-dc1b81e83c9f

</details>

> However, when you enter the video preview you can notice that the video is played and immediately paused by looking at the play/pause icon. I think we can block it by using some kind of variable that locks the icon button state change until the video is paused and the video preview is displayed. What do you think about it?

Sure, just pushed the changes to the [test branch](https://github.com/ikevin127/Expensify/tree/test/39078).

## Result
<details>
<summary>Android: Native (OnePlus 7T - Android 14)</summary>

https://github.com/Expensify/App/assets/56457735/e61cb97b-6804-400f-b56c-06b4f8ce6629

</details>

@Skalakid @paultsimura I'm looking forward to your feedback regarding this implementation so I can update my proposal to reflect the latest test branch changes, in case we decide to go with this solution 🙌

**Comment by ikevin127** [comment] 2024-04-05 11:41
## Updated [proposal](https://github.com/Expensify/App/issues/39078#issuecomment-2032602290)
Changed solution to reflect the latest discussion ([#39078 (comment)](https://github.com/Expensify/App/issues/39078#issuecomment-2036770752) and [#39078 (comment)](https://github.com/Expensify/App/issues/39078#issuecomment-2039279574)):
- use the solution in all platforms
- handle the play / pause controls toggle

**Comment by amyevans** [comment] 2024-04-05 15:08
Looks good, thanks! Assigning @ikevin127

**Comment by ikevin127** [comment] 2024-04-05 17:34
📯 PR https://github.com/Expensify/App/pull/39755 ready for review!

**Comment by alexpensify** [comment] 2024-04-05 22:26
Thanks @ikevin127 for the update.

**Comment by ikevin127** [comment] 2024-04-06 08:55
👋 Hi, while doing some more testing of the proposed solution PR I came to the conclusion that oddly, even though initially I was able to take videos and it worked - later on I noticed that it still doesn't cover WebKit based browsers (MacOS / iOS - Safari, Chrome, Firefox, Opera, etc) due to the browser not allowing to programatically call `.play()` on videos before user interaction.

Therefore my play / pause solution does not work on these specific browsers / platforms, throwing the following console error:

> [!caution]
> NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

which leaves the user with a transparent preview until they interact with the video controls (play / pause). **Note:** using `isMuted={false}` prop still does not work.

I stayed late and came up with another fix which does cover all platforms / browsers. The new solution entails creating a library (@libs/) called `setVideoPoster` which does the following:
1. **(index.native.ts)** Keep the original PR's `#t=` (time fragment) implementation for native platforms only since it works as expected. We do this using a helper function called `prepareSourceURL`.

2. **(index.ts)** For all web based platforms / browsers (including Desktop) we do the following:
- remove the original PR's `#t=` (time fragment) implementation since its problematic on WebKit based browsers (infinite loading issue). We do this using a helper function called `prepareSourceURL` returning the `sourceURL` without the `addSkipTimeTagToURL` (`#t=` [time fragment]) addition like we do on native
- using `expo-av`'s Video [`usePoster`](https://docs.expo.dev/versions/latest/sdk/video/#useposter) and [`posterSource`](https://docs.expo.dev/versions/latest/sdk/video/#postersource) props to actually set the preview (poster) when the video is loaded
- created a new function named `extractVideoPoster` which uses html video + canvas to capture a frame from the given video blob url, at a specific video duration (in seconds)

I thoroughly tested this new implementation and it works reliably 100% of the time , covering all platforms / browsers. Now I want to know if it's cool to push this to the PR branch and update the proposal again once the @paultsimura confirmed that this solution is working reliably.

**Comment by ikevin127** [comment] 2024-04-06 09:02
👋 Hi, while doing some more testing of the proposed solution PR I came to the conclusion that oddly, even though initially I was able to take videos and it worked - later on I noticed that it still doesn't cover WebKit based browsers (MacOS / iOS - Safari, Chrome, Firefox, Opera, etc) due to the browser not allowing to programatically call `.play()` on videos before user interaction.

Therefore my play / pause solution does not work on these specific browsers / platforms, throwing the following console error:

> [!caution]
> NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

which leaves the user with a transparent preview until they interact with the video controls (play / pause). **Note:** using `isMuted={false}` prop still does not work.

I stayed late and came up with another fix which does cover all platforms / browsers. The new solution entails creating a library (@libs/) called `setVideoPoster` which does the following:
1. **(index.native.ts)** Keep the original PR's `#t=` (time fragment) implementation for native platforms only since it works as expected. We do this using a helper function called `prepareSourceURL`.

I decided to keep the original PR's solution on native since on native we cannot use html elements (video, canvas) to extract a frame from the video - this would require installing a new package and we most likely don't want that.

2. **(index.ts)** For all web based platforms / browsers (including Desktop) we do the following:
- remove the original PR's `#t=` (time fragment) implementation since its problematic on WebKit based browsers (infinite loading issue). We do this using a helper function called `prepareSourceURL` returning the `sourceURL` without the `addSkipTimeTagToURL` (`#t=` [time fragment]) addition like we do on native
- using `expo-av`'s Video [`usePoster`](https://docs.expo.dev/versions/latest/sdk/video/#useposter) and [`posterSource`](https://docs.expo.dev/versions/latest/sdk/video/#postersource) props to actually set the preview (poster) when the video is loaded
- created a new function named `extractVideoPoster` which uses html video + canvas to capture a frame from the given video blob url, at a specific video duration (in seconds) by loading video's metadata (we avoid calling `.play()`)

I thoroughly tested this new implementation and it works reliably 100% of the time , covering all platforms / browsers. Now I want to know if it's cool to push this to the PR branch and update the proposal again once the @paultsimura confirmed that this solution is working reliably.

**Comment by ikevin127** [comment] 2024-04-06 09:34
@paultsimura Sure, have at it 🙌

> This is quite weird because I did test your test branch yesterday, and it worked on both Safari & Chrome on a physical iPhone.

Indeed, same thing for me! First I thought it might be from the recent TS migration of `BaseVideoPlayer` but it's not because I switched back to the test branch, performed a clean install (`npm ci`) and it still did not work anymore on physical iPhone.

1. I am using `ngrok` so it's a secure connection (https) - all good here!
2. Then I noticed the **NotAllowedError** in the console while the video preview remained transparent -> the error appearing as a result of `getStatusAsync` method being called as part of calling `playVideo()` - this can be noticed if we add the `.catch` block to the promise -> returning the **NotAllowedError**.
3. This is how I confirmed that it's the WebKit based browsers policy to not allow calling `.play()` programatically, without user interacting with video controls first by pressing a button / click. Once user interacts, `getStatusAsync / setStatusAsync` don't throw the **NotAllowedError** error anymore.

**Comment by ikevin127** [comment] 2024-04-08 13:55
@paultsimura Sure, here's the test branch: [#test/39078-2](https://github.com/ikevin127/Expensify/tree/test/39078-2) and [diff](https://github.com/Expensify/App/compare/main...ikevin127:Expensify:test/39078-2).

These are the results of this solution:

<details>
<summary>Android: Native</summary>


https://github.com/Expensify/App/assets/56457735/50dac28b-1dd3-4099-abbe-0b1234bc2872



</details>

<details>
<summary>Android: mWeb Chrome</summary>


https://github.com/Expensify/App/assets/56457735/a951b14d-ee9c-4613-a798-1936b48ed6c5



</details>

<details>
<summary>iOS: Native</summary>


https://github.com/Expensify/App/assets/56457735/44e1b7a2-4edc-471f-bf05-7b99943359c7



</details>

<details>
<summary>iOS: mWeb Safari</summary>


https://github.com/Expensify/App/assets/56457735/1ed19b65-4d83-41f6-9220-f7313e702cd3



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>


https://github.com/Expensify/App/assets/56457735/0441841c-56b8-4be1-af47-f475713f9949



</details>

<details>
<summary>MacOS: Desktop</summary>


https://github.com/Expensify/App/assets/56457735/b85d9c65-bd68-445a-933b-3850fae79339



</details>

**Comment by ikevin127** [comment] 2024-04-08 15:36
@paultsimura That's fine by me!

> looks badly hacky, even though it works

Can you please elaborate which part looks badly hacky to you and why / how so ?

## **Summary to consider for other potential contributors:**
- using `#t=` (time fragment) causes:
`Failed to load resource: blob:https://...%23t=0.001`
`The operation couldn’t be completed. (WebKitBlobResource error 1.)`
on WebKit based browsers (physical iPhone device)

> [!note]
> The `#t=` (time fragment) works as expected on all platforms / devices - **except** on mWeb on physical iPhone devices (Safari, Chrome, etc).

- calling play / pause programatically causes the **NotAllowedError** on some browsers (mostly WebKit based - which require user action / click on a button to initiate play), hence unreliable

**Comment by ikevin127** [comment] 2024-04-08 21:47
> Can you please elaborate which part looks badly hacky to you and why / how so ?

@paultsimura I was asking because I would like to work on the 2nd solution and bring it to a point where it's less badly hacky. I'd do this regardless of whether or not a new / better proposal comes in and will potentially be selected.

Also if 1st solution works as expected and I'm the only one for which it doesn't work anymore - I guess we can move on with the open PR ? I'm curious if it works well for anyone else!

**Comment by ikevin127** [comment] 2024-04-10 10:50
> if this is true then my 2 cents would be to show a thumbnail with play button instead of auto start playing the video,mweb Safari has these kind of issues

@ishpaul777 Yes, this is what my [2nd proposed solution](https://github.com/Expensify/App/issues/39078#issuecomment-2041023465) does: it uses canvas on web to capture a frame from the video blob and uses that frame as thumbnail -> by doing this we don't call play / pause programatically on web where browsers using WebKit engine like Safari / Chrome on iOS: mWeb don't allow it.

https://github.com/Expensify/App/issues/39078#issuecomment-2042826793 here you have the test branch and diff of the 2nd proposed solution.
If you have any questions regarding the 2nd solution implementation or need more context on the issue, feel free to ask!

**Comment by alexpensify** [comment] 2024-04-16 00:37
@ishpaul777 - are you able to review this one? Keep us posted if you are still dealing with the high-priority GH. Thanks!

**Comment by alexpensify** [comment] 2024-04-17 21:31
## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by amyevans** [comment] 2024-04-23 14:51
@ishpaul777 bump on the above, how's your bandwidth looking?

**Comment by amyevans** [comment] 2024-04-23 14:57
No problem, thank you!

**Comment by ikevin127** [comment] 2024-04-24 16:28
@ishpaul777 It's true that with the first solution (the one you tested), there's the problem with the black screen preview, therefore it's unreliable.

I looked into it but with the method I'm using there's nothing that can be done to make it work 100% reliably since its related to WebKit based browsers not allowing play programatically without user action (browser limitation).

##

However in the second solution we're not doing that but instead using a canvas to snapshoot a preview on web, and maintaining the currently used `#t=` time fragment implementation on native platforms, this way we reliably have things work 100% of the time on all platforms / browser types.

Here's the explanation for the 2nd solution:  https://github.com/Expensify/App/issues/39078#issuecomment-2041023465 and the comment where I reference the test branch and diff: https://github.com/Expensify/App/issues/39078#issuecomment-2042826793.

I don't consider the 2nd solution hacky as for native platform we're not changing anything compared to how things are currently. We're only changing things on web with the canvas method and for this we're using platform specific files (as required by contributor guideline) to implement the fix.

**Comment by ikevin127** [comment] 2024-04-24 18:15
Oh, my bad - I will be looking into this based on https://github.com/Expensify/App/issues/39078#issuecomment-2073010499 to see what's causing the issue and will get back today.

**Comment by ikevin127** [comment] 2024-04-26 15:07
@ishpaul777 Indeed, after extensive testing I can confirm too that none of my proposed solutions fixes the issue, specifically only on physical iOS: mWeb devices where all the browsers use WebKit engine by design.

This must be due to the browser limitation / privacy concerns - where a video cannot be played / seeked without actual user interaction (button click or press), hence not allowing us to extract a frame to use for preview using the above suggested methods.

##

I have a lead on how to possibly tackle this issue, I just have to test it first then I'll write-up a formal proposal, again.

**Comment by ikevin127** [comment] 2024-04-27 02:09
> I have a lead on how to possibly tackle this issue

Yeah...it's not possible (IMO) to have this issue fixed on iOS: mWeb on real physical devices (all WebKit based browsers) from the FE side. Why do I say this ?

The lead mentioned above was that I added an external `https://somedomain.com/video.mp4` form video directly to the `BaseVideoPlayer` sourceURL to which the `#t=0.001` (time fragment) was appended and this worked when the attachment modal was opened with the hardcoded external video.

The issue is that we cannot pass local files to the video player dirrectly for security reasons, unless we're transforming them in a URL blob via `URL.createObjectURL` with [this](https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/components/AttachmentModal.tsx#L337-L351) logic. Problem is that on mWeb WebKit based browsers, appending `#t=0.001` (time fragment) to a blob does not work, throwing the `(WebKitBlobResource error 1.)` error -> resulting in infinite loading spinner.

Given this, we most likely won't want to send local files to BE simply to generate a preview so this leaves us with the following possible solution that will do the following only on **mWeb WebKit based browsers**:
- remove the `#t=0.001` (time fragment) addition in order to prevent the error and have the user blocked on the infinite loading spinner

This still won't show a video preview since it's literally impossible (IMO) since on mWeb WebKit based browsers we're not allowed to set `#t=0.001` (time fragment) and we're also not allowed to play the video programatically in order to extract a frame -> leaving us without a video preview, but at least the user is not blocked from attaching the video, playing it and uploading it.

This is how it will look on mWeb WebKit based browsers:

<details>
<summary>iOS: mWeb Safari</summary>


https://github.com/Expensify/App/assets/56457735/5cd65e17-f11a-412b-9bed-e4710231f4c1


</details>

Please let me know if this is an acceptable solution in your opinion for this specific edge case in order to at least unblock the user. If so, I'd update my proposal to remove the `#t=0.001` (time fragment) specifically for mWeb WebKit based browsers.

@alexpensify @ishpaul777

**Comment by ikevin127** [comment] 2024-05-01 22:22
> Cool! lets move this forward then, @ikevin127 Can you please update your proposal

## Updated [proposal](https://github.com/Expensify/App/issues/39078#issuecomment-2032602290)
- updated solution according latest findings from [#39078 (comment)](https://github.com/Expensify/App/issues/39078#issuecomment-2080320441) and CME's decision from [#39078 (comment)](https://github.com/Expensify/App/issues/39078#issuecomment-2085657659)

> [!note]
> With the updated solution -> the behaviour will now align on both iOS: mWeb physical devices and Simulator as in both will have transparent preview even though the `#t=1` (time fragment) bug does not happen on iOS: mWeb Simulator devices.

cc @ishpaul777

**Comment by amyevans** [comment] 2024-05-02 20:13
Thanks for updating the proposal! Let us know once the PR is updated as well

**Comment by ikevin127** [comment] 2024-05-02 20:26
> Thanks for updating the proposal! Let us know once the PR is updated as well

PR https://github.com/Expensify/App/pull/39755 was updated according to [proposal](https://github.com/Expensify/App/issues/39078#issuecomment-2032602290) and is ready for review! 🎉 

> [!note]
> Sorry, I thought I'm supposed to wait for @ishpaul777 's approval of the updated proposal before moving on to updating the PR.

cc @amyevans

**Comment by alexpensify** [comment] 2024-05-07 18:45
Thank you for the update @ishpaul777!

**Comment by alexpensify** [comment] 2024-05-14 22:23
Ok, Upwork is up to date for tomorrow. I'm adding the note to remember why there are two C+ here: https://github.com/Expensify/App/issues/39078#issuecomment-2047155509

Now, automation should kick in with the summaries tomorrow.

**Comment by ikevin127** [comment] 2024-05-15 17:14
@alexpensify Is anything else needed from our side in order for the payment to be issued today ?

**Comment by alexpensify** [comment] 2024-05-15 22:19
Payouts due: 2024-05-15

- [ ] Contributor: $500 @ikevin127 
- [ ] Contributor+: $500 @ishpaul777 

Upwork job is [here](https://www.upwork.com/jobs/~015c647e39b68ccf23).

We are treating this one as a `High` issue, which is why the payment is $500 and not $250.

**Comment by alexpensify** [comment] 2024-05-15 22:28
Closing - everyone has been paid via Upwork and I closed the job there.

**Closed by alexpensify** 2024-05-15 22:28 UTC
Labels: External, Daily, Awaiting Payment, Bug
