### ISSUE TITLE
[HOLD for payment 2023-07-03] [$1000] Chat - Focus is lost if message deletion confirmation after editing is made from keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20954] opened 2023-06-16 23:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start ND on Desktop App or Chrome and login with any account
2. Open any chat
3. Send any message
4. Press Arrow Up key on keyboard
5. Select All - Ctrl / Cmd + A
6. Press 'Delete' key
7. Press 'Enter' key
8. Confirm message deletion with 'Enter' key

## Expected Result:
Message deleted. Focus on composer

## Actual Result:
Message deleted. Focus lost

## Workaround:
 Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f508a5f1-991a-46b0-b07a-671c009feb6d

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c31893755e56c1da</li>
        <li>Upwork Job ID: 1670954686446301184</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-06-20 00:39
Issue looks good!

**Comment by kaushiktd** [comment] 2023-06-21 08:43
### Please re-state the problem that we are trying to solve in this issue.
Chat - Focus is lost if message deletion confirmation after editing is made from the keyboard

### What is the root cause of that problem?
When the Confirmation modal is shown then and if the user press enter keys then it will trigger both the callback function for the confirmation button and the onBackdropPress callback.
From the onBackdropPress callback, it will call the function modal close and it will try to refocus on the `ReportActionItemMessageEdit` composer from the last parameter of the below function from
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.js#L217

`ReportActionContextMenu.showDeleteModal(props.reportID, props.action, false, deleteDraft, () => InteractionManager.runAfterInteractions(() => textInputRef.current.focus())); 
`
if only the confirmation button is triggered it will call `deleteDraft` and try to refocus on `ReportActionComposeFocusManager`

### What changes do you think we should make in order to solve the problem?
We need to prevent multiple callbacks when hit enter key. So we need to check the condition on BaseModal `onBackdropPress` callback on the below file.
https://github.com/Expensify/App/blob/main/src/components/Modal/BaseModal.js#L103
```
if (e && e.type === 'keydown' && e.key === 'Enter') { 
     return; 
} 
```

When pressing enter key, it shows the opposite key event in the log. react-native-web has changed keydown event to keyup event
https://github.com/necolas/react-native-web/blob/c350d82427a0f7651ae4421bf373cde72f27bb0f/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L344-L346
So I would suggest, don't change the e.type event in the existing condition because maybe if again anything changes are done by react-native-web, it will cause the same issue. 
So it would be best to check if the keyboard key event appears if yes terminate the process and don't trigger 
```
this.props.onClose(); 
onBackdropPress callback.
```

change the below line from
```
if (e && e.type === 'keydown' && e.key === 'Enter') { 
     return; 
} 
```

 to 

` if (e) return;`

**Comment by kaushiktd** [comment] 2023-06-22 04:17
@francoisl @thesahindia I am trying to understand for my personal technical knowledge, why are we favoring the solution of changing e.type event when there are high chances that this issue will reappear again. Are you sure you looked at the following? I am willing to learn based on what factor you guys are making your decision.

> So I would suggest, don't change the e.type event in the existing condition because maybe if again anything changes are done by react-native-web, it will cause the same issue. So it would be best to check if the keyboard key event appears if yes terminate the process and don't trigger
> 
> ```
> this.props.onClose(); 
> onBackdropPress callback.
> ```
> 
> change the below line from
> 
> ```
> if (e && e.type === 'keydown' && e.key === 'Enter') { 
>      return; 
> } 
> ```
> 
> to
> 
> ` if (e) return;`

**Comment by kaushiktd** [comment] 2023-06-22 11:12
> @kaushiktd In my main proposal, I suggested to remove condition of `e.type`. You can review it again and raise your concerns if you have any. Thanks

Exactly! What if react native web changed key event again? This issue will appear again. Please explain if I am incorrect here.

**Comment by kaushiktd** [comment] 2023-06-23 04:34
@hoangzinh The concern I have raised is actually self explanatory but let me try to explain it in even simpler terms.

You have given a solution solely based on the react-native-web review from below URL:
https://github.com/necolas/react-native-web/blob/c350d82427a0f7651ae4421bf373cde72f27bb0f/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L344-L346

It has `onKeyDown` event but return Keyup, so you have to change e.type === 'keyup'

So here my question is, what happens if react-native-web changes its event type again on `onKeyDown` to keydown?
In that case, this issue won't get solved because the problem is based on react-native-web review. This issue will come again.

@francoisl @slafortune @thesahindia Do you guys understand my point here?

**Comment by slafortune** [comment] 2023-07-05 20:33
Offers sent @thesahindia @hoangzinh 

@thesahindia can you complete the checklist?

**Comment by kaushiktd** [comment] 2023-07-06 02:33
I am glad you came to a conclusion but I am not sure why my question is ignored here. Why are we favoring the solution that is most likely going to be the cause of this issue again? I have no issue with who you hire but that question is bugging me and I would really appreciate the clarification on that. @francoisl @thesahindia 

> @hoangzinh The concern I have raised is actually self explanatory but let me try to explain it in even simpler terms.
> 
> You have given a solution solely based on the react-native-web review from below URL: https://github.com/necolas/react-native-web/blob/c350d82427a0f7651ae4421bf373cde72f27bb0f/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L344-L346
> 
> It has `onKeyDown` event but return Keyup, so you have to change e.type === 'keyup'
> 
> So here my question is, what happens if react-native-web changes its event type again on `onKeyDown` to keydown? In that case, this issue won't get solved because the problem is based on react-native-web review. This issue will come again.
> 
> @francoisl @slafortune @thesahindia Do you guys understand my point here?

**Comment by kaushiktd** [comment] 2023-07-06 14:42
> Beside that, I haven't tested yet. But with your proposal [#20954 (comment)](https://github.com/Expensify/App/issues/20954#issuecomment-1600436189). Will it cause regression with mouse click on the backdrop won't close the modal?

I've tested. As per my proposal #20954 (comment) it will work with the mouse click event as well as work with both keyboard and It will close the modal with it's backdrop. The focus to message composer again.

https://drive.google.com/file/d/1UQ2dmwB6u-wuWp2j8-n7mvLL6YaQ12z8/view?usp=sharing

**Comment by kaushiktd** [comment] 2023-07-06 15:34
I appreciate your clarification on this. This was actually bugging me. Since the original issue was related to keyboard only, I tested it only with the Keyboard. Thank you, brother!

**Comment by slafortune** [comment] 2023-07-06 17:57
Just waiting on you @thesahindia to complete the checklist and then I can issue payment and close this 👍

**Comment by slafortune** [comment] 2023-07-10 13:09
@thesahindia will you be able to get to this?

**Comment by slafortune** [comment] 2023-07-11 21:39
https://github.com/Expensify/Expensify/issues/299208

**Comment by JmillsExpensify** [comment] 2023-09-22 08:43
@slafortune Can you please add a payment summary so that I can issue payment via NewDot?

**Comment by francoisl** [comment] 2023-09-26 04:56
cc @slafortune on the payment summary so that Jason can issue payments and close the issue

**Comment by JmillsExpensify** [comment] 2023-09-28 01:20
Awaiting payment summary.

**Comment by JmillsExpensify** [comment] 2023-10-01 02:15
Still awaiting payment summary.

**Comment by JmillsExpensify** [comment] 2023-10-05 21:32
@muttmuure Can I get a payment summary so I can issue payment?

**Comment by JmillsExpensify** [comment] 2023-10-05 21:33
(It can't be me, that's why I re-assigned).

**Comment by trjExpensify** [comment] 2023-10-05 21:40
Wagwan! Looking..

**Comment by trjExpensify** [comment] 2023-10-05 21:43
Payments as follows: 

- $1,500 to @thesahindia for C+ review & #urgency bonus 
- $1,500 to @hoangzinh for the bug fix & #urgency bonus 
- Applause reported the issue, no bug reporter to pay. 

Notes: 

- Urgency bonus applies as per [here](https://github.com/Expensify/App/issues/20954#issuecomment-1605042115). 
- Bounty levels are pre-Aug 30th at $1,000 + 50% bonus.

**Comment by JmillsExpensify** [comment] 2023-10-05 21:43
$1,500 payment approved for @thesahindia based on BZ summary.

**Comment by trjExpensify** [comment] 2023-10-05 21:45
@hoangzinh looking at the upwork job, it seems like you were paid for this job. So I'm going to close the issue out. Give me a shout if you don't think it's correct!

**Closed by trjExpensify** 2023-10-05 21:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
