### ISSUE TITLE
[HOLD for payment 2023-09-29] [$1000] Web - Selecting a user in the new group member search, a message 'No results found' is displayed.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26072] opened 2023-08-28 11:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Click FAB button
2. Click new group
3. Search any email and select, Observe that the message "No results found" appears

## Expected Result:
Message "No results found" does not appears after select user

## Actual Result:
Message "No results found" appears after select user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e6c77e6e-07df-47cf-acc3-70f715b3c2b4

https://github.com/Expensify/App/assets/93399543/3156de61-f21e-4995-a58b-727a8a01126e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692453168520689
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01868e8617d1a2f9e1</li>
        <li>Upwork Job ID: 1696632090628845568</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26742716</li>
<li>namhihi237 | Contributor | 26742717</li>
<li>namhihi237 | Reporter | 26742719</li>
</ul></li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-08-29 21:12
I'm able to reproduce the issue.

<img width="521" alt="Screenshot 2023-08-29 at 14 10 53" src="https://github.com/Expensify/App/assets/8292562/333c8f4a-c346-4b9a-9b26-07750154e061">

**Comment by s77rt** [comment] 2023-08-29 22:19
@namhihi237 Thanks for the proposal. Your RCA is correct and the solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/26072#issuecomment-1695563485)

**Comment by s77rt** [comment] 2023-09-01 19:46
Not overdue. @neil-marcellini ^

**Comment by s77rt** [comment] 2023-09-04 11:29
@neil-marcellini ^

**Comment by tjferriss** [comment] 2023-09-05 19:11
@s77rt what exactly do you need from @neil-marcellini?

**Comment by s77rt** [comment] 2023-09-05 19:19
@tjferriss To review the approved proposal and assign the contributor if agreed.

**Comment by s77rt** [comment] 2023-09-11 11:02
@neil-marcellini https://github.com/Expensify/App/issues/26072#issuecomment-1698220130

**Comment by s77rt** [comment] 2023-09-11 12:39
@bfitzexpensify No, I don't think it will address it. This issue is only about the header message not the options.

**Comment by tjferriss** [comment] 2023-09-12 22:04
I'm still able to produce this one.

**Comment by s77rt** [comment] 2023-09-16 00:38
Not overdue. Seems that @neil-marcellini is OOO. Asked in [Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1694824698960589) for another engineer.

**Comment by s77rt** [comment] 2023-09-18 12:53
Not overdue. Still need an engineer review for this

**Comment by s77rt** [comment] 2023-09-18 17:10
@parasharrajat That issue looks pretty much the same as this one. We can close that one and add that case here to be handled.

The expected behaviour is not to show the not found message if there is a valid result (and it's selected).

**Comment by neil-marcellini** [comment] 2023-09-18 20:08
Sorry for the delay, I'll review today.

**Comment by neil-marcellini** [comment] 2023-09-18 23:47
> @namhihi237 Thanks for the proposal. Your RCA is correct and the solution looks good to me.
> 
> 🎀 👀 🎀 C+ reviewed [Link to proposal](https://github.com/Expensify/App/issues/26072#issuecomment-1695563485)

I agree, hired!

**Comment by neil-marcellini** [comment] 2023-09-18 23:49
@parasharrajat I think https://github.com/Expensify/App/issues/27658 should be treated as a duplicate since it's so similar, and we should fix that issue with @namhihi237's PR too.

**Comment by namhihi237** [comment] 2023-09-19 02:10
Sure @neil-marcellini @s77rt I will include it in the PR

**Comment by c3024** [comment] 2023-09-19 06:27
@neil-marcellini Could you consider giving bug report bounty for the issue #27658?

**Comment by s77rt** [comment] 2023-09-23 22:58
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/23982
- The offending PR has been commented on: https://github.com/Expensify/App/pull/23982#discussion_r1309406901
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by tjferriss** [comment] 2023-09-25 07:34
Payment Summary:

- @s77rt Reviewer $1500
- @namhihi237 Contributor $1500
- @namhihi237 Reporter $250

Both team members are eligible for the 50% speed bonus

**Comment by neil-marcellini** [comment] 2023-10-02 17:24
Clearing overdue

**Comment by tjferriss** [comment] 2023-10-03 01:07
All payments have been sent via Upworks. Closing!

**Closed by tjferriss** 2023-10-03 01:07 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by s77rt** [comment] 2023-10-05 20:06
@parasharrajat Oh right! Thanks for bringing this up!

@tjferriss The paymend here should be $500. I have refunded the $1000.
