### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500]  Web - Chat - There is a cancelled request where isDarkMode=true is present

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34669] opened 2024-01-17 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26.1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34395
## Action Performed:
1. Open the network tab in Chrome console
2. Send https://staging.new.expensify.com/statements/202312
in any 1:1 chat
3. Turn on light mode
4. Open the link

## Expected Result:
There shouldn't be a cancelled request

## Actual Result:
There is a cancelled request where isDarkMode=true is present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fb064987-6c2a-4411-a919-181f9af25711

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01656e05b8d4b00139</li>
        <li>Upwork Job ID: 1747725844186800128</li>
        <li>Last Price Increase: 2024-01-17</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28117763</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by tgolen** [comment] 2024-01-17 21:00
Since this has no user impact, I'm removing the deploy blocker label. Please correct me if I'm wrong about the impact level.

**Comment by aswin-s** [comment] 2024-01-17 23:19
## Proposal
	
### Please re-state the problem that we are trying to solve in this issue.
	
There is a cancelled request in network panel when WalletStatementPage is loaded

### What is the root cause of that problem?
	
On the WalletStatementPage, the statementPageUrl for WalletStatementModal is constructed as follows:

https://github.com/Expensify/App/blob/4b7b8f2480866200c64a8b614a1f485c0112aa11/src/pages/wallet/WalletStatementPage.js#L94

Note that the url utilises the `themePreference` value to determine the user's current theme.

The themePreference is derived from the `useThemePreference()` hook, which asynchronously reads the theme preference from Onyx via an effect.

https://github.com/Expensify/App/blob/4b7b8f2480866200c64a8b614a1f485c0112aa11/src/hooks/useThemePreference.ts#L12-L21

Initially, themePreference is set to CONST.THEME.FALLBACK and later updated to the current theme by the effect.

https://github.com/Expensify/App/blob/4b7b8f2480866200c64a8b614a1f485c0112aa11/src/hooks/useThemePreference.ts#L8

When the user is on light theme, WalletStatementPage first receives the themePreference value as `CONST.THEME.FALLBACK`, which is `dark`. It is then updated to `light` once the useEffect runs. Consequently, the url variable changes, causing the WalletStatementModal component to re-render. As the WalletStatementModal triggers a network request upon rendering and then unmounts immediately, the request gets canceled. This is why a canceled network request is observed.

### What changes do you think we should make in order to solve the problem?

The dependency on the useThemePreference hook is the fundamental issue. We should instead utilize the useTheme hook to directly read the current color scheme. Since the ThemeProvider has already loaded the theme preference, the `theme.colorScheme` value will remain constant when the WalletStatementPage renders, thereby preventing the canceled request.

```tsx

function WalletStatementPage(props) {
    const theme = useTheme();
    
    // use theme.colorScheme to construct the url
    const url = `${CONFIG.EXPENSIFY.EXPENSIFY_URL}statement.php?period=${yearMonth}${theme.colorScheme === CONST.THEME.DARK ? '&isDarkMode=true' : ''}`;

```

### What changes do you think we should make in order to solve the problem?
	
An alternative would be to not rely on the colorScheme field in the theme. Instead, we could introduce a specific currentTheme field in the ThemeContext to represent the active theme.

**Comment by kaushiktd** [comment] 2024-01-18 09:00
### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - There is a cancelled request where isDarkMode=true is present

### What is the root cause of that problem?
The dependency on the `useThemePreference` hook is identified as the fundamental issue. The hook relies on asynchronous operations, leading to initial renders with an undesired theme preference value.

### What changes do you think we should make in order to solve the problem?  
Optimize the `useThemePreference` hook using `useMemo` to prevent unnecessary re-renders. This change ensures that the theme preference is correctly calculated and avoids triggering network requests on each render.

  ```
const themePreference = useMemo(() => {
    const theme = preferredThemeFromStorage ?? CONST.THEME.DEFAULT;

    // If the user chooses to use the device theme settings, we need to set the theme preference to the system theme
    if (theme === CONST.THEME.SYSTEM) {
      return systemTheme ?? CONST.THEME.FALLBACK;
    } else {
      return theme;
    }
  }, [preferredThemeFromStorage, systemTheme]);

  return themePreference;
} 
```

### Video:-
https://drive.google.com/file/d/15I1YNuGJ6ChQKgj1bh_2yMg-f7VZ0UFy/view?usp=sharing

**Comment by tgolen** [comment] 2024-01-22 18:19
@c3024 Do you need some help giving these initial proposals a look or can you get to this soon?

**Comment by c3024** [comment] 2024-01-22 18:55
I'm on it. Will complete today.

**Comment by c3024** [comment] 2024-01-23 02:53
Thank you for your proposals.

I think the correct way to fix the useThemePreference hook. I don't see the need to have the themePreference as a state variable and set it with useEffect afterwards in the useThemePreference hook.

So, [proposal here](https://github.com/Expensify/App/issues/34669#issuecomment-1898060933) by @kaushiktd looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by tgolen** [comment] 2024-01-23 16:05
FYI @muttmuure ^^^

**Comment by kaushiktd** [comment] 2024-01-23 16:25
@tgolen @muttmuure Thank you guys! Will let you know when PR is ready.

**Comment by kaushiktd** [comment] 2024-01-31 04:24
@tgolen @c3024 will you send me invitation to apply on job OR it will be directly paid on Upwork?

**Comment by c3024** [comment] 2024-02-04 16:47
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #21667 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21667/files#r1477367303
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion has been started. This is a trivial bug and this is unlikely to be identified earlier
* [x]  [@c3024] Determine if we should create a regression test for this bug. No, this is not something related to user flow and also not a significant bug.
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by muttmuure** [comment] 2024-02-08 12:40
Handling

**Comment by muttmuure** [comment] 2024-02-09 15:31
Automation seems to have hired the wrong person for reviewer and nobody for contributor

**Comment by muttmuure** [comment] 2024-02-09 15:36
@kaushiktd has been paid, regardless

**Comment by kaushiktd** [comment] 2024-02-09 15:38
Amm, I do not receive any payment on Upwork! Where did you pay me @muttmuure ?

**Comment by muttmuure** [comment] 2024-02-09 15:42
argh it was a different profile

**Comment by c3024** [comment] 2024-02-09 15:48
I was paid correctly. I was the reviewer. I am being asked for a refund. 🤔 @muttmuure

**Comment by muttmuure** [comment] 2024-02-09 15:49
Ah OK, so it worked correctly then

**Comment by muttmuure** [comment] 2024-02-09 15:50
Let me cancel that refund request

**Comment by muttmuure** [comment] 2024-02-09 15:53
OK @kaushiktd should have an offer on Upwork

**Comment by kaushiktd** [comment] 2024-02-09 15:55
Thanks, @muttmuure 

Offer is accepted.

**Comment by muttmuure** [comment] 2024-02-09 15:56
contract extended

**Comment by muttmuure** [comment] 2024-02-09 15:57
@c3024 maybe you just decline the refund request

**Comment by c3024** [comment] 2024-02-09 15:58
I don't see a decline option. Maybe I will just ignore it?

**Comment by muttmuure** [comment] 2024-02-09 15:59
Sounds fine then

**Comment by kaushiktd** [comment] 2024-02-09 16:00
> contract extended

I am not seeing any milestone paid in my account.

**Comment by kaushiktd** [comment] 2024-02-09 16:01
It shows me this error when I tried to accept offer. 
<img width="477" alt="Screenshot 2024-02-09 at 9 31 10 PM" src="https://github.com/Expensify/App/assets/43398804/56dc53c8-18a4-4310-b788-3a87bb8a4845">

**Comment by kaushiktd** [comment] 2024-02-09 16:17
@muttmuure Can you please try withdrawing and creating new offer?

**Comment by kaushiktd** [comment] 2024-02-12 13:01
@muttmuure New offer is accepted and payment milestone requested

**Comment by muttmuure** [comment] 2024-02-13 15:15
All paid

**Closed by muttmuure** 2024-02-13 15:15 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
