### ISSUE TITLE
[BONUS PAYMENT] [$1000] Not able to invite an email when it's a substring of the selected email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21783] opened 2023-06-28 11:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings => Workspaces => Select a Workspace => Members => Invite new members
2. Search an email [`abcde@gmail.com](mailto:%60abcde@gmail.com)` and select it
3. Then search another email [`bcde@gmail.com](mailto:%60bcde@gmail.com)` which is a substring of the selected email

## Expected Result:
We should be able to search the second email [`bcde@gmail.com](mailto:%60bcde@gmail.com)` and select it after selecting the first email

## Actual Result:
We can't search for the second email [`bcde@gmail.com](mailto:%60bcde@gmail.com)` after selecting the first email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/67b9411f-593b-4da7-a5b3-7e5da9627133

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eh2077
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687699081649209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c7b7da0a7c6f9b3</li>
        <li>Upwork Job ID: 1674592628144259072</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-28 11:09
## Proposal
From @eh2077

### Please re-state the problem that we are trying to solve in this issue.

Not able to invite an email when it's a substring of the selected email.

### What is the root cause of that problem?

The root cause of this issue is that we concat logins of selected options to a string `filterText` and check by `!filterText.includes(login)` if a `login` is unselected, which is wrong, see below snippet

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/workspace/WorkspaceInvitePage.js#L153-L155

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can save logins of selected options to an array `selectedLogins` and use method `!_.contains(selectedLogins, login)` to check if a login is unselected. 

To achieve it, we can change 

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/workspace/WorkspaceInvitePage.js#L153-L155

to

```js
const selectedLogins = _.map(this.state.selectedOptions, ({login}) => login);
const personalDetailsWithoutSelected = _.filter(this.state.personalDetails, ({login}) => !_.contains(selectedLogins, login));
const hasUnselectedUserToInvite = this.state.userToInvite && !_.contains(selectedLogins, this.state.userToInvite.login);
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by jliexpensify** [comment] 2023-06-28 22:02
I feel like the steps are not clear - asking here: https://expensify.slack.com/archives/C049HHMV9SM/p1687989728056769?thread_ts=1687699081.649209&cid=C049HHMV9SM

**Comment by jliexpensify** [comment] 2023-06-30 01:35
Cool, questions resolved and I can repro!

**Comment by abdulrahuman5196** [comment] 2023-07-02 15:36
The proposal from @eh2077  here https://github.com/Expensify/App/issues/21783#issuecomment-1611209494 looks good and works well. The root cause is correct and it is very weird we have created a string with all the logins and searching with it. 

@eh2077  Could you kindly paste the proposal again from your login, just for reference in PR sake?

🎀👀🎀
C+ Reviewed

🎀 👀 🎀 C+ reviewed

cc: @jliexpensify

**Comment by abdulrahuman5196** [comment] 2023-07-02 15:37
@deetergp C+ approved comment is here - https://github.com/Expensify/App/issues/21783#issuecomment-1616704679

**Comment by eh2077** [comment] 2023-07-02 15:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Not able to invite an email when it's a substring of the selected email.

### What is the root cause of that problem?

The root cause of this issue is that we concat logins of selected options to a string `filterText` and check by `!filterText.includes(login)` if a `login` is unselected, which is wrong, see below snippet

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/workspace/WorkspaceInvitePage.js#L153-L155

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can save logins of selected options to an array `selectedLogins` and use method `!_.contains(selectedLogins, login)` to check if a login is unselected. 

To achieve it, we can change 

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/workspace/WorkspaceInvitePage.js#L153-L155

to

```js
const selectedLogins = _.map(this.state.selectedOptions, ({login}) => login);
const personalDetailsWithoutSelected = _.filter(this.state.personalDetails, ({login}) => !_.contains(selectedLogins, login));
const hasUnselectedUserToInvite = this.state.userToInvite && !_.contains(selectedLogins, this.state.userToInvite.login);
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by eh2077** [comment] 2023-07-02 15:56
> @eh2077 Could you kindly paste the proposal again from your login, just for reference in PR sake?

Sure! Added https://github.com/Expensify/App/issues/21783#issuecomment-1616710314

**Comment by abdulrahuman5196** [comment] 2023-07-05 18:09
@deetergp Pending on your approval.

**Comment by deetergp** [comment] 2023-07-05 20:16
@eh2077's proposal sounds like the right one. Let's do it!

**Comment by eh2077** [comment] 2023-07-06 08:53
@abdulrahuman5196 The PR https://github.com/Expensify/App/pull/22319 is ready for review, thanks.

**Comment by jliexpensify** [comment] 2023-07-17 06:24
Nice one, @abdulrahuman5196 don't forget the checklist :)

**Comment by abdulrahuman5196** [comment] 2023-07-22 13:55
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/7986#issuecomment-1646589116

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Edge case issue. So wouldn't be beneficial to create a test case for the same.

**Comment by abdulrahuman5196** [comment] 2023-07-22 13:55
@jliexpensify BZ checklist is complete here - https://github.com/Expensify/App/issues/21783#issuecomment-1646589371

**Comment by jliexpensify** [comment] 2023-07-23 23:40
Paying everyone now! @eh2077 - $1250, @abdulrahuman5196 - $1000.

**Comment by eh2077** [comment] 2023-07-24 01:11
@jliexpensify I think speed bonus should be applied here. See below timeline

Assign: 2023-07-05T20:16:12Z
C+ engineer @abdulrahuman5196 reviewed and approved: 2023-07-07T19:36:57Z
Internal engineer @deetergp merged: 2023-07-10T21:28:55Z

**Comment by jliexpensify** [comment] 2023-07-24 01:13
Hmm yes, good point - there were 2 days of the weekend

**Comment by jliexpensify** [comment] 2023-07-24 01:59
New job here - https://www.upwork.com/jobs/~015be223583ed610b4

**Comment by jliexpensify** [comment] 2023-07-24 02:01
@eh2077 and @abdulrahuman5196 have invited you for the bonus payout

**Comment by eh2077** [comment] 2023-07-24 02:02
@jliexpensify Accepted thanks!

**Comment by abdulrahuman5196** [comment] 2023-07-24 02:04
@jliexpensify accepted the invite

**Comment by jliexpensify** [comment] 2023-07-24 02:08
Paid, thanks!

**Closed by jliexpensify** 2023-07-24 02:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
