### ISSUE TITLE
[$500] "Hmm... it's not here" error message when navigating to "money2020"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34317] opened 2024-01-11 07:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #32164 
**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log out
2. Navigate to staging.new.expensify.com/money2020
3. Log in with a expensifail new account

## Expected Result:
You should be navigated to a new chat report, between your account & [money2020@expensify.com.](mailto:money2020@expensify.com.)

## Actual Result:
"Hmm... it's not here" error message when navigating to "money2020".

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/53875466-35e9-4718-a6fd-4d90ca1605c3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013946689ceb636208</li>
        <li>Upwork Job ID: 1745350007262670848</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by MelnykDmitro** [comment] 2024-01-11 10:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Reaching unlogged non existing URL doesn't cause redirect to **not found page**, however after logging in it navigates to **not found page**. 

### What is the root cause of that problem?

There is bug-like condition of **React Navigation** which causing unexpected reaching not found page. To replicate it user has to:
- Reach **not found page** when there is no defined **not found page** in the stack navigator.
- Reach changing of stack navigator to have **not found page**

### What changes do you think we should make in order to solve the problem?

We can Define not found screen in the PublicScreens to user lead to the HomeScreen. This way router won't reach not found page after authentication anymore.

### What alternative solutions did you explore? (Optional)

Provide **not found** page in case unathenticated user reaches non existing page.

**Comment by VickyStash** [comment] 2024-01-11 16:43
I guess the demo flow related to `money2020` was removed as a part of [this PR](https://github.com/Expensify/App/pull/33213), so it's an expected result and not a bug.

**Comment by MelnykDmitro** [comment] 2024-01-12 11:08
> I guess the demo flow related to `money2020` was removed as a part of [this PR](https://github.com/Expensify/App/pull/33213), so it's an expected result and not a bug.

Yes, demo flow `money2020` might be not relevant anymore. However there is still another bug with relates to any 404.

**Comment by mollfpr** [comment] 2024-01-12 16:47
> However there is still another bug with relates to any 404

Could you elaborate on it more or do you have some example for this kind of issue?

**Comment by mollfpr** [comment] 2024-01-15 14:04
@muttmuure We can close this. The `money2020` is removed, and the result is expected.

**Closed** 2024-01-17 18:33 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
