### ISSUE TITLE
Chat - Phone number is invited to Workspace countless time after invitation to workspace room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35111] opened 2024-01-24 22:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create Workspace
2. Create workspace room
3. Invite contact number user to the room
4. Navigate to the Workspace> Members
5. Invite the same contact number user
6. Go back to Invite page and invite same user

## Expected Result:
Invited user should be present on Workspace member list and message that this user is already member of this workspace should appear when try to add same user

## Actual Result:
Contact number user can be invited to Workspace countless time after same user invited to Workspace room
When dismiss workspace page and navigate to back to members this user disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d5c4c98a-3f4a-481c-9ac1-4d4d60374b76

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2024-01-25 05:52
Looks like this was fixed in a recent revert - I can't reproduce on staging

**Closed by thienlnam** 2024-01-25 05:52 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by amyevans** [comment] 2024-01-25 14:28
Thanks Jack! Confirmed as well
