### ISSUE TITLE
[Android] infinite loading search screen

### ISSUE THREAD

**Issue by kirillzyusko** [Expensify/App#37156] opened 2024-02-23 18:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** any
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg and @abdulrahuman5196 
**Slack conversation:**

## Action Performed:

- open app on Android
- go to search screen
- try to search anything

## Expected Result:

The loading should disappear when data is fetched from server.

## Actual Result:

Skeleton is always shown

## Workaround:

> Can the user still use Expensify without this being fixed? 

No

> Have you informed them of the workaround?

No

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/22820318/c3d81267-6100-4af3-a406-8120a50f6be9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment] 2024-02-26 20:51
I can't reproduce this and believe it has been fixed. Closing.

**Closed by isabelastisser** 2024-02-26 20:51 UTC
Labels: Daily, Overdue, Bug
