### ISSUE TITLE
[$500] IOU-User able to create distance request with vague location

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30626] opened 2023-10-31 11:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile icon --- Preferences
3. Toggle on forced offline
4. Navigate back to LHN
5. Tap on a Workspace chat
6. Tap plus icon-- Request money
7. Tap distance request
8. Enter start "Dh" and save
9. Enter Finish "Cb" and save
10. Tap next
11. Tap Request
12. Navigate back to LHN
13. Tap profile icon---- Preferences
14. Toggle off forced offline
15. Open the Workspace chat
16. Tap on distance request created to open distance request detail page
17. Tap on receipt

## Expected Result:
For vague location, if user creates distance request, it must show error.

## Actual Result:
User able to create distance request with vague location

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/1d56b051-7578-4231-b71f-1f7cc5f0757d

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01425f6ffb0736addd</li>
        <li>Upwork Job ID: 1719309451541983232</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by rakshitjain13** [comment] 2023-10-31 11:20
Dupe of https://github.com/Expensify/App/issues/29783

**Comment by bfitzexpensify** [comment] 2023-11-03 21:20
> Dupe of https://github.com/Expensify/App/issues/29783

Agreed, closing

**Closed by bfitzexpensify** 2023-11-03 21:20 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
