### ISSUE TITLE
Web - Workspace - Clicking on "Go to #admins room" the WS setting page appears for a moment.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19813] opened 2023-05-30 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19295

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account.
3. Go to Settings -> Workspaces -> Open any WS.
4. Press three dots.
5. Press Go to #admins room/Go to #announce room.

## Expected Result:
System navigates you to the corresponding workspace room.

## Actual Result:
The WS setting page appears for a moment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-2

**Reproducible in staging?:**Yes

**Reproducible in production?:**No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/3435833740abecd691f9f00e62c3f3f2a7d49ed37daca3eddd975f164f32a75a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdulrahuman5196** [comment] 2023-05-30 15:29
@lanitochka17  Could you add video of the issue?

**Comment by Julesssss** [comment] 2023-05-31 10:48
I'm struggling to see what the issue is here. I know it was reported on windows only, but the video matches what i see on macOS, and it seems fine...

https://github.com/Expensify/App/assets/10736861/e1a234b9-4431-42ea-b16a-bb66d6bbf281

**Comment by conorpendergrast** [comment] 2023-05-31 13:50
@Julesssss I agree - I'm confused on the bug here!

**Comment by conorpendergrast** [comment] 2023-05-31 13:51
Without further details, I'll close this out tomorrow

**Closed** 2023-06-06 08:36 UTC
Labels: Daily, Overdue, Bug
