### ISSUE TITLE
[$1000] Web - App crashes when selecting `Translate to "Language"` by right clicking on chrome in login screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13403] opened 2022-12-07 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open login page - right click and press on Translate to "Language".
2. Fill email id and press on continue.
3. Press go back on Not email-id:`Go back.
4. Press continue again on login screen.
5. Press go back again.
## Expected Result:
App shouldn't crash if webpage translate enabled.
## Actual Result:
App crashing randomly on user actions.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.36-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206266863-31e973a5-6831-40b3-bd49-0b0421758445.mov

https://user-images.githubusercontent.com/43996225/206266893-636a5e2b-466c-4348-8f79-01bc86a2f664.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jatinsoni
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670389024141949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01127b45e8eb04373b</li>
        <li>Upwork Job ID: 1600592978997096448</li>
    </ul>
</details>

**Comment by jatinsonijs** [comment] 2022-12-07 18:40
We can fix this by add class="notranslate" in body or html tag tag
<!DOCTYPE html>
<html lang="en" class="notranslate" translate="no">
<head>
  <meta name="google" content="notranslate" />
</head>
<body>
...
</body>
</html>

**Comment by marcaaron** [comment] 2022-12-07 20:23
I can't think of any reason why we would want to prevent people from translating the app with a `notranslate` attribute.

They should be able to use whatever plugins or browser features they want. 

Why is the app crashing?

**Comment by marcaaron** [comment] 2022-12-07 22:10
![2022-12-07_12-09-54](https://user-images.githubusercontent.com/32969087/206307439-30d9c3e7-0957-4a30-9ba0-30426a89d374.png)

This is the error that gets thrown

**Comment by marcaaron** [comment] 2022-12-07 22:11
https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore

Not in any of our code so it must be in a 3rd party repo

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-07 22:16
@marcaaron May be this GH issue comment might be of any help tracking down the issue https://github.com/facebook/react/issues/11538#issuecomment-390386520

The problem is that Google Translate replaces text nodes with <font> tags containing translations while React keeps references to the text nodes that are no longer in the DOM tree.

**Comment by marcaaron** [comment] 2022-12-07 22:21
Given that this is an old bug and has to be fixed in React I'm going to close this and hope it gets resolved in a future version. 

Until then, we shouldn't prevent people from translating the app using whatever tools they want. If it leads to a crash then that's not really on us to provide any solution for. You can use the app in the supported languages or hope that the app doesn't crash.

**Comment by puneetlath** [comment] 2022-12-07 22:37
That makes sense to me too. Thanks @marcaaron!

**Comment by yevheniitsuryk** [comment] 2022-12-07 22:46
### PROPOSAL

@marcaaron @puneetlath  @eVoloshchak Actually found a [solution here](https://github.com/facebook/react/issues/11538#issuecomment-390386520), and applied it in project - we need to wrap every text string in span, and no crashes or errors in console.

React throws in the following cases:

A text node is conditionally rendered and it's not the only child of its parent. Then React calls parent.removeChild(textNode) when the text node is removed and throws because textNode is no longer a child of parent. 

A node before a text node is conditionally rendered. Then React calls parent.insertBefore(someNode, textNode) when the node is inserted and throws because textNode is no long a child of parent.

https://github.com/Expensify/App/blob/main/src/components/Text.js
 ```diff
 const Text = React.forwardRef(({
    color,
    fontSize,
    textAlign,
    children,
    family,
    style,
    ...props
}, ref) => {
    // If the style prop is an array of styles, we need to mix them all together
    const mergedStyles = !_.isArray(style) ? style : _.reduce(style, (finalStyles, s) => ({
        ...finalStyles,
        ...s,
    }), {});
    const componentStyle = {
        color,
        fontSize,
        textAlign,
        fontFamily: fontFamily[family],
        ...mergedStyles,
    };

    if (!componentStyle.lineHeight && componentStyle.fontSize === variables.fontSizeNormal) {
        componentStyle.lineHeight = variables.fontSizeNormalHeight;
    }

-    return (
-        // eslint-disable-next-line react/jsx-props-no-spreading
-        <RNText allowFontScaling={false} ref={ref} style={[componentStyle]} {...props}>{children}</RNText>
-    );

+    const renderChildren = () => _.map(Children.toArray(children), child => <span>{child}</span>);
+  
+  return (
+    // eslint-disable-next-line react/jsx-props-no-spreading
+    <RNText allowFontScaling={false} ref={ref} style={[componentStyle]} {...props}>{renderChildren()}</RNText>
+  );
});
 ```

https://user-images.githubusercontent.com/64137632/206311464-29beb024-22e1-44e2-8367-1e79ed8e38f0.mp4

**Comment by marcaaron** [comment] 2022-12-08 00:40
That looks like a pretty low level change and I'm not sure the tradeoff of adding a span around every text component is going to be worth it. I don't feel we have a good reason to believe this crash will be common enough for us. Gonna stick with "do nothing" on this one for now unless it becomes a large problem.

**Comment by bnawalage** [comment] 2022-12-08 13:34
PROPOSAL

@marcaaron 

I found where the issue was and it was in the below code segment 

![Screenshot from 2022-12-08 20-09-13](https://user-images.githubusercontent.com/17808099/206458102-f3d92228-15f2-4819-a4ac-39d52dbfe13d.png)

To fix this. I changed two files PasswordForm.js and ChangeExpensifyLoginLink.js

I removed the inline code (highlighted in the above image ) and createed a function in the PasswordForm.js to get the login value (refer the below images)  and then passed it as a property to ChangeExpensifyLoginLink.js
  
![Screenshot from 2022-12-08 21-20-42](https://user-images.githubusercontent.com/17808099/206457504-021a6639-d30d-442d-ad51-2dcde22bddf9.png)

![Screenshot from 2022-12-08 20-15-57](https://user-images.githubusercontent.com/17808099/206444387-37b9e00b-579f-433c-9fa1-5796ef38d5e0.png)

Conclution - The reason might be, it can't send a functional behavior as children object to the Text widget. 

[Untitled_ Dec 8, 2022 9_16 PM.webm](https://user-images.githubusercontent.com/17808099/206458286-cd146828-dd53-4e6d-b2f7-1905bc839e35.webm)

**Comment by puneetlath** [comment] 2022-12-12 15:44
Actually, that sounds pretty good to me. What do you think @marcaaron?

**Comment by puneetlath** [comment] 2022-12-13 14:58
Good point. @bnawalage can you help us with more detail on the root cause of the issue? That will help us decide whether to go with your solution.

**Comment by eVoloshchak** [comment] 2022-12-13 15:12
@bnawalage is correct, the component that causes the issue is [ChangeExpensifyLoginLink.js](https://github.com/Expensify/App/blob/main/src/pages/signin/ChangeExpensifyLoginLink.js). 
Because, as @yevheniitsuryk correctly pointed out

> React throws in the following case: A text node is conditionally rendered and it's not the only child of its parent. Then React calls parent.removeChild(textNode) when the text node is removed and throws because textNode is no longer a child of parent.

And both of `Text` components on `ChangeExpensifyLoginLink` have multiple children, which causes the error. 
This approach would work, but it has two problems

- We'd have to make sure to never make this mistake in the future, probably an `eslint` rule or a new checklist item would be needed
- Many other pages also have this issue, for instance, TermsAndLicenses, CloseAccountPage, ValidationStep, etc

We need a universal solution

**Comment by puneetlath** [comment] 2022-12-13 15:21
Ok, given that this is a confirmed Chromium bug and all the solutions presented are still workarounds, I'm inclined to re-close the issue. 

Thanks everyone for your investigations, we really appreciate it. We're looking forward to working with you on other issues!

**Closed by puneetlath** 2022-12-13 15:21 UTC
Labels: Daily, Internal, Bug
