### ISSUE TITLE
[HOLD for payment 2024-08-20] Expense - Reply in thread option is missing for system message after rejoining thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47225] opened 2024-08-12 12:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/46640
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Go to transaction thread.
5. Edit any field and save it.
6. Right click on system message > Reply in thread.
7. Click on the report header > Leave.
8. Right click on system message > Join thread.
9. Right click on system message again.

## Expected Result:
The system message will have Reply in thread option after rejoining thread.

## Actual Result:
Reply in thread option is missing for system message after rejoining thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/60cd22b4-d3b7-4ff0-9447-c0639fd22cf4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-08-12 12:24
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-08-12 12:28
Production 

https://github.com/user-attachments/assets/9728a16e-4d69-4a31-9e58-28709fc10169

**Comment by bernhardoj** [comment] 2024-08-12 13:48
This comes from my [PR](https://github.com/Expensify/App/pull/46640). Opened up a new PR to fix this.

**Comment by Beamanator** [comment] 2024-08-13 00:10
@bernhardoj @mkhutornyi any update here? Looks like https://github.com/Expensify/App/pull/47234 was started to fix this bug, but @mkhutornyi thinks there might be some other bug, right? What's next?

**Comment by bernhardoj** [comment] 2024-08-13 02:59
@Beamanator I think @mkhutornyi just asking for confirmation, which I replied on the PR.

**Comment by Beamanator** [comment] 2024-08-13 03:05
ahaa ok great! Looks like y'all are moving this along, thanks! 🙏

**Comment by Beamanator** [comment] 2024-08-13 15:48
Working well in staging!

**Comment by lschurr** [comment] 2024-08-20 16:31
Just clarifying @bernhardoj @Beamanator - was there a regression here or is full payment due for the PR?

**Comment by bernhardoj** [comment] 2024-08-20 16:37
This issue was discovered after my [PR](https://github.com/Expensify/App/pull/46640), but the issue actually existed before, so I'm not sure if a payment is eligible here. It would be nice if there is though 😄 

cc: @Beamanator @mkhutornyi

**Comment by lschurr** [comment] 2024-08-21 21:15
Double checking on this one internally before moving forward with payments.

**Comment by mallenexpensify** [comment] 2024-08-23 21:44
@mkhutornyi and @bernhardoj we're discussing the regression internally, I commented
> I think this falls into [here in the C+ doc](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#bookmark=id.qr9c929owwy8)
> > If regressions are found that “should have”* been caught after the PR has been approved,

and
> >*“Should have” = C+ should have caught the bug by fully following the checklist.  If C+ skips a step or completed the checklist incompletely, payment will be cut in half. Exceptions can be made by the assigned internal engineer for large PRs that introduce new functionality.

and @Beamanator commented
> Yeah that sounds like it to me too - I'm pretty sure in the checklist we have some points about testing any changes to a component everywhere that that component is used - which soundsssssss like is what they admitted to missing

@mkhutornyi @bernhardoj do you agree the regression was caused because something was missed that you _should_ have caught?

**Comment by bernhardoj** [comment] 2024-08-24 02:07
I don't think it's easy to catch since the issue only happens in a one-expense report, while we are testing on a transaction thread level. The issue is also happening in prod, but on a normal message, not on a system message since we are not able to reply in thread a system message before.

**Comment by lschurr** [comment] 2024-08-26 20:08
Thanks for the discussion! We've decided to pay as normal.

Payment Summary:
- Contributor: $250 @bernhardoj (Please request in NewDot)
- Reviewer: $250 @mkhutornyi ([To be paid in Upwork](https://www.upwork.com/nx/wm/offer/103691784))

**Comment by bernhardoj** [comment] 2024-08-27 02:31
Thanks! Requested in ND.

**Closed** 2024-08-28 15:04 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-28 17:29
$250 approved for @bernhardoj
