### ISSUE TITLE
[500] Workspace - #applause.expensifail.com shows incorrect title and avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39097] opened 2024-03-27 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on #applause.expensifail.com
3. Tap on header
4. Tap on avatar

## Expected Result:
The avatar page of #applause.expensifail.com ust show correct title " #applause.expensifail.com " and avatar as "A"

## Actual Result:
The avatar page of #applause.expensifail.com shows incorrect title " Unavailable Workspace " and avatar as "U"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e391edc2-6a97-4b2c-b58f-f5a6910f32bf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012543d96e3f384b66</li>
        <li>Upwork Job ID: 1785066979434536960</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-27 19:57
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment] 2024-04-11 21:18
I haven't been able to reproduce. @lanitochka17 if you are still experiencing this please reopen and let me know

**Comment by lanitochka17** [comment] 2024-04-24 18:31
Issue is still reproducible on the latest build 1.4.64-6

https://github.com/Expensify/App/assets/78819774/cae2f549-7abe-429b-a714-094c628baf10

**Comment by kevinksullivan** [comment] 2024-04-29 22:01
Moving to wave-collect since this is workspace chat related.

**Comment by Santhosh-Sellavel** [comment] 2024-05-03 18:17
No proposals yet

**Comment by kevinksullivan** [comment] 2024-05-08 18:29
No proposals

**Comment by kevinksullivan** [comment] 2024-05-21 22:18
We've had no traction here, so bumping up to $500.

**Comment by wildan-m** [comment] 2024-05-23 14:42
@lanitochka17 can you invite me to that workspace? I can't reproduce it myself.

if that's possible, here is my dev email: wildevemail+1@gmail.com

**Comment by kevinksullivan** [comment] 2024-06-04 22:05
Still waiting on proposals. I will defer to @lanitochka17 on [this ask](https://github.com/Expensify/App/issues/39097#issuecomment-2127311274), as I am not sure how they use that room.

**Comment by kevinksullivan** [comment] 2024-06-07 20:46
@lanitochka17 can you take a look at the request above?

**Comment by kevinksullivan** [comment] 2024-06-07 20:47
If we are only seeing this in applause and cannot reproduce elsewhere I'd also vote we close this

**Comment by lanitochka17** [comment] 2024-06-10 11:52
@kevinksullivan Hello. Any member with an expensifail account can join this room. You need to enter #applause.expensifail.com in the search.

**Comment by kevinksullivan** [comment] 2024-06-13 18:56
@wildan-m won't have an expensifail account though. I'm going to close this out until we see it happen outside of applause@

**Closed by kevinksullivan** 2024-06-13 18:56 UTC
Labels: External, Daily, Overdue, Bug
