### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] [Simplified Collect][Categories] WorkspaceCategoriesSettingsPage: full page implementation - toggle require categories policy, onyx action

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35706] opened 2024-02-02 19:38 UTC
Implement `WorkspaceCategoriesSettingsPage: full page implementation - toggle require categories policy, onyx action` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154080d90e7f3dfba</li>
        <li>Upwork Job ID: 1755659460840173568</li>
        <li>Last Price Increase: 2024-02-08</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2024-02-02 19:38
@ArekChr can you please comment here so I can assign you to the issue?

**Comment by lschurr** [comment] 2024-02-08 16:12
Any update here @ArekChr?

**Comment by brunovjk** [comment] 2024-02-08 18:49
I would like to work on it. Thanks.

**Comment by luacmartins** [comment] 2024-02-08 19:02
@brunovjk thanks for the interest, but we already have someone working on this.

**Comment by happydev0110** [comment] 2024-02-08 21:41
Hi
I hope work with you.

**Comment by lschurr** [comment] 2024-02-12 17:40
What's the latest here? Any update @ArekChr?

**Comment by cubuspl42** [comment] 2024-02-13 08:44
If @ArekChr is unavailable on next overdue we can consider re-assigning

**Comment by ArekChr** [comment] 2024-02-13 08:55
Hi @lschurr this issue is blocked by https://github.com/Expensify/App/issues/35705, need to finish categories page first

**Comment by trjExpensify** [comment] 2024-02-23 18:29
With the PR in review, I'm taking this off hold.

**Comment by lschurr** [comment] 2024-03-05 17:22
@allroundexperts - Could you review and confirm we don't need a regression test?

**Comment by lschurr** [comment] 2024-03-07 20:11
I pulled back the contract offered in Upwork to Jakub T. since they didn't end up reviewing the PR - https://github.com/Expensify/App/pull/37133#issuecomment-1965126581

**Comment by lschurr** [comment] 2024-03-07 20:11
Payment summary is correct. Closing this one out.

**Closed by lschurr** 2024-03-07 20:11 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-03-12 02:59
$500 approved for @allroundexperts based on summary.
