### ISSUE TITLE
Workspace - The workspace deleted in the newly created account reappears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13154] opened 2022-11-29 20:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. In the email field, enter a gmail email address for a new account -> Press continue
3. Validate new account and login
4. Create New Workspace
5. Delete nearly created workspace

## Expected Result:
The workspace is removed without any problems

## Actual Result:
1. The deleted workspace reappears
2. An error appears when trying to delete the workspace again

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.33.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204636203-c169511a-8675-4bda-a5c8-3c0a63bf1606.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2022-11-30 21:47
Unable to reproduce this locally at the moment, and can't reproduce either on staging - though the site is having issues right now, I'll try again later.

**Comment by francoisl** [comment] 2022-12-02 18:27
Still can't reproduce. After I delete the workspace, the left panel goes back to the (empty) Workspaces page, unlike the Settings page in your video. So I'm thinking we must have changed something recently which also coincidentally fixed the issue here. Going to leave this open a little more so I can confirm on staging, the site issues are making it really difficult to use at the moment :( 

https://user-images.githubusercontent.com/2229301/205357885-2a4c4c57-1231-44dd-9835-c4e9f86db030.mov

**Comment by isabelastisser** [comment] 2022-12-05 13:48
Hey @francoisl , feel free to close the issue if you still can't reproduce it this week. Thanks!

**Comment by francoisl** [comment] 2022-12-06 19:41
Yeah still can't reproduce today, closing!

**Closed by francoisl** 2022-12-06 19:41 UTC
Labels: Daily, Bug
