### ISSUE TITLE
[$500] Chat - In bracket() email entered [$](expen@gmail.com) is shown like URL link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30018] opened 2023-10-19 19:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join 
 Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
![image](https://github.com/Expensify/App/assets/78819774/798706ec-e189-4a44-aa43-8e6ac931ae2c)

## Expected Result:
![image](https://github.com/Expensify/App/assets/78819774/1f24a6a2-4af6-4277-bcdf-f90ed1ee60b7)

## Actual Result:
![image](https://github.com/Expensify/App/assets/78819774/13a18f3a-7220-44d0-a5f2-0a192a2fcfa8)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/95a5da0b-04f7-4a6e-ba7a-6878e85a0f3a

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b86aa5e0856bfe6c</li>
        <li>Upwork Job ID: 1715089429733097472</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-10-20 00:18
This is not a bug as we support alias text for email as well/

**Comment by greg-schroeder** [comment] 2023-10-23 10:20
closing

**Closed by greg-schroeder** 2023-10-23 10:20 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
