### ISSUE TITLE
[$250] Split expense - Scan receipt does not show red brick road error details

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41256] opened 2024-04-29 21:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714397696317219

## Action Performed:
1. Open NewDot app
2. Click on Fab > Split expense
3. Scan a receipt with details missing and split
4. Open the receipt from the preview
## Expected Result:
The error message on the preview says "Receipt missing details" but when you go to view the Split details, you don't know which details are actually missing. We should highlight under the specific inputs which details were missing, for example, if the Merchant name couldn't be found, let's highlight the Merchant row
## Actual Result:
In the split details view, there is no indication of which fields need to be fixed.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/4af32aeb-8837-4e8f-afaa-05b5dd9aceb6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01395d5820a0885f64</li>
        <li>Upwork Job ID: 1786772949119090688</li>
        <li>Last Price Increase: 2024-05-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by bfitzexpensify** [comment] 2024-05-04 15:01
Added to vip-split, and sending external to see if this can be worked on by contributors.

**Comment by nkdengineer** [comment] 2024-05-06 05:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the split details view, there is no indication of which fields need to be fixed.

### What is the root cause of that problem?
We pass the split draft transaction to `MoneyRequestComfirmationList` if it exists. If we edit any field before the scan is complete, we will create a split draft transaction in Onyx and the state of the scan will be `ready`. After the scan is complete, the receipt state is updated in the current transaction and it's not updated in split draft transaction.


https://github.com/Expensify/App/blob/8db67c4da2e5547abd08441503ca92fe06363d7f/src/pages/iou/SplitBillDetailsPage.tsx#L129


So the error field will not appear in confirm page because we use the draft transaction which has the scan state is `ready`.

https://github.com/Expensify/App/blob/8db67c4da2e5547abd08441503ca92fe06363d7f/src/components/MoneyRequestConfirmationList.tsx#L335

### What changes do you think we should make in order to solve the problem?
In `SplitBillDetailPage`, we already pass `hasSmartScanFailed` to confirm page which check the current transaction. So we can do the same by creating `hasMissingSmartscanFields` variable on `SplitBillDetailPage` and passing `hasMissingSmartscanFields` it to confirm page 

```
const hasMissingSmartscanFields = TransactionUtils.hasMissingSmartscanFields(transaction);
```
https://github.com/Expensify/App/blob/8db67c4da2e5547abd08441503ca92fe06363d7f/src/pages/iou/SplitBillDetailsPage.tsx#L77-L78

And then replace `TransactionUtils.hasMissingSmartscanFields(transaction)` check here with this prop
```
!!hasSmartScanFailed && hasMissingSmartscanFields
```
https://github.com/Expensify/App/blob/8db67c4da2e5547abd08441503ca92fe06363d7f/src/components/MoneyRequestConfirmationList.tsx#L335

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-05-13 03:13
@ishpaul777 I can reproduce this bug by editing any field before the scan is complete. As the video below, I edited the category field before the scan is complete.

https://github.com/Expensify/App/assets/161821005/4d02f5e8-d202-47ab-99fe-107aa4278867

**Comment by nkdengineer** [comment] 2024-05-20 05:22
@shubham1206agra The problem is, we pass split draft transaction as `transaction` prop into `MoneyRequestComfirmationList` and the state of the scan in `draftTransaction` is `ready` that makes `TransactionUtils.hasMissingSmartscanFields(transaction)` returns false in `MoneyRequestComfirmationList` although the scan is complete. So we should check `TransactionUtils.hasMissingSmartscanFields` with the current transaction in `SplitBillDetailsPage` and pass it as a new prop to `MoneyRequestComfirmationList`

**Comment by bfitzexpensify** [comment] 2024-05-28 21:02
Update on this one @shubham1206agra?

**Comment by mvtglobally** [comment] 2024-05-30 01:34
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2024-05-30 22:26
Asked #qa to check via https://expensify.slack.com/archives/C9YU7BX5M/p1717088516206259

Assigning a BZ buddy as I head OOO until June 11th. 

@jliexpensify - if the test confirms we can't reproduce, we can close this, otherwise continue with the normal process

**Comment by kavimuru** [comment] 2024-05-31 00:28
issue fixed. 

https://github.com/Expensify/App/assets/43996225/c2f508ef-9e93-4cd7-9491-4672fbd2795b

**Comment by jliexpensify** [comment] 2024-05-31 00:59
Awesome thanks! Job removed, closing!

**Closed by jliexpensify** 2024-05-31 00:59 UTC
Labels: External, Daily, Help Wanted, Bug, retest-weekly
