### ISSUE TITLE
[$500]  IOU - Crash when editing the description of an IOU that was initially created with a description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28464] opened 2023-09-29 11:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27830
## Action Performed:
1. Open a New Expensify app
2. Log in with any account
3. Navigate to any conversation
4. Create any IOU with a description
5. Navigate to the details of the created IOU
6. Edit or add a description

## Expected Result:
You should be able to edit the description again or as many times as you need without a crash

## Actual Result:
The app crashes when attempting to edit the IOU description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] Windows / Chrome
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3f3e9a96-0cbb-4808-8c64-fc2ab1ba7c36

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a56b914ca5e471d</li>
        <li>Upwork Job ID: 1713998814284345344</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-10-02 22:11
Newdot went down for me in the middle of testing this. Will move on and circle back.

**Comment by strepanier03** [comment] 2023-10-06 23:27
I cannot recreate this.

**Comment by strepanier03** [comment] 2023-10-06 23:27
<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/aa4bb29e-99d1-40da-addb-2ddd0bebe4f8">

**Comment by lanitochka17** [comment] 2023-10-09 17:30
@strepanier03  Hello Errors do not appear, but now there is a crash; change description

https://github.com/Expensify/App/assets/78819774/41e3d146-addd-4ba9-acfc-194095ff3d61

**Comment by strepanier03** [comment] 2023-10-12 23:21
Thanks for the heads up @lanitochka17 - I'll test again.

**Comment by strepanier03** [comment] 2023-10-16 19:18
I can recreate this with the crash on staging so I'll update the OP comment.

https://github.com/Expensify/App/assets/10925636/0540b0e7-23bd-4250-8f85-6b456d6960db

**Comment by wlegolas** [comment] 2023-10-16 22:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - Crash when editing the description of an IOU that was initially created with a description

### What is the root cause of that problem?

The problem is related when getting the transaction details and the transaction's "**comment**" property has a value of type number.

https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/libs/ReportUtils.js#L1383

When the transaction's comment property has a **number**, the method `getDescription` assumes that the value is a string, but this value is treated inside the ONYX as a number. For this reason, an error is thrown inside the `BaseTextinput` component because the **number** object doesn't have the `endsWith` method.

https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/components/TextInput/BaseTextInput.js#L427

### What changes do you think we should make in order to solve the problem?

We must change the `getDescription` method to emphasize that the value in the `comment` property is a string.

https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/libs/TransactionUtils.ts#L196

**Note:** This method is used in a few places (you can see in the image below) but with the same purpose, showing the current and old description, for this reason, I think this change won't bring side effects to the application.

![image](https://github.com/Expensify/App/assets/698363/3ba74a04-48f9-452a-990a-b0dfe1310292)

### What alternative solutions did you explore? (Optional)

Another solution was to change the `EditRequestPage` component to cast the value from the `transactionChanges` object to be a string, but the value is already a string.

https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/pages/EditRequestPage.js#L168

**POC**

https://github.com/Expensify/App/assets/698363/5099ff2e-94ca-42b2-90d2-032def5a9388

**Comment by wlegolas** [comment] 2023-10-18 20:19
## Proposal
[Updated](https://github.com/Expensify/App/issues/28464#issuecomment-1768784229)

**Comment by strepanier03** [comment] 2023-10-18 22:51
Friendly bump @aimane-chnaif for proposals. Thanks!

**Comment by wlegolas** [comment] 2023-10-20 19:43
Hi, @aimane-chnaif I tested locally here with the latest version from the `main` branch and the problem still occurs, as you can see in the evidence below:

https://github.com/Expensify/App/assets/698363/502a359d-fc07-476c-a4c4-0e650a75c9fb

**Comment by strepanier03** [comment] 2023-10-26 00:06
Friendly bump @aimane-chnaif, thank you 🙌

**Comment by mvtglobally** [comment] 2023-10-27 00:43
Issue not reproducible during KI retests. (First week)

**Comment by wlegolas** [comment] 2023-10-27 12:56
> @wlegolas can you test again on latest main?

Sure, I'll test and bring the result.

**Comment by wlegolas** [comment] 2023-10-27 13:21
Hi @aimane-chnaif 

Unfortunately, the error still occurs using the latest `main` version `v1.3.92-0`.

https://github.com/Expensify/App/assets/698363/aef693e4-d07e-407a-9fb2-62b06f4d8ad5

**Comment by strepanier03** [comment] 2023-10-30 22:25
I'm going to switch this back to External.

**Comment by wlegolas** [comment] 2023-10-30 23:07
## Proposal
[Updated](https://github.com/Expensify/App/issues/28464#issuecomment-1768784229)

**Comment by pradeepmdk** [comment] 2023-10-31 03:02
@wlegolas I am not able to reproduce this on the latest main. are you?

**Comment by wlegolas** [comment] 2023-10-31 11:44
Hi @aimane-chnaif and @pradeepmdk 

This issue was fixed yesterday through this PR https://github.com/Expensify/App/pull/30526.

**Comment by wlegolas** [comment] 2023-11-01 00:53
Hi @aimane-chnaif I think the problem is related to the old money requests, when I create a new one, the `comment` value is of type `string`.

When I'm using an old money request I can see that the `comment` is a number, but with the fix https://github.com/Expensify/App/pull/30526 the issue is not happening.

**Comment by strepanier03** [comment] 2023-11-03 23:03
Per [this](https://github.com/Expensify/App/issues/28464#issuecomment-1787058185) I am closing as fixed.

**Closed by strepanier03** 2023-11-03 23:03 UTC
Labels: External, Engineering, Daily, Overdue, Bug
