### ISSUE TITLE
[HOLD for payment 2024-01-04] [$1000] IOS - Emoji chopped off from top in workspace name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26044] opened 2023-08-27 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings-> Workspaces
2. Click New Workspace -> Click Settings
3. Rename with “:vertical_traffic_light::vertical_traffic_light::vertical_traffic_light::vertical_traffic_light:” -> Click Save

## Expected Result:
Emoji with some height is being chopped off from top

## Actual Result:
:vertical_traffic_light: Emoji shouldn’t be chopped off

💥 Please note, this seems to be device-specific and will likely only affect smaller phones (for example, the issue was reproduced on an iPhone 11)💥 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Image from iOS (2)](https://github.com/Expensify/App/assets/93399543/62f77689-2c8d-488a-8758-cc1c94069167)

![Image from iOS (1)](https://github.com/Expensify/App/assets/93399543/10557585-d359-46f5-9c23-148786782aa0)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692310024902729
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119f528f80030b332</li>
        <li>Upwork Job ID: 1696626363709296640</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by DinalJivani** [comment] 2023-08-29 19:51
@johncschuster 
I am able to reproduce this issue on iPhone 11 iOS/Native App. 
Not sure for about other devices though...

**Comment by johncschuster** [comment] 2023-08-29 20:12
Thanks for calling that out, @DinalJivani! I've updated the OP to indicate that this might be device-specific.

**Comment by dantastisk** [comment] 2023-08-30 00:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The 🚦-emoji is cut-off when used in the name of a workspace.

### What is the root cause of that problem?

The root cause of the problem is the `styles.textHeadline` being applied to the element. The style combines `variables.fontSizeXLarge` with `variables.lineHeightXXLarge`, which causes the clipping as the line-height is simply not large enough for the font size. This happens everywhere that `styles.textHeadline` is used. Another example can be seen with the user displayname as can be seen here:

<details>
  <summary>Screenshot of user page</summary>
  
![8E2A30BF-D3A1-40D4-A370-994F9B76C2BF](https://github.com/Expensify/App/assets/48072523/8a7d1137-b7c4-4652-94d9-6208212d2e64)
</details>


The style gets applied here:
https://github.com/Expensify/App/blob/96a0db1aa2e239530f926b9bf62951f3c3408918/src/pages/workspace/WorkspaceInitialPage.js#L239-L244

The style:
https://github.com/Expensify/App/blob/96a0db1aa2e239530f926b9bf62951f3c3408918/src/styles/styles.js#L382C1-L388

The variables in question:
https://github.com/Expensify/App/blob/96a0db1aa2e239530f926b9bf62951f3c3408918/src/styles/variables.ts#L54
https://github.com/Expensify/App/blob/96a0db1aa2e239530f926b9bf62951f3c3408918/src/styles/variables.ts#L95

### What changes do you think we should make in order to solve the problem?


A clean and simple fix is to change `styles.textHeadline.lineHeight` from `variables.lineHeightXXLarge` to `variables.lineHeightXXXLarge`. This ensures that it gets fixed everywhere and looks perfect as shown in the screenshots below.

<details>
  <summary>Screenshot of workspace with fix</summary>
  
![1E2265DA-0EA0-4A43-A3ED-E26478595943](https://github.com/Expensify/App/assets/48072523/7e8f8ccc-d757-4556-8600-78c4fcea0d1a)

</details>

<details>
  <summary>Screenshot of user page with fix</summary>
  
![0E4AFC78-BDAC-43AA-B2AE-07B54EB0B9D0](https://github.com/Expensify/App/assets/48072523/a8b71b4d-49aa-4ac4-8de8-ecfe3e8b0403)

</details>

### What alternative solutions did you explore? (Optional)

Alternative solutions include introducing a new style specifically for where `styles.textHeadline` is used and emojis might appear.

**Comment by dantastisk** [comment] 2023-09-05 14:05
@fedirjh It affects quite a few tall emojis. Also the issue gets increasingly worse as text size is decreased on the device and affects text too on the lower settings, especially letters with accents (see the Á in the screenshots below).

As for potential regressions, I've checked everywhere that the `textHeadLine` style is used, and my proposal doesn't seem to break anything. On the contrary it actually fixes the issue in other places as well (like the user displayname and the participant details in a report).

This is with the lowest text size setting:
![BC7E3E6E-01E6-45A0-BCFD-565CD2D60F31](https://github.com/Expensify/App/assets/48072523/663b81f5-7497-4fe1-b1cc-c438346b99f7)

Same settings with the proposed fix:
![28071255-9257-4564-9FB5-B92C7B371A70](https://github.com/Expensify/App/assets/48072523/3aa595d1-479a-495b-877d-ded05c275638)

**Comment by dantastisk** [comment] 2023-09-05 17:22
> @dantastisk what device have you tested on?

The screenshots are from a physical iPhone XS.

I was not able to reproduce the bug on a simulated iPhone, initially, but I realize now, that this is because the bug is related to the device text size setting (in Settings -> Accessibility -> Display & Text Size -> Larger Text). As far as I can tell, the chopping only happens when this is set to the 3rd tick or lower, worsening as the text size is decreased.

<img width="313" alt="image" src="https://github.com/Expensify/App/assets/48072523/a5632594-5256-4e01-9284-78c36b27b92c">

I do not know how common it is to adjust these settings and what the policy is for supporting this, but this makes it seem like it should be supported:

https://github.com/Expensify/App/blob/cbda2b03824d9b125ec6ab19e87ff533bea1b22f/src/styles/variables.ts#L3-L12

**Comment by DinalJivani** [comment] 2023-09-06 12:33
@dantastisk 

I checked this Text size thing, default selection will be 3rd tick, When we go for larger size it actually works fine, But when you go to smallest size it chopped the emoji even more... Adding video for same below.

https://github.com/Expensify/App/assets/58871336/de194a59-72c6-4640-b89a-8ab6c3693b37

**Comment by johncschuster** [comment] 2023-09-12 13:48
> @johncschuster This bug seems to be an emoji/device-specific case, and it's an extremely edge case, I suggest we do nothing here.

@fedirjh sorry I missed this comment! I'm a bit torn. Yes, I agree this is a bit device-specific, but the `Universal Font Size` setting in iOS's Accessibility features might make this behavior more common.

@Expensify/design, what are your thoughts on fixing this behavior? I kinda feel like we should fix it to ensure _all_ folks are seeing New Expensify as we intend it to be seen.

**Comment by mvtglobally** [comment] 2023-09-13 17:18
Issue not reproducible during KI retests. (First week)

**Comment by DinalJivani** [comment] 2023-09-14 11:24
> Issue not reproducible during KI retests. (First week)

@mvtglobally 
Did you test this issue on iPhone 11 ? 
I think this is device specific and depends upon some attributes like Font size in Settings > Accessibility.

**Comment by shawnborton** [comment] 2023-09-15 02:10
Hmm I'm not too sure here, I don't know what our overall strategy is for supporting the phone's accessibility sizes. I agree it shouldn't be cut off, but I'm not sure how exactly we might fix that.

**Comment by johncschuster** [comment] 2023-09-19 21:47
Bringing the [discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1695159980593109) around phone size support to `#bug-zero`

**Comment by johncschuster** [comment] 2023-09-26 16:08
Ok! I've got one opinion that we should fix this. Let's go ahead and give it a try. @fedirjh do you think any of the proposals above are sufficient?

**Comment by mvtglobally** [comment] 2023-09-28 03:13
Issue not reproducible during KI retests. (Second week)

**Comment by DinalJivani** [comment] 2023-09-29 11:24
>Issue not reproducible during KI retests. (First week)

@mvtglobally
Did you test this issue on iPhone 11 ?
I think this is device specific and depends upon some attributes like Font size in Settings > Accessibility.

**Comment by dantastisk** [comment] 2023-09-29 11:26
@mvtglobally @DinalJivani I can reproduce on all iOS devices, seems to only depend on font size settings.

**Comment by DinalJivani** [comment] 2023-09-29 11:28
@dantastisk 
Yes correct but on iPhone 11 it chops off emojis with normal/default text size too.

**Comment by dantastisk** [comment] 2023-10-04 07:46
Busy week. Update coming tomorrow!

**Comment by johncschuster** [comment] 2023-10-04 21:24
Thanks, @dantastisk!

**Comment by dantastisk** [comment] 2023-10-05 14:18
I can no longer reproduce this. Neither for the original case or the ones in your screenshots @fedirjh. Can you check if it's the same for you?

**Comment by DinalJivani** [comment] 2023-10-10 12:13
I'm still able to reproduce on v1.3.80-0 Mobile app
Tested on iPhone 11 with iOS 16.0

![IMG_2FB0F1CE6A67-1](https://github.com/Expensify/App/assets/58871336/ce559450-c356-4c45-982e-5de6ef94ccfc)

**Comment by johncschuster** [comment] 2023-10-17 20:52
Looks like this behavior is still reproducible. @dantastisk @neonbhai can you update your proposals to account all cases within the app?

**Comment by johncschuster** [comment] 2023-10-20 10:47
@dantastisk / @neonbhai bump!

**Comment by johncschuster** [comment] 2023-10-26 19:42
Pinged in Slack

**Comment by johncschuster** [comment] 2023-11-07 21:43
Good thinking! I'll raise this to an agency.

**Comment by johncschuster** [comment] 2023-11-14 22:25
I have raised this to both SWM and Callstack to see if anyone can take this on.

**Comment by rezkiy37** [comment] 2023-11-15 09:40
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by johncschuster** [comment] 2023-11-15 13:25
That sounds great, @rezkiy37! It's all yours!

**Comment by rezkiy37** [comment] 2023-11-17 10:01
> @rezkiy37 This bug appears to impact other areas, particularly text inputs. Please review my comment [#26044 (comment)](https://github.com/Expensify/App/issues/26044#issuecomment-1741012875)

I know it. I confirmed it.

**Comment by rezkiy37** [comment] 2023-11-17 17:56
No important updates, still investigating.

**Comment by rezkiy37** [comment] 2023-11-20 14:48
Yep, I am preparing a proposal today for Callstack internal review, then will post it here.

**Comment by rezkiy37** [comment] 2023-11-20 18:27
@fedirjh, I just found an interesting situation. There aren't any problems to fix line of a static text. 
However, most cases mentioned in your [comment](https://github.com/Expensify/App/issues/26044#issuecomment-1741012875) are inputs. Moreover, only when the keyboard is opened. The problem disappears, when you close the keyboard. I thought to update `lineHeight` of the input.

Meanwhile, other guys [updated](https://github.com/Expensify/App/pull/14273/files) logic for the **BaseTextInput's** `lineHeight`.

<img width="715" alt="Screenshot 2023-11-20 at 19 17 05" src="https://github.com/Expensify/App/assets/57314631/d62d86e0-bc37-455d-b19a-d903c3d60508">

Actually, if we are adding any `lineHeight` to the input, it breaks one-line one.

Also, playing with the input's `height` it's got the wrong kind of luck. 

So, I think we need to accept a compromise, because it is a super edge case and one-line inputs more important.

**Comment by rezkiy37** [comment] 2023-11-27 10:26
Melvin, AFAIK waiting on a decision on comments above from @johncschuster.

**Comment by rezkiy37** [comment] 2023-11-28 16:24
No update.

**Comment by rezkiy37** [comment] 2023-11-29 15:50
No update.

**Comment by johncschuster** [comment] 2023-12-06 14:47
So sorry I missed your comment, @fedirjh.

> @johncschuster It seems we're somewhat limited in options for addressing this bug affecting single-line inputs. Given the importance of one-line inputs across the app and the rarity of this edge case, embracing a compromise might be the most pragmatic way forward. What are your thoughts on this?

I'm open to a compromise, but I think I would like to bring this conversation to Slack so we can get a more holistic understanding of the problem/solution and any consequences that might come from the compromise. Would you mind raising the discussion? I'm happy to do it, but I think you might be able to explain it a little better.

**Comment by rezkiy37** [comment] 2023-12-06 15:07
I've opened the [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1701875218950319).

**Comment by johncschuster** [comment] 2023-12-08 22:03
Ok! We've discussed the compromise in Slack, and I think we're good to accept it. 👍

**Comment by rezkiy37** [comment] 2023-12-11 09:50
Cool, so I am preparing a PR soon.

**Comment by rezkiy37** [comment] 2023-12-12 14:51
Currently, the proposal is being reviewed internally.

**Comment by rezkiy37** [comment] 2023-12-13 12:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tall emojis (like 🚦) are chopped off from top.

### What is the root cause of that problem?
The root cause of the problem is that `lineHeight` is not large enough in pair with `fontSize` of some components. The app should handle cases when user globally increase font size and decrease as well.

In general there is a few cases what we are going to fix: a workspace name, a user display name and tabs.

### What changes do you think we should make in order to solve the problem?
Increase `lineHeight` value in [styles.ts](https://github.com/Expensify/App/blob/main/src/styles/styles.ts) for:

1. [.textHeadline](https://github.com/Expensify/App/blob/main/src/styles/styles.ts#L413) → [variables.lineHeightXXXLarge](https://github.com/Expensify/App/blob/main/src/styles/variables.ts#L102);
2. [.optionDisplayName](https://github.com/Expensify/App/blob/main/src/styles/styles.ts#L1544) → [variables.lineHeightXXLarge](https://github.com/Expensify/App/blob/55903d45103ad446cb891dd1099d4e1dd7ea1ec1/src/styles/variables.ts#L101);
3. [.optionAlternateText](https://github.com/Expensify/App/blob/main/src/styles/styles.ts#L1565) → [variables.lineHeightXXLarge](https://github.com/Expensify/App/blob/55903d45103ad446cb891dd1099d4e1dd7ea1ec1/src/styles/variables.ts#L101);
4. [.chatItemMessageHeaderSender](https://github.com/Expensify/App/blob/main/src/styles/styles.ts#L1690) → [variables.lineHeightXXLarge](https://github.com/Expensify/App/blob/55903d45103ad446cb891dd1099d4e1dd7ea1ec1/src/styles/variables.ts#L101);
5. [.tabText](https://github.com/Expensify/App/blob/55903d45103ad446cb891dd1099d4e1dd7ea1ec1/src/styles/styles.ts#L3614C37-L3614C37) → (*set*) `14`.

Increase `lineHeight` value in [ReportPreview.js](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/ReportPreview.js#L246) for preview message to [variables.lineHeightXXLarge](https://github.com/Expensify/App/blob/55903d45103ad446cb891dd1099d4e1dd7ea1ec1/src/styles/variables.ts#L101).

Once we increase the `lineHeights`, text has enough place to render from the smallest to largest font sizes.

### What alternative solutions did you explore? (Optional) 
N/A

**Comment by rezkiy37** [comment] 2023-12-15 14:30
Waiting on review for a [proposal](https://github.com/Expensify/App/issues/26044#issuecomment-1853819468) above.

**Comment by rezkiy37** [comment] 2023-12-18 10:04
@fedirjh, who can review the [proposal](https://github.com/Expensify/App/issues/26044#issuecomment-1853819468)?

**Comment by arosiclair** [comment] 2023-12-19 13:50
Weird how the Internal assigner did not assign an engineer [here](https://github.com/Expensify/App/issues/26044#issuecomment-1732534258). Let's go with the proposal anyway.

**Comment by arosiclair** [comment] 2023-12-19 13:52
Looks like you're actually already assigned @rezkiy37 so feel free to post your PR 👍

**Comment by paultsimura** [comment] 2023-12-19 13:58
There was quite a similar issue regarding centering and chopping off tops of emojis: https://github.com/Expensify/App/issues/32283#issuecomment-1835759361

It was closed as non-important, but @tienifr posted quite a similar [proposal](https://github.com/Expensify/App/issues/32283#issuecomment-1835759361) 2 weeks before the one selected here.

Just a heads-up: @jjcoffee @slafortune

**Comment by jjcoffee** [comment] 2023-12-19 14:11
Good spot! I don't have a strong opinion on whether or not this one should be closed too but it has been open for far longer and deals with it more broadly across the app. We should definitely make sure to fix the issue with the emoji picker too, if it's not already on the cards cc @rezkiy37  (see https://github.com/Expensify/App/issues/32283).

**Comment by rezkiy37** [comment] 2023-12-19 15:03
So, I've prepared a [PR](https://github.com/Expensify/App/pull/32818). Please take a look 🙂

**Comment by rezkiy37** [comment] 2023-12-22 14:01
Guys, I am having a vacation till the 4th January. So, I will be OOO within this period.

**Comment by arosiclair** [comment] 2023-12-25 19:36
> Guys, I am having a vacation till the 4th January. So, I will be OOO within this period.

That should be fine. @fedirjh can you review the PR in the meantime?

**Comment by situchan** [comment] 2023-12-27 16:38
There's [regression](https://github.com/Expensify/App/issues/33647) from linked [PR](https://github.com/Expensify/App/pull/32818)

**Comment by johncschuster** [comment] 2024-01-05 01:32
Looks like I need to manually create the Upwork job since it wasn't automatically created. We were _just_ [discussing a new process for this](https://expensify.slack.com/archives/C01SKUP7QR0/p1704306657202619) today. I'll follow the process there and get this paid out.

**Comment by johncschuster** [comment] 2024-01-08 19:38
# Payment Summary
@fedirjh requires payment by manual request of $1000 
@rezkiy37 does not require payment (Contractor)
@DinalJivani requires payment by manual request of $1000

**Comment by situchan** [comment] 2024-01-08 19:41
There was [regression](https://github.com/Expensify/App/issues/33647)

**Comment by DinalJivani** [comment] 2024-01-09 09:34
@johncschuster 
Can you please create Upwork job and send me offer?

**Comment by johncschuster** [comment] 2024-01-16 21:14
@DinalJivani, I invited you to the Upwork job. Can you please accept that so I can issue payment for the bug report?

**Comment by DinalJivani** [comment] 2024-01-16 21:16
@johncschuster 
You sent offer for $50 instead of $250. This is old bug report.

**Comment by DinalJivani** [comment] 2024-01-16 21:23
@johncschuster 
I had just accepted offer. Please approve $250 reporting bonus. 

Thanks

**Comment by johncschuster** [comment] 2024-01-23 20:11
> You sent offer for $50 instead of $250. This is old bug report.

@DinalJivani sorry about that. I just double-checked when the reporting bonus change was made, and I see it was August 30, while this was reported on August 17th. I've issued the corrected amount of $250.

**Comment by johncschuster** [comment] 2024-01-23 20:12
> @johncschuster Could you please invite me as well? I am already ineligible for the manual requests.

Sure thing, @fedirjh, I'll invite you now.

**Comment by johncschuster** [comment] 2024-01-24 16:21
Payment has been issued! Thanks everyone!

**Closed by johncschuster** 2024-01-24 16:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
