### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] mWeb - Members - When last member leaves the group, user is not prompted with a warning message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42204] opened 2024-05-15 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4566310
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home

2. Tap start chat
3.  Select a user and create group
4. Send few messages
5. Tap header -- member
6. Select one member listed and remove the member
7. Tap back
8. Tap Leave group

## Expected Result:
When last member leaves the group, user must be prompted with a warning message

## Actual Result:
When last member leaves the group, user is not prompted with a warning message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cef8bacb-1786-4fe7-a087-21c655900421

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108d139f0fc936c57</li>
        <li>Upwork Job ID: 1790901683068096512</li>
        <li>Last Price Increase: 2024-05-16</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment] 2024-05-15 18:10
We think that this bug might be related to #vip-vsp

**Comment by greg-schroeder** [comment] 2024-05-16 00:01
Checking if we should handle [here](https://github.com/Expensify/App/issues/40256) before applying External

**Comment by greg-schroeder** [comment] 2024-05-16 00:26
Looks like they want to solve this separately, so let's keep it here. Going to add `External`

**Comment by mananjadhav** [comment] 2024-05-16 20:31
Overall all proposals have similar ideas on fixing this, but I found @tienifr's proposal comprehensive. 

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2024-05-21 23:18
@dangrous quick bump

**Comment by greg-schroeder** [comment] 2024-05-21 23:21
Thanks @mananjadhav you were 3 minutes ahead of me!

**Comment by dangrous** [comment] 2024-05-22 13:44
Thanks for your patience! I'm still on my 40% schedule so a bit slow. I agree with @mananjadhav's assessment, assigning to @tienifr!

**Comment by mananjadhav** [comment] 2024-06-11 21:26
I couldn't pinpoint to the exact PR for this one, but I feel we should add a regression test for this one. The test steps from the PR looks fine to me.

1. Open app
2. Tap start chat
3. Select a user and create group
4. Send few messages
5. Tap header -- member
6. Select one member listed and remove the member
7. Tap back
8. Tap Leave group
9. When last member leaves the group, user must be prompted with a warning message.

**Comment by greg-schroeder** [comment] 2024-06-13 22:29
Processing

**Comment by greg-schroeder** [comment] 2024-06-13 22:31
Payment summary:

Contributor: @tienifr - $250 - Paid via Upwork
C+: @mananjadhav - $250 - You can make a manual request

**Comment by greg-schroeder** [comment] 2024-06-13 22:33
Regression test filed, closing

**Closed by greg-schroeder** 2024-06-13 22:32 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-14 03:09
$250 approved for @mananjadhav
