### ISSUE TITLE
[$125] "No results found" text is not aligned to left edge

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37984] opened 2024-03-08 15:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709846865518079

## Action Performed:
1. Open app
2. Click on search 
3. Type some random text which will give "No results found" message
4. Verify the alignment with left edge

## Expected Result:
Should be aligned with left edge

## Actual Result:
Not aligned with left edge

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-03-07 at 16 27 53@2x](https://github.com/Expensify/App/assets/38435837/036c1b54-a4e9-48e6-a59f-e5c5a86034c7)

![Screen Shot 2024-03-08 at 10 43 18 AM](https://github.com/Expensify/App/assets/38435837/2e67b226-d403-4a31-9988-289ebdef3a80)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019fd4e434eac176f9</li>
        <li>Upwork Job ID: 1766288950642847744</li>
        <li>Last Price Increase: 2024-03-16</li>
<li>Automatic offers: </li>
<ul>
<li>brandonhenry | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by shawnborton** [comment] 2024-03-08 15:50
@greg-schroeder just a note that we want to make the bounty on this one super small given that it's such a tiny change.

**Comment by greg-schroeder** [comment] 2024-03-13 10:52
Proposal review

**Comment by greg-schroeder** [comment] 2024-03-17 08:23
Bump @allroundexperts

**Comment by allroundexperts** [comment] 2024-03-17 11:55
Thanks for the proposals everyone. I think I'd go with @brandonhenry's [proposal](https://github.com/Expensify/App/issues/37984#issuecomment-1986714516) since it gives us the flexibility to handle more edge cases like this in the future.

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2024-03-17 12:27
> @allroundexperts , No conflict with your chosen proposal but can i ask what did my [proposal](https://github.com/Expensify/App/issues/37984#issuecomment-1985978048) lack, I guess i proposed a similar solution:)
> 
> thanks

From my understanding, your proposal was lacking where to put the changes.

**Comment by allroundexperts** [comment] 2024-03-21 19:43
Thanks for the proposals everyone. I think I'd go with @brandonhenry's [proposal](https://github.com/Expensify/App/issues/37984#issuecomment-1986714516) since it gives us the flexibility to handle more edge cases like this in the future.

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2024-03-21 19:50
🎀 👀 🎀 C+ reviewed

**Comment by nayabatir1** [comment] 2024-03-22 20:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "No results found" text in the search page is not aligned with the left edge of the search input. We want the "No results found" text to have the same left padding as the search input for consistency.

### What is the root cause of that problem?
In `BaseSelectionList` padding is `pb5` but when input label is `Name, email, or phone number` it should be `pb4`.
I like @brandonhenry [proposal](https://github.com/Expensify/App/issues/37984#issuecomment-1986714516) but we can do the same inside `BaseSelectionList` without passing additional props.
Requesting @allroundexperts to check this once

### What changes do you think we should make in order to solve the problem?
```js
<View style={textInputLabel === translate('optionsSelector.nameEmailOrPhoneNumber') ? [styles.ph4, styles.pb5] : [styles.ph5, styles.pb5]}>
    <Text style={[styles.textLabel, styles.colorMuted]}>{headerMessage}</Text>
</View>
```

### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment] 2024-03-25 15:11
> @allroundexperts, it seems like @GandalfGwaihir did correctly identify the RCA first; given the bug is purely UI, I think we can go with the first correct proposal. What do you think? Is there another reason you'd like to go with @brandonhenry's solution?

@grgia Although @GandalfGwaihir did identify the RCA first, I think there proposal was lacking the place where to add the required changes. Given how straightforward this bug was, I think the minor details should have been thought off here. Final call is yours though.

**Comment by grgia** [comment] 2024-03-26 09:42
> Although @GandalfGwaihir did identify the RCA first, I think there proposal was lacking the place where to add the required changes. Given how straightforward this bug was, I think the minor details should have been thought off here. Final call is yours though.


@GandalfGwaihir I'm going to go with @allroundexperts's choice for this PR given their reasoning. But I am happy to help you find a similar issue to work on.

**Comment by greg-schroeder** [comment] 2024-03-27 03:33
Adding to #vib-vsb per https://expensify.slack.com/archives/C01SKUP7QR0/p1711491618714289

**Comment by nayabatir1** [comment] 2024-04-01 04:10
Requesting general feedback from @allroundexperts @grgia 

I've suggested an alternate approach to this issue without passing any additional props. Could please let me know why passing additional props is preferrable choice. I understand if its too late for proposal review. Just want to understand coding style here.

[Link](https://github.com/Expensify/App/issues/37984#issuecomment-2015841063)

**Comment by mallenexpensify** [comment] 2024-04-01 17:27
@brandonhenry per [CONTRIBUTING.md,](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md?rgh-link-date=2024-04-01T17%3A24%3A34Z#:~:text=New%20contributors%20are%20limited%20to%20working%20on%20one%20job%20at%20a%20time%2C%20however%20experienced%20contributors%20may%20work%20on%20numerous%20jobs%20simultaneously.)

> New contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously.

You currently have [6 issues open](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+assignee%3Abrandonhenry+) with non merged or closed. Please do not submit proposals for new issues until **all** six PRs have been merged.

Also [from CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md?rgh-link-date=2024-04-01T17%3A24%3A34Z#:~:text=Daily%20updates%20on,original%20contract%20terminated.)

> Daily updates on weekdays are highly recommended. If you know you won’t be able to provide updates within 48 hours, please comment on the PR or issue stating how long you plan to be out so that we may plan accordingly. We understand everyone needs a little vacation here and there. Any issue that doesn't receive an update for 5 days (including weekend days) may be considered abandoned and the original contract terminated.

Please keep the issue and PR moving along with urgency, along with all others.

**Comment by greg-schroeder** [comment] 2024-04-05 21:34
@brandonhenry I only see a Closed PR linked to this issue - can you link the one that was merged?

**Comment by greg-schroeder** [comment] 2024-04-15 02:06
Payment summary:

@brandonhenry $125
@allroundexperts $125 

Sibtain you can make a manual request, and then if you could take care of the checklist we can close this out tomorrow!

**Comment by allroundexperts** [comment] 2024-04-15 14:00
## Checklist
1. I was not able to pinpoint the exact PR that caused this. It looks like that the issue existed since the time we created the `SearchPage`.
2. N/A
3. N/A
4. I think a regression test would be an overkill here. If we disagree, then the steps given in the OP look clear enough to me.

**Comment by shawnborton** [comment] 2024-04-25 15:15
Hmm it looks like this still isn't aligned properly:
![CleanShot 2024-04-25 at 11 15 09@2x](https://github.com/Expensify/App/assets/2319350/334452bf-6944-4254-bcdb-5bd111bd1939)

**Comment by shawnborton** [comment] 2024-04-25 15:15
Thoughts @brandonhenry ?

**Comment by greg-schroeder** [comment] 2024-04-26 19:27
Uh oh, is there a regression issue or should we just handle here?

**Comment by grgia** [comment] 2024-04-29 12:20
Is the root issue the same? Are we not using the same component for these two inputs?

**Comment by shawnborton** [comment] 2024-04-29 12:25
Yeah, apologies if we didn't make it clear in the issue but ideally this is solved everywhere as to me, this feels like the same kind of component/UX.

**Comment by greg-schroeder** [comment] 2024-05-09 05:16
PR remains in progress/review w/ @shawnborton

**Comment by shawnborton** [comment] 2024-05-09 11:32
The PR above looks good to me, but now we need a C+ to run through the checklist. Will comment on the PR too.

**Comment by greg-schroeder** [comment] 2024-05-15 08:57
PR looks all green, we should be ready to merge eh?

**Comment by shawnborton** [comment] 2024-05-15 15:10
Just merged, sorry about that!

**Comment by greg-schroeder** [comment] 2024-05-22 00:18
Merged. Awaiting deploy to staging -> prod

**Comment by mallenexpensify** [comment] 2024-06-14 21:32
Looks like this hit production 3 weeks ago 
- https://github.com/Expensify/App/pull/41221#issuecomment-2133551778 

Looks like you were auto-paid @brandonhenry cuz you were hired on a milestone. 
<img width="407" alt="image" src="https://github.com/Expensify/App/assets/22508304/f74b2e68-8c6b-49ad-a206-1ccde0a7b976">

@greg-schroeder , I removed `Reviewing`, can you wrap this up? thx

**Comment by greg-schroeder** [comment] 2024-06-17 21:33
Ah, sorry folks, the automation didn't run, so my tracking didn't pick up payment pending

**Comment by greg-schroeder** [comment] 2024-06-17 21:34
Payment summary:

Contributor: @brandonhenry - $125 - paid via upwork
C+: @allroundexperts - $125 - ND Manual Request


cc @JmillsExpensify

**Closed** 2024-06-17 21:35 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-17 22:46
$125 approved for @allroundexperts
