### ISSUE TITLE
[HOLD for payment 2023-06-07] [$1000] Center QR image turns into difference avatar for a moment after being removed.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19211] opened 2023-05-18 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login app in 2 tabs.
2. From the first tab open Share QR image, from second tab, try to remove the user avatar.
3. Observe the center Qr image.

## Expected Result: 
Center QR image should turn into default avatar.
## Actual Result:  
Center QR image turns into difference avatar for a moment after being removed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a302efae-5afa-4663-b72c-90819fb4b617

https://github.com/Expensify/App/assets/43996225/9ee5aee9-3624-4a2e-93b5-37536c122514

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684249640364239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e69cb0f1402572c0</li>
        <li>Upwork Job ID: 1659379434933579776</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-05-19 02:04
Reproduced in Chrome:

https://github.com/Expensify/App/assets/59587260/f27322bd-2353-4982-8f5e-9f29d63f63ad

**Comment by tgolen** [comment] 2023-05-22 10:59
I think we can go ahead and make that update. I don't think there is any reason to keep using the old avatar.

**Comment by grgia** [comment] 2023-05-22 13:05
The old avatar is required in order to update the avatar only on both Old and New Dot. On Old dot we do not use our new default avatar designs

**Comment by grgia** [comment] 2023-05-22 13:09
To illustrate:
<img width="292" alt="image" src="https://github.com/Expensify/App/assets/38015950/98a48013-1a59-4ccc-821d-ef1196840f29">

vs 
<img width="274" alt="image" src="https://github.com/Expensify/App/assets/38015950/8419dd13-07e7-48d4-9e9c-547c9c4d2f63">

To support both platforms, we set the default avatar URL for Old Expensify whereas in New Expensify we calculate which one to show at render

**Comment by tgolen** [comment] 2023-05-23 08:24
OK, what updates to the proposal need to be made? Is it just a matter of changing the reference in the optimistic data?

**Comment by tgolen** [comment] 2023-05-24 08:38
OK, thanks! @kadiealexander you have the 🟢 to hire @hoangzinh 

@hoangzinh you can create the PR as soon as you're ready 👍

**Comment by kadiealexander** [comment] 2023-05-25 02:52
@tgolen the assigned engineer assigns in Github, that doesn't need to wait for me. I'll ensure the Upwork contracts get sent and everyone gets paid 😊

**Comment by tgolen** [comment] 2023-05-25 07:48
Cool, I didn't know about that. I'll try to remember it in the future. Thanks!

**Comment by tgolen** [comment] 2023-05-31 04:04
Unfortunately, I need to reassign this due to going on extended leave.

**Comment by kadiealexander** [comment] 2023-06-07 05:34
May 25th 2:50pm (GMT+12) - Thursday
May 29th 5:32pm (GMT+12) - Monday

PR was merged within 3 business days, eligible for speed bonus.

**Comment by kadiealexander** [comment] 2023-06-07 05:48
Contracts sent to all, @fedirjh please don't forget about [the checklist](https://github.com/Expensify/App/issues/19211#issuecomment-1570525529)!

**Comment by kadiealexander** [comment] 2023-06-08 06:12
Thanks @fedirjh! Everyone is paid so I'm closing this out. Great work team!

**Closed by kadiealexander** 2023-06-08 06:12 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
