### ISSUE TITLE
Bug: shows add account number page for a second while click on  connect bank account reported by @gadhiyamanan 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11843] opened 2022-10-14 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to workspace> issue cards >connect bank account > connect manually
2. Go back to previous screens
3. Again click on issue cards > connect account

## Expected Result:
it should show connect with plaid or connect manually option

## Actual Result:
shows add account and routing number screen for a second

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.15-2
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195870360-bf0bad1b-ce6f-4561-9775-8e7b990d06dc.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665428453776049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment] 2022-10-21 10:54
Reviewing this now.

**Comment by isabelastisser** [comment] 2022-10-21 11:15
I'm unable to reproduce it! @kavimuru @gadhiyamanan

**Comment by gadhiyamanan** [comment] 2022-10-21 11:21
@isabelastisser still able to reproduce v1.2.16-5(production)
https://user-images.githubusercontent.com/54790231/197184527-6233ea92-d3b6-4c32-bfae-9aa512e7a022.mp4

**Comment by isabelastisser** [comment] 2022-10-23 00:59
I'm still unable to reproduce it. @kavimuru @gadhiyamanan 


https://user-images.githubusercontent.com/31258516/197368088-6b33b628-54e6-4230-acd6-9b278c04cfbe.mp4

**Comment by kavimuru** [comment] 2022-10-24 15:43
@isabelastisser I am not able to reproduce too. Only @gadhiyamanan is able to reproduce.

**Comment by isabelastisser** [comment] 2022-10-25 09:55
Hey @gadhiyamanan, I'm still unable to reproduce it on mobile or the web, so I'm closing this issue. Please reopen if you need me to review this further. Thanks!

**Closed by isabelastisser** 2022-10-25 09:55 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
