### ISSUE TITLE
[Hold for Payment 08-30-23][$1000] Web - There is a delete option on a reply inside IOU report screen on the receiver's side

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23805] opened 2023-07-28 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a money request from account A to account B
2. Open the IOU report by clicking on the IOU preview on both account A and account B
3. Send a reply from account B
4. Hover over the sent reply from account A

## Expected Result:
There should be no delete icon on account A

## Actual Result:
Account A can see and click the delete button on the reply sent from account B. And if user A deletes the message Auth error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/45f173cc-15c2-4e90-8cf3-8683d47100e8

https://github.com/Expensify/App/assets/93399543/3fe01304-485b-4e29-bcb3-a743f3824f2c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690539901030749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7d728393a99ac94</li>
        <li>Upwork Job ID: 1686409939086225408</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>huzaifa-99 | Contributor | 26056682</li>
<li>Nathan-Mulugeta | Reporter | 26056686</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-08-01 16:13
Thanks for the report, the video makes this issue really clear 👍

**Comment by nickshuttle** [comment] 2023-08-01 21:32
Proposal
Please re-state the problem that we are trying to solve in this issue.
We want to hide the delete icon in the mini context menu for user A if the message was sent from user B.

What is the root cause of that problem?
In https://github.com/Expensify/App/pull/18735, we added the feature for policy admins to delete any message in workspace rooms, which displayed the delete icon to workspace admins.

Now when we request money from a user (in 1-1 or group chat), the requestor (User A) becomes the policy admin (policy.role === admin) for the money request. When the requestee (User B) replies to the money request action inside a thread, [this](https://github.com/Expensify/App/blob/b2381f6c60acd4beca34b83c65a898eefb0594d6/src/libs/ReportUtils.js#L280) condition becomes true for User A and shows the delete icon for User A

What changes do you think we should make in order to solve the problem?
Plan of action:
- Break up canDeleteReportAction into two clear usage utils. One for Delete as action owner and one for Delete with admin rights.
- For action owner no changes needed.
- For Admin we can block list certain report types from the check, example: Utilize isMoneyRequestReport to ensure admin access is ignored if the report is a money request type.

You can either do the block list as part of the admin until or pair it with another util. Example: (canDeleteReportActionWithAdmin && !isMoneyRequestReport)

What alternative solutions did you explore? (Optional)
Alternatively, you could look above in this thread for other options but I think those are blocking access on too wide of a scale. It may/may not be the case that we want to block admin deletes on ALL dms but it is the case we want to block it on IOU types.

Also - Regardless of solution breaking that canDeleteReportAction is vital to avoid running into this issue with another type down the line. It's just not clear to both have admin and owner rights checked in the same function like this.

**Comment by nickshuttle** [comment] 2023-08-01 21:42
Contributor details
Your Expensify account email: work.shuttleworth@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01860966a7fc3f0688

**Comment by mananjadhav** [comment] 2023-08-03 05:36
Thanks for the proposals folks. Both the proposals have the correct RCA, I don't like the idea of splitting `canDeleteReportAction`, as if we have more cases in the future, we wouldn't want to create than many utils. 

Hence, @huzaifa-99's proposal [here](https://github.com/Expensify/App/issues/23805#issuecomment-1655953806) looks good to me. @huzaifa-99 I think it makes sense to use existing utils if we have any. But please note, I'll check with the BZ team member which all accesses should block the Delete action, and we should cover all of them in the current scope.

@sakluger Can you confirm the types of chat/report, etc. where we want to hide the Delete option? I can see this bug report [too](https://expensify.slack.com/archives/C049HHMV9SM/p1690989018741129). 

🎀 👀 🎀  C+ reviewed.

**Comment by nickshuttle** [comment] 2023-08-03 07:23
> Thanks for the proposals folks. Both the proposals have the correct RCA, I don't like the idea of splitting `canDeleteReportAction`, as if we have more cases in the future, we wouldn't want to create than many utils.
> 
> Hence, @huzaifa-99's proposal [here](https://github.com/Expensify/App/issues/23805#issuecomment-1655953806) looks good to me. @huzaifa-99 I think it makes sense to use existing utils if we have any. But please note, I'll check with the BZ team member which all accesses should block the Delete action, and we should cover all of them in the current scope.
> 
> @sakluger @MonilBhavsar Can you confirm the types of chat/report, etc. where we want to hide the Delete option? I can see this bug report [too](https://expensify.slack.com/archives/C049HHMV9SM/p1690989018741129).
> 
> 🎀 👀 🎀 C+ reviewed.

I understand to some degree. However, the place this is being called already calls many utils. You know the code base far better than me but it seems like having utils with understandable outcomes is going to serve the future devs much better than a single method with many rules inside it that are murky.

`shouldShow: (type, reportAction, isArchivedRoom, betas, menuTarget, isChronosReport, reportID) =>
            // Until deleting parent threads is supported in FE, we will prevent the user from deleting a thread parent
            type === CONTEXT_MENU_TYPES.REPORT_ACTION &&
            ReportUtils.canDeleteReportAction(reportAction, reportID) &&
            !isArchivedRoom &&
            !isChronosReport &&
            !ReportActionUtils.isMessageDeleted(reportAction),`
         
These overloaded && checks like this scare me. I really would figure out how to refactor this into something not so fragile to where the menu is being loaded up. 

Anyway - Thank you for looking everything over.

**Comment by mananjadhav** [comment] 2023-08-03 07:44
I agree with your points @nickshuttle. It works both ways. One having these large overloaded conditions can be daunting and definitely affect the readability, but having the same utils created based on different thread types would add to the code smells. Better way would be to split these conditions into context based flags, which then make the util more readable.

**Comment by nickshuttle** [comment] 2023-08-03 14:14
@mananjadhav - Yeah, I understand. It's one of those things where you are stuck between things. The way it is already has code smell (Conditional Complexity) but not done correctly refactoring could put a new code smell into place.

The approach right now is going to build on top of that complexity with no clear call out for the next developer. If you don't break it, I really would suggest finding a way to make it super clear to the next developer that there are XYZ conditions being checked. Once you add policy admin === true && (thisChat === true || thatChat === true) it's gonna get weird the next time some new message type needs to make this choice.

Really, if you were up to bigger changes there could be a better approach where you could created some sort of rules engine instead of this direct checks on different states. That would allow for finer grained control in a much more testable/maintainable way.

**Comment by sakluger** [comment] 2023-08-05 01:19
> @sakluger @MonilBhavsar Can you confirm the types of chat/report, etc. where we want to hide the Delete option? I can see this bug report [too](https://expensify.slack.com/archives/C049HHMV9SM/p1690989018741129).

In both this case and the one you linked, a user is able to delete someone else's message/request. In general, a user should never be able to delete someone else's message or request. You should only be able to delete something that you created yourself.

There may be other places where the delete button isn't appropriate, but I can't think of them at the moment.

**Comment by MonilBhavsar** [comment] 2023-08-07 11:04
> In both this case and the one you linked, a user is able to delete someone else's message/request. In general, a user should never be able to delete someone else's message or request. You should only be able to delete something that you created yourself.


> Maybe we should still allow the original intent and fix other cases where the user can delete someone else's msg?

Agree 👍

**Comment by sakluger** [comment] 2023-08-07 20:16
Ah, so are you saying that we should allow admins to delete messages from other users, but not requests? Or are you saying that admins should be able to delete both messages and requests from other users?

**Comment by MonilBhavsar** [comment] 2023-08-08 09:54
I think we should allow users to delete comment following this issue https://github.com/Expensify/App/issues/18727
For requests, I don't think we should allow anyone to delete the request, as it be rejected, if it's inappropriate

**Comment by neil-marcellini** [comment] 2023-08-09 17:20
I agree with [the plan](https://github.com/Expensify/App/issues/23805#issuecomment-1669300833) from Monil.

**Comment by neil-marcellini** [comment] 2023-08-10 15:50
Oh thanks I missed that. I'll review it soon.

**Comment by mananjadhav** [comment] 2023-08-10 16:53
I think @huzaifa-99's proposal stands valid, and we can work out other changes in the PR.

**Comment by neil-marcellini** [comment] 2023-08-10 19:28
@huzaifa-99's [proposal](https://github.com/Expensify/App/issues/23805#issuecomment-1655953806) looks good to me too 🚀

**Comment by mananjadhav** [comment] 2023-08-25 18:20
This was deployed on production 2 days ago but the title wasn't updated.

**Comment by mananjadhav** [comment] 2023-08-31 14:34
@sakluger This was deployed to production for 7 days but the title wasn't updated. Can you please post the payout summary?

@neil-marcellini I think this is eligible for the timeline bonus, as C+ review was done within the 3 days.

**Comment by mananjadhav** [comment] 2023-09-04 16:22
@neil-marcellini @sakluger quick bump on the previous comments.

**Comment by mananjadhav** [comment] 2023-09-07 18:50
@neil-marcellini @sakluger another follow up.

**Comment by sakluger** [comment] 2023-09-07 20:15
Sorry for the delay! Yes, I reviewed the PR and this one qualifies for the bonus because it was C+ approved well within the allowed time.

**Summarizing payouts for this issue:**

Reporter: @Nathan-Mulugeta - $250 (paid on Upwork)
Contributor: @huzaifa-99 $1500 (hired on Upwork)
Contributor+: @mananjadhav $1500 (payable via Manual Request)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~01b7d728393a99ac94

@huzaifa-99 could yuu please accept the offer in Upwork so that we can complete the payment? Thanks!

**Comment by mananjadhav** [comment] 2023-09-07 20:18
Thanks @sakluger. Appreciate your help here.

**Comment by Nathan-Mulugeta** [comment] 2023-09-07 20:29
Hey @sakluger I didn't receive any payments yet. You might have paid wrong person?

**Comment by Nathan-Mulugeta** [comment] 2023-09-07 20:41
Just received the payment thanks.

**Comment by sakluger** [comment] 2023-09-08 03:12
Phew, glad you go the payment @Nathan-Mulugeta!

@mananjadhav did you send the payment request in NewDot? Would you like me to leave the issue open until you've done that, or will you track and handle outside the issue?

**Comment by mananjadhav** [comment] 2023-09-08 03:51
Yes @sakluger. I've raised the payout request on NewDot.

I'll track this outside the issue. cc - @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2023-09-10 11:44
$1,500 approved for payment via NewDot based on BZ summary.

**Comment by sakluger** [comment] 2023-09-11 16:04
Thanks everyone!

**Closed by sakluger** 2023-09-11 16:04 UTC
Labels: Reviewing, External, Daily, Bug
