### ISSUE TITLE
[NEEDS REPRO] Empty report preview with $0 shows up

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35364] opened 2024-01-30 09:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @luacmartins 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706197156247149

## Action Performed:
1. create money request with workspace chat
2. Observe the report preview
## Expected Result:
Should display report details
## Actual Result:
empty report preview with $0 shows up
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-01-25 at 8 38 38 AM](https://github.com/Expensify/App/assets/43996225/8dcfe9a5-6a18-4d32-9b2d-b664862917da)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6cd970bf69b48e4</li>
        <li>Upwork Job ID: 1762493211753984000</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2024-01-30 09:43
Unable to repro, have asked Carlos for more info

**Comment by jliexpensify** [comment] 2024-02-01 02:28
Carlos thinks it's related to: https://github.com/Expensify/App/issues/34948

**Comment by jliexpensify** [comment] 2024-02-01 02:29
Hi @marcochavezf - going to assign this one to you as well as Carlos thinks the 2 are related!

**Comment by marcochavezf** [comment] 2024-02-09 16:43
The other issue also was not reproducible too 😄 I'm going to apply the `retest-weekly`

**Comment by jliexpensify** [comment] 2024-02-13 04:39
Hey @marcochavezf do I ened to do anything here? Does Applause test this?

**Comment by marcochavezf** [comment] 2024-02-13 20:34
Seems that only the label is needed for Applause to retest it. If it's not reproducible in three weeks the issue is closed https://expensify.slack.com/archives/C01SKUP7QR0/p1705698135329489, I will move it to weekly again

**Comment by marcochavezf** [comment] 2024-02-20 16:59
Moving to weekly again since the `retest-weekly` is added

**Comment by mvtglobally** [comment] 2024-02-21 02:23
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-02-27 15:06
Issue not reproducible during KI retests. (Second week)

**Comment by luacmartins** [comment] 2024-02-27 15:55
I think we can close this. Please reopen if the issue happens again.

**Closed by luacmartins** 2024-02-27 15:55 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Bug, retest-weekly

**Comment by jliexpensify** [comment] 2024-02-28 01:37
Removed Upworks job
