### ISSUE TITLE
[$250] Receipt fails to upload when smart scanned and typo in error message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48740] opened 2024-09-06 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-11
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725645046337449

## Action Performed:
1.Launch the app and login
2.Submit an expense by smartscanning
## Expected Result:
Receipt uploaded and no typo in error messages
## Actual Result:
Receipt fails to upload and No space before `Download the file` on the error message. No error message displayed desktop (For failed upload)
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_7756](https://github.com/user-attachments/assets/e1d3894c-dddc-4de8-989f-dd307bbfbb68)

![image (7)](https://github.com/user-attachments/assets/99e46c04-5201-456f-994c-2313d027f734)

![IMG_1622](https://github.com/user-attachments/assets/40bf2662-92c2-4003-8ac0-8cb25aa097af)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833220161234377162</li>
        <li>Upwork Job ID: 1833220161234377162</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103975547</li>
<li>Nodebrute | Contributor | 103975549</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by etCoderDysto** [comment] 2024-09-06 19:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt fails to upload when smart scanned and typo in error message
### What is the root cause of that problem?
We are not adding a space after `Localize.translateLocal('iou.error.receiptFailureMessage')`
https://github.com/Expensify/App/blob/342b1d51f966a5f9fa9a2f6103c3eb8463f938e0/src/components/DotIndicatorMessage.tsx#L71-L79
### What changes do you think we should make in order to solve the problem?
We should add space after `Localize.translateLocal('iou.error.receiptFailureMessage')`
```
{`${Localize.translateLocal('iou.error.receiptFailureMessage')}+" "`}
```
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-09-15 09:53
@allgandalf Adding aspace after `.` in [en.ts](https://github.com/Expensify/App/blob/8b348c6049eafe9089bb49d339a68b5e7d423d06/src/languages/en.ts#L866) will add space in every usage of the copy. And it seems we only want to add the space when another translation comes after it. Don't you think it is better to add the space where the copy is followed by another copy or translation  as [my proposal](https://github.com/Expensify/App/issues/48740#issuecomment-2334717617) suggests?

cc: @luacmartins

**Comment by cead22** [comment] 2024-09-16 07:59
I don't know if these proposals make sense. The main issue is the receipt failing to upload. The issue with the typo in the error message is secondary.

If we're only gonna solve the typo, let's log a different issue that only talks about the typo. The main issue to solve is the smartscan upload failing

**Comment by cead22** [comment] 2024-09-17 09:51
I know. The receipt uploaded and SmartScanned, and I still got an error in New Dot, which made me think this is a front end issue

**Comment by cead22** [comment] 2024-09-19 09:36
No, I just uploaded a receipt and it worked fine. And I don't have repro steps, so I'm gonna close this

**Closed by cead22** 2024-09-19 09:36 UTC
Labels: External, Daily, Bug
