### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] Import categories - Dropdown button does not match the selection in the dropdown list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50312] opened 2024-10-06 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh0410009@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click 3-dot menu > Import spreadsheet.
4. Upload a csv containing two column data.
5. Click on the dropdown of the first item.

## Expected Result:
The selection in the dropdown should match what is displayed on the dropdown button.

## Actual Result:
The dropdown button shows "Enabled", but the selection in the dropdown is "Ignore".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6626304_1728235057248!Screenshot_2024-10-07_at_01 12 42" src="https://github.com/user-attachments/assets/e5e6833b-0ecc-416b-a5cc-956f419e61b7">

https://github.com/user-attachments/assets/48118e97-396a-46ef-a88e-e1e98b26c949

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843456236485457533</li>
        <li>Upwork Job ID: 1843456236485457533</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 104404493</li>
<li>Nodebrute | Contributor | 104404495</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by IuliiaHerets** [comment] 2024-10-06 19:13
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-10-06 19:13
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-10-07 09:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Import categories - Dropdown button does not match the selection in the dropdown list

### What is the root cause of that problem?

This bug happens with the column that returns the columnName as `empty` in the default case [here](https://github.com/Expensify/App/blob/7981265dc14bc9cb99b512baddbb027446568fcf/src/components/ImportColumn.tsx#L114-L116) 

It leads the `defaultSelectedIndex` to be `-1` which causes the display text in the dropdown button to be different from the selected option in the drop-down menu
https://github.com/Expensify/App/blob/7981265dc14bc9cb99b512baddbb027446568fcf/src/components/ImportColumn.tsx#L165
### What changes do you think we should make in order to solve the problem?
For the default case,  we should return `CONST.CSV_IMPORT_COLUMNS.IGNORE` here instead of an empty string.

```
default:
    attribute = CONST.CSV_IMPORT_COLUMNS.IGNORE;
    break;
```
https://github.com/Expensify/App/blob/7981265dc14bc9cb99b512baddbb027446568fcf/src/components/ImportColumn.tsx#L114-L116

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-10-08 01:34
This is a wave-control project, moving.

**Comment by mkzie2** [comment] 2024-10-10 04:20
@ZhenjaHorbach Here is why I propose adding the ignore as a fallback in the `findColumnName` function.

When we import a CSV file, we save the spreadsheet data, and all column names are `ignore` by default. Then the column name will be updated based on the value in `findColumnName` function. 


https://github.com/Expensify/App/blob/f0be8a731dc0832827dbd14d23fd49b332ff275e/src/libs/actions/ImportSpreadsheet.ts#L12-L15

It will not update in the case empty string is returned because we already have the check here. But the `defaultSelectedIndex` is also used to focus and display the correct column value then it makes sense to return `ignore` by default
https://github.com/Expensify/App/blob/f0be8a731dc0832827dbd14d23fd49b332ff275e/src/components/ImportColumn.tsx#L167-L174

**Comment by mkzie2** [comment] 2024-10-14 09:30
@ZhenjaHorbach Can you please check again? We should update `findColumnName` function by returning the default value correctly instead of having a fallback like the selected proposal, it doesn't fix the RCA. I also have an explanation here

```
const defaultSelectedIndex = columnRoles.findIndex((item) => item.value === colName);
const finalIndex = defaultSelectedIndex !== -1 ? defaultSelectedIndex : columnRoles.findIndex(item => item.value === 'ignore');

```

**Comment by Nodebrute** [comment] 2024-10-14 14:03
@mkzie2, your proposal didn't work.



> @ZhenjaHorbach, @mkzie2's solution will not work. You can try importing this file in the tags import section, and you'll see that the error will still be reproducible with the GL code value. [Categories-2024-09-10 17_10_20.413.csv](https://github.com/user-attachments/files/17318395/Categories-2024-09-10.17_10_20.413.csv)

Here are the steps to test your proposal. You'll see that it doesn't fix the problem.

**Comment by Nodebrute** [comment] 2024-10-15 22:40
Pr will be ready in few hours

**Comment by kadiealexander** [comment] 2024-10-25 06:47
Reassigning for someone to handle payment as I'm OOO for the next two weeks.

**Comment by alexpensify** [comment] 2024-10-30 04:34
Payouts due: 2024-10-29

- [ ] Contributor: $250 @ZhenjaHorbach
- [ ] Reviewer: $250 @Nodebrute

Upwork job is [here](https://www.upwork.com/jobs/~021843456236485457533). Everyone has been paid in Upwork.  I'm keeping this open to complete the regression test.

**Comment by alexpensify** [comment] 2024-11-02 05:13
Not overdue

**Comment by mjasikowski** [comment] 2024-11-04 08:17
@alexpensify shall we add the `Retest Weekly` label?

**Comment by alexpensify** [comment] 2024-11-05 02:02
Other GHs have been a priority; I need to circle back here and create the regression test GH. This action wouldn't classify for a relabel.

**Comment by alexpensify** [comment] 2024-11-13 16:18
Not overdue

**Comment by alexpensify** [comment] 2024-11-23 00:19
No update

**Comment by mjasikowski** [comment] 2024-12-04 10:22
@alexpensify no update again?

**Comment by alexpensify** [comment] 2024-12-04 22:38
Closing - all set here

**Closed by alexpensify** 2024-12-04 22:38 UTC
Labels: External, Weekly, Awaiting Payment, Bug
