### ISSUE TITLE
[$500] [MEDIUM] Migrate the EmojiPickerMenu to Flashlist

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#30911] opened 2023-11-06 13:15 UTC
Part of https://github.com/Expensify/App/issues/28902

Let's migrate EmojiPickerMenu to use Flashlist component instead of FlatList

Callstack is working on the migration right now.

Lets use this issue for daily updates on this migration
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01717c0ee29a49c13a</li>
        <li>Upwork Job ID: 1757786794067501056</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by TMisiukiewicz** [comment] 2023-11-06 14:08
Hi, I'm Tomasz from Callstack, I'd like to work on that issue

**Comment by roryabraham** [comment] 2023-11-06 15:33
@TMisiukiewicz do you expect to make daily progress on this issue?

**Comment by esh-g** [comment] 2023-11-06 17:22
Related bug here: https://expensify.slack.com/archives/C01GTK53T8Q/p1699208483024949

**Comment by TMisiukiewicz** [comment] 2023-11-07 15:51
Started working on migrating the EmojiPickerMenu for web.

**Comment by TMisiukiewicz** [comment] 2023-11-08 13:35
No progress today, as I had to work on some regressions and i was investigating failing tests in LHNOptionList migration. I'm off Thursday and Friday, in case there is a need of pushing this forward before Monday, I know @vitHoracek already pinged CK team if anyone could grab this

**Comment by shubham1206agra** [comment] 2023-11-09 09:12
I think this issue is related https://github.com/Expensify/App/issues/30948

**Comment by TMisiukiewicz** [comment] 2023-11-13 17:04
Back to work on this task today and continued with migration of the web component. Working on adopting the styles to the list correctly with FlashList, since it does not support e.g. `contentContainerStyle` properties other than background and padding. 

Regarding the issue mentioned above, it proposes using `updateCellsBatchingPeriod` prop, which is unavailable in FlashList. I'd suggest implementing FlashList first, and then, if the issue still exists, fixing it with the solution available in FlashList.

**Comment by TMisiukiewicz** [comment] 2023-11-15 16:02
Some minor CSS updates and fixing scroll to index left for web, then I'll take care of mobile version

**Comment by TMisiukiewicz** [comment] 2023-11-16 15:26
Some minor things to be re-checked, I should create a PR tomorrow.

**Comment by roryabraham** [comment] 2023-12-22 18:10
PR merged after a lot of reviews. Thanks for all the iteration @TMisiukiewicz! As discussed in the PR and in [slack](https://expensify.slack.com/archives/C03UK30EA1Z/p1703268507667669?thread_ts=1703263865.501919&cid=C03UK30EA1Z), I want us to follow-up with another PR to build `ArrowLeft` and `ArrowRight` support in `useArrowKeyFocusManager` so that we can further DRY up the platform differences in `EmojiPickerMenu`. Thanks!

**Comment by roryabraham** [comment] 2023-12-23 00:31
Just marked this as a new feature instead of a bug for accounting purposes

**Comment by roryabraham** [comment] 2024-01-04 00:38
No payments or additional regression tests are needed here. However, I am still expecting a follow-up PR from @TMisiukiewicz [as referenced above](https://github.com/Expensify/App/issues/30911#issuecomment-1867952207)

**Comment by roryabraham** [comment] 2024-01-04 00:39
@TMisiukiewicz let us know when we can expect that follow-up PR (or at least, the first one for `useArrowKeyFocusManager`)

**Comment by TMisiukiewicz** [comment] 2024-01-04 07:30
hi @roryabraham I'm planning to work on that next week, as this week I had to focus on audit related stuff!

**Comment by TMisiukiewicz** [comment] 2024-01-10 14:55
I'm about to get back to this and start working on implementing `ArrowLeft` and `ArrowRight` into `useArrowKeyFocusManager`.

**Comment by roryabraham** [comment] 2024-01-10 18:55
Look forward to seeing the PR!

**Comment by TMisiukiewicz** [comment] 2024-01-12 15:46
This week I was able to adjust hook to conditionally use `ArrowLeft` and `ArrowRight` - it allows to use it only when amount of the items per row are passed to the hook. Additionally I've added a parameter that should prevent from moving to the beginning of the list when end is reached and the other way round. Currently I'm working on adjusting it on the Emoji picker, it mostly works but the current solution has some side-effects that I need  to correctly cover, gonna get back to this after the weekend

**Comment by roryabraham** [comment] 2024-01-14 05:18
Thanks for the update!

**Comment by TMisiukiewicz** [comment] 2024-01-15 16:09
I already integrated the hook with the `EmojiPickerMenu` component, I just need to fix one issue that i have when list is filtered. Once it's done I'll make one more round of tests on the picker and I'll verify if changes made to the hook did not affect other components where it is used. I should open a draft PR tomorrow

**Comment by roryabraham** [comment] 2024-01-23 21:47
@TMisiukiewicz what's the status here?

**Comment by TMisiukiewicz** [comment] 2024-01-23 21:52
@roryabraham sorry, the draft PR got stuck in our internal code review. I'll ping someone from our team and open it as soon as i get an approval

**Comment by TMisiukiewicz** [comment] 2024-01-26 12:21
PR is under C+ review 👍

**Comment by muttmuure** [comment] 2024-01-26 12:57
Great!

**Comment by alexpensify** [comment] 2024-02-02 22:14
Catching up here, looks like we are moving forward.

**Comment by roryabraham** [comment] 2024-02-05 20:37
The minor regression was not treated as a blocker, and has already been fixed.

**Comment by roryabraham** [comment] 2024-02-06 20:59
Hey @TMisiukiewicz 👋🏼 

I think there's still more we can do to DRY up the implementation between web and native. I know appreciate you helping us work through all this technical debt. A few suggestions/observations:

- On web we're using `throttle` for `filterEmojis`, on native we're using `debounce`. It seems like it should be safe to just use debounce on both platforms. Let's try setting the timeout to 200ms (which should be fast enough that you don't really notice a delay), but long enough that we're not doing a ton of extra work. In the long run (after we get the new arch + concurrent react set up), I think we'll probably want to replace most of these usages of `debounce` + `setState` with [startTransition](https://react.dev/reference/react/startTransition)
- It looks like there are some unnecessary differences between web and mobile around `emojiListRef` / `scrollToHeader`. I think that both of those can probably be moved to the base implementation
- If we create a `useMouseMoveHandler` hook that's a no-op on mobile ([at least, for now](https://expensify.slack.com/archives/C01GTK53T8Q/p1707252859303449)) then we can DRY up the `mouseMoveHandler` logic and move that to the base implementation.

There might be more, but these seem like low-hanging fruit.

**Comment by TMisiukiewicz** [comment] 2024-02-07 09:09
hey @roryabraham! My hands are full right now with some stuff with high priority, but I can get back to this once I'm done with it. Thanks for pointing out the parts to focus on, if I have any other observations what could be potentially DRYed up, I'll post them here as well 👍

**Comment by roryabraham** [comment] 2024-02-07 09:14
Ok, sounds good. I think this can be treated as kind of lower priority for now as it doesn't really affect users and is more about code quality

**Comment by jjcoffee** [comment] 2024-02-08 16:01
@alexpensify Would you be able to assign me to the issue as I reviewed the PR? Thanks!

**Comment by alexpensify** [comment] 2024-02-08 16:34
Yep, done!

**Comment by alexpensify** [comment] 2024-02-13 22:43
Weekly Update: Making progress here

**Comment by jjcoffee** [comment] 2024-02-14 11:20
@alexpensify I think the payment for PR review on this is due as the PR hit [production](https://github.com/Expensify/App/pull/34581#issuecomment-1928449843) last week. :bow:

**Comment by alexpensify** [comment] 2024-02-14 15:19
@jjcoffee - thanks for flagging, I'll work on the next steps since automation didn't kick in here.

**Comment by alexpensify** [comment] 2024-02-14 15:22
@jjcoffee please accept the offer in Upwork - https://www.upwork.com/jobs/~01717c0ee29a49c13a

Thanks!

**Comment by jjcoffee** [comment] 2024-02-14 15:24
@alexpensify Accepted, thanks!

**Comment by alexpensify** [comment] 2024-02-14 18:43
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @TMisiukiewicz is from an agency-contributor and not due payment
-  Contributor+ that helped on the issue and/or PR - @jjcoffee paid $500

Upwork Job: https://www.upwork.com/jobs/~01717c0ee29a49c13a

Extra Notes regarding payment: @jjcoffee has been paid via Upwork.

**Closed by alexpensify** 2024-02-14 18:43 UTC
Labels: Reviewing, External, Daily, NewFeature, Help Wanted
