### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web - Tooltip not visible for task assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21713] opened 2023-06-27 17:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Create a task
2. Assign it to some one
3. Go to task page
4. Take the cursor to assignee
5. Not tooltip

## Expected Result:
Tooltip should be shown

## Actual Result:
Tooltip not present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/474e6711-ffd3-451d-ac0f-43c1a469ebeb

https://github.com/Expensify/App/assets/93399543/8754a242-0f79-4c18-9490-7d63c361aef9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687543065679319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9a87fc35eb2547b</li>
        <li>Upwork Job ID: 1673818558264049664</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25687409</li>
<li>StevenKKC | Contributor | 25687411</li>
<li>BhuvaneshPatil | Reporter | 25687413</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-06-27 18:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip not visible for task assignee.

### What is the root cause of that problem?
We does not wrap task assignee with `UserDetailsTooltip`.

### What changes do you think we should make in order to solve the problem?
We should wrap task assignee with `UserDetailsTooltip` in [`TaskHeader.js`]() as below.

```js
                                {assigneeAccountID && assigneeAccountID > 0 && (
                                    <UserDetailsTooltip accountID={assigneeAccountID}>
                                        <View style={[styles.flex1, styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween]}>
                                            <Avatar
                                                source={assigneeAvatar}
                                                type={CONST.ICON_TYPE_AVATAR}
                                                name={assigneeName}
                                                size={CONST.AVATAR_SIZE.HEADER}
                                            />
                                            <View style={[styles.flexColumn, styles.ml3]}>
                                                <Text
                                                    style={[styles.headerText, styles.pre]}
                                                    numberOfLines={1}
                                                >
                                                    {assigneeName}
                                                </Text>
                                            </View>
                                        </View>
                                    </UserDetailsTooltip>
                                )}
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by jliexpensify** [comment] 2023-06-27 22:20
I can replicate on Staging v32-5, even with a user with a name (which should have a tooltip):

https://github.com/Expensify/App/assets/30815269/a09100d3-5e7a-4877-bd36-b3ef98b89a2b

**Comment by jeet-dhandha** [comment] 2023-06-28 05:35
I would suggest we hold this issue or close it as we are redesigning task details page.
https://github.com/Expensify/App/issues/19330

**Comment by phuchoang23** [comment] 2023-06-28 09:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip not visible for task assignee

### What is the root cause of that problem?
We don't wrap task assignee with `Tooltip` component
I see we use `Tooltip` component for other pages so I think we should reuse this component

### What changes do you think we should make in order to solve the problem?
Wrap task assignee with `Tooltip` component

**More details:**
```

<View style={[styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween]}>
  {props.report.managerEmail && (
       <>
            <Tooltip text={assigneeName}>
                  <Avatar
                      source={assigneeAvatar}
                      type={CONST.ICON_TYPE_AVATAR}
                      name={assigneeName}
                      size={CONST.AVATAR_SIZE.HEADER}
                   />
             </Tooltip>
              <View style={[styles.flexColumn, styles.ml3]}>
                  <Text
                       style={[styles.headerText, styles.pre]}
                       numberOfLines={1}
                   >
                       {assigneeName}
                   </Text>
               </View>
         </>
   )}
</View>
```

Result:
<img width="1435" alt="Screen Shot 2023-06-28 at 4 54 14 PM" src="https://github.com/Expensify/App/assets/129079323/39bbf1df-0596-4850-adac-f9280fb094b0">

**Comment by s77rt** [comment] 2023-06-28 20:35
I have asked here https://github.com/Expensify/App/issues/19330#issuecomment-1612069160 whether we should put this one on hold or proceed

**Comment by s77rt** [comment] 2023-06-28 23:23
Looks we should put this on hold. cc @jliexpensify

**Comment by s77rt** [comment] 2023-07-03 22:32
Still on hold

**Comment by s77rt** [comment] 2023-07-07 23:06
Still on hold

**Comment by jliexpensify** [comment] 2023-07-09 22:56
Dropping to Weekly since we're on hold.

**Comment by s77rt** [comment] 2023-07-18 23:36
@jliexpensify We can lift the hold now. https://github.com/Expensify/App/pull/20841 is now merged.

**Comment by s77rt** [comment] 2023-07-19 12:46
@StevenKKC @phuchoang23 Can you please update your proposals to reflect the current state?

**Comment by StevenKKC** [comment] 2023-07-19 13:55
@s77rt I updated [my proposal](https://github.com/Expensify/App/issues/21713#issuecomment-1609994975).

**Comment by s77rt** [comment] 2023-07-19 18:14
@StevenKKC Thanks for the update. I think we don't need to do anything here. The avatar already has the correct tooltip showing.

**Comment by StevenKKC** [comment] 2023-07-19 18:25
@s77rt Task assignee does not have tooltip. Please check again.

**Comment by s77rt** [comment] 2023-07-19 18:38
@StevenKKC Can you please share a video/screenshot?

**Comment by StevenKKC** [comment] 2023-07-19 18:44
@s77rt 
This is a screenshot on main branch.

https://github.com/Expensify/App/assets/131836113/936287d0-fe79-4181-bcb8-b957a43e42a9

This is a screenshot after change code based my proposal.


https://github.com/Expensify/App/assets/131836113/03761f3e-fd5c-4482-b94b-40ec0e33bfe3

**Comment by s77rt** [comment] 2023-07-19 18:50
@StevenKKC That's a different bug and your change makes the icon having a different size.

**Comment by StevenKKC** [comment] 2023-07-19 19:00
@s77rt This issue is that the task page does not display a tooltip for the task assignee. Could you please explain why that is a different bug?

**Comment by s77rt** [comment] 2023-07-19 19:05
@StevenKKC The issue was reported for the header view (see the videos in the OP). That seems fixed already.

**Comment by StevenKKC** [comment] 2023-07-19 19:15
@s77rt I checked the videos in the OP. Task detail page is redesigned and the page in the video is the previous task detail page.

**Comment by s77rt** [comment] 2023-07-19 22:06
@shawnborton Can you please help decide whether we should add a tooltip on the assignee avatar? Check the first video here https://github.com/Expensify/App/issues/21713#issuecomment-1642579573

**Comment by shawnborton** [comment] 2023-07-20 11:36
We can add a tooltip but please do not change the avatar size there.

**Comment by s77rt** [comment] 2023-07-20 15:20
@StevenKKC Thanks for the update. Instead of wrapping `Avatar` with `UserDetailsTooltip`, can we pass `icons` as an array so we use `MultipleAvatars` instead of `Avatar`? `MultipleAvatars` already have the mentioned logic https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/components/MultipleAvatars.js#L110-L131

**Comment by StevenKKC** [comment] 2023-07-20 17:49
@s77rt Thanks for your reply. I updated [my proposal](https://github.com/Expensify/App/issues/21713#issuecomment-1609994975). Please review again. Thanks.

**Comment by StevenKKC** [comment] 2023-07-20 18:23
@s77rt Please check alternative solution.

**Comment by s77rt** [comment] 2023-07-20 18:36
@StevenKKC Thanks for the update. That's not what I meant, we already have a logic that displays `MultipleAvatars` if `icons` is an array. We should pass the `icon` prop as an array from `TaskView` to `MenuItem`.

**Comment by BhuvaneshPatil** [comment] 2023-07-20 19:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Tooltip not visible for task assignee

### What is the root cause of that problem?
For displaying avatar in `MenuItem` in `TaskView`, to display tooltip, we need array of icons to be provided as prop. But we are not passing the `icon` as an array.
https://github.com/Expensify/App/blob/99519f2347f91a2328f0e143e8a2859628412ffa/src/components/MenuItem.js#L148-L160

### What changes do you think we should make in order to solve the problem?
We need to pass the `icon` prop for `MenuItem` in `TaskView` as an array, this can be done like following - 
```
icon={OptionsListUtils.getAvatarsForAccountIDs([props.report.managerID], props.personalDetails)}
```

### What alternative solutions did you explore? (Optional)

**Comment by StevenKKC** [comment] 2023-07-20 19:07
@s77rt I updated [my proposal](https://github.com/Expensify/App/issues/21713#issuecomment-1609994975).

**Comment by s77rt** [comment] 2023-07-20 22:56
@BhuvaneshPatil Thanks for the proposal. Your RCA is correct. The solution looks good except the avatar icon is bigger than it's supposed to be.

**Comment by s77rt** [comment] 2023-07-20 23:00
@StevenKKC Thanks for the update. Overall looks good, but why are we constructing the `assigneeTooltipIcon` object manually? Is there any specific case where `OptionsListUtils.getAvatarsForAccountIDs` (as suggested by @BhuvaneshPatil) won't work as expected?

**Comment by BhuvaneshPatil** [comment] 2023-07-21 02:58
@s77rt Updated the proposal for handling size changes.

**Comment by StevenKKC** [comment] 2023-07-21 05:26
@s77rt I think using `OptionsListUtils.getAvatarsForAccountIDs` would be a good idea.

**Comment by s77rt** [comment] 2023-07-21 17:20
@BhuvaneshPatil Thanks for the update. I think we reached the same solution as proposed by @StevenKKC.

**Comment by s77rt** [comment] 2023-07-21 17:21
@StevenKKC Thanks for the update. I think we can go with your proposal as it was the first complete one.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/21713#issuecomment-1609994975)

**Comment by BhuvaneshPatil** [comment] 2023-07-21 17:29
thanks for the update @s77rt , on to the next bug hunting. Good luck @StevenKKC .

**Comment by StevenKKC** [comment] 2023-07-24 07:29
@s77rt [PR](https://github.com/Expensify/App/pull/23461) is ready for review.

**Comment by s77rt** [comment] 2023-07-26 23:13
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18806
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18806#discussion_r1275560750
- A discussion in #expensify-bugs has been started: We already have a discussion about adding tooltip to the checklist https://expensify.slack.com/archives/C02NK2DQWUX/p1689013364759179
- Determine if we should create a regression test for this bug: No

**Comment by jliexpensify** [comment] 2023-08-03 06:48
Payment summary:

- Bug Reporter: @BhuvaneshPatil $250
- Contributor: @StevenKKC $1000 + $500 (speed bonus)
- C+: @s77rt $1000 + $500 (speed bonus)

[Upwork job](https://www.upwork.com/jobs/~01e9a87fc35eb2547b)

Is that all correct? It looks like this was merged in a day

**Comment by s77rt** [comment] 2023-08-03 11:37
@jliexpensify Looks correct!

**Comment by jliexpensify** [comment] 2023-08-04 01:15
Everyone's paid and job removed, thanks!

**Closed by jliexpensify** 2023-08-04 01:15 UTC
Labels: External, Daily, Awaiting Payment, Bug
