### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Expense - Expense preview shows "x paid amount" when expense payment is cancelled offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52135] opened 2024-11-06 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2610010@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workflows are enabled and Add approvals feature is enabled
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense, approve it and pay elsewhere
4. Go offline
5. Click on the expense preview
6. Click on the report header
7. Click Cancel payment
8. Cancel the payment
9. Click Unapprove
10. Click on the report subtitle to return to the main chat

## Expected Result:
The expense preview will show "x owes amount" without checkmark because the expense payment is cancelled offline

## Actual Result:
The expense preview shows "x paid amount" when expense payment is cancelled offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5e219d01-3bef-411c-8271-a6869e272d11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854562907265274025</li>
        <li>Upwork Job ID: 1854562907265274025</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104908738</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by mkzie2** [comment] 2024-11-06 19:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The expense preview shows "x paid amount" when expense payment is cancelled offline

### What is the root cause of that problem?
`iouSettled` condition is true if `isSettled` function returns true or `action.childStatusNum` is `CONST.REPORT.STATUS_NUM.REIMBURSED`

https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/components/ReportActionItem/ReportPreview.tsx#L135

After paying the expense, `action.childStatusNum` is updated correctly. But when we cancel the payment and unapproved the report, this status isn't updated (only the `statusNum` of the expense report is updated).

It leads `iouSettled` is still `true` because this condition `action?.childStatusNum === CONST.REPORT.STATUS_NUM.REIMBURSED` is still `true`

https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/components/ReportActionItem/ReportPreview.tsx#L135

And the preview is displayed `x paid amount`
### What changes do you think we should make in order to solve the problem?
We should only check `action?.childStatusNum` when the iou report data isn't available

```
const iouSettled = iouReport ? ReportUtils.isSettled(iouReportID) : action?.childStatusNum === CONST.REPORT.STATUS_NUM.REIMBURSED;
```
https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/components/ReportActionItem/ReportPreview.tsx#L135

### What alternative solutions did you explore? (Optional)
When we cancel the payment and unapproved the report we should update `childStateNum` and `childStatusNum` of the parent report action in optimistic data and reset it in failure data with the value like [here](https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/libs/actions/IOU.ts#L7551-L7552) and [here](https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/libs/actions/IOU.ts#L7351-L7352)

**Comment by joekaufmanexpensify** [comment] 2024-11-07 16:33
Reproduced. Yeah, if we're showing `Approve` again on the report preview if you unapproved while offline, it seems odd that we are showing the report as paid when it was also canceled offline. 

Seems like this is a [pattern B situation](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#b---optimistic-with-feedback-pattern) based on the unapproved and payment cancel comments having .5 opacity. Not sure if we need to do something to signal on the report preview to signal pattern B too though. 

https://github.com/user-attachments/assets/98b37b88-ea48-469a-ac1d-91b57398449e

**Comment by sobitneupane** [comment] 2024-11-12 13:57
Thanks for the proposal @mkzie2 

I prefer the alternative proposal as it directly addresses the root cause of the issue.

> When we cancel the payment and unapproved the report we should update childStateNum and childStatusNum of the parent report action in optimistic data and reset it in failure data with the value like [here](https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/libs/actions/IOU.ts#L7551-L7552) and [here](https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/libs/actions/IOU.ts#L7351-L7352)

Could you clarify what values we should update childStateNum and childStatusNum to? It would be helpful if you could provide additional details for this alternative solution.

**Comment by mkzie2** [comment] 2024-11-12 14:07
@sobitneupane In two places, we will update `childStateNum`, `childStatusNum` with the same `stateNum` and `statusNum` value that we updated for the expense report

https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/libs/actions/IOU.ts#L7551-L7552

https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/libs/actions/IOU.ts#L7351-L7352

**Comment by mkzie2** [comment] 2024-11-12 14:23
@sobitneupane I updated my [proposal](https://github.com/Expensify/App/issues/52135#issuecomment-2460634519).

**Comment by sobitneupane** [comment] 2024-11-14 11:50
Thanks for the update @mkzie2 

[Alternative proposal](https://github.com/Expensify/App/issues/52135#issuecomment-2460634519) from @mkzie2 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by mkzie2** [comment] 2024-11-18 07:33
@sobitneupane The [PR](https://github.com/Expensify/App/pull/52687) is ready.

**Comment by joekaufmanexpensify** [comment] 2024-11-18 16:34
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-11-25 16:30
Same

**Comment by joekaufmanexpensify** [comment] 2024-12-02 15:42
@sobitneupane could you please handle checklist so we can prep to pay?

**Comment by joekaufmanexpensify** [comment] 2024-12-06 16:03
[Bumped in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1733501025286889)

**Comment by sobitneupane** [comment] 2024-12-08 13:02
**Regression Test Proposal:**

1. Go to a workspace chat
2. Submit, approve, and pay an expense
3. Go offline
4. Open the expense report
5. Click on header --> Cancel payment
6. Unapprove the report
7. Go back to the workspace chat
8. Verify that the report preview will show "x owes amount" without checkmark.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2024-12-08 13:07
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/44229#issuecomment-2525833995

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

**Comment by joekaufmanexpensify** [comment] 2024-12-09 16:31
Regression test issue is here: https://github.com/Expensify/Expensify/issues/451691

**Comment by joekaufmanexpensify** [comment] 2024-12-09 16:31
All set to issue payment. We need to pay: 

- @mkzie2 $250 for PR via Upwork. 
- @sobitneupane $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-12-09 16:32
@mkzie2 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-12-09 16:32
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-12-09 16:33
@sobitneupane please request payment at your earliest convenience. Closing as this is otherwise all set!

**Closed by joekaufmanexpensify** 2024-12-09 16:33 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 10:59
$250 approved for @sobitneupane
