### ISSUE TITLE
[HOLD for payment 2023-08-10] [$250] Migrate withDelayToggleButtonState.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16219] opened 2023-03-20 08:47 UTC
### Filenames
- [ ] [src/components/withDelayToggleButtonState.js](https://github.com/Expensify/App/blob/main/src/components/withDelayToggleButtonState.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f71d79044993f634</li>
        <li>Upwork Job ID: 1685090997633961984</li>
        2023-07-29<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25857026</li>
<li>rayane-djouah | Contributor | 25857028</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-06 11:09
I'd love to work on this.

**Comment by dayana7204** [comment] 2023-06-27 19:29
I am ready to work on this ticket. :)

**Comment by vdem0115** [comment] 2023-07-07 14:31
I would like to work on this issue.

**Comment by olexyt** [comment] 2023-07-07 14:45
I can work on this issue.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 19:12
I'm able to work on this if needed!

**Comment by KrAbhas** [comment] 2023-07-19 10:21
Allow me!

**Comment by Parshvi16** [comment] 2023-07-29 03:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate `withDelayToggleButtonState.js` to function component

### What is the root cause of that problem?
need to change class based component to functional

### What changes do you think we should make in order to solve the problem?
- component state and props from class to function syntax
- render method from class to function syntax
- lifecycle methods to hooks(if any)
- update callbacks from class to function syntax (possibly with useCallback hook)
- update refs from class to function syntax
- any other class component logic to function component
- and ensure no regressions occur.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by reinesarchisorte** [comment] 2023-07-29 04:15
Can i take this?

**Comment by priyankrawat** [comment] 2023-07-29 04:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of [src/components/withDelayToggleButtonState.js](https://github.com/Expensify/App/blob/main/src/components/withDelayToggleButtonState.js) to the function component.


### What is the root cause of that problem?
No root cause, just need to migrate class component to function component.

### What changes do you think we should make in order to solve the problem?
By looking at the code, we can use hooks to refactor the code to function component. We have to follow the following changes-

1. Use the useState hook to manage the state previously handled by this.state.
2. Use the useEffect hook to handle the cleanup when the component is unmounted.
3. Utilize the useRef hook to store the timer reference for proper cleanup.
4. Ensure that the toggleDelayButtonState function continues to work correctly.
5. Finally make sure there is no regression.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexxxwork** [comment] 2023-07-29 04:18
I would love to work on this issue

**Comment by s77rt** [comment] 2023-07-29 11:32
Thank you all for your interest here. Going in chronological order
- @rayane-djouah Let's do it :rocket: 

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by PauloGasparSv** [comment] 2023-08-09 20:27
Not overdue, still on hold till tomorrow

**Comment by Christinadobrzyn** [comment] 2023-08-10 23:16
Paying now. 

Payouts due:

Issue Reporter: NA
Contributor: $250 + $125 (bonus) @rayane-djouah 
Contributor+: $250 + $125 (bonus) @s77rt 

Eligible for 50% #urgency bonus? Yes per https://github.com/Expensify/App/issues/16219#issuecomment-1659038780

Upwork job is [here](https://www.upwork.com/jobs/~01f71d79044993f634)

**Comment by Christinadobrzyn** [comment] 2023-08-10 23:18
Let me know if I'm missing anything! Closing GH.

**Closed by Christinadobrzyn** 2023-08-10 23:18 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment

**Comment by s77rt** [comment] 2023-08-10 23:21
@Christinadobrzyn Functional migration issues are not eligible for the urgency bonus https://expensify.slack.com/archives/C02NK2DQWUX/p1691672264412869. I have refunded the +50%.

**Comment by Christinadobrzyn** [comment] 2023-08-10 23:42
Ah thank you @s77rt! @rayane-djouah sounds like the $125 bonus on your payment doesn't apply to this if you can refund it. Sorry for the confusion! 

Updated this comment with the payment - https://github.com/Expensify/App/issues/16219#issuecomment-1674041578
