### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] [Dupe detection] Report header has "Hold" action when the expense is already in Hold status

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49872] opened 2024-09-27 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y
**Reproducible in production?:**  N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48522
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [Employee] Submit two same expenses in the workspace chat.
3. [Admin] Go to any of the submitted expense in the workspace chat.
4. [Admin] Go offline.
5. [Admin] Click Review duplicates.
6. [Admin] Click Keep this one (any).
7. [Admin] Click Confirm on the confirmation page.
8. [Admin] Go to the other transaction thread that has "Hold" action in the expense preview.
9. [Admin] Click on the report header.

## Expected Result:
Since the other expense has "Hold" action, the report header should have the "Unhold" action.

## Actual Result:
The report header has "Hold" action when the expense is already in Hold status.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0055f62e-e602-418a-8393-ccaf2387c219

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840780088904015602</li>
        <li>Upwork Job ID: 1840780088904015602</li>
        <li>Last Price Increase: 2024-09-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment] 2024-09-27 22:00
On prod, the other expense vanishes instantly

https://github.com/user-attachments/assets/7f756a65-9140-466b-a8c1-2cb2e554584b

**Comment by IuliiaHerets** [comment] 2024-09-27 22:02
We think that this bug might be related to #wave-collect - Release 1

**Comment by roryabraham** [comment] 2024-09-29 00:38
Dupe detection is behind a beta w/ only internal users and developers, this is NAB

**Comment by jasperhuangg** [comment] 2024-09-30 15:45
Since all of these actions happen offline this issue is in the front-end and can therefore be fixed externally.

**Comment by jasperhuangg** [comment] 2024-10-03 18:38
@eVoloshchak Please review proposals!

**Comment by jasperhuangg** [comment] 2024-10-07 21:32
@twilight294 sorry for the confusion, I have thumbs to your proposal but didn't intend on assigning you, I was acknowledging that I saw your proposal.

**Comment by stephanieelliott** [comment] 2024-10-11 04:34
@eVoloshchak the [PR](https://github.com/Expensify/App/pull/50383) is waiting on your review, can you take a look?

**Comment by stephanieelliott** [comment] 2024-10-14 23:46
> @eVoloshchak the https://github.com/Expensify/App/pull/50383 is waiting on your review, can you take a look?

^^ Bump @eVoloshchak

**Comment by situchan** [comment] 2024-10-16 07:37
I can review PR if needed

**Comment by stephanieelliott** [comment] 2024-10-22 07:14
PR is on staging!

**Comment by yuwenmemon** [comment] 2024-10-23 06:33
This doesn't appear to be fixed by the PR as the original issue is still reproducible on Mobile Web: https://github.com/Expensify/App/pull/50383#issuecomment-2430541377

**Comment by stephanieelliott** [comment] 2024-10-31 08:53
Summarizing payment on this issue: 

 - Contributor: @eVoloshchak $250 via NewDot - Please request 
 - Contributor+: @daledah $250 via Upwork - offer extended, please accept!
 
 Upwork job is here: https://www.upwork.com/jobs/~021851909474139768777

**Comment by stephanieelliott** [comment] 2024-11-05 08:24
All paid!

**Closed by stephanieelliott** 2024-11-05 08:24 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-11-18 16:09
$250 approved for @eVoloshchak
