### ISSUE TITLE
[$500] Android - Settings - App crashes when changing device font size and then tapping on Profile icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32515] opened 2023-12-05 19:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Background the app
3. Change the device font size
4. Return to the app
5. Tap on the profile icon

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1a7de005-d8db-4c50-a5ae-4b2faf2ce766

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01977dd9f154104e64</li>
        <li>Upwork Job ID: 1732120049690255360</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by allroundexperts** [comment] 2023-12-06 18:56
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/32515#issuecomment-1841556610) looks good!

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2023-12-06 19:02
I think @situchan fixed it yesterday https://github.com/Expensify/App/pull/32525. But, it seems like he missed to change it in `/src/libs/Navigation/Navigation.ts`.

**Comment by situchan** [comment] 2023-12-06 19:05
Ah, so the crash really happened on production app?

**Comment by situchan** [comment] 2023-12-06 19:08
My fix was not fixing the root cause, but just to avoid crash. As seen in typing, rootState is not optional so should not be undefined

**Comment by iwiznia** [comment] 2023-12-06 19:38
> I think @situchan fixed it yesterday https://github.com/Expensify/App/pull/32525. But, it seems like he missed to change it in /src/libs/Navigation/Navigation.ts.

Ah ok, given it's the same error, I think @situchan should fix it as part of that other issue, agree?

**Comment by allroundexperts** [comment] 2023-12-10 18:59
> Are you still able to reproduce crash on latest main?

Seems to be fixed on the latest main. I can also no longer reproduce this today. @suneox I see you had posted a proposal recently. Can you reproduce it?

**Comment by iwiznia** [comment] 2023-12-14 19:12
@allroundexperts do you agree we should make the fix @suneox proposes?

**Comment by bfitzexpensify** [comment] 2023-12-17 14:54
Bump @allroundexperts - do you think the fix suggested by @suneox is worthwhile, even though this particular bug is no longer happening?

**Comment by situchan** [comment] 2023-12-17 14:57
I think we can close this as no longer crash happening. If any critical issue happens in the future with the same root cause, we can always reopen.

**Comment by bfitzexpensify** [comment] 2023-12-19 23:34
Any updated thoughts @suneox?

**Comment by bfitzexpensify** [comment] 2023-12-20 13:30
Thanks @suneox. OK, let's close this one out then.

**Closed by bfitzexpensify** 2023-12-20 13:30 UTC
Labels: External, Daily, Help Wanted, Bug
