### ISSUE TITLE
[$1000] Web -  User B's Previous Description Overrides User A's Assigned Description- Public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22093] opened 2023-07-02 23:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
A) From User A:
1. Login to the app with User A.
2. Create a room and set it to public mode.
3. Create a task within the room: Add any title. WRITE A MEMORABLE DESCRIPTION. (Description 1).Do not choose an assignee and verify if the newly created room is selected by default under share.
B) From User B:-
1. Click on + button > assign task and create a task. Choose any title and WRITE A MEMORABLE DESCRIPTION (Description 2). Choose User B as an assignee and share it anywhere.
C) From User A, go to detail > share code > copy link and share it to User B
D) From User B, open the room > locate the task assigned by User A > go to task thread > click on description
Verify if this description is exactly what User A wrote

## Expected Result:
User B should see the description written by User A who created the task.

## Actual Result:
User B is presented with a discrepancy. Instead of observing the intended description authored by User A, User B is confronted with their own previous task description (Description 2), an occurrence resulting from the system's erroneous retrieval of the most recent entry.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4400c223-9c9d-41c4-8c43-ce1f924cf48f

https://github.com/Expensify/App/assets/93399543/4a3c4d3d-d7af-400d-80a9-eb1c68edda04

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688258456734509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5f6333176e1303f</li>
        <li>Upwork Job ID: 1679157556016054272</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-07-03 19:59
Asking about this

https://expensify.slack.com/archives/C049HHMV9SM/p1688414333700369?thread_ts=1688258456.734509&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-07-06 21:29
Still clarifying in slack

**Comment by kevinksullivan** [comment] 2023-07-12 15:55
Got clarity on the issue in slack.

**Comment by eVoloshchak** [comment] 2023-07-16 23:24
Not overdue, will review the proposal today

**Comment by eVoloshchak** [comment] 2023-07-17 19:10
> IMO this should be addressed in the BE side. The correct report message with the description field should be returned in the reportActions_[task_action_id] key inside OpenReport api response

I agree with @tienifr, [this should be addressed on the back end](https://github.com/Expensify/App/issues/22093#issuecomment-1617763995). I don't think it's severe enough to implement a temporary solution on the front end

**Comment by mvtglobally** [comment] 2023-07-20 02:54
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2023-07-24 08:09
Oofda sorry for the delay :D 

@thienlnam @jasperhuangg have either of you seen something like this? I believe y'all are still working on a few task updates so just wanted to check if either of y'all are already fixing this or not :D

**Comment by thienlnam** [comment] 2023-07-24 21:35
Can we verify this bug is still reproducible? - we've made a lot of task changes since this bug was created

**Comment by thienlnam** [comment] 2023-07-24 21:35
https://github.com/Expensify/App/issues/22093#issuecomment-1643029133

Actually looks like we can't so maybe we can just close this

**Comment by Beamanator** [comment] 2023-07-25 07:59
Aah true, maybe @mvtglobally can you test once more and we can close if not reproducible?

**Comment by kevinksullivan** [comment] 2023-07-28 18:50
No longer reproducible. Discussed in slack and closing.

**Closed by kevinksullivan** 2023-07-28 18:50 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Overdue, Bug
