### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-13] Crash on split confirm

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#19234] opened 2023-05-18 23:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

___

This is a follow up issue from https://github.com/Expensify/App/pull/17349#issuecomment-1537823597

## Action Performed:
1. (Precondition) Have the desktop app open but not logged in; optionally, throttle your network (see last step)
2. Log in to web
3. In a 1:1 DM, select `Send money`
4. Copy the URL from the address bar
5. Modify the URL so that it's a deep link (replace `http` with `new-expensify`) and open it
7. Follow the deep link prompt to open it in desktop
8. Enter an amount to split and click `Next` button very quickly (if you are not throttling your network)

## Expected Result:
Split confirm page should open

## Actual Result:
The app crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/96077027/236749210-e6132003-424b-4610-ba35-dbea8fe2ccbf.mov

https://github.com/Expensify/App/assets/7277067/857bdb25-c2c2-43a8-93be-84f52fb75628

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aimane-chnaif 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f9b81ec5ac80063</li>
        <li>Upwork Job ID: 1668641221032722432</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by amyevans** [comment] 2023-05-18 23:31
@jczekalski please comment on the issue so I can assign you

**Comment by jczekalski** [comment] 2023-05-19 10:20
@amyevans

**Comment by jczekalski** [comment] 2023-05-19 12:22
@amyevans I pulled the changes from the latest version of [main](https://github.com/Expensify/App/commit/435c70bf14651f4028f57d424e62e2f7495cb2f8) and started looking into this. If I quickly open the Send Money page using slow 3G network throttling or deep link into the page (`http://localhost:8080/send/new`) I get these errors:
```
tNumberFormatUnitOptions.js:18 Uncaught TypeError: currency cannot be undefined

The above error occurred in the <TextInputWithCurrencySymbol> component:
 ```
 ```
 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at eval (index.js:11:1)
 ```
 

https://github.com/Expensify/App/assets/39824924/fc5a71cc-943a-44a4-940c-19949dca0ec4


So I can't get to the confirmation screen without the app crashing. In the video you uploaded, the Send Money page works fine and the errors in the console are different (the app crashes when the confirmation page is opened). It looks like these are new issues, do you know if they've been reported?

**Comment by amyevans** [comment] 2023-05-19 21:12
We have over 1,000 open issues in the repo, so I don't know off the top of my head if they've been reported yet haha. Could you post them in the #expensify-bugs Slack channel? Our QA team is better at spotting duplicates, and if they aren't dupes they will create new issues for them.

**Comment by jczekalski** [comment] 2023-05-22 10:00
> We have over 1,000 open issues in the repo, so I don't know off the top of my head if they've been reported yet haha. Could you post them in the #expensify-bugs Slack channel? Our QA team is better at spotting duplicates, and if they aren't dupes they will create new issues for them.

Good point! Sorry, I'm still getting used to this setup :) I posted the bug in the `#expensify bugs` channel.

**Comment by jczekalski** [comment] 2023-05-24 13:06
**Update**: I approved the [PR](https://github.com/Expensify/App/pull/19441#pullrequestreview-1441783550) which fixes the bug I mentioned above (crash on Send money / Request money / Split bill), so we should be able to work on this issue once it has been merged.

**Comment by kowczarz** [comment] 2023-05-25 09:03
I'm from Software Mansion, I'd like to work on this job.

**Comment by amyevans** [comment] 2023-05-25 14:40
Greg and I both just spent some time attempting to reproduce as well and weren't able. I'm going to close. Thanks guys!

**Comment by amyevans** [comment] 2023-05-25 17:33
Okay thanks, reproduced and wrote up some clearer steps - let me know if they can be tweaked for clarity:


https://github.com/Expensify/App/assets/7277067/857bdb25-c2c2-43a8-93be-84f52fb75628



1. (Precondition) Have the desktop app open but not logged in; throttle your network
2. Log in to web
3. In a 1:1 DM, select `Send money`
4. Copy the URL from the address bar
5. Modify the URL so that it's a deep link (replace `http` with `new-expensify`) and open it
7. Follow the deep link prompt to open it in desktop
8. Enter an amount to split

**Comment by amyevans** [comment] 2023-05-25 23:25
FYI: I'll be OOO tomorrow and Monday.

**Comment by greg-schroeder** [comment] 2023-05-26 07:24
Okay, nice, the new reproduction steps look better/clearer for sure

**Comment by greg-schroeder** [comment] 2023-05-26 07:25
@kowczarz - mind taking another stab at reproducing? If you can are you still available to action this?

**Comment by kowczarz** [comment] 2023-05-26 10:31
Yep, I managed to reproduce the issue, I'm working on proposal.

**Comment by kowczarz** [comment] 2023-05-26 10:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes on money request confirmation

### What is the root cause of that problem?
The app wants to read property of value that can be undefined here
https://github.com/Expensify/App/blob/ec9bc04108992ff400b3fb86d8a31091d727310e/src/components/MoneyRequestConfirmationList.js#L293

### What changes do you think we should make in order to solve the problem?
Before accessing `payPalMeAddress` of `recipient`, we need to ensure that the `recipient` is not undefined and has a value.

To do so I would extract the boolean cast to a separate constant and before the cast I'd use [`_.isUndefined`](https://lodash.com/docs/#isUndefined) to ensure if the `recipient` exists.

### What alternative solutions did you explore? (Optional)
NA

**Comment by kowczarz** [comment] 2023-05-26 12:54
@aimane-chnaif I've just updated it.

**Comment by greg-schroeder** [comment] 2023-05-29 13:17
Looks like we're awaiting @amyevans to return tomorrow for confirmation

**Comment by greg-schroeder** [comment] 2023-05-31 20:29
PR is up!

**Comment by greg-schroeder** [comment] 2023-06-05 15:18
PR review is very nearly complete

**Comment by greg-schroeder** [comment] 2023-06-06 18:38
Merged, awaiting deploy to prod

**Comment by greg-schroeder** [comment] 2023-06-13 15:27
Added the label to create an Upwork job, sorry for pings

**Comment by greg-schroeder** [comment] 2023-06-13 16:12
Sent an offer to @aimane-chnaif

**Comment by greg-schroeder** [comment] 2023-06-13 16:15
Last step is the checklist @aimane-chnaif!

**Comment by greg-schroeder** [comment] 2023-06-13 16:45
All right. Thanks for running through it. Paid out. Going to close.

**Closed by greg-schroeder** 2023-06-13 16:45 UTC
Labels: External, Weekly, Awaiting Payment, Bug
