### ISSUE TITLE
workspace photo not updating immediately - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11098] opened 2022-09-19 05:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.   go to any space
2.   change photo

## Expected Result:
photo should be update immediately

## Actual Result:
takes 2-3 seconds to update

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.99-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190955648-6d32e6f3-3655-44b3-83d2-a2e993eb99f9.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662315208529829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2022-09-19 17:49
Can't reproduce this at all on iOS now. [Original report](https://expensify.slack.com/archives/C01GTK53T8Q/p1663609717644569?thread_ts=1662315208.529829&cid=C01GTK53T8Q) was almost two weeks ago, so this might have been fixed. Closing for now but will re-open if anyone mentions that they're still experiencing this in Slack.

**Closed by joekaufmanexpensify** 2022-09-19 17:49 UTC
Labels: Daily
