### ISSUE TITLE
[Awaiting Payment 16th May] [Wave Collect] [Xero] [Advanced] Create the main Advanced Settings page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39746] opened 2024-04-05 16:44 UTC
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.86x8n1g09vky).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by Christinadobrzyn** [comment] 2024-04-11 03:05
@lakchote are you working on this too? looks like there's no engineer assigned yet so just checking

**Comment by lakchote** [comment] 2024-04-11 06:15
> @lakchote are you working on this too? looks like there's no engineer assigned yet so just checking

Yes, I'll be working on this.

**Comment by lakchote** [comment] 2024-04-15 15:39
Updated title with the HOLD issue.

**Comment by Christinadobrzyn** [comment] 2024-04-26 07:41
we're on hold for this - https://github.com/Expensify/App/issues/39725 right @lakchote?

**Comment by lakchote** [comment] 2024-04-30 09:17
> we're on hold for this - #39725 right @lakchote?

Yes, we were on hold for https://github.com/Expensify/App/issues/39725 to be merged.

It was merged yesterday. Technically we are able to work on this now.

I'm going to focus today on [fixing the remaining bugs](https://expensify.slack.com/archives/C01GTK53T8Q/p1714468527496189?thread_ts=1714119216.357459&cid=C01GTK53T8Q) for the Xero authorization flow before working on it.

**Comment by rushatgabhane** [comment] 2024-05-02 03:36
I'm working on this

**Comment by Christinadobrzyn** [comment] 2024-05-08 08:57
awesome! thank you @rushatgabhane added you to the GH - we'll monitor the PR https://github.com/Expensify/App/pull/41475

**Comment by trjExpensify** [comment] 2024-05-09 11:58
Deployed to production 9 hours ago.

**Comment by Christinadobrzyn** [comment] 2024-05-14 08:56
Payouts due—Based on our [payment structure](https://expensify.slack.com/archives/C02NK2DQWUX/p1712250884549319), I think this should be $500 since it relates to the roadmap? Do you think?

- [ ] Contributor+: $500 @rushatgabhane 

@rushatgabhane you're paid in NewDot, right? Do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-05-16 08:14
nudge @rushatgabhane about a regression test for this. Maybe we can use the test steps in the PR for a regression test?

- Navigate to a workspace with xero connected
- Click advanced
- Verify that you can see auto sync toggle. Verify that you can toggle it
- Verify that there is a purchase bill status selector
- Toggle reimbursed reports
- Verify that toggling reimbursed reports shows/hides account selectors.

**Comment by trjExpensify** [comment] 2024-05-16 11:08
Payment will be handled centrally when we wrap the project, we can close this as the regression period is over. 

Equally, we can hand over the regression tests to Applause once the project wraps (CC: @zanyrenney). Closing it out!

**Closed by trjExpensify** 2024-05-16 11:08 UTC
Labels: Daily, NewFeature, Awaiting Payment
