### ISSUE TITLE
[$500] [HOLD for payment 2023-12-21] IOU - Back button unresponsive on touches on IOU details page in offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32408] opened 2023-12-02 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Navigate to any 1:1 converssation
3. Make a Money Request
4. Turn you internet connection off
5. Navigate to IOU details page
6. Tap on back button in header

## Expected Result:
User should be navigated back on IOU listing page

## Actual Result:
The back button unresponsive on touches. It is unable to navigate back and user get stuck on the empty page with loading skeleton animation.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d81e314a-ea44-465e-9928-9b369a7d0da4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ceacebec21ea886</li>
        <li>Upwork Job ID: 1730978209177305088</li>
        <li>Last Price Increase: 2023-12-02</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 27990113</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-12-02 18:01
# Proposal

## Please re-state the problem that we are trying to solve in this issue



## What is the root cause of that problem?

https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/pages/home/HeaderView.js#L199-L201

Issue comes from the above code block because in offline mode the `isLoading` is true and it renders the `ReportHeaderSkeletonView` component which has `onPress={() => {}}`.

## What changes do you think we should make in order to solve the problem?

Add new prop `onBackButtonPress = () => {}` (default) to `ReportHeaderSkeletonView` component and then from `HeaderView` component pass :

```
<ReportHeaderSkeletonView onBackButtonPress={props.onNavigationMenuButtonClicked} />
```

`props.onNavigationMenuButtonClicked` being the same function used for header go back button when `isLoading` is false.

 ### Videos

<details>
<summary>iOS: Native</summary>

</details>

**Comment by chiItepin** [comment] 2023-12-02 21:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user is not able to navigate back to the previous screen while the screen remains "loading".
As a user I should be able to navigate back at any time without being constrained by either latency or an offline connection.

### What is the root cause of that problem?
The `ReportHeaderSkeletonView` component is rendering a "dummy" back button without an `onPress` callback. However, Skeleton/Shimmer views should be minimal, it should not be rendering this "dummy" back button.

### What changes do you think we should make in order to solve the problem?


Instead of providing the same `onNavigationMenuButtonClicked ` prop its parent use to toggle the menu, I would remove the "dummy" back button rendered by the Skeleton, these views should be minimal and should not rely on props that don't directly contribute to the purpose of the skeleton.

Once the "dummy" back button is removed from the Skeleton, I would make sure the the main back button which in this case is the `PressableWithoutFeedback` rendered by the `HeaderView` would be remain rendering regardless of whether the screen is loading or not, it should not care about the status.

Providing this experience to our users:

<img width="424" alt="Screenshot 2023-12-02 at 14 28 42" src="https://github.com/Expensify/App/assets/50275849/525ef43f-e838-482a-a63a-7f7a6ae98156">

Benefits:
- Maintain one header back button (expanding the dummy back button would make this piece less maintainable on the other hand)
- Better user experience
- Consistency

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by chiItepin** [comment] 2023-12-02 21:35
Contributor details
Your Expensify account email: hector.almeida.ca@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011f4f88a011c86571

**Comment by ikevin127** [comment] 2023-12-06 22:40
@thesahindia PR https://github.com/Expensify/App/pull/32592 ready for review! 🚀

**Comment by ikevin127** [comment] 2023-12-17 19:39
I think there's been an issue with melvin not changing the title of the issue to [HOLD for payment {date}] 3 days ago when the fix was deployed to production as per https://github.com/Expensify/App/pull/32592#issuecomment-1856053455

**Comment by twisterdotcom** [comment] 2023-12-20 23:46
Ah I see. Okay, this should have been [HOLD for payment 2023-12-21]. @ikevin127 and @thesahindia I will get this paid, but it will have to be post Christmas.

**Comment by ikevin127** [comment] 2024-01-03 20:41
cc @twisterdotcom

**Comment by twisterdotcom** [comment] 2024-01-05 10:48
Payment Summary:

- @thesahindia to be paid $500 [here](https://www.upwork.com/nx/wm/offer/100305058) (Contributor+)
- @ikevin127 to be paid $500 [here](https://www.upwork.com/nx/wm/offer/100304985) (Contributor)

**Comment by JmillsExpensify** [comment] 2024-01-09 18:40
$500 payment approved for @thesahindia based on comment above.

**Comment by twisterdotcom** [comment] 2024-02-01 15:59
I think we can close this right?

**Closed by twisterdotcom** 2024-02-01 15:59 UTC
Labels: Reviewing, External, Monthly, Bug
