### ISSUE TITLE
[$1000] Chat - App does not scroll to bottom when we pay any request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24653] opened 2023-08-16 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. From user B, request money from user A
4. From user A, open user B report, send few messages and ensure that 'Pay elsewhere' button goes out of screen.
5. Scroll to 'Pay elsewhere' message and click on pay button
6. Observe that it adds message to the report but does not scroll to bottom as it normally does for normal messages

## Expected Result:
App should scroll to bottom whenever we add or app adds new message to the report

## Actual Result:
App does not scroll to bottom when we pay request and app adds new paid message to the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5511a949-df61-4519-b5d1-0461ab680f33

https://github.com/Expensify/App/assets/78819774/d8aaaeda-d355-45ba-801b-a67ad412cd7d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691395112098369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f676f20384dab24</li>
        <li>Upwork Job ID: 1693637463259348992</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-08-17 10:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not scroll to bottom when we pay any request.

### What is the root cause of that problem?
When we pay request, `IOU.payMoneyRequest` is called.
But in this function, app does not call `Report.notifyNewAction`.
https://github.com/Expensify/App/blob/0bdf18378356d6f4d5dd0aada5182b3c1648fa4e/src/libs/actions/IOU.js#L1510-L1527
So app does not scroll to bottom when we pay request.

### What changes do you think we should make in order to solve the problem?
We should call `Report.notifyNewAction` in `IOU.payMoneyRequest`.
```js
    ...
    API.write(apiCommand, params, {optimisticData, successData, failureData});
    Navigation.dismissModal(chatReport.reportID);
+   Report.notifyNewAction(chatReport.reportID, iouReport.ownerAccountID);
    ...
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by maddylewis** [comment] 2023-08-21 14:53
assigning C+ to begin reviewing proposals

**Comment by maddylewis** [comment] 2023-08-24 19:46
@thesahindia doesn't have the bandwidth for this one right now. @Santhosh-Sellavel - lmk if you have availability atm!

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 18:21
@maddylewis I can get to this on Monday!

**Comment by maddylewis** [comment] 2023-08-28 13:31
@Santhosh-Sellavel - will review this one today :)

**Comment by maddylewis** [comment] 2023-08-30 16:58
closing based on this convo - https://expensify.slack.com/archives/C02NK2DQWUX/p1693367006433669?thread_ts=1693253145.311429&cid=C02NK2DQWUX

**Closed by maddylewis** 2023-08-30 16:58 UTC
Labels: External, Daily, Help Wanted, Bug
