### ISSUE TITLE
[Ready for payment][$250] Tags - Selection mode is on Tags page after exiting Categories with selection mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47685] opened 2024-08-20 07:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 9.0.22-5
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has enabled Tags feature.
- There is no tag in Tags list.

1. Launch New Expensify app.
2. Go to workspace settings > Categories.
3. Long tap on any category > Select.
4. On iOS, swipe to right to exit the page (not app back button).
5. On Android, use device back navigation to exit the page.
6. Go to Tags.

## Expected Result:
Selection mode will not be shown in Tags page.

## Actual Result:
Selection mode is on Tags page when exiting Categories page while selection mode is on.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d15e2edd-793a-4549-bf21-26dcb64c74a5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019436d499cc978b90</li>
        <li>Upwork Job ID: 1826085634600304781</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103616917</li>
<li>dominictb | Contributor | 103616918</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-08-20 07:54
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-20 07:54
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by wildan-m** [comment] 2024-08-20 09:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tags - Selection mode is active on the Tags page after leaving Categories.

### What is the root cause of that problem?
useEffect logic  to turn off selection in src/components/SelectionListWithModal/index.tsx is incorrect
### What changes do you think we should make in order to solve the problem?

I think we should turn it of when `!isSmallScreenWidth || !isFocused || selectedItems.length === 0`

src/components/SelectionListWithModal/index.tsx
```tsx
    const isFocused = useIsFocused();

    useEffect(() => {
        // We can access 0 index safely as we are not displaying multiple sections in table view
        const selectedItems = sections[0].data.filter((item) => item.isSelected);

        if (!isSmallScreenWidth || !isFocused || selectedItems.length === 0) {
            turnOffMobileSelectionMode();
            return;
        }

        if (!selectionMode?.isEnabled) {
            turnOnMobileSelectionMode();
        }

    }, [sections, selectionMode, isSmallScreenWidth, isFocused]);

```
or 
```tsx
        const selectedItems = sections[0].data.filter((item) => item.isSelected);
        if (!isSmallScreenWidth) {
            if (selectedItems.length === 0) {
                turnOffMobileSelectionMode();
            }
            return;
        }

        if(!isFocused)
        {
            turnOffMobileSelectionMode();
            return;
        }

        if (!selectionMode?.isEnabled) {
            turnOnMobileSelectionMode();
        }

```
### What alternative solutions did you explore? (Optional)
cleanup using `navigation.addListener('blur'`

            const unsubscribe = navigation.addListener('blur', () => {
                 turnOffMobileSelectionMode();
            });
            return unsubscribe;

**Comment by wildan-m** [comment] 2024-08-21 05:44
@dukenv0307 are all screens in react-navigation remounted? There are cases where the screen is not remounted. Would it be safer to rely on focus instead of component mount?

**Comment by kadiealexander** [comment] 2024-10-02 06:56
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@dukenv0307] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@dukenv0307] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@dukenv0307] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@dukenv0307] Determine if we should create a regression test for this bug.
- [ ] [@dukenv0307] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-10-02 06:57
Payouts due:

- [ ] Contributor: $250 @dominictb
- [ ] Contributor+: $250 @dukenv0307

Upwork job is [here](https://www.upwork.com/jobs/~019436d499cc978b90).

**Closed** 2024-10-06 22:46 UTC
Labels: Reviewing, External, Daily, Bug
