### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000]  Text "Invite new members" is jerked

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22036] opened 2023-07-02 01:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspaces
2. Go member
3. Click invite, Observe that The word "Invite new member" is  jerked, Easier see on the big screen
## Expected Result: 
The word "Invite member" is not jerked
## Actual Result: 
The word "Invite member" is not jerked

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ad8239ef-d692-43a5-a2b9-c4afdda6ff17

https://github.com/Expensify/App/assets/43996225/896fad8e-74a3-4ae0-affd-74b0dd7ea6b1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688112890310839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2fb2aaa7db7f478</li>
        <li>Upwork Job ID: 1675919369069428736</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-07-02 18:35
I don't really understand the bug report. Asked in the slack thread.

**Comment by puneetlath** [comment] 2023-07-03 17:28
We chatted in the Slack thread and I think this issue stems from the fact that we don't push the invite members page on top of the existing page, like we do in all other scenarios. The page is just updated in-place. 

So I think we should update this to work like all other page in the right-hand-pane, where the new page slides in from the right on top of the existing page.

**Comment by b4s36t4** [comment] 2023-07-03 19:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Text "Invite new members" is jerked 

### What is the root cause of that problem?
Although navigation and everything is going fine, the root issue causing the issue is the input we have inside the invite member page.

If we observe closely that whenever we click on Invite the input is instantly getting focus which is kind of reason for the transition not to show.

### What changes do you think we should make in order to solve the problem?
We should delay the focusing the input while rendering component, we should use the prop to delay focus.

Take a look at here -> https://github.com/Expensify/App/blob/e7a17f8d7af114a596b4919c19815e5ac9a38c35/src/pages/workspace/WorkspaceInvitePage.js#L295


### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-07-03 19:44
[aa.webm](https://github.com/Expensify/App/assets/59088937/8e3bb4ff-7eca-42a9-bc56-2a82f2fee129)

**Comment by s77rt** [comment] 2023-07-04 11:51
@puneetlath Are you able to reproduce the bug? Seems hard to reproduce or even to notice :sweat_smile:. @namhihi237 Can you help here?

**Comment by b4s36t4** [comment] 2023-07-04 12:18
@s77rt you have to observe the transition of the page, it's different from all other pages. When you click on Members you'll the page (transitioned from right side) but when you click on `Invite` even though it is a new Page there's no animation or page transition happened.

**Comment by s77rt** [comment] 2023-07-04 12:44
@b4s36t4 I got that. I read your proposal it seems to help on the "dropped frames" issue but I'm not sure if this is the issue we are talking about here.

**Comment by b4s36t4** [comment] 2023-07-04 12:45
I think the slack thread mentioned above might help you understand.

**Comment by s77rt** [comment] 2023-07-04 16:53
@b4s36t4 Were you able to reproduce the bug? (the left and right vibration of the text and not the lack of animation/dropped frames)

**Comment by b4s36t4** [comment] 2023-07-04 16:55
Yes, @s77rt . I was able to.

**Comment by b4s36t4** [comment] 2023-07-04 17:08
@s77rt please watch this video, observe closely on `I` from `Invites` there's small shake happening. 
[aa.webm](https://github.com/Expensify/App/assets/59088937/af23005a-198f-46c2-8422-bed3f724e42e)

**Comment by s77rt** [comment] 2023-07-04 17:27
@b4s36t4 Thanks. Can you please upload a video after delaying the input focus? (pass `shouldDelayFocus`)

**Comment by b4s36t4** [comment] 2023-07-04 17:29
Yes, tested. You have the video same above.

**Comment by b4s36t4** [comment] 2023-07-04 17:30
> [aa.webm](https://github.com/Expensify/App/assets/59088937/8e3bb4ff-7eca-42a9-bc56-2a82f2fee129)
> 

This is the video @s77rt

**Comment by s77rt** [comment] 2023-07-04 18:11
@b4s36t4 That's great. I think we should fix the missing right-to-left animation anyway. That and this issue seems to have the same root cause although I was not able to clearly reproduce this one.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by mountiny** [comment] 2023-07-04 19:08
@b4s36t4 Feel free to raise a PR.

@s77rt noting I would like to ask SWM for a review of the PR as well since this is related to the navigation. It might be good to think of a general solution for any page which can be affected with this similar problem

**Comment by b4s36t4** [comment] 2023-07-04 20:06
@MelvinBot @mountiny Raised PR, thanks.!!

**Comment by mountiny** [comment] 2023-07-06 02:16
PR merged

**Comment by b4s36t4** [comment] 2023-07-07 11:29
Thanks @mountiny

**Comment by b4s36t4** [comment] 2023-07-10 08:50
@puneetlath I see Reviewing Tag, but PR is merged? is there anything I'm missing?

**Comment by s77rt** [comment] 2023-07-10 12:40
@b4s36t4 It will be removed once the PR hit production.

**Comment by puneetlath** [comment] 2023-07-11 18:03
Sent hiring offers to @s77rt and @b4s36t4. 

@namhihi237 can you apply to the job please? 

Also @s77rt friendly reminder about the checklist.

**Comment by b4s36t4** [comment] 2023-07-11 18:06
@puneetlath As per the comments I feel this deserves a bonus. PR got merged within 3 days right?! is there anything I'm missing?

**Comment by puneetlath** [comment] 2023-07-11 18:07
Yes, the bonus will be applied when paying.

**Comment by b4s36t4** [comment] 2023-07-11 18:08
oh ok. Got it Thanks.!

**Comment by puneetlath** [comment] 2023-07-11 18:08
No worries 😄

**Comment by puneetlath** [comment] 2023-07-11 18:11
Ok great, thanks. Offers have been sent to everyone.

**Comment by s77rt** [comment] 2023-07-11 22:44
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/20731
- The offending PR has been commented on: https://github.com/Expensify/App/pull/20731#discussion_r1260351648
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1689115447484029
- Determine if we should create a regression test for this bug: No

**Comment by mountiny** [comment] 2023-07-20 11:56
@anmurali Puneet is ooo so to move this forward I have reassigned the bug zero

The payments should be:
- $1000 @s77rt 
- $1000 @b4s36t4 
- $250 to @namhihi237

**Comment by mountiny** [comment] 2023-07-24 12:50
@anmurali This is ready for payment

**Comment by mountiny** [comment] 2023-07-24 14:47
@puneetlath Thats correct, apologies, the automation must failed here so there was no urgency comment and I did not look into this. 

it should be $1500 for @b4s36t4 and @s77rt

**Comment by puneetlath** [comment] 2023-07-24 15:18
Whoops. Sent contracts for the missed bonus payments.

**Comment by puneetlath** [comment] 2023-07-25 15:32
Bonuses paid. Thanks again!

**Closed by puneetlath** 2023-07-25 15:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
