### ISSUE TITLE
[HOLD for payment 2023-09-04] Console error on opening the report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25616] opened 2023-08-21 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
To reproduce open report which has money request previews.
1. Open any chat report
2. Observer the console error(Unexpected text node: . A text node cannot be a child of a <View>)
## Expected Result: 
Console error should not occur
## Actual Result: 
Console error occurs(Unexpected text node: . A text node cannot be a child of a <View>)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bb27e7b7-a57d-4147-9629-1620f7e4863f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692641891784579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2023-08-21 19:34
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Console error on opening the report which has money request previews
### What is the root cause of that problem?
It seems to be a regression from this [PR](https://github.com/Expensify/App/pull/24235) where we are using string variable for a conditional rendering. For an empty string it tries to render empty Text and causes the issue.
https://github.com/Expensify/App/blob/d1cf9be0d28128e921c2ba606cde680f2fa537d7/src/components/ReportActionItem/MoneyRequestPreview.js#L257-L261
### What changes do you think we should make in order to solve the problem?
Use `!_.isEmpty(requestMerchant)` to convert it to a boolean to avoid rendering unexpected empty Text which prevents the issue `Unexpected text node: . A text node cannot be a child of a <View>.`.

**Comment by s77rt** [comment] 2023-08-21 21:21
cc @Li357

**Comment by Li357** [comment] 2023-08-21 21:26
@s77rt Will address here! https://github.com/Expensify/App/pull/25613

**Comment by roryabraham** [comment] 2023-08-21 21:38
Not able to reproduce on staging, not a deploy blocker.

**Comment by mountiny** [comment] 2023-08-22 14:56
This was deployed yesterday so its a deploy blocker, assigning @Li357 as he ha a fix up

**Comment by sakluger** [comment] 2023-08-22 17:41
The [PR](https://github.com/Expensify/App/pull/25613) was merged, can we remove the deploy blocker?

**Comment by mountiny** [comment] 2023-08-23 18:46
Cant reproduce anymore @Pujan92 Can you confirm

If that is the case @bfitzexpensify can you please pay out $250 to @Pujan92 for reporting?

**Comment by Pujan92** [comment] 2023-08-23 18:47
Yes @mountiny , not reproducible now.

**Comment by Li357** [comment] 2023-09-04 14:31
No regression steps needed.

**Comment by bfitzexpensify** [comment] 2023-09-05 09:59
Offer sent for reporting @Pujan92

**Comment by Pujan92** [comment] 2023-09-05 10:16
> Offer sent for reporting @Pujan92

Accepted @bfitzexpensify :)

**Comment by bfitzexpensify** [comment] 2023-09-05 11:41
Cool, all paid out, we're done here!

**Closed by bfitzexpensify** 2023-09-05 11:41 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
