### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Web- Action menu - Unable to navigate options in Action menu using Arrow keys

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23280] opened 2023-07-20 15:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to site
2. Open a conversation
3. Click on a chat
4. Open action menu
5. Use arrow keys and TAB to navigate
6. Tap FAB
7. Use Arrow Keys and TAB to navigate

## Expected Result:
Like in FAB, user must be able to navigate using both arrow keys and TAB button.

## Actual Result:
On pressing FAB, user can navigate through options using both arrow keys and TAB button. In Action Menu, user can navigate only using TAB . He cannot use arrow keys and navigate through options in Action menu,

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5c8cfa1f-12d6-4ce2-8d1a-34f4b11d096c

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eeba1242aba22472</li>
        <li>Upwork Job ID: 1682468481034489856</li>
        <li>Last Price Increase: 2023-07-21</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26241505</li>
<li>samh-nl | Contributor | 26748431</li>
</ul></li>
    </ul>
</details>

**Comment by IftikharNadeem12** [comment] 2023-07-21 21:22
import React, { useRef, useEffect } from 'react';
import { View, TouchableOpacity, Text, Keyboard } from 'react-native';

const ChatComponent = () => {
  const item1Ref = useRef(null);
  const item2Ref = useRef(null);
  // Add more refs for other menu items if needed

  useEffect(() => {
    const handleArrowKeyPress = (event) => {
      if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
        // Prevent default arrow key behavior, such as scrolling
        event.preventDefault();

        // Get the currently focused element
        const currentlyFocusedItem = item1Ref.current || item2Ref.current;
        if (!currentlyFocusedItem) return;

        // Find the next focusable element based on the Arrow key pressed
        const nextFocusableItem = event.key === 'ArrowDown' ? item2Ref.current : item1Ref.current;

        // Focus the next element
        if (nextFocusableItem) {
          nextFocusableItem.focus();
        }
      }
    };

    // Add event listener for keydown
    Keyboard.addListener('keydown', handleArrowKeyPress);

    // Clean up the event listener on component unmount
    return () => {
      Keyboard.removeListener('keydown', handleArrowKeyPress);
    };
  }, []);

  // Your chat component code with TouchableOpacity for each menu item
};

**Comment by IftikharNadeem12** [comment] 2023-07-21 21:23
import React, { useRef, useEffect } from 'react';
import { View, TouchableOpacity, Text, Keyboard } from 'react-native';

const ChatComponent = () => {
  const item1Ref = useRef(null);
  const item2Ref = useRef(null);
  // Add more refs for other menu items if needed

  useEffect(() => {
    const handleArrowKeyPress = (event) => {
      if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
        // Prevent default arrow key behavior, such as scrolling
        event.preventDefault();

        // Get the currently focused element
        const currentlyFocusedItem = item1Ref.current || item2Ref.current;
        if (!currentlyFocusedItem) return;

        // Find the next focusable element based on the Arrow key pressed
        const nextFocusableItem = event.key === 'ArrowDown' ? item2Ref.current : item1Ref.current;

        // Focus the next element
        if (nextFocusableItem) {
          nextFocusableItem.focus();
        }
      }
    };

    // Add event listener for keydown
    Keyboard.addListener('keydown', handleArrowKeyPress);

    // Clean up the event listener on component unmount
    return () => {
      Keyboard.removeListener('keydown', handleArrowKeyPress);
    };
  }, []);

  // Your chat component code with TouchableOpacity for each menu item
};


**My Upwork Profile is; 

Iftikhar Nadeem**

https://www.upwork.com/freelancers/iftikharnadeem

**Comment by IftikharNadeem12** [comment] 2023-07-21 21:25
Contributor Details;

My Expensify account email: ijweaver2004@gmail.com
My Upwork Profile Link;

https://www.upwork.com/freelancers/iftikharnadeem

**Comment by jscardona12** [comment] 2023-07-21 21:43
## Proposal: Implement Keyboard Navigation for Context Menu

### Problem:

The current implementation of the `BaseReportActionContextMenu` component in React Native lacks keyboard navigation support using arrow keys. As a result, users who rely on keyboard input are unable to easily navigate through the context menu options, leading to a subpar user experience and accessibility issues.

### Root Cause:

The root cause of the problem is the absence of event listeners and handling for keyboard events in the `BaseReportActionContextMenu` component. Without capturing arrow key presses, the component cannot update the selected index of the context menu options or apply a selected style to the corresponding menu item, hindering keyboard navigation.

### Solution:

To solve the problem and enable keyboard navigation, we propose the following changes to the `BaseReportActionContextMenu` component:

1. **Event Listeners for Keyboard Events:**
   - Implement event listeners for the `'keydown'` event on the component. These event listeners will capture keyboard input, allowing us to respond to arrow key presses.

2. **Handle Arrow Key Presses:**
   - In the event handler for the `'keydown'` event, specifically check for arrow key presses (`ArrowUp` and `ArrowDown`).
   - Prevent the default behavior of the arrow keys to avoid unintended scrolling or other interactions.

3. **Update Selected Index:**
   - Track the selected index of the context menu options within the component's state.
   - When an arrow key is pressed, update the selected index accordingly, ensuring it stays within the bounds of the available menu options.

4. **Apply Selected Style:**
   - Modify the rendering of the context menu items to apply a selected style to the item corresponding to the current selected index.
   - This can be achieved through the use of the `isSelected` prop passed to the `ContextMenuItem` component or by applying specific styles to the selected menu item.

### Implementation Details:

[Implementation Details Code](https://github.com/jscardona12/ExpensifyJuanC/commit/3a149b8e3d5b531cbd639fc6fe48492d743f3869
)


### Working Solution:


https://github.com/Expensify/App/assets/16781411/931cdde1-7dce-4a2d-84ae-bee7e75b92a6

**Comment by jscardona12** [comment] 2023-07-21 21:46
Hi @0xmiroslav, let me know what do you think about the above [Proposal](https://github.com/Expensify/App/issues/23280#issuecomment-1646267026). 

Thanks!

**Comment by maddylewis** [comment] 2023-07-24 17:17
waiting for an update on @samh-nl's question here - https://github.com/Expensify/App/issues/16259#issuecomment-1648193154

**Comment by marcaaron** [comment] 2023-07-25 19:55
yes, I would recommend we HOLD this issue on https://github.com/Expensify/App/issues/16259

**Comment by maddylewis** [comment] 2023-07-27 13:40
holding based on - https://github.com/Expensify/App/issues/23280#issuecomment-1650450830

**Comment by maddylewis** [comment] 2023-08-06 20:06
still holding

**Comment by situchan** [comment] 2023-08-10 04:18
The holding [PR](https://github.com/Expensify/App/pull/23934) was merged.
I'd like to take this as C+ based on [discussion](https://expensify.slack.com/archives/C02NK2DQWUX/p1691641008846119?thread_ts=1691488353.531539&cid=C02NK2DQWUX)

**Comment by situchan** [comment] 2023-08-14 04:05
@maddylewis can you please assign me here?

**Comment by maddylewis** [comment] 2023-08-30 20:32
@situchan let us know if we're good to move forward with this one - https://github.com/Expensify/App/issues/23280#issuecomment-1696994506

**Comment by maddylewis** [comment] 2023-09-08 14:59
@situchan - let us know if we can move forward with @samh-nl's proposal - thx!

**Comment by situchan** [comment] 2023-09-08 15:29
> @situchan - let us know if we can move forward with @samh-nl's proposal - thx!

@samh-nl's proposal is incomplete as seen in video. A few more things to consider:
- enter key press event
- unnecessary first index


https://github.com/Expensify/App/assets/108292595/5c2389e1-3298-49e4-a024-c2e985301746

**Comment by situchan** [comment] 2023-09-08 16:13
@samh-nl your solution still doesn't solve:
- unnecessary first index

As you see my video, I should press 6 times in a loop while 5 menu items total

**Comment by situchan** [comment] 2023-09-08 16:31
> first menu item is not always shown

It's quick emoji reactions list which is not MenuItem.

**Comment by maddylewis** [comment] 2023-09-18 18:59
@situchan - let us know once you've reviewed updated proposal - ty! 

https://github.com/Expensify/App/issues/23280#issuecomment-1713949416

**Comment by situchan** [comment] 2023-09-19 05:47
@samh-nl's [proposal](https://github.com/Expensify/App/issues/23280#issuecomment-1644162724) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by francoisl** [comment] 2023-09-19 06:43
Looks good to me as well, let's go with your proposal @samh-nl

**Comment by francoisl** [comment] 2023-09-25 03:15
Reposting @situchan's [message](https://github.com/Expensify/App/pull/27877#issuecomment-1731058680) regarding the bonus from the PR here:

> There's 2 hrs delay from bonus timeline but it would be much appreciated if it's still eligible unless any regression found. The delay was just from variable name change and @samh-nl was sleeping at that moment. cc: @francoisl

@maddylewis do you know if we have any precedent in a situation like this?

**Comment by maddylewis** [comment] 2023-10-02 13:34
## Payments
- [ ] Reporting bonus: N/A
- [ ] Contributor: @samh-nl ($1k via Upwork)
- [ ] C+: @situchan ($1k via Upwork)

**Comment by maddylewis** [comment] 2023-10-02 13:34
@situchan will you review this checklist when you have a chance? https://github.com/Expensify/App/issues/23280#issuecomment-1733293500

**Comment by situchan** [comment] 2023-10-02 13:36
This is kind of feature request than bug

**Comment by situchan** [comment] 2023-10-02 14:22
**Regression Test Proposal** (web/desktop only)
1. Go to any chat that has a message
2. Right-click the message
3. Verify that context menu opens
4. Repeat pressing up/down arrows from keyboard
5. Verify that selected option changes based on arrow key
6. Verify that first option is selected on Down press when last option is selected
7. Verify that last option is selected on Upon press when first option is selected
8. Press Enter on any selected option
9. Verify that it triggers action of selected option correctly and context menu closes

**Comment by maddylewis** [comment] 2023-10-02 17:42
offers sent 👍

**Comment by situchan** [comment] 2023-10-02 17:48
@maddylewis Accepted, thanks. Can you also please check bonus eligibility?

**Comment by maddylewis** [comment] 2023-10-02 17:52
included bonus

**Comment by maddylewis** [comment] 2023-10-02 17:57
@situchan - i think i paid you twice. i'll request a refund for the $1k payment.

**Comment by situchan** [comment] 2023-10-02 18:03
@maddylewis can we use that 1k for #24610 which is due payment for more than a month?

**Comment by maddylewis** [comment] 2023-10-04 20:03
haha, yes for sure!

**Comment by maddylewis** [comment] 2023-10-04 20:05
confirmed here that the double payment can be used for the outstanding issue here - https://github.com/Expensify/App/issues/24610

**Closed by maddylewis** 2023-10-04 20:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
