### ISSUE TITLE
[HOLD for payment 2024-03-20] [HOLD for payment 2024-03-19] [$500] Tag - Tag list shows old tag as selected when newer tag is selected in Split scan request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38042] opened 2024-03-11 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has tags.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Split bill > Scan.
4. Create a scan split with a tag.
5. Click on the split preview.
6. Click Tag.
7. Select a different tag.
8. Click Tag.

## Expected Result:
The Tag list will show the newly-selected tag on the top

## Actual Result:
The Tag list shows the original tag selected in Step 4 on the top.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/24c4ae8f-7a4e-4aed-8fde-8aebe6c6e96b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e2d605b4f1b0cbe</li>
        <li>Upwork Job ID: 1767210397356195840</li>
        <li>Last Price Increase: 2024-03-11</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-11 13:30
We think that this bug might be related to #wave6-collect-submitters
cc @greg-schroeder

**Comment by mountiny** [comment] 2024-03-11 13:40
Seems like this might be related to @FitseTLT @puneetlath @neil-marcellini @ishpaul777 https://github.com/Expensify/App/pull/37879

**Comment by nkdengineer** [comment] 2024-03-11 13:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The edited tag isn't applied in split bill request

### What is the root cause of that problem?
In split bill requests, we save the draft data in `splitDraftTransaction` field instead of `transaction` field. But in here, we always get tag from `transaction` field

https://github.com/Expensify/App/blob/bf1ff4c428b454caebd44ab9057f8739c2cbd107/src/pages/iou/request/step/IOURequestStepTag.js#L90

### What changes do you think we should make in order to solve the problem?
We should use information from the `splitDraftTransaction` field if `isEditingSplitBill` is true like we did in IOURequestStepCategory

https://github.com/Expensify/App/blob/bf1ff4c428b454caebd44ab9057f8739c2cbd107/src/pages/iou/request/step/IOURequestStepCategory.js#L76
 
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-03-11 13:56
@ishpaul777 This issue isn't caused by https://github.com/Expensify/App/pull/37879

**Comment by DylanDylann** [comment] 2024-03-11 14:01
Agree with @nkdengineer. I noticed this bug and reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1710156718325559). Could I take over this issue as a C+ role?

**Comment by kbecciv** [comment] 2024-03-11 14:07
@mountiny The QA team is uncertain whether selecting one multilevel tag will deselect another. Should we treat this as the same issue, or do we need to create a new one?

https://github.com/Expensify/App/assets/93399543/dd552a90-14cc-49e0-bfbf-05256bf4814b

**Comment by DylanDylann** [comment] 2024-03-11 14:08
@mountiny For more information about this bug, I handled many bugs that relate to new money request refactoring:
 + https://github.com/Expensify/App/issues/34608
 + https://github.com/Expensify/App/issues/34606
 + https://github.com/Expensify/App/issues/34611
 + https://github.com/Expensify/App/issues/34609

In these issues, we need to use `splitDraftTransaction` instead of "transaction" if isEditingSplitBill is true like @nkdengineer's solution. It seems @dukenv0307 missed this logic in this PR that caused this issue

From above information, @nkdengineer's proposal is good solution

**Comment by DylanDylann** [comment] 2024-03-11 14:40
About the [additional bug](https://github.com/Expensify/App/issues/38042#issuecomment-1988528602), we also should handle here

@nkdengineer For the tag section, we allow multiple tags so we also need to set the index for the tag in splitDraftTransaction and use `TransactionUtils.getTag` to get the correct index tag.

**Comment by DylanDylann** [comment] 2024-03-11 14:54
Look good. @nkdengineer's updated proposal fixes both issues

cc @mountiny

**Comment by mountiny** [comment] 2024-03-11 15:26
Thanks @DylanDylann

@nkdengineer can you raise the PR asap? thanks!

**Comment by nkdengineer** [comment] 2024-03-11 17:21
Sure

**Comment by nkdengineer** [comment] 2024-03-11 18:22
will open draft PR in next 20 mins

**Comment by luacmartins** [comment] 2024-03-11 22:48
This is fixed in staging!

**Comment by sakluger** [comment] 2024-03-18 19:32
Hey @nkdengineer, could you please apply to the Upwork job (https://www.upwork.com/jobs/~017e2d605b4f1b0cbe), or alternatively, link to your Upwork profile here so that I can send you an offer?

@DylanDylann could you please complete the BZ checklist?

**Comment by DylanDylann** [comment] 2024-03-19 14:45
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the [PR](https://github.com/Expensify/App/pull/35136)
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to [comment](https://github.com/Expensify/App/pull/35136#discussion_r1530515979)
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

Precondition::

 User is an employee of Collect workspace.
 The Collect workspace has tags.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Split bill > Scan.
4. Create a scan split with a tag.
5. Click on the split preview.
6. Click Tag.
7. Select a different tag.
8. Click Tag.
9. The Tag list will show the newly-selected tag on the top


Do we agree 👍 or 👎

**Comment by luacmartins** [comment] 2024-03-19 18:45
We'll add test steps once the feature is fully implemented. No need to add them now.

**Comment by sakluger** [comment] 2024-03-20 19:52
Summarizing payment on this issue:

Contributor: @nkdengineer $500, sent offer via Upwork (https://www.upwork.com/nx/wm/offer/101491657)
Contributor+: @DylanDylann $500, paid via Upwork 


@nkdengineer please let me know once you've accepted the offer.

**Comment by nkdengineer** [comment] 2024-03-22 06:54
@sakluger I've accepted the offer, thanks.

**Comment by sakluger** [comment] 2024-03-22 15:01
Thank you! All contracts have been paid out.

**Closed by sakluger** 2024-03-22 15:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
