### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] On task title editing page when title field is empty than error message is `This field is required` instead of `please enter a title`

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19023] opened 2023-05-16 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app -> Login in account
2. Click on FAB button -> Click on Assign task option
3. Enter title -> Assign task -> Click on confirm task -> will navigate to task detail page
4. On task detail page click on Task (name) -> clear title field and press save -> Notice error message is `This field is required` instead of `please enter a title`

## Expected Result: 
On task title editing page error message should be `please enter a title` when empty
## Actual Result:  
On task title editing page error message is `This field is required` which is not inconsistent to other pages of task

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/272b3410-0265-43fd-9e9e-170c812e4d25" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/9b843ab7-0ef2-4842-85fe-13a5880386f1" width="40%" height="40%">

<img width="960" alt="ffd" src="https://github.com/Expensify/App/assets/43996225/bc02dc26-fdde-4dad-9915-47b352145b04">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684138217007209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af6e96d10c81b9cb</li>
        <li>Upwork Job ID: 1660741242395484160</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-16 14:54
### Proposal
by 
[@Dhairya Senjaliya](https://expensify.slack.com/team/U03DZEN48SC)

### Please re-state the problem that we are trying to solve in this issue.
- On task title editing page when title field is empty than error message is `This field is required` instead of `please enter a title`
### What is the root cause of that problem?
The reason is we are using general form error `common.error.fieldRequired`
### What changes do you think we should make in order to solve the problem?
We have already defined an error message if task name is empty which is `newTaskPage.pleaseEnterTaskName`
We just need to replace old message with new one on `validate()` inside the `TaskTitlePage.js`
```diff
      if (_.isEmpty(values.title)) {
-        errors.title = props.translate('common.error.fieldRequired');
+        errors.title = props.translate('newTaskPage.pleaseEnterTaskName');
      }
```
 ### What alternative solutions did you explore? (Optional)
- N/A

**Comment by alexpensify** [comment] 2023-05-17 17:35
@sophiepintoraetz  - I've run out of time to continue looking into this one. I'm OOO until Wednesday, May 24, and following the [new process](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799). I'm reassigning the Bug label to identify if this is a bug. Thank you!

**Comment by sophiepintoraetz** [comment] 2023-05-19 16:09
I'm not able to replicate this on staging on iOS (v1.3.16-0) or desktop (v1.3.16-5)
<img width="498" alt="image" src="https://github.com/Expensify/App/assets/42940078/a37b170a-1283-4837-a80b-a060e90919b6">

![IMG_0882](https://github.com/Expensify/App/assets/42940078/28d38700-99c7-4d3e-8b59-0099b9bbf8e2)

**Comment by sophiepintoraetz** [comment] 2023-05-19 16:34
Ah, I needed to confirm the task by sharing first - I am able to reproduce
![IMG_0883](https://github.com/Expensify/App/assets/42940078/8a6d45d2-5a8c-4173-8b61-b70c8fd50f53)

**Comment by sophiepintoraetz** [comment] 2023-05-22 09:33
@greg-schroeder - in case there's any movement on the issue between Al coming back in office on Wed - assigning you in case something happens!

**Comment by sophiepintoraetz** [comment] 2023-05-22 10:34
Oh, I thought that's what flo decides...?

**Comment by flodnv** [comment] 2023-05-22 15:44
@thienlnam do you agree this is a bug, or was it intentional?

**Comment by greg-schroeder** [comment] 2023-05-22 19:17
@sophiepintoraetz Ah got it, you assigned `Engineering` for that purpose cause you weren't sure. Got it! Sorry just coming into the middle I was a bit confused. :D

**Comment by thienlnam** [comment] 2023-05-22 19:37
I agree this is a bug, we can keep these consistent - though I feel like we should be using the default 'This field is required' for both pages instead of the other one

**Comment by flodnv** [comment] 2023-05-22 20:15
Why? Seems like the recommendation from everyone else is to use "Please enter a title", which I think is a better message (more descriptive)

**Comment by flodnv** [comment] 2023-05-22 20:17
I'm going to hire https://github.com/dhairyasenjaliya as per the above proposal but I'm struggling : https://expensify.slack.com/archives/C049HHMV9SM/p1684786642522019?thread_ts=1684138217.007209&cid=C049HHMV9SM

**Comment by greg-schroeder** [comment] 2023-05-22 20:25
Yeah, he just needs to comment I believe

**Comment by thienlnam** [comment] 2023-05-22 21:08
> Why? Seems like the recommendation from everyone else is to use "Please enter a title", which I think is a better message (more descriptive)

I don't feel strongly so we can go with what you suggest - my reasoning was the 'This field is required' messaging is commonly used throughout the app for missing fields in forms and there is no change here. The title is more specific sure, but it's also implied since the error exists right under the title input

**Comment by flodnv** [comment] 2023-05-22 21:47
Yeah I looked at the FORMS.md and it was not clear about this. @luacmartins is there any guidance about this^ specifically..?

**Comment by flodnv** [comment] 2023-05-23 16:55
Ok @dhairyasenjaliya let's do what @luacmartins said, and indeed do the update for other fields if you see it. Also please update FORMS.md

**Comment by eVoloshchak** [comment] 2023-05-23 20:43
There is also 'Please enter a routing number', 'Please enter an account number', 'Please enter an address', 'Please enter your date of birth', 'Please enter a password', 'Please enter your two factor code', 'Please enter your password', 'Please enter your magic code', 'Please enter your two factor code', 'Please enter your authenticator code', 'Please enter your Expensify password' and others

**Comment by luacmartins** [comment] 2023-05-24 15:14
lol I was wrong and it seems like we already created 42k different error messages. Do we want to keep that pattern?

**Comment by flodnv** [comment] 2023-05-24 16:25
I personally much prefer specific error messages than seeing `This field is required` everywhere. Let's go with the original first proposal then.

**Comment by luacmartins** [comment] 2023-05-24 18:00
Makes sense. Let's do it!

**Comment by alexpensify** [comment] 2023-05-24 21:13
@greg-schroeder and @sophiepintoraetz - I appreciate your help here! I'm back online and removing your assignment.

**Comment by alexpensify** [comment] 2023-05-27 01:18
@eVoloshchak - When you get a chance, please fill out the checklist above. Thanks!

**Comment by alexpensify** [comment] 2023-05-27 01:23
@eVoloshchak and @dhairyasenjaliya - To prepare for the payment date, please apply to the job in Upwork: 

https://www.upwork.com/jobs/~01af6e96d10c81b9cb

Thanks!

**Comment by alexpensify** [comment] 2023-05-30 21:35
@eVoloshchak - When you get a chance, please apply for the job in Upwork so I'm ready for the payment date on June 2. Thanks!

**Comment by alexpensify** [comment] 2023-06-01 22:53
We are on track for payment tomorrow. I don't see an Urgency Bonus here but I did notice that @dhairyasenjaliya reported the bug and fixed it, so I will include that in the payment process.

**Comment by alexpensify** [comment] 2023-06-02 13:44
@dhairyasenjaliya - Thank you for flagging the concerns here, it looks like the automation missed the notice. I went back to manually audited the project and I see the assignment was on May 22. The PR was merged on May 24, so I will factor in the urgency bonus when I work on the payment process later today.

**Comment by eVoloshchak** [comment] 2023-06-02 16:25
-  The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/17940

- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/17940/files#r1214579816

-  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Don't think an additional discussion is needed here, this was just the wrong text used

-  Determine if we should create a regression test for this bug. A very minor bug with extremely low impact. Regression test isn't needed here

**Comment by alexpensify** [comment] 2023-06-02 21:24
@eVoloshchak and @dhairyasenjaliya - the payments have been prepared in Upwork. Please accept and I can complete the process.

**Comment by alexpensify** [comment] 2023-06-03 19:00
@eVoloshchak and @dhairyasenjaliya - everyone has been paid in Upwork. I'll wait to confirm again on Monday, then will close the GH.

**Closed** 2023-06-05 15:16 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
