### ISSUE TITLE
[Awaiting payment] [$250] Web - Chat - Error in JS console when right-clicking in the app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37877] opened 2024-03-07 10:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37316

**Version Number:** v1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** almexp2+777@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any chat with some attachments
2. Open JS console and refresh the page
3. Right click on any attachment
4. Refresh the page to clear your console 
5. Right-click on a chat message
6. Observe the console error
7. Refresh again
8. Right-click on a chat row in the LHN
9. Observe the console error

## Expected Result:
No errors appear in the JS console.

## Actual Result:
Error in JS console when right-clicking. 
Error: `'Cannot record touch end without a touch start`. [Source](https://github.com/Expensify/react-native-web/blob/04c6cbd111f2e38e6afd5cda2a8062c3ca75e813/packages/react-native-web/src/modules/useResponderEvents/ResponderTouchHistoryStore.js#L141). 

## Workaround:
N/A, right-clicking still works functionally. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2df5ee67-9d2a-46fd-9d53-eda93192982f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122ffd00715c18b6e</li>
        <li>Upwork Job ID: 1765696373749649408</li>
        <li>Last Price Increase: 2024-03-07</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-07 10:14
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by trjExpensify** [comment] 2024-03-07 11:03
Hey! 

1. #vip-vsb is correct as a chat bug. I can reproduce it reliably. 
2. It doesn't seem to be causing a functional issue. You can still right-click, so it has no impact on usability. 
3. Ideally we don't have JS warnings in the console though. This warning isn't limited to right-clicking attachments, but rather anywhere you right-click in the app (i.e a chat message, LHN chat row etc).
4. Looks like it's [something to do](https://github.com/Expensify/react-native-web/blob/04c6cbd111f2e38e6afd5cda2a8062c3ca75e813/packages/react-native-web/src/modules/useResponderEvents/ResponderTouchHistoryStore.js#L141) with the `recordTouchEnd` function and RNW, so I don't see why it can't be external. 

CC: @mountiny quick hip check. Shall we proceed to find a fix for this? I'm not aware of a logical reason for not recording a `touch start` with the right-click action.

**Comment by mountiny** [comment] 2024-03-07 11:06
I agree with the assessment, I think its best to get rid of the error so I would export this issue for contributors for $250

**Comment by trjExpensify** [comment] 2024-03-07 11:10
Sounds good!

**Comment by trjExpensify** [comment] 2024-03-11 11:11
What do you think, @mananjadhav?

**Comment by mananjadhav** [comment] 2024-03-11 17:32
While @dukenv0307's proposal looks promising, I first tried reproducing it and I can't. I tried on `v1.4.50-2`, MacOS Chrome and Safari both.

https://github.com/Expensify/App/assets/3069065/d8276d2f-208d-4412-ab70-07e7725b681e

**Comment by mananjadhav** [comment] 2024-03-13 18:11
Sorry my bad I was checking the Errors only and not warnings.

> additionally check `isPrimaryPointerDown(domEvent)` only when updating the `trackedTouchCount` [here](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/modules/useResponderEvents/ResponderSystem.js#L312) so it shouldn't affect the recordTouchTrack operation

I am inclined to have this solution, but I can see `isPrimaryPointerDown` is used only at one place so we might just update the method to `isPrimaryOrSecondaryPointerDown`.

Going to take a feedback from internal engineer. But @dukenv0307's proposal/alternative works for me.

🎀 👀 🎀 C+ reviewed

**Comment by deetergp** [comment] 2024-03-15 23:30
I think renaming it to `isPrimaryOrSecondaryPointerDown` is fine. I've assigned @dukenv0307.

**Comment by trjExpensify** [comment] 2024-03-18 10:56
Cool, looking forward to the PR, @dukenv0307!

**Comment by deetergp** [comment] 2024-03-27 04:18
PR is currently being tested on staging

**Comment by mananjadhav** [comment] 2024-03-31 16:37
This was deployed on production 4 days ago but the payout date wasn't updated.

**Comment by mananjadhav** [comment] 2024-04-04 22:19
@trjExpensify This is ready for payout. 

We don't have any offending PR and we don't need any regression test for this.

**Comment by mananjadhav** [comment] 2024-04-08 11:47
@trjExpensify Can you help here?

**Comment by trjExpensify** [comment] 2024-04-08 14:12
Yup! Payment summary as follows:

- $250 to @dukenv0307 for the fix (Paid!)
- $250 to @mananjadhav for the C+ review (feel free to submit a request!)

Thanks!

**Closed by trjExpensify** 2024-04-08 14:12 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-04-09 13:52
$250 approved for @mananjadhav
