### ISSUE TITLE
[$500] Web - Composer - 'Write something...' is not vertically center aligned when clicking 'Go back to hom

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33708] opened 2023-12-28 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to ND staging
2. Open new tab > enter https://staging.new.expensify.com/anything
in address bar
3. Press enter
4. Click on 'Go back to home page' link

## Expected Result:
'Write something...' should be vertically aligned within the composer

## Actual Result:
'Write something...' is not vertically aligned within the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f7767b23-0026-430d-8439-87585c3389e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164dc28319bb85e74</li>
        <li>Upwork Job ID: 1740374460272353280</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-28 14:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The composer is not styled correctly after navigating from NotFound route.

### What is the root cause of that problem?
This is happening because the Composer is being rendered in the background of the NotFound page with the `numberOfLines = 0`, as it's trying to fetch the value from Onyx by a non-existing report ID here:

https://github.com/Expensify/App/blob/d76eaef1dc405e8be00d08509b6255063d61a037/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L616-L621

### What changes do you think we should make in order to solve the problem?
We should set the initial value of the `numberOfLines` to 1:

```js
        numberOfLines: {
            key: ({reportID}) => `${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT_NUMBER_OF_LINES}${reportID}`,
            // We might not have number of lines in onyx yet, for which the composer would be rendered as null
            // during the first render, which we want to avoid:
            initWithStoredValues: false,
            initialValue: 1,
        },
```



### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-12-29 09:15
@slafortune Can you confirm dupe and close this?

**Comment by shubham1206agra** [comment] 2024-01-03 03:34
@slafortune Bump on the above.

**Comment by slafortune** [comment] 2024-01-03 15:22
Sorry for the delay - Yes, closing this as a dupe 👍

**Closed by slafortune** 2024-01-03 15:22 UTC
Labels: External, Daily, Help Wanted, Bug
