### ISSUE TITLE
Workspace Invite Member Page Animation Not Smooth

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22524] opened 2023-07-09 05:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to app
2. Go To Settings
3. Go To Workspaces
4.  Select A Workspace
5. Click On Invite
## Expected Result: 
Animation To Invite Member Should Be Smooth
## Actual Result: 
Animation To Invite Member Is Not Smooth

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d26800e8-540f-4c61-9319-006804ffb91f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @syedsaroshfarrukhdot
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687301978741149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2023-07-12 07:46
reviewing today

**Comment by dylanexpensify** [comment] 2023-07-13 12:29
unable to repro, @syedsaroshfarrukhdot can you confirm if this is still occurring on MacOS/Safari w/latest build?

**Comment by syedsaroshfarrukhdot** [comment] 2023-07-13 21:25
Not able to reproduce on latest build.

**Comment by dylanexpensify** [comment] 2023-07-14 11:56
Thanks for confirming! closing!

**Closed by dylanexpensify** 2023-07-14 11:56 UTC
Labels: Daily, Needs Reproduction, Bug
