### ISSUE TITLE
After resizing window shows the "Hmm... it's not here" page for the contact method details page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21802] opened 2023-06-28 14:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App, Go to Settings > Profile > Contact method
2. Press New contact method > Add any email that already has an Existing account
3. Press Add
4. We can see a red dot for the newly added contact method > Press on the contact method
5. Press Remove
6. Remove confirmation modal will be displayed now resize the window until it shows only the contact details screen
## Expected Result:
Modal should be closed, and we should be able to see the contact method detail page.
## Actual Result:
After resizing window, contact method is deleted, and the "Hmm... it's not here" page is displayed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/04cb625b-1666-4895-aa96-2d77024d0ec5

https://github.com/Expensify/App/assets/43996225/5c21f79c-6a76-4e8b-9ace-0e7cf617b6cb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687775502215429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lealobanov** [comment] 2023-06-28 15:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After resizing window, 'Remove Contact' modal disappears and the "Hmm... it's not here" page is displayed instead.

### What is the root cause of that problem?

The 'Hmm, it's not here' error view is triggered in the ContactMethodDetailsPage component when:

```
const loginData = this.props.loginList[contactMethod];
        if (!contactMethod || !loginData) {
            return <NotFoundPage />;
        }

```

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-06-28 15:47
### Proposal

After resizing window(between web and mobile), `OpenApp` api is called.
But `LOGIN_LIST` value is not updated for invalid email (red dot 🔴 ).
`LOGIN_LIST` value is not updated for valid email (green dot ).
so after resize or reload app, app lost invalid email data.

Solution: need to update LOGIN_LIST value when call `AddNewContactMethod`

Thanks

**Comment by bernhardoj** [comment] 2023-06-29 10:21
Dupe of https://github.com/Expensify/App/issues/19287 which is closed for https://github.com/Expensify/App/issues/17827

**Comment by michaelhaxhiu** [comment] 2023-07-03 23:51
@bernhardoj do you mean this is a dupe of https://github.com/Expensify/App/issues/19287

@jayeshmangwani do you agree?

**Comment by michaelhaxhiu** [comment] 2023-07-03 23:53
I agree with @bernhardoj (thanks for your input!) and will close this GH as a dupe report here. LMK if you disagree @jayeshmangwani

**Closed by michaelhaxhiu** 2023-07-03 23:53 UTC
Labels: Daily, Bug
