### ISSUE TITLE
Android\IOS - Unable to move cursor to the place I want after copy the URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11859] opened 2022-10-14 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Select any user and type any URL
4. Copy the URl and paste on composed box
5. Try to move the cursor in the middle of URL

## Expected Result:
Able to move cursor to the place I want after copy the URL

## Actual Result:
Unable to move cursor to the place I want after copy the URL

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.15.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195906324-afbf2faf-7ad8-460b-8aff-b288e3ddf71e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-10-15 17:07
Also user can not paste the copied text. Let me know if we need a separate issue for this one.

https://user-images.githubusercontent.com/93399543/195999104-3b4b265c-c14a-4c4e-808d-cf272f5da018.mp4

**Comment by grgia** [comment] 2022-10-17 17:07
Not overdue, checking for duplicates

**Comment by grgia** [comment] 2022-10-17 17:28
Duplicate of https://github.com/Expensify/App/issues/11867

**Closed by grgia** 2022-10-17 17:28 UTC
Labels: Engineering, Daily
