### ISSUE TITLE
[$500] No participant image is shown in details page for group chats that are old - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11319] opened 2022-09-27 04:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any group chat already present in LHN.
2. Click on header to open details page.

## Expected Result:
Participant images are shown.

## Actual Result:
No participant images are shown.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- IOS

**Version Number:** 1.1.92-0
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/192430986-739fad47-4644-44f1-b2f6-ad380bc61c5e.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661668398972989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-10-19 05:50
I'm getting a grey avatar when testing this on iOS mobile v 1.2.17. 

![RPReplay_Final1666158334 (1)](https://user-images.githubusercontent.com/51066321/196607301-7d093ac6-fd4f-4461-a186-d6bf904f88ce.gif)

So I think this is related to this GH: https://github.com/Expensify/App/issues/10704 or this GH https://github.com/Expensify/App/issues/11425

Sending to eng for a buddy check.

**Comment by chiragsalian** [comment] 2022-10-19 18:50
I can't reproduce either on staging. I tested on ios on staging.
I tried those steps i.e., I went to 3 different group chats, clicked on the header, and for all of them I see the profile icon.

Can you retest on web on staging @mvtglobally, after deleting indexed data, with console open and checking for any console errors?

**Comment by chiragsalian** [comment] 2022-10-21 23:52
Friendly bump to retest @mvtglobally when you get the chance 🙂

**Comment by mvtglobally** [comment] 2022-10-24 04:42
@chiragsalian we were not able to reproduce. I asked team to double check as well

**Comment by chiragsalian** [comment] 2022-10-24 17:09
Cool, let me know once your team retests 👍

**Comment by chiragsalian** [comment] 2022-10-27 00:01
Friendly bump, was there any update here?

**Comment by aneequeahmad** [comment] 2022-10-28 02:57
@chiragsalian I'm able to repro this on latest production [1.2.20-3](https://github.com/Expensify/App/releases/tag/1.2.20-3)

Video:

https://user-images.githubusercontent.com/36359331/198484498-451694f1-7c9f-4aeb-ae9c-9a565685eef6.mov

**Comment by chiragsalian** [comment] 2022-10-28 17:28
Ah awesome, okay now im able to reproduce it on both staging and production. This should be straightforward to address. Adding External label and demoting to weekly.

**Comment by sophiepintoraetz** [comment] 2022-10-30 23:33
[Job posted!](https://www.upwork.com/jobs/~011e9bb1d6b3bd9eda)

**Comment by aneequeahmad** [comment] 2022-10-31 00:29
### **PROPOSAL**

**Root cause:**

- Avatar image is not shown since there is no data of this participant present in `user personal details` except `display name which is the email of participant` can be seen in video attached.

**Video:**

https://user-images.githubusercontent.com/36359331/198909477-e14052c1-2c06-4813-9661-6446467caf15.mov

Solution:

- We shouldn't show that user in `ReportParticipantsPage` which doesn't have the `personal details data available` and only have display name nothing other than that.

**Comment by Santhosh-Sellavel** [comment] 2022-10-31 17:52
Removing/Not showing participants is bad

@chiragsalian Any chance this could be internal? Why those details are missing?

The way I see it, we should investigate why it's not received or not fetched and fix it.

Can we bump this to weekly while wait for better proposal, thanks!

**Comment by sophiepintoraetz** [comment] 2022-10-31 18:25
Yeah, that might be a Melvin-bot thing (I moved it to weekly yday) - @Santhosh-Sellavel - potentially because help is wanted?

**Comment by chiragsalian** [comment] 2022-10-31 23:08
> Any chance this could be internal? Why those details are missing?

I think external is best. This is because some people haven't uploaded any avatar or perhaps have very new accounts so there is no data like first name, last name or avatar information setup just yet. Or maybe the backend has not set defaults for some of the older accounts/chat reports. We could have it internal such that PHP layer always provides the default but it feels like it would be easiest to use a default in the front end when avatar information is not present.

Plus without investigating too deeply I think the solution would be to use Expensicons.FallbackAvatar when there is nothing to display there. I'm wondering if that would suffice or if there will be a color mismatch of the avatars? Anyway let me know your thoughts.

**Comment by Santhosh-Sellavel** [comment] 2022-11-01 21:46
Agree, this could be external. Let's wait for proposals!

**Comment by sophiepintoraetz** [comment] 2022-11-04 01:54
[Posted](https://expensify.slack.com/archives/C01GTK53T8Q/p1667526772175659) in #open-source doubling the price.

**Comment by aneequeahmad** [comment] 2022-11-07 11:45
This issue has been fixed on `November 2nd, 2022` in commit # `7d1c5bbc2`. Not reproducible.

cc: @sophiepintoraetz, @Santhosh-Sellavel

Screenshot:
<img width="1191" alt="Screenshot 2022-11-07 at 4 42 02 PM" src="https://user-images.githubusercontent.com/36359331/200302196-6490dc7b-7768-4e06-932a-5e26e317c010.png">

**Comment by Santhosh-Sellavel** [comment] 2022-11-07 13:41
Ya I agree, this is no longer reproducible, thanks @aneequeahmad!
@chiragsalian we are good to close this one, please test it once before closing this(As this was not easily reproducible initially.)
cc: @sophiepintoraetz

**Comment by chiragsalian** [comment] 2022-11-07 18:09
Yup, it looks resolved.
![image](https://user-images.githubusercontent.com/14356145/200383512-268a2fc1-bff8-470f-8c8e-cd2feeae6709.png)

Thanks guys 🙇‍♂️ 
Closing issue.

**Closed by chiragsalian** 2022-11-07 18:09 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug

**Comment by aneequeahmad** [comment] 2022-11-07 20:24
Thanks for the effort everyone.

 @sophiepintoraetz I guess i'm eligible for the reporting bonus as this issue is fixed and deployed on production.

**Comment by sophiepintoraetz** [comment] 2022-11-08 22:28
@aneequeahmad - feel free to apply for the job here https://www.upwork.com/jobs/~011e9bb1d6b3bd9eda

**Comment by aneequeahmad** [comment] 2022-11-08 22:32
@sophiepintoraetz I applied for the job. Thanks for mentioning.
