### ISSUE TITLE
[$2000] Web -  Chat disappear after deleting thread first message in MoneyRequestPage

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23766] opened 2023-07-27 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the app
2. Go to any chat and request money
3. Click on the message to open up the request chat
4. Click once again on the money chat to open the Money Request report
5. Send any message
6. Reply in the thread
7. Delete thread first message
8. Notice that the chat has disappeared
9. Click back in the browser to take you to the money request page and no replies showing up!

## Expected Result:
The thread should stay appearing in the chat history and clicking on it should show the message deleted

## Actual Result:
It disappears. and message is not showing up in the MoneyRequestPage except if we start navigating from the main chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/23e8a62c-8c98-46c1-ad33-9fb3e20a05e4

https://github.com/Expensify/App/assets/93399543/e269bef9-4fa6-437e-b66e-5d19476581f7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @makiour
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690422160767899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9081856593312f9</li>
        <li>Upwork Job ID: 1686173305269719040</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>makiour | Reporter | 26062581</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-31 04:00
Cannot reproduce:

![image](https://github.com/Expensify/App/assets/59587260/6685b8bf-e071-4e31-a56c-661bae4c5b8c)

@makiour could you please try reproduce on version v1.3.47-3?

**Comment by kadiealexander** [comment] 2023-08-01 00:27
Still unable to reproduce (deleted thread still shows as expected):

![image](https://github.com/Expensify/App/assets/59587260/2076a60f-0168-4c33-91c3-af196c3a879a)

**Comment by Pal-Ahuja** [comment] 2023-08-01 01:32
Hi, 

Thanks for sharing this issue. I can definitely understand how this could adversely impact the user experience. 

Let me give it a tech thought along with my team and come back to you. 

thanks, 

Pal Ahuja

**Comment by Pal-Ahuja** [comment] 2023-08-01 01:43
Contributor details
Expensify account email: palinfocom.net@expensify.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f9425bd5b37caf69
--------------------------------------------------------------------------------------------
Hi,

Thanks for sharing this issue. I can definitely understand how this could adversely impact the user experience.

Let me give it a tech thought along with my team and come back to you.

thanks,

Pal Ahuja

**Comment by ashrafalgaher** [comment] 2023-08-01 01:47
Contributor details
Your Expensify account email: ashrafalgaher@gmail.com<REPLACE EMAIL HERE>
Upwork Profile Link: <[REPLACE LINK HERE](https://www.upwork.com/freelancers/~01421e76cfe70bd326)>

**Comment by ashrafalgaher** [comment] 2023-08-01 01:48
Contributor details
Your Expensify account email: ashrafalgaher@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01421e76cfe70bd326

**Comment by Pal-Ahuja** [comment] 2023-08-01 01:53
Contributor details
Expensify account email: pal.ahuja@palinfocom.net 
Upwork Profile Link: https://www.upwork.com/freelancers/~01f9425bd5b37caf69

Hi,

Thanks for sharing this issue. I can definitely understand how this could adversely impact the user experience.

Let me give it a tech thought along with my team and come back to you.

thanks,

Pal Ahuja

**Comment by ashrafalgaher** [comment] 2023-08-01 02:27
Contributor details
Your Expensify account email: [ashrafalgaher@gmail.com](mailto:ashrafalgaher@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01421e76cfe70bd326
There is a proposal for how I will fix the bug in the Expensify app:
Problem:
The bug in the Expensify app occurs when a user deletes a message in a chat thread. The deleted message disappears from the chat history, but it does not disappear from the MoneyRequestPage. This means that if the user clicks back to the MoneyRequestPage, they will not see the deleted message.
Cause:
The cause of the bug is likely a problem with the way that the chat history is saved. When a user deletes a message, the message is not actually deleted from the database. Instead, the message is marked as deleted. This means that the message is still technically in the chat history, but it is not visible to the user.
Solution:
The solution to the bug is to change the way that the chat history is saved. When a user deletes a message, the message should be deleted from the database. This will ensure that the message is no longer visible to the user, even if they click back to the MoneyRequestPage.
Steps:
To fix the bug, I will follow these steps:
Check the chat history to see if the message is actually being saved.
If the message is not being saved, I will make a change to the code that is responsible for saving the chat history.
I will test the change to make sure that it fixes the bug.
I will submit the code to the Expensify team for review.
Timeline:
I estimate that it will take me 1-2 days to fix the bug. I will keep the Expensify team updated on my progress.
Testing:
I will test the fix on all platforms to make sure that it works correctly. I will also include screenshots in my proposal to show that the fix works.
Conclusion:
I believe that this is a straightforward bug to fix. I am confident that I can fix the bug within 1-2 days. I will keep the Expensify team updated on my progress.
Thank you for your consideration.

**Comment by ashrafalgaher** [comment] 2023-08-01 03:13
Proposal


Problem:

The bug in the Expensify app occurs when a user deletes a message in a chat thread. The deleted message disappears from the chat history, but it does not disappear from the MoneyRequestPage. This means that if the user clicks back to the MoneyRequestPage, they will not see the deleted message.

Cause:

The cause of the bug is likely a problem with the way that the chat history is saved. When a user deletes a message, the message is not actually deleted from the database. Instead, the message is marked as deleted. This means that the message is still technically in the chat history, but it is not visible to the user.

Solution:

The solution to the bug is to change the way that the chat history is saved. When a user deletes a message, the message should be deleted from the database. This will ensure that the message is no longer visible to the user, even if they click back to the MoneyRequestPage.

Steps:

To fix the bug, I will follow these steps:

Check the chat history to see if the message is actually being saved.
If the message is not being saved, I will make a change to the code that is responsible for saving the chat history.
I will test the change to make sure that it fixes the bug.
I will submit the code to the Expensify team for review.
Timeline:

**Comment by kadiealexander** [comment] 2023-08-04 04:36
@situchan please take a look at this proposal, thank you!

**Comment by situchan** [comment] 2023-08-04 08:57
reviewing today

**Comment by StevenKKC** [comment] 2023-08-04 19:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat disappear after deleting thread first message in MoneyRequestPage.

### What is the root cause of that problem?
If delete the first thread message in money request report, the report's `lastMessageText` is set to empty.
As a result, in `ReportUtils.shouldReportBeInOptionList` function returns `false`.
https://github.com/Expensify/App/blob/c32fb5a9a04423bbfb5f07326431c8de186615aa/src/libs/ReportUtils.js#L2369-L2371
Therefore, the money request report is disappear in LHN.

### What changes do you think we should make in order to solve the problem?
We should exclude the money request report in [this line](https://github.com/Expensify/App/blob/c32fb5a9a04423bbfb5f07326431c8de186615aa/src/libs/ReportUtils.js#L2369).
```js
-   if (isChatThread(report) && !report.lastMessageText) {
+   if (isChatThread(report) && !report.lastMessageText && !isMoneyRequest(report)) {
        return false;
    }
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by kadiealexander** [comment] 2023-08-08 04:27
Have bumped @situchan [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1691468808160769).

**Comment by kadiealexander** [comment] 2023-08-14 01:44
On hold, not overdue :)

**Comment by kadiealexander** [comment] 2023-08-22 06:21
Thanks @dukenv0307, I'll remove the hold.

**Comment by kadiealexander** [comment] 2023-08-28 06:35
Not overdue, was on hold.

**Comment by shubham1206agra** [comment] 2023-08-28 07:08
@allroundexperts @kadiealexander Unable to repro this in DEV. Please confirm

**Comment by rojiphil** [comment] 2023-08-28 07:17
I too cannot reproduce. Would be good if we reconfirm this.

**Comment by shubham1206agra** [comment] 2023-08-29 03:08
Isn't this ideal behaviour with empty chats?

**Comment by kadiealexander** [comment] 2023-08-31 04:16
It's definitely fixed for me now too. Closing this as resolved.

![image](https://github.com/Expensify/App/assets/59587260/96f2d957-4699-4fe7-b21b-1889a810eb51)

@dukenv0307 if you're getting a different experience with just regular threads, can you please raise that as a new bug?

**Closed by kadiealexander** 2023-08-31 04:16 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
