### ISSUE TITLE
[HOLD for payment 2023-08-30] [$1000] Web - Markdown pasted from selection-copy is different from clipboard-copy

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23659] opened 2023-07-26 16:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Paste this markdown (it has a heading, then a code snippet and a quote)
### test heading 
```
Code snippet
```
> [link](www.example.com)
3. Now use the copy to clipboard option, and copy the sent message
4. Paste the message in the composer and send it again (notice that there are no difference in both messages)
5. Now select the sent message text by cursor and press cmd+c
6. Paste the text in the composer and send the message.
7. Notice that the markdown message has an extra line in the code snippet part.

## Expected Result:
Message copied from selection should be the same that that copied from context menu

## Actual Result:
Message copied from selection has an extra line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e5ccaade-8d95-4873-aa5a-765400214f61

https://github.com/Expensify/App/assets/93399543/48d6c3c0-e6b9-44ec-bc91-e47dc4a32722

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690364432300409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c94943755b5fa6d</li>
        <li>Upwork Job ID: 1684694244929720320</li>
        <li>Last Price Increase: 2023-08-03</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26012873</li>
<li>huzaifa-99 | Reporter | 26012875</li>
</ul></li>
    </ul>
</details>

**Comment by pbkompasz** [comment] 2023-07-28 06:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Markdown pasted from selection-copy is different from clipboard-copy

### What is the root cause of that problem?

Inconsistency between the `Copy to Clipboard` and the default copy (CMD+C/CTRL+C).
An extra line is added to the code section of the pasted Markdown when the copying action is the default one.

### What changes do you think we should make in order to solve the problem?


The `Copy to Clipboard` option uses `Clipboard.setString` to store a string/HTML in the clipboard.
We can overwrite the `copy` event of a component/components and call the same method (`Clipboard.setString`) which  would lead to a consistent output.
To implement this we would have to add an event listener and call the `Clipboard.setString` method.

### What alternative solutions did you explore? (Optional)

\-

**Comment by akamefi202** [comment] 2023-07-28 08:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An extra line is added to the code snippet when the user copy & paste the message using keyboard shortcut. 

### What is the root cause of that problem?
````
```
code snippet
```
abc
````
If we add a message that contains a code snippet(with linebreak at the end), a `<br />` tag is being appended at the end of `<pre>` tag.
```<pre>code&#32;snippet<br /></pre>abc```

Then if we copy & paste that message using keyboard shortcut, this `<br />` tag is being parsed too so an extra line will be added to the markdown text.
https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/hooks/useCopySelectionHelper.js#L8-L9

As a result, we see an extra line in the code snippet part.
````
```
code snippet

```
abc
````

### What changes do you think we should make in order to solve the problem?
We should not add that unnecessary `<br>` tag since the code snippet supports line break at the end as default.

To implement this, we should update the `expensify-common` repository.
https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js

We should update the rule of `codeFence` block for deleting the newline character of the end if it exists.
```
replacement: (match, __, textWithinFences) => {
    const group = textWithinFences.replace(/(?:(?![\n\r])\s)/g, '&#32;').replace(/\n$/g, '');
    return `<pre>${group}</pre>`;
},
```

So the unnecessary `<br>` tag won't be added and we also won't be able to see the extra line.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by puneetlath** [comment] 2023-07-28 21:16
@mollfpr please review when you get a chance, thanks!

**Comment by mollfpr** [comment] 2023-07-31 12:27
Reviewing

**Comment by akamefi202** [comment] 2023-08-03 14:19
@mollfpr 
>The selection listener is only called if we make a text selection in the App right? How do we handle the case where we make text selection outside of the App, for example from this OP issue?

Yes, the listener is only called if we copy the selection using keyboard shortcut(Ctrl + C) inside the app.
And if this listener is called, selection will be saved to clipboard in both html & text format.

>It seems you didn't have the <br> tag in the expression for the regex rules. In this case, can we correctly handle the parser on pasting the text?

https://github.com/Expensify/App/blob/34d1d9569c7d126315d3dee67609d78ce928c78e/src/components/Composer/index.js#L298-L301

It will be parsed using `htmlToMarkdown` function of `ExpensiMark` class when we paste the text.

**Comment by mollfpr** [comment] 2023-08-03 14:21
@akamefi202 Could you attach a working result video?

**Comment by akamefi202** [comment] 2023-08-03 14:39
@mollfpr 
[Screencast from 2023年08月03日 22时34分26秒.webm](https://github.com/Expensify/App/assets/53784473/abf29a55-f9a4-4627-b1e0-3e0696ff8239)

**Comment by mollfpr** [comment] 2023-08-03 16:41
Thanks @akamefi202 

>We should parse selection in advance, before saving it to clipboard & parsing it using htmlToMarkdown function.
We should remove the child <div> tag inside <pre> tag and the problem will be fixed.

Are the changes we need to parse the selection before set to the clipboard? You said that the break line tag is removed from `htmlToMarkdown`, then why does the issue still occur on copying the text from another source e.g. this issue OP?


https://github.com/Expensify/App/assets/25520267/e1d275dc-44de-4ecb-81ae-0d3cf51ed283

**Comment by akamefi202** [comment] 2023-08-03 17:14
@mollfpr 
I only thought about selection inside the app.
Should we fix this problem too? The subject of this issue is that markdown pasted from selection-copy is different from clipboard-copy.
Copying from Github can't avoid making a difference because of completely different html structure.

**Comment by akamefi202** [comment] 2023-08-03 19:51
@mollfpr 
I think we need to update `htmlToMarkdownRules` of `expensify-common` to fix above issue.
Currently, `htmlToMarkdownRules` contains rules only for parsing html selection from Expensify & Slack.
We need to add rules for parsing html selection from Github too.
https://github.com/Expensify/expensify-common/blob/1076899202ad338232a6cfeb4b242234aa932cb0/lib/ExpensiMark.js#L241-L247

I suggest to add below two rules.
First rule is for deleting unnecessary attributes of tags.
Second rule is for deleting unnecessary child tag inside `<pre>` tag.
```
{
  name: 'attribute',
  regex: /( *(style|dir|class)=(\"|\')([\s\S]*?)\3)/gi,
  replacement: ''
},
{
  name: 'nested',
  regex: /<pre><(div|code)>([\s\S]*?)<\/\1><\/pre>/gi,
  replacement: '<pre>$2</pre>'
},
```
Working result:
[Screencast from 2023年08月04日 03时45分15秒.webm](https://github.com/Expensify/App/assets/53784473/01cbf45d-6419-4af5-8f3f-dabbad26822e)

**Comment by mollfpr** [comment] 2023-08-04 15:11
>I only thought about selection inside the app.

We can fix it in both if it's the same root cause.

>First rule is for deleting unnecessary attributes of tags.

@akamefi202 Why do we need this? Because of this, there's a failure in the jest.

Although the solution is working. I want to know why `div` or `code` causes the newline to appear inside the block code.

**Comment by akamefi202** [comment] 2023-08-04 15:21
@mollfpr 
Thank you for your opinion. I agree with you. First rule isn't required. We can fix both issues by adding one rule.

>Although the solution is working. I want to know why div or code causes the newline to appear inside the block code.

https://github.com/Expensify/App/issues/23659#issuecomment-1655279506
I explained the reason in my proposal.
Currently, `handlePastedHTML` function adds head & tail line breaks in default. And it removes the new line character at the end of `<pre>` tag if it exists, for preventing addition of new line characters.
But through rendering of HTML content, `<div>` or `<code>` tag is appended inside `<pre>`. So `<br>` tag is also inside of `<div>` tag. As a result, the end new line character won't be removed and we will see an extra line in markdown text.
You can check the regex in below code and it will help understanding.

https://github.com/Expensify/expensify-common/blob/1076899202ad338232a6cfeb4b242234aa932cb0/lib/ExpensiMark.js#L321-L325

**Comment by akamefi202** [comment] 2023-08-04 15:29
@mollfpr 
For example, if we copy and paste message using clipboard button in context menu. `handlePastedHTML` function parses html code through below steps.
```
<pre>code<br></pre> -> <pre>code<pre> -> ```\ncode\n```
``` 
But if we copy and pasting using selection and keyboard shortcut.
```
<pre><div>code<br></div></pre> -> <pre><div>code<br></div></pre> -> ```\ncode\n\n```
```

**Comment by mollfpr** [comment] 2023-08-05 11:09
Thanks @akamefi202, that make sense to me.

I have tested the [proposal](https://github.com/Expensify/App/issues/23659#issuecomment-1655279506), and we only need to add 1 rule to remove the `<div>` or `<code>` tag to make the test work. Let's go with @akamefi202 [proposal](https://github.com/Expensify/App/issues/23659#issuecomment-1655279506) then.

🎀 👀 🎀 C+ reviewed!

**Comment by puneetlath** [comment] 2023-08-08 16:16
Sorry, just catching up. I think I like this solution better: 

>Second rule is for deleting unnecessary child tag inside <pre> tag.

That way we handle it on paste, rather than on copy. And that way no matter how many divs exist inside the pre tags, they'd get removed. What do y'all think?

**Comment by akamefi202** [comment] 2023-08-08 16:26
Yeah, I suggested it and @mollfpr agreed with that solution too.

**Comment by puneetlath** [comment] 2023-08-08 16:29
Ah ok. The link seemed to be to the earlier proposal, so I wasn't sure. Let's do it then!

**Comment by akamefi202** [comment] 2023-08-08 16:35
I applied to the [Upwork job](https://www.upwork.com/jobs/~019c94943755b5fa6d) and I believe that the PR will be ready by tomorrow.

**Comment by akamefi202** [comment] 2023-08-09 06:44
I updated [proposal](https://github.com/Expensify/App/issues/23659#issuecomment-1655279506).
I added the discussed solution as alternative solution.

**Comment by akamefi202** [comment] 2023-08-09 07:42
@mollfpr @puneetlath 
[PR](https://github.com/Expensify/expensify-common/pull/564) is ready.

**Comment by akamefi202** [comment] 2023-08-30 14:47
@puneetlath @mollfpr It's Aug 30th. Could you please help me with payment? And can we close this issue now?

**Closed** 2023-08-30 15:04 UTC
Labels: Reviewing, External, Weekly, Bug
