### ISSUE TITLE
Distance - Countries, which begin with entered letter are displayed next to suggested places

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33941] opened 2024-01-04 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33887

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Create a workspace and go to your workspace expense chat
4. Create a distance request and allow the browser to give your location
5. Type an `a` in the first waypoint and confirm that the locations offered are biased by your real location

## Expected Result:
The locations offered are biased by your real location

## Actual Result:
When the location is turned on, along with the locations offered depending on your real location, countries whose names begin with the entered letter are displayed next

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a68ebf6e-3f09-466c-afae-2f0a822aa07c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment] 2024-01-04 12:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The location bias of Google Places search is not strictly limiting the results to fit into the predefined location bias: https://stackoverflow.com/a/59850360

It seems like the countries have a high rank in Google places search results, therefore they are returned in the search results even though they are not within the provided boundaries.

### What changes do you think we should make in order to solve the problem?
I would suggest not showing countries in the search results at all, since the distance requests are expensable by mileage, and "trip from Poland to the USA" is a very unclear distance.

For this, we can filter out the search results with `type: country` here:

https://github.com/Expensify/App/blob/a2fc252eb6fd13700acf417bf005217dbb051db4/src/components/AddressSearch/index.js#L442-L451

<img width="303" alt="image" src="https://github.com/Expensify/App/assets/12595293/c51f838d-c272-4a60-bf7a-281fc8f0a7aa">


### What alternative solutions did you explore? (Optional)

**Comment by youssef-lr** [comment] 2024-01-04 18:06
cc @aldo-expensify could this be related to your [PR](https://github.com/Expensify/App/pull/33887? Regardless, what do you think about the proposal above removing countries from the suggestions all together?

**Comment by allroundexperts** [comment] 2024-01-04 18:10
cc @rojiphil Since you authored this feature and might have a better idea on how to fix!

**Comment by youssef-lr** [comment] 2024-01-04 18:12
Yeah I'm not sure about hiding countries to be honest, it sounds like we would be fixing a symptom instead of the actual problem. Because this isn't happening in production according to @kbecciv.

**Comment by allroundexperts** [comment] 2024-01-04 18:14
The feature as a whole is not yet on staging. [This](https://github.com/Expensify/App/pull/33334) was the original PR.

**Comment by paultsimura** [comment] 2024-01-04 18:15
> Because this isn't happening in production

It is actually, but in Prod the results are currently not location-biased at all, so it isn't noticeable that much (e.g. India, Israel, UK here):

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/12595293/dd80e838-cbe4-4464-ae31-e6ebda6bde0b">
<img width="375" alt="image" src="https://github.com/Expensify/App/assets/12595293/248c8c38-cdcf-416f-b1bb-489cf0d12205">

**Comment by aldo-expensify** [comment] 2024-01-04 18:17
Good point @paultsimura , I think we should remove this as a deploy blocker then

**Comment by marcaaron** [comment] 2024-01-04 18:18
Can a distance request be created from one country to another? Sounds weird, but if it works then maybe someone wants to do it.

I feel like the countries (if left in) should be prioritized last in the list after any more specific possible locations.

Also agree this doesn't need to be a blocker.

**Comment by paultsimura** [comment] 2024-01-04 18:23
Just to give a little more info about why the countries appear in the list even though they are outside of the boundaries: https://developers.google.com/maps/documentation/javascript/reference/places-service#LocationBias

> A LocationBias represents a **soft boundary or hint** to use when searching for Places. Results **may come from outside the specified area**...

**Comment by aldo-expensify** [comment] 2024-01-04 18:31
> Can a distance request be created from one country to another? Sounds weird, but if it works then maybe someone wants to do it.

It makes sense to me, you could drive across small countries in Europe for example :). What I think doesn't make sense is that the suggestion shows a Country (not an address in a country). It doesn't make sense to me to calculate distances between "countries" without specific addresses.

**Comment by trjExpensify** [comment] 2024-01-05 00:13
yeah, agree with Aldo there. @thienlnam what was the intention from the OG issue here?

**Comment by thienlnam** [comment] 2024-01-05 02:33
Here's the OG [issue](https://github.com/Expensify/App/issues/32068) for this feature. If we chose a starting location, we wanted the destination or stop autocomplete to be around where the starting location was as opposed to showing places that were in different states entirely.

Agree with others that this isn't a blocker - but I do think we should remove countries from the results. I can't really think of a situation where you would do that - especially since we're calculating mileage from one address to another

**Comment by trjExpensify** [comment] 2024-01-05 12:15
Yeah, I think you should be allowed to put in addresses across countries, but claiming mileage for "UK" to "France" is not a legit case, so we should remove countries in the results.

**Comment by trjExpensify** [comment] 2024-01-05 12:17
@rojiphil @parasharrajat @thienlnam will you guys take this over as a clean-up [from this](https://github.com/Expensify/App/pull/33334)?

**Comment by rojiphil** [comment] 2024-01-05 13:14
@parasharrajat  @thienlnam 

I am not sure of the cleanup that needs to be done as part of the [PR here](https://github.com/Expensify/App/pull/33334) 

As I understand, we are using Google Place Autocomplete service ([ref](https://developers.google.com/maps/documentation/places/web-service/autocomplete))to arrive at our place predictions. Based on the `input` provided, the Autocomplete service would return 5 place predictions after ordering results based on perceived relevance. Before adding `locationbias`, we would get results from faraway places even though there were relevant results near the waypoints. Now, after adding `locationbias`, we get results from nearby locations if relevant predictions are available nearby. This is what we have done in the PR.

However, I think the issue here is independent of the recently implemented `locationbias` feature as we have not altered the logic of the type of results returned. The existing code uses `address` type as mentioned [here](https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/components/AddressSearch/index.js#L143) and [here](https://developers.google.com/maps/documentation/places/web-service/supported_types#table3) which seems to be root cause of this issue. The `address` type does not seem to prevent results of type `country`. Also, there could be other unwanted types like `continent` that can come in. 
Maybe, the owners of `react-native-google-places-autocomplete` library have an answer for this.

What are your thoughts?

**Comment by paultsimura** [comment] 2024-01-05 13:28
I agree that it's not related to the location bias feature and wasn't introduced by it.

> The existing code uses `address`

We explicitly pass no `resultTypes` to not limit the search results here, and using pre-defined `resultTypes` is mentioned in my proposal as an alternative solution: https://github.com/Expensify/App/issues/33941#issuecomment-1877017790:
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/iou/request/step/IOURequestStepWaypoint.js#L256

**Comment by rojiphil** [comment] 2024-01-05 13:32
That's the solution then. Passing `address` will solve the problem then.

**Comment by paultsimura** [comment] 2024-01-05 13:37
> Passing `address` will solve the problem then.

Unfortunately no: it will return only locations with precise addresses: no businesses, no landmarks. And that's most likely undesirable.

<details><summary>Without type:address</summary>
<p>

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/12595293/2eb8fc5a-4a18-46e5-b749-5451486010b7">

</p>
</details> 

<details><summary>With type:address</summary>
<p>

<img width="374" alt="image" src="https://github.com/Expensify/App/assets/12595293/8f67ea8d-258e-4073-a06d-279c10ef8ba4">

</p>
</details>

**Comment by rojiphil** [comment] 2024-01-05 13:44
> That's why I suggest manually filtering out unwanted types post-search.

Manually filtering seems to be a workaround as we will have to identify all undesirable types. Also, the side-effect is that we will see less than 5 results sometimes. And worse, none if all turn out to be of the same kind.

**Comment by rojiphil** [comment] 2024-01-05 14:14
> Unfortunately no: it will return only locations with precise addresses: no businesses, no landmarks. And that's most likely undesirable.

That's a good point. Maybe, that's why `types` is left empty. 
We have finer controls with the [new Places API](https://developers.google.com/maps/documentation/places/web-service/overview). But, unfortunately, the library we use depends on  Google Place Autocomplete service. 
The other alternative is for the library to support the new Places API to take advantage of the recent advancements.

**Comment by trjExpensify** [comment] 2024-01-15 23:27
Okay, so if I'm understanding this correctly:

Filtering out countries in isolation is a limitation of the version of the Google Places API we use (coming from upstream library), and doing so would cause us to miss out on including things like businesses and landmarks that we don't want. Is that correct?

**Comment by rojiphil** [comment] 2024-01-16 15:41
> Filtering out countries in isolation is a limitation of the version of the Google Places API we use (coming from upstream library), and doing so would cause us to miss out on including things like businesses and landmarks that we don't want. Is that correct?

That's correct

**Comment by trjExpensify** [comment] 2024-01-17 16:08
Cool, so I would lean on the side of closing this out and revisiting it when the library upstream supports the new Places API. CC: @youssef-lr @marcaaron @aldo-expensify @thienlnam for thoughts!

**Comment by aldo-expensify** [comment] 2024-01-17 16:19
That plan sounds good to me, I don't think this is high priority and we can wait.

**Comment by thienlnam** [comment] 2024-01-18 04:10
I agree we might have some false-positives trying to post process the countries out of the results manually. I don't mind putting this on hold but it may be disruptive for the users that actually try to use this feature (Not sure how often the countries show up when searching for a place but in the video it seems like it is almost every search)

**Comment by trjExpensify** [comment] 2024-01-18 13:38
>I don't mind putting this on hold but it may be disruptive for the users that actually try to use this feature 

I'm sure we'll get that feedback if its the case. 

Sidebar: I think location bias might have had some unwanted side effects, but we can move [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1705578708739609) (internal ref) on that one as a next step!

**Closed by trjExpensify** 2024-01-18 13:38 UTC
Labels: Engineering, Weekly, NewFeature
