### ISSUE TITLE
Bank account: Infinite loading when adding existing bank account again

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13985] opened 2023-01-04 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account, go to Workspace => Connect Bank Account => Choose Plaid.
2. Add a bank account with plaid that you already added it, now it's showing the error, reload the page.
3. Notice that it shows the infinite loading, close the page, go to the workspace => connect bank account again.
4. Notice that it shows the infinite loading.

_Full Reproduction Steps_
1. Go to account settings -> payments -> Add Payment method. Click the bank account option
2. Log into plaid, and select the bank account number you'll be going with. In this case, I added the one ending in x1111
3. After adding it successfully, go to workspace. Create a new workspace if you need to
4. Now "Connect Bank Account" within workspace settings
5. Log into plaid. Select **Chase** so you can select which accounts to transfer over. _Only select the x1111_ account.
    <img width="808" alt="image" src="https://user-images.githubusercontent.com/12980144/212170270-6916bb76-b1b2-427d-b750-d2186c7aecfb.png">

## Expected Result:  
There's no infinite loading

## Actual Result: 
There's infinite loading

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.48-2
**Reproducible in staging?:**  y 
**Reproducible in production?:** could not check
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210599168-e7fd0894-463c-429e-8227-9e12b4dbb044.mov

https://user-images.githubusercontent.com/43996225/210599131-93969c7a-c86b-4728-8e5a-c50deb1a5822.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672765951849519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a17a6139da65315e</li>
        <li>Upwork Job ID: 1615466553898729472</li>
        <li>Last Price Increase: 2023-01-17</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-01-06 00:10
I haven't been able to test but will review it tomorrow.

**Comment by alexpensify** [comment] 2023-01-07 00:36
@marcochavezf - I'm adding engineering to review if this is something we should block if the account was already added instead of letting the user start the flow again. Thanks!

**Comment by alexpensify** [comment] 2023-01-09 20:18
Not overdue, the label was added over the weekend.

**Comment by alexpensify** [comment] 2023-01-12 01:32
@marcochavezf have you had a chance to test at this one?

**Comment by ctkochan22** [comment] 2023-01-12 19:15
@kavimuru To clarify repro steps, did you add the bank account as a payment method first? Than tried to add that bank account to a workspace?

**Comment by ctkochan22** [comment] 2023-01-12 19:52
I can take this @marcochavezf if you don't mind 🙇 . Other wise feel free to take it back :)

**Comment by ctkochan22** [comment] 2023-01-12 19:55
So I was able to reproduce by adding the bank account as a payment method first, which should be stated in the reproduction steps to make things super clear. Going to update the description

**Comment by alexpensify** [comment] 2023-01-13 00:24
Thanks, @ctkochan22 for the update-- should apply the Internal label?

**Comment by ctkochan22** [comment] 2023-01-13 01:04
So the logic is falling through here: https://github.com/Expensify/App/blob/34fc98f34668de447a490639f5bdc0429a0e1380/src/components/AddPlaidBankAccount.js#L122-L132

We show the loader if the token is missing OR plaid is loading. If not we then check if there is an error message. If there is an error message, we display it. Lastly if there is a token present, we show the Plaid data (selector or the redirect link).

These are in separate "if" statements, which does not make it mutually exclusive. So when we reload the page after no bank accounts have been found, we enter that block. 

Token is gone upon refresh. Bank accounts are missing. So we default to spinner.

**Solution**
I think we should only show the spinner if 
- We are loading something still
- Token is empty **and** there is no error message present

**Comment by ctkochan22** [comment] 2023-01-13 01:20
@nkuoch Let me know if you see any issue with this

**Comment by ctkochan22** [comment] 2023-01-17 21:50
Oh this was fixed https://github.com/Expensify/App/issues/13985

I'm not sure its not showing up here.

**Comment by alexpensify** [comment] 2023-01-17 22:09
I'm going to reopen to identify if I need to proceed forward with the payment next steps.

**Comment by alexpensify** [comment] 2023-01-17 22:38
@hungvu193 - I sent an invite in Upwork. Please accept since you found this bug and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2023-01-18 01:03
Here is what I see in Upwork, can you double-check if I found the right person: 

![image](https://user-images.githubusercontent.com/8107070/213055264-40631671-04cb-4645-b23c-b2d8d680f096.png)

Thanks!

**Comment by hungvu193** [comment] 2023-01-18 01:16
@alexpensify yeah that's me, not sure why it didn't appear on my upwork, can you please rehire?

**Comment by hungvu193** [comment] 2023-01-18 01:43
Nevermind,I accepted the invitation:D

**Comment by alexpensify** [comment] 2023-01-18 01:44
All good, I sent an offer now via Upwork.

**Comment by alexpensify** [comment] 2023-01-18 01:48
Closing - the process has been completed in Upwork!

**Comment by alexpensify** [comment] 2023-01-18 18:17
@aimane-chnaif thanks for flagging. I'll work on the process today.

**Comment by alexpensify** [comment] 2023-01-18 23:33
I've run out of time today and will work on the payment in Upwork tomorrow for C+. Sorry, I missed this part in my previous process.

**Comment by alexpensify** [comment] 2023-01-19 18:54
@aimane-chnaif - thanks again for catching this honest mistake on my end. I have started the process in Upwork. Please reply once you confirm this GH can be closed. Here is the upwork job: 

https://www.upwork.com/jobs/~01754b83bcbf760b7b

**Comment by alexpensify** [comment] 2023-01-19 18:55
Cool, I'm closing this GH.

**Comment by alexpensify** [comment] 2023-01-20 15:48
Ok, let me review what's going on in Upwork.

**Comment by alexpensify** [comment] 2023-01-20 16:20
Alright, the payment should be on the way now. @aimane-chnaif can you please confirm? Once I get confirmation, I'll close this GH. Thanks!

**Comment by alexpensify** [comment] 2023-01-20 16:44
Perfect! Thanks for the update.

**Closed by alexpensify** 2023-01-20 16:44 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Internal, Bug
