### ISSUE TITLE
[$500] Distance - Duplicate waypoint error message is not dimissed after closing distance editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34999] opened 2024-01-23 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: App location access is disabled
1. Go to workspace chat
2. Create a distance request with A-B-A address
3. Navigate to request details page
4. Click Distance
5. Drag the waypoint so that it becomes A-A-B
6. Save the request
7. Exit the distance editor
8. Refresh the page
9. Click Distance

## Expected Result:
The duplicate waypoint error message is dismissed

## Actual Result:
The duplicate waypoint error message is not dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a4a61099-4a61-4d9c-8595-cdbf9b10f81b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018929236a56deb238</li>
        <li>Upwork Job ID: 1749887372530053120</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28142961</li>
<li>tienifr | Contributor | 28142962</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-01-23 20:11
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by paultsimura** [comment] 2024-01-23 20:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Duplicate waypoint" error remains between the "edit distance" page refreshes.

### What is the root cause of that problem?
For the distance request, we restore the transaction to original one only if it was not saved:

https://github.com/Expensify/App/blob/872eb17903f18f9a99d69abe6e45d6e736c70c77/src/components/DistanceRequest/index.js#L117-L126

However, in this case we save the transaction, but it's not persisted due to the route request.

### What changes do you think we should make in order to solve the problem?
We should add an extra check for the transaction to not have the route error:

```js
        return () => {
            // If the user cancels out of the modal without saving changes, then the original transaction
            // needs to be restored from the backup so that all changes are removed.
            if (transactionWasSaved.current && !hasRouteError) {
                return;
            }
            TransactionEdit.restoreOriginalTransactionFromBackup(transaction.transactionID);
        };
```



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-23 20:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Duplicate waypoint" error remains between the "edit distance" page refreshes.

### What is the root cause of that problem?
For the distance request, we use a hook that restores the transaction to the original one if it was not saved:

https://github.com/Expensify/App/blob/872eb17903f18f9a99d69abe6e45d6e736c70c77/src/components/DistanceRequest/index.js#L117-L126

However, in this issue's scenario, we save the transaction (`transactionWasSaved.current` becomes `true`), but the changes are not persisted due to the route error. However, we still return early because the condition of `transactionWasSaved.current` is met, and therefore do not fully restore the transaction to its original state.

### What changes do you think we should make in order to solve the problem?
We should add an extra check – early return only if the transaction was saved without a route error:

```js
        return () => {
            // If the user cancels out of the modal without saving changes, then the original transaction
            // needs to be restored from the backup so that all changes are removed.
            if (transactionWasSaved.current && !hasRouteError) {
                return;
            }
            TransactionEdit.restoreOriginalTransactionFromBackup(transaction.transactionID);
        };
```

### What alternative solutions did you explore? (Optional)

**Comment by JordanLevy19** [comment] 2024-01-23 21:49
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
The error message regarding non-unique waypoints in a distance request feature persists even after a user refreshes the page. This indicates that the error state is not being reset as expected during a page reload.

**What is the root cause of that problem?**
The root cause of the error message persisting after a page refresh is perhaps due to the hasError state in the DistanceRequest component not being reset correctly. The state is initially set to false, but the code only explicitly resets it in a specific useEffect cleanup function tied to the transaction and transactionID dependencies. If this cleanup function doesn't trigger correctly on a page refresh - either because the component isn't unmounting/remounting properly, or the dependencies don't change as expected - then the hasError state remains true, causing the error message to persist. Additionally, the submitWaypoints function sets this error state under certain conditions, but without a corresponding reset mechanism that activates on page refresh, the error state is not cleared.

**What changes do you think we should make in order to solve the problem?**

Ensure hasError Resets on Page Refresh:
Modify the useEffect for transaction and transactionID to explicitly reset hasError not only when the component unmounts but also when it remounts, which typically happens on a page refresh. This can involve adding a condition to check if waypoints or relevant conditions have been reinitialized and reset hasError accordingly.


Review and Update submitWaypoints Logic:
Implement a mechanism in submitWaypoints to reset hasError when the conditions that initially set it to true no longer apply. This could involve adding a state update at the start of this function to reset the error state, or incorporating additional checks to ensure the state aligns with the current conditions.


Improve Waypoints Update Logic:
In updateWaypoints, add logic to reassess the error state whenever waypoints are successfully updated. This ensures that if the error condition related to waypoints is resolved, hasError is reset to false.


What alternative solutions did you explore? (Optional)

**Comment by samilabud** [comment] 2024-01-23 22:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - waypoint error message is not dimissed after closing distance editor

### What is the root cause of that problem?
We are using Onyx to store and persist errors inside the transaction object:

https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/types/onyx/Transaction.ts#L60

Because of this when we got an error we going to keep it at least we save the waypoints again.

### What changes do you think we should make in order to solve the problem?
We should clean the transaction errors when unmount the Distance request component inside the next line:
https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/components/DistanceRequest/index.js#L117

The code result should be:
```
.
.
.
  return () => {
            // If there are error cached in onyx
            if (hasRouteError) {
                TransactionEdit.cleanTransactionErrors(transaction);
            }
.
.
.
```
And the cleanTransactionErrors could be (inside of https://github.com/Expensify/App/blob/main/src/libs/actions/TransactionEdit.ts):
```
function cleanTransactionErrors(transaction: OnyxEntry<Transaction>) {
    if (!transaction) {
        return;
    }
    const newTransaction = {
        ...transaction,
        errorFields: {
            route: {},
        },
    };
    Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${transaction.transactionID}`, newTransaction);
}
```

Result:

https://github.com/Expensify/App/assets/5216036/1e2d9256-08ad-4e1b-88bf-ed6f0f1a50bb

**Comment by alitoshmatov** [comment] 2024-01-30 05:57
Missed this one, reviewing today

**Comment by alitoshmatov** [comment] 2024-01-30 18:02
@paultsimura Thank you for your proposal. Even if transaction is restored when closing the page, error is still persisting.

**Comment by alitoshmatov** [comment] 2024-01-30 18:05
@JordanLevy19 Don't get me wrong but your proposal looks like written by a chatbot, it very vague and has no context awareness

**Comment by JordanLevy19** [comment] 2024-01-30 18:13
Hey @alitoshmatov - not wrong at all - this was actually my first go at one of these bugs, and I have definitely learned to be more specific about the issues and to and identify as much as possible where the actual bugs reside in the code files and components!

Thank you for the feedback!

**Comment by alitoshmatov** [comment] 2024-01-30 18:19
@Krishna2323 Thank you for your proposal, you are suggesting how to prevent duplicate waypoints from being submitted. I think your solution is not complete because there is no error handling there. You are just preventing user from submitting duplicate waypoints

**Comment by alitoshmatov** [comment] 2024-01-30 18:25
@samilabud Thank you for your proposal. Your RCA is correct and your solution does solve this issue. But I am not sure if it is expected behavior to clean all transaction errors when distance page is closed

**Comment by alitoshmatov** [comment] 2024-01-30 18:27
@tienifr Thank you for your proposal. Your RCA is correct. I do agree we should validate waypoints and show duplicate error before user submits the edit just like creating distance request.

**Comment by kmbcook** [comment] 2024-02-01 15:26
In https://github.com/Expensify/App/issues/34441 we have proposed to use a draft transaction for editing waypoints, which would solve this issue.

**Comment by alitoshmatov** [comment] 2024-02-02 18:29
@kmbcook Can you elaborate how that issue will solve ours?

**Comment by kmbcook** [comment] 2024-02-02 19:15
@alitoshmatov sorry, I was wrong.

**Comment by alitoshmatov** [comment] 2024-02-05 15:39
We can go with @tienifr 's [proposal](https://github.com/Expensify/App/issues/34999#issuecomment-1907559618)

C+ reviewed 🎀 👀 🎀

**Comment by tgolen** [comment] 2024-02-05 16:15
LGTM 👍

**Comment by alitoshmatov** [comment] 2024-03-26 11:50
@JmillsExpensify Bump

**Comment by JmillsExpensify** [comment] 2024-03-29 16:11
If you need something urgent please please reach out to me in Slack in our open source community or directly 1:1. Sorry for the delay!

**Comment by JmillsExpensify** [comment] 2024-03-29 16:12
Payment summary:

 - Contributor: @tienifr $500 
 - Contributor+: @alitoshmatov $500

Also @alitoshmatov I don't believe I've seen a BZ checklist. Can you please complete one? Thank you.

**Comment by JmillsExpensify** [comment] 2024-03-29 16:15
All contributors have been paid out though please @alitoshmatov help with the BZ checklist before we can close this on out!

**Comment by JmillsExpensify** [comment] 2024-04-01 17:23
@alitoshmatov bump on the BZ checklist.

**Comment by alitoshmatov** [comment] 2024-04-01 19:17
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/29125
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/29125/files#r1546740052
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need


cc: @JmillsExpensify

**Closed** 2024-04-01 20:45 UTC
Labels: Reviewing, External, Weekly, Bug
