### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] Web/Safari - Attachment - Drag and drop popup does not show on Safari

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34349] opened 2024-01-11 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Drag and attachment to any chat
----
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click on "+" > Request money > Scan module
4. Drag and attachment to the scan module

## Expected Result:
User expects there to be a "Drag to upload" popup (Or "+" symbol for the first case) and in the second case a popup that says "Let it go - drag to up upload)

## Actual Result:
No popup is shown when dragging and dropping, there is a "+" symbol but this shows ups and then after a while for no reason disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9b614215-0a82-41ac-b96a-b5a92ec16311

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018eedacd3a9252d63</li>
        <li>Upwork Job ID: 1745435828436111360</li>
        <li>Last Price Increase: 2024-01-11</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 28102162</li>
<li>tienifr | Contributor | 28102165</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-11 13:28
regression from https://github.com/Expensify/App/pull/33864

**Comment by s77rt** [comment] 2024-01-11 15:16
@tienifr Can you please take a look at this

**Comment by amyevans** [comment] 2024-01-15 15:43
Thanks for jumping on it so quickly @tienifr and @s77rt!

PS I can't assign you until you comment here @tienifr.

**Comment by s77rt** [comment] 2024-01-22 01:05
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/33864
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No. We have a test already https://expensify.testrail.io/index.php?/cases/view/2730088

**Comment by s77rt** [comment] 2024-01-22 01:06
@amyevans Please close this, no payment to handle here since it's a regression.

**Closed** 2024-01-22 14:46 UTC
Labels: External, Weekly, Awaiting Payment, Bug
