### ISSUE TITLE
[HOLD for payment 2024-07-25] Troubleshoot-"Mask fragile user data while exporting Onyx state" toggle is auto-enabled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#44841] opened 2024-07-04 15:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #43552
**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** no (This feature is not in production) Not sure it is Blocker
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Login to new Expensify app
2. Navigate to account settings > Troubleshoot
3. Scroll to the "Mask fragile user data while exporting Onyx state" menu and disable the toggle
4. Navigate away from the account settings page
5. Navigate back to settings > Troubleshoot
6. Observe the "Mask fragile user data while exporting Onyx state" toggle

## Expected Result:
"Mask fragile user data while exporting Onyx state" toggle remains disabled

## Actual Result:
"Mask fragile user data while exporting Onyx state" toggle is auto-enabled after being manually disabled

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/24bc21b3-c498-48bf-986f-7c5301c11bf6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by kavimuru** [comment] 2024-07-04 15:07
@blimpich FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by etCoderDysto** [comment] 2024-07-04 15:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Toggled "Mask fragile user data while exporting Onyx state" doesn't persist 
### What is the root cause of that problem?
We are saving the toggle state in `useState` rather than storing the state in Onyx
https://github.com/Expensify/App/blob/6ac95e4c7fdf555b7ba8c9365fb522305d239dc2/src/pages/settings/Troubleshoot/TroubleshootPage.tsx#L55
### What changes do you think we should make in order to solve the problem?
1. Add ONYX key and its type in ONYXKYES.ts
`SHOULD_MASK_ONYX_STATE: 'shouldMaskOnyxState'`
2. Initialize the added onyx key with `true` in `Onyx.init()`
3. Fetch the onyx value in `TroubleShootPage`
4. Pass the fetched data to `isOn` in `Switch` component of `TroubleShootPage`
5. Create action that will update the onyx state when Switch is toggled 
6. Pass the action to `onToggle` in `Switch` component of `TroubleShootPage`
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-07-04 15:20
[Updated my proposal](https://github.com/Expensify/App/issues/44841#issuecomment-2209209223) with minor details

**Comment by blimpich** [comment] 2024-07-04 16:37
I don't consider this a deploy blocker. Its minor and it relates to a feature that we really only use for debugging purposes, not user functionality. Demoting.

**Comment by blimpich** [comment] 2024-07-04 16:43
I don't think we should mark this as external since this relates to https://github.com/Expensify/App/issues/44841. It should just be follow up work for that PR.

**Comment by blimpich** [comment] 2024-07-08 21:09
Assigned to @ZhenjaHorbach and @hayata-suenaga as this is follow up for https://github.com/Expensify/App/issues/43097

**Comment by etCoderDysto** [comment] 2024-07-09 07:21
> @etCoderDysto 
> Thanks for the proposal !
> 
> If we don't mind contributors fixing this issue 
> Then this [proposal](https://github.com/Expensify/App/issues/44841#issuecomment-2209209223) makes sense
> And I'm happy to go with it
> 
> 🎀👀🎀 C+ reviewed
> 

Great! I will raise a PR ASAP.

**Comment by etCoderDysto** [comment] 2024-07-09 07:32
> > > @etCoderDysto
> > > Thanks for the proposal !
> > > If we don't mind contributors fixing this issue
> > > Then this [proposal](https://github.com/Expensify/App/issues/44841#issuecomment-2209209223) makes sense
> > > And I'm happy to go with it
> > > 🎀👀🎀 C+ reviewed
> > 
> > Great! I will raise a PR ASAP.
> 
> @etCoderDysto 
> Not needed yet 😅
> Until we wait for @hayata-suenaga approval
> 

Alright 😁! I will wait 😁

**Comment by etCoderDysto** [comment] 2024-07-09 07:43
Alright 😁! I will wait 😁

**Comment by dylanexpensify** [comment] 2024-07-10 08:08
Waiting for Hayata to confirm!

**Comment by hayata-suenaga** [comment] 2024-07-11 13:00
sorry for the delay! 🙇

**Comment by etCoderDysto** [comment] 2024-07-15 11:58
PR is almost ready 😁. It will ready for review today.

**Comment by dylanexpensify** [comment] 2024-07-15 11:59
Nice! Lets get it!

**Comment by etCoderDysto** [comment] 2024-07-15 13:20
[PR](https://github.com/Expensify/App/pull/45401) us ready for review.

**Comment by dylanexpensify** [comment] 2024-07-16 17:43
Nice!

**Comment by dylanexpensify** [comment] 2024-07-22 12:39
Payment coming up!

**Comment by dylanexpensify** [comment] 2024-07-25 11:02
@Christinadobrzyn I'm heading ooo now until the 5th of August! TY for finishing this off! 🙇‍♂️

**Comment by etCoderDysto** [comment] 2024-07-25 17:38
Here is my Upwork profile: https://www.upwork.com/freelancers/~01ea78e0164390eb79
Thank you!

**Comment by Christinadobrzyn** [comment] 2024-07-25 17:44
Thanks @etCoderDysto! Please accept the offer [here](https://github.com/Expensify/App/issues/44841#issuecomment-2251047639)

**Comment by etCoderDysto** [comment] 2024-07-25 17:46
I have accepted the offer. Thank you!

**Comment by Christinadobrzyn** [comment] 2024-07-25 19:53
Oh! Thanks for bringing that up @ZhenjaHorbach - let me check with the team.

**Comment by muttmuure** [comment] 2024-07-29 12:24
@ZhenjaHorbach is being paid here: https://github.com/Expensify/App/issues/43097

**Comment by etCoderDysto** [comment] 2024-07-29 12:39
To make things clear, I am not getting paid twice for the offending PR the and fixing PR😁. I was not the author of the offending PR. I only worked on the fixing PR.

**Comment by Christinadobrzyn** [comment] 2024-07-29 15:53
Awesome! I think this can be closed as @etCoderDysto was paid in this issue and @ZhenjaHorbach will be paid in [this issue ](https://github.com/Expensify/App/issues/43097)

**Closed** 2024-07-29 15:53 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
