### ISSUE TITLE
mweb - Room - Room description is shown briefly and disappeared

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43757] opened 2024-06-14 11:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4627773
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab -- start chat -- room
3. Enter all details including room room description
4. Tap create room

## Expected Result:
Room description must be shown and not disappear

## Actual Result:
Room description is shown briefly and disappeared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/80b9af14-b9ef-4000-a5a0-015d6374afa8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-14 11:05
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-14 11:05
We think that this bug might be related to #vip-vsp

**Comment by truph01** [comment] 2024-06-14 23:22
I think it is related to https://github.com/Expensify/App/issues/43788

**Comment by alexpensify** [comment] 2024-06-17 22:29
Thanks for flagging @truph01! That GH is on hold for https://github.com/Expensify/App/issues/37560. I'm going to close since help is on the way.

**Comment by izarutskaya** [comment] 2024-06-28 09:14
Issue is still reproducible 
Build v9.0.3-1

https://github.com/Expensify/App/assets/115492554/af2671ee-de75-4bbc-ad81-29a08f33ad8a

**Comment by alexpensify** [comment] 2024-06-28 22:24
Closing this one because we closed the other GH related to it: https://github.com/Expensify/App/issues/37560#issuecomment-2187036040

**Comment by alexpensify** [comment] 2024-06-28 22:24
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Closed by alexpensify** 2024-06-28 22:24 UTC
Labels: Daily, Bug
