### ISSUE TITLE
[HOLD for payment 2024-12-12] Android & iOS - App crashes after completing onboarding

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53431] opened 2024-12-03 06:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** stefanslvatorea+sjdos2323od@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Create a new account on web but do not complete onboarding.

1. Launch ND or hybrid app.
2. On onboarding purpose, choose Manage my team's expenses.
3. Select organization size.
4. Select an accounting.
5. Complete the onboarding.

## Expected Result:
App will not crash after completing onboarding.

## Actual Result:
App crashes repeatedly after completing onboarding.
Issue happens on Samsung Galaxy Z Fold4 - Android 14
## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
  
[0312.txt](https://github.com/user-attachments/files/17988542/0312.txt)

https://github.com/user-attachments/assets/4b252b07-3611-4f8e-a3fd-98c8b8457400

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by techievivek** [comment] 2024-12-03 12:17
But yes this looks related to https://github.com/Expensify/App/pull/52314

**Comment by techievivek** [comment] 2024-12-03 12:22
https://github.com/user-attachments/assets/fd1eea59-e3a5-44a3-8d78-431bce658ea7

**Comment by techievivek** [comment] 2024-12-03 12:24
@IuliiaHerets Can you please re-test this once again, I was unable to reproduce this on my end.

**Comment by perunt** [comment] 2024-12-03 12:54
Hi everyone! I'm from the Margelo team and happy to help with this

**Comment by mohammedmatar** [comment] 2024-12-03 13:40
Hello @perunt ! I'm not an official contributor to Expensify, but I've been exploring the issues in the project as part of my learning process. I noticed this issue and wanted to share a potential solution I've come across.

I've implemented a change to address the error by adding the 'worklet' directive to the `getTooltipAnimatedStyles` function. Here's a summary of the change and its implications:

1. Added the 'worklet' directive:
   The 'worklet' directive was added to the `getTooltipAnimatedStyles` function. This directive indicates that the function should be compiled as a worklet for use with React Native Reanimated.

   ```typescript
   getTooltipAnimatedStyles: (props: TooltipAnimationProps) => {
       'worklet';
       // ... rest of the function
2. Purpose of the change:
This directive indicates that the function should be compiled as a worklet for use with React Native Reanimated, allowing it to run on the UI thread for smooth animations.
3. Resolving the error:
This change should address the error that was occurring due to the function not being properly marked as a worklet.
4. Considerations:
This solution assumes the use of Reanimated 2 or later.
It may improve performance for animations and gestures.
Any values or functions used within this worklet should be compatible with the Reanimated worklet system.

**Comment by perunt** [comment] 2024-12-03 13:49
@mohammedmatar I'm aware of it, but thank you for your findings :)
I'm trying to understand why WEB works with shared value in useAnimatedStyle without the worklets marker.

**Comment by puneetlath** [comment] 2024-12-03 22:13
This seems to be fixed after CP. Though we have a problem with the onboarding modal not always showing up.

**Comment by Christinadobrzyn** [comment] 2024-12-09 23:47
Payment coming up in a few days 

@perunt should we have a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-12-13 15:55
Sounds good melvin 

@perunt should we have a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-12-16 15:56
@techievivek Do you think we need a regression test for this? Or can we just close?

**Comment by techievivek** [comment] 2024-12-16 16:38
We don't need to add any additional regression test for this since the app was crashing during loading of LHN itself.

**Comment by Christinadobrzyn** [comment] 2024-12-16 23:34
Awesome! Thank you @techievivek! 

Closing this out as complete since no payment in ND or Upwork is due.

**Closed by Christinadobrzyn** 2024-12-16 23:34 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
