### ISSUE TITLE
[$250] Accounting – When navigate back from NetSuite page workspace profile page opens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46230] opened 2024-07-25 20:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with expensifail account
2. Create Workspace> Enable Accounting
3. Go to Accounting
4. Click on connect NetSuite
5. Verify Upgrade modal appears
6. Click Back

## Expected Result:
User should land on Accounting page

## Actual Result:
User lands on Workspace profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/66930efc-6349-48d9-b4f0-d02634945a58

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01564450f18c93f647</li>
        <li>Upwork Job ID: 1818424433339662150</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 103358804</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment] 2024-07-25 20:15
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-25 20:15
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment] 2024-07-25 20:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting – When navigate back from NetSuite page workspace profile page opens
### What is the root cause of that problem?
We are navigating to profile page if `backTo` is undefined
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L47-L48
### What changes do you think we should make in order to solve the problem?

Change it to 
```
                onBackButtonPress={() => Navigation.goBack(route.params.backTo)}

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-25 20:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting – When navigate back from NetSuite page workspace profile page opens
### What is the root cause of that problem?
We are navigating to profile page if `backTo` is undefined
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L47-L48
### What changes do you think we should make in order to solve the problem?

Change it to 
```
                onBackButtonPress={() => Navigation.goBack(route.params.backTo)}

```
or alternatively omit the line 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L47-L48
to use default `goBack` behaviour `HeaderWithBackButton`

or alternatively use `dismissModal`
```
                    onBackButtonPress={Navigation.dismissModal}

```


### What alternative solutions did you explore? (Optional)

**Comment by neonbhai** [comment] 2024-07-25 20:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting – When navigate back from NetSuite page workspace profile page opens

### What is the root cause of that problem?
We don't define the backTo param here:
https://github.com/Expensify/App/blob/6cf54723b36094379e7a478633a6ed3f43cd9c43/src/components/ConnectToNetSuiteButton/index.tsx#L59

### What changes do you think we should make in order to solve the problem?
We will add the third param pointing to policyAccountingPage. We will get it from `Navigation.getActiveRouteWithoutParams()`

**Comment by FitseTLT** [comment] 2024-07-25 21:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting – When navigate back from NetSuite page workspace profile page opens
### What is the root cause of that problem?
We are not passing the `backTo` here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/ConnectToNetSuiteButton/index.tsx#L59-L60
so it will fallback to the workspace profile route here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L47-L48
### What changes do you think we should make in order to solve the problem?

We should pass the accounting route as the backTo here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/ConnectToNetSuiteButton/index.tsx#L59-L60
```
                        Navigation.navigate(ROUTES.WORKSPACE_UPGRADE.getRoute(policyID, CONST.UPGRADE_FEATURE_INTRO_MAPPING.netsuite.alias, ROUTES.WORKSPACE_ACCOUNTING.getRoute(policyID)));
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-25 21:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting – When navigate back from NetSuite page workspace profile page opens
### What is the root cause of that problem?
We are not passing the `backTo` here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/ConnectToNetSuiteButton/index.tsx#L59-L60
so it will fallback to the workspace profile route here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L47-L48
### What changes do you think we should make in order to solve the problem?

We should pass the accounting route as the backTo here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/ConnectToNetSuiteButton/index.tsx#L59-L60
```
                        Navigation.navigate(ROUTES.WORKSPACE_UPGRADE.getRoute(policyID, CONST.UPGRADE_FEATURE_INTRO_MAPPING.netsuite.alias, ROUTES.WORKSPACE_ACCOUNTING.getRoute(policyID)));
```
if needed we can also remove workspace profile fallback route here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L47-L48

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2024-07-30 23:13
Hey @abdulrahuman5196 we've got a few proposals to review on this one!

**Comment by abdulrahuman5196** [comment] 2024-08-01 15:28
Checking now

**Comment by abdulrahuman5196** [comment] 2024-08-01 15:55
@neonbhai 's proposal here https://github.com/Expensify/App/issues/46230#issuecomment-2251348529 looks good and works well. Other proposals are similar.
The same issue is happening for `Sage Intacct` connect as well. Kindly fix the same in the PR as well.

🎀 👀 🎀
C+ Reviewed

**Comment by robertjchen** [comment] 2024-08-01 16:12
Let's do it 👍

**Comment by neonbhai** [comment] 2024-08-02 09:40
Thank you for assigning, raising PR soon!

**Comment by stephanieelliott** [comment] 2024-08-08 03:02
Hey @neonbhai looks like the PR review is held on a comment looking from clarification from you -- can you weigh in when you get a sec?

**Comment by neonbhai** [comment] 2024-08-09 07:19
hi, I've run in an issue, when testing the upgrade workspace flow that affects navigation:

#### Steps (Reproducible in prod):

1. Go to collect policy with categories enabled
2. Click on a category -> Click on GL Code
3. Refresh the Page
4. Click back button
5. Modal does not dismiss to chat, we land on workspace profile (bug)
6. Try going to the collect policy and view a category
7. Category Details opens with the workspace list page 
8. Click on a Workspace -> click Back
9. User is in a state to view chat without LHN 


https://github.com/user-attachments/assets/aed8af91-33ad-4ec5-9f8f-d03885e60a1c


We can fix this by making sure the upgrade page dismisses when not on a workspace. Here:

https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L45-L48

```jsx
onBackButtonPress={() => Navigation.goBack()}
```
This will make the upgrade page go back only if navigation state has previous items, and to dismiss if user has an empty navigation stack (site reloaded)

<Details><Summary>Result</Summary>

This works perfectly:

https://github.com/user-attachments/assets/468952e8-30f5-40e5-b36e-c4e8f0b2121a


</Details>

Should we fix this?

👍 - Agree, go ahead
👎 - Disagree

**Comment by stephanieelliott** [comment] 2024-08-14 00:57
Hey @robertjchen what do you think of the proposal above?

**Comment by robertjchen** [comment] 2024-08-15 06:23
I think we should fix this, please proceed 👍

**Comment by stephanieelliott** [comment] 2024-08-21 03:02
Hey @neonbhai checking in from this comment on the PR: 

> Looks like in https://github.com/Expensify/App/pull/45730 we decided to change navigation connected with upgrade flows, and now redirect to the Token Input pages. This means that the current approach is not needed.
> 
> The changes in https://github.com/Expensify/App/pull/45730 also incorporates the solution to related bug noted https://github.com/Expensify/App/issues/46230#issuecomment-2277308093, so it's not reproducible
> 
> The original issue and reported issue https://github.com/Expensify/App/issues/46230#issuecomment-2277308093 are not bugs anymore after the changes.
> 
> We should not move forward with current approach. I'll close the PR

With this being the case, are you saying we should close this issue? Also, does that mean that the fix described [here](https://github.com/Expensify/App/issues/46230#issuecomment-2277308093) is no longer necessary?

**Comment by stephanieelliott** [comment] 2024-08-28 01:26
Thanks @neonbhai! Makes sense, I agree we should issue payment for this and then close.

**Comment by stephanieelliott** [comment] 2024-08-28 01:30
Summarizing payment on this issue: 

 - Contributor: @neonbhai $250 via Upwork -- offer extended, please accept! https://www.upwork.com/nx/wm/offer/103711977
 - Contributor+: @abdulrahuman5196 $250 via Upwork -- offer extended, please accept! https://www.upwork.com/nx/wm/offer/103711982
 
 Upwork job is here: https://www.upwork.com/jobs/~01201199f64fde6026

**Comment by abdulrahuman5196** [comment] 2024-08-29 17:46
Hi @stephanieelliott I am getting paid via newDot. Will request in newDot.

**Comment by robertjchen** [comment] 2024-08-29 22:06
Thanks! 🙇

**Closed by robertjchen** 2024-08-29 22:06 UTC
Labels: Reviewing, External, Monthly, Bug

**Comment by JmillsExpensify** [comment] 2024-09-02 21:05
$250 approved for @abdulrahuman5196
