### ISSUE TITLE
[$1000] Chat - Copy email option is missing chat settings with new user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22192] opened 2023-07-04 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21779
## Action Performed:
1. Open app and login with User A
2. Click on new chat and enter an email of a User B (new user that doesn't have Expensify account)
3. Click on header of chat and copy the email of User B

## Expected Result:
Copy email option should be available

## Actual Result:
Copy email option is missing on Web in chat with new user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1b10c61f-56e3-4f4c-ab1f-9698f78a5242

**Expensify/Expensify Issue URL:**

**Issue reported by:** Yes

**Slack conversation:** Yes

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198cc663a4ea8fbfd</li>
        <li>Upwork Job ID: 1677354613124038656</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-04 22:57
This should be fixed in the backend. When open report with new email, the backend now returns accountID, avatar, and displayName. This should include login as well.
![image](https://github.com/Expensify/App/assets/126839717/996a2eb5-e513-4f51-9661-8108e09fa457)

**Comment by anmurali** [comment] 2023-07-07 16:32
Ideally we fix this by adding the `Email` to the profile even for new users? (We won't have the rest like pronouns etc.)
Looks like this:
<img width="354" alt="image" src="https://github.com/Expensify/App/assets/14225673/90e33acd-43b2-4ade-8f35-71279deb1cc7">

But we want it to look like this:
<img width="348" alt="image" src="https://github.com/Expensify/App/assets/14225673/472553fd-91ed-411c-a882-47186d9a4e50">

**Comment by uzproblue** [comment] 2023-07-07 16:49
Proposal: 
I can work on this

**Comment by f-d-r-720** [comment] 2023-07-07 17:47
Hello, has the problem been solved or are you still accepting proposals? Greetings!👍

**Comment by spacexdragonpie** [comment] 2023-07-10 09:04
This also happens when renaming an account after account exists.  See this issue for steps to create such an account: https://github.com/Expensify/App/issues/22293


![Screenshot from 2023-07-10 16-01-48](https://github.com/Expensify/App/assets/137755377/05a08ea6-d3f6-4670-a780-9af0232a9ed1)

**Comment by spacexdragonpie** [comment] 2023-07-10 09:07
Contributor details
Your Expensify account email: spacexdragonpie@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017a45afbd5badccec

**Comment by anmurali** [comment] 2023-07-10 12:07
Not overdue, reviewing proposals

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:35
There isn't any proposals actually.

@uzproblue  Kindly use this proposal template to provide analysis and solution

**Comment by uzproblue** [comment] 2023-07-13 17:57
## Proposal

I can work on this issue.
I will fix copy email feature and make the component look like the example provided above.

**Comment by ShogunFire** [comment] 2023-07-14 00:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we click on the header of a chat we can't copy the email when the user has no login

### What is the root cause of that problem?

In ProfilePage and DetailsPage we only display the line with  copy Email or copy Sms if the user has a login.
For example for ProfilePage the condition is here:
https://github.com/Expensify/App/blob/9c65620c724410693e71786d2df5980769ea2f8a/src/pages/ProfilePage.js#L181-L195


### What changes do you think we should make in order to solve the problem?

When the user has no login we can use the display name, I think the easiest way is to put displayName as a default value when we retrieve the login. So instead of this:
https://github.com/Expensify/App/blob/9c65620c724410693e71786d2df5980769ea2f8a/src/pages/ProfilePage.js#L113
We can do this:
`const login = lodashGet(details, 'login', displayName);`

We can do the same thing for DetailsPage

### What alternative solutions did you explore? (Optional)
I don't see what regressions that could cause but just in case if we are afraid of regressions we can also replace the null here: 
https://github.com/Expensify/App/blob/9c65620c724410693e71786d2df5980769ea2f8a/src/pages/ProfilePage.js#L195
by the same thing as above but with displayName, and maybe also test that displayName is a correct email or sms

**Comment by anmurali** [comment] 2023-07-17 17:38
@abdulrahuman5196 is _now_ reviewing proposals

**Comment by abdulrahuman5196** [comment] 2023-07-19 20:17
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-07-19 20:22
@ShogunFire for proposal here https://github.com/Expensify/App/issues/22192#issuecomment-1635084689
I don't think using displayName will be a right option, since displayname can be something with isn't email.

**Comment by abdulrahuman5196** [comment] 2023-07-19 20:25
I think this is due to the recent change of not sending `login` value as part of userdetails for privacy concerns. So I am not sure on the new expectation of this issue on the profile page. So tagging @luacmartins (Assuming he worked on this, if not kindly tag the person who be able to provide the expectation on this)

**Comment by luacmartins** [comment] 2023-07-19 21:01
Thanks for the ping. I didn't work directly on this feature. @Beamanator can you weight in here

**Comment by ShogunFire** [comment] 2023-07-19 23:05
There are times where it's impossible to get the email if I understand correctly. In that case I think we should focus on the times where we can get the email/phone number

What do you think of doing the last sentence of my alternative proposal:
> and maybe also test that displayName is a correct email or sms

**Comment by Beamanator** [comment] 2023-07-20 11:15
The email NOT showing up in this case was by design - if you don't "know" the user, you won't get their `login` in the returned personal details

cc @puneetlath as we both worked on this project

I believe we should :donothing: here

@lanitochka17 when you created this issue, you mentioned `Slack conversation: Yes` but you didn't link a slack convo

**Comment by anmurali** [comment] 2023-07-24 15:29
@Beamanator so do we just need to close this issue then? What are we waiting on?

**Comment by puneetlath** [comment] 2023-07-24 15:45
I agree this isn't a bug and can be closed.

**Closed by puneetlath** 2023-07-24 15:45 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by ShogunFire** [comment] 2023-07-24 15:50
I find it weird that userA doesn't know userB login when he has used this login to create the chat...
