### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Continue button is hidden behind keyboard on onboarding pages.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45037] opened 2024-07-09 02:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720471428343119

## Action Performed:

1. Create a new account.
2. Choose "manage my team expenses" purpose on the first onboarding page
3. Type Business name
4. Click continue
5. Type first name
6. Click continue

## Expected Result:
The continue button move to the top with the keyboard when opening it
## Actual Result:
The continue button is hidden behind the keyboard
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9ae6de2b-8b8b-424d-9ce9-6f2d4e00a4d0

https://github.com/Expensify/App/assets/38435837/1325fbcf-464c-40b2-b870-ac2c9689e3ef

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca1aa78c61096205</li>
        <li>Upwork Job ID: 1810702818116110090</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103050117</li>
<li>nkdengineer | Contributor | 103118552</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by m-natarajan** [comment] 2024-07-09 02:34
@lschurr Issue reporter commented to assign this to him as he have context. I am not sure I can assign him or not, Can you please confirm?

**Comment by nkdengineer** [comment] 2024-07-09 03:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The continue button is hidden behind the keyboard

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/OnboardingWork/BaseOnboardingWork.tsx#L81-L84

we don't pass enabled props

### What changes do you think we should make in order to solve the problem?
In these places

https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/OnboardingWork/BaseOnboardingWork.tsx#L81-L84

https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L139-L142

I suggest to use ScreenWrapper and remove KeyboardAvoidingView
```
<ScreenWrapper
            includeSafeAreaPaddingBottom={false}
            shouldEnableMaxHeight
            shouldEnableKeyboardAvoidingView
            testID="BaseOnboardingWork">
```
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2024-07-09 16:24
Assigned to you @m-natarajan - Could you review the proposal?

**Comment by lschurr** [comment] 2024-07-09 16:56
Oops! Sorry about that @rayane-djouah - good now.

**Comment by robertjchen** [comment] 2024-07-15 03:21
👍 to @nkdengineer 's proposal

**Comment by lschurr** [comment] 2024-08-01 19:22
This is not overdue. Payment date is tomorrow.

**Comment by lschurr** [comment] 2024-08-02 16:20
Payment summary:

- Contributor: $250 @nkdengineer (paid in Upwork)
- Reviewer: $250 @rayane-djouah (paid in Upwork)

**Closed by lschurr** 2024-08-02 16:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
