### ISSUE TITLE
[HOLD for payment 2023-10-09] [$250] Personal Details - When random url param for country passed the app crashes on Dev and shows allCountries.randomParam

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28743] opened 2023-10-03 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings -> personal Details -> Home Address ->
2. Select Country Selection, Choose a country
3. Change country param in URL to anything random

## Expected Result:
Selected country should not change or fallback to default a default country

## Actual Result:
Selected country changes to allCountries.randomParam

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/01c9b285-62dd-4af5-b529-e31172fd8024

https://github.com/Expensify/App/assets/93399543/3be1eec8-e268-443d-88b6-57a8992dcf26

https://github.com/Expensify/App/assets/93399543/7a47d203-7f38-434c-b4a8-e7423d7f39a3

https://github.com/Expensify/App/assets/93399543/9995c360-b5b1-4a09-a08f-8d23c129de89

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696284209392199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad40bd8b7e5b3460</li>
        <li>Upwork Job ID: 1709296238434172928</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-10-03 19:56
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
While changing the country code from URL in the address page, it shows unwanted string instead of country
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/6f3c7069b0b1eadce27e867b56311caab74e389e/src/components/CountrySelector.js#L38
The issue is here as we are only checking if the country code is present, we also have to check whether the provided country code is in country list.
### What changes do you think we should make in order to solve the problem?
we also have to check whether the provided country code is in country list in constants from this
https://github.com/Expensify/App/blob/d913865d85ec90679bd3c7b01cd85f4375229acb/src/CONST.ts#L1465-L1469
The result would look something like this
```javascript
  const title = isCountryCodeExist && countryCode ? translate(`allCountries.${countryCode}`) : '';
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by kbecciv** [comment] 2023-10-03 19:57
Proposal  by: @ishpaul777
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1696284209392199


### Proposal

### Problem
When there is a invalid url param for country is passed, the selected country is shown as "allCountries.randommparampassed" and in dev environment, app crashes.

### Root cause
The root cause is that the country param is not validated before setting the current country in the AddressPage, and invalid country param is passed to the `CountrySelector`, as the param is invalid, the country is not found in the country list translation, and title is set to "allCountries.randommparampassed", In dev environment, app crashes as the country is not found in the country list.

### Solution

we need to validate the country param before setting the current country in the AddressPage, and if the country is invalid, we will not set the current country [here](https://github.com/expensify/App/blob/7dc923eb7562b819a4c7ba15a3197776b33c4792/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L156C7-L158C10).

```jsx
const isCountryFromUrlValid = lodashGet(CONST.ALL_COUNTRIES, countryFromUrl);
if (!countryFromUrl || countryFromUrl === currentCountry || !isCountryFromUrlValid)
```
Optionally we can set error message in the `CountrySelector` if the country is invalid, so that user can know that the country is invalid.
or we can show a Not Found page if the country param is invalid.

**Comment by DylanDylann** [comment] 2023-10-04 08:21
Could we consider this is regression from https://github.com/Expensify/App/pull/26742 ?

**Comment by stephanieelliott** [comment] 2023-10-06 05:18
> Could we consider this is regression from https://github.com/Expensify/App/pull/26742 ?

Hey @allroundexperts what do you think?

**Comment by mountiny** [comment] 2023-10-06 13:29
I don think its a regression but also edge case so lowering the amount

**Comment by mountiny** [comment] 2023-10-06 13:55
We will handle it as part of this issue https://github.com/Expensify/App/issues/23725

**Comment by mountiny** [comment] 2023-10-06 16:27
Yes, @stephanieelliott can you please pay this one out $50 to @ishpaul777

**Comment by stephanieelliott** [comment] 2023-10-10 03:00
[WIP] Summarizing payment on this issue -- @mountiny can you confirm this is right? Specifically, that we're paying only the bug reporter in this issue, and both C and C+ will be paid in https://github.com/Expensify/App/issues/23725

 - Issue reporter: $50 to @ishpaul777 (paid via Upwork, offer extended and awaiting acceptance)
 - Contributor: $0, being paid lump sum elsewhere, see https://github.com/Expensify/App/issues/23725#issuecomment-1750694824
 - Contributor+: @parasharrajat, being paid in https://github.com/Expensify/App/issues/2372
 
 Upwork job is [here](https://www.upwork.com/jobs/~01ad40bd8b7e5b3460), no bonus is included on final payout

**Comment by mountiny** [comment] 2023-10-10 13:22
LGTM

**Comment by stephanieelliott** [comment] 2023-10-11 05:18
Great, @ishpaul777 is paid so closing this one out!

**Closed by stephanieelliott** 2023-10-11 05:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
