### ISSUE TITLE
Android - Chat - The input field jumps when editing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13512] opened 2022-12-11 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to any chat
4. Sent any message
5. Tap and hold to view the action menu
6. Tap on the Pencil icon to activate the edit message box

## Expected Result:
The input field NOT jumps

## Actual Result:
The input field jumps

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** v1.2.38-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206919612-42ef305e-ba08-440b-93f6-2aad36d3f07d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2022-12-12 17:07
Seems the keyboard is being dismissed when it shouldn't be. I can help manage this after BZ checks

**Comment by MitchExpensify** [comment] 2022-12-12 19:30
I am heading ooo so need to reassign -  Reapplying the bug label

**Comment by AndrewGable** [comment] 2022-12-12 20:53
Isn't this a dupe of https://github.com/Expensify/App/issues/11048?

**Comment by MitchExpensify** [comment] 2022-12-12 21:14
100% looks like a dupe to me, closing this one in favor of #11048

**Closed by MitchExpensify** 2022-12-12 21:14 UTC
Labels: Daily, Bug
