### ISSUE TITLE
[$2000] mWeb/Safari is missing cursor in several pages of the app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19608] opened 2023-05-25 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to ND and open the following pages
2. Add PayPal -> 

- AddPayPalMePage
- Add New Contact Method -> NewContactMethodPage
- Connect Bank Account Step 1
- New Room Page
- New Chat/ New Group Search Page
- IOU Description Page -> MoneyRequestDescriptionPage
- TaskDescriptionPage
- TaskTitlePage

## Expected Result:
Cursor is autofocussed
## Actual Result:
No cursor when opening the pages
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/efe08f13-5193-436f-8284-8df48ba6a282

https://github.com/Expensify/App/assets/43996225/2efd869b-92a1-4da8-95b7-65c7c5d690df

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sobitneupane 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684811807573929?thread_ts=1681775845.071829&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9f2b3b8ff604a05</li>
        <li>Upwork Job ID: 1663292069357699072</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-05-26 21:16
Seems related https://github.com/Expensify/App/issues/19220

**Comment by sobitneupane** [comment] 2023-05-27 02:58
@MitchExpensify They are different issues. Here the issue is "Input is not auto-focused when user opens the page though it appears as if it is focused (input in highlighted in green color but misses cursor and keyboard).

**Comment by MitchExpensify** [comment] 2023-05-29 21:11
Thanks @sobitneupane !

**Comment by MitchExpensify** [comment] 2023-05-30 22:32
Not overdue

**Comment by ShogunFire** [comment] 2023-05-30 22:48
I don't reproduce

**Comment by mallenexpensify** [comment] 2023-05-31 03:01
Not sure how I got assigned when the `External` label was added, with Mitch assigned, unassigning myself

**Comment by MitchExpensify** [comment] 2023-06-09 12:06
No response from anyone in the thread, bumped it

**Comment by sobitneupane** [comment] 2023-06-09 12:11
> I don't reproduce

@ShogunFire It is reproducible only in real device (not reproducible in simulator)

**Comment by MitchExpensify** [comment] 2023-06-13 19:14
Ok seeing as this is reproducible and the above listed inputs auto-focus on all other platforms except IOS/safari I'm going to try find proposals in Slack..

**Comment by MitchExpensify** [comment] 2023-06-13 19:32
Actually I'm not sure why this didn't auto-double, doing so now manually

**Comment by MitchExpensify** [comment] 2023-06-13 19:36
Posted in open source here and doubled https://expensify.slack.com/archives/C01GTK53T8Q/p1686684947789839

**Comment by MitchExpensify** [comment] 2023-06-16 01:16
Ok based on @mananjadhav's feedback in Slack I'm going to go ahead and close this because Safari iOS won't auto focus the input and it won't allow us to programmatically do that as well. Sorry for the time it took to realize that and please let me know if I'm missing anything

**Closed by MitchExpensify** 2023-06-16 01:16 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by ShogunFire** [comment] 2023-06-16 01:29
Hello, have you seen my comment on slack as well ? I agree that Safari IOS is hard to autofocus but I think we should investigate why some screens seem to be able to do it as I showed in this video:

https://github.com/Expensify/App/assets/19537677/08763616-6e56-4d30-ad6d-2d268ab6a438

Especially the TextInput in OptionList are autofocused I haven't found the why though
