### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Web - There's no max length for editing private notes input

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27694] opened 2023-09-18 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report => report details => Private Notes.
2. Choose My Notes => Try to paste over 15,000 characters and click Save.
3. Verify that there's no limit character for editing private note Input.

## Expected Result:
Private note input should be limit character like other input.

## Actual Result:
There's no max length for editing private notes input.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b0aca28c-69f5-4a01-863b-84fc2f885ca5

https://github.com/Expensify/App/assets/93399543/b55047c2-7ca8-4892-9aea-092a3ecdf4f0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694923317416409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d2086d12246e4a8</li>
        <li>Upwork Job ID: 1703805477394239488</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26808029</li>
<li>hungvu193 | Reporter | 26808030</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-18 16:19
Proposal by: @hungvu193
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694923317416409

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There’s no max length limit for editing private notes TextInput and as I can see the browser is not responding after that.
### What is the root cause of that problem?
We didn’t have maxLength for our TextInput in here, so when user pasted large amount of characters ( > 30,000), it will make the App frozen.
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/PrivateNotes/PrivateNotesEditPage.js#L118-L132
### What changes do you think we should make in order to solve the problem?
We should add ` maxLength={CONST.MAX_COMMENT_LENGTH}` to our TextInput, similar with ReportWelcomeMessage.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by bfitzexpensify** [comment] 2023-09-20 10:49
A couple of proposals ready for review when you get a chance @burczu - thanks!

**Comment by burczu** [comment] 2023-09-20 11:48
@bfitzexpensify I'll be reviewing them soon.

**Comment by francoisl** [comment] 2023-09-22 00:42
Yep sounds good, pretty straightforward change.

**Comment by bfitzexpensify** [comment] 2023-10-03 18:42
Switching this to daily so I'm aware of it and action it on 10/5

**Comment by bfitzexpensify** [comment] 2023-10-06 18:34
Payments complete, please review the BZ checklist when you get a chance @burczu - thanks!

**Comment by bfitzexpensify** [comment] 2023-10-09 22:59
Friendly bump on the BZ checklist @burczu - thank you!

**Comment by burczu** [comment] 2023-10-10 11:32
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: It was working this way since the very beginning
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bfitzexpensify** [comment] 2023-10-10 23:03
OK, let's close this out - thanks everyone

**Closed by bfitzexpensify** 2023-10-10 23:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
