### ISSUE TITLE
[$500] Camera view is blank when using ‘Scan’

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37033] opened 2024-02-21 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @adelekennedy 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708450419664849

## Action Performed:

1. Navigate to FAB > request money
2. Tap on the Scan tab
3. Allow access
4. Camera view does not open in app
5. Take picture
6. Picture appears once split request is made

## Expected Result: 
Camera view should appear once access is granted
## Actual Result:
Camera view does not appear

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d1593624-da71-4553-929b-01587269b3c0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a341d74fdcb2a534</li>
        <li>Upwork Job ID: 1760339741189869568</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by Habtamu-Asefa** [comment] 2024-02-21 16:49
I could not reproduce on Android

**Comment by dm-freelancer** [comment] 2024-02-25 13:17
I tried this on Safari in my iPhone 14 and the camera works fine after granting permissions. I was not able to reproduce this.

**Comment by dm-freelancer** [comment] 2024-02-25 14:01
Contributor details
Your Expensify account email: divyanshumahajan.freelance@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012b58e691fb39254f

**Comment by stephanieelliott** [comment] 2024-02-27 07:19
I think this was an iOS issue! I was able to repro on v 16.7.5. Then I updated to 17.3.1 and was no longer able to repro -- the camera asked for permissions straight away, then after granting permissions it worked fine. So I think this is not our bug and has been resolved in the latest iOS version

**Closed by stephanieelliott** 2024-02-27 07:19 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
