### ISSUE TITLE
[HOLD for payment 2024-10-11] Track distance - Distance and Rate show “Pending” when tracking via Just track it route

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50051] opened 2024-10-02 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Go to Distance.
4. Enter waypoints > Next.
5. Click Just track it.

## Expected Result:
Distance and Rate will show the correct distance and rate when tracking via Just track it route.

## Actual Result:
Distance and Rate show “Pending” when tracking via Just track it route.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2ae08704-fb40-4064-8c43-5b10bd775c1e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by IuliiaHerets** [comment] 2024-10-02 11:33
We think that this bug might be related to #wave-collect - Release 1

**Comment by madmax330** [comment] 2024-10-02 12:21
cc @neil-marcellini can you take a look? Since you're more familiar with distance requests

**Comment by Shahidullah-Muffakir** [comment] 2024-10-02 13:13
Regression from https://github.com/Expensify/App/pull/49007

**Comment by madmax330** [comment] 2024-10-02 16:21
@grgia assigning you then since this is something that you're working on: https://github.com/Expensify/App/issues/48787

**Comment by abekkala** [comment] 2024-10-07 13:34
### PAYMENT SUMMARY FOR OCT 11

- Fix: Internal @grgia 
- PR Review: @fedirjh [$250, if no regressions] payment via NewDot

**Comment by abekkala** [comment] 2024-10-08 15:54
The PR showed Deployed to Production on Oct 4 - that would make payment on Oct 11, not the 14th
<img width="653" alt="Screenshot 2024-10-08 at 10 53 37 AM" src="https://github.com/user-attachments/assets/d45addb3-38ef-43e7-aa07-7ec907a932d6">

**Comment by abekkala** [comment] 2024-10-11 13:46
posting summary once more before closing: 

___

### PAYMENT SUMMARY FOR OCT 11
- Fix: Internal @grgia
- PR Review: @fedirjh [$250] payment via NewDot

**Closed by abekkala** 2024-10-11 13:46 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-10 12:16
$250 approved for @fedirjh
