### ISSUE TITLE
[$500] Workspace removed from list after using "clear cache and restart" in troubleshooting

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37977] opened 2024-03-08 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:

1.  Go to Settings and select "Create Workspace."
2. Navigate to your profile, click "About," then select "Troubleshoot."
3. Tap on "Clear Cache and Restart."
4. Go back and click on "Check Workspace." Notice that the workspace is no longer in the list.

## Expected Result:
The workspace should remain in the list after using "clear cache and restart" during troubleshooting.

## Actual Result:
Workspace removed from list after using "clear cache and restart" in troubleshooting

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f12e193e-8132-4864-b042-6acce9c0391f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afab748bcafa9d56</li>
        <li>Upwork Job ID: 1767293507810406400</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-03-08 15:05
We think that this bug might be related to #wave8-collect-admins
cc @zanyrenney

**Comment by jayeshmangwani** [comment] 2024-03-12 09:37
@m-natarajan I am able to see the workspaces after few moments, attaching a file below, also @GandalfGwaihir can you please confirm if workspace is coming for you after a few moments or not ?

https://github.com/Expensify/App/assets/35371050/a8e7b54d-44dd-4127-b1db-013534b3d23f

**Comment by jayeshmangwani** [comment] 2024-03-12 20:29
Thanks for the steps @GandalfGwaihir, Yes now I am able to reproduce with 1 new account, though issue is not consistent on my side, for 1 new account I was able to reproduce and for second new account, workspace is loading, I was wondering why it is working with the old accounts and not the newly created account ?

as per your [proposal](https://github.com/Expensify/App/issues/37977#issuecomment-1986121540), If we add the POLICY's to keysToPreserve array then issue is being solved but this is not the ideal solution(as I doubt we are intentionally resetting the workspace data), as here RCA is unclear, 

**can you answer this, why workspace is loading for the old accounts but not for the new account ?**

**Comment by jayeshmangwani** [comment] 2024-03-13 11:30
Thanks for the confirmation ,now I am not able to reproduce too,

**Comment by johncschuster** [comment] 2024-03-14 21:41
Great! I'll go ahead and close it then. Please reopen if you are able to reproduce the issue!

**Closed by johncschuster** 2024-03-14 21:41 UTC
Labels: External, Daily, Help Wanted, Bug
