### ISSUE TITLE
when entering dots and then phone number - Gives incorrect error - The email entered is invalid

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20634] opened 2023-06-12 23:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Open app
2 Enter .........+998901391803

## Expected Result: 
Correct error - as dots are not email
## Actual Result: 
Gives incorrect error - The email entered is invalid

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/26153580-ee6c-4169-b8c9-12372b10f2e9" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/5fad12e2-135b-4c46-b6e9-5150bb41abf5" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686152079294879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2023-06-14 16:16
Thanks @hungvu193 - i agree its a dupe of that issue and we already decided to do nothing here- https://expensify.slack.com/archives/C01GTK53T8Q/p1686576430054169?thread_ts=1686555416.737809&cid=C01GTK53T8Q

**Closed by zanyrenney** 2023-06-14 16:16 UTC
Labels: Daily, Bug
