### ISSUE TITLE
 Chat - Red dot appears when send message in Public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39064] opened 2024-03-27 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+gm128@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38503
## Action Performed:
1. Go to public room (https://staging.new.expensify.com/r/387000100885406
) or create your own public room
2. Type a message and click Send button

## Expected Result:
Message should be successfully sent and present in chat history

## Actual Result:
Unable to send message in Public room, red dot error appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/14c8c56b-10f1-4dbe-a614-70adc4df811c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-27 14:32
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-03-27 14:33
@johnmlee101  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johnmlee101** [comment] 2024-03-27 17:28
fixed! Closing as I cannot reproduce anymore

**Closed by johnmlee101** 2024-03-27 17:28 UTC
Labels: DeployBlockerCash, Engineering, Hourly
