### ISSUE TITLE
[HOLD for payment 2023-02-10] [$2000] Showing pointer cursor on code-block chat message instead of I-beam cursor

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14301] opened 2023-01-13 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat room.
2. Send code-block message `test`
3. Hover on code-block message.

## Expected Result:
On code-block message should show I-beam cursor as it not performing any action. We can copy it as normal text.

## Actual Result:
Showing Pointer cursor on code-block messages.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:**  y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212422639-254e0fcf-5b26-4c7b-ba42-d6b08d78c74b.mov

https://user-images.githubusercontent.com/43996225/212422663-770788a5-6969-4d88-a5b6-56dba52afd47.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673621030750769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c6f096c770787e9</li>
        <li>Upwork Job ID: 1615834499213443072</li>
        <li>Last Price Increase: 2023-01-25</li>
    </ul>
</details>

**Comment by arielgreen** [comment] 2023-01-18 22:09
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by mollfpr** [comment] 2023-01-19 03:06
Thanks, guys for the proposals!

Since this issue only occurs for the `pre` tag I'm inclined to add the style where it's needed. So, I say we can go with @Prince-Mendiratta [proposal](https://github.com/Expensify/App/issues/14301#issuecomment-1396198626). cc @cead22  @arielgreen 

🎀 👀 🎀 C+ reviewed!

**Comment by s77rt** [comment] 2023-01-19 19:24
### Proposal (kind of)
Revert `BasePreRenderer` to https://github.com/Expensify/App/blob/9f2ce1aeb95884d68ea5250867f8910dbb65d8dc/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/BasePreRenderer.js

### RCA
This is a regression by https://github.com/Expensify/App/pull/12987
After that PR the `PreRenderer` is now rendered in a `<Pressable />` and that does not make sense as we are only displaying text. That PR did change a lot so maybe the change of `PreRenderer` was unintentional. Need someone to confirm this.

**Comment by cead22** [comment] 2023-01-20 01:24
@mollfpr I think both solutions work, but I'm curious if you think using `TouchableWithoutFeedback` is better than hardcoding the style. If so, let's go with that proposal. If not, I agree with going with @Prince-Mendiratta 's

**Comment by mollfpr** [comment] 2023-01-20 01:54
@s77rt Do we really need the extra `View` inside the `TouchableWithoutFeedback`?

@cead22 Tested `TouchableWithoutFeedback` and it works without adding extra style. We can go with `TouchableWithoutFeedback` but I have concerns with the extra `View`.

I also notice that we have different feedback when long pressing on `code` and `pre` where it's no highlight background on `pre` (it's not caused by the proposal).

https://user-images.githubusercontent.com/25520267/213600957-9db6d6fc-90e8-4441-9a09-1dd994a7eb36.mov

If we use `TouchableWithoutFeedback` without the extra `View` we have the same feedback highlight on `code` and `pre`.


https://user-images.githubusercontent.com/25520267/213601154-b9cf5dd5-cea1-43cb-a5f2-98d6f110fff2.mov

**Comment by s77rt** [comment] 2023-01-20 09:28
@mollfpr If we don't wrap with `<View />` then the button won't work, in a sense we are applying my [proposal 1](https://github.com/Expensify/App/issues/14301#issuecomment-1397491022). If we do wrap with `<View />` the button will work leaving everything as it is just without the pointer cursor.

**Comment by s77rt** [comment] 2023-01-20 09:33
`<TouchableWithoutFeedback />` always require a `<View />`. You can verify that in our App.

**Comment by s77rt** [comment] 2023-01-20 10:03
@Prince-Mendiratta Other renders do not use it because it makes sense there to use `<Pressable /`> e.g. the attachment widget.

**Comment by cead22** [comment] 2023-01-20 19:21
> Thanks @Prince-Mendiratta @s77rt!

Just echoing this sentiment, thank you both again for your proposals
 
> Okay, after testing several times I couldn't find any issue with the `View` wrap and `TouchableWithoutFeedback`. I am more inclined to the `TouchableWithoutFeedback` [proposal](https://github.com/Expensify/App/issues/14301#issuecomment-1397505830) because changing the style feels hacky of course I will go with the style proposal if there's no way to fix the issue.

This was my original feeling that hardcoding the style was a little hacky, even tough it's a simple solution, so I think the `TouchableWithoutFeedback` proposal is the way to go.

> This is a regression by #12987 After that PR the `PreRenderer` is now rendered in a `<Pressable />` and that does not make sense as we are only displaying text. That PR did change a lot so maybe the change of `PreRenderer` was unintentional. Need someone to confirm this.

Before moving forward, I think it's worth confirming this, but given the Pressable component used there is being pass props `onPressIn`, `onPressOut`, and `onLongPress`, my guess is that it is necessary to use Pressable there. @parasharrajat @b1tjoy can you confirm?

**Comment by mollfpr** [comment] 2023-01-23 12:03
Thanks @b1tjoy for confirming it!

**Comment by cead22** [comment] 2023-01-23 23:37
Alright, thanks again to everyone for their input. Let's move forward with @s77rt 's proposal with `TouchableWithoutFeedback` @arielgreen

**Comment by situchan** [comment] 2023-01-26 14:18
According to https://github.com/Expensify/App/issues/14589, not sure about using `TouchableWithoutFeedback` is permanent solution here.

**Comment by arielgreen** [comment] 2023-01-26 19:35
@s77rt please let me know when you've applied on Upwork https://www.upwork.com/jobs/~014c6f096c770787e9

**Comment by s77rt** [comment] 2023-01-26 19:42
Hmm I thought we would wait for a clarification from https://github.com/Expensify/App/issues/14589
Well, since I'm assigned already will start working on that and decide later...

**Comment by s77rt** [comment] 2023-01-26 20:24
Applied in [Upwork](https://www.upwork.com/jobs/~014c6f096c770787e9).
[PR](https://github.com/Expensify/App/pull/14605) is ready.

cc @arielgreen

**Comment by mollfpr** [comment] 2023-01-27 15:18
Any thoughts on https://github.com/Expensify/App/issues/14301#issuecomment-1405070267? @arielgreen @cead22

**Comment by cead22** [comment] 2023-01-27 17:59
cc @mountiny since you created that issue. What do you think about this proposal?

**Comment by cead22** [comment] 2023-01-27 20:20
Discussing in slack

**Comment by cead22** [comment] 2023-01-30 16:47
@mollfpr you're good to continue forward with this issue per the [slack discussion ](https://expensify.slack.com/archives/C01GTK53T8Q/p1674849188218889?thread_ts=1674844591.879669&cid=C01GTK53T8Q)

**Comment by s77rt** [comment] 2023-02-04 09:14
Regression Steps:
1. Go to any chat
2. Send a code-block message
3. Hover over the message
4. Verify that the cursor is I-beam (and not pointer)

**Comment by arielgreen** [comment] 2023-02-06 01:05
OOO this week -- reassigning so payment isn't held on me.

**Comment by mollfpr** [comment] 2023-02-07 07:10
> [@mollfpr / @cead22] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/12987

> [@mollfpr / @cead22] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/12987#issuecomment-1420296167

**Comment by cead22** [comment] 2023-02-10 01:02
> [ ] [@mollfpr / @cead22] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

@mollfpr do you want to kick off a discussion about this? Perhaps we can everyone that when working with code blocks they should always make sure the cursor is the I-beam, or maybe we can add a new item to the reviwer checklist like: if you're updating code relating to rendering a code block, make sure the cursor on code blocks is still the I-beam cursor (or is that overkill?)

Let me know what you think, and I'm also happy to start the convo in slack. Thanks!

**Comment by mollfpr** [comment] 2023-02-13 08:36
@cead22 Sorry, I missed this.

Adding a new checklist will be overkill; it’s a rare case with updating the component. 

Let’s start a slack chat if you have another thoughts.

**Comment by slafortune** [comment] 2023-02-14 22:28
@mollfpr @cead22 Was there a discussion started?  I don't see that in Slack yet - so held off paying this out as the final step.

**Comment by mollfpr** [comment] 2023-02-15 13:46
@cead22 @slafortune start a [discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1676468691175009) on Slack!

**Comment by mollfpr** [comment] 2023-02-17 00:35
@slafortune Accepted the offer, thank you!

**Comment by slafortune** [comment] 2023-02-17 18:23
All paid - 
![image](https://user-images.githubusercontent.com/11725910/219749580-b8af34eb-ed41-4018-bc71-6b91813e2274.png)

**Closed by slafortune** 2023-02-17 18:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
