### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Inconsistent styling on create task push to page

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#20007] opened 2023-06-01 21:05 UTC
https://expensify.slack.com/archives/C04QEB4MJEQ/p1685378425623999

The labels should use our textSupporting color
The small label should be closer to the value
the arrows/carets should use our icon color and should be at 20x20

The style on the second step of creating a task is inconsistent with the push-to-page style from other places in the app. I feel like we keep recreating this style instead of just using the same global component.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018dddd8a08831da39</li>
        <li>Upwork Job ID: 1664377958553657344</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-06-01 21:06
Current:
<img width="725" alt="Screenshot 2023-06-01 at 2 05 57 PM" src="https://github.com/Expensify/App/assets/30609178/2e34b0c0-f03b-4634-8c63-244cb40d3cd8">


Styles should look like
<img width="654" alt="Screenshot 2023-06-01 at 2 06 18 PM" src="https://github.com/Expensify/App/assets/30609178/b1b3ea36-ecc2-4214-8c0a-ef79b3502a1a">

**Comment by sethraj14** [comment] 2023-06-01 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistent styling on create task push to page

### What is the root cause of that problem?

Not providing right styles to the text and icons

### What changes do you think we should make in order to solve the problem?

We could make the styles consistent by changing these lines - 

` <Text style={[styles.label, styles.textLabelSupporting, props.icons.length > 0 ? styles.mb2 : styles.mb0]}>{props.translate(props.label)}</Text>`

and pass these styles to icon - 

`                    <Icon
                        src={Expensicons.ArrowRight}
                        fill={themeColors.icon}
                        width={variables.iconSizeNormal}
                        height={variables.iconSizeNormal}
                        inline
                    />`

![Screenshot 2023-06-02 at 2 53 51 AM](https://github.com/Expensify/App/assets/14844259/08cf7a85-7c39-4e2f-9491-9740b0e201d8)


### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-06-01 21:44
@allroundexperts Thanks for the proposal. Can we re-use `MenuItemWithTopDescription` instead of recreating the component?

**Comment by s77rt** [comment] 2023-06-01 21:45
@sethraj14 Thanks for the proposal. Same question as above ^

**Comment by sethraj14** [comment] 2023-06-01 22:34
> @allroundexperts Thanks for the proposal. Can we re-use `MenuItemWithTopDescription` instead of recreating the component?

Yes, I was exploring the same as we use this in every other place.

**Comment by sethraj14** [comment] 2023-06-01 23:23
@s77rt 

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistent styling on create task push to page

### What is the root cause of that problem?

Not providing right styles to the text and icons

### What changes do you think we should make in order to solve the problem?

In order to shift to MenuItemWithTopDescription we have these fields to map - 

1. `label` -> `description` (with props.translate(<value_here>))
2. `text` -> `title`
3. `onPress` -> `onPress`
4. `disabled` -> `shouldShowRightIcon`
5. `alternateText` -> Add new props `alternateText` to MenuItem 
6. `icon` -> Add support for array of icons 

After adding these props, we need to change the MenuItem file like this [here](https://github.com/Expensify/App/blob/f4f89a0cac5b07265e82c85e69e48720997ba84b/src/components/MenuItem.js#L171)-

```javascript
                                {Boolean(props.icon) && _.isArray(props.icon) && (
                                    <MultipleAvatars
                                        icons={props.icon}
                                        size={CONST.AVATAR_SIZE.DEFAULT}
                                        secondAvatarStyle={[StyleUtils.getBackgroundAndBorderStyle(themeColors.appBG)]}
                                    />
                                )}
                                {Boolean(props.alternateText) && (
                                    <View style={[styles.pl0]}>
                                        <Text
                                            style={titleTextStyle}
                                            numberOfLines={1}
                                        >
                                            {convertToLTR(props.title)}
                                        </Text>
                                        <Text style={StyleUtils.combineStyles(styles.sidebarLinkText, styles.optionAlternateText, styles.textLabelSupporting, styles.pre)}>
                                            {props.alternateText}
                                        </Text>
                                    </View>
                                )}
``` 


Hover should be there as it will be consistent with other similar screens. 

Discard `isShareDestination` as it is not doing anything in the current implementation

Finally the [NewTaskPage](https://github.com/Expensify/App/blob/f4f89a0cac5b07265e82c85e69e48720997ba84b/src/pages/tasks/NewTaskPage.js#L124) file will look like this - 

```javascript
<ScrollView>
                <View style={styles.flex1}>
                    <MenuItemWithTopDescription
                        description={props.translate('newTaskPage.title')}
                        title={props.task.title}
                        onPress={() => Navigation.navigate(ROUTES.NEW_TASK_TITLE)}
                        shouldShowRightIcon={true}
                    />
                    <MenuItemWithTopDescription
                        description={props.translate('newTaskPage.description')}
                        title={props.task.description}
                        onPress={() => Navigation.navigate(ROUTES.NEW_TASK_DESCRIPTION)}
                        shouldShowRightIcon={true}
                    />
                    <MenuItemWithTopDescription
                        alternateText={assignee.subtitle}
                        description={props.translate('newTaskPage.assignee')}
                        title={assignee.displayName || ''}
                        onPress={() => Navigation.navigate(ROUTES.NEW_TASK_ASSIGNEE)}
                        shouldShowRightIcon={true}
                        icon={assignee.icons}
                    />
                    <MenuItemWithTopDescription
                        alternateText={shareDestination.subtitle}
                        description={props.translate('newTaskPage.shareSomewhere')}
                        title={shareDestination.displayName || ''}
                        onPress={() => Navigation.navigate(ROUTES.NEW_TASK_SHARE_DESTINATION)}
                        shouldShowRightIcon={true}
                        icon={shareDestination.icons}
                    />
                    <FormAlertWithSubmitButton
                        isAlertVisible={submitError}
                        message={errorMessage}
                        onSubmit={() => onSubmit()}
                        enabledWhenOffline
                        buttonText={props.translate('newTaskPage.confirmTask')}
                        containerStyles={[styles.mh0, styles.mt5, styles.flex1]}
                    />
                </View>
            </ScrollView>
``` 

The final solution will be cleaned and optimized.

### What alternative solutions did you explore? (Optional)

We could make the styles consistent by changing these lines - 

` <Text style={[styles.label, styles.textLabelSupporting, props.icons.length > 0 ? styles.mb2 : styles.mb0]}>{props.translate(props.label)}</Text>`

and pass these styles to icon - 

`                    <Icon
                        src={Expensicons.ArrowRight}
                        fill={themeColors.icon}
                        width={variables.iconSizeNormal}
                        height={variables.iconSizeNormal}
                        inline
                    />`

![Screenshot 2023-06-02 at 2 53 51 AM](https://github.com/Expensify/App/assets/14844259/08cf7a85-7c39-4e2f-9491-9740b0e201d8)

**Comment by s77rt** [comment] 2023-06-02 13:21
@allroundexperts Thanks. This is looking good but let's not worry about the hover style, it's better to keep it for consistency.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @thienlnam

**Comment by s77rt** [comment] 2023-06-02 13:22
@sethraj14 Thanks. I think the idea is the same as @allroundexperts's so we will just go with the first. But feel free to check other issues with Help Wanted label [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22).

**Comment by s77rt** [comment] 2023-06-12 21:39
Not overdue. PR is merged.

**Comment by muttmuure** [comment] 2023-06-12 23:52
Not on prod yet

**Comment by muttmuure** [comment] 2023-06-26 10:20
@allroundexperts @s77rt invited to job

**Comment by s77rt** [comment] 2023-06-26 12:47
@muttmuure Applied!

**Comment by muttmuure** [comment] 2023-06-28 14:59
Offer sent to @s77rt. Still waiting on @allroundexperts to apply

**Comment by s77rt** [comment] 2023-06-28 17:56
@muttmuure Accepted!

**Comment by muttmuure** [comment] 2023-07-03 12:35
@s77rt paid, @allroundexperts offer sent

**Comment by thienlnam** [comment] 2023-07-06 00:14
I think we're all good here? @allroundexperts Did your contract get paid out?

**Comment by muttmuure** [comment] 2023-07-06 16:42
Contract paid out for @allroundexperts too. 

Thanks for your patience here!

**Closed by muttmuure** 2023-07-06 16:42 UTC
Labels: External, Daily, Improvement, Awaiting Payment
