### ISSUE TITLE
[$250] Web - Expense - New line marker is not removed in thread after Holding an expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50302] opened 2024-10-06 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** [Yokabdk+new206@gmail.com](mailto:Yokabdk+new206@gmail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click the FAB
3. Click on submit expense and submit the expense
4. Click the IOU and Hold Button
5. Input reason and Hold expense
6. Observe the new line marker doesn't disappear after seeing the reply in the thread multiple times
7. Click the IOU and Unhold Button
8. Observe the new line marker doesn't disappear

## Expected Result:
The new line marker should disappear after the reply is opened and the reason is observed by a user

## Actual Result:
The New line marker doesn't Disappear After user observes the reason in the thread for multiple times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/bd1feea5-e21f-441a-be04-ffc62d62f3fd

![_Photo_2](https://github.com/user-attachments/assets/0acb6dfa-4c41-493e-96d2-77c66ce3f349)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843326088684628926</li>
        <li>Upwork Job ID: 1843326088684628926</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-10-07 19:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The **New Marker** is not removed, even after opening the tread of hold reason multiple times 
### What is the root cause of that problem?
the condition **shouldDisplayNewMarker** is not added in this place:
https://github.com/Expensify/App/blob/96957ef42d1df2c7318cde7f28ffaf0f09652680/src/pages/home/report/ReportActionItemContentCreated.tsx#L63


as it is added here, in few other places:
https://github.com/Expensify/App/blob/fb4e24eca0905c8dec0c6dc69b4758aa66f2a791/src/pages/home/report/ReportActionItem.tsx#L929

### What changes do you think we should make in order to solve the problem?
Pass **shouldDisplayNewMarker** as a prop in :
https://github.com/Expensify/App/blob/fb4e24eca0905c8dec0c6dc69b4758aa66f2a791/src/pages/home/report/ReportActionItem.tsx#L853-L859

then use it here:
https://github.com/Expensify/App/blob/fb4e24eca0905c8dec0c6dc69b4758aa66f2a791/src/pages/home/report/ReportActionItemContentCreated.tsx#L63-L67
as
```
    shouldDisplayNewMarker && shouldHideThreadDividerLine ? (
                <UnreadActionIndicator
                    reportActionID={report.reportID}
                    shouldHideThreadDividerLine={shouldHideThreadDividerLine}
                />
```

**Comment by Shahidullah-Muffakir** [comment] 2024-10-07 20:28
https://github.com/user-attachments/assets/cd5818a4-6b1a-43ea-822f-4808b38954fc

**Comment by c3024** [comment] 2024-10-08 10:23
@Shahidullah-Muffakir 

Thanks for your proposal. Can you please elaborate on the RCA?

If `shouldHideThreadDividerLine` is `true` it means the first visible action is unread here.

https://github.com/Expensify/App/blob/016822b3d7b956fcd0a27790c7b9f9ce5a1f85b0/src/pages/home/report/ReportActionsList.tsx#L439-L442

When it is unread why is the marker showing up there irrespective of whether we check for `shouldDisplayNewMarker` or not?

**Comment by klajdipaja** [comment] 2024-10-09 12:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a report is marked as hold the action in the child report shows as unread but it stays always unread even when the user moves between reports.

### What is the root cause of that problem?

When a child report is visited the `readNewestAction` API is not called which would update the lastReadTime of the report so that on the next visit the user does not see the marker again. This is called when the user switches between reports only or opens the report from a different tab or browser. There are multiple side effects in https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.tsx that manages these scenarios.



### What changes do you think we should make in order to solve the problem?
We need to trigger the `readNewestAction` API when the child report is opened as we have done for marking tasks as read in ReportScreen.tsx in this line:
https://github.com/Expensify/App/blob/3777223374152bb83333674e06b3497aaea27b81/src/pages/home/ReportScreen.tsx#L683

We can change the condition to check if the report is a Child Report so that it can be generlized to more scenarios not just tasks:
```
if (!!report?.lastReadTime || !ReportUtils.isChildReport(report)) {
            return;
        }
```

This would then allow for the read newest action to be called for all child reports



### What alternative solutions did you explore? (Optional)

**Comment by klajdipaja** [comment] 2024-10-10 10:59
Updated proposal https://github.com/Expensify/App/issues/50302#issuecomment-2402124270 .
The initial RCA and solution was working only sometimes when the data matched the conditions.

For the current proposal I have created this DRAFT PR #50551 .
If you want to check what I refer to as "complete solution" in my proposal take a look at the first commit in the PR

**Comment by c3024** [comment] 2024-10-10 16:41
@klajdipaja 

Is this still reproducible?

I don't see this bug on latest `main`.





https://github.com/user-attachments/assets/898f2ac0-71de-4a1d-8e17-d34149c9a2fd

**Comment by klajdipaja** [comment] 2024-10-10 18:30
Well that sucks for me 😅. I tried on stage now and it's not reproducible anymore. I was working on the proposal this morning with the latest main so not sure what changed

**Comment by sakluger** [comment] 2024-10-10 18:48
Thanks for checking again, and sorry you didn't get a chance to finish this one yourself @klajdipaja. I'm going to go ahead and close the GH issue since it seems like it's fixed now.

**Closed by sakluger** 2024-10-10 18:48 UTC
Labels: External, Daily, Help Wanted, Bug
