### ISSUE TITLE
[HOLD for #17387][$1000] BUG: "Hmm...this page is not there" page displayed when assigning task with invalid email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22032] opened 2023-07-02 01:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign :heavy_plus_sign:
2. Select "Request" and Assign Task, then click "Next"
3. Add a Title and click "Next"
4. Click on Assign and add an invalid email such as eg 1, jone.due@-[gmail.com](http://gmail.com/) or eg 2, "—@—.com", then confirm tasks
## Expected Result: 
The app should display a relevant error message indicating that the email is invalid.
## Actual Result: 
The app displays a "Hmm...this page is not there" page when assigning a task with an invalid email.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/41faa7c9-2851-4d10-98f8-4786c9bb9dba

https://github.com/Expensify/App/assets/43996225/9a58b532-124b-45eb-aea4-f9ab89e06346

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688106565970839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bf82589e89e90e5</li>
        <li>Upwork Job ID: 1675763215630663680</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-03 07:07
Reproduced:

https://github.com/Expensify/App/assets/59587260/0fbba743-29a7-4d74-9caf-3e22c098ea3a

**Comment by alexxxwork** [comment] 2023-07-03 08:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The app displays a "Hmm...this page is not there" page when assigning a task with an invalid email.

### What is the root cause of that problem?

The root cause is similar to this issue https://github.com/Expensify/App/issues/21896
1. Front-end allows to enter invalid email and calls OpenReport on assignee field row select.
https://github.com/Expensify/App/blob/5009b8d5d8edd5e9bb6f4f6def88c5acaea8bc3c/src/pages/tasks/TaskAssigneeSelectorModal.js#L161
2. This call ends with an error from BE which isn't handled
```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Error\\Email\\InvalidEmail",
    "UUID": "a9444a52-b2b2-491a-a0a3-3c56c6a16c09",
    "message": "a@---v.vc - is not a valid email address",
    "title": "",
    "data": {
```
3. BE returns error on task creation because of invalid parent error from previous step

### What changes do you think we should make in order to solve the problem?


We could check entered email for validity before selection

### What alternative solutions did you explore? (Optional)

We could check for BE errors before closing create task modal

**Comment by kadiealexander** [comment] 2023-07-05 01:57
@0xmiroslav please review the proposal above!

**Comment by lazar-stamenkovic** [comment] 2023-07-05 02:48
### Please re-state the problem that we are trying to solve in this issue.
The app displays a "Hmm...this page is not there" page when assigning a task with an invalid email.

### What is the root cause of that problem?
this issue is caused because email validation works incorrectly in OptionsListUtils.getHeaderMessage called within TaskAssigneeSelectorModal.js
https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/pages/tasks/TaskAssigneeSelectorModal.js#L98

for example, invalid email "--@--.com" passes this email validation checking but the backend returns invalid email error.

### What changes do you think we should make in order to solve the problem?
The email validation checking function is derived from the expensify-common library. It is crucial to update the isValidEmail function in the str.js file within the expensify-common library. This update will ensure that the email validation functions consistently, aligning with the backend's behavior.
it may be necessary to update the CONST.REG_EXP.EMAIL in the const.jsx file within the expensify-common library for comprehensive email validation.

### What alternative solutions did you explore? (Optional)
If you give me access for the expensify-common library repositiory or want to fix this in the app repo, i can work on this.

**Comment by kadiealexander** [comment] 2023-07-10 05:41
@0xmiroslav please review the proposals here!

**Comment by kadiealexander** [comment] 2023-07-12 01:13
As we have two proposals that have not been reviewed, and 4 reminders [here](https://github.com/Expensify/App/issues/22032#issuecomment-1628257059), [here](https://github.com/Expensify/App/issues/22032#issuecomment-1620909178), [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1688696413524889) and [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1688959565214009?thread_ts=1688696413.524889&cid=C02NK2DQWUX), I've reached out to the C+ team to see if there's anyone who can take this one on.

**Comment by mananjadhav** [comment] 2023-07-12 01:25
Thanks for the proposals folks. I can see both the proposal follow the guidelines to keep the jargons out, but we could add some technical details. 

@alexxxwork could you mention where would the change be ? What would the change be? Will it use an existing util or will you write a new one ? 


@lazar-stamenkovic That is an interesting find, I’ll confirm if the Regex fails for only some or all the cases. You’re correct that if we were to fix the regex we’ll have to update the Expensify-common package. But your proposal also misses the details of what will be changed ? You’ve mentioned comprehensive, but can we please elaborate what we mean by that? Which cases will we cover ?

**Comment by lazar-stamenkovic** [comment] 2023-07-12 01:41
@mananjadhav this issue is produced because some invalid email passes email validation checking through CONST.REG_EXP.EMAIL in the const.jsx file within the expensify-common library.

ex:   "jone.due@-gmail.com" or eg 2, "—@—.com"".  these emails are invalid email.  but the frontend returns true on email validation checking for these emails and calls the backend api with these invalid emails.
then backend returns invalid email error and the frontend displays this screen "Hmm..."

So we need to fix CONST.REG_EXP.EMAIL in the const.jsx file within the expensify-common library so that it returns false for these invalid emails, prevent to call backend api and displays correct error message.

Again, CONST.REG_EXP.EMAIL in the const.jsx file within the expensify-common library are used in all email fields in the app.
so this issue is caused in all screens with email input field. For example, login page and add new contact info screen etc.

Would you please take a look how the app works after inputing these invalid emails in task assigning page, contact info adding page and log in page?

**Comment by alexxxwork** [comment] 2023-07-12 02:37
@mananjadhav The inconsistencies of `Str.isValidEmail` would be fixed in #17387

**Comment by mananjadhav** [comment] 2023-07-12 02:51
Thanks @aimane-chnaif. @kadiealexander as suggested we should put this on hold.

**Comment by kadiealexander** [comment] 2023-07-19 03:25
Sorry, was OOO! Popping this on hold.

**Comment by kadiealexander** [comment] 2023-07-28 05:49
Still on hold.

**Comment by kadiealexander** [comment] 2023-08-08 06:05
Same as above.

**Comment by kadiealexander** [comment] 2023-08-22 06:12
Still on hold.

**Comment by kadiealexander** [comment] 2023-08-31 06:46
The issue that this was on hold for is now done, and it looks like this issue is fixed!

![image](https://github.com/Expensify/App/assets/59587260/fdbfe31a-bf2d-4703-a8dd-1e337073f425)

Closing.

**Closed by kadiealexander** 2023-08-31 06:46 UTC
Labels: External, Weekly, Overdue, Bug

**Comment by tewodrosGirmaA** [comment] 2023-11-08 10:38
Hello @kadiealexander, I received the offer but it has not been settled yet. I apologize for the delay. I have reported this issue and I would appreciate your help in resolving this matter. Thank you.

**Comment by kadiealexander** [comment] 2023-11-08 22:25
@tewodrosGirmaA We pay the bug reporter that was listed on the original issue that fixed the bug, in this case that was completed [here](https://github.com/Expensify/App/issues/17387). Thanks for understanding.
