### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Expense - Title field is not grayed out when edited offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45072] opened 2024-07-09 13:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44988
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Click on the expense preview
5. Go offline
6. Click on the report header
7. Click Title field
8. Edit the title and save it

## Expected Result:
The title field will be grayed out when edited offline

## Actual Result:
The title field is not grayed out when edited offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8a439639-5419-404a-b237-de7ea5a5467c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef7d62e69d5030af</li>
        <li>Upwork Job ID: 1811445257984330574</li>
        <li>Last Price Increase: 2024-07-18</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103220965</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by etCoderDysto** [comment] 2024-07-09 13:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Title field is not grayed out when edited offline
### What is the root cause of that problem?
When updating title we add pending action to `report.pedingFields.reportName`. But
we are passing only `report.pendingFields?.[fieldKey]` to pendingAction of report title here
https://github.com/Expensify/App/blob/9c32293ab6c0465eec38f1c573b8b5a09e1e112d/src/pages/ReportDetailsPage.tsx#L597-L599
### What changes do you think we should make in order to solve the problem?
we should add `report?.pendingFields?.reportName` to pendingAction too
```
 pendingAction={report.pendingFields?.[fieldKey] ?? report?.pendingFields?.reportName}
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-07-09 13:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Title field is not grayed out when edited offline
### What is the root cause of that problem?
When updating title we add pending action to `report.pedingFields.reportName`. But
we are passing only `report.pendingFields?.[fieldKey]` to pendingAction of report title here
https://github.com/Expensify/App/blob/9c32293ab6c0465eec38f1c573b8b5a09e1e112d/src/pages/ReportDetailsPage.tsx#L597-L599
### What changes do you think we should make in order to solve the problem?
we should add `report?.pendingFields?.reportName` to pendingAction too
```
 pendingAction={report.pendingFields?.[fieldKey] ?? report?.pendingFields?.reportName}
```

### What alternative solutions did you explore? (Optional)

Result: 

https://github.com/Expensify/App/assets/171434916/48942e9b-c5c4-4c25-bb28-715be2188b5b

**Comment by cdOut** [comment] 2024-07-19 08:45
@dominictb laid it out the best, we definitely need to be using both the `report.pendingFields?.[fieldKey]` and `report.pendingFields?.reportName` for pendingAction and errors, however if we want to look for the report name field in the error section we would also need to include it in the clearing method `Report.clearReportFieldErrors(report.reportID, titleField)`, which would have to be refactored to also support passing singular field keys instead of entire fields, so that was definitely missing in the proposal.

Should I go ahead and create a PR for it?

cc: @fedirjh

**Comment by trjExpensify** [comment] 2024-07-19 11:19
Report fields is being built in #wave-control, moving to that project. CC: @caitlinwhite1 @thienlnam

**Comment by cdOut** [comment] 2024-07-22 15:24
I can raise the PR for this one, this is a very small change so there shouldn't be many problems with it.

**Comment by aldo-expensify** [comment] 2024-07-22 19:13
Assigned @dominictb first for the automatic upwork job creation.

@cdOut will raise a PR now, correct?

**Comment by aldo-expensify** [comment] 2024-07-22 19:14
@miljakljajic I followed @fedirjh 's suggestion [here](https://github.com/Expensify/App/issues/45072#issuecomment-2243203145) for handling assignment/payment.

**Comment by cdOut** [comment] 2024-07-22 20:35
Yup, I'm raising the PR now.

**Comment by cdOut** [comment] 2024-07-22 21:59
PR raised, recorded a video and moved it to review.

**Comment by JmillsExpensify** [comment] 2024-08-05 11:57
@miljakljajic payment summary when you get a chance.

**Comment by miljakljajic** [comment] 2024-08-05 12:19
@fedirjh is owed 250 for their work reviewing this issue

**Comment by JmillsExpensify** [comment] 2024-08-05 12:43
$250 approved for @fedirjh

**Comment by miljakljajic** [comment] 2024-08-07 09:22
Paid you too @dominictb , thank you!

**Closed by miljakljajic** 2024-08-07 09:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
