### ISSUE TITLE
[$500] Hold Request - Composer is focused while RHP is open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36829] opened 2024-02-20 04:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Sign up with a new account
2. Create an IOU with a user
3. Navigate to IOU reports details page
4. Click on three dot › Hold request > enter reason › press enter
## Expected Result:
Composer shouldn't be focused

## Actual Result:
Composer is focused

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/e0e46e07-6a66-45e8-ad8f-f3e4799b7b44

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d88b69191153c8ff</li>
        <li>Upwork Job ID: 1759792841964003328</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-02-20 04:12
We think this bug might be related to  #vip-bills
cc @davidcardoza

**Comment by rushatgabhane** [comment] 2024-02-20 04:13
is this severe enough to be deploy blocker?

**Comment by MonilBhavsar** [comment] 2024-02-20 09:10
Agree, we can remove deploy blocker as it is not critical.
Commented on the PR it is coming from https://github.com/Expensify/App/pull/33897#issuecomment-1953770498

**Comment by dragnoir** [comment] 2024-02-20 09:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Git it button is not focused

### What is the root cause of that problem?

On the 1st screen, "Hold Request", when the button "Hold Request" is clicked, there's an actiopn to turn back to the main request report screen, wish bring back focus to the "Write anything..' input

https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/pages/iou/HoldReasonPage.tsx#L42-L49

The navigate back function turn to the main report screen and does not open the next "This request is on Hold" screen.

### What changes do you think we should make in order to solve the problem?

When the screen "This request is on Hold" is opened we need to set the focus on the "Got it" button on src/pages/ProcessMoneyRequestHoldPage.tsx

```js
const  submitBtn  =  useRef<View>(null);

useFocusEffect(
  React.useCallback(() => {
    if (!submitBtn.current) {
      return;
    }
    submitBtn.current.focus();
  }, []),
);

<Button
  ref={submitBtn}
```

**Comment by dylanexpensify** [comment] 2024-02-20 09:40
@rushatgabhane to review proposal!

**Comment by MonilBhavsar** [comment] 2024-02-20 09:43
Should this be handled as regression as it coming from https://github.com/Expensify/App/pull/33897 that was deployed last night

**Comment by BartoszGrajdek** [comment] 2024-02-20 18:20
This issue is a duplicate of https://github.com/Expensify/App/issues/36825 - after we fix the original issue this won't be a problem anymore

**Comment by robertjchen** [comment] 2024-02-20 22:02
Closing, to be handled in https://github.com/Expensify/App/issues/36825

**Closed by robertjchen** 2024-02-20 22:02 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
