### ISSUE TITLE
[HOLD for payment 2023-11-01] [$500] The error message does not close in one click if the address dropdown is open.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29433] opened 2023-10-12 12:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1,3,80,0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696764596197229

## Action Performed:
1. Go to the staging environment.
2. Open the FAB icon and select the "Request Money" option.
3. Navigate to the distance tab and click on "Start."
4. Trigger an error message by selecting "use current location" and denying access.
5. Open the dropdown by clicking on the address input and entering a few characters.
6. Attempt to close the error message by clicking the close button on the error.
7. Observe that the dropdown is closed, but the error message remains open.

## Expected Result:
The error message should be removed with a single click just like in native devices

## Actual Result:
Attempting to close the error results in the dropdown closing, but the error message persists.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/a927264e-d30c-483a-aed8-d84b9e5939ec

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/648bf67e-bac0-4611-a452-cfa2d9d5f86d

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/81a62217-5550-46f6-8d38-996c7ff7ebcf

https://github.com/Expensify/App/assets/93399543/8e45c45a-ab1f-47e1-9ca5-8d66ddcc4ca2

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/5f404cdf-e1ac-408f-b1d4-f672fd9bfc8e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019bb896d532ae6056</li>
        <li>Upwork Job ID: 1712446430446161920</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27266011</li>
<li>bernhardoj | Contributor | 27266013</li>
<li>aman-atg | Reporter | 27266014</li>
</ul></li>
    </ul>
</details>

**Comment by Samueljh1** [comment] 2023-10-12 12:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error message does not close in one click if the address dropdown is open.

### What is the root cause of that problem?
The dropdown menu is preventing click/touch events from bubbling down to other components.

### What changes do you think we should make in order to solve the problem?
Modify code in the dropdown menu to ensure click events are passed down to other components.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by pradeepmdk** [comment] 2023-10-12 13:24
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

The error message does not close in one click if the address dropdown is open.
### What is the root cause of that problem?

in react-native-google-places-autocomplete plugin when input box blur triggered time flat list is hidden so at the time next event is not triggering 
https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/ef107387c6846924423b832a242eee83cb07eed4/GooglePlacesAutocomplete.js#L721

### What changes do you think we should make in order to solve the problem?
https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/ef107387c6846924423b832a242eee83cb07eed4/GooglePlacesAutocomplete.js#L725
here we need to set into set timeout

### Result

**Comment by JmillsExpensify** [comment] 2023-10-17 21:04
@ntdiary Thoughts on the proposals so far?

**Comment by JmillsExpensify** [comment] 2023-10-24 22:52
PR merged. Waiting for it to hit production and start the regression hold.

**Comment by JmillsExpensify** [comment] 2023-10-25 18:25
@ntdiary Mind kicking off the BZ checklist?

**Comment by JmillsExpensify** [comment] 2023-10-25 18:26
In the meantime, payment summary:

 - Issue reporter: @aman-atg $50
 - Contributor: @bernhardoj $750 (incl. urgency bonus)
 - Contributor+: @ntdiary $750 (incl. urgency bonus)

**Comment by tylerkaraszewski** [comment] 2023-11-03 21:56
Doesn't need to be overdue.

**Comment by JmillsExpensify** [comment] 2023-11-08 12:37
> > **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> > 
> > * [x]   [@ntdiary] The PR that introduced the bug has been identified. Link to the PR: [Allow user to get current location #25990](https://github.com/Expensify/App/pull/25990)
> > * [x]   [@ntdiary] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25990/files#r1372692571
> > * [x]   [@ntdiary] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **No need**
> > * [x]   [@ntdiary] Determine if we should create a regression test for this bug. **No need**
> > * [x]   [@ntdiary] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **No need**
> > * [ ]   [@JmillsExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
> 
> Just a minor feature polish, no need to add regression test. Hey, @JmillsExpensify, very happy to work on issues with you again. I still remember the [previous comment](https://github.com/Expensify/App/issues/27365#issuecomment-1752036807), so here it's fine to just pay me $500. 😄

Thanks!

**Comment by JmillsExpensify** [comment] 2023-11-08 12:40
Everyone paid out based on summary above. Closing.

**Closed by JmillsExpensify** 2023-11-08 12:40 UTC
Labels: External, Daily, Awaiting Payment, Bug
