### ISSUE TITLE
FAB menu - Console error when clicking FAB button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21952] opened 2023-06-30 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click on the green plus button (FAB)

## Expected Result:
Global create menu opens and there is no error in the console

## Actual Result:
Console error appears.
The same behavior when clicking on:
1. `+` button near composer
2. Emoji icon
3. Profile avatar
4. WS avatar
5. Add a payment method

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f2af5b89-804f-4800-9e49-1a63912fc449

![Bug6111866_image__121_](https://github.com/Expensify/App/assets/78819774/1d17f9e8-feb6-40d3-99ef-f83e0a7196e5)

![Bug6111866_image__124_](https://github.com/Expensify/App/assets/78819774/7b2a4c42-1e85-4450-8553-6cc40e55b2e4)

![Bug6111866_image__122_](https://github.com/Expensify/App/assets/78819774/fea31174-fead-41e8-a6a3-c659c940cae4)

![Bug6111866_image__123_](https://github.com/Expensify/App/assets/78819774/125b3594-8573-423d-8afa-64cb1f38b919)

![Bug6111866_image__125_](https://github.com/Expensify/App/assets/78819774/f4b0b1c4-7c26-4fd7-b2f5-c59f2079f665)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-06-30 13:33
Regression of https://github.com/Expensify/App/issues/20516

**Comment by lanitochka17** [comment] 2023-06-30 13:45
Sorry, posted duplicate https://github.com/Expensify/App/issues/21944

**Comment by Julesssss** [comment] 2023-06-30 13:46
Thanks! Closing as dupe of #21944

**Closed by Julesssss** 2023-06-30 13:46 UTC
Labels: DeployBlockerCash, Engineering, Hourly
