### ISSUE TITLE
[$500] IOU - Blurry receipt in IOU preview when the receipt is a long PDF file

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38735] opened 2024-03-21 09:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Create a manual request from any user with a long PDF receipt (attached below).
3. Go to 1:1 DM, IOU report and transaction thread.

## Expected Result:
The receipt in IOU preview in 1:1 DM, IOU report and transaction thread will be clear.

## Actual Result:
The receipt in IOU preview in 1:1 DM, IOU report and transaction thread is blurry.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/944c479c-7649-40f8-b6a1-e9f3bfe46835

[Bug6421271_1710989341214!International_Money_Transfer__Send_Money_Abroad_with_Wise__ex-TransferWise_.pdf](https://github.com/Expensify/App/files/14692655/Bug6421271_1710989341214.International_Money_Transfer__Send_Money_Abroad_with_Wise__ex-TransferWise_.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100172d6c24a63b92</li>
        <li>Upwork Job ID: 1772223119970160640</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-21 09:37
We think this issue might be related to the #collect project.

**Comment by shahinyan11** [comment] 2024-03-21 22:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Blurry receipt in IOU preview when the receipt is a long PDF file
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/d7edf935e3726acb0f12cfa22d1aa725c0b99ec3/src/components/ReportActionItem/ReportActionItemImage.tsx#L90C7-L97C6)  we use the `PDFThumbnail` component to display the file only if it is a local file. Since in our case the files are not local and have a large height it is displayed blurry in `ThumbnailImage` component .
### What changes do you think we should make in order to solve the problem?
I suggest using the `PDFThumbnail` component to display the `PDF` even if it is not local.  To do that we can do below changes
1. Get `environmentURL` using `useEnvironment` hook in [ReportActionItemImage](https://github.com/Expensify/App/blob/d7edf935e3726acb0f12cfa22d1aa725c0b99ec3/src/components/ReportActionItem/ReportActionItemImage.tsx#L53C10-L53C31) component and update the definition of `attachmentModalSource` like below
```
const attachmentModalSource = useMemo(()=>{
    const url = tryResolveUrlFromApiRoot(image ?? '')
    return  isLocalFile ? url : environmentURL.concat(url)
}, [image, environmentURL]);
```
2. Move [this](https://github.com/Expensify/App/blob/d7edf935e3726acb0f12cfa22d1aa725c0b99ec3/src/components/ReportActionItem/ReportActionItemImage.tsx#L90C7-L97C6) `else if` block up a step and remove the check of `isLocalFile` from there
```
if (isEReceipt) {
        receiptImageComponent = (
            <View style={[styles.w100, styles.h100]}>
                <EReceiptThumbnail
                    transactionID={transaction.transactionID}
                    iconSize={isSingleImage ? 'medium' : 'small'}
                />
            </View>
        );
    } else if (filename && Str.isPDF(filename) && typeof attachmentModalSource === 'string') {
        receiptImageComponent = (
            <PDFThumbnail
                previewSourceURL={attachmentModalSource}
                isAuthTokenRequired={!isLocalFile}
                style={[styles.w100, styles.h100]}
            />
        );
    } else if (thumbnail && !isLocalFile) {
        receiptImageComponent = (
            <ThumbnailImage
                previewSourceURL={thumbnailSource}
                style={[styles.w100, styles.h100]}
                isAuthTokenRequired
                fallbackIcon={Expensicons.Receipt}
                fallbackIconSize={isSingleImage ? variables.iconSizeSuperLarge : variables.iconSizeExtraLarge}
                shouldDynamicallyResize={false}
            />
        );
    }  else {
        receiptImageComponent = (
            <Image
                source={imageSource}
                style={[styles.w100, styles.h100]}
            />
        );
    }
```

**I noticed that there is a problem with extra renders in [ReportActionItemImage](https://github.com/Expensify/App/blob/d7edf935e3726acb0f12cfa22d1aa725c0b99ec3/src/components/ReportActionItem/ReportActionItemImage.tsx#L53C10-L53C31). The [receiptImageComponent](https://github.com/Expensify/App/blob/d7edf935e3726acb0f12cfa22d1aa725c0b99ec3/src/components/ReportActionItem/ReportActionItemImage.tsx#L116C26-L116C47) is rendered many times due to bad implementation.**

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-03-25 16:54
@shahinyan11 Thanks for the proposal. Your RCA is correct. We want to render the image thumbnail returned by the server whenever possible for performance reasons (rendering an image is faster than rendering a pdf). This may need to be fixed internally cc @luacmartins -- Doing nothing may also be a valid option as I don't think a long pdf receipt is that common.

**Comment by luacmartins** [comment] 2024-03-25 18:55
I agree. I think the ROI here is really small, so I'd vote to :do-nothing:

**Comment by greg-schroeder** [comment] 2024-03-26 11:43
Sounds good, let's close for now

**Closed by greg-schroeder** 2024-03-26 11:43 UTC
Labels: External, Daily, Help Wanted, Bug
