### ISSUE TITLE
[$500] Chat - Not all messages arrive on receiver side

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35001] opened 2024-01-23 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/19723&group_by=cases:section_id&group_id=290914&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User A and User B have previous existing conversation
1. User A opens conversation with User B
2. User B opens conversation with User A
3. User A send few lines of text to User B

## Expected Result:
Receiver should see all messages from sender

## Actual Result:
Not all messages arrive on receiver side, only few lines of text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d7905ab3-45c9-443a-8e46-9e5d71cf266c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01357ad76b92d56372</li>
        <li>Upwork Job ID: 1749892077767520256</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-23 20:29
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by jeremy-croff** [comment] 2024-01-24 04:24
This is a dupe of:
https://github.com/Expensify/App/issues/34748

**Comment by akinwale** [comment] 2024-01-24 06:47
Agree with @jeremy-croff. We can close this one in favour of https://github.com/Expensify/App/issues/34748.

**Closed** 2024-01-24 19:57 UTC
Labels: External, Daily, Help Wanted, Bug
