### ISSUE TITLE
[hold for #20486] [$1000] Money Request - no tooltip shown for the "To" email address

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19341] opened 2023-05-20 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Request money from any user, which will create a new report for that request.
2. Hover over the "share code" option.
3. Open the new owes report.
4. Hover over the email written under "to".
5. The tooltip does not appear for that user

## Expected Result: 
The tooltip should appear for both users.

## Actual Result: 
The tooltip does not appear for the user whose email is written under "to".

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/aa7dcb66-a1ed-48aa-9445-e6a0f0d0006a

https://github.com/Expensify/App/assets/43996225/c7e1d0cc-6ccd-4027-a447-feac9b81d059

**Issue reported by:** @usmantariq96 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684346461913589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee8291cc04f7b5cf</li>
        <li>Upwork Job ID: 1660733874213466112</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-20 14:13
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
The tooltip is not appearing in the Money Request/Owes header for the user who owes money or whose email is written under "to".

### What is the root cause of that problem?
Money request header for payee is rending via text component as shown code block below:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/MoneyRequestHeader.js#L120-L125

There is not no tooltip used with this text component. So it will not show tooltip. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
To solve this we can wrap Text component with tooltip, but it will not work because text component is extend up to right end due to its parent component has flex1 set [here](https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/MoneyRequestHeader.js#L119).

So within `src/components/MoneyRequestHeader.js` we have to replace Text component (line. 120-125) with `DisplayNames` as shown in code below. It will provide tooltip. We are using `DisplayNames` for payer name also.

```javascript
<DisplayNames
    fullTitle={payeeName}
    displayNamesWithTooltips={[{displayName: payeeName, tooltip: moneyRequestReport.managerEmail}]}
    tooltipEnabled
    numberOfLines={1}
    textStyles={[styles.headerText, styles.pre]}
    shouldUseFullTitle={isExpenseReport}
/>
``` 

This will solve the isse and shows tooltip for payee header name as shown in result video.

### What alternative solutions did you explore? (Optional)
None.

<details>
<summary>Results</summary>

https://github.com/Expensify/App/assets/7823358/0298aa3a-8e13-43e9-af1b-fd0f1d6d6bb7

</details>

**Comment by isabelastisser** [comment] 2023-05-22 19:49
not overdue!

**Comment by isabelastisser** [comment] 2023-05-24 20:44
Hey @sobitneupane, it looks like we have enough proposals. Can you please review them? Thanks!

**Comment by sobitneupane** [comment] 2023-05-25 10:20
@isabelastisser Can you please clarify what is the expected behavior here?

As of now, only Display Name on the first row has tooltip. Do we want to add tooltip just to Display Name on the second row or to avatars as well? Unlike ChatHeaders in normal messages, header in money requestor page is not clickable.
 
https://github.com/Expensify/App/assets/25876548/91474c14-8170-4b47-ad8c-b3d0511fdbf8

**Comment by youssef-lr** [comment] 2023-05-29 20:14
@sobitneupane It seems like in chats we show the tooltip on both the avatar and the display name. Let's keep it consistent and do the same here.

**Comment by sobitneupane** [comment] 2023-05-31 07:22
[Proposal](https://github.com/Expensify/App/issues/19341#issuecomment-1555922209) from @allroundexperts to introduce tooltip on both the avatar and display name goods to me. Implementation details can be tweaked in PR if required.

🎀👀🎀 C+ reviewed
cc: @youssef-lr

**Comment by michaelhaxhiu** [comment] 2023-06-02 19:55
Is https://github.com/Expensify/App/issues/19774 a dupe? I feel like the same PR should address this all :think

**Comment by michaelhaxhiu** [comment] 2023-06-02 19:56
@allroundexperts @sobitneupane @youssef-lr what do you think?

**Comment by michaelhaxhiu** [comment] 2023-06-02 20:02
You mean "update the test steps" in this GH specifically?

**Comment by michaelhaxhiu** [comment] 2023-06-02 20:13
Understood! Done.

My recommendation for next steps:
- Keep this GH open and handle both bugs. They could be separate but it feels like high overlap like @allroundexperts mentioned :)
- Close the other GH https://github.com/Expensify/App/issues/19774
- Double bounty to $2000 (for added scope - it would've been 2 separate jobs worth this amount anyway)
- Pay 2 bug reporting bonuses here to each individual that reported (updated GH body to include that)

**Comment by michaelhaxhiu** [comment] 2023-06-02 20:32
Ok... I am realizing this was a mistake. These issues are slightly different and we need to figure out the desired behavior for the hover/interactiveness of Amount/Description/Date

I'm going to undo everything I just did 

![image](https://github.com/Expensify/App/assets/13206896/e9705d0e-2c81-4ebd-970f-bfd59812afef)

**Comment by youssef-lr** [comment] 2023-06-05 14:46
@isabelastisser sounds good to me!

**Comment by youssef-lr** [comment] 2023-06-05 15:06
@allroundexperts replied!

**Comment by isabelastisser** [comment] 2023-06-07 19:57
Summary:

A contributor is assigned, and PR is created!

I'm reassigning ([SO](https://stackoverflowteams.com/c/expensify/questions/8836)) because I will be OOO until June 14. Thanks! 

`Once I return from OOO if the chore is still outstanding, I will take over any remaining action items.

**Comment by youssef-lr** [comment] 2023-06-14 20:13
@allroundexperts replied in your PR.

**Comment by isabelastisser** [comment] 2023-06-15 16:55
Taking this back!

**Comment by isabelastisser** [comment] 2023-06-15 16:56
No updates, PR is not merged yet.

**Comment by isabelastisser** [comment] 2023-06-20 14:33
No updates, PR is not merged yet.

**Comment by isabelastisser** [comment] 2023-06-23 19:45
I will be OOO until July 5, so assigning another team member. [SO](https://stackoverflowteams.com/c/expensify/questions/883) for reference.

**Comment by joekaufmanexpensify** [comment] 2023-06-27 17:36
Looks like PR is pending review from @youssef-lr

**Comment by sobitneupane** [comment] 2023-06-28 10:23
@joekaufmanexpensify @youssef-lr  We are going to update the money request header in https://github.com/Expensify/App/issues/20486. I don't think this issue will be any longer valid with the new money request header.

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:33
Ah, interesting. Are you thinking we should just close this one then?

**Comment by sobitneupane** [comment] 2023-06-30 03:20
Yes, I think we can close this or hold this issue and recheck after https://github.com/Expensify/App/issues/20486 gets resolved.

**Comment by joekaufmanexpensify** [comment] 2023-06-30 17:25
Cool, yeah let's hold for that issue. Then, once it's done we can test and close if this is fixed!

**Comment by joekaufmanexpensify** [comment] 2023-06-30 17:26
Making this weekly since it's on hold!

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:31
On hold still.

**Comment by isabelastisser** [comment] 2023-07-05 20:33
I'm back. Thanks @joekaufmanexpensify !

**Comment by isabelastisser** [comment] 2023-08-02 14:04
This is on hold pending progress [here.](https://github.com/Expensify/App/issues/20486)

**Closed** 2023-09-29 10:56 UTC
Labels: Reviewing, External, Monthly, Bug
