### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] IOU - Unable to create IOU with "Hidden" users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31792] opened 2023-11-23 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create group conversation with users you have not existing conversation before
3. Click on "+" button from chat composer> Split Bill
4. Add amount and click Next button

## Expected Result:
User should be able to create Split bill with "Hidden" users, Split button should be active

## Actual Result:
User is not able to create IOU with "Hidden" users, Split button is grayed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ba6e62b9-6b3e-431d-a104-1d617c91a767

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1b3071c11ee0d1c</li>
        <li>Upwork Job ID: 1727789932415844352</li>
        <li>Last Price Increase: 2023-11-23</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27867123</li>
<li>dukenv0307 | Contributor | 27867124</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-11-23 20:27
Investigating. Might be intended.

**Comment by luacmartins** [comment] 2023-11-23 20:35
Ok, I don't think this is intended because we can still split bill with anon users from the global create

**Comment by luacmartins** [comment] 2023-11-23 20:39
This issue also happens in prod. Not a blocker. I think the PR that introduced the issue is https://github.com/Expensify/App/blob/8b5306468bc9660124bad97df6142f19354649f0/src/pages/iou/steps/MoneyRequestConfirmPage.js#L80 because we filter participants without a login [here](https://github.com/Expensify/App/blob/8b5306468bc9660124bad97df6142f19354649f0/src/pages/iou/steps/MoneyRequestConfirmPage.js#L80) so the participant list is empty

**Comment by luacmartins** [comment] 2023-11-23 20:40
https://github.com/Expensify/App/assets/22219519/c8f46c05-88b3-4592-961d-9660846d073f

**Comment by luacmartins** [comment] 2023-11-23 20:43
cc @lukemorawski  @puneetlath @allroundexperts

**Comment by DylanDylann** [comment] 2023-11-24 09:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to create IOU with "Hidden" users

### What is the root cause of that problem?
We don't allow users to create requests or split bills with hidden user. Note that, when clicking request money in FAB and going to the participant page, we also don't display hidden user in the suggestion list

### What changes do you think we should make in order to solve the problem?
I think in DM chat with hidden user or in group chat with hidden users, we should hide the request/send/split bill button when clicking + button. 
In here
https://github.com/Expensify/App/blob/a2fc32bbfb8d5917e83134568187529d488812e2/src/libs/ReportUtils.js#L3868-L3879

We should get the personal details of all otherParticipants and add conditions to make sure that we only show request/send/split bill button if personal detail of all otherParticipants include a login field (It mean that this user is not hidden user)
 
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-11-24 17:04
@dukenv0307 Thanks for the proposal. Your RCA is correct. The solution looks good to me. I don't see a reason to have that filter condition either but I have asked [here](https://github.com/Expensify/App/pull/27547#discussion_r1404542904) for confirmation.

**Comment by s77rt** [comment] 2023-11-24 17:09
@DylanDylann Thanks for the proposal. I think in the FAB flow those hidden users are not something that you'd be usually looking for thus not in the list (it's actually a feature since those users are hidden you should not be able to search for them). But for the DM I'd expect the functionality to work as I don't see a reason to disable it.

**Comment by s77rt** [comment] 2023-11-27 14:01
Not overdue. Still waiting for a clarification on https://github.com/Expensify/App/pull/27547#discussion_r1404542904

**Comment by s77rt** [comment] 2023-11-28 11:57
Got a clarification on the above ^ We can remove the filter as it was only done to avoid a bug that no longer exists.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/31792#issuecomment-1825109289)

**Comment by luacmartins** [comment] 2023-11-28 16:39
Proposal looks good. Let's get this fixed!

**Comment by s77rt** [comment] 2023-12-05 20:24
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/27547
- The offending PR has been commented on: https://github.com/Expensify/App/pull/27547#discussion_r1404542904
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Start a chat with a user you have not chatted with before
2. Verify the user's display name is "Hidden"
3. Start money request flow (press the + grey button)
4. Verify you were able to complete the money request

**Comment by zanyrenney** [comment] 2023-12-13 11:12
**payment summary**

no bug finder - applause
@s77rt requires payment [offer](https://www.upwork.com/nx/wm/offer/27867123) (Reviewer) - paid $500
@dukenv0307 requires payment [offer](https://www.upwork.com/nx/wm/offer/27867124) (Contributor) - paid $500

**Comment by zanyrenney** [comment] 2023-12-13 11:13
regression test can be worked on separately, all payments complete - closing!

**Closed by zanyrenney** 2023-12-13 11:13 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
