### ISSUE TITLE
Chat - The main compose box is missing when editing a message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12199] opened 2022-10-27 17:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and login
2. Go to any chat > Send a message
3. Edit the message

## Expected Result:
When editing a message, the main compose box must be present

## Actual Result:
The main compose box is missing when editing a message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.20-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs
** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/198352994-6dde6b7a-211c-4121-a1af-670a96b99a2b.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-10-27 17:05
Not a bug. It is intentional.

**Comment by zanyrenney** [comment] 2022-10-28 12:16
Closing! intentional design.

**Closed by zanyrenney** 2022-10-28 12:16 UTC
Labels: Daily, Bug
