### ISSUE TITLE
[HOLD for payment 2024-02-14] Settings - Unexpected Increase in Padding Between Tooltip and Icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35479] opened 2024-01-31 14:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Click on "Settings."
2, Hover over the back icon in the left corner and observe an unexpected increase in padding between the back tooltip and back icon

## Expected Result:
The padding between the back icon and the back tooltip should remain consistent

## Actual Result:
Unexpected increase in padding between the tooltip and back icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3c48e2a2-4d7a-4486-ab31-9d2622c6e0d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-31 14:20
We think that this bug might be related to #vip-vsp 
CC @quinthar

**Comment by esh-g** [comment] 2024-01-31 14:20
Regression from: https://github.com/Expensify/App/pull/35126
@dukenv0307

**Comment by dangrous** [comment] 2024-01-31 14:35
Yep! @esh-g has it right - I commented [here](https://github.com/Expensify/App/pull/35126#issuecomment-1919229339) and will look into it further shortly

**Comment by dangrous** [comment] 2024-01-31 20:44
I'm removing the blocker label here since it's a very minor issue; a fix is in progress but I don't think this needs to block anything.

**Comment by dangrous** [comment] 2024-02-01 16:09
@dukenv0307 do you mind commenting on this so I can assign you? @c3024 I already added you since I could for some reason. Thanks!

**Comment by dangrous** [comment] 2024-02-06 20:21
hi! no rush but would love a clarification on ^ - @dukenv0307 are you saying [here](https://github.com/Expensify/App/issues/35892#issuecomment-1930460836) that it's basically not this PR that caused the issue, but another PR combined with this one that unluckily got merged at the same time?

**Comment by dangrous** [comment] 2024-02-12 15:03
Just to bring the conversation back here, we determined no regression on this PR - just an interaction between two PRs that was not testable at the time

**Comment by c3024** [comment] 2024-02-14 15:04
This is a regression and needs no payment.

**Comment by strepanier03** [comment] 2024-02-14 19:46
Great, if no payment is needed then I'm going to close it out. Thanks everyone!

**Closed by strepanier03** 2024-02-14 19:46 UTC
Labels: Engineering, Daily, Awaiting Payment
