### ISSUE TITLE
[$1000]  Payments - "Add payment method" button is disabled when offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19835] opened 2023-05-30 17:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the testing app
2. Navigate to Settings > Payments
3. Disable the internet connection in the device
4. Observe "Add Payment Method" button

## Expected Result:
The user should be able to click on "Add payment method" while internet is disconnected

## Actual Result:
Button is disabled / user can't click on the button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/2be192f0026a33bbaaafc8e89980c4da18b403506f1da89c269ce989bd20599f
https://platform.applause.com/services/links/v1/external/37ff8f9ae325936f3aa9fa7816a5ddf9ba27a0bd461fe543ea6dec7df2584662

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c2ad97c509cc33c</li>
        <li>Upwork Job ID: 1665752705146265600</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-06-05 16:09
Reproducible 👍

**Comment by marcaaron** [comment] 2023-06-06 02:50
Not blocking. I don't have time for it. If someone feels passionately about it they can look into it.

**Comment by srikarparsi** [comment] 2023-06-08 06:18
@sonialiap I also don't feel like enabling the button while offline is that important especially since the entire page is getting updated with N7. If you agree, I think we can close out this issue as well.

**Comment by srikarparsi** [comment] 2023-06-13 20:12
Messaged @sonialiap, she will probably respond tomorrow as it was outside her working hours but I believe we will close out this issue.

**Comment by sonialiap** [comment] 2023-06-14 21:19
I agree, closing out 📕

**Closed by sonialiap** 2023-06-14 21:19 UTC
Labels: External, Daily, Help Wanted, Bug
