### ISSUE TITLE
[$1000] Inconsistency in dragging attachments into composer

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24376] opened 2023-08-10 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. drag and drop multiple attachments in to composer.
2. observe in the composer only one attachment is visible.
3. another attachment is not visible.

## Expected Result:
 if you are allowing multiple attachments we should send multiple attachments or else we should allow only one attachment at a time.

## Actual Result:
composer is allowing multiple attachments and showing only one attachment or sending only one attachment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.52-3
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/4d8e4ea2-7986-41c7-80d9-8d6fb46086d0

https://github.com/Expensify/App/assets/38435837/fdf97dc9-c285-445d-a368-b606aeb710b9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @immadisetty-jaya-surya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691132393227349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186c6898bf1b539df</li>
        <li>Upwork Job ID: 1691202938909872128</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-08-15 20:07
I just had a chat with @Julesssss and @luacmartins and it sounds like this behavior isn't a bug. The act of dragging/selecting multiple files and uploading them to the composer does not result in uploading multiple files. We currently only support uploading a single file at a time.

_That said_, I do agree that we should support multiple file uploads in a single drag since it would feature-match OldDot's upload limit of up to 10 files at a time. But I think that would make this more of an `Improvement` than a `Bug`.

**Comment by immadisetty-jaya-surya** [comment] 2023-08-15 20:27
@johncschuster I reported this as bug because I feel we're only allowing one file at a time.. but we're not showing it to the user anywhere or any alert is there so I reported this as a bug.

**Comment by situchan** [comment] 2023-08-21 12:46
> I do agree that we should support multiple file uploads in a single drag since it would feature-match OldDot's upload limit of up to 10 files at a time. But I think that would make this more of an `Improvement` than a `Bug`.

Since this is a new feature, I think we should discuss design first.
@johncschuster do we have design doc for multiple uploads support?

**Comment by johncschuster** [comment] 2023-08-25 21:48
Asking about how we should move forward in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1693000041523729)

**Comment by johncschuster** [comment] 2023-08-29 01:05
The discussion in Slack is ongoing. I'll be back with an update shortly.

**Comment by johncschuster** [comment] 2023-08-29 14:47
Ok, we've come to a consensus. The bug described here is not a bug – it's a behavior that has not yet been built into NewDot. Given that it hasn't been designed yet, I'm going to close this issue until we discuss how we want to treat the ability to upload multiple image attachments into the same chat message.

**Closed by johncschuster** 2023-08-29 14:47 UTC
Labels: External, Daily, Help Wanted, Bug
