### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$500] mWeb - Chat-Pasting text in compose box makes page moves up and down

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41137] opened 2024-04-27 13:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4519310
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Paste any text repeatedly and note the page

## Expected Result:
Pasting text in compose box must not make page moves up and down

## Actual Result:
Pasting text in compose box makes page moves up and down

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bda8c52a-79d2-4d7d-a06b-e5bf10cd4930

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160628a928782ce4e</li>
        <li>Upwork Job ID: 1785426352607657984</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102450889</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment] 2024-04-27 13:58
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-27 13:59
We think that this bug might be related to #vip-vsp

**Comment by abhigurjeet** [comment] 2024-05-03 19:32
What should be the ideal behaviour here?
The virtual keyboard should remain open or closed when pasting text?
@johncschuster

**Comment by johncschuster** [comment] 2024-05-07 22:00
@abhigurjeet 

> What should be the ideal behaviour here?
> The virtual keyboard should remain open or closed when pasting text?

I would expect the virtual keyboard to remain open when pasting text.

**Comment by johncschuster** [comment] 2024-05-10 20:59
[Pinging for one more retest](https://expensify.slack.com/archives/C9YU7BX5M/p1715374780679449)

**Comment by kavimuru** [comment] 2024-05-10 21:51
Issue is not reproducible 

https://github.com/Expensify/App/assets/43996225/476f3d1b-000f-4a76-b7b9-d216df734daf

**Comment by abhigurjeet** [comment] 2024-05-11 11:39
Issue is reproducible. https://github.com/Expensify/App/assets/38328775/c7f081cb-edba-4137-9581-78166529d4b9

**Comment by abhigurjeet** [comment] 2024-05-11 11:45
Issue is reproducible. 

https://github.com/Expensify/App/assets/38328775/177bdbea-756b-41b1-8d32-04754619c30d

The virtual keyboard closes for a second and then reopens, it should remain open when pasting text.

**Comment by johncschuster** [comment] 2024-05-11 15:02
I agree with @abhigurjeet. This looks like it's still happening.

**Comment by johncschuster** [comment] 2024-05-14 02:06
I'm going to raise the bounty to try to get more eyes on this.

**Comment by johncschuster** [comment] 2024-05-16 20:35
No proposals yet.

**Comment by johncschuster** [comment] 2024-05-16 20:39
[Bumped for proposals](https://expensify.slack.com/archives/C01GTK53T8Q/p1715891960126119?thread_ts=1715652408.535909&cid=C01GTK53T8Q)

**Comment by ikevin127** [comment] 2024-05-19 03:30
Seems to be caused by `RNMarkdownTextInput`, to confirm this I replaced Composer/index.tsx with `RNTextInput` as this is what we used to have [here](https://github.com/Expensify/App/blob/1.4.8-1/src/components/Composer/index.js) previously.

If we console.log `textInput.current?.isFocused()` within Composer/index.tsx, we an see that when we paste using the long-press > Paste popup, `isFocused` becomes false then true, which causes the keyboard to close / re-open -> causing layout to shift down / up.

I also looked into PR https://github.com/Expensify/App/pull/32971, but these changes don't seem to be the root cause as I tested them using `RNTextInput` and the issue was not present.

I was not able to pinpoint the root cause within `@expensify/react-native-live-markdown`, but everything points to it.

**Comment by abhigurjeet** [comment] 2024-05-19 19:08
I have analysed this issue, I invested a lot of time to resolve this issue but unfortunately couldn't find a solution.

So, here are my analysis:

<b>Root Cause:</b>
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/hooks/useHtmlPaste/index.ts#L49-L51

- This is the code which is causing the keyboard to close and open in a second when a plain text is pasted.
- The blur event causes the virtual keyboard to close automatically and the focus event causes the virtual keyboard to open automatically again and this code manually triggers these events.
(I have also pasted the code which states the reason for why this code was written).

<b>Things that I tried to resolve this issue</b>

- I have tried commenting out both the blur and the focus method, in the above code, but when I do this and copy paste text again, the keyboard closes. It doesn't open again, neither does it remain open, it simply closes.
- I have also tried commenting out the blur method, but that also closes the keyboard. Even thought the composer remains in focus mode, the keyboard closes.
(The above attempts raise a new problem which is the closing of keyboard on pasting plain text.)

<b>Few more analysis</b>
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Composer/index.tsx#L253
This is the composer component, I tried commenting this **useHtmlPaste** code which is called on every render and which handles the paste events for plain text and html. The keyboard still closes upon pasting plain text, this clearly suggests something else is triggering the keyboard to close.

Hopefully these analysis might help if someone is working on this issue and if anybody has some ideas that I can try, then let me know and I will propose a solution for this one.

**Comment by johncschuster** [comment] 2024-05-20 22:18
@dukenv0307 can you please review the comments above?

**Comment by johncschuster** [comment] 2024-05-23 22:27
@dukenv0307 can you take a look at the updated proposal above?

Also, just an FYI, I will be OOO starting tomorrow and will return on Tuesday.

**Comment by mountiny** [comment] 2024-05-24 13:59
Thanks, feel free to raise the PR

**Comment by mountiny** [comment] 2024-06-04 17:08
done

**Comment by BartoszGrajdek** [comment] 2024-06-05 09:33
[This PR](https://github.com/Expensify/react-native-live-markdown/pull/357) has introduced [a bug](https://github.com/Expensify/react-native-live-markdown/pull/341#issuecomment-2146805686) to the `react-native-live-markdown` lib on FF (but also on Chrome in specific cases). We're currently investigating if there's a way to fix it without reverting these changes.

**Comment by BartoszGrajdek** [comment] 2024-06-06 21:52
Hi,
It seems like this regression is a blocker for us, so we've decided to prioritize it. That being said I investigated and [this specific change](https://github.com/Expensify/react-native-live-markdown/pull/357/files#diff-ec487e4a4ccb9c4ffd7ead6ff0a585595aa8d9e9b7d5167d0a2444d70d2001e1R563) caused the regression. 

Looking at the discussion above it seems like there was [a bug](https://github.com/Expensify/App/issues/41137#issuecomment-2127866960) related to cursor positioning that you were fixing, but I can't reproduce it. @dominictb are you sure that this change is necessary and can you test it to make sure?

**Comment by BartoszGrajdek** [comment] 2024-06-07 06:26
I think that makes sense, please open a PR so we can test if that fixes the problem and doesn't introduce any additional bugs 🙌🏻

**Comment by Tony-MK** [comment] 2024-06-09 15:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Emoji gets inserted in front of entered text

### What is the root cause of that problem?

When getting the current position of the cursor it's using the start of the cursor instead of the end.

```
const selectionAfterTextChange = CursorUtils.getCurrentCursorPosition(divRef.current);
```
### What changes do you think we should make in order to solve the problem?


Let's change the code snippet like the one below to choose the end of the cursor.

```
const selectionAfterTextChange = CursorUtils.getCurrentCursorPosition(divRef.current).end;
```

**Comment by mountiny** [comment] 2024-06-09 19:45
The markdown change had to be reverted to get the deploy out

**Comment by BartoszGrajdek** [comment] 2024-06-10 20:42
Adding the update here as well:

> Alright so here's what we're going to do now: We'll revert [this PR](https://github.com/Expensify/react-native-live-markdown/pull/357) since [a fix](https://github.com/Expensify/react-native-live-markdown/pull/370) for the [regression](https://github.com/Expensify/App/issues/41137#issuecomment-2153464605) I've mentioned was reverted [here](https://github.com/Expensify/react-native-live-markdown/pull/377). You'll have to make 1 PR with all of these changes and we will do our best to help you along the way with the implementation since it looks like this is a tricky bug. Our goal is to keep `react-native-live-markdown` lib as bug-free as we can and that way we can properly test it to ensure nothing breaks. 🙌🏻

**Comment by johncschuster** [comment] 2024-06-12 14:05
Thanks for the comment, @dominictb! When I review the PR linked above (https://github.com/Expensify/App/pull/43255), I don't see your involvement. Can you link the PR you worked on?

**Comment by johncschuster** [comment] 2024-06-18 15:36
@dukenv0307 can you address the BZ Checklist above when you get a moment? Thank you!

**Comment by johncschuster** [comment] 2024-06-20 15:11
# Payment Summary:
Contributor+: @dukenv0307  - $500 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/102450889)
Contributor: @dominictb - $500 - paid via Manual request

**Closed** 2024-06-20 15:12 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by johncschuster** [comment] 2024-07-25 15:09
Sorry I missed your comment, @dominictb! Can you please apply to [this job](https://www.upwork.com/jobs/~010072fbf9691100c2) when you get moment?

**Comment by johncschuster** [comment] 2024-07-25 18:02
Payment has been issued!
