### ISSUE TITLE
[$500] Expense - Unable to save Merchant by hitting Enter in confirmation page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37294] opened 2024-02-27 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to FAB > Request money > Manual.
3. Enter amount and select participant.
4. Proceed to confirmation page.
5. Click Show more > Merchant.
6. Enter a merchant and hit Enter.

## Expected Result:
The Merchant will be saved when hitting Enter.

## Actual Result:
The Merchant is not saved when hitting Enter.
This issue also occurs with Description.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0710bb0c-bc4b-49e1-a066-6a878d2299df

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173bf7e04af9fbaa2</li>
        <li>Upwork Job ID: 1762479426479763456</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 14:08
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by Pujan92** [comment] 2024-02-27 14:40
Please link the offended PR as it is not reproducible on production.

**Comment by grgia** [comment] 2024-02-27 17:42
I don't think this needs to block deploy

**Comment by BhuvaneshPatil** [comment] 2024-02-27 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Unable to save Merchant by hitting Enter in confirmation page

### What is the root cause of that problem?
The pr is - https://github.com/Expensify/App/pull/31606
The root cause of problem is we have subscribed to enter shortcut on `BaseOptionsSelector`, that prevents the form from submitting, and that avoid bubbling of that event.

### What changes do you think we should make in order to solve the problem?
We shall unsubscribe to `Enter` shortcut key event.
When we go to different pages (ex - Description, Merchant)
To Do this, we need to make following changes - 
1. For use effect here - 
https://github.com/Expensify/App/blob/04644d80b375237a629ff5f875ce14752df1d71c/src/components/OptionsSelector/BaseOptionsSelector.js#L370-L377
we shall also check if `isFocused` (not from prop) is true. This means we are only subscribing if we are on the page that has `BaseOptionsSelector`, not the inside. Because then it will act as we press enter it's on the confirmation list.
<details> 

<summary> Changes </summary>

```js
useEffect(() => {
    // Unregister the shortcut before registering a new one to avoid lingering shortcut listener
    enterSubscription.current();
    if (!disableEnterShortCut && isFocused) {
        subscribeToEnterShortcut();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [disableEnterShortCut]);

```
</details>
2. While subscribing to events, we shall also check if the window is focused (the value we using `useIsFocused()`) for this use effect 

https://github.com/Expensify/App/blob/04644d80b375237a629ff5f875ce14752df1d71c/src/components/OptionsSelector/BaseOptionsSelector.js#L379-L387
<details> 

<summary> Changes </summary>

```js
useEffect(() => {
    if (isFocused) {
        subscribeToEnterShortcut();
        subscribeToCtrlEnterShortcut();
    } else {
        unSubscribeFromKeyboardShortcut();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [isFocused]);
```
</details>

3. We need to remove the subscriptions done by the hooks (spent alot of time in this )
https://github.com/Expensify/App/blob/069efefa7b550bb7b5325f108b96a52cc6a1e896/src/components/OptionsSelector/BaseOptionsSelector.js#L305-L309

result - 

https://github.com/Expensify/App/assets/27822551/6402e86c-3d69-407d-b9d3-c0c401cceecb


### What alternative solutions did you explore? (Optional)

**Comment by Piotrfj** [comment] 2024-02-29 13:00
Update: re-refactoring is ready to be tested, it fixes all the regression issues I was aware of. Please test it (especially the tags, because I could not yet replicate the scenario on my site).
The fix is based on the @roryabraham solution, so special thanks for him!
Link to PR: https://github.com/Expensify/App/pull/37494

**Comment by grgia** [comment] 2024-03-04 17:43
I take it we can close this one out @Pujan92 ?

**Comment by situchan** [comment] 2024-03-04 17:45
Offending PR was reverted - https://github.com/Expensify/App/pull/31606#issuecomment-1970096957
FIne to close

**Closed** 2024-03-05 01:17 UTC
Labels: External, Engineering, Daily, Help Wanted
