### ISSUE TITLE
[$125] Workspace switcher - Back button returns to Inbox when creating new workspace in Search page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47562] opened 2024-08-16 11:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search
3. Open workspace switcher
4. Click on the create workspace button
5. Click on the app back button

## Expected Result:
App will return to Search page with workspace switcher panel opened

## Actual Result:
App returns to Inbox page with workspace switcher panel opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8c7f7030-518a-4dd1-8390-f9cb94f5223c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ecb2af50a3c8e0d</li>
        <li>Upwork Job ID: 1825547542380258833</li>
        <li>Last Price Increase: 2024-09-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment] 2024-08-16 11:54
We think that this bug might be related to #vip-vsp

**Comment by cead22** [comment] 2024-08-19 14:55
> App returns to Inbox page with workspace switcher panel opened

I'm not sure this is the expected behavior, so we should confirm on slack. I think the right label to apply here would be DeployBlockerCash and not DeployBlocker

**Comment by cead22** [comment] 2024-08-19 14:56
I don't think this should block the App deploy either, cc @chiragsalian

**Comment by greg-schroeder** [comment] 2024-08-27 05:56
@parasharrajat checking on expected behavior here

**Comment by greg-schroeder** [comment] 2024-08-27 06:15
Go away Melvin

**Comment by greg-schroeder** [comment] 2024-08-27 16:33
Team agrees expected behavior should be to go back to the search page and not the inbox, but it's low priority

**Comment by tushar-a-b** [comment] 2024-08-27 16:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Back button returns to inbox when new workspace created in search page.

### What is the root cause of that problem?
We are using `Navigation.resetToHome()` when click on back button. So it goes to home every time when we click back button on component `WorkspaceInitialPage`. Refer below code: 
https://github.com/Expensify/App/blob/db1c4c2593109224a973d1111b150f0d99fe3613/src/pages/workspace/WorkspaceInitialPage.tsx#L425-L432

#### Explanation
Above code was written to fix issue #46816 by PR #46939. 
The main root cause for both the issues (i.e. #46816 and #47562) is we have incorrect `routes` state which causes the incorrect navigation.
When we initially click on `WorkspaceSwitcher` and click on create workspace from LHP `+` button, the below condition get  satisfied in `linkTo` function and we push the `diffActions` from `adaptedState` to current `routes` state in below code: 
https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/libs/Navigation/linkTo/index.ts#L138-L146 

which results in this `routes` state (refer below image): 
<img width="436" alt="Screenshot 2024-08-27 at 10 20 32 AM" src="https://github.com/user-attachments/assets/b79dfcc9-41f5-4347-b0fd-365cc0899924">

As we can notice there is an extra route that is `"Settings_Workspaces"` before `"FullScreenNavigator"` that is reason when we navigate back by closing the `FullScreenNavigator` modal i.e. `WorkspaceInitialPage` we end up in `SettingsWorkspaces` page (in #46816) instead we should land on the route that is above the `SettingsWorkspaces` page in this case the `Reports` page with the previous opened report as per correct `routes` state.

If we comment out the `Navigation.resetToHome()` in below code, we end up in `SettingsWorkspaces` page for current issue #47562 as well, hence root cause is same. (Extra route `"Settings_Workspaces"` in root `routes` state)
https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/pages/workspace/WorkspaceInitialPage.tsx#L425-L432

The extra route is getting pushed into the root `routes` state is because of we have `isCentralPaneAndBottomTabMandatory ` as `true` during the navigation action of `WorkspaceInitial` (when we click on create workpace from LHP) in case of `FULL_SCREEN_NAVIGATOR` action type in below code: 

We are initializing `isCentralPaneAndBottomTabMandatory` as `true`
https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L165-L168

and no change in `isCentralPaneAndBottomTabMandatory` in case of `FULL_SCREEN_NAVIGATOR` navigation actions here: 
https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L268-L294

So, we get `isCentralPaneAndBottomTabMandatory` as `true` and push the `CentralPane` and `BottomTab` routes below  here: 

https://github.com/Expensify/App/blob/80f7d1eb08680f1e4994b782d5fd002a99c34b49/src/libs/Navigation/AppNavigator/getPartialStateDiff.ts#L37-L61
https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/libs/Navigation/linkTo/index.ts#L139-L146




### What changes do you think we should make in order to solve the problem?


We should not let `dispatch` the `diffActions` for `CentralPane` and `BottomTab` for `FULL_SCREEN_NAVIGATOR`. To do so we should make `isCentralPaneAndBottomTabMandatory` as `false` while the action of `FULL_SCREEN_NAVIGATOR` by adding 
```
metainfo.isCentralPaneAndBottomTabMandatory = false;
``` 
after this line

https://github.com/Expensify/App/blob/9c0c647dacf736f62380207d8fe46e1f7b4ecc45/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L288

By doing this we will stop `dispatch` of `diffActions` in case of `FULL_SCREEN_NAVIGATOR` action and we will solve both the issues Workspace Switcher (refer to below video):

https://github.com/user-attachments/assets/2731f012-e331-40d0-939b-7b5884e73fdd

As we can notice we solve both the problems of incorrect navigation (from both the issues as mention above) when we create workspace from Workspace Switcher LHP but now, we have another issue that we can notice at the end of the video that when we open RHP it opens after navigating back to `WorkspaceList` page which is again causing due to same set of code where we are dispatching `diffActions` below but this time by `RIGHT_MODAL_NAVIGATOR`:

https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/libs/Navigation/linkTo/index.ts#L139-L146

https://github.com/Expensify/App/blob/9c0c647dacf736f62380207d8fe46e1f7b4ecc45/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L181-L214

We should also add this in above code to stop dispatching `diffActions`:
```
metainfo.isCentralPaneAndBottomTabMandatory = false;
``` 

Final Result (refer to below video):

https://github.com/user-attachments/assets/89239365-e8d2-482b-8000-5eff4d7f26e2

 

 




### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by greg-schroeder** [comment] 2024-09-06 22:55
Thanks @parasharrajat, let me know where you land

**Comment by greg-schroeder** [comment] 2024-09-09 06:30
Sounds good

**Comment by greg-schroeder** [comment] 2024-09-11 20:12
Rajat is still debugging

**Comment by greg-schroeder** [comment] 2024-09-16 10:04
Rajat will get to this during the week

**Comment by greg-schroeder** [comment] 2024-09-18 19:14
Bump @parasharrajat :)

**Comment by greg-schroeder** [comment] 2024-09-23 03:04
Bump @parasharrajat

**Comment by greg-schroeder** [comment] 2024-09-30 10:07
Still in proposal review

**Comment by greg-schroeder** [comment] 2024-10-01 01:45
#vip-vsb is now fully paused/closed, so I'm going to close this as it doesn't really fit in #newdot-quality or any other active project.

**Closed by greg-schroeder** 2024-10-01 01:45 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
