### ISSUE TITLE
[HOLD for payment 2024-11-18] [$500] Add Track expense follow up questions as rows in details view of a Tracked expense

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#51358] opened 2024-10-23 18:47 UTC
**Problem:** When a user Tracks an expense in NewDot, they are presented with four options at the end of the flow: send to someone, share with an accountant, categorize it, or do nothing for now. If a user decides to do nothing for now, they will never be able to send or share the expense in NewDot in the future if they change their mind because those options only appeared as a whisper message and will never reappear:
![CleanShot 2024-10-23 at 20 46 37@2x](https://github.com/user-attachments/assets/b4076f06-57a0-4b53-9899-c554752c4882)

The only way they can do this is to switch back to Classic or to delete the expense and start over. This is bad because our core business strategy relies on users being able to easily send expenses to anyone to increase the viral nature of the product.

**Solution:** Add the track expense options into the details view of a tracked expense. We currently use the details view of an expense to surface other actions like Delete or Download, so this is a natural place to include the other missing track options. This will then allow users to go back to their tracked expenses and easily send them or share them when they wish.

![image](https://github.com/user-attachments/assets/01b3b245-7241-4fb1-9fa8-4e6dec405b09)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849411242829996514</li>
        <li>Upwork Job ID: 1849411242829996514</li>
        <li>Last Price Increase: 2024-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 104698287</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by shawnborton** [comment] 2024-10-23 18:49
cc @anmurali

**Comment by shahinyan11** [comment] 2024-10-23 20:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add Track expense follow up questions as rows in details view of a Tracked expense
### What is the root cause of that problem?
New feature 
### What changes do you think we should make in order to solve the problem?
1. Add below keys in [REPORT_DETAILS_MENU_ITEM](https://github.com/Expensify/App/blob/ba2922421acc4921c184455c2dd2dcfa314288ee/src/CONST.ts#L2953)
```
REPORT_DETAILS_MENU_ITEM: {
    ....
    
    SUBMIT_TO_SOMEONE: 'submitToSomeone',
    CATEGORIZE_IT: 'categorizeIt',
    SHARE_WITH_ACCOUNTANT: 'shareWithAccountant',
    NOTHING_FOR_NOW: 'nothingForNow',
}
```
2. Add bellow code [here](https://github.com/Expensify/App/blob/ba2922421acc4921c184455c2dd2dcfa314288ee/src/pages/ReportDetailsPage.tsx#L481)
```
if( isTrackExpenseReport && parentReport && parentReportAction ){
    const transactionID = getTransactionID(report.reportID);

    items.push(
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.SUBMIT_TO_SOMEONE,
            translationKey: 'actionableMentionTrackExpense.submit',
            icon: Expensicons.Bug,
            action: () => ReportUtils.createDraftTransactionAndNavigateToParticipantSelector(transactionID ?? '0', parentReport.reportID, CONST.IOU.ACTION.SUBMIT, parentReportAction.reportActionID),
            isAnonymousAction: false,
         },
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.CATEGORIZE_IT,
            translationKey: 'actionableMentionTrackExpense.categorize',
            icon: Expensicons.Bug,
            action: () => ReportUtils.createDraftTransactionAndNavigateToParticipantSelector(transactionID ?? '0', parentReport.reportID, CONST.IOU.ACTION.CATEGORIZE, parentReportAction.reportActionID),
            isAnonymousAction: false,
        },
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.SHARE_WITH_ACCOUNTANT,
            translationKey: 'actionableMentionTrackExpense.share',
            icon: Expensicons.Bug,
            action: () => ReportUtils.createDraftTransactionAndNavigateToParticipantSelector(transactionID ?? '0', parentReport.reportID, CONST.IOU.ACTION.SHARE, parentReportAction.reportActionID),
            isAnonymousAction: false,
        },
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.NOTHING_FOR_NOW,
            translationKey: 'actionableMentionTrackExpense.nothing',
            icon: Expensicons.Bug,
            action: () => Report.dismissTrackExpenseActionableWhisper(parentReport.reportID, parentReportAction),
            isAnonymousAction: false,
        },
     );
}
```
We also need to update the `Expensicons.Bug` to the appropriate icons in above code.
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-23 20:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add Track expense follow up questions as rows in details view of a Tracked expense
### What is the root cause of that problem?
New feature 
### What changes do you think we should make in order to solve the problem?
1. Add below keys in [REPORT_DETAILS_MENU_ITEM](https://github.com/Expensify/App/blob/ba2922421acc4921c184455c2dd2dcfa314288ee/src/CONST.ts#L2953)
```
REPORT_DETAILS_MENU_ITEM: {
    ....
    
    SUBMIT_TO_SOMEONE: 'submitToSomeone',
    CATEGORIZE_IT: 'categorizeIt',
    SHARE_WITH_ACCOUNTANT: 'shareWithAccountant',
    NOTHING_FOR_NOW: 'nothingForNow',
}
```
2. Add bellow code [here](https://github.com/Expensify/App/blob/ba2922421acc4921c184455c2dd2dcfa314288ee/src/pages/ReportDetailsPage.tsx#L481)
```
if( isTrackExpenseReport && parentReport && parentReportAction ){
    const transactionID = getTransactionID(report.reportID);

    items.push(
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.SUBMIT_TO_SOMEONE,
            translationKey: 'actionableMentionTrackExpense.submit',
            icon: Expensicons.Bug,
            action: () => ReportUtils.createDraftTransactionAndNavigateToParticipantSelector(transactionID ?? '0', parentReport.reportID, CONST.IOU.ACTION.SUBMIT, parentReportAction.reportActionID),
            isAnonymousAction: false,
         },
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.CATEGORIZE_IT,
            translationKey: 'actionableMentionTrackExpense.categorize',
            icon: Expensicons.Bug,
            action: () => ReportUtils.createDraftTransactionAndNavigateToParticipantSelector(transactionID ?? '0', parentReport.reportID, CONST.IOU.ACTION.CATEGORIZE, parentReportAction.reportActionID),
            isAnonymousAction: false,
        },
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.SHARE_WITH_ACCOUNTANT,
            translationKey: 'actionableMentionTrackExpense.share',
            icon: Expensicons.Bug,
            action: () => ReportUtils.createDraftTransactionAndNavigateToParticipantSelector(transactionID ?? '0', parentReport.reportID, CONST.IOU.ACTION.SHARE, parentReportAction.reportActionID),
            isAnonymousAction: false,
        },
        {
            key: CONST.REPORT_DETAILS_MENU_ITEM.NOTHING_FOR_NOW,
            translationKey: 'actionableMentionTrackExpense.nothing',
            icon: Expensicons.Bug,
            action: () => Report.dismissTrackExpenseActionableWhisper(parentReport.reportID, parentReportAction),
            isAnonymousAction: false,
        },
     );
}
```
We also need to use corresponding icons instead "Expensicons.Bug" in above code
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-24 11:44
> @aimane-chnaif I would like to point out that I proposed the first solution [here](https://github.com/Expensify/App/issues/51358#issuecomment-2433320766), other contributors elaborated in detail based on my proposal , but the basic idea of other proposals is the same as my proposal🙏

@twilight2294 I disagree with you, it's not quite right, you just made a "quick offer" without all the necessary changes to be first, but we spent a little more time to provide detailed proposal with all necessary changes

**Comment by shahinyan11** [comment] 2024-10-29 03:14
> @shahinyan11 can you please elaborate additional changes what @twilight2294 missed?

Yes.Here are differences
1. The first step in my proposal. @twilight2294's proposal use the same key for all items
2. Parametrs passed to function`ReportUtils.createDraftTransactionAndNavigateToParticipantSelector`. The @twilight2294's proposal does not specify where did the values ​​`transactionID`, `reportID` and `action` come from ? The code was just copy pasted and not

**Conclusion:** The code in @twilight2294's proposal was just copy pasted and there is not made changes to adjust it to use in new component

**Comment by shahinyan11** [comment] 2024-10-29 03:22
@aimane-chnaif You can just test @twilight2294's proposal and see that it doesn't work because the changes provided aren't enough.

**Comment by shahinyan11** [comment] 2024-10-29 06:39
@twilight2294 From where and how to get `transactionID` and `reportID`, was this information mentioned in your proposal? because there are different entities `report` and `parenrReport`. You also used `action.reportActionID` in your proposal. Did you mention how the `action` should be obtained?

All these should be mentioned in the proposal because they are important and can be implemented in different ways. Don't you agree with me @aimane-chnaif ?

**Comment by shahinyan11** [comment] 2024-10-30 07:02
## Proposal
[Updated](https://github.com/Expensify/App/issues/51358#issuecomment-2433413947). Delete  extra point

**Comment by shahinyan11** [comment] 2024-10-30 07:24
PR will be ready today

**Comment by shahinyan11** [comment] 2024-11-01 18:08
@aimane-chnaif @thienlnam Sorry, but I'm surprised by your decision. I think it's not fair.

**Comment by shawnborton** [comment] 2024-11-07 08:00
What's the latest on this one? We'd like to get this one implemented soon.

**Comment by shawnborton** [comment] 2024-11-07 08:20
Hi @NJ-2020 - I am not involved in evaluating or awarding proposals, I will leave that discussion up to @JmillsExpensify @thienlnam @aimane-chnaif

**Comment by JmillsExpensify** [comment] 2024-11-19 12:40
@twilight2294 I sent you an offer via Upwork.

**Comment by JmillsExpensify** [comment] 2024-11-19 13:47
All paid out! Waiting on the BZ checklist and then we can issue the last payment and close this out.

**Comment by anmurali** [comment] 2024-11-24 10:06
@twilight2294 @aimane-chnaif - can we please add detailed regression test plan?

**Comment by JmillsExpensify** [comment] 2024-11-25 13:40
Still waiting on BZ checklist to be complete.

**Comment by JmillsExpensify** [comment] 2024-11-27 10:31
Same as above.

**Comment by JmillsExpensify** [comment] 2024-12-04 09:40
Still waiting on the BZ checklist, specifically the regression test.

**Comment by JmillsExpensify** [comment] 2024-12-11 08:46
Still waiting on the BZ checklist. cc @aimane-chnaif

**Comment by JmillsExpensify** [comment] 2024-12-18 11:28
@aimane-chnaif I'm going to close this one. Please reach out to me via Slack when you have the BZ checklist ready. Thank you!

**Closed by JmillsExpensify** 2024-12-18 11:28 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug, High Priority
