### ISSUE TITLE
[hold for  #21706] [$1000] user avatar still display in search after user is added to my contacts, and profile image not display.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22614] opened 2023-07-11 03:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with user A and change profile image.
2. Login with user B and search for user A and start chat with him.
3. From user B search again for user A.
## Expected Result:
 User A profile image should be displayed for User B in search after starting chat between them.
## Actual Result: 
User A profile image not displayed for User B in search  after starting chat between them, and instead normal avatar is display.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-07-10 at 9 54 39 PM](https://github.com/Expensify/App/assets/43996225/4885a6e9-463c-448d-85d6-da6adb2582b2)

https://github.com/Expensify/App/assets/43996225/6df8c74a-c350-4f69-8919-c425fa336d44

https://github.com/Expensify/App/assets/43996225/8d47a587-ec0f-48da-9c51-510b6a768101

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689031004312789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175e9842c0e226b98</li>
        <li>Upwork Job ID: 1679235559358210048</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-07-11 18:44
I'm unable to reproduce this on my end. 


https://github.com/Expensify/App/assets/54866469/27142096-1124-4158-8dbd-0ba2637832f9

**Comment by joekaufmanexpensify** [comment] 2023-07-11 18:44
Discussing next steps in the slack thread!

**Comment by joekaufmanexpensify** [comment] 2023-07-12 19:47
Asked for [a secondary triager](https://expensify.slack.com/archives/C01SKUP7QR0/p1689191230487459) to see if someone else can reproduce.

**Comment by joekaufmanexpensify** [comment] 2023-07-12 20:52
@slafortune was able to reproduce this in the above thread!

**Comment by joekaufmanexpensify** [comment] 2023-07-12 21:05
Part of me wonders whether this would be considered a "dynamic updating" issue (which per [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1689009972403289?thread_ts=1688646398.596839&cid=C01GTK53T8Q), we are no longer treating as bugs). I'm not sure though, so going to proceed for now, and if we determine this issue falls into that category, we can always close it then.

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:13
Proposals pending review.

**Comment by multijump** [comment] 2023-07-14 07:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
user avatar still display in search after user is added to my contacts, and profile image not display

### What is the root cause of that problem?
The RC is the BE didn't return full account info in openReport api for no messaging report.
BE didn't return full account info so FE put the fake account info to optimisticData.
This caused the lack of user info and implements of too many redundant logics and code in FE.

### What changes do you think we should make in order to solve the problem?

1. BE should return full of account info in openReport api call
2. FE can remove redundant optmisticData from Onyx subscription.

### What alternative solutions did you explore? (Optional)
N/A

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by joekaufmanexpensify** [comment] 2023-07-14 18:52
@0xmiroslav Could you review the proposals here when you have a chance? Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-17 12:41
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:17
I think we're pending input from @Beamanator here on [the above question](https://github.com/Expensify/App/issues/22614#issuecomment-1638421439).

**Comment by Beamanator** [comment] 2023-07-19 10:43
Oof sorry for the delay

**Comment by Beamanator** [comment] 2023-07-19 10:44
> @Beamanator I'd like to confirm the expected behavior here.
If users haven't interacted each other yet (no login) after creating DM, should they appear in search list or not?

No they should not appear in the search list if they don't have a `login` because this indicates they're not "known" to you, so it should be slightly harder to start a new chat with them (though obviously the original user can re-type the email but only if they _know_ it already)

**Comment by joekaufmanexpensify** [comment] 2023-07-20 18:19
@0xmiroslav Now that the above question was confirmed, are we able to proceed for this one?

**Comment by joekaufmanexpensify** [comment] 2023-07-21 13:11
@0xmiroslav Ah, interesting. So put this on hold until the above issue is fixed. And then just validate then that that issue fixed this bug too?

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:40
On hold

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:31
Same

**Comment by joekaufmanexpensify** [comment] 2023-08-14 13:18
Same

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:31
PR this is held on just got merged last week. So we should be able to test this soon!

**Comment by joekaufmanexpensify** [comment] 2023-08-28 13:44
PR is out on prod, all set to test whether this is fixed today!

**Comment by joekaufmanexpensify** [comment] 2023-08-28 14:06
Tested and this was fixed by the above issue. Closing as this is all set!

**Closed by joekaufmanexpensify** 2023-08-28 14:06 UTC
Labels: External, Weekly, Help Wanted, Bug
