### ISSUE TITLE
[$250] Workspace - "Remove members" and "Make admin" options are present for owner

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46620] opened 2024-07-31 22:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/45732
**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** unable to check new feature
**Issue reported by:** applause internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Members.
3. Long press on the owner.
4. Tap Select.
5. Tap on the dropdown.

## Expected Result:
Owner should not be able to be selected (production behavior).

## Actual Result:
Owner can be selected and there are "Remove members" and "Make members" options which are not applicable to the owner.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110a7f901ae8b6a28</li>
        <li>Upwork Job ID: 1818787780851878074</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 103438189</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by m-natarajan** [comment] 2024-07-31 22:43
We think that this bug might be related to #wave-collect - Release 1

**Comment by neonbhai** [comment] 2024-07-31 23:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We allow the select modal to be present for options which have selection disabled. 

### What changes do you think we should make in order to solve the problem?
We should use the `isCheckBoxDisabled` property here when checking selection mode should be triggered:


https://github.com/Expensify/App/blob/c46990ba7e8e7cf21da72bce5ade7472f7cf7019/src/components/SelectionListWithModal/index.tsx#L44-L45

```jsx
if (!turnOnSelectionModeOnLongPress || !isSmallScreenWidth || item?.isCheckBoxDisabled) {
	return;
}
```

**Comment by Tony-MK** [comment] 2024-08-01 15:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - "Remove members" and "Make admin" options are present for owner

### What is the root cause of that problem?

The problem is that the `WorkspaceMembersPage` does not disabled the policy owner option.

Hence, the policy owner option can always be selected and the "Remove members" and "Make admin" options are present for the owner.

https://github.com/Expensify/App/blob/ec38b0508184b9ef00c368c7c5f7e583edfb0bef/src/pages/workspace/WorkspaceMembersPage.tsx#L348-L350

### What changes do you think we should make in order to solve the problem?


We should disable the owner option being able to be selected by adding the following condition, `accountID === policy?.ownerAccountID`,  to check if the account owns the policy for `isDisabled`.

The full condition will look like this.

```
isDisabled:
    accountID === policy?.ownerAccountID
    !!details.isOptimisticPersonalDetail || 
    (isPolicyAdmin && (policyEmployee.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || !isEmptyObject(policyEmployee.errors))), 
....
```

**Comment by getusha** [comment] 2024-08-06 13:39
@neonbhai why do we need `item?.isDisabled` in the condition?

**Comment by neonbhai** [comment] 2024-08-06 13:54
ah I meant to write `isDisabledCheckbox`. Solution stays same!

**Comment by getusha** [comment] 2024-08-06 13:58
>@getusha Can you re-check the https://github.com/Expensify/App/issues/46620#issuecomment-2261675223, it does not work. We don't have isCheckBoxDisabled

Yes, i figured it could be a typio

**Comment by neonbhai** [comment] 2024-08-06 15:10
I think we should go for the proposals which proposes the idea first. This is noted in https://github.com/Expensify/App/issues/28535 and https://github.com/Expensify/App/issues/27592#issuecomment-1722295827

**Comment by cead22** [comment] 2024-08-07 16:09
I agree with @getusha and @neonbhai on this one. I think it's hard to argue that `isCheckBoxDisabled` was referring something other than `isDisabledCheckbox`

Before moving forward with the proposal, what are the use cases for which we should have `item.isDisabled` with a value different than `item.isDisabledCheckbox`?

**Comment by neonbhai** [comment] 2024-08-07 17:32
> what are the use cases for which we should have item.isDisabled with a value different than item.isDisabledCheckbox

we could have this situation if a user was invited to a workspace offline, or if a member is pending delete [ref: [here](https://github.com/Expensify/App/blob/2336ba827e9752d951a322db3a0c61ee40849d8e/src/pages/workspace/WorkspaceMembersPage.tsx#L347-L350)]. But for disabled items, all presses are disabled on the Pressable in `BaseListItem` here: https://github.com/Expensify/App/blob/2336ba827e9752d951a322db3a0c61ee40849d8e/src/components/SelectionList/BaseListItem.tsx#L88 so a check for `item.isDisabled` is not needed here. We could still add this as a sanity check.

cc: @cead22

**Comment by neonbhai** [comment] 2024-08-09 03:37
Raising PR soon!

**Comment by bfitzexpensify** [comment] 2024-08-13 13:34
How is this one going @neonbhai?

**Comment by getusha** [comment] 2024-09-10 09:22
Seems like automation failed on this one. @cead22 could you please check? thanks!

**Comment by cead22** [comment] 2024-09-11 15:59
@bfitzexpensify can you handle payment for this issue please? Automation failed here, but I think @neonbhai should be paid via https://www.upwork.com/jobs/~0110a7f901ae8b6a28, and I'm not sure about @getusha after a brief look at the code

Below is the bug zero checklist for reference, in case we need to complete it. Let me know if I tagged the wrong people on some of the items.

Thanks


**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@neonbhai] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@neonbhai] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@neonbhai] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@neonbhai] Determine if we should create a regression test for this bug.
- [ ] [@neonbhai] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by cead22** [comment] 2024-09-23 10:30
Bump @neonbhai @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2024-09-24 08:33
Back from OOO, handling this now

Payment summary: 

@neonbhai to be paid $250 for contributor work - offer sent via Upwork
@getusha to be paid $250 for C+ work - via manual request

@getusha can you complete the checklist in https://github.com/Expensify/App/issues/46620#issuecomment-2344066942? Thanks!

**Comment by getusha** [comment] 2024-09-29 20:08
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/46096
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/46096#issuecomment-2381584927
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
 [@getusha] Determine if we should create a regression test for this bug. **No. IMO it's not related to an important flow and isn't impactful**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by bfitzexpensify** [comment] 2024-09-30 08:37
Thanks! Let's close this out

**Closed by bfitzexpensify** 2024-09-30 08:37 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-02 15:07
$250 approved for @getusha
