### ISSUE TITLE
[$250] [HOLD for payment 2024-03-29] Newly added tag is not arranged in alphabetical order

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38261] opened 2024-03-13 23:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Settings > Workspaces > Collect workspace.
3. Go to Tags.
4. Click Add tag.
5. Add a tag.

## Expected Result:
The new tag will be arranged in alphabetical order.

## Actual Result:
The new tag is not arranged in alphabetical order. It only follows the order after refreshing the page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b524be86-1f7c-43c1-ab1a-d42fcbff6218

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01820a70bf08232dfa</li>
        <li>Upwork Job ID: 1778526852557000704</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by m-natarajan** [comment] 2024-03-13 23:33
@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-03-13 23:36
We think that this bug might be related to #wave-control
cc @JmillsExpensify

**Comment by marcaaron** [comment] 2024-03-13 23:40
>@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

It's a deploy blocker so it should really be fixed by whoever broke this.

**Comment by marcaaron** [comment] 2024-03-13 23:40
Seems related to https://github.com/Expensify/App/pull/37870 cc @luacmartins

**Comment by luacmartins** [comment] 2024-03-14 01:34
I can take this over! Thanks for the ping!

**Comment by nkdengineer** [comment] 2024-03-14 05:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Newly added tag is not arranged in alphabetical order
### What is the root cause of that problem?
- After creating tag, we just add a new tag to the policyTags without sorting alphabeta order. Refreshing the page will display data correctly because BE returns the correct tags's order
### What changes do you think we should make in order to solve the problem?
- We need to create a sort function in FE side to sync with FE side, then use it to update the optimistic data when craeting a new tag
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mountiny** [comment] 2024-03-14 14:19
I think this does not have to be a blocker

**Comment by luacmartins** [comment] 2024-03-14 15:11
This is not a blocker since the feature is still WIP. PR to fix it [here](https://github.com/Expensify/App/pull/38317)

**Comment by luacmartins** [comment] 2024-04-01 16:36
Just pending payment

**Comment by luacmartins** [comment] 2024-04-15 16:19
still pending payment

**Comment by luacmartins** [comment] 2024-04-17 20:24
Just pending payment

**Comment by luacmartins** [comment] 2024-04-23 00:06
Bump for payment @kevinksullivan

**Comment by luacmartins** [comment] 2024-04-25 19:46
Bump for payment @kevinksullivan

**Comment by luacmartins** [comment] 2024-04-30 14:24
Bump @kevinksullivan for payment

**Comment by kevinksullivan** [comment] 2024-04-30 21:00
Same as other issue, waiting for @situchan to accept.

<img width="1295" alt="image" src="https://github.com/Expensify/App/assets/22508290/a25c454e-4560-46f6-b0e0-9c6c35bf3049">

**Comment by kevinksullivan** [comment] 2024-05-09 21:15
Still waiting on @situchan

**Comment by situchan** [comment] 2024-05-20 07:38
@kevinksullivan sorry I am back from vacay. Can you please send new offer? Old one was expired.

**Comment by kevinksullivan** [comment] 2024-05-20 23:48
All good!

**Comment by kevinksullivan** [comment] 2024-05-20 23:50
@situchan fresh offer here

https://www.upwork.com/jobs/~01820a70bf08232dfa

**Comment by kevinksullivan** [comment] 2024-05-21 21:55
all set

**Closed by kevinksullivan** 2024-05-21 21:55 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment, Bug

**Comment by situchan** [comment] 2024-05-22 05:25
![image](https://github.com/Expensify/App/assets/108292595/6e770639-148f-42dd-89d9-0889dbeaef2f)

@kevinksullivan this was created before Apr 4
