### ISSUE TITLE
[Waiting for C+ payment] [$500]  Android - Wrong location briefly shows before San Francisco when first open Distance request page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27087] opened 2023-09-09 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Request money
2. Click Distance tab
3. Observe map view

## Expected Result:
Shows San Francisco as default location

## Actual Result:
Weird location briefly shows before directing to San Francisco

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7e7dab44-0f52-43ca-a755-aa6666827a57

![Screenshot 2023-09-05 at 10 23 43 AM](https://github.com/Expensify/App/assets/93399543/ce0c39f3-b72c-4add-b6c5-c39f853586bd)

![Screenshot 2023-09-05 at 10 14 50 AM](https://github.com/Expensify/App/assets/93399543/4251e511-6c45-47db-ab60-c5b4bb2941b3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693888204337759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106c2a9461a735378</li>
        <li>Upwork Job ID: 1710683488590667776</li>
        <li>Last Price Increase: 2023-10-07</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-09 17:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong location briefly shown on the map before the default initial location, San Francisco the first time the Distance request page is open.

### What is the root cause of that problem?
This seems to be an issue specific to how the default location is set with the Mapbox SDK on Android. It is easily reproducible after launching the app for the first time. It seems when the camera (used for displaying the map viewport) is initialised for the first time, it has to move the camera center to the new location from Atlantic City (the default center if none is set). On subsequent attempts to open the distance request screen, San Francisco remains the center, so the camera does not have to move.

### What changes do you think we should make in order to solve the problem?
There is a callback to set the map idle state, which indicates that the map is ready for interaction and updates. We can render an overlay in [DistanceRequest](https://github.com/Expensify/App/blob/main/src/components/DistanceRequest.js) before the first call to set the map idle state, and then hide the overlay when the `setMapIdle` handler is called. This overlay will hide the initial camera movement from Atlantic City to San Francisco, and then when the map is ready (idle), the overlay gets hidden.

This can be achieved with the following steps.

1. In [MapView.tsx](https://github.com/Expensify/App/blob/main/src/components/MapView/MapView.tsx), add an `onMapIdle` or `onMapReady` prop which will be a method. Add the prop type to [MapViewTypes.ts](https://github.com/Expensify/App/blob/main/src/components/MapView/MapViewTypes.ts): `onMapReady: () => void;`

2. Update the `setMapIdle` method.
```diff
const setMapIdle = (e: MapState) => {
    if (e.gestures.isGestureActive) return;
    setIsIdle(true);
+    if (onMapReady) {
+        onMapReady();
+    }
};
```

3. In DistanceRequest, add a state variable, `mapReady`.
```
const [mapReady, setMapReady] = useState(false);
```

4. Update the rendering block for the `MapView` component in DistanceRequest with the overlay, and implement the handler for the `onMapReady` prop.
```diff
{!isOffline && Boolean(mapboxAccessToken.token) ? (
+  <>
      <MapView
          ...
+          onMapReady={useCallback(() => {
+              if (!mapReady) {
+                  setMapReady(true);
+              }
+          }, [])}
      />
+      {!mapReady && <View style={styles.mapViewOverlay} />}
+  </>
)
```

5. Add overlay styles. These can be tweaked.
```
mapViewOverlay: {
    flex: 1,
    position: 'absolute',
    left: 0,
    top: 0,
    borderRadius: 16,
    width: '100%',
    height: '100%',
    backgroundColor: themeColors.cardBG,
    ...spacing.m4,
},
```

### What alternative solutions did you explore? (Optional)
I tried setting the `animationMode` for the camera to `none`, with the assumption that the camera's initial movement from Atlantic City to San Francisco was animated, but this did not have any effect.

**Comment by sonialiap** [comment] 2023-09-12 11:04
@mollfpr we have a couple proposals, what do you think?

**Comment by akinwale** [comment] 2023-09-12 14:57
> @akinwale @ZhenjaHorbach Why it's only happening on Android?
> > The main problem is the coordinate value, which can be undefined for a short time during initialization of the map.

This is not actually a fix for the issue. I tested this and it is still reproducible even after setting the coordinates directly in MapView.tsx.

> I have a hard time confirming the issue. Does anyone have a suggestion?

It seems that the Mapbox SDK for Android is not as performant as other platforms probably due to different device configurations in terms of processor speed and available memory.

I can easily reproduce the issue in the Android 11 emulator. In order to reproduce the behaviour reliably, close the app completely (also remove from recents), relaunch the app and then try to create a Distance request. You will notice the map moving from the initial location the first time the map loads. This only happens the first time. If you try to create another Distance request during the same app session, it will be centered on San Francisco already.

**Comment by akinwale** [comment] 2023-09-12 15:25
> > 
> 
> @akinwale can you record a video, please ? Because if we deleted the default coordinate values Then we will see the same location as in the bug description
> 
> Therefore, it is logical to overwrite this value with the one we need

[default-location-flash.webm](https://github.com/Expensify/App/assets/4160319/5c68177f-3b97-45e3-bef7-e2d758d7cd83)

You'll notice around the 0:31 / 0:32 mark that the default location (Atlantic City) flashes and renders for a bit before the map moves to the center coordinate (San Francisco).

**Comment by mollfpr** [comment] 2023-09-13 17:17
I'm okay with @akinwale proposal to cover the map component until it's ready (idle). I tried to find a similar issue on the upstream, but no one cares much about it, and it's tough to notice.

Also, this issue polishes the map render and does not block the user from using the distance request feature.

I would like to hear the opinion of the internal engineer. So I'm recommending to consider @akinwale [proposal](https://github.com/Expensify/App/issues/27087#issuecomment-1712564872).

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-09-27 06:37
Add a note for the speed bonus calculation.

The assignment is on 14th Sept GMT+7, and the PR merged on 15th Sept GMT+7.

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PRs. This is an improvement for the Request money distance feature.


> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1. On Android native, close the app and remove the app from the recent menu
2. Launch the app
3. Tap the global create menu, and select Request Money
4. Select the Distance tab if it is not already selected
5. Verify that the map displays San Francisco and there is no weird jumping after the blocking view overlay is automatically hidden
6. Select Start and Finish waypoints
7. Tap on Next and then select the target workspace
8. Verify that there is no weird jumping on the map on the confirmation screen after the blocking view overlay is automatically hidden. The map may zoom in on the route after the overlay is hidden, which is the expected behavior
9. 👍 or 👎

**Comment by kadiealexander** [comment] 2023-09-28 04:22
Payouts due:

Issue Reporter: $50 @situchan
Contributor: $500 @akinwale
Contributor+: $500 @mollfpr

Eligible for 50% #urgency bonus? Yes (PR was merged within 24 hours)

Upwork job is [here](https://www.upwork.com/jobs/~014793e3b4669749b9).

**Comment by kadiealexander** [comment] 2023-09-28 04:25
Upwork contracts sent to @situchan and @akinwale!

@mollfpr please let me know if you're paid via Upwork or Newdot

**Comment by akinwale** [comment] 2023-09-28 04:26
> Upwork contracts sent to @situchan and @akinwale!
> 
> @mollfpr please let me know if you're paid via Upwork or Newdot

Accepted. Thanks!

**Comment by mallenexpensify** [comment] 2023-09-29 11:49
@JmillsExpensify , can you confirm that @mollfpr is setup for payment via NewDot?  If so I'll drop a note in #bug-zero with an updated list of everyone

**Comment by kadiealexander** [comment] 2023-10-03 21:22
Not overdue. @mollfpr please let us know how you'd prefer to be paid.

**Comment by mollfpr** [comment] 2023-10-04 16:09
@kadiealexander I would love to get this pay in NewDot, but I am still waiting for the confirmation https://github.com/Expensify/App/issues/27087#issuecomment-1740761925.

**Comment by mallenexpensify** [comment] 2023-10-05 13:46
Confirming @mollfpr can be paid via NewDot. The [SO](https://stackoverflowteams.com/c/expensify/questions/16949/16950#16950) is updated and the [associated sheet](https://docs.google.com/spreadsheets/d/1WKnL5G5CPQH85byWLbZ28bN4wZbjmPsVOJcZWZnSxmM/edit?usp=sharing).

**Comment by mollfpr** [comment] 2023-10-05 14:08
@mallenexpensify I guess I can create the request in the NewDot now?

**Comment by mallenexpensify** [comment] 2023-10-05 23:51
Yes @mollfpr , please do, based on the instructions I sent you last week.  Thx

**Comment by JmillsExpensify** [comment] 2023-10-06 11:12
> @JmillsExpensify , can you confirm that @mollfpr is setup for payment via NewDot? If so I'll drop a note in #bug-zero with an updated list of everyone

Yes.

**Comment by JmillsExpensify** [comment] 2023-10-06 11:13
$750 payment approved for @mollfpr based on BZ summary.

**Closed** 2023-10-09 03:47 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
