### ISSUE TITLE
[$500] Dev: Web -  Input fields are not auto focused on "Cash" page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26380] opened 2023-08-31 10:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Request money
2. Click on scan and attach a receipt
3. Observe the input field "Name, email or phone number"
---------or---------
1. Click on FAB > Request money
2. Click on manual and insert an amount and click next
3. Observe the input field "Name, email or phone number"

## Expected Result:
The input field should be autofocused

## Actual Result:
Input field is not autofocused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.60.1
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/23a9e852-f03d-49fc-b576-8a230c621f25

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693469471814339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016379a4af8a665559</li>
        <li>Upwork Job ID: 1697717740300275712</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-08-31 10:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Web - Input fields are not auto focused on "Cash" page
### What is the root cause of that problem?
the focus is lost when transition end
### What changes do you think we should make in order to solve the problem?
we need to add `shouldDelayFocus` prop to `OptionsSelector` in MoneyRequestParticipantsSplitSelector and MoneyRequestParticipantsSelector

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-08-31 11:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
we try to focus the input before page transition has ended

### What changes do you think we should make in order to solve the problem?
Add `shouldDelayFocus` in `OptionsSelector` in `MoneyRequestParticipantsSelector`

There are other pages as well, where we use `OptionsSelector` component. It does not occur when we go to page via UI.
But it appears when we directly go there using url.
Examples - 
- `NewChatPage` - by url - `http://localhost:8082/new/chat`
- `SearchPage` - by url - `http://localhost:8082/search`
- `TaskShareDestinationSelectorModal` - by url - `http://localhost:8082/new/task/share-destination`

We can fix these pages in the same issue as well

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-09-01 21:06
I was able to reproduce this, leaving the page unfocused made the flow a bit confusing so I think this is worth fixing.

**Comment by gadhiyamanan** [comment] 2023-09-06 02:36
@rushatgabhane this is dupe of https://github.com/Expensify/App/issues/24314

**Comment by situchan** [comment] 2023-09-06 07:00
> Sure but we don't have any proposals on it, and it's double price 😅

Callstack member was already assigned there and raised [PR](https://github.com/Expensify/App/pull/25922)

**Comment by stephanieelliott** [comment] 2023-09-08 15:19
Should we wait for https://github.com/Expensify/App/pull/25922 to merge, then test again and revisit?

**Comment by stephanieelliott** [comment] 2023-09-11 23:06
Given that #25922 may fix this, putting on hold til that PR is merged.

**Comment by stephanieelliott** [comment] 2023-09-18 01:01
https://github.com/Expensify/App/issues/26380 was fixed. Hey @kbecciv can try retesting this on Dev please?

**Comment by kbecciv** [comment] 2023-09-18 01:26
Hey @stephanieelliott, I can only retest on staging and production.

**Comment by Nathan-Mulugeta** [comment] 2023-09-18 07:25
I just retested this on staging and the issue is no longer present.

**Comment by stephanieelliott** [comment] 2023-09-21 18:33
Thanks @Nathan-Mulugeta! Will go ahead and close this

**Closed by stephanieelliott** 2023-09-21 18:33 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
