### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250]  Inbox - The entire page blinks when clicking Inbox on Inbox page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43585] opened 2024-06-12 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. On Inbox page, click Inbox icon
3. Refresh the page
4. Click Inbox

## Expected Result:
The entire page will not blink

## Actual Result:
The entire page blinks
This issue is not reproduced on Search and Account settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/71c74f91-4f21-4c0d-96a2-25f2cbf1ab2f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f33295394aa2f176</li>
        <li>Upwork Job ID: 1801707280294774711</li>
        <li>Last Price Increase: 2024-06-21</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102890680</li>
<li>truph01 | Contributor | 102890682</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by truph01** [comment] 2024-06-15 00:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The entire page blinks
This issue is not reproduced on Search and Account settings page

### What is the root cause of that problem?
- When click on "Inbox" button, we call:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L73-L76

- In ```navigate``` function, this logic is called:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/linkTo/index.ts#L142-L146

- In expected, ```actionForBottomTabNavigator``` in above should be ```undefined```, so the function will do nothing if user has already been in the ```/home``` page, but in this case, ```actionForBottomTabNavigator``` in not ```undefined```.

- So let's take a look at the ```getActionForBottomTabNavigator``` to find the RCA.

- In ```getActionForBottomTabNavigator```, we already have logic to do nothing if the current bottom tab is the same as the one we want to navigate to:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/linkTo/getActionForBottomTabNavigator.ts#L31-L39

- In this case, the expected is that ```isNewPolicy: false``` but actually, it is ```true``` because ```isNewPolicy = bottomTabParams?.policyID !== payloadParams?.policyID``` with ```bottomTabParams?.policyID: undefined``` and ```payloadParams?.policyID: ''``` (we can console.log in this line to see these values).

### What changes do you think we should make in order to solve the problem?
- Base on the above, we can update this:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/linkTo/getActionForBottomTabNavigator.ts#L36C11-L36C79
to:
```
    const isNewPolicy = (!!bottomTabParams?.policyID || !!payloadParams?.policyID) &&  bottomTabParams?.policyID !== payloadParams?.policyID;
```

### What alternative solutions did you explore? (Optional)

- We can also disable or early return this function:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L73
if ```currentTabName === SCREENS.HOME```. Do the same with other button tabs.

**Comment by truph01** [comment] 2024-06-15 01:04
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.
The entire page blinks
This issue is not reproduced on Search and Account settings page

### What is the root cause of that problem?
- When click on "Inbox" button, we call:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L73-L76

- In ```navigate``` function, this logic is called:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/linkTo/index.ts#L142-L146

- In expected, ```actionForBottomTabNavigator``` in above should be ```undefined```, so the function will do nothing if user has already been in the ```/home``` page, but in this case, ```actionForBottomTabNavigator``` in not ```undefined```.

- So let's take a look at the ```getActionForBottomTabNavigator``` to find the RCA.

- In ```getActionForBottomTabNavigator```, we already have logic to do nothing if the current bottom tab is the same as the one we want to navigate to:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/linkTo/getActionForBottomTabNavigator.ts#L31-L39

- In this case, the expected is that ```isNewPolicy: false``` but actually, it is ```true``` because ```isNewPolicy = bottomTabParams?.policyID !== payloadParams?.policyID``` with ```bottomTabParams?.policyID: undefined``` and ```payloadParams?.policyID: ''``` (we can console.log in this line to see these values).

### What changes do you think we should make in order to solve the problem?
- Base on the above, we need to cover the case ```bottomTabParams?.policyID: undefined``` and ```payloadParams?.policyID: ''```. We can update this:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/linkTo/getActionForBottomTabNavigator.ts#L36
to:
```
    const isNewPolicy = (!!bottomTabParams?.policyID || !!payloadParams?.policyID) &&  bottomTabParams?.policyID !== payloadParams?.policyID;
```

### What alternative solutions did you explore? (Optional)

- We can also disable or early return this function:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L73
if ```currentTabName === SCREENS.HOME```. Do the same with other button tabs.

**Comment by alitoshmatov** [comment] 2024-06-18 11:43
@truph01 Thank you for your proposal, your RCA is correct and your solution does solve the problem. But this issue is also happening for search page, when you go to search page, refresh and then click on search page expenses list is refreshing and blinking. Ideally we should solve that too

**Comment by truph01** [comment] 2024-06-18 12:00
@alitoshmatov 

> this issue is also happening for search page

- It can be fixed with my alternative solution.

**Comment by alitoshmatov** [comment] 2024-06-18 12:06
@truph01 I didn't understand what you mean by that, I mean it is not search page has separate navigate [function](https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L103-L105) which is not related to home pages navigation function

**Comment by truph01** [comment] 2024-06-18 12:12
@alitoshmatov

- Currently, we have a logic to handle when user click on "Inbox"
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L82

- Also, the logic when user click on "Search":
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L103-L105

- So, my alternative solution is that, we will early return these ```onPress``` functions if ```currentTabName === SCREENS.HOME``` in case of "Inbox" button and ```currentTabName === SCREENS.SEARCH.BOTTOM_TAB || currentTabName === SCREENS.SEARCH.CENTRAL_PANE``` in case of "Search" button.

**Comment by alitoshmatov** [comment] 2024-06-19 10:08
@truph01 This solution does not work, navigation to home tab is completely not working, clicking on search tab is not going to the first menu item. This looks like a workaround for me

https://github.com/Expensify/App/assets/59907218/b19cdaa5-4ebb-446c-aba0-35be713d5602

**Comment by truph01** [comment] 2024-06-19 10:10
@alitoshmatov You mean my main solution or alternative solution?

**Comment by alitoshmatov** [comment] 2024-06-19 10:28
Your main solution solves the issue only for home tab

My latest response was for solution you provided [here](https://github.com/Expensify/App/issues/43585#issuecomment-2175951561)

**Comment by truph01** [comment] 2024-06-19 10:29
I implement this [solution](https://github.com/Expensify/App/issues/43585#issuecomment-2175951561) and it still works on my side:


https://github.com/Expensify/App/assets/170341821/870b0f7e-d126-46ca-8ca7-854538c6ddba

**Comment by truph01** [comment] 2024-06-19 10:40
@alitoshmatov Here is the detail code changes:
1. https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L73-L76
```
    const navigateToChats = useCallback(() => {
        if (currentTabName === SCREENS.HOME) {
            return;
        }
        const route = activeWorkspaceID ? (`/w/${activeWorkspaceID}/home` as Route) : ROUTES.HOME;
        Navigation.navigate(route);
    }, [activeWorkspaceID, currentTabName]);
```

2. https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.website.tsx#L103-L105
```
                    onPress={() => {
                        if (currentTabName === SCREENS.SEARCH.BOTTOM_TAB) {
                            return;
                        }
                        interceptAnonymousUser(() => Navigation.navigate(ROUTES.SEARCH.getRoute(CONST.TAB_SEARCH.ALL)));
                    }}
```
in the above ```if (currentTabName === SCREENS.SEARCH.BOTTOM_TAB) {``` condition, we can consider adding ```|| currentTabName === SCREENS.SEARCH.CENTRAL_PANE``` as well

**Comment by alitoshmatov** [comment] 2024-06-19 11:05
@truph01 search page is still blinking when pressed right after refreshing it. Adding `currentTabName === SCREENS.SEARCH.CENTRAL_PANE` additionally does prevent blinking but it also causes menu item not going back to the first one when search tab is pressed.

**Comment by truph01** [comment] 2024-06-19 11:36
@puneetlath When users are already on search page, the "Search" icon in bottom tab is highlighted and the focused option in the left-hand screen is something like "Shared" "Draft", or "Finished". Then user clicks on the "Search" icon in the bottom tab. Should the focused option in left-hand screen reset to the first option, "Expenses"?

**Comment by puneetlath** [comment] 2024-06-20 13:38
Hmm, good question. @luacmartins what do you think?

**Comment by luacmartins** [comment] 2024-06-20 19:47
I don't think we should reset the view in that case, they are already in the Search page so we should just return early instead of navigating again.

**Comment by puneetlath** [comment] 2024-06-24 20:08
@alitoshmatov any of the proposals catching your eye?

**Comment by puneetlath** [comment] 2024-06-25 16:49
@alitoshmatov bump

**Comment by alitoshmatov** [comment] 2024-06-25 18:24
Okay I think we can go with @truph01 's [proposal](https://github.com/Expensify/App/issues/43585#issuecomment-2178351978) where we prevent navigation when already in the same page based on conditions

C+ reviewed 🎀 👀 🎀

**Comment by truph01** [comment] 2024-06-27 12:10
@alitoshmatov [PR](https://github.com/Expensify/App/pull/44528) is ready

**Comment by puneetlath** [comment] 2024-07-16 20:10
@alitoshmatov friendly reminder about the checklist so we can pay tomorrow.

**Comment by puneetlath** [comment] 2024-07-17 14:58
@truph01 has been paid. Still waiting on the checklist for @alitoshmatov.

**Comment by puneetlath** [comment] 2024-07-17 16:02
All paid. Thanks everyone!

**Closed by puneetlath** 2024-07-17 16:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
