### ISSUE TITLE
[HOLD for payment 2024-04-03] HIGH: [Reliability] [$500] Unread fevicon does not show for new messages / unread messages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38256] opened 2024-03-13 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710193817230399
 
## Action Performed:
1. Sign in to a account as user A
2. Sign in to another account in another device as B
3. Send a message from B to A

## Expected Result:
Fevicon should display unread icon 

## Actual Result:
Does not show

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/738567c4-805b-4ed0-ae72-fd71f5e89f54

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011928bada81510714</li>
        <li>Upwork Job ID: 1768019508229373952</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-03-13 20:14
I'd like to review this as C+ since I have context while reviewing similar issues:
- https://github.com/Expensify/App/issues/31276
- https://github.com/Expensify/App/issues/32225

**Comment by askavyblr** [comment] 2024-03-14 03:13
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
  
Unread favicon does not show for new messages

**What is the root cause of that problem?**
 
We need to update unreadReports and sync 

**What changes do you think we should make in order to solve the problem?**

https://github.com/Expensify/App/blob/13f8bc010e824312707058eebc0fb5f43c2514dc/src/libs/UnreadIndicatorUpdater/index.ts#L42

**What alternative solutions did you explore? (Optional)**

N/A

**Comment by jeremy-croff** [comment] 2024-03-14 03:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The favicon for unread is missing! Great catch btw

### What is the root cause of that problem?
This is a regression from the typescript migration: https://github.com/Expensify/App/issues/25231
There is functional difference between this and javascript. Changing to the previous javascript file mitigates this issue.

I believe this is a case of "Side effect imports" to understand the issue in depth.
Typescript has to be [configured](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) in order to preserve unused side effects, but without that, it will clean it up unused imports as an optimization. This is different from JS.

### What changes do you think we should make in order to solve the problem?
I completely agree with the previous post that we should just import everything with `import './libs/UnreadIndicatorUpdater'` [here]( [App/src/Expensify.tsx] in order to execute all the side effects of that file.  I just felt obligated to mention the RCA, and link the regression. Additionally we can remove the lint exclusions `// eslint-disable-next-line @typescript-eslint/no-unused-vars` 


### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2024-03-14 16:23
> I'd like to review this as C+ since I have context while reviewing similar issues:
> 
> * [MEDIUM: [$500] Unread indicator is showing in the fevicon even though there is nothing in LHN #31276](https://github.com/Expensify/App/issues/31276)
> * [LOW: [$500] Unread notification in fevicon does not update when the user is in another tab #32225](https://github.com/Expensify/App/issues/32225)

@garrettmknight Please assign them as C+ here, I'll unassign myself here.

**Comment by situchan** [comment] 2024-03-14 16:30
Thanks

**Comment by situchan** [comment] 2024-03-14 18:26
Thanks for the proposals.

While @jeremy-croff's root cause is more accurate, I think it's not fair for @gijoe0295 to ignore their efforts to find offending PR and solution first. Pointing out the offending PR itself mostly covers the root cause.
That being said, I recommend to assign @gijoe0295.
Proposal: https://github.com/Expensify/App/issues/38256#issuecomment-1995605005

@jeremy-croff please feel free to comment with the reason if you disagree.
Assigned engineer will give the final call.
🎀 👀 🎀 C+ reviewed

**Comment by jeremy-croff** [comment] 2024-03-14 19:24
> Thanks for the proposals.
> 
> While @jeremy-croff's root cause is more accurate, I think it's not fair for @gijoe0295 to ignore their efforts to find offending PR and solution first. Pointing out the offending PR itself mostly covers the root cause. That being said, I recommend to assign @gijoe0295. Proposal: [#38256 (comment)](https://github.com/Expensify/App/issues/38256#issuecomment-1995605005)
> 
> @jeremy-croff please feel free to comment with the reason if you disagree. Assigned engineer will give the final call. 🎀 👀 🎀 C+ reviewed

I know this situation is a bit complicated because I also feel bad for suggesting the same solution. The only improvement I could find was to remove the unnecessary lint rule. 

However, based on your explanation, I would like to clarify a few things. Firstly, I was the one who identified the problematic PR and linked it to TypeScript migration, not @gijoe0295. Secondly, it appears that @gijoe0295 only edited the PR to indicate that the issue was caused by TypeScript migration after the fact."er I posted this root cause

**Comment by situchan** [comment] 2024-03-14 19:29
> However, based on your explanation, I would like to clarify a few things. Firstly, I was the one who identified the problematic PR and linked it to TypeScript migration, not @gijoe0295. Secondly, it appears that @gijoe0295 only edited the PR to indicate that the issue was caused by TypeScript migration after the fact."er I posted this root cause

As we know the offending line, the PR could have been identified in a few seconds using git bisect or git lens


<img width="675" alt="Screenshot 2024-03-15 at 1 29 09 AM" src="https://github.com/Expensify/App/assets/108292595/94ac7b4d-8027-442e-b650-da94c9ce4576">

**Comment by jeremy-croff** [comment] 2024-03-14 19:39
@situchan I see what you mean. 

His root cause states specifically it's a wrong import, and that's it.But that import hadn't changed in over a year and that is why I wanted to point out the real root cause. He then posted he posted 3 lines of code all with different git history. For example it could've been the default export that occured during writing of the unit test of https://github.com/Expensify/App/commit/8c3c4e24e55f52409a74c1b6bc9a51e60f0c67e9 also 2 months ago. since the import never changed right.

When I wrote my proposal I thought it would provide the actual clarity. As it brought in the specifics and the history the bug. Not leave you to assume based on your own usage of gitlens on 1 of the refererred lines of code.

But now I also see that @gijoe0295 edited his proposal to mention typescript, but I don't have the granular timestamp to know where it was me or him that posted it first. As both were 16 hours ago.
@gijoe0295 Maybe we found it at the same time, but the only reason I posted was because you missed this at first and I knew I could add value even if I don't actually do the work and you do 👍

**Comment by situchan** [comment] 2024-03-14 19:42
@gijoe0295 updated proposal 25min before @jeremy-croff's post

**Comment by jeremy-croff** [comment] 2024-03-14 19:47
@gijoe0295 I hope you understand where I came from, I drafted the proposal for far over 25 minutes so I was not trying to duplicate your proposal. I actually did not know you edited to add typescript before my post so my statement of me pointing it out first was genuine, but a misunderstanding.

Thanks for all the clarifications and @situchan there's no disagreement from me.

**Comment by garrettmknight** [comment] 2024-03-15 12:54
@deetergp good to assign @gijoe0295 then? Looks solid to me!

**Comment by deetergp** [comment] 2024-03-15 23:11
Yep, let's go with @gijoe0295 👍

**Comment by quinthar** [comment] 2024-03-16 23:47
@gijoe0295 Great!  Can you give an ETA for completion?

**Comment by jeremy-croff** [comment] 2024-03-17 00:59
> @gijoe0295 Great!  Can you give an ETA for completion?

It seems this is in the hands of the C+ @situchan as @gijoe0295 has a PR open with a completed checklist!

**Comment by quinthar** [comment] 2024-03-23 00:38
is this done? can we close it?  Why didn't it close automatically?

**Comment by situchan** [comment] 2024-03-23 00:42
[PR](https://github.com/Expensify/App/pull/38433) reached staging

**Comment by garrettmknight** [comment] 2024-04-05 18:24
All paid out.

@situchan can you post the bug zero checklist when you get a chance?

**Comment by deetergp** [comment] 2024-04-15 17:07
Bump @situchan

**Comment by deetergp** [comment] 2024-04-24 00:58
> @situchan can you post the bug zero checklist when you get a chance?  

Another friendly bump, @situchan

**Comment by garrettmknight** [comment] 2024-04-24 09:13
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@situchan] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@situchan] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@situchan] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@situchan] Determine if we should create a regression test for this bug.
- [ ]  [@situchan] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ]  [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by garrettmknight** [comment] 2024-05-03 14:55
@situchan bumpity bump

**Comment by deetergp** [comment] 2024-05-21 23:49
@situchan Bump! Please finish the checklist. Thanks!

**Comment by situchan** [comment] 2024-05-22 05:36
Sorry I am back from vacay

**Comment by situchan** [comment] 2024-05-22 05:41
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/35296
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/35296/files#r1609288483
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A

### Regression Test Proposal
1. Login to any account with several unread chats
2. [Web] Verify that browser's tab favicon shows unread status and tab title shows unread count
3. [iOS/Desktop] Verify that app's icon shows unread status

**Comment by deetergp** [comment] 2024-05-22 18:06
Thanks @situchan and welcome back 🎉

**Closed** 2024-05-22 21:11 UTC
Labels: External, Weekly, Awaiting Payment, Bug
