### ISSUE TITLE
[HOLD for payment 2024-06-11] LOW: Implement filtering for search pages.

### ISSUE THREAD

**Issue by TMisiukiewicz** [Expensify/App#37619] opened 2024-03-01 17:10 UTC
### Problem
Based on our measurements in high-traffic accounts, the search page takes an average of 4100ms to re-render on every keystroke. This is a problem because the user will notice a significant lag between changing their search term and the results list updating.
The root cause of this problem is `getSearchText`, which is called for every keystroke and is inefficient because it reconstructs all the options in the results list using createOption over and over.
### Solution
Let's speed up `getSearchText` by refactoring it such that, instead of re-generating all the result options every time the search terms change, we just generate the options once and filter them based on the current search term.
To achieve this, we recommend using a rank-value sorting, where a higher number means it will appear higher in the list:

- **Acronym** - item’s acronym is the given value
- **Contains** - item contains the given value
- **Word starts with** - if one of the item’s words starts with the given value
- **Starts with** - if the item starts with the given value
- **Equals** - case-insensitive equality
- **Case sensitive** - case-sensitive equality

Note that this will maintain the current search result ordering, just implement it in a different way. By making this change, we can improve the following metrics:

- `open_search` → Before: ~5900ms → After: ~4900ms (~1000ms improvement)
- `load_search_options` → Before: ~4100ms → After: ~3200ms (~900ms improvement)
- search query changed after initial load → Before: 4100ms → After: 350ms (~12x improvement)

We can apply this technique everywhere in the app where we use a search bar to filter option results.

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by roryabraham** [comment] 2024-03-01 17:21
Making @TMisiukiewicz the issue owner here since for now we're just awaiting a PR

**Comment by TMisiukiewicz** [comment] 2024-03-04 15:15
Already incorporated the algorithm into the codebase and created an util responsible for filtering, now working on implementing it into the first search page

**Comment by roryabraham** [comment] 2024-03-11 23:15
> how should we approach implementing it in other search pages? Should we implement filtering in all required pages with this single PR or should we get this one merged first and then implement each one separately?

let's definitely break it up into a series of smaller PRs if there's a straightforward way to do that. It might feel like more work but things always tend to go smoother this way 🙂

**Comment by DylanDylann** [comment] 2024-03-13 09:53
@TMisiukiewicz Could you help to make a video about this problem on staging? 

I also see this problem

>  the search page takes an average of 4100ms to re-render on every keystroke.

But It seems the RCA is from `SearchForReports` API takes a long time to respond

https://github.com/Expensify/App/assets/141406735/adf81ed9-e461-43d8-9130-4b92423c7a51

Please correct me if I missed anything

**Comment by TMisiukiewicz** [comment] 2024-03-13 10:48
hi @DylanDylann, the server search is not related to the changes made in this PR. This PR improves the performance of the local search by replacing options generation with filtering. On staging, you can enable showing verbose logs in the console and look for the messages: `Timing:staging.new.expensify.load_search_options`, when you type in the search input, it will give you the amount of time it takes to load the options that should be visible on the list. When testing this PR, this message won't be displayed after typing because it's not re-generating the options anymore - results should be displayed quicker.

Staging:

https://github.com/Expensify/App/assets/13985840/811f0ab7-64f8-4f69-af98-0788dd2b839e

Adhoc:

https://github.com/Expensify/App/assets/13985840/a18bbb0a-d27f-4cc6-a62a-d14f9b5d9e01

As you can see in the Adhoc build, the `load_search_options` is registered once server search is resolved, not when user stops typing (it's probably because response from the server updates some reports and there is a need of generating it once again)

**Comment by DylanDylann** [comment] 2024-03-13 12:24
@TMisiukiewicz Thanks. I see that in your PR.

**Comment by stephanieelliott** [comment] 2024-03-19 01:31
PR is moving along, seems like we are ready to test 🚀

**Comment by stephanieelliott** [comment] 2024-03-28 22:19
PR is waiting on your review @roryabraham!

**Comment by roryabraham** [comment] 2024-03-31 13:17
Sorry for the delay. I'll try to review tomorrow. It's a large PR so something I need to carve out a bit more time for

**Comment by stephanieelliott** [comment] 2024-04-04 23:18
PR is being actively reviewed

**Comment by roryabraham** [comment] 2024-04-15 20:17
The [initial search filtering PR](https://github.com/Expensify/App/pull/37909) was merged last week, awaiting the next ones to be ready for review

**Comment by TMisiukiewicz** [comment] 2024-04-17 12:53
Current status of migration:

**Ready for review:**
- Request money
- Send money

**Draft PR:**
- Share logs
- Assign to task
- Share task
- New Chat

**To Do:**
- Invite to room
- Invite to workspace

Draft PRs will be opened once the #40235 PR is merged (they share some part of the code that is implemented in that PR)

**Comment by TMisiukiewicz** [comment] 2024-04-23 13:16
All the searchable pages now have draft PRs. Waiting for #40235 to be merged before opening them

**Comment by stephanieelliott** [comment] 2024-04-23 14:41
Reapplying the `New Feature` label to get another BZ member on this while I am OOO til May 2. Thanks @laurenreidexpensify, I'll grab this back from you when I return!

**Comment by iwiznia** [comment] 2024-04-24 17:20
Hey, I am not 100% sure if this is a regression from this PR, but it seems it could....
I was trying to jump to one of our channels called `#nice-compliments` but was surprised when a "random" thread was showing up first (the thread's message does contain `nice` in it) was showing up first.
Not sure what the solution is exactly, some options:
1. Prefer channels over threads when all things are equal
2. Prefer reports that start with the searched term over reports that have it in other parts of the name

**Comment by stephanieelliott** [comment] 2024-05-02 23:19
Returning from OOO so I will grab this back from you @laurenreidexpensify! 

 Hey @TMisiukiewicz not sure if you saw the comment above -- can you weigh in on whether that may be a regression from one of your PRs that were recently merged?

**Comment by TMisiukiewicz** [comment] 2024-05-06 06:43
Hi @iwiznia @stephanieelliott sorry for late response, I was OOO as well, gonna take a deeper look on this issue today!

**Comment by TMisiukiewicz** [comment] 2024-05-06 13:48
So I investigated how it works, and seems like it is not a regression. Basically once we get the matching items, we are doing an additional sorting, where chatrooms and archived chats are moved to the bottom of the list. since `#nice-compliments` is a chatroom, that's the reason why it is on the list under a thread. On the other hand, if the searched value is an exact match of an `option.login`, it is moved to the top of the list.

> Prefer channels over threads when all things are equal

That's the easiest way (probably just few lines of code to change), and we could implement it only when search value is not empty, so when the full list of options is rendered, the threads are not moved to the bottom. 
> Prefer reports that start with the searched term over reports that have it in other parts of the name

Notice that the chatroom name starts with `#`, so it is treated the same as having a `nice` somewhere in the middle of a string. That could be easily improved by ignoring `#` in the chatroom names when search value does not start with `#`.

However, there might be some cases where the results might slightly differ from the current behavior. Especially when you are searching for some options based on personal details, e.g. e-mail. If we decide to move forward with it, would be great to test it on the adhoc build before merging.

Let me know your thoughts, if that sounds good I can prepare a PR 👍

**Comment by stephanieelliott** [comment] 2024-05-09 17:17
Thanks @TMisiukiewicz! 

> > Prefer channels over threads when all things are equal
> 
> That's the easiest way (probably just few lines of code to change), and we could implement it only when search value is not empty, so when the full list of options is rendered, the threads are not moved to the bottom.

It seems like this option is probably the way to go. @roryabraham @iwiznia what do you guys think?

**Comment by iwiznia** [comment] 2024-05-09 17:25
> where chatrooms and archived chats are moved to the bottom of the list

Why are we moving chat rooms to the bottom? That seems wrong to me... 

> , the threads are not moved to the bottom.

Wouldn't this make them show on the top? 😕 

> Notice that the chatroom name starts with #, so it is treated the same as having a nice somewhere in the middle of a string. That could be easily improved by ignoring # in the chatroom names when search value does not start with #.

Yes, we should do this.

**Comment by TMisiukiewicz** [comment] 2024-05-14 07:33
> Why are we moving chat rooms to the bottom? That seems wrong to me...

I think it's because it prioritizes search by user data over chat rooms - if you type e.g. an e-mail, and it's a chat room participant, the chat room would display higher on the list than the user you are actually looking for, which seems confusing. However, when searching for a chat room by its name, personal details-based options are unlikely to appear, so the search results appear correct. Putting chat rooms at the end of the list doesn't affect prioritization, as there are no other items that should be ranked above them.

> Wouldn't this make them show on the top? 😕

when the full list is rendered, items are sorted by last activity time first and by putting chat rooms and archived rooms on the bottom second , so threads can possibly show on top as well. That's the current default behavior. I was thinking about proritizing chat rooms over threads only when search input is not empty, so if search alghoritm finds a chat room and thread with a search term you provided, it will put the chat room higher, regardless of the last activity time.

**Comment by stephanieelliott** [comment] 2024-05-17 20:51
Thanks @TMisiukiewicz! 

> Notice that the chatroom name starts with #, so it is treated the same as having a nice somewhere in the middle of a string. That could be easily improved by ignoring # in the chatroom names when search value does not start with #.

OK, so it sounds like we want to move forward with this option, and I think that it fits within the scope of issue. Can you work on a PR for it?

**Comment by TMisiukiewicz** [comment] 2024-05-20 08:57
@stephanieelliott sure I'll take care of it this week

**Comment by TMisiukiewicz** [comment] 2024-05-21 09:31
@stephanieelliott sorry, I just figured out this won't change anything, because even if we ignore `#`, we have this ordering happening after results are filtered, I already mentioned it earlier:
> Basically once we get the matching items, we are doing an additional sorting, where chatrooms and archived chats are moved to the bottom of the list.

So I think the only way to handle it is this
>  I was thinking about proritizing chat rooms over threads only when search input is not empty, so if search alghoritm finds a chat room and thread with a search term you provided, it will put the chat room higher

Created a draft PR #42411 , let me know if that solution works for you so I can open it for a review

**Comment by TMisiukiewicz** [comment] 2024-05-23 12:21
I'm off until Monday so I opened the PR to not block it during my absence

**Comment by stephanieelliott** [comment] 2024-05-29 07:15
Thanks @TMisiukiewicz! 

PR is reviewed and ready to be merged, just holding since we're on a semi-freeze

**Comment by stephanieelliott** [comment] 2024-06-01 02:50
PR is on staging!

**Comment by DylanDylann** [comment] 2024-06-14 03:26
@stephanieelliott Should I get payment for reviewing [this PR](https://github.com/Expensify/App/pull/37909)?

**Comment by stephanieelliott** [comment] 2024-06-18 07:11
Oh, yeah @DylanDylann  not sure why that summary skipped the C+ 

Summarizing payment on this issue: 

 - Contributor: @TMisiukiewicz - no payment needed (Expert Contributor)
 - Contributor+: @DylanDylann $250 via Upwork -- offer extended

https://www.upwork.com/jobs/~01cd8b29a9eb2d9b90

**Comment by DylanDylann** [comment] 2024-06-19 05:25
@stephanieelliott This issue was created on March 2 and the PR was created on March 8 when the initial price still was 500$. Should we update the offer to increase the compensation?

**Comment by stephanieelliott** [comment] 2024-06-20 21:36
Yes @DylanDylann, updated! Please accept the offer when you get a chance.

**Comment by DylanDylann** [comment] 2024-06-22 04:44
@stephanieelliott I accepted the offer, huge thanks!

**Comment by stephanieelliott** [comment] 2024-06-25 00:38
All paid!

**Closed by stephanieelliott** 2024-06-25 00:38 UTC
Labels: Engineering, Daily, NewFeature, Overdue, Awaiting Payment

**Comment by DylanDylann** [comment] 2024-10-16 16:44
Hi @stephanieelliott According to the [payment summary](https://github.com/Expensify/App/issues/37619#issuecomment-2175333947), the payment for me should be $500, but only $250 was paid out (via [this offer](https://www.upwork.com/nx/wm/offer/102817010)), can you help re-check on this?

**Comment by stephanieelliott** [comment] 2024-10-24 06:01
Oops! So weird, the job was $500 but the milestone was just $250. Sorry about that! Sent another $250 as a bonus on the same job, so we should be square now!

**Comment by DylanDylann** [comment] 2024-10-25 16:31
@stephanieelliott Thanks so much for looking into this 🥇

**Comment by mallenexpensify** [comment] 2025-07-31 17:18
### Payment Summary 

Contributor+: @Ollyws due $500 via NewDot for [PR review](https://github.com/Expensify/App/pull/42411)

I checked assignment date and it's after their eligibility date
