### ISSUE TITLE
New lines doesn't preserved when copying multi-line message with "Copy to Clipboard" reported by @kerupuksambel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12556] opened 2022-11-08 16:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send a multi-line message
3. Copy it with Copy to Clipboard
4. Paste it to a text editor

## Expected Result : 
The multi-line message should be multi-lined when pasted to the text editor

## Actual Result : 
The new lines isn't preserved and multi-line message is turned into one line message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200619428-cde64e54-6b9b-4df3-bd66-e2f53b973898.mp4

https://user-images.githubusercontent.com/43996225/200619455-f1fb7253-eca2-41c7-b84b-f08dbc706b91.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667859412449149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-11-08 21:49
I can't reproduce testing it on the latest staging `v1.2.25-0` on either Web nor Desktop following these steps: 

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send a multi-line message
3. Copy it by clicking the clipboard icon on the comment action menu 
4. Paste it to a text editor (I've used Mac's `TextEdit`)

<img width="583" alt="image" src="https://user-images.githubusercontent.com/16232057/200683084-7441884c-1a78-4cd7-9321-3feaf5cdaa76.png">

Closing this out, and popping a note in the original thread. Feel free to suggest better reproduction steps to reliably reproduce this to reopen it.

**Closed by trjExpensify** 2022-11-08 21:49 UTC
Labels: Daily, Bug
