### ISSUE TITLE
[$250] mWeb - IOU - Hidden user is shown in split expense if new user is invited to room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47233] opened 2024-08-12 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4845754
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap start chat
3. Create a new room
4. Tap header -- members
5. Invite a new user with no expensify account
6. Navigate to conversation page
7. Tap plus icon -- split expense
8. Enter an amount and tap next

## Expected Result:
Hidden user must not be shown in split expense if new user with no expensify account is invited to room

## Actual Result:
Hidden user is shown in split expense if new user with no expensify account is invited to room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/032143ce-0944-4d9c-a2ca-4a372141a834

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a81711c35771fb09</li>
        <li>Upwork Job ID: 1823770451031123290</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by lanitochka17** [comment] 2024-08-12 13:48
We think that this bug might be related to #vip-split

**Comment by lanitochka17** [comment] 2024-08-12 13:49
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-12 14:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - IOU - Hidden user is shown in split expense if new user is invited to room

### What is the root cause of that problem?
We are not filtering out the optimistically created participants here
https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L149-L155
### What changes do you think we should make in order to solve the problem?

We should filter out if the participant cannot be found in personalDetails
```
const participants = useMemo(
        () =>
            transaction?.participants
                ?.filter((participant) => {
                    return !!personalDetails[participant.accountID ?? ''];
                })
                ?.map((participant) => {
```
### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2024-08-14 17:15
hey there @Pujan92 please can you review the proposal above and let me know if we can move ahead with assigning this contributor to the issue?

**Comment by Pujan92** [comment] 2024-08-17 13:37
@FitseTLT Are you able to reproduce the issue as I am not able to reproduce it?

**Comment by FitseTLT** [comment] 2024-08-17 16:01
This issue is fixed now we can close it. @zanyrenney

**Comment by zanyrenney** [comment] 2024-08-22 12:54
This issue is fixed now we can close it. @zanyrenney

**Closed by zanyrenney** 2024-08-22 12:54 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
