### ISSUE TITLE
[$500] Expense - "This report will be reimbursed outside of Expensify" sentence disappears in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34051] opened 2024-01-05 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace on Old Dot
1. Go to workspace chat as employee
2. Create a manual request
3. Submit the report
4. As admin, pay the report elsewhere
5. As employee, click on the expense preview
6. Right click on the reimbursement message > Reply in thread

## Expected Result:
The reimbursement message will not disappear in thread

## Actual Result:
Part of the reimburment message - "This report will be reimbursed outside of Expensify" disappears in thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/13aa43e6-ffe5-4651-9fa6-8a2ab4ed418b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188aabe1016612f59</li>
        <li>Upwork Job ID: 1743440258673152000</li>
        <li>Last Price Increase: 2024-01-06</li>
    </ul>
</details>

**Comment by joelbettner** [comment] 2024-01-06 01:11
@gijoe0295 can you provide some links to the code to describe where you're talking about?

**Comment by joelbettner** [comment] 2024-01-06 01:16
cc: @Beamanator

**Comment by bernhardoj** [comment] 2024-01-06 04:11
I think it's a BE issue. Every time we open the thread, the OpenReport (thread) gives a shorter message. If we go back to the chat report, the OpenReport (chat report) gives the complete message.

**Comment by ktejas** [comment] 2024-01-06 16:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Part of the reimburment message - "This report will be reimbursed outside of Expensify" disappears in thread

### What is the root cause of that problem?
When calling openReport() we are passing reportID key's value instead of chatReportID key's value from the object "props.report".
![Screenshot from 2024-01-06 20-48-24](https://github.com/Expensify/App/assets/2357228/318ac42a-1edd-45aa-9a4b-5c0aba438978)
![Screenshot from 2024-01-06 20-49-06](https://github.com/Expensify/App/assets/2357228/0bc98c8a-98ea-41d7-9c44-de4a4a70b300)

### What changes do you think we should make in order to solve the problem?
Fix the request body Payload to the API command 'OpenReport', by passing chatReportID instead of reportID in the Form Data key named 'reportID'.
![Screenshot from 2024-01-06 21-25-16](https://github.com/Expensify/App/assets/2357228/127e721e-7bd2-400c-b140-65b916f7070b)


### What alternative solutions did you explore? (Optional)
Tried to reduce multiple API calls to OpenReport command. But ran out of time, couldn't figure out an alternate solution.

**Comment by ktejas** [comment] 2024-01-06 16:08
Contributor details
Your Expensify account email: krishnasalimeda@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0152d06b5129e5b130

**Comment by mvtglobally** [comment] 2024-01-07 04:55
Still repro on build 1.4.22-2 

https://github.com/Expensify/App/assets/43995119/ab19d69c-2713-4a14-bce5-a2ac7107a1ce

**Comment by Beamanator** [comment] 2024-01-10 12:11
Hmm honestly I don't think we want to be able to create a thread on this automated message... 

@JmillsExpensify since we've talked about this system message showing up in NewDot (the `You marked this report as manually reimbursed. This report will be reimbursed outside of Expensify` message): Do you think users should be able to start threads from these comments or not?

**Comment by joelbettner** [comment] 2024-01-12 20:38
I think this issue is going to be resolved by the two linked issues and their respective PRs above. I'm going to close. @Beamanator @jasperhuangg feel free to open if you disagree.

**Closed by joelbettner** 2024-01-12 20:38 UTC
Labels: Engineering, Daily, Internal, Overdue
