### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Send invoice - Thread header in invoice workspace chat shows third line "Invoice"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41289] opened 2024-04-30 02:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (New Feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Send a message.
4. Right click on the message > Reply in thread.
5. Note that the header consists of two lines.
6. Go to FAB > Send invoice.
7. Send an invoice.
8. In invoice workspace chat, send a message.
9. Right click on the message > Reply in thread.
## Expected Result:
Only two lines will be shown in the thread header, which will be header and subtitle link.

## Actual Result:
Three lines are shown in invoice workspace chat thread header, which are made of header, subtitle link and "Invoice" line.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/36c29af0-805f-48f5-bc15-2e7e3328c3fb

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151a2dd35ff38b79a</li>
        <li>Upwork Job ID: 1785187433647714304</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by m-natarajan** [comment] 2024-04-30 02:50
We think this bug might be related to #wave-collect - Release 1

**Comment by m-natarajan** [comment] 2024-04-30 02:50
@robertjchen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Nodebrute** [comment] 2024-04-30 03:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Thread header in invoice workspace chat shows third line "Invoice"
### What is the root cause of that problem?
That's because we check for isChatThread after isInvoiceRoom.
https://github.com/Expensify/App/blob/a462d5854359850359f248aaec58ad4bc2c0efcd/src/libs/ReportUtils.ts#L3164-L3169
### What changes do you think we should make in order to solve the problem?

We should swap positions of these two checks.
https://github.com/Expensify/App/blob/a462d5854359850359f248aaec58ad4bc2c0efcd/src/libs/ReportUtils.ts#L3164-L3169
```
 if (isChatThread(report)) {
        return '';
    }
    if (isInvoiceRoom(report)) {
        return Localize.translateLocal('workspace.common.invoices');
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by robertjchen** [comment] 2024-04-30 06:00
Does not appear to be a serious deploy blocker to me and should be addressable by external contributors 👍

**Comment by neonbhai** [comment] 2024-04-30 09:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread header in invoice workspace chat shows third line "Invoice"

### What is the root cause of that problem?
We never show subtitle for chat threads in app, but don't check for it here:

https://github.com/Expensify/App/blob/aee3a53099e87577639413561c0fd590ee56f1eb/src/pages/home/HeaderView.tsx#L118-L121

The issue is apparent when the order of checks in getChatRoom changed. This makes it easy to introduce regressions to header in the future as we don't have clear enough rule as what should be the order of the checks.

https://github.com/Expensify/App/blob/aee3a53099e87577639413561c0fd590ee56f1eb/src/libs/ReportUtils.ts#L3163-L3169

To make sure we don't accidently display subtitles in future (even if a subtitle is calculated) in the context of a thread, we would add sanity checks here:

https://github.com/Expensify/App/blob/aee3a53099e87577639413561c0fd590ee56f1eb/src/pages/home/HeaderView.tsx#L118-L121

This would make the display logic clear and independent of arbitrary ordered if conditions [here](https://github.com/Expensify/App/blob/aee3a53099e87577639413561c0fd590ee56f1eb/src/libs/ReportUtils.ts#L3163-L3190).

### What changes do you think we should make in order to solve the problem?
We would:
- Keep the `isChatThread` as the first check in `getChatRoomSubtitle `:
  https://github.com/Expensify/App/blob/aee3a53099e87577639413561c0fd590ee56f1eb/src/libs/ReportUtils.ts#L3163
- We will add a check for `!isChatThead` in `shouldShowSubtitle` here
  https://github.com/Expensify/App/blob/aee3a53099e87577639413561c0fd590ee56f1eb/src/pages/home/HeaderView.tsx#L118
  ```jsx
  if(isChatThead) {
      return false
  }
  ```
  
### Result
This works perfectly:

https://github.com/Expensify/App/assets/64629613/0b31f137-2b86-4537-a0bd-9c42effed486

**Comment by cristipaval** [comment] 2024-04-30 15:05
#vip-billpay related. cc @danielrvidal

**Comment by VickyStash** [comment] 2024-04-30 15:51
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by Nodebrute** [comment] 2024-04-30 17:06
@cristipaval Hi, I submitted my proposal after the 'help wanted' tag was added. As far as I know, proposals submitted before the Callstack contributor's comment are considered.

**Comment by VickyStash** [comment] 2024-04-30 19:55
NOTE: I'll be OOO 1-8th of May 🌴

**Comment by alexpensify** [comment] 2024-05-08 22:16
Tomorrow, I'll prepare the payment summary if one isn't auto-created for this issue.

**Comment by alexpensify** [comment] 2024-05-09 22:25
Closing - the automation is correct here. @rushatgabhane please submit the payment request. Thanks!

**Closed by alexpensify** 2024-05-09 22:25 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 04:06
$250 approved for @rushatgabhane
