### ISSUE TITLE
[$1000] Web - On copy paste on workspace invite message page, app pastes text on compose box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23184] opened 2023-07-19 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open members
6. Reload the page
7. Remove any user
8. Click on invite and select any issue
9. Click Next
10. On invite message page, copy the current text and try to paste same text after it, observe that text is pasted in compose box behind

## Expected Result:
App should paste text in invite message field if we copy and paste text while invite message field is in focus

## Actual Result:
App pastes the text in compose box when we reload on members page, remove 1 member and invite any other and reach invite message paste

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-18
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/78509c3f-9cd6-4e2c-aa25-2030de3e7a3e

https://github.com/Expensify/App/assets/93399543/e452f038-e997-4fc0-8e9b-9496d7dd343a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689703579147449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105c6892023aa08e8</li>
        <li>Upwork Job ID: 1683525862926856192</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 25841637</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-07-19 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy-paste on the workspace invite page leads to the text being pasted in the compose box.
### What is the root cause of that problem?
After reload, composer gets `paste event` and check value of `checkComposerVisibility` function.
https://github.com/Expensify/App/blob/0fcfe75f47c8f7e413f1b08885be124d33f9e17d/src/pages/home/report/ReportActionCompose.js#L703-L706
when closing `remove member` Dialog, `this.propos.modal.isVisible` becomes to false.
so composer gets the incorrect paste.
### What changes do you think we should make in order to solve the problem?
When closing Modal, we should not set `ONYXKEYS.MODAL` value.
https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/pages/workspace/WorkspaceMembersPage.js#L422-L431
we can add this `ConfirmModal` of `WorkspaceMembersPage`
```
shouldSetModalVisibility={false}
````
### What alternative solutions did you explore? (Optional)

**Comment by makiour** [comment] 2023-07-19 20:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The issue here is that the paste command is not working when trying to paste into invite message after deleting a user.

**Investigation**
After I looked into the error, I found that a paste issue is occuring also when we try to paste in the edited comment as it is a composer component same as the main chat composer. 
When we try to paste into an edited comment, it also pastes into the main composer of the report open. Here is a video illustrating the issue. 
[bugPasting.webm](https://github.com/Expensify/App/assets/60530038/3e618484-b55b-4893-8493-46f787ae2dfd)

Thus, the root cause should be fixing the whole pasting mechanism as it occurs in multiple instances of components.


### What is the root cause of that problem?

The first thing I did is investigating the paste function, and I found that there was a global paste event listener which is always called and triggered when the component mount here:
https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/components/Composer/index.js#L176-L178

And will unmount here: 
https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/components/Composer/index.js#L210

My first thought is that a general paste listener is not needed as we have handlePaste that will do the job, however, the issue here is if we delete the global pasting listener, this will not allow attachment or HTML pasting and they are handled differently.

The root cause, then, is that we are making the listener global for the entire HTML document, which affects all elements/components of the page. Thus, we need to handle it specifically for the input we are dealing with:

--> We need to use the textInput element istead of document where the listener then will be associated with only to the specific input!

### What changes do you think we should make in order to solve the problem?

We need to change componentDidMount line:
https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/components/Composer/index.js#L177

to 

`this.textInput.addEventListener('paste', this.handlePaste);`

and componentWillUnmount line:
https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/components/Composer/index.js#L210

To 

`this.textInput.removeEventListener('paste', this.handlePaste);`



### What alternative solutions did you explore? (Optional)
N/A

**Comment by johncschuster** [comment] 2023-07-21 20:51
Heads up, @robertKozik

**Comment by robertKozik** [comment] 2023-07-24 16:14
thanks @johncschuster for mentioning. Looking into it

**Comment by johncschuster** [comment] 2023-07-24 17:14
@parasharrajat do you agree with @robertKozik's [proposal](https://github.com/Expensify/App/issues/23184#issuecomment-1648276401) above?

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 21:29
This is fixed now, can you still reproduce this?

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 21:33
This ends up as a duplicate as all share a common root cause. 
@parasharrajat I'll pick this up from you anyways as it is a regression,
@johncschuster Please assign me this one.

I'll post the next steps here, thanks!

**Comment by abdulrahuman5196** [comment] 2023-08-01 10:52
@Santhosh-Sellavel This issue also seems to be related - https://github.com/Expensify/App/issues/23319

**Comment by johncschuster** [comment] 2023-08-01 22:36
@Santhosh-Sellavel how's it going? Do you have next steps for us?

**Comment by mvtglobally** [comment] 2023-08-02 16:47
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2023-08-02 23:39
It seems the issue is no longer reproducible. Holding.

**Comment by Santhosh-Sellavel** [comment] 2023-08-07 17:53
Just on hold, for now, discussion in Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1690242585218809)

**Comment by johncschuster** [comment] 2023-08-07 21:28
Thanks for the heads up, @Santhosh-Sellavel!

**Comment by Santhosh-Sellavel** [comment] 2023-08-09 23:20
@johncschuster We decided not to revert the PR, so we can close this one and just issue reporting bonus here.  As this one is already fixed.

**Comment by johncschuster** [comment] 2023-08-14 21:42
Payment has been issued to the bug reporter (@dhanashree-sawant). Closing!

**Closed by johncschuster** 2023-08-14 21:42 UTC
Labels: External, Engineering, Daily, Overdue, Bug
