### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000]  Error not displayed for invalid phone number in New Contact Method section

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21247] opened 2023-06-21 18:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Profile > Contact Methods
2. Click "New Contact Method"
3. Enter an invalid phone number (e.g. +1-212-456ww7890)
4. No error is displayed

## Expected Result: 
The app should display an error for invalid phone numbers to ensure consistency
## Actual Result: 
The app does not display an error for invalid phone numbers in the New Contact Method section.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture - 2023-06-15T014547.796.webm](https://github.com/Expensify/App/assets/43996225/210e728f-42cf-4470-99ed-bcbe09d1f13e)

https://github.com/Expensify/App/assets/43996225/61483a1d-954b-47ca-a61b-358e2cb7f669

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686819848909279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193d5a8ad70190344</li>
        <li>Upwork Job ID: 1671812275847946240</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-06-22 09:26
@getusha Maybe, but we don't translate `+1-212-456ww7890` into `+1-212-456997890`. Either way, that's incorrect! 

So there are two potential solutions: reject non-numeric phone numbers (ie: show an error when you enter `+1-212-456ww7890`) or translate the letters into numbers (ie: translate `+1-212-456ww7890` into +1-212-456997890`.

I think we can safely use the first solution by validating that field. we seem to reject it on the back-end, as we initially allow that phone number to be entered, and then we silently remove it from the Contact Method list.

**Comment by conorpendergrast** [comment] 2023-06-22 09:27
This may have a similar solution to https://github.com/Expensify/App/issues/21230, also reported by @tewodrosGirmaA

**Comment by mananjadhav** [comment] 2023-06-22 09:53
Thanks for the proposal @getusha. This looks good to me. As you rightly said, letters is phone numbers is acceptable but as mentioned earlier we don't convert them to digits. 

@conorpendergrast  We can use @getusha's solution. The linked issue is related to email and not necessarily the same solution.

**Comment by alexxxwork** [comment] 2023-06-22 11:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The form validates telephone numbers with letters in them on add new contact page

### What is the root cause of that problem?

The root cause of the problem is that we use awsome-phonenumber lib to check telephone number validity. And this lib uses Google's libphonenumber.
And libphonenumber lib allows using letters instead of numbers in a phone number, as seen here:

https://github.com/google/libphonenumber/blob/b30f7d90154b3148ee7b162f0e236a9cd1fa2229/javascript/i18n/phonenumbers/phonenumberutil.js#L560-L567

### What changes do you think we should make in order to solve the problem?


We could check if the input number contains letters and replace the number using awsome-phonenumbers methods. We already do it before sending info to backend here:
https://github.com/Expensify/App/blob/9bef5074ae858e7efb0d757473409ef099dac309/src/pages/settings/Profile/Contacts/NewContactMethodPage.js#L71-L73

So we could update number in the form after successful check for validity

**Comment by Babur171** [comment] 2023-06-22 13:22
@kavimuru

**Comment by Babur171** [comment] 2023-06-22 13:25
Firstly, a regex pattern should be defined to validate phone numbers. This pattern should cover the acceptable format and any specific requirements for phone numbers in your system. For example, it might include rules for country codes, area codes, and number length.

Once the regex pattern is defined, it can be applied to the phone number input field in the "New Contact Method" section. This can be done during the form validation process. When the user submits the form or moves to the next field, the phone number should be checked against the regex pattern.

**Comment by conorpendergrast** [comment] 2023-06-22 15:28
@mananjadhav Can you do that thang and post to accept the solution? That'll auto-assign the engineer to review and confirm the solution, and assign @getusha. Thank you!

**Comment by mananjadhav** [comment] 2023-06-22 15:31
@conorpendergrast Sorry I missed that, I updated the comment, will it assign then?

**Comment by mananjadhav** [comment] 2023-06-22 15:32
Thanks for the [proposal](https://github.com/Expensify/App/issues/21247#issuecomment-1602332099) @getusha. This looks good to me. As you rightly said, letters is phone numbers is acceptable but as mentioned earlier we don't convert them to digits. 

C+ reviewed  🎀👀🎀

**Comment by mananjadhav** [comment] 2023-06-22 15:34
@conorpendergrast Am I doing something wrong? It looks like it didn't assign an engineer.

**Comment by conorpendergrast** [comment] 2023-06-22 19:40
:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by conorpendergrast** [comment] 2023-06-22 19:41
:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by conorpendergrast** [comment] 2023-06-22 19:48
Ah, that won't work for me anyway because I'm C+ (I checked where we interact with GitHub's webhook on this). 

@mananjadhav I don't think it works on comment edits, _I think_.  Can you try posting with just `:ribbon: :eyes: :ribbon:` which is what we're looking for

**Comment by slafortune** [comment] 2023-06-22 21:46
Will the fix in this issue address any invalid field - phone or email? Would you like me to close [this](https://github.com/Expensify/App/issues/21230) as a duplicate?

**Comment by mananjadhav** [comment] 2023-06-23 04:46
I think this will just fix the phone. We can add email here, but I think better to have a separate issue?

:ribbon: :eyes: :ribbon: C+ Reviewed

**Comment by mananjadhav** [comment] 2023-06-23 04:46
@jasperhuangg This is the [comment](https://github.com/Expensify/App/issues/21247#issuecomment-1602849980) with the linked proposal.

Thanks @conorpendergrast.

**Comment by conorpendergrast** [comment] 2023-06-27 09:55
I see the PR has been reviewed and approved by @mananjadhav, currently waiting for review by @jasperhuangg 👍

**Comment by conorpendergrast** [comment] 2023-06-28 13:06
Contracts sent for all three (bug, C and C+), including the 50% urgency bonus for C and C+

**Comment by jasperhuangg** [comment] 2023-07-07 20:32
cc @conorpendergrast it's past 07/06, let's get people paid!

**Comment by conorpendergrast** [comment] 2023-07-10 13:42
I agree, everyone got paid! 

@mananjadhav We just need [the checklist](https://github.com/Expensify/App/issues/21247#issuecomment-1613736158) now please

**Comment by mananjadhav** [comment] 2023-07-10 16:56
Here's the offending [PR](https://github.com/Expensify/App/pull/18223), which I think caused the bug when resolving merge conflicts [here](https://github.com/getusha/App/commit/13eeb808bf09a9c4a51dfa8c2b37db000426dd77)?  I've posted a comment [here](https://github.com/getusha/App/commit/13eeb808bf09a9c4a51dfa8c2b37db000426dd77#r121192800).

I do think it makes sense to add a regression test here so that we don't end up looking at this case again. @conorpendergrast The test steps from the PR are good enough for the regression test.

**Comment by conorpendergrast** [comment] 2023-07-11 14:29
Regression test created: https://github.com/Expensify/Expensify/issues/299038

And we're all done!

**Closed by conorpendergrast** 2023-07-11 14:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
