### ISSUE TITLE
[$1000] Add a Check-In Button to the Lounge Access Page

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#25425] opened 2023-08-17 18:47 UTC
## Problem

Coming from https://github.com/Expensify/Expensify/issues/298259 as well as some [conversations](https://expensify.slack.com/archives/CLR7QV2DN/p1692291562329509?thread_ts=1691094838.093729&cid=CLR7QV2DN) in Slack we need capture all lounge attendees, even if they don't end up using the WiFi. In addition, we'd like to have a way to limit lounge visits in the future in-app.

## Solution
Add a check-in button for the lounge pass that we would authenticate when customers enter the space. Here's a mockup:

![image](https://github.com/Expensify/App/assets/7516624/d7e01bf8-e552-4ba0-b0c6-aa3b76783d09)
![image](https://github.com/Expensify/App/assets/7516624/8d2fcbec-8c8a-43b7-989d-729699634e81)

You can find these screens in the [NewDot / Lounge Access Figma file](https://www.figma.com/file/vwDE2f4cboyl1d9TkOV913/Lounge-Access?type=design&node-id=0-1&mode=design&t=ZoTxdlViQZaqIzm9-11), and you can check out the threads mentioned in my previous comment to read the discussions.

The button would call a new API command: `RecordLoungeVisit` ([Issue](https://github.com/Expensify/Expensify/issues/309023) - done)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01466d67f7aa839a02</li>
        <li>Upwork Job ID: 1696495334494158848</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26420500</li>
</ul></li>
    </ul>
</details>

**Comment by yuwenmemon** [comment] 2023-08-17 18:48
Tagging Design for their input.

**Comment by maddylewis** [comment] 2023-08-17 19:12
i don't think a BZ member needs to be assigned to this but feel free to re-assign me if im missing something - ty!

**Comment by yuwenmemon** [comment] 2023-08-21 20:49
@shawnborton @dannymcclain curious for your thoughts on the design I described in the OP:

> Ideally, after checking in the graphic above could change colors or change entirely to show the new state of being "Checked In"

**Comment by dannymcclain** [comment] 2023-08-21 20:51
@yuwenmemon I'm actually working on this now and will hopefully be posting something in slack in a bit. I think we definitely want to provide _some kind_ of affordance that they are checked in, but I'm not sure if the graphic is the place to do it (definitely going to explore that though).

**Comment by dannymcclain** [comment] 2023-08-21 21:41
Just posted some options in Slack: https://expensify.slack.com/archives/CLR7QV2DN/p1692653956599479?thread_ts=1691094838.093729&cid=CLR7QV2DN

**Comment by dannymcclain** [comment] 2023-08-22 14:51
[A few more ideas after some feedback](https://expensify.slack.com/archives/CLR7QV2DN/p1692715814861149?thread_ts=1691094838.093729&cid=CLR7QV2DN)

**Comment by dannymcclain** [comment] 2023-08-22 15:45
Shawn had [an idea](https://expensify.slack.com/archives/CLR7QV2DN/p1692717121125429?thread_ts=1691094838.093729&cid=CLR7QV2DN) to clean up some of the organization of this screen and make the hierarchy a little more clear (I really like it a lot).

**Comment by dannymcclain** [comment] 2023-08-23 16:03
Posted a little tweak to Shawn's idea in the [#lounges thread/channel](https://expensify.slack.com/archives/CLR7QV2DN/p1692806568187439?thread_ts=1691094838.093729&cid=CLR7QV2DN).

**Comment by dannymcclain** [comment] 2023-08-23 17:54
[Posted (hopefully the last) set of options for us to pick from.](https://expensify.slack.com/archives/CLR7QV2DN/p1692812712307839?thread_ts=1691094838.093729&cid=CLR7QV2DN)

**Comment by dannymcclain** [comment] 2023-08-23 20:10
We have a winner! 
![image](https://github.com/Expensify/App/assets/7516624/d7e01bf8-e552-4ba0-b0c6-aa3b76783d09)
![image](https://github.com/Expensify/App/assets/7516624/8d2fcbec-8c8a-43b7-989d-729699634e81)

You can find these screens in the [NewDot / Lounge Access Figma file](https://www.figma.com/file/vwDE2f4cboyl1d9TkOV913/Lounge-Access?type=design&node-id=0-1&mode=design&t=ZoTxdlViQZaqIzm9-11), and you can check out the threads mentioned in my previous comment to read the discussions.

**Comment by dannymcclain** [comment] 2023-08-28 13:35
Does everyone have what they need for this one?

**Comment by yuwenmemon** [comment] 2023-08-28 19:23
Yep, thanks @dannymcclain!

**Comment by joekaufmanexpensify** [comment] 2023-08-28 20:33
[Posted in SWM room. ](https://expensify.slack.com/archives/C04878MDF34/p1693254826524139)

**Comment by MaciejSWM** [comment] 2023-08-29 09:13
Hey @yuwenmemon. I'm from Software Mansion and I'll be more than happy to help! Let's chat later today about the details.

**Comment by b4s36t4** [comment] 2023-08-29 12:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add a Check-In Button to the Lounge Access Page
### What is the root cause of that problem?
NA - Feature Request

### What changes do you think we should make in order to solve the problem?
1. We should add 3 new menu items/fields 
    - Address Field fetched by geo location
    - Amount of check-in remaining
    - Check-in button.

* Button should be disabled if user is offline

2. API calls required
    * Fetches check-in and location of user
    * Add Optimistic data to show loader when the API call is going
    * error field to show error in case of any error which check-in
    * Call `RecordLoungeVisit` with appropriate params to record the lounge visit.




### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment] 2023-08-30 19:42
One proposal pending review

**Comment by joekaufmanexpensify** [comment] 2023-08-30 19:42
Separately @MaciejSWM did you and @yuwenmemon connect on your questions? If not, perhaps we can discuss them here?

**Comment by yuwenmemon** [comment] 2023-08-30 21:42
Yeah, @MaciejSWM is going to be working on this with myself assisting on some back-end changes. We can remove the `Help Wanted` label.

**Comment by joekaufmanexpensify** [comment] 2023-08-31 20:19
@yuwenmemon are the frontend changes held on the backend changes you linked above? Or can @MaciejSWM start on those now?

**Comment by yuwenmemon** [comment] 2023-08-31 20:21
I've provided @MaciejSWM with details on what data to expect and what the format should be. So he is free to start now if he pleases!

**Comment by joekaufmanexpensify** [comment] 2023-09-01 19:50
Sounds good! @MaciejSWM could you share when a PR might be up here?

**Comment by joekaufmanexpensify** [comment] 2023-09-04 17:25
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-09-05 20:11
@MaciejSWM bump on this when you have a sec?

**Comment by MaciejSWM** [comment] 2023-09-06 14:53
Hi guys, sorry, github mentions are not the best way to reach me, always better to ping on slack, sorry for not responding.

Anyway posting here the details we agreed on:
- The address of the Lounge is going to be hardcoded on the Frontend side
- The rest of the data is coming from the Backend side - number of entries left, current status of entry, etc.
- Scope: For now the user can only enter the lounge, but can't leave it manually.

I'll be OOO starting today, and I come back on Tuesday the 12th. Let's see if I can make any progress before I leave. I'll post a Draft PR if I can

**Comment by joekaufmanexpensify** [comment] 2023-09-06 14:55
All good, and sounds good! Bumping this to weekly if you'll be OOO.

**Comment by MaciejSWM** [comment] 2023-09-06 19:14
I pushed a draft PR

**Comment by joekaufmanexpensify** [comment] 2023-09-11 13:39
Sounds good!

**Comment by MaciejSWM** [comment] 2023-09-15 12:04
@yuwenmemon @dannymcclain any suggestions on the design when there are no check-ins left in the current month? Hide the check-in button?
<img width="430" alt="image" src="https://github.com/Expensify/App/assets/85628901/839ed1ee-5e50-4e1f-8097-e9e4ff690c22">

**Comment by dannymcclain** [comment] 2023-09-15 14:39
What if we did something like one of these? Let them know they're out of check-ins, but will be eligible again next month. And use a disabled button to let them know when they can check-in again. I think this language will probably need some tweaking, but it gets the idea across. @shawnborton what do you think?

<img width="670" alt="image" src="https://github.com/Expensify/App/assets/7516624/36119e69-300c-409a-b62f-a086bda963d2">

**Comment by shawnborton** [comment] 2023-09-18 05:26
I think we might want to avoid the disabled button as I think per our form guidelines, we try to avoid them and instead always allow users to submit forms but return error messages when needed. Given that they can't really submit anything here, I would opt to just remove the button and add the text to existing blurb right above.

**Comment by dannymcclain** [comment] 2023-09-18 15:07
Yeah you're right—good call. That'd look like this (blurb text is kinda FPO—we can update it to say whatever makes the most sense).
<img width="750" alt="image" src="https://github.com/Expensify/App/assets/7516624/1d43afaf-e4d6-428b-851e-cb1fceb6f87d">

**Comment by shawnborton** [comment] 2023-09-19 00:04
Looks great to me!

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:01
@MaciejSWM anything else needed to get the draft PR into review?

**Comment by MaciejSWM** [comment] 2023-09-29 07:48
Hey, I was OOO and I'm now back at it. The last thing to add is the `nextCheckInReset` - it feels like it should come from the backend side instead of being calculated on the frontend side. I'll talk to @yuwenmemon about that. Also, I'm still waiting for Spanish translations so I'll probably need to bump in slack to get a response.

**Comment by yuwenmemon** [comment] 2023-09-29 08:49
Hey @MaciejSWM I'll actually be heading out on OOO myself for a while starting today. @pecanoro (`rocio` in Slack)  is familiar with this feature and the back-end design and should be able to help you out with whatever you need!

**Comment by yuwenmemon** [comment] 2023-09-29 10:40
> The last thing to add is the nextCheckInReset - it feels like it should come from the backend side instead of being calculated on the frontend side.

@MaciejSWM Yes agreed.

**Comment by joekaufmanexpensify** [comment] 2023-10-02 21:24
Still in progress

**Comment by MaciejSWM** [comment] 2023-10-03 14:29
Update: PR is 98% ready. It's now just waiting for `nextCheckInReset` to be passed from BE to FE and then it's a quick update on FE side and ready for review.

**Comment by pecanoro** [comment] 2023-10-09 15:01
@MaciejSWM I created an internal PR to add the `nextCheckInReset `, I will post here when it gets deployed. Beware that the date is returned in the international format `2023-11-01` so it need to be localized.

**Comment by pecanoro** [comment] 2023-10-12 01:10
@MaciejSWM Changes were deployed, you can use them now!

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:54
Bump @MaciejSWM are you able to work on next steps now?

**Comment by sakluger** [comment] 2023-10-18 00:53
For some reason, I thought that this check-in button had been live for a while, but then noticed my own Lounge Access profile doesn't have the button. How close are we to adding the button?

**Comment by joekaufmanexpensify** [comment] 2023-10-23 14:06
[Bumped in Slack. ](https://expensify.slack.com/archives/C04878MDF34/p1698070005928439)

**Comment by sakluger** [comment] 2023-10-24 19:13
Hey folks, we've decided to pause having guests in the Lounge, so I'm going to close this issue for now since we no longer need a check-in button.

**Comment by sakluger** [comment] 2023-10-24 19:20
Hey folks, we've decided to pause releasing this new button, so I'm going to close this issue for now. I'll follow up if we have additional updates.

**Comment by sakluger** [comment] 2023-10-24 19:25
Aaaaand reopening to handle payments since the PR was completed and was just about to get merged.

**Comment by joekaufmanexpensify** [comment] 2023-11-06 17:04
@pecanoro and I chatted, and since there was a good amount of work done on this issue's [PR](about:blank), @aimane-chnaif is still due some compensation for their work (even though the PR was ultimately closed). @aimane-chnaif we're going to pay $500 here.

**Comment by joekaufmanexpensify** [comment] 2023-11-06 17:06
Old upwork job is closed. New one [here. ](https://www.upwork.com/jobs/~01ee1c62dcd654056a)

**Comment by joekaufmanexpensify** [comment] 2023-11-06 17:07
@aimane-chnaif offer sent for $500!

**Comment by joekaufmanexpensify** [comment] 2023-11-06 19:18
Ah cool. Yeah it is valid. I will pay there and revoke the new offer.

**Comment by joekaufmanexpensify** [comment] 2023-11-06 19:20
@aimane-chnaif $500 sent and contract ended.

**Comment by joekaufmanexpensify** [comment] 2023-11-06 19:21
Closing as this one's all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-11-06 19:21 UTC
Labels: Reviewing, External, Engineering, Weekly, NewFeature, Design
