### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Refactor: Remove `isVisible` prop from `ValidateCodeForm`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#19787] opened 2023-05-30 01:09 UTC
Refer to [this comment](https://github.com/Expensify/App/pull/18679/files#r1209602038)for specifics.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195fcdfcd6d788597</li>
        <li>Upwork Job ID: 1671941653990858752</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-06-12 01:41
will work on this tomorrow (Monday)

**Comment by hayata-suenaga** [comment] 2023-06-22 18:02
I don't time to work o this so I gonna make this issue external 🙇

**Comment by alexpensify** [comment] 2023-06-23 15:53
Ok, thank you for that update!

**Comment by shonsirsha** [comment] 2023-06-23 16:28
Hey 🙂  👋  this seems like a quite straightforward refactoring process - thanks for making it external. I saw another proposal above (before it was made external) but I believe it's incomplete / missing some steps.

 ## Proposal
 ### Please re-state the problem that we are trying to solve in this issue.
 We'd like to remove `isVisible` prop from `ValidateCodeForm` in `SignInPage`. And also from all of its descendant components that are using this `isVisible` prop. In my alternative proposal (bottom), I explain a solution if we don't want to remove `isVisible` completely and only remove it from the `ValidateCodeForm` but keep it in the `BaseValidateCodeForm`
 
 ### What is the root cause of that problem?
Essentially, the `isVisible` prop is not being used. Please refer to [this comment](https://github.com/Expensify/App/pull/18679/files#r1209602038). However, removing the prop only in the component itself will cause the field to not be visible. 

This is due to `ValidateCodeForm`'s descendant (`BaseValidateCodeForm`) has a default value of `isVisible` to be `false`. The `isVisible` value (`false`) in `BaseValidateCodeForm` **comes from the `withToggleVisibilityView` HoC, which we also have to remove from `BaseValidateCodeForm`.**

 ### What changes do you think we should make in order to solve the problem?

The changes will be distributed **across 4 files** as follows.

1. File: `signin/SignInPage.js`. Changes:

```diff
diff --git a/src/pages/signin/SignInPage.js b/src/pages/signin/SignInPage.js
index a875c25359..1b57934902 100644
--- a/src/pages/signin/SignInPage.js
+++ b/src/pages/signin/SignInPage.js
@@ -163,7 +163,7 @@ class SignInPage extends Component {
                         isVisible={showLoginForm}
                         blurOnSubmit={this.props.account.validated === false}
                     />
-                    {showValidateCodeForm ? <ValidateCodeForm isVisible={showValidateCodeForm} /> : <PasswordForm isVisible={showPasswordForm} />}
+                    {showValidateCodeForm ? <ValidateCodeForm /> : <PasswordForm isVisible={showPasswordForm} />}
                     {showResendValidationForm && <ResendValidationForm />}
                     {showUnlinkLoginForm && <UnlinkLoginForm />}
                 </SignInPageLayout>
```

2. File: `signin/ValidateCodeForm/index.js`. Changes:  

```diff
diff --git a/src/pages/signin/ValidateCodeForm/index.js b/src/pages/signin/ValidateCodeForm/index.js
index e60c30bff3..2329f38521 100644
--- a/src/pages/signin/ValidateCodeForm/index.js
+++ b/src/pages/signin/ValidateCodeForm/index.js
@@ -1,25 +1,10 @@
 import React from 'react';
-import PropTypes from 'prop-types';
 import BaseValidateCodeForm from './BaseValidateCodeForm';
 
-const defaultProps = {
-    isVisible: false,
-};
-
-const propTypes = {
-    isVisible: PropTypes.bool,
-};
-function ValidateCodeForm(props) {
-    return (
-        <BaseValidateCodeForm
-            isVisible={props.isVisible}
-            autoComplete="one-time-code"
-        />
-    );
+function ValidateCodeForm() {
+    return <BaseValidateCodeForm autoComplete="one-time-code" />;
 }
 
 ValidateCodeForm.displayName = 'ValidateCodeForm';
-ValidateCodeForm.propTypes = propTypes;
-ValidateCodeForm.defaultProps = defaultProps;
 
 export default ValidateCodeForm;
```
(removing `isVisible` props completely).

3. File: `signin/ValidateCodeForm/index.android.js`. Changes: 

```diff
diff --git a/src/pages/signin/ValidateCodeForm/index.android.js b/src/pages/signin/ValidateCodeForm/index.android.js
index e0258121fa..e3ec3ed4fc 100644
--- a/src/pages/signin/ValidateCodeForm/index.android.js
+++ b/src/pages/signin/ValidateCodeForm/index.android.js
@@ -1,25 +1,10 @@
 import React from 'react';
-import PropTypes from 'prop-types';
 import BaseValidateCodeForm from './BaseValidateCodeForm';
 
-const defaultProps = {
-    isVisible: false,
-};
-
-const propTypes = {
-    isVisible: PropTypes.bool,
-};
-function ValidateCodeForm(props) {
-    return (
-        <BaseValidateCodeForm
-            isVisible={props.isVisible}
-            autoComplete="sms-otp"
-        />
-    );
+function ValidateCodeForm() {
+    return <BaseValidateCodeForm autoComplete="sms-otp" />;
 }
 
 ValidateCodeForm.displayName = 'ValidateCodeForm';
-ValidateCodeForm.propTypes = propTypes;
-ValidateCodeForm.defaultProps = defaultProps;
 
 export default ValidateCodeForm;
```
(also removing the `isVisible` prop).

4. File: `signin/ValidateCodeForm/BaseValidateCodeForm` Changes:

```diff
diff --git a/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js b/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
index edb8a9ac53..4d81832a09 100755
--- a/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
+++ b/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js
@@ -15,7 +15,6 @@ import ChangeExpensifyLoginLink from '../ChangeExpensifyLoginLink';
 import withLocalize, {withLocalizePropTypes} from '../../../components/withLocalize';
 import compose from '../../../libs/compose';
 import * as ValidationUtils from '../../../libs/ValidationUtils';
-import withToggleVisibilityView, {toggleVisibilityViewPropTypes} from '../../../components/withToggleVisibilityView';
 import canFocusInputOnScreenFocus from '../../../libs/canFocusInputOnScreenFocus';
 import * as ErrorUtils from '../../../libs/ErrorUtils';
 import {withNetwork} from '../../../components/OnyxProvider';
@@ -56,7 +55,6 @@ const propTypes = {
     autoComplete: PropTypes.oneOf(['sms-otp', 'one-time-code']).isRequired,
 
     ...withLocalizePropTypes,
-    ...toggleVisibilityViewPropTypes,
 };
 
 const defaultProps = {
@@ -71,7 +69,6 @@ function BaseValidateCodeForm(props) {
     const [twoFactorAuthCode, setTwoFactorAuthCode] = useState('');
     const [timeRemaining, setTimeRemaining] = useState(30);
 
-    const prevIsVisible = usePrevious(props.isVisible);
     const prevRequiresTwoFactorAuth = usePrevious(props.account.requiresTwoFactorAuth);
     const prevValidateCode = usePrevious(props.credentials.validateCode);
 
@@ -80,26 +77,11 @@ function BaseValidateCodeForm(props) {
     const timerRef = useRef();
 
     useEffect(() => {
-        if (!inputValidateCodeRef.current || prevIsVisible || !props.isVisible || !canFocusInputOnScreenFocus()) {
+        if (!inputValidateCodeRef.current || !canFocusInputOnScreenFocus()) {
             return;
         }
         inputValidateCodeRef.current.focus();
-    }, [props.isVisible, prevIsVisible]);
-
-    useEffect(() => {
-        if (!inputValidateCodeRef.current) {
-            return;
-        }
-
-        if (!validateCode) {
-            return;
-        }
-
-        // Clear the code input if magic code valid
-        if (prevIsVisible && !props.isVisible) {
-            setValidateCode('');
-        }
-    }, [props.isVisible, prevIsVisible, validateCode]);
+    }, []);
 
     useEffect(() => {
         if (prevValidateCode || !props.credentials.validateCode) {
@@ -309,6 +291,5 @@ export default compose(
         credentials: {key: ONYXKEYS.CREDENTIALS},
         preferredLocale: {key: ONYXKEYS.NVP_PREFERRED_LOCALE},
     }),
-    withToggleVisibilityView,
     withNetwork(),
 )(BaseValidateCodeForm);
```
(removing the `withToggleVisibilityView` HoC and the unused props).

 
### What alternative solutions did you explore? (Optional)

We might only want to remove `isVisible` from `ValidateCodeForm` in the `SignInPage` but keep the `isVisible` prop in the `BaseValidationCodeForm` (for whatever reason).

If that's the case, we don't need to make any changes in `BaseValidationCode`. Instead, we only need to:

1. Explicitly pass `true` as the `isVisible` prop in the index page (and remove the unused `defaultProps` and `propTypes`).

2. Keep the same changes as above for `signin/SignInPage.js`.


With my two proposal above, I hope we can find one that fits our use-case best. 

Thanks! 🙂

**Comment by shonsirsha** [comment] 2023-06-23 16:35
Contributor details
Your Expensify account email: sean.liesanggoro@code.berlin
Upwork Profile Link: https://www.upwork.com/freelancers/~015644b14a43b1fc70

**Comment by alexpensify** [comment] 2023-06-26 03:56
@rushatgabhane - when you get a chance, can you review this proposal? Thank you!

**Comment by hayata-suenaga** [comment] 2023-06-26 17:23
Assigning @huzaifa-99

**Comment by alexpensify** [comment] 2023-06-27 19:44
Thank you for the update @huzaifa-99!

**Comment by alexpensify** [comment] 2023-06-29 22:25
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back then if it's not closed by then. 

Required action from the 🐛 team: Check on the PR state and it might be ready for payment late next week.

**Comment by hayata-suenaga** [comment] 2023-06-30 16:06
@muttmuure just a memo. The PR has been on hold for a while because of the merge freeze but I left the hold today

**Comment by muttmuure** [comment] 2023-07-03 12:17
No update needed

**Comment by muttmuure** [comment] 2023-07-10 12:35
No update needed

**Comment by alexpensify** [comment] 2023-07-10 21:12
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

@hayata-suenaga are we still on a freeze?

**Comment by hayata-suenaga** [comment] 2023-07-10 23:38
@alexpensify we're waiting for @rushatgabhane's response to [this comment](https://github.com/Expensify/App/pull/21594#issuecomment-1624103232)

**Comment by alexpensify** [comment] 2023-07-12 22:30
@rushatgabhane - any update here: https://github.com/Expensify/App/pull/21594#issuecomment-1624103232

**Comment by rushatgabhane** [comment] 2023-07-13 05:00
on it!

**Comment by alexpensify** [comment] 2023-07-14 18:39
Thanks, we will look out for that update!

**Comment by alexpensify** [comment] 2023-07-16 17:27
Waiting for the update here

**Comment by alexpensify** [comment] 2023-07-18 20:23
Alright, waiting for automation to kick in here.

**Comment by rushatgabhane** [comment] 2023-07-25 14:24
Not a regression. We're just removing dead code.

**Comment by rushatgabhane** [comment] 2023-07-25 14:24
Made a manual request on new dot https://staging.new.expensify.com/r/5866861233909813

**Comment by alexpensify** [comment] 2023-07-25 21:14
@rushatgabhane - thanks for completing the checklist. I'll work on the payment process in Upwork for @huzaifa-99 tomorrow July 26.

**Comment by alexpensify** [comment] 2023-07-26 21:26
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @huzaifa-99 $1000
-  Contributor+ that helped on the issue and/or PR - @rushatgabhane $1000

Upwork Job: https://www.upwork.com/jobs/~0195fcdfcd6d788597

*_If applicable, the bonuses will be applied on the final payment_

Extra Notes regarding payment: This one was held because of the merge freeze, so I believe there is still a payment here. With that said, there will be no urgency bonus.

**Comment by alexpensify** [comment] 2023-07-26 21:38
I'm having trouble with the Upwork job and will complete the process tomorrow.

**Comment by JmillsExpensify** [comment] 2023-07-27 04:41
Reviewed details for @rushatgabhane. This is accurate and approved for payment in NewDot.

**Comment by alexpensify** [comment] 2023-07-27 23:15
@huzaifa-99 - I've sent the payment via Upwork. Please accept and I can complete the required process.

**Comment by alexpensify** [comment] 2023-07-28 20:44
Ok, I've closed the job in Upwork and the payment to @huzaifa-99 has been sent out via Upwork.

**Closed by alexpensify** 2023-07-28 20:44 UTC
Labels: External, Daily, Improvement, Awaiting Payment, Bug
