### ISSUE TITLE
[HOLD for payment 2024-05-30] [Wave Collect] [Xero] [Export Flow] Create the Preferred exporter select page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39742] opened 2024-04-05 16:40 UTC
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.cuxyqos9kurc).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by stephanieelliott** [comment] 2024-04-08 22:19
@lakchote can this be done externally or do we need to pull in an internal engineer for this?

**Comment by lakchote** [comment] 2024-04-10 07:50
> @lakchote can this be done externally or do we need to pull in an internal engineer for this?

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

I've removed the `Help Wanted` label as we do not need proposals for it. 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by stephanieelliott** [comment] 2024-04-10 19:43
Cool, thanks for clarifying!

**Comment by stephanieelliott** [comment] 2024-04-15 21:50
Still held on https://github.com/Expensify/App/issues/39725

**Comment by lakchote** [comment] 2024-04-19 07:03
Double-checking with internal engineers, some might be interested to work on this.

**Comment by stephanieelliott** [comment] 2024-04-23 03:42
Reapplying the `New Feature` label to get another BZ member on this while I am OOO til May 2. Thanks @JmillsExpensify -- this is held on the Xero authorization flow but will be worked on either by SWM or internal engineers (context [here](https://github.com/Expensify/App/issues/39742#issuecomment-2046785196)). Please keep an eye for any movement and I will grab this back from you when I return!

**Comment by lakchote** [comment] 2024-04-30 09:27
Yes, we were on hold for https://github.com/Expensify/App/issues/39725 to be merged.

It was merged yesterday. Technically we are able to work on this now.

I'm going to focus today on [fixing the remaining bugs](https://expensify.slack.com/archives/C01GTK53T8Q/p1714468527496189?thread_ts=1714119216.357459&cid=C01GTK53T8Q) for the Xero authorization flow before working on it.

**Comment by stephanieelliott** [comment] 2024-05-02 16:19
I'm back from OOO, thanks for watching this while I was out @JmillsExpensify! 

Thanks for the update @lakchote! Just want to clarify -- are you going to work on this one yourself, or should we pull in the SWM engineers per the Slack discussion?

**Comment by lakchote** [comment] 2024-05-03 08:33
> I'm back from OOO, thanks for watching this while I was out @JmillsExpensify!
> 
> Thanks for the update @lakchote! Just want to clarify -- are you going to work on this one yourself, or should we pull in the SWM engineers per the Slack discussion?

It will be worked on by @hungvu193

**Comment by trjExpensify** [comment] 2024-05-16 10:55
Deployed to staging yesterday.

**Comment by lakchote** [comment] 2024-05-17 12:14
Assigning @mananjadhav as he'll need to be paid for the C+ review of the linked PR once this hits production and the 7 day regression period passes.

**Comment by stephanieelliott** [comment] 2024-05-21 23:43
PR is still on staging.

**Comment by stephanieelliott** [comment] 2024-05-29 07:20
Looks like the PR deployed to prod last week, will manually update the title/labels for the 7-day hold.

**Comment by stephanieelliott** [comment] 2024-05-30 22:40
I had to manually create a job on Upwork for this

 - [Upwork Job](https://www.upwork.com/jobs/~017aaac0f9f763d071)
 - Offer for @hungvu193: https://www.upwork.com/nx/wm/offer/102533875

**Comment by stephanieelliott** [comment] 2024-05-30 22:41
Summarizing payment on this issue: 

 - Contributor: @hungvu193 $250 via Upwork - OFFER EXTENDED 
 - Contributor+: @mananjadhav $250 due via NewDot 
 
 Upwork job is here: https://www.upwork.com/jobs/~017aaac0f9f763d071

**Comment by trjExpensify** [comment] 2024-05-30 22:58
... ah, we'll handle the payment for this centrally with the guys working on the feature. We can close this out as the regression period is over!

**Comment by stephanieelliott** [comment] 2024-06-01 02:43
Ah cool! Ok Upwork job canceled.

**Closed by stephanieelliott** 2024-06-01 02:43 UTC
Labels: Reviewing, Weekly, NewFeature, Awaiting Payment
