### ISSUE TITLE
Send money - Unexpected error when sending money to a Hidden contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35394] opened 2024-01-30 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM with a Hidden contact ([yonghongkok2+300101@gmail.com](mailto:yonghongkok2+300101@gmail.com)).
2. Click + > Send money.
3. Enter amount and confirm send money.
4. Click on the send money preview.

## Expected Result:
No error will show up.

## Actual Result:
It shows "Unexpected error, please try again later".
Issue is not reproducible when sending money via FAB button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/be438616-0874-41e1-ae22-9726cc4a1e04

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-01-30 12:57
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by cristipaval** [comment] 2024-01-30 15:45
I can't reproduce this one 👀

**Comment by cristipaval** [comment] 2024-01-30 15:46
Ah, wait, there have been some CORS errors, according to the console in the screen recording.

**Comment by bernhardoj** [comment] 2024-01-30 15:57
@cristipaval I can reproduce this, this happens after https://github.com/Expensify/App/pull/32470. If we send money to a Hidden user, the `requestorEmail` here is an empty string.
https://github.com/Expensify/App/blob/cfb6f2c9b36c28ebc1e78189f65c97278cd885aa/src/libs/actions/IOU.js#L2877-L2880

<img width="518" alt="image" src="https://github.com/Expensify/App/assets/50919443/f1bf623b-6cb9-4150-b50f-62b26ea914a8">

<img width="377" alt="image" src="https://github.com/Expensify/App/assets/50919443/0ad0dc14-1484-43db-97b5-1c22c8458b3e">

Before https://github.com/Expensify/App/pull/32470, specifically this [change](https://github.com/Expensify/App/pull/32470/files#diff-7d43f3c3e4decdb0057928e895f456d51c0f4081837edd5e2c4ed7ddd570e274R324), the `requestorEmail` is undefined and JSON.stringify don't include an undefined value.

I think the API doesn't actually need `requestorEmail` as it works fine on prod, so maybe we can remove it. Another option is to keep the `requestorEmail` undefined.

**Comment by cristipaval** [comment] 2024-01-30 16:14
Thanks @bernhardoj , I'll look into this one again soon.

**Comment by francoisl** [comment] 2024-01-30 19:34
So @cristipaval should this be a backend fix? Looks like we'd need to also account for empty strings in [this condition](https://github.com/Expensify/Web-Expensify/blob/8626f1fe756cfe70f05c487c4c1837fb7772dbf6/lib/ReportAPI.php#L4992-L4996).

**Comment by cristipaval** [comment] 2024-01-30 19:38
yes, @francoisl, I was just investigating this and I think it's cleaner to fix it in the backend

**Comment by cristipaval** [comment] 2024-01-30 19:50
aaaaah, and now I understand why I couldn't reproduce initially. I was using the `Pay elsewhere` option to send money.

**Comment by francoisl** [comment] 2024-01-30 19:58
Ok yeah I was inspecting the logs more and comparing a request made to prod vs staging, and indeed, the only difference is that the `requestorEmail` wasn't passed at all on prod, e.g.

production:
```
{"amount":200,"currency":"IDR","requestorAccountID":867656,"comment":"","idempotencyKey":"2d2bf53f-468d-9f9b-f87f-b11f1d302f1d"}
```

staging:
```
{"amount":200,"currency":"IDR","requestorEmail":"","requestorAccountID":16323312,"comment":"","idempotencyKey":"ec2c797e-d121-3036-9634-15d0d043b57c"}
```

Happy to send a PR if you need.

**Comment by francoisl** [comment] 2024-01-30 19:58
Oh cool you already sent one 😄 ⚡

**Comment by cristipaval** [comment] 2024-01-30 20:00
@francoisl Shall I request a CP for the fix? 👀

**Comment by francoisl** [comment] 2024-01-30 20:04
Yeah I think it wouldn't hurt. There was already a Web-E deploy today so the issue might also start happening in production once we deploy NewDot later today.

**Comment by cristipaval** [comment] 2024-02-07 16:08
The fix for this one hit production already

**Closed by cristipaval** 2024-02-07 16:08 UTC
Labels: Reviewing, Engineering, Daily
