### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] iOS - Copy and Download buttons overlap with Next button when app is in Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20138] opened 2023-06-03 23:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in and enter the app
2. Change language to Spanish
3. Go to Seguridad -> Autenticación de dos factores

## Expected Result:
Button should not overlap between each other

## Actual Result:
Copy and Download buttons overlap with Next button when app is in Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/46521de4-048a-49e3-95aa-8c5e689ed23c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb40af209228ca22</li>
        <li>Upwork Job ID: 1666201965044396032</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by faizansahib** [comment] 2023-06-04 11:02
hello

**Comment by faizansahib** [comment] 2023-06-04 11:08
email:faizan.akash99@gmail.com          upwork Profile Link :  https://www.upwork.com/freelancers/faizans50

**Comment by twisterdotcom** [comment] 2023-06-06 21:54
Weird. Yes, I can repro.

**Comment by Santhosh-Sellavel** [comment] 2023-06-07 18:41
@Expensify/design Do we need to fix anything here?

**Comment by shawnborton** [comment] 2023-06-08 17:16
Hmm I don't understand why the buttons/background card area overlap the button like that, but it's definitely a bug. @MonilBhavsar can you take a look at this one since I think you worked on this feature?

**Comment by kbecciv** [comment] 2023-06-08 17:51
It happened on IPhone 7 and 8

**Comment by Santhosh-Sellavel** [comment] 2023-06-08 17:52
@shawnborton We have a proposal above should I wait for @MonilBhavsar here?

**Comment by shawnborton** [comment] 2023-06-08 17:59
Well I'm not sure if we should accept proposals or make the original PR author go back and fix all of this, because it seems like we didn't implement this feature properly.

**Comment by MonilBhavsar** [comment] 2023-06-09 06:08
Looks like this is a case for small screen devices we missed while introducing scroll view [here](https://github.com/Expensify/App/pull/19260).
@BeeMargarida or @thiagobrez could you please us with this issue.

**Comment by thiagobrez** [comment] 2023-06-09 08:58
@MonilBhavsar I'll take a look at this 👌🏻

**Comment by thiagobrez** [comment] 2023-06-09 15:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In Two-Factor authentication CodesPage, when the app is in Spanish and in small screens, the Copy and Download buttons (from page body) overlap with the Next button in the footer

### What is the root cause of that problem?

Footer is included in the page ScrollView, which causes the page to have to contract to fill everything

### What changes do you think we should make in order to solve the problem?


- Move `FixedFooter` outside the `ScrollView`
- Remove `flex1` from the `ScrollView` contentContainerStyle
- Add a little paddingTop to the `FixedFooter`, so when the page scrolls there is a gap between content and footer, so the UI doesn't feel too cluttered
- In the Copy and Download buttons wrapper, render a column instead of row when screen is extra small (Galaxy Fold). **This is a different issue that wasn't seen before** - these buttons were overflowing horizontally in this screen size

<details>
<summary>iPhone 7</summary>
<video src="https://github.com/Expensify/App/assets/26878038/07cc25d4-ddbc-499d-a8af-ac8acd4788ae" />
</details>

<details>
<summary>iPhone 8</summary>
<video src="https://github.com/Expensify/App/assets/26878038/deb2fe84-e41b-4fe4-82a6-2e5604499291" />
</details>

<details>
<summary>iPhone 14</summary>
<video src="https://github.com/Expensify/App/assets/26878038/619c2ed7-ae0a-4bb2-91be-987640c364e8" />
</details>

<details>
<summary>Pixel 5</summary>
<video src="https://github.com/Expensify/App/assets/26878038/95737325-066c-41bc-99ea-c0ebdb18b0c5" />
</details>

<details>
<summary>Galaxy Fold</summary>
<video src="https://github.com/Expensify/App/assets/26878038/224df10d-d49c-47bc-be19-9c048af24e33" />
</details>

**Comment by Santhosh-Sellavel** [comment] 2023-06-09 16:23
@arosiclair @MonilBhavsar 
Looks good to me. cc @shawnborton

**Comment by shawnborton** [comment] 2023-06-09 16:28
Just to make sure I understand, are we paying this out as a new bug with a new fix? Why wouldn't we treat this as a regression and ask the original PR author to fix this?

**Comment by Santhosh-Sellavel** [comment] 2023-06-09 16:33
@shawnborton There is an open issue https://github.com/Expensify/App/issues/19187 it's within the we can handle it there as regression.

**Comment by thiagobrez** [comment] 2023-06-09 16:33
Hey @shawnborton, I'm the original PR author :)

Wasn't sure how the process should go in this case, so I decided to post a proposal anyway

**Comment by shawnborton** [comment] 2023-06-09 16:39
Ah apologies. Okay, I say we treat this like a regression. @MonilBhavsar what's the process for that?

**Comment by thiagobrez** [comment] 2023-06-12 09:26
PR is ready for review here: https://github.com/Expensify/App/pull/20575

**Comment by twisterdotcom** [comment] 2023-06-12 10:12
Okay, we should handle this in the original issue apparently: https://stackoverflowteams.com/c/expensify/questions/8513.

However, that is an overall issue for many bugs, so I prefer keeping it isolated in here, but we'll account for the regression in the payment. I will assign you to this @thiagobrez.

**Comment by mvtglobally** [comment] 2023-06-13 19:02
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment] 2023-06-14 22:24
Is this resolved without the PR then?

**Comment by thiagobrez** [comment] 2023-06-19 07:50
PR is being reviewed here: https://github.com/Expensify/App/pull/20575

**Comment by Santhosh-Sellavel** [comment] 2023-06-28 13:12
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/19260
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/19260#discussion_r1245186159
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This should have been caught in this review based on the checklist
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [x]  [@twisterdotcom] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

We don't need a separate regression test here, this minor Ui polish. Existing cases should be enough. @arosiclair Let me know if you differ on any of the above.

Thanks!

Cc: @twisterdotcom

**Comment by greg-schroeder** [comment] 2023-06-28 23:54
No problem @twisterdotcom - I'll take care of payment once we reach the payment date tomorrow :)

**Comment by greg-schroeder** [comment] 2023-06-29 19:58
Wait actually I'm coming into this a bit late as I didn't managed this issue from the start - are we paying full price for this (but just to C+ for review)? There was some kind of regression here but I'm not certain @arosiclair @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 21:10
@greg-schroeder Better this discussion can happen on Slack or new dot. We can wait for @twisterdotcom, I'm in no rush to collect payments here.

**Comment by greg-schroeder** [comment] 2023-06-29 23:18
Good call, I will open a discussion

**Comment by greg-schroeder** [comment] 2023-06-30 00:07
I sent you an offer @Santhosh-Sellavel for this one... given you're a different reviewer than the initial PR let's just go with the standard payment.

**Comment by greg-schroeder** [comment] 2023-06-30 07:29
awaiting payment acceptance and we can close this out

**Comment by Santhosh-Sellavel** [comment] 2023-07-03 20:20
Not overdue

**Comment by greg-schroeder** [comment] 2023-07-06 08:19
Closing for now as everything else is complete. :)

**Closed by greg-schroeder** 2023-07-06 08:19 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-07 11:54
Paid Santhosh on new Dot.
