### ISSUE TITLE
[Retest][Wave Collect] [Collect approvers] [$500] Web - Expense - After approval, expense status becomes "paid"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34878] opened 2024-01-22 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4208299
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a collect workspace on OD, invite a member as employee and submit a request with that employee. Both the workspace and the employee account should have a bank account setup. 

1. Go to https://staging.new.expensify.com/
2. Log in as the approver of workspace.
3. Go to the chat with the employee that submitted the request and the WS.
4. Open the report.
5. Select and click "Approve".

## Expected Result:
The status of the report should remain as "approved".

## Actual Result:
The status of the report changes to "Paid".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/219bad70-0225-48eb-8637-748a63d4359b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01386ca474157ceadb</li>
        <li>Upwork Job ID: 1749418105696747520</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-22 13:06
We think that this bug might be related to #wave7-collect-approvers
CC @RachCHopkins

**Comment by s-alves10** [comment] 2024-01-22 14:14
Not able to reproduce this

**Comment by isagoico** [comment] 2024-01-24 23:32
Added a precondition to the OC that we missed to include initially: 
> Both the workspace and the employee account should have a bank account setup.

**Comment by strepanier03** [comment] 2024-01-26 20:59
Working on setting up this testing and then will try to repro. 

@s-alves10 - If you take into consideration the pre-condition mentioned [here](https://github.com/Expensify/App/issues/34878#issuecomment-1909098768), can you repro?

**Comment by strepanier03** [comment] 2024-01-31 22:03
I am also really struggling to recreate this. I'm going to close this for now and if someone is able to repro still perhaps you can also update the OP steps to be more clear?

**Comment by kbecciv** [comment] 2024-02-12 19:43
Issue is reproducible!

https://github.com/Expensify/App/assets/93399543/4ad2c7e1-8f3c-4048-a940-1a0800069c7f

**Comment by strepanier03** [comment] 2024-02-12 23:03
Thank you @kbecciv - Tying to a wave/vip now.

**Comment by marcochavezf** [comment] 2024-02-13 16:58
Seems auto-reimbursement is enabled, so seems correct that we're paying the expense automatically.

<img width="803" alt="Screenshot 2024-02-13 at 10 54 33 a m" src="https://github.com/Expensify/App/assets/6829422/80ab8dcb-fe75-4d24-8012-89f6d4af3b10">

I think the problem is that we're not sending the `settling up` report action.

**Comment by marcochavezf** [comment] 2024-02-21 18:21
> @marcochavezf - Are you saying that when testing you could only recreate this if auto reimbursement is enabled and if you test with it disabled this doesn't happen?

Yup, I know it's a bit hairy but that's probably the reason of the edge case 😄 

I'm going to assign myself to investigate today

**Comment by marcochavezf** [comment] 2024-02-21 19:36
I remember we're changing the logic for the Pay button [here](https://github.com/Expensify/App/issues/34951), so we should be on hold for that issue and re-evaluate the bug again here.

**Comment by strepanier03** [comment] 2024-02-26 17:05
Hold GH is still open, will check in again later this week.

**Comment by strepanier03** [comment] 2024-03-11 04:25
HOLD GH is open. Priority for this is polish.

**Comment by strepanier03** [comment] 2024-03-19 21:43
HOLD issue it closed, will retest.

**Comment by marcochavezf** [comment] 2024-03-20 18:47
The other pending GH for the new Pay logic button was closed. I also asked QA team to update the test cases in TR [here](https://expensify.slack.com/archives/C9YU7BX5M/p1709770204110689). I'm going to apply the `retest-weekly` label

**Comment by marcochavezf** [comment] 2024-03-25 17:15
Waiting for testing

**Comment by mvtglobally** [comment] 2024-04-04 03:24
Issue not reproducible during KI retests. (First week)

**Comment by marcochavezf** [comment] 2024-04-07 23:31
Closing it per https://github.com/Expensify/App/issues/34878#issuecomment-2036103833

**Closed by marcochavezf** 2024-04-07 23:31 UTC
Labels: Weekly, Internal, Overdue, Bug, retest-weekly
