### ISSUE TITLE
[$1000] DEV: The search field does not focus when selecting money request participants

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24314] opened 2023-08-09 12:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Mobile web browser at [new.expensify.com](https://new.expensify.com/) (DEV not staging) on Android
2. Click on + icon and select request money option
3. enter amount and click on Next button
4. Notice the search field doesn't maintain focus.

## Expected Result: 
input field should be focused and keyboard should be opened on mobile

## Actual Result: 
keyboard open for a second and hides on mobile, input field does not maintain focus

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome mobile web
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev v1.3.54-13
**Reproducible in staging?:** No
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/587e4697-e112-4c3e-a3a5-5c8fb244f9d4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691037165176299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1f88a241863e6bc</li>
        <li>Upwork Job ID: 1692290423533080576</li>
        <li>Last Price Increase: 2023-08-17</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26270465</li>
<li>gadhiyamanan | Reporter | 26270468</li>
</ul></li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-08-10 16:08
Asking if this will be fixed with https://github.com/Expensify/App/issues/10731

**Comment by Christinadobrzyn** [comment] 2023-08-11 20:26
I can't seem to access Browserstack so I can't test this - asking for some help from the team here - https://expensify.slack.com/archives/C01SKUP7QR0/p1691785217712849

**Comment by Christinadobrzyn** [comment] 2023-08-11 22:08
Can reproduce asking for more testing - https://expensify.slack.com/archives/C049HHMV9SM/p1691791675458309?thread_ts=1691037165.176299&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-08-14 23:53
Still can't reproduce - discussing here - https://expensify.slack.com/archives/C049HHMV9SM/p1692003832058349?thread_ts=1691037165.176299&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-08-15 21:25
Still working on narrowing down the issue - https://expensify.slack.com/archives/C049HHMV9SM/p1692134407829329?thread_ts=1691037165.176299&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-08-17 20:39
I still can't reproduce - I'll follow this slack thread and we can still test but I can't reproduce this - https://expensify.slack.com/archives/C049HHMV9SM/p1692304707462269?thread_ts=1691037165.176299&cid=C049HHMV9SM

**Comment by Swor71** [comment] 2023-08-18 12:31
Hey, I'm Marcin from Callstack - expert contributor group - I would like to help resolve this issue

**Comment by Christinadobrzyn** [comment] 2023-08-18 20:52
Hey @cubuspl42 - let me know if having @Swor71 work on it is good! I can add the engineering label to move this along

**Comment by cubuspl42** [comment] 2023-08-19 14:55
@Christinadobrzyn Sure, let's do that

**Comment by Christinadobrzyn** [comment] 2023-08-22 18:46
Hi @luacmartins - we've decided to have @Swor71 from Callstack work on this. Do we need a proposal first or just start the PR?

**Comment by luacmartins** [comment] 2023-08-22 19:45
No need for a proposal. Gonna assign them to the issue.

**Comment by ayazhussain79** [comment] 2023-08-24 07:54
Anyone able to reproduce this on dev or staging now?

**Comment by gadhiyamanan** [comment] 2023-08-24 08:05
This is reproducible in staging

**Comment by Swor71** [comment] 2023-08-24 12:09
hey, apologies for lack of updates 🙏🏻 , I had some major issues with my setup but managed to sort it out and I am currently looking into this issue

**Comment by jasperhuangg** [comment] 2023-08-24 18:35
This seems to also be happening on other platforms: https://github.com/Expensify/App/issues/25803 I've updated to the OP to reflect this

**Comment by Swor71** [comment] 2023-08-25 11:05
hey, PR for the fix - https://github.com/Expensify/App/pull/25922, it turns out it's a simple change to allow for the transitions to play out before focusing the input

**Comment by situchan** [comment] 2023-09-05 07:31
In this PR, I suggest to fix all pages across the app where auto focus don't work on some platforms as they have the same root cause.
i.e. Select a currency page


https://github.com/Expensify/App/assets/108292595/2f80f7e5-83fb-4bb8-b516-440328612c60

**Comment by situchan** [comment] 2023-09-06 06:59
Why not generalize solution on all pages in this GH?
i.e. we can fix https://github.com/Expensify/App/issues/26380 here

**Comment by cubuspl42** [comment] 2023-09-06 07:31
@situchan From my perspective, because the work on the issue/PR is practically done and we've done it within the original scope.

**Comment by cubuspl42** [comment] 2023-09-15 10:23
@Swor71 @luacmartins

Okey, so it seems that https://github.com/Expensify/App/issues/27202 was a duplicate of https://github.com/Expensify/App/issues/24314 (our issue), which wasn't caught up, and they "outrun" us.

I can't see any other path than closing this issue.

The only thing left out to figure out is the compensation. Speaking directly, I can't see how it's our fault that a duplicate wasn't classified as such. I'm open to hearing other perspectives.

**Comment by Swor71** [comment] 2023-09-15 12:16
@cubuspl42 @luacmartins 

I do agree that there is, realistically, no other course of action than to close this issue.

It's too bad that the dupe was not caught sooner as we've gone through 3 weeks of reviews and then the asked change to the approach just to be beat by one day before the merge :D but I guess that just happens sometimes ;)

Also, since I'm part of Callstack, I believe the compensation part is handled differently and shouldn't be an issue(?)

**Comment by luacmartins** [comment] 2023-09-18 00:48
Yea, I agree. Let's close this issue. Thanks for all the work everyone and sorry it turned out like this.

**Comment by gadhiyamanan** [comment] 2023-09-18 04:32
@Christinadobrzyn @luacmartins this is eligible for reporting bonus because it is reported first

**Comment by luacmartins** [comment] 2023-09-18 07:28
Reopened for reporting bonus payment @Christinadobrzyn

**Comment by Christinadobrzyn** [comment] 2023-09-19 18:04
Sorry, I'm a little lost on this one, are we just paying the reporter? @luacmartins

**Closed** 2023-10-11 15:00 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
