### ISSUE TITLE
[HOLD for payment 2024-12-17] Make Search Input on search results Page behave similarly to SearchRouter

### ISSUE THREAD

**Issue by Kicu** [Expensify/App#53126] opened 2024-11-26 12:14 UTC
Followup after discussion in: https://github.com/Expensify/App/pull/52568

Make the Input on SearchResults Page behave similarly to SearchRouter.
It should show:
 - 5 recent searches same as Router
 - chat rooms/reports working identically to router (navigating to chats when clicked)

Also make `cmd+k` on this Page focus the input instead of displaying Router.

![Screenshot 2024-11-26 at 13 13 06](https://github.com/user-attachments/assets/0cd9c325-cbc1-4164-b22e-a8d69bafc225)

CC @shawnborton @luacmartins 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by shawnborton** [comment] 2024-11-26 12:18
Awesome, thanks!

**Comment by trjExpensify** [comment] 2024-11-26 13:39
Nice, who's taking this one on @Kicu?

**Comment by Kicu** [comment] 2024-11-26 13:52
myself ofcourse! 😁 please assign me 🙏

**Comment by luacmartins** [comment] 2024-11-26 18:24
Done!

**Comment by Kicu** [comment] 2024-12-02 09:58
PR will be ready today.
Recently a lot of people are touching Search simultaneously, and I had a lot of problems resolving conflicts on Friday.

**Comment by rojiphil** [comment] 2024-12-05 17:25
Please also assign me to the issue here. Thanks.

**Comment by luacmartins** [comment] 2024-12-05 17:40
PR merged

**Comment by luacmartins** [comment] 2024-12-10 19:20
PR merged

**Comment by ikevin127** [comment] 2024-12-16 18:28
This had a regression:
- https://github.com/Expensify/App/issues/53823

which was confirmed by author in follow-up PR https://github.com/Expensify/App/pull/53859 description.

**Comment by trjExpensify** [comment] 2024-12-17 12:08
Checklist time please, @rojiphil!

**Comment by rojiphil** [comment] 2024-12-18 02:57
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [x] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: This was a continual work from [this PR](https://github.com/Expensify/App/pull/52568)  

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not Required 

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal

### Precondition:

### Test:
1. Ensure that the central pane is displaying any page other than the `search` page
2. On key-in `Cmd+k`,  verify that the search router is displayed
3. Enter a search text e.g. type:chat from:xyz@xyz.com and press `enter` to open the search page.
4. Verify that the search page shows the search input containing the search text.
5. On key-in `Cmd+k` verify that the focus is shown on the search input.  
6. Key-in `Cmd+k` again and verify that the focus is lost on the search input.
7. Key-in `Cmd+k` again and bring back the focus on the search input.
8. Key-in a search text and press `enter` so that reports are also displayed in search results.
9. Click/Tap a report/workspace in the search result and verify that the central pane is navigated to the selected report/workspace.
10. Navigate back to the `Search` page and key-in the email of a user with whom there was no chat before. 
11. Press `Enter` and verify that the user is navigated to the chat report of the new user.

Do we agree 👍 or 👎

**Comment by rojiphil** [comment] 2024-12-18 02:58
@luacmartins Can we keep the compensation here to $250 after considering the regression? The reasoning is that we did some [awesome](https://github.com/Expensify/App/pull/53198#issuecomment-2520966691) work here and it took more cycles of review than the usual ones to reach there. 
cc @trjExpensify

**Comment by luacmartins** [comment] 2024-12-18 16:50
Yea, I think that's fine

**Comment by trjExpensify** [comment] 2024-12-19 11:34
Sounds good! 

Payment summary as follows: 

- $250 to @rojiphil for the C+ review

Offer sent!

**Comment by rojiphil** [comment] 2024-12-19 11:46
Accepted offer. Thanks @trjExpensify

**Comment by trjExpensify** [comment] 2024-12-19 11:54
Paid, closing!

**Closed by trjExpensify** 2024-12-19 11:54 UTC
Labels: Daily, Awaiting Payment, Bug
