### ISSUE TITLE
[HOLD for payment 2023-06-28] IOS - Bank account- Error message nor displayed for incorrect validation code/ incorrect account number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19923] opened 2023-05-31 23:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

**Scenario 1:**
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Enable staging Web secure server in Account Preferences if disabled
3. Navigate to the add bank account modal
4. Verify the Add bank account modal is displayed with 2 options to add bank accounts (Log in and Manual)
5. Select the Manual method to add a bank account
6. Use the "Pending State Withdrawal Account" credentials (available below)
7. Verify that when you finish the flow - the modal asks for 3 amounts of test transactions
8. Submit three random amounts

**Scenario 2**
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Enable staging Web secure server in Account Preferences if disabled
3. Navigate to the add bank account modal
4. Verify the Add bank account modal is displayed with 2 options to add bank accounts (Log in and Manual)
5. Select the Connect with plaid method to add a bank account
6. On the bank account list select "Chase"
7. You'll be redirected to the "First Platypus Bank"
8. Enter the credentials "user_good / pass_good"
9. Continue until you're redirected to the choose an account screen in NewDot
10. Select the bank account ending in 1111
11. Verify you're redirected to the enter back account details manually (this is a special case for the Chase bank account selection)
12. Enter a incorrect bank account number (e.g 1111222233334444

## Expected Result:
Scenario 1: Verify that you see the following error: The validate code you entered is incorrect, please try again
Scenario 2: Error for entering the wrong bank account and in which number should the bank account end with.

## Actual Result:
No validation error message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.2

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Incorrect validation code**

https://github.com/Expensify/App/assets/43996225/2e54eadc-59e4-45e3-a6a5-e83e8446ce45

**Incorrect account number issue**

https://github.com/Expensify/App/assets/43996225/996a43ea-1b46-449a-9aa6-d75821a5d807

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-05-31 23:49
Hello@AndrewGable  We cannot check the issue in production

**Comment by luacmartins** [comment] 2023-06-01 02:15
The reproducible steps don't match the videos shared. So I'm not sure which one is correct. FWIW I can reproduce what's shown in the video on prod too, so it wouldn't be a blocker. I'm waiting for applause to confirm.

**Comment by AndrewGable** [comment] 2023-06-01 02:36
> I can reproduce what's shown in the video on prod too

I think we should lean on this and investigate it as a normal bug

**Comment by luacmartins** [comment] 2023-06-01 02:38
Sounds good!

**Comment by isagoico** [comment] 2023-06-01 02:44
Uploaded correct videos! Apologies for the confusion with this one

**Comment by kbecciv** [comment] 2023-06-01 11:49
The first scenario: on step 11 error message not displayed for validation.

**TR link https://expensify.testrail.io/index.php?/tests/view/3482503** 

https://github.com/Expensify/App/assets/93399543/64320ec6-4608-4f8b-94f6-0e2469274505

The second scenario: step 19.  error for entering the wrong bank account is not displayed.

**TR link https://expensify.testrail.io/index.php?/tests/view/3482507**


https://github.com/Expensify/App/assets/93399543/5313c1d9-5b2b-4a68-bb2c-56db0cc10753

**Comment by luacmartins** [comment] 2023-06-01 15:04
Hm this is looking like a regression from my Form hook refactor PR - https://github.com/Expensify/App/pull/19633. But I tested this flow thoroughly and didn't have any issues. I'll check again.

**Comment by robertjchen** [comment] 2023-06-02 13:36
yup, thanks!! 🙇

**Comment by tjferriss** [comment] 2023-06-12 05:19
@luacmartins looks like you've got a PR up for this. Do you expect to complete it this week?

**Comment by luacmartins** [comment] 2023-06-12 16:51
Yea, it's actively being reviewed. Hopefully, we'll get it merged soon.

**Comment by luacmartins** [comment] 2023-06-21 16:24
Checklist complete

**Comment by luacmartins** [comment] 2023-06-29 23:30
Waiting on payment

**Comment by luacmartins** [comment] 2023-07-04 18:31
@tjferriss did we pay @rushatgabhane for the PR review?

**Comment by tewodrosGirmaA** [comment] 2023-07-04 21:25
Hello @luacmartins , I've noticed that the application doesn't display an error message when we input "XXXXX6789" as the account number. In my testing scenario, this seems to be a unique case. Before closing this issue, I kindly request you to take a look at our conversation on Slack: [Slack Conversation Link](https://expensify.slack.com/archives/C049HHMV9SM/p1688391230054399). It might provide some helpful insights. Thank you!

**Comment by luacmartins** [comment] 2023-07-05 14:54
Replied in thread

**Comment by luacmartins** [comment] 2023-07-10 18:03
@rushatgabhane did the manual request go through?

**Comment by tjferriss** [comment] 2023-07-12 06:16
I just sent @rushatgabhane an offer: https://www.upwork.com/jobs/~013d27f378e338aa91.

Sorry for the delay, I should have re-assigned before heading out on vacation.

**Closed** 2023-07-12 15:25 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
