### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000] Android - Keyboard jumps when clicking on `fix the errors` after entering incorrect contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20507] opened 2023-06-09 11:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Profile -> Contact method -> New contact method
4. Enter the incorrect contact method and press Add
5. Click on `fix the errors` several times

## Expected Result:
Keyboard NOT jumps

## Actual Result:
Keyboard jumps

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d9a6b317-31c5-4b07-adb4-cbe9edfd069b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5b60de07da8f65b</li>
        <li>Upwork Job ID: 1668348877574615040</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by payal-lathidadiya** [comment] 2023-06-09 12:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard jumps when clicking on fix the errors after entering incorrect contact method. 

### What is the root cause of that problem?
This is happening because on click of link "fix the errors", we are explicitly dismissing the keyboard [here](https://github.com/Expensify/App/blob/main/src/components/Form.js#L338) without checking if element is already focused. This causes jump and flickering as keyboard closes and opens again.
 
### What changes do you think we should make in order to solve the problem?
We should not already dismiss/close the keyboard if it's already visible.

So, we can update logic in `onFixTheErrorsLinkPressed` in `Form` component to only dismiss keyboard when keyboard is not visible

```js
if(!Keyboard.isVisible) {
    // Start with dismissing the keyboard, so when we focus a non-text input, the keyboard is hidden
    Keyboard.dismiss();
}
```

### What alternative solutions did you explore? (Optional)
None

**Comment by stephanieelliott** [comment] 2023-06-12 20:06
Moving to `External`, looks like we already have a proposal in the scrollback

**Comment by mmaleiter** [comment] 2023-06-13 19:49
# Proposal

Like @payal-lathidadiya identified, the root cause is that clicking on the TextLink triggers a keyboard dismiss and 
than the focus of the text input is requested again. 

My solution also would take place in the definition of onFixTheErrorsLinkPressed and would be a chance of the control logic in this function body.

Please tell me if you need more details, I would be happy to contribute and score the upwork job. :-)

**Comment by mmaleiter** [comment] 2023-06-13 19:57
Contributor details
Your Expensify account email: mmaleiter+8@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b2c012d993acbf21

**Comment by cubuspl42** [comment] 2023-06-13 21:59
> cc @cubuspl42 Could you please take a look at this issue? The keyboard dismissal was introduced in this commit [c1afb95](https://github.com/Expensify/App/commit/c1afb956cdc1b1cfcfdf8ae5d739f22cb29f7b5a). It seems that it was implemented as a workaround to blur non-input components. Am I correct in my understanding? Is it possible to simply remove it?

The mentioned commit is a reaction to the PR review; the reviewer suggested that the `Keyboard.dismiss()` is shorter while doing the same thing.

While reverting that commit literally doesn't fix the currently discussed issue, something similar could do the job!

**Comment by cubuspl42** [comment] 2023-06-13 22:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The keyboard unexpectedly jumps when pressing the "Fix the errors" button after inputting incorrect contact information. 

### What is the root cause of that problem?

The [`Keyboard.dismiss()` invocation in the `Form` component](https://github.com/Expensify/App/blob/b089bde1dcc506adab2c90659769b08a879ce045/src/components/Form.js#L339) is intended to hide the keyboard open for a previously focused text input, when the non-text input (especially a picker) is being focused.

The code, as written, is unfortunately also fired in the specific case when the text input we want to focus is already focused, resulting in the discussed unexpected behavior.

### What changes do you think we should make in order to solve the problem?

I suggest modifying the mentioned logic so it's closer to the original intention. Let's blur other inputs than the one we want to focus.

Instead of the unconditional...

```js
Keyboard.dismiss();
```

...let's do...

```js
// Blur other inputs
_.values(inputRefs.current).forEach((input) => {
    if (input !== focusInput && input.blur && typeof input.blur === 'function') {
        input.blur();
    }
});
```

**Comment by mmaleiter** [comment] 2023-06-14 07:39
@fedirjh I think my solution also covers the case of dismissing outside. I will test the case you mentioned.

**Comment by mmaleiter** [comment] 2023-06-14 09:15
@fedirjh Thank you for pointing out and explaining the details. 

https://github.com/Expensify/App/assets/109748065/a21ad78b-9586-438e-ad5f-eaddde758aa8

**Comment by mmaleiter** [comment] 2023-06-14 11:37
@fedirjh  my approach would take place in the definition of onFixTheErrorsLinkPressed in Form.js
and would be a change of the control logic of visibility and dismiss. No introduction of state or something similar.
Here is a video how the implementation would work on two screens.

Uploading output_file_2.mov…

**Comment by payal-lathidadiya** [comment] 2023-06-14 18:35
@fedirjh you're correct. the change I proposed may cause regression to other behavior with picker select.

## Proposal
Update to previous [proposal](https://github.com/Expensify/App/issues/20507#issuecomment-1584528914) 
### What changes do you think we should make in order to solve the problem?
Instead, below is new solution
Call `Keyboard.dismiss()` only when focus element is picker
```js
if(focusInput.picker) {
    Keyboard.dismiss();
}
```

### What alternative solutions did you explore? (Optional)

Alternatively, we could blur all other elements except `focusInput` instead of dismissing keyboard.
```js
// Proactively blur all inputs, as on Native we can't expect that all the inputs we'd like
// to focus actually supports focusing or that their focus method blurs other inputs
// Blur other inputs
_.values(inputRefs.current).forEach((input) => {
    if (input !== focusInput && input.blur && typeof input.blur === 'function') {
        input.blur();
    }
});
```

**Comment by mmaleiter** [comment] 2023-06-16 09:11
@fedirjh Thanks for your reply. I am just a newby here getting familiar with how working together works here. 

I would delete lines 338 and 339 and change the code block starting at 349 to 

```javascript
                            // Focus the input after scrolling, as on the Web it gives a slightly better visual result
                            if (focusInput.focus && typeof focusInput.focus === 'function') {
                                if(!Keyboard.isVisible()) {
                                    focusInput.focus();
                                }
                                else {
                                    Keyboard.dismiss();
                                }
                            }
```
Code seems to be the clearest explanation. ;-) 

I tested it on the android app and android chrome browser.

I think this solution cleans up the work around and applies the missing logic, 
by only requesting the focus if it not already focused and dismissing the Keyboard otherwise.

**Comment by payal-lathidadiya** [comment] 2023-06-16 13:41
> @payal-lathidadiya your solution is a duplicate of @cubuspl42 [proposal](https://github.com/Expensify/App/issues/20507#issuecomment-1590126582)

Awh yeah, I could see overlap with solution already proposed. 

However that's part of alternate approach i suggested. The other solution to dismiss keyboard only when focus input is picker will work as expected.

**Comment by payal-lathidadiya** [comment] 2023-06-16 13:43
> @payal-lathidadiya your solution is a duplicate of @cubuspl42 [proposal](https://github.com/Expensify/App/issues/20507#issuecomment-1590126582)

@fedirjh 
Awh yeah, I could see overlap with solution already proposed.

However that's part of alternate approach i suggested. The other solution to dismiss keyboard only when focus input is picker will work as expected.

**Comment by mmaleiter** [comment] 2023-06-19 08:47
@fedirjh Thank you for your answer. As I understood the requirement, the keyboard should close when touch outside a text input and scroll. I will have a look and check if there is an integration of this case.  Only scroll and not dismiss.

**Comment by mmaleiter** [comment] 2023-06-19 09:50
Hello @fedirjh, 
I think now all cases should be covered by using this code.
 // Focus the input after scrolling, as on the Web it gives a slightly better visual result
                            if (focusInput.focus && typeof focusInput.focus === 'function' && isMobileDevice) {
                                if(!Keyboard.isVisible()) {
                                    focusInput.focus();
                                }
                                else if( focusInput.type !== "TextInput"){
                                    Keyboard.dismiss();
                                }
                            }

**Comment by mmaleiter** [comment] 2023-06-19 10:02
@fedirjh  So now I think everything should be coverred. Hopefully :-)

```
                            // Focus the input after scrolling, as on the Web it gives a slightly better visual result
                            if (focusInput.focus && typeof focusInput.focus === 'function' && isMobileDevice) {
                                if(!Keyboard.isVisible()) {
                                    focusInput.focus();
                                }

                            } else {
                                Keyboard.dismiss();
                            }

```

**Comment by payal-lathidadiya** [comment] 2023-06-19 13:02
> @payal-lathidadiya your solution is not working for me.

Thanks @fedirjh for taking out time to review and test this.

did you mean this solution not working?
```js
if(focusInput.picker) {
    Keyboard.dismiss();
}
```

As I tested, it seems to work as expected. 

https://github.com/Expensify/App/assets/130229379/bc05f359-5ca3-4ee4-9415-10c833753301

**Comment by payal-lathidadiya** [comment] 2023-06-19 15:09
> > With my updated proposal [#20507 (comment)](https://github.com/Expensify/App/issues/20507#issuecomment-1591792155), it considered the scenario you identified and working correctly.
> 
> @payal-lathidadiya Please test the scenario that I've mentioned , your proposal will work only for text input , here is your proposal didn’t worked for the picker select
> 
>  Simulator.Screen.Recording.-.iPhone.14.-.2023-06-19.at.14.59.24.mp4

@fedirjh seems to be some confusion here.

with my new proposal [here](https://github.com/Expensify/App/issues/20507#issuecomment-1591792155), it would work correctly for select picker as well. 

Here is test result;
https://github.com/Expensify/App/assets/130229379/bc05f359-5ca3-4ee4-9415-10c833753301

Let me know if I'm missing anything .

**Comment by payal-lathidadiya** [comment] 2023-06-20 07:20
> @payal-lathidadiya did you tested your solution with IOS ?

Hmm, seems like some issue with iOS. I'll look into further investigation.

**Comment by mmaleiter** [comment] 2023-06-20 10:03
@fedirjh I guess I found a solution that satisfies all requirements. I did not fully test it and will do that now and post the results.

```
                        onFixTheErrorsLinkPressed={() => {
                            const errorFields = !_.isEmpty(errors) ? errors : props.formState.errorFields;
                            const focusKey = _.find(_.keys(inputRefs.current), (key) => _.keys(errorFields).includes(key));
                            const focusInput = inputRefs.current[focusKey];

                            // We subtract 10 to scroll slightly above the input
                            if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function') {
                                // We measure relative to the content root, not the scroll view, as that gives
                                // consistent results across mobile and web
                                focusInput.measureLayout(formContentRef.current, (x, y) => formRef.current.scrollTo({y: y - 10, animated: false}));
                            }

                            _.values(inputRefs.current).forEach((input) => {
                                if (input === focusInput && input.blur && typeof input.blur === 'function' && !errorFields.hasOwnProperty(focusKey)) {
                                    input.blur();
                                }
                            });

                            const shouldFocus = !(focusInput.type === TextInput && errorFields.hasOwnProperty(focusKey));
                            // Focus the input after scrolling, as on the Web it gives a slightly better visual result
                            if (focusInput.focus && typeof focusInput.focus === 'function') {
                                if(!Keyboard.isVisible || ( Keyboard.isVisible && shouldFocus)) {
                                    focusInput.focus();

                                }
                            }
                        }}

```

**Comment by tjferriss** [comment] 2023-06-22 05:16
@fedirjh what do you think of this latest proposal?

**Comment by cubuspl42** [comment] 2023-06-23 12:41
> I think we have a simple solution , we can just dismiss the keyboard on the `BasePicker` focus method.

You're right, that should work! As this isn't really a part of any proposal yet, as far as I can tell, I updated mine so it includes this, labeled as "Approach 2". I hope this is fine.

## Proposal
[Updated](https://github.com/Expensify/App/issues/20507#issuecomment-1590126582)

**Comment by cubuspl42** [comment] 2023-06-23 12:57
@Nodebrute 

It's his solution with an extra observation that it works if `Checkbox` is updated accordingly, yes.

**Comment by cubuspl42** [comment] 2023-06-23 14:53
> > Please note that this might require a minor update to the Checkbox class, probably fixing #12508 as a side-effect.
> 
> @cubuspl42 Why is this needed for this issue? How is that related to the suggested changes, as it will not affect the Checkbox component?

@fedirjh 

I haven't tested this, to be honest, I just assumed that. I'm a bit busy right now, but I could try testing this scenario later today.

Currently, the line which we discuss in `Form`...

```js
// Start with dismissing the keyboard, so when we focus a non-text input, the keyboard is hidden
Keyboard.dismiss();
```

...has a comment saying _when we focus **a non-text** input_. I wrote that comment. "Non-text" input includes checkboxes. When you forget about an obligatory checkbox in a form while a text input is focused, you'd like to hide the keyboard, analogically to the picker. It's the reason `Keyboard.dismiss();` landed in `Form` in the first place. But as it causes visual problems, as we're aware now, we can move the responsibility of hiding the keyboard to non-text inputs' `focus` method.

Currently, `Checkbox` on Native forwards to `Pressable`, for no particular reason I believe. We could implement `focus` there explicitly, as we do in `BasePicker` (and hide a keyboard in that method).

This will, kind of accidentally, fix an exception being thrown on iOS when you try to call `focus` on `Pressable`, because `Pressable`'s `focus` throws an exception on iOS (at least it used to). That's what https://github.com/Expensify/App/issues/12508 is about.

**Comment by cubuspl42** [comment] 2023-06-23 15:02
> @cubuspl42 that's a separate issue and is closed for good reasons. It has nothing to do with dismissing keyboard.

@Nodebrute

It was closed with reasoning like "this exception flying around doesn't _seem_ to break anything now, let's leave this as it is". While I'm aware that it sometimes happens in software engineering, and I've done that myself a few times, I wouldn't call this _good reasons_. It definitely won't hurt actually fixing this, if a solution is aligned with the goals of this issue.

**Comment by Beamanator** [comment] 2023-06-27 07:59
Hey @Nodebrute :D Next step was getting you assigned! I agree with @fedirjh that your proposal looks great, so please let us know when to expect a PR, thanks! 🙏 👍

**Comment by stephanieelliott** [comment] 2023-07-05 19:59
Hey @fedirjh can you please complete the BugZero checklist above so we can issue payment tomorrow? Thanks!

**Comment by stephanieelliott** [comment] 2023-07-07 04:38
@Nodebrute I just sent you the offer in Upwork, please accept and I will issue the payment + speed bonus ASAP! 
@fedirjh extended an offer to you as well, please accept when you get a chance!

**Comment by stephanieelliott** [comment] 2023-07-07 05:13
Awesome, issued the payment to you in Upwork @Nodebrute!

**Comment by Beamanator** [comment] 2023-07-10 10:36
@fedirjh did you accept the upwork offer?

**Closed** 2023-07-11 01:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
