### ISSUE TITLE
[$500] Room - Room name field is not populated with existing room name in room name editor

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30504] opened 2023-10-27 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing:** PR https://github.com/Expensify/App/pull/29771

**Version Number:** v1.3.92-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Precondition: User has a room.
1. Go to staging.new.expensify.com
2. Go to any room.
3. Click on the room header > Settings.
4. Click on Room name.

## Expected Result:
The existing room name will be populated in the room name field.

## Actual Result:
The room name field is not populated.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/c0e46adb-f095-469e-bf01-76416a6eb6ef

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113de9bd7f3295ef2</li>
        <li>Upwork Job ID: 1717881275782803456</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-10-27 12:44
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The room name field isn't initialized with the current name of the room

### What is the root cause of that problem?
While the current name is passed down via the defaultValue prop, it isn't passed through RoomNameInput to InputWrapper

### What changes do you think we should make in order to solve the problem?
We can accept defaultName as a prop in RoomNameInput and initialize the value of InputWrapper to defaultName

What alternative solutions did you explore? (Optional)
N/A

**Comment by dangrous** [comment] 2023-10-27 14:32
This is a quick fix but we may be reverting the PR that caused it (#28877) so holding for now.

**Comment by brianmuks** [comment] 2023-10-27 14:33
Please re-state the problem that we are trying to solve in this issue.
 Room name field is not populated with existing room name in room name editor
What is the root cause of that problem?
room name is not being passed to the input as the `defaultVlaue` 
Notice that `defaultVlaue`  is missing . 
https://github.com/Expensify/App/blob/49bc03bca208ac6503291640215104ece3098751/src/components/RoomNameInput/index.js#L9

What changes do you think we should make in order to solve the problem?
we should include `defaultValue` as a passed prop. 

`function RoomNameInput({...,defaultValue}) {`

What alternative solutions did you explore? (Optional)
N/A

**Comment by luacmartins** [comment] 2023-10-27 18:13
We're reverting the offending PR

**Comment by luacmartins** [comment] 2023-10-27 18:59
We can close this issue since we're CPing the revert

**Closed** 2023-10-27 18:59 UTC
Labels: External, Engineering, Hourly, Help Wanted, Bug
