### ISSUE TITLE
Room - Unable to type anything in the search field in Members page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51664] opened 2024-10-29 14:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+dsjsidjsio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a room
3. Invite 8 members to the room
4. Click on the room chat header
5. Click Members
6. Enter anything on the search field

## Expected Result:
User should be able to type in the search field in Members page

## Actual Result:
User is unable to type anything in the search field in Members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/7e772bba-8792-4eda-b0f5-c8572b060418

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-29 14:14
Production:

https://github.com/user-attachments/assets/dccfef5d-478f-4e98-bb90-11e4b8825b3c

**Comment by bondydaa** [comment] 2024-10-29 15:50
nothing stands out to me from the checklist immediately, trying to dive in deeper on a few to see if they're related.

**Comment by bondydaa** [comment] 2024-10-29 15:59
i believe this is the component https://github.com/expensify/app/blob/main/src/pages/RoomMembersPage.tsx

**Comment by bondydaa** [comment] 2024-10-29 16:18
the search input only shows when there are 8 or more based on this logic https://github.com/Expensify/App/blob/65fa00a002b3603d335e9a3180b10d6fa365cd58/src/pages/RoomMembersPage.tsx#L195

but the PR that added that has been live for months (and should be on prod already) so it makes me think there is something within one of the nested/base components of `SelectionListWithModal` that might have changed but even there I don't really see any recent, staging only changes for `SelectionList` or `BaseSelectionList`

**Comment by bondydaa** [comment] 2024-10-29 16:27
asked for help here https://expensify.slack.com/archives/C01GTK53T8Q/p1730219259911659?thread_ts=1730210923.463089&cid=C01GTK53T8Q

i need to focus on other tasks for now.

**Comment by bondydaa** [comment] 2024-10-29 18:56
Thanks @grgia for https://github.com/Expensify/App/pull/51684, just merged that. requesting a CP now.

**Comment by bondydaa** [comment] 2024-10-29 19:25
i tested on staging and seems to be working. 

https://github.com/user-attachments/assets/062e0269-9e04-4073-881c-f2c1346e33ca

asked for QA to retest as we 🙏

**Comment by kavimuru** [comment] 2024-10-29 21:26
Tester can still reproduce in #announce room but not in the other rooms.

https://github.com/user-attachments/assets/b5ea9734-dce7-4a1e-bc17-feaba84a7af8

**Comment by bondydaa** [comment] 2024-10-29 21:35
ah I see why, looks like that is using this page https://github.com/expensify/app/blob/main/src/pages/ReportParticipantsPage.tsx which is very similar to https://github.com/expensify/app/blob/main/src/pages/RoomMembersPage.tsx which is what we already fixed. I think the fix is the same thing as i see the `debouncedState` in the `ReportParticipantsPage` file.

**Comment by bondydaa** [comment] 2024-10-29 22:13
new PR here https://github.com/Expensify/App/pull/51702

**Comment by bondydaa** [comment] 2024-10-29 22:28
i'll be signing off shortly, left a note for beaman in the #deployer channel about this one. i believe we just need to review, merge, CP https://github.com/Expensify/App/pull/51702 to fix this.

**Comment by bondydaa** [comment] 2024-10-30 16:56
bumped the qa thread to retest this again since most recent fix has been CP'd so this should be fixed https://expensify.slack.com/archives/C9YU7BX5M/p1730307374065539?thread_ts=1730229556.632319&cid=C9YU7BX5M

**Comment by kavimuru** [comment] 2024-10-30 19:12
Not reproducible

https://github.com/user-attachments/assets/8dee551c-4e00-4ac1-a537-2632c15dcd1b

**Closed** 2024-10-30 20:45 UTC
Labels: Reviewing, Engineering, Weekly

**Comment by suneox** [comment] 2024-12-20 16:29
Hi @bondydaa I've reviewed [this PR](https://github.com/Expensify/App/pull/51702#issuecomment-2445638105), so can I receive any offer? Thanks!
