### ISSUE TITLE
[$500] Personal Details - Special characters like colon displays no results found in search at start

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30207] opened 2023-10-23 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698066379419069

## Action Performed:
1. Open the app
2. Open settings->profile->personal details->address
3. Select united states in country
4. In state, type colon or similar special characters, observe that it triggers no result found
5. Type letters after colon and observe that now search displays result
6. Type colon in between the text and observe that it does nothing

## Expected Result:
pp should not trigger No result found on state search when searched using special characters like colon as search is not affected with the terms in middle and it works find in timezone which has similar search logic

## Actual Result:
App triggers No result found on state search when we use just 1 special character in start

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/f0306309-2ffd-41a4-b411-55646acc066d

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/a626b6f1-d12f-49a4-9547-5ec47cc0e2c5

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/5a384f7d-7ff1-40fd-b598-9bc47f33c4ea

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/a61015bc-9a35-434a-ac6c-9b6c7d9d3f69

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/cc1a3d4a-a8f0-4d39-ad97-5f5ea0977e07

https://github.com/Expensify/App/assets/93399543/5aec2744-2bba-472b-a0de-7887ed8f4fd2

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/15c57bf8-f397-44a1-8d9d-550babdd219d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/93399543/1ee94715-2287-452e-a522-534189501c59

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019505524c8d3b076e</li>
        <li>Upwork Job ID: 1716557636652843008</li>
        <li>Last Price Increase: 2023-10-30</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-10-23 20:55
Related to: https://github.com/Expensify/App/issues/29826

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The country search page doesn't properly search using non-latin characters

### What is the root of the issue
Items in the array of countries being searched get sanitized with the StringUtils.sanitizeString() function which:
"Removes diacritical marks and non-alphabetic and non-latin characters from a string."

This obviously removes the capability to search using special characters.

The same function is also run on the search term being used to search the array of countries.

What changes do you think we should make in order to solve the problem?
Create a function which sanitizes strings without stripping them of their special characters. This could be done by creating a new regex in the const file. Apply that function to the searchTerm and the items in the array of countries.

### What alternative solutions did you explore? (Optional)
NA

**Comment by graylewis** [comment] 2023-10-23 21:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The app shows no results found when special characters are typed in the search instead of showing the full list of countries, like the behavior is on the timezone search.

### What is the root cause of that problem?
Instead of returning the full list of countries when the sanitized search string is empty, it returns an empty array.

```
    const trimmedSearchValue = StringUtils.sanitizeString(searchValue);
    if (!trimmedSearchValue) {
        return [];
    }
```

### What changes do you think we should make in order to solve the problem?
Like when the search value is empty, we just return the full list of countries:
```
    const trimmedSearchValue = StringUtils.sanitizeString(searchValue);
    if (!trimmedSearchValue) {
        return [];
    }
```

**Comment by sourcecodedeveloper** [comment] 2023-10-25 18:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When searching country or state using special characters displays no results.

### What is the root cause of that problem?
The search filter function searchCountryOptions() removes special characters and returns an empty array unlike in timezone search.

### What changes do you think we should make in order to solve the problem?
The timezone selector is able to filter special characters. 

const searchWords = searchValue.toLowerCase().match(/[a-z0-9]+/g) || [];
const searchResults = _.filter(countryStates, (tz) =>
    _.every(
        searchWords,
        (word) =>
            tz.text
                .toLowerCase()
                .replace(/[^a-z0-9]/g, ' ')
                .indexOf(word) > -1,
    ),
);
    

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-10-30 16:44
Hey @0xmiroslav any feedback on the proposals?

**Comment by iwiznia** [comment] 2023-10-30 17:53
Hmmm how is this a bug? If you search for `:ar` and there's no state with that name (since no state has a colon in the name) then we show the no results page, seems correct to me. 

@stephanieelliott what are your thoughts?

**Comment by iwiznia** [comment] 2023-10-30 18:02
The description says:
> pp should not trigger No result found on state search when searched using special characters like colon as search is not affected with the terms in middle and it works find in timezone which has similar search logic


And the solution is also showing data when searching for `:al`...

I am confused...

**Comment by iwiznia** [comment] 2023-10-30 18:13
I don't think this is really a bug or if it is that's worth fixing it. But will wait for @stephanieelliott to chime in about that.

Regarding the cause/solution, we already sanitize the input [here](https://github.com/Expensify/App/blob/main/src/libs/searchCountryOptions.ts#L21) when calling [sanitizeString](https://github.com/Expensify/App/blob/main/src/libs/StringUtils.ts#L10) shouldn't the change be somewhere around that code, especially since it is already replacing the non latin characters there?

**Comment by sourcecodedeveloper** [comment] 2023-10-30 18:15
@iwiznia may have point.  @0xmiroslav shouldn't the regex be fixed in that case. not just return the entire list. The timezone selector is not affected because it matches on /[a-z0-9]+/g. If you are worried keeping sanitizeString, then it can be kept and also matched against the timezone regex and then that should work as well.

**Comment by sourcecodedeveloper** [comment] 2023-10-30 19:38
> I also thought `:` itself should show nothing but it's weird that adding another letter next to it (i.e. `:a`) shows result.

@0xmiroslav I understand your point about sanitize. I also agree that ":" or special characters should show nothing if used along side letters e.g. ":ar". I have updated proposal so it checks for special characters and early returns if necessary i.e. not show anything for ":ar"

**Comment by graylewis** [comment] 2023-10-31 00:34
@iwiznia In and of itself, I wouldn't say that searching with only a special character and returning no results found is a bug. The issue is that this behavior isn't consistent with other similar search interfaces on the site, like the Timezone search that the reporter mentions. It's possible that the Timezone search might need to be updated instead if this is the intended behavior, in which case the solution would be to edit the `filterShownTimezones` function in the `TimezoneSelectPage` component:

```
    const filterShownTimezones = (searchText) => {
        setTimezoneInputText(searchText);
        const searchWords = searchText.toLowerCase().match(/[a-z0-9]+/g) || [];
        setTimezoneOptions(
            _.filter(allTimezones, (tz) =>
                _.every(
                    searchWords,
                    (word) =>
                        tz.text
                            .toLowerCase()
                            .replace(/[^a-z0-9]/g, ' ')
                            .indexOf(word) > -1,
                ),
            ),
        );
    };
```

The fucntion would need to be updated to return an empty array if searchWords (the sanitized searchText split into words) is an empty array

**Comment by iwiznia** [comment] 2023-10-31 12:18
> The issue is that this behavior isn't consistent with other similar search interfaces on the site, like the Timezone search that the reporter mentions

Seems like the only place not calling sanitize is the timezone search, so if we were to update anything, it would be that so that it matches the rest of the code, no?

Anyway, I still want to hear from @stephanieelliott because I think we should do nothing.

**Comment by sourcecodedeveloper** [comment] 2023-10-31 12:39
The sanitize is being called for country selector to handle diacritic characters. The timezone selector does not need to handle diacritic characters and therefore probably does not need calling sanitize. What seems appropriate to resolve as bug is handling the ":ar" searchValue, if any special characters are entered in the country search then return early with no results. 
If not the ":ar" then I agree the issue can be closed.

**Comment by stephanieelliott** [comment] 2023-11-01 06:15
I agree with @iwiznia, even if this is a bug I do think this feels pretty low value. I think doing nothing is a good move here -- gonna close

**Closed by stephanieelliott** 2023-11-01 06:15 UTC
Labels: External, Daily, Help Wanted, Bug
