### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000] Web - Connect bank account- No sign is shown to indicating the account number and routing number can't be changed on Connect bank account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25577] opened 2023-08-21 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Select a workspace and access "Connect Bank Account."
3. Proceed to Step 3 out of 5.
4. Return to the Connect bank account(Step 1).
5. Notice that the account number and routing number can't be changed and no sign is shown indicating they can't be changed

## Expected Result:
A sign is shown indicating they can't be changed

## Actual Result:
No sign is shown indicating they can't be changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9fb53e2a-d2e5-45af-b686-3cc2052831a4

https://github.com/Expensify/App/assets/115492554/42f9da9e-d0dc-4d0b-b0b6-75f0477a2077

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1691728690907359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0584ef975154c77</li>
        <li>Upwork Job ID: 1694056060363059201</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>himanshuragi456 | Contributor | 26326916</li>
<li>daveSeife | Reporter | 26326918</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-08-21 12:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Connect bank account- No sign is shown to indicating the account number and routing number can't be changed on Connect bank account
### What is the root cause of that problem?
`disabled` prop is passed to `TextInput` in routing number account number here:
https://github.com/Expensify/App/blob/12bd6a7f23dd16141e57c2abe83d4e274a5f3737/src/pages/ReimbursementAccount/BankAccountManualStep.js#L106
### What changes do you think we should make in order to solve the problem?
We should update `TextInput` to have `cursor: not-allowed` when `disabled` prop is true.

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-08-23 03:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Connect bank account- No sign is shown to indicating the account number and routing number can't be changed on Connect bank account

### What is the root cause of that problem?
We don't add the cursor style for text input and checkbox. I think the user isn't allowed to click the checkbox

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/79ea92345e48599d6663ef20213f8c64bb0568c1/src/pages/ReimbursementAccount/BankAccountManualStep.js#L97
https://github.com/Expensify/App/blob/79ea92345e48599d6663ef20213f8c64bb0568c1/src/pages/ReimbursementAccount/BankAccountManualStep.js#L110

In 2 inputs here, we should add this style
```
inputStyle={[shouldDisableInputs && styles.cursorDisabled]}
```

We also add this style to checkbox here
https://github.com/Expensify/App/blob/79ea92345e48599d6663ef20213f8c64bb0568c1/src/pages/ReimbursementAccount/BankAccountManualStep.js#L122
```
disabled={shouldDisableInputs}
```
And in CheckboxWithLabel, we will create new props called disabled and pass this prop to Checkbox Component

We also consider adding the grey background with decreasing opacity to text input and the checkbox like we did in other places
### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2023-08-24 18:29
will look this today

**Comment by Santhosh-Sellavel** [comment] 2023-08-24 20:04
@himanshuragi456 [proposal](https://github.com/Expensify/App/issues/25577#issuecomment-1686245385) is straight forward one, LGTM!

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-08-24 20:07
@hayata-suenaga 

> I believe this should be implemented throughout the app for disabled RNTextInputs, in that case this style should be added in RNTextInput of BaseTextInput.js

This is the way to go, Let us know your thoughts on the proposal!

**Comment by DylanDylann** [comment] 2023-08-25 01:00
@Santhosh-Sellavel I think we also should disable the checkbox for consistency as mentioned in [my proposal](https://github.com/Expensify/App/issues/25577#issuecomment-1689224101)

**Comment by DylanDylann** [comment] 2023-08-25 06:49
@shawnborton Could you help to confirm that should we disable the checkbox for consistency in this issue? I see it will make more sense

**Comment by DylanDylann** [comment] 2023-08-25 06:52
> @DylanDylann This is just a minor adjustment

@himanshuragi456 Not minor (you don't mention it in your proposal). This issue is pretty straightforward and my proposal is better with other optional improvements as well for consistency

**Comment by shawnborton** [comment] 2023-08-25 14:51
Do we know why they can't be changed? 

But yeah, if they can't be changed, perhaps we can use more of a read-only version which would basically look like this existing pattern where we just label + value and no underline or right caret:
<img width="294" alt="image" src="https://github.com/Expensify/App/assets/2319350/51731a7e-0bcc-4f21-8536-e5df90155af1">

**Comment by shawnborton** [comment] 2023-08-25 15:11
What's the deal with the checkbox? I don't see anything mentioned about it in the original bug description.

**Comment by hayata-suenaga** [comment] 2023-08-25 15:19
@himanshuragi456 do you mean this checkbox?

<img width="360" alt="Screenshot 2023-08-25 at 8 18 51 AM" src="https://github.com/Expensify/App/assets/98560306/7c62b504-8b16-4b84-b5b8-f1a62941703f">

**Comment by DylanDylann** [comment] 2023-08-25 15:28
@shawnborton @hayata-suenaga I suggest in [my proposal](https://github.com/Expensify/App/issues/25577#issuecomment-1689224101) that we also should disable the checkbox for more consistency

**Comment by hayata-suenaga** [comment] 2023-08-25 15:32
I gonna assign @himanshuragi456 

please confirm about the cursor pointer's expected behavior with Shawn but other than that, we're good to go with a PR

@DylanDylann thank you for your detailed proposal and active discussion. We're looking forward to working with you in the next issue 😄

**Comment by hayata-suenaga** [comment] 2023-08-25 15:33
@himanshuragi456 is the checkbox even clickable after the first input?

**Comment by shawnborton** [comment] 2023-08-25 15:50
@hayata-suenaga do you know the answer to this:

> Do we know why they (the account number and routing numbers) can't be changed?

**Comment by hayata-suenaga** [comment] 2023-08-25 15:52
I missed that question. No I actually don't. I gonna ask in opne source and product

**Comment by hayata-suenaga** [comment] 2023-08-25 15:54
I think we have to start over if we want to change the information

<img width="400" alt="Screenshot 2023-08-25 at 8 53 59 AM" src="https://github.com/Expensify/App/assets/98560306/20cfa385-5bb9-4a85-b3e8-ba7a33dbd173">

**Comment by hayata-suenaga** [comment] 2023-08-25 16:02
yep it is expected that once you start the process of a certain account, you have to go back to restart the process all over again to change the account: https://expensify.slack.com/archives/C03U7DCU4/p1692979276523309?thread_ts=1692978989.566759&cid=C03U7DCU4

**Comment by hayata-suenaga** [comment] 2023-08-25 16:03
@himanshuragi456 if we cannot edit the checkbox, we should also disable the cursor for that, too

**Comment by hayata-suenaga** [comment] 2023-09-07 21:16
@puneetlath 

There was a discussion of payment in this [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1694062401145699) and in [this comment](https://github.com/Expensify/App/pull/25991#issuecomment-1709747925) in the PR.

I think we should't apply the penalty here as requirements changed several times, which caused a delay.

cc: @himanshuragi456

**Comment by puneetlath** [comment] 2023-09-07 22:11
Makes sense 👍🏾

**Comment by puneetlath** [comment] 2023-09-18 16:54
@Santhosh-Sellavel friendly reminder on the checklist so that we can pay later this week. Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-09-18 17:13
I think we can skip the checklist here as this end up as UI Polish not worth adding regression tests as well, Let me know your thoughts.

cc: @puneetlath @hayata-suenaga

**Comment by puneetlath** [comment] 2023-09-20 11:16
Yep, I think that's fine for this one.

**Comment by puneetlath** [comment] 2023-09-21 06:01
Payment summary: 

@Santhosh-Sellavel - C+ - $1000 (to be paid via NewDot)
@himanshuragi456 - C - $1000 (paid via Upwork) 
@daveSeife - B - $250 (paid via Upwork) 

@Santhosh-Sellavel let me know when you've raised the request in NewDot and I'll close this out. 

Thanks everyone!

**Comment by puneetlath** [comment] 2023-09-25 06:03
@Santhosh-Sellavel friendly reminder on creating the NewDot request.

**Comment by Santhosh-Sellavel** [comment] 2023-09-25 19:17
Requested on new dot

**Comment by puneetlath** [comment] 2023-09-26 01:49
Great, closing!

**Closed by puneetlath** 2023-09-26 01:49 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-28 01:03
$1,000 payment approved for @Santhosh-Sellavel based on BZ summary.
