### ISSUE TITLE
[HOLD for #20373][$1000] Web - Nothing happens when clicking 'mark as unread' for first message in Task page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22059] opened 2023-07-02 12:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a Task
2. Click on 'Mark as Done' button
3. Go to the reaction menu on the "Completed task" message and Click on 'Mark as unread'

## Expected Result:
New line marker should appear

## Actual Result:
New line marker don't appear.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f286ad12-8202-4a1f-be58-3bd1d8e7ece4

https://github.com/Expensify/App/assets/93399543/44e800cb-0146-4b9c-9522-49327e6a9cdf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688193259099549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a6e191233b5d7c1</li>
        <li>Upwork Job ID: 1676693735101640704</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-07-02 12:13
# Proposal

## Please re-state the problem
Nothing happens when clicking 'mark as unread' for first message in Task page after clicking 'mark as done'.

## What is the root cause of that problem?
When we click on mark as done, a `reportAction` indicating it as done, gets created and gets added to the report. Here in the `completeTask` function:
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/libs/actions/Task.js#L201-L206

But fields like `lastVisibleActionCreated` of the report donot get updated to reflect this `reportAction` being added to the `report`. We only update `stateNum` and `statusNum`:
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/libs/actions/Task.js#L195-L197

But the function `ReportUtils.isUnread` (which is used to check if a report is unread) depends on `lastVisibleActionCreated` which is still not updated in the report.

## What changes do you think we should make to solve this problem?
We should also update other properties of the report while adding the `reportAction` like we do in `Task.createTaskAndNavigate` function.
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/libs/actions/Task.js#L136-L142

This can be done with the following code:
```js
function completeTask(taskReportID, taskTitle) {
    const message = `completed task: ${taskTitle}`;
    const completedTaskReportAction = ReportUtils.buildOptimisticTaskReportAction(taskReportID, CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED, message);

    const lastAction = completedTaskReportAction;

    const currentTime = DateUtils.getDBTime();

    const lastCommentText = ReportUtils.formatReportLastMessageText(lastAction.message[0].text);

    const optimisticReport = {
        lastVisibleActionCreated: currentTime,
        lastMessageText: lastCommentText,
        lastMessageHtml: lastCommentText,
        lastReadTime: currentTime,
        lastActorEmail: currentUserEmail,
        lastActorAccountID: currentUserAccountID,
        stateNum: CONST.REPORT.STATE_NUM.SUBMITTED,
        statusNum: CONST.REPORT.STATUS.APPROVED,
    };

    const optimisticData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${taskReportID}`,
            value: optimisticReport
        },

        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${taskReportID}`,
            value: {[completedTaskReportAction.reportActionID]: completedTaskReportAction},
        },
    ];
.....
```


## What other approach did you explore?
None

**Comment by adelekennedy** [comment] 2023-07-05 20:45
replicated - this should match how we treat other actions/messages

**Comment by s77rt** [comment] 2023-07-05 22:34
@esh-g Thanks for the proposal. Your RCA makes sense. The suggestion solution looks good, in fact we are already doing something very similar in this PR https://github.com/Expensify/App/pull/20373 so we probably have nothing to do here.

**Comment by s77rt** [comment] 2023-07-05 22:35
@adelekennedy Let's put this on hold for https://github.com/Expensify/App/pull/20373

**Comment by s77rt** [comment] 2023-07-12 17:41
@adelekennedy Do we need to have `[HOLD]` in the title? Melvin does not see this as being on hold

**Comment by adelekennedy** [comment] 2023-07-20 22:51
you're so right!!

**Comment by s77rt** [comment] 2023-07-31 18:33
Still on hold

**Comment by adelekennedy** [comment] 2023-08-08 21:02
holding

**Comment by adelekennedy** [comment] 2023-08-21 17:51
Still on hold, moving to Monthly

**Comment by s77rt** [comment] 2023-09-23 23:07
The PR we are holding this issue for got closed. Asked for next steps [here](https://github.com/Expensify/App/pull/20373#issuecomment-1732428480).

**Comment by s77rt** [comment] 2023-10-25 14:48
@PauloGasparSv @bondydaa From https://github.com/Expensify/App/pull/20373#issuecomment-1732428480. That issue was closed with not much details. Can you please help us on how we should move forward with this one?

@esh-g Can you please check if the issue is still reproducible?

**Comment by s77rt** [comment] 2023-11-27 14:12
@PauloGasparSv @bondydaa @esh-g ^

**Comment by esh-g** [comment] 2023-11-27 15:30
@s77rt This does not seem to be reproducible anymore..

**Comment by s77rt** [comment] 2023-11-27 17:32
@esh-g Thank you! Looks like this was fixed by the unread marker refactor https://github.com/Expensify/App/pull/18637

**Comment by s77rt** [comment] 2023-11-27 17:33
@adelekennedy We are good to close this one

**Closed** 2023-11-27 17:33 UTC
Labels: External, Weekly, Help Wanted, Bug
