### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Scan - Infinite loading for scan option if it is selected after manual.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51821] opened 2024-10-31 17:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5168073&group_by=cases:section_id&group_order=asc&group_id=309127
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on FAB
2. Click on submit expense
3. Verify the manual option is selected
4. Select the Scan option

## Expected Result:
"Take a photo, Camera access is required to take pictures of receipts" or a camera interface are displayed

## Actual Result:
Infinite loading for scan option if it is selected after manual

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/912f1fa8-c8a7-49f5-adc6-9e00578b9843

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852097315271105119</li>
        <li>Upwork Job ID: 1852097315271105119</li>
        <li>Last Price Increase: 2024-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>QichenZhu | Contributor | 104755565</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by lanitochka17** [comment] 2024-10-31 17:13
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-31 17:13
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment] 2024-10-31 21:16
Reproduced. 

https://github.com/user-attachments/assets/9809a561-28c7-4d36-aae6-af0d9946ee2d

**Comment by TalhaAmjad0034** [comment] 2024-11-01 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When switching from the "manual" option to the "scan" option in the app, the user encounters an infinite loading screen rather than seeing the camera interface or receiving a camera permissions prompt.

### What is the root cause of that problem?
The problem arises because the `isTabFocused` state fails to update accurately during tab transitions. This inconsistency stems from delays in syncing `isPageFocused` and `tabPositionAnimation`, which cause `isTabFocused` to remain in an incorrect state. As a result, the app cannot reliably trigger the camera interface or permissions prompt, leading to an indefinite loading state.


https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/hooks/useTabNavigatorFocus/index.ts#L53-L82

### What changes do you think we should make in order to solve the problem?
To fix this, we need a robust synchronization between `isPageFocused` and `tabPositionAnimation`:
1. Separate tracking for `isPageFocused` using `useEffect`, so `isTabFocused` updates immediately when `isPageFocused` or `tabPositionAnimation` changes.
2. Introduce a check to update `isTabFocused` dynamically based on the current position range (`tabIndex - 1` to `tabIndex + 1`) in `tabPositionAnimation` to ensure a reliable focus state when the user changes tabs.

This approach maintains state accuracy across tab changes, ensuring the scan tab loads the camera or permissions prompt as intended.

```
// Add a listener to track the animation's current position (value) and update isTabFocused accordingly.
        const listenerId = tabPositionAnimation.addListener(({value}: PositionAnimationListenerCallback) => {
            // Determine if the tab is within the visible range based on tabIndex and update focus status.
            const isInFocusRange = value >= tabIndex - 1 && value <= tabIndex + 1;
            const newFocusState = isInFocusRange && isPageFocused;

            // Request an animation frame to set isTabFocused for smoother updates.
            DomUtils.requestAnimationFrame(() => {
                setIsTabFocused(newFocusState);
            });
        });

        // Obtain the initial tab position for an accurate focus status on component load.
        const initialPosition = tabPositionAnimation.__getValue();
        const isInitiallyFocused = initialPosition > tabIndex - 1 && initialPosition < tabIndex + 1 && isPageFocused;

        // Set the initial focus state based on the current position and page focus status.
        setIsTabFocused(isInitiallyFocused);

        // Clean up the listener when the component unmounts or tabPositionAnimation changes.
        return () => {
            if (tabPositionAnimation) {
                tabPositionAnimation.removeListener(listenerId);
            }
        };
    }, [tabIndex, isPageFocused, tabPositionAnimation]);

    useEffect(() => {
        // If tabPositionAnimation is not available, update isTabFocused directly based on isPageFocused.
        if (!tabPositionAnimation) {
            setIsTabFocused(isPageFocused);
        } else {
            // Update focus state directly whenever isPageFocused changes, ensuring synchronization with tab animation.
            const updateFocusDirectly = () => {
                const value = tabPositionAnimation.__getValue();
                const isWithinTabIndex = value >= tabIndex - 1 && value <= tabIndex + 1;
                const shouldBeFocused = isWithinTabIndex && isPageFocused;

                setIsTabFocused(shouldBeFocused);
            };

            // Request an animation frame for a smoother update when isPageFocused changes.
            DomUtils.requestAnimationFrame(updateFocusDirectly);
        }
    }, [isPageFocused]);
```

### What alternative solutions did you explore? (Optional)
One alternative solution considered was to use a custom animation trigger to monitor tab focus directly. However, this approach would have added complexity without fully addressing the root cause related to synchronization between `isPageFocused` and `tabPositionAnimation`.

Attached screen record of local version with above fix in `useTabNavigatorFocus/index.ts`



https://github.com/user-attachments/assets/11850369-5d46-47ec-87aa-81587f7ce3de

**Comment by QichenZhu** [comment] 2024-11-01 13:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When open IOU with the Manual tab and switching to the Scan tab, the camera loads infinitely.

### What is the root cause of that problem?

After PR https://github.com/Expensify/App/pull/51020 was merged, which removed the use of animation state from `TabSelector` on web platforms, the listener of `tabPositionAnimation` is not called when switching tabs.

https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/hooks/useTabNavigatorFocus/index.ts#L57

So `useTabNavigatorFocus` doesn't work, and `isTabActive` is not changed, which mean it is `false` when you open the Manual tab, and it is still `false` after you switch to the Scan tab.

https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L95

The camera cannot get the permission state if `isTabActive` is false.

https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L172-L174

https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L189

So it shows a spinner.

https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L616-L617

### What changes do you think we should make in order to solve the problem?

The mentioned PR addressed a very minor issue https://github.com/Expensify/App/issues/50265, so maybe it could simply be reverted.

### What alternative solutions did you explore? (Optional)

1. `isTabActive` was introduced in https://github.com/Expensify/App/issues/37737 to prevent the permission request from prompting early on native platforms, but on web platforms, the prompt only appears after you click the Continue button. So we could remove the dependency on `isTabActive` from the lines below.

https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L172

https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L193

2. Use the navigation state instead of the animation state as the source of truth. 
It was discussed in https://github.com/Expensify/App/issues/33732. We need to work based on the previous attempt https://github.com/Expensify/App/pull/33754.

**Comment by QichenZhu** [comment] 2024-11-05 10:46
## Proposal
[Updated](https://github.com/Expensify/App/issues/51821#issuecomment-2451859918)

@ntdiary Thank you very much for your comments. I updated the main solution and moved the original main solution as a last option.

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:21
PR merged, awaiting deploy to staging

**Comment by joekaufmanexpensify** [comment] 2024-11-20 17:07
Regression test is here: https://github.com/Expensify/Expensify/issues/446317

**Comment by joekaufmanexpensify** [comment] 2024-11-20 17:08
All set to pay. We need to pay: 

- @QichenZhu $250 for PR via Upwork. 
- @ntdiary $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-11-20 17:09
@QichenZhu $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-11-20 17:09
Upwork job closed.

**Closed** 2024-11-20 17:09 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-11-21 10:56
$250 approved for @ntdiary
