### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Web - Log in - Inconsistency between signin button and 2FA button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20848] opened 2023-06-15 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> security -> 2FA
2. Copy/ download codes and continue
3. Meanwhile download the authenticator application. Now, Scan the QR.
4. Now type the generated code.
5. Notice that the "loading sign along with the next button" is displayed as disabled before moving to the next page. ( even when the correct code is typed)
6.  However, if similar steps are followed (i.e after typing magic code ) on the signing page, "the loading bar on sign-in button" is shown enabled.

## Expected Result:
Consistency between the buttons. i.e. after typing the correct magic code on singin page or the 2FA code on the authentication page, buttons should either be enabled or disabled on both pages.

## Actual Result:
`Next` button on authentication page is shown _disabled_ before moving to next page, even when the correct 2FAcode is entered.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:**yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/73eb4b42-5b1c-4e6d-acf9-18a6eda920d9

https://github.com/Expensify/App/assets/93399543/43b9d7d6-7d8e-495e-9192-ef1a04497759

**Expensify/Expensify Issue URL:** @ashimsharma10

**Issue reported by:** https://expensify.slack.com/archives/C049HHMV9SM/p1686219682890139

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8ad74604f91854d</li>
        <li>Upwork Job ID: 1671877459838341120</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-06-20 14:19
I don't think this behavior is a bug. I've asked [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1687270725215389) to get a second opinion.

**Comment by johncschuster** [comment] 2023-06-21 14:31
Bumped my thread since I didn't get any responses.

**Comment by mollfpr** [comment] 2023-06-26 14:58
Thanks @tienifr, for the proposal.

I'm not sure using `useImperativeHandle` feels over-engineered. Why can't we move the button to `BaseTwoFactorAuthForm` and fix the positioning?

**Comment by mollfpr** [comment] 2023-06-28 01:04
> I tried it but the BaseTwoFactorAuthForm is placed in ScrollView and we want the next button stays outside the ScrollView to show it even on the small screen height. And I don't see any places on our code that we put FixedFooter stays inside ScrollView.

Okay that makes sense

> That why I want to use useImperativeHandle, and we also used it in other pages

@tienifr Could you give an example of which page it is?

**Comment by mollfpr** [comment] 2023-06-30 18:12
Sorry for the delay @tienifr 🙏

I'm okay with `useImperativeHandle` and I don't see any drawback for now. @johncschuster the [proposal](https://github.com/Expensify/App/issues/20848#issuecomment-1603700861) looks good to me 🚀

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-07-03 15:45
@tienifr Let me know when the PR is ready. Thanks!

**Comment by mollfpr** [comment] 2023-07-18 05:28
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18576

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18576/files#r1266234798

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression test should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1. Open the App and go to Settings -> Security -> Two-factor authentication
2. Copy / download codes to continue
3. Keep the input empty and press the Next button
4. **Verify** that the next button is pressable and the error validation is shown "Please enter your two-factor authentication code"
5. Put less than 6 digits to the input and press the Next button
6. **Verify** that the next button is pressable and the error validation is shown "Incorrect two-factor authentication code. Please try again."
7. Now put the correct code from your authenticator app
8. **Verify** that it automatically submit the form and moves you to the next page
9. 👍 or 👎

**Comment by johncschuster** [comment] 2023-07-19 17:41
@ashimsharma10 I've just sent you an invite on Upwork. Can you please accept the job?

**Comment by johncschuster** [comment] 2023-07-19 17:45
Payment has been issued to @tienifr and @mollfpr. I'll get the regression test issue going shortly.

**Comment by ashimsharma10** [comment] 2023-07-21 08:32
@johncschuster Accepted . Waiting for payment

**Comment by johncschuster** [comment] 2023-07-22 12:15
Thanks, @ashimsharma10! Payment has been issued.

I'll get the regression steps in a GH on Monday and we can close this out.

**Comment by johncschuster** [comment] 2023-07-26 19:28
**Summary of payment issued:**
 External issue reporter - @ashimsharma10 - $250
 Contributor that fixed the issue - @tienifr - $1000
 Contributor+ that helped on the issue and/or PR - @mollfpr - $1000

**Closed by johncschuster** 2023-07-26 19:28 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
