### ISSUE TITLE
[HOLD for payment 2024-01-18] [$500] Private Note - The message 'Hmm... it's not here' displays instead of Skeleton UI when viewing Private Notes in Offline Mode.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30246] opened 2023-10-24 12:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697131558107909

## Action Performed:
1. Log in to any Account.
2. Disable the network connection to switch to OFFLINE mode.
3. Open any chat and select a Contact to view their details.
4. Click on "Private Notes"
5. Observation: You will see the message "Hmm... it's not here" displayed.

## Expected Result:
A Skeleton UI should be displayed, as it is a general concept applied when the data is loading.

## Actual Result:
 Instead of a Skeleton UI, the message "Hmm... it's not here" is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/a5cf05fa-7a4c-4c90-98b3-8201e28b5d61

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/6d4a8d8f-3ff4-4a69-9746-6e6ce86890e3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/e50ebd99-75f2-4f40-b738-d7152fb7fc39

https://github.com/Expensify/App/assets/93399543/8a0f16b5-30ca-4fe2-b0ae-c1963a68e64d

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/d08e56d2-dbc6-435b-a031-c74e14a3f76b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb01f2ab30a52085</li>
        <li>Upwork Job ID: 1716795251231830016</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27616931</li>
<li>hungvu193 | Contributor | 27616932</li>
<li>tranvantoan-qn | Reporter | 27616934</li>
</ul></li>
    </ul>
</details>

**Comment by rakshitjain13** [comment] 2023-10-24 13:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The message 'Hmm... it's not here' displays instead of Skeleton UI when viewing Private Notes in Offline Mode
### What is the root cause of that problem?
In PrivateNotesListPage.js  , should shouldShow become true due to offline mode
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/pages/PrivateNotes/PrivateNotesListPage.js#L127-L133
### What changes do you think we should make in order to solve the problem?
We have to update the condition with !network.isOffline in the above check and show OptionsListSkeletonView when the network is offline 
```
<FullPageNotFoundView
                shouldShow={
                    _.isEmpty(report.reportID) ||
                    (!report.isLoadingPrivateNotes && _.isEmpty(lodashGet(report, 'privateNotes', {})) && !network.isOffline) ||
                    ReportUtils.isArchivedRoom(report)
                }
            >
                <HeaderWithBackButton
                    title={translate('privateNotes.title')}
                    shouldShowBackButton
                    onCloseButtonPress={() => Navigation.dismissModal()}
                />
                <ScrollView contentContainerStyle={styles.flexGrow1}>
                    {network.isOffline ? (
                        <OptionsListSkeletonView shouldAnimate />
                    ) : report.isLoadingPrivateNotes && _.isEmpty(lodashGet(report, 'privateNotes', {})) ? (
                        <FullScreenLoadingIndicator style={[styles.flex1, styles.pRelative]} />
                    ) : (
                        _.map(privateNotes, (item, index) => getMenuItem(item, index))
                    )}
                </ScrollView>
            </FullPageNotFoundView>
```

https://github.com/Expensify/App/assets/54314936/4293fba1-30eb-48b7-8c2c-fb46c0f6a478




### What alternative solutions did you explore? (Optional)

NA

**Comment by jjcoffee** [comment] 2023-10-24 13:55
@rakshitjain13 Thanks for the proposal! If we go ahead with this change, I think we'd probably want to always display the skeleton loader instead of the full screen loader otherwise coming back online there'd be an odd transition from Skeleton Loader -> Full Screen Loader -> Notes. cc @Expensify/design for feedback!

**Comment by rakshitjain13** [comment] 2023-10-24 14:42
@jjcoffee Thanks for the feedback and I think your suggestion makes more sense. Hence updated the proposal https://github.com/Expensify/App/issues/30246#issuecomment-1777195215

**Comment by hungvu193** [comment] 2023-10-25 04:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The message 'Hmm... it's not here' displays instead of Skeleton UI when viewing Private Notes in Offline Mode.
### What is the root cause of that problem?
We currently show NotfoundPage with below condition
https://github.com/Expensify/App/blob/1c85ebeb55ffe81bf0cfa64665b4dc6625b94683/src/pages/PrivateNotes/PrivateNotesListPage.js#L128-L132

Since we only load when it's not offline, NotFoundPage will be shown in this case.
https://github.com/Expensify/App/blob/1c85ebeb55ffe81bf0cfa64665b4dc6625b94683/src/pages/PrivateNotes/PrivateNotesListPage.js#L67-L70
### What changes do you think we should make in order to solve the problem?

Show the loading indicator or skeleton instead of blocking user from using it (similar to other places like Address or WorkspaceMembers). So we need to remove `network.isOffline` from `shouldShow` props of `FullPageNotFoundView`. Also update the condition of

```javascript
 {(report.isLoadingPrivateNotes && _.isEmpty(lodashGet(report, 'privateNotes', {}) || (network.isOffline && _.isEmpty(lodashGet(report, 'privateNotes', {})))) ? (
                        <FullScreenLoadingIndicator style={[styles.flex1, styles.pRelative]} />
                    ) : (
                        _.map(privateNotes, (item, index) => getMenuItem(item, index))
                    )}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by tranvantoan-qn** [comment] 2023-10-25 04:50
@jjcoffee 

**FYI**: This issue was expected to be resolved with https://github.com/Expensify/App/issues/27591, but for some reason, it hasn't been. Therefore, I believe it's necessary to examine that issue for further details on what was actually implemented and whether we can build upon that solution.

**Comment by jjcoffee** [comment] 2023-10-25 08:27
@tranvantoan-qn Thanks for the extra context! Looking at that [issue](https://github.com/Expensify/App/issues/27591) it looks like it's expected for the `FullScreenLoadingIndicator` to show and not the skeleton loader. We also want to make sure that the notes page will load if we already have the notes loaded (as you suggested in [your comment](https://github.com/Expensify/App/issues/27591#issuecomment-1760679739)). cc @hungvu193 and @rakshitjain13

**Comment by rakshitjain13** [comment] 2023-10-25 08:32
@jjcoffee Thanks for the confirmation that ```FullScreenLoadingIndicator``` is expected and not Skeleton which the bug reporter proposed. Hence I am updating my proposal to shift from ```OptionsListSkeletonView``` to ```FullScreenLoadingIndicator```

**Comment by hungvu193** [comment] 2023-10-25 08:34
> @tranvantoan-qn Thanks for the extra context! Looking at that [issue](https://github.com/Expensify/App/issues/27591) it looks like it's expected for the `FullScreenLoadingIndicator` to show and not the skeleton loader. We also want to make sure that the notes page will load if we already have the notes loaded (as you suggested in [your comment](https://github.com/Expensify/App/issues/27591#issuecomment-1760679739)). cc @hungvu193 and @rakshitjain13

Yeah, we're showing Fullscreenloading until we reconnect to the internet as I said in my proposal.

**Comment by puneetlath** [comment] 2023-10-31 19:12
@jjcoffee mind summarizing where we're at with this issue currently?

**Comment by jjcoffee** [comment] 2023-11-01 16:05
So we have two pretty identical proposals, but @hungvu193's was the first to include handling for being offline and already having loaded the notes. 

When testing both proposals I see a brief appearance of the `Hmm... it's not here` message before the private notes load after coming back online:


https://github.com/Expensify/App/assets/27287420/c27f17c7-031a-472c-a600-e58f9af144b4

**Comment by rakshitjain13** [comment] 2023-11-01 17:22
@jjcoffee I think it is because when we shift from offline to online for a moment isLoadingPrivateNotes is false. After all, it is set to false in a case when you first visited or failed due to offline https://github.com/Expensify/App/blob/f9d11c5c6509245b28570d53440f4fa341ced202/src/libs/actions/Report.js#L2377-L2385
which makes the below condition true in shouldShow
```
  (!report.isLoadingPrivateNotes && _.isEmpty(lodashGet(report, 'privateNotes', {})) && !network.isOffline)
```

If we change to true in failureData we don't ```Hmm... it's not here``` when shifting from offline to online like
```
failureData: [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
                    value: {
                        isLoadingPrivateNotes: true,
                    },
                },
            ]
```
cc: @hungvu193

**Comment by hungvu193** [comment] 2023-11-02 11:11
> So we have two pretty identical proposals, but @hungvu193's was the first to include handling for being offline and already having loaded the notes.
> 
> When testing both proposals I see a brief appearance of the `Hmm... it's not here` message before the private notes load after coming back online:
> 
>  private-notes-coming-online-2023-11-01_17.02.21.mp4

So the `Report.getReportPrivateNote(report.reportID);` is using `API.read` which is not persisted. Because of that after changing connection to online, NotFoundView will be shown first because our useEffect (which includes the `Report.getReportPrivateNote(report.reportID)` to set isLoadingPrivateNotes to true  will run after re-render).
I think the best way to archive the expected result is to introduce new variable called `isReconnecting` and we won't show NotFoundView when our application is reconnecting. More details in my [updated proposal](https://github.com/Expensify/App/issues/30246#issuecomment-1778492320)

**Comment by puneetlath** [comment] 2023-11-07 16:32
@jjcoffee thoughts on the latest convo?

**Comment by jjcoffee** [comment] 2023-11-08 12:00
Apologies for the delay here, @hungvu193's updated [proposal](https://github.com/Expensify/App/issues/30246#issuecomment-1778492320) LGTM! We use a similar trick in `WorkspaceMembersPage` to check if we are reconnecting.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by puneetlath** [comment] 2023-11-10 22:02
Sounds good to me. Makes sense that we'd follow the same pattern we use elsewhere.

**Comment by jjcoffee** [comment] 2023-11-27 10:23
Just an update here - the PR is still being worked on, we encountered an extra edge case that @hungvu193 needs to dig into for a fix.

**Comment by jjcoffee** [comment] 2023-12-05 09:36
Still waiting on @hungvu193. I'm not sure if maybe they've gone away or something as they've not replied for a while!

**Comment by hungvu193** [comment] 2023-12-09 03:03
> @hungvu193 are you still working on this? 

I do. I've been out sick last couples of week. I'll be back this weekend

**Comment by jjcoffee** [comment] 2024-01-02 10:27
Just waiting for @puneetlath to merge [the PR](https://github.com/Expensify/App/pull/31257).

**Comment by puneetlath** [comment] 2024-01-17 18:47
@jjcoffee bump on the checklist so that we can pay tomorrow.

**Comment by jjcoffee** [comment] 2024-01-18 07:59
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28461/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28461/files#r1457057393
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - just needed more thorough testing
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open the app and go offline
2. Open any chat which has private notes and tap on the header to open the chat details
3. Tap on "Private Notes"
4. Verify that a loader displays
5. Go back online
6. Verify that the notes are populated

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-01-18 08:03
Note that there's an outstanding [regression](https://github.com/Expensify/App/issues/34270) that is waiting on @hungvu193's input.

**Comment by puneetlath** [comment] 2024-01-19 15:54
@hungvu193 are you planning to handle that shortly? We won't be able to pay this one out until you do.

**Comment by hungvu193** [comment] 2024-01-21 14:04
> @hungvu193 are you planning to handle that shortly? We won't be able to pay this one out until you do.

Cool. I'm on it.

**Comment by jjcoffee** [comment] 2024-01-31 08:54
[Deployed](https://github.com/Expensify/App/issues/34270#issuecomment-1918252720) to production! @puneetlath Can we update the HOLD for payment here to 2024-02-07? Thanks!

**Comment by puneetlath** [comment] 2024-02-07 15:59
All paid. Thanks everyone!

**Closed by puneetlath** 2024-02-07 15:59 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
