### ISSUE TITLE
[$250] 3 OpenReport API calls for the same report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49948] opened 2024-09-30 17:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727446418470879

## Action Performed:

1. User A and user B are on a chat
2. User A adds a comment
3. User A creates a thread under their comment
4. User B clicks the thread

## Expected Result:
Thread opens and no duplicate OpenReport API calls for same report
## Actual Result:
3 OpenReport API calls for the same report
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (10)](https://github.com/user-attachments/assets/c3b25a4a-4ded-493a-ad3d-75da61c97a51)

![Snip - (14) New Expensify - Google Chrome](https://github.com/user-attachments/assets/2142ed23-af32-4b65-a95c-074bcda3c2c1)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841330786260257123</li>
        <li>Upwork Job ID: 1841330786260257123</li>
        <li>Last Price Increase: 2024-11-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by bernhardoj** [comment] 2024-10-01 05:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are 2 OpenReport calls when open a thread that we never loaded yet.

### What is the root cause of that problem?
The 1st OpenReport is called in this effect. The purpose of this effect is to call the OpenReport on mount, but we only want to call it when the report onyx is already loaded. We did this after migrating from withOnyx to useOnyx [here](https://github.com/Expensify/App/pull/37596).
https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/pages/home/ReportScreen.tsx#L489-L496

The 2nd and 3rd call is triggered from this effect.
https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/pages/home/ReportScreen.tsx#L577-L588

When we open the thread that we haven't loaded yet, the report will initially be undefined. The 1st OpenReport will optimistically merge the reportName as Chat Report.
https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/libs/actions/Report.ts#L779-L783

This will update the report to `{reportName: 'Chat Report'}`, and so, the report onyx now contains an empty `reportID`.
https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/pages/home/ReportScreen.tsx#L169-L173

Because `onyxReportID` (empty string) is different from `prevReport?.reportID` (undefined), the 2nd OpenReport is called. After the 1st OpenReport is finished, the `onyxReportID` is updated to the correct reportID (X). Again, because the `onyxReportID` (X) is different from `prevReport?.reportID` (empty string), the 3rd OpenReport is called.

### What changes do you think we should make in order to solve the problem?

There are 2 solutions. First, if we see the comment here, 
https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/pages/home/ReportScreen.tsx#L577-L585

it's mentioned that when deeplinking from a report to another report, the report screen is not unmounted and the reportID param is not updated, so the old conditions doesn't work when comparing prev reportID params to the current reportID params.
<img width="681" alt="image" src="https://github.com/user-attachments/assets/c0486496-7008-497e-8652-7ac2ecae4a5b">

The report screen is not unmounted part is still true today because if we deeplink to the same screen with a different params, react-navigation will just update the screen params, so this part isn't true anymore.

> the reportID in the route also doesn't change.

So, the first solution is to use the old conditions by comparing the prev reportID params and the current reportID params.
```
if (prevReportIDFromRoute === reportIDFromRoute) {
    return;
}
```
##
The second solution is to push a new screen if the reportID is different. To do that, we can override the deeplink here.
https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/libs/Navigation/linkingConfig/subscribe/index.native.ts#L21-L29

```
if (focusedRoute?.name === SCREENS.REPORT && hasAuthToken()) {
    Navigation.navigate(path as Route);
    return;
}
```

Then, we can remove the OpenReport call here.
https://github.com/Expensify/App/blob/69483ff0ef36e39fbf40c15f2caa3471dccbef17/src/pages/home/ReportScreen.tsx#L577-L585

**Comment by VictoriaExpensify** [comment] 2024-10-02 04:16
I think #vip-vsb is the best place for this since it's related to threads

**Comment by iwiznia** [comment] 2024-10-09 16:02
@shubham1206agra can you review @bernhardoj's proposal or should we reassign this?

**Comment by bernhardoj** [comment] 2024-10-10 02:19
That specifically happens after https://github.com/Expensify/App/pull/49056 where they add a check for the report here.
https://github.com/Expensify/App/blob/f0be8a731dc0832827dbd14d23fd49b332ff275e/src/pages/home/ReportScreen.tsx#L169-L173

<img width="1667" alt="image" src="https://github.com/user-attachments/assets/be6a37f1-1aa5-46e6-8635-1894186238b7">

So, previously, even when the report is undefined, the reportID will still be an empty string, so the 2nd OpenReport isn't called.

> Again, because the onyxReportID (X) is different from prevReport?.reportID (empty string), the 3rd OpenReport is called.

But I tried reverting it locally and the 3rd OpenReport is still called when the reportID changes from empty string to the correct reportID. That's why I didn't talk about that since the multiple OpenReport will still happen.

**Comment by bernhardoj** [comment] 2024-10-16 09:32
Why is it a workaround? The current code is the workaround for an issue that isn't happening anymore.
https://github.com/Expensify/App/blob/96ffbfe27c5c1b85b062e6ab50c0adc46b0e94c3/src/pages/home/ReportScreen.tsx#L580-L586

I'm suggesting to revert back to the old condition which compares the prev and current reportID params. If my solution is a workaround, then the old code is also a workaround, which I don't think is true.

There is even a 2nd solution that will remove that condition and push a new screen instead of updating the current screen params.

I think removing a workaround is preferable compared to patching existing workaround.

**Comment by VictoriaExpensify** [comment] 2024-10-29 10:10
> I think removing a workaround is preferable compared to patching existing workaround.

I agree that this is preferable.

> Why is it a workaround? The current code is the workaround for an issue that isn't happening anymore.

Is it not happening anymore _because_ of the workaround @bernhardoj ? i.e. if we removed the workaround would the issue resurface?

**Comment by bernhardoj** [comment] 2024-10-29 10:17
> Is it not happening anymore because of the workaround @bernhardoj ? i.e. if we removed the workaround would the issue resurface?

Yes, it's not happening anymore from my testing but not because of the workaround. I think it's a bug in the navigator that we used in the old code before.

**Comment by VictoriaExpensify** [comment] 2024-10-29 10:33
OK if reverting the workaround from your code [here](https://github.com/Expensify/App/issues/49948#issuecomment-2428719933) will resolve this issue, and removing it will not cause further issues, I think that's the approach we should take

**Comment by iwiznia** [comment] 2024-11-06 15:13
Is it? IIRC someone mentioned that this was still happening... See this conversation https://expensify.slack.com/archives/C05LX9D6E07/p1730737982412859?thread_ts=1727884875.529299&cid=C05LX9D6E07

**Comment by VictoriaExpensify** [comment] 2024-11-13 10:30
hey @shubham1206agra - can you please check the conversation Ioni linked here - https://github.com/Expensify/App/issues/49948#issuecomment-2460028756

It looks like this issue is still happening

**Comment by mvtglobally** [comment] 2024-11-16 01:57
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-11-19 12:38
Fixed over here: https://github.com/Expensify/App/issues/51680

**Closed by muttmuure** 2024-11-19 12:38 UTC
Labels: External, Daily, Help Wanted, Bug
