### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] After deletion of workspace, stuck on create WS and "Hmm... It's not here" Page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20622] opened 2023-06-12 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click "+" button
2. Create WS from the bottom sheet
3. Delete WS from the option which is shown on the top Three buttons click
4. Try to go back
## Expected Result: 
It should be navigated to the profile or Home page
## Actual Result: 
After Deletion WS, stuck on create WS and "Hmm... It's not here" Page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-2
**Reproducible in staging?:** Y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1668ce7f-5955-4412-bf1d-d9f8249efe46

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686138272103839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f49e2245c904302</li>
        <li>Upwork Job ID: 1669020226599235584</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-06-12 21:14
We need to confirm if this is reproducible otherwise close it

**Comment by mountiny** [comment] 2023-06-14 16:32
@bernhardoj popping is defintiely a way to go in this case.

**Comment by arielgreen** [comment] 2023-06-16 02:48
Reassigning, team change

**Comment by mountiny** [comment] 2023-06-16 09:52
Thanks, SWM will try to review the proposals today.

**Comment by mountiny** [comment] 2023-06-19 11:42
Still waiting for the review.

**Comment by adamgrzybowski** [comment] 2023-06-19 12:27
I tested the solution with `pop()`. Looks good to me! 🚀

**Comment by adamgrzybowski** [comment] 2023-06-19 12:42
@mountiny I think that the second one changes how the flow looks like. The difference is one adds `goBack` before `navigate` and the second replaces `navigate` with `goBack`

**Comment by bfitzexpensify** [comment] 2023-06-29 05:58
Offers sent out @niravkakadiya25 @honnamkuan @allroundexperts

**Comment by niravkakadiya25** [comment] 2023-06-29 06:00
accepted @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2023-06-29 06:05
Also @allroundexperts a reminder to complete the BZ checklist - https://github.com/Expensify/App/issues/20622#issuecomment-1602991725 - and we can get this all closed out. Thanks!

**Comment by bfitzexpensify** [comment] 2023-07-03 07:38
Bump on the BZ checklist @allroundexperts - thank you!

**Comment by bfitzexpensify** [comment] 2023-07-05 10:51
Cool, that sounds fair to me. OK, we're all done here, closing this out

**Closed by bfitzexpensify** 2023-07-05 10:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
