### ISSUE TITLE
 Web - Chat -Emojis are not displayed correctly in the Emoji Picker

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13589] opened 2022-12-14 18:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a conversation
2. Open the emoji picker
3. Scroll down the list to the bottom verifying each emoji is rendered correctly

## Expected Result:
After scrolling down the list of emojis, it should be located on their places and without defects

## Actual Result:
Emojis are not displayed correctly in the Emoji Picker

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web ( Windows 10/Chrome)

**Version Number:** 1.2.39.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/207674287-e7045d8f-0dec-420a-afad-e520561575d7.mp4

![newmoji](https://user-images.githubusercontent.com/93399543/207674289-9d80cef5-e47f-451d-baca-8ddba4c687e9.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-12-14 18:19
Issue is reproduced only on Windows 10 Pro/Chrome

![image (5)](https://user-images.githubusercontent.com/93399543/207675410-d00b72bf-e0ea-4d1a-b48d-adf55db9bd3a.png)

**Comment by PauloGasparSv** [comment] 2022-12-14 19:20
Hey @kbecciv can you which your version of Chrome you have?

Could you also test this on another browser like Firefox and send another video so we can check if it happens exactly the same there too?

Tested both staging and prod on a mac and couldn't replicate, I hope this isn't a problem windows only problem.

**Comment by kbecciv** [comment] 2022-12-14 19:34
I have Windows 11 Pro and could not reproduce the issue, but we ask in channel for more reproduction - two people with Windows 10 Pro able to reproduce it.
Do you want me to ask tester to check in Firefox on Windows 10 Pro?

**Comment by PauloGasparSv** [comment] 2022-12-15 15:03
Thks @kbecciv! I'd appreciate if you could also ask them to test on Firefox but that's not a blocker so don't worry and no rush :D

Changed this to `internal` to work on a fix myself if we can reproduce the bug. I'll test this on a couple of windows 10 machines I have and ask for help on slack if I can't reproduce it.

**Comment by PauloGasparSv** [comment] 2022-12-15 15:53
I reproduced the error on a windows 10 machine.

Same displacement problem:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/6564265/207906315-337ecee1-8e1b-4e18-a988-71d38556d4da.png">

And some emojis appear on an extra column:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/6564265/207906395-18749b93-f100-484a-a07f-6a755fb7d9a4.png">

I'll double check if the extra column problem already has an issue to it and start working on a fix. I still have no idea why this is happening

**Comment by kbecciv** [comment] 2022-12-15 19:16
@PauloGasparSv Firefox has the same issue as Chrome 

![image (6)](https://user-images.githubusercontent.com/93399543/207947698-517d9075-e964-40bb-b3f5-ff31c9d9c710.png)

**Comment by PauloGasparSv** [comment] 2022-12-15 20:36
Ok, I think some emojis don't exist on Windows and when we try to render them we end up rendering the fallback emoji + a random emoji beside it.

I just tested sending the red hair person emoji to myself, here it is on Mac:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/6564265/207961595-2f0baad5-fade-4fad-916b-6e57fe7f4095.png">

And on Windows:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/6564265/207961733-c2e2bb48-3e22-4008-b542-6aae498c53c6.png">

Trying to think of an easy fix for this

**Comment by PauloGasparSv** [comment] 2022-12-16 17:28
Still working on this, trying to develop on mac and test on windows using ngrok but so far I still don't have a fix.

I've searched the web for a solution but I didn't find a lot of people reporting problems with emojis natively and the ones I've found are not solved >:( 

I'll keep this with me untill Monday and ask the team for help on it if I can't think of a fix.

**Comment by mallenexpensify** [comment] 2022-12-16 21:27
Wanna drop a comment into #expensify-open-source to see if anyone has recommendations for how to manage? I imagine this issue has been addressed before for different apps managing emoji across OSs

**Comment by PauloGasparSv** [comment] 2022-12-18 18:06
@mallenexpensify Will do, I mentioned I would **do it on Monday** because I was still testing it on a Windows machine I found here : )

**Comment by PauloGasparSv** [comment] 2022-12-19 15:41
[Sent a message on #expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1671464270798609) asking for help.

I believe the font `Segoa UI Emoji` used on Windows for emojis the browser doesn't have doesn't contain all emoji unicodes on version 1.29, the very latest available for windows 10. That explains why some emojis are being displayed incorrectly or as a white square, but I'm not sure if it explains why there are some emojis being displayed as two different emoji/unicode characters.

I tried changing the fonts and using some external fonts too but had no success. For some reason I didn't find a lot of help online again, despite the fact that this seems like a very normal problem other teams should have come across.

**Comment by PauloGasparSv** [comment] 2022-12-19 17:34
The slack discussion revealed this is a [known issue that we already choose to keep like that for now](https://github.com/Expensify/App/issues/13070#issuecomment-1349027136).


> I think we should actually just pay our Contributor and C+ and close this. This is a Windows/Linux problem, not an us problem.
> 
> I mentioned this in the PR, but for the future we have considered making all emojis custom images, or licensing from apple, both of which would solve this problem. However, both of those options are large undertakings that we are not going to do for a while so I think we can skip it for now.
> 

Closing this off for now!

**Closed by PauloGasparSv** 2022-12-19 17:34 UTC
Labels: Daily, Internal, Bug
