### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Save the World - Navigation problem on teachers contact page after a reload

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31895] opened 2023-11-27 00:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Click on FAB
2. Click Save the World > I am a teacher
3. Click on the "Update email address" button at the bottom. (or the 'contact methods' link)
4. Click on New contact method
4. Refresh page.
5. Click on the back button twice

## Expected Result:
Navigating back takes you to the "I am a Teacher" page

## Actual Result:
Navigating back takes you to the "Profile" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4af8536c-02b0-481c-aa74-ff3c31a56d76

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01635fe8e43e66eeee</li>
        <li>Upwork Job ID: 1728930388464914432</li>
        <li>Last Price Increase: 2023-11-27</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 27851097</li>
<li>ZhenjaHorbach | Contributor | 27851099</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-11-27 00:55
# Please re-state the problem that we are trying to solve in this issue.
Save the World - Navigation back doesn't work correctly on teachers new contact method page after a reload

# What is the root cause of that problem?
 the current contact-methods url is used in two places in the `teacher` url and in the profile settings so thats why we use the back to with the `/contact-methods` .. 

in  the case of the `/contact-methods/new`, when we click on back it brings us back to the contact-methods but doesnt specify the back-to 

so in the `/contact-methods/new` back navigation, we should add  backTo=`/settings/profile/contact-methods?backTo=%2Fteachersunite%2Fi-am-a-teacher` to the route

https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/settings/Profile/Contacts/NewContactMethodPage.js#L107

**Comment by shubham1206agra** [comment] 2023-11-27 01:49
@mkhutornyi Where did your proposal go?

**Comment by sukach318** [comment] 2023-11-27 01:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Save the World - Navigation problem on teachers contact page after a reload

### What is the root cause of that problem?
The root cause is just in this code line:
`const navigateBackTo = lodashGet(props.route, 'params.backTo', ROUTES.SETTINGS_PROFILE);`
This line of code is retrieving a parameter named `backTo` from the current route's parameters. If the `backTo` parameter is not present, the default value of `ROUTES.SETTINGS_PROFILE` will be used.
### What changes do you think we should make in order to solve the problem?

in [src/pages/settings/Profile/Contacts/ContactMethodsPage.js](url)
change 
`const navigateBackTo = lodashGet(props.route, 'params.backTo', ROUTES.SETTINGS_PROFILE);`
to
`const navigateBackTo = lodashGet(props.route, 'params.backTo', ROUTES.TEACHERS_UNITE);`

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-11-27 05:51
![image](https://github.com/Expensify/App/assets/58412969/d3ab13d3-f9c7-46fc-b304-bf99bc6148bc)

Just putting here for transparency.

Since @ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/31895#issuecomment-1827016675) has the correct RCA, and the solution. Let's go with this.
🎀 👀 🎀 C+ reviewed

Just a note for @ZhenjaHorbach, we should call it something else other than `backTo` as this might be a bit misleading

**Comment by shubham1206agra** [comment] 2023-11-27 13:52
> @shubham1206agra If my previous proposal is considered, just want to know what's wrong with my proposal. From guideline, the proposal doesn't need to be full code implementation. Accepted proposal is more like PR. I thought just idea was fine. Not complaining but just to consider for future issues. Thanks

Actually there's some explanation missing on why do we need backTo, and how did we reach the conclusion that we require backTo here.

**Comment by adelekennedy** [comment] 2023-12-13 17:13
### Payouts due:

Contributor: $500 @ZhenjaHorbach 
Contributor+: $500 @shubham1206agra 

@shubham1206agra will you complete the checklist above so we can close this out?

**Comment by shubham1206agra** [comment] 2023-12-18 06:28
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23063/
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23063#issuecomment-1859631457
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@adelekennedy] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2023-12-18 12:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
