### ISSUE TITLE
[$500] LHN - Pinned chat remains in the pinned position when unpinned

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32744] opened 2023-12-08 19:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to HT account with a lot of chats
3. Open a chat that is far from the top of LHN
4. Click 3-dot menu > Pin
5. Open any chat
6. Refresh the page
7. Open the pinned chat
8. Click 3-dot menu > Unpin

## Expected Result:
The pinned chat will return to its original position when unpinned

## Actual Result:
The pinned chat remains in the pinned position when unpinned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/75d44edc-ba07-4bcb-9ade-951e4eafe092

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016260213b2c35851c</li>
        <li>Upwork Job ID: 1733214428002885632</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by brunovjk** [comment] 2023-12-11 11:34
I couldn't reproduce, here it works normally in dev.new.expensify and staging

**Comment by CortneyOfstad** [comment] 2023-12-11 19:48
Same, I wasn't able to recreate either. Were you able to recreate this on your side?

**Comment by CortneyOfstad** [comment] 2023-12-12 13:50
Hey! Sorry for the confusion here, but we just got an internal update. Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759), we can close any bugs that are not related to Waves, so closing this out 👍 We will re-address once the waves are completed.

**Closed** 2023-12-12 13:50 UTC
Labels: External, Daily, Help Wanted, Bug
