### ISSUE TITLE
[HOLD for payment 2024-03-07] [LOW] [P2P] [$500] IOU - Delay in updating green dot and total amount when the net amounts cancel each other out for 2 users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33774] opened 2023-12-29 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User A has requested money from User B
1. Log in as User B
2. Go to 1:1 DM with User A > Click IOU preview
3. Request the same amount from User A to make the net owe become 0
4. Note the the green dot for the main chat in LHN
5. Return to main chat
6. Return to the IOU report
7. Delete the requested amount created in Step 3

## Expected Result:
In Step 3, once the net owe becomes 0, the green dot for the main chat in LHN will disappear
In Step 7, the new amount should update instantly

## Actual Result:
In Step 3, once the net owe becomes 0, the green dot for the main chat in LHN does not disappear, unless the main chat is visited
In Step 7, the total amount remains at 0, unless the report is revisited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9662059f-9076-4743-be9f-fdbbf9dbeaf2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d07091eedfc5a43</li>
        <li>Upwork Job ID: 1740800068445937664</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28079575</li>
<li>tienifr | Contributor | 28079576</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-29 18:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This is happening because we do not update the `hasOutstandingChildRequest` of the parent 1:1 report when requesting the money.

### What is the root cause of that problem?
In `IOU.getMoneyRequestInformation`, we need to calculate the total amount of the IOU Report, and if it's 0, optimistically set the chat report's `hasOutstandingChildRequest` to `false`.

### What changes do you think we should make in order to solve the problem?




### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2024-01-02 02:17
@lanitochka17 I don't think the title is very clear.

Am I correct in my understanding that the title should be something like: `Delay in updating green dot and total amount when the net amounts cancel each other out for 2 users`?

**Comment by shubham1206agra** [comment] 2024-01-03 12:19
@tienifr's [proposal](https://github.com/Expensify/App/issues/33774#issuecomment-1872472758) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by shubham1206agra** [comment] 2024-01-04 08:52
@mountiny Can you clarify the above comment?

**Comment by mountiny** [comment] 2024-01-04 16:09
Well regarding that line, thats about request money and setting the GBR optimistically which only happens in the workspace/ expense report case. You cannot request money from yourself in IOU case

**Comment by kbecciv** [comment] 2024-01-06 15:33
@jliexpensify Updated the title, thank you!

**Comment by thienlnam** [comment] 2024-01-08 02:48
https://github.com/Expensify/App/issues/33774#issuecomment-1877360599

Is there an additional question that there is confusion with?

**Comment by mountiny** [comment] 2024-01-09 00:19
Ah interesting, yeah I did not consider the case of deleting money request or requesting more than what you are owed to remove the GBR.

So yeah in that case we have more routes to cover. 

Requesting more than what you are owed in IOU case will remove the GBR.

This would also mean deleting money request on IOU or expense report, the GBR might change

Editing amount on the IOU report can change the report owner/ manager and update the GBR as well. 

Could we handle all of these cases in this one issue? I think its a fair scope given the changes are laid out clearly code-wise

**Comment by mountiny** [comment] 2024-01-11 23:24
@tienifr @shubham1206agra Can you note if you need any help with the additional cases?

**Comment by mountiny** [comment] 2024-01-12 12:44
@thienlnam @tienifr I have made a backend PR for this https://github.com/Expensify/Auth/pull/9653 

So this shoudl be resolved next week if there is anything else you need help with let us know

**Comment by jliexpensify** [comment] 2024-01-14 23:08
Not overdue

**Comment by jliexpensify** [comment] 2024-01-18 04:52
Not overdue, but am I correct in saying that Vit's PR was deployed and this should be now fixed?

**Comment by thienlnam** [comment] 2024-01-18 05:39
Vit's PR just unblocked the piece needed for the FE PR. We're still waiting for a FE fix here

**Comment by jliexpensify** [comment] 2024-01-18 05:41
Aha, thank you for clarifying!

**Comment by jliexpensify** [comment] 2024-01-21 21:30
Not overdue!

**Comment by jliexpensify** [comment] 2024-01-28 03:33
@shubham1206agra Hi, looks like you need to review the PR?

**Comment by shubham1206agra** [comment] 2024-01-28 06:25
I am OOO right now. Will review it on 30th

**Comment by jliexpensify** [comment] 2024-03-08 00:50
Payment Summary

- Contributor: @tienifr $500
- C+: @shubham1206agra $500 - Please complete checklist!

[NEW UPWORKS JOB](https://www.upwork.com/jobs/~014d416efbab525b48)

**Comment by jliexpensify** [comment] 2024-03-08 05:28
Paid and job closed

**Closed by jliexpensify** 2024-03-08 05:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
