### ISSUE TITLE
[$250] Avatar edit meus are not centered with avatars

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42715] opened 2024-05-28 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dannymcclain 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716912176919379

## Action Performed:
1. Open expensify 
2. Click on a Group, Personal, or Workspace avatar
3. Click on the edit icon to show the menu

## Expected Result:
The edit/context menu should be horizontally centered with the avatar.

## Actual Result:
The menu is 'slightly' off-center.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-05-28 at 10 55 52@2x](https://github.com/Expensify/App/assets/38435837/0deadb24-ee4e-4887-ab61-348da4f90675)

![Snip - (17) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/fcf28585-599f-4d05-94b1-472c990c5ef3)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01244bed1f8e5b6449</li>
        <li>Upwork Job ID: 1798194820757864448</li>
        <li>Last Price Increase: 2024-06-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by nkdengineer** [comment] 2024-05-29 09:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The menu is 'slightly' off-center.

### What is the root cause of that problem?
On large screen, we calculate the position of edit menu via `anchorRef` position. We already expect the edit menu is centered with avatars by update `horizontal` position here.

https://github.com/Expensify/App/blob/9d397782a7bd1bfa739d7cbb82837226b3269326/src/components/AvatarWithImagePicker.tsx#L299

But the problem is `variables.photoUploadPopoverWidth` is wrong. The edit popover content has width `335` and the container style of popover menu modal has `borderWidth: 1` that is defined here so the current width of this menu should be `337`.

https://github.com/Expensify/App/blob/9d397782a7bd1bfa739d7cbb82837226b3269326/src/styles/utils/generators/ModalStyleUtils.ts#L201


### What changes do you think we should make in order to solve the problem?
Change the `photoUploadPopoverWidth` variable to the correct value that is `337` as the reason in the RCA above 


https://github.com/Expensify/App/blob/9d397782a7bd1bfa739d7cbb82837226b3269326/src/styles/variables.ts#L207
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-06-06 04:18
@thesahindia For all cases, we only need to change the value of `photoUploadPopoverWidth`.

**Comment by nkdengineer** [comment] 2024-06-06 08:05
* Update

For the case `shouldUseStyleUtilityForAnchorPosition` is `true` we should update the style here to use `photoUploadPopoverWidth` variable instead of hard code like this. This can make sure the style will be correct if we change `photoUploadPopoverWidth`.

https://github.com/Expensify/App/blob/90dee7accae79c49debf30354c160cab6c52c423/src/styles/index.ts#L3556

**Comment by mvtglobally** [comment] 2024-06-10 12:36
Issue not reproducible during KI retests. (First week)

**Comment by chiragsalian** [comment] 2024-06-10 18:27
@dragnoir's [proposal](https://github.com/Expensify/App/issues/42715#issuecomment-2136019646) LGTM.
But does this issue still exist? mvtglobally says not reproducible. I tried testing but i couldn't tell for sure.

**Comment by kadiealexander** [comment] 2024-06-11 04:55
I also couldn't reproduce. Closing as fixed for now, please reopen if you disagree.

**Closed by kadiealexander** 2024-06-11 04:55 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
