### ISSUE TITLE
[$250] New account - Onboarding messages aren't present when selecting "Something else" in the modal

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45455] opened 2024-07-16 08:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/45248
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Lig in with a new Gmail account
3. Choose "Something else" in the onboarding modal
4. Input any first and last name and click on the "Continue" button
5. Open Chrome console
6. Paste and run "Onyx.log('nvp_onboarding');"
7. Copy the received chatReportID from the console
8. Paste it after the last "/" in the link and navigate to it: https://staging.new.expensify.com/r/

## Expected Result:
Onboarding messages should be visible.

## Actual Result:
Onboarding messages aren't present when selecting "Something else" in the modal. They're visible for all of the other onboarding options.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/63b56ee2-d7ab-44ac-8e13-e0ba769a5113

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec9d2ec7c34c29b9</li>
        <li>Upwork Job ID: 1813236871020557880</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by izarutskaya** [comment] 2024-07-16 08:32
We think this issue might be related to the #collect project.

**Comment by iwiznia** [comment] 2024-07-16 13:54
Hmmm wait, but I can also reproduce on prod... is this the message that I am not supposed to be seeing?
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/475959cc-2941-45a7-a175-ed25730a8492">

**Comment by kavimuru** [comment] 2024-07-16 15:26
@iwiznia  In step 6 

> Paste and run "Onyx.log('nvp_onboarding');

"`Onyx.log('nvp_onboarding'); `returns with an error in production, but onboarding message is not present for both production and staging when selecting "Something else" option.

**Comment by iwiznia** [comment] 2024-07-16 15:38
Seems this was triggered when testing https://github.com/Expensify/App/pull/45248 since the script does not work on prod cc @rojiphil @chiragsalian 

Not a blocker though

**Comment by trjExpensify** [comment] 2024-07-16 15:54
I'm still confused. 

>Onboarding messages aren't present when selecting "Something else" in the modal. They're visible for all of the other onboarding options.

There aren't any onboarding tasks when that onboarding intent is selected, so I wouldn't expect any.

**Comment by rojiphil** [comment] 2024-07-16 19:40
> Onboarding messages aren't present when selecting "Something else" in the modal.

I also think this is expected.
 
But what I don't understand is `They're visible for all of the other onboarding options`. 
My understanding is that onboarding messages are shown only when we have a workspace i.e. via `Manage my team's expenses`
@trjExpensify @chiragsalian Is this understanding correct?

**Comment by trjExpensify** [comment] 2024-07-17 00:15
>My understanding is that onboarding messages are shown only when we have a workspace i.e. via Manage my team's expenses

Nah, there's tasks for different onboarding intents. Just not the "something else" option. You have access to [the doc](https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.fvluo2r33dar) already to check out the UI of those if you're interested.

**Comment by rojiphil** [comment] 2024-07-17 01:48
> > My understanding is that onboarding messages are shown only when we have a workspace i.e. via Manage my team's expenses
> 
> Nah, there's tasks for different onboarding intents. Just not the "something else" option. You have access to [the doc](https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.fvluo2r33dar) already to check out the UI of those if you're interested.

Oh shoot! I got confused with the term `Onboarding messages`. Thanks for pointing out the document.

**Comment by rojiphil** [comment] 2024-07-17 01:50
Can we close this issue please if there is nothing to be fixed here?

**Closed** 2024-07-19 01:59 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
