### ISSUE TITLE
[$1000] Not showing loader on add bank account page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14425] opened 2023-01-19 23:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open settings -> Payments.
2. Press on Add payment method -> Bank account.
3. Observe loader is not display.

## Expected Result:
Loader should be display until preparing Plaid link.

## Actual Result:
Loader not showing on add bank account

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213583165-f8c044dc-f57e-4efb-ba48-928d997a3a90.mov

https://user-images.githubusercontent.com/43996225/213583333-3bbc82ae-0af2-4d86-aade-ffbd3bb28c2e.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674055957380549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a4fe2b93e051102</li>
        <li>Upwork Job ID: 1616549263858544640</li>
        <li>Last Price Increase: 2023-01-20</li>
    </ul>
</details>

**Comment by arielgreen** [comment] 2023-01-20 17:09
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by abdulrahuman5196** [comment] 2023-01-20 21:41
**Proposal**
Might be regression from https://github.com/Expensify/App/pull/14264
As we don't check if the token is present or not, we just end up not showing the loader in the UI. We would be required to check if the token is present without any errors to avoid recreating the issue the above PR intended to solve and to solve this loader not showing issue as well.

```diff
--- a/src/components/AddPlaidBankAccount.js
+++ b/src/components/AddPlaidBankAccount.js
@@ -115,7 +115,7 @@ class AddPlaidBankAccount extends React.Component {
         if (!plaidBankAccounts.length) {
             return (
                 <FullPageOfflineBlockingView>
-                    {lodashGet(this.props.plaidData, 'isLoading') && (
+                    {(lodashGet(this.props.plaidData, 'isLoading') || (!token && !plaidDataErrorMessage)) && (
                         <View style={[styles.flex1, styles.alignItemsCenter, styles.justifyContentCenter]}>
                             <ActivityIndicator color={themeColors.spinner} size="large" />
                         </View>
```
We can also use lodash function on the above.

**Comment by abdulrahuman5196** [comment] 2023-01-20 22:15
Yup @aimane-chnaif, saw now that https://github.com/Expensify/App/pull/14264 got merged only 3 hours ago. With latest main the issue is not reproducible.

**Comment by ctkochan22** [comment] 2023-01-20 22:34
This should be fixed with the noted PRs. Can we close?

**Comment by Pujan92** [comment] 2023-01-21 01:11
**Proposal**

**Issue**: On the read api call `OpenPlaidBankLogin` we don't set the loading state which seems to be issue here.

**Soltuion**: We need to update the plaidData `isLoading` onyx state on the read call `OpenPlaidBankLogin` which fetches the plaid token. 

```diff
diff --git a/src/libs/actions/Plaid.js b/src/libs/actions/Plaid.js
index 393b5bbc9..ac463b6d0 100644
--- a/src/libs/actions/Plaid.js
+++ b/src/libs/actions/Plaid.js
@@ -12,7 +12,29 @@ function openPlaidBankLogin(allowDebit, bankAccountID) {
     const params = getPlaidLinkTokenParameters();
     params.allowDebit = allowDebit;
     params.bankAccountID = bankAccountID;
-    API.read('OpenPlaidBankLogin', params);
+    API.read('OpenPlaidBankLogin', params, {
+        optimisticData: [{
+            onyxMethod: CONST.ONYX.METHOD.MERGE,
+            key: ONYXKEYS.PLAID_DATA,
+            value: {
+                isLoading: true,
+            },
+        }],
+        successData: [{
+            onyxMethod: CONST.ONYX.METHOD.MERGE,
+            key: ONYXKEYS.PLAID_DATA,
+            value: {
+                isLoading: false,
+            },
+        }],
+        failureData: [{
+            onyxMethod: CONST.ONYX.METHOD.MERGE,
+            key: ONYXKEYS.PLAID_DATA,
+            value: {
+                isLoading: false,
+            },
+        }],
+    });
 }
```

Also like other pages(IOUDetails, ...), we can use `FullScreenLoadingIndicator` instead `ActivityIndicator` here.

```diff
diff --git a/src/components/AddPlaidBankAccount.js b/src/components/AddPlaidBankAccount.js
index 386eea4c3..3a6c9b557 100644
--- a/src/components/AddPlaidBankAccount.js
+++ b/src/components/AddPlaidBankAccount.js
@@ -120,8 +122,8 @@ class AddPlaidBankAccount extends React.Component {
             return (
                 <FullPageOfflineBlockingView>
                     {this.props.plaidData.isLoading && (
-                        <View style={[styles.flex1, styles.alignItemsCenter, styles.justifyContentCenter]}>
-                            <ActivityIndicator color={themeColors.spinner} size="large" />
+                        <View style={[styles.flex1]}>
+                            <FullScreenLoadingIndicator />
```

---------------------------------------------

Other solution will be w.r.t to onyx key `plaidLinkToken` which we receives from backend, we need to modify the structure for onyx `plaidLinkToken` to object from string, which has 2 properties(1 for token, 1 for loading) and the same structure needs to receive from the api response with `Merge` operation.

**Comment by jatinsonijs** [comment] 2023-01-21 04:55
@Pujan92 It is fixed by https://github.com/Expensify/App/pull/13236, plz pull latest code and recheck

**Comment by Pujan92** [comment] 2023-01-21 08:35
@jatinsonijs Thanks, I pulled and now it is not reproducible.

@aimane-chnaif @ctkochan22 Isn't it good practice to update the `isLoading` state on success and failure case, otherwise in the case of failure it keeps spinning and won't show the error.

```diff
diff --git a/src/libs/actions/Plaid.js b/src/libs/actions/Plaid.js
index 0785a1fd9..76bbd2e0f 100644
--- a/src/libs/actions/Plaid.js
+++ b/src/libs/actions/Plaid.js
@@ -13,23 +13,42 @@ function openPlaidBankLogin(allowDebit, bankAccountID) {
     const params = getPlaidLinkTokenParameters();
     params.allowDebit = allowDebit;
     params.bankAccountID = bankAccountID;
-    const optimisticData = [{
-        onyxMethod: CONST.ONYX.METHOD.SET,
-        key: ONYXKEYS.PLAID_DATA,
-        value: {...PlaidDataProps.plaidDataDefaultProps, isLoading: true},
-    }, {
-        onyxMethod: CONST.ONYX.METHOD.SET,
-        key: ONYXKEYS.PLAID_LINK_TOKEN,
-        value: '',
-    }, {
-        onyxMethod: CONST.ONYX.METHOD.MERGE,
-        key: ONYXKEYS.REIMBURSEMENT_ACCOUNT_DRAFT,
-        value: {
-            plaidAccountID: '',
-        },
-    }];
 
-    API.read('OpenPlaidBankLogin', params, {optimisticData});
+    API.read('OpenPlaidBankLogin', params, {
+        optimisticData: [
+            {
+                onyxMethod: CONST.ONYX.METHOD.SET,
+                key: ONYXKEYS.PLAID_DATA,
+                value: {...PlaidDataProps.plaidDataDefaultProps, isLoading: true},
+            },
+        ],
+        successData: [
+            {
+                onyxMethod: CONST.ONYX.METHOD.MERGE,
+                key: ONYXKEYS.PLAID_LINK_TOKEN,
+                value: '',
+            },
+            {
+                onyxMethod: CONST.ONYX.METHOD.MERGE,
+                key: ONYXKEYS.PLAID_DATA,
+                value: {...PlaidDataProps.plaidDataDefaultProps, isLoading: false},
+            },
+        ],
+        failureData: [
+            {
+                onyxMethod: CONST.ONYX.METHOD.MERGE,
+                key: ONYXKEYS.REIMBURSEMENT_ACCOUNT_DRAFT,
+                value: {
+                    plaidAccountID: '',
+                },
+            },
+            {
+                onyxMethod: CONST.ONYX.METHOD.MERGE,
+                key: ONYXKEYS.PLAID_DATA,
+                value: {...PlaidDataProps.plaidDataDefaultProps, errors: {['Error Message']}, isLoading: false},
+            },
+        ],
+    });
 }
```

**Comment by eVoloshchak** [comment] 2023-01-23 19:08
Not overdue, seems like the issue has been fixed by https://github.com/Expensify/App/pull/13236, since it isn't reproducible anymore.

**Comment by arielgreen** [comment] 2023-01-24 19:19
Closing since this is now resolved.

**Closed by arielgreen** 2023-01-24 19:19 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by Pujan92** [comment] 2023-01-24 19:24
@eVoloshchak Can you plz check [my comment](https://github.com/Expensify/App/issues/14425#issuecomment-1399207995) as it says we are not hiding the loader in case of the error.

**Comment by eVoloshchak** [comment] 2023-01-24 20:44
@Pujan92, i've seen it, I think this is something worth reporting on Slack. It's different from our issue, since in your case spinner will be showing when it shouldn'r
