### ISSUE TITLE
Android - Search - App freezes and crashes after opening tasks from search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50270] opened 2024-10-04 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44.8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Tap FAB > Start chat
3. Select a user
4. Tap + > Assign tasks
5. Create 2 tasks
6. Navigate to the Search
7. Open the created tasks (it might take a few times)

## Expected Result:
User is able to open the created tasks from Search

## Actual Result:
The app freezes and then crashes after opening one of the created tasks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/bdf2a374-840c-48e3-9a60-a08397d87d18

[logs (2).txt](https://github.com/user-attachments/files/17263177/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-04 19:44
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by hungvu193** [comment] 2024-10-05 06:18
I think it will be dupe of https://github.com/Expensify/App/issues/49997

**Comment by bernhardoj** [comment] 2024-10-05 15:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App freeze when open task page.

### What is the root cause of that problem?
After doing some debugging, I found that the freeze is related to the animated style we have in SpacerView.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/components/SpacerView.tsx#L24-L28

I don't know, but using withTiming inside the useAnimatedStyle cause the issue.

### What changes do you think we should make in order to solve the problem?

Remove the withTiming from useAnimatedStyle 
```
const animatedStyles = useAnimatedStyle(() => ({
    borderBottomWidth: borderBottomWidth.value,
    marginTop: marginVertical.value,
    marginBottom: marginVertical.value,
}));
```

and instead, use it when trying to update the shared value.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/components/SpacerView.tsx#L39-L40

```
marginVertical.value = withTiming(values.marginVertical, {duration: CONST.ANIMATED_TRANSITION});
borderBottomWidth.value = withTiming(values.borderBottomWidth, {duration: CONST.ANIMATED_TRANSITION});
```

**Comment by joekaufmanexpensify** [comment] 2024-10-07 21:42
Closing since this has same RCA as the issue linked above

**Closed by joekaufmanexpensify** 2024-10-07 21:42 UTC
Labels: Daily, Bug

**Comment by bernhardoj** [comment] 2024-10-08 04:18
@joekaufmanexpensify I think this one is easier to reproduce. Maybe we can start working on this one and hold the other one.

**Comment by jjcoffee** [comment] 2024-10-08 08:17
@bernhardoj Do you think https://github.com/Expensify/App/issues/49997 has the same root cause? Or are you unable to reproduce it with those steps?

**Comment by bernhardoj** [comment] 2024-10-08 11:13
I was able to repro it, but it's really inconsistent to reproduce. Once I repro it when updating it > 20 times, once when updating it > 10 times.

This issue also requires opening the task multiple times, but it's only like 2-5 times.

**Comment by hungvu193** [comment] 2024-10-08 15:00
I can. reproduce both issues and it's an ANR, so @bernhardoj you probably should move your proposal here to  https://github.com/Expensify/App/issues/49997
