### ISSUE TITLE
Wallet- The wallet page keeps loading infinitely and "add payment method" is greyed out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25787] opened 2023-08-23 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Login using expensifail account
3. Tap profile icon
4. Tap Wallet

## Expected Result:
The wallet page should show content without loading and "add payment method" must not be greyed out

## Actual Result:
The wallet page keeps loading infinitely and "add payment method" is greyed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f871138a-ab81-4aab-a6b1-77ecde2c14bb

![Bug6174730_Screenshot_2023-08-23-21-26-11-289_com android chrome](https://github.com/Expensify/App/assets/78819774/30e35de3-863b-461f-9df1-2812d898d757)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment] 2023-08-23 18:41
I've run into some issues getting my Android emulator working, but I think they are sorted out now so I should be able to test the reproduction steps soon.

**Comment by mountiny** [comment] 2023-08-23 19:02
I cannot reproduce on iOS FWIW

**Comment by roryabraham** [comment] 2023-08-23 20:29
Not reproducible on Android w/ a normal (non-expensifail) account

**Comment by marcaaron** [comment] 2023-08-23 20:29
Checked this on my real life Android phone on the staging version of the app. It is not reproducible for me.

Gonna mark this as a "Needs reproduction" and remove the blocker.

**Comment by deetergp** [comment] 2023-08-29 00:23
I'm going to mark this Weekly and if nobody can reproduce it by the time it goes Overdue again, I'm going to close it.

**Comment by deetergp** [comment] 2023-09-12 00:51
Nobody has been in a rush to reproduce this one, so I am going to close it.

**Closed by deetergp** 2023-09-12 00:51 UTC
Labels: Engineering, Weekly, Needs Reproduction, Overdue
