### ISSUE TITLE
[HOLD for payment 2024-08-09] Ensure we show upgrade flow for GL/Payroll/Tax codes for non control policy.

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#45643] opened 2024-07-17 23:29 UTC
Coming from: [slack](https://expensify.slack.com/archives/C06ML6X0W9L/p1721253148286619?thread_ts=1721148029.626019&cid=C06ML6X0W9L)

GL/Payroll/Tax codes are available for control policies only. 
For policies of lower tier, we should show the upgrade flow.

- [x] Ensure the tag/category/tax field just says "Name"

<img width="350" alt="image" src="https://github.com/user-attachments/assets/cde549ca-b52e-4cfe-9076-1f044cd5b610">

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment] 2024-07-18 08:32
@isabelastisser will take as project lead for this initiative!

**Comment by isabelastisser** [comment] 2024-07-18 17:30
@dylanexpensify, what's the deadline? Just so you know, I will be OOO tomorrow and next week and will return on July 29. Please reassign it if needed. Thanks!

**Comment by dangrous** [comment] 2024-07-25 18:33
Taking this over from you @madmax330 since I needed to review anyway (fixes some tax code stuff)

**Comment by dylanexpensify** [comment] 2024-08-05 12:28
Payment coming up!

**Comment by brunovjk** [comment] 2024-08-08 12:21
I have reviewed the [PR](https://github.com/Expensify/App/pull/45866), @dangrous, can you assign me here so I can fill out the _proposal for regression test_? We have some issues (#45770 #46624) that have been fixed/closed as well, I believe we can create all the tests here. Thank you :D

**Comment by dangrous** [comment] 2024-08-08 13:23
done!

**Comment by brunovjk** [comment] 2024-08-08 18:13
**Regression Test Proposal**

**Test 1: Upgrade Modal for Non-Control Policies**
1. Go to a non-control policy.
2. Enable tags, taxes, and categories.
3. Go to categories, select a category.
4. Click `GL Code`. Verify the upgrade modal is shown. Return without upgrade.
5. Click `Payroll code` and verify that upgrade modal is shown.
6. Go to `Tags` and select a tag, then click `GL Code`. Verify the upgrade modal is shown.
7. Go to `Taxes` and select a tax, note that `Tax code` is empty.
8. Click on the `Tax code`. Verify the upgrade modal is shown.
9. Note that `Tax code` content is only shown after upgrading to Control.

**Test 2: Tax Code Validation**
1. Go to Workspace settings > Taxes in a Control policy.
2. Click any tax, then click the Tax code.
3. Without modifying it, save the tax code.
4. Verify no errors appear.

Do we agree 👍 or 👎

**Comment by dylanexpensify** [comment] 2024-08-09 13:38
Payment summary:
- Contributor: @rushatgabhane $250
- Contributor+: @brunovjk $250

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-08-09 13:45
[Job to apply!](https://www.upwork.com/jobs/~013030e515a7420b44)

**Comment by codinglife108** [comment] 2024-08-09 14:10
Hello. team
I have more interest about this but, Does anyone please add some more explanation to here ?
Thanks

**Comment by brunovjk** [comment] 2024-08-11 00:53
@dylanexpensify I applied for the [job](https://www.upwork.com/jobs/~013030e515a7420b44) but it seems strange to the usual, is everything ok? Thank you.

**Comment by dylanexpensify** [comment] 2024-08-12 10:49
@brunovjk sent offer! Did look odd, but all should be good now!

**Comment by JmillsExpensify** [comment] 2024-08-12 16:39
$250 approved for @rushatgabhane

**Comment by dylanexpensify** [comment] 2024-08-13 07:17
We're all done here

**Closed by dylanexpensify** 2024-08-13 07:17 UTC
Labels: Daily, Awaiting Payment, Bug
