### ISSUE TITLE
[$250] Hover on selected timezone does not change background color

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29129] opened 2023-10-09 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696839660892099

## Action Performed:
1. Open the app
2. Open settings->profile->timezone and open timezone
3. Hover on current selected timezone and observe that background color of value does not change to hover background color
4. Similarly, click green plus->request money and click on currency in manual
5. Hover over current selected value and app changes background color of the value to hover background color
## Expected Result:
App should change background color of current selected value to hover color on hover
## Actual Result:
App does not change background color of value to hover color on hover on current selected timezone
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/48c94c33-e1df-4737-8d96-8349a504b030

https://github.com/Expensify/App/assets/38435837/8e8358ba-8e37-42f1-9ae4-a9d87d7f83d6

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/bc86f3c1-cad8-488c-8353-86bee29fd1d9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131e2deef32d67dda</li>
        <li>Upwork Job ID: 1711495257750364160</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by vadymbokatov** [comment] 2023-10-09 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
when Hover on selected timezone does not change background color
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/964ddb893ee6e7e96d50a0ca2fa65989ffbdf682/src/components/SelectionList/BaseListItem.js#L27-L45
in this code isFocused && styles.sidebarLinkActive, covers the style assigned to hover state of PressableWithFeedback and only focus color is visible.
### What changes do you think we should make in order to solve the problem?
`<PressableWithFeedback
                onPress={() => onSelectRow(item)}
                disabled={isDisabled}
                accessibilityLabel={item.text}
                accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                hoverDimmingValue={1}
                hoverStyle={styles.hoveredComponentBG}
                dataSet={{[CONST.SELECTION_SCRAPER_HIDDEN_ELEMENT]: true}}
                style={[isFocused && styles.sidebarLinkActive]}
            >`
by moving style of isFocused from View to  PressableWithFeedback the element is able to change it on hover

**Comment by manancodes** [comment] 2023-10-09 22:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The list item should change colour when hovered over it, even if it is selected.

### What is the root cause of that problem?
The css class has been used on the wrong component.
https://github.com/Expensify/App/blob/b2d1c6f14f6eea1f1ccbaf3065a200f1094656f8/src/components/SelectionList/BaseListItem.js#L43

### What changes do you think we should make in order to solve the problem?
It should be used on the parent component.
This component is being used in a lot of places and it's the same problem everywhere. Making this change will fix this everywhere.

**Comment by cead22** [comment] 2023-10-10 00:21
This looks like a simple bug, and I imagine the solution will be simple as well, so I decreased the bounty

**Comment by shawnborton** [comment] 2023-10-10 17:04
This is not a bug, closing!

**Closed by shawnborton** 2023-10-10 17:04 UTC
Labels: External, Daily, Help Wanted
