### ISSUE TITLE
[$125] Web - Onboarding - Onboarding modal's corner become rectangular when hovering over the back button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48684] opened 2024-09-06 08:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1383@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign up with a new account
3. When the onboarding modal shows up click on something else
4. Hover over the back button and observe the corner of the modal

## Expected Result:
Nothing unusual happens to the corners of the onboarding modal

## Actual Result:
Corners of the onboarding modal become rectangular first until the tooltip shows up and reverts back to being curved

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/73604844-7cf9-44ba-94c9-4c2e16f31b29

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832074357963924539</li>
        <li>Upwork Job ID: 1832074357963924539</li>
        <li>Last Price Increase: 2024-09-27</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-09-06 08:18
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-09-06 08:18
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment] 2024-09-06 15:12
This seems like a basic styling issue. I'm going to set the price at $125.

**Comment by rlmorrison74** [comment] 2024-09-06 18:24
Just tried to reproduce on mac-chrome, but I'm not experiencing this issue.

**Comment by rlmorrison74** [comment] 2024-09-06 18:26
Contributor details
Your Expensify account email: rlmorrison.74@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010522cfcacf6a249a

**Comment by sandeeppal007** [comment] 2024-09-07 14:56
This issue is caused by a state re-render. When we hover over the back button, the card initially displays the default CSS, which lacks the border-radius property. Once the original CSS loads, the card becomes rounded as intended.

**Comment by sandeeppal007** [comment] 2024-09-07 15:06
Contributor details
Your Expensify account email: sandeeppal7902@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/sandeeppal

**Comment by sakluger** [comment] 2024-09-09 19:51
Added the retest-weekly label.

**Comment by sandeeppal007** [comment] 2024-09-10 02:06
I setup local env for the expensify on windows but it not working can  somebody help me.

**Comment by AttockOffice85** [comment] 2024-09-10 04:24
**Please re-state the problem that we are trying to solve in this issue.**
1. Corners of the onboarding modal become rectangular first until the tooltip shows up and reverts back to being curved.
2. If user slightly touch the border of the back button, and do not go further, the corners stay rectangular.
![image](https://github.com/user-attachments/assets/0206bdfc-4ebd-454b-8480-bf676f75251e)

**What is the root cause of that problem?**
The _BaseOnboardingPersonalDetails_ component's styling is not proper.

**What changes do you think we should make in order to solve the problem?**
I will adjust the styling of the _BaseOnboardingPersonalDetails_ component, which will eventually remove the bug. 

**What alternative solutions did you explore? (Optional)**
Overflow hidden on the component or it's parent.

**Contributor details**
**Your Expensify account email:** [attockofficeworkonly@gmail.com](mailto:attockofficeworkonly@gmail.com)
Upwork Profile Link: -------

**Comment by AttockOffice85** [comment] 2024-09-10 04:26
**Contributor details**
**Expensify account email:** [attockofficeworkonly@gmail.com](mailto:attockofficeworkonly@gmail.com)
**Upwork Profile Link:** -------

**Comment by Bakhtiar85** [comment] 2024-09-10 14:38
**Please re-state the problem that we are trying to solve in this issue.**
The corners of the onboarding modal turn rectangular when the tooltip is about to show up and revert back to being curved after the tooltip appears. If the user slightly touches the border of the back button without fully interacting, the corners remain rectangular.

**What is the root cause of that problem?**
The BaseOnboardingPersonalDetails component’s styling does not properly maintain the curved corners during specific interactions.

**What changes do you think we should make in order to solve the problem?**
I will adjust the styling of the BaseOnboardingPersonalDetails component to ensure that the modal's corners remain consistently curved, even when the tooltip is displayed or when interacting with the back button.

**What alternative solutions did you explore? (Optional)**
I explored using overflow: hidden on the component or its parent to keep the corners in place but found it less effective than directly fixing the component's styling.

**Contributor details**
Your Expensify account email: [makhdoomabubakar85@gmail.com](mailto:makhdoomabubakar85@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/makhdoomabubakar

**Comment by Bakhtiar85** [comment] 2024-09-10 14:38
Contributor details
Your Expensify account email: [makhdoomabubakar85@gmail.com](mailto:makhdoomabubakar85@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/makhdoomabubakar

**Comment by Bakhtiar85** [comment] 2024-09-10 14:40
Contributor details
Your Expensify account email: [makhdoomabubakar85@gmail.com](mailto:makhdoomabubakar85@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~017304c8ed7eb17c49

**Comment by Bakhtiar85** [comment] 2024-09-10 14:49
Contributor details:
Your Expensify account email: makhdoomabubakar85@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017304c8ed7eb17c49

**Comment by Bakhtiar85** [comment] 2024-09-13 16:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The corners of the onboarding modal initially appear rectangular until the tooltip displays, at which point they return to their curved state. Additionally, if the user lightly touches the edge of the back button without pressing further, the corners remain rectangular.

### What is the root cause of that problem?
The issue seems to stem from improper styling in the BaseOnboardingPersonalDetails component. This inconsistency causes the modal’s border-radius to temporarily reset.

### What changes do you think we should make in order to solve the problem?
I will adjust the CSS for the BaseOnboardingPersonalDetails component, ensuring the border-radius remains consistent, even when the tooltip appears or when hovering near the back button.

### What alternative solutions did you explore? (Optional)
One alternative approach is applying overflow: hidden either to the component itself or to its parent container to control any visual overflow that may be contributing to the issue.

**Comment by akinwale** [comment] 2024-09-16 12:40
Still looking for proposals that explain the exact root cause with an appropriate fix suggested.

**Comment by sakluger** [comment] 2024-09-19 16:34
Hmm, we never got a retest by QA.

@AttockOffice85 @Bakhtiar85  @ra-md were you all able to reproduce this issue after Sept 9?

**Comment by akinwale** [comment] 2024-09-23 13:50
@ra-md Do you have a reference or an explanation for the cited bug? Is there an existing bug report filed with Chromium?

**Comment by wildan-m** [comment] 2024-09-24 03:57
Issue not replicated in Chrome Version 128.0.6613.139 on macOS. The original poster was using Windows; could this be a Chrome bug specific to Windows? Which Chrome version was utilized by the tester?

**Comment by sakluger** [comment] 2024-09-25 20:14
@ra-md could you please clarify which operating system and version of the app you were using when you reproduced the issue? And could you please answer @akinwale's question [here](https://github.com/Expensify/App/issues/48684#issuecomment-2368332448)? Thanks!

**Comment by sakluger** [comment] 2024-09-30 14:36
I can't reproduce this one in Mac Chrome (Version 128.0.6613.138). Given the low impact on users and the difficulty in reproduction, I'm going to close this one for now so we can focus on higher impact bugs.

**Closed by sakluger** 2024-09-30 14:36 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug, retest-weekly
