### ISSUE TITLE
[$500] Approve button not disappear after approving report offline if advanced approval set

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47264] opened 2024-08-12 20:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19.2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/44940
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: create a control workspace, set "Manually approve all expenses" over to $10 and set advanced approval in OD:
- boss owner (admin) submits to mini owner
- mini owner (admin) submits boss owner
- manager (employee) submits to mini owner forwards to mini owner over limit forwards (limit 100) to boss owner
- employee 1 (employee) submits to manager
- employee 2(employee) submits to manager

1. Log in as an employee 1 and submit an expense below $100, e.g. $25
2. Log in as an manager
3. Disable internet connection
4. Approve the report

## Expected Result:
The approve button dsiappears

## Actual Result:
The approve button is still displayed until user returns online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b3f27ae-2414-42d4-9b3b-e62419645ce4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01682c8c3ddb795078</li>
        <li>Upwork Job ID: 1829413690213012581</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103937090</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by izarutskaya** [comment] 2024-08-12 20:35
Production

https://github.com/user-attachments/assets/fc7a8c83-a0e7-40f9-a214-034a3fdb4ea9

**Comment by Beamanator** [comment] 2024-08-12 23:55
I'd say this isn't a blocker since advanced approvals in NewDot are quite new - I'll get @rushatgabhane and @mananjadhav to look into this ASAP (tomorrow hopefully) 🙏  - see https://github.com/Expensify/App/pull/44940#issuecomment-2284943045

**Comment by adelekennedy** [comment] 2024-08-19 21:37
@Beamanator any updates on this from @mananjadhav and @rushatgabhane? Should I assign them here?

**Comment by mananjadhav** [comment] 2024-08-20 21:12
I can take a look at this tomorrow.

**Comment by marcaaron** [comment] 2024-08-24 00:56
@mananjadhav Any update?

**Comment by adelekennedy** [comment] 2024-08-27 18:34
@mananjadhav were you able to get to this one?

**Comment by mananjadhav** [comment] 2024-08-28 17:06
I couldn't get to this one. I'll try to get to this by tomorrow.

**Comment by adelekennedy** [comment] 2024-08-28 20:19
Great! If you don't have time we'll reassign to get it moving forward!

**Comment by mananjadhav** [comment] 2024-08-29 20:00
@adelekennedy I haven't got time to take a look at the issue. We can open up for External contributors and I can help with the review if needed.

**Comment by adelekennedy** [comment] 2024-09-04 00:28
Still seeing if someone has time to pick this up

**Comment by garrettmknight** [comment] 2024-09-06 17:20
Let's get some action on this one.

**Comment by FitseTLT** [comment] 2024-09-06 18:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Approve button not disappear after approving report offline if advanced approval set

### What is the root cause of that problem?
When there is an advanced approval chain the report status will not change to approved status
https://github.com/Expensify/App/blob/812fc316a007b711d62a986582d19440c2c1dad8/src/libs/actions/IOU.ts#L6922
but instead the manager id will be changed to the next approver but we are not updating the managerID of the expense report 
https://github.com/Expensify/App/blob/812fc316a007b711d62a986582d19440c2c1dad8/src/libs/actions/IOU.ts#L6938-L6948
### What changes do you think we should make in order to solve the problem?

We need to set the manager id optimistically to next approver id
```
    const currentUserApprovalIndex = approvalChain.findIndex((email) => email === currentUserEmail);
    const managerID = isLastApprover(approvalChain) || currentUserApprovalIndex === -1 ? expenseReport?.managerID : getAccountIDsByLogins([approvalChain[currentUserApprovalIndex + 1]])[0];

```
and set the managerID of the expense report optimistically here
https://github.com/Expensify/App/blob/812fc316a007b711d62a986582d19440c2c1dad8/src/libs/actions/IOU.ts#L6942-L6946
### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-09-07 23:57
@mananjadhav are you able to review proposals here or should we reassign?

**Comment by rushatgabhane** [comment] 2024-09-07 23:59
i can take a look ^

**Comment by mananjadhav** [comment] 2024-09-08 03:51
I’ll review in an hour.

**Comment by mananjadhav** [comment] 2024-09-08 05:02
Reviewing the proposal now.

**Comment by mananjadhav** [comment] 2024-09-08 05:48
@FitseTLT I understand adding the managerID to the optimistic steps but when I was trying to access the props last time this is what I found.

```
{
    "isCurrentUserManager": true,
    "isOpenExpenseReport": false,
    "isApproved": false,
    "iouSettled": false,
    "isArchivedReport": false
}
```
Essentially the `canApproveIOU` was returning `true` and if you see `currentManagerID` is already true based on the `iouReport.managerID`. So I am not sure how this is getting fixed. Can you please clarify?


https://github.com/Expensify/App/blob/9affb1384815fa8155fe23c523127c1e72b1120d/src/libs/actions/IOU.ts#L6812-L6833

**Comment by FitseTLT** [comment] 2024-09-09 09:58
>Essentially the canApproveIOU was returning true and if you see currentManagerID is already true based on the iouReport.managerID. So I am not sure how this is getting fixed. Can you please clarify?

Yeah. @mananjadhav This is exactly the reason my solution fixes it(BTW I have already tested my solution works perfectly). The reason the approve button exists after pressing the approve button is because the current user is still the manager.
There are two cases for the approve action btw:
1. For simple approve flow as soon as you press the button the iou report will be changed into approved state (so the approve button will disappear)
2. But for our case here, advanced approval flow, the iou report state will not change because there is unfinished approval flow and there is still another approver to approve it and the iou report state will change to approved only when the last approver in the approval chain approves it. So when the current user is not the last approver in the chain what BE does (and also what I have done in optimistic data) is the `managerID` of the iou report will be set to the next approver and the approve button will disappear because the current user will not be manager anymore (`isCurrentUserManager` is false).

**Comment by mananjadhav** [comment] 2024-09-10 12:23
@FitseTLT Do you mind uploading the video of the fix you've applied? I'll take a look again at my end too.

**Comment by FitseTLT** [comment] 2024-09-10 13:22
Here is a test branch https://github.com/FitseTLT/App/tree/fix-approve-button-in-offline

https://github.com/user-attachments/assets/087fffaf-1b3d-4ef3-bc48-3e2ab31aa737

**Comment by trjExpensify** [comment] 2024-09-11 01:14
>Precondition: create a control workspace

This is an advanced approvals bug with the prerequisite being a control workspace, moving to #wave-control.

**Comment by mananjadhav** [comment] 2024-09-12 13:08
Thanks for sharing the branch. I tested the flow and it worked fine. I was attempting a different change from yours and hence it didn't work for me.

I think @FitseTLT's [proposal](https://github.com/Expensify/App/issues/47264#issuecomment-2334639798) looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by adelekennedy** [comment] 2024-09-18 01:45
PR is in progress

**Comment by adelekennedy** [comment] 2024-10-01 00:09
Deployed to prod today!

**Comment by mananjadhav** [comment] 2024-10-08 16:42
@adelekennedy this should be ready for payout. I couldn't exactly pinpoint the offending PR. Closest I think this should've been a part of https://github.com/Expensify/App/pull/44940/files. 

Meanwhile I don't know if a regression test exists for the whole advance approval workflow. @adelekennedy can you confirm this? I think it should exists and in that case we don't need a regression test here.

**Comment by adelekennedy** [comment] 2024-10-09 16:47
Payouts due:

- [ ] Contributor: $500 @FitseTLT (Upwork) @FitseTLT will you confirm you received the payment? I know we've been experiencing an Upwork bug, in this case i released payment first and then closed the contract
- [ ] Contributor+: $500 @mananjadhav (NewDot)

Upwork job is [here](https://www.upwork.com/jobs/~01682c8c3ddb795078).

**Comment by FitseTLT** [comment] 2024-10-09 16:51
@adelekennedy I received the payment Thx!

**Comment by AngadManroy** [comment] 2024-10-13 20:25
is the issue still live?

**Closed** 2024-10-14 02:25 UTC
Labels: Reviewing, External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-15 01:13
$250 approved for @mananjadhav

**Comment by mananjadhav** [comment] 2024-10-15 04:41
@garrettmknight The amount is $500.
