### ISSUE TITLE
[HOLD for payment 2023-09-21] [$500] Dev: Web - Console error on request money thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26092] opened 2023-08-28 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select request money option
2. Enter amount and click on Next button
3. Click on any user and request money
4. Go to request money thread

## Expected Result:
It should not show any console error

## Actual Result:
Console error appears (Warning: Failed prop type: Invalid prop `source` supplied to `Image`, expected one of type [number].)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.57.5
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/07b92b8e-aa52-44a6-8b6c-298f62800f25

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692679550499059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01157770cac8c77081</li>
        <li>Upwork Job ID: 1696964639125438464</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 26442047</li>
<li>gadhiyamanan | Reporter | 26442049</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-28 15:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error for opening a report of money request view

### What is the root cause of that problem?
It persists after this [PR](https://github.com/Expensify/App/pull/22562) merged where the image source is passed as a string which should be the either number or object.
https://github.com/Expensify/App/pull/22562/files#diff-53a3b5c2e20375a2d0d3a700bd76dab7791ddc968e942d510a9e06572dc0e26fR57
https://github.com/Expensify/App/blob/7b5fadf5ef4300e38f99867b38e9a25ad583c194/src/components/Image/imagePropTypes.js#L10-L17

### What changes do you think we should make in order to solve the problem?
We need to pass it as an object by setting its `uri` property.
`source={{uri: EmptyStateBackgroundImage}}`
https://github.com/Expensify/App/blob/7b5fadf5ef4300e38f99867b38e9a25ad583c194/src/components/ReportActionItem/MoneyRequestView.js#L120

**Comment by sonialiap** [comment] 2023-08-30 19:14
Reproducible, triaging to external

**Comment by shubham1206agra** [comment] 2023-08-31 06:16
@parasharrajat There's a slight problem with the approach approved by you.

See this in the iOS native.

<img width="1512" alt="Screenshot 2023-08-31 at 11 43 07 AM" src="https://github.com/Expensify/App/assets/58412969/29c4cc4c-fcef-464b-8320-f27192def8f0">


Can you please re-review the proposal?

**Comment by shubham1206agra** [comment] 2023-08-31 06:34
The problem is that native and web uses different resolvers for image source resolution
On the web we see a string URL as a source but on native we see a number as source 

So your selected solution will cause prop error but now on native

**Comment by shubham1206agra** [comment] 2023-08-31 06:40
See this
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/58412969/4afccc8b-c671-4fa1-bae7-438e463ed3c6">

**Comment by shubham1206agra** [comment] 2023-08-31 13:45
@parasharrajat Can you review the proposal again in this case, please?

**Comment by sonialiap** [comment] 2023-09-19 07:12
@parasharrajat are we writing a regression test for this?

**Comment by sonialiap** [comment] 2023-09-19 07:18
Payments

@parasharrajat review + bonus = $750 - please request in NewDot
@shubham1206agra fix + bonus = $750 - paid ✔️ 
@gadhiyamanan report = $50 - I'm not seeing an option to pay you. Have you accepted the offer?

**Comment by gadhiyamanan** [comment] 2023-09-19 07:23
@sonialiap offer accepted. i think reporting bonus should be $250 because it was logged before 30 Aug (before [announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649))

**Comment by sonialiap** [comment] 2023-09-26 06:24
@gadhiyamanan agreed, thanks for pointing out that Melvin miscounted. I'm correcting that to $250 for the reporting

**Comment by sonialiap** [comment] 2023-09-26 06:26
@parasharrajat bump on the regression test question (are we writing one for this issue?)

**Comment by thienlnam** [comment] 2023-09-30 09:41
Agreed - seems like we're just waiting on NewDot payout before closing this one out?

**Comment by sonialiap** [comment] 2023-10-04 04:54
Thanks for confirming that we don't need a regression test. In that case I'm closing out the issue since we do not need to keep the issue open for payout via NewDot

**Closed by sonialiap** 2023-10-04 04:54 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:44
$750 payment approved for @parasharrajat based on BZ summary.
