### ISSUE TITLE
[HOLD for payment 2023-09-07] [$500] Redirect icon is not highlighted on hover

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25692] opened 2023-08-22 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the staging Expensify website.
2. Click on the plus sign and select "Request Money".
3. Add a desired amount and an email address.
4. Click on the requested money.
5. Observe that the redirect icon
## Expected Result:
The redirect icon should be highlighted on hover
## Actual Result:
The redirect icon is not highlighted on hover
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/4c379c93-e89d-46b4-afae-927fe4a01991

https://github.com/Expensify/App/assets/38435837/170eca4f-078e-4c7a-86cb-28511707926c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692685377725719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138f9abcf1acbfcc9</li>
        <li>Upwork Job ID: 1694124812688658432</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>dhairyasenjaliya | Contributor | 26374116</li>
<li>tewodrosGirmaA | Reporter | 26374119</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-08-22 16:32
This doesn't need to be a deploy blocker, it doesn't block any user actions, and while it's not the intended styling, it doesn't make the feature confusing to the user.

**Comment by FrancisJTR7** [comment] 2023-08-23 00:09
Proposal: Simply change the color to the "highlighted" color on hover. This would be from #8B9C8F to #9DADA8.  This can be done by changing color on hover or if that doesn't work by applying a second icon above it which changes opacity to reveal different colors on hover, etc.. there are many ways to fix this.

**Comment by FrancisJTR7** [comment] 2023-08-23 00:12
Contributor details
Your Expensify account email: xgalasko@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0144bc7dc4388ee107

**Comment by sakluger** [comment] 2023-08-23 21:06
@allroundexperts could you please take a look at @dhairyasenjaliya's proposal?

@FrancisJTR7 all proposals must follow the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) from our Contributing Guide.

**Comment by FrancisJTR7** [comment] 2023-08-23 21:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When hovered, the reinstate icon should light up to #9DADA8 from #8B9C8F, this is currently not occurring. 
### What is the root cause of that problem?
The icon does not have an on hover state to change it.
### What changes do you think we should make in order to solve the problem?
Simply change the color to the "highlighted" color on hover. This would be from #8B9C8F to #9DADA8.
### What alternative solutions did you explore? (Optional)
By applying a second icon above it which changes opacity to reveal different colors on hover, etc.

**Comment by sakluger** [comment] 2023-09-12 04:14
**Summarizing payouts for this issue:**

Reporter: @tewodrosGirmaA $250 (paid on Upwork
Contributor: @dhairyasenjaliya $750 (paid on Upwork)
Contributor+: @allroundexperts $750 (payable via Manual Request after BZ checklist is completed)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~0138f9abcf1acbfcc9

**Comment by sakluger** [comment] 2023-09-12 04:15
@allroundexperts please let me know once you have finished the BZ checklist and requested payment via NewDot so that I can close the issue, thanks!

**Comment by sakluger** [comment] 2023-09-14 17:26
@allroundexperts any updates on the checklist?

**Comment by sakluger** [comment] 2023-09-18 05:17
Looks good to me! @allroundexperts please feel free to request the payment, and thanks again!

**Closed by sakluger** 2023-09-18 05:17 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 12:48
$750 payment for @allroundexperts approved based on BZ summary.
