### ISSUE TITLE
[Pay Meow][$500] Web - Report - The loading skeleton has no animation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37420] opened 2024-02-28 13:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4347568
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with an HT account that has a lot of conversations in it
3. Turn off the internet
4. Navigate to any conversation with a large correspondence history
5. Scroll through the correspondence history to the beginning so that the loading skeleton appears

## Expected Result:
The loading skeleton should have animation

## Actual Result:
The loading skeleton has no animation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4ede35b0-7ab0-4964-87ff-61e09acc074f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018fdeb7fea12452b0</li>
        <li>Upwork Job ID: 1764756355855122432</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-28 13:16
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment] 2024-02-28 13:17
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by isabelastisser** [comment] 2024-02-28 16:27
Reviewing.

**Comment by isabelastisser** [comment] 2024-02-28 17:11
I don't have the Troubleshoot section in staging. Can you share instructions on how to access that specific command? Thanks!

**Comment by isabelastisser** [comment] 2024-02-29 18:28
bump @kbecciv

**Comment by kbecciv** [comment] 2024-03-04 14:49
@isabelastisser QA team was using expensifail account, there is no specific step

**Comment by isabelastisser** [comment] 2024-03-05 15:16
Hi @situchan, can you please review the proposal above? Thanks!

**Comment by kmbcook** [comment] 2024-03-05 22:36
Doesn't animation indicate to the user that content is actually loading? In this case there is no internet connection, and therefore no loading. Isn't this expected behavior?

**Comment by situchan** [comment] 2024-03-06 10:08
Thanks for the proposals. I think we can wait for upstream fix.
Meanwhile, we can bump this to weekly.
cc: @isabelastisser

**Comment by abzokhattab** [comment] 2024-03-06 10:09
I agree lets see when the author fixes it

**Comment by abzokhattab** [comment] 2024-03-06 10:38
@tienifr  I spent more than 1.5 hours getting the root cause and it took me time to know that Chromioum had a breaking change as there are no results on Google for such an issue, and I already mentioned the GitHub issue addressing this part. so your comment is actually considered a subset of my proposal since the PR is mentioned in [referenced issue](https://github.com/danilowoz/react-content-loader/issues/316#issuecomment-1979504372).  

i don't wanna get into this argument, as we are building a cooperative environment so i am leaving it to the C+ to decide.

Have a good day!

**Comment by situchan** [comment] 2024-03-06 10:44
@abzokhattab to get assigned, please be active on upstream issue/PR to get this bug resolved asap rather than just waiting for the version bump.

**Comment by situchan** [comment] 2024-03-07 21:03
@isabelastisser https://github.com/Expensify/App/issues/37420#issuecomment-1980513814

**Comment by abzokhattab** [comment] 2024-03-07 21:04
The author fixed the issue and we are waiting for [the PR](https://github.com/danilowoz/react-content-loader/pull/317) to be merged

**Comment by abzokhattab** [comment] 2024-03-08 17:50
The PR was merged … lets upgrade the version

**Comment by situchan** [comment] 2024-03-08 17:59
I recommend @abzokhattab as they first found out the correct root cause.
Proposal: https://github.com/Expensify/App/issues/37420#issuecomment-1977846461
Aka. Upstream PR what @tienifr mentioned was raised after @abzokhattab posted proposal. So it's fair to assign @abzokhattab.
🎀 👀 🎀 C+ reviewed

**Comment by chiragsalian** [comment] 2024-03-08 18:17
Hmm, I'm actually tending towards @tienifr solution. It looks like this PR was merged - https://github.com/danilowoz/react-content-loader/pull/317#issuecomment-1980499545 so won't just updating our react-content-loader to `7.0.0` suffice. Thoughts?

**Comment by situchan** [comment] 2024-03-08 18:20
> If that PR was still in progress i would have suggested @abzokhattab since its hard to tell something when i PR will be done but over here it looks like its done.

That's exactly what I said here:

> Aka. Upstream PR what @tienifr mentioned was raised after @abzokhattab posted proposal

Upstream [PR](https://github.com/danilowoz/react-content-loader/pull/317) was created 17 hrs after @abzokhattab posted proposal

**Comment by situchan** [comment] 2024-03-08 18:23
@chiragsalian I just prioritized research and efforts they made for this issue but if you think @tienifr should be assigned for mentioning version bump, please go ahead.

**Comment by situchan** [comment] 2024-03-08 18:26
> won't just updating our react-content-loader to `7.0.0` suffice

In case you confused, this will be final solution of course even if @abzokhattab was assigned. Not patch like their original proposal.

**Comment by chiragsalian** [comment] 2024-03-08 18:39
Ah I see. Cool, thanks for that context. Yes, that sounds good to me.
Proposal LGTM, feel free to create the PR @abzokhattab.

**Comment by abzokhattab** [comment] 2024-03-09 11:20
@tienifr Please take it easy, I understand where your anger comes from however the current issue is not a normal case. I appreciate your efforts, but it's essential to note that my initial proposal pinpointed the library issue well before the PR was linked to the issue (17 hours after my proposal was posted, as @situchan mentioned). Your proposal, though valuable, essentially referred back to the PR that **emerged from discussions I had already referenced**.

Given this sequence, my contributions in finding the root cause and helping in finalizing the PR laid the groundwork for addressing the issue, which justifies my assignment here.

Thanks.

**Comment by abzokhattab** [comment] 2024-03-09 11:20
@situchan  @chiragsalian  [the PR](https://github.com/Expensify/App/pull/38016) is ready.

**Comment by situchan** [comment] 2024-03-10 12:40
I raised [internal discussion](https://expensify.slack.com/archives/C02NK2DQWUX/p1709952046203849) yesterday. We'll provide update soon after weekend is over.

**Comment by abzokhattab** [comment] 2024-03-11 03:01
One more time, a clarification for the comments timeline: 
1. **5th of March at 4:42am**:  I found the root cause of the issue and was able to reference the github issue of the library which fixed the bug  ... at that time the only available solution was [this one](https://github.com/danilowoz/react-content-loader/issues/316#issuecomment-1976998203), and since we want to fix our bugs fast, i didn't wait for the PR to be raised and added the proposal 
2. **5th of March at 9:40pm** : the library author found a [solution](https://github.com/danilowoz/react-content-loader/issues/316#issuecomment-1979504372) then created the PR and linked it to the issue 
3. **6th of March at 11.47am**: Tienifr checked the newest comment on the issue I already referenced and added a proposal referring to the author's PR

Given this sequence, my contributions in finding the library issue which was later linked to the PR justifies the assignment.

Thanks.

**Comment by mallenexpensify** [comment] 2024-03-11 21:41
Commented on [the Slack convo ](https://expensify.slack.com/archives/C02NK2DQWUX/p1710193248370519?thread_ts=1709952046.203849&cid=C02NK2DQWUX)to help move this along. 
> First, we want to avoid competition when we're all working towards the goal of fixing a bug (I know this seems counter-intuitive where multiple proposals are submitted but, in the end, we're looking for what everyone thinks is best, then moving forward)
Second, upstream fixes, and those that happen quickly, are edge cases.  Everyone will always be different.  It takes research on the part of a contributor to find or create the upstream issue.

For edge cases, we don't have them documented in CONTRIBUTING.md because they're rare and we manage them 1:1.

Without full knowledge, and with me not being an engineer, my hunch is...
- Increase the job price from $500 to $750 then split the total.  If there's an equal amount of work it can be 50/50. If one contributor takes the lead, especially on the PR and the test steps then a $250/$500 split seems like it'd be more fair (that way the PR author would be getting the full job price of the issue)

**Comment by abzokhattab** [comment] 2024-04-04 21:04
I think the regression/payment bot didn't work in this issue .. the PR was merged to prod more than a week ago.

**Comment by mallenexpensify** [comment] 2024-04-06 00:26
Thanks @abzokhattab . 
@abzokhattab , @situchan , @tienifr can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~018fdeb7fea12452b0

I think I accidentally sent multiple offers, please only accept one.

**Comment by abzokhattab** [comment] 2024-04-06 00:32
Thanks Matt @mallenexpensify  for your understanding in this issue, I have just accepted the offer.

Up to the next one!

**Comment by mallenexpensify** [comment] 2024-04-07 21:54
Contributor: @tienifr paid $250 via Upwork
Contributor: @abzokhattab paid $500 via Upwork
Contributor+ @situchan **owed** $500 via Upwork, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~018fdeb7fea12452b0

**Comment by isabelastisser** [comment] 2024-04-08 15:57
Thanks for handling the. paymentS, @mallenexpensify 

Bump @situchan 

Contributor+ @situchan owed $500 via Upwork, can you please accept the job and reply here once you have?
https://www.upwork.com/jobs/~018fdeb7fea12452b0

**Comment by isabelastisser** [comment] 2024-04-10 19:44
Hey @situchan, please follow up on my comment above.

**Comment by isabelastisser** [comment] 2024-04-15 16:32
Bump @situchan, please accept the offer and I will process the payment in Upwork. Thanks!

**Closed by isabelastisser** 2024-04-15 16:32 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by situchan** [comment] 2024-05-20 07:35
@isabelastisser sorry I am back from vacay. Can you please send new offer? Old one was expired.

**Comment by isabelastisser** [comment] 2024-05-20 17:54
Thanks for the heads up, @situchan ! I will send a new offer now.
