### ISSUE TITLE
iOS isn't loading new chats in Left Hand Nav (LHN)/main list of chats.

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10484] opened 2022-08-23 04:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Opened app

## Expected Result:
To see current chats listed

## Actual Result:
Chats from a week and a half ago are showing, new ones aren't

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.88-14
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661195981757409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-08-23 20:21
Gonna close cuz I think it's a dupe of https://github.com/Expensify/App/issues/9382

**Closed by mallenexpensify** 2022-08-23 20:21 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction
