### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Web - User is unable to download attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22133] opened 2023-07-03 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Upload a picture attachment
3. Open the picture
4. Click on 'download' icon

## Expected Result:
Image should be downloaded

## Actual Result:
A new URL is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8288fb8e-b9ce-4653-a5f2-049f3d9920e8

https://github.com/Expensify/App/assets/93399543/87266724-e7b4-49be-912b-2e056fa985af

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688411675617159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168bae7edd97168e9</li>
        <li>Upwork Job ID: 1676239642199293952</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by kashn11** [comment] 2023-07-03 20:10
this issue is due to cors error

**Comment by kashn11** [comment] 2023-07-03 20:14
Contributor details
Your Expensify account email: kashanilyas098@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a6a250468eeb61d8

**Comment by Julesssss** [comment] 2023-07-04 09:45
Not a blocker, also likely already existed on staging

**Comment by kidroca** [comment] 2023-07-04 13:51
I have identified the root cause of this issue in a specific change from [this pull request](https://github.com/Expensify/App/pull/20365/files#r1252049731), where I've also left a note for reference.

In the `AttachmentModal` component, two types of views are conditionally rendered: a single image view and a carousel view. When the carousel view is active, we depend on the `onNavigate` callback to update the attachment data, including `source`, `file`, and `isAuthTokenRequired`. This callback is triggered both initially and upon any change, ensuring that the modal's state is always correctly updated.

The transition to a function-based component unfortunately overlooked the need to update the `isAuthTokenRequired` state. This state is crucial for the carousel logic to function as expected. Hence, the absence of its update is causing the issue we're seeing.

**Comment by kidroca** [comment] 2023-07-04 14:19
@Julesssss 
I've included the suggested fix in my PR as it also changes the `onNavigate` logic 
It's a small PR and I hope it's not a problem to combine 2 fixes
- https://github.com/Expensify/App/pull/22179

I'll provide test steps to verify the download issue is resolved

**Comment by Julesssss** [comment] 2023-07-04 14:40
Excellent find, thank you. I'm going to assign you to this issue and generate an Upwork job for it.

**Comment by Julesssss** [comment] 2023-07-04 14:41
@muttmuure @laurenreidexpensify it assigned you both somehow 😕

**Comment by Julesssss** [comment] 2023-07-04 14:42
@Santhosh-Sellavel, I assigned you to the PR review

**Comment by Santhosh-Sellavel** [comment] 2023-07-04 16:51
@Julesssss @allroundexperts

We follow random assigning to spread issues across the team fairly. If we start picking issues based on previous PR then only one C+ will be reviewing all PRs related to a specific feature or improvements.

**Comment by Santhosh-Sellavel** [comment] 2023-07-04 17:10
Yeah, I can see that buddy, we had similar cases in the past and we will continue to have those in the future as well. Where someone from an expert agency or an expert contributor like Kidorica will be working on a new feature or specific improvements which will have multiple PRs also.

**Comment by kidroca** [comment] 2023-07-04 19:56
PR is ready for review 
- https://github.com/Expensify/App/pull/22179

**Comment by Julesssss** [comment] 2023-07-05 08:09
Fair point @Santhosh-Sellavel. Let's stick with auto-assigner (outside of the C+ channel) 👍

**Comment by Julesssss** [comment] 2023-07-05 12:55
Hey @laurenreidexpensify, when we get to the payout stage please can we use NewDot instead of UpWork? Thanks

**Comment by laurenreidexpensify** [comment] 2023-07-06 07:30
Assigning @anmurali for the payout

**Comment by laurenreidexpensify** [comment] 2023-07-18 09:29
@Santhosh-Sellavel your payment will be issued in newdot on the C+ payment pilot cc @JmillsExpensify @anmurali 

@Natnael-Guchima @kidroca apols for late offers, but your offers are now ready in upwork for job thanks

**Comment by Natnael-Guchima** [comment] 2023-07-18 09:30
No worries. Accepted the offer. Thanks @laurenreidexpensify

**Comment by kidroca** [comment] 2023-07-19 07:43
@Santhosh-Sellavel 
> @kidroca I believe you might have the idea on which PR this issue was introduced, please let me know thanks!

Check this comment out, it links the PR and explains the issue: https://github.com/Expensify/App/issues/22133#issuecomment-1620290477

**Comment by kidroca** [comment] 2023-07-19 07:45
@laurenreidexpensify
> @Natnael-Guchima @kidroca my apologies for any late responses, but please note that your offers are now available on Upwork for review. Thank you for your patience.

Just a quick note, I have recently joined the beta program, and as per our agreement, it is understood that any future assignments, including the current task, will be compensated through the New Dot.

**Comment by laurenreidexpensify** [comment] 2023-07-19 12:49
Okay, outstanding steps here:

@Santhosh-Sellavel can you please complete the checklist 
@Santhosh-Sellavel @kidroca can you please close out your payments in newdot on the pilot if you have not requested them already

payment has been issued to @Natnael-Guchima

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 20:09
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20365
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20365/files#r1252049731
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: IMO should have caught it while reviewing.
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. Yes
> * [ ]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@anmurali / @laurenreidexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 20:17
Bug: 
Web - User is unable to download attachments

### Regression Steps

#### Common to all
1. Navigate to a conversation where multiple images & pdfs are shared
2. Scroll through the chat to see all attachments 
3. Now click on any attachment
4. Verify Attachment Carousel view is opened

#### On web and mobile web

 1. Repeat the common steps to reach Attachment Carousel
 2. Verify the URL in the address bar of the browser changes as we change attachments in the attachment carousel
 3. Download a variety of attachments and check that the downloading functionality remains intact.
 4.  Change attachments using the arrow and verify downloading works
 
#### Other platforms

1.  Repeat the common steps to reach Attachment Carousel
2. Download a variety of attachments and check that the downloading functionality remains intact.
3. Change attachments using the arrow and verify downloading works


👍  or 👎 
cc: @Julesssss

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 20:20
Requested Payment on ND

**Comment by laurenreidexpensify** [comment] 2023-07-21 16:57
Steps looked good @Santhosh-Sellavel  - we're done with this one. Thanks!

**Closed by laurenreidexpensify** 2023-07-21 16:57 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-23 07:40
Approved 1k to Santhosh based on https://github.com/Expensify/App/issues/22133#issuecomment-1642024771

**Comment by JmillsExpensify** [comment] 2023-07-29 17:03
Reviewed details for @kidroca. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
