### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Task - user can can edit task details even if user is not assigned nor task creator

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31863] opened 2023-11-25 16:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a workspace
2. Go to settings > workspace > members
3. Add userB as member
4. Go to #annoince
5. Click on + icon and select assign task
6. Enter title and description
7. Assign it to yourself and create a task
8. Sign in as userB
8. Go to task report screen
9. Edit the task details

## Expected Result:
Only task creator or assignee can edit the task details

## Actual Result:
Anyone from room can edit the task details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fc2718d1-e5ca-4567-b234-bc6fd92ba4f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011716884c6ff12695</li>
        <li>Upwork Job ID: 1728446042061295616</li>
        <li>Last Price Increase: 2023-11-25</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27874125</li>
<li>DylanDylann | Contributor | 27874126</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-25 16:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - user can can edit task details even if user is not assigned nor task creator
### What is the root cause of that problem?
Let's see the condition to modify the task
https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/libs/actions/Task.js#L875

Because the members of the workspace have permission to comment to announce the room, as above condition they also edit the report in that room 
### What changes do you think we should make in order to solve the problem?
Let's this PR: https://github.com/Expensify/App/pull/23971
We allow member in a group to edit the task in that group 
We need to add a condition to check if It is policy room (announce room) / normal room we will only allow admin of the policy or the assignee edit task 



### What alternative solutions did you explore? (Optional)

**Comment by giltron** [comment] 2023-11-25 17:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Member of workspace (not admin) is allowed to edit a task they are not assigned to


### What is the root cause of that problem?


During [canModifyTask](https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/libs/actions/Task.js#L875), the check is not correct, as it only validates the user is a part of any parent (as per comments its only supposed to be #admin

```
  // If you don't have access to the task report (maybe haven't opened it yet), check if you can access the parent report
  // - If the parent report is an #admins only room
  // - If you are a policy admin
  var parentReport = ReportUtils.getParentReport(taskReport);
  return ReportUtils.isAllowedToComment(parentReport);
```

### What changes do you think we should make in order to solve the problem?

Within canModify Report it should be added (as per notes) that the parent report is an #admins only

```
  return ReportUtils.isAllowedToComment(parentReport) && getReportName(parentReport) === '#admins';

``


### What alternative solutions did you explore? (Optional)

N/A

**Comment by DylanDylann** [comment] 2023-11-28 16:14
@Ollyws 

Currently, we have logic to make sure that creator and assignee always have permission to edit task
https://github.com/Expensify/App/blob/48e0c1e435ae98df6d8ad2dda5caf624e73a0792/src/libs/actions/Task.js#L880

**Comment by aldo-expensify** [comment] 2023-11-30 17:23
That makes sense to me!

**Comment by isabelastisser** [comment] 2023-12-11 18:04
@Ollyws please provide an update. Thanks!

**Comment by isabelastisser** [comment] 2024-01-02 18:17
@Ollyws, please complete the checklist above so I can close the issue. Thanks!

I will process the payments in Upwork.

**Comment by isabelastisser** [comment] 2024-01-03 17:03
All set!

**Closed by isabelastisser** 2024-01-03 17:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
