### ISSUE TITLE
[$500] Web - Every user is allowed to create all types ( public/private) rooms in Workspaces "teacher's unite testing policy" and " Expensifydotorg/ Teachers unite !"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26718] opened 2023-09-04 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to fab button -> new room
2. Type room name
3. On select a workspace, try selecting  "teacher's unite testing policy" or  " Expensifydotorg/ Teachers unite !"
4. Select any visibility.
5. Note that everyone can create rooms inside such Expensify.org workspace !

## Expected Result:
If all forms of user can easily create private/public rooms inside teacher's unite testing policy, if might be cluttersome.
User should not be able to create rooms under such specific Workspaces designated for specific purposes.

## Actual Result:
Every user is allowed to create all types ( public/private) rooms in Workspaces "teacher's unite testing policy" and " Expensifydotorg/ Teachers unite !"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a285ba81-dac7-43d6-8e93-03fe309c152c

https://github.com/Expensify/App/assets/93399543/5846e9b8-648c-4d0b-93b6-3424c320faf4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693476004581829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196b593ffceba5253</li>
        <li>Upwork Job ID: 1699144486060986368</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by ashimsharma10** [comment] 2023-09-05 09:16
Tip while reproducing: 

If you dont see "teacher's unite testing policy " workspace in dropdown while creating room,  First join teacher-unite group filling the form fields " I know a teacher" and " I am a teacher"

**Comment by slafortune** [comment] 2023-09-05 19:36
applying the external label

**Comment by Pujan92** [comment] 2023-09-05 19:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User able to create rooms for the corporate policies(Not sure whether this is a bug or not)

### What is the root cause of that problem?
We are considering all the policies which are available for the user to allow creating the room in it.
https://github.com/Expensify/App/blob/30076c5b5767b0a9914ff2e7d043dbef70584030/src/pages/workspace/WorkspaceNewRoomPage.js#L118
https://github.com/Expensify/App/blob/1849ab14d6eb096792250225711e5bb1c28ec622/src/libs/PolicyUtils.js#L12-L14

### What changes do you think we should make in order to solve the problem?
I think we can update the function `getActivePolicies` to filter out the corporate policies or specific this policy based on id.

**Comment by slafortune** [comment] 2023-09-08 17:27
@cubuspl42 what do you think about the proposal presented by @Pujan92 ?

Reassigning a BZ member, I am out on sabbatical.

**Comment by cubuspl42** [comment] 2023-09-11 08:13
@Pujan92

> I think we can update the function `getActivePolicies` to filter out the corporate policies or specific this policy based on id.

This doesn't sound too confident!

Have you tested this solution? If not, what are the blockers to test it? If this is needed, was this consulted with others on Slack?

I don't want to be picky on wording, but I think that if the author is not convinced by their own proposal, it's a blocker from moving forward with it.

**Comment by laurenreidexpensify** [comment] 2023-09-12 10:03
still waiting on solutions

**Comment by cubuspl42** [comment] 2023-09-13 08:26
@Pujan92 Are you available to leave a short reply to my questions?

**Comment by Pujan92** [comment] 2023-09-13 08:29
> Have you tested this solution? If not, what are the blockers to test it? If this is needed, was this consulted with others on Slack?

@cubuspl42 I earlier tested the solution and just updated the screencast in the proposal with more details.  

> I don't want to be picky on wording, but I think that if the author is not convinced by their own proposal, it's a blocker from moving forward with it.

Actually, I was confident about what I suggested but to be honest not very sure about the expected behaviour. Sorry for that but let me bring the below 2 doubts to the Slack thread OR let me know if you have an idea for it.

1) Only for Teacher's unite policy do we need to prevent users from creating a new room?
2) Policy owner of Teacher's unite is allowed to create a new room?

**Closed** 2023-09-13 08:52 UTC
Labels: External, Daily, Help Wanted, Bug
