### ISSUE TITLE
[$500] Distance - Despite receiving the validation message "Please select unique waypoints," the system allows the user to proceed with the distance request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27196] opened 2023-09-11 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the "+" icon.
2. Select "Request money" and then chose "distance."
3. Select the starting point and click "Add stop" until the button became disabled
4. Add a stop address.
5. Now add finishing points.
6. Attempted to send the request.

## Expected Result:
After receiving the validation message "Please select unique waypoints," the user should not be able to proceed further with the request

## Actual Result:
Despite the validation message, the system still allows the user to send the distance request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/79c7bd9b-993d-4b30-9983-c2f4c23e7340

https://github.com/Expensify/App/assets/115492554/72c938bb-7210-43b7-bfcd-62c4ddc60cce

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693936855288019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f75e3daaf63f614</li>
        <li>Upwork Job ID: 1701329084817547264</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-09-11 21:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - Despite receiving the validation message "Please select unique waypoints," the system allows the user to proceed with the distance request

### What is the root cause of that problem?

The issue here is that hasRouteError is not included in the condition to disable the button thus resulting in the button being active as long as there are two items selected as waypoints without any consideration for errors

### What changes do you think we should make in order to solve the problem?

We could use hasRouteError in the condition for isDisabled but first I think we should change hasRouteError from using lodashHas to lodashGet and check if lodashGet(transaction, 'errorFields.route') !== null because the problem with using lodashHas is that once an error happens, even if you clear the error, the error object remains and lodashHas will return true anyway, you can test this by changing the DotIndicatorMessage's "messages" we are passing to something like "hello" and observe the red dot indicator staying even after clearing the error.

After changing hasRouteError to using lodashGet we could use it for button disabling so that the user cannot procceed unless there are no errors

```javascript
<Button
    success
    style={[styles.w100, styles.mb4, styles.ph4, styles.flexShrink0]}
    onPress={() => IOU.navigateToNextPage(iou, iouType, reportID, report)}
    pressOnEnter
    isDisabled={waypointMarkers.length < 2 || hasRouteError}
```

### Result

https://github.com/Expensify/App/assets/74202751/2ff670ed-e519-4cbf-b6d8-c76f4c0048e5

**Comment by paultsimura** [comment] 2023-09-11 22:10
This has already been fixed in the current `main` branch by this PR: https://github.com/Expensify/App/pull/26705

**Comment by NicMendonca** [comment] 2023-09-13 21:49
@izarutskaya can you confirm please ^^

**Comment by NicMendonca** [comment] 2023-09-13 21:55
confirmed: https://expensify.slack.com/archives/C049HHMV9SM/p1693936855288019

**Comment by NicMendonca** [comment] 2023-09-13 21:56
thank you @paultsimura!!

**Closed by NicMendonca** 2023-09-13 21:55 UTC
Labels: External, Daily, Help Wanted, Bug
