### ISSUE TITLE
[$500] Android - Status - On tapping save, "clear status" is not shown before navigating to previous page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34886] opened 2024-01-22 13:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch site in mweb/app
2. Tap profile
3. Tap status
4. Select an emoji
5. Enter a message
6. Tap save
7. Note, on tapping save, "clear status" is shown/not shown before navigating to previous page in mweb and Android

## Expected Result:
When tapping save, there must be consistent behaviour on showing/not showing "clear status" in mweb & Android before navigating to previous page.

## Actual Result:
After selecting status emoji, entering message, on tapping save "clear status " is seen before navigating to previous page in mweb but not in Android. Inconsistent behaviour is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/11b12b9a-d842-4497-ac7d-6f1ed9ab20a9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01378cdeab58829dc2</li>
        <li>Upwork Job ID: 1749427027673931776</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-22 13:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Status - On tapping save, "clear status" is not shown before navigating to previous page

### What is the root cause of that problem?
We show the clear status when there is status emoji or text https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/settings/Profile/CustomStatus/StatusPage.js#L182-L183
whose value depends on the status read from the personal details so the display only depends on whether the onyx update comes before the navigation or not 
### What changes do you think we should make in order to solve the problem?

To make it consistent we can use a ref that will be set when we set status emoji or text from empty to some value and we should not allow the display of the button when that ref is set
### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-22 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Clear status" button is shown for a moment before navigating to a previous screen.

### What is the root cause of that problem?

The button is shown based on this condition:

https://github.com/Expensify/App/blob/5e710377c42462f7fb4266677619fc29d5092c5b/src/pages/settings/Profile/CustomStatus/StatusPage.js#L182-L191

And the status is persisted & navigation happens here:

https://github.com/Expensify/App/blob/5e710377c42462f7fb4266677619fc29d5092c5b/src/pages/settings/Profile/CustomStatus/StatusPage.js#L83-L92

So between the status is persisted and navigation, which happens after interactions, the button is displayed briefly.

### What changes do you think we should make in order to solve the problem?
I don't see a need for using the `InteractionManager.runAfterInteractions` here, IMO we can just remove it:

```js
            User.updateCustomStatus({
                text: statusText,
                emojiCode,
                clearAfter: clearAfterTime !== CONST.CUSTOM_STATUS_TYPES.NEVER ? clearAfterTime : '',
            });

            User.clearDraftCustomStatus();
            navigateBackToPreviousScreen();
```

### What alternative solutions did you explore? (Optional)

**Comment by sabal9991** [comment] 2024-01-23 17:44
Solution Proposal for GitHub Issue #34886

Issue Title: Clear Status Button Not Showing on Android
GitHub Issue: [Expensify/App/issues/34886](https://github.com/Expensify/App/issues/34886)

Description:
When executing the React Native project on an Android device, the "Clear Status" button is not displaying on the status page. This issue occurs when selecting an emoji and entering text before navigating back to the profile page.

Steps to Reproduce:

Navigate to the status page.
Select an emoji and enter text.
Attempt to navigate back to the profile page.
Expected Behavior:
The "Clear Status" button should be visible when an emoji and text are selected.

Actual Behavior:
The "Clear Status" button is not showing as expected.

Potential Causes and Checks:

Condition Check:

Ensure that the condition !!currentUserEmojiCode || !!currentUserStatusText is evaluating to true.
Logging:

Add console.log statements to inspect the values of currentUserEmojiCode and currentUserStatusText.
Update Draft Status:

Check if User.clearDraftCustomStatus() and User.updateDraftCustomStatus({clearAfter: DateUtils.getEndOfToday()}) behave as expected.
Effect Dependencies:

Verify the dependencies of the useEffect hook for handling draft status.
External Dependencies:

Ensure external components, like the EmojiPicker, are not causing unexpected side effects.
Styling:

Confirm that the styling of the "Clear Status" button is not causing it to be hidden or overlapped.
Navigation Flow:

Double-check the navigation flow to ensure it doesn't interfere with the button's visibility.
Proposal:
To address the "Clear Status" button visibility issue on Android, I propose the following steps:

Condition Check:

Review the condition !!currentUserEmojiCode || !!currentUserStatusText and make adjustments if necessary. Ensure it accurately reflects the desired visibility criteria.
Logging:

Implement additional logging statements to capture the values of currentUserEmojiCode and currentUserStatusText during the button rendering process. This will help diagnose whether the condition is met.
Update Draft Status:

Ensure that the calls to User.clearDraftCustomStatus() and User.updateDraftCustomStatus({clearAfter: DateUtils.getEndOfToday()}) are correctly updating the draft status.
Effect Dependencies:

Validate the dependencies in the useEffect hook related to handling draft status. Ensure it triggers appropriately based on changes in currentUserEmojiCode and currentUserClearAfter.
External Dependencies:

Examine external components (e.g., EmojiPicker) for any unexpected interactions that might impact the rendering of the "Clear Status" button.
Styling:

Check the styling of the "Clear Status" button to ensure it is not set to be hidden or overlapped by other elements.
Navigation Flow:

Review the navigation flow to ensure that navigating back to the profile page is not causing unintended re-renders or state changes.
Next Steps:
If this proposal is accepted, I will proceed with the suggested changes and provide a detailed pull request on the Expensify/App GitHub repository. The pull request will include relevant code modifications, screenshots, and confirmation of testing on all platforms.

Contributor Guidelines:
Before submitting the proposal, I have reviewed the [Contributor Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to ensure compliance with Expensify's contribution standards.

Payment Terms:
As per the documented [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md), payment amounts are variable, dependent on any regressions caused by the work.

I look forward to your feedback and the opportunity to contribute to the resolution of this issue.

**Comment by sabal9991** [comment] 2024-01-23 17:44
Solution Proposal for GitHub Issue #34886

Issue Title: Clear Status Button Not Showing on Android
GitHub Issue: [Expensify/App/issues/34886](https://github.com/Expensify/App/issues/34886)

Description:
When executing the React Native project on an Android device, the "Clear Status" button is not displaying on the status page. This issue occurs when selecting an emoji and entering text before navigating back to the profile page.

Steps to Reproduce:

Navigate to the status page.
Select an emoji and enter text.
Attempt to navigate back to the profile page.
Expected Behavior:
The "Clear Status" button should be visible when an emoji and text are selected.

Actual Behavior:
The "Clear Status" button is not showing as expected.

Potential Causes and Checks:

Condition Check:

Ensure that the condition !!currentUserEmojiCode || !!currentUserStatusText is evaluating to true.
Logging:

Add console.log statements to inspect the values of currentUserEmojiCode and currentUserStatusText.
Update Draft Status:

Check if User.clearDraftCustomStatus() and User.updateDraftCustomStatus({clearAfter: DateUtils.getEndOfToday()}) behave as expected.
Effect Dependencies:

Verify the dependencies of the useEffect hook for handling draft status.
External Dependencies:

Ensure external components, like the EmojiPicker, are not causing unexpected side effects.
Styling:

Confirm that the styling of the "Clear Status" button is not causing it to be hidden or overlapped.
Navigation Flow:

Double-check the navigation flow to ensure it doesn't interfere with the button's visibility.
Proposal:
To address the "Clear Status" button visibility issue on Android, I propose the following steps:

Condition Check:

Review the condition !!currentUserEmojiCode || !!currentUserStatusText and make adjustments if necessary. Ensure it accurately reflects the desired visibility criteria.
Logging:

Implement additional logging statements to capture the values of currentUserEmojiCode and currentUserStatusText during the button rendering process. This will help diagnose whether the condition is met.
Update Draft Status:

Ensure that the calls to User.clearDraftCustomStatus() and User.updateDraftCustomStatus({clearAfter: DateUtils.getEndOfToday()}) are correctly updating the draft status.
Effect Dependencies:

Validate the dependencies in the useEffect hook related to handling draft status. Ensure it triggers appropriately based on changes in currentUserEmojiCode and currentUserClearAfter.
External Dependencies:

Examine external components (e.g., EmojiPicker) for any unexpected interactions that might impact the rendering of the "Clear Status" button.
Styling:

Check the styling of the "Clear Status" button to ensure it is not set to be hidden or overlapped by other elements.
Navigation Flow:

Review the navigation flow to ensure that navigating back to the profile page is not causing unintended re-renders or state changes.
Next Steps:
If this proposal is accepted, I will proceed with the suggested changes and provide a detailed pull request on the Expensify/App GitHub repository. The pull request will include relevant code modifications, screenshots, and confirmation of testing on all platforms.

Contributor Guidelines:
Before submitting the proposal, I have reviewed the [Contributor Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to ensure compliance with Expensify's contribution standards.

Payment Terms:
As per the documented [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md), payment amounts are variable, dependent on any regressions caused by the work.

I look forward to your feedback and the opportunity to contribute to the resolution of this issue.

**Comment by sabal9991** [comment] 2024-01-24 06:38
Contributor details
Your Expensify account email: <sabalchaulagain777@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~0157ed7158e8dea6f2>

**Comment by sabal9991** [comment] 2024-01-24 07:34
Contributor details
Your Expensify account email: <concierge@expensify.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~0157ed7158e8dea6f2>

**Comment by sabal9991** [comment] 2024-01-24 07:35
Contributor details
Your Expensify account email: <concierge@expensify.com](mailto:concierge@expensify.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~0157ed7158e8dea6f2>

**Comment by anmurali** [comment] 2024-01-24 23:43
Tested on iOS native and Android native and the behavior is consistent. Cannot reproduce.

**Comment by paultsimura** [comment] 2024-01-25 07:23
@anmurali this is the Web platform that has a faulty behavior: the "Clear status" button appears before the right-hand modal fully closes. It should appear only on the second opening of the modal after the status is set.

https://github.com/Expensify/App/assets/12595293/11a3c225-6cc5-4473-ae59-13a684562742

**Comment by anmurali** [comment] 2024-02-06 16:40
Discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705930945613109)
Closing as this seems really trivial.

**Closed by anmurali** 2024-02-06 16:40 UTC
Labels: External, Daily, Needs Reproduction, Overdue, Bug
