### ISSUE TITLE
[HOLD Needs Repro] Keystrokes aren't being quickly recognized when typing immediately after opening a chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31286] opened 2023-11-13 22:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699896354633069

## Action Performed:
1. Go to any report
2. Go to a different report with a lot of chats and *immediately* start typing quickly.  (I navigate via cmd+k)

## Expected Result: 
All the keystrokes entered show up quickly and consistently in the compose box

## Actual Result: 
There is a delay in the keystrokes showing (which gets better after a few seconds)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8aecfaff-5674-4886-b051-90b622595f58

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-11-15 04:41
https://github.com/Expensify/App/assets/59587260/6ef97bc5-d7c2-4b25-941d-bc110d98a3d4

I wasn't able to reproduce :( @mallenexpensify what version are you using?

**Comment by mallenexpensify** [comment] 2023-11-15 18:59
I wasn't able to reproduce either @kadiealexander , at least not consistently.  I unassigned you, assigned me, and put on hold, pending reproduction steps. I'll keep trying to break it :)
Im' on Version 1.3.99-0 , Desktop.  Also tested Chrome and wasn't able to repro. Thx

**Comment by mallenexpensify** [comment] 2023-11-21 23:29
Just updated to latest version on desktop and unable to reproduce so, closing.

**Closed by mallenexpensify** 2023-11-21 23:29 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
