### ISSUE TITLE
Submit expense - Next Steps shows "Waiting for You to pay" when payment is blocked by violations

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53163] opened 2024-11-26 19:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+bm1jd9@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create workspace
3. Go to categories > settings > enable "Members must categorize all expenses"
4. Go to the workspace chat and submit an expense
5. Click on the expense preview then see the next steps.

## Expected Result:
The next steps should ask the user to fix the violation instead of stating "Waiting for You to pay."

## Actual Result:
The next steps message displays "Waiting for You to pay expense(s)" even when payment is blocked due to a violation.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/82ca3728-f397-481b-b02c-33a24c3649eb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-11-26 20:13
https://github.com/user-attachments/assets/d812bcb6-e3c7-4e99-8911-06109231ad8d

@IuliiaHerets @kavimuru, I could repro this in production. Did the tester test this change in production before labelling it as a blocker? 

Gonna remove the label, but we should look into it.

I assume the problem is that its the admin/policy owner and the submitter all in one so probably the logic is incorrectly picking priority.

**Comment by IuliiaHerets** [comment] 2024-11-27 06:07
@mountiny Tester shared the video 

https://github.com/user-attachments/assets/1af1ccab-6fc3-4352-95d7-357d0d73141e

**Comment by flodnv** [comment] 2024-11-27 20:41
Adding the label back: https://expensify.slack.com/archives/C01GTK53T8Q/p1732737120984209?thread_ts=1732649367.590529&cid=C01GTK53T8Q

**Comment by mountiny** [comment] 2024-11-27 22:27
Revert being CPed

**Comment by flodnv** [comment] 2024-11-28 12:51
Cool, can we close this?

**Closed** 2024-11-28 13:11 UTC
Labels: Reviewing, Engineering, Weekly, Bug
