### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] Scan - Settings button does not open location permission settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45431] opened 2024-07-15 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Click + > Submit expense > Scan
4. Upload a receipt
5. Submit the expense
6. Click Settings

## Expected Result:
Browser location permission access should appear

## Actual Result:
The modal closes and the expense is submitted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cd162f50-4114-4924-964f-c70cbceb5737

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efe1095b2043e581</li>
        <li>Upwork Job ID: 1812971045434010011</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by tgolen** [comment] 2024-07-15 22:02
I'm demoting this from a blocker since it doesn't impact product usage.

**Comment by eh2077** [comment] 2024-07-16 16:23
This is caused by changes from https://github.com/Expensify/App/pull/39875.

@Julesssss Should we consider this as a regression and let author of https://github.com/Expensify/App/pull/39875 to fix this? Or handle this separately as a follow-up improvement

**Comment by tgolen** [comment] 2024-07-16 16:37
I think we should handle it like a typical regression. Thanks for finding
that PR!

**Comment by Julesssss** [comment] 2024-07-17 10:22
Shared [here](https://github.com/Expensify/App/pull/39875#issuecomment-2232961508) on the issue.

**Comment by Julesssss** [comment] 2024-07-17 14:59
@lanitochka17 would you mind confirming the issue here please? I see in the video that the permission prompt is displayed to the user:

![Screenshot 2024-07-17 at 15 57 48](https://github.com/user-attachments/assets/d9c49728-3384-46c3-8874-4a0cbbcb62d9)

**Comment by eh2077** [comment] 2024-07-22 14:58
@Julesssss What do you think about @tienifr 's comment ^?

**Comment by Julesssss** [comment] 2024-07-22 15:36
Ah I see. So yes, it would be better to alter the button to say 'Continue' for mWeb Safari/Chrome

**Comment by allroundexperts** [comment] 2024-07-22 22:42
@tienifr's proposal looks good to me @Julesssss. I'd do a similar thing.

**Comment by eh2077** [comment] 2024-07-23 00:08
Unassigned myself from here as this is going to be handled as a regression / follow-up improvement of the original issue

**Comment by Julesssss** [comment] 2024-07-23 08:26
> I think we should handle it like a typical regression. Thanks for finding

> Unassigned myself from here as this is going to be handled as a regression/follow-up improvement of the original issue

I disagree this is a regression. This is a new feature, and this was called out during development. 

@eh2077 would you like to be C+ still? Else perhaps @allroundexperts could take over as C+ role?

**Comment by allroundexperts** [comment] 2024-07-23 08:28
I can take over since I have authored this flow 😄

**Comment by eh2077** [comment] 2024-07-23 08:29
@Julesssss Ah yeah I can take it as C+ then

**Comment by Julesssss** [comment] 2024-07-23 08:33
Ugh these bloody labels 😭

**Comment by Julesssss** [comment] 2024-07-23 08:33
@allroundexperts can you please review [this proposal](https://github.com/Expensify/App/issues/45431#issuecomment-2229758580), then we can move forward. thanks

**Comment by trjExpensify** [comment] 2024-07-25 22:05
Bump on the proposal review, @allroundexperts.

**Comment by allroundexperts** [comment] 2024-07-25 22:24
Oh, I already reviewed it [here](https://github.com/Expensify/App/issues/45431#issuecomment-2243934164).

@tienifr's [proposal](https://github.com/Expensify/App/issues/45431#issuecomment-2229758580) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment] 2024-07-26 08:58
Hey @tienifr, please go ahead with the PR

**Comment by trjExpensify** [comment] 2024-08-29 09:47
Checklist time, @allroundexperts.

**Comment by allroundexperts** [comment] 2024-09-01 22:51
I think that the checklist is not applicable here since the behaviour wasn't very well defined for this edge case. A regression test would be overkill here as well since we're just changing the button text to `Got it!`

**Comment by trjExpensify** [comment] 2024-09-02 19:26
Is there a regression test from the OG implementation you worked on for this modal, and if so, does it outline the expected behaviour for web and mobile?

**Comment by garrettmknight** [comment] 2024-09-04 13:50
$250 approved for @tienifr

**Comment by trjExpensify** [comment] 2024-09-09 18:26
Great, thank you for that. 

>I think we can close out this issue after payment.

Yep, this can now proceed to payment. Payment summary as follows: 

- $250 to @tienifr for the fix
- $250 to @allroundexperts for the C+ review

Both are free to request on ND now. Closing!

**Closed by trjExpensify** 2024-09-09 18:26 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-08 12:26
$250 approved for @allroundexperts
