### ISSUE TITLE
Members - Pressing Enter for the first time mark user and moves to the next screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21276] opened 2023-06-21 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com or start Desktop App
2. Log in with expensifail account
3. Create or go to any workspace
4. Open Members
5. Click Invite
6. Click 'Enter' key

## Expected Result:
First user is selected and marked. The screen with the users list is still open

## Actual Result:
First user is marked AND the NEXT screen opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cccf7513-7321-410c-8e3d-3a0382818acf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2023-06-21 23:03
I can reproduce the issue, looking into the cause now.

**Comment by francoisl** [comment] 2023-06-22 01:23
I think this is working as intended, the difference between staging and production is that we autofocus the `Name, email, or phone number` text input:

<table>
<tr>
 <td>Staging
 <td>Prod
<tr>
 <td><video src="https://github.com/Expensify/App/assets/2229301/d298b229-f745-4502-81af-28592ab208bc" /></td>
 <td><video src="https://github.com/Expensify/App/assets/2229301/d46003a3-b847-4cc5-8810-0edade1f57f6" />
</table>


If you press Enter while the text input is focused, we also select the current row and navigate back on production.
If you unfocus the search input on staging and press Enter, we also select the highlighted row.

I can't pinpoint to what change to make the input automatically focus now, but it feels like a better UX to me - when you open that invite page, you probably want to start typing a name/email/phone number to filter options, so it makes sense to autofocus the input.

**Comment by francoisl** [comment] 2023-06-22 05:31
cc @luacmartins as discussed in Slack. Going to close this so we can move forward with the deploy.

**Closed by francoisl** 2023-06-22 05:31 UTC
Labels: DeployBlockerCash, Engineering, Hourly
