### ISSUE TITLE
[$500] Chat - App allows to delete other users messages in # admin of workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29823] opened 2023-10-17 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697532701974139

## Action Performed:
Precondition: To test, user will need to have 1 workspace with multiple admins in it
1. Open the app
2. Open # admin of workspace with multiple admins
3. Hover or long press on message from other user
4. Observe that delete comment option is available

## Expected Result:
App should not allow user to delete other users messages

## Actual Result:
App allows user to delete other users messages in # admin

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/93399543/da2184ae-e24c-456f-accb-cb4bb5736883

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/7903ba74-297c-4058-a883-59b4d3e3e77b

</details>

<details>
<summary>iOS: Native</summary>

  

https://github.com/Expensify/App/assets/93399543/27f7f777-35fc-46e3-a448-e01c4b2be276

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2877d764-b701-4832-9571-ee110140e9e0

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/22284b90-ce9c-4556-af7a-8aa1f1706ea6

https://github.com/Expensify/App/assets/93399543/08731f7d-7bd3-4db6-843f-0f09577c6c09

https://github.com/Expensify/App/assets/93399543/3633c256-0657-494f-9908-a64b1c105114

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/ead5f902-1cdf-4510-aa6d-cb7c9d92b461

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a6d08b85f59984d</li>
        <li>Upwork Job ID: 1714369820496429056</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-10-17 20:23
This seems like a backend issue.

**Comment by graylewis** [comment] 2023-10-17 20:35
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
This is clearly also a backend issue primarily. If the intended behavior is for this to be forbidden, then the backend needs to not let it happen regardless of frontend actions. That being said, there still needs to be a solution for correctly displaying the context action in admin chats on the frontend.

### What is the root of the issue
The issue comes down to the function `canDeleteReportAction`, which the contextActionMenu relies on to determine whether the delete action should be displayed. The last three lines of this function follow:
```
    const isAdmin = policy.role === CONST.POLICY.ROLE.ADMIN && !isDM(report);

    return isActionOwner || isAdmin;
```
Obviously, this code results in admins of a workspace being able to delete others' messages, even if those users are admins.

### What changes do you think we should make in order to solve the problem?

We have to add a check to see if the user sending the message is an admin:
`return isActionOwner || (isAdmin && !actionOwnerIsAdmin);`

What alternative solutions did you explore? (Optional)
NA

**Comment by jliexpensify** [comment] 2023-10-18 00:09
@Santhosh-Sellavel what do you think? Is this a back-end issue?

**Comment by jliexpensify** [comment] 2023-10-22 02:21
issue still remains:

![image](https://github.com/Expensify/App/assets/30815269/349bf2ac-0db5-4de9-bcae-e4ccf878579f)

**Comment by jliexpensify** [comment] 2023-10-22 02:23
Hi @NikkiWines - I have a tongue twister for you: it looks like any Admin can [delete](https://github.com/Expensify/App/issues/29823#issuecomment-1773973651) another Admin's message in the #admins room where there are multiple admins.

Is this an `internal` issue?

**Comment by NikkiWines** [comment] 2023-10-25 00:37
Hmm, I'd say it's a combo - we'll need to prevent that action on the backend but it's probably also wise update the UI so we don't show the option to delete another admin's message

**Comment by jliexpensify** [comment] 2023-10-25 02:50
Thanks! Will you tackle both @NikkiWines or just the back-end part? If so, we could turn this GH into an "update the UI" one and make it `External`?

**Comment by NikkiWines** [comment] 2023-10-25 02:51
I can take on the backend, let's handle the UI update separately

**Comment by jliexpensify** [comment] 2023-10-25 03:14
Ok cool, I assume the "update the UI" part is simply removing the option to delete an Admin chat in the Admin room?

If so, is it best to use this GH, or should we create a new one once you're done?

**Comment by NikkiWines** [comment] 2023-10-25 03:42
Yep, that's correct - it basically involves actually adding a check to determine if the commenter is also an admin. If so, we won't show the option to delete the comment. And I think we can use this issue for the UI update! 

And unless we need another backend update to determine if the commenter is an admin, then we should be able to do the UI update and backend change concurrently

**Comment by NikkiWines** [comment] 2023-10-27 02:55
Backend PR is in review

**Comment by NikkiWines** [comment] 2023-10-30 21:33
Backend PR is live! @Santhosh-Sellavel can you review @graylewis's [proposal](https://github.com/Expensify/App/issues/29823#issuecomment-1767130596) please 🙇

**Comment by jliexpensify** [comment] 2023-11-01 01:14
Not overdue - bumping @Santhosh-Sellavel

**Comment by jliexpensify** [comment] 2023-11-03 03:41
Bumped via Slack

**Comment by Santhosh-Sellavel** [comment] 2023-11-03 14:12
Sorry for the delay. @graylewis [proposal](https://github.com/Expensify/App/issues/29823#issuecomment-1767130596) looks good. 
But one query how`actionOwnerIsAdmin` is  computed?

**Comment by graylewis** [comment] 2023-11-03 17:30
@Santhosh-Sellavel Roughly, we can use isAdminOfFreePolicy(policies) from Policy.js and pass it reportAction.actorAccountID from canEditMoneyRequest(reportAction)

**Comment by Santhosh-Sellavel** [comment] 2023-11-06 17:02
@graylewis That's not the case, can you please check. `isAdminOfFreePolicy` is to decided whether logged in user is admin or not.

**Comment by graylewis** [comment] 2023-11-06 18:51
@Santhosh-Sellavel After doing some poking around, it looks like as of now there is no simple way to check if another user is an admin of a workspace. There is no data loaded in Onyx (unless you're on the WorkspaceMembersPage, therefore triggering API.read("OpenWorkspaceMembersPage")) that lists the users and their roles for a given workspace. There are two approaches to solving this issue:

1. We leverage existing API endpoints to get a list of all users, lookup the user who created the report action (message) and check if that user is an admin. This approach would entail creating a new function in PolicyUtils.js which uses the onyx collection ONYXKEYS.COLLECTION.POLICY_MEMBERS to fetch all users, and then to look up the action creators ID in that list of members. 
2. We add a 'role' field to every report action which represents the role of the person who created the report action. This seems logical to include and will probably be needed at some point down the line anyway. 

What do you think of these solutions @Santhosh-Sellavel? It doesn't seem like there's any other place in the app where other users' roles are referenced in this way.

**Comment by Santhosh-Sellavel** [comment] 2023-11-07 17:43
[Both](https://github.com/Expensify/App/issues/29823#issuecomment-1795927136) sound like an over-engineered solution. 

@NikkiWines What's your thought here?

Also, can you answer this?

> I don't have access to a 'full' policy (one that's not considered a 'free' policy), so I can't test this theory, but it seems like there is an employees field on full policies which might include the information we need (assuming managers are admins and vice-versa). I'd be interested to hear if anyone else has some insight into whether this is a feasible approach.
> 
> It's also not clear to me how different free policies are from full policies. Can free policies even have multiple admins? I can't see a way to add another admin to my workspace, but if not, why even create a #admins chat room?

**Comment by jliexpensify** [comment] 2023-11-07 23:45
[Free plans only allow for one Admin](https://community.expensify.com/discussion/8355/faq-free-plan-and-workspaces/p1?new=1)

>Can my workspace have more than one Admin?

>No. Currently, the Expensify Workplace only allows for just one admin (the Workspace creator).

**Comment by NikkiWines** [comment] 2023-11-08 03:09
Hmmm, yeah agreed that both solutions aren't ideal. Especially if we only allow free workspaces with one admin in New Expensify right now. 

> It's also not clear to me how different free policies are from full policies. Can free policies even have multiple admins? I can't see a way to add another admin to my workspace, but if not, why even create a #admins chat room?

Full policies can have multiple admins and there are plans to introduce that functionality into New Expensify in the future. But yes at the moment the #admins chat room is a bit lonely 😅

I think this is a bug that users in the future could encounter, but it's not a bug someone could encounter now - at least with a normal set up for New Expensify. 

I suggest we close this or put it on hold for now until we introduce multiple admins for workspaces in New Expensify. Thoughts?

**Comment by jliexpensify** [comment] 2023-11-08 03:15
>until we introduce multiple admins for workspaces in New Expensify.

@NikkiWines any ideas when this might be?

Also - do we actually want to allow Admins to delete other Admin messages? I always thought we would only want users to delete their own messages.

**Comment by NikkiWines** [comment] 2023-11-08 18:14
> @NikkiWines any ideas when this might be?

Nope, not sure where that is on the roadmap. 

> Also - do we actually want to allow Admins to delete other Admin messages? I always thought we would only want users to delete their own messages.

We don't want admins to be able to delete other Admin messages. Admins should only be allowed to delete their own messages and non-admin messages.

**Comment by jliexpensify** [comment] 2023-11-08 22:23
Yep, that's what I thought! Forgive my ignorance here, but can we just blanket remove the delete button in all #admins rooms? Or is that something that's really complex?

**Comment by NikkiWines** [comment] 2023-11-08 23:04
Because we don't just want to disallow admins from deleting other admin messages in just #admins, we want to disallow it across all rooms tied to a workspace.

**Comment by jliexpensify** [comment] 2023-11-08 23:06
Ok cool, thanks Nikki! I'm happy to pay the Reporter but lets probably close this one?

**Comment by jliexpensify** [comment] 2023-11-08 23:09
Payment Summary

- Bug Reporter: @dhanashree-sawant $50

[Upworks Job](https://www.upwork.com/jobs/~016a6d08b85f59984d)

**Comment by jliexpensify** [comment] 2023-11-09 03:34
Paid and job closed!

**Closed by jliexpensify** 2023-11-09 03:34 UTC
Labels: Engineering, Daily, Help Wanted, Bug
