### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] Web - RBR(red dot) for the maximum number of attempts of the resend magic code persists after Successfully adding the Contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21220] opened 2023-06-21 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Profile > Contact method
2. Press New Contact method > Enter any of your email address
3. Go to the newly added Contact method and Press Resend magic code 5-6 times until we get the error of the maximum number of attempts
4. Enter the last magic code from the Email
5. If the magic code worked and then It will navigate back to the Contact Methods page, and we can see the RBR error beside the newly added email

## Expected Result:
 If the magic code worked, we should remove the red dot error as we can not access the Enter magic code page, so we can not access/remove the error.

## Actual Result:
Magic code worked, and we navigated back to the Contact Methods page, but still, we could see the red dot.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b377388f-1947-4283-b89d-c8f9c744cada

https://github.com/Expensify/App/assets/93399543/a1e3aba5-2c96-415d-9538-e70bc586978e

https://github.com/Expensify/App/assets/93399543/0d2a5243-7b0c-41ea-9d37-40204d34d177

**Expensify/Expensify Issue URL:**

**Issue reported by:** @jayeshmangwani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686751798535969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012abf0b985aa6c54b</li>
        <li>Upwork Job ID: 1673362150600179712</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment] 2023-06-21 15:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RBR for the maximum number of attempts of the resend magic code persists after Successfully verifying the magic code

### What is the root cause of that problem?
1. When we press the `Resend magic code` at that, we time call the requestContactMethodValidateCode method from User.js,

https://github.com/Expensify/App/blob/f15e6dc98d2c5853ed3456c5c6c648a25c66823f/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L80-L81


if the API return the error then we set the error for validateCodeSent to errorFields in failureData

https://github.com/Expensify/App/blob/a2d074b1964d754b3dbf10fedee954e746670221/src/libs/actions/User.js#L168-L170

2. And when we get an error for validateCodeSent, and we do not clear the error by pressing the cross icon from the RBR, we add the correct magic code. At that time validateCodeSent error does not reset to null, and then we do not show the magic code page. However, the validateCodeSent error value is still there, and we can see the red dot beside the contact method.

### What changes do you think we should make in order to solve the problem?
We should set the validateCodeSent error to null when we get the success response for the ValidateSecondaryLogin, so that when we successfully validate the contact method and the magic code works, then no need to show the error for a maximum number of magic code requests.

so here we need to add the `errorFields: {validateCodeSent: null}` to the successData of the ValidateSecondaryLogin

https://github.com/Expensify/App/blob/f15e6dc98d2c5853ed3456c5c6c648a25c66823f/src/libs/actions/User.js#L426-L437

```
    errorFields: {
        validateCodeSent: null,
    }
```

### What alternative solutions did you explore? (Optional)
none

**Comment by sonialiap** [comment] 2023-06-26 16:07
triaging to external 👍

**Comment by mollfpr** [comment] 2023-06-27 19:26
Thanks @jayeshmangwani and the [proposal](https://github.com/Expensify/App/issues/21220#issuecomment-1601084439) looks good to me 🚀

🎀 👀 🎀 C+ reviewed!

**Comment by deetergp** [comment] 2023-06-28 18:38
That seems like the right solution. Hiring @jayeshmangwani.

**Comment by jayeshmangwani** [comment] 2023-06-29 04:58
@mollfpr [PR](https://github.com/Expensify/App/pull/21841) is ready for review

**Comment by mollfpr** [comment] 2023-07-12 16:03
Melvin forgot to calculate this issue 🤔

The assignment **Jun 29**
PR merged on **Jul 1**

**Comment by sonialiap** [comment] 2023-07-13 13:36
All paid ✔️

**Closed by sonialiap** 2023-07-13 13:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
