### ISSUE TITLE
[$250] Expense - Missing Members section in expense report details page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40541] opened 2024-04-19 09:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat as employee.
3. Create a manual expense.
4. Go to expense report.
5. Click on the report header.
6. As Admin, repeat Step 4 and 5 with employee workspace chat.

## Expected Result:
Members section will show up in expense report details page (production behavior).

## Actual Result:
Members section is missng in expense report details page. It only shows up when one of the members sends a message in expense report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/006715d4-dbbf-440d-96f7-a25757ef4ad5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01653d31f427db89ae</li>
        <li>Upwork Job ID: 1781308954716004352</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-19 09:51
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-19 09:51
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-19 09:53
Production 


https://github.com/Expensify/App/assets/115492554/3dd7608e-7674-4803-b3ad-c4ac1eaf87c0

**Comment by lakchote** [comment] 2024-04-19 13:10
Not a blocker per se, but definitely something we want to handle.

**Comment by shahinyan11** [comment] 2024-04-19 13:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Missing Members section in expense report details page
### What is the root cause of that problem?
Here we get all participants only for  `groupChat` reports
### What changes do you think we should make in order to solve the problem?
1. Update [this](https://github.com/Expensify/App/blob/9a115b64a4fc7d167d87ece406044aaa0cb4ab87/src/pages/ReportDetailsPage.tsx#L84C1-L91C31) part of code like below
```
const isGroupChat = useMemo(() => ReportUtils.isGroupChat(report), [report]);
const isPolicyExpenseChat  = useMemo(() => ReportUtils.isPolicyExpenseChat(report), [report]);
const participants = useMemo(() => {
    if (isGroupChat || isPolicyExpenseChat) {
        return ReportUtils.getParticipantAccountIDs(report.reportID ?? '');
    }

    return ReportUtils.getVisibleChatMemberAccountIDs(report.reportID ?? '');
}, [report, isGroupChat]);
```

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-04-19 14:02
## Proposal
[Updated](https://github.com/Expensify/App/issues/40541#issuecomment-2066617547).  Fixed minor omission in proposal

**Comment by lakchote** [comment] 2024-04-19 15:07
@sakluger I'll be OOO next week until April 29th. Feel free to assign another internal engineer to review if needed.

**Comment by sakluger** [comment] 2024-04-22 18:44
Removed @lakchote. Since it's not a blocker, we don't need a BE engineer yet. One will be assigned once a proposal is chosen.

**Comment by sakluger** [comment] 2024-04-24 22:58
I'm going to assign a new C+ as well to help spread the load and get the proposals reviewed.

**Comment by sakluger** [comment] 2024-04-24 22:58
@s77rt, we have a few outstanding proposals. Could you please take a look when you have a chance?

**Comment by s77rt** [comment] 2024-04-25 19:28
Frontend side:
I don't see a bug here. The members menu item will show up only if there is visible members in that report.

Backend side:
If we create an expense report should the participants be visible? cc 🎀 👀 🎀

**Comment by Julesssss** [comment] 2024-04-26 09:05
Hey @s77rt could you clarify why the proposals aren't suitable in this case? I know that a backend solution is preferable in most cases, but it looks like `isParentReportPolicyExpenseChat` is a reasonable condition to add in this case.

**Comment by Julesssss** [comment] 2024-04-26 09:10
Also I'm struggling to understand the bug report. So 'Fridayyy' is the workspace, and we are creating a workspace expense report (which should include both the admin and user)?

**Comment by s77rt** [comment] 2024-04-26 17:17
@Julesssss Displaying hidden members contradicts the purpose of having them hidden in the first place. I'm not seeing any recent frontend change in this area. It's probably a recent backend change that broke this.

> So 'Fridayyy' is the workspace, and we are creating a workspace expense report (which should include both the admin and user)?

Yes, that's correct. However the members are set as hidden. Can you please check if that change was recent?

**Comment by Julesssss** [comment] 2024-04-29 08:48
Thanks, I see now. After reviewing all recent backend PRs I located one which may be related. I'm asking for their thoughts on this bug 🤞

**Comment by Julesssss** [comment] 2024-04-30 08:59
The first one was unrelated, but I have found one more that might be the cause🤞

**Comment by sakluger** [comment] 2024-05-02 16:30
@Julesssss any updates?

**Comment by Julesssss** [comment] 2024-05-03 07:39
It was [also](https://github.com/Expensify/Web-Expensify/pull/41752#issuecomment-2085415068) not the cause unfortunately. 

Rodrigo provided this thought as an alternative to this being a backend issue. But I don't have time to further triage either suggestion. I think we'll have to hold this for now as it's just a polish item.

> I think it is more related to adopting the new participants property in the FE. Not sure how we did before, but the visibility of participants is calculated by checking if the notification preferences is HIDDEN, and as far as I know the notification preference for the participants in expense reports is HIDDEN until something happens.

**Comment by sakluger** [comment] 2024-05-03 15:46
Okay, I'll change this to weekly for now.

**Comment by sakluger** [comment] 2024-05-14 14:14
@Julesssss checking in again, what's the latest here?

**Comment by Julesssss** [comment] 2024-05-15 07:24
I have no further ideas about the regression. I'm afraid that it's very unlikely I'll be able to prioritise this in the next month or so.

**Comment by sakluger** [comment] 2024-05-16 20:23
Okay, let's switch to monthly.

**Comment by Julesssss** [comment] 2024-05-20 08:49
I don't think there's much we can do to speed this along. If this is still occurring, we'll have to wait for other internal engineering tasks to calm down a bit.

**Comment by mvtglobally** [comment] 2024-06-10 12:41
Issue not reproducible during KI retests. (First week)

**Comment by s77rt** [comment] 2024-06-20 23:20
Should we make this Internal?

**Comment by Julesssss** [comment] 2024-06-27 17:23
This issue is not going to be prioritised internally, so I am closing it.

**Closed by Julesssss** 2024-06-27 17:23 UTC
Labels: External, Engineering, Monthly, Help Wanted, Bug
