### ISSUE TITLE
[HOLD for payment 2024-07-25] [$250] [Payment card / Subscription] When adding Payment card, there is a slight delay before it shows

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44904] opened 2024-07-05 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44361
## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account (Beta enabled)
3. Access https://staging.new.expensify.com/settings/subscription/add-payment-card
4. Input valid card data & Save

## Expected Result:
User expects that after saving the card data immediately loads and displays

## Actual Result:
Several seconds go by before the card actually appears on the Sub page, leading the user to think the details did not save

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7f761c91-7774-4285-bf1a-7ddd04c2c4d5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b996dd4f4317410f</li>
        <li>Upwork Job ID: 1809282225502876268</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103066195</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-07-05 14:05
@mountiny  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment] 2024-07-05 14:05
Not a blocker since this is behind beta

@blimpich I hope you dont mind I will assign you.

Are we not handling this optimistically? Feels like we should, but if not there should be some loader

**Comment by blimpich** [comment] 2024-07-05 16:25
Yeah this is a bug, we should be handling this optimistically.

**Comment by sonialiap** [comment] 2024-07-08 09:40
@getusha what do you think of the above proposals?

**Comment by getusha** [comment] 2024-07-08 20:53
thanks for the proposal @dominictb
The solution you provided works and i see that's what we're doing in `AddDebitCardPage`, could you expand more on your RCA and why the solution makes it work? thanks!

**Comment by getusha** [comment] 2024-07-09 16:27
I get it now, we are handling this optimistically already, the issue is just we are just closing the form too soon.

**Comment by getusha** [comment] 2024-07-09 16:28
@dominictb's [proposal](https://github.com/Expensify/App/issues/44904#issuecomment-2213244439) looks good to me
🎀 👀 🎀  C+ reviewed!

**Comment by getusha** [comment] 2024-07-09 16:42
@blimpich do we want to handle this optimistically? i assume the backend will need to validate the card?

This is the behavior when adding a bank account

https://github.com/Expensify/App/assets/75031127/80b62c3f-9ddd-4392-86d9-99acb070e879

After applying @dominictb's solution the form will stay until it finishes loading, same as ^

**Comment by blimpich** [comment] 2024-07-09 16:49
Yes we should be handling this optimistically.

**Comment by getusha** [comment] 2024-07-09 18:36
The proposal sounds good, though I would like to see more details on the implementation. We also need to change the offline UX pattern. it's currently blocking form. @cretadn22 could you update your proposal to include that too?

> Yes we should be handling this optimistically.

@blimpich I suggest just showing a loading indicator on the submit button, that'll allow us to show an appropriate error message (if any) while in the form, and to keep the current offline pattern as I see the backend does some validation on the card details. That way makes the most sense to me. Please check the `Add a Debit Card` page - settings/wallet/add-debit-card - i think it's similar to this page.

**Comment by trjExpensify** [comment] 2024-07-10 10:36
I tend to agree with @getusha here, Submitting the `Add payment card` and `Change payment currency` forms were both pattern C in the design doc as well because of these third party API calls. 

So I think we should remain on the form with a loading indicator on the submit button after they click it. If the API call is successful, the modal closes and the details should be updated on Subscription page (removing this feeling of there being a delay right now). If it fails, the modal doesn't close, and the errors are displayed in the form to fix using the standard form errors pattern. 

@mountiny @shawnborton do ya'll agree?

**Comment by trjExpensify** [comment] 2024-07-10 16:24
Great stuff, so @getusha can we move this on for a proposal review from Ben and get the PR going? Thanks!

**Comment by blimpich** [comment] 2024-07-10 16:27
I think we're waiting on @cretadn22 to update their proposal with more details, so that it aligns with what we want here.

**Comment by mountiny** [comment] 2024-07-10 16:34
Yeah that sounds good if this should be pattern C

**Comment by getusha** [comment] 2024-07-10 16:47
@blimpich we can proceed with @dominictb's [proposal](https://github.com/Expensify/App/issues/44904#issuecomment-2213244439) since we decided to stick with pattern C

@dominictb could you update your proposal to include https://github.com/Expensify/App/issues/45124 too? thanks!

**Comment by blimpich** [comment] 2024-07-10 17:01
@dominictb please still update your proposal like @getusha said to include a fix for [this issue](https://github.com/Expensify/App/issues/45124), since they are basically the same issue 🙂

Thank you @getusha for your suggestion on how to make this better, I agree this is the ideal solution to arrive at 👍

**Comment by blimpich** [comment] 2024-07-11 16:04
@dominictb DM'ed you with steps on how to do it, requires some special steps to use test data.

**Comment by blimpich** [comment] 2024-07-12 18:58
@dominictb sorry I forgot to mention that all magic codes when using a Expensify engineer's local backend will be `000000`. You won't get any emails unless I manually run a particular script on my backend.

For the missing onyxData, that appears to be a bug. Thank you for catching that! I will get that fixed, but it will probably take a few days or longer.

**Comment by blimpich** [comment] 2024-07-12 19:02
For now lets keep this issue/PR focused on adding a payment card, we'll use [this issue](https://github.com/Expensify/App/issues/45124) to handle the change currency flow internally since this will require backend changes.

**Comment by trjExpensify** [comment] 2024-07-15 21:17
Nice one! Can you complete the video/screenshots in the OP of the PR linked above? Thanks!

**Comment by blimpich** [comment] 2024-07-15 23:39
@dominictb thank you for reporting the bug! I believe that has the same root cause as the first BE bug. Lets come back to that once the first BE bug is completed.

**Comment by sonialiap** [comment] 2024-07-25 10:05
Payment summary:
@getusha $250 - please request in ND - please complete the [checklist](https://github.com/Expensify/App/issues/44904#issuecomment-2236544869)
@dominictb $250 - paid ✔️

**Comment by JmillsExpensify** [comment] 2024-07-30 18:41
$250 approved for @getusha

**Closed** 2024-08-02 13:08 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
