### ISSUE TITLE
[Bug] [$1000] Android - Split/Send/Request money - The transition is not smooth when requesting/split amount

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10610] opened 2022-08-26 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any chat
3. Go to any group conversation or chat
4. Click the `+` icon
5. Select Split Bill/Send Money/Request Money
6. Enter an amount and select the `Next` confirmation button

## Expected Result:
The transition should be smooth

## Actual Result:
The transition is not smooth

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.92.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186993264-fe99cc5a-a028-4efb-b377-dc396ee07a00.mp4

https://user-images.githubusercontent.com/93399543/186993270-b1a8f8fe-0c72-44ab-b040-ed4893921e21.mp4

https://user-images.githubusercontent.com/93399543/186993276-0ed0a687-636c-46b2-95ec-087be0986437.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment] 2022-08-30 16:38
I'm not sure I see the issue here w/ "The transition is not smooth". Do you have the original Slack discussion or a more detailed description for additional context?

**Comment by isagoico** [comment] 2022-09-01 17:17
@robertjchen hello! The transitions between modals is included in our scope when testing the regression. In the video it can be seen that the loading of the Big Number Pad page is glitchy (it's kinda hard to put it into words haha). 

If these types of bugs related to transitions are not in scope please let us know and we'll inform the team.

**Comment by robertjchen** [comment] 2022-09-02 11:13
Ahh, I think I see it now! These issues are definitely in scope as we want to make the app as well-polished as possible 😉 Let me open this up to our contributors to see if there's a proposal to make it better 🙏

**Comment by jboniface** [comment] 2022-09-05 18:11
job: https://www.upwork.com/jobs/~0165f8b1c2bb3e578e

**Comment by jboniface** [comment] 2022-09-14 15:49
increased to $500

**Comment by kakajann** [comment] 2022-09-15 22:55
Seems smooth to me


https://user-images.githubusercontent.com/11542415/190520174-033e3416-ce95-46f2-b244-77b4966723cd.mov

**Comment by marcochavezf** [comment] 2022-09-19 22:07
> Seems smooth to me
> 
>  Screen.Recording.2022-09-16.at.3.21.04.AM.mov

In the second `0:05` the modal blinks for a fraction of a second, I think that is what @isagoico was referring to [here] (https://github.com/Expensify/App/issues/10610#issuecomment-1234564719).

**Comment by dylanexpensify** [comment] 2022-09-20 08:24
@marcochavezf thoughts on doubling?

**Comment by marcochavezf** [comment] 2022-09-20 22:49
> @marcochavezf thoughts on doubling?

Yeah I think makes sense to double the price, the glitch is also happening on Android (native):

https://user-images.githubusercontent.com/6829422/191376612-9a82d822-485b-4bbb-98fe-bf1b20338abf.mp4

Seems we're displacing the pad number (for a fraction of a second) in order to display the phone keyboard, but the position of the pad number should be static.

@JmillsExpensify I think this issue can be considered also part of the WA quality project, thoughts?

**Comment by marcochavezf** [comment] 2022-09-20 22:53
Paused the video when this happens and the pad number shouldn't be in that position:

<img width="297" alt="Screen Shot 2022-09-20 at 17 50 28" src="https://user-images.githubusercontent.com/6829422/191378497-b5d790fe-e1ac-45f4-8e3a-82fb08b7075b.png">

---

> > ⚠️ Looks like this issue was linked to a **possible regression on PRODUCTION** [here](https://github.com/Expensify/App/issues/10608)
> > If you are the assigned CME please investigate whether the linked PR caused a regression and leave a comment with the results.
> 
> In this case there's no linked PR, but the linked issue seems to be related

Related to this ^ I think the linked issue is a different problem and seems it's [no longer happening](https://github.com/Expensify/App/issues/10608#issuecomment-1251846231).

**Comment by marcochavezf** [comment] 2022-09-23 18:20
According to this [post](https://expensify.slack.com/archives/C01SKUP7QR0/p1663754280536209), I'm going to put this issue on hold until we have a solution for the keyboard initiative because seems to be related. Also, I'm going to remove the label `Help Wanted`. @dylanexpensify could you remove the job from Upwork?

**Comment by dylanexpensify** [comment] 2022-09-27 08:39
Yes! Shall we close then @marcochavezf ?

**Comment by marcochavezf** [comment] 2022-09-27 17:50
@dylanexpensify Ah I think only the Upwork job, because the problem exists, and we'd want to re-evaluate the issue after the Keyboard initiative is implemented.

**Comment by JmillsExpensify** [comment] 2022-11-01 23:42
Snagging this from you @dylanexpensify since I'm on the tracking issue.

**Comment by JmillsExpensify** [comment] 2022-11-02 19:50
Now that the keyboard initiative is kicked off, I'm removing the hold.

**Comment by JmillsExpensify** [comment] 2022-11-02 19:50
@tgolen Shall you take this one from @marcochavezf as well, since you're leading the tracking issue?

**Comment by JmillsExpensify** [comment] 2022-11-02 19:52
Whatever the case, the old Upwork job expired so I have created a new one and also raised the price to $1000 given that this is a mainline initiative for WAQ. https://www.upwork.com/jobs/~0123070f67b356c4b3

**Comment by JmillsExpensify** [comment] 2022-11-02 19:53
One final note. @applausebot can you help me re-test this as well, as I don't have an Android device I'm able to test with.

**Comment by tgolen** [comment] 2022-11-02 21:36
Sure, I'll take this over.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:48
You know what, I think we are done here. I just tested this and the bouncing caused by the keyboard no longer exists. I'm attaching a video of my test just now. 

https://user-images.githubusercontent.com/1127863/200194345-15bd2a69-e636-4aa8-adbc-5351ccdc7e01.MP4

**Comment by JmillsExpensify** [comment] 2022-11-06 20:48
Given that I'm unable to reproduce I'm closing this issue. Another keyboard issue bites the dust!

**Closed by JmillsExpensify** 2022-11-06 20:48 UTC
Labels: External, Engineering, Monthly, Needs Reproduction, Bug
