### ISSUE TITLE
[HOLD for payment 2024-07-02] [$250] Expense - Expense preview in the main chat is blank when deleting expense offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44214] opened 2024-06-22 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp around https://expensify.testrail.io/index.php?/tests/view/4661677
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to FAB > Submit expense > Manual.
4. Enter amount > Select a participant with no unsettled expense > Submit the expense.
5. Go to transaction thread.
6. Click on 3-dot menu > Delete expense.
7. Delete the expense.

## Expected Result:
The expense preview in the main chat will show 0.00 (production behavior).

## Actual Result:
The expense preview in the main chat is blank.

In a different case where user submits two expenses and deletes both of the expenses offline, the expense preview in the main chat shows the total amount, instead of 0.00.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/c4c3ca4e-b10a-46b4-8d3f-0ad878405ce0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01703c45cd54d93a3c</li>
        <li>Upwork Job ID: 1805181146577846482</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by m-natarajan** [comment] 2024-06-22 17:36
@francoisl FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-22 17:37
We think that this bug might be related to #wave-collect - Release 1

**Comment by francoisl** [comment] 2024-06-24 18:31
This seems to be coming from https://github.com/Expensify/App/pull/40168, reverting it locally fixes the issue. However I don't think we need to block on this, it just affects offline behavior and the expense still gets deleted when you come back online - going to demote for now.

**Comment by nkdengineer** [comment] 2024-06-25 03:02
@francoisl I will fix this issue since it's my regression.

**Comment by jayeshmangwani** [comment] 2024-06-27 06:23
@francoisl @muttmuure We can close this issue. The issue was a regression from the https://github.com/Expensify/App/pull/40168 PR, and there is no payment due for this issue.

**Closed** 2024-06-27 09:53 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment, Bug
