### ISSUE TITLE
Task -Not here page briefly shown when assigning task after creating distance expense via FAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46713] opened 2024-08-02 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Tap FAB > Submit expense > Distance
3. Enter start and finish viewpoints and complete creating distance expense
4. Navigate to the LHN
5. Tap FAB > Assign a task
6. Tap the go back icon

## Expected Result:
No extra screen is displayed when selecting Assign task from FAB, and user returns to LHN when tapping the go back icon

## Actual Result:
Not here page is briefly displayed in the background, and when tapping the go back icon, user returns to the expense report instead of LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/25d5d35e-1530-4a03-b500-f647533d7ae1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-02 12:21
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-02 12:22
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment] 2024-08-02 15:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not here page is briefly displayed in the background, and when tapping the go back icon, user returns to the expense report instead of LHN

### What is the root cause of that problem?

After we create a distance request, a report with `reportID` is `undefined` stored in Onyx because `OpenReport` API is called here with `reportID` is `undefined` when we open the waypoint page (the `reportID` param in this page is undefined)

https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L69

Then the matching here is the `Report` routes with `reportID` as `undefined` because the report `report_undefined` exists in Onyx

https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L153-L154



It leads `metainfo.isCentralPaneAndBottomTabMandatory` and `metainfo.isFullScreenNavigatorMandatory` are returned as `true` because we don't move to this case.

https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L191-L193

Finally, the report screen route with id is `undefined` is added here that shows the not found page
https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/libs/Navigation/linkTo/index.ts#L139-L141
### What changes do you think we should make in order to solve the problem?
1. We should add the new task detail page into `RHP_SCREENS_OPENED_FROM_LHN ` to avoid the another bug if we open this page via QAB

https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L24

2. Safer check whether the `reportID` here is `undefined` or empty string before getting the report from Onyx and also check the report has `reportID` or not

https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L153-L154

3. OPTIONAL: we can prevent call `OpenReport` API here if the `reportID` is invalid or we're in the create flow

https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L69
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-08-07 14:42
I'm tempted to close this issue because the other issue seems more like the route cause, right?

**Comment by JmillsExpensify** [comment] 2024-08-08 01:04
Going to go ahead and close.

**Closed by JmillsExpensify** 2024-08-08 01:04 UTC
Labels: Daily, Bug
