### ISSUE TITLE
[$1000] Web - Extra line is being added on Welcome message input field if user prepends ">" block quote

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21903] opened 2023-06-29 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace and go to announce room
2. Click on the header > settings > Welcome message
3. Type "> hey" inside of the input field and click on save
4. Click on Welcome message again and observe the input field

## Expected Result:
 No extra lines should be added before the welcome message

## Actual Result:
Extra line is added before the welcome message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b12dd4f-5943-4a0b-b7d7-526c0f0d6928

https://github.com/Expensify/App/assets/93399543/c63ebada-8439-410e-b2a7-063853c8f315

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687981670403749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014103a1ee001b423a</li>
        <li>Upwork Job ID: 1674772708681207808</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-29 22:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Extra line is added at the start and end when `> ` is prepended in Welcome message page

### What is the root cause of that problem?

`> ` is a blockquote markdown.

We add the extra linebreak at the start and end when parsing blockquote.
https://github.com/Expensify/expensify-common/blob/52e551cae863ca0a4ec7be8b1ae9b0dee90632e7/lib/ExpensiMark.js#L305

This is the root cause

### What changes do you think we should make in order to solve the problem?

I'm not sure why we add linebreaks. Anyway, removing them solves the issue


### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment] 2023-06-30 10:09
This looks similar to this issue: https://github.com/Expensify/App/issues/20725, I've pinged the C and C+ there to see if the resolution would be the same. If it is, I'll pay the bug reporter and close this out

**Comment by conorpendergrast** [comment] 2023-06-30 10:10
Reproduced: 

<img width="404" alt="image" src="https://github.com/Expensify/App/assets/5802477/e7df911c-a0d6-46b7-aefd-675ffd6b0ac0">

**Comment by conorpendergrast** [comment] 2023-06-30 13:31
Superd, so @narefyev91 confirmed that this is the same as https://github.com/Expensify/App/issues/20725#issuecomment-1614443461. 

This appears to be a unique bug, with the same root cause, so we'll pay for that bug report

**Comment by conorpendergrast** [comment] 2023-06-30 13:35
Sorry, I did that to auto-create the job! Sent an offer to @Nathan-Mulugeta for bug report via Upwork. Once that's paid and contract ended, I'll close this

**Comment by Nathan-Mulugeta** [comment] 2023-06-30 13:36
Accepted offer just now @conorpendergrast

**Comment by conorpendergrast** [comment] 2023-06-30 13:52
Paid, thanks for the speediness @Nathan-Mulugeta!

**Closed by conorpendergrast** 2023-06-30 13:52 UTC
Labels: Daily, Bug

**Comment by OctavianGuzu** [comment] 2023-06-30 16:06
Hey @conorpendergrast , I saw the job on Upwork and submitted a proposal including a fix and a justification of the bug, but looks like the job was assigned to someone else from the start? How does this work for future bugs that show up?

**Comment by OctavianGuzu** [comment] 2023-06-30 16:08
Contributor details
Your Expensify account email: octavian.guzu@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~014cbae534414aec68

**Comment by OctavianGuzu** [comment] 2023-06-30 16:09
Contributor details
Your Expensify account email: [octavian.guzu@gmail.com](mailto:octavian.guzu@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~014cbae534414aec68

**Comment by OctavianGuzu** [comment] 2023-06-30 16:09
Contributor details
Your Expensify account email: octavian.guzu@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014cbae534414aec68

**Comment by conorpendergrast** [comment] 2023-06-30 19:15
@OctavianGuzu Hey! We only accept proposals directly on GitHub issues, following [this process](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).

In this case, the bug has been [identified](https://github.com/Expensify/App/issues/21903#issuecomment-1614438295) as a duplicate of an issue that is already being fixed, so we don't need any more proposals. There's a lot more ([over 200](https://github.com/Expensify/App/issues?page=3&q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)!) issues that do need proposals though!
