### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Split - Values after decimal point displayed on second line if splitting certain amounts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42117] opened 2024-05-13 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: the device text size is set to default (middle)
1. Open the app and log in
2. Tap FAB > Split expense
3. Enter certain amount (1, 6-9, 60, 70, 80, 90)
4. On the next screen select one participant
5. Proceed to the confirmation screen

## Expected Result:
The values after decimal point are displayed in one line

## Actual Result:
The values after decimal point are displayed on the second line. It happens with certain amounts (1, 6-9, 60, 70, 80, 90) if splitting between 2 users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/189f6557-abcf-4402-81f2-683e7ef7ce33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b4523bc0bb34adf</li>
        <li>Upwork Job ID: 1793049519934955520</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 102671868</li>
<li>tienifr | Contributor | 102690052</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by lanitochka17** [comment] 2024-05-13 22:41
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-13 22:41
We think that this bug might be related to #vip-split

**Comment by bernhardoj** [comment] 2024-05-14 13:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Decimal value is put at the second line.

### What is the root cause of that problem?
Currently, we set a fixed width for the split amount input.
https://github.com/Expensify/App/blob/a6cb60c63201e823406cee5298b682be796a804b/src/components/MoneyRequestConfirmationList.tsx#L492

It assumes each digit width is 9 and it adds the prefix padding. However, the input has a padding right style.
https://github.com/Expensify/App/blob/a6cb60c63201e823406cee5298b682be796a804b/src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.tsx#L64

If the input is 35.00 and we don't use the fixed width, the width is 64.3334...
<img width="195" alt="image" src="https://github.com/Expensify/App/assets/50919443/a24423cb-1466-42a4-b9d9-7e5ba6968319">

but the fixed width value is 64.

### What changes do you think we should make in order to solve the problem?

We should consider for the padding right into the calculation by adding `pr1.paddingRight`.

**Comment by bernhardoj** [comment] 2024-05-16 16:05
Updated proposal to include fix for https://github.com/Expensify/App/issues/42279

**Comment by greg-schroeder** [comment] 2024-05-21 22:41
Applied `External` so we can get proposal review going

**Comment by DylanDylann** [comment] 2024-05-23 09:04
@tienifr  Could you provide a test branch for your solution?

**Comment by DylanDylann** [comment] 2024-05-28 02:26
Hi Melv, the @tienifr's proposal looks promising. I am requesting a test branch to ensure it works well on devices. @tienifr Any update on this issue?

**Comment by greg-schroeder** [comment] 2024-06-01 02:24
bump @tienifr on the above!

**Comment by greg-schroeder** [comment] 2024-06-01 02:42
Go away Melvin

**Comment by greg-schroeder** [comment] 2024-06-03 18:39
Thanks @tienifr

**Comment by DylanDylann** [comment] 2024-06-05 07:44
@tienifr Any update?

**Comment by DylanDylann** [comment] 2024-06-10 09:53
[Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1718009497594619)

**Comment by mallenexpensify** [comment] 2024-06-10 14:59
Assigned to @dukenv0307

**Comment by dangrous** [comment] 2024-06-11 16:07
Yep, that seems to clean things up. Let's do it

**Comment by dangrous** [comment] 2024-06-24 15:26
How are we looking on this one @tienifr @dukenv0307?

**Comment by dangrous** [comment] 2024-06-25 14:40
Got it - @tienifr do you think you can take a look and updated as needed today? Would love to move this forward and it's been about a week. Thanks!

**Comment by greg-schroeder** [comment] 2024-06-28 09:22
Last update from @tienifr was yesterday:

>On it now. I was working on a related PR and thought it's better to finish it first before this so we wouldn't have expectation conflicts.

**Comment by greg-schroeder** [comment] 2024-07-16 21:45
PR is on staging, awaiting deploy to prod

**Comment by greg-schroeder** [comment] 2024-07-24 11:16
Processing

**Comment by greg-schroeder** [comment] 2024-07-24 11:17
Payment summary:

Contributor: @tienifr - $250 - You can make a manual request via ND (rescinded Upwork offer)
C+: @dukenv0307 - $250 - Paid via Upwork

**Comment by greg-schroeder** [comment] 2024-07-24 11:18
Next up is the checklist from @dukenv0307!

**Comment by JmillsExpensify** [comment] 2024-07-24 21:17
$250 approved for @tienifr

**Closed** 2024-07-25 10:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
