### ISSUE TITLE
[Hold for Payment 21 Dec][$1000] `Save` button doesn't work if you update a Room Name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13003] opened 2022-11-24 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on fab icon > new room
2. Pick a Room Name  
3. Create a room
4. Go to room settings for room and type a new name
5. Press save
6. Observe nothing happens, UI name does not update
7. Navigate back to chats, observe room name 

## Expected Result: 
The button should be pressed and show that an action has been taken 

## Actual Result:
 The keyboard closes. The room name does save if you navigate back to Chats. 

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203823474-81f57af4-a63c-40c2-a255-da8404877b47.mov

https://user-images.githubusercontent.com/43996225/203823538-7f1400ab-3d76-45b9-a451-81b8c7468bbc.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669227031265659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~012f2e465011b52f0d
- Upwork Job ID: 1596111589733318656

**Comment by Puneet-here** [comment] 2022-11-24 15:49
### Proposal
Pass keyboardShouldPersistTaps="handled" or keyboardShouldPersistTaps="always" at `ScrollView` https://github.com/Expensify/App/blob/3cf717412cf6b03357184bf057921cf658ff158d/src/pages/ReportSettingsPage.js#L147   
If we want to dismiss the keyboard once user press save button we can add Keyboard.dismiss() in `validateAndUpdatePolicyRoomName`
https://github.com/Expensify/App/blob/3cf717412cf6b03357184bf057921cf658ff158d/src/pages/ReportSettingsPage.js#L90

**Comment by laurenreidexpensify** [comment] 2022-11-25 12:00
From  this  SO: https://stackoverflow.com/c/expensify/questions/14418

- [x] The "bug" is  actually  a  bug 
- [x]  The  bug  is  not  a  duplicate  report  of  an  existing  GH 
- [x]  The  bug  is  reproducible, following  the  reproduction  steps:
1. Click on fab icon > new room
2. Pick a Room Name  
3. Create a room
4. Go to room settings for room and type a new name
5. Press save
6. Observe nothing happens, UI name does not update
7. Navigate back to chats, observe room name 
- [x] The  GH  template  is  filled  out  as  fully  as  possible -- this  means  the  GH  body  and  title  are  clear

**Comment by Vishrut19** [comment] 2022-11-25 12:11
Hey! Can I try to work on this issue ?

**Comment by sobitneupane** [comment] 2022-11-25 12:41
@Puneet-here Thanks for your proposal.

Your [proposal](https://github.com/Expensify/App/issues/13003#issuecomment-1326615859) does the required job. But I think the better approach will be to make use of [Form](https://github.com/Expensify/App/blob/main/src/components/Form.js). 

It's a good opportunity to refactor this page to use Form. 

cc: @srikarparsi

**Comment by sobitneupane** [comment] 2022-11-25 12:44
@Vishrut19 Thanks for your interest. 

If you haven’t already, check out the [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md). You can find how to post proposals [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#working-on-expensify-jobs).

**Comment by allroundexperts** [comment] 2022-11-25 13:09
## Proposal

As mentioned @sobitneupane, we can just refactor this component to use `Form` component. As such, the following changes need to be done:

```diff
diff --git a/src/pages/ReportSettingsPage.js b/src/pages/ReportSettingsPage.js
index c59511daf..d2c84e625 100644
--- a/src/pages/ReportSettingsPage.js
+++ b/src/pages/ReportSettingsPage.js
@@ -11,6 +11,7 @@ import compose from '../libs/compose';
 import Navigation from '../libs/Navigation/Navigation';
 import * as Report from '../libs/actions/Report';
 import * as ReportUtils from '../libs/ReportUtils';
+import Form from '../components/Form';
 import HeaderWithCloseButton from '../components/HeaderWithCloseButton';
 import ScreenWrapper from '../components/ScreenWrapper';
 import withLocalize, {withLocalizePropTypes} from '../components/withLocalize';
@@ -75,7 +76,8 @@ class ReportSettingsPage extends Component {
         };
 
         this.resetToPreviousName = this.resetToPreviousName.bind(this);
-        this.validateAndUpdatePolicyRoomName = this.validateAndUpdatePolicyRoomName.bind(this);
+        this.updatePolicyRoomName = this.validateAndUpdatePolicyRoomName.bind(this);
+        this.validate = this.validate.bind(this);
     }
 
     /**
@@ -87,10 +89,7 @@ class ReportSettingsPage extends Component {
         Report.clearPolicyRoomNameErrors(this.props.report.reportID);
     }
 
-    validateAndUpdatePolicyRoomName() {
-        if (!this.validate()) {
-            return;
-        }
+    updatePolicyRoomName() {
         Report.updatePolicyRoomName(this.props.report, this.state.newRoomName);
     }
 
@@ -185,14 +184,20 @@ class ReportSettingsPage extends Component {
                                             </View>
                                         )
                                             : (
-                                                <RoomNameInput
-                                                    ref={el => this.roomNameInputRef = el}
-                                                    value={this.state.newRoomName}
-                                                    policyID={linkedWorkspace && linkedWorkspace.id}
-                                                    errorText={this.state.errors.newRoomName}
-                                                    onChangeText={newRoomName => this.clearErrorAndSetValue('newRoomName', newRoomName)}
-                                                    disabled={shouldDisableRename}
-                                                />
+                                                <Form
+                                                    submitButtonText={this.props.translate('common.save')}
+                                                    validate={this.validate}
+                                                    onSubmit={this.updatePolicyRoomName}
+                                                >
+                                                    <RoomNameInput
+                                                        ref={el => this.roomNameInputRef = el}
+                                                        value={this.state.newRoomName}
+                                                        policyID={linkedWorkspace && linkedWorkspace.id}
+                                                        errorText={this.state.errors.newRoomName}
+                                                        onChangeText={newRoomName => this.clearErrorAndSetValue('newRoomName', newRoomName)}
+                                                        disabled={shouldDisableRename}
+                                                    />
+                                                </Form>
                                             )}
                                     </View>
                                     {!shouldDisableRename && (

```

**Comment by allroundexperts** [comment] 2022-11-25 13:30
@Puneet-here Updated my proposal.

**Comment by allroundexperts** [comment] 2022-11-25 23:08
@sobitneupane Updated my proposal.

**Comment by sobitneupane** [comment] 2022-11-28 03:35
@allroundexperts Thanks for your [proposal](https://github.com/Expensify/App/issues/13003#issuecomment-1327456487).
But it looks like it is not a good idea to use `Form` Component here. In this particular case, we won't be making use of `FormAlertWithSubmitButton` of `Form` component. So, after passing `onSubmit` and `validate` props to the `Form`, we have to reference it back to `ReportSettingsPage`. And even the Picker value does not depend on the Form submission. It's value changes with the input change.

**Comment by allroundexperts** [comment] 2022-11-28 06:48
@sobitneupane So then we should just use what @Puneet-here suggested?

**Comment by sobitneupane** [comment] 2022-11-28 07:20
@Puneet-here's [Proposal](https://github.com/Expensify/App/issues/13003#issuecomment-1326615859) here looks good to me.

🎀👀🎀 C+ reviewed

cc: @srikarparsi

**Comment by srikarparsi** [comment] 2022-11-30 09:14
thanks @sobitneupane, looks good to me as well. assigning you to the issue @Puneet-here

**Comment by laurenreidexpensify** [comment] 2022-11-30 13:05
@Puneet-here @sobitneupane offers sent in Upwork ✔️

**Comment by laurenreidexpensify** [comment] 2022-12-05 12:23
Merged but not deployed, this looks eligible for the 3 bonus

**Comment by laurenreidexpensify** [comment] 2022-12-16 10:10
Looks like this was deployed to Prod 2 days ago, updating manually for payment in 5 days if no regressions

**Comment by laurenreidexpensify** [comment] 2022-12-21 14:33
Paid ✔️ @Puneet-here @sobitneupane 

Regression Test Case is already outlined here https://expensify.testrail.io/index.php?/cases/view/1971090&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229067

**Comment by Puneet-here** [comment] 2022-12-21 17:59
Hi @laurenreidexpensify, I think this is eligible for the 50% bonus because it was merged within 3 business days (there was saturday and sunday in the middle)

**Comment by Puneet-here** [comment] 2022-12-27 15:37
Bump @laurenreidexpensify

**Comment by Puneet-here** [comment] 2023-01-20 11:07
bump @laurenreidexpensify

**Comment by laurenreidexpensify** [comment] 2023-01-20 13:56
Sorry @sobitneupane @Puneet-here - paid now!

**Closed by laurenreidexpensify** 2023-01-20 13:56 UTC
Labels: Reviewing, External, Weekly, Bug
