### ISSUE TITLE
[HOLD for payment 2024-12-03] [HOLD for payment 2024-11-29] Chat - No green line when click New message from top of the chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#52891] opened 2024-11-21 11:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** gocemate+a2907@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. User A scroll to the top of the chat with user B
2. User B sends a message
3. User A hit the New message green button
4. Chat is scrolled to the bottom

## Expected Result:
There should be a green line above the new message

## Actual Result:
No green line when click New message from top of the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

On android/web and android/app green line appears briefly and dissapears

## Screenshots/Videos

https://github.com/user-attachments/assets/2027460e-57d1-4212-a1f0-e718d9676f48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by rlinoz** [comment] 2024-11-21 14:23
Reverted this PR https://github.com/Expensify/App/pull/50692 locally and fixes this issue.

It looks like some change in that PR is re-triggering `unreadMarkerReportActionID` multiple times.

cc: @Krishna2323 @rayane-djouah

**Comment by rlinoz** [comment] 2024-11-22 13:34
Issue is fixed after CP:
https://github.com/user-attachments/assets/a0e58909-8935-43f1-b1cd-55d82c71fcde

**Comment by rlinoz** [comment] 2024-11-29 12:10
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by rlinoz** [comment] 2024-11-29 12:15
No payment needed, closing.

**Closed by rlinoz** 2024-11-29 12:15 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
