### ISSUE TITLE
[$500] Custom welcome message section is small for rooms

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30894] opened 2023-11-05 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699163449677249

## Action Performed:
1. Open app and login
2. Create a room
3. Click on the header > settings> welcome message 
4. Type a longer message

## Expected Result:
The message section should expand to fit the content, or even just be sized for the whole screen.

## Actual Result:
Welcome message content is small and does not expand

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![10](https://github.com/Expensify/App/assets/38435837/4a7c12a8-8434-4aae-a9ea-574935a7308d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3ae88df429cb4ff</li>
        <li>Upwork Job ID: 1721271665403342848</li>
        <li>Last Price Increase: 2023-11-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by dubielzyk-expensify** [comment] 2023-11-05 21:19
The potential to improve this is to have a property that allows us to let the textarea grow automatically. It shouldn't be default behavior, but it would be nice to allow for it on certain screens.

**Comment by dubielzyk-expensify** [comment] 2023-11-05 23:19
Looking into it I see a slightly different UI where message isn't in settings but on the room creation screen and given this I'm unsure if this is even something we want. Keen on @Expensify/design opinion here

**Comment by yh-0218** [comment] 2023-11-06 02:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The custom welcome message input area for rooms is small and does not expand to a sufficient height to accommodate longer messages.
### What is the root cause of that problem?
Because we have a fixed max height for all platforms.
https://github.com/Expensify/App/blob/846a4b74ef81fa17ecaed4af8bfe22ad2eeeb8c8/src/pages/workspace/WorkspaceNewRoomPage.js#L219
https://github.com/Expensify/App/blob/846a4b74ef81fa17ecaed4af8bfe22ad2eeeb8c8/src/styles/styles.ts#L2829-L2831
### What changes do you think we should make in order to solve the problem?
We need to use different style between mobile and web.
we can use `isExtraSmallScreenHeight` and `isSmallScreenWidth` from `useWindowDimensions`
### What alternative solutions did you explore? (Optional)

**Comment by DanutGavrus** [comment] 2023-11-06 09:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Message section is too small for rooms.

### What is the root cause of that problem?
The currently used style on the text input sets a maximum height of `115px` for any device type (web/mobile/etc) and for any device size (small/large/etc).

### What changes do you think we should make in order to solve the problem?
I think we should use the existing `getMaximumHeight` method from `StyleUtils` in order to set the welcome message max height to **1/3**(my suggestion, we may tune this) of the device height.  

1. Introduce `const {windowHeight} = useWindowDimensions();` in the `ReportWelcomeMessagePage` component;
2. Replace `containerStyles={[styles.autoGrowHeightMultilineInput]}`with `containerStyles={[StyleUtils.getMaximumHeight(windowHeight / 3)]}`

**Result**
...adding video soon

**Comment by bharatcontact** [comment] 2023-11-06 13:25
**### Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
Message section is too small for rooms.

**What is the root cause of that problem?**
The currently used style on the text input sets a maximum height of 115px for any device type (web/mobile/etc) and for any device size (small/large/etc).

**What changes do you think we should make in order to solve the problem?**
We can add a function to calculate the height of the box on key events based on the font size and current window dimensions. Based on the output height from the logic, we can keep updating the height of the textbox

**Comment by bharatcontact** [comment] 2023-11-06 13:29
Contributor details
Your Expensify account email: bharat.contactus@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017b46e9cfc1f0a0dd

**Comment by bharatcontact** [comment] 2023-11-06 13:30
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Message section is too small for rooms.

**What is the root cause of that problem?**
The currently used style on the text input sets a maximum height of 115px for any device type (web/mobile/etc) and for any device size (small/large/etc).

**What changes do you think we should make in order to solve the problem?**
We can add a function to calculate the height of the box on key events based on the font size and current window dimensions. Based on the output height from the logic, we can keep updating the height of the textbox

**Comment by dubielzyk-expensify** [comment] 2023-11-06 23:13
Think you nailed it there, @dannymcclain.

**Comment by alexpensify** [comment] 2023-11-09 01:42
Reassigning another 🐛  team member, I'm going OOO until Tuesday, November 14, and will take it back if it's still open by my return date.

@JmillsExpensify - Required action from the team: 

I haven't been able to confirm the next steps here, but it sounds like Design is suggesting to close. Can you please verify and complete the required action? Thanks!

**Comment by mollfpr** [comment] 2023-11-13 15:13
> To me this feels like it should be a more global consideration/discussion for our textarea component (which I don't think is very well-defined as is since it starts off as a single line and kinda tends to behave like a "normal" input).

I agree with this.

>For this specific situation, if the message field is behaving the same way as all our other multiline inputs, I would probably just leave it as is for now.

As far as I can see, every page that uses our `TextInput` with `autoGrowHeight` already has the style to set the max height to `115px`, so every `textarea` on those pages will behave the same to this issue.

@alexpensify @JmillsExpensify Based on the above conclusion, I think we can do nothing about this issue. What do you guys think?

**Comment by alexpensify** [comment] 2023-11-14 18:09
Thanks for the summary @mollfpr! I'm going to agree and close this GH.

**Closed by alexpensify** 2023-11-14 18:09 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
