### ISSUE TITLE
[$500] Cant chat with users after deleting a split bill

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26351] opened 2023-08-30 22:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign into a NewDot account
2. Go offline
3. Split a bill with two other new accounts, A and B
4. Open the DM with account B, delete the money request.
5. Open the DM with account A (as of now, it will crash at this step. That's a known bug: https://github.com/Expensify/App/issues/25481)
6. Go back on online and refresh the page to view the chat with account A
7. Delete the money request with account A
8. try to open a DM with account A.

## Expected Result: 
The user should be able to chat with account A.

## Actual Result: 
The user can't chat with account A. If they try to open the DM they just see a 404 "it's not here" error
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.359-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a35a984b-1608-4a11-bb0b-5efbe1b95d04

**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692637324842699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de79918502f8a43d</li>
        <li>Upwork Job ID: 1699456437913591808</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-09-06 16:15
Adding the external label

**Comment by slafortune** [comment] 2023-09-08 17:18
Still waiting on proposals - reassigning a BZ member, I'm out on sabbatical.

**Comment by s77rt** [comment] 2023-09-11 11:11
Still looking for proposals

**Comment by s77rt** [comment] 2023-09-13 15:46
Not close, still looking for proposals

**Comment by mvtglobally** [comment] 2023-09-13 17:18
Issue not reproducible during KI retests. (First week)

**Comment by s77rt** [comment] 2023-09-18 13:14
Not overdue. No proposals yet and the issue may not be reproducible

**Comment by s77rt** [comment] 2023-09-20 14:06
Same ^

**Comment by CortneyOfstad** [comment] 2023-09-29 12:48
@s77rt do you think it is worth doubling the payment to get some proposals? TIA!

**Comment by s77rt** [comment] 2023-09-29 14:08
@CortneyOfstad No I don't think so. Also we may need to hold this on https://github.com/Expensify/App/pull/27996

**Comment by s77rt** [comment] 2023-10-02 14:31
Not overdue. May need reproduction test after https://github.com/Expensify/App/pull/27996 gets merged

**Comment by CortneyOfstad** [comment] 2023-10-05 16:07
@s77rt looks like the PR was merged 15 hours ago — any updates?

**Comment by s77rt** [comment] 2023-10-06 01:10
Just tested. I can't reproduce the bug so probably it's fixed.

**Comment by CortneyOfstad** [comment] 2023-10-09 13:35
I couldn't reproduce either, so going to close this. Thank you!

**Closed by CortneyOfstad** 2023-10-09 13:35 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
