### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Android - Profile - Zip code field is auto populated with invalid format when adding address

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52237] opened 2024-11-08 09:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5196117&group_by=cases:section_id&group_order=asc&group_id=229064
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Settings" on the bottom of the screen.
3. Tap on "Profile"
4. Scroll down to "Address" and open the section.
5. Tap on "Address Line 1"
6. Complete with "123 Paddington Street" and select the "UK, London" option when it appears on suggestions.
7. Verify each field is auto populated correctly and tap on "Save"

## Expected Result:
When selecting an address from suggestions, all the fields should be auto populated properly and the user should be able to save this address.

## Actual Result:
When selecting "123 Paddington Street, UK, London" from address suggestions, the zip code field gets auto populated with an invalid format and the user is unable to save this address.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c36c3018-ca90-4e95-bdbb-1faff602c45b

 </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856693783876183313</li>
        <li>Upwork Job ID: 1856693783876183313</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104983746</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment] 2024-11-13 13:41
Opening up to the community since we already have a proposal.

**Comment by FitseTLT** [comment] 2024-11-14 22:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Android - Profile - Zip code field is auto populated with invalid format when adding address

### What is the root cause of that problem?
We are only allowing outward and inward code together in the regex here
https://github.com/Expensify/App/blob/17cae112dd45a4cb80b8dbbab020102f70ba7407/src/CONST.ts#L3761-L3764
but in this case it only provided the outward code, hence, the error.
### What changes do you think we should make in order to solve the problem?

The outward code is 2-4 char length code before the space and the inward code is 3 character length after the space so we should update the regex to allow for allowing omitting of the inward code. We do that by making the inward code(the regex part after the space as a whole optional with `?`)
```
/^[A-Z]{1,2}[0-9R][0-9A-Z]?\s*([0-9][A-Z-CIKMOV]{2})?$/
```
_Note that if we change the inward code part as `[0-9]?[A-Z-CIKMOV]{0,2}`, as suggested above, it will not enforce the inward code to be length of 3 and will generally lose the correct inward code regex rule already setup._
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-11-14 22:59
Edited by **proposal-police**: This proposal was **edited** at 2024-11-14 22:59:01 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Android - Profile - Zip code field is auto populated with invalid format when adding address

### What is the root cause of that problem?
We are only allowing outward and inward code together in the regex here
https://github.com/Expensify/App/blob/17cae112dd45a4cb80b8dbbab020102f70ba7407/src/CONST.ts#L3761-L3764
but in this case it only provided the outward code, hence, the error.
### What changes do you think we should make in order to solve the problem?

The outward code is 2-4 char length code before the space and the inward code is 3 character length after the space so we should update the regex to allow for allowing omitting of the inward code. We do that by making the inward code(the regex part after the space as a whole optional with `?`)
We will also need to add a sample without an inward code to inform the user that omitting it is possible.

```
 GB: { 
     regex:/^[A-Z]{1,2}[0-9R][0-9A-Z]?\s*([0-9][A-Z-CIKMOV]{2})?$/, 
     samples: 'LA102UX, BL2F8FX, BD1S9LU, WR4G 6LH, W1U', 
 }, 
```
_Note that if we change the inward code part as `[0-9]?[A-Z-CIKMOV]{0,2}`, as suggested above, it will not enforce the inward code to be length of 3 and will generally lose the correct inward code regex rule already setup._
The other problem I noticed in the regex regarding inward code is inward code are three char length with the first part digit followed by the second part of two letters but the letters cannot include the letters `CIKMOV` according to [here](https://www.tengosoftware.com/uk-postcode-format-gift-aid-tips/). But the CIKMOV in our regex is doing nothing right now so we should update that part too to exclude these letters by updating to character group of `[A-BD-HJLNP-UX-Z]`
### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-11-20 06:53
@mjasikowski quick bump on this

**Comment by mjasikowski** [comment] 2024-11-20 08:13
let's go with @FitseTLT's proposal!

**Comment by mjasikowski** [comment] 2024-11-22 10:56
Pinged @FitseTLT on Slack to get an update on his progress.

**Comment by FitseTLT** [comment] 2024-11-22 11:00
PR will be ready today 👍

**Comment by mananjadhav** [comment] 2024-11-22 21:20
PR will be posted soon and I'll try to finish the review over the weekend.

**Comment by mananjadhav** [comment] 2024-12-04 18:21
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<summary>Bug classification</summary>

Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: NA

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: NA

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

Regression Test Proposal Template.

I don't think we need a separate regression test for this one.

**Comment by mananjadhav** [comment] 2024-12-08 17:17
@JmillsExpensify Can you please post the payout summary so that I can raise the request?

**Comment by JmillsExpensify** [comment] 2024-12-09 09:46
As for the regression test, why would we not at a regression test for international addressees? That seems to be the main issue, and one that we should test in the future to ensure it doesn't happen again.

**Comment by JmillsExpensify** [comment] 2024-12-09 09:47
Contributor paid via Upwork.

**Comment by mananjadhav** [comment] 2024-12-09 10:00
> Version Number: 9.0.59-0
> Reproducible in staging?: Y
> Reproducible in production?: Y
> If this was caught on HybridApp, is this reproducible on New Expensify Standalone?: Y
> If this was caught during regression testing, add the test name, ID and link from TestRail: > https://expensify.testrail.io/index.php?/tests/view/5196117&group_by=cases:section_id&group_order=asc&group_id=22906

Because I thought it's already a part of the regression test? If it isn't then we'll need to add.

**Comment by JmillsExpensify** [comment] 2024-12-09 10:45
Ah, perfect, thanks for confirming. Ok, closing this issue out then, as your payment happens via New Expensify.

**Closed by JmillsExpensify** 2024-12-09 10:45 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-10 12:52
$250 approved for @mananjadhav
