### ISSUE TITLE
Onboarding - Some copy is not removed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42653] opened 2024-05-27 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/42408
## Action Performed:
1. Sign up with a new account
2. Select 'Manage teams'
3. Enter Business Name > First Name
4. Close the video modal

## Expected Result:
'Let's get your company set up! , your dedicated specialist, is online now and can answer your initial questions or provide a demo.
💬 CHAT WITH YOUR SETUP SPECIALIST' should be removed

## Actual Result:
'Let's get your company set up! , your dedicated specialist, is online now and can answer your initial questions or provide a demo.
💬 CHAT WITH YOUR SETUP SPECIALIST' is not removed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1710" alt="Bug6493080_1716826377012!Screenshot_2024-05-27_at_7 08 04_in_the_evening" src="https://github.com/Expensify/App/assets/78819774/eb7ca70d-cc2d-404f-9d9f-649102813eb6">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-27 17:41
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment] 2024-05-27 21:09
@lanitochka17 I don't understand the expected behavior. What do you mean it should be "removed"?

**Comment by kavimuru** [comment] 2024-05-28 12:22
@puneetlath I think it is dupe of https://github.com/Expensify/App/issues/41451

**Comment by puneetlath** [comment] 2024-05-28 13:48
Okay got it! Closing this out then.

**Closed by puneetlath** 2024-05-28 13:48 UTC
Labels: DeployBlockerCash, Engineering, Hourly, DeployBlocker

**Comment by NikkiWines** [comment] 2024-05-28 17:02
Ah yes sorry, the PR to update the rest of the copy beyond `Let's get you set up 🔧` is handled by [this internal PR](https://github.com/Expensify/Web-Expensify/pull/42109) which should be merged today You all are correct in that this isn't a blocker.
