### ISSUE TITLE
[HOLD for payment 2023-12-08] [$500]  Distance - Prevent deleting receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29684] opened 2023-10-16 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:** Applause - Internal Team

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Create a distance request to the workspace chat
4. Click on the distance request preview twice
5. Click on the receipt > Three-dot menu > Delete receipt > Delete
6. Click on Distance
7. Add a more stop and Save it

## Expected Result:
The new distance is saved

New: You should not be able to remove the distance receipt in the first place

## Actual Result:
The new distance is not saved. Clicking on Save does not save it and close the edit page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/cf4a86fa-b21b-452b-9854-e3746145b3af

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e0aeb0e907b54cf</li>
        <li>Upwork Job ID: 1715165699664687104</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27853396</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-10-16 15:48
Looks like receipt is required to edit distance request. 

Backend is sending error saying that receipt is not found
<img width="1210" alt="Screenshot 2023-10-16 at 20 39 13" src="https://github.com/Expensify/App/assets/59907218/fc778262-89a3-4dc5-bb31-b4106f27094b">

I think expected result should be sorted out before proceeding: Should distance request be allowed to be edited if its receipt is deleted?

**Comment by stephanieelliott** [comment] 2023-10-20 00:38
Ok, thanks! Adding labels to assign an internal engineer for BE changes.

**Comment by danieldoglas** [comment] 2023-10-23 12:32
adding @thienlnam since he was part of the core team for this!

**Comment by thienlnam** [comment] 2023-10-23 18:54
After an internal discussion, https://expensify.slack.com/archives/C05DWUDHVK7/p1698085763744569

The expected functionality is that you should not be able to remove the distance map receipt

**Comment by alitoshmatov** [comment] 2023-10-23 19:37
I can apply in frontend changes

I would apply additional `!TransactionUtils.isDistanceRequest(props.transaction)` check here, so that only non-distance receipts could be deleted:

https://github.com/Expensify/App/blob/5ad33724f2926f1b687bbac2b3d8fcfced5eb997/src/components/AttachmentModal.js#L379

**Comment by thienlnam** [comment] 2023-10-26 23:01
Started on a draft for the BE changes, moved to a weekly since it's not urgent by any means

**Comment by stephanieelliott** [comment] 2023-11-06 21:52
Hey @thienlnam not urgent, but any update here?

**Comment by thienlnam** [comment] 2023-11-07 03:23
BE Auth [PR](https://github.com/Expensify/Auth/pull/9052) is in review now! Once that is merged, will have to handle the FE updates

**Comment by thienlnam** [comment] 2023-11-09 09:06
Auth PR is live, now to to have the FE handled and successfully clearing the error

@alitoshmatov Since you've expressed interest, can you create a standard proposal for this?

**Comment by alitoshmatov** [comment] 2023-11-09 09:10
Sure, working on it

**Comment by alitoshmatov** [comment] 2023-11-09 09:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Prevent deleting receipt in distance iou.

### What is the root cause of that problem?
We have not implemented correct check for showing delete option in menu items.

### What changes do you think we should make in order to solve the problem?
We should apply additional `!TransactionUtils.isDistanceRequest(props.transaction)` check here, so that only non-distance receipts could be deleted:

https://github.com/Expensify/App/blob/5ad33724f2926f1b687bbac2b3d8fcfced5eb997/src/components/AttachmentModal.js#L379

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment] 2023-11-09 09:45
Can we also verify that an error is shown successfully and can be cleared even if you tried to delete a distance request receipt? Now that the BE PR is live, you should be able to test that as well

**Comment by alitoshmatov** [comment] 2023-11-10 17:50
@thienlnam Sorry I didn't understand what you mean, are implying that user would still be able to delete receipt even after implementing frontend changes?

**Comment by stephanieelliott** [comment] 2023-11-13 15:28
@alitoshmatov no, you should not be able to delete the receipt. I think what we want to test is that the error is shown when the receipt deletion is attempted, and it can be cleared by the user -- @thienlnam can you check me on that?

**Comment by thienlnam** [comment] 2023-11-19 18:38
Yeah that's correct - the button should be removed, this is just verifying the error message is shown correctly if we end up adding another method of deleting a receipt

**Comment by thienlnam** [comment] 2023-11-22 01:12
Pending proposal / proposal updates

**Comment by DylanDylann** [comment] 2023-11-22 02:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Unable to save distance edit after deleting receipt

### What is the root cause of that problem?
1. We don't hide delete button if the attachment is map receipt 
2. We don't handle errors in FE in case the user still deletes the map receipt in a special way
### What changes do you think we should make in order to solve the problem?

1. We should hide "Delete Receipt" button **only when the receipt is a map receipt** 
We should create a new variable like this
```
const isMapReceipt = lodashGet(props.transaction, 'routes.route0.geometry.coordinates', []).length > 0;
```

and we only display Delete button if isMapReceipt is true.

Note that: in case we use isDistanceRequest as a condition to display the delete button as above proposal. If you replace the receipt by a normal image, they can't delete it

2. Optional
Currently, if we apply the change as mentioned in 1. I don't see any way to call Delete Receipt API from FE. But we can save the error from BE in DeleteReceipt API to ONYX for using in future
### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2023-11-23 18:40
@dukenv0307 Failure data already contains transaction ID can we make use of that?
> The back-end needs to return the error message Onyx merge for receipt on the `transaction_${transactionId}` key

**Comment by Santhosh-Sellavel** [comment] 2023-11-27 13:50
Cool then @dukenv0307's [proposal](https://github.com/Expensify/App/issues/29684#issuecomment-1821954823) LGTM here.

C+ Reviewed
🎀 👀 🎀

**Comment by thienlnam** [comment] 2023-11-28 18:28
> The user can still replace the receipt with the uploaded image. In this case, do you guys want to display delete option ?

Yeah we don't want to allow replacing the receipt either - We'll also need to make BE changes for this but for now can you hide the option in the FE?

**Comment by stephanieelliott** [comment] 2023-12-08 17:18
Summarizing payment on this issue: 

 - Issue reporter: N/A
 - Contributor: $500 @dukenv0307 PAID via Upwork 
 - Contributor+:  $500, @Santhosh-Sellavel can you please complete the BZ checklist? 
 
 Upwork job is [here](https://www.upwork.com/jobs/~019e0aeb0e907b54cf)

**Comment by Santhosh-Sellavel** [comment] 2023-12-10 19:16
Regression Steps should be enough here because the behavior was intentional earlier when it was added. Let me know your thoughts @thienlnam 


### Steps

1. Create a distance request
2. After the request is created, go to the transaction thread report
3. Click on the receipt image
4. Click on the three-dot in the attachment modal
5. Verify that only the download option appears

**Comment by stephanieelliott** [comment] 2023-12-13 15:25
Issue for QA test here: https://github.com/Expensify/Expensify/issues/349090

All clear here, @Santhosh-Sellavel please request your payment via newdot!

**Closed by stephanieelliott** 2023-12-13 15:25 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-01-10 17:20
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-01-14 08:52
$500 payment approved for @Santhosh-Sellavel based on [this comment](https://github.com/Expensify/App/issues/29684#issuecomment-1847552645).
