### ISSUE TITLE
[HOLD for overpayment refund] [$1000] Web - Duplicate particpant name and avatar at the top of the Money request message.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25819] opened 2023-08-24 09:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login as User A and User B in front of you at the same time.
2. As User A Open User B chat and request money( make sure it works by avoiding the bugs around IOU feature Now  )
3.  As User B Open the same chat and request  money from User A.

## Expected Result:
Both Patticpants names and avatars should be displayed at the top of the Money request message.

## Actual Result:
Duplicate particpant name and avatar ( User A name and avatar ) at the top of the Money request message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-0

**Reproducible in staging?:** Y

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2f69d740-9103-4ac8-bbc0-9e975a1cde86

https://github.com/Expensify/App/assets/115492554/4ac578be-f154-427c-91a0-e58246ec419e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ahmed-Abdella

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692033869443169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc2d76b91c3cdcd1</li>
        <li>Upwork Job ID: 1696679786881073152</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26790515</li>
<li>hungvu193 | Contributor | 26790518</li>
<li>Ahmed-Abdella | Reporter | 26790520</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-08-30 00:22
Was able to reproduce, seems like it'd be External

**Comment by mallenexpensify** [comment] 2023-09-04 03:03
@situchan can you please review @hungvu193 's proposal above? https://github.com/Expensify/App/issues/25819#issuecomment-1691530037

**Comment by mallenexpensify** [comment] 2023-09-04 03:03
@adelekennedy  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by adelekennedy** [comment] 2023-09-06 21:39
@situchan Should we up the bounty?

**Comment by situchan** [comment] 2023-09-07 18:40
@adelekennedy yes, still open for better proposals.

This is long lasting issue after #21102

**Comment by mallenexpensify** [comment] 2023-09-11 06:17
Thanks for 👀 @adelekennedy 
@situchan can you provide feedback on @hungvu193 's proposal and why you propose we wait for other proposals? Thx

**Comment by mallenexpensify** [comment] 2023-09-14 08:22
@situchan please review the above proposals, it's been over a week

**Comment by mallenexpensify** [comment] 2023-09-19 09:26
Unassigned @situchan due to inactivity. @jjcoffee , can you please review the proposals above?

**Comment by situchan** [comment] 2023-09-19 19:39
Sorry for late here. We should consider various cases to fix the issue completely. That's why I didn't approve any proposal.
I will post update after handling urgent issues.

**Comment by jjcoffee** [comment] 2023-09-20 07:36
@situchan If you have other cases, please note them here so that you don't block us moving forward with this. Thanks!

**Comment by hayata-suenaga** [comment] 2023-09-21 00:36
const secondaryAccountId = props.iouReport.ownerAccountID === actorAccountID ? props.iouReport.managerID : props.iouReport.ownerAccountID;


can you kindly explain what these IDs are?

- `iouReport.managerID`
- `iouReport.ownerAccountID`
- `actorAccountID`

**Comment by hayata-suenaga** [comment] 2023-09-21 05:41
thank you for the explanation @hungvu193 assigned you

**Comment by Ahmed-Abdella** [comment] 2023-09-21 11:33
Sorry @mallenexpensify @hayata-suenaga , but this issue was reported before the rate change shouldn't it be at 250$ rate?

**Comment by jjcoffee** [comment] 2023-09-22 12:07
Just to note we're pondering over whether or not it's expected behaviour for the avatars to switch places, so I've raised it [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1695384309904919) to field some opinions.

**Comment by mallenexpensify** [comment] 2023-09-25 09:15
@Ahmed-Abdella correct, sent you a new offer at $250

**Comment by situchan** [comment] 2023-10-06 03:02
There was regression from [PR](https://github.com/Expensify/App/pull/27912) fixing this issue - https://github.com/Expensify/App/issues/28554
And fixed by https://github.com/Expensify/App/pull/28350

**Comment by jjcoffee** [comment] 2023-10-06 12:22
@situchan Thanks for flagging! I don't think you are correct, however. I can't replicate when retesting on [the PR](https://github.com/Expensify/App/pull/27912):


https://github.com/Expensify/App/assets/27287420/b08c6a34-0ad3-494a-989b-ca5e3295ebfa

**Comment by jjcoffee** [comment] 2023-10-13 10:49
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23043
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23043#issuecomment-1761309273
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A** - just required more thorough testing
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Login as User A and User B in front of you at the same time.
2. As User A request money from User B
3. As User B request money from User A
4. Verify that the IOU preview displays two different avatars and display names

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-10-13 10:49
@mallenexpensify Checklist complete, and a friendly bump on the payment!

**Comment by hayata-suenaga** [comment] 2023-10-16 12:17
melvin, we're waiting for payment

**Comment by mallenexpensify** [comment] 2023-10-17 20:05
Issue reporter: @Ahmed-Abdella paid $250 via Upwork
Contributor: @hungvu193 paid $1500 via Upwork, inc urgency bonus
Contributor+: @jjcoffee paid $1500 via Upwork, inc urgency bonus

Regression Test
- https://github.com/Expensify/Expensify/issues/327008

@jjcoffee can you confirm there wasn't a regression from the PR for this issue? I see a comment above but not anything in the PR https://github.com/Expensify/App/pull/27912

**Comment by jjcoffee** [comment] 2023-10-18 09:08
Thanks @mallenexpensify! I wasn't able to repro the regression that @situchan commented [here](https://github.com/Expensify/App/issues/25819#issuecomment-1749920162) when [retesting](https://github.com/Expensify/App/issues/25819#issuecomment-1750558270) with just our PR, so it must have come from some other change.

**Comment by situchan** [comment] 2023-10-18 10:01
> Thanks @mallenexpensify! I wasn't able to repro the regression that @situchan commented [here](https://github.com/Expensify/App/issues/25819#issuecomment-1749920162) when [retesting](https://github.com/Expensify/App/issues/25819#issuecomment-1750558270) with just our PR, so it must have come from some other change.

Please check the root cause in https://github.com/Expensify/App/issues/28554#issuecomment-1741965153

**Comment by hayata-suenaga** [comment] 2023-10-23 02:38
As @situchan suggested, theres seem to be a regression from this PR. @jjcoffee if you don't think otherwise, I think we can consider that a regression happened.

**Comment by jjcoffee** [comment] 2023-10-23 11:55
@hayata-suenaga Ohh my apologies, I thought I wasn't able to repro with just our PR, but actually I misunderstood [this comment](https://github.com/Expensify/App/issues/28554#issuecomment-1749698437) as meaning that the behaviour was happening for manual requests too, but apparently it was only for distance + scans. Agree now that there was indeed a regression. Sorry for the confusion!

**Comment by mallenexpensify** [comment] 2023-10-23 16:19
Ok, I'm updating the above for payment to account for the regression and removing the urgency bonus (per [CONTRIBUTING.md ](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#regressions)) 
> the assigned Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) are not eligible for the 50% urgency bonus

I've requested refunds of $1k from @hungvu193 and @jjcoffee , will leave this issue open til I confirm the funds have been refunded.

**Comment by jjcoffee** [comment] 2023-10-24 08:53
Will need a few days before my account gets topped back up enough to issue the refund. Sorry about this mess!

**Comment by hayata-suenaga** [comment] 2023-10-26 15:54
Melvin, we're waiting for the refound

**Comment by jjcoffee** [comment] 2023-10-30 09:03
@mallenexpensify Refunded! :bow:

**Comment by mallenexpensify** [comment] 2023-10-30 22:55
Thanks @jjcoffee and @hungvu193, confirming the refunds and that the total payment was $500 each.

**Closed by mallenexpensify** 2023-10-30 22:55 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
