### ISSUE TITLE
[$250] Sign in – Chat long loading when login via magic link using Recovery code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46730] opened 2024-08-02 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4804201
**Email or phone of affected tester (no customers):** ponikarchuks+102824@gmail.com
**Issue reported by:** Applause - internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In Sign in page enter Gmail email of a user with 2FA enabled
3. Open email and navigate via Magic link
4. Go back to Sign in page and click Use recovery code
5. Paste Recovery code and press Sign in

## Expected Result:
 Chat history opens

## Actual Result:
Chat long loading

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/da60b43c-ea0d-49f8-8f2f-6a34638d5223

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013259ceff7cd5e594</li>
        <li>Upwork Job ID: 1820564666420399442</li>
        <li>Last Price Increase: 2024-09-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-02 15:26
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-02 15:26
We think that this bug might be related to #vip-vsp

**Comment by johncschuster** [comment] 2024-08-09 21:32
@jjcoffee, it's very likely this issue will be closed if we can't either 1) have it fixed by an external contributor, or 2) redistribute this under a different, prioritized project.

#vip-vsb has been deprioritized internally, so if this winds up being a BE issue, we will likely close it.

**Comment by johncschuster** [comment] 2024-08-09 21:33
bump

**Comment by jjcoffee** [comment] 2024-08-12 10:48
Hmm I can't repro myself, @lanitochka17 can you retest and let us know if there are any specific extra steps involved? There's a cut in the video so I'm wondering if there's something missing from there.

**Comment by johncschuster** [comment] 2024-08-15 13:11
[Asking in Slack for a restest](https://expensify.slack.com/archives/C9YU7BX5M/p1723727355316079)

**Comment by lanitochka17** [comment] 2024-08-15 15:43
Chat long loading, but opens

https://github.com/user-attachments/assets/9b87c3f6-3a2b-46b2-87bf-8a8d50ba247c

**Comment by jjcoffee** [comment] 2024-08-16 09:36
@lanitochka17 Thanks for the retest! Can you confirm if this only happens when you have two tabs open?

**Comment by jjcoffee** [comment] 2024-08-19 09:45
Not overdue, waiting for @lanitochka17's response on [the above](https://github.com/Expensify/App/issues/46730#issuecomment-2293176012).

**Comment by lanitochka17** [comment] 2024-08-20 16:19
The problem reproducible  when logging in via the Magic link on the second tab, i.e. two tabs open.

**Comment by johncschuster** [comment] 2024-08-21 20:31
@jjcoffee looks like we've got our confirmation on the repro steps!

**Comment by jjcoffee** [comment] 2024-08-22 08:01
Trying to get some attention on this [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1724313653043439).

**Comment by johncschuster** [comment] 2024-08-26 22:16
[Bumped in Slack!](https://expensify.slack.com/archives/C01GTK53T8Q/p1724710587786139)

**Comment by NJ-2020** [comment] 2024-08-27 09:10
I cannot reproduce this issue

**Comment by jjcoffee** [comment] 2024-08-27 12:22
@NJ-2020 Thanks for trying! Did you make sure to [open the magic link](https://github.com/Expensify/App/issues/46730#issuecomment-2299251186) in a new tab?

**Comment by NJ-2020** [comment] 2024-08-27 13:36
@jjcoffee Yes but i couldn't reproduce the issue

**Comment by johncschuster** [comment] 2024-08-29 21:29
[Asking for a restest](https://expensify.slack.com/archives/C9YU7BX5M/p1724966905019279)

**Comment by m-natarajan** [comment] 2024-08-30 19:32
Works good now

https://github.com/user-attachments/assets/cb90698e-cd50-4388-9e9c-758c3b1cca68

**Comment by johncschuster** [comment] 2024-09-03 21:14
Just saw the results from [this comment](https://github.com/Expensify/App/issues/46730#issuecomment-2322213340). Looks like we can button this one up!

**Closed by johncschuster** 2024-09-03 21:14 UTC
Labels: External, Daily, Help Wanted, Bug
