### ISSUE TITLE
Android - Workspace - In WS chat room details page, long WS name is truncated inconsistently

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45636] opened 2024-07-17 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4697549
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: create a workplace with long workspace name - 5 : yradhe-krishna-dfgggggghhhhhhh-hhhhhhhhh-hhhhhhhhhghbbn😁😄😄
1. Launch app in both mweb and android
2. Tap on a Workplace chat room with long workspace name
3. Tap on the header

## Expected Result:
In workspace chat room details page, long workspace name must be truncated consistently in same manner

## Actual Result:
In workspace chat room details page, long workspace name is truncated inconsistently

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1f59a497-4813-4a6e-9757-ea623e8caccd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-17 20:56
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-17 20:57
We think that this bug might be related to #vip-vsp

**Comment by neonbhai** [comment] 2024-07-17 21:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Workspace - In WS chat room details page, long WS name is truncated inconsistently 

### What is the root cause of that problem?
Title is truncated as it is missing an individual flex style, causing it to not take the available space on native
https://github.com/Expensify/App/blob/dee47a51ecbae80a31e88fdbfedb084f916b1c9a/src/pages/ReportDetailsPage.tsx#L691

### What changes do you think we should make in order to solve the problem?
We will wrap this line with a `View` and add `styles.flex1` on it
https://github.com/Expensify/App/blob/dee47a51ecbae80a31e88fdbfedb084f916b1c9a/src/pages/ReportDetailsPage.tsx#L691

**Comment by sonialiap** [comment] 2024-07-22 10:22
dupe of https://github.com/Expensify/App/issues/45475

**Closed by sonialiap** 2024-07-22 10:22 UTC
Labels: Daily, Overdue, Bug
