### ISSUE TITLE
[WAITING ON SOBIT - CHECKLIST] [$250] Selected row in onboarding modal should not get :hover style

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44055] opened 2024-06-20 00:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718816345646859

## Action Performed:
1. Sign up for a new account
2. In the onboarding modal, select an option
3. Hover over the selected option

## Expected Result:
Selected row should not get a hover style

## Actual Result:
Selected row changes BG color on hover

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/2319350/67429660-14dd-474c-9751-b87c15f55850

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ffaa9b43dacb7a8a</li>
        <li>Upwork Job ID: 1806378179434309152</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 103133129</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by truph01** [comment] 2024-06-20 02:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect row hover style is showing
- We are using ```backgroundColor: theme.activeComponentBG``` for ```hoverAndPressStyle```.
### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
- We should use ```styles.hoveredComponentBG``` instead.

### What alternative solutions did you explore? (Optional)

**Comment by neonbhai** [comment] 2024-06-20 07:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding modal uses incorrect row hover style when hovering over the options

### What is the root cause of that problem?
There are two problems:
- The hoverStyle is being passed incorrectly [here](https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L100)
- The MenuItem styles [here](https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/components/MenuItem.tsx#L510-L516) applied in the wrong order.



  Current order applies hover style after the active button style giving us this behavior:

  <Details><Summary>Video (hover applied after active style)</Summary>


  

  https://github.com/Expensify/App/assets/64629613/0c3c3102-06da-4fa8-928b-b3d2c35ccf8f




  </Details>
 

#### Additionally:
  This order effectively prevents us from seeing the pressed style for `menuItem` as defined here:

  https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/styles/utils/index.ts#L1320-L1321

  Which gives us this tactile feedback when pressing:

  <Details><Summary>Video</Summary>


  https://github.com/Expensify/App/assets/64629613/675e68af-a6d1-4d57-8947-4aff2e9c137b


  </Details>

### What changes do you think we should make in order to solve the problem?
- change [this line](https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L100) to:
  ```jsx
  hoverAndPressStyle: [styles.hoveredComponentBG],
  ```

- Move this style:
  https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/components/MenuItem.tsx#L513
  after this line:
  https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/components/MenuItem.tsx#L515

  ```diff
  --  StyleUtils.getButtonBackgroundColorStyle(getButtonState(focused || isHovered, pressed, success, disabled, interactive), true),
      ...(Array.isArray(wrapperStyle) ? wrapperStyle : [wrapperStyle]),
      !focused && (isHovered || pressed) && hoverAndPressStyle,
  ++  StyleUtils.getButtonBackgroundColorStyle(getButtonState(focused || isHovered, pressed, success, disabled, interactive), true),
  ```



### Alternatively
If we don't want feedback on active press we can add a check for `!isMenuItem` [here](https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/styles/utils/index.ts#L1321)

**Comment by truph01** [comment] 2024-06-20 08:09
### [Updated proposal](https://github.com/Expensify/App/issues/44055#issuecomment-2179711731)

**Comment by shawnborton** [comment] 2024-06-25 18:20
@mallenexpensify can you please review this when you get a moment? Thanks!

**Comment by mallenexpensify** [comment] 2024-06-27 17:26
@sobitneupane , 👀 on the above proposals plz? Please keep in mind at @truph01 's proposal had been updated many times

<img width="543" alt="image" src="https://github.com/Expensify/App/assets/22508304/d22b707a-f5b7-484d-ae6a-b47f7725a76e">

**Comment by truph01** [comment] 2024-06-27 17:35
@mallenexpensify Yeah, my last update time was 3:04 PM, and then I commented ["Proposal Updated"](https://github.com/Expensify/App/issues/44055#issuecomment-2180074209) at 3:10 PM as mentioned in the contributor guides.

**Comment by mallenexpensify** [comment] 2024-06-28 01:55
@truph01 , yes, please continue to post 'proposal updated' when you do. I was referencing that updates were made over a handful of hours which might affect consideration of other proposals if they were submitted within that time.

**Comment by sobitneupane** [comment] 2024-06-28 08:02
@shawnborton Looks like the issue is not reproducible any longer.


https://github.com/Expensify/App/assets/25876548/f672ed8d-4751-4963-b495-d75fca736e49

**Comment by shawnborton** [comment] 2024-06-28 08:40
Interesting, if that's the case, we can just close this. Let me test quickly as well...

**Comment by shawnborton** [comment] 2024-06-28 08:42
Indeed it looks fixed. But let me ask a follow up question for the @Expensify/design team - should we make it so that the row that has the :active/:selected state should not get a hover BG? I think yes? But I don't feel too strongly. I think our existing patterns in the app make it so that anything that has a selected state doesn't get a hover BG color (like LHN items for instance).

**Comment by dannymcclain** [comment] 2024-06-28 14:08
Yes 100% agree on that point Shawn. It's weird for the selected item to go from heavily emphasized to not-as-emphasized on hover.

**Comment by shawnborton** [comment] 2024-06-28 14:10
Okay cool, I'll go ahead and modify the title + body, and maybe we can take a new round of proposals here?

**Comment by truph01** [comment] 2024-06-28 14:33
### [Proposal updated](https://github.com/Expensify/App/issues/44055#issuecomment-2179711731)

- I updated alternative solution.

**Comment by sobitneupane** [comment] 2024-07-01 09:54
Thanks for the update @truph01 

Your alternative solution looks good to me but I believe we would want that behavior throughout the app not only in onboarding modal. Maybe we can use existing props in MenuItem instead of passing `isSelected` prop.

**Comment by truph01** [comment] 2024-07-01 10:08
@sobitneupane What about my main solution? This [PR](https://github.com/Expensify/App/pull/43987) should be reverted because it makes the change to the MenuItem component directly, meanwhile, MenuItem is used in a lot of positions in the app, that can leads to the regression. In this case, it introduces a regression mentioned in [comment](https://github.com/Expensify/App/issues/44055#issuecomment-2196424023): "the row that has the :active/:selected state get a hover BG"

**Comment by sobitneupane** [comment] 2024-07-02 09:20
> Maybe it exists in the product, but I think :hovering over any push row or option row should use our rowHover color, which does not collide with our border color.

I believe we would want the hovered action to have `hoveredComponentBG`  throughout the app if the menuitem is interactive and is not clicked or selected. If that is the case, I think it's okay to make change in MenuItem.

@shawnborton Could you please confirm the behavior? Do we want the hovered color to be `hoveredComponentBG` throughout the app if the menu item is interactive and is not selected? 

Not only in onboarding modal, selected row has :hover style even in settings menu item.

**Comment by truph01** [comment] 2024-07-02 09:35
Please note the above [behavior](https://github.com/Expensify/App/issues/44055#issuecomment-2202550143) appears after this [PR](https://github.com/Expensify/App/pull/43987), which breaks our behavior before.

**Comment by shawnborton** [comment] 2024-07-02 09:50
Got it, yeah I am saying we do NOT want that behavior. If the row is in the selected state, do not give it a hover color.

**Comment by sobitneupane** [comment] 2024-07-05 09:06
@truph01 Would you want to update your proposal based on https://github.com/Expensify/App/issues/44055#issuecomment-2199719498?

**Comment by truph01** [comment] 2024-07-05 09:11
@sobitneupane Sure. But if we choose that solution, it does not fix this [comment](https://github.com/Expensify/App/issues/44055#issuecomment-2202591203). What do you think?

**Comment by truph01** [comment] 2024-07-05 09:12
@sobitneupane I am updating it...

**Comment by truph01** [comment] 2024-07-05 09:17
### [Proposal updated](https://github.com/Expensify/App/issues/44055#issuecomment-2179711731)

**Comment by mallenexpensify** [comment] 2024-07-09 00:59
@sobitneupane plz review @truph01 's updated proposal above.

**Comment by sobitneupane** [comment] 2024-07-09 08:22
Since we want all the hovered Menu Item to have same behvaior throughout the app as mentioned [here](https://github.com/Expensify/App/issues/44055#issuecomment-2202540892), I believe the alternative solution would be the better option.

Alternative [proposal](https://github.com/Expensify/App/issues/44055#issuecomment-2179711731) from @truph01 looks good to me.

C+ reviewed

**Comment by mallenexpensify** [comment] 2024-07-16 01:00
@marcaaron 👀 [above](https://github.com/Expensify/App/issues/44055#issuecomment-2216920123) plz

**Comment by truph01** [comment] 2024-07-16 17:17
PR https://github.com/Expensify/App/pull/45499 is ready

**Comment by jliexpensify** [comment] 2024-08-01 23:37
Payment Summary

- C: @truph01 $250 ([Upwork job](https://www.upwork.com/jobs/~01ffaa9b43dacb7a8a))
- C+: @sobitneupane (ND payment)

Waiting on checklist

**Comment by jliexpensify** [comment] 2024-08-03 06:34
Paid and job closed. @sobitneupane bump for checklist!

**Comment by sobitneupane** [comment] 2024-08-05 10:04
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/43987
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/43987/files#r1703875086
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I don't think any new update is required.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-08-05 10:06
**Regression Test Proposal**

1. Sign up for a new account
2. In the onboarding modal, select an option
3. Hover over the selected option
4. Verify that the selected option does not get hover style.

Do we agree 👍 or 👎

**Comment by marcaaron** [comment] 2024-08-06 01:01
LGTM @sobitneupane

**Comment by mallenexpensify** [comment] 2024-08-07 00:27
Test Case GH, thanks @sobitneupane 
https://github.com/Expensify/Expensify/issues/418347

**Closed by mallenexpensify** 2024-08-07 00:27 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-02 17:39
$250 approved for @sobitneupane based on [this summary](https://github.com/Expensify/App/issues/44055#issuecomment-2264214051).
