### ISSUE TITLE
[HOLD for payment 2023-06-30] [$1000] On Terms and Fees Page Monthly Fee, Purchase Fee, ATM Withdrawal fee values are cropped.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20678] opened 2023-06-13 14:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/enable-payments
2. Complete the step until you reach the Terms and Fees Page
3. Check the value fields mentioned
## Expected Result: 
Text/Values are visible clearly as it is on other platforms
## Actual Result: 
Any values/text should not be cropped

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img src="https://github.com/Expensify/App/assets/43996225/608bede1-64d6-4c36-80b3-31e421fe09c2" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/abd83d6f-f6fc-4d10-8198-4b2b5f8326e8" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686161977469969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01229c1dea62af0f2e</li>
        <li>Upwork Job ID: 1668624335111434240</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-06-13 14:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Terms and Fees Page Monthly Fee, Purchase Fee, ATM Withdrawal fee values are cropped.

### What is the root cause of that problem?
In `ShortTermsForm` we have this:
```js
<View style={[styles.flex2]}>
    <View style={[styles.flexRow, styles.mb1]}>
        <Text style={styles.textLarge}>{Localize.translateLocal('termsStep.monthlyFee')}</Text>
    </View>
    <View style={styles.flexRow}>
        <Text style={[styles.textHeadline, styles.textXXXLarge]}>{Localize.translateLocal('termsStep.feeAmountZero')}</Text>
    </View>
</View>
```
Second `TextView` is the one with the '$0' in it, which is cropped at top. It has `style={[styles.textHeadline, styles.textXXXLarge]}` where `styles.textHeadline` sets both `fontSize` & `lineHeight`, but `styles.textXXXLarge` sets only the `fontSize`, thus making the text bigger than the available line height, resulting in it being cropped. The above code appears twice, 1 for the '$0' on the left, 1 for the '$0' on the right.

### What changes do you think we should make in order to solve the problem?
Update `styles.textXXXLarge` to also include a corresponding `lineHeight`. In `variables.js` we currently have `lineHeightSmall, lineHeightNormal, ..., lineHeightXXLarge`, so we need to add 1 more: `lineHeightXXXLarge: getValueUsingPixelRatio(32, 37)`.

<details>
<summary>Result:</summary>
<img src="https://github.com/Expensify/App/assets/56603839/283840c8-3e73-4b45-9d7a-d1d0f95e65a1" width="250px">
</details>

### What alternative solutions did you explore?
Create a new style to be used only for these 2 `TextView`'s like:
```js
  fontSize: variables.fontSizeXXXLarge,
  lineHeight: variables.lineHeightXXXLarge
```
and replace `styles.textXXXLarge` with it.

**Comment by Pujan92** [comment] 2023-06-13 16:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Terms and Fees Page Monthly Fee, Purchase Fee, ATM Withdrawal fee values are cropped.

### What is the root cause of that problem?
We are setting the font-size of `32px` with keeping the lineHeight of `27px` which is causing this issue. For the values we are only providing the increase fontSize without the needed lineHeight here.
https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/pages/EnablePayments/TermsPage/ShortTermsForm.js#L29

https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/styles/styles.js#L339-L341

### What changes do you think we should make in order to solve the problem?
We need to set correct `lineHeight` for this `fontSize` text and it needs to be more than the `fontSize`.

We can define one more variable called `lineHeightXXXXLarge: getValueUsingPixelRatio(37, 42),`

Used that variable for the class `textXXXLarge` `lineHeight: variables.lineHeightXXXXLarge,`

**Comment by DanutGavrus** [comment] 2023-06-15 11:52
@allroundexperts What do you think about [my Proposal](https://github.com/Expensify/App/issues/20678#issuecomment-1589412694)? 👀

**Comment by DanutGavrus** [comment] 2023-06-16 11:15
@allroundexperts Would you rather prefer us to add the `lineHeight` directly to the `styles.textXXXLarge` such that all texts in the app with this style will get the corresponding line height possibly fixing/preventing other crop issues, or to just create a _new_ style which we'll use _only_ for these problematic `TextViews` in this issue?

**Comment by Pujan92** [comment] 2023-06-16 11:15
Thanks @allroundexperts but to argue as the root cause/solution is very straightforward I thought to provide the correct value for the `lineHeight` as it should not be the same of `fontSize`.

**Comment by bfitzexpensify** [comment] 2023-06-19 06:44
I think let's just target this specific issue for now, rather than adding `lineHeight` to all 5 styles.

**Comment by DanutGavrus** [comment] 2023-06-19 07:28
@bfitzexpensify I agree! Should I create the PR?

**Comment by bfitzexpensify** [comment] 2023-06-19 07:29
Yes, please!

**Comment by DanutGavrus** [comment] 2023-06-19 08:49
@allroundexperts @bfitzexpensify 
PR created: [PR21015](https://github.com/Expensify/App/pull/21015)

**Comment by DanutGavrus** [comment] 2023-06-21 16:14
Are Melvin calculations correct?

**Comment by DanutGavrus** [comment] 2023-06-21 16:38
@deetergp but even with your hold, "within 3 working days" is inclusive and Malvin says "days elapsed: 3". Is there something wrong in how Melvin makes its calculations, or am I misunderstanding the guidelines?

**Comment by deetergp** [comment] 2023-06-21 20:28
Oh, I understand what you mean. I agree `days elapsed: 3` seems like it should be considered as being `within 3 days`.

**Comment by bfitzexpensify** [comment] 2023-06-23 06:54
Thanks for pointing that out @DanutGavrus, it does seem there's an issue there with the calculations being completed. I've raised the issue internally.  

This particular issue does qualify for the urgency bonus, so we can ignore what Melvin has said there.

**Comment by bfitzexpensify** [comment] 2023-06-29 05:58
Moved to daily so I can issue payments tomorrow

**Comment by bfitzexpensify** [comment] 2023-06-30 10:10
Offers sent out @Santhosh-Sellavel @DanutGavrus @allroundexperts. 

@allroundexperts, please complete the BZ checklist when you get a chance!

**Comment by bfitzexpensify** [comment] 2023-07-03 07:38
Bump on BZ checklist @allroundexperts - thanks!

**Comment by bfitzexpensify** [comment] 2023-07-05 10:52
>I think a regression test might not be needed here because the existing regression test for this page should have caught this. Let me know @deetergp if you disagree and I'll propose the steps for the test.

I agree with you, I don't think we need a new test here. 

Let's close this out!

**Closed by bfitzexpensify** 2023-07-05 10:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
