### ISSUE TITLE
[$500] Web - Chat - When sign in to Expensify, lost a conversation with a new message on LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26656] opened 2023-09-04 12:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open 2 accounts on 2 browser
2.  User A sign out
3. User B send a message to User A
4. User A login to Expensify again

## Expected Result:
Received a message from user B on the top of LHN

## Actual Result:
User A does not receive messages from user B and does not see the conversation on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dd733ee4-147e-4323-b247-65b8518e7707

https://github.com/Expensify/App/assets/115492554/770ea044-642d-445d-ae10-49dd73a1b09c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Le Thi Thu Thuy

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692954768122869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01408683b571052093</li>
        <li>Upwork Job ID: 1713976162400333824</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-09-13 08:48
Isn't this a dupe of the linked issue?

**Comment by JmillsExpensify** [comment] 2023-09-13 08:49
Indeed that looks to be the case. Minimally we should hold on that issue to confirm.

**Comment by JmillsExpensify** [comment] 2023-10-10 23:00
The linked issue is now closed, though I'll have to come back to reproducing this one.

**Comment by JmillsExpensify** [comment] 2023-10-16 17:52
Going to open this up to the community in case anyone else can reproduce and would like to work on this one.

**Comment by MrMuzyk** [comment] 2023-10-19 11:33
@izarutskaya 
Hey, I couldn't reproduce the issue (see the video). Can you confirm that it still happens?

https://github.com/Expensify/App/assets/23487612/9ab06b97-5b5a-43c6-9456-c6a33a9cedcc

**Comment by JmillsExpensify** [comment] 2023-10-24 18:10
I wasn't able to reproduce this one either, so closing.

**Closed by JmillsExpensify** 2023-10-24 18:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
