### ISSUE TITLE
[$1000] Payments - "Add Payment Method" does not response when tap on it while offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24272] opened 2023-08-08 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings > Payments
2. Disable the internet connection in the device
3. Tap on "Add Payment Method"

## Expected Result:
User should be able to tap on "Add Payment Method" button and select "PayPal.me" when navigate there when offline

## Actual Result:
"Add Payment Method" does not response when tap on it while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/92544e92-58dc-43b9-b59a-78d8d95d90ca

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01552488fc1d8d6853</li>
        <li>Upwork Job ID: 1689576942050172928</li>
        <li>Last Price Increase: 2023-08-10</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-08 15:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add payment method button is disabled when the device is offline.

### What is the root cause of that problem?
The button's isDisabled flag is modified based on an isOffline flag int he PaymentMethodList component.

### What changes do you think we should make in order to solve the problem?
Remove the isOffline flag from the isDisabled prop then conditionally display options.

### What alternative solutions did you explore? (Optional)
None.

**Comment by DylanDylann** [comment] 2023-08-08 16:42
In close account page and connect bank account, the user can't access when offline. So I think this is not a bug, because we should prevent user do important action like add payment method when offline like we did in close account and connect bank account

**Comment by DylanDylann** [comment] 2023-08-08 16:45
Contributor details
Your Expensify account email: [dylandylan9112@gmail.com](mailto:dylandylan9112@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~010c6310ab55f3d17d

**Comment by DylanDylann** [comment] 2023-08-08 16:47
Contributor details
Your Expensify account email: dylandylan9112@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010c6310ab55f3d17d

**Comment by flaviadefaria** [comment] 2023-08-14 13:58
I agree with other GH and will close this as well.

**Closed by flaviadefaria** 2023-08-14 13:58 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
