### ISSUE TITLE
[$500] Distance - Request created with ../participants link returns app to request steps when going back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32274] opened 2023-11-30 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Tap FAB > Request money > Distance.
3. Modify the link to .../new/participants.
4. Continue with Distance request creation.
5. After creating the request, return to previous page using device navigation (or browser back button for web).

## Expected Result:
App will return to the previous report or LHN.

## Actual Result:
App returns to the distance request creation steps (confirmation page, workspace selection, request money page) rather than LHN. Request money page appears multiple times when attempting to return to LHN using device back button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/927f33f1-415c-4d81-bff6-91ae31e58519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2023-11-30 16:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Distance - Request created with ../participants link returns app to request steps when going back
### What is the root cause of that problem?
The root cause of the problem is this line of code
https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
that was added in this [pr](https://github.com/Expensify/App/pull/31316) to solve deeplinking issue on logout for Android. 
So when we input `../participants` link it will redirect us to `request/new/distance` and after we are naviagted to the request distance page (or manual it doesn't matter) 
https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
this line of code is pushing the route to navigation state making the routes to be length of three (instead of two) with two of them `RightModalNavigator`. So after finishing the money request creation process only one of the `RightModalNavigator` is popped by `dismissModal` therefore when we navigate back from the report it will navigate back for the other unnecessary `RightModalNavigator` added to the route.
### What changes do you think we should make in order to solve the problem?

We just need to add a condition here https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
to check that it native b/c we only need it to run for native as I explained to fix deeplinking problem.
so change it to
```
if (!willBlurTextInputOnTapOutside) {
                    Navigation.navigate(route, CONST.NAVIGATION.ACTION_TYPE.PUSH);
                }
```
### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment] 2023-12-12 01:50
Hey @eVoloshchak can you review the above please?

**Comment by eVoloshchak** [comment] 2023-12-13 18:03
Looks like we recently changed how the link is structured,https://staging.new.expensify.com/create/request/participants opens a not found page, while https://staging.new.expensify.com/request/new/participants is redirecting to manual request tab

@FitseTLT, could you please verify this is still reproducible for you?

**Comment by FitseTLT** [comment] 2023-12-13 18:29
@eVoloshchak Can't.

**Comment by kevinksullivan** [comment] 2023-12-20 01:14
Closing unless someone shows this is still reproducible.

**Closed by kevinksullivan** 2023-12-20 01:14 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
