### ISSUE TITLE
[$2000] Task - Task message not removed from original assignee chat when a different assignee is set for the same task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21585] opened 2023-06-26 16:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign a task to User A
2. Verify it creates a new task report and also there is a new message in User A chat related to the task
3. Now go into task report, click on header and change task assignee to User B
4. Verify it correctly assigns the task to User B and also there is a new message in User B chat related to the task
5. Notice that User A still has the task message in their chat.

## Expected Result:
When task assignee is changed from User A to User B, we should either remove the task message from User A chat or update the message to indicate the assignee was changed

## Actual Result:
User A still has the task message even after unassigned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2d22e751-4bbc-4696-9b83-8c7b0b1f3092

https://github.com/Expensify/App/assets/93399543/1d6b9910-162a-4edb-a1e9-3a693ea88919

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687437127141249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e874db22226abcd6</li>
        <li>Upwork Job ID: 1674425523193294848</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-06-28 22:16
Handling tomorrow

**Comment by muttmuure** [comment] 2023-06-29 14:32
Context for `internal` and `external` labels here: https://expensify.slack.com/archives/C01GTK53T8Q/p1688046136288659

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 20:35
I think we don't need two C+ plus here, so I'm gonna unassign here!

**Comment by muttmuure** [comment] 2023-07-03 16:07
Upped the price

**Comment by thienlnam** [comment] 2023-07-03 17:39
This is not a bug - works as intended. This would technically be a feature request

**Comment by kmwamasali** [comment] 2023-07-04 07:27
@muttmuure @thienlnam 
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task message not removed from original assignee chat when a different assignee is set for the same task

### What is the root cause of that problem?
When generating the report action items there's no check for assignee, so the frontend displays all loaded tasks
https://github.com/Expensify/App/blob/917c344649d1fe8101de0f58a4554f3f5dee8666/src/pages/home/report/ReportActionItem.js#L251-L264

### What changes do you think we should make in order to solve the problem?
1. Adding a strikethrough on the task title when the task is reassigned and if desirable disable the checkbox so it can't be clicked anymore

### What alternative solutions did you explore? (Optional)
2. Display a tag(pill button) next to title that says reassigned

**Comment by thienlnam** [comment] 2023-07-06 18:40
> Hm, this feels unexpected to me. But maybe there is more context to leaving the task in place for past assignees

Past assignees can still access the task. If we were to remove the task message from the original assignee they would not have a way to access it

**Comment by kmwamasali** [comment] 2023-07-10 05:52
@muttmuure @thienlnam should we conclude that it's better to leave the message? In my proposal I suggest for ways to highlight the reassignment while keeping the task message. 
What other steps should we take for this proposal? Would posting a question in the group help with a conclusion

**Comment by muttmuure** [comment] 2023-07-10 14:29
I agree that this isn't a bug, and technically we would consider this polish for the tasks project

**Comment by kmwamasali** [comment] 2023-07-10 16:12
@muttmuure understood will await your approval to work on the PR

**Comment by thienlnam** [comment] 2023-07-10 17:12
IMO we should just close this unless there is a strong reason to change this

**Comment by muttmuure** [comment] 2023-07-10 17:31
agreed. TBH my preference is that we get some customers using the tool and then if it comes up again we can respond to that real usage. 

@kmwamasali we'll revisit at a later date. Thanks for your passion to work on this!

**Closed by muttmuure** 2023-07-10 17:31 UTC
Labels: External, Daily, Internal, Help Wanted, Bug
