### ISSUE TITLE
 Login - Onboarding modal not displayed for new account creation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35748] opened 2024-02-03 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applaustester+cknew@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account with either gmail or expensifail domain

## Expected Result:
Onboarding modal should be displayed for new account creation

## Actual Result:
Onboarding modal not displayed for new account creation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b5f2f62f-350a-47b2-ad99-d0f16c0df9b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-03 15:03
Production: 

![Bug6365501_1706921789551!PROD](https://github.com/Expensify/App/assets/78819774/d8e13d24-8947-4e9d-992b-3e7787ab39f2)

**Comment by bernhardoj** [comment] 2024-02-04 08:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The engagement modal for new user doesn't show.

### What is the root cause of that problem?
If the active route is not a bottom tab navigator, the modal won't show.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/PurposeForUsingExpensifyModal.tsx#L99-L104

This works fine for small screen, but for large screen, we have both the bottom tab navigator and central pane navigator (the report screen) on the stack and the central pane navigator is the focused (active) screen.

If we look at the [engagement modal PR](https://github.com/Expensify/App/pull/32154/files#diff-1aa13dcb8c006f23034cbb092ee730ed35feef4facb0637f78d8b546e25f4768), we cover both small and large screen cases by checking whether the active route is not a central pane navigator or a HOME.

### What changes do you think we should make in order to solve the problem?

Add another case to check whether the active route is not a central pane navigator.
```
if (currentRoute && NAVIGATORS.BOTTOM_TAB_NAVIGATOR !== currentRoute.name && currentRoute.name !== NAVIGATORS.CENTRAL_PANE_NAVIGATOR) {
    return;
}
```

We don't check for HOME because HOME is inside the bottom tab navigator.

### What alternative solutions did you explore? (Optional)
Even though the main solution is the approach we have been using before, one downside is that the engagement modal will still show on a report screen on a small-screen device which maybe we actually don't expect. We can obviously add a small screen check, but another way is to move back the engagement modal component (PurposeForUsingExpensifyModal) to SidebarScreen and then we only need to check whether the active route is HOME or not.
```
if (currentRoute && currentRoute.name !== SCREENS.HOME) {
    return;
}
```

Why do we check for HOME now? Because the sidebar screen is inside the bottom tab navigator and navigation.getState will get the nearest navigator state, in this case, the bottom tab navigator.

**Comment by shubham1206agra** [comment] 2024-02-05 06:04
Dupe of https://github.com/Expensify/App/issues/35663
cc @iwiznia @hayata-suenaga

**Comment by mountiny** [comment] 2024-02-05 12:39
@bernhardoj could you move your proposal over to https://github.com/Expensify/App/issues/35663 that issue came first

**Closed by mountiny** 2024-02-05 12:39 UTC
Labels: Engineering, Hourly
