### ISSUE TITLE
VBA - Connect Bank Account modal keeps opening until page refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38090] opened 2024-03-11 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/1971173
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User has completed Plaid flow VBA & Onfido (TR: https://expensify.testrail.io/index.php?/cases/view/1971173
)
1. On Connect bank account modal window, click 'Yes, let's chat'
2. Navigate to workspace settings > Bank account
3. Click anywhere outside the Connect bank account modal window.

## Expected Result:
Connect bank account modal window closes

## Actual Result:
Connect bank account modal window briefly closes and opens again, until user refresh the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/31c50af1-a208-4d19-a1cf-5cb3c1321bc5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-11 20:54
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-03-12 05:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The bank account page keeps reopening when closing it.

### What is the root cause of that problem?
When we press the Let's Chat button, it will navigate to the concierge chat, but the bank account page is still in the nav stack. When we revisit the bank account, it will be pushed to the top of the stack.

[RHP (bank account step), Concierge, RHP (bank account validation step)]

When we try to close the page, the 2nd bank account RHP will be unmounted and clear the bank account data.
https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L278-L283

This triggers the `useEffect` for the first RHP that compares the step from params and the step from bank account data Onyx.
https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L252
https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L316-L344

And because the onyx data is cleared, the navigation logic above is triggered (BankAccountStep !== ValidationStep), making it impossible to leave the page.

This was previously fixed in https://github.com/Expensify/App/issues/34456, but I guess the BA refactor raised this issue again (the component that was used before the refactor is now removed).

### What changes do you think we should make in order to solve the problem?

Dismiss the modal (RHP) before navigating to the concierge chat by passing `true` to the first param (`shouldDismissModal`).
https://github.com/Expensify/App/blob/b8590c966c7a7f7df8b6a1c8d8566cbab0fd572b/src/pages/ReimbursementAccount/ConnectBankAccount/components/FinishChatCard.tsx#L30

**Comment by kevinksullivan** [comment] 2024-03-15 22:41
checking on this

https://expensify.slack.com/archives/C01SKUP7QR0/p1710542480416309

**Comment by kevinksullivan** [comment] 2024-03-19 21:37
checking once more

https://expensify.slack.com/archives/C01SKUP7QR0/p1710884216422989

**Comment by kevinksullivan** [comment] 2024-03-19 22:00
moving to wave-collect for now, will update if that convo linked above takes a turn though.

**Comment by kevinksullivan** [comment] 2024-03-26 17:24
updating priority, no update.

**Comment by trjExpensify** [comment] 2024-04-03 18:54
Did you figure out if it was reproducible on a collect workspace editor?

**Comment by kevinksullivan** [comment] 2024-05-21 22:48
Sorry this one fell off. Trying to test with the testrail now and the passport photo throws an error from the testrail @lanitochka17 . Any ideas on getting around this? 

![image](https://github.com/Expensify/App/assets/22508290/50160343-8c0b-4626-8d0b-62db3bfbeaa0)

**Comment by kevinksullivan** [comment] 2024-05-21 23:04
alright, got through with my ID an was unable to reproduce.

**Closed by kevinksullivan** 2024-05-21 23:04 UTC
Labels: Monthly, Bug
