### ISSUE TITLE
[$500] Request money - User A can request money in the workspace expense room using URL, even though only User B should be able to request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27618] opened 2023-09-17 14:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account
2. Create a workspace and invite User B
3. Open the workspace room from User B
4. Navigate to the "Request money" section
5. Enter an amount and click "Next."
6. Copy the URL and click "Request..."
7. Return to User A's account
8. Open the workspace expense room where User B requested money
9. Send the copied URL and open it
10. Enter an amount and request it by clicking on "Request money"

## Expected Result:
 User A should not be able to request money using the URL in workspace expense room, as it is intended only for User B

## Actual Result:
User A can request money in the workspace expense room using URL, even though only User B should be able to request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f2bcbc43-24fd-47fa-83c2-34ca7e1fa62e

https://github.com/Expensify/App/assets/78819774/ef59b24e-a050-4b57-9c2c-e2923f366949

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694642540255229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193de23f043eea69d</li>
        <li>Upwork Job ID: 1703417313135792128</li>
        <li>Last Price Increase: 2023-10-08</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-09-17 14:45
Seems not a bug as user B can request it from the workspace report

**Comment by ayazhussain79** [comment] 2023-09-17 16:30
There are two expense rooms, one for User A and the other for User B. In User B's expense room, the "Request Money" option is not available for User A, although you can still request money using a URL

**Comment by zanyrenney** [comment] 2023-09-21 05:47
Not sure why I was assigned via `External` when there is already a Bug assignee: 
<img width="776" alt="2023-09-21_06-46-45" src="https://github.com/Expensify/App/assets/56830058/b175e10f-2fcc-411f-bf72-8f20f207fc15">

Unassigning as the later assignee, to remove the duplication of bug management!

**Comment by situchan** [comment] 2023-10-10 22:05
@dukenv0307 is your proposal still valid?

**Comment by JmillsExpensify** [comment] 2023-10-17 20:43
@situchan thoughts on next steps and the existing proposals?

**Comment by JmillsExpensify** [comment] 2023-10-17 20:43
Or should we keep this internal?

**Comment by situchan** [comment] 2023-10-17 20:44
No need to be internal yet. I will confirm today

**Comment by situchan** [comment] 2023-10-24 09:43
I think this was fixed in https://github.com/Expensify/App/issues/23755.
@dukenv0307 can you confirm? As you were the author of that PR.

**Comment by JmillsExpensify** [comment] 2023-10-24 22:34
Oh ok perfect! Ok so I'll issue payment for reporting and we're done here. 

 - Issue reporter: @ayazhussain79 $50

**Comment by JmillsExpensify** [comment] 2023-10-24 22:37
@ayazhussain79 I believe I've just sent you an offer in Upwork. Can you please accept.

**Comment by ayazhussain79** [comment] 2023-10-24 22:38
@JmillsExpensify offer accepted, Thank you

**Comment by JmillsExpensify** [comment] 2023-10-24 23:06
All paid out. Thanks!

**Closed by JmillsExpensify** 2023-10-24 23:06 UTC
Labels: Engineering, Daily, Internal, Bug
