### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] Billable - Unable to adjust billable toggle for split scan and toggle is always disabled after split

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44920] opened 2024-07-05 15:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4695791
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- "Re-bill expenses to clients" settings is set to "Default to billable" on Old Dot
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Split expense > Scan
4. Submit a split scan expense
5. While the receipt is scanning, click on the split preview
6. Click on the billable toggle
7. Enter the required info and split the expense with billable enabled
8. Click on the split preview

## Expected Result:
In Step 6, user should be able to toggle off and on the billable toggle
In Step 8, the split preview will show that billable is enabled because the expense is split with billable enabled

## Actual Result:
In Step 6, user is unable to toggle off and on the billable toggle
In Step 8, the split preview shows that billable is disabled when the expense is split with billable enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1603b040-da14-40ee-a337-94f5f1173cbb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01126e533e614fb9eb</li>
        <li>Upwork Job ID: 1810482612250493622</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103082578</li>
<li>nyomanjyotisa | Contributor | 103348168</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment] 2024-07-05 15:37
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-07-08 05:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 6, user is unable to toggle off and on the billable toggle
In Step 8, the split preview shows that billable is disabled when the expense is split with billable enabled

### What is the root cause of that problem?
1. We don't pass `onToggleBillable` to update the `billable` in draft transaction when we toggle billable in `SplitBillDetailsPage` as we do in `IOURequestStepConfirmation` [here](https://github.com/Expensify/App/blob/b0947e029faea27eebf348d125032a992d6181c3/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L571) 

https://github.com/Expensify/App/blob/b0947e029faea27eebf348d125032a992d6181c3/src/pages/iou/SplitBillDetailsPage.tsx#L124

2. We don't pass `billable` param to `CompleteSplitBill` API and then BE returns `billable` as `false` by default.
### What changes do you think we should make in order to solve the problem?
1. Pass `onToggleBillable` prop to `MoneyRequestConfirmationList` to update the `billable` of draft transaction

```
onToggleBillable={(billable) => {
    IOU.setDraftSplitTransaction(transaction?.transactionID ?? '-1', {billable})
}}
```

https://github.com/Expensify/App/blob/b0947e029faea27eebf348d125032a992d6181c3/src/pages/iou/SplitBillDetailsPage.tsx#L124

2. Get the billable [here](https://github.com/Expensify/App/blob/b0947e029faea27eebf348d125032a992d6181c3/src/libs/actions/IOU.ts#L4914) and pass it as parameter of `CompleteSplitBill` API [here](https://github.com/Expensify/App/blob/b0947e029faea27eebf348d125032a992d6181c3/src/libs/actions/IOU.ts#L4926). I tested and when we pass the correct `billable` param, BE returns `billable` correctly as the value that we passed in the API.

### What alternative solutions did you explore? (Optional)
NA

**Comment by mallenexpensify** [comment] 2024-07-09 01:15
I think I was able to reproduce. 

https://github.com/Expensify/App/assets/22508304/e9024685-fbff-42a8-8e26-fed5bb7edd61

<img width="848" alt="image" src="https://github.com/Expensify/App/assets/22508304/a8d67866-b0a2-4984-b6ac-4ac3058b068c">

@parasharrajat can you repro? If so, can you provide feedback and/or review the proposals above?  Thx

**Comment by NikkiWines** [comment] 2024-07-11 14:08
Thanks for the bump @parasharrajat. Since @nyomanjyotisa's initial proposal solved issue 1 and @nkdengineer's proposal solved issue 2, we should split the compensation between both users. 

As for who implements the solution 🤔 I guess I'd say it should be @nkdengineer as they posted the most complete solution overall. 

Does that sound fair? @nkdengineer what do you think?

**Comment by nkdengineer** [comment] 2024-07-11 14:39
@NikkiWines Thanks for your feedback. Based on the guidelines, the selected proposal should fix all issues in the OP. I suggest compensating 7:3 in this case since I spent more effort investigating the issue and raising the PR. What do you think?

**Comment by mallenexpensify** [comment] 2024-07-11 17:54
Thanks all, I'd like to:
1. Have @nkdengineer draft the PR, compensation will be $250
2. Compensate @nyomanjyotisa $125 for submitting the correct fix for 1/2 of the bug. 

It's rare we have two bugs combined into a single issue so let's consider this an edge case.

**Comment by nkdengineer** [comment] 2024-07-11 17:58
@mallenexpensify Thanks, I'm happy with that. @NikkiWines Can you please assign me here? And then I will raise the PR tomorrow morning.

**Comment by nkdengineer** [comment] 2024-07-12 04:49
@parasharrajat Have a problem with the latest main. Can't enter the amount input so I can't complete the split bill to test problem 2.


https://github.com/user-attachments/assets/0d74e73c-62b9-43ad-95ab-ed3efed41305

**Comment by nkdengineer** [comment] 2024-07-15 04:02
@parasharrajat The PR is [here](https://github.com/Expensify/App/pull/45319).

**Comment by mallenexpensify** [comment] 2024-07-26 22:48
Contributor: @nkdengineer  paid $250 via Upwork
Contributor+: @parasharrajat due $250 via NewDot  

@parasharrajat plz complete the BZ checklist above.

**Comment by mallenexpensify** [comment] 2024-07-31 22:01
@nyomanjyotisa apologies, I should have also assigned to you so that it'd help me not forget to pay. Can you please accept the job and reply here once you have?  https://www.upwork.com/jobs/~01126e533e614fb9eb

Test case
- https://github.com/Expensify/Expensify/issues/416877

**Comment by mallenexpensify** [comment] 2024-07-31 22:47
Thanks @nyomanjyotisa , you've been paid.  Payment confirmation comment has been updated above.

**Closed by mallenexpensify** 2024-07-31 22:47 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-03 19:12
$250 approved for @parasharrajat
