### ISSUE TITLE
[HOLD for payment 2023-10-31] Address - 'Hmm it's not here' page shows up when selecting a country

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30128] opened 2023-10-21 17:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Personal details > Address > Country
3. Select a country

## Expected Result:
Country is selected successfully

## Actual Result:
'Hmm it's not here' page shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/e173ce3b-c2fa-4eb4-a62a-aaa74b9b01e3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-10-21 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Address - 'Hmm it's not here' page shows up when selecting a country
### What is the root cause of that problem?
after select country we backTo 
```
Navigation.navigate(`${route.params.backTo}?country=${option.value}`);
```
the issue here is the url is not cirrect so the route.params.backTo is return undifined
the url has 2 "?"
http://localhost:8082/settings/profile/personal-details/address/country?country=US?backTo=%2Fsettings%2Fprofile%2Fpersonal-details%2Faddress

this because getBackToParam is start with "?" regardless the main url has "?" or not
https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/ROUTES.ts#L14-L16

### What changes do you think we should make in order to solve the problem?
we need to change getBackToParam to not start with "?" and when it used, use it this  `?${getBackToParam(backTo)}` or `&${getBackToParam(backTo)}`
```
function getBackToParam(backTo?: string): string {
    return backTo ? `backTo=${encodeURIComponent(backTo)}` : '';
}
```
### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-10-21 17:32
This is a regression from the PR https://github.com/Expensify/App/pull/29813

**Comment by thienlnam** [comment] 2023-10-22 00:10
Hmm I tried the revert of that PR but still running into a different problem when trying the reproduction steps
http://localhost:8082/settings/profile/personal-details/address

![Screenshot 2023-10-21 at 5 10 12 PM](https://github.com/Expensify/App/assets/30609178/2665867f-a41d-4eae-9aa3-300c76eec428)

**Comment by thienlnam** [comment] 2023-10-22 01:27
Ah nevermind, looks like it is fixed after NPM install - going with a straight revert here

**Comment by luacmartins** [comment] 2023-10-22 03:00
I think @ahmedGaber93's  solution with `getUrlWithBackToParam` looks good. I created a PR with it since we might CP this weekend to fix the issue before Money2020. We should compensate @ahmedGaber93 accordingly.

**Comment by mountiny** [comment] 2023-10-22 21:21
@JmillsExpensify What I have usually applied was the 25% rule so that would be $125 to @ahmedGaber93

**Comment by mountiny** [comment] 2023-10-22 21:38
Fixed in staging

**Comment by JmillsExpensify** [comment] 2023-10-24 22:55
@luacmartins Do we need any new regression tests for this one?

**Comment by JmillsExpensify** [comment] 2023-10-24 22:55
In the meantime, here's the payment summary: 

 - Contributor: @ahmedGaber93 $125

**Comment by JmillsExpensify** [comment] 2023-11-01 15:21
@luacmartins Quick check on the regression test. Do you think we need one for this case?

**Comment by luacmartins** [comment] 2023-11-01 16:57
No need for a regression test. Applause caught this during it already.

**Comment by luacmartins** [comment] 2023-11-06 16:49
Just missing payment here

**Comment by luacmartins** [comment] 2023-11-09 22:01
Same

**Comment by JmillsExpensify** [comment] 2023-11-15 16:04
Ok great, circling back for payment then.

**Comment by JmillsExpensify** [comment] 2023-11-24 18:21
@ahmedGaber93 Do you mind confirming that you haven't been paid for this issue? I'm unable to find a linked Upwork job, so I just want to be sure before creating another job.

**Comment by ahmedGaber93** [comment] 2023-11-24 18:31
@JmillsExpensify no, I haven't been paid for this issue.

**Comment by JmillsExpensify** [comment] 2023-11-24 18:54
Thanks I'll create an Upwork job now.

**Comment by JmillsExpensify** [comment] 2023-11-24 18:58
Mind applying here: https://www.upwork.com/jobs/~0172d8e78897a88014

**Comment by ahmedGaber93** [comment] 2023-11-24 19:11
@JmillsExpensify Applied.

**Comment by JmillsExpensify** [comment] 2023-11-24 19:14
Offer sent! Thank you

**Comment by JmillsExpensify** [comment] 2023-11-24 19:20
Offer paid via Upwork. Thanks everyone!

**Closed by JmillsExpensify** 2023-11-24 19:20 UTC
Labels: Engineering, Daily, Monthly, Awaiting Payment, Bug
