### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Search - Total amount for the report in Shared is -0.00 when it has only scanning expenses

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43990] opened 2024-06-19 12:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4609426
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Submit two scan expenses to the workspace chat.
4. While the scanning is ongoing, go to Search.
5. Go to Shared.

## Expected Result:
The total amount for the report in Shared will be 0.00.

## Actual Result:
The total amount for the report in Shared is -0.00.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e2ac101c-b7a1-4b32-926d-e134f343d980

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122d04513e0a42253</li>
        <li>Upwork Job ID: 1803626666039149098</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102824702</li>
<li>nkdengineer | Contributor | 102824703</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by izarutskaya** [comment] 2024-06-19 12:37
We think this issue might be related to the #collect project.

**Comment by mallenexpensify** [comment] 2024-06-20 03:12
@c3024 likely add `Help Wanted`, any thoughts before I do?

**Comment by nkdengineer** [comment] 2024-06-20 03:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The total amount for the report in Shared is -0.00.

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/SelectionList/Search/ReportListItem.tsx#L42, we always multiply with `-1` if it's an expense, even when the value is 0.

`-1 * 0` will be `-0`, so it's displayed as -0 in front-end.

### What changes do you think we should make in order to solve the problem?

Only multiply if `total` is not 0
```
let total = reportItem?.total ?? 0;

if (total) {
    total *= (reportItem?.type === CONST.REPORT.TYPE.EXPENSE ? -1 : 1);
}
```

After that `total` can be used in https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/SelectionList/Search/ReportListItem.tsx#L42
```
text={CurrencyUtils.convertToDisplayString(total, reportItem?.currency)}
```

This can be made an utility to ensure consistency in this logic.

### What alternative solutions did you explore? (Optional)
If value is -0, convert it to 0 inside `convertToDisplayString` or `convertToFrontendAmountAsInteger`

**Comment by nkdengineer** [comment] 2024-06-20 03:57
[Proposal updated](https://github.com/Expensify/App/issues/43990#issuecomment-2179757228) to add alternative solution

**Comment by iloveyourglasses** [comment] 2024-06-21 01:29
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
The total amount for the report in Shared is -0.00.

### What is the root cause of that problem?
In

https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/SelectionList/Search/ReportListItem.tsx#L42

indeed as [nkdengineer](https://github.com/nkdengineer) stated you always multiply with -1 if it's an expense, even when the value is 0.

-1 * 0 will be -0, so it's displayed as -0 in front-end.

### What changes do you think we should make in order to solve the problem?
add 0 to the overall amount, the issue is hardcoded in javascript itself !!!

the line 42 will then be

 text={CurrencyUtils.convertToDisplayString((reportItem?.type === CONST.REPORT.TYPE.EXPENSE ? -1 : 1) * (reportItem?.total ?? 0) **+ 0**, reportItem?.currency)} 

This can be made an utility to ensure consistency in this logic.

### What alternative solutions did you explore? (Optional)
Even better avoid such mutiplication by wrting line 42 as

text={(reportItem?.type === CONST.REPORT.TYPE.EXPENSE ? "-" : "") + CurrencyUtils.convertToDisplayString((reportItem?.total ?? 0), reportItem?.currency)}

**Comment by iloveyourglasses** [comment] 2024-06-21 01:34
Contributor details
Your Expensify account email: rnel2@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0182b95dfd9db2cbea

**Comment by c3024** [comment] 2024-06-21 05:44
@nkdengineer 's [proposal here](https://github.com/Expensify/App/issues/43990#issuecomment-2179757228). I found this use case at only one place so the primary solution looks fine to me.

🎀 👀 🎀 C+ Reviewed

**Comment by nkdengineer** [comment] 2024-06-24 03:44
@c3024 this [PR](https://github.com/Expensify/App/pull/44227) is ready for review

**Comment by mallenexpensify** [comment] 2024-07-11 01:16
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @c3024 paid $250 via Upwork

@c3024 , please fill out the BZ checklist above.  Thx

**Comment by c3024** [comment] 2024-07-11 06:29
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #42932
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/nkdengineer/App/commit/642baa4314fe5bb927f14054ab89aa3824dae5de#r144114057
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this is too specific a case and the bug could not have been identified earlier.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test proposal
1. Submit two scan expenses in a workspace chat.
2. While the scanning is ongoing, press on `Search` on Bottom Tab Bar.
3. Press on `Shared`.
4. Verify that the `Total` amount for this report (workspace chat of step 1) in `Shared` is displayed as 0.00.

**Comment by arosiclair** [comment] 2024-07-18 18:11
@mallenexpensify is this done?

**Comment by mallenexpensify** [comment] 2024-07-20 00:02
> is this done?

it is now! 
- https://github.com/Expensify/Expensify/issues/414087

**Closed by mallenexpensify** 2024-07-20 00:02 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
