### ISSUE TITLE
[HOLD for payment 2023-06-30] [$1000] mWeb - Chat - Using autfill for a protected PDF file sends email address to conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19721] opened 2023-05-27 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat>add attachment
4. Select password protected PDF file
5. Press enter password and use autofill
6. Press send

## Expected Result:
Only protected PDF file is displayed in the conversation.

## Actual Result:
When entering a password for a protected PDF file in conversation, if you use autofill, the email address is displayed in the conversation.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/67b4b7afe5b78bf761097c28c3e0a1b2d351ef55a496b57d093f73c937000a5e

https://platform.applause.com/services/links/v1/external/9b36d3bf8af506238044e444a44afad37eadff038b8f5776ffbf0c844fa8569a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a9f8a7d73f75789</li>
        <li>Upwork Job ID: 1665907721923502080</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-05-27 22:11
Hi @kbecciv, a few parts of the reproduction steps are unclear to me and I am not able to reproduce. Can you please clarify a few things for me?

1. Did you test this on other platforms and find that it's only happening on iOS Safari?
2. To auto-fill, did you save the password in the browser first? It's not clear from the description or video how you made the auto-fill happen.

**Comment by kbecciv** [comment] 2023-05-29 14:44
Hello @sakluger 
1.Yes, this issue  only happening on iOS Safari, I can reproduced in my phone as well.
2. Here is the steps how to set autofill password in the iPhone.
a. On your iPhone or iPad, open your device settings.
b. Select Passwords.
c. Follow the prompts to unlock your device.
d. Select Password Options.
e. Turn on AutoFill Passwords.
Able to reproduce it.
![IMG_6284](https://github.com/Expensify/App/assets/93399543/1321bc3f-f856-4a08-9225-4d03ab1f8352)

**Comment by sakluger** [comment] 2023-05-30 20:44
No responses yet in Slack.

**Comment by sakluger** [comment] 2023-06-01 17:35
Still no responses, reposted in #expensify-open-source

**Comment by sakluger** [comment] 2023-06-01 18:40
Okay, we should fix. I still need to reproduce this one - I don't use the keychain on my iPhone so I will need to do some more setup to test this out.

**Comment by sakluger** [comment] 2023-06-02 16:45
I don't know what's going on, but I can't log into my test account right now (it won't send me a magic link) and so I can't test this.

**Comment by sakluger** [comment] 2023-06-02 22:10
Sorry but I wasn't able to reproduce this and I'm OOO next week, going to reassign this to another BZ member.

**Comment by sophiepintoraetz** [comment] 2023-06-06 02:08
I'm able to reproduce! Discussing[ here](https://expensify.slack.com/archives/C01SKUP7QR0/p1686016929142759) whether it's worth fixing as you have to manually add the password to the keychain.

https://github.com/Expensify/App/assets/42940078/d4477afe-a0f0-48ab-968a-cff518778dc4

**Comment by sophiepintoraetz** [comment] 2023-06-07 00:23
@sakluger - keeping you assigned in case this runs until you come back. The best practise is to keep yourself assigned to issues if you think they're going to continue until your return!

**Comment by sophiepintoraetz** [comment] 2023-06-08 00:21
@Julesssss - how long should we leave this open before dropping into either Callstack ([#expensify-callstack](https://app.slack.com/client/T03SC9DTT/C03UK30EA1Z)) or Software Mansion ([#expensify-swm](https://app.slack.com/client/T03SC9DTT/C04878MDF34)) channels?

**Comment by Julesssss** [comment] 2023-06-08 08:36
Lets leave it another week

**Comment by s77rt** [comment] 2023-06-11 20:26
Still looking for proposals...

**Comment by sophiepintoraetz** [comment] 2023-06-12 02:12
All right, I'm unassigning myself as I'm going OOO - it is a little earlier than when Sasha is due back but at the rate we're going, I doubt any payment will be needed by the 14th. 
@sakluger - if there are still no proposals by the time you get back, Jules and I discussed [dropping this](https://github.com/Expensify/App/issues/19721#issuecomment-1581692048) into the agency rooms for some help.

**Comment by Julesssss** [comment] 2023-06-12 07:44
Hi @kbecciv, is this only occuring on iOS, or was that the only platform that was tested?

**Comment by rezkiy37** [comment] 2023-06-14 11:03
Hi, I'm Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by sakluger** [comment] 2023-06-14 17:06
Thanks @rezkiy37! Happy to have you work on this one.

**Comment by Julesssss** [comment] 2023-06-15 07:55
Hey Michael, let me know if you have any questions!

**Comment by rezkiy37** [comment] 2023-06-16 16:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When **Safari** suggests to autofill a password of some protected _PDF_ file, **Safari** sets **username** value to the main input of a chat. The app sends the **username** only when the users have tapped “Send”, not before.

### What is the root cause of that problem?
The app already use `autoComplete="off"` for the `RNTextInput` of `Composer` (the main chat input). However, [Safari ignores the `autocomplete="off"` value for **username**, **email** and **password** fields](https://caniuse.com/input-autocomplete-onoff). The browser looks for the closest input to set **username**, this way the closest input is from `Composer`. Because, `PDFView` is a modal, the **DOM tree** still have all chat components.

### What changes do you think we should make in order to solve the problem?
Because, **Safari** ignores `autoComplete="off"`, `editable=false`, `readOnly=true`, the app should have some input that should receive the **username** value.
My idea is to add a hidden input only for **Safari** in `PDFPasswordForm`. Because, this component requests autofill, so this component should handle **username** and **password** values. We don’t mess with the main screen and we keep that “bug” isolated.

1. Create a component - `HiddenInputComponent` ⬇️
2.  `index.js` - all other platform should not get any additional nodes:
```js
  function HiddenInputComponent () { return null; }
```
3. `index.web.js` - only for the web app. Via `Browser.getBrowser() === CONST.BROWSER.SAFARI` condition the app renders a bare `TextInput` with `autoComplete="username"` only _(it helps Safari to find this input)_. The input should be wrapped in `View` _(because in web there are many divs around the input itself)_ with `styles.dNone` to be invisible for users via `display: none`:
```js
function HiddenInputComponent() {
    return Browser.getBrowser() === CONST.BROWSER.SAFARI ? (
        <View style={styles.dNone}>
            <TextInput autoComplete="username" />
        </View>
    ) : null;
}
```

4. Use this component in `PDFPasswordForm` near to the already existed `TextInput`.

### What alternative solutions did you explore? 
There are a couple of other solutions:

#### The first one is to use another callback of `TextInput`:
1. `TextInput` of **RN** has 2 callbacks: [onChange](https://reactnative.dev/docs/textinput#onchange) and [onChangeText](https://reactnative.dev/docs/textinput#onchangetext). 
2. Basically, the app use `onChangeText` because it provides new value only. 
3. `onChange` provides `nativeEvent` where there is `target` and for browsers there is a property [isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted).
    1. When `true` - the event was generated by a user action. Generally, it means pasting or typing
    2. When `false` - the event was created or modified by a script or dispatched. It means autofill or other non-user events.
4. The app could use `onChange` instead of `onChangeText` for `Composer`. There is `text` in `nativeEvent`. However, there is a warning (check below).
![Screenshot 2023-06-16 at 10 37 09](https://github.com/Expensify/App/assets/57314631/0534b476-da7e-4026-a053-fe3d8fff6dfe)

5. Inside `Composer` I can handle `onChange` and take `isTrusted` and `text`. When `isTrusted === true` , I will call `onChangeText` , when `false` - **do nothing**.
6. For parent components no changes on props or something else. I improve `Composer` only. 
7. `TextInput` itself does not have `onChangeText` callback anymore, only `onChange` is being used.

#### The second one is to unmount `RNTextInput` in `Composer` via **Onyx**
1. Add a key - `IS_PDF_PASSWORD_MODAL_OPEN` to `src/ONYXKEYS.js`.
2. Create a file - `PDFPasswordModalActions` in `src/libs/actions` . This file contains connection to **Onyx** and 2 functions: `showPDFPasswordModal` and `hidePDFPasswordModal` .
3. Mount or unmount `RNTextInput` in `Composer` based on `isPDFPasswordModalOpen` property from `withOnyx` hoc.
4. In `PDFView` remove `shouldRequestPassword` from **state** to use the variable from `withOnyx` only.
5. Control show/hide **state** of `PDFPasswordForm` via the functions.

**Comment by s77rt** [comment] 2023-06-16 22:40
@rezkiy37 Thanks for the proposal. Your RCA is correct. The proposed solutions make sense but since we are dealing with a browser limitation and we will have to apply some kind of a hack let's make the changes as minimal as possible. What about:
```js
autoComplete={isSafari ? "username" : "off"}
```

Since Safari will ignore the `autoComplete=off` we can just set it to `autoComplete=username` this should _trick_ the browser not to fill the username in the Composer and still fill the password correctly.

**Comment by s77rt** [comment] 2023-06-18 23:12
Working on it, Melvin

**Comment by Julesssss** [comment] 2023-06-19 07:56
Hi @rezkiy37, thanks for the proposal. Before we move forward, what do you think of @s77rt's suggestion?

**Comment by rezkiy37** [comment] 2023-06-19 08:57
> Hi @rezkiy37, thanks for the proposal. Before we move forward, what do you think of @s77rt's suggestion?

I will try this solution and let you know today 🙂

**Comment by rezkiy37** [comment] 2023-06-19 12:40
It works!
I've set `autoComplete="username"` instead of `autoComplete="off"` for `TextInput` in `PDFPasswordForm`. 
I confirm that the suggestion form @s77rt works perfectly! 

#### Upload a secured PDF file
https://github.com/Expensify/App/assets/57314631/3b50eada-fa05-4e2b-a398-31f2dd0e1e03

#### Preview a secured PDF file
https://github.com/Expensify/App/assets/57314631/f1bdd03e-8b9a-4a39-b784-a6eb273da811

**Comment by rezkiy37** [comment] 2023-06-19 15:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When **Safari** suggests to autofill a password of some protected _PDF_ file, **Safari** sets **username** value to the main input of a chat. The app sends the **username** only when the users have tapped “Send”, not before.

### What is the root cause of that problem?
The app already use `autoComplete="off"` for the `RNTextInput` of `Composer` (the main chat input). However, [Safari ignores the `autocomplete="off"` value for **username**, **email** and **password** fields](https://caniuse.com/input-autocomplete-onoff). The browser looks for the closest input to set **username**, this way the closest input is from `Composer`. Because, `PDFView` is a modal, the **DOM tree** still have all chat components.

### What changes do you think we should make in order to solve the problem?
There is a workaround to bypass **Safari**'s odd behaviour.
Set `autoComplete=username` instead of `autoComplete=off` for **Safari** only, via `Browser.getBrowser() === CONST.BROWSER.SAFARI` in `TextInput` of `PDFPasswordForm`. This tricks the browser not to fill the username somewhere else and still fill the password correctly.
Also, this component requests autofill, so this component should handle **username** and **password** values. We don’t mess with the main screen and we keep that “bug” isolated.

#### Upload a secured PDF file
https://github.com/Expensify/App/assets/57314631/3b50eada-fa05-4e2b-a398-31f2dd0e1e03

#### Preview a secured PDF file
https://github.com/Expensify/App/assets/57314631/f1bdd03e-8b9a-4a39-b784-a6eb273da811

**Comment by s77rt** [comment] 2023-06-19 15:58
@rezkiy37 Thanks for the update. This looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @Julesssss

**Comment by Julesssss** [comment] 2023-06-20 07:50
> Triggered auto assignment to @PauloGasparSv

What

**Comment by sakluger** [comment] 2023-06-21 20:21
Sent an Upwork offer to @s77rt so we're ready to go once everything is done.

**Comment by s77rt** [comment] 2023-06-24 19:14
- The PR that introduced the bug has been identified: n/a. This is a browser limitation (by design)
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: I doubt we have much to discuss since this is a browser limitation and more like an edge case
- Determine if we should create a regression test for this bug: I don't feel this is required for this case

**Comment by sakluger** [comment] 2023-07-01 01:21
All paid out, thanks everyone!

**Closed by sakluger** 2023-07-01 01:21 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
