### ISSUE TITLE
Expensify Card - Card details change briefly when card details RHP is refreshed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#53574] opened 2024-12-04 16:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.71-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Expensify Card feature is enabled.
- User has assigned themselves a virtual card.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.
3. Click on the virtual card.
4. Refresh the page.

## Expected Result:
Expensify Card details will not change when card details RHP is refreshed.

## Actual Result:
- Virtual badge changes to Physical briefly.
- Cardholder name is shown as Hidden briefly.
- Remaining limit and card limit show 0.00 briefly.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1d298dfd-1389-40db-a77c-b051b5267d0e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thelullabyy** [comment] 2024-12-04 16:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify Card - Card details change briefly when card details RHP is refreshed

### What is the root cause of that problem?
When reloading, the ONYX data isn't loaded It caused the default data is displayed in a moment

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/ccc5efdbccbc2b19f22431ab98df16f01b7d744e/src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx#L51

```
const [cardsList, cardsListMetaData] = useOnyx(`${ONYXKEYS.COLLECTION.WORKSPACE_CARDS_LIST}${workspaceAccountID}_${CONST.EXPENSIFY_CARD.BANK}`); 

...


If (isLoadingOnyxValue(cardsListMetaData)) {
  return <FullScreenLoadingIndicator />
}
```


Also need to apply to company card detail page

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment] 2024-12-05 03:19
@mountiny This seems like a lack of when implementing this feature. Could I take over this one?

**Comment by mountiny** [comment] 2024-12-06 16:13
I dont think this is worth getting fixed now

**Closed by mountiny** 2024-12-06 16:13 UTC
Labels: Daily, Bug
