### ISSUE TITLE
[$500] Workspace - If user log in and immediately go offline, distance rate always appears as 0

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33045] opened 2023-12-14 09:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/32773

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Log out and kill the app.
2. Open New Expensify app again and log in.
3. Immediately after login, disable the internet connection.
4. Go to Settings > Workspaces > Select any workspace > Reimbursement > Distance rate.

## Expected Result:
Distance rate should appear as if it were loading or waiting for internet connection.

## Actual Result:
Distance rate appears as 0.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/109f66d5-4ae0-4aef-a437-08d160e42210

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181b95ca0d40733e5</li>
        <li>Upwork Job ID: 1735233897587527680</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-12-15 15:46
Assigned to Wave 8. cc @zanyrenney as we'll need to figure out what the ideal behavior is here.

**Comment by alitoshmatov** [comment] 2023-12-19 16:24
> Assigned to Wave 8. cc @zanyrenney as we'll need to figure out what the ideal behavior is here.

@puneetlath Should I proceed with reviewing proposal or are we waiting for confirmation?

**Comment by puneetlath** [comment] 2023-12-19 20:00
I've removed the help wanted label for now. We can re-add it once the behavior has been clarified.

**Comment by alitoshmatov** [comment] 2024-01-02 10:30
Waiting for confirmation on expected behavior here.

**Comment by iwiznia** [comment] 2024-01-26 19:38
@joekaufmanexpensify @puneetlath why is this internal? Seems like we paused reviewing proposals [here](https://github.com/Expensify/App/issues/33045#issuecomment-1863397109) but never unpaused them. Did you figure out what the correct behavior is? And why would it not be to show the loading indicator?


(removing `internal` for now, since this can be worked on externally)

**Comment by joekaufmanexpensify** [comment] 2024-01-29 14:34
Going to take a closer look at this one today.

**Comment by joekaufmanexpensify** [comment] 2024-01-30 15:20
Posted [discussion](https://expensify.slack.com/archives/C036QM0SLJK/p1706627962148699) on expected behavior

**Comment by joekaufmanexpensify** [comment] 2024-01-30 18:57
We discussed in the above thread and decided to close this bug report. We are working on refactoring this part of the product, and this issue will be addressed then.

**Closed by joekaufmanexpensify** 2024-01-30 18:57 UTC
Labels: Engineering, Daily, Bug
