### ISSUE TITLE
[$500] Status - Selected emojis in status page's emoji picker don't add to frequently used section

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31802] opened 2023-11-23 21:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Go to staging.expensify
2. Navigate to Settings > Profile > Status > Status Detail
3, Click on the down chevron icon to open the emoji picker
4, Select an emoji, then go to the top of the emoji picker section and observe that the emoji is not added to the frequently used section

## Expected Result:
When clicking on emojis, they should be added to the frequently used section, similar to the behavior in the composer emoji picker

## Actual Result:
Selected emojis are not added to the frequently used section, unlike the behavior in the composer emoji picker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/26a9899b-2288-458e-9103-c3846b4c9264

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca6c37a3f4b46846</li>
        <li>Upwork Job ID: 1727805546590011392</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-24 01:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Status - Selected emojis in status page's emoji picker don't add to frequently used section

### What is the root cause of that problem?
We don't call `User.updateFrequentlyUsedEmojis` in Status Page

### What changes do you think we should make in order to solve the problem?
We are handling `updateFrequentlyUsedEmojis` case by case so It is easy to miss updating frequently used emojis when new emoji picker is created. I suggest we should move logic `updateFrequentlyUsedEmojis` into EmojiPicker to dry code
In here
https://github.com/Expensify/App/blob/f52c59d55be2d6d2775623d92c3043bd6d42cc0f/src/components/EmojiPicker/EmojiPicker.js#L48
We should add a new prop called `shouldUpdateFrequentlyUsedEmojis`. When this prop is true we will call `User.updateFrequentlyUsedEmojis` function 

Because currently, we are handling `updateFrequentlyUsedEmojis` case by case in these places: AddReactionBubble, MiniQuickEmojiReactions, EmojiPickerButtonDropdown (Status Page, don't handle updateFrequentlyUsedEmojis), EmojiPickerButton (Main composer and Edit Composer). With my approach, we need to remove logic `updateFrequentlyUsedEmojis` in AddReactionBubble, MiniQuickEmojiReactions. In EmojiPickerButton, we will pass `shouldUpdateFrequentlyUsedEmojis` is false, because here, we have another logic to handle `updateFrequentlyUsedEmojis` to cover many other cases like pasting text that contains emoji, selecting emoji from the suggestion,...

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-12-01 19:03
How are we looking here @0xmiroslav?

**Comment by bfitzexpensify** [comment] 2023-12-05 19:22
Bump on this one @0xmiroslav

**Comment by bfitzexpensify** [comment] 2023-12-11 19:32
How are things looking here @0xmiroslav?

**Comment by bfitzexpensify** [comment] 2023-12-14 14:36
Bump on this one again @0xmiroslav, thank you!

**Comment by bfitzexpensify** [comment] 2023-12-17 14:34
I've re-reviewed the problem here, and I don't think it fits neatly into any of the waves or VIP projects we have. I'm going to close this out for focus.

**Closed by bfitzexpensify** 2023-12-17 14:34 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
