### ISSUE TITLE
[HOLD for payment 2023-10-10] [$1000] No activity yet appears in task item of search RHN.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26679] opened 2023-09-04 15:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign a task.
2. Click on Mark as done.
3. Send a message.
4. Delete the message.
5. Open search RHN by pressing CRTL+K.
6. Observe the created task item in search RHN.
## Expected Result: 
No activity yet appears in task item of search RHN.
## Actual Result: 
No activity yet should not appear.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/176768c0-158e-4bfc-88f1-8ae7098977ef

https://github.com/Expensify/App/assets/43996225/334caa94-18a1-4cc1-964f-80ef05e9d162

**Expensify/Expensify Issue URL:**
**Issue reported by:** @oleksandr-pantsyr
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692977375401449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dac65c2c994b81e0</li>
        <li>Upwork Job ID: 1699721930034528256</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 26875557</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by StevenKKC** [comment] 2023-09-04 15:53
## Proposal

### Please state again the problem we are trying to solve in this issue.
No activity yet appears in task item of search RHN.

### What is the cause of this issue?
Task report's subtitle in LHN is generated as below.
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/libs/SidebarUtils.js#L305-L316
And on search page, task report's subtitle is generated as below.
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/libs/OptionsListUtils.js#L513
As you can see, we set proper subtitle in LHN, but we simply set `lastMessageText` on search page.
So `No activity yet` is displayed on search page.
### What changes do you think we should make to solve the problem?
We should set proper subtitle on search page just like in LHN.

### What alternative solutions have you investigated? (Optional)
None.

**Comment by bfitzexpensify** [comment] 2023-09-07 09:50
Reproduced, sending this external

**Comment by DylanDylann** [comment] 2023-09-07 10:10
<img width="1440" alt="Screenshot 2023-09-07 at 17 09 45" src="https://github.com/Expensify/App/assets/141406735/29895397-355b-4045-8c9a-2f9d936f941e">


The BE return lastMessagetext is ''  after deleting a message. We should fix it in BE

**Comment by Santhosh-Sellavel** [comment] 2023-09-07 17:04
@thienlnam 
Is this valid bug?
Your thoughts seems like backend?

**Comment by Santhosh-Sellavel** [comment] 2023-09-07 17:05
I am unassigning due to low bandwidth, if C+ assistance required assign a new C+ by reapplying `External` label

cc: @bfitzexpensify

**Comment by thienlnam** [comment] 2023-09-11 01:51
Hmm yeah looks like a BE update is needed for this specific scenario

**Comment by bfitzexpensify** [comment] 2023-09-11 11:19
OK, adding the engineering label in that case

**Comment by Gonals** [comment] 2023-09-12 03:28
Oh, nice catch! Yeah, this looks like a Backend change

**Comment by Gonals** [comment] 2023-09-12 04:50
Nope! Backend is working correctly (and the search element eventually updates to the correct message), and we are optimistically setting it to the correct value too. The issue is that we are not telling the search option that they need to update the element. Back to external!

**Comment by bfitzexpensify** [comment] 2023-09-14 09:19
Awaiting proposals

**Comment by bfitzexpensify** [comment] 2023-09-15 11:32
This has only been external for 3 days, will wait until mid-next week before considering a change to the bounty here

**Comment by Gonals** [comment] 2023-09-18 09:27
@bfitzexpensify said mid-week, Melvin!

**Comment by bfitzexpensify** [comment] 2023-09-20 10:01
No proposals after a week, I've doubled the bounty on this one

**Comment by zukilover** [comment] 2023-09-20 10:55
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
No activity yet appears in task item of search RHN

### What is the root cause of that problem?
In case of a report comment deletion, the report last action will only be shown in RHN if it is a pending remove action:
https://github.com/Expensify/App/blob/4c207ec07ce4d0b3ca3cc4a6f90b02524b4b440f/src/libs/OptionsListUtils.js#L403-L410

### What changes do you think we should make in order to solve the problem?
Add another condition to accommodate report comment deletion (without pending moderation) as well, .e.g.:
```
    if (ReportActionUtils.isPendingRemove(lastNonWhisper) || ReportActionUtils.isDeletedAction(lastNonWhisper)) {
            const latestVisibleAction =
                _.find(
                    allSortedReportActions[report.reportID],
                    (action) => ReportActionUtils.shouldReportActionBeVisibleAsLastAction(action) && !ReportActionUtils.isCreatedAction(action),
                ) || {};
            lastMessageTextFromReport = lodashGet(latestVisibleAction, 'message[0].text', '');
        }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bfitzexpensify** [comment] 2023-09-22 10:09
Couple of proposals ready for review @rushatgabhane

**Comment by bfitzexpensify** [comment] 2023-09-25 13:14
Friendly bump @rushatgabhane

**Comment by situchan** [comment] 2023-09-26 05:51
@oleksandr-pantsyr you need to submit proposal on upwork for the first issue. This is one time process.
From next issues you're getting assigned, Melvin will send upwork offer automatically.

**Comment by situchan** [comment] 2023-09-26 06:17
@oleksandr-pantsyr as I said, automatic offer is from next issues. For this one, BZ member (@bfitzexpensify) will hire you manually.

**Comment by rojiphil** [comment] 2023-09-26 06:21
> @rojiphil let's do this! lemme know when you can raise a PR

@rushatgabhane Working on this now. PR should be ready in the next 3-4 hours.

**Comment by rojiphil** [comment] 2023-09-26 10:32
@rushatgabhane [PR](https://github.com/Expensify/App/pull/28248) is ready for review. Kindly review.

**Comment by bfitzexpensify** [comment] 2023-10-03 18:39
Switching this to daily so I'm aware of it and action it on 10/10

**Comment by bfitzexpensify** [comment] 2023-10-09 22:41
Payment due tomorrow

**Comment by rojiphil** [comment] 2023-10-10 08:24
> Payment due tomorrow

@bfitzexpensify @rushatgabhane 
Wanted to check if this qualifies for bonus payment as, I think, the issue got fixed before 3 days.
It was just that the final approval and merger from internal team member took some extra time. 
What are your thoughts?

Here are the timeline details that I could gather:
Work Started: Sept. 26, 8:47 AM, GMT+5:30 [link](https://github.com/Expensify/App/issues/26679#issuecomment-1734763590)
Work Completed: Sept. 28, 1:41  PM, GMT+5:30 [link](https://github.com/Expensify/App/pull/28248#issuecomment-1738681130)
Time Taken: Approximately 2 days 5 hours.

**Comment by bfitzexpensify** [comment] 2023-10-10 21:34
Agreed @rojiphil, I think this qualifies for the #urgency bonus 

Payment summary:

Reporter: $50 for @oleksandr-pantsyr offer sent via Upwork
Contributor: $1500 for @rojiphil paid via Upwork ✅ 
C+: $1500 for @rushatgabhane to be paid via manual request

**Comment by rojiphil** [comment] 2023-10-11 01:37
Thanks @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2023-10-13 23:12
Upwork payments complete, a reminder to complete the BZ checklist when you get a chance @rushatgabhane - thank you!

**Comment by Gonals** [comment] 2023-10-17 09:48
Quick ping @rushatgabhane

**Comment by JmillsExpensify** [comment] 2023-10-18 18:52
$1,500 payment approved for @rushatgabhane based on BZ summary.

**Comment by bfitzexpensify** [comment] 2023-10-20 18:21
Friendly bump on that BZ checklist @rushatgabhane - thank you!

**Comment by bfitzexpensify** [comment] 2023-10-24 22:47
Another bump on the checklist @rushatgabhane - thanks!

**Comment by bfitzexpensify** [comment] 2023-10-27 16:39
Reminder on the BZ checklist @rushatgabhane

**Comment by bfitzexpensify** [comment] 2023-10-31 18:39
@rushatgabhane can you please complete this checklist so we can close this issue out?

**Comment by bfitzexpensify** [comment] 2023-11-07 13:26
Just waiting on BZ checklist here, Melv

**Comment by bfitzexpensify** [comment] 2023-11-07 14:16
Just waiting on BZ checklist here, Melv

**Comment by rushatgabhane** [comment] 2023-11-17 08:43
@bfitzexpensify updated the checklist https://github.com/Expensify/App/issues/26679#issuecomment-1767180621

**Comment by bfitzexpensify** [comment] 2023-11-17 20:12
Thanks @rushatgabhane! Created a regression test update. We're all done here, thanks everyone

**Closed by bfitzexpensify** 2023-11-17 20:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
