### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Redesign 2FA input prompt to allow recovery codes input

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#22335] opened 2023-07-06 10:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Coming from this customer's issue https://github.com/Expensify/Expensify/issues/295936

## Action Performed:
Break down in numbered steps
1. Enable 2FA in Newdot
2. Download recovery codes
3. Assuming one loses access to authenticator app

## Expected Result:
Describe what you think should've happened
User should be able to login by entering their recovery codes

## Actual Result:
Describe what actually happened
User is unable to enter recovery codes.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Signin into olddot, renable 2FA and then come to newdot.
Confusing from user's perspective

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

https://github.com/Expensify/App/assets/32012005/f57679f6-9e2c-40cc-b4bd-881bb8dae0a0

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2527e617e6edb31</li>
        <li>Upwork Job ID: 1678281063937363968</li>
        2023-07-17<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25671030</li>
<li>alitoshmatov | Contributor | 25671031</li>
</ul></li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment] 2023-07-06 10:50
@shawnborton I think we can use a simple text input we have for login, right?

**Comment by shawnborton** [comment] 2023-07-06 12:24
Exactly, we already have a simple text input component we could use.

**Comment by laurenreidexpensify** [comment] 2023-07-07 08:19
@MonilBhavsar anything else required here before or can I add `external`?

**Comment by MonilBhavsar** [comment] 2023-07-10 05:37
Yes, we can move ahead 👍

**Comment by Vishrut19** [comment] 2023-07-10 06:24
Is this issue already assigned to someone ?

**Comment by alitoshmatov** [comment] 2023-07-10 06:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Redesign 2FA input prompt to allow recovery codes input
### What is the root cause of that problem?
This is feature request
### What changes do you think we should make in order to solve the problem?
We can add checkbox or text link here saying like `Use recovery code` and when pressed we switch to normal text input from magic code input
https://github.com/Expensify/App/blob/c51349b124f93a42e237ac5403ee900030fcff34/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L244-L259

### What alternative solutions did you explore? (Optional)

**Comment by MonilBhavsar** [comment] 2023-07-10 06:36
> Is this issue already assigned to someone ?
Not yet!

**Comment by Vishrut19** [comment] 2023-07-10 06:39
> > Is this issue already assigned to someone ?
> 
> Not yet!

okay thanks. So, I can put up my proposal right?

**Comment by MonilBhavsar** [comment] 2023-07-10 07:36
@alitoshmatov thanks for the proposal!
I like switching between the inputs, as users won't be required to change their keyboard on mobile to enter numeric 2FA code(for most of the times).


> I am assuming the request used here also works with recovery codes, but if we can apply any changes if needed.

Yes

And, recovery code has 8 characters, So I think we can also update the length check.
Overall, I like this compared to a common input to allow both 2FA and recovery codes. @shawnborton curious for your thoughts. May be we can also discuss in #product.

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:36
Will check on the proposal in the morning

**Comment by abdulrahuman5196** [comment] 2023-07-15 11:44
@MonilBhavsar / @shawnborton  we need guidance on the design for this issue.

**Comment by shawnborton** [comment] 2023-07-17 13:58
What is the difference between this issue and [this one here](https://github.com/Expensify/App/issues/21708)? cc @marcaaron 

As for the linked proposal, that would work for me but we could also just use a standard text input and not need to toggle between 2FA and recovery.

**Comment by MonilBhavsar** [comment] 2023-07-17 14:22
Considering user's perspective and mobile first app, I like switching inputs, as most of the times, users will enter 6 digit 2FA code from the authenticator app, and for normal input that might require user to change to numeric keypad on mobile devices.

**Comment by shawnborton** [comment] 2023-07-18 00:26
Okay that's fair, let's go with your recommendation then.

**Comment by MonilBhavsar** [comment] 2023-07-19 10:08
Thanks Shawn for the thought! @abdulrahuman5196 we're good to check the proposal now

**Comment by abdulrahuman5196** [comment] 2023-07-20 12:53
I also like the idea of switching inputs. But we have to watch out for focus switches and clearing inputs on switching.

Since we are already aligned on the switching input case and as its a new feature implementation, @alitoshmatov 's proposal here https://github.com/Expensify/App/issues/22335#issuecomment-1628319424 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by MonilBhavsar** [comment] 2023-07-20 13:37
Thanks!
> But we have to watch out for focus switches and clearing inputs on switching.

Good point!
@alitoshmatov could you please include this details in your proposal?

**Comment by MonilBhavsar** [comment] 2023-07-21 09:20
Thanks!
Looks good to me 👍 

> We can either introduce second state variable called recoveryCode and apply appropriate validation when submitting

Different validation sounds good to me. Recovery codes has 8 alphanumeric characters

**Comment by alitoshmatov** [comment] 2023-07-21 09:36
PR will be ready in couple of hours. 
One thing clarify, what should be exact texts for switching inputs? Also, can you provide me with correct spanish translations
`Use recovery code` - `Use two-factor code`

cc: @abdulrahuman5196 @shawnborton

**Comment by alitoshmatov** [comment] 2023-07-22 06:12
PR is ready - https://github.com/Expensify/App/pull/23390

**Comment by MonilBhavsar** [comment] 2023-08-02 13:50
@laurenreidexpensify could you please help to verify a quick copy here - Does `Use 2FA code` and `Use recovery code` looks good? For `Use 2FA code`, I think we can `Use authenticator code` since that's what we use above input

<img width="1440" alt="252253920-198cd816-0dc8-48df-b767-a791c441b6" src="https://github.com/Expensify/App/assets/32012005/c2d49e99-2854-4f28-8b8f-04751c028969">


<img width="1440" alt="252253561-fc15ed60-e75f-47bb-a769-24643a940b99" src="https://github.com/Expensify/App/assets/32012005/58ead00f-3b2e-414a-8087-c9aa041c061a">

**Comment by abdulrahuman5196** [comment] 2023-08-06 07:18
@laurenreidexpensify Could you kindly check on the above?

And other strings as well here - https://github.com/Expensify/App/pull/23390/files#diff-22037c1e4dbdea8803b450b3fce06e6c475762a31ecf84b34dc264ba0e443637R570

**Comment by laurenreidexpensify** [comment] 2023-08-08 12:57
Sorry for the hold up here everyone! I got the translations almost immediately h/t @marcochavezf but forgot to paste them here 🤦‍♀️ 

> Please copy or download codes before continuing
`Copia o descarga los códigos antes de continuar`

> Please enter a valid amount before continuing.
`Por favor ingresa un monto válido antes de continuar`

**Comment by alitoshmatov** [comment] 2023-08-08 16:46
@laurenreidexpensify We need someone to confirm these texts and their translation or suggest new one https://github.com/Expensify/App/pull/23390/files#diff-22037c1e4dbdea8803b450b3fce06e6c475762a31ecf84b34dc264ba0e443637R570

**Comment by abdulrahuman5196** [comment] 2023-08-08 17:03
@laurenreidexpensify Just to highlight from @alitoshmatov 's comment.

We also need to confirm the texts from product and their translation(Not just translation)

cc: @MonilBhavsar @shawnborton

**Comment by laurenreidexpensify** [comment] 2023-08-09 19:51
Sorry everyone I mixed up some translations I was working on. I will confirm the correct copy first thing tomorrow.

**Comment by laurenreidexpensify** [comment] 2023-08-10 09:15
Sorry folks just reviewing this, can someone please list a summary here of the exact phrases we need confirmation for and the translations. It's quite hard to work out now based on the links, so a summary here will help me review and get the translations. thanks

**Comment by MonilBhavsar** [comment] 2023-08-10 17:58
@laurenreidexpensify please see this message https://github.com/Expensify/App/issues/22335#issuecomment-1662251153
We need to confirm english translation for two messages below the input - 
1. Use 2FA code (My thought is to have "Use two-factor authenticator code" here, as we don't use 2FA)
2. Use recovery code

**Comment by alitoshmatov** [comment] 2023-08-10 18:42
@laurenreidexpensify @MonilBhavsar 
```
'Please enter your recovery code' - 'Por favor, introduce tu código de recuperación'
'Incorrect recovery code. Please try again.' - 'Código de recuperación incorrecto. Por favor, inténtalo de nuevo'
'Use recovery code' - 'Usar código de recuperación'
'Recovery code' - 'Código de recuperación'
'Use two-factor authentication code' - 'Usar autenticación de dos factores',
```

These are new texts we are introducing, error messages are exactly the same as magic code errors, just changed `magic code` to `recovery code`

**Comment by alitoshmatov** [comment] 2023-08-16 15:53
@laurenreidexpensify Friendly bump

**Comment by laurenreidexpensify** [comment] 2023-08-18 14:54
getting translations [here](https://expensify.slack.com/archives/C21FRDWCV/p1692370253265649) internally - updated this to a daily so I make sure to get this over the line, as I've been the blocker on progress here

**Comment by laurenreidexpensify** [comment] 2023-08-18 15:10
@alitoshmatov - confirmed, these are the correct translations to use - 

> 'Please enter your recovery code' - 'Por favor, introduce tu código de recuperación'
> 'Incorrect recovery code. Please try again.' - 'Código de recuperación incorrecto. Por favor, inténtalo de nuevo'
> 'Use recovery code' - 'Usa el código de recuperación'
> 'Recovery code' - 'Código de recuperación'
> 'Use two-factor authentication code' - 'Usa autenticación de dos factores',

thanks!

**Comment by MonilBhavsar** [comment] 2023-08-25 06:34
Thanks lauren!
@alitoshmatov can you please update the PR with these translations!

**Comment by alitoshmatov** [comment] 2023-08-25 09:32
@MonilBhavsar updated PR and requested review from C+

**Comment by laurenreidexpensify** [comment] 2023-10-03 08:26
Payment Summary:

- External issue reporter - N/A @MonilBhavsar internal no payment
- Contributor that fixed the issue - @alitoshmatov $500, payment issued in Upwork
- Contributor+ that helped on the issue and/or PR - @abdulrahuman5196  $500, payment issued in Upwork

To note there was also a case for a +9 day penalty here, but am doing a discretionary waiver as the issue remained blocked on Expensify for a few weeks after assignment.

**Comment by laurenreidexpensify** [comment] 2023-10-03 08:35
@abdulrahuman5196 bump for steps ahead ^^

**Comment by alitoshmatov** [comment] 2023-10-03 09:02
@laurenreidexpensify  We had a regression of this issue https://github.com/Expensify/App/issues/28092

**Comment by alitoshmatov** [comment] 2023-10-03 09:10
Though I would argue that this was not a regression but a completion to the original PR and caused by incomplete requirements. I mean original PR didn't break anything and delivered expected result. Considering that this was a feature not a bug, detailed requirements would have definitely been helpful. Still, It is just my opinion, and I respect the final decision

**Comment by alitoshmatov** [comment] 2023-10-03 09:12
I have another pending payment issues and we can skip on one of those 500$ payments to to fix overpayment

**Comment by abdulrahuman5196** [comment] 2023-10-03 09:35
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not regression. This is a feature request.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

General regression test for the new feature.

1) Have a user whose 2fa is enabled
2) Sign in with this user
3) At two-factor authentication step make sure Use recovery code text link is present
4) Make sure pressing it switches input type to simple text input
5) Enter recovery code
6) Make sure recovery code is being validated correctly and you can sign in with correct recovery code


cc: @laurenreidexpensify

**Comment by MonilBhavsar** [comment] 2023-10-05 10:22
Since this issue was a feature request, technically we cannot call https://github.com/Expensify/App/issues/28092 as regression considering that workflow did not exist previously. But It was something that we could have caught while testing the PR linked to this issue.

My though - we can issue full payment here and consider https://github.com/Expensify/App/issues/28092 as a follow up issue/PR since it was one liner change and issue no payment there. If it is possible? @laurenreidexpensify @abdulrahuman5196 @alitoshmatov

**Comment by abdulrahuman5196** [comment] 2023-10-05 10:27
Agree on the same @MonilBhavsar . 

Cc: @laurenreidexpensify

**Comment by MonilBhavsar** [comment] 2023-10-09 07:20
Thank you everyone!
@laurenreidexpensify we have closed https://github.com/Expensify/App/issues/28092 without payment and we need to issue payment here

**Comment by laurenreidexpensify** [comment] 2023-10-09 09:03
Okay great - as per summary [here](https://github.com/Expensify/App/issues/22335#issuecomment-1744458033) all payments have been issued, so am closing.

**Closed by laurenreidexpensify** 2023-10-09 09:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
