### ISSUE TITLE
[HOLD for payment 2024-01-04] [HOLD for payment 2024-01-03] [$500] Scan Split - Entered amount is not saved in split scan details view

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33587] opened 2023-12-26 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to workspace chat > + > Split bill.
2. Go to Scan.
3 .Create a scan split bill.
4. Click on the bill split preview.
5. Click amount.
6. Enter amount and save it.

## Expected Result:
The entered amount is saved.

## Actual Result:
The entered amount is not saved.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0b2a7d4c-4c38-40af-82f5-1f0e0398949d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f97d51fb2a55a23</li>
        <li>Upwork Job ID: 1739640051172978688</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28070204</li>
<li>situchan | Contributor | 28070454</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by shubham1206agra** [comment] 2023-12-26 13:34
Maybe https://github.com/Expensify/App/pull/32533 is the PR

**Comment by shubham1206agra** [comment] 2023-12-26 13:44
## Proposal
### Please re-state the problem that we are trying to solve in this issue

 Scan Split - Entered amount is not saved in split scan details view

### What is the root cause of that problem?

It is stemming from https://github.com/Expensify/App/pull/32533

### What changes do you think we should make in order to solve the problem?

Fix 

```js
const saveAmountAndCurrency = useCallback(
        ({amount, currency: newCurrency}) => {
            const newAmount = CurrencyUtils.convertToBackendAmount(Number.parseFloat(amount));

            // If the value hasn't changed, don't request to save changes on the server and just close the modal
            if (newAmount === transactionAmount && newCurrency === transactionCurrency {
                Navigation.dismissModal();
                return;
            }

            IOU.updateMoneyRequestAmountAndCurrency(transaction.transactionID, report.reportID, newCurrency, newAmount);
            Navigation.dismissModal();
        },
        [transaction, report],
    );
```

### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment] 2023-12-26 14:44
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/33587#issuecomment-1869566325) looks good to me. 🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2023-12-26 15:09
Sounds good! Since this is deploy blocker, let's try to get this merged today!

**Comment by mountiny** [comment] 2023-12-26 22:51
Going to reassig to @situchan because this is a deploy blocker and we need to fix this with urgency and @allroundexperts is not available

**Comment by pecanoro** [comment] 2024-01-08 10:11
@anmurali Can you handle the payment whenever you have a moment? Thanks!

**Comment by anmurali** [comment] 2024-01-10 00:15
Paid.

**Closed by anmurali** 2024-01-10 00:15 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
