### ISSUE TITLE
[Report Fields] [$500] [MEDIUM] Expense - Unable to unselect option in report field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36602] opened 2024-02-15 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36304

## Action Performed:
Precondition: admin creates a Collect workspace in OD and invites an employee, admin sets up a dropdown field with a few options in Reports > Report and Invoice Fields
1. Open the app and log in as the employee
2. Navigate to the workspace room
3. Request money from the workspace
4. Open the report and then the report field "Field"
5. Select any option
6. Open the report field again and unselect the option

## Expected Result:
The option is unselected, the checkmark is not displayed, and the report field is empty

## Actual Result:
The option stays selected and is displayed in the report field. Also, the selected option is displayed in "Recent" instead of above "Recent" and "All" sections like in other places Category, tags

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/10acbf36-588b-4826-be30-feb7a27347aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119ace936e559d689</li>
        <li>Upwork Job ID: 1758162235501703168</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-15 16:12
We think that this bug might be related #wave6-collect-submitters
cc @greg-schroeder

**Comment by FitseTLT** [comment] 2024-02-15 16:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Unable to unselect option in report field

### What is the root cause of that problem?
We are setting the selected value without checking it is the already selected one here
https://github.com/Expensify/App/blob/2d2e05f30260482b0cd3076a32842cf755d49e3c/src/pages/EditReportFieldDropdownPage.tsx#L96
### What changes do you think we should make in order to solve the problem?

We should change it to 
```
                        onSelectRow={(option: Record<string, string>) => onSubmit({[fieldID]: option.text === searchValue ? '' : option.text})}

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-02-29 11:26
Will be ready EOW

**Comment by greg-schroeder** [comment] 2024-03-02 00:35
Bump @FitseTLT - do you have a Draft PR you can link as a starting point at least? Thanks!

**Comment by FitseTLT** [comment] 2024-03-05 15:08
@Ollyws [PR](https://github.com/Expensify/App/pull/37761) ready

**Comment by JmillsExpensify** [comment] 2024-03-26 02:53
It looks like we've closed the linked PR, so shouldn't we close this issue as well as a result?

**Comment by greg-schroeder** [comment] 2024-03-26 04:28
Closing!

**Closed by greg-schroeder** 2024-03-26 04:28 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by greg-schroeder** [comment] 2024-03-27 23:39
sent offers to you both, you are correct
