### ISSUE TITLE
[HOLD for payment 2024-12-12] [HOLD for payment 2024-12-03] [$250] iOS Search - Folder background in the empty state disappears after switching tabs

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51735] opened 2024-10-30 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has no expenses
1. Launch ND or hybrid app
2. Go to Search
3. Switch between different expense status tab

## Expected Result:
The folder background in the empty state will not disappear after switching tabs

## Actual Result:
The folder background in the empty state disappears after switching tabs

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 
<img width="427" alt="44 52" src="https://github.com/user-attachments/assets/315766f3-deb0-4d55-b4c6-c069a0259c80">

https://github.com/user-attachments/assets/64f5fcde-7b6e-4600-8e57-54f1c71c0dec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852040650047940888</li>
        <li>Upwork Job ID: 1852040650047940888</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-10-30 12:56
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-30 12:57
We think that this bug might be related to #wave-control

**Comment by SzymczakJ** [comment] 2024-10-30 16:14
I'm able to reproduce, feel free to assign me, as I can work on it.

**Comment by SzymczakJ** [comment] 2024-10-31 11:40
FYI I'll OOO on Friday and Monday.
I've looked into this bug but it seems really strange and I'll probably have to consult the big brains in SWM open-source team to solve this 😄

**Comment by UltraneDevelopment** [comment] 2024-10-31 20:47
**Issue Summary**
The folder background disappears in the empty state when switching between different expense status tabs. This issue is currently isolated to iOS (both Standalone and HybridApp), while it works as expected on other platforms.

**Proposed Solution**

1. Component State Persistence:

- Ensure that the component responsible for rendering the empty state background maintains its visibility state across tab switches.

 -Implement persistent state management (using a method such as useState or useRef), so the background doesn’t reset or disappear when changing tabs.

2. Force Component Re-render on Tab Switch:

- On iOS, React Native components sometimes need to be explicitly updated during tab switches. By using key or a similar identifier, we can trigger a re-render of the background component, making sure it persists through each tab switch.

- This will ensure that the background component is rendered consistently across tabs, preventing visibility loss.

3. Platform-Specific Styling or Rendering:

- Since the issue is iOS-specific, conditional logic (e.g., Platform.OS === 'ios') can be applied to re-render the background component on tab switches solely for iOS, preserving the behaviour across Android and web.

4. Testing and Validation:

- After implementing this solution, I would conduct extensive testing on all affected iOS platforms (Standalone and Hybrid) to verify that the background persists.
- I’d also test on Android and web to ensure there are no regressions or unintended changes.

**Comment by UltraneDevelopment** [comment] 2024-10-31 20:50
Contributor details
Your Expensify account email: logan.harris@ultranedevelopment.co.uk
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~0152633cd2e0038e15)

**Comment by UltraneDevelopment** [comment] 2024-10-31 20:50
Contributor details
Your Expensify account email: logan.harris@ultranedevelopment.co.uk
Upwork Profile Link: https://www.upwork.com/freelancers/~0152633cd2e0038e15

**Comment by SzymczakJ** [comment] 2024-11-05 15:03
I've looked into this issue with @WoLewicki and here's our update:
- the problem is caused by recycling views that react native is doing on iOS to be more performant. It recycles faulty views that for some reason don't show the background, even though it's properly set,
- the faulty views are coming from react-content-loader library, as when we comment the components coming from this library the problem is not longer reproducible,
- we have a workaround for this to just turn off view recycling on iOS native side, but it will come with it's costs, as it will bring performance down
- as the workaround presented above is not ideal, we will dig deeper to fix the root cause, which is probably located in react-content-loader library

**Comment by mananjadhav** [comment] 2024-11-05 17:49
Okay. @garrettmknight if this is handled by the agency should we remove the "Help Wanted" label?

**Comment by SzymczakJ** [comment] 2024-11-07 16:47
No update, I had to prioritise other task(migration of react-native-live-markdown to npm), but I'll work on it tomorrow.

**Comment by SzymczakJ** [comment] 2024-11-08 16:52
Bug is complicated, I think we can rule out the react-content-loader, as even overriding the return value of this library to null doesn't fix the bug. I'll continue to work on this on Tuesday, because Monday is bank holiday in Poland.

**Comment by SzymczakJ** [comment] 2024-11-13 09:31
Together with @WoLewicki we managed to find a workaround for this:
As I previously said the problem is caused by view recycling which is new arch feature. Some <View /> components coming from <ItemListSkeletonView /> component were broken(we don't know what is breaking them yet), we are fixing this by just styling <SkeletonViewContentLoader /> directly without the help of <View /> component, so we don't reuse broken <View /> components.
The workaround is a viable option and I'l put up a PR with it today, but we would like to get to the root cause of this bug because it might be a problem for us in other parts of the app, this is why I'm gonna continue investigating it for a while.

**Comment by SzymczakJ** [comment] 2024-11-13 16:37
I've put up a PR with a workaround fix.
On the other hand the root cause is still not solved yet and it might come up in other parts of the app, because combination of components that produces this bug is common(<View /> + <Svg /> + <Lottie />). We suspect it's connected to Lottie and investigating the root cause would take some time but whole React Native community would benefit when we solve this.
I don't know, if we should continue to work on this task or should we stay with this workaround solution and move on to tasks with more priority. I'll let you decide @garrettmknight 😄

**Comment by SzymczakJ** [comment] 2024-11-14 13:59
> investigating the root cause would take some time but whole React Native community would benefit when we solve this.
I don't know, if we should continue to work on this task or should we stay with this workaround solution and move on to tasks with more priority.

Bump @garrettmknight 🙇

**Comment by garrettmknight** [comment] 2024-11-15 10:32
@SzymczakJ let's go with the workaround for now since it sounds like solving the root cause will take quite a bit of time.

**Comment by garrettmknight** [comment] 2024-11-15 10:32
We can see if this comes up more and decide to fix the root if necessary, but this is a pretty small inconsistency that I don't think merits a huge solution unless it becomes a lot more common.

**Comment by blimpich** [comment] 2024-11-25 17:12
Update: looks like its still reproducing even after the proposal was merged ([link](https://github.com/Expensify/App/pull/52481#issuecomment-2498076104)). @SzymczakJ is going to look into it.

**Comment by SzymczakJ** [comment] 2024-11-26 16:23
The bug became reproducible after merging main to PR branch. I think I have a solution for that, which I'm currently testing. I will put up a PR with it tomorrow

**Comment by SzymczakJ** [comment] 2024-11-27 11:37
PR ready for review, I think now it will be robust enough to cover all edgecases.

**Comment by garrettmknight** [comment] 2024-12-03 20:15
@mananjadhav please complete the checklist and submit for payment.

**Comment by mananjadhav** [comment] 2024-12-04 02:16
We had to push a second PR to fix this, which was just deployed to staging yesterday. The payout date will be based on this new PR https://github.com/Expensify/App/pull/53199

**Comment by mananjadhav** [comment] 2024-12-12 10:46
@garrettmknight This was more of a workaround solution with no exact offending PR. Should we skip the checklist for this one? What do you think of adding a regression test for this one?

**Regression Test Proposal**
1. Open the app with no expenses or chats.
2. Go to the search page
3. You should see a search folder animation icon.
4. Switch between different tabs (expense statuses).
5. Ensure the search folder animation is visible. Switch between the tabs atleast a few mins.

**Comment by mananjadhav** [comment] 2024-12-13 17:45
@garrettmknight quick bump on this one.

**Comment by garrettmknight** [comment] 2024-12-13 17:55
All set - request payment when you're ready!

**Comment by mananjadhav** [comment] 2024-12-13 17:58
Thanks for the prompt action. I've already raised it [here](https://new.expensify.com/r/228394223820319).

**Comment by JmillsExpensify** [comment] 2024-12-13 19:32
Payment summary: $250 @mananjadhav for PR review and testing

**Comment by mananjadhav** [comment] 2024-12-14 04:52
Thanks @JmillsExpensify. Quick question, do we need an explicit comment from the BZ member? or checklist from bot [comment](https://github.com/Expensify/App/issues/51735#issuecomment-2538270005) is enough?

**Comment by garrettmknight** [comment] 2024-12-17 12:02
So long as the checklist has been completed by BZ we're good.

**Comment by mananjadhav** [comment] 2024-12-17 12:10
Okay cool then. I've already raised the request on NewDot.

**Closed** 2024-12-21 14:17 UTC
Labels: External, Weekly, Awaiting Payment, Bug
