### ISSUE TITLE
[HOLD for payment 2024-07-02] Mention - Report mention #admins is not styled when editing comment in room chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42521] opened 2024-05-23 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #41731
**Version Number:** 1.4.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room.
3. Send a message.
4. Right click on the message > Edit comment.
5. Type #admins.

## Expected Result:
Report mention #admins will be styled because the chat is part of the workspace (not 1:1 DM).
## Actual Result:
Report mention #admins is not styled when editing comment in room chat.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5b513140-cb0a-4478-ae75-cd3966a8c3bd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by m-natarajan** [comment] 2024-05-23 12:38
@carlosmiceli FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-05-23 12:50
@puneetlath, can you help clarify what's a bug here:

1. The edit comment composer does not have auto-complete. Is that expected? 
2. Clicking "Edit comment" on a room mention results in a blank composer. This is not expected? The value should be in the composer when you go to edit it
3. If the value is there and there's no auto-complete, when should it get "highlighted"? Is it when there's an exact match to a room name/person, or just as soon as you use the type a character after the `#` or `@` operator?

**Comment by carlosmiceli** [comment] 2024-05-23 18:11
Yes, I'm also not sure I understand what the bug is in the video? Also, doesn't feel like an hourly/urgent issue, right?

**Comment by rlinoz** [comment] 2024-05-23 18:39
Editing mentions is not supported yet, it is being worked on here https://github.com/Expensify/App/issues/39550

**Comment by carlosmiceli** [comment] 2024-05-23 18:46
Gotcha @rlinoz , what would be the proper update of labels in this case?

**Comment by puneetlath** [comment] 2024-05-23 18:51
>The edit comment composer does not have auto-complete. Is that expected?

Yes, this is currently expected until we support inline auto-suggestion: https://github.com/Expensify/App/issues/16078

I think we should just close this issue for now.

**Comment by lanitochka17** [comment] 2024-06-15 13:54
Issue is still reproducible on the latest build 1.4.84-0


https://github.com/Expensify/App/assets/78819774/2ace2c0e-c5ff-4417-af37-011d47977b2b

**Comment by mountiny** [comment] 2024-06-16 21:40
This is minor and I have tested in staging and production and its same behaviour for me 😕

**Comment by rlinoz** [comment] 2024-06-17 14:37
In the PR it was working, maybe something else changed?

cc: @war-in @eh2077

**Comment by war-in** [comment] 2024-06-17 16:29
> In the PR it was working, maybe something else changed?

I just checked the PR and it seems that it was not working there too :/ I'll dive into it tomorrow 🙏

**Comment by eh2077** [comment] 2024-06-17 23:55
That's weird as it worked for me when I tested it

**Comment by war-in** [comment] 2024-06-18 10:39
@eh2077 You're right. In videos posted by you (and in mine too) there are styled room mentions. I found the commit which broke it and it is the [last main merge](https://github.com/Expensify/App/pull/40565/commits/88465453763e4e52dc0a89b68590cce7cfa3af90).
When you switch to the [previous one](https://github.com/Expensify/App/pull/40565/commits/f0b59c07fbdc9b7ab9f72110f1aca1a92a1d9af4), room mentions are highlighted.

So the issue comes from some other commit merged to main

**Comment by eh2077** [comment] 2024-06-19 16:38
@war-in Can you help to investigate the root of this issue? I found that mentions are styled when editing private notes


https://github.com/Expensify/App/assets/117511920/dc1e8d48-961b-4656-99ab-f52b4011b43d

**Comment by carlosmiceli** [comment] 2024-06-19 19:26
Being investigated.

**Comment by war-in** [comment] 2024-06-21 08:41
@eh2077 Yes! I'll post an update here when I find something

**Comment by war-in** [comment] 2024-06-21 09:56
Hmm, I'm not sure if you're aware of it but on the current main all mentions are displayed as IDs 🥶 
<img width="302" alt="image" src="https://github.com/Expensify/App/assets/61014013/643ddccb-16b3-4839-ae72-de8bb6d1cb7c">

I found the root cause of this issue. `MentionReportRendered` can't get the correct report (and its' name). 

The fix will be quick. Should I do it as a part of this issue or maybe we want to fix it ASAP?
cc @carlosmiceli

**Comment by war-in** [comment] 2024-06-21 10:24
I also posted a [comment](https://github.com/Expensify/App/pull/43632#issuecomment-2182471061) on PR which broke that

**Comment by war-in** [comment] 2024-06-21 12:42
I think I found the issue 🎉 

`Composer` now has the `isGroupPolicyReport` prop (set by default to `false`) which defines if the room mentions are on or off (e.g. we don't want to mention rooms in DMs).

I'll prepare the fix :)

**Comment by war-in** [comment] 2024-06-21 14:19
FYI, PR is ready and waiting for the review!

**Comment by eh2077** [comment] 2024-06-21 14:59
Reviewing PR

**Comment by trjExpensify** [comment] 2024-07-02 15:34
Assigning @eh2077, as Eric is due payment for the C+ review. The Applause team flagged this regression through existing testing, so not adding a new one. 

No payment due here, as it was a regression from https://github.com/Expensify/App/pull/44160 caught during the regression period. Closing!

**Closed by trjExpensify** 2024-07-02 15:34 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
