### ISSUE TITLE
Chat - Unable to send empty backticks for code block, Send icon is disabled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9008] opened 2022-05-13 22:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8948

## Action Performed:
1. Log in
2. Start a chat conversation
3. Send a message with empty backticks (code block with no text in-between)

## Expected Result:
Verify empty backticks are sent and NOT an empty code block

## Actual Result:
Unable to send empty backticks are sent . Send button is inactive.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.60-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/168395576-733cd226-4928-4f85-89e1-8901a6051ef8.mp4

![Bug5570627_Screen_Shot_2022-05-13_at_3 52 47_PM](https://user-images.githubusercontent.com/43996225/168395578-05dab6c1-3fbf-4d12-bf88-5cf5b4e023a6.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment] 2022-05-13 22:11
@kavimuru please remember that the Triager (in this case, me) adds the Engineering label.

**Comment by roryabraham** [comment] 2022-05-15 22:34
I recommend that we just close this. I don't think sending a message with just an empty code block is really an important use case.

**Comment by arosiclair** [comment] 2022-05-16 13:38
I'll attempt to reproduce this with the latest on `main`, but I agree this doesn't need a new issue. The original issue #8720 is still open.

**Comment by arosiclair** [comment] 2022-05-16 14:57
Follow up: it looks like this issue was duplicated and worked on at the same time in #7971 and #8720. The first issue added logic to disable the send button in this scenario. In the second I added logic to allow you to successfully send this kind of message. I would argue that disabling the send button is no longer necessary for this.

**Comment by AndrewGable** [comment] 2022-05-16 21:58
I agree, closing!

**Closed by AndrewGable** 2022-05-16 21:58 UTC
Labels: Engineering, Daily, Overdue
