### ISSUE TITLE
Inviting users with phone number displays weird message on phone

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20435] opened 2023-06-08 02:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new workspace and go to invite members
3. Invite a user that has phone number (it's compulsory), and on the message field , remove the current message and add your own message within quotation marks " " and also add signs like & , backtik ` and <
4. Check the message that may have arrived on your phone number that you invited before
5. Notice that quotation marks is displayed as &quot and looks weird in the message. Also the backtick, & and < are also shown weirdly
## Expected Result: 
Message while Inviting users with phone number doesn't display properly on the message that has arrived on phone
## Actual Result: 
Message while Inviting users with phone numbers should  be displayed properly
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f94c7644-c038-4e87-bb2a-f90ade3f34c7

<img src="https://github.com/Expensify/App/assets/43996225/ef89b328-95b2-4855-b386-1e73293d5467" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/5a73df8e-9ea0-4540-8353-0d8d98093803" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685941205156389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108b7537c7a8d0d92</li>
        <li>Upwork Job ID: 1669098003016310784</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by alex-mechler** [comment] 2023-06-12 22:00
Yes, this will have to be internal

**Comment by stephanieelliott** [comment] 2023-06-14 21:43
Thanks @alex-mechler, guess you're the lucky one on assignment here then!

**Comment by stephanieelliott** [comment] 2023-06-15 19:13
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @NicMendonca,  I'll grab this back from you when I return!

**Comment by alex-mechler** [comment] 2023-06-15 23:26
Have not had a chance to dive into this, and am OOO friday-monday as a heads up here. I don't think this is urgent enough to warrent reassignment, but feel free to spin the wheel for another engineer if needed

**Comment by NicMendonca** [comment] 2023-06-19 12:04
@alex-mechler should this still be a `daily`?

**Comment by michaelhaxhiu** [comment] 2023-06-21 18:19
🧇 I'm removing AlexM's assignment and triggering assignment of a new engineer

**Comment by NicMendonca** [comment] 2023-06-23 00:56
@cead22 let me know if I need to find someone else internally 👋

**Comment by cead22** [comment] 2023-06-24 00:21
Quick investigation so far
- I reproduced inviting my phone number to an expensifail.com workspace
- [Logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227dc0b8bc6d445257-LAX%22)+AND+timestamp:[2023-06-23T23:05:52.775Z+TO+2023-06-24T01:05:52.775Z]&index=logs_expensify-022952)
- `AccountID #2211126 called 'InviteUsers' for policy '8F24C5EAEC6CADA3' message 'Test &amp; &quot; &gt;' emailList '+14153166423@expensify.sms'`
- It looks like we're HTML-encoding the message before make the api call, so we're sending the encoded message to the api. It's possible we need a front end fix as well

```
Processing 'AddMembersToWorkspace' for 'expensify.com' from '75.80.102.185' ~~ 
command: 'AddMembersToWorkspace' 
employees: '[{"email":"+14153166423@expensify.sms"}]' 
welcomeNote: 'Test &amp; &quot; &gt;'                      <---------------------------------------
policyID: '8F24C5EAEC6CADA3'
reportCreationData: '{"+14153166423@expensify.sms":{"reportID":"3871915553990080","reportActionID":"668730370059106033"}}' 
appversion: '1.3.31-3' 
pusherSocketID: '479922.296723' 
authToken: '<REDACTED>' 
referer: 'ecash' 
platform: 'web' 
api_setCookie: 'false' 
email: 'carlos@expensifail.com' 
partnerName: 'expensify.com'
browserGUID: '64963360b5db0' 
HTTP_CF_BOT_SCORE: '93' 
HTTP_CF_JA3_HASH: '21374ef547fa5844c59fd5d2f4ffdbaf'
```

**Comment by cead22** [comment] 2023-06-25 20:32
Looks like we intentionally html-escape here 
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/actions/Policy.js#L408-L409

**Comment by NicMendonca** [comment] 2023-06-29 20:37
@cead22 any update on this one?

**Comment by cead22** [comment] 2023-07-04 00:09
Sorry, I don't have any updates for this yet, I've been kinda slammed. Ionatan [posted a message today](https://expensify.slack.com/archives/C03TQ48KC/p1688419837215279) that makes me think that the solution I was thinking about might not be the right one, so I need to check with him on that before trying to code the solution

**Comment by MariaHCD** [comment] 2023-07-04 08:26
I think this is related to: https://github.com/Expensify/App/issues/20081

@cristipaval has a solution here: https://github.com/Expensify/Web-Expensify/pull/38012 but let's confirm this is actually the holistic solution we want.

**Comment by cristipaval** [comment] 2023-07-04 12:24
> I think this is related to: #20081
> 
> @cristipaval has a solution here: [Expensify/Web-Expensify#38012](https://github.com/Expensify/Web-Expensify/pull/38012) but let's confirm this is actually the holistic solution we want.

Yes, it seems to be a dupe of https://github.com/Expensify/App/issues/20081

**Comment by stephanieelliott** [comment] 2023-07-05 19:56
Ah yep, I agree this is a dupe and is solved with https://github.com/Expensify/App/issues/20081. Gonna close this out but feel free to reopen if you disagree

**Closed by stephanieelliott** 2023-07-05 19:56 UTC
Labels: Engineering, Daily, Internal, Bug
