### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Dev: Web - Workspace - Calendar disappears when clicking on it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20973] opened 2023-06-17 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app on Safari Web
2. Go to settings > workspace >Bank account > connect manually
3. Fill the form until step 3
4. On date of birth field click to add date 

## Expected Result:
Calendar does not disappear when clicking on it

## Actual Result:
Calendar disappears when clicking on it the first time 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0c00e263-81e4-4b4a-ba59-891ed38f78c4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686396209206479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01474c1fe598ac86fd</li>
        <li>Upwork Job ID: 1670876754666561536</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-06-19 22:45
Not overdue

**Comment by jeet-dhandha** [comment] 2023-06-19 22:57
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
For `Safari` mWeb while adding DOB in Workspace's Bank account, disappears on click. This is not happening in chrome. 
(Also happening in other places too.)

### What is the root cause of that problem?
- In `Safari` mWeb, when we click on `DatePicker` it is getting called multiple times thus getting out of focus sometimes.

### What changes do you think we should make in order to solve the problem?
- I would suggest using `throttle` from underscore to maintain the time gap between two calls. 
<img width="939" alt="Screenshot 2023-06-20 at 4 27 25 AM" src="https://github.com/Expensify/App/assets/78416198/d3149ec9-0f72-47fe-a977-5051fadcf008">

Fixed:

https://github.com/Expensify/App/assets/78416198/03f22493-410f-49fc-966d-3c3229afdefb



### What alternative solutions did you explore? (Optional)
- N/A

**Comment by mananjadhav** [comment] 2023-06-20 20:32
@MitchExpensify @kbecciv Are you folks able to reproduce this on Safari? I am not able too. Also one thing I noticed is the GH issue body video shows the date format in `YYYY-MM-DD`, but for me it loads in `DD/MM/YYYY` format.

**Comment by MitchExpensify** [comment] 2023-06-21 21:17
> Are you folks able to reproduce this on Safari? I

I was, yes!

**Comment by mananjadhav** [comment] 2023-06-27 10:15
I think @kushu7's [proposal](https://github.com/Expensify/App/issues/20973#issuecomment-1596130089) is good. I don't think we should be using throttle and we can't remove showDatePicker. I wonder if we can just use `Browser.isMobileSafari` instead of `!Browser.isMobileChrome`.


🎀 👀 🎀 C+ reviewed.

**Comment by roryabraham** [comment] 2023-06-29 22:43
@narzullome, please ignore the above ^

**Comment by MitchExpensify** [comment] 2023-07-01 18:24
@narzullome can you please apply to the Upwork job here for eventual reporting payment?  https://www.upwork.com/jobs/~01474c1fe598ac86fd Thank you!

**Comment by narzullome** [comment] 2023-07-01 19:15
@MitchExpensify Applied

**Comment by MitchExpensify** [comment] 2023-07-01 22:59
Great! Everyone should have offers for eventual payment 👍

**Comment by MitchExpensify** [comment] 2023-07-03 21:07
No worries, we can just take that OOO delay into account for any bonus consideration 👍

**Comment by roryabraham** [comment] 2023-07-08 03:44
For posterity, I was OOO from 2023-06-30 => 2023-07-05, so 4 business days. Then I didn't review the PR yesterday, so that's a 5th day where it sat outside of @kushu7 and @mananjadhav's control.

**Comment by MitchExpensify** [comment] 2023-07-13 23:23
Reminder set to pay on the 20th!

Reminder to take the BZ steps when you get a chance @mananjadhav 🚀

**Comment by MitchExpensify** [comment] 2023-07-19 18:56
> I don't think we need a regression test for this one.

👍 

> Also @MitchExpensify I will be raising the payout request on NewDot.

Great! Thanks @mananjadhav

**Comment by mananjadhav** [comment] 2023-07-20 02:15
Thanks @MitchExpensify. I've raised a request on NewDot. Can you help with the payout for @kushu7? Also timeline bonus will apply to them.

**Comment by MitchExpensify** [comment] 2023-07-20 20:49
Of course! Paid all. Feel free to close this once the NewDot payment comes through @mananjadhav 

Thanks everyone!

**Comment by mananjadhav** [comment] 2023-07-21 04:02
@MitchExpensify  I don't have the access to close it. But I think we can close this out if other pay outs are done. My payment is stuck because of approval for one of the previous issues. I'll track it on NewDot.

**Comment by anmurali** [comment] 2023-07-21 16:42
Approved $1000 to Manan based on https://github.com/Expensify/App/issues/20973#issuecomment-1635049190

**Comment by mananjadhav** [comment] 2023-07-21 16:43
@anmurali I think the payout here is 1500.

**Comment by anmurali** [comment] 2023-07-21 16:44
You beat me to the edit. Haha
I believe because this was delayed due to Rory's OOO 9https://github.com/Expensify/App/issues/20973#issuecomment-1626711336) we're approving it for a bonus?

**Comment by mananjadhav** [comment] 2023-07-21 16:44
Yeah that's right.

**Comment by mananjadhav** [comment] 2023-07-21 21:45
@MitchExpensify Good to close this one out?

**Comment by MitchExpensify** [comment] 2023-07-22 23:44
If you've received payment, absolutely!

**Closed by MitchExpensify** 2023-07-22 23:44 UTC
Labels: External, Daily, Awaiting Payment, Bug
