### ISSUE TITLE
Clicking on browser/system back button takes user back two steps

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21218] opened 2023-06-21 14:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspace > reimbursements > Connect bank account > Connect manually
2. Click on the browser/system back button

## Expected Result: 
App should take user one step back
## Actual Result: 
App takes user two steps back
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/28d58f8a-208d-4e37-ab18-b0b64ef87f4d

https://github.com/Expensify/App/assets/43996225/cd4d9763-44a8-4f4c-a811-95dd5a8be933

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686817579048109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by daordonez11** [comment] 2023-06-23 07:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Going back with browser button instead of header back goes back "2 views", in other words, returns to ReimbursementPage instead of BankAccountPage
Note: It 
### What is the root cause of that problem?
`BankAccountStep` component has something called `substeps` stored in the onyx key `REIMBURSEMENT_ACCOUNT.achData.subStep`
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/pages/ReimbursementAccount/BankAccountStep.js#L61C1-L79C1
Since this navigation is managed on memory pressing back in the browser/android back button goes back in the React Navigation stack, hence going back from BankAccountStep to `ReimbursementAccountPage`. Pressing in the navigation header back goes through a custom code in `ReimbursementAccountPage`:
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L276C1-L290C18
This is why it works pressing on it, it just cleans de `REIMBURSEMENT_ACCOUNT.achData.subStep` key from Onyx

### What changes do you think we should make in order to solve the problem?
So to be clear this seems like a "desired" behavior so there are 2 possible solutions:
1. Refactor the code of the substeps and turn `BankAccountStep` into a mini Stack inside `ReimbursementAccountPage` or RHP. This might take some effort due to all the lines included in the goBack method, with a high chance of regression:
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L276C1-L290C18
2. @mountiny @marcochavezf I think I know have found two possible use cases of my [proposal](https://github.com/Expensify/App/issues/20558#issuecomment-1585445290) in https://github.com/Expensify/App/issues/20558 basically I could implement the library of BackButtonUtils so generic that it could allow this special use cases of navigation: going back to substep, going back to public room . Or any other special scenario to work. This can be found in the original [PR](https://github.com/Expensify/App/pull/20733). And then it wouldn't be a single resp code and could be useful in other special navigation scenarios. Calling a specific handler in two places: 1. `SignInPage` 2. `BankAccountStep`

cc. @WoLewicki 

### What alternative solutions did you explore? (Optional)

N/A both discussed in the proposal

**Comment by mountiny** [comment] 2023-06-23 12:43
@gedu will be working on refactoring this entire flow

@anmurali could we make the Tiered bank account tracking issue public otherwise its hard to link for contributors?

@gedu Would you be able and want to work with @daordonez11 on making sure the flow is made from individual stack screens to ensure the navigation works as expected?

**Comment by WoLewicki** [comment] 2023-06-23 17:14
Yeah, it seems like the same issue as with `Request Money` flows, where the steps were not connected to the navigation. So if we want to refactor it, I think there is nothing to add from my side. Also, hijacking `Back` button won't still solve the browser back button scenario on web, or am I missing something @daordonez11 ?

**Comment by daordonez11** [comment] 2023-06-23 17:18
Right @WoLewicki it was lack of knowledge form my side. Definitely if everything will be in the stack hijack is not necessary. It could be a workaround in case there is custom navigation inside of the app. I don't know if there are other places but definitely is just a patch solution.

**Comment by anmurali** [comment] 2023-06-26 16:04
@gedu want to make sure you have seen this and will factor this into your detailed design considerations for https://github.com/Expensify/Expensify/issues/289050. Can you give me a 👍 here to make sure?

(@vitHoracek I am trying to transfer https://github.com/Expensify/Expensify/issues/289050 to App repo, stay tuned)

**Comment by anmurali** [comment] 2023-07-03 17:54
I am going to close this because we will handle this in the VBBA refactor as commented earlier

**Closed by anmurali** 2023-07-03 17:54 UTC
Labels: Daily, Overdue, Bug

**Comment by Nathan-Mulugeta** [comment] 2023-07-03 17:58
Isn't this eligible for reporting bonus since the report has contribution @anmurali

**Comment by mountiny** [comment] 2023-07-06 03:35
Probably not in this case because we had plans to fix this with the refactor anyways. Thanks for raising this though!
