### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Web-Not found - LHN shows weird animation and becomes unresponsive after invoice deeplinking

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42906] opened 2024-05-31 10:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/41730
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Deep link to send invoice (e.g https://staging.new.expensify.com/create/invoice/start/1/7783051691252045
)
3. Click on the back icon of the not found RHP
4. Click on Settings

## Expected Result:
RHP closes with the right animation and LHN becomes responsive

## Actual Result:
RHP closes with a weird animation and LHN becomes stuck and unresponsive when opening settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a2f3d1e9-7279-4857-9754-ea0b4e0d0254

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01adb4996302fbbbfc</li>
        <li>Upwork Job ID: 1796610903877054464</li>
        <li>Last Price Increase: 2024-05-31</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 102545412</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by izarutskaya** [comment] 2024-05-31 10:03
@johncschuster I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-31 10:05
Production 
![Screenshot 2024-05-31 at 14 15 16](https://github.com/Expensify/App/assets/115492554/d3c4f7e7-f303-4613-b592-a504b8129f09)

**Comment by cristipaval** [comment] 2024-05-31 15:04
Removed the deploy blocker as per [this plan](https://expensify.slack.com/archives/CSL3XBCCR/p1717167018470479?thread_ts=1717165640.669459&cid=CSL3XBCCR). Let's assign @tienifr to fix and @shubham1206agra for the c+ review, since they are the authors of the original PR 🙏

**Comment by johncschuster** [comment] 2024-05-31 18:34
Sorry about the tag, @DylanDylann. We're assigning this one out to @tienifr and @shubham1206agra.

@tienifr / @shubham1206agra, can you comment on the issue so I can assign this to you?

**Comment by johncschuster** [comment] 2024-06-14 14:18
Will be paying this out on the 20th if there are no regressions. @shubham1206agra, can you complete the BZ Checklist above before then? Thank you!

**Comment by johncschuster** [comment] 2024-06-17 14:47
Got it. Thanks, @shubham1206agra!

**Comment by johncschuster** [comment] 2024-06-20 15:08
@shubham1206agra bump on the above question!

**Comment by johncschuster** [comment] 2024-06-21 14:55
@shubham1206agra Great! In that case, it sounds like we can close this one.

**Closed by johncschuster** 2024-06-21 14:55 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
