### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] Web - LHN - The page of the new group does not open if you press "Ctr+ENTER"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18480] opened 2023-05-05 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in HT account
3. In a account with a lot of active conversations, click on the green + icon on the home screen.
4. Click New Group. The New Group Page should open.
5. Without selecting any results, press Ctr+Enter. Nothing should happen.
6. Select several results.
7. Press Ctr+ENTER, and a group should be opened with your selected results.

## Expected Result:
Nothing should happen if users are not selected from the contact list after you press Ctr+Enter, but group should be opened with your selected results if you press Ctr+Enter.

## Actual Result:
Selected multiple results from the contact lists but not opened group with selected results if you press Ctr+Enter.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Web / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.10.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236486363-09c8af38-5849-4784-bc28-0c0b1bdb02e8.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156a1fe3b554ad240</li>
        <li>Upwork Job ID: 1655725621488488448</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-05-09 00:05
Makes sense, adding the `External` label

**Comment by kbecciv** [comment] 2023-05-10 13:52
@mananjadhav The QA team was given instruction to test all PRs in HT account. Let me check with new account.

**Comment by kbecciv** [comment] 2023-05-10 14:39
Issue is reproduced with low traffic account.

https://github.com/Expensify/App/assets/93399543/441c1ec7-dbe3-4cbc-a80c-8a590b6a92f0

**Comment by mananjadhav** [comment] 2023-05-10 14:51
Thanks @kbecciv for the update.

@mountiny I think @allroundexperts's proposal is good. Let me know what you think.

**Comment by stephanieelliott** [comment] 2023-05-12 03:17
Hey @mountiny, does [this proposal](https://github.com/Expensify/App/issues/18480#issuecomment-1537541205) look good to you?

**Comment by mountiny** [comment] 2023-05-14 15:52
Assigned @allroundexperts thanks for the review @mananjadhav and sorry for delay been on a conference

**Comment by mananjadhav** [comment] 2023-05-14 17:18
No worries. Thank you responding on the weekend. @allroundexperts You can start the with the PR.

**Comment by stephanieelliott** [comment] 2023-05-16 21:56
PR undergoing review!

**Comment by mountiny** [comment] 2023-05-17 13:34
@allroundexperts released in the `1.0.1` version

**Comment by mananjadhav** [comment] 2023-06-01 18:42
https://github.com/Expensify/react-native-key-command/pull/13 caused this regression. I have commented on the [PR](https://github.com/Expensify/react-native-key-command/pull/13#issuecomment-1572590760).

I don’t think we need a discussion but I do think we need a regression test for this one.  The test steps from the PR are good enough. What do you folks think @moutiny @stephanieelliott @allroundexperts ?

**Comment by stephanieelliott** [comment] 2023-06-05 20:56
I've paid @mananjadhav! Will create an issue for the regression test this evening, will leave this open til that's been completed.

**Comment by stephanieelliott** [comment] 2023-06-07 19:37
Issue for regression test: https://github.com/Expensify/Expensify/issues/289910

**Comment by mountiny** [comment] 2023-09-22 04:50
@thiagobrez Would you be able to work on this issue?

**Comment by thiagobrez** [comment] 2023-09-22 05:55
@mountiny hey! Im OOO until Tuesday, so I can take it on Wednesday if you want :D 

Also, I think you probably know this, but this issue is not related to the selection list refactor, its still in the old implementation

**Comment by mountiny** [comment] 2023-09-22 06:18
Thanks, well in that case maybe @MaciejSWM could have a look as he worked on this flow?

**Comment by mountiny** [comment] 2023-09-25 14:20
@thiagobrez wil lbe back from ooo soon and able to look into this one

**Comment by thiagobrez** [comment] 2023-09-27 15:20
Will start on this tomorrow 👍🏻

**Comment by thiagobrez** [comment] 2023-09-28 10:34
@mountiny @izarutskaya CMD + Enter is doing nothing in this case because there was no member selected. If you first select a member by pressing "Add to group", CMD + Enter will create the group and redirect to the chat. I believe it's working as expected.

See video below:
<video src="https://github.com/Expensify/App/assets/26878038/b047e326-a64e-4d58-954e-e110caee64a9" />

Also, please follow [this issue](https://github.com/Expensify/App/issues/18480), and [this discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1695715220767399), where the expected behavior for the Enter hotkey is being discussed (not exactly the same as here we're discussing CMD + Enter, but good to know)

**Comment by thiagobrez** [comment] 2023-09-28 10:38
cc @peterdbarkerUK @cristipaval

**Comment by thiagobrez** [comment] 2023-09-28 12:00
Previous video I sent seems to be broken, re-uploading here

https://github.com/Expensify/App/assets/26878038/8c6fb48a-4a1e-44fd-b895-5da0bb57d78a

**Comment by mountiny** [comment] 2023-10-02 22:22
Thanks @thiagobrez I agree that from your videos, that looks like expected behaviour

**Closed by mountiny** 2023-10-02 22:22 UTC
Labels: External, Daily, Bug
