### ISSUE TITLE
[$250] Infinite loading on members list on refreshing transfer owner success page & back to members list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40746] opened 2024-04-23 03:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
User is an admin of a collect workspace where the owner is someone else
1. Go to the workspace page and open the collect workspace
2. Open members page
3. Click on the owner
4. Click on "Transfer owner"
5. When the success page loads refresh the page
6. Tap back button twice till member listing page is displayed
7. Wait for few seconds (Note: Infinite loading appears)
8. Refresh the members listing page & wait for few seconds & observe endless loading occurs again

## Expected Result:
Transferred roles get updated & member listing is displayed

## Actual Result:
Infinite loading appears on WS members listing after refreshing the transfer owner success page & going back to members listing page

Note :
1. Issue reproducible on Android & iOS app as well when background app on member listing page & reopen it (Video attached for Android app)
2. Issue doesn't get resolved when members listing page is refreshed on step 7 as endless loading is seen again after few seconds
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/184ab6b6-a5f9-4764-bcce-1677d98d116b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e809f2c16a22ffe</li>
        <li>Upwork Job ID: 1782697621073084416</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-04-23 03:18
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mountiny** [comment] 2024-04-23 09:07
Exporting this and demoting it seems to be quite rare reproduction steps

**Comment by mallenexpensify** [comment] 2024-04-23 23:45
@fedirjh reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by robertjchen** [comment] 2024-04-29 08:28
Awaiting proposals

**Comment by mvtglobally** [comment] 2024-05-06 19:54
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-05-22 04:38
Issue not reproducible during KI retests. (Second week)

**Comment by robertjchen** [comment] 2024-05-23 12:46
Going to close this out for now given that we were unable to reproduce here:  https://github.com/Expensify/App/issues/40746#issuecomment-2123851010

**Closed by robertjchen** 2024-05-23 12:46 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
