### ISSUE TITLE
[HOLD for payment 2023-11-27] [$250] Dev: Web - Search page is not opening with transition when navigating with keyboard shortcut while on sign in page as anonymous user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29112] opened 2023-10-09 18:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.79.3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696789311359329

## Action Performed:
1. Create a public room AS user "A". Copy link to room.
2. Log out of app and open the link.
3. Click on Sign in Button on LHN.
4. Open Search page using keyboard shortcut (CTRL+K).

## Expected Result:
Search page should open with animation from right side same as Send Message page

## Actual Result:
Search page not opening with animation from right side

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details> n/a

<details>
<summary>Android: mWeb Chrome</summary>

</details> n/a

<details>
<summary>iOS: Native</summary>

</details> n/a

<details>
<summary>iOS: mWeb Safari</summary>

</details> n/a

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/03adea7b-f2e6-4c16-971d-b5bc47b435b0

</details> 

<details>
<summary>MacOS: Desktop</summary>

 

</details> n/a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c3e6703d5cc7641</li>
        <li>Upwork Job ID: 1711442560781221888</li>
        <li>Last Price Increase: 2023-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27503376</li>
<li>b4s36t4 | Contributor | 27503379</li>
<li>ishpaul777 | Reporter | 27503380</li>
</ul></li>
    </ul>
</details>

**Comment by shahzoab** [comment] 2023-10-09 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a modal is already opened before pressing the keyboard shortcut for the search modal, it does not appear with a transition.

### What is the root cause of that problem?
The animation has been intentionally disabled due to an animation glitch while using keyboard shortcuts.
`<Stack.Screen
    name="Search"
    component={ModalStackNavigators.SearchModalStackNavigator}
    options={{
        // Disable animation for this screen because it causes an animation glitch when using shortcuts
        animationEnabled: false, 
    }}
/>`

### What changes do you think we should make in order to solve the problem?
We can make animationEnabled true and then test if there's any glitch in the animation as mentioned in the code comment.
`<Stack.Screen
    name="Search"
    component={ModalStackNavigators.SearchModalStackNavigator}
    options={{
        animationEnabled: true,
    }}
/>`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by shahzoab** [comment] 2023-10-09 19:35
Contributor details
Your Expensify account email: shahzoab@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0197e6d2b5bd5f4085

**Comment by b4s36t4** [comment] 2023-10-09 22:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Web - Search page is not opening with transition when navigating with keyboard shortcut while on sign in page as anonymous user
### What is the root cause of that problem?

We intentionally stopped animation for the Search Screens cause of few issues with the animation when tried accessing using shortcut while doing navigation refactoring.

But at this point where we have a matured navigation & handling everything clearly we can enable the animation now.


### What changes do you think we should make in order to solve the problem?

Remove `options` from the `Screen` component here https://github.com/Expensify/App/blob/547e10dc09d40f3127411104018d2c7db90a4053/src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js#L35-L42


### What alternative solutions did you explore? (Optional)
We can leave this as it is done as intentional, although it happens with any RHP screens

**Comment by cead22** [comment] 2023-10-10 00:28
This looks like a simple bug, the solution looks simple, and it looks like this was written as is intentionally. Though it makes sense to update now that we have better navigation, the value of this isn't incredibly high for the end user, so I decreased the bounty

**Comment by shahzoab** [comment] 2023-10-10 08:27
On React Navigation docs they mentioned that `animationEnabled` defaults to `true` on iOS and Android, `false` on Web. So instead of removing `options` from the Screen component, we should set it to `true`.

**Comment by sakluger** [comment] 2023-11-02 19:17
> Well, I agree with you. But It seems that we have disabled the animation on purpose to address some issues

@fedirjh this point was address both in @b4s36t4's [proposal](https://github.com/Expensify/App/issues/29112#issuecomment-1754002748)...

> We intentionally stopped animation for the Search Screens cause of few issues with the animation when tried accessing using shortcut while doing navigation refactoring.
>
> But at this point where we have a matured navigation & handling everything clearly we can enable the animation now.

and in @cead22's comment:

> This looks like a simple bug, the solution looks simple, and it looks like this was written as is intentionally. Though it makes sense to update now that we have better navigation.

I think we can move forward with enabling the animation.

**Comment by MonilBhavsar** [comment] 2023-11-03 11:36
Looks good to me 👍

**Comment by sakluger** [comment] 2023-11-03 23:36
I'm OOO all next week, reassigning BZ label.

**Comment by b4s36t4** [comment] 2023-11-04 16:09
@fedirjh Here is the PR for this: https://github.com/Expensify/App/pull/30885

**Comment by peterdbarkerUK** [comment] 2023-11-15 10:55
QA ongoing

**Comment by sakluger** [comment] 2023-11-30 18:15
All paid out, thanks!

**Closed by sakluger** 2023-11-30 18:15 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
