### ISSUE TITLE
[$2000] Web - Login - Non-clickable LHN instead of "Abracadabra, you're logged in" page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20410] opened 2023-06-07 21:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
**Scenario 1**
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open an new tab and navigate to the staging link

**Scenario 2**
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open an new tab and navigate to the staging link
4. Verify the 2FA required page is displayed. Should have a message similar to "Please enter the two-factor authentication code where you are trying to sign in."
5. Navigate back to the original tab - Keep the second tab open
6. Verify the log in flow is now asking the user to enter the 2FA code
7. Enter the 2FA code
8. Verify the user can log in
9. Navigate to the secondary tab
10. Verify the "Abracadabra, you're logged in" page is displayed

**Scenario 3:**
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open an new INCOGNITO window and navigate to the staging link

**Scenario 4:**
1. Log out of the account
2. Enter the email on the email field and continue
3. Verify the there's a message below that says "Not [Email]?" and a link to "Go back"
4. Click on "Go Back"
5. Verify the email is still displayed in the email field
6. Continue with the log in flow
7. Navigate to the email inbox and look for the magic link email
8. Change the link to staging if needed
9. Open a new tab and paste the link in the URL

**Scenario 5:**
1. On the log in screen, enter a new account email
2. Navigate to the email inbox and open the validate email and copy the link
3. Modify the last portion of the link by a character, i.e.
In a text box - Formulate the URL by using the path obtained from step 3 http://staging.new.expensify.com/v/
- E.g if the original link was https://stagin.new.expensify.com/v/7453760/123884
change a single character > https://staging.new.expensify.com/v/7453760/12388**8**
4. Navigate to the compiled link
5. Verify you're redirected the "Magic code expired" page
6. Click on the "Request new magic code here"
7. Verify the user receives a new magic link
8. Change the link to staging, open a new tab and navigate to the link
## Expected Result:
For both scenarios: "Abracadabra, you're logged in" page should be displayed

## Actual Result:
For both scenarios: Non-clickable LHN (logged in pp) is displayed instead of "Abracadabra, you're logged in"" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
https://expensify.testrail.io/index.php?/tests/view/3490257
https://expensify.testrail.io/index.php?/tests/view/3490091
https://expensify.testrail.io/index.php?/tests/view/3490191
https://expensify.testrail.io/index.php?/tests/view/3490257
https://expensify.testrail.io/index.php?/tests/view/3490256

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Scenario 1**

https://github.com/Expensify/App/assets/93399543/0d371892-bca6-4a70-a51a-82709bf82baa

**Scenario 2**

https://github.com/Expensify/App/assets/93399543/68d0fff0-6373-46b8-a1dc-f2ac1f28819d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @natnael-guchima

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154116efc17a0ee13</li>
        <li>Upwork Job ID: 1666593984300412928</li>
        <li>Last Price Increase: 2023-07-01</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-06-07 23:07
Taking this over from @joelbettner

**Comment by roryabraham** [comment] 2023-06-07 23:15
Wasn't able to reproduce w/ scenario 1 in dev, but _was_ able to reproduce on staging. I think the difference was that the desktop deeplink was making it not work as expected?

**Comment by roryabraham** [comment] 2023-06-07 23:28
Was able to reproduce this in dev by removing [this dev environment check](https://github.com/Expensify/App/blob/576d2a94c8f046b2cf59edb8ea227b96853d34ad/src/components/DeeplinkWrapper/index.website.js#L40)

**Comment by roryabraham** [comment] 2023-06-07 23:50
So it seems like what's happening here is that we're redirecting to `new-expensify://URL` [here](https://github.com/Expensify/App/blob/eb9df258eed60f64c1f04eda99607fc568816341/src/components/DeeplinkWrapper/index.website.js#L98-L117), and that's causing the request to the transition page w/ the correct `exitTo` to be cancelled:

![image](https://github.com/Expensify/App/assets/47436092/1f3e3433-84ea-4e72-9cec-aa94c6f5b4cd)

and that seems to be why the flow is failing?

**Comment by roryabraham** [comment] 2023-06-07 23:52
I reproduced this on production. Demoting it from deploy blocker to regular bug.

**Comment by abdulrahuman5196** [comment] 2023-06-08 15:47
No initial proposals till now. Will circle back once we have.

**Comment by abdulrahuman5196** [comment] 2023-06-12 14:15
No proposals still

**Comment by abdulrahuman5196** [comment] 2023-06-14 19:51
@roryabraham There hasn't been any proposals for this issue. Could we raise the bounty?
I think the BZ here is @puneetlath  but I think he is out this week.

**Comment by roryabraham** [comment] 2023-06-17 01:31
Doubled the bounty

**Comment by abdulrahuman5196** [comment] 2023-06-18 16:45
@hoangzinh I tried even now on staging and I am getting a unresponsive spinner page with LHN.
There was also a another mention of similar issue in slack bug as well - https://expensify.slack.com/archives/C049HHMV9SM/p1686903317694329

Could you try with any of these steps as well?

**Comment by WoLewicki** [comment] 2023-06-21 11:11
Is it connected to the navigation refactor in a way that I can help you anyhow?

**Comment by abdulrahuman5196** [comment] 2023-06-21 20:11
We already have one proposal. But it needs some dive deep and more testing time since whenever we repro this bug, it is making the local web non-actionable after that. Will try to complete the review before tomorrow.

**Comment by abdulrahuman5196** [comment] 2023-06-23 15:24
Sorry for the delay @hoangzinh . It seems whenever i try to reproduce this issue, the local gets messed up and blocking me to focus on other priority issues as well. Will close it out this weekend by spending more time on it.

**Comment by abdulrahuman5196** [comment] 2023-06-26 19:49
@hoangzinh  Could you kindly check if you able to reproduce the issue with the slack tests you mentioned currently? It is only leading to this bug https://github.com/Expensify/App/issues/21258

Not of the steps is reproducible currently

**Comment by puneetlath** [comment] 2023-06-28 23:07
Just to make sure I understand. The bug is still happening? Or it's working as expected now?

**Comment by roryabraham** [comment] 2023-06-29 23:00
Requested a retest by Applause: https://expensify.slack.com/archives/C9YU7BX5M/p1688079598241329

**Comment by abdulrahuman5196** [comment] 2023-06-30 16:48
>Just to make sure I understand. The bug is still happening? Or it's working as expected now?

@puneetlath  The bug was transforming into different cases for sometime(since there where multiple scenarios in OP), could be due to external changes. As of now, the bug is transformed into a relatable state of this bug https://github.com/Expensify/App/issues/21258, where the view is frozen but the content is shown. (which is also fixed and recently deployed)
So I doubt this will be reproducible but not entirely sure if all related scenarios are fixed, so its a good thing we have requested for a re-test - https://github.com/Expensify/App/issues/20410#issuecomment-1613900475

**Comment by puneetlath** [comment] 2023-07-03 19:16
@hoangzinh please report this as a new bug in #expensify-bugs as it seems different from what this issue was originally about.

**Closed by puneetlath** 2023-07-03 19:16 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
