### ISSUE TITLE
[$250] Expense report - Expense report duplicates in another chat after approver submits report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45670] opened 2024-07-18 11:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4730487
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
precondition: approver and submitter are members of one workspace
1. Go to https://staging.new.expensify.com/
and log in as submitter
2. Navigate to the workspace chat
3. Create an expense but do not submit the report
4. Go to https://staging.new.expensify.com/
and log in as approver
5. Navigate to the workspace chat
6. Submit the report on behalf of the submitter

## Expected Result:
The report does duplicate in another workspace chat

## Actual Result:
The report duplicates in another workspace chat as like the approver submitted the report on their own but not as on behalf of submitter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ac3d4968-a21a-4017-a409-bb7db2a4abb3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d33a019fbdce84cb</li>
        <li>Upwork Job ID: 1813999616403125038</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by izarutskaya** [comment] 2024-07-18 11:06
We think this issue might be related to the #collect project.

**Comment by garrettmknight** [comment] 2024-07-18 18:09
Opening this up to `External`, but it might be BE.

**Comment by kabeer95** [comment] 2024-07-18 22:12
# Duplicate Expense Reports in Another Chat on Expensify

## Problem Statement

When an approver submits an expense report on Expensify, the report is duplicated in another chat, causing confusion and potential errors.

## Root Cause

The root cause of this issue is likely due to a misconfiguration in the Expensify settings or a bug in the chat system.

## Proposed Solution

To resolve this issue, I propose the following steps:

Check Expensify Settings: Verify that the Expensify settings are correctly configured, and the report submission process is properly set up.
Review Chat Configuration: Review the chat configuration to ensure that reports are not being duplicated or forwarded to another chat unintentionally.
Check Report Submission History: Check the report submission history to identify if there are any duplicate submissions or errors.
Test and Validate: Thoroughly test the expense report submission process on Expensify to ensure that reports are not duplicated in another chat.
Expensify Settings to Check

Chat Settings: Verify that the chat settings are correctly configured, and reports are not being duplicated or forwarded to another chat.
Report Submission Settings: Check the report submission settings to ensure that reports are being submitted correctly and not duplicated.
Approval Workflow: Review the approval workflow to ensure that reports are not being duplicated or sent to multiple approvers.
Troubleshooting Questions

Are there any custom chat integrations or workflows set up in Expensify?
Are there any duplicate report submission errors in the Expensify logs?
Has the approver submitted the report multiple times, causing the duplication?
Implementation Code (JavaScript)

javascript
```
// Example of correct report submission API call
fetch('/api/reports/' + reportId + '/submit', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    approverId: approverId
  })
})
.then((response) => {
  // Handle successful report submission
  console.log('Report submitted successfully!');
})
.catch((error) => {
  // Handle error and prevent duplicate report submission
  console.error('Error submitting report:', error);
});

// Example of chat integration to prevent duplicate reports
const chatIntegration = {
  async sendMessage(reportId, approverId) {
    try {
      // Check if report is already submitted in chat
      const existingReport = await getReportFromChat(reportId);
      if (existingReport) {
        console.log('Report already submitted in chat. Skipping duplicate submission.');
        return;
      }

      // Submit report to chat
      await submitReportToChat(reportId, approverId);
      console.log('Report submitted to chat successfully!');
    } catch (error) {
      console.error('Error submitting report to chat:', error);
    }
  }
};

```
### Alternative Solutions

If the above solution does not resolve the issue, we could explore alternative solutions, such as:

Implementing a unique report ID system to prevent duplicates
Using a different expense reporting tool or API
Contacting Expensify support for further assistance

**Comment by garrettmknight** [comment] 2024-07-31 17:06
Waiting for a volunteer

**Comment by garrettmknight** [comment] 2024-08-06 21:15
Still waiting for a volunteer.

**Comment by garrettmknight** [comment] 2024-08-07 10:44
Just retested and I'm having trouble reproducing.

**Comment by trjExpensify** [comment] 2024-08-09 02:03
Putting this in hot picks for vis.

**Comment by garrettmknight** [comment] 2024-08-12 19:24
Tested again, couldn't reproduce. Closing

**Closed by garrettmknight** 2024-08-12 19:24 UTC
Labels: Weekly, Internal, Bug, retest-weekly
