### ISSUE TITLE
[HOLD for payment 2023-11-17] [$500]  Chat – Page crashes when open attachment preview in any chat and reload the page (Ctrl+R)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30998] opened 2023-11-07 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log into NewDot with any account
2. Open any chat with an attachment
3. Click the attachment to open the preview modal
4. Reload the page (CTRL+R)

## Expected Result:
Opens reloaded page

## Actual Result:
Page crashes when open attachment preview in any chat and reload the page (CTRL+R)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09fd6368-bdfc-46d8-93b1-7d192dcf7b12

[log.txt](https://github.com/Expensify/App/files/13281851/log.txt)

Production

https://github.com/Expensify/App/assets/78819774/f5be66a6-4509-410e-9498-e63d1951f113

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172058ac50f9604bf</li>
        <li>Upwork Job ID: 1721905825731407872</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27559652</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by mountiny** [comment] 2023-11-07 15:02
Making this external to get more eyes on this

**Comment by erquhart** [comment] 2023-11-07 15:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when loaded to attachment preview.

### What is the root cause of that problem?
`parentReportActions` can be null, and we're attempting  to access a property on it:
https://github.com/Expensify/App/blob/2827cf0aae6df5948833e8847bc818f83c0748c5/src/components/LHNOptionsList/OptionRowLHNData.js#L78

### What changes do you think we should make in order to solve the problem?

Check to ensure `parentReportActions` is defined first:
```js
    const parentReportAction = parentReportActions && parentReportActions[fullReport.parentReportActionID];
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by situchan** [comment] 2023-11-07 15:13
@GItGudRatio @erquhart 
Thanks for proposals. Do you have constant repro step?
I am not able to reproduce following repro step in OP here.


https://github.com/Expensify/App/assets/108292595/aa12d6f5-6d1a-4d7b-bf86-942cbc5cf9ee

**Comment by mollfpr** [comment] 2023-11-07 15:20
@mountiny I think @situchan has this; I will not be available in an hour, so I will unassign myself.

**Comment by erquhart** [comment] 2023-11-07 15:20
I dropped my proposal, @GItGudRatio's was better and closer to actual root cause.

**Comment by erquhart** [comment] 2023-11-07 15:21
@situchan you have to click the attachment to focus on it, then reload

**Comment by TMisiukiewicz** [comment] 2023-11-07 15:47
can confirm @GItGudRatio proposal should work fine

**Comment by mountiny** [comment] 2023-11-07 16:31
As in other instances, given the PR author of the regression is available, they will raise a PR witha fix but we will partially compensate the proposal which helped to identify the correct fix.

**Comment by DylanDylann** [comment] 2023-11-07 17:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Page crashes when open attachment preview in any chat and reload the page (Ctrl+R)
### What is the root cause of that problem?
We pass a null value here (parentReportActions: null)
https://github.com/Expensify/App/blob/ffc2f2c8c9cbd66e6e7fec2f295f516cd7e7c922/src/components/LHNOptionsList/LHNOptionsList.js#L153

It causes a crash because we are using `parentReportActions[fullReport.parentReportActionID];`  


Let's see the current logic in the LHNOptionsList
https://github.com/Expensify/App/blob/ffc2f2c8c9cbd66e6e7fec2f295f516cd7e7c922/src/components/LHNOptionsList/LHNOptionsList.js#L139

Because some reports don't have `parentReportID`, `itemFullReport.parentReportID` will be `undefined`

It means that we are getting: 
```
const itemParentReportActions = reportActions[`reportActions_undefined`];
```

`itemParentReportActions` will be null because we have `reportActions_undefined : null` in reportActions Object. See below log 


<img width="402" alt="Screenshot 2023-11-08 at 00 25 08" src="https://github.com/Expensify/App/assets/141406735/975de462-bbe4-4d7a-8489-ff4d7a3aa069">

**The RCA** is that somewhere in App, we are using  `Onyx.set('reportActions_${reportId}, null ` without checking `reportId` is `undefined`
### What changes do you think we should make in order to solve the problem?
We need to check reportId and we only set it to ONYX if It is valuable 

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-08 09:45
@situchan @TMisiukiewicz From my investigation, It seems the RCA in @GItGudRatio's proposal isn't corrrect. Could you help to take a look at my proposal.
cc @mountiny

**Comment by situchan** [comment] 2023-11-08 09:47
> The RCA is that `somewhere` in App, we are using `Onyx.set('reportActions_${reportId}, null`  without checking reportId is undefined

@DylanDylann do you know that `somewhere`?

**Comment by mountiny** [comment] 2023-11-08 15:40
Fixed in staging

**Comment by laurenreidexpensify** [comment] 2023-11-20 12:16
Payment Summary

C+ - @situchan payment issued in Upwork $500
Contributor - @TMisiukiewicz does not require payment (Contractor)

**Comment by laurenreidexpensify** [comment] 2023-11-20 12:17
Final Steps: @situchan to complete checklist and then we can close out

**Comment by situchan** [comment] 2023-11-20 12:31
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30242
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30242/files#r1399136571
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was caught by Applause - Internal Team so no need additional regression test

**Closed** 2023-11-21 10:37 UTC
Labels: External, Engineering, Daily, Weekly, Awaiting Payment, Bug

**Comment by situchan** [comment] 2023-12-06 06:36
@laurenreidexpensify I haven't received payment yet. Can you please check?
