### ISSUE TITLE
[$500] Report-When opening reports in lhn, if no activity in report, focus is on compose&keypad opens

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31615] opened 2023-11-21 11:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on reports (which don't have any activity in it.)
3. Note focus is on compose & keypad opens.
4. Tap on a report (which have any activity in it.)
5. Note keypad does not opens and no focus is on compose

## Expected Result:
When opening reports in lhn , focus must not be on compose & keypad must not open.

## Actual Result:
From LHN, If opening report which has activity, keypad not opens and no focus is on compose. But when opening reports in lhn when no activity in report, focus is on compose & keypad opens.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/93cfea72-9fe9-47f7-9153-92c1773a42c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bd7a3167a4dd20f</li>
        <li>Upwork Job ID: 1726924123648757760</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-27 18:05
@ntdiary this is not a new chat, it's a chat with comments only and no activities, eg., IOUs.

**Comment by mallenexpensify** [comment] 2023-11-27 23:50
Unable to test right now, will look into tomorrow

**Comment by mallenexpensify** [comment] 2023-11-28 19:22
@ntdiary how'd you find/know [that link](https://github.com/Expensify/App/pull/4921#discussion_r718023887)?!?!?!  

I was able to reproduce and only for a new chat in a room that doesn't have any comments (existing chats with content don't show the keyboard when opening for me, iOS > Safari). 

So.. I'm going to close this. cc'ing @parasharrajat since he posted the comment linked above, in case he has additional context. Thx

**Closed by mallenexpensify** 2023-11-28 19:22 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by erquhart** [comment] 2023-11-28 19:44
@mallenexpensify you have to do it with a chat that has _only comments_.

- make a new chat
- add a single comment
- navigate away from the chat and back to it

**Comment by erquhart** [comment] 2023-11-28 21:24
@mallenexpensify okay I'm seeing the same now - looking at the server responses, I'm betting the backend fix recommended in https://github.com/Expensify/App/issues/31243#issuecomment-1807061189 is in place now.
