### ISSUE TITLE
[$1000] [Bug] IOS - Chat - Password - Save button bounces when moving from one line to another

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11057] opened 2022-09-16 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in any account
3. Navigate to settings by clicking on the user avatar over LHN
4. Click on change password
5. Switch from one field to another

## Expected Result:
The button should not twitch when switching from one field to another

## Actual Result:
Save button bounces when moving from one line to another

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190664093-0c88f68d-06d4-4806-8f42-445258bc8a9e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Testing 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2022-09-16 21:43
Seems like something easy for external work. However I'm pretty sure it's due to the keyboard issues that we're handling internally (the place it jumps to/from is where, on my phone, autofill suggestions are shown, and so I think the jump is the phone registering it as a password blank and seeing if it has anything to fill it with - that's not showing in the attached video here but it's the exact place and so I think the keyboard just isn't showing up).

I'm going to move to weekly, and put a hold on it for the Keyboard Initiative.

**Comment by dangrous** [comment] 2022-09-28 19:09
This is on hold, not overdue

**Comment by dangrous** [comment] 2022-10-07 16:47
Holding for keyboard push

**Comment by dangrous** [comment] 2022-10-17 18:17
Still on hold

**Comment by dangrous** [comment] 2022-10-26 19:57
Still on hold

**Comment by miljakljajic** [comment] 2022-11-02 15:57
[Posted to Upwork.](https://www.upwork.com/ab/applicants/1587806073372385280/job-details)

**Comment by JmillsExpensify** [comment] 2022-11-02 19:48
@miljakljajic  Given that we're still early and no proposals have been accepted, I'm assigning myself per the new BZ process: https://stackoverflow.com/c/expensify/questions/14597/14598#14598.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:21
Contributors - this issue is still open and we're accepting proposals!

**Comment by JmillsExpensify** [comment] 2022-11-08 19:50
Still waiting for proposals. Increasing the price to $500.

**Comment by dangrous** [comment] 2022-11-11 21:40
Waiting for proposals.

**Comment by JmillsExpensify** [comment] 2022-11-14 18:28
We've hit another week with no proposals, so I'm raising the price to $1,000.

**Comment by bondydaa** [comment] 2022-11-15 15:33
will take a look into this today

**Comment by bondydaa** [comment] 2022-11-15 23:18
testing this on 1.2.27-4 on web, desktop and haven't been able to reproduce yet.

Tested on the following iOS devices and OS versions:
iOS 15.5 iPhone 13
iOS 15.5 iPhone SE

but couldn't reproduce either. Do we know if there was a specific iOS version that this didn't work on?

**Comment by tungmt** [comment] 2022-11-16 00:19
I think it is iOS issue only. I can reproduce this issue with both iOS app/web (firefox) on all my devices:
iOS 16.1 iPhone 13 Pro
iOS 15.4.1 iPhone xs max
iOS 14.4.2 iPhone 6s

It is not happen in other platform when I tested it.

https://user-images.githubusercontent.com/7497751/202052384-8050c1f0-64b2-4048-9aef-81932c865ce0.MP4


https://user-images.githubusercontent.com/7497751/202052400-f3777a86-7aae-4b72-8379-2ec3424536c3.MP4


https://user-images.githubusercontent.com/7497751/202052404-e35509f5-564d-44ce-a77e-eadd779fc580.MP4

**Comment by bondydaa** [comment] 2022-11-16 15:26
Spoke with @JmillsExpensify we're actually just going to close this. We are in the process of removing passwords all together from the platform so this view/page will be removed entirely sooner rather than later anyways.

**Closed by bondydaa** 2022-11-16 15:26 UTC
Labels: Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2022-11-16 15:29
Yes, thank you so much @bondydaa for raising this. Apologies I missed this myself when taking over the issue. 🙏🏼
