### ISSUE TITLE
[HOLD for payment 2024-03-20] App loads chats on the left with tag list on the right when refreshing tag list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37848] opened 2024-03-06 23:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Collect workspace with tags.
- The tags include tag in Parent: Child format and some regular 

1. Go to staging.new.expensify.com
2. Go to Workspace settings > Collect workspace.
3. Go to Tags.
4. Refresh the page.

## Expected Result:
Workspace settings on the left are preserved.

## Actual Result:
App loads chats on the left with tag list on the right.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/0a946eee-059b-4028-8e51-a6a240f70d8d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-03-07 03:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When refreshing on the workspace tags page, the left page shows LHN while the central page shows the workspace tags page.

### What is the root cause of that problem?
When we refresh the page, it will call `getAdaptedState` and see what navigator is inside the nav stack. In our case, we have a central pane (workspace tags page).
https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L253-L254

It will try to find the matching bottom tab navigator with the current central pane.
https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/libs/Navigation/linkingConfig/getMatchingBottomTabRouteForState.ts#L16-L20

However, we don't have a mapping for the workspace tags page and the bottom tab navigator page.
https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/libs/Navigation/linkingConfig/TAB_TO_CENTRAL_PANE_MAPPING.ts#L4-L18

So, it will default to HOME, that is the LHN.
https://github.com/Expensify/App/blob/ffa731a28a2d1402148eef54e51d86fbb64321fe/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L52-L63

### What changes do you think we should make in order to solve the problem?

Add the mapping for workspace tags page.
```
[SCREENS.WORKSPACE.INITIAL]: [
    ...
    SCREENS.WORKSPACE.TAGS,
],
```

**Comment by luacmartins** [comment] 2024-03-07 13:13
@waterim since this came from the Tags PR. Let's fix this as part of the next settings PR.

**Comment by waterim** [comment] 2024-03-07 14:56
@luacmartins this one is already fixed in settings PR!

**Comment by luacmartins** [comment] 2024-03-07 14:58
Nice one!

**Comment by luacmartins** [comment] 2024-03-27 00:53
IMO there's no need for the BZ checklist since this is a new feature in development

**Comment by luacmartins** [comment] 2024-04-01 16:23
I think we can close this one!

**Closed by luacmartins** 2024-04-01 16:23 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
