### ISSUE TITLE
[$1000] Icons in VBA flow are very hard to see or white in dark mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13132] opened 2022-11-29 15:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com (Web)
2. Sign into a valid account
3. Click on Profile > Workspace > Connect bank > Connect manually (First issue here on Routing page)
4. Enter routing information and proceed to the next page
5. Scroll down to the "Incorporation date" section and locate the calendar icon on the right of the input field (Second issue here)

## Expected Result:
1. The background of the routing image should match the dark theme
2. The calendar icon should be a color that is easily seen in the dark theme
3. When the user taps the dropdown, all text should be clear and readable

## Actual Result:
1. The background of the routing image is white and does not match the current theme
2. The calendar icon is black and very hard to see, an average user may miss this entirely if they do not know its there
3. When the user taps the dropdown, all text is black on a dark background and hard to understand

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.33-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1067" alt="Screenshot 2022-11-29 at 9 55 30 AM" src="https://user-images.githubusercontent.com/43996225/204567066-81348d3b-4262-4176-871b-bed2ec83aca7.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669696874240429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01bad5604e9c4055b5
- Upwork Job ID: 1597651373329428480

**Comment by luacmartins** [comment] 2022-11-29 17:44
Gonna reassign to myself since Maria might be out for the day.

**Comment by luacmartins** [comment] 2022-11-29 17:56
@dhairyasenjaliya solution one looks good! Can you get a PR up soon since this is a deploy blocker?

**Comment by dhairyasenjaliya** [comment] 2022-11-29 17:58
Hey @luacmartins sure creating PR now

**Comment by luacmartins** [comment] 2022-11-29 17:58
Cool, I'll assign you to this issue and get the process started! Thanks!

**Comment by luacmartins** [comment] 2022-11-29 17:59
Going to speed this one up since it's a deploy blocker

**Comment by dhairyasenjaliya** [comment] 2022-11-30 16:48
@mvtglobally both are separate issue I logged here https://expensify.slack.com/archives/C049HHMV9SM/p1669787031782639?thread_ts=1669787031.782639&cid=C049HHMV9SM

**Comment by luacmartins** [comment] 2022-11-30 16:51
@mvtglobally please log another issue for https://github.com/Expensify/App/issues/13132#issuecomment-1332452883

**Comment by mollfpr** [comment] 2022-12-01 00:06
@tjferriss Im haven't reviewed anything, so I’m not eligible for compensation

**Comment by dhairyasenjaliya** [comment] 2022-12-01 10:28
@tjferriss Is this eligible for a 50% bonus since PR merged within an hour

**Comment by tjferriss** [comment] 2022-12-01 19:34
@mollfpr my mistake. 

@dhairyasenjaliya yes, you are eligible for the bonus. Can you please apply to the Upworks job?: https://www.upwork.com/jobs/~01bad5604e9c4055b5

**Comment by tjferriss** [comment] 2022-12-01 19:35
Checklist to close the issue now that the PR is merged:

- [ ] If this bug was caught on production, add or update the [regression tests](https://expensify.testrail.io/index.php?/dashboard) ([SO for How do I get new regular regression QA tests added?](https://stackoverflow.com/c/expensify/questions/363/364#364)) so that the same bug can’t reach production again and link to the updated test here:
- [ ] Link to the PR that caused the bug:
- [ ] Comment on the offending PR to notify the author and reviewers that the PR caused this bug.
- [ ] Reduce the pay of the C+ on the offending PR if they should have caught the regression (ie. they overlooked a step/checkbox that led to the regression.)
- [ ] Start a discussion in #contributor-plus about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.
- [ ] Complete payment to @contrib1, @cplus1, and @issureporter1 [after 7 days](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions).

**Comment by dhairyasenjaliya** [comment] 2022-12-02 00:53
@tjferriss applie along with bug reporting bonus as well

**Comment by tjferriss** [comment] 2022-12-05 19:41
@dhairyasenjaliya you've been hired.

**Comment by luacmartins** [comment] 2022-12-05 21:19
@tjferriss checklist is done on my end.

**Comment by tjferriss** [comment] 2022-12-06 23:17
I've created the regression test issue and paid out @dhairyasenjaliya. I'll close this out once the regression test has been added.

**Comment by tjferriss** [comment] 2022-12-14 22:07
Applause confirmed we don't need an additional regression test for this issue so we're good to close this out. Thanks everybody.

**Closed by tjferriss** 2022-12-14 22:07 UTC
Labels: Reviewing, External, Engineering, Daily
