### ISSUE TITLE
[$500] Web - Error in JS console when open hidden profile page via link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29368] opened 2023-10-11 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Found when executing PR : https://github.com/Expensify/App/pull/29277

**Version Number:** v1.3.81-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Precondition: User A and User B should have no prior chat history

As User A:
1. Open a tab and sign in as User A
2. Click on 'Profile avatar' > Share code > Copy URL to clipboard

As User B:
1. Open a tab and sign in as User B
2. Paste the URL to the address bar
3. Press enter

## Expected Result:
No errors appear in the JS console.

## Actual Result:
There are some errors in the JS console when open hidden profile page via link.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/9ca0d80c-7bf1-4669-94eb-6082dd67f37b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01882dc64b752af177</li>
        <li>Upwork Job ID: 1712190422998413312</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

[utest-dl.s3.amazonaws.com_12102_26469_432782_6233377_bugAttachment_Bug6233377_1697046806224%21Error_in_JS_console.log_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231011T193442Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Cr.txt](https://github.com/Expensify/App/files/12873929/utest-dl.s3.amazonaws.com_12102_26469_432782_6233377_bugAttachment_Bug6233377_1697046806224.21Error_in_JS_console.log_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231011T193442Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz-Cr.txt)

**Comment by b4s36t4** [comment] 2023-10-11 19:49
Dupe of #29116

**Comment by stephanieelliott** [comment] 2023-10-17 01:48
Agree this is a dupe

**Closed by stephanieelliott** 2023-10-17 01:48 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
