### ISSUE TITLE
[$250] Expense - Infinite and flickering skeleton when submitting expense to user after relogin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42675] opened 2024-05-27 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense to a user with no previous chat.
3. Send a message to another chat (important).
4. Log out.
5. Log in.
6. Go to FAB > Submit expense > Manual.
7. Submit another expense to the same user in Step 2.
## Expected Result:
The chat report with user in Step 2 will not turn to skeleton.
## Actual Result:
The chat report with user in Step 2 turns to infinite skeleton and it flickers.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/8dbee774-6bea-4182-aaa4-b92697c8b662

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f3d491c2454a0c1</li>
        <li>Upwork Job ID: 1795228901046882304</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by kavimuru** [comment] 2024-05-27 21:47
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-05-27 21:47
We think this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-05-28 03:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The chat report with user in Step 2 turns to infinite skeleton and it flickers.

### What is the root cause of that problem?
After we logout and login again and don't open the chat with the user, we don't have the created action of this report. And then when we submit a new request, BE returns another report preview action but the optimistic report preview action isn't cleared that makes `OpenReport` API is called infinitely. The reason is the newest action is the optimistic report preview action that doesn't link with the previous action of the report that makes `hasCreatedAction` is still `false` and `isLoadingInitialReportActions` is changed from `false` to `true` each time we call `OpenReport` API. 

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionsView.tsx#L422-L424
### What changes do you think we should make in order to solve the problem?
1. When we submit an expense, BE should return the data of optimistic report preview action as `null`. The `reportActionID` of this action is `reportPreviewReportActionID` param that we passed to `RequestMoney` API. So the optimistic report preview action can be cleared and then current action can be displayed.

2. We should update the dependency of the `useEffect` [here](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionsView.tsx#L407) to prevent calling many time
- update `reportActions` here to `reportActions.length` since we only get the length in this `useEffect`
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionsView.tsx#L428

- update `report` here to `report?.chatType` since we only use chat type to check in `isInvoiceRoom` function
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionsView.tsx#L435

### What alternative solutions did you explore? (Optional)
NA

**Comment by jayeshmangwani** [comment] 2024-05-28 16:29
@nkdengineer Are you able to reproduce this issue reliably from the latest main branch? I have tried with a few users, but whenever I try to send the submit expense a second time after logging out and logging in, getting the `Unexpected error creating this chat, please try again later. There is a previously existing chat between these users.` Error.
<img width="1312" alt="Screenshot 2024-05-28 at 9 54 44 PM" src="https://github.com/Expensify/App/assets/35371050/1f79589d-3e05-4688-871e-ec235b69f236">

**Comment by nkdengineer** [comment] 2024-05-29 04:52
@jayeshmangwani You need to invite this user to workspace to have the full personal detail of the user. And then on the second time you submit a expense for this user via FAB this error will not happen.

**Comment by jayeshmangwani** [comment] 2024-05-29 07:18
> You need to invite this user to workspace to have the full personal detail of the user. And then on the second time you submit a expense for this user via FAB this error will not happen.

Tried but got the same result as before and was eventually not able to reproduce the original issue mentioned in the description

**Comment by jayeshmangwani** [comment] 2024-05-29 07:19
@kavimuru Is there any prerequisite to reproduce this issue? currently, I am not able to reproduce it easily.

**Comment by nkdengineer** [comment] 2024-05-29 07:31
> Are you able to reproduce this issue reliably from the latest main branch? I have tried with a few users, but whenever I try to send the submit expense a second time after logging out and logging in, getting the Unexpected error creating this chat, please try again later. There is a previously existing chat between these users. Error.

@jayeshmangwani When you submit the second expense, I guess you still need to enter the email of user in participant page (because you don't have the full personal detail of that user) that makes a new report is created and then when BE returns data the current report is returned which makes the error appears.

**Comment by jayeshmangwani** [comment] 2024-05-29 07:33
Yes, I understand why I am getting the error on the chat; I am saying I cannot reproduce the original issue thats in the description.

**Comment by jayeshmangwani** [comment] 2024-05-29 07:34
@nkdengineer, [from the video](https://github.com/Expensify/App/issues/42675#issuecomment-2136721521), I didn't get what you are trying to convey.

**Comment by nkdengineer** [comment] 2024-05-29 07:39
@jayeshmangwani Sorry I upload wrong video, updated new video for reproducing this bug.

**Comment by jayeshmangwani** [comment] 2024-05-30 16:27
@nkdengineer can you please add more details for this line `BE returns another report preview action but the optimistic report preview action isn't cleared that makes OpenReport API is called infinitely`, What data does `another report preview` contains? And How not clearing the optimistic report preview action is related to infinite loop ?

**Comment by nkdengineer** [comment] 2024-05-31 08:26
> can you please add more details for this line BE returns another report preview action but the optimistic report preview action isn't cleared that makes OpenReport API is called infinitely, What data does another report preview contains

@jayeshmangwani the another report preview action here is the correct report preview action that will contain both the first and the second request that we created.

>  And How not clearing the optimistic report preview action is related to infinite loop ?

If we don't clear the optimistic report preview, this function will always return the report actions array that only contain the optimistic report preview action because this action doesn't link to any previous report action. 

https://github.com/Expensify/App/blob/25c54389f5e903d9503ce97de7c29356ce81e1d4/src/pages/home/ReportScreen.tsx#L257

And then `OpenReport` API is called infinitely because `hasCreatedAction` is `false` and `isLoadingInitialReportActions` is changed from `true` to `false` after a `OpenReport` API is complete
https://github.com/Expensify/App/blob/25c54389f5e903d9503ce97de7c29356ce81e1d4/src/pages/home/report/ReportActionsView.tsx#L407

**Comment by jayeshmangwani** [comment] 2024-06-04 12:59
Not Overdue, we have a proposal but I am trying to reproduce this issue relatively, i was able to reproduce this issue always but not always, Issue look BE, before logout and login it is working fine, will see what API causing this

**Comment by jayeshmangwani** [comment] 2024-06-05 21:13
Thanks @nkdengineer , After testing with some new users, I feel the same that Issue can be fixed from the [BE](https://github.com/Expensify/App/issues/42675#:~:text=When%20we%20submit%20an,action%20can%20be%20displayed.)

Approving to assign an internal engineer since this looks a [BE issue](https://github.com/Expensify/App/issues/42675#issuecomment-2141480117)

🎀👀🎀

**Comment by puneetlath** [comment] 2024-06-11 16:10
Sorry @jayeshmangwani I don't totally understand the back-end issue. Mind explaining what you think the back-end needs to return differently?

**Comment by jayeshmangwani** [comment] 2024-06-13 12:03
> Mind explaining what you think the back-end needs to return differently?

@puneetlath exactly I am not sure at the moment what BE needs to send differently (or BE expects the other value from the RequestMoney params), I've tried with many users, and the issue happens not only with new users but also with old users' IOUs. and another issue I can see is participant's data is also null (not sure if this will solved after infinite loop)
<img width="574" alt="Screenshot 2024-06-13 at 5 10 10 PM" src="https://github.com/Expensify/App/assets/35371050/6c0de185-2961-4a93-a2d7-6341c84b97ee">

However, I suspect that `iouReportID` param is the culprit here, but that can be verified from the backend logs or by checking what value the RequestMoney API expects for iouReportID value for the already created iOU. 

Let me explain a bit this scenario:

1. With a user A, I have an expense request that works fine (iouReportID: 643718661816580).
2. I sent another one from the chat `+ > Submit expense` (iouReportID: 643718661816580) that works fine, no infinite loop.
3. Now, clear the cache from TroubleShoot.
4. From the FAB, I sent an expense report to the same user A from step 1 (but with iouReportID: 6614901684858704). Here, the iouReportID is different, And here I think we need to confirm what BE expects that value of iouReportID

And reason here @nkdengineer mentioned here for the [infinite call](https://github.com/Expensify/App/issues/42675#:~:text=And%20then%20OpenReport%20API%20is%20called%20infinitely%20because%20hasCreatedAction%20is%20false%20and%20isLoadingInitialReportActions%20is%20changed%20from%20true%20to%20false%20after%20a%20OpenReport%20API%20is%20complete) is correct

https://github.com/Expensify/App/blob/1883f99e14194d0d8462955d93c2ad0770a7e8a9/src/pages/home/report/ReportActionsView.tsx#L252

hasCreatedAction initially is true as actionName value is `CREATED`, but when sent the expense report from the FAB (RequestMoney API call), it changes to `REPORTPREVIEW` and it causes the loop

**Comment by jayeshmangwani** [comment] 2024-06-13 12:19
This PR https://github.com/Expensify/App/pull/41962 has some issues listed in the 'Fixed Issues' section that look similar to this issue.

**Comment by puneetlath** [comment] 2024-06-24 20:52
Thanks for the info @jayeshmangwani! I will look into this soon.

**Comment by puneetlath** [comment] 2024-07-03 19:52
It's still on the list.

**Comment by mvtglobally** [comment] 2024-07-19 03:20
Issue not reproducible during KI retests. (First week)

**Comment by jayeshmangwani** [comment] 2024-07-23 13:36
It looks like the infinite flicker issue is solved now. I am also not able to reproduce it.

**Comment by puneetlath** [comment] 2024-07-23 14:21
Oh cool! I'll go ahead and close this out then.

**Closed by puneetlath** 2024-07-23 14:21 UTC
Labels: External, Monthly, Help Wanted, Bug
