### ISSUE TITLE
[$2000] App stops working when sending a message with an attachment simultaneously.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20067] opened 2023-06-02 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Go to any chat > Enter a message with an attachment (the attachment should be included in the same message as the text, not in a follow-up message)
3. Notice that you cannot perform any other action
## Expected Result: 
App should have kept working.
## Actual Result: 
App stopped working

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c4e8baed-a4e6-4f5d-9680-65c2382c7a10

https://github.com/Expensify/App/assets/43996225/8d4ff973-1429-40d0-8c46-84f18659157f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685344677331179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128175cf1498c8359</li>
        <li>Upwork Job ID: 1668221239066378240</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-06-05 16:11
The app _looks_ like it's working to me when I review the videos above. I've asked in Slack for clarity around the behavior so I can reproduce it.

**Comment by johncschuster** [comment] 2023-06-06 15:01
From Slack:

> After performing all the steps in the OP, you won't be able to perform any other action.

Updating the repro steps to include that

**Comment by johncschuster** [comment] 2023-06-08 15:51
@daraksha-dk I cannot reproduce this. I went to a chat, sent an image, and then sent a follow-up message, and that message was successful. Can you clarify what else we need to do to reproduce this?

**Comment by johncschuster** [comment] 2023-06-09 17:33
Bumped in Slack

**Comment by johncschuster** [comment] 2023-06-10 12:23
Ah, got it. So, the _same_ message should contain text and an image, rather than one line having text, and the following line being an image. I'll test that and report back.

Thanks for clarifying!

**Comment by johncschuster** [comment] 2023-06-12 11:37
Ok! I have reproduced the behavior. Triaging!

**Comment by spcheema** [comment] 2023-06-12 11:47
Draft proposal

**Comment by spcheema** [comment] 2023-06-12 12:28
@johncschuster it's not reproducible on prod. Just install new app on my iPhone and no freezing. 

Similarly no issue found on simulator.

**Comment by johncschuster** [comment] 2023-06-13 13:54
@spcheema did you follow step 2 _explicitly_? I was able to reproduce it by following those exact steps.

**Comment by spcheema** [comment] 2023-06-13 23:53
@johncschuster Nah... both attachment and text in the same message (not follow up)

And I can't reproduce it

**Comment by johncschuster** [comment] 2023-06-14 11:17
Thanks for clarifying that, @spcheema! I'll try reproducing it again shortly to see if the behavior persists.

**Comment by johncschuster** [comment] 2023-06-15 11:33
Hmm... I can't reproduce it now. @daraksha-dk, can you give it another try?

**Comment by johncschuster** [comment] 2023-06-20 15:42
Looks like we haven't gotten any proposals for this one. I think we'll likely need to double the bounty.

**Comment by pasyukevich** [comment] 2023-06-23 14:02
I have reproduced it on a physical device within an app version that is currently in the app store. 

Now I'm checking with the latest version from the "main" branch and physical device. (Not reproduced in the simulator with this app version)

**Comment by madmax330** [comment] 2023-06-26 10:36
@pasyukevich thanks, if the issue is not reproducible on the latest version I would not worry about it because it was probably fixed somewhere else.

**Comment by pasyukevich** [comment] 2023-06-26 11:31
@madmax330 The issue is reproduced when using a newer version in the production environment. 
Tested with the same version from the branch locally, the issue is not reproduced. The same situation with the installation of the physical device - the issue does not reproduce with the development build. 

I assumed that this connected only with the build that is created for production. 

I continue my investigation by looking for the root cause.

**Comment by madmax330** [comment] 2023-06-26 11:38
Thanks 👍🏽

**Comment by pasyukevich** [comment] 2023-06-27 08:41
I found a way to reproduce this behavior locally on the physical device with some logs. 

I continue my investigation by looking for the root cause.

**Comment by johncschuster** [comment] 2023-06-27 11:54
Thanks for the deep dive, @pasyukevich! Is there anything you need from us to keep the urgency up on this one? This issue is just about to be four weeks old, which will require us to take it internal. I'd hate to do that if you've got a solution in mind.

**Comment by pasyukevich** [comment] 2023-06-28 10:12
@johncschuster 
At this moment I don't have straight forward solution. 
Moreover, this bug stopped constantly reproducing yesterday in the middle of the day. Now it is reproducing from time to time.
I'm able to reproduce it only on the production build or local build with the release scheme. 

**Here are my assumptions about the root cause:**
  1. It starts from a problem or behavior on the backend side on image uploading with text (when I was able to reproduce it I receive a lot of such errors: _nw_connection_add_timestamp_locked_on_nw_queue [C26] Hit maximum timestamp count, will start dropping events_ )
  2. After it modal is closed we are not able to interact with the app, the keyboard is not showing, but updates are still coming if smth send to this chat. I guess that in case of an error on BE, the app is just not able properly close the modal and we see a transparent layer that blocks any interactions with the app. 
  
I continue my investigation to find the root cause and fix it. 

If I will found the fix I will notify you about it before the proposal.

**Comment by pasyukevich** [comment] 2023-06-29 15:31
As I see it's not connected with the modal itself or wrappers. 
But I'm still assuming that this is the behavior related to the overlapped object. 

I continue my investigation by looking for the root cause.

**Comment by johncschuster** [comment] 2023-06-30 12:19
Thanks, @pasyukevich!

**Comment by pasyukevich** [comment] 2023-06-30 15:16
For this issue, I checked next: 

-    Added different colors for everything with opacity, transparent, and position absolute  to identify the overlayed element - nothing showed with color in the reproduced case
-   After some changes were able to type anything with the keyboard to the input (saw updates of the input, but was not able to click on it)

Regarding this, my current assumptions and conclusions: 
 
- I was able to reproduce  this issue locally on a physical device with a release scheme and without debug executable
- VoiceOver is not able to go through the app in case of this issue (like there is nothing to go through and navigate). 
- This issue may be connected with 3rd party that just lay over the app and block any interaction.

**Comment by johncschuster** [comment] 2023-07-05 14:57
@thesahindia can you take a look at @pasyukevich's comment above when you get a moment?

@pasyukevich, given what you've found, do you have a proposal for how to solve the problem, or are you looking to validate the root cause?

**Comment by pasyukevich** [comment] 2023-07-05 15:41
Currently, I don't have any working proposal on how to solve this problem. 

If you are not object - I will continue the investigation by looking for the root cause.

**Comment by johncschuster** [comment] 2023-07-06 15:17
Thanks, @pasyukevich! I'm going to add the `Help Wanted` label so we can get some proposals for this one.

**Comment by johncschuster** [comment] 2023-07-06 18:09
I've increased the bounty to get some 🔥 under it

**Comment by lindboe** [comment] 2023-07-06 18:47
I'm not sure if this will be helpful, but just to add my two cents:

If this is using react-native's Modal or react-native-modal: We at Infinite Red have had a number of issues with this native-backed modal on iOS. Race conditions that cause the modal's transparent overlay to not be properly dismissed were common, and extremely hard to debug and fix.

We try to use Javascript-based modals for this reason. Creating screens with react-navigation's modal presentation can be a great option. There are also JS-based portal libraries that can work well if the RN screen option doesn't work.

**Comment by kmwamasali** [comment] 2023-07-07 17:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App stops working when sending a message with an attachment simultaneously.
After investigating the issue, expected behavior on file upload is for attachment to be added to chat immediately.
My proposal is to solve the duplicate issue of files with spaces in their names failing to attach, which I feel can be covered here as well.

### What is the root cause of that problem?
The issue stems from the `AttachmentPicker` which removes spaces from the file name when checking if a file is valid. And then when the file is renamed the spaces are missing and the file is lost.
 
### What changes do you think we should make in order to solve the problem?
Adjusting the string splitting function to store/account for spaces when adding the file
`const {fileExtension} = FileUtils.splitExtensionFromFileName(lodashGet(_file, 'name', ''));`

**Comment by johncschuster** [comment] 2023-07-10 15:13
What do you think of the above, @thesahindia?

**Comment by Muhammad-Bilal-7896** [comment] 2023-07-11 08:06
Hi there Expensify Team members I am able to reproduce the above issue on ios 7 physical device. After the text sent with an attachement the app is hanging up and i am not able to perform anything else.

**Comment by Muhammad-Bilal-7896** [comment] 2023-07-11 08:07
Contributor details
Your Expensify account email: bilalmohib7896@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013a136c7081592898

**Comment by Muhammad-Bilal-7896** [comment] 2023-07-11 14:51
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
The member name is shown even after removal from the member list. When mentionining any member this member should not be shown.
> 
> ### What is the root cause of that problem?
The Root Cause is that the backend is not updating the @ mentions list that is coming from personal details API. 

```jsx
 personalDetails: {
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
 },
 
 src/pages/home/report/ReportActionCompose.js At this path
```

This is the file code where the data for suggestions for mentions is coming and it is not fetching the correct data i.e this list is not being updated after the removal of member.
```jsx
getMentionOptions(personalDetails, searchValue = '') {
        const suggestions = [];

        if (CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT.includes(searchValue.toLowerCase())) {
            suggestions.push({
                text: CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT,
                alternateText: this.props.translate('mentionSuggestions.hereAlternateText'),
                icons: [
                    {
                        source: Expensicons.Megaphone,
                        type: 'avatar',
                    },
                ],
            });
        }

        console.log('suggestions', suggestions);

        const filteredPersonalDetails = _.filter(_.values(personalDetails), (detail) => {
            // If we don't have user's primary login, that member is not known to the current user and hence we do not allow them to be mentioned
            if (!detail.login) {
                return false;
            }
            if (searchValue && !`${detail.displayName} ${detail.login}`.toLowerCase().includes(searchValue.toLowerCase())) {
                return false;
            }
            return true;
        });

        const sortedPersonalDetails = _.sortBy(filteredPersonalDetails, (detail) => detail.displayName || detail.login);
        _.each(_.first(sortedPersonalDetails, CONST.AUTO_COMPLETE_SUGGESTER.MAX_AMOUNT_OF_ITEMS - suggestions.length), (detail) => {
            suggestions.push({
                text: detail.displayName,
                alternateText: detail.login,
                icons: [
                    {
                        name: detail.login,
                        source: detail.avatar,
                        type: 'avatar',
                    },
                ],
            });
        });

        return suggestions;
    }
```

In the remove users function at this file path src/pages/workspace/WorkspaceMembersPage.js

```jsx
const removeUsers = () => {
        if (!_.isEmpty(errors)) {
            return;
        }

        const selectedUserNames = selectedEmployees.map((accountID) => {
            const member = props.personalDetails[accountID];
            return member ? member.login || member.displayName : '';
        });

        console.log('Selected Users to be Removed:', selectedUserNames);

        // Store the selected users in AsyncStorage
        storeData("removedMembersList",selectedUserNames);

        // Remove the admin from the list
        const accountIDsToRemove = _.without(selectedEmployees, props.session.accountID);

        Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);
        setSelectedEmployees([]);
        setRemoveMembersConfirmModalVisible(false);
    };
```

So basically the line `Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);` is updating the code for the members list in the WorkspaceMembersPage component but is not updating the Personal Details List

> 
> When a member is removed from workspace it does not have any impact in suggestions lsit (personal details object)
> 
> ### What changes do you think we should make in order to solve the problem?
In order to fix this issue the best one is to compose the mentions list from the workspace Members List. 
That is the file **ReportActionCompose** at src/pages/home/report/ReportActionCompose.js will need a change to take the members list from the workspace list.

> ### What alternative solutions did you explore? (Optional)
> I have fetched the members list and then compared the suggestion list for mentions with that one and removed the members that are not present in the members list. 

I have also solved this using hard code solution where i have used react native async storage to save the removed members like here
```js
  const storeData = async (key,value) => {
        try {
             const jsonValue = JSON.stringify(value);
            await AsyncStorage.setItem(key, jsonValue);
        } catch (e) {
            // saving error
        }
    };

    const removeUsers = () => {
        if (!_.isEmpty(errors)) {
            return;
        }

        const selectedUserNames = selectedEmployees.map((accountID) => {
            const member = props.personalDetails[accountID];
            return member ? member.login || member.displayName : '';
        });

        console.log('Selected Users to be Removed:', selectedUserNames);

        // Store the selected users in AsyncStorage
        storeData("removedMembersList",selectedUserNames);

        // Remove the admin from the list
        const accountIDsToRemove = _.without(selectedEmployees, props.session.accountID);

        Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);
        setSelectedEmployees([]);
        setRemoveMembersConfirmModalVisible(false);
    };
```

And then filtering the current suggestion list and removing the removed members list members. Basically this is a bad solution but this was the first i tried and this is not the one i will use. 

## Solution I will use
> I will use the workspace data members list instead of the people list used in the suggestions. 
OR
> I will implement comparing the suggestion list with the memberlist workspace members data and will remove all that are not part of the workspace array data.

**Comment by pasyukevich** [comment] 2023-07-11 16:30
@kmwamasali I'm not sure that this is the root cause for this issue. 

I'm able to reproduce this bug with pictures that do not contain any spaces in the name.

**Comment by pasyukevich** [comment] 2023-07-11 16:34
@johncschuster From my side, I found the potential problem and now checking how to solve it properly.

Based on my assumptions, It is connected with modals on this page and does not have straight forward relation with BE.

**Comment by pasyukevich** [comment] 2023-07-13 12:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The app stops working when sending a message with an attachment simultaneously.

### What is the root cause of that problem?

The modal layer is not fully removed from the app after closing the Attachment modal. This is caused by `calculateEmojiSuggestion` and `calculateMentionSuggestion` that prevents the full unmount of the modal. This problem was already solved here https://github.com/Expensify/App/issues/16591. Looks like after some updates this fix slightly regressed.

### What changes do you think we should make in order to solve the problem?

Modify `onSelectionChange` to set `this.shouldBlockEmojiCalc` and `this.shouldBlockMentionCalc` to `false` inside the `if (!this.state.value || e.nativeEvent.selection.end < 1)` statement. This will prevent calling these calculations during the closing of the modal

**Comment by johncschuster** [comment] 2023-07-13 12:56
@thesahindia what do you think about the above proposal?

**Comment by johncschuster** [comment] 2023-07-17 14:47
@thesahindia how did testing go? Does the proposal fit?

**Comment by getusha** [comment] 2023-07-18 14:36
I am not able to reproduce too.

**Comment by johncschuster** [comment] 2023-07-22 12:07
It looks like we're good to close this one out.

**Closed by johncschuster** 2023-07-22 12:07 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Overdue, Bug
