### ISSUE TITLE
[$500] Compose-The markdown for bold is not applied like italic and strikethrough.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30823] opened 2023-11-03 08:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a chat
3. Enter ~hjj~4~45677~

_hjj_4_45677_

*hjj*4*45677*
4.Send the message

## Expected Result:
The markdown should be applied for bold like italic and strikethrough.

## Actual Result:
The markdown for bold is not applied like italic and strikethrough.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/19d1c83e-95fe-458b-a82b-b63aa2864c9a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01490bd23a2d65a4ce</li>
        <li>Upwork Job ID: 1720354161206349824</li>
        <li>Last Price Increase: 2023-12-01</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 28062561</li>
</ul></li>
    </ul>
</details>

**Comment by t109ct** [comment] 2023-11-03 08:42
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Composer-The markdown for bold is not applied like italic and strikethrough.

### What is the root cause of that problem?
The markdown's regex pattern for bold (https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L214) is not applied like italic and strikethrough. we need to fix it.

### What changes do you think we should make in order to solve the problem?
We can fix bold markdown's regex pattern as following
```
regex: /\B\*((?![\s*])[\s\S]*?[^\s*])\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
```

We can add relevant test case for this issue.
and above fixing does not make other auto test cases failed.

**Comment by isabelastisser** [comment] 2023-11-06 17:03
@0xmiroslav can you please review the proposals above? Thanks!

**Comment by Victor-Nyagudi** [comment] 2023-11-07 14:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Compose - The markdown for bold is not applied like italic and strikethrough.

### What is the root cause of that problem?

The character class in [the bold rule's regular expression of `ExpensiMark.js`](https://github.com/Expensify/expensify-common/blob/a055da6a339383da825f353d5c0da72a26285007/lib/ExpensiMark.js#L214) doesn't match asterisks inside the bold markdown syntax i.e. `[^\s*]` matches any non-whitespace character and a literal `*`. 

```javascript
// ...
{
    name: 'bold',      // ⬇️ here
    regex: /\B\*((?=\S)(([^\s*]|\s(?!\*))+?))\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
    replacement: (match, g1) => (g1.includes('<pre>') || this.containsNonPairTag(g1) ? match : `<strong>${g1}</strong>`),
}
// ...
```

I'm not sure why this is (still investigating), but my guess is maybe it was meant to be a quantifier. However, moving the asterisk to outside the character class e.g. `[^\s]*` has one major drawback, as explained in the alternative solutions I explored section. 

### What changes do you think we should make in order to solve the problem?

I propose replacing the character class with a non-whitespace character match i.e. `\S`. This way, we can also account for other types of whitespace characters such as tab, carriage return, etc. 

```javascript
// ...
{                                        
    regex: /\B\*((?=\S)((\S🟢|\s(?!\*))+?))\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
}
// ...
```

<details>

<summary>Short demo after changes</summary>

https://github.com/Expensify/App/assets/79470910/b7394248-4e69-4281-8103-c1bda5b7de10

</details>

### What alternative solutions did you explore? (Optional)

I noticed that if there's a space after the inner asterisk, the regular expression doesn't match the whole string even after my changes.

<details>

<summary>Screenshot of match</summary>

![expensify-space-not-matched-bold-markdown](https://github.com/Expensify/App/assets/79470910/31d9b0d6-90d2-4721-a335-1dc1d65f42a1)

</details>

I went back and forth on whether it looks right the way it is, or if the entire section between the asterisks should be matched and consequentially bolded, but that is still up for debate (I'm leaning towards this match working as intended). 

Nevertheless, I tried fixing this by moving the asterisk to outside the character class ,and got a match. 

<details>

<summary>Screenshot of match</summary>

![expensify-asterisk-outside-character-class-match](https://github.com/Expensify/App/assets/79470910/9b8eb2ea-eb58-4c30-a85b-770128f10341)

</details>

Everything seemed to work fine until, during testing, I added some text immediately after the ending asterisk like below, and this led to [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html), which, as the name suggests, is something we definitely do not want. 

```
*hjj*4* 45677*somegibberishafter
```

**Comment by isabelastisser** [comment] 2023-11-09 16:55
Hey @0xmiroslav, can you please review the proposals above?

**Comment by isabelastisser** [comment] 2023-11-16 17:35
@0xmiroslav please provide an update!

**Comment by isabelastisser** [comment] 2023-11-29 21:39
@0xmiroslav, please provide an update, thanks!

**Comment by isabelastisser** [comment] 2023-11-30 20:38
Bump @0xmiroslav

**Comment by isabelastisser** [comment] 2023-12-04 17:15
Hey @0xmiroslav, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2023-12-05 19:07
Bump @0xmiroslav

**Comment by isabelastisser** [comment] 2023-12-08 14:38
@0xmiroslav please provide an update. Thanks!

**Comment by Victor-Nyagudi** [comment] 2023-12-14 14:43
Any thoughts on my [proposal](https://github.com/Expensify/App/issues/30823#issuecomment-1798630097), @0xmiroslav?

**Comment by t109ct** [comment] 2023-12-14 15:49
@0xmiroslav We should match the regex pattern structure for all of italic,bold,strikethough, otherwise it will cause other regression issue.
```
*hjj*4*45677*sfs****
_hjj_4_45677_sfs____
~hjj~4~45677~sfs~~~~
```

My solution keeps consistency about the above test strings, but @dukenv0307 's does not

**Comment by isabelastisser** [comment] 2023-12-15 17:42
@0xmiroslav @t109ct please provide an update on the PR. Thanks!

**Comment by t109ct** [comment] 2023-12-18 10:19
@0xmiroslav @isabelastisser 
Thanks for review and assignment

The PR https://github.com/Expensify/expensify-common/pull/622 for expensify-common repo is ready

**Comment by isabelastisser** [comment] 2023-12-18 15:51
Thanks @t109ct ! Bump @0xmiroslav for PR review. Thanks!

**Comment by isabelastisser** [comment] 2023-12-20 16:47
Hey @0xmiroslav, did you review the PR? Thanks!

**Comment by isabelastisser** [comment] 2023-12-22 17:29
Hey @0xmiroslav, can you please prioritize this issue? Please let me know if you would like me to reassign it. Thanks!

**Comment by isabelastisser** [comment] 2024-01-02 18:16
Hey @madmax330 and @t109ct, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2024-01-03 16:50
Bump @0xmiroslav @t109ct

**Comment by stitesExpensify** [comment] 2024-01-05 19:51
PR is merged

**Comment by isabelastisser** [comment] 2024-01-08 15:33
Not overdue.

**Comment by mallenexpensify** [comment] 2024-01-24 00:46
What's status here? I see [the below from three weeks ago](https://github.com/Expensify/expensify-common/pull/622#event-11404343955). 

<img width="749" alt="image" src="https://github.com/Expensify/App/assets/22508304/13e7486c-d39e-40db-9d11-4ace52b6ba3c">

**Comment by t109ct** [comment] 2024-01-24 01:13
I am waiting for payment, it's merged 3 weeks ago

**Comment by mallenexpensify** [comment] 2024-01-24 04:03
@t109ct can your you please confirm your first name and last initial for payment in Upwork.  Or... better yet,  a link to your Upwork profile.   Thx

**Comment by mallenexpensify** [comment] 2024-01-26 00:56
Ping @t109ct , can you share your upwork account? You weren't auto-added to the Upwork job, it doesn't appear the [contributor details ](https://github.com/Expensify/App/issues/30823#issuecomment-1792055853)were completed. 

Thanks,

**Comment by isabelastisser** [comment] 2024-01-30 17:54
Bump @t109ct, please follow up on the request above.  Thanks!

**Comment by isabelastisser** [comment] 2024-02-02 01:05
Hey @t109ct, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2024-02-05 13:12
Bump @t109ct so that we can process the payment. Thanks!

**Comment by isabelastisser** [comment] 2024-02-07 16:58
@mallenexpensify, do you know @t109ct name so that we can bump the Contributor in Slack for visibility?

**Comment by isabelastisser** [comment] 2024-02-07 17:07
@0xmiroslav, I sent you the offer in Uprwork. Please accept it and I will process the payment.

@t109ct, my plan is to close this issue tomorrow, so please share your Upwork profile details for payment as soon as possible. Thanks!

**Comment by mallenexpensify** [comment] 2024-02-07 18:48
Bumped to weekly, I'm unfamiliar with @t109ct and don't see them in Slack or having emailed contributors@expensify.com .

**Comment by isabelastisser** [comment] 2024-03-04 17:32
I'm closing this since we haven't heard from @t109ct for over a month. @t109ct, please comment here or message me in Slack if you need the payment. Thanks!

**Closed by isabelastisser** 2024-03-04 17:32 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug

**Comment by t109ct** [comment] 2024-03-04 19:19
@isabelastisser @mallenexpensify 
Sorry for very late reply, but I had gotten a car accident and been hospitalized. and discharged a week ago
The recent comment notified me about this issue.

I will update soon

**Comment by t109ct** [comment] 2024-03-04 19:21
Contributor details
Your Expensify account email: celenaschwinghammer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fe7078c12d6cbd14

**Comment by isabelastisser** [comment] 2024-03-05 14:49
Hi @t109ct, I'm sorry to hear that you got into an accident and that you're doing well. I wish you a speedy recovery! I have sent you an offer in Upwork now, please accept it, and I will process the payment. Thank you!

**Comment by t109ct** [comment] 2024-03-05 15:00
@isabelastisser I've received payment, thanks for your care
