### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] RHP - User remains on the Private Notes page when clicked on back btn after reload

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40502] opened 2024-04-18 20:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Navigate to any conversation with other user
3. Click on Header to open Profile page
4. Click on Private Notes
5. Reload the page
6. Click on back button
7. Click on back button again

## Expected Result:
User should be redirected to Profile page when clicked back button

## Actual Result:
User remains on the Private Notes page when clicked on back button after page reload. When user clicked on back button again the RHP will be closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/18e04f2a-8f8d-450e-a3ae-31b5bc28b584

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0ae1b806ad11050</li>
        <li>Upwork Job ID: 1781084747484880896</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment] 2024-04-18 20:30
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment] 2024-04-18 21:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RHP - User remains on the Private Notes page when clicked on back btn after reload
### What is the root cause of that problem?
On pressing back button in `PRIVATE_NOTES_EDIT`  we always navigating to `PRIVATE_NOTES_LIST` page . 
### What changes do you think we should make in order to solve the problem?
Update [this](https://github.com/Expensify/App/blob/99b736ed51844939e36b4cf98ebc00a9815fb383/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L119C17-L119C113) line like below
```
onBackButtonPress={() => {
    route.params.accountID ?  ReportUtils.goBackToDetailsPage(report) : Navigation.goBack(ROUTES.PRIVATE_NOTES_LIST.getRoute(report.reportID))
}}
```
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-04-18 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RHP - User remains on the Private Notes page when clicked on back btn after reload
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/99b736ed51844939e36b4cf98ebc00a9815fb383/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L119C42-L119C112) in the `PRIVATE_NOTES_EDIT` page we always go to `PRIVATE_NOTES_LIST` page using `Navigation.goBack` method by clicking `back` button. When we pass the `fallbackRoute` param in the `Navigation.goBack` method, it only goes to that route if the current route is the first one in the navigation stack, otherwise it goes back to the previous route. And so the current screen becomes first one in navigation stack, we navigate to the `fallbackRoute` after clicking the `back` button.
### What changes do you think we should make in order to solve the problem?
1. Add ability to receive `backTo` param for `ROUTES.PRIVATE_NOTES_EDIT.getRoute` method.  To do this update [this](https://github.com/Expensify/App/blob/99b736ed51844939e36b4cf98ebc00a9815fb383/src/ROUTES.ts#L303C9-L303C118) line as below 
```
getRoute: (reportID: string, accountID: string | number, backTo?: string) => getUrlWithBackToParam(`r/${reportID}/notes/${accountID}/edit` as const, backTo),
```
2. Add `Navigation.getActiveRoute()` as third ( `backTo` ) param in `getRoute` methods [here](https://github.com/Expensify/App/blob/99b736ed51844939e36b4cf98ebc00a9815fb383/src/libs/ReportUtils.ts#L5624C55-L5624C99) and [here](https://github.com/Expensify/App/blob/99b736ed51844939e36b4cf98ebc00a9815fb383/src/pages/PrivateNotes/PrivateNotesListPage.tsx#L72C77-L72C113)

3. Update [this](https://github.com/Expensify/App/blob/99b736ed51844939e36b4cf98ebc00a9815fb383/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L119C17-L119C113) line like below
```
onBackButtonPress={() => Navigation.goBack(route.params?.backTo)}
```
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-04-18 22:18
Was able to repro, seems like it can be external, @shubham1206agra , can you review the bug and proposals above? Thx

https://github.com/Expensify/App/assets/22508304/35881c03-ab54-4bfb-96ca-2627b0e82965

**Comment by nkdengineer** [comment] 2024-04-19 04:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User remains on the Private Notes page when clicked on back button after page reload. When user clicked on back button again the RHP will be closed

### What is the root cause of that problem?
We always fallback go back to private note list page here

https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L119
### What changes do you think we should make in order to solve the problem?
We should use the same check as we do here to go to the private note edit or private note list page.

https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/libs/ReportUtils.ts#L5622-L5628

1. Create a utils like `goBackFromPrivateNotes` in `ReportUtils`. If `currentUserPrivateNote` is empty we will go back to to detail page by using `goBackToDetailsPage` function. Otherwise fallback to private note list.

```
function goBackFromPrivateNotes(report: OnyxEntry<Report>, session: OnyxEntry<Session>) {
    if (isEmpty(report) || isEmpty(session) || !session.accountID) {
        return;
    }
    const currentUserPrivateNote = report.privateNotes?.[session.accountID]?.note ?? '';
    if (isEmpty(currentUserPrivateNote)) {
        goBackToDetailsPage(report);
        return;
    }
    Navigation.goBack(ROUTES.PRIVATE_NOTES_LIST.getRoute(report.reportID));
}
```

2. In `PrivateNotesEditPage`, subscribe `session` from Onyx. And then call `goBackFromPrivateNotes` function here 

```
onBackButtonPress={() => ReportUtils.goBackFromPrivateNotes(report, session)} 

```
https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L119

### What alternative solutions did you explore? (Optional)
NA

**Comment by mallenexpensify** [comment] 2024-04-19 23:36
@shubham1206agra plz review proposals above, thx.

**Comment by shahinyan11** [comment] 2024-04-22 14:32
> Well, I am going to go ahead with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/40502#issuecomment-2065722793) with one side note, i.e., we should use a modified version of `navigateToDetailsPage` instead of `goBackToDetailsPage`.
> 
> 🎀👀🎀 C+ reviewed

@shubham1206agra Are you sure that whenever `currentUserPrivateNote` is empty, we should go to the details page.
Could you give your opinion on my proposal? I want to understand what is the advantage of @nkdengineer's propsal compared to mine

**Comment by mountiny** [comment] 2024-04-24 19:17
Not overdue

**Comment by mountiny** [comment] 2024-04-24 19:17
@nkdengineer when will you have a PR up please?

**Comment by nkdengineer** [comment] 2024-04-25 00:57
Will open it today.

**Comment by nkdengineer** [comment] 2024-04-25 01:09
Will open it today.  For the past few days I tried to run my Android simulator but failed.

**Comment by nkdengineer** [comment] 2024-04-25 01:53
@shubham1206agra The PR is [here](https://github.com/Expensify/App/pull/40951). I still cannot run Android App now.

**Comment by mallenexpensify** [comment] 2024-05-22 00:21
Seems to have gone a bit stale but... we're in a merge freeze now so the PR should be deployed soon
- https://github.com/Expensify/App/pull/40951#issuecomment-2120935152

**Comment by mallenexpensify** [comment] 2024-06-12 00:23
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @shubham1206agra owed $250 via Upwork. 

@shubham1206agra , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01435fc0aa943015f5 


Sorry I missed this (not sure how)

**Comment by nkdengineer** [comment] 2024-06-20 04:58
@mallenexpensify I think we can process payment now and then we can close this issue.

**Comment by mallenexpensify** [comment] 2024-06-21 20:45
Closing, everyone's paid. I created a TestRail GH too
- https://github.com/Expensify/Expensify/issues/406659

**Closed by mallenexpensify** 2024-06-21 20:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
