### ISSUE TITLE
[HOLD on #21498] Web -  App allows to modify announce, admin room name with deep link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22968] opened 2023-07-16 11:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Click on 3 dot and click on go to #announce room
6. Click #announce in head to open details page
7. Click on settings and observe that it does not allow to update room name
8. Add '/room-name' to URL and click enter, observe that it opens room name edit page with name as # announce

## Expected Result:
App should not allow users to open announce and admin rooms room name edit page using deep link

## Actual Result:
App allows users to open announce and admin rooms room name edit page using deep link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/40b9babc-b98d-4f69-b7de-e8f792c27d9b

https://github.com/Expensify/App/assets/93399543/c6df550d-078c-44e9-a6f0-d5dd3190dfac

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689410765634399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-07-16 14:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - App allows to modify announce, admin room name with deep link.

### What is the root cause of that problem?
We don't have any check for validating that room's name can be changed in `RoomNamePage`.

### What changes do you think we should make in order to solve the problem?
We shall add the check in `RoomNamePage` similar to we did in `RoomSettingsPage`
we can use this logic - 
```
this.shouldDisableRename(linkedWorkspace) || ReportUtils.isChatThread(this.props.report)
```

we shall move the logic inside `shouldDisableRename` to ReportUtils and use it in `RoomNamePage`
https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/pages/settings/Report/ReportSettingsPage.js#L63-L82


There are two approaches for this -
1. Wrap the component in `FullPageNotFoundView` and display the page not found view with error. Same check has been done in `WriteCapabilityCheck`, here we are not showing any error message. 
If we want to show the error message, we pass it using `subtitleKey`.
3.  add the check in `RoomNamePage` and if the room name can't be changed, we return and render nothing.

### What alternative solutions did you explore? (Optional)

**Comment by dhanashree-sawant** [comment] 2023-07-16 15:54
The bug is for announce, admin room name update which are not allowed by either admin or user. We are tricking the system here to update, not that 21498

**Comment by twisterdotcom** [comment] 2023-07-20 00:28
I think if we already have a fix in the works, let's HOLD on that.

**Comment by twisterdotcom** [comment] 2023-07-20 00:28
Held on https://github.com/Expensify/App/issues/21498

**Comment by abdulrahuman5196** [comment] 2023-07-21 08:58
@twisterdotcom The fix was merged to staging couple of hours ago. We can re-test this issue on staging

**Comment by twisterdotcom** [comment] 2023-07-28 14:50
Okay, this is fixed. I will pay out for the bug report here **ONLY**.

Paying @dhanashree-sawant $250 via Upwork: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25810014

**Comment by twisterdotcom** [comment] 2023-07-28 15:23
Paid.

**Closed by twisterdotcom** 2023-07-28 15:23 UTC
Labels: Weekly, Awaiting Payment, Bug
