### ISSUE TITLE
[Hold - Browser Resizing - #13971] Bank account - the cursor is disabled in the bottom dock model of the account preview.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13959] opened 2023-01-03 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Payments > add Paypal/Bank account
2. Decrease browser window size
3. Click on account card and hover over bottom account preview

## Expected Result:
The cursor should be the default.

## Actual Result:
The cursor has been disabled.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / windows / Chrome / Safari 
- [ ] MacOS / Desktop

**Version Number:** v1.2.47-0.
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210413078-c017e6af-2605-4928-bd4f-17d5ca9f04d8.mov

https://user-images.githubusercontent.com/43996225/210413113-5708bd8b-f4c2-43f6-a07f-04be613f23c3.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672684745660549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-01-03 21:42
Triaging: 

From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you're unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it's better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by joekaufmanexpensify** [comment] 2023-01-03 21:55
I can reproduce: 

![2023-01-03_16-52-10 (1)](https://user-images.githubusercontent.com/54866469/210447767-93793b80-d747-4eef-87dc-a825d2dbf1fd.gif)

**Comment by joekaufmanexpensify** [comment] 2023-01-03 21:58
Going to start a discussion about this one in Slack. This is def a bug. However, it's niche, purely aesthetic, and barely noticeable. So not sure whether it's worth fixing right now. 

The cursor disablement is only when the window is resized on web/desktop, and is only when the cursor is in the area near the delete button. It is not disabled when actually hovering over the button.

**Comment by joekaufmanexpensify** [comment] 2023-01-03 22:03
Asked [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1672783427814329)

**Comment by trjExpensify** [comment] 2023-01-04 02:24
As a result of those threads today, I've created [this parent issue](https://github.com/Expensify/App/issues/13971). We should tackle all of these browser resizing issues holistically and need someone to own that plan.

**Comment by joekaufmanexpensify** [comment] 2023-01-30 14:29
sounds good.

**Comment by joekaufmanexpensify** [comment] 2023-02-27 14:15
Captured in larger parent issue, which is on hold.

**Comment by joekaufmanexpensify** [comment] 2023-03-27 08:57
Still on hold

**Comment by joekaufmanexpensify** [comment] 2023-04-24 13:20
Same

**Comment by joekaufmanexpensify** [comment] 2023-05-22 13:16
Still on hold

**Comment by joekaufmanexpensify** [comment] 2023-06-19 13:32
Same

**Comment by joekaufmanexpensify** [comment] 2023-07-17 13:16
Same.

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:57
Held

**Comment by joekaufmanexpensify** [comment] 2023-08-21 14:01
Same

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:44
Still held

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:16
Same

**Comment by joekaufmanexpensify** [comment] 2023-10-23 14:15
Held

**Closed** 2023-11-20 14:33 UTC
Labels: Monthly, Bug
