### ISSUE TITLE
Android - Attachments - Attachments (MP4, Docx, webp) in conversation history are flickering

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33618] opened 2023-12-26 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to a conversation
3. Tap the plus button in compose box
4. Add attachments (MP4, Docx, webp)

## Expected Result:
When navigate to conversation history attachment should look normal and there shouldn't be any shaking or flickering files

## Actual Result:
Attachments (MP4, Docx, webp) in conversation history are shaking

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/37866a67-d327-4cab-a7d3-901ca1391796

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2023-12-26 20:42
Can't seem to reproduce this on Android **v1.4.17-1**:

https://github.com/Expensify/App/assets/6833644/def9d034-85a9-4162-9820-fd889e69c328

**Comment by arosiclair** [comment] 2023-12-26 20:48
Closing this out since it isn't reproducible atm.

**Closed by arosiclair** 2023-12-26 20:48 UTC
Labels: DeployBlockerCash, Engineering, Hourly
