### ISSUE TITLE
Holding down on one of the suggested contacts selects the comment behind the suggestion box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18926] opened 2023-05-14 14:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open newDot on mobile web Chrome
2. Write "@" in the text composer to bring up the suggestion box
3. Hold down on one of the suggested contacts

## Expected Result:
The comment behind the suggestion box should not be selected and menu items should not show up

## Actual Result:
The comment behind the suggestion box is selected and the menu items are shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5bb7055f-7859-46ee-b4eb-97b3b75a621b

https://github.com/Expensify/App/assets/43996225/3076c606-3e8e-4cf8-8132-0e776f4d154a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683885453991959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-05-15 12:03
[Looking for help here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684152169180729)

**Comment by conorpendergrast** [comment] 2023-05-15 12:45
@pecanoro was not able to reproduce via Android physical device.

@kavimuru Were you able to reproduce already?

**Comment by conorpendergrast** [comment] 2023-05-17 08:49
Closing as not reproducible on an Android physical device, or Browserstack. If someone else can reliably reproduce, then great - let's reopen!

**Closed by conorpendergrast** 2023-05-17 08:49 UTC
Labels: Daily, Needs Reproduction, Bug
