### ISSUE TITLE
Hybrid Android - Chat - White area appears behind keyboard as keyboard is pulling up

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52816] opened 2024-11-20 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-3
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+29302390@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- App is in dark mode.

1. Launch hybrid app.
2. Go to New Expensify.
3. Open any chat.
4. Close keyboard.
5. Focus on the composer to open keyboard.

## Expected Result:
No white area will appear behind keyboard as keyboard is pulling up.

## Actual Result:
White area appears behind keyboard as keyboard is pulling up.

This issue is not reproducible on standalone ND.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e7dce7e0-876f-475a-a84b-65aea26455c0

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2024-11-21 19:56
Asked for help here: https://expensify.slack.com/archives/C04878MDF34/p1732218948047719

Unassigning as my plate is full

**Comment by jnowakow** [comment] 2024-11-26 14:27
I'm from SoftwareMansion and I'll work on this one

**Comment by jnowakow** [comment] 2024-11-27 10:50
I've tried to reproduce it from newest main. On simulator I'm not able to reproduce it. I'll try on physical device

**Comment by puneetlath** [comment] 2024-12-04 15:22
Ok great. Let's close this then.

**Closed by puneetlath** 2024-12-04 15:22 UTC
Labels: Engineering, Daily, Overdue, Bug
