### ISSUE TITLE
Web - IOU - There is a delay in sending money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37300] opened 2024-02-27 14:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29991
## Action Performed:
1. Log in with a Gmail account
2. Click on the FAB - Send money
3. Enter any amount
4. Select a gmail address that never logged in

## Expected Result:
There shouldn't be any delays

## Actual Result:
There is a delay in sending money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dbe7ab0f-d020-42c6-8ea4-67d00169e6f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-27 14:27
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @arielgreen

**Comment by lakchote** [comment] 2024-02-27 15:45
Not a blocker or related to NewDot performance.

Instead it's an API slowdown, see the `SendMoneyElseWhere` api response in the video below.

https://github.com/Expensify/App/assets/21549771/b819c1ae-6d32-4deb-ac6b-8f916d8ee9f9

Closing the issue for these reasons.

**Comment by luacmartins** [comment] 2024-02-27 15:48
Sorry @lakchote I spoke too soon. In prod, the API also takes 6s but the page loads immediately because of the optimistic data, so this seems like a regression in App.

**Comment by lakchote** [comment] 2024-02-27 15:52
> Sorry @lakchote I spoke too soon. In prod, the API also takes 6s but the page loads immediately because of the optimistic data, so this seems like a regression in App.

Oh, my bad. Well let's take a deeper look at this!

**Comment by lakchote** [comment] 2024-02-27 16:54
I've looked at all the PRs that got merged, and I don't see any that could have had an effect on Onyx optimistic data for send money.

Last change on `IOU.ts` `sendMoneyElsewhere()` and `sendMoneyWithWallet()` was [4 weeks ago](https://github.com/Expensify/App/pull/34092)

It seems like optimistic data is correctly set judging by my screen below (on dev):
<img width="1160" alt="image" src="https://github.com/Expensify/App/assets/21549771/66b0cc3c-333e-421e-8783-ff4844eeea8c">

It's very hard to reproduce on dev since I don't have the latency problems I would have on staging. 
As such, I can't see the optimistic data (or lack thereof) problem come into play.

**Comment by luacmartins** [comment] 2024-02-27 17:56
Just noting that this happens for other flows too, e.g. Start chat and Request money

**Comment by lakchote** [comment] 2024-02-27 17:58
The issue was [elsewhere](https://github.com/Expensify/App/pull/37323).

Now it's fast on staging, since the revert PR was deployed.

**Comment by bernhardoj** [comment] 2024-02-28 02:44
@aimane-chnaif the Onyx PR doesn't introduce the delay, maybe it was a site issue. The report screen shows a skeleton loader instead of a blank screen after the Onyx PR. Same case like this [one](https://github.com/Expensify/App/issues/37251)

**Comment by luacmartins** [comment] 2024-02-28 15:01
I think we can close this issue, since we CPed a fix and it was tested in staging.

**Closed by luacmartins** 2024-02-28 15:01 UTC
Labels: Engineering, Hourly
