### ISSUE TITLE
[HOLD for payment 2023-12-08] [$500] Android - Task - Error message displayed when creating task with line break in title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31440] opened 2023-11-16 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to any chat
3. Tap the "+" button > Assign task
4. Copy text with a line break and paste into the title field
5. Complete task creation flow

## Expected Result:
Task is created and the title is displayed as one line

## Actual Result:
The error message "Auth CreateTask returned an error. Unexpected error create task, please try again later" is shown, and the title is displayed with a line break.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7151fd61-2d37-42a2-a623-022e27d4fb08

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e745855aa3defdd</li>
        <li>Upwork Job ID: 1725145741215453184</li>
        <li>Last Price Increase: 2023-11-16</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27817765</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-11-16 14:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When copying multiline text in task title, multiline title is displayed in task report and error is shown

### What is the root cause of that problem?

We use copy-paste function of native platforms in TextInput component. When pasting multiline text in single line TextInput on Android, it looks like a single line, but its value has a linebreak. For instance, when pasting 'hello\nworld', it looks like 'hello world' but its real value is 'hello\nworld'. When creating task with multiline title, it looks like the backend returns error

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to remove all the line breaks from the title
Update
https://github.com/Expensify/App/blob/6ea4539d15ac523a070532a69ab99cbf1dabba0c/src/pages/tasks/NewTaskDetailsPage.js#L108
to
```
    onValueChange={(value) => setTaskTitle(value.replace(/\n/g, ' '))}
```

This works as expected

**Note**: We need to apply this change to `NewTaskTitlePage` as well

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by alexismailov2** [comment] 2023-11-16 14:18
Looks like Upwork task https://www.upwork.com/jobs/500-Android-Task-Error-message-displayed-when-creating-task-with-line-break-title-31440-Expensify_~015e745855aa3defdd/?referrer_url_path=find_work_home Is not relevant anymore?

**Comment by nixonbaguiluck** [comment] 2023-11-17 21:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error message "Auth CreateTask returned an error. Unexpected error create task, please try again later" is shown, and the title is displayed with a line break.

### What is the root cause of that problem?
The difference in behavior between Android, iOS, and web when copying multi-line strings into a <TextInput> component is due to the inherent platform-specific handling of line breaks.

### What changes do you think we should make in order to solve the problem?

We can fix this issue so briefly if we change only one line as following part.

https://github.com/Expensify/App/blob/3f7e66a8e39b8ecfe4921c74f11f168deafd5d21/src/pages/tasks/NewTaskDetailsPage.js#L111-L111

```javascript
<View style={styles.mb5}>
    <InputWrapper
        ...
        onValueChange={(value) => setTaskTitle(value.replace(/\r?\n|\r/g, ' '))}
    />
</View>
``` 

The Result is same as following video.
file:///home/nixon/Downloads/check.webm

### What alternative solutions did you explore? (Optional)
NA

**Comment by nixonbaguiluck** [comment] 2023-11-17 22:33
Sorry, Updated my proposal. https://github.com/Expensify/App/issues/31440#issuecomment-1817122330

**Comment by sakluger** [comment] 2023-11-21 17:46
Bumped in Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1700588773073479.

**Comment by sobitneupane** [comment] 2023-11-22 13:16
Will review it shortly.

**Comment by sobitneupane** [comment] 2023-11-23 12:07
Thanks for the proposal everyone.

@tienifr's proposal looks good to me. The issue exists in multiple flows in the app. So, I believe making the change in `BaseTextInput` `index.native.js` is the best way to solve the issue.

🎀 👀 🎀 C+ reviewed

**Comment by sakluger** [comment] 2023-12-07 21:05
@sobitneupane mind finishing the BZ checklist so that we can approve your payment tomorrow? Thanks!

**Comment by sobitneupane** [comment] 2023-12-08 11:42
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

I don't think we can point to a particular PR for this bug. This bug exists in all the single line inputs in the app. I would say it was present from the very beginning in the android app.

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

N/A
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-12-08 11:47
Regression Test Proposal:

1. Go to any single line input in the app.( For example: 'Display Name' in Profile or 'Task Title' in 'Assign Task')
2. Copy multiline texts and paste in input field.
3. Submit the form.
4. Verify that the input is accepted and line breaks in the text in replaced by spaces.

Do we agree 👍 or 👎

**Comment by sakluger** [comment] 2023-12-09 00:28
Looks good, thanks!

**Summarizing payouts for this issue:**

Contributor: @tienifr $500 (paid on Upwork)
Contributor+: @sobitneupane $500 (payable via Manual Request)

**Comment by sakluger** [comment] 2023-12-09 00:29
@sobitneupane please let me know once you've sent the manual request so I can close the issue. Thanks!

**Comment by sakluger** [comment] 2023-12-11 17:45
I'm going to close this one out. @sobitneupane please let me know in Slack if it needs to be reopened for any reason.

**Closed by sakluger** 2023-12-11 17:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2023-12-15 09:52
https://github.com/Expensify/App/issues/31440#issuecomment-1848003899

Requested payment on newDot.

**Comment by JmillsExpensify** [comment] 2023-12-15 23:15
$500 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/31440#issuecomment-1848003899).
