### ISSUE TITLE
[$1000] Money request page crash after sign in

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23420] opened 2023-07-23 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out if you are signed in
2. Go to staging.new.expensify.com/request/new
3. Login
## Expected Result: 
App crash
## Actual Result: 
App should not crash

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1341c04e-8d08-4e46-9dfc-e40707439e7d

https://github.com/Expensify/App/assets/43996225/1e1cc62e-2193-42fb-ae6b-c2a967f5ea43

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690017033035589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c96f9a061c08188b</li>
        <li>Upwork Job ID: 1683620832387874816</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 25856547</li>
<li>bernhardoj | Reporter | 25856549</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-23 17:02
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The app crash when opening the money request page after signing in
### What is the root cause of that problem?
The crash happens because in `TextInputWithCurrencySymbol`, `selectedCurrencyCode` prop is marked as required, but it got undefined.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/TextInputWithCurrencySymbol.js#L23-L24
The `selectedCurrencyCode` is passed down from `MoneyRequestAmountPage` with the value from `props.iou.currency` (Onyx IOU). We have a `defaultProps` that set the currency to USD.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/iou/steps/MoneyRequestAmountPage.js#L67-L72
`defaultProps` will be used if `iou` is undefined. The problem is, Onyx IOU itself has a default value.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/setup/index.js#L31-L39
So, when we sign in, we have an IOU object of `{loading, error}` which will ignore the `defaultProps` in `MoneyRequestAmountPage`, thus the currency is undefined.
This issue is a regression of my PR here https://github.com/Expensify/App/pull/17964. Previously, we use `lodashGet` to get the currency and default to USD. Here is the commit of using the `lodashGet` [https://github.com/Expensify/App/pull/17964/commits/4fdf587c1fca3cc147f7184c1bf765bcd2cf5ee5#diff-879f243892ee617d3ea9b[…]91d2bec3eb12b90f09aac6a05a](https://github.com/Expensify/App/pull/17964/commits/4fdf587c1fca3cc147f7184c1bf765bcd2cf5ee5#diff-879f243892ee617d3ea9bc2550496a07521c2b91d2bec3eb12b90f09aac6a05a)
but somehow I remove it in a later commit.
### What changes do you think we should make in order to solve the problem?

I think that's okay to not use `lodashGet` and instead we can remove the default value of Onyx IOU.
(remove this)
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/setup/index.js#L36-L39
Both loading and error are not being used anywhere.
### What alternative solutions did you explore? (Optional)
Make `selectedCurrencyCode` in `TextInputWithCurrencySymbol` optional and set USD as the default prop of `selectedCurrencyCode`.

**Comment by JmillsExpensify** [comment] 2023-07-24 23:29
<img width="1579" alt="Screenshot 2023-07-24 at 17 28 56" src="https://github.com/Expensify/App/assets/1127863/e990fee5-694f-4595-be0b-fbf1615a52a5">

Interestingly, I don't get a crash for this case though I do see this.

**Comment by JmillsExpensify** [comment] 2023-07-24 23:30
In any case, I think that's largely a detail given that it's consistent with your video. I'm going to triage as a result.

**Comment by MuhammadASif011** [comment] 2023-07-25 02:47
Hello, If you need my help to fix this task, so please let me know. Thank you
[$1000] Money request page crash after sign in #23420 - Expensify

Upwork profile: https://www.upwork.com/freelancers/~01ef98c02265da3b6f

**Comment by kayowakmelese** [comment] 2023-07-25 04:00
Hello, we can solve the issue by modifying this code   
//Check if props.iou.currency exists, otherwise, use the default currency (USD)
const selectedCurrencyCode = props.iou.currency || 'USD';

**Comment by kayowakmelese** [comment] 2023-07-25 04:03
Contributor details
Your Expensify account email: kayomelese4@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01393ae9100dff9b33

**Comment by kayowakmelese** [comment] 2023-07-25 04:08
Contributor details
Your Expensify account email: kayomelese4@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01393ae9100dff9b33

**Comment by kayowakmelese** [comment] 2023-07-25 04:09
Contributor details
Your Expensify account email: kayomelese4@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01393ae9100dff9b33

**Comment by MuhammadASif011** [comment] 2023-07-25 04:40
Contributor details
 Expensify account email: asifsuperior43@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ef98c02265da3b6f

**Comment by flyingmorrow** [comment] 2023-07-25 09:02
It is snap to fix it I think.
In this case error occurred due to variable of currency.
check currency variable and prevent case that can not be undefined then it can be fixed easily I think.
I can fix it rapidly.
Please kindly send me mail to handsome.sladar@gmail.com
then I can fix it right now.
Thank you.

**Comment by madmax330** [comment] 2023-07-31 12:44
Hmmm, I'm not able to assign @bernhardoj for some reason...
@bernhardoj can you comment on the issue or something?

**Comment by rushatgabhane** [comment] 2023-08-08 04:16
I don't think this was the current fix

**Comment by trjExpensify** [comment] 2023-08-30 17:45
👋 @JmillsExpensify can you reduce the payment for @bernhardoj by 50% when you pay this please? 

We missed a regression [here](https://github.com/Expensify/App/issues/24216#issuecomment-1699465126) and I already settled up. Thanks!

**Comment by JmillsExpensify** [comment] 2023-10-16 15:37
Payment summary:

 - Issue reporter: @bernhardoj $250
 - Contributor: @bernhardoj $1,000 (incl. urgency bonus; overpaid $500 [here](https://github.com/Expensify/App/issues/24216#issuecomment-1699465126))
 - Contributor+: @allroundexperts $1,500 (incl. urgency bonus)

I'll issue an offer to @bernhardoj based on this amount. Please comment on this issue if you feel that's incorrect.

**Comment by JmillsExpensify** [comment] 2023-10-16 15:38
Then @allroundexperts looks like you owe us a BZ checklist on this issue, including suggestion on regression test.

**Comment by JmillsExpensify** [comment] 2023-10-16 15:40
Alright, Upwork offers are paid out. I'm going to close this issue but I'll still keep tabs on follow-up since I'll have to process a payment for C+ via NewDot.

**Closed by JmillsExpensify** 2023-10-16 15:40 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2023-10-23 16:43
That seems like a pretty basic regression test. I think it's already covered given that we are testing requesting before each deploy.

**Comment by JmillsExpensify** [comment] 2023-10-23 16:43
$1,500 payment approved for @allroundexperts based on summary above.
