### ISSUE TITLE
[HOLD for #21488][$1000] Web - No users displayed until the emoji is reacted for the second time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22127] opened 2023-07-03 18:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new room on PUBLIC mode
3. (Imp step) - On the room, send a message and react with an emoji
4. Click on header, copy the URL.
5. Login in another web chrome and login with user B and paste the URL so that the room can be accessible to User B
6. From user B, react with some another emoji to the same message sent by User A
7. Now open an incognito window and as an anonymous user, paste the room URL
8. On incognito, Right-click on the emoji reaction on the message and notice that it displays empty list
9. But now, again from User A, react the same previous message with some other emoji
10. On Incognito , again right click on the emojis reacted by User A and notice that this time it displays the username/email of User A
11. But if you right click on emoji reacted by User B, you'll still not be able to see the username/email of User B.
12. Thus, for a emoji reaction list to occur , User A/ User B needs to react with emoji the second time after an anonymous user opens the room

## Expected Result:
Users should be displayed in the first time only

## Actual Result:
No users displayed until the emoji is reacted for the second time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cd713879-60ef-4203-9ac1-b00abdc26529

https://github.com/Expensify/App/assets/93399543/47fe0592-3dbb-49de-bc13-3df29a4f5f72

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688285170064149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4a0c03c92592a89</li>
        <li>Upwork Job ID: 1676417484622086144</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-05 02:27
Reproduced:

https://github.com/Expensify/App/assets/59587260/1ccb9466-576e-4589-b95a-0db2c4fda1ea

**Comment by alitoshmatov** [comment] 2023-07-05 08:03
We have similar issue here - https://github.com/Expensify/App/issues/21488. 
I think root cause is the same, Where backend is not sending `personalDetailsList`

**Comment by kadiealexander** [comment] 2023-07-10 05:43
@thesahindia thoughts on putting this on hold for #21488?

**Comment by kadiealexander** [comment] 2023-07-21 02:21
This was fixed with #21488 - no longer reproducible:

https://github.com/Expensify/App/assets/59587260/ec18eb6e-4ec2-4304-ae45-5a1d2d33f963

**Closed by kadiealexander** 2023-07-21 02:21 UTC
Labels: External, Weekly, Overdue, Bug
