### ISSUE TITLE
[$250] Hide video playback controls on auto-playing videos

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42323] opened 2024-05-16 21:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715816175965469

## Action Performed:
1. On a new account, tap green (+) button
2. Tap "Track Expense"
3. Observe bottom sheet w/video about how to Track expense playing with controls obscuring the video

## Expected Result:
The controls on the video shouldn't have the controls showing by default
## Actual Result:
For videos auto-playing on mobile devices the controls should only show once the user taps the video.
In the attachment modal it's worth showing the playback controls, but they should still fade out after 2s
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/570c0bb5-b93f-4cc9-9f05-045b6b218bbf

https://github.com/Expensify/App/assets/38435837/bcea0cd1-d667-49e1-a24a-205166f726d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db5e669ade628193</li>
        <li>Upwork Job ID: 1792927198372831232</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 102529999</li>
<li>tienifr | Contributor | 102638224</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by neonbhai** [comment] 2024-05-16 21:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hide video playback controls on auto-playing videos 

### What is the root cause of that problem?
We don't hide the video controls in feature training modals here:
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/FeatureTrainingModal.tsx#L137

### What changes do you think we should make in order to solve the problem?
We should change to always hide, using the const.



### Alternatively
We can use a prop to determine showing of controls, if any feature training modal needs it

**Comment by dubielzyk-expensify** [comment] 2024-05-20 00:26
In the proposal here the controls fade out too quickly. When tapping the player, the controls should stay visible fully for `2 seconds` (or `2.5 seconds`) and fade out for `500 ms`.

**Comment by dubielzyk-expensify** [comment] 2024-05-20 05:38
Cool. What does that mean? Is this not the PR to implement it?

**Comment by rojiphil** [comment] 2024-05-27 16:35
@tienifr Why do we need another state `controlStatusState` when we can use `shouldPlay` to determine if we need to show the controls initially or not?

**Comment by bfitzexpensify** [comment] 2024-05-30 17:11
Adding a second BZ team member to keep an eye on this while I'm ooo until June 11th. 

Currently in the proposal review stage.

**Comment by rojiphil** [comment] 2024-05-30 19:27
I will review and share an update on this tomorrow my day

**Comment by alexpensify** [comment] 2024-06-03 23:43
@rojiphil any news here? Thanks!

**Comment by rojiphil** [comment] 2024-06-06 17:24
> > when we can use shouldPlay to determine if we need to show the controls initially or not?
> 
> I don't think so. The controls are displayed based on `controlStatus`, not a `shouldPlay`, see [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/VideoPlayer/BaseVideoPlayer.tsx#L366). Please correct me me I was wrong.

Ok. I think we should not depend on `shouldPlay` to decide on displaying controls.

**Comment by rojiphil** [comment] 2024-06-06 17:27
This is an improvement to an existing video player and @tienifr [proposal](https://github.com/Expensify/App/issues/42323#issuecomment-2116490326) is good enough to get this moving. 
Fine-tuning the implementation and design team approval can be done in the PR stage. 
🎀👀🎀 C+ reviewed

**Comment by alexpensify** [comment] 2024-06-11 22:57
Weekly update: The PR is ready for review.

**Comment by alexpensify** [comment] 2024-06-18 21:55
Weekly update: The PR is going through the review process.

**Comment by alexpensify** [comment] 2024-06-25 20:36
Weekly update: The PR is moving along through the process with no delays.

**Comment by alexpensify** [comment] 2024-07-02 16:46
Weekly Update: More feedback in the PR, but moving forward

**Comment by alexpensify** [comment] 2024-07-09 21:44
Weekly Update: Moving back to weekly. @rojiphil the PR is ready for another review. Design confirmed the recent updates are good.

**Comment by alexpensify** [comment] 2024-07-16 22:04
Weekly Update: The PR is moving along in the review process.

**Comment by alexpensify** [comment] 2024-07-23 22:23
Weekly Update: The PR is still being reviewed.

**Comment by alexpensify** [comment] 2024-08-01 01:07
Weekly Update: The PR is moving through reviews

**Comment by alexpensify** [comment] 2024-08-07 21:47
Moving back to Weekly since the PR is in the review process

**Comment by alexpensify** [comment] 2024-08-13 22:03
Weekly Update: QA steps are under review

**Comment by alexpensify** [comment] 2024-08-21 19:28
@bfitzexpensify - I realized you are back online, so I'm exiting the stage here. Thanks!

**Comment by rojiphil** [comment] 2024-08-22 17:34
@bfitzexpensify @MariaHCD Since it is pay time here, I wanted to put forward a request to increase the compensation considering the amount of effort we spent in fine-tuning the video player. 
Would $1000 sound fair?

Reasoning:

1. Over a while, we identified improvements in 10 different use cases as captured in the test case description [here](https://github.com/Expensify/App/pull/43349#issue-2343490116)
2. This required us to repeat review and tests for 6 times as mentioned here ([1](https://github.com/Expensify/App/pull/43349#issuecomment-2167315972), [2](https://github.com/Expensify/App/pull/43349#issuecomment-2192017231), [3](https://github.com/Expensify/App/pull/43349#issuecomment-2202973548), [4](https://github.com/Expensify/App/pull/43349#issuecomment-2205785334), [5](https://github.com/Expensify/App/pull/43349#issuecomment-2235736094), [6](https://github.com/Expensify/App/pull/43349#issuecomment-2255006695))

**Comment by bfitzexpensify** [comment] 2024-08-30 11:06
@MariaHCD I'll defer this to you - do you think the work described in the comment above is 4x what we'd usually expect?

**Comment by MariaHCD** [comment] 2024-09-02 10:05
I think the work done was definitely thorough and entailed quite a few improvements for the video player but I think it warrants a 2x increase (not 4x), in my opinion.

**Comment by rojiphil** [comment] 2024-09-06 15:27
> $500 to be paid to @rojiphil for contributor work - offer sent via Upwork

@bfitzexpensify Accepted offer as C+ reviewer. Awaiting payment. Thanks.

**Comment by bfitzexpensify** [comment] 2024-09-06 15:29
Paid out. Closing this one out.

**Closed by bfitzexpensify** 2024-09-06 15:29 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by garrettmknight** [comment] 2024-09-11 18:52
$250 approved for @tienifr
