### ISSUE TITLE
[Workspace Feeds] Expensify Card - Reconciliation account link directs to hmm not here page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46108] opened 2024-07-24 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11
**Reproducible in staging?:** y
**Reproducible in production?:** New feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home

2. Tap profile icon -- workspaces - workspace
3. Tap more features - enable expensify card
4 Tap expensify card
5.Tap settings -- settlement account
6.Tap Reconciliation account link

## Expected Result:
Reconciliation account link must not direct to hmm not here page

## Actual Result:
Reconciliation account link directs to hmm not here page

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/99e24dec-d3ae-4e4c-876e-7ae5b1ae765c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2024-07-24 14:45
Looks like a new page created in https://github.com/Expensify/App/pull/45415 - pinging @koko57 @allgandalf @mountiny @MariaHCD

**Comment by koko57** [comment] 2024-07-24 14:47
Not a deploy blocker, we're still working on this project

**Comment by dangrous** [comment] 2024-07-24 14:48
ah okay great! I'll remove the labels

**Comment by dangrous** [comment] 2024-07-24 14:49
do you want me to assign y'all to this or will you handle as part of the implementation issues?

**Comment by mountiny** [comment] 2024-07-24 14:50
Happy to take over to handle this

**Comment by trjExpensify** [comment] 2024-07-25 12:59
Do we need this issue then, @mountiny?

**Comment by mountiny** [comment] 2024-07-25 23:17
@allgandalf I will make it weekly but I think its better to have this reminder than the comment in code

**Comment by koko57** [comment] 2024-08-07 09:30
Still waiting fot the BE

**Comment by trjExpensify** [comment] 2024-08-07 10:06
What command are you waiting on? Is it `ToggleCardContinuousReconcilation`?

**Comment by koko57** [comment] 2024-08-07 10:23
yup!

**Comment by koko57** [comment] 2024-08-07 15:17
After merging this PR https://github.com/Expensify/App/pull/46978 this issue won't be reproducible

**Comment by koko57** [comment] 2024-08-08 07:07
https://github.com/Expensify/App/pull/46978 is merged, it can be retested now

**Comment by mountiny** [comment] 2024-08-13 13:39
Closing as this should be fixed now, we can revisit if not

**Closed by mountiny** 2024-08-13 13:39 UTC
Labels: Engineering, Weekly, Bug
