### ISSUE TITLE
[Held on #20354] [$500] Chat – Second user is highlighted when create a group using keyboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38216] opened 2024-03-13 11:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4417998
**Email or phone of affected tester (no customers):** ponikarchuks+713324@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Сlick on FAB
4. Click on "Start Chat"
5. Use the arrow keys, tab key and Enter to select multiple results from the contact lists (at list 3 accounts)

## Expected Result:
Selected user is highlighted when create a group using keyboard

## Actual Result:
Second user is highlighted when create a group using keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2d9dbb67-ef8b-4414-b9cd-7e6f0409d205

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015834298cf682f992</li>
        <li>Upwork Job ID: 1769865643699728384</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-13 11:28
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-13 11:29
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by dragnoir** [comment] 2024-03-13 12:44
HOLD for https://github.com/Expensify/App/pull/34356

**Comment by s77rt** [comment] 2024-03-19 15:58
Holding on https://github.com/Expensify/App/issues/20354 since https://github.com/Expensify/App/pull/34356 is reverted

**Comment by anmurali** [comment] 2024-03-25 14:56
Changed the title accordingly. Still holding as https://github.com/Expensify/App/issues/20354 is in progress

**Comment by s77rt** [comment] 2024-04-05 22:03
New PR that we are holding on is still open https://github.com/Expensify/App/pull/38610

**Comment by s77rt** [comment] 2024-04-10 21:11
Holding on https://github.com/Expensify/App/pull/38610
@anmurali Can you change the title to "HOLD" instead of "Held"

**Comment by s77rt** [comment] 2024-04-19 22:41
https://github.com/Expensify/App/pull/38610 is merged. Bug no longer reproducible. Let's close this @anmurali

**Comment by s77rt** [comment] 2024-04-29 16:35
We can close this one @anmurali

**Comment by mvtglobally** [comment] 2024-05-01 13:59
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-05-06 19:51
Issue not reproducible during KI retests. (Second week)

**Comment by s77rt** [comment] 2024-05-11 14:51
To be closed

**Comment by mvtglobally** [comment] 2024-05-13 14:03
Issue not reproducible during KI retests. (Third week)

**Comment by s77rt** [comment] 2024-05-20 19:29
@anmurali We can close this

**Comment by mvtglobally** [comment] 2024-05-22 04:36
Issue not reproducible during KI retests. (Forth week)

**Comment by s77rt** [comment] 2024-05-29 22:00
To be closed

**Comment by mvtglobally** [comment] 2024-05-30 01:24
Issue not reproducible during KI retests. (Fifth week)

**Comment by s77rt** [comment] 2024-06-08 11:50
To be closed

**Comment by s77rt** [comment] 2024-06-17 23:20
@anmurali Please close this

**Comment by s77rt** [comment] 2024-06-26 21:02
To be closed

**Comment by mvtglobally** [comment] 2024-07-03 14:37
Issue not reproducible during KI retests. (6th week)

**Comment by s77rt** [comment] 2024-07-05 21:44
To be closed

**Comment by mvtglobally** [comment] 2024-07-11 03:54
Issue not reproducible during KI retests. (7th week) Are we ok to close this?

**Comment by s77rt** [comment] 2024-07-15 10:56
@anmurali Can you please close this one

**Comment by mvtglobally** [comment] 2024-07-19 03:17
Issue not reproducible during KI retests. (8th week) 
Closing as there has been no action on this at all for an extended period. 
@anmurali  pls feel free to reopen.

**Closed by mvtglobally** 2024-07-19 03:17 UTC
Labels: External, Weekly, Help Wanted, Bug
