### ISSUE TITLE
[$500] Search - Reply in thread on invite message displays undefined/fake in search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29567] opened 2023-10-13 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83.10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697184595029359

## Action Performed:
1. Open the app
2. Open any workspace chat in which you were invited
3. Hover on invited message and click on reply in thread
4. Open search and observe that below reply in thread report, undefined/fake is displayed

## Expected Result:
App should display workspace name or user email below reply in thread report in search which has no messages

## Actual Result:
App displays undefined/fake below reply in thread report in search for reply in thread on invite message

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/0309fe16-e6e4-447e-9c39-ac2cc67132cf

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/b5e1a174-3280-4ebb-a14e-2bb197208bb7

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/5d73a780-fb1d-4d42-a2d2-bd44c7119e41

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/93399543/132cbaba-171a-4c39-9986-db470cda35a2

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/d28f8843-88c6-4208-b613-b025cf12ada6

https://github.com/Expensify/App/assets/93399543/f6dbbbc2-47f9-4736-bfd3-4e8082e5ecde

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/79a69e0c-5a71-42ea-b271-d2826fd8750a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168e11378d36ee4bc</li>
        <li>Upwork Job ID: 1712825221601480704</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by s-alves10** [comment] 2023-10-13 17:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When replying in thread on invite message in workspace chat, undefined/fake appears in chats search

### What is the root cause of that problem?

For policy chat, we show `lastMessageText` as `alternateText` as you can see below
https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/OptionsListUtils.js#L508

`lastMessageText` consists of `{actor}: {message}`
https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/OptionsListUtils.js#L492-L495

When creating a new thread, `lastActorAccountID` is set to 0 as you can see
https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/ReportUtils.js#L2620

This is the root cause

### What changes do you think we should make in order to solve the problem?

For threads, we can use the `actorAccountID` of `parentReportAction` as `lastActorAccountID` if `lastActorAccountID` is empty(0)
Update 
https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/OptionsListUtils.js#L493
to
```
        let lastActorAccountID = report.lastActorAccountID;
        if (result.isThread) {
            if (!lastActorAccountID) {
                const parentReportAction = ReportActionUtils.getReportAction(report.parentReportID, report.parentReportActionID);
                lastActorAccountID = lodashGet(parentReportAction, 'actorAccountID', 0);
            }
        }
        const lastActorDetails = personalDetailMap[lastActorAccountID] || null;
```

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/d066018c-f775-4053-9a1a-c996368d6460


</details>


### What alternative solutions did you explore? (Optional)
We can set `parentReportAction.actorAccountID` to `lastActorAccountID` when creating a thread

**Comment by rojiphil** [comment] 2023-10-13 17:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When `reply in thread` is done on a workspace invite message, the search page displays undefined/fake as subtitle.

### What is the root cause of that problem?

As shown [here](https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/OptionsListUtils.js#L493C1-L494C173), we initialise the `lastMessageText` with the last actor’s display name. Now, since we are dealing with a whisper action that does not have all the required data, `lastActorAccountID` within report will contain 0. The local storage uses the display from within the personal details map which will return `__fake__`. 

Further, as shown [here](https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/OptionsListUtils.js#L508), since `lastMessageText` contains fake value, it will get assigned. This is the root cause for displaying fake text in search page. 

### What changes do you think we should make in order to solve the problem?

1) We can ignore invalid actor account id by checking if the value is 0 by making changes [here](https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/OptionsListUtils.js#L493) like this below. This way, `lastMessageText` will not contain fake value.

```
	const lastActorDetails = report.lastActorAccountID !== 0 ? personalDetailMap[report.lastActorAccountID] || null : null;

```

2) Additionally, the `subtitle` will return `empty` for thread as shown [here](https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/libs/ReportUtils.js#L1876). We can additionally check for `isPolicyExpenseChat` as shown below so that the workspace name can be displayed

```
    if (isChatThread(report) && !isPolicyExpenseChat(report)) {
        return '';
    }

```

### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-10-16 12:04
I'm OOO Oct 16-23. Adding leave buddy

Status: looking for proposals

**Comment by conorpendergrast** [comment] 2023-10-18 12:24
@eVoloshchak do you agree [this is a BE issue](https://github.com/Expensify/App/issues/29567#issuecomment-1762856604)?

**Comment by rojiphil** [comment] 2023-10-19 02:28
> When we first create a thread, the last actor ID is 0, this is because there is no one sending a message yet.

@bernhardoj 
I do not understand how this is a BE issue. Maybe, I am missing something here.
As I understand, `lastActorAccountID` being set to 0 is the root cause. 
Here, what do you expect the BE to set the value of `lastActorAccountID`?  

cc @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-10-23 13:17
Looking into this shortly

**Comment by conorpendergrast** [comment] 2023-10-27 20:34
@sonialiap You're back! Unassinging myself. Status is that @eVoloshchak is next to look into this

**Comment by eVoloshchak** [comment] 2023-10-30 10:25
Looks like this isn't reproducible anymore

https://github.com/Expensify/App/assets/9059945/780eacff-9d05-48e5-9d38-af455751c1f9

@tienifr, @s-alves10, @rojiphil, @bernhardoj, could you please check is the issue is still present for you? Thanks!

**Comment by sonialiap** [comment] 2023-11-01 13:51
Testing to see if I can reproduce

**Comment by sonialiap** [comment] 2023-11-01 13:58
I cannot reproduce this. Closing. Please reopen if you can reproduce it

**Closed by sonialiap** 2023-11-01 13:58 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by twisterdotcom** [comment] 2023-11-16 21:53
https://github.com/Expensify/App/issues/30744#issuecomment-1815373465
