### ISSUE TITLE
Android - Chat - In mweb, cursor is visible on @user but not visible in Android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47733] opened 2024-08-20 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app in Android and mweb
2. Tap on a chat
3. Enter eg : @[jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
4. Note the message is filled with blue background
5. Just keep on different characters in email id and note cursor is visible

## Expected Result:
Cursor must be visible on @user in both mweb and Android

## Actual Result:
In mweb, cursor is visible on @user but not visible in Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/34103c18-de1f-4de4-9750-5352ce5877c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-20 17:34
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-20 17:34
We think that this bug might be related to #vip-vsp

**Comment by OfstadC** [comment] 2024-08-21 20:19
Looking into this now

**Comment by OfstadC** [comment] 2024-08-22 19:23
Can't reproduce - maybe because i'm using browserstack? I'm OoO tomorrow - but will try again Monday AM

**Comment by OfstadC** [comment] 2024-08-26 19:41
Going to test on physical android device

**Comment by OfstadC** [comment] 2024-08-27 18:31
Okay I was able to reproduce - but I imagine this is pretty low priority since an indicator of where the cursor is (the little green bubble arrow thing 😅) is still visible - and it's only limited to the highlight. 

This would also fall under VIP VSB which is on hold so going to close this for now

**Closed by OfstadC** 2024-08-27 18:31 UTC
Labels: Daily, Bug
