### ISSUE TITLE
[$500] Workspace - "Plaid" popup and "Steapline payments" tab appears for short time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33702] opened 2023-12-28 11:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18.1
**Reproducible in staging?:** Y
**Reproducible in production?:**  N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Start to add bank account with Plaid
4. Use Regions bank
5. Complete the flow until the "Connect bank account" step

## Expected Result:
The tab and popup shouldn't be visible.

## Actual Result:
"Plaid" popup and "Steapline payments" tab appears for short time after clicking the "Allow" button. On mWeb, only the "Steapline payments" tab appears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ead6f74b-e8d8-48b5-941f-a050b66d5b17

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138dc87e929ab95b9</li>
        <li>Upwork Job ID: 1740336625461047296</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-12-28 12:34
Dupe of https://github.com/Expensify/App/issues/32356

**Comment by mountiny** [comment] 2023-12-28 20:32
this is dupe of https://github.com/Expensify/App/issues/32356 which is on hold

**Closed by mountiny** 2023-12-28 20:32 UTC
Labels: External, Engineering, Hourly, Help Wanted, Bug
