### ISSUE TITLE
Concierge - Confirmation buttons does not response on Concierge message to create #room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42785] opened 2024-05-29 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a105@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on the green + button> Start chat> Room
2. Create room with "This #room is to send cute cat memes"
3. Edit description by adding more text
4. Change the room name
5. Verify that Concierge message with content "Heads up, #room doesn't exist yet. Do you want to create it?" appears with two options "Yes" and "No"
6. Click on "Yes"

## Expected Result:
"Yes" button should be responsible

## Actual Result:
"Yes" button does not response. The button keep appearing when click on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/60e3ce3b-e7b7-469b-bb0c-a891ceaed9bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-29 18:11
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment] 2024-06-05 00:26
<img width="1068" alt="image" src="https://github.com/Expensify/App/assets/14225673/d4439a0c-7172-414e-bba3-6a822f9c8f16">
I am not getting a concierge message..

**Comment by anmurali** [comment] 2024-06-11 18:33
I cannot reproduce, so closing.

**Closed by anmurali** 2024-06-11 18:33 UTC
Labels: Daily, Overdue, Bug
