### ISSUE TITLE
Task – Green dot is present in LHN when reassign task to another user as user B of the group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42193] opened 2024-05-15 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4561836
**Email or phone of affected tester (no customers):** applausetester+jpcategory@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Open group chat and create task without assignee
4. As user B of the group open task details and assign it to me
5. Verify that green dot appears in LHN
6. As user B reassign task to any other user
7. Observe the LHN

## Expected Result:
Green dot disappears in LHN when reassign task to another user as user B of the group

## Actual Result:
Green dot is present in LHN when reassign task to another user as user B of the group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b2bdc812-80bb-462b-a68c-af315110c037

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-15 13:18
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment] 2024-05-20 11:12
If we are reassigning the task from one user to another, we want the green brick Road to show so that the user knows they have a new action waiting on them. Not a bug -- closing.

**Closed by zanyrenney** 2024-05-20 11:12 UTC
Labels: Daily, Overdue, Bug

**Comment by kbecciv** [comment] 2024-06-25 15:30
Hey @zanyrenney! Can you create a GH issue for the TR update? We currently have steps indicating that a green dot should be present when a user reassigns a task to another DM participant -  https://expensify.testrail.io/index.php?/cases/view/2661775
