### ISSUE TITLE
[Awaiting C+ Payment Confirmation] [HOLD for payment 2023-07-20] [$1000] Task - Green dot doesn't get removed from an archived taskReport row in the LHN 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22029] opened 2023-07-01 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select Assign task
2. Enter title and assign it to yourself
3. Share it in in any other DM
4. Click Confirm Task
5. Go to the taskReport that appears in the LHN with a green dot
6. Click on three vertical dots icon
7. Click Cancel 

## Expected Result:
The green dot is removed from the archived taskReport row in the LHN

## Actual Result:
The taskReport gets archived but the green dot remains on the LHN row

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6bc3bd60-5e3e-49d9-bc01-cd1c95f02be2

https://github.com/Expensify/App/assets/93399543/af896416-7a15-495c-99dc-b18fae6a1a16

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688223588004229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159e4c66c12746e63</li>
        <li>Upwork Job ID: 1676263892823867392</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-04 14:16
Hm, I don't see the green dot on the taskReport row in the LHN at all as the creator in this scenario - which I think makes sense, right? The action is on the person I assigned the task to:

@thienlnam can you confirm on this? 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/9752a8e5-174f-4266-8c5a-17e6fdb360a7">

**Comment by trjExpensify** [comment] 2023-07-04 15:34
Hm, I wasn't using expensifail, but my own private domain on `trj.chat`. 

I just tried with a gmail account and I can't even open the taskReport: 

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/a0cb65a6-e45c-4ea2-8f6c-5c3c80f08828">
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/299414f4-f1b8-448d-a084-7382d091389b">

**Comment by trjExpensify** [comment] 2023-07-04 15:41
I did create a task from the gmail account.

**Comment by trjExpensify** [comment] 2023-07-04 16:15
Erm, that's a different case. If I'm assigning a task to myself, then the action is on me as the assignee and therefore I should see a green dot initially. These are the steps provided: 

> 1. Click + icon and select Assign task
> 2. Enter title and assign it to a user
> 3. Click Confirm Task
> 4. Go to task report
> 5. Click on three vertical dots icon
> 6. Click Cancel 

We should be able to reproduce following them exactly, if step 2 requires a specific account type (public versus private domain) or assigning a **task to yourself** to reproduce it, that's important information to convey in the bug report steps. 

> **Repro steps**
> 1. Click + icon and select Assign task
> 2. Enter title and assign it to yourself
> 3. Share it in in any other DM
> 3. Click Confirm Task
> 4. Go to the taskReport that appears in the LHN with a green dot
> 5. Click on three vertical dots icon
> 6. Click Cancel 

>**Expected results:**

>The green dot is removed from the archived taskReport

> **Actual results:**

>The taskReport gets archived but the green dot remains on the LHN row

https://github.com/Expensify/App/assets/16232057/f27364c6-fa5b-423f-a4cb-d5a832143a96

P.S - using a public domain wasn't required to actually reproduce this, so I left those out of the steps.

**Comment by pecanoro** [comment] 2023-07-05 16:29
Agreed, seems like a good solution! Assigning @hungvu193

**Comment by trjExpensify** [comment] 2023-07-19 20:25
I wouldn't say it's an edge case to assign a task to yourself somewhere and then cancel the task, but I agree it's a new feature. 

On that topic, @thienlnam, where are you at with adding a suite of regression tests for the tasks feature as part of the project?

**Comment by thienlnam** [comment] 2023-07-19 20:39
I have an issue for applause to add it - https://github.com/Expensify/Expensify/issues/294769

**Comment by trjExpensify** [comment] 2023-07-19 21:59
Excellent! Do you want to add [this one](https://github.com/Expensify/App/issues/22029#issuecomment-1641608148) to that suite?

**Comment by thienlnam** [comment] 2023-07-19 22:03
Donezo

**Comment by trjExpensify** [comment] 2023-07-20 23:15
Thanks! Payments as follows: 

@adeel0202 - $250 for the bug report - offer sent 
@hungvu193 - $1,500 for the fix - paid! 
@thesahindia - over to you to request $1,500.

**Comment by trjExpensify** [comment] 2023-07-21 10:11
Settled up with @adeel0202, closing!

**Comment by trjExpensify** [comment] 2023-07-24 11:01
No change since Friday, Melv. Though @thesahindia, want to confirm you've requested payment?

**Comment by trjExpensify** [comment] 2023-07-25 22:59
I think we keep these open until confirmed. CC: @JmillsExpensify

**Comment by trjExpensify** [comment] 2023-07-31 09:49
@JmillsExpensify have you approved this for payment.

**Comment by JmillsExpensify** [comment] 2023-08-01 05:40
I don't see any requests from @thesahindia, I don't think. Can you confirm?

**Comment by trjExpensify** [comment] 2023-08-01 14:42
Got it, definitely progress that one with the team in Slack!

**Comment by JmillsExpensify** [comment] 2023-08-02 04:36
@thesahindia Do you want to proceed with Upwork in the meantime? Or would you like to wait?

**Comment by trjExpensify** [comment] 2023-08-07 09:47
>I think this is the only ticket that is left open. I prefer we close the tickets so that no one has to keep waiting.

@JmillsExpensify you're closer to that process than I am. Should we be keeping these open until you post the approved confirmation on C+ payment?

**Comment by pecanoro** [comment] 2023-08-18 09:01
@trjExpensify @JmillsExpensify  Any updates? 😄

**Comment by trjExpensify** [comment] 2023-08-21 10:44
Thanks, @thesahindia. Glad you're feeling better!

**Comment by JmillsExpensify** [comment] 2023-08-24 05:23
Reviewed the details for @thesahindia. $1,500 approved for payment via NewDot based on the BZ summary above.

**Closed by JmillsExpensify** 2023-08-24 05:23 UTC
Labels: External, Weekly, Awaiting Payment, Bug
