### ISSUE TITLE
[$1000] Web - The working flow should be changed when reached request magic code limit

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21617] opened 2023-06-26 19:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open login form
2. Request magic code
3. Wait for the Timer ends and request new code
4. Repeat step 3 until reached the limit >> the error will show
5. Request new code again

## Expected Result:
When user reached request magic code limit, the function to request new code should be also disabled

## Actual Result:
The label "Didn't receive a magic code?" keep showing, so the user can click to request a new code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image - 2023-06-26T152102 420](https://github.com/Expensify/App/assets/93399543/cbea82eb-0d28-41ad-8803-4e0c65eb091b)

https://github.com/Expensify/App/assets/93399543/667edbbf-2e7b-47e7-b4db-8bf81e556f0e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687454317395259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01809ee3e44fc82cdd</li>
        <li>Upwork Job ID: 1673756075822219264</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-27 17:57
This is a dupe of https://github.com/Expensify/App/issues/21631

**Comment by tranvantoan-qn** [comment] 2023-06-27 18:07
@Christinadobrzyn 
My report was created before that report - about 2 hours :d , So that issue should be a duplicate of mine
So, what do you think? 
<img width="1027" alt="My report" src="https://github.com/Expensify/App/assets/10254571/58a340d8-e361-48eb-bb9a-4b7cfb75f174">
<img width="1120" alt="NAT" src="https://github.com/Expensify/App/assets/10254571/5af7f7d9-6034-4061-b035-853c8542a5e2">

**Comment by Christinadobrzyn** [comment] 2023-06-27 18:08
Sure, that's fine - I'll close mine and we can test here. 

@tranvantoan-qn I think we need to decide what we want this expected behaviour to be. 

- Should the timer be changed to count down a longer amount of time (to coincide with the message) > after which the user can request another magic code?
- Should the timer disappear and they need to reach out to concierge@expensify.com?

**Comment by tranvantoan-qn** [comment] 2023-06-27 18:14
@Christinadobrzyn 
THANK YOU!!!

I think it depends on the complexity:
- **Less complexity**: We can just hide the timer, so the user has to wait to go back to the main login form and start over (the form with the email field)
**- More complexity:** If we know how long the user has to wait, we can show the timer duration as that long. This is more complexity but give the user more context and information

**Comment by Christinadobrzyn** [comment] 2023-06-27 18:15
Sorry, didn't mean to add the eng label.

**Comment by kevinksullivan** [comment] 2023-07-03 20:28
@rushatgabhane can you provide an update on your review?

**Comment by kevinksullivan** [comment] 2023-07-06 16:13
bumping in slack

**Comment by chiragsalian** [comment] 2023-07-06 20:34
Hmm, i don't follow how the proposal is good. If we increase the counter to 5mins, then 5 minutes later there is a chance the user can still see the same message no?

Okay lets put some numbers here to make an easier decision. This is what i believe is the backend behavior,
1. Auth checks if the user has requested a validate code 5 times within 30mins. If the user requests for more validate codes within 30 minutes, they will get throttled, PHP will receive 401 error and newDot will see the error message "You've reached the maximum number..."
2. Each validate code is valid for 7 days i believe.

We could increase the timer to 30 minutes and then the user will definitely not see the error, but that's not a good solution either because is user does attempt1 - 1 min mark, attempt2 - 3 min mark.... attempt5 - 29 minute mark, then instead of waiting 1 minute, the user would end up having to wait 30 minute if we increase timer by 30 minutes.

> The backend should return an error code instead of the full error text.

I agree with this. Especially because this should be translated text so that it can be displayed in Spanish too.

So as i think about this, is the proposal to increase to 5 minutes, just so that the probability of the user hitting the rate limit is lower? If so I'm okay with it. I agree we should not disable the button since the user needs it to retry receiving a magic code later.

> do you think we should hide the resent button and the timer, instead of showing a 5 min timer?

No we should not hide/disable the request a new code button or timer since the user should be able to use it slightly later.

Also is it just me or is the video in the description unrelated? It shows changing the screen from large to small updating the timer render which looks like a different problem.

My ideal solution,
1. Auth returns the exact time remaining to not be throttled. (like 25 minutes. Note for self - NVP is `private_throttleAttempts_resendValidateCode` and we need to return +1ms of the first entry)
2. We update the message to say "You've reached the requested maximum number of magic codes for a timeframe. Please wait until the timer reaches 0 and try again." (will need to involve others for a language check)
3. The moment the countdown ends and the user attempts "Request a new code" it should work since they are outside their throttle timeframe.

But ideal solution sounds like more effort for maybe not too much gain so I'll defer to @tjferriss and @kevinksullivan if we want an ideal solution. I personally like the ideal solution since i think its more accurate user feedback but we might have to discuss this in #product to ensure everyone is on the same page.

If we're not doing ideal solution i think we should do nothing since the user can get the same error 5 minutes later. Increasing the counter to lower the probability of the error is not a big win in my opinion. Although i think we should open another issue to return error code so that the error message can be translated on the front end since its bad that it doesn't support Spanish atm.

Thoughts? 🙂

**Comment by tjferriss** [comment] 2023-07-10 17:43
>I personally like the ideal solution since i think its more accurate user feedback but we might have to discuss this in #product to ensure everyone is on the same page.

I agree with your summary @chiragsalian. Magic sign-in codes are big part of our security which we want to get right so I think it's worth the extra effort to make it clearer to the user what is happening.

**Comment by tjferriss** [comment] 2023-07-12 05:57
@chiragsalian how do you want to proceed? Should we take this to #product to get more eyes on it?

**Comment by rushatgabhane** [comment] 2023-07-13 05:32
> If we're not doing ideal solution i think we should do nothing 

@chiragsalian agree with your reasoning. I'm in favor of closing this one because the ideal solution doesn't add too much value

**Comment by kevinksullivan** [comment] 2023-07-17 15:41
Going to unassign myself here because we have two BZs.

**Comment by tjferriss** [comment] 2023-07-24 22:58
@rushatgabhane @chiragsalian are we looking for proposals at this point?

**Comment by tjferriss** [comment] 2023-07-25 22:28
Got it. @chiragsalian are you going to pick this up or should we re-assign internally?

**Comment by tjferriss** [comment] 2023-08-01 21:33
@chiragsalian friendly bump here on next steps.

**Comment by tjferriss** [comment] 2023-08-09 04:43
@chiragsalian another bump on this one...

**Comment by chiragsalian** [comment] 2023-08-09 17:52
Sorry im on parental leave. I'll be back August 17th. We can either wait for me to come back to implement this or reassign internally for an engineer to implement the steps i mentioned [here](https://github.com/Expensify/App/issues/21617#issuecomment-1624275878).

**Comment by tjferriss** [comment] 2023-08-11 16:55
I think we can wait for you to return. I'm going to move the issue to weekly for now.

**Comment by tjferriss** [comment] 2023-08-23 17:29
@chiragsalian hope you had a good leave! Are you able to pick this issue back up?

**Comment by chiragsalian** [comment] 2023-08-23 22:24
Hey @tjferriss, sure i can work on this. I've posted in #product ([slack post](https://expensify.slack.com/archives/C03U7DCU4/p1692827863343569)) to get more eyes on this. Its a bit of a change so i want to make sure more people are aware of my proposal before i make the changes. Once more people approve it I'll tackle this issue.

**Comment by chiragsalian** [comment] 2023-08-24 17:48
Discussed on [slack](https://expensify.slack.com/archives/C03U7DCU4/p1692827863343569). The conclusion is that we are choosing not to make any changes to this flow right now. 
The reason being, at this time we do not want to show more information which would open us up to being hit more often by fraudsters.

I'm closing out this issue for now.

**Closed by chiragsalian** 2023-08-24 17:48 UTC
Labels: Engineering, Weekly, Internal, Bug
