### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Hold - Missing "Unhold" on the report header of held expense after it is moved to new report offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46371] opened 2024-07-27 23:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42573
## Action Performed:
Precondition:
- Workspace has an approver (can be workspace owner)
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit three expenses to the workspace chat
4. Hold two of the expenses
5. Click Submit button
6. Go offline
7. Click Approve
8. Approve partially (click the green approve button)
9. Go back to the main workspace chat
10. Click on the new report generated which contains the held expenses
11. Click on any of the held expense preview to go to transaction thread
12. Click on the report header

## Expected Result:
Unhold option should be present on the report details of the held expense after it is moved to a new report offline

## Actual Result:
hold option is missing on the report details of the held expense after it is moved to a new report offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/06be6eea-b1e7-4ed5-a9cc-14fd7796cb4f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154caef32a9b3ac64</li>
        <li>Upwork Job ID: 1817961052655862549</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103351156</li>
<li>cretadn22 | Contributor | 103351157</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by lanitochka17** [comment] 2024-07-27 23:10
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-07-29 04:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
hold option is missing on the report details of the held expense after it is moved to a new report offline

### What is the root cause of that problem?
The held requests are moved to a new expense report and a new report preview is also created. Still, we haven't updated the `parentReportActionID` of `optimisticExpenseReport` to the new report preview action.

https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/actions/IOU.ts#L6246

https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/actions/IOU.ts#L6254

Then `parentReportAction` is `undefined` here and the hold or unhold option doesn't appear
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/ReportDetailsPage.tsx#L122


Another bug here is we update the total of the new expense report as the amount of the first hold transaction and it's wrong

https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/actions/IOU.ts#L6250


### What changes do you think we should make in order to solve the problem?
1. After creating the optimistic expense report and report preview action, we should update the `parentReportActionID` of the expense report to the `reportActionID` of the new report preview action

```
optimisticExpenseReport.parentReportActionID = optimisticExpenseReportPreview.reportActionID;
```


https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/actions/IOU.ts#L6254

2. We should update the total of the new expense report as the total amount of all hold transactions instead of first transaction

```
const total = holdTransactions.reduce((prev, cur) => prev + cur.amount, 0);
const optimisticExpenseReport = ReportUtils.buildOptimisticExpenseReport(
    chatReport.reportID,
    chatReport.policyID ?? iouReport.policyID ?? '',
    recipient.accountID ?? 1,
    total * -1,
    getCurrency(firstHoldTransaction),
    false,
);
```
### What alternative solutions did you explore? (Optional)

**Comment by robertjchen** [comment] 2024-07-29 16:36
> We should update the total of the new expense report as the total amount of all hold transactions instead of first transaction if all transactions have the same currency.

There was some discussion on the report amounts [here](https://github.com/Expensify/App/issues/46310#issuecomment-2255435328) and why some of the behavior is intentional 🤔

**Comment by robertjchen** [comment] 2024-07-29 16:39
Also, a PR is in progress around [context menu](https://github.com/Expensify/App/pull/45151)s-  hopefully there's no overlap there as well?

I'm seeing if the fix here may also address this? https://github.com/Expensify/App/issues/41655

**Comment by ikevin127** [comment] 2024-07-29 16:46
♻️ Will review proposals today, check on possible overlap issues and see if it solves the other mentioned issue.

**Comment by ikevin127** [comment] 2024-07-30 02:11
> There was some discussion on the report amounts https://github.com/Expensify/App/issues/46310#issuecomment-2255435328 and why some of the behavior is intentional 🤔

Indeed, based on that comment I would not go out of scope in this issue - keep it contained to what this issue is about strictly.

> Also, a PR is in progress around https://github.com/Expensify/App/pull/45151 hopefully there's no overlap there as well?
> 
> I'm seeing if the fix here may also address this? https://github.com/Expensify/App/issues/41655

Regarding https://github.com/Expensify/App/pull/45151, took a quick-look and I don't think there are any conflicts between the work done there and this issue. @cdOut should be able to confirm whether or not my assumption is right.

Regarding https://github.com/Expensify/App/issues/41655 - I don't think there's any overlap here.

##

@cretadn22's [proposal](https://github.com/Expensify/App/issues/46371#issuecomment-2254369728) LGTM. The RCA was identified and the solution solves the issue.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-07-30 02:14
@nkdengineer In the future, please be mindful of the [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) as repeated failure in following the rules can lead to warnings and even removal from the contributor program.

> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

**Comment by nkdengineer** [comment] 2024-07-30 02:30
@ikevin127 Thanks for your feedback. I think my proposal is different from the selected proposal. The main ideal is the same but the implementation is different

Here is the alternative implementation from the selected proposal. It mentioned to use `optimisticExpenseReport.parentReportActionID` directly in `buildOptimisticReportPreview`

>An alternative approach is to use optimisticExpenseReport.parentReportActionID directly in buildOptimisticReportPreview instead of adding a new parameter. However, I prefer the previous approach because it is safer.


And here is my implementation
> After creating the optimistic expense report and report preview action, we should update the parentReportActionID of the expense report to the reportActionID of the new report preview action

That is why I posted a new proposal.

**Comment by cdOut** [comment] 2024-07-30 07:20
> Regarding #45151, took a quick-look and I don't think there are any conflicts between the work done there and this issue. @cdOut should be able to confirm whether or not my assumption is right.

Just wanted to confirm that there is indeed no overlap.

**Comment by alexpensify** [comment] 2024-07-31 22:22
@robertjchen we need your review here? Thanks!

**Comment by robertjchen** [comment] 2024-08-01 05:19
Let's do it 👍

**Comment by ikevin127** [comment] 2024-08-01 16:33
@cretadn22 Please let us know when we can expect a PR to be ready for review🧑‍💻

**Comment by alexpensify** [comment] 2024-08-05 21:00
Awesome, waiting for automation to kick in here.

**Comment by Christinadobrzyn** [comment] 2024-08-07 18:15
hey there! https://github.com/Expensify/App/issues/46896 was created while testing the [PR](https://github.com/Expensify/App/pull/46721). 

Should we treat https://github.com/Expensify/App/issues/46896 separately or fix it as part of this?

**Comment by ikevin127** [comment] 2024-08-11 01:08
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42573.
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42573#issuecomment-2282334519.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

**Precondition**: Workspace has an approver (can be workspace owner).

1. Go to workspace chat.
2. Submit three expenses to the workspace chat.
3. Hold two of the expenses.
5. Go **offline**.
6. Go back to the main workspace chat.
7. Click **Approve**.
8. Approve partially (click the green approve button for only compliant expenses).
9. The two held expenses should show underneath as optimistic.
10. Click on the new report generated which contains the two held expenses.
11. Click on any of the held expense preview to go to the transaction thread.
12. Click on the report header.
13. Ensure that the **Unhold** option is present.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment] 2024-08-14 07:41
cc @alexpensify

**Comment by alexpensify** [comment] 2024-08-14 17:56
Payouts due: 2024-08-14

- [ ] Contributor: $250 @cretadn22 
- [ ] Contributor+: $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~0154caef32a9b3ac64).

**Comment by alexpensify** [comment] 2024-08-14 18:01
I've completed the payment process via Upwork and will close this issue for now. Later this week, I'll create the regression test request.

**Closed by alexpensify** 2024-08-14 18:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
