### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Top part of the page becomes darker when user goes to the chats page  

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36385] opened 2024-02-12 22:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.40-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in.

1. Keep switching between the chats and workspaces pages.
2. Verify that the top part of the page becomes darker when user goes to the chats page.

## Expected Result:
The top part of the page should remain in the same shade of white.

## Actual Result:
The top part of the page becomes darker.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/eb807c62-af42-4e55-a94a-0d71b47d32dc

![Bug6377344_1707775492425!IMG_E2924](https://github.com/Expensify/App/assets/38435837/66db689f-79a8-42a3-b70b-03ad73b114d9)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff0ec4f217764dfa</li>
        <li>Upwork Job ID: 1757172368748474368</li>
        <li>Last Price Increase: 2024-02-19</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>jeremy-croff | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-13 02:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app status bar is not the same color on the home screen 

### What is the root cause of that problem?
The color that is set on the home screen is slightly different than the other screens

### What changes do you think we should make in order to solve the problem?
We can update https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/styles/theme/themes/light.ts#L96 to colors.productLight100. There's a corresponding dark theme that also needs to be updated to ```backgroundColor: colors.productDark100,``` for that screen.

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-13 02:46
https://github.com/Expensify/App/pull/32512/files updated some of the theme background colors without adjusting the status bar

**Comment by alexpensify** [comment] 2024-02-14 19:16
@alitoshmatov - keep us posted if this proposal will fix the issue. Thanks!

**Comment by jeremy-croff** [comment] 2024-02-17 00:07
> @jeremy-croff Thank you for proposal, can provide some screen shots of your solution working. Also does changing this color effect other places of the app?

https://github.com/Expensify/App/assets/157416545/451b9d3a-26a7-4b25-9982-f7bcd05bee70

This change is scoped to the home screen route.

**Comment by alexpensify** [comment] 2024-02-21 01:43
Catching up from being OOO, @alitoshmatov any update to @jeremy-croff's reply? Thanks!

**Comment by alitoshmatov** [comment] 2024-02-21 06:17
That looks great, let's go with @jeremy-croff 's [proposal](https://github.com/Expensify/App/issues/36385#issuecomment-1940318599)

C+ reviewed 🎀 👀 🎀

**Comment by alexpensify** [comment] 2024-02-23 00:06
@yuwenmemon we need your review here. Thanks!

**Comment by jeremy-croff** [comment] 2024-02-26 19:26
Acknowledged, will be able to provide this within the next 24hr. Thank you!

**Comment by alexpensify** [comment] 2024-03-01 02:03
Awesome, looks like automation kicked in here. 

--- 

Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-03-08 00:35
I've updated the payment summary here https://github.com/Expensify/App/issues/36385#issuecomment-1972145512 for the following job in Upwork: 

https://www.upwork.com/jobs/~01ff0ec4f217764dfa

Closing since everyone has been paid here.

**Closed by alexpensify** 2024-03-08 00:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
