### ISSUE TITLE
The hover effect animation is not functioning properly on the Bank Account in workspace settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35839] opened 2024-02-05 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Settings > Workspace > Bank Account
2. Click on it; the modal opens on the right side
3. The hover effect animation should be centered on the Bank Account section

## Expected Result:
The hover effect animation should be centered on the Bank Account section

## Actual Result:
The hover effect animation is not centered on the Bank Account section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/e701d97a-8149-4880-a00d-61fd0add3df5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-02-05 17:11
Taking over, related to ideal nav.

**Comment by esh-g** [comment] 2024-02-05 17:19
# Proposal

## Root cause
We are checking if the `Menuitem` is pressed based on whether the item route name is present in the route, but for `bankAccount` we are not passing any `routeName`

## Solution
We should pass `routeName` property for `bankAccount` item in `WorkspaceInitialPage`

**Comment by mountiny** [comment] 2024-02-05 18:29
@trjExpensify Curious for your opinion on this one, I feel like we should eventually update the bank account to have its own page in the main pane same as all the other settings pages.

If we would do that, this change would not be necessary

**Comment by trjExpensify** [comment] 2024-02-05 18:38
Yeah, interesting one. We could move the `Bank account` page to the main pane like we have the others. Clicking the rows in the card open the modal in the RHP.

That said, with `Simplified Collect: Workflows` when we implement the new re-designed workspace editor, it'll actually be RHP again:

![image](https://github.com/Expensify/App/assets/16232057/e3295d26-f77c-41b5-ad99-815a86e20147)

So perhaps the decision to do

**Comment by trjExpensify** [comment] 2024-02-05 19:58
>We also have the case where we have a flow from central navigator to the bank account page in RHP, so this can't be moved to central pane at least

Nah, all of those weird redirects will go away with the redesigned workspace editor as those pages get replaced.

**Comment by mountiny** [comment] 2024-02-08 14:55
making this monthly and will confirm once we update this flow

**Comment by mountiny** [comment] 2024-03-12 21:22
This button will be removed from the LHP so I am going to close this issue

**Closed by mountiny** 2024-03-12 21:22 UTC
Labels: Engineering, Monthly, Overdue
