### ISSUE TITLE
Web - Japaneese - Incorrect popup option in emoji popup when typing in Japaneese

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18476] opened 2023-05-05 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/16065

## Action Performed:
1. Login to ND
2. Go to any chat
3. Switch to Japaneese
4. Open the emoji picker
5. Type "smile" while the input mode is in Japanese

## Expected Result:
The text that appears is gibberish but you should see a popup selection tool appears. That popover should contain the option for smile.

## Actual Result:
Popup doesn't contain the option for smile, only gibberish test.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236474305-639c5a5e-30a3-4fc7-946d-af7830bead4b.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment] 2023-05-05 16:16
This is actually an expected behavior. There are many input options when you're inputting text in Japanese (I don't know which one you're using). Because the one you're using is converting roman input to Japanese directly, it should not show emojis for smile.

I'm closing this issue.

**Closed by hayata-suenaga** 2023-05-05 16:16 UTC
Labels: Daily, Bug
