### ISSUE TITLE
[$2000] Android -Scan- Parent message not automatically updated to [Deleted] when deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27058] opened 2023-09-08 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to + > Request money > Scan > Take a pic of the receipt
2. Once uploaded, add an amount. (very important)
3. Verify you receive amount changed message on the bottom of the page
4. Click on the 3 dots and attempt to delete it
5. Verify that the parent message does not automatically update to [Deleted]

## Expected Result:
When the parent message is deleted, it should automatically update to [Deleted]

## Actual Result:
Parent message is not automatically updated to [Deleted]

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/98ed70a3-4665-4df0-8c18-dd8f78c4a282

https://github.com/Expensify/App/assets/93399543/32d3eafb-e1b4-4a68-8258-9d458fea88d7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1693868591788509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a605ed983b7c2031</li>
        <li>Upwork Job ID: 1700244152320290816</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-09-11 11:31
Agreed this should be external. Not sure why melv assigned both you and I, @CortneyOfstad, but I'm happy to take this one

**Comment by bfitzexpensify** [comment] 2023-09-14 09:53
@parasharrajat do you have a little more context on that? Is the expected behaviour that we don't remove historical messages upon deletion? If so, I think we would classify this as not being a bug and close the issue.

**Comment by bfitzexpensify** [comment] 2023-09-18 11:24
Thanks for the clarification. You're right in that the expected behaviour doesn't match how other deleted parent messages work. It does still seem like there might be something to fix here (ensuring the parent message is updated to [Deleted]). 

So, how does this sound:

We update the action performed to this:

1. Go to + > Request money > Scan > Take a pic of the receipt
2. Once uploaded, add an amount. (very important)
3. Verify you receive amount changed message on the bottom of the page
4. Click on the 3 dots and attempt to delete it
5. Verify that the parent message does not automatically update to [Deleted]

With an expected behaviour of:

When the parent message is deleted, it should automatically update to [Deleted]

**Comment by bfitzexpensify** [comment] 2023-09-18 11:31
Agreed. OK, title and all sections of the OP updated

**Comment by bfitzexpensify** [comment] 2023-09-21 11:26
We updated the issue earlier this week, so I'll wait until next week to consider doubling the bounty here.

**Comment by bfitzexpensify** [comment] 2023-09-25 13:16
OK, let's double this one.

**Comment by shubham1206agra** [comment] 2023-09-28 13:39
@parasharrajat I just checked
This issue is not exclusive to Android
And receipt is not required

You just need to somehow create a comment (in this case, by changing the amount), and then delete the request.
I am gonna check this one why this is happening

**Comment by bfitzexpensify** [comment] 2023-09-28 15:26
Good point @shubham1206agra, updating the impacted platforms in the OP

**Comment by bfitzexpensify** [comment] 2023-10-02 17:54
OK, no more proposals have come in, so let's double this again

**Comment by shubham1206agra** [comment] 2023-10-03 12:37
<img width="1512" alt="Screenshot 2023-10-03 at 6 07 00 PM" src="https://github.com/Expensify/App/assets/58412969/ab6e4f21-f7ad-4aed-a0de-37874971d535">

Just confirming, is this the ideal behaviour?

**Comment by s-alves10** [comment] 2023-10-03 12:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After creates a money request and updates the amount, parent message isn't updated to [Deleted request] when deleted

### What is the root cause of that problem?

When we need to show deleted request, we set `message[0].isDeletedParentAction` to true here
https://github.com/Expensify/App/blob/f2a98fcb948a1775f16eb9b21f59f7e87bf9fe31/src/libs/actions/IOU.js#L1462

And for deleted parent request, we show `[Deleted request]` here
https://github.com/Expensify/App/blob/f2a98fcb948a1775f16eb9b21f59f7e87bf9fe31/src/components/ReportActionItem/MoneyRequestAction.js#L131-L133

The problem is in `ReportActionsUtils.isDeletedParentAction` function
https://github.com/Expensify/App/blob/f2a98fcb948a1775f16eb9b21f59f7e87bf9fe31/src/libs/ReportActionsUtils.js#L67-L69

As you can see, we check `isDeletedParentAction` flag and `childVisibleActionCount` as well, but we don't have `childVisibleActionCount` for our money request actions. So `ReportActionsUtils.isDeletedParentAction` function returns false for parent money request action. Because of this, parent money request action fails in visibility test [here](https://github.com/Expensify/App/blob/f2a98fcb948a1775f16eb9b21f59f7e87bf9fe31/src/libs/ReportActionsUtils.js#L355)

That's why the deleted parent money request is hidden

### What changes do you think we should make in order to solve the problem?

We don't have `childVisibleActionCount` for money request actions and set `isDeletedParentAction` flag only when we need to show the deleted parent money request. I verified that the backend works this way as well.
So we can update the `ReportActionsUtils.isDeletedParentAction` function like
```
function isDeletedParentAction(reportAction) {
    return lodashGet(reportAction, ['message', 0, 'isDeletedParentAction'], false) && (isMoneyRequestAction(reportAction) || lodashGet(reportAction, 'childVisibleActionCount', 0) > 0);
}
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/08777360-a254-4621-a06f-c249201fba32


</details>


### What alternative solutions did you explore? (Optional)
We can do the same as we do for general message actions.
That is, we can solve this issue by updating `childVisibleActionCount`, `childCommenterCount`, `childLastVisibleActionCreated`, and `childOldestFourAccountIDs` of parent money request action.
This should be done in the backend as well.

**Comment by shubham1206agra** [comment] 2023-10-03 13:25
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Scan- Parent message not automatically updated to [Deleted] when deleted

### What is the root cause of that problem?

For deleted requests, we set `isDeletedParentAction` to true for the given action.

And for deleted requests, we get reportName (of IOU) here, which should get to `[Deleted request]` in the case

https://github.com/Expensify/App/blob/b29d682876e1cc16f7d7000a4a56664a77e56423/src/libs/ReportUtils.js#L1469-L1472

But the problem is in `ReportActionsUtils.isDeletedParentAction` function

https://github.com/Expensify/App/blob/b29d682876e1cc16f7d7000a4a56664a77e56423/src/libs/ReportActionsUtils.js#L67-L69

There is a check for `childVisibleActionCount` to be greater than 0. This was created with the intention to keep only such requests/tasks/messages which have some message (thread) inside it to avoid any clutter in the report.

But when we change anything for the money request, such as description, amount, etc., it does not increase the amount of `childVisibleActionCount` due to the fact that someone created a money request by mistake and wants to delete it. After deletion, it should not show the request in the favour that the user just changed the parameter of the request, not anything useful is inside it.

In this case, parent money request should remain hidden.

But another problem is that the deleted money request reportName is not rendering properly due to value of `lodashGet(reportAction, 'childVisibleActionCount', 0) > 0` being false, which is a bug.

### What changes do you think we should make in order to solve the problem?

In the above case, we should use another function apart from `ReportActionsUtils.isDeletedParentAction`. We can either use `ReportActionsUtils.isDeletedAction` or we can define a custom function like

```js
function isDeletedMoneyRequestAction(reportAction) {
    return lodashGet(reportAction, ['message', 0, 'isDeletedParentAction'], false);
}
```

### What alternative solutions did you explore? (Optional)

If we also want to make parent Action to `[Deleted request]`. I think we should create some UI around it, so that when we click on it. It should open a Deleted request.

**Comment by bfitzexpensify** [comment] 2023-10-03 16:20
>Just confirming, is this the ideal behaviour?

@shubham1206agra, correct

**Comment by shubham1206agra** [comment] 2023-10-03 16:27
@bfitzexpensify Just want to confirm another thing
Can you read my proposal and see the ideal behaviour description there?
I want to confirm the ideal behaviour

**Comment by bfitzexpensify** [comment] 2023-10-09 22:42
@parasharrajat have you had a chance to review this?

**Comment by bfitzexpensify** [comment] 2023-10-12 18:41
friendly bump @parasharrajat

**Comment by shubham1206agra** [comment] 2023-10-13 01:36
@parasharrajat Maybe this

But when we change anything for the money request, such as description, amount, etc., it does not increase the amount of childVisibleActionCount due to the fact that someone created a money request by mistake and wants to delete it. After deletion, it should not show the request in the favour that the user just changed the parameter of the request, not anything useful is inside it.

**Comment by shubham1206agra** [comment] 2023-10-15 05:46
@parasharrajat I think this has been taken care of already in https://github.com/Expensify/App/pull/28214

**Comment by bfitzexpensify** [comment] 2023-10-20 18:22
How did your testing go @parasharrajat?

**Comment by s-alves10** [comment] 2023-10-23 06:58
@parasharrajat

It looks like the title in LHN and the header of the transaction thread were fixed already
Here is my question: 
After deleting the iou request, LHN title and the header are changed to [Deleted request], but iou report shows nothing though there exists the transaction thread in the LHN.
![image](https://github.com/Expensify/App/assets/126839717/3edfdc2a-7767-4721-8ef9-e4de98e10e39)

I thought we should show [Deleted request] in the iou report as well like
![image](https://github.com/Expensify/App/assets/126839717/7c4fc147-03dd-4286-850d-adeca9a2a785)

Let me know what the expected behavior is
Thank you

**Comment by bfitzexpensify** [comment] 2023-10-24 22:49
> Yup. This is gone. @bfitzexpensify



Great, thanks @parasharrajat. Closing this out.

**Closed by bfitzexpensify** 2023-10-24 22:49 UTC
Labels: Engineering, Daily, Internal, Bug
