### ISSUE TITLE
[$250] Web - IOU - Swiping with the mouse causes text to be selected and tabs quickly switching

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47651] opened 2024-08-19 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://github.com/Expensify/App/pull/47485
**Email or phone of affected tester (no customers):** 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to FAB - Submit expense
4. Switch between Manual, Scan and Distance tabs with the click, hold and swipe method

## Expected Result:
I should be able to switch between tabs with the mouse smootly. Text shouldn't be selected and quick switching shouldn't happen.

## Actual Result:
Swiping with the mouse causes text to be selected and tabs quickly switching back and forth.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/976b0a3c-1430-4a17-aec7-3eafcc77ea22

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4f519f87f7ca5c0</li>
        <li>Upwork Job ID: 1825784474327119736</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103624416</li>
<li>Krishna2323 | Contributor | 103624417</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by IuliiaHerets** [comment] 2024-08-19 17:53
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-19 17:53
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-08-20 06:38
Wow, how cool, I had no idea this was a thing! There is definitely a technique right now, you have to click and hold in the exact right place and getting back from the map is a challenge!! 

I don't think this is internal.

**Comment by RachCHopkins** [comment] 2024-08-20 06:49
Also, I use a touch-pad and I found that if I clicked & held but swiped too fast my mouse cursor would go past the edge and it would drop it and ping back. Here's my experience:

https://github.com/user-attachments/assets/02ee89f9-9966-4f24-bdc5-5cdcf03a681c

I hope there's no audio because I got hopelessly stuck on the distance tab and couldn't stop laughing at my incompetence. I even managed to accidentally look something up on the dictionary app.

**Comment by RachCHopkins** [comment] 2024-09-09 04:12
How are you doing with the review here @ZhenjaHorbach ?

**Comment by ZhenjaHorbach** [comment] 2024-09-09 06:54
> How are you doing with the review here @ZhenjaHorbach ?

PR is ready to be merged
We are just waiting for @kirillzyusko's opinion on [this comment](https://github.com/Expensify/App/pull/48004#issuecomment-2331834608) !

**Comment by kirillzyusko** [comment] 2024-09-09 10:43
> PR is ready to be merged

Yeah, the error from CI job doesn't prevent the PR from being merged 👍 

We always can improve CI job in future to ignore warnings or any other kind of improvement!

**Comment by RachCHopkins** [comment] 2024-09-18 00:30
Automation is borked, it's been a week since @stitesExpensify's comment so I assume this is ready to pay. And do we need any regression test @ZhenjaHorbach?

**Comment by RachCHopkins** [comment] 2024-09-18 00:31
Payment Summary:

- Contributor: @Krishna2323 to be paid $250 via Upwork
- Contributor+: @ZhenjaHorbach to be paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~01c4f519f87f7ca5c0)

**Comment by RachCHopkins** [comment] 2024-09-18 00:35
Contributors have been paid, the contracts have been completed, and the Upwork post has been closed.

Just waiting on whether we need regression testing.

**Closed** 2024-09-26 21:47 UTC
Labels: Reviewing, External, Weekly, Bug
