### ISSUE TITLE
[ON HOLD #34610] [$500] Distance - Duplicate waypoints message does not instantly show up in distance request editor

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36519] opened 2024-02-14 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Go to + > Request money > Distance.
3. Enter A-B-A waypoints.
4. Reorder the waypoints by dragging so that it becomes A-A-B.
5. Note that error message for duplicate waypoints instantly shows up.
6. Change the distance back to A-B-A.
7. Proceed to confirmation page.
8. Click Distance.
9. Reorder the waypoints by dragging so that it becomes A-A-B.
10. Note that error message for duplicate waypoints instantly shows up.
11. Create the distance request with A-B-A waypoints.
12. Go to request details page.
13. Click Distance.
14. Reorder the waypoints by dragging so that it becomes A-A-B.

## Expected Result:
The error message for duplicate waypoints will instantly show up.

## Actual Result:
The error message for duplicate waypoints does not instantly show up. It only shows up after user attempts to save the duplicate waypoints.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bcc27658-2a81-406a-88ec-03e39c76df46

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6febd25fc272874</li>
        <li>Upwork Job ID: 1757796016628969472</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-14 15:57
We think that this bug might be related  #wave5-free-submitters
CC @dylanexpensify

**Comment by paultsimura** [comment] 2024-02-14 16:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When editing a Distance request, the duplicate waypoints error is not shown immediately.

### What is the root cause of that problem?
When implementing this immediate error display, it was added only for the creation flow: https://github.com/Expensify/App/pull/32999, and the edit flow was missed.

### What changes do you think we should make in order to solve the problem?
We need to add the same changes (made to `IOURequestStepDistance`) to the `DistanceRequest/index.js`

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-02-14 22:49
I think DistanceRequest should / will be removed in https://github.com/Expensify/App/issues/34610

@zanyrenney Can you please put this on hold for https://github.com/Expensify/App/issues/34610

**Comment by zanyrenney** [comment] 2024-02-19 15:17
DONE, thanks!

**Comment by zanyrenney** [comment] 2024-02-21 15:55
This is on HOLD. so Not a daily priority just now.

**Comment by zanyrenney** [comment] 2024-02-21 15:57
Not overdue, on hold.

**Comment by s77rt** [comment] 2024-02-23 20:04
Still on hold

**Comment by s77rt** [comment] 2024-02-26 16:51
Still on hold

**Comment by zanyrenney** [comment] 2024-02-29 16:35
ON HOLD

**Comment by s77rt** [comment] 2024-03-04 12:27
On hold

**Comment by s77rt** [comment] 2024-03-06 23:27
Still on hold

**Comment by zanyrenney** [comment] 2024-03-11 11:44
Still on hold.

**Comment by zanyrenney** [comment] 2024-03-11 11:45
Going to move this to weekly, as it's been on hold a while.

**Comment by s77rt** [comment] 2024-03-11 11:47
Weekly sounds good

**Comment by zanyrenney** [comment] 2024-03-11 11:47
thank you @s77rt

**Comment by s77rt** [comment] 2024-03-19 21:58
Still on hold

**Comment by s77rt** [comment] 2024-04-01 19:41
It looks like the other issue is closed but not clear why. Gonna wait for the next overdue label till things are cleared up

**Comment by zanyrenney** [comment] 2024-04-04 09:52
It has now been reopened: 
![2024-04-04_10-52-12](https://github.com/Expensify/App/assets/56830058/af3a53f8-7231-4422-8163-eda717c681be)

**Comment by zanyrenney** [comment] 2024-04-04 09:53
distance being worked on in VIPVSB. https://expensify.slack.com/archives/C0671JDRKQW/p1710872125301479

adding to that project.

**Comment by s77rt** [comment] 2024-04-12 23:13
Still on hold

**Comment by zanyrenney** [comment] 2024-04-22 10:11
Still on HOLD.

**Comment by zanyrenney** [comment] 2024-05-01 20:12
This is on HOLD. We don't need to adjust the bounty

**Comment by s77rt** [comment] 2024-05-11 14:57
Issue is no longer reproducible. We can close this

**Comment by s77rt** [comment] 2024-05-20 19:29
@zanyrenney We can close this

**Comment by s77rt** [comment] 2024-05-29 22:00
To be closed

**Comment by s77rt** [comment] 2024-06-08 11:50
To be closed

**Comment by s77rt** [comment] 2024-06-17 23:20
@zanyrenney Please close this

**Comment by s77rt** [comment] 2024-06-26 21:02
To be closed

**Comment by s77rt** [comment] 2024-07-05 21:44
To be closed

**Comment by s77rt** [comment] 2024-07-15 10:56
@zanyrenney We can close this one

**Comment by s77rt** [comment] 2024-07-23 21:29
To be closed

**Comment by s77rt** [comment] 2024-08-02 01:43
@zanyrenney ^

**Comment by zanyrenney** [comment] 2024-08-12 18:40
Closed based on comment abve.

**Closed by zanyrenney** 2024-08-12 18:40 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
