### ISSUE TITLE
Android - Request money - App crashes when editing Amount twice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25841] opened 2023-08-24 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24630
## Action Performed:
1. Launch New Expensify app
2. Request money from other user
3. Tap on the IOU preview twice
4. Edit the amount twice

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ddc27c05-f089-4c46-b932-8c2dace19f93

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pradeepmdk** [comment] 2023-08-24 14:44
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Android - Request money - App crashes when editing Amount twice

### What is the root cause of that problem?
![Screenshot 2023-08-24 at 7 33 27 PM](https://github.com/Expensify/App/assets/16595846/8ca51deb-b829-4ae3-8b55-2c6aff895afc)
https://github.com/Expensify/App/blob/329cac3b49fc47da8eac1b7a74a511171fe22345/src/components/ReportActionItem/ReportActionItemImage.js?#L75
due andorid stict type we shoud pass an string but here pass an number that'y its falling

this pr is causing this isse in the 
'editMoneyRequest' api in optimastic data we are setting as a 
https://github.com/Expensify/App/blob/329cac3b49fc47da8eac1b7a74a511171fe22345/src/libs/TransactionUtils.js?#L93
OPEN
its triggred 
https://github.com/Expensify/App/blob/329cac3b49fc47da8eac1b7a74a511171fe22345/src/components/ReportActionItem/MoneyRequestView.js?#L112

### What changes do you think we should make in order to solve the problem?
here in ReportActionItemImage uri does not load the react native assets image but it will load native image.
```
 return (
        <Image
            source={{uri: image}}
            style={[styles.w100, styles.h100]}
        />
    );
``` 
so we need 'ReportActionItemImage' one more pros if we are trying load assets image means 
```
 return (
        <Image
            source={assets ?  assets : {uri: image}}
            style={[styles.w100, styles.h100]}
        />
    );
``` 
and this function should return `getThumbnailAndImageURIs` {thumbnail: null, image: null , assets: null};

and
here we neeed check pending action statement as well.
```javascript
function hasReceipt(transaction) {
    return lodashGet(transaction, 'receipt.state', '') !== '';
}
```

**Comment by Nathan-Mulugeta** [comment] 2023-08-24 15:16
Hey guys I think this bug report might have the same root cause as the one I have reported. And my report came first [here](BUG: App crashes after deleting a second money request made after a deleted request
From: @Nathan Mulugeta
Action Performed:
1. Open a new account on ND
2. Click on FAB > Request money > Enter an amount > Enter an email and confirm the request 
3. Click on the IOU preview component twice to open the details page
4. Click on Merchant and change it to something else and click on save
5. Go back one step and delete the IOU request which was made 
6. Go back to the chat page and click on the plus icon > request money > enter an amount and confirm the request 
7. Click on the IOU preview component once to go to the report page
8. Hover over the last preview component and click on the delete icon
Expected Result: App should delete the last IOU without any crash
Actual Result: App crashes after waiting for a few seconds
Platforms: Desktop web chrome
Version Number: v1.3.57-0
Screenshots or Videos: :thread:) on slack.

**Comment by amyevans** [comment] 2023-08-24 15:20
@pradeepmdk I don't think I'm following your proposal. The `<ReportActionItemImage />` component is only used if the transaction has a receipt, and the bug video shows that it is a cash request.

If it _does_ have something to do with that PR, the PR has already deployed to production, so this wouldn't be a deploy blocker. @lanitochka17 could you try to reproduce the issue on production again and confirm for me if it crashes or not?

**Comment by pradeepmdk** [comment] 2023-08-24 16:05
![Screenshot 2023-08-24 at 9 29 48 PM](https://github.com/Expensify/App/assets/16595846/d449ebc0-2883-4927-a1df-0e7683e467d2)

For this first point has  'receipt' editMoneyRequest should not return the when `receipt.state` is empty.

and for this crash part `source={assets ?  assets : {uri: image}}` image for blob or file  so that its should not crash is when receipt data as well.

**Comment by mountiny** [comment] 2023-08-24 16:57
>  editMoneyRequest called first time its return the receipt data so that its start occurring from second time

@amyevans fyi this will be fixed with the next auth deploy happening real soon I think  https://github.com/Expensify/Auth/pull/8562

So maybe we can just wait

**Comment by pradeepmdk** [comment] 2023-08-24 17:03
@mountiny  still we have an issue with loading images from local assets `getThumbnailAndImageURIs` 
>let image = ReceiptGeneric;
Local assets should be passed to without uri

**Comment by roryabraham** [comment] 2023-08-24 18:55
https://github.com/Expensify/Auth/pull/8562 has been deployed

**Comment by Pujan92** [comment] 2023-08-24 19:12
I think not reproducible now as the receipt state is not updated unnecessarily when the request type is not scan.

**Comment by amyevans** [comment] 2023-08-24 19:17
Cool, @roryabraham mind confirming the issue is no longer reproducible? My Android build is hosed at the moment, trying to get that going again but in the meantime I can't test 😅

**Comment by roryabraham** [comment] 2023-08-24 22:54
Confirmed, no longer reproducible.

**Closed by roryabraham** 2023-08-24 22:54 UTC
Labels: DeployBlockerCash, Engineering, Hourly
