### ISSUE TITLE
[$250] Android - Chat- The link in message is displayed as text.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32403] opened 2023-12-02 15:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Paste a text with link in it
4. Send the message
5. Note the link in message is displayed as clickable link
6. Launch app
7. Tap on a report
8. Paste the same text with link in it
9. Send the message
10. Note the link in message is displayed as text

## Expected Result:
The link in message must be displayed as clickable link and not as text.

## Actual Result:
In mweb, the link in message is displayed as clickable link but in android the link in message is displayed as text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/38bb7c6d-893b-43a1-9abe-76045fabec80

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc6f40574bba0e81</li>
        <li>Upwork Job ID: 1730971989461237760</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28002430</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by HafeezRai** [comment] 2023-12-02 15:45
Summary:
I propose to address the issue described in GitHub Issue #32403, where the link in the message is displayed as text rather than a clickable link within the Expensify Android Chat application. My solution involves implementing changes in the codebase to correctly parse and render links, providing users with a seamless experience when interacting with shared URLs.

Technical Explanation:

    Link Parsing and Formatting:
        Enhance the existing message parsing logic to identify links within the text.
        Implement a URL parser to correctly recognize and extract URLs from the message content.

    TextView Customization:
        Modify the TextView component responsible for rendering chat messages to recognize and handle hyperlinks appropriately.
        Use Android's Linkify class or a custom link detection mechanism to convert identified URLs into clickable links.

    Clickable Link Handling:
        Implement an OnClickListener for clickable links, directing users to the associated web page when clicked.
        Ensure that the link handling mechanism is consistent across various Android versions and devices.

    Testing:
        Rigorously test the implementation on different Android platforms, including various screen sizes and resolutions, to ensure a consistent user experience.
        Conduct unit tests to verify the correctness of the link parsing and rendering logic.

**Comment by HafeezRai** [comment] 2023-12-02 15:54
Summary:
I propose to address the issue described in GitHub Issue https://github.com/Expensify/App/issues/32403, where the link in the message is displayed as text rather than a clickable link within the Expensify Android Chat application. My solution involves implementing changes in the codebase to correctly parse and render links, providing users with a seamless experience when interacting with shared URLs.

Technical Explanation:

Link Parsing and Formatting:
    Enhance the existing message parsing logic to identify links within the text.
    Implement a URL parser to correctly recognize and extract URLs from the message content.

TextView Customization:
    Modify the TextView component responsible for rendering chat messages to recognize and handle hyperlinks appropriately.
    Use Android's Linkify class or a custom link detection mechanism to convert identified URLs into clickable links.

Clickable Link Handling:
    Implement an OnClickListener for clickable links, directing users to the associated web page when clicked.
    Ensure that the link handling mechanism is consistent across various Android versions and devices.

Testing:
    Rigorously test the implementation on different Android platforms, including various screen sizes and resolutions, to ensure a consistent user experience.
    Conduct unit tests to verify the correctness of the link parsing and rendering logic.

**Comment by sausame** [comment] 2023-12-03 05:00
I believe that the Android version of the application does indeed support a combination of links and text. However, it appears that the current parser is struggling to accurately identify this specific mixture pattern. To address this issue, I recommend modifying the parser to enhance its capability to recognize and appropriately handle this type of pattern. This adjustment will ensure a more seamless and effective parsing process for the mixture of links and texts within the application.

In terms of testing, I believe focusing on the functionality and conducting tests on just one Android device should be sufficient for identifying the issue. Since it's less likely to be affected by variations in screen resolutions, concentrating on a single device can streamline the testing process. However, it is crucial to conduct thorough testing to ensure a consistently optimal user experience (UE).

Furthermore, I propose the implementation of an abstract and consolidated layer positioned between the parser and the display on any platform. This intermediary layer will enable parsers to uniformly translate both text and links into standardized formats. Consequently, each platform can utilize the formatted data for display purposes, accommodating diverse technical stacks seamlessly.

Contributor details
Your Expensify account email: bi_song@163.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0185f10a9a8425071d

**Comment by Santhosh-Sellavel** [comment] 2023-12-04 18:02
@greg-schroeder Unassigning due to low bandwidth please assign a new C+ here, thanks!

**Comment by situchan** [comment] 2023-12-04 18:25
I am interested in reviewing this

**Comment by greg-schroeder** [comment] 2023-12-07 19:42
Assigned @situchan as new C+!

**Comment by greg-schroeder** [comment] 2023-12-11 09:59
Thoughts on proposals here @situchan?

**Comment by greg-schroeder** [comment] 2023-12-13 11:50
bump

**Comment by greg-schroeder** [comment] 2023-12-18 17:18
bump @situchan

**Comment by situchan** [comment] 2023-12-18 17:21
@HafeezRai please review our [contributing guideline](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and follow [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md). Thanks

**Comment by situchan** [comment] 2023-12-18 17:21
No satisfactory proposals yet

**Comment by greg-schroeder** [comment] 2023-12-19 03:16
Sounds good. Waiting for new proposals, then

**Comment by Victor-Nyagudi** [comment] 2023-12-20 06:27
I'm having trouble reproducing this. 

Does it matter where the message with a link is copied from? Does it need to be formatted using link markdown syntax?

The text I copied that had both regular links and markdown syntax (not at the same time) was formatted correctly after pasting it in the composer and then sending on Android native.


Side note: Copying the message by long pressing it, choosing "copy to clipboard", and then pasting in the composer on Android web resulted in the link being pasted as plain text.

**Comment by greg-schroeder** [comment] 2023-12-21 19:16
@kbecciv can you answer Victor's question above about where the link is copied from?

**Comment by kbecciv** [comment] 2023-12-22 20:22
@greg-schroeder Tester used information from Wikipedia site - https://www.wikipedia.org/
![image](https://github.com/Expensify/App/assets/93399543/f773ab37-b831-48df-bb23-3b7c46ff63ee)

**Comment by greg-schroeder** [comment] 2023-12-31 10:35
This was formatted correctly for me when testing

**Comment by greg-schroeder** [comment] 2024-01-03 20:23
I think I will close for now given inconsistent reproduction

**Comment by situchan** [comment] 2024-01-29 16:59
@greg-schroeder the bug is still reproducible.

The OP was not clear. This is inconsistency issue between mWeb and native.
On mWeb, the link in message is pasted correctly but on native, the plain text.

**Comment by lanitochka17** [comment] 2024-09-03 12:32
Issue is still reproducible on the latest build 9.0.28-0


https://github.com/user-attachments/assets/7a9b7022-e129-4f11-a15b-71b41da1f780

**Comment by situchan** [comment] 2024-09-04 18:58
Awaiting proposals

**Comment by greg-schroeder** [comment] 2024-09-06 22:55
Awaiting proposals, not overdue

**Comment by greg-schroeder** [comment] 2024-09-09 06:13
Same as above

**Comment by greg-schroeder** [comment] 2024-09-11 20:13
Same as above

**Comment by greg-schroeder** [comment] 2024-09-16 10:04
Same as above

**Comment by greg-schroeder** [comment] 2024-09-18 19:14
Awaiting proposals

**Comment by greg-schroeder** [comment] 2024-09-27 19:31
Still awaiting proposals

**Comment by greg-schroeder** [comment] 2024-10-01 01:47
Closing this as #vip-vsb is now paused/closed.

**Closed by greg-schroeder** 2024-10-01 01:47 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
