### ISSUE TITLE
[$500] Fab - Hidden not displayed on chat header & LHN when creating an IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36885] opened 2024-02-20 14:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB > Request money > enter amount
2. Select a new user that has ND account > Click on 'Request' button

## Expected Result:
Hidden should be displayed in LHN & report header

## Actual Result:
Hidden is not displayed in LHN & report header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e8d0e519-b58c-4d9b-8b4a-c405c8cc22f8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ea497aa7819e170</li>
        <li>Upwork Job ID: 1759944064634163200</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-20 14:13
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by flodnv** [comment] 2024-02-20 16:47
@greg-schroeder @DylanDylann are you able to reproduce? I am unable. I think something is missing from repro steps @kbecciv ?

**Comment by flodnv** [comment] 2024-02-20 16:49
>Expected Result:
>Hidden should be displayed in LHN & report header

I don't even get that -- @kbecciv can you share a screenshot of the expected outcome please? 😕

**Comment by kbecciv** [comment] 2024-02-20 17:50
I've noticed a discrepancy in behavior between production and staging. In production, the avatar of a user whom I've never chatted with before, but who has an ND account, is displayed in the header. However, in staging, the user's avatar is displayed as a skeleton in both the header and LHN.

**Production**
https://github.com/Expensify/App/assets/93399543/fddd6dfb-0969-4584-8718-cb5a2117a13d

**Staging**

https://github.com/Expensify/App/assets/93399543/50bd6a25-44f9-4ae4-b6b5-973b85bf8ff5

**Comment by DylanDylann** [comment] 2024-02-23 05:30
@dukenv0307 Do you suggest applying isOptimisticReport to report or reportAction? It seems your permalink taking us to success data of reportAction

**Comment by DylanDylann** [comment] 2024-02-23 06:40
But your permalink linked to success data or report action

<img width="622" alt="Screenshot 2024-02-23 at 13 39 48" src="https://github.com/Expensify/App/assets/141406735/9e2e4921-3dd5-4c1d-9dea-3fbc0645f372">

**Comment by DylanDylann** [comment] 2024-02-23 08:23
@dukenv0307 Could you reproduce this issue on latest main?

**Comment by DylanDylann** [comment] 2024-02-23 17:04
@chiragsalian @flodnv  we can't reproduce the original issue anymore, so I think we should remove deployBlocker label in this issue. And we also should consider to fix above bug that is mentioned by @dukenv0307

**Comment by DylanDylann** [comment] 2024-02-25 09:22
@chiragsalian Reported bug [here](https://expensify.slack.com/archives/C049HHMV9SM/p1708852913951209). Let's close this one

**Closed** 2024-02-26 19:07 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
