### ISSUE TITLE
Multiple API calls in console when user is not making actions 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8504] opened 2022-04-06 03:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat 
2. Switch to another chat 

## Expected Result:
There should be only relevant API calls in the Console 

## Actual Result:
Multiple API calls are made when user is not making multiple actions 

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.51-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="438" alt="image - 2022-04-05T234658 233" src="https://user-images.githubusercontent.com/43995119/161891858-448e7b83-c2b4-451a-92cc-dcd2927aa8f3.png">
![Screen Shot 2022-04-05 at 11 45 33 PM](https://user-images.githubusercontent.com/43995119/161891871-bfe78504-5770-4846-9feb-b951f4acbc6d.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648928114676369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joelbettner** [comment] 2022-04-07 16:30
@mvtglobally I'm unable to reproduce this. 
<img width="891" alt="image" src="https://user-images.githubusercontent.com/13264774/162252175-5fb2a26d-c474-48fc-8fd2-ef722b60d436.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/13264774/162252240-3d45b400-8521-4f09-9120-808cdbcd8c0d.png">

Is there anything in particular about the chats that you're going back and forth between?

**Comment by joelbettner** [comment] 2022-04-07 17:52
I think this is worth working on, but I cannot re-produce it. I've tried on production and on staging. However, @mvtglobally has been able to reproduce it. I'm going to un-assign myself and add the External label. Whoever gets assigned this, we should make sure others are able to re-produce this.

**Comment by joelbettner** [comment] 2022-04-07 17:53
@roryabraham @marcaaron any ideas why this isn't happening for all users?

**Comment by roryabraham** [comment] 2022-04-07 18:44
@joelbettner Did you take a peek at the network console? It's weird that you would see almost no logs in the console, did you have any filters for different log levels?

The first set of logs in the OP look like an expired authToken had to be reauthenticated. Also seeing a fair amount of logs related to performance monitoring/timing, which is expected in certain flows. Personally I think we need more to go on for this issue to be valuable – reproduction steps or a clear indication that something unexpected is happening.

Going to just close this out for now.

**Closed by roryabraham** 2022-04-07 18:44 UTC
Labels: External, Engineering, Daily

**Comment by marcaaron** [comment] 2022-04-08 00:37
It could be related to some of the network refactors we did recently, but agree that without a reproduction it will be hard to say why it's happening.
