### ISSUE TITLE
 Request money - 3-dot menu does not disappear after deleting money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29632] opened 2023-10-14 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28214
## Action Performed:
1. Go to staging.new.expensifail.com or open iOS, Android, Desktop App
2. Login with any account
3. Create a request money
4. Go to the transaction thread report of the request
5. Send a message in this report
6. Click on the 3-dot icon in the header and delete the request
7. Verify that the 3-dot icon is hidden after the request is deleted

## Expected Result:
3-dot icon is hidden after the request is deleted

## Actual Result:
3-dot icon is NOT hidden after the request is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/fe274ff0-a998-4a35-8967-2b61f6347991

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/1e94e26a-9ae8-40ad-987f-fe8013df6e42

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/61fb8de2-47e2-4f1b-bd54-aef0f0b371a5

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/65bb20b6-b7f6-4029-91cf-2767e51b1fb8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment] 2023-10-15 05:56
Can you confirm me the ideal behaviour?

**Comment by mountiny** [comment] 2023-10-15 21:11
I dont think this has to be a blocker and @dukenv0307 should handle this regression as it was clearly bad merge conflict

**Comment by mountiny** [comment] 2023-10-16 10:42
This is the request page, I am not sure, @jasperhuangg @trjExpensify what do you think, should we close this as expected?

**Comment by trjExpensify** [comment] 2023-10-16 10:49
If a request is preserved because of the comments in the transaction thread, I don't see why we wouldn't let you pin it still. So then in that regard, because the `pin` action is now a menu item within the overflow menu, it makes sense to remain in this scenario.

**Comment by mountiny** [comment] 2023-10-16 11:35
I will close this issue then

**Closed by mountiny** 2023-10-16 11:35 UTC
Labels: Engineering, Daily, Bug
