### ISSUE TITLE
[Hold for payment 2024-09-16] [$125] [P2P Distance] Split - Error shows up when splitting distance to workspace chat via QAB

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47021] opened 2024-08-08 02:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.18-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** New feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [applausetester+kh050806@applause.expensifail.com](mailto:applausetester+kh050806@applause.expensifail.com)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace.
3. Go to workspace chat.
4. Click + > Split expense > Distance.
5. Split distance expense in the workspace chat.
6. Click FAB.
7. Click Split distance under Quick action.
8. Enter waypoints > Next.
## Expected Result:
User will be able to split distance to workspace chat via QAB.
## Actual Result:
Error shows up when splitting distance to workspace chat via QAB.
On iOS, app crashes.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/b0add05c-57aa-44d4-8872-fd7f58d80e5d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebb99c7c764b036a</li>
        <li>Upwork Job ID: 1824435072292925117</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103602852</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by youssef-lr** [comment] 2024-08-08 09:30
Checking

**Comment by youssef-lr** [comment] 2024-08-08 09:37
Not a web blocker. Looks like the request from the workspace chat uses `CreateDistanceRequest` for the command, and the one from QAB uses the 'SplitBill' command which fails. I think it should use `CreateDistanceRequest` as well. cc @neil-marcellini

**Comment by youssef-lr** [comment] 2024-08-08 09:38
Removing blocker from NewDot as well because this Distance Split are not live in production yet

**Comment by sonialiap** [comment] 2024-08-13 12:15
@youssef-lr am I correct in that this was introduced by Neil's PR? Should this be assigned to him?

**Comment by youssef-lr** [comment] 2024-08-13 22:04
>am I correct in that this was introduced by Neil's PR? 

Yes. I think it's fine to have this external unless @neil-marcellini wants to work on it?

**Comment by sonialiap** [comment] 2024-08-16 13:17
@dylanexpensify I'm OOO Aug 19-30, adding leave buddy. 
Status: just moved to external (though maybe @neil-marcellini will want this once he's back to full working hours) so we're looking for a proposal

**Comment by youssef-lr** [comment] 2024-08-16 14:11
Adjusting price, we just need to change the endpoint and the params I think

**Comment by Shahidullah-Muffakir** [comment] 2024-08-19 16:03
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
If a user clicks on the "Split Distance" from the quick actions, when the user filled the Start and Stop location, and click on Split Button, it results in an error, preventing the user from splitting the expense.

### What is the root cause of that problem?
Before splitting the distance, we need to calculate both the distance and the amount for that distance (Same like we do when user try to split the distance from workspace chat). However, the system is not performing these calculations and is directly attempting to split, which leads to an error.

### What changes do you think we should make in order to solve the problem?
After the user enters the start and stop locations, we should first display the "Next" button. When the user clicks on that button, the distance and amount will be calculated. Only after this calculation should the "Split" button be shown, allowing the user to split the amount.
    **The following is the startMoneyRequest function:**
    `function startMoneyRequest(iouType: ValueOf<typeof CONST.IOU.TYPE>, reportID: string, requestType?: IOURequestType, 
    skipConfirmation = false)`

In the case of splitting distance, we should not skip the confirmation. If we skip it, we won’t calculate the distance and the amount for this distance, which will cause an error. so while calling this function pass true for skipConfirmation , now it is passing false.

**change :**
```
case CONST.QUICK_ACTIONS.SPLIT_DISTANCE:
    selectOption(() => IOU.startMoneyRequest(CONST.IOU.TYPE.SPLIT, quickActionReportID, CONST.IOU.REQUEST_TYPE.DISTANCE, true), true);
```

**to :** 
```case CONST.QUICK_ACTIONS.SPLIT_DISTANCE:
    selectOption(() => IOU.startMoneyRequest(CONST.IOU.TYPE.SPLIT, quickActionReportID, CONST.IOU.REQUEST_TYPE.DISTANCE, false), true);
```

**Comment by Shahidullah-Muffakir** [comment] 2024-08-19 16:29
Screen Recording: Showing Distance splitting from Quick actions
https://github.com/user-attachments/assets/b96dcf51-bc83-4d8a-9707-91eea1f01b0e

@

**Comment by akinwale** [comment] 2024-08-20 05:57
@Shahidullah-Muffakir How would your proposed solution work in offline mode? Can you test this as well?

**Comment by Shahidullah-Muffakir** [comment] 2024-08-20 07:58
Do we have support for Distance split in offline mode?
I think Distance split is not currently supported in offline mode, including in production. The main challenge is calculating distances and amounts without internet access.
Currently In production In offline mode, users can only use Manual split, not Distance split.

This video shows:
Manual split available offline in Prod 
Distance split unavailable offline in Prod
Video:
https://github.com/user-attachments/assets/2311b120-1891-4405-97c0-6839fb3da9ea

**Comment by Shahidullah-Muffakir** [comment] 2024-08-20 07:59
@akinwale Do we have support for Distance split in offline mode?
I think Distance split is not currently supported in offline mode, including in production. The main challenge is calculating distances and amounts without internet access.
Currently In production In offline mode, users can only use Manual split, not Distance split.

This video shows:
Manual split available offline in Prod 
Distance split unavailable offline in Prod
Video:
https://github.com/user-attachments/assets/2311b120-1891-4405-97c0-6839fb3da9ea

**Comment by akinwale** [comment] 2024-08-20 08:25
We can move forward with @Shahidullah-Muffakir's [proposal](https://github.com/Expensify/App/issues/47021#issuecomment-2296925938) here.

🎀👀🎀 C+ reviewed.

**Comment by Shahidullah-Muffakir** [comment] 2024-08-20 17:06
Thank you for hiring me, I will make the PR within one hour.

**Comment by dylanexpensify** [comment] 2024-08-21 10:20
Nice turnaround @Shahidullah-Muffakir!

**Comment by Shahidullah-Muffakir** [comment] 2024-08-21 10:52
Thank you @dylanexpensify .

**Comment by Shahidullah-Muffakir** [comment] 2024-08-22 23:00
@akinwale , PR #47737 has been ready for 2 days. Could you review when possible? Thank you!

**Comment by akinwale** [comment] 2024-08-23 05:46
Thanks for the bump. I will review today.

**Comment by sonialiap** [comment] 2024-09-02 09:36
@dylanexpensify thanks for helping out while I was OOO! Taking this back. Feel free to keep on or unassign yourself

**Comment by sonialiap** [comment] 2024-09-13 10:39
Still waiting for the production deploy https://github.com/Expensify/App/pull/47737

**Comment by akinwale** [comment] 2024-09-13 12:51
@sonialiap Automation hasn't been picking up some issues in the past few days. The PR was deployed to production on [2024-09-09](https://github.com/Expensify/App/issues/48664#event-14185603442) (part of this [checklist](https://github.com/Expensify/App/issues/48664)), so payment is due on 2024-09-16.

**Comment by sonialiap** [comment] 2024-09-13 13:22
Thanks @akinwale!

**Comment by sonialiap** [comment] 2024-09-17 10:37
Payment summary:
- @akinwale $125 - paid ✔️ 
- @Shahidullah-Muffakir $125 - offer sent in upwork

**Closed** 2024-09-17 10:43 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
