### ISSUE TITLE
[$500] Start Chat - Workspace not auto selected when creating Room for public existing user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34519] opened 2024-01-15 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34160
## Action Performed:
Prerequisites: Existing public account with existing workspace
1. Open https://staging.new.expensify.com/
2. Log in with prerequisite account
3. Click on the green plus button (FAB)
4. Click on Start chat
5. Click on Room tab if necessary

## Expected Result:
Existing workspace should be automatically selected for Workspace field

## Actual Result:
Workspace field is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a71d8360-3291-4260-8001-de4bcb089370

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153cb4ce8578165a7</li>
        <li>Upwork Job ID: 1746945138582761472</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2024-01-15 17:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
we are not initialising any value for policyID in `WorkspaceNewRoomPage`

### What changes do you think we should make in order to solve the problem?
1. Set the state initially like this
```js
    const [policyID, setPolicyID] = useState(PolicyUtils.getActivePolicies(props.policies).at(0).id || null);
```
2. use that value in `InputWrapper`
```js
                                <InputWrapper
                                    InputComponent={ValuePicker}
                                    inputID="policyID"
                                    label={translate('workspace.common.workspace')}
                                    items={workspaceOptions}
                                    onValueChange={setPolicyID}
                                    value={policyID}
                                />
```

### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment] 2024-01-15 17:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace not auto selected when creating Room for public existing user
### What is the root cause of that problem?
 
The backend doesn't return the `account.activePolicyID` https://github.com/Expensify/App/blob/34a1db339d700ab0d0b594433c367f6a17714962/src/pages/workspace/WorkspaceNewRoomPage.js#L371-L379

thats why the displays empty workspace 

### What changes do you think we should make in order to solve the problem?

either this issue is fixed in the backend, 

or we add a fallback to select the first workspace if the `account.activePolicyID` is not returned: 

if we go with this approach then we need to change this https://github.com/Expensify/App/blob/34a1db339d700ab0d0b594433c367f6a17714962/src/pages/workspace/WorkspaceNewRoomPage.js#L103 

to  

```js
    const [policyID, setPolicyID] = useState(props.activePolicyID ||  props.policies[0].id);
```

we can of course use lodash to safely access those the props.policies object

```

**Comment by s-alves10** [comment] 2024-01-15 18:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace isn't auto selected in creating room page even when there are active workspaces

### What is the root cause of that problem?

We have two code segments to initialize the workspace value
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/workspace/WorkspaceNewRoomPage.js#L103

https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/workspace/WorkspaceNewRoomPage.js#L145-L150

The problem is the value of `activePolicyID`. There may be 2 cases
- `activePolicyID` is empty
- `activePolicyID` isn't included in active policies

These cases were not handled. This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to handle the above 2 cases
1. Move [this code](https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/workspace/WorkspaceNewRoomPage.js#L199-L207) above [this line](https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/workspace/WorkspaceNewRoomPage.js#L144)
2. Update the [effect code](https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/workspace/WorkspaceNewRoomPage.js#L145-L150) as follows
```
    useEffect(() => {
        if (workspaceOptions.length === 0 || policyID && workspaceOptions.some(option => option.value === policyID)) {
            return;
        }
        if (props.activePolicyID && workspaceOptions.some(option => option.value === policyID)) {
            setPolicyID(props.activePolicyID);
        } else {
            setPolicyID(workspaceOptions[0].value);
        }
    }, [props.activePolicyID, policyID, workspaceOptions]);
```

This works as expected

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/8a90b1f9-ae3c-4c60-84ae-6a5599ac9f7a

</details>

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-01-16 03:29
This feature is done [here](https://github.com/Expensify/App/issues/32435), It seems we need to wait a update from BE 
cc @alitoshmatov @s-alves10

**Comment by kadiealexander** [comment] 2024-01-19 00:49
Closing as a dupe of 32435

**Closed by kadiealexander** 2024-01-19 00:49 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
