### ISSUE TITLE
[PAID] [$250] User is navigated back to the participants page when they try to submit the expense using "enter" on keyboard

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45184] opened 2024-07-10 16:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720620532517159

## Action Performed:

1. Click FAB
2. Select Submit Expense and enter random amount
3. Select any member
4. On the confirmation page hit `enter` on the keyboard

## Expected Result:
Should be able to submit the expense/ error should be displayed if there are any missing fields
## Actual Result:
We are navigated back to the participants list RHP
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/15d15940-e336-4340-ada1-25375448c6aa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/38435837/42a98372-bb68-4fb0-ae7d-f18b88848baa

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb4569d225d64720</li>
        <li>Upwork Job ID: 1813125140202653640</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103229334</li>
<li>abzokhattab | Contributor | 103421507</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abzokhattab</details>

**Comment by Tony-MK** [comment] 2024-07-17 07:25
@allgandalf, I failed to reproduce this issue on macOS Chrome. 

Does this only occur Windows Chrome?

**Comment by alitoshmatov** [comment] 2024-07-17 16:33
Go ahead @allgandalf

**Comment by alitoshmatov** [comment] 2024-07-17 16:38
@Tony-MK I reproduced it. It is happening because by default back button is getting focused

**Comment by Tony-MK** [comment] 2024-07-18 04:24
Not to bother anyone but I am having a hard time reproducing the issue on MacOS Chrome.

Are there any extra conditions or prerequisites in the steps?

According to the comment above, I think the back button initially got focused for a very slight duration.

I also tried to reproduce the issue quickly, without any delay between the steps but failed.

Can anyone help me reproduce the issue?

Thanks

**Comment by isogit123** [comment] 2024-07-18 13:22
I've been able to reproduce it on Windows Chrome browser. Even If I wait for a moment before pressing enter, it still navigates me to the participants page.

**Comment by sonialiap** [comment] 2024-07-23 10:13
@allgandalf all yours!

**Comment by aldo-expensify** [comment] 2024-08-07 00:53
Assigned, no overdue

**Comment by aldo-expensify** [comment] 2024-08-15 17:44
Merged

**Comment by sonialiap** [comment] 2024-08-16 12:47
@OfstadC I'm OOO Aug 19-30, adding leave buddy. 
Status: in review, approaching payment

**Comment by OfstadC** [comment] 2024-08-19 16:59
Sounds good @sonialiap ! 😃

**Comment by OfstadC** [comment] 2024-08-27 14:59
Yes @allgandalf 😃 - It's on my agenda this morning

**Comment by OfstadC** [comment] 2024-08-27 18:03
https://github.com/Expensify/Expensify/issues/423686

**Comment by OfstadC** [comment] 2024-08-27 18:07
## Payment Summary
- @allgandalf paid $250 via Upwork
- @abzokhattab paid $250 via Upwork

**Closed** 2024-08-27 18:08 UTC
Labels: Reviewing, External, Daily, Bug
