### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web -  In new task page, share destination doesn't have subtitle text for 1 to 1 DM and group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22296] opened 2023-07-05 19:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to assign task
2. Enter title and click next
3. Choose an assignee
4. Choose either 1 to 1 DM

## Expected Result:
Selected share destination should have subtitle (contact method) shown below the user's display name 

## Actual Result:
Selected share destination does not have subtitle (contact method) shown below the user's display name for 1:1 DMs. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b4d0116-0355-4e29-957f-154e568b8819

![image (15)](https://github.com/Expensify/App/assets/93399543/d82c5c64-d6dc-4935-8db4-b807535b044e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688485210604909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fbeac64e9814e82</li>
        <li>Upwork Job ID: 1677046091547865088</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-05 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In new task page, share destination doesn't have subtitle text for 1 to 1 DM and group chat


### What is the root cause of that problem?

Root cause of the issue is that in our `NewTaskPage`, for the `shareDestination` object, `subtitle` field is empty

<img width="292" alt="image" src="https://github.com/chiragxarora/pdf-download/assets/54641656/b06ad494-2f8b-4870-ae60-65678d080c1e">

And in description we are displaying subtitle of the object here

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/pages/tasks/NewTaskPage.js#L169-L172

Now the subtitle field is originating from `TaskUtils.getShareDestination` > `ReportUtils.getChatRoomSubtitle`

And in `getChatRoomSubtitle` method we don't have any condition to catch DMs or group chats 

https://github.com/Expensify/App/blob/6e03e5407d3fcdf2da370f3aaf88aa391c075e14/src/libs/ReportUtils.js#L1107-L1125

And all such reports get caught in this if block 

https://github.com/Expensify/App/blob/6e03e5407d3fcdf2da370f3aaf88aa391c075e14/src/libs/ReportUtils.js#L1111-L1113

Thus subtitle is empty and we don't see it on share destination menu item

### What changes do you think we should make in order to solve the problem?

We need an extra if block to catch DMs and we can determine them by checking the report type, report's chatType and participants length before the other if block mentioned above in RCA.

```js
if (isChatReport(report) && getChatType(report) === '' && report.participants && report.participants.length === 1) {
    return report.participants[0];
}
```

This works because DMs don't have a chat type as per our code definitions here 

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/CONST.js#L574-L580

NOTE: In slack conversation, its decided to show no subtitle for group chats, if expected results change later, then we can alter the condition on participants array

<details>
  <summary>Results</summary>


https://github.com/chiragxarora/pdf-download/assets/54641656/eff5df96-1f01-4030-b0c8-a0bb1af1c153



</details>

### What alternative solutions did you explore? (Optional)

None

**Comment by joekaufmanexpensify** [comment] 2023-07-06 20:05
Reproduced.

**Comment by joekaufmanexpensify** [comment] 2023-07-07 16:55
Pending review of proposal.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 13:59
@eVoloshchak Could you take a look at this proposal when you have a sec?

**Comment by joekaufmanexpensify** [comment] 2023-07-11 18:46
[Bumped review in Slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1689101167534029)

**Comment by eVoloshchak** [comment] 2023-07-11 21:11
@kbecciv's [proposal](https://github.com/Expensify/App/issues/22296#issuecomment-1622319103) looks good to me!

🎀👀🎀 C+ reviewed!
cc: @joekaufmanexpensify

**Comment by shawnborton** [comment] 2023-07-12 11:48
I dont think we should worry about the chat report headers here, let's just solve the inconsistency in the share destination row.

**Comment by joekaufmanexpensify** [comment] 2023-07-12 18:52
Waiting for sign off on the proposal from @bondydaa

**Comment by bondydaa** [comment] 2023-07-12 20:11
I'm a little confused now...

> I dont think we should worry about the chat report headers here

@shawnborton it sounds like if we with https://github.com/Expensify/App/issues/22296#issuecomment-1622319103 it's going to add the contact method to the chat report header as shown in this comment https://github.com/Expensify/App/issues/22296#issuecomment-1631799399.

Are you saying that is fine or that we should leave chat report headers alone and not change them?

**Comment by shawnborton** [comment] 2023-07-12 20:12
I'm saying we can add the subheader in the share destination but let's not change how we display the report header for a 1:1 DM

**Comment by bondydaa** [comment] 2023-07-12 20:17
okay cool that's what I thought, thanks for clarifying. 

Then I don't think we should go with https://github.com/Expensify/App/issues/22296#issuecomment-1622319103 since that would change the report headers for 1:1 DMs, right?

@eVoloshchak are you good with https://github.com/Expensify/App/issues/22296#issuecomment-1623916868 then as I believe it's suggesting it'd only show the contact method in the selector and new task page?

**Comment by bondydaa** [comment] 2023-07-12 23:38
https://github.com/Expensify/App/issues/22296#issuecomment-1631930344 is what confused me... 

so "the other proposal" in that that comment is https://github.com/Expensify/App/issues/22296#issuecomment-1623916868?

Could you create a new proposal that states how we can only fix this for the share destination and not change the report headers?

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:13
Close to selecting a proposal here.

**Comment by bondydaa** [comment] 2023-07-13 18:52
Awesome thanks for that, seems good to me @eVoloshchak your thoughts?

**Comment by joekaufmanexpensify** [comment] 2023-07-14 18:51
Pending review of updated proposal

**Comment by joekaufmanexpensify** [comment] 2023-07-17 12:40
Same

**Comment by bondydaa** [comment] 2023-07-17 18:41
bumped @eVoloshchak on slack.

**Comment by eVoloshchak** [comment] 2023-07-17 23:19
The updated proposal looks good to me, let's proceed with the PR!

🎀👀🎀 C+ reviewed!

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:17
@bondydaa We're all set to assign the contributor here, right?

**Comment by bondydaa** [comment] 2023-07-24 15:04
merged

**Comment by thienlnam** [comment] 2023-07-25 23:11
This added the regression https://github.com/Expensify/App/issues/23583, could you guys take a look? Will assign you both to the issue

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:32
@eVoloshchak Could you please complete your portion of the BZ checklist here so we can prep to issue payment in a few days?

**Comment by joekaufmanexpensify** [comment] 2023-08-01 20:39
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1690922370831249)

**Comment by eVoloshchak** [comment] 2023-08-01 22:51
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18672
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18672/files#r1281220382
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: It's a simple visual bug, I don't think an additional discussion is needed
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
I think we might add a small regression test for this. This isn't very impactful, but has the potential to negatively affect the user experience (slightly, but still)

**Comment by eVoloshchak** [comment] 2023-08-01 22:55
**Regression Test Proposal**

1. Press FAB -> Assign Task
2. Enter a title and click Next
3. Click on Share Somewhere
4. Choose 1 to 1 DM
5. Verify selected share destination has a subtitle (contact method) shown below the user's display name

**Do we agree 👍 or 👎**

**Comment by joekaufmanexpensify** [comment] 2023-08-02 17:59
Great, thanks! I'll create a regression test issue now.

**Comment by joekaufmanexpensify** [comment] 2023-08-02 19:11
This means we need to pay: 

- @chiragxarora - $1,750 ($1000 for PR +$500 speed bonus +$250 reporting bonus). Paid via upwork. 
- @eVoloshchak - $1,500 ($1,000 for C+ review +$500 speed bonus). Paid via Expensify.

**Comment by joekaufmanexpensify** [comment] 2023-08-02 19:19
@chiragxarora $1,750 sent and upwork jobs ended! You were hired in Upwork twice (for PR and reporting), so I sent $1,500 in the PR job, and $250 in the reporting one.

**Comment by joekaufmanexpensify** [comment] 2023-08-02 19:19
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-08-02 19:19
@eVoloshchak could you please request $1,500 and comment here once you have? Thanks!

**Comment by eVoloshchak** [comment] 2023-08-03 01:26
Requested the payment via NewDot🎉

**Comment by JmillsExpensify** [comment] 2023-08-03 03:21
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Closed** 2023-08-03 12:30 UTC
Labels: External, Daily, Awaiting Payment, Bug
