### ISSUE TITLE
[$250] Search - App closes RHP instead of returning to report after deleting expense with comments

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45505] opened 2024-07-16 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause -Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any DM
3. Submit two expenses to the user
4. Go to transaction thread of any submitted expense
5. Send a few comments
6. Go to Search
7. Click on the transaction thread with comments
8. Click on the report header
9. Click Delete expense
10. Delete the expense

## Expected Result:
App will return to the transaction thread with comments

## Actual Result:
App closes the RHP completely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5925c43e-a4b6-4151-910b-4d829fc5d366

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137d82e1685ebf8ce</li>
        <li>Upwork Job ID: 1813273804933428276</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by lanitochka17** [comment] 2024-07-16 17:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by neil-marcellini** [comment] 2024-07-16 18:13
@jasperhuangg I found that this was modified recently by the PR associated with this issue [[$250] Expense - Inconsistency in dismissing report details RHP when deleting expense with comments](https://github.com/Expensify/App/issues/44336#top). I think the current staging behavior might be expected now, but I'm unsure. What do you think? Re-assigning to you since you managed that issue.

**Comment by jasperhuangg** [comment] 2024-07-16 18:15
@neil-marcellini Good shout, I think this is the new expected behavior now. @lanitochka17 Are there any integration tests that we need to update?

**Comment by bernhardoj** [comment] 2024-07-17 03:35
Yeah, this was agreed in the previous issue to close the details page when deleting a transaction, so we use `dismissModal`, but this closes the report RHP too. If we want to keep the report RHP open, we can use `goBack` instead (I can create a follow-up PR if we want to do that).

**Comment by jasperhuangg** [comment] 2024-07-19 22:41
@bernhardoj No worries, I think if we agreed in the other issue then that should be the new expected behavior. I'll reach out to QA in Slack about updating the regression test.

**Comment by jasperhuangg** [comment] 2024-07-20 20:54
Relevant Slack thread for updating regression tests is [here](https://expensify.slack.com/archives/C9YU7BX5M/p1721428972696779)

**Comment by jasperhuangg** [comment] 2024-07-23 22:26
Bumped the thread

**Comment by jasperhuangg** [comment] 2024-07-29 17:17
Resolved in the Slack thread

**Closed by jasperhuangg** 2024-07-29 17:17 UTC
Labels: Engineering, Daily, Overdue
