### ISSUE TITLE
Chat - Space between some emojis not consistent in a conversation with many emojis

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25703] opened 2023-08-22 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Logged into the Expensify App.
1. Open any chat between 2 people that has lots of emojis in a conversation.
2. Observe to see if the space between the emojis is consistent.

## Expected Result:
The space between the emojis should be consistent.

## Actual Result:
The space between some emojis is not consistent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/650f12fe-277f-4aa9-849b-e99baf6eddce

![Bug6173584_Android-Space_between_some_emojis_not_consistent_in_a_conversation_with_many_emojis](https://github.com/Expensify/App/assets/78819774/98da513d-3c31-401d-8299-5ed1b717ac8f)

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-08-26 15:42
I don't reproduce I think the reporter probably did a copy paste and added a space somewhere

**Comment by mallenexpensify** [comment] 2023-08-30 00:30
@lanitochka17 I'm unable to reproduce in BrowserStack. can you paste in the emoji you, or your team, were using?  Thx.

**Comment by lanitochka17** [comment] 2023-08-30 12:12
@mallenexpensify  Gap appear when copying and pasting emoji's.

https://github.com/Expensify/App/assets/78819774/a0e17a76-0ffe-4188-8c2f-f6c29c69e957

**Comment by ShogunFire** [comment] 2023-08-30 12:18
Yeah not a bug, you have space between the emojis but not at the end so when you copy paste the emoji from the end and from the beginning don't have a space between them. Try copying emojis wothout spaces

**Comment by mallenexpensify** [comment] 2023-09-04 03:06
Gonna close this as I'm unable to reproduce, thanks @ShogunFire for the comment.

**Closed by mallenexpensify** 2023-09-04 03:06 UTC
Labels: Daily, Overdue, Bug
