### ISSUE TITLE
[$1000] Copy update for #announce rooms

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23819] opened 2023-07-28 20:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where account A is signed in
2. Create workspace > invite account B to the workspace > navigate to announce room of the workspace
3. Observe the copy above the composer 'Use #announce to chat about anything'
4. Click on announce room header > click on 'Settings' > click on 'Who can post' link > click on 'Admins only'
5. Observe the copy above the composer for admin account A & member account B
## Expected Result: 
Copy change (approved here https://github.com/Expensify/App/issues/23819#issuecomment-1661146413):
Update `Say Hello` to `Welcome to #announce!`
Update: `Use #announce to chat about anything` to `Only admins can send messages in this channel`
## Actual Result: 
'Use #announce to hear about important announcements message is displayed even though members can't send messages since setting is changed to admins only

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d8776185-679f-45cd-9159-96b343df5f5a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690466219403929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
![Snip - (1) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/6fbff46c-589a-4281-a6b6-20eb8378770f)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1525bd4d7a0e8a8</li>
        <li>Upwork Job ID: 1686714666554503168</li>
        <li>Last Price Increase: 2023-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 25996931</li>
<li>natnael-guchima | Reporter | 25996933</li>
<li>ishpaul777 | Contributor | 26136150</li>
</ul></li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-08-01 18:49
@joaniew tagging you in for copy regarding updating the #announce room description. Should we update it? Imo the reporter does have a point that saying "Use announce to make announcements" doesn't make sense as a statement for employees. 

If we do want to change it, do we want two different copies, one for users and one for admins, or one that works for both user types? 

If we want two do we want something along the lines of,
- Admin: Use #announce to make announcements
- Employee: Follow #announce to see important updates from your admin

**Comment by joaniew** [comment] 2023-08-01 21:49
What if we did something like
- Update `Say Hello` to `Welcome to #announce`
- For everyone: `Only admins can send messages in this channel.`

**Comment by sonialiap** [comment] 2023-08-02 12:24
Looks good, thanks, Joanie

**Comment by ishpaul777** [comment] 2023-08-02 12:47
```
 else if (isAdminsOnlyPostingRoom(report) && !isAnnounceRoom(report)) {
        welcomeMessage.phrase1 = Localize.translateLocal('reportActionsView.beginningOfChatHistoryAdminOnlyPostingRoomPartOne');
        welcomeMessage.phrase2 = Localize.translateLocal('reportActionsView.beginningOfChatHistoryAdminOnlyPostingRoomPartTwo', {workspaceName});
    } else if (isAnnounceRoom(report)) {
        if(isAdminsOnlyPostingRoom(report)) {
            // set desired translation here
        } else {
            // set desired translation here

        }
    } 
```

**Comment by eVoloshchak** [comment] 2023-08-07 20:59
Both proposals are quite similar, since it's just a simple text label update. I think we can proceed with the first [proposal](https://github.com/Expensify/App/issues/23819#issuecomment-1656304840), which was posted by @samh-nl 

🎀👀🎀 C+ reviewed!

**Comment by marcochavezf** [comment] 2023-08-07 21:03
Thanks for the review @eVoloshchak, assigning @samh-nl 🚀

**Comment by ishpaul777** [comment] 2023-08-07 21:18
@eVoloshchak I still think both proposals are quite different in implementation my proposal was detailed enough with a Plan of action.

**Comment by ishpaul777** [comment] 2023-08-08 07:32
@marcochavezf @eVoloshchak please take a look here.

**Comment by ishpaul777** [comment] 2023-08-10 18:34
@eVoloshchak i am expecting a clarification i have gone through the raised PR none of the proposed changes are added by @samh-nl rather he added changes i proposed this feels unfair

**Comment by eVoloshchak** [comment] 2023-08-10 18:35
I'm on it right now @ishpaul777, apologies for the delay

**Comment by eVoloshchak** [comment] 2023-08-10 18:59
The proposal doesn't have to contain the exact code snippet or an exhaustive list of cases where a fix needs to be applied. So generally, the first proposal to identify the root cause and propose a **general idea**  on how to fix it - is a winning proposal. In this case it's a bit simpler, since the task was just to update a text label. That's why initially I chose @samh-nl proposal, even though it lacked the full technical details. 
However, raised [PR](https://github.com/Expensify/App/pull/24309/files) does indeed contain the changes proposed by @ishpaul777's [proposal](https://github.com/Expensify/App/issues/23819#issuecomment-1662149068)
Moving forward I would recommend sticking to the original proposals while implementing the solution, so that we're fair in any process without any conflicts

This is my mistake, since @ishpaul777's proposal is the correct one, proposing to use `isAdminsOnlyPostingRoom` initially.
@marcochavezf, could you reassign @ishpaul777 to this job please? Sorry for the confusion everyone

**Comment by ishpaul777** [comment] 2023-08-10 19:36
thanks @eVoloshchak

**Comment by ishpaul777** [comment] 2023-08-11 15:18
@marcochavezf can you assign me please i'll raise a PR immediately

**Comment by ishpaul777** [comment] 2023-08-15 06:57
Gentle Bump to @marcochavezf. Thanks

**Comment by marcochavezf** [comment] 2023-08-15 16:49
Thank you to @eVoloshchak for taking the time to re-evaluate the proposal, and thanks to @ishpaul777 for seeking clarification. Reviews can sometimes be challenging, and the details might not always be clear until the PR is raised. I appreciate everyone's hard work on this, and I'll assign this to @ishpaul777. Let's keep up the great teamwork!

**Comment by ishpaul777** [comment] 2023-08-15 17:25
Thanks @marcochavezf will raise a PR in few hours. Just want to confirm copy -

### Hero Text -
if announce room (anyone can send or admin can send only) or a room in which only Admin can send - "Welcome to #room_name!"

### Body text -

if announce room all can send (not changed)
if any room all member can send (not changed)
if announce room or any other room only admins can send - "Only admins can send messages in this room."

also can i get spanish copy?

**Comment by ishpaul777** [comment] 2023-08-15 19:30
cc - @joaniew @sonialiap for confirmation of copy and spanish translation.

**Comment by marcochavezf** [comment] 2023-08-16 17:28
@ishpaul777 

"Welcome to #room_name!" -> "Bienvenido a #room_name!"

"Only admins can send messages in this room." -> "Solo los administrators pueden enviar mensajes en esta sala"

**Comment by ishpaul777** [comment] 2023-08-16 17:36
Thanks @marcochavezf. Again I want to confirm if the announce room copy is "Welcome to #announce!"  for both cases (admin only and all members). can you confirm this too?

**Comment by ishpaul777** [comment] 2023-08-17 12:02
Thanks @eVoloshchak. Can you confirm the  other query too??

**Comment by eVoloshchak** [comment] 2023-08-17 16:02
> "Welcome to #announce!" for both cases (admin only and all members)

Yes, I believe it should be `Welcome to #announce!` for both cases

**Comment by ishpaul777** [comment] 2023-08-17 18:06
Okay Thanks! @eVoloshchak

I just noticed 
"Only admins can send messages in this channel"  is different in [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1691487187230889) and what @marcochavezf provided 
- (Solo los administradores pueden enviar mensajes en este canal) in slack
- "Solo los administrators pueden enviar mensajes en esta sala" by @marcochavezf

**Comment by eVoloshchak** [comment] 2023-08-28 17:45
The automation for this didn't work, The payment date should be 31 Aug
This also has caused one regression: https://github.com/Expensify/App/pull/24643#issuecomment-1688999930

**Comment by ishpaul777** [comment] 2023-09-01 08:13
@marcochavezf gentle bump for pay reminder

**Comment by ishpaul777** [comment] 2023-09-11 10:41
@sonialiap @marcochavezf gentle bump

**Comment by eVoloshchak** [comment] 2023-09-17 20:11
@marcochavezf, friendly bump on the above

**Comment by eVoloshchak** [comment] 2023-09-22 11:19
@marcochavezf, @sonialiap, gentle bump for payment

**Comment by Natnael-Guchima** [comment] 2023-09-25 07:20
@sonialiap A gentle bump for payment

**Comment by eVoloshchak** [comment] 2023-10-02 09:38
@sonialiap, bump on the above

**Comment by eVoloshchak** [comment] 2023-10-05 11:09
Bumping on Slack

**Comment by sonialiap** [comment] 2023-10-06 03:14
Thank you for the slack bump, Eugene! My apologies for the delay, everyone 🙇 

@Natnael-Guchima report $250 - offer sent
@eVoloshchak review -regression $500 - offer sent
@ishpaul777 fix -regression $500 - offer sent

No time bonus due to regression. Regression found within 24hr of PR merge

<img width="1130" alt="image" src="https://github.com/Expensify/App/assets/17131195/d56b4eb5-b512-425a-a7a9-aa0d017c60b2">

**Comment by Natnael-Guchima** [comment] 2023-10-06 03:41
Accepted the offer. Thanks @sonialiap

**Comment by eVoloshchak** [comment] 2023-10-06 07:45
Requested the payment via NewDot, thanks!

**Comment by sonialiap** [comment] 2023-10-06 11:09
@Natnael-Guchima report $250 - paid ✔️
@ishpaul777 fix -regression $500 - paid ✔️

Closing issue 💰

**Closed by sonialiap** 2023-10-06 11:09 UTC
Labels: Reviewing, External, Weekly, Waiting for copy, Bug

**Comment by JmillsExpensify** [comment] 2023-10-09 17:17
$500 payment approved for @eVoloshchak based on BZ summary.
