### ISSUE TITLE
NetSuite - Can't connect to NetSuite error message appears briefly before connection is done

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47855] opened 2024-08-22 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4880987&group_by=cases:section_id&group_order=asc&group_id=314239
**Email or phone of affected tester (no customers):** applausetester+gm103059@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Accounting
2. Click on the connect button next to NetSuite
3. Enter correct the NetSuite tokens> Confirm

## Expected Result:
There should be no error message since the connection is successfully established

## Actual Result:
"Can't connect to NetSuite" error message appears briefly before connection is successfully established

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c85ccb70-5aa4-4f62-a673-4c51aaacc295

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-22 12:37
Production:

https://github.com/user-attachments/assets/23903748-6984-4ad3-b9d4-2aee28e9e4fe

**Comment by brunovjk** [comment] 2024-08-22 13:31
It seems related to our [PR](https://github.com/Expensify/App/pull/47059), investigating.

**Comment by dangrous** [comment] 2024-08-22 14:02
yeah seems like it. Is `verified` false by default? Maybe it's flashing if the verification is taking longer than expected.

**Comment by brunovjk** [comment] 2024-08-22 14:24
I believe [this issue](https://github.com/Expensify/App/issues/44148) is related. Maybe the [PR](https://github.com/Expensify/App/pull/47483) will fix it as well, @dangrous can you test it? I don't have credentials.

**Comment by dangrous** [comment] 2024-08-22 15:12
struggling to test on dev, can't make it connect at all, so I can't test the PR... looking for a volunteer to help us out!

**Comment by arosiclair** [comment] 2024-08-22 16:35
This is just a dupe of https://github.com/Expensify/App/issues/44148 closing it out

**Closed by arosiclair** 2024-08-22 16:35 UTC
Labels: DeployBlockerCash, Engineering, Hourly
