### ISSUE TITLE
Notification - Messages do not arrive in the order to user B when sent it from user A

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14303] opened 2023-01-13 21:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Close the NewDot app.
2. Send messages in order from user A to user B 

## Expected Result:
Messages are arriving in the order to user B when sent it from user A

## Actual Result:
Messages do not arrive in the order to user B when sent it from user A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native
- [ ] iOS / native

**Version Number:** 1.2.54.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/212423044-1a348d61-23d8-4880-a046-c9f54be9d123.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160b52a996929c6cd</li>
        <li>Upwork Job ID: 1620562267961016320</li>
        <li>Last Price Increase: 2023-01-31</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-01-17 19:32
I do have the same notifications settings
![IMG_5641](https://user-images.githubusercontent.com/93399543/212994642-ebb6f38c-c9ba-44e1-927f-ad2a0c461224.png)

**Comment by MitchExpensify** [comment] 2023-01-24 04:01
To confirm, are you able to reproduce this using the steps in the OP @kbecciv ?

**Comment by kbecciv** [comment] 2023-01-27 15:14
@MitchExpensify Checking again, update you shortly.

**Comment by kbecciv** [comment] 2023-01-27 15:19
@MitchExpensify Able to reproduce this issue with device iPhone 8/14.2, build 1.2.60.0

https://user-images.githubusercontent.com/93399543/215121677-6ac85c16-9753-491d-8173-1ff30d962426.MP4

**Comment by MitchExpensify** [comment] 2023-01-31 23:18
Finally reproduced this, thanks for your patience:

![image](https://user-images.githubusercontent.com/36425901/215905152-cf314456-ffc5-4748-b4c6-60a8e94f11d6.png)

Coming from [the Bug Zero SO](https://stackoverflowteams.com/c/expensify/questions/14418),  and seeing as this will require backend changes, I'm going to label this internal and demolition as a next step

**Comment by MitchExpensify** [comment] 2023-01-31 23:20
Note: If this remains internal, it won't require any payment and I'll close the Upwork job accordingly. Will see if @mananjadhav agrees!

**Comment by mananjadhav** [comment] 2023-02-01 20:50
Yeah it is fine. I am assuming we won't have any App PR to be reviewed by C+? If that's the case we can close out the Upwork job.

**Comment by MitchExpensify** [comment] 2023-02-02 01:52
Cool, thanks @mananjadhav 

@mountiny I think I missed the eng label didn't I? Is that why you removed the demolition label (Just trying to get an internal engineer assigned)

**Comment by mountiny** [comment] 2023-02-02 11:19
@MitchExpensify oh yeah sorry we have deprecated a Demolition label per this Whats [next post](https://expensify.slack.com/archives/CC7NECV4L/p1668121020245589?thread_ts=1668041684.862529&cid=CC7NECV4L), so I have deleted it.

Can you add Engineering label?

also cc @Julesssss @arosiclair since this is related to notifications

**Comment by Julesssss** [comment] 2023-02-02 14:49
I haven't been able to reproduce on Android yet. There's also an argument for holding this, as improving the threaded/communication notifications _might_ resolve this.

**Comment by mountiny** [comment] 2023-02-02 15:49
Noting here that we have a similar issue https://github.com/Expensify/App/issues/13250 which is however not lnked ot notifications, but potentially the root cause might be the same. If we could confirm the root cause is same, this issue should be closed in favour of the one I have linked since that older and easier to reproduce

**Comment by arosiclair** [comment] 2023-02-02 16:02
I haven't dug into it too closely, but I'd say there's probably no way to guarantee in-order delivery of each individual notification. But I agree with @mountiny we should probably make sure #13250 is resolved first before digging any further into this. Threaded notifications from https://github.com/Expensify/Expensify/issues/258537 may also improve the UX of this.

**Comment by mountiny** [comment] 2023-02-02 16:08
Thanks for the context, I think it would make sense to close this one out in favour of https://github.com/Expensify/App/issues/13250 and the threaded notifications and then we can come back to this in case we see this happening even with those aforementioned items fixed. Thanks!

**Closed by mountiny** 2023-02-02 16:08 UTC
Labels: Daily, Internal, Bug

**Comment by Julesssss** [comment] 2023-02-02 17:35
Nice, yeah I agree with closing this 👍

**Comment by MitchExpensify** [comment] 2023-02-03 01:40
Woooh great!
