### ISSUE TITLE
[HOLD] Inconsistency between the behavior of the "next" button and the scrollability of steps 1 and 2.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20437] opened 2023-06-08 03:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Navigate to the "Settings" section.
2.	Click the "Security" option.
3.	Select the "Two-factor authentication" feature.
4.	Noted that in step 1, the "next" button can be scrolled, and a scrollbar is visible from top to bottom.
5.	In step 2, enter an invalid magic code to trigger the appearance of a scrollbar on the right.
6.	Observe that the "next" button remains fixed at the bottom, and the scrollbar is positioned from the top to just above the button.
## Expected Result: 
There should be consistency between both steps, meaning that the behavior of the "next" button should be the same in both cases. It should either be fixed or scrollable in both steps.
## Actual Result: 
The observed behavior is inconsistent. In step 1, the "next" button can be scrolled, while in step 2, the "next" button remains fixed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/66cfe083-5284-43a6-a4e1-85e3027f7794

https://github.com/Expensify/App/assets/43996225/7f245a81-3c16-48d5-b4d8-8b70db2e3e6f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685944613089219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Santhosh-Sellavel** [comment] 2023-06-08 17:27
@strepanier03 this is pretty much dupe of #20138, please add hold for now, thanks!

**Comment by usmantariq96** [comment] 2023-06-08 18:02
@strepanier03 Do I get the reporting bonus considering these are two different bugs?

**Comment by strepanier03** [comment] 2023-06-08 22:47
@Santhosh-Sellavel - Thank you I will do that. 

Is this GH you linked enough of a dupe that this GH should be closed or do you think it is different enough that the reporting bonus should be paid?

**Comment by Santhosh-Sellavel** [comment] 2023-06-09 16:20
@strepanier03 
This is just a dupe of the other one, only explained differently. So we can close this one straight away!

**Closed** 2023-06-15 19:11 UTC
Labels: Weekly, Bug
