### ISSUE TITLE
[$500] Web - App crash when open deep link request money confirmation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27357] opened 2023-09-13 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a WS
2. Click FAB button => request money
3. Select manual
4. Enter amount => Next
5. Select a WS => next
6. Copy URL and send in admin room
7. Logout and login again
8. Go to above admin room
9. Click the link confirm request money send above
10. Click outside to dismiss modal
11. Click the link again link confirm request money, Observe that the app crashes

## Expected Result:
The app does not crash

## Actual Result:
App crashed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c2bf75ab-8dc8-49eb-b1cb-9ba467c7d143

https://github.com/Expensify/App/assets/93399543/77ef374f-b6f8-4175-87dc-35afb933565b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694360354610749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01300647614a46b577</li>
        <li>Upwork Job ID: 1701968212595740672</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-09-13 14:59
Looks like a dupe of https://github.com/Expensify/App/issues/27085

**Comment by situchan** [comment] 2023-09-13 15:53
@namhihi237 can you please share console log?

**Comment by adelekennedy** [comment] 2023-09-18 09:06
@situchan does this look like a dupe of https://github.com/Expensify/App/issues/27085?

**Comment by situchan** [comment] 2023-09-18 09:08
https://github.com/Expensify/App/issues/27085 was reported by me and I am aware of this bug.
Once I confirm crash log from @namhihi237, we can determine.

**Comment by adelekennedy** [comment] 2023-09-21 07:56
pending crash log!

**Comment by adelekennedy** [comment] 2023-09-25 07:35
@situchan any updates here?

**Comment by situchan** [comment] 2023-09-25 07:42
It's same crash log. Let's close this as dupe

**Closed** 2023-09-28 09:02 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
