### ISSUE TITLE
Web – Task – Not updated message 1:1 DM in LHN after reassigned the task to another group member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29365] opened 2023-10-11 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any user
1. Navigate to a Group Chat
2. Click on the + in the compose box and select "Assign task"
3. Enter a Title and a Description
4. Assign a user from the group that you have access to
5. Create the task
6. Assign another user from the group that you have access to

## Expected Result:
Updated message 1:1 DM in LHN after reassigned the task to another group member

## Actual Result:
Not updated message 1:1 DM in LHN after reassigned the task to another group member. When create a task assigned to another member of the group, the 1:1 conversation is created in LHN with last message “assigned to [name]”, this message does not change after reassigned the task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] Windows: Chrome

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/44b5bf26-7705-4a97-a546-cd6107629061

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment] 2023-10-11 19:33
@lanitochka17 can you provide the slack convo for this one along with a screen recording

**Comment by DylanDylann** [comment] 2023-10-12 10:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not updated message 1:1 DM in LHN after reassigned the task to another group member

### What is the root cause of that problem?
Let's see the current behavior in our app
1. User A assigns a task in chat A-B (no assignee or assign to anyone), We always display "task for {title}" in the subtitle of chat A-B on LHN 
2. User A assigns a task in chat A-B (assign to C), We display "assigned to {C}" in the subtitle of chat A-C on LHN 

**Note:** chat A-B mean the chat betwwen user A and User B (1:1)

In the case 2, if then we change assignee, the subtitle of chat A-C on LHN is not updated because we don't update the report action in report A-C

### What changes do you think we should make in order to solve the problem?
**Option 1:** Always use "task for {title}" for created task report action in all places 

**Option 2:** In case 2, When changing assignee (assign to X), we also update the report action in chat A-C to "assigned to {X}"

**Option 3**: In case 2, When changing assignee (assign to X), we hide the created task message in chat A-C (becasue in this time C is not related to this task - this task is created by A, share to B, assign to X)

@shawnborton @abekkala Could you help to confirm what is expected for this issue? Thanks

### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2023-10-12 13:07
I'm actually quite unfamiliar with how tasks should work. @trjExpensify sorry to bother, but do you have a good idea on how this one should work?

**Comment by trjExpensify** [comment] 2023-10-12 16:01
I came across another issue with the reassigning tasks logic [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1697106566204779?thread_ts=1697011686.815509&cid=C02NZ2HGJAZ). Even after reassigning the task, the parent chat remains as the report action added to the creator<>original assignee DM and it's still shared with the original assignee, so we might be seeing another instance here of where the handling of reassigning tasks could be causing a few things to look a bit strange in reality.

So I think the question here is whether we should be adding a follow-up reportAction to communicate that the task was reassigned. That somewhat negates the stale report action in the original assignee's DM even though the task isn't assigned to them anymore. I.e

>assigned to Tom 
>reassigned to Shawn

CC: @thienlnam

**Comment by thienlnam** [comment] 2023-10-12 16:54
Hmm, this is kind of expected right now, we're not updating old reportActions with the new assignee name. 

> So I think the question here is whether we should be adding a follow-up reportAction to communicate that the task was reassigned.

**Comment by trjExpensify** [comment] 2023-10-13 00:21
>Hmm, this is kind of expected right now, we're not updating old reportActions with the new assignee name.

Yeah, I agree. It's sort of one of the benefits of the preview component for expense/iouReports being a "preview" of the report where all the actions for it live, so it just updates with the latest. i.e Tom owes/Jack owes, report total amount in aggregate etc.  

>I'm not totally sure this is necessary once we add edit history into the task report it will show things like 'Jack assigned the task to Tom' as a system message

Yeah exactly, that's what I mean though. The system message is a reportAction logged in the taskReport history, so it would negate this stale reportAction at the parentChat of the original assignee. it would also presumably notify the old assignee of that change as the taskReport is shared with them when the sys message is added, which is also helpful. Is this being worked on?

**Comment by thienlnam** [comment] 2023-10-13 23:26
>  Is this being worked on?

We have an issue for adding edit history to the task report https://github.com/Expensify/App/issues/23302
It's on hold for another linked issue, but it is being tracked

**Comment by trjExpensify** [comment] 2023-10-16 11:45
Okay cool, so we have an issue for it and this can be closed as it's expected to not update the original report action upon reassigning a task.

**Closed by trjExpensify** 2023-10-16 11:45 UTC
Labels: Daily, Overdue, Bug
