### ISSUE TITLE
[$250] Chat summary email doesn't display video content

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42301] opened 2024-05-16 14:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715820105101429

## Action Performed:
1. Open chat with someone
2. Send video and have them not open or read the chat
3. Observe recipients email
## Expected Result:
The email summarizing "missed" chats should indicate that there's a video that was sent that's representative of the video
## Actual Result:
 It shows a stretched image that doesn't indicate that this was a video
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (2)](https://github.com/Expensify/App/assets/38435837/f67698f8-bea4-4476-a4c1-3a1e550715c9)

![Snip - NataNSMDejkq and Rajan - mnata utest@gmail com - Gmail - Google Chrome](https://github.com/Expensify/App/assets/38435837/18727ca0-94ac-4083-90d1-bd90587f3988)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5cb10905ae74ed4</li>
        <li>Upwork Job ID: 1793007823619047424</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by dylanexpensify** [comment] 2024-05-21 19:55
Moving external

**Comment by samilabud** [comment] 2024-05-22 14:59
I think this is BE 🤔

**Comment by ikevin127** [comment] 2024-05-22 19:42
@dylanexpensify I think this should go `Internal` as am pretty sure the report email templating is handled from the BE side.

**Comment by ikevin127** [comment] 2024-05-28 19:12
Awaiting on decision for the issue to be labeled `Internal`.

**Comment by dylanexpensify** [comment] 2024-05-29 06:33
Moved!

**Comment by ikevin127** [comment] 2024-06-10 18:51
`Internal`: looking for a volunteer.

**Comment by ikevin127** [comment] 2024-06-14 18:19
`Internal:` looking for a volunteer.

**Comment by dylanexpensify** [comment] 2024-06-17 19:33
@ikevin127 you can stay assigned if you like, though might take a bit to get an internal volunteer

**Comment by ikevin127** [comment] 2024-06-17 19:43
Looking for a volunteer.

**Comment by dylanexpensify** [comment] 2024-06-21 10:00
Similar

**Comment by ikevin127** [comment] 2024-06-21 21:11
Looking for a volunteer 🎲

**Comment by ikevin127** [comment] 2024-06-27 22:30
Still looking for a volunteer 🎲

**Comment by ikevin127** [comment] 2024-07-01 18:05
Still looking for a volunteer 🎲

**Comment by ikevin127** [comment] 2024-07-02 20:23
Still looking for a volunteer 🎲

**Comment by ikevin127** [comment] 2024-07-08 20:24
Looking for a volunteer 🎲

**Comment by dylanexpensify** [comment] 2024-07-10 08:11
Similar, let's move weekly

**Comment by dylanexpensify** [comment] 2024-08-05 12:43
Same

**Comment by dylanexpensify** [comment] 2024-10-07 12:43
Same

**Comment by dylanexpensify** [comment] 2024-10-07 12:44
this is a lower priority though

**Comment by ikevin127** [comment] 2024-10-07 22:42
Still looking for a volunteer 🎲

**Comment by dylanexpensify** [comment] 2024-10-15 12:31
Reassigning as I head to parental leave next week! Thanks Anu!

**Comment by ikevin127** [comment] 2024-10-18 18:41
Still looking for a volunteer 🎲

**Comment by ikevin127** [comment] 2024-10-22 19:46
♻️ Issue is `Internal` - still looking for a volunteer!

##

@anmurali If not urgent, maybe this can be demoted to Weekly / Monthly to avoid daily `Overdue`.

**Comment by ikevin127** [comment] 2024-10-28 20:06
♻️ Issue is `Internal` - still looking for a volunteer!

##

@anmurali If not urgent, maybe this can be demoted to Weekly / Monthly to avoid daily `Overdue`.

**Comment by ikevin127** [comment] 2024-11-01 18:57
♻️ Issue is `Internal` - still looking for a volunteer!

##

@anmurali If not urgent, maybe this can be demoted to Weekly / Monthly to avoid daily `Overdue`.

**Comment by ikevin127** [comment] 2024-11-06 02:02
♻️ Issue is `Internal` - still looking for a volunteer!

##

@anmurali If not urgent, maybe this can be demoted to Weekly / Monthly to avoid daily `Overdue`.

**Comment by ikevin127** [comment] 2024-11-11 19:50
♻️ Issue is `Internal` - still looking for a volunteer!

##

@anmurali If not urgent, maybe this can be demoted to Weekly / Monthly to avoid daily `Overdue`.

**Comment by anmurali** [comment] 2024-11-12 01:31
Rotating to get another BZ assigned while OOO

**Comment by abekkala** [comment] 2024-11-12 19:46
co-assigning Anu so that she can take this back, if needed once back from ooo. 


Also, this is super old - and it was never added to a project. Is there a summary that can be given for me to catch up here. Looks like this has been in place since May??

**Comment by abekkala** [comment] 2024-11-12 21:36
ok after some reviewing and retesting. 

I was not able to reproduce this. 

I tested it and the 'image' is not stretched in the email notification. 
<img width="459" alt="Screenshot 2024-11-12 at 3 35 38 PM" src="https://github.com/user-attachments/assets/3780aa36-0487-4c8b-acb6-ae5fac34e8b0">

I can click the image and it brings me to the message. 

Closing.

**Closed by abekkala** 2024-11-12 21:36 UTC
Labels: Daily, Internal, Help Wanted, Bug
