### ISSUE TITLE
[$250] GBR is not on the Inbox even though the admin has tasks assigned to them

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50364] opened 2024-10-07 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-4
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danieldoglas 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728328637972249

## Action Performed:
1. Sign up in OD with gmail account
2. No GBR shows up on the inbox even though that is where we want to drive you
3. Go to settings and validate the account entering the magic code
4. Look at the inbox
## Expected Result:
Should have GBR shown
## Actual Result:
No GBR in the inbox
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9af26839-44e3-4fc6-a1da-9ed3e3a1b662

https://github.com/user-attachments/assets/c373e78b-6eb9-4d9e-8a19-52ee8d845619

https://github.com/user-attachments/assets/99de93b9-fd58-48cf-a58b-cd1832d4d819

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846571770167267008</li>
        <li>Upwork Job ID: 1846571770167267008</li>
        <li>Last Price Increase: 2024-10-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by truph01** [comment] 2024-10-08 01:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
GBR is not on the Inbox even though the admin has tasks assigned to them
### What is the root cause of that problem?
- The chat tab status is only update if its dependencies are changes:

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L71-L73

- So if there is a new assigned task, the status does not update immediately.
### What changes do you think we should make in order to solve the problem?
- We should add the reports and reportActions data to the above dependencies as well:

```
    const report = useOnyx(ONYXKEYS.COLLECTION.REPORT);
    const reportActions = useOnyx(ONYXKEYS.COLLECTION.REPORT_ACTIONS);
    const [chatTabBrickRoad, setChatTabBrickRoad] = useState<BrickRoad>(getChatTabBrickRoad(activeWorkspaceID));

    useEffect(() => {
        setChatTabBrickRoad(getChatTabBrickRoad(activeWorkspaceID));
    }, [activeWorkspaceID, transactionViolations, report, reportActions]);
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by anmurali** [comment] 2024-10-16 01:48
Discussing in Slack

**Comment by truph01** [comment] 2024-10-17 08:15
@abdulrahuman5196 What do you think about [my proposal](https://github.com/Expensify/App/issues/50364#issuecomment-2398449105)?

**Comment by abdulrahuman5196** [comment] 2024-10-23 17:44
Checking now

**Comment by abdulrahuman5196** [comment] 2024-10-28 19:41
Checking now.

**Comment by abdulrahuman5196** [comment] 2024-10-28 20:06
I don't even get the employees popup until I refresh. After that I am able to the GBR in the inbox. 
Do let me know if the bug is still reproducible, if so anything I am missing here?
@m-natarajan  @truph01 @anmurali 



https://github.com/user-attachments/assets/089317c5-e419-4fc9-adc2-c877ad4f66a4

**Comment by mvtglobally** [comment] 2024-10-30 09:46
Issue not reproducible during KI retests. (First week)

**Comment by anmurali** [comment] 2024-11-06 01:36
Yep, looks like this is now fixed. Closing.

**Closed by anmurali** 2024-11-06 01:36 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
