### ISSUE TITLE
[HOLD for payment 2024-01-04] [$250] Android - Workspace - Card icon is shown as a green square icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33594] opened 2023-12-26 14:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to Settings > Workspaces > any workspace.

## Expected Result:
All icons are displayed properly.

## Actual Result:
Card icon is shown as a green square icon.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/00ac5b25-4ccf-4e24-946c-feab33ad5ee9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b583b60c7afce86e</li>
        <li>Upwork Job ID: 1739665839943921664</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28070426</li>
<li>aswin-s | Contributor | 28070450</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mountiny** [comment] 2023-12-26 14:34
Potentially related to the expo image update, but its odd this is only happening on native android

**Comment by mountiny** [comment] 2023-12-26 15:10
QA confirmed only happening on native android

**Comment by mountiny** [comment] 2023-12-26 15:16
Actually found that this will most likely be related to the expo image update as there were some other icons which had similar issue https://expensify.slack.com/archives/C01GTK53T8Q/p1703186271886829

**Comment by mountiny** [comment] 2023-12-26 15:17
cc @akinwale @WojtekBoman

**Comment by mountiny** [comment] 2023-12-26 15:31
Still looking for proposals

**Comment by Tony-MK** [comment] 2023-12-26 15:56
On the dev environment, it seems like it works properly.

![Screenshot](https://github.com/Expensify/App/assets/22982173/f56ff889-6e8a-4b7b-9d18-4c2b95b3ef08)

**Comment by mountiny** [comment] 2023-12-26 16:08
I do not have android to confirm this in staging/ prod

**Comment by mountiny** [comment] 2023-12-26 16:09
Thanks! @Tony-MK Do you for sure have the latest main with expo-image installed?

**Comment by shubham1206agra** [comment] 2023-12-26 16:12
<img width="447" alt="Screenshot 2023-12-26 at 9 42 01 PM" src="https://github.com/Expensify/App/assets/58412969/5851c069-48c5-430b-b37a-f7d391e26154">

Not able to repro this on emulator

**Comment by Pujan92** [comment] 2023-12-26 16:12
Same for me too.

![Screenshot_1703607135](https://github.com/Expensify/App/assets/14358475/61f1e043-b695-4e0a-97d1-4367f7f53bd3)

**Comment by situchan** [comment] 2023-12-26 16:15
@mountiny can we get android apk for staging build? Contributors don't have access to it

**Comment by mountiny** [comment] 2023-12-26 16:28
Lets check on some adhoc build waiting for some to finish

**Comment by Tony-MK** [comment] 2023-12-26 16:30
@mountiny It was version `v1.4.17-1 Develop` but it seems other contributors have verified it.

**Comment by mountiny** [comment] 2023-12-26 16:41
I am making an adhoc buil don this up to date PR so you could test there https://github.com/Expensify/App/pull/33604

**Comment by situchan** [comment] 2023-12-26 17:17
reproduced in release build. Not happening in debug build

**Comment by shubham1206agra** [comment] 2023-12-26 17:19
Yes
In release build, it happens

**Comment by shubham1206agra** [comment] 2023-12-26 17:22
Checked from https://github.com/Expensify/App/pull/33603#issuecomment-1869656808

**Comment by shubham1206agra** [comment] 2023-12-26 17:32
> Tested on latest main on physical device, not reproducable. ![PHOTO-2023-12-26-21-56-59](https://private-user-images.githubusercontent.com/104348397/292894837-7611c1ef-69a0-4c4d-bed6-3a591e2a56c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDg1ODksIm5iZiI6MTcwMzYwODI4OSwicGF0aCI6Ii8xMDQzNDgzOTcvMjkyODk0ODM3LTc2MTFjMWVmLTY5YTAtNGM0ZC1iZWQ2LTNhNTkxZTJhNTZjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxNjMxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGUzYTE0OGRhYWZiMmYyN2QwNzlhMTlhZjNkOTI4MzA0YjMyZjAwZjdmZWI2OTEyMzQ5MGI3NjcwNjM1NDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XWVgGignBRvktqE2E-UITVlD9deIvdmjMRWN0eyAkb8)

@ishpaul777 What error are you getting here?

**Comment by kbecciv** [comment] 2023-12-26 18:38
@mountiny 
Issue is reported on:
1. Samsung Galaxy Note 10+ / Android 12
2. Samsung Galaxy Z Fold 4 / Android 14
3. Samsung Galaxy A02s/12
4. Pixel 6 / Android 14
5. Pixel 5 / Android 14

![Screenshot_20231226-123247](https://github.com/Expensify/App/assets/93399543/1b8b3890-668c-4e9d-80aa-7a69c7863c7c)
![Screenshot_20231227_023215_New Expensify](https://github.com/Expensify/App/assets/93399543/485b32ba-7111-40e2-a7ed-691e58f7b57b)
![photo_2023-12-26_13-32-26](https://github.com/Expensify/App/assets/93399543/44cd8521-7b0c-48eb-a57a-ef3f20d17d77)
![image (44)](https://github.com/Expensify/App/assets/93399543/ff06fd02-cfaa-4cc7-ae30-f8fab336df70)

**Comment by mountiny** [comment] 2023-12-26 21:38
@shubham1206agra @ishpaul777 @situchan any proposals for this one? I think if this would be a last DB, I would remove the label as its minor but would be nice to fix it

**Comment by aswin-s** [comment] 2023-12-26 21:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Card icon on Workspace home screen is shown as a green square icon.

### What is the root cause of that problem?

The`ExpensifyCard` icon file name is `expensifycard.svg`. There is another asset named `expensify-card.svg` which is mapped to `ExpensifyCardImage`. Looks like after release build there is a name conflict that causes the image assets to get swapped/overwritten.

### What changes do you think we should make in order to solve the problem?

Simply rename the file to `expensify-card.svg` and update the import in Expensicons.ts like below

```ts
import ExpensifyCard from '@assets/images/expensify-card-icon.svg';
```

To verify the fix generate a release build using below command and check the Workspace screen.

```bash
npx react-native run-android  --mode release
```

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by mountiny** [comment] 2023-12-26 21:48
@aswin-s interesting, did you test this theory?

**Comment by aswin-s** [comment] 2023-12-26 21:49
@mountiny Yes, I generated a release build locally and tested on simulator. I could simulate the green square icon on simulator before the fix too.

**Comment by mountiny** [comment] 2023-12-26 21:54
@aswin-s Can you make a draft PR so we can generate adhoc build for testing?

**Comment by aswin-s** [comment] 2023-12-26 21:57
@mountiny Done!

**Comment by situchan** [comment] 2024-01-11 19:32
Not able to find offending PR but from [deploy checklist](https://github.com/Expensify/App/issues/33576), I think expo-image PR is the culprit.
This was caught by QA team during regression test so no need new regression test.
To prevent such bugs further, it would be good to add eslint rule to avoid duplicated resource file names after excluding `-`, but not a big deal.

**Comment by mountiny** [comment] 2024-01-11 23:15
@JmillsExpensify ready for payment

**Comment by JmillsExpensify** [comment] 2024-01-24 03:17
Payment summary:

 - Issue reporter: QA
 - Contributor: $250 @aswin-s 
 - Contributor+: $250 @situchan

**Comment by JmillsExpensify** [comment] 2024-01-24 03:19
All contracts paid out, closing.

**Closed by JmillsExpensify** 2024-01-24 03:19 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
