### ISSUE TITLE
[$500] Web - Assignee email or name is missing for other users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27144] opened 2023-09-11 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to chat with userB
2. Click on + icon and select assign task option
3. Enter title and create task
4. Go to task thread
5. Click on Assignee and select Assignee with whom userB didn't have chat history
6. From userB, check the Assignee in task thread

## Expected Result:
Assignee email or name should show

## Actual Result:
Assignee email or name is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a06e0091-1266-413b-9947-232dacc754f5

https://github.com/Expensify/App/assets/93399543/89654fbc-03e1-415f-a5d7-73435fecba6a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1693807403315129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f80383d65e746df</li>
        <li>Upwork Job ID: 1701221850589401088</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by h0u554m** [comment] 2023-09-11 16:25
Stop emitting the 'assign event' when a user is assigned, and emit it only when a message is sent.

Your Expensify account email: https://new.expensify.com/a/15606409
Upwork Profile Link: https://www.upwork.com/freelancers/~01d68a22e5d906bca6

**Comment by h0u554m** [comment] 2023-09-11 16:39
Stop emitting the 'assign event' when a user is assigned, and emit it only when a message is sent.

Contributor details
Your Expensify account email:
houssammarrakchimk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d68a22e5d906bca6

**Comment by h0u554m** [comment] 2023-09-11 16:39
Stop emitting the 'assign event' when a user is assigned, and emit it only when a message is sent.

Contributor details
Your Expensify account email:
houssammarrakchimk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d68a22e5d906bca6

**Comment by flaviadefaria** [comment] 2023-09-14 18:37
We're waiting for proposals.

**Comment by flaviadefaria** [comment] 2023-09-15 10:41
@kadiealexander  I'm going OoO for a week so assigning this to you so that you can move it forward in the meantime. I'll take it back from you once I'm online again. Thanks!

**Comment by kmostafa599** [comment] 2023-09-18 19:40
Problem Statement
The current implementation of the setAssigneeValue function in our codebase generates random IDs and uses a fake owner email and owner account when creating an optimistic chat report. This approach can lead to inconsistencies and potential issues in our application, as the generated IDs and owner details do not correspond to actual user data.

Proposed Solution
We propose to modify the setAssigneeValue function to use the proper user email instead of a fake one. This will involve the following steps:

Retrieving User Data: When the setAssigneeValue function is called, we will retrieve the actual user data from our database or authentication service or calling event. This data should include the user’s email and account ID.

Modifying Chat Report Generation: In the buildOptimisticChatReport function, we will replace the randomly generated IDs and fake owner email with the actual user data retrieved in step 1. This will ensure that the chat report is linked to an actual user account.

Updating Share Destination: If a share destination isn’t already set in this step, we will set the shareDestination as that chat report.

Benefits
Implementing this solution will provide several benefits:

Data Consistency: By using actual user data instead of randomly generated IDs and fake details, we can ensure consistency across our application.

**Comment by kadiealexander** [comment] 2023-09-19 05:47
@ArekChr any thoughts on the proposal above?

**Comment by ArekChr** [comment] 2023-09-19 08:26
@kadiealexander I couldn't reproduce this error, the display name is always visible in assignee of task

**Comment by kadiealexander** [comment] 2023-09-19 22:56
![image](https://github.com/Expensify/App/assets/59587260/dd35e49c-2622-4938-bcb2-8127606116d3)

I also can no longer reproduce this error. @gadhiyamanan could you please confirm if you can still reproduce it?

**Comment by gadhiyamanan** [comment] 2023-09-20 05:33
it is still reproduciable 
you need to select Assignee with whom userB didn't have chat history


https://github.com/Expensify/App/assets/54790231/9f4ee883-9bdd-4e91-8210-fa0d234db7eb

**Comment by kadiealexander** [comment] 2023-09-20 23:23
My userB was a brand new account with no conversation history with the assignee:

![image](https://github.com/Expensify/App/assets/59587260/4644c06c-14aa-4ca3-8f08-572c71ca211f)

**Comment by kadiealexander** [comment] 2023-09-20 23:36
Tried again with a gmail account as User B, all accounts are on different domains:

![image](https://github.com/Expensify/App/assets/59587260/4f9be32a-9561-45eb-b279-c0e18126f28b)

**Comment by ArekChr** [comment] 2023-09-21 08:27
@kmostafa599 What is the root cause of the issue? Please follow the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md#what-is-the-root-cause-of-that-problem)

**Comment by kmostafa599** [comment] 2023-09-23 01:46
The current implementation of the setAssigneeValue function in our codebase generates random IDs and uses a fake owner email and owner account when creating an optimistic chat report. This approach can lead to inconsistencies and potential issues in our application, as the generated IDs and owner details do not correspond to actual user data.

The root cause of this problem is the use of randomly generated IDs and fake owner details when creating an optimistic chat report. This can lead to inconsistencies as these details do not match with actual user data.

 modify the setAssigneeValue function to use the proper user email instead of a fake one. This will involve the following steps:

Retrieving User Data: When the setAssigneeValue function is called, we will retrieve the actual user data from our database or authentication service. This data should include the user’s email and account ID.

Modifying Chat Report Generation: In the buildOptimisticChatReport function, will replace the randomly generated IDs and fake owner email with the actual user data retrieved in step 1. This will ensure that the chat report is linked to an actual user account.

Updating Share Destination: If a share destination isn’t already set in this step, will set the shareDestination as that chat report.

**Comment by kadiealexander** [comment] 2023-09-25 06:33
@ArekChr any further thoughts?

**Comment by mvtglobally** [comment] 2023-09-28 03:19
Issue not reproducible during KI retests. (First week)

**Comment by kadiealexander** [comment] 2023-09-28 04:36
@gadhiyamanan can you still reproduce this? I've never been able to.

**Comment by gadhiyamanan** [comment] 2023-09-28 05:16
still able to reproduce

https://github.com/Expensify/App/assets/54790231/4ec9131e-4737-474d-b245-fb19cc0618b6

**Comment by kadiealexander** [comment] 2023-09-29 01:45
@gadhiyamanan the video doesn't match the steps in the OP, could you please rewrite new reproduction steps?

**Comment by gadhiyamanan** [comment] 2023-09-29 02:59
I am doing the same thing, which step am i missing ?

**Comment by kadiealexander** [comment] 2023-09-29 03:26
I'm not sure, I just can't reproduce. When I try, I can't assign the task to a third user. 

https://github.com/Expensify/App/assets/59587260/371e8110-7d65-4b41-be31-89756cc42df7

**Comment by gadhiyamanan** [comment] 2023-09-29 04:54
try this 

1. from userA, create a chat with userB and userC (receiver also need to send message otherwise it will not reflect in Assignee list )
2. from userA, Click on + icon and select assign task option
3. Enter title and select userB as share somewhere 
4. create task
5. from userB, Go to task thread
6. from userA, Go to task thread and Assign task to userC 


https://github.com/Expensify/App/assets/54790231/e2524d43-5b87-4969-9cf4-6b6ad19effc1

**Comment by flaviadefaria** [comment] 2023-10-03 10:34
I tried reproducing this and also couldn't reproduce it. @kadiealexander @ArekChr have you been able to reproduce this with  @gadhiyamanan last steps?

**Comment by ArekChr** [comment] 2023-10-03 11:03
Same here, couldn't reproduce this issue, when reassigning tasks to someone else I see the correct avatar and display name

**Comment by flaviadefaria** [comment] 2023-10-04 11:38
Ok since no one seems to be able to reproduce this I'll close this for now.

**Closed by flaviadefaria** 2023-10-04 11:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
