### ISSUE TITLE
payment due 1st August LOW: [$500] New feature request: Frequently used emoji is not updated when reacting to messages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37807] opened 2024-03-06 00:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709671306336899

## Action Performed:
1. Open any chat
2. React with emoji for a message

## Expected Result:
Emoji should be displayed in the frequently used emojis 

## Actual Result:
Frequently used emoji list is not updated.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f2c96817-8d79-42e9-8068-6b48e3ed18cc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a421e19748004629</li>
        <li>Upwork Job ID: 1767189140562845696</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-03-06 01:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Frequently used emoji is not updated when reacting to messages
### What is the root cause of that problem?
- When AddEmojiReaction, we do not call API ```UpdateFrequentlyUsedEmojis``` like we did when we typing a emoji message
### What changes do you think we should make in order to solve the problem?
- We can update [this](https://github.com/Expensify/App/blob/91c2b492740f04a4167157f1fc3712bef39b15ec/src/libs/actions/Report.ts#L2213) to:
```
    User.updateFrequentlyUsedEmojis(EmojiUtils.getFrequentlyUsedEmojis(emoji));
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by zanyrenney** [comment] 2024-03-11 14:02
hey @jayeshmangwani - please can you review the proposals above?

**Comment by jayeshmangwani** [comment] 2024-03-11 14:15
Starting reviewing proposals

**Comment by jayeshmangwani** [comment] 2024-03-11 14:52
@neonbhai Your RCA seems wrong
> But we don't have it for when emoji is selected from the popover.

We call updateFrequentlyUsedEmojis when we select the emoji from the suggestions.




I like the @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/37807#issuecomment-1979924129) as they suggest to call the `updateFrequentlyUsedEmojis` when we call the `toggleEmojiReaction` function

🎀👀🎀 C+ reviewed

**Comment by iwiznia** [comment] 2024-03-11 20:17
hmmmmm I think this issue needs to be solved in the backend probably, no? In AddEmojiReaction and RemoveEmojiReaction otherwise we would not be following our principle of only doing 1 API request per user interaction...

**Comment by yuwenmemon** [comment] 2024-03-11 21:50
Yeah @iwiznia is right, this needs to be remedied in the backend.

**Comment by nkdengineer** [comment] 2024-03-11 22:38
@yuwenmemon But we still need the BE change as I mentioned in my proposal, right? For example, we still need to handle the offline case

**Comment by yuwenmemon** [comment] 2024-03-11 22:59
Yes, that's correct we'd want to optimistically update the frequently used emojis. However, we shouldn't be doing that until the backend solution is in place.

**Comment by nkdengineer** [comment] 2024-03-11 23:06
@yuwenmemon Thanks. Can this issue be external after the BE change?

**Comment by nkdengineer** [comment] 2024-03-14 06:13
@yuwenmemon Please help ping on this issue if the BE is done. I just want to test it again after BE changes. Please help check my [comment](https://github.com/Expensify/App/issues/37807#issuecomment-1989612163) as well

**Comment by zanyrenney** [comment] 2024-03-14 11:23
to be clear @yuwenmemon would you be backing those backend changes? should we make this weekly and on hold for those changes for now then?

**Comment by yuwenmemon** [comment] 2024-03-14 18:20
@zanyrenney yeah that sounds like a good idea as it will take me a little bit of time to get to this

**Comment by iwiznia** [comment] 2024-03-14 21:29
Ahh great catch @nkdengineer! You are correct, we need to do this both in the backend and the frontend.
@yuwenmemon I think both changes could be made independently, no?

**Comment by yuwenmemon** [comment] 2024-03-14 21:30
Well, wouldn't it be weird to optimistically update your frequently used emojis when it's not actually getting saved in the backend just yet?

**Comment by iwiznia** [comment] 2024-03-14 21:39
Hmmm maybe weird, but I can't think of anything bad that would happen. Yes, if you switch deices or log out and back in the list would change, but that's a bit meh especially if we are adding the backend part soon afterwards.
Anyway, we can hold too, just pointing out that it might not be totally necessary.

**Comment by yuwenmemon** [comment] 2024-03-14 21:56
Actually, you know what, since the front-end sends the entire [FrequentlyUsedEmoji](https://github.com/Expensify/App/blob/e59d87f870bf9731b251d7286675ed1a44076b52/src/types/onyx/FrequentlyUsedEmoji.ts) array anyway, I think it's something that will need to be passed to `AddEmojiReaction` as a param, in addition to optimistic data. So, okay let's actually do the FE first - and @nkdengineer can you send the updated FrequentlyUsedEmoji array to AddEmojiReaction similar to how we would do when [calling `UpdateFrequentlyUsedEmoji` directly](https://github.com/Expensify/App/blob/08d357d0a9187f03c2810fe1f39221379319ffdd/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L296) so that we can update it there?

cc @stitesExpensify as I'm admittedly unfamiliar with the emoji code to double check me on this.

**Comment by iwiznia** [comment] 2024-03-14 22:05
Huh? I don't follow... why would we need to pass the whole array if you are just adding one reaction?
How I thought this would work is that the backend would just get the emoji passed and add it to the recently used nvp.

**Comment by yuwenmemon** [comment] 2024-03-14 22:41
All the logic for generating the content for the frequentlyUsedEmojis NVP is done in the front-end:
https://github.com/Expensify/App/blob/f31cd54bb4255396ce0564c9c14068cf686c46f0/src/libs/EmojiUtils.ts#L211-L240

There's some validation in the API, but in general, it's just saving what is passed to it:
https://github.com/Expensify/Web-Expensify/blob/e96ff0ff608fe147ef4c294be4fc3b614c7b0e5c/lib/UserAPI.php#L3992-L4024

The way I see it we can:
1) Duplicate all the above logic in the back-end in Auth, risking the two get out of sync at some point, or have minor inconsistencies that are hard to tell. 

or

2) Reuse the method above (`getFrequentlyUsedEmojis`) to generate the Frequently Used Emojis the same way we would as if saving them the way we currently do, and then just save that front-end generated value in Auth when calling `AddEmojiReaction`

Option 2 seems simpler to me. Again, I'd also want to check with @stitesExpensify to see what he thinks.

**Comment by nkdengineer** [comment] 2024-03-15 15:08
@stitesExpensify What do you think about these [two options](https://github.com/Expensify/App/issues/37807#issuecomment-1998599963)?

**Comment by jasperhuangg** [comment] 2024-03-18 19:07
Gonna be working on the back-end for this

**Comment by stitesExpensify** [comment] 2024-03-19 22:11
👋 apologies for the delay I was OOO.

I don't think that `3` is an option @iwiznia because that is not offline first. 

Between 1/2 I agree that 2 is the cleaner option compared to duplicating logic in both the front and back end

**Comment by iwiznia** [comment] 2024-03-19 22:12
> I don't think that 3 is an option @iwiznia because that is not offline first.

We don't have to be extremists, I don't think it matters if we don't update optimistically the recently used emojis

**Comment by iwiznia** [comment] 2024-03-19 22:13
> 2 is the cleaner option compared to duplicating logic in both the front and back end

2 is IMO the worst option

**Comment by yuwenmemon** [comment] 2024-03-20 20:01
@jasperhuangg assigning to you if you're gonna be working on the BE for this!

**Comment by nkdengineer** [comment] 2024-03-20 20:07
@yuwenmemon  Can I fix the offline case in the FE side parallel?

**Comment by jasperhuangg** [comment] 2024-03-20 21:28
@iwiznia Can you clarify why option 2 is the worst?

I think if we already have offline-first behavior we shouldn't break it in order to get rid of `UpdateFrequentlyUsedEmojis`. Can you point out which part of this approach you don't agree with?

1. We remove `UpdateFrequentlyUsedEmojis` everywhere in the code.
2. We use the front-end function [`getFrequentlyUsedEmojis`](https://github.com/Expensify/App/blob/68a96ed9488c50f473d1ed12a5954ae45f02a3f5/src/libs/EmojiUtils.ts#L211-L240) to generate optimistic frequently used emojis debounced as the user types. We call it again when we call `AddComment` or `AddEmojiReaction` in the front-end.
3. We send the value it generates to the `AddComment` and `AddEmojiReaction` commands, and let Auth handle setting the NVP.

To me it feels like this approach is a pretty big improvement over the existing one:
- We don't call `UpdateFrequentlyUsedEmojis` debounced anymore–IMO that was pretty wasteful since a user wouldn't switch devices while they were in the middle of typing a comment and wouldn't need the NVP set on their other devices.
- We still maintain offline-first functionality
- We can do all the writes in a single Auth command

**Comment by jasperhuangg** [comment] 2024-03-20 21:31
@nkdengineer We're still discussing the best approach for tackling this issue–we'll see what we land on before deciding the order in which the FE/BE changes need to be handled.

**Comment by iwiznia** [comment] 2024-03-20 21:55
> @iwiznia Can you clarify why option 2 is the worst?

Because if you send a message with just 👍 we would also send a list of 25 emojis that takes up ~1950 bytes. This would happen on every message you send with an emoji. It would also happen whenever you added a reaction to any message. But really, that information is not needed, given that the backend already has that data.

**Comment by jasperhuangg** [comment] 2024-03-20 22:33
@iwiznia Got it, I guess that makes sense. I think I agree with your opinion on option 3 then.

What I've gathered from this is:
- What we currently have is bad, because we're calling `UpdateFrequentlyUsedEmojis` multiple times as the user is typing. This creates a lot of unnecessary load on our servers as it is a write command, plus it's a command that has known performance issues: https://github.com/Expensify/Expensify/issues/379910
- Option 1 is bad, because we'll be duplicating logic in the front-end and back-end, which means we're doing the same work twice and could also cause bugs.
- Option 2 is bad, because we'll be sending way too much data that will slow down `AddComment` and `AddEmojiReaction`, two very frequently used commands.

Option 3 is bad because it isn't offline-first, but after thinking about it some more, how bad would not optimistically updating the frequently used emojis really be? Worst case is, if someone is using emojis offline or as they type:
- The sorting order of two emojis won't be swapped in the frequently used list
- An emoji won't be added to the end of the frequently used list

But I feel like neither of those cases would even happen that frequently–it's not like the frequently used emoji NVP changes every time someone uses an emoji.

cc @stitesExpensify I know you handled the design for making this offline-first, what are your thoughts on what I've laid out here?

**Comment by yuwenmemon** [comment] 2024-03-20 22:41
Yeah, that's a great point @jasperhuangg I don't think we need to update your frequently used emojis when offline. Especially after sustained use the frequently used emojis would become relatively static anyway.

**Comment by iwiznia** [comment] 2024-03-21 15:05
lol ok so [you agree](https://github.com/Expensify/App/issues/37807#issuecomment-2008236183) 😄

**Comment by stitesExpensify** [comment] 2024-03-21 19:37
If we are okay with not having it be offline first then option 3 seems like the best to me

**Comment by jasperhuangg** [comment] 2024-03-26 23:34
Going OOO for the rest of the week so I won't have time to look into this until next week.

**Comment by zanyrenney** [comment] 2024-04-04 09:51
Seeing as this is performance related, I have added this to NewExpensify performance project, though I think it is low.

**Comment by zanyrenney** [comment] 2024-04-15 18:14
@jasperhuangg any update here? I can see you're back now. Would be great to get this closed out please.

**Comment by zanyrenney** [comment] 2024-04-24 14:03
Thanks for the update @jasperhuangg 

Going by the weekly cadence makes sense i think! Did you have time write up that straightforward solution though so that we can have it in this GitHub issue and move forward? Thanks!

**Comment by jasperhuangg** [comment] 2024-05-03 20:37
@zanyrenney The solution requires back-end changes, so unless we get another internal engineer on this we won't really be able to move forward.

It essentially involves deleting all frontend logic related to updating the optimistic frequently used emojis and implementing logic in the back-end that handles updating the NVP every time a user reacts to or sends a report action.

**Comment by quinthar** [comment] 2024-05-12 18:47
Moving this to #vip-vsb project.

**Comment by jasperhuangg** [comment] 2024-05-13 18:35
Made some good progress with the release PRs I have assigned, so I'm updating the priority of this to Daily.

**Comment by jasperhuangg** [comment] 2024-05-15 20:32
Made some more progress on the PRs today, not overdue.

**Comment by zanyrenney** [comment] 2024-05-17 11:43
any further progress here @jasperhuangg ?

**Comment by zanyrenney** [comment] 2024-05-20 11:09
bump @jasperhuangg

**Comment by jasperhuangg** [comment] 2024-05-23 19:10
@zanyrenney Sorry was OOO. I'm back now and prioritizing the PRs for this since they have to do with API performance.

**Comment by zanyrenney** [comment] 2024-05-24 09:03
Should we make this weekly then? Sounds like the ksv2 prioritsation is wrong? @jasperhuangg

**Comment by zanyrenney** [comment] 2024-05-24 09:03
Changing to weekly, feel free to change it back if you disagree.

**Comment by jasperhuangg** [comment] 2024-05-27 16:50
@zanyrenney Ah sorry for the confusion, I think we should actually keep it Daily. I've been working on this with a Daily cadence, since this issue has to do with API performance, which is a top priority.

**Comment by jasperhuangg** [comment] 2024-05-29 23:38
Steady progress on this, looking to submit the PRs for review either today or early tomorrow depending on how testing goes.

**Comment by jasperhuangg** [comment] 2024-06-03 17:08
Still working on this! Not overdue, moving on to manual testing and should be able to submit for official review soon.

**Comment by jasperhuangg** [comment] 2024-06-14 17:10
PRs are still under review

**Comment by jasperhuangg** [comment] 2024-06-24 20:35
The App PR was deployed to production, and I just took the HOLD off of https://github.com/Expensify/Auth/pull/10919, we should be good for one last review before merging it!

**Comment by jasperhuangg** [comment] 2024-07-01 17:53
Just the following PRs left on this, will push them forward now that the most important parts in the Auth PR are deployed.

https://github.com/Expensify/App/pull/42208
https://github.com/Expensify/Web-Expensify/pull/42176

**Comment by mvtglobally** [comment] 2024-07-11 03:42
Issue not reproducible during KI retests. (First week)

**Comment by jasperhuangg** [comment] 2024-07-17 18:35
Just merged the Web-E PR officially removing the `UpdateFrequentlyUsedEmojis` command!

**Comment by jasperhuangg** [comment] 2024-07-17 18:35
I think we can close this out :)

**Comment by jayeshmangwani** [comment] 2024-07-17 19:12
@jasperhuangg Can we please open the issue for handling the payment of reviewed [PR](https://github.com/Expensify/App/pull/42208)?

**Comment by jasperhuangg** [comment] 2024-07-18 17:16
Oops, yes sorry @jayeshmangwani. @zanyrenney we need to handle paying them out for the review of that PR. Thanks fo bringing that to my attention!

**Comment by jasperhuangg** [comment] 2024-07-18 17:17
Oops, yes sorry @jayeshmangwani. @zanyrenney we need to handle paying them out for the review of that PR. Thanks fo bringing that to my attention!

**Comment by mvtglobally** [comment] 2024-07-19 03:11
Issue not reproducible during KI retests. (Second week)

**Comment by jayeshmangwani** [comment] 2024-07-21 08:10
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: **New feature**
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **New feature**
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


## Regression Test Proposal

1. Create a new account.
2. Using this account, send a message with a few emojis in any report.
3. Open the emoji picker in the composer.
4. Verify the emojis you used in the message appear in the "Frequently Used" section.
5. Now react to the comment you just made.
6. Open the emoji picker in the composer.
7. Verify the emoji you used to react is sorted to the front of the "Frequently Used" list.

Do we agree 👍 or 👎

**Comment by jayeshmangwani** [comment] 2024-07-30 11:26
@zanyrenney, can you please add a payment summary for the issue? The issue is now ready to be closed. The PR hit production on July 17.

**Comment by zanyrenney** [comment] 2024-08-01 12:28
Sure thing!

**Comment by zanyrenney** [comment] 2024-08-01 12:49
**payment summary**

$500 owed to @jayeshmangwani for this issue.

**Closed by zanyrenney** 2024-08-01 12:49 UTC
Labels: Reviewing, Daily, Internal, NewFeature, Help Wanted, Bug

**Comment by jayeshmangwani** [comment] 2024-08-05 04:57
Requested as per https://github.com/Expensify/App/issues/37807#issuecomment-2262959655

**Comment by JmillsExpensify** [comment] 2024-08-05 12:08
$500 approved for @jayeshmangwani
