### ISSUE TITLE
mWeb/Safari - LHN - A black space can be seen at the bottom for a short time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32646] opened 2023-12-07 11:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/31152

**Version Number:** 1.4.9.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Open any conversation
3. Tap on the back button

## Expected Result:
The black space shouldn't be appearing.

## Actual Result:
A black space can be seen at the bottom for a short time after navigating back to LHN from any conversation. It's even more noticeable if you do a FAB message to a new account and go back to LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6304170_1701935143538!capture](https://github.com/Expensify/App/assets/115492554/0b003cb1-b9bf-4e3a-869b-e7a22d41ac3a)

https://github.com/Expensify/App/assets/115492554/2bfcf454-642d-4f53-a67a-c4e50ce5e12e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Balogh08** [comment] 2023-12-08 17:24
I cannot reproduce the bug. In the description for the platform `Android: mWeb Chrome` is checked but the video seems to show `iOS: mWeb Safari`. I checked both but could not reproduce the bug. Could you provide more information? 😄

**Comment by Santhosh-Sellavel** [comment] 2023-12-10 19:32
> I cannot reproduce the bug. In the description for the platform `Android: mWeb Chrome` is checked but the video seems to show `iOS: mWeb Safari`. I checked both but could not reproduce the bug. Could you provide more information? 😄

@izarutskaya bump!

**Comment by lanitochka17** [comment] 2023-12-12 22:15
@Santhosh-Sellavel You are right, this is iOS: mWeb Safari.
And my phone shows a white glare while switching
Iphone 14 Pro/Max/Safari


https://github.com/Expensify/App/assets/78819774/e7fa54f2-d29b-43ee-a98c-2539a2e09ffb

**Comment by stephanieelliott** [comment] 2023-12-13 15:34
Thanks @lanitochka17, issue body has been updated

**Comment by Santhosh-Sellavel** [comment] 2023-12-18 18:33
Can you reproduce this one @stephanieelliott?

**Comment by stephanieelliott** [comment] 2023-12-19 21:05
Nope I can't repro either! Given that its such a minor visual issue even when reproducible, I am gonna opt to close this.

**Closed by stephanieelliott** 2023-12-19 21:05 UTC
Labels: External, Daily, Help Wanted, Bug
