### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] Desktop - Chat - Infinite loading displayed on selected chat when navigate to RHP with deeplink

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33149] opened 2023-12-15 11:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition: user should be Signed Out on Desktop
1. Open http://staging.new.expensify.com/
in Web and select any conversation in LHN
2. Navigate on http://staging.new.expensify.com/enable-payments
3. Click on "Allow" to open the Desktop app
4. Click outside of the RHP to close it

## Expected Result:
Previously selected chat should be loaded and properly displayed

## Actual Result:
Infinite loading displayed on selected conversation when navigate to RHP with deeplink

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/83c2c43e-2b6e-46a0-bb5f-a0ecfcf32538

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae306e7095356be1</li>
        <li>Upwork Job ID: 1735616582656286720</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 28064493</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-12-15 12:22
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Infinite loading displayed on selected conversation when navigate to RHP with deeplink to desktop app.

## What is the root cause of that problem?

The reason why we get the **infinite loading spinner on local development desktop** is because the desktop app is calling navigate with transition route **and this action is not handled by the navigator**.

The way the flow was designed to work for the desktop app:
- user can be authenticated or not
- user attempts transition from web to desktop app
- web app prompts user to open URL in desktop app
- upon opening,  web sends transition route to desktop app with `exitTo`, `email` and `shortLivedAuthToken` to re-authenticate the user then redirect to `exitTo` route at the end of all this

**Important**: transition route is used to deeplink web to desktop in this case, it was not designed to actually be called by the navigator once we're in the desktop app.

## What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/173582ff506202ca32671cc0a7acea1f440dddb0/src/libs/actions/Report.ts#L2031

We have to make sure that the transition route passed from the main electron process is **NOT** called by the navigator once we are transitioned into the desktop app, for this we check:
- the platform is desktop
- route is `transition` type

if these conditions are met then we **return** meaning we not call the react navigation with the transition route which causes the issue on staging / local desktop app.

```diff
...

                // If the platform is desktop and route is `transition` we don't want to navigate
                // to the route because it will display the infinite loading indicator.
                // See issue: https://github.com/Expensify/App/issues/33149
+               if (getPlatform() === CONST.PLATFORM.DESKTOP && route.includes(ROUTES.TRANSITION_BETWEEN_APPS) {
+                   return;
+               }

             Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH);
```

## Videos

<details>
<summary>MacOS: Desktop (staging / local)</summary>

- staging

https://github.com/Expensify/App/assets/56457735/5428f539-2b24-4149-8893-7516173b95c6

- local dev

https://github.com/Expensify/App/assets/56457735/8bc8be14-30b2-41de-bc61-bf3811926968

</details>

**Comment by narefyev91** [comment] 2023-12-15 14:59
Proposal from @ikevin127 looks good to me https://github.com/Expensify/App/issues/33149#issuecomment-1857799980
🎀 👀 🎀 C+ reviewed

**Comment by ikevin127** [comment] 2023-12-18 13:11
@narefyev91 PR ready for review https://github.com/Expensify/App/pull/33225 🚀

**Comment by Christinadobrzyn** [comment] 2024-01-03 00:51
Payouts due:

Issue Reporter: NA
Contributor: NA- paid as external contributor through Callstack
Contributor+: $500 @ikevin127 (paid through Upwork)

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~01ae306e7095356be1).

@narefyev91 can you let us know about a regression test?

**Comment by narefyev91** [comment] 2024-01-03 08:23
- The PR that introduced the bug has been identified. Link to the PR - it was not a regression - just missing functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by Christinadobrzyn** [comment] 2024-01-03 17:02
sounds good! I think we can close this!

**Closed by Christinadobrzyn** 2024-01-03 17:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
