### ISSUE TITLE
Android Native: The bottom half of the camera doesn't work (i.e. shutter, flash and file upload buttons)

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#47911] opened 2024-08-23 12:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Android 9.0.24
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1724402419158759 

## Action Performed:
Break down in numbered steps

1. Click on "Submit expense"
2. Camera opens and "you need to give permissions" is shown
3. Click on "Continue" and notice nothing happens
4. Go to Android camera settings and give permissions to Expensify app
5. Permissions screen disappears
6. Click on shutter, flash and upload file buttons - nothing happens

## Expected Result:
Describe what you think should've happened

Shutter, flash and file upload buttons are responsive

## Actual Result:
Describe what actually happened

They are not

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment] 2024-08-23 12:17
Hanno from Margelo here, who build the used react-native-vision-camera library. Feel free to assign me 👋

**Comment by Julesssss** [comment] 2024-08-23 13:49
I can reproduce. Perhaps the bug is within the permission logic that occurs before the camera is launched.

**Comment by hannojg** [comment] 2024-08-23 13:50
Yes, thats likely. We are using a very outdated version of `rn-vision-camera` and I believe this has been fixed already. I am currently looking in upgrading rn-vision-camera!

**Comment by hannojg** [comment] 2024-08-23 13:50
what phone model + android version are you using @Julesssss ?

**Comment by Julesssss** [comment] 2024-08-23 13:52
Just edited my comment. Pixel 8a, Android 14

**Comment by hannojg** [comment] 2024-08-23 20:11
Regression was introduced in:

- https://github.com/Expensify/App/pull/47418
- 
looking into a fix within react-native-pager-view now…

**Comment by hannojg** [comment] 2024-08-23 20:12
(So its not a bug in react-native-vision-camera / an android 14 permission issue!)

**Comment by hannojg** [comment] 2024-08-23 20:52
The issue was already reported in the library here:

- https://github.com/callstack/react-native-pager-view/issues/836#issuecomment-2303983097

I found the same fix as the library maintainer. Will propose a patch PR until this is fixed in the library!

**Comment by cristipaval** [comment] 2024-08-26 15:20
FYI: We reverted the library upgrade in the meantime, to fix 3 blockers and unblock the deploy.

**Comment by jliexpensify** [comment] 2024-08-27 04:14
@cristipaval @hannojg @muttmuure @Julesssss the camera is working again!

**Comment by Julesssss** [comment] 2024-08-27 10:21
> Please assign me to the issue as I am C+ on the PR @Julesssss

Done

**Comment by muttmuure** [comment] 2024-08-27 10:40
> @cristipaval @hannojg @muttmuure @Julesssss the camera is working again!


Hooray!

**Closed** 2024-09-23 10:49 UTC
Labels: Reviewing, Monthly, Bug
