### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Status - Highlighting minutes and pressing Back key does not reset it to 00

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33143] opened 2023-12-15 09:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to Settings > Profile > Status.
3. Click Clear after.
4. Click Custom > Time.
5. Highlight the minutes.
6. Press Back key on keyboard.

## Expected Result:
The minutes will be reset to 00.

## Actual Result:
Nothing happens to the minutes and the cursor moves to the beginning of hours.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4c45a83f-c3d5-4641-902c-fb61962bb8b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5a5a8e401086431</li>
        <li>Upwork Job ID: 1735595606525665280</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28065612</li>
<li>paultsimura | Contributor | 28065613</li>
</ul></li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-12-15 09:48
Removing blocker status, you can still change it with the delete key using the caret: 

![Screenshot 2023-12-15 at 09 47 04](https://github.com/Expensify/App/assets/10736861/11c0bcf0-8502-4a1e-b9b1-f3a22de1a65e)
![Screenshot 2023-12-15 at 09 47 10](https://github.com/Expensify/App/assets/10736861/cabe242f-e94a-4c09-80b0-0d91bec32989)

**Comment by paultsimura** [comment] 2023-12-15 09:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
This happens because of the function we are calling on the `onKeyPress` of the minutes input:

https://github.com/Expensify/App/blob/541ee3568ba8034b85df295f8546a5d45f35f137/src/components/TimePicker/TimePicker.js#L323C15-L332

We only set the focus to the hours input.

### What changes do you think we should make in order to solve the problem?
We should perform the value replacement in `onKeyPress` similar to what we do when handling the custom number pad:

https://github.com/Expensify/App/blob/541ee3568ba8034b85df295f8546a5d45f35f137/src/components/TimePicker/TimePicker.js#L252-L289

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-12-16 01:25
@bernhardoj Thanks for the proposal. Your solution makes sense but it does not cover the minute case. Can you please update your proposal to cover it? Also we need to make it work with the backbutton in the software keyboard too


https://github.com/Expensify/App/assets/16493223/74c47a17-53cf-45f3-9bd1-667989a15584

**Comment by s77rt** [comment] 2023-12-16 01:28
@paultsimura Thanks for the proposal. The approach looks good to me. Is there any reason we need to adjust the regex instead of just checking if the text is empty beforehand? Also same note above regarding the soft num pad backbutton

**Comment by s77rt** [comment] 2023-12-16 01:35
@dukenv0307 Thanks for the proposal. I don't think we should clear the input on the key press event. Handling this on `handleHourChange` / `handleMinutesChange` is more fitting.

**Comment by paultsimura** [comment] 2023-12-16 04:34
> Is there any reason we need to adjust the regex instead of just checking if the text is empty beforehand? 

No, it's basically doing the same thing, I just thought updating regex would look shorter and cleaner.

Regarding the num pad - right, we'll need to handle it in a somewhat similar way. Would you like me to update the proposal with more tech details?

**Comment by s77rt** [comment] 2023-12-16 10:11
@dukenv0307 Currently yes it's but when we need to control a component we usually use the on value change callback since it's more generic. For example if you select the minutes then right click -> Cut. Only the `handleMinutesChange` callback will fire.


https://github.com/Expensify/App/assets/16493223/d189dc6e-e156-4036-94ad-7cbf6be90ef1

**Comment by s77rt** [comment] 2023-12-16 10:23
@paultsimura 

> otherwise replacing the minutes by selection wouldn't work

That's a good a point but based on the comments this is not allowed on purpose due to the lack of paste validation on minutes and the weird behavior on hours.


https://github.com/Expensify/App/assets/16493223/fbe58e90-35cb-4327-b076-28e626fe0a96

**Comment by paultsimura** [comment] 2023-12-16 10:29
Actually @s77rt now that I started testing the time picker more extensively, I see there is a lot of bugs and unexpected behaviors with it. I think the easiest way will be to create a test branch with all the changes.

Looks like there was not enough effort put into working with selections. 

If you give me time by Monday, I think I will come up with more robust solution and we won't need to disable copy/paste functionality.

**Comment by pecanoro** [comment] 2023-12-18 13:41
Not overdue, discussing possible solutions

**Comment by paultsimura** [comment] 2023-12-18 14:05
## Proposal

Updated proposal https://github.com/Expensify/App/issues/33143#issuecomment-1857590669

Also added a link to the branch for more convenient testing.

**Comment by s77rt** [comment] 2023-12-18 20:16
@paultsimura Can you please have the complete solution on the refactor on the proposal itself and not in a branch. Code diffs, branches, PRs are discouraged. Also let's keep the `isOnlyNumericValue` regex untouched, for the empty string case there should be an early return to handle it.

**Comment by paultsimura** [comment] 2023-12-19 08:07
## Proposal

Updated proposal https://github.com/Expensify/App/issues/33143#issuecomment-1857590669

**Comment by s77rt** [comment] 2023-12-19 16:12
@paultsimura Thanks! That looks good to me but this does not cover the replace by selection case?

**Comment by paultsimura** [comment] 2023-12-19 16:14
@s77rt no, it's not in the scope of this issue, so I removed the replace-by-selection logic from my latest proposal. Should I bring it back?

**Comment by paultsimura** [comment] 2023-12-19 18:50
@s77rt since you've said the proposal looks good for solving the issue, and the `replace by selection` is a nice-to-have addition, why won't we move this discussion further into the PR?

My proposal is already big and looks almost like a PR, and considering Engineers' comments, it's not the best approach to place full production-ready code into a proposal:

> There is too much code and that's why we request that code doesn't get put into proposals.

https://github.com/Expensify/App/issues/32912#issuecomment-1854832712

**Comment by s77rt** [comment] 2023-12-19 18:52
@paultsimura Sounds good to me!

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/33143#issuecomment-1857590669)

**Comment by pecanoro** [comment] 2023-12-19 20:38
Assigning @paultsimura!

**Comment by paultsimura** [comment] 2023-12-20 20:06
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/33344

**Comment by paultsimura** [comment] 2024-01-03 13:00
@pecanoro while working on this issue, we've decided to fix not only this one but a couple of other bugs related to the TimePicker (it was quite buggy actually). This led to spending a solid week of day-to-day development and testing from both the C and C+ sides.

I've seen that in such cases, contributors negotiate for a larger bounty since otherwise these bugs would have been fixed as separate issues later. I'll leave the bounty decision up to you, but could we please make this PR free from potential regression penalties? As it did cover a lot of logic changes to fix different cases, but we might have missed some edge cases.

For instance, here are 4 other fixed bugs that were out of scope here:

<details><summary>Unexpected re-conversion of 24h to 12h format when entering the first digit</summary>
<p>

https://github.com/Expensify/App/assets/12595293/ab465312-3f8f-4da0-90fb-a6bfc6775e8d

</p>
</details> 

<details><summary>Jumping cursor when moving from hours to minutes</summary>
<p>

https://github.com/Expensify/App/assets/12595293/15fcdd20-4ef2-459b-941f-f750ce385673

</p>
</details> 

<details><summary>Buggy behavior when removing digits using the "Delete" button</summary>
<p>

https://github.com/Expensify/App/assets/12595293/70f9a330-7541-4316-ab5b-8a4dda0a8f7c

</p>
</details> 

<details><summary>Buggy behavior when pressing "Space"</summary>
<p>

https://github.com/Expensify/App/assets/12595293/58c985ee-2b80-49da-8c95-1d7dc5e6ec94

</p>
</details>

**Comment by s77rt** [comment] 2024-01-07 11:00
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/24620
- The offending PR has been commented on: https://github.com/Expensify/App/pull/24620#discussion_r1443983091
- A discussion in #expensify-bugs has been started: I don't think this is needed
- Determine if we should create a regression test for this bug: The work done here is mostly adding missing features and fixing bugs for a component that is newly written. I don't think we require a regression test in this case

**Comment by lschurr** [comment] 2024-01-11 17:08
Hmm @bfitzexpensify is already on this one. Are you able to handle, Benny?

**Comment by bfitzexpensify** [comment] 2024-01-11 18:38
Payments complete, agreed we don't need a regression test here. Closing this one out.

**Closed by bfitzexpensify** 2024-01-11 18:38 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
