### ISSUE TITLE
[$500] Mac/Safari - Login - App crashed when login to App

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33551] opened 2023-12-23 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33238
## Action Performed:
Precondition: Safari version: 15.5
1. Navigate to ND https://staging.new.expensify.com/
2. Login with account

## Expected Result:
User should be login

## Actual Result:
App crashed. "Uh-oh, something went wrong!. If the problem persists, reach out to [concierge@expensify.com"](mailto:concierge@expensify.com%22)
and two buttons are present refresh and Sign out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1011" alt="Bug6325011_1703349983877!crash" src="https://github.com/Expensify/App/assets/78819774/61c36408-8b02-4458-b332-8a01c1fe8620">

https://github.com/Expensify/App/assets/78819774/6b6bc49e-f12f-4a6b-aa90-27185935b2f8

[logs 2.txt](https://github.com/Expensify/App/files/13759714/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0a43e9aa7cd2f5f</li>
        <li>Upwork Job ID: 1738606471051292672</li>
        <li>Last Price Increase: 2023-12-30</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-12-25 03:53
> Looks like #33238 hasn't deployed to staging yet.

This issue is unrelated to the mentioned PR

**Comment by rojiphil** [comment] 2023-12-25 03:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On a fresh signing with a new account, an unintended report is attempted to be displayed in central pane. This is the problem we are trying to solve. 

### What is the root cause of that problem?

When we load the App for the very first time using a new account (i.e. this account was not used for signin before), the `openApp` will also return `Domain Room` as shown in attached image below. Since the App is loaded for the first time, there will be no `reportID` specified in `routes` param due to which `findLastAccessedReport` will be used [here](https://github.com/Expensify/App/blob/7b836cfcee79084177191e3dfb4a927698b09eb4/src/libs/ReportUtils.ts#L822C1-L862C2) to determine the last accessed report id via `ReportScreenIDSetter`. Here, `isFirstTimeNewExpensifyUser` will be true as this is a first time new user and `ignoreDomainRooms` would be true as we want to ignore domain rooms. Since we ignore the domain rooms only after the check for `isFirstTimeNewExpensifyUser`, the domain room report id is returned as the last accessed id thereby resulting in the display of domain room in central pane. This is the root cause of the problem. 

![Screenshot 2023-12-25 at 8 54 30 AM](https://github.com/Expensify/App/assets/3004659/25c63dc2-dd2a-47f3-a988-c389a64af7fc)


### What changes do you think we should make in order to solve the problem?

To solve the problem, we should, first, filter out the domain rooms before deciding on the last accessed report id for the first time Expensify user [here](https://github.com/Expensify/App/blob/7b836cfcee79084177191e3dfb4a927698b09eb4/src/libs/ReportUtils.ts#L844C1-L859C6) like this:

    if (ignoreDomainRooms) {
        // We allow public announce rooms, admins, and announce rooms through since we bypass the default rooms beta for them.
        // Check where ReportUtils.findLastAccessedReport is called in MainDrawerNavigator.js for more context.
        // Domain rooms are now the only type of default room that are on the defaultRooms beta.
        sortedReports = sortedReports.filter(
            (report) => !isDomainRoom(report) || getPolicyType(report, policies) === CONST.POLICY.TYPE.FREE || hasExpensifyGuidesEmails(report?.participantAccountIDs ?? []),
        );
    }

    if (isFirstTimeNewExpensifyUser) {
        if (sortedReports.length === 1) {
            return sortedReports[0];
        }

        return adminReport ?? sortedReports.find((report) => !isConciergeChatReport(report)) ?? null;
    }


### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-12-25 04:01
@rojiphil should these conditions meet to reproduce this issue?
- old macOS
- new account

**Comment by rojiphil** [comment] 2023-12-25 04:39
> @rojiphil should these conditions meet to reproduce this issue?
> 
> * old macOS
> * new account

While `new account` is required here, I am unsure of the macOS/Safari criteria. I used macOS Ventura 13.2.1/v16.3 Safari.

**Comment by situchan** [comment] 2023-12-25 04:43
I am not able to reproduce on both old (16.0) and new (17.0) safari. Tested with new account

**Comment by rojiphil** [comment] 2023-12-25 04:45
> I am not able to reproduce on both old (16.0) and new (17.0) safari. Tested with new account

hmm.. That's interesting. Let me have a look again.

**Comment by rojiphil** [comment] 2023-12-25 04:48
@situchan 
Can you please check if you get two reports as a response from `openApp` as mentioned in my [proposal](https://github.com/Expensify/App/issues/33551#issuecomment-1868708931)?

**Comment by rojiphil** [comment] 2023-12-25 04:52
Maybe this has to do with `domain` since we are dealing with a domain room. 
My test accounts have a custom domain.

**Comment by getusha** [comment] 2023-12-27 12:19
I am also not able to reproduce this, we can close it.

**Comment by getusha** [comment] 2023-12-29 10:32
> Did you happen to try a test account with a custom domain?

@rojiphil could you please explain what a custom domain is?

**Comment by rojiphil** [comment] 2023-12-29 10:45
> could you please explain what a custom domain is?

@getusha 
Let's take a test account (say user@mydomain.com). 
Here, `mydomain.com` is what I referred to as the custom domain.

**Comment by anmurali** [comment] 2024-01-02 23:08
It's slow to load but I can login. Closing this issue.

**Closed by anmurali** 2024-01-02 23:08 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by rojiphil** [comment] 2024-01-03 09:10
> It's slow to load but I can login. Closing this issue.

@anmurali 

I can still reproduce the issue. Here is an attached video for the same.

Since you would have an account with `expensify.com` domain, can you please try creating a `new` test account with `expensify.com` domain on `staging.new.expensify.com`?
I think this will reproduce the problem here.

https://github.com/Expensify/App/assets/3004659/2311218f-6596-4ab9-8db9-dc25732effc5
