### ISSUE TITLE
Android/IOS - Chat - Cursor goes up while trying to scroll down @gadhiyamanan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11284] opened 2022-09-26 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2.  Go to any chat
3.  Send a long message 
4.  Try to  edit long message
5. Scroll to end of message and try to scroll to up

## Expected Result:
 Cursor should not goes up

## Actual Result:
Cursor goes up

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192285192-9ed668de-8469-429a-9f6c-4c8d2b9eb275.mp4

https://user-images.githubusercontent.com/93399543/192285207-4fb2976e-657d-40e5-a422-0005f0c9f1d3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662398571329099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment] 2022-09-26 18:33
Hmm, I'm not really seeing what the issue is here, the scrolling in the videos seems normal. The cursor is going up because that is the location that is being tapped on the screen, so the cursor is moving.

**Comment by sophiepintoraetz** [comment] 2022-09-27 09:18
@kbecciv - can you confirm whether that this is the case?
>The cursor is going up because that is the location that is being tapped on the screen, so the cursor is moving.

Otherwise, I agree with Alex that this is probably a non-issue.

**Comment by sophiepintoraetz** [comment] 2022-09-28 08:09
All right - in the interest of focus, I'm going to close this one out. @kbecciv - feel free to reopen this if you feel otherwise/have more context to add.

**Closed by sophiepintoraetz** 2022-09-28 08:09 UTC
Labels: Engineering, Weekly, Improvement
