### ISSUE TITLE
[$250] Deeplink - Infinite loading displayed when clicked on open in app button

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43472] opened 2024-06-11 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4611168&group_by=cases:section_id&group_id=229043&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+omq320@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Sign in with account A in desktop app and account B in web
2. Open staging.new.expensify.com in web
3. Reload the page
4. Click on "Allow" button on "Do you want to allow this website to open “New Expensify”?" pop-up

## Expected Result:
User should be redirected to desktop app and signed in with account B

## Actual Result:
Infinite loading displayed when user redirected to the desktop app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/48a4e015-969a-4bf1-b6d9-98967bca00e9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01860b2f894cfe747a</li>
        <li>Upwork Job ID: 1801462488954291750</li>
        <li>Last Price Increase: 2024-07-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by stephanieelliott** [comment] 2024-06-18 06:54
Waiting for some proposals

**Comment by stephanieelliott** [comment] 2024-06-20 22:06
Still waiting for  proposals

**Comment by skyweb331** [comment] 2024-06-23 17:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Enable to auto login with User B on Mac Desktop from web, even though User A is already logged in Mac Desktop
### What is the root cause of that problem?
`<LogInWithShortLivedAuthTokenPage>` is in `<PublicScreen>` route, and authenticated user can not access to `<PublicScreen>` from below...
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/Navigation/AppNavigator/index.tsx#L27-L40

so Login URL for User B from web is not accessible on Desktop as User A is already logged in there.

### What changes do you think we should make in order to solve the problem?
`<LogInWithShortLivedAuthTokenPage/> ( route: SCREENS.TRANSITION_BETWEEN_APPS )` should be accessible regardless of authentication status.

So I can Add below route to `<AuthScreen/>` route too ( This is already defined in `<PublicScreen/>`)
```javascript
<RootStack.Screen
    name={SCREENS.TRANSITION_BETWEEN_APPS}
    options={defaultScreenOptions}
    component={LogInWithShortLivedAuthTokenPage}
/>
```


### What alternative solutions did you explore? (Optional)
There could be some more routes which should be accessible regardless of authentication status in the future, so we have to make a place where these routes could be defined. 

And I think, here is the best place where we can define a route like `<ScreenForBoth/>`
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/Navigation/AppNavigator/index.tsx#L27-L40

But `<AuthScreen/>` and `<PublicScreen/>` returns `<RootStack.Navigator/>` so it requires some route structure changes...
I can provide detailed plan if this optional solution is really required.

**Comment by stephanieelliott** [comment] 2024-06-25 00:07
Hey @rojiphil can you review the above proposal when you get a sec?

**Comment by rojiphil** [comment] 2024-06-25 18:05
Reviewing today

**Comment by rojiphil** [comment] 2024-06-26 08:05
@skyweb331 There is already an existing route for `TRANSITION_BETWEEN_APPS` in `AuthScreens` [here](https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L346C1-L350C23) to `loadLogOutPreviousUserPage`. 
How would adding another route for `TRANSITION_BETWEEN_APPS`  to `LogInWithShortLivedAuthTokenPage` help here?

**Comment by skyweb331** [comment] 2024-06-26 17:26
Sorry, I just checked it on staging web with electron on my desktop and I can not reproduce this bug...

**Comment by mvtglobally** [comment] 2024-07-03 14:35
Issue not reproducible during KI retests. (First week)

**Comment by rojiphil** [comment] 2024-07-04 12:13
@stephanieelliott Can we close this since this is not reproducible?

**Comment by stephanieelliott** [comment] 2024-07-09 23:44
Yeah let's close!

**Closed by stephanieelliott** 2024-07-09 23:44 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
