### ISSUE TITLE
[$1000] Web - Workspace name not updated for UserB, requires page refresh if UserA changes their workspace name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22136] opened 2023-07-03 19:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with userA account
2. Go to the “New room” section
3. Enter room name and select userA workspace
4. Select visibility to “Public”
5. Click on “Create room”
6. Go to the room detail
7. Share code > Copy URL to clipboard
8. Open other browser and login with userB account
9. Join the room by pasting URL
10. Go to the room detail from userB account
11. Now change the workspace name from userA account

## Expected Result:
When UserA changes their workspace name, the workspace name should update automatically for UserB without requiring a page refresh

## Actual Result:
The workspace name is not updated for UserB when UserA changes their workspace name. UserB needs to refresh the page in order to see the updated workspace name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6ffd4bf2-84f1-4de8-a9ac-5ba9b9196330

https://github.com/Expensify/App/assets/93399543/8b289707-f0dd-4fac-8485-38d353800a04

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687855345510949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bec5fa73cfccfb2e</li>
        <li>Upwork Job ID: 1678894921046982656</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-07-11 22:31
I couldn't reproduce this after my initial attempt, but I see that @kbecciv was able to (and the bug reporter was). I'm going to pass this onward to see if contributors agree & can reproduce (if not, then we'll close the GH for now).

**Comment by jsskrh** [comment] 2023-07-12 02:49
A possible solution to this issue is making use of web sockets. This was the room name is not solely dependent on data sent from the server hence needing to refresh. Rather when the workspace name is changed by userA, an event is emitted and sent through the server side app to userB who’s listening for this event, thus updating the workplace name in real time.

**Comment by washedrepent** [comment] 2023-07-12 02:53
> A possible solution to this issue is making use of web sockets. This was the room name is not solely dependent on data sent from the server hence needing to refresh. Rather when the workspace name is changed by userA, an event is emitted and sent through the server side app to userB who’s listening for this event, thus updating the workplace name in real time.

Exactly. Need to make use of websockets or use polling to fetch the latest information.

**Comment by washedrepent** [comment] 2023-07-12 02:56
Contributor details
Your Expensify account email: hans_eric_lippke@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0123bc19abb81e951e

**Comment by jsskrh** [comment] 2023-07-12 03:01
> A possible solution to this issue is making use of web sockets. This was the room name is not solely dependent on data sent from the server hence needing to refresh. Rather when the workspace name is changed by userA, an event is emitted and sent through the server side app to userB who’s listening for this event, thus updating the workplace name in real time.

Contributor details
Your Expensify account email: jesseakorah@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~01dabc783fd94fce6c)

**Comment by ayazhussain79** [comment] 2023-07-16 17:42
@0xmiroslav but not for userB

**Comment by michaelhaxhiu** [comment] 2023-07-18 21:15
Thanks for the further investigation @0xmiroslav! Going  `Internal` and assigning `Engineering`

**Comment by michaelhaxhiu** [comment] 2023-07-18 21:18
settle down melvie

**Comment by aldo-expensify** [comment] 2023-07-24 23:13
So.. looking at the backend, I'm pretty sure that @0xmiroslav is correct and we are just not pushing the changes to users from public rooms that are not members of the policy.

It is not hard to fix, but I'm bit concerned about what if the policy is the room has lots of accounts.. we may end up with a timeout.

**Comment by aldo-expensify** [comment] 2023-07-25 23:26
PRs up:

- https://github.com/Expensify/Auth/pull/8358
- https://github.com/Expensify/Web-Expensify/pull/38309

**Comment by aldo-expensify** [comment] 2023-07-27 19:08
Web-E PR merged

**Comment by michaelhaxhiu** [comment] 2023-08-04 15:02
Note: I'm preparing to go OOO for ~2 weeks and going to assign another BZ to oversee this please 🙏 

Next steps:
- Await this to reach completion, which Aldo will let us know!
- Process the due payments to the bug reporter & C+ only (since this is internal). This will be $250 for @ayazhussain79 and $1000 for @0xmiroslav 

Thanks in advance @maddylewis

**Comment by aldo-expensify** [comment] 2023-08-04 16:50
The last  PR https://github.com/Expensify/Web-Expensify/pull/38309 hit production already, we should check if this is fixed now

**Comment by maddylewis** [comment] 2023-08-06 18:11
im OOO until August 20 - https://github.com/Expensify/App/issues/22136#issuecomment-1665753300

**Comment by joekaufmanexpensify** [comment] 2023-08-07 18:56
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-08-07 18:58
@0xmiroslav I was looking into this, and there was some miscommunication with my [colleague's comment here](https://github.com/Expensify/App/issues/22136#issuecomment-1665753300) about payment. Since both of the PRs here were internal/backend, with out C+ review, there wouldn't be a C+ payment here. 

Thinking this is what you prob expected, but LMK if you have any questions about this!

**Comment by joekaufmanexpensify** [comment] 2023-08-07 19:37
This means all we need to do is issue the $250 reporting payment for this issue to @ayazhussain79

**Comment by joekaufmanexpensify** [comment] 2023-08-07 19:38
@ayazhussain79 offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2023-08-08 13:28
>Correct. No review payment required here.
It's optional that I might be eligible for partial comp for the research work which led to fixing backend.

Got it, ty! When we discussed this internally, we landed on $0 for C+ here, so I'm thinking it makes sense to stick with that. Happy to discuss further if you disagree though! Either way, we appreciate you determining that this should be fixed internally.

**Comment by joekaufmanexpensify** [comment] 2023-08-08 13:29
Correct. No review payment required here.
It's optional that I might be eligible for partial comp for the research work which led to fixing backend.

@0xmiroslav Got it, ty! When we discussed this internally, we landed on $0 for C+ here, so I'm thinking it makes sense to stick with that. Happy to discuss further if you disagree though! Either way, we appreciate you determining that this should be fixed internally.

**Comment by joekaufmanexpensify** [comment] 2023-08-08 13:30
@ayazhussain79 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-08 13:30
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-08-08 13:31
Closing for now, as this one is all set. Let me know if anyone has any other thoughts/questions on this though!

**Closed by joekaufmanexpensify** 2023-08-08 13:31 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
