### ISSUE TITLE
[Bug] [$250] Android - Invite members - Invite message text box disappears when select emoji picker

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10609] opened 2022-08-26 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test app
2. Log in to applause.expensifail account
3. Navigate to the Workspace editor page
4. Navigate to Manage Members
5. Tap the Invite button
6. Select the Invite message text box
7. Select emoji picker

## Expected Result:
Invite message text box is still visible when selecting the emoji picker

## Actual Result:
Invite message text box disappears when selecting the emoji picker

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.92.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186990035-71f24d8d-cd76-41c0-b1e5-0b072a914d5f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kakajann** [comment] 2022-08-27 04:30
# Proposal
This is the `KeyboardAvoidingView` bug when you set its behavior to `height`.

### Solution
We have to make this behavior `undefined` when we use this component in `WorkspaceInvitePage` on Android.
https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/components/ScreenWrapper/BaseScreenWrapper.js#L80

We can't simply add the prop (`keyboardAvoidingViewBehavior={undefined}`) to this component:
https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/pages/workspace/WorkspaceInvitePage.js#L231
because `undefined` will be treated as `height` due to this line:
https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/components/ScreenWrapper/index.android.js#L14

So, how to fix?
1. Add `default` to `keyboardAvoidingViewBehavior` in `ScreenWrapper` prop types
```diff
-    keyboardAvoidingViewBehavior: PropTypes.oneOf(['padding', 'height', 'position']),
+    keyboardAvoidingViewBehavior: PropTypes.oneOf(['default', 'padding', 'height', 'position']),
```

2. Modify `ScreenWrapper` android code
```jsx
import React, {useMemo} from 'react';
import BaseScreenWrapper from './BaseScreenWrapper';
import {defaultProps, propTypes} from './propTypes';

const ScreenWrapper = (props) => {
    const keyboardAvoidingViewBehavior = useMemo(() => {
        if (props.keyboardAvoidingViewBehavior === 'default') {
            return undefined;
        }

        if (props.keyboardAvoidingViewBehavior !== undefined) {
            return props.keyboardAvoidingViewBehavior;
        }

        return 'height';
    }, [props.keyboardAvoidingViewBehavior]);

    return (
        <BaseScreenWrapper
            // eslint-disable-next-line react/jsx-props-no-spreading
            {...props}
            keyboardAvoidingViewBehavior={keyboardAvoidingViewBehavior}
        >
            {props.children}
        </BaseScreenWrapper>
    );
};

defaultProps.keyboardAvoidingViewBehavior = undefined;

ScreenWrapper.propTypes = propTypes;
ScreenWrapper.defaultProps = defaultProps;

export default ScreenWrapper;
```

3. Create a cross-platform `WorkspaceInvitePageWrapper` component (index.js and index.android.js) and return
```js
<ScreenWrapper keyboardAvoidingViewBehavior="default">
{children}
</ScreenWrapper>
```
on android. Otherwise `ScreenWrapper` component without any prop.

# Result

https://user-images.githubusercontent.com/11542415/187014352-26ff1cfa-cdfa-49b6-bbfb-743e6abd67d8.mov

**Comment by adelekennedy** [comment] 2022-08-29 20:05
[internal](https://www.upwork.com/ab/applicants/1564343339340345344/job-details)
[external](https://www.upwork.com/jobs/~011679614d337a9357)

**Comment by roryabraham** [comment] 2022-08-30 11:22
Putting this on HOLD on https://github.com/Expensify/App/issues/10273

**Comment by mvtglobally** [comment] 2022-09-20 05:07
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2022-10-03 17:42
this is on hold

**Comment by tgolen** [comment] 2022-10-13 17:06
I removed the HOLD on this and assigned it to me because this is fixed in https://github.com/Expensify/App/pull/11586

**Comment by adelekennedy** [comment] 2022-10-13 17:10
I don't think any payment is due, this was reported by applause and no proposals were accepted

**Comment by mvtglobally** [comment] 2022-10-18 11:16
Issue not reproducible during KI retests. (Second week)

**Comment by parasharrajat** [comment] 2022-10-18 13:03
let's remove the help wanted and External labels.

**Comment by roryabraham** [comment] 2022-10-21 00:13
Removed `Help Wanted` for now

**Comment by mvtglobally** [comment] 2022-10-24 18:28
Issue not reproducible during KI retests. (Third week) @roryabraham  Are we ok to close this?

**Comment by tgolen** [comment] 2022-10-25 14:59
Wow, it's so weird that a lot of these are disappearing, even without my fix deployed. It's fine to close this.

**Closed by tgolen** 2022-10-25 14:59 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
