### ISSUE TITLE
[$1000]  Contact methods does not  sort alphabetically without a reload

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22220] opened 2023-07-04 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User should already have 1 non default contact added and verified
1. Open the app
2. Open settings
3. Open profile
4. Open contact method
5. Add new contact method, contact method should be alphabetically first then other non default contact method
6. Verify the contact method and observe that app does not arrange them alphabetically, go back and revisit and see that it is still not arranged
7. Reload the app and now observe that contact methods are arranged alphabetically
## Expected Result: 
App should arrange non default contact methods alphabetically once they are verified
## Actual Result: 
App needs reload to arrange non default contact methods alpabetically
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** I get error when adding 3rd email and could not test
**Reproducible in production?:** I get error when adding 3rd email
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/30c0551d-e7d4-414d-8a8e-7415db9380d7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688389272795789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01390ca96e2ca8fedc</li>
        <li>Upwork Job ID: 1676426981334614016</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-07-04 20:26
# Proposal

## Please re-state the problem
Contact methods are only sorted on page reload.

## What is the root cause of that problem?
The root cause is that while sorting the methods in this line here:
https://github.com/Expensify/App/blob/a05baabef9bef986671e74da500c1c07f27834cd/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L66

We only sort for having the default contact method on top and not sorting the rest alphabetically. But when reloaded, the server does store them alphabetically and we see the difference.

## What changes do you think we should make to solve this problem?
We should add a condition the `_.sortBy` to also sort these methods alphabetically. Which can be done with the following code:
```
const sortedLoginNames = _.sortBy(loginNames, (loginName) => ([props.loginList[loginName].partnerUserID === props.session.email ? 0 : 1, loginName]));
```
Explaination of code: Instead of returning either just `0` or `1`, we can return an array with the first condition resolving to `0` or `1` and then the second condition being just the name, which will automatically be arranged alphabetically by the `_.sortBy` method.

## What other approach did you explore?
None

**Comment by kadiealexander** [comment] 2023-07-05 03:04
Repro:

https://github.com/Expensify/App/assets/59587260/ca036ba6-3e0a-45fe-8033-2adecaf507a2

**Comment by Pujan92** [comment] 2023-07-05 15:56
I think it is fine as per this comment https://github.com/Expensify/App/issues/17883#issuecomment-1523209490

**Comment by Komal1124** [comment] 2023-07-05 19:08
Contributor details
Expensify account email: komalchatiwal327@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019a55984d84c859ef

**Comment by eVoloshchak** [comment] 2023-07-06 16:12
> I think it is fine as per this comment https://github.com/Expensify/App/issues/17883#issuecomment-1523209490

Agree with @Pujan92, this can be closed

> I’m in the camp that we should do nothing. This seems like quite the theoretical case. Most accounts have one additional login besides their main one – which they use for receipt forwarding and in the case that they leave the company employing them.
Ok great we'll :donothing: for sorting EXCEPT we will display the default contact method on top

**Comment by esh-g** [comment] 2023-07-06 16:16
Just adding another note, that they are being sorted on reloading the page and the inconsistency may also be a factor...

**Comment by shubham1206agra** [comment] 2023-07-06 16:38
> Just adding another note, that they are being sorted on reloading the page and the inconsistency may also be a factor...

@esh-g Its due to storage in backend order, and we have used stable sorting in `_.sortBy`

**Comment by kadiealexander** [comment] 2023-07-07 02:57
Closing as per this comment https://github.com/Expensify/App/issues/17883#issuecomment-1523209490, thanks @Pujan92!

**Closed by kadiealexander** 2023-07-07 02:57 UTC
Labels: External, Daily, Help Wanted, Bug
