### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Task - Pointer shows up for an archived task when hovering over the edge of the checkbox

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37236] opened 2024-02-26 22:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing Pr** https://github.com/Expensify/App/pull/31674
## Action Performed:
1. Open ND and log in with any account
2. Go to announce room
3. Create a task
4. Delete the workspace in whose announce room the task is just created
5. Note that the task report was archived in LHN
6. Tap task in the archived announce room
7. Hover over the edge of the checkbox carefully

## Expected Result:
No pointer should show up since the task is archived and can not be checked

## Actual Result:
A pointer shows up when hovering over the edge of the checkbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5152902f-05bd-4f45-bc06-e0d186e277e0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115fb6326c37966b2</li>
        <li>Upwork Job ID: 1762247262944112640</li>
        <li>Last Price Increase: 2024-02-26</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>brandonhenry | Contributor | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-02-26 22:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task - Pointer shows up for an archived task when hovering over the edge of the checkbox

### What is the root cause of that problem?

The `canModifyTask` function checks if the workspace or parent report is archived.

https://github.com/Expensify/App/blob/297bcec1b2013c22a71c1065ed8d3ddf337862fd/src/libs/actions/Task.ts#L884-L887

### What changes do you think we should make in order to solve the problem?


Instead of checking for the parent report is archived, we can remove this condition `ReportUtils.isArchivedRoom(parentReport)`.

**Comment by jasperhuangg** [comment] 2024-02-27 00:49
Definitely do not need to be blocking deploy on something so minor

**Comment by jasperhuangg** [comment] 2024-02-27 03:15
Great explanation @brandonhenry let's move forward with your proposal!

Also, once you've submitted your PR, please complete the checklist and be sure to include a regression test to ensure that this bug doesn't crop up again, thanks!

**Comment by jasperhuangg** [comment] 2024-02-27 03:19
@Krishna2323 my mistake, I didn't realize that the proposal was a duplicate. In fairness, I will assign you, thanks for making me aware.

**Comment by trjExpensify** [comment] 2024-03-07 11:45
Deployed to staging 13 hours ago, Melv.

**Comment by trjExpensify** [comment] 2024-03-14 19:22
👋 @ntdiary checklist time! :)

**Comment by trjExpensify** [comment] 2024-03-15 19:21
Haha, that it does! 🕐 Cool, I've asked Matt for an update on that quickly. If not, I can pay you via Upwork.

In the meantime.. I don't think it's worth having a regression test for this pointer cursor. 👍 Payment summary as follows:

$500 to @ntdiary for the C+ review
$500 to @Krishna2323 for the fix

**Comment by trjExpensify** [comment] 2024-03-18 11:35
Yep, we're proceeding with Upwork for now. 

@Krishna2323 - paid
@ntdiary - waiting for you to accept the offer. :)

**Comment by trjExpensify** [comment] 2024-03-18 13:00
Perfect, paid. Closing! 👍

**Closed by trjExpensify** 2024-03-18 13:00 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
