### ISSUE TITLE
[$250] IOU - Category briefly reselects itself when removed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44649] opened 2024-06-28 20:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. FAB > Submit Expense
2. Add amount and choose workspace
3. Add category and merchant
4. Go to IOU > Category > click to remove

## Expected Result:
The category should not briefly reselect itself

## Actual Result:
The category briefly reselects itself when clicked to remove

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0e3ec17d-521c-4b0c-8911-cad120ef2785

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c03aa025a5c5f612</li>
        <li>Upwork Job ID: 1807555103945888117</li>
        <li>Last Price Increase: 2024-07-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment] 2024-06-28 20:05
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment] 2024-06-30 23:20
Yep, I can reproduce this one - after selecting and deselecting multiple times (e.g. 2 times) the Category reappears briefly again.

**Comment by pankajsoftyoi** [comment] 2024-07-01 11:24
##  Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category briefly reselects itself when removed

### What is the root cause of that problem?
There isn't any condition in place which prevents getting reselected itself in ` onSelectRow(item); `.
https://github.com/Expensify/App/blob/57622ffe1eb5e8396a0e60d8b9b06f9451985589/src/components/SelectionList/BaseListItem.tsx#L79-L82

### What changes do you think we should make in order to solve the problem?
Need to set the following condition for already selected item. With this change it will prevent to reselect itself.
```
 if (!canSelectMultiple && !item.isSelected && !rightHandSideComponent) {
      onSelectRow(item);
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jliexpensify** [comment] 2024-07-03 09:37
Bump @fedirjh for a review!

**Comment by wlegolas** [comment] 2024-07-08 00:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - Category briefly reselects itself when removed

### What is the root cause of that problem?

When the user selects and deselects multiple times (e.g. 2 times) the Category reappears briefly again because the previous request finished successfully and updates the Onyx state with a new `transaction` that has the category information before the request to update the `transaction` with deselected category has not yet been completed.

For example:

1. The user clicks on the "**Category**" label to open the modal to select the Category.
2. The user selects the category "**Advertising**"
3. App closes the modal
4. The request `UpdateMoneyRequestCategory` is started to update the transaction with the selected category "**Advertising**".
5. The user clicks on the "**Category**" label to open the modal to deselect the Category.
6. User deselects the category "**Advertising**"
7. App closes the modal
8. The request `UpdateMoneyRequestCategory` is started to update the transaction with **an empty string** in the category property.
9. The user clicks on the "**Category**" label to open the modal
10. The request started at step 4 finished and updates the Onyx state with a new transaction with the category "**Advertising**"
11. User sees the "**Advertising**" as selected category
12. The request started at step 8 finished and updates the Onyx state with a new transaction with the category with an empty string

The issue is caused because when the user deselects the Category (`CategoryPiker` component) and opens the modal again (`MoneyRequestView` component) the previous request (to select the Category "**Advertising**") finished and updates the state with a new transaction with the category "**Advertising**" and the user can see the "**Advertising**" category as selected and after a while the last request finishes and updates the state with an empty category.

In the following video, you can see the steps above, in the Network tab you can see when each request finishes.

https://github.com/Expensify/App/assets/698363/8f83baf0-0196-4589-8e5b-f87f0b0068da

### What changes do you think we should make in order to solve the problem?

We should change the `IOURequestStepCategory` component to show the loading message meanwhile the request to update the category is not completed yet. With this solution when the user opens the modal they will see a loading indicator and when the last request finishes the user will be able to proceed.

The loading indicator here https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepCategory.tsx#L113 should be changed to use the `isLoadingReportData` information from Onyx state to show the loading indicator if the `isLoadingReportData` property is `true`. For example:

```
function IOURequestStepCategory({
    report: reportReal,
    reportDraft,
    route: {
        params: {transactionID, backTo, action, iouType, reportActionID},
    },
    transaction,
    splitDraftTransaction,
    policy: policyReal,
    policyDraft,
    policyTags,
    policyCategories: policyCategoriesReal,
    policyCategoriesDraft,
    reportActions,
    session,
    isLoadingReportData,
}: IOURequestStepCategoryProps) {
    ...
    const {isOffline} = useNetwork({onReconnect: fetchData});
    const isLoading = !isOffline && (policyCategories === undefined || isLoadingReportData); // Here we should change
}

```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

https://github.com/Expensify/App/assets/698363/9b5191b1-0439-44cb-b21e-b9d8415ffc68

**Comment by wlegolas** [comment] 2024-07-10 18:10
Hi @fedirjh thank you for sharing your points.

About your point about "Breaking the offline flow" the loading indicator won't be shown because the first condition is to be online:
```
const isLoading = !isOffline && (policyCategories === undefined || isLoadingReportData);
```
I recorded the video below to show the offline functionality when the `CategoryPicker` is shown and the user is offline, you can see the behavior is the same that we have currently on Staging.

https://github.com/Expensify/App/assets/698363/9d4b3ea0-ba92-4562-a20c-74f4901f4677

Related to your point "Loading indicator on form", I suggested putting a loading indicator because the application state is not up to date and the `CategoryPicker` component needs to show feedback to the user about the previous process still occurring. I checked in other forms but didn't find a form with the same behavior that I found in the `CategoryPicker`, maybe other forms don't have this problem with the app state not being up to date.

**Comment by mvtglobally** [comment] 2024-07-11 03:51
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2024-07-11 03:59
Oh interesting, @fedirjh can you repro this? I wasn't able to.

**Comment by wlegolas** [comment] 2024-07-11 17:55
I could see this problem when I changed my network connection to a slow one because the main problem was related to the time that the previous request didn't finish with the time the user opened the modal (`CategoryPicker`).

**Comment by jliexpensify** [comment] 2024-07-11 22:13
Interesting - @fedirjh since selecting a Category is pretty integral to the product, it would be great to ensure that this is rock-solid. Are you able to confirm [this](https://github.com/Expensify/App/issues/44649#issuecomment-2223544309) and determine if we can fix it? Thanks!

**Comment by jliexpensify** [comment] 2024-07-15 04:25
Waiting on @fedirjh

**Comment by wlegolas** [comment] 2024-07-17 02:46
Hi @fedirjh I agree with your point about the `category` field does not have a related modified field.

I simulated locally adding the `modifiedCategory` field and looks like worked as expected.

I can change my proposal to have the implementation to fix it but in my opinion, we have two changes, one in the Frontend project (I can put the details in my current proposal) and another change on the Backend side because the transaction needs to return this new field `modifiedCategory` to update the state with the correct information.

If you agree I can change my proposal to have the information to use the new field `modifiedCategory` to fix this problem.

**Comment by wlegolas** [comment] 2024-07-18 00:51
> > we have two changes, one in the Frontend project (I can put the details in my current proposal)
> 
> @wlegolas Can you share details about front end changes?

Sure, below I'm putting a brief details about the front end changes that we should do to have the `modifiedCategory` information in the Transaction object and also solve this issue.

* Add the new property `modifiedCategory` in the [Transaction](https://github.com/wlegolas/ExpensifyApp/blob/main/src/types/onyx/Transaction.ts#L298) type
* Change the [getCategory](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/TransactionUtils.ts#L413-L415) method to retrieve the category value first using the `modifiedCategory` this looks like the implementation we have in the [getMerchant](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/TransactionUtils.ts#L381)
* Improve the [getUpdateMoneyRequestParams](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/actions/IOU.ts#L2474) method to add a state in the **successData** and **failureData** to have the correct information before the request is finished. For example:

```
function getUpdateMoneyRequestParams(
    transactionID: string,
    transactionThreadReportID: string,
    transactionChanges: TransactionChanges,
    policy: OnyxTypes.OnyxInputOrEntry<OnyxTypes.Policy>,
    policyTagList: OnyxTypes.OnyxInputOrEntry<OnyxTypes.PolicyTagList>,
    policyCategories: OnyxTypes.OnyxInputOrEntry<OnyxTypes.PolicyCategories>,
    onlyIncludeChangedFields: boolean,
): UpdateMoneyRequestData {
    const optimisticData: OnyxUpdate[] = [];
    const successData: OnyxUpdate[] = [];
    const failureData: OnyxUpdate[] = [];
    ...

    // Update recently used categories if the category is changed
    if ('category' in transactionChanges) {
        const optimisticPolicyRecentlyUsedCategories = Category.buildOptimisticPolicyRecentlyUsedCategories(iouReport?.policyID, transactionChanges.category);
        if (optimisticPolicyRecentlyUsedCategories.length) {
            optimisticData.push({
                onyxMethod: Onyx.METHOD.SET,
                key: `${ONYXKEYS.COLLECTION.POLICY_RECENTLY_USED_CATEGORIES}${iouReport?.policyID}`,
                value: optimisticPolicyRecentlyUsedCategories,
            });
        }

        // Update the state with the modified category
        successData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`,
            value: {
                modifiedCategory: transactionChanges.category,
            },
        });

        // Revert the transaction's modified category to the original value on failure.
        if (transaction) {
            failureData.push({
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`,
                value: {
                    modifiedCategory: transaction.modifiedCategory,
                },
            });
        }
    }

    ...
}
``` 
* Add some Unit Tests [here](https://github.com/wlegolas/ExpensifyApp/blob/main/tests/unit/TransactionUtilsTest.ts) to ensure that the `getCategory` method is returning the correct information across transaction scenarios.

This solution will work properly If the back end returns the `modifiedCategory` when the `UpdateMoneyRequestCategory` request is completed.

If you have any questions or suggestions, please let me know.

**Comment by mvtglobally** [comment] 2024-07-19 03:22
Issue not reproducible during KI retests. (Second week)

**Comment by jliexpensify** [comment] 2024-07-19 03:26
Waiting on @fedirjh

**Comment by jliexpensify** [comment] 2024-07-23 03:59
Ok, that's fair - thanks for doing some additional testing @fedirjh , closing!

**Closed by jliexpensify** 2024-07-23 03:59 UTC
Labels: External, Daily, Help Wanted, Bug
