### ISSUE TITLE
Workspace - Newly created workspace does not appear in workspace list on second device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25423] opened 2023-08-17 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to staging.new.expensify.com with the same account on two devices
2. On the first device, create a new workspace
3. On the second device, go to Settings > Workspace

## Expected Result:
The newly created workspace will appear on the second device

## Actual Result:
The chat room for the newly created workspace appear on LHN on the second device, but not on the workspace list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a8137d42-dbb3-4dcc-847f-9516b91fe35c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-08-17 19:07
This issue is the regression of this [PR](https://github.com/Expensify/App/pull/24021).

When we create a workspace, we optimistically set [isPolicyExpenseChatEnabled: true](https://github.com/Expensify/App/blob/f45ddbe78cf00b6a36927aab19422a45cd8a975b/src/libs/actions/Policy.js#L920) but the pusher events doesn't include this value. 

This is the root cause 
We can revert the PR but I think this should be fixed in the backend

**Comment by s-alves10** [comment] 2023-08-17 19:21
@Nikhil-Vats 

Did you pull the latest changes? It's still reproducible for me on main

**Comment by puneetlath** [comment] 2023-08-21 17:32
Assigning over to @youssef-lr since he already has a PR up for this.

**Comment by youssef-lr** [comment] 2023-08-29 10:28
This has been deployed.

**Closed by youssef-lr** 2023-08-29 10:28 UTC
Labels: Reviewing, Engineering, Daily
