### ISSUE TITLE
[$500] mWeb - Status - Keyboard does not appear after autofocus when going to “Status” page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33298] opened 2023-12-19 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open settings and select Profile
3. Enter Status page and view auto-focus

## Expected Result:
Keyboard should appear when message field of Status page is auto focused

## Actual Result:
Keyboard does not appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c0e48893-0415-4a5c-8eee-70d41e851ec9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152a6e99547a1e7a9</li>
        <li>Upwork Job ID: 1737135883301212160</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-19 15:46
I can't reproduce.

**Comment by abeebridwan** [comment] 2023-12-19 15:51
I can't reproduce as well 
the keyboard appears
@Krishna2323 @neonbhai  what are using for testing plz?

**Comment by alitoshmatov** [comment] 2024-01-03 10:56
Thank you everyone. Issue is not reproducible: 


https://github.com/Expensify/App/assets/59907218/25b3753f-397e-49cd-a842-8d0b62ff56a3

cc: @sonialiap

**Comment by sonialiap** [comment] 2024-01-08 18:47
Thanks Ali. Closing since the issue is not reproducible

**Closed by sonialiap** 2024-01-08 18:47 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
