### ISSUE TITLE
Dev: Receipt image on the split details page is showing empty space instead of receipt image

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38642] opened 2024-03-19 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** main branch local
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710852882197159

## Action Performed:
1. Open App > Go to workspace chat.
2. Create a scan split request.
3. Click on the split request while it is scanning.
4. Check the Receipt image on the split details page.

## Expected Result: 
Receipt image should be displayed

## Actual Result: 
Instead of Receipt image, showing empty space

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![bug-split-receipt](https://github.com/Expensify/App/assets/38435837/32d8c947-0151-4e03-9353-d35542d84d5d)

https://github.com/Expensify/App/assets/38435837/29517fb0-272f-4e20-aa33-6d34ee5049b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2024-03-21 17:59
I am pretty confident we have reported this elsewhere. I think it is a dupe.

**Comment by zanyrenney** [comment] 2024-03-21 18:17
Ah i think i must have seen this in the channel: https://expensify.slack.com/archives/C049HHMV9SM/p1710852882197159

**Comment by zanyrenney** [comment] 2024-03-21 18:17
Just a note to say, I am OOO now until April 2nd, reassigning BZ team member to help while I am OOO.

**Comment by jayeshmangwani** [comment] 2024-03-28 15:56
@zanyrenney This issue only reproducible on my local machine, but not on the staging or production, I think if i no one can reproduce this issue we can close the Issue

cc: @slafortune

**Comment by slafortune** [comment] 2024-03-28 17:43
Check on issue related to MAIN here -https://expensify.slack.com/archives/C01SKUP7QR0/p1711641852062809
CLosing

**Closed by slafortune** 2024-03-28 17:43 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
