### ISSUE TITLE
[HOLD for payment 2024-04-03] [PAY March 27][$250] [Reassure] Add reassure test for BaseOptionsList

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38168] opened 2024-03-12 19:42 UTC
### Problem

The [components/OptionsList/BaseOptionsList](https://github.com/Expensify/App/blob/a3b70bf82102dd5092e840062db9fe4192c4c04c/src/components/OptionsList/BaseOptionsList.tsx#L1-L285) is a complex component in the App and if its performance degrades, it can have considerable impact on the App performance.

### Solution

Let's add a reassure test to cover various cases of this component use similarly as we have created such tests for [SelectionList](https://github.com/Expensify/App/blob/a3b70bf82102dd5092e840062db9fe4192c4c04c/tests/perf-test/SelectionList.perf-test.tsx#L1-L164) component for example.

____

Please refer to other tests in the repository, here is a [readme](https://github.com/Expensify/App/tree/main/tests/perf-test) for reassure tests which should help you get familiar with the tool.

All new tests should be written in TS.

Please provide a proposal stating, how you could write such test and scenarios for the component such that we test the slowest execution path as well.

cc @OlimpiaZurek 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013308adf811c76d8b</li>
        <li>Upwork Job ID: 1767637401542344704</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by brunovjk** [comment] 2024-03-12 20:05
### Please re-state the problem that we are trying to solve in this issue.
Add reassure test for BaseOptionsList

### What is the root cause of that problem?

The intricate nature of the BaseOptionsList component, when experiencing performance degradation, can have a notable impact on the application's responsiveness.

### What changes do you think we should make in order to solve the problem?
To address this concern, we propose the addition of a reassurance test that comprehensively covers different use cases of the BaseOptionsList component. This reassurance test should be crafted in TypeScript (TS) to align with our project's language choices. The focus should be on evaluating the slowest execution path of the component, ensuring its robustness and optimal performance.

Additionally, we could follow the measurePerformance approach outlined in the `App/tests/perf-test/SelectionList.perf-test.tsx` file. This approach involves scenarios such as rendering lists with multiple items, testing scrolling performance, assessing onPress/onSelect actions, and evaluating text input interactions. By implementing this strategy, we can ensure that the reassurance test covers a broad range of potential performance bottlenecks.

### What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment] 2024-03-12 20:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Reassure] Add reassure test for BaseOptionsList]
### What is the root cause of that problem?
** New Feature of Writing Test **
### What changes do you think we should make in order to solve the problem?

This is the example Test for reference : 
```
import {measureFunction} from 'reassure';  
import BaseOptionsList from '@src/components/OptionsList/BaseOptionsList';

describe('BaseOptionsList performance', () => {

  const mockSections = // array of 1000 sections
  const mockSelectedOptions = // array of 1000 selected options

  it('measures rendering with 1000 sections', async () => {

    const wrapper = shallow(
      <BaseOptionsList 
        sections={mockSections}
        selectedOptions={mockSelectedOptions}
      />
    );
    
    await measureFunction(() => {
      wrapper.render();
    });

  });

});
```
- This test creates a large amount of mock data - 1000 sections and 1000 selected options.

- It renders the BaseOptionsList component with this data and times how long the initial render takes.

- This allows assessing the performance rendering BaseOptionsList with a realistic amount of data it may handle.

- Additional tests could try different amounts of mock data to test scaling. Or measure rerender times by changing specific props like selectedOptions.

 -The goal is to catch any regressions in rendering performance as the data grows over time. By testing with production-level data volumes, it reduces the risk of slowdowns when users have large amounts of options.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jayeshmangwani** [comment] 2024-03-13 20:46
Thanks for the proposals

From the above proposals I like the @ShridharGoel 's [Proposal](https://github.com/Expensify/App/issues/38168#issuecomment-1992446249), they have mentioned a basic thousand items render scenario, in the PR we can add the few real-life other scenarios like,

1. scroll and press a option list item
2. render multiple options and select list items

 🎀 👀 🎀 C+ reviewed

**Comment by mountiny** [comment] 2024-03-13 23:09
@ShridharGoel please create a Pr and can you please add the scenarios @jayeshmangwani mentioned?

**Comment by jayeshmangwani** [comment] 2024-03-14 17:35
@ShridharGoel What is the ETA for PR?

**Comment by mountiny** [comment] 2024-03-18 10:26
PR is up

**Comment by slafortune** [comment] 2024-03-22 13:25
Merged on 3/20 - so without a regression, payment would be 3/27

**Comment by slafortune** [comment] 2024-03-27 15:12
@mountiny @jayeshmangwani  will we need regression tests for this?

**Comment by slafortune** [comment] 2024-03-27 15:14
@jayeshmangwani offer sent [here](https://www.upwork.com/nx/wm/offer/101368336)
@ShridharGoel offer sent [here](https://www.upwork.com/nx/wm/offer/101368341)

**Comment by jayeshmangwani** [comment] 2024-03-27 15:34
@slafortune No regression tests are needed, update was in the automated tests

**Comment by mountiny** [comment] 2024-03-29 23:03
No tests required here

**Comment by slafortune** [comment] 2024-04-03 12:48
@jayeshmangwani @ShridharGoel please accept the offers sent.

**Comment by jayeshmangwani** [comment] 2024-04-03 13:03
@slafortune Please send a new offer; Getting an error when accepting the old offer.
<img width="728" alt="Screenshot 2024-04-03 at 6 32 33 PM" src="https://github.com/Expensify/App/assets/35371050/5a93e73b-8dca-4f1f-982d-ec382c297c7b">

**Comment by jayeshmangwani** [comment] 2024-04-03 17:06
@slafortune Declined the offer, and I have applied manually to the job Upwork job https://www.upwork.com/jobs/~013308adf811c76d8b

**Comment by slafortune** [comment] 2024-04-03 19:25
Alright - I accepted the proposal and sent you another offer - https://www.upwork.com/nx/wm/offer/101721107

**Comment by slafortune** [comment] 2024-04-03 19:27
@jayeshmangwani is paid
Waiting on @ShridharGoel to accept offer sent [here](https://www.upwork.com/nx/wm/offer/101368341)

**Comment by slafortune** [comment] 2024-04-03 19:44
@ShridharGoel are you able to do the same thing that @jayeshmangwani just did?  Since it worked, seems like the best option.

**Comment by slafortune** [comment] 2024-04-04 12:01
All paid

**Closed by slafortune** 2024-04-04 12:01 UTC
Labels: External, Weekly, NewFeature, Awaiting Payment
