### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Web - App throws 'No content to add' error if we send empty alias for email 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21234] opened 2023-06-21 17:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type in a link with empty alias eg: `[](google.com)`
4. Observe that app handles it well
5. Send email with empty alias eg: `[](test@test.com)`
6. Observe that app throws 'No content to add' for step 5 message

## Expected Result:
App should handle empty alias for email in similar way like it does for link

## Actual Result:
App throws 'No content to add' error for email with empty alias

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3efe4b24-22e0-47e5-9758-5bae899a4dac

https://github.com/Expensify/App/assets/93399543/b68bed52-6612-4012-9223-1ffaf656b18d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686755882619169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e72288a82e6fae6</li>
        <li>Upwork Job ID: 1671920286239043584</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-06-21 17:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App throws 'No content to add' error if we send empty alias for email.

### What is the root cause of that problem?

The root cause of this issue is that below markdown

```
[](test@gmail.com)
```

is translated into html

```html
<a href="mailto:test@gmail.com"></a>
```

by applying [email rule](https://github.com/Expensify/expensify-common/blob/f9985d572c772757885ff59ea5c82b1050c6b3f7/lib/ExpensiMark.js#L59-L68)

```js
{
    name: 'email',
    process: (textToProcess, replacement) => {
        const regex = new RegExp(
            `\\[([^[\\]]*)]\\(${CONST.REG_EXP.MARKDOWN_EMAIL}\\)`, 'gim'
        );
        return this.modifyTextForEmailLinks(regex, textToProcess, replacement);
    },
    replacement: (match, g1, g2) => `<a href="mailto:${g2}">${g1.trim()}</a>`,
}
```

The capturing group g1,  `([^[\\]]*)` , is possible to be empty string and, in the replacement method, we didn't check if `g1.trim() `is empty or not. So, we get anchor tag with empty text by apply the email rule.

The backend returns an error when we try to [save](https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/libs/actions/Report.js#L293) html `<a href="mailto:test@gmail.com"></a>` to the backend. The error returned by backend is

<img width="778" alt="image" src="https://github.com/Expensify/App/assets/117511920/dc30940c-2bbd-4ab3-9655-c698f4c824ec">

I think the error from backend makes sense because the backend needs to convert html

```html
<a href="mailto:test@gmail.com"></a>
```

to text(aka `message[0].text`) which shouldn't be empty.

So the root cause of this issue is that [email rule](https://github.com/Expensify/expensify-common/blob/f9985d572c772757885ff59ea5c82b1050c6b3f7/lib/ExpensiMark.js#L59-L68) doesn't avoid creating anchor tag with empty text.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can skip creating anchor tag with empty text. 

To achieve this, we can change the replacement method of  [email rule](https://github.com/Expensify/expensify-common/blob/f9985d572c772757885ff59ea5c82b1050c6b3f7/lib/ExpensiMark.js#L59-L68) from

```js
replacement: (match, g1, g2) => `<a href="mailto:${g2}">${g1.trim()}</a>`,
```

to

```js
// skip rendering if g1.trim() is empty
replacement: (match, g1, g2) => (!g1.trim() ? match : `<a href="mailto:${g2}">${g1.trim()}</a>`),
```

Below is the demo video of the solution

https://github.com/Expensify/App/assets/117511920/4fc47889-2aa8-4e10-93eb-4d9eb94d037a

### What alternative solutions did you explore? (Optional)

N/A

**Comment by laurenreidexpensify** [comment] 2023-06-22 12:47
Checking something internally here https://expensify.slack.com/archives/C01SKUP7QR0/p1687437975259329 about this

**Comment by eh2077** [comment] 2023-06-25 16:17
@YacineF0001 Thanks for tagging me in your proposal. But I think our solutions are different for test case like
```
[    ](test@gmail.com)
```

Below is the demo video for two test cases
```
[](test@gmail.com)
[    ](test@gmail.com)
```

https://github.com/Expensify/App/assets/117511920/3aaeafeb-34be-4d16-8ba0-83c4cc4c61f3

I think the App prefers to keep the user input as it is. So, in the editing mode, we display the original input. 

@laurenreidexpensify Happy to hear your thoughts on the expected behaviour.

cc @parasharrajat

**Comment by eh2077** [comment] 2023-06-26 01:45
### Proposal
[Updated](https://github.com/Expensify/App/issues/21234#issuecomment-1601286678) to add an alternative regex based method and included a demo video covers more test cases.

cc @parasharrajat

**Comment by eh2077** [comment] 2023-06-26 02:53
> @eh2077 Thanks for your pointing out. it can be also done with Regex. 
> 
> Just add (?!\\[[ ]*\\]) at the beginning of pattern.
> 
> ![image](https://github.com/Expensify/App/assets/137194363/3caf3023-df9c-4ece-b34f-f94a88328211)
> 
> 
> 
> @parasharrajat My proposal [updated](https://github.com/Expensify/App/issues/21234#issuecomment-1606101293)

@YacineF0001 I think your method only fixes the effects and not the root cause. The method I suggested to handle all white spaces fixes the root causes. That's the essential.

**Comment by eh2077** [comment] 2023-06-26 03:30
> @eh2077 you just added a case with '\s' instead of ' ' on my regex. 

I'm afraid I can't agree on it. According to timeline, I first came up the regex solution to solve the root cause of **_all whitespaces_**, which is essential to fix the root cause of the issue.

> so let's wait for @parasharrajat 's review on your original one and my regex solution

I think the C+ team will review it following the [contribution guides](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#check-github-for-existing-proposals-from-other-users) here

> Expensify reviews all solution proposals on a first come first serve basis. If you see other contributors have already proposed a solution, you can still provide a solution proposal and we will review it. We look for the earliest provided, best proposed solution that addresses the job.

**Comment by eh2077** [comment] 2023-06-28 01:10
@parasharrajat Thanks for reviewing proposals. 

I'm open to share the bounty with @YacineF0001 , like 50/50. I'd also suggest to let @YacineF0001 make the PR which should be his first contribution to the App! Hope team will take this into consideration.

**Comment by laurenreidexpensify** [comment] 2023-07-03 11:06
@parasharrajat is tehre something specific that requires technical review? we updated the process in the past couple of weeks, so engineering review is only required on the PR or any technical conversation in the issue, so if you're happy with the solution and the team sharing the bounty, then SGTM and we can move to PR?

**Comment by Gonals** [comment] 2023-07-03 14:06
> I am fine with it @eh2077. What do you say @YacineF0001?
> 
> Bump @Gonals

Sorry, I was OOO until today. I am fine with it too 👍

**Comment by Gonals** [comment] 2023-07-03 14:06
> I am fine with it @eh2077. What do you say @YacineF0001?
> 
> Bump @Gonals

I was OOO until today, but I agree with this too 👍

**Comment by eh2077** [comment] 2023-07-04 02:10
@YacineF0001 I think you can start to prepare the PR. Usually you don't have to apply the job to be allowed to submit the PR. You can also apply the job when payment is due, so you'll have time to handle your Upwork account issue during that time.

**Comment by eh2077** [comment] 2023-07-04 07:55
@parasharrajat Should I make the PR to move the issue forward quicker as suggested by @YacineF0001 's https://github.com/Expensify/App/issues/21234#issuecomment-1619379253 ?

**Comment by laurenreidexpensify** [comment] 2023-07-04 07:56
@YacineF0001 unfortunately if you do not have an active Upwork account we will not be able to move forward here. Would recommend as a next step that you work with Upwork to have the account restored. We have plenty of issues available to work on with the `help wanted` label, so this won't be the only opportunity to pick up a job on our repos!

**Comment by eh2077** [comment] 2023-07-04 08:24
@parasharrajat The PR https://github.com/Expensify/expensify-common/pull/555 for expensify-common is ready. Please help to review it at your convenience, thanks!

**Comment by eh2077** [comment] 2023-07-04 14:39
@parasharrajat The PR https://github.com/Expensify/App/pull/22182 for App to bump version of expensify-common is ready.

**Comment by eh2077** [comment] 2023-07-18 09:35
@laurenreidexpensify Accepted the offer thanks.

**Comment by laurenreidexpensify** [comment] 2023-07-19 12:20
Payments issues + regression test requested. 

@parasharrajat am closing, please proceed with payment request in newdot via @anmurali Thanks

**Closed by laurenreidexpensify** 2023-07-19 12:20 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 05:13
@laurenreidexpensify Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @parasharrajat's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by laurenreidexpensify** [comment] 2023-07-28 11:34
Payments: 

-  External issue reporter: @dhanashree-sawant = $250,  issued in Upwork
-  Contributor that fixed the issue: @eh2077 = $1000 + $500, issued in Upwork
-  Contributor+ that helped on the issue and/or PR: @parasharrajat + 3 day merge bonus = $1000 + $500, issued in newdot

**Comment by JmillsExpensify** [comment] 2023-07-29 16:01
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
