### ISSUE TITLE
Android - Chat - App takes too long to respond after tapping the green plus icon or chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23077] opened 2023-07-18 12:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Tap the green plus icon
3. Tap "Chat"

## Expected Result:
The App should respond immediately after the user taps the "green plus" icon or "Chat"

## Actual Result:
After tapping the "green plus icon" or "Chat", the app takes too long to respond

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/819b758b-11d4-4298-98cf-70f242ba1724

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by MitchExpensify** [comment] 2023-07-18 23:03
I have admitedly not been assigned a deploy blocker bug @stitesExpensify - Based on [this](https://github.com/Expensify/App/issues/23077#issuecomment-1640968725), I'm curious if you are up for fixing this or if we need to look elsewhere?

**Comment by jasperhuangg** [comment] 2023-07-18 23:05
This seems to be reproducible in production, so I don't think we should block deploy on this. @MitchExpensify this should go through the regular bug triage process

**Comment by MitchExpensify** [comment] 2023-07-18 23:21
Ok great! Thanks @jasperhuangg 

The delay is pretty short but it is noticeable (I think 😅 ) . Maybe that is browserstack - Did you reproduce on a physical device Jasper?

**Comment by MitchExpensify** [comment] 2023-07-24 20:58
>  Did you reproduce on a physical device @jasperhuangg? 

A quick bump on this question as I'm a little unsure if my reproduction was related to using a virtual device on browserstack seeing as the delay was barely noticeable

**Comment by stitesExpensify** [comment] 2023-07-28 18:39
bump @jasperhuangg were you ever able to reproduce on a physical device?

**Comment by jasperhuangg** [comment] 2023-07-31 03:48
Nope, I wasn't. I don't really have the bandwidth to look into this right now, sorry for the delay.

**Comment by MitchExpensify** [comment] 2023-08-01 18:27
Closing until we can get reliable production steps

**Closed by MitchExpensify** 2023-08-01 18:27 UTC
Labels: Engineering, Daily, Overdue, Bug
