### ISSUE TITLE
[$500] [Ideal Nav] Chats - Breadcrumbs shows different workspace when another workspace is selected via keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38297] opened 2024-03-14 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has a few workspaces
1. Go to staging.new.expensify.com
2. Open workspace switcher
3. Open a different workspace using keyboard arrow keys and Enter

## Expected Result:
The breadcrumbs will show the correct workspace

## Actual Result:
The breadcrumbs shows different workspace when another workspace is selected via keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cbc2f374-9f18-48d3-8138-3d555ef8b110

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165d93da7594b5802</li>
        <li>Upwork Job ID: 1769822686303518720</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-14 12:01
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by lanitochka17** [comment] 2024-03-14 12:01
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-03-14 13:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The breadcrumb shows the previous selected workspace when selecting it with keyboard.

### What is the root cause of that problem?
When we select a workspace, it will do 3 things, set the new active workspace ID, navigate back, and push a new bottom tab screen with a new policy ID params.
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/pages/WorkspaceSwitcherPage.tsx#L113-L117

Then, we also have a nav state change listener that will also set the new active workspace ID based on the top most bottom tab policy ID.
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/libs/Navigation/NavigationRoot.tsx#L115-L124

The issue we have here is the state listener above is called with an undefined policy ID. It's undefined when we call Navigation.goBack because, at this point, there is no policy ID yet in the params. After the switch policy ID happens, we get the correct policy ID. Weirdly, if we select it normally, the navigation goBack and switch policy ID happens in a batch, so we never get an undefined policy ID.

The next problem is because the active workspace ID is updated very quickly between the correct policy ID and undefined, `withOnyx` can't give the correct onyx data. This is a bug in onyx itself. You can test it by having a button that will switch the active workspace ID between an undefined and a real policy ID and you will see the issue.

### What changes do you think we should make in order to solve the problem?

Maybe we should fix the onyx issue, but I would like to propose to update the active workspace ID only when the nav state changes. In short, we will remove the setActiveWorkspaceID here.
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/pages/WorkspaceSwitcherPage.tsx#L113

and keep what we have here.
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/libs/Navigation/NavigationRoot.tsx#L115-L124

**Comment by trjExpensify** [comment] 2024-03-15 12:38
Isn't this the same? https://github.com/Expensify/App/issues/38281

**Comment by trjExpensify** [comment] 2024-03-15 13:00
Got it, I thought they might be related or the solution [here](https://github.com/Expensify/App/issues/38297#issuecomment-1999220296) fixes the delay.

**Comment by dylanexpensify** [comment] 2024-03-18 20:26
Yep, repro'd. Nice catch!

**Comment by dylanexpensify** [comment] 2024-03-20 11:43
bump @rushatgabhane

**Comment by trjExpensify** [comment] 2024-03-25 19:08
@rushatgabhane can you look at this one, please?

**Comment by dylanexpensify** [comment] 2024-03-25 19:50
Pending @rushatgabhane review

**Comment by rushatgabhane** [comment] 2024-03-26 13:40
yes gimme a moment

**Comment by rushatgabhane** [comment] 2024-03-26 20:37
I like @bernhardoj's [proposal](https://github.com/Expensify/App/issues/38297#issuecomment-1997408354) to update the active workspace ID only when the nav state changes.

🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2024-03-27 06:15
> The UI will have a glitch and the workspace icon will not be displayed in time

I think that looks alright. The avatar will take some time to update

**Comment by bernhardoj** [comment] 2024-03-28 12:08
We always need to call goBack to close the WS switcher page. I'm okay if you want to go with @dragnoir main solution if it works well.

**Comment by rushatgabhane** [comment] 2024-03-30 08:36
@dragnoir thanks for the explaination. I like your solution 🎀 👀 🎀 

https://github.com/Expensify/App/issues/38297#issuecomment-1999220296

**Comment by trjExpensify** [comment] 2024-04-15 10:18
PR merged, nice!

**Comment by rushatgabhane** [comment] 2024-04-28 17:34
PR on prod last week - https://github.com/Expensify/App/pull/39787#issuecomment-2069773870

@trjExpensify please attach payment summary when you can, thank you : )

**Comment by rushatgabhane** [comment] 2024-04-28 17:35
manual request here - https://staging.new.expensify.com/r/7288437908240506

**Comment by dylanexpensify** [comment] 2024-04-29 10:28
@dragnoir please [apply here](https://www.upwork.com/jobs/~010e04548563eeb3ff)! 🙇‍♂️

**Comment by JmillsExpensify** [comment] 2024-04-30 23:25
$500 approved for @rushatgabhane

**Comment by dylanexpensify** [comment] 2024-05-01 07:46
@dragnoir paying today!

**Comment by dylanexpensify** [comment] 2024-05-07 11:09
Done!

**Closed by dylanexpensify** 2024-05-07 11:09 UTC
Labels: Reviewing, External, Weekly, Bug
