### ISSUE TITLE
IOU - IOU preview component avatars are not being shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25509] opened 2023-08-18 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Reply from account B
3. Go to account A and click on the plus icon > request money > enter an amount > confirm the request
4. Observe the IOU preview component

## Expected Result:
There should be two avatars (account A's and account B's) on the left side of the IOU preview component

## Actual Result:
If account A makes a money request after sending a message the avatars show up. But if account B replies after account A sent a message then the IOU preview components will not show the two avatars

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f98b2d21-7428-4fc8-af7b-63dc11977453

https://github.com/Expensify/App/assets/78819774/6a9208d2-eb92-4ce9-9e99-fe805e825da4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691576448671119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment] 2023-08-19 09:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If account A makes a money request after sending a message the avatars show up. But if account B replies after account A sent a message then the IOU preview components will not show the two avatars. There should be two avatars (account A's and account B's) on the left side of the IOU preview component

### What is the root cause of that problem?
The primary reason for this discrepancy is the logic inside the `isConsecutiveActionMadeByPreviousActor` function, which decides how avatars should be displayed in the component. The function determines if actions should be grouped or displayed consecutively. The issue arises because, when User A sends a request for money, the `actorAccountID` is assigned User B's ID. This causes the function to interpret that the consecutive actions are not made by the same actor, thus leading to current scenario.

https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/pages/home/report/ReportActionsList.js#L263

https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/ReportActionsUtils.js#L255-L288

### What changes do you think we should make in order to solve the problem?
To rectify this:

**1. Refine the Logic:** Update the `isConsecutiveActionMadeByPreviousActor` function to accurately determine the sequence of actions, especially for IOU-related actions.

**2. Utilize Existing Structures:** Using the `allReports` structure and the function `getIOUReportIDFromReportActionPreview`, access the necessary data for the current and previous reports.

**3. Determine IOU Actions:** Introduce a check within the function to determine if the action is related to an IOU report. This can be achieved by evaluating the type of report.

**4. Compare Relevant Attributes:** For IOU actions, modify the comparison logic to evaluate the correct attributes for the avatars. For instance, consider attributes like `managerID` and `ownerAccountID` to ensure the right display decision is made.
```

// eslint-disable-next-line no-use-before-define
const currentReport = allReports[getIOUReportIDFromReportActionPreview(currentAction)];
// eslint-disable-next-line no-use-before-define
const previousReport = allReports[getIOUReportIDFromReportActionPreview(previousAction)];

// eslint-disable-next-line es/no-optional-chaining
if (isIOUReport(currentReport) && !isIOUReport(previousReport)){
    return false;
}
// Can also do this
//  if ( !isIOUReport(currentReport) && isIOUReport(previousReport)){
//     return false;
// }

if (isIOUReport(currentReport) && isIOUReport(previousAction)) {
  return currentReport.ownerAccountID === previousReport.ownerAccountID && currentReport.managerID === previousReport.managerID;
}

return currentAction.actorAccountID === previousAction.actorAccountID;
```

**Comment by ShogunFire** [comment] 2023-08-19 19:45
Your proposal makes sense but if I am not mistaken in your video at the end the issue is still there 
![image](https://github.com/Expensify/App/assets/19537677/e91e7c7d-0232-44ba-9d04-44dbe9d96ed6)

PS: I am not the C+ I just want to see if it's worth getting into this

**Comment by ygshbht** [comment] 2023-08-19 19:53
That looks like a difference issue if at all as you see the Avatar but not two

**Comment by ShogunFire** [comment] 2023-08-19 19:56
Ah you are right this is better but I still think if the issue is to show the avatars they should show correctly

**Comment by ShogunFire** [comment] 2023-08-19 20:07
Actually you are right this is another issue  sorry https://github.com/Expensify/App/issues/25510

**Comment by ygshbht** [comment] 2023-08-19 20:08
I forgive you

**Comment by stephanieelliott** [comment] 2023-08-22 16:48
Ok, so based on the video it seems like the pattern is: 
 - If the account initiates the request (i.e. takes an action): 2 avatars shown 
 - If the account just receives the request (i.e has not taken any action): initiator's avatar shown 
 
 Im I following this correctly? If so, I think that makes sense. Anyone can make a request to anyone else -- but your avatar is shown when you have taken an action to participate in the request. I think showing both avatars also makes sense, but this seems more of a design choice than a bug.

**Comment by ygshbht** [comment] 2023-08-22 16:54
Maybe I am wrong but I think it's also saying that in both scenarios you are requesting money, the avatars are shown if previous message was by you and they are not shown if the message was by other user. In both cases, there should be two avatars as it's the same action

**Comment by ygshbht** [comment] 2023-08-22 16:55
> Actually you are right this is another issue sorry #25510

@stephanieelliott Maybe you are referring to this issue

**Comment by stephanieelliott** [comment] 2023-08-25 16:59
Thanks @ygshbht. Seeing as this doesn't affect functionality and is an intentional design choice, I am going to close this for now. If we decide to change it in the future we will reopen it.

**Closed by stephanieelliott** 2023-08-25 16:59 UTC
Labels: Daily, Overdue, Bug

**Comment by ygshbht** [comment] 2023-08-25 17:02
Ok! I just thought it is weird when you make the money request and the app shows it is made by the other user

**Comment by Nathan-Mulugeta** [comment] 2023-08-25 17:08
Yeah I thought the same too, it is very weird if it is a design choice.
