### ISSUE TITLE
[HOLD for payment 2023-12-06] [HOLD for payment 2023-11-28] Wallet - After tapping on the debit card number field, an error message appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30703] opened 2023-11-01 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.94.0
**Reproducible in staging?:**Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29983
## Action Performed:
1. Log in with any expensifail account
2. Go to profile - Setting - Wallet
3. Select Add Bank Account
4. Select Debit card
5. Put Name on "Name on card" field
6. Tap on "Debit card number" field

## Expected Result:
No error message appears after tapping on the debit card number field

## Actual Result:
After tapping on the debit card number field, an error message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b80ffed7-3196-4da9-8717-2a52dab0b154

Production:

https://github.com/Expensify/App/assets/78819774/8e0cb80a-c08a-4148-836b-dbb397081161

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2023-11-01 14:48
@kowczarz Are you able to fix this ASAP or should https://github.com/Expensify/App/pull/29983 be reverted?

**Comment by tgolen** [comment] 2023-11-01 17:01
@lanitochka17 I am cherry-picking the revert of the offending PR to staging now. Can you please retest this once it is deployed there and see if the deployblocker is resolved?

**Comment by kavimuru** [comment] 2023-11-01 18:06
@tgolen sure we will retest.

**Comment by Beamanator** [comment] 2023-11-01 19:08
Ready for retest please @kavimuru 🙏

**Comment by kavimuru** [comment] 2023-11-01 19:16
@Beamanator Our team validating. It's a pass in all the platforms but iOS. iOS build (1.3.94-1) is not available yet.

**Comment by Beamanator** [comment] 2023-11-02 08:09
I can confirm this is fixed on iOS build 1.3.94-2! 👍

**Comment by kowczarz** [comment] 2023-11-08 16:42
Hello @tgolen! I was OOO last week. I will restore the changes and fix the issue today/tomorrow.

**Comment by JmillsExpensify** [comment] 2023-11-24 19:23
@allroundexperts do you mind kicking off the BZ checklist as well?

**Comment by JmillsExpensify** [comment] 2023-11-24 19:24
In addition, I'd like confirmation as to whether this issue should be subject to a regression penalty?

**Comment by allroundexperts** [comment] 2023-11-26 22:06
## Regression Test
1. Log in and Go to profile -> Setting -> Wallet
2. Select Add Bank Account
3. Select Debit card
4. Put Name on "Name on card" field
5. Tap on "Debit card number" field

Verify that no error message appears after tapping on the debit card number field.

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment] 2023-11-29 00:18
Hmm, I'm starting to think that this might not be needed in TestRail. @tgolen can I get a second opinion?

**Comment by JmillsExpensify** [comment] 2023-11-29 00:19
In the meantime, payment summary:

 - Issue reporter: N/A
 - Contributor: Expert agency
 - Contributor+: @allroundexperts $500

**Comment by tgolen** [comment] 2023-11-29 16:23
I agree it's a very low-value regression. If there is already an existing regression test for adding a debit card, maybe this could be just one additional verification that the testers verify. If there is no existing regression test, then we probably don't need to add anything.

**Comment by tgolen** [comment] 2023-12-08 15:52
@JmillsExpensify @allroundexperts Can we see about getting this one closed out? Looks like there is a final checklist waiting on you.

**Comment by JmillsExpensify** [comment] 2023-12-13 05:37
@allroundexperts mind completing the BZ checklist? Once we get that I get can ahead and close and you can request payment in NewDot.

**Comment by allroundexperts** [comment] 2023-12-14 00:54
@JmillsExpensify I've already added the regression test above. Rest of the checklist is not applicable here since this was just a revert of a refactor we previously did.

**Comment by JmillsExpensify** [comment] 2023-12-14 05:14
Perfect, thanks for confirming. Regression test created

**Comment by JmillsExpensify** [comment] 2023-12-14 05:14
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/30703#issuecomment-1830987981).

**Closed by JmillsExpensify** 2023-12-14 05:14 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
