### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [HOLD for payment 2024-06-13] Group Chats Front end clean up & refactors

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40187] opened 2024-04-12 20:11 UTC
@s77rt I would say this list is not exclusive. If you have any ideas on how to improve the code further we can take an approach where you propose what we should change, I'll review that, and we can go from there and add things to the list below. 

Otherwise, this is the minimum expectation:

- [ ] Refactor `navigateToMostRecentReport()`. There is some overlap with `findLastAccessedReport()` and `navigateToMostRecentReport()` and we can probably centralize this logic. Typescript and logic could also be cleaned up for this in some places (e.g. https://github.com/Expensify/App/pull/39757/files#r1560501974, https://github.com/Expensify/App/pull/39757/files#r1560497281 and https://github.com/Expensify/App/pull/39757/files#r1560510114)

- [ ] Combine the `r/:reportID/settings/group-name` route and `room-name` route. Let’s just have one top level page for editing both (separate components can be rendered depending on chat type - just one idea). And call this `settings/name`. Reduce potential duplication if possible.

- [ ] `NewChatConfirmPage` - move or useCallback for these functions https://github.com/Expensify/App/pull/39757/files#r1560025967 

- [ ] `ReportDetailsPage` - Capture all avatar options in the renderAvatar as per this suggestion here https://github.com/Expensify/App/pull/39757/files#r1560030786 optionally, this could also be a new component as well.

- [ ] `getReportName()` refactor suggestion from here https://github.com/Expensify/App/pull/39757#discussion_r1554713758

- [ ] `newChatNameForm` Onyx key - seems this is not working as intended https://github.com/Expensify/App/pull/39757#issuecomment-2041282724

- [ ] Ensure that we can not access an invalid member page as found here - https://github.com/Expensify/App/pull/39757#issuecomment-2041283316

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by s77rt** [comment] 2024-04-23 23:51
No update yet

**Comment by marcaaron** [comment] 2024-04-30 00:59
This can come off HOLD now.

**Comment by s77rt** [comment] 2024-05-08 20:02
I didn't get a chance to look into this yet

**Comment by s77rt** [comment] 2024-05-18 17:00
Raised a [PR](https://github.com/Expensify/App/pull/42365) for the first list item (`navigateToMostRecentReport` simplification)

**Comment by s77rt** [comment] 2024-05-18 19:59
Raised a [PR](https://github.com/Expensify/App/pull/42369) for the second list item (combining report name routes)

**Comment by s77rt** [comment] 2024-06-04 11:24
Raised a [PR](https://github.com/Expensify/App/pull/43027) for the remaining tasks:
- [X] `NewChatConfirmPage` - move or useCallback for these functions: Done
- [X] `ReportDetailsPage` - Capture all avatar options in the renderAvatar: This was handled [here](https://github.com/Expensify/App/pull/42735) 
- [X] `getReportName()` refactor: `getReportName` already supports group chat, nothing to do here
- [X] `newChatNameForm` Onyx key - seems this is not working as intended: False positive. This is working as expected, we are not using draft here and the empty `newChatNameForm` object shown in the video is for the form state i.e. `isLoading`, `errors`. Since it's not loading and we don't have errors it's empty.
- [X] Ensure that we can not access an invalid member page: Done

**Comment by ikevin127** [comment] 2024-06-06 18:44
**^ Regression message is `false` alarm as the issue was caused by PR https://github.com/Expensify/App/pull/42554.**
##

> * [ ] Combine the r/:reportID/settings/group-name route and room-name route. Let’s just have one top level page for editing both (separate components can be rendered depending on chat type - just one idea). And call this settings/name. Reduce potential duplication if possible.

The **[HOLD for payment 2024-06-13]** was added from PR https://github.com/Expensify/App/pull/42369 and I require payment as reviewer.

cc @marcaaron

**Comment by ikevin127** [comment] 2024-06-12 19:34
@marcaaron Can you please assign somebody to handle the payment for the **first merged PR** tomorrow ?
**Note:** It's the one referenced above in https://github.com/Expensify/App/issues/40187#issuecomment-2153175196.

**Comment by ikevin127** [comment] 2024-06-13 18:31
@adelekennedy The first payment for the first merged PR https://github.com/Expensify/App/pull/42369 is due today, more context [here](https://github.com/Expensify/App/issues/40187#issuecomment-2153175196) in a previous comment.

**Comment by adelekennedy** [comment] 2024-06-13 19:04
Payouts due:

- [ ] Contributor: $250 @s77rt 
- [ ] Contributor+: $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~01b4669fc5a97c0f41).

**Comment by adelekennedy** [comment] 2024-06-13 19:05
@ikevin127 I think we'll just use this issue for each related payment that's due - it looks like we have three related PRs with payment due today, the 18th and on the 20th?

**Comment by ikevin127** [comment] 2024-06-13 19:22
@adelekennedy Offer accepted, thanks a lot !

##

> @ikevin127 I think we'll just use this issue for each related payment that's due - it looks like we have three related PRs with payment due today, the 18th and on the 20th?

Yes, the first payment was due today for the PR author and me as reviewer and there will be another payment due on **2024-06-18** based on https://github.com/Expensify/App/issues/40187#issuecomment-2161765246 for the same PR author and @jjcoffee as reviewer.

 The **[HOLD for payment 2024-06-20]** is weird because it was already deployed to production 2 days ago based on https://github.com/Expensify/App/issues/40187#issuecomment-2161765246 and this is the same and last PR of this issue based on PR author https://github.com/Expensify/App/issues/40187#issuecomment-2147289270, addressing all other checkboxes.

**Comment by s77rt** [comment] 2024-06-13 22:29
@adelekennedy There is still one PR https://github.com/Expensify/App/pull/42365 that needs to be merged (do not close the issue yet)

**Comment by adelekennedy** [comment] 2024-06-13 22:33
@s77rt yes! I plan to keep this issue [open](https://github.com/Expensify/App/issues/40187#issuecomment-2166577035) o we can track payment for all three PRs

**Comment by adelekennedy** [comment] 2024-06-17 20:02
next payment due tomorrow!

**Comment by adelekennedy** [comment] 2024-06-18 17:54
Payouts due for [43027](https://github.com/Expensify/App/pull/43027):

- [ ] PR: $250 @s77rt 
- [ ] PR Review: $250 @jjcoffee 

Upwork job is [here](https://www.upwork.com/ab/applicants/1801329782704979917/suggested).

**Comment by s77rt** [comment] 2024-06-18 21:37
@adelekennedy I'm only due $250 for the issue. The remaining payments are only for the reviewers

**Comment by adelekennedy** [comment] 2024-06-18 22:16
@s77rt sorry about that - are you saying for the three PRs you authored ([42369](https://github.com/Expensify/App/pull/42369), [43027](https://github.com/Expensify/App/pull/43027), and [42365](https://github.com/Expensify/App/pull/42365) you should only get the $250 already paid out for the first PR?

**Comment by s77rt** [comment] 2024-06-18 23:12
@adelekennedy Yes that's correct

**Comment by jjcoffee** [comment] 2024-06-19 10:45
@adelekennedy Offer accepted, thanks!

**Comment by adelekennedy** [comment] 2024-06-19 19:29
Final PR hasn't merged yet

**Comment by adelekennedy** [comment] 2024-06-24 18:19
I think we're just waiting for the final PR to pay out the reviewer fee

**Comment by marcaaron** [comment] 2024-06-27 03:16
Is this done yet?

**Comment by s77rt** [comment] 2024-06-27 15:13
@marcaaron Almost, it requires your review 👀 https://github.com/Expensify/App/pull/42365/

**Comment by adelekennedy** [comment] 2024-07-01 21:46
It looks like that last PR was just approved and merged!

Payouts due for https://github.com/Expensify/App/pull/42365"

 PR Review: $250 @fedirjh (NewDot)

**Comment by adelekennedy** [comment] 2024-07-01 21:46
Anything

**Comment by adelekennedy** [comment] 2024-07-08 04:06
not deployed to prod yet

**Comment by s77rt** [comment] 2024-07-15 15:57
Checklist ^ does not apply here. This was just a cleanup task.

Issue can be closed after paying out @fedirjh

**Comment by adelekennedy** [comment] 2024-07-15 16:59
2 days away from payment!

**Comment by marcaaron** [comment] 2024-07-25 01:50
Are we waiting for anything else here?

**Comment by adelekennedy** [comment] 2024-07-25 04:03
Payouts due:

- [ ] Contributor: $250 @fedirjh

**Closed by adelekennedy** 2024-07-25 04:03 UTC
Labels: Weekly, Planning, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-05 11:55
$250 approved for @fedirjh
