### ISSUE TITLE
[$1000] Selecting a message sent before IOU by triple click copies both regular message and IOU preview message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14263] opened 2023-01-13 02:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to the chat, and send any text message, e.g. Hello world
2. Request money to the user using click + in Composer
3. Using double click copy the message that was sent before requesting money
4. Paste the copied message in chat or anywhere

## Expected Result:
Selected message only should be copied to clipboard

## Actual Result:
Selected message and request money message both are being copied

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.53-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212220172-7be1733e-8c97-4727-8960-7aef86251ab6.mov

https://user-images.githubusercontent.com/43996225/212220185-b7634471-4cd5-4384-be69-ace15e1c8947.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673552189522379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bba5039e2e0425a5</li>
        <li>Upwork Job ID: 1613893870777389056</li>
        <li>Last Price Increase: 2023-01-13</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-01-13 12:25
reviewing

**Comment by dylanexpensify** [comment] 2023-01-13 13:35
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by Someone-here** [comment] 2023-01-13 15:12
I am unable to reproduce this on `1.2.54-0`
Is there something I am missing? I copied the exact same process as in slack but I couldn't replicate.
@jayeshmangwani

**Comment by jayeshmangwani** [comment] 2023-01-13 15:22
@Someone-here can you please share video, so that I can help you to test

**Comment by getusha** [comment] 2023-01-13 16:27
I am unable to reproduce this on `staging`
I think it's handled somewhere @jayeshmangwani

**Comment by getusha** [comment] 2023-01-13 16:34
@Someone-here yes i am too unable to reproduce it in local & staging but it's producible in prod

**Comment by alexxxwork** [comment] 2023-01-13 16:55
Got it again. Used Ctrl-Ins + right button to paste. But can't reproduce again

**Comment by mananjadhav** [comment] 2023-01-16 04:29
@kavimuru Are you able to reproduce this reliably?

**Comment by OscarLVargas** [comment] 2023-01-16 20:05
The problem is that when selecting the message, Safari doesn't correctly identify where the paragraph ends. The correction is to add a span tag after the message and before the edited flag.

https://user-images.githubusercontent.com/122373536/212757507-cd56b993-6a3c-4a58-9b66-77accce5d437.mov

**Comment by francoisl** [comment] 2023-01-17 18:48
I'm curious about what version of Safari you use, in case it's specific to a version? I'm also unable to reproduce the issue on Safari 16.2. Tested on staging, production and the current dev version.

**Comment by OscarLVargas** [comment] 2023-01-17 20:25
I have Safari version 15.6.1, upon checking again, I found that the div structure is different in production and now triple-clicking does not select more than one line.

**Comment by kavimuru** [comment] 2023-01-17 22:10
@mananjadhav I am not able to reproduce in the version 1.2.55-0

**Comment by francoisl** [comment] 2023-01-18 02:32
Ok so it seems no one can reproduce anymore, maybe there was an issue but it got fixed as a side effect of another PR...

I'm going to close this for now, let's reopen if it starts happening again.

**Closed by francoisl** 2023-01-18 02:32 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by mananjadhav** [comment] 2023-01-18 02:37
Agreed on closing it!
