### ISSUE TITLE
Track tax - Tax amount is not 0.00 after editing distance when "Tax reclaimable" is not filled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43840] opened 2024-06-17 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4635627
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Track tax is enabled
- The distance rate to be used has a non-zero tax rate and "Tax reclaimable on" amount is not filled
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a distance expense using the distance rate from the precondition
4. Go to transaction thread
5. Note that the tax amount is 0.00
6. Click Distance
7. Edit distance and save it
8. Note that the tax amount is no longer 0.00
9. Go to main chat and return to transaction thread
10. Note that the tax amount is 0.00

## Expected Result:
The tax amount should remain 0.00 after editing the distance because "Tax reclaimable on" amount is not filled

## Actual Result:
In Step 8, the tax amount is no longer 0.00 after editing the distance
In Step 10, the tax amount changes back to 0.00 after revisiting transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fccd0f2f-7f3e-4015-ad21-c4692a64742f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by lanitochka17** [comment] 2024-06-17 15:02
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-17 15:02
We think that this bug might be related to #wave-collect - Release 1

**Comment by trjExpensify** [comment] 2024-06-19 11:17
@MonilBhavsar @nkdengineer might want to look at this. 👀

**Comment by MonilBhavsar** [comment] 2024-06-24 06:27
Will look this week

**Comment by MonilBhavsar** [comment] 2024-06-28 05:02
I've identified the root cause. Will write automated tests and submit PR for review

**Comment by MonilBhavsar** [comment] 2024-06-28 09:24
PR is in review!

**Comment by puneetlath** [comment] 2024-07-05 18:29
Looks like this was fixed. I'll ask for a re-test.

**Comment by kavimuru** [comment] 2024-07-08 13:40
Not reproducible anymore.

https://github.com/Expensify/App/assets/43996225/e7f09f49-22bb-4b34-ba63-e6f6a2748432

**Comment by puneetlath** [comment] 2024-07-08 13:57
Great, thanks! Closing out.

**Closed by puneetlath** 2024-07-08 13:57 UTC
Labels: Reviewing, Daily, Bug
