### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$500] IOU-After deleting request, hold request system message displayed distorted

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40078] opened 2024-04-11 06:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap start chat
3. Select user with no prior conversation
4. Tap plus icon and request money without receipt
5. Again request money with receipt(use camera and upload an image for receipt)
6. Open 2nd IOU details page
7. Tap on top 3 dots and select hold request
8. Enter reason and save it
9. Tap got it.
10. Tap 3 dots and select unhold
11. Again tap 3 dots and delete request

## Expected Result:
As in production, user must be navigated to previous IOU details page after deleting 2nd IOU.

## Actual Result:
After deleting request, hold request system message displayed section looks distorted. User is in same delete request page in staging with distorted system message section but user navigated to previous IOU details page in production after deleting request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/791035a8-229d-4f55-88b9-9696331c0fb6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ea5b468859985ff</li>
        <li>Upwork Job ID: 1778348288449794048</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102448064</li>
<li>ahmedGaber93 | Contributor | 102448065</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by izarutskaya** [comment] 2024-04-11 06:16
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-11 06:16
We think this issue might be related to the #vip-vsb.

**Comment by Julesssss** [comment] 2024-04-11 10:31
@Gonals this seems like enough of an edgecase to not block the deploy, do you agree?

**Comment by Gonals** [comment] 2024-04-11 21:40
> @Gonals this seems like enough of an edgecase to not block the deploy, do you agree?

Yeah, I'd say so

**Comment by jjcoffee** [comment] 2024-04-16 08:56
Waiting on proposals, have bumped on Slack!

**Comment by jjcoffee** [comment] 2024-04-19 08:11
Still waiting on proposals.

**Comment by jjcoffee** [comment] 2024-04-23 07:38
Still no proposals!

**Comment by jjcoffee** [comment] 2024-04-29 08:27
Hmm still no proposals, @anmurali do you think it's worth bumping the price on this to attract more proposals? Or is it too minor?

**Comment by jjcoffee** [comment] 2024-05-03 11:32
Just a heads up I'll be OOO next week, 6th-13th (I may have some time on the 6th). Feel free to reassign based on urgency and/or if proposals start rolling in!

**Comment by anmurali** [comment] 2024-05-06 20:49
Bumped up the price and rotated the C+ assignment

**Comment by ahmedGaber93** [comment] 2024-05-22 01:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU-After deleting request, hold request system message displayed distorted

### What is the root cause of that problem?
We display the `AnimatedEmptyStateBackground.tsx` in the first row in the flatlist see [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionItem.tsx#L787), so if the image move out the first row (expained why below), it will overlap on the next row/view, and because android not take care about z index if the views are not siblings, the image will overlap above on the next row/view, and because the images has transparent pixels it not full cover the next row/view and seem distorted.

<details>
<summary>60px overlap</summary>

![Screenshot_1716336202](https://github.com/Expensify/App/assets/41129870/9b055385-b503-48f8-873b-0cf0dcc2d9f3)

</details>


So the root cause here is two points:
 1. The current design behavior now is the background image bottom is overlapped 60px with the message/view in the same row (see image below), overlap is different between IMAGE_HEIGHT - VIEW_HEIGHT see [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/CONST.ts#L204-L206), the 60px is a static value, and if the message/view under the background is smaller than 60px the image will move out the row and overlap the next row like on MoneyReportView.tsx(this issue case), but the issue not appear on it because the wrapper view has style `styles.overflowHidden` see [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/ReportActionItem/MoneyReportView.tsx#L63C92-L63C113), but after we delete the IOU we use diffrent UI that don't have `styles.overflowHidden` see [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionItem.tsx#L786)

 2. the image background use rotation sensor which scale the image to 1.15X [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/AnimatedEmptyStateBackground.tsx#L42), this scale makes the image move out the row and overlap the next row, but it also not appear  because `styles.overflowHidden` or because the message/view under the background is more bigger than 60px and background not passed to the bottom edge of the first row

### What changes do you think we should make in order to solve the problem?
Add `styles.overflowHidden` to the UI that displayed when IOU deleting [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionItem.tsx#L786) to prevent the image overlap above on the next row like we do on UI before deleting [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/ReportActionItem/MoneyReportView.tsx#L63) 

### What alternative solutions did you explore? (Optional)
we can also beside the main soluation calculate VIEW_HEIGHT based on scale 1.15x like we do in [IMAGE_HEIGHT](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/AnimatedEmptyStateBackground.tsx#L42), by edit [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/styles/utils/index.ts#L798) to be
```javascript
// marginTop: emptyStateBackground.SMALL_SCREEN.VIEW_HEIGHT,
const overlay = IMAGE_HEIGHT - VIEW_HEIGHT = 60;
marginTop: emptyStateBackground.SMALL_SCREEN.IMAGE_HEIGHT  * 1.15 - overlay,
```
this will make the image dimensions is exactly the same row one, see below image(before/after)

<details>
<summary>before</summary>

![Screenshot_1716339978](https://github.com/Expensify/App/assets/41129870/a9dc7a50-78e7-4c1c-ad5a-b7fc3c525cfa)



</details>

<details>
<summary>after</summary>


![Screenshot_1716339916](https://github.com/Expensify/App/assets/41129870/6fc5d337-3623-4b58-a849-4d6c81fb0a8a)

</details>


We need also to edit task report as it has the same issue.

**Comment by ahmedGaber93** [comment] 2024-05-22 10:08
@dukenv0307 Thanks for your feedback.

My fix is to add `styles.overflowHidden` to the UI that displayed when IOU deleting [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionItem.tsx#L786) **like we do on UI before deleting** [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/ReportActionItem/MoneyReportView.tsx#L63). It works fine with me. Is this not work for you?

**Comment by ahmedGaber93** [comment] 2024-05-22 10:24
@dukenv0307 I don't understand why we will edit VIEW_HEIGHT to 180 as this not the current design, but any way overflow hidden will prevent any overlapping what ever VIEW_HEIGHT height.


https://github.com/Expensify/App/assets/41129870/0718a69b-27a4-49b4-b05a-128d87f083ca

**Comment by ahmedGaber93** [comment] 2024-05-22 10:36
@dukenv0307 I follow your steps here https://github.com/Expensify/App/issues/40078#issuecomment-2124455805

It works fine with me. 



https://github.com/Expensify/App/assets/41129870/3683086c-f034-404d-b2a9-875d4383db75

**Comment by ahmedGaber93** [comment] 2024-05-22 10:53
@dukenv0307 I try to fix the issue on one place (the current issue case) **_as sample of the fix_**, but we can apply the same fix on all places have the issue.

**Comment by VincentCorleone** [comment] 2024-05-23 08:47
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
After deleting request, hold request system message displayed distorted. Background Image covered message.
## What is the root cause of that problem?
zIndex only works on positioned elements.
## What changes do you think we should make in order to solve the problem?
modify
https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/components/InvertedFlatList/CellRendererComponent.tsx#L24
to
```typescript
{zIndex: -props.index, position: "relative"},
```

## What alternative solutions did you explore? (Optional)
none

**Comment by VincentCorleone** [comment] 2024-05-23 08:52
Contributor details
Your Expensify account email: 707119577@qq.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ed57881916ec1303

**Comment by VincentCorleone** [comment] 2024-05-24 07:44
> Current assignee @Gonals is eligible for the choreEngineerContributorManagement assigner, not assigning anyone new.

What does this mean? Does this mean that this issue does not accept new proposal anymore?

**Comment by ahmedGaber93** [comment] 2024-05-27 08:05
@dukenv0307 PR https://github.com/Expensify/App/pull/42629 is ready for review.

**Comment by anmurali** [comment] 2024-06-21 01:54
@dukenv0307 can you pls complete the BZ checklist. All offers are paid out.

**Comment by ahmedGaber93** [comment] 2024-06-21 10:05
@anmurali BZ checklist is completed by C+ @dukenv0307 here https://github.com/Expensify/App/issues/40078#issuecomment-2162080572, I don't know why we have two BZ checklist!

**Comment by ahmedGaber93** [comment] 2024-06-21 10:08
@anmurali I think we missed splitting contributor bounty between me and @VincentCorleone based on this https://github.com/Expensify/App/pull/42629#issuecomment-2148790185

**Comment by anmurali** [comment] 2024-06-26 03:34
@VincentCorleone - can you pls link me your Upwork profile? I will get you paid out and then close this issue. Sorry, I missed that comment up top.

**Comment by Gonals** [comment] 2024-07-05 14:37
@anmurali, how's payment going?

**Comment by anmurali** [comment] 2024-07-08 19:54
Ah, I paid @VincentCorleone a week ago. Forgot to close the issue.

**Closed by anmurali** 2024-07-08 19:54 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
