### ISSUE TITLE
IOS - Workspace - App is crashed when delete the Workspace offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13198] opened 2022-11-30 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Create a WS in Android app and delete it ( do it online and offline)
1. Launch the app in IOS with the same account
3. Tap on your avatar > Workspaces > Select a workspace or click New workspace.
4. Click the vertical ellipses menu > Delete workspace
5. Tap on your avatar > Workspaces > Select a workspace or click New workspace.
6. Go offline
7. Click the vertical ellipses menu > Delete workspace
8. If you can triage the crash, please try again steps 3-7

## Expected Result:
App is not crashed when delete the Workspace offline

## Actual Result:
App is crashed when delete the Workspace offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.34.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204871399-f344512a-8463-4775-8ae4-6e7b5627ce09.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-12-01 06:21
I think this might be related to this online/offline issue https://github.com/Expensify/App/issues/12775

@stitesExpensify could you give a buddy check?

**Comment by stitesExpensify** [comment] 2022-12-01 16:24
Hmm it's definitely very similar, but I think it's different than that issue because this isn't showing a "replay", this is the app actually crashing

**Comment by stitesExpensify** [comment] 2022-12-02 18:47
@kbecciv can you confirm this is still reproducible for you?

**Comment by stitesExpensify** [comment] 2022-12-05 19:24
Still trying to repro this

**Comment by Christinadobrzyn** [comment] 2022-12-06 03:44
I can't reproduce this but I don't really understand the steps and also, I'm not sure what this is solving - would this happen in the 'real world' or does this relate to something else?

**Comment by stitesExpensify** [comment] 2022-12-06 17:10
That being said, i'm going to close this since neither of us can reproduce it

**Closed by stitesExpensify** 2022-12-06 17:10 UTC
Labels: Daily, Bug

**Comment by kbecciv** [comment] 2022-12-07 21:09
@stitesExpensify Checking again with current build.

**Comment by kbecciv** [comment] 2022-12-07 21:14
Issue is not reproduced with build 1.2.36.2

https://user-images.githubusercontent.com/93399543/206297652-fbc10680-60b6-4225-820e-51358ccf8bda.MP4
