### ISSUE TITLE
[$250] Hold - Red dot for held expense disappears when approve the report partially

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52566] opened 2024-11-14 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5222741&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceapprover236@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions:

1. Login as the owner of the workspace.
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver

Steps:

1. As Employee submit 2 expenses on workspace chat
2. As Approver hold the first expense
3. As Approver approve the report partially
4. Take a look at the held expense on approvers side

## Expected Result:
Red dot should be present on the held expense

## Actual Result:
Red dot for held expense is lost and only reappears when refresh the page

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d7d9b827-6334-4576-9e6a-69ca0e99a12c
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857095206791026885</li>
        <li>Upwork Job ID: 1857095206791026885</li>
        <li>Last Price Increase: 2024-11-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by mkzie2** [comment] 2024-11-14 17:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Red dot for held expense is lost and only reappears when refresh the page

### What is the root cause of that problem?
When we put a transaction on hold, we don't add `showInReview` as `true` here

https://github.com/Expensify/App/blob/d5a7b499d3ba2074f5ad069ed27a043d029d7036/src/libs/actions/IOU.ts#L7715

Which causes `hasViolation` of this transaction to return `false` and no RBR is displayed. After we open the expense report, backend returns the hold violation of this transaction with `showInReview` as `true` then RBR appears
https://github.com/Expensify/App/blob/d5a7b499d3ba2074f5ad069ed27a043d029d7036/src/libs/TransactionUtils/index.ts#L870

### What changes do you think we should make in order to solve the problem?
We should add `showInReview: true` for new hold violation here

```
const newViolation = {name: CONST.VIOLATIONS.HOLD, type: CONST.VIOLATION_TYPES.VIOLATION, showInReview: true}; 

```
https://github.com/Expensify/App/blob/d5a7b499d3ba2074f5ad069ed27a043d029d7036/src/libs/actions/IOU.ts#L7715

### What alternative solutions did you explore? (Optional)

**Comment by iwiznia** [comment] 2024-11-14 18:00
Looking....

**Comment by iwiznia** [comment] 2024-11-14 18:28
I can't seem to reproduce this locally... when I do it I end up in the approved part of the report, not the held part.
I am also getting all kinds of weird behavior, so maybe it's something related to my tests

**Comment by mkzie2** [comment] 2024-11-14 18:37
> As Employee submit 2 expenses on workspace chat

@iwiznia To easier to reproduce, after the step above you can go offline and do the next steps.

**Comment by iwiznia** [comment] 2024-11-14 18:54
ok yeah updated my PR to handle this case too

**Comment by kavimuru** [comment] 2024-11-14 20:34
Not reproducible 

https://github.com/user-attachments/assets/98f7eb2e-bb75-4b78-a173-e7a948820883

**Comment by iwiznia** [comment] 2024-11-15 14:01
I think that's acceptable since violations don't work offline. Going to close this for now, reopen if you disagree.
cc @cead22 @pecanoro

**Comment by mkzie2** [comment] 2024-11-15 14:35
@iwiznia The hold violation is working offline, we add the hold violation in optimistic data when we put a transaction on hold here.

https://github.com/Expensify/App/blob/d5a7b499d3ba2074f5ad069ed27a043d029d7036/src/libs/actions/IOU.ts#L7715

**Comment by iwiznia** [comment] 2024-11-15 14:39
Ohhh thanks for that context! It seems we don't do that for the new report when approving it then.
@allgandalf can you take a look into that?

**Comment by mkzie2** [comment] 2024-11-15 18:40
@allgandalf What do you think about my proposal?

**Comment by alexpensify** [comment] 2024-11-29 21:40
@allgandalf - @iwiznia confirmed this is a regression. What's the plan here? Thanks for the update!

**Comment by alexpensify** [comment] 2024-12-03 20:20
Thank you!

**Comment by alexpensify** [comment] 2024-12-15 04:27
Closing - there has been no movement here.

## Heads up, I will be offline until Wednesday, December 18, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Closed by alexpensify** 2024-12-15 04:27 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
