### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000]  profile pic not show in suggestion list in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22194] opened 2023-07-04 16:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to offline mode
2. click on + icon and select new chat option
3. enter email and click on that
4. go to that chat
5. type @ and type email with whom you are chatting
## Expected Result: 
in suggestion list default profile pic should show
## Actual Result: 
in suggestion list default profile pic does not show

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/999f4164-589e-4619-b162-7faf5f39d684

https://github.com/Expensify/App/assets/43996225/886de797-4140-4dc4-acde-580173d1bf5b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688385002046289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128e2ad21fe85905d</li>
        <li>Upwork Job ID: 1676951592035852288</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-04 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Profile picture is not shown in mention list in offline mode

### What is the root cause of that problem?

We get user icon by this utility function
https://github.com/Expensify/App/blob/4eef8fe76051707963f650693f31ee1418c5b6b7/src/libs/UserUtils.js#L150

But above function wasn't used in getting mention list
https://github.com/Expensify/App/blob/4eef8fe76051707963f650693f31ee1418c5b6b7/src/pages/home/report/ReportActionCompose.js#L489

This is the root cause

### What changes do you think we should make in order to solve the problem?

We should use `UserUtils.getAvatar` function to get icon

Replace the line 489 with
```
        source: UserUtils.getAvatar(detail.avatar, detail.accountID),
```

This works as expected.


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2023-07-05 22:02
Interesting, I would have thought this would only be solved by image caching improvements. @Beamanator can you give me a sense check on that, please.

**Comment by Beamanator** [comment] 2023-07-06 09:15
@trjExpensify in both reproduction videos, I noticed we're only dealing with default avatars so nothing to do with image caching - it just looks like we're not correctly getting the default avatar image in that mention suggestion list

**Comment by trjExpensify** [comment] 2023-07-06 13:49
Cool, sounds good! 👍

**Comment by trjExpensify** [comment] 2023-07-10 10:37
Awaiting a proposal review by @aimane-chnaif!

**Comment by sophiepintoraetz** [comment] 2023-07-12 12:39
@Beamanator - can I also get a sense check on that your comment around 
>it just looks like we're not correctly getting the default avatar image in that mention suggestion list

and whether this would also resolve a similar [issue](https://github.com/Expensify/App/issues/22409) where the avatar in the mention list is not matching the avatar in the main profile?

**Comment by Beamanator** [comment] 2023-07-12 13:15
@sophiepintoraetz yeah they do look super related and ideally the fix for this one should incorporate the fix for the other one - a.k.a. I don't think it makes any sense to fix this one without also fixing the other one... Since they're so closely related to each other

**Comment by trjExpensify** [comment] 2023-07-12 14:08
Interesting, but aren't the custom profile images related to image caching?

**Comment by Beamanator** [comment] 2023-07-12 14:11
Ooh when I looked before i thought i saw we were talking about default avatars which aren't related to image caching - maybe i'm confused?

**Comment by trjExpensify** [comment] 2023-07-12 21:25
Oh, I see now. It's still the default avatar not a user's custom set avatar.

**Comment by s-alves10** [comment] 2023-07-13 12:09
I explained it in root cause section. Why should I mention it again?

**Comment by s-alves10** [comment] 2023-07-13 12:41
## Proposal
[Updated](https://github.com/Expensify/App/issues/22194#issuecomment-1620551031)

**Comment by s-alves10** [comment] 2023-07-13 18:11
@aimane-chnaif 

[PR](https://github.com/Expensify/App/pull/22830) is ready for review

**Comment by trjExpensify** [comment] 2023-07-26 12:21
👋 @aimane-chnaif can you get the checklist please so we can proceed to payments? 

In the meantime, confirming the payments as follows: 

- $250 to @gadhiyamanan for the bug report 
- $1,500 to @s-alves10 for the fix & #urgency bonus 
- $1,500 to @aimane-chnaif for the C+ review & #urgency bonus 

Note: Issue was assigned on the 13th, and C+ approved on the 14th. The delay until the 18th on internal review is on us, and no further changes were required to the PR following that PR approval, so applying the bonus!

**Comment by trjExpensify** [comment] 2023-07-27 13:57
Gotcha, but presumably we missed it for a reason. It might be beneficial for `@mentions` to have an offline test. CC: @puneetlath thoughts?

**Comment by trjExpensify** [comment] 2023-07-27 14:56
I see this one, but not offline: 

<img width="1275" alt="image" src="https://github.com/Expensify/App/assets/16232057/1423216d-4483-4142-966d-03fbdc4c4e4c">

**Comment by trjExpensify** [comment] 2023-07-31 10:04
Cool, I've created one for Applause [here](https://github.com/Expensify/Expensify/issues/304101).

**Comment by trjExpensify** [comment] 2023-07-31 10:06
Settled up with everyone, closing!

**Closed by trjExpensify** 2023-07-31 10:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
