### ISSUE TITLE
[HOLD for payment 2024-10-11] Search - Expenses are not highlighted when selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50046] opened 2024-10-02 10:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh300901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- There are at least two expenses submitted to the other user.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Select the expenses via checkbox.
4. Note that the selected expenses are not highlighted.
5. Go to Outstanding.
6. Select all expenses via checkbox.
7. Note that the report header for the group expenses is not highlighted.

## Expected Result:
The expenses will be highlighted when selected (production behavior).

## Actual Result:
In Step 4, the selected expenses in All tab are not highlighted.
In Step 7, the report header for the group expenses is not highlighted.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1f229126-a14a-42c6-960f-5accc4bb3638

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by IuliiaHerets** [comment] 2024-10-02 10:51
We think that this bug might be related to #wave-control

**Comment by nkdengineer** [comment] 2024-10-02 11:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 4, the selected expenses in All tab are not highlighted.
In Step 7, the report header for the group expenses is not highlighted.

### What is the root cause of that problem?

We override the focused background and selected background style [here](https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/components/SelectionList/Search/ReportListItem.tsx#L81) and [here](https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/components/SelectionList/Search/TransactionListItem.tsx#L33)

It's only applied when we hover over the report item.

### What changes do you think we should make in order to solve the problem?
We should move the style [here](https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/components/SelectionList/Search/ReportListItem.tsx#L81) and [here](https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/components/SelectionList/Search/TransactionListItem.tsx#L33) above the selected background and focused background style  [here](https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/components/SelectionList/Search/ReportListItem.tsx#L78) and [here](https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/components/SelectionList/Search/TransactionListItem.tsx#L30)



### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2024-10-02 13:04
Removing blocker label. I commented [here](https://github.com/Expensify/App/pull/49192#issuecomment-2388594381) and I'll await a response before moving forward.

**Comment by luacmartins** [comment] 2024-10-02 15:30
Thanks! @ishpaul777 will work on a PR to address this.

**Comment by ikevin127** [comment] 2024-10-02 17:03
♻️ Looking into this as I authored the alleged offending PR, will get back soon with confirmation and PR if it is indeed coming from https://github.com/Expensify/App/pull/49192.

**Comment by ikevin127** [comment] 2024-10-02 17:17
@luacmartins ✅ I confirm that this issue is indeed a regression of PR https://github.com/Expensify/App/pull/49192 and I'm working on a follow-up PR to fix it right now since this is still in the regression period.

**Comment by ikevin127** [comment] 2024-10-02 17:24
🟢 Sure, I can review since this is in the regression period and I think we'd like to keep it contained.

@ishpaul777 Sorry, didn't know you started working on the fix. This would've been my diff (added some comments for clarity), and I think your version with `styles.bgTransparent` is cleaner 👍 



```diff
diff --git a/src/components/SelectionList/Search/ReportListItem.tsx b/src/components/SelectionList/Search/ReportListItem.tsx
index ea36ba44ccc..df196a8d4e3 100644
--- a/src/components/SelectionList/Search/ReportListItem.tsx
+++ b/src/components/SelectionList/Search/ReportListItem.tsx
@@ -75,11 +75,13 @@ function ReportListItem<TItem extends ListItem>({
         styles.pv1half,
         styles.ph0,
         styles.overflowHidden,
-        item.isSelected && styles.activeComponentBG,
-        isFocused && styles.sidebarLinkActive,
-        // Removing some of the styles because they are added to the parent OpacityView via animatedHighlightStyle
+        // We unset backgroundColor and reset marginHorizontal because the styles
+        // are handled by parent OpacityView via animatedHighlightStyle
         {backgroundColor: 'unset'},
         styles.mh0,
+        // These should be at the end because otherwise the item won't highlight when selected
+        item.isSelected && styles.activeComponentBG,
+        isFocused && styles.sidebarLinkActive,
     ];
 
     const handleOnButtonPress = () => {
diff --git a/src/components/SelectionList/Search/TransactionListItem.tsx b/src/components/SelectionList/Search/TransactionListItem.tsx
index 39172711516..bd9fceb5a5c 100644
--- a/src/components/SelectionList/Search/TransactionListItem.tsx
+++ b/src/components/SelectionList/Search/TransactionListItem.tsx
@@ -27,11 +27,13 @@ function TransactionListItem<TItem extends ListItem>({
         styles.selectionListPressableItemWrapper,
         styles.pv3,
         styles.ph3,
-        item.isSelected && styles.activeComponentBG,
-        isFocused && styles.sidebarLinkActive,
-        // Removing some of the styles because they are added to the parent OpacityView via animatedHighlightStyle
+        // We unset backgroundColor and reset marginHorizontal because the styles
+        // are handled by parent OpacityView via animatedHighlightStyle
         {backgroundColor: 'unset'},
         styles.mh0,
+        // These should be at the end because otherwise the item won't highlight when selected
+        item.isSelected && styles.activeComponentBG,
+        isFocused && styles.sidebarLinkActive,
     ];
 
     const listItemWrapperStyle = [
 ```

**Comment by luacmartins** [comment] 2024-10-02 20:25
Thanks! I assigned you as reviewer @ikevin127

**Comment by ikevin127** [comment] 2024-10-04 22:43
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/49192.
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/49192/files#r1788391399.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Navigate to the Search page.
2. Select expenses via the checkbox.
3. Verify that the selected expenses are highlighted.
4. Go to Outstanding expenses.
5. Select all expenses via checkbox.
6. Verify that the report header for the expense group is highlighted.

Do we agree 👍 or 👎.

**Comment by Julesssss** [comment] 2024-10-08 10:50
I don't think we need a specific regression test for this small fix.

**Comment by Christinadobrzyn** [comment] 2024-10-09 08:08
Payouts due in a few days

- [ ] Contributor: $250 @ishpaul777 (Upwork offer - https://www.upwork.com/nx/wm/offer/104334781)
- [ ] Contributor+: $250 @ikevin127 (Upwork offer - https://www.upwork.com/nx/wm/workroom/38646509/overview)

Let me know if anything needs to be changed about the payment summary.

**Comment by Christinadobrzyn** [comment] 2024-10-14 01:45
Ah, okay. Thanks for letting me know, @ishpaul777. 

I closed the Upwork contracts for you and @ikevin127 without payment. No regression test based on this [comment](https://github.com/Expensify/App/issues/50046#issuecomment-2399512345). 

Closing this out as complete.

**Closed by Christinadobrzyn** 2024-10-14 01:45 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
