### ISSUE TITLE
[$500] Attachment - When opening Attachment deeplink, blank page displayed instead of hhm not here

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34453] opened 2024-01-12 17:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com
4. Copy the URL
5. Launch app
6. Login as any user who has no access to attachment
7. Tap on a report
8. Paste the link in compose
9. Send the message
10. Tap on the link

## Expected Result:
When opening Attachment deeplink, hhm not here page must be displayed

## Actual Result:
When opening Attachment deeplink, blank page displayed instead of hhm not here

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7ee5ef7f-f88c-45e9-8791-884016fff123

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b27b587d1226973c</li>
        <li>Upwork Job ID: 1745859115637157888</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-12 17:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 When opening Attachment deeplink, blank page displayed instead of hhm not here

### What is the root cause of that problem?
We haven't enclosed REportAttachement inside NotFoundPage
### What changes do you think we should make in order to solve the problem?

We should enclose it in NOtFoundPage
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-01-12 18:01
This seems like recent regression. Used to work before.
Anyone is able to find offending PR?

**Comment by situchan** [comment] 2024-01-12 19:21
Dupe of https://github.com/Expensify/App/issues/23374

**Comment by alitoshmatov** [comment] 2024-01-14 20:37
Thank you @situchan.

Confirmed it is a dupe of https://github.com/Expensify/App/issues/23374

We can close this issue @miljakljajic

**Comment by miljakljajic** [comment] 2024-01-22 14:26
Closing, thank you!

**Closed by miljakljajic** 2024-01-22 14:26 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
