### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] iOS - Categories - Offline indicator overlaps with home bar in Default spend categories page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51544] opened 2024-10-27 22:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch ND app
2. Go to workspace settings > Categories
3. Go offline
4. Tap Settings
5. Tap Airlines
6. Scroll down to dismiss the keyboard

## Expected Result:
Offline indicator will not overlap with home bar after dismissing the keyboard

## Actual Result:
Offline indicator overlaps with home bar briefly after dismissing the keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/af943413-04fd-4b42-accb-f28ada6f0ded

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850900545784411884</li>
        <li>Upwork Job ID: 1850900545784411884</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104697028</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by bernhardoj** [comment] 2024-10-28 04:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Offline indicator overlaps with the iOS home bar briefly after closing keyboard.

### What is the root cause of that problem?
The category selector page uses a Modal and inside the modal, we have a padding bottom added to avoid the home bar overlapping. But, if a keyboard is shown, we won't apply the padding-bottom.
https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/components/Modal/BaseModal.tsx#L196

It was added to fix this [issue](https://github.com/Expensify/App/issues/33712) where there is an extra space at the bottom when the keyboard is shown, so they apply the padding-bottom only if the keyboard is closed. So, in this issue, when the keyboard opens, the padding-bottom isn't applied and when we close the keyboard, the offline indicator will overlap with the home bar for a while until the keyboard state changes to "closed".

### What changes do you think we should make in order to solve the problem?

Applying the padding-bottom conditionally based on the keyboard state is only needed when the keyboard-avoiding view is enabled. If it's disabled, then the modal content won't be pushed above the keyboard, so we won't see the padding-bottom either. So, the first solution is to always apply the padding-bottom if the keyboard avoiding view is disabled.

```
shouldAddBottomSafeAreaPadding: (!avoidKeyboard || !keyboardStateContextValue?.isKeyboardShown) && shouldAddBottomSafeAreaPadding,
```

`avoidKeyboard` is disabled by default.
https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/components/Modal/BaseModal.tsx#L47

And because we don't need to avoid keyboard for the category selector modal, we can just disable it from the ScreenWrapper too.
https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/pages/workspace/distanceRates/CategorySelector/CategorySelectorModal.tsx#L33-L48

```
shouldEnableKeyboardAvoidingView={false}
```

### What alternative solutions did you explore? (Optional)
Wrap the children with SafeAreaView and remove the manual safe area padding calculation.
https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/components/Modal/BaseModal.tsx#L188-L203
https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/components/Modal/BaseModal.tsx#L272-L277
`<SafeAreaView style={styles.flex1}>`

**Comment by isabelastisser** [comment] 2024-10-28 14:28
@muttmuure, does this issue belong to [[#whatsnext] #quality](https://github.com/orgs/Expensify/projects/71)?

**Comment by bernhardoj** [comment] 2024-11-02 04:22
PR is ready

cc: @dukenv0307

**Comment by isabelastisser** [comment] 2024-11-04 21:30
Bump @dukenv0307 for PR review. Thanks!

**Comment by bernhardoj** [comment] 2024-11-17 08:58
Requested in ND.

**Comment by isabelastisser** [comment] 2024-11-18 20:14
Payment summary:

@bernhardoj requires payment through NewDot Manual Requests $250 C+
@dukenv0307 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104697028) (Reviewer) Paid in Upwork.

**Closed by isabelastisser** 2024-11-18 20:14 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-11-21 11:01
$250 approved for @bernhardoj
