### ISSUE TITLE
[$250] mweb-chat-Unable to type in compose box

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42523] opened 2024-05-23 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4569546
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open any report
3. Type random letters in compose
## Expected Result:
User must be able to type in compose.
## Actual Result:
User unable to type in compose. Compose is not functioning properly.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [X] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d5ad9fac-ae92-4e15-8718-b61254d87c4e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @SzymczakJ</details>

**Comment by m-natarajan** [comment] 2024-05-23 13:57
@adelekennedy FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-23 13:58
We think that this bug might be related to  #vip-vsb

**Comment by amyevans** [comment] 2024-05-23 16:05
I'm unable to reproduce:

https://github.com/Expensify/App/assets/7277067/20bcea32-9eab-475b-bac9-5add9ee89389

@adelekennedy can you give it a try?

**Comment by samilabud** [comment] 2024-05-23 16:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mweb-chat-Unable to type in compose box

### What is the root cause of that problem?
It seems the new module "@expensify/react-native-live-markdown" is the root cause, when we pass it through our RNMarkDownTextInput component (`markdownStyle={markdownStyle}`):

https://github.com/Expensify/App/blob/84290e42da3794c621b792725222a8d7c16664b6/src/components/Composer/index.tsx#L324-L332

### What changes do you think we should make in order to solve the problem?
As the @expensify/react-native-live-markdown component is out of our control (externals) I suggest marking it as internal, meanwhile we can use the [RNMarkDownTextInput](https://github.com/Expensify/App/blob/84290e42da3794c621b792725222a8d7c16664b6/src/components/Composer/index.tsx) without the new markdown styles, like:

```
<RNMarkdownTextInput
                autoComplete="off"
                autoCorrect={!Browser.isMobileSafari()}
                placeholderTextColor={theme.placeholderText}
                ref={(el) => (textInput.current = el)}
                selection={selection}
                style={[inputStyleMemo]}
                value={value}
                defaultValue={defaultValue}
                autoFocus={autoFocus}
                /* eslint-disable-next-line react/jsx-props-no-spreading */
                {...props}
                onSelectionChange={addCursorPositionToSelectionChange}
                onContentSizeChange={(e) => {
                    setTextInputWidth(`${e.nativeEvent.contentSize.width}px`);
                    updateIsFullComposerAvailable({maxLines, isComposerFullSize, isDisabled, setIsFullComposerAvailable}, e, styles);
                }}
                disabled={isDisabled}
                onKeyPress={handleKeyPress}
                onFocus={(e) => {
                    ReportActionComposeFocusManager.onComposerFocus(() => {
                        if (!textInput.current) {
                            return;
                        }

                        textInput.current.focus();
                    });

                    props.onFocus?.(e);
                }}
            />
```

Test after changes:

https://github.com/Expensify/App/assets/5216036/907609eb-3687-4ac7-971f-793668f63057

**Comment by adelekennedy** [comment] 2024-05-23 18:09
@amyevans I also can't reproduce

**Comment by amyevans** [comment] 2024-05-23 18:53
Asked about it in #qa: https://expensify.slack.com/archives/C9YU7BX5M/p1716490376842399

**Comment by kavimuru** [comment] 2024-05-23 19:26
@amyevans Reproduced with certain devices only. 

Issue reproducible on: Galaxy S10+ / Andriod 12,  Fold 4 / Android 14(repro with samsung keyboard only and not with Gboard), Galaxy S10 / Android 11, Samsung Galaxy A50/Android11, Xiaomi Redmi Note 10S - Android 13

Not reproducible on Pixel devices

**Comment by amyevans** [comment] 2024-05-23 19:44
> As the @expensify/react-native-live-markdown component is out of our control (externals)

We do have some control, it's our open source repo 😄 

@robertKozik would you be able to help look into this further?

**Comment by robertKozik** [comment] 2024-05-24 14:16
Sadly I won't be able to help for now, but I'll pass it to my colleagues which are involved in  `react-native-live-markdown`

**Comment by amyevans** [comment] 2024-05-24 14:16
Thanks!

**Comment by amyevans** [comment] 2024-05-24 15:46
Some discussion here: https://expensify.slack.com/archives/C06BDSWLDPB/p1716559779115879

**Comment by amyevans** [comment] 2024-05-24 15:47
Opening it up to external proposals to see if anyone is able to suggest a useful solution over the weekend!

**Comment by amyevans** [comment] 2024-05-24 22:05
The revert was cherry-picked and I requested a retest from QA here: https://expensify.slack.com/archives/C9YU7BX5M/p1716588309012709?thread_ts=1716490376.842399&cid=C9YU7BX5M

**Comment by jjcoffee** [comment] 2024-05-27 14:04
Unassigning as no C+ required here (and no payment).

**Comment by SzymczakJ** [comment] 2024-05-28 08:57
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by rlinoz** [comment] 2024-05-29 23:40
Should I close the other issue since we reverted that PR? Also, maybe @mollfpr should be the C+ here as a regression?

**Comment by amyevans** [comment] 2024-05-30 01:57
> Should I close the other issue since we reverted that PR?

Let's keep it open for now just to ensure its criteria is satisfied once a new PR is opened?

> Also, maybe @mollfpr should be the C+ here as a regression?

Sounds good, assigning!

**Comment by SzymczakJ** [comment] 2024-06-04 14:21
Update: We need to wait for react-native-live-markdown fix to be merged. I've put out a PR with that fix https://github.com/Expensify/react-native-live-markdown/pull/366. When the fix is merged I will reapply changes that Robert Kozik made, that were solving [this room mentions issue](https://github.com/Expensify/App/issues/41597), as they will no longer cause this "unable to type in compose box" bug. I think you can also assign me to that [room mentions issue](https://github.com/Expensify/App/issues/41597).

**Comment by amyevans** [comment] 2024-06-04 14:24
Okay thanks for the update! Can you comment on that GH, I'm unable to assign otherwise

**Comment by SzymczakJ** [comment] 2024-06-06 14:28
Update: we are still waiting to merge this fix in react-native-live-markdown https://github.com/Expensify/react-native-live-markdown/pull/366, I'm pinging `react-native-live-markdown` team to merge this fix ASAP 😄

**Comment by amyevans** [comment] 2024-06-10 13:49
👍

**Closed by amyevans** 2024-06-10 13:49 UTC
Labels: Reviewing, Engineering, Weekly, Bug
