### ISSUE TITLE
[$250] Track expense - Report View Briefly Displayed for Single Expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46361] opened 2024-07-27 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. In self DM, click the plus sign > Track Expense
2. Add an amount and confirm it
3. In the message whisper, select "Submit to Someone."
4. Select an email, confirm it, and go to IOU
5. Notice that the total amount is briefly shown

## Expected Result:
The Report view should be displayed only if there are two or more expenses

## Actual Result:
When submitting a single expense from self DM, the Report view is briefly displayed in the IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f1b9ea1a-b2db-420e-9d9b-eb988c1273ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018828788ef868888b</li>
        <li>Upwork Job ID: 1818281786440610970</li>
        <li>Last Price Increase: 2024-08-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-07-27 16:08
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-27 16:08
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-07-30 13:44
More context on the current status of the VSB project:

https://expensify.slack.com/archives/C066HJM2CAZ/p1721760866963099?thread_ts=1721729395.916419&cid=C066HJM2CAZ

**Comment by JKobrynski** [comment] 2024-08-08 12:15
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by isabelastisser** [comment] 2024-08-08 14:42
I assigned you @JKobrynski. Thanks!

**Comment by JKobrynski** [comment] 2024-08-12 14:47
@fedirjh I found a fix, going to post a proposal with detailed explanation tomorrow morning!

**Comment by JKobrynski** [comment] 2024-08-13 10:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report view is briefly displayed for single expense

### What is the root cause of that problem?

The reason behind it is this part of `ReportActionItemContentCreated.tsx`

```tsx
const [transaction] = useOnyx(`${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID ?? '-1'}`);

const transactionCurrency = TransactionUtils.getCurrency(transaction);
```

Initially, there is no `transactionID` and there is a fallback to `-1`. Because of that, the `transaction` object from `useOnyx` is undefined. That value is passed to `TransactionUtils.getCurrency` which returns **USD** by default (even if the object is undefined). So basically, if you are using any currency other than **USD** (I used **PLN** in my testing) the component is going to be "wrong" for a brief moment. It's going to return USD by default, until the actual `transactionID` (not -1 fallback) is available. Then it's going to return **EUR**, **PLN** or whatever currency was used for that transaction.

The problem explained above doesn't directly cause the issue though, it causes it indirectly through this line in the same file (props passed to `<MoneyReportView/>`):

```tsx
shouldShowTotal={transactionCurrency !== report.currency}
```

The report view is rendered is **shouldShowTotal** is `true`, and it's always going to be `true` for a brief moment if a currency other than **USD** was used. 

For example, as mentioned above I used **PLN** and my initial `transactionID` (as always) was undefined, so `TransactionUtils.getCurrency` returned **USD**, and therefore the comparison for `shouldShowTotal` was true (Report View was displayed) until there was a `transactionID` available, then `TransactionUtils.getCurrency` returned **PLN** and the comparison was false (Report View disappeared).

### What changes do you think we should make in order to solve the problem?


I would add an additional check to the line with `shouldShowTotal` to verify if `transaction` is available, if not, it should always fallback to `false`.

### What alternative solutions did you explore? (Optional)

None

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by isabelastisser** [comment] 2024-09-06 19:45
Hey @thienlnam, can you please review the approved proposal above? thanks!

**Comment by thienlnam** [comment] 2024-09-06 20:46
Ah the PR has already been merged. Looks like it deployed a few weeks ago so we should be good to create QA steps and then pay this out

**Comment by isabelastisser** [comment] 2024-09-09 18:59
Payment automation didn't work, reviewing this now.

**Comment by isabelastisser** [comment] 2024-09-09 19:01
Payment summary:

@fedirjh, $250 for C+ review. Payment via NetDot.

**Comment by isabelastisser** [comment] 2024-09-09 19:04
all set!

**Closed by isabelastisser** 2024-09-09 19:04 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-23 10:19
$250 approved for @fedirjh
