### ISSUE TITLE
[$500]  IOU/LHN - IOU not been pinned by default 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31403] opened 2023-11-15 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed in
1. Open app
2. Create IOU money request with any user
3. Navigate back to LHN
4. Observe the IOU report position in LHN and its icons

## Expected Result:

Step 4: Transaction thread report is pinned by default

## Actual Result:

Step 4: Transaction thread report isn't pinned by default

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/02ee1e05-17a3-4d1d-b1e0-22c8751cdb10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159bd7d65d5681c02</li>
        <li>Upwork Job ID: 1724881721908154368</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28037472</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by lanitochka17** [comment] 2023-11-15 20:07
Test Rail: https://expensify.testrail.io/index.php?/tests/view/3974494&group_by=cases:section_id&group_order=asc&group_id=229063

**Comment by raphaelppp** [comment] 2023-11-15 20:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When requesting money in a conversation, the latter should be pinned.

### What is the root cause of that problem?
IOU.requestMoney does not pin the report.

### What changes do you think we should make in order to solve the problem?
I added the following line to IOU.requestMoney : 
```    
Report.notifyNewAction(chatReport.reportID, payeeAccountID);
```

**Comment by riqts** [comment] 2023-11-15 21:20
[Please re-state the problem that we are trying to solve in this issue.]

The problem is that the IOU request is not automatically pinning the conversation after it is made

[What is the root cause of that problem?]

Essentially the togglePinnedState is not being called in the current IOU.js  RequestMoney function.

```
Report.togglePinnedState(chatReport.reportID, false);
```


[What changes do you think we should make in order to solve the problem?]

Incorporating a Report.TogglePin on the already existing IOU.RequsetMoney function should return this to normalcy

[What alternative solutions did you explore? (Optional)]
Alternatively the actual backend for the requestMoney could perform a similar action and just handle this but this may be this may not be the most simple, predictable and trackable solution in the current setup

**Comment by riqts** [comment] 2023-11-15 21:22
Contributor details
Your Expensify account email: jacksonbrummell1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014853d868137150b0

**Comment by s-alves10** [comment] 2023-11-15 23:34
This looks like a backend issue. IOU details report should have `isPinned: true` when creating, but it isn't now

**Comment by bfitzexpensify** [comment] 2023-11-20 22:04
Few proposals ready for you to review @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-11-21 18:31
Sorry @bfitzexpensify Not sure how I missed this. I've unassigned newly assigned issues due to low bandwidth somehow missed it. If any C+ can review this immediately please Reassign. Otherwise I can look into this tomorrow.

**Comment by bfitzexpensify** [comment] 2023-11-21 21:39
All good! Tomorrow is fine.

**Comment by Santhosh-Sellavel** [comment] 2023-11-23 13:42
Sorry again for the delay here

I'm confused here about Expected Result.


> Step 4: created IOU report should be pinned by default in LHN as mentioned in the TestRail case steps

Are you referring to each IOU Request thread should be pinned.  Can you share me test rail link/ID

> Steps 7 and 11: the pinned option should not be displayed in the context menu on IOU report details page

**Comment by lanitochka17** [comment] 2023-11-28 17:10
@Santhosh-Sellavel 
Test Rail: https://expensify.testrail.io/index.php?/tests/view/3974494&group_by=cases:section_id&group_order=asc&group_id=229063

**Comment by Santhosh-Sellavel** [comment] 2023-12-01 17:48
Thanks for the test rail. @lanitochka17 was this test passing earlier, when it got added. 

@bfitzexpensify Can you check and provide us clear expected OP. From test rail I found this internal issue link https://github.com/Expensify/Expensify/issues/298942 but I don't have access to this was this a regression if so please provide more details from which issue this got added, thanks!

**Comment by bfitzexpensify** [comment] 2023-12-01 18:36
@Santhosh-Sellavel OK, these are the TestRail steps:

1. Create a IOU (or use an existing IOU conversation)
2. Verify that IOU conversations (reports) are always pinned by default in the LHN
3. Right-click on the IOU conversation (the one with a green dot) in the LHN
4. Verify that there is no pin option on the context Menu

So @dukenv0307's identified issues [here](https://github.com/Expensify/App/issues/31403#issuecomment-1813766985) are correct:

1. Transaction thread report isn't pinned by default
2. Transaction thread report has pin option

Does that help clarify things? I also updated the actual/expected behaviours in the OP.

**Comment by bfitzexpensify** [comment] 2023-12-01 19:47
Pinned always, so it shouldn't be possible to unpin

**Comment by bfitzexpensify** [comment] 2023-12-04 22:45
Sorry to come in with this now @Santhosh-Sellavel @dukenv0307 - after chatting in Slack, we've decided the following:

- Transaction thread report should be pinned by default (this is the same)
- Transaction thread should be unpinnable (this is new)

Basically, we need to fix only one of the two bugs here - the ability to unpin the IOU should remain as it is now (so we'll want to update Step 4 of the existing TestRail thread

**Comment by Santhosh-Sellavel** [comment] 2023-12-06 11:48
Yeah, right!

**Comment by bfitzexpensify** [comment] 2023-12-06 12:37
Cool, so it sounds like we need both a BE and FE change. Does the order of those changes matter?

**Comment by bfitzexpensify** [comment] 2023-12-06 13:56
Sweet. OK, @neil-marcellini just tagging you so you're aware of the need for BE changes too - is that something you have the capacity to take on?

**Comment by neil-marcellini** [comment] 2023-12-08 18:04
@bfitzexpensify thanks for the tag. I have 4 or 5 issues that are higher priority than this, but I can work it in if needed. Would you please help me out by updating the description with simple tests steps and the updated expected and actual results? I'm not really clear on it yet.

**Comment by Santhosh-Sellavel** [comment] 2023-12-14 19:04
@neil-marcellini Should we wait for BE or let's go head test and merge FE?

**Comment by Santhosh-Sellavel** [comment] 2023-12-18 18:10
Cool, then I too think the same @dukenv0307 

> I think we should wait for BE to complete the final testing.

@neil-marcellini When can we expect BE changes?

**Comment by Santhosh-Sellavel** [comment] 2023-12-25 19:15
bump @neil-marcellini

**Comment by Santhosh-Sellavel** [comment] 2024-01-10 15:27
@bfitzexpensify / @neil-marcellini  bump on the BE changes here

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 17:15
Any update @neil-marcellini / @bfitzexpensify

**Comment by neil-marcellini** [comment] 2024-02-06 22:43
Hi guys, I finally checked my mentions lol. Sorry for the delay! I was never assigned, so I have been totally unaware of this until now. Please don't hesitate to DM me in the future. Any way, I'll take a look.

**Comment by neil-marcellini** [comment] 2024-02-07 19:55
I'm checking on the priority of this issue in [Slack here](https://expensify.slack.com/archives/C03U7DCU4/p1707335658702659)

**Comment by bfitzexpensify** [comment] 2024-02-07 23:55
Hey @lanitochka17 - can you clarify which test case this issue was identified from? After chatting in Slack, we don't believe this is actually an issue, and we'd like to update whichever test this is originating from.

**Comment by lanitochka17** [comment] 2024-02-08 14:56
@bfitzexpensify Hello
TR https://expensify.testrail.io/index.php?/tests/view/3974494&group_by=cases:section_id&group_order=asc&group_id=229063

**Closed** 2024-02-09 00:26 UTC
Labels: Engineering, Weekly, Internal, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-02-09 15:41
@bfitzexpensify Before a hiring decision was made, these were the inputs we got here in https://github.com/Expensify/App/issues/31403#issuecomment-1836594930, not sure where got mixed was the testrail updated?

> @Santhosh-Sellavel OK, these are the TestRail steps:
> 
> 1. Create a IOU (or use an existing IOU conversation)
> 2. Verify that IOU conversations (reports) are always pinned by default in the LHN
> 3. Right-click on the IOU conversation (the one with a green dot) in the LHN
> 4. Verify that there is no pin option on the context Menu
> 
> So @dukenv0307's identified issues [here](https://github.com/Expensify/App/issues/31403#issuecomment-1813766985) are correct:
> 
> 1. Transaction thread report isn't pinned by default
> 2. Transaction thread report has pin option
> 
> Does that help clarify things? I also updated the actual/expected behaviours in the OP.

I think this qualifies for payment, as most work is done.

**Comment by bfitzexpensify** [comment] 2024-02-11 22:24
@Santhosh-Sellavel I can't see the TestRail history but the current TR step, which is:

>Verify that IOU conversations (reports) are NOT pinned by default in the LHN

Differs from step 2 I'd listed above in that comment:

>Verify that IOU conversations (reports) are always pinned by default in the LHN

So, the expected behaviour was updated, and therefore this issue is no longer an issue. 

Agree that this qualifies for partial payment (at 50%) due to the work already completed.

**Comment by bfitzexpensify** [comment] 2024-02-11 22:24
Payment summary: 

Contributor: @dukenv0307 to be paid $250 via Upwork ✅ 
C+: @Santhosh-Sellavel to be paid $250 via manual request

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 17:47
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-05-31 04:29
$250 approved for @Santhosh-Sellavel
