### ISSUE TITLE
mWeb - Keyboard dismiss after input wrong the magic code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21845] opened 2023-06-28 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to login page
2. Input an email => Continue
3. Input the invalid magic code
4. Click into first code
5. Input the number

## Expected Result:
Keyboard not dismissed after re-entering the first few numbers

## Actual Result:
 Keyboard is dismissed after re-entering the first few numbers

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/231b8974-6be2-4820-83a4-625f7b43eee8

https://github.com/Expensify/App/assets/93399543/d493fd8b-2a71-4860-9c71-02faeaa94653

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687915048896069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-06-30 20:32
Discussing [this internally](https://expensify.slack.com/archives/C048ZLJ78P5/p1688156994867829). I can reproduce, but am not sure this is a bug.

**Comment by joekaufmanexpensify** [comment] 2023-06-30 21:04
Discussed in the above slack thread and confirmed this is not a bug. We allow editing in place, so a user can correct if they miskey a digit in the code. As soon as the code hits 6 digits entered, we attempt to login again and close the keyboard (which is consistent with the original login attempt). This includes if one digit in the code is edited in place. 

Whereas if the user removes the code entirely, we only dismiss keyboard once they hit 6 digits entered again.

**Comment by joekaufmanexpensify** [comment] 2023-06-30 21:04
Closing as this is not a bug!

**Closed by joekaufmanexpensify** 2023-06-30 21:04 UTC
Labels: Daily, Bug
