### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] [SelectionList refactor] [Wave Collect] Extract checkbox design and placing outside the BaseListItem component to specific list item components.

### ISSUE THREAD

**Issue by burczu** [Expensify/App#38222] opened 2024-03-13 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

Coming from this issue: https://github.com/Expensify/App/issues/35717 and discussed it [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1710332452771549).

We recently refactored the `SelectionList` component extracting list item components like `UserListItem`, `RadioListItem` and `TableListItem` and asking the parent component to decide which list item component should be used by the `SelectionList`. There is also a `BaseListItem` component used by all of these newly extracted item components that holds some common part of the code. 

Unfortunately this component still encapsulate how the checkbox used in the list item looks like and where it's placed, so the goal of this issue is to extract defining checkbox outside the `BaseListItem` and move this responsibility to specific list item components.
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7cfec47d64461f0</li>
        <li>Upwork Job ID: 1767895235204546560</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by burczu** [comment] 2024-03-13 13:02
Just to inform: I'll be able to start working on this once I've fished my other assignments in the Simplified collect project - most likely this Friday or Monday next week.

**Comment by mountiny** [comment] 2024-03-13 23:08
@shubham1206agra since @burczu is already working on some other wave collect task today and on Friday, would you fancy handling this task too given you have context?

**Comment by trjExpensify** [comment] 2024-03-21 10:49
👋 @burczu looks like there's a question for you here: https://github.com/Expensify/App/pull/38448#discussion_r1532017308

**Comment by trjExpensify** [comment] 2024-03-21 21:26
Thanks!

**Comment by DylanDylann** [comment] 2024-03-27 08:03
I can take over as C+

**Comment by mountiny** [comment] 2024-04-08 13:09
$250 to both @shubham1206agra and @DylanDylann

**Comment by Christinadobrzyn** [comment] 2024-04-11 03:04
Prepping payouts. 

- [ ] Contributor+: $250 @shubham1206agra (Upwork offer - https://www.upwork.com/ab/applicants/1767895235204546560/offers)
- [ ] Contributor+: $250 @DylanDylann (Upwork offer - https://www.upwork.com/nx/wm/workroom/36842418/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01e7cfec47d64461f0).

**Comment by Christinadobrzyn** [comment] 2024-04-16 00:44
Paid @DylanDylann based on this payment summary - https://github.com/Expensify/App/issues/38222#issuecomment-2048851262

Waiting for @shubham1206agra to accept the Upwork offer

@DylanDylann do we need a regression test?

**Comment by DylanDylann** [comment] 2024-04-16 02:31
@Christinadobrzyn I don't think we need a regression test for this issue because this is a refactor task

**Comment by Christinadobrzyn** [comment] 2024-04-17 07:18
DM'd @shubham1206agra about the upwork offer

**Comment by Christinadobrzyn** [comment] 2024-04-17 07:55
Awesome! Paid this out based on this payment summary - https://github.com/Expensify/App/issues/38222#issuecomment-2048851262

closing - let me know if I missed anything!

**Closed by Christinadobrzyn** 2024-04-17 07:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
