### ISSUE TITLE
[HOLD for payment 2024-11-11] Remove GBR from the account settings on initial signup

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#47863] opened 2024-08-22 13:59 UTC
Based on the discussion here:https://expensify.slack.com/archives/C07HPDRELLD/p1724334488573109?thread_ts=1724252245.683699&cid=C07HPDRELLD, we've decided to remove the GBR from the account settings that direct users to validate their login.
<img width="1677" alt="Screenshot 2024-08-22 at 7 29 17 PM" src="https://github.com/user-attachments/assets/c88b3a60-2f3f-40cf-a9a0-6ccb735a0757">

## Problem 
This step is an unnecessary diversion during the initial onboarding setup. 
<img width="178" alt="Screenshot 2024-08-22 at 7 29 10 PM" src="https://github.com/user-attachments/assets/7ac5d6e7-b155-4787-bc83-2a2fc600a19a">
Account validation is only required for setting up 2FA and for wallet and bank account-related processes, where we have the validation path integrated into those specific flows.

## Solution
Remove the GBR from the account settings that users encounter when signing up on NewDot.

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by bernhardoj** [comment] 2024-08-22 14:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We don't want to show the GBR for new unvalidated user.

### What is the root cause of that problem?
The GBR will show if the brick road indicator is returned from `getLoginListBrickRoadIndicator`.
https://github.com/Expensify/App/blob/ed04ac47da2194e279d4a4a6225280f755148bda/src/pages/settings/Profile/ProfilePage.tsx#L71

There are 2 cases. 1 if there is an error which will show the RBR.
https://github.com/Expensify/App/blob/ed04ac47da2194e279d4a4a6225280f755148bda/src/libs/UserUtils.ts#L56-L63

And the other one if one of the contact methods is not validated yet which will show the GBR.
https://github.com/Expensify/App/blob/ed04ac47da2194e279d4a4a6225280f755148bda/src/libs/UserUtils.ts#L48-L50

### What changes do you think we should make in order to solve the problem?

We can remove the validated status check here, so GBR won't show if there is a non-validated contact method.
https://github.com/Expensify/App/blob/ed04ac47da2194e279d4a4a6225280f755148bda/src/libs/UserUtils.ts#L60-L62

login A: validated
login B: non-validated

Before:
GBR shows

After:
No GBR

OR

We can modify `hasLoginListInfo` to always return false if the login list is only 1, otherwise, use the current logic.

**Comment by FitseTLT** [comment] 2024-08-23 13:05
>seems like a simple problem,

@ntdiary Yeah it is a simple and straightforward problem with simple fix that's why I am giving clear simple proposal I don't know why you are not selecting my proposal which was the first.
@techievivek

**Comment by techievivek** [comment] 2024-08-28 09:06
That's a good question. I'm not entirely sure what the expected behavior should be. On the one hand, since the user's primary login still needs to be verified, it doesn't make sense to display the GBR to direct the user to verify another login, as verifying this login would make it their primary login. However, on the other hand, we might still want to show the GBR because the user has voluntarily added this login method and may want to validate it.

CC @JmillsExpensify @danielrvidal for thoughts on the above.

**Comment by danielrvidal** [comment] 2024-08-28 18:39
If someone adds a secondary login I think it makes sense to add the GBR to all the logins so they know they need to verify them. By that chance, they are taking actions to use us, and thus, we're not as worried about making sure they only see GBRs for onboarding. Curious if @JmillsExpensify agrees on that one?

**Comment by techievivek** [comment] 2024-09-02 04:28
Not overdue, reached out to Jason for his thoughts on above point.

**Comment by techievivek** [comment] 2024-09-02 15:18
Ok, thanks for confirming the behavior here. @ntdiary we should be good to move forward now.

**Comment by techievivek** [comment] 2024-09-09 17:05
> Then, to summarize, if I understand correctly, when the user signs up for the first time, we want all four GBRs in the image below to be removed. And if the user explicitly adds a second contact method, these four GBRs will be shown, right? 😄 (or more precisely, there will be five because of the two contact methods)

Yes, we only want to remove the GBR during the initial signup. Once the user starts exploring the app and adding things explicitly, it should function as normal.

**Comment by techievivek** [comment] 2024-09-10 13:52
@Krishna2323 Assigned the GH to you, can you get started with the PR?

**Comment by techievivek** [comment] 2024-09-25 06:20
Looks like we haven't made a progress for a while here, any updates?

**Comment by JmillsExpensify** [comment] 2024-11-19 10:54
Offer sent.

**Comment by JmillsExpensify** [comment] 2024-11-19 10:57
All paid out. Thanks everyone! Pending NewDot payment can be requested, so I'm closing this one out.

**Closed by JmillsExpensify** 2024-11-19 10:57 UTC
Labels: External, Weekly, Awaiting Payment, Bug
