### ISSUE TITLE
[HOLD for payment 2023-01-30] [$1000] Pencil icon does not disappear for the archived room if the WS is deleted from another device

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14260] opened 2023-01-12 23:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Create a workspace from web
2. Go to the announce room for that workspace
3. Type something in the composer
4. Open mobile app and sign in with same user
5. Delete the workspace from mobile app

## Expected Result:
Pencil icon should not be shown in LHN for achived room
## Actual Result:
Pencil icon is shown and the archived room stays on top even if it is not pinned

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212202855-a76498d7-0d11-46e1-a97a-82ad608ab0d8.mov

https://user-images.githubusercontent.com/43996225/212202872-c769fef6-cadb-492e-9342-76a91a4594ae.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673534519355329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a953d4382d33bf3</li>
        <li>Upwork Job ID: 1613958629505818624</li>
        <li>Last Price Increase: 2023-01-13</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-01-13 17:48
Reviewing this now.

**Comment by isabelastisser** [comment] 2023-01-13 17:58
I can reproduce this.

**Comment by situchan** [comment] 2023-01-13 18:05
### **Proposal**
https://github.com/Expensify/App/blob/main/src/components/LHNOptionsList/OptionRowLHN.js
```diff
-                           {optionItem.hasDraftComment && (
+                           {optionItem.hasDraftComment && !optionItem.isArchivedRoom && (
                                <View
                                    style={styles.ml2}
                                    accessibilityLabel={props.translate('sidebarScreen.draftedMessage')}
                                >
                                    <Icon src={Expensicons.Pencil} height={16} width={16} />
                                </View>
                            )}
```

**Comment by Prince-Mendiratta** [comment] 2023-01-13 18:09
# Proposal
## RCA
This issue occurs because we do not check for room archive status in the display of icons. Thus, allowing for the icon to show up. This can be very annoying since there is no real way to get rid of the icon since you cannot remove the draft comment.

## Solution 1

Hide the icon from being displayed if the room has been archived.
```diff
diff --git a/src/components/LHNOptionsList/OptionRowLHN.js b/src/components/LHNOptionsList/OptionRowLHN.js
index e64ed774b8..805c5b3485 100644
--- a/src/components/LHNOptionsList/OptionRowLHN.js
+++ b/src/components/LHNOptionsList/OptionRowLHN.js
@@ -215,7 +215,7 @@ const OptionRowLHN = (props) => {
                             style={[styles.flexRow, styles.alignItemsCenter]}
                             accessible={false}
                         >
-                            {optionItem.hasDraftComment && (
+                            {!optionItem.isArchivedRoom && optionItem.hasDraftComment && (
                                 <View
                                     style={styles.ml2}
                                     accessibilityLabel={props.translate('sidebarScreen.draftedMessage')}
```

## Solution 2
When the workspace is deleted, remove the draft comment from Onyx keys as well for that report.

**Comment by abdulrahuman5196** [comment] 2023-01-13 18:11
**Proposal**
            Issue is due to the fact that isDraft field in Onyx would still be set to 'true' as Pusher event doesn't reset it. This field is kept as a local field to support draft comments.
            
            **Solution 1 Best IMO**
            We can check if the room is archived before showing it in UI. Along with this issue we can notice that the archived room is present at the top instead of going to bottom along with Archived chats. I have added code diff for both.
            ```diff
            --- a/src/libs/SidebarUtils.js
            +++ b/src/libs/SidebarUtils.js
            @@ -134,13 +134,14 @@ function getOrderedReportIDs(reportIDFromRoute) {
                         return;
                     }
             
            -        if (report.hasDraft) {
            -            draftReports.push(report);
            +        // To fix archived message at top issue
            +        if (ReportUtils.isArchivedRoom(report)) {
            +            archivedReports.push(report);
                         return;
                     }
             
            -        if (ReportUtils.isArchivedRoom(report)) {
            -            archivedReports.push(report);
            +        if (report.hasDraft) {
            +            draftReports.push(report);
                         return;
                     }
             
            @@ -229,7 +230,8 @@ function getOptionData(reportID) {
                 result.ownerEmail = report.ownerEmail;
                 result.reportID = report.reportID;
                 result.isUnread = ReportUtils.isUnread(report);
            -    result.hasDraftComment = report.hasDraft;
            +    // To stop showing pencil icon in the list
            +    result.hasDraftComment = result.isArchivedRoom ? false : report.hasDraft;
                 result.isPinned = report.isPinned;
                 result.iouReportID = report.iouReportID;
                 result.keyForList = String(report.reportID);
            ```
            
            **Solution 2**
            We can start sending 'hasDraft: false' value from server on workspace delete event. Not sure on this as currently we consider hasDraft to be local device state.
            
            **Solution 3**
            We can reset onyx data by calling 'setReportWithDraft' and 'saveReportComment' with reset values when we see room is archived but report has 'hasDraft' to be true. One advantage is we reset the draft comment data from onyx well. Even server can send data to reset draft comment as well similar to solution 2.

**Comment by hungvu193** [comment] 2023-01-13 18:18
<b>Proposal<b/>
I think we need to add the condition we only show the pencil icon if it this room has draft and it's not archived.
I have an alternative solution that we can edit the `getOptionData` function to make an archived room will never has draft.

```diff
diff --git a/src/libs/SidebarUtils.js b/src/libs/SidebarUtils.js
index 9e6e1ed75..22c731eb0 100644
--- a/src/libs/SidebarUtils.js
+++ b/src/libs/SidebarUtils.js
@@ -215,12 +215,13 @@ function getOptionData(reportID) {
         shouldShowSubscript: false,
         isPolicyExpenseChat: false,
     };
+    const isArchiveRoom = ReportUtils.isChatRoom(report);
 
     const participantPersonalDetailList = _.values(OptionsListUtils.getPersonalDetailsForLogins(report.participants, personalDetails));
     const personalDetail = participantPersonalDetailList[0] || {};
 
     result.isChatRoom = ReportUtils.isChatRoom(report);
-    result.isArchivedRoom = ReportUtils.isArchivedRoom(report);
+    result.isArchivedRoom = isArchiveRoom;
     result.isPolicyExpenseChat = ReportUtils.isPolicyExpenseChat(report);
     result.shouldShowSubscript = result.isPolicyExpenseChat && !report.isOwnPolicyExpenseChat && !result.isArchivedRoom;
     result.pendingAction = report.pendingFields ? (report.pendingFields.addWorkspaceRoom || report.pendingFields.createChat) : null;
@@ -229,7 +230,7 @@ function getOptionData(reportID) {
     result.ownerEmail = report.ownerEmail;
     result.reportID = report.reportID;
     result.isUnread = ReportUtils.isUnread(report);
-    result.hasDraftComment = report.hasDraft;
+    result.hasDraftComment = !isArchiveRoom && report.hasDraft;
     result.isPinned = report.isPinned;
     result.iouReportID = report.iouReportID;
     result.keyForList = String(report.reportID);

```

**Comment by tgolen** [comment] 2023-01-13 20:51
Wow, 7 proposals 😬 Let me look through these.

@situchan you had the first proposal, but you didn't follow the guidelines about posting an explanation of why the problem is occurring. Please be sure to include that on future proposals!

For the rest of the solutions, we should _not_ tie the visibility of the icon to the status of the report. The icon should only be tied to the `hasDraft` data. Linking the display of the icon to any other data is just confusing and eventually makes an unmanageable mess of the logic. 

Therefore, the only proposal that I think solves this properly is @abdulrahuman5196 proposal 2: set `hasDraft: false` from the server when deleting a workspace. @abdulrahuman5196 would you please provide a more thorough proposal for this case? What about the case where the second application is not currently connected to Pusher? Is setting `hasDraft: false` in Onyx all that is required or is there other local in-memory stuff happening around the draft which also needs to be cleaned up?

**Comment by abdulrahuman5196** [comment] 2023-01-13 23:40
Hi, @tgolen.
Currently when draft comment is added. We set 2 local values one hasDraft flag and the other actual draft comment with these below methods

https://github.com/Expensify/App/blob/f06b625880c963840d4c46eafadd1af0cdffd21c/src/libs/actions/Report.js#L567-L587

Both of these values need to be reset in onyx when we delete the workspace. The draft comment value inside onyx poses no issue if 'hasDraft' is disabled currently(as we check for hasDraft before using draft comment), but still would be best to clean up both as a best practice.

**Now to server solution**
The user can get the information of workspace deleted only through 2 ways in this case.
1) Pusher event
2) Refresh information through fetch API's when user moves to appropriate screens like 'OpenReport'. (I assume 'ReconnectApp' or 'OpenApp' also return report data, just saying as example can provide exact data) 

---
1) Pusher event
Currently we get pusher events similar to this when a workspace is deleted

>[{"onyxMethod":"merge","key":"report_4955522883611843","value":{"statusNum":2,"stateNum":2,"oldPolicyName":"Abdulrahu5196+1's Workspace 2"}},{"onyxMethod":"merge","key":"reportActions_4955522883611843","value":{"1":{"person":[{"type":"TEXT","style":"strong","text":"abdulrahu5196+1@gmail.com"}],"actorEmail":"abdulrahu5196+1@gmail.com","actorAccountID":14244652,"message":[{"type":"TEXT","style":"strong","text":"You"},{"type":"TEXT","style":"normal","text":" closed this report"}],"originalMessage":{"policyName":"Abdulrahu5196+1's Workspace 2","reason":"policyDeleted"},"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_6.png","created":"2023-01-13 21:18:58.247","timestamp":1673644738,"reportActionTimestamp":1673644738247,"automatic":false,"sequenceNumber":1,"actionName":"CLOSED","shouldShow":true,"clientID":"","reportActionID":"8124289965024451587"}}}]

We can return 'hasDefault: false' in the 'report_4955522883611843' to reset the flag and another 'merge' value in pusher array to reset the draft comment added via this line. Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}`, comment); 


**What about the case where the second application is not currently connected to Pusher?**
I don't think this might be an issue here, as the pusher event of workspace deletion itself wouldn't even reached the device in this case, so draft comment poses no treat. Leaving aside the hasDraft issue also, If pusher is failing we would only refresh the workspace delete state through mechanism 2 mentioned above during user actions. (I assume we don't have a retry mechanism for pusher in server, backend folks can correct me)


2) Refresh through fetcher API's
Here we would be required to send 'hasDefault: false' in the API response along with another 'merge' value to reset draft comment similar to what we do in pusher.  But the drawback to this is, in fetcher API we would be wastefully sending 'merge' for this '${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}` key to reset draft comment as we can't be sure if in mobile has draft comment or not without any hacky solutions(Not a big drawback in my opinion though as its just a key with empty value)

I think resetting the draft values at onyx would solve the core problem.

**Comment by tgolen** [comment] 2023-01-14 00:37
@abdulrahuman5196 that's excellent, thanks! Makes a lot of sense and I agree that both `hasDraft` and the draft comment should be removed if possible. I see that [here](https://github.com/Expensify/App/blob/188816d1e12bf462b54f90446c706df0e0fb2c88/src/libs/actions/Policy.js#L644) we are clearing `hasDraft` on the client making the request, but it is not clearing the draft comment. I wonder if that is also a mistake that we should fix? Someone on our side (maybe @aldo-expensify?) can help out with the server changes to the pusher events.

**Comment by abdulrahuman5196** [comment] 2023-01-14 10:03
>I see that [here](https://github.com/Expensify/App/blob/188816d1e12bf462b54f90446c706df0e0fb2c88/src/libs/actions/Policy.js#L644) we are clearing hasDraft on the client making the request, but it is not clearing the draft comment. I wonder if that is also a mistake that we should fix?

Just to note adding solution for client making request won't change the behavior/solution of this particular bug on secondary device. (Disclaimer lol)
Ultimately the pusher/API refresh will clear the hasDraft and draft comment data in the onyx on the client if we implement the server solution discussed above. But I agree, it should be better to clear the data through optimisticData and reverted with failureData if required on client making request as a good practice to close the loop on draft comment stale data

@tgolen , So the answer to your above question is 'Yes'. And its not just that place alone, we have to clear the draft comment data at multiple other instances as well when the workspace is deleted and similar scenarios. For example

1. We have to remove the draft comment at failure Data for 'CreateWorkspace' - [here](https://github.com/Expensify/App/blob/188816d1e12bf462b54f90446c706df0e0fb2c88/src/libs/actions/Policy.js#L702)
2. We have to remove the draft comment at optimisticData and set the opposite in failureData of 'DeleteWorkspace' - [here](https://github.com/Expensify/App/blob/188816d1e12bf462b54f90446c706df0e0fb2c88/src/libs/actions/Policy.js#L63)
3. As pointed out we would also need to remove the draft comment at 'RemoveWorkspace' as well - [here](https://github.com/Expensify/App/blob/188816d1e12bf462b54f90446c706df0e0fb2c88/src/libs/actions/Policy.js#L644)
4. And another place is we call saveReportComment with empty string incase of draft comment to be removed, but we can also set it to null, so that the actual key itself is removed from onyx as a good faith solution.


I can check and remove at other places as well if any found as part of this change. I would be happy to make these as well part of the draft issue.

But just a suggestion, I agree the client side clean-up of draft data is required, but should we track that change as part of this bug?, I think both poses as separate issue although the cause is same. As this client side clean up of data doesn't change/improve the behavior of secondary device focused on this issue. I think we can take it up as a separate issue and fix it there as different testing also would be required for primary device initiating the request and secondary device issue. But I am still fine to make the changes as part of this bug itself if required.

**Comment by abdulrahuman5196** [comment] 2023-01-14 18:00
@s77rt  That was my proposal 3 mentioned here
>We can reset onyx data by calling 'setReportWithDraft' and 'saveReportComment' with reset values when we see room is archived but report has 'hasDraft' to be true

The sample Pseudo code for that would be,

```
//Find if the chat has been archived via any mechanism
if (isArchivedChat(report)) && report.hasDraft == true {
    //clear onyx data related to draft like calling 'setReportWithDraft' and 'saveReportComment' with reset values or calling directly
}
```
This can be done from multiple places like OnyxListener, PusherListener, API response or UI place as well, but in any place you would end up doing a code like the above pseudo code. Or a somewhat similar code to the above.
There are couple of disadvantages with this approach that's why i called it out as a 3rd proposal. That is what we are trying to avoid by not tying one information with another, if tying one information with another is fine, we can just use the UI based proposals.

It's not straightforward as mentioned in the above code change. We are now end up tying policy information with the report draft status, which is more coupling data than the proposals which had UI level filter. The data flow in this case would be like this

1) Workspace delete information passed to device ------> 2) Device sets the information in Onyx -----> 3) We listen to onyx change events -----> 4) We now know that the onyx data is not completely reset 4) We get the policy id -----> 5) Find appropriate reportId -----> 6) Reset the data which was not properly reset on step1.

Instead of doing all these steps if server responds with proper data in step 1 itself, we could avoid all other computations.
And another Just my opinion, I think it's fine to start thinking draft as server value as well because at some future point expensify might be required to show the draft in multiple devices with same login similar to slack(We can raise a new feature request if not already present)

And another important point to note is there there where 2 different clean ups discussed, one on the primary device initiating the deleteworkspace request and the other on the secondary device which gets notified on deletion.
For primary device we don't even need to do all these steps as it knows that the data is about to wiped and it should clean relevant data as proposed [here](https://github.com/Expensify/App/issues/14260#issuecomment-1382705073)

And to clarify on another point, I didn't callout client_is_typing data previously because it gets reset automatically after 1.5s. And I also thought about "Why do we even need 2 data to determine if a report is draft or not in first place, won't just draft comment be enough" but it will end up making the logic more complex in the chat list and report page as hasDraft flag is updated only when user starts typing or draft is removed, but draft comment is updated for every key typed by user.

**Comment by s77rt** [comment] 2023-01-14 18:29
@abdulrahuman5196 Sorry your proposal 3 is not clear enough and without code it's hard to tell what you meant exactly, we can call the reset functions as you mentioned from anywhere but it's important to know from where and that's the key difference.

Personally, I'm not okay with dragging the server down with client issues.

As with my proposed solution, we are not strictly coupling the data as the UI solution, we are only doing so with the clean up and that's a good compromise I would say.

**Comment by tgolen** [comment] 2023-01-17 15:30
There are a few things that I like about @s77rt's proposal:

- I like that it doesn't involve the server for something that is only client-side
- It accounts for any number of reports on a workspace

Regarding the use of `Onyx.update()`, it's still going to trigger `n` calls to merge and set (`n` is number of reports) and I think the better approach would be to craft three Onyx commands. One `mergeCollection()` and two `multiSet()`. This would be the most performant way of doing a batch update like this.

@abdulrahuman5196 I appreciate you looking into that draft cleanup on the frontend, and I agree with you that it is a separate issue than this one, so we can remove that discussion for now.

**Comment by s77rt** [comment] 2023-01-17 15:33
@tgolen That's a great idea, that way we will do only 2 calls. I will update the proposal.

**Comment by s77rt** [comment] 2023-01-17 15:49
### Proposal (Updated)
```diff
diff --git a/src/libs/ReportUtils.js b/src/libs/ReportUtils.js
index 6e54ce74b5..37c0a371c1 100644
--- a/src/libs/ReportUtils.js
+++ b/src/libs/ReportUtils.js
@@ -1175,6 +1175,15 @@ function getChatByParticipants(newParticipantList) {
     });
 }
 
+/**
+ * Get policy reports
+ * @param {String} policyID
+ * @returns {Array}
+ */
+function getPolicyReports(policyID) {
+    return _.filter(allReports, report => report && report.policyID === policyID);
+}
+
 /**
 * Returns true if Chronos is one of the chat participants (1:1)
 * @param {Object} report
@@ -1249,6 +1258,7 @@ export {
     buildOptimisticReportAction,
     shouldReportBeInOptionList,
     getChatByParticipants,
+    getPolicyReports,
     getIOUReportActionMessage,
     getDisplayNameForParticipant,
     isIOUReport,
diff --git a/src/libs/actions/Policy.js b/src/libs/actions/Policy.js
index 403523bcbb..2ac3580faf 100644
--- a/src/libs/actions/Policy.js
+++ b/src/libs/actions/Policy.js
@@ -22,8 +22,17 @@ Onyx.connect({
         if (!key) {
             return;
         }
-
         if (val === null || val === undefined) {
+            const policyID = key.replace(ONYXKEYS.COLLECTION.POLICY, '');
+            const policyReports = ReportUtils.getPolicyReports(policyID);
+            const cleanUpMergeQueries = {};
+            const cleanUpSetQueries = {};
+            _.each(policyReports, ({reportID}) => {
+                cleanUpMergeQueries[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`] = {hasDraft: false};
+                cleanUpSetQueries[`${ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT}${reportID}`] = null;
+            });
+            Onyx.mergeCollection(ONYXKEYS.COLLECTION.REPORT, cleanUpMergeQueries);
+            Onyx.multiSet(cleanUpSetQueries);
             delete allPolicies[key];
             return;
         }
```

### Update
Optimised the onyx calls cleanup

**Comment by isabelastisser** [comment] 2023-01-17 17:23
@tgolen, please let me know which proposal you want to move forward with, and I will hire the contributor in Upwork. Thanks!

**Comment by tgolen** [comment] 2023-01-17 18:04
That looks great, @s77rt. Thanks for the updated proposal. 🟢 on hiring @s77rt for this one @isabelastisser

**Comment by isabelastisser** [comment] 2023-01-17 18:44
Update: 

- Hired @s77rt in Upwork.

**Comment by s77rt** [comment] 2023-01-17 19:04
@tgolen How should we handle the test screenshots in this case?

**Comment by tgolen** [comment] 2023-01-17 21:31
I think you could basically just show a screenshot of the pencil icon no longer being displayed.

**Comment by tgolen** [comment] 2023-01-17 22:07
OK, got it. I think the "second device" can just be a chrome incognito window for every test (this is the one where you delete the workspace).

**Comment by s77rt** [comment] 2023-01-17 22:13
Applied in [Upwork](https://www.upwork.com/jobs/~013a953d4382d33bf3).
[PR](https://github.com/Expensify/App/pull/14379) is ready.

**Comment by isabelastisser** [comment] 2023-01-30 19:54
Update: the contributors were paid in Upwork.

Reported by @adeel0202 
Fixed by: @s77rt

**Comment by isabelastisser** [comment] 2023-01-30 20:05
@rushatgabhane , I sent you an offer in Upwork, please accept it and I will issue the payment ASAP. Thanks!

**Comment by isabelastisser** [comment] 2023-01-30 21:44
Regression test discussion in Slack can be found [here.](https://expensify.slack.com/archives/C01SKUP7QR0/p1675115025394399)

**Comment by isabelastisser** [comment] 2023-01-30 22:24
@rushatgabhane paid in Upwork.

**Closed** 2023-02-06 20:01 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug
