### ISSUE TITLE
[$500] Pin - Pinned chat returns to unpin status when returning online after reload

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31733] opened 2023-11-22 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New expensify app
2. Go offline
3. Pin any chat from LHN
4. Kill the app
5. Go online
6. Open the app

## Expected Result:
Pinned chat in offline mode should remain pin status when come back online

## Actual Result:
Pinned chat returns to unpin status when returning online after reload

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0e0c3bd6-27ce-4d7b-836e-6b6aedf0046d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4741938b029e9bc</li>
        <li>Upwork Job ID: 1727385703560392704</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by akamefi202** [comment] 2023-11-22 18:48
Same RCA with https://github.com/Expensify/App/issues/23891

**Comment by erquhart** [comment] 2023-11-22 19:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Pinning, unpinning, and other offline actions are not persisted if there is a reload while offline.

### What is the root cause of that problem?

`persistedRequests` is being mutated from outside of the `save()` method in `PersistedRequests`:
https://github.com/Expensify/App/blob/405269a838d034ced6ccdd5e9c4be0af92cfe9b7/src/libs/actions/PersistedRequests.ts#L21-L32

This is a regression introduced in #30425, it affects pretty much all offline persisted requests.

### What changes do you think we should make in order to solve the problem?

Make a local copy of `persistedRequests` within the `save()` function to ensure outside mutations don't have impact.

**Comment by erquhart** [comment] 2023-11-22 19:16
@akamefi202 this is different, regression from #28172.

**Comment by WojtekBoman** [comment] 2023-11-22 19:43
Hi, I've already proposed this solution [here](https://github.com/Expensify/App/pull/30425#issuecomment-1823090209). I am waiting for @roryabraham response

**Comment by luacmartins** [comment] 2023-11-22 19:59
@WojtekBoman I commented on that issue, but I still see an error in the CloseAccount case

**Comment by luacmartins** [comment] 2023-11-27 17:11
Agree. Closing issue.

**Closed by luacmartins** 2023-11-27 17:11 UTC
Labels: External, Daily, Help Wanted, Bug
