### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Arrow key shortcut stops working

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#19700] opened 2023-05-26 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from: https://github.com/Expensify/App/pull/18883/files#r1206010822

## Action Performed:

1. Open the panel to invite new members to a workspace (/workspace/<workspace id>/invite)
2. Verify that arrows up and down work and they change the selected row
3. Select something with the mouse
4. Click Next
5. Go back
7. BUG: The arrow keys don't change the highlighted row anymore

## Expected Result:
Pressing UP or DOWN should change the highlighted row

## Actual Result:
Pressing UP or DOWN doesn't do anything

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ecaf4548dae58200</li>
        <li>Upwork Job ID: 1668438254258597888</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2023-05-26 21:37
The cause is pretty narrowed down here:
- https://github.com/Expensify/App/pull/18883/files#r1206010822
- https://github.com/Expensify/App/pull/18883/files#r1205951089

I think this would have been easier to fix if we were dealing with functional components. There out of the box memoization with Class components. The recommended way is to use the library `memoize-one` which we don't currently have, and I'm not sure we want it since we are moving toward functional components.

**Comment by johncschuster** [comment] 2023-05-30 12:15
FYI - No Slack thread for this one.

**Comment by aldo-expensify** [comment] 2023-05-30 17:16
Also, Vit was recommending me to get help from one of our external expert agencies to work on this ([here](https://github.com/Expensify/App/pull/18883/files#r1209132113)). I think that could be a good idea.

**Comment by roryabraham** [comment] 2023-06-01 22:40
Looking into this now

**Comment by roryabraham** [comment] 2023-06-01 23:01
I'm not sure I yet see how this is related to https://github.com/Expensify/App/pull/18883, because the `OptionsSelector` doesn't yet use the `useArrowKeyFocusManager` or `useKeyboardShortcut` hooks.

**Comment by roryabraham** [comment] 2023-06-01 23:12
Found [this lib](https://github.com/JohannesKlauss/react-hotkeys-hook) which honestly seems pretty slick

**Comment by aldo-expensify** [comment] 2023-06-01 23:13
- `PopoverMenu` subscribe shortcuts globally using `useArrowKeyFocusManager` and `useKeyboardShortcut`
- `BaseOptionsSelector` subscribes globally `ARROW UP` and `ARROW DOWN` keys using `ArrowKeyFocusManager` ([here](https://github.com/Expensify/App/blob/933264afbc0f2285cf905a0767b75472721cf537/src/components/OptionsSelector/BaseOptionsSelector.js#L330-L335))
- In the past, `PopoverMenu` subscribed shortcuts before `BaseOptionsSelector`'s subscribed shortcuts, just because of mounting order. This made the `BaseOptionsSelector`'s callback execute first.
- Since the change introduced by https://github.com/Expensify/App/pull/18883, `PopoverMenu` is constantly unsubscribing and subscribing the shortcuts, moving the callback to the front of any other with the same priority thanks to the way we insert the callback [here](https://github.com/Expensify/App/blob/933264afbc0f2285cf905a0767b75472721cf537/src/libs/KeyboardShortcut/index.js#L126-L127) (slice).
- When the callback subscribed by `PopoverMenu` executes first, it doesn't give a chance to `BaseOptionsSelector`'s callback to execute because it prevents bubbling `shouldBubble = false` (default [here](https://github.com/Expensify/App/blob/933264afbc0f2285cf905a0767b75472721cf537/src/hooks/useKeyboardShortcut.js#L12))

I'm pretty sure you could fix this particular bug by playing with the priorities with the callback, but I still think this should be fix in a way it stops unsubscribing/subscribing every cycle.

**Comment by aldo-expensify** [comment] 2023-06-01 23:15
> Found [this lib](https://github.com/JohannesKlauss/react-hotkeys-hook) which honestly seems pretty slick

Interesting, the focus trap thing could help solving the problem we have with key event listeners that keep listening even out of view (see https://expensify.slack.com/archives/C01GTK53T8Q/p1685138015892469 / https://github.com/Expensify/App/issues/18419)

**Comment by roryabraham** [comment] 2023-06-01 23:19
This seems like the exact scenario the upcoming `React.useEvent` hook is designed for.

**Comment by aldo-expensify** [comment] 2023-06-01 23:25
> This seems like the exact scenario the upcoming `React.useEvent` hook is designed for.

In only found this: https://github.com/reactjs/rfcs/pull/220

Is this going to be implemented? Looks good, but I think for the moment, if that is not near to be released, this can be done with `useCallback` + `useMemo` in functional react. In class components is hard I believe.

**Comment by roryabraham** [comment] 2023-06-01 23:26
Yeah, it's just an RFC now, and we should be able to simulate it.

**Comment by roryabraham** [comment] 2023-06-02 00:12
Put up a draft PR with a potential fix: https://github.com/Expensify/App/pull/20016. More testing and discussion is needed since it uses an experimental React feature which is explained in good detail here: https://react.dev/learn/separating-events-from-effects#declaring-an-event-function

**Comment by johncschuster** [comment] 2023-06-05 15:51
PR is being worked on, Melv. Chill.

**Comment by roryabraham** [comment] 2023-06-07 20:31
I haven't made any progress on the PR, been tied down with deploy chores. Considering making this external, but if we need to use a new React hook to fix it then we need a slack convo first

**Comment by johncschuster** [comment] 2023-06-12 11:30
This is being solved internally, Melv. Chill

**Comment by gedu** [comment] 2023-06-13 13:35
## Proposal
### Please restate the problem that we are trying to solve in this issue.
The issue occurs when the user selects an item from the OptionList, moves to a next screen, and then returns. Upon returning, the arrow key selection (UP and DOWN) stops working in the PopoverMenu component.
To reproduce:
Open the panel to invite new members to a workspace (/workspace//invite).
Verify that arrow keys (UP and DOWN) work and change the selected row.
Select an item using the mouse.
Click “Next.”
Go back to the previous screen.
BUG: The arrow keys no longer change the highlighted row.

## What is the root cause of this problem?
The issue stems from a conflict between the keyboard subscription in the PopoverMenu component (which also re-renders multiple times) and the useKeyboardShortcut hook. Initially, when entering the Workspace invite members page, the keyboard subscription is handled by the ArrowKeyFocusManager in the componentDidMount event, occurring after the PopoverMenu subscription. This initial setup works fine. However, upon leaving the screen and returning, the PopoverMenu subscribes again, even though it is not currently visible. Consequently, when the Workspace page becomes visible again, the componentDidMount event is not fired, and the last subscription from the PopoverMenu remains active.

### What changes do you propose to solve the problem?
To resolve the issue, we need to modify the implementation of the PopoverMenu component. The PopoverMenu component uses the useArrowKeyFocusManager, which internally uses the useKeyboardShortcut hook. Currently, the PopoverMenu does not pass information about whether it is active or not to the useArrowKeyFocusManager, causing it to always subscribe to keyboard shortcuts. To address this, we can add an “isActive” prop to the useArrowKeyFocusManager, which will indicate whether the menu is currently active or not. This prop can be derived from the “props.isVisible” value.
On top of this, I would add the suggestion and cleanups from @aldo-expensify

**Comment by roryabraham** [comment] 2023-06-13 18:12
Ok, I think that makes sense. Thanks for the explanation @gedu 🙇🏼

**Comment by Santhosh-Sellavel** [comment] 2023-06-13 21:44
I'll just wait for the PR then, thanks for the early review @roryabraham!

**Comment by gedu** [comment] 2023-06-14 13:39
@roryabraham @aldo-expensify Hey, while I was adding the `isActive` and doing the cleanup, I noticed that the `useArrowKeyFocusManager` function has an unstable type for the disabledIndexes parameter, which is `disabledIndexes = [].` This causes any hook that uses this parameter to be recreated every time.

I was improving the callback for `useKeyboardShortcut` so the `useEffect` doesn't get called everytime. but if I do this

```
 const arrowUpCallback = useCallback(() => {
        if (maxIndex < 0) {
            return;
        }

        setFocusedIndex((index) => {
            const currentFocusedIndex = index > 0 ? index - 1 : maxIndex;
            let newFocusedIndex = currentFocusedIndex;

            while (disabledIndexes.includes(newFocusedIndex)) {
                newFocusedIndex = newFocusedIndex > 0 ? newFocusedIndex - 1 : maxIndex;
                if (newFocusedIndex === currentFocusedIndex) {
                    // all indexes are disabled
                    return index; // no-op
                }
            }
            return newFocusedIndex;
        });
    }, [disabledIndexes, maxIndex]);
    useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.ARROW_UP, arrowUpCallback, arrowConfig);
    ```
    because `disabledIndexes` always is a new array the function will be recreating calling again the `useEffect`, chatting internally I think the best option is to create a const array and use it, in this case, is good because we just query the value, doing this we avoid that when other use this hook they don't need to use `useMemo` and pass always an array.
    
    ```
    const EMPTY_ARRAY = Object.freeze([]);
    
    function useArrowKeyFocusManager({
    maxIndex,
    onFocusedIndexChange = () => {},
    initialFocusedIndex = 0,
    disabledIndexes = EMPTY_ARRAY,
    shouldExcludeTextAreaNodes = true,
    isActive,
}) {}
```

Doing `freeze` so if someone tries to mutate the array get an error, because at least for now we don't want to support that behavior.

I want to point this out because as we start using hooks, these issues could arise in many places.

What do you think?

Before
<img width="337" alt="Screen Shot 2023-06-14 at 15 37 46" src="https://github.com/Expensify/App/assets/1676818/5e0e4291-852e-4fe4-8c84-d3a2429eb005">

After
<img width="309" alt="Screen Shot 2023-06-14 at 15 38 13" src="https://github.com/Expensify/App/assets/1676818/277053ba-4635-4b74-b425-dc720e039509">

**Comment by chrispader** [comment] 2023-06-19 12:42
The `isActive` addition would also come in handy [in this PR](https://github.com/Expensify/App/pull/18648), since we want to be able to use the `useArrowKeyFocusManager` for two different contexts (emojis and suggestions), and being able to `disable` a keyboard shortcut subscription temporarily, would be great

**Comment by roryabraham** [comment] 2023-06-29 23:33
I think this is ready for payment now

**Comment by Santhosh-Sellavel** [comment] 2023-07-02 22:10
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18883 
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: Already pointed out by @aldo-expensify in th issue description https://github.com/Expensify/App/pull/18883/files#r1206010822
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Should have been caught with our checklist.
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug.
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@johncschuster] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Santhosh-Sellavel** [comment] 2023-07-02 22:11
### Regression Steps 
1. Open the panel to invite new members to a workspace (/workspace//invite)
2. Verify that arrows up and down works and the selected row is changed 
3. Select something with the mouse
4. Click Next
5. Go back
6. The arrow keys change the highlighted row

👍  or 👎 

cc: @roryabraham @johncschuster

**Comment by anmurali** [comment] 2023-07-07 11:55
Paid

**Comment by johncschuster** [comment] 2023-07-07 14:37
Thanks, @anmurali!

**Comment by roryabraham** [comment] 2023-07-08 06:34
Then, since @gedu works for Callstack, we are all set to close this 🎉

**Closed by roryabraham** 2023-07-08 06:34 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
