### ISSUE TITLE
[HOLD for payment 2024-09-10] [$250] iOS - Composer - Add attachment modal is hidden behind the keyboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48452] opened 2024-09-03 11:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Focus on the composer (important)
4. Tap +
5. Tap Add attachment

## Expected Result:
Add attachment modal will not be hidden behind the keyboard

## Actual Result:
Add attachment modal is hidden behind the keyboard

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dcc06c05-1d90-4a66-a5bc-bd1d16108a74

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01929e53bf6e5a45ee</li>
        <li>Upwork Job ID: 1831044805586591004</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103803636</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by danieldoglas** [comment] 2024-09-03 18:41
It looks like a glitch; I can't simulate that after several tries.

https://github.com/user-attachments/assets/8d2fd8ea-f754-4a1c-8750-8cd6248e97e4

**Comment by roryabraham** [comment] 2024-09-03 18:47
@danieldoglas looks like you're testing on iOS web, not iOS native

**Comment by danieldoglas** [comment] 2024-09-03 19:01
This is not happening in production, so we need to check what happened.

**Comment by danieldoglas** [comment] 2024-09-03 20:52
@ishpaul777 can you spin up a PR for that?

**Comment by situchan** [comment] 2024-09-03 21:22
Looks like regression from https://github.com/Expensify/App/pull/47991

**Comment by roryabraham** [comment] 2024-09-03 22:18
cherry-picking the fix here: https://github.com/Expensify/App/actions/runs/10691504641

**Comment by roryabraham** [comment] 2024-09-03 22:57
Verified this is fixed on staging ✅

**Comment by danieldoglas** [comment] 2024-09-04 03:07
Removing @parasharrajat

**Comment by stephanieelliott** [comment] 2024-09-11 02:37
Summarizing payment on this issue: 

 - Contributor: @ishpaul777 $250 via Upwork -- PAID 
 - Contributor+: n/a internal 
 
 Upwork job is here: https://www.upwork.com/jobs/~01929e53bf6e5a45ee

**Closed by stephanieelliott** 2024-09-11 02:37 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
