### ISSUE TITLE
[$500]  Chat list rendering is broken on resized window - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10359] opened 2022-08-11 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the staging app on web.
2. Resize the browser window vertically (see video for example).
3. Scroll up to load more messages

## Expected Result:
No rendered message should vanish and jump around.

## Actual Result:
Message from bottom start to disappear as you scroll and scrolling back to latest messages cause them to jump around.

## Workaround:
unknown. 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184216136-f0e15682-7117-48dc-95bc-6d4694d3516c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658528857540249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2022-08-16 05:15
https://www.upwork.com/jobs/~01dc1b2ec7b9540d24

**Comment by mountiny** [comment] 2022-08-22 10:38
@kevinksullivan Let's double the price on this one, no proposals yet

**Comment by kevinksullivan** [comment] 2022-08-22 21:39
Doubled

**Comment by mvtglobally** [comment] 2022-08-23 04:44
Issue not reproducible during KI retests. (First week)

**Comment by mountiny** [comment] 2022-08-23 07:37
👀 Promising

**Comment by kevinksullivan** [comment] 2022-08-24 00:29
Taking myself in case this pops up again, since I'll be OOO for a bit. Thanks @RachCHopkins !

**Comment by mountiny** [comment] 2022-09-01 13:32
@mvtglobally Waiting to see if this is reproducible.

**Comment by mvtglobally** [comment] 2022-09-02 04:28
@mountiny It is repro. 

https://user-images.githubusercontent.com/43995119/188059010-a8b486c5-5d1d-452b-b462-83a471867a30.mp4

**Comment by mountiny** [comment] 2022-09-02 09:02
@mvtglobally Thanks for confirming

**Comment by mvtglobally** [comment] 2022-09-06 03:43
@mountiny This week team is not able to repro. Not sure if this is device specific issue. 
Issue not reproducible during KI retests. (Second week)

**Comment by mountiny** [comment] 2022-09-08 10:35
@mvtglobally once  you gonna test, can you also make sure this works fine on standart sizes, ie ipad mobile web? I think that if it works fine there, we could move this to Monthly and add Needs Reproduction label to make sure we find out what is exactly the problem here and how to reproduce it reliably.

**Comment by mountiny** [comment] 2022-09-14 14:36
@mvtglobally Any updates here?

**Comment by mvtglobally** [comment] 2022-09-14 17:14
@mountiny missed earlier message. Checking now

**Comment by mvtglobally** [comment] 2022-09-14 17:25
@mountiny This was the latest reproduction during this weeks retest. Issue is definitely not consistent  


https://user-images.githubusercontent.com/43995119/190221868-602d7159-6116-4f9b-8fb9-fec4e97aaf7e.mp4

**Comment by mountiny** [comment] 2022-09-15 11:19
@mvtglobally Thank you! Would be great if your team could dig in a nd find some reliable reproduction steps on this one as that will help us to fix this.

**Comment by mountiny** [comment] 2022-09-20 12:19
Moving this to Monthly, it is very low ROI right now as it seems it is hard to reproduce.

**Comment by mvtglobally** [comment] 2022-10-03 20:13
Issue not reproducible during KI retests. (Third week)

**Comment by mountiny** [comment] 2022-10-04 12:35
I think I will go ahead and close this issue out, the reproduction steps are not reliable and the issue is very low ROI.

We are trying to focus on bigger issues related to performance to make the native apps more usable so this one is just distracting. 

@NicMendonca I think we can go ahead and pay Rajat the compensation bonus for reporting, but we never been able to reliably face this issue.

**Comment by mvtglobally** [comment] 2022-10-11 12:57
Issue not reproducible during KI retests. (Fourth week)

**Closed** 2022-10-11 12:58 UTC
Labels: External, Engineering, Monthly, Needs Reproduction, Help Wanted

**Comment by NicMendonca** [comment] 2022-10-11 13:02
@parasharrajat can you please accept my offer when you get the chance?

**Comment by parasharrajat** [comment] 2022-10-11 14:58
Thanks, @NicMendonca but the offer terms are wrong, reporting is 250, not 500. I can't change it so you will have to send a new one.

**Comment by mountiny** [comment] 2022-10-11 15:08
Thanks for raising this @parasharrajat

**Comment by NicMendonca** [comment] 2022-10-11 15:11
@parasharrajat updated the offer!

**Comment by parasharrajat** [comment] 2022-10-11 16:15
Thanks. Accepted

**Comment by NicMendonca** [comment] 2022-10-11 17:19
paid!
