### ISSUE TITLE
[$500] Billable-In distance request, greyed out billable option is displayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31437] opened 2023-11-16 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre:condition: In old dot, in admin account, set "Rebill expenses to clients" to "disable".
1. Launch app as employee
2. Tap on employee Workspace
3. Tap plus icon near compose
4. Tap request money----Distance request
5. Enter start and finish waypoints
6. Tap next
7. Note since " Billable " option is disabled, there is no "billable" option in distance request final confirmation page
8. Tap Request amount
9. In old dot, in admin account, set "Rebill expenses to clients" to "default to billable".
10. In employee account, open already created distance request to open distance request detail page
11. Note toggle off ( greyed out) "Billable" option is displayed.

## Expected Result:
The distance request is created while the "billable" option is "disabled" so it must not show "billable" option Or it must show toggle on(green) billable option as "default to billable" is set after creating distance request.

## Actual Result:
The distance request is created while the "billable" option is "disabled". After creating distance request, "default to billable" option is selected.

So it must not show "billable" option Or it must show toggle on(green) billable option but it displays greyed out billable option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b8090705-b8ef-47cc-bf59-dbf6b2ca43f5

https://github.com/Expensify/App/assets/115492554/86e97d69-95e8-4320-9f42-ad80a8f81912

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01018458db1c94278d</li>
        <li>Upwork Job ID: 1725123579704299520</li>
        <li>Last Price Increase: 2023-11-16</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-16 12:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Billable-In distance request, greyed out billable option is displayed
### What is the root cause of that problem?
The display is not hidden when the policy default is billable here
https://github.com/Expenify/App/blob/8872311253a7b188e7a9c64b9482371432748de5/src/components/ReportActionItem/MoneyRequestView.js#L119
### What changes do you think we should make in order to solve the problem?

We should update the code not to display it when the transaction billable is set to false 
   ```
 const shouldShowBillable = isPolicyExpenseChat && transactionBillable;
```
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2023-11-16 20:41
This is not a bug. It's correct that a request would not have the billable flag if it's created at a time when the flag is disabled on the workspace entirely. 

If default to billable is later enabled, we surface the billable flag on historical requests, but it is intentional. that we don't set it to billable on historical requests. As an admin wanting all new requests to default to billable does not necessarily mean they want all existing requests set to billable. 

The admin can still go in and manually set historical requests to billable after enabling it.

**Comment by joekaufmanexpensify** [comment] 2023-11-16 20:41
Closing is this is intentional

**Closed by joekaufmanexpensify** 2023-11-16 20:41 UTC
Labels: External, Daily, Help Wanted, Bug
