### ISSUE TITLE
[HOLD - #25834] [$1000] Web - Chat -  It takes a long time to reply to a Whisper message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24486] opened 2023-08-12 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to an account
2. Join a public room (one not used for conferences) 
3. We will receive a Whisper message.
4. Hover over the Whisper and click "Reply in thread."
5. Click on the Chat header and select "Leave Thread."
6. Repeat step 4,5 few times
7. Observe that it takes a longer time to finish than usual.

## Expected Result:
1. The function should response quickly
2. OR: the option to reply to a Whisper is redundant, we should hide it.

## Actual Result:
1. It take a long time to response
2. During that loading time, it show Unavailable workspace

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f62d7a88-d8f6-4882-b8ed-bd4d6dba5108

https://github.com/Expensify/App/assets/115492554/a08ae339-beb0-4a15-994c-82cc3060ff09

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691093120525669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185bccf9578fe6b32</li>
        <li>Upwork Job ID: 1693686290700910592</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by Talha345** [comment] 2023-08-12 21:10
Unable to reproduce. Seems to be working fine for me!

**Comment by alexpensify** [comment] 2023-08-14 21:30
@tranvantoan-qn are you still able to reproduce it?

**Comment by tranvantoan-qn** [comment] 2023-08-15 16:33
@alexpensify It seems a little bit faster when replying to Whisper's message, but the loading performance is pretty poor **in general**. I don't know if any recent changes have had an impact, but the app has been performing poorly for me in the few recent releases.

Sometimes the app becomes unresponsive.

<img width="805" alt="image" src="https://github.com/Expensify/App/assets/10254571/3ec58707-9ef1-49f0-90d0-835961e3945c">

https://github.com/Expensify/App/assets/10254571/3b8ffaac-8e38-40ca-b3a9-72c9695a6403

**Comment by alexpensify** [comment] 2023-08-15 22:17
Ok thanks, I'll review this feedback

**Comment by alexpensify** [comment] 2023-08-17 22:38
Still on my testing list

**Comment by alexpensify** [comment] 2023-08-18 21:10
@techievivek - I need some feedback here. This 🐛 appears to be more performance-based and I couldn't find anything in the App repo that would address it. I know there are initiatives to improve performance but not sure if that will address this particular GH. Thanks for reviewing!

**Comment by alexpensify** [comment] 2023-08-21 17:43
Not overdue, this one is still under review.

**Comment by techievivek** [comment] 2023-08-21 18:05
@alexpensify

Something looks fishy here. For some reason we seem to be calling `openReport` twice for the same `reportID`. I inspected it a few times and it seems to behave the same way every time. The average `openReport` duration is somewhere between 700-800ms and that seems to be the case here as well but calling the command twice seems to have a delay effect? I think we can add the external label here to see if someone can figure out the reason.

<img width="1715" alt="Screenshot 2023-08-21 at 11 26 31 PM" src="https://github.com/Expensify/App/assets/35863227/4fd4b0d2-ce45-4860-bf96-424adfafb2eb">


<img width="1725" alt="Screenshot 2023-08-21 at 11 28 44 PM" src="https://github.com/Expensify/App/assets/35863227/326285d9-0223-4904-915e-778b1fd24901">

**Comment by alexpensify** [comment] 2023-08-21 18:08
Thanks @techievivek for the review! Adding the external label to keep moving forward.

**Comment by tranvantoan-qn** [comment] 2023-08-21 18:17
I have a test account that performs extremely slowly. If you guys want to investigate more, maybe I can add you add a secondary contact, so you can login and check it

**Comment by alexpensify** [comment] 2023-08-24 03:48
Thank you @tranvantoan-qn for that update

**Comment by tranvantoan-qn** [comment] 2023-08-24 03:50
FYI
What @techievivek pointed out is also reported here:
https://expensify.slack.com/archives/C049HHMV9SM/p1692661200803469

**Comment by alexpensify** [comment] 2023-08-28 05:23
@tranvantoan-qn - If you are interested, please [submit a proposal](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) for review. Thanks!

**Comment by alexpensify** [comment] 2023-08-30 01:29
Still accepting proposals.

**Comment by alexpensify** [comment] 2023-08-31 23:51
Waiting for proposals

**Comment by OlimpiaZurek** [comment] 2023-09-01 10:19
Hi, I'm Olimpia from Callstack - expert contributor group.  I’d like to work on this issue.

**Comment by michaelhaxhiu** [comment] 2023-09-01 13:24
@OlimpiaZurek do you think we can group this GH and https://github.com/Expensify/App/issues/25834 into a single investigation and fix? Curious for your take as these are both performance-related.

If they don't feel similar enough in nature, feel free to express that sentiment and we can keep them separate.

**Comment by OlimpiaZurek** [comment] 2023-09-01 14:20
@michaelhaxhiu Since both of these issues seem to be performance-related, I think we can group them together and investigate as a single issue.

**Comment by michaelhaxhiu** [comment] 2023-09-01 16:10
cool 👍 let's do it, maybe you will need to coordinate with the internal engineer assigned on #25834 (Vivek) since that issue may pertain to backend performance. Let's see 👀

**Comment by alexpensify** [comment] 2023-09-01 22:52
Alright with this feedback, I'm going to close this one in favor of https://github.com/Expensify/App/issues/25834

**Comment by tranvantoan-qn** [comment] 2023-09-01 23:00
@alexpensify 
Am I eligible for reporting bonus? It seems like this is still a valid one and not a duplicate of #25834 (because it was created before that one).

**Comment by michaelhaxhiu** [comment] 2023-09-04 11:10
@tranvantoan-qn you would be eligible for the reporting bonus after the bug is fixed only. 

I think it may be wise to keep this GH open to track that this specific bug is fixed @alexpensify - this will help us track that it gets fixed for sure. There's a chance, for example, that the fix doesn't address this aspect of the problem (though I hope it does!)

**Comment by alexpensify** [comment] 2023-09-04 15:14
@tranvantoan-qn - I'm OOO until tomorrow but will review your question when I'm back online.

**Comment by alexpensify** [comment] 2023-09-04 15:25
With this feedback, I'm going to put this one on HOLD and update it to be a weekly.

**Comment by alexpensify** [comment] 2023-09-12 22:35
Weekly Update: On hold

**Comment by alexpensify** [comment] 2023-09-20 04:54
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-10-03 23:26
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-10-11 00:00
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-10-18 00:08
Weekly update: On Hold

**Comment by alexpensify** [comment] 2023-10-24 23:30
Weekly Update: On Hold

**Comment by tranvantoan-qn** [comment] 2023-10-25 13:17
@alexpensify

According to [this message](https://expensify.slack.com/archives/C01GTK53T8Q/p1696265713396809).

Can you help me to remove this link `https://staging.new.expensify.com/r/5303403427249671`  from the [issue description](https://github.com/Expensify/App/issues/24486#issue-1848058252) (Even though we do not need to send any message in this case)

**Comment by alexpensify** [comment] 2023-11-01 00:58
Weekly update: On Hold but I edited the GH steps above.

**Comment by alexpensify** [comment] 2023-11-08 00:28
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-11-15 01:07
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-11-21 23:24
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-11-29 01:20
@techievivek - The PR that we were on hold for was merged, are we good to take this one off hold and check it?

**Comment by alexpensify** [comment] 2023-12-05 23:11
Weekly Update: @techievivek any update here to my last question? Thanks!

**Comment by techievivek** [comment] 2023-12-12 07:54
Sorry for the delay, I will test this and share the update. Thanks

**Comment by alexpensify** [comment] 2023-12-12 15:52
Weekly update: Thank you @techievivek

**Comment by techievivek** [comment] 2023-12-13 07:05
The performance issue seems to have been fixed. I did a live testing, and it seems to worked perfectly without any noticeable lag.


https://github.com/Expensify/App/assets/35863227/af8114b1-6a47-40c6-b8d9-617629c6dd3b

**Comment by tranvantoan-qn** [comment] 2023-12-13 07:13
Hi @alexpensify
Can you determine if the reporting bonus is applicable to me?

**Comment by alexpensify** [comment] 2023-12-19 00:53
I was OOO last Friday. Flagging that this one is under review if this issue triggered the team to update or if another GH alerted the team to issue a fix and this GH was related but not the trigger to fix.

**Comment by alexpensify** [comment] 2023-12-19 19:15
Here is the payment summary: 

-  External issue reporter @tranvantoan-qn  $250 
-  Contributor that fixed the issue N/A Internal 
-  Contributor+ that helped on the issue and/or PR N/A Handled in another GH 

Upwork Job: 

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: This one is before the payment update. After discussing with @techievivek, this GH helped raise awareness of one part of the updates that happened in this PR: https://github.com/Expensify/Web-Expensify/pull/39587.

**Comment by tranvantoan-qn** [comment] 2023-12-20 03:21
Thank you, I really appreciate your consideration!

**Comment by alexpensify** [comment] 2023-12-20 21:09
@tranvantoan-qn - I've sent the contract in Upwork.

**Comment by tranvantoan-qn** [comment] 2023-12-21 01:16
@alexpensify 
Thank you,
I've accepted the offer.

**Comment by alexpensify** [comment] 2023-12-23 02:52
Thanks, I've completed the payment process in Upwork!

**Closed by alexpensify** 2023-12-23 02:52 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
