### ISSUE TITLE
[HOLD for payment 2023-08-15] App crashes when edited description of task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23210] opened 2023-07-19 22:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Assign task" section
3. Enter a title and create task
4.  Click on description and edit it
## Expected Result: 
App should not crash when editing description of task
## Actual Result: 
App crashes when edited description of task

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ee36dda1-0ac5-4b22-b199-88611692bacc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689776819661849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d8887850db77d1d</li>
        <li>Upwork Job ID: 1691486821752541184</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-07-19 22:32
I can't seem to reproduce this on dev

**Comment by thienlnam** [comment] 2023-07-19 22:56
@yuwenmemon Can you confirm before we close this out?

**Comment by aldo-expensify** [comment] 2023-07-19 23:09
I can try to reproduce

**Comment by aldo-expensify** [comment] 2023-07-19 23:14
ah, this happens in IOS, I may not be able to reproduce reliably. I'll try in Android, but it is not good enough to discard the deploy blocker I think.

**Comment by aldo-expensify** [comment] 2023-07-19 23:20
I confirmed that it crashes in Android native too, I don't know if this crashes on production

**Comment by aldo-expensify** [comment] 2023-07-19 23:38
I'm failing to reproduce in dev. One thing I noticed before the crash was that the description showed up empty before editing and crashing, and I had typed something when I created the task.

**Comment by yuwenmemon** [comment] 2023-07-20 17:53
Revert has been merged just need to CP it to Staging

**Comment by ayazhussain79** [comment] 2023-07-20 17:59
it is resolved now

**Comment by jasperhuangg** [comment] 2023-07-20 19:53
CP is going out, I'll retest and remove the deploy blocker label once it's done.

We'll need to pay out @ayazhussain79 for the reporting bonus before closing this out. @mallenexpensify

**Comment by thienlnam** [comment] 2023-07-20 21:07
Re-opening so we can get this paid out for the reporter

**Comment by situchan** [comment] 2023-07-24 20:58
This happens on latest staging / production. I noticed that the root cause already existed before https://github.com/Expensify/App/pull/22983.

Another way of reproducing crash:
1. Go to any task report
2. Click + on composer > Assign task **(important step to set ONYXKEYS.TASK null)**
3. Click back button on Assign task page
4. Select Description field
5. Click Save button on Task description page

**Comment by situchan** [comment] 2023-07-24 21:00
Same bug happens on Assignee modal - https://github.com/Expensify/App/pull/23342#issuecomment-1648571208.

**Comment by situchan** [comment] 2023-07-25 06:17
@ayazhussain79 can you please confirm in staging/production that native app still crashes following repro step in https://github.com/Expensify/App/issues/23210#issuecomment-1648604974?

**Comment by ayazhussain79** [comment] 2023-07-25 08:15
@situchan i tried it but able to reproduce, are you still able to reproduce it?

**Comment by situchan** [comment] 2023-07-25 08:33
yeah, it's another bug. Even crashes when update description

**Comment by ayazhussain79** [comment] 2023-07-25 08:48
here is another bug when pressing back button on assignee page its returns back to the task creating page


https://github.com/Expensify/App/assets/56740856/5730c587-d9b9-4d09-9c36-e1d7159682ef

**Comment by situchan** [comment] 2023-07-25 08:50
> Even crashes when update description

This is fixed in latest main (#23342 merged). Still happens on staging / production

**Comment by ayazhussain79** [comment] 2023-08-01 17:45
@thienlnam @aldo-expensify @mallenexpensify this bug is just pending for payment

**Comment by mountiny** [comment] 2023-08-15 16:28
Matt is probably ooo, this is ready to paid to the reporter as the bug is fixed.

**Comment by laurenreidexpensify** [comment] 2023-08-16 17:25
@mountiny sorry just to be clear, are you saying the only payment required on this issue is to the bug reporter?

**Comment by mountiny** [comment] 2023-08-16 20:14
Correct, I think this PR has solved this issue too but the root casue was the same so we should not be paying for this issue to the contributor PR author https://github.com/Expensify/App/pull/23342

So just $250 to @ayazhussain79

**Comment by laurenreidexpensify** [comment] 2023-08-18 08:37
offer sent to @ayazhussain79 in Upwork!

**Comment by ayazhussain79** [comment] 2023-08-18 09:09
@laurenreidexpensify offer accepted, Thank you

**Comment by laurenreidexpensify** [comment] 2023-08-18 12:32
Payment Summary:

- Bug report $250 paid to @ayazhussain79 in Upwork

**Closed by laurenreidexpensify** 2023-08-18 12:32 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
