### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$250] Migrate RequestorOnfidoStep.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16246] opened 2023-03-20 08:51 UTC
### Filenames
- [ ] [src/pages/ReimbursementAccount/RequestorOnfidoStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/RequestorOnfidoStep.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108c7eff871f84756</li>
        <li>Upwork Job ID: 1702336246230073344</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-06 11:11
I'd love to work on this.

**Comment by neonbhai** [comment] 2023-06-09 00:54
I can work on this!

**Comment by olexyt** [comment] 2023-07-07 14:57
I can work on this issue.

**Comment by to-ai** [comment] 2023-07-11 21:25
I am able to work on this task.

**Comment by pradeepmdk** [comment] 2023-07-30 14:48
i will work on this

**Comment by barttom** [comment] 2023-09-13 14:09
Hi! I'm Bartek from Callstack - an expert contributor group and I would like to work on this one.

**Comment by barttom** [comment] 2023-09-13 14:14
Contributor details
Your Expensify account email: bartlomiej.tomczyk@callstack.com

**Comment by Rose-Miller-web-dev** [comment] 2023-09-14 18:23
### Proposal
### Issue
Migration from RequestorOnfidoStep.js class to function

### Solution
Create a function corresponding the class and migrate the functionalities to it in addition to updating the references to the class
for instance if there is some import in a component like below
`import {RequestorOnfidoStep}`
then it should become
`import RequestorOnfidoStep`

Upwork Profile: https://www.upwork.com/freelancers/rosemiller
Expensify Email: thisisrosemiller@gmail.com

**Comment by jliexpensify** [comment] 2023-09-14 22:33
Someone has already been assigned to work on this

**Comment by jliexpensify** [comment] 2023-10-09 23:08
This isn't overdue right? Also, is any payment from me needed? Sobit takes New.Dot and @barttom invoices us right?

**Comment by barttom** [comment] 2023-10-10 05:47
Hey @jliexpensify!
This issue is on me, I just need to merge main branch into mine fetuje branch, but I’m on OOO until end of this week

**Comment by jliexpensify** [comment] 2023-10-11 04:39
No worries! Thanks for letting us know. @barttom just to confirm that you invoice us for payment, correct?

**Comment by barttom** [comment] 2023-10-11 05:49
@jliexpensify I’m a part of callstack team, so I afaik they are care of invoices 😉

**Comment by jliexpensify** [comment] 2023-10-11 21:51
Cool, in that case - Payment Summary:

- Contributor: @barttom Invoiced payment
- C+: @sobitneupane $250 New.Dot payment

No Upworks job needed here.

**Comment by jliexpensify** [comment] 2023-10-16 06:44
Hi @sobitneupane @barttom just checking: this hasn't been competed/implemented right?

**Comment by barttom** [comment] 2023-10-16 07:16
@jliexpensify It has been merged

**Comment by Pujan92** [comment] 2023-10-18 13:41
@barttom As it is still in the regression period, I found a console warning and reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1697636190219869).

Reason: We switched to `useLocalize` and removed `withLocalize` but `StepPropTypes` expects a prop `withLocalizePropTypes` which is now missing.

**Comment by jliexpensify** [comment] 2023-10-24 04:33
Hmm just to confirm: there's a regression related tot his GH? So payment should be adjusted to $125?

**Comment by jliexpensify** [comment] 2023-10-25 03:06
Payment Summary (assuming there's a regression)

- Contributor: @barttom $125 (Callstack invoiced payment)
- C+: @sobitneupane $125 (New.Dot payment)

NO UPWORKS JOB

**Closed** 2023-10-26 05:11 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment

**Comment by sobitneupane** [comment] 2023-10-27 12:59
@jliexpensify I wasn't assigned to the PR, and I didn't review it. Therefore, no payment is due to me.

**Comment by jliexpensify** [comment] 2023-10-30 00:24
Fixed, thanks for letting me know!
