### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000] It must show the detail of the user's profile that assigns the task

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24144] opened 2023-08-04 02:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
*First login to different accounts with two different users, one as user A and the other as user B
1-[User A] Click plus sign
2-[User A] Open  Assign task
3-[User A] Write a title and click Next button
4-[User A] Select  User B in Share somewhere  and click Confirm task button
5-[User B] Open the task assign by the User A
6-[User B] Click on the profile picture

## Expected Result:
It should show the detail of User A as shown in any Thread created by them. Do not show the "Settings" tab, as this is HELD on a future redesign.

## Actual Result:
Show the detail the User B.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.47-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/84bcb517-9fcf-4fb8-89eb-5f0964449610

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690804316551009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011911d675e889edb8</li>
        <li>Upwork Job ID: 1687508460543074304</li>
        <li>Last Price Increase: 2023-08-04</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26033003</li>
<li>BhuvaneshPatil | Contributor | 26033006</li>
</ul></li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2023-08-04 02:12
proposal from reporting contributor 

# Proposed solution
### Please re-state the problem that we are trying to solve in this issue.
It must show the detail of the user's profile that assigns the task
*What is the root cause of that problem?*
For task reports, participantAccountIDs refers to the task assignee. On selecting a task report, it shows the correct avatar of the task creator but participantAccountID is used to navigate to the profile page. That's why it's showing incorrect profile details
*What changes do you think we should make in order to solve the problem?*
Add a condition inside the ReportUtils.navigateToDetailsPage function to check if a given report type is TASK then use report.ownerAccountID for navigation otherwise participantAccountID.
https://github.com/Expensify/App/blob/dc3270005e924e49a890028bd4b3ef094a939227/src/libs/ReportUtils.js#L1386
if (participantAccountIDs.length === 1) {
        Navigation.navigate(ROUTES.getProfileRoute(
            report.type === CONST.REPORT.TYPE.TASK ? report.ownerAccountID :participantAccountIDs[0]));
        return;
}
### What alternative solutions did you explore? (Optional)
N/A

**Comment by romitgithub** [comment] 2023-08-05 15:12
Contributor details
Your expensify account email: choudharyromit@gmail.com
Upwork profile: https://www.upwork.com/freelancers/~01b7c2a45e48a0d1d1

**Comment by romitgithub** [comment] 2023-08-05 15:12
Contributor details
Your Expensify account email: choudharyromit@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7c2a45e48a0d1d1

**Comment by s77rt** [comment] 2023-08-06 15:18
I'm not sure about the expected behaviour. Asking on Slack for a clarification https://expensify.slack.com/archives/C01GTK53T8Q/p1691334974136469

**Comment by BhuvaneshPatil** [comment] 2023-08-06 18:17
Kinda dupe - https://github.com/Expensify/App/issues/23579

@s77rt Please have a look.

**Comment by twisterdotcom** [comment] 2023-08-07 16:50
I agree we haven't done anything about this yet, but I think we should, even if we've closed it in the past. It's fine for us to change our mind in the future, and it doesn't make past decisions innately wrong.

@BhuvaneshPatil let's keep discussing for now in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1691334974136469

**Comment by BhuvaneshPatil** [comment] 2023-08-07 18:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It must show the detail of the user's profile that assigns the task

### What is the root cause of that problem?
As decided here in slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1691426870537099?thread_ts=1691334974.136469&cid=C01GTK53T8Q

We should show the task title (the one that appears in header below the avatar, and avatar will be of task creator)

### What changes do you think we should make in order to solve the problem?
We are disabling showing `shouldUseFullTitle` here - 
https://github.com/Expensify/App/blob/09f6b6b00ecbee279f8988b92dd81abeb56416d1/src/pages/ReportDetailsPage.js#L153-L160

For that value we use - 
https://github.com/Expensify/App/blob/09f6b6b00ecbee279f8988b92dd81abeb56416d1/src/pages/ReportDetailsPage.js#L63-L64

We shall change - `shouldUseFullTitle` to something like below - 

```js
const shouldUseFullTitle = !shouldDisableSettings || ReportUtils.isTaskReport(props.report);
```

It will allow to show full title in case we are opening a task report.

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-08-08 14:43
@Mauri-salazar Thanks for the proposal. Your RCA is correct however the solution is not what we looking for i.e. we don't want to navigate to the owner profile (the expected behaviour did change based on slack thread).

___

@twisterdotcom Can you please update the Expected Results.

**Comment by s77rt** [comment] 2023-08-08 14:45
@spcheema Thanks for the proposal. Your RCA is correct, the solution looks good to me but I think it was first proposed by @honnamkuan.

**Comment by s77rt** [comment] 2023-08-08 14:49
@dukenv0307 Thanks for the proposal. I think it's the same as @honnamkuan's

**Comment by s77rt** [comment] 2023-08-08 14:51
@BhuvaneshPatil Thanks for the proposal. It seems also same as @honnamkuan's. I have checked the old issue as well, you proposed a solution to show the task's owner profile details and not the task details.

**Comment by s77rt** [comment] 2023-08-08 14:54
@BhuvaneshPatil I think @honnamkuan proposed that change even before discussion in Slack. It seems fair to go with their proposal as they were the first.

**Comment by s77rt** [comment] 2023-08-08 15:02
@BhuvaneshPatil Oh, my bad! I didn't see the proposal posted by @kbecciv. I think you qualify for both reporter and contributor.

**Comment by BhuvaneshPatil** [comment] 2023-08-08 16:47
@twisterdotcom 
just to confirm , it should look like this - 

Show task name below user name just like we do in threads.
<img width="712" alt="Screenshot 2023-08-08 at 10 16 04 PM" src="https://github.com/Expensify/App/assets/27822551/64fc0837-3cb2-4ae4-b003-197f9ba308ad">

**Comment by twisterdotcom** [comment] 2023-08-08 17:04
Nice!

**Comment by cristipaval** [comment] 2023-08-08 17:23
> @BhuvaneshPatil Oh, my bad! I didn't see the proposal posted by @kbecciv. I think you qualify for both reporter and contributor.

It's still not clear to me what solution you think I should review, @s77rt. I see [here](https://github.com/Expensify/App/issues/24144#issue-1835957152) that @Mauri-salazar reported the issue

**Comment by s77rt** [comment] 2023-08-08 17:27
@cristipaval This is the original issue https://github.com/Expensify/App/issues/23579 it was closed before but the bug was not fixed

**Comment by BhuvaneshPatil** [comment] 2023-08-08 17:37
To sum up the situation -  

I have raised this issue - https://github.com/Expensify/App/issues/23579. It was closed but the bug isn't fixed till now. For that issue I have submitted the proposal - https://github.com/Expensify/App/issues/23579#issuecomment-1650376240

After lot of discussion, it was decided to show the user details of creator - https://expensify.slack.com/archives/C049HHMV9SM/p1689928645869329

It was again discussed here - https://expensify.slack.com/archives/C01GTK53T8Q/p1691334974136469, and decided that we will show the same details as we show for threads. (please have a look at comment above https://github.com/Expensify/App/issues/24144#issuecomment-1669968788). 

As the original bug is - https://github.com/Expensify/App/issues/23579 and the proposal for it is - https://github.com/Expensify/App/issues/23579#issuecomment-1650376240 (there are few others that I have changed as requirements changed).

@s77rt Please add your views for the same.

**Comment by s77rt** [comment] 2023-08-08 19:29
@BhuvaneshPatil Discussing next steps in Slack

**Comment by BhuvaneshPatil** [comment] 2023-08-09 13:09
> @cristipaval This is the original issue #23579 it was closed before but the bug was not fixed
> 
> Edit: The solution to review is [#24144 (comment)](https://github.com/Expensify/App/issues/24144#issuecomment-1668353267) which is also basically the same in the old issue [#23579 (comment)](https://github.com/Expensify/App/issues/23579#issuecomment-1650376240)

@cristipaval Please have a look on this updated comment.

**Comment by cristipaval** [comment] 2023-08-09 16:45
Thanks @s77rt and @twisterdotcom for all the work you've done here!

@BhuvaneshPatil you're all set, looking forward to reviewing your PR 🚀

**Comment by BhuvaneshPatil** [comment] 2023-08-09 17:24
Thanks @cristipaval .

I will submit PR by tomorrow.

This change will have following things - 
- Navigate user to report details page when clicking on header
- User avatar will be avatar of task creator, and the title below will be title of task.
- Settings should not be visible in report details page in case of task.

@twisterdotcom  Please confirm the requirements.

cc - @s77rt

**Comment by BhuvaneshPatil** [comment] 2023-08-09 19:16
PR raised.

**Comment by twisterdotcom** [comment] 2023-08-18 10:15
Apologies but I am finally going on Parental Leave. I am reassigning to another member of the team.

**Comment by s77rt** [comment] 2023-08-18 13:53
- The PR that introduced the bug has been identified: Not a bug. The task details page is not implemented yet. This is technically an improvement.
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: n/a

**Comment by BhuvaneshPatil** [comment] 2023-08-25 11:39
^^

**Comment by adelekennedy** [comment] 2023-08-28 16:13
### Payouts due:

Issue Reporter: $250 @Mauri-salazar
Contributor: $1000 @BhuvaneshPatil 
Contributor+: $1000 @s77rt 

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/jobs/~011911d675e889edb8).

**Comment by BhuvaneshPatil** [comment] 2023-08-28 16:19
@adelekennedy This is dupe of - https://github.com/Expensify/App/issues/23579
Thus reporter should be considered of that issue.

Reference - https://github.com/Expensify/App/issues/24144#issuecomment-1669793419

cc - @s77rt

**Comment by adelekennedy** [comment] 2023-08-28 16:20
Ah thank you - I'm catching up here after picking this up from Ted. deleted Slack comment and removing the reporting bonus

**Comment by Mauri-salazar** [comment] 2023-08-28 16:28
So it hasn't been decided yet if my payment as a reporter will be made, right?

**Comment by Mauri-salazar** [comment] 2023-08-28 16:43
@adelekennedy Excuse me,
Am I not getting paid for this report?
Although the bug, it's related to, was already closed when I reported this bug.

**Comment by adelekennedy** [comment] 2023-08-30 22:36
Coming back to this, after reading through all the comments:
@BhuvaneshPatil you reported this bug but the issue was closed previously before making it external 
@Mauri-salazar you then reported this bug independently and it was moved through to external

From [this comment](https://github.com/Expensify/App/issues/24144#issuecomment-1669793419) @s77rt thinks that @BhuvaneshPatil is eligible for the reporting bonus (but does not mention @Mauri-salazar)

I think this is a tough case where according to what we've done in the past @BhuvaneshPatil you wouldn't be eligible as we decided not to work on the issue previously but @Mauri-salazar would be as we opted to work on this - however for fairness I'd rather pay you both the reporting bonus as it was discussed above

**Comment by Mauri-salazar** [comment] 2023-08-30 23:00
@adelekennedy   I am very happy since this is my first payment, and thank you very much for giving me the opportunity to work with you. :)

**Comment by adelekennedy** [comment] 2023-09-01 23:06
@Mauri-salazar will you apply [here](https://www.upwork.com/jobs/~011911d675e889edb8)?

**Comment by Mauri-salazar** [comment] 2023-09-02 00:33
@adelekennedy  Yes, I just applied.
 Thank you so much.!

**Comment by adelekennedy** [comment] 2023-09-04 22:35
Accepted your offer @Mauri-salazar

**Comment by Mauri-salazar** [comment] 2023-09-05 01:42
@adelekennedy  Ready, Thank you very much!

**Comment by adelekennedy** [comment] 2023-09-05 01:45
and paid!

**Closed by adelekennedy** 2023-09-05 01:45 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by BhuvaneshPatil** [comment] 2023-09-05 04:03
@adelekennedy Can you please check if you have paid me correctly? I think you have paid me twice, can you please confirm?
