### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Task – RHP present when delete task with reply

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45699] opened 2024-07-18 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4735083
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Issue reported by:**  Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Create a task
5. Open task detail
6. Send comment
7. Click on header and delete the task

## Expected Result:
RHP disappears when delete task with reply [(see this comment)](https://github.com/Expensify/App/issues/45699#issuecomment-2237982770)

## Actual Result:
RHP present when delete task with reply, but disappears when delete IOU with reply

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0bad3ecd-0386-4f7b-a4b7-efb7e4086d59

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d58ba540e5cc55b0</li>
        <li>Upwork Job ID: 1814135208916800159</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 103251909</li>
<li>dominictb | Contributor | 103251910</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment] 2024-07-18 16:38
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-18 16:38
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-07-18 16:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task – RHP present when delete task with reply

### What is the root cause of that problem?
We are only navigating back if there are no visible actions
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/actions/Task.ts#L1058-L1060
### What changes do you think we should make in order to solve the problem?

remove the `if` 
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-18 16:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task – RHP present when delete task with reply

### What is the root cause of that problem?
We are only navigating back if there are no visible actions `!ReportActionsUtils.doesReportHaveVisibleActions`
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/actions/Task.ts#L1058-L1060
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/actions/Task.ts#L923-L924
### What changes do you think we should make in order to solve the problem?

We should dismiss modal in when the task has visible actions so change it to 
```
if (shouldDeleteTaskReport) {
        Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(parentReport?.reportID ?? '-1'));
    } else {
        Navigation.dismissModal();
    }
```


### What alternative solutions did you explore? (Optional)
remove the `if` here if we want to navigate back to the parent 
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/libs/actions/Task.ts#L1058

**Comment by jliexpensify** [comment] 2024-07-19 02:53
@lanitochka17 to confirm, are you expecting the RIght Hand Pane (RHP) to show when an expense is deleted? i.e. to mirror the Task?

**Comment by jliexpensify** [comment] 2024-07-19 02:57
Thanks @dominictb - yeah that's the behaviour I'm seeing when testing this, so I don't think this is a bug. Closing!

**Comment by jliexpensify** [comment] 2024-07-19 03:04
Oh, I see - I misunderstood you! So you're saying the decision was made by Shawn that the RHP shouldn't exist when a task or/and an expense is deleted?

**Comment by jliexpensify** [comment] 2024-07-19 03:08
Thanks for clearing this up @dominictb - in that case, I agree: it's a bug

**Comment by jliexpensify** [comment] 2024-07-23 03:33
bump @abdulrahuman5196 we have a proposal

**Comment by abdulrahuman5196** [comment] 2024-07-23 19:13
Hi, Will check on this tomorrow

**Comment by abdulrahuman5196** [comment] 2024-07-24 10:17
Checking now

**Comment by abdulrahuman5196** [comment] 2024-07-24 11:11
@dominictb 's proposal here looks good and works well. It is inline with the current expense deletion flow. 
But one suggestion to instead of doing step 3 in the mentioned place, we can add another if statement to different task deletion like done here, anyways that could be handled in the PR.

https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/ReportDetailsPage.tsx#L663-L666

🎀 👀 🎀
C+ Reviewed

**Comment by jliexpensify** [comment] 2024-08-14 05:53
Bump @abdulrahuman5196 for the checklist

Payment Summary

- C: @dominictb $250
- C+: @abdulrahuman5196 $250 (please accept the job!)

[Upwork job](https://www.upwork.com/jobs/~01d58ba540e5cc55b0)

**Comment by abdulrahuman5196** [comment] 2024-08-14 15:10
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Go to NewDot
2) Open any chat
3) Create a task
4) Open task detail
5) Send comment
6) Click on header and delete the task
7) Verify that: RHP disappears when delete task with reply

@jliexpensify I am getting paid via newDot.

**Comment by JmillsExpensify** [comment] 2024-08-14 19:10
$250 approved for @abdulrahuman5196

**Comment by jliexpensify** [comment] 2024-08-15 02:47
Paid and job closed.

**Closed** 2024-08-15 02:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
