### ISSUE TITLE
[$1000] Able to open context action menu even when swiping off the report screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14514] opened 2023-01-24 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat that has a pay money request 
2. Long press the pay money request 
3. Without letting your finger leave the screen during the long press,  swipe right
4. The app goes to the previous screen but context menu stays active

## Expected Result
Should not be able to go back while long press

## Actual Result
Able to use the context menu even when not on report screen and able to delete comment while not being on that screen

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] iOS / native

**Version Number:** 1.2.58-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214363094-a18a9cb7-fdd6-4ae4-a7a2-4aed3ff06b21.mov

https://user-images.githubusercontent.com/43996225/214363443-f0e6fac9-fb0f-4b0b-a8e4-72f36cf74c3a.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674502407489669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa4a22e35db7ab8b</li>
        <li>Upwork Job ID: 1619036312768962560</li>
        <li>Last Price Increase: 2023-01-27</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-01-26 18:39
This is pretty bad, I had to kill the app in order to get out of the context menu . Updated the OP to use `pay money request`.

**Comment by esh-g** [comment] 2023-01-27 18:16
# Proposal

**Solution**

We need to dismiss the `contextMenu` once the user swipes off from the report screen.
```diff
diff --git a/src/pages/home/ReportScreen.js b/src/pages/home/ReportScreen.js
index d544d78a6..a66d9bc4f 100644
--- a/src/pages/home/ReportScreen.js
+++ b/src/pages/home/ReportScreen.js
@@ -29,6 +29,7 @@ import OfflineWithFeedback from '../../components/OfflineWithFeedback';
 import withDrawerState, {withDrawerPropTypes} from '../../components/withDrawerState';
 import ReportFooter from './report/ReportFooter';
 import Banner from '../../components/Banner';
+import * as ReportActionContextMenu from "./report/ContextMenu/ReportActionContextMenu";
 import withLocalize from '../../components/withLocalize';
 import reportPropTypes from '../reportPropTypes';
 import FullPageNotFoundView from '../../components/BlockingViews/FullPageNotFoundView';
@@ -222,6 +223,10 @@ class ReportScreen extends React.Component {
         // When the ReportScreen is not open/in the viewport, we want to "freeze" it for performance reasons
         const freeze = this.props.isSmallScreenWidth && this.props.isDrawerOpen;
 
+        if (freeze) {
+            ReportActionContextMenu.hideContextMenu(false);
+        }
+
         // the moment the ReportScreen becomes unfrozen we want to start the animation of the placeholder skeleton content
         // (which is shown, until all the actual views of the ReportScreen have been rendered)
         const animatePlaceholder = !freeze;

```

https://user-images.githubusercontent.com/77237602/214636973-2b77acb3-ac52-49bc-a635-ce12f34cb038.mov

**Comment by aldo-expensify** [comment] 2023-01-27 18:33
I'm not sure if this is a real problem, but the code in the proposal https://github.com/Expensify/App/issues/14514#issuecomment-1406908693 looks like it could close the context menu if the ReportScreen gets re-rendered, right? Could it get re-rendered in other cases and close the context menu when we didn't want to close it? I.e. a push event arriving with new comments?

**Comment by esh-g** [comment] 2023-01-27 18:38
@aldo-expensify Please note that it will only close when we choose to freeze the screen and I don't think that the user should be able to perform any context actions if the screen is frozen with the `Freeze` component.

And if you're wondering if this is a problem, I think it is because on `mWeb` also if you open the context menu and press the back button, the contextMenu stays open even on the LNH. So that is a problem and the proposal above fixes that

**Comment by aldo-expensify** [comment] 2023-01-27 18:58
@esh-g thanks for explaining!

**Comment by mateoLorenzo1** [comment] 2023-01-27 22:39
Its already fixed?

**Comment by aldo-expensify** [comment] 2023-01-27 23:05
> Its already fixed?

We are at the proposal stage, I'll give some time to @mananjadhav to test and give me his opinion on https://github.com/Expensify/App/issues/14514#issuecomment-1406908693

**Comment by s77rt** [comment] 2023-01-29 08:28
This is a duplicate. https://github.com/Expensify/App/issues/9823

**Comment by esh-g** [comment] 2023-01-29 08:32
@s77rt The native back button issue is fixed already, if you press the native back button, popovers do close. But in this case no back button needs to be pressed, the user needs to swipe left while long pressing

**Comment by s77rt** [comment] 2023-01-29 08:36
The issue is still open (put on hold for navigation reboot).
I can still reproduce the issue

https://user-images.githubusercontent.com/16493223/215314945-a00baa15-7dcd-45ef-bbcf-0e05884d061b.mp4

**Comment by aldo-expensify** [comment] 2023-01-30 18:04
> This is a duplicate. https://github.com/Expensify/App/issues/9823

Thanks @s77rt for finding that... I do think we can handle these things together as part of the same issue. They are both about going "back" with the context menu open, but this one uses a different gesture to do it.

I tested in native and going back with the "back" button when the context menu is open closes the context menu, so that parts works fine.

@JmillsExpensify do you agree with marking this as duplicate and handling it together with https://github.com/Expensify/App/issues/9823 ?

**Comment by JmillsExpensify** [comment] 2023-01-31 19:43
> @JmillsExpensify do you agree with marking this as duplicate and handling it together with https://github.com/Expensify/App/issues/9823 ? We could just make sure we test the solution for https://github.com/Expensify/App/issues/9823 swiping back in native.

Completely agree that this is part of the navigation reboot, further that both issues are about going "back." Agree with others that we should mark as duplicate and address with https://github.com/Expensify/App/issues/9823.

**Comment by aldo-expensify** [comment] 2023-02-01 18:50
Updated https://github.com/Expensify/App/issues/9823 to consider the swipe back case. Closing this....

**Closed by aldo-expensify** 2023-02-01 18:50 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
