### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Updated multiple selector in workspace settings to be green when objects are selected

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#52972] opened 2024-11-22 17:03 UTC
Problem: Users are not sure what to do next when they select multiple categories, tags, etc. when updating the workspace settings. ([thread](https://expensify.slack.com/archives/C07HPDRELLD/p1732297945702999?thread_ts=1732078999.713569&cid=C07HPDRELLD))

Solution: If someone is selecting multiple objects when updating the workspace, the multiple selector should be green instead of grey. This would apply in any workspace update where multiple objects can be selected so members, taxes, categories, tags, etc. 

This is what should be green going forward: 
![2024-11-22_09-59-13](https://github.com/user-attachments/assets/78c1d03b-c1a7-4169-b883-012f499c17b5)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860018331543721914</li>
        <li>Upwork Job ID: 1860018331543721914</li>
        <li>Last Price Increase: 2024-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>twilight2294 | Contributor | 105064120</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment] 2024-11-22 18:03
Note for contributors: We should use this pattern for any bulk action, so that should be on the following routes:

 - /settings/workspaces/[workspaceID]/categories
 - /settings/workspaces/[workspaceID]/tags
 - /settings/workspaces/[workspaceID]/reportFields
 - /settings/workspaces/[workspaceID]/taxes
 - /settings/workspaces/[workspaceID]/members
 - /search

Let me know if I missed any though I think that covers it.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-22 18:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When user selects multiple items in the workspace settings in the members, tags and other pages, the multiple selector is not showing as success button 
### What is the root cause of that problem?
Improvement
### What changes do you think we should make in order to solve the problem?
When user selected multiple items, set the success prop of `ButtonWithDropdownMenu` as true.
so we can pass a new prop:
`                    success={selectedCategoriesArray.length >1}
`
to the `ButtonWithDropdownMenu`
inside:
`WorkspaceCategoriesPage`
`WorkspaceMembersPage` 
`WorkspaceTaxesPage`
`WorkspaceTagsPage`
`WorkspaceReportFieldsPage`

we will change the `selectedCategoriesArray` to the corresponding array in the above pages.

and inside the :
`SearchPageHeader` , pass   `   success={selectedTransactionsKeys.length > 1}` as a prop to `ButtonWithDropdownMenu`

We can explore other pages in app where the multiple selector button could be displayed in green when the user selects multiple items, provided this aligns with the intended design.

**Comment by anmurali** [comment] 2024-11-24 02:40
@hungvu193 waiting on you to review the proposals here. Can you pls prioritise it this week?

**Comment by hungvu193** [comment] 2024-11-24 02:43
> @hungvu193 waiting on you to review the proposals here. Can you pls prioritise it this week?

Yes. I'll review today

**Comment by hungvu193** [comment] 2024-11-24 10:42
Thanks for the proposals, everyone. I checked the usage of `ButtonWithDropdownMenu` in the project. Most of the time we will use it as bulk actions, and because of that I think updating the default props of `success` to `true` will be the most efficient way.
@twilight2294 's [proposal here ](https://github.com/Expensify/App/issues/52972#issuecomment-2494414398)looks good to me!

🎀 👀 🎀  C+ reviewed

**Comment by Shahidullah-Muffakir** [comment] 2024-11-24 13:27
> Solution: If someone is selecting multiple objects when updating the workspace,

@hungvu193 , based on the OP, I understood that the selector button should only turn green when the user selects more than one item. With the selected proposal, it will turn green as soon as one item is selected. Just wanted to confirm: is this the expected behavior? Thanks!

**Comment by hungvu193** [comment] 2024-11-24 13:45
Thanks for pointing that out @Shahidullah-Muffakir.
@JmillsExpensify Should the dropdown button be green if we only select one option?

**Comment by dangrous** [comment] 2024-11-25 17:03
For me, I'd think it should be green even when only one item is selected - not just multiple. But I defer to @danielrvidal, and/or @Expensify/design to confirm! (Design, see initial issue description from Daniel for the quick overview.) Thanks!

**Comment by dannymcclain** [comment] 2024-11-25 17:13
>it should be green even when only one item is selected - not just multiple

I agree. If we're making this change, _all_ bulk action button should be green, regardless of number of items selected.

**Comment by danielrvidal** [comment] 2024-11-25 18:59
Agreed with @dannymcclain it should be whenever bulk actions can be used, so even with one selection.

**Comment by shawnborton** [comment] 2024-11-26 12:59
For consistency's sake I feel like we should make this the same everywhere

**Comment by JmillsExpensify** [comment] 2024-11-27 11:55
Yeah, it's basically part of the framework now. Let's do it everywhere.

**Comment by JmillsExpensify** [comment] 2024-12-09 09:17
Payment summary:

 - Contributor: $250 @twilight2294 via Upwork
 - Reviewer: $250 @hungvu193 via New Expensify

**Comment by hungvu193** [comment] 2024-12-09 09:59
## Regression Test:
1. Go to Workspace > Categories > Select Multiple options
2. Verify that The selector is green in color
3. Go to Workspace > tags > Select Multiple options
4. Verify that The selector is green in color
5. Go to Workspace > Report Field > Select Multiple options
6. Verify that The selector is green in color
7. Go to Workspace > taxes > Select Multiple options
8. Verify that The selector is green in color
9. Go to Workspace > members > Select Multiple options
10. Verify that The selector is green in color
11. Go to Search > Select Multiple options
12.  Verify that The selector is green in color
13. Switch to small screen mode (using Web Inspector). Verify that The selector is green in color.

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment] 2024-12-09 10:37
That looks good to me. Regression test added, so we'll wait two more days for the regression period to end.

**Comment by JmillsExpensify** [comment] 2024-12-11 11:38
The regression period is over, and the contributor has been paid out via Upwork. @hungvu193 please request via New Expensify. I'm going to close this issue!

**Closed by JmillsExpensify** 2024-12-11 11:38 UTC
Labels: External, Daily, Internal, NewFeature, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-12-12 11:23
$250 approved for @hungvu193
