### ISSUE TITLE
[$1000] Web - Two-factor authentication is not fully visible

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21183] opened 2023-06-21 10:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go Settings > Security >Two-factor authentication
3. Copy codes
4. Click to Next button
If bug not reproducible - refresh the page
Do the steps from 2 - 4 Two times

## Expected Result:
Two-factor authentication is  fully visible

## Actual Result:
Two-factor authentication is not fully visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d9b406f5-4c3a-4bc3-a9fd-1216e3f44c4e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687243228581929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011360edc58368e0c5</li>
        <li>Upwork Job ID: 1671502675380977664</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by Shivam7-1** [comment] 2023-06-21 10:48
Hii
I am interested in work on this Issue can anyone please let me know how should I give proposal or do I get assign directly with this issue ?

**Comment by captain-Akshay** [comment] 2023-06-21 10:50
can't reproduce in the current version on MAIN

**Comment by captain-Akshay** [comment] 2023-06-21 10:55
Contributor details
Your Expensify account email: akshay.sharma0503@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011080bf94061a0972

**Comment by Shivam7-1** [comment] 2023-06-21 11:14
##Proposal

###Two-factor authentication is not fully visible

##Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?
The error is occurring in the `CodesPage.js` file. In the `CodesPage` component, the `TwoFactorAuthActions.clearTwoFactorAuthData()` function is being called in the cleanup of the `useEffect` hook, but that function does not exist in the provided code. This is causing an error and preventing the expected result.

###What changes do you think we should make in order to solve the problem?
To fix the error,  remove the `TwoFactorAuthActions.clearTwoFactorAuthData()` call or provide the implementation of that function.

**Comment by sonialiap** [comment] 2023-06-21 12:57
I cannot reproduce this error on Chrome (the QR page is correctly centered for me) but seems like Shivam7-1 can so triaging it to External

**Comment by Vishrut19** [comment] 2023-06-21 13:14
Hello! I tried to reproduce it but for me it is not happening.

<img width="1470" alt="Screenshot 2023-06-21 at 6 44 39 PM" src="https://github.com/Expensify/App/assets/53470896/d7d99fb5-28bc-49d8-b9c6-190b08e1cfb0">

**Comment by Shivam7-1** [comment] 2023-06-21 13:25
Yes for encounter this type  error, made a changes in code to remove the TwoFactorAuthActions.clearTwoFactorAuthData() call and  provide the implementation of that function.

**Comment by ashimsharma10** [comment] 2023-06-21 13:58
Have posted this before, find it https://github.com/Expensify/App/issues/21183?fbclid=IwAR3yGz2EkWZ6BNlI1y2KjVwKC2IWFw4nPShzXWYog7Sl9DEXLBr2o58GJVU

**Comment by jstortoise** [comment] 2023-06-21 18:26
This can be reproduced on safari

**Comment by narzullome** [comment] 2023-06-22 00:23
Yes this is  reproduced in Safari

**Comment by abdulrahuman5196** [comment] 2023-06-23 19:20
@sonialiap Could you kindly remove the reviewing label. Its masking this issue in K2

**Comment by flaviadefaria** [comment] 2023-06-23 21:08
@sonialiap @abdulrahuman5196 I confirmed [internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1687553621625899) that we'll keep this GH open but compensate @ashimsharma10 for reporting the bug instead of @narzullome since they reported it first.

**Comment by Shivam7-1** [comment] 2023-06-24 03:12
@flaviadefaria I am new to expensify as Contributor can I just get to know that In How many days Proposal are getting reviewed my proposal link https://github.com/Expensify/App/issues/21183#issuecomment-1600646881

**Comment by abdulrahuman5196** [comment] 2023-06-26 07:51
Hi, @Shivam7-1 the general guideline for C+ review on a proposal is 24 hours. But it could get delayed for others reason, for example, this issue was dupe of other issue and we had doubts on where to proceed this.

Anyways will try to close out the review on this today.

**Comment by Shivam7-1** [comment] 2023-06-26 08:12
@abdulrahuman5196  Thanks for responding 😊

**Comment by abdulrahuman5196** [comment] 2023-07-04 13:09
Looking into the issue now

**Comment by abdulrahuman5196** [comment] 2023-07-04 13:14
And @sonialiap I am unable to reproduce this issue even after multiple tries in different ways on safari.

**Comment by ashimsharma10** [comment] 2023-07-04 13:39
@abdulrahuman5196 have you tried refreshing the page or trying with a brand new account?

**Comment by abdulrahuman5196** [comment] 2023-07-04 13:54
@ashimsharma10  yes. Tried now as well. No luck.

**Comment by Shivam7-1** [comment] 2023-07-04 14:47
> @Shivam7-1 On the proposal here [#21183 (comment)](https://github.com/Expensify/App/issues/21183#issuecomment-1600646881)
> 
> > the error is occurring in the CodesPage.js file. In the CodesPage component, the TwoFactorAuthActions.clearTwoFactorAuthData() function is being called in the cleanup of the useEffect hook, but that function does not exist in the provided code. This is causing an error and preventing the expected result.
> 
> I don't think the root cause is correct the function is present here
> 
> https://github.com/Expensify/App/blob/1fb53191783c2833022de427fb52b440f663336b/src/libs/actions/TwoFactorAuthActions.js#L7-L10



> Hi, @Shivam7-1 the general guideline for C+ review on a proposal is 24 hours. But it could get delayed for others reason, for example, this issue was dupe of other issue and we had doubts on where to proceed this.
> 
> Anyways will try to close out the review on this today.

Hii @abdulrahuman5196 I think the problem with the ScrollView component,  the Section component with the title "twoFactorAuth.keepCodesSafe".
In the Section component,  the View component with the `styles.twoFactorAuthCodesBox(props)` style applied.
Inside the View component, locate the View component with the `styles.twoFactorAuthCodesContainer` style applied.

For Fix this above view component issue I think we have to Modify the Text component within the View component to add a `numberOfLines={1} prop`.
 Hence This prop ensures that the text is displayed in a single line and does not overflow.

**Comment by shubham1206agra** [comment] 2023-07-06 17:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Web - Two-factor authentication is not fully visible
### What is the root cause of that problem?

The root cause is that the room name input is auto focused in the middle of screen transition. This will cause the transition to pause on Safari.
### What changes do you think we should make in order to solve the problem?

We need to focus the input after the screen transition already completes, similar to what we've done through out the app. There are 2 routes to go through this:

Route 1
1. Define `shouldDelayFocus` prop in `MagicCodeInput` component under `App/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/BaseTwoFactorAuthForm.js` file.
2. Need to correct and refactor the already existing logic of `shouldDelayFocus` in MagicCodeInput component.

Route 2
Define `onEntryTransitionEnd` prop function in `ScreenWrapper` component under `App/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js`.

Similar examples of route 2 used in the app are [here](https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/pages/EditRequestDescriptionPage.js#L29), [here](https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/pages/ReportWelcomeMessagePage.js#L55) and [here](https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/pages/settings/Payments/AddPayPalMePage.js#L47). 

I think we should go through route 2 for this issue as `shouldDelayFocus` is kind of hack solution because it uses timeout.
### What alternative solutions did you explore? (Optional)

Similar issue might be happening in other places so we should expand the issue to check other places as well.

**Comment by abdulrahuman5196** [comment] 2023-07-08 10:01
@shubham1206agra 's proposal here https://github.com/Expensify/App/issues/21183#issuecomment-1624020568

>We need to focus the input after the screen transition already completes, similar to what we've done through out the app. 

This is not true, we have mix of both `onEntryTransitionEnd` and `autofocus` uses through the app.

**Comment by abdulrahuman5196** [comment] 2023-07-08 10:03
I tried again but unable to reproduce this issue. It would be best to provide some way to reliabily reproduce this issue instead of one of multiple times tries.

Reached out in slack as well - https://expensify.slack.com/archives/C01GTK53T8Q/p1688810617233909

**Comment by shubham1206agra** [comment] 2023-07-08 10:40
> I tried again but unable to reproduce this issue. It would be best to provide some way to reliabily reproduce this issue instead of one of multiple times tries.
> 
> Reached out in slack as well - https://expensify.slack.com/archives/C01GTK53T8Q/p1688810617233909

I don't have a slack invite yet, so that's why I can't see it yet. But I am able to reproduce this quite consistently on my Mac M1 Pro machine inside Safari. If you want, we can setup a meet, and discuss this in length.

**Comment by shubham1206agra** [comment] 2023-07-08 10:42
> @shubham1206agra 's proposal here [#21183 (comment)](https://github.com/Expensify/App/issues/21183#issuecomment-1624020568)
> 
> > We need to focus the input after the screen transition already completes, similar to what we've done through out the app.
> 
> This is not true, we have mix of both `onEntryTransitionEnd` and `autofocus` uses through the app.

About this, maybe we should use route 1 as it will be much simpler to implement. About route 2, it may cause some issue on reloading the page.

**Comment by abdulrahuman5196** [comment] 2023-07-19 20:28
@sonialiap I am still unable to repro the issue. What should we do as next steps here?

And Kindly can you remove the 'Reviewing' label, it is making me miss this issue in the K2.

**Comment by mvtglobally** [comment] 2023-07-20 02:53
Issue not reproducible during KI retests. (First week)

**Comment by shubham1206agra** [comment] 2023-07-20 04:38
> @sonialiap I am still unable to repro the issue. What should we do as next steps here?
> 
> And Kindly can you remove the 'Reviewing' label, it is making me miss this issue in the K2.

This specific issue is not occurring but something else has came up. I think someone tried to fix it but some other issue came up with it

**Comment by sonialiap** [comment] 2023-07-24 14:22
I cannot reproduce. Looks like this issue has been fixed.

@shubham1206agra if there's a new issue, please report it so that an issue can be created and investigated

**Closed by sonialiap** 2023-07-24 14:22 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
