### ISSUE TITLE
[$1000]  iOS Safari - Additional cursor visible in wrong position when entering magic code in any page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20644] opened 2023-06-13 01:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open new.expensify.com in Safari on iOS.
2. Enter any email/phone.
3. Enter the magic code digits 1 by 1.
4. Notice that the blue vertical cursor stays in the first digit slot and moves slightly towards the right as we enter more digits.

## Expected Result: 
The blue vertical cursor should not be visible at all since it is not visible in any apps/phone browsers/desktop app/desktop browsers.
## Actual Result: 
The blue cursor is visible in iOS safari. Moreover, its position was wrong.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c6c947ff-73e6-42b5-874d-01609fd271c7

https://github.com/Expensify/App/assets/43996225/aa17d589-d7ee-48d2-b827-05b3b6c6b03d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686155622112579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149549af47f58f7a5</li>
        <li>Upwork Job ID: 1669721849027104768</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-06-13 07:11
> Thanks a lot for the input, I am not suggesting removal though, my proposal is about adding additional styling. Have verified that paste feature in Safari still works.

Using `caretColor` will raise warnings that the style property is not supported. I think the key to fixing this issue would be to figure out why the `caretHidden` prop works in iOS 16.2 but is broken in 16.4. What changed between these versions?

**Comment by strepanier03** [comment] 2023-06-13 22:24
As explained above I can't recreate without a real iOS device, I tried in Browserstack without any luck. 

I've asked for someone with an actual device to test [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1686695057961179).

**Comment by strepanier03** [comment] 2023-06-15 21:33
@conorpendergrast - I bumped for testing again since I don't have a physical iOS device to test this. The bump is [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1686864755979039) but if you have an iPhone maybe you can get it tested sooner.

**Comment by akinwale** [comment] 2023-06-16 04:01
Looks like this is a duplicate of https://github.com/Expensify/App/issues/19220

**Comment by Nikhil-Vats** [comment] 2023-06-16 07:31
@akinwale this is a different issue since an additional cursor is visible in iOS which shouldn't be there at all. You can check the video.

**Comment by conorpendergrast** [comment] 2023-06-16 08:34
I do have a physical iOS device, and I absolutely will test this!

**Comment by conorpendergrast** [comment] 2023-06-19 13:30
Agreed, that looks like an identical bug to https://github.com/Expensify/App/issues/19220, which was reported a month earlier. Thanks @s77rt, I missed that in my dupe issue check!

**Closed by conorpendergrast** 2023-06-19 13:30 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
