### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Saved search- Default search name in dropdown button shows policy ID when reopening search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50223] opened 2024-10-04 10:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Open workspace switcher and select a workspace.
4. Tap Filters icon.
5. Add any filter.
6. Tap Save search.
7. Note that the search name in the dropdown button and list does not show policy ID.
8. Open dropdown list.
9. Tap on the same saved search again.

## Expected Result:
The search name in the dropdown button will not show policy ID.

## Actual Result:
The search name in the dropdown button shows policy ID, while the search name in the list does not have policy ID.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2ac2bf86-5ca9-4f7e-9618-20ec5d2b231a

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843666631417893773</li>
        <li>Upwork Job ID: 1843666631417893773</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104344570</li>
<li>Nodebrute | Contributor | 104344571</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by IuliiaHerets** [comment] 2024-10-04 10:23
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-10-04 10:24
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-10-06 10:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saved search name shows policyID when selecting it from the popover.

### What is the root cause of that problem?
I think there are 2 problems here.

When we save a new search filter, the query and name will be the same, and if we switch to a workspace before creating the filter, the policyID will be included as the query and name.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/Search/AdvancedSearchFilters.tsx#L261-L263
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/actions/Search.ts#L54-L65

Selecting the saved search from the popover will update the route params, query and name, from the saved search query and name, in our case, it will be the same.

The first problem is the inconsistent name logic between the **search type button text**,
<img width="321" alt="image" src="https://github.com/user-attachments/assets/6b293485-ea22-496e-9e3f-0fceeb12b6c7">

and the **saved search text** in the popover.
<img width="414" alt="image" src="https://github.com/user-attachments/assets/cb2326c3-9179-41a5-96aa-bb313663333b">

The **search type button text** always uses the name if it exists,
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/Search/SearchTypeMenu.tsx#L222-L223

while the **saved search text** uses the name if the value is different than the query. If it's the same, it will build the name using `getSearchHeaderTitle`.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/Search/SearchTypeMenu.tsx#L115-L119

The second issue is `getSearchHeaderTitle` doesn't include the `policyID` attribute.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/SearchUtils.ts#L766-L769

### What changes do you think we should make in order to solve the problem?

We can update the `getSearchHeaderTitle` logic to include the `policyID` and it will make it consistent by showing the `policyID`.
```
const {type, status, policyID} = queryJSON;

let title = policyID ? `type:${type} status:${status} policyID:${policyID}` : `type:${type} status:${status}`;
```

<img width="385" alt="image" src="https://github.com/user-attachments/assets/682cf35a-c75d-4895-bf71-4041d2d6e167">

But we can also update the name logic to make it consistent.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/Search/SearchTypeMenu.tsx#L222-L223

```
let title: string | undefined = undefined;
if (!isCannedQuery) {
    title = searchName && searchName !== queryJSON.inputQuery 
        ? searchName 
        : SearchUtils.getSearchHeaderTitle(queryJSON, personalDetails, cardList, reports, taxRates);
}
```

**Comment by OfstadC** [comment] 2024-10-08 14:33
Added this to Wave Control - posted in Slack for confirmation

**Comment by suneox** [comment] 2024-10-09 12:15
Can anyone reproduce this issue on the latest main?

**Comment by bernhardoj** [comment] 2024-10-09 14:13
Still reproducible.

https://github.com/user-attachments/assets/f5a2c9c4-9aad-47b4-b937-2fcd679d85ae

**Comment by suneox** [comment] 2024-10-09 18:24
Thanks for all the proposals. Based on the expected behavior for this issue is that `The search name in the dropdown button will not show policy ID.` and this issue only occurs on small devices. 
Therefore, @bernhardoj proposal does not meet the expected behavior. 
@Nodebrute [proposal](https://github.com/Expensify/App/issues/50223#issuecomment-2394016127) LGTM

🎀 👀 🎀 C+ reviewed

**Comment by OfstadC** [comment] 2024-10-22 17:42
@suneox Could you please complete the BZ checklist? Thank you ! 😃

**Comment by suneox** [comment] 2024-10-22 17:58
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/49446
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. [Link to comment](https://github.com/Expensify/App/pull/49446/files#r1811158729)
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by OfstadC** [comment] 2024-10-24 18:14
## Payment Summary

- @suneox paid $250 via Upwork 
- @Nodebrute paid $250 via Upwork

**Closed** 2024-10-24 18:15 UTC
Labels: External, Daily, Awaiting Payment, Bug
