### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] - Paid expenses do not have "Paid" label when the expenses are grouped expenses

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52369] opened 2024-11-12 10:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation** (hyperlinked to channel name):

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses.
4. Pay the expenses.
5. Go to Search > All.

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2b6c006b-a2dd-449e-b60a-0986cd7bcb88

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856301612409763010</li>
        <li>Upwork Job ID: 1856301612409763010</li>
        <li>Last Price Increase: 2024-11-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by Julesssss** [comment] 2024-11-12 11:42
> Reproducible in production?: N/A - new feature, doesn't exist in prod

Demoting

**Comment by Julesssss** [comment] 2024-11-12 11:44
Hi @IuliiaHerets, the reproduction steps aren't added yet. Could you please tag me when they are listed, thanks.

**Comment by klajdipaja** [comment] 2024-11-12 14:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The status of the transaction does not show as paid when the transaction is part of a thread with multiple transaction and all transactions are paid.

### What is the root cause of that problem?
To build the rows of the search results we call `SearchUIUtils.getSections` in this line https://github.com/klajdipaja/Expensify-App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/components/Search/index.tsx#L209.
When the search is for all expenses it then calls: https://github.com/klajdipaja/Expensify-App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/SearchUIUtils.ts#L212C10-L212C33.

In this function we try to resolve the action of the transaction in this line:
https://github.com/klajdipaja/Expensify-App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/SearchUIUtils.ts#L227
The root cause is then hidden on this block:
https://github.com/klajdipaja/Expensify-App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/SearchUIUtils.ts#L253-L256
because of this part of the conditon which is true: `(isTransaction && !data[key].isFromOneTransactionReport)`
To sum it up, it seems like it has been the intended behaviour that when the transaction is part of multiple transaction report it will show the `View` action.

### What changes do you think we should make in order to solve the problem?

We should remove that part of the condition that checks for single transaction and make the conditon into this:
```
    if (!isTransaction && !isReportEntry(key)) {
        return CONST.SEARCH.ACTION_TYPES.VIEW;
    }
```
And rely on the action returned by the backend for this transaction instead of using the isSettled method which relies on the report that the transaction belongs to because the report does not have the right data to understand individual transaction status.

To do that we can at this line after when we resolved the transaction:
https://github.com/klajdipaja/Expensify-App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/SearchUIUtils.ts#L257.
this block:
```
   if (transaction?.action === CONST.SEARCH.ACTION_TYPES.PAID) {
        return CONST.SEARCH.ACTION_TYPES.PAID;
    }
```



### What alternative solutions did you explore? (Optional)

**Comment by Anaslancer** [comment] 2024-11-12 16:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Paid expenses do not have "Paid" label when the expenses are grouped expenses

### What is the root cause of that problem?
Whenever we pay several transactions once, `isFromOneTransactionReport` of `transaction` is always `false`.
Btw, in this below code, if `isFromOneTransactionReport` is false, getAction return `'view'`.
https://github.com/klajdipaja/Expensify-App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/SearchUIUtils.ts#L253-L255
So we are watching the `'view'` label in expenses search list.

### What changes do you think we should make in order to solve the problem?
If we want to see 'paid' at the moment, we should remove this below condition.
https://github.com/klajdipaja/Expensify-App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/SearchUIUtils.ts#L253-L255
Here is the changed code.
```
    if (!isTransaction && !isReportEntry(key)) {
        return CONST.SEARCH.ACTION_TYPES.VIEW;
    }
```

### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by IuliiaHerets** [comment] 2024-11-12 17:03
@Julesssss Added steps, sorry of this 
![image](https://github.com/user-attachments/assets/d690b6cc-ec2d-415d-a815-10d3ab6fed66)

**Comment by luacmartins** [comment] 2024-11-12 22:06
I'll be handling this since I'm the author of the PR that caused the regression.

**Comment by Julesssss** [comment] 2024-11-13 10:13
Thanks @luacmartins, usubscribing

**Comment by luacmartins** [comment] 2024-11-13 19:36
Not ready to be paid, we just reverted the PR and I'll be working on a fix for this.

**Comment by luacmartins** [comment] 2024-11-27 22:54
This is done

**Closed by luacmartins** 2024-11-27 22:54 UTC
Labels: Engineering, Weekly, Internal, Awaiting Payment, Bug
