### ISSUE TITLE
Threads - Pin icon doesn't disappear right after user leaves a thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46084] opened 2024-07-23 23:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat
3. Send a message
4. Hover over the message and click on reply in thread
5. Send a message inside the thread
6. Click on the header of the thread
7. Click on Pin
8. Click on Leave
9. Click on the pinned thread chat you just left

## Expected Result:
When clicking 'Leave Thread' in step 8, the pin icon in the thread chat should either disappear, indicating the thread is no longer pinned, or persist when revisiting the thread later, maintaining its pinned status

## Actual Result:
When clicking 'Leave Thread' in step 8, the pin icon remains in the left thread chat, but it disappears when revisiting the chat thread before joining

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5d5187d5-eaef-4ff1-9d51-784aee49da14

![27](https://github.com/user-attachments/assets/404858fc-0469-428f-868e-799b56b3c447)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-23 23:32
We think that this bug might be related to #vip-vsp

**Comment by marcaaron** [comment] 2024-07-23 23:46
Not deploy blocker worthy.

**Comment by tsa321** [comment] 2024-07-24 06:24
Maybe the the expected result is not to automatically unpin the thread report, then this issue would be the back end issue.

**Comment by Tony-MK** [comment] 2024-07-24 07:10
This issue is not reproducible on the latest main.

**Comment by stephanieelliott** [comment] 2024-07-25 20:36
I'm also unable to repro this. Reproduction aside, seeing as this is a pretty minor issue that only affects threads and falls under a project that's currently paused, IMO this is not worth investigating much further.  I think we should close this as `Not a priority`, @marcaaron what do you think?

**Comment by marcaaron** [comment] 2024-07-26 18:42
Works for me!

**Closed by marcaaron** 2024-07-26 18:42 UTC
Labels: Engineering, Daily, Bug
