### ISSUE TITLE
[HOLD FOR PAYMENT JUNE 21][$250] "Uploading attachment" text too close to message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42297] opened 2024-05-16 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715818269205899

## Action Performed:
1. Open any report
2. Send a image with text

## Expected Result:
There should be a small gap between the text you entered and the "Uploading attachment..." text
## Actual Result:
There is no gap between them
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-05-15 at 20 09 25@2x](https://github.com/Expensify/App/assets/38435837/6e43b491-d60b-45b0-b9a9-1ca996446071)

![Snip - (147) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/f835773d-3aee-4ab0-bfaa-a786e2737bcf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f281695ab48cd898</li>
        <li>Upwork Job ID: 1791158555071238144</li>
        <li>Last Price Increase: 2024-05-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by nkdengineer** [comment] 2024-05-17 03:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no gap between them

### What is the root cause of that problem?
- When sending a message with text, we use [this](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L3453) optimistic message text.
### What changes do you think we should make in order to solve the problem?
- We can add an additional ```\n``` character to the above to make a gap.

### What alternative solutions did you explore? (Optional)
- NA

**Comment by manishram** [comment] 2024-05-21 06:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the issue, it is mentioned that the "Uploading attachment" text which shows when we actually add any attachment while sending a message shows very close to the actual message. This makes "Uploading attachment" text indistinguishable from the actual message. And hence making a bad UI.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L3453

### What changes do you think we should make in order to solve the problem?
* Instead of just making space, I think we should also change the color of the text a little different from the font color of the actual message. This can be a little bit greyish. At the same time, this text should also animate fade-in - fade-out slowly to give the user a clear idea that "Uploading attachment" is a system information that will stay there until the attachment uploads successfully.


https://github.com/Expensify/App/assets/22790904/e1ea758b-7ee1-4c31-8f61-8b02bbcc288b


### What alternative solutions did you explore? (Optional)
NA

**Comment by slafortune** [comment] 2024-05-23 21:13
There is a PR for review - I'll be on vacation until June 4th, so adding a BZ in the meantime.  I'll take this back on the 4th if needed.

**Comment by mallenexpensify** [comment] 2024-06-13 00:10
PR merged today 
https://github.com/Expensify/App/pull/42516

**Comment by slafortune** [comment] 2024-06-13 21:17
Payment due June 19th with no regressions.

**Comment by mallenexpensify** [comment] 2024-06-18 19:35
@slafortune , looks like it should be paid on the 21st, based on [PR hitting production on the 14th](https://github.com/Expensify/App/pull/42516#issuecomment-2168862921). updated the title to reflect.

**Comment by slafortune** [comment] 2024-06-19 14:38
OHHH!  Thanks @mallenexpensify, my mistake 👍

**Comment by slafortune** [comment] 2024-06-21 18:12
@dragnoir offer sent here - https://www.upwork.com/nx/wm/offer/102829200
@thesahindia as C+ is due $250 via NewDot

**Closed** 2024-06-21 18:52 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug

**Comment by kidroca** [comment] 2024-07-05 10:07
I'm a bit unsure about the need for a custom `<uploading-attachment>` element to fix this issue. Does it serve any purpose beyond addressing styling problems? In other cases, we use `<br />` to handle new line gaps. Could we have used `<br />` elements for the optimistic content as well?

I'm working on replacing the "Uploading attachment..." text with the actual attachment. Should I keep the `<uploading-attachment>` custom element, or is it okay to remove it once the text is replaced with a preview of the attachment?

**Comment by shawnborton** [comment] 2024-07-05 12:04
@kidroca I think you make some good points. I am cool with whatever solution you think is best, as long as we achieve the desired design/style where there is a clear space between the message and the image below it. So if you want to undo the custom element, that is fine by me.

**Comment by JmillsExpensify** [comment] 2024-07-19 15:47
$250 approved for @thesahindia
