### ISSUE TITLE
[$1000] Skeleton-view is right oriented when scrolling up and loading new messages on Android

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#13636] opened 2022-12-15 19:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Have a chat with 100+ comments on it
2. On Android, scroll up quickly, so that you cause the chat to need to load more chats

## Expected Result:
The skeleton view that indicated we're loading more chats is left-oriented like on other platforms.

## Actual Result:
The skeleton view is right-oriented

## Workaround:
N/A

## Platform:
Where is this issue occurring?
- Android

**Version Number:** `1.2.40`
**Reproducible in staging?:**  Y
**Reproducible in production?:**  Y
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Notes/Photos/Videos:**
https://user-images.githubusercontent.com/4741899/207949730-7c6c4800-24b1-427b-9590-7f296d098353.mp4

**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @yuwenmemon 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671130333575879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01383ef4f4c88c4510</li>
        <li>Upwork Job ID: 1603522970016489472</li>
        <li>Last Price Increase: 2022-12-15</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2022-12-16 01:41
**Proposal**

The inverted FlatList on Android set the `inverted` to `false` and use translate style to make it inverted. 

https://github.com/Expensify/App/blob/3620bf2fbeba22429e1497802c183626b5803fad/src/components/InvertedFlatList/index.android.js#L6-L24

As you can see, we also set the CellRendererComponent and apply the `styles.inverted` to the cell. So, what we need to do is to also apply the style to the footer component.

```diff
<BaseInvertedFlatList
    // eslint-disable-next-line react/jsx-props-no-spreading
    {...props}
    ref={ref}

    // Manually invert the FlatList to circumvent a react-native bug that causes ANR (application not responding) on android 13
    inverted={false}
    style={styles.invert}
    verticalScrollbarPosition="left" // We are mirroring the X and Y axis, so we need to swap the scrollbar position

    CellRendererComponent={InvertedCell}
+   ListFooterComponentStyle={styles.invert}
/>

```

**Comment by kganakga** [comment] 2022-12-16 02:19
**Proposal** 

the skeleton view was right-oriented because the BaseInvertedFlatList component was configured to invert the layout of the FlatList. This was done by setting the inverted prop to false and applying the styles.invert style to the FlatList component.
this  line of code caused the skeleton view to be right-oriented:
inverted={false}
style={styles.invert}
By setting the inverted prop to false, the layout of the FlatList was inverted, which caused the skeleton view to be right-oriented. The styles.invert style was also applied to further invert the appearance of the FlatList.

To fix the issue and display the skeleton view in a left-oriented manner, you can set the inverted prop to true and remove the styles.invert style. This will restore the default, non-inverted layout of the FlatList and display the skeleton view in a left-oriented manner.

I hope this helps to clarify the cause of the issue and how to fix it. I have written code that can solve it.

**Comment by mananjadhav** [comment] 2022-12-16 02:53
Thanks for the proposal folks. @bernhardoj [proposal](https://github.com/Expensify/App/issues/13636#issuecomment-1354059071) looks good here.  

I am also tagging @mountiny and @Beamanator for second review as this broken when we moved `InvertedFlatList` to `index.android.js` in this PR https://github.com/Expensify/App/pull/12820.

@sketchydroide all yours.

**Comment by Beamanator** [comment] 2022-12-16 07:50
That sooounnnds good to me, what do you think @mountiny ? 

Also I think it could be good to get @hannojg 's opinion here since they've been working on a lot of Android fixes lately, and they're the author of that PR that caused this issue. @hannojg would you mind taking a look at [this proposal](https://github.com/Expensify/App/issues/13636#issuecomment-1354059071) which could fix this issue that was probably caused by [your PR](https://github.com/Expensify/App/pull/12820/files)? :D

**Comment by hannojg** [comment] 2022-12-16 08:16
The proposal from @bernhardoj looks good to me! Setting the inverted back to true is currently not an option due to a bug in the Android framework on Android 13.

Good catch!

**Comment by s77rt** [comment] 2022-12-16 10:31
Shouldn't we fix the bug in RN instead of the style workaround?
@hannojg Can you link the RN bug you mentioned on your PR?

**Comment by sketchydroide** [comment] 2022-12-16 11:04
I think we can go with @bernhardoj suggestion then

**Comment by bernhardoj** [comment] 2022-12-16 11:46
Applied on Upwork. I will open the PR today or tomorrow.

**Comment by hannojg** [comment] 2022-12-16 12:02
Do we have a video of the bug occurring? While I agree with @bernhardoj approach to apply the style to other parts of the flatlist (instead of inverting the list by using the `invert` prop), I am not sure if the footer thing actually fixes the whole issue? The proposal might need another pair of eyes 😅

**Comment by mountiny** [comment] 2022-12-16 12:40
Nice find! I think @0xmiroslav proposal would be great once we start using the `InvertedFlatList` in other places too! For now the first solution works fine and is quick and simple.

**Comment by bernhardoj** [comment] 2022-12-16 16:43
I have opened the PR, however I'm currently unable to test it on iOS Safari because of the 403 sign in problem.

**Comment by sketchydroide** [comment] 2022-12-22 16:37
the PR has been merged

**Comment by sketchydroide** [comment] 2022-12-27 10:43
still in QA at the moment as far as I can tell, I think QA is on holidays, so it might take some time

**Comment by sketchydroide** [comment] 2022-12-29 12:16
ok this is already in prod, I don't know if everyone has been payed yet, @kevinksullivan when come back next week can you check that?

**Comment by mananjadhav** [comment] 2023-01-02 06:18
This was deployed to production 5 days back so should be ready for payout in 2 days! Title isn't updated but payment is pending.

**Comment by sketchydroide** [comment] 2023-01-02 10:43
thanks @mananjadhav

**Comment by mananjadhav** [comment] 2023-01-03 10:11
@sketchydroide @kevinksullivan This is ready for payout today!

**Comment by sketchydroide** [comment] 2023-01-03 10:17
@kevinksullivan maybe you can take of this when you come in tomorrow

**Comment by mananjadhav** [comment] 2023-01-06 02:30
Accepted @kevinksullivan. Thanks for helping out here.

**Comment by bernhardoj** [comment] 2023-01-06 02:31
@kevinksullivan Accepted.

**Comment by mananjadhav** [comment] 2023-01-10 06:51
@kevinksullivan Is the contributor paid out too? Anything else pending here or are we good to close this one out?

**Comment by bernhardoj** [comment] 2023-01-10 07:03
I already get paid.

**Comment by mananjadhav** [comment] 2023-01-10 07:03
Thanks for confirming @bernhardoj. @kevinksullivan anything else pending here?

**Comment by sketchydroide** [comment] 2023-01-10 10:37
if both of you ae payed I think we can close it

**Closed by sketchydroide** 2023-01-10 10:37 UTC
Labels: Reviewing, External, Daily, Bug
