### ISSUE TITLE
[$500] Chat - Edited displayed for codeblock on no edit

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32982] opened 2023-12-13 15:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Open any report
3. Send 3 bactick codeblock eg: ```Hello```
4. Copy the sent codeblock to clipboard
5. Paste and send again
6. Edit the message sent in step 5
7. Make codeblock single line (not removing spaces, just making it single line)
8. Save and observe that now it displays edited below

## Expected Result:
App should not display 'edited' label is no changes is done to message

## Actual Result:
App displays 'edited' label to codeblock even when no changes is done to block (only made it single line as we have sent it on very first instance)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bd85606e-bb3b-47b4-af89-e1e5c75e0fb3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8b681d69f8f211e</li>
        <li>Upwork Job ID: 1734963988247306240</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-12-13 16:57
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
App displays 'edited' label to codeblock even when no changes is done to block (only made it single line as we have sent it on very first instance)
### What is the root cause of that problem?
The root cause is that  `htmlToMarkdown` in ExpensiMark adds the new line code `\n` for `code` so that `originalCommentMarkdown` get different from `textForNewComment` when we delete new line code in editing.
https://github.com/Expensify/App/blob/0e99676c5579306ff76581820e0cb1f72bbc2e12/src/libs/actions/Report.ts#L1242
### What changes do you think we should make in order to solve the problem?
We need to eliminate new line code from `originalCommentMarkdown` when comparing to `textForNewComment`.
https://github.com/Expensify/App/blob/0e99676c5579306ff76581820e0cb1f72bbc2e12/src/libs/actions/Report.ts#L1242
to
```
if (originalCommentMarkdown.replaceAll('\n', "") === textForNewComment) {
        return;
    }
```
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by jliexpensify** [comment] 2023-12-15 00:12
The advice (internally) was to close this one - https://expensify.slack.com/archives/C01SKUP7QR0/p1702598495284639?thread_ts=1702595354.887429&cid=C01SKUP7QR0

**Closed by jliexpensify** 2023-12-15 00:12 UTC
Labels: External, Daily, Help Wanted, Bug
