### ISSUE TITLE
Search - Search router text color is gray

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51002] opened 2024-10-17 10:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/50815
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Light theme should be used.

1. Navigate to https://staging.new.expensify.com/
2. Log in with a Gmail account that has some expenses
3. Navigate to Search - Filters
4. Set any filter that'll give results and click on the "View results" button

## Expected Result:
Search router text color should be black

## Actual Result:
Search router text color is gray.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b8854b3e-98cc-4710-aeda-e2d0f3f3eee7

![Bug6637288_1729143309448!Capture](https://github.com/user-attachments/assets/94f27642-567b-4979-8748-23946242e54f)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-10-17 10:48
We think this issue might be related to the #collect project.

**Comment by FitseTLT** [comment] 2024-10-17 12:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search - Search router text color is gray

### What is the root cause of that problem?
We are setting `searchInputStyle` here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/components/Search/SearchRouter/SearchRouterInput.tsx#L108
which sets the color to textSupporting
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/styles/index.ts#L3617
### What changes do you think we should make in order to solve the problem?

If we want to set it to black we can set the color to `themeTextColor`
```
                        inputStyle={[styles.searchInputStyle, styles.themeTextColor, inputWidth, styles.pl3, styles.pr3]}

```
### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2024-10-17 15:42
I'll work on this fix since it seems like we had a bad conflict resolution that undid the changes from [my PR](https://github.com/Expensify/App/pull/50815)

**Comment by luacmartins** [comment] 2024-10-17 15:53
PR in review

**Comment by luacmartins** [comment] 2024-10-17 16:11
PR being CPed

**Comment by luacmartins** [comment] 2024-10-17 17:17
Fixed in staging

**Closed by luacmartins** 2024-10-17 17:17 UTC
Labels: Reviewing, Engineering, Weekly, Hourly, Bug
