### ISSUE TITLE
[RE-test] [VIP-VSB] [$500] mWeb-composer-Keyboard quickly pops up when clicking back while emoji picker is open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36552] opened 2024-02-14 23:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Open a chat
2. Click inside the compose box
3. Click on the emoji picker
4. Click on the system back button

## Expected Result:
Keyboard should not pop up

## Actual Result:
Keyboard pops up quickly

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f6e3419f-7d20-4ce3-a4ec-0b231e31ce35

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3a4265cd18f27fb</li>
        <li>Upwork Job ID: 1757911388775432192</li>
        <li>Last Price Increase: 2024-06-26</li>
    </ul>
</details>

**Comment by andreasnw** [comment] 2024-02-15 02:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
pressing the soft back button on Android while using the emoji modal, it closes the modal, flashes the keyboard, and then takes the user back to the previous page. we don't want the keyboard to pops out.

### What is the root cause of that problem?
We called the `EmojiPickerButton` within `ReportActionCompose`. It includes the `onModalHide` prop, which triggers a `focus` function. This function is responsible for bringing up the keyboard. 

https://github.com/Expensify/App/blob/634f7666b049aced9f6ac2ae5565508ec07d813e/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L464-L470

notes: i've also noticed some inconsistencies in the Android Native app where the keyboard doesn't always pop up when this function is called.

### What changes do you think we should make in order to solve the problem?

if we reckon it's unnecessary for the keyboard to pop up after closing the emoji picker in any scenario, we can go ahead and remove the `onModalHide` props from `EmojiPickerButton`.

```
                           <EmojiPickerButton
                                isDisabled={isBlockedFromConcierge || disabled}
                                onEmojiSelected={(...args) => composerRef.current.replaceSelectionWithText(...args)}
                                emojiPickerID={report.reportID}
                                shiftVertical={emojiShiftVertical}
                            />
```

### What alternative solutions did you explore? (Optional)
depending on what we want it to do, we could also opt to call a different function instead of `focus` when the emoji modal closes.

**Comment by agent3bood** [comment] 2024-02-15 07:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb-composer-Keyboard quickly pops up when clicking back while emoji picker is open

### What is the root cause of that problem?

`EmojiPicker.hideEmojiPicker` is supposed to handle this case by checking `isNavigation` arg.
But the parent component `PopoverWithMeasuredContent` does not pass this arg to the `onClose` handler.


### What changes do you think we should make in order to solve the problem?
- Update `PopoverWithMeasuredContent.onClose` signature to include `isNavigation` arg.
- When modal is closed by navigation (back button), call `PopoverWithMeasuredContent.onClose` with `isNavigation` arg set to true.
- When modal is closed by clicking outside, call `PopoverWithMeasuredContent.onClose` with `isNavigation` arg set to false.

### What alternative solutions did you explore? (Optional)

n/a

**Comment by strepanier03** [comment] 2024-02-16 04:36
This https://github.com/Expensify/App/issues/35756 is really closely related. I'm thinking of closing this in favor or that one.

**Comment by allroundexperts** [comment] 2024-02-19 03:54
@strepanier03 I don't think the two are related. This one is about the keyboard flashing for a short time when pressing the `back` button in the header. The one you shared is about incorrect navigation when pressing the hardware back button.

**Comment by allroundexperts** [comment] 2024-02-19 04:13
Although, once #35756 is fixed, this will become less annoying because the user would remain on the same screen. Pressing `back` button in that case would lead to the closing of the emoji picker menu and showing up of the keyboard with the composer being focused. I think this would be desirable in that case. Let's hold this on #35756 and see if this is an issue after the former is fixed.

**Comment by strepanier03** [comment] 2024-02-23 04:01
Sounds good @allroundexperts!

**Comment by strepanier03** [comment] 2024-03-11 04:27
HOLD GH still open.

**Comment by strepanier03** [comment] 2024-03-19 21:40
Hold GH still open.

**Comment by strepanier03** [comment] 2024-04-05 04:01
Still open.

**Comment by strepanier03** [comment] 2024-04-16 22:21
HOLD GH still open.

**Comment by strepanier03** [comment] 2024-05-03 22:59
Still on hold.

**Comment by strepanier03** [comment] 2024-05-22 00:15
HOLD GH is closed so we can retest this.

**Comment by mvtglobally** [comment] 2024-06-05 21:22
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment] 2024-06-14 03:43
Thank you @mvtglobally - Will wait for second test and then close if still unreproducible.

**Comment by strepanier03** [comment] 2024-06-26 23:06
I'm going to close this out, I can't repro and neither can applause.

**Closed by strepanier03** 2024-06-26 23:06 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug, retest-weekly
