### ISSUE TITLE
[Awaiting Payment August 27th] [$500] Chat - UX covers message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44388] opened 2024-06-25 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-17
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Admin > plus sign
2. Add title and Assignee
3. Go to Quick Action and assign task
4. Add title and confirm

## Expected Result:
UX should not cover the message

## Actual Result:
UX covers the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ab12b35a-8232-4155-9fc6-d32a50fbc5d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eec125fcb90e14fe</li>
        <li>Upwork Job ID: 1805999145742342542</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment] 2024-06-25 12:50
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-25 12:51
e think that this bug might be related to #vip-vsp

**Comment by kevinksullivan** [comment] 2024-06-26 21:56
@lanitochka17 I am unable to reproduce this actually. Are there more specific steps I need to follow than those you added in the post? 

![image](https://github.com/Expensify/App/assets/22508290/aa66d5e7-6aa6-45bc-bfa1-88f258802885)

**Comment by iCodePrograms** [comment] 2024-06-26 22:54
> @lanitochka17 I am unable to reproduce this actually. Are there more specific steps I need to follow than those you added in the post?
> 
> ![image](https://private-user-images.githubusercontent.com/22508290/343353632-aa66d5e7-6aa6-45bc-bfa1-88f258802885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDI0NjUsIm5iZiI6MTcxOTQ0MjE2NSwicGF0aCI6Ii8yMjUwODI5MC8zNDMzNTM2MzItYWE2NmQ1ZTctNmFhNi00NWJjLWJmYTEtODhmMjU4ODAyODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIyNDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNTcwMDc5NGMxYjdiODRlYzY0ZGFlOGYwYzliYmQzNjcwNzcxOTE3Y2UxNGNjYTI2YTkyYTY4YTEyZWU4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nv7jWjBCwR7dUrvwraH7OTtjUIBGsrGbX7pBaq-5McY)

Again coming in from Upwork, I believe we would require to add another task to reproduce the issue and a specific mode of display which is causing the issue

**Comment by iCodePrograms** [comment] 2024-06-26 23:09
Contributor details
Your Expensify account email: shamabegum88@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f8324b203ccf973f

**Comment by kevinksullivan** [comment] 2024-06-27 17:34
>Again coming in from Upwork, I believe we would require to add another task to reproduce the issue and a specific mode of display which is causing the issue

@iCodePrograms can you elaborate? I took the `Help wanted` label off here and am trying to reproduce.

**Comment by iCodePrograms** [comment] 2024-06-28 01:16
Hi @kevinksullivan, to be able to reproduce the error
Click **New Workspace** ->
**Back button (left arrow)** ->
Click on **#admins** channel ->
Click on the **+** button beside the chat box ->
**Assign Task** ->
Enter any title ->
Select Assignee ->
**Create Task**->
Click on the **+** button in the menu to find Quick Action **Assign Task** ->
Enter title ->
**Create Task**
You should see the error
something like this
![image](https://github.com/Expensify/App/assets/142686837/ce153269-ac31-4202-9209-1ee685cb2612)
I'm using Windows OS by the way I can reproduce it too, we might need to extend the scope of occurrence in details of the issue.

**Comment by Julesssss** [comment] 2024-07-09 14:03
Bumping the bounty here. It's an important issue to resolve as it can appear without warning in other cases. 

For example, it appeared [here](https://github.com/Expensify/App/issues/44992) within the invoices flow.

**Comment by Julesssss** [comment] 2024-07-09 14:04
These issues also appear related: 
- https://github.com/Expensify/App/issues/43571#issuecomment-2177744210
- https://github.com/Expensify/App/issues/42795

**Comment by Julesssss** [comment] 2024-07-09 14:12
@allgandalf yeah 👍

**Comment by wasxxm** [comment] 2024-07-09 20:33
I just pulled the latest forked version of the repo, and I am no longer able to reproduce the above error; I was able to produce it a few hours ago. Has it been fixed?

**Comment by wasxxm** [comment] 2024-07-10 01:32
# Proposal
### Please re-state the problem that we are trying to solve in this issue
After adding a few tasks or invoices, a part of the background image UX should not cover the message; however, it currently does in that chat conversation window, and it feels broken.

### What is the root cause of that problem?
The root cause of the problem is the <InvertedFlatList../> in the /src/pages/home/report/ReportActionsList.tsx starting at line 683. The InvertedFlatList inherits from BaseInvertedFlatList, which in turn inherits from FlatList with an "inverted" parameter. This parameters applies  _transform: scaleY(-1)_ to the list items flipping the list vertically upside down.

This creates a new stack of elements inside the list which causes the z-index property not to respect the originally assigned z-index value; we, therefore, see that background image coming on top of the list items.

### What changes do you think we should make in order to solve the problem?

We need to do the following steps:
1. Remove  \<AnimatedEmptyStateBackground /> from /src/components/ReportActionItem/MoneyReportView.tsx at line 62, 
2. Add the same (i.e. \<AnimatedEmptyStateBackground />) to /src/pages/home/report/ReportActionsList.tsx before line 683.
3. Replace line 46 of /src/pages/home/report/AnimatedEmptyStateBackground.tsx having the existing code:

` <View style={StyleUtils.getReportWelcomeBackgroundContainerStyle()}>`

with:

` <View style={[StyleUtils.getReportWelcomeBackgroundContainerStyle(), {height: '100%'}]}>`

### What alternative solutions did you explore? (Optional)
I also tried removing the background image altogether by doing step 1 and leaving everything else the same. It does not actually solve the problem but removes the annoying background messing up with the text.

**Comment by Julesssss** [comment] 2024-07-10 09:45
> I just pulled the latest forked version of the repo, and I am no longer able to reproduce the above error; I was able to produce it a few hours ago. Has it been fixed?

I [asked](https://expensify.slack.com/archives/C9YU7BX5M/p1720604680878809) QA for a retest 👍

**Comment by wasxxm** [comment] 2024-07-10 09:58
> > I just pulled the latest forked version of the repo, and I am no longer able to reproduce the above error; I was able to produce it a few hours ago. Has it been fixed?
> 
> I [asked](https://expensify.slack.com/archives/C9YU7BX5M/p1720604680878809) QA for a retest 👍

I was able to reproduce the bug and it happens for all UIs involving the InvertedFlatList; I have suggested a solution above.

**Comment by kbecciv** [comment] 2024-07-10 13:44
Issue reproducible

https://github.com/Expensify/App/assets/93399543/2ad7c39d-58e0-47d0-a97b-83279a6a427d

**Comment by wasxxm** [comment] 2024-07-12 13:25
https://github.com/Expensify/App/issues/44388#issuecomment-2219303604
Proposal Updated

**Comment by wasxxm** [comment] 2024-07-13 08:02
> Can you please explain why the issue is occurring (RCA) along with **links** to our codebase
> Sorry but i really don't understand what you are really trying to explain here, can you be more specific in terms of what the ideal behaviour should be and why the inconsistency is happening.

Let me explain it in more simple terms: 

In the file https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.tsx at line 684, you can see <InvertedFlatList .. />. This component is responsible for rendering the UI for the messages in the chat window such as the tasks, invoices, and welcome texts, in a list. A closer inspection of the component's CSS styling reveals that it has a CSS rule _transform: scaleY(-1)_ which flips the list upside down. This was done to display the latest messages at the bottom of the chat; had it not been applied, you will end up seeing the newest chat/messages at the very top of the chat list.

However, this introduces a problem in the way browsers treat the _z-index_ property of an HTML element. Whenever a CSS based transformation, such as scaling in above case, is applied on an HTML element, it loses its original z-index property in relation to other elements in the DOM.

The same phenomenon happens in this case. The messed up UI you see in this case is because of a DIV with a background image coming in front of the chat list, even though it has a z-index of -1. If you go to line 63 of the file: https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemCreated.tsx, you can see this component \<AnimatedEmptyStateBackground />; this is the component rendering a DIV with a background image using CSS. So as soon as the _transform: scaleY(-1)_ is applied on the list, as I mentioned above, this background component comes to the front of the chat list UI.

The ideal behaviour should be not to flip the list of chat list UI; instead, a reverse sorting should have been applied at the backend, so that latest messages appear at the bottom of the chat without any UI tricks.

> Does that happen on staging as well, or is it happening only when we apply your suggested solution?

Yes, it happens at the staging as well. I can see through my Google Chrome Network Logs that the API endpoint: https://staging.expensify.com/api/OpenReport? returns an array inside onyxData with duplicate or almost similar objects for a single task with  "actionName": "ADDCOMMENT",:

```
{
    "onyxMethod": "merge",
    "key": "reportActions_4082806742617648",
    "value": {
        "1902385733061192700": {
            "person": [
                {
                    "type": "TEXT",
                    "style": "strong",
                    "text": "Waseem Khan"
                }
            ],
            "actorAccountID": 17802616,
            "message": [
                {
                    "type": "COMMENT",
                    "html": "task for sfefefefef",
                    "text": "task for sfefefefef",
                    "isEdited": false,
                    "whisperedTo": [],
                    "isDeletedParentAction": false,
                    "deleted": "",
                    "reactions": []
                }
            ],
            "originalMessage": {
                "html": "task for sfefefefef",
                "lastModified": "2024-07-13 07:26:55.132",
                "taskReportID": 617253907972382
            },
            "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/285f0f984f8c54c9ca2c386d0e16587f5d98e416_128.jpeg",
            "created": "2024-07-13 07:26:55.132",
            "timestamp": 1720855615,
            "reportActionTimestamp": 1720855615132,
            "automatic": false,
            "actionName": "ADDCOMMENT",
            "shouldShow": true,
            "reportActionID": "1902385733061192700",
            "previousReportActionID": "1283128664733577895",
            "lastModified": "2024-07-13 07:26:55.132",
            "childReportID": "617253907972382",
            "childType": "task",
            "childReportName": "sfefefefef",
            "childOwnerAccountID": 17802616,
            "childManagerAccountID": 17802616,
            "whisperedToAccountIDs": []
        },
        "1283128664733577895": {
            "person": [
                {
                    "type": "TEXT",
                    "style": "strong",
                    "text": "Waseem Khan"
                }
            ],
            "actorAccountID": 17802616,
            "message": [
                {
                    "type": "COMMENT",
                    "html": "task for sdcsfds",
                    "text": "task for sdcsfds",
                    "isEdited": false,
                    "whisperedTo": [],
                    "isDeletedParentAction": false,
                    "deleted": "",
                    "reactions": []
                }
            ],
            "originalMessage": {
                "html": "task for sdcsfds",
                "lastModified": "2024-07-13 07:26:45.954",
                "taskReportID": 6672766817607404
            },
            "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/285f0f984f8c54c9ca2c386d0e16587f5d98e416_128.jpeg",
            "created": "2024-07-13 07:26:45.954",
            "timestamp": 1720855605,
            "reportActionTimestamp": 1720855605954,
            "automatic": false,
            "actionName": "ADDCOMMENT",
            "shouldShow": true,
            "reportActionID": "1283128664733577895",
            "previousReportActionID": "3794866778627686587",
            "lastModified": "2024-07-13 07:26:45.954",
            "childReportID": "6672766817607404",
            "childType": "task",
            "childReportName": "sdcsfds",
            "childOwnerAccountID": 17802616,
            "childManagerAccountID": 17802616,
            "whisperedToAccountIDs": []
        },
        "3794866778627686587": {
            "reportActionID": "3794866778627686587",
            "previousReportActionID": "0",
            "actionName": "CREATED",
            "created": "2024-07-13 07:26:22.292",
            "reportActionTimestamp": 1720855582292,
            "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/285f0f984f8c54c9ca2c386d0e16587f5d98e416_128.jpeg",
            "message": [
                {
                    "type": "TEXT",
                    "style": "strong",
                    "text": "You"
                },
                {
                    "type": "TEXT",
                    "style": "normal",
                    "text": " created this report"
                }
            ],
            "person": [
                {
                    "type": "TEXT",
                    "style": "strong",
                    "text": "Waseem Khan"
                }
            ],
            "automatic": false,
            "sequenceNumber": 0,
            "shouldShow": true,
            "lastModified": "2024-07-13 07:26:22.292"
        }
    }
}
```

**Comment by tsa321** [comment] 2024-07-15 13:44
@allgandalf  If we want to handle the similar errors in Front End based on [this message](https://expensify.slack.com/archives/C01GTK53T8Q/p1720533672162139?thread_ts=1720533146.376329&cid=C01GTK53T8Q), we could remove the optimistic created report actions (and optimistic IOU report action) after API request finished. Similar to my [proposal](https://github.com/Expensify/App/issues/43797#issuecomment-2173688182) in other issue.

**Comment by tsa321** [comment] 2024-07-16 02:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - UX covers message in admins chat if user create task from quick action after creating task from the `+` button in left of the composer

### What is the root cause of that problem?

The glitch of the UX is because there are more than one `created` type report action in the admins rooom.
When the user create task from quick action the `createTaskAndNavigate` params of `assigneeChatReport` is the admins chat report and not the correct chat report.
Then in these lines : 

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/actions/Task.ts#L202-L211

the `getTaskAssigneeChatOnyxData` will create optimistic `created` report action for the admins report, because of the incorrect `assigneeChatReport`.

The quick action will eventually call `createTaskAndNavigate` from:

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/pages/tasks/NewTaskDetailsPage.tsx#L78-L84

The task.assigneeChatReport is set in here:

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/actions/Task.ts#L789-L794

`...report` the report is the admins report and not the correct assignee report. 
Then will eventually create the optimistic `created` report action in the admins room like I explained above.

### What changes do you think we should make in order to solve the problem?

We could add `asssigneeChatReportID` in:

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/actions/Task.ts#L234-L242

in the onyx merge above (inside of createTaskAndNavigate), and adjust the setAssgineeValue and setAssigneeChatReport to use the `assigneeChatReportID`.

**Comment by tsa321** [comment] 2024-07-16 02:24
> not overdue, can you explain more @tsa321 , how would that solve the UX issue

@allgandalf I am sorry, I think it is different issue. I have made a proposal above.

**Comment by tsa321** [comment] 2024-07-19 14:08
@allgandalf In my alternative solution, the needed changes  is :

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/actions/Task.ts#L830

modify that line into:

`setAssigneeValue(accountLogin, accountID, reportID, undefined, false, skipConfirmation);` 

Result:

https://github.com/user-attachments/assets/21b3b58e-906f-4605-8efe-a08a21a966b6

> The first task and the text above it is duplicated and at the top of the screen, mind explaining why that happens? also if we add more task using the quick action they are added correctly at the bottom, it is only the first task and the room description which is duplicated and the UX looks messy, why is that?

This issue occurs because when the user clicks on the "create task" quick action button, the `chatReport` parameter in `setAssigneeValue` is incorrect. `chatReport` should represent a chat between the user and the assignee (a 1:1 chat), but it is incorrectly set to the admin report.

As a result, the function `getTaskAssigneeChatOnyxData`, located at 

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/actions/Task.ts#L203
returns incorrect data. It generates an additional `created` report action in the admin room, causing the UX glitch.

To investigate why this issue only occurs on the first click of the quick action, further details are available at 

https://github.com/Expensify/App/blob/9e811c2caae409111481b7030bac70d2966baa9f/src/libs/ReportUtils.ts#L6271-L6272

Because of  `isOptimistic` field of the admin report is not cleared after a successful API request to create a workspace, the `getTaskAssigneeChatOnyxData` will create a new `created` report action for the assgineeChatReport (which is admins report).

Inside `getTaskAssigneeChatOnyxData`, the `isOptimistic` field of `assigneeChatReport` (which is admins report) is set to false at:

https://github.com/Expensify/App/blob/9e811c2caae409111481b7030bac70d2966baa9f/src/libs/ReportUtils.ts#L6298

Therefore, only the first click on the quick action will trigger the incorrect `created` report action in the admins report.

<br />
Therefore, the solution to this issue could involve implementing my alternative approach. 

If we also need to fix the `isOptimistic` flag for the admin and announcement reports, we can set both to false after creating a new workspace.

**Comment by codewaseem** [comment] 2024-07-22 20:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Here we are trying to solve the bug in which the background image covers the message content in the Chat UI, making the text unreadable and unable to interact with the UI elements like checkboxes. 

### What is the root cause of that problem?
The root cause is that the background image of the bottom message (having a higher z-index value) overlaps with the previous message (lower z-index value). This is because the `<InvertedFlatList />` flips the axial symmetry of the elements and it also inverts the positioning context (top & bottom in this case). The `getReportWelcomeBackgroundImageStyle()` sets the bottom position value to 0 causing the image to be wrongly positioned. 

### What changes do you think we should make in order to solve the problem?
We can simply remove the { bottom: 0 } styles from the `getReportWelcomeBackgroundImageStyle()` to solve this problem. 

#### Before Fix
<img width="1291" alt="Screenshot 2024-07-23 at 01 33 12" src="https://github.com/user-attachments/assets/e847d6a0-d68a-47c5-bc59-6cc62ca10c6a">

#### After Fix - Background Image is moved to its correct position
<img width="1291" alt="Screenshot 2024-07-23 at 01 36 00" src="https://github.com/user-attachments/assets/29a80ce5-186c-46f6-a06c-648fd3d9c9c8">


### What alternative solutions did you explore? (Optional)
None

**Comment by codewaseem** [comment] 2024-07-22 20:22
Contributor details
Your Expensify account email: codewaseem@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017fece84a5f04f185

**Comment by codewaseem** [comment] 2024-07-22 20:41
https://github.com/Expensify/App/issues/44388#issuecomment-2243738886
Proposal Updated

**Comment by codewaseem** [comment] 2024-07-29 06:36
Hi @allgandalf, thanks for the welcome!

Yes, I only considered the solution from the styling perspective. 

I have one question, Does optimistic UI happen only when sending a new message, or does it happen every time the chat UI is rendered? Because I can see the bug even on the pages I created earlier.

I'm still exploring the codebase, so please don't mind the questions. :)

**Comment by Julesssss** [comment] 2024-08-06 08:42
> Thanks for sharing the test branch @tsa321 , will test the changes

Hi @allgandalf , just bumping you on this 🙂

**Comment by Julesssss** [comment] 2024-08-19 13:55
Hi, I was OOO. Checking now

**Comment by trjExpensify** [comment] 2024-09-03 23:29
Updated labels for you, Kev. Payments due.

**Comment by trjExpensify** [comment] 2024-09-05 00:44
Done!

**Comment by kevinksullivan** [comment] 2024-09-05 20:57
New job 

https://www.upwork.com/ab/applicants/1831797736299827437/job-details

Offer sent to @allgandalf . @tsa321 mind linking your upwork profile or applying directly? Thanks

**Comment by kevinksullivan** [comment] 2024-09-05 20:57
paid @allgandalf

**Comment by kevinksullivan** [comment] 2024-09-06 14:47
offer sent @tsa321 . Let me know when you accept!

**Comment by Julesssss** [comment] 2024-09-10 13:16
@kevinksullivan I assume payment is complete, but please verify before closing. Thanks

**Comment by kevinksullivan** [comment] 2024-09-12 12:25
yup all set here

**Closed by kevinksullivan** 2024-09-12 12:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
