### ISSUE TITLE
Web - Sign -The password is not visible in dark mode when you have autofill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13141] opened 2022-11-29 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. In log in page start typing your email address
3. Select any email

## Expected Result:
The password is visible in dark mode when you have autofill

## Actual Result:
The password is not visible in dark mode when you have autofill

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.33.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204605233-82fa6e4f-fa0f-41da-a962-efcbbe520f06.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-11-29 18:53
Taking a look at it right now!

**Comment by PauloGasparSv** [comment] 2022-11-29 19:04
I'm trying to reproduce here but the field gets highlighted for me instead making the password visible. Let me think.

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/6564265/204622396-86df5666-6de1-420b-ac8c-276abcb91478.png">

**Comment by PauloGasparSv** [comment] 2022-11-29 19:07
Ok, reproduced it here! Had to type something after it gets highlighted : )

**Comment by PauloGasparSv** [comment] 2022-11-29 19:10
Never mind, I accidentally messed with the CSS.

I can't reproduce this, will ask for help on slack!

**Comment by PauloGasparSv** [comment] 2022-11-29 19:26
After some time I can reproduce the error!!!! That highlight was removed and deployed but I think I had some cached JS in my browser that made it stick.

**Comment by PauloGasparSv** [comment] 2022-11-29 20:02
For some reason the css property `-webkit-transition-delay: 99999s` [introduced here](https://github.com/Expensify/App/pull/13119) is breaking the input.

I couldn't find any documentation about how the `transition-delay` or `-webkit-transition-delay` properties  work on input fields (or anything related to this problem).

https://user-images.githubusercontent.com/6564265/204635931-1567d277-c156-4ec2-a4d5-0ac73e30b715.mov

Trying to think of a way around this that doesn't involve reverting anything.
cc @marcaaron @luacmartins @MonilBhavsar @thesahindia can someone help me on this?

**Comment by luacmartins** [comment] 2022-11-29 21:11
Since these autofills are based on transitions, it makes sense that "disabling" them would break this. @marcaaron any thoughts on how to fix this?

**Comment by marcaaron** [comment] 2022-11-29 21:11
Ah hmm this sucks. Well, we can revert it but then the styles will look ugly again - so it's between ugly styles or this bug (which I think is sort of bad because it creates a confusing user experience and not a "style" issue). No sorry, I don't have any ideas let's bring it to Slack?

**Comment by marcaaron** [comment] 2022-11-29 21:15
>Since these autofills are based on transitions, it makes sense that "disabling" them would break this

Not sure if it makes sense to me. Can you explain it @luacmartins ? 

It does seem unique to password fields as no other fields have been reported as affected.

**Comment by PauloGasparSv** [comment] 2022-11-29 21:18
> It does seem unique to password fields as no other fields have been reported as affected.

I don't think it's unique to password fields : /  the **email field also has the same problem**. I thought it would be important so I show it after 22 seconds  on the [video I attached](https://github.com/Expensify/App/issues/13141#issuecomment-1331228595).

But I agree, these styles are important now that we have the dark mode so let's bring it to slack.

**Comment by PauloGasparSv** [comment] 2022-11-29 21:22
@marcaaron I feel you would explain this issue better than me on slack. **Do you want to bring this to over there** or can I do it?

Also, should we bring this to #engineering-chat or another room? I think some people that have strong opinions on the design may not see the message if we send it there.

**Comment by luacmartins** [comment] 2022-11-30 01:42
Gonna close this since we CP'ed the fix and it solved the issue

**Closed by luacmartins** 2022-11-30 01:42 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
