### ISSUE TITLE
[$500] Dev: Web - Click on back button close the RHP instead of opening Details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27598] opened 2023-09-16 19:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to #admins >Private notes
2. Reload the page
3. Click on back icon

## Expected Result:
It should navigates to Details page

## Actual Result:
Close the RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a6fcb300-b36a-4762-b2ce-a37f6b1f7038

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694788314587129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c7fb2a8b63fc0bf</li>
        <li>Upwork Job ID: 1703126966989799424</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-09-17 04:21
Dupe of #22041

**Comment by trjExpensify** [comment] 2023-09-18 08:26
Yup, agree with that. Closing!

**Closed by trjExpensify** 2023-09-18 08:26 UTC
Labels: External, Daily, Help Wanted
