### ISSUE TITLE
[$500] Composer - Insertion pointer jumps to the end when entering emoji in the middle of message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36199] opened 2024-02-09 02:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Add up to three emojis in composer
2. Bring Insertion pointer to the middle of the emojis
3. Add emoji from picker
## Expected Result:
Insertion pointer should be next to the newly added emoji

## Actual Result:
Insertion pointer is displayed at the end of the message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/9f93d3c3-6702-47c9-9672-8200602f91b0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123468df55b304b80</li>
        <li>Upwork Job ID: 1755776610237042688</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by yoyumiracle** [comment] 2024-02-09 04:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Insertion pointer jumps to the end when entering emoji in the middle of message

### What is the root cause of that problem?
Root cause of this problem maybe something affected to TextInput's pointer.

### What changes do you think we should make in order to solve the problem?
I think modify TextInput's onChange handle function will be solve problem.
Step1. Get current pointer of TextInput.
Step2. Compare if pointer is less or greater than TextInput's value length.
Step3. Set value of TextInput.
Step4. If Step2 result is "less" than set pointer current else set pointer to length of current value's length.

I can't test it in my eyes. I hope it would be help to fix problem

**Comment by mollfpr** [comment] 2024-02-09 04:57
> Root cause of this problem maybe something affected to TextInput's pointer.

@yoyumiracle Could explain more about this? What and where are the problems?

**Comment by yoyumiracle** [comment] 2024-02-09 05:27
### Could explain more about this? What and where are the problems?

updateMultilineInputRange(textInputRef.current, shouldAutoFocus);
I think composer component use this function. Function logic sometimes set comporser pointer to lastest of the input.
Unfortunately I can't test it. It's only depends on my code analysis. Please convince for that. Thanks.

**Comment by jcdiprose** [comment] 2024-02-09 13:34
I cannot replicate this on dev. Must be already fixed

**Comment by yoyumiracle** [comment] 2024-02-09 15:53
> I cannot replicate this on dev. Must be already fixed

Sorry for misunderstanding. Will you check this code correct or not? It's code of updateMultilineInputRange function.

    const updateMultilineInputRange: UpdateMultilineInputRange = (input, shouldAutoFocus = true) => {
        if (!input) {
            return;
        }
    
        if ('value' in input && input.value && input.setSelectionRange) {
            const length = input.value.length;
    
            // For mobile Safari, updating the selection prop on an unfocused input will cause it to automatically gain focus
            // and subsequent programmatic focus shifts (e.g., modal focus trap) to show the blue frame (:focus-visible style),
            // so we need to ensure that it is only updated after focus.
            const shouldSetSelection = !(Browser.isMobileSafari() && !shouldAutoFocus);
            if (shouldSetSelection) {
                input.setSelectionRange(length, length);
            }
            // eslint-disable-next-line no-param-reassign
            input.scrollTop = input.scrollHeight;
        }
    };

**Comment by thienlnam** [comment] 2024-02-09 18:18
Likely related to https://github.com/Expensify/App/pull/35837

**Comment by yoyumiracle** [comment] 2024-02-09 19:20
> We've reverted the offending PR #35837, so this is no longer a blocker

Does it mean that the issue is solved?

**Comment by thienlnam** [comment] 2024-02-09 20:13
It's no longer an issue impacting the App, but is being handled separately before we re-introduce the live markdown changes

**Comment by thienlnam** [comment] 2024-02-21 17:44
Not a current bug, but being worked on as part of https://github.com/Expensify/App/issues/36071

**Comment by thienlnam** [comment] 2024-02-26 17:45
https://github.com/Expensify/App/issues/36199#issuecomment-1957482943

**Comment by Skalakid** [comment] 2024-03-01 15:49
Hello, I created the fix for this issue inside live markdown library: https://github.com/Expensify/react-native-live-markdown/pull/208

**Comment by thienlnam** [comment] 2024-03-12 19:27
This should be fixed in react-live-markdown repo

**Closed by thienlnam** 2024-03-12 19:27 UTC
Labels: Engineering, Monthly, Internal, Bug
