### ISSUE TITLE
Dev: Web - Console log error on clicking 'Confirm task' button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22824] opened 2023-07-13 17:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Click on '+' icon
3. Click on 'Assign task' button
4. Enter title & click on 'Next' button
5. Click on 'Confirm task' button

## Expected Result:
There should be no console error

## Actual Result:
Console error is displayed [Provided collection doesn't have all its data belonging to the same parent.]

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.39-8
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e63280b3-ee90-4b3f-9154-59043f8b9f71

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689172121893929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2023-07-13 17:08
@yuwenmemon - asking for a friend here to reproduce, as I don't have access to a DEV environment!

**Comment by situchan** [comment] 2023-07-14 13:38
Dupe of https://github.com/Expensify/App/issues/22853

**Comment by sophiepintoraetz** [comment] 2023-07-14 15:47
Actually, @Natnael-Guchima - looks like you are not correct - thanks @Santhosh-Sellavel!
<img width="799" alt="image" src="https://github.com/Expensify/App/assets/42940078/9c10f473-6b2b-4ca1-bb1d-8a4fa6b9c396">

**Closed** 2023-07-14 15:49 UTC
Labels: Engineering, Daily, Bug

**Comment by Natnael-Guchima** [comment] 2023-07-14 16:09
You are right. I didn't see the slack report since there were no slack link attached too the GH issue. Sorry for raising a wrong flag
