### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000] Task - Time zone message for assignee disappears and does not update when changing assignee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24420] opened 2023-08-11 12:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Assign a task to User A and select User B as Share somewhere destination
3. Open the task detail page
4. Tap on Assignee and change assignee to User C

## Expected Result:
The time zone message for task assignee above composer will update with the new assignee

## Actual Result:
The time zone message for task assignee disappears and never updates to a new one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f4957eb4-6377-4fb6-b418-8feb86944e61

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b86a5af45ed94fa</li>
        <li>Upwork Job ID: 1690077183610470400</li>
        <li>Last Price Increase: 2023-08-11</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26202460</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-08-11 17:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Time zone message for assignee disappears and does not update when changing assignee.

### What is the root cause of that problem?
If create a task, app does not set the task report's `participantAccountIDs` field.

And `ReportUtils.canShowReportRecipientLocalTime` checks the report's `participantAccountIDs`.
So after create a task, does not show time zone for assignee.

After go to the parent report and navigate back, or refresh the task page, app sends `OpenReport` API to BE, and then BE returns the report that has `participantAccountIDs` field.
So in this time, app shows time zone for assignee.

If we change the task assignee, app does not change `participantAccountIDs` field.
But if we go to the parent report and navigate back, or refresh the task page, `OpenReport` API returns the report that has `participantAccountIDs` with two account ids.
So app does not show time zone for assignee.

### What changes do you think we should make in order to solve the problem?
For the task report, we should show the report `managerID`'s time zone instead of `participantAccountIDs`
```js
const reportRecipient = ReportUtils.isTaskReport(this.props.report) ? this.props.personalDetails[this.props.report.managerID] : this.props.personalDetails[participantsWithoutExpensifyAccountIDs[0]];
```

And we should modify `ReportUtils.canShowReportRecipientLocalTime` to return `true` for the task report.
```js
    if (ReportActionsUtils.isTaskReport(report)) {
        return true;
    }
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by joekaufmanexpensify** [comment] 2023-08-11 19:05
Yeah, I can reproduce this. Given we show the timezone of the task initial assignee, I think we'd want to update this if the assignee changes (perhaps unless you assign to yourself)? 

I also think we'd want to show the timezone of the assignee, as soon as they are assigned (rather than having to click out and back into the task). 

https://github.com/Expensify/App/assets/54866469/eb59eaf8-8687-4694-a9f0-9bfca7d39e1b

**Comment by Tony-MK** [comment] 2023-08-12 04:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Time zone message for the assignee disappears and does not update when changing the assignee. Also does not show the Time zone immediately message when the task is created as @joekaufmanexpensify 
stated in this comment https://github.com/Expensify/App/issues/24420#issuecomment-1675238852.


### What is the root cause of that problem?

When `reportRecipent` object is fetched, it uses first participant id in the `participantsWithoutExpensifyAccountIDs` array. Therefore, when the assignee of the task changes, the new assignee is pushed to the bottom of the array. Hence, the `reportRecipent` variable won't change to the current assignee. 

https://github.com/Expensify/App/blob/1e3f952574e2bbff9566c86c686a0589a5063a55/src/pages/home/report/ReportActionCompose.js#L956

https://github.com/Expensify/App/blob/1e3f952574e2bbff9566c86c686a0589a5063a55/src/libs/ReportUtils.js#L817

Also, the function `canShowReportRecipientLocalTime` returns false when the `participantsWithoutExpensifyAccountIDs` array has more than one participant.

https://github.com/Expensify/App/blob/1e3f952574e2bbff9566c86c686a0589a5063a55/src/libs/ReportUtils.js#L816

https://github.com/Expensify/App/blob/1e3f952574e2bbff9566c86c686a0589a5063a55/src/libs/ReportUtils.js#L820-L828

### What changes do you think we should make in order to solve the problem?


1. We need to use the `report.mangerID` when fetching the value for `reportRecipent` because the `report.managerID` variable is the id of the current assignee. Change the two lines to get the correct current assignee when the report is a task.

`const reportRecipient = this.props.personalDetails[ReportUtils.isTaskReport(this.props.report) ? this.props.report.managerID : participantsWithoutExpensifyAccountIDs[0]]`

`const reportRecipient = personalDetails[isTaskReport(report) ? report.managerID : participantsWithoutExpensifyAccountIDs[0]]`

2. The function `canShowReportRecipientLocalTime` needs to return true if is a task that is not assigned to the owner regardless of the number of participants the report has. 

https://github.com/Expensify/App/blob/1e3f952574e2bbff9566c86c686a0589a5063a55/src/libs/ReportUtils.js#L821C13-L821C13

Change the line above to follow the condition below.

`isTaskReport(report) ? report.managerID != report.ownerID : !hasMultipleParticipants`

**Comment by joekaufmanexpensify** [comment] 2023-08-15 20:31
@sobitneupane mind taking a look at proposals here when you have a chance?

**Comment by sobitneupane** [comment] 2023-08-16 17:12
Thanks for proposal everyone.

@tienifr's [proposal](https://github.com/Expensify/App/issues/24420#issuecomment-1675656171) looks good to me. 

🎀 👀 🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment] 2023-08-17 22:02
Pending review of proposal

**Comment by joekaufmanexpensify** [comment] 2023-08-18 17:59
@youssef-lr could you confirm whether we're good to proceed with this proposal when you have a sec? TY!

**Comment by youssef-lr** [comment] 2023-08-18 18:05
Proposal looks good to me as well.

**Comment by joekaufmanexpensify** [comment] 2023-08-18 18:08
TY!

**Comment by joekaufmanexpensify** [comment] 2023-09-04 17:53
Payment due in a week. @sobitneupane mind completing the BZ checklist this week?

**Comment by joekaufmanexpensify** [comment] 2023-09-12 13:53
Bumped in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-09-13 13:15
Still pending.

**Comment by sobitneupane** [comment] 2023-09-13 15:47
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

I don't think specific PR is responsible for this issue. We used existing `canShowReportRecipientLocalTime` function in Task Report as well which behave quite differently.

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not required.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-09-13 15:48
**Regression Test Proposal**

1. Assign a task to User A and select User B as Share somewhere destination
2. Open the task detail page
3. Tap on Assignee and change assignee to User C
4. Verify that the time zone message for task assignee above composer will update with the new assignee

Do we agree 👍 or 👎

**Comment by joekaufmanexpensify** [comment] 2023-09-13 20:43
BZ checklist is complete!

**Comment by joekaufmanexpensify** [comment] 2023-09-13 20:43
All set to issue payment.

**Comment by joekaufmanexpensify** [comment] 2023-09-13 20:46
This one does not qualify for the bonus. So we need to make the following payments: 

- @tienifr - $1,000 for PR (paid via Upwork). 
- @sobitneupane $1,000 for C+ (paid via NewDot).

**Comment by joekaufmanexpensify** [comment] 2023-09-13 20:47
@sobitneupane mind requesting $1,000 via NewDot and confirming here once complete? TY!

**Comment by joekaufmanexpensify** [comment] 2023-09-18 02:47
@tienifr $1,000 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-09-19 03:04
Bumped payment request in NewDot.

**Comment by joekaufmanexpensify** [comment] 2023-09-20 08:01
@sobitneupane could you please submit your payment request here so we can close this?

**Comment by sobitneupane** [comment] 2023-09-20 09:11
@joekaufmanexpensify I am waiting to receive payment for the older requests. Once it is done, I will request payment for this one. It should not take long.

**Comment by joekaufmanexpensify** [comment] 2023-09-21 07:53
Got it, sounds good! Moving to weekly then in the interim.

**Comment by joekaufmanexpensify** [comment] 2023-09-25 03:02
@sobitneupane any update on this?

**Comment by sobitneupane** [comment] 2023-09-25 05:03
Requested payment on newDot.

https://github.com/Expensify/App/issues/24420#issuecomment-1718295674

**Comment by joekaufmanexpensify** [comment] 2023-09-25 05:56
TY! Closing this for now. Payment summary message is [here](https://github.com/Expensify/App/issues/24420#issuecomment-1718295674).

**Closed by joekaufmanexpensify** 2023-09-25 05:56 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-28 00:58
$1,000 payment approved for @sobitneupane based on BZ summary.
