### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Task - Not here page appears briefly when closing task error message in public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31446] opened 2023-11-16 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out if logged in.
2. Navigate to a public room that has an unassigned task (https://staging.new.expensify.com/r/2376199970894587
).
3. Tap on the unassigned task.
4. Tap Mark as complete.
5. Close the error message.

## Expected Result:
Error message will be dismissed without any error message.

## Actual Result:
Not here page shows up briefly after closing the error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9f0d5cb4-bc5a-4340-83d1-2a6a354ee849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010013646d8714a6e0</li>
        <li>Upwork Job ID: 1725155572948697088</li>
        <li>Last Price Increase: 2023-11-16</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27722578</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-16 14:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Task - Not here page appears briefly when closing task error message in public room

### What is the root cause of that problem?
- When closing the error, we will delete the report
https://github.com/Expensify/App/blob/1deced458107c2f1bfd8c5e4e7c88678ecfc4249/src/libs/actions/ReportActions.ts#L29-L32
- That leads to the "not found page" appear for a while.
### What changes do you think we should make in order to solve the problem?
- We should only call ```deleteReport``` if the ```reportAction``` is task action

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by aaabccczzz05** [comment] 2023-11-16 14:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task show not found briefly when close the error
### What is the root cause of that problem?
We always delete the task report if we close the error from the task report, its purpose here is to delete the task report created with error.
https://github.com/Expensify/App/blob/1deced458107c2f1bfd8c5e4e7c88678ecfc4249/src/libs/actions/ReportActions.ts#L29-L32
### What changes do you think we should make in order to solve the problem?
We should add the condition whether the pendingAction is add or not

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-11-16 15:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Not here page appears for a brief moment when closing task error in a public room

### What is the root cause of that problem?

When closing a error, [clearReportActionErrors](https://github.com/Expensify/App/blob/1deced458107c2f1bfd8c5e4e7c88678ecfc4249/src/libs/actions/ReportActions.ts#L9) is called

Let's take a look into this function
https://github.com/Expensify/App/blob/1deced458107c2f1bfd8c5e4e7c88678ecfc4249/src/libs/actions/ReportActions.ts#L28-L32
As you can see above, we delete task report if `message.[0].taskReportID` exists. This was added to delete a task report failed in creation in the PR https://github.com/Expensify/App/pull/26848. It looks like the author assumed that `message.[0].taskReportID` exists only when creating a task, but this field exists in optimistic report action for completing/reopening/cancelling a task as well. Please refer the below code segment
https://github.com/Expensify/App/blob/1deced458107c2f1bfd8c5e4e7c88678ecfc4249/src/libs/ReportUtils.js#L2862-L2868

That is why the task report is deleted from onyx store

This is the root cause

### What changes do you think we should make in order to solve the problem?

In order to solve this issue, we need to modify the condition for deleting a task report
Update
https://github.com/Expensify/App/blob/e5e1965fb016af0963bbfc5210d1955b4ad910d6/src/libs/actions/ReportActions.ts#L28-L32
to
```
        // Delete the failed task report too
        if (ReportActionUtils.isCreatedTaskReportAction(reportAction)) {
            Report.deleteReport(reportAction.message?.[0]?.taskReportID ?? '');
        }
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/6eb59ecc-53dd-4c82-a09d-59425bea5c32


</details>

### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment] 2023-11-17 14:35
I think the main root case here - that we allow anonymous user to ability complete / re-open task interaction - which should not be - and BE correctly rejecting that try - but we should block it before on FE side (which will avoid any bugs which we see now or may see in future).  
Following all other patterns from public rooms - we ask user to sign in - to make any operation which required from signed user. Based on that - i think @dukenv0307 proposal makes sense to me https://github.com/Expensify/App/issues/31446#issuecomment-1814745412
🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment] 2023-11-17 14:46
@narefyev91 

I think calling `completeTask` may result in error due to some other reason like network status, etc. Also, unauthorized user may try to complete the task. In those cases, we need not to delete the task report itself. Obviously, deleting task report when clearing an error is a bug if that's not the task creation error. I'm sure we have to handle this case

cc @tylerkaraszewski @laurenreidexpensify

**Comment by narefyev91** [comment] 2023-11-17 14:52
> @narefyev91
> 
> I think calling `completeTask` may result in error due to some other reason like network status, etc. Also, unauthorized user may try to complete the task. In those cases, we need not to delete the task report itself. Obviously, deleting task report when clearing an error is a bug if that's not the task creation error. I'm sure we have to handle this case
> 
> cc @tylerkaraszewski @laurenreidexpensify

I think when user click on Complete Task - we should show right panel with Login flow - and ask user to login to make this action, rather than allow user to try to complete.
User should not come to this code below - when user do not have permissions to do it.
```
 const taskReportID = reportAction.message?.[0]?.taskReportID; 
 if (taskReportID) { 
     Report.deleteReport(taskReportID); 
 } 
```
In any case final decision for @tylerkaraszewski

**Comment by laurenreidexpensify** [comment] 2023-11-30 10:51
@narefyev91 pls complete checklist and advise on regression test thanks

**Closed** 2023-12-01 11:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
