### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] NetSuite - Sync error isn't displayed when connecting to NetSuite with invalid credentials

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46768] opened 2024-08-03 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4807616&group_by=cases:section_id&group_id=314239&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite with invalid credentials

## Expected Result:
Sync error should be displayed

## Actual Result:
Sync error isn't displayed when connecting to NetSuite with invalid credentials

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b3178725-098d-43d1-be81-08778f622ae3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ceab16370193c3b8</li>
        <li>Upwork Job ID: 1820591512049375650</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by sakluger** [comment] 2024-08-05 22:44
Tagging @yuwenmemon, @mananjadhav, @shubham1206agra since you all worked on the design doc for this feature.

**Comment by brunovjk** [comment] 2024-08-06 15:47
Indeed, we are not checking for when `verified: false`. I tested @nyomanjyotisa's [proposal](https://github.com/Expensify/App/issues/46768#issuecomment-2269073683), and it seems to fix the issue. However, I'm wondering about the error message—should we update it to something specific about the credential error? @internal, can you confirm if it's only a backend issue? Thank you.

🎀👀🎀 C+ reviewed

**Comment by tgolen** [comment] 2024-08-06 16:47
Wouldn't the error message get updated here? 

https://github.com/Expensify/App/blob/main/src/languages/en.ts#L3115

**Comment by brunovjk** [comment] 2024-08-06 16:56
Exactly. should we update/add it to something specific about the invalid credentials?

**Comment by mananjadhav** [comment] 2024-08-06 17:10
There was a discussion [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1720179157722519?thread_ts=1719271507.184899&cid=C06ML6X0W9L) but I cannot find what we concluded for the same.

**Comment by tgolen** [comment] 2024-08-06 18:05
woop, not sure what happened there. @sakluger can you take care of that, please?

**Comment by sakluger** [comment] 2024-08-07 17:32
Sure thing! Here are the Upwork offers:

@brunovjk - https://www.upwork.com/nx/wm/offer/103437519
@nyomanjyotisa - https://www.upwork.com/nx/wm/offer/103437511

**Comment by sakluger** [comment] 2024-08-24 01:53
I'm going to be OOO until Aug 30, so I'll assign another BZ member who can manually create those Upwork offers.

**Comment by brunovjk** [comment] 2024-08-26 11:38
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

**Regression Test Proposal**
  - Click on FAB - New workspace
  - Enable "Accounting" in the "More features" page
  - Navigate to "Accounting"
  - Connect to NetSuite with invalid credentials
  - Verify sync error displayed
  - Do we agree 👍 or 👎

**Comment by tgolen** [comment] 2024-08-30 15:49
@VictoriaExpensify Can you please complete the checklist here to close this one out?

**Comment by VictoriaExpensify** [comment] 2024-09-02 02:45
Created an issue to add the regression test to TestRail - https://github.com/Expensify/Expensify/issues/425122

**Comment by VictoriaExpensify** [comment] 2024-09-02 02:52
**Payment summary:**

Contributor: @nyomanjyotisa paid $250 via [Upwork Job](https://www.upwork.com/jobs/~01ceab16370193c3b8)
Contributor+: @brunovjk paid $250 via [Upwork Job](https://www.upwork.com/jobs/~01ceab16370193c3b8)

Thanks for your work on this issue!

**Closed by VictoriaExpensify** 2024-09-02 02:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
