### ISSUE TITLE
[$500] BA - "+" can be entered at beginning in value fields without being it marked as invalid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35093] opened 2024-01-24 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4234171
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and have created a Workspace
1. Go to Settings > Workspaces > Select Workspace > Bank account
2. Try to add BA manually and reach the Test transactions page
3. In the value fields, enter "+" at the beginning and any number

## Expected Result:
There should be an error message indicating invalid amount

## Actual Result:
There is no error message for the invalid amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bb03e785-6561-403d-8efe-e092762882a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01856ebed6b3302e15</li>
        <li>Upwork Job ID: 1750235916657090560</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-01-24 19:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
BA - "+" can be entered at beginning in value fields without being it marked as invalid
### What is the root cause of that problem?
Here the check `_.isNaN(Number(value))` returns valid number without + 
### What changes do you think we should make in order to solve the problem?
We should change the check of number . For example we can use regexp

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-01-24 20:06
@RohanSasne My all updates done before your proposal

**Comment by shahinyan11** [comment] 2024-01-24 20:13
@RohanSasne I did not like you reaction. are you see any update in my proposed solutions after your proposal ?

**Comment by getusha** [comment] 2024-01-26 19:07
Reviewing proposals, will provide an update today.

**Comment by getusha** [comment] 2024-01-26 19:28
@RohanSasne [proposal](https://github.com/Expensify/App/issues/35093#issuecomment-1908828954) looks good to me. works for other cases like adding `-` in front of the number. and looks the simplest for this issue.
Alternative solution may be, converting `+1` to `1` and returning it? I'll let the internal engineer weigh on this.

🎀 👀 🎀 C+ Reviewed!

**Comment by shahinyan11** [comment] 2024-01-26 19:30
@getusha Is not there any feedback about my proposal

**Comment by getusha** [comment] 2024-01-26 19:36
@shahinyan11 I picked @RohanSasne's proposal based on its simplicity to handle the case and i don't think replacing the condition with regex is a good idea it may cause future regressions. this is a straight forward and simple bug, and the selected proposal handles `+`, `-` altogether without having to use a regex.

**Comment by aldo-expensify** [comment] 2024-01-26 19:38
@lanitochka17 can you confirm if entering the  validation amount prefixed with a `+` causes the any problem when you try to submit? If the bank accounts gets validated just fine, I'll close this issue.

In my opinion, `+123` is just another (valid) way of writing `123`, preventing the user from doing that doesn't have any value.

**Comment by aldo-expensify** [comment] 2024-01-26 19:44
Tested and it doesn't cause the submission to fail:



https://github.com/Expensify/App/assets/87341702/ab8ca9b3-03bb-4055-8412-0a80d08cb406

Closing because I think this is not worth spending money and more time on.

**Comment by shahinyan11** [comment] 2024-01-26 19:45
> In my opinion, `+123` is just another (valid) way of writing `123`, preventing the user from doing that doesn't have any value.

@aldo-expensify We should fix this  because can be written `-123` . Is the `-123 `also valid ?

**Closed by aldo-expensify** 2024-01-26 19:44 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by aldo-expensify** [comment] 2024-01-26 19:49
> > In my opinion, `+123` is just another (valid) way of writing `123`, preventing the user from doing that doesn't have any value.
> 
> @aldo-expensify We should fix this because can be written `-123` . Is the `-123` also valid ?

Yes, it is valid, those transactions are supposed to add up to 0, so there will be some negative and some positives.

**Comment by aldo-expensify** [comment] 2024-01-29 17:52
> Just a small thought @aldo-expensify , considering the fact that later if at the backend we only consider positive values as parameters then we may have regression for negative values. (This is because for value verification we might want to avoid edge cases such as this issue :) )

I don't think we should do developments based on hypothetical cases like this, I'll wait for the problem to happen and then decide what to do.

> This is because as seen in video posted by you +115 goes as 115 in the backend

It goes from `+115` to `115` because it gets converted to a `number` by the frontend at some point.

> we instruct them to just enter the amount

I think the backend ignores the sign, so if the user enters -x o x is the same.
