### ISSUE TITLE
[$500] Send Button disabled when modify text after adding attachment 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10186] opened 2022-08-02 05:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create work space
2. Trying adding an attachment
3. Reject the permission
4. Enter anything in the text input

## Expected Result:
User should be able to send messages 

## Actual Result:
Send button is disabled. 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![WhatsApp Image 2022-07-28 at 3 44 07 PM](https://user-images.githubusercontent.com/43995119/182298998-c0cb30e9-4ee0-4d19-8a5b-352271700530.jpeg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Justicea83 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659023298980129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2022-08-04 20:45
Hey sorry for the delay! This looks like a good candidate for an external contributor to work on.

**Comment by kadiealexander** [comment] 2022-08-05 06:35
https://www.upwork.com/jobs/~01fa5fa238af39851b
https://www.upwork.com/ab/applicants/1555442172263116800/job-details

**Comment by Julesssss** [comment] 2022-08-22 08:49
Seeking proposals.

**Comment by dhairyasenjaliya** [comment] 2022-08-22 08:53
@Julesssss do we have any additional details regarding steps as of now seems like this is not reproducible have tried it on multiple devices with failure

**Comment by Santhosh-Sellavel** [comment] 2022-08-22 08:53
@Julesssss Were you able to reproduce this? I am also unable to reproduce!

**Comment by Julesssss** [comment] 2022-08-22 09:16
Ah sorry, I misread the above comments. I'm also not able to reproduce this. 

@jasperhuangg were you able to reproduce? If not I think we can remove external for now

**Comment by mvtglobally** [comment] 2022-08-23 04:38
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-08-30 15:23
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-09-06 03:18
Issue not reproducible during KI retests. (Third week). Are we ok to close?

**Comment by Julesssss** [comment] 2022-09-06 10:57
Yep, let's close it 👍

**Closed by Julesssss** 2022-09-06 10:57 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
