### ISSUE TITLE
[$500] Chat - PDF preview is opening in a smaller version

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34041] opened 2024-01-05 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a conversation
2. Upload a PDF file
3. Close the app
4. Open the app
5. Navigate to the chat with the PDF

## Expected Result:
PDF preview should load the correct size for the first time

## Actual Result:
PDF preview is opening in a smaller version and gets to the correct size later

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/596e9f1c-f279-4c33-b9a9-2e55c9428767

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e002ff9a3c1a28c</li>
        <li>Upwork Job ID: 1743328628679159808</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-05 19:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The PDF preview shows as small first and then resized to normal

### What is the root cause of that problem?
The PDF preview is rendered by ImageRenderer and the width and height are retrieved from the HTML attribute
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js#L48-L49

However, both width and height are 0, and if you notice the code above, we fall back to undefined. Because it's undefined, the ThumbnailImage gets the default width and height of 200.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/ThumbnailImage.tsx#L74

The image component then loads the image and updates it to the correct size.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/ThumbnailImage.tsx#L87-L95

### What changes do you think we should make in order to solve the problem?

Have a cache to cache the image size similar to the Lightbox.js component. Then we use this cached size as the fallback instead of undefined.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/Lightbox.js#L17
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/Lightbox.js#L70

We currently have the cache implemented for native only on the Image component here.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/Image/index.native.js#L12-L14
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/Image/index.native.js#L61

I think it's weird to have the cache implementation exposed by a component, so I think we can create a new global file to handle the cache

(the cache only lives on memory, so it will be cleared when the app closed)

**Comment by sourcecodedeveloper** [comment] 2024-01-07 11:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pdf attachment preview after upload is opened in smaller size and later resized to actual size.

### What is the root cause of that problem?
The root cause of the issue is that after the pdf is uploaded, in ImageRenderer.js, the imageWidth and imageHeight fallback to undefined because the html attributes 'data-expensify-width' and 'data-expensify-height' are set to 0.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js#L48

The ThumbnailImage prop sets default values for imageWidth and imageHeight to 200.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/ThumbnailImage.tsx#L74

The ImageWithSizeCalculation component eventually calls GetSize() from react native image api, to return the actual image size.
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/ThumbnailImage.tsx#L102

RNImage.GetSize()
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/Image/index.js#L39

Then after GetSize, the size is recalculated based on the actual size provided by GetSize()
https://github.com/Expensify/App/blob/f5a3c0202128a8e0e77607defbbdcb4f30f80ad3/src/components/ThumbnailImage.tsx#L89


### What changes do you think we should make in order to solve the problem?
I tried prefetching and caching approach using react native image api prefetch and querycache. Even after the image is prefetched, react native does not return size immediately using GetSize(). The approach I suggest to use is using persistentstorage (Onyx) for storing image data i.e. imgurl, width and height. Once stored in Onyxdb, the image data can be easily retreived using imgUrl and then passed into ImageRenderer.js and then to ThumbnailImage as imageWidth and imageHeight props. 
With the caching approach, getSize would be called each time the user switches reports and the activity indicator would be displayed each time but with the persistent storage the image data is retrieved immediately from Onyxdb and there is no delay in displaying the correct size.


### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment] 2024-01-08 13:18
@hoangzinh let me know your thoughts here. This seems like a tiny issue though, so if any of these proposals take a lot of time and effort to complete, I'd prefer we close instead of "fix", because the PDF still loads fine.

**Comment by sourcecodedeveloper** [comment] 2024-01-09 16:49
@hoangzinh the persistent storage approach I mentioned is simple and effective, some feedback would be much appreciated. Thanks

**Comment by sourcecodedeveloper** [comment] 2024-01-09 17:15
@twisterdotcom please do take few moments and review the video posted in [proposal](https://github.com/Expensify/App/issues/34041#issuecomment-1880034807) and comment on current behavior. The proposal is to not have the activity loader displayed each time the user switches reports.

**Comment by sourcecodedeveloper** [comment] 2024-01-10 11:01
@hoangzinh Thanks for feedback. I have added another poc video to demonstrate [proposal](https://github.com/Expensify/App/issues/34041#issuecomment-1880034807) from uploading attachment to preview loading.

**Comment by sourcecodedeveloper** [comment] 2024-01-11 14:11
@hoangzinh @twisterdotcom In the video poc I have covered the flow from user loading the chat first time and adding attachment to the user switching reports. As demonstrated, the issue does not occur the first time chat is loaded or after uploading attachment. In the video attached by tienifr, the attachment is preloaded and does not demonstrate the entire flow and the issue could reoccur the first time user load chat or after uploading attachment.

**Comment by sourcecodedeveloper** [comment] 2024-01-12 07:17
@hoangzinh I am curious how @tienifr proposal is unique from others.
@tienifr please kindly also share video of the entire flow from user uploading attachment to user switching reports so that becomes clear as how the proposal is unique from others.

**Comment by sourcecodedeveloper** [comment] 2024-01-12 09:32
>  I terminated the app completely and reopened the app again.
@tienifr the closing the app and opening the app part is clear but what is not clear is the actual uploading of the attachment and after the attachment is loaded whether the issue remains.
@hoangzinh The issue is also occurring on the web besides other platforms. I have also made the solution clear that is not to show the image if the size is not known but I have provided clear video demonstrating that no resizing takes place after attachment is loaded and the first time chat is loaded.

**Comment by twisterdotcom** [comment] 2024-01-12 11:24
TBH, all the solutions seem to do what is required from a product perspective as long as @tienifr's also works from upload, which I assume it does.

@hoangzinh please choose the solution you think makes the most technical sense and we can assign an internal engineer to verify as well.

**Comment by sourcecodedeveloper** [comment] 2024-01-12 12:29
@twisterdotcom @hoangzinh I also propose to split not all but some of the bounty should the review determine both solutions meet product perspective :smile: and I suggest not to leave things on assumptions because that is how regressions happen, uploading another video would take maybe 5 minutes.

**Comment by bernhardoj** [comment] 2024-01-12 14:26
I don't think it's over-engineered. We did the same approach for Lightbox.js which is a pretty simple approach
https://github.com/Expensify/App/blob/964548a2adb3ed9e2572ad33456759176a01b76c/src/components/Lightbox.js#L17
https://github.com/Expensify/App/blob/964548a2adb3ed9e2572ad33456759176a01b76c/src/components/Lightbox.js#L70-L74

**Comment by bernhardoj** [comment] 2024-01-12 14:37
Yes, that's correct

**Comment by sourcecodedeveloper** [comment] 2024-01-12 14:38
@hoangzinh The first load would not be an issue, i can provide another video if that would assist.

**Comment by sourcecodedeveloper** [comment] 2024-01-12 14:49
@hoangzinh Yes, I agree that the first load requirement was supposed to be discussed in proposal and I left that out because I did not want to give out too much before the proposal was awarded. To get the image to load on first load need to add useEffect in ReportActionItemFragment

**Comment by sourcecodedeveloper** [comment] 2024-01-12 15:00
@hoangzinh Please review revised [proposal](https://github.com/Expensify/App/issues/34041#issuecomment-1880034807), I have included part on how to get first load. Also the issue could probably get resolved on the backend if data-expensify-width and data-expensify-height were provided, depends how busy the back-end team is.

**Comment by sourcecodedeveloper** [comment] 2024-01-12 15:08
> Also I think caching width/height of images to Onyx seems over-engineered to me.

@hoangzinh The temp ids for invited members are also being stored in onyx when the user invites members to workspace, storing image meta data in onyx is related to that and would follow similar pattern.

**Comment by sourcecodedeveloper** [comment] 2024-01-12 17:28
@hoangzinh regarding the specifics of first load, I can share the implementation details after the proposal is awarded. I assure the proposal does handle first load as demonstrated in the poc. Thanks for understanding.

**Comment by marcochavezf** [comment] 2024-01-12 19:49
Thanks for the review, @hoangzinh; I'm leaning towards closing this issue as you mentioned [here](https://github.com/Expensify/App/issues/34041#issuecomment-1889338224). Currently, I'm focused on fixing wave issues for the backend. If it can be fixed purely on the frontend, it would be great; we can wait a bit longer in case there's a better proposal.

**Comment by marcochavezf** [comment] 2024-01-12 19:52
> @hoangzinh regarding the specifics of first load, I can share the implementation details after the proposal is awarded. I assure the proposal does handle first load as demonstrated in the poc. Thanks for understanding.

@sourcecodedeveloper given the comment above, feel free to provide more details in your current proposal maybe you can change @hoangzinh's mind :)

**Comment by sourcecodedeveloper** [comment] 2024-01-13 11:18
@marcochavezf Thanks

@hoangzinh I can try and elaborate in some more detail and perhaps get the proposal. 

I would add useEffect in ReportActionItemFragment. The useEffect will have dependency of [fragment.html]

https://github.com/Expensify/App/blob/753ce92ea9a1858dd2d576eeff692df527ea3ecb/src/pages/home/report/ReportActionItemFragment.js#L96

1) When the user uploads the attachment the first time, the fragment.html is set to ATTACHMENT_UPLOADING_MESSAGE_HTML and the message Uploading attachment... is displayed in the chat. I would add fragment.html as dependency to useEffect and listen for updates to fragment.html.

2) I would also add useState variable isAttachmentLoading and set the value to true while the attachment is uploaded.

3) The useEffect would trigger on value change of fragment.html. After the attachment is uploaded, the fragment.html contains the image preview source, in the useEffect I would check the value of fragment.html and obtain the imgUrl and then check if the imgUrl has already been processesed previously and stored in Onyx key store. If the imgUrl has previously been processed, I would set isAttachmentLoading to false and return from useEffect.

3) If the imgUrl has not been previously processed i.e the lookup in key store would return null, I would then proceed to call RNImage.GetSize(imgUrl) and in the success callback for GetSize store the image width and height in keystore and set isAttachmentLoading to false.

4) The useState variable isAttachmentLoading would be used for displaying the previous message Uploading attachment... through out the attachment upload + the call to RNImage.GetSize(if needed). Once the isAttachmentLoading is set to false, the image preview is ready to be displayed in first load.

**Comment by sourcecodedeveloper** [comment] 2024-01-13 11:19
@marcochavezf Thanks

@hoangzinh I can try and elaborate in some more detail and perhaps get the proposal. 

I would add useEffect in ReportActionItemFragment. The useEffect will have dependency of [fragment.html]

https://github.com/Expensify/App/blob/753ce92ea9a1858dd2d576eeff692df527ea3ecb/src/pages/home/report/ReportActionItemFragment.js#L96

1) When the user uploads the attachment the first time, the fragment.html is set to ATTACHMENT_UPLOADING_MESSAGE_HTML and the message Uploading attachment... is displayed in the chat. I would add fragment.html as dependency to useEffect and listen for updates to fragment.html.

2) I would also add useState variable isAttachmentLoading and set the value to true while the attachment is uploaded.

3) The useEffect would trigger on value change of fragment.html. After the attachment is uploaded, the fragment.html contains the image preview source, in the useEffect I would check the value of fragment.html and obtain the imgUrl and then check if the imgUrl has already been processesed previously and stored in Onyx key store. If the imgUrl has previously been processed, I would set isAttachmentLoading to false and return from useEffect.

3) If the imgUrl has not been previously processed i.e the lookup in key store would return null, I would then proceed to call RNImage.GetSize(imgUrl) and in the success callback for GetSize store the image width and height in keystore and set isAttachmentLoading to false.

4) The useState variable isAttachmentLoading would be used for displaying the previous message Uploading attachment... through out the attachment upload + the call to RNImage.GetSize(if needed). Once the isAttachmentLoading is set to false, the image preview is ready to be displayed in first load.

**Comment by sourcecodedeveloper** [comment] 2024-01-16 16:10
> when user sign out and sign in again, then go to any chat that has images. What would you show in the chat report when isAttachmentLoading is true?

@hoangzinh Interesting point. After the user signs out, the onyx storage is cleared and signing back in would mean the image size is no longer stored in onyx and needs to be reloaded.
While isAttachmentLoading is true, I would need to show either attachment loading placeholder text or some success activity indicator.

Option 1: 
The existing implementation when uploading attachment uses placeholder const when attachment is uploading,
ATTACHMENT_UPLOADING_MESSAGE_HTML: 'Uploading attachment...',

[poc_loader1.webm](https://github.com/Expensify/App/assets/141340971/f1abe278-7269-4b0b-bb0e-73d00cef6846)

Option 1 would be to add another placeholder const for reloading sizes i.e ATTACHMENT_LOADING_MESSAGE_HTML: 'Loading Attachment...' 

Option 2:
Instead of using placeholder message, the success activity loader can be used. Attached poc for activity loader,

[poc_loader2.webm](https://github.com/Expensify/App/assets/141340971/ca7c1413-b001-41e8-a430-ab39e2847222)

**Comment by sourcecodedeveloper** [comment] 2024-01-16 19:48
> @tienifr's https://github.com/Expensify/App/issues/34041#issuecomment-1879078487 provided a simple fix, but if we show a large image or network is slow, the image is disappear for a short period. I think it's worse than currently (temporary show in a smaller version then show in a correct version).

@hoangzinh I would not be showing large image and their proposal does not cover first load and also does not use any kind of cache or onyx, they would need to show activity loader even after file is uploaded and each time user switch report call getSize. Instead of showing image, I would be displaying either Option 1 or Option 2.

What I can suggest for the proposal, something to benefit both the FE & BE. The ImageRenderer already has 'data-expensify-width' and 'data-expensify-height' but the BE is not sending the correct values. In the ImageRenderer I can add check to only load image width and height from onyx if the 'data-expensify-width' and 'data-expensify-height' are undefined. Then depending on when and if the BE starts sending correct width/height, the priority would be given to the values from BE. 

And the other thing regarding BE, after sign out/signin, the BE would also need to fetch image sizes and send to FE by api call, the report on FE would need to show some form of activity loader from Option 1 or Option 2, while the image size is retrieved from BE. Also once the BE has returned the correct width/height, storing the values in onyx storage would be beneficial for immediate use when switching reports. Otherwise, the BE would have to return image width/height each time the user goes from one chat to another. So even if the BE returns correct width and height, storing the image width/height from the BE in onyx storage would be beneficial for displaying images when the user goes from one chat to another.

> I'm focused on fixing wave issues for the backend.

On the other hand, does not look like @marcochavezf would be available any time soon which means it would go to waste and issue would get closed.

**Comment by sourcecodedeveloper** [comment] 2024-01-18 09:52
@hoangzinh how about considering the proposal for if the BE implements correct width and height, then retrieving width and height from onyx would still provide faster loading when the user goes from one chat to another, otherwise the BE would have to fetch image with and height each time user switches reports.

**Comment by twisterdotcom** [comment] 2024-01-18 22:22
@marcochavezf intrigued for your thoughts here? I'm worried we might be wasting a lot of time on something trivial and not super noticeable for the end user.

I'm also not sure we care _that much_ about having the same behavior on first login vs every other time you can recover some onyx cache. The app has infinite sessions, so I kind of think if we have to load it once incorrectly for it to load correctly every other time (unless you sign out), that's an acceptable solution.

**Comment by twisterdotcom** [comment] 2024-01-18 23:31
Not overdue.

**Closed** 2024-01-19 01:38 UTC
Labels: External, Daily, Help Wanted, Bug
