### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Last message text are not shown when searching for the rooms

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41816] opened 2024-05-07 21:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708669400849159

## Action Performed:
1. Open app
2. Click on Find icon
## Expected Result:
Last comment should display for the rooms
## Actual Result:
Showing the workspace chat name as last comment
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2024-05-07 174932](https://github.com/Expensify/App/assets/38435837/8773e06e-9cf9-45e4-ab7f-6d682a73b5a2)

![IMG_6381](https://github.com/Expensify/App/assets/38435837/7a241b92-5319-4983-baa0-e0aae101060c)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5ae7362185c5a44</li>
        <li>Upwork Job ID: 1788509395347320833</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by nkdengineer** [comment] 2024-05-08 03:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Showing the workspace chat name as last comment

### What is the root cause of that problem?
In `getSearchOptions`, we pass `forcePolicyNamePreview` as `true` into `getOptions` function

https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/OptionsListUtils.ts#L1996

So the alternateText is forced to the `policyName` by this condition
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/OptionsListUtils.ts#L556
### What changes do you think we should make in order to solve the problem?
We should remove param so it can have the default value is `false` and then the last message text is shown in search page

https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/OptionsListUtils.ts#L1996

### What alternative solutions did you explore? (Optional)
NA

### Result

<img width="1512" alt="Screenshot 2024-05-08 at 10 52 10" src="https://github.com/Expensify/App/assets/161821005/3cc8e2fc-2757-40af-982e-6d36439f2ebd">

**Comment by laurenreidexpensify** [comment] 2024-05-08 11:23
@youssef-lr is this under vip-vsb?

**Comment by youssef-lr** [comment] 2024-05-08 21:24
@laurenreidexpensify Yes I think it fits there.

**Comment by rushatgabhane** [comment] 2024-05-13 05:54
@dragnoir's proposal LGTM
🎀 👀 🎀

**Comment by nkdengineer** [comment] 2024-05-13 08:14
@youssef-lr What is the expected here? Should we fix for all reports show the last message text in search page or only fix for chat room?

**Comment by laurenreidexpensify** [comment] 2024-05-16 09:25
@youssef-lr bump for response, pls unassign yourself once you've reviewed thanks!

**Comment by youssef-lr** [comment] 2024-05-16 12:53
Sorry I missed this. @nkdengineer this issue is about chat rooms only so I think we can limit it to those.

**Comment by nkdengineer** [comment] 2024-05-16 12:54
@youssef-lr Should the policy expense chat show the workspace name in search page?

**Comment by youssef-lr** [comment] 2024-05-16 12:59
#admins and #announce rooms should show the policy name I think so they can be distinguished, but other rooms should show the last message. For policy expense chats, do we not already show the last message?

**Comment by rushatgabhane** [comment] 2024-05-20 19:03
waiting on @youssef-lr's [approval](https://github.com/Expensify/App/issues/41816#issuecomment-2106708735)

**Comment by aldo-expensify** [comment] 2024-05-21 18:48
@youssef-lr should I un-assign myself and leave this to you?

**Comment by youssef-lr** [comment] 2024-05-21 20:41
Sounds good @aldo-expensify

**Comment by nkdengineer** [comment] 2024-05-22 02:46
@youssef-lr I think we're still discussing about the expected here https://github.com/Expensify/App/issues/41816#issuecomment-2115204690

**Comment by laurenreidexpensify** [comment] 2024-06-04 15:00
Merged, not yet on staging

**Comment by laurenreidexpensify** [comment] 2024-06-13 10:27
Payment Summary - 

- Contributor @dragnoir paid via Upwork $250 
- C+ @rushatgabhane requires payment through NewDot Manual Requests

@rushatgabhane pls confirm regression steps and checklist thanks

**Comment by laurenreidexpensify** [comment] 2024-06-14 09:00
@rushatgabhane pls confirm regression steps and checklist above so we can close thanks

**Comment by rushatgabhane** [comment] 2024-06-16 12:54
1. The PR that introduced the bug has been identified. Link to the PR: This is a new behavior. Not a bug.

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again


                1. Go to any room chat
                2. Send a comment
                3. Click on the search icon from LHN
                4. Verify that the last posted comment is displayed under the room name in search page

**Closed** 2024-06-17 08:46 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-23 15:56
@mallenexpensify can you please confirm the payment summary about with an amount for @rushatgabhane? I can't approve until I have that.

**Comment by mallenexpensify** [comment] 2024-06-24 23:44
@JmillsExpensify , updated [Lauren's payment breakdown above](https://github.com/Expensify/App/issues/41816#issuecomment-2165252224)
> - C+ @rushatgabhane owed $250 via NewDot.

**Comment by JmillsExpensify** [comment] 2024-06-25 03:20
$250 approved for @rushatgabhane
