### ISSUE TITLE
Hybrid Android - App is stuck at Book travel page after opening Trips from OD and then Try ND

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51121] opened 2024-10-19 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-0
**Reproducible in staging?:** Can't check
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49602
**Email or phone of affected tester (no customers):** applausetester+kh1410003@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch hybrid app.
2. Go to OD if the app is in ND.
3. Open menu.
4. Tap Trips.
5. Tap app back button.
6. Tap Try New Expensify.
7. Tap app back button.

## Expected Result:
User is able to return to New Expensify from OD after opening Book travel page from OD.

## Actual Result:
App is stuck at Book travel page after opening Trips from OD and then open Try New Expensify.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4445af7f-9f09-438c-9b83-609149820420

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-19 14:55
We think that this bug might be related to #vip-travel

**Comment by carlosmiceli** [comment] 2024-10-19 16:33
This is most likely the PR that caused it: https://github.com/Expensify/App/pull/49602

**Comment by Beamanator** [comment] 2024-10-21 13:18
FYI SWM is looking into this - https://expensify.slack.com/archives/C04878MDF34/p1729497719145869

**Comment by mateuuszzzzz** [comment] 2024-10-21 14:45
Hi, I have an update.

On Android the issue is caused by `lastVisitedPath` from which we construct initial navigation state.
It is quite surprising that it is not reproducible on iOS, because it should be platform-agnostic. 

I'm preparing PR with a fix. Also, I'm going to investigate why the behaviour is different on both platforms.

**Comment by yuwenmemon** [comment] 2024-10-22 00:39
Closing: https://expensify.slack.com/archives/C9YU7BX5M/p1729557218232369?thread_ts=1729554748.866629&cid=C9YU7BX5M

**Closed by yuwenmemon** 2024-10-22 00:39 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
