### ISSUE TITLE
[$250] Chat - RBR displayed on the wrong expense preview component for a few seconds

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51989] opened 2024-11-04 20:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51782
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2033@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Submit a manual expense
4. Submit a scan expense with a picture that will through an error
5. Wait for the scan to be finished and open the report conversation

## Expected Result:
RBR shown only on the failed scan expense

## Actual Result:
RBR shown on the manual expense at first for a few seconds

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9101993f-9986-48d4-9e24-992ee4a726eb

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854987328786203223</li>
        <li>Upwork Job ID: 1854987328786203223</li>
        <li>Last Price Increase: 2024-11-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by jacobkim9881** [comment] 2024-11-06 12:30
The cause of RBR is from data of BE API. The first transaction has this violation tag called `cashExpenseWithNoReceipt`:

```js

[info] [Report] Handled multipleEvents event sent by Pusher - 
...
{"transactionViolations_3345000142618413242":null,
"transactionViolations_8239222946581758013":[{"data":null,"name":"cashExpenseWithNoReceipt","type":"notice"}]}}],"eventType":"onyxApiUpdate"}],"lastUpdateID":2800591071,"previousUpdateID":2800591070}""

```

I think if there is no reason to send `cashExpenseWithNoReceipt` by opening the thread, then the violation should not be sent. The code may be in BE API.

**Comment by c3024** [comment] 2024-11-12 14:24
Looks like this should be an internal issue. I will check and update.

**Comment by c3024** [comment] 2024-11-17 12:44
> The cause of RBR is from data of BE API. The first transaction has this violation tag called `cashExpenseWithNoReceipt`:
> 
> ```js
> [info] [Report] Handled multipleEvents event sent by Pusher - 
> ...
> {"transactionViolations_3345000142618413242":null,
> "transactionViolations_8239222946581758013":[{"data":null,"name":"cashExpenseWithNoReceipt","type":"notice"}]}}],"eventType":"onyxApiUpdate"}],"lastUpdateID":2800591071,"previousUpdateID":2800591070}""
> ```
> 
> I think if there is no reason to send `cashExpenseWithNoReceipt` by opening the thread, then the violation should not be sent. The code may be in BE API.

@jacobkim9881 

Which request is returning the response with that transaction violation?

**Comment by jacobkim9881** [comment] 2024-11-17 13:42
It is an update from `GetMissingOnyxMessages` request which is the result from waiting for identifying scan. 
The order is like:
Submitted Scan expense -> Scanning -> An update from BE called `GetMissingOnyxMessages` request -> The transaction `transactionViolations` data has `cashExpenseWithNoReceipt` error -> Scanfinished

**Comment by c3024** [comment] 2024-11-21 10:14
@jacobkim9881 

Thanks for the explanation.

@MitchExpensify 

This needs a backend fix. So, this should be internal.

**Comment by MitchExpensify** [comment] 2024-11-26 02:13
I thought labeling internally would assign someone

**Comment by c3024** [comment] 2024-11-27 09:09
🎀 👀 🎀

**Comment by carlosmiceli** [comment] 2024-12-02 17:04
Yeah, finally having time to pick this up today, will report back! 🙏

**Comment by carlosmiceli** [comment] 2024-12-03 04:28
@jacobkim9881 @c3024 I'm not convinced that this is a BE issue. I may be wrong, but [this](https://github.com/Expensify/App/issues/51989#issuecomment-2459627084) seems like correct behavior (the first transaction has no violation and the second one does. Shouldn't a failed scan actually send a violation?

What I think it's happening is that the FE is applying the RBR to all grouped transactions, or maybe all the report transactions, despite only one having violations. Here's what I'm seeing in dev when the first transaction is created successfully and we throw the second with the scan:

1- First RequestMoney (no violations)
![Screenshot 2024-12-03 at 1 21 13 AM](https://github.com/user-attachments/assets/9036e548-6279-4959-8ab5-a0816701683d)

2- Second RequestMoney (failed)
![Screenshot 2024-12-03 at 1 22 22 AM](https://github.com/user-attachments/assets/cdd1d72a-e1a0-4e54-8f7d-db5f30b44dc8)

3- Both transactions have the RBR in the workspace (this is the actual issue, right @IuliiaHerets ?):
![Screenshot 2024-12-03 at 1 20 53 AM](https://github.com/user-attachments/assets/9424dd45-0ec4-4161-8d08-97f0db29e78f)

4- Opening the expense report (looks correct):
![Screenshot 2024-12-03 at 1 22 44 AM](https://github.com/user-attachments/assets/a7a5fa03-b36c-4ceb-b304-1026294b0ac5)

Looking at this, I don't see a BE problem, but I may be wrong. If you still believe it to be a BE issue, please elaborate further what type of response would fix this issue and how.

**Comment by carlosmiceli** [comment] 2024-12-03 04:31
Re-adding the external label because I'd be interested in seeing FE proposals in the meantime.

**Comment by carlosmiceli** [comment] 2024-12-05 16:30
Any updates here? @c3024 @jacobkim9881 

@MitchExpensify I noticed we haven't gotten proposals since re-adding the External label, why do you think that may be?

**Comment by jacobkim9881** [comment] 2024-12-05 20:03
@carlosmiceli 
> The first transaction has this violation tag called cashExpenseWithNoReceipt

I think there is a reason with `cashExpenseWithNoReceipt` tag on the first transaction. We could let manual transactions not have RBR for the tag from client app.

**Comment by carlosmiceli** [comment] 2024-12-06 14:54
@jacobkim9881 did you read this: https://github.com/Expensify/App/issues/51989#issuecomment-2513524492 ?

**Comment by jacobkim9881** [comment] 2024-12-07 00:31
@carlosmiceli We could let the manual transaction not have RBR for `cashExpenseWithNoReceipt` error but I think the transaction should not get the error from the response.

**Comment by carlosmiceli** [comment] 2024-12-09 17:33
@mallenexpensify We haven't gotten a response from @c3024 in over a week, how can we reassign this to another C+?

**Comment by c3024** [comment] 2024-12-09 18:18
@carlosmiceli 

The expected result in OP is 

>RBR shown on the manual expense at first for a few seconds

I understood this as the brief appearance of the RBR on the cash (with no receipt) expense when clicking on the preview (~1:14-1:15 in this video)

https://github.com/user-attachments/assets/6b6a2d3b-1dd8-4a24-85d4-0b1c031b5673

The `GetMissingOnyxMessages` request returns a transaction violation for the cashWithoutReceipt expense so the RBR shows up on this cashWithoutReceipt expense for a brief period (like a second or so). When we open a report, the `OpenReport` is called immediately which correctly returns the violations for transactions (that is no violation for the cashWithoutReceipt) transaction and the RBR on the cashWithoutReceipt disappears immediately.

Here is another video with going offline intermittently to show that more clearly. 
1. Before the scan response returns, there is no RBR on any transaction.
2. After the scan response comes, the backend response `GetMissingOnyxMessages` returns a violation for the cashWithoutReceipt transaction.
3. We open this report after going offline. Now, an RBR appears on the cashWithoutReceipt transaction because of this violation mentioned in step 2.
4. If we go online, the queued `OpenReport` request is made and its response returns no violations for the cashWithoutReceipt transactions and the RBR disappears.

https://github.com/user-attachments/assets/e4df228e-bbca-43e2-9fa2-c2ca7202054c

So, as far as I understand, there must be some issue with the response returned for `GetMissingOnyxMessages` and this needs a backend fix. I have not found any code on frontend that shows RBRs for all transactions in a report even when there are violations only for some transactions.

@IuliiaHerets , please confirm if this is the bug?

>I understood this as the brief appearance of the RBR on the cash (with no receipt) expense when clicking on the preview (~1:14-1:15 in this video)

@jacobkim9881 , this is what I understood from your proposal. Please correct me if I missed something.

@carlosmiceli , the `RequestMoney` responses are correct.

>3- Both transactions have the RBR in the workspace (this is the actual issue, right @IuliiaHerets ?):
The picture just below this text in your comment shows two transactions (or previews?) with RBRs. Are you seeing an RBR on one of them even when there are no violations in it?

**Comment by c3024** [comment] 2024-12-09 18:44
@carlosmiceli 

>If you still believe it to be a BE issue, please elaborate further what type of response would fix this issue and how.

There is no need for a `GetMissingOnyxMessages` request and response here.

The scan response (or OpenReport) response presently send a `previousUpdateID` larger than the lastUpdatedID on the client giving the client an indication that the data on the client is out of date. So, client makes the `GetMissingOnyxMessages` request and that returns a response with incorrect violations. (A similar issue of needless call of `GetMissingOnyxMessages` and the reason for that call is explained [here](https://github.com/Expensify/App/issues/49931#issuecomment-2422259161). It is a big wall of text but that explains when a client calls `GetMissingOnyxMessages`).

1. The ideal fix is to fix the scan response and OpenReport responses to not send a previousUpdateID larger than the lastUpdateID.
2. Another simpler fix is to not send a violation for the cashWithoutReceipt transaction in the `GetMissingOnyxMessages` response.

**Comment by mvtglobally** [comment] 2024-12-14 05:04
Issue not reproducible during KI retests. (First week)

**Comment by c3024** [comment] 2024-12-23 13:14
This can be closed. The bug is not reproducible anymore!

**Closed** 2024-12-23 15:25 UTC
Labels: External, Weekly, Internal, Help Wanted, Bug
