### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Offline deleted workspace allows to open reimburse page and also allow to open and save rate page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27173] opened 2023-09-11 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Switch off the internet
3. Open settings->workspaces->any workspace->reimbursements and copy the URL
4. Delete the workspace opened in step 3
5. Open settings->workspaces and observe that by default we are not allowed to open deleted workspace
6. Paste and send the URL in any chat
7. Click on the URL in the chat and observe that it opens the deleted workspace reimbursement page
8. Click on rate tab and change the value for rate and save, observe that app does not provide any error
## Expected Result:
App should not allow to open reimburse and rate page after workspace is deleted

## Actual Result:
App allows to open reimburse and rate page and also does not provide error on save after workspace is deleted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a7765cab-fc81-4531-867c-e27cfd6c6759

https://github.com/Expensify/App/assets/43996225/55346eae-a8b2-4daf-a79d-1be992b748ac

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693303155795799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120ee75107e7b68ee</li>
        <li>Upwork Job ID: 1701274596529786880</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26745200</li>
<li>DylanDylann | Contributor | 26745201</li>
<li>dhanashree-sawant | Reporter | 26745202</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-11 16:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Offline deleted workspace allows to open reimbure page and also allow to open and save rate page

### What is the root cause of that problem?
In here, we only display not found page if the policy is empty or the current user is not admin
https://github.com/Expensify/App/blob/00ad8cf0e8ff2012140a4445ff8573a629af8483/src/pages/workspace/WorkspacePageWithSections.js#L108
But when we delete workspace offline the policy still exist with pending Action is delete
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/00ad8cf0e8ff2012140a4445ff8573a629af8483/src/pages/workspace/WorkspacePageWithSections.js#L108

In here, we add `|| policy.pendingAction === 'delete'`

We also should do the same thing on all other workspace pages

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-09-11 20:01
Looks like there was a double assignment, I'm going to unassign myself and leave the first BZ team member.

**Comment by DylanDylann** [comment] 2023-09-13 18:14
@0xmiroslav 
[updated proposal](https://github.com/Expensify/App/issues/27173#issuecomment-1714247972) to cover all pages

**Comment by DylanDylann** [comment] 2023-09-19 16:25
@0xmiroslav This PR https://github.com/Expensify/App/pull/27743 is ready for review

**Comment by DylanDylann** [comment] 2023-09-22 06:31
We requested a review from Internal Enginneer 2 days ago but It seems @AndrewGable is busy. It causes the PR to last 3 days + 3 hours. Are we eligible for a bonus in this case?

**Comment by Christinadobrzyn** [comment] 2023-09-29 22:30
preparing for payment, any regression test here @0xmiroslav?

**Comment by Christinadobrzyn** [comment] 2023-10-03 18:26
Thanks, @0xmiroslav can you also let me know about a regression test for this one? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-10-04 15:58
Payouts due:

Issue Reporter: $50 @dhanashree-sawant (paid in upwork)
Contributor: $500 + $250 bonus @DylanDylann (paid in upwork)
Contributor+: $500 + 250 bonus @0xmiroslav (paid later?)

Eligible for 50% #urgency bonus? Y - https://github.com/Expensify/App/issues/27173#issuecomment-1741621375

Upwork job is [here](https://www.upwork.com/jobs/~0120ee75107e7b68ee).

**Comment by Christinadobrzyn** [comment] 2023-10-04 15:59
Okay, paid everyone in Upwork but @0xmiroslav - it sounds like you're tracking the jobs that need to be paid separately.

@0xmiroslav can you let me know about a regression test for this? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-10-10 22:25
nudge @0xmiroslav about a regression test for this. thanks!

**Comment by Christinadobrzyn** [comment] 2023-10-11 22:37
regress test created - https://github.com/Expensify/Expensify/issues/325468

Closing!

**Closed by Christinadobrzyn** 2023-10-11 22:37 UTC
Labels: External, Weekly, Awaiting Payment, Bug
