### ISSUE TITLE
Distance - Wrong error message is shown when creating an invalid distance request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31834] opened 2023-11-24 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Go offline.
3. Go to workspace chat > + > Request money.
4. Go to Distance.
5. Enter vague addresses - SF for Start and LA for Finish point.
6. Create the Distance expense.
7. Go online.

## Expected Result:
The error message that will be shown is "Unexpected error requesting money, please try again later"

## Actual Result:
The error message is "The receipt didn't upload. Download the file or dismiss this error and lose it" instead of the usual "Unexpected error requesting money, please try again later".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7d25a8ea-a9c6-4f86-9426-848f7477c7a3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-11-24 16:19
Looks like a regression of https://github.com/Expensify/App/pull/29790

**Comment by iwiznia** [comment] 2023-11-24 17:51
It indeed looks like a regression of that PR.. @Gonals can you take a look? Otherwise we can revert...
Going to wait till monday since most people are ooo today.

**Comment by luacmartins** [comment] 2023-11-24 19:25
TBH I think we should revert given the comments on the PR after it was merged. That being said, a clean revert is no longer possible

**Comment by iwiznia** [comment] 2023-11-24 19:36
Yeah, going to wait for monday so that Alberto can take a look. It's not like we want to deploy today...

**Comment by luacmartins** [comment] 2023-11-24 19:40
Haha I was trying to deploy or at least leave the checklist clear for monday morning deploy, but there are so many open blockers 😅

**Comment by iwiznia** [comment] 2023-11-24 19:41
>  I was trying to deploy
You crazy man, it's friday and most of the company is OOO and/or traveling 😄

**Comment by luacmartins** [comment] 2023-11-24 20:00
Anyways, I got the revert PR ready if we decide to go that way - https://github.com/Expensify/App/pull/31854

**Comment by situchan** [comment] 2023-11-24 20:11
@ishpaul777 no, it's local file download. Not from server. Just to help user not re-scan receipt in case upload failed for some reason.
Here's scenario:
- user scans receipt using device camera
- upload to server and forget the receipt
- after a while, failed to upload
- user has no way to upload receipt again

With this local download feature, user can download scanned receipt to device and re-upload importing from gallery.
So first time user scans from camera, 2nd time imports from device gallery.
Makes sense?

**Comment by iwiznia** [comment] 2023-11-24 20:13
For distance receipts, there's nothing to download, so that message does not make sense.

**Comment by situchan** [comment] 2023-11-24 20:13
yeah, I am talking about scan receipt, not distance receipt. So this is bug anyway

**Comment by luacmartins** [comment] 2023-11-24 20:40
I don't think the implementation of this error is correct. If there was an error uploading the receipt, that's a server side error and we should be sending an `errorField: receipt` Onyx update from the server and checking that instead. I don't think we should not optimistically set this on the client if a money request fails because it could have failed for other reasons other than a receipt upload.

**Comment by iwiznia** [comment] 2023-11-24 21:03
> In any case a request fails, we want the user to have option to download receipt if he added otherwise it will be lost no matter the reason request fails as far as i understand, so i think its fine to use failuredata here

Correct. If the user uploaded a file, we want to ensure the file is not lost and they can download it.

**Comment by shubham1206agra** [comment] 2023-11-26 03:16
@luacmartins For receipt money requests, shouldn't we allow the user to download the file irrespective of the error, as we will remove the request after clicking the close button?

I think the error message structure can be:

`Error message from the backend`
Due to the above error, the receipt didn't upload. You can just download the file or dismiss this error and lose it.

Something on the line of this.

**Comment by shubham1206agra** [comment] 2023-11-26 16:35
Another thing, backend doesn't send anything except error status code when I send corrupted file as receipt. I think backend can send error for onyx in this case.

**Comment by shubham1206agra** [comment] 2023-11-27 09:10
This is the issue https://github.com/Expensify/App/issues/28965. Here, we will replace the placeholder image to optimistic map component.

**Comment by shubham1206agra** [comment] 2023-11-27 12:32
> Okay, as i skimming through issue we will use a snapshot image of route as initial receipt unless request is successful,still the question is same why we show download file message when user haven't added one?

Nope we are not using an image there

**Comment by mountiny** [comment] 2023-11-27 13:30
Assigning @0xmiroslav as he was C+ on the PR and created a follow up fix

**Comment by mountiny** [comment] 2023-11-27 14:56
This is fixed in staging, given @0xmiroslav has been C+ on the offending PR which will have to be completed I think payments will be handled there and we can close this one
https://github.com/Expensify/App/assets/36083550/fee29b4d-e49d-480e-a2f4-7cc5a264b153

**Closed by mountiny** 2023-11-27 14:56 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
