### ISSUE TITLE
[$250]  Chat scrolls back to the last message on opening the keyboard reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12237] opened 2022-10-28 14:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Scroll the chat so that you can see the old messages
3. Tap on the input to open the keyboard

## Expected Result:
The chat shouldn't scroll back to the last message

## Actual Result:
The chat scroll back to the last message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666912513143069

https://user-images.githubusercontent.com/43996225/198657547-06a8fd9a-8104-4dd1-81eb-f675038d6144.mov

https://user-images.githubusercontent.com/43996225/198657606-751db190-1b43-4994-8b8c-e58292ec8a4a.mp4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment] 2022-10-31 17:33
Assigning an engineer to triage - can this be worked on by an external contributor?

**Comment by jasperhuangg** [comment] 2022-11-01 18:28
Looks like a good candidate for the `External` label.

**Comment by TwizzyIndy** [comment] 2022-11-03 09:53
# Proposal

We only have to remove `keyboardEvent` listener on `ReportActionsView`. I think that could be fine.

https://github.com/Expensify/App/blob/25c306015d7b08fec915e6005cde7c928bdc847e/src/pages/home/report/ReportActionsView.js#L104-L114

**Comment by michaelhaxhiu** [comment] 2022-11-03 23:29
Heya @miljakljajic just dropping a note as a reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out :)

Can we export this one to Upwork since it's external? That'll help increase public visibility on the job.

Also @rushatgabhane are you able to review the proposal today or tomorrow?

**Comment by TwizzyIndy** [comment] 2022-11-04 08:16
Thanks for reviewing bro @rushatgabhane. I want to update my proposal.
# Proposal

We don't really have to remove the `keyboardEvent` here. We should check whether the current flatlist is at the bottom or not. We shouldn't scroll to the bottom if it is at the bottom. There is `currentScrollOffset` in `ReportActionView` which reflects the current scroll position. So we can check it like this. This looks also fine with [#3545](https://github.com/Expensify/App/issues/3545)

```diff
        this.keyboardEvent = Keyboard.addListener('keyboardDidShow', () => {
+            if (!ReportActionComposeFocusManager.isFocused() || this.currentScrollOffset !== 0) {
                return;
            }
            ReportScrollManager.scrollToBottom();
        });
```


https://user-images.githubusercontent.com/6712795/199924828-493fa88f-774e-4c7e-a0b7-9df2775297b3.mp4


https://user-images.githubusercontent.com/6712795/199925183-369b4cef-b32f-40f2-a398-77b630d5d53e.mov

**Comment by miljakljajic** [comment] 2022-11-04 11:11
[Job posted to Upwork.](https://www.upwork.com/ab/applicants/1588489145805021184/job-details)

**Comment by jasperhuangg** [comment] 2022-11-04 18:18
@TwizzyIndy I like your proposal and am inclined to accept it, but can you modify it a bit to include an explanation of how the logic in this condition would fix the problem? Ping me when you do. Thanks!

```
if (!ReportActionComposeFocusManager.isFocused() || this.currentScrollOffset !== 0)
```

**Comment by TwizzyIndy** [comment] 2022-11-06 14:17
Thank you. @jasperhuangg. I would like to add some explanation like this below.

```javascript
        this.keyboardEvent = Keyboard.addListener('keyboardDidShow', () => {
            // If the keyboard shows up and then
            // not focused on the report action composer or the current scroll position is not at the bottom
            // we won't scroll to the bottom here.
            if (!ReportActionComposeFocusManager.isFocused() || this.currentScrollOffset !== 0) {
                return;
            }
            ReportScrollManager.scrollToBottom();
        });
```

**Comment by miljakljajic** [comment] 2022-11-07 14:51
what do you think @rushatgabhane @jasperhuangg - are you happy with the suggestion @TwizzyIndy has provided above?

**Comment by TwizzyIndy** [comment] 2022-11-07 17:34
I'm sorry too but I don't even know how to explain it now. 😅

**Comment by jasperhuangg** [comment] 2022-11-07 21:38
@TwizzyIndy thank you for your reply!

I'm not looking for a comment explaining **_what_** is happening in the code, I'm looking for an explanation of **_why_** we're adding this code in the first place. 

Why does adding `this.currentScrollOffset !== 0` solve this issue? It might help to first clearly define for yourself what `this.currentScrollOffset` is in relation to. 

It appears we set it to `-nativeEvent.contentOffset.y` [here](https://github.com/Expensify/App/blob/a656daeeca0a6c88f2f36349178fc8cc79373ae4/src/pages/home/report/ReportActionsView.js#L317-L318), and that appears to be the distance from the  bottom of the ScrollView (which is the "start" because it's inverted).

I honestly don't really see why it works either. If you're unable to explain why then I'm afraid we'll be unable to accept your proposal.

**Comment by TwizzyIndy** [comment] 2022-11-08 04:10
Thank you.I will explain it as much as I can. 

Firstly, The issuer doesn't want to scroll back to the last message when he opens up the keyboard. So what I do first was, search for the event or callback when the keyboard open up. 

Then I found the `keyboardDidShow` listener. My first proposal was to delete that callback implementation to solve the problem. But it will be some regression issue. 

So I take a look at Issue [3545](https://github.com/Expensify/App/issues/3545) and figured out how he implemented composer focusing. His code was aimed to avoid scrolling down to the bottom when the ReportActionComposer is not focused. I've noticed that might be very similar to this issue.

So I knew that I only have to check the scroll position which is at the bottom or not. If not at the bottom, we don't need to scroll down. 

And found that giving `Zero` means setting the flatlist to the bottom by looking at the constructor method here.

https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/pages/home/report/ReportActionsView.js#L64-L80

When the scroll is not at the bottom, `currentScrollOffset` will be minus or negative values.  Because we update the value every time by the `trackScroll` event here.

https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/pages/home/report/ReportActionsView.js#L321-L329

And this callback made me confident about this proposal. Someone checked the `currentScrollOffet` here to read the newest action here.

https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/pages/home/report/ReportActionsView.js#L125-L138


When the scroll position is not at the bottom, the `currentScrollOffet` will be some negative values. So, I checked it in the callback to make sure that the flatlist was not at the bottom. If it got negative values, exit from the callback. That means it won't scroll down to the bottom.

**Comment by jasperhuangg** [comment] 2022-11-08 16:21
@TwizzyIndy thank you for the explanation, I'm happy with it. Assigning you, feel free to request me on your PR

**Comment by miljakljajic** [comment] 2022-11-09 17:13
Thank you, @TwizzyIndy. I've gone ahead and hirred you for this job in Upwork. Looking forward to seeing the PR.

**Comment by jasperhuangg** [comment] 2022-11-10 00:46
I'll take this one over, since I incorrectly accepted @TwizzyIndy proposal, sorry. The logic for this one is actually more complex than I had originally anticipated so I'll try to tackle this one myself.

**Comment by miljakljajic** [comment] 2022-11-14 11:57
Ah, no problem Jasper. I ended the contract - looking forward to seeing your solution.

**Comment by jasperhuangg** [comment] 2022-11-15 17:23
I have a draft PR up that tries to use [React Native's `onViewableItemsChanged` prop](https://reactnative.dev/docs/flatlist#onviewableitemschanged). You can read more about that [here](https://suelan.github.io/2020/01/21/onViewableItemsChanged/). It's a callback provided by `FlatList` that gets invoked whenever some scrolling causes the viewable items to change. It provides you with the current list of viewable items.

The only thing is it seems our implementation of `FlatList` has made it so `onViewableItemsChanged` doesn't entirely just work out of the box. Sometimes, it'll say there are only 2 visible items when there are clearly way more.

**Comment by jasperhuangg** [comment] 2022-11-15 19:01
@TwizzyIndy if you'd still like to look into my comment [here](https://github.com/Expensify/App/issues/12237#issuecomment-1315639408) and come up with another solution with this new context I'd still be happy to accept a proposal!

**Comment by Puneet-here** [comment] 2022-11-18 16:21
@jasperhuangg, I think we should fix this because it's annoying. There's a real life case for example I sometimes scroll to the past messages while writing a response for them.

> I think it's actually common behavior in most chat apps to scroll to the bottom of the chat when you open the keyboard.

I tried Slack, Whatsapp and instagram I didn't see this bug there so I believe it's the opposite

**Comment by jasperhuangg** [comment] 2022-11-18 16:24
@Puneet-here so what should we want the expected behavior to be? It's not entirely clear from the issue. Should we just disable scrolling to the bottom?

**Comment by Puneet-here** [comment] 2022-11-18 16:30
Yes, that's what other app are doing. I think we should do the same. Opening a keyboard shouldn't scroll the chat back to the latest message.

**Comment by jasperhuangg** [comment] 2022-11-18 16:32
I use Wechat, to talk to my family and friends 😆 and they scroll to the bottom, but just tried it the other ones you described and you're right, they don't scroll down.

**Comment by miljakljajic** [comment] 2022-11-28 12:42
Seems like the PR has merged, shall I close?

**Comment by miljakljajic** [comment] 2022-11-28 13:19
Ah my apologies, Puneet! I forgot that you reported it. I've hired you in Upwork for the job.

**Comment by Puneet-here** [comment] 2022-11-28 13:49
Thanks! I have accepted the offer.

**Comment by marcaaron** [comment] 2022-11-30 20:29
@jasperhuangg, I'm not sure if I agree with the outcome here. Messages on iOS always scrolls you to the bottom when you pop open the input. I prefer that behavior because if you are composing a message you'll want to see the latest message for context.

**Comment by JmillsExpensify** [comment] 2022-11-30 22:01
I'm with @marcaaron. I'm not sure if I agree with this bug report. Like clearly there isn't a right way here, it's just a preference. Some apps do it one way and other apps do it another way. As a result, this issue is wading into product design rather than bug fixing. I personally think we should close it until we have a larger conversation about which design is right.

**Comment by jasperhuangg** [comment] 2022-12-02 20:54
agree @JmillsExpensify thanks for the clarify here, definitely felt out of my depth with product design stuff. I also talked to a few different people about this issue and it seems like everyone has a different preference.

@marcaaron Did not realize that that was the behavior for Messages on iOS, thanks for pointing that out.

>  I prefer that behavior because if you are composing a message you'll want to see the latest message for context.

At least when I'm scrolled up in a chat, I'm most likely replying to the message I'm scrolled up to, not the latest one that I can't see on my screen. If you want another mechanism to scroll down to the bottom, perhaps we could add a button with an arrow on it that scrolls us down?


Regardless, I'll apply the `Planning` label to this and start up a chat in #expensify-open-source.

**Comment by marcaaron** [comment] 2022-12-02 20:58
>I'm most likely replying to the message I'm scrolled up to

Aren't you always kind of replying to the entire chat / last message and not some historical message that you are scrolled up to? Once we add threads then you can reply to a specific message.

**Comment by jasperhuangg** [comment] 2022-12-02 22:20
Closing as per conclusion from discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670014848299729)

**Comment by Puneet-here** [comment] 2022-12-02 22:35
@jasperhuangg, this still needs to be settled up. Can we keep this open?

**Comment by Puneet-here** [comment] 2022-12-05 11:58
@jasperhuangg bump

**Comment by JmillsExpensify** [comment] 2022-12-08 03:36
@Puneet-here Invited you via Upwork for reporting. Job is also here: https://www.upwork.com/jobs/~01aa7c375e34f4cbd5. Can you apply and we'll get this handled ponto?

**Comment by jasperhuangg** [comment] 2022-12-08 03:37
apologies @Puneet-here totally didn't realize! Yes, please apply on Upwork as Jason mentioned, thanks again for the bump

**Comment by JmillsExpensify** [comment] 2022-12-08 23:24
@Puneet-here Still waiting for you to accept in Upwork.

**Comment by Puneet-here** [comment] 2022-12-09 06:08
>@Puneet-here Still waiting for you to accept in Upwork.

Applied, thanks!

**Comment by jasperhuangg** [comment] 2022-12-12 06:38
Not overdue, just waiting for @Puneet-here to get paid out and we can close this out

cc @JmillsExpensify looks like he's all set up to get paid!

**Comment by JmillsExpensify** [comment] 2022-12-12 13:04
Offer sent to @Puneet-here Waiting for him to accept and then someone can pay him out. @miljakljajic or @jasperhuangg do either of you mind doing that today/tomorrow? I'm OOO this week.

**Comment by Puneet-here** [comment] 2022-12-12 13:31
Accepted

**Closed** 2022-12-12 16:21 UTC
Labels: Engineering, Daily, Planning, Bug
