### ISSUE TITLE
[HOLD for payment 2024-08-07] [$500] [Expensify Help] Add cache busting to HelpDot files

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#28209] opened 2023-09-26 02:24 UTC
We're loading the [CSS files](https://github.com/Expensify/App/blob/271059bff840e3da1fdea2de6c633ad5a3fdcf64/docs/_layouts/default.html#L9-L10) in the help site without a cache-busting technique, which causes to not load the recent CSS file:

![image (10)](https://github.com/Expensify/App/assets/6829422/e2a5e07b-002c-4354-a68e-382c1ef78b54)
![image (9)](https://github.com/Expensify/App/assets/6829422/259dee68-5f1a-423a-baf3-988a6ba1b0f3)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dffa1ca53efd8c82</li>
        <li>Upwork Job ID: 1744435293782720512</li>
        <li>Last Price Increase: 2024-07-13</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28089289</li>
<li>wildan-m | Contributor | 103153018</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by roryabraham** [comment] 2023-10-05 03:28
In [this thread](https://expensify.slack.com/archives/C094TGUTZ/p1696476120053659?thread_ts=1696058736.845509&cid=C094TGUTZ) we are discussing moving from GitHub Pages to Cloudflare Pages, which would provide a mechanism to fix this correctly by cache-busting for all files with something like [this](https://github.com/Expensify/App/blob/7d6f91fbe39574cef11cbdfd5ffacbcebe5fa3e5/.github/workflows/platformDeploy.yml#L322-L326)

**Comment by marcochavezf** [comment] 2023-10-05 16:08
Not overdue, update posted above

**Comment by marcochavezf** [comment] 2023-10-25 17:41
Hi @rushatgabhane @roryabraham, now that we have the help site running on Cloudflare pages, do you know if we still need to set up the cache-busting mechanism there?

**Comment by roryabraham** [comment] 2023-11-04 01:38
Yes, created a WIP PR: https://github.com/Expensify/App/pull/30877

Just need to know the Cloudflare zone for HelpDot

**Comment by roryabraham** [comment] 2023-11-13 21:38
Discussing in slack: https://expensify.slack.com/archives/C07J32337/p1699910022772639

**Comment by roryabraham** [comment] 2023-12-07 05:01
[This](https://gist.github.com/daneden/7027258) looks like potentially a good example implementation

**Comment by roryabraham** [comment] 2023-12-07 05:26
It would be pretty easy to follow that example and then cache just assets by adding liquid tags to the default template like so:

```liquid
<link rel="stylesheet" href="/assets/css/style-{% bust_cache %}.css">
```

However, that doesn't address any caching of the generated `.html` files themselves. 🤔

**Comment by roryabraham** [comment] 2023-12-13 17:44
I haven't been treating this as high priority, but there was a kind of bad bug that happened just today: https://expensify.slack.com/archives/C03TQ48KC/p1702485429643679 cc @stitesExpensify

**Comment by stitesExpensify** [comment] 2023-12-13 18:40
Personally I think it's worth merging your original approach now, and then the local cache issue can keep being worked on here

**Comment by roryabraham** [comment] 2023-12-13 20:26
Sure, put that PR in for review

**Comment by roryabraham** [comment] 2024-01-08 19:05
Removing reviewing label. Maybe we can make this external at this point? I said some of this above, but I would love to hear proposals that build off of something like [this](https://gist.github.com/daneden/7027258) to accomplish caching that:

- Works automatically for any file on the site
- Uses a hash of the file, not a timestamp, to control the caching such that the cache is busted only when the file actually changes.

**Comment by roryabraham** [comment] 2024-01-08 19:11
Asked an accounting-related question [here](https://expensify.slack.com/archives/C02QSAC6BJ8/p1704740987051029)

**Comment by roryabraham** [comment] 2024-01-08 19:12
Bumping this to weekly at my discretion because I know it's not particularly urgent

**Comment by rushatgabhane** [comment] 2024-01-08 19:16
@roryabraham could you please assign it to me, i can take this as part of helpdot migration project

**Comment by roryabraham** [comment] 2024-01-08 19:16
Discussed in slack and @rushatgabhane is going to take a pass at this in association with the HelpDot migration round 2 project: https://expensify.slack.com/archives/C02QSAC6BJ8/p1704741308222349?thread_ts=1704740987.051029&cid=C02QSAC6BJ8

**Comment by roryabraham** [comment] 2024-01-08 19:17
So @MitchExpensify just TBC we didn't end up using C+ services for this issue at this point in time

**Comment by MitchExpensify** [comment] 2024-01-08 19:26
Auto-offer to @getusha withdrawn:

<img width="1294" alt="image" src="https://github.com/Expensify/App/assets/36425901/6b79948d-404d-434e-8397-b431ffe9f914">

**Comment by rushatgabhane** [comment] 2024-01-17 04:19
No updates yet. 

Explored [jekyll-asset-post-processor](https://github.com/harrego/jekyll-asset-post-processor). It focuses on cache busting CSS, JS, images etc. It achives it by suffixing files with a hash made from contents and file name.

**Comment by MitchExpensify** [comment] 2024-02-11 20:22
Are we still looking to do this @rushatgabhane ?

**Comment by rushatgabhane** [comment] 2024-02-16 02:29
Yes, just not a priority

**Comment by rushatgabhane** [comment] 2024-03-05 22:09
same as above

**Comment by rushatgabhane** [comment] 2024-04-04 03:32
will do it this week

**Comment by roryabraham** [comment] 2024-07-12 20:31
@rushatgabhane is going to transition to a C+ role rather than a contributor role for this. Going to open it up to the community for proposals.

**Comment by roryabraham** [comment] 2024-07-12 20:33
Awaiting proposals

**Comment by wildan-m** [comment] 2024-07-13 03:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add cache busting to HelpDot files

### What is the root cause of that problem?

New feature

### What changes do you think we should make in order to solve the problem?

Add a Unix timestamp to your asset URLs. This will render out the current timestamp every time you make a change to the code.

_layouts/default.html
```html
    <link rel="stylesheet" href="/assets/css/styles.css?v={{ site.time | date: '%s%N' }}">
```

This can also be implemented to script/linked image if required.

The format '%s%N' is used to generate a Unix timestamp with nanosecond precision. Let’s break it down:

%s: Represents the seconds since the Unix epoch (January 1, 1970). It gives you a whole number representing the current time.
%N: Represents the nanoseconds part of the current time. It provides additional precision beyond seconds.
By combining these two, you get a unique timestamp that updates every second (and even more frequently with nanoseconds). 

### Result
<img width="821" alt="image" src="https://github.com/user-attachments/assets/82bde31f-2878-4d59-aade-9b62c1d3a9c8">


### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment] 2024-07-13 03:24
@wildan-m could you please have a look at this comment and modify your proposal accordingly - https://github.com/Expensify/App/issues/28209#issuecomment-1844407343

**Comment by wildan-m** [comment] 2024-07-13 03:48
@rushatgabhane has not found the answer yet. It may be possible to achieve with jekyll-assets, but since that is not actively maintained, there are build errors during my attempt. I have an alternative solution using `${{github.run_id}}`. This version will not update the cache if we run the same deployment multiple times.

**Comment by rushatgabhane** [comment] 2024-07-13 03:50
@wildan-m the goal is to use the contents of a file to generate a hash. And use that hash for caching

**Comment by wildan-m** [comment] 2024-07-13 16:57
@rushatgabhane @roryabraham since we are using the github-pages gem, we are unable to create custom plugins like [this one](https://github.com/MayOneUS/mayday-2.0-frontend/blob/4a868f92146abb9a2dee24d52503018e804f3ff1/_plugins/cache_bust_filters.rb). There are [several restrictions](https://github.com/github/pages-gem/blob/bd1018072aab370ddf63aa9c3938867e2133ac80/lib/github-pages/configuration.rb#L45-L70) imposed by github pages. It might be advisable to reconsider the expected solution.

**Comment by rushatgabhane** [comment] 2024-07-13 17:08
hey @wildan-m thanks for looking into this. we aren't using github pages. we're using cloudflare pages so we shouldn't have that problem?

**Comment by wildan-m** [comment] 2024-07-15 03:45
@rushatgabhane Proposal [updated](https://github.com/Expensify/App/issues/28209#issuecomment-2226740079).

Add Alternative 2 solution. Post process build file with appending hash version of the asset

**Comment by wildan-m** [comment] 2024-07-15 07:05
Proposal [updated](https://github.com/Expensify/App/issues/28209#issuecomment-2226740079).

Add alternative 3 solution. Use cache_bust filter (Semi automatic)

**Comment by rushatgabhane** [comment] 2024-07-15 11:32
@roryabraham i like @wildan-m's proposal # 3  https://github.com/Expensify/App/issues/28209#issuecomment-2226740079.

it gives us control which for which files to cache bust

**Comment by MitchExpensify** [comment] 2024-07-16 17:36
Reassigning as I'm heading on leave 🙇

**Comment by zanyrenney** [comment] 2024-08-07 14:29
### payment summary

@wildan-m requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/103153018) (Contributor) - paid $500 via upwork
@rushatgabhane requires payment through NewDot Manual Requests - paid as part of larger help site project. CLosing!

**Closed by zanyrenney** 2024-08-07 14:29 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment
