### ISSUE TITLE
[$250] Dupe detection - Tax amount on confirmation page is negative

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46733] opened 2024-08-02 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4808522
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has some tax rates
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two expenses with same amount, date, merchant, and same non-zero tax rate
4. Go to transaction thread of any expense
5. Click Review duplicates
6. Select Keep this one (any)
7. Proceed to confirmation page

## Expected Result:
Tax amount will not be negative

## Actual Result:
Tax amount on confirmation page is negative

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3caf85b9-3072-40b0-8def-e57f94a1cb34

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01906d0d3fa2f95106</li>
        <li>Upwork Job ID: 1820681328083813277</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103681264</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @FitseTLT</details>

**Comment by lanitochka17** [comment] 2024-08-02 15:44
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-02 15:45
We think that this bug might be related to #wave-collect - Release 2
CC @wavelead

**Comment by FitseTLT** [comment] 2024-08-02 16:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dupe detection - Tax amount on confirmation page is negative

### What is the root cause of that problem?
When we display in confirmation page we use `getTaxAmount`
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/components/MoneyRequestConfirmationListFooter.tsx#L255-L256
but when we display it in review dupe we display the raw `transaction.taxAmount`
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/components/ReportActionItem/MoneyRequestView.tsx#L162-L164
### What changes do you think we should make in order to solve the problem?

We should use getTaxAmount same as we used for the main chat money request view
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/ReportUtils.ts#L2716-L2717
here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/components/ReportActionItem/MoneyRequestView.tsx#L162-L163
```
   const formattedTaxAmount = updatedTransaction?.taxAmount
        ? CurrencyUtils.convertToDisplayString(TransactionUtils.getTaxAmount(updatedTransaction, !isEmptyObject(report) && ReportUtils.isExpenseReport(report)), transactionCurrency)
 
```
### What alternative solutions did you explore? (Optional)
To be consistent with the transaction we display in the money request view for the main chat here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/components/ReportActionItem/MoneyRequestView.tsx#L138-L151
We can pass the `updatedTransaction` through ReportUtils.getTransactionDetails here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/pages/TransactionDuplicate/Confirmation.tsx#L85-L86

**Comment by Tony-MK** [comment] 2024-08-03 14:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Dupe detection - Tax amount on confirmation page is negative

### What is the root cause of that problem?

The problem is that the `TransactionUtils.buildNewTransactionAfterReviewingDuplicates` function directly copies the `originalTransaction` with the tax amount as negative since it is an expense report.
 
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/TransactionUtils/index.ts#L953-L959

### What changes do you think we should make in order to solve the problem?


Like the `getUpdatedTransaction` function, we should have the condition to make the `taxAmount` negative.

https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/TransactionUtils/index.ts#L244

So, in the `TransactionUtils.buildNewTransactionAfterReviewingDuplicates` function let's add a condition like the `getUpdatedTransaction` function when creating the transaction after [this](https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/TransactionUtils/index.ts#L958) line.

```
taxAmount: isFromExpenseReport ? -originalTransaction.taxAmount : originalTransaction.taxAmount;
```

Or we use the `getTaxAmount` function which still checks for `isFromExpenseReport`.

```
taxAmount: getTaxAmount(originalTransaction.taxAmount)
```

### What alternative solutions did you explore? (Optional)

Option 1:

Like the main solution let's check if the `updatedTransaction` `isFromExpenseReport` and convert the `taxAmount` to its negative.

https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/components/ReportActionItem/MoneyRequestView.tsx#L162-L164

```
const formattedTaxAmount = updatedTransaction?.taxAmount
        ? CurrencyUtils.convertToDisplayString(isFromExpenseReport ? -updatedTransaction?.taxAmount : updatedTransaction?.taxAmount , transactionCurrency)
        : CurrencyUtils.convertToDisplayString(transactionTaxAmount, transactionCurrency);
```

Option 2:

We can use the `getUpdatedTransaction` function in the line below to get the updated transaction over a copy of the original transaction passed to `<MoneyRequestView/>`.

https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/pages/TransactionDuplicate/Confirmation.tsx#L85

```
updatedTransaction={getUpdatedTransaction(transaction as OnyxEntry<Transaction>)}
```

**Comment by stephanieelliott** [comment] 2024-08-06 04:40
Added labels -- I agree this should be fixed.

**Comment by trjExpensify** [comment] 2024-08-09 00:35
Dupe detection is now in #wave-control. CC: @pecanoro @JmillsExpensify

**Comment by stephanieelliott** [comment] 2024-08-14 02:05
Hey @mananjadhav we have several proposals here, can. you please review?

**Comment by mananjadhav** [comment] 2024-08-14 17:20
Sorry I was OOO. I'll review the proposals soon.

**Comment by mananjadhav** [comment] 2024-08-15 13:53
Checking the proposals today.

**Comment by pecanoro** [comment] 2024-08-19 19:01
@mananjadhav Friendly bump on the proposals!

**Comment by mananjadhav** [comment] 2024-08-20 14:58
I did review them once. I'll have one of them shortlisted in 2-3 hours.

**Comment by mananjadhav** [comment] 2024-08-20 17:15
Reusing the existing method `getTaxAmount` makes sense. Hence, I think we should go with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/46733#issuecomment-2265778149) here.

🎀 👀 🎀

**Comment by pecanoro** [comment] 2024-08-26 07:39
Assigning @FitseTLT to the issue!

**Comment by mananjadhav** [comment] 2024-08-28 17:03
@FitseTLT any updates on the PR?

**Comment by FitseTLT** [comment] 2024-08-29 15:01
> @FitseTLT any updates on the PR?

@mananjadhav There is a change in latest main: We have now started showing taxAmount always as positive https://github.com/Expensify/App/pull/43519/commits/8ad100211349edc9c3296a678b4645ead8e62294#r1716191793 so the suggested change is not needed anymore.

**Comment by stephanieelliott** [comment] 2024-09-04 02:59
> There is a change in latest main: We have now started showing taxAmount always as positive, [here](https://github.com/Expensify/App/pull/43519/commits/8ad100211349edc9c3296a678b4645ead8e62294#r1716191793), so the suggested change is not needed anymore.

Ok, sounds like we can close this then. Since there was no PR I will not issue payment, but please comment if I missed something and payment should be due

**Closed by stephanieelliott** 2024-09-04 02:59 UTC
Labels: External, Daily, Overdue, Bug
