### ISSUE TITLE
[$500] iOS - When font size is decreased, the page is only scrollable on part of the screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37487] opened 2024-02-29 12:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. On the left bottom option, decrease the font size to any value below 100%.
3. Scroll down the page.

## Expected Result:
The page should be completely visible and functional on the entire screen.

## Actual Result:
The page is visible and scrollable only on part of the screen. This happens with iOS only, on any page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b2c982a0-f79c-491c-af6c-e9a80ba32302

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bbc4ce277d5ce3be</li>
        <li>Upwork Job ID: 1765581169198260224</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-29 12:04
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by jliexpensify** [comment] 2024-03-01 03:08
@izarutskaya is this an iOS safari issue only? I can't seem to repro on Android Chrome.

**Comment by jliexpensify** [comment] 2024-03-03 23:59
Bump @izarutskaya

**Comment by bernhardoj** [comment] 2024-03-04 05:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The sign-in page doesn't take full height when the browser font size is decreased.

### What is the root cause of that problem?
The sign in page has `shouldEnableMaxHeight` enabled which means the page maximum height is set to the `windowHeight` coming from `useWindowDimensions`. However, `windowHeight` value doesn't react to the viewport scale because we normalize it with the current scale that is coming from this [upstream PR](https://www.github.com/necolas/react-native-web/pull/2520/) to fix this [issue](https://www.github.com/Expensify/App/issues/17246).

This becomes a problem because on Safari mobile web, when we reduce the page scale, the document height (`window.document.documentElement.clientHeight`) becomes bigger which doesn't happen on other webs (tested on edge, desktop safari, Android mWeb chrome). Because our `windowHeight` doesn't react to the scale value, it is smaller than the document height. That's why the page doesn't take the full height.

### What changes do you think we should make in order to solve the problem?

We can have a new variable called `scaledWindowHeight` which is the window height multiplied by the viewport scale. We will use this for mWeb safari only and use it as the new max height.
```
const scaledWindowHeight = windowHeight / (window.visualViewport?.scale ?? 1);
```

**Comment by jliexpensify** [comment] 2024-03-07 03:10
Hi @bernhardoj - can you confirm if this is an iOS issue only? @izarutskaya has not responded to my repeated bumps. Thanks!

**Comment by bernhardoj** [comment] 2024-03-07 03:22
@jliexpensify hi, yes, it's an iOS Safari issue only.

**Comment by jliexpensify** [comment] 2024-03-07 03:33
Thank you @bernhardoj - can you confirm that this issue also affects production?

I'm going to make a judgment call on this one, but I think we should fix it IF it also affects production - even though it doesn't relate to a Wave, it directly affects a group of users (iOS) and means that they can't access part of the page. But I don't think it needs to be $500.

**Comment by bernhardoj** [comment] 2024-03-07 03:39
Yes, this affects production too. I think it's fine to keep it at $500 as this affects (not all) many pages too, as shown in the video below (on prod):

https://github.com/Expensify/App/assets/50919443/ea1d9df4-97c2-4496-a06d-59666b0ccc37

**Comment by jliexpensify** [comment] 2024-03-07 03:45
Great, thanks for the video @bernhardoj - appreciate it. Agreed, if it's affecting pretty much every page, lets keep it at $500 and fix it.

**Comment by visortelle** [comment] 2024-03-07 09:49
**Fix proposal.** Here is a `max-height` attribute that should be removed. If the proposal is accepted, I'll check if should it be removed conditionally, depending on the screen size or not, and will check in all major browsers.

<img width="861" alt="Screenshot 2024-03-07 at 1 45 26 PM" src="https://github.com/Expensify/App/assets/9302460/5c38bbbc-7008-4f39-9182-f54f469a8c3c">

**Comment by visortelle** [comment] 2024-03-07 10:29
Contributor details
Your Expensify account email: visortelle@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c7ada531f902b80a

**Comment by jliexpensify** [comment] 2024-03-08 00:09
Hi @fedirjh - can you review please?

**Comment by jliexpensify** [comment] 2024-03-14 10:22
Bump @fedirjh - have you reviewed?

**Comment by jliexpensify** [comment] 2024-03-15 03:11
Actually, I am making the decision to close this due to:

- It only affecting iOS users on Safari
- My assumption that not many users will be physically reducing the font size
- My assumption that as users reduce the font size and discover this issue, they should work out that to reverse it, they will need to enlarge the font size

**Closed by jliexpensify** 2024-03-15 03:11 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by visortelle** [comment] 2024-03-15 03:15
@jliexpensify it would be good to think about these decisions **before** spending other people's time on providing a solution.

Cheers.

**Comment by jliexpensify** [comment] 2024-03-15 05:34
@visortelle Apologies for the sudden decision, but just because a Bug Report is generated that does not guarantee that we'll want to/need to fix the bug. In addition, the .MD also states that contributors are welcome to make proposals, but they may not be accepted or the bug might end up being `Internal` which means that it then won't be worked on by external contributors.

So my feedback to you is that your [comment](https://github.com/Expensify/App/issues/37487#issuecomment-1998865461) here is unnecessary and not appreciated. The reality is even though you've made a proposal, there's a chance it won't be accepted or used - and whilst that is unfortunate, there are plenty of other bugs to work on.

For visibility, I will add some additional context on my [comment](https://github.com/Expensify/App/issues/37487#issuecomment-1998862705): Expensify is choosing to prioritise our roadmap, so everyone in the Bug Zero team has been tasked with re-evaluating all their assigned bugs and working out which Wave or VIP project they are a part of. Unfortunately, I believe that this is a general iOS bug that doesn't fit with any Wave or VIP project at the moment, so in the interest of prioritising the roadmap, I have decided to close this.

It may be re-opened in the future, if we get customers reporting that this is affecting their New Expensify usage.

**Comment by visortelle** [comment] 2024-03-15 06:16
>  the .MD also states that contributors are welcome to make proposals, but they may not be accepted or the bug might end up being Internal which means that it then won't be worked on by external contributors.

You should decide it before creating the Upwork job. Otherwise, it looks completely unethical.
