### ISSUE TITLE
[PAID - Reporting] IOU - When the name of the Merchant is too long, text is out of field in IOU report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25780] opened 2023-08-23 16:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25738
## Action Performed:
1. Open staging.new.expensify.com
2. Go to any chat/report
3. Click on "+" icon
4. Click on "Request money"
5. Enter any amount and click "Next"
6. Click on "Description"
7. Enter any text over 300 characters
8. Click on Save
9. Click on "Show more"
10. Click on "Merchant"
11. Enter any text over 300 characters
12. Click on Save
13. Click on "Request"
14. Click on the message to go to the IOU report

## Expected Result:
Name of merchant should be contained inside the text box

## Actual Result:
Name of merchant is outside the text box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56.18

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7f1bb65c-7e28-4299-9a80-093b7fe3c3af

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team/ @Ahmed-Abdella

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692718440819559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae35c173f09896f0</li>
        <li>Upwork Job ID: 1696218949815410688</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-23 16:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Merchant name overflows in money request preview

### What is the root cause of that problem?
We are not breaking the word currently which seems the cause for it.

### What changes do you think we should make in order to solve the problem?
We can add `styles.breakAll` for the merchat Text.

**Comment by Ahmed-Abdella** [comment] 2023-08-23 16:37
Hi all, I reported this earlier here  [slack] (https://expensify.slack.com/archives/C049HHMV9SM/p1692718440819559), but it didn't make it to github yet

**Comment by situchan** [comment] 2023-08-23 16:37
@lanitochka17 this was first reported by me - https://github.com/Expensify/App/pull/25738#issuecomment-1689091431

**Comment by alphaboss1104** [comment] 2023-08-23 16:42
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Merchant name overflows in money request preview

### What is the root cause of that problem?

We are not breaking the word currently which seems the cause for it.

### What changes do you think we should make in order to solve the problem?

We can wrapping the text document in [here](https://github.com/Expensify/App/blob/43c6f11bd59b1d83ed4cef1162610f3e34aff701/src/components/ReportActionItem/MoneyRequestPreview.js#L272):

```js
          <View style={[styles.flexRow]}>
+               <View style={[styles.flex1]}>
                    <Text style={[styles.textLabelSupporting, styles.mb1, styles.lh16]}>{requestMerchant}</Text>
+               </View>                      
          </View>
```

### What alternative solutions did you explore? (Optional)

Using `numberOfLines` and `ellipsizeMode` properties in the `Text` component to limit the text and indicate there is more.

**Comment by Ahmed-Abdella** [comment] 2023-08-23 16:44
@situchan could you please check again, I reported this more than 24hrs ago. this was before https://github.com/Expensify/App/pull/25738 got fixed. they are different please check again.

**Comment by situchan** [comment] 2023-08-23 16:55
> @situchan could you please check again, I reported this more than 24hrs ago. this was before #25738 got fixed. they are different please check again.

yeah, you reported first. I just wanted to highlight that this is not regression from https://github.com/Expensify/App/pull/25738 and we're already aware of.

**Comment by marcaaron** [comment] 2023-08-23 19:04
Gonna demote this one. Seems like a regular bug and could not reproduce it on web.

**Comment by mountiny** [comment] 2023-08-23 19:07
I think we should include the fix for this issue in this PR https://github.com/Expensify/App/pull/21664 or the PR actually might be fixing it already

**Comment by Ahmed-Abdella** [comment] 2023-08-23 19:12
@marcaaron  reproduced on Web, just make sure you have no spaces in the long merchant name![screenshot_from_2023-08-22_18-26-49.png](https://github.com/Expensify/App/assets/77763699/c7d503cd-f725-4dd3-a88f-373e6ef79bf8)

**Comment by Ahmed-Abdella** [comment] 2023-08-23 19:18
@mountiny I don't think the PR you mentioned fix this, it is about the description input. This issue is about the Merchant and how it is displayed. The description has no issues here. Please check this I reported this earlier in slack (https://expensify.slack.com/archives/C049HHMV9SM/p1692718440819559?thread_ts=1692718440.819559&cid=C049HHMV9SM)

**Comment by mountiny** [comment] 2023-08-23 19:19
We could update the merchant field in the PR the same way as description

**Comment by Ahmed-Abdella** [comment] 2023-08-23 19:27
@mountiny I am sure that they are not related, if you check the video above you will find the description doesn't overflow here and the PR is not merged yet. The description is working fine. The PR fixing the description  input. This issue is how we display the Merchant. Completely different issues.

**Comment by Ahmed-Abdella** [comment] 2023-08-23 19:32
We should completly ignore description here, it is displayed correctly. and it should removed from the steps in the report. It has no affect here.

**Comment by Ahmed-Abdella** [comment] 2023-08-23 19:53
If we fix it the same way as description it will make the Merchant input accept multi lines, and won't fix how the Merchant displayed

**Comment by Ahmed-Abdella** [comment] 2023-08-23 23:48
@mountiny If you have time, Could you please help me on this, I reported this earlier in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1692718440819559), shouldn't I considered the reporter ?

**Comment by mountiny** [comment] 2023-08-24 00:14
Updated you as a reporter, please try to post in less comments

**Comment by stitesExpensify** [comment] 2023-08-28 20:29
This can be handled externally. Not overdue.

**Comment by Ahmed-Abdella** [comment] 2023-08-30 04:21
@stitesExpensify This issue is not reproducible anymore, It got fixed here https://github.com/Expensify/App/pull/21664 after @mountiny asked the contributer to do so. Will I be eligible for the reporting bonus in that case or not as I am the original reporter for this issue and It got fixed depending on that report

**Comment by situchan** [comment] 2023-08-30 20:44
This was planned to fix before this GH is created - https://github.com/Expensify/App/pull/25738#issuecomment-1689091431

**Comment by Ahmed-Abdella** [comment] 2023-08-30 20:50
@situchan my report on slack was before this comment, check it please. https://expensify.slack.com/archives/C049HHMV9SM/p1692718440819559?thread_ts=1692718440.819559&cid=C049HHMV9SM

**Comment by situchan** [comment] 2023-08-30 20:53
yup agree based on https://github.com/Expensify/App/issues/22513#issuecomment-1640951910
But not agree based on https://github.com/Expensify/App/issues/22513#issuecomment-1642797229

**Comment by Ahmed-Abdella** [comment] 2023-08-30 21:07
@situchan could you please clarify this, the other comment you mentioned has nothing to do with this issue

**Comment by situchan** [comment] 2023-08-30 21:12
I just took example.
In that issue, I didn't get compensation though reported earlier because it didn't contribute to fixing the issue.
But it's edge case and depend on BZ members' decision.
Usually, I have seen so far those cases are still eligible for reporting bonus.

**Comment by mountiny** [comment] 2023-08-31 21:23
I think we can pay the rpeorting bonus here, I have asked the contributor to include the fix in existing PR.

**Comment by stitesExpensify** [comment] 2023-09-05 15:06
@strepanier03 can we please pay @Ahmed-Abdella for reporting this, and then we can close it out?

**Comment by strepanier03** [comment] 2023-09-05 23:03
@stitesExpensify - Sure thing, I'll work on that now.

**Comment by strepanier03** [comment] 2023-09-05 23:07
@Ahmed-Abdella - I have hired you for the job in Upwork, please confirm and let me know so I can pay you out.

**Comment by Ahmed-Abdella** [comment] 2023-09-05 23:10
@strepanier03 I accepted the offer, Thanks!

**Comment by strepanier03** [comment] 2023-09-05 23:24
Great, thank you! Working on paying now.

**Comment by strepanier03** [comment] 2023-09-05 23:27
### Payment summary

- [x] - Bug Reporter - @Ahmed-Abdella - $250 paid via Upwork
- [x] - Contributor - N/A
- [x] - C+ - N/A

**Comment by strepanier03** [comment] 2023-09-05 23:27
Closing now!

**Closed by strepanier03** 2023-09-05 23:27 UTC
Labels: External, Engineering, Daily, Help Wanted
