### ISSUE TITLE
[$125] Web - Keyboard shortcuts don't work on Web

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29444] opened 2023-10-12 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29202

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
2. Press CTRL + K, CTRL + Shift + K or CTRL + J

## Expected Result:
Keyboard shortcuts work

## Actual Result:
Keyboard shortcuts don't work

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary> Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/5774130a-738b-480d-b8ad-ba0021e512a3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8718160823e8ebc</li>
        <li>Upwork Job ID: 1712523724517322752</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-12 17:40
I cannot repro

**Comment by pradeepmdk** [comment] 2023-10-12 17:43
i think this is duplicate of this https://github.com/Expensify/App/issues/29341

**Comment by pradeepmdk** [comment] 2023-10-12 17:44
I have a solution for this https://github.com/Expensify/App/issues/29341#issuecomment-1758186392 

if you need quick PR I am available now @mountiny

**Comment by pradeepmdk** [comment] 2023-10-12 17:46
@mountiny  
Repro step:

1. Open FAB menu and close it
2. Press Ctrk+K
3. Expects to open Search page but nothing happens (BUG)
4. Open FAB menu again
5. Close FAB menu by clicking anywhere outside
6. Search page opens this time (BUG)

**Comment by mountiny** [comment] 2023-10-12 22:12
Thanks for linking and confirming this is not ablocker, I am going to close this now then

**Closed by mountiny** 2023-10-12 22:12 UTC
Labels: External, Daily, Help Wanted, Bug
