### ISSUE TITLE
[$1000] Web - Blank image is displayed for image which has another image in reply in thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23817] opened 2023-07-28 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any image
4. Hover and click on reply in thread and send another image
5. Copy URL of another report and logout
6. Paste URL and login
7. Switch off internet and revisit main thread opened in step 2
8. Switch on the internet and observe that image is displayed blank
9. Click on image and observe that it displays fine in preview, close preview and see that it is still blank

## Expected Result:
App should load the images and display them properly once we are back online

## Actual Result:
App loads blank image if image has another image in reply in thread and we logout, login , go offline, visit the thread and come online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d8f2b3ab-6fd0-418a-b985-a66052547795

https://github.com/Expensify/App/assets/93399543/a4c224b7-64f1-45b6-a015-e60029b3cfa5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690542362109319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159c81170d8897913</li>
        <li>Upwork Job ID: 1685856346967736320</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-29 11:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem at hand pertains to image display in the web app. Specifically, if an image has another image in reply in a thread, the app displays the image as blank when a user logs out, logs back in, goes offline, visits the thread and then comes back online. However, the image should load properly once the user is back online.

### What is the root cause of that problem?
The root cause of this problem is that the browser doesn't automatically reload the image once the network connection is reestablished. As such, despite the user being back online, the image remains blank on the thread.

### What changes do you think we should make in order to solve the problem?
To solve this issue, we need to ensure the image reloads once the network reconnects. One potential approach is to use a key prop on Image elements and increment a counter every time the network reconnects, prompting a re-render and thus, a reload of the image. However, due to a known [issue](https://github.com/facebook/react-native/issues/12606) with React Native, this approach might not always work as expected.

Alternatively, we could modify the image URL to include a cache-buster parameter like ?forceReloadAfterOffline=34. This would force the browser to retrieve the image again once back online, bypassing the cache.

A third possible approach is to mimic the behaviour of other image elements that reload after network reconnects, such as Avatars. Their behaviour is likely to not load the image if there is no network, and display another placeholder element in place of the image. Once the network connection is reestablished, the image should then be displayed

**Comment by sophiepintoraetz** [comment] 2023-07-31 03:26
I am able to reproduce this but I do wonder if this has some crossover with this [issue ](https://github.com/Expensify/App/issues/22507)
![2023-07-31_15-07-03 (1)](https://github.com/Expensify/App/assets/42940078/9f51fff6-ace1-4bbb-91ab-c810c65e18f3)

**Comment by sophiepintoraetz** [comment] 2023-08-02 21:53
@ArekChr - can you please take a look at the proposal and see if we can move forward with it?

**Comment by ArekChr** [comment] 2023-08-03 13:24
I have tested this bug and it appears to have been fixed. Now, a skeleton is displayed instead of a blank image.

https://github.com/Expensify/App/assets/24796318/2feca6df-e7f2-4373-b5f0-925721f66e10

**Comment by sophiepintoraetz** [comment] 2023-08-08 03:46
Thank you Arkadiusz! I'll check this a bit later to see whether this is expected.

**Comment by sophiepintoraetz** [comment] 2023-08-10 20:46
Ah, this is still with me.

**Comment by sophiepintoraetz** [comment] 2023-08-14 17:04
Closing this one out because showing a skeleton is expected behaviour when going offline - thanks @ArekChr

**Closed by sophiepintoraetz** 2023-08-14 17:04 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
