### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Workspace - Default currency is clickable as a workspace member and it leads to error page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37288] opened 2024-02-27 13:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is invited as a member of a workspace.
1. Go to staging.new.expensify.com.
2. Log in as workspace member.
3. Open workspace settings.
4. Click on the workspace in which user is a member.
5. Click Currency.

## Expected Result:
Currency should not be clickable, since workspace member will not be able to edit the workspace currency.

## Actual Result:
Currency is clickable, which leads to an error page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a71616ba-b5d5-49df-b166-f7d0878f66f8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc2eec63f826c791</li>
        <li>Upwork Job ID: 1762473973362655232</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 13:45
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by godofoutcasts94** [comment] 2024-02-27 13:55
This is a regression of this [PR](https://github.com/Expensify/App/pull/34897)

**Comment by situchan** [comment] 2024-02-27 14:01
I think @ruben-rebelo should handle this as PR author

**Comment by Pujan92** [comment] 2024-02-27 14:28
Yes, I think we should wait for @ruben-rebelo and let them handle this if they are available.

**Comment by Ron-Maina** [comment] 2024-02-27 14:51
<h1>Cause of the Problem</h1>
Permissions and Read-Only Mode: The code in <strong>WorkspaceProfilePage</strong> checks if the user has administrative privileges (readOnly) to determine whether certain elements, including the currency section, should be editable. If the currency section is mistakenly made clickable regardless of user permissions, it could lead to the mentioned error.

<h1>Possible Solution</h1>
Permissions Check: Verify that the permission checks (readOnly) are correctly applied throughout the component, including the currency section, to prevent unauthorized interactions by adjusting the <strong>MenuItemWithTopDescription</strong> component to prevent clicking on the currency under certain conditions.

**Comment by Ron-Maina** [comment] 2024-02-27 14:58
<h1>Cause of the Problem</h1>
Permissions and Read-Only Mode: The code in <strong>WorkspaceProfilePage</strong> checks if the user has administrative privileges (readOnly) to determine whether certain elements, including the currency section, should be editable. If the currency section is mistakenly made clickable regardless of user permissions, it could lead to the mentioned error.

<h1>Possible Solution</h1>
Permissions Check: Verify that the permission checks (readOnly) are correctly applied throughout the component, including the currency section, to prevent unauthorized interactions by editing the <strong>MenuItemWithTopDescription</strong> component to prevent clicking on the currency under certain conditions.

**Comment by luacmartins** [comment] 2024-02-27 18:32
This was a known issue and a dupe of https://github.com/Expensify/App/issues/37100.

**Comment by sonialiap** [comment] 2024-03-12 10:29
@Pujan92 sorry I missed this last week, it didn't come up in my search

@Pujan92 Reviewer $500 offer sent
ruben-rebelo - callstack, no payment needed

**Comment by Pujan92** [comment] 2024-03-12 10:31
Np, accepted the offer :)

**Closed** 2024-03-12 11:52 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment
