### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] First field is not focused after clicking the fix the errors link on Connect Manually page reported by @parasharrajat 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12400] opened 2022-11-02 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app on web.
2. Go to Settings.
3. Click on any workspace(if there are not workspace create new).
4. Go to Connect Bank Account menu.
5. Select Connect Manually.
6. Press save & Continue  without entering any information on any field.
7. fix the errors shows up above the save & continue button.
8. Click on the link.
9. Observe that all the fields are red but focus is set to Account number Field even if there is a error field above it.

## Expected Result:
 Focus should be set on `Routing Number` field.

## Actual Result:
 When all fields are errored, focus is not set on the first field called Routing Number.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.22-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (1)](https://user-images.githubusercontent.com/43996225/199597214-3169ceb2-59b6-45e2-a560-11692b11ebb8.png)
https://user-images.githubusercontent.com/43996225/199597236-7faabc85-1baf-4b22-ba6c-05bf4aa06abc.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665921536612629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-11-03 10:51
<b>Proposal</b>
There's no focus prop for current Routing Number input in here:
https://github.com/Expensify/App/blob/25c306015d7b08fec915e6005cde7c928bdc847e/src/pages/ReimbursementAccount/BankAccountManualStep.js#L94-L100
<b>Solution</b>
Add `autoFocus` to this `TextInput`:
```diff
                    <TextInput
+                      autoFocus
                        inputID="routingNumber"
                        label={this.props.translate('bankAccount.routingNumber')}
                        defaultValue={ReimbursementAccountUtils.getDefaultStateForField(this.props, 'routingNumber', '')}
                        keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
                        disabled={shouldDisableInputs}
                        shouldSaveDraft
                    />
```

Result:

https://user-images.githubusercontent.com/16502320/199702522-062009dc-c1c9-4e72-8fde-0ce51cc4ce32.mov

**Comment by gadhiyamanan** [comment] 2022-11-03 11:36
**Proposal**
we need to rearrange errorFields as below.  add routingNumber validation before accountNumber validation

Before : 
https://github.com/Expensify/App/blob/25c306015d7b08fec915e6005cde7c928bdc847e/src/pages/ReimbursementAccount/BankAccountManualStep.js#L36-L54

After: 
```
    validate(values) {
        const errorFields = {};
        const routingNumber = values.routingNumber && values.routingNumber.trim();

        if (!routingNumber || !CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(routingNumber) || !ValidationUtils.isValidRoutingNumber(routingNumber)) {
            errorFields.routingNumber = this.props.translate('bankAccount.error.routingNumber');
        }
        if (
            !values.accountNumber
            || (!CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) && !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim()))
        ) {
            errorFields.accountNumber = this.props.translate('bankAccount.error.accountNumber');
        }
        if (!values.acceptedTerms) {
            errorFields.acceptedTerms = this.props.translate('common.error.acceptedTerms');
        }

        return errorFields;
    }

```

it's because we have set focus on the first errorfield in From.js

https://github.com/Expensify/App/blob/25c306015d7b08fec915e6005cde7c928bdc847e/src/components/Form.js#L230-L232

**Comment by zanyrenney** [comment] 2022-11-03 18:04
Sorry @hungvu193 i'm not clear if you are saying this bug Will be fixed as part of that proposal above, or if that proposal above is a fix for this specific bug?

**Comment by hungvu193** [comment] 2022-11-04 04:16
@zanyrenney my bad. I misunderstood the description, I deleted it since there was a good proposal above.

**Comment by hungvu193** [comment] 2022-11-06 10:30
@rushatgabhane Yeah, we can update the way we focus on field in:
https://github.com/Expensify/App/blob/25c306015d7b08fec915e6005cde7c928bdc847e/src/components/Form.js#L230-L232

```diff
 onFixTheErrorsLinkPressed={() => { 
-      this.inputRefs[_.first(_.keys(this.state.errors))].focus(); 
+     this.findFirstError()
 }} 

```

```javascript
 findFirstError = () => {
        const errorArrays = _.keys(this.state.errors);
        const inputArrays = _.keys(this.inputRefs);
        let currentFocusKey = null;
        _.every(inputArrays, (currentFieldKey) => {
            const errorIndex = _.indexOf(errorArrays, currentFieldKey);
            if (errorIndex !== -1) {
                currentFocusKey = currentFieldKey;
                return false;
            }
            return true;
        });
        if (currentFocusKey) {
            this.inputRefs[currentFocusKey].focus();
        }
    }
```

https://user-images.githubusercontent.com/16502320/200165724-be9565ef-c4ae-40e2-bfbd-9400640aae25.mov

**Comment by hungvu193** [comment] 2022-11-06 11:14
There are similar error reported here: https://github.com/Expensify/App/issues/12436
That because we are using different Form components for different forms. And each form has different way to handle press Fix Error. We should avoid that.

**Comment by parasharrajat** [comment] 2022-11-06 14:28
@0xmiroslav  Nice one. Exactly the way I was thinking (mount order).

**Comment by zanyrenney** [comment] 2022-11-07 10:01
Looks like we have a proposal - @ctkochan22 let me know what you think!

**Comment by Santhosh-Sellavel** [comment] 2022-11-09 01:03
@hungvu193 @0xmiroslav I tested both of your proposals both are working for the connect manually page. But not working for other pages
example for company setup page,

https://user-images.githubusercontent.com/85645967/200710320-5042ee52-a6b0-4e64-825e-cc504dd79df7.mov

**Comment by hungvu193** [comment] 2022-11-09 01:06
> There are similar error reported here: https://github.com/Expensify/App/issues/12436
> That because we are using different Form components for different page. And each form has different way to handle press Fix Error. We should avoid that.

As I mentioned here, they are using different Form component, I think we are a PR to refactor that already

**Comment by Santhosh-Sellavel** [comment] 2022-11-11 01:15
Sorry for the delay, @ctkochan22. 
Both proposals are working!
But I like @0xmiroslav's proposals, here!
C+ Reviewed
🎀 👀 🎀

**Comment by ctkochan22** [comment] 2022-11-11 01:18
Cool thanks team. @zanyrenney lets hire @0xmiroslav

**Comment by Santhosh-Sellavel** [comment] 2022-11-14 16:37
PR is ready for review!

**Comment by zanyrenney** [comment] 2022-11-15 12:01
@0xmiroslav I can't find you on Upwork when I am trying to hire you:
<img width="1176" alt="2022-11-15_12-00-33" src="https://user-images.githubusercontent.com/56830058/201914713-041a8e69-bc32-4b73-a557-2dacd7b0555e.png">
<img width="1083" alt="2022-11-15_12-00-22" src="https://user-images.githubusercontent.com/56830058/201914739-8f573135-c86d-433d-a5cd-6f19438bc4b3.png">

Please can you apply to the job directly via this link: https://www.upwork.com/jobs/~01a2007b1a50c1fece

**Comment by zanyrenney** [comment] 2022-11-18 11:37
Hmm, I don't see the regression test linked - @ctkochan22 @Santhosh-Sellavel any idea where I'd find that?

**Comment by Santhosh-Sellavel** [comment] 2022-11-21 14:45
@ctkochan22 bump!

**Comment by ctkochan22** [comment] 2022-11-22 06:51
Added

**Comment by luacmartins** [comment] 2022-11-29 16:55
I'm not sure that the offending PR is correct. The feature was introduced in the linked PR and worked well. AFAIK we had quite a few regressions on this functionality along the way, e.g. https://github.com/Expensify/App/issues/11424 and https://github.com/Expensify/App/issues/11729

**Comment by Santhosh-Sellavel** [comment] 2022-12-05 16:52
@zanyrenney This is due for payment, also the PR is eligible for %50 bonus as it was merged in 3 biz days!

**Comment by parasharrajat** [comment] 2022-12-05 16:54
I think when this issue was solved,  %50 bonus was not active. But it could be.

**Comment by Santhosh-Sellavel** [comment] 2022-12-05 17:02
@parasharrajat Bonus was active on issue hires made after Nov 4. As we can see they are hired on Nov 11 Friday. Merged within the next 3 business days i/e by Nov 16. So it's eligible for a bonus!

**Comment by ctkochan22** [comment] 2022-12-06 05:46
Sorry, was ooo last week on a family emergency. Looks like we need to add a regression test. Looking up how to do that now

**Comment by zanyrenney** [comment] 2022-12-06 17:42
Paid and included Bonus @0xmiroslav

**Comment by zanyrenney** [comment] 2022-12-06 17:56
oops, missed some payments here. Reopening!

**Comment by zanyrenney** [comment] 2022-12-06 17:58
https://www.upwork.com/jobs/~01a2007b1a50c1fece - i need you to apply for the job @parasharrajat @Santhosh-Sellavel so I can pay you.

**Comment by zanyrenney** [comment] 2022-12-07 11:25
@Santhosh-Sellavel @parasharrajat - paid!

**Closed by zanyrenney** 2022-12-07 11:25 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
