### ISSUE TITLE
[Paid - HOLD for BE fix] Search bar - Another error message for a short time when opening archived chat from search bar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26657] opened 2023-09-04 12:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open webiste
2. Click on search icon and find any archived workspace that has some messages in it so that it should be loaded for a short time.
3. While loading this chat, you can see another error message for a short time

## Expected Result:
There should not appear another error message for a short time when opening archived chat from search bar

## Actual Result:
Another error message for a short time when opening archived chat from search bar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a0f3d87a-909b-4a93-b9de-28637d5b6c29

https://github.com/Expensify/App/assets/115492554/80383b2b-6be7-43d9-bc07-5dbdc07137b6

https://github.com/Expensify/App/assets/115492554/8602f8a2-b360-4881-8980-8efca7acab4e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692963972266199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01262419686265c297</li>
        <li>Upwork Job ID: 1701300837881397248</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26665415</li>
<li>tienifr | Contributor | 26665416</li>
<li>mahmudjontoraqulov | Reporter | 26665420</li>
</ul></li>
    </ul>
</details>

**Comment by jscardona12** [comment] 2023-09-04 15:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search bar - Another error message for a short time when opening archived chat from search bar
### What is the root cause of that problem?
This error is not happening just on the search it happens when the reportActions are not save in the browser Onyx IndexDB. The first call it will return null to inititialize and make the component is the dafault props in which in this case the default props brings the defailt message that we are seeing for a short time. 

THis is state in the Onyx Code:
<img width="853" alt="Screenshot 2023-09-04 at 10 29 55 AM" src="https://github.com/Expensify/App/assets/16781411/2e5500ba-f6d3-47cc-af0e-473598805664">

### What changes do you think we should make in order to solve the problem?
We wait to render if the value of `archiveReason` is "default" in [ArchivedReportFooter.js](https://github.com/Expensify/App/blob/main/src/components/ArchivedReportFooter.js#L52)

### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment] 2023-09-11 18:25
Adding external label!

**Comment by jjcoffee** [comment] 2023-09-12 15:42
@jscardona12's [proposal](https://github.com/Expensify/App/issues/26657#issuecomment-1705454248) doesn't feel so clear to me in the RCA and both solutions lack detail.

Happy to go with @tienifr's [proposal](https://github.com/Expensify/App/issues/26657#issuecomment-1714973164) as it has the correct RCA and the solution looks good. I'd probably prefer the skeleton rather than just the empty tag. I'm not sure if we need some design input here?

:ribbon::eyes::ribbon: C+ reviewed

**Comment by robertjchen** [comment] 2023-09-14 03:01
Thanks for the review, I also agree with @tienifr 's proposal 👍 Let's definitely go with the skeleton, and we can always make design improvements later.

**Comment by jjcoffee** [comment] 2023-10-05 14:50
Just noting that this one got delayed because we needed a bit of design back and forth to settle on the right look for the skeleton.

**Comment by jjcoffee** [comment] 2023-10-16 09:14
The PR got reverted as a result of https://github.com/Expensify/App/issues/29087. We [agreed](https://github.com/Expensify/App/issues/29087#issuecomment-1761715226) that it wasn't technically a regression as there's an existing BE issue that was just previously better masked. 

I think it makes sense to patch the BE first before re-releasing this PR, but a bit unsure of the process. Do you need to apply the internal label? @sakluger

**Comment by sakluger** [comment] 2023-10-16 17:12
Yes, I think that is the correct process. Even though there is no penalty, we should wait until the issue is fixed and live before payment anything out.

@robertjchen since you are already assigned to this issue, are you available to help patch the backend issue?

**Comment by sakluger** [comment] 2023-10-18 16:14
Asked @robertjchen here if he can help with the BE fix.

**Comment by sakluger** [comment] 2023-10-19 17:40
I asked for a volunteer [here](https://expensify.slack.com/archives/C03SSAQ7P/p1697737217556089).

**Comment by sakluger** [comment] 2023-10-20 20:47
No volunteers yet, asked for help again.

**Comment by sakluger** [comment] 2023-10-23 20:32
Still no volunteers, bumped the Slack thread.

**Comment by sakluger** [comment] 2023-10-24 21:16
I asked @robertjchen if he's able to step in an work on this one, we'll see!

**Comment by sakluger** [comment] 2023-10-25 16:30
We're having trouble finding a BE engineer to work on this, so I've gone ahead and paid out everyone for their work on this issue. I'm going to switch it to monthly while we work on finding someone to fix the backend, once we're ready to redeploy I will increase the urgency again.

**Comment by MahmudjonToraqulov** [comment] 2023-10-30 08:32
@sakluger I got paid and thanks for that. But the payment was 250$. Is the payment should be 250$ or it was by mistake?

**Comment by MahmudjonToraqulov** [comment] 2023-11-02 09:05
> @sakluger I got paid and thanks for that. But the payment I got was 250$. Is the payment should be 250$ or it was by mistake?

Bump @sakluger for a question.

**Comment by sakluger** [comment] 2023-11-22 22:24
@MahmudjonToraqulov Yes that was the correct payment since you reported the bug before we updated our payout rates.

**Comment by robertjchen** [comment] 2023-12-28 11:34
BE work pending

**Comment by sakluger** [comment] 2024-01-29 19:56
@robertjchen any updates?

**Comment by robertjchen** [comment] 2024-03-04 05:17
no update, focus is on waves. Soon!

**Comment by sakluger** [comment] 2024-04-03 23:20
Added to vip-vsb project, since all open projects need to be associated with a wave or vip.

**Comment by sakluger** [comment] 2024-05-08 00:22
Still on hold.

**Comment by robertjchen** [comment] 2024-06-11 06:15
Holing for backend

**Comment by robertjchen** [comment] 2024-07-07 09:18
still holding for BE

**Comment by sakluger** [comment] 2024-08-08 16:26
@robertjchen any updates?

**Comment by sakluger** [comment] 2024-10-11 00:08
I'm going to move this to daily and test tomorrow to see if this is even still happening. It's been a long time and we've closed the #vip-vsb project that this was tied to, so we either need to move it to another project, or close the issue.

**Comment by jjcoffee** [comment] 2024-10-15 07:07
@sakluger The original fix was reverted due to pending required BE changes ([this comment](https://github.com/Expensify/App/issues/26657#issuecomment-1764056910) has some context). Payment was already made on that basis, but the BE fix was never made.

**Comment by sakluger** [comment] 2024-10-16 16:17
Oh yeah - I even updated the title to remind myself that this was already paid out 🤦‍♂️ .

I'll post one more time in Slack to see if we want to finish the BE piece or if we should just close it.

**Comment by sakluger** [comment] 2024-10-16 17:06
As recommended, I am moving this to `#quality` as a LOW priority project. I will unassign @robertjchen and move back to monthly. That way, if a BE engineer is looking for an issue to work on, they'll see that it's available.

**Comment by muttmuure** [comment] 2024-11-12 10:48
I know I said that we would fix this eventually, but I am correcting myself now, given that we want the Quality project board to be useful to internal engineers, and a long list of insignificant, non-customer-reported bugs impedes that. 

Closing out.

**Closed by muttmuure** 2024-11-12 10:48 UTC
Labels: External, FirstPick, Monthly, Internal, Bug
