### ISSUE TITLE
[$500] IOU Report - Two separate IOU reports created in the same 1:1 chat

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#34674] opened 2024-01-17 21:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-8
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1705451831035939?thread_ts=1705449509.628199&cid=C01GTK53T8Q

## Action Performed:
_@mallenexpensify reproduction steps_
1. Received money request from Scott
2. Noticed it didn't include the $2.87 I knew I already owed him
3. Asked Scott to request $1 manually
4. $1 was added to the the most recent IOU request, old one hasn't been updated the past two transactions

_Alternate reproduction steps:_
1. Create 2 manual IOUs in a 1:1 conversation with user B
2. Create a Split with a scanned expense in a group conversation that includes user B and another user
3. Wait for the Scan to finish 
4. Create a manual Split in the same conversation
5. Navigate back to the 1:1 to check the IOU reports

## Expected Result:
There should be only one, ongoing IOU request between two users.

## Actual Result:
There are two active IOU requests 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/f1009c33-3628-4230-abc6-333f11d94f52)
![image](https://github.com/Expensify/App/assets/44479856/0dfa1910-b304-4df3-a3ed-0055b0ecb22a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a527a0df0c4b582d</li>
        <li>Upwork Job ID: 1747731238713110528</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by isagoico** [comment] 2024-01-18 13:51
I was able to reproduce the issue, here are the steps: 

1. Create 2 manual IOUs in a 1:1 conversation with user B
2. Create a Split with a scanned expense in a group conversation that includes user B and another user
3. Wait for the Scan to finish 
4. Create a manual Split in the same conversation
5. Navigate back to the 1:1 to check the IOU reports

On the image below: 
1. IOU report 1 contains the expenses made in the 1:1 conversation
2. IOU report 2 contains the split expenses made in the group conversation

![image](https://github.com/Expensify/App/assets/44479856/df1183d2-604b-4927-b896-28d8a5036715)

**Comment by joekaufmanexpensify** [comment] 2024-01-22 14:59
Not overdue. Pending proposals

**Comment by joekaufmanexpensify** [comment] 2024-01-23 14:39
Same

**Comment by eVoloshchak** [comment] 2024-01-23 22:04
> any reason you can think this shouldn't be external?

@mallenexpensify, this could be a BE issue, but could also be a problem on the FE.
I'm leaning toward the first one, but it's only a guess, I haven't done any investigating myself. 
Let's leave this External for now and wait for proposals

**Comment by joekaufmanexpensify** [comment] 2024-01-25 16:04
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-01-29 14:36
I will bring this one to slack to solicit proposals if nothing soon

**Comment by joekaufmanexpensify** [comment] 2024-01-30 22:42
Going to look at which project this fits into tomorrow

**Comment by joekaufmanexpensify** [comment] 2024-02-02 21:45
Hmm, I followed the exact reproduction steps listed above, and could not reproduce. Specifically, I: 

1. Logged into jkaufman+51@expensifail.com, and created two manual IOUs with jkaufman+7@expensifail.com. 
2. Then, I did a scanned split with jkaufman+51@expensifail.com, jkaufman+7@expensifail.com, and jkaufman+0@expensifail.com. 
3. Then, I did a manual split with jkaufman+51@expensifail.com, jkaufman+7@expensifail.com, and jkaufman+0@expensifail.com. 
4. When I go back to the DM between jkaufman+51@expensifail.com and jkaufman+7@expensifail.com, I see all 4 requests combined into one report. 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/8cf87ea4-f90e-435a-bbd2-4b04792e3a06">

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/aa2f6cee-0918-4077-9b8a-d6e20eb7b0f7">

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/800527cb-1386-4f9e-9700-3be04547d4fe">

**Comment by joekaufmanexpensify** [comment] 2024-02-02 21:45
Going to close this one for now, as it doesn't seem to be consistently reproducible. If there are other steps that can be used to consistently reproduce this, let me know, and happy to investigate further!

**Closed by joekaufmanexpensify** 2024-02-02 21:45 UTC
Labels: External, Daily, Help Wanted, Bug
