### ISSUE TITLE
[$500] Login - Can't go back after trying to log in using another tab with invalid code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34584] opened 2024-01-16 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Enter an email and tap on "Continue"
3. Go to email inbox and copy the magic link
4. Modify the last portion of the link (magic code) and change it to staging
5. Go to link on another tab (code expired page should be displayed)
6. Return to original tab and tap on "Go back"

## Expected Result:
The user should be taken to the main login page

## Actual Result:
The "Go back" button is unresponsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/93399543/452b67c4-93dd-405b-a660-3ab41e7e81ab

https://github.com/Expensify/App/assets/78819774/d2bcbe78-769d-4a69-a332-7d5c3815a41d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8455532fbcf8436</li>
        <li>Upwork Job ID: 1747291164819349504</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-16 15:16
Issue is not reproducible in production

https://github.com/Expensify/App/assets/93399543/ae9f7746-2acf-45c4-8430-d1139fc2a788

**Comment by s-alves10** [comment] 2024-01-16 16:50
This looks like a regression of this PR https://github.com/Expensify/App/pull/33554(Onyx update)

**Comment by ikevin127** [comment] 2024-01-16 17:32
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The "Go back" button is unresponsive after trying to log in using another tab with invalid code.

## What is the root cause of that problem?

https://github.com/Expensify/App/blob/ee7704626bdd70ed469fb270da65a38680403454/src/libs/actions/Session/index.ts#L593-L598

The `Onyx.multiSet` in the block above doesn't work as expected, even though it gets called, the keys are not set to `null`.

## What changes do you think we should make in order to solve the problem?

If we're looking for a quick, working solution then instead of `Onyx.multiSet` we should use `Onyx.set` twice.
Once we unblocked deploy, we should figure out why `Onyx.multiSet` doesn't work in this edge case.


## Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/c5bfb347-c783-4153-b11c-d221ac6fcb8b

</details>

**Comment by mountiny** [comment] 2024-01-16 18:00
@ikevin127 Are you suggesting this is repro in production too? because this code has been around for a while

**Comment by situchan** [comment] 2024-01-16 18:03
> The `Onyx.multiSet` in the block above doesn't work as expected, even though it gets called, the keys are not set to `null`.

It's possible that the root cause came from recent Onyx update.

**Comment by ikevin127** [comment] 2024-01-16 18:11
@mountiny It's only reproducible on staging / dev, it didn't get to production yet.

**Comment by AndrewGable** [comment] 2024-01-16 22:11
@mountiny fixed with his revert

**Closed by AndrewGable** 2024-01-16 22:11 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted

**Comment by chrispader** [comment] 2024-01-19 14:49
I'm trying to reproduce this after bumping Onyx again in https://github.com/Expensify/App/pull/34801

I can't get to the point where it says "the code is expired". If i change the last part of the URL to any other number/string, it just shows me this string. Same thing if i change it to a staging address.

Is this the expected behaviour?

Also the "Go back" button is responsive in the development version.

@mountiny do i need to configure anything special or use an ad-hoc build to get a similar repro environment?
