### ISSUE TITLE
[$2000] IOS/Android - Page is moving up in Password page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9122] opened 2022-05-20 23:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. In log in page put the email address
3. Tap Continue
4. In Password page start typing your password

## Expected Result:
Page is not moving up in Password page

## Actual Result:
Page is moving up in Password page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.65.3
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/169623660-8cb5382e-145d-47c3-946a-487dc0da46fd.mp4

https://user-images.githubusercontent.com/93399543/169623662-681e53cb-b497-4548-865e-80680c410c54.mp4

**Upwork job link:** https://www.upwork.com/jobs/~01edd8f91c1de28679

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-05-20 23:34
Also seems most likely related to https://github.com/Expensify/App/pull/8752

**Comment by marcaaron** [comment] 2022-05-20 23:35
It's the only material change in the release that would affect the UI.

**Comment by Santhosh-Sellavel** [comment] 2022-05-21 06:43
@marcaaron 
This issue seems related to #8752 for sure not introduced in #8752.

The issue already exists before these changes. Here is a screen recording from our production version 1.1.64.0 (#8752 is not deployed to production)

https://user-images.githubusercontent.com/85645967/169639444-4987eaa7-4812-46eb-8d9f-963de5ee3c7c.MP4

**Comment by kbecciv** [comment] 2022-05-21 13:07
@Santhosh-Sellavel This is issue is not reproduced in Production.

https://user-images.githubusercontent.com/93399543/169652863-cdddd88f-78d9-423b-a954-f33e2a92a3b0.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-05-21 13:44
> @marcaaron 
> This issue seems related to #8752 for sure not introduced in #8752.
> 
> The issue already exists before these changes. Here is a screen recording from our production version 1.1.64.0 (#8752 is not deployed to production)
> 
> https://user-images.githubusercontent.com/85645967/169639444-4987eaa7-4812-46eb-8d9f-963de5ee3c7c.MP4
> 
> 
> 

@kbecciv This is from production too.

**Comment by kbecciv** [comment] 2022-05-21 13:49
@Santhosh-Sellavel I understand, by watching your video - page is not moving. Please compare your result in STG, you will see the difference.

**Comment by Santhosh-Sellavel** [comment] 2022-05-21 14:18
@kbecciv 
Here is the comparison result for staging & prod, I'm not notice anything different between both versions in both apps!

### IOS
https://user-images.githubusercontent.com/85645967/169655276-095c0c2c-e915-456e-88a9-fc9ec48abb45.mov

### Android
https://user-images.githubusercontent.com/85645967/169655517-84d2a19c-bafd-4042-a6e0-39f4b3f6cbc7.mov

cc: @marcaaron

**Comment by Julesssss** [comment] 2022-05-23 17:17
I agree with @Santhosh-Sellavel here. The difference is subtle, but it does seem like the issue already exists on prod. Here's my screencap from the production branch: 

https://user-images.githubusercontent.com/10736861/169873273-7f3d5512-2c7e-4e8e-9881-701b20abb7a6.mov

**Comment by michaelhaxhiu** [comment] 2022-05-25 21:26
Job posted to upwork here - https://www.upwork.com/jobs/~01edd8f91c1de28679

**Comment by Santhosh-Sellavel** [comment] 2022-06-01 16:35
@michaelhaxhiu @marcaaron 
We're still looking for a proposal here. As I'm going on OOO unassigning this one. Can anyone re-apply Exported label again here? thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-06-01 19:29
Help Wanted label is removed add that back!

**Comment by michaelhaxhiu** [comment] 2022-06-02 13:05
Hm I think this is due for a price doubling as it's been 8 days. 

(I wonder if the label changes messed with the slackbot logic, as I didn't get a ping for it yet 🤔 )

**Comment by michaelhaxhiu** [comment] 2022-06-09 21:19
doubled, again

**Comment by MTN718** [comment] 2022-06-13 20:50
**Proposal Shane** 

It's because of LoginKeyboardAvoidingView control when keyboard shows, password form move up. So to avoid it, change LoginKeyboardAvoidingView to View and then it doesn't move up Password Form

![image](https://user-images.githubusercontent.com/12084368/173442105-fae5f900-8297-4a93-8a25-ef4972a237c1.png)


To like this

![image](https://user-images.githubusercontent.com/12084368/173442179-1b2dd33d-2eed-402a-ba91-f7c2077a0b5b.png)

https://user-images.githubusercontent.com/12084368/173443060-1ba67fc2-e0a8-47ab-9fb7-2d89f3d9c8c7.mov

**Comment by rushatgabhane** [comment] 2022-06-13 21:13
@MTN718 we want the content to move out of the way of the virtual keyboard. Removing `LoginKeyboardAvoidingView` isn't a good idea.

**Comment by MTN718** [comment] 2022-06-14 06:05
What about add LoginKeyboardAvoidingView only TextInput for password? Currently it is covering logo, button and text(status)..

**Comment by rushatgabhane** [comment] 2022-06-16 17:05
@MTN718 the footer should move up when keyboard is opened. But it shouldn't cause the things above it to move up.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/29673073/174126555-c401029a-0cb1-41f8-bc39-0d54bcb0ab3d.png">

**Comment by MTN718** [comment] 2022-06-16 17:10
Ah yes that's no problem. Original code footer does not in KeyboardAvodingView. So we should be put footer in KeyboardAvodingView then. I will attach Video

**Comment by MTN718** [comment] 2022-06-16 18:00
https://user-images.githubusercontent.com/12084368/174135958-8617fcb4-3cd2-4756-97d2-3a42940c2df9.mov

**Comment by rushatgabhane** [comment] 2022-06-16 21:14
@MTN718 I'm sorry that I wasn't clear about the expected behavior.

In this video there are two pages - email and password page. In both pages you can see that the footer moves up without moving the text inputs.


In email page, on opening the keyboard the text inputs don't move up. But in password page, on opening the keyboard the whole page shifts up a bit. This is the issue.

https://user-images.githubusercontent.com/29673073/174164126-c108fb98-d103-427b-b263-fd4d7cfad120.mp4

**Comment by michaelhaxhiu** [comment] 2022-06-17 11:39
Doubling price of job.

**Comment by rushatgabhane** [comment] 2022-06-17 12:28
@sobitneupane I'm sorry, I don't understand. 
This is how it should look like https://github.com/Expensify/App/issues/9122#issuecomment-1133631246

**Comment by MTN718** [comment] 2022-06-17 12:55
## Proposal

Moving screen up because of this part of code (forget? button section)

![image](https://user-images.githubusercontent.com/12084368/174301361-76497cb8-0bd7-48f7-8fec-8170ff9ea714.png)

It makes keyboard avoiding section increase than username input section. So should be KeyboardAvodingSection should be cover only TextInput in Passwod Form like this

![image](https://user-images.githubusercontent.com/12084368/174301570-2f80b3f4-351a-42ea-bd00-52119b985d8a.png)

## Solution
1. Change LoginkeyboardAvodingView to View like this

![image](https://user-images.githubusercontent.com/12084368/174301781-eb847577-5db6-4b38-acc1-13ebfdc3aecc.png)


2. Change LoginForm and Password TextInput under KeyboardAvodingView

![image](https://user-images.githubusercontent.com/12084368/174301891-52e27c0c-1d4b-4468-8227-e6bd07a91c0c.png)

![image](https://user-images.githubusercontent.com/12084368/174301937-64811222-6f3a-44df-b7f8-6560e1610bdf.png)

Then it will resolve :)


https://user-images.githubusercontent.com/12084368/174302494-7304107f-cd1f-4f51-84ec-00278f3ec301.mp4

**Comment by rushatgabhane** [comment] 2022-06-17 14:50
@MTN718 Thanks for your proposal! But it does not match the expected behavior shown here https://github.com/Expensify/App/issues/9122#issuecomment-1133631246
If i'm missing something, please let me know

**Comment by MTN718** [comment] 2022-06-17 14:56
@rushatgabhane 
Footer is Moving in Android. But not IOS from original code without my change.
And I'm having a problem to record in Android But my code also moving Android footer too.

**Comment by rushatgabhane** [comment] 2022-06-17 14:59
@MTN718 no that's okay, you don't need to add video for it

**Comment by MTN718** [comment] 2022-06-17 15:00
@rushatgabhane Ok Thanks. My solution will be work ?

**Comment by mananjadhav** [comment] 2022-06-19 19:42
@rushatgabhane trying to understand if this and https://github.com/Expensify/App/issues/6941 are related?

**Comment by MTN718** [comment] 2022-06-20 12:32
@rushatgabhane What about feedback for my solution?

**Comment by parasharrajat** [comment] 2022-06-20 19:57
@MTN718 brought my attention to this issue. Just want to add that this issue was not happening last time I checked (maybe two months back).

I will try to debug this one along https://github.com/Expensify/App/issues/6941 to see what could be wrong.

**Comment by MTN718** [comment] 2022-06-20 19:58
No it's happening i tested some days ago with @rushatgabhane. You can see video.

**Comment by rushatgabhane** [comment] 2022-06-23 16:58
Interesting. I couldn't repro this issue because I had some text autofilled.

https://user-images.githubusercontent.com/29673073/175353758-5f46dbf2-0c83-4f18-9273-b0d6cb7d3658.mp4

**Comment by rushatgabhane** [comment] 2022-06-23 17:03
Can you please dive deeper into the root cause? I think `git bisect` will be helpful because this issue isn't on production.

**Comment by MTN718** [comment] 2022-06-23 17:10
@rushatgabhane I have explained it's because of avoiding section height increasing when go password screen. I have tried reduce it and then it does not move up

**Comment by rushatgabhane** [comment] 2022-06-23 17:15
> Moving screen up because of this part of code (forget? button section)
It makes keyboard avoiding section increase than username input section. So should be KeyboardAvodingSection should be cover only TextInput in Passwod Form like this

@MTN718 I don't think it's because of that because it works fine in production. Please let me know if I'm missing something

**Comment by MTN718** [comment] 2022-06-23 17:18
@rushatgabhane How can i check production app for android/ios?

**Comment by rushatgabhane** [comment] 2022-06-23 17:19
@MTN718 you can download it from the app store. Or checkout to the [production](https://github.com/Expensify/App/tree/production) branch

**Comment by rushatgabhane** [comment] 2022-06-23 17:27
> Can this issue be closed if it's not reproducible?

@marcaaron i'm sorry for the misunderstanding. This issue is reproducible on main and staging.

**Comment by MTN718** [comment] 2022-06-23 17:39
@rushatgabhane I just pull from production branch and try run on Android but still problem on production branch too. Let me add video

**Comment by rushatgabhane** [comment] 2022-06-23 17:44
@MTN718 if you'll checkout to this commit  https://github.com/Expensify/App/commit/bdb101a14bbd356a111f2e8e11755b058d1082be which was made 23 days ago, you won't be able to repro this issue.

**Comment by MTN718** [comment] 2022-06-23 17:46
You mean main branch?

**Comment by MTN718** [comment] 2022-06-23 18:07
I have checkout that commit and tried run on android. But it's same

![image](https://user-images.githubusercontent.com/12084368/175365516-eb3c05d0-86ec-4f70-b486-d01d7d24b7ab.png)

Let me add video

**Comment by rushatgabhane** [comment] 2022-06-24 18:42
@MTN718 I think that is how it's supposed to work https://github.com/Expensify/App/issues/9122#issuecomment-1164716952

**Comment by MTN718** [comment] 2022-06-24 19:18
https://github.com/Expensify/App/issues/9122#issuecomment-1158136155

In this comment, you mentioned
"In this video there are two pages - email and password page. In both pages you can see that the spacing between footer and text input reduces on opening the keyboard.

In email page - opening the keyboard doesn't move the text input. But in password page, opening the keyboard shifts the whole page UP by a bit. This is the issue."

Issue is the Password page move up a bit when keyboard open.  And this comment also happen issue https://github.com/Expensify/App/issues/9122#issuecomment-1164716952 but you mentioned on this commit, it should be not happen.

**Comment by rushatgabhane** [comment] 2022-06-24 19:29
@MTN718 I disagree with my [previous comment](https://github.com/Expensify/App/issues/9122#issuecomment-1158136155). Because I didn't explain the _why_

Anyway, in password page we have two additional items that are shown above the keyboard.

- `Fogot Password?`
- `Not user@example.com? Go back`

This is what makes it move up, and I think that's fine because the user should be able to see both these options and they shouldn't be hidden under a keyboard or button.

**Comment by rushatgabhane** [comment] 2022-06-24 19:51
Yeah, I don't think there's a problem that this issue is tryna solve.

@michaelhaxhiu / @marcaaron please close this issue unless you disagree with https://github.com/Expensify/App/issues/9122#issuecomment-1165870648

**Comment by MTN718** [comment] 2022-06-24 19:52
oh... i was working with your previous comment https://github.com/Expensify/App/issues/9122#issuecomment-1158136155

**Comment by rushatgabhane** [comment] 2022-06-24 19:54
@MTN718 I'm sorry about that. Please raise a feature request on slack if you think we can have a better UX

**Comment by MTN718** [comment] 2022-06-24 19:54
I still don't have slack access. Even sent request.

**Comment by rushatgabhane** [comment] 2022-06-24 19:59
@MTN718 what's your email? I'll ask for it to be added 

Please resend the email and make sure to send your upwork profile link

**Comment by MTN718** [comment] 2022-06-24 19:59
tenstar718@gmail.com

**Comment by MTN718** [comment] 2022-06-24 20:01
sent again.

**Comment by marcaaron** [comment] 2022-06-28 22:53
@rushatgabhane can you bring this to `#contributor-plus` so we can discuss? I'm still catching up here and unsure if we should close this or not.

**Closed** 2022-06-29 16:49 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Help Wanted
