### ISSUE TITLE
Web -Workspace - Unavailable workspace message appears when searching for the room created by admin until page refreshed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11230] opened 2022-09-23 00:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to account A in a regular browser
2. Login to account B in a incognito
3. Add B as a member in A's workspace
4. Create room in account A's workspace
5. Go to account B and search for room created in account A and observe the header

## Expected Result:
Workspace' s name should appear below room name

## Actual Result:
Unavailable workspace message appears until the page is refreshed
## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.5-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191875087-9ab6e8f6-c8f1-44eb-b1a8-77dce45e5454.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2022-09-23 23:56
Yep this is definitely happening. Very reproducible using the instructions in the issue, so I'm going to put the Demolition label on (this is my first time doing this so if I'm incorrect let me know!). Probably Weekly since it's not really preventing anything (you can still chat, it's only the text itself that's wrong).

**Comment by mvtglobally** [comment] 2022-10-03 20:21
Issue not reproducible during KI retests. (First week)

**Comment by neil-marcellini** [comment] 2022-10-03 21:44
Not reproducible on dev or prod so we can close this.
![image](https://user-images.githubusercontent.com/26260477/193691434-9ecf9251-98e3-46ec-bb87-1d31b105484e.png)

**Closed by neil-marcellini** 2022-10-03 21:44 UTC
Labels: Engineering, Weekly, Demolition, Overdue
