### ISSUE TITLE
[$500] Dev: Web - Console error occurs when clicking on a deleted or paid request money category URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28318] opened 2023-09-27 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the workspace expense room chat.
2. Navigate to "Request money" > "Manual"
3. Enter an amount and click on "Next"
4. Select a category and send the request.
5. Go to the sent request money detail page.
6. Click on the Category and copy the URL, then send it.
7. Delete the request money.
8. Click on the sent URL for the deleted request money.

## Expected Result:
No console error should appear when clicking on the URL for a deleted or paid request money category

## Actual Result:
A console error occurs when clicking on a deleted or paid request money category URL

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.74-2
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/41e99458-47c0-42c4-b245-c7bad6535ef2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695713591802959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d64fca889407111a</li>
        <li>Upwork Job ID: 1707045828508962816</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-09-27 15:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting error while editing category of deleted request.
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/components/OptionRow.js#L218
Here this.props.option.icons is undefined which causes the error.
### What changes do you think we should make in order to solve the problem?
We can have default value as 0 if Here this.props.option.icons is undefined
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Youhy** [comment] 2023-09-27 16:58
Proposal

Please re-state the problem that we are trying to solve in this issue.

Getting error while editing category of deleted request.

What is the root cause of that problem?

`this.textInput ` is a ref which is not initialised by the time when the function is called, or component already unmounted when the timeOut is executed

[App/src/components/OptionsSelector/BaseOptionsSelector.js](https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/components/OptionsSelector/BaseOptionsSelector.js#L71-L75)

Lines 71 to 75 in [cf9ad20](https://github.com/Expensify/App/commit/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44)
 if (this.props.isFocused && this.props.autoFocus && this.textInput) { 
     setTimeout(() => { 
         this.textInput.focus(); 
     }, CONST.ANIMATED_TRANSITION); 
 }

What changes do you think we should make in order to solve the problem?

Ref cycle should be initialised properly and should not rely on timeouts assuming that element will be accessible by the time timeout is fulfilled. The timeout execution depends on the amount of asynchronous code running in EventLoop already. 

What alternative solutions did you explore? (Optional)

Early return in EditRequestPage instead of returning FullPageNotFound at the end can help also, but this is a hack to bypass the issue instead of fixing it

**Comment by Youhy** [comment] 2023-09-27 17:35
Contributor details
Your Expensify account email: youhy@tut.by
Upwork Profile Link: https://www.upwork.com/freelancers/~01d867cf0154cbd9ba

**Comment by iwiznia** [comment] 2023-10-02 14:55
A couple questions:
1. How would the timeoutID work exactly?
2. Looking at the error seems that the variable is null and thus why it is failing, can't we just check that `this.textInput` is not null?
3. What happens after you click the link with the proposed fix? Does it not do anything at all? Because I think it should show the page not found page, but I don't think it will?

**Comment by iwiznia** [comment] 2023-10-02 17:26
Thanks for clarifying! And yes, I think having a link that does absolutely nothing is as broken as the current behavior from a user perspective.

**Comment by iwiznia** [comment] 2023-10-03 10:59
I think we should, @greg-schroeder what do you think?

**Comment by greg-schroeder** [comment] 2023-10-03 12:58
We should definitely not have a link that does nothing - that's just the same buggy user experienced repackaged. I think we should show the not found page for sure

**Comment by iwiznia** [comment] 2023-10-11 16:26
Sorry I missed this.
The `canEdit` is defined here https://github.com/Expensify/App/blob/6311f805e47beed35d798b3249769c8626fd511e/src/pages/EditRequestPage.js#L115 but that does not seem like what we want. It's totally possible that you can't edit the request but can see it, no?

**Comment by iwiznia** [comment] 2023-10-11 17:13
What I am saying is that I think there are 2 cases:
1. User can't edit the request (for example because it is settled already)
2. User can't access the request at all

And what I am saying is that I am not sure if in the first case we would want to show the not found page. 
Does that make sense? 
Maybe in case 1 we still want to return as we are doing now? I am not really sure.

**Comment by iwiznia** [comment] 2023-10-11 18:03
>We will still have a link that does nothing, and is that fine?

Hmmmm, so if you try to click on a request that was settled, we do nothing currently? Yeah, that sounds wrong too. Shouldn't we be opening the request page but have all controls disabled or something? Feels like we should already have covered this case... 😕

**Comment by iwiznia** [comment] 2023-10-12 17:55
Wait... what does `we dismiss the modal` mean? I initially read it as disable those fields, but I am not sure that's what you are saying

**Comment by iwiznia** [comment] 2023-10-12 18:16
Hmmmm I think users should be able to see the request, even if it is paid. Let's take this to slack...

**Comment by iwiznia** [comment] 2023-10-12 18:19
Posted here

**Comment by greg-schroeder** [comment] 2023-10-16 14:48
Seems the slack discussion ended with:

 "So if the user that submitted the request visits the edit page of a settled request, they would land (or get redirected) to the request page with all fields disabled"

**Comment by hungvu193** [comment] 2023-10-26 03:43
Looks like #29101  is now merged

**Comment by hungvu193** [comment] 2023-10-26 03:53
now merchant and description can be updated when a request is paid, is this expected?

**Comment by greg-schroeder** [comment] 2023-10-27 17:01
What do you think @fedirjh?

**Comment by hungvu193** [comment] 2023-10-28 01:35
When clicking edit date deeplink still nothing happens. Isn't that we're fixing in this issue?

**Comment by greg-schroeder** [comment] 2023-11-09 11:25
Removed hold, sorry for delay I missed this one

**Comment by greg-schroeder** [comment] 2023-11-13 09:32
I think we should just close this after reviewing more. Please comment if you disagree.

**Closed by greg-schroeder** 2023-11-13 09:32 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
