### ISSUE TITLE
[HOLD for payment 2023-06-29] [$2000] Web - Login - 2FA Input field not focused when proceed from magic code page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19711] opened 2023-05-27 00:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition - User has setup a 2FA to log into account

1. Open https://staging.new.expensify.com/

2. Input email for account from the precondition
3. Click "Continue"
4.Input magic code
5. Click "Continue"
6. Press digits in the keyboard
## Expected Result:
After user proceeds to authenticator code input page - the input field is focused and user can instantly type the code

## Actual Result:
After user proceeds to authenticator code input page - the input field is NOT focused and user has to additionally click on it to set focus

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/87cdda1c-1176-4240-94c4-8bdd6f1342ca

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145b8fd18db4b7dff</li>
        <li>Upwork Job ID: 1663365147022503936</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-05-27 09:31
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Web - Login - 2FA Input field not focused when proceed from magic code page

### What is the root cause of that problem?
We are rendering magic code and 2FA input conditionally via code block shown below.
https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L198-L242

We can see there is `autofocus` set at line 211 and 226 although it only focus during magic code input but not during 2FA inout.

So here problem that we are rendering same component conditionally within same parent, so here react will just pass the new props and keep the component loaded. So component did mount will not trigger when 2FA input appear. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
We have to pass unique key prop to `<MagicCodeInput>` component render at line 200 and 216 as shown code below. 
```javascript
{this.props.account.requiresTwoFactorAuth ? ( 
     <View style={[styles.mv3]}> 
         <MagicCodeInput 
             ...
            key="2FAInput"  // *** Add this prop ***
         /> 
     </View> 
 ) : ( 
     <View style={[styles.mv3]}> 
         <MagicCodeInput 
             ...
            key="magicCodeInput"   // *** Add this prop ***
         /> 
         <View style={[styles.changeExpensifyLoginLinkContainer]}> 
            ...
         </View> 
     </View> 
 )} 
```
So react will treat both component different and it will mount component from scratch instead of just passing the new props. This will solve the issue as shown in result video.

**Note:** At  present I set key for both component for sample purpose, we can decide key as suggested by engineering team.

### What alternative solutions did you explore? (Optional)
None

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/7823358/bb99ffba-a83b-4e74-8d61-a614349f6729

</details>

**Comment by kadiealexander** [comment] 2023-05-30 02:01
Reproduced on staging web!

https://github.com/Expensify/App/assets/59587260/28b8cc50-8d7a-4238-a674-7a794a674c63

**Comment by ShogunFire** [comment] 2023-05-30 23:16
Does @PrashantMangukiya 's proposal counts or are you waiting for proposals ? His proposal looks good... Can I copy paste it and get chosen ahah ?

**Comment by kadiealexander** [comment] 2023-05-31 00:04
Prashant's proposal counts, we're just waiting on @abdulrahuman5196 to review it. If you have your own proposal to share, by all means go ahead! :)

**Comment by abdulrahuman5196** [comment] 2023-06-01 20:17
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-06-01 20:46
@PrashantMangukiya The proposal is not working iOS safari? Could you kindly check on that?
But it works on web desktop, ios native

>So here problem that we are rendering same component conditionally within same parent, so here react will just pass the new props and keep the component loaded. So component did mount will not trigger when 2FA input appear.

I am not entirely sure on the rootcause. Why do we think this happens? Similarity in end DOM structure? Could you add more information to this and any react native reference possible.

**Comment by marcaaron** [comment] 2023-06-02 19:48
FWIW, auto focusing inputs is **_really_** messed up on iOS Safari and doesn't work properly for many cases see this really long issue thread 😄 

https://github.com/Expensify/App/issues/10414

**Comment by PrashantMangukiya** [comment] 2023-06-04 07:00
> @PrashantMangukiya The proposal is not working iOS safari? Could you kindly check on that?
But it works on web desktop, ios native

Yes autofocus for safari is messes up  as mentioned in comment above. https://github.com/Expensify/App/issues/19711#issuecomment-1574234046

> So here problem that we are rendering same component conditionally within same parent, so here react will just pass the new props and keep the component loaded. So component did mount will not trigger when 2FA input appear.
>
> > I am not entirely sure on the rootcause. Why do we think this happens? Similarity in end DOM structure? Could you add more information to this and any react native reference possible.

@abdulrahuman5196 here is the [react doc link](https://react.dev/learn/preserving-and-resetting-state#same-component-at-the-same-position-preserves-state) related to this. Thank you.

**Comment by abdulrahuman5196** [comment] 2023-06-04 20:15
@PrashantMangukiya Thanks for references. 

Tested in all platforms.

The solutions works for most platforms except iOS safari and native android.
It seems iOS safari is auto focus is messed up. So it should be fine for now.

But could you check why its not working on native android?(Not sure if its existing issue as well.)

**Comment by abdulrahuman5196** [comment] 2023-06-07 18:40
Seems we have 2 new proposals. Will review these tomorrow.

**Comment by kadiealexander** [comment] 2023-06-12 00:54
@abdulrahuman5196 could you please prioritise the above reviews so we can move this forward? Thanks!

**Comment by abdulrahuman5196** [comment] 2023-06-12 15:18
@WikusKriek  You solution is working on platforms as I did initial testing.
I am not sure if the root cause is correct

>But the blur function sets the focus index to undefined, so we have nothing to focus.

When we call focus it make the index 0 and focuses 

https://github.com/Expensify/App/blob/b77cf55dd6793cbbf76e985ea46b8825c2e923a4/src/components/MagicCodeInput.js#L110-L112

**Comment by abdulrahuman5196** [comment] 2023-06-12 15:21
@hoangzinh  Your solution here https://github.com/Expensify/App/issues/19711#issuecomment-1580791122 is working on platforms as far as I tested. But I don't think we should go for the fix until we know the correct root cause. 

Tagging the implementor @BeeMargarida to help us here. @BeeMargarida Could you kindly check and let us know on your thoughts

cc: @marcaaron

**Comment by abdulrahuman5196** [comment] 2023-06-12 15:22
@kadiealexander  I don't think we should increase the bounty for now, since the proposals are working but not sure on the root cause. So we should wait sometime to hear back on this questions.

**Comment by BeeMargarida** [comment] 2023-06-12 16:12
@abdulrahuman5196 I think the proposal works. Just to explain, this seems like optimizations on react side. Even though we have 2 different MagicCodeInput components, when switching from the validateCode for the 2FACode, the `input`of the component will still contain the value of the validateCode (even though we are now passing an empty `twoFactorAuthCode` code). 
I'm not sure what's more advanced, but this problem might also be related to this one - https://github.com/Expensify/App/issues/18244 - since it also deals with the focus logic.

**Comment by abdulrahuman5196** [comment] 2023-06-14 20:05
@WikusKriek 's updated proposal here https://github.com/Expensify/App/issues/19711#issuecomment-1580165315 works as mentioned before and makes more sense with the @BeeMargarida 's information here https://github.com/Expensify/App/issues/19711#issuecomment-1587646777. It would be better to clear all the stale data when switching from validateCode input to 2FA input.

🎀👀🎀
C+ Reviewed
cc: @kadiealexander 


Since internal engineers are only assigned after C+ review, @BeeMargarida  if you are available could you kindly check on this issue and confirm the proposal and approve as internal engineer, since you already have background on it. (Kindly do a double check on my approval)

@kadiealexander If @BeeMargarida  becomes unavailable kindly assign an internal engineer as per the new process.

**Comment by kadiealexander** [comment] 2023-06-15 00:46
@luacmartins we've landed on a proposal [here](https://github.com/Expensify/App/issues/19711#issuecomment-1591899271), please check it over and assign the contributor if you agree!

**Comment by BeeMargarida** [comment] 2023-06-15 08:51
@abdulrahuman5196 The proposal looks good to me 👍
The only suggestion I make is that instead of using the `clear` method, which might be confusing (the concern raised by @hoangzinh), is to create another one called `resetFocus` or something, that includes the `setInput('')`. This is only a suggestion, feel free to discard it if you don't agree.

**Comment by abdulrahuman5196** [comment] 2023-06-15 09:37
I agree on the concerns and suggestions by @BeeMargarida and @hoangzinh here. I think the suggestion of a new method called `resetFocus` or similar from @BeeMargarida  make sense and we should also need to make sure this new method is dry compared to `focus` and `clear`. But anyways these are PR level suggestion and the contributor would have to address these concerns in the PR.
cc: @WikusKriek

**Comment by kadiealexander** [comment] 2023-06-19 05:23
Hey team! I'm just adding a note that I'll be OOO until June 26th. I don't think any bug0 team actions will come up this week but if you need a bug0 teammate while I'm gone, please reapply the label! Thanks.

**Comment by abdulrahuman5196** [comment] 2023-06-20 15:49
Melvin is wrong here. PR was merged within 3 working days totally, almost 6 hours before 3 days mark (2 days being weekend out of the 5 days).

**Comment by abdulrahuman5196** [comment] 2023-06-22 18:02
> The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression. But was present from original implementation.

>Determine if we should create a regression test for this bug.

yes

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Go to login page and enter login information where the account already has Two factor authentication enabled
2) Enter magic code and continue
3) Two factor code input should be focused and keyboards should be opened in-case on native apps

**Comment by abdulrahuman5196** [comment] 2023-06-29 01:57
@kadiealexander Thank you. Accepted the upwork job offer.

**Comment by kadiealexander** [comment] 2023-06-30 04:03
Everyone is paid (plus a bonus as per https://github.com/Expensify/App/issues/19711#issuecomment-1599058476). Thanks for the speedy work team!

**Closed by kadiealexander** 2023-06-30 04:03 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
