### ISSUE TITLE
[$500] Web - Mini context menu keeps visible after opening Search RHN by Ctrl/CMD + K

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27549] opened 2023-09-15 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open report page with multiple chat messages.
2. Move the mouse pointer over a message and mini context menu will be shown.
3. Open Emoji Picker by clicking 'Add reaction' button in mini context menu.
4. Press Ctrl/CMD + K to open Search RHN.
5. Close Search RHN and move the mouse pointer over messages.

## Expected Result:
Mini context menu should be only shown on hovered message.

## Actual Result:
Previously opened mini context menu keeps visible regardless of hover state.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2946efaf-6267-4f4c-bee7-78238be98e0e

https://github.com/Expensify/App/assets/93399543/14cd712a-bdb2-4ab5-8e4f-c4f119e9110f

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694699303165169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c0c625b3a053d7e</li>
        <li>Upwork Job ID: 1702737549085298688</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-09-15 23:23
Possibly a duplicate of https://github.com/Expensify/App/issues/27244

**Comment by jliexpensify** [comment] 2023-09-16 00:45
Yep, I think you're right @paultsimura - @mollfpr is also the C+ assigned, so if it isn't a dupe, let me know and I'll re-open this.

**Closed by jliexpensify** 2023-09-16 00:45 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by paultsimura** [comment] 2023-09-16 13:09
I was wrong, sorry. While working on the other issue, I found out that this one is a completely different root cause.
@jliexpensify @mollfpr 

This issue is actually a regression from https://github.com/Expensify/App/issues/15276

**Comment by paultsimura** [comment] 2023-09-16 13:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When opening the search page using cmd+k with the emoji picker open, the mini context menu stays visible.

### What is the root cause of that problem?
The emoji picker context menu action has a special function that manually closes the mini context menu on the picker being closed:

https://github.com/Expensify/App/blob/4e75989f28bd7a90f7ee9cc564ff0771d35dd2c8/src/pages/home/report/ContextMenu/ContextMenuActions.js#L51-L60

However, when navigating, this function is being neglected:

https://github.com/Expensify/App/blob/a7c53edc968e3998e50a0566b8a7b84097569dff/src/components/EmojiPicker/EmojiPicker.js#L72-L78

### What changes do you think we should make in order to solve the problem?
My suggestion is to remove the `if (isNavigating)` logic here:

```diff
    const hideEmojiPicker = (isNavigating) => {
-        if (isNavigating) {
-            onModalHide.current = () => {};
-        }
        emojiPopoverAnchor.current = null;
        setIsEmojiPickerVisible(false);
    };
```

In https://github.com/Expensify/App/issues/15276, this change was introduced to prevent the Search Input from losing focus on opening. Seems like since then the focusing logic has changed, and if we remove the `if (isNavigating)` part, the focus still works.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-09-16 13:19
@aimane-chnaif just posted [the proposal](https://github.com/Expensify/App/issues/27549#issuecomment-1722228427) with the details.
