### ISSUE TITLE
[HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] [Theme Switching] 🐛 Wallet - Open in app banner is dark themed on Wallet page even if the app is in light mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33122] opened 2023-12-14 21:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have Expensify app installed and light mode must be enabled
1. Go to Settings > Wallet

## Expected Result:
Open in app banner should appear in light mode

## Actual Result:
Open in app banner is in dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6313539_1702582788247!IMG_E2019](https://github.com/Expensify/App/assets/78819774/d68d5b93-c9c7-4145-8205-19dedf89f28a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2023-12-14 23:14
This was just a minor mistake – dark theme color being using in `light.ts`: https://github.com/Expensify/App/blob/fd71747303cd8df7fc1dfc9b010752e5635b2684/src/styles/theme/themes/light.ts#L115-L116

**Comment by grgia** [comment] 2023-12-14 23:33
Gonna fix in https://github.com/Expensify/App/pull/33100 since same root cause

**Comment by Julesssss** [comment] 2023-12-15 09:16
CP'd a fix

**Comment by Julesssss** [comment] 2023-12-15 09:43
https://github.com/Expensify/App/pull/33100#issuecomment-1857567500

**Comment by roryabraham** [comment] 2023-12-29 21:58
Solution for this is on prod, and the C+ payment is being handled in https://github.com/Expensify/App/issues/33091, so I think we're good to close this out

**Closed by roryabraham** 2023-12-29 21:58 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
