### ISSUE TITLE
[$500] Android - Workspaces - Can open `Connect bank account' and '?' (Get assistance) at the same time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34455] opened 2024-01-12 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Workspaces -> Cards
4. Click `Connect bank account' and '?' (Get assistance) simultaneously

## Expected Result:
It is impossible to open two tabs at the same time

## Actual Result:
Two tabs open at the same time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1863c206-dbb4-46ab-ba6f-873165fecb26

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122789af76f867cba</li>
        <li>Upwork Job ID: 1745859822794940416</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2024-01-12 17:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can open `Connect bank account' and '?' (Get assistance) at the same time

### What is the root cause of that problem?

we are not using the single execution context in the connect bank account button here: 

https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/components/ConnectBankAccountButton.js#L35-L50
 
### What changes do you think we should make in order to solve the problem?

we need to use the single execution in the connect bank account page or in button component: 
```
    const {singleExecution} = useSingleExecution();
```


```js
            onPress={() => singleExecution(ReimbursementAccount.navigateToBankAccountRoute(props.policyID, activeRoute))}
```

**Comment by NicMendonca** [comment] 2024-01-16 13:40
> Click `Connect bank account' and '?' (Get assistance) simultaneously

This doesn't feel like something a user will do. They will do these separately. Going to close this for now.

**Closed by NicMendonca** 2024-01-16 13:40 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
