### ISSUE TITLE
[$500] Distance Split - Distance in split distance request shows "Merchant" instead of "Distance"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33698] opened 2023-12-28 11:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to workspace chat > + > Split bill.
2. Go to Distance.
3. Create split distance request.
4. Click on the split preview.
Note that distance request shows Merchant for distance instead of Distance.

## Expected Result:
The split distance details view shows "Distance" label for distance.

## Actual Result:
The split distance details view shows "Merchant" for distance instead of "Distance".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3639edf8-ce1d-4e10-a50a-dbb8bee399ee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e39ad642057e5fd2</li>
        <li>Upwork Job ID: 1740332042499534848</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by getusha** [comment] 2024-01-02 17:59
Reviewing.

**Comment by getusha** [comment] 2024-01-04 16:33
@abzokhattab could you share implementation details or the branch to test your proposal?

**Comment by shubham1206agra** [comment] 2024-01-08 16:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Distance Split - Distance in split distance request shows "Merchant" instead of "Distance"

### What is the root cause of that problem?

In

https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/iou/SplitBillDetailsPage.js#L125-L153

We don't use `isDistanceRequest` prop. Due to this, default value of `false` is used in `isDistanceRequest` prop, which is used in determining the correct title.

### What changes do you think we should make in order to solve the problem?

Add `isDistanceRequest` in above.

The correct value can be derived using

```js
const isDistanceRequest = TransactionUtils.isDistanceRequest(props.transaction);
```

**Comment by getusha** [comment] 2024-01-08 19:11
@shubham1206agra is there any plan to fix this on the backend?

**Comment by shubham1206agra** [comment] 2024-01-08 19:13
Most probably yes. I will update here once I get the update.

**Comment by getusha** [comment] 2024-01-11 16:50
Not overdue, waiting for the backend fix.

**Comment by jliexpensify** [comment] 2024-01-17 00:12
Hi @slafortune  just coming from this [thread](https://expensify.slack.com/archives/C05DWUDHVK7/p1705329555812999?thread_ts=1703805792.841859&cid=C05DWUDHVK7) - Neil has suggested implementing P2P distance requests are implemented first before working on these types of issues. Did you want to close this? cc @shubham1206agra

**Closed** 2024-01-17 20:57 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
