### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Web - App does not remove dot from amount in split bill after first try

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22361] opened 2023-07-06 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on + and click on split bill
3. Enter any amount and write decimal dot (eg. 1234.)
4. Click on next and select any users
5. Click on back twice and observe that normally app removes the dot from the end of amount
6. Again change the amount or keep the amount the same and write dot in the end.
7. Again select any users or keep the already selected user and click on next
8. Go back twice and observe that app no longer removes dot from the amount

## Expected Result:
 App should remove the dot from the amount if user has not inserted any digit after it.

## Actual Result:
App does not removes the dot from the amount when we edit the amount second time even if no digit has been inserted after it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f220ef96-2558-4285-84cc-fef1a247ff95

https://github.com/Expensify/App/assets/93399543/57570bcb-223d-42b6-904c-b777d728fc87

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688631197920759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01516b47bd364f3b33</li>
        <li>Upwork Job ID: 1677044876093419520</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by manjesh-yadav** [comment] 2023-07-07 06:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not remove dot from amount in split bill after first try
### What is the root cause of that problem?

https://github.com/Expensify/App/blob/d98a02a5d227c4503e3e3d05c7a3029431d51145/src/pages/iou/steps/MoneyRequestAmountPage.js#L150-L159


1. We parse the amount to the number and convert it to a string 
2. when we add a dot again, the old amount and the new amount is the same after parsing, and our condition will become false the state is not updated and we can see the dot is still there 


### What changes do you think we should make in order to solve the problem?
When we navigate to `navigateToNextPage ` we should parse it again to convert into string and set the right cursor position 


```js
const amountAsString = Number(this.state.amount).toString()
this.setState({
                amount: amountAsString,
                selection: {
                    start: amountAsString.length,
                    end: amountAsString.length,
                },
            });```

**Comment by eVoloshchak** [comment] 2023-07-10 12:33
Reviewing proposals today

**Comment by eVoloshchak** [comment] 2023-07-10 22:50
That is an interesting bug🧐
The proposals are quite similar, I think we should proceed with @kushu7's [proposal](https://github.com/Expensify/App/issues/22361#issuecomment-1624213133) since that was the first proposal to identify the root cause and propose a fix

**Comment by puneetlath** [comment] 2023-07-27 23:23
@eVoloshchak friendly reminder about the checklist ahead of next week.

**Comment by eVoloshchak** [comment] 2023-08-02 15:51
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/17964
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/17964/files#r1282100858
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a simple visual bug, I don't think an additional discussion is needed
- Determine if we should create a regression test for this bug.
**Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No**
The bug has almost zero impact, doesn't affect the user experience at all, I think a regression test isn't needed here

**Comment by puneetlath** [comment] 2023-08-02 21:52
Issue reporter:  @dhanashree-sawant $250 (paid via Upwork)
Contributor: @kushu7 $1000 (paid via Upwork)
Contributor+: @eVoloshchak (to be NewDot)

@eVoloshchak can you please request payment on NewDot and then comment here once you have? Thanks!

**Comment by puneetlath** [comment] 2023-08-02 23:36
Ah yes, right you are. I'll amend.

**Comment by eVoloshchak** [comment] 2023-08-03 16:27
@puneetlath, thanks, requested the payment via NewDot🎉

**Comment by JmillsExpensify** [comment] 2023-08-03 22:10
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by puneetlath** [comment] 2023-08-03 22:11
Great, closing out. Thanks everyone!

**Closed by puneetlath** 2023-08-03 22:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
