### ISSUE TITLE
[$250] Android - The app does not display the pending state

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44641] opened 2024-06-28 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4682953&group_by=cases:section_id&group_id=309132&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+pendingreceipt@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Login with [applausetester+pendingreceipt@applause.expensifail.com](mailto:applausetester+pendingreceipt@applause.expensifail.com)
2. Navigate to Account settings > Wallet
3. Make sure that under Assigned Cards the "Discover" card is assigned under the applause.expensifail domain
Steps:
1. Navigate to the workspace chat
2. Smartscan a receipt that will scan successfully to the workspace

## Expected Result:
The app should display the pending state

## Actual Result:
The app does not display the pending state

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![image__2_](https://github.com/Expensify/App/assets/78819774/60e5c2e4-4ece-4b6e-94c0-9be3cd3868d2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dcfd798465d34857</li>
        <li>Upwork Job ID: 1808829326680192305</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment] 2024-06-28 18:56
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-28 18:56
We think that this bug might be related to #vip-vsp

**Comment by garrettmknight** [comment] 2024-07-01 15:38
@kevinksullivan / @grgia should this be done already or is it expected with where we are in the feeds project?

**Comment by garrettmknight** [comment] 2024-07-03 19:29
Asking in [slack](https://expensify.slack.com/archives/C036QM0SLJK/p1720034936666479?thread_ts=1719848335.959829&cid=C036QM0SLJK)

**Comment by garrettmknight** [comment] 2024-07-04 11:44
Looks like it's part of https://github.com/Expensify/Expensify/issues/372206

**Comment by ahmedGaber93** [comment] 2024-07-05 02:01
Waiting on proposals

**Comment by ahmedGaber93** [comment] 2024-07-08 08:52
Waiting on proposals

**Comment by ahmedGaber93** [comment] 2024-07-10 08:28
Waiting on proposals

**Comment by mvtglobally** [comment] 2024-07-11 03:51
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2024-07-12 16:51
Closing since it was solved here: https://github.com/Expensify/Expensify/issues/372206

**Closed by garrettmknight** 2024-07-12 16:51 UTC
Labels: External, Daily, Help Wanted, Bug
