### ISSUE TITLE
Web - Briefly displaying changed task title and description when user is no longer the assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21909] opened 2023-06-29 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Note: Anyone should be able to reassign a task to someone else.

1. Login with userA account 
2. Open userB chat
3. Go to the “Assign task”
4. Enter title and select userB as assignee
5. Click on “Confirm task”
6. Open other browser and login with userB account
7. Open userA chat  Click on task message 
8. Click on assignee and select someone else  
9. Change the title and description after changing the assignee

## Expected Result:
If the assignee is changed, the title and description should be disabled or should not change for a second

## Actual Result:
Changed task title and description briefly displayed if the user is no longer the assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3e218a42-a2a1-49e3-b764-9eddd94de7c4

https://github.com/Expensify/App/assets/93399543/860f0bcd-4787-415b-b502-ece7e400885d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687988408465889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ad74b5baa4e1c23</li>
        <li>Upwork Job ID: 1675630627536535552</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-30 01:16
It sounds like there's a root cause with https://github.com/Expensify/App/issues/21626 (not an engineer though). Asking for @allroundexperts to review as he is assigned as C+

**Comment by jliexpensify** [comment] 2023-07-01 07:08
Agree - asking here for confirmation: https://expensify.slack.com/archives/C01SKUP7QR0/p1688195284781699

**Comment by jliexpensify** [comment] 2023-07-02 22:19
@allroundexperts thanks for your patience! Discussed it and David B. weighed in: we should allow anyone to re-assign a task to another person.

This makes the task feature more fluid, and replicates essentially what you can do in GH.

With that in mind, @StevenKKC do you want to take a crack at an updated proposal?

**Comment by jliexpensify** [comment] 2023-07-04 04:20
I'll be OOO for a few days, but we're still awaiting proposals

**Comment by StevenKKC** [comment] 2023-07-04 05:32
@jliexpensify If we should allow anyone to re-assign a task to another person, this issue should be fixed by BE.

**Comment by StevenKKC** [comment] 2023-07-04 05:58
@allroundexperts Sorry, I have mislead the comment.

**Comment by StevenKKC** [comment] 2023-07-04 06:16
@allroundexperts @jliexpensify Task creator and assignee can re-assign a task to another person, and others is not allowed, is this right?

**Comment by jliexpensify** [comment] 2023-07-04 06:35
@allroundexperts at the moment, we're actually discussing this [behaviour](https://expensify.slack.com/archives/C01SKUP7QR0/p1688195284781699). The current desire from David B is that Tasks should work like GH: if a user is assigned a task, anyone else should be able to reassign it.

cc @thienlnam as you've been chatting to David B about this and might have a consensus.

**Comment by jliexpensify** [comment] 2023-07-04 06:41
Ah, sorry - to clarify: there might be permissions like that in the Expensify/App repo, but internally, we use another repo that allows anyone to assign/re-assign/unassign GH's in our Expensify team (e.g. I can unassign one of my colleagues from a GH they are assigned to and reassign someone else). That's what I was referring to!

**Comment by thienlnam** [comment] 2023-07-06 19:46
Making the BE changes for this new access change in https://github.com/Expensify/Expensify/issues/296932

**Comment by thienlnam** [comment] 2023-07-12 18:01
Still need to make the BE changes

**Comment by jliexpensify** [comment] 2023-07-17 00:36
Oh hold.

**Comment by thienlnam** [comment] 2023-07-19 20:31
Moving this to same priority as the internal issue

**Comment by jliexpensify** [comment] 2023-07-31 01:51
On Hold

**Comment by thienlnam** [comment] 2023-08-09 21:33
Held issue is done - can we still see if this is a problem?

**Comment by jliexpensify** [comment] 2023-08-10 01:06
@thienlnam tested this one with Kadie - here's what we did:

1. I created a new task and assigned to Kadie. Description: `Please edit the description and task name and reassign back to me`
2. Kadie was able to edit the description, task name and assign it back to me suuccessfully.

Are there any other testing steps I should do? Everything seemed pretty stable, and makes the Task feature very fluid!

**Comment by jliexpensify** [comment] 2023-08-10 01:07
Payment summary:

- Bug Reporter: @ayazhussain79 $250

Creating upworks job shortly

**Comment by jliexpensify** [comment] 2023-08-10 07:06
Since I can't seem to repro the issue (tested again on my side), going to close this! We are all sorted with payments.

**Closed by jliexpensify** 2023-08-10 07:06 UTC
Labels: Weekly, Internal, Bug

**Comment by thienlnam** [comment] 2023-08-10 17:50
Sweet, all sounds good!
