### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Request money - Inappropriate Error message show up when going back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28086] opened 2023-09-24 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Click on FAB > Request money
2. Click 'Next' without entering a valid number
3. Notice an error message show up
4. Enter a Valid number and Click on next
5. Click the back button on the manual page to go back to the Request Money page
6. Erase the valid amount entered. Notice an error message shows up

## Expected Result:
The error should only show up after the user taps the button again

## Actual Result:
An error message shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/12554d67-c8fb-4bf7-b9cb-50dcb25c87ec

https://github.com/Expensify/App/assets/93399543/b2859421-9799-471c-8db4-62b9d3f594ec

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695514629151899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136329907e03b716d</li>
        <li>Upwork Job ID: 1706132442238746624</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26976243</li>
<li>akinwale | Contributor | 26976246</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-24 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the first step of a manual money request, an invalid amount error message is being displayed when editing the amount after submitting an invalid amount for the first time.

### What is the root cause of that problem?
The new amount input is being validated upon every change to the amount input.

### What changes do you think we should make in order to solve the problem?
Remove the call to setFormError upon every amount change. We can move this to the `onBlur` handler of the input or when the Next button is clicked.

### What alternative solutions did you explore? (Optional)
None.

**Comment by situchan** [comment] 2023-09-24 16:41
While this is expected behavior, it doesn't look good to make currency and amount input **dance** whenever error appears/disappears. We can fix position no matter error shows or not so add absolute style to error view.
Anyway, not a deploy blocker.


https://github.com/Expensify/App/assets/108292595/efeb31ea-2a46-4ed0-a9a9-5ed5429814af

**Comment by situchan** [comment] 2023-09-24 16:53
yes I know the root cause but jumping even on web which has enough height

**Comment by Julesssss** [comment] 2023-09-25 01:41
While the button changes made [here](https://github.com/Expensify/App/pull/23712) valid:

> Button's should be clickable even though the necessary steps are not fulfilled and Fix error options should be shown up instead to keep the app consistency

The two cases are quite different and we should still make a change here. In the case of 2FA setup, the user only needs to copy the codes once -- it makes sense in that specific case to not require the user to copy the codes every time they go back and forth in the tabs.

_____________

The error should not show up immediately upon the user deleting the amount. Only once the button is pressed should the error display. The UX should not be different based on whether the user has just opened the tab OR has navigated back to the amount page.

**Comment by Julesssss** [comment] 2023-09-25 01:53
Updated the description. Also, this is definitely not a blocker, updating the checklist.

**Comment by Julesssss** [comment] 2023-09-26 03:04
Ah, thanks for sharing. I took this question [directly to the designers](https://expensify.slack.com/archives/C03TME82F/p1695697384456199) to clear this up and unblock us. Will report back

**Comment by Julesssss** [comment] 2023-09-26 04:31
Confirmed that we should reset the state. But if I misunderstood your point please let me know!

<img width="678" alt="Screenshot 2023-09-26 at 12 29 51" src="https://github.com/Expensify/App/assets/10736861/9d26e32c-82f8-483f-bd8f-4bb409faf32c">

**Comment by Julesssss** [comment] 2023-09-26 05:31
What exactly do you mean by 'clear it'? I think the error should appear/clear only after the button is pressed.

**Comment by Julesssss** [comment] 2023-09-26 05:59
> Actually now, after the first time the error appears, anytime the value is invalid the error will appear.

That's exactly the case I think we need to fix in this issue.

**Comment by akinwale** [comment] 2023-09-26 06:30
> > Actually now, after the first time the error appears, anytime the value is invalid the error will appear.
> 
> That's exactly the case I think we need to fix in this issue.

My proposal already tackles this. Basically, the idea is the error will only be displayed on if the button is clicked when the amount is invalid. As soon as the user starts modifying the amount again, the error is cleared, and will not be displayed until the button is clicked again with an empty amount field.

**Comment by Julesssss** [comment] 2023-09-28 12:14
I don't think this case should be treated as a regression personally

**Comment by akinwale** [comment] 2023-10-02 12:10
@fedirjh My [PR](https://github.com/Expensify/App/pull/28607) is ready for review. Thanks.

**Comment by lschurr** [comment] 2023-10-13 15:50
Payment are made to @akinwale and @fedirjh. I invited you to the job as well @daveSeife - could you accept and apply?

**Comment by akinwale** [comment] 2023-10-13 15:53
> Payments are made to @akinwale and @fedirjh. I invited you to the job as well @daveSeife - could you accept and apply?

Received. Thanks!

**Comment by lschurr** [comment] 2023-10-13 23:30
All payments made. Closing.

**Closed by lschurr** 2023-10-13 23:30 UTC
Labels: External, Engineering, Daily, Awaiting Payment
