### ISSUE TITLE
[HOLD for payment 2024-03-20] [Wave8] [Simplified Collect] [Workflows] Create Payment page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#37197] opened 2024-02-26 08:08 UTC
We've recently merged the [main workflows page](https://github.com/Expensify/App/pull/36345).

The task here is to create the Payment page present under the main worfklows page.

It will appear when we click on the `>` icon under the `Connect bank account` menu item:
![image](https://github.com/Expensify/App/assets/21549771/0a05cd46-ef31-479e-9f4a-cd703df08ad8)

**Expected mockups below**

_No VBBA flow_
<img width="670" alt="image" src="https://github.com/Expensify/App/assets/21549771/4f03a6e0-2aaf-42b5-b47d-c84286d7b184">

_VBBA flow_
<img width="670" alt="image" src="https://github.com/Expensify/App/assets/21549771/541284fc-d0f2-49ed-b858-e43989375613">

Technical details can be found [here](https://docs.google.com/document/d/1T--VcAaCm-8aq5oEO78_vVXxBpXY1gq7NiJrboGZNcs/edit#bookmark=id.26kmycv21oxr).

**Comment by luacmartins** [comment] 2024-02-27 03:11
@ishpaul777 would you be able to work on the implementation for this issue since you have access to the design doc?

**Comment by lakchote** [comment] 2024-02-27 07:36
> > would you be able to work on the implementation for this issue since you have access to the design doc
> 
> Sure 😃 i'd love to work on it

Perfect! Thank you. Assigning it to you

**Comment by luacmartins** [comment] 2024-02-28 17:35
@ishpaul777 the reimbursementAccount key should have [these details](https://github.com/Expensify/App/blob/59f8f3d4889afe26c3f73c2e8e3df1ced50e11dd/src/types/onyx/ReimbursementAccount.ts#L11-L38), I think we can use that to build the bank account name as shown in the image

**Comment by luacmartins** [comment] 2024-02-28 17:45
This is the object I see when I have a bank account added. Maybe your account doesn't have a bank account properly set up:

![Screenshot 2024-02-28 at 10 44 49 AM](https://github.com/Expensify/App/assets/22219519/25e46008-b7cc-425e-bb32-9ab90b912aa5)

**Comment by luacmartins** [comment] 2024-02-28 20:40
>we’ll check for plaidData Onyx key details
this seems wrong since that key is temporary only when we're in the process of connecting with Plaid.

That should navigate to `ROUTES.BANK_ACCOUNT_WITH_STEP_TO_OPEN`, which would show the EnableBankAccount page
![Screenshot 2024-02-28 at 1 40 01 PM](https://github.com/Expensify/App/assets/22219519/dbfbb3b7-317c-4eb0-84eb-2c78d895b939)

**Comment by luacmartins** [comment] 2024-03-01 02:21
@ishpaul777 how's it going with this issue? Do you have a branch or draft PR up yet?

**Comment by trjExpensify** [comment] 2024-03-04 09:02
Draft PR is up, @ishpaul777 what's your ETA on marking it ready for review?

**Comment by trjExpensify** [comment] 2024-03-04 10:03
Thanks for the update, @ishpaul777. @lakchote, can you help here?

**Comment by lakchote** [comment] 2024-03-04 10:13
> > what's your ETA on marking it ready for review?
> 
> I have completed the most part, a few blocker i have:
> 
> 1. The `SetWorkspacePayer` is throwing a 404 error from server, so for now i tried `setWorkspaceReimbursement` command to set workspace admin as reimburserEmail which seems to working fine but i'll change it once that command is working
> 
> 2. There is no command for changing `policy.reimbursementChoice` to toggle on/off the option, and i dont find a way to have the VBA owner set as default workspace payer.
> 

For 1., it should be the command that exists is `SetWorkspaceReimbursement` and not `SetWorkspacePayer`.
If we want to use the latter, we should change the alias name in Web-E. cc @luacmartins 

For 2.,  to toggle on/off the option, you need to call `Policy_setReimbursementFromChoice ` with parameters `policyID`, and `reimbursementChoice` (set it as `reimburseManual `)

To have the VBBA owner set as default workspace payer, call `SetWorkspaceReimbursement` with the VBBA owner's email

For 3., you can maybe add a param to `ReimbursementAccountPage` so that on redirect from the Workflows screen, it knows it's from Workflows and as such doesn't clear reimbursement data

**Comment by lakchote** [comment] 2024-03-04 10:53
> > To have the VBBA owner set as default workspace payer, call SetWorkspaceReimbursement with the VBBA owner's email
> 
> Actually achData dont dont have a VBA owner email property :( [#37197 (comment)](https://github.com/Expensify/App/issues/37197#issuecomment-1969518335), so we dont have a way to know the owner email

I'm going to look into it. I'll report back

**Comment by lakchote** [comment] 2024-03-04 11:44
> @lakchote is the command Policy_setReimbursementFromChoice with Policy_ post fix, asking because i dont see this pattern followed anywhere ?

It's `Policy_setReimbursementFromChoice` with `setReimbursementFromChoice` in lowercase. 

It's an old command that's why it didn't follow the new and proper convention naming.

We can create an alias for it later. 

Could you please use it and report back if you can make it work?

**Comment by lakchote** [comment] 2024-03-04 11:54
> Its working 👍, one more thing for clarity, when option is `reimburseManual` option is on and when its off is it `reimburseYes` or `reimburseNo`

When it's on it's `reimburseYes`, when it's off it's`reimburseManual`

**Comment by lakchote** [comment] 2024-03-04 12:34
@ishpaul777 I've found an ISO way of getting the reimburser email if it's set or default to the owner of the VBBA account.

Will put up a PR for @luacmartins to review.

**Comment by lakchote** [comment] 2024-03-04 13:19
> @ishpaul777 I've found an ISO way of getting the reimburser email if it's set or default to the owner of the VBBA account.
> 
> Will put up a PR for @luacmartins to review.

PR ready for review too @luacmartins 

Here's a quick link to the PRs:
[Alias for API command ](https://github.com/Expensify/Web-Expensify/pull/41115)
[Reimburser email for VBBA](https://github.com/Expensify/Web-Expensify/pull/41116)

**Comment by luacmartins** [comment] 2024-03-04 15:37
Update:
- Alias PR is merged. You can keep using `Policy_setReimbursementFromChoice` for testing for now until the new command `SetReimbursementFromChoice` is deployed.
- For the reimburser email from VBBA, we should be using the new `reimbursementAccount<policyID>` key, with the policyID appended to it. It seems like we don't load this information when opening the Workflows page, so we need a command to do that @lakchote.

**Comment by luacmartins** [comment] 2024-03-04 15:40
@ishpaul777 we'll have to create an `OpenPolicyWorkflowsPage` API command that should be called when the user opens the Workflows page to load this data. I wouldn't block your PR on it though

**Comment by jjcoffee** [comment] 2024-03-04 16:32
@trjExpensify Could you assign me here as I'll be reviewing the PR as C+? Thanks! :pray:

**Comment by luacmartins** [comment] 2024-03-04 16:36
Done

**Comment by lakchote** [comment] 2024-03-06 08:39
> @ishpaul777 we'll have to create an `OpenPolicyWorkflowsPage` API command that should be called when the user opens the Workflows page to load this data. I wouldn't block your PR on it though

PR should be merged today

**Comment by trjExpensify** [comment] 2024-03-20 19:09
Alright, alright... 

- $500 to @jjcoffee for the C+ review
- $500 to @ishpaul777 for the fix

We'll take care of the regression tests for the simplified collect project. :) 

Let me know if that's correct and I'll get these paid out.

**Comment by jjcoffee** [comment] 2024-03-21 09:46
@trjExpensify LGTM!

**Comment by trjExpensify** [comment] 2024-03-21 17:53
Perfect. Offers sent!

**Comment by jjcoffee** [comment] 2024-03-22 10:10
@trjExpensify Accepted, thanks!

**Comment by trjExpensify** [comment] 2024-03-22 11:29
@jjcoffee paid you.

**Comment by trjExpensify** [comment] 2024-03-25 12:01
@ishpaul777 we're still waiting on you to accept [the offer](https://www.upwork.com/nx/wm/offer/101509184).

**Comment by trjExpensify** [comment] 2024-03-25 22:14
Paid! :)

**Closed by trjExpensify** 2024-03-25 22:14 UTC
Labels: Daily, NewFeature, Awaiting Payment
