### ISSUE TITLE
[$500] Sign In - Data - Account and app data is not fully loaded after attempt to Sign In with suspended account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29013] opened 2023-10-06 16:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Tap in email label
3. Write a suspended account email
4. Tap "Continue" button
5. Tap on "Back"
6. Replace the email with a valid (non-suspended) account email
7. Tap on "Continue" button
8. Fill the magic code label
9. Observe the listed chat in LHN
10. Tap on FAB
11. Tap on Request Money
12. Select Manual tab
13. Tap on currency
14. Observe listed currencies

Suspended account: [applausetester+omc1@applause.expensifail.com](mailto:applausetester+omc1@applause.expensifail.com)
Tested account: [applausetester+omw1@applause.expensifail.com](mailto:applausetester+omw1@applause.expensifail.com)

## Expected Result:
User should be signed in and all account and app data should be loaded

## Actual Result:
Step 9:
Only several conversations listed in LHN (the issue occurs occasionally)
Step 13:
Unable to change currencies because all currencies is missing on search page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d1a99e9d-9d12-45f2-9c5c-df8386ab4549

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01240579ed69bf1c9d</li>
        <li>Upwork Job ID: 1711711997061881856</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27463078</li>
</ul></li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-10-10 11:55
^ just added external label

**Comment by NicMendonca** [comment] 2023-10-12 19:28
waiting for proposals

**Comment by mollfpr** [comment] 2023-10-16 10:11
Not overdue, still waiting for proposals.

**Comment by MrMuzyk** [comment] 2023-10-17 14:12
@lanitochka17 

The account ([applausetester+omc1@applause.expensifail.com](mailto:applausetester+omc1@applause.expensifail.com)) doesn't have emails suspended anymore. Do you happen to have other account that has emails suspended? I'm not able to reproduce it anymore

**Comment by mollfpr** [comment] 2023-10-17 16:02
@NicMendonca Let's assign this issue to @MrMuzyk, so there's no proposal submitted.

**Comment by lanitochka17** [comment] 2023-10-18 00:52
Hello We don't have any blocked accounts yet

**Comment by MrMuzyk** [comment] 2023-10-18 11:34
@lanitochka17 
That's too bad :( I think I've found the root cause of the issue but in order to confirm that together with the fix I need an account to test this. I've asked for help in obtaining account with suspended mailing but no luck so far.

**Comment by mollfpr** [comment] 2023-10-20 15:35
@MrMuzyk I found a suspended email you can try dusjosjkposakpa@gmail.com

**Comment by MrMuzyk** [comment] 2023-10-24 11:41
@mollfpr 
Thanks, I've tried it and it works so I'm working on proposal now

**Comment by MrMuzyk** [comment] 2023-10-25 10:16
Hey, I’ve started work on some wave6 features that are high-priority and someone else from Callstack will take over this issue

**Comment by NicMendonca** [comment] 2023-10-26 20:54
@MrMuzyk cool! Do we know who that person will be yet?

**Comment by barttom** [comment] 2023-10-27 06:12
@NicMendonca Hi! I'm Bartek from Callstack and I want to take over this issue, please assign me :)

**Comment by mollfpr** [comment] 2023-10-30 13:47
Not overdue, Melv. Bump @NicMendonca to assign this issue to @barttom.

**Comment by barttom** [comment] 2023-10-30 14:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When user tries to log in into account that has email suspended, then goes back and logs into regular account, then regular account doesn’t behave properly.
### What is the root cause of that problem?
When user logs into to the app a check if performed to see if it should initialise the app with `App.openApp()` or to try to reconnect - https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.js#L171
When we first try to log in into the account with suspended mails and then into the regular account this check https://github.com/Expensify/App/blob/main/src/libs/SessionUtils.ts#L39 sets loggedInDuringSession variable to false because authToken is already present at this point. It happens even though this variable just got reset when going back to 1st step of login form - https://github.com/Expensify/App/blob/main/src/libs/actions/SignInRedirect.ts#L83


### What changes do you think we should make in order to solve the problem?

We can check if current email is different that this saving into session, by adding another conditional in https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.js#L158
```
const isLoggingInAsNewUser = SessionUtils.isLoggingInAsNewUser(currentUrl, session.email);
const shouldGetAllData = isUsingMemoryOnlyKeys || SessionUtils.didUserLogInDuringSession() || isLoggingInAsNewUser;
```

### What alternative solutions did you explore? (Optional)
We should change the check in this line - https://github.com/Expensify/App/blob/main/src/libs/SessionUtils.ts#L39 to `if (session?.authToken && loggedInDuringSession !== undefined) {` to also account for the reset of loggedInDuring session variable. If it gets reseted we should be ignoring already present authToken which will result in `App.openApp()` being called after logging in and resolving our issue.

**Comment by mollfpr** [comment] 2023-11-01 13:34
The proposal looks good to me! @barttom Let's do it!

🎀 👀 🎀 C+ reviewed!

**Comment by tgolen** [comment] 2023-11-01 14:35
Sounds good to me too.

**Comment by barttom** [comment] 2023-11-28 08:00
The fix was merged two weeks ago, should we close this issue?

**Comment by mollfpr** [comment] 2023-11-29 05:30
> The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough. I think this is a case where we haven't handled it yet.

>Determine if we should create a regression test for this bug.
>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the app
2. Try to log in with a suspended account (e.g. [dusjosjkposakpa@gmail.com](mailto:dusjosjkposakpa@gmail.com)) and type continue
3. Tap back to the login screen
4. Log in with Your proper account.
5. Observe the listed chat in LHN - should have listed Your chats
6. Tap on FAB -> Tap on Request Money -> Tap on currency - should have a list of currencies
7. 👍 or 👎 

@NicMendonca Could you give the payment summary so I can do the manual request? Thank you!

**Comment by iwiznia** [comment] 2023-12-07 20:58
This caused a regression. See https://github.com/Expensify/App/issues/32590#issuecomment-1845121244

**Comment by JmillsExpensify** [comment] 2023-12-11 01:40
Re-opening for the regression. Also holding payment until regression is resolved.

**Comment by JmillsExpensify** [comment] 2023-12-13 15:32
What are the next steps here?

**Comment by NicMendonca** [comment] 2023-12-15 22:13
bump @barttom @mollfpr! Have you had a chance to look at [this regression](https://github.com/Expensify/App/issues/32590#issuecomment-1845121244)?

**Comment by mollfpr** [comment] 2023-12-20 03:55
Sorry, I'm unaware that the `OpenApp` should be called once after login.

**Comment by barttom** [comment] 2023-12-21 07:28
Sorry, I'm also not aware of that. Looks like they proceeded solution in the other issue

**Comment by JmillsExpensify** [comment] 2023-12-26 17:24
Alright, so are you saying that @iwiznia shouldn't have identified this issue as a regression?

**Comment by JmillsExpensify** [comment] 2023-12-26 17:24
Let's get to the bottom of this soon, as it's delaying payment for @mollfpr until we align on whether a regression was involved or not.

**Comment by mollfpr** [comment] 2023-12-27 04:17
@JmillsExpensify I believe there's a regression, but the root cause of the proposal was correct.

**Comment by JmillsExpensify** [comment] 2023-12-27 22:26
Ok, so in that case, I approve the $500 payment for @mollfpr based on this comment.

**Closed by JmillsExpensify** 2023-12-27 22:26 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
