### ISSUE TITLE
[$500] Clicking "Enter" key selects and unselects the user in group split bill

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30649] opened 2023-10-31 18:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696935067155479

## Action Performed:
1. Open the app
2. Open any group chat
3. Click on plus and click on split bill
4. Enter any amount and continue
5. Unselect few users from below
6. Click "enter" key and observe that app select unselects the user
## Expected Result: 
App should select the user and move on to next user on "enter" key click
## Actual Result: 
App select unselects same user every time on enter click on group split bill

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/e3b87934-9d54-495b-bb7d-e5a7511425b0

https://github.com/Expensify/App/assets/38435837/3680cb36-e9e3-4eba-a64d-8def1fbbe2b6

https://github.com/Expensify/App/assets/38435837/ec113508-a4b4-4eaf-90f9-0a017a6d8731

https://github.com/Expensify/App/assets/38435837/7bec80c9-4d7e-47c1-831d-56b665997062

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/b523fc53-0f79-45a1-8845-541873f3f1dd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010303eb8cba36ffc8</li>
        <li>Upwork Job ID: 1719416022134972416</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-10-31 18:24
# Proposal

## Please re-state the problem we are trying to solve
Clicking "Enter" key selects and unselects the user in group split bill

## What is the root cause of this problem?
The `OptionSelector` has a different focus system than the inbuilt browser one. This is caused due to the conflict between the two.

## What changes should be made to fix this?
We should prevent the default browser focus by passing the prop `shouldPreventDefaultFocusOnSelectRow` as `true` in `MoneyRequestConfirmationList.js`

**Comment by akamefi202** [comment] 2023-10-31 19:28
Dupe with https://github.com/Expensify/App/issues/21392

**Comment by s77rt** [comment] 2023-11-01 07:31
@lschurr Let's close this as a dupe ^

**Comment by jaimishpatel5** [comment] 2023-11-01 12:44
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
Clicking "Enter" key selects and unselects the user in group split bill

**What is the root cause of that problem?**
We were passing shouldPreventDefaultFocusOnSelectRow always false

**What changes do you think we should make in order to solve the problem?**
in default props for OptionsSelector.js we should update shouldPreventDefaultFocusOnSelectRow to true.
const defaultProps = {
    onSelectRow: undefined,
    textInputLabel: '',
    placeholderText: '',
    keyboardType: 'default',
    selectedOptions: [],
    headerMessage: '',
    canSelectMultipleOptions: false,
    shouldShowMultipleOptionSelectorAsButton: false,
    multipleOptionSelectorButtonText: '',
    onAddToSelection: () => { },
    highlightSelectedOptions: false,
    hideSectionHeaders: false,
    boldStyle: false,
    showTitleTooltip: false,
    **//here//
		shouldPreventDefaultFocusOnSelectRow: true**
}

**What alternative solutions did you explore? (Optional)**
none

**Comment by lschurr** [comment] 2023-11-01 16:19
Closing as a dupe.

**Closed by lschurr** 2023-11-01 16:19 UTC
Labels: External, Daily, Help Wanted, Bug
