### ISSUE TITLE
[HOLD for payment 2024-12-03] [$50] Update copy on the app preferences page

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#52790] opened 2024-11-19 17:58 UTC
# Problem
When users find it difficult to navigate our application's features due to interface clutter, it leads to decreased engagement and lower conversion and retention rates.

# Solution
Clean up some of the copy on the app preferences page:

1. Remove the text "Customize your Expensify account."
2. Remove the section header for "Notifications"

![image](https://github.com/user-attachments/assets/8f5ccdc4-30e0-4ccc-b03e-1ed383d61eed)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859527407524347826</li>
        <li>Upwork Job ID: 1859527407524347826</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 105008786</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment] 2024-11-19 18:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update copy on the app preferences page
### What is the root cause of that problem?
This is an improvment
### What changes do you think we should make in order to solve the problem?
Remove the `title` and `subtitle` prop here

https://github.com/Expensify/App/blob/763215e0aa0ac256f5f129e7f62444a466e84e8f/src/pages/settings/Preferences/PreferencesPage.tsx#L54

### What alternative solutions did you explore? (Optional)

**Comment by tgolen** [comment] 2024-11-19 23:38
@JmillsExpensify let's set the bounty on this one to $50 since it's a simple copy change.

**Comment by jacobkim9881** [comment] 2024-11-20 01:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Because of less readable interface, user engagements are low and retention rates are too.

### What is the root cause of that problem?
This part is less readable
https://github.com/Expensify/App/blob/9368566b52364a34747d8f97d3de7f427b3e0712/src/languages/en.ts#L1615-L1619

And this is too
https://github.com/Expensify/App/blob/9368566b52364a34747d8f97d3de7f427b3e0712/src/pages/settings/Preferences/PreferencesPage.tsx#L62-L67

### What changes do you think we should make in order to solve the problem?

Change to
`Customize your Expensify account.`

and remove the text header.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by prakashbask** [comment] 2024-11-20 13:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clean up some of the copy on the app preferences page

### What is the root cause of that problem?
UX improvement suggestion to reduce interface clutter and improve customer engagement and retention

### What changes do you think we should make in order to solve the problem?
1) App references page has a Section component which defines subtitle properties in order to display the text "Customize your Expensify account".  To remove this text, following changes are proposed

&nbsp;&nbsp;&nbsp;&nbsp;a) Remove subtitle and subtitleMuted props in
>https://github.com/Expensify/App/blob/d7450adad5458110e73a61a061f3de2c303c53e6/src/pages/settings/Preferences/PreferencesPage.tsx#L55
>https://github.com/Expensify/App/blob/d7450adad5458110e73a61a061f3de2c303c53e6/src/pages/settings/Preferences/PreferencesPage.tsx#L57

&nbsp;&nbsp;&nbsp;&nbsp;b) Remove subtitle language translation in both english and spanish translation files

>https://github.com/Expensify/App/blob/d7450adad5458110e73a61a061f3de2c303c53e6/src/languages/en.ts#L1618 
>https://github.com/Expensify/App/blob/d7450adad5458110e73a61a061f3de2c303c53e6/src/languages/es.ts#L1620

2) App preferences page also have a preference for Notifications and a Text component is used to render the label "Notifications". To remove this text, following changes are proposed

&nbsp;&nbsp;&nbsp;&nbsp;a) Remove Text component in 
>https://github.com/Expensify/App/blob/d7450adad5458110e73a61a061f3de2c303c53e6/src/pages/settings/Preferences/PreferencesPage.tsx#L62

&nbsp;&nbsp;&nbsp;&nbsp;b) Remove notifications label language translation in both english and spanish translation files
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/languages/en.ts#L319
>https://github.com/Expensify/App/blob/9f83a4118ff0b8080ac8c037b36a26252a12b06f/src/languages/es.ts#L310

End Result is shown below
![Screenshot 2024-11-20 at 6 39 12 PM](https://github.com/user-attachments/assets/61bc1363-9ee2-407e-b37e-aff728fabd33)


### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-11-21 10:52
Reviewing proposals in a moment

**Comment by JmillsExpensify** [comment] 2024-11-21 11:10
Thanks. Issue opened up for proposals at $50

**Comment by brunovjk** [comment] 2024-11-21 12:45
@nkdengineer and @jacobkim9881 proposals, while correct, lack multilingual support and completeness compared to @prakashbask.

I think we can go with @prakashbask's [proposal](https://github.com/Expensify/App/issues/52790#issuecomment-2488548912), as it is the most complete. It not only addresses the UI changes but also ensures that translations in multiple languages are updated.

<details>
<summary>Quick test on my side:</summary>



![Screenshot 2024-11-21 at 09 14 11](https://github.com/user-attachments/assets/0b686f77-5d71-40c0-8abe-57c40adc3a0f)

</details>



🎀👀🎀 C+ reviewed

**Comment by prakashbask** [comment] 2024-11-22 06:52
PR https://github.com/Expensify/App/pull/52944

**Comment by JmillsExpensify** [comment] 2024-11-27 11:53
All contributors have offers. Waiting for the regression period to pass and checklist.

**Comment by brunovjk** [comment] 2024-12-02 11:58
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: Update copy

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: It does not apply because it is not a bug but an update.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: It does not apply because it is not a bug but an update.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
- I don't believe we need a regression test since this is an update (removal) of a copy.

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-12-03 09:28
All contracts paid out. I agree with @brunovjk that copy changes don't require a new regression test. Closing this one.

**Closed by JmillsExpensify** 2024-12-03 09:28 UTC
Labels: External, Daily, Awaiting Payment, Bug
