### ISSUE TITLE
`You appear to be offline' text change place in report screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13831] opened 2022-12-26 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. navigate to home page
2. disable network
3. navigate to any report , observe You appear to be offline

## Expected Result:
You appear to be offline. message should stick to the bottom

## Actual Result:
You appear to be offline. message change its place after a second

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

- [ ] iOS / native - **(Needs reproduction)**

**Version Number:** 1.2.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209579960-3b90bb30-cbe9-4a00-aa92-9fea275626eb.mp4

https://user-images.githubusercontent.com/43996225/209579979-87380a0e-75d7-4502-aef3-4c3da88e505a.mov

https://user-images.githubusercontent.com/43996225/209580076-657b4eb8-2745-459e-9db7-ea90cf818dbd.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671897359248469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2022-12-29 22:52
I can reproduce on the live Android 1.2.43-1 version. I wasn't able to get offline mode to work on browserstack so I couldn't test the most recent version

**Comment by ctkochan22** [comment] 2023-01-03 02:06
Okay, hmm. So the description isn't fully filled out. 

So its only happening on Android?

**Comment by ctkochan22** [comment] 2023-01-10 06:57
bump

**Comment by tgolen** [comment] 2023-01-10 20:42
After analyzing the video closer, I think it's not related to the offline indicator. You can see that the entire skeleton UI is shifting position when a new chat is loading in. I think this is just normal layout stuff happening as contents loads in, so I don't really think this is very much worth fixing. You can see these two frames show the difference. The position shifts at the same time as the avatar and call buttons display in the header.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1228807/211657666-4cd12564-ddb3-46f6-82bc-e2bc6c6feea5.png">

**Comment by ctkochan22** [comment] 2023-01-10 23:35
Fired up android. And still unable to reproduce- https://recordit.co/HBQq9rC5bF

On top of what Tim said, lets close this until have have clearer repro steps and we have something meaningful to fix.

**Closed by ctkochan22** 2023-01-10 23:35 UTC
Labels: Engineering, Daily, Bug
