### ISSUE TITLE
[HOLD for payment 2023-11-17] [$1000] Android-Compose- Header markdown-multiline with URL, vary in format while editing & sending

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26942] opened 2023-09-07 10:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app and click on a chat
2. Type into the chat:
```
    # [google1
    google2
    google3](https://www.google.com)
```
3. Try to edit the typed comment. Notice that it has a different markdown structure:
```
    # [google1](https://www.google.com)
    google2
    google3
```

## Expected Result:
User sending an URL, with 3 rows of multiline message in [ ],all are shown as URL.

Similarly,User sending an URL including header markdown, with 3 rows of multiline message in [ ], all 3 rows multiline message must be shown as URL.

The Header markdown, multiline message with URL, must not display in different format while editing. All three rows of multiline message should display inside [ ], as entered by user

## Actual Result:
User sending an URL, with 3 rows of multiline message in [ ],all are shown as URL.

User sending an URL including header markdown, with 3 rows of multiline message in [ ], only first row message is shown as url and remaining two rows message shown as text.

The Header markdown, multiline message with URL, displays in different format while editing. First row text entered only shown inside [ ], and for remaining 2 rows message format changed and shown outside [ ].

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/60a0d008-33e3-496e-9c74-fc0123c6c940

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf462eb26aa8fbe1</li>
        <li>Upwork Job ID: 1701242002102861824</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertKozik</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertKozik</details>

**Comment by strepanier03** [comment] 2023-09-11 14:19
Working on this now, I've been ill.

**Comment by strepanier03** [comment] 2023-09-11 14:31
Repro'd following steps.

![image](https://github.com/Expensify/App/assets/10925636/f2e8fddd-7486-41ea-9cb7-6bfcd995d9f5)

**Comment by strepanier03** [comment] 2023-09-14 21:23
Waiting for proposals Melvin, we're good for now.

**Comment by robertKozik** [comment] 2023-09-18 10:49
Still waiting for proposals

**Comment by strepanier03** [comment] 2023-09-18 20:40
I don't think we should increase the bounty at this time, there are simply a lot of open issues to be worked on right now and this isn't a critical bug that should take priority.

**Comment by robertKozik** [comment] 2023-09-21 10:02
waiting for proposals

**Comment by strepanier03** [comment] 2023-09-22 18:47
I'm out of the office on Monday and Tuesday next week. If urgent action is needed by a BZ during that time, please reach out to [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to ask for help. Otherwise, I'll on this Wednesday when I'm online again. 

Have a good weekend!

**Comment by robertKozik** [comment] 2023-09-26 14:33
No update here - still waiting for proposals

**Comment by strepanier03** [comment] 2023-09-27 22:11
@robertKozik - Do you think we should increase the bounty? What do you think is the main blocker to receiving proposals for this if you don't think a higher bounty would help?

**Comment by robertKozik** [comment] 2023-09-28 07:34
Let me take a look more closely, will come back shortly

**Comment by robertKozik** [comment] 2023-09-28 08:11
@strepanier03 
Alright, first of all, it's not an Android-specific problem. It can be reproduced across all platforms, as the issue lies within the `ExpensiMark` parsing. The problem stems from the regex parsing the markdown link to HTML.

I suggest we modify the reproduction steps as follows:

1. Type into the chat:

```
# [google1
google2
google3](https://www.google.com)
```

2. Try to edit the typed comment. Notice that it has a different markdown structure:

```
# [google1](https://www.google.com)
google2
google3
```

This should make it easier to reproduce when fixing.

Additionally, I'm thinking that we should increasing the bounty. Bugs within the parsers/regexes are, in my opinion, more troublesome to fix.

**Comment by strepanier03** [comment] 2023-09-28 21:06
@robertKozik 

> Alright, first of all, it's not an Android-specific problem. It can be reproduced across all platforms, as the issue lies within the ExpensiMark parsing.

Gotcha, I'll update the OP comment to include the other platforms. 

> I suggest we modify the reproduction steps as follows:

Thank you for the suggestion, I'll make that update as well. 

> Additionally, I'm thinking that we should increasing the bounty. Bugs within the parsers/regexes are, in my opinion, more troublesome to fix.

Wonderful, thank you so much for weighing in. This is the context that I just don't have working on the product side (not the code side) of Expensify. I'll double the bounty and we'll see what another week gets us in terms of proposals.

**Comment by soro-kuraima** [comment] 2023-09-29 04:53
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android-Compose- Header markdown-multiline with URL, vary in format while editing & sending #26942

### What is the root cause of that problem?
Incorrect regex expression for replacing headings

https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js
#L181-L185

it results in incorrect heirarchy of html divs, 
the html looks like this
`<h1><a href="https://herald.com" target="_blank" rel="noreferrer noopener">herald </h1>com<br /> chom</a>`

### What changes do you think we should make in order to solve the problem?
i'd change regex to something like this
{
    name: 'heading1',
    regex: /^# +(?! )((?:(?!<pre>|\n|\r\n).)+?)(?=\n|<|$)/gm,
    replacement: (_, content) => {
        return '<h1>' + content.replace(/\n/g, '<br>') + '</h1>';
    }
}

this will result in 
`<h1><a href="https://herald.com" target="_blank" rel="noreferrer noopener">herald </br>com </br> chom</a> </h1>`

but in that case all of it will be in <h1>.

if the header markdown is required only for first letter, the htmlToMarkdown / htmlToText methods as well to accomodate it.

**Comment by shubham1206agra** [comment] 2023-09-29 13:29
@robertKozik I have doubts about the expected behaviour

**Comment by pradeepmdk** [comment] 2023-09-29 14:04
@robertKozik I think this this working as expected only. 

```
[google1
    google2
    google3](https://www.google.com)
``` 
this will shown as a URL 

[google1
    google2
    google3](https://www.google.com)

here it will  point all the 3 line point to google.


and this one
`[google1](https://www.google.com)` this part only url remain goes a text only.
```
[google1](https://www.google.com)
    google2
    google3
```
[google1](https://www.google.com)
    google2
    google3
this is the markdown structure.

you can verify this using github comment also.

**Comment by soro-kuraima** [comment] 2023-09-30 02:02
It's actually generating incorrect html, the tags hierarchy is broken.

**Comment by strepanier03** [comment] 2023-10-02 19:41
@robertKozik - Friendly bump on the comments above, thank you for your insight 🙌 on moving this forward.

**Comment by pradeepmdk** [comment] 2023-10-02 19:50
@soro-kuraima could you  share the   Which one is incorrect HTML here ?

**Comment by soro-kuraima** [comment] 2023-10-02 21:11
`<h1>
         <a href="https://herald.com" target="_blank" rel="noreferrer noopener">herald
</h1>
          com<br />
          chom</a>`

this one for eg:- 
notice h1 > a ; but h1 closes before a.

**Comment by r3770** [comment] 2023-10-03 02:23
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Header markdown-multiline with link is not parsed as expected

### What is the root cause of that problem?
```
    # [google1
    google2
    google3](https://www.google.com)
```
markdown parser is parsing above header-mulitline link as following.
```
<h1><a href=\"https://google.com\" target=\"_blank\" rel=\"noreferrer noopener\">google</h1>google<br />google</a>
```
but it's not expected behavior.
when we check on github and discord platform, expected behavior is that first line (`[google1`) is parsed as header, and https://www.google.com will be parsed as autolink.
![image](https://github.com/Expensify/App/assets/86615752/cba061f0-4560-453d-9d2b-45ed268903d6)
![image](https://github.com/Expensify/App/assets/86615752/6700807c-db59-4565-8247-c4daaf1d8750)

i think it's expected behavior...
### What changes do you think we should make in order to solve the problem?
To get expected behavior, we can move header1 rule before link rule. and it's not enough to get what we expect.
so we can add a more condition `match[1].includes('</h1>')` in https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L491

then parsed html will be as following
```
<h1>[google</h1>google<br />google](<a href=\"https://google.com\" target=\"_blank\" rel=\"noreferrer noopener\">https://google.com</a>)
```
it does not make other autotest cases failed.

**Comment by r3770** [comment] 2023-10-05 10:34
@strepanier03 @robertKozik 
Could you check my [proposal](https://github.com/Expensify/App/issues/26942#issuecomment-1744062072) please ?

**Comment by robertKozik** [comment] 2023-10-06 12:36
@soro-kuraima, could you please share the resulting HTML after applying your solution? I'd like to double-check it before making a decision on the proposals.

**Comment by soro-kuraima** [comment] 2023-10-06 19:17
I've tried two solutions. 

One gave the following result:

 ```
 <h1>
         <a href="https://herald.com" target="_blank" rel="noreferrer noopener">
          herald
          <br />
          com<br />
          chom</a>
 </h1>
```

Another one where I change the h1 replacement regex and sequence in which it's decided

The following result will come


```
 <h1>
         <a href="https://herald.com" target="_blank" rel="noreferrer noopener">
          herald
          </a>
 </h1>
          com
          <br/>
          chom
```

I've one doubt. The issue is with expensimark.js in 
expensify-common/lib.

So, the changes and pr will have to be in that repo.

**Comment by soro-kuraima** [comment] 2023-10-06 19:45
> # Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Header markdown-multiline with link is not parsed as expected
> 
> ### What is the root cause of that problem?
> ```
>     # [google1
>     google2
>     google3](https://www.google.com)
> ```
> markdown parser is parsing above header-mulitline link as following.
> ```
> <h1><a href=\"https://google.com\" target=\"_blank\" rel=\"noreferrer noopener\">google</h1>google<br />google</a>
> ```
> but it's not expected behavior.
> when we check on github and discord platform, expected behavior is that first line (`[google1`) is parsed as header, and https://www.google.com will be parsed as autolink.
> ![image](https://github.com/Expensify/App/assets/86615752/cba061f0-4560-453d-9d2b-45ed268903d6)
> ![image](https://github.com/Expensify/App/assets/86615752/6700807c-db59-4565-8247-c4daaf1d8750)
> 
> i think it's expected behavior...
> ### What changes do you think we should make in order to solve the problem?
> To get expected behavior, we can move `heading1` rule before `link` rule. and it's not enough to get what we expect.
> so we can add a more condition `match[1].includes('</h1>')` in https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L491
> 
> then parsed html will be as following
> ```
> <h1>[google</h1>google<br />google](<a href=\"https://google.com\" target=\"_blank\" rel=\"noreferrer noopener\">https://google.com</a>)
> ```
> it does not make other autotest cases failed.
> ![image](https://github.com/Expensify/App/assets/86615752/715b5ce4-c4fc-4a6b-8c00-c4647d1e615d)
> 

Is it working for text to markdown and does it work for more than 3 lines and takes edge cases in account ?

**Comment by r3770** [comment] 2023-10-07 07:23
> Is it working for text to markdown and does it work for more than 3 lines and takes edge cases in account ?

yes, for sure. you can check as it is.

**Comment by robertKozik** [comment] 2023-10-09 08:34
Thanks both of you for your input on this issue. I think the research from @r3770 gives us the correct path to resolve this issue. As I see it doesn't need regex changes which could be prone to regressions. 
I think we should go with the @r3770 [proposal](https://github.com/Expensify/App/issues/26942#issuecomment-1744062072)

🎀 👀 🎀 C+ reviewed

**Comment by cead22** [comment] 2023-10-12 03:42
We have a good proposal. It looks like next step is for @strepanier03 to manually hire @r3770

**Comment by strepanier03** [comment] 2023-10-16 16:21
Sure thing, will get that sorted today.

**Comment by r3770** [comment] 2023-10-20 04:44
Contributor details
Your Expensify account email: serhiiklymenko26@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f170fd393981eec1

**Comment by robertKozik** [comment] 2023-10-23 19:16
@r3770 Yes, after you are assigned please create the PR for `expensify-common`

**Comment by strepanier03** [comment] 2023-10-24 14:27
@r3770 - You can review the [contributing.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to learn how to contribute to the community and complete a job using the correct steps.

**Comment by r3770** [comment] 2023-10-25 07:48
@strepanier03 @robertKozik 
The PR https://github.com/Expensify/expensify-common/pull/592 for expensify-common repo is ready for review

**Comment by r3770** [comment] 2023-10-26 07:48
@strepanier03 Could you kindly send me a offer for this job on upwork ?

**Comment by r3770** [comment] 2023-10-27 06:55
@cead22 @strepanier03 @robertKozik 
Friendly bump

**Comment by cead22** [comment] 2023-10-27 17:48
@robertKozik can you try posting a comment on [the PR](https://github.com/Expensify/expensify-common/pull/592) so I can assign you the review please?

**Comment by strepanier03** [comment] 2023-10-27 19:45
@r3770 - The offer will come automatically and be linked in the payment summary comment.

**Comment by r3770** [comment] 2023-10-30 11:42
@robertKozik could you please take a look into [PR](https://github.com/Expensify/expensify-common/pull/592) ?

**Comment by r3770** [comment] 2023-11-01 21:39
@robertKozik Friendly bump

**Comment by strepanier03** [comment] 2023-11-02 17:22
@robertKozik - Please review and update the PR as soon as you can.

**Comment by r3770** [comment] 2023-11-02 22:48
@cead22 @robertKozik The App PR https://github.com/Expensify/App/pull/30808 is ready to move forward

**Comment by r3770** [comment] 2023-11-10 07:42
@strepanier03 @cead22
The App PR had been merged, what is the next step ?
Could you send me offer on upwork ? or should I apply for the job ?

**Comment by eh2077** [comment] 2023-11-15 13:29
The fix of this issue breaks `autolink` within heading, see https://github.com/Expensify/App/issues/31352


https://github.com/Expensify/App/assets/117511920/ab5ad6df-34ce-4f0f-a609-86e32d519455

**Comment by r3770** [comment] 2023-11-15 13:30
@cead22 @robertKozik 
A regression has been reported on https://github.com/Expensify/App/issues/31352
what can i do now ?

**Comment by cead22** [comment] 2023-11-15 16:41
I think so, and if you can't come up with a simple fix, then maybe we can revert and try again from the beginning

**Comment by r3770** [comment] 2023-11-16 00:50
@cead22 @robertKozik 
https://github.com/Expensify/expensify-common/pull/605 is ready to fix extra issue

**Comment by r3770** [comment] 2023-11-17 08:41
@cead22 @robertKozik 
The App PR https://github.com/Expensify/App/pull/31477 is ready, but git action tests are failed, not sure why it is
Could you check it ?

**Comment by r3770** [comment] 2023-11-27 11:47
@cead22 @strepanier03 
Friendly bump

**Comment by r3770** [comment] 2023-11-29 09:33
@cead22 @strepanier03 
Kind Bump again

**Comment by r3770** [comment] 2023-11-30 00:10
@cead22 @strepanier03 @robertKozik 
It's been a week since the fixed version of regression issue deployed to staging.
Could you check how we can move forward ?

**Comment by strepanier03** [comment] 2023-11-30 17:23
@r3770 - Please apply for the job [here](https://www.upwork.com/jobs/~01639469c7d0acd6ee), I've attempted to hire you directly to it but because your Upwork profile is private I cannot.

**Comment by r3770** [comment] 2023-11-30 22:41
@strepanier03 
Offer accepted, Thanks

**Comment by strepanier03** [comment] 2023-11-30 22:42
Thank you again for your quick communication @r3770, I'm sorry this went unhandled for this long.

**Comment by strepanier03** [comment] 2023-11-30 22:43
Since the checklist is done and no regression test is suggested I'm going to close this out. Thanks everyone and thank you for the 1:1 message @cead22 🙌

**Closed by strepanier03** 2023-11-30 22:43 UTC
Labels: Reviewing, External, Engineering, Daily, Internal, Awaiting Payment, Bug
