### ISSUE TITLE
[HOLD for payment 2024-01-16][$500] Web - Workspace - Inconsistent tooltip for workspace name in thread and IOU

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31894] opened 2023-11-26 23:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Go to Settings > Workspaces > New Workspace.
2. Change the workspace name if you want
3. Go to the workspace expense room.
4. Send a message.
5. Go to 'Request money.'
6. Enter the amount and send it.
7. Go to the workspace setting and delete it.
8. Click on IOU and hover over the workspace name at the header.
9. Go back, hover over the message, and click on 'Reply In Thread'
10. Hover over the workspace name at the header.
11. Notice inconsistency between workplace name tooltips.

## Expected Result:
The workspace name tooltip should be the same for thread header and IOU.

## Actual Result:
Inconsistency in the thread workspace name tooltip and IOU workspace name tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/65b30c91-6743-4514-888f-6b4dd5fea075

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c1c53f77916777c</li>
        <li>Upwork Job ID: 1728926172581572608</li>
        <li>Last Price Increase: 2023-11-26</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27883148</li>
</ul></li>
    </ul>
</details>

**Comment by chie2727** [comment] 2023-11-27 14:24
Contributor details
Your Expensify account email: sophiea-e@hotmail.co.uk
Upwork Profile Link: https://www.upwork.com/freelancers/~01e5bcae9f03690137

**Comment by kaushiktd** [comment] 2023-11-28 12:33
### Please re-state the problem that we are trying to solve in this issue.
Web - Workspace - Inconsistent tooltip for workspace name in thread and IOU

### What is the root cause of that problem?
The function `getPolicyName()` returns "Unavailable workspace policy" when the workspace name is not available. This is happening when we delete the workspace.

### What changes do you think we should make in order to solve the problem?
If the workspace name (`report.policyName` or `report.oldPolicyName`) is not available, the function will return an empty string or hidden. If the workspace name is available, it will display the workspace name accordingly. 

or

When a thread is opened after the workspace has been archived, set the `oldPolicyName` to the name of the workspace before deletion. Ensure this change is reflected both optimistically (client-side) and on the backend.

**Comment by cubuspl42** [comment] 2023-11-29 15:41
C+ reviewed 🎀 👀 🎀

I approve the proposal by @chie2727. In my opinion, obtaining the archived workspace name from the parent-report is a cleaner and more normalized approach in this scenario.

**Comment by chie2727** [comment] 2023-11-30 04:42
Thank you very much.
I will submit a PR as soon as my proposal is accepted on Upwork.

**Comment by chie2727** [comment] 2023-12-01 01:53
@cubuspl42 Thanks for letting me know. The PR is ready for review: https://github.com/Expensify/App/pull/32325

**Comment by chie2727** [comment] 2023-12-12 01:09
Hi @cubuspl42, will the PR be merged soon?

**Comment by cubuspl42** [comment] 2023-12-12 10:43
@chie2727 

😳

I don't know what happened here, I'll comment on the PR.

**Comment by chie2727** [comment] 2023-12-26 00:39
@dukenv0307 
Interesting to hear your insight. If you have a look at my PR (https://github.com/Expensify/App/pull/32325/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811dbR507) you can see that my proposal is not to make the thread report rely on the root parent report, but instead to add the root parent report to the search condition for finding the policy name. So in the case that the policy name is not present in the policy object or the report object, it can be obtained from the parent report object instead.

**Comment by cubuspl42** [comment] 2023-12-27 09:59
@dukenv0307 Thanks for sharing your findings.

It's unlikely that we change the assignment at this stage.

How many reports does one need to have to trigger paginating?

**Comment by cubuspl42** [comment] 2023-12-27 13:15
> What do you think?

I'll test this solution on my most report-heavy account (most likely heavier than any real customer). I'll see if I can observe any problems!

> I'm good too work together

I don't think the Expensify process has room for such a step.

**Comment by cubuspl42** [comment] 2023-12-27 13:38
It's definitely not "normal" or "common", but I'm not saying there was no precedence. Still, we're assuming that the solution being reviewed right can trigger a bug, although I havent't yet reproduced it or seen it reproduced (or maybe _produced_ would be a more suitable term?).

**Comment by amyevans** [comment] 2024-01-11 22:18
Looks like https://github.com/Expensify/App/pull/32325 was deployed to prod 1/9 and the automation just didn't trigger. I'll update the labels/title accordingly.

**Comment by MitchExpensify** [comment] 2024-01-13 20:30
Thanks @amyevans, reminder set to pay on the 16th!

**Comment by MitchExpensify** [comment] 2024-01-16 21:00
Paid and contract ended for @cubuspl42 

Offer sent to @chie2727, will pay out once accepted! 🙇

**Comment by MitchExpensify** [comment] 2024-01-23 02:14
Paid and contract ended!  Thanks all

**Closed by MitchExpensify** 2024-01-23 02:14 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
