### ISSUE TITLE
[$500] IOU - In WS, pay elsewhere button shown even after paid

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36379] opened 2024-02-12 21:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4303948
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Using enable wallet, add chase Bank plaid 111 ending account
3. In WS--bank-- add chase Bank plaid 111 ending account
4. In WS chat, request money and pay elsewhere

## Expected Result:
In WS, pay elsewhere button must not be shown after paid.

## Actual Result:
In WS, pay elsewhere button shown even after paid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cc34d2bb-8a64-47e4-9590-766df44c38f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012477eba2d13c4e44</li>
        <li>Upwork Job ID: 1757157712421134336</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-12 21:40
We think that this bug might be related #vip-bills
CC @davidcardoza

**Comment by allroundexperts** [comment] 2024-02-17 03:43
Not overdue. Looking for proposals.

**Comment by slafortune** [comment] 2024-02-19 19:09
@kbecciv if you select the dropdown option, are you able to select to pay another way, like the added bank account?  And they should be the default option showing?

**Comment by slafortune** [comment] 2024-02-23 16:58
@kbecciv sorry if I'm not picking up something in your recording on this - if you select the dropdown option, are you able to select to pay another way, like the added bank account? And they should be the default option showing?

**Comment by kbecciv** [comment] 2024-03-04 14:49
@slafortune Checking with team

**Comment by kbecciv** [comment] 2024-03-04 14:59
@slafortune Issue is reproducible

https://github.com/Expensify/App/assets/93399543/41acd587-02ff-485f-927e-cbda93e39e9a

**Comment by slafortune** [comment] 2024-03-04 17:45
Thanks for rechecking @kbecciv !

**Comment by Swor71** [comment] 2024-03-05 14:14
hey I'm Marcin from Callstack - expert contributor group, I'd like to take a look at this issue

**Comment by slafortune** [comment] 2024-03-05 16:05
Thanks @Swor71 - I've assigned you 👍

**Comment by Swor71** [comment] 2024-03-07 13:08
cc @kbecciv @slafortune 
trying to reproduce this issue (followed the very limited repro steps) but it seems the issue here is a bit different - the accounts are the same hence this is happening, could someone clarify if these are actually the correct steps and/or is it actually a bug?
<img width="844" alt="image" src="https://github.com/Expensify/App/assets/32240132/cdaf0ab4-d432-4de4-af39-3c4e088b741a">

**Comment by slafortune** [comment] 2024-03-07 13:31
AH!  Thanks @Swor71 sorry I missed that, makes sense!

@kbecciv do you disagree in closing this?

**Comment by Swor71** [comment] 2024-03-12 15:32
@kbecciv friendly bump on [the question](https://github.com/Expensify/App/issues/36379#issuecomment-1983515405) from @slafortune :)

**Comment by Swor71** [comment] 2024-03-18 09:50
@slafortune Melvin is getting unhappy with this open issue :D how should we proceed since @kbecciv is unfortunately not responding to our mentions?

**Comment by slafortune** [comment] 2024-03-18 20:21
I think we can close this - as it is, this is expected since they are the same account in the steps.  Thanks @Swor71 for sticking with this 👍

**Closed by slafortune** 2024-03-18 20:21 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by kbecciv** [comment] 2024-03-19 15:47
We can close the issue!
