### ISSUE TITLE
[$500] Android - Distance - Confirmation page flickers after saving description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32582] opened 2023-12-06 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- App location access is denied
1. Launch New Expensify app
2. Go to workspace chat > + > Request money
3. Go to Distance
4. Enter addresses > Continue
5. On the confirmation page, tap Description
6. Enter description and save it

## Expected Result:
The confirmation page does not flicker after saving the description

## Actual Result:
The confirmation page flickers after saving the description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f144dbf2-705c-4011-9a3a-418c8ddcaf5f

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011306a4c127682f24</li>
        <li>Upwork Job ID: 1732482197834444800</li>
        <li>Last Price Increase: 2023-12-20</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2023-12-07 16:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Distance - Confirmation page flickers after saving description

### What is the root cause of that problem?
It turns out that this is  known issue of react navigation . You can see a discussion of this error [here](https://github.com/software-mansion/react-native-screens/issues/111).

### What changes do you think we should make in order to solve the problem?
Adding below code in  App.js should be enough to fix problem 
```
import { enableScreens } from 'react-native-screens'

enableScreens()
```
But if above code is not enough we need to add  [this line](https://github.com/Expensify/App/blob/8fa65ec4de74f22f7c700eb78b4ee83eda96de58/src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx#L20) in RightModalNavigator.js to below

```
  const screenOptions = useCallback(({navigation}) => {
      return {
          detachPreviousScreen: !navigation.isFocused(),
          ...RHPScreenOptions(styles)
      }
  }, [styles]);
```

### What alternative solutions did you explore? (Optional)
NO

**Comment by shahinyan11** [comment] 2023-12-12 14:26
> I don't think we want to detach previous screens. Let's see if we can get better proposals without enableScreens.

what's not good about `enableScreens`
I saw that several new issues have opened where the same problems are on other screens. My proposal can fix this problem globally in app

**Comment by shahinyan11** [comment] 2023-12-14 15:43
@0xmiroslav I would be grateful if you don't ignore my writing and answer something

**Comment by shahinyan11** [comment] 2023-12-15 06:44
> @shahinyan11 the issue you linked is very old (4 years ago)

@0xmiroslav 
But that solves the problem, doesn't it? I was expecting an answer on what it could have a bad effect on

**Comment by zanyrenney** [comment] 2023-12-18 13:02
@0xmiroslav can't you review the propsoals first?

**Comment by shahinyan11** [comment] 2023-12-18 14:29
@0xmiroslav  Sorry, but I don't agree with you that the solution is harmful.

**Comment by mountiny** [comment] 2023-12-18 15:21
Asked

**Comment by WoLewicki** [comment] 2023-12-18 16:58
The problem with @shahinyan11 solution is that we will have the previous screen attached all the time and it is for sure suboptimal. Is this issue reproducible on other screens? Could you check if it is connected somehow to having `TextInput` on the screen? It is quite hard to determine what exactly is wrong in a very complex scenario 😅

**Comment by shahinyan11** [comment] 2023-12-18 17:10
@WoLewicki  But if the current screen has modal presentation will not we have previous screen attached anyway ? 
If so, what do you say if we transfer `enableScreens()` from `App.js` to somewhere where this will only affect modal screens ?

**Comment by WoLewicki** [comment] 2023-12-18 17:20
> But if the current screen has modal presentation will not we have previous screen attached anyway ?

Yes, but the screen we are seeing is not a modal yeah? I am not sure what do you mean here.

> If so, what do you say if we transfer enableScreens() from App.js to somewhere where this will only affect modal screens ?

`enableScreens` method does not change anything right now since `RNScreens` are enabled by default if you don't change it explicitly in each navigator. 

Could we also get answers for the questions from my previous comment? I think having a minimal reproducible example for this would be best to have it fixed ASAP.

**Comment by shahinyan11** [comment] 2023-12-18 17:34
@WoLewicki The screen has a modal presentation. And I can't answer why, but using only `enableScreens` solves the problem. There is not need `detachPreviousScreen` it is mentioned additionally.
And about reproducing. This is very difficult to reproduce and the provided steps will not always lead to this.

**Comment by WoLewicki** [comment] 2023-12-19 09:41
If you are sure that adding `enableScreens` solves the problem, I think you can make a PR with it and then we can test if it is true.

**Comment by WoLewicki** [comment] 2023-12-19 09:44
Also, I think our strategy is to always try and fix the root of the problem, so I think that trying to create a minimal repro where we could spot the bug would be best option 🚀

**Comment by shahinyan11** [comment] 2023-12-19 10:07
@WoLewicki  The solution with using  `enableScreens`  already is checked by C+ @0xmiroslav . I would like to him to be active in discussions .

**Comment by WoLewicki** [comment] 2023-12-19 11:20
@shahinyan11 do you know what is the root of the problem we are trying to solve with the code you suggested?

**Comment by shahinyan11** [comment] 2023-12-19 11:43
@WoLewicki How I understand it is the navigation package bug .  And I mentioned an issue link from react-navigation GitHub issues in my proposal

**Comment by shahinyan11** [comment] 2023-12-19 11:44
> The suggested solution above is harmful and might cause any unexpected behavior on other parts. So I'd like to confirm with react-navigation expert if it's the right approach.

The C+ says the solution is harmful. Can you explain what is harmful in using `enableScreens` ?

**Comment by WoLewicki** [comment] 2023-12-19 16:43
The problem with it is that it is enabled by default so I would be against adding such thing without knowing why it fixes anything (code enabling it by default: https://github.com/software-mansion/react-native-screens/blob/336efc0c715c1312ec4f9d8bd5709cc1d884709b/src/index.native.tsx#L46)

**Comment by shahinyan11** [comment] 2023-12-19 20:48
@0xmiroslav  It is my version.  And I think this is correct, at least until there is not someone who has a different explanation and solution . As much as I can’t say what the main problem is, you can’t say why “enableScreens” is harmful

Anyway I have nothing to add to my proposal . You can accept it or reject it .

**Comment by shahinyan11** [comment] 2023-12-19 20:59
@0xmiroslav @WoLewicki @zanyrenney 
Or I suggest increasing the payment to spend more time on deep research. And perhaps this will help attract the attention of other participants and we received better proposal

**Comment by WoLewicki** [comment] 2023-12-20 12:55
Can we get answers for questions from this comment so we can narrow down the root of the problem: https://github.com/Expensify/App/issues/32582#issuecomment-1861058212 ?

**Comment by mvtglobally** [comment] 2023-12-21 16:16
Issue not reproducible during KI retests. (First week)

**Comment by shahinyan11** [comment] 2023-12-21 16:37
> Issue not reproducible during KI retests. (First week)

@mvtglobally Sorry. Can you explain what means `KI` ?

**Comment by zanyrenney** [comment] 2023-12-22 13:53
Also can't reproduce this after testing again. I think we can maybe close this?

**Comment by mountiny** [comment] 2023-12-26 11:32
If we cannot reproduce this reliably I think we can close this. cc @isagoico @mvtglobally @kavimuru Could you please retest again?

**Comment by kbecciv** [comment] 2023-12-27 14:20
@mountiny Issue is no longer reproduced

https://github.com/Expensify/App/assets/93399543/fa62f0e4-bd1b-4918-bafb-64a8d0f2ef40

**Comment by mountiny** [comment] 2023-12-27 14:27
Thanks!

**Closed by mountiny** 2023-12-27 14:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
