### ISSUE TITLE
Expense - Workspace chat does not get bold on LHN even if new marker is present

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46955] opened 2024-08-07 10:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** Yokabdk+new11@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to settings and workspace and create a workspace
3. Go to workspace chat and click on plus icon
4. Click on submit expense
5. Enter an amount (e.g 100) and click Next
6. Input a merchant and submit the expense
7. Create another expense with a different amount (e.g 50)
8. Navigate to the expense details page of the first expense (e.g 100)
9. Click on header and click on hold
10. Click on the workspace chat (Important)
11. Click on the expense preview
12. Go offline
13. Click on the drop down of the green pay button at the top right corner
13. Click on "Pay elsewhere"
14. Click on "Pay only 50" on the confirmation pop up
15. Observe the workspace chat on LHN and click on it
16. Observe the new line marker

## Expected Result:
The workspace chat becomes bold as there is a new message and hence the new line marker

## Actual Result:
The workspace chat on LHN doesn't get bold even if there is a new line marker. This is different from the behaviour seen while executing the steps online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2a51b363-36e1-4477-89c7-ef518f0097e0

<img width="594" alt="Bug6553688_1721998638877!Screenshot_2024-07-26_155300" src="https://github.com/user-attachments/assets/5669ee66-10bd-45d1-9c91-18d9052a5d53">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VictoriaExpensify** [comment] 2024-08-12 07:14
I'm having trouble recreating the issue because, at step 10, the Workspace Chat does not show the "new" line that @izarutskaya's test does

 

https://github.com/user-attachments/assets/57cf7d13-dff9-41db-8a6b-a1ceb82c0a20

**Comment by VictoriaExpensify** [comment] 2024-08-12 07:17
posted to Open-Source to see if Applause can reproduce it - https://expensify.slack.com/archives/C01GTK53T8Q/p1723447006955459

**Comment by VictoriaExpensify** [comment] 2024-08-15 01:59
I'm closing this because I cannot reproduce the issue as shown by @izarutskaya and I haven't had a response to the post. Please reopen if you think we should continue

**Closed by VictoriaExpensify** 2024-08-15 01:59 UTC
Labels: Daily, Overdue, Bug
