### ISSUE TITLE
MEDIUM: [$500] Unread indicator is showing in the fevicon even though there is nothing in LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31276] opened 2023-11-13 20:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699899029212629

## Action Performed:
1. Open app and login
2. Make a IOU request 
3. Open the IOU thread to see the details
4. Observe the unread indicator in expensify fevicon

## Expected Result:
If there is an unread indicator, LHN should have one unread message

## Actual Result:
But nothing in LHN with unread message. 

it was caused by this transaction thread, which wasn’t showing up in my LHN, but was considered unread by the logic being used to compute the [unread indicator here](https://github.com/Expensify/App/blob/f23efa1118f52a953dc2b109875c33b3fd206a06/src/libs/UnreadIndicatorUpdater/index.js#L11). We should update the logic of the unread indicator to make sure it matches the logic of the LHN (or even better use shared logic). So that it’s never possible to see the unread indicator when you don’t have anything unread in the LHN.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![IMG_0222](https://github.com/Expensify/App/assets/38435837/a0169f54-c73c-4fa1-9de4-bb600073f4ed)

![image (31)](https://github.com/Expensify/App/assets/38435837/c9fd048d-25f5-46c1-9dab-af8c3096d299)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d98ea368e18737bf</li>
        <li>Upwork Job ID: 1724168903941550080</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by ericuldall** [comment] 2023-11-13 23:21
# Proposal
This seems to be an issue with new reports coming in from onyx. There is no check if the change was triggered by the currently logged in user. So subscribed actions from that user will show as unread.

To fix this, we should add an additional check to verify the report was not triggered by the currently logged in user.

**Comment by paultsimura** [comment] 2023-11-14 09:09
@puneetlath could you please double-check this was not happening simply because of the Concierge chat being unread? This can be easily overseen for the new accounts.

**Comment by AmjedNazzal** [comment] 2023-11-14 09:36
I think this should be held until [this](https://github.com/Expensify/App/issues/28536#issuecomment-1773926403) is completed because it will apply changes to `UnreadIndicatorUpdater`

**Comment by cubuspl42** [comment] 2023-11-14 11:25
I think that this issue is a possible duplicate of https://github.com/Expensify/App/issues/28536, or at least has a high chance of getting solved by the associated PR

**Comment by puneetlath** [comment] 2023-11-14 17:55
@cubuspl42 indeed it does sound very similar to that. @muttmuure perhaps we can put it on hold for #31276 that and then we can have @shawnborton and others who are experiencing this re-test after #31276 is live.

**Comment by puneetlath** [comment] 2023-11-15 15:52
Lol whops, I meant https://github.com/Expensify/App/issues/28536

**Comment by cubuspl42** [comment] 2023-11-16 09:14
In case this doesn't move forward, please ping also in PR https://github.com/Expensify/App/pull/30133, as Melvin won't remind me about that issue anymore

**Comment by MonilBhavsar** [comment] 2023-11-16 13:33
Commented in the PR

**Comment by cubuspl42** [comment] 2023-11-20 13:15
[Ongoing discussion](https://github.com/Expensify/App/pull/30133#issuecomment-1818960844) on the issue found in the PR

**Comment by MonilBhavsar** [comment] 2023-11-21 11:35
PR is being reviewed

**Comment by situchan** [comment] 2023-11-24 13:13
Not overdue

**Comment by MonilBhavsar** [comment] 2023-11-27 09:13
Discussion is going on PR, looks like it has halted cc @cubuspl42

**Comment by cubuspl42** [comment] 2023-12-05 11:20
We're waiting for a review by @Gonals 🙂

**Comment by cubuspl42** [comment] 2023-12-06 11:11
https://github.com/Expensify/App/pull/30133 is merged! You're good to go 🙂 Start with re-testing.

**Comment by MonilBhavsar** [comment] 2023-12-06 11:11
PR is merged and awaiting deploy

**Comment by cubuspl42** [comment] 2023-12-06 13:46
Just so we're on the same page, we're talking about the PR associated with the issue we're holding on here 🙂 This one can be put off hold

**Comment by muttmuure** [comment] 2023-12-18 12:07
I think we can take this off hold now? @situchan what do you think of @dukenv0307's [proposal here](https://github.com/Expensify/App/issues/31276#issuecomment-1809346822)?

**Comment by situchan** [comment] 2023-12-19 17:29
> We should check for this case the same way we do in `OptionRowLHN`

@dukenv0307's proposal sounds good. But I am still testing with various accounts to validate it.

**Comment by MonilBhavsar** [comment] 2023-12-27 11:29
Proposal being tested

**Comment by muttmuure** [comment] 2024-01-02 19:19
@situchan let us know how your testing went!

**Comment by muttmuure** [comment] 2024-01-08 11:17
bump @situchan, just waiting on results from your testing: https://github.com/Expensify/App/issues/31276#issuecomment-1863202894

**Comment by situchan** [comment] 2024-01-08 11:23
@dukenv0307 I am not sure how you will apply same logic to `UnreadIndicatorUpdater`

```
    const isHidden = optionItem.notificationPreference === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN;
    if (isHidden && !props.isFocused && !optionItem.isPinned) {
        return null;
    }
```

**Comment by situchan** [comment] 2024-01-08 11:32
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/31276#issuecomment-1809346822) looks good and tests well.
🎀 👀 🎀 C+ reviewed

**Comment by MonilBhavsar** [comment] 2024-01-08 12:16
I see this is also being fixed in https://github.com/Expensify/App/pull/34025 as a regression from https://github.com/Expensify/App/pull/30133

**Comment by situchan** [comment] 2024-01-08 12:21
ok, we can put this on hold

**Comment by muttmuure** [comment] 2024-01-10 18:18
Held

**Comment by quinthar** [comment] 2024-01-11 01:51
This feels like a wave5 issue as it deals with transaction threads; reassigning.

**Comment by muttmuure** [comment] 2024-01-15 15:38
Still in review here: https://github.com/Expensify/App/pull/34025

**Comment by muttmuure** [comment] 2024-01-17 18:31
Still in review

**Comment by muttmuure** [comment] 2024-01-22 10:57
Still open

**Comment by muttmuure** [comment] 2024-01-22 12:04
Not overdue!

**Comment by muttmuure** [comment] 2024-01-23 17:32
Held

**Comment by MonilBhavsar** [comment] 2024-01-29 12:44
PR merged and deployed to production. Taking this off hold.

**Comment by MonilBhavsar** [comment] 2024-01-29 12:45
Have asked if bug is fixed or not in slack thread https://expensify.slack.com/archives/C049HHMV9SM/p1706532316571099?thread_ts=1699899029.212629&cid=C049HHMV9SM

**Comment by iwiznia** [comment] 2024-01-29 16:12
This has been working for me for a while for me https://expensify.slack.com/archives/C03U7DCU4/p1706112016224459

**Comment by muttmuure** [comment] 2024-01-30 15:10
It seems like there are a few PRs that will be eligible for payment here, I need to comb through and figure it out

**Comment by muttmuure** [comment] 2024-02-02 09:53
OK, so the linked issue was a fix for a regression - https://github.com/Expensify/App/issues/33506 so no payment there. 

We did get a proposal for this issue above, but since there was an overlap with the regression fix, there was already something solid and we actually didn't need the second proposal. 

So I am going to close this, but if you think that your work was eligible for payment despite this issue not having a linked PR, please send me a DM!

**Closed by muttmuure** 2024-02-02 09:53 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
