### ISSUE TITLE
[$500] Web and Desktop are not synced for the new chats sent

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34358] opened 2024-01-11 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @justinpersaud 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704927485668869

## Action Performed:
1. Login to same account in both Web and Desktop
2. Send a message to the above account

## Expected Result:
Both web and desktop should receive the message at the same time

## Actual Result:
Desktop and iOS receives message immediately and not web

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2d47cfb28f730b6</li>
        <li>Upwork Job ID: 1745453573031129088</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2024-01-12 01:08
I wasn't able to reproduce, I got all 3 notifications within 2 seconds of each other:

![image](https://github.com/Expensify/App/assets/59587260/9b9e6961-f234-47fe-a314-a54d28b1959b)

![image](https://github.com/Expensify/App/assets/59587260/e03e48b0-1b8c-4eab-a36a-37e6026001c7)

**Comment by jliexpensify** [comment] 2024-01-12 01:16
@justinpersaud , can you still repro this? Could it have been a temporary slowness?

**Comment by puneetlath** [comment] 2024-01-12 20:31
I think this is a dupe of https://github.com/Expensify/App/issues/33847 and we should close. Reopen if you disagree.

**Closed by puneetlath** 2024-01-12 20:31 UTC
Labels: External, Daily, Help Wanted, Bug
