### ISSUE TITLE
[$500] Details - Wrong text in tooltip on 3 dots of owes report details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29703] opened 2023-10-16 18:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697471268360179

## Action Performed:
1. Open the app
2. Open owes report or send request money request to any user and click IOU message once
3. Click in header to open details
4. Observe that we display participants as title in details
5. Hover on 3 dots in the report and observe that it displays report title text instead of displaying user list

## Expected Result:
Hover on 3 dots in owes report details should display user list as tooltip text

## Actual Result:
Hover on 3 dots in owes report details shows report title text

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/8363cfc5-c66c-4878-a559-85826c7862b2

https://github.com/Expensify/App/assets/93399543/cbbb7e12-45d6-4309-9edd-affcc6b6c89b

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/75d3188e-9b02-409d-8b77-305781b82a27

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c5b71f132322fe9</li>
        <li>Upwork Job ID: 1713984868090105856</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-16 18:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

3 dots shows the report title instead of display name list in report detail page

### What is the root cause of that problem?

We're showing the full title in the tooltip as you can see below
https://github.com/Expensify/App/blob/2fb47ac92005bcd832c24ed91df2ee043a1be51f/src/components/DisplayNames/DisplayNamesWithTooltip.js#L73

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to show display names when we don't show title
Update the above line to
```
        <Tooltip text={props.shouldUseFullTitle ? props.fullTitle : _.map(props.displayNamesWithTooltips, ({displayName}) => displayName).join(', ')}>
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/6e111a6e-ebb1-41e0-9606-17ca0d85489c


</details>


### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment] 2023-10-16 18:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

wrong tool tip display in the report details page 
### What is the root cause of that problem?


we display the report name instead of the participants list
https://github.com/Expensify/App/blob/2fb47ac92005bcd832c24ed91df2ee043a1be51f/src/components/DisplayNames/DisplayNamesWithTooltip.js#L73



### What changes do you think we should make in order to solve the problem?

use participants names instead of the report name.. to do that we can use the already existing report util function that composes the title for a given account ids: 

```js
    const participantsNames = useMemo(() => ReportUtils.getWhisperDisplayNames(participants), [participants]);
```

```js
     <DisplayNames
                                    fullTitle={participantsNames}
                                    displayNamesWithTooltips={displayNamesWithTooltips}
                                    tooltipEnabled
                                    numberOfLine
                                    s={isChatRoom && !isThread ? 0 : 1}
                                    textStyles={[styles.textHeadline, styles.textAlignCenter, isChatRoom && !isThread ? undefined : styles.pre]}
                                    shouldUseFullTitle={shouldUseFullTitle}
                                />
```

**Comment by jliexpensify** [comment] 2023-10-18 00:20
Thanks @bernhardoj - closing this!

**Closed by jliexpensify** 2023-10-18 00:20 UTC
Labels: External, Daily, Help Wanted, Bug
