### ISSUE TITLE
 Android - Expenses - "Unexpected error" when submitting track expense to someone

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52665] opened 2024-11-16 14:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Open self DM
3. Tap on the "+" button and select "Track Expense"
4. Complete the expense creation flow and send it to chat
5. On the options displayed below the expense, select "Submit to Someone"
6. Submit the expense to any other user
7. Navigate to the chat where the expense was sent
8. Open the expense report and wait for one or two minutes
9. Verify all the information is displayed correctly and no error is displayed

## Expected Result:
After creating a track expense and selecting "Submit to Someone", the expense should be submitted to the selected user without any error

## Actual Result:
"Unexpected error submitting this expense" message is displayed in expense report, a few minutes after creating a track expense and selecting the "Submit to Someone" option."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4789367d-bcaa-4124-94a9-3e7dde1ca71e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CyberAndrii** [comment] 2024-11-16 15:06
Dupe of https://github.com/Expensify/App/issues/45086

**Closed** 2024-11-19 15:25 UTC
Labels: Daily, Overdue, Bug
