### ISSUE TITLE
Chat- Unable to leave chat thread. Closing the account leads to concierge page then  to " Hmmmm it's not here page"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21117] opened 2023-06-20 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login
3. Tap on a any chat thread
4. Tap on the top area for chat info
5. Tap on leave thread option

## Expected Result:
The user should be able to leave the chat thread successfully

## Actual Result:
The user is navigated to the concierge page after tapping on leave thread option. Closing the concierge page then leads the user to " Hmmmm it's not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5a8d2d5f-e3da-49c7-a6f8-9b6e61f74d67

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2023-06-21 05:28
Dupe of https://github.com/Expensify/App/issues/20908

**Comment by JmillsExpensify** [comment] 2023-06-28 05:06
Agree with the contributor that this is a dupe.

**Closed by JmillsExpensify** 2023-06-28 05:06 UTC
Labels: Daily, Overdue, Bug
