### ISSUE TITLE
[$1000] Split Bill - Last Split Bill description within the group is displayed on all split bill detail pages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19855] opened 2023-05-30 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR**https://github.com/Expensify/App/pull/19390

## Action Performed:
1. Go to NewDot
2. Create a split bill with several users with description
3. Open group chat and create another split bill with different description
4. Open new split Details page for the first Split Bill

## Expected Result:
Description from step 2 should be displayed

## Actual Result:
Description from step 3 is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/308be96fbcf3f79db684db2be6e296224360728aeae1cc63681b405b0cea2035

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01edb91d2bc99f8597</li>
        <li>Upwork Job ID: 1663688334189305856</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-05-30 23:26
Very weird. It seems to be just taking the oldest open description:
<img width="1800" alt="image" src="https://github.com/Expensify/App/assets/9133401/9c57391a-31b6-41d6-acd7-cede7dbc57d7">

Like in this instance, it's a split with two others, but the description is the description of a split with just the two from earlier:
<img width="1800" alt="image" src="https://github.com/Expensify/App/assets/9133401/06ec8586-e841-4e69-aab6-8b512899acd0">

**Comment by BhuvaneshPatil** [comment] 2023-05-31 01:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
in Split bill detail page, the description shown is not matching with original

### What is the root cause of that problem?
For `MoneyRequestConfirmationList` we are taking `IOU` from Onyx, that is global IOU. example - When I try to create new Split Bill, the IOU will be using its description for the value. It's being set at below - 
https://github.com/Expensify/App/blob/0d1995a209218f721eb8ba123091b17d3fb29964/src/pages/iou/MoneyRequestDescriptionPage.js#L53-L56

### What changes do you think we should make in order to solve the problem?
Like we are passing the `iouAmount` to `MoneyRquestConfirmationList` component, we can pass the new prop `iouComment` from `SplitBillDetailsPage`.
https://github.com/Expensify/App/blob/0d1995a209218f721eb8ba123091b17d3fb29964/src/components/MoneyRequestConfirmationList.js#L361-L372


### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2023-05-31 08:44
Closing as a dupe of [this previously reported issue](https://github.com/Expensify/App/issues/19870). Feel free to add proposals to that issue instead.

**Closed by Julesssss** 2023-05-31 08:44 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by Julesssss** [comment] 2023-05-31 14:28
Created after, but it was raised way earlier in Slack. Better to keep the original issue rather than remember to pay out the contributor.

**Comment by esh-g** [comment] 2023-06-01 19:57
@tienifr Please review this comment: https://github.com/Expensify/App/issues/19870#issuecomment-1572682875
which is regarding a regression that can be caused if we use `props.iouComment` instead of `props.iou.comment`
