### ISSUE TITLE
[HOLD for payment 2024-01-22] [$500] Workspace - In Workspace, trying to add a number contact & selecting it, contact disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34020] opened 2024-01-05 12:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap Profile icon
3. Tap Workspaces ---- Workspace ---- Members
4. Tap invite
5. Enter a number eg: +919787766754
6. From the list, tap and select the contact

## Expected Result:
In Workspace, trying to add a number contact & selecting it, contact must not disappear

## Actual Result:
In Workspace, trying to add a number contact & selecting it, contact disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dae43a43-e2fe-4265-8d38-4623d49019b8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bf34b264efa7a44</li>
        <li>Upwork Job ID: 1743245225212407808</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Contributor | 28087732</li>
<li>dukenv0307 | Contributor | 28087733</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-05 12:52
This is a regression from https://github.com/Expensify/App/pull/31648, which is still within the regression period.

Confirmed by reverting the PR locally: 
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/12595293/e8965800-5726-4968-bdcf-e8e5f6795aa8">

cc: @abdulrahuman5196 @thienlnam

**Comment by thienlnam** [comment] 2024-01-08 02:49
Thanks Pavlo - assigning from that PR

**Comment by abdulrahuman5196** [comment] 2024-01-08 19:32
Hi, Thanks for the PR. It seems this is not a deploy blocker. So Will work on review in my morning.

**Comment by kevinksullivan** [comment] 2024-01-12 19:16
Hi @abdulrahuman5196 any update?

**Comment by abdulrahuman5196** [comment] 2024-01-12 19:24
@kevinksullivan  the PR was merged. Since this is a regression issue, we can close the issue once we verify in production after it reaches there.

**Comment by abdulrahuman5196** [comment] 2024-01-18 19:37
> the PR was merged. Since this is a regression issue, we can close the issue once we verify in production after it reaches there.

Yeah. Already pointed out here. We can close this issue.

**Closed** 2024-01-19 05:45 UTC
Labels: External, Weekly, Awaiting Payment, Bug
