### ISSUE TITLE
Web - The user is able to send the message with more than 15,000 characters

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26468] opened 2023-09-01 10:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Insert a text exceeding 15,000 characters in the text box
2. Add an emojis
3. Hit backspace to remove the space

## Expected Result:
Send button should remain disabled with a message indicating the number of inserted characters

## Actual Result:
The user is able to send the message with more than 15,000 characters

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[limit-bug-n.webm](https://github.com/Expensify/App/assets/93399543/45d9acd1-fcb5-4ffb-9e4f-7c24b4f7e350)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692880491617199
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2023-09-01 23:11
I guess in theory the problem is that we're not counting the **actual** character amount after the user deletes the backspace and preventing them from sending. But this is...really edge case. Closing it

**Closed by adelekennedy** 2023-09-01 23:11 UTC
Labels: Daily, Needs Reproduction, Bug
