### ISSUE TITLE
[$500] LHN shows tag as @email@domain.com instead of @person

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36284] opened 2024-02-09 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707498095462179

## Action Performed:
1. Go to any public room
2. Mention any user in the message

## Expected Result:
LHN should show @person
## Actual Result:
Shows as @email@domain.com
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-02-09 at 9 01 38 AM](https://github.com/Expensify/App/assets/38435837/b4153c1c-f57d-4748-b3f8-2e06a8e8df45)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c3d81a0688971b8</li>
        <li>Upwork Job ID: 1756047410853744640</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-09 20:29
Can I get confirmation of this behaviour?
We are explicitly coding to display the users login info in the composer after picking the user, not the display name

**Comment by jeremy-croff** [comment] 2024-02-09 21:29
Is this a bug?
I find client side support for this here: https://github.com/Expensify/App/pull/26877
But no record of the api sending the account_id or the client setting the account_id to map to @person

**Comment by jeremy-croff** [comment] 2024-02-09 21:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Show @Person mentions in LHN

### What is the root cause of that problem?
Seems we have no accountID on the <user-mention> html object we send and retrieve.

### What changes do you think we should make in order to solve the problem?
We can start sending the accountid of the mentioned user inside the <user-mention> node so that https://github.com/Expensify/App/pull/26877 works as expected.

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-02-12 15:14
Not overdue. Will look at this more today

**Comment by joekaufmanexpensify** [comment] 2024-02-13 22:03
[Discussing ](https://expensify.slack.com/archives/C03U7DCU4/p1707861789821059?thread_ts=1707788860.271399&cid=C03U7DCU4)

**Comment by joekaufmanexpensify** [comment] 2024-02-14 21:17
Confirmed in Slack that this should be fixed by https://github.com/Expensify/Expensify/issues/313934 , closing in favor of that issue!

**Closed by joekaufmanexpensify** 2024-02-14 21:17 UTC
Labels: External, Daily, Help Wanted, Bug
