### ISSUE TITLE
[HOLD for payment 2024-01-28] CRITICAL: [$500] Switching from most recent to #focus shows already-read chats in the LHN

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#34466] opened 2024-01-12 23:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** No
**Email or phone of affected tester (no customers):** All
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705098619607699

## Action Performed:
_Precondition: User must have several conversations and no unread chats. Priority mode is set to Most Recent_

1. Refresh the page
1. Without taking other actions - Navigate to preferences and enable #focus in priority mode

## Expected Result:
Only the current report should be visible in the LHN

## Actual Result:
The LHN remains unchanged (or at least, many unread chats remain visible in the LHN)

## Workaround:
If the user takes other actions before refreshing, the issue is not reproduced. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/44479856/409705fc-4957-4006-8e6a-b3bff90dfe56

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111ebc2af8eb5ed14</li>
        <li>Upwork Job ID: 1745951096565080064</li>
        <li>Last Price Increase: 2024-01-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28106614</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by abzokhattab** [comment] 2024-01-13 00:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigating through unread reports doesnt remove them after being read in focus mode
### What is the root cause of that problem?

in this PR we introduced performance enhancments in the rerendering process of the LHN list  https://github.com/Expensify/App/pull/27364 

the enhancement basically included this primary change where a check was defined that if the current report id is not in the previous rendered list then we need to rerender, else we assume that the list is the same however this is not true in the case of "focus mode" since in the foucs mode if you open an unread report then navigates to another report, the prev report should be execluded from the list:

```js
https://github.com/janicduplessis/Expensify-App/blob/1edf8cb2fecf83c0943ea9c19be9e8ed4ee6ccd1/src/pages/home/sidebar/SidebarLinksData.js#L84C1-L95C1
```
 
### What changes do you think we should make in order to solve the problem?

we need to add another condition that the old report is still shown in the list after switching to another report: 
this can be done by using the `shouldReportBeInOptionList` function which tells if a report should be in the option list or not:   

```js
// first we need to get the prev currentreportid value
const oldReportID = usePrevious(currentReportID);
```

then rewrite the `optionListItemsWithCurrentReport` to be 
```js
    const optionListItemsWithCurrentReport = useMemo(() => {
        const oldReport = oldReportID ? chatReports[oldReportID] : null;
        const shouldOldReportBeShown = ReportUtils.shouldReportBeInOptionList(oldReport, currentReportID, priorityMode === CONST.PRIORITY_MODE.GSD, betas, policies, true);
        if ((currentReportID && !_.contains(optionListItems, currentReportID)) || (oldReportID && !shouldOldReportBeShown)) {
            return SidebarUtils.getOrderedReportIDs(currentReportID ?? '', chatReports, betas, policies, priorityMode, allReportActions);
        }
        return optionListItems;
    }, [oldReportID, chatReports, currentReportID, priorityMode, betas, policies, optionListItems, allReportActions]);

```


or an alternative solution would be to revert the pr changes and use on useMemo on the `SidebarUtils.getOrderedReportIDs` function

**Comment by bernhardoj** [comment] 2024-01-13 07:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Switching from the most recent fo #focus mode still shows all read chats

### What is the root cause of that problem?
When we change the priority mode, it will recalculate the chats that should be shown on the LHN.
https://github.com/Expensify/App/blob/753ce92ea9a1858dd2d576eeff692df527ea3ecb/src/pages/home/sidebar/SidebarLinksData.js#L75-L88

It will first compare with the existing list whether something has changed or not, then, we will only get the updated list IF the app is not loading (!isLoading).

However, we have an issue where the `isLoading` onyx data is stuck at true. This happened before because we are ignoring the `successData` and `failureData` if the [onyx updates from the server haven't changed](https://github.com/Expensify/App/pull/33666), then we fix it by making sure both [`successData` or `failureData` is always applied even when that case happen](https://github.com/Expensify/App/pull/34006).

But this problem arose again because, in https://github.com/Expensify/App/pull/33530, we are adding a new property called `finallyData` that we haven't included the case yet for the onyx update ignore fix.

### What changes do you think we should make in order to solve the problem?

We should include `finallyData` to be processed even when the onyx updates from the server haven't changed.
https://github.com/Expensify/App/blob/753ce92ea9a1858dd2d576eeff692df527ea3ecb/src/libs/actions/OnyxUpdates.ts#L87-L95

```
|| !isEmptyObject(request.finallyData)
```
----
<details>

<summary>Another issue:</summary>

But another thing I notice with this switching mode is that the list could be late to be updated because we ignore the updates if `isLoading` is true which I think makes sense when we load the app for the first time because we want to wait for the OpenApp API to be fully complete first.
https://github.com/Expensify/App/blob/753ce92ea9a1858dd2d576eeff692df527ea3ecb/src/pages/home/sidebar/SidebarLinksData.js#L84-L86

However, this becomes a problem when we switch from focus to most recent because it will also call [OpenApp](https://github.com/Expensify/App/blob/753ce92ea9a1858dd2d576eeff692df527ea3ecb/src/libs/actions/App.ts#L62-L65), so if we switch from focus -> most recent -> focus, we will see all read chats in the 2nd focus mode for a few seconds before the OpenApp completes.

https://github.com/Expensify/App/assets/50919443/03799dec-df98-42b2-9e5a-142de64aa815


We can fix this by adding another condition that checks if the priority mode is updated, then we will update the list.
```
const prevPriorityMode = usePrevious(priorityMode)

if (... || (prevPriorityMode !== priorityMode))
    // update the list
}
```
</details>

**Comment by zanyrenney** [comment] 2024-01-15 18:52
@parasharrajat please review the proposal and let me know what you think.

**Comment by quinthar** [comment] 2024-01-17 01:23
Added to #vip-vsb, thanks so much for taking this on!  It's blocking https://github.com/Expensify/App/issues/33619, which is a pretty important one.

**Comment by zanyrenney** [comment] 2024-01-17 13:01
asked here - https://expensify.slack.com/archives/C01GTK53T8Q/p1705494618062199

**Comment by dangrous** [comment] 2024-01-17 19:05
This sounds great! Assigning.

**Comment by quinthar** [comment] 2024-01-18 02:09
What's the ETA for this?

**Comment by bernhardoj** [comment] 2024-01-18 04:00
PR should be up soon

**Comment by bernhardoj** [comment] 2024-01-18 04:31
PR is ready

cc: @parasharrajat

**Comment by zanyrenney** [comment] 2024-01-18 10:54
awesome, thanks @bernhardoj @parasharrajat please prioritise the review.

**Comment by quinthar** [comment] 2024-01-19 01:03
What's the ETA for review?

**Comment by bernhardoj** [comment] 2024-01-19 03:19
The PR is merged

**Comment by dangrous** [comment] 2024-01-19 15:38
Yep! This is on staging now, being QAd

**Comment by garrettmknight** [comment] 2024-01-24 15:43
@parasharrajat I'm trying to figure out whether the PR that caused this is right. https://github.com/Expensify/App/issues/34466 was discovered in v1.4.24-7 and the [deploy blocker slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1705101622781029?thread_ts=1705098619.607699&cid=C049HHMV9SM) shows it in production. https://github.com/Expensify/App/pull/33530 was deployed to staging in 1.4.24-4, to production in 1.4.24-8. Are you sure that's the right one?

**Comment by garrettmknight** [comment] 2024-01-26 18:49
@parasharrajat bump on the above

**Comment by dangrous** [comment] 2024-01-29 20:41
So based on the solve, as well as this being a user (Expensify employee) reported bug, I think this may be one of those bugs that's been there pretty much since the beginning, we maybe just didn't notice it? [We didn't appear to have regression tests that would catch it](https://expensify.slack.com/archives/C049HHMV9SM/p1705098796040559?thread_ts=1705098619.607699&cid=C049HHMV9SM) so it'll be unclear when it started. 

That might be a cop out, though - I didn't investigate too long - but it feels like it might be the case

**Comment by dangrous** [comment] 2024-02-01 16:48
let me know what you think of that ^ @garrettmknight and @parasharrajat.

**Comment by dangrous** [comment] 2024-02-02 15:31
Yeah I think it's kind of a mix - the bug existed likely since the beginning, and then that linked PR _could_ have fixed it but didn't since it didn't apply the onyx updates for finallydata

**Comment by garrettmknight** [comment] 2024-02-06 20:04
Hey @dangrous - no need to investigate further. We're good to pay out here.

**Comment by dangrous** [comment] 2024-02-07 14:44
> For reference, here are some details about the assignees on this issue:
> 
> * @parasharrajat requires payment through NewDot Manual Requests
> * @bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28106614) (Contributor)

Great! @zanyrenney we're ready to go here - thanks!

**Comment by zanyrenney** [comment] 2024-02-08 16:26
Thanks @danieldoglas

**Comment by zanyrenney** [comment] 2024-02-08 16:27
payment summary:

@parasharrajat requires payment through NewDot Manual Requests - please request $500 for this issue
@bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28106614) (Contributor)**** paid $500 via upwork!

**Closed by zanyrenney** 2024-02-08 16:27 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 03:41
$500 approved for @parasharrajat
