### ISSUE TITLE
[MEDIUM] Backwards Compatibility: "Billable no longer valid" appears in Manual but not Scan request when disabled

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34765] opened 2024-01-18 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace that has billable option enabled by default.
1. Go to workspace chat.
2. Create a manual request and a scan request, both with billable toggled on.
3. As admin, disable billable option on Old Dot.
4. As employee, go to request details page of manual request and scan request.

## Expected Result:
"Billable no longer valid" will appear under Billable section in both manual and Scan request.

## Actual Result:
"Billable no longer valid" appears in the manual request but not Scan request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8c1bffd2-0e57-404c-b8be-9cb2d46bba33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-01-18 22:13
Not a blocker as its minor and nobody is using the collect in newdot yet

**Comment by yuwenmemon** [comment] 2024-02-07 19:04
Assigned to another Critical issue in this Wave so going to unassign and add the Hot Pick tag.

**Comment by yuwenmemon** [comment] 2024-02-09 02:37
Picking this back up as I'm free now again!

**Comment by greg-schroeder** [comment] 2024-02-20 05:26
I guess this is backwards compatibility issue given the nature of how to reproduce it, but it's not really critical functionality and the error message is only missing in one place (yet present elsewhere). I'll call this one out in the update and see what people think about priority.

**Comment by greg-schroeder** [comment] 2024-02-20 18:41
Tossing a `Hot Pick` on this as Yuwen is working on something else right now - if anyone has bandwidth they could jump in instead! 

context: https://expensify.slack.com/archives/C02MW39LT9N/p1708453585539349

**Comment by cristipaval** [comment] 2024-02-23 20:14
I got the confirmation from @cead22 on Slack, that all violations are hidden until the SmartScanning is done. This is by design. I tested that the violation related to the Billable field appears when the SmartScanning is done, and it works well.

I'll close the issue.

**Closed by cristipaval** 2024-02-23 20:14 UTC
Labels: Engineering, Daily, Improvement
