### ISSUE TITLE
[HOLD for payment 2023-06-29] [HOLD for payment 2023-06-28] [$1000] Search - Group chat displays blank in Search results

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21127] opened 2023-06-20 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with HT account or any account where you have a lot of group conversation
3. Click on magnify glass and scroll the page

## Expected Result:
Group chat displays without issue

## Actual Result:
Group chat displays blank in Search result

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-6

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5bcd6f13-f8d4-4b72-aeac-41a63796bd91

https://github.com/Expensify/App/assets/93399543/f99ec154-a883-4675-b00c-428954b603c1

![image (73)](https://github.com/Expensify/App/assets/93399543/a121f2d4-6948-4897-9bc2-5045512030c7)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01541118f633ad9ca1</li>
        <li>Upwork Job ID: 1671222841055092736</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by Beamanator** [comment] 2023-06-20 16:15
Looks still reproducible in staging & `main`

**Comment by Beamanator** [comment] 2023-06-20 16:15
(@amyevans I'm not planning to look into the fix for now, let me know if you need me to)

**Comment by amyevans** [comment] 2023-06-20 16:38
Thanks, I can repro on `main` too, taking a closer look

**Comment by jeet-dhandha** [comment] 2023-06-20 16:54
<img width="935" alt="Screenshot 2023-06-20 at 10 23 51 PM" src="https://github.com/Expensify/App/assets/78416198/4a63fe4e-b5c3-4a0b-b819-0d7c1bd2412b">

Its a basic change. We had to pass participantsList when we have a list of participants.

**Comment by jeet-dhandha** [comment] 2023-06-20 16:55
## Before:
<img width="375" alt="Screenshot 2023-06-20 at 10 25 27 PM" src="https://github.com/Expensify/App/assets/78416198/b52bcebf-6d16-4c38-9d5b-421390360c08">

## After:
<img width="379" alt="Screenshot 2023-06-20 at 10 25 04 PM" src="https://github.com/Expensify/App/assets/78416198/b7b09791-1294-4e1c-af45-384e3eb1e0be">

**Comment by amyevans** [comment] 2023-06-20 17:20
@jeet-dhandha Your fix isn't working in my local tests
![Screenshot 2023-06-20 at 1 18 42 PM](https://github.com/Expensify/App/assets/7277067/624df6ab-9b5c-4c8d-8c78-d385a6a8c3ff)
(this.props.option.accountID is 0)

**Comment by Beamanator** [comment] 2023-06-20 17:32
@amyevans just checking which account has `option.accountID` of `0`? It should almost never be 0 ideally 😬

**Comment by amyevans** [comment] 2023-06-20 17:40
@Beamanator this is the data (I'm not clear yet where that data flows from, so can't say more than that at the moment - maybe it's just bad local data somehow?):
![Screenshot 2023-06-20 at 1 38 27 PM](https://github.com/Expensify/App/assets/7277067/66515e14-fa21-47d6-9cf6-466cad68edb0)

@Pujan92 that condition worked for me 👍 , how does it look to you @Beamanator? (cc @luacmartins)

**Comment by Beamanator** [comment] 2023-06-20 17:42
Ooh @Pujan92 that could be correct 🙃 

Sadly I'm able to see this bug @amyevans but am investigating another bug, let me know if you need me to help with this one, but seems we may be on track for the fix already 🙏

**Comment by amyevans** [comment] 2023-06-20 17:51
@Pujan92 do you have capacity/interest in putting together a PR for this fix quickly?

If not, I will handle once I'm out of a meeting in about 30-40 min.

**Comment by Pujan92** [comment] 2023-06-20 17:52
Yes @amyevans , I can raise a PR now for the fix.

**Comment by luacmartins** [comment] 2023-06-20 17:52
So the `accountID` is 0 because we default it to 0 [here](https://github.com/Expensify/App/blob/8ba223457b9a2e8d02f1c57d7c21fd7f0c523573/src/libs/OptionsListUtils.js#L422), but we only set it the report doesn't have multiple participants [here](https://github.com/Expensify/App/blob/8ba223457b9a2e8d02f1c57d7c21fd7f0c523573/src/libs/OptionsListUtils.js#L510). Is that the expected behavior @Beamanator?

**Comment by Beamanator** [comment] 2023-06-20 17:55
Aah interesting @luacmartins - I believe I only default to `0` cuz I thought that made sense, but seeing that everything else starts out as `null` maybe the `accountID` should NOT start as `0` - good find

**Comment by luacmartins** [comment] 2023-06-20 17:57
I think it's fine to initialize with 0 or null, but what do we want to store for group chats?

**Comment by Beamanator** [comment] 2023-06-20 17:59
I guess we'd use `result.participantsList` for group chats?

**Comment by Pujan92** [comment] 2023-06-20 18:04
Yes, currently due to this condition `(this.props.option.participantsList || this.props.option.accountID ? [this.props.option] : []).slice(0, 10),`
It always pass either `this.props.option` or `[]`, so wrapping with `()` the second condition solves the issue and pass `this.props.option.participantsList` when it is available.

**Comment by luacmartins** [comment] 2023-06-20 18:08
@Pujan92 feel free to tag me as a reviewer too

**Comment by amyevans** [comment] 2023-06-20 21:32
Tested on staging, looks good -
![staging-test](https://github.com/Expensify/App/assets/7277067/b2b3c056-0581-477e-aa7f-e5eff84b2e99)

**Comment by luacmartins** [comment] 2023-06-20 22:11
Thank you!

**Comment by joekaufmanexpensify** [comment] 2023-06-26 12:58
This qualifies for [a speed bonus](https://github.com/Expensify/App/issues/21127#issuecomment-1599358159), so we need to issue the following payments here: 

- @Pujan92 - $1,500 ($1,000 for PR, and $500 speed bonus). 
- @allroundexperts - $1,500 ($1,000 for review, and $500 speed bonus). 
- No reporting bonus here.

**Comment by joekaufmanexpensify** [comment] 2023-06-26 12:59
@Pujan92 offer sent for $1,000 ($500 will be issued as bonus)

**Comment by joekaufmanexpensify** [comment] 2023-06-26 13:00
@allroundexperts Could you please complete your portion of the BZ checklist when you have a chance? Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-06-27 21:16
All set to issue payment soon once the BZ checklist is complete.

**Comment by amyevans** [comment] 2023-06-29 12:48
I don't think we need a regression test specific to this case, Group Chat flows have plenty of regression tests already and blank text would be very obvious to the testers already without calling it out as a separate item.

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:48
BZ checklist is complete! All set to issue payment.

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:50
@Pujan92 $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:51
@allroundexperts $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:51
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:52
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-06-29 18:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
