### ISSUE TITLE
[$1000] 2FA - When logging in with Sign in with Google, the system does not require 2FA confirmation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30216] opened 2023-10-23 22:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
The account must have 2FA enabled
1. Open New Expensify app
2. Sign in through the "Sign in with Google" function with the prepared account

## Expected Result:
When 2FA is enabled, the system should always ask you to enter the 2FA confirmation code when you sign in

## Actual Result:
When logging in with Sign in with Google, the system does not require 2FA confirmation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/4713d70c-ff8d-45d4-99ca-9ab409670272

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d1144dfd0a56dbe</li>
        <li>Upwork Job ID: 1726584499867627520</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by krobinsmith** [comment] 2023-10-23 22:38
Hello
You can add one more step to login process.

**Comment by sonialiap** [comment] 2023-10-30 14:59
Looking for proposals

**Comment by sonialiap** [comment] 2023-11-03 12:14
I'm doubling the price of this issue to $1000. We're still looking for proposals

**Comment by b4s36t4** [comment] 2023-11-03 14:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
2FA - When logging in with Sign in with Google, the system does not require 2FA confirmation
### What is the root cause of that problem?

This issue have multiple root causes in which there are few backend changes also do require.

1. If we login through google/apple we're directly getting logged in (means we're getting `authToken` response from backend), even if the `requiresTwoFactorAuth` is `true`

2. We don't have any direct/plausible way to verify the 2FA, `SignInUser` with 2FA code is not working, we need to update the backend to handle 2FA verification without OTP verification before.

3. Update the frontend to show the verification screen if there is 2FA required.


### What changes do you think we should make in order to solve the problem?

First two changes are related backend, this should be internal.

For the frontend change, below are required changes.

1. Save the method of login, `isSSOLogin` to figure out if the login is from third party provider.

2. Update the `getRenderOptions` function and update the condition inside the function. https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/signin/SignInPage.js#L130

```jsx
const shouldShowValidateCodeFormForSSO = hasAccount && isSSOLogin && !isUnvalidatedSecondaryLogin;

return {
    /// returns
shouldShowValidateCodeForm: shouldShowValidateCodeForm || shouldShowValidateCodeFormForSSO,
}

```



### What alternative solutions did you explore? (Optional)
NA

cc: @sonialiap @0xmiroslav

**Comment by sonialiap** [comment] 2023-11-06 11:08
"Back end", sounds like this is calling for an `internal` label. @marcochavezf will you be able to assist on this issue?

**Comment by marcochavezf** [comment] 2023-11-13 20:27
No update, but I will keep this on my radar for this week

**Comment by marcochavezf** [comment] 2023-11-20 04:01
I think we're also not requiring 2FA for SSO in OldDot, correct?

**Comment by marcochavezf** [comment] 2023-11-21 22:44
Moving this to weekly since we don't have 2FA in OldDot and focused on wave7

**Comment by marcochavezf** [comment] 2023-12-01 16:36
No update, still focused on critical items for wave7

**Comment by marcochavezf** [comment] 2023-12-11 19:32
No update

**Comment by sonialiap** [comment] 2023-12-15 17:11
Confirmed in [slack](https://expensify.slack.com/archives/C02MW39LT9N/p1702651848106519) that this is expected behavior. Not a bug 🚫 🐛

**Closed by sonialiap** 2023-12-15 17:11 UTC
Labels: Engineering, Weekly, Internal, Bug
