### ISSUE TITLE
email address displayed in tooltip goes out of border when hovering over images

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20992] opened 2023-06-18 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new group by clicking the plus sign and choosing "New group".
2. Add an email with a long email address to the group.
3. Click on the email's profile to open the detail section on the right.
4. Hover over the email and then over the photo. When hovering over the photo, the email displayed on the tooltip goes out of the border, while when hovering over the email, the email address is displayed properly.

## Expected Result: 
When hovering over images, the email should not go out of the tooltip border like it does when hovering over the email.
## Actual Result: 
When hovering over images, the email address goes out of the tooltip border and does not display properly like it does when hovering over the email.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (14).webm](https://github.com/Expensify/App/assets/43996225/537a3247-c622-4442-a92d-9ae13b1bd5df)

https://github.com/Expensify/App/assets/43996225/872dd40e-0463-47cc-a55b-32a7c4bdc45a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687022265639079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-06-19 18:39
Closing in favor of https://github.com/Expensify/App/issues/20839. I also could not reproduce this in staging nor production
![Screenshot 2023-06-19 at 12 39 28 PM](https://github.com/Expensify/App/assets/22219519/c4a5adfc-f8bd-431b-8206-8292a7475a0d)

**Closed by luacmartins** 2023-06-19 18:39 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug

**Comment by chiragsalian** [comment] 2023-06-19 19:08
I cannot reproduce the issue either. I tested in group member section on staging,
![image](https://github.com/Expensify/App/assets/14356145/e377e658-df45-4a0a-b392-306ec76e5541)
