### ISSUE TITLE
[HOLD App#18604] [$1000] Deleting a request money message shows a empty last message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18861] opened 2023-05-12 19:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open chat > Request money
2. After requesting delete it

## Expected Result:
Deleting a request money message should not display a empty last message.
## Actual Result:
Deleting a request money message shows a empty last message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.1
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f8eb4b50-4f82-4917-b356-13433ca46545

https://github.com/Expensify/App/assets/43996225/541a7f17-8d7c-4d62-a39f-75404df5b077

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683906942740509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b71f19dcccb67b54</li>
        <li>Upwork Job ID: 1657138400751517696</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-12 19:04
@trjExpensify @JmillsExpensify @luacmartins @mountiny @Julesssss @cristipaval tagging as per this [comment](https://expensify.slack.com/archives/C049HHMV9SM/p1683917647419189?thread_ts=1683906942.740509&cid=C049HHMV9SM) in the slack

**Comment by joekaufmanexpensify** [comment] 2023-05-12 19:44
Reproduced on staging. 


https://github.com/Expensify/App/assets/54866469/9ceae38e-00b4-41f3-8ce5-e876f456a4a7

**Comment by joekaufmanexpensify** [comment] 2023-05-12 19:45
@Julesssss LMK if your plan is to keep this internally, and I'll add that label to the issue.

**Comment by trjExpensify** [comment] 2023-05-12 21:39
This can go external 👍

**Comment by s-alves10** [comment] 2023-05-13 17:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty row is added when delete a request money message.

### What is the root cause of that problem?

Now we don't show `Reqeust bill` actions with `total = 0` as you can see below. We only show the latest action as shown in the description video(`settled up`).
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/ReportActionItem/IOUPreview.js#L134-L136

This works fine but the main reason for this issue is here.
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/home/report/ReportActionItem.js#L292-L304

The `content` is empty, but we have its style `styles.chatItem`. Its value is:
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/styles/styles.js#L1415-L1422
The `padding` style makes the empty row visible.

### What changes do you think we should make in order to solve the problem?

1. Add `isIOUActionNotShown` function to `ReportActionsUtils.js`. This function would return true if the given action should be hidden.
2. In `ReportActionItem.js`, if the action should be hidden, the `render` function have to return `null`.

```
  if (ReportActionUtils.isIOUActionNotShown(this.props.report.reportID, this.props.reportActions, this.props.action)) {
     return null;
  }
```
4. These fixes would affect the group displaying. We need to fix the `displayAsGroup` props of `ReportActionItem`.
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/home/report/ReportActionsList.js#L127


### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-05-13 17:58
I am not sure if this is best solution @s-alves10 because we will move the requests to the iou/expense reports with [this PR](https://github.com/Expensify/App/pull/18604)

I will put this on hold for that PR so we can see if its reproducible there

**Comment by Julesssss** [comment] 2023-05-15 10:44
Agree with holding.

**Comment by joekaufmanexpensify** [comment] 2023-05-16 19:01
@luacmartins Awesome, does that mean we can close this?

**Comment by luacmartins** [comment] 2023-05-16 22:52
@joekaufmanexpensify can we check if this is still reproducible before closing?

**Comment by trjExpensify** [comment] 2023-05-16 22:54
How can you delete @luacmartins when we don't have the transaction view sorted yet, it's just empty?

**Comment by luacmartins** [comment] 2023-05-16 23:02
You can hover the IOUPreview in the IOU/Expense report and the context menu should show the delete option.

**Comment by trjExpensify** [comment] 2023-05-16 23:07
Nada on staging:

<img width="1129" alt="image" src="https://github.com/Expensify/App/assets/16232057/338e2d36-cece-4a55-8036-8a4bcd7b5f7c">

**Comment by trjExpensify** [comment] 2023-05-16 23:21
Okay, gave it a refresh and I can see the trash can now. Tested in a workspaceChat and a DM, still something wonky going on:

https://github.com/Expensify/App/assets/16232057/2a194879-6b7a-415b-a626-051a30b01871

**Comment by joekaufmanexpensify** [comment] 2023-05-17 14:13
I agree it's still a bit wonky, but the bug reported in this issue is fixed, no? There is no longer an empty last message. 

The settled up 0.00 alongside showing the cash request for 30.00 as completed feels a bit odd, but it feels like that's a different bug, if it is one.

**Comment by trjExpensify** [comment] 2023-05-18 16:26
Correct, there is no longer an empty last message.

**Comment by luacmartins** [comment] 2023-05-18 17:16
Yea, we can close this.

**Closed by luacmartins** 2023-05-18 17:16 UTC
Labels: External, Daily, Help Wanted, Bug
