### ISSUE TITLE
[$500] LHN - Expense details report title does not show the amount in LHN after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32382] opened 2023-12-01 21:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31302
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat > + > Request money
3. Create a manual expense
4. Open manual expense details page and send a message
5. Open another chat and send a message (if on web and desktop app)
6. Log out
7. Log in

## Expected Result:
The title for expense details report in LHN shows the correct amount

## Actual Result:
The title for expense details report in LHN does not show the amount at all after relogin. It only shows the amount after opening the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/49d0e205-d249-4192-9e1a-5f0bef351275

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c05b0ef5839e23d</li>
        <li>Upwork Job ID: 1731684125096988672</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-12-02 22:36
I don't think this is blocker. Staging is even better than production which shows nothing in LHN title

### Before opening reports:

#### Staging:

<img width="372" alt="Screenshot 2023-12-03" src="https://github.com/Expensify/App/assets/108292595/ea7ff558-fae3-48f2-918d-e6e10cb6a493">

#### Production:

<img width="372" alt="Screenshot 2023-12-03" src="https://github.com/Expensify/App/assets/108292595/2af5a333-6ec2-41ec-8f10-1274aad65348">

#### After reverting #31302:

<img width="372" alt="Screenshot 2023-12-03" src="https://github.com/Expensify/App/assets/108292595/73a5b919-1f30-44e7-806c-5359eb2daf2f">


### After opening reports:

<img width="372" alt="Screenshot 2023-12-03" src="https://github.com/Expensify/App/assets/108292595/e0a1e78e-3dce-4e8f-a51a-580e22742bfc">

**Comment by situchan** [comment] 2023-12-04 14:41
The solution is limited. I don't think of any better solution in frontend just to show "Request" unless backend supports something for that.
cc: @puneetlath since you managed https://github.com/Expensify/App/issues/30687

**Comment by shubham1206agra** [comment] 2023-12-08 08:19
@joelbettner Bump here

**Comment by tsa321** [comment] 2023-12-12 01:06
## Proposal

#### Please re-state the problem that we are trying to solve in this issue.

In LHN, the title or name of chat thread of IOU request doesn't display full text after user logout then login

####  What is the root cause of that problem?

When user logut then login, the back end doesn't return all transactions data and when LHN is rendered the getTransactionReportName will fall in this section: 

https://github.com/Expensify/App/blob/86a2521cd0e299800a100c5b002a4f08730b670d/src/libs/ReportUtils.ts#L1900-L1902

#### What changes do you think we should make in order to solve the problem?

We could use reportAction message data instead of displaying `Request`.
The code could be something like:
`return reportAction.message[0].html;`
in that line instead of `return Localize.translateLocal('iou.request');`

#### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-12-14 11:13
@joelbettner bump

**Comment by puneetlath** [comment] 2023-12-14 18:34
I think this behavior is expected, right @fedirjh @tienifr ?

**Comment by joelbettner** [comment] 2023-12-14 20:21
Sorry...I'm just tied down with some other work before I can get to making those changes in `OpenApp`.

**Comment by joelbettner** [comment] 2023-12-18 17:51
I'm going to close this for now and this is the currently the intended bahavior. Perhaps the issue can be re-visited in the future if we change what our intended behavior is like.

**Closed by joelbettner** 2023-12-18 17:51 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue
