### ISSUE TITLE
[HOLD for payment 2023-09-20] [HOLD for payment 2023-09-12] [$1000] Fix the logic to check Start and Finish waypoints

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26583] opened 2023-09-02 21:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a workspace chat
2. Click on the "+" icon next to the text composer
3. Select "Request money" and then choose "Distance"
4. Select the starting and finishing points
5. Click on "Add stop". Don't save an address for this new waypoint/stop.
6. Proceed by clicking the "Next" button.
7. Check that a route line is not drawn on the map on the confirmation page when it should. Click "Save" on the next screen
8. Check the error message that appears on the request preview.

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.62-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (feature is not available on staging yet)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693689189765409

https://github.com/Expensify/App/assets/98560306/742b929a-e9d8-4463-9cbf-5762b954674c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd9ea344375ece26</li>
        <li>Upwork Job ID: 1698087422245027840</li>
        <li>Last Price Increase: 2023-09-02</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26471457</li>
<li>situchan | Contributor | 26483019</li>
</ul></li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-09-02 21:37
Double the price because this is a regression from Wave 5 project that needs an urgent fix

**Comment by Pujan92** [comment] 2023-09-02 21:58
@hayata-suenaga what is the expected result here?

**Comment by hayata-suenaga** [comment] 2023-09-02 22:29
I'm checking with the exact requirement with the internal team right now. I'll get back to you soon after a quick discussion.

**Comment by JmillsExpensify** [comment] 2023-09-02 23:05
For this case of someone entering two waypoints, and no further valid waypoints, we want to:

 - Allow user to tap `Next` only on `Start` and `Stop` have waypoints and all other subsequent waypoints are invalid
 - On tapping `Next`, discard all subsequent invalid waypoints, so there is just a start and finish (for this case of only entering two waypoints)

The same logic would also apply to the case where someone has entered three waypoints, with invalid waypoints mixed it. So for instance, valid `Start` and `Stop`, with an invalid additional `Stop` but a valid `Finish`. If the user taps next then we'll save the valid `Start`, `Stop`, and `Finish` and discard the one invalid `Stop`. 

This approach optimizes for not requiring extra steps of the user even if they accidentally "fat finger" an extra stop. Any questions, please let us know.

**Comment by hayata-suenaga** [comment] 2023-09-02 23:19
yes I think yours accomplish the requirements @allroundexperts let's do this 🚀

**Comment by JmillsExpensify** [comment] 2023-09-02 23:27
Woo! Thank you. ❤️

**Comment by Pujan92** [comment] 2023-09-03 03:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Allow empty middle added stops to proceed user with the flow

### What is the root cause of that problem?
Currently, we don't have specific conditions to allow empty add stops for the user convenience. 

### What changes do you think we should make in order to solve the problem?

I am assuming the below points need to be incorporated

1) Start and End waypoint should be mandatory
2) If start and end waypoint is provided then ignore the empty middle stops
3) Validate the waypoint with the previous available waypoint, not the exact previous waypoint if it is empty
4) After passing through the above conditions, pass the valid waypoints for the `getRoute` api call

**Changes**

- Update `validateWaypoints` function
https://github.com/Expensify/App/blob/e088539f32561dca5e0490300bd9e5684cd54d04/src/libs/TransactionUtils.js#L292-L316

```
function validateWaypoints(waypoints) {
    const waypointValues = _.values(waypoints);

    // Ensure the number of waypoints is between 2 and 25
    if (waypointValues.length < 2 || waypointValues.length > 25) {
        return false;
    }

    // Ensure first and last waypoint is available
    if(!waypointValues[0] || !waypointValues[waypointValues.length-1]) {
        return false;
    }

    let previousFilledWaypoint = waypointValues[0];

    for (let i = 1; i < waypointValues.length; i++) {
        const currentWaypoint = waypointValues[i];
        previousFilledWaypoint = waypointValues[i - 1] || previousFilledWaypoint;

        // Check for adjacent waypoints with the same address
        if (previousFilledWaypoint && currentWaypoint.address === previousFilledWaypoint.address) {
            return false;
        }
    }

    return true;
}
```

- Pick only valid waypoints for api call

https://github.com/Expensify/App/blob/e088539f32561dca5e0490300bd9e5684cd54d04/src/components/DistanceRequest.js#L158

```
Transaction.getRoute(iou.transactionID, _.pick(waypoints, waypoint => !_.isEmpty(waypoint)));
```

**Comment by Pujan92** [comment] 2023-09-03 04:58
I know the issue gets assigned, but trying to cover more cases [here](https://github.com/Expensify/App/issues/26583#issuecomment-1703996357). Kindly consider it if it makes sense.

**Comment by situchan** [comment] 2023-09-03 05:04
> Or kept visible (only ignored for calculation)

I think this is fine and it also respects user's waypoints edition. No need to make logic complex

> I know the issue gets assigned, but trying to cover more cases https://github.com/Expensify/App/issues/26583#issuecomment-1703996357. Kindly consider it if it makes sense.

I think `Start`, `Stop`, `Finish` are just a matter of copy. Each of them are just one of waypoints.
So first valid waypoint can be "Start" point, last valid waypoint can be "Finish" point

**Comment by Pujan92** [comment] 2023-09-03 05:11
Ok, so aren't we allowing the empty waypoints between filled waypoints? I thought for eg. When first and third waypoints filled we need to ignore the second one.

**Comment by hayata-suenaga** [comment] 2023-09-04 03:31
@JmillsExpensify

@situchan (C+) helped with the review along with @ntdiary (C+)

**Comment by JmillsExpensify** [comment] 2023-09-04 22:55
Cool, noted.

**Comment by JmillsExpensify** [comment] 2023-09-04 22:56
Looks like we have another follow-up PR though?

**Comment by hayata-suenaga** [comment] 2023-09-25 07:19
@ntdiary / @allroundexperts / @situchan could any of you complete the bug zero checklist please 🙇

**Comment by hayata-suenaga** [comment] 2023-09-26 04:40
I also feel like regression test is not necessary. I agree with @ntdiary

**Comment by JmillsExpensify** [comment] 2023-10-07 21:35
Alright thanks! Here's the payment summary then:

 - Issue reporter: N/A
 - Contributor: @allroundexperts $1,000
 - Contributor+: @ntdiary $200
 - Contributor+: @situchan $800

Is this agreeable with everyone?

**Comment by situchan** [comment] 2023-10-08 03:26
This is eligible for bonus.
There were 2 PRs we worked for this GH: https://github.com/Expensify/App/pull/26591, https://github.com/Expensify/App/pull/26705 and both were within 3 business days considering merge freeze period.

So
Contributor: @allroundexperts $1,500
Contributor+: @ntdiary $300
Contributor+: @situchan $1200
If everyone agrees?

**Comment by JmillsExpensify** [comment] 2023-10-08 13:28
@hayata-suenaga Can you confirm that you agree with this summary?

**Comment by hayata-suenaga** [comment] 2023-10-09 01:48
assignment 9/3
first PR open 9/3 merge 9/4
second PR open 9/5 merge 9/6

**Comment by JmillsExpensify** [comment] 2023-10-09 18:03
Great thanks. Updated payment summary. 

 - Issue reporter: N/A
 - Contributor: @allroundexperts $1,500
 - Contributor+: @ntdiary $300
 - Contributor+: @situchan $1200

**Comment by JmillsExpensify** [comment] 2023-10-09 18:03
$1,500 payment approved for @allroundexperts based on summary above.

**Comment by situchan** [comment] 2023-10-09 18:04
I already have offer accepted - https://github.com/Expensify/App/issues/26583#issuecomment-1704560100

**Comment by JmillsExpensify** [comment] 2023-10-09 18:16
I'm not seeing any other outstanding offers/contracts, though send me a link if there are.

**Comment by JmillsExpensify** [comment] 2023-10-09 18:19
Everyone has been paid out though, so closing this issue!

**Closed by JmillsExpensify** 2023-10-09 18:19 UTC
Labels: External, Weekly, Awaiting Payment, Bug
