### ISSUE TITLE
[$500] Distance - Receipt opens Not here page instead of e-receipt when Distance is created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31138] opened 2023-11-09 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Have at least two saved addresses.
1. Launch New Expensify app.
2. Go offline
3. Go to workspace chat > + > Distance
4. Create a distance request offline
5. Go to distance request details page
6. Click on the receipt

## Expected Result:
Ereceipt is shown with pending map

## Actual Result:
Not here page is displayed
On web, the receipt shows e-receipt with pending map when the request is created offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e0b46228-9913-4f68-83c5-df220cba4fca

https://github.com/Expensify/App/assets/78819774/e4fef6c4-92f9-460e-ac61-dc5f423667c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b7e5a74d81069f4</li>
        <li>Upwork Job ID: 1722650432215658496</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27899043</li>
<li>dukenv0307 | Contributor | 27899044</li>
</ul></li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-09 17:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attachment modal won't load when offline on a native app.

### What is the root cause of that problem?
We're strictly comparing a number and a string to find the attachment index here:
https://github.com/Expensify/App/blob/ba1af3bdc20ad876e0c92d0618d1c63ad359cd3d/src/components/Attachments/AttachmentCarousel/index.native.js#L39

### What changes do you think we should make in order to solve the problem?

Convert `attachment.source` to a string before comparing.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by s77rt** [comment] 2023-11-10 11:30
@dukenv0307 Thanks for the proposal. Your RCA is correct. Fixing this at the highest level looks good here i.e. the alternative solution.

```js
const decodedSource = decodeURI(_.get(props, ['route', 'params', 'source']));
const source = Number(decodedSource) || decodedSource;
```

If the source is a string of numbers then it's assumed we imported an image asset. In this case the source is supposed to be a number.


🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/31138#issuecomment-1804215476)

**Comment by s77rt** [comment] 2023-11-10 11:33
@erquhart Thanks for the proposal but it seems to be a dupe.

**Comment by s77rt** [comment] 2023-11-13 08:59
@joelbettner https://github.com/Expensify/App/issues/31138#issuecomment-1805563930

**Comment by s77rt** [comment] 2023-11-20 13:29
@joelbettner ^

**Comment by s77rt** [comment] 2023-11-27 14:05
@joelbettner ^

**Comment by joelbettner** [comment] 2023-11-30 15:55
Proposal looks good. I assigend @dukenv0307.

Sorry for the delay. I was OOO and been catching up on things since I was out.

**Comment by s77rt** [comment] 2023-12-01 15:18
We have a selected proposal, Melvin

**Comment by s77rt** [comment] 2023-12-27 15:46
PR was deployed to production 3 weeks ago. Seems like the auto process failed here.

**Comment by s77rt** [comment] 2024-02-05 02:44
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/20167
- The offending PR has been commented on: https://github.com/Expensify/App/pull/20167#discussion_r1477599069
- A discussion in #expensify-bugs has been started: Not needed. Such bugs could be caught during offline testing.
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Go offline
2. Create a distance request
3. Go to the transaction report of that request
4. Click on the receipt image
5. Verify that receipt image loads correctly

(Related https://expensify.testrail.io/index.php?/cases/view/2661872 and https://expensify.testrail.io/index.php?/cases/view/2730072)

**Comment by strepanier03** [comment] 2024-03-20 15:28
Sorry about this, it was still set to Monthly and went under the radar.

**Comment by strepanier03** [comment] 2024-03-20 15:51
Thank you both so much for your patience and I'm sorry about the delay here. If you ever notice automation failing and the GH is staying in Monthly or Weekly, you can ping me in Slack right away and I'll switch the label. Frankly, there's just too many GHs every day to be able to check through Weeklies, let alone Monthlies, so I am relying heavily on automation to float things up that need my attention. 

I've paid you both and created the reg test GH as well. Going to close this out.

**Closed by strepanier03** 2024-03-20 15:51 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
