### ISSUE TITLE
[RUSHAT to complete checklist] [$500] Web - Emoji picker - Holding down on scroll bar and sliding down selects emoji instead of scrolling

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33709] opened 2023-12-28 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a conversation
2. Click on the emoji picker
3. Hold down on the scroll bar on the right of the emoji picker
4. Try to slide down while holding down the scroll bar

## Expected Result:
The side bar should be able to scroll down

## Actual Result:
Instead of scrolling down the performed action results in selecting the emoji categories

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/67d8782c-92dc-4017-83e8-a3a274bd04de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0bac704c1843b72</li>
        <li>Upwork Job ID: 1740375313641885696</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by ayushjha119** [comment] 2023-12-28 14:50
@kbecciv i can start working on this.... can you assign this to me??

**Comment by dragnoir** [comment] 2023-12-28 19:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Sticky header overlaps scroll bar.

### What is the root cause of that problem?

 The Sticky header from `FlashList` overlaps scroll bar.
 The 1st part of the scroll bar is overlapped and user can't click on it.

### What changes do you think we should make in order to solve the problem?

Change the style of the [StickyHeader children](https://github.com/Expensify/App/blob/d1649148f200b0fa4d4b09bad56b343c5b285927/src/components/EmojiPicker/EmojiPickerMenu/index.js#L338) (because we don't have access to style the StickyHeader div) to give space for the scroll bar.
```js
<View  style={[styles.emojiHeaderContainer, target === 'StickyHeader' ? styles.stickyHeaderEmoji : undefined]}>
```
where StickyHeader is:
```
stickyHeaderEmoji: {
	position:  'absolute',
	width:  '-webkit-fill-available',
	...spacing.mh4,
},
```

**Comment by dragnoir** [comment] 2023-12-28 20:03
To support all browsers we can use the below:
```js
  width: '100%',
  width: '-webkit-fill-available',
  width: '-mos-available',
  width: 'fill-available',
```

**Comment by jliexpensify** [comment] 2023-12-29 00:26
Can repro, let DB know in #vip-vsb [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1703809573978779)

**Comment by dragnoir** [comment] 2023-12-29 05:02
@tienifr you are copying my proposal. You're just trying to calcylate width with js.

**Comment by dragnoir** [comment] 2023-12-29 06:19
@tienifr the hard part is how to override the parent absolute position without having access to it.
Assigning absolute position to a child **is my idea and the 1st who mentioned it**. You jsu calculated width in a different way.

I also mentioned how to make fill for all browsers.

**Comment by dragnoir** [comment] 2023-12-29 06:59
@rushatgabhane @jliexpensify I am a new contributor and it's mentioned [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)

> _Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable._

Also I was watched lots of proposals and I am sure details like how to handle or how the team prefer to calculate width can be discussed throw PR. (Unless the proposal is wrong and it's not the case here)

In my propsal I figured our the route cause problem and as you can see [here](https://github.com/Shopify/flash-list/issues/540) lots of other developers was not able to figure out how to style the StickyHeader and how to eliminate the absolute position. 
My solution, assigning absolute to a child to override the width of an absolute parent, is the main key to solve the issue. And I am sure the second proposal difference is not important, meaningful or considerable as mentioned in the contribution guide.

**Comment by dragnoir** [comment] 2023-12-29 08:35
> I believe putting width: 100% will break the current behavior.

 Please check how CSS Overriding works.

**Comment by jliexpensify** [comment] 2024-01-02 02:03
Bump @rushatgabhane for reviews please!

**Comment by rushatgabhane** [comment] 2024-01-02 20:23
@dragnoir thank you for the proposal. Your root cause looks good but I'm not a fan of the solution.

**Comment by dragnoir** [comment] 2024-01-02 20:25
@rushatgabhane you don't like the "absolute" solution?

**Comment by rushatgabhane** [comment] 2024-01-02 20:36
> you don't like the "absolute" solution

i think that's fine. Everything in RN is set to `relative` by default, so `absolute` positioning is always relative to the parent. And that is what is what we want to do.

**Comment by rushatgabhane** [comment] 2024-01-02 20:37
Instead of `width:  '-webkit-fill-available'`, i would calculate the width because it's know to us.

**Comment by dragnoir** [comment] 2024-01-02 20:41
@rushatgabhane setting the width is a side part of the solution.
The main part is how to cancel the absolute style of the parent without having access to it. Assigning absolute to the child is the main solution.
Calculating width can be done with many solutions,
`-webkit-fill-available` means fill the available space - margin/padding and we already set 16px margin in right and left. Technicall is not wrong but as you mentioned, the Expensify team prefer maybe the js way

**Comment by rushatgabhane** [comment] 2024-01-02 20:41
I recommend that we assign @dragnoir because they had the correct [root cause and a solution](https://github.com/Expensify/App/issues/33709#issuecomment-1871437437) that fixes the root cause.

A [nitpick](https://github.com/Expensify/App/issues/33709#issuecomment-1871727444) was pointed by @tienifr to calculate the width as it's know to us.

So we should use` width: isSmallScreenWidth ? windowWidth - 32: 288` as suggested by @tienifr 

C+ reviewed 🎀 👀 🎀

**Comment by marcochavezf** [comment] 2024-01-03 23:48
> @rushatgabhane @marcochavezf As I can see your comment [here](https://github.com/Expensify/App/issues/33709#issuecomment-1874523970), we should combine 2 proposals. Can I and @dragnoir colab in this issue? Thanks

Yeah, that sounds good to me :oneteam:, Assigning both 🚀

**Comment by jliexpensify** [comment] 2024-01-03 23:50
@marcochavezf curious how this works for Payments: do both @tienifr and @dragnoir get paid $250 each?

**Comment by marcochavezf** [comment] 2024-01-03 23:56
Yeah I think that would be fair since the ultimate solution includes parts of both proposals, what do you think @rushatgabhane @tienifr @dragnoir?

**Comment by marcochavezf** [comment] 2024-01-04 19:22
Given that we don't have guidelines about more than one contributor working together in a PR, @dragnoir could you raise the PR with the changes and @tienifr could you help @dragnoir with the screenshots? Let me know if that works for both 🙇🏽

**Comment by dragnoir** [comment] 2024-01-06 19:09
@marcochavezf PR ready https://github.com/Expensify/App/pull/34077

**Comment by jliexpensify** [comment] 2024-01-22 23:33
^ well that is new!

As discussed:

- @dragnoir $250
- @tienifr $250
- @rushatgabhane $500

[Upwork Job](https://www.upwork.com/jobs/~01c0bac704c1843b72)

Bump for Rushat to complete the checklist please!

**Comment by jliexpensify** [comment] 2024-01-22 23:36
Just awaiting everyone to accept in Upworks and I shall pay out.

**Comment by dragnoir** [comment] 2024-01-23 08:16
Thank you. Accepted.

**Comment by jliexpensify** [comment] 2024-01-24 02:24
Paying now - p.s. @dragnoir in the future, no need to submit work! We'll pay when the due date has passed.

**Comment by jliexpensify** [comment] 2024-01-24 02:25
Paid and job removed.

@rushatgabhane bump to complete the checklist please!

**Comment by jliexpensify** [comment] 2024-01-29 00:09
@rushatgabhane bump to complete the checklist

**Comment by rushatgabhane** [comment] 2024-01-29 06:11
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by marcochavezf** [comment] 2024-01-29 17:53
Hi @jliexpensify, I think the checklist was the only pending item here, correct?

**Comment by jliexpensify** [comment] 2024-01-29 23:08
Yep @marcochavezf - contributors have been paid and job is now closed.

Checklist is a WIP, so I'll close once Rajat updates it.

**Closed** 2024-01-30 02:20 UTC
Labels: External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-01-30 18:23
$500 payment approved for @rushatgabhane based on [this summary](https://github.com/Expensify/App/issues/33709#issuecomment-1905023075).
