### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] Console error on click of the paypal payment method where Make default payment method option isn’t available(Error: `Invalid prop style supplied to Button`)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19752] opened 2023-05-29 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Goto Settings -> Payments
2. Click on paypal method
3. Observe the console error in the devtools

## Expected Result: 
Console error should not be occurred
## Actual Result: 
Console error occurs

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** needs reproduction
**Reproducible in staging?:**  needs reproduction
**Reproducible in production?:**  needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f8b27f61-c0d8-4b43-a31d-3927d582a8f2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684427630067449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011825e5129fec9a46</li>
        <li>Upwork Job ID: 1663730404176728064</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-29 17:45
Proposal by @Pujan92 

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Console error on click of the paypal payment method where `Make default payment method` option isn’t available
### What is the root cause of that problem?
For the button style we are passing the empty array here when default button option isn’t available for it, whereas in the button we are expecting style prop to be `PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.object), PropTypes.object])`
https://github.com/Expensify/App/blob/cb6ba23ea1e99a3b332983568ee8e9aa0c2a09dd/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L477
https://github.com/Expensify/App/blob/cb6ba23ea1e99a3b332983568ee8e9aa0c2a09dd/src/components/Button/index.js#L76
### What changes do you think we should make in order to solve the problem?
We need to pass an empty object either in the array or separately to fulfill the required prop types.
```
style={[shouldShowMakeDefaultButton ? styles.mt4 : {}]}
```
OR
```
style={shouldShowMakeDefaultButton ? styles.mt4 : {}}
```

**Comment by JmillsExpensify** [comment] 2023-05-31 02:13
Not sure what's going on here and it's DEV so I'm going to go ahead and open this one up.

**Comment by Web-Go-To** [comment] 2023-05-31 14:46
Hello,
Based on the error message, it looks like there is an issue with how the `style` property is being used in the `Button` component. It is possible that the `style` property is being supplied an incorrect value type, or it has not been defined.
To fix this error, I can take the following steps:
1. I will check the `Button` component's code implementation to ensure that the `style` property is defined as an object type. The `style` property value must be an object containing CSS style properties and values.
2. I will check the usage of `Button` component is passing an object as the value of the `style` property. And I will ensure that the object supplied contains valid CSS style properties and values. 
For example:
```
<Button
  style={{ backgroundColor: 'blue', color: 'white', padding: '10px' }}
  onClick={handleClick}
>
  Click Me
</Button>
```
In the example above, the `style` property is being supplied with an object containing valid CSS style properties to apply the corresponding styling to the button. 
3. I will check the React documentation on PropTypes and ensure that the correct type is defined in the `Button` component's prototype.

**Comment by Web-Go-To** [comment] 2023-05-31 14:59
Contributor details
Your Expensify account email: yanaworkem@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0125148e869fb3679c

**Comment by Web-Go-To** [comment] 2023-05-31 15:10
Hello,
Based on the error message, it looks like there is an issue with how the style property is being used in the Button component. It is possible that the style property is being supplied an incorrect value type, or it has not been defined.
To fix this error, I can take the following steps:

I will check the Button component's code implementation to ensure that the style property is defined as an object type. The style property value must be an object containing CSS style properties and values.
I will check the usage of Button component is passing an object as the value of the style property. And I will ensure that the object supplied contains valid CSS style properties and values.
For example:
<Button
  style={{ backgroundColor: 'blue', color: 'white', padding: '10px' }}
  onClick={handleClick}
>
  Click Me
</Button>
In the example above, the style property is being supplied with an object containing valid CSS style properties to apply the corresponding styling to the button.
3. I will check the React documentation on PropTypes and ensure that the correct type is defined in the Button component's prototype.

**Comment by NikkiWines** [comment] 2023-06-01 23:52
Yep, agreed. @Pujan92's proposal looks good! 🚀

**Comment by Pujan92** [comment] 2023-06-02 18:43
> @Pujan92, i believe you need to comment in this issue before I can assign you to it 🙇

Ok, Done. I will raise a PR once it gets assigned to me. Thanks!

**Comment by Pujan92** [comment] 2023-06-03 14:09
@mollfpr @NikkiWines [PR](https://github.com/Expensify/App/pull/20117) is ready for review!

**Comment by JmillsExpensify** [comment] 2023-06-08 03:42
@mollfpr we still have plenty of time, though ahead of the regression ending, would appreciate you checking off the items above. Thank you!

**Comment by mollfpr** [comment] 2023-06-08 06:21
@JmillsExpensify yup, I will finish it today. Thanks for the reminder!

**Comment by mollfpr** [comment] 2023-06-12 17:09
Sorry for the delay @JmillsExpensify 🙏

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/13648

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/13648/files#r1226974514

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Soon we will migrate to TS, which warns in the editor. Also, it should be caught while reviewing the PR.

> [@mollfpr] Determine if we should create a regression test for this bug.

Yes!

>[@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Goto Settings -> Payments
2. Click on the Paypal method
3. **Verify** there isn't any console error
4. 👍 or 👎

**Comment by Pujan92** [comment] 2023-06-22 06:03
Bump @JmillsExpensify :)

**Comment by JmillsExpensify** [comment] 2023-06-26 18:54
Thanks guys! Sorry for the delay. Jumping in now.

**Comment by JmillsExpensify** [comment] 2023-06-26 19:18
Summarizing payments, this is what I'm seeing:

 - Issue reporter: @Pujan92 $250
 - Contributor: @Pujan92 $1,500
 - Contributor+: @mollfpr $1,500

I've invited you both to the [Upwork job](https://www.upwork.com/jobs/~011825e5129fec9a46). Bonuses will be paid out when payment is issue, with the offer now including the base.

**Comment by Pujan92** [comment] 2023-06-26 19:22
Thanks @JmillsExpensify , Accepted!

**Comment by JmillsExpensify** [comment] 2023-06-26 19:52
Also, I disagree that we should add a regression test for console errors. I think this one is out of scope.

**Comment by JmillsExpensify** [comment] 2023-06-26 19:53
@Pujan92 You're all set! I added the bonus on final payment.

**Comment by JmillsExpensify** [comment] 2023-06-27 04:49
Alright, everyone has been paid out at this point and I don't think a regression test is in scope. Closing this issue out.

**Closed by JmillsExpensify** 2023-06-27 04:49 UTC
Labels: External, Daily, Awaiting Payment, Bug
