### ISSUE TITLE
[$500] IOU - Web - The error for the date is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34917] opened 2024-01-22 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211871
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

1. Click on the + button > Request money> Scan
2. Upload a picture that will fail the scan
3. Add two participants
4. Wait for the scan to fail
5. Click on the split preview

## Expected Result:
The merchant, date and amount fields should contain in-line field errors

## Actual Result:
The error for the date is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6350894_1705948826201!image__2_](https://github.com/Expensify/App/assets/78819774/67e88d6a-2e34-449a-a03d-c47cac8a2dd8)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189ebab509492601c</li>
        <li>Upwork Job ID: 1749516979752669184</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-22 19:40
We think that this bug might be related to[#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by jeremy-croff** [comment] 2024-01-22 20:04
Seems like NBA because the fields have a valid default value. It's common to default to the current date until entered for example.

Is there a requirement to not have default values for scanned receipts?

**Comment by lschurr** [comment] 2024-01-24 22:53
@eVoloshchak could you take a look at this one?

**Comment by eVoloshchak** [comment] 2024-01-24 23:05
I agree with @jeremy-croff's [comment](https://github.com/Expensify/App/issues/34917#issuecomment-1904718633), doesn't look like a bug. There's a valid date. 

What is the expected result in this case? What should the error say?

**Comment by eVoloshchak** [comment] 2024-01-29 11:04
Not overdue, same as above

**Comment by lschurr** [comment] 2024-01-31 16:35
Hmm just so I understand, are we thinking this is expected and not a bug @eVoloshchak?

**Comment by eVoloshchak** [comment] 2024-02-03 17:47
@lschurr, yeah, that is correct

**Comment by lschurr** [comment] 2024-02-05 19:28
Closing this since we believe it's expected behavior.

**Closed by lschurr** 2024-02-05 19:28 UTC
Labels: External, Daily, Help Wanted, Bug
