### ISSUE TITLE
mWeb/Chrome - Expenses - The Save button on the Merchant page is unresponsive in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54671] opened 2024-12-30 21:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.79-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5389852
**Issue reported by:** Applause - Internal Team
**Component:** Money Requests

## Action Performed:
New user has created a new workspace by selecting "Manage my team expenses" and has started their onboarding checklist.

1. Go offline by disabling the internet connection in the device settings (not from the Troubleshot page)
2. Go to the workspace chat automatically created
3. Tap on + button > Create expense
4. Enter any amount
5. Enter a merchant
6. On the Merchant page, tap the Save button

## Expected Result:
The Save button leads to the Confirm details page and the merchant is displayed in the Merchant field

## Actual Result:
The Save button on the Merchant page is unresponsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2842586b-60ab-43c7-bd21-291ad324ac18

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by blimpich** [comment] 2024-12-30 22:24
Fairly minor. Not sure if this should be considered a blocker. I'll look into it though, there a few suspicious PRs that might make this an easy fix.

**Comment by blimpich** [comment] 2024-12-30 23:43
Working on this. Doesn't repo in web, issue says it only repos in Android mweb. Currently having trouble getting my local Android mweb up and running.

**Comment by blimpich** [comment] 2024-12-31 00:17
Alright I finally got mweb working, reproduces on main. Testing suspicious PRs to see if reverting them fixes the issue.

**Comment by blimpich** [comment] 2024-12-31 00:24
Confirmed it is this PR: https://github.com/Expensify/App/pull/53529. Reverting it fixed the issue. Going to revert.

**Comment by huult** [comment] 2024-12-31 00:25
PR fixed this issue already to merge

**Comment by huult** [comment] 2024-12-31 00:26
@blimpich herể is the pull request https://github.com/Expensify/App/pull/54634

**Comment by blimpich** [comment] 2024-12-31 00:31
Ah I see. Looks like this issue is basically a dupe. Since I don't consider this super high priority and we already have a fix on the way I'm just going to remove the deploy blocker and mark this as a dupe of https://github.com/Expensify/App/issues/54609

**Closed by blimpich** 2024-12-31 00:31 UTC
Labels: DeployBlockerCash, Engineering, Hourly
