### ISSUE TITLE
[HOLD #23959] Web - RHN - Opening RHN after opening the emoji picker will keep the composer focused

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25584] opened 2023-08-21 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Open emoji picker
3. Click on profile avatar

## Expected Result:
The composer should not be focused.

## Actual Result:
The composer is focused and can type on it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/5bf8ab71-8c52-4eae-ad5d-6501f3cfb12f

https://github.com/Expensify/App/assets/115492554/a24d8734-4bf8-4d05-a181-de402caec2e2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @getusha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691746780206579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-08-21 14:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - RHN - Opening RHN after opening the emoji picker will keep the composer focused 
### What is the root cause of that problem?
When emoji picker popover is closed it is automatically focusing to composer, and this line is responsible for this:
https://github.com/Expensify/App/blob/cea152bc582aa0cf405756ac77779f948811b4a9/src/pages/home/report/ReportActionCompose.js#L1234
### What changes do you think we should make in order to solve the problem?
I think this logic causes a lot of unexpected focuses in composer, like it is not just RHN but pressing anything after opening emoji picker results in the same. For example pressing search after emoji picker causes focus to be in composer and not in search page, or pressing FAB you can't use up/down buttons because focus is still in composer.

That is why, I think we should completely get rid of this logic. 
But we should modify here: https://github.com/Expensify/App/blob/cea152bc582aa0cf405756ac77779f948811b4a9/src/pages/home/report/ReportActionCompose.js#L1235
So that when emoji is picked we focus back in composer
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2023-08-30 00:51
Thanks @bernhardoj for the context
Going to put on hold pending https://github.com/Expensify/App/issues/23959

**Comment by mallenexpensify** [comment] 2023-09-05 02:19
Updated title and moved to weekly

**Comment by mallenexpensify** [comment] 2023-09-19 09:43
Still on hold
- https://github.com/Expensify/App/issues/23959

**Comment by mallenexpensify** [comment] 2023-10-04 17:34
Holding on upstream

**Comment by mallenexpensify** [comment] 2023-10-14 00:36
Still holding

**Comment by mallenexpensify** [comment] 2023-10-25 13:42
No progress on upstream hold
- https://github.com/Expensify/App/issues/23959

**Comment by mallenexpensify** [comment] 2023-11-03 23:42
^ same

**Comment by mallenexpensify** [comment] 2023-11-14 22:51
^ same same, upstream hold

**Comment by mallenexpensify** [comment] 2023-11-28 21:02
Still held upstream
- https://github.com/Expensify/App/issues/23959

**Comment by mallenexpensify** [comment] 2023-12-12 23:16
Same ^

**Comment by mallenexpensify** [comment] 2023-12-23 18:38
Hold

**Comment by mallenexpensify** [comment] 2024-01-03 02:05
HOld

**Comment by mallenexpensify** [comment] 2024-01-17 03:09
Still holding
- https://github.com/Expensify/App/issues/23959

**Comment by mallenexpensify** [comment] 2024-01-31 02:01
hold

**Comment by mallenexpensify** [comment] 2024-02-13 23:46
Still on hold

**Comment by mallenexpensify** [comment] 2024-02-24 01:44
hold

**Comment by mallenexpensify** [comment] 2024-03-04 18:55
Still held but other issue is making progress
- https://github.com/Expensify/App/issues/23959#issuecomment-1975610966

**Comment by mallenexpensify** [comment] 2024-03-13 02:10
Still on hold
- https://github.com/Expensify/App/issues/23959

**Comment by mallenexpensify** [comment] 2024-03-27 02:25
Holding

**Comment by mallenexpensify** [comment] 2024-04-10 01:52
Bumped to monthly cuz held issue was bumped to monthly
- https://github.com/Expensify/App/issues/23959
-

**Comment by mallenexpensify** [comment] 2024-05-15 01:25
Holdin'

**Comment by mallenexpensify** [comment] 2024-06-19 01:10
Waiting for feedback on 
- https://github.com/Expensify/App/issues/23959

**Comment by mallenexpensify** [comment] 2024-07-24 01:40
PR for issue we're held on is waiting review
https://github.com/Expensify/App/issues/23959#issuecomment-2244215044

**Comment by mallenexpensify** [comment] 2024-08-28 00:52
UI is drastically changed since this was reported over a year ago, closing, unable to reproduce

**Closed by mallenexpensify** 2024-08-28 00:52 UTC
Labels: Weekly, Bug, retest-weekly
