### ISSUE TITLE
[Awaiting payment] [$1000] Web - Compose box is distorted and messages are not loaded on reload after expand in compose box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21881] opened 2023-06-29 16:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the NewExpensify app at https://staging.new.expensify.com
3. Click on an existing compose box or create a new compose box from a chat or task
4. Shift enter in compose box to enable expand button > press enter a few times to make the compose box window wide
5. Click on expand button
6. Reload and observe that expand button and + button in compose box are distorted and app does not load the chats

## Expected Result:
App should load the chats and display expanded view on reload when we expand compose box and reload

## Actual Result:
 App does not load the chats and compose box is distorted when we expand compose box and reload

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f330c59b-b2a4-4b96-919e-bfffd8b8bbe9

https://github.com/Expensify/App/assets/93399543/b522fc37-a160-41d2-a3f1-9d9942c6c140

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687948877344299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb137372e1458408</li>
        <li>Upwork Job ID: 1674819530237825024</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-30 16:37
I can reproduce it - seems to only be affecting Mac/Chrome/Safari. Adding external label

**Comment by pasyukevich** [comment] 2023-07-03 08:39
Hi,
I am from Callstack - an expert contributor group
I start to investigate this issue

**Comment by pasyukevich** [comment] 2023-07-04 13:12
Hi @Christinadobrzyn 

Am I able to continue my investigation? 
I was able to reproduce this issue and started some investigation.

**Comment by pasyukevich** [comment] 2023-07-05 15:21
Found some dependency between the isSidebarLoaded and isComposerFullSize flags. 
Looks like isComposerFullSize prevents updating the isComposerFullSize if they are placed in the same component. 

Created Slack thread related to this behavior.  https://expensify.slack.com/archives/C01GTK53T8Q/p1688570107740179

**Comment by Christinadobrzyn** [comment] 2023-07-05 20:08
Hired in Upwork: 
Internal job: https://www.upwork.com/ab/applicants/1674819530237825024/job-details
External job: https://www.upwork.com/jobs/~01cb137372e1458408

@aimane-chnaif as C+
@dhanashree-sawant as reporter

Let me know when we should add an eng label @aimane-chnaif

**Comment by pasyukevich** [comment] 2023-07-06 15:33
Found a few ways how to fix this issue.  
I continue my investigation by looking for a better one.

**Comment by pasyukevich** [comment] 2023-07-07 15:08
Found a  better solution how to fix this issue. 
I am preparing the proposal.

**Comment by Christinadobrzyn** [comment] 2023-07-07 21:42
@pasyukevich is preparing the proposal!

**Comment by pasyukevich** [comment] 2023-07-10 13:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we are trying to solve is the constant loading state for the content of the report after expanded composer and page reloading.
### What is the root cause of that problem?
This issue is connected with Onyx behavior. It does not work as expected.

`withOnyx` HOC does not update boolean values that are initialized from the storage for components that are mounting not first. (I was able to reproduce constantly the same behavior in any components except the root - `Expensify.js`)
This reproduces in case there are boolean values that are already defined in the indexDb storage and stay the same till the full page rendering. (In such case another value, that was actually updated, would not be updated in the described component and will stay the same as the initial value)

The report loading state depends on the `isSidebarLoaded` value. To show content the `isSidebarLoaded` should be true.
In this flow `isSidebarLoaded` stay false inside the report while actually it is already updated to true for others.

In this case, `isComposerFullSize` blocks any updates of the `isSidebarLoaded` value.

I was also able to reproduce this with the collapsed and expanded composer. (it occurs when `reportIsComposerFullSize_...` is defined with value true/false/undefined in the indexDB for the current report)

Any of the proposed changes can be only a kind of workaround. I consider that after such fixes this issue should be fixed inside the Onyx library.
### What changes do you think we should make in order to solve the problem?
Disable initialization of the `isSidebarLoaded` flag with stored value in the `withOnyx` hook by adding `"initWithStoredValues: false"` (`ReportScreen`). In this case, all updates will be triggered normally.
### What alternative solutions did you explore?
Pass isSidebarLoaded from the upper component.

**Comment by pasyukevich** [comment] 2023-07-10 13:52
I guess this issue is related to this one - https://github.com/Expensify/App/issues/22122 

Based on the information that I got from the issue description and Slack thread to the issue I assume that the root cause of the problem is the same - Onyx library. I am more than sure that it can be fixed in the same way as I described here. (before it will be patched on the Onyx side)

**Comment by Christinadobrzyn** [comment] 2023-07-10 21:02
Asking for a review of combining these issues - https://github.com/Expensify/App/issues/22122#issuecomment-1629726677

**Comment by Julesssss** [comment] 2023-07-11 08:20
> Based on the information that I got from the issue description and Slack thread to the issue, I assume that the root cause of the problem is the same - the Onyx library. I am more than sure that it can be fixed in the same way as I described here. (before it will be patched on the Onyx side)

Sounds good to me. I'll hold the other issue.

**Comment by Julesssss** [comment] 2023-07-11 08:22
I'm happy to go ahead and assign you @pasyukevich. It would be great if you can raise one PR with the fix (linking it to this issue and the [Emulator issue](https://github.com/Expensify/App/issues/22122)), and depending on how many other potential instances of the initialization bug maybe we can bundle the others into the same PR.

**Comment by pasyukevich** [comment] 2023-07-12 11:29
@Julesssss 

After implementing and checking the proposed approach I found out that the main approach broke the `isSidebar` logic on mobile/mobile web platforms.  

Rechecked the alternative solution using the same flow - everything works well. To fix this issue, the isSidebar flag should be passed from the upper component (`ReportScreenWrapper`).

  At the same time, the main proposal should work well for the other issue that is connected to the splash screen. 

  I believe that both approaches are workarounds. 
After the fixes, I want to continue the investigation with the Onyx library and fix the root cause. Once the root cause is fixed, both of these fixes should be reverted.

Can I continue with this updated direction?

**Comment by Julesssss** [comment] 2023-07-12 12:27
Hey @pasyukevich. Given the issues aren't suuuuuper critical maybe we can just hold in that case and focus on the underlying issue?

**Comment by pasyukevich** [comment] 2023-07-12 12:45
Sure, @Julesssss. In this case, I will focus on the investigation of the underlying issue.

**Comment by Julesssss** [comment] 2023-07-12 12:59
Cool. I'll keep you assigned and will just put a hold on this for now.

**Comment by pasyukevich** [comment] 2023-07-14 16:38
Hi @Julesssss,

I'm not able to reproduce this issue locally and on the stage after the update of the ReportScreenWrapper to a functional component. (Now it has more re-renders and they just force React to update the ReportScreen.)

However, I'm still able to reproduce this issue elsewhere.
I'm continuing my investigation of the underlying issue by looking for a root cause.

**Comment by Christinadobrzyn** [comment] 2023-07-14 18:33
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're on hold looking for the root cause - I'll assign this back to me when I'm back.

**Comment by Julesssss** [comment] 2023-07-17 12:44
PR in draft still

**Comment by conorpendergrast** [comment] 2023-07-19 20:56
@pasyukevich Any success in uncovering the underlying cause?

**Comment by pasyukevich** [comment] 2023-07-20 11:22
@conorpendergrast I've identified the root cause. As previously suspected, the issue is linked to Onyx updating the flow during loading.

**Comment by pasyukevich** [comment] 2023-07-20 11:23
@Julesssss Should I proceed to open a separate issue specifically for the Onyx repository and formulate a proposal within that context?

**Comment by Julesssss** [comment] 2023-07-20 12:16
Hey @pasyukevich, no we can discuss that here! Please share your findings

**Comment by pasyukevich** [comment] 2023-07-20 12:56
@Julesssss 

Issue connected with Onyx flow.   It becomes reproducible when the state is updated with value before the setWithOnyxState call. 

Step-by-step flow  based on this issue (ReportScreen):  
	1. withOnyx setState called with ({ isSidebarLoaded: true }) while loading: true. (this.state = { loading: true, isSidebarLoaded: true })
	2. setWithOnyxState called with isComposerFullSize: true
        3. setWithOnyxState checked that loading: true and ignored the current state. (this.state = { loading: true, isSidebarLoaded: true })
        4. Updated value of this.state with   {...this.tempState, loading: false}; (this.state = { loading: false, isSidebarLoaded: false,  isComposerFullSize: true, ………… } )  
        
        
So in this flow updated state was ignored, I was able to fix this problem just by updating this.setState inside the setWithOnyxState with the additional spreading of the current state.

  This issue is already not reproducible on the ReportScreen but I’m able to constantly reproduce that behavior if move the component with the same two flags upper the ReportWrapper.

**Comment by Julesssss** [comment] 2023-07-20 14:58
Excellent, thank you! Please go ahead and raise the PR and we can review

**Comment by Julesssss** [comment] 2023-07-24 09:40
Hey @pasyukevich, let us know when you have a PR ready for review 👍

**Comment by pasyukevich** [comment] 2023-07-26 08:07
Hi @Julesssss, 

The [PR](https://github.com/Expensify/react-native-onyx/pull/283) is ready for review

**Comment by pasyukevich** [comment] 2023-07-27 12:52
@aimane-chnaif 
Since I posted the message you forwarded, I haven't been able to reproduce the exact issue. However, I did encounter similar instances of broken flow in other areas.

Currently, I can't replicate it elsewhere in the latest app, but I can reproduce the same behavior from my forked branch that uses the latest Onyx library. Therefore, I believe we still need to fix the underlying cause to prevent future occurrences.

The reproduction steps: https://github.com/Expensify/react-native-onyx/pull/283#issuecomment-1653441265

**Comment by conorpendergrast** [comment] 2023-07-31 15:36
It looks like work is ongoing on this one via https://github.com/Expensify/react-native-onyx/pull/283, correct?

**Comment by conorpendergrast** [comment] 2023-07-31 19:36
@Christinadobrzyn is back, so I'm unassigning!

**Comment by Christinadobrzyn** [comment] 2023-08-03 20:32
Working on https://github.com/Expensify/react-native-onyx/pull/283

**Comment by Christinadobrzyn** [comment] 2023-08-14 23:16
watching this PR - https://github.com/Expensify/react-native-onyx/pull/283

**Comment by Christinadobrzyn** [comment] 2023-08-18 21:53
watching this PR - https://github.com/Expensify/react-native-onyx/pull/283

**Comment by Christinadobrzyn** [comment] 2023-08-28 21:35
watching this PR - https://github.com/Expensify/react-native-onyx/pull/283

**Comment by Christinadobrzyn** [comment] 2023-09-07 15:26
Hey @aimane-chnaif can you confirm if we're holding for this https://github.com/Expensify/App/pull/26305 or something else?

**Comment by dhanashree-sawant** [comment] 2023-09-08 05:24
Hi @Christinadobrzyn, since this job is older then job mentioned in PR, will it be eligible for reporting bonus? If so then I already have the offer for this job, can you approve that before closing it?

**Comment by Christinadobrzyn** [comment] 2023-09-19 22:25
Hey @Julesssss do you have any thoughts on paying for https://github.com/Expensify/App/pull/26274

@dhanashree-sawant yes, you will be paid are the reporter.

**Comment by Julesssss** [comment] 2023-09-20 01:37
> Hey @Julesssss do you have any thoughts on paying for https://github.com/Expensify/App/pull/26274

Yeah that's fair. Someone else created a PR and merged it before mine, but it would have been a valid review still.

**Comment by Christinadobrzyn** [comment] 2023-09-29 00:25
Soudns good, sorry for the delay in payment. 

I'll pay this tomorrow. 

@aimane-chnaif I'm thinking we'll pay 25% for the work on the PR? Let me know if you feel the payment should be different based on the work you did.  thanks!

**Comment by Julesssss** [comment] 2023-09-29 04:53
Yeah I agree. @Christinadobrzyn this was only not merged because our internal review was too slow. We should pay 100% IMO

**Comment by Christinadobrzyn** [comment] 2023-09-29 21:30
Sounds good, sorry @aimane-chnaif I should've asked you what seemed fair.

Payouts due:

Issue Reporter: $250 @dhanashree-sawant  (paid in Upwork with this [job posting](https://www.upwork.com/jobs/~01cb137372e1458408) - now closed)
Contributor: NA
Contributor+: $1000 @aimane-chnaif (please accept the offer in this [Upwork posting ](https://www.upwork.com/jobs/~01fe8b8e686fcc9965))

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~01fe8b8e686fcc9965).

**Comment by perfectdev95** [comment] 2023-09-29 21:38
Hello @Christinabrzyn
I hope you are doing well.
While reading the job post on Upwork and I am very interested in this project.
I can fix this project on time with high quality ASAP.
Please, let's make a contract.

**Comment by perfectdev95** [comment] 2023-09-29 21:40
osamunori95@gmail.com
https://www.upwork.com/freelancers/~01bb384137b6dfa7e5

**Comment by Julesssss** [comment] 2023-10-02 09:07
Just awaiting payment now

**Comment by Christinadobrzyn** [comment] 2023-10-10 22:39
Thanks @aimane-chnaif paid you in Upwork based on this payment plan - https://github.com/Expensify/App/issues/21881#issuecomment-1741510292

Closing!

**Closed by Christinadobrzyn** 2023-10-10 22:39 UTC
Labels: External, Engineering, Weekly, Overdue, Bug
