### ISSUE TITLE
[Workspace Chats] Web - Chat- Archive reason not immediately available for workspace chats

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8644] opened 2022-04-14 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

We found this issue when executing https://github.com/Expensify/App/pull/8437 
Original issue isn't fixed https://github.com/Expensify/Expensify/issues/204497

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)
3. Add a new member to the workspace via Manage Members > Invite
4. Log-in as the member and send a couple of messages in the member's workspace chat
5. Log back in again to the admin account and remove the member from the workspace via Manage Members > Remove
6. Go back to LHN and open .
7. Click back into the workspace chat.

## Expected Result:
Textbox is appeared after back into the workspace chat

## Actual Result:
Textbox is appeared after refresh the page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android 
- Desktop App
- Mobile Web

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+41322abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/163404431-1f621560-2c5f-44b7-ac99-662cde7b0a35.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment] 2022-04-14 21:51
@yuwenmemon just to confirm, do you think this issue should be internal or external?

**Comment by yuwenmemon** [comment] 2022-04-14 22:15
This can be external!

**Comment by mallenexpensify** [comment] 2022-04-15 22:04
Posted! https://www.upwork.com/jobs/~0161ef6695919d8c97

**Comment by wildanmuhlis2** [comment] 2022-04-19 09:15
@kbecciv How should it behave when a member is deleted from the workspace?

(1) Should it keep the old chat but hide the textbox or (2) delete the chat archive completely.

I can't reproduce the above issue exactly. 
What happened to me is similar with this issue #8470

It can only be refreshed after logout and re-login and the chat entries are completely gone.

**Comment by mallenexpensify** [comment] 2022-04-25 23:53
Doubled price to $500
https://www.upwork.com/jobs/~0161ef6695919d8c97

@parasharrajat , can you help with @wildanmuhlis2 's question above?

**Comment by NikkiWines** [comment] 2022-04-26 00:16
I'm also not sure I understand the bug (but having troubles with NewDot locally so haven't been able to do my own testing). I think since https://github.com/Expensify/App/issues/8470 is resolved we should retest to make sure this is still a bug.

**Comment by mvtglobally** [comment] 2022-04-26 05:00
@NikkiWines This issue is found when executing PR https://github.com/Expensify/App/pull/8437/ 
As per Step 5 user should see a textbox when navigating back, but we only see it after refresh.

**Comment by trjExpensify** [comment] 2022-04-27 09:51
I think more specifically the problem now is that the archivedReason that requires a refresh. The textbox appears immediately, but it reads "This chat room has been archived" until you refresh and see the proper archivedReason. 

Before refresh: 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16232057/164078562-4aebdf92-4807-4b4e-b5d1-d9afaf731a48.png">

After refresh: 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16232057/164078639-76c5ce73-b556-4400-90f7-9403d2244ca1.png">

**Comment by NikkiWines** [comment] 2022-04-28 01:37
Cool, thank you for retesting @mvtglobally and thanks for the clarification @trjExpensify. 

> (1) Should it keep the old chat but hide the textbox or (2) delete the chat archive completely.

@wildan-m, from @trjExpensify's explanation it sounds like we want option (1) here.

**Comment by wildan-m** [comment] 2022-04-28 02:10
@NikkiWines , @mvtglobally , @trjExpensify  thanks for your confirmation.

I need to clarify one thing. On the second step to reproduce the issue:

> 2. Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)

How can I make my account a policyExpenseChat beta account?

I've tried to override this function to return **true** in my local code:

```
function canUseAllBetas(betas) {
    return true || Environment.isDevelopment() || _.contains(betas, CONST.BETAS.ALL);
}
```

and also enabled `Use Secure Staging Server` in the preferences.

@mvtglobally's screen:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/11847279/165661235-e0a6feb3-d234-4b61-b7f7-8bab6445cb29.png">

My local screen:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/11847279/165661368-8689f644-9dfc-42f7-bd0d-1f227ec151b0.png">

There is no **Chat Main** and  **Workspace** chat on my screen. Am I missing some steps?

**Comment by parasharrajat** [comment] 2022-04-28 12:56
@wildan-m do this. 
1. enable the beta as you did from Permissions.js. BTW they should be already enabled on dev server. 
```js
function canUsePolicyRooms(betas) {
    return true || _.contains(betas, CONST.BETAS.POLICY_ROOMS) || _.contains(betas, CONST.BETAS.ALL);
}

/**
 * @param {Array<String>} betas
 * @returns {Boolean}
 */
function canUsePolicyExpenseChat(betas) {
    return true || _.contains(betas, CONST.BETAS.POLICY_EXPENSE_CHAT) || canUseAllBetas(betas);
}
```
2. Now Go to the Green Plus icon for the LHN (chat list). 
3. See if it gives an option to create a room (new Room).
4. Create a Room. 

Then follow the steps from the issue description.

**Comment by trjExpensify** [comment] 2022-04-28 16:20
^^ A `policyExpenseChat` gets created automatically for each member of a workspace, so you don't need to create a `New room` to test this.

**Comment by wildan-m** [comment] 2022-04-28 16:23
@parasharrajat after overriding `canUsePolicyRooms `, I can create a custom room for a specific workspace, but it's different from the chat room shown on @mvtglobally's screen. Her screen doesn't have a hashtag prefix.

My screen after create custom room:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/11847279/165797869-8d9714ae-d888-4d66-8971-0d50a7165602.png">


Also, this custom room behave differently when member access revoked. It will show the textbox but pointed to `Unavailable Workspace`
<img width="679" alt="image" src="https://user-images.githubusercontent.com/11847279/165798758-401dc9d6-43bb-4b35-a80e-985ad0e05a67.png">

**Comment by wildan-m** [comment] 2022-04-28 16:26
> ^^ A `policyExpenseChat` gets created automatically for each member of a workspace, so you don't need to create a `New room` to test this.

@trjExpensify Does it only work for account `@expensifail.com`? I use @gmail.com for test account

**Comment by trjExpensify** [comment] 2022-04-28 16:44
Not that I'm aware, just requires the policyExpenseChat beta. Did you CMD+K search for a member on the workspace to find the workspace chat? (E.g "wildevemail@gmail.com" before you removed that user)

**Comment by TomatoToaster** [comment] 2022-04-28 18:14
I'm just being aware of this issue now, but I think this is better as an internal issue since users outside of the policyExpenseChat beta will never be able to see Workspace Chats (different from policyRooms). We filter out policyExpenseChats at the API level and so there's nothing you can do in the client that would let you access them.

**Comment by TomatoToaster** [comment] 2022-05-02 15:46
Actually in testing this right now, it seems to be fixed! 🎉 

Here's a screen recording testing this on production:

https://user-images.githubusercontent.com/19364431/166264013-5689dad5-800d-4378-ac4a-696cf4c1733e.mov


I think this may have been inadvertently fixed when other PRs relating to the archive reason were merged since this issue was opened.

I'll wait for @trjExpensify or QA to confirm before closing this out, but I think no PR is necessary for this one.

**Comment by trjExpensify** [comment] 2022-05-02 16:33
Looks like we're good here! 

![archivereason](https://user-images.githubusercontent.com/16232057/166274924-7967e463-42c8-4048-9d7a-4a7eb0b1acc5.gif)

**Comment by trjExpensify** [comment] 2022-05-20 19:13
👋 @TomatoToaster - when I removed the member from the workspace, it still took navigating away and back to the workspace chat for the archiveReason to update:

![archivereason1](https://user-images.githubusercontent.com/16232057/169596370-1aa8e66e-83f3-4cd4-8f38-688147e5183f.gif)

**Comment by JmillsExpensify** [comment] 2022-05-23 19:26
Should we create a new issue for this one @TomatoToaster or keep using the old issue?

**Comment by TomatoToaster** [comment] 2022-05-23 19:32
This issues fine, I can look into this one.

**Comment by TomatoToaster** [comment] 2022-05-31 18:04
Got a PR for this one, should be in review soon.

**Closed** 2022-06-01 09:22 UTC
Labels: Reviewing, Engineering, Weekly, Internal
