### ISSUE TITLE
[HOLD for payment 2022-10-10][$500] Markdown for hyperlinks doesn't work with email addresses - Reported by Karim mostafa

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10516] opened 2022-08-24 03:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Go to chat box
2- type an email address using markdown for a hyperlink: eg `[abc@gmail.com](abc@gmail.com)`
3- observe the result.

## Expected Result:
One link should appear

## Actual Result:
Two links appear instead of one.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186325123-128ca12c-4e06-45c7-9945-2ffc272a5c1d.mp4

https://user-images.githubusercontent.com/43995119/186325125-3a5f92d1-9ac8-41c1-8262-28b449acdee3.mp4

https://user-images.githubusercontent.com/43995119/186325127-4fd0a764-3ebf-45f1-8fb7-7af91145d4a8.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Karim-30 Karim mostafa
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659954984294019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2022-08-24 08:30
Triaged and got the same result.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/33293730/186370092-0ca12829-d314-4c02-9e18-15ad76d26ea1.png">

**Comment by laurenreidexpensify** [comment] 2022-08-25 13:18
https://www.upwork.com/jobs/~0197256b0c15c2cdc4

**Comment by aimane-chnaif** [comment] 2022-08-25 15:58
### **Proposal**

This issue happens when text inside `[]` doesn't match regex on this line:
https://github.com/Expensify/expensify-common/blob/e0ec0b9abca4d7b417ba0b016f8725856cfeeece/lib/ExpensiMark.js#L64

> regex: /\[(`[\w\\s\\d!?&#;]`+)\]\(([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\)/gim,

Current regex accepts only words and limited special characters (`!?&#;`) and doesn't accept `+@` which is normally used in email and also doesn't accept space (i.e. `[My Email](abc@gmail.com)`).

**Solution1**
We can allow more special characters allowed in email, along with space.
updated regex:

> regex: /\[(`[\w\\s\\d!?&#; +@]`+)\]\(([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\)/gim,

**Solution2**
We can allow any characters in [] by using `.+`
updated regex:

> regex: /\[(`.`+)\]\(([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\)/gim,

I prefer **Solution2** because user can input any text in `[]` including any special characters, spaces, not only email

**Comment by aimane-chnaif** [comment] 2022-08-25 16:16
Before fix:

https://user-images.githubusercontent.com/96077027/186716980-2b7e8c47-c5ea-4ef2-b5e1-fa6e337ac509.mov



After fix:

https://user-images.githubusercontent.com/96077027/186717032-21da66ba-3393-4b1d-96fd-e25bdfcfd567.mov

**Comment by laurenreidexpensify** [comment] 2022-08-26 09:12
@MonilBhavsar LGTM - what's your take?

**Comment by MonilBhavsar** [comment] 2022-08-29 13:47
Expected result looks good to me!
I would like @mananjadhav to go through proposals first.
Also we should add regex and expected result to automated tests so we don't break it in future.

**Comment by mananjadhav** [comment] 2022-08-30 04:13
Checking the regex.

**Comment by mananjadhav** [comment] 2022-08-31 00:51
@MonilBhavsar I looked into the Regex, and yeah we're basically filtering only limited characters for group 0 to match. @mollfpr's proposal with **Solution 2**, to support all characters within `[]` looks good with just one issue/question. Let me know if that is an acceptable expected output.

@mollfpr In your second regex, it also accepts if you just put spaces. `[ ](abc@example.com)`, which won't render anything. Can you fix that and update your proposal?

**Comment by mollfpr** [comment] 2022-08-31 02:13
@mananjadhav you got the wrong person 😅

**Comment by aimane-chnaif** [comment] 2022-08-31 03:39
> In your second regex, it also accepts if you just put spaces. [ ](abc@example.com), which won't render anything. Can you fix that and update your proposal?

yes, I also know that case. If `[ ]`, it will look like `_` (not empty) since this is hyperlink.
If this should be excluded, `[ ] (abc@example.com)` will look same as `[ ] (abc@example.com)` without any conversion.
Is that fine?

If fine, here's updated regex:

> regex: /[(?!\s+)(.+)](([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(.[a-zA-Z]+)+))/gim,

This doesn't allow spaces at the beginning inside `[]`
i.e.
`[ ](abc@example.com)` ❌
`[  ](abc@example.com)` ❌
`[myemail](abc@example.com)` ✅
`[ my email](abc@example.com)` ❌
`[my email](abc@example.com)` ✅
`[my email ](abc@example.com)` ✅
`[ my email ](abc@example.com)` ❌

**Comment by mananjadhav** [comment] 2022-08-31 03:55
Sorry for tagging it wrong. Thanks @aimane-chnaif. This is better. @MonilBhavsar can confirm if spaces are fine. But your proposal looks good to me. 

🎀 👀 🎀 
C+ reviewed

**Comment by laurenreidexpensify** [comment] 2022-09-01 14:48
@MonilBhavsar Bump ^^

**Comment by MonilBhavsar** [comment] 2022-09-01 16:09
Spaces in between are fine. We can ignore spaces at start and end i.e. we should not match them.

> yes, I also know that case. If [ ], it will look like _ (not empty) since this is hyperlink.

Could you please clarify this? Empty `[ ]` shouldn't render anything , no?

> If fine, here's updated regex:
> `regex: /[(?!\s+)(.+)](([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(.[a-zA-Z]+)+))/gim,`

Also, Is this proposed regex? If yes, looks like we need a space or `?!` at beginning to match the text?

**Comment by aimane-chnaif** [comment] 2022-09-01 16:50
> Could you please clarify this? Empty `[ ]` shouldn't render anything , no?

`[](abc@example.com)`
`[ ](abc@example.com)`
`[myemail](abc@example.com)`
`[ my email](abc@example.com)`
`[my email](abc@example.com)`
`[my email ](abc@example.com)`
`[ my email ](abc@example.com)`

Here's screenshot for each case of the above example:
<img width="721" alt="demo" src="https://user-images.githubusercontent.com/96077027/187968872-f9640292-f246-4be0-b588-c490843049ab.png">

As you see fix 1, `[ ]` renders `_` since this is hyperlink

> Also, Is this proposed regex? If yes, looks like we need a space or ?! at beginning to match the text?

`?!` means `not match` so `?!\s+` means `not accept spaces at the beginning`
<img width="1033" alt="regex" src="https://user-images.githubusercontent.com/96077027/187965968-1cfcb094-462c-4af0-a6b7-87701ed9a328.png">

**Comment by MonilBhavsar** [comment] 2022-09-02 08:15
> As you see fix 1, [ ] renders _ since this is hyperlink

I think we should just skip it and not render anything.

Thanks for clarifying!
Your Fix 1 output looks better, but as said above we shouldn't render `_` in first use case and skip spaces at the starting.

**Comment by aimane-chnaif** [comment] 2022-09-02 08:29
@MonilBhavsar you mean to trim content inside `[]` before validating regex?

**Comment by aimane-chnaif** [comment] 2022-09-02 08:34
I think even github doesn't trim that content.
i.e. [ ](abc@example.com), [  test  ](abc@example.com)

**Comment by aimane-chnaif** [comment] 2022-09-02 08:34
I think even github doesn't trim that content.
i.e. [ ](abc@example.com), [  test  ](abc@example.com)

**Comment by aimane-chnaif** [comment] 2022-09-02 12:05
**Updated proposal:**

current line:
```
regex: /\[([\w\\s\\d!?&#;]+)\]\(([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\)/gim,
```
updated line:
```
regex: /\[(.*)\]\(([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\)/gim,
```

current line:
```
replacement: '<a href="mailto:$2">$1</a>',
```
updated line:
```
replacement: (match, g1, g2) => `<a href="mailto:${g2}">${g1.trim()}</a>`,
```

This looks exactly same as github comment:
<img width="159" alt="markdown" src="https://user-images.githubusercontent.com/96077027/188139228-f85fd4d8-572e-4119-9228-793bbb1c9fe7.png">

**Comment by mananjadhav** [comment] 2022-09-03 18:21
Quick question @MonilBhavsar are we suggesting showing an empty text? or skipping the text altogether?

**Comment by MonilBhavsar** [comment] 2022-09-05 08:53
I think skipping the text. Looks like github markdown does the same

Input Markdown:

```
Hi, [](email@gmail.com) is my email
Hi, [ this](email@gmail.com) is my email
Hi, [           this](email@gmail.com) is my email
Hi, [ this                ](email@gmail.com) is my email
```

Output:

<img width="167" alt="Screenshot 2022-09-05 at 9 51 49 AM" src="https://user-images.githubusercontent.com/32012005/188409482-cb37f53f-9da9-4658-a2a6-e37f28460344.png">

**Comment by mananjadhav** [comment] 2022-09-06 06:45
@MonilBhavsar Do we need anything else from @aimane-chnaif? Are we good to hire them?

**Comment by laurenreidexpensify** [comment] 2022-09-08 08:27
@MonilBhavsar bump ^

**Comment by MonilBhavsar** [comment] 2022-09-08 09:00
Looks good to me! Thanks for updating the proposal 👍

**Comment by laurenreidexpensify** [comment] 2022-09-13 11:06
@aimane-chnaif @mananjadhav @Karim-30 I've invited you to job on Upwork

**Comment by laurenreidexpensify** [comment] 2022-09-22 08:09
@mananjadhav is the PR getting reviewed today? Thanks

**Comment by mananjadhav** [comment] 2022-09-22 08:23
Yes, I reviewed the code it looks fine. I need to test it now. I will get to it in 2-3 hours and send the feedback.

**Comment by laurenreidexpensify** [comment] 2022-09-30 10:31
First PR here is merged

**Comment by MonilBhavsar** [comment] 2022-10-03 05:41
Looks like `expensify-common` is updated with another latest merge commit and this improvement is now live on staging.

**Comment by MonilBhavsar** [comment] 2022-10-03 05:43
I think we'll need to manually edit the title to hold for payment until regression period. cc @laurenreidexpensify

**Comment by MonilBhavsar** [comment] 2022-10-03 06:12
I'll discuss with my team and get back to you

**Comment by michaelhaxhiu** [comment] 2022-10-04 14:08
asdfaRajat I’m confused by your latest comment - was it for @Rushat or me? 
Rajat I’m confused by your latest comment - was it for @Rushat or me? 
Rajat I’m confused by your latest comment - was it for @Rushat or me? 
Rajat I’m confused by your latest comment - was it for @Rushat or me?

**Comment by mananjadhav** [comment] 2022-10-06 04:08
@laurenreidexpensify  I can see this is pushed to production. Can we please update the payment date ?

cc - @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2022-10-06 05:49
Was deployed on 2022-10-03, so updated it to 2022-10-10

**Comment by trjExpensify** [comment] 2022-10-12 11:46
👋 Happy to take care of this while Lauren is out. 

Can we confirm these are the correct payments? 

$500 - @aimane-chnaif for the fix
$500 - @mananjadhav for C+ 
$250 - @Karim-30 for reporting the issue

**Comment by mananjadhav** [comment] 2022-10-12 11:51
That is correct @trjExpensify

**Comment by trjExpensify** [comment] 2022-10-12 16:46
Cool, thanks for confirming. Offers have been sent to all three of you with the correct amounts.

**Comment by trjExpensify** [comment] 2022-10-12 16:47
@mananjadhav -paid! (The auto-accept gets me every time. 😂)

**Comment by trjExpensify** [comment] 2022-10-12 17:06
@Karim-30 - paid! Just waiting on @aimane-chnaif now and we can close this out.

**Comment by trjExpensify** [comment] 2022-10-12 19:55
@aimane-chnaif - paid! We're all set here. 🎉

**Closed by trjExpensify** 2022-10-12 19:55 UTC
Labels: External, Engineering, Weekly, Improvement
