### ISSUE TITLE
[$500] Two lines (marked as unread line and divider lines) display at the same time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26240] opened 2023-08-29 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and any paid sum chat
2. Click on mark as unread
## Expected Result: 
we should display 1 line at the same time
## Actual Result: 
Two lines (marked as unread line and divider lines) display at the same time

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (4).webm](https://github.com/Expensify/App/assets/43996225/fe009ea3-abc4-4dea-a5d3-801de5c9b609)

![Snip - (104) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/4d2cdb1b-e82c-4110-ae4b-f8d57e608af3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691827544521099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149e5e270a45222cc</li>
        <li>Upwork Job ID: 1702052852667211776</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-08-29 18:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Both lines (divider line and mark as unread line) show at the same time when clicking on the mark as unread

### What is the root cause of that problem?
Let's see the requested money report as below image

<img width="1074" alt="Screenshot 2023-08-22 at 16 59 57" src="https://github.com/Expensify/App/assets/141406735/4fab5c64-4e5d-4a2f-8c63-1282b1e3dfbb">

In this report, we have 2 report actions (CREATED action and IOU action). The divider line is rendered by CREATED action, the new marker line is rendered by IOU action and the CRETED action is rendered before IOU action. After IOU action is marked as unread, currentUnreadMarker is set while rendering the IOU action. It means that the CREATED action is rendered before currentUnreadMarker is set. It caused that while rendering the CREATED action shouldHideThreadDividerLine will be set based on the old currentUnreadMarker (because in this time, currentUnreadMarker isn't set until IOU action is rendered)
### What changes do you think we should make in order to solve the problem?
Because for each ReportActionList we only have one value of shouldHideThreadDividerLine. So we don't need to initialize shouldHideThreadDividerLine in renderItem function. I suggest we should create a new state called  shouldHideThreadDividerLine  
``` 
const [shouldHideThreadDividerLine, setshouldHideThreadDividerLine] = useState(false);
```

and we will reset this state when currentUnreadMarker is changed in here
https://github.com/Expensify/App/blob/893c2a5f88ca5268230f580c26fd5b3d6a9efafe/src/pages/home/report/ReportActionsList.js#L238-L240

```
setshouldHideThreadDividerLine(sortedReportActions.length > 1 && sortedReportActions[sortedReportActions.length - 2].reportActionID === currentUnreadMarker.current)

```

### Result

https://github.com/Expensify/App/assets/141406735/799fbc63-5d73-4810-a7ef-9830c6f828c3

**Comment by dylanexpensify** [comment] 2023-08-31 08:56
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-09-04 10:16
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry I didn't get to this last week, had head down on wave4 saastr

**Comment by dylanexpensify** [comment] 2023-09-11 10:28
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment] 2023-09-13 20:13
confirmed

**Comment by dylanexpensify** [comment] 2023-09-19 08:29
you're right! Thanks @parasharrajat!

**Closed by dylanexpensify** 2023-09-19 08:29 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
