### ISSUE TITLE
Top header bar is also scrolling while scrolling the screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18602] opened 2023-05-08 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any profile page
2. click on textfield
3. Scroll the screen
4. Observe the top bar

## Expected Result:
Topbar should not be scroll like about section

## Actual Result: 
Topbar is scroll while opening keyboard. Topbar should not be scroll like about section.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236916734-9382fc5f-fe8b-46a5-9673-5a30e3779ce8.MP4

https://user-images.githubusercontent.com/43996225/236916809-314985ba-bcb7-42e2-b41b-633410cddf87.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683476881376069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment] 2023-05-10 19:07
I'm unable to reproduce this on mobile and desktop apps. Closing!

**Closed by isabelastisser** 2023-05-10 19:07 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by niravkakadiya25** [comment] 2023-05-11 02:29
@isabelastisser i am still able to reproduce this issue. This issue is on mobile web (ios, safari)
