### ISSUE TITLE
mWeb/Safari - Chat - "New Messages" button is unresponsive on taps in Safari

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47035] opened 2024-08-08 07:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4832989&group_by=cases:section_id&group_order=asc&group_id=306202
**Email or phone of affected tester (no customers):** applausetester+omqq1@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: user should be SIgned IN and have at least one conversation with long history
1. Open https://staging.new.expensify.com/
2. Navigate to any chat with long history
3. Make the last message as 'Unread'
4. Scroll up
5. Navigate to any thread
6. Navigate back to the main chat
7. Tap on "New Messages" button

## Expected Result:
Chat should be scrolled down to the unread message

## Actual Result:
Nothing happened when tapped on the 'New Messages' button. The 'New Messages' button is unresponsive on taps.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f3c10499-4f69-410a-aeeb-ef4fbf8d765f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-08 07:26
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-08 07:26
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment] 2024-08-08 17:56
I'm not able to reproduce. I attempted on MacOS an iOS (Safari) 

- Marked recent chat as unread
- navigated to a different chat and back
- scrolled up
- selected "New Message" 
- Was brought to the most recent message

**Comment by OfstadC** [comment] 2024-08-14 19:34
Was still not able to reproduce so closing this issue

**Closed by OfstadC** 2024-08-14 19:34 UTC
Labels: Weekly, Bug
