### ISSUE TITLE
[$250] mWeb - Dupe detect - Keyboard displayed below educational modal when open dupe expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51398] opened 2024-10-24 11:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in with a new account
2. Create a workspace
3. Navigate to the workspace chat
4. Submit 2 expenses with the same amount
5. Open any expense

## Expected Result:
The keyboard is hidden when the educational modal opens

## Actual Result:
The keyboard is displayed below the educational modal
It does not happen when manually putting an expense on hold

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/66e425ae-2267-43f6-b6b3-1645525dceb2

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849586790771531414</li>
        <li>Upwork Job ID: 1849586790771531414</li>
        <li>Last Price Increase: 2024-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by IuliiaHerets** [comment] 2024-10-24 11:21
We think that this bug might be related to #wave-control

**Comment by FitseTLT** [comment] 2024-10-24 13:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Dupe detect - Keyboard displayed below educational modal when open dupe expense

### What is the root cause of that problem?
The composer auto focuses on opening the transaction thread and then popover will be open as soon as `shouldShowHoldMenu` is set to true here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/MoneyRequestHeader.tsx#L127
so the popover will overlap with the keyboard
### What changes do you think we should make in order to solve the problem?

We should blur the report action compose whenever we display the hold menu (isVisible changes to true)
Here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/ProcessMoneyRequestHoldMenu.tsx#L44
```
useEffect(() => {
        if (!isVisible) {
            return;
        }
        ReportActionComposeFocusManager.composerRef.current?.blur();
    }, [isVisible]);
```
_FYI: Keyboard.dismiss doesn't suffice as the cursor will be visible under the popover and most importantly it doesn't work for web_
### What alternative solutions did you explore? (Optional)
We can also use Focus Trap in ProcessMoneyRequestHoldMenu (or generally in Popover component) by passing `isVisible` to `active` prop, that will automatically defocus the compose or any other text input when the popover is displayed

**Comment by FitseTLT** [comment] 2024-10-25 09:58
@MitchExpensify this is a dupe of an older issue https://github.com/Expensify/App/issues/51060
Let's close this one

**Closed** 2024-10-25 20:43 UTC
Labels: External, Daily, Help Wanted, Bug
