### ISSUE TITLE
Android Hybrid - Chat - Suggestions box appears automatically when editing mention

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51900] opened 2024-11-01 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5171406&group_by=cases:section_id&group_order=asc&group_id=292106
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Open any chat
3. Add a mention and send it to chat
4. Long tap on the mention and select "Edit Message"
5. Verify that edit view is opened and that suggestions box is not displayed until removing part of the mention or adding an "@"

## Expected Result:
Suggestions box for mentions shouldn´t be displayed until removing any letter of the mention while editing or until adding an "@" to add a new mention

## Actual Result:
Suggestions box is automatically displayed when editing a mention, despite not removing any letter of the already added mention or not adding an "@" to add a new mention to the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/1afd247a-f624-40d1-83f2-91630ac36a96

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment] 2024-11-06 20:36
So I tested this with @slafortune — and when sending a message with a mention and text (i.e. `@CortneyOfstad — how is it going?`) — when you edit the message, the suggestion box does not appear. 

However, if the message is just a mention/tag, and you go to edit, the suggestion box appears automatically, which is by design.

Because of this, this is not a bug, and working as intended. Closing!

**Closed by CortneyOfstad** 2024-11-06 20:36 UTC
Labels: Daily, Bug
