### ISSUE TITLE
[HOLD for payment 2023-01-30]  In the “Something went wrong” page, Expensify logo and  home bar are too close at the bottom

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14283] opened 2023-01-13 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Enable #focus mode on desktop
2. Open the mobile app iOS
3. Some random chat is showing without any chat history
4. Tap on it

## Expected Result:
In the error message page there should be enough space between expensify logo and home bar

## Actual Result:
 In the “Something went wrong” page, Expensify logo and  home bar are too close at the bottom

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.53-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/212358822-7198c24a-0489-4514-af5a-970b4626680a.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673513890584989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be353b0b68d8dc70</li>
        <li>Upwork Job ID: 1613951896391966720</li>
        <li>Last Price Increase: 2023-01-13</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-01-13 17:31
Gonna just handle this one internally.

**Comment by mananjadhav** [comment] 2023-01-18 02:56
Will review and test this today.

**Comment by mananjadhav** [comment] 2023-01-30 20:27
@marcaaron Can you assign someone for the payout here? Also I think this was missed in this PR https://github.com/Expensify/App/pull/13580 where we added the bottom padding, so should we link the PR for the regression?

**Comment by marcaaron** [comment] 2023-01-30 20:38
@mananjadhav Sorry, I don't know the answer to that question. I would suggest asking in Slack.

**Comment by marcaaron** [comment] 2023-01-30 20:40
>I think this was missed in this PR https://github.com/Expensify/App/pull/13580 where we added the bottom padding, so should we link the PR for the regression?

Yea, I think yes we should just for consistency. Though, that was a tough one to QA since it touched all screens. There's not much I'd say about how to improve the review or testing there. I think everyone did as good of a job as they could.

**Comment by garrettmknight** [comment] 2023-01-31 14:40
Asked @mananjadhav to apply for the job so I can hire/pay. Updating to daily to stay on it.

**Comment by garrettmknight** [comment] 2023-01-31 15:04
Hired/paid @mananjadhav
Closing, reopen if something isn't right.

**Closed by garrettmknight** 2023-01-31 15:04 UTC
Labels: Reviewing, Daily, Internal, Awaiting Payment, Bug
