### ISSUE TITLE
[$250] Android - Composer - Suggestion list is overlapping with text in the composer and buttons

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50377] opened 2024-10-08 08:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/41071
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to DM.
3. Type @.

## Expected Result:
Suggestion list will appear above the composer.

## Actual Result:
Suggestion list is overlapping with text in the composer and also the buttons.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/02ecea1a-2ec5-4766-a8d1-d0c24d6ee4cc

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843610135139118862</li>
        <li>Upwork Job ID: 1843610135139118862</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by Gonals** [comment] 2024-10-08 11:12
Marking as external. I don't think we need to block deploy on this. What do you think, @thienlnam?

**Comment by BhuvaneshPatil** [comment] 2024-10-08 13:22
We might want to hold this for https://github.com/Expensify/App/pull/50132

**Comment by Gonals** [comment] 2024-10-08 13:25
> We might want to hold this for #50132

Ah, yep. It seems like the same issue but on android web instead of native

**Comment by Gonals** [comment] 2024-10-08 13:37
I am not seeing this on Staging on my Android. This is likely only happening in some devices, so I think we can remove the blocker

**Comment by devanshujain95** [comment] 2024-10-08 14:23
@Gonals I think this is not reproducing because of this #5038

**Closed** 2024-10-09 08:09 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Bug
