### ISSUE TITLE
[HOLD for payment 2024-03-07] MEDIUM: [$500] Chat-In offline, uploading attachment & deleting it, is not showing strike-through

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36639] opened 2024-02-15 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Go offline
3. Tap plus icon & select add attachment
4. Upload an image using camera
5. Long press the message " Uploading attachment "
6. Tap delete comment and confirm delete

## Expected Result:
In offline, uploading attachment & deleting it, must show strike-through message

## Actual Result:
In offline, uploading attachment & deleting it, is not showing strike-through message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09505906-2040-454b-8fd6-c51f2103886f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011966647b4d15a032</li>
        <li>Upwork Job ID: 1758512787167080448</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-15 21:55
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-02-15 21:56
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abdulrahuman5196** [comment] 2024-02-19 09:10
Seems to be a new issue. Will check on proposals today.

**Comment by CortneyOfstad** [comment] 2024-02-21 15:59
@abdulrahuman5196 any updates on the reviews on the proposals? Thanks so much!

**Comment by abdulrahuman5196** [comment] 2024-02-22 13:37
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-22 14:19
@Krishna2323 's proposal here https://github.com/Expensify/App/issues/36639#issuecomment-1947452796 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by Beamanator** [comment] 2024-02-22 15:25
Hmm we currently use `OfflineWithFeedback` to show the strikethrough for normal comments (if we delete them while offline)... Do we not currently use this for attachment report actions? If not, shouldn't we start using that? I don't see this component mentioned in any proposal so far, can someone first clarify this point?

![Screenshot 2024-02-22 at 5 23 35 PM](https://github.com/Expensify/App/assets/3885503/2cd11dfe-d0f9-40f3-a25c-bb54f675cddf)

**Comment by Beamanator** [comment] 2024-02-23 14:32
Ok I followed the code you're talking about @dukenv0307 - do you have any idea why we added `shouldDisableStrikeThrough` to `OfflineWithFeedback` in ReportActionItem.js? Maybe because there's too many child components, the strikethrough wasn't being rendered in the correct place?

Anyway, it seems a bit hacky to me that we added `shouldDisableStrikeThrough` in the past, but it is probably too much work to get that cleaned up at this exact moment for this fix

I'm honestly leaning a bit toward @dukenv0307 's proposal of using `TextCommentFragment` to render the strikethrough text in this case, because
1. It's already built & technically at this point we do only have text to display
2. `AttachmentCommentFragment` will probably never need a strikethrough in other cases (we wouldn't put a strikethrough in images / attachments i believe)

What do you think @abdulrahuman5196 ?

**Comment by Beamanator** [comment] 2024-02-23 14:53
> @Beamanator, I already purposed about using `TextComponentFragment` in my alternative solution.

True you mentioned it, but it didn't look clear to me like @dukenv0307 's proposal

> Due to [this issue](https://github.com/Expensify/App/issues/17365) we add `shouldDisableStrikeThrough `.

Thank you, that's very helpful!

**Comment by abdulrahuman5196** [comment] 2024-02-23 15:37
Hi, @Beamanator , Sorry for not chiming in earlier.

>Anyway, it seems a bit hacky to me that we added shouldDisableStrikeThrough in the past, but it is probably too much work to get that cleaned up at this exact moment for this fix

Yep. This was one of the reasons from my end to suggest the approved proposal.

**Between Using `AttachmentCommentFragment` or `TextCommentFragment`** 

There where certain pointers for me go ahead with using `AttachmentCommentFragment`

1) IMO, as per the current code, we have clear responsibility split, like attachment messages are using `AttachmentCommentFragment` and others are using `TextCommentFragment` 
2) It is relatively very simple to just add the `styleAsDeleted` check to `AttachmentCommentFragment` similar to how the `TextCommentFragment` has it now, which would solve this issue.
https://github.com/Expensify/App/blob/eeb6836d8867301e7b1d8ceae5dce9f7d3e828bc/src/pages/home/report/ReportActionItemFragment.tsx#L113-L116
3) If we are to use `AttachmentCommentFragment`, then any specific logic present as part of that component should be moved or supported in `TextCommentFragment` if not present already(for eg: logic of `addExtraMargin` flag in `AttachmentCommentFragment`)

So if we use `TextCommentFragment`, we would be adding checks to see if the attachment is in upload state and then use the `TextCommentFragment`. This would just end up adding unwanted complexity specifically.

So IMO, at this point, it wouldn't be beneficial for us to migrate the usage for `AttachmentCommentFragment` to `TextCommentFragment` for this specific style issue.

**Comment by abdulrahuman5196** [comment] 2024-03-05 09:03
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be case from beginning.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Go offline
2) Open any report
3) Add any attachment
4) Delete it
5) Verify line-though is shown on `Uploading attachment...` text


cc: @CortneyOfstad

**Comment by CortneyOfstad** [comment] 2024-03-11 16:10
Regression test created here — https://github.com/Expensify/Expensify/issues/377645

Closing!

**Closed by CortneyOfstad** 2024-03-11 16:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
