### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] VBA - Able to add future dates manually in the Incorporation date field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13261] opened 2022-12-02 01:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Profile > Workspace > Connect a bank account > Connect manually
2. Enter a valid routing number and account number
3. Click save & continue
4. On company information page, click on the incorporation date field
5. Enter a future date manually and click `Save & Continue`

## Expected Result:
Invalid date error is displayed

## Actual Result:
Able to add future date and proceed to next page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.35-0
**Reproducible in staging?:** y
**Reproducible in production?:** Can't check
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/205197349-73e95087-9b22-4a48-9f45-39851b930b6b.mp4

https://user-images.githubusercontent.com/43996225/205197363-39e4d240-f9f0-47b4-be84-9af2adf17ed8.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669889569412959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01e3b1ed24a09f9c37
- Upwork Job ID: 1599459920872185856

**Comment by allroundexperts** [comment] 2022-12-02 02:18
### Proposal
The issue is a typo in the `validate` function of the form.

## Fix
```diff
diff --git a/src/pages/ReimbursementAccount/CompanyStep.js b/src/pages/ReimbursementAccount/CompanyStep.js
index d57e6be6c..41cd4dc06 100644
--- a/src/pages/ReimbursementAccount/CompanyStep.js
+++ b/src/pages/ReimbursementAccount/CompanyStep.js
@@ -104,7 +104,7 @@ class CompanyStep extends React.Component {
         }
 
         if (!values.incorporationDate || !ValidationUtils.isValidPastDate(values.incorporationDate)) {
-            errors.incorporationDateFuture = this.props.translate('bankAccount.error.incorporationDateFuture');
+            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDateFuture');
         }
 
         if (!values.incorporationState) {

```

**Comment by tienifr** [comment] 2022-12-02 04:09
# Proposal

## Problem
In https://github.com/Expensify/App/blob/820e876d5e4a8cbffe272220c1182c8942ed93cf/src/pages/ReimbursementAccount/CompanyStep.js#L102

```
        if (!values.incorporationDate || !ValidationUtils.isValidDate(values.incorporationDate)) {
            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');
        }

        if (!values.incorporationDate || !ValidationUtils.isValidPastDate(values.incorporationDate)) {
            errors.incorporationDateFuture = this.props.translate('bankAccount.error.incorporationDateFuture');
        }
```

We are having 2 validation for the incorporation date Input with 2 keys in errors object are`incorporationDate` and  `incorporationDateFuture`. On the other hand, we only show the error of fields when key in the errors object coincides with inputID that is touched. See the below code

In https://github.com/Expensify/App/blob/820e876d5e4a8cbffe272220c1182c8942ed93cf/src/components/Form.js#L144
```
        const errors = _.pick(validationErrors, (inputValue, inputID) => (
            Boolean(this.touchedInputs[inputID])
        ));
```
the `incorporationDateFuture` key in the errors object never be shown because on UI there exists only `incorporationDate` InputID without `incorporationDateFuture` InputID
## Solution

I suggest that we should use one key in errors object for `incorporationDate` inputID

```diff
        if (!values.incorporationDate || !ValidationUtils.isValidDate(values.incorporationDate)) {
            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');
        }

        if (!values.incorporationDate || !ValidationUtils.isValidPastDate(values.incorporationDate)) {
+            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDateFuture');
-            errors.incorporationDateFuture = this.props.translate('bankAccount.error.incorporationDateFuture');
        }

```

## Result

https://user-images.githubusercontent.com/113963320/205212844-e4f1b877-a89a-41ff-b144-949d6484a9ec.mp4

**Comment by tienifr** [comment] 2022-12-02 04:37
# Updated Proposal

I just saw a problem in [my above solution](https://github.com/Expensify/App/issues/13261#issuecomment-1334739664)
It always shows the message` Incorporation date cannot be in the future` even if we enter 1/1/1001 because `errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');` will be overrides by `errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDateFuture');`


## Solution

we should validate `incorporationDateFuture` before `incorporationDate`

```diff
-        if (!values.incorporationDate || !ValidationUtils.isValidDate(values.incorporationDate)) {
-            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');
-        }

        if (!values.incorporationDate || !ValidationUtils.isValidPastDate(values.incorporationDate)) {           
         errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDateFuture');
         errors.incorporationDateFuture = this.props.translate('bankAccount.error.incorporationDateFuture');
        }

+     if (!values.incorporationDate || !ValidationUtils.isValidDate(values.incorporationDate)) {
+           errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');
+        }

```

## Result




https://user-images.githubusercontent.com/113963320/205215796-efd9de47-6b84-45b2-a404-48ba04cd9f6f.mov

**Comment by alexpensify** [comment] 2022-12-04 17:46
Adding external to get 👁️s on this one and create the job.

**Comment by Puneet-here** [comment] 2022-12-05 12:52
### Proposal 

If we want to show only one error then @adeel0202's first proposal will fix this.

If we want to fix this issue without removing the second error we need to make these changes -

1. Use the same error key for future date error because error will be shown only for the inputID that we have provided in the input/picker
Change `errors.incorporationDateFuture` to `errors.incorporationDate`
https://github.com/Expensify/App/blob/eb0110d8d2bc2d1ed00828a1c9efdcbb6a8929d7/src/pages/ReimbursementAccount/CompanyStep.js#L107

2. Change the logic at `isValidDate` function
```js
function isValidDate(date) {
    if (!date) {
        return false;
    }

    const pastDate = moment().subtract(1000, 'years');
    const testDate = moment(date);

    return testDate.isValid() && testDate.isAfter(pastDate);
}
```
We need to change the logic because the specific error that we have for future dates doesn't show up unless the future date is only between current day and 1000 years in future becauseAt isValidDate we check if the date is between 1000 years back and 1000 years in future and when it's more than 1000 years in future then isValidDate function returns false and we see `Please enter a valid date` 
So, at isValidDate function we should only check that the date is not more than 1000 years back in the past and we won't return false for future dates. isValidPastDate function can handle the future dates if user uses a future date it will return false and they will see `Incorporation date cannot be in the future`

3. Validate future date case first
```diff
-        if (!values.incorporationDate || !ValidationUtils.isValidDate(values.incorporationDate)) {
-            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');
+        if (!values.incorporationDate || !ValidationUtils.isValidPastDate(values.incorporationDate)) {
+            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDateFuture');
         }
 
-        if (!values.incorporationDate || !ValidationUtils.isValidPastDate(values.incorporationDate)) {
-            errors.incorporationDateFuture = this.props.translate('bankAccount.error.incorporationDateFuture');
+        if (!values.incorporationDate || !ValidationUtils.isValidDate(values.incorporationDate)) {
+            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');
         }
```
Or use the validation like below
```js
        if (!values.incorporationDate || !ValidationUtils.isValidDate(values.incorporationDate)) {
            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDate');
        } else if (!values.incorporationDate || !ValidationUtils.isValidPastDate(values.incorporationDate)) {
            errors.incorporationDate = this.props.translate('bankAccount.error.incorporationDateFuture');
        }
```
We have to make this change otherwise the user will see future date error even for invalid past date

**Comment by thesahindia** [comment] 2022-12-05 15:31
@tienifr, after implementing your solution `Please enter a valid date` will be shown if the user uses a date which is 1000+ year in future.

@adeel0202, we should see both the errors. Specific errors are always good. 
Your second proposal has the same problem as @tienifr

**Comment by thesahindia** [comment] 2022-12-05 15:32
@puneetlath I like @Puneet-here's [proposal](https://github.com/Expensify/App/issues/13261#issuecomment-1337289837)
 
C+ reviewed 🎀👀🎀

**Comment by puneetlath** [comment] 2022-12-14 22:50
@adeel0202 yes, not to worry! We'll be compensating you since the solution used was similar to one you proposed.

**Comment by puneetlath** [comment] 2022-12-14 22:50
@adeel0202 can you please apply to the Upwork job? Need to pay the reporting bonus as well.

**Comment by Puneet-here** [comment] 2022-12-14 23:12
@puneetlath, do we compensate for solutions proposed before external label if they get used internally? On most of the issues I found that it is not the case, for example [here](https://github.com/Expensify/App/issues/13022#issuecomment-1332785174)

**Comment by marcaaron** [comment] 2022-12-15 03:50
Can we take it to Slack please @Puneet-here? This issue had an `External` label on it.

**Comment by thesahindia** [comment] 2022-12-15 09:40
@puneetlath, is it eligible for C+ compensation for reviewing the proposals?

**Comment by puneetlath** [comment] 2022-12-22 17:59
My apologies for the delay here. I _think_ this is what needs to be done for payment on this issue: 

1. @adeel0202 - $250 for reporting
2. @adeel0202 - $1000 for the solution 
3. @thesahindia - $500 for doing 50% of the C+ work on this job in reviewing proposals
4. @rushatgabhane - $1000 for internal PR review/testing 

Does that all sound right?

**Comment by puneetlath** [comment] 2022-12-29 18:38
Just need to get to the BZ checklist for this. All payments are done. Will get to it soon.

**Comment by puneetlath** [comment] 2023-01-06 01:13
Checklist completed. Closing.

**Closed by puneetlath** 2023-01-06 01:13 UTC
Labels: Reviewing, Daily, Internal, Bug
