### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Anonymous user can access the settings page 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38163] opened 2024-03-12 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710244751238109

## Action Performed:
1. As a member of a public room type a bunch of settings page URLs in a public room. E.g https://staging.new.expensify.com/settings/profile, https://staging.new.expensify.com/settings/wallet, https://staging.new.expensify.com/settings/preferences, https://staging.new.expensify.com/settings/security
2. Sign-out of any instance of Expensify you have on that device
3. Enter the URL of the public room containing those links (e.g https://staging.new.expensify.com/r/xxxxxxxxxxxx)
4. Click on the links to the settings pages as an anonymous user in the chat
5. Observe you can access the settings pages

## Expected Result:
The sign-in prompt should appear in the RHP just like clicking the "settings" bottom tab or search icon.

## Actual Result:
The pages are accessible via the deep links.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b43cac40-b3d4-4552-9192-1dffc87511aa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012cb619021a94beb4</li>
        <li>Upwork Job ID: 1768801922139336704</li>
        <li>Last Price Increase: 2024-03-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by alexpensify** [comment] 2024-03-12 23:09
@puneetlath would your `accountID-based ` project cover this one? If no, then I'll pitch it to the vsb room. Thanks for checking!

**Comment by bernhardoj** [comment] 2024-03-13 04:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Anonymous user can access restricted page such as settings page by clicking the link from the chat.

### What is the root cause of that problem?
We don't prevent the user to directly navigate to a page from a link in the chat.
https://github.com/Expensify/App/blob/91d7eb22b3cf0e690271a1313bf8016d03cb3ef7/src/libs/actions/Link.ts#L102-L107

### What changes do you think we should make in order to solve the problem?

We can check if it's a page that is accessible for anonymous user only. If it's not accesible, we redirect the user to the sign in modal.
```
if (Session.isAnonymousUser() && !Session.canAnonymousUserAccessRoute(internalNewExpensifyPath)) {
    Session.signOutAndRedirectToSignIn()
    return;
}
Navigation.navigate(internalNewExpensifyPath as Route);
```

### What alternative solutions did you explore? (Optional)
We can do the anonymous check inside Navigation.navigate, but this would require more changes as there would be cyclic dependency between Session and Navigation.

**Comment by DylanDylann** [comment] 2024-03-13 11:33
This is dupe of https://github.com/Expensify/App/issues/25482

**Comment by trjExpensify** [comment] 2024-03-13 13:32
>As a https://github.com/Expensify/App/pull/37421#issuecomment-1991398112, can I take this as C+ as I already have context?

Yep makes sense!

>This is dupe of https://github.com/Expensify/App/issues/25482

I don't think it's strictly a dupe per se. That's about a task title/description, whereas this is about settings pages -- importantly here, things like starting the Plaid flow to enable the wallet is possible. I agree both are valid though and we should prompt for sign-in. 

@youssef-lr coming from that other issue, I think we fix this, so we close this loop on being able to start that enable wallet flow without being signed-in. (Check the OP vid here for that).

**Comment by DylanDylann** [comment] 2024-03-13 14:41
I think we should reopen the previous issue because there are some pending proposals

**Comment by alexpensify** [comment] 2024-03-13 18:19
I'm double checking with my team on the assignment plan and confirming if we should run with this GH or open the dupe. I should have an update by tomorrow. Thanks!

**Comment by puneetlath** [comment] 2024-03-13 18:26
@alexpensify no my changes are related to mentions, which it doesn't seem like this issue is related to.

**Comment by alexpensify** [comment] 2024-03-13 18:33
Cool, thanks for confirming!

**Comment by alexpensify** [comment] 2024-03-16 00:51
Ok, instead of opening the other GH, I chatted with the team and let's work here. @mkhutornyi let's go with @DylanDylann's proposal. Next week, I'll figure out the wave or VIP for this one.

**Comment by alexpensify** [comment] 2024-03-18 22:58
Thanks, @mkhutornyi for the update! Can you share the PR related to the regression so we can identify if we should put this one on hold?

**Comment by alexpensify** [comment] 2024-03-21 00:00
Thanks, I'll review that GH to identify if we should put this one one hold. That said, it looks like the other issue is moving forward.

**Comment by DylanDylann** [comment] 2024-03-21 22:32
@mkhutornyi [PR](https://github.com/Expensify/App/pull/38503) is ready to review

**Comment by alexpensify** [comment] 2024-03-22 19:27
Awesome, thanks @DylanDylann for the update!

**Comment by alexpensify** [comment] 2024-04-04 22:47
Tomorrow, I will prepare the payment summary but please accept the invites here: 

https://www.upwork.com/jobs/~012cb619021a94beb4

@DylanDylann and @mkhutornyi -- Thanks!

**Comment by alexpensify** [comment] 2024-04-05 20:49
@DylanDylann - I've paid you via Upwork

@mkhutornyi - Please accept the invite and I can complete the process. Thanks!

**Comment by alexpensify** [comment] 2024-04-08 15:27
Update: Waiting for @mkhutornyi to accept the Upwork invite to complete the payment process there.

**Comment by alexpensify** [comment] 2024-04-10 23:50
@mkhutornyi please accept the Upwork invite and then I can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-04-12 19:41
No update here, still waiting for @mkhutornyi to accept the Upwork invite: 

https://www.upwork.com/jobs/~012cb619021a94beb4

**Comment by alexpensify** [comment] 2024-04-15 21:26
I believe that @mkhutornyi is OOO right now. Heads up, I will be offline starting on Wednesday until Tuesday, April 23. I'll check again one more time before I go OOO to see if I can complete the payment process.

**Comment by alexpensify** [comment] 2024-04-23 22:31
Catching up from being OOO and going to remove @mallenexpensify. I checked the Upwork job and we are still waiting for @mkhutornyi to accept.

**Comment by alexpensify** [comment] 2024-04-30 22:27
I've asked the team for feedback since this one has been pending payment for over a month - https://expensify.slack.com/archives/C01SKUP7QR0/p1714516012720699

**Comment by alexpensify** [comment] 2024-05-01 23:12
@mkhutornyi - I'm going to move this to monthly. Please let me know when you are back online and we can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-05-17 15:03
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-05-31 16:32
Monthly check-in - no update here. Setting a reminder to review a month.

**Comment by mallenexpensify** [comment] 2024-06-06 00:05
@mkhutornyi is back! can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019112f681ac31089d

@alexpensify , please finish off payment once it's ready.

**Comment by alexpensify** [comment] 2024-06-06 00:15
Awesome, thanks for the update!

**Comment by alexpensify** [comment] 2024-06-06 19:11
Done, I've completed the payment process via Upwork and closed the jobs there. Welcome back @mkhutornyi!

**Closed by alexpensify** 2024-06-06 19:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
