### ISSUE TITLE
[HOLD for payment 2022-11-16] [$500] Web - FAB - "New Workspace" option is disabled after deleting Workspace in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11825] opened 2022-10-13 21:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings->Workspace
4. Kill the internet connection
5. Delete the workspace
6. Turn on the internet connection
7. Click on FAB button and check for a "New workspace" option

## Expected Result:
"New Workspace" option should be available

## Actual Result:
"New Workspace" option is disabled.
"New Workspace" option becomes available only after re-login

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195712579-88b42f99-83ea-4a33-ad42-7506c1d36476.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-10-14 09:48
Nice spot. Confirmed that we'll need to re-show the FAB New Workspace option.

**Comment by Julesssss** [comment] 2022-10-19 09:38
Awaiting contributors

**Comment by alexpensify** [comment] 2022-10-19 20:04
@Julesssss - Based on your last response, should I hold on creating the job in Upworks?

**Comment by alexpensify** [comment] 2022-10-19 20:56
Disregard my last comment, I'll work on the job posting later this week.

**Comment by alexpensify** [comment] 2022-10-21 21:04
The job has been created in Upwork: 

Internal: https://www.upwork.com/ab/applicants/1583564673241923584/job-details
External: https://www.upwork.com/jobs/~017971a3070c51f85a

**Comment by mallenexpensify** [comment] 2022-10-26 15:04
Price Doubled to $500
https://www.upwork.com/jobs/~017971a3070c51f85a

**Comment by ahsan-K** [comment] 2022-10-26 17:02
As per my understanding you guys using Redux in your project and after making API request of delete workspace you are calling Redux action to update the UI state and Redux store. The main problem is your tooltip UI popup which is appearing after clicking on "Plus" button is not updating successfully. I will debug the whole code and will read Popup component's code as well for getting information is you code successfully updating (re-rendering) or not.

**Comment by Santhosh-Sellavel** [comment] 2022-10-26 17:50
@ahsan-K Seems you are new here.

Get started by checking out our contributing [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) first and don't forget to check out [readme](https://github.com/Expensify/App#readme).

**Comment by ahsan-K** [comment] 2022-10-26 17:53
@Santhosh-Sellavel I have read and posted the proposal on Upwork as well.

**Comment by Santhosh-Sellavel** [comment] 2022-10-26 17:57
I'm afraid you skipped the whole thing, take time to read through and understand our process.

Checkout how to [Propose a solution for the job](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

**Comment by ahsan-K** [comment] 2022-10-26 18:19
"Proposal"
Hello Sir, I'm am senior software engineer with over 5+ years of experience on ReactJS. I have strong grip on javascript. I have read the description and saw the video of that issue which is on Github.
I will be more then happy to solve your issue. I have understand that why "New Workspace" button is not showing after deleting the Work Space.

How i will solve this problem?
As per my understanding you guys using Redux in your project and after making API request of delete workspace you are calling Redux action to update the UI state and Redux store. The main problem is your tooltip UI popup which is appearing after clicking on "Plus" button is not updating successfully. I will debug the whole code and will read Popup component's code as well for getting information is you code successfully updating (re-rendering) or not.

Let's jump on an initial call/meeting so that we can discuss more about it.

Best Regards,
Ahsan Ali

**Comment by smrutiparida** [comment] 2022-10-26 18:20
@kbecciv I am not able to reproduce the issue in staging and local environment. 

My hypothesis was that the App.reconnectApp shall first fetch the policy that is deleted in client from the server post reconnection and then the Pusher based deletion of policy happens which must be updating the UI again. As both actions are synchronous, we must be seeing such a behavior for a moment till Onyx is updated because of server load or network slow connection.

However i can't reproduce this issue. It shall help immensely if you check once. All the time my UI in local and staging are updated with 'Create new workspace' the moment is network is back.

 ```
componentDidMount() {
        NetworkConnection.listenForReconnect();
        NetworkConnection.onReconnect(() => App.reconnectApp());
        PusherConnectionManager.init();
        ...
        ...
    }
```

**Comment by Julesssss** [comment] 2022-10-27 08:07
Hi @ahsan-K. @Santhosh-Sellavel was directing you to the readme as we do not use Redux, and it explains our process for hiring external contributors.

**Comment by kbecciv** [comment] 2022-10-30 23:32
@smrutiparida Issue is not reproduced any more with build 1.2.21.4

https://user-images.githubusercontent.com/93399543/198907265-b1366529-b1f9-4cec-86aa-7b3a8a3df856.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-10-31 07:43
Only when we go online, the option appears. But should we hide the option until we go online, I believe we should still look for solution @kbecciv ? @Julesssss What do you think?

There is a proposal above looks promising didn't get to test it though. Let me if we wish to proceed will test and update thanks!

**Comment by Julesssss** [comment] 2022-10-31 10:53
Yeah, @Ollyws's proposal sounds good to me. @Santhosh-Sellavel please take a quick review

**Comment by Santhosh-Sellavel** [comment] 2022-10-31 20:08
@Julesssss 
@Ollyws proposal looks good, test well!

C+ Reviewed
🎀 👀 🎀

**Comment by alexpensify** [comment] 2022-11-01 16:14
Thanks for the update!

**Comment by alexpensify** [comment] 2022-11-04 23:22
Cool, looks like we are moving to reviews!

**Comment by alexpensify** [comment] 2022-11-07 23:14
I've checked this GH and see Jule's comment that this one is still under review.

**Comment by mvtglobally** [comment] 2022-11-09 03:37
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2022-11-10 01:13
I'll check the status on 11/16.

**Comment by mvtglobally** [comment] 2022-11-16 02:18
Issue not reproducible during KI retests. (Second week)

**Comment by alexpensify** [comment] 2022-11-16 22:25
@Julesssss - this one still has a hold. Can I proceed forward to the payment? I believe there are no issues with the tests, so far.

**Comment by Julesssss** [comment] 2022-11-17 10:00
Hey @alexpensify -- yeah, I think the hold was automatically added until we make the payment 👍

**Comment by alexpensify** [comment] 2022-11-18 03:50
@Ollyws has been hired as the contributor. Please accept and I can continue the process in Upwork: 

https://www.upwork.com/jobs/~017971a3070c51f85a

**Comment by alexpensify** [comment] 2022-11-18 17:37
Thanks, @Ollyws! Closing this job has been paid via Upwork.

**Comment by Santhosh-Sellavel** [comment] 2022-11-18 17:40
@alexpensify Missed out me!

**Comment by alexpensify** [comment] 2022-11-18 17:50
My apology @Santhosh-Sellavel! I will work on the required steps.

**Comment by alexpensify** [comment] 2022-11-18 20:11
@Santhosh-Sellavel - you have been hired as a contributor. Please accept and I can continue the process in Upwork: 

https://www.upwork.com/jobs/~01f2ecf93218a3f610

**Comment by Santhosh-Sellavel** [comment] 2022-11-18 20:30
Done thanks @alexpensify

**Comment by alexpensify** [comment] 2022-11-18 20:36
@Santhosh-Sellavel thank you for your grace here! I've corrected my mistake 😓 and closing this job. Everyone has been paid via Upwork.

**Closed by alexpensify** 2022-11-18 20:36 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
