### ISSUE TITLE
Payment - "You appears to be offline" is duplicated 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10087] opened 2022-07-25 22:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #9895
## Action Performed:
1. Sign into an account on NewDot.
2. Turn on your wifi.
3. Go to settings > Payment

## Expected Result:
"You appears to be offline" - must be displayed once

## Actual Result:
"You appears to be offline"  message is duplicated

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** any
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/180885062-cba7cc76-44cc-47db-8aaa-34c1f1eb7a70.jpg" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/180885629-0a7eb72c-43b4-45b6-9436-c033f3ed4f32.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2022-07-26 15:59
Oops sorry, missed my assignment to this - was catching up from being OOO. Looking into it now

**Comment by jasperhuangg** [comment] 2022-07-26 16:01
@NikkiWines I have a feeling it could be related to https://github.com/Expensify/App/pull/9895, which I'm about to revert. Will let you know if this fixes the problem!

**Comment by NikkiWines** [comment] 2022-07-26 16:32
Ah, yeah, I think you're right. The `OfflineIndicator` is shown on small screens on the [`ScreenWrapper`](https://github.com/Expensify/App/pull/9895/files#diff-99bb9513f8851d01747af100af8584564a0bc8899e4cb927307df8241a3274f8R147-R151) (added in https://github.com/Expensify/App/pull/9895)  but the `OfflineIndicator` was also added to the [`BasePaymentsPage`](https://github.com/Expensify/App/commit/1eebd135dbeae29b1b8e432a28b3980d74e29a6c#diff-339a7f89041cd4c701ecc3eafa4b7919d282a3cbe1b6ff0abd2e31438622ea5bR437) in https://github.com/Expensify/App/pull/9589 so it'll end up showing twice on that page.

**Comment by NikkiWines** [comment] 2022-07-26 20:35
Looks like a [revert PR](https://github.com/Expensify/App/pull/10113) for https://github.com/Expensify/App/pull/9895 has been merged and deployed to staging. Testing now to see if I can reproduce the original error

**Comment by NikkiWines** [comment] 2022-07-26 21:00
Hmm, ok. Now looks like there's no offline indicator whatsoever since it's been removed from both [ScreenWrapper](https://github.com/Expensify/App/commit/ef9b14592940fef3cd7c4923799c642e0ec3f39c#diff-99bb9513f8851d01747af100af8584564a0bc8899e4cb927307df8241a3274f8L148-L150) and [BasePaymentsPage](https://github.com/Expensify/App/commit/ef9b14592940fef3cd7c4923799c642e0ec3f39c#diff-339a7f89041cd4c701ecc3eafa4b7919d282a3cbe1b6ff0abd2e31438622ea5bL437). 

@jasperhuangg @MariaHCD since you both worked on the offline indicator for these pages and there's been some crossed wires, what do you want to do going forward. I think we should add back in `OfflineIndicator` to `BasePaymentsPage` while we're waiting for the v2 of https://github.com/Expensify/App/pull/9895. Thoughts?

**Comment by NikkiWines** [comment] 2022-07-26 21:01
Either way, though I don't think this is a blocker anymore since there's no duplication of the offline indicator anymore. Going to adjust the labels appropriately and keep it assigned.

**Comment by luacmartins** [comment] 2022-07-26 21:29
So right now we have no `You appear to be offline` message? It seems ok to remove the blocker status, but we should fix this soon.

**Comment by MariaHCD** [comment] 2022-07-27 08:38
> I think we should add back in `OfflineIndicator` to `BasePaymentsPage` while we're waiting for the v2 of #9895. Thoughts?

This sounds good to me!

**Closed** 2022-07-28 14:25 UTC
Labels: Reviewing, Engineering, Weekly, Improvement
