### ISSUE TITLE
[HOLD for payment 2023-08-28] [$500] Request money - The app crashes when user deleted the request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25451] opened 2023-08-18 02:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap Fab
3. Tap request money
4. Tap enter any amount
5. Tap next
6. Select any user
7. Tap Request money
8. Tap last transaction to open the last requested money page
9. Tap the money requested
10. In IOU details page, tap 3 dots to select "delete request"
11. Tap delete request

## Expected Result:
The request money should be deleted

## Actual Result:
The app crashes when user deleted the request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/aef26869-3797-4f7d-a903-b4bd0922bede

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Ingernal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8ef599b7ac8134d</li>
        <li>Upwork Job ID: 1692480853057089536</li>
        <li>Last Price Increase: 2023-08-18</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26194635</li>
<li>pradeepmdk | Contributor | 26194639</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-08-18 05:03
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
[Request money - The app crashes when the user deleted the request money]
### What is the root cause of that problem?
![Screenshot 2023-08-18 at 10 22 17 AM](https://github.com/Expensify/App/assets/16595846/4c67aa73-6051-475b-a49f-176711025be1)
after delete request `title is 0` here 0 is number 
https://github.com/Expensify/App/blob/404cefb6d1f8b56cbb9a8b2192cef432b489dff8/src/components/MenuItem.js?#L134

### What changes do you think we should make in order to solve the problem?

we need fix the type to string  here accessibilityLabel
possiblity to get title is null or undefined 

```javascript
                    accessibilityLabel={props.title ? props.title.toString() : ''}
``` 

we need fix below those as well all should be an type error only.
<img width="633" alt="Screenshot 2023-08-18 at 10 30 38 AM" src="https://github.com/Expensify/App/assets/16595846/6489bbd3-00cf-4a1d-81fc-48d35e36cd2e">
<img width="667" alt="Screenshot 2023-08-18 at 10 30 53 AM" src="https://github.com/Expensify/App/assets/16595846/75827394-0b8a-436e-ac7d-6f1302fd44d9">

**Comment by mountiny** [comment] 2023-08-18 10:18
given this is quite simple solution I have decrease the price to $500, @pradeepmdk I have assigned you, can you create the PR now and complete the checklist with urgency given this is a deploy blocker?

**Comment by pradeepmdk** [comment] 2023-08-18 10:22
sure @mountiny

**Comment by abdulrahuman5196** [comment] 2023-08-18 11:16
Kindly let me know once PR is ready I can review.

**Comment by pradeepmdk** [comment] 2023-08-18 11:18
@abdulrahuman5196 PR is ready

**Comment by flaviadefaria** [comment] 2023-08-18 11:26
@alexpensify I'm heading OoO for a week so reassigning to you in the meantime, thanks!

**Comment by mountiny** [comment] 2023-08-18 12:11
I can take this over from robert 🙇

**Comment by yuwenmemon** [comment] 2023-08-18 18:54
Fix has been deployed to staging ✅

**Comment by alexpensify** [comment] 2023-08-21 17:59
No update, waiting for automation to kick in here.

**Comment by alexpensify** [comment] 2023-08-28 23:05
I'm catching up from being OOO, I will prepare the payment steps tomorrow.

**Comment by alexpensify** [comment] 2023-08-30 01:36
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @pradeepmdk $750
-  Contributor+ that helped on the issue and/or PR - @abdulrahuman5196 $750 

Upwork Job: https://www.upwork.com/jobs/~01b8ef599b7ac8134d

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: The amount is less per @mountiny's feedback [here](https://www.upwork.com/jobs/~01b8ef599b7ac8134d) but there is an urgency bonus. I'm calculating half of the base amount at $250, so the final amount given would be $750. 

Let me know if there is any feedback or else I will complete the payment tomorrow. Thanks!

**Comment by alexpensify** [comment] 2023-08-30 22:41
Everyone has been paid in Upwork. @abdulrahuman5196 please complete the checklist and we can close ou this GH. Thanks!

**Comment by alexpensify** [comment] 2023-09-01 20:21
@abdulrahuman5196 - we are waiting to close this GH until the checklist is complete, can we get an update soon? Thanks!

**Comment by abdulrahuman5196** [comment] 2023-09-04 10:19
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/20251/files#r1314735902

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. This is a minor fix and won't be beneficial to add regression test case.

@alexpensify Sorry for the delay. Completed the checklist

**Comment by alexpensify** [comment] 2023-09-04 15:01
Thanks! I'm going to close now-- great work team.

**Closed by alexpensify** 2023-09-04 15:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
