### ISSUE TITLE
[HOLD for payment 2023-10-30] Large legal name are not saved and no error message is displayed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19821] opened 2023-05-30 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open personal details
5. Open legal name
6. Enter maximum length first name, last name in legal name and click on save
7. Go back twice and revisit legal name
## Expected Result: 
When the character limit is exceeded a counter should be displayed beneath the field in error as [implemented here](https://github.com/Expensify/App/pull/28722#issuecomment-1747570990).

## Actual Result: 
App does not save large legal name and displays older saved name when we revisit the menu.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:**  1.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ccf8d513-f997-4ef2-b707-58862a880d5d

https://github.com/Expensify/App/assets/43996225/87ac932b-ff8e-47b4-b539-0e91428d338f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685263179032739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-05-30 18:36
Yep, that makes sense to me. Added a hold, let's take care of it in one place consistently. 👍

**Comment by trjExpensify** [comment] 2023-06-02 10:19
No change. Should have dropped this to weekly now it's on hold.

**Comment by trjExpensify** [comment] 2023-06-21 22:40
Joe kicked off that discussion.

**Comment by trjExpensify** [comment] 2023-07-03 10:24
@joekaufmanexpensify where are we at with the next steps on https://github.com/Expensify/App/issues/18647?

**Comment by joekaufmanexpensify** [comment] 2023-07-05 12:48
I just posted [an update](https://expensify.slack.com/archives/C01GTK53T8Q/p1688561105668269?thread_ts=1686863510.616919&cid=C01GTK53T8Q) on the slack discussion this morning!

**Comment by trjExpensify** [comment] 2023-07-12 10:04
Awesome, thanks Joe!

**Comment by trjExpensify** [comment] 2023-07-24 10:48
Joe is progressing the linked issue still. :)

**Comment by trjExpensify** [comment] 2023-08-02 16:38
Proposal in the linked issue is being approved!

**Comment by trjExpensify** [comment] 2023-08-07 09:44
Proposal in the linked issue is awaiting a review from @youssef-lr.

**Comment by trjExpensify** [comment] 2023-08-10 21:24
Still on hold.

**Comment by trjExpensify** [comment] 2023-08-14 09:54
Linked issue needs a backend change as a next step before I can retest this. :)

**Comment by trjExpensify** [comment] 2023-08-21 11:17
@joekaufmanexpensify @youssef-lr - did [that PR mentioned here](https://github.com/Expensify/App/issues/18647#issuecomment-1682973741) go up?

**Comment by trjExpensify** [comment] 2023-08-30 13:05
@joekaufmanexpensify do you think we should take care of the limit on this one in the imp of #18647?

**Comment by joekaufmanexpensify** [comment] 2023-08-30 17:34
Ah, we decided to leave legal first and last name at 50 characters each. We aren't changing them in that issue. So I'd think we could take this off of hold and fix this now!

**Comment by trjExpensify** [comment] 2023-08-30 17:42
Excellent, so in terms of the expectation here: 

1. Legal name (first and last) are limited to 50 characters each 
2. We follow our standard forms pattern to display the error on blur. 

For #2, is there standardised wording we're using for character length to follow here?

**Comment by joekaufmanexpensify** [comment] 2023-08-30 21:30
>Legal name (first and last) are limited to 50 characters each

Yep!

>We follow our standard forms pattern to display the error on blur.

That's interesting. We hadn't discussed error messages for these fields, but that's a good point. I guess it is a bit odd that there is no error right now. Are you thinking that if you try and exceed the limit for a field, rather than stop the cursor, we'd unfocus the field and display an error?

**Comment by trjExpensify** [comment] 2023-08-30 21:32
Ah, so what's the proposed handling otherwise for like pasting more character than the limit into the field? Do we auto trim it to the character length allowed or display an error if you click off the field?

**Comment by joekaufmanexpensify** [comment] 2023-08-31 21:46
Noting that @trjExpensify and I discussed this further today. Going to bring a discussion about error handling to the existing slack thread tomorrow!

**Comment by trjExpensify** [comment] 2023-09-04 09:31
Thanks, @joekaufmanexpensify! Mind linking it here when you do?

**Comment by joekaufmanexpensify** [comment] 2023-09-05 14:59
Yep I will!

**Comment by trjExpensify** [comment] 2023-09-11 11:34
So I think we're almost at a point discussing in another linked issue above about the expected handling. That said, I think this will still be held on the issue that first introduces that character limit pattern.

**Comment by trjExpensify** [comment] 2023-09-15 14:26
Same, Melv.

**Comment by trjExpensify** [comment] 2023-09-18 09:46
Same spot, Melv.

**Comment by trjExpensify** [comment] 2023-09-20 11:25
Same! @joekaufmanexpensify when do you think we'll be good to go here?

**Comment by joekaufmanexpensify** [comment] 2023-09-21 03:38
We are still ironing out the error pattern for the counter [here. ](https://github.com/Expensify/App/issues/25804#issuecomment-1728717311) I actually just tagged you in one question there, which should be one of the last things we need to decide.

**Comment by trjExpensify** [comment] 2023-09-21 09:40
Commented!

**Comment by trjExpensify** [comment] 2023-09-27 07:58
Same, Melv!

**Comment by trjExpensify** [comment] 2023-10-02 14:44
Commented on the linked issue, getting closer.

**Comment by trjExpensify** [comment] 2023-10-06 00:32
No change.

**Comment by trjExpensify** [comment] 2023-10-09 10:57
PR is in review on the character counter. Asking [here](https://github.com/Expensify/App/issues/25804#issuecomment-1752786224) about whether we will even need a PR for this issue specifically, or if we just need to pay out the bug report when #18647 is done.

**Comment by trjExpensify** [comment] 2023-10-13 17:03
Linked PR is still in review!

**Comment by trjExpensify** [comment] 2023-10-16 13:27
Alrighty, [this PR](https://github.com/Expensify/App/pull/28722#issuecomment-1747570990) is now on prod. I'm going to open this up for proposals to add the character counter as implemented in that PR.

**Comment by srikarparsi** [comment] 2023-10-16 19:07
Looks good to me too, thanks!

**Comment by trjExpensify** [comment] 2023-10-30 12:21
Thanks, @fedirjh! We have this test for legal name in personal details. I think we suggest adding to it, so I've created an issue for that.

**Comment by trjExpensify** [comment] 2023-10-30 12:22
Moving on to confirm the payments due here: 

- $750 to @dukenv0307 for the bug fix & #urgency bonus 
- $750 to @fedirjh for the C+ review & #urgency bonus 
- $50 to @dhanashree-sawant for the bug report

Urgency bonus applies because the issue was assigned on Oct 16th ~6pm (GMT) and approved on Oct 19th ~4pm (GMT) within the 3 days window. 

Agreed? Let me know and I'll proceed with the offers.

**Comment by dhanashree-sawant** [comment] 2023-10-31 05:31
Hi @trjExpensify, the reporting bonus will be 250$ as the issue is raised before august 30.

**Comment by trjExpensify** [comment] 2023-10-31 14:07
Ah yes, of course. So In fact the payouts are as follows based on the prior to Aug 30th rates: 

- $1500 to @dukenv0307 for the bug fix & #urgency bonus
- $1500 to @fedirjh for the C+ review & #urgency bonus
- $250 to @dhanashree-sawant for the bug report

**Comment by trjExpensify** [comment] 2023-11-01 10:30
Settled up with everyone, closing!

**Closed by trjExpensify** 2023-11-01 10:30 UTC
Labels: External, Daily, Awaiting Payment, Bug
