### ISSUE TITLE
[$250] mWeb - room- Inviting a previously unknown user to room displays member count incorrectly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46298] opened 2024-07-26 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a room chat -- header -- invite
3. Enter an email you have not previously had contact with eg: [jaihanumanblog+1111@gmail.com](mailto:jaihanumanblog+1111@gmail.com)
and invite to room
4. Tap back button
5. Note members count

## Expected Result:
Inviting an user to room via secondary contact must display member count correctly

## Actual Result:
Inviting an user to room via secondary contact must display member count correctly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/user-attachments/assets/4791a6fd-da17-4143-a063-6271aed4beec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5145e9ee0c2aee8</li>
        <li>Upwork Job ID: 1818427399700311066</li>
        <li>Last Price Increase: 2024-07-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by lanitochka17** [comment] 2024-07-26 13:21
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-07-26 13:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - room-Inviting an user to room via secondary contact displays member count incorrectly
### What is the root cause of that problem?
The issue is not caused by using the secondary contact to add a member to a room but instead when a user adds a member who's personal detail doesn't exist in onyx a new optimistic personal detail is created then after a while the real personal detail representing the member comes and the optimistic personal detail will be deleted but the accountID of the optimistic personal detail still exists in `report.participants` list so the members count will be wrong as we display the participants length here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/ReportDetailsPage.tsx#L305-L306
### What changes do you think we should make in order to solve the problem?

We should filter particpants whose personal details doesn't exist just the same as what we use in RoomMemebersPage here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/RoomMembersPage.tsx#L174-L180
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-26 13:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 room-Inviting a user who you have no contact before displays member count incorrectly
### What is the root cause of that problem?
The issue is not caused by using the secondary contact to add a member to a room (as indicated in OP) but instead when a user adds a member who's personal detail doesn't exist in onyx a new optimistic personal detail is created then after a while the real personal detail representing the member comes from BE and the optimistic personal detail will be deleted but the accountID of the optimistic personal detail still exists in `report.participants` list so the members count will be wrong as we display the participants length here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/ReportDetailsPage.tsx#L305-L306
### What changes do you think we should make in order to solve the problem?

We should filter particpants whose personal details doesn't exist just the same as what we did in RoomMemebersPage here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/RoomMembersPage.tsx#L174-L180
We should change 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/ReportDetailsPage.tsx#L138-L141
to
```
const participants = useMemo(() => {
        const shouldExcludeHiddenParticipants = !isGroupChat && !isSystemChat;
        const participantAccountIDs = ReportUtils.getParticipantsAccountIDsForDisplay(report, shouldExcludeHiddenParticipants);
        return participantAccountIDs?.filter((accountID) => !!personalDetails?.[accountID]);
    }, [report, isGroupChat, isSystemChat, personalDetails]);
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-26 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 room-Inviting a user who you have no contact before displays member count incorrectly
### What is the root cause of that problem?
The issue is not caused by using the secondary contact to add a member to a room (as indicated in OP) but instead when a user adds a member who's personal detail doesn't exist in onyx a new optimistic personal detail is created then after a while the real personal detail representing the member comes from BE and the optimistic personal detail will be deleted but the accountID of the optimistic personal detail still exists in `report.participants` list so the members count will be wrong as we display the participants length here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/ReportDetailsPage.tsx#L305-L306
### What changes do you think we should make in order to solve the problem?

We should filter particpants whose personal details doesn't exist just the same as what we did in RoomMemebersPage here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/RoomMembersPage.tsx#L174-L180
We should change 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/ReportDetailsPage.tsx#L138-L141
to
```
const participants = useMemo(() => {
        const shouldExcludeHiddenParticipants = !isGroupChat && !isSystemChat;
        const participantAccountIDs = ReportUtils.getParticipantsAccountIDsForDisplay(report, shouldExcludeHiddenParticipants);
        return participantAccountIDs?.filter((accountID) => !!personalDetails?.[accountID]);
    }, [report, isGroupChat, isSystemChat, personalDetails]);
```
_We can also check and do the same for workspace members too if needed._
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-26 14:04
@stephanieelliott the title of the OP is a lit bit misleading as it suggests the problem is caused by using the secondary contact to invite the member but the problem is caused by the member being invited was a member with which the current user had no contact before. So to reproduce it, you should test by adding a member with which you had no contact before. 
And also I suggest you update the title of the issue accordingly Thx. 👍

**Comment by bernhardoj** [comment] 2024-07-27 06:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inviting user we never chat before to a room will make an extra count to the room member count.

### What is the root cause of that problem?
When we are searching for a new user, the app will generate a random optimistic account ID.
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/OptionsListUtils.ts#L1748-L1749
When we invite the user, the app will optimistically merge the generated account ID to the room participants.
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/actions/Report.ts#L2809-L2836

However, we never clear the optimistic report participant. This logic is used for both invite to room and group, but the issue doesn't happen in a group chat because the API for invite to group chat returns a response when success that will clears the optimistic report participant.

### What changes do you think we should make in order to solve the problem?

Fix it in the BE so invite to room also returns a response to clear the optimistic report participant.

OR

Fix it in the FE by clearing the optimistic report participant in success data.
```js
const participantsSuccessData = inviteeAccountIDs.reduce(
    (reportParticipants, accountID: number) => ({...reportParticipants, [accountID]: null}),
    {},
);
const successData: OnyxUpdate[] = [
    {
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
        value: {
            participants: participantsSuccessData,
            pendingChatMembers: successPendingChatMembers,
        },
    },
];
```

**Comment by stephanieelliott** [comment] 2024-07-30 23:22
Thanks @FitseTLT! I see what you mean -- updated the title and action steps to make that more clear.

**Comment by stephanieelliott** [comment] 2024-07-30 23:24
Given that it affects any user you've not previously had contact with (not secondary logins) and persists on the workspace, I think this is worth fixing. Adding labels to get the proposals reviewed.

**Comment by dangrous** [comment] 2024-08-02 20:03
Okay yep, I think it makes the most sense to copy the group chat behavior on the backend. I should be able to get to that early next week!

To confirm, if we do that, we shouldn't need any front end fixes, right?

**Comment by dangrous** [comment] 2024-08-05 17:24
This did need an incredibly minor front end adjustment, so I went ahead and did that myself. Both PRs will be in review in a sec!

**Comment by stephanieelliott** [comment] 2024-08-08 03:00
The second PR is held on https://github.com/Expensify/App/pull/46825 which is merged but not yet on prod , so we should be able to resume this soon.

**Comment by dangrous** [comment] 2024-08-09 15:28
still waiting on deploy to prod, will likely be Monday due to earnings, Friday...

**Comment by dangrous** [comment] 2024-08-14 15:15
So this ends up with the correct amount, but it takes a while to get there. It doesn't get higher than it should but if I'm the only person in a room and then I invite another person, it stays 1 for a while, before switching to 2. @ZhenjaHorbach (or others) do you want to give this a look and see if there's anything we can do optimistically on the front end that might make this cleaner?

Or if I need to update the backend again we can do that.

**Comment by dangrous** [comment] 2024-08-14 18:27
Oh weird! I just tested again (in order to take the video) and it works like a charm. Maybe something was happening on the backend.

Are we good to close, or do we need any payments handled?

**Comment by stephanieelliott** [comment] 2024-08-16 01:18
Hey @ZhenjaHorbach I extended the offer to you in Upwork, can you accept when you get a sec? https://www.upwork.com/nx/wm/offer/103546715

**Comment by stephanieelliott** [comment] 2024-08-17 01:44
Summarizing payment on this issue: 

 - Contributor: N/A internal 
 - Contributor+: @ZhenjaHorbach $250 via Upwork -- PAID 
 
 Upwork job is here: https://www.upwork.com/jobs/~01b5145e9ee0c2aee8

**Closed by stephanieelliott** 2024-08-17 01:44 UTC
Labels: Reviewing, Weekly, Internal, Help Wanted, Bug
