### ISSUE TITLE
[$1000] Getting “That page is nowhere to be found” error when reloading a failed contact method

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19287] opened 2023-05-19 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to contact methods page
2. Add a new contact method which is not part of any existing account.
3. Keep adding and removing this same method so that you start getting “too many attempts” error or "failed to add this contact method"
4. Now add this one last time. 
5. Click into the contact method to open the detailed page for that contact method.
6. Reload the browser.
7. Notice we are getting “This page is nowhere to be found error”.

## Expected Result:
Instead of getting error user should be navigated to “Contact methods page”.
## Actual Result:
Getting “This page is nowhere to be found” error.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fb483038-5769-43b1-a08a-e677b7ffc6f8

https://github.com/Expensify/App/assets/43996225/796398dc-11c5-4125-81d9-d69516569e04

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hasebsiddiqui, @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684278673009539, [expensify.slack.com/archives/C049HHMV9SM/p1682204153817999](https://expensify.slack.com/archives/C049HHMV9SM/p1682204153817999)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b7ffb51f8035d3f</li>
        <li>Upwork Job ID: 1661601448383819776</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-05-22 04:21
Unable to reproduce:

https://github.com/Expensify/App/assets/59587260/06acf3c7-5ccd-4d07-97f0-05a7e2ae8554

@hasebsiddiqui could you please try again and let me know if you're still experiencing this issue?

**Comment by hasebsiddiqui** [comment] 2023-05-22 09:32
@kadiealexander You need to open the detail page of failed contact to reproduce the error. 

https://github.com/Expensify/App/assets/43096403/5b5f7fc5-e4df-47f2-a440-b312cfc13598

**Comment by hasebsiddiqui** [comment] 2023-05-23 21:58
@kadiealexander Any update?

**Comment by kadiealexander** [comment] 2023-05-25 05:12
Thanks for that detail @hasebsiddiqui, I reproduced it:

https://github.com/Expensify/App/assets/59587260/f5ef885c-89e3-4a9a-84d6-a12f2dbaf340

**Comment by kadiealexander** [comment] 2023-05-25 05:14
Sorry Sonia, not sure why you got assigned when I'm already assigned!

**Comment by bernhardoj** [comment] 2023-05-25 05:20
Dupe of this https://github.com/Expensify/App/issues/17849

**Comment by kadiealexander** [comment] 2023-05-25 05:43
Yes, that one was closed in favour of this one.

**Comment by amyevans** [comment] 2023-05-25 22:08
Yes it's a slightly different symptom of the same underlying problem from #17827, so will be fixed there.

I add `hello@hi.com` as a contact method and the route I'm on is http://localhost:8080/settings/profile/contact-methods/hello%40hi.com/details
![error](https://github.com/Expensify/App/assets/7277067/e0ca6125-571d-423c-94d7-e108c6eef97b)

When I refresh that page, `OpenApp` returns the `loginList` from the server and uses `set`, hence overwriting the `hello@hi.com` entry.
![refresh](https://github.com/Expensify/App/assets/7277067/4752c7ac-f3db-43b2-83e7-bf725897c68d)

**Closed by amyevans** 2023-05-25 22:08 UTC
Labels: External, Daily, Help Wanted, Bug
