### ISSUE TITLE
[$1000] Split bill - Bill splitting error when in 2 tabs

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26216] opened 2023-08-29 15:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any group chat
2. Click the "+" icon and select "Split bill"
3. Input amount of money and click "Next"
4. Copy the URL on the browser
5. Open a new tab -> Paste the copied URL
6. Click button "Split bill" in 1st tab
7. Click  "< Cash" on modal of 2nd tab
8. Input amount of money and click "Next" again

## Expected Result:
navigate to "Split bill" modal

## Actual Result:
After pressing "Next" button, the screen is returned to the amount input modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/66efa3f3-7583-4d48-9e84-e30c7c676501

https://github.com/Expensify/App/assets/115492554/0ba5d79e-57cf-4ad7-8a33-8e3d80ac353f

https://github.com/Expensify/App/assets/115492554/82d3048f-c9ae-4e5c-b69f-4df34ecfad97

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Le Thi Thu Thuy

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692692134315659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cdd1bc133e52a9a</li>
        <li>Upwork Job ID: 1699156283918704640</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-09-05 20:33
Not overdue. This was just triaged, Melv.

**Comment by s77rt** [comment] 2023-09-11 11:03
Not overdue. Looking for proposals

**Comment by s77rt** [comment] 2023-09-16 00:34
Not overdue. Still looking for proposals

**Comment by s77rt** [comment] 2023-09-18 13:15
Same ^ Still looking for proposals

**Comment by johncschuster** [comment] 2023-09-19 21:41
I'm going to raise the bounty

**Comment by ilkeruyanik** [comment] 2023-09-20 05:10
I couldn't reproduce it. Can you reproduce it?

**Comment by s77rt** [comment] 2023-09-23 23:21
Not overdue. I think this may not be necessary a bug. The money request / split data are stored in Onyx and it's shared across tabs. We may need to refactor the IOU flow to fix this.

**Comment by johncschuster** [comment] 2023-09-27 00:09
@s77rt you mentioned before that you think we may need to refactor the IOU flow to fix this. Do you know if this has been talked about anywhere? If not, I think we should raise the discussion.

**Comment by s77rt** [comment] 2023-09-27 00:46
@hayata-suenaga I think we talked about this and back then we had IOU todos that the refactor was not convenient. Do we still have upcoming IOU work or can we go with the refactor?

The refactor would mainly remove Onyx usage i.e. do not store participants, amount, etc in Onyx

**Comment by hayata-suenaga** [comment] 2023-09-27 02:35
I'm checking with the internal team to get opinions on if this refactoring is something we want to pursue.

**Comment by mvtglobally** [comment] 2023-09-28 03:18
Issue not reproducible during KI retests. (First week)

**Comment by s77rt** [comment] 2023-10-02 11:40
@hayata-suenaga Any updates on how we should handle this?


Still looking for proposals...

**Comment by johncschuster** [comment] 2023-10-05 20:48
@hayata-suenaga bump!

**Comment by hayata-suenaga** [comment] 2023-10-06 01:39
confirming with @tgolen about this as he is working on a refactoring involving the Money Request flow

**Comment by s77rt** [comment] 2023-10-09 14:46
I think we agreed on closing this one. Multi tabs support is not a priority for now.

**Comment by hayata-suenaga** [comment] 2023-10-10 01:31
forgot to close this one 😓

**Closed** 2023-10-10 01:31 UTC
Labels: Engineering, Daily, Internal, Bug
