### ISSUE TITLE
[$250] Request Money - Inconsistent Padding Between Error Message and Save Button in Tax value section

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39922] opened 2024-04-09 12:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1,Navigate to Profile > Workspace > Create Workspace.
2, Enable tax feature under More Features > Tax Rate 1.
3, Go to the Value section, clear the number, and attempt to save. Observe the padding between the save button and the error message.
4, Access FAB > Request Money > Add Amount > Choose Split With.
5, Proceed to the Tax Amount section and attempt to save without entering anything. Note the padding between the error message and the save button.
6, The padding between the error message and the save button in the Tax Value section and Tax Amount section is inconsistent.

## Expected Result:
The padding between the error message and the save button in the Tax Value section should be consistent with other number value sections.

## Actual Result:
The padding between the error message and the save button in the Tax Value section increases significantly and is inconsistent with other number value sections.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4628c24a-b4ed-4863-a071-aefd2eb9b818

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d37ed51248fa5380</li>
        <li>Upwork Job ID: 1777812961038524416</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-04-09 12:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money - Inconsistent Padding Between Error Message and Save Button in Tax value section

### What is the root cause of that problem?
We are giving extra padding bottom for non touch screen here
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/components/AmountForm.tsx#L227-L228
### What changes do you think we should make in order to solve the problem?

We should remove it and always give it margin bottom 0
### What alternative solutions did you explore? (Optional)

**Comment by izarutskaya** [comment] 2024-04-09 12:26
We think this issue might be related to the #collect project.

**Comment by FitseTLT** [comment] 2024-04-09 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money - Inconsistent Padding Between Error Message and Save Button in Tax value section

### What is the root cause of that problem?
We are giving extra padding bottom for non touch screen here
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/components/AmountForm.tsx#L227-L228
### What changes do you think we should make in order to solve the problem?

We should remove it and always give it margin bottom 0
```
                        style={[styles.pAbsolute, styles.b0, styles.mb0, styles.ph5, styles.w100]}

```
just like amount form for e.g.
https://github.com/Expensify/App/blob/ad9b5d7a2ee54ad6379538b84c322fc29b2a6adb/src/pages/iou/steps/MoneyRequestAmountForm.tsx#L315-L316
### What alternative solutions did you explore? (Optional)
Or we can leave margin bottom style to let it be zero by default

**Comment by hungvu193** [comment] 2024-04-10 02:05
@Krishna2323's [proposal here](https://github.com/Expensify/App/issues/39922#issuecomment-2045112345) is straightforward and looks good to me 
👀 🎀 👀  C+ reviewed

**Comment by hungvu193** [comment] 2024-04-10 02:05
🎀 👀 🎀

**Comment by lakchote** [comment] 2024-04-10 07:26
@Krishna2323's proposal LGTM

**Comment by hungvu193** [comment] 2024-04-11 00:05
@Krishna2323 do you have any ETA for the PR?

**Comment by hungvu193** [comment] 2024-04-11 10:18
> @hungvu193, PR is ready for video, only the recording for android native is remaining, there are some build issues.

Cool. That's fine since Android build is failing after new arch was enable, can you check all checklist please?

**Comment by MitchExpensify** [comment] 2024-05-06 20:30
**Payment summary**:

C $250 @Krishna2323 
C+ $250 @hungvu193

**Comment by hungvu193** [comment] 2024-05-29 23:38
We're good to close this one ☝️

**Closed** 2024-05-30 07:26 UTC
Labels: Reviewing, External, Monthly, Bug
