### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Web - Chat - The deleted message reappears when navigating to another chat and returning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27569] opened 2023-09-15 22:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open any chat
2.	Write a message but do not send it; instead, select all text and delete it
3.	After deleting, press Enter immediately
4.	Switch to a different chat and then return to the original chat
5.	Observe that the deleted message reappears

## Expected Result:
The message should be deleted permanently

## Actual Result:
The message reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a386f6f0-b6a1-4af7-a00d-8d3e320ffcee

https://github.com/Expensify/App/assets/78819774/2836b6e3-f59d-4004-9cf9-44d8eb3bdc0e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694585707620149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0cd42dfc8371fd8</li>
        <li>Upwork Job ID: 1702812597778710528</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26730775</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-15 23:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - Chat - The deleted message reappears when navigating to another chat and returning.

### What is the root cause of that problem?
- Currently, clicking on send button or press ENTER will call ```submitForm``` function:
https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L248-L267
https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L235-L243
- When deleting all text input (for example "**abcdef**") and clicking on send button or pressing on ENTER:

1. Firstly, ```debouncedSaveReportComment.cancel();``` called to ignore the before saveReportComment action - in this case is saving the report comment as an empty string - ```Report.saveReportComment(reportID, '')```. So after this step, the reportComment is still "abcdef" text
2. After that, ```composerRef.current.prepareCommentAndResetComposer()``` is called but it will check if the current comment is empty or not, if true, does not run the remaining logic.
3. So the report comment is still saved as  "abcdef", that lead to the bug 

### What changes do you think we should make in order to solve the problem?
- We can make sure the ``updateComment(' ')``` is called regardless the comment length is greater than 0 or not like below: 
```
    const prepareCommentAndResetComposer = useCallback(() => {
        const trimmedComment = commentRef.current.trim();
        const commentLength = ReportUtils.getCommentLength(trimmedComment);
        updateComment('');
        // Don't submit empty comments or comments that exceed the character limit
        if (!commentLength || commentLength > CONST.MAX_COMMENT_LENGTH) {
            return '';
        }
```
- Also in the PR detail, we need to ignore the ```updateComment(' ')``` in case exceeding the maximum character
### What alternative solutions did you explore? (Optional)

### Result

[Screencast from 14-09-2023 14:43:07.webm](https://github.com/Expensify/App/assets/141406735/becf9b10-5b74-4c57-b563-8208b752753c)

**Comment by mananjadhav** [comment] 2023-09-17 19:03
I think @bernhardoj's proposal to call debounce below if would be better.

🎀 👀 🎀 C+ reviewed.

**Comment by DylanDylann** [comment] 2023-09-18 01:21
@mananjadhav Update my proposal https://github.com/Expensify/App/issues/27569#issuecomment-1722006714
### What alternative solutions did you explore? (Optional)
- Currently, the ```const submitForm``` is called regardless the ```isSendDisabled``` is true or not. I think we don't need to call it in when the isSenDisable is true like below:
```
    const submitForm = useCallback(
        (e) => {
            if (isSendDisabled) return;
            if (e) {
                e.preventDefault();
            }

            // Since we're submitting the form here which should clear the composer
            // We don't really care about saving the draft the user was typing
            // We need to make sure an empty draft gets saved instead
            debouncedSaveReportComment.cancel();
```
- If the ```isSendDisabled``` is true, we stop calling the remaining logic, so the bug ```The deleted composer message shows again if pressing enter after deleting the whole message/text.``` will be fixed

**Comment by tjferriss** [comment] 2023-09-18 03:22
I'm able to reproduce the bug. The external label has already been added.

**Comment by DylanDylann** [comment] 2023-09-18 11:39
@cristipaval please help check my comment [here](https://github.com/Expensify/App/issues/27569#issuecomment-1722640991)

**Comment by tjferriss** [comment] 2023-09-26 07:32
Payment Summary:

- Reviewer @mananjadhav $750
- Contributor @bernhardoj $750
- Reporter @usmantariq96 $250

Eligible for speed bonus

**Comment by cristipaval** [comment] 2023-10-02 09:53
The payment is due today, Melv. @mananjadhav still to do the checklist, though.

**Comment by mananjadhav** [comment] 2023-10-02 16:59
I couldn't pinpoint a specific PR as the composer has been refactored quite a lot. 

That being said  @tjferriss I think it makes sense to add a regression test here. We can use QA steps from the PR. wdyt @cristipaval?

**Comment by tjferriss** [comment] 2023-10-02 22:03
@bernhardoj payment has been sent. 

@usmantariq96 I just sent you an offer via Upworks for the reporting bonus.

**Comment by usmantariq96** [comment] 2023-10-03 03:33
@tjferriss I haven't received any offer yet.

**Comment by tjferriss** [comment] 2023-10-03 17:40
I'm sorry, I must have selected the wrong person. Can you please apply to the posting here: https://www.upwork.com/jobs/~01c0cd42dfc8371fd8

**Comment by JmillsExpensify** [comment] 2023-10-05 21:05
$750 payment approved for @mananjadhav based on BZ summary

**Comment by tjferriss** [comment] 2023-10-05 21:19
@usmantariq96 can you please apply to the job so we can get you paid out?

**Comment by usmantariq96** [comment] 2023-10-06 03:26
@tjferriss applied
Thanks

**Comment by tjferriss** [comment] 2023-10-06 20:17
Offer sent

**Comment by usmantariq96** [comment] 2023-10-07 02:12
Offer accepted
Thanks

**Comment by cristipaval** [comment] 2023-10-09 21:31
What's the payment status here? Can we close the issue?

**Comment by tjferriss** [comment] 2023-10-11 03:49
The payment has been sent to @usmantariq96 so we can close it now.

**Closed by tjferriss** 2023-10-11 03:49 UTC
Labels: External, Daily, Awaiting Payment, Bug
