### ISSUE TITLE
[$500] The conversation is not displayed in the LHN of the recipient with the status "Hidden"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35371] opened 2024-01-30 10:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211589
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account - A
3. In incognito mode, open https://staging.new.expensify.com/
4. Log in with a gmail account - B that has not previously communicated with account A
5. From account A, send messages to user B
## Expected Result:
A conversation must be displayed in the LHN even if the recipient is a new user in "Hidden" status to the sender.

## Actual Result:
A conversation is not displayed in the LHN if the recipient is a new user in "Hidden" status to the sender

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/45c6779a-ae19-4180-be51-bc0d5cc970ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153c47dbf5ec93934</li>
        <li>Upwork Job ID: 1752278430803443712</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2024-02-06 00:56
Bump @tienifr on the above!

**Comment by greg-schroeder** [comment] 2024-02-09 03:07
Seems we're still unclear on expected behavior here, is that right?

**Comment by greg-schroeder** [comment] 2024-02-12 21:41
looks like we're waiting on @francoisl or @yuwenmemon to weigh in here https://github.com/Expensify/App/issues/35371#issuecomment-1935725930

**Comment by francoisl** [comment] 2024-02-12 23:28
Hm I'm not sure of the expected behavior either. @srikarparsi it looks like you added the hidden logic in [this PR](https://github.com/Expensify/Auth/blob/c4f8235119823a415525b08293df640aed5c8cc9/auth/command/OpenReport.cpp#L341-L343), can you confirm if there should be a conversation visible in the LHN in this case please?

**Comment by srikarparsi** [comment] 2024-02-13 01:14
Hey, just ran through a couple of cases and it seems like there's only a problem with "Hidden" users (as the title suggests but just wanted to double check)

The expected behavior is:
1. Send a message from User A to User B
2. Ensure the message shows up for User B

> can you confirm if there should be a conversation visible in the LHN in this case please?
Yes, there should be a conversation visible in the LHN in this case.

And this expected behavior holds for all cases except for when the user is "Hidden" (I think this happens when the user is not on the same policy so we want to keep their email secure).

Also, in regards to this comment:

> it looks like you added the hidden logic in [this PR](https://github.com/Expensify/Auth/blob/c4f8235119823a415525b08293df640aed5c8cc9/auth/command/OpenReport.cpp#L341-L343)

We [change](https://github.com/Expensify/Auth/pull/9531/files#diff-7d3f89cee9578c11d06f3f40aae607662648d2aab066d79e6b14d73bb0c7ff9a) the notification preference to `always` for all users when anyone else posts a comment in the report. I think there might be something with the updates not sending if the users don't have each others' contact informations (which is why the user is Hidden to the other)?

**Comment by francoisl** [comment] 2024-02-14 00:41
Thanks Srikar for the insight.

@tienifr it sounds like we can use your proposal to use `lastReadTime` to show the chat then?

**Comment by srikarparsi** [comment] 2024-02-15 09:04
User B should receive notification preference `always` for the report once User A comments on it.

**Comment by greg-schroeder** [comment] 2024-02-16 05:22
If that's the case, let's move this to `Internal`?

**Comment by greg-schroeder** [comment] 2024-02-19 21:48
Okay let us know what you think Franc

**Comment by francoisl** [comment] 2024-02-23 03:43
What seems to be happening is that user B receives the report summary with the `notificationPreference` set to `hidden`, and then `GetMissingOnyxMessages` returns the correct value `always`, but the report summary update is applied _after_ the response from GetMissingOnyxMessages, so it overwrites the `always` value to `hidden` in Onyx.

<img width="1384" alt="image" src="https://github.com/Expensify/App/assets/2229301/86a35f0f-00ee-460b-9b6f-5d2fbef479a3">

<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/2229301/2ce6392b-1ece-47d1-85ba-6d67eb8c7bd2">

The incorrect `hidden` is returned from `structureReportForOnyx()` in the backend, which is deprecated and there's an [internal issue](https://github.com/Expensify/Expensify/issues/364994) to get rid of it already. In the meantime, I'll see if there's a quick workaround in the meantime.

**Comment by greg-schroeder** [comment] 2024-02-27 03:49
Discussion ongoing

**Comment by greg-schroeder** [comment] 2024-03-02 00:20
@francoisl sorry to bug you on this one, but I'm a bit over my head at this point. Thoughts on [this comment](https://github.com/Expensify/App/issues/35371#issuecomment-1961558551)?

**Comment by greg-schroeder** [comment] 2024-03-09 02:27
No worries @francoisl, I understand. Let's check in again next week 👍

**Comment by francoisl** [comment] 2024-03-12 19:11
Ughhh no time for this one sorry.

**Comment by greg-schroeder** [comment] 2024-03-25 11:23
Okay perhaps we could revisit this week!

**Comment by greg-schroeder** [comment] 2024-03-26 04:29
Per team discussion closing this for now, reopen if you strongly disagree

**Closed by greg-schroeder** 2024-03-26 04:29 UTC
Labels: Engineering, Weekly, Internal, Bug
