### ISSUE TITLE
Split Bill -Split Bill flow is blocked after the final button "Split $XX" is clicked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22239] opened 2023-07-05 01:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com on Safari
2. Click FAB and select "Split Bill" or go to any group, click "+" and select "Split Bill"
3. Follow the flow to the last screen and click the final button "Split $XX"

## Expected Result:
"Spli Bill" flow finished successfully and IOU preview appeared in the group

## Actual Result:
"Split Bill" flow is blocked after the final button "Split $XX" is clicked. The cursor has a "Blocked" icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/da8b4939-183d-449a-85ba-fbbd97054ee6

https://github.com/Expensify/App/assets/78819774/ff8814d4-f044-42a2-af71-134d9f4d817b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-05 02:00
I can't reproduce on the latest staging

**Comment by JmillsExpensify** [comment] 2023-07-12 12:28
I'm also unable to reproduce this one on staging. Closing.

**Closed by JmillsExpensify** 2023-07-12 12:28 UTC
Labels: Daily, Overdue, Bug
