### ISSUE TITLE
Dev: Web - Cursor position is not at the end of the task title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22494] opened 2023-07-08 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Assign task" section
3. Enter a title and create task
4. After creating click on task title
5. Notice that the cursor position is not at the end of the message

## Expected Result:
Cursor position should be at the end of the task title message

## Actual Result:
Cursor position is not at the end of the task title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.38-3
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ec1bc0c8-44b7-4222-b51e-13fe792b49af

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688765673868159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-07-08 20:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Web - Cursor position is not at the end of the task title

### What is the root cause of that problem?
This is a known issue in React Native in multiline input, and it fixed in task description in this PR #20836, but I think we  may change title task multiline support in this issue #22495
### What changes do you think we should make in order to solve the problem?
I think we need to fix this issue and this #22495 in one PR by 
1. Removing this props `autoGrowHeight` and `textAlignVertical` and `containerStyles` 
2. and add new prop `submitOnEnter` here.
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/tasks/TaskTitlePage.js#L77

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2023-07-10 14:51
It sounds like this is a dupe, and if not, I don't think this is a bug.

**Comment by isabelastisser** [comment] 2023-07-10 15:28
@jasperhuangg should I apply the external label here?

**Comment by danieldoglas** [comment] 2023-07-10 16:05
Assigning @jasperhuangg

**Comment by isabelastisser** [comment] 2023-07-10 16:10
@danieldoglas should this be internal?

**Comment by danieldoglas** [comment] 2023-07-10 16:24
I don't think it needs to be internal, this is also not a deploy blocker.

**Comment by jasperhuangg** [comment] 2023-07-10 19:03
@danieldoglas thanks! Will investigate a fix today

**Comment by danieldoglas** [comment] 2023-07-17 16:37
I think this issue is related to https://github.com/Expensify/App/issues/21523#issuecomment-1637454102

**Comment by ayazhussain79** [comment] 2023-07-17 16:50
This #22494 issue was the regression of [PR ](https://github.com/Expensify/App/pull/20841)

**Comment by ayazhussain79** [comment] 2023-07-18 20:13
@danieldoglas this bug is fixed now [PR](https://github.com/Expensify/App/pull/22586) was merged 4 days ago

**Comment by jasperhuangg** [comment] 2023-07-18 22:25
This was fixed, let's get the reporter paid out and close this out! @isabelastisser

**Comment by isabelastisser** [comment] 2023-07-19 15:59
@ayazhussain79 I sent you an offer in Upwork.

All set!

**Closed by isabelastisser** 2023-07-19 15:59 UTC
Labels: Reviewing, Engineering, Daily, Needs Reproduction

**Comment by ayazhussain79** [comment] 2023-09-12 19:48
@isabelastisser can you please approve the payment on upwork

**Comment by isabelastisser** [comment] 2023-09-12 19:55
@ayazhussain79 The payment was made, thanks!

**Comment by ayazhussain79** [comment] 2023-09-12 20:51
Thank you
