### ISSUE TITLE
[$500] Web - Pencil icon appears for the last chat room when typing after popover is open from emoji reaction

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27046] opened 2023-09-08 17:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Open any chat from LHN
3. Send a message and react to the message
4. Open reaction detail by making right click
5. Type something and send the message
6. Open any other chat from LHN
7. Repeat steps 3 to 4
8. Type something
9. Observe the LHN

## Expected Result:
The pencil icon should only appear on the current chat

## Actual Result:
The pencil icon appears on the current and last chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/522f4757-16e7-44f9-a693-ca2692b60462

https://github.com/Expensify/App/assets/93399543/5de1a680-2b8c-4116-b254-4553a6937174

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693829484228389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b0e708164831d25</li>
        <li>Upwork Job ID: 1700197539850969088</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-09-08 22:45
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The pencil icon appears on the current and last chat


### What is the root cause of that problem?
`replaceSelectionWithText` that is responsible for text insertion at `selection` point is excessively called within `focusComposerOnKeyPress` which is a handler for various event including navigation blur/focus. This is unnecessary because `replaceSelectionWithText` is already being executed in an `useImperativeHandle` hook.

https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L387-L390

### What changes do you think we should make in order to solve the problem?
Remove `replaceSelectionWithText` from `focusComposerOnKeyPress` event handler, on line 388:
```
                   focus();
            // Remove this: replaceSelectionWithText(e.key, false);
        },
        [
            checkComposerVisibility, 
            focus, 
            // Remove this: replaceSelectionWithText
        ],
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeet-dhandha** [comment] 2023-09-09 02:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Editing the composer edits the previous route's composer too.

### What is the root cause of that problem?
- The issues is that when navigating to new report the previous report's composer is still mounted and thus editing the composer edits the previous route's composer too.

### What changes do you think we should make in order to solve the problem?
- The solution is to check if the `Navigation.getActiveRoute()` has current reportID or not. If not then early return the `updateComment` function.

```js
const isActiveReportID = Navigation.getActiveRoute().includes(reportID);
```

```js
const updateComment = useCallback(
        (commentValue, shouldDebounceSaveComment) => {
            if (!isActiveReportID) return; // early return if not active reportID
...rest
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by JmillsExpensify** [comment] 2023-09-13 09:09
Huh, that's odd. I agree we should resolve, so I'm triaging.

**Comment by JmillsExpensify** [comment] 2023-09-13 09:09
We're open for proposals.

**Comment by jeet-dhandha** [comment] 2023-09-13 09:12
Any thoughts on my proposal https://github.com/Expensify/App/issues/27046#issuecomment-1712394341

**Comment by misgana96** [comment] 2023-09-17 11:01
This is because the internal teams decided to disallow typing when popover  is open.

**Comment by mvtglobally** [comment] 2023-09-28 03:19
Issue not reproducible during KI retests. (First week)

**Comment by misgana96** [comment] 2023-09-28 03:27
> @JmillsExpensify @allroundexperts It is not reproducible anymore. This is because the internal teams decided to disallow typing when the popover is open. #27250
> 
> Am I eligible for the reporter bonus? The issue has been fixed by disabling typing when the popover is open.

**Comment by mvtglobally** [comment] 2023-10-05 03:06
Issue not reproducible during KI retests. (Second week)

**Comment by misgana96** [comment] 2023-10-06 11:48
@JmillsExpensify @allroundexperts It is not reproducible anymore. This is because the internal teams decided to disallow typing when the popover is open. #27250

Am I eligible for the reporter bonus? The issue has been fixed by disabling typing when the popover is open.

**Comment by JmillsExpensify** [comment] 2023-10-10 23:11
> Okay, so after some discussion, we've decided that it makes sense to disallow typing when any pop up is open, so we don't need to work on this issue - as this is now expected behavior. Thanks for your patience!

Given that we didn't award any reporting bonus for the other issue, I don't see why we're award it here either?

**Comment by misgana96** [comment] 2023-10-11 07:00
@JmillsExpensify The other issue is the expected behavior so they didn't award any reporting bonus, but here the issue is a valid issue and it was fixed by disallowing typing when any pop-up is open. I feel these two cases are different.

**Comment by JmillsExpensify** [comment] 2023-10-16 18:04
That's fair. Payment summary: $50 payment to @misgana96 issue reporting.

**Comment by misgana96** [comment] 2023-10-16 18:51
@JmillsExpensify I applied for the job.

**Comment by misgana96** [comment] 2023-10-16 19:28
Offer accepted.

**Comment by JmillsExpensify** [comment] 2023-10-16 19:41
Thanks, all paid out!

**Closed by JmillsExpensify** 2023-10-16 19:41 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by misgana96** [comment] 2023-10-16 19:47
Accepted. Thank you
