### ISSUE TITLE
[HOLD for payment 2023-12-13][$500]  Mention(@) and emoji(:) popup does not close when dragging a file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30153] opened 2023-10-23 02:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697872753258699

## Action Performed:
1. Open any Chat
2. Write @ or : and any emoji name, While the popup is open Drag a file onto the chat
Notice the popup does not dismiss

## Expected Result:
 Popup closes when dragging a file

## Actual Result:
Popup does not close when dragging a file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/c696f641-a448-4c1b-b11d-cf67921d1b9d

https://github.com/Expensify/App/assets/93399543/f03008a9-6a7c-4464-8060-1a6f0cd75c5b

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/a4ca642b-230c-452f-bd0f-bc477a7d0638

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebdf425a95b3b890</li>
        <li>Upwork Job ID: 1716273483340058624</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27579707</li>
<li>ishpaul777 | Contributor | 27579709</li>
<li>daveSeife | Reporter | 27579710</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-23 02:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Suggestions popup doesn't close when dragging a file

### What is the root cause of that problem?

We do nothing to close suggestions popup when dragging a file

### What changes do you think we should make in order to solve the problem?

1. Change the `updateShouldShowSuggestionMenuToFalse` function to receive `shouldShow` argument
Update
https://github.com/Expensify/App/blob/35aa3db0fe2a139c6b68cb6d3f6a2b0fd252349e/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L112-L119
https://github.com/Expensify/App/blob/35aa3db0fe2a139c6b68cb6d3f6a2b0fd252349e/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L240-L247

to
```
    const updateShouldShowSuggestionMenuToFalse = useCallback((shouldShow) => {
        setSuggestionValues((prevState) => {
            if (prevState.shouldShowSuggestionMenu !== shouldShow) {
                return {...prevState, shouldShowSuggestionMenu: shouldShow};
            }
            return prevState;
        });
    }, []);
```

2. Update
https://github.com/Expensify/App/blob/35aa3db0fe2a139c6b68cb6d3f6a2b0fd252349e/src/pages/home/report/ReportActionCompose/Suggestions.js#L74-L77
to
```
    const updateShouldShowSuggestionMenuToFalse = useCallback((shouldShow = false) => {
        suggestionEmojiRef.current.updateShouldShowSuggestionMenuToFalse(shouldShow);
        suggestionMentionRef.current.updateShouldShowSuggestionMenuToFalse(shouldShow);
    }, []);
```

3. Add the following code to [Suggestions](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/Suggestions.js)
```
    const {isDraggingOver} = useContext(DragAndDropContext);

    ...
    useEffect(() => {
        updateShouldShowSuggestionMenuToFalse(!isDraggingOver);
    }, [isDraggingOver])
```

This works as expected

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2023-10-23 06:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Mention and emoji suggestions appear over the drop screen when dragging a file on to the composer with suggestions open.
### What is the root cause of that problem?
I think the expected behaviour should be not necessarily to close the suggestions popup. Instead we want the 'Drop to Upload' layover should be over the suggestions popup.
We are using this host here to show suggestions.
https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L349
Suggestions are wrapped inside `Portal` with this host name here
https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/components/AutoCompleteSuggestions/index.native.js#L8-L11
but here we are porting it to the `body` 
https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/components/AutoCompleteSuggestions/index.js#L56
so the suggestions popover appears over the drop layover.
### What changes do you think we should make in order to solve the problem?
I think we should wrap the `BaseAutoCompleteSuggestions` with `Portal` and remove `createPortal` in the `return` specified above.
With this change, the `componentToRender` and `return` of `index.js` of `AutoCompleteSuggestions` will be something like this.
```js
const componentToRender = (
        <Portal hostName="suggestions">
          <BaseAutoCompleteSuggestions
              // eslint-disable-next-line react/jsx-props-no-spreading
              {...props}
              ref={containerRef}
          />
        </Portal>
    );

    return (
        Boolean(width) &&
        <View style={StyleUtils.getBaseAutoCompleteSuggestionContainerStyle({left, width, bottom})}>{componentToRender}</View>
    );
```
### What alternative solutions did you explore? (Optional)
<details>
<summary>Result</summary>


https://github.com/Expensify/App/assets/102477862/f1bc24cd-a2e9-4000-9a20-0f5258a06304





</details>

**Comment by cubuspl42** [comment] 2023-10-23 07:12
@s-alves10 Would you publish your branch?

**Comment by c3024** [comment] 2023-10-23 07:17
@cubuspl42 

Is the suggestions popup closing the expected behaviour?

I think it need not close. In my opinion, the expected behaviour is that the drop layover should be above the suggestions.

**Comment by s-alves10** [comment] 2023-10-23 07:49
@cubuspl42 

Please check this branch https://github.com/s-alves10/App/tree/fix/issue-30153

**Comment by cubuspl42** [comment] 2023-10-23 09:17
@ishpaul777 Thanks for referencing the earlier issue, as it's always good to know that this was considered before.

I do agree with @s-alves10 that this is an obvious visual glitch.

**Comment by s-alves10** [comment] 2023-10-23 10:51
@c3024 

We need to use portal for the issue https://github.com/Expensify/App/issues/27036

@dukenv0307 

Mention suggestions wouldn't show when cancelling the dragging in your solution

@ishpaul777 

I think your solution would work for other popovers, but we need to show suggestions again after dragging is cancelled or completed

cc @cubuspl42

**Comment by c3024** [comment] 2023-10-23 23:59
I am not suggesting to remove portal altogether. 

I think we should use the host "suggestions" instead of document body for the portal.

**Comment by sonialiap** [comment] 2023-10-26 10:35
@cubuspl42 I skimmed the issue and looks like we don't quite have a proposal we want to move forward with, is that correct? Are there any that are close and could be accepted with some changes?

**Comment by cubuspl42** [comment] 2023-10-26 11:02
@sonialiap

Sorry for the lack of updates. I think we'll be able to pick a proposal from the existing ones, possibly with small adjustments.

@ishpaul777 

It's a good observation that the context menu is also affected! Would it be possible to use our `DragAndDropContext` in your solution, instead of subscribing to the DOM events directly?

**Comment by s-alves10** [comment] 2023-10-26 11:33
@cubuspl42 

Will you let me know your thoughts on https://github.com/Expensify/App/issues/30153#issuecomment-1774931125?

**Comment by cubuspl42** [comment] 2023-10-26 11:36
> Mention suggestions wouldn't show when cancelling the dragging in your solution

> I think your solution would work for other popovers, but we need to show suggestions again after dragging is cancelled or completed

I don't feel like it's a necessity to automatically show the suggestion popup after the drag is finished. I would personally prefer it if it didn't open automatically; still, both behaviors sound acceptable.

**Comment by s-alves10** [comment] 2023-10-26 11:41
@cubuspl42 

I'm saying the case where dragging is cancelled. The composer would get focused again but the suggestion popup doesn't show. We have been treating this as a bug up to now. A similar issue is https://github.com/Expensify/App/issues/22447.

**Comment by cubuspl42** [comment] 2023-10-27 09:13
> @cubuspl42
> 
> I'm saying the case where dragging is cancelled. The composer would get focused again but the suggestion popup doesn't show. We have been treating this as a bug up to now. A similar issue is #22447.

@s-alves10 Thanks for mentioning this. I'll double-check on the internal Slack channel when I have a chance. Currently there are some technical issues with Slack.

@ishpaul777 I'll come back to the `DragAndDropContext` topic once I verify this ^

**Comment by sonialiap** [comment] 2023-10-31 11:37
@cubuspl42 any updates on the things you were going to look into? :)

**Comment by cubuspl42** [comment] 2023-10-31 12:12
I started [a thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1698754296258849) on `#expensify-open-source`

**Comment by sonialiap** [comment] 2023-11-03 12:34
We've gotten agreement from Puneet for the 
>a drag gesture overrides all popovers and closes them (until something triggers them again).

plan. @cubuspl42 let's move forward with the proposal that does this?

**Comment by cubuspl42** [comment] 2023-11-06 10:05
In my opinion, the best proposal is the one by @ishpaul777, which suggests closing all popovers (whether it's the emoji picker, mention list, or context menu) when a file is dragged over.

In the case of the mentions list, it would be re-opened the next time it's triggered. I find this behavior reasonable and convincing. It [was also approved](https://expensify.slack.com/archives/C01GTK53T8Q/p1698754296258849) in the Slack thread.

The technical details such as using/not using `DragAndDropProvider` can be handled during PR review.

C+ reviewed 🎀 👀 🎀

**Comment by joelbettner** [comment] 2023-11-08 17:33
@cubuspl42 The proposal from @ishpaul777 looks good. I assigned him to this issue.

**Comment by DylanDylann** [comment] 2023-11-23 09:20
@sonialiap I reported this bug before here https://github.com/Expensify/App/issues/27564. Could you help to update reporter on the OP

**Comment by cubuspl42** [comment] 2023-12-06 11:29
PR is merged

**Comment by sonialiap** [comment] 2023-12-15 14:59
Automation didn't run. The PR went to production on Dec 6, updating issue title to payment on Dec 13

**Comment by sonialiap** [comment] 2023-12-18 16:40
@ishpaul777 contributor $500 paid ✔️ 
@cubuspl42 reviewer $500 paid ✔️ 
@DylanDylann bug report $50 - offer sent

**Closed** 2023-12-22 09:55 UTC
Labels: Reviewing, External, Daily, Bug
