### ISSUE TITLE
Split scan - Empty tax row in split confirmation page which leads to crash

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38260] opened 2024-03-13 23:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- Tax is enabled by admin end via Workspace features > Taxes on ND.
- There is no any tax rate in the workspace.

1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Go to + > Split bill > Scan.
4. Upload a receipt.
5. Click on the empty row.

## Expected Result:
There will be no empty row in confirmation page.

## Actual Result:
There is an empty row in confirmation page, which crashes the app when clicked on it.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7a59719a-77ab-4a79-810a-20c3af75f826

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-03-13 23:12
@stephanieelliott FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by marcaaron** [comment] 2024-03-13 23:38
Seems possibly related to one of these:

https://github.com/Expensify/App/pull/38111
https://github.com/Expensify/App/pull/37870

@mountiny or @luacmartins probably knows

**Comment by luacmartins** [comment] 2024-03-14 15:05
This seems more related to https://github.com/Expensify/App/pull/38111. @yuwenmemon @dukenv0307 @mananjadhav could you please check?

**Comment by situchan** [comment] 2024-03-14 15:06
https://github.com/Expensify/App/pull/38111

**Comment by luacmartins** [comment] 2024-03-14 15:52
Nice find @dukenv0307. If this is related to enabling the tax feature in NewDot, this is not a blocker then since that feature is still WIP and only internal people have access to that. It should also be solved [here](https://github.com/Expensify/App/issues/38234)

**Comment by stephanieelliott** [comment] 2024-03-26 01:43
Still held on https://github.com/Expensify/App/issues/38234

**Comment by stephanieelliott** [comment] 2024-04-04 22:44
Just tested and I think this is not happening anymore? The conditions to repro are: 

> There is no any tax rate in the workspace, 

and 

> Click on the empty row.

Now, when tax is enabled it's not possible to have no tax rate because the rate`Tax Exempt` auto populates and can't be deleted. With this being the case, you will never have an empty row. 

<img width="512" alt="image" src="https://github.com/Expensify/App/assets/31225194/8fa6eb3b-ec87-46b5-9f7c-54a0c9fc990e">

**Comment by stephanieelliott** [comment] 2024-04-04 22:47
Hey @m-natarajan can you check me on the above? It seems like this is either no longer happening, or we need to add more details to `Action Performed` and include steps for configuring Tax on the workspace so that this is reproducible

**Comment by luacmartins** [comment] 2024-04-08 18:31
I think this has been fixed by https://github.com/Expensify/App/issues/38234. We're good to close.

**Closed by luacmartins** 2024-04-08 18:31 UTC
Labels: Engineering, Daily, Overdue, Bug, retest-weekly
