### ISSUE TITLE
Android -  Signup - App crashes when creating a new account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9264] opened 2022-05-31 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Enter any email address which does not have expensify account
3. Tap continue

## Expected Result:
User is taken to magic link sent screen

## Actual Result:
App crashed with message Uh -oh something went wrong!

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.70-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/171282377-0c461567-be54-4972-9b5b-2616e09510a3.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment] 2022-05-31 21:46
@neil-marcellini the bug is reproducible on a physical Android device.

1.1.70-1, Pixel 6, Android 12
https://user-images.githubusercontent.com/29673073/171289609-26b86e98-a3c2-42e4-83d7-0b7dd1a7c8bb.mp4

**Comment by neil-marcellini** [comment] 2022-05-31 21:48
Cool, thanks @rushatgabhane. I think this should probably be internal since it might have to do with our API. I'll send it to the demolition team. I would take it myself if I had an android.

**Comment by mvtglobally** [comment] 2022-05-31 22:13
@neil-marcellini. full video 

https://user-images.githubusercontent.com/43995119/171292880-05af2867-4737-4c2e-bda1-b1a43d44266b.mp4

**Comment by neil-marcellini** [comment] 2022-05-31 22:30
I'm wondering if the error I'm seeing [here](https://github.com/Expensify/App/pull/8855#issuecomment-1142696925) is related?

**Comment by marcaaron** [comment] 2022-05-31 22:41
I think I know the cause. Can someone please check to see if this exists on my branch here -> https://github.com/Expensify/App/pull/9060

**Comment by rushatgabhane** [comment] 2022-05-31 22:46
@marcaaron #9060  didn't fix it

![Screenshot_20220601-014500](https://user-images.githubusercontent.com/29673073/171296162-71684198-0f34-440f-8d63-95d1a58eb741.png)

**Comment by rushatgabhane** [comment] 2022-05-31 22:49
> I'm wondering if the error I'm seeing https://github.com/Expensify/App/pull/8855#issuecomment-1142696925 is related?

@neil-marcellini yep, looks like it.

**Comment by luacmartins** [comment] 2022-06-01 16:05
Ah this seems like this issue that I created this week - https://github.com/Expensify/App/issues/9255. It's been happening for a while now. I'm gonna close that issue in favor of this one.

**Comment by TomatoToaster** [comment] 2022-06-10 20:07
PR up for this but feels like a band-aid not a real solution. I'm not sure if there's a better solution to this. After investigating and trying to recreate this (hadn't been able to on emulator obviously) I think this should at least address the problem.

**Comment by marcaaron** [comment] 2022-06-15 18:40
I looked at the linked solution, but it seems like it would briefly display something like `Not ?` instead of `Not amal@expensify.com?` in the cases where it would previously crash. Maybe better to just show nothing.

**Comment by francoisl** [comment] 2022-06-27 18:45
Reopening this since there was still an issue during the QA, see https://github.com/Expensify/App/issues/9480#issuecomment-1167743847 for context.

**Comment by TomatoToaster** [comment] 2022-06-27 20:22
> I looked at the linked solution, but it seems like it would briefly display something like `Not ?` instead of `Not amal@expensify.com?` in the cases where it would previously crash. Maybe better to just show nothing.

I guess I could conditionally render the whole block if the `props.credentials.login` exists. I'll start with that, but I think this is a bandaid solution and will still likely cause the API error mentioned right above. I'm guessing the fact that `props.credentials.login` doesn't is causing the problem.

**Comment by aldo-expensify** [comment] 2022-06-29 20:19
This has been fixed now.

See https://github.com/Expensify/Terraform/commit/3d54c66dcf97c1e72867a2dfee02a1177ce155c3 and https://github.com/Expensify/App/issues/9564#issuecomment-1170443845

**Closed by aldo-expensify** 2022-06-29 20:19 UTC
Labels: Engineering, Daily, Improvement, Demolition
