### ISSUE TITLE
[$250] Web - Notification count in the tab flashes when back is clicked

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29604] opened 2023-10-14 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/29409

**Version Number:** v1.3.84-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Sign in to an account.
3. Go through different unread chats.
4. Click back.
5. Observe the Notification count in the tab.

## Expected Result:
Notification count should be the same

## Actual Result:
Notification count in the tab flashes when back is clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/6b2a3d7e-413a-48e5-b108-748e1614968d

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011757bc5f159e3e7a</li>
        <li>Upwork Job ID: 1713187815326801920</li>
        <li>Last Price Increase: 2023-10-15</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-14 13:41
Nor teproducible in production

Uploading bandicam 2023-10-14 17-00-23-295.mp4…

**Comment by pradeepmdk** [comment] 2023-10-14 14:11
> Nor teproducible in production
> 
>  bandicam.2023-10-14.17-00-23-295.mp4

I think this is not a bug because when you hit the back button notification count is wrong in Production 
so here we are fixing when you hit the back button we are updating the correct count https://github.com/Expensify/App/pull/29409
cc: @sobitneupane @MariaHCD

**Comment by ikevin127** [comment] 2023-10-14 16:29
I can still reproduce this on latest main on MacOS: Chrome.

The reason why some might not be able to reproduce this is because it's a Chromium engine specific issue hence why @pradeepmdk might have missed it in his PR https://github.com/Expensify/App/pull/29409

### Video

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/56457735/1ee1595b-8890-4186-b080-7c775f4e7719

</details>

# Proposal
## Please re-state the problem that we are trying to solve in this issue
Notification count in the tab flashes when back is clicked.

## What is the root cause of that problem?
This is due to the way Chromium based browsers handle their tab management - it maintains a snapshot of the title and favicon and re-uses it briefly when navigating.

Browsers do have some freedom in exactly when they fire popstate events, and Chrome seems to do it before the new page has fully loaded - hence the flickering of notification count on Chrome.

The issue is caused by the logic in this file:

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js#L6-L14

Because this does not handle Chrome's behaviour when it comes to tab management and therefore on Chrome the state of the snapshot is keept hence the flash of old notification count before being updated with the current one.

## What changes do you think we should make in order to solve the problem?
My approach which will handle this issue for all browsers (including Chromium based) is to use window's `history.replaceState()` to replace the current history instead of a new one being added, therefore when clicking the back button it won't show the old snapshot count title and instead will show the correct notification count without any flashes.

```diff
- let unreadTotalCount = 0;

function updateUnread(totalCount) {
    const hasUnread = totalCount !== 0;
-   unreadTotalCount = totalCount;
    // This setTimeout is required because due to how react rendering messes with the DOM, the document title can't be modified synchronously, and we must wait until all JS is done
    // running before setting the title.
    setTimeout(() => {
        // There is a Chrome browser bug that causes the title to revert back to the previous when we are navigating back. Setting the title to an empty string
        // seems to improve this issue.
        document.title = '';
        document.title = hasUnread ? `(${totalCount}) ${CONFIG.SITE_TITLE}` : CONFIG.SITE_TITLE;
        document.getElementById('favicon').href = hasUnread ? CONFIG.FAVICON.UNREAD : CONFIG.FAVICON.DEFAULT;

        // Update the browser history with a new title and favicon, instead of letting it remember the old state
        // This is used because a side effect in Chromium based browsers where browser creates snapshots
        // of the page state and re-uses them when navigating, causing a brief "flash" of the old title/favicon
+       window.history.replaceState({unreadTotalCount: totalCount}, document.title);
    }, 0);
}

// Update the title and favicon when the user navigates to a history state that we pushed.
- window.addEventListener('popstate', () => {
+ window.addEventListener('popstate', event => {
+   if (!((event.state && "unreadTotalCount" in event.state))) {
+       return;
+   }

-    updateUnread(unreadTotalCount);
+   updateUnread(event.state.unreadTotalCount);
});
```

## What alternative solutions did you explore? (Optional)
N/A

## Videos

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/56457735/10f07921-9c23-4542-8b15-6ba5c831c026

https://github.com/Expensify/App/assets/56457735/ff40b234-5f49-43c3-9ddb-d6d29671ad8a

</details>

**Comment by pradeepmdk** [comment] 2023-10-14 16:41
@ikevin127 see the notification count in the resulting video when you hit back count increases.

**Comment by akinwale** [comment] 2023-10-14 16:50
@ikevin127 Your proposed solution has a flaw where the unread count in the browser title ends up being incorrect. It should maintain the current unread count after clicking the back button.

In any case, if valid, this may end up being considered as a regression of the PR https://github.com/Expensify/App/pull/29409 which would require the original PR author to fix it.

We'll have to wait for feedback from an internal engineer.

cc @MariaHCD @sobitneupane

**Comment by ikevin127** [comment] 2023-10-14 17:21
Indeed, I know that the counter increases when going back from reading a notification.

Seeing this comment's video https://github.com/Expensify/App/issues/29604#issuecomment-1762919864 I thought that's the intended behaviour as that's how it is currently on staging.

If that's not the intended behaviour then I am happy to update my proposal such that the count is always in sync with Onyx and also stays updated even on `popstate` according to realtime report read / unread notifications trigger.

**Comment by mountiny** [comment] 2023-10-15 18:51
I agree this is not a blocker so removing the label, however we should still investigate this unless it will be covered by @pradeepmdk PR

**Comment by MariaHCD** [comment] 2023-10-16 09:47
I do believe this is a regression from https://github.com/Expensify/App/pull/29409 so it makes sense for the PR author @pradeepmdk to handle.

cc: @sobitneupane

**Comment by ikevin127** [comment] 2023-10-16 13:21
I can confirm that this is not a regression. I consider this a browser level limitation / issue.

> Browsers that use the Chromium engine keep snapshots of pages for performance reasons and to improve the user experience when navigating through the history. These snapshots include the current state of the DOM, the JavaScript heap, and other details such as the window title. 

> When you navigate back to a page using the forward/backward buttons, or via JavaScript's history API, these snapshots are used to quickly reconstruct the page to the state it was in when the snapshot was created.

> This means that any changes you make to the window title or other browser-level features in the popstate event (or other events that occur after the snapshot was taken but before the page is visible to the user again) can be overwritten by the old, cached state from the snapshot while the page is loaded. This could result in a brief "flash" of the old title before your new title is set. 

> Unfortunately, this behavior is a side effect of how browsers implement page navigation for performance, and is unlikely something that can be easily changed or worked around. It could be seen as a browser level limitation or issue, but not necessarily a "bug".

**Comment by sakluger** [comment] 2023-10-17 16:17
There is some disagreement around whether this is a regression. @MariaHCD what do you think about what @pradeepmdk and @ikevin127 are saying?

**Comment by MariaHCD** [comment] 2023-10-17 16:34
Oh, interesting. Thanks @pradeepmdk and @ikevin127! This does look like a browser-level limitation. So not a regression, then.

Perhaps there won't be a clean solution for this so I'd say if we don't find a good solution, we can close this one out.

Thoughts, @akinwale?

**Comment by akinwale** [comment] 2023-10-17 17:08
@MariaHCD Since it's not a regression, the [proposal](https://github.com/Expensify/App/issues/29604#issuecomment-1763033578) by @ikevin127 could work in this scenario using history.replaceState ([reference](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState)), where the unread count is being stored in the browser's history state.

@ikevin127 Could you please update your proposal and provide a video to demonstrate the expected behaviour with the unread count? Is it also possible to get rid of the `setTimeout` or is that still required for it to work properly?

**Comment by ikevin127** [comment] 2023-10-17 17:37
@akinwale There's a catch with my current proposal:
- when you hit the back button the notification count increments back up even though the notifications were read
which from what I was told it is not the desired behaviour

So there's a choice here to be made between the following options:
1. We keep @pradeepmdk's current implementation which causes the flash on Chrome browser
2. We add my proposal's solution for Chrome browser **only**, all other browsers keep above (1.) solution except Chrome
3. We add my proposal's solution for all browsers (least desirable)

Based on what's decided here I can update my proposal.

As for getting rid of the current implementation's `setTimeout` I'm not sure, according to the developer's comment:

`// This setTimeout is required because due to how react rendering messes with the DOM, the document title can't be modified synchronously, and we must wait until all JS is done running before setting the title.`

we might break the current functionality if removed. I'll make sure to check when updating my proposal if we get there.

**Comment by akinwale** [comment] 2023-10-17 18:13
> 2. We add my proposal's solution for Chrome browser **only**, all other browsers keep above (1.) solution except Chrome

If we go with this (we can use `Browser.isChrome` to apply Chrome-only behaviour), will the correct unread  count (ie. the reduced count) be displayed as expected?

**Comment by ikevin127** [comment] 2023-10-17 21:31
To answer your question: no.

After further testing on the current implementation that's on staging I can confirm that on Chrome the following happens:
- on back / forward button the notification flickers to cached title before the real count is being shown (current issue)
- also for the following steps:
1. Go to https://staging.new.expensify.com
2. Sign in to an account
3. Go through different unread chats in order for the tab notification to decrement count (1-2 decrements)
4. Logout
5. Click browser **forward** button and observe the same flicker will happen briefly showing cached title before showing just logged out title: `New Expensify` without any notification count

So I guess that this flicker thing was always there on Chrome as the PR author showed [here](https://github.com/Expensify/App/issues/29604#issuecomment-1764218060) for Gmail and this PR https://github.com/Expensify/App/pull/29409 only exposed it to where it can be observed.

I wouldn't count this behaviour as a regression, as I said before its more of a browser-level limitation.

#### Solution if the flicker is really not wanted while logged in and navigating back / forward:
The only way to get rid of the flicker would be to allow the notifications to increment back up on Chrome while logged in. If the user reads some messages then performs logout and then hits the forward button, we will keep the current implementation with the flicker because when upon logout it's less likely that users would hit the forward button and see the flicker. It's more likely to be seen while logged in and hitting back button while reading through reports.

^ - This would be the behaviour for Chromium based browsers. For all other browsers the current implementation works as expected, no flickers both logged in back / forward buttons and upon logout back / forward buttons.

If this solution is something that would work for you, I can update my proposal with the solution described above.
Otherwise, I think keeping the current implementation works just fine.

**Comment by akinwale** [comment] 2023-10-19 07:32
@MariaHCD Considering the discussion above, looks like we may have to close this since it's a browser limitation.

**Comment by MariaHCD** [comment] 2023-10-19 09:02
I'd agree with closing since it's a browser limitation. Leaving the final decision to the assigned folks here, @Li357 and @MitchExpensify

**Comment by MitchExpensify** [comment] 2023-10-20 20:52
lets do it

**Closed by MitchExpensify** 2023-10-20 20:52 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
