### ISSUE TITLE
[HOLD for payment 2023-12-21][$500] Update CONSTS to direct developers to use role instead of accessibilityRole

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#31500] opened 2023-11-17 19:33 UTC
- Restore CONST.ACCESSIBLITY_ROLE.TEXT to have the value text
- Create CONST.ROLE with comments on appropriate use
- Add a deprecation JSDoc on CONST.ACCESSIBLITY_ROLE with an instruction to use role instead of accessibilityRole
- Update any role props that point to CONST.ACCESSIBLITY_ROLE to point to CONST.ROLE instead.

This will encourage appropriate code syntax moving forward and keep things clean and on the cutting edge!
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012561c8136f1b8b5a</li>
        <li>Upwork Job ID: 1726618160989405184</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by trevor-coleman** [comment] 2023-11-17 21:39
Hey @dangrous -- this is my baby!

**Comment by trevor-coleman** [comment] 2023-11-17 21:42
As a note: I don't get paid via Upwork as I'm with Infinite Red.

**Comment by dangrous** [comment] 2023-11-20 15:08
sorry for all the notifications - trying to get a C+ here, (thanks @allroundexperts!), @trevor-coleman will be handling the issue

**Comment by trevor-coleman** [comment] 2023-11-20 22:22
I've got [a draft PR going](https://github.com/Expensify/App/pull/31590), but not sure how to handle the testing part. 

Should I write up tests for every component touched her? 

It would be quite a few components (~100), and as the changes are a like-for-like substitution of values from a known list of acceptable values I think the risk it pretty low.

Happy to do whatever is needed, just wanted to get some advice on what an appropriate testing section looks like for a find-replace PR like this.

**Comment by dangrous** [comment] 2023-11-20 23:26
That's a great question. I think if most of the changes are exactly the same, I think we can call out the testing steps for just a few of them. Since this also shouldn't cause any visual change, it shouldn't be too bad.

@allroundexperts since you've done a lot more testing, what are your thoughts on the best way forward?

**Comment by getusha** [comment] 2023-11-21 07:50
@trevor-coleman @dangrous what about adding a new lint rule?

**Comment by trevor-coleman** [comment] 2023-11-21 19:38
@getusha -- that's a good idea, though it would be a PR against the [ESLint config repo](https://github.com/Expensify/eslint-config-expensify).

The rule to use would be [`forbid-component-props`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md).

**Comment by trevor-coleman** [comment] 2023-11-21 19:39
> I think a general round of testing should suffice here. Try creating new chats / requesting money and make sure that you don't get any new console errors.

Sounds good -- I'll get started on that now.

**Comment by trevor-coleman** [comment] 2023-11-22 22:50
Opened a PR: https://github.com/Expensify/App/pull/31590

Let me know if the testing section seems ok! 

(It's my first time writing one for this repo, and this is a bit of a weird case. )

**Comment by dangrous** [comment] 2023-12-14 21:32
This has been merged to prod, though the automation didn't fire. I updated the title, and we can grab a BZ closer to the time to handle payment. It's just review for @allroundexperts, right?

**Comment by allroundexperts** [comment] 2023-12-19 11:24
@dangrous That is correct!

**Comment by allroundexperts** [comment] 2023-12-19 11:24
Can you just add a payment summary? TY!

**Comment by dangrous** [comment] 2023-12-19 18:35
hey @abekkala , not a bug, but we'll need payment on 12/21!

It should just be:
* @allroundexperts for review!

**Comment by abekkala** [comment] 2023-12-19 20:54
**PAYOUT NOTES**
$500
@allroundexperts **paid in NEWDOT, not Upwork**

@dangrous you can close this when needed as @allroundexperts will request his payment via NewDot

**Comment by peterdbarkerUK** [comment] 2023-12-21 20:08
@trevor-coleman doesn't need to be paid via UpWork, as he's Infinite Red. 

@allroundexperts could you send your request via NewDot? CC @anmurali while Mills is OoO: $500 for C+ review.

**Comment by peterdbarkerUK** [comment] 2023-12-21 20:08
Weird that this assigned me for the payment issue in addition to @abekkala, maybe due to holiday season OoO?

**Comment by peterdbarkerUK** [comment] 2023-12-27 11:38
@JmillsExpensify $500 to @allroundexperts when it's sent, thanks!

**Comment by abekkala** [comment] 2024-01-04 17:10
This one is ready to be closed out once:
@allroundexperts requests $500 payment in New Dot

@JmillsExpensify

**Comment by allroundexperts** [comment] 2024-01-07 19:48
@abekkala I've noted it down. Feel free to close. Thanks!

**Comment by peterdbarkerUK** [comment] 2024-01-10 08:22
@allroundexperts sorry Sibtain, I'm a bit confused: did you already request and receive this payment?

**Comment by allroundexperts** [comment] 2024-01-11 22:59
@peterdbarkerUK I have requested payment but haven't received it yet. I think we can close this issue because receiving the payment does take some time.

**Comment by peterdbarkerUK** [comment] 2024-01-12 08:22
CC @JmillsExpensify this one should be ready to go, $500 to @allroundexperts 

Let's close once payment is confirmed, no need to risk things slipping through the cracks :)

**Comment by dangrous** [comment] 2024-01-17 16:29
How are we looking on this one? I think still waiting on payment for @allroundexperts from @JmillsExpensify, is that right?

**Comment by abekkala** [comment] 2024-01-17 19:14
> How are we looking on this one? I think still waiting on payment for @allroundexperts from @JmillsExpensify, is that right?

yes, that is correct

**Comment by JmillsExpensify** [comment] 2024-01-23 03:25
I don't think I've received a payment request, though as a heads up, we don't keep issues open that are waiting payment in Expensify. Feel free to close it.

**Comment by JmillsExpensify** [comment] 2024-01-23 03:26
Ah yeah, I just checked. @allroundexperts needs to submit the report to me, as that's the only way it shows up in my LHN. But again, no need to keep this issue open for Expensify payments, so I'd go ahead and close it.

**Comment by abekkala** [comment] 2024-01-23 03:27
sounds good @JmillsExpensify thanks!

**Closed by abekkala** 2024-01-23 03:27 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-01-24 23:51
$500 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/31500#issuecomment-1888639550).
