### ISSUE TITLE
Workspace - Workspace editor opened after WS was created from the Global Create menu closes by itself

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23287] opened 2023-07-20 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com in Chrome / Safari or start Desktop App
2. Create new Expensifail account and validate it
3. Click 'New workspace' in Global Create menu
4. Check that the Workspace editor is open

## Expected Result:
Workspace editor remains open until there is an action to close it.

## Actual Result:
Workspace editor closes by itself after a few seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7392d4c3-b25e-4804-abf9-5e73e526d757

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment] 2023-07-20 16:20
asked about this in open source here https://expensify.slack.com/archives/C01GTK53T8Q/p1689870003703889

**Comment by bondydaa** [comment] 2023-07-20 16:46
sounds like there may be a PR already merged in `main` that fixes this since it's not reproducible on `main`. we're trying to figure that out so we can CP the PR.

**Comment by mountiny** [comment] 2023-07-20 18:04
They could not reproduce this again https://expensify.slack.com/archives/C01GTK53T8Q/p1689875721536609?thread_ts=1689870003.703889&cid=C01GTK53T8Q closing

**Closed by mountiny** 2023-07-20 18:04 UTC
Labels: DeployBlockerCash, Engineering, Hourly
