### ISSUE TITLE
[HOLD Paypal feature update][$1000] Web - It does not show error message if PayPal username has leading or trailing space

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23791] opened 2023-07-28 12:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings> Payments
2. Click on Add payment method button and select PayPal.me option
3. Enter Paypal username with leading space

## Expected Result:
It should show invalid username error (same as previous version) or trim username

## Actual Result:
It does not show invalid username error and username shifts left side on click of add Paypal account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d95ca890-ae1b-4e05-b276-374c80fe8620

https://github.com/Expensify/App/assets/93399543/c6ba3a0d-8cf7-438f-99f7-d1f7677c7b2a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690526881707709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01caff7fb052f5762f</li>
        <li>Upwork Job ID: 1685298133264203776</li>
        <li>Last Price Increase: 2023-08-05</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-07-28 13:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a PayPal.me username, it accepts leading or trailing spaces as part of the username.

### What is the root cause of that problem?
In the `validate` method, the value is automatically trimmed before the validation is performed on the value.

### What changes do you think we should make in order to solve the problem?
Get the actual value from the input field using a state variable set as the value instead of `values.payPalMeUsername`.

**Comment by maddylewis** [comment] 2023-07-29 14:36
this is cause by a regression - https://expensify.slack.com/archives/C049HHMV9SM/p1690526905961579?thread_ts=1690526881.707709&cid=C049HHMV9SM

**Comment by vatsal-git** [comment] 2023-07-29 15:47
### Proposal
Go to file CONST.js located in 'https://github.com/Expensify/App/blob/main/src/CONST.js#L1131' path.
Go to line 1146
Original code in the line: PAYPAL_ME_USERNAME: /^[a-zA-Z0-9]{1,20}$/,
Replace the line with this: PAYPAL_ME_USERNAME: /^(?! )(?![a-zA-Z0-9]* $)[a-zA-Z0-9]{1,20}$/

Done and dusted. It will remove any leading or trailing spaces. If the issue is still not solved, I can provide more guidance of what you exactly need to do.

I will also apply for the job at Upwork!

**Comment by vatsal-git** [comment] 2023-07-29 15:52
Contributor details
Your Expensify account email: vatsal.acct01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f1f8db617204ee96

**Comment by muneebkhan4** [comment] 2023-07-29 22:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a PayPal.me username, leading or trailing spaces as part of the username are accepted as valid which is wrong. It should not add PayPal.me username which has leading or trailing spaces.

### What is the root cause of that problem?
The root cause of the problem in the Regex which is validating PAYPAL_ME_USERNAME.

Here it is: https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/CONST.js#L1146

### What changes do you think we should make in order to solve the problem?
We can solve this problem by updating the Regex for PAYPAL_ME_USERNAME in such a way that it also checks for leading or trailing spaces.


### What alternative solutions did you explore? (Optional)
Alternatively, we can look into the onInputChange function here:
https://github.com/Expensify/App/blob/ba08d3d71a38cdcd1c07318b65115ea3ea4b6498/src/components/Form.js#L321

It is quite possible that the leading and trailing spaces are getting trimmed before the Regex validation.

**Comment by mehvash-Khan** [comment] 2023-07-30 13:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paypal.me username is being added and saved(after trimming) even when user adds leading/trailing spaces to the name. Paypal username if entered with leading/trailing spaces should throw error.

### What is the root cause of that problem?
Root cause of this problem is that we are trimming the PayPal username and then passing that trimmed value to the regex(where it is checking for string validation). Regex `PAYPAL_ME_USERNAME` is defined to validate if PayPal name does not have any leading/trailing spaces and special characters which in our case is absolutely correct and needs no change. The root cause here is value being passed for regex validation is being trimmed and therefore regex is returning true and hence not giving error for PayPal username with space.

### What changes do you think we should make in order to solve the problem?
If we want error message to be displayed when username has leading/trailing space, we will have to pass that value as it is [here](https://github.com/Expensify/App/blob/513fed987c8b6249ab3cc0d8d9c133eb4b3dcfa8/src/pages/settings/Payments/AddPayPalMePage.js#L41) and not trim it. 

Currently our `Form` component trims every input value during validation as seen [here](https://github.com/Expensify/App/blob/24ed1bebf19539d27878ed419f7cc10ae942531f/src/components/Form.js#L112). We can add an additional prop in `Form` named `disableTrim` which will include an array of input IDs of those text fields whose values should not be trimmed during validation. In `AddPayPalMePage.js` we can add `disableTrim={["payPalMeUsername"]}`. Now in our `Form` component we update our OnValidate function like below:

```js
 const onValidate = useCallback(
        (values) => {
            const trimmedStringValues = {};
            _.each(values, (inputValue, inputID) => {
                if (_.isString(inputValue)) {
                    if(props.disableTrim.includes(inputID))
                        trimmedStringValues[inputID] = inputValue;
                    else
                     trimmedStringValues[inputID] = inputValue.trim();
                } else {
                    trimmedStringValues[inputID] = inputValue;
                }
            });

```
Default value for `disableTrim` can be an empty array so that no other component is affected.

### What alternative solutions did you explore? (Optional)

**Comment by mehvash-Khan** [comment] 2023-07-30 13:12
Adding a video here with the above change.



https://github.com/Expensify/App/assets/127308250/1c48768d-f2aa-477d-99cc-a007409d686e

**Comment by krimo11** [comment] 2023-07-31 00:17
Contributor details
Your Expensify account email: djouah.abdelkrim@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01dd4198edd7453dc0

**Comment by maddylewis** [comment] 2023-07-31 22:10
@sobitneupane - will you review these proposals when you have a chance? thanks!

**Comment by sobitneupane** [comment] 2023-08-02 18:12
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/23791#issuecomment-1655682255) by @samh-nl looks good to me.

> Option 1. We pass the trimmed value to User.addPaypalMeAddress

If we don't mind user adding spaces in the beginning and end for paypal address, we can go with the first option.

> Option 2. We can change Form to also pass the raw non-trimmed values as a second argument:

But to align with previous condition before having Form refactor, we can pass the non-trimmed value as 2nd argument from form component itself and use it where ever required. 

@samh-nl Are there are other places where `rawValues` can be useful?

**Comment by maddylewis** [comment] 2023-08-06 19:08
@sobitneupane - do we think this is worth fixing based on this comment? https://expensify.slack.com/archives/C01GTK53T8Q/p1691006515807909?thread_ts=1690999903.863719&cid=C01GTK53T8Q

**Comment by maddylewis** [comment] 2023-08-06 19:10
@Christinadobrzyn - i am OOO until ~Aug 20. we are chatting in Slack about the proposed fix for this one - https://github.com/Expensify/App/issues/23791#issuecomment-1662719388

That said, @JmillsExpensify made a comment here that makes me think this might not be worth fixing if we're going to deprecate this feature altogether at some point - https://expensify.slack.com/archives/C01GTK53T8Q/p1691006515807909?thread_ts=1690999903.863719&cid=C01GTK53T8Q

**Comment by Christinadobrzyn** [comment] 2023-08-07 18:20
I'll follow this thread over the coming days to see if this should stay open. https://expensify.slack.com/archives/C01GTK53T8Q/p1691006515807909?thread_ts=1690999903.863719&cid=C01GTK53T8Q

**Comment by JmillsExpensify** [comment] 2023-08-08 04:05
I don't have a formal proposal at the moment, to be clear. I do think we should do this eventually though.

**Comment by Christinadobrzyn** [comment] 2023-08-10 20:24
It sounds like this should be on hold for now. Going to move this to monthly for tracking

**Comment by sophiepintoraetz** [comment] 2023-09-08 03:42
We are deprecating paypal (decision [here](https://expensify.slack.com/archives/C057F53HR40/p1694141684236569), GH [here](https://github.com/Expensify/App/issues/26368)) so closing this out, thanks!

**Closed by sophiepintoraetz** 2023-09-08 03:42 UTC
Labels: External, Monthly, Bug
