### ISSUE TITLE
Workspace - Workspace owner can be checked marked on Members page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37555] opened 2024-02-29 18:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+gm51@applause.expensifail.com
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create Workspace
2. Go to Members page
3. Try to checkmark the Owner

## Expected Result:
Owner should not be checkmarkable

## Actual Result:
Workspace owner can be checked marked on Members page/ Remove option becomes active but unresponsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fcd10ebe-d577-482f-a08b-cb40a811818a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-29 18:38
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by rushatgabhane** [comment] 2024-02-29 18:44
### Proposal

### Root cause
The menu item is disabled - https://github.com/Expensify/App/blob/e4e98a2c2957b838b1a2a635cdfabf7a5af9d837/src/pages/workspace/WorkspaceMembersPage.tsx#L322-L324 but no such check is added for toggling the user.


### Solution

We should add similar checks here
https://github.com/Expensify/App/blob/a1a6a746ae53b62a44b7c0c0d58a002aa30d07ca/src/pages/workspace/WorkspaceMembersPage.tsx#L240

**Comment by luacmartins** [comment] 2024-02-29 18:45
We'll address this as part of https://github.com/Expensify/App/pull/37199. NAB since the owner can't actually be removed.

**Comment by luacmartins** [comment] 2024-02-29 18:45
Closing in favor of https://github.com/Expensify/App/pull/37199

**Closed by luacmartins** 2024-02-29 18:45 UTC
Labels: Engineering, Hourly
