### ISSUE TITLE
Web - When "Pasting" a code in sign in menu, the code vanishes and/or flashes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23075] opened 2023-07-18 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Input an email address
3. Copy a code from email (It can be the right code or wrong code)
4. Pate the code

## Expected Result:
The user expects that the code will show in the input field

## Actual Result:
The code either flashes rapidly before signing into the account OR does not show at all if it is the incorrect code that is being pasted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f878a754-6dda-447d-be00-6d0ce1ecbe19

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by cead22** [comment] 2023-07-18 14:28
Labeling daily since it looks like it's already being worked on

**Comment by jasperhuangg** [comment] 2023-07-18 17:55
@cead22 I'm unable to reproduce this in our staging or production builds. Looks like it was fixed by https://github.com/Expensify/App/pull/23023. Closing


https://github.com/Expensify/App/assets/31285285/c44d614b-7b22-4e80-bce3-ba66e3edfc2a

**Closed by jasperhuangg** 2023-07-18 17:55 UTC
Labels: DeployBlockerCash, Engineering, Hourly
