### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500]  IOU Category - Search message shows 'Invalid email' when typing email address in search field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28078] opened 2023-09-23 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27459
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any workspace chat
3. Go to + > Request money > Manual
4. Enter an amount
5. Click Show more > Category.
6. Enter a few letters, followed by @

## Expected Result:
The message below the search field will display 'No results found'..

## Actual Result:
The message below the search field displays 'invalid email' when Category search does not involve email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f780b607-ab40-48ee-9fd4-a91cd525d5b6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131655c00ab293751</li>
        <li>Upwork Job ID: 1710313308418142208</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27217343</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-23 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU Category - Search message shows 'Invalid email' when typing email address in search field 

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/libs/OptionsListUtils.js#L1476-L1485

Let's see the logic to get header message, we are checking if the search value includes "@" we will display errorMessageInvalidEmail instead of noResultsFound
### What changes do you think we should make in order to solve the problem?
In this case, we don't search email and phone number 
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/libs/OptionsListUtils.js#L1477-L1485

So this logic to redandunt. We need to pass one more params called includeEmailAndPhoneNumber to getHeaderMessage function

and only apply logic to check email and phone if this param is true

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2023-09-25 22:35
Not sure how to make a Category, asking QA - https://expensify.slack.com/archives/C9YU7BX5M/p1695681312874909

**Comment by Christinadobrzyn** [comment] 2023-09-27 18:54
still trying to get Categories to work on my c.dobrzyn+45@expensifail.com account.

**Comment by Christinadobrzyn** [comment] 2023-09-28 22:42
I still can't get Category and reached out to the team and they can't get it either so maybe we disabled them. I'm going to close this.

**Comment by DylanDylann** [comment] 2023-09-29 12:44
@Christinadobrzyn I still can reproduce this bug on the latest main. You can ping C+ team or internal engineer to help verify the bug

**Comment by DylanDylann** [comment] 2023-10-02 06:20
This is an example about category issue: https://github.com/Expensify/App/issues/28079

**Comment by DylanDylann** [comment] 2023-10-04 03:00
@s77rt It seems @Christinadobrzyn can't access the category feature. Because you are C+ Contributor of another issue that relates to category https://github.com/Expensify/App/issues/28517. Could you help to verify this is a bug? 
Sorry, If I bothers you

**Comment by s77rt** [comment] 2023-10-04 15:29
I can reproduce the bug

<img width="377" alt="Screenshot 2023-10-04 at 4 29 35 PM" src="https://github.com/Expensify/App/assets/16493223/adf7bd52-032e-4c59-b43d-78345175cfb8">

**Comment by ChrisCates** [comment] 2023-10-06 16:03
@ZhenjaHorbach, I'm also interested in the project.

By the way the regular expression you suggested will work for validation. But, it won't match the whole email if it has punctuation in it:

```
/\w+@\w+\.\w+/
```

It's better to use:

```regex
/\S+@\S+\.\S+/
```

This will return the whole email on a match. And not partial using the `\w` expression if the email has punctuation.
This is more for sanity sake in the future to verify full email matching.

**Comment by ChrisCates** [comment] 2023-10-06 16:07
Contributor details
Your Expensify account email: hello@chriscates.ca
Upwork Profile Link: https://www.upwork.com/freelancers/~01ed9060ff74912e35

**Comment by ChrisCates** [comment] 2023-10-06 16:12
@ZhenjaHorbach no it's not.

Please review TLDs with punctuation in them:

![image](https://github.com/Expensify/App/assets/1561091/565acfb6-45d0-4d70-bf69-14b1d51fda58)

**Comment by ChrisCates** [comment] 2023-10-07 22:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue

In the "IOU Category". When you search for a message. It shows "invalid email". When instead, it needs to show "no results found".

### What is the root cause of that problem?

There is an issue with the regex. As per discussion in this thread. We need to add regex to verify that the search input value is an email.

We would use the following regex pattern to properly identify all emails including emails with punctuation in their TLDs (as discussed earlier in this thread).

### What changes do you think we should make in order to solve the problem?

As per the snippet seen here:

https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/libs/OptionsListUtils.js#L1476-L1490

We will need to update this script to use a regex that properly captures email values:

```javascript
     if (searchValue && !hasSelectableOptions && !hasUserToInvite) { 
         if (/^\d+$/.test(searchValue) && !isValidPhone) { 
             return Localize.translate(preferredLocale, 'messages.errorMessageInvalidPhone'); 
         } 
         if (/\S+@\S+\.\S+/.test(searchValue) && !isValidEmail) { 
             return Localize.translate(preferredLocale, 'messages.errorMessageInvalidEmail'); 
         } 
         if (hasMatchedParticipant && (isValidEmail || isValidPhone)) { 
             return ''; 
         } 
         return Localize.translate(preferredLocale, 'common.noResultsFound'); 
     } 
```

We will also  want to add additional unit tests for this function:

```javascript
function getHeaderMessage()
```

To verify that the desired outputs.

In the following file https://github.com/Expensify/App/blob/main/tests/unit/OptionsListUtilsTest.js

We do not have unit tests for `getHeaderMessage()`. We should add them and check for numbers, emails and other queries.

However, should that be a separate issue?

**Comment by cubuspl42** [comment] 2023-10-09 17:30
@ChrisCates [asked me](https://github.com/Expensify/App/issues/28820#issuecomment-1753250244) for my thoughts on their proposal.

After giving your proposal a quick look, I can't see the benefit of it over other proposals. The form is more or less alright, although the root cause analysis is quite shallow; "There is an issue with the regex." is not very precise.

The assigned C+ (@rushatgabhane) can give you more feedback. Once you have Slack access, you can also ask for high-level feedback there, but _please_ be sure that you double-read the contributing guidelines before you do that.

**Comment by ChrisCates** [comment] 2023-10-09 17:52
@cubuspl42, 

If an email is inputted with a TLD that has a `-` in it.
It will not register as an email.

For example, if you input:

```
test@website.com
```

It will register an email. However, if you input:

```
test@my-website.com
```

It will not register an email. This is why you need to use `\S` as opposed to `\w`.

I can add that to the proposal for clarity.

Also, unit testing on the function:

```javascript
function getHeaderMessage()
```

May be helpful for future sanity sake.

**Comment by Christinadobrzyn** [comment] 2023-10-10 18:22
hi @rushatgabhane could you review the proposals when you have a moment? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-10-13 22:20
nudge @rushatgabhane when you have a moment to review the proposals! Thanks!

**Comment by DylanDylann** [comment] 2023-10-17 10:39
@rushatgabhane this [PR](https://github.com/Expensify/App/pull/29741) is ready for review

**Comment by MariaHCD** [comment] 2023-10-30 08:31
I believe we just need the BZ checklist here so we can proceed with the payments

**Comment by Christinadobrzyn** [comment] 2023-10-30 15:30
Payouts due:

Issue Reporter: NA - reporter is Applause
Contributor: $500 + $250 speed bonus @DylanDylann (Paid through Upwork)
Contributor+: $500 + $250 speed bonus @rushatgabhane (paid manually in NewExpensify)

Eligible for 50% #urgency bonus? Y - https://github.com/Expensify/App/issues/28078#issuecomment-1767805933

Upwork job is [here](https://www.upwork.com/jobs/~0131655c00ab293751).

@rushatgabhane could you let us know about a regression test?

**Comment by Christinadobrzyn** [comment] 2023-10-31 20:34
nudge @rushatgabhane about a regression test, thanks!

**Comment by Christinadobrzyn** [comment] 2023-11-06 22:21
Dming @rushatgabhane to see if we need a regression test

**Comment by rushatgabhane** [comment] 2023-11-07 03:27
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-11-07 03:40
Created a manual request https://staging.new.expensify.com/r/8819237970145454

**Comment by Christinadobrzyn** [comment] 2023-11-07 18:52
awesome! I think this can be closed.

**Closed by Christinadobrzyn** 2023-11-07 18:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-13 21:53
$750 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/28078#issuecomment-1785471504).
