### ISSUE TITLE
[HOLD for payment 2024-10-29] [HOLD for payment 2024-10-25] [$250] Android - Search - Keyboard does not auto open in Search modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51010] opened 2024-10-17 12:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Open a report.
3. Tap Search icon.

## Expected Result:
Keyboard will auto open.

## Actual Result:
Keyboard does not auto open.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/01e1dcce-315f-496d-9d31-2b69b83b354b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846960678624915682</li>
        <li>Upwork Job ID: 1846960678624915682</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 104471055</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by Kicu** [comment] 2024-10-17 14:22
Was this tested on a physical phone? Cos I'm testing this on android emulator right now (Pixel) and the keyboard does open:

https://github.com/user-attachments/assets/03b9bf9f-7cee-4dda-9ade-0f47feebc592

https://github.com/user-attachments/assets/8cb2c6b5-2ce6-4ff7-be97-44cab7d15de0

I did however noticed exactly one case where it didn't open, but I cannot reproduce it consistently. All the other cases it did open.
I can test on a physical device later, but I'm curious if other people can reproduce this easily?

**Comment by luacmartins** [comment] 2024-10-17 15:45
I can reliably reproduce this on a Pixel 6 physical device

**Comment by srikarparsi** [comment] 2024-10-17 16:51
I'm also able to pretty reliably reproduce this on an emulator (I'm using Pixel 7 Pro API 33):

https://github.com/user-attachments/assets/78ab4279-40fa-4600-8f3f-6b55cf73b126

**Comment by srikarparsi** [comment] 2024-10-17 17:05
Going to make this external

**Comment by huult** [comment] 2024-10-17 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Keyboard does not auto open in Search modal

### What is the root cause of that problem?

This issue of [react-native-modal](https://github.com/react-native-modal/react-native-modal/issues/516)

### What changes do you think we should make in order to solve the problem?
We should update follow [this comment](https://github.com/react-native-modal/react-native-modal/issues/516#issuecomment-997961846)
```diff
//.src/components/Search/SearchRouter/SearchRouterInput.tsx#L87
+    useEffect(() => {
+        InteractionManager.runAfterInteractions(() => {
+            inputRef.current?.blur();
+            inputRef.current?.focus();
+        });
+    }, []);
```
<details>
<summary>

https://github.com/user-attachments/assets/2f970dbe-037a-47ab-a7c0-afc28145c5ac

</summary></details>

**Comment by shahinyan11** [comment] 2024-10-17 18:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Search - Keyboard does not auto open in Search modal
### What is the root cause of that problem?
We already encounter such issues in other places. for example [this](https://github.com/Expensify/App/issues/17479) one
### What changes do you think we should make in order to solve the problem?
1. Add below code in `SearchRouterInput` component
```
    const inputRef = useRef(null);

    useEffect(() => {
        if(autoFocus){
            InteractionManager.runAfterInteractions(()=>{
                inputRef.current?.focus();
            })
        }
    }, [])
```
2. Add `ref={inputRef}` on [TextInput](https://github.com/Expensify/App/blob/e2018aab2df23023d2ef72aa9a5a054a8262c56d/src/components/Search/SearchRouter/SearchRouterInput.tsx#L91) component
### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment] 2024-10-17 18:28
Note for C+: It looks like the other proposal also uses the shouldDelayFocus prop in TextInput to execute code similar to my example.
https://github.com/Expensify/App/blob/0e388222c8425caa13cc0f88e1317edcc755ea0f/src/components/TextInput/BaseTextInput/index.tsx#L108-L121

**Comment by jayeshmangwani** [comment] 2024-10-17 18:49
Both `useAutoFocusInput` and `shouldDelayFocus` work, but IMO we should go with `useAutoFocusInput`, as it's used across all auto-focused InputWrapper components.

@srikarparsi @luacmartins I'm attaching a video below to confirm how the input behaves after these changes. For example, if the keyboard is open on the report screen and we press 'Search' the following should happen:

1. Keyboard will hide.
2. Navigation to the Search screen will occur.
2. Keyboard will reopen once navigation finishes.

https://github.com/user-attachments/assets/781091ac-014c-4e91-906c-768d0dadb727

**Comment by huult** [comment] 2024-10-17 19:44
@jayeshmangwani , I tried using `useAutoFocusInput` during my debugging, but my emulator wasn’t working, so I didn't use it and found a new solution. Just a note for you. 😄 
<details>
<summary>

https://github.com/user-attachments/assets/271d6925-a448-4972-b372-c3d4cbe6a45d

</summary>
</details>

**Comment by jayeshmangwani** [comment] 2024-10-17 19:48
> I tried using `useAutoFocusInput` during my debugging, but my emulator wasn’t working, so I didn't use it and found a new solution. Just a note for you. 😄

remove autoFocus and it will work 😄

**Comment by srikarparsi** [comment] 2024-10-17 19:51
> I'm attaching a video below to confirm how the input behaves after these changes. For example, if the keyboard is open on the report screen and we press 'Search' the following should happen:

Yes, this looks correct to me

**Comment by srikarparsi** [comment] 2024-10-17 19:53
It looks like @abzokhattab’s proposal does this, @jayeshmangwani have you had a chance to verify this

**Comment by jayeshmangwani** [comment] 2024-10-17 19:53
> Yes, this looks correct to me

Great! We can go with @abzokhattab 's [Proposal](https://github.com/Expensify/App/issues/51010#issuecomment-2419429623) of using useAutoFocusInput

🎀 👀 🎀 C+ reviewed

**Comment by srikarparsi** [comment] 2024-10-17 19:57
Awesome, @abzokhattab do you think you’ll be able to put up a PR soon?

**Comment by jayeshmangwani** [comment] 2024-10-17 20:00
> have you had a chance to verify this

Yes I've tested, and it works fine

**Comment by srikarparsi** [comment] 2024-10-17 20:05
> Thank you. the PR will be ready in the morning.

Sorry, will that be in around an hour or a little longer. Since this is a deploy blocker, it’s a little more time sensitive.

**Comment by srikarparsi** [comment] 2024-10-17 20:07
Awesome, thank you!

**Comment by jayeshmangwani** [comment] 2024-10-17 21:07
@abzokhattab I noticed you're actively engaged with [this issue ](https://github.com/Expensify/App/issues/51050) and have updated a proposal just few minuted ago. Could you focus on this Deploy Blocker instead of introducing new proposals on other Issue?

**Comment by jayeshmangwani** [comment] 2024-10-17 21:34
Thanks, I am starting testing

**Comment by srikarparsi** [comment] 2024-10-18 00:25
[PR](https://github.com/Expensify/App/pull/51064) merged, requested [CP](https://expensify.slack.com/archives/C07J32337/p1729211079346269)

**Comment by marcaaron** [comment] 2024-10-18 17:19
@luacmartins @srikarparsi please remove the deploy blocker label and check this off whenever we confirm the fix worked.

**Comment by srikarparsi** [comment] 2024-10-18 18:02
Fix worked

https://github.com/user-attachments/assets/0013c8ec-3301-4cc2-94d7-3b3b221c0e90

**Comment by sakluger** [comment] 2024-10-25 22:20
Weird - I'm not sure why the second payment hold was added, this was deployed to prod 7 days ago. I'll prep the payment summary.

Summarizing payment on this issue:

Contributor: @abzokhattab $250, paid via Upwork
Contributor+: @jayeshmangwani $250, please complete the BZ checklist, then request on Newdot

**Comment by jayeshmangwani** [comment] 2024-10-26 06:31
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48785
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/48785#discussion_r1817687781
- [ ]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [ ]  [@jayeshmangwani] Determine if we should create a regression test for this bug. N/A
- [ ]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. N/A

**Comment by jayeshmangwani** [comment] 2024-10-26 06:32
@sakluger  I’ve checked the first two items on the checklist. For the third, I’m not sure if discussion is necessary here, as it could have been addressed in the PR review. As for items 4 and 5, I don’t think dedicated regression tests are needed.

**Comment by sakluger** [comment] 2024-10-28 16:10
Thanks @jayeshmangwani!

**Closed by sakluger** 2024-10-28 16:10 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-06 11:58
$250 approved for @jayeshmangwani
