### ISSUE TITLE
[$500] Android - Compose-Code block applied for url, half link is missing, cannot be seen.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30292] opened 2023-10-24 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter `[https://github.com/Expensify/App/issues/21400#issuecomment-1622190091`](https://github.com/Expensify/App/issues/21400#issuecomment-1622190091%60)
in compose box
4. Send the message

## Expected Result:
Code block applied for url and that full url link must be visible

## Actual Result:
Code block applied for url, half link is missing, cannot be seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/f4e39285-8c76-416a-b1d1-3c4b7dfe52d9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106e78b3f023dfa6e</li>
        <li>Upwork Job ID: 1716916531386109952</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-10-24 22:11
I think this bug has the same root cause as this issue: https://github.com/Expensify/App/issues/4733 (lots of context here about the problem)

**Comment by bfitzexpensify** [comment] 2023-10-31 23:10
How does the proposal in https://github.com/Expensify/App/issues/30292#issuecomment-1781303250 look @Ollyws?

**Comment by bfitzexpensify** [comment] 2023-11-03 19:14
Bump on proposal review when you get a chance @Ollyws - thank you!

**Comment by bfitzexpensify** [comment] 2023-11-06 23:03
Yep, I think that's a good call. OK, closing this in favour of that.

**Closed by bfitzexpensify** 2023-11-06 23:03 UTC
Labels: External, Daily, Help Wanted, Bug
