### ISSUE TITLE
[Payment Due June 21] [$250] Can't open tag with tag name with % special characters

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42549] opened 2024-05-23 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1716460972676239

## Action Performed:
1. Sign into https://staging.new.expensify.com/
2. Click Account Settings > Workspace > More Features > tags
3. Create a tag name !@#$%^&*(*&^%$#@ (it seems to be the `%' that throws the error'
4. Save the Tag > Click on the tag again - notice the "uh-oh, something went wrong!" error 

## Expected Result:
The user should access to tag setting page

## Actual Result:
App crashes - notice the "uh-oh, something went wrong!" error 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ea5150d1-5555-4877-a704-f862a9b36219

https://github.com/Expensify/App/assets/51066321/0175fe42-daea-4b47-a341-0c29f2b83182

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e766d47beaa045bb</li>
        <li>Upwork Job ID: 1795004446572822528</li>
        <li>Last Price Increase: 2024-05-27</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 102522628</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by DylanDylann** [comment] 2024-05-23 18:42
I reported this bug from [here](https://github.com/Expensify/App/pull/42381#issuecomment-2126784349), I would love to take this issue as C+ if this is external

**Comment by abzokhattab** [comment] 2024-05-23 20:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
app crashes when opening a tag with a name having special characters 
### What is the root cause of that problem?
when clicking on a tag inside the tags page, the `tagName` is passed as a route param after being encoded as URI:
https://github.com/Expensify/App/blob/b9516382aea50484fb8d3a0ebe1caee69fbaeace/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L161

https://github.com/Expensify/App/blob/788b3f6d5e924e45fe623e73db0d05e479de73d8/src/ROUTES.ts#L677

then inside when the `TagSettingsPage` is loaded, the tagName is parsed back to the original value using `decodeURIComponent`
https://github.com/Expensify/App/blob/788b3f6d5e924e45fe623e73db0d05e479de73d8/src/libs/Navigation/linkingConfig/config.ts#L433-L438
finally inside the `TagSettingsPage` 
the `route.params.tagName` is wrongly decoded again causing the decode function to throw an error: https://github.com/Expensify/App/blob/30b0dc852369f69cfe83e3d08b60af70d529d8db/src/pages/workspace/tags/TagSettingsPage.tsx#L47-L49


 
### What changes do you think we should make in order to solve the problem?

there is no need to decode the tagName inside the `TagSettingsPage` since the value is already parsed back to the original value inside the navigation config, 

so we should modify [this](https://github.com/Expensify/App/blob/30b0dc852369f69cfe83e3d08b60af70d529d8db/src/pages/workspace/tags/TagSettingsPage.tsx#L47-L49) to:
```js
    const currentPolicyTag = policyTag.tags[route.params.tagName] ?? Object.values(policyTag.tags ?? {}).find((tag) => tag.previousTagName === route.params.tagName);
```

**Comment by DylanDylann** [comment] 2024-05-24 07:40
I reported this bug from [here](https://github.com/Expensify/App/pull/42381#issuecomment-2126784349), I would love to take over this issue as C+ if this is external

**Comment by Christinadobrzyn** [comment] 2024-05-27 05:58
Hey @DylanDylann I'm not able to reproduce this on safari. I'm doing the following: 

1. Create a workspace > Click More Features > toggle on Tags
2. Click Add Tag 
3. Create a tag with tag name including special characters [ex: jlkaf&(*)*(&(*^(*^*(&)*)(]
4. Save the Tag
5. Click Enabled > be able to enable and disable the tag

There is some other weird stuff happening that might be related? Are you doing something different to get this issue?

https://github.com/Expensify/App/assets/51066321/c753af6b-5938-4578-a9f1-f6a806b498aa

**Comment by Christinadobrzyn** [comment] 2024-05-27 07:17
@DylanDylann do you think this might be related? https://github.com/Expensify/App/issues/41414

**Comment by DylanDylann** [comment] 2024-05-27 07:51
@Christinadobrzyn The original bug can still be reproduced. Please try again with this name: `!@#$%^&*(*&^%$#@`

**Comment by DylanDylann** [comment] 2024-05-27 07:57
@Christinadobrzyn I can't reproduce your bug [here](https://github.com/Expensify/App/issues/42549#issuecomment-2132698939). Could you copy exactly 2 tag names used in your video?

**Comment by Christinadobrzyn** [comment] 2024-05-27 08:06
Ah thanks @DylanDylann - I can reproduce with !@#$%^&*(*&^%$#@ (I think it's just the % that's causing the error). Updated the OP. Do you think this can be external?

**Comment by DylanDylann** [comment] 2024-05-27 08:08
I checked this bug before reporting it. This is a bug from the front end. Let's make it external

**Comment by DylanDylann** [comment] 2024-05-27 08:11
> Do you think this is related - https://github.com/Expensify/App/issues/41414 - seems to be the same error

@Christinadobrzyn  This is different from https://github.com/Expensify/App/issues/41414

**Comment by Christinadobrzyn** [comment] 2024-05-28 05:02
Awesome - we have some proposals to review when you have a moment @DylanDylann!

**Comment by DylanDylann** [comment] 2024-05-28 05:04
Sure, I will review proposals by the end of today or tomorrow

**Comment by truph01** [comment] 2024-05-28 10:21
I updated the [proposal](https://github.com/Expensify/App/issues/42549#issuecomment-2133351642) a bit to fix a malformed permalink

**Comment by DylanDylann** [comment] 2024-05-29 02:46
All proposals work well. But I prefer @truph01's [proposal](https://github.com/Expensify/App/issues/42549#issuecomment-2133351642) because it also addresses the bug on the category page with an appropriate solution

🎀 👀 🎀 C+ reviewed

**Comment by truph01** [comment] 2024-05-29 06:36
@ShridharGoel It's unused in the codebase so there's no reason to keep it. The back-end also doesn't return that field, it just exists in optimistic data.

**Comment by lakchote** [comment] 2024-05-30 07:24
@truph01's proposal LGTM 👍

**Comment by truph01** [comment] 2024-05-31 15:22
I am implementing the PR

**Comment by Christinadobrzyn** [comment] 2024-06-05 07:34
Update for Melvbot - looks like the [PR](https://github.com/Expensify/App/pull/42937) is in the works!

**Comment by DylanDylann** [comment] 2024-06-12 06:55
@Christinadobrzyn The PR needs approval from @lakchote, but he is out of the office until July 1st.

**Comment by Christinadobrzyn** [comment] 2024-06-12 08:28
Ah okay, let me see if I can get someone else to review the PR. Asking the team - https://expensify.slack.com/archives/C066HJM2CAZ/p1718180871595969

**Comment by Christinadobrzyn** [comment] 2024-06-13 01:39
Just a heads up - I'm going to be ooo until June 24th so going to assign a teammate to watch this while I'm away

**Comment by DylanDylann** [comment] 2024-06-13 02:55
The PR is merged. Waiting for deploying to production

**Comment by DylanDylann** [comment] 2024-06-19 04:51
@JmillsExpensify The PR is deployed to production 4 days ago. Please update the status of this issue

**Comment by mvtglobally** [comment] 2024-06-20 14:20
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2024-06-24 23:05
Looks like the PR was deployed into production on June 14 so the 7 day hold ended on June 21st. This is due for payment. correct? @DylanDylann 

Payouts due:

- [ ] Contributor: $250 @truph01 (can you please accept our offer - https://www.upwork.com/nx/wm/offer/102802999)
- [X] Contributor+: $250 @DylanDylann (paid in upwork- https://www.upwork.com/nx/wm/workroom/37426723/details)

Upwork job is [here](https://www.upwork.com/ab/applicants/1795004446572822528/hired).

@DylanDylann do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-06-26 15:11
@truph01 can you please accept the Upwork offer - https://github.com/Expensify/App/issues/42549#issuecomment-2187575786

@DylanDylann do we need a regression test for this?

**Comment by DylanDylann** [comment] 2024-06-26 15:14
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Open app
2. Click Account Settings > Workspace > More Features > tags
3. Create a tag name !@#$%^&(&^%$#@ (it seems to be the `%' that throws the error'
4. Save the Tag > Click on the tag again - notice the "uh-oh, something went wrong!" error
5. Observe that the user should access to tag setting page


Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2024-06-27 20:18
Regression test - https://github.com/Expensify/Expensify/issues/408381

Waiting on finalising payment - https://github.com/Expensify/App/issues/42549#issuecomment-2187575786

**Comment by Christinadobrzyn** [comment] 2024-06-28 20:27
This is done other than the payment to @truph01. 

Moving this to weekly to wait for @truph01 to accept offer - https://www.upwork.com/nx/wm/offer/102802999

**Comment by truph01** [comment] 2024-07-01 04:56
@Christinadobrzyn Offer accepted, sorry for the delay 🙏

**Comment by Christinadobrzyn** [comment] 2024-07-01 16:29
Thanks @truph01 - paid out based on this payment summary - https://github.com/Expensify/App/issues/42549#issuecomment-2187575786

Closing!

**Closed by Christinadobrzyn** 2024-07-01 16:29 UTC
Labels: External, Weekly, Bug
