### ISSUE TITLE
[$500] Onfido/Plaid CORS error in the console

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24260] opened 2023-08-08 12:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23944
## Action Performed:
1. Go to staging.new.expensify.com
2. Open the JS console
3. Observe the CORS error

## Expected Result:
No CORS errors relating to onfido and plaid.

## Actual Result:
CORS error in the console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6156985_Screen_Shot_2023-08-07_at_4 56 02_PM](https://github.com/Expensify/App/assets/78819774/207da7a6-cd31-437f-9f17-0fcf7f8cd3e3)

https://github.com/Expensify/App/assets/78819774/3a1263ca-79dc-4bb1-86de-157e865168f0

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160d3b3d39fa70308</li>
        <li>Upwork Job ID: 1690041670446833664</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-08-11 16:41
I can't reproduce this issue, but if it does happen it could block functionality from those sources. Asked in [eng-chat](https://expensify.slack.com/archives/C03TQ48KC/p1691772016208099) if anyone else is experiencing this too

**Comment by trjExpensify** [comment] 2023-08-11 16:44
Looks like Paulo can, and I can as well. Going to move it on `internal`, but modify the OP.

**Comment by trjExpensify** [comment] 2023-08-14 10:06
No change since Friday, assigned to @aldo-expensify to work on :)

**Comment by aldo-expensify** [comment] 2023-08-14 19:27
This has been here for a while and I don't think it is causing problems beside the console error. I'll make this `weekly`.

I found some old intent to fix this here: https://expensify.slack.com/archives/C03TQ48KC/p1673266216576919

**Comment by trjExpensify** [comment] 2023-08-22 12:55
Looks like Melvin bumped this to `daily`. We've only got a couple of weeks left before this breaks WAQ, what's the plan to get a PR up @aldo-expensify? :)

**Comment by aldo-expensify** [comment] 2023-08-22 20:40
I found this page that does a report on the content policies:

https://csper.io/evaluations/64e51c8f15b491ee727119de

Maybe it can be handy to detect what we have to fix

**Comment by aldo-expensify** [comment] 2023-08-22 20:43
Our Content security policies: https://github.com/Expensify/Cloudflare-Workers/blob/031ff872fd5ad3bd6a71cb102d4274969df6d001/new.expensify.com/wrangler.toml#L19

**Comment by aldo-expensify** [comment] 2023-08-22 20:47
This appears to be the `<script>` causing the problem:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/87341702/a568d2ca-e795-4c51-a836-df8825a9ce96">

**Comment by aldo-expensify** [comment] 2023-08-22 20:50
Seems like it is some Cloudflare functionality adding that `<script` (`cdn-cgi/challenge-platform/scripts/invisible.js`)
It may be "Bot fight mode in the Firewall settings"

**Comment by aldo-expensify** [comment] 2023-08-22 20:53
For reference, here they seem to list the Content policies you may need for different Cloudflare's products: https://developers.cloudflare.com/fundamentals/get-started/reference/content-security-policies/

**Comment by aldo-expensify** [comment] 2023-08-22 20:55
According to https://developers.cloudflare.com/bots/reference/javascript-detections/#if-you-have-a-content-security-policy-csp, we are in the third case, which is the discourage way of using the CSP (content security policy). It says that we should be using `nonce-` for script tags.

**Comment by aldo-expensify** [comment] 2023-08-25 19:52
Not getting to this today, I'll work on it early next week.

**Comment by aldo-expensify** [comment] 2023-08-29 01:10
No updates yet, I'll give it more time later.

**Comment by trjExpensify** [comment] 2023-08-30 13:36
Okay, thanks Aldo! We've only got a week before this breaks WAQ, so it would be good to avoid that.

**Comment by aldo-expensify** [comment] 2023-09-01 00:59
Created a draft PR which I think may fix the issue. I asked for more experienced eyes to have take a look before making it ready for review (asked [here](https://expensify.slack.com/archives/C03TQ48KC/p1693529885758789)).

**Comment by trjExpensify** [comment] 2023-09-04 09:43
(So annoying when all the labels get removed when adding one.. grr!)

Woop, thanks Aldo! I see we're popping the PR on hold for a few days until after the conference, yeah?

**Comment by trjExpensify** [comment] 2023-09-13 10:57
We should be good to proceed here now with the freeze over, @aldo-expensify.

**Comment by aldo-expensify** [comment] 2023-09-13 13:13
We will deploy the changes next week when Justin is in Bali

**Comment by aldo-expensify** [comment] 2023-09-20 07:26
The fix was deployed and the error is not there anymore: https://github.com/Expensify/Cloudflare-Workers/pull/86#issuecomment-1727119715

**Closed** 2023-09-20 07:26 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
