### ISSUE TITLE
[HOLD for payment 2024-07-22] [Unapprove in NewDot - Collect] Show Unapprove btn, add Confirm modal, call API endpoint

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#44066] opened 2024-06-20 08:05 UTC
Tracking issue: https://github.com/Expensify/Expensify/issues/384891

Note: This issue can't be MERGED until https://github.com/Expensify/Expensify/issues/406171 is finished. But it can be started while that other issue is WIP 🙏 

Design doc sections:
1. [Show “Unapprove” button in NewDot](https://docs.google.com/document/d/1SMogmfaVdQAQSx92I8vwEh9qFD8PbSEsKS9yK-trHmg/edit#bookmark=id.d5nx172ovq2y)
2. [Add new use of component ConfirmModal](https://docs.google.com/document/d/1SMogmfaVdQAQSx92I8vwEh9qFD8PbSEsKS9yK-trHmg/edit#bookmark=id.5lgk3xc3bv9s)
3. [Create function unapproveExpenseReport in NewDot](https://docs.google.com/document/d/1SMogmfaVdQAQSx92I8vwEh9qFD8PbSEsKS9yK-trHmg/edit#bookmark=id.hwig0bkijqs8)

Goals:
1. Show the Unapprove button to the correct people at the correct time in the correct place
2. When user clicks the button, show new ConfirmModal IFF report has been exported to connected accounting 
package
    - Note: I probably need to add more details about when this needs to get shown
3. Call new API endpoint, UnapproveExpenseReport
    - Unapproving is Offline Pattern B

Note: For the "show warning modal if report has already been exported to accounting package" stuff, don't implement that here! That will be covered in https://github.com/Expensify/App/issues/44884

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by Beamanator** [comment] 2024-06-20 08:06
@rushatgabhane is assigned to complete this job 👍

**Comment by isabelastisser** [comment] 2024-06-29 00:26
@rushatgabhane, can you please provide an update? Thanks!

**Comment by rushatgabhane** [comment] 2024-06-29 09:14
PR above ^

We're waiting for https://github.com/Expensify/App/pull/44229#discussion_r1650294292

**Comment by Beamanator** [comment] 2024-07-01 09:09
FYI I've got a few more backend changes I'm making today to hopefully this this App PR ready for testing mid-week

**Comment by Beamanator** [comment] 2024-07-05 06:26
@rushatgabhane backend changes shouldddd all be on Staging! Your PR can be tested now in staging! (not technically "off hold" till the next deploy, which may happen Monday)

**Comment by Beamanator** [comment] 2024-07-05 07:10
Note: added this to the OP:

> Note: For the "show warning modal if report has already been exported to accounting package" stuff, don't implement that here! That will be covered in https://github.com/Expensify/App/issues/44884

**Comment by Julesssss** [comment] 2024-07-08 15:10
hey @Beamanator, [here's](https://github.com/Expensify/Expensify/issues/410822) a server error that I think is related to these changes.  I removed the blocker label as this seems to be a new App feature.

```
Throw ExpException - 8ba5fe883b2f7d19c56045fcd8330f36 ~~ message: '403 Incorrect report type' exceptionMessage: 'Auth UnapproveExpenseReport returned an error' exceptionFile: '/git/releases/expensify.com/1fe9c8e/lib/Auth.php' exceptionLine: '126' exceptionCode: '403'
```

**Comment by blimpich** [comment] 2024-07-08 21:02
Follow up issue for this: https://github.com/Expensify/App/issues/44991.

**Comment by jayeshmangwani** [comment] 2024-07-10 22:12
@isabelastisser Can you please assign me to the issue, so that I can keep track it on K2?

**Comment by isabelastisser** [comment] 2024-07-18 20:05
@rushatgabhane, please complete the BZ list. Thanks!

**Comment by isabelastisser** [comment] 2024-07-18 20:08
Payment summary:

- @rushatgabhane requires payment through NewDot Manual Requests $250 C+ review
- @jayeshmangwani requires payment through NewDot Manual Requests $250 Contributor

I will be OOO tomorrow and next week, so I am reassigning this until I return on July 29. Thanks, @sakluger!

Status: Payment is due on July 22.

**Comment by jayeshmangwani** [comment] 2024-07-19 06:00
The Test steps from the PR will be sufficient for the regression test.

## Regression Test Proposal


1. Go to a control policy as an admin.
2. Make yourself the approver.
3. Submit an expense to the policy.
4. Approve the expense and go to the expense.
5. Click on the report header.
6. Verify that we can see the "Unapprove" button.
7. Verify that after clicking "Unapprove" we can see the "unapproved $x" message in the chat.

**Connect to an accounting integration**


1. Connect to Xero / QuickBooks / Sage / NetSuite.
2. Submit an expense to the policy.
3. Approve the expense and go to the expense.
4. Click the report header.
5. Verify that we can see the "Unapprove" button.
6. Click "Unapprove" and verify a modal shows a warning that you're connected to an accounting integration.
7. Verify that after clicking "Unapprove" we can see an "unapproved $x" message in the chat.


Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-07-22 20:43
$250 approved for @rushatgabhane

**Comment by sakluger** [comment] 2024-07-22 23:24
Looks good! Closing 👍

**Closed by sakluger** 2024-07-22 23:24 UTC
Labels: External, Daily, NewFeature, Awaiting Payment

**Comment by jayeshmangwani** [comment] 2024-07-25 04:57
Requested $250
