### ISSUE TITLE
[$250] Chat - Duplicate concierge when deep linking to onboarding and signing in with expensifail

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49402] opened 2024-09-18 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+nl613@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:**   ##Applause-Internal  team

## Action Performed:
1. Sign out
2. Navigate to staging.new.expensify.com/onboarding/purpose
3. Sign in with an expensifail account

## Expected Result:
One concierge is seen on the LHN

## Actual Result:
Duplicate Concierge seen on the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f54eb7fc-3d7e-4b7a-9569-fdd4fccde5c8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837203927265235886</li>
        <li>Upwork Job ID: 1837203927265235886</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by VickyStash** [comment] 2024-09-23 13:22
I'm able to reproduce it on staging, but not on the dev. I'll try to check maybe it got fixed by some PR.

**Comment by VickyStash** [comment] 2024-09-23 14:11
Also, it looks like this issue is the same as https://github.com/Expensify/App/issues/44465 and looks similar to https://github.com/Expensify/App/issues/49507

**Comment by VickyStash** [comment] 2024-09-24 14:33
Okay, I've figured out why I can't reproduce this bug in dev. It looks like it got fixed by this PR: https://github.com/Expensify/App/pull/49516
cc @mollfpr

**Comment by isabelastisser** [comment] 2024-09-26 13:39
Bump @izarutskaya. It looks like this can no longer be reproduced, can you please confirm? Thanks!

**Comment by isabelastisser** [comment] 2024-09-26 20:21
It can no longer be reproduced, closing.

**Closed by isabelastisser** 2024-09-26 20:21 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
