### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Distance - Invalid waypoints aren't cleared when a request fails

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48631] opened 2024-09-05 10:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4919784
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Go to workspace chat
4. Go offline
5. Go to submit distance expense
6. Enter an invalid waypoint and click save
12. Add another waypoint and continue to submit the expense
13. Go online
14. Verify the request fails
15. Green plus, submit an expense, distance
16. Go to enter a waypoint

## Expected Result:
Invalid waypoints should be removed from suggestion list

## Actual Result:
Invalid waypoints stay on the suggestion list

## Workaround:
Submit a distance expense with valid waypoints, which will clear any invalid recent waypoints. Or. sign out and back in, since the invalid recent waypoints are only on the frontend.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c514b4fe-13e5-4dfa-8216-662571941710

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833644939720857104</li>
        <li>Upwork Job ID: 1833644939720857104</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104234581</li>
<li>wildan-m | Contributor | 104234583</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by izarutskaya** [comment] 2024-09-05 10:45
We think this issue might be related to the #collect project.

**Comment by suneox** [comment] 2024-09-11 02:53
@nyomanjyotisa  Thank you for your proposal, but we also need to prevent selecting invalid waypoints when the network is slow or offline.

**Comment by nkdengineer** [comment] 2024-09-11 03:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invalid waypoints stay on the suggestion list

### What is the root cause of that problem?
Here we only check the waypoint is empty or not to decide to save this waypoint to recent list

https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/libs/actions/Transaction.ts#L127-L130
### What changes do you think we should make in order to solve the problem?
We can use the `waypointHasValidAddress` function as we do [here](https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/libs/TransactionUtils/index.ts#L645) to check the waypoint is valid or not before saving it to recent list

```
if (!recentWaypointAlreadyExists && waypoint && TransactionUtils.waypointHasValidAddress(waypoint)) {
    const clonedWaypoints = lodashClone(recentWaypoints);
    clonedWaypoints.unshift(waypoint);
    Onyx.merge(ONYXKEYS.NVP_RECENT_WAYPOINTS, clonedWaypoints.slice(0, CONST.RECENT_WAYPOINTS_NUMBER));
}
```

https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/libs/actions/Transaction.ts#L127-L130
### What alternative solutions did you explore? (Optional)

**Comment by suneox** [comment] 2024-09-11 12:16
@johncschuster I’d like to confirm should we prevent selecting invalid waypoints in offline mode? (currently, we don’t validate waypoints in offline mode) to maintain consistency with the online flow.


https://github.com/user-attachments/assets/23dd6229-13a4-475d-9403-948f6f2e0e11

**Comment by trjExpensify** [comment] 2024-09-12 00:08
>but we also need to prevent selecting invalid waypoints when the network is slow or offline.

Why so? Don't we do that validation when you come back online? 🤔 CC: @neil-marcellini for vis on this issue.

**Comment by nkdengineer** [comment] 2024-09-12 03:18
I think we should only prevent saving invalid waypoints to the recent list because if we prevent selecting invalid waypoint in offline, the user that doesn't have recent waypoints list can't create distance request in offline.

**Comment by trjExpensify** [comment] 2024-09-13 00:05
>I think we should only prevent saving invalid waypoints to the recent list because if we prevent selecting invalid waypoint in offline, the user that doesn't have recent waypoints list can't create distance request in offline.

I agree. We shouldn't save invalid waypoints to recents, they're useless. But we shouldn't prevent selecting invalid waypoints, because we don't know if they are valid or not when you're offline, so then you couldn't create a distance request when offline.

**Comment by suneox** [comment] 2024-09-13 09:32
>  But we shouldn't prevent selecting invalid waypoints, because we don't know if they are valid or not when you're offline, so then you couldn't create a distance request when offline.

Based on the expected result @nkdengineer [proposal](https://github.com/Expensify/App/issues/48631#issuecomment-2342533947) LGTM

🎀 👀 🎀 C+ reviewed

**Comment by suneox** [comment] 2024-09-13 13:02
I’d like to clarify that the selected solution is to prevent saving an invalid waypoint, rather than filtering out the invalid waypoints in the list. The implementation details can be addressed during the code review process. The alternative [solution](https://github.com/Expensify/App/issues/48631#issuecomment-2331233387) proposed by @nyomanjyotisa is the same as @nkdengineer [solution](https://github.com/Expensify/App/issues/48631#issuecomment-2342533947), which is to prevent saving an invalid waypoint. However, I selected @nkdengineer proposal because it was posted before @nyomanjyotisa notify [an update](https://github.com/Expensify/App/issues/48631#issuecomment-2342534329).

But I just double-checked, and it turns out that the updated proposal (at [2024-09-11T03:14:11Z](https://api.github.com/repos/Expensify/App/issues/comments/2342533947)) was actually submitted before the new proposal (at [2024-09-11T03:14:32Z](https://api.github.com/repos/Expensify/App/issues/comments/2331233387)).

Sorry everyone, this was my mistake for not checking the detailed update times, so I’ve updated the [selected proposal](https://github.com/Expensify/App/issues/48631#issuecomment-2348488478) accordingly.

**Comment by neil-marcellini** [comment] 2024-09-17 19:28
Hi, sorry for the delay. I reviewed all proposals and I would like to suggest something different.

The root cause of the issue, in my opinion, is that the optimistically saved recent waypoints are not updated when we receive an error from the backend that the distance request failed to create, because the waypoints are invalid.

Idk if the error is that specific, but if a distance request fails to create then we should remove the waypoints it contains from the recent waypoints. A potential problem is if the recent waypoints already contain 'validAddressA' and the failed distance expense contains waypoints 'validAddressA', 'invalidAddressB'. We wouldn't want to remove 'validAddressA' from the recent waypoints, in that case. Therefore we'll also need mark new waypoints in the recent waypoints list as pending to be added, and on failure only remove those that are pending addition to the recent waypoints list.

Does that sounds good to you all? The first person to update or post a good proposal following this plan will be assigned.

**Comment by nkdengineer** [comment] 2024-09-18 07:48
@neil-marcellini But we will save the waypoint to the recent list when we select the waypoint and we can have a case that user can enter an invalid waypoint then edit to another before creating the distance request.

**Comment by neil-marcellini** [comment] 2024-09-18 17:30
Ok, interesting point. I think that flow would work like this.

The user enters an invalid waypoint, it's saved to the recent waypoint list optimistically and marked as pending add. Then, the user edits it to a valid waypoint which is also saved to recent waypoints as pending add. The request succeeds and an Onyx update with method 'set' returns the proper recent waypoints, clearing the invalid one.

In the same case where an invalid waypoint is edited to a valid one, but where there is still at least one invalid waypoint, the failure data set up in the response should reset the recent waypoints list to one where all waypoints are not pending addition.

I think that should all work. Any more questions?

**Comment by johncschuster** [comment] 2024-09-20 22:34
[Bumping Slack for proposals](https://expensify.slack.com/archives/C01GTK53T8Q/p1726871640819129)

**Comment by wildan-m** [comment] 2024-09-23 04:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invalid waypoints remain on the suggestion list when creating a distance request.

### What is the root cause of that problem?

We are not revert the recent waypoints if something error when creating distance request.

### What changes do you think we should make in order to solve the problem?

We can revert recentWaypoints to the latest validated value if error occurs.

`getRecentWaypoints()` can be from Transaction action or as `createDistanceRequest` param

src/libs/actions/IOU.ts
```tsx

createDistanceRequest(
.....
    const recentServerValidatedWaypoints = getRecentWaypoints().filter(item => !item.pendingAction)
    onyxData?.failureData?.push({
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.NVP_RECENT_WAYPOINTS}`,
        value: recentServerValidatedWaypoints,
    } )

    API.write(WRITE_COMMANDS.CREATE_DISTANCE_REQUEST, parameters, onyxData);
 .....
```

Flag new waypoint
src/libs/actions/Transaction.ts
```tsx
function saveWaypoint(transactionID: string, index: string, waypoint: RecentWaypoint | null, isDraft = false) {
..........
    const recentWaypointAlreadyExists = recentWaypoints.find((recentWaypoint) => recentWaypoint?.address === waypoint?.address);
    if (!recentWaypointAlreadyExists && waypoint !== null) {
        const clonedWaypoints = lodashClone(recentWaypoints);
        waypoint.pendingAction = CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD;
        clonedWaypoints.unshift(waypoint);
        Onyx.merge(ONYXKEYS.NVP_RECENT_WAYPOINTS, clonedWaypoints.slice(0, CONST.RECENT_WAYPOINTS_NUMBER));
```

I think we don't need to clear `pendingField`, since the server response will be SET if success, but let me know if that's required
[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/48631-remove-invalid-recent-waypoint?expand=1)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by suneox** [comment] 2024-09-23 09:11
@wildan-m  Thank you for your proposal. We also need to handle the case for `TrackExpense`.

> I think we don't need to clear pendingField, since the server response will be SET if success, but let me know if that's required

![Screenshot 2024-09-23 at 15 51 09](https://github.com/user-attachments/assets/6b405d29-9799-4156-8490-18832eb91520)


@neil-marcellini  Additionally, we need to clear `pendingField` because the response data still includes the `pendingAction` field, to prevent cases where a valid waypoint gets cleared

**Comment by wildan-m** [comment] 2024-09-23 09:57
> @wildan-m Thank you for your proposal. We also need to handle the case for TrackExpense.

@suneox it seems track expense also call request money. do you think we need different treatment for track expense?

> Additionally, we need to clear pendingField because the response data still includes the pendingAction field, to prevent cases where a valid waypoint gets cleared

I didn't notice that, seems it's more appropriate to clear that in the server side (?)

**Comment by suneox** [comment] 2024-09-23 11:10
> @suneox it seems track expense also call request money. do you think we need different treatment for track expense?

@wildan-m `createDistanceRequest` and `trackExpense` are different cases.

> seems it's more appropriate to clear that in the server side

Yep, we’re still waiting for the internal team’s feedback on that point.

**Comment by neil-marcellini** [comment] 2024-09-23 17:23
> @neil-marcellini Additionally, we need to clear `pendingField` on the BE side because the response data still includes the `pendingAction` field, to prevent cases where a valid waypoint gets cleared

Sorry, I'm not quite following. Would you please list the steps taken to encounter this problem and show the response that is returned? You can also link to a draft PR if that's needed to test this. Regardless, I think that the frontend should generally handle the pendingAction / pendingFields data. If there's some reason why that's not possible please let me know why.

**Comment by wildan-m** [comment] 2024-09-23 18:37
@neil-marcellini `successData` is initialized before receiving the server response. The `nvp_expensify_recentWaypoints` latitude and longitude data are set to 0 before the response is received. If we generate the success data from the front end, it will overwrite the server response with lat: 0, lon: 0.

also the `nvp_expensify_recentWaypoints` doesn't have stable index key like reportActions, the local and returned data length can be different, we can't rely on array sequence index.

**Comment by wildan-m** [comment] 2024-09-23 18:49
> createDistanceRequest and trackExpense are different cases.

@suneox sure, but only the `saveWaypoint` function modifies `NVP_RECENT_WAYPOINTS` and it is called in `IOURequestStepWaypoint`. The `track expense` feature also utilizes `IOURequestStepWaypoint` but [with different parameters](https://github.com/Expensify/App/blob/a99cf941a355a412e7498c41a69a99b01e35431c/src/components/ReportActionItem/MoneyRequestView.tsx#L331).

**Comment by suneox** [comment] 2024-09-24 08:45
> Sorry, I'm not quite following. Would you please list the steps taken to encounter this problem and show the response that is returned? You can also link to a draft PR if that's needed to test this. Regardless, I think that the frontend should generally handle the pendingAction / pendingFields data. If there's some reason why that's not possible please let me know why.

I'll prepare a test branch to explain the details ASAP

**Comment by suneox** [comment] 2024-09-25 09:58
@neil-marcellini  Currently, the data type for [NVP_RECENT_WAYPOINTS](https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/ONYXKEYS.ts#L895) is an array, but the Onyx library only supports [replacing the entire array](https://www.npmjs.com/package/react-native-onyx#merging-data). Therefore, after receiving new waypoints from the server, we cannot remove pendingAction in the successful request case by `onxyData.successData`

Example:

```javascript
  request data = [
      {
        "keyForList": "waypoint_1727255981380",
        "address": "130 nguyen chi thanh",
        "name": "",
        "lat": 0,
        "lng": 0,
        "pendingAction": "add"
      },
      ...
  ];
  
  response data = [
    {
      "keyForList": "130 Đ. Nguyễn Chí Thanh_1727072486310",
      "address": "130 Đường Nguyễn Chí Thanh, Phường 3, District 10, Ho Chi Minh City, Vietnam",
      "name": "130 Đ. Nguyễn Chí Thanh",
      "lat": 10.7608132,
      "lng": 106.6722783,
      "pendingAction": "add"
    },
    ...
  ]
```

In that case, we need BE support to remove pendingAction from the response. If we don’t remove pendingAction, any subsequent failed request may result in the removal of valid waypoints.

```diff
  response data = [
    {
      "keyForList": "130 Đ. Nguyễn Chí Thanh_1727072486310",
      "address": "130 Đường Nguyễn Chí Thanh, Phường 3, District 10, Ho Chi Minh City, Vietnam",
      "name": "130 Đ. Nguyễn Chí Thanh",
      "lat": 10.7608132,
      "lng": 106.6722783,
-     "pendingAction": "add"
    },
    ...
  ]
```

If this pattern isn’t commonly supported by the backend, we can proceed with the previous solution, which is to only prevent saving an invalid waypoint. WDYT?

**Comment by suneox** [comment] 2024-09-30 15:57
We’re still waiting on the internal team to decide [the solution](https://github.com/Expensify/App/issues/48631#issuecomment-2331233387) prevent adding an invalid waypoint to the list, or [the solution](https://github.com/Expensify/App/issues/48631#issuecomment-2359040533) manage the pendingAction on the client side based on the request status (in this case we need backend support base on [this comment](https://github.com/Expensify/App/issues/48631#issuecomment-2373623014))

**Comment by neil-marcellini** [comment] 2024-10-01 18:42
Ah ok, I'm looking at the original bug report again and I'm realizing that I misinterpreted it originally. Sorry! I now see that no request is sent to the backend at all in the original bug report.

I don't think the provided steps result in a real bug. We have "invalid" waypoints in the recent waypoints list after coming back online, but I don't think that's really an issue. It doesn't cause a problem directly. The problem only occurs later if a user tries to create an expense with those invalid waypoints. When that request fails they are not cleared from the recent waypoints list. I will update the description and testing video accordingly.

Maybe in a perfect world we would queue some kind of action that validates waypoints saved while offline, that aren't used in any request, when going back online; but I don't think that's worth it the effort of building such a mechanism. Instead we can make sure optimistic recent waypoints are cleaned up when the next request is made.

Oh wait, I see that when you go back online and try to use these waypoints they won't be allowed, so the request will have to be made while offline. We don't really have a problem with invalid waypoints from offline being used while online. They can still be used while offline, but they aren't necessarily "invalid" at that point, we don't know whether they are valid or not because we are offline. As soon as any distance expense in successfully created, the invalid waypoints will be removed from Onyx.

Here's video proof:

https://github.com/user-attachments/assets/c709e195-6d4c-4999-a4ce-448b6add7242


So I think the only problem that remains is cleaning up these waypoints when the request fails. The case you mentioned of saving invalid waypoints, then switching to use valid ones is not a problem. We only have a problem when creating requests with invalid waypoints. Furthermore, I don't think we'll need to set any pendingAction data afterall.

**Bug:**
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Go to workspace chat
4. Go offline
5. Go to submit distance expense
6. Enter an invalid waypoint and click save
7. Exit out of the expense creation flow
9. Start a distance expense flow
10. Click on start waypoint and see the suggestion list
11. Select the invalid waypoint
12. Add another waypoint and continue to submit the expense
13. Go online
14. Verify the request fails
15. Green plus, submit an expense, distance
16. Go to enter a waypoints
17. Verify the invalid waypoints is no longer in the recent waypoints list ❌ 

**Pseudocode:**
```
When creating the request onyxData {
    In the optimistic data {
        No changes needed, recent waypoints are already saved before this
    }
    In the success data {
        No changes are needed. The backend will return an Onyx.set update with the proper recent waypoints
    }
    Failure data {
        // The goal is to properly reset the recent waypoints
        Create an Onyx.set update with the recent waypoints currently stored in Onyx
    }
}
```


Please let me know what you all think of this approach 🙇

**Comment by suneox** [comment] 2024-10-02 05:39
@neil-marcellini Based on the latest expected behavior, we can proceed with the updated alternative [proposal](https://github.com/Expensify/App/issues/48631#issuecomment-2367212691) from @wildan-m.

**Comment by neil-marcellini** [comment] 2024-10-02 16:54
Ok sweet, I'm glad we've landed on a solution! I like @wildan-m's [proposal](https://github.com/Expensify/App/issues/48631#issuecomment-2367212691) too. I keep changing my mind, but I like the main solution with the pendingAction approach. Either way could work but that's slightly more clear, and I forgot in my last comment that we need a way to identify the current waypoints that have been saved by the server vs offline. Hiring 🚀

**Comment by wildan-m** [comment] 2024-10-03 02:28
@neil-marcellini Thanks for the assignment, please confirm that we'll go with adding pendingAction? If so, we'll need backend modification as mentioned here https://github.com/Expensify/App/issues/48631#issuecomment-2367639225 and explained more here https://github.com/Expensify/App/issues/48631#issuecomment-2373623014

**Comment by wildan-m** [comment] 2024-10-04 20:17
@neil-marcellini bump https://github.com/Expensify/App/issues/48631#issuecomment-2390374379

**Comment by wildan-m** [comment] 2024-10-07 06:27
@suneox The PR is ready https://github.com/Expensify/App/pull/50323. Thanks!

**Comment by suneox** [comment] 2024-10-18 08:18
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: *N/A*
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. *There isn’t an offending PR in this case, as this is a new requirement intended to cover an edge case.​*
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by johncschuster** [comment] 2024-10-22 02:18
# Payment Summary:
Contributor: @wildan-m paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104234583)
Contributor+: @suneox paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104234581)

**Closed by johncschuster** 2024-10-22 02:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
