### ISSUE TITLE
[HOLD for payment 2024-11-11] [GR Phase 1] Create reusable “UploadFile” component

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50894] opened 2024-10-16 13:45 UTC
Design doc link: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=kix.u4ayheaipya1

**Comment by MrMuzyk** [comment] 2024-10-21 09:13
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

I will take over as Eugene is still working on the AttachmentPicker and I've already finished my other phase 1 tasks.

**Comment by sonialiap** [comment] 2024-11-11 21:01
Payment summary:
- @hungvu193 $250 please request in ND. Do we need a regression test here?

**Comment by hungvu193** [comment] 2024-11-12 01:56
@sonialiap This feature isn't using anywhere at the moment. (Our next PR will use it). I don't think we need regression test for this issue.

**Comment by sonialiap** [comment] 2024-11-12 11:50
Thanks, closing since there's nothing to test yet in a regression test

**Closed by sonialiap** 2024-11-12 11:50 UTC
Labels: Weekly, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-11-20 12:48
$250 approved for @hungvu193
