### ISSUE TITLE
[$250] mWeb - Chat - Before emoji picker box opens, a seperate compose box with cursor is shown briefly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40461] opened 2024-04-18 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4499507
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Tap emoji picker in compose box
4. Select an emoji
5. Note size of emoji in compose box is bigger compare to production
6. Select one more emoji
7. Send the message
8. Long press the sent message amd tap edit comment
9. Tap emoji picker from edit compose box

## Expected Result:
Before emoji picker box opens, a separate compose box with cursor must not be shown briefly while edit comment

## Actual Result:
Before emoji picker box opens, a separate compose box with cursor is shown briefly while edit comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/73d3db0c-d2a4-4595-a609-40a192b7df4e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01030e7a0cab136f03</li>
        <li>Upwork Job ID: 1782524877291671552</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-18 14:43
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-18 14:43
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-04-19 10:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The main composer is shown when opening the edit composer emoji picker.

### What is the root cause of that problem?
When we focus on an edit composer, the main composer will be hidden. But when the edit composer is blurred, the main composer will shown again. In this case, when we press the emoji picker button, the edit composer will be blurred.

But actually, we already prevent the main composer from showing when we press the emoji picker button as shown here.
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/home/report/ReportActionItemMessageEdit.tsx#L449-L457

The way it works is, that if the pressed element is an emoji picker button ID, then don't show the main composer yet. However, the emoji picker button element doesn't have the ID set.

We already pass the ID here,
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/home/report/ReportActionItemMessageEdit.tsx#L469

However, the pressable component accepts `nativeID` prop instead of `id`.
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/components/Pressable/GenericPressable/index.tsx#L19
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/components/Pressable/GenericPressable/index.tsx#L26

### What changes do you think we should make in order to solve the problem?

Rename the props from `id` to `nativeID` specifically in `EmojiPickerButton` (or we can rename the pressable props to `id`, but we need to rename it for many components too).

_we may need to check for messageEditInput ID too_

Note: in native, the main composer will still appear (even though covered by the modal) because it's blurred when the modal shows. To further improve it, we can ignore the blur when the emoji picker modal is active.

```
if (relatedTargetId && [messageEditInput, emojiButtonID].includes(relatedTargetId) || EmojiPickerAction.isActive(action.reportActionID)) {
    return;
}
```

But there are currently 2 issues with `EmojiPickerAction.isActive`. `EmojiPickerAction.isActive` compares the active ID and the passed ID. 
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/components/EmojiPicker/EmojiPicker.tsx#L150

The active ID is set after calculating the anchor position, but we need to set it immediately when calling `showEmojiPicker`.
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/components/EmojiPicker/EmojiPicker.tsx#L88-L100

Second, we never clear the active ID when closing the emoji picker, so we need to do that.

**Comment by puneetlath** [comment] 2024-04-22 21:40
@s77rt FYI there is already a proposal above.

**Comment by s77rt** [comment] 2024-04-23 17:56
@bernhardoj Thanks for the proposal. Your RCA is correct. This looks to be a regression from https://github.com/Expensify/App/pull/24482/commits/822efb502d1442bcbe5a7a9e3c504a90b0ca07c7. Regarding the web solution, we should use `id` since `nativeID` is deprecated. Regarding native, did you try clearing the active action? I remember we had some tricky bugs on that area and a lengthy issue https://github.com/Expensify/App/issues/23908

**Comment by bernhardoj** [comment] 2024-04-24 09:43
Yes, I tried it. The `isActive` issue of emoji picker is also mentioned in the [proposal there](https://github.com/Expensify/App/issues/23908#issuecomment-1657736680)
<img width="886" alt="image" src="https://github.com/Expensify/App/assets/50919443/28a78a69-e36c-45f3-ab6f-8061261f0173">

but instead of clearing it when other edit message is focused, we should clear it when the emoji picker hides.

_btw, the 3rd case in the linked issue happens on `main`_

**Comment by s77rt** [comment] 2024-04-24 10:39
@bernhardoj 

> but instead of clearing it when other edit message is focused, we should clear it when the emoji picker hides

That was the first attempt but didn't work well when a message is deleted from another device while the emoji picker for that message is still open. Let's test that scenario as well as other cases where `EmojiPickerAction.isActive` is used.

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/40461#issuecomment-2066267504)

**Comment by s77rt** [comment] 2024-04-29 16:33
Not overdue. @puneetlath ^

**Comment by bernhardoj** [comment] 2024-04-30 04:35
PR is ready

cc: @s77rt

**Comment by s77rt** [comment] 2024-05-23 22:49
PR was deployed to production 2 weeks ago

**Comment by puneetlath** [comment] 2024-05-27 17:29
Whoops, right you are. Can you complete the checklist @s77rt?

**Comment by puneetlath** [comment] 2024-05-27 17:30
@bernhardoj has been paid. 

@s77rt [payment](https://www.upwork.com/nx/wm/workroom/37119194/overview) just pending checklist above.

**Comment by s77rt** [comment] 2024-05-27 19:56
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/24482
- The offending PR has been commented on: https://github.com/Expensify/App/commit/822efb502d1442bcbe5a7a9e3c504a90b0ca07c7#r142442593
- A discussion in #expensify-bugs has been started: I don't feel we have much to discuss, the bug was caused by conflicts
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment] 2024-05-27 19:57
@puneetlath Done!

**Comment by puneetlath** [comment] 2024-05-27 21:08
kk all paid. Thanks everyone and sorry for the delay!

**Closed by puneetlath** 2024-05-27 21:08 UTC
Labels: Reviewing, External, Monthly, Bug
