### ISSUE TITLE
Text is overlapping in the main chat window

### ISSUE THREAD

**Issue by sakluger** [Expensify/App#25648] opened 2023-08-22 03:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Clicked on a push notification for a new message, which opened NewDot to that message

## Expected Result:

The text should be shown in chronological order of how it was sent

## Actual Result:

Some chat messages are overlapping others. When I hover over the message, it flashes.

![Overlapping text](https://github.com/Expensify/App/assets/5997400/dd4404d1-0fa2-4de4-9cc5-a1c25536c8be)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** sasha@expensify.com, jessica.dooley@team.expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

Screenshots from jessica.dooley@team.expensify.com:

![image](https://github.com/Expensify/App/assets/5997400/5edfd64e-6551-4f9b-8206-87a7eacb1bd6)

![image](https://github.com/Expensify/App/assets/5997400/40390ada-39ca-4e0f-b4b8-becd7d196afe)

![image](https://github.com/Expensify/App/assets/5997400/03775f1e-6e0d-4b2a-9146-a60958a07eb3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692664635223199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2023-08-22 06:07
Potential dupe of https://github.com/Expensify/App/issues/25616, but should still be addressed with urgency

**Comment by roryabraham** [comment] 2023-08-22 06:08
Looks like it _might_ be fixed by https://github.com/Expensify/App/pull/25613 cc @Li357

**Comment by dylanexpensify** [comment] 2023-08-22 08:40
On it now

**Comment by dylanexpensify** [comment] 2023-08-22 08:42
Unable to reproduce on staging as well @MonilBhavsar @roryabraham (also @Li357 is OOO now)

**Comment by MonilBhavsar** [comment] 2023-08-22 08:52
Thanks! I'll comment in the slack.
@spcheema looks like you were able to reproduce this issue. Do you have any specific clear steps to reproduce?

**Comment by dylanexpensify** [comment] 2023-08-22 11:55
Woof, still cannot reproduce

**Comment by MonilBhavsar** [comment] 2023-08-22 12:10
Thanks! I have been able to reproduce by sending long quoted message

```
> Hello



> Yes, lon quotes
```

**Comment by MonilBhavsar** [comment] 2023-08-22 12:24
It does seem like regression, as it is only happening on staging. I'm currently checking the list of PR's

**Comment by Li357** [comment] 2023-08-22 14:13
I think we can address this quickly. The regression is due to a styling I added for receipt scanning that had unintended effects.

**Comment by MonilBhavsar** [comment] 2023-08-22 14:24
Thank you @Li357 ! Mind linking the PR that you think caused this

**Comment by dangrous** [comment] 2023-08-22 14:37
This may be the same as https://github.com/Expensify/App/issues/25678, caused by https://github.com/Expensify/App/pull/24235#issuecomment-1688295141

**Comment by tjferriss** [comment] 2023-08-23 17:37
Applause reported a similar issue happening on iPad https://github.com/Expensify/App/issues/25478. I have also seen my text overlapping recently.

**Comment by mountiny** [comment] 2023-08-23 18:52
This is fixed in the latest staging and reported internally so closing

**Closed by mountiny** 2023-08-23 18:52 UTC
Labels: Reviewing, Engineering, Weekly, Bug
