### ISSUE TITLE
[HOLD for payment 2024-12-17] [Search v1.2] Add date-based filter for report actions

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#52262] opened 2024-11-08 15:18 UTC
Coming from the [design doc](https://docs.google.com/document/d/1G53Ebwl1XJx2ea2c0WO3rg1DmpGK8D0sMCRWvAM3D1o/edit?tab=t.0#bookmark=id.5v195qe5vwk0), the intended design is that we more broadly have date filters for report actions. In particular, this means search syntax for:

 - `submitted:`
 - `approved:`
 - `paid:`
- and `exported:`

These queries will accept dates in the YYYY-MM-DD format. 

Note: some report actions can be undone (submission, approval, payment), or can happen multiple times (approval, export). As a result, we’ll filter on the date corresponding to the last report action. In the case of approvals, it’s the last report action corresponding to final approval. 

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment] 2024-11-11 19:46
Coming from the design doc, the intended design is that we more broadly have date filters for report actions. In particular, this means search syntax for:

 - `submitted:`
 - `approved:`
 - `paid:`
- and `exported:`

These queries will accept dates in the YYYY-MM-DD format. 

Note: some report actions can be undone (submission, approval, payment), or can happen multiple times (approval, export). As a result, we’ll filter on the date corresponding to the last report action. In the case of approvals, it’s the last report action corresponding to final approval.

**Comment by luacmartins** [comment] 2024-11-21 00:12
Moving this to daily

**Comment by JmillsExpensify** [comment] 2024-11-21 22:54
P.S. Once we get these added to the front-end, the filters should look like this. We've landed on adding subtle dividers to thematically break up the information. 
![image](https://github.com/user-attachments/assets/89acf476-e429-4dbb-84ce-54702cdd3451)

Note: Feed/bank doesn't exist yet, though it's also in the works.

**Comment by JmillsExpensify** [comment] 2024-11-22 18:21
P.S. @luacmartins let's make sure that design reviews the PR. The divider should have 8px top/bottom margins.

**Comment by luacmartins** [comment] 2024-11-22 18:37
Will do

**Comment by JmillsExpensify** [comment] 2024-11-26 21:16
Still in the queue

**Comment by luacmartins** [comment] 2024-11-26 21:18
Backend PR was merged. Frontend PR is almost ready

**Comment by luacmartins** [comment] 2024-11-26 23:54
App PR in review

**Comment by JmillsExpensify** [comment] 2024-11-27 11:42
Do you want me to test an adhoc build?

**Comment by luacmartins** [comment] 2024-11-27 16:18
Sure, I'm running a build. Will post the links once ready

**Comment by luacmartins** [comment] 2024-12-10 19:30
PR in staging

**Comment by JmillsExpensify** [comment] 2024-12-20 20:14
Payment summary: $250 @dukenv0307 via New Expensify.

**Comment by JmillsExpensify** [comment] 2024-12-20 20:16
Contributor is paid through New Expensify, so given that regression test is created, I'm closing this issue.

**Closed by JmillsExpensify** 2024-12-20 20:16 UTC
Labels: Daily, Internal, NewFeature, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-12-30 11:31
Payment summary: $250 @dukenv0307 via New Expensify.

**Comment by JmillsExpensify** [comment] 2024-12-30 11:33
$250 approved for @dukenv0307
