### ISSUE TITLE
IOU - Amount & currenty of requested money not displayed in header add attendees page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23970] opened 2023-08-01 00:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should be logged in
1. Open app
2. Click on the FAB button
3. CLick on Request Money
4. Write any amount
5. Click "Next" button

## Expected Result:
Amount and currency should be displayed in header next to back button

## Actual Result:
"Cash" text displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS /  Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1680" alt="Bug6141581_Screenshot_2023-07-25_at_20 51 12" src="https://github.com/Expensify/App/assets/78819774/8d4a30e2-c7a5-4403-bc50-7adc6b6d2f25">

https://github.com/Expensify/App/assets/78819774/1c30a979-8a4c-4853-b2e7-e2c8b1a8a63c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Intetnal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-08-01 18:37
@trjExpensify Quick buddy check on this behavior as a request flow maestro - Is this expected behavior indeed correct?

**Comment by trjExpensify** [comment] 2023-08-01 21:47
This is expected now. "Cash" seems a bit strange, because we haven't yet added "Distance" or "Scan" which are in the middle of being built and will be options soon in the request money flow. 

@lanitochka17 @isagoico is there a test case that needs modifying here perhaps?

**Comment by MitchExpensify** [comment] 2023-08-02 20:03
So the "actual result", ("Cash" text displayed), behavior is expected now - Got it! Thank you. 

> @lanitochka17 @isagoico is there a test case that needs modifying here perhaps?

Yes, please let us know if so 👍

**Comment by isagoico** [comment] 2023-08-02 20:59
Updated this TC to remove this step 
- [Global Create - Request Money - Attendees page and Final review](https://expensify.testrail.io/index.php?/cases/view/1971027)
![image](https://github.com/Expensify/App/assets/44479856/37c127e8-09a2-44ec-88a7-97a130b0ea00)

Modified it so it verifies that "Cash" is displayed. 
![image](https://github.com/Expensify/App/assets/44479856/c8429898-04d8-4b5f-bde2-f1901022f372)

**Comment by MitchExpensify** [comment] 2023-08-05 12:01
Thank you @isagoico ! Closing

**Closed by MitchExpensify** 2023-08-05 12:01 UTC
Labels: Daily, Overdue, Bug
