### ISSUE TITLE
 iPhone 11 Pro Max - Autocomplete sign in email gets weird highlight style

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21638] opened 2023-06-26 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
* trigger autocomplete of email by using iOS
## Expected Result: 
input should not change
## Actual Result: 
weird 1990 old input displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari -  iPhone 11 Pro Max 
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/83691654-193e-48a6-9726-0ec92bcd83f5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dan1d
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687400154616549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment] 2023-06-30 14:13
hmmm, this issue seemingly slipped through the cracks amongst my other dailies. i will action this one today.

**Comment by maddylewis** [comment] 2023-06-30 19:19
@kavimuru - i see you added the `Needs Reproduction` label to this issue. Were you unable to reproduce this on your end?

**Comment by maddylewis** [comment] 2023-06-30 19:58
im not able to repro this on my end. and @kavimuru may not have been able to either. that said, im going to close this one out for now.

**Closed by maddylewis** 2023-06-30 19:58 UTC
Labels: Daily, Needs Reproduction, Bug
