### ISSUE TITLE
[HOLD ON #35977] [$500] [MEDIUM] `Attachment` shown in the LHN when sending a message with image

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37191] opened 2024-02-26 00:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-14
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708811957655339

## Action Performed:
1. Open any chat
2. Send a message with attachment
3. Look at the LHN as a recipient

## Expected Result:
In the LHN first line of the message should display

## Actual Result:
`Attachment` is displayed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/45c13785-4037-41d3-addd-7d17341bab4a
![image (5)](https://github.com/Expensify/App/assets/38435837/45ea255e-de0f-41b5-9e8b-af38c9d1bebd)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1ad1258cf6daa29</li>
        <li>Upwork Job ID: 1761910899454898176</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by mollfpr** [comment] 2024-02-27 09:57
@brandonhenry You can't post more than one proposal. Please update your latest solution in the first proposal, and hide the second proposal.

>Refrain from leaving additional comments until someone from the Contributor-Plus team and / or someone from Expensify provides feedback on your proposal (do not create a pull request yet).
> - Do not leave more than one proposal.
> - Do not make extensive changes to your current proposal until after it has been reviewed.
> - If you want to make an entirely new proposal or update an existing proposal, please go back and edit your original proposal, then post a new comment to the issue in this format to alert everyone that it has been updated:

Ref: https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job

---


>I can confirm that the message typed right before sending the attachment is DEFINITELY going through and should be sent to the BE.

Could you proof this? I tried to send an attachment while having drafted text in the composer, and yes both of them are sent from the `AddAttachment` API, but the response shows that the text message and the attachment are in different actions.

https://github.com/Expensify/App/assets/25520267/6b8093b5-a874-497e-ba58-d846ac78f3cd

**Comment by mollfpr** [comment] 2024-02-29 05:12
@brandonhenry You might be right that the FE already implemented the send attachment with the message, but still if the `reportActions` are created separately, then the last text shown in the LHN is from the last `reportActions`.


@dukenv0307 Your proposal seems to have the right path, but we have ongoing discussions about implementing the inline image here https://expensify.slack.com/archives/C01GTK53T8Q/p1707270017261459

@tgolen Do you mind confirming if this needs to hold for https://github.com/Expensify/App/issues/35977 or https://github.com/Expensify/App/issues/37246?

**Comment by mollfpr** [comment] 2024-03-12 12:32
I'll bring this to the Slack channel 👀

**Comment by kevinksullivan** [comment] 2024-03-15 22:10
@mollfpr did you end up bringing to slack? I don't see it in the [original thread](https://expensify.slack.com/archives/C049HHMV9SM/p1708811957655339). Can you link it here once you've done so?

**Comment by mollfpr** [comment] 2024-03-19 15:42
I'm sorry for misunderstanding the issue. Looking at the original bug report, the issue is with the message from the Concierge where they can send a text with an image in a single comment.

The feature to send text and inline images is currently under development. So it's not reproducible from user perspective.

Here's a report action example from the Concierge that sends a text with an inline image.

```
{
  "reportActionID": "4718340389065588544",
  "message": [
    {
      "type": "COMMENT",
      "html": "Thanks for your patience. I was able to find the flights you sent me. Are these flights acceptable?:<br /><br /><img src=\"https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com/uploads%2F1676906287486-1676906287485.png\" style=\"width:300px;\" class=\"fr-fic fr-dib\" alt=\"uploads%2F1676906287486-1676906287485.png\" />",
      "text": "Thanks for your patience. I was able to find the flights you sent me. Are these flights acceptable?:\n\n[Attachment]",
      "isEdited": false,
      "whisperedTo": [],
      "isDeletedParentAction": false,
      "reactions": []
    }
  ],
  "actionName": "ADDCOMMENT",
  "originalMessage": {
    "html": "Thanks for your patience. I was able to find the flights you sent me. Are these flights acceptable?:<br /><br /><img src=\"https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com/uploads%2F1676906287486-1676906287485.png\" style=\"width:300px;\" class=\"fr-fic fr-dib\" alt=\"uploads%2F1676906287486-1676906287485.png\" />",
    "lastModified": "2023-02-20 15:18:37.595"
  },
  "whisperedToAccountIDs": [],
  "created": "2023-02-20 15:18:37.595",
  "actorAccountID": 8392101,
  "person": [
    {
      "type": "TEXT",
      "style": "strong",
      "text": "Expensify Concierge"
    }
  ]
}
```

![Screenshot 2024-03-19 at 22 39 41](https://github.com/Expensify/App/assets/25520267/eedb9e00-2bb9-4163-a4be-3fd90912ec31)

---

The problem now is hard to reproduce like the screenshot from @quinthar on the bug report, because not all users get the same message from the Concierge which is a text with the inline image.

**Comment by mollfpr** [comment] 2024-03-19 16:55
@dukenv0307 Is the message have the text and inline message on 1 report action?

**Comment by mollfpr** [comment] 2024-03-19 17:11
I think that's the same as sending a text first and then the image on the second message. So the LHN is expected to show the last message `[Attachment]`.

I haven't confirmed if we have the last message of an inline image that will show the `[Attachment]`.

**Comment by kevinksullivan** [comment] 2024-03-19 21:56
Moving to VIP-VSB as this is tried to chat.

**Comment by kevinksullivan** [comment] 2024-03-19 21:57
Also agree with the proposal to hold this

**Comment by kevinksullivan** [comment] 2024-03-26 17:36
still held

**Comment by tgolen** [comment] 2024-03-26 17:55
> I think we should hold for https://github.com/Expensify/App/issues/35977, which we will display the attachment with text as only one action

I've started working on this today. When there is a message that contains both text and an attachment, what should the LHN show? I am not super opinionated about it but I think it should _probably_ show the text of the command and not bother about showing `[Attachment]`. To be clear what I am proposing:

Situation | Preview in LHN
-- | --
Text only | `Truncated text of the comm...`
Attachment only | `[Attachment]`
Text + Attachment | `Truncated text of the comm...`

Does that sound right?

**Comment by tgolen** [comment] 2024-03-27 15:29
We'll eventually have to cover those I guess, but those aren't possible right now (or with my changes in #35977). Maybe we could:

- Replace all attachments in the comment with `[File]`
- Strip out all the HTML from the comment
- Truncate the remaining text (which also might cut off `[File]` but that's probably OK)

**Comment by kevinksullivan** [comment] 2024-05-09 22:03
Taking this off hold @mollfpr

**Comment by kevinksullivan** [comment] 2024-05-09 22:03
going to test this now actually.

**Comment by mollfpr** [comment] 2024-06-13 18:06
@kevinksullivan I can't reproduce the issue in production. I think we can close this.

![Screenshot 2024-06-14 at 01 01 32](https://github.com/Expensify/App/assets/25520267/bd97cae3-52a5-4233-b1a9-093c21f655e6)
![Screenshot 2024-06-14 at 01 05 37](https://github.com/Expensify/App/assets/25520267/9e9fd7f6-c5a6-480e-b622-c83da2135065)

**Closed** 2024-07-26 15:40 UTC
Labels: External, Engineering, Monthly, Help Wanted, Overdue, Bug
