### ISSUE TITLE
[$1000] [HOLD for payment 2023-08-28] [HOLD for payment 2023-08-16] Find solution to low resolution large images on Android, and the Canvas crash 

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#18963] opened 2023-05-15 17:50 UTC
### Problem

While attempting to solve an issue with low-quality Android images, we [disabled hardware acceleration](https://expensify.slack.com/archives/C035J5C9FAP/p1684167572104089) and introduced a major performance regression. 

@terrysahaidak noticed this while running performance testing and outlined a plan for re-enabling and trying an alternative fix. 

### Solution

- Revert the PR for an immediate performance gain 
- Investigate the possibility of disabling hardware acceleration for images
- Figure our our long term solution: Either accept lower quality images, or find an alternative

_[Example big image](https://user-images.githubusercontent.com/44479856/132889916-e46ac3dc-19ad-4cca-a033-ec13b8ac79ad.jpg)_
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe4797a997c161ea</li>
        <li>Upwork Job ID: 1696867422937661440</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-05-15 18:20
cc @fabioh8010 @ArekChr

**Comment by ArekChr** [comment] 2023-05-16 07:30
Hi, I'm working on an image transform that will allow the display of large images that will allow re-enabling hardware acceleration in this [PR](https://github.com/Expensify/App/issues/17427)

**Comment by Julesssss** [comment] 2023-05-16 10:46
Awesome, look forward to this @ArekChr 👍

**Comment by Julesssss** [comment] 2023-05-16 10:48
My first step is to revert the original PR, which I'll do this afternoon after finishing higher priority work.

**Comment by Julesssss** [comment] 2023-05-16 14:46
First step was taken [here](https://github.com/Expensify/App/pull/19021): revert the PR that disabled hardware accelleration

**Comment by terrysahaidak** [comment] 2023-05-17 10:06
@ArekChr `react-native-image-pan-zoom` is built with PanResponder and is deprecated by the authors, the performance is not great and it feels very janky on android, even pinch gesture is not registered all the time for me. We had this bug #17720 we had to disable switching pages because of it. The new approach will have better performance, we will be able to implement all our own interactions with all the animations running on UI thread.


But we still need to downscale the image, because when a number of pixels is too high when you transform scale image down it can also lag a bit, because basically, we try to render too many pixels.

**Comment by ArekChr** [comment] 2023-05-17 11:03
Does the scale-down that you mention resolve that issue? How does it work with small images? The factor of scale 0.1 in the example will be calculated automatically? 

Regarding downscale, in the main branch `fast-image` have disabled transformations so it displays the original size of the image, what size of the image are you trying to display?

Maybe reverting these changes will reduce lags while transforming large images

**Comment by terrysahaidak** [comment] 2023-05-25 08:42
I tried the image zoom component I implemented with Reanimated/Gesture handler + @ArekChr Fast Image PR. In this example, i render the image as is and scale it down using `transform: [{ scale }]`

It works pretty well on low-end Samsung a12 ($150 phone):

https://github.com/Expensify/App/assets/7809008/9167aa66-5d88-4cac-aebb-648ab6d7f6e0

**Comment by mountiny** [comment] 2023-05-25 10:30
Thats great, thanks Terry!

**Comment by Julesssss** [comment] 2023-06-09 09:15
Hey @terrysahaidak, you r work looks promising. Is this something we can continue working on?

**Comment by mountiny** [comment] 2023-06-12 21:24
Arek is ooo for couple of weeks now I believe.

@terrysahaidak would you be able to provide an update, thanks!

**Comment by chrispader** [comment] 2023-06-19 14:40
Currently working on finishing @terrysahaidak 's work. Created a [draft PR here](https://github.com/Expensify/App/pull/20798)

**Comment by Julesssss** [comment] 2023-06-19 15:01
Awesome, I'll take a quick early review today.

**Comment by chrispader** [comment] 2023-06-28 12:17
@Julesssss the PR is ready for review! 🚀

**Comment by chrispader** [comment] 2023-07-22 17:55
We noticed that on very large images, the focal point and therefore the pinch gesture is not perfect yet. Gonna refine that tomorrow morning!

**Comment by Julesssss** [comment] 2023-08-01 14:13
Latest [build](https://github.com/Expensify/App/pull/20798#issuecomment-1660198697) is looking good

**Comment by Julesssss** [comment] 2023-08-07 13:30
Merged! Awaiting deployment

**Comment by jliexpensify** [comment] 2023-08-30 23:09
@ArekChr @chrispader - this wasn't a regression/no linked PR's or discussions right?

Any QA steps you'd like to recommend, so I can get a GH created?

**Comment by Julesssss** [comment] 2023-08-31 08:48
> this wasn't a regression/no linked PR's or discussions right?

@jliexpensify nah, not a regression

**Comment by jliexpensify** [comment] 2023-08-31 10:28
@Julesssss am I going crazy or did the checklist not appear in this GH?

**Comment by Julesssss** [comment] 2023-08-31 12:11
Yeah, I only see [this](https://github.com/Expensify/App/issues/18963#issuecomment-1687085023) one...

**Comment by jliexpensify** [comment] 2023-08-31 12:20
Really weird - the only other thing from the checklist (from memory) are the QA strps, if anyone wants to recommend some? I can make a GH for testrail if needed.

Otherwise, we can close this!

**Comment by jliexpensify** [comment] 2023-09-04 00:54
Bump @chrispader @ArekChr - any QA steps for me to document in a GH? Cheers.

**Comment by chrispader** [comment] 2023-09-04 13:48
I'd say the same as in [the fixing PR](https://github.com/Expensify/App/pull/20798):

**On iOS/Android:**

1. Go to a report/chat with a large attachments in it ([example image](https://user-images.githubusercontent.com/44479856/132889916-e46ac3dc-19ad-4cca-a033-ec13b8ac79ad.jpg))
2. Open an attachment image
3. Make sure the app doesn't crash
4. Make sure gestures are smooth and easy to use
5. Make sure low resolution large images are displayed correctly and zooming works.
6. Make sure other attachment types (PDF, etc.) still work

**Comment by jliexpensify** [comment] 2023-09-05 03:01
Cheers, GH created. No payment needed so closing!

**Closed by jliexpensify** 2023-09-05 03:01 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Awaiting Payment

**Comment by sobitneupane** [comment] 2023-09-05 17:56
I did review the [associated PR](https://github.com/Expensify/App/pull/20798). Requested $1000 for PR review in newDot.

cc: @jliexpensify

**Comment by jliexpensify** [comment] 2023-09-05 23:32
Just had a look and you are correct cc @Julesssss 

Payment Summary for Jason Mills:

- C+: @sobitneupane $1000 (New.Dot): reviewed PR

**Comment by JmillsExpensify** [comment] 2023-09-10 10:32
$1,000 payment approved via NewDot based on BZ summary.
