### ISSUE TITLE
Web - Can send messages by clicking around the send button, outside the composer, and when the cursor is an arrow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23863] opened 2023-07-29 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login, open any chat and type any message.
2. Go and click around the send button, ( and not the send button itself ), inside or outside the composer, when the cursor is still arrow

## Expected Result:
Users shouldn’t be able to send messages when clicking around the send button (inside or outside the composer), and when the cursor is arrow.
 He should be able to do that by clicking only on the button itself

## Actual Result:
User can send messages by clicking around the send button ( inside or outside the composer ). and when the cursor is arrow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 28-07-23 17_25_18.webm](https://github.com/Expensify/App/assets/93399543/42f6a055-3bd0-4a5a-91f3-76533c7fbfb0)

https://github.com/Expensify/App/assets/93399543/920753c8-57e3-4ff8-92df-dfbced67106c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690567101181809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-29 16:45
**Proposal by**: @Ahmed-Abdella
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690567101181809

> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Can send messages by clicking around the send button, inside or outside the composer, and while the cursor is Arrow. While the user should be able to send messages by clicking the send button itself.
>
> ### What is the root cause of that problem?
> 2 reasons cause that and they are related to the style of the Button Wrapper here
>
> https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L1235C1-L1250C1
>
> 1. This button wrapper is square and it is the area that does sending actions by clicking on it, so it should be round to match the button itself and the right round side of the composer.
> 2. After making it around we now face another issue, it is the `margin: 3` we added to the button
 > here
 https://github.com/Expensify/App/blob/main/src/styles/styles.js#L1669C1-L1677C7
> which makes the button inside the wrapper (clickable area) by 3px of margin.
> Those reasons lead to spaces (inside and outside the composer) where I can click to send messages, while they are not part of the button and the cursor is an arrow.
>### What changes do you think we should make in order to solve the problem?
 >1. To fix the first issue we should just make the wrapper round by adding this prop
 ```
wrapperStyle={{borderRadius: 99}}
```
or
```
wrapperStyle={{borderRadius: "50%"}}
```
to this
(https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L1235C1-L1250C1)
now the wrapper is round and matches the button (no clickable spaces around the corners)
>2. To fix the second issue we should remove the `margin: 3` property from `styles.chatItemSubmitButton` here
 https://github.com/Expensify/App/blob/main/src/styles/styles.js#L1669C1-L1677C7
And add the margin for the whole wrapper beside the `borderRadius` we added before
 ```
wrapperStyle={{borderRadius: 99, margin:"3px"}}
```
by doing that we add the margin between  the whole wrapper and the composer edges
NOTE:
Removing the `margin: 3` property from `styles.chatItemSubmitButton`
affect two other elements inside
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.js
the cancel button here
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.js#L279C21-L297C49
and the message edit button here
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.js#L358C29-L372C53
so we should add this prop
 ```
wrapperStyle={{ margin:"3px"}}
```
to those components to keep everything consistent.
> ### What alternative solutions did you explore? (Optional)
N/A

**Comment by rushatgabhane** [comment] 2023-07-29 17:58
not a bug imo. it's intended

**Comment by Ahmed-Abdella** [comment] 2023-07-29 18:02
@rushatgabhane  No it is not, as it is working just fine in new dot

**Comment by kbecciv** [comment] 2023-07-29 18:26
@rushatgabhane It could be related to this KI https://github.com/Expensify/App/issues/23848.

**Comment by Beamanator** [comment] 2023-07-31 11:37
I don't think this is big enough of a bug to make a deploy blocker, but should still be fixed

**Comment by Ahmed-Abdella** [comment] 2023-07-31 15:26
Here are the screenshots that expalin my proposal above (it is all in the slack conversation)

![Screenshot from 2023-07-28 17-18-06](https://github.com/Expensify/App/assets/77763699/68ec76aa-14b0-4789-89ef-c80e228b4c53)

![Screenshot from 2023-07-28 17-19-26](https://github.com/Expensify/App/assets/77763699/f118d03b-481a-4446-9a97-1eff8b249ec7)

![Screenshot from 2023-07-28 17-22-04](https://github.com/Expensify/App/assets/77763699/8185d854-547e-4ac4-96b6-f68d7fd8d1c5)

**Comment by adelekennedy** [comment] 2023-07-31 22:31
Agree this might be a dupe of https://github.com/Expensify/App/issues/23848 @AndrewGable or @rushatgabhane can I get gut check on that? In which case we should close this one as the other issues was reported first

**Comment by Ahmed-Abdella** [comment] 2023-07-31 23:08
@adelekennedy I reported my issue on Slack first, while the other issue was reported here first. It's possible that they are two distinct issues. However, what matters most is that the problem was resolved, regardless of whether you addressed mine or the other one first. Thanks.

**Comment by adelekennedy** [comment] 2023-08-02 22:16
<img width="749" alt="Screenshot 2023-08-02 at 3 11 18 PM" src="https://github.com/Expensify/App/assets/60450566/72b87059-dbe4-43c6-9b9c-3eb02f527a2a">
<img width="758" alt="Screenshot 2023-08-02 at 3 12 33 PM" src="https://github.com/Expensify/App/assets/60450566/6251122f-bf6b-4447-bb91-73d7ea4d04e4">


It looks like that other issue was reported later but made it into Slack earlier, I'll pay you the reporting bonus @Ahmed-Abdella in case we decide to close

**Comment by Ahmed-Abdella** [comment] 2023-08-02 23:43
@adelekennedy Thanks, I appreciate your concern.

**Comment by adelekennedy** [comment] 2023-08-07 18:59
I'm making the call that this is a dupe - going to close this and pay you out @Ahmed-Abdella

**Comment by adelekennedy** [comment] 2023-08-07 19:04
@Ahmed-Abdella please apply [here](https://www.upwork.com/jobs/~01748c5516ab0c24fc)!

**Comment by Ahmed-Abdella** [comment] 2023-08-07 22:32
@adelekennedy Applied, Thanks

**Comment by adelekennedy** [comment] 2023-08-07 22:34
hired!

**Comment by Ahmed-Abdella** [comment] 2023-08-07 22:38
@AndrewGable I accepted the offer

**Closed** 2023-08-07 22:39 UTC
Labels: Engineering, Daily, Bug
