### ISSUE TITLE
[HOLD for payment 2024-01-09] [HOLD for payment 2023-12-26] HIGH: [$500] Show workspace interstitial when trying to create a room with no workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27995] opened 2023-09-22 08:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com.
2. Log in as user with no workspace.
3. Go to + > Send message > Room.

## Expected Result:

When there is no workspace found, then clicking on Room will lead to the following screens:

![image](https://github.com/Expensify/App/assets/38236554/4f43b3dd-a0ed-4570-bff0-954f96012222)

## Actual Result:
User is presented with 'Hmm.. it's not here' message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.72-9

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/bf53a62e-6d06-4818-b701-9d051c2bafd1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e79d9d183706783</li>
        <li>Upwork Job ID: 1712078763933061120</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27276980</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RobertLadue</details>

**Comment by c3024** [comment] 2023-09-22 09:07
There is a bug raised for double back icons [here](https://github.com/Expensify/App/issues/27603) for this same case. We are working on this [solution](https://github.com/Expensify/App/issues/27603#issuecomment-1722309355) here in this [PR](https://github.com/Expensify/App/pull/27983). 

If there is a specific behavior we would like to show, it can be worked out in this PR.

cc: @eVoloshchak @flodnv

**Comment by situchan** [comment] 2023-09-22 09:16
I don't think this is blocker but UX improvement, though I thought not found page was intentional.
There was not such page before new global create refactor.
cc: @thienlnam

**Comment by c3024** [comment] 2023-09-22 11:53
I think the best choice is to not show the # Room option at all when there is no workspace available.

We can use the same condition that is used in `WorkspaceNewRoomPage` for showing the error in the `NewChatSelectorPage`.

We can use this
https://github.com/Expensify/App/blob/2a5ea63cfb7917c941c9153ce1051b2491a1e54b/src/pages/workspace/WorkspaceNewRoomPage.js#L122
and
https://github.com/Expensify/App/blob/2a5ea63cfb7917c941c9153ce1051b2491a1e54b/src/pages/workspace/WorkspaceNewRoomPage.js#L147
in `NewChatSelectorPage`and use this same condition to hide the # Room when there is no workspace available.

We can make a function getWorkspaceOptions in PolicyUtils to make the code DRY and reuse in both the pages.

https://github.com/Expensify/App/assets/102477862/61b01483-9284-484a-b05e-34c318c283c6

cc @thienlnam

**Comment by thienlnam** [comment] 2023-09-22 13:09
Yeah agreed, I'm going to go ahead and remove the blocker label for now

**Comment by situchan** [comment] 2023-09-22 15:07
Another option is to show tutor screen similar to empty workspace.

<img width="373" alt="Screenshot 2023-09-22 at 9 05 53 PM" src="https://github.com/Expensify/App/assets/108292595/cb160c62-7abc-4b9c-9317-f5fa3fb333c4">

**Comment by shawnborton** [comment] 2023-09-25 03:25
Interesting, curious for what @JmillsExpensify @trjExpensify @kevinksullivan @MitchExpensify think about this one. 

If you have no workspace, should you be able to create a room? Did we cover this case in the Simplify Global Create project? 

Maybe we need to bring this to Slack for more discussion.

**Comment by MitchExpensify** [comment] 2023-09-25 03:28
> If you have no workspace, should you be able to create a room? 

No, I don't think you should be able to seeing as rooms need to be tied to a workspace.

**Comment by thienlnam** [comment] 2023-09-25 03:31
<img width="367" alt="Screenshot 2023-09-25 at 11 31 31 AM" src="https://github.com/Expensify/App/assets/30609178/05f6fd2a-3bc8-4689-b610-fe736d6522f8">

Yeah, perhaps we just hide the #room tab if you aren't part of any workspace?

**Comment by MitchExpensify** [comment] 2023-09-25 03:41
Or direct them to create a workspace there

**Comment by trjExpensify** [comment] 2023-09-25 03:53
We haven't really talked a bunch about "upgrade" paths lately, but the `#room` tab being locked with a page on how to unlock rooms by creating a workspace would be pretty good, I think.

**Comment by bfitzexpensify** [comment] 2023-09-26 09:41
>We haven't really talked a bunch about "upgrade" paths lately, but the #room tab being locked with a page on how to unlock rooms by creating a workspace would be pretty good, I think.

This sounds like a solid approach to me - thoughts on that @shawnborton?

**Comment by kevinksullivan** [comment] 2023-09-27 04:19
yeah, I like the idea of promoting the creation a workspace on this page when someone doesn't have one. Was chatting with @shawnborton about the CTA redirecting to the empty state of the workspaces page as well.

**Comment by bfitzexpensify** [comment] 2023-10-06 18:48
OK, so it sounds like this is the preferred solution:

When you don't have a workspace, then clicking **Send Message** should open the following pane, with the default selection being **Chat** rather than **Room**, and a lock or something similar on the **Room** tab. 

![image](https://github.com/Expensify/App/assets/38236554/144348c7-3ea4-441f-93cd-8fd889ccd268)


When you click on **Room**, it takes you to a page that describes what a Room is, with a CTA to open a Workspace to enable that functionality. 

How does that sound @trjExpensify @MitchExpensify @shawnborton @kevinksullivan @thienlnam @techievivek?

**Comment by MitchExpensify** [comment] 2023-10-06 20:27
I think Send Message should open on "Chat" be default, not rooms

**Comment by dubielzyk-expensify** [comment] 2023-10-09 01:03
Just throwing in my 2 cents here: I like the idea of educating the user on what rooms are, but also pointing them to a workspace which needs to be created for rooms to be available (similar to what others have already mentioned).

Instead of locking or showing the same UI perhaps we could go with a simple empty state which explains rooms and why it's not available, then points them to create a workspace.

![image](https://github.com/Expensify/App/assets/145416827/fac779b1-7b97-4cc1-b612-ce7da4d46732)

**Comment by techievivek** [comment] 2023-10-09 03:53
>  I like the idea of educating the user on what rooms are, but also pointing them to a workspace which needs to be created for rooms to be available

💯 
I like what @dubielzyk-expensify has shared, but will wait for others to chime in.

**Comment by shawnborton** [comment] 2023-10-09 13:00
Oh, I like that a lot @dubielzyk-expensify! Maybe the button on the left should say "Learn more" since it brings you to a page to learn more and then create the workspace from there? Also, I could see the button on the left being green (success) as well.

**Comment by trjExpensify** [comment] 2023-10-09 18:29
Yeah, I agree with that. If there's a `Create workspace` button, I'd expect it to create one when I click it, so `Learn more` sounds good.

**Comment by dubielzyk-expensify** [comment] 2023-10-10 02:05
![image](https://github.com/Expensify/App/assets/145416827/1adeef79-7905-4357-979d-2465e4336d53)

**Comment by techievivek** [comment] 2023-10-16 10:46
@hoangzinh, thanks, going to update the GH. 👍

**Comment by techievivek** [comment] 2023-10-16 10:47
Look like @bfitzexpensify already updated it. 🙇

**Comment by RobertLadue** [comment] 2023-10-27 11:31
Where is the copy below being used because in the screenshot I saw earlier it had different copy. Just trying to make sure I understand where and when it would be displayed?

> No workspace found in English
> and No se encontró ningún espacio de trabajo in Spanish.
> Rooms are a great place to discuss and work with multiple people. To message a room, create or join a workspace in English
> and Las salas son un gran lugar para discutir y trabajar con varias personas. Para enviar mensajes a una sala, crear o unirse a un espacio de trabajo in Spanish.

Is it replacing the copy below?

![image](https://github.com/Expensify/App/assets/12521433/232dda71-19dc-4740-bba1-8072e29165ac)

**Comment by RobertLadue** [comment] 2023-11-13 19:52
I'll hop in later today, sorry for the wait everyone!

**Comment by RobertLadue** [comment] 2023-11-29 15:14
> Rooms are a great place to discuss and work with multiple people. To begin collaborating, create a room or join a workspace.

How does everyone feel about this copy? Sorry for the wait, I didn't get to this before I went OOO and then traveled again immediately after OOO for work.

**Comment by RobertLadue** [comment] 2023-12-05 03:56
>Rooms are a great place to discuss and work with multiple people. To begin collaborating, create or join a workspace.

Yeah this should be the copy, my bad!

**Comment by quinthar** [comment] 2023-12-05 12:03
@dukenv0307 can you give an ETA for when you think you'll have submitted the PR?  Thanks!

**Comment by RobertLadue** [comment] 2023-12-07 17:17
That looks right to me based on google translate, but not sure if there are any local nuances with the translation that make it formal or less formal...

**Comment by RobertLadue** [comment] 2023-12-07 17:18
Are there any other translations needed and what's stopping us from merging this at the moment?

**Comment by quinthar** [comment] 2023-12-13 01:25
Bump, what are the next steps here?  It's been idle for 5 days

**Comment by quinthar** [comment] 2023-12-13 21:27
@dukenv0307 what is the ETA for fixing?

**Comment by bfitzexpensify** [comment] 2023-12-14 00:55
cc @techievivek on the PR review

**Comment by bfitzexpensify** [comment] 2023-12-15 15:34
Deployed to staging yesterday

**Comment by shawnborton** [comment] 2023-12-18 13:35
Looks like the incorrect illustration was used for this, I left a comment in the PR. So let's make sure we get that fixed before paying anything out.

**Comment by dubielzyk-expensify** [comment] 2023-12-19 03:40
Would be good to make it part of the same PR. Here's the illustration:

[telescope.svg.zip](https://github.com/Expensify/App/files/13710872/telescope.svg.zip)

**Comment by shawnborton** [comment] 2023-12-19 13:56
Thanks Jon!

**Comment by RobertLadue** [comment] 2023-12-20 04:32
Going to unassign myself since I was just here to review copy!

**Comment by bfitzexpensify** [comment] 2024-01-11 15:23
Payment made to @hoangzinh, offer sent to @dukenv0307, regression steps proposed in https://github.com/Expensify/App/issues/27995#issuecomment-1873620708

**Comment by bfitzexpensify** [comment] 2024-01-11 22:30
I'm mostly ooo until Jan 29 so tagging in another BZ team member to close this out. 

@mallenexpensify the only item left is to complete payment to @dukenv0307 via https://www.upwork.com/ab/applicants/1745464644211769344/job-details. 

@dukenv0307, please comment in this issue when you've accepted that offer.

**Comment by bfitzexpensify** [comment] 2024-01-18 23:52
Payment complete.

**Closed by bfitzexpensify** 2024-01-18 23:52 UTC
Labels: External, Engineering, Daily, NewFeature, Overdue, Waiting for copy, Awaiting Payment, Bug
