### ISSUE TITLE
[$250] Reimburse expenses - Error appears after changing Rate and Unit

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12542] opened 2022-11-08 01:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot app
2. Go to the WS settings -> Reimburse expenses
3. Change both fields: Rate and Unit

## Expected Result:
The user should be able to change Rate and Unit fields in Reimburse expenses without any issues

## Actual Result:
 Error appears after changing Rate and Unit

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Desktop App

**Version Number:** 1.2.24.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200449825-cb7b455b-062d-4032-bd3f-6deada3d3b06.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-11-08 10:17
<img width="1680" alt="Screen Shot 2022-11-08 at 17 06 03" src="https://user-images.githubusercontent.com/16502320/200537707-78da3e2d-861e-4f36-a20d-2e21c0b75d3e.png">

More informations for anyone who want to fix this, this error will happen when you tried to change the dropdown immediately 
right after you change the  Rate. Seems we need to call API synchronous here.
I think we can add a `Save` button below the Rate and Unit field and call the API synchronous when we press the `Save` button.

**Comment by bfitzexpensify** [comment] 2022-11-10 14:43
Upwork job [here](https://www.upwork.com/jobs/~0121202609b7f260c8)

**Comment by Delgee** [comment] 2022-11-10 17:36
### Proposal
### Root cause
This issue is a race condition that happens when you change the unit before the rate change response is returned.
It should not be an issue in normal cases since the server will respond before human input. But there is a debouncer with 1 second added to the "rate" Input so it gives the "unit change" selectbox 1 second of a headstart.
### Solution 1
Just add another debouncer to the "unit change"selectbox" so it won't have 1 second of a headstart. A timeout can also work.

```diff
diff --git a/src/pages/workspace/reimburse/WorkspaceReimburseView.js b/src/pages/workspace/reimburse/WorkspaceReimburseView.js
index f077583fa..1f75a67ea 100644
--- a/src/pages/workspace/reimburse/WorkspaceReimburseView.js
+++ b/src/pages/workspace/reimburse/WorkspaceReimburseView.js
@@ -83,6 +83,8 @@ class WorkspaceReimburseView extends React.Component {

         this.debounceUpdateOnCursorMove = this.debounceUpdateOnCursorMove.bind(this);
         this.updateRateValueDebounced = _.debounce(this.updateRateValue.bind(this), 1000);
+        this.updateUnitValueDebounced = _.debounce(this.updateUnitValue.bind(this), 1000);
+
         this.updatedValue = this.state.unitRateValue;
     }

@@ -96,15 +98,30 @@ class WorkspaceReimburseView extends React.Component {
                 .values()
                 .findWhere({name: CONST.CUSTOM_UNITS.NAME_DISTANCE})
                 .value();
+
+            const prevDistanceCustomUnit = _.chain(lodashGet(prevProps, 'policy.customUnits', []))
+                .values()
+                .findWhere({name: CONST.CUSTOM_UNITS.NAME_DISTANCE})
+                .value();
+
+            const prevUnitValue = lodashGet(prevDistanceCustomUnit, 'attributes.unit', 'mi');
+            const unitValue = lodashGet(distanceCustomUnit, 'attributes.unit', 'mi');
+
             const customUnitRate = _.find(lodashGet(distanceCustomUnit, 'rates', {}), rate => rate.name === 'Default Rate');
-            this.setState({
+            const prevCustomUnitRate = _.find(lodashGet(prevDistanceCustomUnit, 'rates', {}), rate => rate.name === 'Default Rate');
+
+            const prevUnitRateValue = this.getUnitRateValue(prevCustomUnitRate);
+            const unitRateValue = this.getUnitRateValue(customUnitRate);
+
+            this.setState(state => ({
                 unitID: lodashGet(distanceCustomUnit, 'customUnitID', ''),
                 unitName: lodashGet(distanceCustomUnit, 'name', ''),
-                unitValue: lodashGet(distanceCustomUnit, 'attributes.unit', 'mi'),
+                unitValue: prevUnitValue !== unitValue ? unitValue : state.unitValue,
                 unitRateID: lodashGet(customUnitRate, 'customUnitRateID'),
-                unitRateValue: this.getUnitRateValue(customUnitRate),
-            });
-            this.updatedValue = this.getUnitRateValue(customUnitRate);
+                unitRateValue: prevUnitRateValue !== unitRateValue ? unitRateValue : state.unitRateValue,
+            }));
+
+            this.updatedValue = prevUnitRateValue !== unitRateValue ? unitRateValue : this.updatedValue;
         }

         const reconnecting = prevProps.network.isOffline && !this.props.network.isOffline;
@@ -157,6 +174,12 @@ class WorkspaceReimburseView extends React.Component {
             return;
         }
+        this.setState({unitValue: value}, () => {
+            this.updateUnitValueDebounced(value);
+        });
+    }
+
+    updateUnitValue(value) {
         const distanceCustomUnit = _.find(lodashGet(this.props, 'policy.customUnits', {}), unit => unit.name === 'Distance');
         if (!distanceCustomUnit) {
             Log.warn('Policy has no customUnits, returning early.', {
```


https://user-images.githubusercontent.com/6459339/201166821-301667d5-5135-42e6-aebb-bc7bb67d98bc.mov



### Solution 2
Making denounced function into a single function that can do both changes.

**Comment by parasharrajat** [comment] 2022-11-11 20:25
I dunno what's causing this bug. Let me do some digging first.

**Comment by bfitzexpensify** [comment] 2022-11-14 12:33
Not overdue, looks like @parasharrajat is digging into the cause

**Comment by mvtglobally** [comment] 2022-11-16 02:25
Issue not reproducible during KI retests. (First week)

**Comment by Andruso** [comment] 2022-11-16 16:35
@mvtglobally It's still reproducible in live and dev - you need to change the unit very fast ( <1sec) after last change to the rate. Additionally, it's easier to reproduce on Firefox which seems slower: [Loom](https://www.loom.com/share/f5cfd80cfe7e4fb08c37e1bc7c175e2f)

**Comment by Andruso** [comment] 2022-11-16 17:11
@parasharrajat I agree with the root cause given by @Delgee [above](https://github.com/Expensify/App/issues/12542#issuecomment-1310652966):

> This issue is a race condition that happens when you change the unit before the rate change response is returned.
It should not be an issue in normal cases since the server will respond before human input. But there is a debouncer with 1 second added to the "rate" Input so it gives the "unit change" selectbox 1 second of a headstart.

Also I think that the most simple fix would be to save both values together as @Delgee proposed:
> Making debounced function into a single function that can do both changes.

I'd additionally [remove debounce and save onBlur](https://github.com/Expensify/App/issues/12542#issuecomment-1310720748) to make it more robust and user-friendly but that might be a separate ticket, if necessary.

@Delgee would you still be interested in solving this (as your proposal came first)? If not, then I could do it myself.

**Comment by Delgee** [comment] 2022-11-16 17:36
Yes, I'm still interested in solving this issue.

**Comment by parasharrajat** [comment] 2022-11-16 17:51
This one is an interesting issue. I don't have much knowledge of the backend. 

A possible solution might be to debounce the Unit Api request so that there is some gap between both requests. 

Another solution might be to combine the requests. The second one looks good but requires backend changes.

Both of them are mentioned in https://github.com/Expensify/App/issues/12542#issuecomment-1310652966. 

@marcaaron What do you think?

**Comment by marcaaron** [comment] 2022-11-16 18:46
Before diving into the race condition conversation... I'm a little confused about this feature and how it got implemented like this in the first place and why it was not implemented using our [form guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md).

Why are we using a debounce on this input to save the rate when every other form in our app does not work this way...

Based on [this issue](https://github.com/Expensify/App/issues/6213) tagging in @trjExpensify and @deetergp to add some context before continuing.

**Comment by trjExpensify** [comment] 2022-11-16 18:58
Did we have the form guidelines back in Nov 2021 a year ago? Either way, [this is a dupe](https://github.com/Expensify/App/issues/12451) of this `internal` issue that @jasperhuangg is working on after the API refactors, isn't it?

**Comment by marcaaron** [comment] 2022-11-16 20:57
>Did we have the form guidelines back in Nov 2021 a year ago?

Who can remember such things? :trollface: 

>Either way, https://github.com/Expensify/App/issues/12451 of this internal issue that @jasperhuangg is working on after the API refactors, isn't it?

Looks like it. Thanks! Closing.

**Closed by marcaaron** 2022-11-16 20:57 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
