### ISSUE TITLE
[$500] Room - Split bill option does not show up after inviting member until the room is revisited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32375] opened 2023-12-01 21:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click + > Start chat > Room
3. Create a workspace room
4. Invite a member by mentioning the user name
5. Click +
6. Go to another chat
7. Return to the workspace room
8. Click +

## Expected Result:
In Step 5, split bill option will show up after inviting the user

## Actual Result:
In Step 5, split bill option does not show up after inviting the user
The option only shows up after revisiting the room in Step 7

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/21eac31d-3bf3-4cee-9a78-0acde2fc3590

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed1f83038ca012a0</li>
        <li>Upwork Job ID: 1730697215761219584</li>
        <li>Last Price Increase: 2023-12-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28064288</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-01 21:41
This is a BE issue: the Pusher does not update `participantAccountIDs` of the room report when sending the "invited ..." message.

**Comment by jliexpensify** [comment] 2023-12-04 02:52
@rushatgabhane if you could confirm if this is a back-end issue, I'll assign it as `Internal` - thanks!

**Comment by jliexpensify** [comment] 2023-12-07 23:36
Bump @rushatgabhane for this [comment](https://github.com/Expensify/App/issues/32375#issuecomment-1837757502)

**Comment by jliexpensify** [comment] 2023-12-13 02:00
Messaged @rushatgabhane on Slack

**Comment by rushatgabhane** [comment] 2023-12-13 03:30
> What is the root cause of that problem?
We're not inviting the members to the room optimistically when they are invited via mentions.

Agree agree!

C+reviewed 🎀 👀 🎀

**Comment by jliexpensify** [comment] 2023-12-14 22:59
Note to self: this will be part of #vip-split-p2p-chat-groups

Also bump @srikarparsi for a review, thanks!

**Comment by jliexpensify** [comment] 2023-12-17 23:44
Waiting on Srikar!

**Comment by srikarparsi** [comment] 2023-12-18 06:06
lgtm to as well :)

**Comment by GabiHExpensify** [comment] 2024-01-06 00:28
bump @rushatgabhane, it sounds like the PR is waiting on your review -- anything the rest of us can do to help move this forward?

**Comment by jliexpensify** [comment] 2024-01-12 02:01
Not overdue, PR is being reviewed!

**Comment by GabiHExpensify** [comment] 2024-01-13 02:19
This PR has been in review for a month, what can we do to help move it along?

**Comment by jliexpensify** [comment] 2024-01-14 23:07
Bump @rushatgabhane - it looks like you were going to review the PR 3 days ago, has that happened yet?

**Comment by rushatgabhane** [comment] 2024-01-17 05:26
I wanna take a step back and discuss the solution.

@dukenv0307 @srikarparsi I don't think [parsing html to get a list of mentions](https://github.com/Expensify/App/pull/33274#discussion_r1436518354) in a message is a good idea because it is a hack and will cause bugs in future when html of a mention changes. 

If we want a list of mentions in a message, I think that we should maintain that list when the user is typing new mentions.

Is there a better way to do this?

**Comment by srikarparsi** [comment] 2024-01-18 08:12
I also agree, I don't think parsing html is a great idea, but I can't really find a better way to do this. I'll ask if anyone who has worked on mentions has any ideas.

**Comment by youssef-lr** [comment] 2024-01-18 09:30
I'm not able to reproduce this issue anymore, can you guys confirm?

https://github.com/Expensify/App/assets/9680864/706b36d2-fc5f-4763-bf1f-a2f281c1979e

**Comment by srikarparsi** [comment] 2024-01-19 05:32
Cool, thanks @youssef-lr! Are we all good to close this out @jliexpensify @rushatgabhane?

**Comment by rushatgabhane** [comment] 2024-01-19 05:42
perfect! we can close this

**Comment by jliexpensify** [comment] 2024-01-21 21:36
Happy to close, a PR was made but wasn't deployed correct? So there shouldn't be any payments. 

I will also remove the Upworks job. Please comment/re-open if you disagree!

**Closed** 2024-01-21 21:37 UTC
Labels: Reviewing, External, Monthly, Bug
