### ISSUE TITLE
Web - The whole quote container is not clickable to the link 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23432] opened 2023-07-23 18:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot
2. Log in with any account
3. Select any user
4. Send the GH link (https://github.com/Expensify/App/issues)

## Expected Result:
The whole quote container should be clickable to the link 

## Actual Result:
The whole quote container is not clickable to the link 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 11 03 09 AM](https://github.com/Expensify/App/assets/93399543/6ea7b7da-6a4a-439f-8175-09b376560ae3)

https://github.com/Expensify/App/assets/93399543/e4339b62-ff16-471c-bea1-cbdf92f9a243

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689951815045029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-07-23 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we click on the container of a Link preview, nothing happens

### What is the root cause of that problem?

In LinkPreviewer component the only thing that catch clicks is the TextLink here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/home/report/LinkPreviewer.js#L108-L114



### What changes do you think we should make in order to solve the problem?

If we want to catch clicks on the whole link preview we need to add a Pressable, for example PressableWithoutFeedback and onClick we need to open the link for example using Linking.openUrl. The code looks like this:

```
return (
    linkData && (
        <PressableWithoutFeedback
            onPress={() => {
                Linking.openURL(url);
            }}
           >
        <View
```

There are more props in PressableWithoutFeedback like accessibiity label but we can find them during the PR

Result:

https://github.com/Expensify/App/assets/19537677/a6ec96b7-2721-494f-8402-e70af66e387e


### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment] 2023-07-24 06:28
Relevant issue https://github.com/Expensify/App/issues/22979

**Comment by shawnborton** [comment] 2023-07-24 11:42
I'm curious why the whole container should be clickable? Is that actually expected behavior? Slack doesn't do this, for instance. cc @marcaaron

**Comment by MitchExpensify** [comment] 2023-07-24 19:17
> I'm curious why the whole container should be clickable? Is that actually expected behavior? Slack doesn't do this, for instance. cc @marcaaron

+1, in the related issue https://github.com/Expensify/App/issues/22979#issuecomment-1642077697 (Thanks @eh2077 !) we're actually running with the expected behavior that only the link itself, versus the entire preview, should be clickable. 

I'm going to close this out as this is a dupe of that issue

**Closed by MitchExpensify** 2023-07-24 19:17 UTC
Labels: Daily, NewFeature, Bug
