### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500] Workspace - Title with /Chats and /Settings is not aligned properly with minimum font size

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35785] opened 2024-02-04 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Kill the app if it is in the background
2. Change device font size to the minimum
3. Relaunch New Expensify app
4. Note that "/ Chats" is not on the same line as Expensify logo
5. Tap Settings from the bottom
6. Note that "/ Settings" is not on the same line as Expensify logo
7. Select a workspace
8. Note that "Workspace / Settings" is aligned to the top (higher than usual)

## Expected Result:
In Step 4, 6 and 8, when device font size is the minimum, the Expensify title will align accordingly

## Actual Result:
In Step 4 and 6, "/ Chats" and "/Settings" are not on the same line as Expensify logo when device font size is minimum
In Step 8, "Workspace / Settings" is aligned to the top (higher than usual)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/88fc6cbe-56a4-4948-91bb-8d5dcce8c201

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016dcd74798af67988</li>
        <li>Upwork Job ID: 1754910426505916416</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment] 2024-02-04 18:10
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by mountiny** [comment] 2024-02-05 14:37
Not a blocker, adding Design label to help us align on how this should behave as the system font sizes change.

**Comment by shawnborton** [comment] 2024-02-05 15:09
oh boy, cc @Expensify/design on this one... I don't have a great answer, other than... what if we just made it so that this part of the app didn't change if system font settings changed?

Or in the very least, we should be making sure that everything maintains perfect vertical center alignment.

**Comment by dannymcclain** [comment] 2024-02-05 16:16
Hmmmm yeah this is tricky. Seems like everything works as expected for non-Expensify workspaces right? Everything just scales down together?

Is there any possible way we could also scale down the wordmark in the same way? (This might be an absolutely nutty idea, just tossing it out there.)

> what if we just made it so that this part of the app didn't change if system font settings changed?

I don't love the idea of of specifically and directly not supporting a user's choice. There's got to be another way. I just don't know if I have any good ideas for it right now.

> we should be making sure that everything maintains perfect vertical center alignment.

This might be our best bet unless we can get that wordmark to scale along with the text. The titles won't sit on the same baseline anymore but at least they'd be vertically centered?

**Comment by shawnborton** [comment] 2024-02-05 17:14
> This might be our best bet unless we can get that wordmark to scale along with the text. The titles won't sit on the same baseline anymore but at least they'd be vertically centered?

Yeah, in the very least, let's just make sure the non-filtered view has the vertically centered alignment? As you mentioned, seems like that's the only one that has the very obvious bug here.

**Comment by dubielzyk-expensify** [comment] 2024-02-05 23:45
Yeah, I agree that we need to scale it after user preference.

I wonder if we can scale like an image rather than text. So `Expensify/Workspace name` is treated as one element that we apply `scale` to rather than font-size?

**Comment by shawnborton** [comment] 2024-02-06 01:24
Oh that's an interesting approach... Def would be curious to see a solution like that.

**Comment by mountiny** [comment] 2024-02-06 16:50
Sounds like we agree this should scale with the user preference but keep the correct alignment, making it external.

**Comment by mountiny** [comment] 2024-02-09 17:44
@dukenv0307 can you please raise a PR?

**Comment by shawnborton** [comment] 2024-02-12 13:44
Not overdue, waiting for PR here.

**Comment by mountiny** [comment] 2024-03-12 23:07
Was merged

**Comment by sonialiap** [comment] 2024-03-13 11:28
@mountiny since the PR has been merged, is it now waiting for the regression hold and payment or is this issue still in progress? Did automation skip the issue 🕵️ If it's on the payment stage then I'll update the labels/title

**Comment by sonialiap** [comment] 2024-03-20 11:52
Original upwork job expired so I created a new one and sent out offers

@Ollyws Reviewer $500 - offer sent - [please complete the checklist](https://github.com/Expensify/App/issues/35785#issuecomment-1995517598)
@dukenv0307 Contributor $500 - offer sent

**Comment by sonialiap** [comment] 2024-03-21 11:36
Thanks Olly :)

Both payments made

**Closed** 2024-03-21 11:37 UTC
Labels: External, Engineering, Daily, Design, Awaiting Payment, Bug
