### ISSUE TITLE
[HOLD awaiting refund from overpayment] [$500] Details - Workspace split bill displays user name instead of workspace name to admin

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29219] opened 2023-10-10 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696924602489199

## Action Performed:
1. Open the app and login with user A
2. Open the app using any other device and login with user B
3. From user A, add user B as member in any of user A workspaces
4. From user A, open workspace chat created newly after step 3
5. From user B, click on green plus button situated in LHN of app
6. From user B, click on request money->manual
7. Type in any amount and click Next
8. In the user list, click on split besides workspace report name used in step 3 and finish the request money process
9. From user A, click on split bill message and observe that in details, instead of workspace name it displays username

## Expected Result:
App should display workspace name besides workspace avatar in split bill details page

## Actual Result:
App displays username name besides workspace avatar to admin user in split bill details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/109ac380-2168-412f-b2d6-24bc510f2cb5

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/93399543/23865910-c6d9-4c27-b8a4-ddef36dad5bf

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/e8dab79e-5876-4dc1-be9c-ea58d3e36b27

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/bfaf7c8e-382e-4867-85c6-97445915c884

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/d0cc59a5-e424-4806-b628-7fad05f09375

https://github.com/Expensify/App/assets/93399543/70325180-94e7-436a-b61a-a56049250476

https://github.com/Expensify/App/assets/93399543/206be0b8-9260-4f53-9c87-75ec7c598b40

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/9dfd1f84-6237-46e9-8e08-c634238ed819

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f60ccd423ab1d2e</li>
        <li>Upwork Job ID: 1711802547356061696</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27154595</li>
<li>akamefi202 | Contributor | 27154596</li>
<li>dhanashree-sawant | Reporter | 27154598</li>
</ul></li>
    </ul>
</details>

**Comment by akamefi202** [comment] 2023-10-10 21:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace split bill displays user name instead of workspace name in split details.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b5445bd0da78132d602b2f3de36a19b1cf495fce/src/libs/OptionsListUtils.js#L99-L102

The app gets the information to display inside `getPolicyExpenseReportOption` function.
And inside it, the app calls `getReportName` function to get name.

https://github.com/Expensify/App/blob/b5445bd0da78132d602b2f3de36a19b1cf495fce/src/libs/ReportUtils.js#L1798-L1800

Inside `getReportName` function, it calls `getPolicyExpenseChatName` function to get the name of workspace.

https://github.com/Expensify/App/blob/b5445bd0da78132d602b2f3de36a19b1cf495fce/src/libs/ReportUtils.js#L1308-L1310

But the `getPolicyExpenseChatName` function returns workspace name only if policy is owned by the user.
If not, it returns the name of owner.

As a result, we see user name of user B instead of workspace name if we check split details as user A.
Because the policy is owned by user B.

### What changes do you think we should make in order to solve the problem?
We should call `getPolicyName` directly function inside `getPolicyExpenseReportOption` function.
Because we're meant to get workspace name inside `getPolicyExpenseReportOption` function.

```
const workspaceName = ReportUtils.getPolicyName(expenseReport);
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mallenexpensify** [comment] 2023-10-11 02:41
@s77rt can you please review @akamefi202 's proposal? Thx

**Comment by s77rt** [comment] 2023-10-11 13:21
@akamefi202 Thanks for the proposal. Your RCA is correct and the solution looks good to me 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/29219#issuecomment-1756257496)

**Comment by mallenexpensify** [comment] 2023-10-12 01:37
@lakchote 👀 please on the proposal above when ya have a min

**Comment by lakchote** [comment] 2023-10-12 05:24
@akamefi202 proposal LGTM.

**Comment by akamefi202** [comment] 2023-10-12 05:35
I accepted the offer and PR will be ready by today.

**Comment by s77rt** [comment] 2023-10-16 23:55
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/17132
- The offending PR has been commented on: https://github.com/Expensify/App/pull/17132#discussion_r1361368629
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by mallenexpensify** [comment] 2023-10-17 21:43
@s77rt what's your reasoning for not wanting a regression test for this?

**Comment by s77rt** [comment] 2023-10-18 02:37
@mallenexpensify Due to the nature of the bug I don't think it would resurface again where a regression test would be needed. Do you think we would be better with a test for this case?

**Comment by Christinadobrzyn** [comment] 2023-10-18 19:14
Hey @mallenexpensify - there was an accidental [overpayment](https://github.com/Expensify/App/issues/26214#issuecomment-1758645358) to @akamefi202 on this job (payment was $1000 but there were some regressions so the actual payment should have been $250). 

Is it possible to adjust the payment from this one? cc @akamefi202

**Comment by s77rt** [comment] 2023-10-18 22:44
@Christinadobrzyn I think @akamefi202 can issue a refund for that past payment

**Comment by mallenexpensify** [comment] 2023-10-18 23:32
@Christinadobrzyn , I'd recommend requesting a refund on that job then, once it's confirmed, I can pay this one out.   Assuming we do that, _we_ should also update the title to reflect to hold (so I don't forget)

**Comment by akamefi202** [comment] 2023-10-23 16:41
@mallenexpensify @s77rt Could you please finish this issue if you have any time?

**Comment by Christinadobrzyn** [comment] 2023-10-23 17:05
Ah okay, thanks @mallenexpensify I do see the option to request a refund on this [job](https://github.com/Expensify/App/issues/26214#issuecomment-1758542357) so I did that. Just a heads up @akamefi202 I requested a partial refund for this [job](https://github.com/Expensify/App/issues/26214#issuecomment-1775636056) through Upwork.

**Comment by akamefi202** [comment] 2023-10-23 18:36
@mallenexpensify Could you please pay here first? That $1000 payment was more than 3 weeks ago so that I don't have enough money for refund in Upwork now. I promise that I will do refund.

**Comment by mallenexpensify** [comment] 2023-10-24 23:19
Oooof, that is a tricky situation @akamefi202.  I just paid this 

Issue reporter: @@dhanashree-sawant paid $50 via Upwork
Contributor: @akamefi202 paid $750 via Upwork. Please _accept_/pay the refund [for the other job](https://github.com/Expensify/App/issues/26214#issuecomment-1758542357)
Contributor+: @s77rt paid $750 via Upwork.  

@s77rt I wasn't sure about the regression test so I created on, Applause/QA will _do something_ with it if they think it'd be helpful
https://github.com/Expensify/Expensify/issues/329593

Gonna leave this open and a weekly til I'm able to confirm @akamefi202 's refund for the other issue.

**Comment by mallenexpensify** [comment] 2023-11-03 23:37
Awaiting refund on other issue
https://github.com/Expensify/App/issues/26214#issuecomment-1793242306

**Comment by akamefi202** [comment] 2023-11-06 06:32
@mallenexpensify Sorry for late reply. I was OOO last week. I made the refund and I think we might close this issue now.

**Comment by mallenexpensify** [comment] 2023-11-06 20:30
Thanks @akamefi202 , confirm refund was issued for #26214

**Closed by mallenexpensify** 2023-11-06 20:30 UTC
Labels: External, Weekly, Awaiting Payment, Bug
