### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Search - RHP closes or returns to transaction thread depending on which field is edited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43958] opened 2024-06-18 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4641773
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Enable all the features in the workspace so that all possible fields are present in transaction thread
- Billable option is enabled on Old Dot
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Go to Search
5. Open the transaction from Step 3
6. Edit all the fields (Amount, description, merchant, category, tag, tax rate, tax amount, billable toggle)

## Expected Result:
After editing the fields, there should be consistency whether the RHP should close and return to previous page. The RHP should not close after editing any field 

## Actual Result:
After editing Amount, Tag and Billable field, RHP closes.
While for the rest of the fields, RHP returns to transaction thread after editing the fields

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0ef8de32-2858-4270-8aa1-5b3552a68880

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d87627b980e14f86</li>
        <li>Upwork Job ID: 1803575274326292159</li>
        <li>Last Price Increase: 2024-06-19</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102865693</li>
<li>Krishna2323 | Contributor | 102865694</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment] 2024-06-18 20:54
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment] 2024-06-19 23:47
I agree this is weird; the RHP should not close after editing any field IMO. If we close the RHP we're assuming the user is finished editing that expense which may not be the case. We should drop them back in the view they were previously on which is the RHP open.

**Comment by NikkiWines** [comment] 2024-06-25 05:10
Agreed, @Krishna2323's proposal looks fine for this issue

**Comment by MitchExpensify** [comment] 2024-07-16 20:05
Reassigning while I'm on leave (PR is on staging) 🙇

**Comment by sonialiap** [comment] 2024-07-24 10:19
Payment summary:
- @Krishna2323 $250 - offer sent via upwork
- @ishpaul777 $250 - offer sent via upwork - please complete the [checklist](https://github.com/Expensify/App/issues/43958#issuecomment-2232049884)

**Comment by sonialiap** [comment] 2024-07-24 10:31
Sorry Krishna! I thought I copied Ishpaul's name so that I can search for him on Upwork but apparently I didn't and sent a duplicate offer to you 😅

**Comment by sonialiap** [comment] 2024-08-13 08:34
@ishpaul777 checking if I can issue payment for you here? :)

**Comment by sonialiap** [comment] 2024-08-13 10:02
Excellent, payment issued ✔️

**Closed by sonialiap** 2024-08-13 10:02 UTC
Labels: External, Weekly, Awaiting Payment, Bug
