### ISSUE TITLE
[HOLD for payment 2023-11-01] [HOLD for payment 2023-10-13] [$500] Chat - App displays mention suggestion for sometime when we remove space from before @

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28170] opened 2023-09-25 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type @, it will trigger mention suggestions
4. Add space before @
5. Remove the space and observe that suggestions are displayed for sometime and then dismissed

## Expected Result:
App should not display suggestions on removing space before @

## Actual Result:
 App displays suggestions on removing space before @ for sometime

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/48d46156-7678-4827-a5dc-acb1af90ffe6

https://github.com/Expensify/App/assets/93399543/964e79e3-c452-4a51-b98b-05f42af1c718

https://github.com/Expensify/App/assets/93399543/1d46c808-c5db-4984-b8c4-1968426e3510

https://github.com/Expensify/App/assets/93399543/92c8c795-b9a4-4cdc-85e2-bcc05b9b4df9

https://github.com/Expensify/App/assets/93399543/969a841a-f864-4c6f-994e-fb09deb6df17

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695458107547879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193240eea08f27c8d</li>
        <li>Upwork Job ID: 1706350665337753600</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26974438</li>
<li>paultsimura | Contributor | 26974441</li>
<li>dhanashree-sawant | Reporter | 26974442</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-09-25 17:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The mentions suggestion appears for a moment when the symbol before "@" is removed.

### What is the root cause of that problem?
Because of dependencies list of this hook, the calculation is called before and after the value is changed:

https://github.com/Expensify/App/blob/26cd27fb8e6982ce8bedc393c585f3679e4935ab/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L235-L237

1. With changed value but previous selection
2. With changed value and new selection

As a result, on step 1, the cursor is calculated as standing after the "@" sign and the menu is shown.

### What changes do you think we should make in order to solve the problem?
We should execute this hook only if the selection has changed.

Option 1:
Change this hook to execute only if the selection was changed:
```js

    const prevSelection = usePrevious(selection);
    const didSelectionChange = !_.isEqual(prevSelection, selection);

    useEffect(() => {
        if (!didSelectionChange) {
            return;
        }

        calculateMentionSuggestion(selection.end);
    }, [didSelectionChange, selection, calculateMentionSuggestion]);

```

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-09-29 04:11
dupe assignment, i got this @stephanieelliott - unassigning you.

**Comment by cubuspl42** [comment] 2023-09-29 09:47
I approve the proposal by @paultsimura. The RCA looks fine, and the fix is simple.

C+ reviewed 🎀 👀 🎀

**Comment by lakchote** [comment] 2023-10-02 07:02
Solution looks good to me. Assigning now.

**Comment by paultsimura** [comment] 2023-10-02 07:32
Thanks, the PR is ready for review.

**Comment by amyevans** [comment] 2023-10-03 23:56
Crossposting that a regression has been identified: https://github.com/Expensify/App/issues/28657

**Comment by stephanieelliott** [comment] 2023-10-11 05:11
Updated `Hold` period to match the payout date of the regression.

**Comment by cubuspl42** [comment] 2023-10-11 08:16
@stephanieelliott I don't think we're eligible for payment here, at least for now. We had to [revert the solution](https://github.com/Expensify/App/pull/28794), and we're still investigating other options that will both solve this issue and don't have undesired side effects.

The fact that this is related to a bug in React Native itself doesn't help.

@paultsimura What's the latest status here? I know you've been discussing this on Slack

**Comment by zanyrenney** [comment] 2023-10-16 13:49
Yep, i think you're right @cubuspl42 this wouldn't qualify for payment. Let's link the slack conversation if there is one?

**Comment by paultsimura** [comment] 2023-10-16 13:52
> Yep, i think you're right @cubuspl42 this wouldn't qualify for payment. Let's link the slack conversation if there is one?

Here's the conversation, unfortunately it doesn't get the responses quite frequently:
https://expensify.slack.com/archives/C01GTK53T8Q/p1696421170146759

**Comment by shubham1206agra** [comment] 2023-10-17 15:37
Please test https://github.com/Expensify/App/issues/28749 with the proposed solution

**Comment by zanyrenney** [comment] 2023-10-17 16:36
who are you asking to test @shubham1206agra - please add the specific user you are directing your comments too so that we can understand better and keep pushing this forward with urgency?

**Comment by cubuspl42** [comment] 2023-10-17 17:03
@paultsimura Do you have a Git branch with these changes at hand?

**Comment by paultsimura** [comment] 2023-10-17 17:32
@cubuspl42 here it is: https://github.com/paultsimura/Expensify/tree/fix/28170-mention-on-delete
However, @shubham1206agra is right – this brings back the https://github.com/Expensify/App/issues/28749. Working on it...

**Comment by paultsimura** [comment] 2023-10-17 21:34
Ok, seems like I have a workaround that covers all the current cases I know:

```diff
+   const previousValue = usePrevious(value);

    useEffect(() => {
+       if (value.length < previousValue.length) {
+           return;
+       }

        calculateMentionSuggestion(selection.end);
    }, [selection, calculateMentionSuggestion]);
```

@cubuspl42 please test when you have a spare minute. The changes are in the branch already (with some debugging logs for the moment).
cc: @shubham1206agra

**Comment by cubuspl42** [comment] 2023-10-18 10:30
@paultsimura This might be working! But would you also test [this branch](https://github.com/cubuspl42/App/tree/useEffectWarmedUp-2) and share your thoughts?

**Comment by paultsimura** [comment] 2023-10-18 14:27
> @paultsimura This might be working! But would you also test [this branch](https://github.com/cubuspl42/App/tree/useEffectWarmedUp-2) and share your thoughts?

Unfortunately, the branch doesn't solve the current issue, does it work for you @cubuspl42 ?

https://github.com/Expensify/App/assets/12595293/8ece5d60-86ea-4658-9286-9688e8da785e

It's almost the same dependencies set as in current production – the `calculateMentionSuggestion` in our hook's dependencies changes with every `value` change (which is in `calculateMentionSuggestion`'s dependencies list). So replacing `calculateMentionSuggestion` with `value` eventually doesn't change anything, as far as I can see 🤔

**Comment by paultsimura** [comment] 2023-10-19 10:10
> I forgot what problem I'm workarounding in the end

I had the exact same situation at some point😅
It was because I was trying to find a workaround that solves all the issues at once. But after none of them worked, moved to just straightforward "don't show suggestions on removal" workaround.

**Comment by cubuspl42** [comment] 2023-10-19 10:13
You can file a PR with your best idea so far, we can move the discussion there

**Comment by zanyrenney** [comment] 2023-11-01 11:37
@cubuspl42 requires payment [offer](https://www.upwork.com/nx/wm/offer/26974438) (Reviewer) - paid $500
@paultsimura requires payment [offer](https://www.upwork.com/nx/wm/offer/26974441) (Contributor) paid $500
@dhanashree-sawant requires payment [offer](https://www.upwork.com/nx/wm/offer/26974442) (Reporter) paid $50

no bonus as 15 days elapsed.

all payments complete. Closing!

**Closed by zanyrenney** 2023-11-01 11:37 UTC
Labels: External, Weekly, Awaiting Payment, Bug
