### ISSUE TITLE
[$1000] Web -  Historical IOUs appearing in LHN like a pinned chat, above more recent chats, though they aren’t pinned

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23438] opened 2023-07-23 19:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If you have any old historical reports, then these will appear immediately below your pinned chats and above chat with more recent activity
3. Tap into the IOU report. The right header is also missing

## Expected Result:
Old IOUs shouldn’t appear above more recent chats, all IOUs should also have modern headers that links back to the parent report to which they are attached.

## Actual Result:
 Again, the headers are incorrect, the chats are being sorted incorrectly in the LHN vs more recent chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 11 07 05](https://github.com/Expensify/App/assets/93399543/73fa5c18-3081-4143-ad8b-5ae38a36808d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689959205989049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113e10683f580c981</li>
        <li>Upwork Job ID: 1683416987148619776</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>WikusKriek | Contributor | 26116737</li>
</ul></li>
    </ul>
</details>

**Comment by phamnduy** [comment] 2023-07-24 14:37
Contributor details
Your Expensify account email: phamngocduy96@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016a77b711407d33f1

**Comment by JmillsExpensify** [comment] 2023-07-24 21:38
This is still happening to me. I had even more appear today.

**Comment by ArekChr** [comment] 2023-07-25 09:32
Looking for proposals 📣

**Comment by priyankrawat** [comment] 2023-07-26 05:18
Contributor details
Your Expensify account email: rawat.priyank@yahoo.in
Upwork Profile Link: https://www.upwork.com/freelancers/~01dea109e55d7750c6

**Comment by dylanexpensify** [comment] 2023-07-28 09:59
@ArekChr mind giving @WikusKriek a reply?

**Comment by dylanexpensify** [comment] 2023-07-31 09:09
bump @ArekChr!

**Comment by ArekChr** [comment] 2023-07-31 11:30
Hey @dylanexpensify @WikusKriek, unfortunately, I don't have any old historical reports to reproduce this bug. Could we reassign someone who can reproduce this issue?

**Comment by dylanexpensify** [comment] 2023-08-03 11:11
@ArekChr of course!

**Comment by dylanexpensify** [comment] 2023-08-03 11:12
@mananjadhav can you review these? 🙇‍♂️

**Comment by dylanexpensify** [comment] 2023-08-08 08:05
Reviewing this today to post update! Got stuck with travel yesterday!

**Comment by dylanexpensify** [comment] 2023-08-10 11:05
@WikusKriek yes please! @mananjadhav mind reviewing?

**Comment by mananjadhav** [comment] 2023-08-11 07:24
Thanks for the proposal @WikusKriek. @dylanexpensify I am not sure if that's the expected behavior or the bug. If this the expected behavior in the GH body is correct, then @WikusKriek's proposal is good here.

I will stay let @dylanexpensify and internal engineer confirm once.

🎀 👀 🎀 C+ reviewed.

**Comment by tgolen** [comment] 2023-08-11 13:44
@WikusKriek I would like to understand your proposal better. Would you mind updating just this psuedo logic to explain what the current behavior is and what you propose (it looks like the comment is maybe a little out-of-date)?

https://github.com/Expensify/App/blob/530b45598bc52ec57a5d42327ef90942f1afe5df/src/libs/SidebarUtils.js#L116-L125

**Comment by dylanexpensify** [comment] 2023-08-14 08:02
looking now!

**Comment by tgolen** [comment] 2023-08-14 14:58
@WikusKriek Thanks. To make sure I understand your proposal clearly, you are suggesting to remove the settled IOUs from group 2 (and they will be default be in group 5)?

> Outstanding IOUs and outstanding IOUs waiting for bank account action to complete

Aren't these both the same thing? It appears they are both outstanding IOUs, and whether or not there are bank account actions to complete, they will be sorted from largest to smallest amounts. Can it be simplified to:

> Outstanding IOUs - Always sorted by iouReportAmount with the largest amounts at the top of the group

**Comment by tgolen** [comment] 2023-08-14 17:16
OK, thanks for clarifying. I'm OK with this proposal now and request that the PR also:

- Updates the comment about the groups and the sorting
- Removes the unnecessary unit test for the pending bank account

**Comment by mananjadhav** [comment] 2023-08-18 16:35
We got delayed by a few hours, I would request if we can still apply the bonus here. The QA was done, I spent quite a lot of time on getting my builds for Android and iOS.

**Comment by dylanexpensify** [comment] 2023-08-18 19:14
CC @tgolen thoughts? Seems understandable to me

**Comment by dylanexpensify** [comment] 2023-08-21 10:16
After discussing internally, we'll be sticking with the standard timeline requirement. For context, this stemmed from discussing grace periods and the outcomes where the boundaries we establish become fuzzy and ultimately hinder the initial premise behind offering this. Thanks for your understanding <3

**Comment by dylanexpensify** [comment] 2023-08-21 10:58
Payment summary:
- Contributor: @WikusKriek $1,000
- Contributor+: @mananjadhav $1,000

[Upwork job](https://www.upwork.com/jobs/~0113e10683f580c981). Please apply!

**Comment by mananjadhav** [comment] 2023-08-22 13:56
Thanks for the clarification. Totally agreed.

**Comment by dylanexpensify** [comment] 2023-08-25 11:47
Waiting for regression period to be over!

**Comment by mananjadhav** [comment] 2023-09-03 20:11
I couldn't pinpoint to a specific PR here, as the logic has existed since long. 

I also don't think we need to add a regression test here.

**Comment by mananjadhav** [comment] 2023-09-04 16:21
@dylanexpensify Quick bump on this one.

**Comment by mananjadhav** [comment] 2023-09-07 18:47
@JmillsExpensify a quick follow up on the payout here.

**Comment by JmillsExpensify** [comment] 2023-09-10 11:11
$1,000 approved for payment based on BZ summary.

**Comment by mananjadhav** [comment] 2023-09-17 16:51
@dylanexpensify Can we please payout @WikusKriek? If already done, can we close this one out?

and I changed my mind about adding regression tests.


**Regression Test Steps**
1. Open the app
2. Verify that the LHN are ordered in the order of the list
       - Pinned
       - Outstanding IOUs
       - Drafts
       - Non-archived reports and settled IOUs
       - Archived reports

**Comment by dylanexpensify** [comment] 2023-09-20 08:45
done!

**Closed by dylanexpensify** 2023-09-20 08:45 UTC
Labels: Reviewing, External, Weekly, Bug
