### ISSUE TITLE
The "New" marker is appearing on thread messages after refreshing the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26563] opened 2023-09-02 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Hover over the message and click "Reply in thread"
4. Refresh the page
5. Observe that the "New" marker is displayed on the thread message
## Expected Result: 
The "New" marker should not be displayed on thread messages after refreshing the page
## Actual Result: 
The "New" marker is appearing on thread messages after refreshing the page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cb5b8e26-77af-4591-9b67-2c93d47ddf94

![Snip - (2) New Expensify - Google Chrome (7)](https://github.com/Expensify/App/assets/43996225/6c1d108f-ccb5-4003-ad4f-77a1d1d8b2b9)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693001557283169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-09-08 15:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We show the new message line the first time the user refreshes a thread report 

### What is the root cause of that problem?

We calculate weither we should show the new marker here: https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/pages/home/report/ReportActionsList.js#L229-L240

Looking at this code when we are in a newly created thread, in sortedReportActions we only have the CREATED action so nextMessage is undefined, so we show the new marker if this condition `isMessageUnread(reportAction, report.lastReadTime);` is true.

For this condition to be true `report.lastReadTime` must be inferior to `reportAction.created`.

The first time we enter the report those two dates are equal because we set them optimistically but when we refresh the dates are returned by the server and `report.lastReadTime` is inferior  to `reportAction.created` so we show the marker


### What changes do you think we should make in order to solve the problem?

Solution 1: the server has to return a  lastReadTime equal to the created date


Solution 2: We can also decide to compare the created date of the parent report  action in case this is the first message of a thread, we can use shouldDisplayParentAction to know that 


### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2023-09-11 10:29
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment] 2023-09-13 20:17
Couldn't reproduce - @ayazhussain79 can you confirm, cc @kavimuru

**Comment by ayazhussain79** [comment] 2023-09-13 20:53
@dylanexpensify You can reproduce it on dev

**Comment by dylanexpensify** [comment] 2023-09-19 08:27
cannot repro still on staging - closing

**Closed by dylanexpensify** 2023-09-19 08:27 UTC
Labels: Daily, Overdue, Bug
