### ISSUE TITLE
[$250] [Held requests] Hold option is available for failed scan expense but does not work as intended

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45263] opened 2024-07-11 12:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with any user
3. Submit one manual expense
4. Submit a scan expense with an invalid receipt
5. Wait for the scanning to fail
6. After the scanning fails, go to transaction thread of the failed scan expense
7. Click on the report header
8. Click Hold
9. Enter a reason and save it
10. Revisit the transaction thread

## Expected Result:
The failed scan expense will remain in held status

## Actual Result:
The failed scan expense becomes unheld after revisiting the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/43a1a21f-e364-4209-9574-de09017b79d8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119279654a77b0111</li>
        <li>Upwork Job ID: 1816865137954875032</li>
        <li>Last Price Increase: 2024-07-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by lanitochka17** [comment] 2024-07-11 12:31
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-11 12:32
We think that this bug might be related to #wave-collect - Release 1

**Comment by etCoderDysto** [comment] 2024-07-11 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold option is available for failed scan expense but does not work as intended
### What is the root cause of that problem?
`canHoldUnholdReportAction` returns true for `hold` when scan state is `SCANFAILED`. This is because we are only checking if `isScanning` and returning false when it is true;
https://github.com/Expensify/App/blob/28e5e4553454503180a64103bb35fae743424b6b/src/libs/ReportUtils.ts#L2826
### What changes do you think we should make in order to solve the problem?
We should check if scanning failed and return false if it does. 
* Check if scanning failed 
```
const isScanFailed = TransactionUtils.hasReceipt(transaction) && transaction?.receipt?.state === CONST.IOU.RECEIPT_STATE.SCANFAILED;
```
* return false when it is true 

```
const canHoldRequest = canHoldOrUnholdRequest && !isOnHold && (isRequestHoldCreator || (!isRequestIOU && canModifyStatus)) && !isScanning && !!transaction?.reimbursable && !isScanFailed;
```
We can apply the same for `canUnholdRequest` to put an extra guard 
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-07-30 11:48
The `canHoldOrUnholdRequest` function only considers the scanning status of the receipt and not the failed status. When the receipt scanning fails, `canHoldOrUnholdRequest` shows the `Hold` option. Clicking on the `Hold` option adds a `hold` field to the `comment` of the `transaction`, and the backend does not throw an error. The `Unhold` option then appears in place of `Hold` on the `ReportDetailsPage`.

However, when we go back to the parent report and revisit the thread, it calls `OpenReport` and there is no `hold` field in the `comment` of the `transaction`. Consequently, the `Hold` option appears again on the `ReportDetailsPage`.

Since we do not allow holding an expense while scanning, it is logical to also prevent holding the expense when the scan fails. Therefore, the [proposal here](https://github.com/Expensify/App/issues/45263#issuecomment-2222885831) by @etCoderDysto looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by luacmartins** [comment] 2024-07-30 15:46
I'm not sure what the expected behavior is here. @robertjchen could you please confirm? Should we be able to hold expenses with a failed scan? I don't see anything in the backend preventing that, so I'm not sure why the hold action is not persisted in this case.

**Comment by c3024** [comment] 2024-07-30 16:23
There is no check on the backend to prevent holding a request that is being scanned. This restriction is only on the frontend. If we remove the `isScanning` condition in `canHoldOrUnHoldRequest` on the front-end and click on `Hold` in the `ReportDetailsPage`, the backend does not throw any error.

**Comment by luacmartins** [comment] 2024-07-30 16:26
Yes, I noticed that when implementing the feature on the Search page as well. There are several checks on the frontend that are not enforced by the API. @robertjchen is that something that we should be enforcing on the API side too?

**Comment by robertjchen** [comment] 2024-07-31 10:09
> Should we be able to hold expenses with a failed scan?

Yes. 

Is the issue with the fact that the report status is not being optimistically updated after the held action?

**Comment by luacmartins** [comment] 2024-07-31 12:32
Ok, so we should be able to hold the expense. @etCoderDysto @c3024 I think the RCA is incorrect in this case. Now why does that not work properly if the API request doesn't fail?

**Comment by etCoderDysto** [comment] 2024-07-31 12:36
> Ok, so we should be able to hold the expense. @etCoderDysto @c3024 I think the RCA is incorrect in this case. Now why does that not work properly if the API request doesn't fail?

I will investigate why it is failing and get back to you.

**Comment by c3024** [comment] 2024-08-03 06:26
I think this should be checked from the backend.

`HoldRequest` adds a `hold` field to the `comment` in the transaction, but after visiting the parent report and then revisiting the transaction thread, the `OpenReport` call does not return the transaction with the `hold` in its `comment` field.

https://github.com/user-attachments/assets/2be2ff1d-56f1-4d00-b708-f011128254c7

**Comment by luacmartins** [comment] 2024-08-06 06:28
@c3024 so is the expense held, but the system message is missing?

**Comment by c3024** [comment] 2024-08-06 06:43
The expense is held correctly as long as we are on the report or on the report details page but when we revisit this report the  `OpenReport` response from backend resets this field that determines if the expense if held or not.

**Comment by luacmartins** [comment] 2024-08-07 06:49
@c3024 I'm unable to reproduce that behavior in dev. Loading the report with the `held` transaction still returns the `hold` action. What am I missing?

Uploading Screen Recording 2024-08-07 at 9.48.25 AM.mov…

**Comment by trjExpensify** [comment] 2024-08-08 23:36
I can repro this: 

https://github.com/user-attachments/assets/f908506e-0a0a-4964-9f76-15b42c38964b

**Comment by c3024** [comment] 2024-08-09 08:25
@luacmartins I can repro it consistently with the steps in the OP.

**Comment by luacmartins** [comment] 2024-08-12 08:50
Yea, I'm not sure why I can't reproduce this. I wonder if we're not persisting the data or if OpenReport is just not returning the hold action. @trjExpensify @c3024 do you have a reportID for the problematic transactions?

**Comment by trjExpensify** [comment] 2024-08-12 13:33
That one above in the screenshot of mine is `5146156808592902`

**Comment by robertjchen** [comment] 2024-08-14 07:17
Hm, it seems like the core issue is that `OpenReport` is not returning the hold action.  I've dug through the command, but nothing indicates that it's caching anything- the action and changes to the reports clearly happen before `OpenReport`, so why is it not being reflected in the data? 🤔

**Comment by luacmartins** [comment] 2024-08-14 13:45
@robertjchen I was able to reproduce this in staging (not in dev) and it seems like we do return the reportAction in OpenReport and it is stored in Onyx, but for some reason the UI doesn't reflect that


https://github.com/user-attachments/assets/68348906-dee8-48d4-b220-ac29dc894275

![Screenshot 2024-08-14 at 7 44 59 AM](https://github.com/user-attachments/assets/41a7c477-6f60-4825-89f0-6de61f95af9c)

**Comment by luacmartins** [comment] 2024-08-14 13:47
That being said, I can hold the request again and the API returns a 200 and I end up with 2 hold actions

![Screenshot 2024-08-14 at 7 46 09 AM](https://github.com/user-attachments/assets/d49125a6-e400-4041-b832-aac33148bf52)

**Comment by luacmartins** [comment] 2024-08-14 20:23
PR in review

**Comment by luacmartins** [comment] 2024-08-14 20:23
This will be internal, since the bug is in the API

**Comment by robertjchen** [comment] 2024-08-15 23:01
Fix was deployed!

**Comment by c3024** [comment] 2024-08-17 13:27
This is not reproducible anymore. Fixed!


https://github.com/user-attachments/assets/f0fbf9b7-4a69-49b2-823e-1d055c63d2ef

**Comment by luacmartins** [comment] 2024-08-19 12:47
Awesome! Seems like the fix worked. Closing!

**Closed by luacmartins** 2024-08-19 12:47 UTC
Labels: Reviewing, Daily, Internal, Bug, retest-weekly
