### ISSUE TITLE
[$1000] Avatar is selectable in chat 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13908] opened 2022-12-30 16:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Long-press the avatar in the header (near the back button)

## Expected Result:
The details page should open with details of the given user

## Actual Result:
The avatar is highlighted

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / Safari

**Version Number:** 1.2.46-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/210089696-e661dee8-9695-4fa2-a84d-53230df1e1e2.PNG" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/210089680-9147d12a-1ec2-443d-93d3-f22ca44e0fd2.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672374301952909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01770d630fe98329bd</li>
        <li>Upwork Job ID: 1609937519541727232</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by sketchydroide** [comment] 2023-01-02 15:40
I could reproduce in iOS/Safari like mentioned, not sure what exaclyt can be done, but may setting as not selectable, I think I remember seing such and option

**Comment by roryabraham** [comment] 2023-01-02 16:12
@sketchydroide we might be able to fix this by just setting `focusable={false}`: https://necolas.github.io/react-native-web/docs/accessibility/#keyboard-focus

**Comment by sketchydroide** [comment] 2023-01-02 16:49
yes, I forgot that the property was, but focused makes total sense, thanks

**Comment by sketchydroide** [comment] 2023-01-03 15:34
should still work on this today

**Comment by JmillsExpensify** [comment] 2023-01-11 05:03
Shall we open this up for external proposals then? Seems like a good idea given that we've stalled a bit.

**Comment by sketchydroide** [comment] 2023-01-11 13:08
Yes let's

**Comment by hungvu193** [comment] 2023-01-11 13:18
We can fix this by adding the styles: `styles.userSelectNone` to the View of SubscripAvatar and MultipleAvatars.
Here's the result:

https://user-images.githubusercontent.com/16502320/211816065-bc4d5fb5-9f3f-46bd-b8df-f33943b8130e.mov

**Comment by bernhardoj** [comment] 2023-01-11 14:32
### **Proposal**

We can add `styles.userSelectNone` to the pressable to make it non-selectable.

By the way, we can also select the avatar by long press the chat title first and then drag the start selection to left to select the avatar (on Android mWeb) and also all Avatar is selectable.

1st solution
```diff
diff --git a/src/pages/home/HeaderView.js b/src/pages/home/HeaderView.js
index fa2680d10..e0d5088c3 100644
--- a/src/pages/home/HeaderView.js
+++ b/src/pages/home/HeaderView.js
@@ -99,7 +99,7 @@ const HeaderView = (props) => {
                     >
                         <Pressable
                             onPress={() => ReportUtils.navigateToDetailsPage(props.report)}
-                            style={[styles.flexRow, styles.alignItemsCenter, styles.flex1]}
+                            style={[styles.flexRow, styles.alignItemsCenter, styles.flex1, styles.userSelectNone]}
                         >
                             {shouldShowSubscript ? (
                                 <SubscriptAvatar
```

But doing this makes the chat title also non-selectable. So, the other solution is to add the style to the Avatar component.

2nd solution
```diff
diff --git a/src/components/Avatar.js b/src/components/Avatar.js
index a236c63b2..af811eb17 100644
--- a/src/components/Avatar.js
+++ b/src/components/Avatar.js
@@ -80,7 +80,7 @@ class Avatar extends PureComponent {
         const iconSize = StyleUtils.getAvatarSize(this.props.size);
 
         return (
-            <View pointerEvents="none" style={this.props.containerStyles}>
+            <View pointerEvents="none" style={[styles.userSelectNone, this.props.containerStyles]}>
                 {_.isFunction(this.props.source) || this.state.imageError
                     ? (
                         <View style={iconStyle}>
```

**Comment by JmillsExpensify** [comment] 2023-01-11 17:28
@mananjadhav I wanted to put this issue on your radar. It'd be good to prioritize any proposals as we get them given that we have two weeks left until this bug will be elevated to `urgent` status.

**Comment by mananjadhav** [comment] 2023-01-11 17:49
Thanks for the bump, I'll be checking this within 30-40 mins.

**Comment by mananjadhav** [comment] 2023-01-11 18:26
@bernhardoj Proposal does disable the avatar selection, but I recommend using it on `Avatar`. But generally when we disable selection, long press will trigger the text selection some other nearby component, which is HeaderView in our case. 

@JmillsExpensify  @sketchydroide @Gonals   Are we fine the following output when we long press the Avatar?

<img width="469" alt="image" src="https://user-images.githubusercontent.com/3069065/211887692-79a7f92a-2f13-4c19-9098-5dd85cf82762.png">

If yes, then we can go ahead with @bernhardoj's proposal.

**Comment by JmillsExpensify** [comment] 2023-01-11 21:16
That's a great question. I don't think that's terrible, but I also think we should create a thread in #expensify-open-source to get a broader discussion going. What do you think? Would you be willing to start that?

**Comment by mananjadhav** [comment] 2023-01-12 14:26
@JmillsExpensify I started a thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1673533485828289)

**Comment by mananjadhav** [comment] 2023-01-12 14:28
@bernhardoj While I've started the thread, and also the explained the behavior, I just realized the **Expected Result** is `The details page should open with details of the given user.`

I don't see that happening with your proposal.

**Comment by bernhardoj** [comment] 2023-01-12 15:07
@mananjadhav Oh, I also just realized the long press should open the details. 

We can just add the onLongPress, the same thing @sketchydroide mentioned [here](https://github.com/Expensify/App/issues/13908#issuecomment-1372360318).

```diff
diff --git a/src/pages/home/HeaderView.js b/src/pages/home/HeaderView.js
index fa2680d10..afda2f913 100644
--- a/src/pages/home/HeaderView.js
+++ b/src/pages/home/HeaderView.js
@@ -99,6 +99,7 @@ const HeaderView = (props) => {
                     >
                         <Pressable
                             onPress={() => ReportUtils.navigateToDetailsPage(props.report)}
+                            onLongPress={() => ReportUtils.navigateToDetailsPage(props.report)}
                             style={[styles.flexRow, styles.alignItemsCenter, styles.flex1]}
                         >
                             {shouldShowSubscript ? (
```

But I'm not sure why we want to open the details when we long press it. And also, it will open the details when we long press the user name.

**Comment by mananjadhav** [comment] 2023-01-16 04:22
thanks for the comments @0xmiroslav. I'll check your proposals today.

**Comment by mananjadhav** [comment] 2023-01-16 16:06
@0xmiroslav This is a good thought. I am inclined towards using `ControlSelection`. My concern is we're also disabling this for the header text.

@JmillsExpensify @Gonals  What do you folks think about it? Also any specific reason we need to redirect when long pressed.

**Comment by mananjadhav** [comment] 2023-01-16 16:31
Agreed. I am aware and hence I want to confirm if we want to block this for Header too.

**Comment by JmillsExpensify** [comment] 2023-01-17 05:10
@Gonals I think I like where @0xmiroslav is headed in [this comment](https://github.com/Expensify/App/issues/13908#issuecomment-1384286437). Thoughts?

**Comment by bernhardoj** [comment] 2023-01-17 09:23
Just giving my thoughts. Applying the user-select none will also prevent the other avatar be selected, like here
![image](https://user-images.githubusercontent.com/50919443/212838246-315ee0ba-b9cf-4c4f-91ad-eaed944c0e3b.png)

But honestly, I am not sure if we should bother with this selection issue at all (there is nothing broke I guess), as we are still able to select the avatar if we select it like this. Maybe it is the behavior of Safari/chrome mobile. On another platform, we can't select the avatar because it is rendered as a div with a background image.
![image](https://user-images.githubusercontent.com/50919443/212849524-9cab67ac-5d42-47b2-94b2-e0a651148e33.png)

**Comment by JmillsExpensify** [comment] 2023-01-19 00:45
Yeah that's a really interesting comment. I think I agree with it. @roryabraham you reported this issue, so do you mind jumping in and confirming if you are passionate either way?

**Comment by roryabraham** [comment] 2023-01-19 05:51
Yeah, I am not super passionate and can see the argument for this not being a bug at all actually. Going to just close this out then.

**Closed by roryabraham** 2023-01-19 05:51 UTC
Labels: External, Daily, Help Wanted, Bug
