### ISSUE TITLE
 iOS - Hold - Back button on transaction thread returns to Hold - Reason page after holding it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44423] opened 2024-06-26 00:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #43618
**Version Number:** 9.0.2-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace chat.
3. Submit an expense.
4. Go to transaction thread.
5. Tap 3-dot menu > Hold.
6. Enter reason > Save.
7. Tap on the back button.

## Expected Result:
Back button on transaction thread will not return to Hold - Reason page.

## Actual Result:
Back button on transaction thread returns to Hold - Reason page after holding the expense.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/7e881683-2390-457a-9969-df3772c5c620

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-06-26 00:58
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-26 06:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing back button after hold arrived at the hold reason page again.

### What is the root cause of that problem?
After submitting the hold reason, we navigate to the backTo param.
https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/pages/iou/HoldReasonPage.tsx#L56-L58

backTo in this case is the transaction thread report. It should navigate back to the transaction thread because it exists on the stack, but the backTo route keeps being pushed to the nav stack because it's detected that the params of the backTo route is different with the params of the topmost central pane.
https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/libs/Navigation/linkTo/index.ts#L89

If the transaction thread report route is /r/123, then the backTo is also /r/123, but somehow the comparison fails. 
https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/libs/Navigation/linkTo/index.ts#L80-L86
https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/libs/Navigation/linkTo/index.ts#L75

First, the `actionParams?.screen === SCREENS.REPORT` returns false. Second, the shallowCompare also returns false. That's because both `actionParams?.screen` and `actionParams?.params` are undefined. This happened after we [simplify the root navigator](https://github.com/Expensify/App/pull/42582).

Report screen was previously inside a CentralPaneNavigator, but it's not anymore now.

### What changes do you think we should make in order to solve the problem?

Replace the usages of `actionParams?.screen` with `action.payload.name` and `actionParams?.params` with `action.payload.params`.
https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/libs/Navigation/linkTo/index.ts#L79-L86
https://github.com/Expensify/App/blob/9862fdbc01fe36bdb6dee9554023178d9f476bdb/src/libs/Navigation/linkTo/index.ts#L113-L115

**Comment by WojtekBoman** [comment] 2024-06-26 09:08
Hi! I'll take a look at this issue

**Comment by luacmartins** [comment] 2024-06-27 15:42
This was fixed by https://github.com/Expensify/App/pull/44444 and CPed to staging. We're good to close since it was a regression.

**Closed by luacmartins** 2024-06-27 15:42 UTC
Labels: Reviewing, Engineering, Weekly, Bug
