### ISSUE TITLE
[$250] iOS - Track expense - App crashes after deleting expense offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48197] opened 2024-08-28 18:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25.11
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app and log in
2. Navigate to self-DM
3. Tap + > Track expense > Manual
4. Create an expense
5. Disable the internet connection
6. Long tap the expense > Delete expense

## Expected Result:
The expense is greyed out, the amount is crossed out

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2a2aadb6-e40a-4b67-a188-a757b00a0c14

[2808.txt](https://github.com/user-attachments/files/16787261/2808.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b920bb98479136b</li>
        <li>Upwork Job ID: 1828958726626801528</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 103818924</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by IuliiaHerets** [comment] 2024-08-28 18:02
We think that this bug might be related to #wave-collect - Release 1

**Comment by stitesExpensify** [comment] 2024-08-28 22:07
Switching this to deployblockercash since this is iOS only

**Comment by NJ-2020** [comment] 2024-08-29 05:20
@suneox I think you need to turn off the wifi before deleting the expense and it still didn't work i think you can try using staging server

**Comment by NJ-2020** [comment] 2024-08-29 05:32
Yes issue are not reproducible from both non-staging and staging server

**Comment by chiragsalian** [comment] 2024-08-30 16:35
Given this is an edge case and we're having a bit of a difficult time solving this immediately, we'll be demoting it to daily, removing blocker and requesting help with this.

**Comment by hannojg** [comment] 2024-08-31 08:25
cc @kirillzyusko can you comment here so you can be [assigned](https://expensify.slack.com/archives/C035J5C9FAP/p1725034670591529)?

**Comment by kirillzyusko** [comment] 2024-09-02 10:20
Sure, feel free to assign this on me 🙌

**Comment by kirillzyusko** [comment] 2024-09-02 16:23
Few things that I spotted:
- the crash happens because we are trying to unmount a component that already has been unmounted;
- the component that triggers a crash is `Paragraph` (i. e. `Text`)
- if I remove all `Text` elements in `MoneyRequestPreviewContent` component then crash goes away;
- if I clean-up the logic in `OfflineWithFeedback`:

```tsx
<View style={style}>
    {!hideChildren && (
        children
    )}
    {shouldShowErrorMessages && (
        <ErrorMessageRow
            errors={errors}
            errorRowStyles={errorRowStyles}
            onClose={onClose}
            canDismissError={canDismissError}
        />
    )}
</View>
```

then crash also goes away.

I think the problem is hidden somewhere in this code:

```tsx
<View
    style={[needsOpacity ? styles.offlineFeedback.pending : {}, contentContainerStyle]}
    needsOffscreenAlphaCompositing={shouldRenderOffscreen ? needsOpacity && needsOffscreenAlphaCompositing : undefined}
>
```

Because as soon as I remove it the crash is not happening anymore.

I'll continue my investigation tomorrow and hopefully will provide a fix!

**Comment by kirillzyusko** [comment] 2024-09-03 15:12
I opened a PR with a fix here: https://github.com/Expensify/App/pull/48474

**Comment by jjcoffee** [comment] 2024-09-04 12:35
@chiragsalian Can you assign me here as I've been auto-assigned for reviewing the PR? Thanks! :pray:

**Comment by jjcoffee** [comment] 2024-09-23 12:21
- The PR that introduced the bug has been identified. Link to the PR: N/A - not possible to determine
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

(Native mobile only)

1. Navigate to self-DM
2. Tap + > Track expense > Manual
3. Create an expense
4. Disable the internet connection
5. Long tap the expense > Delete expense
6. Verify that the app does not crash

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-09-23 12:22
@VictoriaExpensify This was [deployed](https://github.com/Expensify/App/pull/48474#issuecomment-2347262698) Sept 12, so should be ready for payment now.

**Comment by jjcoffee** [comment] 2024-11-28 10:20
@VictoriaExpensify I think you reopened this one by mistake?

**Comment by VictoriaExpensify** [comment] 2024-11-28 10:46
Ha I guess I did!

**Closed** 2024-11-28 10:46 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
