### ISSUE TITLE
Web -  Bank account - Date doesn't give an error when entering wrong date till checkbox is checked

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24377] opened 2023-08-10 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on Settings > Workspaces > any workspace > Bank account > Connect manually
3. Reach 2nd step and Enter wrong date for date field and you see that Date doesn't give you an error when entering wrong date till checkbox is checked

## Expected Result:
Date should give us an error immadiately when entering wrong date

## Actual Result:
Date doesn't give an error when entering wrong date till checkbox is checked

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.52-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/115492554/c3fd8acf-e9e1-457c-8c60-cbb5437483e9

https://github.com/Expensify/App/assets/115492554/eef466ea-e47d-4500-aa7f-3fa0658c2098

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691124796866249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Talha345** [comment] 2023-08-10 15:13
I think this is not a bug!

**Comment by flaviadefaria** [comment] 2023-08-15 10:42
I agree that we do not need to fix this - closing it.

**Closed by flaviadefaria** 2023-08-15 10:42 UTC
Labels: Daily, Overdue, Bug
