### ISSUE TITLE
[$500] Web - Status - The emoji in status is not centered vertically

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32283] opened 2023-11-30 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Profile -> Status -> Choose some emoji -> Save

## Expected Result:
The emoji in status is centered vertically

## Actual Result:
The emoji in status is not centered vertically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6296227_1701362692726!3011_1](https://github.com/Expensify/App/assets/78819774/01efc45f-0852-428d-8bca-995eb0e5d97c)

![Bug6296227_1701362692747!image__182_](https://github.com/Expensify/App/assets/78819774/fe6d4b1c-4efb-4147-b22b-cfe40004b9d0)

![Bug6296227_1701362692730!3011_2](https://github.com/Expensify/App/assets/78819774/addb612e-602a-4fd8-94ba-8b7032a2ac05)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b4c3beb2fe57896</li>
        <li>Upwork Job ID: 1730285271523926016</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-11-30 18:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The emoji in status is not centered.

### What is the root cause of that problem?
The line height of the emoji is not set.

### What changes do you think we should make in order to solve the problem?

We should set the `lineHeight` to the Emoji component, equal to the font size (22px).



### What alternative solutions did you explore? (Optional)

**Comment by sukach318** [comment] 2023-12-01 10:09
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
The emoji in status is not centered vertically

What is the root cause of that problem?
The root cause arises from setting the font family to `ExpensifyNeue-Regular, "Windows Segoe UI Emoji", "Noto Color Emoji"`. Specifically, the problematic font causing issues is `Segoe UI Emoji`.

### **What changes do you think we should make in order to solve the problem?**
Basically, Segoe UI is intentionally not vertically centered within its "line height". Most typefaces use the same value for the top and bottom "half leading". Segoe UI doesn't and the top half leading is greater than the bottom one. As a consequence, it's hard to fix this via CSS.

There's nothing we plan to do to change about this right now. Customizing styles per OS isn't something we want to get into. We've had this since v4 a few years ago, so nothing new here.

The best way that we can is just that set `line-height` property to 1 using CSS.
When `line-height` is set to `1`, it indicates that the line height should be equal to the current font size of the element.
I would like to tell you that no matter what the solution is, it may not be a complete solution.

Reference link
[https://stackoverflow.com/questions/21580059/text-is-not-vertically-centered](https://stackoverflow.com/questions/21580059/text-is-not-vertically-centered)

### **What alternative solutions did you explore? (Optional)**

**Comment by paultsimura** [comment] 2023-12-01 18:17
> Anyone have some extra repro steps? I don't see any obvious issue, or is it just like 1px off?

It depends on the emoji, but in general – yes, mostly 1-3 px off.

**Comment by yh-0218** [comment] 2023-12-05 07:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The emoji in status is not centered vertically
### What is the root cause of that problem?
We did not set the `line-height` property for emoji
### What changes do you think we should make in order to solve the problem?
We need to set `line-height` [here](https://github.com/Expensify/App/blob/48b5a29f33ca4cfa8a0b75361f68f6df83455613/src/styles/styles.ts#L3799) and [here](https://github.com/Expensify/App/blob/48b5a29f33ca4cfa8a0b75361f68f6df83455613/src/styles/styles.ts#L3677)
```
lineHeight: '100%'
```

### What alternative solutions did you explore? (Optional)

<img width="104" alt="Screenshot 2023-12-05 at 9 51 28 AM" src="https://github.com/Expensify/App/assets/65789015/627188f5-96c9-4449-8e04-e3f1967473f7">
<img width="114" alt="Screenshot 2023-12-05 at 9 51 57 AM" src="https://github.com/Expensify/App/assets/65789015/0009fcb1-7f75-4aab-a95a-001b1679c338">

**Comment by jjcoffee** [comment] 2023-12-06 12:40
Setting the line-height to 22px or 1 or 100% all do the same thing and for emojis that fill the full area they get slightly cropped, which seems unacceptable for such a tiny tweak.

![image](https://github.com/Expensify/App/assets/27287420/7de504fd-4ef0-4bd7-b764-b40c136f77aa)
(Note the sharp top and bottom edges, these are meant to be soft).

Meanwhile @tienifr's [proposal](https://github.com/Expensify/App/issues/32283#issuecomment-1835759361) doesn't seem to work:

![image](https://github.com/Expensify/App/assets/27287420/ca959517-39d8-46ac-bee2-97cf96195230)

I think this [proposal](https://github.com/Expensify/App/issues/32283#issuecomment-1835819236) is correct that there isn't a direct fix for this with CSS as the lack of vertical centring in the font is baked in:

>Most typefaces use the same value for the top and bottom "half leading". Segoe UI doesn't and the top half leading is greater than the bottom one. As a consequence, it's hard to fix this via CSS.

Open to suggestions for more robust workarounds!

**Comment by yh-0218** [comment] 2023-12-06 12:54
Hi, @jjcoffee Could you check [my proposal](https://github.com/Expensify/App/issues/32283#issuecomment-1840186790)
Thanks.

**Comment by jjcoffee** [comment] 2023-12-06 16:19
@yh-0218 I've addressed your proposal at the start of my [comment](https://github.com/Expensify/App/issues/32283#issuecomment-1842787194).

>Setting the line-height to 22px or 1 or **100%** all do the same thing and for emojis that fill the full area they get slightly cropped, which seems unacceptable for such a tiny tweak.

**Comment by yh-0218** [comment] 2023-12-07 04:06
@jjcoffee I can't find cropped emoji when `line-height: '100%'`

**Comment by jjcoffee** [comment] 2023-12-07 13:44
@sukach318 Welcome! Offers are only made for proposals that solve the issue. I'm still looking for a decent solution.

@tienifr If you try it with an emoji that fills the full height, e.g. ➡️, there's a difference. Either way I don't think it's worth applying any of the proposals if they just shift a few pixels _but are still misaligned_. We'd want something that works for all emojis.

@yh-0218 See my [screenshot](https://github.com/Expensify/App/issues/32283#issuecomment-1842787194) - you have to zoom in to see it though :smile:

**Comment by yh-0218** [comment] 2023-12-07 16:07
> No. All platforms are different

we can give different value for all platform

**Comment by sukach318** [comment] 2023-12-08 08:23
@jjcoffee 
I think, while CSS constraints pose challenges in directly tackling this issue, JavaScript will offers a more precise solution.

**Closed** 2023-12-11 19:54 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
