### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Status - Unable to set custom time after selecting the duration

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33423] opened 2023-12-21 15:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Profile > Status.
2. Click Clear after.
3. Select 30 minutes.
4. Click Clear after.
5. Click Date under Custom.
6. Select a different date.

## Expected Result:
The selected date is saved.

## Actual Result:
The selected date is not saved.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a724f215-c857-4f93-ac74-23e70e495358

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4c9ce5463b9747c</li>
        <li>Upwork Job ID: 1737863065032630272</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28067990</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @tylerkaraszewski</details>

**Comment by paultsimura** [comment] 2023-12-21 16:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When selecting the date value, the actual form's value is not updated because the DatePicker is not wrapped in the `<InputWrapper>`

### What changes do you think we should make in order to solve the problem?
We should use:

```js
                <InputWrapper
                    InputComponent={DatePicker}
                    inputID="dateTime"
                    label={translate('statusPage.date')}
                    defaultValue={DateUtils.extractDate(customClearAfter)}
                    minDate={new Date()}
                />
```



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-12-22 22:44
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/33525

**Comment by tylerkaraszewski** [comment] 2024-01-03 22:37
The PR for this is merged. I think it's in @adelekennedy's court next.

**Comment by adelekennedy** [comment] 2024-01-15 16:44
@parasharrajat bump on the checklist

**Comment by adelekennedy** [comment] 2024-01-15 16:46
### Payouts due:

Contributor: $500 @paultsimura (Upwork)
Contributor+: $500 @parasharrajat (NewDot)

**Comment by adelekennedy** [comment] 2024-01-17 23:19
I'll kick it to @tylerkaraszewski for any changes/other thoughts on the regression test but that makes sense to me

**Comment by tylerkaraszewski** [comment] 2024-01-22 23:43
I think that's fine.

**Closed by tylerkaraszewski** 2024-01-22 23:43 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-19 16:40
$500 approved for @parasharrajat
