### ISSUE TITLE
Deploy checklist is listing PRs from 2-3 previous builds 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24030] opened 2023-08-02 02:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the current Deploy checklist. e.g. https://github.com/Expensify/App/issues/24028
2. Check the PRs listed  
3. CP PR 
4. Observe if CP is added to the checklist 

## Expected Result:
Only PRs deployed in the build should be listed 
CPs should be added to the checklist once deployed 

## Actual Result:
Multiple PRs from previous deploys displayed in the checklist even after they were already deployed to PROD.  
Once CP is deployed, its not added to the checklist

## Workaround:
unknown 

**Notes/Photos/Videos:** Any additional supporting documentation 

![Screen Shot 2023-08-01 at 10 08 02 PM](https://github.com/Expensify/App/assets/43995119/9eb6e686-7711-42f6-a431-2a2698a29a17)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Testing Team 
**Slack conversation:** 
https://expensify.slack.com/archives/C9YU7BX5M/p1690509355423659 
https://expensify.slack.com/archives/C9YU7BX5M/p1690256275653639
https://expensify.slack.com/archives/C9YU7BX5M/p1689965139270719
https://expensify.slack.com/archives/C9YU7BX5M/p1690935729223149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158becf89864f9a24</li>
        <li>Upwork Job ID: 1686796943040983040</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-08-04 21:51
@0xmiroslav can you take a peek if this should be internal or external when you have time? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-08-07 18:06
Thanks for confirming @0xmiroslav added the engineering label

**Comment by Christinadobrzyn** [comment] 2023-08-10 20:39
looks like https://github.com/Expensify/App/issues/23179 might be related. 

@0xmiroslav feel free to add any updates on this one!

**Comment by Christinadobrzyn** [comment] 2023-08-14 23:02
Not sure the update on this one - @0xmiroslav what questions do you have for @puneetlath? Can you provide them here or in a Slack convo?

**Comment by Christinadobrzyn** [comment] 2023-08-23 20:49
Sorry, I've not been great about trying to figure out how to guide this issue. I reached out to the team in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1692806049032689) to see if I can get some guidance.

**Comment by Christinadobrzyn** [comment] 2023-08-28 21:28
Hey @mvtglobally are you still seeing this issue?

**Comment by mvtglobally** [comment] 2023-08-29 21:49
still happening on the latest checklist https://github.com/Expensify/App/issues/26113#issuecomment-1696683100

**Comment by thienlnam** [comment] 2023-08-30 00:05
cc @roryabraham

**Comment by roryabraham** [comment] 2023-08-30 07:05
Closing this as a dupe of https://github.com/Expensify/App/issues/21763

**Closed by roryabraham** 2023-08-30 07:05 UTC
Labels: Engineering, Daily, Internal, Bug
