### ISSUE TITLE
Track expense-App crashes when submitting a track expense to someone

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46181] opened 2024-07-25 12:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** y 
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4764744
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  applause internal team
**Slack conversation:**

## Action Performed:
1. Login with a new gmail account
2. Navigate to the Self DM
3. Click on the + on the compose box
4. Choose Track expense
5. Create a manual expense of any amount
6. On the actionable whisper options of the track expense, click on "Submit to someone"
7. When you are brought to the participant selector, start typing an email address

## Expected Result:
User is able to select an email address and finish the flow of submitting to someone

## Actual Result:
App crashes

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/66ccfa1d-1a4a-43f5-8a8c-77f2230715d3

[Bug6552370_1721896458336!staging.new.expensify.com-1721896427037.txt](https://github.com/user-attachments/files/16377741/Bug6552370_1721896458336.staging.new.expensify.com-1721896427037.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-25 12:41
We think that this bug might be related to  #vip-vsb

**Comment by MariaHCD** [comment] 2024-07-25 14:45
Was able to reproduce the bug on staging, looks like the API call to SearchForReports failed, in my case it worked for the first few times but then later errored and returned no response:

![Screenshot 2024-07-25 at 6 45 00 PM](https://github.com/user-attachments/assets/01a58854-535b-4867-8808-f0f28a7a1826)

![Screenshot 2024-07-25 at 6 43 12 PM](https://github.com/user-attachments/assets/fc49ca45-a254-43a8-a599-86743402c3ab)

[Internal logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22SearchForReports%22%20AND%20email%3A%22maria%40expensifail.com%22%20AND%20timestamp%3A%5B2024-07-25T14%3A40%20TO%202024-07-26T23%3A59%5D)

**Comment by NikkiWines** [comment] 2024-07-25 15:03
I can reproduce it on dev, but found this PR on the most recent deploy that literally aims to fix this bug https://github.com/Expensify/App/pull/45994

Given that I don't think this is a web deploy blocker (or even a newDot blocker, I just think the bug is not wholly fixed.

**Comment by NikkiWines** [comment] 2024-07-25 17:08
Weirdly, I'm no longer able to reproduce this on staging or dev 🤔

**Comment by nkdengineer** [comment] 2024-07-25 17:10
I tried and was also not able to reproduce this bug.

**Comment by NikkiWines** [comment] 2024-07-25 17:20
Asked for a re-test [here](https://expensify.slack.com/archives/C9YU7BX5M/p1721927326277539)

**Comment by m-natarajan** [comment] 2024-07-25 18:02
Tester is able to reproduce the bug. Attaching new video and it is happening only in gmail acounts

https://github.com/user-attachments/assets/b096e70b-005d-451a-8a99-efd50e6ec2ce

**Comment by francoisl** [comment] 2024-07-25 18:15
Can't reproduce either locally. The console error in the video above points to [this line](https://github.com/Expensify/App/blob/266d4cbc61b8fc6/src/pages/home/report/ReportActionItem.tsx#L224), though the surrounding code hasn't been changed in a while.
I wonder if it's a backend issue though, like some API command changed the response format for a whisper report action and no longer includes a `resolution`?

**Comment by NikkiWines** [comment] 2024-07-25 20:47
Oh, good thinking @francoisl. @tgolen, I see you in the code for some of the logic related to `resolution` in the whisper reportActions (albeit from a while ago). Do you happen to know of anything that has changed recently in that logic?

**Comment by mountiny** [comment] 2024-07-25 21:10
I think I have just run into something similar in staging https://expensify.slack.com/archives/C049HHMV9SM/p1721940861100039

**Comment by NikkiWines** [comment] 2024-07-25 21:34
> actually the type of reportAction.message is string for ACTIONABLE_MENTION_WHISPER, originalMessage seems depriciated.

`originalMessage` has been deprecated for a while now though (since [here](https://github.com/Expensify/App/pull/40168))

**Comment by francoisl** [comment] 2024-07-25 21:51
I don't understand how `originalMessage` gets to be a string in the first place - can you tell if the stringified message you got [here](https://github.com/Expensify/App/issues/46181#issuecomment-2251416249) was returned by `TrackExpense` or something else?

I just tried the `TrackExpense` API from production and staging, and the backend returns the same format for both

```json
{
  "key": "reportActions_2308535023239471",
  "onyxMethod": "merge",
  "value": {
    "983660383098354030": {
      "actionName": "ACTIONABLETRACKEXPENSEWHISPER",
      "actorAccountID": 8392101,
      "avatar": "https://d1wpcgnaa73g0y.cloudfront.net/894b50e60056c966d12216005fbcacec8ce5a2c0.png",
      "created": "2024-07-25 21:41:48.670",
      "lastModified": "2024-07-25 21:41:48.670",
      "message": [
        {
          "html": "What would you like to do with this expense?",
          "text": "What would you like to do with this expense?",
          "type": "COMMENT",
          "whisperedTo": []
        }
      ],
      "originalMessage": {
        "html": "What would you like to do with this expense?",
        "lastModified": "2024-07-25 21:41:48.670",
        "transactionID": "4621430576663691334"
      },
      "person": [
        {
          "style": "strong",
          "text": "Expensify Concierge",
          "type": "TEXT"
        }
      ],
      "previousReportActionID": "3201231829538080024",
      "reportActionID": "983660383098354030",
      "shouldShow": true
    }
  }
}
```

**Comment by rlinoz** [comment] 2024-07-25 21:53
It is from SearchForReports

```
"reportActions_8326091604995297": {
          "932416413244753707": {
            "action": "ACTIONABLETRACKEXPENSEWHISPER",
            "actorAccountID": 1,
            "actorEmail": "concierge@expensify.com",
            "created": "2024-07-25 20:56:55.686",
            "message": "{\"html\":\"What would you like to do with this expense?\",\"lastModified\":\"2024-07-25 20:56:55.686\",\"transactionID\":\"146406399869489744\"}",
            "reportActionID": 932416413244753700
          },
```

**Comment by rlinoz** [comment] 2024-07-25 21:56
I think it is coming from here: https://github.com/Expensify/Web-Expensify/pull/42853/files#diff-7a032f7284c8b42392fb9715c5196b05b34ebeb369ee31387f702a26980eb792R6566

It works correctly in the OpenReport flow, but not in the SearchForReports

**Comment by francoisl** [comment] 2024-07-25 22:00
Ooooh great find - you have to search for **your own email** to be able to reproduce. 

That PR was deployed to production 6 hours ago and I can repro the crash on production too. We should probably revert it tbh.

**Comment by francoisl** [comment] 2024-07-25 22:28
We're going to cherry-pick a backend fix for this to staging and production now.

Thanks @ishpaul777 and @rlinoz for helping look into this 🙌

**Comment by NikkiWines** [comment] 2024-07-25 22:45
CP has installed on prod 👍

**Comment by NikkiWines** [comment] 2024-07-25 22:46
@francoisl confirmed [here](https://expensify.slack.com/archives/C07J32337/p1721947555814959?thread_ts=1721945877.129709&cid=C07J32337) that this resolved the issue 🎊 🚀 ❤️

**Closed by NikkiWines** 2024-07-25 22:46 UTC
Labels: Engineering, Daily, Bug
