### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] mweb-LHN-Mark as unread a message after deleting self mention displays green dot in LHN.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40469] opened 2024-04-18 15:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open self DM report
3. Mention self and send it
4. Send another message
5. Delete the previous DM message
6. Navigate to LHN
7. Long press the report in LHN and select mark as unread
## Expected Result:
Mark as unread a message after deleting self mention must not display green dot in LHN.

## Actual Result:
Mark as unread a message after deleting self mention displays green dot in LHN.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/77db8ab9-2874-4a85-8b47-1e8fa36d5a98

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e421f5653f9e5c16</li>
        <li>Upwork Job ID: 1783272895128035328</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by m-natarajan** [comment] 2024-04-18 15:24
@twisterdotcom FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-04-18 15:24
We think this bug might be related to #vip-vsb

**Comment by twisterdotcom** [comment] 2024-04-19 14:54
A mobile web bug for an uncommon flow, this is niche.

**Comment by hungvu193** [comment] 2024-04-26 08:34
I'll review this one tomorrow.

**Comment by hungvu193** [comment] 2024-04-27 13:33
@tienifr 's [main solution here](https://github.com/Expensify/App/issues/40469#issuecomment-2076296447) looks good to me! 🎀 👀 🎀  C+ reviewed.

**Comment by twisterdotcom** [comment] 2024-04-30 12:54
Bump @neil-marcellini

**Comment by hungvu193** [comment] 2024-05-03 02:38
Bump @neil-marcellini

**Comment by neil-marcellini** [comment] 2024-05-08 19:14
Sorry somehow I lost track of this one. Looking now.

**Comment by neil-marcellini** [comment] 2024-05-08 19:24
> @tienifr 's [main solution here](https://github.com/Expensify/App/issues/40469#issuecomment-2076296447) looks good to me! 🎀 👀 🎀 C+ reviewed.

I agree, let's do it. Let's also use the plan in 3.b
> 3\. b. Or look for the latest mention report action that mentions this user, and optimistically set the `lastMentionedTime` to that one instead. If there's no such mention report action, set `lastMentionedTime` to null/empty


 @tienifr please let me know via DM if backend changes are needed too, it sounds like they probably are.

**Comment by hungvu193** [comment] 2024-05-19 14:34
Still working on the PR.

**Comment by neil-marcellini** [comment] 2024-06-04 17:08
I'll try to squeeze this in today

**Comment by neil-marcellini** [comment] 2024-06-05 01:28
I got a draft PR up, still a lot of work to do though

**Comment by neil-marcellini** [comment] 2024-06-05 23:57
I got an automated test passing in the backend for this case. My next steps are to test manually with the contributor's App PR. After that I want to add an automated test to make sure it works when there are multiple mentions. Then I want to manually test some more complex cases in a report with multiple users and varying mentions. If I find real problems there I will make the backend handle that too.

Right now it's only update the lastMentionedTime for the user who deletes the comment, but I'm pretty sure deleting a comment could effect all users mentioned in it.

**Comment by neil-marcellini** [comment] 2024-06-08 05:05
Notes to self:
Manually testing this exact case in app worked well and it's fixed, even without a frontend PR. I tested some more complicated cases like mentioning another user in a public report and I verified that it causes the green dot to show incorrectly. I also encountered an error with OpenReport after these cases, and fixed that.

Next time I can start writing some automated tests for these more involved cases, then work on a query to make it all work. I'm thinking I won't send the Onyx updates until a user marks it as unread, but I will save the data right away for consistency.

**Comment by neil-marcellini** [comment] 2024-06-11 16:27
Yesterday I wrote a test for a slightly more complicated case and updated the query to set the last mentioned time for all users in the mention. Finding the last read time and doing the update now happens in one query. I'm also changing it to only send the Onyx update when a user marks the report as unread, because that's the only flow where it's used in App right now and OpenReport will update lastMentionedTime as well.

Before I write more tests I should get the query timed to make sure it's going to be fast enough. I'm concerned that it will not be since I think it involves scanning over all report actions. If it's too slow we might need a totally different approach towards mention data storage.

**Comment by twisterdotcom** [comment] 2024-06-20 16:10
How is this going @neil-marcellini?

**Comment by neil-marcellini** [comment] 2024-06-24 18:23
I've been concerned that the query to fix this on the backend won't scale, so I brought that up [in #engineering-chat today](https://expensify.slack.com/archives/C03TQ48KC/p1719245178288589). After some discussion we decided that the only way to make this efficient is to change the storage format for mentions, and agreed that it's not worth doing so to fix this edge case. So we're going to do nothing on the backend.

However, I think we can still go ahead with the [frontend fix](https://github.com/Expensify/App/pull/41888) because it looks like it solves this exact case and only has a bug in an even more extreme edge case [described here](https://github.com/Expensify/App/pull/41888#issuecomment-2123776605).

**Comment by neil-marcellini** [comment] 2024-06-24 18:25
@tienifr @hungvu193 would you please get the conflicts resolved, retest the PR, and get it ready to merge?

**Comment by hungvu193** [comment] 2024-07-03 08:40
@neil-marcellini Conflicts resolved, can you take a look at the PR please?

**Comment by neil-marcellini** [comment] 2024-07-03 21:06
Taking a look!

**Comment by neil-marcellini** [comment] 2024-07-17 19:35
Turns out it's a backend bug though, and we already said above we're not going to fix that. Hopefully we can get this merged soon.

**Comment by neil-marcellini** [comment] 2024-07-23 23:35
The PR was merged today, finally!

**Comment by hungvu193** [comment] 2024-08-01 06:55
- [x] The PR that introduced the bug has been identified. Link to the PR: I can't really find the offending PR as this is an extremely edge case. See [this comment](https://github.com/Expensify/App/issues/40469#issuecomment-2187157344).
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: Yes

**Regression Test**:
1. Open App.
2. Open self DM report.
3. Mention yourself and send it.
4. Send another message.
5. Delete the previous DM message.
6. Navigate to LHN.
7. Long press the report in LHN and select mark as unread.
8. Verify mark as unread a message after deleting self mention must not display green dot in LHN.

**Comment by twisterdotcom** [comment] 2024-08-02 11:50
Payment Summary:

- @hungvu193 paid $250 via NewDot Manual Request (Reviewer)
- @tienifr paid $250 via NewDot Manual Request (Contributor)

**Closed** 2024-08-02 11:50 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-07 00:00
$250 approved for @hungvu193

**Comment by JmillsExpensify** [comment] 2024-08-14 18:40
$250 approved for @tienifr
