### ISSUE TITLE
Сhat - Message deleted in offline are not striked out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52344] opened 2024-11-11 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go offline
3. Open a report
4. Send a message
5. Delete the message

## Expected Result:
Message deleted in offline must be striked out

## Actual Result:
Message deleted in offline are not striked out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/6083749b-999b-4dca-a15d-9f2ecd6650c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-11-12 11:08
This can be expected BTW. If the user created and deleted a message offline there is no need to show it or even send the create and delete API requests to the BE.

**Comment by kadiealexander** [comment] 2024-11-12 23:04
This does seem like expected behaviour. Closing as not a bug, please reopen if you disagree.

**Comment by IuliiaHerets** [comment] 2024-11-19 11:11
I created a new issue as it is a deploy blocker for build v9.0.64-0, issue happens only on MacOS #52753

**Comment by kadiealexander** [comment] 2024-11-20 03:59
Android <> iOS bug swap with @jliexpensify

**Comment by jliexpensify** [comment] 2024-11-20 04:52
@IuliiaHerets - can you confirm this is a Chrome/Safari issue only? Not an Android one?

**Comment by jliexpensify** [comment] 2024-11-20 04:52
It also seems like we could close this in favour of https://github.com/Expensify/App/issues/52753?

**Closed by jliexpensify** 2024-11-20 04:52 UTC
Labels: Daily, Bug

**Comment by IuliiaHerets** [comment] 2024-11-20 12:07
@jliexpensify Yes, issue has happened only on MacOS (Safari, Chrome and Desktop).
