### ISSUE TITLE
Tax - Split scan - Selected tax rate is duplicated in Tax rate list

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42642] opened 2024-05-27 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #40240 
**Version Number:** 1.4.76-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace is tax enabled.
- Workspace currency default and Foreign currency default have different tax rate in workspace tax settings.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a split scan.
4. When the receipt is scanning, click on the split preview.
5. Click Amount.
6. Change the currency to foreign currency.
7. Enter amount and save it.
8. Click Tax rate.
## Expected Result:
The selected tax rate will not be duplicated.
## Actual Result:
The selected tax rate is duplicated.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/Expensify/App/assets/38435837/e9c3d55c-f53b-47e3-ad53-1c07e6acf50c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by m-natarajan** [comment] 2024-05-27 15:21
@blimpich FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by blimpich** [comment] 2024-05-27 17:43
Looking into this

**Comment by blimpich** [comment] 2024-05-27 17:45
I don't think this is worth blocking the deploy, demoting.

**Comment by blimpich** [comment] 2024-05-27 17:50
@MonilBhavsar I think this is related to https://github.com/Expensify/App/pull/40240. Do you want to take this over? Otherwise I think we can just open this up to contributors.

**Comment by blimpich** [comment] 2024-05-27 20:06
@cretadn22 if this wasn't caused by https://github.com/Expensify/App/pull/40240 then what did cause this? Please explain why you think this specifically isn't a regression

**Comment by bondydaa** [comment] 2024-05-27 21:54
the revert https://github.com/Expensify/App/pull/42670 has been deployed, please retest and confirm this is no longer reproducible.

**Comment by blimpich** [comment] 2024-05-27 22:45
cc: @m-natarajan, can you see if this still reproduces?

**Comment by kavimuru** [comment] 2024-05-28 02:20
This bug is not reproducible

**Comment by Christinadobrzyn** [comment] 2024-05-28 03:21
I also can't reproduce this issue. I think we can close this. Feel free to let me know if I'm missing anything!

**Comment by MonilBhavsar** [comment] 2024-05-29 12:44
I think we should pay @cretadn22 $100 for investigating the root cause of this and other related issues.
I think it helped to revert the PR in timely manner and move forward with the deploy. Also it saved me some time fixing the bugs in a follow up PR. cc @Christinadobrzyn @blimpich @bondydaa 

Comments:
https://github.com/Expensify/App/issues/42642#issuecomment-2133904885
https://github.com/Expensify/App/issues/42649#issuecomment-2133883092
https://github.com/Expensify/App/issues/42652#issuecomment-2133890225
https://github.com/Expensify/App/issues/42655#issuecomment-2134039388

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:19
checking with @MonilBhavsar on your request @cretadn22

**Comment by MonilBhavsar** [comment] 2024-06-06 09:12
I can't think of a reason why we should not. So I'm fine with paying it. Fine with what others has to say 👍

**Comment by blimpich** [comment] 2024-06-06 19:54
Sounds good to me 👍

@Christinadobrzyn can we pay out $250 to @cretadn22 and then close this issue?

**Comment by Christinadobrzyn** [comment] 2024-06-07 04:13
Yep! Payouts due:

- [ ] Contributor: $250 @cretadn22 (upwork offer - https://www.upwork.com/nx/wm/offer/102634283)

Upwork job is [here](https://www.upwork.com/jobs/~01c4f16cd98005fd50).

@cretadn22 can you accept? TY!

**Comment by Christinadobrzyn** [comment] 2024-06-10 06:25
Thanks @cretadn22  - Paid out based on this payment summary - https://github.com/Expensify/App/issues/42642#issuecomment-2153877842

Closing!

**Closed** 2024-06-10 06:25 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
