### ISSUE TITLE
[HOLD] [$500] Currency list for request money/send money not up to date

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29822] opened 2023-10-17 19:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697535573916749

## Action Performed:
1. Open the app
2. Click on green plus and click on request money/send money
3. Click on select currency
4. Search 'AED' or 'AWG' and observe that we don't have symbols for them
5. Go to settings->workspaces->any workspace->settings->default currency
6. Search for 'AED' or 'AWG' and observe that we have symbols for them in that currency list
## Expected Result: 
Currency list should be upto date throughout the app
## Actual Result: 
Currency list of request money/ send money has many missing symbols and is not upto date as workspace default currency list

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/6b8fa34d-1dc6-4fca-8360-81490691988b

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/f1a8328d-0d7e-456f-b694-fd872ff5d512

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/74ee2fa2-5fb3-41f1-8738-e282dd56c06d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/d306703d-41cf-4383-8ebb-3a6bc8ea915d

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/6c28e73e-b84f-42fc-bb5d-a2a7db5fc921

https://github.com/Expensify/App/assets/38435837/1138619d-28c8-4384-9be6-07c1d56d6113

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/29c13654-e800-4259-9208-369f5ed4b400

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01726365c65211c39c</li>
        <li>Upwork Job ID: 1714364607492071424</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by rakshitjain13** [comment] 2023-10-17 19:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Currency list for request money/send money not up to date

### What is the root cause of that problem?
There is inconsistency about how to show text in the list
1) In Request money [link](https://github.com/Expensify/App/blob/12d366931012b0092b924b688924726930398ac4/src/pages/iou/IOUCurrencySelection.js#L99)
2) In selecting the default currency for the workspace [link](https://github.com/Expensify/App/blob/12d366931012b0092b924b688924726930398ac4/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L58)
Above use the concept of [link](https://github.com/Expensify/App/blob/12d366931012b0092b924b688924726930398ac4/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L34)

### What changes do you think we should make in order to solve the problem?
We should implement the same logic as we implemented in selecting the default currency for the workspace, i.e., 2 points above

### What alternative solutions did you explore? (Optional)
NA

**Comment by AliYar-Khan** [comment] 2023-10-18 09:58
### Proposal 
### Please re-state the problem that we are trying to solve in this issue.
Currency list for request money/send money not upto date. Missing currency symbols

### What is the root cause of that problem?
We have inconsistency in the code at both locations where currency with symbols are being placed:
1. https://github.com/Expensify/App/blob/12d366931012b0092b924b688924726930398ac4/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L58

2. https://github.com/Expensify/App/blob/12d366931012b0092b924b688924726930398ac4/src/pages/iou/IOUCurrencySelection.js#L99

 
### What changes do you think we should make in order to solve the problem?
use the workspace settings method we will get the same results i.e currency code with symbols

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2023-10-19 04:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Currency list for request money/send money not upto date 

### What is the root cause of that problem?
1. In Request Money Flow, we use localized symbol for currency
2. In the workspace, we use normal symbol for currency
It causes the consistency
### What changes do you think we should make in order to solve the problem?


we had both functions to get normal symbol and localized symbol
https://github.com/Expensify/App/blob/b38171d0374d52e49ac5131363f920c48ea36eb7/src/libs/CurrencyUtils.ts#L45
and 
https://github.com/Expensify/App/blob/b38171d0374d52e49ac5131363f920c48ea36eb7/src/libs/CurrencyUtils.ts#L56

First, we need to confirm that we should use normal or localized symbol? And then use that function in the both places to avoid consistency

**Comment by DylanDylann** [comment] 2023-10-19 04:21
@shawnborton 
1. In Request Money Flow, we use localized symbol for currency
2. In the workspace, we use normal symbol for currency
It causes the consistency. So we need to confirm that we should use a normal or localized symbol for both places? Could you help to give some UX perspective? 
cc @miljakljajic

**Comment by shawnborton** [comment] 2023-10-19 11:53
Can you show me an image with a difference between the two? 

I think I lean towards having a local symbol, or however is most common to show that symbol before a numerical amount.

**Comment by DylanDylann** [comment] 2023-10-20 04:10
1. This is localized symbol
<img width="1440" alt="Screenshot 2023-10-20 at 11 09 37" src="https://github.com/Expensify/App/assets/141406735/237ca75b-ed60-4864-9c2e-6dbf65184833">


2. This is a normal symbol
<img width="1439" alt="Screenshot 2023-10-20 at 11 09 16" src="https://github.com/Expensify/App/assets/141406735/92131641-071d-4545-9a6d-0a01965c68b8">

**Comment by robertKozik** [comment] 2023-10-20 08:17
@shawnborton waiting for your input. about what kind of symbol is preferable for currency

**Comment by shawnborton** [comment] 2023-10-20 13:20
Hmm @JmillsExpensify @trjExpensify @Expensify/design do you have a strong opinion? The "normal symbol" from above feels nicer to me.

**Comment by dubielzyk-expensify** [comment] 2023-10-22 23:31
+1 to the "Normal"

**Comment by DylanDylann** [comment] 2023-10-23 07:37
@robertKozik [Updated proposal](https://github.com/Expensify/App/issues/29822#issuecomment-1769865854)

**Comment by trjExpensify** [comment] 2023-10-23 18:37
I don't have a strong preference in the picker, but if we use the "normal" symbol, does that mean that someone not in the US can't distinguish between USD and CAD on a request sent to them for example? 

I'm trying to reconcile why we have two different currency lists being used in the first place, and this "local" solution to me sounds like it was something to do with this: 

>[here](https://github.com/Expensify/App/blob/12d366931012b0092b924b688924726930398ac4/src/pages/iou/IOUCurrencySelection.js#L99) we are using getLocalizedCurrencySymbol to get Currency symbol, which uses Locale, defines which Symbol to use based on locality. for example for the US Dollar, the symbol is "$" if the default locale is the US, while for other locales it may be "US$". If no symbol can be determined, the ISO 4217 currency code is returned.

So my question is whether this has a wider impact on where we show a currency symbol in the app, not just the pickers shown [here](https://github.com/Expensify/App/issues/29822#issuecomment-1772048930).

**Comment by DylanDylann** [comment] 2023-10-26 04:07
@shawnborton @dubielzyk-expensify Could you help to check this comment https://github.com/Expensify/App/issues/29822#issuecomment-1775789973 ? And then decide the final decision

**Comment by dubielzyk-expensify** [comment] 2023-10-26 11:51
I was referring to the picker only. If changing it to "normal" in the picker has wider ramifications, then I'd say use localized symbol. @shawnborton will know this area better though

**Comment by shawnborton** [comment] 2023-10-26 11:52
Hmm this is a good point:

> does that mean that someone not in the US can't distinguish between USD and CAD on a request sent to them for example?

At the same time, if you are local to Canada and you see just a $, wouldn't you be used to that and assume it's local currency?

**Comment by DylanDylann** [comment] 2023-10-30 08:30
@trjExpensify @shawnborton @dubielzyk-expensify Could you guys help to confirm our final decision?

**Comment by dubielzyk-expensify** [comment] 2023-10-30 10:05
If this is for the picker only let's go with the simplified symbol due to it having the full currency next to it. So number `2` in [this comment](https://github.com/Expensify/App/issues/29822#issuecomment-1772048930). If this becomes an issue we'll fix it.

**Comment by trjExpensify** [comment] 2023-10-30 14:22
Sorry folks, I was out for a few days last week. 

>@trjExpensify @shawnborton @dubielzyk-expensify Could you guys help to confirm our final decision?

I don't think the question from earlier was answered @DylanDylann. Can you confirm this change only impacts the display of the currencies in the currency pickers? If not, can the proposal show the impact of these changes proposed where currency symbols are displayed in the product holistically. I.e on a request, in an expense/iouReport preview, the expense/iouReport header, payment button etc.

**Comment by DylanDylann** [comment] 2023-10-30 14:47
@trjExpensify 
> So my question is whether this has a wider impact on where we show a currency symbol in the app, not just the pickers shown https://github.com/Expensify/App/issues/29822#issuecomment-1772048930.

[My solution](https://github.com/Expensify/App/issues/29822#issuecomment-1769865854) will make change only be in 2 pickers [here](https://github.com/Expensify/App/issues/29822#issuecomment-1772048930) and there are no impact on other places

**Comment by trjExpensify** [comment] 2023-10-30 15:36
Perfect, then let's go with #2 then as the preference for the display in the pickers. 👍

**Comment by DylanDylann** [comment] 2023-10-30 15:53
@robertKozik We discussed and decided to display normal symbol in the picker. Could you help to take a look at my proposal https://github.com/Expensify/App/issues/29822#issuecomment-1769865854 ?

**Comment by rakshitjain13** [comment] 2023-10-30 16:55
We have to also update if we go with the normal symbol https://github.com/Expensify/App/blob/6389c2d47b3bd21ab6cd9547e510721593d645d3/src/components/TextInputWithCurrencySymbol/BaseTextInputWithCurrencySymbol.js#L11 
with 
```
const currencySymbol = props.currencyList[props.selectedCurrencyCode].symbol;
```
and currencyList will be passed as 
```
export default compose(
    withOnyx({
        currencyList: {key: ONYXKEYS.CURRENCY_LIST},
    }),
)(BaseTextInputWithCurrencySymbolWithRef);
```

Thus updating my proposal https://github.com/Expensify/App/issues/29822#issuecomment-1767047432

**Comment by miljakljajic** [comment] 2023-11-02 15:15
@robertKozik any thoughts on @Charan-hs 's proposal?

**Comment by rakshitjain13** [comment] 2023-11-02 15:28
@miljakljajic @robertKozik In my proposal https://github.com/Expensify/App/issues/29822#issuecomment-1767047432 I implemented something which I was not aware that there is same function exists for that in that file , :) new to the codebase. Thanks @Charan-hs for putting that function . I will be happy no matter who's proposal is selected.

**Comment by sonialiap** [comment] 2023-11-03 12:08
@robertKozik a new issue was just opened that looks mighty similar to this one. What do you think, are they the same issue? https://github.com/Expensify/App/issues/30595

**Comment by DylanDylann** [comment] 2023-11-08 10:56
@robertKozik We confirmed the final decision here](https://github.com/Expensify/App/issues/29822#issuecomment-1785483428). Could you help to take a look at proposals?

**Comment by DylanDylann** [comment] 2023-11-09 14:38
@robertKozik In [my proposal](https://github.com/Expensify/App/issues/29822#issuecomment-1769865854), I suggest we should update to use getCurrencySymbol in both places to make it consistency in both places. In @Charan-hs's proposal we only use getCurrencySymbol in IOUCurrencySelection.js and retain old logic in WorkspaceSettingsCurrencyPage.js, It will make inconsistency in some cases. One more thing, besides spending time proposing solution, I also spend time to follow and support internal team to make correct decision

**Comment by robertKozik** [comment] 2023-11-09 16:40
I greatly appreciate your support and your participation in the ongoing discussion about the expected behavior. However, I had to choose the proposal solely based on its merits. The selected proposal suggests the same approach as yours, and it also mentions changes within the workspace settings page in the alternative solutions section.
> In workspace we can update to use getLocalizedCurrencySymbol to get the currency symbol.

**Comment by cead22** [comment] 2023-11-09 18:09
I'm a little confused about this issue, because the root cause of the problem sounds like desired behavior to me: we should use the localized version of currency symbols.

Moreover, I don't know if the proposal does this, but it should also consider the behavior of other currency selectors and ideally make them all consistent, unless there are good reasons for having different behavior.

That said, I think it's possible this issue will be solved by the proposal presented for this issue https://github.com/Expensify/App/issues/29618#issuecomment-1785638160 which is to

>make a new component: CurrencySelectionList based on the currency selection list of the IOU Request and use it in IOU request and in the workspace default currency setting.

So I suggest we put this issue on HOLD until that other one is resolved

> Sorry for the delay in there. I believe that it's not a dupe. It's very similar issue but it refers different screen - In my opinion each screen should be referenced separately as there is a possibility that we would want to treat them differently.

I think what I'm saying is in disagreement with this, and we should start thinking more holistically about the whole product and all the screens, and only have different behavior when we've identified a good reason to treat them differently, and not based on the possibility that we want to treat them differently. 

Given that, I suggest we close this issue https://github.com/Expensify/App/issues/30595, or at minimum, put it on holdhttps://github.com/Expensify/App/issues/30595

**Comment by miljakljajic** [comment] 2023-11-13 12:12
I agree @cead22 - @sonialiap with that in mind do you want to close out your issue? We can put this one on hold until #29618 is resolved.

**Comment by sonialiap** [comment] 2023-11-13 13:40
Sounds good, closing out 30595

**Comment by cead22** [comment] 2023-11-20 18:22
Still on hold

**Comment by cead22** [comment] 2023-11-30 23:52
This is still on hold

**Comment by miljakljajic** [comment] 2023-12-04 10:51
Not overdue - moved to weekly

**Comment by miljakljajic** [comment] 2023-12-12 13:45
Holding

**Comment by miljakljajic** [comment] 2023-12-22 12:53
Holding

**Comment by miljakljajic** [comment] 2024-01-03 11:18
Holding

**Comment by cead22** [comment] 2024-01-15 21:42
Still on hold

**Comment by s77rt** [comment] 2024-01-16 23:59
Taking this as C+. @cead22 Please assign me here

**Comment by cead22** [comment] 2024-01-17 02:08
Which PR? Isn't it this one https://github.com/Expensify/App/pull/30889?

**Comment by s77rt** [comment] 2024-01-17 02:17
I think we are still holding on that PR. I'm filling for @robertKozik in case that PR didn't fix this issue we will continue here

**Comment by DylanDylann** [comment] 2024-01-17 02:45
The PR https://github.com/Expensify/App/pull/30889 has been delayed for a long time. @cead22 Could you help to push up it

**Comment by cead22** [comment] 2024-01-20 02:14
I DM'd Rajat. If we don't get a review on Monday, we can ask for another C+

**Comment by miljakljajic** [comment] 2024-01-29 13:04
How we doing on this one?

**Comment by miljakljajic** [comment] 2024-02-07 16:35
Moving along on https://github.com/Expensify/App/pull/30889 - shouldnt be long now

**Comment by miljakljajic** [comment] 2024-02-19 12:02
still waiting

**Comment by cead22** [comment] 2024-02-27 23:56
On hold, not overdue

**Comment by cead22** [comment] 2024-03-13 00:47
It looks like this is on hold for an issue that's on hold for another issue... and so on a so forth. I'm gonna make this monthly. I thought about closing but that probably means a new issue will get opened for the same thing

**Comment by s77rt** [comment] 2024-03-28 13:35
@cead22 or @miljakljajic Can you please assign me? I'm taking this as C+ replacing @robertKozik

**Comment by DylanDylann** [comment] 2024-05-06 03:17
https://github.com/Expensify/App/pull/30889 is merged, this issue can't be reproduced anymore

**Closed** 2024-05-06 18:51 UTC
Labels: External, Engineering, Monthly, Overdue, Bug

**Comment by dhanashree-sawant** [comment] 2024-05-07 03:09
Hi @s77rt , @cead22 is this job eligible for reporting bonus?

**Comment by mallenexpensify** [comment] 2024-05-07 19:26
Unfortunately not @dhanashree-sawant .  The PR that fixed this was from a bug issue that was reported 3 days before your report. https://github.com/Expensify/App/issues/29618

There wasn't a PR raised for this one, it was just on hold (for forever).
