### ISSUE TITLE
 Web -LHN - LHN doesn't reflect report value before click

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21620] opened 2023-06-26 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1, Click on FAB menu
2. Click on split bill button
3. Click Enter amount
4. Search & select multiple user
5. Click on split button
6. Click on one of the newly created reports from LHN

## Expected Result:
LHN should reflect report value before click

## Actual Result:
LHN reflects report value after a click on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cd701d08-b7f1-40fa-8eed-f611d860628b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687456348210999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shivam7-1** [comment] 2023-06-27 09:14
## Proposal

### LHN reflects report value after a click on LHN

## Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?
The issue in the code is that the Left Hand Navigation (LHN) does not reflect the report value before clicking on it. Currently, it updates the LHN after a click on the report. 
This happens in `SplitBillDetailsPage.js` code file
In this code file `SplitBillDetailsPage` Function Given this error in UI

### What changes do you think we should make in order to solve the problem?
In Solution of this issue The code can modify as follows:

1. In the `withReportOrNotFound` HOC (Higher Order Component), update the `reportActions` prop to fetch the report actions for the given report ID before rendering the component. This will ensure that the report actions are available in the component's props when it mounts.

2. Update the `SplitBillDetailsPage` component to handle the case where the report or report action is not found. In the case where the report or report action is not found, display an appropriate error message or fallback UI.



By making these changes, the `SplitBillDetailsPage` component will receive the `reportActions` prop with the necessary data before rendering. It will also handle the case where the report action is not found and display an appropriate error message or fallback UI.

**Comment by jjcoffee** [comment] 2023-06-27 10:23
Not reproducible in v1.3.33-3.

**Comment by Natnael-Guchima** [comment] 2023-06-27 10:29
@jjcoffee It is still reproducible. The reports that are affected are not the ones with GBR. 

[Screencast from 2023-06-27 13-26-49.webm](https://github.com/Expensify/App/assets/57330233/f24ba67b-a0a4-4067-99c2-d24c45f26632)

**Comment by dylanexpensify** [comment] 2023-06-28 10:39
Clarifying something in channel

**Comment by Natnael-Guchima** [comment] 2023-06-30 10:40
@dylanexpensify I think the issue is fixed on the latest build. I will check again and let you know if it is fixed or not.

**Comment by dylanexpensify** [comment] 2023-07-03 08:48
reviewing today and posting next steps!

**Comment by dylanexpensify** [comment] 2023-07-04 11:19
agreed, i believe this is fixed!

**Closed by dylanexpensify** 2023-07-04 11:19 UTC
Labels: Daily, Needs Reproduction, Bug
