### ISSUE TITLE
[$1000] Mweb - Compose box - Text formatting of turning message into code and heading is not applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22974] opened 2023-07-16 16:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/

2. Tap on a conversation
3. Paste the below text
The *56* _boy_ ran to ~dark~

`The *56* _boy_ ran to ~dark~`

#heading
4.Tap Send

## Expected Result:
Text formatting of turning message into code and heading must be applied in send messages

## Actual Result:
In second and third line, text pasted, we can note that text formatting of turning message into code and heading is not applied in send messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/94bc479e-208b-4afa-95d8-1cf7e6dd0a95

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ee5fb2a54595e92</li>
        <li>Upwork Job ID: 1680975259918938112</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by med-lean** [comment] 2023-07-17 20:03
@maddylewis I investigated the issue, and I am not able to reproduce the issue. For code transformation, it is working all fine: 
![image](https://github.com/Expensify/App/assets/137059293/963df8d6-a1c5-4e52-bb34-20be72a8f7cd)
![image](https://github.com/Expensify/App/assets/137059293/c810312d-cf82-45e6-937e-f8dec1e983a8)

However, for heading, the only issue is that we need a space between the text and the dash to preview it as a title. instead of #heading try *# heading*

I hope this is not an issue.

**Comment by makiour** [comment] 2023-07-17 20:03
Hey @maddylewis,

I investigated the issue, and I am not able to reproduce the issue. For code transformation, it is working all fine: 
![image](https://github.com/Expensify/App/assets/137059293/963df8d6-a1c5-4e52-bb34-20be72a8f7cd)
![image](https://github.com/Expensify/App/assets/137059293/c810312d-cf82-45e6-937e-f8dec1e983a8)

However, for heading, the only issue is that we need a space between the text and the dash to preview it as a title. instead of #heading try *# heading*

I hope this is not an issue.

**Comment by Talha345** [comment] 2023-07-17 20:27
Not an issue.

Use the following code:

The *56* _boy_ ran to ~dark~
# heading

Note: Space is required in heading. 

![image](https://github.com/Expensify/App/assets/36226639/e2b6827d-eccb-4a49-a5bb-925ca5227a70)

**Comment by maddylewis** [comment] 2023-07-18 20:21
is someone able to clarify whether the "bug" outlined in this issue is expected behavior or not? should i close this one out or should we be working on a fix for this? 

lmk - thanks!

**Closed** 2023-07-21 18:54 UTC
Labels: External, Daily, Help Wanted, Bug
