### ISSUE TITLE
[$500] Web  - Mark unread disappear after resizing screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22196] opened 2023-07-04 16:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Chat any message
3. Mark as unread with this message, Observe that the message is marked unread
4. Resize the screen to small then back to original size, Observe that mark unread disappears

## Expected Result:
Mark unread doesn't disappear after resizing screen

## Actual Result:
 Mark unread does disappear after resizing screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/10d16e9b-5fea-49cf-b45a-0c03958d33bd

https://github.com/Expensify/App/assets/93399543/49efce21-0f9e-4c98-846c-1cd279c78bd3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688459653534249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1435c5c38ad26aa</li>
        <li>Upwork Job ID: 1698699259737006080</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-07-04 19:09
Related to https://github.com/Expensify/App/issues/21560

@zanyrenney I would hold on exporting this one as solution might be coming from @adamgrzybowski

**Comment by mountiny** [comment] 2023-07-04 19:10
making this weekly for that reason

**Comment by zanyrenney** [comment] 2023-07-14 17:42
Thanks for the update @mountiny - anything else to share on what the latest is?

**Comment by mountiny** [comment] 2023-07-14 19:25
Its on hold for this https://github.com/Expensify/App/pull/22437, waiting for review and tests from C+

**Comment by zanyrenney** [comment] 2023-07-24 11:25
https://github.com/Expensify/App/pull/22437 is still open, so we're still in a holding pattern just now.

**Comment by zanyrenney** [comment] 2023-08-07 17:34
Hey @mountiny - should we take this off hold given the progress here? https://github.com/Expensify/App/pull/22437

**Comment by mountiny** [comment] 2023-08-15 17:27
No, until that is merged and deployed

**Comment by zanyrenney** [comment] 2023-08-15 18:45
Thanks for the @mountiny

**Comment by zanyrenney** [comment] 2023-08-25 13:10
https://github.com/Expensify/App/pull/22437 still not merged and deployed, so still holding here for now.

**Comment by zanyrenney** [comment] 2023-09-04 10:28
hey @mountiny looks like the above got merged 🎉 are we good to start working on this one now or are there any other considerations I need to be aware of being we open this up to contributors? Thanks!

**Comment by mountiny** [comment] 2023-09-04 11:56
@zanyrenney could you please first confirm if its still reproducible in staging? If not, we can pay out reporting bonus and close. Thanks!

**Comment by zanyrenney** [comment] 2023-09-04 14:04
Yep, it's reproducible still! file too big for GH but can slack to you if needed.

**Comment by zanyrenney** [comment] 2023-09-04 14:05
@mountiny

**Comment by mountiny** [comment] 2023-09-04 14:07
@zanyrenney in that case lets export it, thanks!

**Comment by WasilIslam** [comment] 2023-09-04 15:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by WasilIslam** [comment] 2023-09-04 16:02
Contributor details
Your Expensify account email: wasilislam456@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/itengineer

**Comment by mountiny** [comment] 2023-09-04 18:08
I just tried in staging and also cannot reproduce anymore! @zanyrenney unless you can still repro, lets close it

@WasilIslam given your proposal, can you still reproduce?

**Comment by WasilIslam** [comment] 2023-09-04 18:20
The error seems to be gone now in the staging part.

**Comment by mountiny** [comment] 2023-09-05 09:25
@namhihi237 yeah you are eligible for $250 reporting bonus. @zanyrenney can you please help and then we can close! thanks everyone!

**Comment by zanyrenney** [comment] 2023-09-11 08:50
@namhihi237 have invited you to the upwork job, please accept for the payout for reporting bonus.

**Comment by zanyrenney** [comment] 2023-09-11 08:54
**Payment Summary**

[Nam Le Trung](https://github.com/namhihi237) - $250 reporting bonus 

no other payments due as we are closing this one.

**Comment by zanyrenney** [comment] 2023-09-11 09:21
PAID. Closing.

**Closed by zanyrenney** 2023-09-11 09:21 UTC
Labels: External, Daily, Help Wanted, Bug
