### ISSUE TITLE
[Hold for payment 2022-12-06 $250] Default rooms are not grayed out when creating a new workspace while offline

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#12151] opened 2022-10-26 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with any account
2. Go offline
3. Click the green plus at the bottom, New workspace. Or if you already have a workspace click the avatar in the header to open the settings, click on a workspace, click the 3 vertical dots at the top, New workspace.

## Expected Result:
The default rooms, `#admins`, `#announce`, and the workspace expense chat should be grayed out in the LHN and on the search page. When navigating to any of these rooms the whole room should be grayed out (50% opacity).

## Actual Result:
The default rooms are not grayed out (50% opacity).

## Workaround:
Ignore it

## Platform:

All platforms

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.18-10
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/26260477/198112025-cf40f3df-9dbb-4ceb-b93b-bd8a97156a69.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2022-10-31 23:36
Not overdue, engineering triage!

**Comment by strepanier03** [comment] 2022-11-01 00:12
@grgia - Are you recommending the External label on this? Did you triage it as an engineer or am I to triage it as a CM?

**Comment by strepanier03** [comment] 2022-11-01 23:11
Internal job posting: https://www.upwork.com/ab/applicants/1587582985521102848/suggested

----

External job posting: https://www.upwork.com/jobs/~01cf8f22223f210999

**Comment by michaelhaxhiu** [comment] 2022-11-03 22:38
Hey @strepanier03, just dropping a note as a reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out. This was just posted a few days ago so not much more you can do at this moment, but let's get clear on your question for @grgia ([above](https://github.com/Expensify/App/issues/12151#issuecomment-1297840744)):

>@grgia - Are you recommending the External label on this?

**Comment by michaelhaxhiu** [comment] 2022-11-03 22:53
Adding the `daily` label back btw! There's more recent context in slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1667513707424009) for reference.

**Comment by tienifr** [comment] 2022-11-07 10:12
# Proposal
## Problem
In https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/libs/ReportUtils.js#L817-L852

when build the optimistic data for default chat report (admin, announce) we don't set `pendingFields` for them so In https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/components/LHNOptionsList/OptionRowLHN.js#L102

and https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/components/OptionRow.js#L136
the pendingAction is null

=> the logic that enable opacity is not applied

## Solution

In https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/libs/ReportUtils.js#L817
I'll add `pendingFields` with createChat ='add'

```diff
        statusNum: 0,
        visibility,
+        pendingFields: {
+            createChat: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
+        }    
    };
```

https://user-images.githubusercontent.com/113963320/200283688-86463677-4c6c-4c08-b906-a16b5a3e0bdd.mp4

**Comment by strepanier03** [comment] 2022-11-07 19:11
@eVoloshchak - Looks like there is a proposal to review for this. 

When you get a chance please review and if you are okay with the solution ping the CME Monil so they can give their sign off as well.

**Comment by eVoloshchak** [comment] 2022-11-08 17:11
> when build the optimistic data for default chat report (admin, announce) we don't set pendingFields for them

@tienifr, thanks for the proposal, makes sense

> I'll add pendingFields with createChat ='add'

This is indeed resolving the issue. Only thing I'm afraid of is that it will introduce issues with chat creation. @tienifr, we're calling `buildOptimisticChatReport` in a couple of places, is adding `pendingFields` to all of them safe?

**Comment by tienifr** [comment] 2022-11-09 08:32
@eVoloshchak we're using `buildOptimisticChatReport` in 4 places: announceChatData, adminsChatData, expenseChatData, policyReport.
As we can see the result above when pendingFields of announceChatData, adminsChatData, expenseChatData are updated to null when we go online.
Here is the evidence of creating new `policyReport`:

https://user-images.githubusercontent.com/113963320/200779111-921de183-d7b4-4a51-adec-1a7ef7f80742.mp4

**Comment by eVoloshchak** [comment] 2022-11-09 13:15
@tienifr thank you for checking this
> we're using buildOptimisticChatReport in 4 places: announceChatData, adminsChatData, expenseChatData, policyReport.

Correct me if I'm wrong, but I can see it being used in 9 places (in `requestMoney`, `createSplitsAndOnyxData`, `getOrCreateChatReport`, etc)

**Comment by strepanier03** [comment] 2022-11-11 01:34
@tienifr - Just a friendly bump to response to the comment from @eVoloshchak [here](https://github.com/Expensify/App/issues/12151#issuecomment-1308737280). Thanks

I am out of the office tomorrow. If there is an urgent need on this GH from a BugZero team member, please post in #expensify-open-source for assistance.

**Comment by tienifr** [comment] 2022-11-11 09:25
Hi @eVoloshchak We are using buildOptimisticChatReport in 8 places 

In /Expensify/App/src/libs/ReportUtils.js
1. line 901: announceChatData  (for creating workspace )
2. line 917: adminsChatData  (for creating workspace )
3. line 929: expenseChatData   (for creating workspace )
(But after using buildOptimisticChatReport in 3 above places, we update directly to Oynx and don't update pendingField and it causes this issue)

In /Expensify/App/src/libs/actions/IOU.js
4. line 63: chatReport (for creating request money )
5. line 245: groupChatReport (for creating split bill)
6. line 331: oneOnOneChatReport (for creating split bill)


In /Expensify/App/src/libs/actions/Report.js
7. line 569:    newChat = ReportUtils.buildOptimisticChatReport(formattedUserLogins); (for opening and entering chat)
8. line 1057: const policyReport = ReportUtils.buildOptimisticChatReport(...) (for creating room)


--> In 5 above places (4->8) after using buildOptimisticChatReport in 3 places, we update `pendingFields: {createChat: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}` before syncing to Oynx

So I suggest 2 solutions to this problem

### Solution 1
We only update pendingField in the first 3 places (1-->3)

the sample PR: https://github.com/Expensify/App/pull/12664

I tested and it worked correctly


https://user-images.githubusercontent.com/113963320/201303589-cd0defcf-3aba-4be3-bd48-acaa35874e5d.mp4



### Solution 2

In https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/libs/ReportUtils.js#L817
I'll add `pendingFields` with createChat ='add'

```diff
        statusNum: 0,
        visibility,
+        pendingFields: {
+            createChat: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
+        }    
    };
```

and remove updating pendingFields manually in other places (4-->8)
The sample PR: https://github.com/Expensify/App/pull/12663

I tested it in all places and it worked correctly


https://user-images.githubusercontent.com/113963320/201309120-bcde4ab6-b26a-439e-b96c-e791d7c4dbe9.mp4

**Comment by eVoloshchak** [comment] 2022-11-14 14:50
> ### Solution 1
> We only update pendingField in the first 3 places (1-->3)
> the sample PR: #12664

I like @tienifr proposal
I think we should go with the first solution since it adds pending actions only for the rooms we need to be greyed out

@MonilBhavsar, could you help me out, are there any default rooms besides `#admins` and `#announce`? 
The issue description states `The default rooms, #admins, #announce, and the workspace expense`, which implies there are other default rooms

**Comment by strepanier03** [comment] 2022-11-14 22:05
@MonilBhavsar - Just a friendly bump on @eVoloshchak's comment. 

Based on the recreation video in the OP post though, I think the "workspace expense" room is the one named "Workspace", right above the admin and announce rooms. 

<img width="186" alt="2022-11-14_14-04-55" src="https://user-images.githubusercontent.com/10925636/201777807-2541ac1c-7cc8-49db-8e62-02d551ba8562.png">

If you agree with the proposal and hiring @tienifr, just let me know and I'll take care of the next steps.

**Comment by strepanier03** [comment] 2022-11-16 03:11
Will check tomorrow for an update.

**Comment by MonilBhavsar** [comment] 2022-11-16 05:45
Sorry missed this.
Default rooms include - Workspace room, #admins, #announce and domain default group. In this specific issue, I think we'll be taking into account Workspace room, #admins and #announce as they are related to a Workspace

**Comment by eVoloshchak** [comment] 2022-11-16 17:50
@MonilBhavsar, thank you!

In that case `Solution 1` of @tienifr's [proposal](https://github.com/Expensify/App/issues/12151#issuecomment-1311445242) looks good to me
🎀👀🎀 C+ reviewed!

**Comment by strepanier03** [comment] 2022-11-17 02:00
The job post is [here](https://www.upwork.com/jobs/~01cf8f22223f210999), please apply and I'll monitor for applications. 

@tienifr - As a reminder, I wanted to link to the new process change regarding PR merge and bonuses [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667607226305649). You can read more about it in the CONTRIBUTING.md as well.

**Comment by tienifr** [comment] 2022-11-17 03:23
Thanks @strepanier03, I've applied to the job, the PR will be ready by November 18

**Comment by MonilBhavsar** [comment] 2022-11-17 04:30
@strepanier03 I was left to review the proposal 😅

**Comment by MonilBhavsar** [comment] 2022-11-17 04:57
I also like the proposal 1 👍

**Comment by tienifr** [comment] 2022-11-17 09:09
Hi @eVoloshchak @MonilBhavsar I just created PR for this issue: https://github.com/Expensify/App/pull/12664 please help to review it

**Comment by strepanier03** [comment] 2022-11-18 01:13
Aaah, sorry about that @MonilBhavsar! I misunderstood where the conversation was at and thought you were on board with the solution because of the discussion about the rooms. I will wait for more explicit approval from the CME moving forward.

**Comment by strepanier03** [comment] 2022-11-18 23:07
@eVoloshchak and @MonilBhavsar - The PR from @tienifr has been submitted and is needing review.

**Comment by tienifr** [comment] 2022-11-21 07:22
Hi @eVoloshchak  This PR is created 4 days ago, please help to review it. Thanks

**Comment by eVoloshchak** [comment] 2022-11-21 07:27
Hi, @tienifr!
I've found a bug and left a [comment](https://github.com/Expensify/App/pull/12664#issuecomment-1318895198) on the PR, please check it out

**Comment by MonilBhavsar** [comment] 2022-11-24 07:12
PR is merged!

**Comment by MonilBhavsar** [comment] 2022-11-28 09:26
Waiting for deploy...

**Comment by strepanier03** [comment] 2022-11-28 23:23
Thank you for the updates @MonilBhavsar - I'll continue following along until I can take further action.

**Comment by strepanier03** [comment] 2022-11-30 01:22
On staging, will check again tomorrow.

**Comment by strepanier03** [comment] 2022-12-02 01:40
Still on staging. 

----

I am OoO for jury duty tomorrow. If immediate action is needed on this GH please post in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) for assistance, thank you.

**Comment by eVoloshchak** [comment] 2022-12-05 12:55
Not overdue, was deployed to staging 13 days ago

**Comment by MonilBhavsar** [comment] 2022-12-06 04:30
The associated PR was deployed to production earlier last week in this [release](https://github.com/Expensify/App/releases/tag/1.2.31-8). Not sure why i didn't post the message here. We can do the checklist manually and close this issue as it has already been 7 days since it was deployed to production

**Comment by MonilBhavsar** [comment] 2022-12-06 04:32
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.2.31-8 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/12664


If no regressions arise, payment will be issued on 2022-12-02. :confetti_ball:

After the hold period, please check if any of the following need payment for this issue, and if so check them off after paying:
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by MonilBhavsar** [comment] 2022-12-06 04:33
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@eVoloshchak / @MonilBhavsar] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@eVoloshchak / @MonilBhavsar] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@eVoloshchak / @MonilBhavsar] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@strepanier03] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by strepanier03** [comment] 2022-12-07 01:14
@tienifr and @eVoloshchak - Please apply for the job [here](https://www.upwork.com/jobs/~01cf8f22223f210999). I'll check back tomorrow and accept/pay as applicable.

**Comment by strepanier03** [comment] 2022-12-07 01:15
I'll work on the TR, this seems like a good thing to test for if we're not already.

**Comment by strepanier03** [comment] 2022-12-07 22:38
Not sure what happened but the job posting is closed now and I can't reopen it. 

----

I made a new posting for @tienifr and @eVoloshchak to apply for, please do that [here](https://www.upwork.com/jobs/~013e7dafa11d75fef1) and I'll check in again to accept and pay.

**Comment by strepanier03** [comment] 2022-12-07 22:38
@eVoloshchak @MonilBhavsar - The three tasks below from the checklist still need to be handled. 

- [ ]  [@eVoloshchak / @MonilBhavsar] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@eVoloshchak / @MonilBhavsar] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@eVoloshchak / @MonilBhavsar] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**Comment by tienifr** [comment] 2022-12-08 01:19
@strepanier03 I've applied to the job
Thanks!

**Comment by strepanier03** [comment] 2022-12-08 03:34
Thank you both, offers sent and will check tomorrow.

**Comment by strepanier03** [comment] 2022-12-09 03:30
@eVoloshchak and @MonilBhavsar - Any chance the rest of the checklist can be wrapped up before the end of the week?

**Comment by strepanier03** [comment] 2022-12-09 03:31
Paid @tienifr, thank you!

**Comment by eVoloshchak** [comment] 2022-12-09 18:59
> The PR that introduced the bug has been identified. Link to the PR:

I think it's https://github.com/Expensify/App/pull/10723, but i wouldn't say it 'introduced' the bug

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

It seems it was the expected result at the time judging by how `pendingAction`  was added for some chats, but not these specifically 

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

We have an item in the checklist that should have prevented this: `I turned off my network connection and tested it while offline to ensure it matches the expected behavior`. Not sure we can catch this type of bug sooner with anything but thorough testing

**Comment by strepanier03** [comment] 2022-12-10 01:42
Thank you @eVoloshchak- I'll update the OG checklist with your comments for clarity. 

I've also paid your contract in UpWork.

**Comment by strepanier03** [comment] 2022-12-10 01:43
I won't get to the regression test stuff until next week.

**Comment by strepanier03** [comment] 2022-12-13 01:46
Thank you @MonilBhavsar for that, I was having a hard time prioritizing. 

That was the last bit before closing so I agree and will wrap this up.

**Closed by strepanier03** 2022-12-13 01:46 UTC
Labels: External, Daily, Bug
