### ISSUE TITLE
[HOLD for payment 2024-10-22] [$250] Web/Desktop - Chat - Focus is lost after deleting a message from edit mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45472] opened 2024-07-16 12:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4725448
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Start ND on Desktop App or go to staging.new.expensify.com
2. Login with any account
3. Open any chat and send a message
4. Press Arrow Up key on keyboard
5. Select All - Ctrl / Cmd + A
6. Press 'Delete' key
7. Press 'Enter' key
8. Confirm message deletion with 'Enter' key

## Expected Result:
Message deleted. Focus is on composer field

## Actual Result:
Focus lost after deleting message in edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/67231f2f-46a8-4f10-93cf-7389de640c18

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe43add27dc504ef</li>
        <li>Upwork Job ID: 1826277990269229690</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 104052891</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by lanitochka17** [comment] 2024-07-16 12:20
We think that this bug might be related to #vip-vsp

**Comment by thienlnam** [comment] 2024-07-16 18:31
This is a pretty edge case bug - don't think it needs to be a blocker

**Comment by code-with-shahzad** [comment] 2024-08-21 18:43
There can be something like handle by state while deleting due to re-render focus can change.
or there can be something handle through searchparams...

**Comment by ardent-dev** [comment] 2024-08-21 20:34
Hi All, this one was reproducible on staging and prod, but I was not able to reproduce it on dev main branch. Could this already be resolved?

**Comment by brunovjk** [comment] 2024-08-22 13:52
You're right, I just tested it and at the last main (v9.0.23-0) it seems to no longer be reproducible:

https://github.com/user-attachments/assets/904b7bff-560d-410b-b5c7-db57b6b9261c

**Comment by lanitochka17** [comment] 2024-08-28 12:44
Issue is still reproducible

https://github.com/user-attachments/assets/4fe03dee-f213-40b2-8d6a-eb43f07a0a1d

**Comment by brunovjk** [comment] 2024-08-28 13:00
Bumped into Slack to search for proposals.

**Comment by brunovjk** [comment] 2024-08-28 21:38
Strange, because in staging I can reproduce it, but **not in the last main (v9.0.25-14)**. I'll keep an eye out for proposals and test again in a week.

**Comment by brunovjk** [comment] 2024-09-03 13:55
I **can** still reproduce it in staging. Bumped into [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1725371690936749) for proposals.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-08 21:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user is in edit mode and deletes a message, the composer field loses focus.

### What is the root cause of that problem?
The application is not properly handling the focus state of the composer field after a message is deleted.
### What changes do you think we should make in order to solve the problem?
1. Observe changes to the **lastReportAction?.message** in the ReportActionCompose component.
2. When lastReportAction?.message updates, indicating a message has been deleted, call a focus() function to re-focus the composer input field.


Here:
https://github.com/Expensify/App/blob/aaa60b9103af83aaa58222e3f36e8cbfbd57e5c3/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L124

we should add this code:
```
useEffect(() => {
    focus();
  }, [lastReportAction?.message]);
```


https://github.com/user-attachments/assets/6daa78ef-bbc5-45c0-8416-24a4aae0a9a6

**Comment by brunovjk** [comment] 2024-09-09 12:55
Reviewing proposal.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-09 16:33
Thank you @brunovjk.
I believe this is a new feature, not a regression.

Looking at the code, we manually focus the input in a few specific cases. For example, when a user tries to submit an empty message while editing, a delete confirmation modal appears. If the user cancels, the input is refocused because it lost focus when the modal was shown.

You can see that here: https://github.com/Expensify/App/blob/89b9226fd6fa0884b8a9c9761759a787e820fcf8/src/pages/home/report/ReportActionItemMessageEdit.tsx#L302-L303

However, when a message is actually deleted, we don’t refocus the input, which is why the behavior feels different. We can’t simply add the refocusing logic when the user confirms the deletion, because two different components are involved: one for writing a comment and another for editing a comment.

Since we don’t have direct access to the comment input from within the edit comment file, we need to handle refocusing by tracking when the comment value updates after a deletion. That can be done in this file: https://github.com/Expensify/App/blob/aaa60b9103af83aaa58222e3f36e8cbfbd57e5c3/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L124

There’s another place where we manually refocus the input when hiding the emoji picker modal: https://github.com/Expensify/App/blob/89b9226fd6fa0884b8a9c9761759a787e820fcf8/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L560-L567

I suggest we follow a similar approach to the one I outlined in my proposal. Alternatively, we could create a new key in Onyx, like commentDelete, and update it when the user confirms deletion. We could then track that value in useEffect and use it to refocus the input.

**Comment by raza-ak** [comment] 2024-09-09 16:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web/Desktop - Chat - Focus is lost after deleting a message from edit mode
### What is the root cause of that problem?
The focus loss happens because the `setUpComposeManagerFocus` function does not account for the scenario where the Composer loses focus after returning from the delete message modal. The focus on the Composer is not restored when it becomes visible again after the modal is closed.
### What changes do you think we should make in order to solve the problem?
To solve the problem, we should modify the `setUpComposeManagerFocus` function to check whether the Composer is visible and, if so, restore focus appropriately. The updated version should handle the modal close event effectively and refocus on the Composer as expected.
Following changes ensure that when the modal is closed, the Composer field regains focus and provides a better user experience.
<img width="921" alt="image" src="https://github.com/user-attachments/assets/f881ef22-94c7-4a97-96ea-d9de86c56319">
[1.webm](https://github.com/user-attachments/assets/1ec5246d-c997-4164-b253-22e75a93b9ba)

**Comment by brunovjk** [comment] 2024-09-09 17:57
Thanks for the proposal @raza-ak, I believe your RCA is not very correct, I tested your proposed solution, and it is triggering `focus` in the main composer unnecessarily:


https://github.com/user-attachments/assets/4312ae4f-99b3-4025-9915-f53baf34b09b

**Comment by brunovjk** [comment] 2024-09-09 18:09
Thanks for clarifying @Shahidullah-Muffakir, although it makes sense to me, I'm still not 100% sure, could you put everything together in your proposal? That way I can ping an internal eng to take a look. Thanks.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-09 19:45
@brunovjk, I’ve updated my original proposal. I combined my earlier explanation with it. Let me know if you need anything else. Thanks!

**Comment by brunovjk** [comment] 2024-09-10 12:29
@bernhardoj sorry to bother you, but can you please take a quick look at this issue here, do you think it might be related to your [PR here](https://github.com/Expensify/react-native-live-markdown/pull/362) somehow? Thanks a lot.

**Comment by bernhardoj** [comment] 2024-09-11 05:55
I don't think it's related to that PR since that PR fix an auto-focus issue on mount.

**Comment by raza-ak** [comment] 2024-09-11 09:25
@brunovjk I've updated my [proposal](https://github.com/Expensify/App/issues/45472#issuecomment-2338596938) and fixed all focus issues. Please review it again.

**Comment by brunovjk** [comment] 2024-09-11 11:37
Thank you very much for confirming @bernhardoj.

**Comment by brunovjk** [comment] 2024-09-11 12:58
Thanks for the update and your time @raza-ak, but I believe we still don't have the correct cause of the issue.

@Shahidullah-Muffakir  I've been investigating and I believe that your RCA is also not adequate, sorry about that. When delete or edit a comment it seems to me that we have already taken care to update the `composer focus` after:
https://github.com/Expensify/App/blob/e9642dc7829f912bbb20be6c0d89b3e6529df7b6/src/pages/home/report/ReportActionItemMessageEdit.tsx#L273-L278

When we edit the focus it is updated successfully (call `deleteDraft`):
https://github.com/Expensify/App/blob/e9642dc7829f912bbb20be6c0d89b3e6529df7b6/src/pages/home/report/ReportActionItemMessageEdit.tsx#L308-L309

However, by leaving the comment empty, we should also update the focus (call `deleteDraft`):
https://github.com/Expensify/App/blob/e9642dc7829f912bbb20be6c0d89b3e6529df7b6/src/pages/home/report/ReportActionItemMessageEdit.tsx#L303-L305

However `deleteDraft` is not being called in `delete` case

https://github.com/user-attachments/assets/9ede165a-c6d1-4850-9d6e-96528ee112c2

I haven't figured out why yet, @raza-ak and @Shahidullah-Muffakir Thoughts?

**Comment by raza-ak** [comment] 2024-09-11 13:33
@brunovjk Did you watch my updated video in the [proposal](https://github.com/Expensify/App/issues/45472#issuecomment-2338596938) and did you test my latest code changes locally? I've fixed that issue and i believe i've shared the correct cause of issue with you.

**Comment by brunovjk** [comment] 2024-09-11 13:54
@raza-ak Yes, I have reviewed it, and although the changes seem to solve the problem I want to be sure of the root cause. I understand, I will take a closer look at your proposal and let you know if I find anything different.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-11 16:58
@brunovjk I've identified the root cause of the bug.  The issue was that the `onConfirm` callback **(deleteDraft**) which should be called when a user confirms the deletion of a message in the `showDeleteModal`, was not being invoked as expected.

The problem stemmed from a typo in the file:
https://github.com/Expensify/App/blob/b76d91ca3b2f973da1bd0a76871d3b6f9ef588bf/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L33

The variable `onConfirmDeleteModal` was incorrectly spelled as `onComfirmDeleteModal` in three instances. After correcting these typos, the functionality is now working as intended, and focus is properly regained after the deletion action.


I've tested the solution, and it resolved the issue. Thank you.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-11 17:06
@brunovjk  Thanks for telling me about the **deleteDraft** function not working. At first, I tried to fix it but couldn't, so I stopped trying. But when you mentioned it again, it made me look harder. Because of that, I found out what was really wrong

**Comment by brunovjk** [comment] 2024-09-11 17:31
Hi @Shahidullah-Muffakir, Thank you for identifying the typo in onComfirmDeleteModal. I corrected it across the file, but after testing, it doesn't seem to affect the functionality or resolve the issue. Upon further review, I couldn't find any references where this ref is actually used. Were you able to resolve it just by fixing the typo?

**Comment by Shahidullah-Muffakir** [comment] 2024-09-11 17:34
@brunovjk  I am sorry I forgot to mention one more small issue int the line 
https://github.com/Expensify/App/blob/b76d91ca3b2f973da1bd0a76871d3b6f9ef588bf/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L267

it should be 
`        callbackWhenDeleteModalHide.current =  runAndResetCallback(onConfirmDeleteModal.current);
`

You can test it with these changes , Thank you.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-11 18:02
@brunovjk,  In the original code we are wrapping the execution of **runAndResetCallback** in an anonymous function. This means the assignment to **callbackWhenDeleteModalHide.current** is now a function that, when executed, will:

Call **runAndResetCallback(onConfirmDeleteModal.current).**
Assign the result of **runAndResetCallback** to **onConfirmDeleteModal.current**.
However, the result of **runAndResetCallback(onConfirmDeleteModal.current)** is a noop function (() => {}), and we are assigning this noop function back to onConfirmDeleteModal.current. As a result:

**onConfirmDeleteModal.current** will get replaced with () => {}

in my suggested changes, we are directly invoking **runAndResetCallback** and assigning its result to callbackWhenDeleteModalHide.current. This ensures that the callback runs immediately, and the reset behavior works as intended.
Thank you.

**Comment by brunovjk** [comment] 2024-09-11 18:04
Hi @Shahidullah-Muffakir, Thank you for following up and for your persistence in addressing the issue. I tested the latest change you suggested, and it seems like this indeed resolves the problem. The root cause appears to be how the callback was handled in callbackWhenDeleteModalHide, specifically assigning a reset function incorrectly. Could you please update your proposal with these changes? Once that's done, I'll submit it for internal review and assign you if they approve. Thanks again for your efforts!

**Comment by Shahidullah-Muffakir** [comment] 2024-09-11 18:12
@brunovjk , Thank you for your feedback! I’ll update the proposal with the suggested changes. Regarding the typos in "onConfirmation," do you want to keep them as they are,  as they  are irrelevant now, or should I correct those as well, ? Thank you.

**Comment by brunovjk** [comment] 2024-09-11 18:16
> @brunovjk , Thank you for your feedback! I’ll update the proposal with the suggested changes. Regarding the typos in "onConfirmation," do you want to keep them as they are, as they are irrelevant now, or should I correct those as well, ? Thank you.

I believe we can fix them yes :D

**Comment by Shahidullah-Muffakir** [comment] 2024-09-11 18:34
@brunovjk proposal https://github.com/Expensify/App/issues/45472#issuecomment-2336825317 updated, Thank you.

**Comment by brunovjk** [comment] 2024-09-11 18:45
I think we can go with @Shahidullah-Muffakir's [proposal](https://github.com/Expensify/App/issues/45472#issuecomment-2336825317) now.

 🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment] 2024-09-19 21:52
🎀👀🎀

**Comment by Shahidullah-Muffakir** [comment] 2024-09-20 10:47
I will submit the PR within 24hrs.

**Comment by brunovjk** [comment] 2024-10-09 11:44
[PR](https://github.com/Expensify/App/pull/49538) under review.

**Comment by brunovjk** [comment] 2024-10-21 13:56
**BugZero Checklist:**
 
 * [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: I didn't find any change/PR that could have caused it, from the file history the lines that were changed in this PR were like that since the file was created. 
 * [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: The change updated the code by directly assigning the result of `runAndResetCallback()` to `callbackWhenDeleteModalHide.current`, eliminating unnecessary indirection and making the behavior more predictable.
 * [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 * [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
 * [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

- Start the ND Desktop App or go to staging.new.expensify.com and log in with any account.
- Open any chat and send a message.
- Press the Arrow Up key, then use Ctrl + A (or Cmd + A) to select all text, followed by the 'Delete' key.
- Press 'Enter' to confirm the deletion.
- Ensure that the focus remains on the composer field after deletion.

Do we agree 👍 or 👎?

cc: @johnmlee101

**Comment by brunovjk** [comment] 2024-10-21 13:59
**BugZero Checklist:**
 
 * [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **I couldn't find any changes or pull requests that would have caused this issue. According to the file history, those lines have remained unchanged since the file was created.** 
 * [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **The change updated the code by directly assigning the result of `runAndResetCallback()` to `callbackWhenDeleteModalHide.current`, eliminating unnecessary indirection and making the behavior more predictable.**
 * [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 * [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
 * [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

- Start the ND Desktop App or go to staging.new.expensify.com and log in with any account.
- Open any chat and send a message.
- Press the Arrow Up key, then use Ctrl + A (or Cmd + A) to select all text, followed by the 'Delete' key.
- Press 'Enter' to confirm the deletion.
- Ensure that the focus remains on the composer field after deletion.

Do we agree 👍 or 👎?

cc: @youssef-lr, @johnmlee101

**Comment by joekaufmanexpensify** [comment] 2024-10-22 20:50
Regression test here: https://github.com/Expensify/Expensify/issues/438069

**Comment by joekaufmanexpensify** [comment] 2024-10-22 20:50
All set to issue payment. We need to pay: 

- @Shahidullah-Muffakir - $250 for PR vio Upwork. 
- @brunovjk - $250 for C+ visa Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-10-22 20:52
@brunovjk $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-10-22 20:56
@Shahidullah-Muffakir you were never hired, so created a [new upwork job](https://www.upwork.com/jobs/~021848830508127487853) and send you an offer for $250

**Comment by Shahidullah-Muffakir** [comment] 2024-10-22 21:01
@joekaufmanexpensify, Thanks, I accepted it. Just to mention that I've already been assigned to a few issues and have received payment through Upwork (Same Upwork account).

**Comment by joekaufmanexpensify** [comment] 2024-10-22 21:02
TY! The issue might've been that this issue was several months old.

**Comment by joekaufmanexpensify** [comment] 2024-10-22 21:03
@Shahidullah-Muffakir $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-10-22 21:03
New upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-10-22 21:03
All set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-10-22 21:03 UTC
Labels: External, Engineering, Daily, Awaiting Payment
