### ISSUE TITLE
[HOLD for payment 2024-11-13][$250] [Performance] HybridApp iOS: Firebase crash - facebook::jsi::JSError

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#51853] opened 2024-11-01 13:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

Firebase crash here: 

https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/ios:com.expensify.expensifylite/issues/6c81436592b37f898c07cab55a30a83a?time=last-seven-days&types=crash&versions=9.0.56%20(9.0.56.0)&sessionEventKey=e05c506c93834ffb8281b148f87b6459_2010479564232592518

## What is the impact of this on end-users?

Reported here: https://expensify.slack.com/archives/C05LX9D6E07/p1730395726205249

## List any benchmarks that show the severity of the issue

14 sessions so far

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

Investigate and fix

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852337274739729797</li>
        <li>Upwork Job ID: 1852337274739729797</li>
        <li>Last Price Increase: 2024-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by mountiny** [comment] 2024-11-01 13:09
```
Fatal Exception: facebook::jsi::JSError
Exception in HostFunction: Unhandled JS Exception: RangeError: Maximum call stack size exceeded This error is located at: in ReportIDsContextProvider in ActiveWorkspaceContextProvider in Ac..., stack: getRootParentReport@1:2745489 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:274552
```

**Comment by arosiclair** [comment] 2024-11-01 16:07
Working on getting the latest TestFlight version of HybridApp. My old version **v9.0.47-4** is loading without any crashes.

**Comment by arosiclair** [comment] 2024-11-01 16:19
Okay updated to **v9.0.56-3** and see no immediate crashes yet. The exception from Firebase seems to be related to threads:

```
Fatal Exception: facebook::jsi::JSError
Exception in HostFunction: Unhandled JS Exception: RangeError: Maximum call stack size exceeded This error is located at: in ReportIDsContextProvider in ActiveWorkspaceContextProvider in Ac..., stack: getRootParentReport@1:2745489 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 getRootParentReport@1:2745520 get
```

**Comment by arosiclair** [comment] 2024-11-01 16:53
I can't reproduce the issue, but I'm pretty sure it has to do with some bugged thread report that @ryanschaffer has. I'm adding cycle detection to [getRootParentReport](https://github.com/Expensify/App/blob/2bde8f2291e361b4d0eac7b8b1fa8f057e8ec7a4/src/libs/ReportUtils.ts#L755-L773) to prevent infinite loops and I'll also log which reports are causing the issue.

**Comment by Beamanator** [comment] 2024-11-04 10:11
Well the PR was CP'd, can we now call this NAB / fixed @arosiclair ? 🙏

**Comment by Beamanator** [comment] 2024-11-04 10:13
Removing `Help Wanted` b/c it looks like we already have a PR to fix this?

**Comment by Julesssss** [comment] 2024-11-04 11:48
Fix was CPd and was confirmed fixed 🎉 

I'm removing the blocker label and closing the Firebase issue.

**Comment by lschurr** [comment] 2024-11-13 17:58
@ZhenjaHorbach - please accept the [offer in Upwork](https://www.upwork.com/nx/wm/offer/104884350)

**Comment by lschurr** [comment] 2024-11-13 18:02
All set!

**Closed by lschurr** 2024-11-13 18:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment
