### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Refactor `MoneyAmountRequestPage` to make it more reusable

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#23149] opened 2023-07-19 02:17 UTC
The `MoneyRequestAmountPage` needs to be improved to make it more reusable for the "Edit Request" flow [here](https://github.com/Expensify/App/blob/main/src/pages/EditRequestPage.js). There are also some issues with the code.

**Issues...**

- `MoneyRequestAmountPage` has a hard dependency on props.iou. AFAICT that is a temporary Onyx key where we are storing things about a request that is currently being staged for creation. The long term plan is to use the `transaction` object. So, the first challenge is decoupling that dependency anywhere it is referenced.
- There is some [navigation handling that should be moved out of this component](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/pages/iou/steps/MoneyRequestAmountPage.js#L235-L258). It also has a dependency on the props.iou Onyx key.
- There are a lot of things being derived from [navigation params](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/pages/iou/steps/MoneyRequestAmountPage.js#L260-L266) like - all over the place. Ideally we would be able to pass those as props and handle the navigation params in a parent page?
- [All this navigation logic](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/pages/iou/steps/MoneyRequestAmountPage.js#L357-L404) should be moved to a new component only used in the request creation flow.

**Other things that are possibly incorrect...**

- [This](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/pages/iou/steps/MoneyRequestAmountPage.js#L212-L217) is referencing an errors prop that doesn't seem to exist 🤔
- I am confused about why all of these values are stored in refs [here](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/pages/iou/steps/MoneyRequestAmountPage.js#L174-L178).
- Having a `useEffect()` [detect a change in props and then set state](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/pages/iou/steps/MoneyRequestAmountPage.js#L268-L270) feels like an anti-pattern? Can we just use the prop?
- It would be good if all of the hooks were documented better + have some comment about why they are being used.

**Deliverables:** 

- Create something like an `AmountRequestPage` and then have a `MoneyRequestAmountPage` and `EditRequestAmountPage` that both use `AmountRequestPage`.

`MoneyRequestAmountPage` - custom navigation stuff, uses the iou Onyx prop, etc.
`EditRequestAmountPage` - different navigation stuff, uses the transaction Onyx prop

- Clean up the existing issues and try to document the code a bit better so it is clearer how all of this works (especially the parts around custom navigation).

Thoughts on this approach?
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018aca51d5f6723c8c</li>
        <li>Upwork Job ID: 1681488307261317121</li>
        <li>Last Price Increase: 2023-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 26031120</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-19 03:05
I'd love to work on this

**Comment by ygshbht** [comment] 2023-07-19 04:37
## Proposal

The `MoneyRequestAmountPage` serves a significant purpose in the app but currently, it lacks reusability due to its structural issues and dependencies. The goal is to enhance its reusability by decoupling it from certain dependencies and moving non-core functionality, like navigation, to more appropriate areas:

**Q: MoneyRequestAmountPage has a hard dependency on props.iou. AFAICT that is a temporary Onyx key where we are storing things about a request that is currently being staged for creation. The long term plan is to use the transaction object. So, the first challenge is decoupling that dependency anywhere it is referenced.**
> A: Indeed, to address this, we can assign props.iou to a variable, let's say `iou`, and use this variable throughout the component. This will eliminate the hard dependency on props.iou and make the component more versatile.

**Q: There is some navigation handling that should be moved out of this component. It also has a dependency on the props.iou Onyx key. There are a lot of things being derived from navigation params - ideally, we would be able to pass those as props and handle the navigation params in a parent page?**
> A: Absolutely, moving navigation handling to a separate component will declutter the MoneyRequestAmountPage, allowing it to focus more on its core functionalities. Passing the navigation parameters as props will further improve the reusability of the component.

**Q: It would be good if all of the hooks were documented better + have some comment about why they are being used.**
> A: Agree, proper documentation of hooks and the reasoning behind their use will not only increase readability but also ensure that their role within the component is clearly understood. This should be a standard practice for code maintainability.

**Q: Having a useEffect() detect a change in props and then set state feels like an anti-pattern? Can we just use the prop?**
> A: Yes, particularly for the currency setting part, it can be handled via prop directly from the parent, eliminating the need for a state change on prop update - this is a more straightforward approach.

**Q: This is referencing an errors prop that doesn't seem to exist.**
> A: The presence of an 'errors' prop that doesn't seem to exist suggests legacy code or a miscommunication in code intent. We need to investigate this further and modify or remove it accordingly to improve code quality.

**Q: I am confused about why all of these values are stored in refs here.**
> A: The usage of refs here seems to be unnecessary for `iouType`, `reportId`, and `isEditing` as their values are derived from props and do not need to persist over rerenders. On the contrary, `textInput` seems to be correctly used as a Ref to store the DOM element. This suggests we need to review and modify the usage of refs in this component.

By following this plan, we aim to make `MoneyRequestAmountPage `more reusable and maintainable, which will prove beneficial for its use in the "Edit Request" flow and other potential future developments.

**Comment by ygshbht** [comment] 2023-07-19 04:50
If I may express my thoughts, 
###### considering the intricacy of MoneyRequestAmountPage, which isn't a brief file with approximately 500 lines, the task of refactoring it is not entirely straightforward. Beyond restructuring the code, we also need to guarantee that it operates flawlessly, devoid of any bugs or regressions. Given the scope of the task, I believe a minimum price range of $1500 to $2000 would be a more equitable starting point for this job

**Comment by twisterdotcom** [comment] 2023-07-19 13:11
@marcaaron do we need a C+ here to evaluate the proposals, or will you do it?

Any thoughts on bumping the price here as @ygshbht proposes? Our usual process is to rely on the market of proposals and bump if we don't think there are any within a week that are good to go.

Secondly, if the proposer we want to go with requests more to complete the job, we can discuss that then.

**Comment by marcaaron** [comment] 2023-07-20 00:54
Not actually accepting any open proposals for this. Working with Callstack on it.

@rayane-djouah, @samh-nl, @ygshbht Thank you for the comments. Unless there's a `Help Wanted` label on an issue it is probably best to refrain from leaving a proposal.

**Comment by koko57** [comment] 2023-07-20 10:46
Hi 🙂 I'm starting working on that with @thiagobrez

**Comment by twisterdotcom** [comment] 2023-07-20 11:11
Can we assign @koko57 to this then @marcaaron?

**Comment by marcaaron** [comment] 2023-07-20 20:11
Sounds great, thank you @koko57 !

**Comment by koko57** [comment] 2023-07-24 12:16
Hello! Sorry for no updates yet - we had an internal event last Friday, I was off that day. I've read the requirements, reviewed the MoneyAmountRequestPage current implementation and started working on the issue.

**Comment by koko57** [comment] 2023-07-25 11:01
## Proposal

As @marcaaron suggested, we should create MoneyRequestAmountPage and EditRequestAmountPage which will hold a separate logic for each page (different props and navigation). The UI components for displaying the step should be moved to another component (similar to [EditRequestDescriptionPage](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/pages/EditRequestDescriptionPage.js#L24) - the name should be changed btw) and get the props from the parent component. 

All the issues that @marcaaron mentioned should be fixed - removing all these useEffects and refs.
I think we can do the same (I mean separate logic from the UI) for all the money request pages - for now, we have an unused (yet) component [EditRequestDescriptionPage](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/pages/EditRequestDescriptionPage.js#L24) that could be easily reused in [MoneyRequestDescriptionPage](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/pages/iou/MoneyRequestDescriptionPage.js#L43) (probably without any more changes or maybe with only some minor ones). For now, we have duplicated code in [MoneyRequestDescriptionPage](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/pages/iou/MoneyRequestDescriptionPage.js#L43) and [EditRequestDescriptionPage](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/pages/EditRequestDescriptionPage.js#L24). I think that for consistency we will need to apply the same approach for the confirmation page. 

IMPLEMENTATION PLAN:

1. Create MoneyRequestAmountForm (draft name, maybe RequestAmountForm would be better) and move all the UI components there
2. Create MoneyRequestAmountPage and EditRequestAmountPage (shouldn’t we rename the first one to NewRequestAmountPage?) -> get all the data from iou or transaction prop here and pass it down to MoneyRequestAmountForm, handle the navigation logic
3. While working on the pages get rid of unnecessary useEffects and refs.

+

Apply the same steps for Description and Confirmation pages -> for the description page we already can use EditRequestDescriptionPage but we should rename it to RequestDescriptionForm and create EditRequestDescriptionPage and NewRequestDescriptionPage

So we will have a structure like this:

NewRequestAmountPage
						->	RequestAmountForm
EditRequestAmountPage

NewRequestDescriptionPage
							-> 	RequestDescriptionForm
EditRequestDescriptionPage

NewRequestConfirmationPage
							-> 	RequestConfirmationForm
EditRequestConfirmationPage


I wonder if we could change the routes for consistency - for now we have [':iouType/new/amount/:reportID?'](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/ROUTES.js#L83C6-L83C6), for money request amount and ['r/:threadReportID/edit/:field'](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/ROUTES.js#L66), for editing any of the fields - maybe we could use the same convention for both - [r]/:iouType/[new/edit]/:field/:reportID -> I mean to have the same order: iouType, new or edit, amount or description.

I guess that for now we would like to able to edit the description and the amount, if we wanted to edit participants or currency we can do this in a similar way.

**Comment by marcaaron** [comment] 2023-07-25 22:52
>Create MoneyRequestAmountForm (draft name, maybe RequestAmountForm would be better)

Either name works here for me.

>shouldn’t we rename the first one to NewRequestAmountPage

Yeah, I really love this suggestion.

>Apply the same steps for Description and Confirmation pages -> for the description page we already can use EditRequestDescriptionPage but we should rename it to RequestDescriptionForm and create EditRequestDescriptionPage and NewRequestDescriptionPage

Yes! Can this be a follow up issue or separate PR?

>I wonder if we could change the routes for consistency - for now we have [':iouType/new/amount/:reportID?'](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/ROUTES.js#L83C6-L83C6), for money request amount and ['r/:threadReportID/edit/:field'](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/ROUTES.js#L66), for editing any of the fields - maybe we could use the same convention for both - [r]/:iouType/[new/edit]/:field/:reportID -> I mean to have the same order: iouType, new or edit, amount or description.

I don't have strong feelings on this, but agree they are inconsistent. Curious what @mountiny thinks. I think if we can also address that in a follow up issue it would be better. Also I'm not sure whether these links are used for any marketing purposes (like emails) or if it would be very easy to change them (I think so, but we should ask).

**Comment by koko57** [comment] 2023-07-26 07:00
> > Apply the same steps for Description and Confirmation pages -> for the description page we already can use EditRequestDescriptionPage but we should rename it to RequestDescriptionForm and create EditRequestDescriptionPage and NewRequestDescriptionPage
> 
> Yes! Can this be a follow up issue or a separate PR?

Of course! It's a good idea. I'll be more than happy to work on this follow up as well 🙂 

So I'm getting to work! 🙂

**Comment by mountiny** [comment] 2023-07-26 22:52
Thanks @koko57 looks great!

> I wonder if we could change the routes for consistency - for now we have [':iouType/new/amount/:reportID?'](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/ROUTES.js#L83C6-L83C6), for money request amount and ['r/:threadReportID/edit/:field'](https://github.com/Expensify/App/blob/9dd3a3ff1d82c944bb0e5d631511348107734e7a/src/ROUTES.js#L66), for editing any of the fields - maybe we could use the same convention for both - [r]/:iouType/[new/edit]/:field/:reportID -> I mean to have the same order: iouType, new or edit, amount or description.

I agree making it more consistent does not hurt, one drawback I can see with the proposed routes though is that we dont care about the `iouType` when we editing the transaction. Then we basically only care about the transaction object and from that we can update everything and if it was a split or request does not matter. Hence I think it would not make sense to put it into the route either.

**Comment by koko57** [comment] 2023-07-28 10:22
@mountiny Thanks for the suggestion!

Update: making progress here, but there's still some work to be done.

**Comment by koko57** [comment] 2023-07-31 13:40
Hi :) I'm very close to opening my draft PR. But before I do that I need to do some cleanup and I've got one question: is there any possible scenario that would require that [logic](https://github.com/BhuvaneshPatil/App/blob/7144f87e520dd8fb8963ce747286d6cf2b8e4d3c/src/pages/iou/steps/MoneyRequestAmountPage.js#L235-L258)? I'm asking because I feel that it's no longer necessary, but maybe I'm missing something and I just wanted to confirm.

**Comment by mountiny** [comment] 2023-07-31 15:24
Good question, I think that you are right, but we might as well discover this during testing

**Comment by marcaaron** [comment] 2023-07-31 21:35
Without having a ton of context (and being quite confused myself about it) I think the best path would be to try and git blame whichever PR added it and make sure we are not re-introducing any regressions / follow whatever test steps we had when it was first added.

**Comment by mountiny** [comment] 2023-07-31 21:39
@koko57 Lets make sure to raise the PR tomorrow and lets work with some C+ to get it merged ASAP. We are focusing a lot now to finish the edit money request feature and this refactor/ improvement will help a lot so (its harder to continue without it and it will double the work for one of us) if we could nail this tomorrow, it would be super helpful. I can help out to get some C+ who could actively help to test it with you tomorrow

Here is WIP PR for the edit money request btw https://github.com/Expensify/App/pull/23703

**Comment by koko57** [comment] 2023-08-01 08:53
Draft PR https://github.com/Expensify/App/pull/23979

**Comment by s77rt** [comment] 2023-08-09 14:26
Can I get assigned here?

**Comment by koko57** [comment] 2023-08-09 14:27
@marcaaron @mountiny I've opened a draft follow-up PR addressing all the comments from https://github.com/Expensify/App/pull/23979. I replied to some of them explaining why I solved the problems a bit differently. Let me know if I can open the PR for review. 

I'll be ooo tomorrow, so if you request any changes, I'll be working on them on Friday.

**Comment by s77rt** [comment] 2023-08-09 14:58
@twisterdotcom Yes

**Comment by mountiny** [comment] 2023-08-15 17:26
@koko57 Is there anything left to do in this issue?

**Comment by koko57** [comment] 2023-08-15 17:56
No, I think everything's done here

**Comment by mountiny** [comment] 2023-08-15 21:02
thanks!  @twisterdotcom I think we can then pay @s77rt for the review $1000 and close this out. Thank you!

**Comment by twisterdotcom** [comment] 2023-08-16 15:03
I think the offer needs to be accepted first? I can't pay it, only make a new one.
<img width="1037" alt="image" src="https://github.com/Expensify/App/assets/9133401/252d36be-9829-4648-8ac0-acf6f019bad1">

**Comment by s77rt** [comment] 2023-08-16 18:11
@twisterdotcom Payment is handled already on https://github.com/Expensify/App/issues/24125

**Closed** 2023-08-17 09:23 UTC
Labels: Reviewing, External, Weekly, NewFeature, Awaiting Payment
