### ISSUE TITLE
[$500] New order of tags do not update after reopening confirmation page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37864] opened 2024-03-07 03:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** New Feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has independent multilevel tags.

1. [Employee] Go to workspace chat.
2. {Employee] Go to FAB > Request money > Manual > Enter amount.
3. [Employee] On confirmation page, note the order of multilevel tags.
4. [Admin] On Old Dot, rearrange the order of multilevel tags (do not delete them)
5. [Employee] Without refreshing the page, repeat Step 2 and 3.

## Expected Result:
The new order of multilevel tags will update when reopening the confirmation page, as it works (it updates) when changing tag name.

## Actual Result:
The new order of multilevel tags does not update when reopening the confirmation page. It only updates after refreshing the page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/87148d1e-7614-4a6b-b489-7b95ff7af751

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194dd2ee1e3003f2e</li>
        <li>Upwork Job ID: 1768169703946260480</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-03-07 03:17
@robertjchen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-03-07 03:18
We think that this bug might be related to #wave6-collect-submitters

cc@greg-schroeder

**Comment by robertjchen** [comment] 2024-03-07 04:16
Yep, not a deploy blocker per se, but definitely looks like a bug to me. Though, I'm not sure if it's on the backend cc: @greg-schroeder

**Comment by luacmartins** [comment] 2024-03-07 13:15
Seems like we're not sending pusher updates for the reordering. Maybe something that https://github.com/Expensify/Auth/pull/9773 will solve

**Comment by luacmartins** [comment] 2024-03-11 17:46
Cool, put a hold for that Auth PR - https://github.com/Expensify/Auth/pull/9773

**Comment by kavimuru** [comment] 2024-03-13 13:03
@Christinadobrzyn Bug is still reproducible by the tester. 

https://github.com/Expensify/App/assets/43996225/4a2480bf-dec0-4cda-982c-4a69648dd8c3

**Comment by Christinadobrzyn** [comment] 2024-03-14 06:55
Ah okay, I deleted the tags in my test [here](https://github.com/Expensify/App/issues/37864#issuecomment-1993432773),  not moved them so that is the difference. I can reproduce the steps in the OP. 

I think we need proposals. and I think this can be external.

**Comment by robertjchen** [comment] 2024-03-18 05:58
The fix was deployed last week. @m-natarajan could you please help confirm if the issue is still reproducible? 🙏

**Comment by Christinadobrzyn** [comment] 2024-03-25 08:31
Asking QA to test too - I think this is resolved - https://expensify.slack.com/archives/C9YU7BX5M/p1711355439541929

**Comment by robertjchen** [comment] 2024-03-25 16:11
Thanks for helping test, closing this out 👍

**Closed by robertjchen** 2024-03-25 16:11 UTC
Labels: Engineering, Daily, Internal, Bug, retest-weekly
