### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500]  Bank - Calendar Is broken in Bank account flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30792] opened 2023-11-02 19:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:**Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Profile > Workspace > Connect to bank account
4. Follow steps until you get to Step 2 of 5, where you can input "Incorporation date" in the calendar.
5. Try and input any date, for example: 01/01/1980

## Expected Result:
User expects to input the date with no problems

## Actual Result:
The input is broken, the user is unable to input the correct date

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/70083247-77b6-4f5b-94b8-fc1c117d76c9

Production:

https://github.com/Expensify/App/assets/78819774/f973331d-c3c1-45fc-af22-c4c8a5d6f76e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4c10e0e27ccfb95</li>
        <li>Upwork Job ID: 1720165922139516928</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-11-02 19:48
Reproduced. Damn, that is indeed pretty bad

**Comment by erquhart** [comment] 2023-11-02 20:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Date changes while year is being entered.

### What is the root cause of that problem?
Date is being parsed via `new Date()` - this changes the timezone and rolls the date back one day, turning `01/01/0001` to `12/31/0000`.

This was introduced in the switch away from moment: https://github.com/Expensify/App/pull/29984/files#diff-6b255c40f9440d083c61f6b75caa0c2ad388438ea8fd18eefb410746b1e955f6

### What changes do you think we should make in order to solve the problem?

Use date-fns `parseISO()` to parse the date without introducing timezone differences.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mountiny** [comment] 2023-11-03 12:03
Seems like a regression from a PR from @allroundexperts and @waterim asking if they can raise a fix

**Comment by erquhart** [comment] 2023-11-03 12:32
@mountiny okay - is there anything for my effort on root cause and providing a solution?

**Comment by mountiny** [comment] 2023-11-03 12:39
Yeah we would pay you for your efforts if you solution will be used

**Comment by mountiny** [comment] 2023-11-03 14:39
PR is merged and we used similar solution to yours @erquhart so we will pay you $125 as 25% of the original amount which is what we usually do in these case. Since its a regression from pr we identified the author should be fixing it but your help is appreciated

**Comment by erquhart** [comment] 2023-11-03 14:46
@mountiny appreciated, thanks! Let me know if there are any steps I need to take.

**Comment by mountiny** [comment] 2023-11-06 16:15
<img width="380" alt="image" src="https://github.com/Expensify/App/assets/36083550/f9e56e0f-12f8-4bf1-bd44-3a6004e7b8b0">


Works!

@conorpendergrast could you please pay $125 to @erquhart for his help on the issue?

**Comment by erquhart** [comment] 2023-11-06 16:34
@mountiny just a heads up, other regressions are popping up and not being linked to this issue. I advised on one here: https://github.com/Expensify/App/issues/30871?notification_referrer_id=NT_kwDOACA6yrI4Mjk0ODc3ODc5OjIxMTIyMDI#issuecomment-1795369621

**Comment by erquhart** [comment] 2023-11-06 20:06
@mountiny @conorpendergrast sorry to bug, but I'm not sure how else to get help on this (and it's probably relevant to getting payment): I've been emailing contributors@expensify.com for a couple weeks now, still trying to get access to Slack. I was hired on another issue also (https://github.com/Expensify/App/issues/30505#issuecomment-1785973520), and followed the steps to apply for the job on Upwork, but haven't received any response there either. Any help is appreciated.

**Comment by conorpendergrast** [comment] 2023-11-06 20:54
@erquhart that's very weird; I can't see anything from you in that email list. Please can you reply to the same thread and cc me (conor@expensify.com)?

**Comment by conorpendergrast** [comment] 2023-11-06 20:55
@mountiny Given [this report](https://github.com/Expensify/App/issues/30792#issuecomment-1795384759), I'll hold on the $125 payment until I get your go-ahead again!

**Comment by erquhart** [comment] 2023-11-06 20:57
@conorpendergrast just sent, thanks for your help.

The payment for me is because my proposal was used by another engineer, as they fixed it as a regression. My comment above was only to point out that I'm still helping out with other places the same bug has popped up, in case that's relevant.

**Comment by mountiny** [comment] 2023-11-07 14:47
@erquhart thanks! We still wait for the PR to hit production +7 days regression perioed before we pay out, even if your solution helped and you havent implemented it

**Comment by conorpendergrast** [comment] 2023-11-14 21:56
@erquhart Oh hey Shawn! Please could you apply for [this job](https://www.upwork.com/jobs/~01f4c10e0e27ccfb95), so that I can pay you $125? Thanks!

**Comment by conorpendergrast** [comment] 2023-11-14 21:58
@allroundexperts [C+ checklist](https://github.com/Expensify/App/issues/30792#issuecomment-1796797910) please!

**Comment by conorpendergrast** [comment] 2023-11-15 10:04
@erquhart Contract sent!

**Comment by conorpendergrast** [comment] 2023-11-15 20:50
Payouts due:

- [x] Contributor: $125 @erquhart [contract paid and ended](https://www.upwork.com/nx/wm/workroom/35457049/overview)
Contributor+: $500 @allroundexperts - manual request

Upwork job is [here](https://www.upwork.com/jobs/~01f4c10e0e27ccfb95).

**Comment by mountiny** [comment] 2023-11-20 16:27
@conorpendergrast has this been paid out then, can we close this?

**Comment by erquhart** [comment] 2023-11-20 17:01
@mountiny I can confirm I have been paid, and I'm the only one on the list.

**Comment by conorpendergrast** [comment] 2023-11-20 20:53
Yep, it has been paid, but the C+ checklist is outstanding for @allroundexperts  I think (hence why I haven't closed this yet)

**Comment by conorpendergrast** [comment] 2023-11-20 21:22
Right, and it was caught via Applause by a regression test. Ok, thanks for making that clear! Closing out, we did it, hooray

**Closed by conorpendergrast** 2023-11-20 21:22 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
