### ISSUE TITLE
[HOLD PR #23994][$1000] The keyboard is re rendered when an emoji appears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22052] opened 2023-07-02 02:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) select a chat
2) click on emoji
3) select a emoji
## Expected Result: 
the keyboard should not  re-rendered when we select an emoji
## Actual Result:
 keyboard is re-rendered when we select an emoji and also there is a flickering of the page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e71d1bfb-0967-4ce4-9d05-40f05a2272f0

https://github.com/Expensify/App/assets/43996225/a96b284e-d501-4e15-ad9e-ebb5862c7133

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eusalazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688152676612889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db7d5a756e5284d5</li>
        <li>Upwork Job ID: 1676298806542942208</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by nitin-kukreti** [comment] 2023-07-02 11:08
according to Expected Result and Actual Result this is not an issue as they both are same

**Comment by kavimuru** [comment] 2023-07-02 22:42
@nitin-kukreti updated the steps, Keyboard rerenders and also you can see a weird flicker of the page too.

**Comment by mallenexpensify** [comment] 2023-07-04 18:36
was able to reproduce, moving along

**Comment by soustab10** [comment] 2023-07-04 22:07
The problem will be solved by: leveraging the shouldComponentUpdate method in thecomponent and checking for specific conditions related to the keyboard event.
```
import React, { Component } from 'react';
import { TextInput } from 'react-native';

class EmojiSafeTextInput extends Component {
  shouldComponentUpdate(nextProps) {
    // Prevent re-rendering when the keyboard event is related to emoji selection
    if (
      this.props.value !== nextProps.value ||
      (this.props.selection && nextProps.selection &&
        this.props.selection.start === nextProps.selection.start &&
        this.props.selection.end === nextProps.selection.end)
    ) {
      return false;
    }
    return true;
  }

  render() {
    return <TextInput {...this.props} />;
  }
}

export default EmojiSafeTextInput;
```

In this example, the EmojiSafeTextInput component extends the TextInput component from React Native. The shouldComponentUpdate method is overridden to handle comparing the value and selection properties. If the selection's value or start and end positions remain the same, indicating an emoji selection event, the method returns false, preventing the component from re-rendering. 

Another way could be to use: Memoized Selectors with Reselect
[Reselect](https://www.npmjs.com/package/reselect) is a third-party React library for creating memorized selectors. It is commonly used with Redux stores and has amazing features to reduce unnecessary re-renderings.

Reselect selectors are capable of computing derived data.
Reselect selectors do not recompute unless their arguments are changed.
They can be used as inputs to other selectors.
Reselect provides an API named createSelector, and it can generate memoized sector functions.

**Comment by soustab10** [comment] 2023-07-04 22:09
Contributor details
Your Expensify account email: soustabhaldar10@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01027be2b5196dd817

**Comment by kpadmanabhan** [comment] 2023-07-05 05:25
Contributor details
Your Expensify account email: krispv@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01063aad97ce0e22c6

**Comment by abdulrahuman5196** [comment] 2023-07-07 20:15
Will provide review on the proposals in the morning

**Comment by abdulrahuman5196** [comment] 2023-07-08 15:36
@soustab10 Kindly follow the proposal template https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md while proposing a solution

**Comment by abdulrahuman5196** [comment] 2023-07-08 15:48
What do we mean by `the keyboard should not re-rendered when we select an emoji` in expected result here?
Do we mean that the keyboard shouldn't come up? or keyboard should come up but without flicker?
@mallenexpensify

**Comment by situchan** [comment] 2023-07-08 15:50
Dupe of #13922

**Comment by ShogunFire** [comment] 2023-07-10 18:26
I don't think it's dupe

**Comment by ShogunFire** [comment] 2023-07-10 18:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Thea animation with the keyboard looks weird when we come back from the emoji picker

### What is the root cause of that problem?

Here:
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/EmojiPicker/EmojiPicker.js#L39
We dismiss the keyboard before opening the emoji picker.
The keyboard avoiding view animation has two animations: when we close the keyboard and when we open it. 

When we open the emoji picker the keyboard is closed but the closing animation is not done 
When we come back, the two animations are done (closing and opening) which makes the transition looks weird.

### What changes do you think we should make in order to solve the problem?


I don't see a reason to dismiss the keyboard here:
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/EmojiPicker/EmojiPicker.js#L39
So we can just remove this line and it looks better: 
Before removing:


https://github.com/Expensify/App/assets/19537677/d067cc6c-456c-4b35-856b-1e4af949af77

After removing:

https://github.com/Expensify/App/assets/19537677/717857b9-9dcd-4d90-9f0c-85aa7f48224a


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mallenexpensify** [comment] 2023-07-11 03:47
> What do we mean by the keyboard should not re-rendered when we select an emoji in expected result here?
Do we mean that the keyboard shouldn't come up? or keyboard should come up but without flicker?

@abdulrahuman5196 , the latter, "keyboard should come up but without flicker?"  is what I was thinking. Maybe that's a polish, possibly feature request though, ¯\_(ツ)_/¯

**Comment by ShogunFire** [comment] 2023-07-11 04:06
@mallenexpensify Do you think the result of my proposal is acceptable ?

**Comment by abdulrahuman5196** [comment] 2023-07-13 16:33
Will check the proposals in couple of hours

**Comment by mallenexpensify** [comment] 2023-07-17 21:18
@abdulrahuman5196 plz review the above proposals

**Comment by abdulrahuman5196** [comment] 2023-07-18 16:10
Sorry for the delay. Caught up in PR reviews. Will provide the review before a day.

**Comment by shubham1206agra** [comment] 2023-07-19 14:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

The keyboard is re rendered when an emoji appears

### What is the root cause of that problem?
In

https://github.com/Expensify/App/blob/16a83ac373c2103add1e416d2b33b2365ab1b87f/src/components/EmojiPicker/EmojiPicker.js#L74
and
https://github.com/Expensify/App/blob/16a83ac373c2103add1e416d2b33b2365ab1b87f/src/components/EmojiPicker/EmojiPicker.js#L39
The action `Keyboard.dismiss()` and `setIsEmojiPickerVisible(true)` are executed asynchronous. Besides, iOS will dismiss the keyboard when popover is opened and open again when it's closed

### What changes do you think we should make in order to solve the problem?
In

https://github.com/Expensify/App/blob/16a83ac373c2103add1e416d2b33b2365ab1b87f/src/components/EmojiPicker/EmojiPicker.js#L72-L78

If keyboard is opening then we'll dismiss keyboard and open popover in `keyboardDidHide` listener. Otherwise I just open popover. We will check the previous state of the Keyboard using `withKeyboardState` which provides prop `isKeyboardShown`.
```js
        calculateAnchorPosition(emojiPopoverAnchor.current).then((value) => {
            onWillShow();
            setEmojiPopoverAnchorPosition(value);
            emojiPopoverAnchorOrigin.current = anchorOrigin || DEFAULT_ANCHOR_ORIGIN;
            setReportAction(reportActionValue);
            if (!props.isKeyboardShown) {
                setIsEmojiPickerVisible(true);
                return;
            }
            const listener = Keyboard.addListener('keyboardDidHide', () => {
                setIsEmojiPickerVisible(true);
                listener.remove();
            });
            Keyboard.dismiss();
        });
```


### Result

https://github.com/Expensify/App/assets/58412969/a0b98585-c4ba-41c6-85da-46600fcc54a9

**Comment by abdulrahuman5196** [comment] 2023-07-19 19:24
Reviewing this now

**Comment by abdulrahuman5196** [comment] 2023-07-19 19:31
> Dupe of #13922

@mallenexpensify I too think its a dupe. Same root cause of ios keyboard flicker with modal, but just in a different place.

**Comment by abdulrahuman5196** [comment] 2023-07-24 12:39
@mallenexpensify Could you check on this https://github.com/Expensify/App/issues/22052#issuecomment-1642644023
We could merge issue based on which issue is more progressed

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:54
@mallenexpensify Gentle ping on this https://github.com/Expensify/App/issues/22052#issuecomment-1647836703

**Comment by abdulrahuman5196** [comment] 2023-08-03 13:02
@mallenexpensify We should just close this. The other issue has a contributor assigned

**Comment by abdulrahuman5196** [comment] 2023-08-03 15:11
Thanks for the information @ntdiary . Then I think we can have this on hold @mallenexpensify just to reverify after the other issue is closed.

**Comment by mallenexpensify** [comment] 2023-08-10 04:45
@ntdiary I saw you got hired for https://github.com/Expensify/App/issues/13922 last week, do you think it's best to put this on hold, pending that being fixed or should we fix this independently?  Also.. thanks for the comments above.  Also, also... sorry I've been lagging (espec to @abdulrahuman5196 ), I was out a bit and have a project with a deadline I've been focused on.

**Comment by mallenexpensify** [comment] 2023-08-23 14:05
Thanks @ntdiary , put this on hold pending
https://github.com/Expensify/App/pull/23994

**Comment by shubham1206agra** [comment] 2023-08-24 06:57
Looks like this is fixed now. https://github.com/Expensify/App/pull/23994#issuecomment-1690239398
@mallenexpensify You can close this one.

**Comment by mallenexpensify** [comment] 2023-09-04 02:09
Closing.  The bug reporting bounty isn't eligible because https://github.com/Expensify/App/issues/13922 was reported well before this issue
<img width="303" alt="image" src="https://github.com/Expensify/App/assets/22508304/29e128cf-5941-4510-9e71-d53710a8711b">

<img width="505" alt="image" src="https://github.com/Expensify/App/assets/22508304/8e5fef67-dec8-4e7e-ad8a-dd60a6a2b9e8">

**Closed by mallenexpensify** 2023-09-04 02:09 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
