### ISSUE TITLE
Assign task - Creating a task offline does not save "Title" and "Description"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20230] opened 2023-06-06 00:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/19749
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in [applausetester+0709izv@applause.expensifail.com](mailto:applausetester+0709izv@applause.expensifail.com)
3. Click on FAB button -> Click on Assign task option
4. Enter title & description -> add any assignee -> Click on confirm task
5. On task detail page click on Description -> clear title field and press save
6. Go offline
7. Repeat steps 3-5
8. Go back online

## Expected Result:
Data entered offline saved

## Actual Result:
If you create a task offline immediately after creating it online, it does not save the "Title" and "Description"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/35444fc4-8864-4cf0-8a11-409c019d7ff4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team 

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-06-06 09:25
I tested on OSX Chrome, and could not reproduce. 

**The details of the task I added offline:** 

<img width="405" alt="image" src="https://github.com/Expensify/App/assets/5802477/430ea212-cb26-4f30-9f30-3daa28309d8c">

**The details of the task created when I went online:** 

<img width="1082" alt="image" src="https://github.com/Expensify/App/assets/5802477/07e57694-d7d9-4a29-a215-34af9fc0e2b7">

**Comment by conorpendergrast** [comment] 2023-06-06 09:50
I have tested this four times and haven't been able to reproduce it yet! 

I did find a somewhat related issue which I posted about here https://expensify.slack.com/archives/C049HHMV9SM/p1686044959556469

**Comment by conorpendergrast** [comment] 2023-06-06 09:53
I tried reproducing this on iOS Chrome too, and also wasn't able to reproduce there

**Comment by conorpendergrast** [comment] 2023-06-06 10:07
One thing that's unclear from the reproduction steps, what does this mean? 

> On task detail page click on Description -> clear title field and press save

**Comment by conorpendergrast** [comment] 2023-06-09 14:53
I still haven't been able to reproduce this today. I'm closing as a result!

**Closed by conorpendergrast** 2023-06-09 14:53 UTC
Labels: Daily, Overdue, Bug
