### ISSUE TITLE
"Expensify chat" is shown in contact list for "start chat"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44750] opened 2024-07-02 21:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-6 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719906408139169

## Action Performed:
Scenario1:
1. Go to staging.new.expensify.com and login
2. Click FAB > Start chat
3. Observe the contact list
Scenario 2: 
Create a group with "concierge" and "Expensify"

## Expected Result:

- "Expensify" should not display in the contact list as can't initiate a chat
- Shouldn't be able to create a group for the above reason

## Actual Result:
- "Expensify" appears in the contact list
- In gmail domain able to initiate the chat
- Able to create a group 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-07-02 at 09 48 46@2x](https://github.com/Expensify/App/assets/38435837/0f8e5881-fafe-48a0-a02f-7755eb13354e)
![CleanShot 2024-07-02 at 09 47 52@2x](https://github.com/Expensify/App/assets/38435837/465b97c6-649c-421d-9340-694a5690ffa2)
![CleanShot 2024-07-02 at 09 47 02@2x](https://github.com/Expensify/App/assets/38435837/ff33f5bc-3e72-4806-8aed-4b55a01a989b)
![image (40)](https://github.com/Expensify/App/assets/38435837/26307339-a352-47b3-98c6-1483fbb34efc)
![Snip - (3) New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/38435837/99f0ddae-e951-441b-ae2c-54557217e9e1)
![Snip - (3) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/245603a6-9ade-48c8-b66f-ba90dec1b23f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neonbhai** [comment] 2024-07-02 23:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Expensify chat" is shown in contact list for "start chat"

### What is the root cause of that problem?
We use the `isGroupChat` here as a prop, but we don't ever set it. 

https://github.com/Expensify/App/blob/fc045a8cf01a74e2879ed911c64e5ece2dca9ecf/src/pages/NewChatSelectorPage.tsx#L34

This needs to be variable on the page, and may have been missed over the refactors.

### What changes do you think we should make in order to solve the problem?
We should have `isGroupChat` as a variable in `NewChatPage` calculated as:

```jsx
const isGroupChat = selectedOptions.length > 0;
```
This will be used [here](https://github.com/Expensify/App/blob/fc045a8cf01a74e2879ed911c64e5ece2dca9ecf/src/pages/NewChatPage.tsx#L137-L139) and [here](https://github.com/Expensify/App/blob/fc045a8cf01a74e2879ed911c64e5ece2dca9ecf/src/pages/NewChatPage.tsx#L320) to carry out the group chat logic.

This will mean that we will remove this from prop definition [here](https://github.com/Expensify/App/blob/fc045a8cf01a74e2879ed911c64e5ece2dca9ecf/src/pages/NewChatPage.tsx#L126) and [here](https://github.com/Expensify/App/blob/fc045a8cf01a74e2879ed911c64e5ece2dca9ecf/src/pages/NewChatPage.tsx#L38-L40)

**Comment by bernhardoj** [comment] 2024-07-03 03:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify notification chat is able to be added to a group.

### What is the root cause of that problem?
In https://github.com/Expensify/App/pull/41290, we allow the Expensify notification chat to be listed in the list (specifically this [change](https://github.com/Expensify/App/pull/41290/files#diff-7d43f3c3e4decdb0057928e895f456d51c0f4081837edd5e2c4ed7ddd570e274L1870)).

But we forgot to cover the case where the user is able to add the Expensify notification to a group.

The `isGroupChat` prop is a very old prop added first in https://github.com/Expensify/App/pull/5138. At that time, we had a new chat and a new group page separated. New group page uses new chat page and pass down the `isGroupChat`.

### What changes do you think we should make in order to solve the problem?

To keep both behavior of https://github.com/Expensify/App/pull/41290 and https://github.com/Expensify/App/pull/5138, we can hide the "Add to group" button when it's the excluded account.
https://github.com/Expensify/App/blob/5ab6be6ecb01d6398eb2503dbd3f6dad60d6638f/src/pages/NewChatPage.tsx#L210-L214

```
if (item.isSelfDM || excludedGroupEmails.includes(item.login ?? '')) {
    return null;
}
```

Then, consider removing the unused `isGroupChat` prop.

**Comment by shawnborton** [comment] 2024-07-03 06:22
I actually think I'm just going to close this, as we did decide that Expensify should still remain in your contacts list. 

And I can't reproduce being able to chat with the Expensify contact using a Gmail account login.

**Closed by shawnborton** 2024-07-03 06:22 UTC
Labels: Daily, Bug

**Comment by bernhardoj** [comment] 2024-07-03 07:42
@shawnborton I think we can take this chance to not allow Expensify to be added to a group, so we can prevent this [issue too](https://github.com/Expensify/App/issues/43841).

**Comment by shawnborton** [comment] 2024-07-03 07:44
Well I'm not actually sure if we want to prevent that or not - it seems like we want to just treat this contact like a normal contact? cc @danielrvidal in case you have thoughts there.
