### ISSUE TITLE
[HOLD for payment 2022-08-08] [$250] "No results found" text is not shown when a user search a non existing currency - reported by @thesahindia 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9981] opened 2022-07-19 04:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Fab icon > send money
2. Click on currency
3. Search a currency that doesn't exist

## Expected Result:
We should see "No results found"

## Actual Result:
We don't see the "No results found" text

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.84-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="371" alt="Screenshot 2022-07-09 at 1 39 14 AM" src="https://user-images.githubusercontent.com/43995119/179666857-f33cb5d0-63e1-4cfe-93da-1d29d2d728d1.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657311583630489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment] 2022-07-19 12:15
I think this is by design, but going to escalate up just in case.

**Comment by mountiny** [comment] 2022-07-19 12:19
I don't see in the code that this would be implemented for the currency search but it makes sense to add it there. Showing blank screen is not good UX.

**Comment by arielgreen** [comment] 2022-07-19 16:00
https://www.upwork.com/jobs/~01b00a8524a966eef0

**Comment by yevheniiochkalov** [comment] 2022-07-19 17:14
I just joined the slack and I can implement this if you provide the design for no result. Will you assign this task for a new developer?

**Comment by metehanozyurt** [comment] 2022-07-19 17:28
## Proposal
### Cause

"No results found" text is not shown when currency list size 0.

### Solution
We can do it like emoji search screen . if size of currency list size 0 we can pass param (`shouldShowNoData`) and show "No results found".
For this method, we need to update three files.

Step 1 -) `IOUCurrencySelection` Component

https://github.com/Expensify/App/blob/1fc51f49388ff00978ecfc213733c4ba1363fd19/src/pages/iou/IOUCurrencySelection.js#L97-L100

Need to change like this

```js
this.setState({
            searchValue,
            currencyData: currencyOptions,
            shouldShowNoData: currencyOptions.length === 0,
        });
```

and


https://github.com/Expensify/App/blob/1fc51f49388ff00978ecfc213733c4ba1363fd19/src/pages/iou/IOUCurrencySelection.js#L122-L129

Need to change like this
```diff
<OptionsSelector
                        sections={this.getSections()}
                        onSelectRow={this.confirmCurrencySelection}
                        value={this.state.searchValue}
                        onChangeText={this.changeSearchValue}
                        shouldDelayFocus
                        placeholderText={this.props.translate('common.search')}
+ shouldShowNoData={this.state.shouldShowNoData}
                    />
```
Step 2 -) `OptionsSelector` Component

https://github.com/Expensify/App/blob/1fc51f49388ff00978ecfc213733c4ba1363fd19/src/components/OptionsSelector.js#L361-L375
change like this
```diff
<OptionsList
                ref={el => this.list = el}
                optionHoveredStyle={this.props.optionHoveredStyle}
+ shouldShowNoData={this.props.shouldShowNoData}
+ translate={this.props.translate} //I don't think this will be allowed, I just added it so that the code does not give an error.
                onSelectRow={this.selectRow}
                sections={this.props.sections}
                focusedIndex={this.state.focusedIndex}
                selectedOptions={this.props.selectedOptions}
                canSelectMultipleOptions={this.props.canSelectMultipleOptions}
                hideSectionHeaders={this.props.hideSectionHeaders}
                headerMessage={this.props.headerMessage}
                hideAdditionalOptionStates={this.props.hideAdditionalOptionStates}
                forceTextUnreadStyle={this.props.forceTextUnreadStyle}
                showTitleTooltip={this.props.showTitleTooltip}
                isDisabled={this.props.isDisabled}
            />
```
Step 3 -) `BaseOptionsList` component

https://github.com/Expensify/App/blob/cf6bb2a0c12baf5183423fb39c64fc7ae4a958af/src/components/OptionsList/BaseOptionsList.js#L225-L245

change like this 

```js
 {this.props.shouldShowNoData ? (
                    <View style={[styles.ph5, styles.pb5]}>
                    <Text
                    style={[
                        styles.disabledText,
                        styles.justifyContentCenter,
                        styles.dFlex,
                        styles.alignItemsCenter,
                        styles.notFoundView
                    ]}
                >
                    {this.props.translate('common.noResultsFound')}
                </Text>
                    </View>
                ):(
                <SectionList
                    ref={this.props.innerRef}
                    indicatorStyle="white"
                    keyboardShouldPersistTaps="always"
                    keyboardDismissMode={this.props.keyboardDismissMode}
                    onScrollBeginDrag={this.props.onScrollBeginDrag}
                    contentContainerStyle={this.props.contentContainerStyles}
                    showsVerticalScrollIndicator={false}
                    sections={this.props.sections}
                    keyExtractor={this.extractKey}
                    stickySectionHeadersEnabled={false}
                    renderItem={this.renderItem}
                    getItemLayout={this.getItemLayout}
                    renderSectionHeader={this.renderSectionHeader}
                    extraData={this.props.focusedIndex}
                    initialNumToRender={5}
                    maxToRenderPerBatch={5}
                    windowSize={5}
                    viewabilityConfig={this.viewabilityConfig}
                    onViewableItemsChanged={this.onViewableItemsChanged}
                />)}
```
video:

https://user-images.githubusercontent.com/6093207/179812374-24ccfed2-8689-4e7f-a34b-972b79278460.mp4

**Comment by parasharrajat** [comment] 2022-07-19 17:45
Not the way it should be done. I don't like the proposal, @metehanozyurt. Please find another solution to fix it.

**Comment by dhairyasenjaliya** [comment] 2022-07-19 17:53
**Proposal**

- Here for send/request (select currency page) -> we need to add a header error message same as the user search list page

**Solution**

- In src/libs/OptionsListUtils we need to create a validation to check if currency exists or not if it does not exist return No result found

 ```
/**
 * Validate Currency search
 *
 * @param {Number} currencyObjectLength
 * @param {String} searchValue
 * @returns {String}
 */
function isCurrencyAvailable(currencyObjectLength, searchValue) {
    const newLocal = currencyObjectLength === 0 && searchValue;
    if (newLocal) {
        return Localize.translate(preferredLocale, 'common.noResultsFound');
    }
}

export { 
    isCurrencyAvailable,
};
```

- and in /src/pages/iou/IOUCurrencySelection.js

https://github.com/Expensify/App/blob/703070de3ea592a4116de17ed0713f05ee7eb73a/src/pages/iou/IOUCurrencySelection.js#L114-L118

 ````

render() {
        const headerMessage = OptionsListUtils.isCurrencyAvailable(this.state.currencyData.length, this.state.searchValue); // add validation finction

        return (
            <ScreenWrapper>
                <KeyboardAvoidingView>
                    <HeaderWithCloseButton
                        title={this.props.translate('iOUCurrencySelection.selectCurrency')}
                        onCloseButtonPress={Navigation.goBack}
                    />
                    <OptionsSelector
                        sections={this.getSections()}
                        onSelectRow={this.confirmCurrencySelection}
                        value={this.state.searchValue}
                        onChangeText={this.changeSearchValue}
                        shouldDelayFocus
                        placeholderText={this.props.translate('common.search')}
                        headerMessage={headerMessage} // pass message to option selector
                    />
                </KeyboardAvoidingView>
            </ScreenWrapper>
        ); 
    }
   ````

**Result**
   
  

https://user-images.githubusercontent.com/47522946/179816243-15d78bee-d265-418c-8991-f5ad3b6bd06b.mp4

**Comment by parasharrajat** [comment] 2022-07-19 18:33
@dhairyasenjaliya your proposal looks good to me.

A few points:
1. We don't have to create a new function in `OptionsListUtils` as this will be used once. 

Do we want to hide the all currencies header as well? cc: @mountiny 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by parasharrajat** [comment] 2022-07-19 18:52
Ok. @dhairyasenjaliya Please remove the `all currencies` header besides showing the `no search result` under the search bar in your PR.

**Comment by dhairyasenjaliya** [comment] 2022-07-19 18:56
sure will do changes soon as per discussed above and create PR

**Comment by dhairyasenjaliya** [comment] 2022-07-20 04:01
hello @parasharrajat @mountiny PR is Up, since this is my first PR let me know if I missed out anything 
thank you

**Comment by mountiny** [comment] 2022-07-20 09:08
Thank you for the message @dhairyasenjaliya! Gonna have a look!

**Comment by arielgreen** [comment] 2022-07-28 00:49
@dhairyasenjaliya can you please be sure to apply to the job on Upwork since we issue payment over there? https://www.upwork.com/jobs/~01b00a8524a966eef0

**Comment by dhairyasenjaliya** [comment] 2022-07-28 07:37
@arielgreen sorry totally missed out, applied now thanks for reminding

**Comment by arielgreen** [comment] 2022-08-08 18:51
@parasharrajat @thesahindia @dhairyasenjaliya hired in Upwork, please accept and I will remit payment

**Comment by dhairyasenjaliya** [comment] 2022-08-09 00:23
@arielgreen job expired

**Comment by arielgreen** [comment] 2022-08-09 00:27
Paid @parasharrajat @thesahindia 

@dhairyasenjaliya I just sent a new offer.

**Comment by dhairyasenjaliya** [comment] 2022-08-09 00:35
@arielgreen accepted

**Comment by arielgreen** [comment] 2022-08-09 00:37
Paid!

**Closed by arielgreen** 2022-08-09 00:37 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Awaiting Payment
