### ISSUE TITLE
[$250] Onboarding  - Infinite loop in onboarding modal when coming from OD via Support

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51481] opened 2024-10-25 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5121161
**Issue reported by:** Applause - Internal Team

## Action Performed:
1.    Go to https://staging.expensify.com/
2.    Get started with “Organize my own expenses” option
3.    Verify you redirect to NewDot and Onboarding modal appears
4.    Click on "Chat and split expenses with friends" option on the Onboarding modal
5.    Enter user name and click Continue button

## Expected Result:
The user can complete the onboarding flow and is brought to the NewDot concierge chat

## Actual Result:
The user remains stuck in an infinite loop in the "What do you want to do today?" modal when he chooses the "Chat and split expenses with friends" option.
By selecting any other option, for instance, "Get paid back by my employer" the loop ends.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/aafc47b6-edf6-419b-b02e-81774d5959ff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850366174167695381</li>
        <li>Upwork Job ID: 1850366174167695381</li>
        <li>Last Price Increase: 2024-11-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment] 2024-10-25 15:45
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment] 2024-10-27 02:37
Yikes, this one is pretty bad - this is what I see in my LHN when I select the `split` option:

![image](https://github.com/user-attachments/assets/ccfb9eda-001b-4054-85ac-2b110c456928)

I can also confirm the `Track` option works fine and gets you out of the loop:

![image](https://github.com/user-attachments/assets/7bfed565-6eeb-4ffc-a316-1e10e3ad2fe6)

**Comment by jliexpensify** [comment] 2024-10-30 23:41
Bump @fedirjh we have a proposal for you to review.

**Comment by jliexpensify** [comment] 2024-11-01 10:07
DM-ed Fedi on Slack

**Comment by muttmuure** [comment] 2024-11-05 10:48
Removing due to low reproducibility

**Comment by jliexpensify** [comment] 2024-11-06 01:57
Thanks @fedirjh - added!

**Comment by mvtglobally** [comment] 2024-11-16 01:54
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2024-11-17 22:41
Nice, will wait another week of testing before closing.

**Comment by jliexpensify** [comment] 2024-11-22 09:37
Waiting on a final test from Applause

**Comment by mvtglobally** [comment] 2024-11-23 03:27
Issue not reproducible during KI retests. (Second week)

**Comment by jliexpensify** [comment] 2024-11-24 22:00
Great, lets close!

**Closed by jliexpensify** 2024-11-24 22:00 UTC
Labels: External, Weekly, Help Wanted, Bug, retest-weekly
