### ISSUE TITLE
Hovering over a user's icon in thread should show First/Last name over email if it exists

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19709] opened 2023-05-27 00:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Hover over the avatar for a thread
## Expected Result: 
See that it displays First/Last name if they have it set
## Actual Result: 
It displays email no matter what

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7fdbb3d2-84b1-4bc4-8e16-ee0108f12d2e

![image](https://github.com/Expensify/App/assets/43996225/72c23694-4ebf-47dd-9bf3-1a73ddff2ed0)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @johnmlee101 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684942216749499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-05-27 00:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hovering over a user's icon in thread should show First/Last name over email if it exists
### What is the root cause of that problem?
we always show actorEmail in the Tooltip
### What changes do you think we should make in order to solve the problem?
we need to show displayName if found and actorEmail is afallback
<Tooltip text={displayName || actorEmail}>

### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment] 2023-05-30 09:02
Copying over @chiragsalian's assessment for next steps:

> Okay so next steps:
> Once this bug report is created, tweak it so that it covers all avatar tooltips and not just thread preview avatar tooltips.
> Open up a pre-discussion to find out what would be best for the future of avatar tooltips.
> Implement it.

**Comment by grgia** [comment] 2023-06-02 12:53
I think there's been discussion about this in multiple issues/slack. Unsure if there's been a consensus- will look for links

**Comment by grgia** [comment] 2023-06-05 13:08
Waiting on an update from this project - https://expensify.slack.com/archives/C04QEB4MJEQ/p1685949949888349

**Comment by puneetlath** [comment] 2023-06-05 13:59
I think we should potentially close this issue, as we're updating the tooltip here: https://github.com/Expensify/App/issues/20086

**Comment by grgia** [comment] 2023-06-05 14:04
Sweet I agree with that, closing this out

**Closed by grgia** 2023-06-05 14:04 UTC
Labels: Daily, Bug
