### ISSUE TITLE
[$500] Chat - The "Hmm... it's not here" page opens when navigating to the IOU link while logged out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37756] opened 2024-03-05 14:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4378479
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with Gmail account
3. Create a IOU in a conversation
4. Navigate to the IOU report (conversation)
5. Copy the URL
6. Log out of the app
7. Navigate to the IOU URL
8. Log in

## Expected Result:
User redirected to the correct IOU report after login

## Actual Result:
The "Hmm... it's not here" page opens when navigating to the IOU link while logged out

## Workaround:
Paste the URL again, or re-navigate to the page.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3f1a1c19-2312-49ab-9a29-7c161efddcd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01782db70707abf0d2</li>
        <li>Upwork Job ID: 1765026380134027264</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2024-03-05 14:47
Not critical enough to be a blocker. We'll fix, and I have shared a comment in our open-source channel to see if anyone is aware of changes to our deep link, routing logic.

**Comment by webbdays** [comment] 2024-03-05 17:13
Problem seems to occur when there is no message still in the chat of that report for the user.

**Comment by omarnagy91** [comment] 2024-03-05 17:50
**Proposal**

**Problem:** IOU report links generated within the application are being incorrectly prefixed with "/w/[policyID]". This is leading to the "Hmm...it's not here" error when users try to access the IOU report via the link.

**Root Cause:** The `customGetPathFromState` function, which is responsible for generating URLs from the navigation state, is unconditionally adding the policy ID prefix. IOU report links, however, should not have this prefix.

**Changes to Solve the Problem:**

I need to modify the `customGetPathFromState` function to implement conditional logic. Here's the proposed update:


```
const customGetPathFromState: typeof getPathFromState = (state, options) => {
  // ... (your existing removePolicyIDParamFromState logic) ...

  const path = getPathFromState(stateWithoutPolicyID, options);
  const policyIDFromState = getPolicyIDFromState(state as State<RootStackParamList>);

  // Only add prefix if the following conditions are met:
  if (policyIDFromState && !path.startsWith('/r/') && !path.includes('workspace/')) { 
    return `/w/${policyIDFromState}${path}`; 
  }

  // No prefix needed
  return path; 
};

```


**Explanation:**

-   The  `/r/`  check prevents corruption of IOU links, which should have a path like "/r/[report_number]".
-   The  `workspace/`  check avoids adding the prefix to workspace-related URLs.
-   If the conditions are not met, the path is returned without the prefix.

**Alternative Solutions Explored:**

1.  **Modifying IOU Link Generation:**  I considered changing how IOU links are generated to always include the policy ID prefix, but this would have required changes in potentially multiple places.
2.  **Complex State Handling:**  I could have introduced more complex logic in other navigation functions to handle the policy ID, but this would risk making the navigation system harder to maintain.

The proposed solution directly addresses the problem within a single function, promoting clarity and maintainability.

**Let's implement this updated `customGetPathFromState` function and thoroughly test IOU link creation and navigation. I'm confident this will resolve the issue!**

**Comment by Julesssss** [comment] 2024-03-06 09:41
It seems like this is a dupe of [this original bug](https://github.com/Expensify/App/issues/34528)

**Closed by Julesssss** 2024-03-06 09:41 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted
