### ISSUE TITLE
Web - 'You'll lose any offline changes if you sign-out.' message appears even if you are online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23742] opened 2023-07-27 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings
2. click on Sign out button
## Expected Result: 
user should be Sign out
## Actual Result: 
shows 'You'll lose any offline changes if you sign-out.' message even if you are online

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cfd52b31-a124-408d-a1d8-d1f95837c19d

https://github.com/Expensify/App/assets/93399543/bcc5a754-8a23-4c94-8919-c6c2fc756e6b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690436737183979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alphaboss1104** [comment] 2023-07-27 16:06
I can't reproduce it.

**Comment by gadhiyamanan** [comment] 2023-07-27 16:44
This is regression from https://github.com/Expensify/App/issues/16281#issuecomment-1652952760

**Comment by mananjadhav** [comment] 2023-07-28 11:12
@mountiny @slafortune  this is a regression from https://github.com/Expensify/App/issues/16281. Awaiting response on this.

**Comment by mountiny** [comment] 2023-07-28 12:30
@mananjadhav given its deploy blocker and the contributor hasnt messaged I have created the PR

**Comment by mananjadhav** [comment] 2023-07-28 12:42
@mountiny I’ll be able go check this in an hour, afk

**Comment by mountiny** [comment] 2023-07-28 14:19
No problem merged going to CP

**Comment by mountiny** [comment] 2023-07-28 15:25
@slafortune Can we pay @gadhiyamanan $250 for reporting this bug?

**Comment by slafortune** [comment] 2023-07-28 19:10
@gadhiyamanan offer sent here - https://www.upwork.com/nx/wm/offer/25815360

**Comment by gadhiyamanan** [comment] 2023-07-29 02:35
@slafortune offer accepted, thanks!

**Comment by slafortune** [comment] 2023-07-31 14:03
Thanks - Paid!

**Closed by slafortune** 2023-07-31 14:03 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
