### ISSUE TITLE
[HOLD] Chat - Uploading svg attachment adds expensify link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22837] opened 2023-07-13 19:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any svg file (make sure file name does not have space in it, we have another issue ongoing for that error)
4. Observe that it displays staging.expensify.com preview

## Expected Result:
App should not display link preview on adding of attachment

## Actual Result:
App displays staging.expensify.com link preview on adding svg attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e5f3d203-85fa-4e09-a221-d6335b6c5766

https://github.com/Expensify/App/assets/93399543/a8b3a25b-58c1-4ca3-ad7a-d65e753e6398

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689271577154629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e07c18c1ab1b1ac1</li>
        <li>Upwork Job ID: 1679592994912608256</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-07-13 19:47
This is not repro with production API so it seems to be web api blocker https://expensify.slack.com/archives/C049HHMV9SM/p1689277141817099?thread_ts=1689271577.154629&cid=C049HHMV9SM

**Comment by francoisl** [comment] 2023-07-13 20:45
Must have been Web, but the deploy already went out today. I'm able to reproduce the issue on production NewDot now, so this is something we'll fix separately and CP if necessary. No need to block the NewDot deploy on this, going to remove the label.

**Comment by bondydaa** [comment] 2023-07-13 20:54
<img width="954" alt="image" src="https://github.com/Expensify/App/assets/4073354/f44b04f8-1541-4238-b2e9-0ed068f4ef50">

sorry so this isn't a deploy blocker now?

**Comment by francoisl** [comment] 2023-07-13 21:04
Not a **NewDot** deploy blocker. It would (should?) have been a Web-E deploy blocker, but I don't think the deployer realized that in time, and the deploy already went out about an hour ago. 
https://expensify.slack.com/archives/C07J32337/p1689278195820979

**Comment by francoisl** [comment] 2023-07-13 21:05
Oh I see what you mean, some weird stuff went on with the labels here. We can remove the DeployBlocker label.

**Comment by bondydaa** [comment] 2023-07-13 21:09
ah coolio thanks for cleaning those up.

@marcaaron i know you were doing stuff for the link previews, not sure that is directly involved here but something is treating svgs as links for some reason.

There was another thread yesterday about mime types for csv or pdfs that weren't working properly so wonder if that's related somehow here where when the svg is uploaded it's got the wrong mime type and therefore gets uploaded as something else which returns a link and thus why the link preview shows up?

**Comment by bondydaa** [comment] 2023-07-13 21:17
nvm on the mime type stuff, found the logs and it looks like the correct mime types were detected:

```
7e63e35d19a03ba6-BOS	2023-07-13 19:21:17 709	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	Processing file attachment upload ~~ cleanedFileName: 'svg_logo-1.svg' fileMimeType: 'image/svg+xml; charset=us-ascii' fileExtension: 'svg' uploadedFileType: 'image/svg+xml'
7e63e35d19a03ba6-BOS	2023-07-13 19:21:17 709	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	Starting file upload virus scan ~~ filename: '/tmp/phpVr68TJ'
7e63e35d19a03ba6-BOS	2023-07-13 19:21:17 719	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	File upload virus scan results ~~ filename: '/tmp/phpVr68TJ' version: 'ClamAV 0.103.6/26968/Thu Jul 13 07:29:43 2023' ping: '1' containsVirus: ''
7e63e35d19a03ba6-BOS	2023-07-13 19:21:17 719	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	S3Bucket_Receipts - Upload file
7e63e35d19a03ba6-BOS	2023-07-13 19:21:17 719	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	S3Bucket_Receipts - Create S3 Obj ~~ classname: 'S3Bucket_Receipts' region: 'us-east-1'
7e63e35d19a03ba6-BOS	2023-07-13 19:21:17 721	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	S3Bucket_Receipts - Uploading... ~~ path: '/tmp/phpVr68TJ' name: 'w_c4e7398682bfb347968150d1d489e7875133d1f2.svg' size: '4,210'
7e63e35d19a03ba6-BOS	2023-07-13 19:21:17 721	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	S3Bucket_Receipts - Attempting upload ~~ attemptNum: '1' path: '/tmp/phpVr68TJ'
7e63e35d19a03ba6-BOS	2023-07-13 19:21:18 111	kbecciv+0713abb1@gmail.com	/api.php	staging-www1.lax	S3Bucket_Receipts - Upload succeed! ~~ path: '/tmp/phpVr68TJ'
```
```


7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 019 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | Processing file attachment upload ~~ cleanedFileName: 'svg_logo-1.svg'  fileMimeType: 'image/svg+xml; charset=us-ascii' fileExtension: 'svg'  uploadedFileType: 'image/svg+xml'
7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 019 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | Starting file upload virus scan ~~ filename: '/tmp/phphL7kbR'
7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 026 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | File upload virus scan results ~~ filename: '/tmp/phphL7kbR' version:  'ClamAV 0.103.6/26968/Thu Jul 13 07:29:43 2023' ping: '1' containsVirus:  ''
7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 026 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | S3Bucket_Receipts - Upload file
7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 026 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | S3Bucket_Receipts - Create S3 Obj ~~ classname: 'S3Bucket_Receipts' region: 'us-east-1'
7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 028 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | S3Bucket_Receipts - Uploading... ~~ path: '/tmp/phphL7kbR' name: 'w_07ce9b0fce2d024a939faf8ef7b2f1658fe02f96.svg' size: '4,210'
7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 028 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | S3Bucket_Receipts - Attempting upload ~~ attemptNum: '1' path: '/tmp/phphL7kbR'
7e63fc2d1d263ba6-BOS | 2023-07-13 19:38:14 437 | kbecciv+0713abb1@gmail.com | /api.php | virt2.sjc | S3Bucket_Receipts - Upload succeed! ~~ path: '/tmp/phphL7kbR'
```

**Comment by bondydaa** [comment] 2023-07-13 21:46
okay tested this myself so I could look at the data in the db, guess i didn't have to test and could have grabbed a reportactionid from the other logs but w/e.

this is what the reportaction looks like:
```
dbondy@db2.rno:~$ sudo readdb.sh -line "select * from reportactions where reportactionid=8193981128086863309;"
       created = 2023-07-13 21:38:38.871
      reportID = 64838855
     accountID = 4314165
        action = ADDCOMMENT
       message = {"html":"<a href=\"https://staging.expensify.com/chat-attachments/8193981128086863309/w_83ec3480eda921700b6033681ae39165a32ce8f2.svg\" data-expensify-source=\"https://staging.expensify.com/chat-attachments/8193981128086863309/w_83ec3480eda921700b6033681ae39165a32ce8f2.svg\">svg_logo-1.svg</a>","lastModified":"2023-07-13 21:38:38.871"}
reportActionID = 8193981128086863309
```

so I think this is b/c of the code from https://github.com/wojtus7/Expensify-App/blob/e5b7e3a767fcf70498c894c9e5f0f4d190e91fb0/src/libs/ReportActionsUtils.js#L216-L227

b/c it's just looking for `a` tags with `href` in the regex. 

not sure if maybe we want to exclude links that have `chat-attachments` or something else from showing previews? or maybe we want this behavior and it's not a bug at all?

I'm tagging everyone who reviewed https://github.com/Expensify/App/pull/17288/ b/c I have zero context here - @iwiznia @eVoloshchak @thienlnam @marcaaron @mountiny @0xmiroslav

**Comment by bondydaa** [comment] 2023-07-13 21:47
i guess maybe i shouldn't have added bug yet but for now i think we treat it as a bug until told otherwise.

**Comment by thienlnam** [comment] 2023-07-13 23:39
I don't think this is a bug - it's always done that but now you're pasting the link to the attachment which now renders a link preview.

So when an attachment is uploaded, it's stored in an S3 bucket, and when you click to open it, it has a link like
> https://staging.new.expensify.com/r/65941296/attachment?source=https://staging.expensify.com/chat-attachments/2654809535425792157/w_d4d1e677c4bf84f2ce953b6e40ed218a88164d71.png

The user is basically just copying the link and pasting it, which does not work for link previews. Right now you need an authtoken to view an image - I believe this is just a new feature where we support link previews for internal image links

**Comment by lschurr** [comment] 2023-07-14 17:20
Should this be closed @bondydaa @thienlnam?

**Comment by dhanashree-sawant** [comment] 2023-07-14 17:39
Currently it is not occuring for PNG or JPG, just SVG, why is it not parsing links from those attachments and displaying it as preview?

**Comment by bondydaa** [comment] 2023-07-14 17:59
I mean the link preview stuff is all new and is just rolling out so hard to say "it's always done this" 😅 . 

I agree nothing has changed for how svgs are returned after being uploaded, this happens for svgs and not png or jgp because I believe we end up rendering png and jpgs directly in the chat whereas svgs we return a link to view it in the modal. 

b/c of that link being returned it's getting picked up by the Link Preview regex and so trying to render the link.

**Comment by bondydaa** [comment] 2023-07-14 18:00
If we want SVGs to get rendered like png or jpgs we could do that. 

Or we could update the Link Preview text to include an authToken so that the Link Preview could actually load the content (it doesn't currently since the request via MarcoLink isn't authenticated and just returns the generic expensify.com content)

**Comment by dhanashree-sawant** [comment] 2023-07-14 18:01
Oh okay, got it now, makes sense

**Comment by bondydaa** [comment] 2023-07-17 18:39
Slack convo https://expensify.slack.com/archives/C01GTK53T8Q/p1689619016089709

**Comment by bondydaa** [comment] 2023-07-24 19:40
i'm removing the bug here b/c it's not really a bug, it's polish on the Link Preview project. 

Sorry for the noise @shawnborton I don't think you're really needed here since we're not going to implement any new design really.

Currently based on this thread I think we should probably just make it so that SVGs can be loaded like JPGs and PNGs https://expensify.slack.com/archives/C01GTK53T8Q/p1689633361062319?thread_ts=1689619016.089709&cid=C01GTK53T8Q

**Comment by lschurr** [comment] 2023-08-01 20:36
Is this still in progress @bondydaa?

**Comment by bondydaa** [comment] 2023-08-02 03:34
started another convo here about all these "bugs" that keep getting brought up related to the link previews https://expensify.slack.com/archives/C01GTK53T8Q/p1690947022029159

It seems there is a GH project for that 
<img width="562" alt="image" src="https://github.com/Expensify/App/assets/4073354/59df69c8-29fd-4e77-bdfc-f558181f544c">

so I'd love for the people involved to chime in on what the plan is for cleaning this stuff up.

**Comment by lschurr** [comment] 2023-09-04 23:56
Hi hi @marcaaron - this isn't overdue right?

**Comment by marcaaron** [comment] 2023-09-06 00:02
I had a similar issue that's on HOLD because we rolled back the Link previews feature temporarily and unassigned the BZ. So, I'll do the same thing here and unassign you @lschurr.

**Comment by marcaaron** [comment] 2023-10-10 18:35
Removing Monthly label for now.

**Comment by marcaaron** [comment] 2023-11-22 01:30
I'm gonna close this for now. Melvin is being a jerk. Link previews will return at some point in the future.

**Closed by marcaaron** 2023-11-22 01:30 UTC
Labels: Engineering, Monthly, Internal, NewFeature, Overdue
