### ISSUE TITLE
[HOLD for payment 2024-02-26] [Payment Due 2-21-24] [$500] App crashes after selecting participant when requesting money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36433] opened 2024-02-13 20:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money.
3. Enter amount > Next.
4. Select a participant > Next.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/9527cb93-6529-4c4e-834f-94d2c9377aff

[Bug6378561_1707854436499!staging.new.expensify.com-1707854304788.txt](https://github.com/Expensify/App/files/14271895/Bug6378561_1707854436499.staging.new.expensify.com-1707854304788.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145417cbbd8e816e2</li>
        <li>Upwork Job ID: 1757505742510735360</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-13 21:42
Agreed regression of https://github.com/Expensify/App/pull/35287 which got merged 5 hrs ago.

**Comment by jeremy-croff** [comment] 2024-02-13 22:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
type error crashing app

### What is the root cause of that problem?
policy object in /MoneyTemporaryForRefactorRequestConfirmationList.js is undefined

### What changes do you think we should make in order to solve the problem?
Default prop for policy as {}

### What alternative solutions did you explore? (Optional)

**Comment by cubuspl42** [comment] 2024-02-14 09:15
This is serious, I'm sorry for missing this. I believe we should revert the offending PR, especially because the Lunar New Year which limits @dukenv0307 availability.

**Comment by cubuspl42** [comment] 2024-02-14 09:56
The impact is high enough that we shouldn't keep this on staging. I'll raise a reverting PR.

**Comment by cubuspl42** [comment] 2024-02-14 10:36
I changed my mind, let's fix this ASAP. I raised the PR myself: https://github.com/Expensify/App/pull/36470

**Comment by cubuspl42** [comment] 2024-02-14 10:37
cc: @pecanoro

**Comment by pecanoro** [comment] 2024-02-20 15:17
We can close this one, since no payment is due as it was a regression.

**Closed by pecanoro** 2024-02-20 15:17 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
