### ISSUE TITLE
Task - User appears twice in the mention list when assigning task via [] method

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50222] opened 2024-10-04 10:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any DM.
3. Create a task by sending [] @<email of user with no chat history> "task name".
4. Type @ and followed by the task assignee.

## Expected Result:
The task assignee will appear in the mention list once.

## Actual Result:
The task assignee appears in the mention list once.
This issue only happens when creating task via [] pathway and task assignee has no chat history with the current user.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6e3ef821-9a5e-4c22-b764-9d6c02db50a5

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-04 10:19
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-10-04 10:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task assignee appears in the mention list once.
This issue only happens when creating task via [] pathway and task assignee has no chat history with the current user.

### What is the root cause of that problem?

When we create task with a new user (that's not been chatted before), we create a new optimistic personal details with a random `accountID` for him:

https://github.com/Expensify/App/blob/6e509c1ef8299dc45a6a51047cc6cecf2c8530d6/src/pages/home/report/ReportFooter.tsx#L156-L158

Later when the BE creates the task successfully, it will return his correct `accountID` and personal details but do not clear the optimistic one, causing duplicated personal details.

### What changes do you think we should make in order to solve the problem?


We need to clear the optimistic personal details when the task is created successfully:

1. Add `isOptimisticPersonalDetail: true` to this:

https://github.com/Expensify/App/blob/52aa9a953167814edab2b49fda9ed5df51200d40/src/libs/actions/Task.ts#L766

2. When `getTaskAssigneeChatOnyxData` [here](https://github.com/Expensify/App/blob/8f22bff9bad8cf6af159c44678a64f867cd62a9d/src/libs/ReportUtils.ts#L7033), check if the assignee's personal details is optimistic and clear it from `personalDetailsList` in `successData`:

```javascript
if (assigneePersonalDetails?.isOptimisticPersonalDetail) {
    successData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: ONYXKEYS.PERSONAL_DETAILS_LIST,
        value: {
            [assigneeAccountID]: null,
        },
    });
}
```

**Comment by sonialiap** [comment] 2024-10-08 10:59
I cannot reproduce this on prod or staging. This also looks like a VSB bug and we're not working on those right now. I'm going to close this as non-reproducible and for focus

1. check how many options show up if I type `@email@domain.com`. Confirm that there's only one
2. make a task in format `[] @email@domain.com task`, hit enter
3. mention `@email` and check how many options show in the list. Should only be one

https://github.com/user-attachments/assets/e9ef5ea1-1901-47a9-b6f0-5da55c8caa5d

**Closed by sonialiap** 2024-10-08 10:59 UTC
Labels: Daily, Overdue, Bug
