### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Quick action - QAB is blank after submitting expense to invalid user and dismissing error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50311] opened 2024-10-06 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Enter amount > Next.
4. Select a VOIP number (+1 631-791-8378).
5. Submit the expense.
6. Dismiss the error in the report.
7. Open FAB.

## Expected Result:
Quick action button will not be blank.

## Actual Result:
Quick action button is blank.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f4ee9207-c09c-4a35-a894-dc2fe82fcfd9

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843772201311603441</li>
        <li>Upwork Job ID: 1843772201311603441</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 104356478</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by IuliiaHerets** [comment] 2024-10-06 19:06
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-10-07 06:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
QAB title is blank after clearing the error of the report.

### What is the root cause of that problem?
When we clear the report error, it will delete the report from Onyx, so the title will be empty.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L213-L216

### What changes do you think we should make in order to solve the problem?

I'd like to propose a different solution, that is reverting the QA to the previous one if fails. When the current action fails, the new QA will stay. But when we use `Clear cache and restart`, we will see the latest data from the BE will show the previous QA.

https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/libs/actions/IOU.ts#L635-L645

```
if (!isOneOnOneSplit) {
    optimisticData.push({
        onyxMethod: Onyx.METHOD.SET,
        key: ONYXKEYS.NVP_QUICK_ACTION_GLOBAL_CREATE,
        value: {
            action: newQuickAction,
            chatReportID: chatReport?.reportID,
            isFirstQuickAction: isEmptyObject(quickAction),
        },
    });
    failureData.push({
        onyxMethod: Onyx.METHOD.SET,
        key: ONYXKEYS.NVP_QUICK_ACTION_GLOBAL_CREATE,
        value: quickAction ?? null,
    });
}
```

This is what we did with the track expense too.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/libs/actions/IOU.ts#L1540-L1544

We can apply this to other action too, such as split bill, send money, and task.

**Comment by bernhardoj** [comment] 2024-10-11 02:29
PR is ready

cc: @ahmedGaber93

**Comment by johncschuster** [comment] 2024-10-23 18:56
Looks like payment is due tomorrow for this one.

**Comment by johncschuster** [comment] 2024-10-25 21:27
@ahmedGaber93 can you please complete the BZ checklist above? I will issue payment once completed.

**Comment by johncschuster** [comment] 2024-10-25 21:29
Payment Summary:

Contributor+: @ahmedGaber93 paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104356478) 
Contributor: @bernhardoj due $250 via NewDot

**Comment by ahmedGaber93** [comment] 2024-10-26 22:57
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38386
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/38386/files#r1817945906
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. Yes
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal


1. Submit a money request to an invalid user (+1 631-791-8378). It will give an error.
2. Press the FAB
3. Verify the Quick action QAB is not blank and not the invalid user in step 1


Do we agree 👍 or 👎

**Comment by johncschuster** [comment] 2024-10-28 22:04
PAID! Thank you!

**Closed by johncschuster** 2024-10-28 22:04 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-10-29 02:53
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-29 14:10
$250 approved for @bernhardoj
