### ISSUE TITLE
[$250] Expense - System message changes to "<you> submitted report to you"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40780] opened 2024-04-23 12:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39321
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user is a member of collect workspace
1. Go to https://staging.new.expensify.com/
and log in as an employee
2. Open the workspace chat
3. Click on "+" > Submit expense
4. Create an expense
5. Open the created expense and submit it

## Expected Result:
The system message "You submitted this report <admin account>" is displayed and does not change

## Actual Result:
The system message changes to "<you> submitted this report to you". After opening the transaction details again it changes to the original one.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/313e542a-a03a-483d-bb96-cfa38a43e5fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2685ef7e5d21048</li>
        <li>Upwork Job ID: 1785793284936679424</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-23 12:07
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-04-23 12:07
@greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by greg-schroeder** [comment] 2024-05-01 22:07
Okay, moving to `External`

**Comment by fitd-tech** [comment] 2024-05-02 05:15
To help others reproduce: you may need to make sure the workspace has the setting More Features -> Workflows -> Add Approvals. My attempts to reproduce this without that setting resulted in a "This chat room has been archived." message instead.

**Comment by fitd-tech** [comment] 2024-05-02 06:36
I haven't been able to reproduce this particular issue yet. @greg-schroeder are there conditions necessary outside of the listed steps? When I submit as a non-approver, I get the intended message. When I submit as an approver, I get "You submitted this report to yourself". In both cases, I'm not seeing the notification change.

**Comment by mvtglobally** [comment] 2024-05-06 19:55
Issue not reproducible during KI retests. (First week)

**Closed** 2024-05-07 09:42 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
