### ISSUE TITLE
Log in - Expired link Validation is not expired, but works as good as new

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13474] opened 2022-12-09 16:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. On the log in screen, enter a new account email
3. Repeat the previous step with the same email - This is to receive 2 validation links
4. Navigate to the account email inbox and open the first email of the 2
5. Copy the Validation link and change it to staging if necessary
6. Navigate to the staging link
7. Verify there's an error displayed indicating there was a problem with the validation link

## Expected Result:
An error message displayed indicating there was a problem with the validation link.

## Actual Result:
There is no error. The user can log in using any of them.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206747557-3fc05a53-a0d5-4fa2-bde4-a673525afeab.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2022-12-09 23:30
I'll test on Monday.

**Comment by pecanoro** [comment] 2022-12-12 19:30
I am going to try and take a look at this to fix it. @alexpensify Can you see if you can reproduce it, please? Thanks

**Comment by alexpensify** [comment] 2022-12-13 00:04
@pecanoro - I can replicate this experience. I requested two password resets and got two emails. I clicked the first email option: 

![image](https://user-images.githubusercontent.com/8107070/207187204-3f6d5994-10f2-405d-ba6f-a418dc2b13dc.png)

And am taken here: 

![image](https://user-images.githubusercontent.com/8107070/207187362-c3148b61-5cac-4546-ba9c-0da9225d54b4.png)

**Comment by pecanoro** [comment] 2022-12-13 18:36
Hmm, actually, I am pretty sure this is the expected behaviour since when you try to set the password, it returns an error:

![image](https://user-images.githubusercontent.com/6474442/207417161-e2f18297-577c-40c9-96d4-20e8113f3452.png)

Because of that, I am going to close it.

**Closed by pecanoro** 2022-12-13 18:36 UTC
Labels: Daily, Internal, Bug
