### ISSUE TITLE
 Accounting - Non-reimbursable expense becomes empty after going offline and online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45191] opened 2024-07-10 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44921
## Action Performed:
Pre-requisite
- Collect workspace with accounting enabled.
- NetSuite beta enabled for the user. (Use expensifail account)
- Setup NetSuite in OldDot.
1. Open the app with the pre-setup workspace.
2. Go to Accounting
3. Click on the Advanced button.
4. Click on Non-reimbursable expense option (Enable Custom form ID to access this field)
5. Input any number and confirm
6. Wait a few seconds and go offline
7. Go back online again

## Expected Result:
The value in Non-reimbursable expense persists

## Actual Result:
The value in Non-reimbursable expense becomes empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d99a90e7-f5d7-4b78-99f0-e033e0989c37

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-10 17:30
@Gonals  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Gonals** [comment] 2024-07-10 17:37
Hmm. This looks like a backend issue, at first glance. Can it be reproduced consistently?

**Comment by Gonals** [comment] 2024-07-10 21:29
Ok, that field is not working at all. It is not a blocker, as this is new functionality and doesn't break any existing stuff, but we need to fix it. I'll look more into it today/tomorrow

**Comment by Gonals** [comment] 2024-07-10 21:35
Yeeep. This is a typo in the backend. Fix incoming

**Comment by Christinadobrzyn** [comment] 2024-07-11 16:53
I assume we can move this from hourly to daily now that a PR is in the works. @Gonals does that sound okay?

**Comment by Gonals** [comment] 2024-07-11 17:06
Yep!

**Comment by Christinadobrzyn** [comment] 2024-07-15 21:59
Update for Melvin- working on PR https://github.com/Expensify/Web-Expensify/pull/42707

**Comment by Christinadobrzyn** [comment] 2024-07-16 17:23
I think I'm going to move this to weekly since we're working on PR - https://github.com/Expensify/Web-Expensify/pull/42707

**Comment by Christinadobrzyn** [comment] 2024-07-23 23:54
PR is in production - https://github.com/Expensify/Web-Expensify/pull/42707 as of the 16th. Can we close this out @Gonals and @lakchote?

**Comment by Christinadobrzyn** [comment] 2024-07-30 17:04
I'm going to close this out. We can reopen if needed.

**Closed by Christinadobrzyn** 2024-07-30 17:04 UTC
Labels: Reviewing, Engineering, Weekly, Improvement, Internal, Bug
