### ISSUE TITLE
[HOLD for payment 2023-11-09] [$1000] Web - API OpenReport shows after switch away from the app and back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27887] opened 2023-09-20 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account
2. Open Developer tool - Network
3. Switch away from the app and back

## Expected Result:
NO api OpenReport shows after switch away and back

## Actual Result:
API OpenReport shows after switch away and back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (49)](https://github.com/Expensify/App/assets/93399543/a46b1b70-5073-4335-bce5-57e0b2c6a946)

https://github.com/Expensify/App/assets/93399543/b9715cf7-966c-4353-adc3-3d05e4a5deca

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695079219960739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f1c0d7d7d757660</li>
        <li>Upwork Job ID: 1704588615900069888</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27362270</li>
<li>saranshbalyan-1234 | Contributor | 27362271</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-09-20 20:37
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
OpenReport API gets called after switching tabs
### What is the root cause of that problem?
We are calling the OpenReport API if visibility changes.
https://github.com/Expensify/App/blob/94c07eabcf8f0c927b759956f24a72c28710186e/src/pages/home/ReportScreen.js#L263-L280
### What changes do you think we should make in order to solve the problem?
Just need to either remove or comment the above code and its working fine.
### What changes do you think we should make in order to solve the problem?
N/A

**Comment by abdel-h66** [comment] 2023-09-20 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

OpenReport is called even when the report is already focused. 

### What is the root cause of that problem?

We are using the useFocusEffect to handle opening a report but this will run every time the repors gets back to view 

https://github.com/Expensify/App/blob/94c07eabcf8f0c927b759956f24a72c28710186e/src/pages/home/ReportScreen.js#L263-L280


### What changes do you think we should make in order to solve the problem?

I would suggest using a ref to keep track of the open status, and avoid calling the OpenReport as such. 

    const reportIsFocused = useRef(false);

```
    useFocusEffect(
        useCallback(() => {
            const unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
                reportIsFocused.current = true;
                const isTopMostReportID = Navigation.getTopmostReportId() === getReportID(route);
                // If the report is not fully visible (AKA on small screen devices and LHR is open) or the report is optimistic (AKA not yet created)
                // we don't need to call openReport
                if (!getIsReportFullyVisible(isTopMostReportID) || report.isOptimisticReport) {
                    return;
                }

               if(reportIsFocused.current) {
                    return;
                }
                Report.openReport(report.reportID);
            });

            return () => unsubscribeVisibilityListener();
        }, []),
    );
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by abdel-h66** [comment] 2023-09-21 11:30
Yes that's true @hoangzinh after digging deeper into the previous changes for that part of the code, I found a PR that fixed the following issue. 

**Switching other app after receiving messages, message will be marked 'read'**
https://github.com/Expensify/App/issues/15634

This means that the visibility change subscription serves as a guard against reading messages without actually seeing them so removing it will definitly break this. 

As this being said, the issue seemed to appear on mobile only because that's where the `getIsReportFullyVisible` will return false, with the LHN open. 

So that check fixes the report being opened without seeing it, but that doesn't stop the call on devices where the report is already open and visibitly changes. 

I found out that adding a third check `isTopMostReportID`, while keeping the previous one to guard againt a regression will stop the unecessary call to OpenReport on an already open report. The solution. will look something like this. 

```
    useFocusEffect(
        useCallback(() => {
            const unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
                const isTopMostReportID = Navigation.getTopmostReportId() === getReportID(route);
                // If the report is not fully visible (AKA on small screen devices and LHR is open) or the report is optimistic (AKA not yet created)
                // we don't need to call openReport
                if (!getIsReportFullyVisible(isTopMostReportID) || report.isOptimisticReport) {
                    return;
                }

                if(isTopMostReportID) {
                    return;
                }


                Report.openReport(report.reportID);
            });

            return () => unsubscribeVisibilityListener();
            // The effect should run only on the first focus to attach listener
            // eslint-disable-next-line react-hooks/exhaustive-deps
        }, []),
    );
```

**Comment by saranshbalyan-1234** [comment] 2023-09-21 20:00
@hoangzinh the isuue is with the useLayoutEffect which is causing api to be called whenever screen is focused, https://github.com/Expensify/App/blob/94c07eabcf8f0c927b759956f24a72c28710186e/src/pages/home/ReportScreen.js#L262-L280
Instead useLayoutEffect we can keep this code in a useEffect which is solving the issue, tested and its working fine with useEffect

**Comment by saranshbalyan-1234** [comment] 2023-09-21 20:02
moreover @abdel-h66 's proposed solution is not working
```javascript
   if(isTopMostReportID) {
                    return;
                }
``` 

Thinking moving it to useEffect would make much sense

**Comment by abdel-h66** [comment] 2023-09-21 20:40
I just double checked my solution @saranshbalyan-1234  and it seems working just fine 😅 do you have a specific use case where it didn't work I would like to check

**Comment by saranshbalyan-1234** [comment] 2023-09-22 11:18
after removing cache, my proposal did not work, my bad!

**Comment by garrettmknight** [comment] 2023-09-25 10:52
@abdel-h66 can you update your solution with @hoangzinh's feedback?

**Comment by abdel-h66** [comment] 2023-09-25 13:06
Yes @garrettmknight I still didnt have time for a second look on this one, I will update here once I try something different

**Comment by garrettmknight** [comment] 2023-09-28 10:14
Still awaiting proposals

**Comment by abdel-h66** [comment] 2023-09-28 20:12
I still don't understand the purpose of the useLayoutEffect and the Visiblity.onChange event, the first time it was introduced was here https://github.com/Expensify/App/pull/16467 

https://github.com/hoangzinh/Expensify-App/blob/31ff3c86300f1d2b46abe89e427c731c7bc44c50/src/pages/home/ReportScreen.js#L134-L148


I removed that useLayoutEffect just to test the messages being read issue and I tested on various apps. 


https://github.com/Expensify/App/assets/144037189/2e90ed64-7277-4bc0-8e19-3ecebc44198c

I could not find any other use cases where that useLayoutEffect could be benefitial.

**Comment by garrettmknight** [comment] 2023-10-03 16:58
Still awaiting a complete proposal.

**Comment by saranshbalyan-1234** [comment] 2023-10-05 18:23
sorry @hoangzinh haven't been able to work on this, can spend time on weekends

**Comment by jeet-dhandha** [comment] 2023-10-12 01:37
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
- `OpenReport` API is called unnecessarily even when no data is changed.

### What is the root cause of that problem?
- Root cause is that we are not checking if the `prevReport` and current `report` are same or not. If they are same, we should not call `OpenReport` API.

### What changes do you think we should make in order to solve the problem?
- We can update the code in `ReportScreen.js` as below.
- Updateing dependencies of `useCallback` to get the latest `report` and `prevReport` values.

```diff
useFocusEffect(
    useCallback(() => {
        const unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
            const isTopMostReportID = Navigation.getTopmostReportId() === getReportID(route);
            // If the report is not fully visible (AKA on small screen devices and LHR is open) or the report is optimistic (AKA not yet created)
            // we don't need to call openReport
-           if (!getIsReportFullyVisible(isTopMostReportID) || report.isOptimisticReport) {
+           if (!getIsReportFullyVisible(isTopMostReportID) || report.isOptimisticReport || _.isEqual(prevReport, report)) {
                return;
            }

            Report.openReport(report.reportID);
        });

        return () => unsubscribeVisibilityListener();
        // The effect should run only on the first focus to attach listener
        // eslint-disable-next-line react-hooks/exhaustive-deps
-   }, []),
+   }, [report, prevReport]),
);
```

### Output

https://github.com/Expensify/App/assets/78416198/f4b54bfa-867d-4372-9c91-417dc9a6d853


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jeet-dhandha** [comment] 2023-10-14 10:26
In below video you can see that these three keys only change over time:
- lastReadTime
- lastVisibleActionCreated
- lastVisibleActionLastModified

And also these keys will remain same until:
- New message arrived
- Or user read the new messages from another tab or another device

https://github.com/Expensify/App/assets/78416198/e276fa41-5566-415c-84ea-4249653ac7bd

**Comment by jeet-dhandha** [comment] 2023-10-14 10:27
@hoangzinh Please check

**Comment by garrettmknight** [comment] 2023-10-16 17:35
@jeet-dhandha can you help @hoangzinh understand your proposal a bit more so we can solve this one?

**Comment by jeet-dhandha** [comment] 2023-10-19 03:09
I am just eliminating the extra calls to OpenReport API. But i don't know what's the main use of OpenReport API call there. This should be explained by someone from `internal` team.

**Comment by marcaaron** [comment] 2023-10-19 19:03
Just looking at the expectation there...

>NO api OpenReport shows after switch away and back

This could be a holdover from when we were using `OpenReport` to mark the report as "read".

This is where the call happens -> https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/pages/home/ReportScreen.js#L268-L278

At one point in the past, calling `OpenReport` would effectively mark the report as "read" and that's why we have this logic. When you leave the report and come back we will mark it as read.

@MonilBhavsar after the changes you made I'm not sure if this should still be the default behavior. Should we be calling `ReadNewestAction` instead if the main goal is to mark the report as read? Or can you think of another reason why we should be calling `OpenReport`?

**Comment by marcaaron** [comment] 2023-10-19 19:27
Kind of tricky to mark the report as read since all logic for that is in the `ReportActionsList`. I am not sure if a clear solution comes to mind. Will wait for @MonilBhavsar's thoughts before proceeding.

**Comment by marcaaron** [comment] 2023-10-19 19:33
I also see most of the previous conversation here has revolved around assuming that it's a bug that this API method gets called at all. IMO the code probably works correctly. We are just calling the wrong API or nobody is sure why we even call it.

**Comment by MonilBhavsar** [comment] 2023-10-20 06:57
@marcaaron looking about old linked issues and code, I feel like the purpose of that code to call `OpenReport` is to - 
1. Fetch undelivered report actions when app was backgrounded
2. And to mark report as read

Previously, both were handled by `OpenReport` API command, but now they are handled separately. I think we can safely remove that code now, as (1) would be handled by reliable updates and (2) would be handled by `ReadNewestAction` API command and that would be called when we render reportAction inside `ReportActionsView` component, so we don't need a separate handler to mark report as read.

**Comment by abdel-h66** [comment] 2023-10-20 07:54
Yea those were my finding too @MonilBhavsar I checked on multiple devices too and everything seemed to work just fine while the call was removed from there https://github.com/Expensify/App/issues/27887#issuecomment-1739943043

**Comment by garrettmknight** [comment] 2023-10-24 10:05
@marcaaron with that context, what do you think?

**Comment by marcaaron** [comment] 2023-10-24 23:43
>I think we can safely remove that code now, as (1) would be handled by reliable updates and (2) would be handled by ReadNewestAction API command and that would be called when we render reportAction inside ReportActionsView component, so we don't need a separate handler to mark report as read.

Ok so basically I think @MonilBhavsar is saying:

- We might get "new actions" when we return from the app being background
- This is actually the only case we care about when it comes to marking the report as "read" after returning from background
- We already  mark the report as read if the report is scrolled to the bottom

I am fine with removing this code. But let's watch out for any regressions and be sure these assumptions are correct.

**Comment by marcaaron** [comment] 2023-10-24 23:45
@hoangzinh sounds like @saranshbalyan-1234 had the first proposal that is closest to where we landed. Do you agree?

**Comment by marcaaron** [comment] 2023-10-25 06:04
@saranshbalyan-1234 can you update your proposal based on the conversation here? I think we are ready to proceed.

**Comment by garrettmknight** [comment] 2023-11-10 19:21
Summarizing payments:
- Urgency bonus: No
- Contributor: @saranshbalyan-1234 $1000 paid via Upwork
- Reviewer: @hoangzinh $1000 paid via upwork

@hoangzinh can you get to the checklist when you get a chance

**Comment by garrettmknight** [comment] 2023-11-13 18:16
Nice one, closing!

**Closed by garrettmknight** 2023-11-13 18:16 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
