### ISSUE TITLE
[$250] LHN - Two "##" displayed for chat rooms

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9939] opened 2022-07-15 14:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and create a expensifail account
2. Create a new workspace
3. Verify the LHN page for the default rooms created

## Expected Result:
Single # displayed for all the default chat rooms for workspace

## Actual Result:
Two # # displayed for chat rooms

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.84-11

**Reproducible in staging?:** Yes

**Reproducible in production?:**  Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![New acounts](https://user-images.githubusercontent.com/43996225/179239183-bce572d8-96f8-4ca4-9222-026ee70427b8.png)
![Old accounts](https://user-images.githubusercontent.com/43996225/179239188-977a7bc7-82b9-4111-85ec-ca262abdf9f5.png)

It happens only with new accounts and not in the old accounts created a while ago.

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 
Applause internal tester

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2022-07-15 22:05
Can't reproduce from my personal account, also on v1.1.84-11, neither on web nor desktop. Going to try from a different account in case it has to do with the account.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/2229301/179317255-d9aebd1a-8c7d-4554-808f-74d4b5635d17.png">

**Comment by kavimuru** [comment] 2022-07-16 13:51
@francoisl This happens only with newly created account.
<img width="960" alt="Screenshot (66)" src="https://user-images.githubusercontent.com/43996225/179357719-07c2c3bf-d571-4567-a933-9f60a877027b.png">

**Comment by thesahindia** [comment] 2022-07-19 11:39
Hey just wanted to know if it is eligible for the reporting as I had reported it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1654791933817549) but I didn't have the steps to repro

**Comment by francoisl** [comment] 2022-07-20 18:19
Got it, I was able to reproduce with a new account!

**Comment by arielgreen** [comment] 2022-07-25 17:47
https://www.upwork.com/jobs/~017e9948d97d933e4e

**Comment by luacmartins** [comment] 2022-07-25 22:36
Hmm I couldn't reproduce this on a new account in neither `main` nor `staging`.

**Comment by luacmartins** [comment] 2022-07-25 22:37
@kavimuru can we still reproduce this?

**Comment by mvtglobally** [comment] 2022-07-26 03:59
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2022-07-26 04:15
I'll close this issue if we can't reproduce for another cycle of KI retests.

**Comment by kavimuru** [comment] 2022-07-26 12:23
@luacmartins  Not able to repro in 1.1.86-0 build.
<img width="960" alt="Screenshot (69)" src="https://user-images.githubusercontent.com/43996225/181004942-c5fb1f88-7c5e-461d-9206-d0f2fe6a007f.png">

**Closed** 2022-07-26 15:48 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
