### ISSUE TITLE
[HOLD for Payment 2024-05-29] Android & iOS - QBO - Multi tag - "Settings" button is positioned outside the page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42059] opened 2024-05-13 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #41351
**Version Number:** 1..4.73-0
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace is connected to QBO.
- Classes and Customers/Projects are imported from Import settings.

1. Launch New Expensify app.
2. Go to workspace settings.
3. Go to Tags.

## Expected Result:
"Settings" button will align properly within the page.

## Actual Result:
"Settings" button is positioned outside the page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/fb938c3b-b85f-4fe4-b7ea-87babd6f3798" width="40%" height="40%">

https://github.com/Expensify/App/assets/38435837/9e6dc7bf-33f1-49de-9c20-8ec2488d4d2c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2024-05-13 14:11
It seems the PR wasn't tested on mobile devices, I am not sure why, I posted in the issue.

**Comment by pecanoro** [comment] 2024-05-13 15:39
Since this is under the beta, I am going to remove the deploy blocker and assign the original authors.

**Comment by s77rt** [comment] 2024-05-13 16:17
[PR](https://github.com/Expensify/App/pull/42086) is ready for review cc @ikevin127

**Comment by ikevin127** [comment] 2024-05-23 00:22
⚠️ **Automation failed**: This was deployed to **production** today [here](https://github.com/Expensify/App/pull/42086#issuecomment-2125963681), therefore should be **[HOLD for Payment 2024-05-29]** and have `Awaiting Payment` label.

cc @slafortune @pecanoro

**Comment by slafortune** [comment] 2024-05-23 22:05
This was a fix for a regression related to https://github.com/Expensify/App/pull/41351#issuecomment-2108135944, so no payment here - will be closing this out after the 7 day hold.

**Comment by slafortune** [comment] 2024-05-23 22:06
I will be on vacation until June 4th, so adding a BZ in the meantime.

**Comment by s77rt** [comment] 2024-05-23 22:57
This can be close since it's a regression. No payment due

**Comment by pecanoro** [comment] 2024-05-24 00:51
Ahh you are right, thank you so much for mentioning it, closing!

**Closed by pecanoro** 2024-05-24 00:51 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
