### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250]  Close account - Unable to close unverified account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44114] opened 2024-06-20 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4652683
**Email or phone of affected tester (no customers):** natnael.expensify+0a89fdndafadf@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign up with a new account
2. Go to Settings > Security > Close account
3. Enter default email > click 'Close account'

## Expected Result:
Account should be closed

## Actual Result:
Account is not closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b5f791f2-1678-4d12-ba37-8c7e46b66070

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5a38773a3b72e10</li>
        <li>Upwork Job ID: 1804323493948615973</li>
        <li>Last Price Increase: 2024-07-13</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 103155489</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan / @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-06-20 20:11
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-06-21 08:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to close unverified account. The request completes but the user isn't logged out.

### What is the root cause of that problem?
When the request is completed, there is already a `clear` onyx command to clear the onyx so the user is logged out. However, when we receive the response, `doesClientNeedToBeUpdated` returns true which will call `OnyxUpdates.saveUpdateInformation` which triggers `GetMissingOnyxMessages` but fails because the account is already closed, so the response onyx data is never applied.
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/Middleware/SaveResponseInOnyx.ts#L28-L33

The reason `doesClientNeedToBeUpdated` returns true is because the `lastUpdateIDAppliedToClient` is smaller than the `previousUpdateID` response from CloseAccount.
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/actions/OnyxUpdates.ts#L162-L169

You can see that `previousUpdateID` is the `lastUpdateID` of the previous request.
<img width="321" alt="image" src="https://github.com/Expensify/App/assets/50919443/654adceb-df42-4a2f-8acf-2e8ef893e210">

But for the CloseAccount response, the `previousUpdateID` is bigger than the previous request `lastUpdateID`, so the app detected there is missing onyx data.
<img width="606" alt="image" src="https://github.com/Expensify/App/assets/50919443/2eadde68-4a05-4fed-8643-e3ffd1d84080">

### What changes do you think we should make in order to solve the problem?

Fix it on the BE so the correct `previousUpdateID` is returned or if we want to fix this on the FE, we can add CloseAccount request to the `requestsToIgnoreLastUpdateID` list because we don't care if there is missing data when closing an account.
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/Middleware/SaveResponseInOnyx.ts#L6-L8

**Comment by isabelastisser** [comment] 2024-06-22 01:20
@mkhutornyi please review the proposals above when you have a chance. Thanks!

**Comment by jasham** [comment] 2024-06-22 12:34
Is this bug is still open or assigned to someone else ?

**Comment by jasham** [comment] 2024-06-22 12:53
Contributor details
Your Expensify account email: jasham009@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/jasham4ryou

**Comment by jasham** [comment] 2024-06-22 12:53
Is this bug is still open or assigned to someone else ?

**Comment by isabelastisser** [comment] 2024-06-24 13:21
@mkhutornyi, please review the proposals above! 

@jasham, this is still open.

**Comment by isabelastisser** [comment] 2024-06-24 15:38
@mkhutornyi I DM'd you for visibility. Thanks!

**Comment by isabelastisser** [comment] 2024-06-27 18:28
Bump @AndrewGable. Thanks!

**Comment by AndrewGable** [comment] 2024-06-27 19:23
@isabelastisser - Did you confirm we do want to allow closing of unverified accounts?

**Comment by isabelastisser** [comment] 2024-06-28 14:31
@AndrewGable, nope! I will post this to BZ now. Thanks!

**Comment by isabelastisser** [comment] 2024-06-28 14:34
Asked [here.](For this [issue](https://github.com/Expensify/App/issues/44114), do we want to allow the closing of unverified accounts?)

**Comment by isabelastisser** [comment] 2024-07-08 15:40
Asking in product:

https://expensify.slack.com/archives/C03U7DCU4/p1720453236924149

**Comment by isabelastisser** [comment] 2024-07-09 20:19
Bump @AndrewGable. Thanks!

**Comment by AndrewGable** [comment] 2024-07-11 00:11
I agree with Jenna 👍

**Comment by isabelastisser** [comment] 2024-07-11 02:01
Thanks, @AndrewGable ! Should I keep this external? Unsure based on @mkhutornyi's comment:

https://github.com/Expensify/App/issues/44114#issuecomment-2190003156

**Comment by isabelastisser** [comment] 2024-07-12 00:30
Bump @AndrewGable 

https://github.com/Expensify/App/issues/44114#issuecomment-2221845948

**Comment by AndrewGable** [comment] 2024-07-12 05:52
Sure we can keep external, I am OOO for the next week and a half so let's find someone else to push this along. Thanks!

**Comment by isabelastisser** [comment] 2024-07-15 15:10
@mkhutornyi, we are keeping this external so let's pick a proposal! Thanks!

**Comment by isabelastisser** [comment] 2024-07-16 16:59
Bump @mkhutornyi, please provide an update! I DM'd you for visibility. Thanks!

**Comment by bernhardoj** [comment] 2024-07-18 11:46
PR is ready

cc: @mkhutornyi

**Comment by isabelastisser** [comment] 2024-07-18 17:10
I will be OOO tomorrow and next week, so I am reassigning this until I return on July 29. Thanks, @kevinksullivan!

Status: Waiting for PR to merge.

**Comment by isabelastisser** [comment] 2024-07-29 14:57
I'm back and taking this back! Thanks, @kevinksullivan!

**Comment by isabelastisser** [comment] 2024-08-01 16:57
Hey @mkhutornyi, please complete the BZ list above. Thanks!

**Comment by bernhardoj** [comment] 2024-08-02 02:05
Requested in ND.

**Comment by isabelastisser** [comment] 2024-08-02 02:13
Payment summary:
 
@bernhardoj requires payment through NewDot Manual Requests $250 / Contributor `PENDING`
@mkhutornyi requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/103155489) $250 (Reviewer) C+  `PAID`

**Comment by isabelastisser** [comment] 2024-08-02 02:14
@mkhutornyi, please complete the BZ list. I will DM you for visibility. Thanks!

**Comment by JmillsExpensify** [comment] 2024-08-03 19:16
$250 approved for @bernhardoj

**Comment by isabelastisser** [comment] 2024-08-05 14:46
All set! Closing.

**Closed by isabelastisser** 2024-08-05 14:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
