### ISSUE TITLE
[HOLD for payment 2024-09-09] [$250] Subscription - Clicking Outside the Modal Doesn't Close It, Causing Inconsistency

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47559] opened 2024-08-16 11:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+tw23478102034@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to Account Settings > Subscription.
2. Add Payment Card > Click on the three-dot menu > Change Payment Currency.
3. Select a currency > Click outside the modal. Notice the modal doesn't close.
4. Repeat: Click the three-dot menu > Change Payment Card > Currency > Click outside. This time, the modal closes, creating inconsistency.

## Expected Result:
After opening the Change Payment Currency modal and selecting a currency, clicking outside the modal should close it.

## Actual Result:
After opening the Change Payment Currency modal and selecting a currency, clicking outside the modal does not close it. This creates an inconsistency compared to other instances (e.g., when changing payment card>Currency), where clicking outside the modal closes it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6e213e8e-b57d-4759-a802-d69974e84962

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4445f00bf760f92</li>
        <li>Upwork Job ID: 1824461014015831545</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103587586</li>
<li>Krishna2323 | Contributor | 103587588</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by izarutskaya** [comment] 2024-08-16 11:07
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment] 2024-08-16 11:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After opening the Change Payment Currency modal and selecting a currency, clicking outside the modal does not close it. This creates an inconsistency compared to other instances (e.g., when changing payment card>Currency), where clicking outside the modal closes it.

### What is the root cause of that problem?
Two places use different ways.

1. `PaymentCardForm`, we are using `CurrencySelector` as a separate page then when we click outside, it's closed
https://github.com/Expensify/App/blob/9940e99abca5b0e7f17c8d29a66df50b2345b8a2/src/components/AddPaymentCard/PaymentCardForm.tsx#L296-L301

2. `PaymentCardChangeCurrencyForm`, we're using a currency modal. Then when we click outside, only the `PaymentCardCurrencyModal` is closed
https://github.com/Expensify/App/blob/9940e99abca5b0e7f17c8d29a66df50b2345b8a2/src/components/AddPaymentCard/PaymentCardChangeCurrencyForm.tsx#L110
### What changes do you think we should make in order to solve the problem?
We should handle the currency as a separate page by using `CurrencySelector` as we do in `PaymentCardForm`. Since `PaymentCardChangeCurrencyForm` is used in two places, we can add `currencySelectorRoute` prop and use a unique route for each place.  


### What alternative solutions did you explore? (Optional)
Or we can use the same way as we do in `PaymentCardChangeCurrencyForm` for `PaymentCardForm`

**Comment by puneetlath** [comment] 2024-08-19 14:32
Is this not the default behavior for modals? Should we make it the default if it isn't?

**Comment by puneetlath** [comment] 2024-09-09 16:05
I added it. @shubham1206agra can you please complete the checklist?

**Comment by puneetlath** [comment] 2024-09-25 08:10
@Krishna2323 has been paid. 

Waiting on checklist and [offer](https://www.upwork.com/nx/wm/offer/104119050) acceptance from Shubham.

**Comment by puneetlath** [comment] 2024-09-26 05:19
All paid. Thanks y'all!

**Closed by puneetlath** 2024-09-26 05:19 UTC
Labels: Reviewing, External, Weekly, Bug
