### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Categories - Toggle, GL code & Payroll code are no longer grayed out after renaming category

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45755] opened 2024-07-19 10:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4737496
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace is under Control plan.

1. Go to staging.new.expensify.com
2. Go offline
3. Go to workspace settings
4. Go to Categories.
5. Click on any category.
6. Click on the toggle, edit GL code and Payroll code.
7. Note that the options gray out.
8. Click on the category name.
9. Rename the category and save it.

## Expected Result:
The toggle, GL code and Payroll code will remain grayed out after renaming the category.

## Actual Result:
The toggle, GL code and Payroll code are no longer grayed out after renaming the category.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9fa972be-0378-4a1d-b70d-0df9b2edaa46

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01432f0d4ba1a79d10</li>
        <li>Upwork Job ID: 1815330505338838748</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103234421</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by izarutskaya** [comment] 2024-07-19 10:40
We think this issue might be related to the #wave-control

**Comment by etCoderDysto** [comment] 2024-07-19 10:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Toggle, GL code & Payroll code are no longer grayed out after renaming category
### What is the root cause of that problem?
We are reseting pendingFields of the category we are editing to `name: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE`. This discards `GL code` and `Payroll code` pendingFields. 
https://github.com/Expensify/App/blob/eb6ca6d7b1b40eafa9bd01d8cda222adbcfc36b0/src/libs/actions/Policy/Category.ts#L283-L285
### What changes do you think we should make in order to solve the problem?
We should spread `policyCategoryToUpdate?.pendingFields` in `pendingFields` below 
```javascript
pendingFields: {
                            ...policyCategoryToUpdate?.pendingFields,
                            name: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
                        },
```
https://github.com/Expensify/App/blob/eb6ca6d7b1b40eafa9bd01d8cda222adbcfc36b0/src/libs/actions/Policy/Category.ts#L283-L285
### What alternative solutions did you explore? (Optional)

**Comment by superstar3222** [comment] 2024-07-22 15:57
Hello, I am one of the expert React Native developers, James Smith.
Now that we've identified your problem, we'd be happy to talk about a solution if you'd like.

**Comment by superstar3222** [comment] 2024-07-22 16:03
I am sorry.
I don't like working at Upwork because Upwork taxes are high.
I think that’s why it’s difficult to work together.

**Comment by superstar3222** [comment] 2024-07-22 16:13
Should I only work at Upwork?

**Comment by superstar3222** [comment] 2024-07-22 16:13
Can u pay elsewhere?

**Comment by superstar3222** [comment] 2024-07-22 17:05
Ok, I will do it.

**Comment by etCoderDysto** [comment] 2024-07-23 11:34
When editing category name, we add a pending action to name property which we will use to gray out the category name. 
https://github.com/Expensify/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Policy/Category.ts#L283-L284
Then when toggling the switch, we spread the existing category state that includes the existing pending field here 
https://github.com/Expensify/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Policy/Category.ts#L154

``` javascript
{
  "name": "Benefits c",
  "areCommentsRequired": false,
  "budget": [],
  "length": 0,
  "enabled": true,
  "pendingAction": "update",
  "pendingFields": {
    "name": "update"
  },
  "previousCategoryName": "Benefits"
}
```

Then it will merged with new pendingField that commes from the toggle 
https://github.com/Expensify/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Policy/Category.ts#L157-L159

And the result will be a pendingField of

pendingFields: { 
     "name": "update",
     enabled: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE, 
 },

**Comment by etCoderDysto** [comment] 2024-07-23 12:05
Great! I will raise a PR when I am assigned.

**Comment by etCoderDysto** [comment] 2024-07-26 18:32
I am working on a [PR](https://github.com/Expensify/App/pull/46176). It will be ready for review by tomorrow.

**Comment by superstar3222** [comment] 2024-07-26 18:46
Ok, thanks for the update.

**Comment by superstar3222** [comment] 2024-07-26 22:48
No updates yet.

**Comment by etCoderDysto** [comment] 2024-07-30 16:56
@rayane-djouah [PR](https://github.com/Expensify/App/pull/46176) is ready for review.
Sorry for being late. I was having [an issue](https://expensify.slack.com/archives/C01GTK53T8Q/p1721940296902559) when trying to build the iOS. 
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:E7E60270-DB92-4B4B-BC31-F9D0420DC6EA, OS:17.5, name:iPhone 15 Pro Max }
{ platform:iOS Simulator, id:E7E60270-DB92-4B4B-BC31-F9D0420DC6EA, OS:17.5, name:iPhone 15 Pro Max }
** BUILD FAILED **
```

**Comment by sonialiap** [comment] 2024-08-14 13:29
Payment summary:
- @rayane-djouah $250 - paid in upwork ✔️ 
- @etCoderDysto $250 - offer sent in upwork

**Comment by etCoderDysto** [comment] 2024-08-14 16:08
> @etCoderDysto $250 - offer sent in upwork

Thanks! I have accepted the offer.

**Comment by sonialiap** [comment] 2024-08-15 11:30
Paid ✔️

**Closed by sonialiap** 2024-08-15 11:30 UTC
Labels: External, Daily, Awaiting Payment, Bug
