### ISSUE TITLE
[Bug] iOS - Chat - The keyboard opens and covers the compose box when have message with a draft

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11118] opened 2022-09-19 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Navigate to a conversation (conv 1)
4.Click on the Pin icon on top right to pin the conversation to the top of LHN
5. Navigate to another conversation (conv 2)
6.Write something on compose box and navigate away from the conversation
7. Navigate to settings by clicking on the user avatar over the LHN
8.Click on preferences
9. Click on the Priority Mode option and select “#focus”
10. We alternately open a conversation with a draft and a pinned conversation

## Expected Result:
The keyboard should not close the compose box.

## Actual Result:
The keyboard opens and covers the composed box when have message with a draft

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.2.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191122955-4a17da67-503f-448e-a351-81fe93e64c7d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-09-20 08:43
This looks like a useful one to fix, but I'll put it on hold & make it Weekly since we're collecting all keyboard initiative issue 👍

**Comment by Beamanator** [comment] 2022-10-03 10:48
Still on hold

**Comment by mvtglobally** [comment] 2022-10-11 13:04
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2022-10-12 10:28
Still on hold

**Comment by tgolen** [comment] 2022-10-13 17:06
I removed the HOLD on this and assigned it to me because this is fixed in https://github.com/Expensify/App/pull/11586

**Comment by mvtglobally** [comment] 2022-10-24 18:33
Issue not reproducible during KI retests. (Third week) Closing

**Closed by mvtglobally** 2022-10-24 18:33 UTC
Labels: Reviewing, Engineering, Weekly, Bug
