### ISSUE TITLE
[Awaiting checklist] [$250] Edit comment - Remaining text in the composer is highlighted after deleting text

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43332] opened 2024-06-08 14:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-16
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
Precondition:
- Account has a lot of chats (so that LHN is not empty).

1. Go to staging.new.expensify.com
2. Go to chat.
3. Send a message.
4. Right click on the message > Edit comment.
5. Highlight the first portion of the message by dragging from right all the way to LHN.
6. Delete the highlighted text.

## Expected Result:
The remaining text will not be highlighted after deleting the text.

## Actual Result:
The remaining text is highlighted after deleting the text.
This issue only happens when dragging the text until the cursor reaches LHN.
This issue is not reproducible when the LHN is empty (where the cursor reaches when dragging).
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/041d2152-2b53-4a76-98ac-d9b1d38a4eb8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f82bb45e00f7a15</li>
        <li>Upwork Job ID: 1799816413393580513</li>
        <li>Last Price Increase: 2024-06-09</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 102678292</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by m-natarajan** [comment] 2024-06-08 14:17
@bondydaa FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-08 14:17
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment] 2024-06-09 19:55
Reverted the offending PR https://github.com/Expensify/react-native-live-markdown/pull/377

**Comment by mountiny** [comment] 2024-06-09 21:27
fixed in -17 version
https://github.com/Expensify/App/assets/36083550/e75d291b-aa88-4f35-9903-44866c16872d

**Comment by mountiny** [comment] 2024-06-10 14:31
@ShridharGoel Can you please comment on this issue so I can assign you?

**Comment by Tony-MK** [comment] 2024-06-10 16:33
Also, I am commenting based on the [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1718031693578749?thread_ts=1717944591.272779&cid=C01GTK53T8Q) with @mountiuny.

**Comment by roryabraham** [comment] 2024-06-10 16:40
@ShridharGoel can you please comment here for assignment, since you helped fix the issue?

**Comment by twisterdotcom** [comment] 2024-06-18 20:58
Hey! I'm the one responsible for payment - apologies but I'm going off the last date here which is the 20th. Do we know why there are two?

**Comment by Tony-MK** [comment] 2024-06-19 02:27
@twisterdotcom, From the [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1718031650287359?thread_ts=1717944591.272779&cid=C01GTK53T8Q) conversation with @mountiny, we decided to split the payment.

@jainilparikh and I don't have a problem with this.

Thanks.

**Comment by mountiny** [comment] 2024-06-20 12:04
Ok I think @ShridharGoel did most work with the revert so suggesting this division:

so:
- @ShridharGoel $150
- @jainilparikh $50
- @Tony-MK $50
- @allroundexperts $250 for review and testing

We should probably add penalty to C+ on this issue for missing these regressions https://github.com/Expensify/App/pull/43255

**Comment by twisterdotcom** [comment] 2024-06-20 12:14
Huge thanks to @mountiny here. Okay, 🎉 Here we are, it's the 20th. Payment Summary:

- @jainilparikh paid $50 [here](WIP) Contributor
- @Tony-MK paid $50 [here](WIP) Contributor
- @ShridharGoel paid $150 [here](https://www.upwork.com/nx/wm/offer/102809243)
- @allroundexperts paid $250 via newDot requests (C+)

@allroundexperts have we handled regression steps already?

**Comment by mallenexpensify** [comment] 2024-06-20 17:35
> We should probably add penalty to C+ on this issue for missing these regressions 

- https://github.com/Expensify/App/pull/43255

Looks like it was @ishpaul777 , that PR was a monster (most linked fixed issues I've ever seen in a PR). I'm unsure which of those issues would be the one for payment.  Any thoughts here @ishpaul777 ? 
<img width="1041" alt="image" src="https://github.com/Expensify/App/assets/22508304/78ac726d-9f72-4481-a09f-07a46178c0d4">

**Comment by allroundexperts** [comment] 2024-06-20 20:23
> @allroundexperts have we handled regression steps already?

I don't think so. The steps given in the OP look good enough to me!

**Closed** 2024-06-20 20:34 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-07-20 17:20
$250 approved for @allroundexperts
