### ISSUE TITLE
Chat - Preview of the image is not appearing for the first time when it's clicked to open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9333] opened 2022-06-07 14:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app and login with HT (High traffic)
2. Go to any chat
3. Sent attachment
4. Open preview for attachment

## Expected Result:
Preview should be open

## Actual Result:
Preview is not appearing for the 1st time and on 2nd attempt it opens.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** v1.1.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+fish@applause.expensifail.com / Qwerty123
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5600110_Screen_Shot_2022-06-07_at_9 11 08_AM](https://user-images.githubusercontent.com/43996225/172410719-86b39c9f-324b-4db5-9fe9-8d143a2d20d0.png)

https://user-images.githubusercontent.com/43996225/172410736-60907f0c-55dd-4ae5-a48d-3dd48d2ae857.mp4

Image used to reproduce this issue 
![165643581-5673760a-0b67-4bd1-96c0-7c9f36a9d977](https://user-images.githubusercontent.com/43996225/172411000-e696573d-256d-4165-8eae-495b36ad3c70.jpeg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2022-06-08 20:22
I've tested this several times today on the latest staging version and cannot reproduce:

https://user-images.githubusercontent.com/7277067/172709669-47c760ac-1313-4a8a-9995-ba32567804ca.mov

I _believe_ it was a regression caused by https://github.com/Expensify/App/pull/8928, which was reverted in https://github.com/Expensify/App/pull/9343, so it makes sense given the timing of my testing that I cannot reproduce. I also tested locally checked out to the commit for 1.1.73-0 (`git co 284e0bada7851288be011e2898c91fa81234cc3e`), and _could_ reproduce, so that seems to line up as well.

Going to close the issue, but feel free to reopen if someone disagrees with this assessment or is able to in staging or production.

**Closed** 2022-06-08 20:22 UTC
Labels: Engineering, Daily
