### ISSUE TITLE
[$250] Android narrow/low pixel tablets - Chat - The FAB button disappears or is covered by the keyboard in horizontal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12592] opened 2022-11-09 14:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12345

## Action Performed:
1. Open the App
2. Login with any account
3. Go to any chat room
4. Go to horizontal mode
5. Focus on composer input to show keyboard

## Expected Result:
The FAB button shouldn't floats to the top and sticks above the keyboard

## Actual Result:
The FAB button disappears or is covered by the keyboard

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android -model Xiaomi Mi Pad - Android 8.1

**Version Number:** 1.2.25.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200857830-b33bd54a-4fc5-4830-91dc-a0dc8f074964.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2022-11-11 00:18
Reassigning to Kadie as I'm about to head OOO

**Comment by kadiealexander** [comment] 2022-11-14 05:09
Asking for someone with an iPad to reproduce - https://expensify.slack.com/archives/C01GTK53T8Q/p1668402566426039

**Comment by kadiealexander** [comment] 2022-11-16 07:04
Reproduced here: https://expensify.slack.com/archives/C01GTK53T8Q/p1668409849644459?thread_ts=1668402566.426039&cid=C01GTK53T8Q

**Comment by kadiealexander** [comment] 2022-11-16 07:06
https://www.upwork.com/ab/applicants/1592776010907643904/job-details
https://www.upwork.com/jobs/~015b48fd1ba383cdca

**Comment by puneetlath** [comment] 2022-11-17 21:15
@iwiznia  this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:  
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by Julesssss** [comment] 2022-11-18 12:55
I think this is a good [example](https://expensify.slack.com/archives/C01GTK53T8Q/p1668775848267399?thread_ts=1668640125.477709&cid=C01GTK53T8Q) of why we should simply block rotation on native and review once we've actually reached reunification.

**Comment by iwiznia** [comment] 2022-11-18 13:35
I agree.

**Comment by JmillsExpensify** [comment] 2022-11-18 22:49
@Julesssss @iwiznia Do we want to disable rotation on native in this issue? I was going to close based on our discussion [in the community](https://expensify.slack.com/archives/C01GTK53T8Q/p1668811497897899?thread_ts=1668640125.477709&cid=C01GTK53T8Q), but we can also use this issue to prevent rotation bugs by disabling this action.

**Comment by iwiznia** [comment] 2022-11-21 10:27
Yeah, I think that makes sense.

**Comment by Julesssss** [comment] 2022-11-22 11:19
> Do we want to disable rotation on native in this issue? 

We disabled rotation years ago. I don't think we need to make any changes

**Comment by iwiznia** [comment] 2022-11-22 12:26
I am confused, then how did @kbecciv reproduced this if rotation is disabled?

**Comment by Julesssss** [comment] 2022-11-22 17:49
Ah, this is how. We lock rotation for small devices and unlock it for tablets: 

![Screenshot 2022-11-22 at 17 48 52](https://user-images.githubusercontent.com/10736861/203385567-8c3669ec-86ac-4e91-87e8-bf849c952b37.png)

**Comment by Julesssss** [comment] 2022-11-22 17:50
So I take that back, we unlocked rotation for tablets at some point.

**Comment by iwiznia** [comment] 2022-11-25 15:43
I have a PR here https://github.com/Expensify/App/pull/13043
But while testing, I realized that I can't really reproduce this issue on neither of the 2 ipad emulators I tried (ipad mini and ipad pro) and neither on the android emulator tablet (Pixel C).
The reason is that all of them seem to always show the big screen view (ie the one with LHN and main pane), so while my PR could make it that they don't rotate, that would mean a worse UX for the user.
My guess is this is only reproducible on tablets with a narrow form factor or less pixel density.
So the question is: do we still want to lock tablets to portrait mode? I think the answer is no and we rather have this small bug on old tablets than preventing users from rotating their tablets (which for lots of users will work fine).

If you agree, let's close this.

**Comment by JmillsExpensify** [comment] 2022-11-26 16:37
Assigning myself as well since we lost the BZ assignment somehow. Also chiming in on @iwiznia's question above. 

> My guess is this is only reproducible on tablets with a narrow form factor or less pixel density.
So the question is: do we still want to lock tablets to portrait mode? I think the answer is no and we rather have this small bug on old tablets than preventing users from rotating their tablets (which for lots of users will work fine).

Hmm, yeah I'm with you. I tried to reproduce this on my iPad mini and I wasn't able to. So I think I'm with you, we should close this. In fact, I'll do that but ahead of doing so I will update the title to remove iPad for clarity.

**Closed** 2022-11-26 16:38 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by iwiznia** [comment] 2022-11-28 13:39
To clarify, it's reproducible on older/smaller ipads.

**Comment by JmillsExpensify** [comment] 2022-11-29 06:45
@0xmiroslav for clarity, is it reproducible on non-tablets or just tablets? Reason being, we don't officially support tablets, though I'm more than happy to re-open if you think it's going to be fixed anyway.

**Comment by JmillsExpensify** [comment] 2022-11-29 06:50
Ok yeah, so all those are unsupported devices. In the interest of focus, let's just keep this closed. We need to tackle tablet support one day, but now isn't the time.

**Comment by mananjadhav** [comment] 2022-11-29 06:52
I agree with @JmillsExpensify. We're focused on items such as BugZero, WAQ, and Dark theme, etc. Tablets isn't the focus right now, and I think we should tackle tablets sometime in future.
