### ISSUE TITLE
[HOLD for payment 2024-08-19]  LHN - App crashes after tap on any chat in LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47134] opened 2024-08-09 06:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4838537
**Email or phone of affected tester (no customers):** fischer9966+080824dadm@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open iOS App
2. Login with any account
3. Tap to any chat in LHN

## Expected Result:
Chat opens correctly

## Actual Result:
App crashes after tap on any chat in LHN

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[log_crash.txt](https://github.com/user-attachments/files/16556926/log_crash.txt)

https://github.com/user-attachments/assets/c4593589-0978-4b74-9085-86212689c958

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-08-09 06:35
We think that this bug might be related to #vip-vsb

**Comment by techievivek** [comment] 2024-08-09 11:27
I am on the latest main, and I can't reproduce this. Is this already fixed?

**Comment by techievivek** [comment] 2024-08-09 12:40
https://github.com/user-attachments/assets/59f3ebbc-464d-4d43-a36a-58b3c55a30aa

Tried once again on lastest main, and couldn't reproduce it.

**Comment by techievivek** [comment] 2024-08-09 12:40
Also, asked in #open-source channel to see if someone can reproduce it https://expensify.slack.com/archives/C01GTK53T8Q/p1723202882608139

**Comment by Beamanator** [comment] 2024-08-09 15:46
A few people are experiencing this - https://expensify.slack.com/archives/C049HHMV9SM/p1723190961011019

But not sure if anyone has reproduced in main

**Comment by trjExpensify** [comment] 2024-08-09 16:34
Thread discussion ongoing, @AndrewGable might have an idea.

**Comment by roryabraham** [comment] 2024-08-09 18:02
PR with a fix is ready to go

**Comment by roryabraham** [comment] 2024-08-09 18:25
this should be fixed in 9.0.18-8: https://github.com/Expensify/App/actions/runs/10323822881

**Comment by Beamanator** [comment] 2024-08-09 19:20
Woohoo!! Working in staging again!

**Comment by m-natarajan** [comment] 2024-08-09 19:23
Issue fixed 

https://github.com/user-attachments/assets/a9b33d2a-aba8-4673-8d46-e776118645aa

**Comment by techievivek** [comment] 2024-08-12 10:07
Going to close this since it's deployed to PROD and no payments or BZ checklist if required for this.

**Closed by techievivek** 2024-08-12 10:07 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
