### ISSUE TITLE
[$250] [Hold 40240] [Track Tax] Unable to save 0 as tax amount during request flow, but able to save it after creation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39856] opened 2024-04-08 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Collect workspace has some tax rates.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Start a manual request flow.
4. On confirmation page, click Show more > Tax.
5. Select a tax that is not 0%.
6. Click Tax amount.
7. Save 0.00 as tax amount.
8. Create the request and go to transaction thread.
9. Click Tax amount.
10. Save 0.00 as tax amount.

## Expected Result:
In Step 7, during the request flow, user should be able to save 0.00 as tax amount, as it is possible to save 0.00 as tax amount post-creation (Step 10).

## Actual Result:
In Step 7, tax reverts to the previous amount when saving 0.00 as tax amount. It is only possible to save 0.00 as tax amount after the request is created (Step 10).

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/609498a8-ca9a-494b-9b50-4c7a68193ab6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2914d77d4fb50a2</li>
        <li>Upwork Job ID: 1778104548229869568</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-08 19:30
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-04-08 19:31
@slafortune I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by FitseTLT** [comment] 2024-04-08 20:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Taxes - Unable to save 0 as tax amount during request flow, but able to save it after creation

### What is the root cause of that problem?
The condition here will be false as `taxAmount` is 0 which is falsy
https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L376-L377
So it will be reset to the original amount
### What changes do you think we should make in order to solve the problem?

We need to change it to 
```
        if (typeof transaction.taxAmount === 'number' && previousTransactionAmount === transaction.amount) {

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-04-08 20:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Taxes - Unable to save 0 as tax amount during request flow, but able to save it after creation

### What is the root cause of that problem?
We are using `transaction.taxAmount` as a condition here which will be falsy when `taxAmount` is 0
https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L376-L377
So it will be reset to the default tax amount
### What changes do you think we should make in order to solve the problem?

We need to change it to 
```
        if (typeof transaction.taxAmount === 'number' && previousTransactionAmount === transaction.amount) {

```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-04-11 03:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. In Step 7, tax reverts to the previous amount when saving 0.00 as tax amount. It is only possible to save 0.00 as tax amount after the request is created (Step 10).
2. Also in the same Step, if we try to save any tax amount that's > 0, it will throw `Maximum tax amount is 0`

### What is the root cause of that problem?
1. In [here](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L376-L378), we're not checking `transaction.taxAmount` properly, so 0-amount will be considered as `false` there and the tax amount not saved to Onyx.
2. In [here](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L42), we're not getting the `taxCode` right, in this case the `taxCode` is not set yet, so it's falling back to the default tax code which is "tax exempt", causing the maximum tax rate to be 0

### What changes do you think we should make in order to solve the problem?

1. In [here](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L376), change to
```
if (transaction.taxAmount !== null && transaction.taxAmount !== undefined && previousTransactionAmount === transaction.amount) {
```
2. In [here](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L42), change to
```
const transactionTaxCode = transaction?.taxCode ?? transaction?.taxRate?.data?.code ?? '';
```
So it will falllback to the `taxCode` of the selected `taxRate` if `taxCode` is not defined.

Or alternatively we can set the `taxCode` to the transaction draft and update it whenever `taxRate` is changed, so it will always be available when retrieving here.

### What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment] 2024-04-11 14:37
All proposals will fix the original bug. But we should go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/39856#issuecomment-2048867595) because he also fixes the additional bug that I think it is so serious

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-04-11 15:25
It's not an "additional" bug, it's a bug encountered using the same reproduction step, in the same user interaction flow so I believe it's part of this issue.

@bondydaa will decide on [the final assignment](https://github.com/Expensify/App/issues/39856#issuecomment-2049845772), thanks all!

**Comment by FitseTLT** [comment] 2024-04-11 15:30
@nkdengineer It's not only about the scope here your solution to the second bug is wrong doesn't fix it, I have given the right [fix](https://github.com/Expensify/App/issues/39856#issuecomment-2049919074) here. `transaction?.taxRate` is not populated until the user selects it so your suggestion doesn't fix anything.

@bondydaa please take a look at my comment [here](https://github.com/Expensify/App/issues/39856#issuecomment-2049919074) The second bug being discussed here is not going to be solved by the selected proposal I have already given the fix. Thx

**Comment by nkdengineer** [comment] 2024-04-11 15:56
> @nkdengineer It's not only about the scope here your solution to the second bug is wrong doesn't fix it

@FitseTLT It's working fine for me. Can you provide clear, reproducible steps to prove that it doesn't work?

Also I recommended 2 solutions for that issue, did you make sure to try both of them (and made sure to implement correctly) before saying so?

**Comment by FitseTLT** [comment] 2024-04-11 16:10
@nkdengineer We are already showing default Value on `tax` ( not tax amount) 
https://github.com/Expensify/App/blob/a7a6910b5befc010fa8bf1c9053bb3c9b7f4e719/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L301-L302
So we need to take that as a fallback here

https://github.com/Expensify/App/blob/fc8f34fab03cec2dcec41324410a54581e511ff8/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L42-L43

Your first solution doesn't even work and your alternative solution We don't need unnecessary hustle of  saving it to draft and so on, the root cause of the problem is that we are not using the right fallback and I have already suggested the right way to solve it. Now let's just wait for the reviewers response @DylanDylann @bondydaa Thnx

**Comment by nkdengineer** [comment] 2024-04-11 16:37
[Proposal updated](https://github.com/Expensify/App/issues/39856) with minor change to the main solution for the 2. issue, to handle case where default tax is non-0.

**Comment by nkdengineer** [comment] 2024-04-11 16:39
@FitseTLT Just FYI your proposed fix doesn't work at all when I try, when the user selects another tax rate, the "maximum tax amount" is still that of the default tax rate.

cc @DylanDylann @bondydaa

**Comment by FitseTLT** [comment] 2024-04-11 18:56
@DylanDylann To take into consideration when `transaction.taxRate` is not set we can give the fallback here instead of my previous suggestion
https://github.com/Expensify/App/blob/a7a6910b5befc010fa8bf1c9053bb3c9b7f4e719/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L44
```
    const moneyRequestTaxPercentage = transaction?.taxRate?.data?.value ?? taxRates?.taxes[taxRates?.defaultExternalID]?.value ?? defaultTaxValue ?? '';

```
as we are clearly taking the `transaction?.taxRate?.data?.value ` when calculating `moneyRequestTaxPercentage` the only problem is the lack of the default tax set by default.

Note also that giving `transaction?.taxRate?.data?.value ` as a fallback doesn't make sense as we are already using it to calculate `moneyRequestTaxPercentage`

https://github.com/Expensify/App/blob/a7a6910b5befc010fa8bf1c9053bb3c9b7f4e719/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L44

I have [updated](https://github.com/Expensify/App/issues/39856#issuecomment-2043556373) my proposal accordingly and also want to mention that the first proposal of @nkdengineer wasn't solving anything as I explained it above we are already setting the right value when transaction.taxRate is set and now he is taking my idea and updating his proposal. Thx.

**Comment by trjExpensify** [comment] 2024-04-11 22:39
CC: @MonilBhavsar Track Tax related.

**Comment by MonilBhavsar** [comment] 2024-04-12 06:07
Thanks! This might be fixed by https://github.com/Expensify/App/issues/39616#issuecomment-2044331690. Let's put it on HOLD

**Comment by slafortune** [comment] 2024-04-16 13:02
I'll be out until 4/22 but not going to add another BZ since this is in a good place 👍

**Comment by slafortune** [comment] 2024-05-08 02:46
Still on HOLD

**Comment by slafortune** [comment] 2024-05-10 14:56
Still on. hold

**Comment by MonilBhavsar** [comment] 2024-05-23 14:37
Should be fixed by refactor https://github.com/Expensify/App/pull/40240/files#diff-29ef0426ea09b0af3420c95911645adcd54c0d3d4c0d8c4fa5aa99dfe37a3646R342-R366

**Comment by slafortune** [comment] 2024-05-23 20:51
I'll be out on vacation until June 4th, not assigning another BZ since this won't need any action before that.  If something changes @MonilBhavsar Please remove me and add the bug table once more to get another BZ assigned.

**Comment by MonilBhavsar** [comment] 2024-06-03 10:18
on HOLD

**Comment by trjExpensify** [comment] 2024-06-10 09:22
Did this get fixed?

**Comment by MonilBhavsar** [comment] 2024-06-10 09:31
Yes, this is fixed!


https://github.com/Expensify/App/assets/32012005/62139c15-75c1-4599-93bf-895088bdf408

Closing this issue

**Closed by MonilBhavsar** 2024-06-10 09:31 UTC
Labels: External, Weekly, Help Wanted, Bug
