### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$125] Expense - "Receipt" label does not appear above receipt placeholder for p2p expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43076] opened 2024-06-04 21:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4574596
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense without receipt.
4. Go to transaction thread.
5. Note that "Receipt" label appears above receipt placeholder.
6. Submit an expense to any user.
7. Go to transaction thread.

## Expected Result:
"Receipt" label will appear above receipt placeholder for p2p expense.

## Actual Result:
"Receipt" label does not appear above receipt placeholder for p2p expense.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/3900f88a-26f0-4cb7-bd48-f40e1520e29f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed4993b4406f58d2</li>
        <li>Upwork Job ID: 1798815121621554421</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102644040</li>
<li>neonbhai | Contributor | 102644041</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by m-natarajan** [comment] 2024-06-04 21:50
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-04 21:50
We think that this bug might be related to #wave-collect - Release 1

**Comment by neonbhai** [comment] 2024-06-04 22:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Receipt" label does not appear above receipt placeholder for p2p expense

### What is the root cause of that problem?
We check for a paid group policy when showing receipt header
https://github.com/Expensify/App/blob/594ae488b4b933d52307caa82da8f6e385e65723/src/components/ReportActionItem/MoneyRequestView.tsx#L333


### What changes do you think we should make in order to solve the problem?
We should remove the paid group policy check [here](https://github.com/Expensify/App/blob/594ae488b4b933d52307caa82da8f6e385e65723/src/components/ReportActionItem/MoneyRequestView.tsx#L333)

```jsx
const shouldShowReceiptHeader = isReceiptAllowed && (shouldShowReceiptEmptyState || shouldShowMapOrReceipt) && canUseViolations;
```

**Comment by luacmartins** [comment] 2024-06-04 23:16
I don't think we need to block the deploy on this and it seems to be a regression from https://github.com/Expensify/App/issues/41489. @Krishna2323 @sobitneupane could you please take a look?

**Comment by cead22** [comment] 2024-06-05 23:27
I think it makes sense to show the receipt header in all cases, since all the other fields have headers as well. What do you think @JmillsExpensify ?

**Comment by CortneyOfstad** [comment] 2024-06-07 17:31
@getusha — we have a few proposals — can you provide feedback on those by EOD? Thank you!

**Comment by getusha** [comment] 2024-06-07 17:53
This has a straightforward fix @neonbhai's [proposal](https://github.com/Expensify/App/issues/43076#issuecomment-2148487435) looks good to me
🎀 👀 🎀 C+ Reviewed!

**Comment by neonbhai** [comment] 2024-06-09 18:06
Raising PR soon!

**Comment by CortneyOfstad** [comment] 2024-06-10 16:23
Awesome — thanks @neonbhai!

**Comment by getusha** [comment] 2024-06-10 17:09
Waiting a PR from @neonbhai

**Comment by getusha** [comment] 2024-06-13 08:45
@neonbhai any updates?

**Comment by neonbhai** [comment] 2024-06-14 02:41
PR is ready for review!

**Comment by CortneyOfstad** [comment] 2024-06-25 15:07
PR deployed to staging 4 days ago 🎉

**Comment by CortneyOfstad** [comment] 2024-06-28 15:39
@getusha can you please complete the checklist above before beginning of next week, so there is no delay in payment? Thanks!

**Comment by getusha** [comment] 2024-06-28 19:43
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41635
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41635#issuecomment-2197523544
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **No, this bug isn't impactful enough to create a regression test**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/a**

**Comment by CortneyOfstad** [comment] 2024-07-02 18:08
@getusha looks like we're still waiting for you to accept the payment in Upwork. Please let me know once you accept and I can get that paid ASAP. Thank you!

**Comment by CortneyOfstad** [comment] 2024-07-03 15:10
Bump @getusha ^^^ 

I am heading OoO until Tuesday (July 9th) so I would like to get this paid as soon as possible  without any further delay. Thanks!

**Comment by getusha** [comment] 2024-07-03 15:22
Accepted, thanks @CortneyOfstad

**Comment by luacmartins** [comment] 2024-07-03 15:31
@CortneyOfstad seems like the offer was accepted, can we close this issue now?

**Comment by CortneyOfstad** [comment] 2024-07-09 16:24
## Payment Summary

@getusha — paid $125 via Upwork
@neonbhai — paid $125 via Upwork

**Closed by CortneyOfstad** 2024-07-09 16:24 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
