### ISSUE TITLE
[$250] Scan split - Confirmation page & Category RHPs appear together when opening Category

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40538] opened 2024-04-19 09:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a scan split expense.
4. Click on the split preview.
5. Click Category.
6. Select a category.
7. Click Category again.

## Expected Result:
There will not be another RHP appearing when opening Category list.

## Actual Result:
Confirmation page RHP appears briefly together with Category list RHP when opening Category list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/33dc4e3c-a319-4a04-b820-660736a382c4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014586c0d55dcc99f4</li>
        <li>Upwork Job ID: 1781430402702237696</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-19 09:39
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-19 09:39
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-19 09:39
Production 

https://github.com/Expensify/App/assets/115492554/604dcd50-f307-443c-a19a-4c61db44267e

**Comment by MariaHCD** [comment] 2024-04-19 11:35
Oh, I see it happens once the expense is submitted and scanning is in progress:

https://github.com/Expensify/App/assets/12268372/4f25d176-80bb-4750-b73d-bb933d5a74a1

**Comment by adelekennedy** [comment] 2024-04-19 16:27
@MariaHCD is this an actual deploy blocker? Or can we scale this back to a high priority bug?

**Comment by adelekennedy** [comment] 2024-04-19 21:10
related to categories - making this wave collect!

**Comment by adelekennedy** [comment] 2024-04-19 21:11
removed the deploy blocker label and re-added the external label

**Comment by bernhardoj** [comment] 2024-04-21 09:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The navigation transition is really weird when navigating to the money request category page.

### What is the root cause of that problem?
On the category page, we use a selection list. In the selection list (specifically in BaseListItem), we have a `useSyncFocus` that will give the selected/focused item a browser focus (`.focus()`)
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/hooks/useSyncFocus/index.ts#L11-L17

Because we focus immediately after mount, you can see that the navigation transition animation for the category page is gone and there is a weird transition happening only when we open the category page from the SplitBillDetailsPage.

Focusing on an element after component mount is a common issue we face, that's why we always delay, for example, auto focus on a page or waiting for screen transition end.

### What changes do you think we should make in order to solve the problem?

In our case, we can either wrap selection list with `withNavigationTransitionEnd` HOC to get the transition end state or just use `isInitialSectionListRender` state. It's simpler to use `isInitialSectionListRender`.

`isInitialSectionListRender` initial value is true and will be set to false when the selection list calls `onLayout`. Then, we will only enable the focus once `isInitialSectionListRender` becomes false.
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/SelectionList/BaseSelectionList.tsx#L361

```
shouldSyncFocus={!isTextInputFocusedRef.current && !isInitialSectionListRender}
```

If we want to use transition end, then it becomes

```
shouldSyncFocus={!isTextInputFocusedRef.current && didScreenTransitionEnd}
```

**Comment by MariaHCD** [comment] 2024-04-22 10:06
I agree that this doesn't need to block the deploy.

@thesahindia could you review the above proposal?

**Comment by adelekennedy** [comment] 2024-04-24 19:30
@thesahindia bump on the proposal review!

**Comment by bernhardoj** [comment] 2024-04-27 13:24
This is already fixed in https://github.com/Expensify/App/pull/40562. I can't reproduce it anymore. Can someone retest?

**Comment by MariaHCD** [comment] 2024-04-29 07:18
@izarutskaya could you please retest this to see if it's still reproducible?

**Comment by MariaHCD** [comment] 2024-05-02 07:56
Not overdue, we just need to retest this. cc: @izarutskaya

**Comment by adelekennedy** [comment] 2024-05-06 17:06
@izarutskaya has this been retested?

**Comment by adelekennedy** [comment] 2024-05-08 19:28
I can't reproduce - I'm going to close this one and we can reopen if this happens again?

**Closed by adelekennedy** 2024-05-08 19:28 UTC
Labels: External, Engineering, Daily, Overdue, Bug, retest-weekly
