### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] Android - Scan IOU - A broken image is downloaded to the device when receipt cannot be downloaded

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27992] opened 2023-09-22 08:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app.
2. Create a Scan IOU.
3. Open the IOU details view.
4. Tap on the receipt > overflow menu > Download.
5. Close the error message.
6. Go to the device gallery.
Note that a broken image is downloaded despite the error message.

## Expected Result:
Nothing will be downloaded to the device since it shows 'Attachment cannot be downloaded' message.

## Actual Result:
A broken image is downloaded to the device despite the 'Attachment cannot be downloaded' message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.72-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/24dfe60d-68a1-407a-b558-1cf646334626

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126f987f66d4dbcf0</li>
        <li>Upwork Job ID: 1705133271802134528</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27229717</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-09-22 08:13
Yep, that's a bug. @izarutskaya do you know what caused it to throw the error?

**Comment by ayazalavi** [comment] 2023-09-22 11:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
As soon as user try downloading file then error is thrown along with junk file stored.

### What is the root cause of that problem?
Root cause exists when we try to copy file in media store which does not exist. https://github.com/Expensify/App/blob/171259c4b47eb1788570db07aa9fbcdcc37ac650/src/libs/fileDownload/index.android.js#L75-L84

This results in junk file saved.

### What changes do you think we should make in order to solve the problem?
Use RNFetchBlob.fs.exists(attachmentPath) to check if file exists before trying to save the file. 

### What alternative solutions did you explore? (Optional)
RNFetchBlob has bugs ,we can tailor each issue like this one and fix them all.

**Comment by ayazalavi** [comment] 2023-09-22 12:00
Hi @mananjadhav,

I hope you're well. I would like to request your approval for my proposal. If you can provide the approval, I will be able to create the pull request (PR) within the next hour. Your prompt response would be greatly appreciated.

Thank you for your consideration.

Best regards,
Ayaz Alavi

**Comment by mananjadhav** [comment] 2023-09-24 15:20
I think considering the broken behavior @bernhardoj's proposal makes more sense. Tagging @shawnborton for more info.

🎀 👀 🎀 C+ reivewed.

**Comment by shawnborton** [comment] 2023-09-25 00:57
Hmm my take is, is it possible to fix the fact that the image can't be downloaded? If not, then I agree, we should not download a broken image after seeing that error message.

**Comment by ayazalavi** [comment] 2023-09-25 02:59
@shawnborton @mananjadhav  it is android only bug. same code is getting file downloaded just fine in other platforms so basically file name convention is not a bug here. As I mentioned in my proposal it is android file system bug and needs to solved only in index.android.js. Quickest solution is to check whether file exists i.e. android file system can read the given file path. If not then dont save the file otherwise file stored will be empty. It is bug in the code it is not checking whether file exists prior to saving it in media store.

**Comment by shawnborton** [comment] 2023-09-25 03:21
Ah then if that is the case, let's try to fix the file not getting downloaded.

**Comment by ayazalavi** [comment] 2023-09-25 03:30
@shawnborton yes I have proposed that already.

**Comment by ayazalavi** [comment] 2023-09-26 04:17
@marcaaron @sakluger please provide your input about above comments.

**Comment by marcaaron** [comment] 2023-09-26 08:51
Well, wow, I actually don't super understand the root cause here. @bernhardoj's explanation is pretty unclear.

>I don't know the reason why a broken file is saved even though the download fails.

Can we not figure this out? Also why did the download fail? What do we need to understand this problem better?

>The issue is, that if we try to download the receipt image and log the image URI, it contains an auth token, so the full URI would be like file:///.....?encryptedAuthToken=asdWJWAPdad...
>So, it makes sense the lib can't find the file. (the receipt image will initially be a local file and later will be replaced with an image from the server, at least on the web)

I don't really understand what you are trying to say here. Where are we _logging_ an image URI? And why does it "make sense" that the lib (which lib exactly?) can't find the file? 😕 

I'm going to kick this one back to @mananjadhav to manage for now to try again. @mananjadhav Please work with the contributors here to put forward a complete proposal that clearly describes the problem and offers a solution.

**Comment by ayazalavi** [comment] 2023-09-26 09:49
@marcaaron look at the video I attached with my proposal. Additionally [copytomediastore](https://github.com/RonRadtke/react-native-blob-util#copytomediastore) copies existing file to media directory but if file does not exists then it will save empty file there. Android filesystem is not able to understand path provided, it is android only bug and exists due to OS incompatibility with the plugin . Simply using **RNFetchBlob.fs.exists(attachmentPath)** can avoid saving empty file which will sort out the issue.

**Comment by sakluger** [comment] 2023-09-29 04:31
@mananjadhav can you please take a look at Marc and Shawn's concerns and advise how you think we should proceed here?

**Comment by mananjadhav** [comment] 2023-10-02 15:49
@sakluger I am still catching up on my issues. This looks a bit critical, then can you please reassign someone else?

**Comment by sakluger** [comment] 2023-10-02 20:36
Thanks for letting me know @mananjadhav, I've reassigned to another C+.

**Comment by mvtglobally** [comment] 2023-10-05 03:02
Issue not reproducible during KI retests. (First week)

**Comment by ayazalavi** [comment] 2023-10-05 03:39
@mvtglobally can you look at my proposal, it will still prevent empty file to be saved in camera roll. Do you think we can implement that here?

**Comment by sakluger** [comment] 2023-10-05 05:54
@mvtglobally what happens now when you retest? Do we still show an error but no longer download the file? Or do we no longer show the error?

**Comment by marcaaron** [comment] 2023-10-10 18:23
Can someone hold the reins here and summarize where we are at with this one? Maybe @ArekChr?

**Comment by mvtglobally** [comment] 2023-10-12 03:43
Issue not reproducible during KI retests. (Second week)

**Comment by ayazalavi** [comment] 2023-10-13 04:35
@sakluger have you looked at my proposal? It is addressing problem we are facing and providing a fix. let me know your thoughts. thanks

**Comment by ArekChr** [comment] 2023-10-16 12:49
@bernhardoj You rightly pointed out the issue. I now understand the problem. When we operate in offline mode, a local file is stored. @marcaaron, the underlying issue is that we're concatenating the auth token to the local file's URI. This works when rendering the image because the Image component can handle the query parameter like `?authToken=bearer.token.etc`. However, when the local URL includes the token, RNFetchBlob treats it as part of the file path. As a result, we get a "file not found" error. We should strip the token from the file URL during local file downloading. @bernhardoj's solution addresses this problem.

**Comment by sakluger** [comment] 2023-10-16 18:18
@ayazalavi I don't review any proposals as I am not an engineer - I'm just helping to manage the GH issue and keep it moving forward.

@marcaaron do you agree with @ArekChr's recommendation to go with @bernhardoj's solution?

**Comment by marcaaron** [comment] 2023-10-16 23:10
Sounds good. Yes I agree after reading the updated proposal.

**Comment by jjcoffee** [comment] 2023-10-17 12:49
Looks like this would also fix https://github.com/Expensify/App/issues/29749, could you confirm @ArekChr or @bernhardoj?

**Comment by ArekChr** [comment] 2023-10-23 12:39
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: We can create regression test.

Regresion test proposal:

1. Open app and enable offline mode.
2. Create a Scan IOU.
3. Open the IOU details view.
4. Tap on the receipt > overflow menu > Download.
5. Ensure that the image downloaded succesfully and verify if image is valid.

Do we agree :+1: or :-1:

**Comment by sakluger** [comment] 2023-10-27 15:56
Proposed regression test steps look good. 👍 

I've paid out @bernhardoj, so we're good to close this one. Thanks everyone! 🚀

**Closed by sakluger** 2023-10-27 15:56 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
