### ISSUE TITLE
[$250] Shows blue line around eye icon reported by @gadhiyamanan

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11384] opened 2022-09-28 18:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > security > change password
2. Click on eye icon several times
3. After clicking, ghost/test from the field below is selected. 

Note: This is true for both password fields, each time after clicking the the eye a couple of times the ghost/text below that field is selecction

## Expected Result:
Clicking on the eye several times shouldn't select text in the field below

## Actual Result:
Clicking on the eye several times selects text in the field below

## Workaround:
None

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.10-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="Screenshot (191)" src="https://user-images.githubusercontent.com/43996225/192861573-b9863733-3c85-48b3-a84d-05897b34d06a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663143478864599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-09-29 20:40
I can't seem to reproduce this one Web, though I'm a version behind and wasn't able to reproduce this on 1.2.8-0. Going to keep this open and try again just as soon as I can get my web app to update to the latest.

**Comment by JmillsExpensify** [comment] 2022-10-03 20:12
I'm unable to reproduce that exact bug, though interestingly, one thing I do see is that when clicking the the eye a couple of times we actually select the ghost text in the field below. Notice the "nueva" selected in this screenshot.

![Screen Shot 2022-10-03 at 15 09 54](https://user-images.githubusercontent.com/1127863/193669666-012500b8-ef54-4fcf-998a-1280cd9f3781.png)

Note: The blue box around the eye DOES NOT appear while clicking. This only appears when I take a screenshot.

**Comment by JmillsExpensify** [comment] 2022-10-03 20:12
Given that I can reproduce, I'm going to update the reproducible steps and then release this to contributors (Going to skip engineering because internally we're focused on other projects).

**Comment by JmillsExpensify** [comment] 2022-10-03 20:18
Upwork job is here: https://www.upwork.com/jobs/~01bfd298096cd2d352

**Comment by aliahmad-997** [comment] 2022-10-03 22:11
<img width="596" alt="image" src="https://user-images.githubusercontent.com/78139953/193691397-9badbeab-e33a-4869-937c-3864caddf480.png">

Able to reproduce it like this. Similarly if we click several times the eye icon it selects the "New password" text. The reason for that is eye is part of outer container, the main container. So, whenever we click many times in a container or main container by default we are able to select the near by text. 

And even if we remove the text it will select the save button text. 

The one solution is to apply user select none to text divs this will disable the selection on those divs.

The other is workaround, placing divs with empty string between the divs and giving the opacity 0.

**Comment by JmillsExpensify** [comment] 2022-10-03 22:38
> The reason for that is eye is part of outer container, the main container. So, whenever we click many times in a container or main container by default we are able to select the near by text.

Ah that's super interesting. So if this is expected behavior, is this really a bug then? I actually wasn't aware of that, and at that point given that I can't reproduce the blue outline of the eye container, I'd be even more for closing the issue at this juncture.

**Comment by JmillsExpensify** [comment] 2022-10-05 23:21
@chiragsalian What do you think on my last comment?

**Comment by chiragsalian** [comment] 2022-10-05 23:33
Hmm i cannot reproduce the blue outline around the eye container. 

But I can reproduce the selection issue mentioned [here](https://github.com/Expensify/App/issues/11384#issuecomment-1266120857). The specific issue captured here is sort of low value so I don't mind closing it by I think it would be nice if we can find a solution to improve BaseTextInput vs hacky CSS solution. This way if we improve our BaseTextInput it would be nice to know that all secure inputs would have a more consistent eye functionality. 

If we cannot find a better long term solution I'm down for closing the issue versus applying CSS hacks that's specific for every situation we use BaseTextInput.

**Comment by JmillsExpensify** [comment] 2022-10-06 18:59
> Hmm i cannot reproduce the blue outline around the eye container.

Agreed I can't reproduce the exact bug [either](https://github.com/Expensify/App/issues/11384#issuecomment-1265975130). 

As for working on this versus closing, I tend to think we should close and come back to this after we refactor account settings (as well as these pages). Re-open if you disagree.

**Closed by JmillsExpensify** 2022-10-06 18:59 UTC
Labels: External, Daily, Help Wanted
