### ISSUE TITLE
[HIGH] [$500] Task - "This is the beginning of your chat" instead of last message shown in LHN after refreshing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37760] opened 2024-03-05 15:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37340
## Action Performed:

1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a task in 1:1 DM or a Room with a long chat history and find it in LHN
4. Delete the task and reload the page

## Expected Result:
The last message is displayed in the chat preview in LHN

## Actual Result:
"This is the beginning of your chat with <user>" message is shown in LHN instead of the last message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/115492554/638655d6-2f0c-4b2b-b061-c5ebe157f022

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a182ad9ea043c9fd</li>
        <li>Upwork Job ID: 1766182827403227136</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-05 15:05
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-03-05 15:05
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment] 2024-03-05 19:48
I think this is an edge case so I'm going to close.

**Comment by izarutskaya** [comment] 2024-03-08 12:49
This bug is still reproducible
Build v1.4.49-0

And we have alternative reproducible steps:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a task in 1:1 DM with a long chat history and find it in LHN
4. Delete the task and reload the page

https://github.com/Expensify/App/assets/115492554/638655d6-2f0c-4b2b-b061-c5ebe157f022

**Comment by garrettmknight** [comment] 2024-03-08 19:10
I agree that this happens, but I don't think it's a mainline use case we need to fix.

**Comment by rojiphil** [comment] 2024-03-09 10:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On deleting a task, LHN displays `This is the beginning...` message in LHN for the 1:1 DM chat.

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/SidebarUtils.ts#L322) we determine the last message text for the LHN from within the report. Now when the task is deleted, the last message text in the report will be empty which is intentional. Since we are not also looking into the message text within the latest visible action, the `This is the beginning…` message gets displayed [here](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/SidebarUtils.ts#L363C1-L366C30). This is the root cause.

### What changes do you think we should make in order to solve the problem?

[Here](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/SidebarUtils.ts#L363), we can additionally look for the last visible action’s message text and display the message if it is not empty. If empty, we can continue to display the `This is the beginning…` message.

We can make changes like this:

```
        if (!lastMessageText) {
            lastMessageText = ReportActionsUtils.getLastVisibleMessage(report.reportID)?.lastMessageText;
        }  
```

### What alternative solutions did you explore? (Optional)

**Comment by andrey010** [comment] 2024-03-09 15:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting task the last message is not displayed in the chat preview in LHN

### What is the root cause of that problem?
```OptionsListUtils.getLastMessageTextForReport``` return empty string, so in ```SideBarUtils``` we have empty value in ```lastMessageText``` and component render default value as for new chat ```'reportActionsView.beginningOfChatHistory'```
### What changes do you think we should make in order to solve the problem?
In order to solve problem I propose adding two additional conditions into ```OptionsListUtils.getLastMessageTextForReport```
``` js script
const isDeletedParentAction = ReportUtils.isCanceledTaskReport(report, lastOriginalReportAction)

else if (ReportActionUtils.getLastVisibleMessage(report?.reportID ?? '').lastMessageText &&!isDeletedParentAction) {
    lastMessageTextFromReport = ReportActionUtils.getLastVisibleMessage(report?.reportID ?? '').lastMessageText
} else if (isDeletedParentAction) { // <-- need this condition if chat view render as last message [Deleted task]
    lastMessageTextFromReport = Localize.translateLocal('parentReportAction.deletedTask');
}
```

**Comment by rojiphil** [comment] 2024-03-09 17:06
## Proposal

[Updated](https://github.com/Expensify/App/issues/37760#issuecomment-1986823356). 
Polished the root cause 
Also suggested alternatively to implement the main solution content within `getLastMessageTextForReport`

**Comment by garrettmknight** [comment] 2024-03-11 11:53
@alitoshmatov We've got a few proposals, can you review today?

**Comment by kmbcook** [comment] 2024-03-11 17:19
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Task - "This is the beginning of your chat" instead of last message shown in LHN after refreshing

### What is the root cause of that problem?
The backend is changing report.lastMessageText to an empty string when the task is cancelled.

### What changes do you think we should make in order to solve the problem?
Fix the backend.

**Comment by alitoshmatov** [comment] 2024-03-12 09:24
Reviewing

**Comment by alitoshmatov** [comment] 2024-03-13 15:24
Thanks everyone for your proposal. As @kmbcook suggested this looks like backend problem, because normally backend should not respond with empty string for `lastMessageText`. Moreover if we switch to offline mode everything works as expected indicating that the problem is indeed related to backend

<img width="383" alt="Screenshot 2024-03-13 at 8 23 16 PM" src="https://github.com/Expensify/App/assets/59907218/19377c24-93d3-4d49-aac4-4db2f722bf1f">

@garrettmknight Can we get internal engineer to take a look at this, since I think it is related to backend issue and can't be solved by external contributors

**Comment by kmbcook** [comment] 2024-03-14 10:27
I appreciate being recognized for my proposal! Could I get some kind of an Upwork offer, a win?  We are working together as a team, right?

**Comment by alitoshmatov** [comment] 2024-03-14 13:18
> I appreciate being recognized for my proposal! Could I get some kind of an Upwork offer, a win? We are working together as a team, right?

To be honest I concluded it was a backend issue way before I got to your proposal. I just didn't want to look ignorant to your proposal. 

Moreover backend related issues cannot be solved by external contributors, that is why there is no need for external input. 

Also please refer to https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions
> Please be aware that compensation for any support in solving an issue is provided entirely at Expensify’s discretion. Personal time or resources applied towards investigating a proposal will not guarantee compensation. Compensation is only guaranteed to those who [propose a solution and get hired for that job](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).

**Comment by kmbcook** [comment] 2024-03-14 15:38
I understand that currently there is no mechanism to compensate contributors who correctly identify the back-end as a root cause. However, it is not always obvious that the back-end is the root cause. If it were obvious, then there would be no need to add the job to Upwork. If this issue had not been added to Upwork, I could have avoided spending any time working on it. I am not upset with anyone, but I am asking that some innovative type of Upwork offer be used to compensate contributors in cases such as this. Innovative thinking as built this community, and I am suggesting that additional innovative thinking can improve it.

**Comment by garrettmknight** [comment] 2024-03-15 13:12
@kmbcook I appreciate the time spent investigating issues doesn't always result in a payout. I missed the initial point about this being BE and added the incorret label, triggering the Upwork job. This isn't part of the normal process, apols for the trouble.

**Comment by kmbcook** [comment] 2024-03-15 14:32
> BE bug, after deleting the task and returning online, `OpenReport` returned `lastMessageText` as empty.

@garrettmknight I missed that (above) comment too!

**Comment by garrettmknight** [comment] 2024-03-18 18:21
Still looking for an internal engineer to pick this one up.

**Comment by quinthar** [comment] 2024-03-20 01:18
Deprioritizing to FUTURE, along with other task bugs

**Comment by mvtglobally** [comment] 2024-03-20 03:41
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2024-03-22 19:04
Will test on Monday to see if we can close!

**Comment by garrettmknight** [comment] 2024-03-25 18:53
Couldn't repro either - closing!

**Closed by garrettmknight** 2024-03-25 18:53 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug, Hot Pick
