### ISSUE TITLE
[$250] Chat- Previous messages do not load on rejoining thread & then enabling internet connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39655] opened 2024-04-04 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4475785&group_by=cases:section_id&group_order=asc&group_id=291937
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition : Open 1:1 chat which has several previous messages
1. Navigate to a 1:1 Conversation
2. Start a thread and send some messages
3. Disable the internet connection on thread conversation page
4. Click on the three dot menu and hit "Leave thread"
5. User navigated back to the parent conversation
6. Click on the thread link to rejoin the thread (Note : skeleton loader is displayed since the user is offline)
7. Enable the internet connection

## Expected Result:
On enabling internet connection after rejoining thread, thread loads and all the previous messages are displayed

## Actual Result:
Previous messages do not load on rejoining thread & then enabling internet connection. Blank chat space is displayed once the user go online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/16d757cb-938f-4a41-9609-6a5aa189f9ef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa1379d6f9d45105</li>
        <li>Upwork Job ID: 1778440845939150848</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-04 20:41
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-04 20:42
We think that this bug might be related to #vip-vsp

**Comment by jacobkim9881** [comment] 2024-04-08 09:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
At report thread offline exiting the thread shows older chats as skeleton loading.

### What is the root cause of that problem?
`getContinuousReportActionChain` saves from unnecessary loading older chats for server responses to get renewed chats. But offline chats aren't renewed from BE server and `getContinuousReportActionChain` sorts older chats out. Without the older chats skeleton loading is shown. 

For sorting chats, some conditions are used. `previousReportActionID` is used as a condition. If `previousReportActionID` is `0` from a parent report, and then left older chats of an array get sorted out.

To order how the app acts in codes,

1. Open thread  
2. the thread's `previousReportActionID` gets `0` 
3. leave the room 

https://github.com/Expensify/App/blob/db15065eb8a224573900b47d47ca06d4fc479055/src/libs/ReportActionsUtils.ts#L313

4. Condition above is used for sorting and by this, older report actions  are cut (because of 2) 
5. On the parent report, load the sorted report actions
6. If online, backend server replace the sorted report actions
7. If offline, still showing skeleton without backend server response

### What changes do you think we should make in order to solve the problem?
If offline, we don't let the app sort report actions based on a condition for `previousReportActionID` because BE server doesn't response. So unsorted report actions are shown.

https://github.com/Expensify/App/blob/f7b000bd00bcea0c2c45f2ac452964e941d07246/src/pages/home/ReportScreen.tsx#L257

From above, we add condition 

```
const currentRangeOfReportActions = network.isOffline? sortedAllReportActions : ReportActionsUtils.getContinuousReportActionChain(sortedAllReportActions, reportActionIDFromRoute);
```

### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2024-04-08 14:44
@lanitochka17 I cannot follow your video — the cursor is moving too fast for me to clearly see what action is being take. Can you please update the original comment with a different video?

**Comment by jacobkim9881** [comment] 2024-04-10 02:11
@roryabraham Thanks for helping me identifying the root cause.  

Could you review my solution too? Importing `useNetwork` on [App/src/pages/home/ReportScreen.tsx](https://github.com/Expensify/App/blob/f7b000bd00bcea0c2c45f2ac452964e941d07246/src/pages/home/ReportScreen.tsx) could be heavy or passing for waiting BE response offline could bring any side effects?

**Comment by jacobkim9881** [comment] 2024-04-11 08:53
Older chats are loaded by this,

https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/pages/home/report/ReportActionsView.tsx#L342

If offline then above function isn't called because of this,

https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/pages/home/report/ReportActionsView.tsx#L323

**Comment by CortneyOfstad** [comment] 2024-04-11 15:13
@akinwale There is a proposal [here](https://github.com/Expensify/App/issues/39655#issuecomment-2042333754) from @jacobkim9881. @roryabraham provided some feedback, but if you have any input as well, please share — thanks!

**Comment by akinwale** [comment] 2024-04-11 19:40
@jacobkim9881 Could you update your proposal with the correct root cause and verify that the solution actually fixes this?

**Comment by jacobkim9881** [comment] 2024-04-13 06:27
## Proposal
[Updated](https://github.com/Expensify/App/issues/39655#issuecomment-2042333754)

**Comment by lanitochka17** [comment] 2024-04-13 22:05
@CortneyOfstad Tried to reproduce the issue several times. It repeats itself every other time.

https://github.com/Expensify/App/assets/78819774/957e1c31-bb76-4d95-a133-91a926015b72

**Comment by CortneyOfstad** [comment] 2024-04-15 13:51
@akinwale there is an update to the proposal [here](https://github.com/Expensify/App/issues/39655#issuecomment-2053523718) 👍

**Comment by akinwale** [comment] 2024-04-15 13:56
@jacobkim9881 Thank you for the update. Could you create a short video demonstrating the proposed fix?

**Comment by jacobkim9881** [comment] 2024-04-17 00:27
@akinwale  It isn't reproducible for now. As BE reponse `previousReportActionID` gets different value not `0`. Seems BE updated response for `previousReportActionID`. As a FE contributor, I can't access related information 😟

**Comment by CortneyOfstad** [comment] 2024-04-17 16:26
@lanitochka17 can you confirm if this issue is still happening?

**Comment by lanitochka17** [comment] 2024-04-17 23:11
@CortneyOfstad Not reproducible now.
Skeleton loader does not appear & all messages displayed as expected after leave/Join thread with or without internet


https://github.com/Expensify/App/assets/78819774/d3f97db5-67ef-472d-93fa-38eef9e3c99b

**Comment by mvtglobally** [comment] 2024-04-18 15:56
Issue not reproducible during KI retests. (First week)

**Closed** 2024-04-18 15:58 UTC
Labels: External, Daily, Help Wanted, Bug
