### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] Accounting - Not able to set up Quickbooks, Intuit page freezes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40978] opened 2024-04-25 13:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40713
## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Enable "Accounting" in the workspace settings
4. Navigate to the "Accounting" tab
5. Tap on the "Set up" button next to Quickbooks

## Expected Result:
I should be able to input data in the Intuit page fields

## Actual Result:
Not able to set up Quickbooks, Intuit page freezes. You can only use the "<" button for navigating back, nothing on the Intuit page is interactable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2a0a310d-0476-461e-b88e-1a813da54404

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by lanitochka17** [comment] 2024-04-25 13:20
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-25 13:20
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment] 2024-04-25 20:58
Hmm, I cannot reproduce. Works fine for me. Going to close this for now, since it's not consistently reproducible. If you're still able to consistently reproduce, please advise the device and app/android version you're using and happy to take another look!

https://github.com/Expensify/App/assets/54866469/f12bb080-06ad-4358-9fd8-378fae143eb4

**Comment by kbecciv** [comment] 2024-05-08 11:47
Issue is reproducible on build 1.4.71.0

https://github.com/Expensify/App/assets/93399543/3fe1565f-2789-4f49-830f-dca27aea36e5

**Comment by joekaufmanexpensify** [comment] 2024-05-08 13:47
I'm on `1.4.71-4` and I cannot reproduce it at all: 


https://github.com/Expensify/App/assets/54866469/6a4e6d7d-d605-40b9-b69d-1ce049618e34

**Comment by joekaufmanexpensify** [comment] 2024-05-08 13:48
@kbecciv if you can still reproduce this, please re-open and share the device type in addition to the app version so I can try on that same/similar device. 

For now, going to re-close, as I still cannot reproduce this at all.

**Comment by kavimuru** [comment] 2024-05-16 12:22
@joekaufmanexpensify Tester is still able to reproduce on Samsung Galaxy A52s 5G / Android 14 in the app version 1.4.74-1
Tester is  unable to swipe on the setup page. Reopening the issue.

https://github.com/Expensify/App/assets/43996225/f72e5884-7554-40f5-b8db-1a8db869831a

**Comment by kavimuru** [comment] 2024-05-16 13:07
Reproduced in Pixel 6 / Android 14 and Samsung S10+ / Android12. Video from pixel 6 is attached here.

Uploading video_2024-05-16_08-39-26.mp4…

**Comment by joekaufmanexpensify** [comment] 2024-05-16 20:47
Hmm I will try and reproduce with those devices

**Comment by joekaufmanexpensify** [comment] 2024-05-16 21:04
So interesting. I still cannot reproduce this at all. I'm on `1.4.71-4` for all of the below devices. 

## Samsung Galaxy A52 

https://github.com/Expensify/App/assets/54866469/a0cc3b4c-892e-42ef-92f3-ee92683de2a0

## Samsung S10 


https://github.com/Expensify/App/assets/54866469/6084feae-5787-44c6-93fa-6617b90e8552


## Pixel 6


https://github.com/Expensify/App/assets/54866469/3df022fc-7022-4947-aeff-df729b465505

**Comment by joekaufmanexpensify** [comment] 2024-05-16 21:06
@kavimuru Perhaps the issue here is using an out of date version of the app? Please feel free to retest and LMK if it's reproducible for you on the newer version of the app. 

But in the interim, I don't think we should move forward with this issue if we cannot consistently reproduce the issue. I personally have not been able to reproduce the issue on any device.

**Comment by kbecciv** [comment] 2024-05-31 14:40
@joekaufmanexpensify
Did you use an emulator or a real device? The QA team is able to consistently reproduce the issue on a real device, but it works fine when using a Bluetooth mouse. Can you please review the issue again? Thank you!

https://github.com/Expensify/App/assets/93399543/38a13663-7f67-4007-9619-86f6c2d875cf

**Comment by joekaufmanexpensify** [comment] 2024-05-31 21:05
@kbecciv I'm not using an emulator. I'm using browserstack, but according to our documentation, it uses real devices.

<img width="685" alt="image" src="https://github.com/Expensify/App/assets/54866469/ec9005ec-0d92-4153-a2dc-ba99f2ed91ba">

**Comment by joekaufmanexpensify** [comment] 2024-05-31 21:10
@kbecciv could you please confirm the device and app version used for the latest reproduction attempt and re-open the issue once you confirm? 

I'll then try it again on my end, and then recruit a secondary internal triager to see if they have a different experience from me.

**Comment by kavimuru** [comment] 2024-06-07 13:58
Issue is reproduced in Samsung Galaxy A52s 5G / Android 14 and ND app version 1.4.80-4 
https://platform.applause.com/services/links/v1/external/8ad2b37b22b5f095b86029797372de4ef89fbb10377a4418da0020f734bd0ecd

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:39
I don't have Samsung Galaxy A52s 5G specifically, but going to test on Samsung Galaxy A52

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:42
I'm on `1.4.80-9`. Still no issue for me. Can't reproduce at all: 

https://github.com/Expensify/App/assets/54866469/b93c9d0d-2673-4cc2-a883-b49a345b5d9c

**Comment by joekaufmanexpensify** [comment] 2024-06-07 14:45
[Asked for secondary triager](https://expensify.slack.com/archives/C01SKUP7QR0/p1717771538071359) to make sure this isn't working only for me.

**Comment by kavimuru** [comment] 2024-06-07 15:34
Able to reproduce with public domain (gmail ) account as well, as per this [comment](https://expensify.slack.com/archives/C9YU7BX5M/p1717772493937589).

https://github.com/Expensify/App/assets/43996225/3dcf855d-0b7a-4c72-bdec-dcfd69451b01

**Comment by joekaufmanexpensify** [comment] 2024-06-07 15:46
Interesting. I just tried with a public domain on my end, and it works totally fine. 

https://github.com/Expensify/App/assets/54866469/b05376b6-d7da-48de-b9cb-a3fde131b742

**Comment by joekaufmanexpensify** [comment] 2024-06-10 13:40
Going to get an additional internal secondary triager today

**Comment by rushatgabhane** [comment] 2024-06-10 20:43
this bug is reproducible

**Comment by joekaufmanexpensify** [comment] 2024-06-10 20:46
@rushatgabhane could you share the device and app version you're reproducing on?

**Comment by rushatgabhane** [comment] 2024-06-10 20:48
Physical Android - Pixel 7
Version: production v1.4.79-11

**Comment by rushatgabhane** [comment] 2024-06-10 20:48
the bug isn't reproducible on simulators

**Comment by joekaufmanexpensify** [comment] 2024-06-10 20:57
Interesting. Our [internal documentation ](https://github.com/Expensify/App/issues/40978#issuecomment-2142977346)says Browserstack (what I have been using to try and reproduce this), is using a real device connected to our staging APIs. Is that not correct?

**Comment by rushatgabhane** [comment] 2024-06-10 21:12
my real device is connected to production API

**Comment by joekaufmanexpensify** [comment] 2024-06-10 21:23
Yep, totally understand that. But given the length of time between when this issue was first opened and now, shouldn't the experiences on both be the same? 

Maybe our internal documentation is wrong though, and not all bugs can be reproduced via our browserstack account.

**Comment by rushatgabhane** [comment] 2024-06-10 21:43
yeah i think on browserstack you use your mouse as input but a physical device has touch input

**Comment by trjExpensify** [comment] 2024-06-11 00:01
@staszekscp, putting this on your radar for tomorrow morn. Coming from this convo: https://expensify.slack.com/archives/C036QM0SLJK/p1718063632916499?thread_ts=1718052353.532159&cid=C036QM0SLJK

**Comment by filip-solecki** [comment] 2024-06-11 13:00
Hi! I am Filip from SWM an expert agency and I'd like to work on this!

**Comment by filip-solecki** [comment] 2024-06-12 11:15
I am coming back with some proposal. From my investigation looks like the issue is related to `Modal` component. Basically while creating Modal we have to define type of the Modal and for integrations(both QBO and Xero) we picked CENTERED type. It allows users to close the modal by swiping down or right and it causes this issue. Changing type for CENTERED_UNSWIPEABLE solves the problem. The issue is known also for some other libraries and probably is related to the new arch. For now I think the best solution is to use other Modal type which allows us to fill the form on all devices and I think that disabling Modal hiding with swipe is not a problem since we have BackButton in header and also native goBack methods(like buttons or swiping from the left side of the screen)
[Here](https://github.com/Expensify/App/pull/43547) is PR for that.

**Comment by rushatgabhane** [comment] 2024-06-12 11:31
@filip-solecki i like the idea! We should a back button on iOS too?

**Comment by filip-solecki** [comment] 2024-06-12 11:55
We have back button in the `HeaderWithBackButton` component above the WebView

**Comment by rushatgabhane** [comment] 2024-06-12 11:56
Perfect, can you please mark the PR ready for review

**Comment by filip-solecki** [comment] 2024-06-12 11:56
Done

**Comment by joekaufmanexpensify** [comment] 2024-06-14 20:51
PR merged!

**Comment by joekaufmanexpensify** [comment] 2024-06-24 15:03
@rushatgabhane, could you please complete the checklist so we can prepare to issue payment?

**Comment by joekaufmanexpensify** [comment] 2024-06-25 14:26
Bumped in slack

**Comment by rushatgabhane** [comment] 2024-06-26 00:21
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40277

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40277/files#r1653766737

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. - No because part of QA
 
5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by joekaufmanexpensify** [comment] 2024-06-26 14:19
TY! Checklist is all set.

**Comment by joekaufmanexpensify** [comment] 2024-06-26 14:22
Only payment here is $250 to @rushatgabhane for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-06-26 14:22
@rushatgabhane you're all set to request payment via NewDot whenever you're ready. Going to close this for now, as it's otherwise all set!

**Closed by joekaufmanexpensify** 2024-06-26 14:22 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-28 17:53
$250 approved for @rushatgabhane
