### ISSUE TITLE
[$250] Expense - Submit button is missing after switching layout from mobile to web

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#52883] opened 2024-11-21 11:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**  applausetester+kh0811002@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Click + > Submit expense > Manual.
4. Proceed to confirmation page.
5. Note that Submit button is present.
6. Open developer tools and switch to mobile layout.
8. Note that Submit button is present.
9. Return to web layout.

## Expected Result:
Submit button will be shown.

## Actual Result:
Submit button is missing on confirmation page after switching layout from mobile to web.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d57492de-5591-479d-ac36-abd7c917bfeb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859734598640577777</li>
        <li>Upwork Job ID: 1859734598640577777</li>
        <li>Last Price Increase: 2024-11-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by huult** [comment] 2024-11-21 17:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Submit button is missing after switching layout from mobile to web

### What is the root cause of that problem?

The submit button is missing because the footer content is not rendered due to a condition that causes an early return, preventing the submit button from being rendered. This happens because `isWindowHeightReducedByKeyboard` returns `true`.

https://github.com/Expensify/App/blob/937064c997d2cbfe8d3d9f6eb181e6da03923c2c/src/components/MoneyRequestConfirmationList.tsx#L825-L827

When we open the developer tools and switch to the mobile layout, `isWindowHeightReducedByKeyboard` returns `true`.

https://github.com/Expensify/App/blob/9c4e6625d04582d3404c806b328064ce02aa0976/src/hooks/useIsWindowHeightReducedByKeyboard/index.ts#L28

After switching to the desktop layout, `isWindowHeightReducedByKeyboard` still returns `true` because it is unable to update. Inside `toggleKeyboardOnSmallScreens`, we check `shouldUseNarrowLayout` and return early. On desktop, `shouldUseNarrowLayout` returns `false` because it is neither a small screen and not `isNarrowPaneModal`. As a result, `isWindowHeightReducedByKeyboard` does not update its value and remains `true`, causing the footer content to return early and the submit button to be missing.

https://github.com/Expensify/App/blob/9c4e6625d04582d3404c806b328064ce02aa0976/src/hooks/useIsWindowHeightReducedByKeyboard/index.ts#L11-L19


### What changes do you think we should make in order to solve the problem?

To resolve this issue, we should reset `isWindowHeightReducedByKeyboard` to `false` when resizing to desktop. Something like this

https://github.com/Expensify/App/blob/9c4e6625d04582d3404c806b328064ce02aa0976/src/hooks/useIsWindowHeightReducedByKeyboard/index.ts#L11-L19

to 

```diff
    const toggleKeyboardOnSmallScreens = useCallback(
        (isKBOpen: boolean) => {
            if (!shouldUseNarrowLayout) {
+                if (!isSmallScreenWidth && isWindowHeightReducedByKeyboard) {
+                    setIsWindowHeightReducedByKeyboard(false);
+                }

                return;
            }
            setIsWindowHeightReducedByKeyboard(isKBOpen);
        },
        [shouldUseNarrowLayout],
    );
```

<details>
<summary>POC</summary>



</details>

### What alternative solutions did you explore? (Optional)

We can update the condition in the footer content to return when `isWindowHeightReducedByKeyboard` is `true` and the screen is small. This ensures it will not execute on desktop. Something like this:

https://github.com/Expensify/App/blob/937064c997d2cbfe8d3d9f6eb181e6da03923c2c/src/components/MoneyRequestConfirmationList.tsx#L825-L827

to

```diff
-   if (isReadOnly || isKeyboardShown || isWindowHeightReducedByKeyboard) {
+   if (isReadOnly || isKeyboardShown || (isSmallScreenWidth && isWindowHeightReducedByKeyboard)) {
        return;
    }
```

**Comment by s77rt** [comment] 2024-11-22 16:40
This is a regression from https://github.com/Expensify/App/pull/51318 and I think it's still within the regression period. It's also causing other bugs e.g. https://github.com/Expensify/App/issues/52828. It may be best to revert the PR

cc @truph01 @eh2077 @thienlnam

**Comment by thienlnam** [comment] 2024-11-22 18:40
It says this is also reproducible on production, so wouldn't it be a different issue?

**Comment by thienlnam** [comment] 2024-11-22 18:50
Ah wait nvm, that PR has been on prod for a while

**Comment by aldo-expensify** [comment] 2024-11-22 18:55
@thienlnam I'll assign you here since you are investigating and have a fix. 🙇

**Comment by s77rt** [comment] 2024-11-24 13:26
Revert PR is merged. Let's close this one

**Closed** 2024-11-25 18:31 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted, Bug
