### ISSUE TITLE
 IOU - No billable toggle shown when editing money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28516] opened 2023-09-29 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27875
## Action Performed:
1. Open the app
2. Log in
3. Create a new money request
4. Open the money request details

## Expected Result:
The billable toggle is shown

## Actual Result:
The billable toggle is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/35ca346f-dfaf-4015-9aae-33b89bb3e22a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdel-h66** [comment] 2023-09-30 19:15
It looks normal, the billable field only appears when the request is inside a workspace.

**Comment by amyevans** [comment] 2023-09-30 22:13
> the billable field only appears when the request is inside a workspace

Exactly! Closing this out, not a bug.

**Closed by amyevans** 2023-09-30 22:13 UTC
Labels: Daily, Bug
