### ISSUE TITLE
LHN display wrong message when edit message to mention someone

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44747] opened 2024-07-02 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719934953730129

## Action Performed:
1. Send a random message
2. Edit this message to mention someone

## Expected Result:
LHN shows the mentioned person
## Actual Result:
LHN shows welcome message
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/11ae5418-f0ae-4299-9dd4-15754c58fa28

https://github.com/Expensify/App/assets/38435837/da4ff17a-bbf6-4c11-a476-244f2759fcfe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jacobkim9881** [comment] 2024-07-03 12:37
### W/O edit but only reference email address
<img width="707" alt="스크린샷 2024-07-03 오후 9 21 17" src="https://github.com/Expensify/App/assets/46774300/99cc793c-a9b7-47a3-a4d9-44d04c83a9ae">

It shows "@[user name]" on LHN.

### The reference email address with edit 
<img width="707" alt="스크린샷 2024-07-03 오후 9 21 50" src="https://github.com/Expensify/App/assets/46774300/539532e0-02c5-4a50-a3bc-7fa729b6013b">

API response get empty value for `text` key when editing message into email address.

**Comment by Tony-MK** [comment] 2024-07-03 15:00
This issue occurs because the backend does not return the mentioned user in the `lastMessageText` in the `updateComment` API response like below.

Therefore, this issue should be handled in the backend.

![Screenshot 2024-07-03 at 17 58 49](https://github.com/Expensify/App/assets/22982173/9e70804a-417f-4eb6-af04-d7f65090bbf2)

**Comment by joekaufmanexpensify** [comment] 2024-07-03 20:42
I can reproduce this. However, it only occurs until you navigate away and back to the chat. Once you do, the LHN updates to show the mention you edited the message to (seen at the end of my video). This feels like a pretty low impact bug to fix ATM, since it only happens if you send a regular message and edit it to add a mention, it fixes itself once you leave and go back to the chat, and we paused the #vip-vsb project (where this would be slotted in). 

https://github.com/Expensify/App/assets/54866469/3ec4ebc6-e233-4e3b-abc0-37f1ef0f11d3

**Comment by joekaufmanexpensify** [comment] 2024-07-03 20:43
I think we should close this for now, and reprioritize it if we get any actual feedback from customers on this. Doing that for now, but LMK if anyone disagrees.

**Closed by joekaufmanexpensify** 2024-07-03 20:43 UTC
Labels: Daily, Bug
