### ISSUE TITLE
Refreshing with an unsent comment in the composer caused the draft message to disappear

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36247] opened 2024-02-09 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707435302125309

## Action Performed:
1.Open a DM and draft a message
2.Refresh the page
## Expected Result:
Drafted message does not disappear
## Actual Result:
Drafted message disappear

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2024-02-12 01:32
Also unable to reproduce on Chrome staging v1.4.39-0.

I've set a notification for for `draft` in the #expensify-bugs channel

Leaving this open but setting it to weekly in the interim, both for me to test intermittently, and to check back for other reports.

**Comment by bfitzexpensify** [comment] 2024-02-21 06:23
Still unable to reproduce, and no other reports of this happening. Going to close this one out.

**Closed by bfitzexpensify** 2024-02-21 06:23 UTC
Labels: Weekly, Needs Reproduction, Overdue, Bug
