### ISSUE TITLE
[HOLD for payment 2024-10-24] [$125] Remove deprecated ReportActionUtils.getParentReportAction method

### ISSUE THREAD

**Issue by bondydaa** [Expensify/App#49551] opened 2024-09-20 18:42 UTC
Greater context in this issue https://github.com/Expensify/App/issues/27262

# Problem
We have marked this method as deprecate and need to remove it https://github.com/Expensify/App/blob/97b51ac79d1fce0f09cfde5081594d138c817603/src/libs/ReportActionsUtils.ts#L337-L347

# Solution
I'm not seeing any usages of this method so I think we can probably just remove it.

I do see these 2 instances of a similar methods but I believe those are just the local functions and not using the `ReportActionUtils` method.

https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/actions/Task.ts#L947
https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/actions/Task.ts#L919-L925

https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/pages/home/ReportScreen.tsx#L126
https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/pages/home/ReportScreen.tsx#L92-L97

If I missed something and we are using `ReportActionUtils.getParentReportAction` then we need to be sure to replace those with either `withOnyx()` or `Onyx.connect()`

cc @tgolen 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837202794110877572</li>
        <li>Upwork Job ID: 1837202794110877572</li>
        <li>Last Price Increase: 2024-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104251488</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by bondydaa** [comment] 2024-09-20 18:42
doh ignore for now! 🤦

**Comment by nkdengineer** [comment] 2024-09-20 18:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Remove deprecated ReportActionUtils.getParentReportAction method
### What is the root cause of that problem?


This is a new feature
### What changes do you think we should make in order to solve the problem?

Remove all use of `getParentReportAction` in `ReportActionUtils` and for all lib files that we create a `getParentReportAction` function, we should add a test in `EnforceActionExportRestrictions` to ensure that we don't export this function to use in any other file

### What alternative solutions did you explore? (Optional)
NA

**Comment by ChavdaSachin** [comment] 2024-09-20 20:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove deprecated ReportActionUtils.getParentReportAction method

### What is the root cause of that problem?
New request
- we are making use of this function on 2 files
- [ReportUtils.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/ReportUtils.ts)
- [[ReportUtils.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/ReportUtils.ts)

Additionally Implementation on [Task.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/actions/Task.ts) is exactly same as on[ReportActionsUtils.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/ReportActionsUtils.ts)
### What changes do you think we should make in order to solve the problem?
- Remove ReportActionUtils.getParentReportAction from all three files - [ReportUtils.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/ReportUtils.ts) ,[ReportUtils.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/ReportUtils.ts) & [ReportActionsUtils.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/ReportActionsUtils.ts) and provide functionality replacement using useOnyx or onyx.connect .
- Additionally remove `getParentReportAction` from [Task.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/actions/Task.ts) as well since it has exactly same implementation and hence it should be marked as deprecate and removed for whatever reason we marked `ReportActionUtils.getParentReportAction` as deprecated.
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by 1subodhpathak** [comment] 2024-09-21 18:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The ```getParentReportAction``` method in ```ReportActionsUtils.ts``` is deprecated and needs removal.

### What is the root cause of that problem?
The method is outdated due to improved `Onyx` state management practices.

### What changes do you think we should make in order to solve the problem?

1. Initially we need to delete the `getParentReportAction` function from `ReportActionsUtils.ts`
2. Then refactor `task.ts` to
    - update local `getParentReportAction` to use `Onyx.connect()` or `withOnyx()`.
    - modify `getTaskAssigneeAccountID` which includes `getParentReportAction` to use the refactored version.
     https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/libs/actions/Task.ts#L1108-L1119
3. We need to verify that the `getParentReportAction` function in `ReportScreen.tsx` does not rely on the deprecated method

### What alternative solutions did you explore? (Optional)
None considered necessary, as the deprecation notice already suggests using Onyx.connect() or withOnyx()

**Comment by mallenexpensify** [comment] 2024-09-23 22:11
d'oh, added `NewFeature` by mistake.  @bondydaa , do you need/want a C+ assigned here to review proposals and the PR? If not, please unassign before @getusha comments.  Thx

**Comment by bondydaa** [comment] 2024-09-23 22:21
oh i think it's fine to keep a c+, go for it @getusha

**Comment by getusha** [comment] 2024-09-24 08:34
@1subodhpathak could you provide a code snippet for this please?

>update local getParentReportAction to use Onyx.connect() or withOnyx()

I agree we should update task.ts since the function is the exact same as the one in ReportActionUtils

**Comment by nkdengineer** [comment] 2024-09-24 09:01
@getusha I think the only thing we need to do here is remove the unused `getParentReportAction` function in `ReportActionUtils`. For other `getParentReportAction` local functions in the lib file we need to make sure this is not exported by adding the test `EnforceActionExportRestrictions`. That is how we do for other functions like `getParentReport`, `getReport`.

**Comment by 1subodhpathak** [comment] 2024-09-24 09:16
> @1subodhpathak could you provide a code snippet for this please?
> 
> > update local getParentReportAction to use Onyx.connect() or withOnyx()
> 
> I agree we should update task.ts since the function is the exact same as the one in ReportActionUtils

Sure @getusha, 
Here's a code snippet 
```typescript
import { withOnyx } from 'react-native-onyx';
import ONYXKEYS from '@src/ONYXKEYS';

const getParentReportAction = withOnyx({
  parentReportActions: {
    key: ({ report }) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.parentReportID}`,
  },
})(({ parentReportActions, report }) => {
  if (!report?.parentReportID || !report.parentReportActionID) {
    return undefined;
  }
  return parentReportActions?.[report.parentReportActionID];
});
```
Here -
- I’m using `withOnyx()` to connect the `parentReportActions` to the Onyx data
- The function checks for both `parentReportID` and `parentReportActionID` and returns the appropriate `parentReportAction`.

**Comment by 1subodhpathak** [comment] 2024-09-25 16:12
@getusha what do you think?

**Comment by getusha** [comment] 2024-09-25 16:18
>@getusha I think the only thing we need to do here is remove the unused getParentReportAction function in ReportActionUtils. For other getParentReportAction local functions in the lib file we need to make sure this is not exported by adding the test EnforceActionExportRestrictions. That is how we do for other functions like getParentReport, getReport.

@nkdengineer the function is basically copy paste from ReportActionUtils, i think we should replace that if we can

**Comment by nkdengineer** [comment] 2024-09-25 16:25
@getusha The past problem is we used `getParentReportAction` of `ReportActionUtils` in the component and other lib files. We resolved it by creating the same local function in the lib file if we need to use it in many places of this lib file and using `Onyx.connect`. For component, we used `withOnyx/useOnyx` to resolve this problem. And for each local function created in the lib file we created, we add a test in `EnforceActionExportRestrictions` to make sure it isn't exported. That is how we do [here](https://github.com/Expensify/App/pull/43632)

**Comment by 1subodhpathak** [comment] 2024-09-25 16:41
Removing the unused `getParentReportAction` function from `ReportActionUtils` is should be a good move here. It will help declutter our codebase and remove deprecated code. I support adding the `EnforceActionExportRestrictions` test for the local `getParentReportAction` function in `task.ts`. This will ensure we're consistent with how we handle similar functions like `getParentReport` and `getReport`

**Comment by 1subodhpathak** [comment] 2024-09-25 18:29
@getusha what's your take on the code snippet I provided?

**Comment by ChavdaSachin** [comment] 2024-09-25 18:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove deprecated ReportActionUtils.getParentReportAction method

### What is the root cause of that problem?
New request
- ReportActionUtils.getParentReportAction function is used by 2 files
  1. [ReportUtils.ts](https://github.com/Expensify/App/blob/e5d410d4c15898db3479e4d7e686048176d5713e/src/libs/ReportUtils.ts)
  2. [Policy.ts](https://github.com/Expensify/App/blob/e5d410d4c15898db3479e4d7e686048176d5713e/src/types/onyx/Policy.ts)

### What changes do you think we should make in order to solve the problem?
- Remove `ReportActionUtils.getParentReportAction()` from - [ReportActionsUtils.ts](https://github.com/Expensify/App/blob/513e6b3c714adbe24cd8b88c9fc9c20130a6c9d4/src/libs/ReportActionsUtils.ts).
- On [ReportUtils.ts](https://github.com/Expensify/App/blob/e5d410d4c15898db3479e4d7e686048176d5713e/src/libs/ReportUtils.ts) we are already fetching `allReportActions` using `onyx.connect()` method similarly fetch `allReportActions` using `onyx.connect()` on [Policy.ts](https://github.com/Expensify/App/blob/e5d410d4c15898db3479e4d7e686048176d5713e/src/types/onyx/Policy.ts)
```js
let allReportActions: OnyxCollection<ReportActions>;
Onyx.connect({
    key: ONYXKEYS.COLLECTION.REPORT_ACTIONS,
    waitForCollectionCallback: true,
    callback: (actions) => {
        if (!actions) {
            return;
        }
        allReportActions = actions;
    },
});
```
- Create local  `getParentReportAction` function in [ReportUtils.ts](https://github.com/Expensify/App/blob/e5d410d4c15898db3479e4d7e686048176d5713e/src/libs/ReportUtils.ts) and [Policy.ts](https://github.com/Expensify/App/blob/e5d410d4c15898db3479e4d7e686048176d5713e/src/types/onyx/Policy.ts)
```js
function getParentReportAction(report: OnyxInputOrEntry<Report>): OnyxEntry<ReportAction> {
    if (!report?.parentReportID || !report.parentReportActionID) {
        return undefined;
    }
    return allReportActions?.[`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.parentReportID}`]?.[report.parentReportActionID];
}
``` 

> [!note]
> on [task.ts](https://github.com/Expensify/App/blob/e5d410d4c15898db3479e4d7e686048176d5713e/src/libs/actions/Task.ts) file we already have local implementation which uses `onyx.connect()` to fetch `allReportActions` and hence needs no improvement

- Add `EnforceActionExportRestrictions` test to for files `Task.ts`, `Policy.ts` and `ReportUtils.ts` to avoid exporting `getParentReportAction` from the same files in future. (as we do for the similar methods which make use of onyx.connect() - `Policy.getPolicy` , `ReportUtils.getPolicy`)
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mallenexpensify** [comment] 2024-09-27 23:54
@getusha 👀 on the above plz

**Comment by getusha** [comment] 2024-09-29 18:39
>The past problem is we used getParentReportAction of ReportActionUtils in the component and other lib files. We resolved it by creating the same local function in the lib file if we need to use it in many places of this lib file and using Onyx.connect. For component, we used withOnyx/useOnyx to resolve this problem. And for each local function created in the lib file we created, we add a test in EnforceActionExportRestrictions to make sure it isn't exported. That is how we do https://github.com/Expensify/App/pull/43632

@nkdengineer i am not sure i am following what you meant to say. are you suggesting to keep the function in `Task.ts`? if yes why?

**Comment by nkdengineer** [comment] 2024-09-30 05:23
> @nkdengineer are you suggesting to keep the function in Task.ts? 

@getusha  Yes

> if yes why?

Because we're using this locally in `Task.ts`. You can see the same pattern for `getReportOrDraftReport` function.

**Comment by 1subodhpathak** [comment] 2024-10-01 19:05
@getusha what do you think on my proposal?

**Comment by getusha** [comment] 2024-10-03 11:34
@nkdengineer is there any reason why we only want to deprecate the function in ReportActionUtils while keeping an exact same function in other files?

>Because we're using this locally in Task.ts

@bondydaa what do you think?

**Comment by nkdengineer** [comment] 2024-10-03 14:17
> is there any reason why we only want to deprecate the function in ReportActionUtils while keeping an exact same function in other files?

@getusha Because we don't use this function anywhere in `ReportActionUtils`.

**Comment by getusha** [comment] 2024-10-03 14:19
>@getusha Because we don't use this function anywhere in ReportActionUtils.

@nkdengineer there are several functions in `ReportActionUtils` that aren't being used in `ReportActionUtils`

**Comment by mallenexpensify** [comment] 2024-10-07 23:05
@getusha is the next step here for you to review the PR? 
- https://github.com/Expensify/App/pull/50211

**Comment by sonialiap** [comment] 2024-10-24 08:58
Payment summary:
- @getusha $125 please request in ND - please complete the [checklist](https://github.com/Expensify/App/issues/49551#issuecomment-2418324349)
- @nkdengineer $125 paid in upwork

**Comment by sonialiap** [comment] 2024-10-30 11:01
@getusha bumping for the [checklist](https://github.com/Expensify/App/issues/49551#issuecomment-2418324349)

**Closed** 2024-11-04 10:15 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 10:45
$125 approved for @getusha
