### ISSUE TITLE
[$500] Sign In -’Please enter authenticator code” is displayed instead “Magic code is incorrect”

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27293] opened 2023-09-12 20:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and enter new account for sign in
2. Navigate to the email inbox and open the validate email and copy the link
3. Modify the last portion of the link by a character, i.e. https://staging.new.expensify.com/v/7453760/12388**8**
4. Navigate to the compiled link

## Expected Result:
Verify you're redirected to the app and a "Magic code is incorrect" is displayed

## Actual Result:
’Please enter authenticator code” is displayed instead “Magic code is incorrect”

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68-15

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d805bb01-b4e8-45e6-81b0-0278d8967c68

![Bug6198062_wrong_link](https://github.com/Expensify/App/assets/78819774/8a1d7b52-ff42-41da-a4d2-e068e6c9c1f6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015251e56b7c77c761</li>
        <li>Upwork Job ID: 1702341556507480064</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-09-13 01:24
This looks like a backend issue. `SigninUserWithLink` API returns the following response
![image](https://github.com/Expensify/App/assets/126839717/3caf0dc0-e0d4-48e6-947b-028dec4c48fc)

**Comment by joekaufmanexpensify** [comment] 2023-09-14 15:19
Reproduced. Interestingly, we only seem to show the 2FA message if an `*` is used. However, if you change anything else about the deep link (add any other special characters, replace numbers with letters, etc.), we display a page that says the magic code is expired. 

However, after displaying the code expired page, if you use the actual code it still works. 

We should clean up all of these cases here, so that modifying the deeplink magic code correctly fails and notifies the user that they tried to use the wrong code.

**Comment by joekaufmanexpensify** [comment] 2023-09-14 15:20
Adding external for now, though curious if the C+ assigned could confirm whether this should be external/internal based on [this](https://github.com/Expensify/App/issues/27293#issuecomment-1716796358)?

**Comment by joekaufmanexpensify** [comment] 2023-09-17 08:25
Pending proposals.

**Comment by joekaufmanexpensify** [comment] 2023-09-18 08:06
Same

**Comment by jjcoffee** [comment] 2023-09-18 08:19
Yup, I can confirm what [this comment](https://github.com/Expensify/App/issues/27293#issuecomment-1716796358) says, this is definitely a BE issue!

**Comment by arosiclair** [comment] 2023-09-19 03:20
Our regex for validate links is this: `^/v/([0-9]+)/(\w+/?)$` which ignores any non-alphanumeric characters at the end of the link so that explains why adding asterisks at the end doesn't break anything. So `/123456*junk*` would work but `/123*junk*456` would not. 

TBH I'm not sure that this is a bad thing since the first part of the link _is_ correct. Also this behavior has existed for [at least 3 years](https://github.com/Expensify/Salt/commit/6151abe02fe48d2cc39d233c4a3fd96a74996c1a) so I think I'm leaning towards doing nothing for this. What do you think @joekaufmanexpensify?

**Comment by joekaufmanexpensify** [comment] 2023-09-19 04:21
Okay, got it. Good with me to do nothing!

**Comment by arosiclair** [comment] 2023-09-19 05:18
Cool closing this out

**Closed by arosiclair** 2023-09-19 05:18 UTC
Labels: Engineering, Daily, Internal, Bug
