### ISSUE TITLE
[PAID] [$250] Tags - The text content for the tag settings didn't update to "expenses"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42278] opened 2024-05-16 11:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/40950
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Enable tags in more features settings of that workspace
4. Navigate to tags > open settings RHP

## Expected Result:
The text content for "spend" should be updated to "expenses"

## Actual Result:
The text content for "spend" didn't update to "expenses"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6482453_1715844003873!image](https://github.com/Expensify/App/assets/115492554/c6705fa4-d56c-47c4-8152-d911356f21ac)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119b30dfee00c07e8</li>
        <li>Upwork Job ID: 1793038382904958976</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by izarutskaya** [comment] 2024-05-16 11:58
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment] 2024-05-17 09:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We are using wrong word

https://github.com/Expensify/App/blob/1faad15adcc79d796a8e065cc586615b755e8473/src/languages/en.ts#L2193



### What changes do you think we should make in order to solve the problem?
This bug only happen with English translation, we don't need to fix in Spanish translation

https://github.com/Expensify/App/blob/1faad15adcc79d796a8e065cc586615b755e8473/src/languages/en.ts#L2193

```
requiresTag: 'Members must tag all expenses', 
```

We also should to fix the same bug in here
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/docs/articles/new-expensify/workspaces/Require-tags-and-categories-for-expenses.md?plain=1#L17

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/docs/articles/new-expensify/workspaces/Require-tags-and-categories-for-expenses.md?plain=1#L27

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by strepanier03** [comment] 2024-05-21 21:57
Able to repro so I tied it to a project and set external.

**Comment by hayata-suenaga** [comment] 2024-05-22 23:45
> I don't think we should replace all occurrences of "spend" with "expenses".

I feel like we made a move to change all wording of `spend` to `expenses` throughout New Expensify, @trjExpensify?
Should we update the remaining texts, too?

**Comment by hayata-suenaga** [comment] 2024-05-22 23:46
I'll handle this PR as this is the regression from my App PR 🙇

**Comment by nkdengineer** [comment] 2024-05-23 14:27
@hayata-suenaga Feel free to glance at [my proposal](https://github.com/Expensify/App/issues/42278#issuecomment-2117108694) and fix other places

**Comment by trjExpensify** [comment] 2024-05-23 15:37
> > I don't think we should replace all occurrences of "spend" with "expenses".
> 
> I feel like we made a move to change all wording of `spend` to `expenses` throughout New Expensify, @trjExpensify? Should we update the remaining texts, too?

I think you're thinking of `Money` to `Expense` :)

**Comment by hayata-suenaga** [comment] 2024-05-23 17:49
@trjExpensify, thank you for the clarifications 😄 So should we change all occurrences of `spend` to `expenses`, or can they co-exist?

**Comment by trjExpensify** [comment] 2024-05-23 20:44
I don't think all of them. They can co-exist. For example, we call the entire feature section `Spend` for distance, workflows etc.

Let's just focus here on fixing the inconsistency between `Categories` and `Tags` in the workspace settings.

**Comment by hayata-suenaga** [comment] 2024-05-24 16:22
Just waiting for C+'s review

**Comment by strepanier03** [comment] 2024-06-11 22:12
### Payment Summary

- $250 @aimane-chnaif via Manual Request

@JmillsExpensify - Request incoming.

**Comment by strepanier03** [comment] 2024-06-19 02:51
Can close once payment is requested.

**Comment by strepanier03** [comment] 2024-06-20 20:45
@aimane-chnaif - Just checking in, did you request payment for this? Can I close this out yet?

**Comment by strepanier03** [comment] 2024-06-27 18:21
@aimane-chnaif - You requested via Upwork? My records show you're using Manual Requests, which is maybe what I think you meant right?

Reopen this if that's incorrect and you want me to make you an Upwork job.

**Comment by strepanier03** [comment] 2024-10-30 20:27
PAID!

**Closed** 2024-10-30 20:28 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
