### ISSUE TITLE
Login - Keyboard doesn't popup after going back to login screen on Android app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18525] opened 2023-05-06 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Input any email on Login screen
2. Tap Continue
3. Tap Go back
4. Tap email and try to change email

## Expected Result:
Keyboard pops up and user can change email

## Actual Result:
Keyboard doesn't pop up, email is not focused.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236636192-057056d4-50b1-462c-bb55-50cd41c42562.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2023-05-08 13:31
Ya it looks like the "Phone or email" field doesn't get auto-focused, which is probably why the keyboard doesn't open 🤔

**Comment by alex-mechler** [comment] 2023-05-08 15:59
Caused by https://github.com/Expensify/App/pull/17878, confirmed by reverting locally

**Comment by roryabraham** [comment] 2023-05-08 23:59
Verified that this was fixed in `1.3.11-4`, which as of now has finished deploying on all platforms except iOS.

https://user-images.githubusercontent.com/47436092/236961389-2a2425b3-f56a-41eb-8ab3-538ed3dcec8d.mp4

**Closed by roryabraham** 2023-05-08 23:59 UTC
Labels: DeployBlockerCash, Engineering, Hourly
