### ISSUE TITLE
Category - When categories are disabled, 'It's not here' page is seen when unselecting category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29565] opened 2023-10-13 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-10

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat > + > Request money > Manual
3. Create an expense with a category
4. On OD as admin, disable all the categorie
5. As the employee who created the expense in Step 2, go to the expense details page
6. Click on Category > Unselect the category

## Expected Result:
'It's not here' page will not appear

## Actual Result:
As the RHP slides away, 'it's not here' page is seen in RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/235e3c5e-3371-4a91-b70c-910eedf1c4c3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:23
Not overdue. Will triage today.

**Comment by joekaufmanexpensify** [comment] 2023-10-17 15:35
I can reproduce this: 


https://github.com/Expensify/App/assets/54866469/95c05122-9a1f-43e6-abbb-99cf518844d4

**Comment by amyevans** [comment] 2023-10-17 17:14
It's a little funky looking. I'd vote we have someone from the Callstack Wave 6 team take a look when they've got a spare moment. But I don't feel passionately about addressing it either.

**Comment by joekaufmanexpensify** [comment] 2023-10-17 17:39
Yeah, the more I think about this, I'm falling in the do nothing camp. It's a significant edge case that someone will be turning categories on/off entirely, and then removing categories from existing requests anyway. 

Since this doesn't impact the user experience at all, I'm thinking we can just wait and see if any actual customers report this when it's being used (which I feel like they probably won't, because if you aren't looking for it, it isn't really noticeable.)

**Comment by joekaufmanexpensify** [comment] 2023-10-17 17:40
Going to close this for now. If anyone feels strongly we should change this, happy to re-open and can get callstack on it!

**Closed by joekaufmanexpensify** 2023-10-17 17:40 UTC
Labels: Daily, Bug
