### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] A visual indicator like a tooltip should be present for currency selector reported by @daraksha-dk

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12555] opened 2022-11-08 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
User doesn't know if he can also change the currency here by clicking on the symbol

## Solution:
A visual indicator like a tooltip should be present for currency selector like we have for almost every action on the app except for this one.

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/43996225/200611500-e41910e7-0721-43b8-a366-1d62b8bfc440.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666716588685909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d2593b6d75e5a34</li>
        <li>Upwork Job ID: 1600875211272773632</li>
    </ul>
</details>

**Comment by daraksha-dk** [comment] 2022-11-10 15:05
@kavimuru I think you forgot to add `AutoAssignerTriage` tag here.

Got the approval here: https://expensify.slack.com/archives/C01GTK53T8Q/p1668006728010219?thread_ts=1666716588.685909&cid=C01GTK53T8Q

**Comment by marcaaron** [comment] 2022-12-07 20:38
Hmm actually - I think this would be good to fix. It does feel like a bug kind of because the currency selector is pretty hard to discover and the change is very low in complexity.

**Comment by bfitzexpensify** [comment] 2022-12-08 15:29
I agree @marcaaron 

### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [x] The "bug" is actually a bug - yes, given 
- [x] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [x] The bug is reproducible, following the reproduction steps.
- [x] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [x] The GH was created by an Expensify employee or a QA tester 
- [x] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by dangrous** [comment] 2022-12-08 16:45
Going to cc @shawnborton on this to see if we have a good design idea for this that we then can figure out how to implement!

**Comment by marcaaron** [comment] 2022-12-08 18:11
personally, I think just solving the tooltip issue is enough for this ticket. if we are discussing different designs then that's not a "bug".

**Comment by daraksha-dk** [comment] 2022-12-08 18:55
I have added a [proposal](https://github.com/Expensify/App/issues/12555#issuecomment-1307517920). Please review.

**Comment by shawnborton** [comment] 2022-12-08 19:32
I agree, let's just add a tooltip and not change the actual design of this.

**Comment by mananjadhav** [comment] 2022-12-09 02:29
Looks like we are okay with Tooltip as a solution. @daraksha-dk's proposal [here](https://github.com/Expensify/App/issues/12555#issuecomment-1307517920) looks fine. I am not sure if the text should be `currency` or `Change currency`.

@shawnborton  @dangrous  ?

**Comment by jatinsonijs** [comment] 2022-12-09 12:52
I think Tooltip is just for web. same concern is also apply on another platforms. And current tooltip still depends on user actions (User have to move cursor above the symbol to know they can change currency by that symbol).

**Comment by MitchExpensify** [comment] 2022-12-09 15:13
@dangrous  this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:

- Decide whether any proposals currently meet our guidelines and can be approved as-is
- For any that can't, please take this issue internal and treat it as one of your highest priorities
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by dangrous** [comment] 2022-12-09 15:48
Since this is sort of a cross between a bug and a feature request, I think we're okay with moving forward with @daraksha-dk's solution for web, and we can circle back around to mobile as a future development. I'll assign you now!

**Comment by daraksha-dk** [comment] 2022-12-09 16:52
PR is ready. I have added the `Moneda` as translation of `currency`. I referenced it from the line below. Please verify if it's correct.
https://github.com/Expensify/App/blob/5ab92f54240381b7e2ebe78af0129d429c4d6b95/src/languages/es.js#L148

**Comment by shawnborton** [comment] 2022-12-09 17:01
Do we want the tooltip to say “Change currency”? Not sure what the Spanish
translation is for that, maybe “Cambiar la moneda” but let’s get
confirmation on that first

**Comment by dangrous** [comment] 2022-12-09 17:23
Do we just want to use the same `selectCurrency` line? Since it's already translated? I feel like that has the same meaning as `Change currency`

**Comment by shawnborton** [comment] 2022-12-09 19:04
Great idea!

**Comment by dangrous** [comment] 2022-12-13 23:10
@mananjadhav This wasn't exactly a bug, and certainly not a regression, is that right? The tooltip never existed? If not I guess we can link to the original PR that created the functionality and did not add the tool tip...

**Comment by mananjadhav** [comment] 2022-12-15 17:07
> This wasn't exactly a bug, and certainly not a regression, is that right? The tooltip never existed?

That's right.  I think this [PR](https://github.com/Expensify/App/pull/8299) added the component but I am guessing the dropdown existed even before creating the component

**Comment by dangrous** [comment] 2022-12-15 17:42
Okay, linked in the checklist and added in a comment! I'm making an executive decision that we don't need a discussion in #expensify-bugs for this because it wasn't a bug, just a miss on the initial conception of the feature. It'll be good in the future to make sure users have an easy way of finding out about "hidden" features like this but I don't think that would be an effective conversation to have in the bugs channel, more something that should already be thought about.

@bfitzexpensify I think maybe we make a regression test to just check if the tooltip is there on web and desktop? And then we can close out.

**Comment by mananjadhav** [comment] 2022-12-21 13:09
@bfitzexpensify this should be eligible for the timeline bonus.

**Comment by bfitzexpensify** [comment] 2022-12-21 13:28
Yup! All upwork contracts paid and ended. Regression test suggested update posted [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1671628821239989). Once that's done I'll get that wrapped up and close this out.

**Comment by bfitzexpensify** [comment] 2022-12-28 05:45
OK, regression test updated. We're all done here.

**Closed by bfitzexpensify** 2022-12-28 05:45 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
