### ISSUE TITLE
[Awaiting C+ newdot payment] [$1000] DEV: image does not show in full view on Staging Server

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26075] opened 2023-08-28 12:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Preferences
2. turn on Use Staging Server
3. go to any chat and send any image
4. click on that image
## Expected Result: 
image should show
## Actual Result: 
Hmm... it's not here appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/13c26dfb-dd9e-4f5a-95b4-530221cc883b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692347578989049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f141e51646e3dfd</li>
        <li>Upwork Job ID: 1696779203867475968</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26425917</li>
<li>gadhiyamanan | Reporter | 26425920</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-08-29 09:01
I'm getting this on sign-in:

![image](https://github.com/Expensify/App/assets/59587260/53dc253d-76a1-4513-8330-3b2e32c35396)

Will need to look into my dev machine tomorrow to repro this properly.

**Comment by kadiealexander** [comment] 2023-08-30 06:57
Reproduced:

https://github.com/Expensify/App/assets/59587260/ea11e26b-1fe7-4791-85dc-382c65a8ae1f

**Comment by pradeepmdk** [comment] 2023-08-30 07:27
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
image does not show in full view on Staging Server

### What is the root cause of that problem?

when staging server enabled basebath is append with `/staging/staging/chat-attachments/6539852094807903528/w_8b5e53ab84b08131c2eede50f1cea6bd6b0b0937.jpg`
https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/libs/tryResolveUrlFromApiRoot.js#L22

here we are checking with equal statment so that its failling https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/components/Attachments/AttachmentCarousel/index.js#L44

### What changes do you think we should make in order to solve the problem?

we need change the condition into 
```
 const initialPage = _.findIndex(attachmentsFromReport, (a) => source.endsWith(a.source));
``` 
Result 
<img width="1436" alt="Screenshot 2023-08-30 at 12 57 13 PM" src="https://github.com/Expensify/App/assets/16595846/c9b36079-fab7-40f6-badd-b0f39e36012e">

**Comment by mountiny** [comment] 2023-08-31 07:12
@tienifr @0xmiroslav this works well in Staging so lets make sure we fix this so we dont break staging

**Comment by mountiny** [comment] 2023-09-25 14:18
I think the automation failed here @kadiealexander can you please pay $1000 to @0xmiroslav and $1000 to @tienifr  and $250 to @gadhiyamanan thanks!

**Comment by kadiealexander** [comment] 2023-09-26 05:25
Payouts due:

Issue Reporter: $250 to @gadhiyamanan
Contributor: $1000 to @tienifr
Contributor+: $1000 to @0xmiroslav

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~015f141e51646e3dfd).

**Comment by kadiealexander** [comment] 2023-09-26 05:28
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@0xmiroslav] The PR that introduced the bug has been identified. Link to the PR: 
- [x] [@0xmiroslav] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [x] [@0xmiroslav] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [x] [@0xmiroslav] Determine if we should create a regression test for this bug.
- [x] [@0xmiroslav] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [x] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by gadhiyamanan** [comment] 2023-09-26 05:29
@kadiealexander this is eligible for $250 because it was reported before 30 August 
cc: @mountiny

**Comment by kadiealexander** [comment] 2023-09-26 05:32
Sorry @gadhiyamanan, these edge cases are funny. I sent a bonus to make the total $250 for you.

**Comment by kadiealexander** [comment] 2023-09-28 21:07
Adjusted to add the bonus.

**Comment by mountiny** [comment] 2023-10-04 11:46
@0xmiroslav as seen in another issues, if your payment is the last pending task here, can we close this isse?

**Comment by mountiny** [comment] 2023-10-04 11:46
I will go ahead and close it, let me know if that needs to be otherwise

**Closed by mountiny** 2023-10-04 11:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
