### ISSUE TITLE
Contact methods - Offline indicator is below Verify button and not bottom of the page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48447] opened 2024-09-03 09:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://github.com/Expensify/App/pull/48320
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings.
3. Go to Profile > Contact methods.
4. Tap New contact method.
5. Enter a new contact method > Next.
6. Go offline.

## Expected Result:
Offline indicator will be at the bottom of the page (above keyboard if keyboard is up).

## Actual Result:
Offline indicator is below Verify button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ca47d3bf-c20a-4ddd-94f8-64495a5ab505

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by etCoderDysto** [comment] 2024-09-03 09:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Contact methods - Offline indicator is below Verify button and not bottom of the page
### What is the root cause of that problem?
We are not passing margin top auto below
https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/pages/settings/Profile/Contacts/ValidateContactActionPage.tsx#L41-L44

### What changes do you think we should make in order to solve the problem?
We should pass margin top auto 
`offlineIndicatorStyle={themeStyles.mtAuto}` 

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-09-03 09:16
## Proposal
Offending PR: https://github.com/Expensify/App/pull/48320
### Please re-state the problem that we are trying to solve in this issue.
Contact methods - Offline indicator is below Verify button and not bottom of the page
### What is the root cause of that problem?
We are not passing margin top auto to `offlineIndicatorStyle`  below
https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/pages/settings/Profile/Contacts/ValidateContactActionPage.tsx#L41-L44

### What changes do you think we should make in order to solve the problem?
We should pass margin top auto 
`offlineIndicatorStyle={themeStyles.mtAuto}` 

### What alternative solutions did you explore? (Optional)

**Comment by MariaHCD** [comment] 2024-09-03 10:51
@getusha @hungvu193 This would also be another follow up improvement from https://github.com/Expensify/App/pull/48320

**Comment by hungvu193** [comment] 2024-09-03 10:53
> @getusha @hungvu193 This would also be another follow up improvement from https://github.com/Expensify/App/pull/48320

Ah yes. Thanks for letting me know, we will tackle this one as well 👍

**Comment by mountiny** [comment] 2024-09-03 12:39
I don't think this has to be a blocker, but @getusha what is your ETA for this PR, it should be a quick one

**Comment by alexpensify** [comment] 2024-09-03 23:13
@mountiny - should we make this eternal and then assign @getusha?

**Comment by mountiny** [comment] 2024-09-04 15:57
I think this was already handled and the payments will be handled on the original issue. So we can close this

**Closed by mountiny** 2024-09-04 15:57 UTC
Labels: Reviewing, Engineering, Weekly, Bug
