### ISSUE TITLE
[$1000] Web - Edit and delete button are not available for normal message in mac after changing default contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21948] opened 2023-06-30 12:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should have more then 1 contact method verified
1. Open the app
2. Open any report
3. Send few messages
4. Change default contact method
5. Revisit report opened in step 2 and hover on latest sent messages (sent in step 3)

## Expected Result:
App should display edit and delete for normal messages

## Actual Result:
pp does not display edit and delete for normal messages after changing default contact method

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari ONLY
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c6a6a77d-3bb7-4cb8-bdab-70441e1bae98

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688029345913139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e71cf3db941fc35</li>
        <li>Upwork Job ID: 1675215183989825536</li>
        <li>Last Price Increase: 2023-07-08</li>
    </ul>
</details>

**Comment by lazar-stamenkovic** [comment] 2023-07-02 19:06
Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web - Edit and delete button are not available for normal message in mac after changing default contact

### What is the root cause of that problem?
After changing contact method, the reportAction is not updated with latest contact method email, so the condition inside canDeleteReportAction will be false:

 if (reportAction.actorEmail === sessionEmail) {
        return true;
    }
### What changes do you think we should make in order to solve the problem?
canDeleteReportAction function has to compare account id instead of email checking current user's message.
![image](https://github.com/Expensify/App/assets/114150992/9e492fdf-4c68-4ae3-a60e-150a8a77b861)


What alternative solutions did you explore? (Optional)
N/A

**Comment by lazar-stamenkovic** [comment] 2023-07-03 08:54
> While changing to accountID is simpler, bug reporters' offline shenanigans after logging in like, login, disable network and change default contact and then try to edit kinda actions might be better addressed with Onyx loginlist.

Comparing account IDs holds significance as they serve the purpose of identifying users and acting as primary keys. 
It's good to avoid adding specific code blocks solely to address edge cases.
Ideally, it is preferable to handle edge cases within the main logic of the codebase, if feasible.

**Comment by lazar-stamenkovic** [comment] 2023-07-03 20:56
@mollfpr, @MitchExpensify please take a look my proposal. 
https://github.com/Expensify/App/issues/21948#issuecomment-1616776147

**Comment by MitchExpensify** [comment] 2023-07-03 22:49
Not overdue, Melvin

**Comment by mollfpr** [comment] 2023-07-07 14:14
Reviewing proposal!

**Comment by mollfpr** [comment] 2023-07-10 15:12
This issue is not reproducible. Is fixed in the accountID migration PR https://github.com/Expensify/App/pull/22327

**Comment by MitchExpensify** [comment] 2023-07-10 22:04
@mollfpr thanks, sounds like reporting payment is all thats due here - agreed?

**Comment by mollfpr** [comment] 2023-07-11 06:38
@MitchExpensify Agree!

**Comment by MitchExpensify** [comment] 2023-07-11 23:11
Awesome, invite sent here for reporting payment @dhanashree-sawant 👍  https://www.upwork.com/jobs/~016e71cf3db941fc35

**Comment by dhanashree-sawant** [comment] 2023-07-12 05:01
@MitchExpensify, Thanks! 
Offer accepted.

**Comment by MitchExpensify** [comment] 2023-07-12 22:06
Awesome, paid!

**Closed by MitchExpensify** 2023-07-12 22:06 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
