### ISSUE TITLE
[HOLD for payment 2023-10-23]

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#27691] opened 2023-09-18 15:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to DM chat
2. Click + and then "Request Money"
3. Use "Scan" option and try to take a picture

## Expected Result:
After giving permissions to the app, the camera should appear

## Actual Result:
After giving permissions to the app, a loading spinner stays there forever

![image](https://github.com/Expensify/App/assets/87341702/cdfad0e3-48a5-4845-bc2b-48a0ebb50675)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native - Specifically a Xiaomi A3 device
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**
- https://expensify.slack.com/archives/C057F53HR40/p1693966434834629?thread_ts=1693598703.818309&cid=C057F53HR40
- https://expensify.slack.com/archives/C035J5C9FAP/p1693955621069789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d479b9dfa637bcca</li>
        <li>Upwork Job ID: 1704032011382767616</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2023-09-18 15:50
Solution:

Marc fixed this here: https://github.com/mrousavy/react-native-vision-camera/pull/1782

We need to update `react-native-vision-camera` to get the fix

**Comment by MitchExpensify** [comment] 2023-09-18 22:08
Is the idea to label this external still @aldo-expensify ? I do not have access to a Xiaomi so I'm tempted to go straight to that step 😅

**Comment by AndrewGable** [comment] 2023-09-19 07:17
This was released in `2.16.1` - I can update it

**Comment by MitchExpensify** [comment] 2023-10-19 00:52
Reminder set to pay! Bump on BZ steps @ntdiary

**Comment by MitchExpensify** [comment] 2023-10-28 21:38
So we should hold on payment if this is still happening, right @ntdiary ?

**Comment by lanitochka17** [comment] 2023-11-15 14:59
Issue still reproducible with latest build 1.3.99-0
Samsung Galaxy Z Fold 4 / Android 13

https://github.com/Expensify/App/assets/78819774/d5b7429a-8ad4-47c5-b4f7-db6c0cc4596b

**Comment by AndrewGable** [comment] 2023-11-15 20:01
What's the latest here?

**Comment by MitchExpensify** [comment] 2023-11-16 02:09
I am unsure honestly, @AndrewGable - We need a proposal to fix it because our original fix here didn't do that, right?

**Comment by MitchExpensify** [comment] 2023-11-26 03:28
Friendly bump, @AndrewGable

**Comment by MitchExpensify** [comment] 2023-11-28 19:23
And just to be clear we'd wait on https://github.com/Expensify/App/issues/30732. in the hope that it resolves this issue?

**Comment by AndrewGable** [comment] 2023-12-07 19:12
Yes, correct

**Comment by MitchExpensify** [comment] 2023-12-18 17:34
On hold, not overdue

**Comment by MitchExpensify** [comment] 2024-01-01 00:38
On hold for https://github.com/Expensify/App/issues/30732

**Comment by MitchExpensify** [comment] 2024-01-09 16:47
Hold for https://github.com/Expensify/App/issues/30732 which found a home on a wave so progress will continue

**Comment by MitchExpensify** [comment] 2024-01-17 22:19
Hold for https://github.com/Expensify/App/issues/30732

**Comment by MitchExpensify** [comment] 2024-01-31 01:33
Hold for https://github.com/Expensify/App/issues/30732

**Comment by MitchExpensify** [comment] 2024-02-13 20:42
Hold for https://github.com/Expensify/App/issues/30732

**Comment by MitchExpensify** [comment] 2024-02-23 21:10
Hold for https://github.com/Expensify/App/issues/30732

**Comment by MitchExpensify** [comment] 2024-02-23 21:11
Hold for https://github.com/Expensify/App/issues/30732

**Comment by MitchExpensify** [comment] 2024-04-08 02:25
Hold for https://github.com/Expensify/App/issues/30732

**Closed** 2024-06-04 21:33 UTC
Labels: Reviewing, Monthly, Internal, Awaiting Payment, Bug
