### ISSUE TITLE
[$250] #admins room of newly created collect workspace incorrectly shows that a user changed the auto-reporting frequency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44580] opened 2024-06-27 23:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719530451877409

## Action Performed:

1. Sign up on OldDot
2. Select "Business" in the welcome task
3. When the message from a guide opens in the right hand pane, select Chat with me
4. Land in #admins room

## Expected Result:
There should be no system message about changing reporting frequency
## Actual Result:
There is a system message that suggests the user changed their reporting frequency to Instant, which is not true

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (36)](https://github.com/Expensify/App/assets/38435837/d024ab00-de90-43e1-bef8-0962bb840715)
![Snip - (1) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/697d58c6-11f4-40fb-b92c-f55aaa2c83a7)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc53212e31364513</li>
        <li>Upwork Job ID: 1808511838338732989</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by Beamanator** [comment] 2024-07-01 05:49
Note: This may somehow relate to https://github.com/Expensify/Web-Expensify/pull/42326, where I tried to fix a case where answering "Business" in the welcome task (in OldDot) was updating policy settings that it shouldn't be updating...

I didn't notice the #admins room changelog

**Comment by kevinksullivan** [comment] 2024-07-03 14:43
I posted this one initially and can confirm it's reproducible each time.

**Comment by diegohosilver** [comment] 2024-07-03 22:12
I was able to reproduce it. At first glance looks like a backend issue, because `Inbox_Task_Complete` response states that the auto reporting frequency of the policy has been set to `instant`.

![Screenshot 2024-07-03 at 6 23 45 PM](https://github.com/Expensify/App/assets/20136219/43fbd7f0-c094-4628-9b91-d94ee1789ce4)

**Comment by trjExpensify** [comment] 2024-08-08 20:25
We don't create the #admins room on workspace creation anymore. I can also see it's not here when I generate the #admins room. 

https://github.com/user-attachments/assets/0dd8e6c0-fd4c-402c-968d-c59e4622d617

![Image](https://github.com/user-attachments/assets/4de52624-9c9a-4f51-818e-3b538141b8c5)


Closing!

**Closed by trjExpensify** 2024-08-08 20:25 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
