### ISSUE TITLE
[Distance] - Inappropriate error message when change Stops order on No route found page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30738] opened 2023-11-01 22:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.94-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to Global Create > Request Money
3. Select Distance option
4. Enter a start location in San Diego, California and a finish location in Honolulu, Hawaii
5. Error message is displayed below the map saying there is no such a route
6. Add new stop location
7. Change the order by dragging the newly added stop to the finish point

## Expected Result:
"No route found through the waypoints. Please edit the waypoints and try again" message should remain

## Actual Result:
"Route exceeds maximum distance limitation" error message appears when change stops order after "No route found through the waypoints. Please edit the waypoints and try again" message is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/079dfe3f-c88e-467b-badd-0e9c41b6cbae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01525f00e143bfc704</li>
        <li>Upwork Job ID: 1719839903683686400</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by mrd5591** [comment] 2023-11-01 22:25
I don't believe this is a real bug since swapping the "Stop" and "Finish" locations in the demo also dramatically changes the distance calculation, so this appears to be working as intended. On the other hand, if this error message should _never_ be shown to an end user, a backend change is required to change out the error message returned to the client.

**Comment by samilabud** [comment] 2023-11-01 23:02
Confirming to change this a backend change is needed because this response depends on the API:

https://github.com/Expensify/App/assets/5216036/e3c2691f-c313-460e-b637-59b61c818fb8

**Comment by s-alves10** [comment] 2023-11-01 23:03
Yeah. This is obviously a backend issue

**Comment by NisargDeveloper** [comment] 2023-11-02 11:06
Yes its an backend issue. I can help you solve it.

Contributor details
Your Expensify account email: nisarg.k.amin@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01149c9659573bccce

**Comment by sophiepintoraetz** [comment] 2023-11-07 00:40
@Ollyws - mind confirming that this is an internal issue? I believe the contributors, just want to make sure this has had the C+ on it too.

**Comment by grgia** [comment] 2023-11-10 09:23
[Bringing this one to slack](https://expensify.slack.com/archives/C05DWUDHVK7/p1699608138631069)

**Comment by grgia** [comment] 2023-11-13 15:01
bumped in slack

**Comment by neil-marcellini** [comment] 2023-11-13 22:12
Ok I tested this myself and looked at the backend code. First of all the reproduction steps aren't quite right. You need to use the exact waypoints provided in the video. Mapbox returns `InvalidInput` as the error code with the message shown. I don't know why it does that exactly, but that's how it works.

A simple solution is to return the same error message in both cases. However, then we lose that helpful error message about exceeding the max distance. For example that happens when the start is Anchorage, Alaska and the finish is Santiago, Chile.

Therefore I think this is Mapbox's problem, and we'll have to deal with it. I really doubt real users will care, they just need to see that it isn't possible. Let's close this out since it's not a real problem.

**Closed by neil-marcellini** 2023-11-13 22:12 UTC
Labels: Engineering, Daily, Internal, Bug
