### ISSUE TITLE
[$250] mWeb - Expense - Second WS member can´t access report and receipt of distance split expenses

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51022] opened 2024-10-17 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5092497&group_by=cases:section_id&group_order=asc&group_id=229067
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Open a workspace chat with at least two members
3. Tap on the "+" button
4. Tap on "Split Expense" and go to distance option
5. Add start and stop waypoints
6. Submit the expense
7. Verify the user can open the expense report and receipt
8. Log out from the account
9. Log in with the account of the second workspace member
10. Open the workspace chat
11. Verify the second member can access the expense report and receipt

## Expected Result:
Second expense participant, should be able to open the expense report and the receipt from the workspace chat

## Actual Result:
When the second participant, opens the distance expense receipt, a "403 Forbidden" message is displayed, and when the report is opened, a "Hmmm, it´s not here" screen is displayed. Second Participant is not able to access the distance split expense information

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/18c87262-7101-4ec2-a7de-063a320f5d38

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848259328541792445</li>
        <li>Upwork Job ID: 1848259328541792445</li>
        <li>Last Price Increase: 2024-10-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @deetergp</details>

**Comment by lanitochka17** [comment] 2024-10-17 14:10
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-17 14:11
We think that this bug might be related to #wave-collect - Release 1

**Comment by VickyStash** [comment] 2024-10-21 09:37
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-10-21 13:39
I was able to reproduce the issue, but it looks like an API problem. The app just displays what API returns.

So for the **User A** - the owner of the workspace and the creator of the split expense - the expense report is returned for `OpenApp` / `OpenReport` API command.

For **User B**  - the member of the workspace - the expense report is not returned by the API inside `OpenReport` data. `OpenReport` call returns `Report not found` error.

❗**NOTE** : the issue is fixed if I turn **User B** into `Admin` of the workspace.

| API calls   | User A (the one who created the split expense) | User B (second member of the workspace) |
| ------------- | ------------- | ------------- |
| OpenApp | <img width="1499" alt="2" src="https://github.com/user-attachments/assets/4cdaa48d-5b04-4fb0-915f-7983b01f53c3"> | <img width="1515" alt="01" src="https://github.com/user-attachments/assets/a1001fa1-17c0-4b95-984f-8003ecf938ff">  |
| OpenReport | <img width="1496" alt="3" src="https://github.com/user-attachments/assets/87162e8c-8d7c-4a0a-b664-b63d7b8f6925">  | <img width="1500" alt="02" src="https://github.com/user-attachments/assets/471972d2-92c8-4206-a163-797f048b7e98">  |
| Receipt display | ![image](https://github.com/user-attachments/assets/7a0f44b6-8b05-43e8-9eee-e4932dc68f96) | <img width="1500" alt="04" src="https://github.com/user-attachments/assets/717fa8b7-1fde-4cfc-9401-f2d5e29fa49a">  |

**Comment by VickyStash** [comment] 2024-10-23 14:39
@ikevin127 What do you think about [this](https://github.com/Expensify/App/issues/51022#issuecomment-2426716737)?

**Comment by ikevin127** [comment] 2024-10-23 20:29
@VickyStash Thanks for the detailed explanation! Your analysis indicates that this is BE related indeed, so I'm going to auto-assign a CME to look into it and confirm whether this should be `Internal`.

🎀👀🎀 C+ reviewed

**Comment by kadiealexander** [comment] 2024-10-25 06:39
Reassigning to someone else to babysit this while I'm OOO for the next two weeks.

**Comment by deetergp** [comment] 2024-10-26 00:13
I am not able to recreate this. I've tried splitting distance expenses both in and out of workspace chats and in each case, I am able to see both the expenses and the receipts as either user.

**Comment by joekaufmanexpensify** [comment] 2024-10-28 16:26
I can try and triage today too.

**Comment by ikevin127** [comment] 2024-10-28 19:42
> I can try and triage today too.

**Comment by deetergp** [comment] 2024-10-29 00:44
Oh, is it specific to Android mobile web? I am pretty sure I tried it in macOS web. I'm heading OOO for the next week—back on the 5th—if we need to keep the press going on this, you may want to find another internal engineer.

**Comment by joekaufmanexpensify** [comment] 2024-10-29 13:21
I tested on android mobile web because that was in OP of the issue. This is a pretty niche case, so I don't think it's really a rush to fix it, so I think fine to leave it a week. We could also just close, but it does feel like this could come up eventually, so maybe best to fix if it's an easy PR.

**Comment by joekaufmanexpensify** [comment] 2024-10-29 13:22
I'll just set to weekly for now, and we can pick this back up next week

**Comment by joekaufmanexpensify** [comment] 2024-11-04 16:00
We'll pick this back up this week once Scott's back

**Comment by deetergp** [comment] 2024-11-06 18:23
Hey gang, I'm back from OOO and will try to get to this today.

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:24
Sounds great. Thanks Scott!

**Comment by VickyStash** [comment] 2024-11-15 15:05
@deetergp Have you had a chance to take a look at this one?

**Comment by deetergp** [comment] 2024-11-16 00:19
@VickyStash I was not able to recreate it. Can anyone else?

**Comment by VickyStash** [comment] 2024-11-18 17:02
I can't reproduce it anymore as well! @lanitochka17 could you please check if it's reproducible for you?

**Comment by joekaufmanexpensify** [comment] 2024-11-18 17:21
Going to close this one out for now, as seems like it's no longer reproducible. @lanitochka17 please let us know if you can still reproduce it and we'll take another look!

**Closed by joekaufmanexpensify** 2024-11-18 17:21 UTC
Labels: Weekly, Internal, Bug

**Comment by lanitochka17** [comment] 2024-11-19 14:16
Now, the error message is not displayed anymore, but when tester opens the report on the second member account, the "Distance" and "Rate" fields are displayed as "Pending" and doesn't load


https://github.com/user-attachments/assets/df0e5df8-ae89-4077-b493-b7b906e36974

**Comment by joekaufmanexpensify** [comment] 2024-11-19 15:23
I just tested this and I have no issue accessing the report from the second user account. 

<img width="341" alt="image" src="https://github.com/user-attachments/assets/587bc44a-438b-48de-aa2d-c9181ed27b72">
