### ISSUE TITLE
[$1000] Dev -Android - Console error on app launch

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12724] opened 2022-11-14 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Actions Performed

1. Launch android app.

## Expected Result: 
No console errors

## Actual Result:  
Console error ERROR  Warning: Failed prop type: Invalid prop `reportActions.reportActions_5887980400113306` of type `array` supplied to `SidebarLinks`, expected `object` at SidebarLinks

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.25-0
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201759361-ff220684-d741-471f-906f-22b04233abb1.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667959713740999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01b384c685e3f60dd2
- Upwork Job ID: 1594686468145885184

**Comment by isabelastisser** [comment] 2022-11-17 14:25
OOO, reassigning.

**Comment by lschurr** [comment] 2022-11-17 16:18
I don't have access to the dev console. Tagging Eng for reproduction.

**Comment by flodnv** [comment] 2022-11-21 13:37
Reproduced on web, confirmed the fix 👍 @lschurr please hire @0xmiroslav 

@tgolen it was introduced here: https://github.com/Expensify/App/pull/10784/files#diff-dd7de4cc8cf99cd14ad8b5168c24c75a12d25aca423502eaaaccedd71c31cb1cR55 

I imagine it was just an oversight? 🤔

**Comment by flodnv** [comment] 2022-11-21 15:34
@rushatgabhane what are your thoughts here, do you agree we can proceed?

**Comment by lschurr** [comment] 2022-11-21 15:57
@0xmiroslav - could you please apply for the job in Upwork? https://www.upwork.com/jobs/~01b384c685e3f60dd2

**Comment by aneequeahmad** [comment] 2022-11-22 21:29
I posted the **Proposal** with the bug report [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668231329934119?thread_ts=1667959713.740999&cid=C01GTK53T8Q). Is there any chance someone has looked at it ? 

cc: @flodnv, @rushatgabhane

**Comment by flodnv** [comment] 2022-11-23 10:33
Sorry @aneequeahmad, AFAIK proposals should be done on Github. LMK if I'm wrong.

**Comment by aneequeahmad** [comment] 2022-11-23 11:22
@flodnv Yeah you're right, proposals should be done on Github when the Job is posted. 

What i understood from the [contribution.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) is that` propose a job, and (optionally) a solution for that job`and is written [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=It%E2%80%99s%20possible%20that,an%20external%20contributor). Lemme know if i'm missing something. Thank you for your comment

**Comment by flodnv** [comment] 2022-11-28 12:21
@aneequeahmad thank you for raising this, which we have discussed internally with Contributor+s. 

[Personal time or resources applied towards investigating a proposal will not guarantee compensation as written in contributing.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Personal%20time%20or%20resources%20applied%20towards%20investigating%20a%20proposal%20will%20not%20guarantee%20compensation.)

I have sent a PR to further clarify this in contributing.md: https://github.com/Expensify/App/pull/13081

**Comment by lschurr** [comment] 2022-11-29 22:39
@flodnv - what are we waiting on for this one? It looks like the PR is merged right?

**Comment by flodnv** [comment] 2022-11-30 12:21
@lschurr you can issue the payments

**Comment by lschurr** [comment] 2022-11-30 21:18
@aneequeahmad - you're still eligible for a reporting bonus since you initially reported the bug. Can you apply for the job in Upwork? https://www.upwork.com/ab/applicants/1594686468145885184/job-details

**Comment by lschurr** [comment] 2022-11-30 21:21
@rushatgabhane - could you also apply for the job in Upwork?

**Comment by aneequeahmad** [comment] 2022-11-30 21:35
@lschurr Im getting an error on [this]( https://www.upwork.com/ab/applicants/1594686468145885184/job-details) link
![Screenshot 2022-12-01 at 2 33 44 AM](https://user-images.githubusercontent.com/36359331/204912844-e746497b-8783-4cff-a016-8ff45e4e710a.png)

**Comment by lschurr** [comment] 2022-11-30 22:45
Ah, can you try this one @aneequeahmad? https://www.upwork.com/jobs/~01b384c685e3f60dd2

**Comment by aneequeahmad** [comment] 2022-11-30 22:59
@lschurr applied. Thanks

**Comment by lschurr** [comment] 2022-12-01 17:44
@0xmiroslav has been paid in Upwork.

@aneequeahmad - go ahead and accept the offer and payment will be issued.

@rushatgabhane - please apply to the job in Upwork (https://www.upwork.com/jobs/~01b384c685e3f60dd2)

**Comment by lschurr** [comment] 2022-12-01 17:57
@flodnv could you double check the timeline? I'm seeing a proposal on 11/15 and then a merged PR on 11/22.. am I reading that incorrectly?

**Comment by aneequeahmad** [comment] 2022-12-01 18:41
@lschurr applied thanks

**Comment by flodnv** [comment] 2022-12-02 11:48
@rushatgabhane is correct

@lschurr please issue bonuses

**Comment by lschurr** [comment] 2022-12-02 15:47
Woop! All have been paid and the job is closed.

**Closed by lschurr** 2022-12-02 15:47 UTC
Labels: External, Engineering, Daily, Bug
