### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] BUG: [distance] request map is cut off after going online

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26540] opened 2023-09-01 23:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run App on latest main branch (for now)
2. Sign in with an account on the distance requests beta (or enable all betas)
3. Go offline
4. Click green plus, request money, distance, enter start and finish addresses
5. Click next
6. Go online and maybe wait a bit
7. Go back to the page with the map

## Expected Result:
The route renders properly on the map and it's not cut off

## Actual Result:
The bottom section of the map is cut off and the bottom corners are not rounded

## Workaround:
Ignore it

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** unreleased
**Reproducible in staging?:** Not yet
**Reproducible in production?:** Not yet
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Originally reported by 
[@situchan](https://expensify.slack.com/team/U04MF8KAANP)
 in a [PR review here](https://github.com/Expensify/App/pull/25707#pullrequestreview-1606168005)
**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693609781739659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016004dbcd8eeeb10d</li>
        <li>Upwork Job ID: 1697749501998895104</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>nahid633 | Contributor | 26681342</li>
<li>situchan | Reporter | 26681346</li>
</ul></li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-09-01 23:14
Side note:bug: if I create a new issue with external and bug labels it assigns two BZ.

**Comment by b4s36t4** [comment] 2023-09-01 23:18
@neil-marcellini when we go back to online, the amount should be update there itself? means ConfirmPage itself or the user needs to go back the page?

**Comment by b4s36t4** [comment] 2023-09-01 23:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[distance] request map is cut off after going online
### What is the root cause of that problem?

Considerably there are two problems here.

1. To show TBD.

Even though we don't have access to how much distance the ride is we're still calculating the distance amount here https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/libs/DistanceRequestUtils.js#L72 in this function which is returning odd amount.

We can return "TBD" if the `distanceInMiles` is `0`.

> The usage of this function is getting refactored in other PR which could give us a way to do this in 
> `MoneyRequestConfirmationList` component itself. Above point is only for reference. Also we need to consider the network 
> status before just giving `TBD`

We can do same with `Amount` menu as well. Just some conditionals within `MoneyRequestConfirmationList` component.

2. Getting Values when going back to online.

On `MoneyRequestConfirmationList` we're rendering the map and when we go offline in money request page we'll call `GetRoutes` command which will return us the route and distance etc which we use to calculate distance and then amount based on it.

But while creating if we're offline we won't be having it so the route will be null even if go online which require us to close the modal and go up again.



### What changes do you think we should make in order to solve the problem?

To fix this we need to do two changes.

Here in this `useEffect` https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/components/DistanceRequest.js#L154

we need update the logic as below 

```jsx

if ((isOffline && _.isEmpty(waypoints)) || !shouldFetchRoute) {
    return;
}

```

Which will refetch the request if there are waypoints and we've updated our online status.

But this only requires us to come back to the first page again, which won't be the case everytime.

To update the `routes` inside `ConfirmedRoute` we also need to call the `GetRoute` command there as well.

```jsx

    useEffect(() => {
        // If the network is offline or we have the coordinate we don't need to call the api again.
        if (isOffline || !_.isEmpty(coordinates)) return;
        Transaction.getRoute(transaction.transactionID, waypoints);
    }, [coordinates, isOffline, transaction.transactionID, waypoints]);

```

### What alternative solutions did you explore? (Optional)
NA

@neil-marcellini Please review the proposal. Sorry for the ping if you're going to review :)

**Comment by paultsimura** [comment] 2023-09-02 05:46
@neil-marcellini please note that my proposal in https://github.com/Expensify/App/issues/26537 fixes the route rendering issue.
These 2 bugs look quite related.
Also it seems like @b4s36t4 's proposal belongs more to that issue than to this one.

**Comment by studentofcoding** [comment] 2023-09-03 05:36
#Proposal

## Please re-state the problem that we are trying to solve in this issue
BUG: [distance] request map is cut off after going online 

## What is the root cause of that problem?
The bug appears because the application does not re-fetch the MapBox route when transitioning from offline to online. This means that if the user goes offline and then comes back online, the MapBox route is not updated, causing it not to appear correctly.

## What changes do you think we should make in order to solve the problem?
Add a mechanism to https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L76 using `useEffect` to listens for changes in the network status and triggers a re-fetch of the MapBox route when the application goes from offline to online.

```
function DistanceRequest({iou, iouType, report, transaction, mapboxAccessToken}) {
    const previousIsOffline = usePrevious(isOffline); // Add this line to store the previous network status

    // ... (rest of the code)


    // Add this useEffect hook
    useEffect(() => {
        if (!previousIsOffline || isOffline || !iou.transactionID) {
            return;
        }
    
        Transaction.getRoute(iou.transactionID, waypoints);
    }, [isOffline, previousIsOffline, iou.transactionID, waypoints]);

    // ... (rest of the code)
}
```



## What alternative solutions did you explore? (Optional)
None

## Result

https://github.com/Expensify/App/assets/20473526/39f14bec-f300-4ed1-8cff-103f1189938f

**Comment by studentofcoding** [comment] 2023-09-03 05:37
> #Proposal
> 
> ## Please re-state the problem that we are trying to solve in this issue
> BUG: [distance] request map is cut off after going online
> 
> ## What is the root cause of that problem?
> The bug appears because the application does not re-fetch the MapBox route when transitioning from offline to online. This means that if the user goes offline and then comes back online, the MapBox route is not updated, causing it not to appear correctly.
> 
> ## What changes do you think we should make in order to solve the problem?
> Add a mechanism to
> 
> https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L76
> 
> using `useEffect` to listens for changes in the network status and triggers a re-fetch of the MapBox route when the application goes from offline to online.
> ```
> function DistanceRequest({iou, iouType, report, transaction, mapboxAccessToken}) {
>     const previousIsOffline = usePrevious(isOffline); // Add this line to store the previous network status
> 
>     // ... (rest of the code)
> 
> 
>     // Add this useEffect hook
>     useEffect(() => {
>         if (!previousIsOffline || isOffline || !iou.transactionID) {
>             return;
>         }
>     
>         Transaction.getRoute(iou.transactionID, waypoints);
>     }, [isOffline, previousIsOffline, iou.transactionID, waypoints]);
> 
>     // ... (rest of the code)
> }
> ```
> 
> ## What alternative solutions did you explore? (Optional)
> None
> 
> ## Result
>  cropped_mapbox_fixed.mp4

cc : @neil-marcellini

**Comment by b4s36t4** [comment] 2023-09-03 05:43
@studentofcoding I don't think you understand the bug correctly. This isn't about loading the route or not.

Sometimes when you only have two waypoints and move offline and online back and forth and doing some things like closing modal selecting an address or adding and removing multiple waypoints causing the map to cutoff.

Like in your video you have the map fully, but the bug is you'll be having the map but the bottom of the map like 10-15% of it is showing as black which is weird and that is the bug.

Let me know if you don't understand the bug.

**Comment by ArekChr** [comment] 2023-09-04 09:58
@neil-marcellini, could you please provide a video showing the actual results of this issue and specify which platforms are affected?

**Comment by trjExpensify** [comment] 2023-09-04 11:36
@ArekChr a video came with the report here by @situchan in the PR: https://github.com/Expensify/App/pull/25707#pullrequestreview-1606168005

**Comment by nahid633** [comment] 2023-09-04 15:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

BUG: [distance] request map is cut off after going online

### What is the root cause of that problem?
 
The problem is related to Mapbox resizing.It is related to the size of the container where the <canvas> is located.
 
### What changes do you think we should make in order to solve the problem?
we should call `mapRef.resize()`. For that we need ResizeObserver to detect size changes on the canvas container.

### What alternative solutions did you explore? (Optional)
none

https://github.com/Expensify/App/assets/22540272/f292a211-e093-445b-9d5d-f63320611619

**Comment by nahid633** [comment] 2023-09-04 15:17
Contributor details
Your Expensify account email: quliyevn633@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018b5a73519689f99a

**Comment by ArekChr** [comment] 2023-09-05 10:10
> we should call mapRef.resize(). For that we need ResizeObserver to detect size changes on the canvas container.

This fix looks good 👌 @nahid633 Could you provide more details on which place should be this function called?

**Comment by nahid633** [comment] 2023-09-05 11:58
In MapView component inside
useEffect(() => 
we need to add 
            const resizeObserver = new ResizeObserver(() => {
               mapRef.resize();
            });
            resizeObserver.observe(mapRef.getContainer());

**Comment by nahid633** [comment] 2023-09-07 05:44
@ArekChr tagging you for reviewing.

**Comment by trjExpensify** [comment] 2023-09-11 11:17
@ArekChr can you review this please? Thanks!

**Comment by ArekChr** [comment] 2023-09-11 12:34
@nahid633 It seems `MapView` doesn't have methods such as `resize` or `getContainer`

**Comment by nahid633** [comment] 2023-09-11 13:09
@ArekChr  https://github.com/Expensify/App/blob/main/src/components/MapView/MapView.web.tsx
line 40.
```
            const resizeObserver = new ResizeObserver(() => {
                mapRef?.resize();
            });

            resizeObserver.observe(mapRef.getContainer());
```

**Comment by ArekChr** [comment] 2023-09-11 14:02
Thanks @nahid633, Looked in the wrong file. This actually solves the problem, the [proposal](https://github.com/Expensify/App/issues/26540#issuecomment-1705413649) LGTM

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by trjExpensify** [comment] 2023-09-12 23:28
Woop! @neil-marcellini can you give this the green light, so we can get @nahid633 going on the PR. Thanks!

**Comment by neil-marcellini** [comment] 2023-09-14 20:19
Ah yeah sorry I missed this for a bit. 

> the [proposal](https://github.com/Expensify/App/issues/26540#issuecomment-1705413649) LGTM

I agree with C+.

**Comment by ArekChr** [comment] 2023-09-15 09:28
@nahid633 Friendly bump, any progress with the PR?

**Comment by nahid633** [comment] 2023-09-15 15:43
Hey @ArekChr , i got offer from upwork today. I will finish and create PR today.

**Comment by nahid633** [comment] 2023-09-16 11:40
@ArekChr [PR](https://github.com/Expensify/App/pull/27574) is ready

**Comment by trjExpensify** [comment] 2023-09-29 10:13
👋 @ArekChr can you get tot he checklist please so we can proceed with the payments? Thanks!

**Comment by trjExpensify** [comment] 2023-10-02 14:58
Awaiting the above!

**Comment by ArekChr** [comment] 2023-10-03 10:57
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by trjExpensify** [comment] 2023-10-03 13:11
Thanks! I tend to agree a visual display issue like a cut off map will be captured in the regression testing of the distance feature, so we don't need a standalone one.

Confirming payments as follows: 

- $500 to @nahid633 for the bug fix 
- $50 to @situchan for the bug report

Settled up, closing!

**Closed by trjExpensify** 2023-10-03 13:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
