### ISSUE TITLE
[$1000] Dev: IOS -The main composer disappears when the thread message edit composer is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26577] opened 2023-09-02 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Click on "Reply in thread"
4. Send a thread message
5. Click on "Edit comment" of sent thread message
6. Press the back button
7. Notice the main composer is not visible when the thread message edit composer is open

## Expected Result:
The main composer should remain visible even when the thread message edit composer is open

## Actual Result:
The main composer disappears when the thread message edit composer is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.62.0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aff0a6ec-2fdc-4731-9c08-b768cb8e8d50

**Expensify/Expensify Issue URL:**
**Issue reported by:** ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693252930657099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a57e2ba43c540555</li>
        <li>Upwork Job ID: 1702066864486952960</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-09-08 16:55
This is different but I believe same rca as https://github.com/Expensify/App/issues/24555 that is goimg to be merged soon

**Comment by kadiealexander** [comment] 2023-09-12 04:54
I'm getting a different error on all iOS devices due to [this](https://expensify.slack.com/archives/C049HHMV9SM/p1693989321525899)
https://github.com/Expensify/App/assets/59587260/718b4a8d-ee78-4dbd-abf0-900898c889dd

**Comment by kadiealexander** [comment] 2023-09-13 05:53
Have posted [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694584345988399) to get help reproducing this so I don't continue to be a blocker.

**Comment by mallenexpensify** [comment] 2023-09-13 10:41
Unable to reproduce on iOS v1.3.68-15

https://github.com/Expensify/App/assets/22508304/93107c83-57af-4927-9fa4-1bd87581e2e7

**Comment by kadiealexander** [comment] 2023-09-18 04:02
Not overdue!

**Comment by kadiealexander** [comment] 2023-09-21 08:19
Not overdue!

**Comment by b4s36t4** [comment] 2023-09-21 09:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: IOS -The main composer disappears when the thread message edit composer is open
### What is the root cause of that problem?

Bug 1: Why composer didn't shown at all? As per the recording we can see that there is no keyboard at all, but we hide/show main composer based on the keyboard visibility. As the simulator doesn't contain any keyboard there's a high chance that `keyBoardWillHide` is not called at all.

https://github.com/Expensify/App/blob/f65c58e2ccaf9204fec93852c5fb4e6b0667926f/src/libs/setShouldShowComposeInputKeyboardAware/index.native.js#L22

> I'm also not able to re-produce this.

Bug 2: Composer getting pained a bit late as per this comment - https://github.com/Expensify/App/issues/26577#issuecomment-1717383557

https://github.com/Expensify/App/blob/f65c58e2ccaf9204fec93852c5fb4e6b0667926f/src/libs/setShouldShowComposeInputKeyboardAware/index.native.js We handle the main composer visibility in this based on the parameter `shouldShow` 

The values can be `true` or `false` but we are never conditioned to the value `true` whereas we call the function with value `true` here https://github.com/Expensify/App/blob/f65c58e2ccaf9204fec93852c5fb4e6b0667926f/src/pages/home/report/ReportActionItemMessageEdit.js#L402 which is calling the function correctly but function does nothing :/

Final RC is, composer visibility depends on keyboard visibility which takes a bit of time because of the listener's callback needs to be called and then again composer visibility changes required.


### What changes do you think we should make in order to solve the problem?

We can have a condition if `shouldShow` is true we reset the composer visibility in this file
https://github.com/Expensify/App/blob/f65c58e2ccaf9204fec93852c5fb4e6b0667926f/src/libs/setShouldShowComposeInputKeyboardAware/index.native.js

```js
if(shouldShow){
    Composer.setShouldShowComposeInput(true);
}
```
Which show the composer whenever the `ReportActionItemMessageEdit` component looses focus on the composer.

> There might be a little jerk because of component rendering while keyboard is closing, which I feel ok and oddly noticeable on mobile screen. Better than showing 
> late right?




### What alternative solutions did you explore? (Optional)
NA


https://github.com/Expensify/App/assets/59088937/ac8f3871-a5bd-47a0-9984-66fb7b4853c2

**Comment by s-alves10** [comment] 2023-09-21 12:25
Is this issue still reproducible on main? I wasn't able to reproduce on the latest main

**Comment by s-alves10** [comment] 2023-09-21 12:29
I think this issue was fixed already. We can close this

**Comment by s-alves10** [comment] 2023-09-21 12:31
We show composer after hiding keyboard if keyboard is visible. If keyboard isn't visible, we show the composer instantly. This is an intentional behavior.

**Comment by b4s36t4** [comment] 2023-09-21 13:09
@s-alves10 the point is composer should show instantly when we close the keyboard... if you see the video it's taking a few seconds delay to show. That's a bug.

**Comment by kadiealexander** [comment] 2023-09-25 06:16
Closing as no longer a bug.

**Closed by kadiealexander** 2023-09-25 06:16 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
