### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Search - Delete modal message changes to ".. these expenses" briefly when clicking Cancel

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45447] opened 2024-07-16 02:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/45143
**Version Number:** 9.0.7-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has at least one unpaid expense.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Click on the checkbox next to one expense (one only, important)
4. Click on the dropdown.
5. Click Delete.
6. Note that the modal message is "Are you sure that you want to delete this expense?"
7. Click Cancel.
8. Note that the modal message changes to "Are you sure that you want to delete these expenses?" quickly before it disappears.

## Expected Result:
The delete modal message should be consistent and not change when clicking Cancel button.

## Actual Result:
The delete modal message changes from "Are you sure that you want to delete this expense?" to "Are you sure that you want to delete these expenses?" after clicking Cancel button.

This issue only happens when one expense is selected.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/96ae1feb-7601-4e9c-b47b-0f2e2f939ab0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01086f676b97015a4f</li>
        <li>Upwork Job ID: 1815203340945056905</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 103247059</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by neonbhai** [comment] 2024-07-16 03:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Delete modal message changes to ".. these expenses" briefly when clicking Cancel

### What is the root cause of that problem?
When deletign expenses we clear the selected items. 
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/Search/SearchListWithHeader.tsx#L69-L77

This changes the translation from pural to singular notation for a second. This causes the text change

### What changes do you think we should make in order to solve the problem?
We will clear selected options after we have hidden the modal [here](https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/Search/SearchListWithHeader.tsx#L69-L77)

**Comment by bernhardoj** [comment] 2024-07-16 06:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Delete modal confirmation message text changes from "...this expense..." to "...these expenses..." when closing the modal.

### What is the root cause of that problem?
The title depends on the selected item to delete count.
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/Search/SearchListWithHeader.tsx#L194-L199

When we press Cancel, it will clear the selected item to delete and set the modal visibility to false.
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/components/Search/SearchListWithHeader.tsx#L62-L65

This makes the selected item to delete count become 0 and the plural form is used while the modal is still animating to close.

### What changes do you think we should make in order to solve the problem?

Clears the selected item to delete when the modal is fully hidden instead of cancelling the modal.
```
onModalHide={() => setSelectedItemsToDelete([])}
```

**Comment by abdulrahuman5196** [comment] 2024-07-24 08:27
Checking now

**Comment by abdulrahuman5196** [comment] 2024-07-24 10:28
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/45447#issuecomment-2230127733 looks good and works well. Using `onModalHide` is better compared to other proposals.

🎀 👀 🎀
C+ Reviewed
@robertjchen

**Comment by bernhardoj** [comment] 2024-07-24 10:42
Yes, it works well.

https://github.com/user-attachments/assets/c5ce635d-92cf-4967-848b-1433c1dbe937

Pretty sure @abdulrahuman5196 have tested it too.

**Comment by robertjchen** [comment] 2024-07-24 11:39
Sounds good, thanks for testing- let's go with @bernhardoj 's proposal 👍

**Comment by bernhardoj** [comment] 2024-07-24 15:46
PR is ready

cc: @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2024-08-14 15:14
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/45143/files#r1717120388

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open Search page
2) Click on the checkbox next to one of the expenses (one only, important)
3) Click on the dropdown
4) Click Delete
5) Note that the confirmation message is "Are you sure that you want to delete this expense?"
6) Click Cancel
7) Verify the confirmation message doesn't change to "Are you sure that you want to delete these expenses?"

**Comment by slafortune** [comment] 2024-08-14 16:05
@abdulrahuman5196 Role C+ is due payment through NewDot Manual Requests - $250
@bernhardoj Role Contributor requires payment through NewDot Manual Requests - $250

**Closed by slafortune** 2024-08-14 16:05 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-14 19:10
$250 approved for @abdulrahuman5196

**Comment by bernhardoj** [comment] 2024-08-15 02:45
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-21 10:59
$250 approved for @bernhardoj
