### ISSUE TITLE
[$1000] selected country does not show on opening Country selection page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23768] opened 2023-07-27 22:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Profile > Personal details > Home address > Country
2. select any country which will redirects to Home address
3. again click on country which will auto populate country name
4. remove the country name from input field  and click on back button
5. again click on country
## Expected Result: 
selected country name should show on opening Country selection page
## Actual Result: 
selected country does not show on opening Country selection page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d162ce06-8536-4c7c-b84e-d0e242b0e202

https://github.com/Expensify/App/assets/43996225/b992e04c-4f90-4482-b28c-bf0566adc854

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690443030366429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d2209c62f7876f0</li>
        <li>Upwork Job ID: 1684883255023452160</li>
        2023-07-28<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25857060</li>
<li>joh42 | Contributor | 25857061</li>
<li>gadhiyamanan | Reporter | 25857063</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-07-28 12:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
selected country does not show on opening Country selection page

### What is the root cause of that problem?
In `AddressPage`, `CountryPicker` component is never unmounted. When we click on country we only change `isPickerVisible` state from false to true and vice versa. And as that component is never unmounted we are not resetting the state here - https://github.com/Expensify/App/blob/a5373eb50f73bc8a33f7aa5e14059523c7645cf1/src/components/CountryPicker/index.js#L36

The root cause of this is not firing useEffect because of dependency change but component not getting remounted when we open the modal.

### What changes do you think we should make in order to solve the problem?
We shall add `isPickerVisible` to `useEffect` dependency array.
Same can be done for `StatePicker` component.

Without opening - 
<img width="960" alt="Screenshot 2023-07-28 at 5 47 39 PM" src="https://github.com/Expensify/App/assets/27822551/2a12cef6-db2f-43db-8680-0dd6229dcea1">

When opened - 
<img width="946" alt="Screenshot 2023-07-28 at 5 48 25 PM" src="https://github.com/Expensify/App/assets/27822551/53bd5e68-a776-4937-9f5b-d29af619db81">



### What alternative solutions did you explore? (Optional)

**Comment by joh42** [comment] 2023-07-28 14:39
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected country in the country picker modal remains cleared after closing and reopening it.
### What is the root cause of that problem?
`searchValue` remains cleared when the modal is reopened.
### What changes do you think we should make in order to solve the problem?
I suggest we set the search value in `showPickerModal()` using `setSearchValue(lodashGet(allCountries, value, ''));`
https://github.com/Expensify/App/blob/b5b730dc02574351524f860e28c0465749a7ae72/src/components/CountryPicker/index.js#L42-L44
I acknowledge that this is similar to other proposed solutions. The difference is that we only run `setSearchValue` when opening the modal, as opposed to both when opening and closing it.
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-07-28 18:26
@dukenv0307 Thanks for the proposal. Your RCA is about right. The solution makes sense but I think we should avoid adding state variables to `useEffect` dependencies because this causes an extra unnecessary render.

```js
// Pattern A
setFoo(5);
setBar(10);
```

```js
// Pattern B
useEffect(() => setBar(10), [foo]);
setFoo(5);
```

Pattern A will result in 1 render while Pattern B will result in 2 renders. We use Pattern B only when we need to setBar after foo is guaranteed to be set. - This is not the case here, we don't need to wait for `isPickerVisible` before setting `searchValue`.

**Comment by s77rt** [comment] 2023-07-28 18:27
@BhuvaneshPatil Thanks for the proposal. I think it's the same as @dukenv0307's proposal.

**Comment by s77rt** [comment] 2023-07-28 18:36
@joh42 Thanks for the proposal. Your RCA does not say much but it's actually correct, `searchValue` remains cleared because once we clear it, we simply do nothing and it stays cleared. The suggested solution looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by s77rt** [comment] 2023-07-28 18:38
@dukenv0307 Thanks for the update but that's actually what @joh42 already suggested.

**Comment by s77rt** [comment] 2023-07-29 12:07
@dukenv0307

If the first solution was
```js
useEffect(() => {
    ...
}, [isPickerVisible]);
```
and the second was
```js
useEffect(() => {
    if (!isPickerVisible) {
        return;
    }
    ...
}, [isPickerVisible]);
```

That would be an optimisation. But in our case the first solution uses `useEffect` while the second solution does not. I think that's enough to distinguish a new approach given the issue simplicity.

**Comment by MariaHCD** [comment] 2023-07-31 11:46
For https://github.com/Expensify/App/issues/23725, I don't think the fix will be refactoring the country picker and state picker as a single page.

So I think we can go ahead with fixing this issue.

cc: @mountiny

**Comment by mountiny** [comment] 2023-07-31 11:51
Yep I agree that we should not be refactoring this to two pages unless thats the only possible solution

**Comment by MariaHCD** [comment] 2023-07-31 13:22
Cool, so let's go ahead with @joh42's proposal as per @s77rt's recommendation.

**Comment by joh42** [comment] 2023-07-31 15:15
Thanks! You can expect a PR to be ready for review tomorrow.

**Comment by joh42** [comment] 2023-08-01 21:49
This exact issue is present in the state selector:

https://github.com/Expensify/App/assets/138504087/0f1a005b-77d4-4e7c-8b37-addc3dcf9692

I'll fix both while I'm at it

**Comment by joh42** [comment] 2023-08-01 22:24
Please note: the state picker is broken in Storybook due to an issue with HeaderWithBackButton that I have reported [here](https://app.slack.com/client/T03SC9DTT/C049HHMV9SM/thread/C049HHMV9SM-1690924765.915249). This issue exists on [staging](https://staging.new.expensify.com/docs/index.html?path=/story/components-form--default). As [suggested](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1690918046.950089) by Jack Nam I still marked the Storybook checkbox as completed, since that issue is not caused by this PR.

**Comment by joh42** [comment] 2023-08-01 23:24
The PR is ready for review @s77rt

**Comment by dylanexpensify** [comment] 2023-08-11 19:59
Great work!

**Comment by dylanexpensify** [comment] 2023-08-18 19:11
Hmm, I think a payment is due - @joh42 @s77rt did you both apply to upwork?

**Comment by s77rt** [comment] 2023-08-18 19:33
@dylanexpensify No payment is due for me here. Payment will be handled in https://github.com/Expensify/App/pull/21049 as this is a regression.

**Comment by joh42** [comment] 2023-08-21 14:29
@dylanexpensify I got an offer automatically (this is my Upwork profile https://www.upwork.com/freelancers/~01c600f0d690c3dfe1)

**Comment by dylanexpensify** [comment] 2023-08-25 11:30
Payments sent!

**Closed by dylanexpensify** 2023-08-25 11:30 UTC
Labels: Reviewing, External, Weekly, Bug
