### ISSUE TITLE
[$500] Not able to update the desktop version from the deprecated version

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37349] opened 2024-02-27 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-4
**Reproducible in staging?:**  needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709019010145459

## Action Performed:
1. Have a deprecated version of the desktop app (such as 1.4.40-4) installed.
2. Get a screen to update the app version "Please update to the latest version of New Expensify"
3. Click `update`

## Expected result: 
the app downloads the update, then automatically restarts and updates.

## Actual result: 
It downloads the .dmg for a new version of the app. To use this version, the user would have to fully uninstall the existing app version and reinstall it from the dmg, Meanwhile, the normal upgrade path of clicking New Expensify -> Check for updates in the app menu is broken. It relies on browser notifications, which have been disabled. (edited) 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (4)](https://github.com/Expensify/App/assets/38435837/a0678b1a-f738-4066-a218-841f3fcac6ed)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137e8a469dcace76d</li>
        <li>Upwork Job ID: 1813344678361465062</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by roryabraham** [comment] 2024-02-28 01:05
Putting this on HOLD for https://github.com/Expensify/App/issues/36758 to make it possible for Applause to test this.

**Comment by adelekennedy** [comment] 2024-03-01 19:46
on hold

**Comment by adelekennedy** [comment] 2024-03-04 16:31
@roryabraham this is still on hold for #36758 right? I think we'd deprioritize this till weekly or monthly to match that issue?

**Comment by roryabraham** [comment] 2024-03-06 06:46
agreed

**Comment by adelekennedy** [comment] 2024-03-13 22:36
deprioritized at the moment

**Comment by adelekennedy** [comment] 2024-04-15 18:38
This is an improvement tied to #36758 - keeping monthly and on hold for now

**Comment by adelekennedy** [comment] 2024-05-16 21:32
still deprioritized

**Comment by adelekennedy** [comment] 2024-06-17 20:24
still deprioritized

**Comment by roryabraham** [comment] 2024-07-16 22:47
Taking this off HOLD since https://github.com/Expensify/App/issues/36758 is done

**Comment by roryabraham** [comment] 2024-07-23 14:45
As discussed in slack, we unfortunately have to put this on HOLD until `9.0.8-1` is deprecated

**Comment by roryabraham** [comment] 2024-07-27 06:58
Can check in [here](https://github.com/Expensify/Web-Expensify/blob/main/lib/Request.php#L31) to see when this can come off HOLD. Right now the minimum supported version is 9.0.5-13

**Comment by adelekennedy** [comment] 2024-08-06 21:59
@roryabraham what's the minimum supported version we need in order to take this off hold? Do we need to wait until it's current?

**Comment by roryabraham** [comment] 2024-08-08 17:51
we need to wait for https://github.com/Expensify/Web-Expensify/blob/3f944d3b34597a71007af529093ac9170c269167/lib/Request.php#L31 to show 9.0.8-2 or higher.

Of course, if we don't want to wait, we could just deprecate older app versions (though, I'd at minimum wait until next week, because of the earnings call)

**Comment by roryabraham** [comment] 2024-08-21 16:30
PR to deprecate 9.0.8-1: https://github.com/Expensify/Web-Expensify/pull/43217

time to move this along

**Comment by roryabraham** [comment] 2024-08-28 17:15
Just completed a successful (forced) update. Going to close this as no longer reproducible

**Closed by roryabraham** 2024-08-28 17:15 UTC
Labels: External, Weekly, Help Wanted, Bug
