### ISSUE TITLE
[HOLD for payment 2023-12-28][$500][Theme Switching] 🐛 Android - Track distance - The inscription in the pop-up window is hardly visible in light mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33136] opened 2023-12-15 01:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user turns on light mode on the app
1. Open the app
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Reimbursements -> Track distance
4. Tap on Unit

## Expected Result:
The inscription in the pop-up window is good visible

## Actual Result:
The inscription in the pop-up window is hardly visible
The same behavior happens with pop-up windows during connecting bank account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6313771_1702595709864!Screenshot_2023-12-15-00-18-12-83_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/78819774/eb57ac10-b67f-4258-b7a5-b2e7041199e3)

![Bug6313771_1702595709846!Screenshot_2023-12-15-00-20-44-89_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/78819774/6e2cac92-1bdc-4748-9349-5d0aeee73cad)

![Bug6313771_1702595709845!photo_2023-12-15_01-06-29](https://github.com/Expensify/App/assets/78819774/9b8ad589-2b9d-4136-a313-5e17b086b002)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee03b399c3458856</li>
        <li>Upwork Job ID: 1737582136051163136</li>
        <li>Last Price Increase: 2023-12-20</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-12-15 01:47
@grgia looks like this is related to themes, do you think you could get a fix up?

**Comment by jasperhuangg** [comment] 2023-12-15 02:37
At least for the workspace reimburse view portion of this issue–it seems like the bug is coming from us not passing theme styles into these components: https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L182-L205

@grgia do you know what styles we're supposed to be passing here?

**Comment by grgia** [comment] 2023-12-15 03:00
@jasperhuangg if we pass the {color: theme.textLight} we can make the text white for now

**Comment by neonbhai** [comment] 2023-12-15 03:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track distance - The inscription in the pop-up window is hardly visible in light mode

### What is the root cause of that problem?
All these errors are because of the `Picker` component.
We are missing the backgroundColor prop for this component in all places. This did work until now, since by default it takes the dark mode.

The text is hardcoded to be always white here:
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/Picker/BasePicker.tsx#L168


### What changes do you think we should make in order to solve the problem?
We should make sure the [`BasePicker`](https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/Picker/BasePicker.tsx) component gets the right theme [here](https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/Picker/BasePicker.tsx#L168)

```js
color: theme.text
```


We should pass the `backgroundColor` prop for the Picker components:

https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/AddPlaidBankAccount.js#L246-L255

https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L199-L204

https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/pages/ReimbursementAccount/CompanyStep.js#L233-L241

```js
backgroundColor={theme.componentBG}
```

### Alternatively
We can remove the backgroundColor prop and set it according to theme inside the [`BasePicker`](https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/Picker/BasePicker.tsx) component itself.

**Comment by Julesssss** [comment] 2023-12-15 10:12
@neonbhai I like setting this in the base picker, any reason why you made that your alternative solution?

**Comment by situchan** [comment] 2023-12-15 10:22
All of these are same issues:
- #33120
- #33136
- #33137 
- #33138

**Comment by neonbhai** [comment] 2023-12-15 11:32
> any reason why you made that your alternative solution?

@Julesssss Hey, was wondering if it wasn't done already for a reason. Setting it in base picker itself is a cleaner solution!

**Comment by grgia** [comment] 2023-12-15 15:57
@situchan I agree with that, we should fix those in one PR

**Comment by grgia** [comment] 2023-12-15 16:14
@neonbhai @situchan 
https://github.com/Expensify/App/pull/16103
Does your proposal work if we remove the dark mode hardcoded background color from this PR? Or do we need to keep that? I'd test locally but my android emulator is completely broken right now

**Comment by situchan** [comment] 2023-12-15 16:17
Goin

> @neonbhai @situchan #16103 Does your proposal work if we remove the dark mode hardcoded background color from this PR? Or do we need to keep that? I'd test locally but my android emulator is completely broken right now

Will try test, but I think it will depend on system theme.

If we should match with app theme, there should be way to communicate between RN and native so if user preference is updated in RN, it should send to native so that native modals update theme properly.

**Comment by grgia** [comment] 2023-12-15 16:18
> Will try test, but I think it will depend on system theme. 

Thank you, I think if we go this route, we should try to match the theme. 

I guess the alternative is using one modal color style on all devices since it only affects android. Let me check with design @situchan

**Comment by grgia** [comment] 2023-12-15 16:50
This one specifically has a secondary problem as the text color is being set to text (?) so at least we should pass the correct text color for both themes

**Comment by grgia** [comment] 2023-12-15 17:02
@situchan if you're able to test the solution, I think for now if we fix the text color to white so it's at least readable then we can remove the deploy blocker and fix the modals pending the convo in slack. 
I've been trying to get my android emulator working but I can't seem to get anything to build without fail, so I am unable to debug this right now. 

If @neonbhai's proposal addresses the text color so it works on the 4 cases (OS Dark/Dark, OS Dark/Light OS Light/Dark OS Light/Light), then let's move forward with that- even if the modal remains dark theme on android light

**Comment by neonbhai** [comment] 2023-12-15 17:13
@grgia having the color as `theme.textLight` fixes the issue:

<img width="350" alt="Screenshot 2023-12-15 at 10 41 02 PM" src="https://github.com/Expensify/App/assets/64629613/a27cc9b4-b7ec-470c-9a6a-19d3d3b954c3">
<img width="350" alt="Screenshot 2023-12-15 at 10 40 29 PM" src="https://github.com/Expensify/App/assets/64629613/deb1a44a-a1b4-434f-9d49-6a550d2f022c">

**Comment by situchan** [comment] 2023-12-15 17:17
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/Picker/BasePicker.tsx#L167C1-L168

@neonbhai that color was also hardcoded intentionally to fix windows picker issue

**Comment by situchan** [comment] 2023-12-15 17:18
I think we should use platform specific code for this.
cc: @grgia

**Comment by grgia** [comment] 2023-12-15 17:40
https://github.com/Expensify/App/blob/655c06c1425e9f889428584eef3c7029f703129a/src/styles/theme/themes/light.ts#L68

@situchan the pickerOptionsTextColor is set to a light color on light mode

**Comment by situchan** [comment] 2023-12-15 18:06
@neonbhai can you share your test branch?

**Comment by roryabraham** [comment] 2023-12-15 18:38
Looking at Android native styles, it looks like we've got some [custom themes for Android native components](https://github.com/Expensify/App/blob/914fe828aaf772739f02c8a8eff9f12428027b66/android/app/src/main/res/values/styles.xml#L3C1-L49), but right now I can't see where the actual background color is set

**Comment by situchan** [comment] 2023-12-15 18:41
@roryabraham https://github.com/Expensify/App/pull/16103/files#diff-f8a6fa55d63160ea7414fd96c94ad6a8a7ffac4f6f3c3706c205a7050c82a9ddR28

**Comment by neonbhai** [comment] 2023-12-15 19:05
Hi @grgia,
> the pickerOptionsTextColor is set to a light color on light mode

productLight900 is #002E22 in app, which is dark tinted:


<img width="338" alt="Screenshot 2023-12-16 at 12 00 59 AM" src="https://github.com/Expensify/App/assets/64629613/b4aeaf13-ae5a-438e-afc5-6b928c670473">


(The naming is bit confusing here for me too)

This means, 

We might need windows specific code to handle the text color on the platform, since:

1. We need white color for text to showup on native devices
2. We need dark color for text to showup on windows devices

branch [here](https://github.com/Expensify/App/compare/main...neonbhai:Expensify:picker-style-fix).

**Comment by roryabraham** [comment] 2023-12-15 19:09
Ok, let's do that as a temporary workaround then follow up with more robust Android native theme switching.

**Comment by grgia** [comment] 2023-12-15 19:09
@neonbhai on your branch, I think we'd actually flip the if statement and return textLight on windows

**Comment by grgia** [comment] 2023-12-15 19:10
The theme key is theme-dependent whereas textLight is white on both light/dark mode

https://github.com/Expensify/App/issues/33136#issuecomment-1858246436

**Comment by roryabraham** [comment] 2023-12-15 19:14
Also @neonbhai instead of making a `getItemColor` a function let's use `useMemo` to memoize the value:

```ts
const itemColor = useMemo(() => (getOperatingSystem() === CONST.OS.WINDOWS ? theme.pickerOptionsTextColor : theme.textLight), [theme]);
```

**Comment by roryabraham** [comment] 2023-12-15 19:15
@neonbhai this is an urgent issue, so please let us know when we can expect a pull request to be ready for review. Thanks!

**Comment by situchan** [comment] 2023-12-15 19:16
Please assign me as well for C+ review

**Comment by roryabraham** [comment] 2023-12-15 19:18
Thanks for jumping in @situchan!

**Comment by neonbhai** [comment] 2023-12-15 19:18
@roryabraham working on in right now!

**Comment by neonbhai** [comment] 2023-12-15 19:22
Memoizing was throwing a lint error here:



<img width="1006" alt="Screenshot 2023-12-16 at 12 48 23 AM" src="https://github.com/Expensify/App/assets/64629613/ebc691b9-1ae3-4985-98f1-8e744245dae1">


seems like a false positive tho 🤔 

cc: @situchan

**Comment by grgia** [comment] 2023-12-15 19:27
@neonbhai 
bump on this https://github.com/Expensify/App/issues/33136#issuecomment-1858365045

**Comment by situchan** [comment] 2023-12-15 19:29
> Memoizing was throwing a lint error here:
> 
> <img alt="Screenshot 2023-12-16 at 12 48 23 AM" width="1006" src="https://private-user-images.githubusercontent.com/64629613/290917211-ebc691b9-1ae3-4985-98f1-8e744245dae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Njg3NzAsIm5iZiI6MTcwMjY2ODQ3MCwicGF0aCI6Ii82NDYyOTYxMy8yOTA5MTcyMTEtZWJjNjkxYjktMWFlMy00OTg1LTk4ZjEtOGU3NDQyNDVkYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE5Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWI0OWI5ZTYzMGM4NzQ0ZWZkNmQ4ZGFjY2U0Yjk5OThhODc4MDUwZGM1NjEyYjgyZTIwMzgyNTBmN2QwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fG3hE2RmINzUS4tbVEYPVvJtR36iI5AvlijObusRZMQ">
> seems like a false positive tho 🤔
> 
> cc: @situchan

you should define before `if (isDisabled) {` as it early returns

**Comment by neonbhai** [comment] 2023-12-15 19:30
>  I think we'd actually flip the if statement and return textLight on windows

Hi, the way this bug works, is we need dark on windows in both themes. I'm just retesting, making sure this works everywhere.

Will update soon

cc: @grgia

**Comment by neonbhai** [comment] 2023-12-15 19:33
> you should define before if (isDisabled) { as it early returns

ah right, thank you :bow:

**Comment by roryabraham** [comment] 2023-12-15 20:06
@neonbhai Any status update?

**Comment by grgia** [comment] 2023-12-15 20:09
> Hi, the way this bug works, is we need dark on windows in both themes. I'm just retesting, making sure this works everywhere.

@neonbhai in this case, we should use `textDark` on windows since `pickerOptionsTextColor` is light on light mode

**Comment by neonbhai** [comment] 2023-12-15 20:41
@grgia Thank you for the suggestions, I tested on windows. Nevermind the earlier comment. Windows just needs `theme.text`, as RN on windows picks up the picker bg color by default

**Comment by roryabraham** [comment] 2023-12-15 21:48
Reviewing https://github.com/Expensify/App/pull/33194.

> RN on windows picks up the picker bg color by default

@neonbhai assuming you're talking about the website, right? react-native-web on windows? We don't currently have E/App configured with a native windows client

**Comment by neonbhai** [comment] 2023-12-15 21:50
@roryabraham yes, on the website!

**Comment by roryabraham** [comment] 2023-12-15 22:55
deploying [here](https://github.com/Expensify/App/actions/runs/7227845771)

**Comment by mvtglobally** [comment] 2023-12-16 01:54
Retested, 
Is this expected now? 

![2023-12-16 03 50 49](https://github.com/Expensify/App/assets/43995119/b376d80b-9f25-4f84-b26d-2c88fa1446e8)


https://github.com/Expensify/App/assets/43995119/1221a4ce-44e4-4b14-ab29-47ea81a96705

**Comment by roryabraham** [comment] 2023-12-16 02:53
@mvtglobally yes, that's expected for the time being. We'll follow up with a better fix, but not as something we CP to fix a deploy blocker

**Comment by roryabraham** [comment] 2023-12-16 22:15
So this has been solved on staging, going to:

- Check it off on the deploy checklist
- Mark this with the bug label to orchestrate payments

**Comment by grgia** [comment] 2023-12-18 15:03
Created a master issue for updating the modal theme https://github.com/Expensify/App/issues/33235

**Comment by alexpensify** [comment] 2023-12-20 21:18
@neonbhai and @situchan - to prepare for the payment process, please apply for the job here: 

https://www.upwork.com/jobs/~01ee03b399c3458856

I'm OOO starting on Friday and want to make sure that this one is ready for payment next week. Thanks!

**Comment by alexpensify** [comment] 2023-12-23 03:05
I've confirmed that offers have been sent via Upwork to @situchan and @neonbhai. @situchan please complete the checklist. It looks like the payment date changed to December 28. 

**Heads up, I'm OOO until January 4, but I will log in on Friday, December 29 to complete this payment process pending no regression.**

**Comment by roryabraham** [comment] 2023-12-27 18:49
Waiting for BZ checklists and payments here, not expecting payments to be complete until 12/29.

**Comment by alexpensify** [comment] 2023-12-29 18:11
Closing - Thank you everyone for your patience here. I've completed the payment process in Upwork and closed this job. Happy New Year! 

@situchan please complete the checklist when you get a chance, thanks!

**Closed by alexpensify** 2023-12-29 18:11 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by situchan** [comment] 2023-12-29 18:14
Happy new year!

We can skip checklist as regression came from theme switching (which won't happen again in the future) and bug was caught by QA team

**Comment by alexpensify** [comment] 2023-12-29 18:19
Noted and thank you.
