### ISSUE TITLE
 Expense - "Next step" message changes when requesting money offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36510] opened 2024-02-14 15:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.41-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Employee is in Collect workspace
- Schedule submit is enabled and set to Daily
1. Go to workspace chat
2. Create a manual request
3. Click on the preview to go to expense report
4. Note that the Next step message is "These expenses are scheduled to automatically submit later today!"
5. Go offline
6. Create another manual request
7. Go to expense report

## Expected Result:
The "Next step" message remains the same, which is "These expenses are scheduled to automatically submit later today!"

## Actual Result:
The "Next step" message changes to "Waiting for x to approve these expenses."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c7cc1d2f-e1d3-42d4-b08e-98a227e77b86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-14 15:19
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by rlinoz** [comment] 2024-02-14 16:37
Hmm, I believe this should be happening in prod as well.

Anyway, maybe @vitHoracek, @rezkiy37 or @allroundexperts can help.

I think it is related to this PR: https://github.com/Expensify/App/pull/34450, specifically this line: https://github.com/Expensify/App/blob/63733d80f28a46d9e9bcaf335cea630060dd2da2/src/libs/actions/IOU.ts#L876

**Comment by Beamanator** [comment] 2024-02-14 16:39
ooh if this is happening in prod, let's call this NAB! Can you confirm @rlinoz ? 🙏

**Comment by rezkiy37** [comment] 2024-02-14 16:43
It is a regressing of this **issue**. I am going to take and fix this.

**Comment by rezkiy37** [comment] 2024-02-14 16:43
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rlinoz** [comment] 2024-02-14 16:45
I think GH failed to link the issue, do you mind linking it?

Also, do you happen to know if this is prod? If it is the PR I linked it is deployed, so this would not be a blocker.

**Comment by rezkiy37** [comment] 2024-02-14 16:48
What's the linking do you mean? It already mentioned this issue - https://github.com/Expensify/App/issues/28771.

**Comment by rlinoz** [comment] 2024-02-14 16:52
Oh I thought the bold *issue* in your comment was supposed to be a link, sorry.

Great, so this seems to be deployed to production and we can the blocker label.

**Comment by mountiny** [comment] 2024-02-14 16:52
This PR is already in production so not a blocker

**Comment by mountiny** [comment] 2024-02-14 16:52
But please do continue with the fix just no need to CP @rezkiy37

**Comment by rezkiy37** [comment] 2024-02-14 16:55
I can confirm that it is deployed. So, it is not a blocker.

https://github.com/Expensify/App/assets/57314631/91191b51-65e5-425f-8f29-e8efc675f684

**Comment by rezkiy37** [comment] 2024-02-14 17:25
Looks like I've found a root cause of the bug. Testing and opening a PR tomorrow.

**Comment by rezkiy37** [comment] 2024-02-16 09:50
@thesahindia, let me clarify:
1. Collect workspace is just a normal workspace right?

No, it is one of type of paid workspaces. You need to use **OD** for creating paid workspaces.

<img width="1728" alt="Screenshot 2024-02-16 at 10 49 08" src="https://github.com/Expensify/App/assets/57314631/cfbe8811-5b4f-4291-af76-b0a8ccf994d2">

2. How can I do that?

You need to use **OD** for managing paid workspaces.

<img width="1598" alt="Screenshot 2024-02-16 at 10 50 09" src="https://github.com/Expensify/App/assets/57314631/0074d6a7-eba5-4de5-8748-b27cca30ddc9">

Does it make sense now?

**Comment by rlinoz** [comment] 2024-03-11 19:51
Hmmm this is in prod already, are we missing something?

**Comment by rlinoz** [comment] 2024-03-12 14:22
Yep, closing then

**Comment by rlinoz** [comment] 2024-04-08 12:53
Sorry about that @thesahindia 

@Christinadobrzyn , @thesahindia was the C+ reviewer for this issue, can you handle payment please?

**Comment by Christinadobrzyn** [comment] 2024-04-09 02:28
Gotcha! Payouts due:

- [ ] Contributor+: $500 @thesahindia (Paid in NewDot)

@thesahindia  you are paid in NewDot, right? Do we need a regression test here?

**Comment by Christinadobrzyn** [comment] 2024-04-10 03:33
Created a regression test for QA to review if we need to add this - https://github.com/Expensify/Expensify/issues/386621

Payment summary here - https://github.com/Expensify/App/issues/36510#issuecomment-2044041976

going to close this out, feel free to reach out if I've missed anything!

**Closed by Christinadobrzyn** 2024-04-10 03:33 UTC
Labels: Reviewing, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-30 23:14
$500 approved for @thesahindia
