### ISSUE TITLE
[$500] IOU-Editing distance request, new message is not shown but for request money, new message shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28478] opened 2023-09-29 13:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money
4. Tap distance
5. Enter start and finish points
6. Tap next and select a workspace
7. Tap show more and enter all fields
8. Tap request amount
9. Tap on distance request and open report page
10. Change amount/date/category and note the changes made message shown below
11. Navigate back to LHN
12. Tap fab-manual
13. Tap request money
14. Enter an amount
15. Select any user
16. Tap request amount
17. Tap IOU transaction to open report page
18. Change merchant/amount /description and save it.
19. Note the changes made messages shown below

## Expected Result:
In changes made messages shown below, the "new message" green line display must be consistent for both request and distance request

## Actual Result:
For editing distance request, "new message" green line is not shown but for request money, "new message" green line is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/da1fcb5a-c60a-4c44-af72-8f8c587f2bdf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162a10f4c446abf35</li>
        <li>Upwork Job ID: 1708383269164470272</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-29 18:09
Reproduced on build 1.3.75.2

https://github.com/Expensify/App/assets/93399543/bb42adac-0330-4433-9d65-6bd5f3b63c42

**Comment by mountiny** [comment] 2023-10-01 07:29
I dont think this needs to be deploy blocker but still something to look at, by the look of things it might be backend issue actually but both edit money request and update distance request modify the expenses in a same way so I am not sure why this shoul dbe different or whether it is reliably reproducible

Making this external so people can look into this

**Comment by alexpensify** [comment] 2023-10-03 23:35
Update: Waiting for proposals here

**Comment by alexpensify** [comment] 2023-10-05 23:45
Update: Waiting for proposals here

**Comment by alexpensify** [comment] 2023-10-11 20:41
Update: Waiting for proposals here but will most likely start asking partners at the end of the week if no movement.

**Comment by mvtglobally** [comment] 2023-10-12 03:44
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2023-10-13 17:15
@mvtglobally I'm confused by your last reply, are you suggesting to close this GH?

**Comment by AndrewGable** [comment] 2023-10-16 20:08
@alexpensify - Can you reproduce? If not let's close.

**Comment by alexpensify** [comment] 2023-10-18 21:59
Tomorrow, I'll run one more test.

**Comment by alexpensify** [comment] 2023-10-20 23:08
I tested and can't replicate -- closing!

**Comment by alexpensify** [comment] 2023-11-09 00:34
I haven't had time to test but will review when I'm back from OOO.

**Comment by alexpensify** [comment] 2023-11-29 19:28
@aimane-chnaif bumping this question again to prepare for proposals, thanks!

**Comment by alexpensify** [comment] 2023-12-01 18:08
@aimane-chnaif any update here?

**Comment by mvtglobally** [comment] 2023-12-08 05:03
Issue not reproducible during KI retests. (Second week)

**Comment by alexpensify** [comment] 2023-12-11 18:42
Daily Update: Still waiting for feedback if we fix this one

**Comment by alexpensify** [comment] 2023-12-13 21:58
Since this has not been reproducible in the latest tests, I'm going to close it out.

**Closed by alexpensify** 2023-12-13 21:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
