### ISSUE TITLE
Chat- Concierge notification email lines overlap

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38066] opened 2024-03-11 17:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open app
2. Start chat with a user you never chatted before

## Expected Result:
User receives a standardized email from Concierge "Hi there! This is your first time chatting with this user....

## Actual Result:
When email is opened on the phone(Gmail App), the text is overlapping with the time the email was received.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6409851_1710173795008!viber_image_2024-03-11_16-04-51-119](https://github.com/Expensify/App/assets/115492554/af56cff7-d01e-46c6-8794-ac9a80ae8fcc)
![Bug6409851_1710173795013!viber_image_2024-03-11_16-04-51-171](https://github.com/Expensify/App/assets/115492554/203318cf-1dde-4bc1-8936-e46c6eb6e459)
![Bug6409851_1710173795008!viber_image_2024-03-11_16-04-51-209](https://github.com/Expensify/App/assets/115492554/1012f621-0557-4cb2-a55c-ec134804c53f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01214179a0b9df8c52</li>
        <li>Upwork Job ID: 1768008917425602560</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rlinoz</details>

**Comment by izarutskaya** [comment] 2024-03-11 17:26
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-11 17:26
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by trjExpensify** [comment] 2024-03-12 14:20
Yep, that's right. @youssef-lr is this bug on your radar from [here](https://github.com/Expensify/Expensify/issues/364323)? Does it also need to be `internal`?

**Comment by youssef-lr** [comment] 2024-03-13 20:18
I think @rlinoz might have more context about this. I think It should be internal yes.

**Comment by youssef-lr** [comment] 2024-03-13 20:22
No C+ needed, this will need a backend change.

**Comment by rlinoz** [comment] 2024-03-13 20:28
Thanks, assigning to this one to myself.

**Comment by rlinoz** [comment] 2024-03-14 21:20
I am not sure if there is a really good solution here

This is what I am getting for mobile, which I think it looks ok:

<img src="https://github.com/Expensify/Web-Expensify/assets/5201282/c93193c2-2707-4da7-890d-5f3e95b0f0f9" width=200px/>
<img src="https://github.com/Expensify/Web-Expensify/assets/5201282/b0688f5b-cbd2-4feb-a7b3-298f5a54d20e" width=200px/>
<img src="https://github.com/Expensify/Web-Expensify/assets/5201282/e5c7a1b2-114a-4400-8ca3-6fec4427d062" width=200px/>
<img src="https://github.com/Expensify/Web-Expensify/assets/5201282/740b7840-2474-45f0-b685-4a7d6569092e" width=200px/>
<img src="https://github.com/Expensify/Web-Expensify/assets/5201282/2f15dc7e-2a97-43b8-99ee-2dc07834a2b5" width=200px/>
<img src="https://github.com/Expensify/Web-Expensify/assets/5201282/bd31c069-84d5-4f30-bf00-01220077804f" width=200px/>


The problem is that in some cases we cut the sender's name too early for desktop, which is not ideal:

<img width="944" alt="image" src="https://github.com/Expensify/App/assets/5201282/d049ce22-1584-44f6-b541-958d235d592b">


Do you have any thoughts on this @shawnborton since you were helping me with the first issue related to this?

**Comment by shawnborton** [comment] 2024-03-15 00:55
Can we truncate the time instead of the name? Or maybe we need a combination of both... going to be hard to do that via CSS in an email client so we might consider truncating the sender name in the code. 

Also, how do we decide to show the full year? I feel like we can omit the full year because the email timestamp would have it. 

We don't really do it consistently in product that I can tell:
![CleanShot 2024-03-14 at 20 54 01@2x](https://github.com/Expensify/App/assets/2319350/86af793d-d192-484a-aab0-701e4721f95f)

Also, shouldn't `concierge@expensify.com` just be Concierge?

**Comment by shawnborton** [comment] 2024-03-15 13:11
> Yeah, I just went with name truncating because that is how we do in product, and even if we truncate the time there will probably be cases where it is not enough.

Cool, works for me!

> The examples above with name truncating are via CSS, do you think there is problem? I think if we truncate in code we may often truncate way more text than needed.

Dang, if you got it to work - then let's do it!

**Comment by rlinoz** [comment] 2024-03-18 12:22
Great, I will open the PR today.

**Comment by rlinoz** [comment] 2024-03-27 12:00
PR got reverted, will get back to it this week.

**Comment by rlinoz** [comment] 2024-04-04 13:59
PR is in prod https://github.com/Expensify/Web-Expensify/pull/41472#issuecomment-2035339210, so closing.

**Closed by rlinoz** 2024-04-04 13:59 UTC
Labels: Reviewing, Daily, Internal, Bug
