### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000]  Inconsistent "Enter" key behavior in Assign task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21205] opened 2023-06-21 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Assign task
2. Click inside the title input field and hit "Enter" key and observe the behavior
3. Go back and click inside the description input field and hit "Enter" key and observe the behavior

## Expected Result: 
The "Enter" key behavior should be consistent for both input fields.
## Actual Result: 
"Enter" key behavior is different for both input fields. When user is inside the title input field the enter key triggers the "Next" button but when inside the description input field the enter key creates a new line. (It would be better if creating a new line is triggered with the "Shift + Enter" key)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.30-0
**Reproducible in staging?:**  y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4368c73e-0e13-46b8-8705-057d399638cf

https://github.com/Expensify/App/assets/43996225/2d097a9e-b24c-49d4-a5d6-7ae2821f5fd1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686812998789659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189b1f49c485f8906</li>
        <li>Upwork Job ID: 1671653984207818752</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-21 14:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent "Enter" key behavior in Assign task

### What is the root cause of that problem?
we are not providing `submitOnEnter` for the description textarea which is causing this behavior and not get submitted the form on enter.

### What changes do you think we should make in order to solve the problem?
We need to pass `submitOnEnter` for the description TextInput.

**Comment by nozadev** [comment] 2023-06-21 23:57
This happens because this autoGrowHeight prop prevents submitting a form, if we add it to `taskTitle` we will get same behaviour 
<img width="700" alt="image" src="https://github.com/Expensify/App/assets/21206256/82fddb03-d008-4a04-b15b-9edc3d0eb949">

**Comment by nozadev** [comment] 2023-06-22 00:03
Digging deeper into `BaseTextInput.js` on line 226 I found this code:

`const isMultiline = this.props.multiline || this.props.autoGrowHeight;`

In the same file on line 342:
`dataSet={{submitOnEnter: isMultiline && this.props.submitOnEnter}}`

Changing `submitOnEnter: true` will submit the form but it also simultaneously creates new line and if title is empty it will show error and make a new line like this:
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/21206256/522a890f-89c0-4130-b424-946e3a40ec2e">

btw I noticed that when I make new line cursor is half cut off height, so it also needs fixing, I will dig deeper and find a good solution.

**Comment by nozadev** [comment] 2023-06-22 00:07
So do what we want?

- make new line on Shift+Enter for both Title and Description (or should we leave Title single line?)
- Submit the form on Enter for both Title and Description

**Comment by nozadev** [comment] 2023-06-22 01:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
description input field the enter key creates a new line. You want to create new line with SHIFT+ENTER and submit/next form just by clicking ENTER

### What is the root cause of that problem?
`autoGrowHeight` prop on TextInput causes input to lose it's default pointer-events functionality which is written in `BaseInput.js` file

### What changes do you think we should make in order to solve the problem?
add 'submitOnEnter' prop to TextInput. But it will make new line if we are focused in `taskDescription` input and cursor's height is cut off. Solution:

- Listen for shift+enter key
- fix styling for textarea when new line is created

**Comment by narefyev91** [comment] 2023-06-22 08:33
Proposal of @Pujan92 https://github.com/Expensify/App/issues/21205#issuecomment-1600901261 makes sense to me - proposal indicates a root case of the issue - and suggested changes should fix current issue
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-06-22 09:42
> @narefyev91 Could you think about [my proposal](https://github.com/Expensify/App/issues/21205#issuecomment-1600985245)? The proposal of @Pujan92 doesn't fix the current issue. We need to add submitOnEnter into
> 
> https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/pages/tasks/NewTaskDetailsPage.js#L102
> 
> 
> to fix the current issue. The proposal of @Pujan92 doesn't mention that

Hey @dukenv0307 - your proposal is the same - that adding submitOnEnter will fix the issue - you pointed out in which files in should be changed including one more file. But the proposal is about adding code which will fix, and not really pointing in which files. Fixing logic is the same for your proposal and for @Pujan92 proposal - he was a first with it. In any case thanks @dukenv0307 will wait your proposals for other issues!

**Comment by narefyev91** [comment] 2023-06-22 10:31
@dukenv0307 i mentioned above my thoughts - in any case the last decision @neil-marcellini. If he will think that your proposal better - he will assign this to you, no worries

**Comment by Pujan92** [comment] 2023-06-22 12:33
Definitely, I was aware of it but somehow I missed the file link in the proposal. But as it is in the same flow it can be understandable and for this, I think root cause with the correct solution matters more. 

> This is https://github.com/Expensify/App/issues/18909#issuecomment-1561728824 where the completed and more valuable proposal is selected instead of the first proposal.

I would prefer to not reference other issues of this type case as we have seen the decision goes in favor of the other way around too for many issues, which depends on the reviewer's perspective.

Anyways, I am fine with whatever the @neil-marcellini decides.

**Comment by neil-marcellini** [comment] 2023-06-23 21:25
@narefyev91 I like @dukenv0307's proposal better because it's more complete.

However, I'm not sure if this is actually a problem. Do we really care if hitting enter in the description field of a task makes a new line? I don't really think so. If we really want to force using shift+Enter to make a new line, then I think hitting only Enter should remove focus from the input, because we usually don't make the form submit on enter. Are you guys good with closing this @lschurr @thienlnam?

**Comment by narefyev91** [comment] 2023-06-26 07:28
> @narefyev91 I like @dukenv0307's proposal better because it's more complete.
> 
> However, I'm not sure if this is actually a problem. Do we really care if hitting enter in the description field of a task makes a new line? I don't really think so. If we really want to force using shift+Enter to make a new line, then I think hitting only Enter should remove focus from the input, because we usually don't make the form submit on enter. Are you guys good with closing this @lschurr @thienlnam?

Everywhere in the app - pressing enter usually submit a form - and i think it should be the same expected behaviour for any form. BTW - i'm fully ok if we will leave as it is :-)

**Comment by neil-marcellini** [comment] 2023-06-26 17:05
Ah ok I see now, thanks for showing the examples that hitting enter in any form submits it. In that case I like @dukenv0307's [proposal](https://github.com/Expensify/App/issues/21205#issuecomment-1600985245).

**Comment by lschurr** [comment] 2023-07-05 17:32
@narefyev91 @dukenv0307 @Nathan-Mulugeta - could you apply for the job in Upwork?

https://www.upwork.com/jobs/~0189b1f49c485f8906

**Comment by lschurr** [comment] 2023-07-05 17:32
@narefyev91 do we need a regression test for this one?

**Comment by Nathan-Mulugeta** [comment] 2023-07-05 17:39
Just applied.

**Comment by jeet-dhandha** [comment] 2023-07-05 19:01
@narefyev91 Please check this. https://github.com/Expensify/App/issues/22284 Might be a difference in user experience or a regression.

**Comment by narefyev91** [comment] 2023-07-06 07:12
> @narefyev91 @dukenv0307 @Nathan-Mulugeta - could you apply for the job in Upwork?
> 
> https://www.upwork.com/jobs/~0189b1f49c485f8906

I'm from Callstack - no needs to do anything with Upwork :-)

**Comment by narefyev91** [comment] 2023-07-06 07:13
> @narefyev91 Please check this. #22284 Might be a difference in user experience or a regression.

@jeet-dhandha i will say that it was a misunderstanding and lack of information based on this comment https://github.com/Expensify/App/pull/21661#issuecomment-1614397623

**Comment by narefyev91** [comment] 2023-07-06 07:13
> @narefyev91 do we need a regression test for this one?

I think really not needed

**Comment by lschurr** [comment] 2023-07-06 18:56
Paid and closed :)

**Closed by lschurr** 2023-07-06 18:56 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by mananjadhav** [comment] 2023-08-07 02:24
@lschurr @neil-marcellini We added enter on submit here. Due to this, when we submit the return key on Android, we submit the form. Hence users cannot enter multiline description as raised https://github.com/Expensify/App/issues/22284.  On desktop and web we can still enter multiline with shift+enter, but not on the mobile devices.

Can we confirm that we do want `Enter` key behavior for all the platforms? or should we solve the linked issue for small screen devices only.


cc - @muttmuure

**Comment by neil-marcellini** [comment] 2023-08-07 16:51
We decided that we want to be consistent and have the enter key submit, as with all other forms. It works well on all the other platforms so I think we should figure out a fix for Android.
