### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Web - User is not navigated to the concierge chat after login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20885] opened 2023-06-16 00:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of NewDot
2. Go to https://staging.new.expensify.com/concierge
3. Verify that you are taken to the login screen
4. Log in to NewDot
5. Verify you're navigated to the concierge chat after login

## Expected Result:
User should be navigated to the concierge chat after login

## Actual Result:
After login, user is navigated to the last chat of his/her last session

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** Yes 

**Reproducible in production?:** No 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2d1dde78-d5ca-4541-83e3-ac6c4e861292

https://github.com/Expensify/App/assets/78819774/c1ad947a-f5a0-4b70-bd7e-87b8be7e844a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195b3719c902bfe8a</li>
        <li>Upwork Job ID: 1669733106684628992</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-06-16 09:27
This seems to be a real blocker.

**Comment by mountiny** [comment] 2023-06-16 09:54
Asked @WoLewicki to have a look

**Comment by mountiny** [comment] 2023-06-16 10:11
And @koko57 too 😄 lets get this fixed

**Comment by mountiny** [comment] 2023-06-16 12:30
No luck?

**Comment by WoLewicki** [comment] 2023-06-16 12:32
The problem comes from how `ReportScreenWrapper` works right now. It sets the `reportID` to the last visited id. The solution would be to set the last visited report to `Concierge` when user signs in. I'm looking for the best place to add it. Do you have an idea where should it be?

**Comment by koko57** [comment] 2023-06-16 14:58
@mountiny My finding so far:
I've tested the app on a revision before this [PR](https://github.com/Expensify/App/pull/20740/files/b03c28529095cd1c8d092f75ef87fad65fe3d9a6) was merged and after merging these changes.

First I've noticed that we don't have a proper id for the concierge chat when calling navigateToConciergeChat [here](https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/libs/actions/Report.js#L1629).

After comparing with the changes before the PR it looks like the Onyx is populated with data before the navigateToConciergeChat - looks like the `SidebarUtils.isSidebarLoadedReady()` is resolved quicker than `Navigation.isReportScreenReady()` 

here are the logs:

before changes
![Screenshot 2023-06-16 at 16 43 43](https://github.com/Expensify/App/assets/28020445/bcbba727-48ff-4f43-a630-83ea1a3a9fd4)

after changes
![Screenshot 2023-06-16 at 16 08 54](https://github.com/Expensify/App/assets/28020445/68629efb-a7e5-48e7-834d-80cbded37654)

So the flow basically looks like this:

- after logging in the Concierge page mounts and the navigateToConciergeChat() is called [here](https://github.com/Expensify/App/blob/d6ddb7e953d596f114171662d32312abe624a498/src/pages/ConciergePage.js#LL35C23-L35C23)
- we don't have the id for the concierge chat ->  we're navigated to the Report page [here](https://github.com/Expensify/App/blob/d6ddb7e953d596f114171662d32312abe624a498/src/libs/actions/Report.js#L1133)
- as the ReportScreen mounts `Navigation.isReportScreenReady()` (in the old revision) and `SidebarUtils.isSidebarLoadedReady()` (in the revision after the PR) are resolved - but it looks like the `SidebarUtils.isSidebarLoadedReady()` is resolved earlier
-  `navigateToConciergeChat()` is called [here](https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/libs/actions/Report.js#L1629) and as we already have the concierge report Id in the case with `Navigation.isReportScreenReady()` we're navigated to the Concierge chat, while in the `SidebarUtils.isSidebarLoadedReady()` we're not

A lot happens here and I hope I explained it as clear as possible 😅 , but if you still have any questions just let me know 🙂

**Comment by AndrewGable** [comment] 2023-06-16 15:45
Demoting to bug per: https://expensify.slack.com/archives/C01GTK53T8Q/p1686927085343139?thread_ts=1686924049.839489&cid=C01GTK53T8Q

**Comment by mountiny** [comment] 2023-06-19 08:07
@WoLewicki @koko57 Could you please review the proposal from @hoangzinh thanks!

**Comment by WoLewicki** [comment] 2023-06-19 08:19
@hoangzinh yeah, it seems very reasonable to just navigate to the route if there is no modal to dismiss. Did you maybe find out why the flow described by @koko57 worked earlier and now it does not work? It might not be too relevant for the issue, but would be nice to know why it happens exactly.

**Comment by koko57** [comment] 2023-06-19 12:03
But can we just update `Navigation.dismissModal` like @hoangzinh proposes? Can it cause any regression?

**Comment by mountiny** [comment] 2023-06-19 13:12
@koko57 @hoangzinh I think we can try it, I cant really think of any regression from this change but we could test the flow. 

@parasharrajat do you agree? I will assign @hoangzinh if so

**Comment by WoLewicki** [comment] 2023-06-19 13:42
Yeah, I also think we should do it. @koko57 can we delay navigating anywhere after sign in until the `reportID` of `Concierge` is resolved? We could then set it as the last visited route or just navigate straight to it.

**Comment by WoLewicki** [comment] 2023-06-20 13:35
Yeah, adding the navigation to the provided route if it is provided and we did not end up in other flows seems reasonable.

**Comment by mountiny** [comment] 2023-06-23 08:55
@parasharrajat any updates? i will be ooo next week so please feel free to handle the discussion and ask someone for help with merging the PR if it will be ready

**Comment by Christinadobrzyn** [comment] 2023-06-26 22:54
Hey @parasharrajat let me know if you'd like to see more proposals or if any of these will work!

**Comment by Christinadobrzyn** [comment] 2023-07-03 17:16
just a quick nudge on this @parasharrajat - thanks!

**Comment by Christinadobrzyn** [comment] 2023-07-06 00:13
@parasharrajat just adding a nudge to keep this GH from going overdue - let me know if you'd like to see more proposals and I can raise the bounty

**Comment by mountiny** [comment] 2023-07-06 00:40
I will ask @koko57 if she has ability to work on this further @hoangzinh could help with review too

**Comment by koko57** [comment] 2023-07-07 13:09
I've checked once again @hoangzinh solution - I navigated to the `targetReportID` [here](https://github.com/Expensify/App/blob/0acd42d05003dde342caa03cd9a3c469a078e0cd/src/libs/Navigation/Navigation.js#L165) instead of just logging the message. It works, but as I've mentioned earlier, the only problem I see here is that we see another's chat avatar for a split of a second before the Concierge report loads. 

https://github.com/Expensify/App/assets/28020445/fb22fdb5-2492-45e9-a84f-ba014fc06b34

For now I can't think of any scenario that @hoangzinh's proposal may cause a problem. I i.e. tried to type a non existing url and I was navigated to the not found page correctly. I wonder what do you guys think of this solution? If this proposal is still not acceptable, I will continue working on this on Monday.

**Comment by koko57** [comment] 2023-07-07 13:19
btw I've found a bug while reproducing this issue: `[Navigation.getReportIDFromRoute()](https://github.com/Expensify/App/blob/0acd42d05003dde342caa03cd9a3c469a078e0cd/src/libs/actions/Report.js#L1180) is not changed to the `getTopmostReportId` and the app crashes when trying to navigate to the Concierge chat. It's because `getReportIDFromRoute` was removed in #21702  I wonder if I should posted as a new ticket or can be fixed here?

**Comment by mountiny** [comment] 2023-07-07 22:58
@koko57 please feel free to post a fix here, are we good to proceed with the proposal from @hoangzinh then?

**Comment by mountiny** [comment] 2023-07-08 20:58
Thanks for the detailed weite up. I think its hard to explore this without actually starting the implementation and testing.

I will assign @hoangzinh and @koko57 as another tester and reviewer in addition to Rajat. @hoangzinh can you please create the pr and test thoroughly all the deeplinks to reports?

**Comment by koko57** [comment] 2023-07-10 10:41
@parasharrajat yeah, I think that @hoangzinh even suggested something like this as [an optional solution](https://github.com/Expensify/App/issues/20885#issuecomment-1595032312)
>  We can add a param option to Report.navigateToAndOpenReport so that we can have option to dismissModal or navigate directly to chatReport [here](https://github.com/Expensify/App/blob/469596a91ad32b9f176ddc35a622cf063a0a2641/src/libs/actions/Report.js#L481)

**Comment by Christinadobrzyn** [comment] 2023-07-13 20:22
Hired in Upwork - job here- https://www.upwork.com/jobs/~0195b3719c902bfe8a

- @hoangzinh as contributor (automatically hired)
- @parasharrajat are you getting paid through NewExpesnify?

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:37
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing the PR and pending for payment.

**Comment by stephanieelliott** [comment] 2023-07-19 07:57
PR is on staging

**Comment by mountiny** [comment] 2023-07-28 12:34
Checklist is not relevant here, this was part of the bigger navigation refactor

@stephanieelliott Are you able to run through the payments? Thanks!

**Comment by stephanieelliott** [comment] 2023-07-28 21:52
Summarizing payments for this issue: 
 - Issue reporter: N/A
 - Contributor: @hoangzinh $1000 (paid via Upwork)
 - Contributor+: @parasharrajat $100 (please request on newdot)

**Closed by stephanieelliott** 2023-07-28 21:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-02 23:44
@stephanieelliott I believe you're missing an extra zero in that summary for @parasharrajat. Is that right?

**Comment by stephanieelliott** [comment] 2023-08-03 00:13
Oops! Sorry, yeah I was missing a `0`. Updated the payment summary! 

> Summarizing payments for this issue:
> 
> - Issue reporter: N/A
> - Contributor: @hoangzinh $1000 (paid via Upwork)
> - Contributor+: @parasharrajat $1000 (please request on newdot)

**Comment by JmillsExpensify** [comment] 2023-08-03 03:17
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
