### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] Inconsistent behavior when copying mentions with different methods

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20814] opened 2023-06-15 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Post a comment with text and a mention
2. Select the posted comment and press CTRL + C to copy it
3. Paste the copied content elsewhere
4. Hover over the posted comment on step 1 and click on copy to clipboard icon
5. Paste the content elsewhere
6. Post a mention comment only and select the posted comment and use ctrl + c to copy the content
7. Compare the contents copied with the above different copy methods

## Expected Result: 
All copy methods should result in the same copied content
## Actual Result: 
When copying a posted comment which has a text and a mention using selection and ctrl + c copy method the content being copied is different from the other methods. The copied content appends this "[]()"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/08cedfda-478b-40e5-ae87-1a48f8f004ad

https://github.com/Expensify/App/assets/43996225/2111ced2-2ad6-43b8-996c-d9e219bcbd63

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1686818464264869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a3e659d43c036c7</li>
        <li>Upwork Job ID: 1669428313148706816</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-06-15 14:06
While this does seem to be a regression, I really don't think it's bad enough to block the already very long deploy. I looked through the [checklist](https://github.com/Expensify/App/issues/20782), but nothing stood out as an obvious cause.

**Comment by dan1d** [comment] 2023-06-15 16:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When copying a posted comment which has a text and a mention using selection and ctrl + c copy method the content being copied is different from the other methods. The copied content appends this ""

### What is the root cause of that problem?

this is the root cause: [https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.js#L173](https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.js#L173) when selecting text the `content` its mixed between html and markdown

When selecting the text `content` gets set as html
![image](https://github.com/Expensify/App/assets/3293616/0a10abd9-e6fa-4c25-8ced-c3a8d4b9cb9c)

When you don't select anything and copy to clipboard you'll see that content gets set as  markdown style:
![image](https://github.com/Expensify/App/assets/3293616/f0e4f8e1-d78a-475a-a0ae-b438b0f64448)

### What changes do you think we should make in order to solve the problem?
we need to parse the html here: [https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.js#L177](https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.js#L177) in a way that `content` gets the same output when writting to the clipboard

### What alternative solutions did you explore? (Optional)
No

**Comment by dan1d** [comment] 2023-06-15 16:52
Contributor details
Your Expensify account email: danielfromarg@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012f00923e496a3daf

**Comment by isabelastisser** [comment] 2023-06-20 14:57
@sobitneupane, to confirm, are we waiting for proposals?

**Comment by sobitneupane** [comment] 2023-06-21 03:44
> @sobitneupane, to confirm, are we waiting for proposals?

@isabelastisser Nope.

This is a regression from https://github.com/Expensify/App/pull/20447 and fixed by https://github.com/Expensify/App/pull/20894.

cc: @tienifr @eVoloshchak

**Comment by isabelastisser** [comment] 2023-06-23 20:14
I will be OOO until July 5, so assigning another team member. [SO ](https://stackoverflowteams.com/c/expensify/questions/8836)for reference.

**Comment by Julesssss** [comment] 2023-06-26 10:22
Not overdue. We're waiting on payment

**Comment by Julesssss** [comment] 2023-06-30 08:16
@michaelhaxhiu ready for payment

**Comment by michaelhaxhiu** [comment] 2023-06-30 16:16
So, the payment owed is just the bug reporting bonus it seems? (for @Nathan-Mulugeta)

**Comment by michaelhaxhiu** [comment] 2023-06-30 17:41
Invited Nathan to accept the job offer for bug reporting bonus.

**Comment by Nathan-Mulugeta** [comment] 2023-06-30 17:42
Just accepted the offer @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2023-06-30 17:44
paid.

**Closed by michaelhaxhiu** 2023-06-30 17:44 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
