### ISSUE TITLE
[HOLD for payment 2022-11-30] [$250] FaceTone selector does not highlight the current selected value on web reported by @parasharrajat 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12804] opened 2022-11-17 00:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in to the app on web.
2. Open any report.
3. Go to composer and click on the EmojiPicker.
4. Click on the face tone changer :raised_hand_with_fingers_splayed: .
5. Observe that there current tone is not highlighted.

## Expected Result: 
Current tone is highlighted in the facetone selector on the EmojiPicker.

## Actual Result: 
Current tone is not highlighted in the facetone selector on the EmojiPicker on WEB.  But Native app has it.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.28-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Screenshot 2022-11-17 00_00_59](https://user-images.githubusercontent.com/43996225/202323992-17d8f1ee-7183-4ae1-819f-c2431ac86218.png)
<img width="960" alt="1" src="https://user-images.githubusercontent.com/43996225/202324009-ad4fb0b8-064b-4662-9b85-33de8b00f25a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668624156359639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-11-17 00:27
Taking this since I'm on the tracking issue.

**Comment by JmillsExpensify** [comment] 2022-11-17 04:40
This is a clear issue and reproducible, so I'm going to go ahead and get the Upwork posting kicked off and open this up for external contributors.

**Comment by JmillsExpensify** [comment] 2022-11-17 04:45
We're open for proposals: https://www.upwork.com/jobs/~01261110e4fdea977f. 

cc @stitesExpensify for 👀 when you get back.

**Comment by Pujan92** [comment] 2022-11-17 07:13
**Proposal**

I think we required an extra condition where we highlight the skinTon if it is the selectedEmoji skinton.

https://github.com/Expensify/App/blob/c1bb6784b890efe139e70fc4062648843b2e47a0/src/components/EmojiPicker/EmojiSkinToneList.js#L86-L93

condition to add on line 92 `|| skinToneEmoji.skinTone === selectedEmoji.skinTone`

**Comment by CosminnB** [comment] 2022-11-17 07:21
**Proposal**

Add an additional state that will store the selected skin tone index and use it to highlight the correspondent skin tone:

```javascript
 this.state = {
            highlightedIndex: -1,
            selectedIndex: -1,
            isSkinToneListVisible: false,
        };


<EmojiPickerMenuItem
   onPress={() => this.updateSelectedSkinTone(skinToneEmoji)}
   onHoverIn={() => this.setState({highlightedIndex: skinToneEmoji.skinTone})}
   onHoverOut={() => this.setState({highlightedIndex: -1})}
   key={skinToneEmoji.code}
   emoji={skinToneEmoji.code}
   isHighlighted={ skinToneEmoji.skinTone === this.state.highlightedIndex
                  || skinToneEmoji.skinTone === `this.state.selectedIndex}/>
```


https://user-images.githubusercontent.com/59282077/202381185-9047e7f1-5b93-4e5f-897f-b864a4812779.mp4

**Comment by CosminnB** [comment] 2022-11-17 20:56
From what I see, it's working, but as you're using highlightedIndex for both the hover effect and selected, the index changes immediatly when you put your mouse over one of the other skin tones.

**Comment by francoisl** [comment] 2022-11-17 22:15
@Pujan92's proposal makes sense to me and seems like the most straightforward – what are your thoughts @rushatgabhane ?

**Comment by Pujan92** [comment] 2022-11-18 01:20
> From what I see, it's working, but as you're using highlightedIndex for both the hover effect and selected, the index changes immediatly when you put your mouse over one of the other skin tones.

Yes, as native app doesn't have hover effect this issue won't persist there.

**Comment by Pujan92** [comment] 2022-11-18 06:42
Ok, Thanks.
I have submitted the proposal in upwork job.

**Comment by JmillsExpensify** [comment] 2022-11-18 08:06
Ok great, I assigned @Pujan92 to the issue. I've also invited/hired both contributors in the related GH issue.

**Comment by JmillsExpensify** [comment] 2022-11-22 05:26
Nice work here. Based on what I'm seeing, the linked PR is eligible for the 50% bonus since it was merged within 3 business days. Is that right @francoisl? If so, I'll issue the bonus as part of final payment when this PR is successfully deployed and the regression period passes.

**Comment by francoisl** [comment] 2022-11-22 18:27
Yes I think you're correct, it's eligible for the bonus!

**Comment by Pujan92** [comment] 2022-11-24 13:27
Thanks :)

**Comment by JmillsExpensify** [comment] 2022-11-26 21:26
Following up on this issue, it looks like our automated Github bot is broken as the linked PR hit production 3 days ago. Accordingly, I'm going to update the title to reflect that payment should be issued on 11-29-22.

**Comment by Pujan92** [comment] 2022-11-30 17:22
@JmillsExpensify Do I expect this today?

**Comment by JmillsExpensify** [comment] 2022-11-30 22:44
Yep you sure can. It's on my list.

**Comment by Pujan92** [comment] 2022-12-01 03:51
> Yep you sure can. It's on my list.

Great, Thanks. :)

**Comment by JmillsExpensify** [comment] 2022-12-01 04:54
Ok I'm circling back to close this out today. Here's where we landed:

 - ✅ Contributor: @Pujan92 $500 (includes the 50% bonus)
 - ✅ Contributor+: @rushatgabhane $500 (includes the 50% bonus)
 - Issue reporter: @parasharrajat $250 (offer sent)

I'll keep this issue open until @parasharrajat accepts for the bug report. Then we should be good here. Thanks all!

**Comment by JmillsExpensify** [comment] 2022-12-01 13:13
Also whoops, my mistake. The correct amounts should be:

 - ✅ Contributor: @Pujan92 $375 (includes the 50% bonus)
 - ✅ Contributor+: @rushatgabhane $375 (includes the 50% bonus)
 - Issue reporter: @parasharrajat $250 (offer sent)

However the bonuses are my mistake, so I won't be asking for a refund on those. We're working on payments being automated and I can't wait!

**Comment by Pujan92** [comment] 2022-12-01 13:15
Yes, how about adjusting it in the other task? I will remind you in the next task payment.

**Comment by JmillsExpensify** [comment] 2022-12-01 15:25
Feel free to remind me in a future task. Let's focus on closing more bugs in the meantime! Everyone is paid out now. Closing.

**Closed by JmillsExpensify** 2022-12-01 15:25 UTC
Labels: Reviewing, External, Daily, Bug
