### ISSUE TITLE
[$1000] Sigin - Console error when opening a chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20448] opened 2023-06-08 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat

## Expected Result:
No console error when opening a chat

## Actual Result:
Console error when opening a chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.4

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (57)](https://github.com/Expensify/App/assets/93399543/a79cc00f-275a-4038-8fed-aa9884a02cfc)
![image (56)](https://github.com/Expensify/App/assets/93399543/05743bb9-be42-4333-9f7b-c284512529ca)

**Expensify/Expensify Issue URL:**

**Issue reported by:** bernhardoj

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686028265538889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152de705a953964b4</li>
        <li>Upwork Job ID: 1668483253988036608</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-08 12:36
I think @spcheema working on it as it occurs after their [PR](https://github.com/Expensify/App/pull/20147).

**Comment by situchan** [comment] 2023-06-08 12:41
Also there's another console error with `cursorPointer` key. It has the same root cause and should be fixed here.

**Comment by tjferriss** [comment] 2023-06-13 05:00
I'm not able to reproduce as I don't have a mobile dev environment with access to the console. @sobitneupane or @robertjchen are either of you able to reproduce the bug?

**Comment by spcheema** [comment] 2023-06-13 05:15
@tjferriss It's not reproducible on prod. It's console warning which block the build. https://github.com/Expensify/App/pull/20462 to fix some other warnings. Lemme know if there is a need to fix this one as well.

**Comment by situchan** [comment] 2023-06-13 07:31
`textUnderlinePosition`, `textDecorationSkipInk` console errors are gone but `cursor` error still remaining. It happens on `ReportPreview` component.
Reproducible step: request money on any chat

![console](https://github.com/Expensify/App/assets/108292595/538b4a6c-038d-40f9-99c8-bdecafcd8f10)

**Comment by sobitneupane** [comment] 2023-06-13 08:27
Thanks for the proposal @situchan. Removing [cursorPointer](https://github.com/Expensify/App/blob/4cad2489f6feb5efb955924764711a0c36439f58/src/styles/styles.js#L2694-L2696) solves one warning but following warning still remains.

<img width="300" alt="Screenshot 2023-06-13 at 14 08 37" src="https://github.com/Expensify/App/assets/25876548/30f9f162-f6fd-499a-93d4-f2e8517fff15">

**Comment by spcheema** [comment] 2023-06-13 08:44
# Proposed solution 

### Please re-state the problem that we are trying to solve in this issue.
Getting console error `Failed prop type: Invalid prop `styles` of type `object` supplied to `PressableWithoutFocus`, expected an array`
 

**What is the root cause of that problem?**
Style property of `PressableWithoutFocus` component expect array but an object is .

Following code in 3 files

```javascript
      <PressableWithoutFocus
                                                style={styles.noOutline}
                                                onPress={show}
                                            >
```

Files are 

- `src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js`
- src/pages/DetailsPage.js
- src/pages/ProfilePage.js


**What changes do you think we should make in order to solve the problem?**

Update code as below

```JSX

  <PressableWithoutFocus
        style={[styles.noOutline]}
        onPress={show}
    >
    
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by spcheema** [comment] 2023-06-13 08:45
@sobitneupane There was another issue created to fix `cursor` pointer issue. This solution is only for `PressableWithoutFocus` component. Happy to consider `cursor` issue as well if it's still there.

**Comment by situchan** [comment] 2023-06-13 09:24
> Thanks for the proposal @situchan. Removing [cursorPointer](https://github.com/Expensify/App/blob/4cad2489f6feb5efb955924764711a0c36439f58/src/styles/styles.js#L2694-L2696) solves one warning but following warning still remains.
> 
> <img alt="Screenshot 2023-06-13 at 14 08 37" width="300" src="https://user-images.githubusercontent.com/25876548/245406679-30f9f162-f6fd-499a-93d4-f2e8517fff15.png">

This is already known and being fixed somewhere - https://github.com/Expensify/App/pull/19545#discussion_r1225052172

**Comment by sobitneupane** [comment] 2023-06-13 10:46
Yup @situchan.`PressableWithoutFocus` warning is already being fixed in https://github.com/Expensify/App/pull/20202.

The warning in cursor can be fixed by @situchan's [proposal](https://github.com/Expensify/App/issues/20448#issuecomment-1582470865). 

> There was another issue created to fix cursor pointer issue.

@spcheema Can you please link the issue?

**Comment by sobitneupane** [comment] 2023-06-19 04:12
@situchan Is the issue still reproducible?

**Comment by situchan** [comment] 2023-06-19 04:58
> @situchan Is the issue still reproducible?

yes still

**Comment by sobitneupane** [comment] 2023-06-19 08:24
[Proposal](https://github.com/Expensify/App/issues/20448#issuecomment-1582470865) from @situchan looks good to me.

🎀 👀 🎀 C+ reviewed
cc: @robertjchen

**Comment by situchan** [comment] 2023-06-19 08:49
@spcheema can you please link that PR? [This](https://github.com/Expensify/App/issues/20448#issuecomment-1588710615) is still reproducible on main

**Comment by sobitneupane** [comment] 2023-06-21 05:16
Following console warning on opening chat.

<img src="https://github.com/Expensify/App/assets/25876548/ea71f8d2-be34-4c0c-af47-a89802e0e3f9" width="350" >

**Comment by sobitneupane** [comment] 2023-06-21 05:22
@parasharrajat Can you please link the issue and PR which fixed it?

**Comment by sobitneupane** [comment] 2023-06-21 05:27
Oops Sorry @situchan. The solution is already implemented. Thanks for the [proposal](https://github.com/Expensify/App/issues/20448#issuecomment-1582470865) though.

**Comment by sobitneupane** [comment] 2023-06-23 03:31
@tjferriss We should be good to close this issue.

**Closed** 2023-06-23 21:33 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
