### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500]  IOU - Unable to dismiss error message in combined report by clicking X button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39420] opened 2024-04-02 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Request money from User B (no unsettled IOU)
3. [User A] Go to combined IOU report > Click Amount
4. [User B] Pay the request
5. [User A] Edit the amount
6. [User A] Click X to dismiss the error message

## Expected Result:
The error message is dismissed

## Actual Result:
Unable to dismiss the error message by clicking X button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9576a7a1-d27e-4dad-93fc-eb9858ae4189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f33b86436968b4d0</li>
        <li>Upwork Job ID: 1775220715733753856</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-02 16:21
@yuwenmemon  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-02 16:21
We think that this bug might be related to #vip-vsp

**Comment by yuwenmemon** [comment] 2024-04-02 17:53
I wouldn't consider this a deploy blocker. Going to remove the label.

**Comment by yuwenmemon** [comment] 2024-04-02 17:56
There also seem to be a _lot_ of issues in that video. But I think the specific inability to close out an error with the 'X' button would be external.

**Comment by nkdengineer** [comment] 2024-04-02 18:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to dismiss the error message by clicking X button

### What is the root cause of that problem?
After this PR https://github.com/Expensify/App/pull/36934, all actions of transaction thread report are displayed in expense report if we only one transaction. 

When we click on x button, the `originalReportID` is returned as expense report so the error isn't cleared because this action is still stored in transaction thread report in Onyx.

https://github.com/Expensify/App/blob/5986481cb12b3160bc261c4850eb82293b16bf35/src/libs/actions/ReportActions.ts#L12
### What changes do you think we should make in order to solve the problem?
We should check this case in `getOriginalReportID`, if the report is oneTransactionReport we will check if current action isn't  present in the expense report we will return the transactionThreadReportID.

```
if (isOneTransactionReport(reportID)) {
    const currentReportAction = ReportActionsUtils.getReportAction(reportID, reportAction?.reportActionID ?? '');
    const reportActions = reportActionsByReport?.[reportID] ?? ([] as ReportAction[]);
    return Object.keys(currentReportAction ?? {}).length === 0 ? ReportActionsUtils.getOneTransactionThreadReportID(reportActions) : reportID;
}
```

https://github.com/Expensify/App/blob/5986481cb12b3160bc261c4850eb82293b16bf35/src/libs/ReportUtils.ts#L4962


I also see that, we are getting `reportActions` wrong here makes `isOneTransactionReport` is always return false. We should fix this to use this function as well

```
const reportActions = reportActionsByReport?.[reportID] ?? ([] as ReportAction[]);
```
https://github.com/Expensify/App/blob/5986481cb12b3160bc261c4850eb82293b16bf35/src/libs/ReportUtils.ts#L1271-L1274


### What alternative solutions did you explore? (Optional)
NA

**Comment by yuwenmemon** [comment] 2024-04-02 18:14
@NikkiWines I see there were several bugs from https://github.com/Expensify/App/pull/36934 - are there plans to revert? Or does the above solution look sufficient?

**Comment by NikkiWines** [comment] 2024-04-02 21:07
no plans to revert, handling them individually as they pop up. Looking at the proposal now

**Comment by NikkiWines** [comment] 2024-04-02 21:14
@nkdengineer's proposal looks good 👍

**Comment by NikkiWines** [comment] 2024-04-03 02:49
In the interest of getting this resolved quickly going to assign @nkdengineer

**Comment by nkdengineer** [comment] 2024-04-03 03:01
Will raise the PR in a few hours.

**Comment by nkdengineer** [comment] 2024-04-03 04:09
@Santhosh-Sellavel The PR is [here](https://github.com/Expensify/App/pull/39474) cc @NikkiWines.

**Comment by adelekennedy** [comment] 2024-04-17 22:51
ah - I accidentally invite dyou to apply to the job @nkdengineer I just sent you a manual offer. Once you accept I'll end it and pay it out immediately

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 18:32
@adelekennedy 
Not sure why payment was mentioned incorrectly in automated summary.  May be we cut default fee to $250 from $500.
But this was completed before the change so I think payment should be $500.

So Requested $500 on New Dot!
cc: @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-05-31 04:33
Re-opening for payment summary

**Comment by adelekennedy** [comment] 2024-05-31 04:43
ah sorry @Santhosh-Sellavel I just double checked the dates for these changes and this should be $500 @JmillsExpensify just updated the payment summary!

**Comment by JmillsExpensify** [comment] 2024-05-31 17:33
$500 approved for @Santhosh-Sellavel

**Comment by nkdengineer** [comment] 2024-08-23 07:03
@JmillsExpensify We can close this issue now.

**Closed** 2024-08-23 14:08 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
