### ISSUE TITLE
Sign in - Magic code is not come

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50210] opened 2024-10-04 08:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open application or web staging.new.expensify.com
2. Emter email
3. Click continue
4. Check your mailbox

## Expected Result:
Email with magic code received.

## Actual Result:
No email received.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a9a5eea1-a3c8-420c-baa4-928ce35933a6

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-04 08:35
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by techievivek** [comment] 2024-10-04 10:17
I am just closing this since another contributor just confirmed that they have received the OTP.

**Closed by techievivek** 2024-10-04 10:17 UTC
Labels: Daily, Bug
