### ISSUE TITLE
[$500] Web - Error doesn't disappear for a while after deleting entire max exceed message.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27698] opened 2023-09-18 16:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report.
2. Paste a message that has over 15,000 characters. Notice now the Composer has red border with the error below.
3. Delete entire message.
4. Notice that Composer still has error for a while after deleting message.

## Expected Result:
Error should disappear right after user deleted the message.

## Actual Result:
Composer still has error for a while after deleting message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/35cd051c-b1a3-4165-b3b6-58fe7315eee3

https://github.com/Expensify/App/assets/93399543/b6796f2e-1b24-4ace-8f2c-04f053b20700

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694937014673629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bef70e1146af3c78</li>
        <li>Upwork Job ID: 1713723076177219584</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment] 2023-09-18 17:03
## Proposal
## Please re-state the problem that we are trying to solve in this issue.
After deleting the comment the max length error still persist.

## What is the root cause of that problem?
https://github.com/Expensify/App/blob/d848eabee0042afd53007bafe3f2406d9c44b210/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L239-L242

commentLength for an empty comment is 0 that is why it returned from the function completely and unable to execute the function further.

## What changes do you think we should make in order to solve the problem?

Just need to pass one more condition like

```javascript
    if (trimmedComment!=""&&!commentLength || commentLength > CONST.MAX_COMMENT_LENGTH) {
            return '';
        }
``` 
## What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2023-09-18 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Error doesn't disappear for a while after deleting entire max exceed message.

### What is the root cause of that problem?
- Currently, the border error is display based on ```hasExceededMaxCommentLength```
- ```hasExceededMaxCommentLength``` is set by debounce function ```updateCommentLength(comment,onExceededMaxCommentLength) - delay 500ms``` and the ```comment``` params is get from the ```ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT``` that is also updated by the debounce function
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/components/ExceededCommentLength.js#L29-L41
- It leads to after clearing all the input, it will delay for a while after removing the border error
### What changes do you think we should make in order to solve the problem?
- We can get the ```comment``` param from the ```value``` state inside the ```<ComposerWithSuggestions />``` component rather than the ```ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT``` and also we can call the ```updateCommentLength(comment,onExceededMaxCommentLength)``` without delay. These two method can decrease the delay time that lead to the bug. So the updateCommentLength will be:
```
 const updateCommentLength = useCallback((comment, onExceededMaxCommentLength) => {
        const newCommentLength = ReportUtils.getCommentLength(comment);
        setCommentLength(newCommentLength);
        onExceededMaxCommentLength(newCommentLength > CONST.MAX_COMMENT_LENGTH);
    }, [ ]);
```
- Note: We can consider to choose one of these two method to decrease the delay time or both  of them
### What alternative solutions did you explore? (Optional)
- NA

### Result
[Screencast from 19-09-2023 00:20:01.webm](https://github.com/Expensify/App/assets/141406735/b7254f3e-65f7-4ffc-884d-5c112a6b3fbf)

**Comment by kevin-williams** [comment] 2023-09-20 23:02
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**

Error doesn't disappear for a while after deleting entire comment when it has exceeded the maximum message

**What is the root cause of that problem?**

Two problems:
1. The ExceedCommentLength checker is getting the debounced value after the report draft is saved, so there is a 1 second delay.
2. The debounce should only happen on setting the error, but you have the 500ms delay on the debounce of the value going back to good again.

**What changes do you think we should make in order to solve the problem?**

Three changes:

1. update ComposerWithSuggestions.js so that it exposes the trimmed value of the editor, so added getTrimmedComment function in the ref.

`    const **getTrimmedComment** = () => commentRef.current.trim();

    ...
    
    useImperativeHandle(
        forwardedRef,
        () => ({
            blur,
            focus,
            replaceSelectionWithText,
            prepareCommentAndResetComposer,
            isFocused: () => textInputRef.current.isFocused(),
            **getTrimmedComment**
        }),
        [blur, focus, prepareCommentAndResetComposer, replaceSelectionWithText, useImperativeHandle(
        forwardedRef,
        () => ({
            blur,
            focus,
            replaceSelectionWithText,
            prepareCommentAndResetComposer,
            isFocused: () => textInputRef.current.isFocused(),
            getTrimmedComment
        }),
        [blur, focus, prepareCommentAndResetComposer, replaceSelectionWithText, **getTrimmedComment**],
    );],
    );
`
2. ReportActionCompose - pass in comment={composerRef.current && composerRef.current.getTrimmedComment() || ''} instead of the reportID so it operates on the text being edited (real time updates)

3.  ExceededCommentLength - update the use effect to short circuit the debounce when the error is fixed, but keep the debounce when checking for an error.

` useEffect(() => {
        const propsCommentLength = ReportUtils.getCommentLength(props.comment);
        // Short circuit if the error is removed
        if (propsCommentLength <= CONST.MAX_COMMENT_LENGTH) {
            setCommentLength(propsCommentLength);
            props.onExceededMaxCommentLength(false);
        } else {
            // Debounce the change when checking for an error
            updateCommentLength(props.comment, props.onExceededMaxCommentLength);
        }
    }, [props.comment, props.onExceededMaxCommentLength, updateCommentLength]);
`

This code is currently working in my local repo and the red border and line count exceeded message are removed immediately.

It also works when editing a comment, not just composing a new one.

**Comment by jliexpensify** [comment] 2023-09-21 22:55
Bumping @sobitneupane for reviews!

**Comment by sobitneupane** [comment] 2023-09-25 09:39
Thanks for your proposal @DylanDylann 

> We can get the comment param from the value state inside the <ComposerWithSuggestions /> component rather than the ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT 

Where are you suggesting to make the change? Will it affect if we have existing draft comment?

> also we can call the updateCommentLength(comment,onExceededMaxCommentLength) without delay

I don't think we can do that. This change was made to improve performance and was intended.

**Comment by sobitneupane** [comment] 2023-09-25 09:42
If we fail to identify a straightforward and direct solution, I believe it may be appropriate to consider closing the issue

**Comment by DylanDylann** [comment] 2023-09-25 09:53
@sobitneupane 
> Where are you suggesting to make the change? Will it affect if we have existing draft comment?
- Currently, we get the comment from the draft and the draft value is updated with the delay 1000ms: https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/components/ExceededCommentLength.js#L54-L58

**Comment by DylanDylann** [comment] 2023-09-25 10:18
@sobitneupane 

> I don't think we can do that. This change was made to improve performance and was intended.

- Now with the change here https://github.com/Expensify/App/pull/24319, we do not the commentLength state, just need to know the input `s length is > 10.000 or not, so we can remove [commentLength, setCommentLength]
- The logic https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/components/ExceededCommentLength.js#L27-L45 can become:
```
    const updateCommentLength = useMemo(
        () =>
            debounce((comment, onExceededMaxCommentLength) => {
                const newCommentLength = ReportUtils.getCommentLength(comment);
          
                onExceededMaxCommentLength(newCommentLength > CONST.MAX_COMMENT_LENGTH);
            }, CONST.TIMING.COMMENT_LENGTH_DEBOUNCE_TIME),
        [],
    );

    useEffect(() => {
        updateCommentLength(props.comment, props.onExceededMaxCommentLength);
    }, [props.comment, props.onExceededMaxCommentLength, updateCommentLength]);

    if (!props.hasExceededMaxCommentLength) {
        return null;
    }
```
- In the above change, the hasExceededMaxCommentLength state only changes when the input`s length exceeds 10.000 so it does not affect the performance

**Comment by kevin-williams** [comment] 2023-09-25 18:37
> @sobitneupane

My solution does not change any of the delays on saving the report in onyx or in setting the error, but it does remove the error immediately by short circuiting the debounce check and directly checking the changed form value rather than the debounced saved report value.

**Comment by jliexpensify** [comment] 2023-09-28 03:10
Bump @sobitneupane to address comments

**Comment by sobitneupane** [comment] 2023-10-02 09:04
Sorry for the delay everyone. I was on leave most of the days last week.

@DylanDylann I haven't understood your proposal completely. Would you mind updating your initial proposal to include the changes you are suggesting? Please try to make use of references and permalink from the app to make the keywords used clearer. Also make use of pseudo codes if necessary.

**Comment by DylanDylann** [comment] 2023-10-02 09:22
@sobitneupane just updated my proposal https://github.com/Expensify/App/issues/27698#issuecomment-1724044938 for more clarity.

**Comment by jliexpensify** [comment] 2023-10-03 04:14
Not overdue, waiting on Sobit's review.

**Comment by kevin-williams** [comment] 2023-10-03 07:20
@sobitneupane I updated my proposal above https://github.com/Expensify/App/issues/27698#issuecomment-1728532313  after doing some testing.   I realized it was only removing the red border when the focus was lost or if you cut out all the text.  I modified it so now it does real time removal of the error as you type.

With this solution you could also remove the debounce of the value on setting the error so the user gets immediate feedback if desired, but without changing the report saving delay in onyx.

Here is a video of it working.

https://github.com/Expensify/App/assets/11356566/3ccd3170-92c5-4916-9afc-12032cfe4d09

**Comment by kevin-williams** [comment] 2023-10-03 14:59
@sobitneupane Tested on IOS and Android and I'm going to retract my proposal.   The ReportUtils.getCommentLength(props.comment) call is too expensive (900 ms to 3000ms per call) to be called any more than it already is, especially in the mobile world.  And the output of this call exceeds the length of props.comment in many cases, so you can't shortcut by checking if props.comment is less than the max length.

To properly solve this issue would require reworking the whole system which is probably not worth it given the minor nature of this bug.   All the solutions I've looked at can solve the issue, but at the expensive of making normal typing slow and sometimes laggy so that the normal usage is bad to save a minor inconvenience.

**Comment by jliexpensify** [comment] 2023-10-06 03:58
Bump @sobitneupane to address the above!

**Comment by sobitneupane** [comment] 2023-10-09 11:41
Sorry for the delay.

I will try to review the proposals before EOD tomorrow (NPT).

**Comment by sobitneupane** [comment] 2023-10-10 07:58
@DylanDylann Thanks for the update. We need to implement the solution not only in `ReportActionCompose` but also in `ReportActionItemMessageEdit` which doesn't make use of `ComposerWithSuggestions`. 

I don't think we can go with the 2nd option as I have already mentioned that it will deteriorate the performance of Composer.

**Comment by sobitneupane** [comment] 2023-10-10 08:00
Thanks for the update @kevin-williams. Appreciate your help.

**Comment by DylanDylann** [comment] 2023-10-10 12:17
@sobitneupane 
> We need to implement the solution not only in ReportActionCompose but also in ReportActionItemMessageEdit

We can do the same with ReportActionItemMessageEdit because ReportActionItemMessageEdit also uses the ```reportActionsDrafts_``` collection to store the draft edit message and it still update with a 1000ms delay like the message composer

**Comment by sobitneupane** [comment] 2023-10-11 10:55
> We can do the same with ReportActionItemMessageEdit because ReportActionItemMessageEdit also uses the `reportActionsDrafts_` collection to store the draft edit message and it still update with a 1000ms delay like the message composer

Do you mean to add `ComposerWithSuggestions` in ReportActionItemMessageEdit as well? I don't think that's a good idea. Primary function of `ComposerWithSuggestions` is to show suggestions which we don't support for Message Edit.

**Comment by DylanDylann** [comment] 2023-10-11 11:01
@sobitneupane No. In my proposal, I suggest that we should get the message input length directly rather than get it from the draft, which is updated with a 1000ms delay. So with the edit message input, we can do the same. ```ComposerWithSuggestions``` component is not mentioned in my proposal as well

**Comment by DylanDylann** [comment] 2023-10-11 11:24
@sobitneupane No. My proposal suggests that: Rather than get the message composer's length from the draft which is updated with 1000 ms delay, we should get the message composer`s length from the message composer`s content directly. So we can do the same with message edit logic.
- But I just checked the current edit message`s logic, the behavior is slightly different from the message composer logic: The message composer error is updated with ~1500 ms delay, but the message edit is only ~ 500 ms. 
- As the RCA mentioned in my proposal, there are two factors led to the delay (with the message composer):

> hasExceededMaxCommentLength is set by debounce function updateCommentLength(comment,onExceededMaxCommentLength) - delay 500ms and the comment params is get from the ONYXKEYS.COLLECTION.REPORT_DRAFT_COMMENT that is also updated by the debounce function (1000ms)

And the message edit only encounter the case ```hasExceededMaxCommentLength is set by debounce function updateCommentLength(comment,onExceededMaxCommentLength) - delay 500ms```

**Comment by sobitneupane** [comment] 2023-10-13 09:50
@jliexpensify I will be unavailable next week. Therefore, I am unassigning myself from the issue. Please feel free to assign it to another C+.

**Comment by jliexpensify** [comment] 2023-10-16 01:07
@Ollyws could you take over from Sobit here and review the proposals? Thanks!

**Comment by creativework12** [comment] 2023-10-16 01:37
a

**Comment by creativework12** [comment] 2023-10-16 01:43
Contributor details
Your Expensify account email: lazarstanoje23@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0151cbdfcca474c09b

**Comment by jliexpensify** [comment] 2023-10-17 01:26
Yeah after having a think about it, I'm inclined to agree with you @Ollyws - I'm fine with closing this. Thank you for re-reviewing here!

**Comment by DylanDylann** [comment] 2023-10-17 02:13
@jliexpensify  Agree that the case user type exceeds 10000 words is the edge case. But I think we need to fix this issue because:
- Currently, we are not displaying the text`s length that the user inputted. We are just displaying "The maximum comment length is 10.000 characters." rather than "10.002/10.000" as we did before.

- So there is the case that the user inputted 10.002 characters, the border error appeared, and they need to remove any 2 characters. But because the border error is updated with a 1500ms delay, and we are not displaying the current input`s length - just "The maximum comment length is 10.000 characters." , it is difficult for users to edit their input to decrease their input`s length

**Comment by jliexpensify** [comment] 2023-10-17 02:47
Going to re-open for @Ollyws to review further

**Comment by jliexpensify** [comment] 2023-10-18 00:19
@Ollyws any further input here?

**Comment by jliexpensify** [comment] 2023-10-22 22:21
Bumping @Ollyws !

**Comment by DylanDylann** [comment] 2023-10-30 11:19
@Ollyws my proposal have two options to remove the debounce: One option can reduce 1000ms and another is 500ms. Combine both can reduce all the debounce

**Comment by DylanDylann** [comment] 2023-10-30 11:23
@Ollyws you can take a look at my proposal and feel free to ask more question about it. Thanks

**Comment by DylanDylann** [comment] 2023-10-30 11:47
@Ollyws 
> As far as I can see the only part of your proposal that could be implemented would be method 1, but there were these unresolved comments about that:
 > @DylanDylann Thanks for the update. We need to implement the solution not only in ReportActionCompose but also in ReportActionItemMessageEdit which doesn't make use of ComposerWithSuggestions.

I `ve commented in https://github.com/Expensify/App/issues/27698#issuecomment-1757469087. Please help check it

**Comment by DylanDylann** [comment] 2023-10-30 12:28
@Ollyws  yeah. You are correct. So in suggestion is:
1. Go with my first option to reduce 1000ms.
2. Fix the issue that you `ve mentioned:

> I would guess because we're getting the value from the draft.
#2 RCA:
- In here:
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/components/ExceededCommentLength.js#L55-L57
 we  get the comment from draft, but use in both edit composer and main composer, that leads to the "max exceed length" does not work when editing comment, and if we are editing comment and switch to type a > 10.000 characters message in main composer, the max exceed length exist in both main composer and edit composer.
- Solution: Add an param called ```isEditing``` to ```ExceededCommentLength``` component, and get the proper message based on it

**Comment by DylanDylann** [comment] 2023-11-01 14:39
@Ollyws yeah, it is my suggestions

**Comment by DylanDylann** [comment] 2023-11-01 14:49
Yeah. I still go with this solution

**Comment by DylanDylann** [comment] 2023-11-01 15:02
@Ollyws Sorry for misunderstood your question
- My solution is:
Move the ```value``` state:
https://github.com/Expensify/App/blob/347df0cc6bc9c1af6a0c7d6ed4034e4222fbf37e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L112
from [ComposerWithSuggestions](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js)  to [ReportActionCompose](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ReportActionCompose.js)

- Then pass it to [ComposerWithSuggestions](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js)  to [ReportActionCompose] by updating:
https://github.com/Expensify/App/blob/347df0cc6bc9c1af6a0c7d6ed4034e4222fbf37e/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L393
to ```<ComposerWithSuggestions value={value} setValue={setValue} ... />```

**Comment by DylanDylann** [comment] 2023-11-06 14:46
@Ollyws Please help review my solution here when you have a chance https://github.com/Expensify/App/issues/27698#issuecomment-1789113427

**Comment by DylanDylann** [comment] 2023-11-07 15:40
@jliexpensify What do you think about this one https://github.com/Expensify/App/issues/27698#issuecomment-1796172931?
- From my side, I think though we cannot remove the debounce completely but still can reduce the delay from 1500ms to 500ms.
- Here is why i think it is worth to fix https://github.com/Expensify/App/issues/27698#issuecomment-1765546425

**Comment by jliexpensify** [comment] 2023-11-08 02:09
@DylanDylann in all honesty, I'm going to defer to @Ollyws here - my main role is to help troubleshoot and manage the issue, and as the C+, Olly should be finding suitable proposals. Given that he's already mentioned that it's an edge case and this issue should be closed a few times already, I'm inclined to lean towards this as well - also this statement indicates we won't really be solving the issue?

> it's essentially impossible to fix completely without removing the debounce

If Olly did think it was an actual issue, my understanding is that he would have chosen a proposal and asked for an internal engineering review. Going to close this one out!

**Closed by jliexpensify** 2023-11-08 02:09 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by DylanDylann** [comment] 2023-11-08 02:17
Many thanks @jliexpensify and @Ollyws
