### ISSUE TITLE
[$1000] Hitting Enter When on Select Workspace option causes input(new line) on Composer.

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24073] opened 2023-08-02 19:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on new Room on FAB.
2. Type Room Name & select any workspace now hit enter
3. Observe that Composer getting focused and adding some input.

## Expected Result:
There shouldn't be  a newline added to composer.

## Actual Result:
Adding a newline into composer.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/c0c17036-0899-4dc4-b995-c6424786894a

https://github.com/Expensify/App/assets/43995119/b3fbb63a-0aff-4a1d-97e0-4850b60e04f7

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @immadisetty-jaya-surya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690789201060999 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c32329f1bb08f9f2</li>
        <li>Upwork Job ID: 1686925472375095296</li>
        <li>Last Price Increase: 2023-08-03</li>
    </ul>
</details>

**Comment by immadisetty-jaya-surya** [comment] 2023-08-02 19:58
@mvtglobally 
updated my proposal
Contributor proposal @immadisetty-jaya-surya

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Dev: Hitting Enter When on Select Workspace option causes input(new line) on Composer.

### What is the root cause of that problem?
RCA for this issue relies here https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/components/FormSubmit/index.js#L21 at this function. 
If we observe other keyboard event listeners inside the codebase we're preventing the default behavior just like here

https://github.com/Expensify/App/blob/24ed1bebf19539d27878ed419f7cc10ae942531f/src/pages/home/report/ReportActionCompose.js#L888

### What changes do you think we should make in order to solve the problem?
We should also prevent the event's default behavior adding a line here

https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/components/FormSubmit/index.js#L21 in this function like below
```js
event.preventDefault()
```
which should prevent adding a new line to the composer.

### What alternative solutions did you explore? (Optional)
NA

**Comment by sophiepintoraetz** [comment] 2023-08-03 02:22
I'm able to reproduce this!

**Comment by gadhiyamanan** [comment] 2023-08-03 02:28
@sophiepintoraetz this is dupe of https://github.com/Expensify/App/issues/19771 and we can close this issue as per https://github.com/Expensify/App/issues/19771#issuecomment-1569396127

**Closed** 2023-08-03 04:58 UTC
Labels: External, Daily, Help Wanted, Bug
