### ISSUE TITLE
[$250] New Group has weird behavior on desktop when using keyboard

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8502] opened 2022-04-06 03:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Imagine you have three contacts, Alice, Bob, and Cathy
2. Open up New Group, and type Ali -- Alice will appear at the top
3. Press "Enter", Alice is selected
4. Type Cath -- Cathy is selected
5. Press "Enter" -- Alice is unselected, and now nobody is.

## Expected Result:
User should be able to select contact by hitting Enter 

## Actual Result:
2nd Contact gets unchecked if user hits enter 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.51-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/161887338-5e5427c7-69b4-48c3-a2c8-50b6538a4a9b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648668545333109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

[job post](https://www.upwork.com/jobs/~012603f4575ca5fa3e)

**Comment by danieldoglas** [comment] 2022-04-06 18:37
Agreed that this is not the expected behavior. It should select the first one of the filtered list, leaving the selected ones as they are.

**Comment by sobitneupane** [comment] 2022-04-07 08:10
Arrow navigation is also not working for New Group and New Chat. It looks like https://github.com/Expensify/App/pull/7702 PR is dealing with the issue. For now, the following replacement will solve the issue. It will select the first option after the selected options if there is any.
https://github.com/Expensify/App/blob/ae8520acbcfac82a7ce7e35e02496033fd02a377/src/components/OptionsSelector.js#L154
```
if (allOptions[this.state.focusedIndex + this.props.selectedOptions.length]){
    this.selectRow(allOptions[this.state.focusedIndex + this.props.selectedOptions.length]);
}
```
This implementation might not be useful after the implementation of above mentioned PR. I think it is better to hold this issue until https://github.com/Expensify/App/pull/7702 gets deployed.

**Comment by parasharrajat** [comment] 2022-04-07 16:18
What is the urgency of this issue? @jboniface

**Comment by parasharrajat** [comment] 2022-04-07 16:47
https://github.com/Expensify/App/pull/7702 tries to standardize the solution for managing arrow navigation. If we go with the above proposal, we may have to remove it when PR is done. 

Should we hold this or go with the solution at hand? cc: @pecanoro

**Comment by pecanoro** [comment] 2022-04-07 17:43
Yeah, it looks like https://github.com/Expensify/App/pull/7702 will solve all these problems? I would say this is a problem for accessibility since some people can't use a mouse, but if we are going to refactor it, this might not be worth solving right now.

**Comment by jboniface** [comment] 2022-04-15 20:28
Should we close this then @pecanoro ?

**Comment by pecanoro** [comment] 2022-04-18 15:52
Yeah, let's close it for now.

**Closed** 2022-04-18 15:56 UTC
Labels: Exported, External, Engineering, Weekly, Improvement, Help Wanted
