### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Web - Emoji - Few emojis does not appear on search in english (works fine in spanish)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25471] opened 2023-08-18 11:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Open emoji picker and search for 'jud'
4. It should display all 3 types of judges i.e. judge , man_judge, woman_judge
5. Similarily search for 'jug', it should display all 3 types of juggling emojis i.e. woman_juggling, juggling_person, man_juggling
6. Change language to spanish and search 'mala', it will display all 3 types of juggling emojis

## Expected Result:
App should display all possible emoji types for any search

## Actual Result:
App does not display all possible emoji types for few emoji searches like 'jug' for juggling emojis and 'jud' for judges emoji in english (works fine in spanish)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** @Dhanashree-Sawant

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ae43c27b-8968-4a01-b385-2ccb03176dd6

https://github.com/Expensify/App/assets/115492554/e6733b19-65f9-4070-9aa2-e356498e8159

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691513077592469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d680d6ea285b4fb</li>
        <li>Upwork Job ID: 1693977609738469376</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 26507497</li>
<li>Dhanashree-Sawant | Reporter | 26507499</li>
</ul></li>
    </ul>
</details>

**Comment by alphaboss1104** [comment] 2023-08-18 17:45
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Few emojis does not appear on search in english
### What is the root cause of that problem?

We didn't add the `keywords` to [here](https://github.com/Expensify/App/blob/main/assets/emojis/en.js).

For example when the language is `english` if we search for `jug`, the `woman_juggling`, `juggling_person`, `man_juggling` emojis should displayed but only `juggling_person` and `amphora` are displayed.
The reason is that `juggling_person` and `amphora` have the  keyword that contains `jug`.

https://github.com/Expensify/App/blob/08dd014c77a32782415612015daa7efd065bf200/assets/emojis/en.js#L1364-L1366
https://github.com/Expensify/App/blob/08dd014c77a32782415612015daa7efd065bf200/assets/emojis/en.js#L2321-L2323

But `woman_juggling`, `man_juggling` don't have got keyword that contains `jug`.

https://github.com/Expensify/App/blob/08dd014c77a32782415612015daa7efd065bf200/assets/emojis/en.js#L1367-L1372

This is the root cause.

### What changes do you think we should make in order to solve the problem?

We Should add the necessary keywords [here](https://github.com/Expensify/App/blob/main/assets/emojis/en.js).

### What alternative solutions did you explore? (Optional)
None.

**Comment by ShogunFire** [comment] 2023-08-19 16:55
Dupe https://github.com/Expensify/App/issues/23429

**Comment by dhanashree-sawant** [comment] 2023-08-20 06:04
Hi @ShogunFire, we don't have any definitive root cause on that issue. Till then calling it dupe is not ideal. Also currently that issue is focused only on flags in spanish and not a universal solution, this issue can help to influence the solution of that issue.

**Comment by ShogunFire** [comment] 2023-08-20 06:29
I changed my dupe comment after 2 minutes after seeing that this was a reverse issue, I still think it's valuable to link the other issue.

**Comment by bfitzexpensify** [comment] 2023-08-22 13:26
Agreed that https://github.com/Expensify/App/issues/23429, though it seems similar, is a separate issue

@allroundexperts we have a couple of proposals ready for review here

@maddylewis I'm ooo for a week, can pick this back up when I'm back if it's not resolved by then

**Comment by maddylewis** [comment] 2023-08-25 13:35
waiting for @allroundexperts to review the existing proposals

**Comment by Li357** [comment] 2023-08-30 12:31
@allroundexperts Sorry for the delay here-- by "full text search" do you mean searching for "jug" starting at any index within the emojis names?

**Comment by bfitzexpensify** [comment] 2023-09-01 11:16
Back from ooo so I can take ownership of this back over - thanks @maddylewis. 

@allroundexperts bump on @Li357's question here - https://github.com/Expensify/App/issues/25471#issuecomment-1699081547

**Comment by Li357** [comment] 2023-09-04 14:29
@allroundexperts Hmm, do we know what WhatsApp does here? Maybe we should do a character minimum, so we only do a full text search after we have 3 characters. Otherwise, it seems overkill and a potential performance issue

**Comment by Li357** [comment] 2023-09-05 13:41
Interesting. I'd prefer WA's approach, so in this case @samh-nl your proposal sounds good. Thanks for checking!

**Comment by dhanashree-sawant** [comment] 2023-09-05 17:37
Hi @bfitzexpensify, the following issue was raised on 18 august but melvin bot has provided 50$ offer. Can you check once you are available?

**Comment by bfitzexpensify** [comment] 2023-09-06 06:37
Hey @dhanashree-sawant, noted, I'll make the adjustment at the time of paying this one out

**Comment by bfitzexpensify** [comment] 2023-09-20 08:34
Payment summary (this job was posted under the previous pricing model)

**Reporting:** @dhanashree-sawant - $250 to be paid via Upwork - offer sent
**Contributor:** @samh-nl - $1500 to be paid via Upwork (I'm considering this eligible for the reporting bonus since the PR was delayed by internal engineer review by 3 days, and there were no changes requested or required) - ✅ 
**C+** @allroundexperts to be paid $1500 via manual request

**Comment by bfitzexpensify** [comment] 2023-09-22 09:45
@allroundexperts reminder to complete the BZ checklist when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2023-09-25 13:10
Thanks!

**Comment by bfitzexpensify** [comment] 2023-09-28 10:26
Bump on the checklist @allroundexperts - thank you!

**Comment by bfitzexpensify** [comment] 2023-10-02 17:18
Looks good to me! OK, we're all good to close this out now.

**Closed by bfitzexpensify** 2023-10-02 17:18 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 13:14
$1,500 payment approved for @allroundexperts based on BZ summary.
