### ISSUE TITLE
 [$1000] Web - Members option menu is not shown until one of the members leaves the public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21059] opened 2023-06-19 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A > Create a new room with a Public mode
2. Click on new room header and copy the share code URL
3. Login with User B and User C on another web chrome window and paste the URL of the room to get access to it
4. On User A (admin), again click on room header and notice that on the details page, the members option menu is seen properly
5. But now , from User B and User C, click on the header of the room and notice that on the details page no 'members' option is seen.
6. Now from one of the users (User B or User C), let's take User B for example, leave the room and notice that on the other user C, the 'members' option menu has appeared.

## Expected Result:
 Members option menu should be shown at first only when any user joins the room

## Actual Result:
Members option menu is not shown until one of the members leaves the room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/14eaa15a-c74b-4a64-a5a8-608220776664

https://github.com/Expensify/App/assets/93399543/d22d1298-ee13-4da4-a668-c1a0968694f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686460538717929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a72bd529fe018ec</li>
        <li>Upwork Job ID: 1671871396568027136</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-06-22 13:24
Placing this one on hold as the fix for [this one](https://github.com/Expensify/App/issues/20761) may resolve this issue.

**Comment by abekkala** [comment] 2023-06-26 13:32
this is still on hole

**Comment by abekkala** [comment] 2023-06-29 14:18
on hold

**Comment by abekkala** [comment] 2023-06-30 15:55
@kevinksullivan Reassigning for Sabbatical

___

CURRENT STATUS: 

- Issue reported by: @priya-zha
- Assigned for Fix: **TBD, may not be needed - this issue on HOLD as fix for 20761 may resolve this one as well.** 
- Assigned C+: @eVoloshchak

**Comment by kevinksullivan** [comment] 2023-06-30 22:38
still held

https://github.com/Expensify/App/issues/20761

**Comment by eVoloshchak** [comment] 2023-07-06 16:01
Not overdue, still held for https://github.com/Expensify/App/issues/20761, looks like it's moving

**Comment by kevinksullivan** [comment] 2023-07-12 22:07
checking reproducibility 

https://expensify.slack.com/archives/C049HHMV9SM/p1689199659960869?thread_ts=1686460538.717929&cid=C049HHMV9SM

**Comment by mallenexpensify** [comment] 2023-07-14 22:58
Added it to the tracking issue. I propose we put this on hold pending
- https://github.com/Expensify/App/issues/22699

**Comment by kevinksullivan** [comment] 2023-07-17 15:50
No longer on hold, awaiting proposals.

**Comment by mallenexpensify** [comment] 2023-07-18 18:16
> Actually this is a dupe of https://github.com/Expensify/App/issues/20761

I agree with @aimane-chnaif , going to close this.  Comment/reopen if you disagree

**Closed by mallenexpensify** 2023-07-18 18:16 UTC
Labels: Daily, Internal, Bug
