### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250]  IOS - Transfer owner - App returns to empty screen when swiping right on success screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44506] opened 2024-06-26 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is invited to a workspace
- User is also promoted to admin
1. Go to app
2. Go to workspace settings > Members
3. Tap on the owner
4. Tap Transfer owner
5. Proceed to success screen
6. Swipe right on the screen (iOS style)

## Expected Result:
App will return to member profile page

## Actual Result:
App returns to an empty Transfer owner screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c98bc362-8ba4-4680-8b9e-97dd1a2f20cb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01054e6abc7abcdf2c</li>
        <li>Upwork Job ID: 1806448714527773045</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102950095</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify / @MitchExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @MitchExpensify</details>

**Comment by lanitochka17** [comment] 2024-06-26 20:29
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-06-28 08:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App returns to an empty Transfer owner screen

### What is the root cause of that problem?
When we go to the success or error page, we navigate to this page so the `WorkspaceOwnerChangeWrapperPage` still present in the navigation stack.


https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L39

https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L45

And then when we swiping, this page appears with empty because the check is complete now.

https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/workspace/members/WorkspaceOwnerChangeCheck.tsx#L36-L39
### What changes do you think we should make in order to solve the problem?
We can use navigate with type is `up` here so the `WorkspaceOwnerChangeWrapperPage` can be removed from the navigation stack.

```
if (!policy.errorFields && policy.isChangeOwnerFailed) {
    // there are some errors but not related to change owner flow - show an error page
    Navigation.navigate(ROUTES.WORKSPACE_OWNER_CHANGE_ERROR.getRoute(policyID, accountID), CONST.NAVIGATION.TYPE.UP);
    return;
}

if (!policy?.errorFields?.changeOwner && policy?.isChangeOwnerSuccessful) {
    // no errors - show a success page
    Navigation.navigate(ROUTES.WORKSPACE_OWNER_CHANGE_SUCCESS.getRoute(policyID, accountID), CONST.NAVIGATION.TYPE.UP);
    return;
}
```


https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L39

https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L45
### What alternative solutions did you explore? (Optional)
NA

**Comment by c3024** [comment] 2024-06-28 08:37
Are there some dummy card details that can be added at this step?

<img width="350" alt="Screenshot 2024-06-28 at 2 05 36 PM" src="https://github.com/Expensify/App/assets/102477862/2b5a62e7-5541-4fe4-9f1b-469a9206ef90">

**Comment by nkdengineer** [comment] 2024-06-28 08:44
@c3024 I commented this validate in `PaymentCardForm`, fill the form and  then test this bug in the fail page.

```
// if (values.cardNumber && !ValidationUtils.isValidDebitCard(values.cardNumber.replace(/ /g, ''))) {
//     errors.cardNumber = translate(label.error.cardNumber);
// }
```

**Comment by c3024** [comment] 2024-06-28 16:28
Thank you for your proposals.

Both solutions fix the issue.

Since the fix pertains to popping of screens in the same `RightModalNavigator`, as far as I know both `goBack` and `UP` work the same way.

As I see `goBack` much more commonly used in our repo than `UP`, I think we can go with @layacat 's [proposal here](https://github.com/Expensify/App/issues/44506#issuecomment-2194280646).

🎀 👀 🎀 C+ Reviewed

**Comment by MitchExpensify** [comment] 2024-07-01 20:49
@puneetlath do you agree with the decision to assign @layacat based on their proposal?

**Comment by MitchExpensify** [comment] 2024-07-01 20:50
Not overdue, Melvin

**Comment by MitchExpensify** [comment] 2024-07-16 18:34
Reassigning as I'm heading on parental leave 🙇

**Comment by c3024** [comment] 2024-07-16 18:38
This is due for payment on 17-07. I'll complete the checklist.

**Comment by c3024** [comment] 2024-07-17 06:05
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #37869 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/4844b40e2fc66c86eb44004a8915849f54b1b82f#r144319754
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not be identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Avatar icon (Account Settings) > Workspaces > Click on a workspace > Members
2. Click on `Owner`
3. Click `Transfer Owner`
4. Fill required fields and proceed to Success or Failure screen
5. Click on browser back button/iOS swipe right/device back button (on Android)
6. Verify that the Profile page of the member/owner in Step 2 appears

**Comment by puneetlath** [comment] 2024-07-17 14:36
Regression test issue: https://github.com/Expensify/Expensify/issues/413387

@c3024 has been paid. 

@layacat I've sent you an [offer](https://www.upwork.com/nx/wm/offer/103156765). Can you ping me here when you've accepted? 

Also, can you follow the steps [here](https://github.com/Expensify/App/issues/44506#issuecomment-2194280776) so that in the future offers get automatically sent to you.

**Comment by puneetlath** [comment] 2024-07-18 18:01
All paid. Thanks everyone!

**Closed by puneetlath** 2024-07-18 18:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
