### ISSUE TITLE
[$250]  Emoji picker - Clicking on same emoji reaction changes skin tone instead of removing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46387] opened 2024-07-28 22:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** bezawitgebremichael+kk@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat
3. Send a message
4. Hover over the message and click on the emoji plus icon
5. Click on "Change default skin tone"
6. Click on any skin tones other than the current one
7. Click on thumbs up reaction
8. Hover over the sent message and click on emoji plus icon again
9. Click on "Change default skin tone"
10. Click on the skin tone different than the current selected one
11. Click on the thumbs up reaction added previously with a different skin tone (the one under the sent message)

## Expected Result:
When changing the default skin tone at step 9 the thumbs up reaction added changes its skin tone as well and when clicking on the thumbs up reaction again the reaction gets removed

## Actual Result:
When changing the default skin tone at step 9 the thumbs up reaction added doesn't change its skin tone and when clicking on the same reaction again with a different skin tone the reaction skin tone changes instead of removing the reaction

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9b135e0b-709e-4f39-b08c-410fe2e8c76f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01028ab74a5fe53b78</li>
        <li>Upwork Job ID: 1818859215495322018</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment] 2024-07-28 22:13
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-28 22:13
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-07-29 03:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on added emoji reaction with a different skin tone add the same emoji with the selected skin tone.

### What is the root cause of that problem?
When we toggle the emoji reaction, it checks whether the emoji with the selected skin tone already added by the current user or not.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/actions/Report.ts#L2569-L2576

> Implement to add the same emoji but with different skin tones

If it's not, then it will add the emoji with the skin tone selected. That's how it's implemented from the first in https://github.com/Expensify/App/issues/15125.

### What changes do you think we should make in order to solve the problem?

If we want that pressing the added reaction to always remove the emoji,
<img width="736" alt="image" src="https://github.com/user-attachments/assets/64c224fe-3ab7-42a1-bbf6-109b11ab9589">

we can update toggleEmojiReaction to accept a new params `ignoreSkinToneOnCompare`.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/libs/actions/Report.ts#L2544-L2550

If it's true, we pass undefined `skinTone` to `hasAccountIDEmojiReacted`. It will only be true in the added reaction bubble.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/home/report/ReportActionItem.tsx#L383-L388

This way, pressing the emoji from emoji picker or context menu will still compare the skin tone too, but pressing the added emoji reaction will ignore the skin tone.

**Comment by rushatgabhane** [comment] 2024-08-07 09:50
I like @bernhardoj's proposal 🎀 👀 🎀 It will be cleaner to implement and avoid regressions

**Comment by chiragsalian** [comment] 2024-08-07 20:46
Proposal LGTM, feel free to create the PR @bernhardoj

**Comment by bernhardoj** [comment] 2024-08-08 07:59
PR is ready

cc: @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-09-16 06:37
deployed to production 2 weeks ago - https://github.com/Expensify/App/pull/47038#issuecomment-2322120826

**Comment by rushatgabhane** [comment] 2024-09-16 06:37
@kadiealexander could you please attach a payment summary

**Comment by kadiealexander** [comment] 2024-09-20 04:23
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@rushatgabhane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@rushatgabhane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@rushatgabhane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@rushatgabhane] Determine if we should create a regression test for this bug.
- [ ] [@rushatgabhane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-09-20 04:24
Payouts due:

- [ ] Contributor: $250 @bernhardoj via manual request
- [ ] Contributor+: $250 @rushatgabhane via manual request

**Comment by bernhardoj** [comment] 2024-09-20 04:30
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-20 05:02
$250 approved for @bernhardoj

**Comment by kadiealexander** [comment] 2024-09-23 23:15
@rushatgabhane bump on the checklist please!

**Comment by garrettmknight** [comment] 2024-09-24 07:49
$250 approved for @rushatgabhane

**Comment by chiragsalian** [comment] 2024-10-01 19:39
Bumped rushat in a 1:1 to handle the checklist.

**Comment by rushatgabhane** [comment] 2024-10-02 09:01
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/15210

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/15210#pullrequestreview-2342241953

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - 


        1. Open any chat and send any message
        2. Add an emoji reaction with a skin tone to the message from the context menu
        3. Repeat step 2 but with a different skin tone
        4. Verify the emoji is added alongside the previous emoji reaction
        5. Now, change the skin tone again from the add reaction picker to a different one (different from step 2 and 3) but don't select any emoji
        6. Press the added emoji reaction bubble
        7. Verify the emoji reaction is removed

**Comment by stitesExpensify** [comment] 2024-10-02 15:52
👋 This was not a bug, it was intended functionality. The same functionality happens in slack, and we built it that way to match. 

https://github.com/user-attachments/assets/6bd581be-090b-44a9-b804-cc45ae7504a1

For next steps I think that we should revert the PR, and maybe update the regression tests to make sure that it matches? I thought we already had a case for this but I guess not. If that is the case though I'm surprised that it took this long for someone to find as a "bug".

Thoughts @chiragsalian ?

**Comment by bernhardoj** [comment] 2024-10-02 16:11
I think what we did here matches the video.

**Comment by stitesExpensify** [comment] 2024-10-02 16:46
Looking at [this video](https://private-user-images.githubusercontent.com/50919443/356133625-9d07df49-5bab-4c3e-87cb-bc26de47bbe4.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODc1MDgsIm5iZiI6MTcyNzg4NzIwOCwicGF0aCI6Ii81MDkxOTQ0My8zNTYxMzM2MjUtOWQwN2RmNDktNWJhYi00YzNlLTg3Y2ItYmMyNmRlNDdiYmU0Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE2NDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MjRlYmZmNGJiMTVkMzAwNDUzYmFhNzAzZGRlNjhiYzhkNTYxYjc1YjA0OTY0ZWVlOGUyMWFjMTEwZjg3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0LU__eOTUV5252bLAJCX-ekqwDi1y3ZQV6oU4_OyuPQ) from the PR, I don't think so. 

Firstly, the functionality for the quick-reactions and the normal reaction picker should be the same. It looks like the quick-react still has the proper functionality, but clicking below the comment does not. 

The test cases should be:
Case 1: This is failing. In the video when the skin tone is changed for a second time, it should have added a third reaction, not removed the reaction
1. React to a message _without using the quick react_
2. Change your default skin tone
3. React with the same emoji to the same message again _without using the quick react_
4. There should now be 2 reactions, one of each skin tone
5. Click the reactions below the message
6. The reactions should disappear


---- 
Case 2: This is currently passing because quick reacts were not changed
1. React to a message _using the quick react_
2. Change your default skin tone
3. React with the same emoji to the same message again _using the quick react_
4. There should now be 2 reactions, one of each skin tone
5. Click the reaction _in quick react_ again
6. The reactions should disappear

**Comment by chiragsalian** [comment] 2024-10-04 21:01
Why revert the PR? i think the code here is an improvement IMO so I'm not following why we want to revert it. 
I think when i change skin tone and click on my existing emoji i would want it to be removed, which is the same that happens on slack.

**Comment by stitesExpensify** [comment] 2024-10-04 22:09
I believe that @bernhardoj was correct, and I was misunderstanding the change here. My apologies. No need to revert the PR or make any changes!

**Closed** 2024-10-08 02:58 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
