### ISSUE TITLE
[HOLD for payment 2024-02-26] Reimbursements - Clicking on currency doesn't work

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36438] opened 2024-02-13 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n (New feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open workspace settings page
2. Click on 'Reimbursements'
3. Click on 'Rate'
4. Click on 'Rate' again
5. Click on 'Currency'
## Expected Result:
Currency list page should be opened or there shouldn't be dropdown to change currency

## Actual Result:
Nothing happens when clicking currency dropdown

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/6fe2dfe4-61c6-429b-9f57-23000da8eece

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by godofoutcasts94** [comment] 2024-02-13 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reimbursements - Clicking on currency doesn't work

### What is the root cause of that problem?
The currency `selection list` is missing here 

https://github.com/Expensify/App/blob/19e28491a92d2ea74b85b73b86aad1f2f3e06174/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage/RatePage.tsx

### What changes do you think we should make in order to solve the problem?

By adding currency `selection list`, we can fix this issue. 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by akinwale** [comment] 2024-02-13 21:32
The currency defaults to the workspace's currency and should not be changed at this point, since that is configured elsewhere. Two options here, either:
1. remove the currency prefix completely, or
2. add a flag prop to the component to hide the dropdown arrow (the dropdown arrow was added in a separate PR).

cc @shubham1206agra

**Comment by godofoutcasts94** [comment] 2024-02-13 21:34
> The currency defaults to the workspace's currency and should not be changed at this point, since that is configured elsewhere. Two options here, either:
> 
> 1. remove the currency prefix completely, or
> 2. add a flag prop to the component to hide the dropdown arrow (the dropdown arrow was added in a separate PR).
> 
> cc @shubham1206agra

@akinwale  Just a quick question for clarity I am asking this but don't you think we can add selector list, which will contain list of currency selection option like other pages?

**Comment by Beamanator** [comment] 2024-02-14 13:21
@shubham1206agra are you working on a PR fix for this somewhere? 🤔

**Comment by dangrous** [comment] 2024-02-14 15:49
Linking the PR here - https://github.com/Expensify/App/pull/36497

**Comment by aldo-expensify** [comment] 2024-02-14 23:01
Assigned @allroundexperts as C+

**Comment by thienlnam** [comment] 2024-02-14 23:21
Removing the blocker 
https://github.com/Expensify/App/pull/36549#issuecomment-1944982700

**Comment by jliexpensify** [comment] 2024-02-26 22:30
Bump @allroundexperts to complete the checklist please!

**Comment by jliexpensify** [comment] 2024-02-27 04:12
Thank you!

**Comment by jliexpensify** [comment] 2024-02-28 03:37
Bumping @allroundexperts - checklist needed?

**Comment by allroundexperts** [comment] 2024-02-28 06:05
> Bumping @allroundexperts - checklist needed?

No. This should be covered in the PR we raised for the [original issue](https://github.com/Expensify/App/issues/36436#issue-2133110374).

**Comment by jliexpensify** [comment] 2024-02-28 09:58
Great, thank you! Closing this.

**Comment by JmillsExpensify** [comment] 2024-03-01 23:55
@jliexpensify Do you mind checking the boxes in the payment summary above? I'd like to see that filled out before I approve.

**Comment by jliexpensify** [comment] 2024-03-03 22:21
@JmillsExpensify done, and payment is handled [here](https://github.com/Expensify/App/issues/36436#issuecomment-1960052514) already, as per this [comment](https://github.com/Expensify/App/issues/36438#issuecomment-1965735062).

**Closed** 2024-03-03 22:22 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-04 15:05
Thanks! $500 approved for @allroundexperts based on [this confirmed summary](https://github.com/Expensify/App/issues/36438#issuecomment-1964362407).

**Comment by allroundexperts** [comment] 2024-03-04 15:24
Yes, my bad. This has been paid [here](https://github.com/Expensify/App/issues/36436#issuecomment-1974098952)

**Comment by JmillsExpensify** [comment] 2024-03-04 15:26
Ah thank you! Sorry I missed that in Jason's previous comment. Updating my comment above.
