### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] IOU - Repeatedly pressing same number shows a mark nearby

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26628] opened 2023-09-03 21:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap request money
4. Press the same number multiple times like 1 or 2 or 3

## Expected Result:
When user presses same number multiple times also, number alone must be displayed

## Actual Result:
When user presses the same number multiple times , nearby "1" number apostrophe like shown, similarly for "2", above and below a small line and while typing 3rd " 3" also we can note the apostrophe like

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/71a31eca-a587-4e77-a12a-99fbb985f30e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011af9157d69c084d8</li>
        <li>Upwork Job ID: 1698646508756721664</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-09-04 10:37
That's pretty subtle, but I see it too through Browserstack

**Comment by lookmanrays** [comment] 2023-09-04 14:34
I see the problem in Chrome (mobile emulator). The possible issue in the viewport resizing — the number appears before the width resizes and because of that the apostrophe shows. Basically, if you take a look you will see that it's not an apostrophe but the front part of a number just appears before the width changes.

**Comment by lookmanrays** [comment] 2023-09-04 14:43
Contributor details
Your Expensify account email: lookman.rays@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01006d6855461586ee

**Comment by neg-0** [comment] 2023-09-05 01:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When changing the text field on the request money screen, the next digit is partially shown for a brief moment.

### What is the root cause of that problem?

The change made from issue #8158 added an additional width of 2 pixels to the Text component used to autoGrow the RNTextInput in BaseTextInput. The value of RNTextInput is changed prior to the Text component resizing, which shows a partial number. 

![image](https://github.com/Expensify/App/assets/1709513/44f6da54-43ed-41f2-9cac-8a19b568b48d)

Here is the same issue with a width of 8 pixels added, to emphasize the issue:

https://github.com/Expensify/App/assets/1709513/2788c426-2de2-4d80-b219-ea09d547ea0e

The change introduced in #9102 no longer seems to be necessary, as removing the extra width does not show any rendering issues on mWeb on either the request money or split bill screens.

https://github.com/Expensify/App/assets/1709513/18f84e37-a6bd-4e89-a3aa-a0f3058114b1


### What changes do you think we should make in order to solve the problem?

Simply remove the extra added width in BaseTextInput makes the text render correctly.

![image](https://github.com/Expensify/App/assets/1709513/ae053d18-9b30-4709-8213-f733a16e1975)

### What alternative solutions did you explore? (Optional)
None

**Comment by neg-0** [comment] 2023-09-05 01:20
Contributor details
Your Expensify account email: dustin@negativezeroinc.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016b88d5b00db11c11

**Comment by conorpendergrast** [comment] 2023-09-11 08:26
I'm on parental leave; re-assigning! This has been triaged and is waiting for proposals.

**Comment by ArekChr** [comment] 2023-09-13 10:48
@neg-0 Could you provide more details regarding suggested changes in your proposal?

**Comment by neg-0** [comment] 2023-09-13 20:58
@ArekChr Sure,

The proposed change is to remove the extra 2 pixels applied to the Text component that's being used to implement autoGrow in the BaseInputText component. The original intent of this padding was to fix issue #8158 but it seems that the root cause has been resolved and the extra padding is no longer necessary.

The code causing this issue is on line 396 of BaseTextInput.

https://github.com/Expensify/App/blob/3f61f61843a91dc2c4f0c3205b35b70dceb38eb7/src/components/TextInput/BaseTextInput.js#L385-L403

Removing the 2 pixels of padding on line 396 will prevent the portion of text from being displayed when the text value changes.

![image](https://github.com/Expensify/App/assets/1709513/8c75f034-f77f-4ebc-a268-d696a18f3aaf)

https://github.com/Expensify/App/assets/1709513/18f84e37-a6bd-4e89-a3aa-a0f3058114b1

Note: To dive deeper into this issue, there is actually a delay between when the text value of RNTextInput changes and when the size of the autoGrow Text component is computed. It's almost imperceptible and shouldn't be noticed by a user on a daily basis, so I'll divert to the Expensify team whether or not I should dive into finding a solution to synchronize these components.

**Comment by ArekChr** [comment] 2023-09-14 11:00
Thanks for details @neg-0!

> Note: To dive deeper into this issue, there is actually a delay between when the text value of RNTextInput changes and when the size of the autoGrow Text component is computed. It's almost imperceptible and shouldn't be noticed by a user on a daily basis, so I'll defer to the Expensify team whether or not I should dive into finding a solution to synchronize these components.

I didn't notice that issue after applying your changes, On which device did you notice that? Could you send a video that shows that sync issue?

**Comment by neg-0** [comment] 2023-09-15 02:21
@ArekChr Check out the video below. Like I said, very hard to notice at full speed. I turned on device throttling in Chrome to make it much more obvious. This is done on Windows Chrome but I can also notice it on Android native.

https://github.com/Expensify/App/assets/1709513/cf01266f-04ab-4981-a7dc-53cc8203818f

**Comment by ArekChr** [comment] 2023-09-15 07:40
@neg-0 I think this might be done as a separate issue. It requires refactoring of baseTextInput and more changes in PR.
Your [proposal](https://github.com/Expensify/App/issues/26628#issuecomment-1718308555) looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by neg-0** [comment] 2023-10-01 12:55
In my opinion, a small UI tweak does not warrant a regression test. @ArekChr and I have discussed the need to eventually refactor this component to more elegantly render the text. A complete component refactor would involve much more work.

**Comment by ArekChr** [comment] 2023-10-02 08:52
- [x] Link to the PR: This component has had performance issues for a long time. It's hard to determine which PR introduced the regression.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by flaviadefaria** [comment] 2023-10-05 11:51
Payment summary:
@neg-0 = $500 (no bonus)

**Comment by flaviadefaria** [comment] 2023-10-05 11:54
@neg-0 I just sent you an offer in UW.

**Comment by flaviadefaria** [comment] 2023-10-05 13:35
Everyone has now been paid so closing this.

**Closed by flaviadefaria** 2023-10-05 13:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
