### ISSUE TITLE
[HOLD for payment 2022-10-03] [$250] Payments > Add Payment Method > Paypal.me: this field is not auto-focused

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10990] opened 2022-09-14 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Open settings page > Payments > Add payment method > Paypal

## Expected Result:
Paypal.me field should be auto-focused

## Actual Result:
Paypal.me field is not auto-focused

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.0.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190185705-4a7b9307-a42f-4478-a5c9-1bd0e0d3f0d8.mp4

<img width="391" alt="Screenshot 2022-08-26 at 3 12 33 AM (1)" src="https://user-images.githubusercontent.com/93399543/190186722-4d6ca5d2-8409-487d-aa73-0533e26ca1bf.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661465653354209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2022-09-14 14:42
Same for me as the video: 
<img width="525" alt="2022-09-14_15-42-13" src="https://user-images.githubusercontent.com/56830058/190186279-de755b0f-e103-4f53-a747-4f09bbf6eea1.png">

**Comment by Puneet-here** [comment] 2022-09-14 15:00
### Proposal 

Pass the code below at https://github.com/Expensify/App/blob/a0340070ebf94fe3acde872c8c0c4222edd984c3/src/pages/settings/Payments/AddPayPalMePage.js#L62
```js
onTransitionEnd={() => {
                if (!this.payPalMeInputRef) {
                    return;
                }

                this.payPalMeInputRef.focus();
            }}
```

and pass the code below here 
https://github.com/Expensify/App/blob/a0340070ebf94fe3acde872c8c0c4222edd984c3/src/pages/settings/Payments/AddPayPalMePage.js#L74
```js
ref={el => this.payPalMeInputRef = el}
```

**Comment by deetergp** [comment] 2022-09-14 23:25
This can be done by an external contributor.

**Comment by jliexpensify** [comment] 2022-09-14 23:58
Posted:

Internal - https://www.upwork.com/ab/applicants/1570200114002706432/job-details
External - https://www.upwork.com/jobs/~01149a8ecea788e448

Invited @aneequeahmad

**Comment by aneequeahmad** [comment] 2022-09-15 00:02
@jliexpensify Invitation not found unfortunately

**Comment by jliexpensify** [comment] 2022-09-15 00:11
@aneequeahmad this is you, correct?

![image](https://user-images.githubusercontent.com/30815269/190284248-bb6adcf9-f058-49a7-93ac-506b7d4c3cdd.png)

**Comment by aneequeahmad** [comment] 2022-09-15 00:12
@jliexpensify Yup this is me

**Comment by jliexpensify** [comment] 2022-09-15 00:39
You've already been invited - if you're not seeing the invite, click here:

https://www.upwork.com/jobs/~01149a8ecea788e448

**Comment by aneequeahmad** [comment] 2022-09-15 00:42
@jliexpensify applied thanks

**Comment by aneequeahmad** [comment] 2022-09-15 00:47
### PROPOSAL

This issue can be fixed like the TextInput focused in `AddSecondaryLoginPage.js` https://github.com/Expensify/App/blob/3e410ef9deebf3ee700f0f98d30989abf1a859e8/src/pages/settings/AddSecondaryLoginPage.js#L95-L101

**Comment by Puneet-here** [comment] 2022-09-15 10:40
> @aneequeahmad's proposal looks good to me. Choosing theirs over others as they reported the issue and another proposal was posted before external.

Hi @parasharrajat, the contributing.md doesn't say anything about this, there is no rule about choosing the contributor's proposal just because they are the reporter and there is no such case mentioned about choosing another proposal if the first proposal is posted before external.

**Comment by aneequeahmad** [comment] 2022-09-15 10:53
@Puneet-here, I asked the same question about posting solution before `External` label or `Help Wanted` label in expensify-open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1662975033011809?thread_ts=1662853564.044149&cid=C01GTK53T8Q). Please read the thread you will get better idea about the policy. 
Thanks

**Comment by Puneet-here** [comment] 2022-09-15 11:06
CONTRIBUTING.md says "Issues that have not had the `External` label applied have not yet been approved for implementation. This means, if you propose a solution to an issue without the `External` label **(which you are allowed to do)** it is possible that the issue will be fixed internally."

Also I have seen threads where it was decided to not stop contributors from posting the proposal on issue before the external label because it can slow the process also there is no dibs for reporter. The reporter can propose the solution in the thread while posting the bug and can link it in the issue. 

cc: @mallenexpensify

**Comment by Puneet-here** [comment] 2022-09-15 11:12
> @Puneet-here, I asked the same question about posting solution before `External` label or `Help Wanted` label in expensify-open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1662975033011809?thread_ts=1662853564.044149&cid=C01GTK53T8Q). Please read the thread you will get better idea about the policy. 

> The thread says the same, you can post the proposal before External label.

**Comment by Puneet-here** [comment] 2022-09-15 11:25
> @Puneet-here Priority is given to the reporters.

I don't think this is the case, If I remember correctly @mallenexpensify had made it clear somewhere.

**Comment by mallenexpensify** [comment] 2022-09-16 00:13
This has def happened in the past and we've updated the CONTRIBUTING.md to (hopefully) address most circumstances like this.  The main part I'd reference is from [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Note%3A%20Before%20submitting%20a%20proposal%20on%20an%20issue%2C%20be%20sure%20to%20read%20any%20other%20existing%20proposals.%20Any%20new%20proposal%20should%20be%20substantively%20different%20from%20existing%20proposals.) is:
> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. Any new proposal should be substantively different from existing proposals.

Based on that, it sounds like @Puneet-here 's proposal should be the one accepted.  We intentionally don't have rule for 'first dibs' for the reporter because, once issues are created, we want them fixed as soon as possible and we don't want to unnecessarily wait for the reporter to _maybe_ submit a proposal.

**Comment by jliexpensify** [comment] 2022-09-16 00:31
Invited @parasharrajat as C+. @mallenexpensify are you making the final decision on hiring? If so, I'll invite @Puneet-here - cheers!

**Comment by mallenexpensify** [comment] 2022-09-16 00:42
Let's give it a _day_ for @parasharrajat to reply before we come to a **final** decision

**Comment by aneequeahmad** [comment] 2022-09-16 10:05
@parasharrajat Ahhh yes, As i was suggested not to post proposals before `External` label is added. I'll keep this conversation in mind next time i report issues or post proposals.

Thanks for clarifying.

**Comment by tgolen** [comment] 2022-09-16 19:10
The proposal is fine with me except for this being unnecessary:

![image](https://user-images.githubusercontent.com/1228807/190713385-08fe5d96-a858-41a9-98e7-a2b5f3602705.png)

We don't declare refs in the constructor at all.

**Comment by Puneet-here** [comment] 2022-09-16 19:23
> We don't declare refs in the constructor at all.

We are declaring the refs in constructor at other pages.
https://github.com/Expensify/App/blob/b4b12addac16a3ef3753273e25c3e58379715a76/src/pages/settings/AddSecondaryLoginPage.js#L58

**Comment by tgolen** [comment] 2022-09-16 19:50
I'll give you bonus Tim-Points if you remove that in your PR :D

**Comment by Puneet-here** [comment] 2022-09-16 19:53
> I'll give you bonus Tim-Points if you remove that in your PR :D

Hahaha 😄 I definitely wanna earn Tim-Points, I will remove all of them.

**Comment by mallenexpensify** [comment] 2022-09-16 20:38
@aneequeahmad , also, thanks for understanding
> @parasharrajat Ahhh yes, As i was suggested not to post proposals before External label is added. I'll keep this conversation in mind next time i report issues or post proposals.
>
>Thanks for clarifying.

We've discussed and reviewed this many time and have updated the CONTRIBUTING.md [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)
> Note: Issues that have not had the External label applied have not yet been approved for implementation. This means, if you propose a solution to an issue without the External label (which you are allowed to do) it is possible that the issue will be fixed internally. If the External label has not yet been applied, Expensify has the right to use your proposal to fix said issue, without providing compensation for your solution. This process covers the very rare instance where we need or want to fix an issue internally.
>
>Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. Any new proposal should be substantively different from existing proposals.

We want issues fixed, and proposals submitted quickly, but we also need to cover our ass in case we decide the fix an issue internally, for some reason.  It's extremely rare (I can't point to an issue we've done this for) but, by having `External` be the main _marker_, it keeps things a bit cleaner/clearer ( at least for us internally and for including in CONTRIBUTING.md as the source of truth).

**Comment by jliexpensify** [comment] 2022-09-17 00:39
Hired Rajat and @aneequeahmad 

@Puneet-here - can you update your GH profile to include your full name? And can you share me your Upwork profile (or apply here - https://www.upwork.com/jobs/~01149a8ecea788e448)? Cheers.

**Comment by Puneet-here** [comment] 2022-09-17 06:53
@jliexpensify, I have applied to the job.

**Comment by mvtglobally** [comment] 2022-09-27 05:15
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-10-03 20:20
Issue not reproducible during KI retests. (Second week)

**Comment by jliexpensify** [comment] 2022-10-03 22:05
Everyone's been paid, and job has been closed - thanks!

**Closed by jliexpensify** 2022-10-03 22:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment
