### ISSUE TITLE
[$250] Tag - Sometimes the "missing {tagName}" error message returns on a chosen tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43590] opened 2024-06-12 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40741
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Navigate to the workspace chat
4. Start submitting a manual expense
5. Only input the "Merchant" field on the confirmation page
6. Submit the expense
7. Open the expense
8. Click on any of the three missing tags
9. Choose any of the options
10. Choose tags for the 2 remaining fields

## Expected Result:
There shouldn't be any error messages on the selected tags

## Actual Result:
Sometimes the "missing {tagName}" error message returns on a chosen tag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ef52b8a9-a808-4387-bd87-fdb34084218a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af1bea0b59a585a5</li>
        <li>Upwork Job ID: 1801155401745680701</li>
        <li>Last Price Increase: 2024-07-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-06-12 16:44
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-12 16:45
We think that this bug might be related to #wave-collect - Release 1

**Comment by VictoriaExpensify** [comment] 2024-06-13 07:31
Oh right, so the Tags are added but, for some reason, they aren't always being saved so we show the Missing error. That sure seems like a bug to me! 

And I agree that this is Wave Collect

**Comment by eVoloshchak** [comment] 2024-06-26 21:00
Not overdue, awaiting proposals

**Comment by VictoriaExpensify** [comment] 2024-07-03 05:40
Not overdue, still awaiting proposals

**Comment by mvtglobally** [comment] 2024-07-03 14:37
Issue not reproducible during KI retests. (First week)

**Comment by VictoriaExpensify** [comment] 2024-07-05 04:25
Hey @lanitochka17 - are you still able to recreate this bug?

**Comment by VictoriaExpensify** [comment] 2024-07-08 23:55
Since we do not have any proposals and it wasn't reproducable during KI tests, I'm closing this one. Reopen if you disagree.

**Closed by VictoriaExpensify** 2024-07-08 23:55 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
