### ISSUE TITLE
mWeb- Chat - The new message received offline is not displayed in the chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13023] opened 2022-11-24 21:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in account A (main device) and account B (secondary device)
2. Go to LHN in account A
3. Kill the internet connection in account A
4. Sent the message from account B to account A
5. Turn on the internet in account A

## Expected Result:
The new message received offline should be displayed in LHN and in the chat

## Actual Result:
The new message received offline is initially displayed only in LHN, but is not displayed in the chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web (Safari and Chrome)
- Android

**Version Number:** 1.2.31.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203863326-c5408604-eab7-463b-ba08-4ca85b3a85f1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2022-11-25 16:14
Was able to reproduce:

https://user-images.githubusercontent.com/38236554/204023241-2f8694d3-16a3-409e-92c1-754d2e72c6ab.MP4

**Comment by bfitzexpensify** [comment] 2022-11-25 16:18
From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [x] **The "bug" is actually a bug**: 
- [x] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [x] **The bug is reproducible, following the reproduction steps:**
- [x] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [x] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

Going to tag in engineering, not sure if this will be fixed by sequence numbers?

**Comment by nkuoch** [comment] 2022-11-28 11:09
I can't reproduce it...
I have my iphone New Expensify app logged with nkuoch@expensify.com on LHN and go on airplane mode.
From my Mac online, on firefox I'm connected with nkuoch@expensifail.com and send a message to nkuoch@expensify.com.
I turn off airplane mode from my iphone app, and see the new message appear. Clicking on the chat, I see it appear too...

https://user-images.githubusercontent.com/2463975/204263237-e4649df9-8ec8-415b-bdaf-8b376c48f30e.MP4

@bfitzexpensify @kbecciv Can you still reproduce? How exactly?

**Comment by kbecciv** [comment] 2022-11-28 14:38
@nkuoch You need to use the mWeb/Safari to reproduce it.

**Comment by nkuoch** [comment] 2022-11-30 12:51
Still can't reproduce it ... Can you @kbecciv ?
I sent the message from mac chrome, and received it successfully on mobile web safari after switching airplane mode and clicking on the chat.

**Comment by JmillsExpensify** [comment] 2022-11-30 15:07
@bfitzexpensify Mind jumping in and help confirming whether you get reproduce? If not, let's close the issue.

**Comment by bfitzexpensify** [comment] 2022-11-30 21:50
Wasn't able to reproduce at this moment with the same steps I took in https://github.com/Expensify/App/issues/13023#issuecomment-1327668920, but I suspect the site slowness might be playing a role in that. Have set a reminder to myself to test this again first thing tomorrow. I'll close if I can't reliably reproduce.

**Comment by bfitzexpensify** [comment] 2022-12-01 13:05
Was unable to reproduce - behaved as expected (when coming back online, the message displayed both in the LHN and within the DM when opened). Closing.

**Closed by bfitzexpensify** 2022-12-01 13:05 UTC
Labels: Engineering, Daily, Bug
