### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] iOS - WS Invite - Invite message link does not lead to invite message page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29163] opened 2023-10-10 09:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing PR https://github.com/Expensify/App/pull/25543

**Version Number:** 1.3.80-0
 
**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in, must have sent the invite message link to any workspace to any conversation.

1. Go to the conversation you have sent the invite message link.
2. Tap on the invite message link.

## Expected Result:
Invite message page should be displayed.

## Actual Result:
Workspace page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/5ff96d17-66bb-4d47-9c8b-1d8539a4bcba

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142f9bb42ec3d0112</li>
        <li>Upwork Job ID: 1711668274402217984</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27158437</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-10 09:02
Not reproduced on Prod. It redirects to browser.

https://github.com/Expensify/App/assets/115492554/2a3c7662-aeb1-455e-be7e-cbd2972734b2

**Comment by mallenexpensify** [comment] 2023-10-11 02:28
Just seeing this now, sorry I missed it (also weird it's an hourly and hasn't gone overdue in 16 hours). 
@sobitneupane , can you review the above?  Do you have any processes in place to be notified of hourly issues? We use it internally but I still missed this.  

Asking about in #qa [here](https://expensify.slack.com/archives/C9YU7BX5M/p1696991269414679)
Also pinging Sobit in #contributor-plus for 👀

**Comment by jasperhuangg** [comment] 2023-10-11 03:12
Personally, I think we should just close this out. This doesn't seem like behavior anyone would ever engage in. Even if they were to do this, I think the current behavior makes sense. It wouldn't make sense to take you back to the invite-members flow, since you have technically already exited that flow. Going to close this out.

**Comment by sobitneupane** [comment] 2023-10-11 03:19
I don't think it's a deploy blocker. It is reproducible in Prod as well. And the other thing is it is reproducible in all platforms.

We used to initially redirect it to Workspace Invite Page (implemented by [this PR](https://github.com/Expensify/App/pull/22262)) which was later changed to Workspace Initial Page by [this PR](https://github.com/Expensify/App/pull/28050) which doesn't look like intended change.

**Comment by mallenexpensify** [comment] 2023-10-11 03:34
Thanks @jasperhuangg and @sobitneupane !

**Comment by mallenexpensify** [comment] 2023-10-12 00:29
Reopening for now, removed deploy blocker and updated to a daily.

**Comment by sobitneupane** [comment] 2023-10-12 09:28
[Proposal](https://github.com/Expensify/App/issues/29163#issuecomment-1754855558) from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by iwiznia** [comment] 2023-10-12 10:59
> This is a regression from [this PR refactor change](https://github.com/Expensify/App/pull/28050/files#diff-263e48e611e289b8b861359cfd2472f0dd20b770f3e95eba5bd901e1e9f04e86) (although not a deploy blocker since it was deployed to prod a long time ago). The refactor has changed the intended behavior from the Workspace Invite page to Workspace Initial page.

FYI @tgolen 

> When investigating this, I found there's an existing bug [here](https://github.com/Expensify/App/blob/a63f853381cd6ea680c31ee24c7c72f02e2d1513/src/libs/Navigation/Navigation.js#L132C50-L132C50) where the lastRoute could be falsy, leading to app crashes, to fix that we should update it to

Why would the route be falsy? What value exactly it has? I would assume that we always have a route?

**Comment by iwiznia** [comment] 2023-10-12 11:00
Proposal looks good otherwise

**Comment by tgolen** [comment] 2023-10-12 16:54
Yes, sorry, this was a regression that was not intended and the constant just needs to be swapped. I had a conflict come up with that constant in the PR and didn't resolve it properly.

**Comment by sobitneupane** [comment] 2023-10-13 06:25
> When investigating this, I found there's an existing bug [here](https://github.com/Expensify/App/blob/a63f853381cd6ea680c31ee24c7c72f02e2d1513/src/libs/Navigation/Navigation.js#L132C50-L132C50) where the lastRoute could be falsy, leading to app crashes, to fix that we should update it to

@dukenv0307 Can you please explain about the issue you are mentioning here. I remember having an issue where app crashes on navigating request money page through link. But I believe it was resolved by some other PR.

**Comment by mallenexpensify** [comment] 2023-10-26 16:54
Lil confused but .... 

Issue reporter: Applause
Contributor: @dukenv0307 paid $750 via Upwork, inc. urgency bonus (it looks like it was technically one hour over 3 days)
Contributor+: @sobitneupane due $750 via NewDot. inc. urgency bonus

I see regression mentioned above, my assumption is that this issue came from another regression, not that there was one here, please correct me if i'm wrong.  Unsure if we want a regression test specifically for this if the issue came from another, what cha think @sobitneupane ?

**Comment by sobitneupane** [comment] 2023-10-30 11:19
> I see regression mentioned above, my assumption is that this issue came from another regression, not that there was one here, please correct me if i'm wrong. 

@mallenexpensify You are right. This issue was regression from https://github.com/Expensify/App/pull/28050. There is no regression from the PR associated with the issue.

**Comment by sobitneupane** [comment] 2023-10-30 11:22
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/28050
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/issues/29163#issuecomment-1759390722
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This issue was caused by some merge conflict during a large refactor.
> * [ ] Determine if we should create a regression test for this bug.

Yes.
> * [ ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-30 11:23
**Regression Test Proposal**

1. Go to Settings > Workspaces > Select any workspace
2. Go to Members > Invite > Invite message page
3. Copy the URL
4. Send this to a report
5. Logout out and login again
6. Click on the url sent in step 3.
7. Verify that the user is redirected to invite page appears

**Comment by sobitneupane** [comment] 2023-10-30 14:05
https://github.com/Expensify/App/issues/29163#issuecomment-1781494629

Requested payment on newDot.

**Comment by mallenexpensify** [comment] 2023-10-30 23:21
Thanks @sobitneupane !  Regression test GH created
- https://github.com/Expensify/Expensify/issues/331501

[Payment breakdown above](https://github.com/Expensify/App/issues/29163#issuecomment-1781494629) is up to date.

**Closed by mallenexpensify** 2023-10-30 23:21 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:25
$750 payment approved for @sobitneupane based on [this summary](https://github.com/Expensify/App/issues/29163#issuecomment-1781494629).
