### ISSUE TITLE
[$500] Task - Title field is not focused when going back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30366] opened 2023-10-25 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698156938953799

## Action Performed:
The title field is not focused when going back
1. Click on FAB > Assign Task
2. Write a title and click on next
3. Click the back button

## Expected Result:
The title field is focused when going back

## Actual Result:
The title field is not focused when going back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary> 

https://github.com/Expensify/App/assets/93399543/30be106c-89e0-4f0e-ad40-22d3f41015f7

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/24c581e9-7bd8-4efc-8df2-90659bdcb9bc

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/26d27138-58a9-4180-8e77-b8755384b734

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9416b393-17f5-405f-8687-ad6cd7c75209

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/99884da9-05a8-4eab-9b62-26bc6a0f9660

</details>

<details>
<summary>MacOS: Desktop</summary>

  

https://github.com/Expensify/App/assets/93399543/96ac1d90-2c07-4fa1-8333-555a423a7f64

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167a5caffbbaa5a60</li>
        <li>Upwork Job ID: 1717217726602346496</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-25 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Title" field on task creation is not focused on navigating back

### What is the root cause of that problem?
For handling the Task's Title field, we use a custom hook: https://github.com/Expensify/App/blob/c3a6b429569474d2e883fb83de802508a85f727a/src/hooks/useAutoFocusInput.js

This hook is intended to handle the field state and auto-focus on navigation.

It uses this hook to handle the navigation state: whether the screen is focused or not:

https://github.com/Expensify/App/blob/c3a6b429569474d2e883fb83de802508a85f727a/src/hooks/useAutoFocusInput.js#L19-L32

However, while it works well on the initial component load and page reload, once we navigate to the next screen, the state of this component is not properly discarded.

### What changes do you think we should make in order to solve the problem?

Along with clearing the focusTimeoutRef, we should set the isScreenTransitionEnded to false:

```diff
    useFocusEffect(
        useCallback(() => {
            focusTimeoutRef.current = setTimeout(() => {
                setIsScreenTransitionEnded(true);
            }, CONST.ANIMATED_TRANSITION);
            return () => {
                if (!focusTimeoutRef.current) {
                    return;
                }
+               setIsScreenTransitionEnded(false);
                clearTimeout(focusTimeoutRef.current);
            };
            // eslint-disable-next-line react-hooks/exhaustive-deps
        }, []),
    );
```



### What alternative solutions did you explore? (Optional)

**Comment by rakshitjain13** [comment] 2023-10-25 17:36
@paultsimura Was writing the same proposal but you bumped first! Supafast 💨

**Comment by DylanDylann** [comment] 2023-10-26 02:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Task - Title field is not focused when going back

### What is the root cause of that problem?
- Currently, we are using the below ```useEffect``` to focus on the input:
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/hooks/useAutoFocusInput.js#L12-L17
- When we refocus on this screen, the dependences ```[isScreenTransitionEnded, isInputInitialized]``` are not changed (```isScreenTransitionEnde``` is still ```true```) so the callback function in useEffect is not called, that lead to the bug
### What changes do you think we should make in order to solve the problem?
- We need to ```setIsScreenTransitionEnded(false)``` when the screen is blurred by adding ```setIsScreenTransitionEnded(false)```
to 
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/hooks/useAutoFocusInput.js#L24-L29
- But when we go to the ```NewTaskDetailPage``` screen, there is a delay when focusing on input. So we need to improve this one by using ```InteractionManager.runAfterInteractions``` by:
update
https://github.com/Expensify/App/blob/05ae4c4d7b150b9bd88569a84eee7e3ab7f3e5fd/src/hooks/useAutoFocusInput.js#L19-L32
to
```
useFocusEffect(
        useCallback(() => {
            const interactionPromise = InteractionManager.runAfterInteractions(() => {
                setIsScreenTransitionEnded(true);
            });
            return () => {
                setIsScreenTransitionEnded(false);
                interactionPromise.cancel();
            };
        }, []),
    );
```


### What alternative solutions did you explore? (Optional)
- NA

### Result

[Screencast from 26-10-2023 09:46:35.webm](https://github.com/Expensify/App/assets/141406735/91e562af-b7a0-4b93-b0c3-446232d01bec)

**Comment by abdulrahuman5196** [comment] 2023-10-30 07:09
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-10-30 11:50
@paultsimura 's proposal here https://github.com/Expensify/App/issues/30366#issuecomment-1779730425 looks good and works well. Other proposals are similar.

🎀 👀 🎀
C+ Reviewed

**Comment by DylanDylann** [comment] 2023-10-30 11:53
@abdulrahuman5196 my proposal mentioned the solution using "InteractionManager.runAfterInteractions", that will fix the issue: delay when refocus and remove using "setTimeout" , please help check

**Comment by abdulrahuman5196** [comment] 2023-11-01 10:50
@DylanDylann Your proposal is only removing the use of setTimeout with runAfterInteractions, whereas the core issue to fix setIsScreenTransitionEnded(false) remains same. And furthermore runAfterInteractions are not expected to work completely with web, as mentioned in the doc - https://reactnative.dev/docs/interactionmanager

**Comment by abdulrahuman5196** [comment] 2023-11-01 10:51
@nkuoch Gentle ping on this https://github.com/Expensify/App/issues/30366#issuecomment-1785022329

**Comment by DylanDylann** [comment] 2023-11-01 10:57
@abdulrahuman5196 thanks for review it

**Comment by DylanDylann** [comment] 2023-11-01 11:14
@abdulrahuman5196 if we should not use interactionManager, so this problem will be fixed in this one https://github.com/Expensify/App/issues/29009#issuecomment-1751609761

**Comment by abdulrahuman5196** [comment] 2023-11-01 11:38
@sophiepintoraetz Can we put this issue on hold for https://github.com/Expensify/App/pull/30675? The same is fix being made at a different place.

**Comment by sophiepintoraetz** [comment] 2023-11-06 01:55
Updated!

**Comment by paultsimura** [comment] 2023-11-08 18:56
@abdulrahuman5196 the PR we were holding for is now merged. The issue is not reproducible anymore on the latest `main`.

**Comment by sophiepintoraetz** [comment] 2023-11-09 03:35
taking off hold.

**Comment by sophiepintoraetz** [comment] 2023-11-09 03:36
@abdulrahuman5196 - do you mind confirming if the issue still stands? If not, then I think payments are:
$500 to @DylanDylann and @abdulrahuman5196 
$50 to @daveSeife

**Comment by sophiepintoraetz** [comment] 2023-11-12 22:41
@DylanDylann - sorry, I'm getting my issues wired - we're all set here!

**Closed by sophiepintoraetz** 2023-11-12 22:41 UTC
Labels: External, Daily, Help Wanted, Bug
