### ISSUE TITLE
[$500] Web - IOU - Incorrect IOU preview component is displayed when requesting money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28142] opened 2023-09-25 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where user A is signed in
2. Open a chat with user B
3. Click on '+' icon > 'Request money' > 'Scan' tab > 'Choose file' > Select an image > 'Request' button
4. Click the request preview
5. Click the receipt image
6. Click the three-dot menu >
Select replace > click on 'Choose file' > select a new image
Open a tab where user B is signed in
Open a chat with user A
9. Click on '+' icon > 'Request money' > 'Manual' tab > enter amount > click on 'Next' button > click on 'Request'
10. Observe that two IOU preview components are created
11. Click on the second iOU preview component > observe that 'RBR' is displayed on LHN

## Expected Result:
A single IOU preview component should be displayed

## Actual Result:
Two IOU preview component is displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/54682f4d-1547-4eff-8be2-0a19701c1664

https://github.com/Expensify/App/assets/115492554/80ac0159-4ec1-4e45-adad-f9dc732d5d89

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695207878592009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd1c573eb7a06cee</li>
        <li>Upwork Job ID: 1706312815653244928</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-09-25 16:19
@garrettmknight @sakluger @jjcoffee 
I could reproduce this on staging but not on latest main. 
Can we confirm if this is still a bug?

**Comment by jjcoffee** [comment] 2023-09-29 11:53
Are you still able to repro @Natnael-Guchima? I find the steps a bit confusing, in the video it looks like we're opening the tab with User B signed in in step 7?

**Comment by Natnael-Guchima** [comment] 2023-10-02 06:02
@jjcoffee Yes, the issue is still reproducible. You are right on the video we are opening a tab where use B is signed in. The steps should have been: 

7. Open a tab where user B is signed in
8. Open a chat with user A

**Comment by sakluger** [comment] 2023-10-02 20:45
I also find this a bit confusing, but I think I understand. When I request money from you and then I edit the receipt image within that request, your next request back to me gets split into two separate request components/elements.

@Natnael-Guchima is that an accurate description of what is happening here?

**Comment by Natnael-Guchima** [comment] 2023-10-03 04:00
@sakluger yes, that is an accurate description of the issue.

**Comment by jjcoffee** [comment] 2023-10-06 13:59
Waiting for proposals.

**Comment by rojiphil** [comment] 2023-10-09 15:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When user A request money using scan receipt from user B and, then, user B requests money using manual request, two report preview comments are displayed in userB’s chat report.

### What is the root cause of that problem?

When user A request money using scan receipt from user B (without entering any request amount), it will create a whisper report preview message (say PREVIEW-A) so that user B is not aware of the scan receipt money request. Now, when user B generates a money request for user A, the optimistic report preview message (say PREVIEW-B) get’s created and `RequestMoney` API is called. The BE, however, detects that PREVIEW-A already exists and updates the money request from user B and sends the updated PREVIEW-A response. This causes a dangling PREVIEW-B that get’s displayed in user B’s chat report along with PREVIEW-A. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?

To solve the problem, we can detect the dangling report preview for IOU report within `shouldReportActionBeVisible` [here](https://github.com/Expensify/App/blob/b3dd8c008790181d195fa79fe61a10e65db805d6/src/libs/ReportActionsUtils.js#L355). We can identify the dangling report preview by checking for a valid a) `childReportID` (compare with `originalReport.linkedReportID`) and b) `childType` (compare with `iou`). Note that `originalReport.linkedReportID` is optimistically assigned during report preview creation [here](https://github.com/Expensify/App/blob/b3dd8c008790181d195fa79fe61a10e65db805d6/src/libs/ReportUtils.js#L2382). If a report preview do not match these conditions, we can consider this to be a dangling report preview, and, prevent display in chat report. 

The condition can be like this:

```
    // Ignore report preview action that does not have a valid linked IOU Report
    if(isReportPreviewAction(reportAction)  && !isPending && !isIOUReportPreviewMessage(reportAction))
    {
        return false;
    }
```

Since `childReportID` and `childType` get’s assigned only on successful API response, we also need to add condition `!isPending` so that the optimistic preview action is displayed during pending action state.

```
function isIOUReportPreviewMessage(reportAction = {}) {
    const {childType = '', childReportID = 0} = reportAction;
    return childType === CONST.REPORT.TYPE.IOU && (String(childReportID) === getIOUReportIDFromReportActionPreview(reportAction));
}
```
### Test Video

https://github.com/Expensify/App/assets/3004659/ad472b89-d564-4c1a-b53c-01b6052f4cec



### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2023-10-10 15:51
Reviewing tomorrow!

**Comment by sakluger** [comment] 2023-10-13 19:18
[Posted to Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1697224679961309) with a friendly bump for @jjcoffee to review the proposal.

**Comment by jjcoffee** [comment] 2023-10-16 09:07
Hmm I can't repro on latest staging (v1.3.84-1) with the exact steps in the issue. @rojiphil or @Natnael-Guchima are you still able to reproduce? Are there any special extra steps?

I can reproduce a similar "double preview component" appearing with a completely new user, but this seems to be a BE issue as User B (new user) doesn't receive the request if there's no amount (e.g. if you use a test image), until you manually add the amount. If User B requests money before the amount is added, then the same double preview component appears.

**Comment by rojiphil** [comment] 2023-10-16 10:57
> are you still able to reproduce? Are there any special extra steps?

@jjcoffee

I am able to reproduce this in the latest main. 
Please refer to the attached video for steps. 
Hope this helps.

https://github.com/Expensify/App/assets/3004659/edde37ee-cdbd-4a64-9fd2-79cc41ee7458

**Comment by rojiphil** [comment] 2023-10-16 13:06
> @rojiphil Hmm so maybe it needs to be that there are no outstanding requests as a precondition (I see that you have previous requests but they are all "paid")?

@jjcoffee 
You are right. And, this can be consistently reproduced under that precondition.

**Comment by sakluger** [comment] 2023-10-16 17:52
Thanks @rojiphil for the help in reproducing this issue.

@jjcoffee given that information, what do you think of @rojiphil's proposal?

**Comment by rojiphil** [comment] 2023-10-18 05:20
@jjcoffee

I think the precursor to this issue comes from [this PR](https://github.com/Expensify/App/pull/24235). 
The tests mentioned in PR do not cover the scenario that we are addressing here.
And, maybe, the `note` comment in the `Tests` section in  PR description refers to this issue.
Hope this helps further. 

Also, awaiting your feedback on the [comment here](https://github.com/Expensify/App/issues/28142#issuecomment-1764986695)

**Comment by jjcoffee** [comment] 2023-10-18 10:12
@rojiphil Do you mean this note?

>Note that for all tests: adding money requests to **an IOU report that already exists** via Global Create creates an extra IOU report action item, because the reportID is not in the URL when going thru **Global Create**. [...] use the + button the chat to create requests.

I think our case is the opposite, we're saying that this only happens when there isn't any existing IOU report right? (Also the issue description we're using the + button rather than global create/FAB).

Are you able to add any context to your RCA as to why this would only be happening when we don't have an existing IOU report?

**Comment by rojiphil** [comment] 2023-10-18 10:59
> I think our case is the opposite, we're saying that this only happens when there isn't any existing IOU report right? (Also the issue description we're using the + button rather than global create/FAB).
> 
> Are you able to add any context to your RCA as to why this would only be happening when we don't have an existing IOU report?

@jjcoffee 

Yes, that is the same note.

Let me try to add context to my RCA.
What I understood by `an IOU report that already exists` means it exists in BE for this chat between User A and User B (generated by User A FE to create a report represented by PREVIEW-A). However, when User B generates a money request for User A (represented by PREVIEW-B), User B’s FE is not aware of the IOU report that already exists in BE and creates a new one locally. This generates a dangling IOU report (represented by PREVIEW-B) in User B’s FE because BE will send back IOU report that existed due to PREVIEW-A as part of the MoneyRequest API response. 
Does this make sense?

Honestly, I didn’t quite get the global create/FAB thing. Maybe, there is another use case for reproducing this via global FAB. 
To me, the test cases really helped me in analyzing our issue.  The test cases only focused on generating a second money request when the first money request had already created an IOU report locally. That works fine. 
However, our case is different as User B is not aware of the IOU report generated by User A.

**Comment by sakluger** [comment] 2023-10-23 20:47
Thanks @jjcoffee, if you can prioritize this one it would be great since it's coming up on one month.

**Comment by jjcoffee** [comment] 2023-10-24 09:52
So going through this again I'm leaning towards this being mainly a BE issue as once User A makes their scan money request:

1. Pusher update with the transaction ID is received by User B, but no IOU report.
2. User B requests money with an optimistic IOU report ID.
3. BE responds by setting that IOU report ID to `null` (i.e. deletes it). However it does not set the relevant `reportPreviewAction` to null, so that action remains.

So I think we can either ensure that the pusher comes with the new IOU report (as happens with manual requests), or in step 3 above set the `reportPreviewAction` to null.

**Comment by rojiphil** [comment] 2023-10-24 12:10
> So I think we can either ensure that the pusher comes with the new IOU report (as happens with manual requests), or in step 3 above set the `reportPreviewAction` to null.

@jjcoffee
I think, it’s worth mentioning [this issue](https://github.com/Expensify/App/issues/29906#issuecomment-1771022287) here where I had suggested a similar option of (2) and (3) but in a different context. 
Also, as the initial scan receipt is a whisper message in User A side, it may be intentional to not send a whisper message to other side i.e. User B. So, not sure if (1) would be feasible. 
Anyways, I too think that fixing this issue in BE is better.

**Comment by sakluger** [comment] 2023-10-27 01:56
Okay, thanks @jjcoffee for the review and thoughts! I'll assign a BE engineer to take a look.

**Comment by danieldoglas** [comment] 2023-10-30 15:35
I think this is related to receipt scanning methods. I'll assign someone from wave4 to take a look since they will probably have more context on this than me.

**Comment by danieldoglas** [comment] 2023-10-30 15:36
@luacmartins , I think this is related to the new code added for receipt scanning. Can you please take a look into it and route it internally to the wave4 team if necessary?

**Comment by luacmartins** [comment] 2023-10-30 16:11
Sure, will do

**Comment by luacmartins** [comment] 2023-10-31 19:10
I don't think that's the correct solution because it'd create a jarring experience for the user when most requests would be merged. I think instead we would create a new one in the BE and just push the new reportID to the FE

**Comment by luacmartins** [comment] 2023-10-31 19:20
TBH I think this is a really edge case scenario and I don't think we should prioritize fixing this issue. I'm gonna close it for now, feel free to reopen if you think we should fix this.

**Closed by luacmartins** 2023-10-31 19:20 UTC
Labels: Engineering, Daily, Internal, Bug
