### ISSUE TITLE
[$1000] Web-Workspace-App does nothing on clicking on 3 dots when modal is open (modal closes for phone)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24284] opened 2023-08-08 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace
3. Click on 3 dots, modal will be displayed, again click on 3 dots and observe that it does nothing
4. Visit any user report, click on phone icon in header, it will open modal, again click on phone icon and observe that it will close the modal
5. Similar working happens for all other modals like Actions, New, Emoji

## Expected Result:
App should close the modal when we click on 3 dots again like it does for all other type of modals throughout the app

## Actual Result:
App does nothing when we click on 3 dots again

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/31cf78ae-200e-4281-b1c2-c3d20f8a3ebf

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691491820472469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ad6bb952da737f6</li>
        <li>Upwork Job ID: 1691525643834966016</li>
        <li>Last Price Increase: 2023-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26139650</li>
<li>ishpaul777 | Contributor | 26139655</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-08-08 18:02
# proposal
# Problem 
Web-Workspace-App does nothing on clicking on 3 dots when modal is open

### root cause
we are not closing the modal here onPress

### changes
close the modal if isPopupMenuVisible using hidePopoverMenu

**Comment by mkhutornyi** [comment] 2023-08-08 18:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does nothing on clicking 3 dots when modal is open

### What is the root cause of that problem?
When click 3 dots, showPopoverMenu is called instead of toggle
https://github.com/Expensify/App/blob/32326f6fa053f3c4c9ccfb3aad7c11d3834da5ee/src/components/ThreeDotsMenu/index.js#L89-L95

### What changes do you think we should make in order to solve the problem?
We should update logic similar to VideoChatButtonAndMenu so when click, popover open/closed status should be toggled

https://github.com/Expensify/App/blob/32326f6fa053f3c4c9ccfb3aad7c11d3834da5ee/src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js#L90-L100

**Comment by puneetlath** [comment] 2023-08-08 18:11
I don't think we need to block the deploy over this. Removing the label.

**Comment by ishpaul777** [comment] 2023-08-08 18:24
are these intentional non toggle popovers or do we need to make them toggle popovers ?

**Comment by dhanashree-sawant** [comment] 2023-08-08 18:29
Hi @aimane-chnaif, one of the effects of it is that we can write and send anything in background even when menu is open, it doesn't do that for any other modal, I think that should be worth fixing.

**Comment by msapple0338** [comment] 2023-08-08 19:02
I don't think this is blocker, even not a bug. Just inconsistency issue.

**Comment by slafortune** [comment] 2023-08-09 20:06
@PauloGasparSv and @aimane-chnaif - do you think we should move forward with [this](https://github.com/Expensify/App/issues/24284#issuecomment-1670102362) or close

**Comment by PauloGasparSv** [comment] 2023-08-11 17:21
Thks so much for all the help here @aimane-chnaif 

> @PauloGasparSv and @aimane-chnaif - do you think we should move forward with https://github.com/Expensify/App/issues/24284#issuecomment-1670102362 or close

I'm not sure. **IMO we should go for consistency**  (but I also don't consider this a "Bug").

Would love to hear your opinion on this too @slafortune

If you agree then let's add the `External` label here and change [these](https://github.com/Expensify/App/issues/24284#issuecomment-1670093126) "Non-toggle popovers" so they close when we click again!

**Comment by PauloGasparSv** [comment] 2023-08-11 17:29
> If so, can I be C+ on this issue as I already reviewed and have full context.

Thks again, will leave you assigned already!

**Comment by slafortune** [comment] 2023-08-15 18:18
> If you agree then let's add the External label here and change https://github.com/Expensify/App/issues/24284#issuecomment-1670093126 "Non-toggle popovers" so they close when we click again!

👍 Ah - yes, I do agree for consistency, I do like this suggestion.

**Comment by ishpaul777** [comment] 2023-08-15 19:08
@aimane-chnaif understood! moving forward i'll keep this in mind.

**Comment by ruiyun43** [comment] 2023-08-15 19:44
Hi.  Glad meet you here
I am ruiyunhuang from USA.
I am Senior web and mobile app developer with 10 years of experience.
I have rich experience in react, react native, next.js, redux and hook.
I am also good at implement interactivity using react native.
https://github.com/SuperStar1012/Lilipad.
this is my previous front end code with implement interactivity.

to solve this problem I need to use a onPress() function in react native.
then using flag that monitoring the open status of modal.
I can fix this issue with in one day.
please contact me.
I am always ready to solve your issue immediately.
Thanks.

**Comment by ruiyun43** [comment] 2023-08-15 20:00
and also we have to use the TouchableWithoutFeedBack component.
That's all.
Thanks.

**Comment by ruiyun43** [comment] 2023-08-15 20:46
I got it. but I think that explain about the solution to solve this problem is not enough with speaking. I want to explain about the solution on call.
btw I don't want get paid from upwork.
so if you can only pay to me through upwork, I can't work with you.

**Comment by ishpaul777** [comment] 2023-08-15 21:00
Hi @ruiyun43, this issue is assigned to me already. Please go through the [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md), 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ruiyun43** [comment] 2023-08-15 21:27
Hmm.
got it.

**Comment by ishpaul777** [comment] 2023-08-16 13:07
@aimane-chnaif, how can i test ButtonWithDropdownMenu? (where is it used and how can i see the usage)?
also what should be done to test usage of AddPaymentMethodMenu in [BaseKYCWall](https://github.com/Expensify/App/blob/main/src/components/KYCWall/BaseKYCWall.js#L103C10-L106C12)?

**Comment by ishpaul777** [comment] 2023-08-16 13:28
i tried overriding beta permission but as soon as I click on workspace chat it disappears, how can i get the beta permissions?

**Comment by ishpaul777** [comment] 2023-08-16 13:38
thanks @aimane-chnaif, just one question if i ask for permission for email@gmail.com. all test accounts  (eg."email+abcd@gmail.com") got the permission right? or should i ask for all the test email accounts?

**Comment by ishpaul777** [comment] 2023-08-16 14:12
okay thanks, and what are testing steps for AddPaymentMethodMenu in [BaseKYCWall](https://github.com/Expensify/App/blob/main/src/components/KYCWall/BaseKYCWall.js#L103C10-L106C12)?

**Comment by PauloGasparSv** [comment] 2023-08-16 14:19
Hey @ishpaul777 I found the [slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1692193697509369) where you request access.

Sorry for not checking this myself but do you know what exact Betas you need?
I think we should probably **add you to the specific Betas you need** instead of enabling all : )

> thanks @aimane-chnaif, just one question if i ask for permission for [email@gmail.com](mailto:email@gmail.com). all test accounts (eg."[email+abcd@gmail.com](mailto:email+abcd@gmail.com)") got the permission right? or should i ask for all the test email accounts?

Aimane already answered this but yeah, I'm pretty sure it doesn't work like that and that the betas will only be applied to the account you specifically ask them for!

**Comment by ishpaul777** [comment] 2023-08-16 14:27
Thanks for your response @PauloGasparSv, can you add me to the betas that are required for testing of AddPaymentMethodMenu in [BaseKYCWall] (https://github.com/Expensify/App/blob/main/src/components/KYCWall/BaseKYCWall.js#L103C10-L106C12)
and ButtonWithDropdownMenu.

**Comment by PauloGasparSv** [comment] 2023-08-16 14:36
> Thanks for your response @PauloGasparSv, can you add me to the betas that are required for testing of AddPaymentMethodMenu in [BaseKYCWall](https://github.com/Expensify/App/blob/main/src/components/KYCWall/BaseKYCWall.js#L103C10-L106C12) and ButtonWithDropdownMenu.
> 
> email - [ishpaul207@gmail.com](mailto:ishpaul207@gmail.com), [ishpaul207+web@gmail.com](mailto:ishpaul207+web@gmail.com), [ishpaul207+native@gmail.com](mailto:ishpaul207+native@gmail.com)

Sure thing @ishpaul777!

As [mentioned on slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1692195656166079?thread_ts=1692193697.509369&cid=C01GTK53T8Q) I have added your 3 accounts to the `policyExpenseChat` Beta!

Please note that Betas will usually take up to an hour to have an effect. So if this doesn't work let's wait a bit before checking if you need another Beta or something : D

**Comment by ishpaul777** [comment] 2023-08-16 14:40
I greatly appreciate your assistance, @PauloGasparSv. Could you kindly provide a response to https://github.com/Expensify/App/issues/24284#issuecomment-1680696562

**Comment by slafortune** [comment] 2023-08-22 21:14
External issue reporter - @dhanashree-sawant - $250 - [OFFER SENT](https://www.upwork.com/nx/wm/offer/26271824)
Contributor that fixed the issue - @ishpaul777, $1500 
Contributor+ that helped on the issue and/or PR -  @aimane-chnaif  $1500
🎉 Speed bonus to be given

**Comment by slafortune** [comment] 2023-08-28 14:43
Paid

**Closed by slafortune** 2023-08-28 14:43 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
