### ISSUE TITLE
[$500] iOS - Wallet - Bank button is not responsive

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40077] opened 2024-04-11 06:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4488516
**Email or phone of affected tester (no customers):** applausetester+vd_ios041024.3@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: user must have created a Workspace and have added a bank account to the WS, so the bank account can be displayed on the Wallet page.

1. Go to Settings > Wallet.
2. Tap on the added bank account or on the 3 dots menu to the right of it.
3. Verify it is not responsive.

## Expected Result:
The bank button and the 3 dots menu should be responsive.

## Actual Result:
The bank button and the 3 dots menu are not responsive.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c699347f-3514-4dcf-ad8d-15d911f176b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01955b986561b0d5cb</li>
        <li>Upwork Job ID: 1778388746136018944</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-11 06:06
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-11 06:07
Production 


https://github.com/Expensify/App/assets/115492554/7a5e1d03-9f38-47b7-b394-53353e779298

**Comment by Julesssss** [comment] 2024-04-11 11:44
Hey @izarutskaya, is the video marked production correct? It looks like a different issue that was opened

**Comment by godofoutcasts94** [comment] 2024-04-11 11:47
> Production
> 
>  RPReplay_Final1712806014.MP4

This video is not related to this issue @izarutskaya

**Comment by godofoutcasts94** [comment] 2024-04-11 11:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Wallet - Bank button is not responsive
### What is the root cause of that problem?
I think the problem is with native view for wallet page.
### What changes do you think we should make in order to solve the problem?

I think we need to redesign wallet page for native devices.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by ikevin127** [comment] 2024-04-11 14:27
@godofoutcasts94 Thanks for the proposal! Unfortunately your RCA and solution are not correct.

**Comment by ikevin127** [comment] 2024-04-11 14:30
> which for some reason doesn't work

@ZhenjaHorbach Any clue regarding the offending PR which caused the FlashList to not work anymore ?

**Comment by ikevin127** [comment] 2024-04-11 14:50
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/40077#issuecomment-2049762369) looks good to me. The RCA is correct, the proposed solution fixes the issue and the offending PR was identified as https://github.com/Expensify/App/pull/13767 in https://github.com/Expensify/App/issues/40077#issuecomment-2049856491.

🎀👀🎀 C+ reviewed

**Comment by godofoutcasts94** [comment] 2024-04-11 14:50
I don't think that PR is responsible it @ikevin127

**Comment by MitchExpensify** [comment] 2024-04-11 23:52
I cannot reproduce the unresponsive add bank or 3 dot menu button in wallet on version v1.4.62-3

**Comment by WoLewicki** [comment] 2024-04-12 09:14
I also cannot reproduce it locally. Does the issue appear only if you have some bank accounts added already @izarutskaya ?

**Comment by ikevin127** [comment] 2024-04-12 09:40
⚠️  Issue still reproducible on latest main branch (v1.4.62-4 Develop).

> Does the issue appear only if you have some bank accounts added already ?

> [!tip]
> Correct, try reproducing with these steps:
> 1. Go to Settings > About > Troubleshoot > Toggle **Use Staging Server** on.
> 2. Go to Settings > Wallet > + Add bank account -> Personal bank account.
> 3. Add CityBank BA using `user_good` / `pass_good` credentials (should look like image below when done).
> **(Important substep)** After (3.) choose one of the 2 options: 
> - navigate back to the Settings page
> - close / re-open the app
> 4. Go to Settings > Wallet and tap on the **newly added bank account item** and notice it's non-responsive.


<img width="340" alt="Screenshot 2024-04-12 at 12 24 21" src="https://github.com/Expensify/App/assets/56457735/a8850815-84c6-412f-b175-6b2dd69930f4">

> [!note]
> 1. After step (3.), it's important to perform one of the 2 actions, otherwise  tapping on the option **will work** and the issue won't seem reproducible.
> 2. The `+ Add bank account` button is always responsive as it's not within the `FlashList`.

cc @MitchExpensify @WoLewicki

**Comment by WoLewicki** [comment] 2024-04-12 13:42
> Go to Settings > About > Troubleshoot > Toggle Use Staging Server on.

I don't have such option in `Troubleshoot`. Are there some steps necessary to get it?

**Comment by WoLewicki** [comment] 2024-04-12 20:30
Could you check if https://github.com/Expensify/App/pull/40191 solves the issue?

**Comment by MitchExpensify** [comment] 2024-04-15 20:53
> If all the issues are related to the patch and Flashlist. Let's hold these issues to be assigned to anyone until we have a fix for that.

Which issues were you referring to holding on specifically @parasharrajat ?

**Comment by kosmydel** [comment] 2024-04-16 10:39
Hey, I'm from Software Mansion.

I was unable to reproduce this issue on `v.1.4.62-10 Develop` version. I followed the steps from the original post and [this comment](https://github.com/Expensify/App/issues/40077#issuecomment-2051417291). 

Can someone confirm, that the issue is still reproducible?

**Comment by ikevin127** [comment] 2024-04-16 14:46
> Could you check if https://github.com/Expensify/App/pull/40191 solves the issue?

@WoLewicki I confirm that with a clean build of https://github.com/Expensify/App/pull/40191, the issue is fixed 🎉

**Comment by roryabraham** [comment] 2024-04-16 18:20
I'm not able to retest this on main - requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1713291635862759

**Comment by kbecciv** [comment] 2024-04-16 19:01
@roryabraham Issue is still reproducible on IOS app with build 1.4.62.11

https://github.com/Expensify/App/assets/93399543/c2deea3e-c3ea-49db-805a-288c128f247b

**Comment by roryabraham** [comment] 2024-04-16 20:56
ok, I was able to reproduce this on main

**Comment by roryabraham** [comment] 2024-04-16 22:35
This will be fixed by https://github.com/Expensify/App/pull/40191 in 1.4.62-13, deploying [here](https://github.com/Expensify/App/actions/runs/8713394572/job/23901703032)

**Comment by roryabraham** [comment] 2024-04-16 23:03
confirmed this is fixed on staging, no payments due so I'm closing it

**Closed by roryabraham** 2024-04-16 23:03 UTC
Labels: DeployBlockerCash, External, Engineering, Daily, Bug
