### ISSUE TITLE
mWeb - Profile - Save button overlaps zoom and rotation functions when trying to upload photo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24004] opened 2023-08-01 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on the avatar in the top right corner to navigate to "Settings"
3. Tap on the avatar again
4. Tap on "Upload Photo" and choose any photo

## Expected Result:
The zoom and rotation functions should be fully visible

## Actual Result:
The "Open in the New Expensify app" top banner causes the rest of the content of the page to drop, causing the save button to partially cover zoom and rotation functions.
The banner at the top of the page that invites you to go to the Expensify App is the reason for this overlap on small screens. The ‘Save’ button is floating and docked to the screen bottom, and the rest of the content stream is moved down from the top banner. If you remove Expensify App, the overlap will disappear.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Uploading Bug6149359_JLSS1271.mp4…

![Bug6149359_IMG_E8515](https://github.com/Expensify/App/assets/78819774/afb3efcd-c78c-4ed7-9aa5-f6500ed2a767)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-08-01 15:04
Dupe of https://github.com/Expensify/App/issues/17752

**Closed** 2023-08-04 16:23 UTC
Labels: Daily, Overdue, Bug
