### ISSUE TITLE
[$1000] Android crash: Value for disabled cannot be cast from String to Boolean

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#14599] opened 2023-01-26 18:54 UTC
# Problem
Coming from this [Crashlytics](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/54b191bc71967d02000a6ee78164be67?time=last-seven-days&versions=1.2.59-1%20(1001025901)&sessionEventKey=63D13FC200370001665A28A9C74CC535_1771045925809069720) crash on android, it seems like we are trying to cast a string to boolean somewhere and that's crashing the android app.

I don't have reproducible steps for this issue yet.

# Why is this important?
Prevents app from crashing

# Solution?
Investigate where the crash is happening and fix the type cast

Logs

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'accessibilityState' of a view managed by: RCTView
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:101)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:86)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1038)
       at android.view.Choreographer.doCallbacks(Choreographer.java:864)
       at android.view.Choreographer.doFrame(Choreographer.java:787)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

```
Caused by com.facebook.react.bridge.UnexpectedNativeTypeException: Value for disabled cannot be cast from String to Boolean
       at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:140)
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:115)
       at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:146)
       at com.facebook.react.uimanager.BaseViewManager.setViewState(BaseViewManager.java:290)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:93)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:86)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1038)
       at android.view.Choreographer.doCallbacks(Choreographer.java:864)
       at android.view.Choreographer.doFrame(Choreographer.java:787)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b1a75297f2e4d9f</li>
        <li>Upwork Job ID: 1620202724309737472</li>
        <li>Last Price Increase: 2023-01-30</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-01-26 22:40
>Error while updating property 'accessibilityState' of a view managed by: RCTView

Maybe this?

https://github.com/Expensify/App/blob/1a985e61b5ef2182a258310d6c692fbc13a37c63/src/components/Checkbox.js#L108-L110

I'm not sure how this is all supposed to work though https://reactnative.dev/docs/0.70/view#accessibilitystate

Maybe you need to provide all the other values since the errors says "Value for disabled cannot be cast from String to Boolean" and we are not providing anything for `disabled`. Docs say they are not required though so my guess is this is a RN core bug.

![2023-01-26_12-39-41](https://user-images.githubusercontent.com/32969087/214966881-06133315-877b-47b3-a99b-689c763bf212.png)

**Comment by marcaaron** [comment] 2023-01-26 22:47
Related: https://github.com/facebook/react-native/issues/35119

There was a suggestion that something somewhere might be passing a string for a `disabled` prop. Didn't look though.

**Comment by luacmartins** [comment] 2023-01-27 00:02
I think we are passing a string to a disabled prop. I took a quick look but I just found [this instance](https://github.com/Expensify/App/blob/aa90b4310192f638684c01732481e8a1246fcf78/src/pages/ReimbursementAccount/CompanyStep.js#L141-L142) that passes a string to a TextInput, which doesn't cause the crash.

**Comment by luacmartins** [comment] 2023-01-30 23:29
I'll open this issue to be external in case a contributor wants to dig into where this happens. We only have logs that shows this happening, but we don't have reproducible steps yet. Meanwhile, I'll put up a PR to fix the instance I found above for TextInputs.

**Comment by mo-4444** [comment] 2023-01-31 00:10
accessibilityState 
Should be a boolean, you are passing an object that has {checked within}

Rather you should be passing {{this.props.isChecked}} in App/src/components/Checkbox.js

**Comment by mo-4444** [comment] 2023-01-31 00:31
![image](https://user-images.githubusercontent.com/55030388/215627843-0d8c916c-5d7e-454f-8812-3f7779b4f162.png)

If the issue is stemming from an iOS device, then this can be the cause.
The suggest that to use the accessiblityHint instead of status.

**Comment by marcaaron** [comment] 2023-01-31 01:22
the issue is on Android.

**Comment by eh2077** [comment] 2023-01-31 01:48
**Proposal**

RAC

This issue related to TypeScript's `&&` operator feature

> The && operator permits the operands to be of any type and produces a result of the same type as the second operand.

We pass `String` value to variable `disabled` here
https://github.com/Expensify/App/blob/d5cfa894155283cb81ca5a17b6b623e534164ae7/src/pages/ReimbursementAccount/CompanyStep.js#L141-L142

We can use `!!` operator to fix this 
```diff
diff --git a/src/pages/ReimbursementAccount/CompanyStep.js b/src/pages/ReimbursementAccount/CompanyStep.js
index 9309a31701..57c0da3b39 100644
--- a/src/pages/ReimbursementAccount/CompanyStep.js
+++ b/src/pages/ReimbursementAccount/CompanyStep.js
@@ -166,7 +166,7 @@ class CompanyStep extends React.Component {
                         label={this.props.translate('companyStep.legalBusinessName')}
                         inputID="companyName"
                         containerStyles={[styles.mt4]}
-                        disabled={shouldDisableCompanyName}
+                        disabled={!!shouldDisableCompanyName}
                         defaultValue={this.props.getDefaultStateForField('companyName')}
                         shouldSaveDraft
                     />
@@ -206,7 +206,7 @@ class CompanyStep extends React.Component {
                         label={this.props.translate('companyStep.taxIDNumber')}
                         containerStyles={[styles.mt4]}
                         keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
-                        disabled={shouldDisableCompanyTaxID}
+                        disabled={!!shouldDisableCompanyTaxID}
                         placeholder={this.props.translate('companyStep.taxIDNumberPlaceholder')}
                         defaultValue={this.props.getDefaultStateForField('companyTaxID')}
                         shouldSaveDraft
```

**Comment by priyeshshah11** [comment] 2023-01-31 05:11
## Proposal

### Problem
I think we are either passing a string or an empty object to the disabled prop somewhere in the app (will try to dig in).

### Solution 

We should convert all the disabled props to a boolean value before passing it to the react-native components such as Button, TouchableOpacity, Pressable, etc by doing the following to fix the issue for sure without knowing where exactly it is coming from.

```
disabled={!!this.props.disabled}
```

**Comment by dhairyasenjaliya** [comment] 2023-01-31 05:49
**Proposal**

- I think this is a known issue from React 0.70 whereby for disabling touchable/pressable components it needs boolean values and somehow  

**Solution**

- We are not passing disable props on `index.native` file that makes empty state for android and for iOS by default it takes false so we need to pass disable same as web to the below file 

https://github.com/Expensify/App/blob/f624d828408543e64422c18a5156ec3e493c0253/src/components/CheckboxWithTooltip/index.native.js#L6-L15

**Changes**
```diff
    <CheckboxWithTooltipForMobileWebAndNative
        style={props.style}
        isChecked={props.isChecked}
        onPress={props.onPress}
        text={props.text}
        toggleTooltip={props.toggleTooltip}
+        disabled={props.disabled}
    /> 
   ````

**Comment by dhairyasenjaliya** [comment] 2023-01-31 05:57
**Proposal 2**

- We can validate by adding `Boolean()` which makes sure passed values have true/false on `Checkbox.js`
```diff

            <Pressable
+               disabled={Boolean(this.props.disabled)}
                onPress={this.firePressHandlerOnClick}
                onMouseDown={this.props.onMouseDown}
                onFocus={this.onFocus}
                onBlur={this.onBlur}
                ref={this.props.forwardedRef}
                onPressOut={this.onBlur}
                style={this.props.style}
                onKeyDown={this.handleSpaceKey}
                accessibilityRole="checkbox"
                accessibilityState={{
                    checked: this.props.isChecked,
                }}
>

```

**Comment by eh2077** [comment] 2023-02-03 15:33
> @priyeshshah11 @dhairyasenjaliya @eh2077 anyone has experienced this crash at least 1 time on android? I suggest to assign someone who has consistent reproducible step since the fix will be easy and straightforward once we catch the crash. (The reproducer will provide solution I believe)

Hi @aimane-chnaif 

I can reproduce the crash stably as I mentioned in the reproduction steps section of my previous proposal.

**Comment by eh2077** [comment] 2023-02-03 16:38
> Have you ever experienced `disabled` value coming from backend is string?

@aimane-chnaif 

No, I haven’t. I tried to reproduce it with real backend data but I'm only able to test it by adding PayPal payment method. 

I think the crash case about `Payments` page I simulated should be worth fixing. I'll be happy to hear your thoughts about it.

**Comment by marcaaron** [comment] 2023-02-03 18:01
Just for reference... there have only been 2 of these crashes in the past 30 days and 0 in the past 7 days. I think we could probably close this one?

**Comment by tgolen** [comment] 2023-02-06 14:34
I agree with Marc. Let's close this until there are repeated crashes.

**Closed by tgolen** 2023-02-06 14:34 UTC
Labels: Reviewing, External, Daily, Needs Reproduction, Help Wanted, Bug
