### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Android - Room - Room background is severely cut off when created offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42757] opened 2024-05-29 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/35045
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to FAB > Start chat > Room
4. Create a room.

## Expected Result:
The background image in room will not be severely cut off.

## Actual Result:
The background image in room is severely cut off.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4032b9a3-240a-47ea-93bc-1ff46e36c879

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01542e8b76660e8c22</li>
        <li>Upwork Job ID: 1798696161576342702</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 102706529</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by izarutskaya** [comment] 2024-05-29 12:15
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-29 12:15
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-05-29 12:15
Production
![Screenshot_2024-05-29-15-05-10-26_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/115492554/79ca68dc-f3f4-46a0-b826-f4eb7214c032)

**Comment by puneetlath** [comment] 2024-05-29 16:27
This feels like a minor UI issue. I think it doesn't need to block the deploy.

**Comment by mallenexpensify** [comment] 2024-05-29 17:04
I agree this doesn't need to be a deploy blocker. Looks like @luacmartins removed the label so I'm bumping to `Daily`. 
Tried multiple times to reproduce on Android via BrowserStack with no luck.

**Comment by flodnv** [comment] 2024-06-03 13:48
Sorry, what is cutoff? I don't see it 😕

**Comment by mallenexpensify** [comment] 2024-06-06 00:39
The bug in the OP is this
<img width="549" alt="image" src="https://github.com/Expensify/App/assets/22508304/a6bb1b49-fa57-4580-9866-9fa428a71a81">

and the way it's supposed to look is to have the full background image, like here
<img width="661" alt="image" src="https://github.com/Expensify/App/assets/22508304/f87aa2b8-f522-4a31-aa14-3d817fc40a6a">

**Comment by jjcoffee** [comment] 2024-06-12 08:40
Waiting for proposals!

**Comment by jnowakow** [comment] 2024-06-12 09:08
I'm from Software Mansion agency and I'll work on it

**Comment by jnowakow** [comment] 2024-06-12 12:03
I can reproduce the issue. Moreover when I go offline on Android many SVGs are missing, for example:

<img width="445" alt="image" src="https://github.com/Expensify/App/assets/56261019/362a272f-c71c-4177-b31e-2055ae8f9e32">

Do you also see this problem?

**Comment by jjcoffee** [comment] 2024-06-12 12:13
@jnowakow Thanks for looking into this! I do see the same issue with the missing SVGs.

**Comment by mallenexpensify** [comment] 2024-06-12 16:10
Assigned to @jnowakow and added to #vip-vsb cuz it doesn't have to do with expense. 
@jnowakow , please try to find additional instances that you can fix at the same time (since you already found [some](https://github.com/Expensify/App/issues/42757#issuecomment-2162838036))

**Comment by mallenexpensify** [comment] 2024-06-17 21:31
Thanks @jnowakow , I bumped it to weekly, it's not a high priority issue.

**Comment by jjcoffee** [comment] 2024-06-18 13:36
[PR](https://github.com/Expensify/App/pull/43895) approved by me.

**Comment by jjcoffee** [comment] 2024-07-10 07:40
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23710
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23710/files#r1671779151
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go offline
2. Create new room chat
3. Verify that the chat's background image is displayed correctly without any cut-off

Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment] 2024-07-11 01:28
Contributor+: @jjcoffee paid $250 via Upwork. 

Thx for the TestRail steps, issue created
- https://github.com/Expensify/Expensify/issues/411945

**Closed by mallenexpensify** 2024-07-11 01:28 UTC
Labels: External, Engineering, Daily, Monthly, Awaiting Payment, Bug
