### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Collect approvers] [$500] Expense - Owner of submission message changes from admin to employee when admin submits it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35263] opened 2024-01-26 19:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [Employee] Go to workspace chat
2. [Employee] Create a manual request and do not submit it
3. [Admin] Go to the workspace chat with employee
4. [Admin] Go to expense report
5. [Admin] Click Submit

## Expected Result:
The report submission message "You (on behalf of employee) submitted this report to you" is owned by the admin

## Actual Result:
The report submission message "You (on behalf of employee) submitted this report to you" is owned by the admin first, then it quickly changes to become owned by the employee, when the message indicates "You" which means the admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f0132a91-4d63-47e4-a434-d88d62fe9947

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b83478ffce02da03</li>
        <li>Upwork Job ID: 1750959089237659648</li>
        <li>Last Price Increase: 2024-01-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment] 2024-01-26 19:10
We think that this bug might be related to #6. 
CC @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-01-26 19:19
I think probably Wave 8 as it seems mostly like an admin-side bug

**Comment by rezkiy37** [comment] 2024-02-02 13:57
So, I've investigated the bug. I can confirm that it still exists. I can say that it is a backend bug. The root cause that the backend attaches an incorrect `actorAccountID` to a submit action item. The app optimistically attaches a current (_admin - 14859714_) user `actorAccountID`, but the backend responses with another value (_employee - 16218756_). Looks like a request it correct:

<img width="832" alt="Request" src="https://github.com/Expensify/App/assets/57314631/ffc9485f-fda5-4859-bd1d-5e120e467b76">

Response:

<img width="841" alt="Response" src="https://github.com/Expensify/App/assets/57314631/07652d04-6f72-4909-bd9f-b75c8b78e3e1">

Video:

https://github.com/Expensify/App/assets/57314631/de52ceaf-e2db-4ff6-951e-b64a38fd8910

**Comment by rezkiy37** [comment] 2024-02-05 15:02
@slafortune, please take a look at a comment above.

**Comment by RachCHopkins** [comment] 2024-02-06 20:41
This may be the same as https://github.com/Expensify/App/issues/33819

**Comment by slafortune** [comment] 2024-02-08 21:38
Hot pick label added

**Comment by rezkiy37** [comment] 2024-02-09 11:38
Yes, please check/review a [comment](https://github.com/Expensify/App/issues/35263#issuecomment-1923880909).

**Comment by rezkiy37** [comment] 2024-02-12 14:22
Still waiting on some feedback about a comment above.

**Comment by trjExpensify** [comment] 2024-02-12 14:25
@youssef-lr @marcochavezf this one is wave7 related, can you help @rezkiy37 out on [this comment](https://github.com/Expensify/App/issues/35263#issuecomment-1923880909) please? Thanks!

**Comment by marcochavezf** [comment] 2024-02-13 17:25
Sure, I will assign myself to this one to check it out today.

**Comment by marcochavezf** [comment] 2024-02-14 01:07
Looks like we're setting the `actorAccountID` in the backend [here](https://github.com/Expensify/Web-Expensify/blob/44af69669f86d4e03f3a02c6e9a9b2c94d161ae7/lib/Report/Action/Item.php#L689), but I still need to figure out why we're changing it

**Comment by marcochavezf** [comment] 2024-02-15 16:51
Yesterday I was focused on another critical, I will continue with this one today

**Comment by marcochavezf** [comment] 2024-02-16 01:45
The `actorAccountID` is defined by the authToken, and we're changing the authToken from the manager to the report owner [here](https://github.com/Expensify/Web-Expensify/blob/2b2015979010905d3d484db322261e799561802a/lib/ReportAPI.php#L3371). Seems we'd need to change the admin-submit auth token logic.

**Comment by marcochavezf** [comment] 2024-02-16 23:51
[PR up](https://github.com/Expensify/Auth/pull/9959)

**Comment by slafortune** [comment] 2024-02-28 16:38
@marcochavezf @parasharrajat can you confirm this can be closed on March 1 as the 7 day mark with no regressions and as far as I can tell no payment is due, @parasharrajat didn't review and @rezkiy37 is an expert contributor.
TIA

**Comment by marcochavezf** [comment] 2024-03-05 00:54
PR to cover the edge case merged. Still working on a solution for this case.

**Comment by trjExpensify** [comment] 2024-03-05 13:12
Do you need to remove the `Hot pick` label, @marcochavezf?

**Comment by marcochavezf** [comment] 2024-03-05 17:06
I suppose the `Hot pick` label is for issues without an engineer, correct? If so I think yeah we should remove it

**Comment by trjExpensify** [comment] 2024-03-06 13:06
Yes, exactly.

**Comment by marcochavezf** [comment] 2024-03-11 17:39
I will continue with the analysis today

**Comment by trjExpensify** [comment] 2024-03-13 22:13
How did that analysis go?

**Comment by marcochavezf** [comment] 2024-03-14 01:50
This one has been a bit complex. I've been testing two possible solutions so far and each one has its side effects. Tomorrow I will try a third one which I think will fix the issue

**Comment by marcochavezf** [comment] 2024-03-14 21:12
@rezkiy37 seems it's not a good idea to change the `actorAccountID` since we have logic that depends on it in OldDot and we use the `admin` value from the reportAction to check if the aciton was taken on behalf of the member. How feasible do you see to use another property for the avatar in this case? Like `adminAccountID` in the reportAction? If it exists, we can use that property instead of `actorAccountID`.

@trjExpensify, just to confirm, for NewDot we always want to show the message `submitted %amount%` even if the admin took it on behalf of the user (we would just change the avatar icon), correct? i.e. we don't show a message like `You (on behalf of marco@expensify.com via admin-submit) submitted this report to you` anymore.

**Comment by trjExpensify** [comment] 2024-03-15 11:21
>@trjExpensify, just to confirm, for NewDot we always want to show the message submitted %amount% even if the admin took it on behalf of the user (we would just change the avatar icon), correct?

Yep!

**Comment by rezkiy37** [comment] 2024-03-15 13:27
> @rezkiy37 seems it's not a good idea to change the actorAccountID since we have logic that depends on it in OldDot and we use the admin value from the reportAction to check if the aciton was taken on behalf of the member. How feasible do you see to use another property for the avatar in this case? Like adminAccountID in the reportAction? If it exists, we can use that property instead of actorAccountID.

If we cannot change the `actorAccountID`, therefore we need to update the app logic to use the admin value as well. 

https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/libs/ReportUtils.ts#L3365-L3366

After this change, we will display only some admin. So, we need to integrate a new property to use value here:

https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/pages/home/report/ReportActionItemSingle.tsx#L81

Btw, what does `delegateAccountID` mean of an action?

**Comment by marcochavezf** [comment] 2024-03-15 14:28
Yeah, that will be the best path, because we want to keep the `actorAccountID` as the member for backwards compatibility with OldDot (and also probably in some parts of NewDot where we compare it with the current session) and instead use `adminAccountID` as a "meta-state" of `actorAccountID` to know the admin took the action on behalf the user.

For `ReportActionItemSingle` I think we should rename that to `accountIDToDisplay` or something similar to avoid more confusion 😄 

> Btw, what does delegateAccountID mean of an action?

This is configured here in OldDot and also it's used to take actions on behalf of the member. I was also thinking to use this property for this case, but for logs recording it already has its unique purpose

<img width="1257" alt="Screenshot 2024-03-15 at 8 03 49 a m" src="https://github.com/Expensify/App/assets/6829422/a4b41c01-2556-4ee8-be26-f9c8a32a8a96">

**Comment by rezkiy37** [comment] 2024-03-15 14:33
So, how would we call a new property of a report action to represent a correct account ID?

**Comment by marcochavezf** [comment] 2024-03-15 15:06
The `actorAccountID` is the accountID saved in the report action. Historically we've been saving the accountID corresponding to the user that initiated the action (the member in this case) and use other properties to know if another user took the action instead of the original accountID (like admin or delegate). 

So the correct account ID should be the actorAccountID in a report action, and we should use another name (according to the context) if we're using an accountID different from the original actorAccountID.

I know this is confusing 😅 but after trying to change the `actorAccountID` in the backend, I realized it's a legacy design that might require a big refactor but I don't think it's worth to do it now for this case.

**Comment by rezkiy37** [comment] 2024-03-15 15:41
I got you. I think that it should be a condition to use another name (_current user_). For example when 
`actionName` is `CONST.REPORT.ACTIONS.TYPE.SUBMITTED` and ...? I am not sure about the second and third arguments.

**Comment by rezkiy37** [comment] 2024-03-15 16:30
Hey!
I must inform you that I have a vacation next week. I will be back on Monday 25.03. During the vacation, someone from Callstack can take the issue to work. See you soon!

**Comment by marcochavezf** [comment] 2024-03-15 21:23
> I got you. I think that it should be a condition to use another name (_current user_). For example when `actionName` is `CONST.REPORT.ACTIONS.TYPE.SUBMITTED` and ...? I am not sure about the second and third arguments.

Ah do you have an example in code?

**Comment by marcochavezf** [comment] 2024-03-18 18:30
No update, focused on other higher-priority tasks/bugs

**Comment by marcochavezf** [comment] 2024-03-19 18:51
Created a PR to send the adminAccountID, I need to update the tests first to make it ready for review

**Comment by marcochavezf** [comment] 2024-03-20 17:41
No update, working on higher priority tasks today

**Comment by rezkiy37** [comment] 2024-03-25 13:36
> > I got you. I think that it should be a condition to use another name (_current user_). For example when `actionName` is `CONST.REPORT.ACTIONS.TYPE.SUBMITTED` and ...? I am not sure about the second and third arguments.
> 
> Ah do you have an example in code?

https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/pages/home/report/ReportActionItemSingle.tsx#L81

**Comment by marcochavezf** [comment] 2024-03-25 17:04
Ah I see, yeah I think we should do something like in a new function `getActorAccountID`:

```js
switch (action?.actionName) {
    case CONST.REPORT.ACTIONS.TYPE.REPORTPREVIEW:
        return iouReport ? iouReport.managerID : action?.actorAccountID;
        
    case CONST.REPORT.ACTIONS.TYPE.SUBMITTED:
        return action?.adminAccountID || action?.actorAccountID;
        
    default:
        return action?.actorAccountID;
}
```

**Comment by marcochavezf** [comment] 2024-03-25 17:06
Btw, the [PR](https://github.com/Expensify/Web-Expensify/pull/41285) to add the adminAccountID is in review

**Comment by rezkiy37** [comment] 2024-03-25 17:07
Okay I will improve the app to handle this [case](https://github.com/Expensify/App/issues/35263#issuecomment-2018486920).

**Comment by rezkiy37** [comment] 2024-03-27 11:07
@marcochavezf, just tried. I can confirm that `adminAccountID` exists. However, when I (_admin_) submit an expense report, the backend attaches a member ID to `adminAccountID`. I am on the staging server.

<img width="1728" alt="Screenshot 2024-03-27 at 12 03 39" src="https://github.com/Expensify/App/assets/57314631/a2afd8da-fdaf-4bd5-a036-1c70a2377fda">

**Comment by rezkiy37** [comment] 2024-03-27 11:10
I've created a draft PR - https://github.com/Expensify/App/pull/39042. You can test.

**Comment by marcochavezf** [comment] 2024-03-27 20:15
> However, when I (admin) submit an expense report, the backend attaches a member ID to adminAccountID.

The admin creates and submits the expense report, right? If that's the case it's correct

**Comment by rezkiy37** [comment] 2024-03-28 13:40
@marcochavezf Well, let me clarify. Maybe I misunderstood something.

There are 2 users: admin (_left, ends `14`_) and employee (_right ends `16`_).

<img width="1728" alt="Initial ids" src="https://github.com/Expensify/App/assets/57314631/6fca1c95-2d81-4809-b0e7-a127f9070d3a">

In the video below we can see the current behaviour. The employee is creating an expense report then the admin submits it. We can see that the app is optimistically assigning the submit action to the admin. After a while, the backend sends an update and reassigns the submit action to the employee. However, the message must be generated for the admin.

https://github.com/Expensify/App/assets/57314631/691ab9e8-cb1b-4832-a82d-1dc845f47e76

Here we can see that the app renders these 2 actions like a group, because of the same author.  

<img width="875" alt="Renders as a group" src="https://github.com/Expensify/App/assets/57314631/503923eb-33f1-4b25-be7f-6f2436e577d1">

AFAIK, the app should recognize these 2 messages from different 2 users: the 1st one (_request - the employee_), and the 2nd one (_submit - the admin_). The backend should assign the new property `adminAccountID` to the admin ID. So I think that the expected behavior should look like this:

<img width="863" alt="Expected" src="https://github.com/Expensify/App/assets/57314631/788ead25-c11a-48db-8d1c-40e70b0b16e4">

I've mocked some conditions to render the submit action for the admin. I still think that `adminAccountID` must be the admin ID, not the employee one for this case. Please correct me if I am wrong. WDYT? Thank you 🙂

**Comment by marcochavezf** [comment] 2024-04-02 02:33
Oh I see, I found a bug with `adminAccountID` which is not setting the correct accountID. I created a PR to fix it. I let you know when it's deployed, sorry for the misunderstanding 🙇🏽

**Comment by marcochavezf** [comment] 2024-04-02 23:10
PR merged, waiting to be deployed

**Comment by marcochavezf** [comment] 2024-04-04 00:18
PR deployed to staging. I will be OOO until next week

**Comment by rezkiy37** [comment] 2024-04-04 16:39
Just opened the [PR](https://github.com/Expensify/App/pull/39042) for review 🙂

**Comment by marcochavezf** [comment] 2024-04-11 16:22
https://github.com/Expensify/App/pull/39042 merged, we'd still need a backend change to keep the message consistent i.e. `submitted %amount% `

**Comment by marcochavezf** [comment] 2024-04-25 22:08
After an analysis, I found out no backend change was needed. We only need to add a new entry to `ReportActionItem`. I created a quick [PR](https://github.com/Expensify/App/pull/41040) to address that.

**Comment by rezkiy37** [comment] 2024-04-26 13:47
Hey!
I just wanted to let you know about my vacation for next week. I will be back on 06.05.2024. Meanwhile, I asked @waterim to take over this issue. 
See you soon!

**Comment by slafortune** [comment] 2024-05-10 14:44
@rezkiy37 are you able to get back at this now pending the mentioned [PR](https://github.com/Expensify/App/issues/35263#issuecomment-2078253625)?

**Comment by rezkiy37** [comment] 2024-05-10 15:07
> @rezkiy37 are you able to get back at this now pending the mentioned [PR](https://github.com/Expensify/App/issues/35263#issuecomment-2078253625)?

We already merged a [PR](https://github.com/Expensify/App/pull/39042) for the App. (https://github.com/Expensify/App/issues/35263#issuecomment-2050063959)

**Comment by marcochavezf** [comment] 2024-05-14 20:02
Backend PRs to fix remaining issues are in review https://github.com/Expensify/App/pull/41040#issuecomment-2111044068

**Comment by slafortune** [comment] 2024-05-23 20:32
I will be on vacation until June 4th, but I will not get another BZ assigned since no payment will need to be handled via Upworks.

It looks like we are still waiting on a PR. @marcochavezf, if something changes and you need a BZ member, please reply to the label.

@rezkiy37 is an expert contributor and is not due payment here
@parasharrajat will be paid $500 via New Dot for the C+ role

**Comment by slafortune** [comment] 2024-06-21 17:12
Still waiting on @marcochavezf 

> One of the backend PRs has been merged, I will post an update here once the remaining ones have been deployed. Meanwhile I will fix the conflicts

**Comment by slafortune** [comment] 2024-07-18 16:47
@rezkiy37 is an expert contributor and not due payment here.
@parasharrajat Role C+ is due $500 via NewDot

**Closed by slafortune** 2024-07-18 16:47 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-03 19:08
$500 approved for @parasharrajat
