### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Create a lint rule for unused styles and translation keys

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#22212] opened 2023-07-04 18:48 UTC
# Problem
We often add new styles to [styles.js](https://github.com/Expensify/App/blob/5009b8d5d8edd5e9bb6f4f6def88c5acaea8bc3c/src/styles/styles.js) or copy to [en.js](https://github.com/Expensify/App/blob/5009b8d5d8edd5e9bb6f4f6def88c5acaea8bc3c/src/languages/en.js) and [es.js](https://github.com/Expensify/App/blob/5009b8d5d8edd5e9bb6f4f6def88c5acaea8bc3c/src/languages/es.js), but when we remove the last instance using them in App, sometimes we forget to also remove their definition from `en.js`, `es.js` or `styles.js`.

# Why is this important
Keeps the codebase clean

# Solution
Add a lint rule to eslint-config-expensify to catch unused styles and translation keys so we can remove them appropriately.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140cfa1480a9e4861</li>
        <li>Upwork Job ID: 1676651464070823936</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by gedu** [comment] 2023-07-05 09:09
Hey, I am Edu from Callstack - an expert contributor group.

I can work on this one

**Comment by gedu** [comment] 2023-07-06 10:20
Working on handling deep storage per key, and searching

**Comment by gedu** [comment] 2023-07-06 18:15
Working on reading the styles and translation files, and adding tests compatible with JSX

**Comment by gedu** [comment] 2023-07-07 14:58
Need to work on another issue, couldn't work on it today

**Comment by NicMendonca** [comment] 2023-07-10 14:00
@gedu any update here?

**Comment by gedu** [comment] 2023-07-11 06:37
Sorry, had to jump to fix a PR, I will try to work on this today or tomorrow

**Comment by gedu** [comment] 2023-07-11 15:18
Didn't have the time to work on this today, but tomorrow I will

**Comment by gedu** [comment] 2023-07-12 15:28
Today I could create a basic invalid test for checking if a style key is missing, I will be working around this to start adding more cases, like `style={[style.label]}`,  `style={[style.label, style.h1]}`, `style={getRandomStyle()}` etc

```
{
            code: `
          function test() {
            return <View style={styles.label}/>;
          }
          `,
            errors: [{message: `${message} label`}],
            parserOptions: {ecmaFeatures: {jsx: true}},
        },
 ```

**Comment by gedu** [comment] 2023-07-14 08:25
@luacmartins After the basic setup and running initial tests, I've been looking into all the patterns and formats to address the issue of missing styles and translations. I come up with the next graph (just for styles):

<img width="1303" alt="Screenshot 2023-07-14 at 10 16 04" src="https://github.com/Expensify/App/assets/1676818/8933b973-04b1-47f5-878c-bd022584b4b9">

So, I start chatting with the Typescript migration team, TypeScript proves to be an effective solution for handling missing styles and translations, as it provides type-checking capabilities for both. For instance:

```
const label = translate('common.label') // it's ok because this path exists in the translation files
const label = translate('common.label.subLabel') // raises an error because it doesn't exist
```
The same applies to styles, where TypeScript will highlight any missing styles that have been deleted.

I believe it is unnecessary to add a custom ESLint rule for this purpose. The complexity introduced by the rule outweighs the benefits, particularly because TypeScript offers robust support and will soon deprecate the need for such a rule.

Therefore, I recommend leveraging TypeScript's inherent capabilities for type-checking styles and translations, which provide a more efficient and reliable solution in the long run.

**Comment by luacmartins** [comment] 2023-07-14 15:15
>TypeScript proves to be an effective solution for handling missing styles and translations

Maybe I wasn't clear in the OP, but we wanna catch **unused** styles/translation keys, not missing ones. For example, [payerSettled](https://github.com/Expensify/App/blob/a2dc004c6342c3b2e1e9a61bdc40b99da4fb647c/src/languages/en.js#L366) is defined in `en.js` and `es.js`, but it seems unused in the App. In that case we should just remove `payerSettled`. Same goes for [fabAction](https://github.com/Expensify/App/blob/a2dc004c6342c3b2e1e9a61bdc40b99da4fb647c/src/languages/en.js#L331) and so on. This is basically a check for when people remove the last instance of a style/translation key and forget to remove the associated style/translation key

**Comment by gedu** [comment] 2023-07-17 06:58
Ohh got it, probably I got it wrong, thanks for the clarification, will work on it

**Comment by gedu** [comment] 2023-07-17 15:22
I've been looking into but seems that it won't be possible with ESLint, Each rule is intentionally isolated for every other rule, and each run through a rule is isolated from all other runs. So I can’t share information between rules to know how many references have a key or know when a key isn’t being used. Looking into other possibilities

**Comment by gedu** [comment] 2023-07-19 08:12
Chatting internally an option to handle this cases

**Comment by gedu** [comment] 2023-07-24 10:48
So the Idea is to make an `NPM package` (or a script) that tracks and detects unused styles and translation keys within a project. The package can be executed using npm or yarn and provides various options and configurations to customize the analysis process.

### Features
Command-Line Execution: The NPM package will provide a command-line interface to run the analysis tool and detect unused styles and translation keys.

Argument Options: Users can pass arguments to specify which types of keys to track. The available options will include --styles, --translation, and --all. For example:
- styles: Track unused style keys.
- translation: Track unused translation keys.
- all: Track both unused style and translation keys.

### Configuration File
The package will include a configuration file (config.json / babel.config ) where users can define the source files for styles and translations. The configuration file will have the following structure:
```
{ "mainSource": { "style": ["path/to/style/file.js"], "translation": ["path/to/translation/en.js", "path/to/translation/es.js"] }, "ignore": ["node_modules"], "source": "src/", "shoutType": "warning" } 
```

**mainSource**: Specify the main source files for styles and translations.
ignore: Define folders or files to ignore during the analysis process (e.g., node_modules).
source: Set the source folder where the analysis will start looking for files.

**shoutType**: Define the type of output for unused keys (e.g., warning, error).
By creating an NPM package that tracks unused styles and translations,  will be a convenient tool to detect and remove unused keys from the codebase. This also will add flexibility to any improvements or feature we wanna add on top.

Also probably will be good to add a new check on the PR template, something:
-> you run unused-keys command to check any style or translation
The same for C+ reviewers
Maybe also we can add it into the CI

**Comment by luacmartins** [comment] 2023-07-25 17:56
@gedu would you mind bringing this proposal to Slack so we can get input for the wider team?

**Comment by TomaszFrackowiak** [comment] 2023-07-27 11:42
@luacmartins - hey, just to let you know , @gedu is ooo, be back on Monday.

**Comment by NicMendonca** [comment] 2023-07-27 21:26
waiting for Monday?

**Comment by gedu** [comment] 2023-07-31 15:41
Yes, on my way

**Comment by gedu** [comment] 2023-07-31 15:45
[Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1690818229495039) created.

@luacmartins @NicMendonca

**Comment by luacmartins** [comment] 2023-08-02 20:26
@gedu seems like we aligned on creating script in App. Do you need anything else to get started?

**Comment by NicMendonca** [comment] 2023-08-07 12:21
bump @gedu ^^

**Comment by gedu** [comment] 2023-08-10 16:25
I have to wrap up another issue, I will start working on this tomorrow

**Comment by gedu** [comment] 2023-08-11 18:38
Had to jump to the unread marker PR, will start with this one on Monday

**Comment by gedu** [comment] 2023-08-17 19:38
Pivoting the way of getting and building the keys so I can look at them on all the files

**Comment by gedu** [comment] 2023-08-18 21:09
Created 2 functions to get from the styles and from translation files the object names and parsing them into keys.

Example:

```
const webViewStyles = {
    tagStyles: {
        em: {
            fontFamily: fontFamily.EXP_NEUE,
            fontStyle: 'italic',
        },
     }
}
```

`webViewStyles.tagStyles.em:src/styles/styles.js:74`

Next I will have to go through the codebase and look for the keys

**Comment by gedu** [comment] 2023-08-21 11:59
Today I will be working on another ticket, will continue with the going through the codebase tomorrow

**Comment by gedu** [comment] 2023-08-23 10:05
Working on another ticket that has more priority

**Comment by gedu** [comment] 2023-08-24 11:07
Still working on another ticket that has more priority

**Comment by gedu** [comment] 2023-08-25 16:54
Will come back to this issue on Monday

**Comment by NicMendonca** [comment] 2023-08-28 13:41
> Working on another ticket that has more priority

@gedu does this mean you think this issue isn't correctly prioritised? Should it be a `weekly` instead of `daily`?

**Comment by gedu** [comment] 2023-08-28 15:14
Not sure, I was looking into a regression bug that was kind of blocking a deployment.

Today, For the Styles checking, I added code to go through the whole code base and get the keywords for later look at the unused keywords.

**Comment by gedu** [comment] 2023-08-29 14:29
The script already found some unused style keys, this is the format that I'm showing at least for now
```
Unused keys:       80
File: src/styles/styles.js
Context around line 3483:
        width: 16,
    },

    validateCodeMessage: {
        width: variables.modalContentMaxWidth,
        textAlign: 'center',
    },
Unused key: styles.validateCodeMessage
--------------------------------
Unused keys:       80
File: src/styles/styles.js
Context around line 3488:
        textAlign: 'center',
    },

    whisper: {
        backgroundColor: themeColors.cardBG,
    },

Unused key: styles.whisper
--------------------------------
```
- I need to improve a bit more the styles because I need to load all the styles from the folders
- Will continue with translations
- Throw an error so any other process is interrupted

**Comment by luacmartins** [comment] 2023-08-29 14:51
That's looking great @gedu! Thanks for the update and work so far!

**Comment by gedu** [comment] 2023-08-30 17:39
Today I worked on translations and tried to use kind of the same logic as for styles but translations don't have a clear pattern.

Base: 
`translate('keyword')`: used in components
`Localize.translateLocal('keyword')`: 
`ErrorUtils.getMicroSecondOnyxError('keyword')`

After that it gets complicated:
- can have expressions: `translate(isOK ? 'common.ok' : 'common.no')` ⚠️
- can have variables: `translate(error)` ❌
- string interpolation: `translate('some.string.${key}')` ⚠️
- keyword conditionally built ❌ 
```
  let descriptionKey = 'distance.waypointDescription.';

if (index === 0) {
     descriptionKey += 'start';
} else if (index === lastWaypointIndex) {
     descriptionKey += 'finish';
} else {
     descriptionKey += 'stop';
}
```
- saved into variables ⚠️
```
const errorLabels = {...}
error[XXXX] = 'common.ok'
error.something = 'common.no'
error.something3 = errorLabels.title
error.something3 = errorLabels['title']
```
- config objects ⚠️
```
translationPath: 'footer.features',
```

⚠️: is possible but I will assume some keywords, like: `error`, `translationPath`, etc, or given I can't get the full key I can remove all the keys that have that suffixes. example: `distance.waypointDescription.` I would assume all the keys that have that suffix are being used
❌: from variables I can't know which keys are being used, some come from the backend, and in the case of key builders, given I don't have a common pattern will be hard to catch them all.

I think in this case this part should be more informative and not that strict given that not all the keys will be found
What do you think we should do?
@luacmartins

**Comment by luacmartins** [comment] 2023-08-30 17:49
Hmm that's interesting and I agree that this case is tricky. I think the value in this would come from being strict, otherwise I'm afraid people would just ignore it. Maybe we can go ahead with the style changes for now then and leave translations as is.

**Comment by gedu** [comment] 2023-08-31 08:44
Ok, I will improve the style one, and later look into translations, maybe propose some code changes to standardize the usage or maybe it is worth changing to a lib like [i18next](https://react.i18next.com/)

**Comment by gedu** [comment] 2023-09-04 15:11
Now I'm using the keys from style/utilities folder, I found more unused keys, but I need to improve a bit the logic to check through the StyleUtils, given that some of the styles are being used there.
 
As improvement, now I'm also getting the keys which values are functions
ex:
```
    centeredModalStyles: (isSmallScreenWidth, isFullScreenWhenSmall) => ({
        borderWidth: isSmallScreenWidth && !isFullScreenWhenSmall ? 1 : 0,
        marginHorizontal: isSmallScreenWidth ? 0 : 20,
    }),
```
I get as key `centeredModalStyles`

**Comment by luacmartins** [comment] 2023-09-07 08:37
very nice @gedu!

**Comment by luacmartins** [comment] 2023-09-07 08:38
Do you have a draft PR that we could link to this issue?

**Comment by gedu** [comment] 2023-09-07 15:54
@luacmartins hey, I just created the Draft PR

I was going to ask, how should I add it into the GH flow

**Comment by luacmartins** [comment] 2023-09-07 22:50
Thanks for the draft! I just assigned myself as a reviewer. 

What do you mean by add it to the GH flow?

**Comment by gedu** [comment] 2023-09-08 10:00
@luacmartins I mean if I added into a workflow, like reassure or any scripts into the `.github/workflows`

**Comment by gedu** [comment] 2023-09-08 10:04
Also, with the unused styles, should I remove them?

**Comment by luacmartins** [comment] 2023-09-10 06:07
Ah yes, it'd be nice to have them run as a GH workflow. Can we add them as part of the lint.yml workflow?

**Comment by gedu** [comment] 2023-09-11 14:48
@luacmartins Hey, I added to the lint.yml, and seems to be working, because it failed given that found some unused styles.

<img width="1642" alt="unused_style_workflow" src="https://github.com/Expensify/App/assets/1676818/49c58fc3-8b83-4cdd-b59c-94201967fa14">

**Comment by gedu** [comment] 2023-09-11 14:50
I will start deleting those styles

**Comment by gedu** [comment] 2023-09-12 18:35
@luacmartins  I have improved the script by splitting the search for objects and functions. In the previous version of the script, it was collecting objects inside arrow functions, which were not being used.

For example:
```
pickerSmall: (backgroundColor = themeColors.highlightBG) => ({
    done: {
        color: themeColors.text,
    },
    doneDepressed: {
        fontSize: defaultPickerStyles.done.fontSize,
    },
    modalViewMiddle: {
        backgroundColor: themeColors.border,
        borderTopWidth: 0,
    },
    modalViewBottom: {
        backgroundColor: themeColors.highlightBG,
    },
    iconContainer: {
        top: 7,
        ...pointerEventsNone,
    },
    icon: {
        width: variables.iconSizeExtraSmall,
        height: variables.iconSizeExtraSmall,
    },
}),
```
Now, the script only collects the arrow function names and searches for them in the codebase. This change resulted in the removal of 19 unused keys that were previously identified incorrectly."

<img width="1326" alt="Screenshot 2023-09-12 at 20 31 59" src="https://github.com/Expensify/App/assets/1676818/1f229a3b-4280-45cc-acee-69282667444c">

**Comment by luacmartins** [comment] 2023-09-13 00:14
That's awesome! Great work!

**Comment by luacmartins** [comment] 2023-09-15 09:43
@gedu is still working on the PR

**Comment by gedu** [comment] 2023-09-15 16:22
I'm currently resolving the conflicts, and I've added some comments to the PR. However, due to the new style format that incorporates a Theme object, I need to modify the way we retrieve and integrate these styles within the codebase.

**Comment by luacmartins** [comment] 2023-09-18 08:51
PR is still being worked on as per @gedu's update above

**Comment by gedu** [comment] 2023-09-18 14:10
@luacmartins PR updated, also found another unused style because a component was removed, so it is working great

**Comment by luacmartins** [comment] 2023-09-19 00:54
Awesome! Is the PR ready for review?

**Comment by gedu** [comment] 2023-09-19 05:41
@luacmartins Yes it is 🙌

**Comment by gedu** [comment] 2023-09-21 10:17
@luacmartins Comments fixed and conflicts solved

**Comment by luacmartins** [comment] 2023-10-03 13:53
@NicMendonca correct, @fedirjh did not review that PR.

**Comment by NicMendonca** [comment] 2023-10-03 13:56
ok cool, we're all set here then!

**Closed by NicMendonca** 2023-10-03 13:56 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
