### ISSUE TITLE
[$1000] WS is displayed twice when "Request money"

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19146] opened 2023-05-17 22:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a brand new account
2. Create a new workspace
3. Invite a member to the workspace
4. Sign in as the member
5. Select the Workspace chat
6. Tap the + icon and select "Request money" > Enter any amount
7. Tap on Next

## Expected Result:
WS should be shown one time.

## Actual Result:
WS is displayed twice.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** v1.3.15-5
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/
<img width="987" alt="Bug6058922_step_5" src="https://github.com/Expensify/App/assets/43995119/d9282a97-6219-44f2-9326-6029839721e5">

https://github.com/Expensify/App/assets/43995119/88b5af04-606e-40e6-b406-760c14d55539

Photos/Videos:** Any additional supporting documentation 

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01328c3c996c6e889c</li>
        <li>Upwork Job ID: 1664294047802880000</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-05-22 19:21
Apologies, I got assigned these during EC3 and I wasn't able to find time during the conference to triage. I'm now OOO for the rest of the week, so I'm going to re-apply the `bug` label so that someone that's more available can help move this forward. Thanks!

**Comment by johncschuster** [comment] 2023-05-30 17:00
Sorry Melv, I'm actioning this now.

**Comment by johncschuster** [comment] 2023-05-30 17:07
I clarified the repro steps. It turns out that if the new user signs into their account but hasn't selected the Workspace chat room, and then requests money, the `To:` field only lists the Workspace once, but if the user selects the Workspace chat room, and _then_ requests money, that seems to introduce two instances of the Workspace "user" in the `To:` field.


https://github.com/Expensify/App/assets/5579997/a666f2b8-05ab-4873-8ecd-d75434f0671c

**Comment by mkarkachov** [comment] 2023-06-01 18:59
I was not able to reproduce this issue. Maybe it was fixed with another commit.

**Comment by johncschuster** [comment] 2023-06-01 20:18
@mkarkachov did you try what I suggested in my clarifying comment [here](https://github.com/Expensify/App/issues/19146#issuecomment-1568781930)?

**Comment by mkarkachov** [comment] 2023-06-02 13:53
> @mkarkachov did you try what I suggested in my clarifying comment [here](https://github.com/Expensify/App/issues/19146#issuecomment-1568781930)?

I did

**Comment by hayata-suenaga** [comment] 2023-06-05 13:27
still accepting proposals

**Comment by hayata-suenaga** [comment] 2023-06-07 20:32
asking for help again in the [open source channel](https://expensify.slack.com/archives/C01GTK53T8Q/p1686169915101309)

**Comment by therealsujitk** [comment] 2023-06-08 05:27
I tried to reproduce this, but I don't get the workspace group after creating the workspace, I only get **#admin** and **#announcements**, am I missing something?

![image](https://github.com/Expensify/App/assets/60378235/e5eaa313-1892-4a34-97df-d82fc8e4074a)

**Comment by johncschuster** [comment] 2023-06-08 14:14
I just bumped the [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1685633404326959) in #open-source

**Comment by johncschuster** [comment] 2023-06-08 14:16
Oh geez, I had this issue open in a tab, and I didn't refresh it, so I missed your comments @hayata-suenaga and @therealsujitk. Sorry about that!

**Comment by johncschuster** [comment] 2023-06-08 14:26
@therealsujitk hmm, I'm unsure why you're not seeing the Workspace group. Is this a brand new Workspace you've created? Can you take a video of the steps you're taking?

**Comment by johncschuster** [comment] 2023-06-08 14:28
@hayata-suenaga, I'm not sure if there's any reason we would **not** add folks to that beta, but you may know something I don't. Are we good to do that? If so, I can do that now.

**Comment by johncschuster** [comment] 2023-06-08 14:34
Asked about betas in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1686234751419949)

**Comment by hayata-suenaga** [comment] 2023-06-08 15:53
@johncschuster I responded to you on [slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1686239604250599?thread_ts=1686234751.419949&cid=C01SKUP7QR0)

**Comment by johncschuster** [comment] 2023-06-08 16:03
I've added @allroundexperts and @HezekielT to the beta. @therealsujitk, I'll add you as soon as I receive your email address.

**Comment by johncschuster** [comment] 2023-06-08 19:21
Sure thing, @hoangzinh! I've just added your email address as well!

**Comment by hayata-suenaga** [comment] 2023-06-12 01:34
@allroundexperts thank you for that information. I'll mark this internal

**Comment by hayata-suenaga** [comment] 2023-06-12 02:29
I have other high priority issues right now reassining internal engineer

**Comment by hayata-suenaga** [comment] 2023-06-12 12:11
apparently, I cannot reassign this so I'll just re-assign myself

**Comment by mvtglobally** [comment] 2023-06-13 19:02
Issue not reproducible during KI retests. (First week)

**Comment by hayata-suenaga** [comment] 2023-06-13 19:31
I'll wait for the second KI test to see if this bug still persists. changing the priority to weekly

**Comment by hayata-suenaga** [comment] 2023-06-16 20:46
last KI test couldn't repro the issue

waiting for another KI test

**Comment by therealsujitk** [comment] 2023-06-17 05:23
I couldn't reproduce this either, I did however notice that the workspace name wasn't visible in the money request modal.

![image](https://github.com/Expensify/App/assets/60378235/c6c5a1ea-2044-49b1-827c-c2cdba7a6b81)

**Comment by hayata-suenaga** [comment] 2023-06-20 00:04
@therealsujitk thank you for the investigation. @johncschuster I think we can wait for another KI test and if the issue is not reproduced, we can close this? 🙇

**Comment by johncschuster** [comment] 2023-06-24 12:47
Sounds great, @hayata-suenaga!

**Comment by hayata-suenaga** [comment] 2023-07-06 00:16
I don't know if another KI test has been done, but I belive  we can close this now

**Closed by hayata-suenaga** 2023-07-06 00:16 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
