### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD for payment 2023-10-09] [$500] Android - Scan IOU - Error shows up when tapping on Capture button to take a photo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28526] opened 2023-09-29 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app.
2. Go to + > Request money > Scan.
3. Tap on the capture button.
4. Close the error.
5. Tap Give permission and allow camera access.
6. Tap on the capture button.

## Expected Result:
The image is captured

## Actual Result:
An error shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/de3e29a9-2433-45a3-b069-b2d41fb70990

Not repro in Production

https://github.com/Expensify/App/assets/78819774/6ae5d332-12b2-400b-8dce-21f5275b9a4e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f80a0a462cf36708</li>
        <li>Upwork Job ID: 1708859395779575808</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by tgolen** [comment] 2023-09-29 23:35
Thanks! This was probably during one of the many conflicts I had to fix.

**Comment by mountiny** [comment] 2023-10-01 08:12
Gonna jump into this one to get it merged and CPed

**Comment by mountiny** [comment] 2023-10-02 15:00
Asked in QA, not repro https://expensify.slack.com/archives/C9YU7BX5M/p1696258649574039?thread_ts=1696257638.565279&cid=C9YU7BX5M

This was a regression from internal PR, not sure what should be the pricing here

**Comment by mountiny** [comment] 2023-10-11 12:28
This was a simple fix after a conflict with two PRs, the author was internal and not around in time to fix this. @allroundexperts Do you accept $250 flat fee for this fix since it was quite straightforward? We appreciate the urgency.

**Comment by laurenreidexpensify** [comment] 2023-10-13 11:40
@mountiny can you confirm the payment amounts for both assignees so I know what to update in the payment summary? Thanks

**Comment by mountiny** [comment] 2023-10-15 14:17
I think flat $500 for both @allroundexperts and @fedirjh is what we should go with here based on how the issue was marked when proposals were given and accepted.

**Comment by laurenreidexpensify** [comment] 2023-10-16 12:47
Payment Summary: 

- @allroundexperts $500 - please request in newdot 
- @fedirjh $500 - please apply to job in Upwork

**Comment by laurenreidexpensify** [comment] 2023-10-18 10:59
@fedirjh I just sent over the offer now 👍

**Closed** 2023-10-18 11:07 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-23 16:40
$500 payment approved for @allroundexperts based on summary above.
