### ISSUE TITLE
[$250] Receipt audit shows "Receipt ° Verified √" when there's a violations related to SmartScan

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46791] opened 2024-08-05 03:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722635347734459

## Action Performed:
- Scan a real receipt that will SmartScan successfully
- Wait for it to SmartScan
- Once SmartScan finishes, update the date of the receipt
- You should see a violation under the date field "date differs from scanned receipt"
- You should also see "Receipt ° Verified √" above the receipt, this is the bug
- Update the amount of the receipt to something *higher*
- You should see "Amount greater than scanned receipt"
- You should also see "Receipt ° Verified √" above the receipt. Again, this is the bug

## Expected Result:
When "Date differs from scanned receipt" and/or "amount greater than scanned receipt" are visible, the receipt audit component shouldn't show "Receipt ° Verified √"
Instead, it should say "Receipt ° Issue found" or "Receipt ° Issues found"
However, we should *not* show "Date differs from scanned receipt" or "Amount greater than scanned receipts" under the receipt (ie, in the ReceiptAuditMessages component)
We should show the "Date differs from scanned receipt" under the date field, and "Amount greater than scanned receipt" under the amount field
## Actual Result:
You see "Receipt ° Verified √" when one of the two mentioned violations are present

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d27b8943-3af8-40a9-8edc-7992365c7ff5

![image](https://github.com/user-attachments/assets/d9e7c905-22b3-48b0-8e9c-765d5c5ac68e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01925fef567df5c3b7</li>
        <li>Upwork Job ID: 1820487169849591150</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by bernhardoj** [comment] 2024-08-05 07:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt audit shows verified even though there is a receipt violation.

### What is the root cause of that problem?
The "Issue found" will be shown if there is a violation that is included in `receiptViolationNames` array.
https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/components/ReportActionItem/MoneyRequestView.tsx#L377-L384

Both "Date differs from scanned receipt" and "Amount greater than scanned receipt" violations are not in the array, so the "Verified" is shown.
https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/components/ReportActionItem/MoneyRequestView.tsx#L433-L434
https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/components/ReceiptAudit.tsx#L23-L28

### What changes do you think we should make in order to solve the problem?

We can just add both `CONST.VIOLATIONS.MODIFIED_AMOUNT` and `CONST.VIOLATIONS.MODIFIED_DATE` to `receiptViolationNames`, but it will also show the violation below the receipt which we don't want.
<img width="434" alt="image" src="https://github.com/user-attachments/assets/80d0f51d-77df-4e65-b3c8-d0946bc693d6">

The violation below receipt is shown by `ReceiptAuditMessages`.
https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/components/ReportActionItem/MoneyRequestView.tsx#L502

So, I propose to rename `receiptViolationNames` to `receiptImageViolationNames` and add a new array called `receiptFieldViolationNames` which contains the new violation name. Then, we will also have a new array called `receiptImageViolations` which contains the image-only violation (the current one).

```
const receiptImageViolationNames: OnyxTypes.ViolationName[] = [
    CONST.VIOLATIONS.RECEIPT_REQUIRED,
    CONST.VIOLATIONS.RECEIPT_NOT_SMART_SCANNED,
    CONST.VIOLATIONS.CASH_EXPENSE_WITH_NO_RECEIPT,
    CONST.VIOLATIONS.SMARTSCAN_FAILED,
];
const receiptFieldViolationNames: OnyxTypes.ViolationName[] = [
    CONST.VIOLATIONS.MODIFIED_AMOUNT,
    CONST.VIOLATIONS.MODIFIED_DATE,
    // other violation names if needed
]
const [receiptImageViolations, receiptViolations] = useMemo(() => {
    const imageViolations = [];
    const allViolations = [];

    for (const violation of (transactionViolations ?? [])) {
        const isReceiptFieldViolation = receiptFieldViolationNames.includes(violation.name);
        const isReceiptImageViolation = receiptImageViolationNames.includes(violation.name);
        if (isReceiptFieldViolation || isReceiptImageViolation) {
            const violationMessage = ViolationsUtils.getViolationTranslation(violation, translate);
            allViolations.push(violationMessage);
            if (isReceiptImageViolation) {
                imageViolations.push(violationMessage);
            }
        }
    }
    return [imageViolations, allViolations];
}, []);
```

Then, we pass the `receiptImageViolations` to `ReceiptAuditMessage` so it will only show the violation message from `receiptImageViolationNames`.
https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/components/ReportActionItem/MoneyRequestView.tsx#L502

**Comment by cead22** [comment] 2024-08-07 23:28
@thesahindia any thoughts on @bernhardoj 's proposal?

**Comment by cead22** [comment] 2024-08-07 23:30
@thesahindia any thoughts on @bernhardoj 's proposal?

**Comment by cead22** [comment] 2024-08-08 16:23
@bernhardoj do you think you'll have a PR up for this today?

**Comment by bernhardoj** [comment] 2024-08-08 16:26
Yes, I'll work on the PR in a few minutes.

**Comment by cead22** [comment] 2024-08-08 16:28
Awesome, thank you!

**Comment by bernhardoj** [comment] 2024-08-08 16:43
PR is ready

**Comment by JmillsExpensify** [comment] 2024-08-28 17:31
Awaiting payment summary

**Comment by muttmuure** [comment] 2024-09-06 15:18
$250 - @bernhardoj 
$250 - @thesahindia

**Comment by JmillsExpensify** [comment] 2024-09-06 15:22
$250 approved for @bernhardoj

**Comment by cead22** [comment] 2024-09-11 18:53
Anything else we need to do before we close this one?

**Comment by garrettmknight** [comment] 2024-09-11 19:04
$250 approved for @thesahindia

**Comment by garrettmknight** [comment] 2024-09-11 19:04
@thesahindia can you complete the checklist?

**Comment by cead22** [comment] 2024-09-25 15:36
@muttmuure bump

**Comment by muttmuure** [comment] 2024-09-25 15:48
Created regression test request for applause

**Comment by muttmuure** [comment] 2024-09-25 15:50
@thesahindia just needs to submit his request in ND

**Closed by muttmuure** 2024-09-25 15:50 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by garrettmknight** [comment] 2024-10-08 18:27
$250 approved for @thesahindia
