### ISSUE TITLE
[Search v2.3] - Educational tooltip appears repeatedly after relogin

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49204] opened 2024-09-14 17:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48566
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click Filters.
4. Add a few filters.
5. Click Save search.
6. Repeat Step 3 to 5 a few times to create more saved searches.
7. Go to Troubleshoot > Clear cache and restart > Reset and refresh (or log out and log in again).
8. Go to Search.

## Expected Result:
Educational tooltip will not appear again as it has appeared previously.

## Actual Result:
Educational tooltip appears repeatedly for each saved search after relogin.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3f7d9f4c-5722-428e-a480-9ba7306d421d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by IuliiaHerets** [comment] 2024-09-14 17:04
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment] 2024-09-15 22:16
This is [known](https://github.com/Expensify/App/pull/48566#issuecomment-2350245989) and NAB for now. We're addressing it as a follow up.

**Comment by lakchote** [comment] 2024-09-17 12:14
Also to be solved:

The tooltip should not show over a dialog.

![image](https://github.com/user-attachments/assets/cee08409-2435-4350-8f42-6d11a9093eaa)
![image](https://github.com/user-attachments/assets/265a8e17-e063-4c21-84fb-325c1a102b94)

Steps:

1. Clicked on an expense on the search result
2. Clicked on the receipt thumbnail
3. The tooltip is still showing above the dialog

**Comment by luacmartins** [comment] 2024-09-19 23:34
Draft PRs up

**Comment by lakchote** [comment] 2024-09-20 11:23
Even though it was not external and we weren't looking for proposals, @gijoe0295's solution helped partially resolve the issue (we needed a backend PR too).

As such I'd say we can compensate him $50 for his solution. 

cc @puneetlath since you were originally assigned as a BZ member

**Comment by puneetlath** [comment] 2024-09-21 22:49
Ok sounds good. @gijoe0295 offer is here: https://www.upwork.com/nx/wm/offer/104071644. Please ping me on this issue when you've accepted.

**Comment by puneetlath** [comment] 2024-10-06 17:58
Paid. Thanks everyone!

**Comment by puneetlath** [comment] 2024-10-06 19:15
Ah apologies, I thought only @gijoe0295 needed compensation from [this comment](https://github.com/Expensify/App/issues/49204#issuecomment-2363502272). Can you link the PR @paultsimura?

**Comment by puneetlath** [comment] 2024-10-06 19:26
Ok cool, I've sent you an offer here: https://www.upwork.com/nx/wm/offer/104292932

Can you complete the checklist as well?

**Comment by VictoriaExpensify** [comment] 2024-10-09 11:28
Payment Summary:
Contributor+: @paultsimura paid $250 via [Upwork](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/38620763)

**Comment by puneetlath** [comment] 2024-10-09 18:33
Regression test issue is here: https://github.com/Expensify/Expensify/issues/434820

Thanks for handling the payment @VictoriaExpensify. Closing!

**Closed by puneetlath** 2024-10-09 18:33 UTC
Labels: Reviewing, Engineering, Weekly, Bug
