### ISSUE TITLE
[$1000] Only "mark as unread" present in deleted message in main but it's not the case with staging

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20816] opened 2023-06-15 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat and send image
2. Click on reply thread option
3. On a new thread page, delete the attachment and refresh the page
4. After deleted message appears, hover on it and it just shows mark as unread. However on staging, all the options are available.

## Expected Result:
Either mark as unread should not be present for deleted message or emoji option should also be present

## Actual Result:
Only mark as unread present in deleted message in main but it's not the case with staging

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686831763770099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01434e6d5b981d683c</li>
        <li>Upwork Job ID: 1669329085854871552</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-06-19 11:41
@dhairyasenjaliya @priya-zha has this really not been repro in staging/ production. I feel like this is intentional and this is not a bug as the comment deleted is a parent of a thread, hence we do not remove it from the history.

**Comment by priya-zha** [comment] 2023-06-19 11:47
@mountiny This issue today is repro on staging as well. Though, it wasn't present on staging when the issue was posted on Slack. According to #[20074](https://github.com/Expensify/App/issues/20074#issuecomment-1587928746) ,it seems like it's intended, therefore, we can close this issue if it's not a bug. Thanks.

**Comment by mountiny** [comment] 2023-06-19 12:31
Thanks for confirming I will go ahead and close this issue as a feature not a bug

**Closed by mountiny** 2023-06-19 12:31 UTC
Labels: External, Daily, Help Wanted, Bug
