### ISSUE TITLE
[$1000] Web -  Avatar keeps changing when entering a space after an email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22167] opened 2023-07-04 11:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on search at the top
2. Write a new email with no chat history
3. Enter space after the email

## Expected Result:
No change of avatar

## Actual Result:
Change of Avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bdebe563-fc10-405a-bbfb-104070de2c32

https://github.com/Expensify/App/assets/93399543/5049b887-49ff-4b87-a840-1af06d609835

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688346266782499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a76155a3d5bc8add</li>
        <li>Upwork Job ID: 1676214546425831424</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-07-04 11:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Avatar keeps changing when entering a space after an email

### What is the root cause of that problem?

From method `updateOptionsWithSearchTerm`

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/pages/workspace/WorkspaceInvitePage.js#L177-L185

We know that we re-calculate `userToInvite` by calling method `OptionsListUtils.getMemberInviteOptions` if `searchTerm` is changed. 

From 

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/OptionsListUtils.js#L781-L787

, we know that the avatar of `userToInvite` is random chosen for each methhod call.

The root cause of this issue is that, in method [updateOptionsWithSearchTerm](https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/pages/workspace/WorkspaceInvitePage.js#L177-L185), we don't skip re-calculating `userToInvite` if 

```js
searchTerm.trim() === this.state.searchTerm.trim()
```

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should call method `OptionsListUtils.getMemberInviteOptions` to calculate `userToInvite` iff 

```js
searchTerm.trim() !== this.state.searchTerm.trim()
```

To achieve this, we can change 

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/pages/workspace/WorkspaceInvitePage.js#L178-L183

to

```js
if (searchTerm.trim() !== this.state.searchTerm.trim()) {
    // We only calculate userToInvite again if searchTerm.trim() is changed
    const { personalDetails, userToInvite } = OptionsListUtils.getMemberInviteOptions(this.props.personalDetails, this.props.betas, searchTerm, this.getExcludedUsers());
    this.setState({
        searchTerm,
        userToInvite,
        personalDetails,
    });
} else {
    // We update searchTerm to allow input with leading or trailing spaces
    this.setState({ searchTerm });
}
```

Other pages, like new chat and search page, have the similar issue and we can use the same approach to fix them.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by conorpendergrast** [comment] 2023-07-04 13:00
Reproduced, thanks!

**Comment by conorpendergrast** [comment] 2023-07-04 13:00
I'm curious to see the RCA for this one. It... sort of makes sense, I think

**Comment by akinwale** [comment] 2023-07-04 13:46
This is similar to https://github.com/Expensify/App/issues/21543 which was considered as not a bug.

**Comment by Ali-ch88** [comment] 2023-07-04 14:13
**Please re-state the problem that we are trying to solve in this issue**
Web - Avatar keeps changing when entering a space after an email

**What is the root cause of that problem?**
     SetState() action makes the component re-render again, so on each render the avatar changes.

**What changes do you think we should make in order to solve the problem?**
     We can restrict the user from entering unnecessary spaces, as there are no spaces allowed in emails or numbers.
      
      const trimmedSearchValue=searchValue.trim()
        if(trimmedSearchValue===this.state.searchValue){
          return;
        }

**What alternative solutions did you explore? (Optional)**
NA

**Comment by eVoloshchak** [comment] 2023-07-06 15:57
I agree with @akinwale's [comment](https://github.com/Expensify/App/issues/22167#issuecomment-1620281297)
This can be closed, since https://github.com/Expensify/App/issues/21543 was closed for the following reason:

> I just found out that this is the expected behavior. Every time a valid phone/email is entered, it assigns a random default avatar. It doesn’t remember we showed the green one if you clear some of the input and enter the same valid email/phone again. So closing it. 

It doesn't really matter if you enter spaces or just enter/delete the same symbol, avatar is generated based on `optimisticAccountID`, which is random every time

**Comment by conorpendergrast** [comment] 2023-07-10 14:57
Yeah ok, great point. Closing as not a bug, similar to https://github.com/Expensify/App/issues/21543

**Closed by conorpendergrast** 2023-07-10 14:57 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
