### ISSUE TITLE
[HOLD] [$1000] Bank Account –  System doesn’t throw an error while entering special characters in the “Personal Address” and “City” fields

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20935] opened 2023-06-16 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open "Settings".
2. Click "Workspaces".
3. Click "Bank Account".
4. Click " Connect bank account".
5. Complete all steps until you reach step 4 “Additional Information”.
6. Notice the system doesn’t throw error while entering invalid “Personal Address” and “City”.

## Expected Result:
System should throw an error while entering invalid “Personal Address” and “City”.

## Actual Result:
System doesn’t throw an error while entering invalid “Personal Address” and “City”.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a02fd358-9b7c-4bd0-bd81-66d4a55fb33a

https://github.com/Expensify/App/assets/93399543/9a37df7a-d90e-4b61-94ef-067ae9b239f4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686379958121289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbfcb7573a279c63</li>
        <li>Upwork Job ID: 1671207142123761664</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-06-20 16:32
asked a question in the slack thread as this is not clear what they mean by "invalid".

**Comment by anotherjung** [comment] 2023-06-20 21:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In the addressform, it doesn't show error text when there's invalid(special characters) typed for street and city

### What is the root cause of that problem?

The component hierarchy is like the following:

```
AddressForm <- IdentityForm <- ACHContractStep
```

[ACHContractStep](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/ACHContractStep.js) -> [IdentityForm](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/IdentityForm.js) -> [AddressForm](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/AddressForm.js)

The `errors` and `onFieldChange` in [AddressForm](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/AddressForm.js#L105-L106) are props from `IdentityForm`.
The `errors` and `onFieldChange` in [IdentityForm](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/IdentityForm.js#L196-L197) are props from `ACHContractStep`.
[ACHContractStep](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/ACHContractStep.js#L214-L237) never sends those props down to `IdentityForm`.

The same for `values` - it never sends `values` from `ACHContractStep` to `AddressForm`.

### What changes do you think we should make in order to solve the problem?

1. Create a new state in `ACHContractStep` to show the current form value states
2. Hand down the props `values` from the state created above
3. Hand down the props `onFieldChange`, which updates the state created above
4. Hand down the props `errors` based on the [validate](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/ACHContractStep.js#L39)

**Comment by anotherjung** [comment] 2023-06-20 22:05
Contributor details
Your Expensify account email: upwork@jungno.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014234311551960e0f

**Comment by anotherjung** [comment] 2023-06-21 19:43
@zanyrenney Can you take a look if my proposal is valid? Thanks

**Comment by Santhosh-Sellavel** [comment] 2023-06-22 12:23
Will review today

**Comment by zanyrenney** [comment] 2023-06-22 14:09
thanks @Santhosh-Sellavel

**Comment by zanyrenney** [comment] 2023-06-22 14:10
Hey, I am heading OOO shortly, so assigning another bug0 team member to help watch over this issue whilst I am OOO.  thanks!

**Comment by ShogunFire** [comment] 2023-06-24 15:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We can enter special characters in adress and city fields

### What is the root cause of that problem?

In the validate function of ACHContractStep [here](https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/pages/ReimbursementAccount/ACHContractStep.js#L39-L89)

we only verify that city is not empty (required field) and then we verify that the address is a valid address. For now all we do to verify that it's a valid adress is verify that it doesn't match a certain regexp here
https://github.com/Expensify/App/blob/78577587b64ca6b466194b66f341cfdc6bbfe072/src/libs/ValidationUtils.js#L42
But this validation is not enough to forbid special character.


### What changes do you think we should make in order to solve the problem?


Change the way we verify an adress is valid by adding a regex validation that excludes special characters
And for the city we can validate also with a regex that there is no special characters

### What alternative solutions did you explore? (Optional)
 
I believe that this is how it works for addresses and cities all over the app so is that really a problem ? Maybe the  best solution is to do nothing


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Santhosh-Sellavel** [comment] 2023-06-26 16:03
> @dylanexpensify Can you check internally whether we should handle this or not? If So How do we want to handle this?

@zanyrenney or @dylanexpensify bump!

**Comment by dylanexpensify** [comment] 2023-06-29 07:05
Wow, my bad on this miss @Santhosh-Sellavel! Checking now!

**Comment by dylanexpensify** [comment] 2023-07-03 08:47
reviewing today and posting next steps!

**Comment by zanyrenney** [comment] 2023-07-03 13:35
Thanks @dylanexpensify let me know if I can help!

**Comment by dylanexpensify** [comment] 2023-07-06 08:36
@Santhosh-Sellavel why would we not solve this externally? Can't think why we wouldn't! But maybe I'm missing some context! LMK 😄

**Comment by ShogunFire** [comment] 2023-07-06 11:13
@dylanexpensify I believe he is asking because the problem is present on every city and address fields in the app

**Comment by Christinadobrzyn** [comment] 2023-07-06 18:06
Hey @Santhosh-Sellavel do you think this [issue](https://github.com/Expensify/App/issues/22301) can be combined with this fix? Seems to be related?

**Comment by Santhosh-Sellavel** [comment] 2023-07-06 18:10
@Christinadobrzyn please add a hold label for now, I'll let you know!

**Comment by dylanexpensify** [comment] 2023-07-10 09:37
@Santhosh-Sellavel can you give us an update today? 🙏

**Comment by Santhosh-Sellavel** [comment] 2023-07-10 20:53
@dylanexpensify I'M Waiting for you here!

**Comment by dylanexpensify** [comment] 2023-07-11 09:57
closing after discussion [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1689022835735929)!

**Closed by dylanexpensify** 2023-07-11 09:57 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
