### ISSUE TITLE
[$500] Workspace switcher - Both "Expensify" and another workspace are highlighted in WS switcher

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37239] opened 2024-02-26 22:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace if there is no workspace
3. Open workspace switcher

## Expected Result:
Only "Expensify" will be highlighted

## Actual Result:
"Expensify" and another workspace are highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c356f103-6428-42d5-9e49-b5f8092aa268

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b29a531f8eb3037</li>
        <li>Upwork Job ID: 1762249377835036672</li>
        <li>Last Price Increase: 2024-02-26</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-26 22:53
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by roryabraham** [comment] 2024-02-26 23:00
I don't think this should be treated as a deploy blocker, demoting to regular bug.

**Comment by roryabraham** [comment] 2024-02-26 23:01
Still keen to know where this regression is coming from.

**Comment by roryabraham** [comment] 2024-02-27 00:53
I think this appears to be a regression from https://github.com/Expensify/App/pull/31606...

> We should subtract 1 from props.selectedOptions.length to get the actual focused index.

@Krishna2323 wouldn't that just move the "duplicate focus" to the end of the list where it's out-of-sight in your video?

**Comment by akinwale** [comment] 2024-02-27 03:51
@Krishna2323 Subtracting 1 from the `props.selectedOptions.length` when it's `0` will give `-1`, which is effectively the same as the first part of the alternate solution. I think it makes sense to just explicitly set `-1` as the initial focus index and then update the rest of the logic accordingly.

We can move forward with @Krishna2323's [proposal](https://github.com/Expensify/App/issues/37239#issuecomment-1965528472) here.

🎀👀🎀 C+ reviewed.

**Comment by roryabraham** [comment] 2024-02-27 08:56
sounds good. I also left a comment [here](https://github.com/Expensify/App/pull/31606#discussion_r1503490398) with a tangentially related change that I would love to see included in your PR @Krishna2323

**Comment by dragnoir** [comment] 2024-02-27 16:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Two elements from the Wokspaces page are highlighted.

### What is the root cause of that problem?

There's no issue with the 1st item to be highlighted when the page Choose a workspace is opened.
This is how the component BaseOptionsSelector works.
below some examples showing how the fist element is always selected:

![image](https://github.com/Expensify/App/assets/12425932/c9b9ce4b-6e22-4e25-8e1e-02c971fb8672)

below a screenshot how the active selected workspace should not be highlighted

![image](https://github.com/Expensify/App/assets/12425932/06113a46-2935-484f-9e1a-b6c4c57972d2)

The issue here is that the actif workspace is highlighted. The correct way is to not highlight the actif workspace and highlight the 1st available option to pick from.

### What changes do you think we should make in order to solve the problem?

In this case of this issue I recommande that we should remove highlights from the Everything list (Expensify itrem) and just keep the green checkmark as with when we select a workspace from the list

![image](https://github.com/Expensify/App/assets/12425932/cfe87539-8f7d-4295-86a9-845ef9dbe2f7)
(as you can see here, the actif workspace is NOT highlighted).

The proposed solution is by disabling the focused option here
https://github.com/Expensify/App/blob/174a0324028fcfcb1df7e82124a76ec9d805179e/src/pages/WorkspaceSwitcherPage.tsx#L195

```diff
<OptionRow
...
- optionIsFocused={!activeWorkspaceID}
+ optionIsFocused={false}
/>
```
### What alternative solutions did you explore? (Optional)

**Comment by dragnoir** [comment] 2024-02-27 16:25
@akinwale pls review the choosen proposal, the -1 to props.selectedOptions.length will just make a mess and regressions.

The function `BaseOptionsSelector` is used by many other components. Below a regression from the update.

https://github.com/Expensify/App/assets/12425932/ffb63b6a-9dce-460c-a7bf-a5f4e1b03e94

as you can see on the video, the new choosen update will select the last item from the list. 
Pls check my proposal.

**Comment by akinwale** [comment] 2024-02-27 23:04
Based on [this comment](https://github.com/Expensify/App/pull/37341#issuecomment-1967767526), this inadvertently got fixed in that [PR](https://github.com/Expensify/App/pull/37341).

cc @roryabraham

**Comment by akinwale** [comment] 2024-02-28 00:10
@Krishna2323 Those are entirely separate issues.

You may still get compensated here since your proposal was selected but that's entirely up to BZ / internal team to decide.

**Comment by roryabraham** [comment] 2024-02-28 00:36
This component was much more complicated than it needed to be, so I've been working on a holistic refactor [here](https://github.com/Expensify/App/pull/37353/files). I think I've simplified it to a point where it makes more sense and is easier to follow.

So far I've only done cursory testing, so my next step is to go through all the open issues related to the `BaseOptionsSelector` and see if they're reproducible on my branch.

**Comment by Piotrfj** [comment] 2024-02-29 13:00
Update: re-refactoring is ready to be tested, it fixes all the regression issues I was aware of. Please test it (especially the tags, because I could not yet replicate the scenario on my site).
The fix is based on the @roryabraham solution, so special thanks for him!
Link to PR: https://github.com/Expensify/App/pull/37494

**Comment by sakluger** [comment] 2024-03-04 21:50
@roryabraham what would you recommend as the next step here? Should we wait to see if your refactored component solves the issue that @Krishna2323 mentioned? Or will we still need a fix after your refactor?

Also, @Krishna2323 - did you do any work on a PR for your original proposal? If so, do you have a draft PR?

**Comment by dragnoir** [comment] 2024-03-04 22:21
BaseOptionSelector is deprecated https://github.com/Expensify/App/pull/37628

**Comment by roryabraham** [comment] 2024-03-05 00:33
ok, looping back here...

1. This issue is no longer reproducible because the PR that caused it was reverted
1. As @dragnoir mentioned, we won't need a follow-up because the component in question has been deprecated
1. Since @Krishna2323 never actually opened a PR for this issue, I think we can probably just close this issue w/o payments

thanks everyone!

**Closed by roryabraham** 2024-03-05 00:33 UTC
Labels: External, Engineering, Daily, Bug
