### ISSUE TITLE
[$500] Chat - Emoji suggestion list can not be dismissed when tap outside

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31018] opened 2023-11-07 18:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Dot app
2. Navigate to any chat
3. Type :sm
4. Tap outside the opened dropdown to dismiss

## Expected Result:
When user tap outside the dropdown - emoji suggestion page should close

## Actual Result:
Emoji suggestion list can not be dismissed when tap outside

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2e10ee9f-1701-463f-8b6b-17fba1954524

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbf05e8d1e6a1b24</li>
        <li>Upwork Job ID: 1721953857078456320</li>
        <li>Last Price Increase: 2024-01-16</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 27873672</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-11-08 10:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji suggestions list can't be dismissed by tapping outside in native platforms

### What is the root cause of that problem?

In web and desktop platforms, when tapping outside, the composer gets blurred and suggestions list is reset
https://github.com/Expensify/App/blob/24184e4a987aba011b5231680da66dcef11f6a24/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L286-L288

But this isn't the case for native platforms, that is, the composer doesn't get blurred when tapping outside.
This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to implement the outside press listener like https://www.npmjs.com/package/react-native-outside-press to blur the composer when tapping outside. We should blur the composer when tapping outside of the suggestions list and the composer because we shouldn't blur the composer when we click the composer.

It looks like the above [package](https://www.npmjs.com/package/react-native-outside-press) can't set multiple target(suggestions list and the composer) so we need to customize the outside press listener

The skeleton code would look like

In App.js: This provider would be added to [here](https://github.com/Expensify/App/blob/24184e4a987aba011b5231680da66dcef11f6a24/src/App.js#L53-L68)
```
    <OutsidePressTargetProvider>
        <Expensify />
    </OutsidePressTargetProvider>
```

In ReportActionCompose.js:
```
    const {addTarget, removeTarget} = useOutsidePressTargets();
    useEffect(() => {
        addTarget(containerRef);
        return () => removeTarget(containerRef);
    }, []);

    ...

    <OutsidePressHandler onPressOutside={() => composerRef.current && composerRef.current.blur()} />
```

In [index.native.js](https://github.com/Expensify/App/blob/main/src/components/AutoCompleteSuggestions/index.native.js)
```
    const {addTarget, removeTarget} = useOutsidePressTargets();
    useEffect(() => {
        addTarget(autocompleteRef);
        return () => removeTarget(autocompleteRef);
    }, []);
```

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment] 2023-11-21 20:00
@thesahindia can you take a look at the proposals?

**Comment by s77rt** [comment] 2023-11-22 17:52
Taking this as C+

**Comment by s77rt** [comment] 2023-11-22 19:50
@dukenv0307 Thanks for the proposal. I don't think your RCA is correct. `keyboardShouldPersistTaps` is only related to the keyboard. If we happen to have the keyboard closed already then clicking outside will still not dismiss the suggestion list.


https://github.com/Expensify/App/assets/16493223/be2906d6-9a7b-49aa-8c80-9d6ed602014e

**Comment by s-alves10** [comment] 2023-11-22 20:21
@s77rt 

Yes, we can avoid global listener. I just suggested that for its use in other places. 

> Can we maybe as an alternative use the remaining space above the suggestion list to render a pressable (kinda backdrop) that hides the suggestion list?

Here is my opinion.
If we need to consider the suggestions list only, we can fix the issue simply by using the outside press handler. But I think we need to consider the composer as well. When tapping outside the suggestions list but inside the composer, the suggestions list should not be dismissed, I think

Please let me know your thoughts

**Comment by s77rt** [comment] 2023-11-22 21:03
@s-alves10 Let's not use that outside press handler. It seems an overkill to add a new package to solve this. Did you get a chance to explore the suggested alternative? (i.e. render a pressable above the suggestion list)

**Comment by s77rt** [comment] 2023-11-23 12:51
@dukenv0307 I disabled the software keyboard on purpose to show that `keyboardShouldPersistTaps` is not the root cause.    You can experience same bug on Android (on Android the keyboard can actually be closed)


https://github.com/Expensify/App/assets/16493223/3ceed674-dd57-490c-b2db-4aec7b4a88e0

**Comment by s77rt** [comment] 2023-11-23 15:21
@s-alves10 Thanks for the update. Why is the rectangle covering the suggestion list? What would happen if we click on the suggestion list in this case?

**Comment by s-alves10** [comment] 2023-11-23 15:24
@s77rt Tapping on the suggestion list works as is now

**Comment by s77rt** [comment] 2023-11-23 15:25
But will it register as a press on the other pressable?

**Comment by s-alves10** [comment] 2023-11-23 15:29
The suggestion list is placed above the `Pressable` and `onPress` isn't called when tapping on the list

**Comment by s77rt** [comment] 2023-11-23 15:36
Okay I see. Can you please explain how/where the pressable is added?

**Comment by s-alves10** [comment] 2023-11-23 15:38
In [AutoCompleteSuggestions](https://github.com/Expensify/App/blob/main/src/components/AutoCompleteSuggestions/index.native.js) component

```
function AutoCompleteSuggestions({measureParentContainer, onClose, ...props}) {
    const {windowHeight} = useWindowDimensions();
    const styles = useThemeStyles();
    return (
        <Portal hostName="suggestions">
            {props.suggestions?.length > 0 && (
                <PressableWithoutFeedback
                    style={[styles.autoCompleteOutsideContainer, {top: -windowHeight, height: windowHeight}]}
                    onPress={onClose}
                />
            )}
            {/* eslint-disable-next-line react/jsx-props-no-spreading */}
            <BaseAutoCompleteSuggestions {...props} />
        </Portal>
    );
}
```

**Comment by s-alves10** [comment] 2023-11-23 15:54
In styles.ts
```
        autoCompleteOutsideContainer: {
            left: -20,
            right: -20,
            position: 'absolute',
        },
```

**Comment by s77rt** [comment] 2023-11-23 16:49
@s-alves10 This is looking good so far but there is an inconsistency between Android an iOS. On Android we can scroll the messages but on iOS we can't. It would be better if we keep the scroll functionality on iOS too. Also how are we going to call `resetSuggestions`? 


https://github.com/Expensify/App/assets/16493223/0f0b80db-607a-423c-88a4-eddcf031b477

**Comment by s-alves10** [comment] 2023-11-24 14:57
@s77rt 

I'm going to pass props `onClose` to `Suggestions` component in `ComposerWithSuggestions`

> It would be better if we keep the scroll functionality on iOS too
It looks tricky to pass touch events through a view without blocking `onPress`. How about to prevent background scrolling?

**Comment by s77rt** [comment] 2023-11-24 17:42
@dukenv0307

> Meanwhile if you remove keyboardShouldPersistTaps="handled", tapping on a report action will blur the composer.

It won't. In this case tapping outside will dismiss the keyboard. The keyboard dismissal action is what blurs the input and not the outside press.

> if you think this root cause is correct ... Then why if keyboardShouldPersistTaps="handled" is removed, the composer now gets blurred when tapping outside?

As explained above, it's not the root cause because it's not the main action that blurs the input. Tapping outside will not blur the input. Tapping outside will dismiss the keyboard. If the keyboard got dismissed the input will get blurred. It's a chain reaction. If keyboard is closed then the input will stay focused.


https://github.com/Expensify/App/assets/16493223/5d4be113-7848-44ab-acb8-3bf539187a90


> why do we need to render a Pressable when we already have all the report actions which are Pressables

Because components shouldn't be coupled. We should be able to close the suggestion box no matter what is rendered underneath.

**Comment by s77rt** [comment] 2023-11-24 17:43
@s-alves10 

> How about to prevent background scrolling?

Scrolling looks like a feature here. I think it would be better to keep it.

**Comment by s77rt** [comment] 2023-11-28 13:06
Still looking for proposals

**Comment by s77rt** [comment] 2023-11-28 13:06
@puneetlath Please assign me here

**Comment by s77rt** [comment] 2023-12-02 19:49
Still looking for proposals

**Comment by s-alves10** [comment] 2023-12-04 16:30
@s77rt 

We can solve this issue by simply changing [this line](https://github.com/Expensify/App/blob/5dcdd097ecf0148669f347178fb7c6e176e6e909/src/pages/home/report/ReportActionsList.js#L469) to
```
                    keyboardShouldPersistTaps="never"
```

The drawback of this solution is that it won't work if hardware keyboard is connected and so keyboard isn't opened when the composer input is focused. I'd like to know we should consider this case as well

**Comment by s77rt** [comment] 2023-12-08 20:16
Still looking for proposals

**Comment by s77rt** [comment] 2023-12-11 10:36
Same ^

**Comment by s77rt** [comment] 2023-12-13 15:59
Still looking for proposals

**Comment by s77rt** [comment] 2023-12-18 16:33
Still looking for proposals

**Comment by s77rt** [comment] 2023-12-21 16:39
Not overdue. Still looking for proposals

**Comment by s77rt** [comment] 2023-12-25 17:52
@dukenv0307 Thanks for the update. I don't think we should involve `ScreenWrapper` here as this issue is limited to the suggestion list it's better to keep the changes only to the suggestion list related components. I'm pretty much inclined into following this approach https://github.com/Expensify/App/issues/31018#issuecomment-1824719558 and fix the scroll issue on iOS.

**Comment by s77rt** [comment] 2023-12-26 12:03
@dukenv0307 The ScreenWrapper could be the last resort here. Let's try to avoid it for now. Did you find reasons why we are having the scroll issue on iOS?

**Comment by augustmuir** [comment] 2023-12-26 17:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji suggestions should dismiss when tapping outside, while still supporting scrollable chat in the background.

### What is the root cause of that problem?
The scenario is not handled natively. Also for iOS it isn't the default behaviour to scroll while a similar popover component is opened.

For example, compare Slack iOS to Slack Android, the issue is here as well. On Slack Android after typing ":sm" you can click outside to dismiss, but on iOS you aren't able to click outside to dismiss.

### What changes do you think we should make in order to solve the problem?
Wrap `ReportActionsList` with a non-conflicting GestureDetector, and emit a tap event tap event. Listen to the event in the emoji suggestion component (or similar component) then handle the close event there.

-------------

See this commit: https://github.com/Expensify/App/compare/main...augustmuir:ExpensifyApp:main

cc @s77rt 

Videos of fix:

https://github.com/Expensify/App/assets/72067396/5e72d5e1-7ebd-4f8f-9cd4-6d73cab7b39f


https://github.com/Expensify/App/assets/72067396/cb135177-9a98-4233-b32a-bd4f1d478ca0

**Comment by s77rt** [comment] 2023-12-27 15:24
@augustmuir Thanks for the proposal. Using ReportActionsList to detect clicks would work but I would prefer not to couple unrelated components. The suggestion list should be closed no matter the underlaying component.

**Comment by s77rt** [comment] 2024-01-01 11:20
Still looking for proposals

**Comment by s77rt** [comment] 2024-01-03 20:33
Same ^

**Comment by s77rt** [comment] 2024-01-09 00:52
Still looking for proposals

**Comment by puneetlath** [comment] 2024-01-11 21:22
Still waiting to see if we can get a viable proposal.

**Comment by s77rt** [comment] 2024-01-14 23:32
Still looking for proposals

**Comment by fabriziobertoglio1987** [comment] 2024-01-16 02:35
The root issue is not in the Expensify App. The issue is a popular react-native issue/limitation.

**Comment by koko57** [comment] 2024-01-17 16:25
Hi! It's Agata from Callstack, I can take a look 🙂

**Comment by koko57** [comment] 2024-01-18 09:16
@puneetlath @s77rt just to make sure on expected results: we want to dismiss the emoji modal but keep the input focused and keyboard opened is that right?

**Comment by fabriziobertoglio1987** [comment] 2024-01-18 10:26
The react-native issues are https://github.com/facebook/react-native/issues/12360, https://github.com/facebook/react-native/issues/27333 and https://github.com/facebook/react-native/issues/28894#issuecomment-738150834. There are also relevant discussions in the gesture-handler 

- react-native iOS and Android, we can not press on two overlay views (for ex. the two views have position absolute and are on top of each other, we can press only one of them using pointerEvents)
- gesture-handler, works on Android, but not on iOS

### Can not scroll ScrollView on Android when Pressable is overlayed on top of it

Using react-native-gesture-handler ScrollView fixes the issue on Android.
The issue is fixed with Gesture Handler, which delivers the event to the ReactScrollView ([onInterceptTouchEvent](https://github.com/facebook/react-native/blob/95bed60a1e173316c67379f20c6596b686e2172d/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java#L398)) handler with GestureHandlerOrchestrator  [deliverEventToGestureHandlers](https://github.com/software-mansion/react-native-gesture-handler/blob/f9c28c8ffeb01ad2188e15c4d6667e5a5953b14a/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt#L201).

<details><summary>CLICK TO OPEN SOURCECODE EXAMPLE</summary>
<p>

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */
import * as React from 'react';
import {
  View,
  Text,
  TextInput,
  StyleSheet,
  SafeAreaView,
  Pressable,
  // ScrollView does not work
  ScrollView,
} from 'react-native';
import {
  // Gesture Handler ScrollView works
  // ScrollView,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';

const SUGGESTIONS = [
  { text: ':heart' },
  { text: ':love' },
  { text: ':kiss' },
  { text: ':lol' },
  { text: ':-)' },
];

function PopUp(props) {
  const suggestions = props.rows.map((row, index) => {
    return (
      <Text key={index} style={styles.popupText}>
        {row.text}
      </Text>
    );
  });
  return <View style={styles.popup}>{suggestions}</View>;
}

function Footer() {
  const [visible, setVisible] = React.useState(true);
  return (
    <View>
      <TextInput style={styles.input} />
      <Pressable
        style={styles.touchable}
        onPress={(e) => {
          setVisible((prevState) => !prevState);
        }}>
        {visible && <PopUp rows={SUGGESTIONS} />}
      </Pressable>
    </View>
  );
}

const App = () => {
  const content = SCROLLVIEW_DATA.map((row, index) => {
    return (
      <Text key={index} style={styles.scrollViewText}>
        {row.title}
      </Text>
    );
  });
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <SafeAreaView style={styles.container}>
        <ScrollView style={styles.scrollView}>{content}</ScrollView>
        <Footer />
      </SafeAreaView>
    </GestureHandlerRootView>
  );
};

export default App;

const styles = StyleSheet.create({
  scrollView: {
    height: 500,
  },
  touchable: {
    position: 'relative',
    top: -550,
    height: 700,
    left: 0,
    right: 0,
    zIndex: 200,
    // backgroundColor: 'rgba(255, 255, 230, 0.9)',
    // backgroundColor: 'yellow',
  },
  scrollViewText: {
    borderWidth: 1,
    height: 40,
    fontSize: 20,
  },
  popup: {
    backgroundColor: 'gray',
    position: 'absolute',
    bottom: 100,
    left: 40,
    right: 40,
  },
  popupText: {
    fontSize: 20,
  },
  input: {
    backgroundColor: 'black',
    color: 'white',
    height: 50,
  },
});

function createScrollViewData(numberOfRows) {
  let data = [];
  for (let index = 0; index < numberOfRows; index++) {
    const element = numberOfRows[index];
    data.push({ title: `Item number ${index}` });
  }
  return data;
}
const SCROLLVIEW_DATA = createScrollViewData(50);
```

</p>
</details>

| Before    | After |
| ----------- | ----------- |
| <video src="https://user-images.githubusercontent.com/24992535/293496035-eb1d1027-40b5-43b4-b081-485d23cfea45.mov" width="350" />      | <img src="https://user-images.githubusercontent.com/24992535/293496029-dda9b46c-56ff-4a57-beba-36e97436c81b.gif" width="350" />       |

**Comment by s77rt** [comment] 2024-01-18 18:09
Raised this to Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1705601299388139 for confirmation if this is worth fixing

**Comment by koko57** [comment] 2024-01-18 20:38
Personally I don't think it's a bug - if we don't want to blur the composer why would we need to dismiss only the suggestion modal. I was curious how it works in other apps - in Slack the suggestion modal is not dismissed either https://github.com/Expensify/App/assets/28020445/7869d6ec-aaad-4f55-ab42-a4bc9ca8082e

**Comment by quinthar** [comment] 2024-01-22 00:34
I'm not able to reproduce this bug; it seems like this is working for me.

**Comment by s77rt** [comment] 2024-01-22 14:33
@puneetlath Should we just close this?

**Comment by puneetlath** [comment] 2024-01-26 14:51
Yes, let's close. Thanks everyone.

**Closed by puneetlath** 2024-01-26 14:51 UTC
Labels: External, Engineering, Daily, Overdue, Bug

**Comment by fabOnReact** [comment] 2024-07-25 06:06
I verified. The issue was fixed with https://github.com/Expensify/App/pull/45076/files.
