### ISSUE TITLE
Expense - Report action shows "changed tax rate to x(previously x)" when there is no rate change

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#54560] opened 2024-12-25 13:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+kh1012020@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Money Requests

## Action Performed:
Precondition:
- Rules and Taxes are enabled.
- There are two tax rates - A and B.
- Tax rate A belongs to Workspace and Foreign currency default.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click Advertising category.
4 Click Default tax rate.
5. Select Tax rate B.
6. Go to workspace chat.
7. Submit an expense with Tax rate B and without category (important).
8. Go to transaction thread.
9. Click Category and select Advertising.

## Expected Result:
There should be no system message for tax rate change since the before and after tax rate is still the same (tax rate B) after selecting a category.

## Actual Result:
There is system message for tax rate change when there is no changes to the tax rate. 
It shows "changed the tax rate to 5% (previously 5%)".

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/095d74bf-5429-4e62-a0d8-5694f0685f8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by linhvovan29546** [comment] 2024-12-25 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report action shows "changed tax rate to x(previously x)" when there is no rate change
### What is the root cause of that problem?
When update `category`, we use [this function](https://github.com/Expensify/App/blob/12e0941f859c61385baa4b05e7513b0bd04b1d1f/src/libs/ReportUtils.ts#L3724-L3730) to build `optimisticData` for report actions when setting a category

https://github.com/Expensify/App/blob/12e0941f859c61385baa4b05e7513b0bd04b1d1f/src/libs/ReportUtils.ts#L3730-L3736
However, this function does not compare `transactionChanges` with `oldTransaction`, which causes the system message to display incorrect text:

https://github.com/Expensify/App/blob/12e0941f859c61385baa4b05e7513b0bd04b1d1f/src/libs/ReportUtils.ts#L3778-L3779

### What changes do you think we should make in order to solve the problem?

We need to compare the `taxCode` of the new transaction with that of the old transaction.
```js
 const didTaxCodeChange = 'taxCode' in transactionChanges && oldTransaction?.taxCode !== transactionChanges.taxCode;
```
and similar for `taxAmount`
  ```js
  const didTaxAmountChange = 'taxAmount' in transactionChanges && transactionChanges?.taxAmount !== TransactionUtils.getTaxAmount(oldTransaction, isFromExpenseReport)
   ```

<details>
 <summary>POC</summary>

https://github.com/user-attachments/assets/f702b4a4-8b4f-40e3-b6ce-cc06167b963b


</details>

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

We can write automated tests for `updateMoneyRequestCategory`

### What alternative solutions did you explore? (Optional)

**Comment by linhvovan29546** [comment] 2024-12-25 15:20
> @linhvovan29546 can you point the offending PR here ?

@allgandalf  The logic originates from PR [#42128](https://github.com/Expensify/App/pull/42128). In [this PR](https://github.com/Expensify/App/pull/53332/files#diff-9c07b44e092fd3d975806649be46d76b75a377c16e32ed86597b630a84c290d0R3452), we added `taxCode` and `taxAmount` based on the category, which caused the system message to display incorrectly.

**Comment by youssef-lr** [comment] 2024-12-25 17:05
Dupe of https://github.com/Expensify/App/issues/54559

**Closed by youssef-lr** 2024-12-25 17:05 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug

**Comment by linhvovan29546** [comment] 2024-12-25 23:43
> Dupe of #54559

I think this is not a duplicate 🤔. The expected outcome for this issue is that no system message for the `taxRate` is displayed, whereas  https://github.com/Expensify/App/issues/54559 focuses on  consistency between changing, removing, or setting `Category` and tax system messages
