### ISSUE TITLE
Web -OldDot Transition - New workspace is displayed without a name initially

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11910] opened 2022-10-17 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to NewDot and log in with a existing account
2. Navigate to OldDot and log in with the same account from the previous step
3. Navigate to Settings > Policies > Group and note the number of free policies
4. Click on the "New Policy" button/"Free" option
5. Verify you're redirected to NewDot, that you're logged in with the same account
6. Verify that only 1 new Workspace has been created

## Expected Result:
The new workspace should appear with a name immediately

## Actual Result:
The new workspace is displayed without a name initially

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.16.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196232805-b9891f06-e04d-410d-b663-af91fff548b6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment] 2022-10-18 20:33
Policy is getting created and stored with no name:
<img width="1601" alt="Screen Shot 2022-10-18 at 1 33 36 PM" src="https://user-images.githubusercontent.com/4741899/196538210-9acedba4-e09f-4aec-b7f6-1d09dd77ab3a.png">

**Comment by yuwenmemon** [comment] 2022-10-18 20:53
Ah we're even just sending it as the string, "undefined"
<img width="623" alt="Screen Shot 2022-10-18 at 1 53 29 PM" src="https://user-images.githubusercontent.com/4741899/196542692-6c295b7c-e7b6-44b8-acd8-cf6783b0b3e5.png">

**Comment by mvtglobally** [comment] 2022-11-03 03:16
Issue not reproducible during KI retests. (First week)

**Comment by yuwenmemon** [comment] 2022-11-03 12:53
That's because I fixed it and it was deployed to production more than a week ago 😅 

Closing

**Closed by yuwenmemon** 2022-11-03 12:53 UTC
Labels: Reviewing, Engineering, Daily, Bug
