### ISSUE TITLE
[$1000]  Members - User receives message that member was not found after inviting new user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21282] opened 2023-06-21 23:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch Expensify App / iOS
2. Log in with Expensifail account
3. Create or go to any workspace
4. Go to 'Members'
5. Tap 'Invite'
6. Input any existing GMail user
7. Tap Next and Invite

## Expected Result:
Invited user appears in the Members list

## Actual Result:
Admin receives a message that the member was not found.
After re-opening app, the previously invited member is present in the members list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5fb50eba-a3e3-466c-9f2d-0a72a718113e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3ab148ee22e5e58</li>
        <li>Upwork Job ID: 1687473037543706624</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

**Comment by Shivam7-1** [comment] 2023-06-22 06:57
## Proposal

### Admin receives a message that the member was not found.
After re-opening app, the previously invited member is present in the members list.

## Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?
I think the error is in the `WorkspaceInvitePage` component.  In the `WorkspaceInvitePage`component, the `getExcluderuser` have creating problem

### What changes do you think we should make in order to solve the problem?
To fix the error,  I will made changes to the `getExcludedUsers` method to exclude the current user and the users who are already policy members from the invite options list.

**Comment by mananjadhav** [comment] 2023-06-22 07:05
@Shivam7-1 I would recommend close the PR. Please read our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

We first generally wait for the proposals to be vetted by the team, and once you’re assigned on GH, you can create the PR.

**Comment by Shivam7-1** [comment] 2023-06-30 03:49
> ### Bug0 Triage Checklist ([Main S/O](https://stackoverflowteams.com/c/expensify/questions/14418))
> * [ ]  This "bug" occurs on a supported platform (ensure `Platforms` in OP are white_check_mark)
> * [ ]  This

Can anyone Just Review My Proposal please is there anything which I missed let me know i will make changes on it

**Comment by mananjadhav** [comment] 2023-06-30 04:09
@Shivam7-1 I'll be reviewing this today. Thank you for the patience. But I did do a quick review of your proposal. Can you please improve quality of the proposal by:

1. Following the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) ? Please retain all the question headings from the template in your proposal.

2. Can you please be specific on what the error is?
> I think the error is in the WorkspaceInvitePage component.

You've mentioned `getExcluderuser` method name. But could you let us know what exactly is wrong with the method logic?

3. Can you elaborate your solution? While I understand your changes. How does that resolve the bug? 

4. Lastly, while you can add some of the technical details, link code, etc in the proposal,  _Please use plain English, be brief and avoid jargon._

**Comment by Shivam7-1** [comment] 2023-06-30 06:29
## Proposal
After re-opening app, the previously invited member is present in the members list.

### Please re-state the problem that we are trying to solve in this issue.
 trying to solve an issue with the `toggleOption` method in the `WorkspaceInvitePage` component. The issue appears to be related to the asynchronous nature of `setState`. The error message suggests that a member was not found immediately after inviting a new user, but the member appears in the members list after reopening the app. Is that correct?
### What is the root cause of that problem?
The error Occurs in `toggleOption` method in the `WorkspaceInvitePage` component. 
Below is Functional Current Code
`
toggleOption(option) {
    this.clearErrors();

    this.setState((prevState) => {
        const isOptionInList = _.some(prevState.selectedOptions, (selectedOption) => selectedOption.login === option.login);

        let newSelectedOptions;

        if (isOptionInList) {
            newSelectedOptions = _.reject(prevState.selectedOptions, (selectedOption) => selectedOption.login === option.login);
        } else {
            newSelectedOptions = [...prevState.selectedOptions, option];
        }

        const {personalDetails, userToInvite} = OptionsListUtils.getMemberInviteOptions(this.props.personalDetails, this.props.betas, prevState.searchTerm, this.getExcludedUsers());

        return {
            selectedOptions: newSelectedOptions,
            personalDetails,
            userToInvite,
            searchTerm: prevState.searchTerm,
        };
    });
}
Current Logic about program is
The `toggleOption` method is responsible for adding or removing an option from the `selectedOptions` array in the component's state. It uses `setState` to update the state and trigger a re-render.

the issue Looks to be related to the asynchronous nature of `setState`. The error message suggests that the member was not found immediately after inviting a new user, but the member appears in the members list after reopening the app. This looks like the state update might not be fully completed when the error message is displayed.

### What changes do you think we should make in order to solve the problem?


To solve this issue, I think we should use the callback function of `setState` to ensure that the state update is finished before performing any further actions. 

By using the callback function, we can ensure that the state update is finished before proceeding with any subsequent actions. This should help in synchronizing the state correctly and prevent the error where the member appears as not found immediately after inviting a new user.

For call back Function we can include for resolve the error
`           if (!this.state.selectedOptions.length) {
                this.showErrorMessage('No options selected');
            }

            
            console.log(this.state)`


### What alternative solutions did you explore? (Optional)
NA

**Comment by Shivam7-1** [comment] 2023-06-30 06:31
> @Shivam7-1 I'll be reviewing this today. Thank you for the patience. But I did do a quick review of your proposal. Can you please improve quality of the proposal by:
> 
> 1. Following the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) ? Please retain all the question headings from the template in your proposal.
> 2. Can you please be specific on what the error is?
> 
> > I think the error is in the WorkspaceInvitePage component.
> 
> You've mentioned `getExcluderuser` method name. But could you let us know what exactly is wrong with the method logic?
> 
> 3. Can you elaborate your solution? While I understand your changes. How does that resolve the bug?
> 4. Lastly, while you can add some of the technical details, link code, etc in the proposal,  _Please use plain English, be brief and avoid jargon._

Soory  `getExcluderuser` Function is not creating error The error is caused by `toogleoption` Function in above proposal i explained logic how it affecting and how we can tackle this issue

**Comment by michaelhaxhiu** [comment] 2023-08-04 14:41
Note: I'm preparing to go OOO for ~2 weeks and re-applying the Bug label to get a buddy on this one.

- Somehow, this got changed to `Weekly` and I missed it in my daily comb through of GHs the past 2 weeks, I'm sorry! It should be `Daily`.
- @fedirjh can you review the proposal provided as a next step?

**Comment by advantiss425** [comment] 2023-08-05 02:11
can I work on this?

**Comment by advantiss425** [comment] 2023-08-05 02:15
Contributor details
Your Expensify account email: advantis27@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d3cdf5981382d470

**Comment by advantiss425** [comment] 2023-08-05 02:16
and what is next then?

**Comment by advantiss425** [comment] 2023-08-05 02:37
hey, is this issue fixed or not?

**Comment by michaelhaxhiu** [comment] 2023-08-05 11:32
@advantiss425 please review https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md. In order to work on a job, you need to make a proposal and be selected.

**Comment by ShogunFire** [comment] 2023-08-08 17:08
Can you still reproduce ? I can't.

**Comment by alexpensify** [comment] 2023-08-09 19:55
@fedirjh when you get a chance, can you review the proposals and confirm if this issue should remain open? Thanks!

**Comment by alexpensify** [comment] 2023-08-10 16:47
Awesome, thank you for that update. I'm closing now.

**Comment by alexpensify** [comment] 2023-08-10 16:48
I've closed the job in Upwork too

**Closed by alexpensify** 2023-08-10 16:47 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
