### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] System throws an error while requesting money if a long description & marchant value is given

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25685] opened 2023-08-22 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Click on '+' icon
3. Click on 'Request money' link
4. Enter amount & click on 'Next' button
5. Click on description > enter over 300 characters value > click on 'Save' button
6. Click on 'Show more' button
7. Click on Marchant > enter over 300 characters value > click on 'Save' button
8. Click on 'Request' button
## Expected Result:
Money requests should be successful
## Actual Result:
System throws an error
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**1.3.56-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/1156dc76-128e-4da9-a066-48799e497f19

https://github.com/Expensify/App/assets/38435837/cbb10a9b-202c-4c74-a831-3ac50014a322

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-Guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692686163590699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b3cd02197f18a6f</li>
        <li>Upwork Job ID: 1694128412349935616</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26273602</li>
<li>Natnael-Guchima | Reporter | 26273603</li>
<li>pradeepmdk | Contributor | 26273680</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-08-22 14:28
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
System throws an error while requesting money if a long description & marchant value is given 
### What is the root cause of that problem?
`RequestMoney` API this throwing  size Exceeded
![Screenshot 2023-08-22 at 7 57 22 PM](https://github.com/Expensify/App/assets/16595846/17c5d62a-8f1e-4826-b083-b7af36b6d45e)
### What changes do you think we should make in order to solve the problem?

we need to limit the character length  in the the UI

**Comment by joelbettner** [comment] 2023-08-22 23:25
@eVoloshchak the proposal from @pradeepmdk looks good to me.

**Comment by pradeepmdk** [comment] 2023-08-22 23:36
@joelbettner can i create the PR Now Due to DeployBlockerCash

**Comment by joelbettner** [comment] 2023-08-22 23:41
@pradeepmdk yes you can feel free to start creating that PR in the interest of time.

**Comment by pradeepmdk** [comment] 2023-08-22 23:43
Thank you @joelbettner. and i want confirm want is limit should i added in the `maxLength` currently backend will support unitl `255` character. should i added the same number ?

**Comment by joelbettner** [comment] 2023-08-22 23:44
Yes, make it 255.

**Comment by pradeepmdk** [comment] 2023-08-22 23:56
adding screenshot

**Comment by ChaosDigtal** [comment] 2023-08-23 00:04
?

**Comment by pradeepmdk** [comment] 2023-08-23 00:31
@joelbettner i think @situchan should in a reviewer role and me as a Contributor role

**Comment by situchan** [comment] 2023-08-23 16:38
Not a blocker. Just linked the comment where I found the issue while reviewing PR.

**Comment by luacmartins** [comment] 2023-08-23 18:51
Demoting it from NAB - https://expensify.slack.com/archives/C05P73VT267/p1692815976972019

**Comment by situchan** [comment] 2023-08-29 00:48
[PR](https://github.com/Expensify/App/pull/25738#issuecomment-1690921088) was deployed to production on Aug 24

**Comment by isabelastisser** [comment] 2023-09-05 19:32
Offers sent in Upwork!

@situchan, please complete the BZ checklist so we can close this issue. Thanks!

**Comment by isabelastisser** [comment] 2023-09-08 20:42
Bump @situchan

**Comment by situchan** [comment] 2023-09-08 20:52
No regression. Just missed this when implement merchant field.
As this is rare case, I don't think regression test is needed.

**Comment by joelbettner** [comment] 2023-09-11 15:33
Any news here?

**Comment by isabelastisser** [comment] 2023-09-11 16:49
Hey @situchan, can you please complete the rest of the checklist below? Thanks!

[@situchan] The PR that introduced the bug has been identified. Link to the PR:
[@situchan] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 [@situchan] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**Comment by situchan** [comment] 2023-09-11 16:51
- [x] The PR that introduced the bug has been identified. Link to the PR: N/A
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A

**Closed** 2023-09-11 16:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by isabelastisser** [comment] 2023-09-11 16:57
All payments were made in Upwork.

Payment summary:

- @situchan C+ review $1000, urgency bonus $500
- @pradeepmdk accepted proposal $1000, urgency bonus $500.
- @Natnael-Guchima $250 reported the issue.
