### ISSUE TITLE
[$250] Expense - Page blinks when opening Hold RHP from report details page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44203] opened 2024-06-22 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp around https://expensify.testrail.io/index.php?/tests/view/4661954
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any DM.
3. Submit two expenses.
4. Go to transaction thread of any expense.
5. Click on the chat header.
6. Click Hold.

## Expected Result:
Page will not blink when opening Hold RHP from report details page.

## Actual Result:
Page blinks when opening Hold RHP from report details page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/b6a303ba-fd33-4085-8f9c-2b935cdea61e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01849f37018df4c9e8</li>
        <li>Upwork Job ID: 1805127337823292445</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by m-natarajan** [comment] 2024-06-22 13:43
@nkuoch FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-22 13:43
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-23 10:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The page behind the RHP looks like blinking when pressing the hold button in details page.

### What is the root cause of that problem?
When we choose the hold button, we do 2 things. First, dismiss the modal, and second, navigate to the hold reason page.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/components/PromotedActionsBar.tsx#L68-L71

https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/ReportUtils.ts#L2808-L2809

If we see the video slowly, we can notice that it's not blinking but the multiple navigations are happening at the same time causing the RHP overlay to become darker and then lighter.

https://github.com/Expensify/App/assets/50919443/cc96fcd5-cef4-4f36-bea7-5f684b971198


### What changes do you think we should make in order to solve the problem?

I don't know if it's expected to dismiss the modal when choosing the hold button, but if it's not, then we can remove it.

https://github.com/Expensify/App/assets/50919443/295f38c2-a39d-4302-92eb-a1890f9aeb6c

**Comment by bernhardoj** [comment] 2024-06-24 10:35
@ishpaul777 I checked that it's because of the focus trap initial focus on the hold explanation page. That kind of sliding issue is similar to https://github.com/Expensify/App/issues/43806 where we focus immediately while an animation is ongoing. This issue doesn't happen when you submit the hold with a mouse. One way to solve this is to delay the focus-trap  by `CONST.ANIMATED_TRANSITION` (300ms), adding the below code to `focusTrapOptions`.
`checkCanFocusTrap: () => new Promise((resolve) => setTimeout(resolve, 300)),`

https://github.com/Expensify/App/blob/d7db203cc8516492387a2a27b089f10bad7ab5ad/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L43-L47

**Comment by oleksolv** [comment] 2024-06-24 11:52
@ishpaul777 

Hi from UpWork!

Here is my fix Proposal and Solution:

### Issue: 

The issue happens because the 2 Navigation Modal Items overlaps each other. So, the backdrop opacity of the 1st one overlaps the 2nd one during the opacity animation effect here: 

https://github.com/Expensify/App/blob/d7db203cc8516492387a2a27b089f10bad7ab5ad/src/styles/index.ts#L1906

At some point the opacity sum of backdrops of the 1st modal and 2nd modal can give more than 0.72 as was prescribed during some time and make the glitch effect of increasing backdrop opacity to 1 and back.

so we have the glitch effect.

### Solution:

Using the index property of useCardAnimation in BaseOverlay

https://github.com/Expensify/App/blob/d7db203cc8516492387a2a27b089f10bad7ab5ad/src/libs/Navigation/AppNavigator/Navigators/Overlay/BaseOverlay.tsx#L22

 and pass it to style can help us to unidentify if we open next modal and turn off backdrop opacity animation, so we will have smooth effect without glitches and opacity animations
 
 ### Demo
 
 

https://github.com/Expensify/App/assets/44111298/04a97f55-d29e-4d15-81a6-48d7ba9dd16c

**Comment by oleksolv** [comment] 2024-06-24 13:34
@ishpaul777 

Sorry, I am first time contributing to Expense, do I need anything to add to my previous post, so you can test that my solution works for modals stack? :)

**Comment by bernhardoj** [comment] 2024-06-24 14:02
@ishpaul777 after my change, pressing the Hold button won't close the details page.

[details, hold reason]

Submitting the hold reason will pop the hold reason page which animates the page to slide from right to left and the details page from left to right, and at the same time the hold explanation page is showing with animation interrupted.

**Comment by oleksolv** [comment] 2024-06-24 14:29
@ishpaul777 If you do not mind I will provide some more details why it is the root issue and it will fix:

1. The project uses React Navigation and all navigation modals are separate views. This rules is applicable also for react-native-app.
2. When we call the navigate to modal we will open the new modal screen. In case of this issue we call:
```
     Navigation.dismissModal(); 
     ReportUtils.changeMoneyRequestHoldStatus(reportAction); 
```
First call will trigger close modal. It spends up to 600ms to close the existed modal and trigger open new modal up to 600ms to open the new one. 

In this case each modal will have its backdrop: you can debug this in browser and see that the animation is in progress for both of the modals. One modal is interpolating from 0.72 - 0 and other from 0 - 0.72.

Here the code you can test, the PR is not ready for review but you can see the changes and the issue fixed for all modals that are calling one by one:
https://github.com/oleksolv/App/pull/1

**Comment by bernhardoj** [comment] 2024-06-24 14:33
Yes, correct.
https://github.com/Expensify/App/blob/2526e31ba9c199ca606f65abb2295e39638d09ee/src/pages/iou/HoldReasonPage.tsx#L56-L69

**Comment by rlinoz** [comment] 2024-06-24 15:34
I think we should try to fix the underlying issue which is there is no `backTo` in the HoldReasonPage when coming from the Search page.

**Comment by bernhardoj** [comment] 2024-06-25 05:59
I think we can do that, but I see this [PR](https://github.com/Expensify/App/pull/44359) is working on a fix for this issue too.

**Comment by stephanieelliott** [comment] 2024-06-27 01:54
That PR was merged to prod yesterday! I'm not able to repro this one -- @ishpaul777 can you try testing and see if it's still happening for you?

**Comment by stephanieelliott** [comment] 2024-06-29 03:46
Yay! Thanks @ishpaul777

**Closed by stephanieelliott** 2024-06-29 03:46 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
