### ISSUE TITLE
IOU - Infinite loading spinner appears when split bill with invalid phone number

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8308] opened 2022-03-24 21:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue reproduced when executing #8019**
## Action Performed:
1. Click on FAB ➕ Button -> Split Bill
2. Enter Amount and press Next
3. Search and select a three-digit phone number
4. Click Next and press the Split Bill button

## Expected Result:
You should see the following error message for the phone number
Please enter a valid phone number, with the country code (e.g. +1234567890)

## Actual Result:
Pressing "Split button" infinite loading spinner appears, after cancelling could not initiate another IOU

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App - Not ready yet still it is 1.1.45-3
- Mobile Web

**Version Number:** 1.1.46

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**Email or phone of affected tester (no customers):** mnata.utest+chaty@gmail.com / Utest123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/160016871-9b325bf2-ab07-4277-a91b-cc5ea59d84b8.mp4

**Issue reproduced when executing #8019**

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-03-24 23:14
👀 Lettuce see what needs to be done her

**Comment by roryabraham** [comment] 2022-03-24 23:55
Not able to reproduce this on staging either 😕

**Comment by rushatgabhane** [comment] 2022-03-25 02:26
Issue is reproducible. cc: @Santhosh-Sellavel 

https://user-images.githubusercontent.com/29673073/160042426-099e3d47-fa8e-4312-94a2-cf825611f721.mov

**Comment by rushatgabhane** [comment] 2022-03-25 03:12
@roryabraham This deploy blocker isn't caused by #8019

It's caused by https://github.com/Expensify/App/pull/8087, because reverting it fixes this issue.

**Comment by rushatgabhane** [comment] 2022-03-25 04:28
I'm gonna take the liberty of creating a PR since it's an hourly ticket.

**Comment by roryabraham** [comment] 2022-03-25 16:51
I wonder why I wasn't able to reproduce it in either environment... 😕 

Thanks for the PR @rushatgabhane 🦸

**Comment by roryabraham** [comment] 2022-03-25 16:52
@Expensify/applauseleads please retest this in `1.1.46-1`, and close it if no longer reproducible 🙏

**Closed** 2022-03-28 22:03 UTC
Labels: DeployBlockerCash, Engineering, Hourly
