### ISSUE TITLE
iOS - Assign task - Group member not shown when trying to assign task in group

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27790] opened 2023-09-19 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre: Create group 2 member

1. Launch App
2. Go to group chat and tap on plus > Assign task
3. Enter a Title and a Description
4. Assign a user from the group that you have access to

## Expected Result:
Group member should be show when trying to assign task in group

## Actual Result:
Group members are not shown when trying to assign tasks in the group.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.71-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/288a39ef-98e3-41d4-8d4a-648e0238cbfe

![Bug6206259_Group_assign_mp4](https://github.com/Expensify/App/assets/115492554/c3ce5737-9c3f-4ee9-861f-916b6c6f47c8)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-09-20 11:03
Hm, I can't reproduce this one: 

<img width="374" alt="image" src="https://github.com/Expensify/App/assets/16232057/ca336461-40aa-437c-a639-e394bc738460">

@izarutskaya can you try again please?

**Comment by trjExpensify** [comment] 2023-09-21 11:48
Bump, @izarutskaya! :)

**Comment by izarutskaya** [comment] 2023-09-24 09:04
Sorry, @trjExpensify, but I can still reproduce it.
iPhone 14 Pro Max/iOS - 16.6.1/Build -v1.3.73-0

This is the new account where the group was created. 
Maybe I can repro this, becouse I don’t have individual chats with every member of this group.

https://github.com/Expensify/App/assets/115492554/28786a3a-a542-438a-ae79-08a6df3853bd

**Comment by trjExpensify** [comment] 2023-09-25 06:59
Oh right, yeah. That's important. I think they don't show up in your contacts list because they aren't "known" to you yet because of the secure logins project. Not really sure if we can do anything about this, tbh.. @puneetlath?

**Comment by puneetlath** [comment] 2023-09-27 07:53
Yeah this isn't actually a bug. Our behavior for the search page is to only show users you "know". So in this case, that's why they don't appear. We could change it to include people in the current chat, even if you don't know them, but I feel like it isn't a problem right now, so not worth updating the behavior.

**Comment by trjExpensify** [comment] 2023-09-27 08:16
Cool, that makes sense. For now then, I'm going to close this out. 

>We could change it to include people in the current chat, even if you don't know them, but I feel like it isn't a problem right now, so not worth updating the behavior.

I think this is probably worth doing at some point. It's a tad strange within a group, but there are likely other instances similar where the behaviour could be altered and we'd benefit from a more holistic plan for that in one sweep.

**Closed by trjExpensify** 2023-09-27 08:16 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
