### ISSUE TITLE
[HOLD for regression test] Web - The whole message with the (edited) text disappears when the updated message contains quotes (" ") @adeel0202

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11377] opened 2022-09-28 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Type any message containing quotes e.g. "test"
4. Send the message
5. Click on the edit icon
6. Edit the message e.g. "test updated"
7. Click on save changes to update the message
8. Click on the edit icon again
9. Click on save changes without making any change

## Expected Result:
The whole message with the (edited) text does not disappear

## Actual Result:
The whole message with the (edited) text disappears

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.8.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192831193-942a1726-b2bd-48a3-ba99-bd9d755f0ca2.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @adeel0202

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663071879002369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-09-28 16:37
@adeel0202 Updated the bug title

**Comment by Christinadobrzyn** [comment] 2022-09-29 03:40
Ah interesting, I don't see any other issues related to this so going to send it to eng

**Comment by PauloGasparSv** [comment] 2022-10-03 22:23
Hey @Luke9389! Yes I did : D

I debugged it a bit and:
1) The message is sent correctly from NewDot to Web-Expensify
2) Web-Expensify knows we are editing the message
3) Web-Expensify is sending the message content to Auth
4) Auth is returning the `html` field as an empty string to Web-Expensify
5) Web-Expensify returns that string through Onyx

And that's as far as I went. I think the problem may be on the [Auth command that updates the comment](https://github.com/Expensify/Auth/blob/main/auth/command/UpdateReportComment.cpp#L55) or in the way [we sanitize the message in Web-Expensify](https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportAPI.php#L465) before sending it to Auth.

But It needs more investigation 😔

**Comment by Luke9389** [comment] 2022-10-06 23:14
I'll check this out tomorrow

**Comment by Luke9389** [comment] 2022-10-07 19:09
When testing this locally, I got this error:
```
?api? [info] transactionList is empty, skipping post processing
?api? [info] Finish initing report ~~ 160
?api? [info] Not updating fields, cache hasn't changed ~~ reportID: '160'
?api? [dbug] _send( expensidev2004.web.report.postProcessPartial:0|ms )
?api? [info] Found a deleted comment without any edit history ~~ sequenceNumber: '20'
?api? [info] Expensify\Onyx - Sending command response via Pusher ~~ 0: '[onyxMethod: 'merge' key: 'reportActions_160']' 1: '[onyxMethod: 'merge' key: 'report_160']'
?api? [info] Push_API - Sending to alternate endpoint to process Pusher notification asynchronously ~~ 0: '{"channels":[{"name":"user","accessModifier":"private-encrypted","params":{"accountID":"2"}},{"name":"user","accessModifier":"private-encrypted","params":{"accountID":"87"}}],"eventType":"onyxApiUpdate","canChunk":true,"eventLogID":"yCW79"}'

?api? [info] [trace] StackTrace start
?api? [info] [trace] 0/5. file '/vagrant/Web-Expensify/lib/Push/API.php' function 'traceFunctionCall' line '254'
?api? [info] [trace] 1/5. file '/vagrant/Web-Expensify/lib/Push/API.php' function 'send' line '174'
?api? [info] [trace] 2/5. file '/vagrant/Web-Expensify/lib/Onyx.php' function 'sendToUserChannelsByAccountIDs' line '120'
?api? [info] [trace] 3/5. file '/vagrant/Web-Expensify/lib/ReportAPI.php' function 'pushUpdatesToClients' line '560'
?api? [info] [trace] 4/5. file '/vagrant/Web-Expensify/lib/ReportAPI.php' function 'editComment' line '567'
?api? [info] [trace] 5/5. file '/vagrant/Web-Expensify/api.php' function 'updateCommentNewDot' line '745'
?api? [info] [trace] StackTrace end
```

I then decided to check out [our logs](expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A"'updateCommentNewDot'"%20AND%20timestamp%3A%5B2022-09-30T00%3A00%20TO%202022-10-08T23%3A59%5D) and it looks like Report::updateCommentNewDot is hitting this a lot.

**Comment by Luke9389** [comment] 2022-10-17 21:57
I'll be doing further investigation on this one this week.

**Comment by Luke9389** [comment] 2022-10-27 21:45
Still need to roll around to this

**Comment by Luke9389** [comment] 2022-11-07 22:46
Still need to roll around to this

**Comment by Luke9389** [comment] 2022-11-08 00:07
OK I think we should actually approach this from the front end. The problem is only reproducable if we edit the message and then hit submit without making changes. If the front end detects this, it should just not send an API request at all (in other words, the submit button shouldn't even be clickable if the edited message is the same as the original).

**Comment by Luke9389** [comment] 2022-11-17 01:27
Poppin around to this tomorrow after re-brand stuff gets done.

**Comment by Luke9389** [comment] 2022-11-29 21:43
tackling this one this week.

**Comment by JmillsExpensify** [comment] 2022-12-08 23:01
@Luke9389 just came across this issue as I was auditing all the older bugs in the repo. Will you be able to pick this up this week? If not, I think we should open this up to volunteers. We seem to have lots of engineers willing to jump in and help out, and if you're already working on other issues, let's get some helping hands to jump into this one. Cool?

**Comment by JmillsExpensify** [comment] 2022-12-08 23:09
Actually, I just noticed that Luke is OOO, so I'm going to go ahead and unassign this one and highlight in Slack.

**Comment by JmillsExpensify** [comment] 2022-12-08 23:11
@sakluger This issue lacked a BZ member so I just removed/re-applied the `Bug` label.

**Comment by JmillsExpensify** [comment] 2022-12-08 23:12
Also asked for volunteers [in Slack](https://expensify.slack.com/archives/CC7NECV4L/p1670541032157569?thread_ts=1670372833.921059&cid=CC7NECV4L).

**Comment by stitesExpensify** [comment] 2022-12-12 15:54
Started looking into this Friday night, diving in fully today

**Comment by stitesExpensify** [comment] 2022-12-12 22:44
Fix is up

**Comment by Luke9389** [comment] 2022-12-13 02:22
Thanks for moving the ball on my behalf @JmillsExpensify!

**Comment by JmillsExpensify** [comment] 2022-12-22 23:14
@sakluger Are you going to be around next week? If not, happy to jump in and help close this out.

**Comment by mollfpr** [comment] 2022-12-27 15:12
@sakluger Could you assign me to the issue and create the Upwork job for the PR review? Thank you!

**Comment by JmillsExpensify** [comment] 2022-12-27 16:24
Well that didn't work as planned. Upwork job is here: https://www.upwork.com/jobs/~01b913417c96073cc8. Payments will be as follows:

 - Contributor+: @mollfpr $1,000
 - Issue reporter: @adeel0202 $250

Can you both please apply and we can get this paid out today?

**Comment by JmillsExpensify** [comment] 2022-12-27 19:24
Thanks, all paid out. @mollfpr This is ready for you when you're back online.

**Comment by mollfpr** [comment] 2022-12-27 22:58
@JmillsExpensify It should be $500, the PR causing [regression](https://github.com/Expensify/App/issues/13661#issue-comment-box).

**Comment by JmillsExpensify** [comment] 2022-12-27 23:36
Thanks for your honesty! I'm away from my computer but I'll circle back this evening.

**Comment by sakluger** [comment] 2022-12-28 02:54
@mollfpr did you receive an offer already through Upwork?

**Comment by mollfpr** [comment] 2022-12-28 03:13
@sakluger I haven't.

**Comment by sakluger** [comment] 2022-12-28 08:10
Thanks - I've sent the offer now through Upwork, once you accept we'll finish paying out.

**Comment by mollfpr** [comment] 2022-12-28 08:51
@sakluger Accepted, thank you!

**Comment by JmillsExpensify** [comment] 2022-12-28 20:46
All paid out. @sakluger Given that we have a regression in play, we should definitely add something to TestRail. Updating the title and leaving that to you.

**Comment by sakluger** [comment] 2023-01-04 23:53
I posted in #bug-zero in Slack with a regression test proposal ([Slack link](https://expensify.slack.com/archives/C01SKUP7QR0/p1672876362903699)).

**Closed** 2023-01-05 20:54 UTC
Labels: Reviewing, Engineering, Daily, Awaiting Payment, Bug
