### ISSUE TITLE
 Close Account - "Account closed successfully" not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44274] opened 2024-06-24 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife+stest@gmail.com
**Issue reported by:**Applause - Internal Team

## Action Performed:
1. Login to an account
2. Go to account settings > Security
3. Close Account

## Expected Result:
"Account closed successfully" is displayed

## Actual Result:
"Account closed successfully" not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/775d1080-4633-40fe-92ed-dcf9348207c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by etCoderDysto** [comment] 2024-06-24 16:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The root cause is all onyx data including `closeAccount` is cleared by pusher response when closing account here
https://github.com/Expensify/App/blob/34a80221441907a3f1f3d98abaeea91e2566e206/src/libs/actions/User.ts#L78-L80

Then we try to display the success message by fetching onyx data after request success here
https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.tsx#L277-L284

And there is no success message on Signin page since `closeAccount` is an empty object 
### What changes do you think we should make in order to solve the problem?
Update the data base to clear all onyx data but `closeAccount` data or remove the close account success message code block since it has no use. 
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-06-25 08:21
Same root cause as https://github.com/Expensify/App/issues/44114

**Closed** 2024-06-28 09:18 UTC
Labels: Daily, Overdue, Bug
