### ISSUE TITLE
Chat -  Can't delete a message using the right click menu with Delete CTA unresponsive

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29918] opened 2023-10-18 21:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29844

## Action Performed:
1. Launch new expensify
2. Go to any chat
3. Send a message
4. Right click on the message
5. Click on delete comment
6. Click on delete CTA

## Expected Result:
The message is deleted

## Actual Result:
Nothing happens when clicking delete on the pop up. The same CTA works if the delete icon was used on the hover menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/53a0cec9-0a27-4708-977a-7770fcf37998

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/c5d2fd22-0d0f-47f6-926c-6b4364a3e858

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2023-10-18 21:59
I can reproduce the issue on staging. I think we had another blocker related to deleting messages, going to check if it's coming from that.

**Comment by francoisl** [comment] 2023-10-18 22:18
So far what I can tell is that `reportIDRef.current` on [this line](https://github.com/Expensify/App/blob/870931972c1c25a7c84d802486c38fa44abfab59/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L238) is 0. It's working fine on `main` though, so there might have been another PR merged recently that fixes this 👀

**Comment by francoisl** [comment] 2023-10-18 23:18
I'm tempted to roll out the deploy with this bug considering that:
- we can't revert https://github.com/Expensify/App/pull/29844, or it will reintroduce the crash from https://github.com/Expensify/App/issues/29839
- I can't reproduce the issue on `main`, so it should be fixed on the next staging version
- it only happens on desktop and web, and you can still delete a message by clicking the 🗑️ icon instead, so there's a straightforward workaround

https://github.com/Expensify/App/assets/2229301/c7c469c7-800d-44ce-9fe3-de7850f44202

**Comment by francoisl** [comment] 2023-10-21 01:38
This is fixed on staging and production now.

**Closed by francoisl** 2023-10-21 01:38 UTC
Labels: Engineering, Hourly, Bug
