### ISSUE TITLE
Android- Subscription -Unable to Change Payment Card and Currency

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47557] opened 2024-08-16 10:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**Found when validating PR :** https://github.com/Expensify/App/pull/46635
**Email or phone of affected tester (no customers):** applausetester+tw23478102034@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to Account Settings > Workspace (create a workspace if not already present).
2. Go to Subscription > Add Subscription > Add Payment Card.
3. Observe that the three-dot menu to change the payment card and currency is missing.

## Expected Result:
Users should be able to change the payment card and currency on Android.

## Actual Result:
The three-dot menu is not visible, preventing users from changing the payment card and currency.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0c23bb4d-c596-416c-bce3-9118a36a76b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-08-16 10:00
We think this issue might be related to the #collect project.

**Comment by iwiznia** [comment] 2024-08-16 15:27
Reassigning to you guys, as I am very lost on this issue and it comes from the linked PR you are assigned to.

**Comment by iwiznia** [comment] 2024-08-16 15:29
Removed the DB label due to https://expensify.slack.com/archives/C9YU7BX5M/p1723822027312069?thread_ts=1723811904.104299&cid=C9YU7BX5M but check that comment out.
Also not sure but I think this would mean we should reduce pay on OG issue.

**Comment by izarutskaya** [comment] 2024-08-16 15:50
Hi @iwiznia I added card in Web than log in with the same account in Android. 
I am sorry for  confusing. This issue reproducible in production. Thank you

**Comment by blimpich** [comment] 2024-08-16 16:20
I'm 95% sure this is the intended behavior. I'll see if I can find the associated thread on this but @trjExpensify can you confirm or deny that we don't want people to be able to add/change billing cards on android?

**Comment by blimpich** [comment] 2024-08-16 16:55
Yes according to [the design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#heading=h.okq40kfetdlp) this is the intended behavior.

**Closed by blimpich** 2024-08-16 16:55 UTC
Labels: Engineering, Hourly, Bug

**Comment by trjExpensify** [comment] 2024-08-17 10:21
Correct, due to the rules of the Apple/Google overlords you can't manage your subscription (add a card, change a card, set or amend your subscription size etc) on native. 👌
