### ISSUE TITLE
[Workspace Feeds] Transactions from the cards are not imported

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52000] opened 2024-11-04 22:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** needs reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [quality](https://applause-ts.slack.com/archives/C05LX9D6E07/p1730755524099499)

## Action Performed:
1. Set up a new feed
2. Assign the card to a employee
3. The card shows a transaction in OD 
4. Check the ND card 
## Expected Result:
Transaction should be imported
## Actual Result:
Transaction are not imported from the cards
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![image (107)](https://github.com/user-attachments/assets/0d4bcbd4-1610-4d8d-b604-9019df70f126)
![image (106)](https://github.com/user-attachments/assets/016b9b19-28f0-4845-8553-123be787daa3)
![image (105)](https://github.com/user-attachments/assets/87990a95-bea8-483c-8c17-21e137f74398)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-11-04 22:47
BZ team member, Callstack will work on this issue, please wait for them to comment before moving the issue forward.

**Comment by joekaufmanexpensify** [comment] 2024-11-05 16:51
Going to bump this one to daily actually, as this is a fairly critical bug. If cards aren't importing transactions, you can't really use the feature.

**Comment by mountiny** [comment] 2024-11-06 02:27
Discussing https://expensify.slack.com/archives/C05LX9D6E07/p1730859995168509?thread_ts=1730755524.099499&cid=C05LX9D6E07

**Comment by mountiny** [comment] 2024-11-11 13:11
Confirmed that when conencted in OldDot the transactions been pulled correct, this is issue specific to the workspace feeds

**Comment by nkuoch** [comment] 2024-11-11 14:44
When I tried myself:

>  431 No password

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/2fad4f1e-5389-474e-b33a-82dd1a8cd964">

Card gets created with no password, because `NVP::get(db, policyAccountID, "private_" + SToLower(bankName) + "CompanyID");` doesn't exist.

It actually starts failing even before. When calling OpenPolicyCompanyCardsFeed, I get `404 Feed not found` because the domain_member nvp doesn't have `settings.companyCards`:

In db, the domain_member NVP looks like this:

```
nkuoch@db1.lax:~$ sudo readdb.sh -tsv "SELECT * FROM nameValuePairs WHERE accountID=18663327"
accountID	name	value	created
18663327	domain_member	{"settings":{"oAuthAccountDetails":{"oauth.chase.com":{"accountList":["CREDIT CARD...3068","TOTAL CHECKING...6155"],"credentials":"...","expiration":1731333390}}}}	2024-11-11 13:31:02
```

**Comment by nkuoch** [comment] 2024-11-11 14:52
cc @robertjchen as I'm not too familiar with the whole flow. Should we have called `AddCommercialFeed` at some point?

**Comment by mountiny** [comment] 2024-11-11 15:14
Yeah I was wondering the same about the `settings.companyCards` missing for the direct feeds and was not sure if its by design

**Comment by robertjchen** [comment] 2024-11-12 07:55
`settings.companyCards` should exist for all feeds types regardless of type since it stores settings around [`liabilityType`](https://github.com/Expensify/Auth/blob/main/auth/command/SetFeedTransactionLiability.cpp#L50) and accounting integrations, etc. which applies to all connections. If it doesn't exist, it should be initialized 👍

**Comment by mountiny** [comment] 2024-11-14 14:08
The web change will be deployed to production later today

**Comment by nkuoch** [comment] 2024-11-14 20:24
I've managed to configure a direct feed on my workspace, and succesfully assigned a card, but when OpenPolicyCompanyCardsFeed gets called, the card is not displayed 

Also, I see in the logs:

Nov 14, 2024 @ 18:47:47.330 | request_id:IemMtx bank:oauth.chase.com blob:[scraper] Invalid bank provided for commercial feed ~~ {"file":"\/var\/importapi.expensify.com\/lib\/class.Log.php","line":112} card_id:21510511 command:getAccountHistory email:nkuoch@expensifail.com host:scraper4.secure-us-east-1 level:info process:php-fpm timestamp:Nov 14, 2024 @ 18:47:47.330 type:scraper _id:ho0ALJMBj3iRn6uSxLMb _index:logs_expensify-031205 _score: - _type:log
-- | --

**Comment by robertjchen** [comment] 2024-11-15 08:28
Hm, it's odd that the bank `oauth.chase.com` is ending up in that flow, the [`login` for commercial cards ](https://github.com/Expensify/Server-Scraper/blob/5842a03cc8531ceac3c408e4251ab0dbba74f76c/scraperClasses/api.php#L39)is always `corporate`, and oauth-based bank connections should be using `oauth_corporate`.

We shouldn't even get to that point due to [this check in Auth](https://github.com/Expensify/Auth/blob/main/auth/command/OpenPolicyCompanyCardsFeed.cpp#L83-L88).

Maybe let's find out why the request is getting to Scrapers and then we can look at the `login` parameter to see if that might be a cause?

**Comment by nkuoch** [comment] 2024-11-15 08:44
@robertjchen yeah, login was "corporate". So, should I do [that](https://github.com/Expensify/Auth/pull/13181/files#diff-c4cef890e0d4d694d0f5cea107e03f34e39bef1e509a779e3a294326ab82b9beR68)?

**Comment by robertjchen** [comment] 2024-11-15 10:08
👍

**Comment by robertjchen** [comment] 2024-11-15 10:08
Yep, that should work!

**Comment by nkuoch** [comment] 2024-11-15 10:47
```
nkuoch@db2.sjc:~$ expensify_cqHelper.sh
This script is not a replacement for buddychecks
Pro-tip: did you remember to run a SELECT to estimate how long your query will take?
Using host: db2.sjc
WARNING: Skipping smokealarm initialization because we're in an interactive terminal
password:
query: UPDATE cards SET login='oauth_corporate' WHERE cardID=21510511;
reason: https://github.com/Expensify/App/issues/52000#issuecomment-2478248952

CustomQuery
query: UPDATE cards SET login='oauth_corporate' WHERE cardID=21510511;
password: XXXXXXXX
reason: https://github.com/Expensify/App/issues/52000#issuecomment-2478248952
connection: close
Execute? (ctrl-c to cancel)
200 OK
commitCount: 25619982036
Connection: close
nodeName: auth.db2.sjc
peekTime: 19
processTime: 140
requestID: zq8ObN
totalTime: 618
unaccountedTime: 144
Content-Length: 2
```

**Comment by nkuoch** [comment] 2024-11-15 10:50
Now getting `No credentials exist in the cookie.` when trying to Sync the card:

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/c891537f-4aa2-464a-b248-a6ac4321c00f">

**Comment by nkuoch** [comment] 2024-11-15 10:53
@robertjchen Should we have put something in the cookie column of the cards table when calling AssignCard? Or should we update scrapers to not require it?

**Comment by robertjchen** [comment] 2024-11-15 11:01
Yes, when assigning the card we would need to have put the credentials from the successful OAuth authentication into there 🤔 

This is traditionally how the flows worked, but we also store the credentials in`domain_member`? 🤔 Perhaps we can update Auth or Scraper code to get it from `domain_member` instead?

Alternatively, the FE could pass the credentials after a successful connection from `domain_member` when calling `AssignCard`

**Comment by nkuoch** [comment] 2024-11-15 11:06
So I can use the credentials from domainMember oAuthAccountDetails and put them in the card cookie as is?

<img width="523" alt="image" src="https://github.com/user-attachments/assets/3b705194-62d3-4575-a29f-3614d0ca74b0">

**Comment by nkuoch** [comment] 2024-11-15 12:29
Ah no, credentials in domain_member are `CipherUtils::encryptThenSeal(JSON::safeEncode(` ..which we can't decrypt auth side ...

**Comment by nkuoch** [comment] 2024-11-15 12:55
Will do as in oldDot, even if it means loosing 1:1:1 for AssignCard: https://github.com/Expensify/Web-Expensify/pull/44444

**Comment by mountiny** [comment] 2024-11-18 12:13
Waiting for web and auth deploys

**Comment by mountiny** [comment] 2024-11-21 13:22
We confirmed this works well for accounts on public domains but just making this cleaned up for private domains

**Comment by nkuoch** [comment] 2024-11-28 15:58
I tested with chase, when I assigned the card, transactions got automatically imported! 🥳 
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/69d8443a-1897-4de5-9d76-983b95ab9d97">

**Comment by nkuoch** [comment] 2024-11-28 16:25
Soo ... closing. Please reopen if any issue remains on any bank.

**Closed by nkuoch** 2024-11-28 16:25 UTC
Labels: Daily, Bug, AutoAssignerNewDotQuality
