### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] LHN - When receiving a large message with empty lines, the LHN does not display "..."

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32497] opened 2023-12-05 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Send a message containing text and empty lines, for example:
"Hello

Hi"

## Expected Result:
Any message received by the user that does not fit completely into the preview in LHN should be displayed with "..." at the end of the preview

## Actual Result:
When receiving a large message with empty lines, the LHN does not display "..."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/27a5f6c6-d293-499f-8d6f-93f04c9f44f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb7a63f85d985319</li>
        <li>Upwork Job ID: 1732095470234775552</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-12-05 20:51
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

LHN - When receiving a large message with empty lines, the LHN does not display

## What is the root cause of that problem?

The main problem is that as alt text we use the `lastMessage` from report which by default truncates all text after a newline

https://github.com/Expensify/App/blob/f80fbe34db2dbb5839946ccfe8b46d8c16462f83/src/libs/ReportUtils.ts#L1148

## What changes do you think we should make in order to solve the problem?

Since the old`lastMessage` values only store half the text, we can use `lastMessageHtml` instead and then using `parser.htmlToText` get text and to make the text on one line and remove line breaks, we can use `replace(/\n/g, ' ')`


As result 

`lastMessageTextFromReport = report ? parser.htmlToText(report.lastMessageHtml).replace(/\n/g, ' ') || '' : '';`

https://github.com/Expensify/App/blob/f80fbe34db2dbb5839946ccfe8b46d8c16462f83/src/libs/OptionsListUtils.js#L416


## What alternative solutions did you explore? (Optional)
NA

**Comment by mollfpr** [comment] 2023-12-11 15:11
Sorry for the delay.

@sakluger Could you give an example of the expected result from the message in the description?

My understanding of the expected result will be `Hello                    ...`

**Comment by sakluger** [comment] 2023-12-11 17:36
@mollfpr I agree that would be the expected result in this case.

**Comment by sakluger** [comment] 2023-12-12 09:20
@dukenv0307 that's interesting, we basically show a newline as a space in the preview.

In this case, where there are many newlines in a row, I think we would be consistent and use a space for every newline, then add the `...` at the end of the preview line. That means that it might look like @mollfpr's example (`Hello                    ...`) or it might include the text at the bottom (`Hello                 ser...`), depending on the number of blank newlines.

**Comment by mollfpr** [comment] 2023-12-14 14:49
I agree with the @dukenv0307 proposal, and we also need to update the BE to align the last message text. I tested on the proposal and got the same expected result.

🎀 👀 🎀 C+ reviewed!

**Comment by MariaHCD** [comment] 2023-12-15 08:07
Looking at the original PR that implemented the BE logic for formatting the lastMessageText from @aldo-expensify: https://github.com/Expensify/Web-Expensify/pull/35658

It seems we intentionally only used the first line when formatting the text. I've put up a [BE PR](https://github.com/Expensify/Web-Expensify/pull/40111) that implements the proposed logic from @dukenv0307's [proposal](https://github.com/Expensify/App/issues/32497#issuecomment-1846876980), but wanted to also clarify if there's a specific reason for the original implementation. 

Once the updated logic in BE PR is approved (or not), we can determine whether the App's logic in `formatReportLastMessageText` needs to be updated as well.

**Comment by MariaHCD** [comment] 2023-12-18 06:41
BE PR was merged: https://github.com/Expensify/Web-Expensify/pull/40111

Let's have the same change on the frontend too as per @dukenv0307's [proposal](https://github.com/Expensify/App/issues/32497#issuecomment-1846876980).

**Comment by sakluger** [comment] 2024-01-11 19:53
Sent an offer to @dukenv0307.

@mollfpr are you still requesting via NewDot, or should I send you an offer via Upwork? Either way, could you please complete the BZ checklist? Thanks!

**Comment by mollfpr** [comment] 2024-01-12 04:09
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This improvement and we do need the BE change to solved this issue.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open a chat
2. Send a message with some lines break, and the first line is short
3. **_Verify_** that in LHN, the last message is displayed with `...`
4. 👍 or 👎 

---

@sakluger I'll be requesting through NewDot; thank you!

**Comment by MariaHCD** [comment] 2024-01-12 11:33
@mollfpr for the regression test steps, I'm thinking we should provide some samples to make it more clear what the expected result should be:

### Input:
```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
```

Expected result: The LHN displays the message truncated to 79 characters & with an ellipses `...` at the end.

![Screenshot 2024-01-12 at 3 30 30 PM](https://github.com/Expensify/App/assets/12268372/353ebcda-c3c2-4b47-b144-26c1a00f80e6)


### Input:
```
Lorem Ipsum is simply dummy text 





of the printing and typesetting industry. 



Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 





It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus 
```

Expected result: The chat in the LHN shows the first line, followed by a space and then a few characters of the second line ending with `...`

![Screenshot 2024-01-12 at 3 32 38 PM](https://github.com/Expensify/App/assets/12268372/aa5a9e7c-a665-4dc8-91a6-d5ee0ba3496e)

### Input:

```
Line 1






Line 2






Line 3
```

Expected result: The chat in the LHN shows all three lines of the message separated by a space 

![Screenshot 2024-01-12 at 3 31 15 PM](https://github.com/Expensify/App/assets/12268372/54eecd42-ac42-4a1d-b46c-9f39f2c79de0)

**Comment by sakluger** [comment] 2024-01-13 00:34
Thanks @mollfpr, and thanks @MariaHCD for the added suggestion, I agree that including specifics of what to type is helpful in regression tests to guarantee the tests are carried out consistently.

@dukenv0307 can you please accept the Upwork offer and let me know once you have? Thanks!

**Comment by JmillsExpensify** [comment] 2024-01-14 08:26
$500 payment approved for @mollfpr based on [this comment](https://github.com/Expensify/App/issues/32497#issuecomment-1887597635).

**Comment by sakluger** [comment] 2024-01-15 17:22
Thanks! I've finished paying out the contract, all done here.

**Closed by sakluger** 2024-01-15 17:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
