### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] Chat -  Email pattern is not recognized when sending a comment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28629] opened 2023-10-02 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Type in compose box [`code`](mailto:%60code%60email@gmail.com)[email@gmail.com](mailto:email@gmail.com)        (without any space)
3. Notice the email is not recognized as email link

## Expected Result:
Email pattern should be recognized and become blue link style

## Actual Result:
Email pattern is not recognized

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9f1a9c5c-acf9-4398-8a19-72cd86aee73e

https://github.com/Expensify/App/assets/78819774/f693a44b-fd37-4281-8b6e-3333b32b8d35

https://github.com/Expensify/App/assets/78819774/de6fb8f5-4983-48ac-bc77-d770af31da37

https://github.com/Expensify/App/assets/78819774/aa02e491-4f6d-4ecb-a3fd-2a985d478863

https://github.com/Expensify/App/assets/78819774/c34c5f06-0117-4204-9344-6542c7cd79f1

https://github.com/Expensify/App/assets/78819774/39722c47-7b2f-44da-a90f-173908b4f565

https://github.com/Expensify/App/assets/78819774/bf194de5-2451-455d-9ce1-4d091a14870c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tsa321

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696219306455269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181685d1a16ff4d31</li>
        <li>Upwork Job ID: 1708873970110574592</li>
        <li>Last Price Increase: 2023-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Contributor | 27335685</li>
<li>tsa321 | Reporter | 27335687</li>
</ul></li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-10-02 17:01
I can reproduce this. Keeping External label.

**Comment by akamefi202** [comment] 2023-10-02 19:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Email pattern is not recognized when sending a comment with inline code & email.

### What is the root cause of that problem?
If we send any comment, `ExpensiMark` class of `expensify-common` repo translates the comment into html text.
```
`code`test@test.com
```
If the user sends above comment, `inlineCodeBlock` regex processes the text first.
```
<code>code</code>test@test.com
```
Then the regex for `autoEmail` blocks replacement if the comment contains any tag before email, only except `<em>` tag.

https://github.com/Expensify/expensify-common/blob/ab4895807dd9a26f64bfaee80db15ee2c48a5124/lib/ExpensiMark.js#L130-L134

### What changes do you think we should make in order to solve the problem?
We need to update the regex for `autoEmail` to allow `</code>` & `</pre>` tag just before email.

```
regex: new RegExp(
                    `(?![^<]*>|[^<>]*<\\/(?!em|code|pre))([^\\w'#%+-]|^|<em>|<\\/code>|<\\/pre>)${CONST.REG_EXP.MARKDOWN_EMAIL}(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`,
                    'gim',
                ),
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Christinadobrzyn** [comment] 2023-10-05 19:59
reviewing proposals

**Comment by jjcoffee** [comment] 2023-10-09 15:55
@ZhenjaHorbach @akamefi202 Could you add extra detail to your proposals explaining what you're proposing to add to the regex and why it works?

**Comment by akamefi202** [comment] 2023-10-09 16:12
@jjcoffee I updated the proposal with more details. Please review again.
https://github.com/Expensify/App/issues/28629#issuecomment-1743629413

**Comment by Christinadobrzyn** [comment] 2023-10-12 20:18
hey @jjcoffee could you check out the revised proposal https://github.com/Expensify/App/issues/28629#issuecomment-1753296901

Or let me know if you'd like to see more proposals.

**Comment by jjcoffee** [comment] 2023-10-13 15:03
@Christinadobrzyn Sorry I haven't had a chance to test the updated proposal properly yet. I will add it to my list for Monday!

**Comment by eh2077** [comment] 2023-10-15 08:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Email pattern is not recognized when sending a comment.

### What is the root cause of that problem?

The root cause of this issue is that the [regex](https://github.com/Expensify/expensify-common/blob/bdbdf44825658500ba581d3e86237d7b8996cc2e/lib/ExpensiMark.js#L180) of `autoEmail` 

```js
`(?![^<]*>|[^<>]*<\\/(?!em))([^\\w'#%+-]|^|<em>)${CONST.REG_EXP.MARKDOWN_EMAIL}(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`,
```

can't match following intermediate text(with `inlineCodeBlock` applied)

```
<code>code</code>test@gmail.com
```

In the starting negative lookahead group, `(?![^<]*>|[^<>]*<\/(?!em))`, the first alternative, `[^<]*>`, skips to match substring, `>test@gmail.com`, because it matches the first character `>`. So, the email is not rendered as anchor tag.

### What changes do you think we should make in order to solve the problem?

Based on the RCA above, we know that the regex piece `[^<]*>` of the starting negative lookahead group is to skip match text inside a tag, like inside the opening tag of anchor tag

```html
<a href="https://staging.new.expensify.com/details/test@expensify.com" target="_blank" rel="noreferrer noopener">https://staging.new.expensify.com/details/test@expensify.com</a>
```

The match we want to skip should contains multiple characters of `[^<]`.

To this issue, we can improve the regex piece `[^<]*>` to `[^<]+>` and the new regex will be

```js
`(?![^<]+>|[^<>]*<\\/(?!em))([^\\w'#%+-]|^|<em>)${CONST.REG_EXP.MARKDOWN_EMAIL}(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`,
```

And we can pass all test cases of expensify-common lib.

### What alternative solutions did you explore? (Optional)

If we dive deeper into the  [regex](https://github.com/Expensify/expensify-common/blob/bdbdf44825658500ba581d3e86237d7b8996cc2e/lib/ExpensiMark.js#L180) 

```js
`(?![^<]*>|[^<>]*<\\/(?!em))([^\\w'#%+-]|^|<em>)${CONST.REG_EXP.MARKDOWN_EMAIL}(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`,
```

we find that the starting negative lookadhead group is redundant because the ending negative lookahead group is already sufficient to skip invalid match. For example, the alternative group, `((?:(?!<a).)+)?<\\/a>`, skips to match email both the `href` property part and text part.

So, we can consider to simplify the regex to

```js
`([^\\w'#%+-]|^)${CONST.REG_EXP.MARKDOWN_EMAIL}(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>|<\\/mention-user>))`,
```

by removing the starting negative lookahead group and add an alternative group in the ending negative lookahead group to skip matching email inside `<mention-user>` tag.

By doing so, we also fix the issue and pass all tests of Expensify-common.

**Comment by jjcoffee** [comment] 2023-10-16 15:02
@Christinadobrzyn Sorry I'm ill at the moment, hope to get better soon, but feel free to reassign if it's urgent enough!

**Comment by Christinadobrzyn** [comment] 2023-10-17 22:29
Aw, I'm sorry @jjcoffee - I'll reassign this so you don't have to stress and can focus on getting better. I hope you feel better soon!

**Comment by Christinadobrzyn** [comment] 2023-10-17 22:30
Hi @burczu - I reassigned this because @jjcoffee isn't feeling well and I don't want to stress him with work. Can you review the proposals and let us know if any will work?

**Comment by burczu** [comment] 2023-10-19 07:37
@Christinadobrzyn Sure thing! I'll take a look at this issue soon.

**Comment by burczu** [comment] 2023-10-20 09:47
I've just reviewed all the proposals and [the one](https://github.com/Expensify/App/issues/28629#issuecomment-1743629413) from @akamefi202 works best for me and I personally like it the most, so I would proceed with it.

The [proposal](https://github.com/Expensify/App/issues/28629#issuecomment-1743434732) from @ZhenjaHorbach does not work for me and [the one](https://github.com/Expensify/App/issues/28629#issuecomment-1763325053) from @eh2077 works but it leaves an angle bracket at the end (please see the image below):

![Screenshot 2023-10-20 at 11 45 09](https://github.com/Expensify/App/assets/7771498/2bbf5373-b51f-4b07-8909-69f2e39470d6)

🎀 👀 🎀 C+ reviewed

**Comment by eh2077** [comment] 2023-10-20 10:00
@burczu Thanks for reviewing proposals. But I'm confused about the test case you shared. Can you share the original input please?

**Comment by burczu** [comment] 2023-10-20 10:45
@eh2077 please see the video:

https://github.com/Expensify/App/assets/7771498/3132f360-7ac0-4cbe-b102-f059c70b9bc5

I'm using regex from your proposal here:

```
(?![^<]+>|[^<>]*<\\/(?!em))([^\\w'#%+-]|^|<em>)${CONST.REG_EXP.MARKDOWN_EMAIL}(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))
```

**Comment by eh2077** [comment] 2023-10-20 13:05
@burczu I can't reproduce it from my end. See demo

https://github.com/Expensify/App/assets/117511920/7d9ccadd-0194-41ad-b18a-2de1d6f00334

The diff I applied
<img width="600" alt="image" src="https://github.com/Expensify/App/assets/117511920/c5bc109b-57d3-46f8-9afa-d4e81c667eab">

**Comment by neil-marcellini** [comment] 2023-10-20 21:22
I agree with the C+ that @akamefi202's [proposal](https://github.com/Expensify/App/issues/28629#issuecomment-1743629413) looks good. Are there any other tags that we should also consider which might come before an email?

@eh2077 your proposal is very good as well, but I don't quite follow every piece of your explanation. It's a complex regex and I like that you want to simplify it, but it also comes with more risk, I think. Would you please edit your explanation in an attempt to make it even more clear? Also if you could show some unit test examples that would really help.

What do you think @burczu? I'm holding off on assignment because I like the idea of simplifying the regex.

**Comment by eh2077** [comment] 2023-10-23 06:57
### Proposal
[Updated](https://github.com/Expensify/App/issues/28629#issuecomment-1763325053) alternative solution to simplify the regex with more detail explanation and examples.

cc @burczu @neil-marcellini

**Comment by neil-marcellini** [comment] 2023-10-23 18:40
Thank you for the updated detailed proposal @eh2077. Breaking down the regex really helped and I like the solution a lot. Hired.

**Comment by eh2077** [comment] 2023-10-24 05:24
@burczu The PR https://github.com/Expensify/expensify-common/pull/590 of expensify-common is ready for review, thanks!

cc @neil-marcellini

**Comment by eh2077** [comment] 2023-10-24 15:03
The PR https://github.com/Expensify/expensify-common/pull/590 has been approved and merged by the default assigned reviewer. 

@burczu  I raised PR https://github.com/Expensify/App/pull/30260 for App to bump the version of expensify-common. Please help to review it when you're free, thanks!

**Comment by burczu** [comment] 2023-10-31 13:15
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: **Didn't find any.**
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **n/a**
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **n/a**
* [ ]  [@burczu] Determine if we should create a regression test for this bug. **I don't think we need regression tests here - the issue didn't break any crucial flows of the App.**
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@Christinadobrzyn] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Christinadobrzyn** [comment] 2023-11-06 23:19
hey @burczu or @eh2077, do you have a regression test?

**Comment by burczu** [comment] 2023-11-07 06:08
@Christinadobrzyn As I wrote in my previous comment:

> I don't think we need regression tests here - the issue didn't break any crucial flows of the App.

**Comment by Christinadobrzyn** [comment] 2023-11-07 17:24
Payouts due:

Issue Reporter: $50 @tsa321 (paid through Upwork)
Contributor: $500 + $250 @burczu (no payment since they are a contractor) 
Contributor+: $500 + $250 @eh2077 (paid through Upwork)

Eligible for 50% #urgency bonus? Y - based on https://github.com/Expensify/App/issues/28629#issuecomment-1779766836

Upwork job is [here](https://www.upwork.com/jobs/~0181685d1a16ff4d31).

**Comment by Christinadobrzyn** [comment] 2023-11-07 17:27
Paid based on [this](https://github.com/Expensify/App/issues/28629#issuecomment-1799286013) payment structure. Closing this GH as complete

**Closed by Christinadobrzyn** 2023-11-07 17:27 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
