### ISSUE TITLE
[HOLD for payment 2024-07-25] [$250] Pay someone - Paid system message is not highlighted when clicking on the message link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44588] opened 2024-06-28 01:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43742
## Action Performed:
1. Go to staging.new.expensify.com/
2. Go to FAB > Pay someone
3. Enter amount, select a user and pay them
4. Go to transaction thrad
5. Right click on the paid system message > Copy link
6. Paste the link in the transaction thread
7. Tap on the link

## Expected Result:
The paid system message will be highlighted

## Actual Result:
The paid system message is highlighted only briefly. The report loads briefly with skeleton and the message is no longer highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b5a13544-7f43-4d68-93fc-7285afa0868b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166f7822923f5e0f7</li>
        <li>Upwork Job ID: 1806505240961845071</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102950113</li>
<li>bernhardoj | Contributor | 102950114</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment] 2024-06-28 01:14
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-06-28 05:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The paid system message is highlighted only briefly. The report loads briefly with skeleton and the message is no longer highlighted

### What is the root cause of that problem?
When the iou report is the combine report, we always remove the `reportActionID` param here.

https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/home/ReportScreen.tsx#L374-L379
### What changes do you think we should make in order to solve the problem?
We shouldn't remove the `reportActionID` in the URL if the linked `reportActionID` is the current action of iou report. We can use `linkedAction` to check this

```
useEffect(() => {
    if (!transactionThreadReportID || !route?.params?.reportActionID || linkedAction.reportActionID) {
        return;
    }
    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(route?.params?.reportID));
}, [transactionThreadReportID, route?.params?.reportActionID, route?.params?.reportID, linkedAction?.reportActionID]);
```
https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/home/ReportScreen.tsx#L374-L379

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-06-28 05:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paid system message is highlighted and immediately not highlighted when linking to the action.

### What is the root cause of that problem?
We have an effect that will clear the report action ID from the params if the report is a one-transaction report.
https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/home/ReportScreen.tsx#L374-L379

This is to fix https://github.com/Expensify/App/pull/40157. Basically, we don't allow users to link to the one-transaction report money request action, including the paid money action. But the paid money action is recently updated to always be shown in this [PR](https://github.com/Expensify/App/pull/43742), however, this issue isn't limited to paid money action, but to all actions in the report.

### What changes do you think we should make in order to solve the problem?

We need to update the effect logic to be stricter, so it only applies to money request action (except paid/sent) in a one-transaction report.
https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/pages/home/ReportScreen.tsx#L374-L379

```
useEffect(() => {
    if (!transactionThreadReportID || !route?.params?.reportActionID || ReportActionsUtils.isSentMoneyReportAction(linkedAction) || !ReportActionsUtils.isMoneyRequestAction(linkedAction)) {
        return;
    }
    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(route?.params?.reportID));
}, [transactionThreadReportID, route?.params?.reportActionID, route?.params?.reportID]);
```

If the linked action is sent money action or if the linked action is not a money request action, we do nothing.

**Comment by hungvu193** [comment] 2024-06-28 09:28
Reviewing shortly

**Comment by hungvu193** [comment] 2024-06-28 09:54
Oops, I got loop API call on ReportScreen that blocked me from testing proposal.

In the meantime, can you guys test this testcase please?

1. Go to FAB > Pay someone
2. Enter amount, select a user and pay them
3. Go to transaction thread
4. Right click on the paid system message > Copy link
5 Paste the link in the transaction thread
6. Tap on the link
7. Reload the page
8. Verify the page is not empty.
Repeat steps above but with other report action like request money...etc. TIA

**Comment by nkdengineer** [comment] 2024-06-28 10:10
@hungvu193 I think you can reset cache and open this report again.

**Comment by hungvu193** [comment] 2024-06-28 10:23
> @hungvu193 I think you can reset cache and open this report again.

Unfortunately, I don't think it works for me 😭 . It still shows infinite skeleton after few refresh.

Can you please check the testcase I mentioned above?

**Comment by nkdengineer** [comment] 2024-06-28 10:52
@hungvu193 it only shows the loading for a few time. For this bug we don't need to refresh the page. We only need to past the link to the composer and click on the link to reproduce this bug.

https://github.com/Expensify/App/assets/161821005/52896514-ffe4-4138-9cd2-70ffa83dec6d

**Comment by pankajsoftyoi** [comment] 2024-06-28 11:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paid system message is not highlighted when clicking on the message link

### What is the root cause of that problem?
The linked message is not getting highlighted as it isn't considering `reportActionID` in route navigation as per the code given below.
https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/ROUTES.ts#L234-L240

### What changes do you think we should make in order to solve the problem?

To highlight the message ID,  `reportActionID` need to pass in route params while navigating to `ROUTES.REPORT_WITH_ID`.
https://github.com/Expensify/App/blob/e78c38e85aab34c815b95d8763f3d01f3a58b42d/src/pages/home/ReportScreen.tsx#L378
replace it with
`Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(route?.params?.reportID, route?.params?.reportActionID));`

### What alternative solutions did you explore? (Optional)

**Comment by hungvu193** [comment] 2024-06-28 14:27
> @hungvu193 it only shows the loading for a few time. For this bug we don't need to refresh the page. We only need to past the link to the composer and click on the link to reproduce this bug.
> 
>  Screen.Recording.2024-06-28.at.17.50.16.mov

Yeah, but while testing proposal, I got a bug where I clicked the link and reload, the screen went empty.

**Comment by hungvu193** [comment] 2024-06-30 15:59
> We need to update the effect logic to be stricter, so it only applies to money request action (except paid/sent) in a one-transaction report.

@bernhardoj would you mind to explain why?

Also while testing all 3 proposals there will be a case when I tried to click the link again even I added more comments, I couldn't scroll to see them. Check the video below:


https://github.com/Expensify/App/assets/16502320/79dfacf5-05c0-477d-8698-35993317c1e5

**Comment by bernhardoj** [comment] 2024-07-01 02:56
> @bernhardoj would you mind to explain why?

Because that's what the [original PR](https://github.com/Expensify/App/pull/40157) should do. We don't want the logic to affect other type of messages. For example, we currently unable to highlight a normal message too in a one-transaction report.

> Also while testing all 3 proposals there will be a case when I tried to click the link again even I added more comments, I couldn't scroll to see them

Can't repro, but it should be out of scope too since we don't modify the comment linking logic.

**Comment by hungvu193** [comment] 2024-07-01 07:28
@bernhardoj  Thanks for your context. I agree with you at this point.

@pankajsoftyoi Your proposal will re-create [this bug](https://github.com/Expensify/App/issues/40087) that we tried to [fix here](https://github.com/Expensify/App/pull/40157). 
<details><summary>Test case</summary>

https://github.com/Expensify/App/assets/16502320/eb1fb1cb-537d-4e54-b9c2-49f583aa0110

</details>

@nkdengineer Your proposal caused a bug while testing with held request action message, please check below video:

<details><summary>Test case</summary>


https://github.com/Expensify/App/assets/16502320/841b4491-9804-4324-a93b-0518165ca4e2

</details>

Thanks for proposals everyone. In this case, I'll go with @bernhardoj 's [proposal here](https://github.com/Expensify/App/issues/44588#issuecomment-2196179504).

🎀 👀 🎀  C+ reviewed

**Comment by nkdengineer** [comment] 2024-07-01 08:19
> if (!transactionThreadReportID || !route?.params?.reportActionID || (linkedAction?.reportActionID && !ReportActionsUtils.isMoneyRequestAction(linkedAction)) || ReportActionsUtils.isSentMoneyReportAction(linkedAction)) {
           
@hungvu193 For this case, I updated my proposal to fix this. I think we should accept comment linking for all actions of the iou report in the combine report instead of only send money request action because for the transaction thread report action in this report when we copy the link, it will link to the transaction thread report, so it doesn't have any problem when we actions of iou report in the combine report.

**Comment by nkdengineer** [comment] 2024-07-02 02:27
@hungvu193 What do you think with my comment here https://github.com/Expensify/App/issues/44588#issuecomment-2199530942?

**Comment by hungvu193** [comment] 2024-07-02 04:28
> @hungvu193 What do you think with my comment here [#44588 (comment)](https://github.com/Expensify/App/issues/44588#issuecomment-2199530942)?

Sorry I missed that message. In my opinion, that sounds more like a feature request to me. At the moment, I think we should aim to fix what's left of #40157.

**Comment by nkdengineer** [comment] 2024-07-02 07:50
@hungvu193  After the update here https://github.com/Expensify/App/issues/44588#issuecomment-2199530942, my proposal will not cause this bug again.

**Comment by bernhardoj** [comment] 2024-07-02 08:29
Open the PR but still in draft. Left a comment in the PR.

cc: @hungvu193

**Comment by hungvu193** [comment] 2024-07-03 08:25
> @hungvu193 After the update here [#44588 (comment)](https://github.com/Expensify/App/issues/44588#issuecomment-2199530942), my proposal will not cause this bug again.

@nkdengineer  I'm not saying your updated proposal doesn't work, I don't think we need to accept comment linking for all actions of the IOU report as it's more of feature request.


====================================

> Open the PR but still in draft. Left a comment in the PR.
> 
> cc: @hungvu193

@bernhardoj I replied in the PR.

**Comment by hungvu193** [comment] 2024-07-09 00:09
PR is under review

**Comment by hungvu193** [comment] 2024-07-10 16:29
Same

**Comment by bernhardoj** [comment] 2024-07-18 13:55
I'll request in ND once payment is due.

**Comment by hungvu193** [comment] 2024-07-24 15:40
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40157
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40157/files#r1690036809
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: Yes

**Regression Test**:
1. Go to any report and submit an expense.
2. Enter amount, select a user and pay them.
4. Click on that expense to open the thread.
5. Right click on the paid system message > Copy link.
6. Paste the link in the transaction thread.
7. Click on that link.
8. Verify that the paid system message is highlighted.

Do we 👍 or 👎 ?

**Comment by twisterdotcom** [comment] 2024-07-24 23:40
Payment Summary:

- @hungvu193 paid $250 [here](https://www.upwork.com/nx/wm/offer/102950113) (Reviewer)
- @bernhardoj paid $250 via NewDot Manual Request (Contributor)

**Closed** 2024-07-24 23:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-07-25 03:05
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-26 00:43
$250 approved for @bernhardoj
