### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Help - Send a message button opens help.expensify.com in a new tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39172] opened 2024-03-28 12:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to help.expensify.com
2. Click Send a message button under "Didn't find what you were looking for?".

## Expected Result:
User is redirected to Concierge chat as it says "Concierge is here to answer all your questions.".

## Actual Result:
User is redirected to help.expensify.com in a new tab.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/28efd27b-186d-4a7d-a97b-df1647d264a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01761bb2ae86cc484e</li>
        <li>Upwork Job ID: 1773423546823450624</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-28 12:24
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by CortneyOfstad** [comment] 2024-03-28 18:54
I am able to recreate this as well — getting eyes on it!

**Comment by CortneyOfstad** [comment] 2024-03-28 18:55
@rojiphil we have a proposal above for this issue [here](https://github.com/Expensify/App/issues/39172#issuecomment-2025106862) – feel free to share your feedback when you have a chance! Thanks!

**Comment by rojiphil** [comment] 2024-03-29 11:46
@gijoe0295 proposal [here](https://github.com/Expensify/App/issues/39172#issuecomment-2025106862) LGTM. 
The RCA is correct and the proposed changes will set the main site url and launch the concierge page. 
🎀👀🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2024-04-01 22:43
Thanks for the review @rojiphil, assigning @gijoe0295 🚀

**Comment by CortneyOfstad** [comment] 2024-04-17 14:42
PR deployed to staging a week ago, so still have to wait a bit

**Comment by rojiphil** [comment] 2024-04-19 15:17
**BugZero Checklist:**  
* [x]  [@rojiphil] The PR that introduced the bug has been identified. [Link to the PR](https://github.com/Expensify/App/pull/32526) 
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. [Link to comment](https://github.com/Expensify/App/pull/32526/files#r1572528312)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **I don't think a discussion is required here as the current checklist itself is good enough to catch such regressions**
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. **Since the functionality is required to reach out to the concierge team, it may be good to have a regression test for this bug**
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Test Steps**
1. Go to Expensify Help Home
2. Press Send a message button
3. Verify user is directed to Concierge chat

**Comment by CortneyOfstad** [comment] 2024-04-25 18:12
## Payment Summary

@gijoe0295 — paid $500 via Upwork
@rojiphil — paid $500 via Upwork

**Comment by CortneyOfstad** [comment] 2024-04-25 18:14
Regression test here — https://github.com/Expensify/Expensify/issues/390863

Thanks all — closing!

**Closed by CortneyOfstad** 2024-04-25 18:14 UTC
Labels: External, Daily, Awaiting Payment, Bug
