### ISSUE TITLE
[$250] [HOLD for payment 2024-06-03] [Guided Setup Stage 2] Multiple workspaces are created when navigating back and changing the business name

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41838] opened 2024-05-08 12:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/41593
**Email or phone of affected tester (no customers):** shussain+acjhn1@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Sign up with a new account
2. Click Manage my team's Expenses in the onboarding modal
3. Verify that the next question you're asked is for your business name
4. Enter your business name
5. Verify that the next question you're asked is for your personal name
6. Click back button and change business name
7. Notice in background multiple workspace created

## Expected Result:
Changing the business name after navigating back should not create multiple workspaces; it should only update the existing workspace with the new name

## Actual Result:
Multiple workspaces are created when navigating back and changing the business name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/76a878c0-0ca6-40b6-90a6-1c413e59571f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ce1c5b54ab34e82</li>
        <li>Upwork Job ID: 1795924034789011456</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by izarutskaya** [comment] 2024-05-08 12:27
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-08 12:27
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-08 12:28
Production 


https://github.com/Expensify/App/assets/115492554/fdb09279-3ce2-4678-864c-9711ef8b744d

**Comment by amyevans** [comment] 2024-05-08 15:00
This is an unintended side effect of the changes in https://github.com/Expensify/App/pull/41593 - @francoisl @DylanDylann @ishpaul777 shall we revert or are one of you available to get a fix PR together soon?

**Comment by trjExpensify** [comment] 2024-05-08 15:25
@mountiny @rezkiy37 might have some ideas as well. I think it's a bit of an edge case to confirm the business name and then go back and change it, so I'm not sure I'd call it a deploy blocker per se, but we should see what we can do about it.

**Comment by mountiny** [comment] 2024-05-08 16:17
Discussed with Tom and I think this does not have to be a deploy blocker as its a rare flow. The UX is not great, but not a blocker.

If we want to keep this behaviour of creating a workspace before the flow is completed (that is to be able to create correct guide calendar link in the message), we should probably consider adding some flag to the optimistic policy data so that when user goes back in the flow, we would not call `CreateWorkspace` but API to update the existing workspace name instead

**Comment by amyevans** [comment] 2024-05-08 16:50
Sounds good, I'll demote it. I agree the approach would be to call `UpdateWorkspaceGeneralSettings` with the new name if the user navigated back and then forward again, but I haven't looked at the code to see how achievable that is. @francoisl mind if I reassign you as CME since you've got more context?

**Comment by francoisl** [comment] 2024-05-08 19:07
Yes that works for me. As Vit said, we need to keep the `CreateWorkspace` API call where it is now rather than at the end of the flow, so that we can have the user's assigned guide's calendar link for the "Meet your setup specialist" task.

----

@cretadn22 I believe you're missing the `name` parameter when you're calling `updateGeneralSettings` in your proposal.
@ishpaul777 I'm going to assign you as C+ if that's ok, since you already have context on the issue.

**Comment by puneetlath** [comment] 2024-05-09 23:54
@francoisl I'll let you take CME on this one.

**Comment by trjExpensify** [comment] 2024-05-16 00:22
PR merged today!

**Comment by francoisl** [comment] 2024-05-29 21:03
Sounds good. Internal issue to create the regression test created, I'm going to assign a BZ to handle payments.

**Comment by MitchExpensify** [comment] 2024-06-02 20:14
Reminder set to pay tomorrow

**Comment by MitchExpensify** [comment] 2024-06-03 19:51
*Payment summary*:

- $250 @ishpaul777 requires payment (Needs manual offer from BZ)
- $250 @cretadn22 requires payment (Needs manual offer from BZ)

Offers sent in Upwork

**Comment by MitchExpensify** [comment] 2024-06-04 16:41
paid and contract ended, thank you!

**Closed by MitchExpensify** 2024-06-04 16:41 UTC
Labels: Engineering, Daily, Help Wanted, Awaiting Payment, Bug
