### ISSUE TITLE
Chat - Text (archived) is not translated in Spanish after switch language setting

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9018] opened 2022-05-14 15:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue is found when executing the PR #8436 
## Action Performed:
1. Go https://staging.new.expensify.com/

2. Log in with expensifail account A
3. Create a Workspace
4. Invite another user B to workspace
5. Go to OldDot and delete the Workspace
6. Log in with account B
7. Go to Setting - Preferences
8. Change language to Spanish
9. Go back to LHN and find your Workspace

## Expected Result:
Text (archived) is translated in Spanish after switch the langue settings

## Actual Result:
Text (archived) is not translated in Spanish after switch the language setting

## Workaround:
After refresh it gets updated

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1-60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5571379_Screenshot_20220514-112416_Chrome](https://user-images.githubusercontent.com/43996225/168439285-2f4e05c7-09a5-4028-9583-53242d2de045.jpg)

https://user-images.githubusercontent.com/43996225/168439287-28e9b337-4acc-433d-8095-3edcc4eff6b3.mp4

https://user-images.githubusercontent.com/43996225/168439290-9819d992-c1e4-4749-aa3b-630caee60c04.mp4
**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-05-15 23:41
The solution to this issue should use `ReportUtils.getReportName` to populate the report names in `SidebarLinks`

**Comment by stitesExpensify** [comment] 2022-05-16 22:13
@cead22 I'm going to hand this over to @srikarparsi to take on!

**Comment by cead22** [comment] 2022-05-17 17:23
Thanks!

**Comment by srikarparsi** [comment] 2022-05-19 06:20
I've been working on this issue and currently have a question regarding code practices and have also ran into a problem with getting data from Onyx.

Currently, when you change the language preference, most of the text in the chat is changing because it is listening for changes made to the locale setting in Onyx and updates the text based on that.

However, the title which includes "(archived)" is different because it only fetches data from Onyx at the beginning and doesn't update based on changes to locale. A fix could be to listen to these changes similar to the text but the problem is that the title text occurs in multiple places and it would just be better to update the title in Onyx directly. 

<img width="1728" alt="Screen Shot 2022-05-19 at 2 07 54 AM" src="https://user-images.githubusercontent.com/48188732/169222225-0dda08a0-bb12-4b01-80a4-a6bd11130793.png">

As shown in the screenshot above, the language is English, but the title says "archivado" since in Onyx, report_16 also has archivado appended to the end. When the page is refreshed from this state, the text changes from archivado to archived which is good, but in Onyx the report name still has (archivado) appended to the end since changing the locale doesn't update Onyx's individual reports. To fix this issue, we need to update each report in Onyx to have the right title name when the language preference is changed. A possible solution is below.

<img width="734" alt="Screen Shot 2022-05-19 at 2 15 12 AM" src="https://user-images.githubusercontent.com/48188732/169223283-931627e7-556f-4fce-9780-4aa8860d68c5.png">

First, I wanted to ask if it was an ok coding practice to update Onyx's reports in the setLocale method as shown above since the other text that changes based on language does it by listening to the language preference setting in Onyx.

Second, I'm running into an issue with the above code. I tried running the commented code but after not finding a way to get all the reports and iterate through them, I wanted to try and get just report_16. When I run that code, it logs undefined which I think means it did not find "report_16" as a key even though it is in Onyx as shown in the first two screenshots. I was thinking this is because that key isn't registered as one of the ones you can get data from but I'm not completely sure. Would anyone happen to know a workaround for this problem?

**Comment by roryabraham** [comment] 2022-05-19 15:05
Hi @srikarparsi, thanks for the write-up. We discussed this a bit in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1650935122490379), but here's my summary:

The `reportName` is a "composite" value that comes from multiple sources:

- The report itself
- personal details
- policies
- locale

And given our new API design that prohibits side-effects from API requests, we had to choose between:

- Storing that composite value in Onyx, and having the server update the reportName in Onyx whenever any of those values changes, OR
- Using those various values (already stored in Onyx, and able to be hooked up with Pusher for live data), and just compose them in the React code using a util function.

We settled on the second approach. So I recently wrote a function, [`ReportUtils.getReportName`](https://github.com/Expensify/App/blob/c16d2ebf853122a56edd606dd49e4a3cc4e28241/src/libs/ReportUtils.js#L453-L484), that is [throughly unit-tested](https://github.com/Expensify/App/blob/fa54389c1460cc478f1e988535ed31110f9ee15e/tests/unit/ReportUtilsTest.js#L100-L239) and generates the correct display name from those various values. What this means is that we should not directly reference the `reportName` field from the report stored in Onyx directly, anywhere in the application. Even setting the correct report name in Onyx on first load is problematic, because we have to ensure that all of those composite values are loaded before we set the report name.

So I think the approach you're taking (updating the reportName for all reports in Onyx, whenever the locale changes), isn't the best approach. Instead, here's what I recommend:

1. Make components use `ReportUtils.getReportName` to get the report name they display, not the `reportName` from Onyx
1. Ensure those components re-render when any of the four values used to create the "composite" `reportName` change. The best way to do this is _probably_ to:
    1. extract the `preferredLocale` Onyx connection out of `ReportUtils`, and instead take the current locale as a parameter to any functions using `preferredLocale` in the utils functions
    2. Wrap any components using those functions in `withLocalize`
    3. Pass the locale from `withLocalize` into the `ReportUtils` functions.
    4. That way, whenever the locale changes, `withLocalize` will re-render any components consuming that locale, and the reportName (or the result of any `ReportUtils` function dependent upon that locale) will also update

**Comment by srikarparsi** [comment] 2022-05-23 18:12
Stuck on understanding which methods are outdated. Messaged to setup a call.

**Comment by roryabraham** [comment] 2022-05-26 22:48
@srikarparsi – anything I can do to help get this over the finish line? I'm here to help + review when you need 🙂

**Comment by srikarparsi** [comment] 2022-06-07 20:46
looked at test cases but believe we might have to change the test cases and not the code so messaged Rory

**Comment by srikarparsi** [comment] 2022-06-09 21:31
Fixed by this pr: https://github.com/Expensify/App/pull/8569

**Closed by srikarparsi** 2022-06-09 21:31 UTC
Labels: Engineering, Daily, Internal
