### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] [Distance] Web - Map and map image doesn't zoom out and display long unconventional routes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27175] opened 2023-09-11 16:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Open the app
2. Click on plus and click on request money
3. Click on 'Distance'
4. In start, select 'India' and in Finish, select 'Pakistan'
5. Observe that map does not display the whole route as it is not straightforward
6. Complete the process, open the request money message twice to open request money page
7. Click on map image to see that map does not display the route fully

## Expected Result:
App should zoom out to display full route in map and image

## Actual Result:
App does not zoom out to display full route in map and image for long distance unconventional routes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.67.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f81488dc-661a-4ce9-8c76-9beb919302d7

https://github.com/Expensify/App/assets/93399543/1e567809-026d-4ad5-9279-048761caf851

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694103719072409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c90939608885c398</li>
        <li>Upwork Job ID: 1701278392102277120</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26914479</li>
<li>dhanashree-sawant | Reporter | 26914481</li>
</ul></li>
    </ul>
</details>

**Comment by mollfpr** [comment] 2023-09-15 18:10
@sumairq Are you suggesting to add the `zoomLevel` props to the map? What the `center` variable will do?

Also, could you attach a video of the working result?

**Comment by rakshitjain13** [comment] 2023-09-16 08:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App should zoom out to display full route in map and image


### What is the root cause of that problem?
Currently, to find the bounds of the map we are using only ```waypoints``` (start, end, stop points). This can be seen in the below code block to get bounds.
https://github.com/Expensify/App/blob/f4affe545df1e1d01f71eea40b7fe9c3e07f5aa3/src/components/MapView/utils.ts#L1-L13

### What changes do you think we should make in order to solve the problem?
We should also consider direction Points in getting the bounds of the map like below :
````
function getBounds(waypoints: Array<[number, number]>, directionCoordinates: undefined | [number, number][]): {southWest: [number, number]; northEast: [number, number]} {
    const lngs = waypoints.map((waypoint) => waypoint[0]);
    const lats = waypoints.map((waypoint) => waypoint[1]);
    if (directionCoordinates) {
        lngs.push(...directionCoordinates.map((coordinate) => coordinate[0]));
        lats.push(...directionCoordinates.map((coordinate) => coordinate[1]));
    }

    return {
        southWest: [Math.min(...lngs), Math.min(...lats)],
        northEast: [Math.max(...lngs), Math.max(...lats)],
    };
}

export default {
    getBounds,
};
````
Attaching a video for support :

https://github.com/Expensify/App/assets/54314936/6beba891-1138-4350-8d35-159b920552ef


### What alternative solutions did you explore? (Optional)
NA

**Comment by rakshitjain13** [comment] 2023-09-16 14:34
## Proposal 
Updated(https://github.com/Expensify/App/issues/27175#issuecomment-1722175816)

**Comment by mollfpr** [comment] 2023-09-18 14:04
@rakshitjain13 Where do we get the value of `directionCoordinates `?

**Comment by rakshitjain13** [comment] 2023-09-18 14:26
@mollfpr In MapView Component ````src/components/MapView/MapView.web.tsx```` directionCoordinates are passed as props and thus we will pass this variable in below function
https://github.com/Expensify/App/blob/9b302c980f4dcaba08d113f47d4852dc121c7e4e/src/components/MapView/MapView.web.tsx#L43

**Comment by mollfpr** [comment] 2023-09-18 15:29
Thanks @rakshitjain13!

The [proposal](https://github.com/Expensify/App/issues/27175#issuecomment-1722175816) from @rakshitjain13 looks good to me! It also makes sense to consider the direction coor to show the full map.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-09-21 15:38
@rakshitjain13 After the internal engineer reviews your proposal and assigns the issue to you. So you need to wait patiently.

**Comment by chiragsalian** [comment] 2023-09-27 23:22
sorry for the delay, my plate has been really full lately.
Proposal LGTM, feel free to create the PR @rakshitjain13

**Comment by rakshitjain13** [comment] 2023-09-28 15:01
@chiragsalian @mollfpr @maddylewis Raised the PR https://github.com/Expensify/App/pull/28396

**Comment by rakshitjain13** [comment] 2023-09-29 04:48
@mollfpr Updated the PR as per requested https://github.com/Expensify/App/pull/28416

**Comment by maddylewis** [comment] 2023-10-13 18:53
## Payments
- [ ] @mollfpr (C+ - $500 via NewDot)
- [ ] @rakshitjain13 requires payment (Contributor - $500 via Upwork)
- [ ] @dhanashree-sawant requires payment (Reporter - $50 via Upwork)

Contributor hired on 9/19. Merged 10/2.

**Comment by maddylewis** [comment] 2023-10-13 18:54
@mollfpr - can you review this checklist - thanks! https://github.com/Expensify/App/issues/27175#issuecomment-1747814177

**Comment by rakshitjain13** [comment] 2023-10-13 18:57
@maddylewis as per Melvin-bot I am eligible for a 50 % bonus. Also, I didn't receive any offer on upwork as it was my first PR. Let me know if I am missing something.

**Comment by maddylewis** [comment] 2023-10-13 18:59
@rakshitjain13 - yep, i updated the price already. and then will you follow the instructions outlined in this comment and apply to the job on Upwork? leave a comment here once you've done that and i will process the payment. thanks! 

https://github.com/Expensify/App/issues/27175#issuecomment-1738232421

**Comment by rakshitjain13** [comment] 2023-10-13 19:02
@maddylewis Already applied to the Upwork job with my Upwork ID: https://www.upwork.com/freelancers/~01c427caaa5ebf3b9c

**Comment by mollfpr** [comment] 2023-10-15 17:38
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/26500

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/26500/files#r1359918071

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regressions step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Click on the green + icon button
2. Click on Request Money
3. Select Distance Tab
4. In the start point type _India_
5. In stop point type _Pakistan_
6. Verify that the whole route is showing on the map
7. 👍 or 👎

**Comment by JmillsExpensify** [comment] 2023-10-17 21:21
$1000 payment approved for @mollfpr based on BZ summary.

**Closed** 2023-10-19 13:49 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
