### ISSUE TITLE
[$4000] Android - Edit message - keyboard is dismissed after selecting an emoji @Tushu17

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9252] opened 2022-05-31 12:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action steps: 
1. Send a message in any chat in App
2. Long press the message and tap on `Edit message` 
3. Tap on the emoji picker
4. Select an emoji and observe the keyboard is dismissed

## Expected results:
The alphabetical keyboard should not be dismissed after selecting an emoji

## Actual Result:
Keyboard doesn't open up after selecting emoji.

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.69.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/171174709-69b79478-f54a-4c55-b84b-114f7ec51087.mp4

**Upwork URL:** https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Issue reported by:** @Tushu17

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650039236885699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~018e351e7d34632075
- Upwork Job ID: 1599837238530191360

**Comment by trjExpensify** [comment] 2022-06-06 11:57
👋 @kbecciv @Tushu17, it took me a second to figure this out based on the steps provided and the issue title. Do you think it's more accurately described as:

Title: _Android - Edit message - keyboard is dismissed after selecting an emoji_

Action steps: 
1. Send a message in any chat in App
2. Long press the message and tap on `Edit message` 
3. Tap on the emoji picker
4. Select an emoji and observe the keyboard is dismissed

Expected results:
The alphabetical keyboard should not be dismissed after selecting an emoji

Let me know and we can update this for clarity.

**Comment by trjExpensify** [comment] 2022-06-09 20:13
Cool, updated. Ready for engineering triage!

**Comment by trjExpensify** [comment] 2022-06-10 17:15
Isn't it always open prior when editing? 🤔

**Comment by Julesssss** [comment] 2022-06-10 18:06
Not if the user manually closes the keyboard. I do this when writing a long message so i can review the full message in a single screen. 

Though rare, I would be annoyed if I finished writing a message, closed the keyboard, added an emoji and then saw the keyboard pop up again. Especially because it's super laggy.

**Comment by Tushu17** [comment] 2022-06-10 19:50
Hey @Julesssss, The behaviour is also inconsistent. The keyboard opens after selecting the emoji at composer.

https://user-images.githubusercontent.com/89839952/173139625-60c1c741-53b7-4d55-b610-2c93d0242f41.mov

.

**Comment by Julesssss** [comment] 2022-06-13 13:12
Thanks, @Tushu17. 

@trjExpensify this is the case which I believe should be excluded: 

https://user-images.githubusercontent.com/10736861/173361430-d66f93e4-077c-417a-809e-a187e1795f88.mp4

**Comment by trjExpensify** [comment] 2022-06-13 17:05
^^ Ah right yes, but that's not in edit mode is it?

**Comment by trjExpensify** [comment] 2022-06-13 20:04
Okay cool, I see what you're saying. Let's do it. 👍

**Comment by Julesssss** [comment] 2022-06-14 13:44
Awaiting proposals

**Comment by trjExpensify** [comment] 2022-06-14 14:54
Upwork job here: https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by parasharrajat** [comment] 2022-06-14 14:55
This used to work.

**Comment by asfandyarsheikh** [comment] 2022-06-14 20:56
Saw this on upwork. Is it good design practice to open a separate bottom sheet for emojis? Why not use a custom keyboard that allows emoji input via separate tab? Something like this https://wix.github.io/react-native-ui-lib/docs/components/keyboard/KeyboardAccessoryView

**Comment by yashwant-dangi** [comment] 2022-06-15 07:24
**Proposal**

For the _EmojiPickerButton_ component, _onModalHide_ callback if we add a timeout of around 50-100 ms in the Interaction Manager then this issue can be resolved. 

https://github.com/software-mansion/react-native-screens/issues/89#issuecomment-514935753


https://user-images.githubusercontent.com/43725028/173767631-25bdc0cc-9202-47d6-b41a-81bab7fc1b3d.mp4

**Comment by Julesssss** [comment] 2022-06-20 13:35
Still awaiting proposals. @trjExpensify can you please double the job price? (I assume we double in UpWork as well as just updating the issue title?)

**Comment by trjExpensify** [comment] 2022-06-20 15:56
Yep, done! https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by trjExpensify** [comment] 2022-06-22 23:58
Not overdue, Melv. Awaiting proposals.

**Comment by Julesssss** [comment] 2022-06-27 12:54
@trjExpensify please double again

**Comment by trjExpensify** [comment] 2022-06-27 13:20
Donezo: https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by mdneyazahmad** [comment] 2022-06-28 10:21
## Proposal

There existed the same issue on composer and is fixed by a workaround with `setTimeout` by this [PR](https://github.com/Expensify/App/pull/3392).

https://github.com/Expensify/App/blob/d7dc3eea13bdb2af3e606530dc42058ca0a291ee/src/pages/home/report/ReportActionCompose.js#L334-L352

https://github.com/Expensify/App/blob/d7dc3eea13bdb2af3e606530dc42058ca0a291ee/src/pages/home/report/ReportActionCompose.js#L638-L642

---

Maybe it has been missed there. My proposal is to do the same thing on edit composer. The only reason I propose is because we already have deployed the same workaround.

https://github.com/Expensify/App/blob/d7dc3eea13bdb2af3e606530dc42058ca0a291ee/src/pages/home/report/ReportActionItemMessageEdit.js#L227-L231

**Comment by parasharrajat** [comment] 2022-06-29 17:18
Ok, I see. Although we have adopted a workaround previously, it does not mean that we should do that always. 

> Let me know whether this proposal is accepted or I think we should also find a solution to the previously deployed workaround.

Yeah, try to find the solution to the real problem of why the keyboard is not opening? Let's see some root cause analysis.

FYI @mdneyazahmad your proposal matches with https://github.com/Expensify/App/issues/9252#issuecomment-1156088875 .

**Comment by trjExpensify** [comment] 2022-07-04 11:48
Any further ideas here @mdneyazahmad?

**Comment by Julesssss** [comment] 2022-07-07 10:00
Not overdue

**Comment by trjExpensify** [comment] 2022-07-11 13:41
Doubled on upwork: https://www.upwork.com/jobs/~01f30fad98ca9b6c69

**Comment by aneequeahmad** [comment] 2022-07-17 04:04
### Proposal

**Problem:**
- Root cause of the issue is in file https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L215-L222
- Whenever  `onBlur of Composer` in `ReportActionItemMessageEdit.js` is triggered with first argument as `true` https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L221
which causes to show `compose input` https://github.com/Expensify/App/blob/4d15590c44fe8bb3f2ab50a3f8e24c0e859e1b8b/src/libs/toggleReportActionComposeView/index.js#L3-L9

**Solution:**
Setting `false` instead of `true` here `   toggleReportActionComposeView(false, VirtualKeyboard.shouldAssumeIsOpen());` fixes the issue

- _**Attached video after the fix**_

https://user-images.githubusercontent.com/36359331/179383445-05ea0698-b56b-4cf4-b357-ba7205d3c2a5.mov

**Comment by parasharrajat** [comment] 2022-07-18 03:34
What is the affect of this change @aneequeahmad?

**Comment by aneequeahmad** [comment] 2022-07-18 04:42
@parasharrajat Effect of setting the first argument to `false` in `toggleReportActionComposeView(false, VirtualKeyboard.shouldAssumeIsOpen())`

- 'true' is used to show the ComposeInput and `onBlur` as on every interaction(like clicking outside the `EditComposeInput`) `onBlur` is triggered and causing the the ComposeInput to show and even focuses ComposeInput if it has draft message. 

- We don't need to show `ComposeInput onBlur` as showing it is already handled when `cancel or save changes` button are pressed. 

Also, as you mentioned above this used to work. You're right this used to work before `18th May 2022` and these changes were added by this [PR](https://github.com/Expensify/App/pull/9060/files#:~:text=onBlur%3D%7B,%7D%7D) in this [commit](https://github.com/Expensify/App/pull/9060/commits/06386dbceb2b20b91bfa38cd44ccb6dfbb7110a2)

**Comment by trjExpensify** [comment] 2022-07-25 12:16
@parasharrajat @Julesssss are we good with this proposal, what's the next step?

**Comment by parasharrajat** [comment] 2022-07-26 15:00
I got the update on the previous changes and we do want to enable the composer on blur on the edit box. So [proposal](https://github.com/Expensify/App/issues/9252#issuecomment-1186391894) is not valid.

**Comment by aneequeahmad** [comment] 2022-07-27 04:57
@parasharrajat Oh alright i didn't know that [this](https://github.com/Expensify/App/issues/9252#:~:text=we%20do%20want%20to%20enable%20the%20composer%20to%20blur%20on%20the%20edit%20box) is a feature and we want to enable the composer to blur

Updated proposal### 

**Problem**

- We need to not run  `toggleReportActionComposeView(true, VirtualKeyboard.shouldAssumeIsOpen());` on blur as another button having action (`opening emojiPicker`) is clicked like `save and cancel`

Solution: 

- Define an `ID` in constructor after `line#76` in `EmojiPickerButton` as `this.emojiButtonID = 'emojiButton';`
https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L75-L77

- Pass ID as prop in `EmojiPickerButton` as `nativeID={this.emojiButtonID}` here

https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L229-L231

- Assign nativeID from props to `Pressable` in `EmojiPickerButton`
https://github.com/Expensify/App/blob/66a05aa4015f96f5bab59929698d517a616620d1/src/components/EmojiPicker/EmojiPickerButton.js#L27-L34

- Return from `onBlur` to prevent re-render when `emoji button` is pressed which cancels the onPress event by re-rendering. `if (_.contains([this.saveButtonID, this.cancelButtonID, this.emojiButtonID]...`
https://github.com/Expensify/App/blob/c2ecea533a3805bbe547b48d61baa8c24a1f89ef/src/pages/home/report/ReportActionItemMessageEdit.js#L216-L218

**Comment by trjExpensify** [comment] 2022-07-29 19:08
@parasharrajat thoughts on the above?

**Comment by aneequeahmad** [comment] 2022-08-01 10:03
@marcaaron This is the relevant [issue](https://github.com/Expensify/App/pull/9060#:~:text=have%20to%20a-,relevant%20issue.,-Reply...). I came to know that 
- we do want to enable the composer to blur on the edit box. Blur can be triggered via clicking on Save or Cancel buttons as well as a normal blur on the EditBox.

So i think to solve this keyboard dismiss issue on `EmojiPicker` we have to stop the method to toggle the composer (`toggleReportActionComposeView`) as it is preventing the users to take actions like we have done for `save` and `cancel` buttons. 

cc: @parasharrajat

**Comment by parasharrajat** [comment] 2022-08-01 10:05
Testing the proposal in a few hours.

**Comment by parasharrajat** [comment] 2022-08-02 09:15
How will this proposal solve the issue on Android @aneequeahmad?

**Comment by aneequeahmad** [comment] 2022-08-02 18:16
@parasharrajat when i debugged the issue pressing the `emojiPicker` button wasn't doing any action. But now it is opening the emojiPicker on latest build `1.1.87-6` so The above proposal is not valid. 

### PROPOSAL

We only need to add  `InteractionManager.runAfterInteractions(() => setTimeout(() => this.textInput.focus(), 100))` here `onModalHide`.

https://github.com/Expensify/App/blob/d6417564acf9d34bad12231dcbc228fcb5c67f98/src/pages/home/report/ReportActionItemMessageEdit.js#L218-L221

**AFTER FIX**

https://user-images.githubusercontent.com/36359331/182445232-aaa5ba38-e6c8-4c52-9f09-4b2d87aeceb3.mp4

**Comment by parasharrajat** [comment] 2022-08-02 18:18
A similar proposal exists.

**Comment by aneequeahmad** [comment] 2022-08-02 18:35
@parasharrajat Actually the next time i test again code base has changed like previously pressing the emojiPicker wasn't doing any action and now in latest build it is opening the `emojiPicker` but setTimeout was to be added as this is a known problem discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1658026341800479). 

I'll take care next time keeping in mind what you said. apologies and thanks for your valuable feedback.

**Comment by Julesssss** [comment] 2022-08-16 17:00
@trjExpensify could we please double, given that we're still seeking proposals.

**Comment by trjExpensify** [comment] 2022-08-18 12:38
👋 back from OoO, doubled [here](https://www.upwork.com/jobs/~01f30fad98ca9b6c69).

**Comment by mollfpr** [comment] 2022-08-21 13:31
### Proposal

There are couples of root cause explained by other's and the issue only happen on Android. Also, we encountered the same issue on `ReportActionCompose` and fix with adding a timeout before focusing the input and that's not acceptable in this issue.

So I try replacing `InteractionManager.runAfterInteractions` when `onModalHide` is called with `requestAnimationFrame`. Turns out this `requestAnimationFrame` is called after `InteractionManager.runAfterInteractions` and makes the keyboard appear when we hide the modal. I think it's because `requestAnimationFrame` will fire after all the frames have been flushed.

I also try the changes on `ReportActionCompose` and works as expected. So probably we can eliminate the `setTimeout` implementation on focusing input.

https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/pages/home/report/ReportActionItemMessageEdit.js#L223
```diff
-  onModalHide={() => InteractionManager.runAfterInteractions(() => this.textInput.focus())}
+  onModalHide={() => requestAnimationFrame(() => this.textInput.focus())}
```

### Result
#### Android

https://user-images.githubusercontent.com/25520267/185793028-3e3b5ec8-73d2-47c4-8e99-8eb4054209d2.mp4

#### iOS

https://user-images.githubusercontent.com/25520267/185793127-4feb627d-0555-4df0-b5de-f2b1d420d3c3.mov

#### mWeb

https://user-images.githubusercontent.com/25520267/185793319-4bacce53-07b8-4861-b7bf-badb9231ceef.mp4

**Comment by trjExpensify** [comment] 2022-08-25 15:47
Not overdue, awaiting proposals.

**Comment by Julesssss** [comment] 2022-08-29 08:52
Not overdue, we're still awaiting proposals here.

**Comment by Julesssss** [comment] 2022-09-01 08:07
Still awaiting proposals here.

**Comment by trjExpensify** [comment] 2022-09-05 13:05
Still awaiting proposals here?

**Comment by Julesssss** [comment] 2022-09-05 14:22
Yep

**Comment by Julesssss** [comment] 2022-09-05 14:35
@trjExpensify please hold on any further pay increases for the moment though.

**Comment by mallenexpensify** [comment] 2022-09-07 23:16
Per[ this internal conversation](https://expensify.slack.com/archives/C02NK2DQWUX/p1661419792053769), putting this keyboard-related issue on hold pending https://github.com/Expensify/App/issues/10273

I updated title and removed `Help Wanted`

**Comment by Julesssss** [comment] 2022-09-12 11:20
No further proposals received.

**Comment by mallenexpensify** [comment] 2022-09-12 23:49
It's on HOLD for now @Julesssss, pending https://github.com/Expensify/App/issues/10273
Not sure why this was a Daily, bumped to Weekly for now

**Comment by trjExpensify** [comment] 2022-09-21 08:42
Can we put this on `Monthly` then and mark it as `Internal` if we're scoping a solution internally?

**Comment by Julesssss** [comment] 2022-10-26 10:32
Still on hold, see [this](https://github.com/Expensify/App/issues/9252#issuecomment-1244720271) message.

**Comment by Julesssss** [comment] 2022-11-28 13:28
No change from [the last](https://github.com/Expensify/App/issues/9252#issuecomment-1291828838) update.

**Comment by trjExpensify** [comment] 2022-12-01 22:48
👋 Isn't #10273 largely complete now, why is this still held? Could it be even fixed on Android, perhaps?

CC: @JmillsExpensify, I don't think this one is on your radar as the BZ on the KeyboardAvoidingView initiative.

**Comment by Julesssss** [comment] 2022-12-02 15:52
Given that the Keyboard changes now seem unlikely to resolve this, let's open it up for solutions again

**Comment by trjExpensify** [comment] 2022-12-02 20:37
Yeah, I agree with that. 👍

**Comment by JmillsExpensify** [comment] 2022-12-02 20:49
Thanks @trjExpensify Feel free to keep it, though I'll subscribe and participate.

**Comment by trjExpensify** [comment] 2022-12-05 18:47
Cool, thanks for confirming. Added the `External` label afresh!

**Comment by Tushu17** [comment] 2022-12-05 19:43
### proposal 
We can create a function to use `setTimeOut` in `ReportActionItemMessageEdit` file.

```
focus(shouldelay = false) {
        InteractionManager.runAfterInteractions(() => {
            if (!this.textInput) {
                return;
            }

            if (!shouldelay) {
                this.textInput.focus();
            } else {
                setTimeout(() => this.textInput.focus(), 100);
            }
        });
    }
```
we can pass that function to `onModalHide` prop of `EmojiPickerButton` as `true`.
https://github.com/Expensify/App/blob/98354545cc89b75a53f07cb1d694f7ab78ffbb40/src/pages/home/report/ReportActionItemMessageEdit.js#L252
`onModalHide={() => this.focus(true)}`.

**Comment by parasharrajat** [comment] 2022-12-05 20:00
@Julesssss Are we expecting a setTimeout-based solution as a fix to this issue? 

If not, https://github.com/Expensify/App/issues/9252#issuecomment-1223036462. 

@Tushu17 being an experienced contributor, we expect our process to be followed. And the process says that a proposal should not match existing ones and contributors should go over the whole issue discussion before proposing a solution. As the proposal matches existing ones, it is rejected.

**Comment by Julesssss** [comment] 2022-12-06 10:00
> Are we expecting a setTimeout-based solution as a fix to this issue?

Only if it can't be avoided.

**Comment by devpenzil** [comment] 2022-12-07 07:27
jh

**Comment by trjExpensify** [comment] 2022-12-07 17:34
Thread we're discussing next steps on this one is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670271699383879) for the breadcrumbs!

**Comment by JmillsExpensify** [comment] 2022-12-07 21:10
Floated with Margelo so removed the `External` and `Help Wanted` labels for now.

**Comment by fedirjh** [comment] 2022-12-07 22:28
@parasharrajat this is a known issue from RN from a long time https://github.com/facebook/react-native/issues/19366 , it was mentioned in their docs as well [Known issues](https://reactnative.dev/docs/textinput#isfocused)

This may explain the mystery :
>We can see then that a ShadowNode exists with a view, and a parent shadow node, but the view doesn't have a parent. This means for the <View> we try to focus in React has had a corresponding native UIElement created, but the element hasn't been connected to the app's visual tree.
>
> So we cannot focus the component, because the UIElement hasn't been attached to the window's view tree yet.

This thread https://github.com/microsoft/react-native-windows/issues/9292 can answer the mystery behind this issue , and it provide a solution https://github.com/microsoft/react-native-windows/issues/9292#issuecomment-1038218769

> I think the queue-based solution is a good one. If a focus request comes in, on something not yet connected, we buffer subsequent UIManager focus/blur requests until the next is available. That would preserve app-side focus state correctly, as well.

@Julesssss  it Looks like setTimeout-based solution can't be avoided

**Comment by hannojg** [comment] 2022-12-09 10:47
I can imagine that my PR https://github.com/Expensify/App/pull/11684 fixes this issue. In my testing the keyboard always reopens after selecting an emoji. Maybe someone can take the time to try to reproduce the issue on the branch? 😊

**Comment by Julesssss** [comment] 2022-12-09 11:34
Cool, thanks all. We'll hold this one briefly until the [linked PR](https://github.com/Expensify/App/pull/11684) is merged. We also have the option of the setTimeout solution as a workaround to revisit if that doesn't work.

**Comment by trjExpensify** [comment] 2022-12-09 11:46
Well, that would be marvellous! Fortuitously @parasharrajat, you're the C+ on it as well! 🎉 

@Julesssss I'm updating to include the hold reason in the title, let's always remember to do that for ease of following.

**Comment by trjExpensify** [comment] 2022-12-19 17:21
Still on hold for that PR. @parasharrajat are you back on that to test this week?

**Comment by JmillsExpensify** [comment] 2022-12-23 17:09
@parasharrajat Are you still blocked from testing?

**Comment by trjExpensify** [comment] 2023-01-03 15:14
Latest from the linked PR this is held on is that it will be tested today.

**Comment by trjExpensify** [comment] 2023-01-12 16:28
PR this is on hold for is [still in review](https://github.com/Expensify/App/pull/11684).

**Comment by trjExpensify** [comment] 2023-01-26 10:27
No change, Melv.

**Comment by trjExpensify** [comment] 2023-02-07 00:55
Still in review. Awaiting a merge to main to re-test!

**Comment by trjExpensify** [comment] 2023-02-15 21:23
Still held!

**Comment by trjExpensify** [comment] 2023-02-27 23:23
No movement on the PR we're held on [here](https://github.com/Expensify/App/pull/11684#issuecomment-1443726606).

**Comment by Julesssss** [comment] 2023-03-09 11:14
No change. We're still held

**Comment by trjExpensify** [comment] 2023-03-20 18:25
No change.

**Comment by trjExpensify** [comment] 2023-06-22 22:48
@Julesssss @parasharrajat the PR linked to has been closed, so what's the revised plan here?

**Comment by Julesssss** [comment] 2023-06-26 08:56
Here's the issue we're holding on: https://github.com/Expensify/App/issues/18444

**Comment by Julesssss** [comment] 2023-06-26 10:03
> Does the scope of this issue also include this? Just wanted to confirm this.

Yeah, I think so.

**Comment by trjExpensify** [comment] 2023-07-05 22:19
Still in a holding pattern, though looks like we're getting close!

**Comment by trjExpensify** [comment] 2023-07-17 11:42
Sounds good!

**Comment by Julesssss** [comment] 2023-07-17 12:32
Still holding on the fork death

**Comment by Julesssss** [comment] 2023-07-24 09:37
Gonna drop to weekly while it's held

**Comment by trjExpensify** [comment] 2023-08-02 16:37
No change.

**Comment by trjExpensify** [comment] 2023-08-11 16:55
Samesies!

**Comment by Julesssss** [comment] 2023-08-14 14:29
Getting closer [here](https://github.com/Expensify/App/issues/13922), but still held

**Comment by trjExpensify** [comment] 2023-08-23 11:33
PR is getting close!

**Comment by trjExpensify** [comment] 2023-09-04 09:29
👋 can someone summarise the next steps here and what we're doing about that now? Thanks!

**Comment by trjExpensify** [comment] 2023-09-13 12:17
@parasharrajat where you at on the continuation?

**Comment by trjExpensify** [comment] 2023-09-13 15:21
Done!

**Comment by Julesssss** [comment] 2023-09-26 05:18
Oh god, yeah we definitely shouldn't auto-focus the emoji search. It slows down the interaction time and reduces the available space by showing the soft keyboard.

**Comment by trjExpensify** [comment] 2023-09-26 06:45
I think the emoji search is expected to be focused, as it is on web/desktop. If we want to deviate from that, I suggest that's a new issue and a discussion in Slack. 

As for this issue on the keyboard being dismissed after selecting an emoji, it seems like we're resolved here. Is that correct?

**Comment by Julesssss** [comment] 2023-09-26 06:49
If it's expected on web/desktop (which I agree with), then this is a good example of a place in which all platforms should NOT align. 

We currently do this when opening a chat because automatically showing the soft keyboard on mobile is slow and annoying as it covers ~40% of the vertical page height. We shouldn't do this for emoji's either.

**Comment by Julesssss** [comment] 2023-09-26 06:52
But I'm happy to raise that elsewhere. And yes, the original issue here is now resolved 🎉

**Comment by trjExpensify** [comment] 2023-09-26 06:54
Yeah, I think that's just out of scope on this issue and needs to be taken some place else. 

So here, we just need to pay @Tushu17 $250 for the OG bug report.

**Comment by trjExpensify** [comment] 2023-09-26 06:56
@Julesssss a good place to start: https://github.com/Expensify/App/issues/27047

**Comment by Julesssss** [comment] 2023-09-26 07:24
> @Julesssss a good place to start: #27047

Thanks, I'm handling the revert [here](https://github.com/Expensify/App/issues/28228).

**Comment by Julesssss** [comment] 2023-09-26 08:57
Oh of course. Good spot!

**Comment by Tushu17** [comment] 2023-09-27 06:02
> So here, we just need to pay @Tushu17 $250 for the OG bug report.

Thank you @trjExpensify, offer accepted.

**Comment by trjExpensify** [comment] 2023-09-27 06:12
Perfect, paid!

**Comment by trjExpensify** [comment] 2023-09-28 03:16
So what are the next steps and who's doing those?

**Comment by Julesssss** [comment] 2023-09-28 03:31
We're back to seeking proposals. [Latest comment](https://github.com/Expensify/App/issues/9252#issuecomment-1724214952)

**Comment by trjExpensify** [comment] 2023-10-03 13:27
This issue is a bit of a spider web, IMO. Should we open a new issue with whatever relevant summary on where we are at, what we don't want to entertain, and then we'll add `help wanted` and `external` to that to seek proposals a fresh. At this point, I'm concerned nobody is going to catch up on 300+ comments and a bunch of linked issues to suggest a proposal here.

**Comment by trjExpensify** [comment] 2023-10-03 14:43
Yes, we keep the assignees and bounty the same but the issue is summarised with what we will accept/not accept in the expected results and any relevant TL;DR of the history that we landed on there.

**Comment by getusha** [comment] 2023-10-03 14:53
> Yes, we keep the assignees and bounty the same but the issue is summarised with what we will accept/not accept in the expected results and any relevant TL;DR of the history that we landed on there.

I started investigating this issue and to read and understand what's the ideal proposal and know what kind of proposals posted takes a lot of time this will be very helpful.

**Comment by trjExpensify** [comment] 2023-10-06 00:16
So @parasharrajat is that something you will summarise for where we're at this far?

**Closed** 2023-10-06 15:24 UTC
Labels: Engineering, Weekly, Improvement, Bug
