### ISSUE TITLE
[$325] Android - Profile - Add contact method flow resumes at magic code page after killing app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48498] opened 2024-09-03 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to Account settings
3. Go to Profile > Contact methods
4. Tap New contact method
5. Enter email > Next
6. On magic code page, kill the app
7. Relaunch the app
8. Go to Account settings
9. Go to Profile > Contact methods
10. Tap New contact method

## Expected Result:
Add contact method flow will restart. App will open new contact method input page

## Actual Result:
Add contact method flow resumes at magic code page instead of new contact method input page after killing app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1e35f089-7307-4c4a-8db3-f097d7ef743a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a6ead314da0c17b</li>
        <li>Upwork Job ID: 1831082861275959824</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by roryabraham** [comment] 2024-09-03 20:33
NAB, demoting.

**Comment by roryabraham** [comment] 2024-09-03 21:32
For posterity, this was likely introduced in [this checklist](https://github.com/Expensify/App/issues/48438).

**Comment by nkdengineer** [comment] 2024-09-04 07:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add contact method flow resumes at magic code page instead of new contact method input page after killing app

### What is the root cause of that problem?
When we kill the app the cleanup function [here](https://github.com/Expensify/App/blob/ec8a5d974d18dea142da2c27e4a8a27ce0a70794/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L64) isn't triggered then if we requested the magic code before killing the App, this `useEffect` will redirect the user to the magic code page


https://github.com/Expensify/App/blob/ec8a5d974d18dea142da2c27e4a8a27ce0a70794/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L56-L62

### What changes do you think we should make in order to solve the problem?

- If it's expected that we want to continue the current step after we kill the app or close the validate code page without clicking on back button we can remove this cleanup function

https://github.com/Expensify/App/blob/ec8a5d974d18dea142da2c27e4a8a27ce0a70794/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L64

- Otherwise, I think we can remove this `useEffect` because I don't see any case that we need this logic.

OPTIONAL: we can also change the cleanup function [here](https://github.com/Expensify/App/blob/ec8a5d974d18dea142da2c27e4a8a27ce0a70794/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L64) to clear the pending contact method whenever the `NewContactMethodPage` is mounted. It also can be unnecessary because when we submit this form the pending contact method data is also reset

https://github.com/Expensify/App/blob/ec8a5d974d18dea142da2c27e4a8a27ce0a70794/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L56-L62
### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2024-09-04 18:08
Agree with @parasharrajat's analysis of the expected behavior

**Comment by bfitzexpensify** [comment] 2024-09-06 14:30
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: working through proposals

**Comment by CortneyOfstad** [comment] 2024-09-18 18:30
@Krishna2323 — bump @parasharrajat's comment above — thanks!

**Comment by rushatgabhane** [comment] 2024-09-20 02:11
regression @hungvu193  / @getusha

**Comment by hungvu193** [comment] 2024-09-20 02:16
Thanks for the ping @rushatgabhane.
I remembered I had already removed the usage of `ValidateActionContactPage` in this PR (https://github.com/Expensify/App/pull/48628).
We switched to use `ValdiateActionModal` and using state to handle it so I think this issue is fixed.

**Comment by hungvu193** [comment] 2024-09-20 02:27
I can confirm it's fixed. We can close this issue:

https://github.com/user-attachments/assets/0723e41d-87ea-411b-89e0-620cc5cc8ff7

**Closed** 2024-09-20 17:12 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
