### ISSUE TITLE
[HOLD for payment 2024-05-09] Mark Down - Mark down doesn't work for task description after saving

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41422] opened 2024-05-01 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Assign task
3. Input a title
4. Input a description with a mark down text (e.g "> test")
5. Create the task by assigning to someone and sharing it somwhere
6. Open the task report page

## Expected Result:
The description renders the markdown

## Actual Result:
The description field doesn't render the appropriate markdown text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c8ba54c8-5ef1-4468-99ba-fd68aa4d9500

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-01 14:41
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-01 14:41
We think that this bug might be related to #vip-vsp

**Comment by Nodebrute** [comment] 2024-05-01 14:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mark Down - Mark down doesn't work for task description after saving
### What is the root cause of that problem?
It's because we are escaping it. We should only escape urls. but due to `false` we are escaping normal description too.
https://github.com/Expensify/App/blob/33a496eef85fc2b5ca733e0d88cdcfe16a8752dd/src/components/ReportActionItem/TaskView.tsx#L154
### What changes do you think we should make in order to solve the problem?

Instead of false we should change it to true
```
 shouldEscapeText={Url.hasURL(report.description ?? '') ? undefined : true}
```
https://github.com/Expensify/App/blob/33a496eef85fc2b5ca733e0d88cdcfe16a8752dd/src/components/ReportActionItem/TaskView.tsx#L154
### What alternative solutions did you explore? (Optional)

**Comment by francoisl** [comment] 2024-05-01 17:32
Thanks for the proposals. Please make sure to link to the offending PR that caused the regression when you can identify it, in this case it looks like it was https://github.com/Expensify/App/pull/41096.

Going to test the proposals shortly.

**Comment by francoisl** [comment] 2024-05-01 18:27
Thanks guys, I'm going to handle this internally because it requires changing some additional values for the onboarding tasks.

**Comment by francoisl** [comment] 2024-05-08 21:53
This was all handled internally, closing.

**Closed by francoisl** 2024-05-08 21:53 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
