### ISSUE TITLE
Auto grow is incorrect in multiline text inputs

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22205] opened 2023-07-04 17:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Go to security
3. Go to close account
4. In 'Enter message', press a and hit `enter` key, then enter b and hit `enter`key
5. Observe that the input does not grow after hit `enter`, but only after pressing b.
## Expected Result: 
Input should grow after pressing `enter` key.
## Actual Result:
 Input does not grow after `enter` key.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4b2d69bb-863d-4fec-9dc8-582b576a6794

https://github.com/Expensify/App/assets/43996225/6941f266-b6af-4914-a28a-ddfa75e01f44

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samh-nl
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688401818961649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by manjesh-yadav** [comment] 2023-07-04 18:32
Dupe of https://github.com/Expensify/App/issues/21271

**Closed** 2023-07-05 21:16 UTC
Labels: Daily, Bug
