### ISSUE TITLE
[HOLD for payment 2023-09-29] [$1000] Time of User A doesn't appear for User B in IOU or Task room.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24228] opened 2023-08-07 18:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open 2 Acounts User A and User B
2. Login as User A click The FAB and Request money from User B.
3. Click in the IOU message to open it in a thread
4. Go to User B and Click on the IOU message to open it in a thread
5. To make sure, start sending messages between the two users ( Optional )
## Expected Result:
User B should be able to see the time of User A ( who request the money ) inside the IOU  room.
## Actual Result:
User B Can't see the time of User A ( Who request the money ) inside IOU room
NOTICE: this happens also in the task room
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 01-08-23 18_50_26.webm](https://github.com/Expensify/App/assets/43996225/34a5f01b-aa92-42dd-8b51-30c52b37a9df)

https://github.com/Expensify/App/assets/43996225/57a4f4e3-afb6-423c-8c99-71e9c24bcff9

![Screenshot from 2023-08-01 18-51-46](https://github.com/Expensify/App/assets/43996225/93537e9f-f3dd-4e23-bf1f-01bdf4598c2a)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690906316722259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1a50a5c3e2c06ad</li>
        <li>Upwork Job ID: 1688633263346528256</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>huzaifa-99 | Contributor | 26515322</li>
<li>Ahmed-Abdella | Reporter | 26515324</li>
</ul></li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-08-07 19:26
I wasn't able to get the same effect in the Task room, but I was in the Request 

<img width="1302" alt="image" src="https://github.com/Expensify/App/assets/5802477/575d9e98-b808-425b-9bff-2c1f0b843303">

**Comment by pradeepmdk** [comment] 2023-08-07 21:00
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
The time of User A doesn't appear for User B in IOU or Task room
### What is the root cause of that problem?
in the command=OpenReport API getting the wrong data 
![Screenshot 2023-08-08 at 2 28 43 AM](https://github.com/Expensify/App/assets/16595846/51ee7851-2473-4112-be5f-896b83bebbb5)

### What changes do you think we should make in order to solve the problem?
need to fix on the backend side

**Comment by ArekChr** [comment] 2023-08-08 10:14
This issue is duplicated https://github.com/Expensify/App/issues/23836

**Comment by conorpendergrast** [comment] 2023-08-08 10:40
Oh nice, great catch. Thanks @ArekChr. Closing as a duplicate of https://github.com/Expensify/App/issues/23836

**Comment by Ahmed-Abdella** [comment] 2023-08-08 10:40
@ArekChr I don't think s, they are two different cases. This issue is that the Sender locat time doesn't appear for the Recipient. The other issue (https://github.com/Expensify/App/issues/23836) is the other way around, the Recipient Local Time does not appear for the sender. 
And there is ahuge difference between the two cases, as in the other issue the Recipient Local Time does  appear for the sender after refresh the page, not like this issue, it never appear.

[Screencast from 08-08-23 13:29:54.webm](https://github.com/Expensify/App/assets/77763699/2a3cb493-9cb4-438f-8cfc-9f8f5ca32220)

Compare this video with the first one above you can see the difference.

**Comment by mountiny** [comment] 2023-08-24 00:18
@huzaifa-99 I think the problem with these is that in any chat except of DM there can be more participants than just 2. Maybe just IOU could be two. In Task report, you can invite people in threads you can invite people, workspace and expenses can have bunch of people too.

**Comment by mountiny** [comment] 2023-08-24 13:46
@conorpendergrast i think this issue is not exactly duplicate of the other one (that is linked to the problem with known and unknown users - secure login)

@ArekChr do you agree? I think we should reopen this

**Comment by ArekChr** [comment] 2023-08-24 16:08
@mountiny I looked it up, and I think so too. Let's reopen this issue.

**Comment by ArekChr** [comment] 2023-08-25 11:46
> I am not sure if we want to show the local time in case of workspace threads, if we don't we can add

Fixing this issue shouldn't change behaviour of other features.

**Comment by ArekChr** [comment] 2023-08-25 12:24
@huzaifa-99 Why using `isRequestMoney`? Are we going to include expenses reports as well not only IOU?

**Comment by ArekChr** [comment] 2023-08-28 10:15
@huzaifa-99, thanks for clarifications, I'm still unsure about the existing behavior for workspace threads and not showing local time there. I'm not sure if this should be a separate issue, @mountiny thoughts? 

As for including expense reports alongside IOU and tasks under `isMoneyRequestReport`, I agree, that it also makes sense to include expense reports.

**Comment by conorpendergrast** [comment] 2023-08-30 10:54
Looks like we're still aligning on a proposal here, correct? Anything I can do to help?

**Comment by ArekChr** [comment] 2023-08-30 11:39
@conorpendergrast Yes, we are considering whether this issue needs to be fixed in workspace threads.
Overall I think so, basically, the fix provided in the @huzaifa-99 proposal looks good to me.

**Comment by ArekChr** [comment] 2023-09-04 07:58
@huzaifa-99 Let's go the [proposal](https://github.com/Expensify/App/issues/24228#issuecomment-1679272809) and what we discussed currently.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by Ahmed-Abdella** [comment] 2023-09-05 21:48
sorry, @conorpendergrast but this issue was reported long time before the rate change (30 Aug), shouldn't it be at 250$ rate?

**Comment by conorpendergrast** [comment] 2023-09-11 12:25
@johncschuster I'm on parental leave; re-assigning! The PR is in the works here

**Comment by ArekChr** [comment] 2023-10-02 13:32
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by johncschuster** [comment] 2023-10-05 20:55
Thanks for the bump, @huzaifa-99! It looks like the offer is still pending in Upwork. Can you accept that?

**Comment by johncschuster** [comment] 2023-10-05 20:56
I've issued payment for @Ahmed-Abdella. I'll get you as soon as you ping me, @huzaifa-99!

**Comment by johncschuster** [comment] 2023-10-12 21:00
Thanks for the bump, @huzaifa-99! I've just issued payment

**Closed** 2023-10-12 21:00 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
