### ISSUE TITLE
[HOLD for payment 2024-01-18] [$500] Expense-No error message when submitting ongoing Scan request and report can be submitted many times

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32374] opened 2023-12-01 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace
1. Log in to ND as the employee
2. Go to the workspace chat > + > Request money
3. Create a manual request and a Scan request
4. Click on the expense preview
5. Click Submit
Note that the submit button reappears after submitting the report and there is no error message, only red dot

## Expected Result:
If the report cannot be submitted because of the ongoing scanning request, error message will show up

## Actual Result:
No error message shows up when submitting report that has ongoing scanning request. Submit button reappears and user can submit it multiple times. Only red dot shows up in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/afa0f654-c8d3-4a6a-88e3-66ed1ff900e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fcd78a13230fc56</li>
        <li>Upwork Job ID: 1730695574080872448</li>
        <li>Last Price Increase: 2023-12-22</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 28070331</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-02 06:26
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Expense-No error message when submitting ongoing Scan request and report can be submitted many times

### What is the root cause of that problem?

This is happening due to the use of incorrect `reportActionID` in the failure Onyx data in the `SubmitReport` API call. 
The offending lines 
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/libs/actions/IOU.js#L2682-L2689

### What changes do you think we should make in order to solve the problem?

We should use `optimisticSubmittedReportAction.reportActionID` instead of `expenseReport.reportActionID`.

#### Result

https://github.com/Expensify/App/assets/58412969/f348bf81-cc95-49b6-b519-39beb1e76b60

### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2023-12-06 04:36
@rushatgabhane Thoughts on the proposals so far?

**Comment by JmillsExpensify** [comment] 2023-12-13 05:47
@rushatgabhane thoughts on these proposals?

**Comment by rushatgabhane** [comment] 2023-12-18 13:47
reviewing

**Comment by shubham1206agra** [comment] 2023-12-18 15:54
> > We should use optimisticSubmittedReportAction.reportActionID instead of expenseReport.reportActionID
> 
> @shubham1206agra i don't agree with this. If success data is for `expenseReport.reportID`, then why should we set failure data for the optmistic report Id?

@rushatgabhane We set success data for `optimisticSubmittedReportAction.reportActionID`, which is the message submitter see when submitting the expense report. So failure should be set for the same.

cc @marcochavezf for more context here

**Comment by rushatgabhane** [comment] 2023-12-18 22:20
> We set success data for optimisticSubmittedReportAction.reportActionID, which is the message submitter see when submitting the expense report. So failure should be set for the same

@shubham1206agra oh yeah, you're right!

**Comment by rushatgabhane** [comment] 2023-12-18 23:07
confirming here https://github.com/Expensify/App/pull/28947#discussion_r1430711420

**Comment by rushatgabhane** [comment] 2023-12-26 17:12
just got a confirmation!
https://github.com/Expensify/App/pull/28947#discussion_r1436539818

**Comment by rushatgabhane** [comment] 2023-12-26 17:13
i like @shubham1206agra's proposal https://github.com/Expensify/App/issues/32374#issuecomment-1837058926

🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2024-01-17 04:44
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28947

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28947#discussion_r1430711420

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No. This bug was caused during first implementation where we sent the wrong reportID in failureData. This bug won't happen again.

4. Determine if we should create a regression test for this bug. No.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - No

**Comment by rushatgabhane** [comment] 2024-01-17 04:45
@JmillsExpensify please attach a payment summary when you can. Thank you 🙇

**Comment by cead22** [comment] 2024-01-23 19:44
Not over due, just pending payment

**Comment by shubham1206agra** [comment] 2024-01-30 04:25
@cead22 Can you please resend offer? Original offer expired :(

**Comment by JmillsExpensify** [comment] 2024-01-30 16:49
Payment summary:

 - Issue reporter: QA
 - Contributor: @shubham1206agra $500 
 - @rushatgabhane $500

**Comment by JmillsExpensify** [comment] 2024-01-30 16:50
$500 payment approved for @rushatgabhane based on summary above.

**Comment by JmillsExpensify** [comment] 2024-01-30 16:51
@shubham1206agra offer sent

**Comment by shubham1206agra** [comment] 2024-01-31 03:00
Offer accepted

**Comment by JmillsExpensify** [comment] 2024-01-31 03:14
All contracts paid, so closing this issue!

**Closed by JmillsExpensify** 2024-01-31 03:14 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
