### ISSUE TITLE
[HOLD App#35519] [$500] [LOW] Android - App crashes after personal info page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36453] opened 2024-02-14 01:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n (new flow)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open app
2. Select a workspace
3. Go to settings
4. Tap Bank account
5. Select "Connect manually"
6. Fill in random data for the personal info screens
7. Tap confirm on the personal info confirmation page
## Expected Result:
Onfido loads

## Actual Result:
App crashes

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/52fb12a9-c40e-40f5-ac74-bc088b38a3ba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d63458c77f02719</li>
        <li>Upwork Job ID: 1757570563966742528</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-14 01:07
Cannot reproduce, I believe this requires a whitelisted account that skips step 3 ( biometrics ) for bank accounts.

**Comment by marcaaron** [comment] 2024-02-14 01:11
cc @barttom

**Comment by marcaaron** [comment] 2024-02-14 01:12
related to https://github.com/Expensify/App/pull/34498

**Comment by mountiny** [comment] 2024-02-14 01:21
@akinwale @shubham1206agra @MrMuzyk This one seems to crash when loading onfido

**Comment by mountiny** [comment] 2024-02-14 01:24
Here is the crash stacktrace most likely

[com.expensify.chat_issue_6c40888feb819ea06cae63314f6df823_crash_session_65CC0D63007E00017B3074590039D7E9_DNE_0_v2_stacktrace.txt](https://github.com/Expensify/App/files/14274217/com.expensify.chat_issue_6c40888feb819ea06cae63314f6df823_crash_session_65CC0D63007E00017B3074590039D7E9_DNE_0_v2_stacktrace.txt)

**Comment by jeremy-croff** [comment] 2024-02-14 01:50
Took me a good while to build android. But unable to reproduce - is this because of the whitelisted account used again?
<img width="379" alt="Screenshot 2024-02-13 at 7 48 00 PM" src="https://github.com/Expensify/App/assets/157416545/6db061c0-dda1-4399-ad21-506a658f70a4">

**Comment by akinwale** [comment] 2024-02-14 05:53
This may be device-specific as I am unable to reproduce this.

**Comment by MrMuzyk** [comment] 2024-02-14 09:56
Im also unable to reproduce that. Tested on Pixel 6 emulator
https://github.com/Expensify/App/assets/23487612/d410ea7d-5436-4ebe-864e-53c6bbc1d0f9

**Comment by mountiny** [comment] 2024-02-14 11:56
Thanks removing the blocker label as this seems very narrow case. Will keep monitoring for more cases though

**Comment by garrettmknight** [comment] 2024-02-14 19:17
@sakluger just reassigning in case this needs help while I'm OOO this week - will be back 2/21 to pick it back up

**Comment by sakluger** [comment] 2024-02-23 16:45
@vitHoracek @akinwale do you agree that this is a dupe of https://github.com/Expensify/App/issues/35519? Should we hold this issue for that one?

**Comment by sakluger** [comment] 2024-02-23 16:46
Still on hold for https://github.com/Expensify/App/issues/35519.

**Comment by garrettmknight** [comment] 2024-03-05 20:09
Good call @mkhutornyi - closing.

**Closed by garrettmknight** 2024-03-05 20:09 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug
