### ISSUE TITLE
[Regression test steps needed][$1000] BUG: Add attachment send button is too large

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#13193] opened 2022-11-30 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in with any account
2. Open a chat and click the plus button to add an attachment, select a file to upload

## Expected Result:
The send button is centered and has a normal width

## Actual Result:
The send button stretches across the whole modal

## Workaround:
Ignore the visual oddity

## Platform:

All? Needs testing.

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.34-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
![image](https://user-images.githubusercontent.com/26260477/204867091-124a592f-0de5-4b3d-a991-84ad60c2c4a3.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669828932546429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~016b240866a2f9a693
- Upwork Job ID: 1598035611785265152

**Comment by allroundexperts** [comment] 2022-11-30 18:26
What is the required width @neil-marcellini?

**Comment by neil-marcellini** [comment] 2022-11-30 18:27
cc @Expensify/design

**Comment by Pujan92** [comment] 2022-11-30 18:42
**Proposal**

To make it normal at center postion we can update the style for the button.

https://github.com/Expensify/App/blob/2881f18300a1b31a2047f1f61f2cdf93d2f7b79e/src/styles/styles.js#L472-L474

`alignItems: 'center',`

<img width="1440" alt="Screenshot 2022-12-01 at 12 12 01 AM" src="https://user-images.githubusercontent.com/14358475/204881721-8ed5a7ab-aba9-4570-9cd0-d3ce96d53341.png">

**Comment by shawnborton** [comment] 2022-11-30 18:52
As for the button, we want it to be full width on mobile but for desktop, maybe we just give it a larger min-width (like 300?) and center it like it's shown above? 

Looks like we need to update the background color behind the PDF as well.

**Comment by Puneet-here** [comment] 2022-11-30 19:04
### Proposal

Add `attachmentButtonBigScreen` to styles.js
```js
attachmentButtonBigScreen:{
        maxWidth: 300,
        alignSelf: 'center'
    }
```
Pass `{[styles.buttonConfirm, this.props.isSmallScreenWidth ? {} : styles.attachmentButtonBigScreen]}` at style
https://github.com/Expensify/App/blob/1f718323105f9ef6d2b26b5e9f78cd1bb38bde68/src/components/AttachmentModal.js#L281

**Comment by akshayasalvi** [comment] 2022-11-30 19:06
**Proposal**

In the `styles.js` update the `buttonConfirm` with the following styles:

```
  buttonConfirm: {
    alignSelf: `center`,
    minWidth: 300
  }



```

**Web Version**
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/57435789/204885322-b98ebb1c-a5c6-450f-bb49-ad8d8e51bda3.png">

**iOS version**
<img width="368" alt="image" src="https://user-images.githubusercontent.com/57435789/204886384-e5ad78e8-fc06-4752-8e42-1a721b794ab2.png">

**Comment by shawnborton** [comment] 2022-11-30 19:07
For mobile/small devices, we should have the button extend to full width. Only desktop/wide devices should get the min-width.

**Comment by Puneet-here** [comment] 2022-11-30 19:17
@shawnborton, can you please check my [proposal](https://github.com/Expensify/App/issues/13193#issuecomment-1332607755)

**Comment by shawnborton** [comment] 2022-11-30 19:19
Yup that works for me, but let's have our contributor team file and review first.

**Comment by Pujan92** [comment] 2022-11-30 19:19
```
buttonConfirm: {
        padding: 20,
        width: '100%',
        maxWidth: 360,
        alignSelf: 'center',
    },
```

[b8fa075e-11e9-4b2b-897d-6c645ff678d0.webm](https://user-images.githubusercontent.com/14358475/204888911-2984c668-6e22-4ae3-8fd9-33cfce178d4e.webm)

**Comment by grgia** [comment] 2022-11-30 19:25
Adding the external label now

**Comment by thesahindia** [comment] 2022-11-30 19:33
@Puneet-here's [proposal](https://github.com/Expensify/App/issues/13193#issuecomment-1332607755) looks good to me. It handles small screen devices too.

🎀👀🎀 C+ reviewed

cc: @grgia

**Comment by Pujan92** [comment] 2022-11-30 19:35
@thesahindia do you think [this](https://github.com/Expensify/App/issues/13193#issuecomment-1332623428) is more suitable for this change where a same class is handling both devices?

**Comment by allroundexperts** [comment] 2022-11-30 19:36
### Proposal

@thesahindia @shawnborton I agree with @Puneet-here proposal. He however missed the incorrect background colour in the pdf preview screen. This can be fixed by:
```diff
diff --git a/src/components/AttachmentModal.js b/src/components/AttachmentModal.js
index 7895b119b..f1831bc09 100755
--- a/src/components/AttachmentModal.js
+++ b/src/components/AttachmentModal.js
@@ -275,10 +275,10 @@ class AttachmentModal extends PureComponent {
 
                     {/* If we have an onConfirm method show a confirmation button */}
                     {this.props.onConfirm && (
-                        <Animated.View style={StyleUtils.fade(this.state.confirmButtonFadeAnimation)}>
+                        <Animated.View style={[StyleUtils.fade(this.state.confirmButtonFadeAnimation), styles.buttonConfirmContainer]}>
                             <Button
                                 success
-                                style={[styles.buttonConfirm]}
+                                style={[styles.buttonConfirm, this.props.isSmallScreenWidth ? undefined : styles.attachmentButtonBigScreen]}
                                 textStyles={[styles.buttonConfirmText]}
                                 text={this.props.translate('common.send')}
                                 onPress={this.submitAndClose}
diff --git a/src/styles/styles.js b/src/styles/styles.js
index adedd13af..87282326e 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -469,6 +469,11 @@ const styles = {
         marginRight: 22,
     },
 
+    attachmentButtonBigScreen: {
+        alignSelf: 'center',
+        minWidth: 300,
+    },
+
     buttonConfirm: {
         margin: 20,
     },
@@ -1822,7 +1827,7 @@ const styles = {
 
     imageModalPDF: {
         flex: 1,
-        backgroundColor: themeColors.modalBackground,
+        backgroundColor: themeColors.shadow,
     },
 
     PDFView: {
@@ -1830,7 +1835,7 @@ const styles = {
         // It's being used on Web/Desktop only to vertically center short PDFs,
         // while preventing the overflow of the top of long PDF files.
         display: 'grid',
-        backgroundColor: themeColors.modalBackground,
+        backgroundColor: themeColors.modalBackdrop,
         width: '100%',
         height: '100%',
         justifyContent: 'center',

```

## Result

<img width="1440" alt="Screenshot 2022-12-01 at 12 36 37 AM" src="https://user-images.githubusercontent.com/30054992/204892122-904a010a-2a81-4306-b8c8-e2dc88db6803.png">

**Comment by thesahindia** [comment] 2022-11-30 19:56
@allroundexperts, seems like a different issue to me.

@Pujan92, there's extra gap horizontally

**Comment by allroundexperts** [comment] 2022-11-30 19:57
@thesahindia @shawnborton mentioned this here: https://github.com/Expensify/App/issues/13193#issuecomment-1332595169

**Comment by Pujan92** [comment] 2022-11-30 20:01
> @Pujan92, there's extra gap horizontally

I am seeing only 20px padding which is the intended one I think.

**Comment by thesahindia** [comment] 2022-11-30 20:09
> Looks like we need to update the background color behind the PDF as well.

@shawnborton, is this supposed to fix in this issue?

**Comment by thesahindia** [comment] 2022-11-30 20:11
> I am seeing only 20px padding which is the intended one I think.

Can you check the side by side comparison in small screen devices.

**Comment by allroundexperts** [comment] 2022-11-30 20:12
@thesahindia @shawnborton Please let me know the link here. I'll add this proposal there.

**Comment by thesahindia** [comment] 2022-11-30 20:13
> Nope, we can make a separate issue for that.

Cool, thanks! 

> @Puneet-here's https://github.com/Expensify/App/issues/13193#issuecomment-1332607755 looks good to me. It handles small screen devices too.
> 
> 🎀👀🎀 C+ reviewed
> 

cc: @grgia

**Comment by thesahindia** [comment] 2022-11-30 20:37
@Pujan92, check the screenshots of small screen width
<details>
<summary>Your proposal </summary>
<img width="437" alt="Screenshot 2022-12-01 at 2 00 43 AM" src="https://user-images.githubusercontent.com/83179295/204901863-7fc5506a-d7e8-42e4-afb1-3a088ad7684b.png">
</details>
<details>
<summary>The selected proposal </summary>
<img width="437" alt="Screenshot 2022-12-01 at 2 00 32 AM" src="https://user-images.githubusercontent.com/83179295/204901871-2a5aa561-a9df-4260-bd17-2ed065ae4b2c.png">
</details>

Some other points -
- The button is not 300px
- Because of padding the button is clickable at 20px are on both sides. I can see QA logging this as an issue.

**Comment by Pujan92** [comment] 2022-11-30 20:44
> * Because of padding the button is clickable at 20px extra area on both sides. I can see QA logging this as an issue.

Yes, thanks for pointing this out.

**Comment by grgia** [comment] 2022-11-30 22:21
LGTM, assigning now

**Comment by slim-python** [comment] 2022-12-01 08:27
following this thread ;--;
just curios if anyone actually get the 1000$

**Comment by kevinksullivan** [comment] 2022-12-21 21:10
Sorry for the delay here. @Puneet-here @thesahindia I just hired both of you for the job. Can you let me know once you've accepted to I can pay this out?

**Comment by kevinksullivan** [comment] 2022-12-21 21:10
And can someone fill out the checklist items as well before we close this one out?

**Comment by thesahindia** [comment] 2022-12-21 21:24
Accepted, thanks!

**Comment by thesahindia** [comment] 2022-12-21 21:25
> And can someone fill out the checklist items as well before we close this one out?

It wasn't a regression ( just an improvement) so we are good here.

**Comment by mallenexpensify** [comment] 2022-12-24 01:02
Paid @thesahindia and @Puneet-here $1500, inc. the 50% bonus for expediency. 
Thanks!
I think we still need to add regression steps to TestRail, assigned myself to hopefully help with those next week.

**Comment by thesahindia** [comment] 2023-01-02 18:45
No actions are needed from me, so unassigning.

**Comment by mallenexpensify** [comment] 2023-01-03 01:38
Confirming regression test steps [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1672709862546459)

**Comment by mallenexpensify** [comment] 2023-01-03 20:49
Didn't get feedback in Slack, thinking of adding the below, will do tomorrow after leaving here for a day
Recommendation: Update to add a regression step to
[Compose box - Attachments (images)](https://expensify.testrail.io/index.php?/cases/view/1971010) as new step #4 `Verify the width of the send button doesn't extend to the far edges of the screen on desktop, web and wide devices.

[Compose box - Attachments (PDF)](https://expensify.testrail.io/index.php?/cases/view/1971194) as new step #4 `Verify the width of the send button doesn't extend to the far edges of the screen on desktop, web and wide devices.

**Comment by mallenexpensify** [comment] 2023-01-11 18:59
Regression test steps added https://github.com/Expensify/Expensify/issues/254500
@thesahindia @grgia , can you check off the other three boxes here then close this?
https://github.com/Expensify/App/issues/13193#issuecomment-1341857597

**Comment by mallenexpensify** [comment] 2023-01-12 00:06
K, closing then.  @grgia plz reopen if you disagree

**Closed by mallenexpensify** 2023-01-12 00:06 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
