### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Close account - Phone account cannot be closed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27283] opened 2023-09-12 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot with phone account 
2. Go to Settings > Security > Close account
3. Try in input phone number in any possible format to "default contact method" field
4. Click close account

## Expected Result:
Account should be closed

## Actual Result:
Error message is displayed. Account is not closed. User is blocked from closing account
User can use any number entry option to log in but to close your account there is only one suggested on this page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.68-15

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4bce31ed-d939-4fd7-8933-9b6a8860faa8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4a7e63cc4598b24</li>
        <li>Upwork Job ID: 1701734067417325568</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 26745151</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-09-12 23:01
I can reproduce this one. I even tried adding the `@expensify.sms` to see if that was the cause, and it didn't work either. 

https://github.com/Expensify/App/assets/16232057/16f4e62b-35a6-4816-8f08-391f4f6305d5

**Comment by trjExpensify** [comment] 2023-09-13 18:16
Wow, why does it need the space between `07814 266906`? I think we should remove that. I also like the idea of the clipboard icon to make this easy.

**Comment by robertKozik** [comment] 2023-09-18 10:47
Hi @hoangzinh! I appreciate your proposal as it directly addresses the root cause. Both adding the copy button and trimming whitespaces are valid options. Personally, I lean towards the latter as the close account option should not be too easy to perform. Requiring the user to type out the contact method acts as an extra confirmation step. While I'm open to further discussion on this, for now, I'm inclined towards the current solution proposed by @hoangzinh.

🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2023-10-02 12:43
Where are we at here?

**Comment by robertKozik** [comment] 2023-10-02 13:19
@trjExpensify I asked a quetion about the implementation. We are currently in review

**Comment by trjExpensify** [comment] 2023-10-02 20:24
Excellent, thanks!

**Comment by trjExpensify** [comment] 2023-10-16 18:07
Strange, not sure how this one fell off my radar to settle up last week. My bad, thanks the bump! 

I agree we don't need a regression test here because Applause caught it within their regression testing for closing accounts already. Proceeding with payments as follows: 

$500 to @hoangzinh for the fix 

No #urgency bonus to be applied as per [here](https://github.com/Expensify/App/issues/27283#issuecomment-1745033296).

**Comment by trjExpensify** [comment] 2023-10-16 18:07
Settled up, closing!

**Closed by trjExpensify** 2023-10-16 18:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
