### ISSUE TITLE
[$500] Request Money - Copied Information Does Not Update When Changes are Made in IOU or Language Settings

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26531] opened 2023-09-01 21:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money."
2. Add the desired amount and email for the money request.
3. Double-click on the requested money to open the IOU.
4. Change the amount and currency, then go back one step.
5. Right-click and select "Copy" to copy the updated information.
6. Observe that the copied information is not updated.
7. Repeat the process while changing the language settings and note that the copied information still does not update

## Expected Result:
The copied information should be updated accordingly when changes are made in IOU or language settings.

## Actual Result:
The copied information does not update when changes are made in IOU or language settings, which can lead to confusion or errors for users.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c69a59b4-c669-4be3-97d0-3b1dd02bb02d

https://github.com/Expensify/App/assets/115492554/6f7e3b85-702e-47ad-8425-f1a7d9ae4f51

**Expensify/Expensify Issue URL:**

**Issue reported by:** @TewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692945253540029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac6043b8d7252dc1</li>
        <li>Upwork Job ID: 1702481828253175808</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-09-06 21:46
I don't think this is a duplicate, so I will test soon.

**Comment by alexpensify** [comment] 2023-09-08 23:34
I've run out of time today and will test soon.

**Comment by alexpensify** [comment] 2023-09-11 22:21
Still on my testing list

**Comment by alexpensify** [comment] 2023-09-15 00:38
Waiting for proposals here.

**Comment by zukilover** [comment] 2023-09-15 01:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request Money - Copied Information Does Not Update When Changes are Made in IOU

### What is the root cause of that problem?
ContextMenuAction does not check if there are any changes in the request money report. It goes to this block directly:

https://github.com/Expensify/App/blob/cd9e86e683ed1a6167888d758c73c74346cfd529/src/pages/home/report/ContextMenu/ContextMenuActions.js#L202-L210

### What changes do you think we should make in order to solve the problem?
Check if there are any amount/currency changes in the IOU report:

```
if (ReportActionsUtils.isMoneyRequestAction(reportAction)) {
                    const parser = new ExpensiMark();
                    const requestMoneyReport = ReportUtils.getReport(originalMessage.IOUReportID)
                    const isRequestMoneyUpdated = (requestMoneyReport.total !== originalMessage.amount) ||
                        (requestMoneyReport.currency !== originalMessage.currency)
                    const modifyIOUMessage = `requested ${requestMoneyReport?.cachedTotal}`
                    Clipboard.setString(isRequestMoneyUpdated ? modifyIOUMessage : parser.htmlToText(content))
}
```

There is another problem in that when the user changes the currency, it does not update it in the IOU store.
For this, we need to correctly implement this line to the `EditRequestAmountPage`:

```
IOU.setMoneyRequestCurrency(currency)
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by DylanDylann** [comment] 2023-09-15 12:04
fix by https://github.com/Expensify/App/pull/27142

**Comment by alexpensify** [comment] 2023-09-15 15:01
Ok, with this feedback, I'm going to close it out.

**Closed by alexpensify** 2023-09-15 15:01 UTC
Labels: External, Daily, Help Wanted, Bug
