### ISSUE TITLE
Emoji appears in chat with slight delay after sending it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36437] opened 2024-02-13 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Enter an emoji.
4. Send the text with just emoji.
## Expected Result:
The emoji will appear in chat immediately after sending it.

## Actual Result:
The emoji appears in chat with slight delay after sending it.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/60854b1c-8bd1-4fbf-85bd-2707257e9efe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2024-02-13 22:47
Having trouble pinpointing which PR the regression is coming from.

At first I was thinking it could be from the new sounds feature, since it almost feels intentional to delay displaying the emoji until the sound plays for dramatic effect 😄 . But I reverted that PR locally and it did not remove the delay.

I guess I can take a stab at the `git bisect` route

**Comment by amyevans** [comment] 2024-02-13 23:05
Okay actually I took another guess before bisecting, and reverting the expensify-common version bump fixed the issue (which was part of the Live Markdown preview project).

cc @thienlnam @robertKozik, let me know if y'all plan to tackle these or if I should mark this `External`.

I'm going to demote to NAB though in the meantime!

**Comment by situchan** [comment] 2024-02-13 23:09
I think this should be deploy blocker.
In offline mode, emoji doesn't show at all


https://github.com/Expensify/App/assets/108292595/d55f0f07-af65-4ce9-aff7-9a99aad70b23

**Comment by robertKozik** [comment] 2024-02-13 23:29
@amyevans although I have bump the expensify-common version, I don't think my changes lead to this issue as it only touched the code connected with codeFences. Last version  of `expensify-common` was 3 weeks old and in the meantime following PR regarding emojis was merged - https://github.com/Expensify/expensify-common/pull/640

**Comment by situchan** [comment] 2024-02-13 23:35
I confirmed https://github.com/Expensify/expensify-common/pull/640 is the offending PR.
Especially this change:
```
        this.rules = [
+           {
+               name: 'emoji',
+               regex: CONST.REG_EXP.EMOJIS,
+               replacement: match => `<emoji>${match}</emoji>`
+           },
```

**Comment by amyevans** [comment] 2024-02-14 15:34
Thanks @robertKozik and @situchan, and apologies for the incorrect assumption.

I'll open a PR to revert https://github.com/Expensify/expensify-common/pull/640 as it was merged prematurely and it doesn't seem like the other PRs for https://github.com/Expensify/App/issues/34307 are quite ready to go yet. cc @dukenv0307 @stitesExpensify 

That'll take care of this GH as well as another deploy blocker linked to the changes.

**Closed** 2024-02-14 19:03 UTC
Labels: Reviewing, Engineering, Weekly, Bug
