### ISSUE TITLE
[$1000] - Task report should not change positioning in LHN when edited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24472] opened 2023-08-12 00:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. As User A, go to a group conversation where User B is a member, and create an unassigned task
3. As User B, go to the unassigned task in Step 2 and assign it to User B
4. Go to User A chat 
5. Observe the positioning in the LHN of the task created in Step 3

## Expected Result:
The task's positioning should remain fixed. When a task is edited (including assignment), task should not change position in the LHN 

## Actual Result:
The task's positioning changes and it moves to the top of the LHN. This is incorrect because only when a task is Opened, reopened, completed or canceled, should it change positioning in the LHN. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b83116b4-9763-4ff7-b9bf-8506e4b770bc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115d36a3883b42226</li>
        <li>Upwork Job ID: 1691854330120933376</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27106438</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-08-16 16:47
Agree the task with the green dot should move to the top.

**Comment by stephanieelliott** [comment] 2023-08-22 16:29
I'm now getting the same behavior across all web platforms. Perhaps this was fixed in a recent release?

**Comment by stephanieelliott** [comment] 2023-08-25 16:55
@lanitochka17 can you try re-testing to see if the behavior is still occurring?

**Comment by lanitochka17** [comment] 2023-08-25 17:58
Issue reproducible with Build 1.3.57-4


https://github.com/Expensify/App/assets/78819774/75be16aa-1e11-40b4-98a0-a00284c29f1f

**Comment by stephanieelliott** [comment] 2023-09-01 18:33
@thesahindia the expected hierarchy is: pinned rooms > green dot tasks > all other rooms. So expected behavior here is that the green dots should be at the top, with all other unpinned rooms below. Let me know if you need more specific info than that!

**Comment by ShogunFire** [comment] 2023-09-04 13:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A rport with green dot should be at the top immediatly

### What is the root cause of that problem?

In getOrderedReportIDs here: https://github.com/Expensify/App/blob/aab0b22592b1dd933a482f799a07917a8be9e61e/src/libs/SidebarUtils.js#L114-L123

we are sorting the reports but we are not handling well the reports with green dots, the only condition we have is if the report is an outstanding iou, there are other cases where the report has a green dot and should be at the top

### What changes do you think we should make in order to solve the problem?

To determine if the report has a green dot we can use the same condition that we have in OptionRowLHN here: https://github.com/Expensify/App/blob/aab0b22592b1dd933a482f799a07917a8be9e61e/src/components/LHNOptionsList/OptionRowLHN.js#L105-L109

There are other changes that we need to make, for example replacing the variable outstandingIOUReports to greenDotReports and modify the code where we sort that array because right now we are sorting by amount of iou here https://github.com/Expensify/App/blob/aab0b22592b1dd933a482f799a07917a8be9e61e/src/libs/SidebarUtils.js#L155

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-09-12 22:56
Posted for input on the expected behavior: https://expensify.slack.com/archives/C049HHMV9SM/p1694559281947899

**Comment by flodnv** [comment] 2023-09-18 03:26
Looks like this is related to tasks, so assigning you @thienlnam

**Comment by mvtglobally** [comment] 2023-09-21 03:35
Issue not reproducible during KI retests. (First week)

**Comment by stephanieelliott** [comment] 2023-09-22 00:00
I'm also not able to reproduce!

**Comment by stephanieelliott** [comment] 2023-10-04 17:44
OK, this is getting confusing...  I retested this several times and it is still happening. 

To make this issue clearer I have: 

1. Updated the title to specify the problematic behavior (since we have drilled in a lot since this was first opened
2. Updated the repro steps to point out that we're specifically looking at the task's positioning in the LHN 
3. Updated the `Actual Result` and `Expected Result`. This issue is unrelated to the green dot and I think that had a part in confusing things. 

The expectation is: 

 - **When a task is created**, reopened, completed or canceled, it rises to the top of the LHN 
 - **When a task is edited** (including assignment), task should not change position in the LHN

**Comment by thienlnam** [comment] 2023-10-05 07:10
Is this specific to only Windows?

**Comment by thienlnam** [comment] 2023-10-05 07:12
Regardless, the solution does make sense for BE updates - we updated the FE to not update those parameters on the report but will still need to update the BE. We're already planning some updates to split up the edit task commands so I'm going to add this issue to that as well

**Comment by thienlnam** [comment] 2023-10-05 07:19
I think we need to double check that the solution doesn't re-add this [bug](https://github.com/Expensify/App/issues/25548) because we just removed childLastVisibleActionCreated from the completed / uncompleted task actions because we're not counting them as 'replies'

**Comment by stephanieelliott** [comment] 2023-10-11 04:46
Moving this to `Weekly` as it's on hold

**Comment by stephanieelliott** [comment] 2023-10-17 01:10
Still held on BE work

**Comment by stephanieelliott** [comment] 2023-10-25 21:05
Looks like E/E #299956 should probably be wrapping up soon

**Comment by thienlnam** [comment] 2023-11-04 17:16
Linked PR is wrapping up soon, I can add the back-end changes after that refactor is done

**Comment by stephanieelliott** [comment] 2023-11-13 15:21
Refractor in https://github.com/Expensify/Expensify/issues/299956 is done, @thienlnam is working on BE changes now

**Comment by thienlnam** [comment] 2023-11-21 19:03
Haven't started yet - probably something that will happen after the thanksgiving week since I have some other things to catch up on this week

**Comment by stephanieelliott** [comment] 2023-12-04 17:26
BE changes still WIP

**Comment by stephanieelliott** [comment] 2023-12-13 14:52
Hey @thienlnam, any update on the BE changes?

**Comment by thienlnam** [comment] 2023-12-14 19:52
Nope, haven't been working on this for other priorities. Since this now falls under vip-vsb I can aim to do it by EOY

**Comment by thienlnam** [comment] 2024-01-02 23:58
Going to close this for https://github.com/Expensify/App/issues/23302, the issue is that editing a task adds a currently invisible reportAction which updates the positioning in the LHN. That's currently a problem, but for https://github.com/Expensify/App/issues/23302 we are making those edit system messages visible which will correct this issue in the process

**Closed by thienlnam** 2024-01-02 23:58 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
