### ISSUE TITLE
iOS - There are two offline messages in final page of the send money IOU flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10261] opened 2022-08-05 14:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign into an account on NewDot.
2. Turn off your WiFi.
3. Click FAB> Send money
4. Complete until the final page of the flow

## Expected Result:
There must be one offline message in the page

## Actual Result:
There are two offline messages in IOU and loading spinner appears in the button

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** v1.1.88-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/183098199-45f62a0c-3750-421d-bce8-5a38ca4167d1.jpg" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/183098206-389b4dff-e40c-45fe-8c6b-0d9b31017e9f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2022-08-05 17:25
@Julesssss do you have any insight into this problem?

**Comment by tgolen** [comment] 2022-08-05 19:01
hm, he is offline. @marcaaron or @yuwenmemon do you have any idea who was working on this area?

**Comment by marcaaron** [comment] 2022-08-05 21:48
I think it might be this:

- We added the page wrapper that will now show the offline message in many places cc @jasperhuangg 
- The red message that is displaying here is a random implementation from a much older issue

**Comment by Julesssss** [comment] 2022-08-08 10:46
Looking into this. Did anyone else manage to reproduce this? Because I'm seeing the expected behavior now on my physical iPhone 7 (matching all other platforms).

**Offline UI shown**
![IMG_0076](https://user-images.githubusercontent.com/10736861/183400875-3560e685-bb9d-4c9f-a916-78382d432c7e.PNG)

**Version**
![IMG_0077](https://user-images.githubusercontent.com/10736861/183400880-d1499f48-67e2-4a8f-b481-4032da39d3f1.PNG)

**Comment by Julesssss** [comment] 2022-08-08 10:54
I'll leave the issue open for a moment, just in case this is reproducible with additional steps that I missed. But I'll remove it as a deploy blocker.

**Comment by Julesssss** [comment] 2022-08-08 10:57
I'm going to close this. If anyone reading this can reproduce it, please re-open, uncheck the checklist box and share the exact device and steps you took.

**Closed by Julesssss** 2022-08-08 10:57 UTC
Labels: Engineering, Daily
