### ISSUE TITLE
[$250] mWeb/Safari - Details - blue outline while copy email to clipboard @gadhiyamanan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11382] opened 2022-09-28 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Go to participant details
4. Click on clipboard

## Expected Result:
Should not be blue outline

## Actual Result:
Shows blue outline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/safari

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192858941-3f4874ba-e099-4b74-a096-7e4aaa57e3c4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663234285784449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-09-29 10:27
Hi, It was reported by me [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661765028598559) and the blue outline shows up at multiple places not only at the clipboard.

**Comment by kevinksullivan** [comment] 2022-09-29 14:58
I can't reproduce on web safari @Puneet-here .

**Comment by kevinksullivan** [comment] 2022-09-29 14:59
https://www.upwork.com/jobs/~01df55da3709a59a8b

**Comment by parasharrajat** [comment] 2022-09-29 19:10
This needs external label

**Comment by Puneet-here** [comment] 2022-09-29 19:13
I can repro
<img width="1294" alt="Screenshot 2022-09-30 at 12 41 36 AM" src="https://user-images.githubusercontent.com/101883770/193121734-31695abb-56b7-4e06-be5d-8d3cb7dccd8c.png">

**Comment by kevinksullivan** [comment] 2022-10-03 15:47
Looking for proposals.

**Comment by kevinksullivan** [comment] 2022-10-03 15:47
@Puneet-here what version are you on? I still can't reproduce.

**Comment by MonilBhavsar** [comment] 2022-10-04 05:54
I also cannot reproduce the issue

**Comment by Puneet-here** [comment] 2022-10-05 07:23
> @Puneet-here what version are you on? I still can't reproduce.

I don't remember the version, I had updated it. It's not reproducible on new versions.

Same goes for ios safari it's not reproducible on newer versions, I believe it can't be reproduced for devices with ios 15.5-16.
Which makes me think that it's related to safari and not our code.

**Comment by parasharrajat** [comment] 2022-10-05 09:41
This is surely a regression. I remember Focus outline was not shown on mobile platforms.

**Comment by kbecciv** [comment] 2022-10-10 19:11
@MonilBhavsar Checking, will update you shortly

**Comment by kbecciv** [comment] 2022-10-10 19:14
Issue is still reproducible with latest build 1.2.12.3

https://user-images.githubusercontent.com/93399543/194937052-70a7f851-cb51-4f14-8725-30a95280fb26.MP4

**Comment by Puneet-here** [comment] 2022-10-11 10:15
@MonilBhavsar, correct. This is only at older versions, I was seeing the same issue at safari  on my mac but after updating I can't repro, same for ios. I tried ios 15.5 - 16 and it is not reproducible there.

**Comment by MonilBhavsar** [comment] 2022-10-14 08:28
@kbecciv could you please check this comment https://github.com/Expensify/App/issues/11382#issuecomment-1274208079
Thank you!

Also, bumoing it to weekly since it is not reproducible on latest version and not a blocking issue

**Comment by parasharrajat** [comment] 2022-10-14 11:43
I think we can just close this issue we this is not happening on the latest safari versions. Because technically this is not a bug but UI stuff. I am sure that with time more users will be forced to use the latest safari versions and this is a low priority.

**Comment by kbecciv** [comment] 2022-10-15 03:23
@MonilBhavsar this happening with IOS 14.2 version

**Comment by MonilBhavsar** [comment] 2022-10-17 05:46
Thanks! Yes, I think we can close this one considering a non blocking UI issue occurring on very old iOS version. Feel free to reopen if you disagree

**Closed by MonilBhavsar** 2022-10-17 05:46 UTC
Labels: External, Weekly, Help Wanted
