### ISSUE TITLE
Web - App goes to another chat when clicking on group's member multiple times quickly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23956] opened 2023-07-31 20:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Any group
2. Click on the group's any member multiple times quickly
3. You go to another chat after that

## Expected Result:
We shouldn't go to another chat when clicking on group's member multiple times quickly

## Actual Result:
 App goes to another chat when clicking on group's member multiple times quickly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (60) (1).webm](https://github.com/Expensify/App/assets/93399543/0ea78f0f-10fa-4ada-a2aa-5ccd448de53b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690693143662559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment] 2023-08-02 14:50
I'm not able to reproduce this so I posted in the Slack thread. I'll close this for now as it also seems to be a super edge case.

**Closed by flaviadefaria** 2023-08-02 14:50 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by MahmudjonToraqulov** [comment] 2023-08-03 04:49
> I'm not able to reproduce this so I posted in the Slack thread. I'll close this for now as it also seems to be a super edge case.

Hey @flaviadefaria.
Have you posted it in the Slack thread. I couldn't find it there.
