### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] Strikethrough markdown is not copied from Slack

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35370] opened 2024-01-30 10:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Navigate to a conversation
3. Copy a strikethrough text from Slack app
4. Paste the text in to composer and Send the text

## Expected Result:
Strikethrough markdown is also copied&pasted with text

## Actual Result:
Only the text is copied&pasted without strikethrough markdown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/251769b9-9a69-4bf4-84e4-ce20a5053c9f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d7c3fc329304d65</li>
        <li>Upwork Job ID: 1752277622429736960</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by bernhardoj** [comment] 2024-01-30 12:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copying a strikethrough text from slack shows a normal text without strikethrough markdown.

### What is the root cause of that problem?
When we copy a strikethrough markdown from slack, the HTML tag is `<s>`.
<img width="447" alt="image" src="https://github.com/Expensify/App/assets/50919443/5f2fff3e-c473-4e51-b3ce-100bce66e82f">

But the regex for strikethrough only considered for `<del>` tag.
https://github.com/Expensify/expensify-common/blob/6ae333c38ca5909245c6310db1dc66728d62d0ed/lib/ExpensiMark.js#L369-L371

### What changes do you think we should make in order to solve the problem?

Add `s` to the regex.

```
<(del|s)...
```

**Comment by abdulrahuman5196** [comment] 2024-02-05 13:53
Will go through proposal today

**Comment by miljakljajic** [comment] 2024-02-07 16:43
Waiting for @abdulrahuman5196 to review the proposals

**Comment by abdulrahuman5196** [comment] 2024-02-08 19:38
Hi, Sorry for the delay. Will take care of this in my morning or will re-assign tomorrow night.

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:14
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:22
@thienlnam Hi, Is this something that would be fixed by the live markdown feature? Or should we fix it as part of this issue?

**Comment by thienlnam** [comment] 2024-02-12 22:00
I don't think preserving markdown in clipboard is something that would be resolved by live markdown - so this can be handled in this issue

**Comment by abdulrahuman5196** [comment] 2024-02-14 18:19
Thank you for the update. Will work on the proposal review.

**Comment by abdulrahuman5196** [comment] 2024-02-16 08:59
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/35370#issuecomment-1916764860 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by bernhardoj** [comment] 2024-02-18 06:37
expensify-common PR is [here](https://github.com/Expensify/expensify-common/pull/653)

cc: @abdulrahuman5196

**Comment by bernhardoj** [comment] 2024-02-21 05:27
App PR is ready

cc: @abdulrahuman5196

**Comment by mountiny** [comment] 2024-03-13 23:17
Asked QA to retest

**Comment by mountiny** [comment] 2024-03-14 12:50
@bernhardoj QA can still repro this issue
https://github.com/Expensify/App/assets/36083550/f2005895-2696-4f1f-98bf-fd922ccbe751

**Comment by bernhardoj** [comment] 2024-03-14 13:19
Hmm, that's weird. Can you test it yourself? Or maybe @abdulrahuman5196

**Comment by mountiny** [comment] 2024-03-14 14:57
@bernhardoj so it works when the message is posted, but it does not work from the markdown composer

ie the above works, the below does not
<img width="555" alt="image" src="https://github.com/Expensify/App/assets/36083550/76ba8549-46d4-4c03-bb44-6e3ca4d85a3f">

I guess that is expected though

**Comment by bernhardoj** [comment] 2024-03-14 15:12
Yeah, I think we can do nothing about that as it's copied as plain text.

**Comment by miljakljajic** [comment] 2024-03-18 14:50
Creating a new upwork job: the previous one has expired

**Comment by miljakljajic** [comment] 2024-03-18 14:56
contracts issued to you both!

**Comment by miljakljajic** [comment] 2024-03-19 10:41
Paid!

**Closed by miljakljajic** 2024-03-19 10:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
