### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Category - Selected category does not appear as selected in split request Category list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37346] opened 2024-02-27 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Click + > Split bill > Scan
4. Upload a receipt
5. Proceed to confirmation page
6. Click Category and select a category
7. Click Split button
8. Click on the split preview
9. Click Category

## Expected Result:
The selected category will appear as selected in split request Category list

## Actual Result:
The selected category does not appear as selected in split request Category list
This issue is only reproducible with Split Scan request and not with manual request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ced029cb-d479-40a3-b728-36c4174c1503

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189e694798cc802db</li>
        <li>Upwork Job ID: 1762570237814657024</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 20:08
We think that this bug might be relpated to #vip-split-p2p-chat-groups
CC @arielgreen

**Comment by Tony-MK** [comment] 2024-02-27 21:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Category - Selected category does not appear as selected in split request Category list

### What is the root cause of that problem?

Once the backend responds to the split bill request, the `splitDraftTransaction` is deleted.

https://github.com/Expensify/App/blob/069efefa7b550bb7b5325f108b96a52cc6a1e896/src/pages/iou/request/step/IOURequestStepCategory.js#L75

Therefore, the category in the `IOURequestStepCategory` component will be `undefined` because the `splitDraftTransaction` is not found in the onyx.

https://github.com/Expensify/App/blob/069efefa7b550bb7b5325f108b96a52cc6a1e896/src/pages/iou/request/step/IOURequestStepCategory.js#L136-L140

### What changes do you think we should make in order to solve the problem?


Check if the `splitDraftTransaction` is found and can be used.

Therefore, let us change the first code snippet, [here](https://github.com/Expensify/App/blob/069efefa7b550bb7b5325f108b96a52cc6a1e896/src/pages/iou/request/step/IOURequestStepCategory.js#L75), above with the one below.

```
const {category: transactionCategory} = 
 ReportUtils.getTransactionDetails(
   isEditingSplitBill && splitDraftTransaction ? 
   splitDraftTransaction : 
   transaction
);
```

### What alternative solutions did you explore? (Optional)

At the onyx level, we set the attributes for the `splitDraftTransaction` prop from `transaction` if the  `splitDraftTransaction` was not available.

**Comment by puneetlath** [comment] 2024-02-28 15:38
CP'ing the fix.

**Comment by abdulrahuman5196** [comment] 2024-03-01 10:35
@puneetlath We don't need payment here since its a regression fix. We can close this issue.

**Comment by puneetlath** [comment] 2024-03-01 15:24
Great, thanks y'all!

**Closed by puneetlath** 2024-03-01 15:24 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment
