### ISSUE TITLE
[$1000] Inconsistency Between Workspace Name and Notification When Editing Workspace Name with HTML Number Code

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20009] opened 2023-06-01 21:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the settings.
2. Create a workspace.
3. Edit the workspace name using HTML number code. I used this HTML number code: "&#72;&#101;&#108;&#108;&#111;".
4. Check the notification when you update the workspace name. It changes the HTML number code to actual words, eg HTML number code "&#72;&#101;&#108;&#108;&#111;" to "Hello"
## Expected Result: 
The app should maintain consistency by not converting HTML number code to actual words in the notification when updating the workspace name. with Html code
## Actual Result: 
Copy-pasting HTML number code as the workspace name results in inconsistency with the notification

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (51).webm](https://github.com/Expensify/App/assets/43996225/2d177ec6-01b4-4a05-88da-52b4348697c1)

https://github.com/Expensify/App/assets/43996225/244c8a1b-8a5b-4afb-997a-bf7ed704c75e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosgirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685474701365379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01913c9e61282ff2f2</li>
        <li>Upwork Job ID: 1666991086241906688</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-06-05 08:21
I think the BE should encode/escape the workspace name updated message.

**Comment by arielgreen** [comment] 2023-06-07 01:49
Wrong Slack convo linked, should be https://expensify.slack.com/archives/C049HHMV9SM/p1685474701365379

**Comment by arielgreen** [comment] 2023-06-09 02:10
@bondydaa I marked this external -- can you confirm this is okay to be external or does it need to be handled internally?

**Comment by BhuvaneshPatil** [comment] 2023-06-09 02:46
A proposal very similar to this - https://github.com/Expensify/App/issues/20080#issuecomment-1575164520

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency Between Workspace Name and Notification When Editing Workspace Name with HTML Number Code

### What is the root cause of that problem?
As mentioned in linked proposal, this is happening because we are not encoding the message before passing to `RenderHTML` component.
Example - `&#72` - this is equivalent of letter `H`, so the `RenderHTML` will convert it to `H`
But if we encode it using `Str.htmlEncode()` it will be converted to - `&amp;#72` and HTML will render `&amp` part as `&`. and remaining as it is. 

### What changes do you think we should make in order to solve the problem?
encode the html before passing it to `RenderHTML`. we can do this conditionally by using `prop` or based on the type of report (mentioned in the proposal)
With this solution we can solve this https://github.com/Expensify/App/issues/20080 as well.
![image](https://github.com/Expensify/App/assets/27822551/a9728656-9589-4e0a-aa5b-ae3636e9660f)



### What alternative solutions did you explore? (Optional)
None

**Comment by BhuvaneshPatil** [comment] 2023-06-13 07:48
Yes @thesahindia .
![image](https://github.com/Expensify/App/assets/27822551/82b33fb4-f3f7-449c-a894-8130f44ab656)

**Comment by BhuvaneshPatil** [comment] 2023-06-13 08:05
The final solution will be combination of https://github.com/Expensify/App/issues/20080#issuecomment-1575164520 and https://github.com/Expensify/App/issues/20009#issuecomment-1583874768, 
That is, we add the prop to `ReportActionItemFragment` to encode the HTML, this is required to avoid regression.

**Comment by arielgreen** [comment] 2023-06-14 22:59
@tewodrosGirmaA @BhuvaneshPatil @thesahindia please be sure to also apply to the Upwork posting asap https://www.upwork.com/jobs/~01913c9e61282ff2f2

**Comment by BhuvaneshPatil** [comment] 2023-06-15 01:36
@arielgreen shall I wait till I get assigned or start working on it? If yes, can you please assign this issue to me.
Thank you.

**Comment by BhuvaneshPatil** [comment] 2023-06-15 02:13
I took a fresh pull, I think the issue is resolved from backend

**Comment by arielgreen** [comment] 2023-06-16 02:54
Reassigning, team change

**Comment by NicMendonca** [comment] 2023-06-16 19:03
@BhuvaneshPatil  thanks for calling that out, and @thesahindia for confirming! 

Closing!

**Closed by NicMendonca** 2023-06-16 19:03 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by tewodrosGirmaA** [comment] 2023-06-16 20:12
Hi @arielgreen @MelvinBot , I applied for Job in upwork , is their additional thing needed from me ?
