### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] Web - IOU - Error message paying elsewhere partially a report with two held expenses and a tracked

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53425] opened 2024-12-03 06:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49971
**Email or phone of affected tester (no customers):** gatantm+123b@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ on a workspace chat
2. Submit 3 expenses (1 expense with a different currency) and track 1 forth expense
3. Hold 2 expenses (1 expense with the different currency)
4. Go back to the main chat
5. Select Pay elsewhere on the report
6. Confirm the partial amount

## Expected Result:
The partial amount is paid

## Actual Result:
"The requested amount has changed" error message is shown

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e662d436-8de4-4ec3-ad92-ff97486ed5f6
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021864070097967682615</li>
        <li>Upwork Job ID: 1864070097967682615</li>
        <li>Last Price Increase: 2024-12-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-12-03 06:18
Production behavior 

https://github.com/user-attachments/assets/bddff7d6-5884-4a56-935e-e95338bbb619

**Comment by techievivek** [comment] 2024-12-03 13:19
@bernhardoj Do you mind taking a look at this ticket and see if it's related to your changes above?

**Comment by puneetlath** [comment] 2024-12-03 23:32
Demoting as discussed in thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1733206499066379

**Comment by trjExpensify** [comment] 2024-12-03 23:35
P.S when trying to look at this from that thread, I was getting a duplicate report preview when I held an expense on `v9.0.70-1` desktop app.

Steps: 

1. Create 2 expenses in the workspace currency 
2. Create 1 expense in a different currency 
3. Click into the expense report
4. Hover over the preview of the first expense in the report.
5. Click `Hold` **from the comment action menu** on the expense preview 
6. Observe the duplicate report preview created

<img width="827" alt="image" src="https://github.com/user-attachments/assets/f6cf11d3-4b07-4c70-86e2-59d6b179b8b6">

**Comment by bernhardoj** [comment] 2024-12-04 13:04
I wanna test this on prod, but the PR is deployed to prod already. I think this issue exists on prod too. The prod video [here](https://github.com/Expensify/App/issues/53425#issuecomment-2513656001) doesn't show the pay behavior. The issue here is that, when we pay money request with held expenses partially, we use the amount of `unheldTotal` as the pay total.
https://github.com/Expensify/App/blob/146204878d1b9d4358d91e9a0a81169a7819d96f/src/libs/actions/IOU.ts#L6642-L6645

However, `unheldTotal` includes non-reimbursable transactions too (track), so we got the error. Previously `unheldTotal` doesn't include non-reimbursable transactions, but we agreed to [update it on the BE to include it](https://github.com/Expensify/App/pull/49971#issuecomment-2396212682). Since it's a BE change and has been updated since 16 Oct, I believe this exists on prod too.

The solution to this is to subtract `unheldTotal` by `unheldNonReimbursableTotal`.

**Comment by s77rt** [comment] 2024-12-04 14:40
@bernhardoj This seems like something we missed? [The plan](https://github.com/Expensify/App/pull/49971#issuecomment-2397561749) already covered that.


> In the approve modal display:
> 
> Partial: unheldTotal
> Full: total
>
> In the pay modal display:
> 
> Partial: **unheldTotal - unheldNonReimbursableTotal**
> Full: total - nonReimbursableTotal
>

**Comment by s77rt** [comment] 2024-12-04 14:42
@bernhardoj Please raise a PR since this is a regression (or at least it's something that was supposed to be done in the PR)

**Comment by bernhardoj** [comment] 2024-12-04 15:40
> This seems like something we missed? https://github.com/Expensify/App/pull/49971#issuecomment-2397561749 already covered that.

That plan only handles the amount to be shown, not the API params.

**Comment by bernhardoj** [comment] 2024-12-04 15:52
I'll handle this tomorrow.

**Comment by bernhardoj** [comment] 2024-12-05 06:30
PR is ready

**Comment by sobitneupane** [comment] 2024-12-09 16:16
This issue was a regression from https://github.com/Expensify/App/pull/49971 PR and is handled by the author of the PR, payment and checklist will be handled in [the original issue.](https://github.com/Expensify/App/issues/48760)

**Comment by s77rt** [comment] 2024-12-15 00:52
Let's close this one. No payment is due here (regression)

**Comment by techievivek** [comment] 2024-12-16 12:08
Closing this based on above comments.

**Closed by techievivek** 2024-12-16 12:08 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
