### ISSUE TITLE
[HOLD for payment 2022-11-16] [$500] Android/iOS - Workspace - Numbers shaking while updating rate in reimburse expenses @gadhiyamanan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11352] opened 2022-09-27 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2.  Log in with any account with Workspace or create one
3. Go Workspace > Reimburse expenses
4. Edit rate

## Expected Result:
Numbers should not shake

## Actual Result:
Numbers shaking while updating rate in reimburse expenses

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android
- iOS

**Version Number:** 1.2.7.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192622718-5a98422b-3ed5-436a-9430-3ebb31e1f099.mp4

https://user-images.githubusercontent.com/43996225/192906134-41c76c0d-c8fe-4d3c-83fa-2b8e1533b46a.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662571711808209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2022-09-29 14:19
Hmm, I don't think this is a bug and is intended behavior? The number can only be so big, so we remove the last number. Feel free to reply if you disagree.

**Comment by gadhiyamanan** [comment] 2022-09-29 14:36
@AndrewGable i think we should add character limitations instead of removing last number

**Comment by gadhiyamanan** [comment] 2022-09-29 16:25
@AndrewGable please check send money, user can enter 8 character 
https://user-images.githubusercontent.com/54790231/193086346-4573661c-0abb-42f3-897d-371a56755a7d.mp4

**Comment by AndrewGable** [comment] 2022-09-29 16:28
Ok thank you, I agree let's match that functionality. I will send to internal if you'd like to propose a solution.

**Comment by sketchydroide** [comment] 2022-10-03 13:19
This is a [duplicated GH but on iOS](https://github.com/Expensify/App/issues/11402), This makes me think this is not Android specific. Changing the Details, but Closing the other one.

**Comment by thesahindia** [comment] 2022-10-05 06:57
Not overdue. We are waiting for proposals.

**Comment by puneetlath** [comment] 2022-10-05 14:45
Updated to $500. 

External Upwork job: https://www.upwork.com/jobs/~01f773e86446de6809
Internal Upwork job: https://www.upwork.com/ab/applicants/1577671134189699072/job-details

**Comment by tienifr** [comment] 2022-10-07 08:54
# Proposal

## Problem
When we change the text in rate input, the below function is executed. And if the user enters more than 8 character, it's not valid so `isInvalidRateValue` === true and it will update the old value again
in /App/src/pages/workspace/reimburse/WorkspaceReimburseView.js
```diff

setRate(value) {
        const decimalSeparator = this.props.toLocaleDigit('.');
        const rateValueRegex = RegExp(String.raw`^\d{1,8}([${getPermittedDecimalSeparator(decimalSeparator)}]\d{0,3})?$`, 'i');
        const isInvalidRateValue = value !== '' && !rateValueRegex.test(value);
        this.setState(prevState => ({
            unitRateValue: !isInvalidRateValue ? this.getRateDisplayValue(value) : prevState.unitRateValue,
        }), () => {
            // Set the corrected value with a delay and sync to the server
            this.updateRateValueDebounced(this.state.unitRateValue);
        });
    }
```

## Solution
We should add maxLength in TextInput component to prevent users from entering more than 8 characters
in /App/src/pages/workspace/reimburse/WorkspaceReimburseView.js
```diff
<TextInput
                                        label={this.props.translate('workspace.reimburse.trackDistanceRate')}
                                        placeholder={this.state.outputCurrency}
                                        onChangeText={value => this.setRate(value)}
                                        value={this.state.unitRateValue}
                                        autoCompleteType="off"
                                        autoCorrect={false}
                                        keyboardType={CONST.KEYBOARD_TYPE.DECIMAL_PAD}
                                        onKeyPress={this.debounceUpdateOnCursorMove}
+                                      maxLength={CONST.MAX_LENGTH_IN_RATE_INPUT}
/>
```
and in /App/src/CONST.js
```diff
+                                          MAX_LENGTH_IN_RATE_INPUT: 8,
```
Result: 

https://user-images.githubusercontent.com/113963320/194510919-7f456edf-c742-4d74-8112-54525589e19b.mov

**Comment by al7373** [comment] 2022-10-09 23:51
**Proposal**

Hello everybody,

We can't fix the problem by simply changing the regex or imposing a larger character limit. 
The problem affects all elements that use the RNTextInput (BaseTextInput) component.
@gadhiyamanan , **"send money"** also present the same symptom, it shakes. 
The problem is: The native TextInput is very fast, the characters you have just typed are displayed before being processed by React which corrects afterwards by imposing the value it has calculated, from this comes the tremor when the character typed does not follow the regex. 
The source of the bug comes from "src/components/RNTextInput.js" not from "src/pages/workspace/reimburse/WorkspaceReimburseView.js".
Here is a solution that I partially implemented. We should make an entire component that updates only when the "props.value" has been checked by React. 

In the following code, I simply mask the TextInput with its clone while waiting for the props.value to actually change in React. Result: There is no more tremor.

`const RNTextInput = (props) => {

    const [screenOpacity, setScreenOpacity] = React.useState(1);

    function handleKeyDown(){
    }

    React.useEffect(function(){
    }, [props.value])


    const original = <TextInput
        ref={(ref) => {
            if (!_.isFunction(props.forwardedRef)) {
                return;
            }
            props.forwardedRef(ref);
        }}

        // By default, align input to the left to override right alignment in RTL mode which is not yet supported in the App.
        // eslint-disable-next-line react/jsx-props-no-multi-spaces
        textAlign="left"

        // eslint-disable-next-line
        {...props}

        onKeyPress={ handleKeyDown }
    />

    const clone = React.cloneElement(original, { ...props, editable: false });

    return <>
        { original }
        <View 
                pointerEvents="none" 
                style={{ 
                  position: 'absolute', 
                  width: "100%",
                  opacity: screenOpacity,
                  backgroundColor: 'white'
                }}
        >
                { clone }
        </View>
    </>
};
`
[solution.webm](https://user-images.githubusercontent.com/24714808/194785123-7be3191d-2dc4-42d4-8e18-227e6084eba6.webm)

**Comment by thesahindia** [comment] 2022-10-11 06:33
Will review today. I will do some investigation first.

**Comment by thesahindia** [comment] 2022-10-11 20:32
I like @aimane-chnaif's [proposal](https://github.com/Expensify/App/issues/11352#issuecomment-1271725848) as it's the most simple solution and works correctly.

C+ reviewed 🎀👀🎀

cc: @AndrewGable

**Comment by Uros787** [comment] 2022-10-11 21:10
hi @thesahindia , dont want to interfere with the judgment but speaking from user experience and not only as a contributor - I don't believe that allowing users to type as many numbers, and then reverting to 8 chars is the most desirable behavior.
This could be misleading, that is why I went with the solution of adding a dot since users can straight away see how the input should look like

**Comment by thesahindia** [comment] 2022-10-13 15:05
In my opinion this is fine, I believe we shouldn't add the decimal while they are typing. Also it's not really a real life case.

**Comment by puneetlath** [comment] 2022-10-13 19:48
@AndrewGable what do you think?

**Comment by AndrewGable** [comment] 2022-10-17 23:51
Agree with @thesahindia's [comment here](https://github.com/thesahindia), I'd suggest @aimane-chnaif.

**Comment by AndrewGable** [comment] 2022-10-26 23:38
PR is under review, discussing

**Comment by puneetlath** [comment] 2022-11-09 16:36
@thesahindia could you help with identifying the PR where the bug was introduced?

**Comment by thesahindia** [comment] 2022-11-09 21:00
> @thesahindia could you help with identifying the PR where the bug was introduced?

I think https://github.com/Expensify/App/pull/9800

**Comment by puneetlath** [comment] 2022-11-16 23:25
@gadhiyamanan @aimane-chnaif @thesahindia can you please apply to the Upwork job here so I can get everyone paid out: https://www.upwork.com/jobs/~01427aa8632545994e

**Comment by gadhiyamanan** [comment] 2022-11-17 02:34
Applied 🚀

**Comment by thesahindia** [comment] 2022-11-17 05:55
Applied, thanks!

**Comment by puneetlath** [comment] 2022-11-21 15:33
Sorry for the delay! Sent you all hiring offers.

**Comment by thesahindia** [comment] 2022-12-01 14:30
@puneetlath, let's close this. I believe it is settled.

**Closed** 2022-12-01 14:43 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
