### ISSUE TITLE
[$250] Android - NetSuite - Option is not being selected without scrolling first on a long list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44927] opened 2024-07-05 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44159
## Action Performed:
1. Create a connection with NetSuite on OD
2. Open the account on ND
3. Go to the workspace accounting settings
4. Go to export configuration
5. Go to Export reimbursable expenses as config
6. Select Journal Entries for the Export as setting
7. Open Reimbursable journal posting account
8. Select any option if none is selected
9. Do step 7 again and tap on any option without scrolling the list

## Expected Result:
App selects the tapped option

## Actual Result:
User is unable to select on the tapped option without scrolling first, user has to scroll first to be able to select from the options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/93c786db-5dc1-4ac6-8d34-01727e8e3cf5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01315e9cb0864499cf</li>
        <li>Upwork Job ID: 1810247323723969047</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103033403</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by mountiny** [comment] 2024-07-05 17:57
I think Netsuite is still behind beta @yuwenmemon and this seems minor so we can demote and deploy

**Comment by mountiny** [comment] 2024-07-05 17:57
cc @tgolen

**Comment by kadiealexander** [comment] 2024-07-08 06:42
@arosiclair do you think this is something our contributors could work on?

**Comment by mountiny** [comment] 2024-07-08 09:39
Yeah this can be external, but also tagging the involved engineers @yuwenmemon @mananjadhav

**Comment by mountiny** [comment] 2024-07-08 11:32
I havent tried, but I can ask QA if they are still able to repro

**Comment by kavimuru** [comment] 2024-07-08 13:28
Tester is still able to reproduce in the latest staging.

https://github.com/Expensify/App/assets/43996225/183843ed-b6a1-4a14-a1f4-28a7cd663103

**Comment by yuwenmemon** [comment] 2024-07-08 16:08
@shubham1206agra can you please have a look at this one?

**Comment by kadiealexander** [comment] 2024-07-16 05:08
@shubham1206agra bump!

**Comment by yuwenmemon** [comment] 2024-07-23 21:40
No update yet for this, we are looking for outside help/input: https://expensify.slack.com/archives/C06ML6X0W9L/p1721715155581529?thread_ts=1721712356.211049&cid=C06ML6X0W9L

**Comment by BrtqKr** [comment] 2024-07-26 08:49
Hey, I'm from SWM, I'd like to take care of this

**Comment by BrtqKr** [comment] 2024-07-26 10:01
One thing - how can I test NetSuite, do you have any accounts set up for debugging?

**Comment by yuwenmemon** [comment] 2024-07-28 23:58
@BrtqKr I can DM you some testing creds

**Comment by yuwenmemon** [comment] 2024-07-28 23:59
@BrtqKr I can DM you some testing creds

**Comment by BrtqKr** [comment] 2024-07-29 14:20
@lanitochka17 @yuwenmemon From what I can see this seems to be working as expected, but I don't see any particular changes that could possibly be the reason why this got fixed in the meantime. 

https://github.com/user-attachments/assets/0521d733-ea8e-4584-9817-0d8d873ace66

**Comment by JmillsExpensify** [comment] 2024-08-01 19:01
Going to close, so if anyone can reproduce please re-open the issue. Thanks!

**Closed by JmillsExpensify** 2024-08-01 19:01 UTC
Labels: External, Engineering, Daily, Overdue, Bug
