### ISSUE TITLE
[HOLD for Payment 2024-10-07][$250] Import categories - Import spreadsheet option is available when workspace is connected to QBO

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48913] opened 2024-09-10 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click 3-dot menu.
4. Click Import spreadsheet.

## Expected Result:
Import spreadsheet option should be hidden when there is connection in the workspace, as the categories are imported from the connection.

## Actual Result:
Import spreadsheet option is available when workspace is connected to QBO

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fcc5a939-5393-4521-82b1-bf6faff293dd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834239004653240865</li>
        <li>Upwork Job ID: 1834239004653240865</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104026058</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by IuliiaHerets** [comment] 2024-09-10 17:08
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by IuliiaHerets** [comment] 2024-09-10 17:09
We think that this bug might be related to #wave-control

**Comment by nkdengineer** [comment] 2024-09-10 17:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We always show the import sheet option without checking we connect an accounting or not


https://github.com/Expensify/App/blob/f642361ba357e1eeb522b2cc4291a620af67cfdb/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L300
### What changes do you think we should make in order to solve the problem?
We should use the same way we display the add category button

https://github.com/Expensify/App/blob/f642361ba357e1eeb522b2cc4291a620af67cfdb/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L248

```
const menuItems = [];
if (!PolicyUtils.hasAccountingConnections(policy)) {
    menuItems.push({
        icon: Expensicons.Table,
        text: translate('spreadsheet.importSpreadsheet'),
        onSelected: () => {
            if (isOffline) {
                Modal.close(() => setIsOfflineModalVisible(true));
                return;
            }
            Navigation.navigate(ROUTES.WORKSPACE_CATEGORIES_IMPORT.getRoute(policyId));
        },
    })
}
menuItems.push({
    icon: Expensicons.Download,
    text: translate('spreadsheet.downloadCSV'),
    onSelected: () => {
        if (isOffline) {
            Modal.close(() => setIsOfflineModalVisible(true));
            return;
        }
        Category.downloadCategoriesCSV(policyId);
    },
});
```
https://github.com/Expensify/App/blob/f642361ba357e1eeb522b2cc4291a620af67cfdb/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L300

If we already connected an accounting, we also need to display the not found page in `ImportCategoriesPage` and `ImportedCategoriesPage` page. We can display a helpful message that help user know that they already connected an accounting and cannot import category
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by nkdengineer** [comment] 2024-09-16 03:40
@thesahindia I think we also need to display the not found page in `ImportCategoriesPage` and `ImportedCategoriesPage` to prevent users from going to this page by deep link when we already connect an accounting.

**Comment by chiragsalian** [comment] 2024-09-16 17:30
Yeah i believe that is correct @nkdengineer. @thesahindia, what are your thoughts?

**Comment by nkdengineer** [comment] 2024-09-18 07:18
I think this is the thing that we can miss in the PR if we don't address this in the proposal.

**Comment by chiragsalian** [comment] 2024-09-18 19:16
Hmm okay alright, sorry @nkdengineer. @Nodebrute makes a convincing point and was first so I'll give it over to them.
Feel free to create the PR @Nodebrute.

**Comment by abekkala** [comment] 2024-09-20 16:18
@Nodebrute can you link the PR please?

**Comment by abekkala** [comment] 2024-10-04 18:29
### PAYMENT SUMMARY FOR OCT 07

- Fix: @Nodebrute [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104026058)
- PR Review: @thesahindia [$250, if no regressions] payment via NewDot

**Comment by abekkala** [comment] 2024-10-04 18:30
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 

- [ ] [@thesahindia ] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@thesahindia ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@thesahindia ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.
- [ ]  [@thesahindia ] Determine if we should create a regression test for this bug.
- [ ]  [@thesahindia ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@abekkala] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by abekkala** [comment] 2024-10-07 14:27
### PAYMENT SUMMARY FOR OCT 07

- Fix: @Nodebrute [$250] payment sent and contract ended - thank you! 🎉 
- PR Review: @thesahindia [$250] payment via NewDot

**Closed by abekkala** 2024-10-07 14:27 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by garrettmknight** [comment] 2024-10-08 18:27
$250 approved for @thesahindia
