### ISSUE TITLE
[$500] Close account - No message about successful account closure

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31690] opened 2023-11-22 12:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Security - Close account
4. Enter you account email and confirm the action

## Expected Result:
The message about the successful closing of the account appears

## Actual Result:
No message about successful account closure

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0c799746-51f8-422b-bc9d-112a2ad458e0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f060a06c71f21d9</li>
        <li>Upwork Job ID: 1727299354646183936</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-11-22 12:14
Not reproduce on production

https://github.com/Expensify/App/assets/115492554/8d1a1e77-9e67-45f8-abc5-740a9cf4d1de

**Comment by shubham1206agra** [comment] 2023-11-22 13:37
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Close account - No message about successful account closure

### What is the root cause of that problem?

This is due to introduced latency in the `save` function of `PersistedRequests` in https://github.com/Expensify/App/pull/30425, the `CloseAccount` API is never called and `redirectToSignIn` clears the `PersistedRequests` queue.

### What changes do you think we should make in order to solve the problem?

Use `makeRequestWithSideEffects` instead of `write` in the `CloseAccount` API call.

### What alternative solutions did you explore? (Optional)

Maybe revert the ttps://github.com/Expensify/App/pull/30425

**Comment by flodnv** [comment] 2023-11-22 15:30
Thank you for the proposals! Taking this to Slack for faster resolution: https://expensify.slack.com/archives/C01GTK53T8Q/p1700666993628189?thread_ts=1700655246.224999&cid=C01GTK53T8Q

**Comment by WojtekBoman** [comment] 2023-11-22 17:05
Hi, I think that this issue can be fixed by adding one change to the save method in PersistedRequests. I proposed a change [here](https://github.com/Expensify/App/pull/30425#issuecomment-1823090209), waiting for response from @roryabraham

**Comment by luacmartins** [comment] 2023-11-22 20:28
We reverted https://github.com/Expensify/App/pull/30425. @WojtekBoman can you please add this issue to your list when you work on v2 of https://github.com/Expensify/App/pull/30425?

**Comment by luacmartins** [comment] 2023-11-22 20:28
Offending PR was reverted. Removing blocker label.

**Comment by luacmartins** [comment] 2023-11-22 22:20
Gonna close this issue in favor of the original one - https://github.com/Expensify/App/issues/28172

**Closed by luacmartins** 2023-11-22 22:20 UTC
Labels: External, Engineering, Daily, Bug
