### ISSUE TITLE
Web -Chat - User can see the members list as a non admin for public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21491] opened 2023-06-24 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Using New Expensify as [danrvidal+snhtest5@gmail.com](mailto:danrvidal+snhtest5@gmail.com)
2. Open a public room https://staging.new.expensify.com/r/5593084223054221
3. Go to Settings > Members List
4. Check all emails

## Expected Result:
User can not see the members list as a non admin for public room

## Actual Result:
User can see the members list as a non admin for public room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (86)](https://github.com/Expensify/App/assets/93399543/34e14079-ca1a-4bf5-8beb-bcfff0ba9926)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Daniel Vidal

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686959350743089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2023-06-27 21:27
I'm not able to reproduce this one. @danielrvidal are you still running into this issue?

I'm going to close the issue, please reopen if you disagree.

**Closed by tjferriss** 2023-06-27 21:27 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
