### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000]  Link conflict when using a mentioned contact as an anchor text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18857] opened 2023-05-12 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat and write “@” to mention a contact
2. Select one contact and hit enter to mention from the suggestion list
3. Put the mentioned contact inside of “[]” and put a link inside of “()” next to it (e.g., “[[@nathan@gmail.com](https://edgeservices.bing.com/edgesvc/google.com)]([google.com](http://google.com/))”)
4. Click enter to post the comment
5. Hover over the mentioned contact as an anchor text and observe the link and the contact
6. Click on the mentioned contact as an anchor text

## Expected Result:
Mentioned contacts should not be used as an anchor text for a link to avoid link conflict.
## Actual Result:
Mentioned contacts can be used as an anchor text for a link and when hovered over, they show both the link and the contact. When clicked on, they open both the link on a new tab and the mentioned contact on RHN.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.13.1
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1703a401-c946-4a03-9b98-17165d41030a

https://github.com/Expensify/App/assets/43996225/731ec41d-5cf8-4b30-ba40-0b6cba9acadb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta and @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683805364578509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b600bbfaf5b9190</li>
        <li>Upwork Job ID: 1658749626727583744</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-05-13 14:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sending a message with mention inside a link markdown, the message will be converted to both mention and link. When you press it, it will open both the link and the user/personal detail.

### What is the root cause of that problem?
When we send a markdown message, it will be converted to html based on the rules defined in ExpensiMark. The rules will be executed from the top to bottom. Let see what happen when we send `[@bernhardoj](google.com)`. 

1. The first 3 rules are skipped. At the userMentions rule, it detects that we have a mention, that is `@bernhardoj`. The text now becomes `[<mention-user>@bernhardoj</mention-user>](google.com)`
https://github.com/Expensify/expensify-common/blob/5f4672c84e19122fc77b4bf1ac092d4919472112/lib/ExpensiMark.js#L74-L83

2. Then we will encounter a link rule which will convert the text to `<a href="google.com" target="_blank" rel="noreferrer noopener"><mention-user>@bernhardoj</mention-user></a>`
https://github.com/Expensify/expensify-common/blob/5f4672c84e19122fc77b4bf1ac092d4919472112/lib/ExpensiMark.js#L106-L126

We can see that we have 2 tag, link (anchor) and custom mention tag.
### What changes do you think we should make in order to solve the problem?


Don't convert the text to mention if it's in a link markdown.
1. We should change the order of the rules such as the email and link rule run first before mention rule (hereMentions and userMentions). 
2. Then, we will update the mention regex to not match if the text contains the closing tag of anchor (`</a>`).
`(?![^<]*<\/a>)` <- append this to the end of the regex for both hereMentions and userMentions.

Also, I find it's weird that we accept `(&#x60;|<code>|<pre>)` but later on in Str.isValidMention, we return false if the mention contains those characters. Instead of doing that, we can just prevent the regex to match in the first place like we do with anchor tag.

`(?![^<]*(<\/pre>|<\/code>|<\/a>))`

This is what we do on other rules too, for example:
https://github.com/Expensify/expensify-common/blob/5f4672c84e19122fc77b4bf1ac092d4919472112/lib/ExpensiMark.js#L134-L136

**Comment by bfitzexpensify** [comment] 2023-05-17 08:19
Reproduced

**Comment by bernhardoj** [comment] 2023-05-18 05:05
Yes, let's handle it in one PR

**Comment by arosiclair** [comment] 2023-05-19 17:59
Assigned @bernhardoj since he's handling this with that PR

**Comment by bfitzexpensify** [comment] 2023-06-01 08:57
@eVoloshchak bump to complete the BZ checklist

**Comment by eVoloshchak** [comment] 2023-06-01 17:43
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/expensify-common/pull/532
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/expensify-common/pull/532/files#r1213482401

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think additional discussion is needed, we already have an appropriate item in the reviewer checklist

-  Determine if we should create a regression test for this bug. We already have a couple of unit tests to catch this, no need for manual regression testing

**Closed** 2023-06-03 07:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
