### ISSUE TITLE
[HOLD for payment 2023-12-12] [hold for payment 2023-11-16] [$500] Chat - Skeleton placeholder flickers when opening chat with IOU in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30503] opened 2023-10-27 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing:** PR https://github.com/Expensify/App/pull/29643

**Version Number:** v1.3.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition:
- There must be a user with existing unpaid IOU.
- Log out and log in again and do not open the chat report with the user that has existing IOU.

1. Go offline.
2. Go to + > Request money > Manual.
3. Request money from the user in the precondition.
3. If there is no flickering, click on the IOU preview to open IOU report.

## Expected Result:
Skeleton placeholder should not flicker.

## Actual Result:
Skeleton placeholder flickers.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/464d0e3d-4b7c-49aa-b2a5-e2dc5c7f4fa0

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01caf37bfdd026bf43</li>
        <li>Upwork Job ID: 1717876350080266240</li>
        <li>Last Price Increase: 2023-10-27</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 27461954</li>
<li>paultsimura | Contributor | 27461958</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-27 14:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat: the top skeleton loader flickers when offline

### What is the root cause of that problem?
The root cause is that we run into an infinite loop of `Report.getOlderActions` API calls here:

https://github.com/Expensify/App/blob/7e06bd7e3b4940f20b30adf55decf10f58de1854/src/pages/home/report/ReportActionsView.js#L151-L165

### What changes do you think we should make in order to solve the problem?

We should make the actual API call only if we are online:

```diff
    const loadOlderChats = () => {
        // Only fetch more if we are not already fetching so that we don't initiate duplicate requests.
-        if (props.isLoadingOlderReportActions) {
+        if (isOffline || props.isLoadingOlderReportActions) {
            return;
        }

        const oldestReportAction = _.last(props.reportActions);

        // Don't load more chats if we're already at the beginning of the chat history
        if (oldestReportAction.actionName === CONST.REPORT.ACTIONS.TYPE.CREATED) {
            return;
        }
        // Retrieve the next REPORT.ACTIONS.LIMIT sized page of comments
        Report.getOlderActions(reportID, oldestReportAction.reportActionID);
    };
```

### What alternative solutions did you explore? (Optional)

**Comment by getusha** [comment] 2023-10-27 14:58
@paultsimura do you have any explanation on why this issue will not happen on web but only on native?

**Comment by paultsimura** [comment] 2023-10-27 15:20
@getusha this happens on the Web as well, it's just more difficult to catch: `loadOlderChats` is called on `InvertedFlatList.onEndReached`:

https://github.com/Expensify/App/blob/c9f0620b1854a1e7ac183474f43ce8260a4801a9/src/pages/home/report/ReportActionsList.js#L417

You need to make the screen on the web really short, so the `onEndReached` is triggered, and you'll see both the flickering and the loop in Network tab:


https://github.com/Expensify/App/assets/12595293/4e105b5d-829f-4735-b23f-bedd73dcc22c


Also, I've updated my proposal with some extra details.

**Comment by getusha** [comment] 2023-10-27 17:58
Thanks @paultsimura! tried applying your solution seems like i have an outdated branch, could you please your branch so i can test it?

**Comment by paultsimura** [comment] 2023-10-27 19:40
@getusha here it is: https://github.com/paultsimura/Expensify/tree/fix/30503-report-skeleton

**Comment by getusha** [comment] 2023-10-28 05:25
[Proposal](https://github.com/Expensify/App/issues/30503#issuecomment-1782978278) from @paultsimura works well and looks good to me.
🎀 👀 🎀 C+ Reviewed

**Comment by joekaufmanexpensify** [comment] 2023-10-30 13:50
Pending internal engineering sign off

**Comment by paultsimura** [comment] 2023-10-30 20:36
I've recently seen [a PR](https://github.com/Expensify/App/pull/28640) pending a review from @aldo-expensify for a month already. Just wanted to confirm he's not OOO at the moment

**Comment by aldo-expensify** [comment] 2023-10-30 21:04
I was OOO for 3 weeks, but I just came back today. I'm catching up with pending stuff, I'll try to review the PR today

**Comment by joekaufmanexpensify** [comment] 2023-10-31 17:32
TY!

**Comment by paultsimura** [comment] 2023-10-31 20:14
Thank you @aldo-expensify, would appreciate if you could give a look on this issue as well — it's waiting for your assignment 🙏🏼

**Comment by aldo-expensify** [comment] 2023-10-31 20:23
Thanks for pinging me again, I thought that the linked PR was all there was left to do hahaha

**Comment by paultsimura** [comment] 2023-10-31 20:48
Thanks. The PR is ready: https://github.com/Expensify/App/pull/30658

**Comment by joekaufmanexpensify** [comment] 2023-11-13 14:49
PR is out on production. Not sure why the automation didn't work. Payment is due (assuming no regressions) on 2023-11-16

**Comment by joekaufmanexpensify** [comment] 2023-11-16 14:40
Looks like a regression came up [here](https://github.com/Expensify/App/issues/31367#issuecomment-1813203571), @paultsimura / @getusha could you take a look?

**Comment by joekaufmanexpensify** [comment] 2023-11-20 14:10
Resolving regression in the above thread

**Comment by joekaufmanexpensify** [comment] 2023-11-27 14:59
Same

**Comment by joekaufmanexpensify** [comment] 2023-12-04 16:15
[PR](https://github.com/Expensify/App/pull/31492) fixing regression is out on staging.

**Comment by joekaufmanexpensify** [comment] 2023-12-12 14:53
[Bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1702392815281029) in Slack

**Comment by getusha** [comment] 2023-12-12 15:34
BugZero Checklist:

- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26166
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/26166/files#r1424177004
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- Determine if we should create a regression test for this bug. **No, this is a minor visual issue which will not affect any user flow.**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by joekaufmanexpensify** [comment] 2023-12-12 21:03
Great, TY! BZ checklist is complete. All set to issue payment.

**Comment by joekaufmanexpensify** [comment] 2023-12-12 21:07
We need to make the following payments here: 

- @paultsimura $50 for reporting. Paid via Upwork. 
- @paultsimura - $250 for PR (50% regression penalty applied). Paid via upwork. 
- @getusha - $250 for C+ review (50% regression penalty applied). Paid via upwork.

**Comment by joekaufmanexpensify** [comment] 2023-12-12 21:09
We need to make the following payments here:

- @paultsimura - $250 for PR (50% regression penalty applied). Paid via upwork.
- @getusha - $250 for C+ review (50% regression penalty applied). Paid via upwork.

**Comment by joekaufmanexpensify** [comment] 2023-12-12 21:11
@paultsimura $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-12-12 21:12
@getusha $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-12-12 21:12
All set. TY everyone!

**Closed by joekaufmanexpensify** 2023-12-12 21:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
