### ISSUE TITLE
[C+ Checklist Needs Completion] [$1000] Keyboard navigation and selection is inconsistent in Split Bill UI

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21392] opened 2023-06-23 11:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21310
## Action Performed:
1. Open http://staging.new.expensify.com/
2. Open Group DM
3. Click on "+" near message composer
4. Click on "Split bill"
5. Insert amount
6. Click "Next"
7. Click with mouse on any member to deselect it
8. Use the keyboard navigation (up/down arrows + enter) to select/deselect different members

## Expected Result:
User can successfully select/deselect members for split bill using keyboard navigation

## Actual Result:
Keyboard navigation starts working incorrectly while selecting/deselecting members if user clicked on one of the members before. When user press "enter" for any member - select checkmark immediately returns to previous state. Sometimes 2 members are selected / deselected instantly instead of 1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6d2377b0-542b-413f-a569-ace6dd03ea30

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b770640f03d0c88</li>
        <li>Upwork Job ID: 1672370582030045184</li>
        <li>Last Price Increase: 2023-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27885262</li>
<li>dukenv0307 | Contributor | 27885264</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-06-23 22:26
I reproduced this. Although the keyboard navigation seems fine to me, the "enter" functionality does seem to be buggy:


https://github.com/Expensify/App/assets/29386373/6ee10e32-ae85-413f-921a-c22d2b4be01e

**Comment by ygshbht** [comment] 2023-06-24 04:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue arises when the user navigates the Split Bill interface using keyboard commands. The selection and deselection of members using the up/down arrow keys and the enter key does not behave as consistently as one would expect.

### What is the root cause of that problem?
This problem could be stemming from how the keyboard events are being handled in the Split Bill UI. It seems the interface isn't fully optimized to respond to keyboard interactions as efficiently as it should.

### What changes do you think we should make in order to solve the problem?
I propose diving into the pertinent parts of the code, specifically files like src\pages\iou\SplitBillDetailsPage.js, and scrutinizing the event handlers tied to keyboard navigation. It's possible that refining these handlers or the state management associated with them can lead to the seamless keyboard-based user experience you're aiming for.

Let me assure you, with my experience and familiarity with similar issues, there's nothing unsolvable here. I am quite confident in delivering a robust solution that rectifies this issue and enhances the overall usability of the Split Bill UI.

**Comment by jeet-dhandha** [comment] 2023-06-25 12:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There are two problems here:
- When we are moving up/down the user is highlighted but the focus is not moved to that user.
- When we are selecting/deselecting the user the list is updated thus changing the user's order.


### What is the root cause of that problem?
- Selection focus is not moved to the user when we are moving up/down.
- The list is re-shuffled on each selection/deselection.

### What changes do you think we should make in order to solve the problem?
- First we should fix the selection focus issue.
- Then we should fix the list re-shuffling issue.

(I will update the code for these two when we finalise on how we want to handle this).

**Comment by mollfpr** [comment] 2023-06-26 15:10
Reviewing now

**Comment by mollfpr** [comment] 2023-06-28 01:32
It's better to fix the selection focus to be aligned with the options focus.

@dukenv0307 While preventing the browser selection selecting the option fixes this issue, but it will create another issue focused option is not selected on enter. We should find a way to keep our focus control so the browser can work together.

---

>I propose diving into the pertinent parts of the code, specifically files like src\pages\iou\SplitBillDetailsPage.js, and scrutinizing the event handlers tied to keyboard navigation. It's possible that refining these handlers or the state management associated with them can lead to the seamless keyboard-based user experience you're aiming for.

@ygshbht What changes do you suggest? We also have the same issue while selecting the members on the invite new member page.

---

> First we should fix the selection focus issue.

@jeet-dhandha How?

---

@c3024 Blurring the browser selection is not preventing both focused options from being selected. It's just dismissing the browser selection.

**Comment by mollfpr** [comment] 2023-06-28 02:13
> Only one option focused by keyboard gets selected on clicking Enter after blurring the active element.

I don't get what you mean. Could you elaborate? It's still a workaround. 

For now, the best solution is integrating browser selection and arrow key focus on the option item. We need to make sure that the browser accessibility is still can be used, so our focus control and selection.

**Comment by mollfpr** [comment] 2023-06-28 12:13
@dukenv0307 I don't understand why it's out of the scope of the ticket. 

When users access the option by pressing the tab and pressing enter, they expect the focused option should be selected.

**Comment by greg-schroeder** [comment] 2023-06-30 07:32
Proposals still under review

**Comment by greg-schroeder** [comment] 2023-07-05 23:20
Okay, got it. Holding.

**Comment by greg-schroeder** [comment] 2023-07-15 16:54
Still on hold

**Comment by greg-schroeder** [comment] 2023-07-31 14:03
Work on selection list refactor continues: https://github.com/Expensify/App/issues/11795

**Comment by greg-schroeder** [comment] 2023-08-09 23:05
""

**Comment by greg-schroeder** [comment] 2023-08-16 02:07
Same as above

**Comment by greg-schroeder** [comment] 2023-08-24 02:24
""

**Comment by greg-schroeder** [comment] 2023-08-29 11:00
""

**Comment by greg-schroeder** [comment] 2023-09-11 13:51
No update

**Comment by greg-schroeder** [comment] 2023-09-22 01:51
no update

**Comment by greg-schroeder** [comment] 2023-09-22 01:52
Okay #12668 is closed

**Comment by greg-schroeder** [comment] 2023-09-22 01:53
@mollfpr what do you think we should do with this now?

**Comment by greg-schroeder** [comment] 2023-09-25 06:49
Bump @mollfpr

**Comment by mollfpr** [comment] 2023-09-25 15:19
https://github.com/Expensify/App/assets/25520267/ee51efac-12f7-466b-9d79-9ce092d26c14

The issue is still reproducible on the latest `main`. The linked issue is closed but not yet fixed. Asking clarification in the main refactor issue https://github.com/Expensify/App/issues/11795#issuecomment-1733934610

**Comment by greg-schroeder** [comment] 2023-10-04 15:59
Okay so they said:

>Hey @mollfpr, not planned - Split Bill is not part of the refactor

**Comment by greg-schroeder** [comment] 2023-10-04 15:59
So, given that it's still reproducible and not going to be solved in the re-factor, I'll take this off hold.

**Comment by mollfpr** [comment] 2023-10-04 16:04
Sorry @greg-schroeder, I forgot to reply here 🙏

**Comment by greg-schroeder** [comment] 2023-10-10 16:24
Awaiting new proposals

**Comment by akamefi202** [comment] 2023-10-10 18:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selection/deselection starts working inconsistently while selecting/deselecting members using keyboard if the user mouse-clicked on a member before that.
Sometimes, 2 members are selected at once.
And sometimes, one is selected but another selected member is deselected at once.

### What is the root cause of that problem?
The root cause is that difference between selection focus and browser focus.
If the user highlights a member using up/down keys after clicking another member using mouse, the browser focus is still on the mouse-clicked member but the selection focus is on the highlighted member.

If the user presses "Enter" key at the moment, the highlighted member will be selected and mouse-clicked member will be deselected.
Because we have event handler for both selection & browser focus.
And those event handlers will be triggered at once.

https://github.com/Expensify/App/blob/0ef24c0cc644dcca6df7c467b2036522d168055c/src/components/OptionsSelector/BaseOptionsSelector.js#L213-L214

https://github.com/Expensify/App/blob/e559308678316aa7603795960c46f78d50372b53/src/components/OptionRow.js#L182-L183

### What changes do you think we should make in order to solve the problem?
I agree that we can align selection focus & browser focus.

https://github.com/Expensify/App/blob/1998fa35e7bcc217ca29757efb7a9fd364346988/src/components/OptionsSelector/BaseOptionsSelector.js#L64

We should update align browser focus to selection focus whenever `focusedIndex` is updated.

https://github.com/Expensify/App/blob/1998fa35e7bcc217ca29757efb7a9fd364346988/src/components/OptionRow.js#L180-L181

For this, we need get ref of rows for each index. We can get it from above part.
As a result, we can align browser focus to selection focus whenever `focusedIndex` is updated.

### What alternative solutions did you explore?
N/A

**Comment by akamefi202** [comment] 2023-10-11 18:19
@mollfpr @greg-schroeder Could you please review my proposal and let me know your opinion?

**Comment by mvtglobally** [comment] 2023-10-12 03:44
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2023-10-13 19:11
@mollfpr can you take a look at most recent proposal? ty!

**Comment by mollfpr** [comment] 2023-10-16 10:23
Sorry I'm running out of time. I will prioritize this tomorrow 🙏

**Comment by mollfpr** [comment] 2023-10-17 05:36
@akamefi202 The proposal looks good, but on the `0:51` when the user starts scrolling the list with the arrow key, the selection highlight should be dismissed. It doesn't look good when the user is using the arrow key, we keep the selection highlight from the browser tab.

**Comment by akamefi202** [comment] 2023-10-17 05:44
@mollfpr Yeah, that's okay. We can add below code inside `updateFocusedIndex` for it.
```
document.activeElement.blur();
```

**Comment by akamefi202** [comment] 2023-10-17 08:34
@bernhardoj 
>1. I don't think the below code is needed

Without this, two handlers will be called together if browser focus & selection focus exists at the same time.
One handler for browser focus and one handler for selection focus.
And I think that this is the main root cause of this issue.

>If you already align the browser TAB focus with the arrow key focus, there could only be one row focused at a time, right?

Yeah, we can align browser focus to selection focus.
But we can't align selection focus to browser focus.
So if user choose an item using TAB key, browser focus & selection focus would be different.

> 2. Blurring the current row will break the TAB navigation, instead you can just remove the blue outline for the list item ONLY.

Same with above. We can't align selection focus to browser focus.
If we remove the blue outline for the list, the user wouldn't able to recognize focused item when he selects an item using TAB key.

**Comment by akamefi202** [comment] 2023-10-17 13:54
@mollfpr I tried to find out other way too but I was not able to find it.
There are several pressable components in the screen such as check box, button, etc.
And only common part was `data-tag`.

**Comment by greg-schroeder** [comment] 2023-10-18 23:12
Hmm... so are we stuck based on https://github.com/Expensify/App/issues/21392#issuecomment-1766470992?

**Comment by mollfpr** [comment] 2023-10-20 02:27
>When focusedIndex changes, trigger .focus on that element so the browser will also focus on it.

@dukenv0307 I assume this will make the focus from the arrow-key have the highlight selection in the option item?

**Comment by akamefi202** [comment] 2023-10-20 07:30
>Do we have another way to do this? I'm afraid using the getAttribute to custom tag is future proof.

If we should not use custom tag, we can use `tagName`.
```
if (document.activeElement.tagName === 'DIV') {
    return;
}
```

**Comment by greg-schroeder** [comment] 2023-10-23 10:18
proposals still being worked on

**Comment by akamefi202** [comment] 2023-10-23 21:49
@mollfpr Could you please let me know your opinion? This is another possible way to prevent double event handler running.
If the browser focus is blur or it's on TextInput, it will return "BODY" or "INPUT".
The app should run the event handler of selection focus.
But if the browser focus is inside the list, it will return "DIV".
The app should run the event handler of browser focus.

https://github.com/Expensify/App/issues/21392#issuecomment-1772227043

**Comment by mollfpr** [comment] 2023-10-25 16:04
Sorry for the delay, I was focusing on another issue. I'll do the review again in the morning 🙏

**Comment by mvtglobally** [comment] 2023-10-27 00:42
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment] 2023-11-01 11:04
Any thoughts here @mollfpr?

**Comment by jaimishpatel5** [comment] 2023-11-01 12:43
https://github.com/Expensify/App/assets/20947611/11ede13e-d765-4dfa-96cc-ad46b6e874cc

**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**

- Clicking "Enter" key selects and unselects the user in group split bill

**What is the root cause of that problem?**

- We were passing shouldPreventDefaultFocusOnSelectRow always false

**What changes do you think we should make in order to solve the problem?**

in default props for OptionsSelector.js we should update shouldPreventDefaultFocusOnSelectRow to true.
const defaultProps = {
    onSelectRow: undefined,
    textInputLabel: '',
    placeholderText: '',
    keyboardType: 'default',
    selectedOptions: [],
    headerMessage: '',
    canSelectMultipleOptions: false,
    shouldShowMultipleOptionSelectorAsButton: false,
    multipleOptionSelectorButtonText: '',
    onAddToSelection: () => { },
    highlightSelectedOptions: false,
    hideSectionHeaders: false,
    boldStyle: false,
    showTitleTooltip: false,
    **//here//**
		**shouldPreventDefaultFocusOnSelectRow: true**
}

**What alternative solutions did you explore? [(Optional)**]()
none

**Comment by esh-g** [comment] 2023-11-01 13:37
# Proposal

## Please re-state the problem we are trying to solve
Clicking "Enter" key selects and unselects the user in group split bill

## What is the root cause of this problem?
The `OptionSelector` has a different focus system than the inbuilt browser one. This is caused due to the conflict between the two.

## What changes should be made to fix this?
We should prevent the default browser focus by passing the prop `shouldPreventDefaultFocusOnSelectRow` as `!Browser.isMobile()` in `MoneyRequestConfirmationList.js` here:
https://github.com/Expensify/App/blob/594551004f6d8e06beea6fc6dbd9f6a2166ab751/src/components/MoneyRequestConfirmationList.js#L554-L560

just like we do in other places like:
https://github.com/Expensify/App/blob/594551004f6d8e06beea6fc6dbd9f6a2166ab751/src/pages/RoomInvitePage.js#L227
https://github.com/Expensify/App/blob/594551004f6d8e06beea6fc6dbd9f6a2166ab751/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L292
https://github.com/Expensify/App/blob/594551004f6d8e06beea6fc6dbd9f6a2166ab751/src/pages/workspace/WorkspaceInvitePage.js#L276

## What alternative options did you explore?
Wherever we use the `shouldPreventDefaultFocusOnSelectRow`, we are using the `!Browser.isMobile()` as the value passed to it... So, I think we can refactor the code to have the default value of this prop set to `!Browser.isMobile()` in the list items itself in components like `BaseListItem.js` and `OptionRow.js`.

**Comment by esh-g** [comment] 2023-11-01 13:38
@jaimishpatel5's proposal was posted after mine in the dupe issue and the solution prosed in their proposal was same as mine.

**Comment by mollfpr** [comment] 2023-11-02 13:41
@jaimishpatel5 @esh-g I didn't find that the solution is working.

I'll re-review the proposal from @akamefi202 and @dukenv0307 again.

**Comment by mollfpr** [comment] 2023-11-07 13:03
Reviewing...

**Comment by mollfpr** [comment] 2023-11-07 14:33
>Modify [this line](https://github.com/Expensify/App/blob/8dba113c233c0a433e81a637ea6c28ca815b3f02/src/components/OptionsSelector/BaseOptionsSelector.js#L185), so that if the option row associated with the focusedIndex is currently the browser-focused element, we'll not trigger the selectFocusedOption (because the browser will already handle it)

@dukenv0307 Could you explain more about the plan for this?

**Comment by mollfpr** [comment] 2023-11-07 14:54
FYI: There's another case where clicking the option item triggers the browser focus, and it will be visible after pressing the arrow key to navigate through the options list.


https://github.com/Expensify/App/assets/25520267/e327e582-9515-44f8-9fbd-8007fad3187d

**Comment by esh-g** [comment] 2023-11-07 16:09
>FYI: There's another case where clicking the option item triggers the browser focus, and it will be visible after pressing the arrow key to navigate through the options list.

@mollfpr This is exactly what my proposal was aiming to fix...

**Comment by greg-schroeder** [comment] 2023-11-09 22:34
@mollfpr thoughts on https://github.com/Expensify/App/issues/21392#issuecomment-1799049426?

**Comment by mollfpr** [comment] 2023-11-10 08:00
@esh-g But the issue of double selection persists with your solution.

**Comment by greg-schroeder** [comment] 2023-11-13 09:31
bump @mollfpr

**Comment by mollfpr** [comment] 2023-11-15 15:46
Sorry for the delay 🙏

We seem already to handle the same issue for the `BaseSelectionList`, and it is better to use role instead of data-tag. @dukenv0307 provided an example of implementation. So I suggest to go with @dukenv0307 [proposal](https://github.com/Expensify/App/issues/21392#issuecomment-1605261940).

🎀 👀 🎀 C+ reviewed!

**Comment by greg-schroeder** [comment] 2023-11-20 18:28
Bump @joelbettner can you confirm the assignment above?

**Comment by greg-schroeder** [comment] 2023-11-26 19:46
Bump @joelbettner

**Comment by joelbettner** [comment] 2023-11-29 18:15
Sorry about that delay. I was OOO last week and battling some illness. Still catching up on things that I missed.

**Comment by greg-schroeder** [comment] 2023-12-19 01:27
Work continues on the linked PR - @mollfpr there's an outstanding question for you if you're able to take a look ASAP <3

**Comment by Pujan92** [comment] 2024-01-22 16:04
Not sure whether [this](https://github.com/Expensify/App/issues/34761) should be considered as a regression from this issue PR or not. [comment](https://github.com/Expensify/App/issues/34761#issuecomment-1899774122)

**Comment by mollfpr** [comment] 2024-01-24 15:43
Thanks @Pujan92 for the notice, I'll check it in the morning.

**Comment by mollfpr** [comment] 2024-01-25 15:33
I tested the changes on the PR https://github.com/Expensify/App/pull/32464, and yes, it did cause the issue here: https://github.com/Expensify/App/issues/34761.

The selected proposal and the root cause explanation indicate that we wrongly passed the component as a function, which makes the issue.

@greg-schroeder I'm not sure how we seeing this as a regression or a side effect of the improvement we did.

**Comment by greg-schroeder** [comment] 2024-01-25 20:07
@mollfpr Yeah I see what you're saying. While it was maybe caused by it, it's not really a regression in the traditional sense

**Comment by greg-schroeder** [comment] 2024-01-25 20:12
The upwork job for this closed a long time ago due to inactivity so I will create a new one

**Comment by greg-schroeder** [comment] 2024-01-25 20:15
Offers sent to @mollfpr and @dukenv0307 

Can you complete the checklist @mollfpr? Thanks!

**Comment by mollfpr** [comment] 2024-01-26 03:04
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 @mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

>[@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

>[@mollfpr] Determine if we should create a regression test for this bug.
[@mollfpr] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again


1. Create a group chat
2. Click on the plus icon > split bill
3. Enter the amount to go to confirm page
4. Click on the checkbox of one member
5. Use the arrow key to focus on another
6. Click enter key
7. Verify that the member which has the checkbox is focused is selected/de-selected
8. 👍 or 👎

**Comment by mollfpr** [comment] 2024-01-26 03:05
@greg-schroeder You can cancel the offer for me; I'll do a manual request in NewDot. Could you give me the payment summary? Thank you!

**Comment by greg-schroeder** [comment] 2024-01-26 18:35
Oh, woops, I forgot, I'll cancel the offer. 

@mollfpr is due $1k for this job

**Comment by greg-schroeder** [comment] 2024-01-26 18:37
Filed regression test, closing this out, I'll pay you right away once you accept offer @dukenv0307

**Closed by greg-schroeder** 2024-01-26 18:37 UTC
Labels: External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-01-26 20:54
$1,000 approved for @mollfpr based on [this comment](https://github.com/Expensify/App/issues/21392#issuecomment-1912512728).
