### ISSUE TITLE
[HOLD for payment 2023-09-27] [HOLD for payment 2023-09-06] [$1000]  Mention list doesnt automatically popup when typing @

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25649] opened 2023-08-22 03:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to staging new dot
2. Go to any chat
3. Type @ and observe that the mention list doesnt automatically pop-up but does when another key is stroked or even when going back to chat and opening chat

## Expected Result:
Mention list should automatically pop-up when typing @
## Actual Result: 
To pop-up mention key needs another key stroke either name suggestion, or going back to chat and coming back or typing space and back space
## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a4ff7cb3-d8a1-499e-9dff-82c49e2af715

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692674547623649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb30763071efa133</li>
        <li>Upwork Job ID: 1695188077897199616</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26373026</li>
<li>sofoniasN | Reporter | 26373029</li>
<li>WikusKriek | Contributor | 26649676</li>
</ul></li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2023-08-22 03:47
https://github.com/Expensify/App/pull/24512 related?

**Comment by techievivek** [comment] 2023-08-22 08:04
@WikusKriek Can you please push a PR to fix this regression and we can cherry pick it to staging, thanks.

**Comment by techievivek** [comment] 2023-08-22 09:24
@WikusKriek 

> While this fix of selectionEnd < 1 does solve the issue on other platforms

You meant to say that it is still broken on native ios?

**Comment by techievivek** [comment] 2023-08-22 09:45
I suggest we revert the main pull request (https://github.com/Expensify/App/pull/24512) and focus on finding a better solution for the original issue. Our goal is to ensure that all features work seamlessly across all platforms.

**Comment by techievivek** [comment] 2023-08-22 10:40
Thanks, @WikusKriek , for providing additional context. I agree that we should proceed with https://github.com/Expensify/App/pull/25660. Once it's merged and CP'ed, we can revisit the original issue and find a solution that works for iOS native.

**Comment by techievivek** [comment] 2023-08-22 10:41
Can you please fill the Author checklist in the PR?

**Comment by adelekennedy** [comment] 2023-08-22 15:55
we have a solution above - going to make this daily. @techievivek can we remove the `DeployBlockerCash' label as well?

**Comment by roryabraham** [comment] 2023-08-23 18:39
Not going to block deploy on this one.

**Comment by adelekennedy** [comment] 2023-08-25 19:49
quick check - this is no longer a deploy blocker and there's some discussion on if this is a regression from https://github.com/Expensify/App/issues/24265 I won't move this to external until we agree on the above @techievivek

**Comment by techievivek** [comment] 2023-08-25 21:10
Sorry for the late reply. I agree with Rajat's comment that this was fixed properly in the original PR but got broken due to some parallel developments. @WikusKriek reported the same in this comment https://github.com/Expensify/App/issues/25649#issuecomment-1687860733.

So this can be considered as a separate issue and we should be good to add the external label here.

**Comment by shubham1206agra** [comment] 2023-08-27 13:39
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Mention list doesn't automatically popup when typing @

### What is the root cause of that problem?

This is due to a bug in https://github.com/facebook/react-native/pull/35603.
For the first input, `_lastStringStateWasUpdatedWith` is `nil`. Due to this, if condition evaluates to false here.

https://github.com/facebook/react-native/blob/e5fe7b391c32dde10487060c2003de4554be91ab/packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.mm#L269

Which does not allow us to execute 
https://github.com/facebook/react-native/blob/e5fe7b391c32dde10487060c2003de4554be91ab/packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.mm#L270-L271

This makes onSelectionChange execute earlier for 1st input after mounting of `RNTextInput` than `onChangeText`, which makes `updateComment` fire after `calculateMentionSuggestion`.

Due to this, the value received in `calculateMentionSuggestion` is blank for the first input.

The correction can also be observed in the Fabric Architecture code.
https://github.com/facebook/react-native/blob/e5fe7b391c32dde10487060c2003de4554be91ab/packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm#L410

### What changes do you think we should make in order to solve the problem?

Correct this bug in the patch as observed in the Fabric code
```diff
- if (_lastStringStateWasUpdatedWith && ![_lastStringStateWasUpdatedWith isEqual:_backedTextInputView.attributedText]) {
+ if (![_lastStringStateWasUpdatedWith isEqual:_backedTextInputView.attributedText]) {
```

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-08-27 13:59
This worked even on iOS at the time of https://github.com/Expensify/App/pull/25660 merge.
Seems like recent PR caused this regression again. I suspect https://github.com/Expensify/App/pull/25758

**Comment by shubham1206agra** [comment] 2023-08-27 14:04
> While this fix of `selectionEnd < 1` does solve the issue on other platforms, #24512 still seems to be a problem. So on iOS native typing '@' does not open the suggestion list. @techievivek what is your thoughts on this?

@situchan See this comment

**Comment by situchan** [comment] 2023-08-27 14:07
@shubham1206agra see this comment as well - https://github.com/Expensify/App/pull/25660#issuecomment-1690385870
You can also check iOS video in Reviewer Checklist

**Comment by shubham1206agra** [comment] 2023-08-27 14:15
@situchan Looks like it was working on your device, as pointed out by you. Now I wonder why it worked on your device but not everyone else.

**Comment by situchan** [comment] 2023-08-27 14:19
ok, I confirmed reverting https://github.com/Expensify/App/pull/25758 fixes iOS issue.

<img width="1177" alt="Screenshot 2023-08-27 at 8 18 53 PM" src="https://github.com/Expensify/App/assets/108292595/24345b35-f873-4da8-abc9-9142e827c985">

0acef6d doesn't work, 68a9fcd works

cc: @mountiny  @hannojg

**Comment by mountiny** [comment] 2023-08-27 17:00
@situchan we dont plan to revert that PR as its been a big refactor.

However, this issue was created before this PR was merged on Friday so lets just aim to fix this in main again. @WikusKriek any ideas for a fix? Otherwise @hannojg will look on monday cc @rushatgabhane @narefyev91

**Comment by situchan** [comment] 2023-08-27 17:01
> @situchan we dont plan to revert that PR as its been a big refactor.

Sure thing! Just tagging you so to determine next step

**Comment by shubham1206agra** [comment] 2023-08-27 17:16
@mountiny would like to see my proposal?

**Comment by mountiny** [comment] 2023-08-27 17:42
It would be interesting to me that the rootcause would be RN bug when this was re-introduced by the refactoring. Is there a solution without a patch?

This patch is in the native binary so we would have to be rebuilding the binary to apply it (as we do now but we are pushing to get the remaining patches out in RN 0.73 and we would not have to do this anymore as its slowing down the Android build times _a lot_). Is that correct?

I would wait for @hannojg to check out the proposal and the issue before moving ahead

**Comment by situchan** [comment] 2023-08-27 21:13
> This doesn't make sense to me. The issue is reproducible on staging but #25758 isn't deployed to staging.

https://github.com/Expensify/App/pull/25660 which fixed this issue wasn't deployed yet to staging too

**Comment by shubham1206agra** [comment] 2023-08-28 06:34
Reimplementing changes from https://github.com/Expensify/App/pull/25660 didn't fix the issue for me.
This is what I have done

In `ComposerWithSuggestions`

```js
const onSelectionChange = useCallback(
        (e) => {
            console.log('onSelectionChange fired');
            // if (suggestionsRef.current.onSelectionChange(e)) {
            //     return;
            // }

            setSelection(e.nativeEvent.selection);
        },
        [/*suggestionsRef*/],
    );

    useEffect(() => {
        suggestionsRef.current.onSelectionChange(selection.end);
    }, [selection.end, suggestionsRef]);
```

In `SuggestionMention`. Similar for `SuggestionEmoji`

```js
const onSelectionChange = useCallback(
        (e) => {
            console.log('onSelectionChange2', e);
            // calculateMentionSuggestion(e.nativeEvent.selection.end);
            calculateMentionSuggestion(e);
        },
        [calculateMentionSuggestion],
    );
```

Result (Please see the logs on Metro carefully when changing input)

Uploading Screen Recording 2023-08-28 at 12.00.18 PM.mov…

**Comment by shubham1206agra** [comment] 2023-08-28 06:37
@rushatgabhane I think https://github.com/Expensify/App/issues/25649#issuecomment-1695109068 should cover your video

**Comment by shubham1206agra** [comment] 2023-08-28 06:40
@situchan Am I missing something in this? https://github.com/Expensify/App/issues/25649#issuecomment-1695109068

**Comment by shubham1206agra** [comment] 2023-08-28 09:50
@WikusKriek I do have question about using `useEffect` for `calculateMentionSuggestion`. 

Why does https://github.com/Expensify/App/issues/25649#issuecomment-1695109068 does not fix the problem but your solution does fix this?
My interpretation is that your solution is highly dependent on the timing of updating of `selection` prop in `SuggestionMention` component. Can you tell me why this solution has guaranteed to run after `onChangeText` (or `updateComment`) has executed?

**Comment by hannojg** [comment] 2023-08-28 09:57
Looking into this …

**Comment by hannojg** [comment] 2023-08-28 10:13
Try removing `selectionEnd < 1`, it will also continue to work for the use case you were describing

**Comment by hannojg** [comment] 2023-08-28 10:15
Thanks for the ref! Do you agree that this code can be removed?

**Comment by hannojg** [comment] 2023-08-28 10:20
Ah awesome okay, can we go ahead with this change then?

**Comment by shubham1206agra** [comment] 2023-08-28 10:35
@hannojg Another solution I can come up with is changing RNTextInput code for iOS in `RNTextInput.js` file for correction of order for first input. Maybe a little complicated but will fix for every TextInput. Wdyt?

**Comment by hannojg** [comment] 2023-08-28 10:37
You mean the call order of `onSelectionChange` and `onChangeText`, so its the same order on android and iOS?

I do like that it's equal on both platforms, but would be afraid that we have code somewhere that works on the assumption that is different on iOS / android. (If that's not the case I would be cool with the change)

**Comment by shubham1206agra** [comment] 2023-08-28 10:39
> You mean the call order of `onSelectionChange` and `onChangeText`, so its the same order on android and iOS?
> 
> I do like that it's equal on both platforms, but would be afraid that we have code somewhere that works on the assumption that is different on iOS / android. (If that's not the case I would be cool with the change)

Not right now, for first input in iOS cause there is RN bug.

> Also by saying that you are pointing out that the issue on iOS is that onSelectionChange gets called before onTextChange right?

Yes, but only for first input

**Comment by shubham1206agra** [comment] 2023-08-28 10:43
@hannojg Easiest would be to use patch till RN 0.73 and hopefully we can migrate to Fabric Architecture before that. (This issue is already fixed for Fabric Architecture)

**Comment by hannojg** [comment] 2023-08-28 10:44
So imo, the cleanest approach to this would be:

- Remove the `selectionEnd < 1` fix
- Fix our `RNTextInput.js` wrapper so that the order of events is the same on each platform

**Comment by shubham1206agra** [comment] 2023-08-28 10:45
Can I take this issue in this case then?

**Comment by hannojg** [comment] 2023-08-28 10:48
That's not on me to decide, I am an external engineer 😅  Maybe @mountiny or @rushatgabhane can help settle here on a decision?
Maybe you could create a proposal that includes the full solution (removing the if condition + the text input fix)

**Comment by shubham1206agra** [comment] 2023-08-28 10:49
> That's not on me to decide, I am an external engineer 😅 Maybe @mountiny or @rushatgabhane can help settle here on a decision? Maybe you could create a proposal that includes the full solution (removing the if condition + the text input fix)

Ok let me update my proposal in that case

**Comment by shubham1206agra** [comment] 2023-08-28 11:48
> Remove the selectionEnd < 1 condition (as its not needed anymore)
@hannojg This condition is used to run `resetSuggestions();` to reset the object on clearing input ig. Not completely sure

**Comment by shubham1206agra** [comment] 2023-08-28 11:58
Tbh I kinda now hate the idea of fixing the execution order in `RNTextInput.js` as this approach requires creating a copy of the `event` object (deep copy not allowed, only shallow copy).  Without this, this error would be thrown

```
 ERROR  Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://reactjs.org/link/event-pooling for more information.
```

**Comment by shubham1206agra** [comment] 2023-08-28 11:59
> @hannojg Easiest would be to use patch till RN 0.73 and hopefully we can migrate to Fabric Architecture before that. (This issue is already fixed for Fabric Architecture)

I would still prefer the original idea

**Comment by techievivek** [comment] 2023-08-28 12:02
@hannojg @WikusKriek The iOS issue seems to be resolved by this PR: https://github.com/Expensify/App/pull/25660. Is there anything left to address here? Are we discussing some further improvements here? Given that @WikusKriek has already worked on this issue, we can ask @WikusKriek to submit another PR for any additional improvements needed here?

**Comment by hannojg** [comment] 2023-08-28 12:08
@shubham1206agra how does the code to fix the event order look like

@techievivek The bug is again present on the main branch due to recent refactors of the ReportActionCompose, and we are discussing how to fix it properly.

**Comment by shubham1206agra** [comment] 2023-08-28 12:10
Looks like this

```js
import React, {useEffect, useRef} from 'react';
import _ from 'underscore';
// eslint-disable-next-line no-restricted-imports
import {TextInput, Platform} from 'react-native';
import Animated from 'react-native-reanimated';
import PropTypes from 'prop-types';

const propTypes = {
    /** A ref to forward to the text input */
    forwardedRef: PropTypes.func,
};

const defaultProps = {
    forwardedRef: () => {},
};

// Convert the underlying TextInput into an Animated component so that we can take an animated ref and pass it to a worklet
const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

let resolveIsReadyPromise;
let isReadyPromise = new Promise((resolve) => {
    resolveIsReadyPromise = resolve;
});

function setIsReady() {
    resolveIsReadyPromise();
}

function resetPromise() {
    isReadyPromise = new Promise((resolve) => {
        resolveIsReadyPromise = resolve;
    });
}

function RNTextInput(props) {
    const isFirstInput = useRef(true);
    useEffect(() => {
        if (Platform.OS === 'ios') {
            return resetPromise;
        }
        setIsReady();
        return resetPromise;
    }, []);
    return (
        <AnimatedTextInput
            allowFontScaling={false}
            ref={(ref) => {
                if (!_.isFunction(props.forwardedRef)) {
                    return;
                }
                props.forwardedRef(ref);
            }}
            // eslint-disable-next-line
            {..._.omit(props, ['onChangeText', 'onSelectionChange'])}
            onChangeText={(text) => {
                if (!_.isFunction(props.onChangeText)) {
                    return;
                }
                if (isFirstInput.current && Platform.OS === 'ios') {
                    isFirstInput.current = false;
                    props.onChangeText(text);
                    setIsReady();
                    return;
                }
                props.onChangeText(text);
            }}
            onSelectionChange={(event) => {
                if (!_.isFunction(props.onSelectionChange)) {
                    return;
                }
                const eventCopy = {...event};
                isReadyPromise.then(() => props.onSelectionChange(eventCopy));
            }}
        />
    );
}

RNTextInput.propTypes = propTypes;
RNTextInput.defaultProps = defaultProps;
RNTextInput.displayName = 'RNTextInput';

export default React.forwardRef((props, ref) => (
    <RNTextInput
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...props}
        forwardedRef={ref}
    />
));
```

**Comment by techievivek** [comment] 2023-08-28 12:18
@hannojg 
> The bug is again present on the main branch due to recent refactors of the ReportActionCompose, and we are discussing how to fix it properly.

I see, thanks for the context.

**Comment by shubham1206agra** [comment] 2023-08-28 12:20
> event.persist()

This worked but I hope this does not cause any issue in the future.

**Comment by mountiny** [comment] 2023-08-28 14:11
I will leave this one for Vivek now to focus on issues I am assigned to, I would just say:
- I cant reliable reproduce this bug on main
- We should really aim to avoid RN patches as we want to use clean RN version as soon as possible to allow for fast builds

**Comment by situchan** [comment] 2023-08-28 14:17
> @hannojg @WikusKriek The iOS issue seems to be resolved by this PR: #25660. Is there anything left to address here? Are we discussing some further improvements here? Given that @WikusKriek has already worked on this issue, we can ask @WikusKriek to submit another PR for any additional improvements needed here?

I suggest @WikusKriek to submit another PR and I take C+ again as we were assigned/reviewed already in previous PR.

**Comment by techievivek** [comment] 2023-08-28 16:52
@WikusKriek, can you confirm if this issue still exists on the main? If so, could you please post an updated proposal to fix it? @situchan, let's also review @shubham1206agra's's proposal, as he has expressed interest in working on this and we want to address the issue properly.

**Comment by situchan** [comment] 2023-09-04 06:29
@WikusKriek can you please share permal link where you're going to add that effect? I assume SuggestionMention component but selection prop doesn't exist there.

**Comment by situchan** [comment] 2023-09-04 07:38
ok, @WikusKriek's [proposal](https://github.com/Expensify/App/issues/25649#issuecomment-1696147595) looks good but we may still hold this until merge freeze is over.
cc: @techievivek

**Comment by shubham1206agra** [comment] 2023-09-04 07:44
@situchan What about this comment?
https://github.com/Expensify/App/issues/25649#issuecomment-1695429729

**Comment by situchan** [comment] 2023-09-04 07:47
@hannojg what's your thought on [this solution](https://github.com/Expensify/App/issues/25649#issuecomment-1696147595)? Asking since you huge refactored composer.
Test branch: https://github.com/Expensify/App/commit/a63c31811d6904fe962d72e84007333a02f52827

**Comment by techievivek** [comment] 2023-09-11 07:23
@situchan Merge freeze is over now, do we have a proposal that we can go with?

**Comment by situchan** [comment] 2023-09-11 07:31
> @situchan Merge freeze is over now, do we have a proposal that we can go with?

yes, https://github.com/Expensify/App/issues/25649#issuecomment-1704765938

**Comment by situchan** [comment] 2023-09-18 12:38
Actually, I think we fixed "2 issues" here and made double efforts.
- First issue successfully done by us. also applies speed bonus
- And then another PR (big composer refactor) caused regression (not by us), which is "2nd issue"
- "2nd issue" successfully done by us. I think this also applies speed bonus (C+ approved in time. Just 2 hrs delay from merge internally)

This is the bounty reconsideration I'd suggest:
- 1k + 0.5k for the first PR done (including urgency bonus)
- 0.5k bonus for the 2nd PR done (after refactor, solution also differs from original one though is similar)

Total: 2k

cc: @techievivek

**Comment by techievivek** [comment] 2023-09-20 09:29
@situchan 

> Actually, I think we fixed "2 issues" here and made double efforts.

Can you share the 2 PRs that you mentioned above? @WikusKriek is already being paid separately for this issue https://github.com/Expensify/App/issues/24265, right?

**Comment by situchan** [comment] 2023-09-20 10:27
> Can you share the 2 PRs that you mentioned above?

@techievivek
- https://github.com/Expensify/App/pull/25660 (before composer refactor)
- https://github.com/Expensify/App/pull/27327 (after composer refactor)

**Comment by techievivek** [comment] 2023-09-20 10:52
Thanks for the links. Just to confirm, the fix for iOS was not included in https://github.com/Expensify/App/pull/25660, right? According to the description in the PR, `Suggestion list will display when opening chat and typing @ on all platforms except iOS native.`. This can also be confirmed from the screen recordings for iOS. So, I would treat this as a single fix for all the platforms.

**Comment by techievivek** [comment] 2023-09-20 10:53
Let me know if I am missing anything here.

**Comment by situchan** [comment] 2023-09-20 11:03
iOS fix was included in #25660 but composer refactor caused regression of iOS only, not affected other platforms.
So we fixed iOS issue again in #27327

**Comment by adelekennedy** [comment] 2023-09-29 05:28
Can I make sure I understand where we are here?
@situchan and @WikusKriek you'd like for us to include the speed bonus for this issues as we there were actually two PRs or, are you asking to be paid out for two issues?

**Comment by situchan** [comment] 2023-09-29 07:16
Waiting for confirmation from @techievivek on https://github.com/Expensify/App/issues/25649#issuecomment-1723324712

**Comment by techievivek** [comment] 2023-10-16 11:13
@adelekennedy The summary over here https://github.com/Expensify/App/issues/25649#issuecomment-1723324712 looks correct. @WikusKriek has also linked the PRs that were created in the process https://github.com/Expensify/App/issues/25649#issuecomment-1751689413.

**Comment by adelekennedy** [comment] 2023-10-16 15:46
How much is due in that case 😅 I agree the speed bonus is due in this case but we don't have guidance on paying anything additional:

### Payouts due:

Issue Reporter: $50 @SofoniasN
Contributor: $1500 @WikusKriek 
Contributor+: $1500 @sobitneupane 

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/nx/wm/offer/26373026).

**Comment by SofoniasN** [comment] 2023-10-17 04:01
Hey @adelekennedy this issue was created before the price change policy and i believe is eligible for the original reporter bonus payment. TIA

**Comment by adelekennedy** [comment] 2023-10-17 15:48
@SofoniasN amended my comment above

**Comment by situchan** [comment] 2023-10-17 15:51
@techievivek can you please double confirm amount with @adelekennedy? Thanks

**Comment by adelekennedy** [comment] 2023-10-24 17:04
@techievivek bump on this please

**Comment by SofoniasN** [comment] 2023-11-02 14:53
@adelekennedy slight bump

**Comment by techievivek** [comment] 2023-11-02 15:12
@adelekennedy 
> How much is due in that case 😅 I agree the speed bonus is due but we don't have guidance on paying anything additional:


It would be 2k.
First PR: 1k for fix + 500 for the bonus.
Second PR: 500 for the fix.

**Comment by adelekennedy** [comment] 2023-11-07 22:23
back from ooo 

### Payouts due:

Issue Reporter: $250 @SofoniasN - Upwork
Contributor: $2000 @WikusKriek - Upwork
Contributor+: $2000 @situchan - Upwork

Eligible for 50% #urgency bonus? Y

**Closed** 2023-11-20 23:03 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
