### ISSUE TITLE
[Awaiting checklist] [$250] LHN - LHN disappears upon leaving a public room / back button isn't redirecting to LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40680] opened 2024-04-22 10:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62.17
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR:** https://github.com/Expensify/Expensify/issues/318139
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/r/8813851443373010
2. Log in with a new Gmail account
3. Leave the room

Or

1. Have a room on some policy
2. Join that room
3. in new tab, deeplink to that room
4. Leave it

## Expected Result:
LHN should still be visible.

## Actual Result:
LHN disappears upon leaving a public room. It returns if the page is refreshed.
On mWeb, iOS and Android you're unable to use the "<" button to go to the LHN from Concierge after leaving the room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f26a5c5c-28b9-46ee-9b68-9db32fd168a9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4dd40ad35562892</li>
        <li>Upwork Job ID: 1782375600407408640</li>
        <li>Last Price Increase: 2024-04-22</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-22 10:46
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-22 10:46
We think this issue might be related to the #cvip-vsb.

**Comment by izarutskaya** [comment] 2024-04-22 10:47
Production 


https://github.com/Expensify/App/assets/115492554/f13f8798-fb14-4c2a-9bdf-b8ce6012ea41

**Comment by twisterdotcom** [comment] 2024-04-22 11:41
Okay, I recreated this here:

https://github.com/Expensify/App/assets/9133401/f5a784a2-95fd-46dd-8618-52b87a116854

But I have since recreated it on staging with my normal account, doesn't have to be new, or only have 1 other chat in the LHN. Simply put, leaving a room is broken on staging. It removes the LHN AFAIK if the room is left just after joining.

**Comment by twisterdotcom** [comment] 2024-04-22 11:46
I have no idea why though cc @Beamanator. Maybe this one from @MonilBhavsar? https://github.com/Expensify/App/pull/35671.

Maybe something to do with leaving groups cc @marcaaron?

**Comment by twisterdotcom** [comment] 2024-04-22 11:47
Going to make it External to see if we can get a quick fix and some C+ eyes anyway.

**Comment by twisterdotcom** [comment] 2024-04-22 11:48
@cubuspl42 would love your help looking for the offending PR here too. Definitely seems like a regression.

**Comment by MonilBhavsar** [comment] 2024-04-22 13:35
https://github.com/Expensify/App/pull/35671 doesn't seem like a offending PR

**Comment by MonilBhavsar** [comment] 2024-04-22 13:39
Okay, while checking if our PR has caused this, I think I found the issue...

**Comment by mallenexpensify** [comment] 2024-04-24 00:04
@Pujan92 reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks
Please review the PR 
- https://github.com/Expensify/App/pull/40701

**Comment by Pujan92** [comment] 2024-04-24 10:48
@izarutskaya @twisterdotcom Can you plz recheck on staging whether this issue is still reproducible or not

**Comment by twisterdotcom** [comment] 2024-04-24 10:56
Nice! It's fixed!

**Comment by MonilBhavsar** [comment] 2024-04-25 13:33
I'm able to reproduce this locally with reproduction steps - 

1. As an admin create a workspace
2. Add two users A and B to the workspace
3. Login as User A and open policy Expense chat and mention user B and invite them
4. As a user B, open user's B policy expense chat
5. Leave the room and 💥

**Comment by MonilBhavsar** [comment] 2024-04-25 13:41
@Pujan92 can you please help here by taking a look. My PR seems to fix this issue

**Comment by Pujan92** [comment] 2024-04-25 13:49
Sure @MonilBhavsar, I will try to reproduce with the mentioned steps and will check the PR soon.

**Comment by MonilBhavsar** [comment] 2024-04-25 13:51
Thanks! Since the root cause is same. May be the original issue is also still reproducible 😄

**Comment by Pujan92** [comment] 2024-04-25 16:02
Able to reproduce sometimes and your PR changes make sense to me. Can you plz reopen it?

https://github.com/Expensify/App/assets/14358475/bcc5d955-58f7-4758-8cbe-f1b7bceee08d

**Comment by MonilBhavsar** [comment] 2024-04-25 16:37
Thanks for confirming! Reopened PR

**Comment by Beamanator** [comment] 2024-05-22 09:39
This looks like it's been ready for payment for a bit @twisterdotcom ? :D

**Comment by Pujan92** [comment] 2024-06-13 12:18
Bump @twisterdotcom for the payment if we are not considering the issue https://github.com/Expensify/App/issues/41128 as a regression from here.

**Comment by twisterdotcom** [comment] 2024-06-13 23:21
https://github.com/Expensify/App/issues/42073#issuecomment-2166943047

**Comment by twisterdotcom** [comment] 2024-06-14 13:51
### Payment Summary
[Upwork Job](https://www.upwork.com/nx/wm/offer/new/13153917)
- Reviewer: @pujan92 paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/new/13153917)

**Comment by twisterdotcom** [comment] 2024-06-14 13:51
LMK if this needs a regression test.

**Comment by Pujan92** [comment] 2024-06-15 13:27
### Regression Test Steps

1. Copy any public room URL and signout
2. Visit the copied URL and sign in
3. Leave that public room
4. Verify the LHN isn't disappear

**Closed** 2024-06-17 09:15 UTC
Labels: Engineering, Weekly, Internal, Bug
