### ISSUE TITLE
[$500] Members - Workspace Member List Page Stuck in Forever Loading State After Inviting New Members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29762] opened 2023-10-17 12:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697477533816919

## Action Performed:
1. Login to any account
2. Go to Account Settings.
3. Open any Workspace (or create a new one).
4. Click on Members >> Invite.
5. Type an not-existing email with the domain @‌[applause.expensifail.com](http://applause.expensifail.com/), for example: toansel@applause.expensifail.com
6. Send the invite >> there will be a error message
7. Go to the #announce room and confirm that the invited email from step #5 is added to the member list.
8. Logout and then log in again.
9. Again, navigate to Account Settings >> Workspace >> Members.
10. Observed: The Workspace’s member list keeps loading indefinitely.

## Expected Result:
Expected Result: .
1. The Workspace's member list should load and display without any issues, as the invited email has already been added as a member in the #announce room.
2. Alternatively, if there is an issue, the invited email should not be added as a new member.

## Actual Result:
The Workspace's member list keeps loading indefinitely.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/d23506eb-eef4-4274-a461-d009cac35214

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/19564189-1c2c-4602-89aa-04194c0d6b3e

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/1b1b2b05-b71e-42e1-937f-35489836e4b8

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9987026b-5559-4b75-a5ae-f94f97327c30

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

  

https://github.com/Expensify/App/assets/93399543/7a84be25-d59a-46ce-8aee-df752df6906a

https://github.com/Expensify/App/assets/93399543/f6edb6e8-89a9-4ba8-bb5b-3a7d32e5a186

https://github.com/Expensify/App/assets/93399543/c75ce756-00cc-4a05-8c91-91d960ae1bbf

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/5b3bc6a9-664c-4742-8dd9-f4136eb55414

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171cf99eaf358016e</li>
        <li>Upwork Job ID: 1714258626307084288</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by s-alves10** [comment] 2023-10-17 13:52
This looks like a backend issue

![image](https://github.com/Expensify/App/assets/126839717/5aa03620-9edb-43e6-bc16-3bef63c9cd2a)

The backend should return valid data

**Comment by s-alves10** [comment] 2023-10-18 12:16
@jjcoffee 

![image](https://github.com/Expensify/App/assets/126839717/af0f6b48-b722-47ad-b1d7-08ebe7c44977)

**Comment by alexpensify** [comment] 2023-10-20 21:14
@jjcoffee - what's the plan here? Do you agree with this feedback?

**Comment by jjcoffee** [comment] 2023-10-23 17:48
@alexpensify Confirmed that this is a BE issue!

**Comment by youssef-lr** [comment] 2023-10-26 17:27
Yeah I can reproduce this. I'll work on a fix tomorrow!

**Comment by youssef-lr** [comment] 2023-10-30 15:56
Still on it, haven't been able to finish the PR yet.

**Comment by alexpensify** [comment] 2023-11-01 18:43
Thanks for the update @youssef-lr!

**Comment by alexpensify** [comment] 2023-11-03 16:37
@youssef-lr I'm going to assign you as the primary person in this GH for now.

**Comment by alexpensify** [comment] 2023-11-07 00:23
@youssef-lr any update here?

**Comment by youssef-lr** [comment] 2023-11-09 19:26
Working on this one this week.

**Comment by youssef-lr** [comment] 2023-11-15 05:21
I couldn't get to this and I'm going OOO tomorrow, can we get this reassigned please @alexpensify? If it's not urgent, I can work on this once I'm back.

**Comment by alexpensify** [comment] 2023-11-16 20:46
Ok, we will need to wait until you are back online then.

**Comment by alexpensify** [comment] 2023-11-29 19:43
Still waiting on @youssef-lr here, no update.

**Comment by alexpensify** [comment] 2023-12-06 18:57
@youssef-lr are you able to pick this one back up?

**Comment by alexpensify** [comment] 2023-12-13 23:08
Thanks for the update!

**Comment by youssef-lr** [comment] 2023-12-22 08:54
I'm gonna have some free time to work on this on Monday.

**Comment by alexpensify** [comment] 2023-12-23 18:48
Thank you @youssef-lr! 

**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by youssef-lr** [comment] 2024-01-02 22:07
No update yet, I'm still on it. I should have an update by EOW or early next one.

**Comment by youssef-lr** [comment] 2024-01-15 01:50
Ok I made some progress. It looks like this only happens in controlled domains, when a domain is validated, only the admin of the domain will be able to invite someone to a workspace from the domain. This is because only the admin is able to invite members and in the process create accounts for them that are not in the closed state.

I think this is by design, but we probably need to figure out how to show a cleaner error in this case, or even find another solution to make this possible. I'll start a discussion in #eng-chat on Monday to get some input.

**Comment by youssef-lr** [comment] 2024-01-31 18:23
Resuming work on this one this week.

**Comment by youssef-lr** [comment] 2024-02-11 21:32
PR's ready.

**Comment by youssef-lr** [comment] 2024-02-15 10:22
We're all set here.

**Comment by tranvantoan-qn** [comment] 2024-02-15 10:34
@youssef-lr What about the reporting bonus, maybe we missed it?

**Comment by youssef-lr** [comment] 2024-02-16 12:43
My bad sorry. @alexpensify I think we need to pay the reporting bonus here.

**Comment by alexpensify** [comment] 2024-02-16 16:44
Heads up, I'm OOO until Tuesday and will review this request then.

**Comment by alexpensify** [comment] 2024-02-20 23:54
I'm still catching up from being OOO-- I need another day to review this one.

**Comment by alexpensify** [comment] 2024-02-21 22:38
@tranvantoan-qn - please accept the proposal in Upwork and I can complete the payment process there. Thanks! 

https://www.upwork.com/jobs/~0186ed4230f672bcfe

**Comment by tranvantoan-qn** [comment] 2024-02-22 01:50
@alexpensify I have accepted the offer, thank you!

**Comment by alexpensify** [comment] 2024-02-22 15:48
All set here @tranvantoan-qn has been paid via Upwork! Closing!

**Closed by alexpensify** 2024-02-22 15:48 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
