### ISSUE TITLE
[Help Wanted] Non-admin approvers can change the report workspace for Approved reports on OldDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41147] opened 2024-04-27 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714132204273809

## Action Performed:
Pre-req: Setup Collect or Control workspace with Submit & Approve - set the approver as an employee, not an admin.
Action Performed:
Employee A submits a report to Employee B
Employee B approves report
Employee B clicks the details on the Report in OldDot

## Expected Result:

- Report workspace should show the actual workspace it’s on
- Report workspace shouldn’t be editable if Employee B isn’t an admin

## Actual Result:

- Report workspace shows a list of workspaces Employee B is an admin on, not the workspace the report is on.
- Employee B can change the workspace even though they aren’t an admin on the existing workspace

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/12f0db12-5e67-4039-bb9e-3a82573bad7a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b52ee6aaf74a66ca</li>
        <li>Upwork Job ID: 1784915027341197312</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2024-05-02 04:28
Internal and waiting to be picked up.

**Comment by strepanier03** [comment] 2024-05-07 22:36
Internal still and waiting to be picked up.

**Comment by strepanier03** [comment] 2024-05-16 00:04
Still looking for ownership and pickup.

**Comment by strepanier03** [comment] 2024-05-21 20:16
I'll retest this and see if it's still happening, then close if it's not.

**Comment by strepanier03** [comment] 2024-05-21 20:23
Yes, this is still occurring as documented. 

<img width="1438" alt="image" src="https://github.com/Expensify/App/assets/10925636/f6ae34cd-7fe4-4182-babf-59baaa7b08e3">

**Comment by strepanier03** [comment] 2024-05-29 21:08
Labeled internally and waiting for ownership and prioritization.

**Comment by strepanier03** [comment] 2024-06-10 21:26
Back from OoO, this looks ready to be picked up by anyone with free cycles, holding still.

**Comment by strepanier03** [comment] 2024-06-13 23:31
Waiting for ownership.

**Comment by strepanier03** [comment] 2024-06-18 02:22
Help wanted.

**Comment by strepanier03** [comment] 2024-06-20 20:44
Held for ownership.

**Comment by strepanier03** [comment] 2024-06-24 18:33
Still looking for someone to pick up, I'm setting weekly because I'm tired of updating for the sake of no update.

**Comment by strepanier03** [comment] 2024-07-03 00:14
Waiting for ownership.

**Comment by mvtglobally** [comment] 2024-07-11 03:43
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment] 2024-07-16 00:14
Thanks @mvtglobally - Will continue to follow future testing and likely close if non-repro still.

**Comment by mvtglobally** [comment] 2024-07-19 03:11
Issue not reproducible during KI retests. (Second week)

**Comment by strepanier03** [comment] 2024-07-24 19:34
Going to close this out as non-repro. We can reopen if needed.

**Closed by strepanier03** 2024-07-24 19:34 UTC
Labels: Weekly, Internal, Help Wanted, Overdue, Bug
