### ISSUE TITLE
[$250] "x" navigates back to the previous page when use URL to access members page 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8723] opened 2022-04-21 05:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login in NewDot
2. Go to your workspace's member RHN
3. Copy the url (should look like /workspace/XXXXXXXXXX/members)
4. Open the URL in a new tab
5. Close the RHN, it will take you out of NewDot

## Expected Result:
Sidebar should be dismissed

## Actual Result:
Instead of the sidebar being dismissed, you are taken back to the page you were at before.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.55-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Kapture 2022-04-19 at 16 10 02](https://user-images.githubusercontent.com/43995119/164376689-e3d767fc-3cf6-4eb1-b2dc-3d359ab78832.gif)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @yuwenmemon 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650409983578409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-04-21 20:16
This issue is related to this other: https://github.com/Expensify/App/issues/8641

I investigated a bit here: https://github.com/Expensify/App/issues/8641#issuecomment-1105713934, in case that helps!

**Comment by bfitzexpensify** [comment] 2022-04-22 08:11
Upwork post [here](https://www.upwork.com/jobs/~016faab20cdd498a33)

**Comment by huzaima** [comment] 2022-04-22 13:35
### Proposal

This is happening because we don't have a history in the navigation stack here:
https://github.com/Expensify/App/blob/02af1110b137651f56ee5f8362ea8c321e5a2f64/src/libs/Navigation/CustomActions.js#L21-L31
 
Modifying the function above to create a history before navigating back will solve the issue.

**Comment by migueriveral** [comment] 2022-04-22 20:17
Hey, I noticed that the issue occurs when I copy and paste the URL in my browser _for the first time_. However, if I do it for the second time, it seems to be working correctly, so my guess is that it's got something to do with the browser history.
How do I setup my local environment so I'm not redirected to the external url when I enter the URL? Thank you!

**Comment by frenkield** [comment] 2022-04-23 21:44
Hi All. This seems to be a duplicate of https://github.com/Expensify/App/issues/8641. The weird behavior is due to a bug in `@react-navigation/native`.

I submitted a proposal for https://github.com/Expensify/App/issues/8641. Should I submit my proposal here as well?

**Comment by rushatgabhane** [comment] 2022-04-24 22:05
Sorry, I can't help here. I'm gonna unassign myself because I have school stuff going on 📚

**Comment by flodnv** [comment] 2022-04-25 16:59
@bfitzexpensify please hire @frenkield

**Comment by bfitzexpensify** [comment] 2022-04-27 06:00
@flodnv do you think this is distinct enough from https://github.com/Expensify/App/issues/8641 for this issue to also remain open, and to hire @frenkield twice?

**Comment by flodnv** [comment] 2022-04-27 13:49
Good question. I think it's fair to say that this is a duplicate, which is what @frenkield said above. 

@frenkield what do you say we close this issue in favor of the other one?

**Comment by frenkield** [comment] 2022-04-27 16:15
Sure, that works for me. Thanks, @flodnv.

**Comment by flodnv** [comment] 2022-04-27 16:55
👍

**Closed by flodnv** 2022-04-27 16:55 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
