### ISSUE TITLE
[$250] Top section of Settings doesn't remain fixed like we do on other pages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48736] opened 2024-09-06 18:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-11
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725640618731099

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Settings and scroll the LHN
## Expected Result:
Top section of setting remain fixed (sticky) like other pages
## Actual Result:
Top section of Settings is not sticky like we do on other pages
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8d395c7-7647-497f-873f-ef0b7040570a

https://github.com/user-attachments/assets/98e7c4e8-5131-473f-82ec-6fe6be506485

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832123307878163515</li>
        <li>Upwork Job ID: 1832123307878163515</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103886812</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by ikevin127** [comment] 2024-09-07 05:26
♻️ Will start reviewing the proposals in ~12h.

**Comment by ChavdaSachin** [comment] 2024-09-07 12:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Settings page header is not fixed like on other pages.

### What is the root cause of that problem?
- `headerContent`  is included in  the  `ScrollView` [here](https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/pages/settings/InitialSettingsPage.tsx#L442)

### What changes do you think we should make in order to solve the problem?
- Move `headerContent` out of `ScrollView` and migrate top padding from from `ScrollView` to `ScreenWrapper` to retain top padding on same spot,
- So, change
 ```js
style={[styles.w100, styles.pb0, styles.pt4]}
```
https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/pages/settings/InitialSettingsPage.tsx#L431
And 
```js
{headerContent}
<ScrollView
   ref={scrollViewRef}
   onScroll={onScroll}
   scrollEventThrottle={16}
   contentContainerStyle={[styles.w100]}
>
     
```
https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/pages/settings/InitialSettingsPage.tsx#L436-L442
- Additionally add bottom border to  `hearedContent` to maintain consistent look on the page and to add an end point to the scrollbar.
<details>
<summary> <h3>Check this screenshot<h3> </summary>
<img width="1284" alt="Screenshot 2024-09-07 at 4 59 37 PM" src="https://github.com/user-attachments/assets/82d25756-497d-43db-a49e-bb1715810ab0">
</details>

```js
<View style={[styles.ph5, styles.pb3 , styles.borderBottom]}>
```
https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/pages/settings/InitialSettingsPage.tsx#L373

> ### Optional change
- Scrollbar could be hidden, by passing additional `ScrollView` parameter value.
```js
showsVerticalScrollIndicator = {false}
```
https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/pages/settings/InitialSettingsPage.tsx#L436-L441
- Only hiding scrollbar without inserting bottom border to `headerContent` is also a considerable option (similar to inbox sidebar).
<details>
<summary><h3>Result With Bottom Border<h3> </summary>
<img width="1077" alt="Screenshot 2024-09-07 at 5 33 58 PM" src="https://github.com/user-attachments/assets/5347cc10-e231-49b6-a13e-f30d4e6171ed">
</details>
<details>
<summary><h3>Result With Bottom Border and Hidden Scrollbar <h3> </summary>
<img width="1289" alt="Screenshot 2024-09-07 at 5 28 04 PM" src="https://github.com/user-attachments/assets/dd34dc52-2ba6-4386-85fe-c3ff0bf42759">
</details>
<details>
<summary><h3>Result With only Hidden Scrollbar <h3> </summary>
<img width="1161" alt="Screenshot 2024-09-07 at 5 36 16 PM" src="https://github.com/user-attachments/assets/6485fe5b-e64c-4f58-8efb-26abb47a0fb0">
</details>




### What alternative solutions did you explore? (Optional)
- `stickyHeaderIndices={[0]}` could be added to `ScrollView` along with  `showsVerticalScrollIndicator = {false}` to hide scrollbar and add `backgroundColor: theme.appBG` to `headerContent` to avoid content overlapping.
Optionally bottom border could be added to `hederContent`.

**Comment by ChavdaSachin** [comment] 2024-09-07 13:16
# Proposal 
[Updated Proposal](https://github.com/Expensify/App/issues/48736#issuecomment-2335177712)
Added Postscript.

**Comment by mhynson** [comment] 2024-09-07 14:51
# Proposal

## Please re-state the problem that we are trying to solve in this issue.

Top section of settings page does not remain fixed/sticky

## What is the root cause of that problem?

`{headerContent}` is inside of the `<ScrollView />` element in the [InitialSettingsPage.tsx](https://github.com/Expensify/App/blob/7537bfb06364c1f3574a3e218200116fe78fcea5/src/pages/settings/InitialSettingsPage.tsx#L442)

## What changes do you think we should make in order to solve the problem?

- Move `{headerContent}` above the `<ScrollView />` [here](https://github.com/Expensify/App/blob/7537bfb06364c1f3574a3e218200116fe78fcea5/src/pages/settings/InitialSettingsPage.tsx#L436)
- remove the styles.pt4 from the `<ScrollView/>` [here](https://github.com/Expensify/App/blob/7537bfb06364c1f3574a3e218200116fe78fcea5/src/pages/settings/InitialSettingsPage.tsx#L440)
- append styles.pt4 to the containing `<View/>` of `headerContent` [here](https://github.com/Expensify/App/blob/7537bfb06364c1f3574a3e218200116fe78fcea5/src/pages/settings/InitialSettingsPage.tsx#L373)

## Demo of Solution

https://github.com/user-attachments/assets/fc60a062-0e73-4fe2-8467-4b1ead9ef639

**Comment by ikevin127** [comment] 2024-09-08 02:13
@mhynson Thanks for your interest in contributing to the Expensify App. Please refer to the [Contributing Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) before posting other proposals as you risk getting a **warning** if you don't follow to the guidelines. Specifically you are in violation of [Propose a solution for the job](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) rule number 6. (note) which states:

> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

because your proposal is simply a copy of a previous [existing proposal](https://github.com/Expensify/App/issues/48736#issuecomment-2334650671), without adding anything extra.

> [!note]
> Repeated **violations** of the guidelines can lead to ⚠️ **warnings**, and if 3 warnings are received within a 1 year span leads to removal from the contributor program.

**Comment by ikevin127** [comment] 2024-09-08 02:15
### Based on the current proposals, 3 slightly different versions stand out:

**Note**: I'm comparing to the Home - Reports LHN since that was displayed as `other pages` in the issue OP videos.

| Current Home - Reports LHN | Proposal 1 (full height LHN scrollbar) | Proposal 2 (scrollable only LHN scrollbar) | Proposal 3 (no scrollbar LHN) |
| ------------- | ------------- | ------------- | ------------- |
| <img width="300" alt="home" src="https://github.com/user-attachments/assets/7ddd4a9e-6f88-4d25-951d-66c46a7f31ba"> | <img width="300" alt="p1" src="https://github.com/user-attachments/assets/086a2ecd-e7f1-4473-99f3-615145b24f4a"> | <img width="300" alt="p2" src="https://github.com/user-attachments/assets/6078cfe7-ea9a-4f6b-a77d-081fc7c3f5b5"> | <img width="300" alt="p3" src="https://github.com/user-attachments/assets/4b309b01-e627-471c-8d86-307ba0c0199a"> |

@Expensify/design  I need help deciding which version we want to go with from a design point of view. If we were to strictly go by the issues' OP and have this look like on the `other pages` then we would go for Proposal 3 (no scrollbar) but maybe we want something else so thought I should ask 😁

##

> [!note]
> ### @ Proposals authors
> - to keep things fair, any edits of the existing proposals **after this post** won't change the final decision of the assignment based on design team's decision

**Comment by shawnborton** [comment] 2024-09-08 15:22
Yeah, the third proposal makes sense to me assuming that we can still scroll that area, even without a scrollbar. Basically it should all work the same was as the Inbox page does with a fixed header and scrollable content area below it.

**Comment by alexpensify** [comment] 2024-09-09 17:16
@ikevin127 - do you have enough feedback to carry on with the review? Thanks for checking!

**Comment by ikevin127** [comment] 2024-09-09 17:21
@alexpensify Yes I do, but I want to check something regarding implementation **before** finalizing the review. It will be done in ~ 1 hour, as soon as I get to the office 👍

**Comment by alexpensify** [comment] 2024-09-09 17:30
Sounds like a plan! Thanks for the update.

**Comment by ikevin127** [comment] 2024-09-09 18:51
🎉 Thanks everybody for the proposals! Given that all proposals are similar in terms of RCA / solution, means that the final decision will be based on the smaller details.

##

@ChavdaSachin's [proposal](https://github.com/Expensify/App/issues/48736#issuecomment-2335177712) looks good to me because the RCA was identified and the **solution** seems the best choice in terms of design (see [confirmation reference](https://github.com/Expensify/App/issues/48736#issuecomment-2336724649)).

What I wanted to double-check was how the Home - Inbox LHN reports page looks if it were to have the scroll and it indeed looks like `{headerContent}` should be outside of the scroll list (see video below).

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/2cf329d0-7b74-42fc-9bcb-5007ce211239

</details>

**When it comes to the PR, the only changes should be:**
1. Moving `{headerContent}` outside of the `ScrollView` and ensuring the padding is correct (as seen before the change).
2. Hiding the scroll-bar.

🎀👀🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2024-09-09 19:04
Sounds good, thanks for the review @ikevin127, assigning @ChavdaSachin 🚀

**Comment by ChavdaSachin** [comment] 2024-09-09 19:10
Thank you @ikevin127 and @marcochavezf for assigning me.
Applied for the Upwork job and will raise PR within an hour or two.

**Comment by ChavdaSachin** [comment] 2024-09-09 19:21
So I am making following changes,

1. migrating `styles.pt4` from `ScrollView` to `ScreenWrapper`.
2. moving `{headerContent}` outside the `ScrollView`.
3.  passing additional props `showsVerticalScrollIndicator = {false}` to `ScrollView` to hide scrollbar.

**Comment by ikevin127** [comment] 2024-09-09 21:33
@ChavdaSachin Since this is your first job / contribution, here's some info on the process:

1. Contributor posts proposal.
2. Proposal is selected (your case here).
3. If contributor contributes for the first time, they have to apply to the Upwork job because they are not in the offer sending automation system yet (first job).
3. Contributor opens PR, pr is reviewed and if all good - merged.
4. PR will be deployed to staging and QA runs tests.
5. If no issues are reported, PR gets deployed to production ~1-2 days after staging deploy.
6. As soon as PR hits production, a 7-day regression period ensues and a HOLD for Payment {date} is added to the issue's title.
7. If no issues are reported at the end of the 7-day regression period, a BZ tram member will issue the payment for both Contributor and C+ | so you will get paid, no worries - it just has to follow this process.

> [!note]
> In case at any stage of the deploy process, a regression is found coming from the deployed PR changes, the issue's bounty will be cut in half (-50%) for both controbutor and C+, and the regression period extends to when the follow-up fix PR is deployed to production.

When the payment is due date, the BZ team member which handles the payments will make sure you accept your offer and you get paid. Given the whole deploy and 7-days regression period process can take several days, the sooner the PR is opened, the better - but keep in mind that rushing to open the PR can lead to regressions if not tested thoroughly.

**Comment by ChavdaSachin** [comment] 2024-09-09 21:45
@ikevin127 thanks a lot. I appreciate the way you operate. 

In addition to above points do you have any note for me or did I miss anything ?
Much appreciated.

**Comment by ikevin127** [comment] 2024-09-09 21:56
@ChavdaSachin Sure, thanks! 🙏

You're all set, I am about to finish the review - the code in the PR looks and tests well. I will post my PR Reviewer Checklist soon and after that we're awaiting final review and merge from assigned Expensify engineer.

##

🎉 You did really good for your first PR in terms of the checklist, tests and code changes.

🗒️ The only thing that was missing (which is not a blocker) would be to add something in the **Details** section of your PRs, to give you some examples of some of my past PRs ([ref1](https://github.com/Expensify/App/pull/41125), [ref2](https://github.com/Expensify/App/pull/34971), [ref3](https://github.com/Expensify/App/pull/38142)) - this helps the reviewers and engineers understand what the PR does and can help especially in cases where regressions are caused by a PR 👍

**Comment by ChavdaSachin** [comment] 2024-09-09 22:14
Thanks @ikevin127, I will keep your advice on my mind.

**Comment by ikevin127** [comment] 2024-09-12 22:11
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-09-19]** according to today's production deploy from https://github.com/Expensify/App/pull/48829#issuecomment-2347263339.

cc @alexpensify @marcochavezf

**Comment by alexpensify** [comment] 2024-09-13 16:53
Thanks, I've noted this date for the payment party.

**Comment by alexpensify** [comment] 2024-09-18 22:37
I checked Upwork to confirm that we are ready for tomorrow. @ikevin127, you are set up, and I can complete the process tomorrow. 

@ChavdaSachin—I tried searching your Upwork profile via the link in your GH bio, but the link is not active. I see you mentioned you input a proposal, but can you do so again here: https://www.upwork.com/jobs/~021832123307878163515

Thanks!

**Comment by ChavdaSachin** [comment] 2024-09-19 16:49
@alexpensify I have sent proposal please check.

**Comment by alexpensify** [comment] 2024-09-19 21:33
Payouts due: 2024-09-19

- [ ] Contributor: $250 @ChavdaSachin 
- [ ] Contributor+: $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~021832123307878163515). All set; everyone has been paid via Upwork!

**Closed by alexpensify** 2024-09-19 21:33 UTC
Labels: Reviewing, External, Weekly, Bug
