### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] IOU – Disabled distance rate is present in the rate list in confirmation page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42284] opened 2024-05-16 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in and go to Collect workspace settings
3. Go to Distance rates
4. Click Add rate
5. Add a new rate
6. Disable existing rate
7. Go to workspace chat
8. Start submit distance flow
9. In confirmation page, click Rate

## Expected Result:
Disabled distance rate is not present in the rate list in confirmation page

## Actual Result:
Disabled distance rate is present in the rate list in confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/609ccf1c-abbd-48aa-8e87-f20ec3781f3e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1179d796babea5c</li>
        <li>Upwork Job ID: 1793173961329356800</li>
        <li>Last Price Increase: 2024-05-22</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 102499784</li>
<li>cretadn22 | Contributor | 102499787</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by izarutskaya** [comment] 2024-05-16 12:28
We think this issue might be related to the #collect project.

**Comment by JmillsExpensify** [comment] 2024-05-22 06:56
Opening this up to the community.

**Comment by ikevin127** [comment] 2024-05-22 19:43
♻️ Reviewing proposals.

**Comment by ikevin127** [comment] 2024-05-23 00:00
@Krishna2323 Your [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2115150488)'s **RCA** is incomplete as only filtering out the disabled distance rates from the Rate option selector is not enough to fix this issue. See **cretadn22**'s [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2116574341) RCA for more details.

Your **main solution** is not detailed enough for me to assess whether or not it would fix the issue. Even if it would be, since the RCA is not complete, it would most likely not tackle the issue fully.

Regarding your **alternative solution**, I think it adds too much overhead and new code when not necessary - besides this, I'm reserved when it comes to adding 2 additional arguments to a function that already has 23 arguments. I checked out your test branch and the same thing mentioned above applies:

> only filtering out the disabled distance rates from the Rate option selector is not enough to fix this issue

Besides not fixing the issue completely, due to the changes from your test branch -> now there's no more difference in the UI when it comes to `canUseAllBetas` being true or false -> the Rate field is always visible as if `canUseAllBetas` is always true.

| canUseAllBetas -> `false` on current `main` | canUseAllBetas -> `false` / `true` (your test branch) |
| ------------- | ------------- |
| <img width="370" alt="cantuseallbetas" src="https://github.com/Expensify/App/assets/56457735/7585e2d2-85d6-4988-a4b5-bf608e193465"> | <img width="373" alt="canuseallbetas" src="https://github.com/Expensify/App/assets/56457735/afbec6f1-d268-4805-a0c5-f88df7f847fd"> |

**Comment by ikevin127** [comment] 2024-05-23 00:00
@GandalfGwaihir Your [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2115338025)'s **RCA** is incomplete as only filtering out the disabled distance rates from the Rate option selector is not enough to fix this issue. See **cretadn22**'s [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2116574341) RCA for more details.

Your proposed **solution** only filters out the disabled distance rates from the Rates selector but if you follow the OP video carefully, once the new distance rate was added, the existing (default) one was disabled -> when reaching the confirmation page even though the existing (default) distance rate is disabled -> it still shows up as the default selected rate in the Rate option for both `canUseAllBetas` true and false UI variations, even though the rate is disabled.

**Comment by ikevin127** [comment] 2024-05-23 00:00
@cretadn22 Your [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2116574341)'s RCA is correct. Your **solution** is problematic since you don't clearly mention which part of the issue the suggested change is targeting. Additionally, your test branch does not help me in assessing whether your solution is working because of the following reasons:
1. It only implements 2 of the suggested bullet-point changes from your solution, the first bullet-point does not seem to be accounted for.
2. It uses `getMileageRates` before the function is defined.
3. I'm reserved when it comes to implementing the logic which includes the `includeDisableRate` argument as I think there's better and simpler ways of tackling this, avoiding the addition of unnecessary arguments.

**Comment by ikevin127** [comment] 2024-05-23 00:00
## Notes for contributors

**Some pointers regarding issue complexity**

This issue has 2 sides to it, see **cretadn22**'s [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2116574341) RCA for more details. To get a better sense of the root cause I'd advise following these steps:
> [!tip]
> 1. Log in and go to **Collect** workspace settings.
> 2. Go to **Distance rates**.
> 3. Click **[+ Add rate]**.
> 4. Add a new rate.
> 5. **Disable** previously existing rate (`0.67`) such that only the newly added rate is **Enabled**.

Now before following the rest of the steps from OP, know that there are 2 different ways the UI can look when arriving on the Distance request confirmation page, and this differs based on whether your account `canUseAllBetas`.

| canUseAllBetas -> `false` | canUseAllBetas -> `true` (OP) |
| ------------- | ------------- |
| <img width="370" alt="cantuseallbetas" src="https://github.com/Expensify/App/assets/56457735/7585e2d2-85d6-4988-a4b5-bf608e193465"> | <img width="373" alt="canuseallbetas" src="https://github.com/Expensify/App/assets/56457735/afbec6f1-d268-4805-a0c5-f88df7f847fd"> |

**Note:** This can be enabled / disabled from `src/libs/Permissions.ts` by hardcode returning true / false for the `canUseAllBetas` function.

**Some RCA & Solution pointers (from a reviewer's POV)**

✅ Have a clear RCA that accounts for the entirety of the issue.
✅ Have a clear and technically detailed implementation of the solution, instead of a vague sentence.
✅ We need a solution which tackless the root cause for both `canUseAllBetas` UI scenarios, including consideration for offline pattern (if any).
✅ We need a clear and detailed technical implementation of the solution which I'm able to test OR a test branch which aligns with your proposal's solution. The test branch should reflect the final implementation as close as possible.

❌ Avoid adding extra parameters to existing functions which already have too many parameters.
❌ Avoid creating a test branch which does not entirely match everything mentioned in the proposed solution changes. Additionally, don't use variable / function names like `abc` as the test branch should reflect the final implementation as close as possible.

>[!important]
> The first contributor to update / post a new proposal considering all of the above will be selected on a `first come, first served` basis.

cc @Krishna2323 @GandalfGwaihir @cretadn22

**Comment by nkdengineer** [comment] 2024-05-23 04:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Disabled distance rate is present in the rate list in confirmation page

### What is the root cause of that problem?

1. We don't clear `lastSelectedDistanceRates` of the policy when the rate is disable

2. We don't filter out the disabled rate here so the disabled rates still present in distance rate step page

https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L55
### What changes do you think we should make in order to solve the problem?
1. We should clear `lastSelectedDistanceRates` of a policy when the rate is disable. To do that we can handle the same way we handle report change [here](https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/libs/actions/Report.ts#L209C9-L209C28). It's something like this in `Policy` actions

```
const allPolicies: OnyxCollection<Policy> = {};
Onyx.connect({
    key: ONYXKEYS.COLLECTION.POLICY,
    callback: (val, key) => {
        ...
        handlePolicyChange(val);

        allPolicies[key] = val;
    },
});
let lastSelectedDistanceRates: OnyxEntry<LastSelectedDistanceRates> = {};
Onyx.connect({
    key: ONYXKEYS.NVP_LAST_SELECTED_DISTANCE_RATES,
    callback: (value) => {
        lastSelectedDistanceRates = value;
    },
});

function handlePolicyChange(policy: OnyxEntry<Policy>) {
    if (!policy || !lastSelectedDistanceRates?.[policy?.id ?? '']) {
        return;
    }

    const rateID = lastSelectedDistanceRates?.[policy?.id ?? ''];
    const distanceUnit = Object.values(policy?.customUnits ?? {}).find((unit) => unit.name === CONST.CUSTOM_UNITS.NAME_DISTANCE);
    const distanceRate = distanceUnit?.rates?.[rateID];

    if (!distanceRate?.enabled) {
        Onyx.merge(ONYXKEYS.NVP_LAST_SELECTED_DISTANCE_RATES, {[policy.id] : null});
    }
}
```

2. In `getDefaultMileageRate`, we should return an extra field `enabled: rate.enabled` to know a rate is disabled or not

https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/libs/DistanceRequestUtils.ts#L51

3. To make distance rate step has the same behavior with other steps like tag, category, we will filter out that disabled rate that isn't the selected rate and return an extra field `isDisabled: !rate.enable`. So if the selected rate is disabled, it can be displayed with grey out 


```
const sections = Object.values(rates).filter((rate) => rate.enabled || rate.customUnitRateID === lastSelectedRateID).map((rate) => {
    const rateForDisplay = DistanceRequestUtils.getRateForDisplay(rate.unit, rate.rate, rate.currency, translate, toLocaleDigit);

    return {
        ...
        isDisabled: !rate.enabled,
    };
});
```
https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L55



### What alternative solutions did you explore? (Optional)
NA

**Comment by ikevin127** [comment] 2024-05-23 19:04
♻️ Reviewing proposals once again.

**Comment by ikevin127** [comment] 2024-05-23 23:10
@nkdengineer Thank you for your proposal. Your [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2126213282)'s **RCA** is correct and complete since it was already pointed out previously. As far as your **solution** goes, though it would fix the issue, due to the different route you approached when it comes to **disabling** the Rate list options -> this does not match with the **expected result** which states:

> Disabled distance rate is not present in the rate list in confirmation page

If the assigned CME decides that we want to involve **design** and adjust the expected result to match your proposed solution, then I would be willing to reconsider assignment.

**Comment by ikevin127** [comment] 2024-05-23 23:10
@cretadn22's updated [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2116574341) looks good to me! They were first to identify the **root cause** correctly and completely and first to update their proposal after initial review. Their updated **main solution** / test branch fixes the issue accordingly as per issue's **expected result** by:
1. Defaulting distance rate to the first enabled when the Rate field is not shown (users with betas **disabled**).
2. (1.) + Not displaying the disabled distance rates in the Rate field list (users with betas **enabled**).

<details>
<summary>Video / Screenshot of Fix</summary>

| `canUseAllBetas` -> `true` | `canUseAllBetas` -> `false` |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/6ee23f75-6305-4358-90d2-d5d7140e78b8"> | <img width="1440" alt="cantUseAllBetas" src="https://github.com/Expensify/App/assets/56457735/44430ec7-aa1a-4a5b-826d-6199758ab0b4"> |

</details>

🎀👀🎀 C+ reviewed

**Comment by neil-marcellini** [comment] 2024-05-28 18:29
> @cretadn22's updated [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2116574341) looks good to me! They were first to identify the **root cause** correctly and completely and first to update their proposal after initial review. Their updated **main solution** / test branch fixes the issue accordingly as per issue's **expected result** by:
> 
> 1. Defaulting distance rate to the first enabled when the Rate field is not shown (users with betas **disabled**).
> 2. (1.) + Not displaying the disabled distance rates in the Rate field list (users with betas **enabled**).
> 
> Video / Screenshot of Fix
> 🎀👀🎀 C+ reviewed



> @cretadn22's updated [proposal](https://github.com/Expensify/App/issues/42284#issuecomment-2116574341) looks good to me! They were first to identify the **root cause** correctly and completely and first to update their proposal after initial review. Their updated **main solution** / test branch fixes the issue accordingly as per issue's **expected result** by:
> 
> 1. Defaulting distance rate to the first enabled when the Rate field is not shown (users with betas **disabled**).
> 2. (1.) + Not displaying the disabled distance rates in the Rate field list (users with betas **enabled**).
> 
> Video / Screenshot of Fix
> 🎀👀🎀 C+ reviewed

Cool thanks, looks good to me to. I guess we forgot about handling this during the initial implementation.

**Comment by ikevin127** [comment] 2024-05-28 19:12
Awaiting for PR to be open!

**Comment by ikevin127** [comment] 2024-06-07 21:03
The PR was reverted because it had regressions and no follow-up fix was provided in a timely manner, therefore a revert was performed.

**What's next ?**
1. @cretadn22 Can let us know if they want to re-work the solution in a new PR, making sure to test it better this time (both author and reviewer), accounting for the regression issues encountered after initial PR was merged ([#43197](https://github.com/Expensify/App/issues/43197) and [#43171](https://github.com/Expensify/App/issues/43171)).
2. If initial contributor does not want to re-work the solution in a new PR, we would re-open the issue to proposals.

**Comment by ikevin127** [comment] 2024-06-08 18:03
@cretadn22 Sorry, my bad - I just noticed the revert PR being closed and the issue being fixed somewhere else.

So the regression was indeed caused by our PR, or it was another PR / unrelated ?

cc @neil-marcellini

**Comment by ikevin127** [comment] 2024-06-15 21:11
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: [#38543](https://github.com/Expensify/App/pull/38543).
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [#38543 (comment)](https://github.com/Expensify/App/pull/38543#issuecomment-2170792548).
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

### Test 1

**Precondition**: User does **NOT** have **betas** enabled, hence no **Rate** field will be displayed in Distance confirmation page.

1. Log in and go to a new Collect workspace settings page.
2. Enable **Distance rates** and go to **Distance rates** page.
3. Click [+ Add rate].
4. Add a new rate and make sure it's **Enabled**.
5. **Disable** previously existing distance rate (the default **$0.670 / mile** rate).
6. Go to the workspace chat.
7. Click composer [+] and proceed to **Submit expense** > **Distance** request.
8. On Distance confirmation page, verify that the enabled rate is set as default in the **Distance** field (see below).

<img width="360" alt="Screenshot 2024-05-29 at 14 10 59" src="https://github.com/Expensify/App/assets/56457735/fad564df-1bf3-4998-ac65-b402f2d1da69">

### Test 2

**Precondition**: User does have **betas** enabled, hence the **Rate** field will be displayed in Distance confirmation page.

1. Log in and go to a new Collect workspace settings page.
2. Enable **Distance rates** and go to **Distance rates** page.
3. Click [+ Add rate].
4. Add a new rate and make sure it's **Enabled**.
5. **Disable** previously existing distance rate (the default **$0.670 / mile** rate).
6. Go to the workspace chat.
7. Click composer [+] and proceed to **Submit expense** > **Distance** request.
8. On Distance confirmation page, verify that the enabled rate is set as default in the **Rate** field (see [1.]).
9. On Distance confirmation page, click on the **Rate** field and verify that the disabled rate is not displayed (see [2.]).

| 1 | 2 |
| ------------- | ------------- |
| <img width="356" alt="1" src="https://github.com/Expensify/App/assets/56457735/0c1261c3-d12c-4186-97d6-283ba098e70d"> | <img width="375" alt="2" src="https://github.com/Expensify/App/assets/56457735/5400719c-5710-4220-8253-4f17da90b583"> |

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment] 2024-06-15 21:11
⚠️ Not sure why the automation added the second HOLD date her, since the PR was deployed **4 days ago** according to https://github.com/Expensify/App/pull/42330#issuecomment-2161772275 -> therefore the **[HOLD for payment 2024-06-18]** is the correct payment date.

**Summary:**
- PR was merged 2 weeks ago according to automation [#42330 (comment)](https://github.com/Expensify/App/pull/42330#issuecomment-2148246715) but wasn't deployed to staging / production
- PR was deployed to production **4 days ago** -> **compensation due** for contributor / reviewer on **2024-06-18**

**Note:** Some regressions were associated with this PR, which if **confirmed** -> the compensation will be reduced. I asked @neil-marcellini to confirm this above in https://github.com/Expensify/App/issues/42284#issuecomment-2156123530 so that everything is clear and ready for payment when due.

cc @JmillsExpensify

**Comment by neil-marcellini** [comment] 2024-06-18 18:29
Yes there was a regression caused by https://github.com/Expensify/App/pull/42330

**Comment by dylanexpensify** [comment] 2024-06-19 22:25
Payment issued to @ikevin127 and @cretadn22 factoring in regression 👍

**Comment by dylanexpensify** [comment] 2024-06-19 22:26
done

**Closed by dylanexpensify** 2024-06-19 22:26 UTC
Labels: External, Daily, Awaiting Payment, Bug
