### ISSUE TITLE
[$1000] Android - Deeplink - App crashes when navigating from deeplink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20395] opened 2023-06-07 17:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User is not signed in to the app.

1. Be signed out on the testing device
2. Click on the link: https://staging.new.expensify.com/concierge
3. Verify you have been navigated to the sign in flow

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bf34c612-0d67-424f-8b29-6710c734712f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0c9ac7a95ea5994</li>
        <li>Upwork Job ID: 1666913354975072256</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-06-07 20:31
Asked for help reproducing in Slack

**Comment by greg-schroeder** [comment] 2023-06-07 21:54
We haven't been able to reproduce this, so I'm going to close. From the team:

> hmmm, I’ve tried it a few different times now and the app doesn’t crash, it just opens up to the login page.
> I don’t receive the “New Expensify keeps stopping” message that is shown in the repro video.

 Perhaps there's more specific steps you can point to @lanitochka17!

**Comment by lanitochka17** [comment] 2023-06-08 18:10
@greg-schroeder Specific steps:
1. Be signed out on the testing device
2. Click on the link: https://staging.new.expensify.com/concierge
3. Verify you have been navigated to the sign in flow

**Comment by greg-schroeder** [comment] 2023-06-08 21:01
Okay. I updated the OP. I can't reproduce this on Browserstack at all but it might be the device I have selected. I'll send it to External though in order to try and get more eyes on it.

**Comment by s77rt** [comment] 2023-06-12 17:59
Not overdue. Still looking for proposals...

**Comment by greg-schroeder** [comment] 2023-06-13 19:07
I tried reproducing it again as well and I still can't

**Comment by greg-schroeder** [comment] 2023-06-14 20:20
I think I'm going to close this as multiple applause testers and internal users can't reproduce it.

**Closed by greg-schroeder** 2023-06-14 20:20 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
