### ISSUE TITLE
Send money - Date is not saved when sending money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29381] opened 2023-10-11 20:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No. Send money is not available on prod

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send money
3. Enter amount > Next
4. Select user > Next
5. Change the date and send the money
6. Open Send money details page

## Expected Result:
The new date is saved

## Actual Result:
The new date is not saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/49a2839b-44e5-4820-94c1-a1d46442c172

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-10-11 21:41
This is not a blocker, its known and it will be fixed with this PR which will hide the date, you cannot edit the date oon send money request. Same goes for merchant. https://github.com/Expensify/App/pull/29358

**Comment by DylanDylann** [comment] 2023-10-12 08:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Send money - Date is not saved when sending money

### What is the root cause of that problem?
In SendMoneyElsewhere API, we don't send created params to server
### What changes do you think we should make in order to solve the problem?
We should send created params (date field) to server

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-10-12 21:49
This can be closed, nobody to be paid

**Closed by mountiny** 2023-10-12 21:49 UTC
Labels: Engineering, Daily, Bug
