### ISSUE TITLE
DEV: Web - arrangement of workspace chat is changed after brief moment of time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26032] opened 2023-08-27 12:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Create new workspace
3. Observe the order of WS in LHN

## Expected Result:
 WS chat order should not change after brief moment of time

## Actual Result:
WS chat order is change after brief moment of time.
observe that while create new WS
order of WS chat is
#admin
#announce
#WS activity
After brief moment of time order is
#admin
#WS activity
#announce

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.55-7
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/54813b59-b43f-488d-a31c-af3e7af8ca1f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692430667118349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2023-08-29 21:16
This is not a bug, it's a feature/improvement, but nothing is broken. I'm going to close the issue.

**Closed by tjferriss** 2023-08-29 21:16 UTC
Labels: Daily, Needs Reproduction, Bug
