### ISSUE TITLE
[HOLD for payment 2024-03-13] Split scan - Split button in split menu is gray instead of green

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37711] opened 2024-03-05 03:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat > + > Split bill.
3. Go to Scan.
4. Create a scan split request.
5. Click on the split preview.
6. 
## Expected Result:
The split button will be green.

## Actual Result:
The split button is gray.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a4c7ccaa-5e4a-46b3-866a-968e519f35cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-03-05 03:16
@anmurali FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment] 2024-03-05 03:17
We think that this bug might be related to #vip-split-p2p-chat-groups
cc @arielgreen

**Comment by MonilBhavsar** [comment] 2024-03-05 06:47
Since it is a regression, it should be basically fixed by an author

**Comment by burczu** [comment] 2024-03-05 08:19
@MonilBhavsar Yes - this is regression. Can you please assign it to me?

**Comment by MonilBhavsar** [comment] 2024-03-05 08:38
@burczu @aimane-chnaif assigned you both to this issue

**Comment by burczu** [comment] 2024-03-05 09:30
@aimane-chnaif The PR is read for review: https://github.com/Expensify/App/pull/37719

**Comment by MonilBhavsar** [comment] 2024-03-05 14:17
This is fixed on staging!

**Comment by MonilBhavsar** [comment] 2024-03-07 05:01
Yes, thanks all!

**Closed by MonilBhavsar** 2024-03-07 05:01 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
