### ISSUE TITLE
[$500] Bank account - Deleting 1st BA, Make default payment method CTA appears for other BA & CTA not functional

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35788] opened 2024-02-04 20:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User has added 2 bank accounts in profile
1. Navigate to staging.new.expensify.com & log in
2. Go to Settings >> Wallet page
3. Delete BA which show default tag
4. Note default tag does not appear for the 2nd saved payment method
5. Click on the saved BA (Modal opens with Make default payment method & Delete button)
6. Click on Make default payment method (Note: Default tag does not appear)
7. Again click on BA (Note : Only delete option displayed)

## Expected Result:
Expected, "Make default payment method" button should not displayed when there is one saved BA left after deleting the first default one. Instead, default tag should appear next to payment method

## Actual Result:
After deleting one default BA, Make default payment method button appears for other saved BA. Also, clicking the button just closes the modal & default tag do not appear next to payment method

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/113d1122-6371-4539-b797-32bec5b2416f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6978f9d5d46d85a</li>
        <li>Upwork Job ID: 1754244421493067776</li>
        <li>Last Price Increase: 2024-02-18</li>
    </ul>
</details>

**Comment by brunovjk** [comment] 2024-02-04 22:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1 - When deleting a bank account, the 'default tag' is not transferred to another account
2 -  _"Make default payment method Modal"_ appears when we only have one bank account registered.

### What is the root cause of that problem?
1 - We do not mark another account as default when deleting:
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/actions/BankAccounts.ts#L221-L226

2 - And we only show the `default tag` when we have more than one registered bank account:
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/settings/Wallet/PaymentMethodList.js#L163-L167

### What changes do you think we should make in order to solve the problem?
1 - When we delete an account we must move the default tag to another account, we must decide whether this tag goes: to the first account in the list, to the last added account or maybe to the last account with default tag.
2 - We must implement the same logic and only show _"Make default payment method Modal"_ if there is more than one bank account registered.

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-02-05 01:18
This seems similar to https://github.com/Expensify/App/issues/34774.

cc @stitesExpensify This is another case where it's easier to have the BE return the new default bank account since we cannot predict it (yet)

- AddPersonalBankAccount => Return added account + previous default account (if the new account is the new default)
- DeletePaymentBankAccount => Return deleted account + new default account (if the deleted account is the current default)

Both commands should return at most two bank accounts.

**Comment by brunovjk** [comment] 2024-02-05 01:51
I agree @s77rt, I don't know if it's easy, but the best solution in my opinion would be _"have the BE return the new default bank account..."_

**Comment by s77rt** [comment] 2024-02-07 17:35
Not overdue. Waiting on @stitesExpensify https://github.com/Expensify/App/issues/35788#issuecomment-1926049398

**Comment by stitesExpensify** [comment] 2024-02-12 17:03
I have not had time to look into the backend solution here yet

**Comment by brunovjk** [comment] 2024-02-19 13:50
@stitesExpensify  this one also https://github.com/Expensify/App/issues/34774  :D

**Comment by isabelastisser** [comment] 2024-02-21 16:46
@stitesExpensify should I add the `internal` label?

**Comment by stitesExpensify** [comment] 2024-02-21 18:45
Yes, thanks for reminding me

**Comment by isabelastisser** [comment] 2024-02-26 18:26
Not overdue, internal.

**Comment by isabelastisser** [comment] 2024-02-29 20:20
@stitesExpensify any progress? Thanks!

**Comment by isabelastisser** [comment] 2024-03-14 17:09
Internal, no updates yet.

**Comment by isabelastisser** [comment] 2024-03-27 17:42
We've had a [discussion ](https://expensify.slack.com/archives/C01GTK53T8Q/p1711426558417769)in Slack and decided to close this issue.

**Closed by isabelastisser** 2024-03-27 17:42 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
