### ISSUE TITLE
[$500] Split - The order of split details and request preview is different before & after opening report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33770] opened 2023-12-29 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.19-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat > + > Split bill.
2. Create a bill split.
3. Note the order of split preview and request preview (the one with pay button).
4. Click on the split preview.
5. Return to the main chat.

## Expected Result:
The order of split preview and request preview should be consistent.

## Actual Result:
Before opening the expense report from the preview (with green button), the order is the expense preview (with green button), followed by the split preview.
After opening the expense report, the order is interchanged. Now the split preview appears first, followed by the expense preview (with green button).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6b2827f2-9b31-427e-84ff-97b6f69f2a84

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01151f83b81fcfc0b1</li>
        <li>Upwork Job ID: 1740793866618548224</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by brunovjk** [comment] 2024-01-02 13:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The issue revolves around the inconsistency in the order of 'split preview' and 'request preview' following the creation of a SplitBill in a workspace chat.

### What is the root cause of that problem?

1 - Upon initiating the 'splitBill' action in a workspace chat through `IOU.js > splitBill(){createSplitsAndOnyxData(...)}`, the `optimisticData` sets a `reportActions_.IOU.created`. Upon receiving a response with `successData`, the `reportActions_.IOU.created` is then updated, and match the newly created `reportActions_.IOU.lastModified`.

2 - When displaying 'preview cards' on a chat using `ReportActionsUtils.getSortedReportActions`, we get the list of reports (`reportActions`) and subsequently sorting it. Initially, the sorting is based on the timestamp, and if timestamps are identical, further sorting is done by CREATED and REPORTPREVIEW.

3 - Immediately after creating a 'splitBill', both `reportActions_.IOU.created` values from 'split preview' and 'request preview' are nearly identical. Consequently, in `getSortedReportActions`, the system falls into one case. However, when `successData.response` is received, the `reportActions_.IOU.created` values diverge, leading to a different case in `getSortedReportActions`.

This inconsistency is at the core of the problem.

### What changes do you think we should make in order to solve the problem?

To address this issue, two potential solutions are proposed:

1. **Backend Modification**: Investigate the feasibility of preventing the backend from modifying the `reportActions_.IOU.created` property when 'SplitBill' is called. This modification could contribute to maintaining consistency.

2. **Sorting Adjustment**: Adjust the sorting logic in `ReportActionsUtils.getSortedReportActions` to prioritize sorting by CREATED and REPORTPREVIEW. This adjustment ensures a consistent ordering of 'split preview' and 'request preview', aligning with the desired arrangement of keeping CREATED at the top and REPORTPREVIEW at the bottom.

### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment] 2024-01-03 16:43
@alitoshmatov will you be able to review this?

**Comment by alitoshmatov** [comment] 2024-01-03 16:48
Working on it

**Comment by alitoshmatov** [comment] 2024-01-04 12:43
I think there is a problem with backend. Based on my research when split bill is made in workspace chat optimistic data for `reportActions_{workspace chat}` contains two entries one for split bill preview and one for request preview. (1st image)

(2nd image) But backend is sending only one entry for this `reportActions_`, it is sending only split bill preview. Thus we have
1) Request preview, which requires pay action - Completely optimistic data
2) Split bill iou preview - received from backend

But when we go to another report and comeback to workspace chat, `openReport` request is made and then backend is sending complete  report actions in  `reportActions_{workspace chat}` which includes split bill preview and Request preview (3rd image)

1st image
<img width="1231" alt="Screenshot 2024-01-04 at 17 37 05" src="https://github.com/Expensify/App/assets/59907218/039cc8a9-b27a-4cdb-933f-489f7ac10811">

2nd image
<img width="797" alt="Screenshot 2024-01-04 at 17 38 01" src="https://github.com/Expensify/App/assets/59907218/99c2f304-e691-48ac-b70d-62575e4e69a5">

3rd image
<img width="936" alt="Screenshot 2024-01-04 at 17 39 51" src="https://github.com/Expensify/App/assets/59907218/631e4411-5355-47a9-a41b-7437bea54eb4">

**Comment by slafortune** [comment] 2024-01-10 14:30
@alitoshmatov sorry for the delay!  Sure can, I'll get an engineer assigned to take a look.

**Comment by joelbettner** [comment] 2024-01-12 19:21
I have been testing to try and re-create this. I haven't been able to.

@kbecciv can you please try to re-create this again and let me know if you're able to?

**Comment by joelbettner** [comment] 2024-01-12 20:06
I just manually tested this locally again. I checked it with timestamps that were the same and timestamps that were different by manually updating the timestamps in my local database. In neither case did the order that the report actions are displayed change. I think this can be closed.
#### How it displayed with different timestamps:
![image](https://github.com/Expensify/App/assets/13264774/1c5f87cd-2296-4c2f-b563-dcde961bceb0)

![image](https://github.com/Expensify/App/assets/13264774/f1d31eb8-e667-406a-8b0b-dab5a8e001ff)

#### Manually updating the timestamps of the report actions:
```sql
sqlite> SELECT * FROM reportActions WHERE reportActionID = 1695655901254895829;
created                  reportID          accountID  action  message                                                                                                                                                                        reportActionID     
-----------------------  ----------------  ---------  ------  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------  -------------------
2024-01-12 19:17:37.834  5873902278986266  15         IOU     {"IOUTransactionID":"3064946919122085017","amount":"1100","comment":"","currency":"USD","lastModified":"2024-01-12 19:17:37.834","participantAccountIDs":[15],"type":"split"}  1695655901254895829
sqlite> SELECT * FROM reportActions WHERE reportActionID = 5013158385792148183;
created                  reportID          accountID  action         message                                                                       reportActionID     
-----------------------  ----------------  ---------  -------------  ----------------------------------------------------------------------------  -------------------
2024-01-12 19:17:37.838  5873902278986266  0          REPORTPREVIEW  {"lastModified":"2024-01-12 19:17:37.838","linkedReportID":2595405387559353}  5013158385792148183
sqlite> UPDATE reportActions SET created = '2024-01-12 19:17:37.834' WHERE reportActionID = 5013158385792148183;
sqlite> SELECT * FROM reportActions WHERE reportActionID = 5013158385792148183;
created                  reportID          accountID  action         message                                                                       reportActionID     
-----------------------  ----------------  ---------  -------------  ----------------------------------------------------------------------------  -------------------
2024-01-12 19:17:37.834  5873902278986266  0          REPORTPREVIEW  {"lastModified":"2024-01-12 19:17:37.838","linkedReportID":2595405387559353}  5013158385792148183
```

#### How it displayed with identical timestamps:
![image](https://github.com/Expensify/App/assets/13264774/4a2e27fd-2477-4461-bdc3-b2bb7703a2cb)

![image](https://github.com/Expensify/App/assets/13264774/b658949b-b4cf-410e-83ff-b112d660bcd8)

**Comment by roryabraham** [comment] 2024-01-12 23:45
I was able to reproduce this:

![image](https://github.com/Expensify/App/assets/47436092/2f2ec435-275e-4315-9175-c53341afaea2)

It took two tries. I think there's just a race condition because there's nothing in the sorting order to ensure that the "IOU preview" appears after the "split preview" (apologies for the ambiguous language)

**Comment by roryabraham** [comment] 2024-01-12 23:52
It's a bit hard to get clear on exactly what is supposed to happen optimistically with a bill split, because the [existing tests](https://github.com/Expensify/App/blob/35a6916095300af9dbfb593156470de9952a0b28/tests/actions/IOUTest.js#L798-L1200) don't cover `REPORTPREVIEW` actions, only `IOU` actions.

So whatever the outcome for this particular issue, I hope that we at least have an external contributor update all scenarios in `IOUTest.js` to cover the optimistic, success, and failure data for the `REPORTPREVIEW` actions

cc @cristipaval

**Comment by brunovjk** [comment] 2024-01-13 02:31
> update all scenarios in `IOUTest.js` to cover the optimistic, success, and failure data for the `REPORTPREVIEW` actions

@roryabraham  can I work on it?

**Comment by brunovjk** [comment] 2024-01-13 02:44
> I think there's just a race condition because there's nothing in the sorting order to ensure

Exactly, I believe it is worth reviewing [ReportActionsUtils.getSortedReportActions](https://github.com/Expensify/App/blob/744e35c85157ecef9cdfab81a0ab56891dc507f9/src/libs/ReportActionsUtils.ts#L189C1-L215C8).

> update all scenarios in `IOUTest.js` to cover the optimistic, success, and failure data for the `REPORTPREVIEW` actions

@roryabraham If we do it, can I work on it?

**Comment by roryabraham** [comment] 2024-01-13 04:19
> Exactly, I believe it is worth reviewing [ReportActionsUtils.getSortedReportActions](https://github.com/Expensify/App/blob/744e35c85157ecef9cdfab81a0ab56891dc507f9/src/libs/ReportActionsUtils.ts#L189C1-L215C8).

I'm not sure yet. For sure the canonical order of reportActions on a report comes from the server. I think we need to have a wider conversation about this because the `REPORTPREVIEW` action is the only reportAction whose `created` value ever changes in the database, and that's a bit strange.

One solution could be to update the back-end with a 1ms sleep in _The Right Place™_ to ensure that the `REPORTPREVIEW` action appears after the `IOU` action in the report. I don't think it's likely that we want to change the primary sorting criteria to be something other than `created` timestamp... 🤔 

Sorry, not sure the best solution here and need to spend some more time discussing it before we greenlight a solution.

**Comment by brunovjk** [comment] 2024-01-13 15:19
Absolutely, @roryabraham. You brought up a solid point about the only ever-changing created value for REPORTPREVIEW in the database. The 1ms sleep idea seems like a quick fix; I'm with you—let's see if we can unearth a more elegant solution.

Totally get the need for more discussion before giving the green light.
Happy to jump in if need any help.

**Comment by kbecciv** [comment] 2024-01-13 18:20
Issue is reproducible v.1.4.24-7

https://github.com/Expensify/App/assets/93399543/fa5e815f-c29a-4db1-9567-2b8af26f355b

**Comment by joelbettner** [comment] 2024-01-15 19:55
I was able to reproduce this, but I had to have the timestamp for the `REPORTPREVIEW` action be BEFORE (not the same as) the timestamp for the `IOU` action.

So, I think this can easily be sorted in the front end.

**Comment by roryabraham** [comment] 2024-01-15 20:19
Mentioned this over DMs, but it's critical that the sorting order of reportActions (or reports, for that matter) to be the same in both the front-end and the back-end. Currently they're actually out-of-sync and we might need to update [this query](https://github.com/Expensify/Auth/blob/6745e475ae16324048c854d8973dd8ab1c5fb528/auth/lib/Report.cpp#L6209-L6263) to account for [this piece of front-end logic](https://github.com/Expensify/App/blob/7dc384c9f9e508691a8477315765b95fe47f8418/src/libs/ReportActionsUtils.ts#L206-L209)

Failure to do this might lead to the `previousReportActionID` essentially being "wrong" from the front-end's perspective, which [after comment linking is merged](https://github.com/Expensify/App/pull/30269) could lead to rendering issues and potentially an infinite loop of API calls trying to "fill the gap" from the "missing" reportActions.

This issue is not that urgent, so I want to make sure we take our time to get this right, as the potential downside is pretty bad

**Comment by roryabraham** [comment] 2024-01-15 21:10
@joelbettner and I are a bit confused about this, but have some general thoughts:

- It seems like `REPORTPREVIEW` actions are not generated optimistically.
- I further feel that they are weird in that they're the only actions that can move their position in the front-end. It also seems like they're a duplicated source of truth about another report – might it be simpler to just generate report previews on the fly in the front-end only?
- The requirement to sync reportAction sorting between the front-end and the back-end kind of sucks. @perunt might it be possible to just update the reportAction sorting in the front-end to just trust the `previousReportActionID` from the back-end? Then a "gap" is detected anywhere where a `previousReportActionID` references a reportAction that we just don't have?
- It also seems like, at the time when this bug occurs, the timestamps of the `IOU` and `REPORTPREVIEW` actions are correct in the database, but incorrect in Onyx. So there's some place in the back-end where we're forgetting to update one or both of those actions in Onyx via Pusher or reliable updates.

**Comment by roryabraham** [comment] 2024-01-15 21:18
Pretty confused because if the `REPORTPREVIEW` action isn't being generated optimistically, and it isn't coming from the `SplitBill` API response, then where is it coming from?

**Comment by roryabraham** [comment] 2024-01-15 21:21
cc @cristipaval any insights here?

**Comment by roryabraham** [comment] 2024-01-16 00:02
> It seems like REPORTPREVIEW actions are not generated optimistically.

This does seem like it might be missing from the `IOU.splitBill` action, but I did find [ReportUtils.buildOptimisticReportPreview](https://github.com/Expensify/App/blob/dcd6f5a2a9c115440b8b8c2b376e28771da594a2/src/libs/ReportUtils.ts#L2888-L2925)

**Comment by cristipaval** [comment] 2024-01-16 11:36
> @joelbettner and I are a bit confused about this, but have some general thoughts:
> 
> * It seems like `REPORTPREVIEW` actions are not generated optimistically.

Report previews have changed a lot in the front-end since they were created. Tagging @youssef-lr as I know he's done a decent amount of work around `SplitBill`

> * I further feel that they are weird in that they're the only actions that can move their position in the front-end. It also seems like they're a duplicated source of truth about another report – might it be simpler to just generate report previews on the fly in the front-end only?

We discussed this idea when we created report previews. It was decided to have a report action in the database for the report previews because we want them to behave like a report preview, with the ability to react to, reply-in-thread, etc.
The information displayed on the report previews is gathered on the fly. In the database, we store minimal info like `linkedReportID`, which is the ID of the report that we're _previewing_. I don't think we have duplicated sources of truth.

> * The requirement to sync reportAction sorting between the front-end and the back-end kind of sucks. @perunt might it be possible to just update the reportAction sorting in the front-end to just trust the `previousReportActionID` from the back-end? Then a "gap" is detected anywhere where a `previousReportActionID` references a reportAction that we just don't have?

I do agree with this. If we agree on another approach, we would also have to refactor the way we sort `CREATED` report actions. They are always lower than any other report actions, exactly as `REPORTPREVIEWS` should always be greater when the timestamp is the same.

> * It also seems like, at the time when this bug occurs, the timestamps of the `IOU` and `REPORTPREVIEW` actions are correct in the database, but incorrect in Onyx. So there's some place in the back-end where we're forgetting to update one or both of those actions in Onyx via Pusher or reliable updates.
>   
>   * Note: I don't see any reference to a `REPORTPREVIEW` action in the response to `SplitBill`

cc'ing @youssef-lr for the last statement here, let me know if you're the wrong person to tag about `SplitBill`

**Comment by joelbettner** [comment] 2024-01-16 19:23
I've been doing some digging.

I found[ that this query](https://github.com/Expensify/Auth/blob/6745e475ae16324048c854d8973dd8ab1c5fb528/auth/lib/Report.cpp#L6209-L6263) does not run when we create a split. Shouldn't it be? Since that query is "the source of truth" for the order of the report actions, when we are creating new report actions by adding splits, I _think_ we should be running that query...no?

I am getting the report actions out of order when I create a new split or add to an existing split:
<img width="476" alt="image" src="https://github.com/Expensify/App/assets/13264774/cb16d6ae-c2bb-4c68-8f84-c6ca0f2a789e">

But as soon as I refresh the page, the query runs and the report actions are back in the correct order:
<img width="452" alt="image" src="https://github.com/Expensify/App/assets/13264774/61d032cc-de0b-4199-a2a0-ccc2a44376f0">

**Comment by joelbettner** [comment] 2024-01-16 20:04
I also did this...

I added some console logging in the `getSortedReportActions` function [here](https://github.com/Expensify/App/blob/2a5a3a92679bc27182295c470417bc2ee6c500f4/src/libs/ReportActionsUtils.ts#L198-L200):
```jsx
        // First sort by timestamp
        if (first.created !== second.created) {
            if (first.actionName === CONST.REPORT.ACTIONS.TYPE.REPORTPREVIEW) {
                console.log('report preview created: ', first.created);
            }
            return (first.created < second.created ? -1 : 1) * invertedMultiplier;
        }
```

Then I started adding splits.

#### Initial creation of the split bill --> the created time on the front end does not match the created time saved in the db:
![image](https://github.com/Expensify/App/assets/13264774/245983a2-fbb6-490a-b358-2721461ded60)
![image](https://github.com/Expensify/App/assets/13264774/0e1dc048-ee97-4045-aa0f-183596729231)

#### After a refresh --> the created still does not match the time saved in the db but everything displays in the correct order because [this query](https://github.com/Expensify/Auth/blob/6745e475ae16324048c854d8973dd8ab1c5fb528/auth/lib/Report.cpp#L6209-L6263) ran which returned all the entries in the correct order regardless of their timestamp:
![image](https://github.com/Expensify/App/assets/13264774/8d5a64fd-f167-4f25-a249-640af6926c0a)
![image](https://github.com/Expensify/App/assets/13264774/0e1dc048-ee97-4045-aa0f-183596729231)

#### I added another split to the report --> the created time on the front end still does not update for the report preview and things display in the incorrect order again:
![image](https://github.com/Expensify/App/assets/13264774/597c54f7-3de9-407a-9758-1a0e97bac563)
![image](https://github.com/Expensify/App/assets/13264774/7df0750e-1740-46e1-b1b9-f9cd8425e831)

#### I refreshed the page --> things displayed in the correct order again despite having the incorrect timestamp in the front end:
![image](https://github.com/Expensify/App/assets/13264774/8991cd87-d8e2-4631-b0e7-a7ea4ada0a24)
![image](https://github.com/Expensify/App/assets/13264774/7df0750e-1740-46e1-b1b9-f9cd8425e831)


cc: @roryabraham @cristipaval @youssef-lr 
It looks like MAYBE the report preview action is being optimistically created with a timestamp, but that timestamp never gets updated after the report preview is successfully created?? What do you think?

**Comment by youssef-lr** [comment] 2024-01-16 20:45
@roryabraham we do build the optimistic report preview [here](https://github.com/Expensify/App/blob/f37dfca4a0cc417f9d56b96e98f88a5b3c3dc9e6/src/libs/actions/IOU.js#L1570). I was also able to reproduce this, I can see that the `REPORTPREVIEW` action has the optimistic `created` timestamp, but the `IOU` has the server's timestamp

<img width="771" alt="Screenshot 2024-01-16 at 21 36 11" src="https://github.com/Expensify/App/assets/9680864/74ff0573-9d6b-4527-9603-567d6a3236e9">

I think the issue here is that we're not pushing the updated `REPORTPREVIEW` back to the frontend. So I think this is a backend issue, as when you log out and log back in, the actions get sorted properly. I verified the [code](https://github.com/Expensify/Web-Expensify/blob/9fdc48b6f91b5b38177c2fb44a7565aac8c3c405/lib/ReportAPI.php#L4616) and we don't really send back the updated `REPORTPREVIEW`, so it remains with the optimistic timestamp only. For comparison, [here's](https://github.com/Expensify/Web-Expensify/blob/9fdc48b6f91b5b38177c2fb44a7565aac8c3c405/lib/ReportAPI.php#L4946) `CompleteSplitBill` which sends back the updates `REPORTPREVIEW`.

**Comment by roryabraham** [comment] 2024-01-17 20:48
Great, thanks for all the investigation and discussion everyone. It looks like [this PR](https://github.com/Expensify/Web-Expensify/pull/40549) will most likely fix this issue. Thanks @youssef-lr!

We're further discussing `REPORTPREVIEW` actions and `previousReportActionID` [here](https://expensify.slack.com/archives/C035J5C9FAP/p1705364872583459?thread_ts=1705035404.136629&cid=C035J5C9FAP)

**Comment by joelbettner** [comment] 2024-01-25 16:05
Not sure why this didn't get closed when the PR was deployed. I'm going to close it.

**Closed by joelbettner** 2024-01-25 16:05 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Bug
