### ISSUE TITLE
Android - Reimburse expenses - the rate value is reset to zero after the system allows entering more than three digits after the dot, error message displayed after. 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11058] opened 2022-09-16 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10974 

## Action Performed:
1. Open the App and login with any account
2. Go to Settings->Workspace->Reimburse expenses
3. Try entering more than three digits after the period. You may need to close the program before that

## Expected Result:
1. It is not possible to enter more than three digits after a dot (comma)
2. The rate should not reset and the error should not appear

## Actual Result:
1. The system is allow entering more than three digits after a dot (comma)
2. Error message displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190669016-3e86687e-5671-423f-a35f-43d1d65b61a0.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment] 2022-09-16 15:19
This can be external

**Comment by luacmartins** [comment] 2022-09-16 15:28
@Justicea83 this is a deploy blocker and should be handled internally because of urgency in the fix. Removing the `External` label.

**Comment by Justicea83** [comment] 2022-09-16 15:30
Ohk, thanks for picking it up, wraping up here

**Comment by luacmartins** [comment] 2022-09-16 16:56
I can reproduce inputting more than 3 digits on android and iOS, however I could not reproduce the error message nor the value being reset to 0.

**Comment by francoisl** [comment] 2022-09-16 17:18
Interesting, have you managed to identify a clear pattern of when it happens? I'm trying the same exact steps as the video and randomly minimizing/reopening the app but can't reproduce (on Android). I wonder if it could have something to do with this PR: https://github.com/Expensify/App/pull/10468.

**Comment by luacmartins** [comment] 2022-09-16 17:21
The error message suggests that the policy has been updated while we were offline, so maybe going offline and editing the policy on OldDot would trigger the error?

I'm triggering that error on dev, but the rate is reset to the original amount after the call fails and the error is shown.

**Comment by luacmartins** [comment] 2022-09-16 17:35
@kbecciv we are having issues reproducing the rate being reset to 0. Is this consistently reproducible for you?

**Comment by luacmartins** [comment] 2022-09-16 20:10
I was able to reproduce reliably as well, but I also see the problem in prod. I'll remove the blocker label and make this an external issue.

**Comment by luacmartins** [comment] 2022-09-16 20:11
Actually, I'll keep this one internal since it might involve the new API command.

**Comment by luacmartins** [comment] 2022-09-19 14:20
Gonna try to investigate this issue this week

**Comment by luacmartins** [comment] 2022-09-22 17:37
I think this might be related to https://github.com/Expensify/Expensify/issues/229696 cc @jasperhuangg

**Comment by luacmartins** [comment] 2022-10-03 21:01
No updates yet. I'll work on it this week.

**Comment by luacmartins** [comment] 2022-10-03 23:15
I see this in the logs:

```
 WARN  Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"82":{},"51174":{"module":"ReactNativeBlobUtil","method":"emitExpiredEvent"},"51574":{},"51576":{},"51578":{},"51580":{},"51582":{},"51584":{},"51586":{},"51588":{},"51590":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51592":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51594":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51596":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51598":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51600":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51602":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51604":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51606":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51608":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51610":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51612":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51614":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51616":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51618":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51620":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51663":{"module":"ReanimatedModule","method":"getValue"},"51714":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51716":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51959":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51962":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51965":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51968":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51971":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51974":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51977":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51980":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51983":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51986":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51989":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51992":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51995":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"51998":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"52001":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"52004":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"52007":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"52010":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"52013":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"52016":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"52019":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"...(truncated keys)...":451} 
    at TouchableOpacity (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:91101:36)
    at TouchableOpacity
    at RCTView
    at View
    at Hoverable (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:262981:70)
    at OptionRowLHN (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:356409:63)
    at withLocalize(OptionRowLHN)
    at RCTView
    at View
    at VirtualizedListCellContextProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:100945:24)
    at CellRenderer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:98352:36)
    at RCTScrollContentView
    at RCTScrollView
    at ScrollView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:98648:36)
    at ScrollView
    at VirtualizedListContextProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:100919:25)
    at VirtualizedList (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:97000:36)
    at FlatList (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:96348:36)
    at RCTView
    at View
    at LHNOptionsList (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:356272:36)
    at RCTView
    at View
    at SidebarLinks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:355939:36)
    at withOnyx(SidebarLinks) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at withWindowDimensions(Component)
    at WithCurrentUserPersonalDetails(withWindowDimensions(Component)) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273363:35)
    at withOnyx(Component) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at withLocalize(Component)
    at RCTView
    at View
    at RCTView
    at View
    at LoginKeyboardAvoidingView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:102408:36)
    at RCTView
    at View
    at BaseScreenWrapper (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:275482:36)
    at withNetwork(BaseScreenWrapper)
    at withOnyx(withNetwork(BaseScreenWrapper)) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at withWindowDimensions(Component)
    at withNavigation(withWindowDimensions(Component)) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273104:101)
    at ScreenWrapper (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:275399:22)
    at BaseSidebarScreen (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:355673:36)
    at withDrawerState(BaseSidebarScreen) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:347342:105)
    at SidebarScreen
    at withOnyx(SidebarScreen) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at withWindowDimensions(Component)
    at withLocalize(withWindowDimensions(Component))
    at withNavigation(withLocalize(withWindowDimensions(Component))) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273104:101)
    at RCTView
    at View
    at AnimatedComponent(View) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:119102:38)
    at RCTView
    at View
    at AnimatedComponent(View) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:119102:38)
    at PanGestureHandler (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:113303:38)
    at PanGestureHandler (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:349813:34)
    at DrawerView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:349926:36)
    at DrawerViewBase (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:347616:22)
    at RCTView
    at View
    at GestureHandlerRootView
    at RCTView
    at View
    at SafeAreaProviderCompat (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:254307:25)
    at DrawerView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:347836:27)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:219162:24)
    at DrawerNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:347493:32)
    at BaseDrawerNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:357143:36)
    at withWindowDimensions(BaseDrawerNavigator)
    at MainDrawerNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:344438:59)
    at withOnyx(MainDrawerNavigator) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at StaticContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:219454:17)
    at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:215146:24)
    at SceneView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:219359:22)
    at RCTView
    at View
    at RCTView
    at View
    at RCTView
    at View
    at CardSheet (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:258005:23)
    at RCTView
    at View
    at AnimatedComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:95547:38)
    at AnimatedComponentWrapper
    at PanGestureHandler (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:113303:38)
    at PanGestureHandler (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:258092:34)
    at RCTView
    at View
    at AnimatedComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:95547:38)
    at AnimatedComponentWrapper
    at RCTView
    at View
    at Card (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:257433:36)
    at CardContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:257027:34)
    at RNSScreen
    at AnimatedComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:95547:38)
    at AnimatedComponentWrapper
    at MaybeFreeze (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:258318:23)
    at Screen (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:258365:36)
    at MaybeScreen (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:258161:24)
    at RNSScreenContainer
    at ScreenContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:258484:31)
    at MaybeScreenContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:258146:23)
    at RCTView
    at View
    at Background (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:253027:21)
    at CardStack (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:254563:36)
    at RCTView
    at View
    at SafeAreaProviderCompat (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:254307:25)
    at RCTView
    at View
    at GestureHandlerRootView
    at StackView (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:252030:36)
    at CustomRootStackNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:250962:24)
    at AuthScreens (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:250403:36)
    at withOnyx(AuthScreens) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at withWindowDimensions(Component)
    at AppNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:250246:14)
    at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:215146:24)
    at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:214695:28)
    at ThemeProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:220794:21)
    at NavigationContainerInner (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:220670:26)
    at NavigationRoot (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:250171:36)
    at Expensify (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:249938:36)
    at withOnyx(Expensify) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at withLocalize(Component)
    at BaseErrorBoundary (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:169833:36)
    at WindowDimensionsProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:250691:36)
    at RenderersPropsProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:298113:44)
    at ListStyleSpecsProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:299624:25)
    at SharedPropsProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:292626:53)
    at RenderRegistryProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:299106:24)
    at RenderHTMLConfigProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:298755:32)
    at TRenderEngineProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:298528:24)
    at BaseHTMLEngineProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:360250:14)
    at HTMLEngineProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:360166:19)
    at LocaleContextProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:221483:36)
    at withOnyx(LocaleContextProvider) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at withOnyx(LocaleContextProvider)
    at RNCSafeAreaView
    at SafeArea (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:361593:22)
    at RNCSafeAreaProvider
    at SafeAreaProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:253586:24)
    at Private_blockedFromConciergeProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273254:21)
    at withOnyx(Private_blockedFromConciergeProvider) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at CurrentDateProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273254:21)
    at withOnyx(CurrentDateProvider) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at ReportActionsDrafts_Provider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273254:21)
    at withOnyx(ReportActionsDrafts_Provider) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at PersonalDetailsProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273254:21)
    at withOnyx(PersonalDetailsProvider) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at NetworkProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273254:21)
    at withOnyx(NetworkProvider) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:164229:40)
    at ComposeProviders (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273314:54)
    at OnyxProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273208:22)
    at ComposeProviders (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:273314:54)
    at RCTView
    at View
    at GestureHandlerRootView
    at App
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:102950:36)
    at NewExpensify(RootComponent) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.chat.expensify.chat:108745:28)
```

**Comment by luacmartins** [comment] 2022-10-12 14:26
I'm still focused on API refactors, but I have a hunch that we might be able to solve the 3 digits issue by using an uncontrolled input.

**Comment by luacmartins** [comment] 2022-10-21 19:02
I'll try to get to this next week!

**Comment by luacmartins** [comment] 2022-10-31 14:50
We have two distinct bugs here
1. On mobile, there's a delay between user input and component re-render, which makes it possible for the input to display more than 3 decimals. This should be fixed once we enable Fabric.
2. The rate is updated to a different value after coming back online. This should be fixed by [this PR](https://github.com/Expensify/App/pull/12103). 

I'm gonna keep this issue open and monitor it to make sure it's solved.

**Comment by mvtglobally** [comment] 2022-11-03 03:02
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2022-11-03 18:16
I can't reproduce 1 anymore. Now we are down to offline edits being reset when we come back online which should be resolved by https://github.com/Expensify/Expensify/issues/229696

**Comment by JmillsExpensify** [comment] 2022-11-03 18:21
Ok cool, so then I'll update the hold and re-test when that one is merged.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:20
Still waiting on https://github.com/Expensify/App/pull/12219 to merge.

**Comment by luacmartins** [comment] 2022-11-07 15:56
https://github.com/Expensify/App/pull/12219 is merged. Gonna retest this.

**Comment by luacmartins** [comment] 2022-11-07 19:19
This issue was fixed by https://github.com/Expensify/App/pull/12219! 🎉 

https://user-images.githubusercontent.com/22219519/200395872-09dc20b5-9e3c-49b9-a8b8-c57b53a0cfe2.mov

Closing. Please reopen if needed.

**Closed by luacmartins** 2022-11-07 19:19 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by JmillsExpensify** [comment] 2022-11-08 05:09
Oh nice! Thanks for jumping on that so quickly and testing!
