### ISSUE TITLE
Distance request - Wrong track on map for request made offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37912] opened 2024-03-07 17:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2730099
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go Offline
2. Make Distance request in any chat
3. Place Start/Finish waypoints like 'Los Angeles, USA' and 'Las Vegas, USA' > complete request
4. Go online
5. Open report details

## Expected Result:
Expect to see track on map from Start to Finish for selected waypoints

## Actual Result:
Track on map is not correspond to Start and Finish waypoints

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/94ec7fad-a810-452a-8c99-e6ea44c65a6b

![Bug6405747_1709832880040!Screen_Shot_2024-03-07_at_6 53 37_PM](https://github.com/Expensify/App/assets/78819774/a7965ac4-54c7-4985-9d03-dd28591960e8)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a33bef6a3d2f883f</li>
        <li>Upwork Job ID: 1766150566496485376</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-07 17:45
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by lanitochka17** [comment] 2024-03-07 17:45
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment] 2024-03-07 21:31
I think this should be internal because the backend has a problem with differentiated locations with the same name.

For Example, The address for *Las Vegas, USA* needs to be *Las Vegas, **CA**, USA* , So it does not respond with a different location.

![Screenshot 2024-03-08 at 00 20 47](https://github.com/Expensify/App/assets/22982173/99c2fb19-6912-402e-b42f-4f82870326a4)

**Comment by Tony-MK** [comment] 2024-03-07 22:00
*Las Vegas, USA* should be *Las Vegas, **NV**, USA*, and *Los Angeles, USA* should be *Los Angeles, **CA**, USA*, so the backend does not respond with a different location.

Ipresume this issue should be fixed internally because the backend has a problem with differentiated locations with the same name.

![Screenshot 2024-03-08 at 00 55 42](https://github.com/Expensify/App/assets/22982173/ea7971bc-03cd-4538-b212-2f068e4b2910)


![Screenshot 2024-03-08 at 00 20 47](https://github.com/Expensify/App/assets/22982173/99c2fb19-6912-402e-b42f-4f82870326a4)

**Comment by Tony-MK** [comment] 2024-03-07 22:01
*Las Vegas, USA* should be *Las Vegas, **NV**, USA*, and *Los Angeles, USA* should be *Los Angeles, **CA**, USA*, so the backend does not respond with a different location.

I presume this issue should be fixed internally because the backend has a problem with differentiated locations with the same name.

![Screenshot 2024-03-08 at 00 55 42](https://github.com/Expensify/App/assets/22982173/ea7971bc-03cd-4538-b212-2f068e4b2910)


![Screenshot 2024-03-08 at 00 20 47](https://github.com/Expensify/App/assets/22982173/99c2fb19-6912-402e-b42f-4f82870326a4)

**Comment by sakluger** [comment] 2024-03-08 17:14
I agree that this is a bug. Both the original bug description, plus the detail added [here](https://github.com/Expensify/App/issues/37912#issuecomment-1984575707) are unexpected behaviors.

**Comment by neil-marcellini** [comment] 2024-03-08 18:17
I'm putting up a fix

**Comment by sakluger** [comment] 2024-03-14 18:56
The [PR](https://github.com/Expensify/Web-Expensify/pull/41200) is deployed to prod and no contributors reviewed the PR. We're good to close this one.

**Closed by sakluger** 2024-03-14 18:56 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
