### ISSUE TITLE
[Awaiting C+ payment] [$1000] App crashes on login after opening split bill details page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23568] opened 2023-07-25 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on split bill
3. Enter any amount and continue
4. Select any 1 user and complete the split bill process
5. In the user report, click on split bill message to open split bill details page
6. Copy the URL, logout, paste the URL and login again, eg URL format: https://staging.new.expensify.com/r/5686244339424710/split/2464435729537161526
7. Observe that app crashes
## Expected Result: 
App should not crash when we open split bill details page
## Actual Result: 
App crashes when we logout and login with split bill details page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/95e78c47-369a-497a-947f-5c939a61883d

https://github.com/Expensify/App/assets/43996225/90347da8-14b0-4525-962d-9139896d9876

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690262928105189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168304d5ea41d503d</li>
        <li>Upwork Job ID: 1684650192147705856</li>
        <li>Last Price Increase: 2023-07-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 25865336</li>
<li>dhanashree-sawant | Reporter | 25865338</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-27 13:21
👋 @dukenv0307 how related is this to [this issue](https://github.com/Expensify/App/issues/21268)? CC: @aldo-expensify

**Comment by aldo-expensify** [comment] 2023-07-27 19:17
If the root cause @dukenv0307 explained [here](https://github.com/Expensify/App/issues/23568#issuecomment-1650314041) is correct, they do appear unrelated to me.

**Comment by trjExpensify** [comment] 2023-07-27 19:41
Cool, will move on `external` for now! :)

**Comment by gulxarahmad** [comment] 2023-07-27 19:49
**Root cause of the problem:**
The root cause of the app crash needs to be investigated further to provide a definitive answer. It could be due to a variety of reasons, such as a bug in the React Native code, compatibility issues between different platforms, memory management problems, or even server-related issues.

**Changes to solve the problem:**
To address the app crash issue, the following steps can be taken:

Bug Investigation: Start by thoroughly investigating the crash logs and error messages reported by the app. Identify patterns or common scenarios that lead to the crash. This will help in pinpointing the cause of the issue.

Reproduce the Bug: Try to reproduce the crash on different devices and platforms (iOS and Android) using the same version of the app. This step is essential to ensure the bug is replicable and consistent across devices.

Inspect Split Bill Details Page: Examine the Split Bill Details page to check if there are any specific elements or interactions triggering the crash. Review the React Native code associated with this page to identify potential issues.

Memory Management: Analyze the memory usage of the app during the login process after opening the Split Bill Details page. Check for any memory leaks or excessive memory usage that could lead to crashes, especially if the user navigates between different pages frequently.

Unit Testing: Write unit tests to cover the critical parts of the code related to the login process and the Split Bill Details page. These tests will help catch regressions and ensure the stability of the app.

React Native Version and Dependencies: Ensure that the React Native version used is stable and compatible with the required dependencies. Consider upgrading to the latest stable version if it addresses any known issues.

Error Handling: Implement proper error handling mechanisms throughout the app to gracefully handle unexpected situations and prevent crashes.

Platform-Specific Optimization: If the crash is specific to a particular platform (iOS or Android), perform platform-specific optimizations and debugging to resolve the issue.

Beta Testing: Once the proposed changes are implemented, conduct beta testing with a group of users to validate the fix and gather feedback.

Remember that the actual solution will require a more detailed analysis of the codebase and the crash reports. The proposal should outline the general approach and steps to tackle the problem effectively.

**Comment by mananjadhav** [comment] 2023-07-28 20:35
Thanks for the proposal @dukenv0307. Your RCA is correct, but I have a few questions on the proposal.

1. Why do we want to remove `withReportOrNotFound` page?

> We should add the check to return loading page before this line

2. which line?

3.  Can we simplify the proposal because the isLoadingReportingData, etc. checks are already in the `withReportOrNotFound` component?

**Comment by mananjadhav** [comment] 2023-07-30 20:28
Thanks for the response, @dukenv0307. I meant why not just add checks for `reportAction`. Why remove the `withReportOrNotFound` hoc?

**Comment by mananjadhav** [comment] 2023-07-31 11:53
I think we can go ahead with your proposal @dukenv0307. You've got the RCA as well as the suggestion. But I have two options of the implementation here.

1. The way you suggested, remove the HoC from the component, copy the `report` checks code to the component and add `reportAction` checks
2. Figure out a way to just add `reportAction` checks, without touching much of the `withReportOrNotFound`.
3. Create a new HoC that caters to report as well as reportAction.

I am going to confirm this from an internal engineer too.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2023-07-31 12:15
Yeah I thought so. Let's wait for @Li357 to respond. Thanks for the patience here.

**Comment by Li357** [comment] 2023-07-31 20:53
I agree, a new HOC would be great. I imagine future components that depend on a specific action being loaded would benefit from a central place of the logic.

**Comment by mananjadhav** [comment] 2023-08-01 04:04
@dukenv0307 I see you've linked a PR, but I don't see the how its related to the current issue.

**Comment by mananjadhav** [comment] 2023-08-13 11:43
@trjExpensify This is ready for payout on 08/15 but the title wasn't updated.

Also I couldn't pinpoint to a specific PR causing this. I think we should add a regression test for this one as it is was crashing the app and related to IOU. The test steps from the PR are good enough for the regression test.

@Li357 wdyt?

**Comment by trjExpensify** [comment] 2023-08-14 12:26
Updated the title! :) 

>I think we should add a regression test for this one as it is was crashing the app and related to IOU. The test steps from the PR are good enough for the regression test.

Yeah cool, I'll ask Applause about what they think is best re: opening from deep links. We should do the same with request money as well.

**Comment by trjExpensify** [comment] 2023-08-15 11:53
Okay, confirming payments as follows:

- @dhanashree-sawant $250 for the bug report (paid!)
- @mananjadhav $1,500 for C+ & #urgency bonus (awaiting a request)
- @dukenv0307 $1,500 for the fix (paid!)

**Comment by mananjadhav** [comment] 2023-08-15 12:05
I’ve raised my request on NewDot.

**Comment by JmillsExpensify** [comment] 2023-08-15 17:21
Reviewed the details for @mananjadhav. Approved for payment in NewDot based on BZ summary above.

**Comment by trjExpensify** [comment] 2023-08-15 17:22
Dope, we're all set then. Closing!

**Closed by trjExpensify** 2023-08-15 17:22 UTC
Labels: Reviewing, External, Weekly, Bug
