### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000]  Incorrect Error Handling for Invalid Phone Number during Sign-In

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23803] opened 2023-07-28 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging Expensify.
2. Enter an invalid phone number.
3. Note that the error handling message states "The email entered is invalid. Please fix the format and try again," without addressing the invalid phone number.
## Expected Result: 
The error handling message should indicate that the entered email or phone number is invalid, with a prompt to fix the format and proceed. with addressing the invalid phone number
## Actual Result: 
The error handling for invalid phone numbers does not inform the user about the invalid input. Only the error handling for invalid emails is displayed, instructing the user to enter a valid email and proceed, without addressing the issue of an invalid phone number during the sign-in process.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1628cd5e-4caa-4066-9f74-3953aad6b5e3

![Snip - New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/f0432cc4-fd43-4ade-819b-8eb988137cfa)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690452210915339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017aee1e591c3b4eb3</li>
        <li>Upwork Job ID: 1686019986563760128</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25933963</li>
<li>akinwale | Contributor | 25933965</li>
<li>tewodrosGirmaA | Reporter | 25933967</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-07-28 15:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The wrong error message (e-mail related) is displayed when trying to validate an invalidate phone number for the login screen.

### What is the root cause of that problem?
The `ValidationUtils.isNumericWithSpecialChars` method only checks for a single '+' character at the beginning of a phone number, and when that check passes, it proceeds to try to validate as an email.

### What changes do you think we should make in order to solve the problem?
Update the regex in the `ValidationUtils.isNumericWithSpecialChars` method to correctly validate the number if one or more '+' signs exist.

### What alternative solutions did you explore? (Optional)
None.

**Comment by alphaboss1104** [comment] 2023-07-28 16:45
As I see This isn't an issue.

**Comment by alphaboss1104** [comment] 2023-07-28 16:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Incorrect Error Handling for Invalid Phone Number during Sign-In
### What is the root cause of that problem?
This issue is related to below code.

https://github.com/Expensify/App/blob/ec1ccf8fd058299a94c6694553c4508dd62981ed/src/pages/signin/LoginForm.js#L131-L138

`ValidationUtils.isNumericWithSpecialChars(input)` is checking whether the input string, after removing special characters, consists only of digits and optionally starts with a (+) sign.

### What changes do you think we should make in order to solve the problem?

- Based on the `Expected Result` we can modify the below code logic.
https://github.com/Expensify/App/blob/ec1ccf8fd058299a94c6694553c4508dd62981ed/src/pages/signin/LoginForm.js#L131-L138

-And another approach is we can modify the `regex` in the below code.
https://github.com/Expensify/App/blob/ec1ccf8fd058299a94c6694553c4508dd62981ed/src/libs/ValidationUtils.js#L315-L317

### What alternative solutions did you explore? (Optional)
None

**Comment by akinwale** [comment] 2023-07-31 14:29
> Adding the external label. Overall the logic should be that if an input starts with a “+” then it should default to the phone message error.

@flaviadefaria Could you please clarify this further? I'm assuming that this applies if it's numbers that come after the "+", right? Or should we apply the logic in every scenario where the input begins with a "+"?

**Comment by flaviadefaria** [comment] 2023-07-31 14:50
>@flaviadefaria So the phone number error message should be displayed if the input string starts with '+'?

Yes, I think this makes the most sense. So basically I'd keep all the logic we have in place right now but would have that if an input starts with "+" the we display the phone number error.

**Comment by alphaboss1104** [comment] 2023-07-31 15:02
> > @flaviadefaria So the phone number error message should be displayed if the input string starts with '+'?
> 
> Yes, I think this makes the most sense. So basically I'd keep all the logic we have in place right now but would add that if an input starts with "+" then we display the phone number error.

Thank you for letting me know. I have one more quesiton. For Example if the input is "+test123123123" or "+1123+123", should we display the phone number error message?

**Comment by flaviadefaria** [comment] 2023-07-31 15:43
In my view yes. But I'm getting a buddy check, in Slack, and will update here soon.

**Comment by getusha** [comment] 2023-07-31 17:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect Error handling for invalid phone number while signing in.
### What is the root cause of that problem?
The current isNumericWithSpecialChars function only validates text/numbers that start with a + character. If the following characters are not +, the match will be dismissed.

($) inside the regex is a position anchor that matches the end of the string. 
### What changes do you think we should make in order to solve the problem?


1. Remove `$` from the regex to make it match until the end of the number (Preferred)
```js
 return /^\+?\d*/.test(LoginUtils.getPhoneNumberWithoutSpecialChars(input));
```
3. Modify the regex to match digits with + character.

![Screenshot 2023-07-31 at 8 52 40 PM](https://github.com/Expensify/App/assets/75031127/5ae0f79b-9362-45ea-9a02-7d2168ffd139)

### What alternative solutions did you explore? (Optional)

**Comment by raghavwahi** [comment] 2023-07-31 19:00
In my view, if an input contains a combination of `[0-9], +, -, .` then consider it as a number otherwise consider it as an email address and then generate an error message accordingly.

### Technical Explanation
I can update the function **isNumericWithSpecialChars**
```
function isNumericWithSpecialChars(input) {
    return /^[\d\+\-\.\s]*$/.test(LoginUtils.getPhoneNumberWithoutSpecialChars(input));
}
```

### Test
`+123-456.78 90`: is a number
`+123456789+1234345`: is a number
`+1233493s`: is not a number thus is an email

**Comment by dglalperen** [comment] 2023-07-31 19:15
Contributor details
Your Expensify account email: dagli.solutions@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015edb0423d7096559

**Comment by raghavwahi** [comment] 2023-07-31 19:17
Contributor details
Your Expensify account email: raghavwahi7@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013dd0cff4a30d4c06

**Comment by dglalperen** [comment] 2023-07-31 19:56
## Proposal

### Problem Statement
When attempting to sign in to the application with an invalid phone number, the error message that is displayed relates to an invalid email address. This is misleading for the user, who may not realize that the problem lies with the phone number they have entered.

### Root Cause
The root cause of this problem lies in the validation logic of the login form. The validation method currently checks if the input is not a valid email and not a possible phone number, with the `ValidationUtils.isNumericWithSpecialChars` method. If the input passes these checks, it is assumed to be an invalid phone number. If it does not, it is assumed to be an invalid email. 

The issue arises when a phone number does not fit the criteria for `ValidationUtils.isNumericWithSpecialChars`, but is also not recognized as a possible phone number by the `awesome-phonenumber` library. In this case, the input falls back to being treated as an invalid email, resulting in an inappropriate error message being displayed.

### Proposed Solution

The validation process could be enhanced by introducing more refined checks using regular expressions (regex). This can provide a more accurate categorization of the input as either a phone number or an email address. Here are the proposed changes:

**Solution 1:** Implement two separate regex checks for email and phone number formats. If the input doesn't match either format, an error can be thrown indicating that the user must enter a valid email or phone number. 

**Solution 2:** Enhance the current `ValidationUtils.isNumericWithSpecialChars` function to handle more cases for phone numbers, possibly using a more comprehensive regex pattern.

**Solution 3:** In case the input is assumed to be a phone number (for example, it starts with a "+"), prioritize phone number validation and error messages over email validation.

### Alternative Solutions Explored
The alternative solution would be to continue using dedicated libraries for email and phone number validation, but enhance the logic to handle edge cases better. However, this could be more complex and may not provide the flexibility and control that regex offers.

By implementing these changes, we can provide a more accurate and helpful error message to the user, improving the usability of the login form and potentially increasing successful sign-ins.

**Comment by saalimzafar** [comment] 2023-07-31 23:31
From this 
`const [formError, setFormError] = useState(false);`

To this will solve many problems
`const [formError, setFormError] = useState(null);`

Inside LoginForm.js

**Comment by flaviadefaria** [comment] 2023-08-02 14:41
@mollfpr any thoughts on the proposals above?

**Comment by mollfpr** [comment] 2023-08-02 15:19
@raghavwahi Are [this](https://github.com/Expensify/App/issues/23803#issuecomment-1658971234) a proposal? If yes, please submit it with [PROPOSAL_TEMPLATE](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md).

@saalimzafar Please post your proposal with the template. Thanks!


@flaviadefaria What I got from ChatGPT, the plus sign at the beginning of the email is not a valid email address. So we should be okay checking the phone number with the plus sign in the beginning.

**Comment by akinwale** [comment] 2023-08-02 15:31
> @flaviadefaria What I got from ChatGPT, the plus sign at the beginning of the email is not a valid email address. So we should be okay checking the phone number with the plus sign in the beginning.

@mollfpr When you get a chance to review the proposals, Solution 3 in [my proposal](https://github.com/Expensify/App/issues/23803#issuecomment-1655884925) takes care of this scenario. Thanks.

**Comment by getusha** [comment] 2023-08-02 15:34
>the plus sign at the beginning of the email is not a valid email address. So we should be okay checking the phone number with the plus sign in the beginning.

@mollfpr both approaches in my proposal also takes care of the case. thank you!

**Comment by mollfpr** [comment] 2023-08-02 15:36
@akinwale There's a flaw in your solution 3; the US phone number can be input without a plus sign, so `1234832+3232` is considered an email.

@getusha Yeah, I prefer the regex solution to reuse it anywhere with the function. But I'll go through all the proposals tomorrow. It's already late for me.

**Comment by akinwale** [comment] 2023-08-02 15:40
> @akinwale There's a flaw in your solution 3; the US phone number can be input without a plus sign, so `1234832+3232` is considered an email.
> 
> @getusha Yeah, I prefer the regex solution to reuse it anywhere with the function. But I'll go through all the proposals tomorrow. It's already late for me.

In that case, my solution 2 using regex matching should work.

**Comment by saalimzafar** [comment] 2023-08-02 16:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we are trying to solve is the incorrect error handling for invalid phone numbers during the sign-in process. Currently, when users enter a wrong phone number, the error message displayed is related to an invalid email, which can confuse users and hinder a smooth sign-in experience.

### What is the root cause of that problem?
The root cause of this problem is the incorrect error initialization. The initial state of `formError` is set to `false` instead of `null`. This incorrect initialization affects the error handling logic in the `LoginForm` component, causing it to display the wrong error message for invalid phone numbers.

### What changes do you think we should make in order to solve the problem?

To solve the problem, we need to update the error handling logic in the `LoginForm` component. The correct approach is to ensure that the initial state of `formError` is set to `null` instead of `false` to properly handle error initialization.


### What alternative solutions did you explore? (Optional)

NA

**Comment by raghavwahi** [comment] 2023-08-03 08:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We're working on fixing a problem. Right now, when people type in the wrong phone number while trying to sign up, they see an error message about email being wrong. This can be confusing and make signing in hard. We want to make this better.

### What is the root cause of that problem?
The problem lies with in the [ValidationUtils.js](https://github.com/Expensify/App/blob/ec1ccf8fd058299a94c6694553c4508dd62981ed/src/libs/ValidationUtils.js#L315-L317) module. The Regex in function `isNumericWithSpecialChars` fails to identify if a '+' is added in between the input. This needs to be updated.

Furthermore, There can be a `.` in the input number so regex in [CONST.js](https://github.com/Expensify/App/blob/ec1ccf8fd058299a94c6694553c4508dd62981ed/src/CONST.js#L1135) should also be updated.

### What changes do you think we should make in order to solve the problem?
To address this issue, I recommend making the following changes:

1. Update the regular expression in [CONST.js](https://github.com/Expensify/App/blob/ec1ccf8fd058299a94c6694553c4508dd62981ed/src/CONST.js#L1135) as follows:
   ```
   SPECIAL_CHARS_WITHOUT_NEWLINE: /((?!\n)[().-\s\t])/g
   ```

2. Revise the `isNumericWithSpecialChars` function in [ValidationUtils.js](https://github.com/Expensify/App/blob/ec1ccf8fd058299a94c6694553c4508dd62981ed/src/libs/ValidationUtils.js#L315-L317) with the following updated version:
   ```javascript
   function isNumericWithSpecialChars(input) {
       return /^[+\d][\d]*$/.test(LoginUtils.getPhoneNumberWithoutSpecialChars(input));
   }
   ```
### What alternative solutions did you explore? (Optional)
None

**Comment by raghavwahi** [comment] 2023-08-03 08:43
@mollfpr I've added my [proposal](https://github.com/Expensify/App/issues/23803#issuecomment-1663540629) using the [PROPOSAL_TEMPLATE](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md)

**Comment by mollfpr** [comment] 2023-08-03 14:09
>Based on the Expected Result we can modify the below code logic.
>-And another approach is we can modify the regex in the below code.

@alphaboss1104 I don't understand what logic and what regex we should use.

---

@getusha 

>Remove $ from the regex to make it match until the end of the number (Preferred)

It catch and email `asdasa@+asdasdasasdas.ccd` as a phone number.

![Screenshot 2023-08-03 at 21 07 36](https://github.com/Expensify/App/assets/25520267/c6ba8321-ed6f-46fb-af29-d3d4269889f4)

> Modify the regex to match digits with + character

Is this a separate solution or tied to the first one?

**Comment by mollfpr** [comment] 2023-08-03 14:13
@saalimzafar How your solution is to fix the issue? Others proposal mention `ValidationUtils.isNumericWithSpecialChars(loginTrim)` not correctly catch the `+42832932+3232` as a phone number.

**Comment by akinwale** [comment] 2023-08-03 14:17
@mollfpr My updated proposal makes use of a combination of Solution 2 and 3 to solve the issue.
The regex will be updated with my proposed Solution 2.
Then we'll add the `loginTrim` check just before the existing check. This should appropriately capture all scenarios even when the number does not start with a '+' sign.

**Comment by mollfpr** [comment] 2023-08-03 14:19
@akinwale Yes, I agree. I tested your solution 2, which did well for now.

Let's go with solution two on @akinwale  [proposal](https://github.com/Expensify/App/issues/23803#issuecomment-1655884925).

🎀 👀 🎀 C+ reviewed!

**Comment by getusha** [comment] 2023-08-03 14:19
> /^[0-9+]/

@mollfpr it will be like ` /^[0-9+]/`

**Comment by akinwale** [comment] 2023-08-03 22:52
@mollfpr My [PR](https://github.com/Expensify/App/pull/24133) is ready for review. Thanks.

**Comment by akinwale** [comment] 2023-08-16 13:05
@mollfpr @flaviadefaria Just wanted to check in for the BZ checklist and payment. Thanks.

**Comment by mollfpr** [comment] 2023-08-16 17:37
Sorry for the delay 🙏

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This is an improvement for the check on the phone number validation.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression test should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Access the sign-in form.
2. Enter an invalid phone number with additional '+' signs (e.g. 155828282+28888).
3. Verify that the validation error message displayed mentions that the input is an invalid phone number.
4. Enter an invalid phone number starting with a '+' sign, containing additional '+' signs (e.g. +1558223322+12888322).
5. Verify that the validation error message displayed mentions that the input is an invalid phone number.

**Comment by mountiny** [comment] 2023-08-18 21:21
This is ready for payment

**Comment by alexpensify** [comment] 2023-08-21 17:15
Here is the payment summary: 

-  External issue reporter @tewodrosGirmaA $250 
-  Contributor that fixed the issue @akinwale $1500 
-  Contributor+ that helped on the issue and/or PR @mollfpr $1500 

Upwork Job: https://www.upwork.com/jobs/~017aee1e591c3b4eb3

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: Sorry for the delay here, I've factored in the bonuses and completed the process in Upwork. Please confirm that you received it. Thank you!

**Comment by mollfpr** [comment] 2023-08-21 17:26
Received! Thanks @alexpensify 👍

**Comment by akinwale** [comment] 2023-08-21 17:38
@alexpensify Received payment on Upwork. Thanks!

**Comment by tewodrosGirmaA** [comment] 2023-08-21 19:01
@alexpensify Received payment on Upwork. Thanks!

**Comment by alexpensify** [comment] 2023-08-21 23:48
Thank you for these updates! 

@mollfpr before I close the GH, can you please complete the checklist? Thanks!

**Comment by mollfpr** [comment] 2023-08-22 01:21
@alexpensify Here are the [checklists](https://github.com/Expensify/App/issues/23803#issuecomment-1681024355)

**Comment by alexpensify** [comment] 2023-08-22 20:19
@thienlnam could you confirm if you agree with this regression test and I can create that GH? Thanks!

**Comment by thienlnam** [comment] 2023-08-22 23:12
Looks good to me!

**Comment by alexpensify** [comment] 2023-08-24 04:31
Closing - the regression test GH has been created

**Closed by alexpensify** 2023-08-24 04:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
