### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Chat - New font is cut if last message is from Concierge

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20451] opened 2023-06-08 12:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From useA, send message to userB
2. From userB, mark that message as offensive
3. Send a message
4. Mark that message as unread

## Expected Result:
New font should not cut

## Actual Result:
New font cut

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.3

**Reproducible in staging?:** Yes

**Reproducible in production?:**  Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_20230608_084348_New Expensify (1)](https://github.com/Expensify/App/assets/93399543/cafbd4ed-77cf-4388-ac3d-269c6ddcf4d2)
![Simulator Screen Shot - iPhone 13 - 2023-06-06 at 11 45 31](https://github.com/Expensify/App/assets/93399543/7228d729-dc7b-4672-8bc3-f28bb0c65be7)

https://github.com/Expensify/App/assets/93399543/4783c20f-39b9-4edc-91b2-91fb4c44de87

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686032203159789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c26bb0c2ffb6603f</li>
        <li>Upwork Job ID: 1666820544158339072</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by spcheema** [comment] 2023-06-08 15:21
# Proposed solution 

### Please re-state the problem that we are trying to solve in this issue.

New font should not cut
 

**What is the root cause of that problem?**

Unread action indicator `New` is rendering behind the concierge view when message recipient flagged a message.

**What changes do you think we should make in order to solve the problem?**

It can fixed with `z-index: 100` css property.


**What alternative solutions did you explore? (Optional)**
N/A

**Comment by spcheema** [comment] 2023-06-08 15:34
# Proposed solution 

### Please re-state the problem that we are trying to solve in this issue.
New font should not cut
 

**What is the root cause of that problem?**

Unread action indicator is going behind the conceirge view.

**What changes do you think we should make in order to solve the problem?**

It can fixed with `z-index: 100` css property.


**What alternative solutions did you explore? (Optional)**
N/A

**Comment by jeet-dhandha** [comment] 2023-06-08 16:55
# Proposed solution
## Please re-state the problem that we are trying to solve in this issue.
- Problem was that the Unread Indicator's New Text was cutoff due to no margin on `isWhisper` Report.

## What is the root cause of that problem?
- Margin is the main issue and some styling issues in unread indicator.

## What changes do you think we should make in order to solve the problem?
- Changes screen shot are below 
<img width="1023" alt="Screenshot 2023-06-08 at 10 18 09 PM" src="https://github.com/Expensify/App/assets/78416198/e2dac1b4-2d05-44e4-a1a0-393cc7869fc7">
<img width="1021" alt="Screenshot 2023-06-08 at 10 18 03 PM" src="https://github.com/Expensify/App/assets/78416198/55ba2699-38e4-4ead-852f-9f3ffc7abb1a">
<img width="1023" alt="Screenshot 2023-06-08 at 10 17 59 PM" src="https://github.com/Expensify/App/assets/78416198/af277492-7884-4e74-9f40-f0290a29fb8d">

- After Changes the unread indicator looks like this (there are few different image just to get the overall idea.)

<img width="377" alt="Screenshot 2023-06-08 at 10 18 39 PM" src="https://github.com/Expensify/App/assets/78416198/14f151f8-cc7d-4bbf-9307-a14f03fc900b">
<img width="370" alt="Screenshot 2023-06-08 at 10 18 29 PM" src="https://github.com/Expensify/App/assets/78416198/baac331c-b92e-4408-af08-01068a42fe3b">
<img width="366" alt="Screenshot 2023-06-08 at 10 18 19 PM" src="https://github.com/Expensify/App/assets/78416198/0bdd9d76-4cdd-4ade-9d77-8dc7fe42ea95">
<img width="350" alt="Screenshot 2023-06-08 at 10 19 09 PM" src="https://github.com/Expensify/App/assets/78416198/52128fe1-08b4-4e6f-b793-6db67b322c38">


## What alternative solutions did you explore? (Optional)
- N/A

**Comment by spcheema** [comment] 2023-06-09 01:33
# Proposed solution 

### Please re-state the problem that we are trying to solve in this issue.
* Problem was that the UnreadActionIndicator  test `New` on unread message was cutoff due to concierge report  overlapping unread message.

 

**What is the root cause of that problem?**

* Since all elements are styles with flex and flex doesn't support z-index.  But this is not a problem in the case non-native devices.
* Also  native devices (iOS & Android) `z-order, axis or index` is troublesome.
** iOS doesn't support `z Order` styling. It just respects element in the order they come.
** Android does have `elevation` property. After applying the style it has no impact actually due flex style I believe.

**What changes do you think we should make in order to solve the problem?**

As explained in the above section, it's not something we can fix normally. I believe we need to set margin & padding to both parent container for native apps only:

unread indicator container style:
```
    unreadIndicatorContainer: {
        position: 'absolute',
        top: -6,
        left: 0,
        width: '100%',
        height: 20,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
        zIndex: 1,
        ...cursor.cursorDefault,
    }
```
Caveat: UI/UX person might not like the space. Unfortunately there is no other solution for now.

Tested on both iPhone & Android. Screenshot attached.
<img width="327" alt="Pasted Graphic 3" src="https://github.com/Expensify/App/assets/19812199/39a5c0c3-c4d0-4360-967e-90a7a1edfeb9">
<img width="332" alt="Pasted Graphic 4" src="https://github.com/Expensify/App/assets/19812199/62a668d3-b745-433e-a7c9-b5b810df9ce0">
![Pasted Graphic 6](https://github.com/Expensify/App/assets/19812199/346f860f-1430-41af-b493-a091a5dbce3e)

![Pasted Graphic 7](https://github.com/Expensify/App/assets/19812199/a654b6da-3f46-4775-a7f5-fec6c056fd15)

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by jeet-dhandha** [comment] 2023-06-09 02:16
@spcheema I gave that approach a try, but one issue with that solution is that the unreadIndicator ends up overlapping the concierge message.

<img width="1093" alt="Screenshot 2023-06-09 at 7 45 49 AM" src="https://github.com/Expensify/App/assets/78416198/13332647-4af7-418e-b351-29752aafb51c">

**Comment by petromoldovan** [comment] 2023-06-09 10:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In IOS platform, the absolute element that marks the "New" message in the chat is hidden behind EVERY previous element with background color that is not transparent. 

### What is the root cause of that problem?
This is the way the Flatlist works. By default the Flatlist renders element in the way that older elements are not allowed to overflow the newer elements. In chat we use the inverted Flatlist. This means that rows in the bottom(older elements) cannot overflow the upper elements(the newer elements). 

### What changes do you think we should make in order to solve the problem?
I will adjust the following file:
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/components/InvertedFlatList/index.ios.js#L1-L11

I will add the `CellRendererComponent` to flat list that gives us control how every list element is rendered. It is a wrapper for each element. See the react native source code:
https://github.com/facebook/react-native/blob/5cc8ceeae210f2f23ef18ded7b7b614682f0d67b/packages/virtualized-lists/Lists/VirtualizedList.d.ts#L383-L388

To the first rendered `CellRendererComponent` I will assign the highest `zIndex` value which equals to the number of rows in the list. I will decrement the `zIndex` value for the subsequent rows by subtracting row index from the total number of rows in the list. The result is that a row in the bottom has higher `zIndex` than a neighbour row on top of it and hence the absolute element with the "New" message is not blocked.

This solution touches only inverted IOS lists. 

This is my POC that works well for all list sizes:
```
import React, {forwardRef} from 'react';
import BaseInvertedFlatList from './BaseInvertedFlatList';
import {View} from 'react-native';
import lodashGet from 'lodash/get';

function RendererComponent(props) {
  const zIndex = props.rowCount ? props.rowCount - props.index : 1;
  return (
    <View
      // eslint-disable-next-line react/jsx-props-no-spreading
      {...props}
      style={[props.style, { zIndex }]}
    />
  )
}

export default forwardRef((props, ref) => (
    <BaseInvertedFlatList
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...props}
        ref={ref}
        inverted
        CellRendererComponent={(cellRendererProps) => <RendererComponent {...cellRendererProps} rowCount={lodashGet(props, 'data.length', 0)} />}
    />
));
```

Result:

![New end](https://github.com/Expensify/App/assets/15109844/a0c58eac-d0cf-40d2-bb82-fc5b74cf455a)
![New top](https://github.com/Expensify/App/assets/15109844/890e3a7e-d9e2-463e-a016-828014e2f216)


### What alternative solutions did you explore? (Optional)
I could try to fix the issue with styling(margins, borders, paddings etc) but the `zIndex` solution seems to be cleaner.

**Comment by spcheema** [comment] 2023-06-12 02:47
@petromoldovan I tried this one but doesn't work in Android app. Though my personal preference is not to touch style if we can't fix it with zIndex

**Comment by petromoldovan** [comment] 2023-06-12 11:01
@spcheema thanks for testing! I added solution for Android as well. It should be doable with zIndex.

**Comment by jeet-dhandha** [comment] 2023-06-13 18:54
Please try marking the `Works works works` message as unread and share the Screenshot here.

**Comment by jeet-dhandha** [comment] 2023-06-13 20:39
I m just confused why you have same background as a `whisper message` on your `text message`. @petromoldovan

**Comment by spcheema** [comment] 2023-06-13 23:51
@petromoldovan I like your solution no doubt but there is background coming to text which I forgot to mention when highlighted Android issue.

**Comment by petromoldovan** [comment] 2023-06-14 14:17
@jeet-dhandha @spcheema thank you guys for the questions. Please refer to the screenshots in the proposal.

**Comment by jeet-dhandha** [comment] 2023-06-15 08:28
<img width="349" alt="Screenshot 2023-06-15 at 1 57 23 PM" src="https://github.com/Expensify/App/assets/78416198/d735cfb0-3f75-4adf-91f2-4e294bc120d4">

@petromoldovan  Could you please provide a screenshot of the unread concierge message similar to the one shown above?

**Comment by petromoldovan** [comment] 2023-06-15 13:20
@cead22 @slafortune @rushatgabhane guys, what do you think about [proposal](https://github.com/Expensify/App/issues/20451#issuecomment-1584312046)  👀?

**Comment by jeet-dhandha** [comment] 2023-06-15 16:52
@cead22 @slafortune - What do we want to achieve here like do we want a margin before and after concierge's whisper message ? or do we let `New` text overlap `whisper message`. https://github.com/Expensify/App/issues/20451#issuecomment-1583027195

**Comment by slafortune** [comment] 2023-06-21 02:11
Checking with the team - https://expensify.slack.com/archives/C01SKUP7QR0/p1687312488132639

**Comment by petromoldovan** [comment] 2023-06-21 07:28
@rushatgabhane thanks for the review! 

**Based on your root cause, what if we don't modify any row in the bottom?**
Nothing happens. 

**What if we add an extra item to the InvertedFlatList that is sandwiched between two comments?**
I though about your solution as well. 
- First of all, it adds complexity because you will have to differentiate between platforms how the "New" message component is rendered. 
- Secondly, there few ways to render the "sandwiched" component that are not exactly straightforward. For example, either you set position to `absolute` and you will have to adjust the styles anyway, or you insert it a as completely different component and you will have to accept the jumpy behaviour when the component is inserted to the least. It is not so nice from the UX perspective. 

I still think that the `zIndex` solution is the most elegant one. `zIndex` exists exactly for such cases. It is just one style property change.

**Comment by jeet-dhandha** [comment] 2023-06-22 08:27
# Proposed solution (UPDATED) (Prev -  https://github.com/Expensify/App/issues/20451#issuecomment-1583027195)
(Removed code and screenshots from proposal. Also added extra description for better understanding of changes and issues)
### Please re-state the problem that we are trying to solve in this issue.
- Problem was that the Unread Indicator's New Text was cutoff due to no margin on `isWhisper` Report Item.

### What is the root cause of that problem?
- Cause 1 : vertical margin aroind whisper item was not added.
- Cause 2 : `top` and `height` of unreadIndicatorContainer is not set properly.

## What changes do you think we should make in order to solve the problem?
- To Fix Cause 1 : Add `marginVertical` 10 when report action item is a whisper message.
- To Fix Cause 2 : Set `top` and `height` of unreadIndicatorContainer properly.
    - for `top` instead of `-10` change to `-6`.
    - for `height` instead of `20` change to `10`.

## What alternative solutions did you explore? (Optional)
- As discussed above we can achieve this with `z-index`. 

But adding marginVertical and styling changes to unreadIndicatorContainer is more appropriate solution. 
As it will fix the issue of cutoff text, also it won't overlap with whisper or other messages.

**Comment by jeet-dhandha** [comment] 2023-06-22 08:28
@rushatgabhane  Please check above updated proposal as per your request.

**Comment by cead22** [comment] 2023-06-26 19:05
I like the zIndex solution, since the alternative seems more complex, and the possibility of it producing "jumpy" behavior when we render the `new` component make it less appealing.

That said, do we really need to assign a zIndex to every message we're rendering, or can we add a zIndex only to the `new` component? Or maybe we assign the same zIndex to all messages, and a higher one for the `new` component. What do you think?

**Comment by petromoldovan** [comment] 2023-06-26 19:39
@cead22 @rushatgabhane thank you for considering my proposal!

Please note that we do not know which message a user might "Mark as unread"(which results in the "New" message line). It could be the first message in the bottom or the last message in the top. That is why we need to assign `zIndex` to all items if the inverted list in descending order. All items must be ordered.

If you are worried about deteriorating performance because of assigning additional prop to all list items: note that we do not render ALL items at once. Flatlist is configured to render only a portion of items at a time. The rest of the list items are rendered in chunks on demand(if user scrolls to the top). So the performance penalty is negligible.

**Comment by petromoldovan** [comment] 2023-06-26 20:26
@rushatgabhane web version works well and is not affected by my proposed changed. I intend to fix the bug only on native platforms.
<img width="434" alt="Screenshot 2023-06-26 at 22 20 18" src="https://github.com/Expensify/App/assets/15109844/d8d19d2d-fee5-4b0c-8a59-788993c4e71f">
<img width="429" alt="Screenshot 2023-06-26 at 22 20 08" src="https://github.com/Expensify/App/assets/15109844/b7c86715-3ebf-494e-9093-5d77786d8fbc">

**Comment by petromoldovan** [comment] 2023-06-26 22:08
@rushatgabhane if you add or delete list items, indexes(or in our case zIndexes) are updated as expected:
https://github.com/Expensify/App/assets/15109844/0fedcede-e406-4a81-9068-2573d6d88a37

**Comment by petromoldovan** [comment] 2023-06-27 06:21
> Awesome, thanks!! So for any change in the list, we recompute the zIndexes for every single row that is rendered by the flatlist (not the entire chat history)

@rushatgabhane it is important to mention that Flatlist updates its internal indexes EVERY time that you add or delete a row. It happens regardless if we add `zIndex` or not. We just ride alone and assign the new index value to a `zIndex` prop when there is an update. 

I think that we are really on point here with the zIndex approach.

**Comment by cead22** [comment] 2023-06-27 16:55
> Please note that we do not know which message a user might "Mark as unread"(which results in the "New" message line). It could be the first message in the bottom or the last message in the top. That is why we need to assign `zIndex` to all items in the inverted list in descending order. Only this option is bulletproof and will work for any list sizes.

To clarify, what I was thinking was that we'd set the same zIndex or no zIndex to all messages, and then set the zIndex on the New message indicator to be the same as the messages + 1. That way all messages have the same, and the new message indicator has a value that's higher than all the messages. Would that work?

> There won't be any shenanigans of updating all rows of the flatlist for row creation and deletion.

As for considering the sandwich solution, this is not a concern given _Flatlist updates its internal indexes EVERY time that you add or delete a row. It happens regardless if we add zIndex or not_, right?


> * Since all elements are styles with flex and flex doesn't support z-index

I also noticed @spcheema mentioned this, is this a concern?

**Comment by cead22** [comment] 2023-06-27 18:35
Sorry, to clarify, that's not what I meant. An example of what I meant is
- Set zIndex on all messages to 0
- Set zIndex of new message indicator to 1
- To incorporate your example, RHP would have a zIndex higher than 1, eg 2

**Comment by petromoldovan** [comment] 2023-06-27 20:12
@cead22 I get it. You want to assign a higher zIndex only the element that actually needs it. I think that it is a possible solution but not the optimal one. 

When I compare your solution to my [proposal](https://github.com/Expensify/App/issues/20451#issuecomment-1584312046) I think about:

1. Performance.
I could add such line to my `RendererComponent` to determine which row should get a higher zIndex:
```
const zIndex = props.isRowWithNewMessage ? 1 : 0;
```
You will have to make this check for every single rendered row in the list. It is not crazily expensive but still one more operation than I proposed. 

2. Props: you will have to pass somehow(prop or context) an additional prop(e.g. `isRowWithNewMessage`) to the `RendererComponent` component. 

3. Scalability: your solution is very specific to the "New message" feature. What if there will be some other feature that also requires a higher zIndex to be assigned to a list row? You will have to add more checks(point 1) and more props(point 2). It gets messy. My solution is generic.

Your solution seems doable. I think it could work. But is the optimal one?

**Comment by petromoldovan** [comment] 2023-06-27 20:23
> 

@rushatgabhane sorry poor wording from my side. I meant the row(not internal) index(0,1,2,3,4,5) is updated properly every time we add or remove a list item. Corrected.

[Proof here](https://github.com/Expensify/App/issues/20451#issuecomment-1608386130)

**Comment by cead22** [comment] 2023-06-29 03:03
Thanks for trying it. I'm good to try @petromoldovan's solution. @rushatgabhane does that work for you or is there anything else you want to try or look into?

**Comment by petromoldovan** [comment] 2023-06-30 09:39
hi @cead22 @rushatgabhane ! I did some performance testing(Dev Menu -> Perf Monitor) on dev build on IOS simulator. I compared the current main branch with a branch with my solution. I did the same operations in every test:
1. Open chat
2. Create a new message
3. View all other messages
4. Mark a message as unread
5. Delete a message. 

Consider the results:
**Current main**
| RAM(MB)  | UI Frame Rate |
| ------------- | ------------- |
| 218-253	| 49-60  |
| 202-233	| 		54-60  |
| 205-235	|		54-60 |
| 208-251	|		52-60  |
| 203-232	|		53-60  |

**Solution branch**
| RAM(MB)  | UI Frame Rate |
| ------------- | ------------- |
| 218-263	|		54-60  |
| 205-233	|		54-60  |
| 213-241		|	53-60  |
| 191-230		|	53-60  |
| 200-228	|		53-60	  |

**Conclusion**
The stats are comparable. There is no performance penalty observed. 

Two test examples:
https://github.com/Expensify/App/assets/15109844/928f4741-36eb-4f11-a13d-3c64d9411a08
https://github.com/Expensify/App/assets/15109844/dedbcfeb-37fe-4b12-aa9e-385b2d650b4a

**Comment by cead22** [comment] 2023-07-04 00:10
Assigned @petromoldovan

**Comment by petromoldovan** [comment] 2023-07-04 06:21
thanks @cead22 and @rushatgabhane and everyone! I will open a pull request ASAP.

**Comment by petromoldovan** [comment] 2023-07-05 08:04
@cead22 @rushatgabhane @slafortune [PR](https://github.com/Expensify/App/pull/22247) is up!

sorry for spamming here.

**Comment by rushatgabhane** [comment] 2023-07-25 14:47
Started an internal discussion to double the bounty to $2k [here 🧵](https://expensify.slack.com/archives/C02NK2DQWUX/p1690296163434689).

**Comment by petromoldovan** [comment] 2023-07-25 15:22
> Because of the quality of discussion and proposal by @petromoldovan, I've started an internal discussion to double the bounty to $2k [here 🧵](https://expensify.slack.com/archives/C02NK2DQWUX/p1690296163434689).

@rushatgabhane I do not what to say. Even if doubling the bounty does not work out, I really appreciate your gesture. Thank you!

**Comment by slafortune** [comment] 2023-07-28 15:42
Typically doubling has predominately been done simply to increase interest and proposals when they aren’t getting enough attention.  Examples like this are great when considering someone for the C+ role 👍

**Comment by slafortune** [comment] 2023-07-28 18:03
- urgency bonus? No
- External issue reporter @gadhiyamanan $250 - PD
- Contributor that fixed the issue @petromoldovan $1000 - PD
- Contributor+ that helped on the issue and/or PR @rushatgabhane $1000 to be paid via new dot once checklist is complete.

**Comment by cead22** [comment] 2023-07-31 09:53
Not overdue. Working on payments

**Comment by slafortune** [comment] 2023-08-03 19:12
@rushatgabhane - can you let me know once payment has been made please?

**Comment by rushatgabhane** [comment] 2023-08-03 20:55
@slafortune because you posted https://github.com/Expensify/App/issues/20451#issuecomment-1656117816

You can close this issue. Anu or Jason will refer thay comment and payout. Thanks!

**Comment by JmillsExpensify** [comment] 2023-08-04 04:15
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Closed** 2023-08-07 19:30 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
