### ISSUE TITLE
[$500] [MEDIUM] Bank account - Confirm button is not disabled when offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36484] opened 2024-02-14 14:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4312329
**Email or phone of affected tester (no customers):** applausetester+vd_mweb041324@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace
1. Go to Workspace > Bank account
2. Initiate the add BA flow until you reach the Personal info double check page
3. Disable the internet connection

## Expected Result:
The Confirm button should be grayed out and disabled

## Actual Result:
Confirm button is not disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6379021_1707892919841!Screenshot_1](https://github.com/Expensify/App/assets/78819774/6a45392d-146e-4d68-b34f-dd71eb24bf08)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116b0e762d51b88bd</li>
        <li>Upwork Job ID: 1759563597209448448</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2024-02-14 14:31
@MrMuzyk I believe you can address it in your PR

**Comment by Swor71** [comment] 2024-02-14 15:04
Hey I'm Marcin from Callstack - expert contributor group - I'd like to work on this issue

**Comment by mountiny** [comment] 2024-02-19 13:00
@Swor71 will address this issue this week

**Comment by mountiny** [comment] 2024-02-19 15:59
And engineer is already assigned to this issue

**Comment by elemanhillary** [comment] 2024-02-19 16:06
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
Confirm button is not disabled when offline

**What is the root cause of that problem?**
We show the button even when user is offline

**What changes do you think we should make in order to solve the problem?**
Check for network status and reachability to enable / disbale button
- we can refactor and maybe make the useNetwork simple to add in reachability, using something like this

```typescript
import { useState, useEffect } from 'react';
import NetInfo, { NetInfoStateType } from '@react-native-community/netinfo';

interface NetworkManagerState {
  networkType: NetInfoStateType | null;
  isConnected: boolean | null;
  isInternetReachable: boolean | null;
}

const useNetworkManager = (): NetworkManagerState => {
  const [networkState, setNetworkState] = useState<NetworkManagerState>({
    networkType: null,
    isConnected: null,
    isInternetReachable: null,
  });

  useEffect(() => {
    const unsubscribe = NetInfo.addEventListener((state) => {
      setNetworkState({
        networkType: state.type,
        isConnected: state.isConnected,
        isInternetReachable: state.isInternetReachable ?? null,
      });
    });

    return () => {
      unsubscribe();
    };
  }, []);

  return networkState;
};

export default useNetworkManager;

```

**Additional**
We can adjust button constraints at the bottom as it looks cropped

**Comment by Swor71** [comment] 2024-02-21 15:13
hey, sorry for a late response to this issue, I had some technical problems with my setup.

fixed this issue along with the same cases for other substep confirmation pages here:  https://github.com/Expensify/App/pull/37025

**Closed** 2024-03-04 18:21 UTC
Labels: Reviewing, External, Engineering, Weekly
