### ISSUE TITLE
Chat - Video is restarted when opened on attachment window

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37853] opened 2024-03-06 23:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4395697
**Email or phone of affected tester (no customers):** vdargentotest+web030624@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Send a video
3. Play the video
4. Verify the video is being played on the preview
5. Click on the expand button to open it on attachment window
6. Verify the video is restarted
7. Go back to the chat
8. Verify the video is not restarted on the preview

## Expected Result:
The video should continue to play at the same point when expanded

## Actual Result:
The video is restarted when expanded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/91669f74-ee5e-4c2b-bcee-7436188a8566

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-06 23:54
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by ShridharGoel** [comment] 2024-03-07 09:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Video is restarted when opened on attachment window.

### What is the root cause of that problem?
Current position is not being passed while navigating to the attachment.
Below code is from VideoRenderer.tsx.
```
const route = ROUTES.REPORT_ATTACHMENTS.getRoute(report?.reportID ?? '', sourceURL);
Navigation.navigate(route);
```

### What changes do you think we should make in order to solve the problem?
In the route, pass a new parameter called `lastPosition`. The video's `positionMillis` can be set as lastPosition when the expand button is clicked.

**Comment by alexpensify** [comment] 2024-03-08 18:43
I'll test early next week and we can figure out the next steps. Thanks!

**Comment by alexpensify** [comment] 2024-03-11 23:20
No update yet, I need to test.

**Comment by dannymcclain** [comment] 2024-03-13 20:00
_Personally_ I feel like it's worth addressing. I would find this pretty annoying. I'll let others weigh in too to see if everyone thinks it's annoying enough to prioritize though.

**Comment by dubielzyk-expensify** [comment] 2024-03-13 23:38
Agreed. We should respect their timestamp in the video whether it's thumbnail size, modal or fullscreen

**Comment by alexpensify** [comment] 2024-03-13 23:41
Cool, thanks Design. I'll try to figure out the right Wave or VIP for this one.

**Comment by alexpensify** [comment] 2024-03-16 00:49
@francoisl - I think you have been working on the video feature. Is this on your radar? If no, then I'll carry on with my next steps.

**Comment by francoisl** [comment] 2024-03-18 17:54
I think this is already being worked on in https://github.com/Expensify/App/pull/38407 (@Skalakid correct me if I'm wrong)

**Comment by alexpensify** [comment] 2024-03-18 22:56
Thanks, @francoisl, we will wait for @Skalakid for feedback before closing this one.

**Comment by Skalakid** [comment] 2024-03-19 08:10
@francoisl That's correct, this PR fixes it. I will give it to review today

**Comment by alexpensify** [comment] 2024-03-20 23:48
Thanks for confirming this is a dupe, closing in favor of https://github.com/Expensify/App/issues/36873.

**Closed by alexpensify** 2024-03-20 23:48 UTC
Labels: Daily, Bug
