### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250]  IOU – Previous Expense report title is returned, if save the title as empty

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42525] opened 2024-05-23 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4569904
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create new workspace
4. Create two Submit expenses in WS chat
5. Navigate to Expense report
6. Click on title field, delete it and press Save
7. Observe the title field
8. Navigate to WS chat via header link
9. Open Expense report again
10. Observe the title field

## Expected Result:
Unable to save empty Expense report title

## Actual Result:
 Previous Expense report title is returned, if save the title as empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8e4105b4-8a8c-4a1f-8af5-a1aa6386fcf7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ce4e42d36033b48</li>
        <li>Upwork Job ID: 1793667673590427648</li>
        <li>Last Price Increase: 2024-05-23</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 102479025</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by lanitochka17** [comment] 2024-05-23 14:21
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-23 14:21
We think that this bug might be related to #vip-vsp

**Comment by abzokhattab** [comment] 2024-05-23 15:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
expense report title allows saving empty empty title
### What is the root cause of that problem?

The title field is displayed if `reportField.type === 'text' or isReportFieldTitle` is true. It is marked as required if `reportField.deletable`is false, which is incorrect. According to [this comment](https://github.com/Expensify/App/issues/35043#issuecomment-1911275433), the title is editable only if deletable is true, as shown [here](https://github.com/Expensify/App/blob/6bc2e31638a051ee5801e26e19844888a50d73bb/src/libs/ReportUtils.ts#L2413). Therefore, the title field should be required if it is not disabled. We can use `!isReportFieldDisabled(report, reportField, policy)` or simply change `!reportField.deletable` to `reportField.deletable`.

https://github.com/Expensify/App/blob/2c9cc0a4b983e18eab5ea8977a36f4db27afa9f6/src/pages/EditReportFieldPage.tsx#L128-L135


### What changes do you think we should make in order to solve the problem?

change the the required field [here](https://github.com/Expensify/App/blob/2c9cc0a4b983e18eab5ea8977a36f4db27afa9f6/src/pages/EditReportFieldPage.tsx#L128-L135)  to `!isReportFieldDisabled(report, reportField, policy)` or simply change the `!reportField.deletable` to `reportField.deletable`

**Comment by abzokhattab** [comment] 2024-05-24 14:59
Hi @parasharrajat 

I would like to hear your opinion about my proposal. I believe the title field should be required if it is not disabled, 
----> meaning when "delectable" is true, not the other way around.

**Comment by abzokhattab** [comment] 2024-05-25 22:47
- The edit title page will only open if the field is editable. For reference, check the mobile screenshots in [this PR](https://github.com/Expensify/App/pull/34884) to see the current behavior if the field is not editable 
- The field is editable if it is not disabled, as illustrated [here](https://github.com/Expensify/App/blob/ff368b8774b98a2062328010e5e0bfcc3200e97b/src/components/ReportActionItem/MoneyReportView.tsx#L76) and [here](https://github.com/Expensify/App/issues/35043#issuecomment-1911275433).
- If the title field is editable, that means it is not disabled, which means the `ReportUtils.isReportFieldDisabled(report, reportField, policy)` is `true` which means happens when the `deletable` field is `true` for the title field.
- Now Regarding the required prop, currently it is enabled if `deletable` is `false`, which is incorrect. It should be required if it is editable, meaning `isRequired={!ReportUtils.isReportFieldDisabled(report, reportField, policy)}` or `isRequired={reportField.deletable}`.


I believe it would be beneficial to include @allroundexperts in this discussion, as he was the one who implemented this feature.

cc @cristipaval @parasharrajat 

Please let me know if you have any further questions.

**Comment by cristipaval** [comment] 2024-05-27 09:52
Why Overdue, Melv? 🙄

**Comment by bfitzexpensify** [comment] 2024-06-14 15:40
Payment summary: 

$250 for @parasharrajat for C+ work to be paid via NewDot manual request
$250 for @cretadn22 - paid via Upwork ✅ 

@parasharrajat, please complete the BZ checklist - thank you!

**Comment by bfitzexpensify** [comment] 2024-06-14 15:56
Those steps look great, thank you. Proposed they be added in https://github.com/Expensify/Expensify/issues/404906. We're all done here, thanks everyone.

**Closed by bfitzexpensify** 2024-06-14 15:56 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-02 13:28
$250 approved for @parasharrajat
