### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Distance rates - Distance rate order in Rate page is random after clear cache and restart app

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50304] opened 2024-10-06 16:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh0410007@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates
3. Add a few distance rates
4. Go to workspace chat.
5. Click + > Submit expense > Distance.
6. Enter waypoints > Next.
7. Click Rate on confirmation page.
8. Note that order of distance rates is A, B, C, D, E etc
9. Go to Troubleshoot > Clear cache and restart
10. Select Reset and refresh
11. Repeat Step 4 to 7.

## Expected Result:
The order of distance rates in Rate page should remain A, B, C, D, E etc.

## Actual Result:
The order of distance rates in Rate page is random after clear cache and restart app.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3d377d29-d644-4d0a-beed-4f52aa0ef400
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844102961422932795</li>
        <li>Upwork Job ID: 1844102961422932795</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 104371732</li>
<li>ChavdaSachin | Contributor | 104371734</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad / @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-10-06 16:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-10-06 16:42
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment] 2024-10-06 17:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance rate order in Rate page is random after clear cache and restart app

### What is the root cause of that problem?
We are not sorting distanceRates here.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L67

### What changes do you think we should make in order to solve the problem?
Implement sorting after reading rates from ONYX here.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L67

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment] 2024-10-06 17:32
## Updated Proposal
[Updated Proposal](https://github.com/Expensify/App/issues/50304#issuecomment-2395514652) added alternate solution.

**Comment by ChavdaSachin** [comment] 2024-10-06 20:43
@cretadn22 thanks for your insights,
But I believe Proposals are about sharing ideas how a problem could be solved isn't it?
And I believe sorting is not any sort of complex problem where it's must to share pseudo code to make reviewer believe in your solution.
But anyways I will respect whatever thought  reviewer might have.

**Comment by nkdengineer** [comment] 2024-10-07 08:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The order of distance rates in Rate page is random after clear cache and restart app.

### What is the root cause of that problem?

> I notice that other proposals aren't clear why the display rate is different when we reset cache and restart

When we add new distances, these objects are added to Onyx in turn then this displays the current order that we added is `A, B, C, D, E`

https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L73

After we reset the cache and restarted, BE returned another order of `rates` object then it displayed in a different order

https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L73

### What changes do you think we should make in order to solve the problem?
Sort the distance rates by `rate` value as we do [here](https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L104-L106)

```
const sections = Object.values(rates)
        .sort((rateA, rateB) => (rateA.rate ?? 0) - (rateB.rate ?? 0))
        .map((rate) => {
```
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L73-L75

### What alternative solutions did you explore? (Optional)
NA

**Comment by CortneyOfstad** [comment] 2024-10-09 19:50
@paultsimura we have a few proposals above for you to review when you have a chance — thanks!

**Comment by madmax330** [comment] 2024-10-11 12:37
I agree with @paultsimura, I don't _how_ we're sorting the data is the most important part of the proposal.

**Comment by CortneyOfstad** [comment] 2024-10-15 19:56
Hey @trjExpensify! I am heading OoO this afternoon (10/15 to 10/23) so reassigning to keep this moving! The PR [here](https://github.com/Expensify/App/pull/50721) has not been launched to staging just yet 👍 

Thanks!

**Comment by trjExpensify** [comment] 2024-10-17 00:27
Sounds good!

**Comment by CortneyOfstad** [comment] 2024-10-24 14:59
I'm back from OoO — thanks for holding down the fort @trjExpensify!

Agree with your proposal @paultsimura!

**Comment by CortneyOfstad** [comment] 2024-10-25 18:12
## Payment Summary

@paultsimura — paid $250 via Upwork
@ChavdaSachin — paid $250 via Upwork

## Regression Test

https://github.com/Expensify/Expensify/issues/439059

**Closed by CortneyOfstad** 2024-10-25 18:12 UTC
Labels: External, Daily, Monthly, Awaiting Payment, Bug
