### ISSUE TITLE
Expensify Card - Member cannot see card details from link in workspace chat unless Wallet is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50471] opened 2024-10-08 19:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh0610009@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [Admin] Asssign a virtual card to member
3. [Member] Do not go to Wallet page (important)
4. [Member] Go to workspace chat
5. [Member] Click on Expensify Card link
6. [Member] Note that Expensify Card details are not revealed (limit and buttons) when opened from the link
7. [Member] Go to Wallet
8. [Member] Go back to workspace chat and open Expensify Card link
9. [Member] Note that Expensify Card details are only revealed (limit and buttons) after user opens Wallet page

## Expected Result:
In Step 6, member should be able to see their Expensify Card details (limit and buttons) without going to Wallet page

## Actual Result:
In Step 6, member is not able to see their Expensify Card details. It does not show the limit and buttons are hidden
In Step 9, after opening Wallet page, user can see Expensify Card details from the link in workspace chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a35a5825-8e3b-4991-a886-73b7213328ee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-08 19:19
We think that this bug might be related to #wave-collect - Release 2

**Comment by truph01** [comment] 2024-10-08 19:27
@allgandalf I think it is bug 2 I mentioned [here](https://github.com/Expensify/App/issues/50375#issuecomment-2399834159). BE should handle it by sending pusher data.

**Comment by thienlnam** [comment] 2024-10-08 20:01
Not a blocker from slack thread since this is not a common flow in NewDot, though should be fixed soon

**Comment by truph01** [comment] 2024-10-08 20:03
@thienlnam This should be fixed in BE, right?

**Comment by thienlnam** [comment] 2024-10-08 20:07
Yeah, looks like it can be - cc @mountiny for how to proceed on this

**Comment by mountiny** [comment] 2024-10-08 21:55
Gonna take over

**Comment by mountiny** [comment] 2024-10-14 04:02
I think this is already sorted as we started to push the onyx updates about new virtual cards correctly now

**Comment by mountiny** [comment] 2024-10-14 04:02
Asked for a retest https://expensify.slack.com/archives/C9YU7BX5M/p1728878536836339

**Comment by izarutskaya** [comment] 2024-10-14 12:20
Issue is not reproducible anymore.

https://github.com/user-attachments/assets/1d17e65b-e294-41e0-b783-c97718694c5e

**Comment by mountiny** [comment] 2024-10-14 16:22
Perfect so that was fixed with the auth pr

**Closed by mountiny** 2024-10-14 16:22 UTC
Labels: Engineering, Daily, Internal
