### ISSUE TITLE
[HOLD for payment 2024-09-18] [$125] Bank account - Company website field is blank on confirmation page if it is not modified

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48674] opened 2024-09-06 04:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account is a private domain account (Expensifail).

1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows
3. Click Connect bank account > Connect manually
4. Proceed to Step 4 - Enter Company's Tax ID page
5. Enter Tax ID > Next
6. Note that the website field is auto populated with https://www.applause.expensifail.com/
7. Click Next without changing the website field.
8. Proceed to confirmation page for Company info.
9. Click Confirm.

## Expected Result:
In Step 8, Company website field should be filled with the auto-populated website in Step 6.

## Actual Result:
In Step 8, Company website field is not filled with the auto-populated website in Step 6.
In Step 9, after clicking Confirm, it shows the error "Please provide a valid Website" when the field is auto-populated with a valid website.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/35f2b5bb-60bc-4bc8-ba27-27faf4c7fb49

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831968301055311769</li>
        <li>Upwork Job ID: 1831968301055311769</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by madmax330** [comment] 2024-09-06 08:10
Looks like we're not rendering the default value. I think this is a front-end issue

**Comment by mkzie2** [comment] 2024-09-06 08:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 8, Company website field is not filled with the auto-populated website in Step 6.
In Step 9, after clicking Confirm, it shows the error "Please provide a valid Website" when the field is auto-populated with a valid website.

### What is the root cause of that problem?

Input's default value is not saved into draft unless user changes value.

We only save draft in `onInputChange`:

https://github.com/Expensify/App/blob/d9618ca882b27714c563702c99ee9c9f6e36cde8/src/components/Form/FormProvider.tsx#L371-L373

### What changes do you think we should make in order to solve the problem?


We should save draft whenever we uses the default values:

https://github.com/Expensify/App/blob/d9618ca882b27714c563702c99ee9c9f6e36cde8/src/components/Form/FormProvider.tsx#L263-L269

**Comment by bernhardoj** [comment] 2024-09-06 09:03
This happens after we re-enable the auto-populate default website [here](https://github.com/Expensify/App/pull/48520) which was previously temporarily disabled. I think I missed the logic to save it to the draft, I'll recheck it later.

**Comment by mountiny** [comment] 2024-09-09 09:59
@bernhardoj is the PR author with the fix @brunovjk is not online so @hungvu193 will handle the PR review

**Comment by mountiny** [comment] 2024-09-09 12:10
$125 payment to @hungvu193 only

**Comment by brunovjk** [comment] 2024-09-09 12:34
> @bernhardoj is the PR author with the fix @brunovjk is not online so @hungvu193 will handle the PR review

I didn't notice any ping/tag about this before. Thanks for handling it @mountiny.

**Comment by greg-schroeder** [comment] 2024-09-17 01:02
All right - well once this is finished up, @hungvu193 you can make a manual request in ND for the reviewer for $125.

**Comment by hungvu193** [comment] 2024-09-17 01:42
Requested on ND

**Comment by greg-schroeder** [comment] 2024-09-18 00:18
All right then,  closing as the payment summary is there and the request was made - payment approver can take a look [here](https://github.com/Expensify/App/issues/48674#issuecomment-2354289017) tomorrow 9/18 to confirm!

**Closed by greg-schroeder** 2024-09-18 00:18 UTC
Labels: External, Engineering, Monthly, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-19 12:32
$250 approved for @hungvu193
