### ISSUE TITLE
[$100] Group chat - No tooltip when hovering over group member avatar in details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29322] opened 2023-10-11 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any group chat
3. Click on the group chat header
4. Hover over the avatars in group details page

## Expected Result:
Tooltip appears when hovering over group member avatar

## Actual Result:
Tooltip does not appear when hovering over group member avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/78819774/5571c049-1ed2-4d6d-9d77-454e86606d37

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01939a661b5c2c58a4</li>
        <li>Upwork Job ID: 1712149389829230592</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-10-11 15:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip is not working in group details page avatars
### What is the root cause of that problem?
In `RoomHeaderAvatar` component, avatars are not wrapped in tooltip
https://github.com/Expensify/App/blob/907e65e074d1fec41b2038eacdd78455d2fdb161/src/components/RoomHeaderAvatars.js#L90-L98
### What changes do you think we should make in order to solve the problem?
We should wrap avatar components in `UserDetailsTooltip`, like this:
```javascript
 <UserDetailsTooltip
                                        key={`stackedAvatars-${index}`}
                                        accountID={icon.id}
                                        icon={icon}
                                        fallbackUserDetails={{
                                            displayName: icon.name,
                                            avatar: icon.avatar,
                                        }}
                                    >
                                        <View>
                                    <Avatar
                                        source={icon.source}
                                        fill={themeColors.iconSuccessFill}
                                        size={CONST.AVATAR_SIZE.LARGE}
                                        containerStyles={[...iconStyle, StyleUtils.getAvatarBorderRadius(CONST.AVATAR_SIZE.LARGE_BORDERED, icon.type)]}
                                        name={icon.name}
                                        type={icon.type}
                                        fallbackIcon={icon.fallbackIcon}
                                    /></View>
                                        </UserDetailsTooltip>
``` 

### What alternative solutions did you explore? (Optional)

**Comment by joelbettner** [comment] 2023-10-11 16:33
This is not a deploy blocker. On production, when clicking the header we get shown the following:
<img width="1496" alt="image" src="https://github.com/Expensify/App/assets/13264774/4003e885-fc29-4aa3-9649-c1a8a004b0e2">

On staging, those details are now under the "Members" selection:
<img width="1498" alt="image" src="https://github.com/Expensify/App/assets/13264774/c62fd47e-e175-4bfa-98df-6123d56a28fd">

Under the "Members" selection everything works correctly with the tooltip:
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/13264774/20b6dbc5-7744-43fe-a60a-07e335864c1b">

**Comment by joelbettner** [comment] 2023-10-11 16:35
This begs the question...do we want to show the tool tip on the "RoomHeaderAvatars" as per @alitoshmatov 's proposal?

**Comment by techievivek** [comment] 2023-10-11 16:37
We added this change as part of this wave 8 issue: https://github.com/Expensify/App/issues/27394 so I will tag @MitchExpensify @trjExpensify @shawnborton to confirm if we want to show the tooltip or not, but I agree that it shouldn't be a deploy blocker.

**Comment by joelbettner** [comment] 2023-10-11 16:41
Cool cool. Given that it is also not a bug, I'm going to un-assign myself while that discussion happens.

**Comment by mountiny** [comment] 2023-10-11 16:46
I think we want to show the tooltip as we do everywhere for consistency but I agree this is not a blocker, we could export this for $250

**Comment by trjExpensify** [comment] 2023-10-11 17:02
>I think we want to show the tooltip as we do everywhere for consistency but I agree this is not a blocker, we could export this for $250

Huh? What's the issue here? We don't show a tooltip when you hover over a user avatar in the profile page, why do we need to do it here in the group details page? A tooltip on hover over the name is enough IMO.

**Comment by techievivek** [comment] 2023-10-13 06:00
I am going to close this because this is expected behaviour. Please re-open the issue or bring a discussion in Slack if you disagree.

**Closed by techievivek** 2023-10-13 06:00 UTC
Labels: External, Engineering, Daily, Help Wanted

**Comment by mountiny** [comment] 2023-10-15 13:47
Alright, we used to show the tooltip almost everywhere so if these are the exception, thats fine
