### ISSUE TITLE
[$500] SplitBill date is incorrect when a date other than today is selected

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36285] opened 2024-02-09 20:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707500020195589

## Action Performed:
1. Create a split bill
2. On the confirmation screen, set the date to a date in the future
3. After creating the bill, click on the preview to view the details
## Expected Result: 
The date should show as date that is not today
## Actual Result: 
The date shows today's date because it's showing the "created" date and not the date the user specified.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/06fe85ce-3a30-490d-a5a9-fd81e9c22296

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d790dc8609cd540a</li>
        <li>Upwork Job ID: 1757674654685200384</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by vishalsanghai** [comment] 2024-02-10 12:26
Should we allow entries with future date?
If not we can disable selecting any future date on UI.

**Comment by vishalsanghai** [comment] 2024-02-10 12:52
Contributor details
Your Expensify account email: vcoolsanghai@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0121fccdaccc2abdc1

**Comment by brunovjk** [comment] 2024-02-10 21:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The SplitBill date displays incorrectly when a date other than today is selected.

### What is the root cause of that problem?
1 - While [making an API call](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/actions/IOU.ts#L1874), the `created` field is not passed as a [param](https://github.com/Expensify/App/blob/main/src/libs/API/parameters/SplitBillParams.ts). Consequently, the backend consistently returns today's date.
2 - The addition of the `created` parameter to `SplitBillParams` improves the optimistic transaction data. However, the SplitBill response still reflects today's date.

### What changes do you think we should make in order to solve the problem?
To address this issue, two essential changes are required:
1 - Include the `created` parameter in `SplitBillParams` and other relevant split params types.
2 - Coordinate with the backend team to implement the necessary updates.

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-02-10 21:19
Noticed this issue while working on another [PR](https://github.com/Expensify/App/pull/35853#issuecomment-1928046880). Interested in addressing it, despite the absence of the "Help Wanted" tag. However, I believe we still need an internal team member to check and implement the required backend adjustments.

**Comment by DylanDylann** [comment] 2024-02-11 07:04
Could I take this issue as C+ contributor because I have context and discuss [here](https://github.com/Expensify/App/pull/35853#issuecomment-1931275735)

**Comment by tgolen** [comment] 2024-02-12 15:36
> Should we allow entries with future date?

I noticed this question and wanted to respond. This should be allowed, yes. Please use these constants for the date.

**Comment by tgolen** [comment] 2024-02-12 15:37
Assigned to you @DylanDylann to work on this.

**Comment by stephanieelliott** [comment] 2024-02-14 07:55
Seems like the labels didn't apply correctly here. Thanks for noticing @brunovjk -- giving you a heads up if you want to make a proposal 😊

**Comment by jonsystems** [comment] 2024-02-14 09:02
It seems like "created" is passed to the RequestMoney command with a value similar to "2024-02-17", but the same doesn't happen on SplitBill. I don't have my environment setup so just posting to anybody who's looking. Seems like you might have to make API changes aswell to implement the "created" parameter and do something with it on the server.

**Comment by brunovjk** [comment] 2024-02-14 10:13
Very good, thank you @stephanieelliott, I already have a [proposal](https://github.com/Expensify/App/issues/36285#issuecomment-1937165240). However, today I will re-investigate and re-make the proposal if necessary.

**Comment by brunovjk** [comment] 2024-02-14 18:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SplitBill date displays incorrectly when a date other than today is selected.

### What is the root cause of that problem?
Missing `created` parameters at [`SplitBillParams`](https://github.com/Expensify/App/blob/main/src/libs/API/parameters/SplitBillParams.ts).

### What changes do you think we should make in order to solve the problem?
- Add `created` parameters at `SplitBillParams`.
- Update `IOURequestStepConfirmation` to pass `transaction.created` to `IOU.splitBill` and `IOU.splitBillAndOpenReport` call.
- Update [`splitBill`](https://github.com/Expensify/App/blob/47cc484a26e6f6c5e6512ebfe3bab172ba788dd1/src/libs/actions/IOU.ts#L1846), [`splitBillAndOpenReport`](https://github.com/Expensify/App/blob/47cc484a26e6f6c5e6512ebfe3bab172ba788dd1/src/libs/actions/IOU.ts#L1899) and [`createSplitsAndOnyxData`](https://github.com/Expensify/App/blob/47cc484a26e6f6c5e6512ebfe3bab172ba788dd1/src/libs/actions/IOU.ts#L1485) to **receive and use** `created` value to `buildOptimisticTransaction`.

> [!NOTE]
> Although the `transaction created` is correct with these changes, we also need to make changes to the BE so that it can use the `created` param passed, as we do in `CompleteSplitBill`, and returns the correct date.
> 
> POC: Create a `splitBillAndOpenReport` **offline** and **than go online**:
> <details>
> <summary>Proposed changes</summary>
> 
> 
> https://github.com/Expensify/App/assets/95647348/24665cde-8444-479f-8421-0b85d6528a3e
> </details>
>
> <details>
> <summary>Latest main</summary>
> 
> 
> https://github.com/Expensify/App/assets/95647348/42186470-e7d6-489a-9537-a96cc31b0c8a
> </details>

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-02-14 19:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SplitBill date displays incorrectly when a date other than today is selected.

### What is the root cause of that problem?
Missing `created` parameters at [`SplitBillParams`](https://github.com/Expensify/App/blob/main/src/libs/API/parameters/SplitBillParams.ts).

### What changes do you think we should make in order to solve the problem?
- Add `created` parameters at `SplitBillParams`.
- Update `IOURequestStepConfirmation` to pass the [`created transaction value`](https://github.com/Expensify/App/blob/821bc7b0f66e492bd091e4832b5af10429f34182/src/libs/TransactionUtils.ts#L377) to [`IOU.splitBill`](https://github.com/Expensify/App/blob/821bc7b0f66e492bd091e4832b5af10429f34182/src/pages/iou/request/step/IOURequestStepConfirmation.js#L280-L292) and [`IOU.splitBillAndOpenReport`](https://github.com/Expensify/App/blob/821bc7b0f66e492bd091e4832b5af10429f34182/src/pages/iou/request/step/IOURequestStepConfirmation.js#L298-L309) call.
- Update [`splitBill`](https://github.com/Expensify/App/blob/47cc484a26e6f6c5e6512ebfe3bab172ba788dd1/src/libs/actions/IOU.ts#L1846), [`splitBillAndOpenReport`](https://github.com/Expensify/App/blob/47cc484a26e6f6c5e6512ebfe3bab172ba788dd1/src/libs/actions/IOU.ts#L1899) and [`createSplitsAndOnyxData`](https://github.com/Expensify/App/blob/47cc484a26e6f6c5e6512ebfe3bab172ba788dd1/src/libs/actions/IOU.ts#L1485) to **receive and use** `created` value to `buildOptimisticTransaction`.

> [!NOTE]
> With these changes, `transaction.created` is correct, but we must also update BE to use the `created` parameter when we call `SPLIT_BILL` and `SPLIT_BILL_AND_OPEN_REPORT`, as we do in `COMPLETE_SPLIT_BILL`, which returns the correct date.
> 
> POC: Create a `splitBillAndOpenReport` **offline** and **than go online**:
> <details>
> <summary>Proposed changes</summary>
> 
> 
> https://github.com/Expensify/App/assets/95647348/24665cde-8444-479f-8421-0b85d6528a3e
> </details>
>
> <details>
> <summary>Latest main</summary>
> 
> 
> https://github.com/Expensify/App/assets/95647348/42186470-e7d6-489a-9537-a96cc31b0c8a
> </details>

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-02-15 09:15
@brunovjk Your proposal looks good to me

Note that: We need to update Split Bill APIs from BE side to fix this issue completely

🎀 👀 🎀 C+ reviewed

**Comment by brunovjk** [comment] 2024-02-15 09:28
Thank you @DylanDylann  :D

**Comment by brunovjk** [comment] 2024-02-15 09:34
> Don't need to update `StartSplitBill` API

Exactly!
Thank you @DylanDylann for the review :D

**Comment by brunovjk** [comment] 2024-02-15 09:37
> Don't need to update `StartSplitBill` API

Exactly!
Thanks for the review @DylanDylann  :D

**Comment by francoisl** [comment] 2024-02-16 01:34
Hi @brunovjk, looks like the backend was just modified to support the `created` param for the commands `SplitBill` and `SplitBillAndOpenReport` a few days ago. Can you try your changes again and see if the backend returns the right date in the response now?

**Comment by francoisl** [comment] 2024-02-16 01:37
Ah shoot, actually this might be the same issue as https://github.com/Expensify/App/issues/34526, which just had this fix merged: https://github.com/Expensify/App/pull/35141. Right?

**Comment by DylanDylann** [comment] 2024-02-16 03:45
@francoisl Thanks for pointing out that. Let's close this one

**Comment by DylanDylann** [comment] 2024-02-16 03:59
Thank you for pointing out that. Can't reproduce anymore

**Comment by stephanieelliott** [comment] 2024-02-16 06:45
I can't repro it anymore either -- gonna close this as resolved.

**Closed by stephanieelliott** 2024-02-16 06:45 UTC
Labels: External, Daily, Help Wanted, Bug
