### ISSUE TITLE
Copilot - Not here page opens on central pane when switching account on Subscription tab

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48246] opened 2024-08-29 09:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has a subscription (activate by creating a workspace).

1. Go to staging.new.expensify.com
2. Log in as a copilot.
3. Go to Account settings.
4. Go to Subscription.
5. Click Account switcher.
6. Select another account.

## Expected Result:
Not here page will not open on central pane.

## Actual Result:
Not here page opens on central pane when switching account on Subscription page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8e3ab8e-db6f-47f1-a7e7-3bae40626f4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by bernhardoj** [comment] 2024-08-29 10:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Subscription page shows not found when switching account.

### What is the root cause of that problem?
When we switch account, we clear the onyx and calls open app.
https://github.com/Expensify/App/blob/b9af3d1f7ab160f7d817102d081b0e6186ba2d02/src/libs/actions/Delegate.ts#L74-L82

Because the data is cleared, the subscription data is gone and thus not found page is shown.
https://github.com/Expensify/App/blob/b9af3d1f7ab160f7d817102d081b0e6186ba2d02/src/pages/settings/Subscription/SubscriptionSettingsPage.tsx#L30-L32

### What changes do you think we should make in order to solve the problem?

We can show a loading indicator while the app is still loading.
```
if (!subscriptionPlan) {
    if (isLoadingApp) {
        return <FullScreenLoadingIndicator />
    }
    return <NotFoundPage />;
}
```

But this isn't enough because clearing the onyx happened first before the open app request, so not found will still show briefly.

We can optimistically set the IS_LOADING_APP when switching the account (connect & disconnect) knowing that we will call open app (set it to false when fails),
https://github.com/Expensify/App/blob/b9af3d1f7ab160f7d817102d081b0e6186ba2d02/src/libs/actions/Delegate.ts#L23-L38

and also we need to preserve the key so it won't be cleared.
https://github.com/Expensify/App/blob/b9af3d1f7ab160f7d817102d081b0e6186ba2d02/src/libs/actions/Delegate.ts#L21

Or, we can introduce a new onyx key called IS_SWITCHING_ACCOUNT.
Or, we can just add it as a new property to ACCOUNT
```
account.isSwitching
```

**Comment by IuliiaHerets** [comment] 2024-08-29 10:41
Sorry, forgot to add `DeployBlockerCash` label

**Comment by cristipaval** [comment] 2024-08-29 11:21
This isn't a blocker, given that the Not found page shows briefly for a second only. Demoting

**Comment by cristipaval** [comment] 2024-08-29 11:24
@dangrous, I think you have knowledge of Copilot in NewDot? Would you mind taking over this one?

**Comment by dangrous** [comment] 2024-08-29 15:16
yeah sure!

**Comment by dangrous** [comment] 2024-08-29 17:13
I think the IS_LOADING_APP idea makes sense here, but we'll also want to consider this same situation in other places in the app. Is there a holistic solution we can use here? Also @rushatgabhane we'll probably want to take this on ourselves?

**Comment by cristipaval** [comment] 2024-08-29 19:36
Thanks a lot @dangrous! 🙇

**Comment by mallenexpensify** [comment] 2024-08-30 22:44
@rushatgabhane can you provide feedback here so we can decide on the next steps?

**Comment by rushatgabhane** [comment] 2024-08-30 22:47
hmmm 

if the last visited page is subscription, and you login you'll get the same bug.

I'll see how we should fix this in the mega fix

**Comment by mallenexpensify** [comment] 2024-08-30 23:38
Assigned to you @rushatgabhane , while we figure out what the next best steps are here. 
What project is Copilot part of, didn't see anything on [Expensify Road Map Projects - Public ](https://docs.google.com/document/d/1pghDdrUVhINJH4jFWNbT2w-ecFqYwTvoGxx4EoYA1U8/edit?usp=sharing
)

**Comment by rushatgabhane** [comment] 2024-08-31 00:08
Wave control??

**Comment by mallenexpensify** [comment] 2024-09-03 00:35
Checking on here, looks like it's part of control 

https://expensify.slack.com/archives/C06ML6X0W9L/p1725317232367829

**Comment by mallenexpensify** [comment] 2024-09-07 00:58
Made you issue owner @rushatgabhane , I think next action is either on you or will be.  Comment if you disagree

**Comment by dangrous** [comment] 2024-09-24 16:39
This went to prod 9/19 - I believe we can close 9/26 - and no payment required I believe

**Comment by dangrous** [comment] 2024-09-30 14:41
Closing this, @allgandalf I believe your review for the [PR](https://github.com/Expensify/App/pull/48517) is being handled on another issue, but if that's NOT the case, please ping here and I can reopen/assign.

**Closed by dangrous** 2024-09-30 14:41 UTC
Labels: Reviewing, Engineering, Weekly, Bug
