### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Dev: Web -  Save button is positioned incorrectly for Private Notes Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27594] opened 2023-09-16 18:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any workspace chat (#admins, #announce etc)
3. Click on header > Private Notes > My Notes > Notes

## Expected Result:
Save button is positioned just below the input

## Actual Result:
Inconsistent with how we have positioned "Save" Button in Welcome Message, Room Name and other pages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.50.7
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (43)](https://github.com/Expensify/App/assets/93399543/7415aa07-671f-4324-860f-07ab5a5c172d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694786159995799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125eda6d35113e0f4</li>
        <li>Upwork Job ID: 1703120056641490944</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26810705</li>
<li>aman-atg | Reporter | 26810706</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-16 18:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Save button is not properly positioned.

### What is the root cause of that problem?
The layout styles are not set properly.

### What changes do you think we should make in order to solve the problem?
Use a FixedFooter to wrap the Save button.

### What alternative solutions did you explore? (Optional)

**Comment by kbecciv** [comment] 2023-09-16 18:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Save button is positioned incorrectly for Private Notes Page

### What is the root cause of that problem?
We didn't use `styles.flexGrow1` for the `Form` component

### What changes do you think we should make in order to solve the problem?}

To fix this, we can just pass `styles.flexGrow1` as styles [here](https://github.com/Expensify/App/blob/1862aff7d5a4c677b3c7ea0424be1f6361dcc91a/src/pages/PrivateNotes/PrivateNotesEditPage.js#L105)https://github.com/Expensify/App/blob/1862aff7d5a4c677b3c7ea0424be1f6361dcc91a/src/pages/PrivateNotes/PrivateNotesEditPage.js#L105

**Comment by PiyushChandra17** [comment] 2023-09-17 07:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Save button is placed just below input text, it should be at the bottom just to maintain consistency

### What is the root cause of that problem?
In `PrivateNotesEditPage`, we are not using any style for `Form` component.

https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/PrivateNotes/PrivateNotesEditPage.js#L105-L110

Hence this is the root cause.

### What changes do you think we should make in order to solve the problem?
We need to add `styles.flexGrow1` in Form styles. Also we need to keep our code "DRY" so instead of wrapping `Form` in `View`, we need to remove `View` and use the styles in `Form` instead, plus add the `Text` inside the form.

```
                <Form
                    style={[styles.flexGrow1, styles.ph5]}
                    formID={ONYXKEYS.FORMS.PRIVATE_NOTES_FORM}
                    onSubmit={savePrivateNote}
                    submitButtonText={translate('common.save')}
                    enabledWhenOffline
                >
                    <View style={[styles.mb5]}>
                        <Text>
                            {translate(
                                Str.extractEmailDomain(lodashGet(personalDetailsList, [route.params.accountID, 'login'], '')) === CONST.EMAIL.GUIDES_DOMAIN
                                    ? 'privateNotes.sharedNoteMessage'
                                    : 'privateNotes.personalNoteMessage',
                            )}
                        </Text>
                    </View>
                    <OfflineWithFeedback
```

### What alternative solutions did you explore? (Optional)
NA

## Result:
<img width="364" alt="Screenshot 2023-09-17 at 1 22 31 PM" src="https://github.com/Expensify/App/assets/47579287/03741b0c-ab0f-4aec-a1f6-5a0fc4e53164">

**Comment by burczu** [comment] 2023-09-18 12:06
I've checked all the proposals and in my opinion [the one](https://github.com/Expensify/App/issues/27594#issuecomment-1722372197) from @hungvu193 solves the issue in the most comprehensive way - I agree that both `View` components that wraps the `Form` and the `Text` components are unnecessary and it's ok to remove them and style the form and the text directly + moving the `Text` component inside the form is correct.

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment] 2023-09-19 21:38
hey @NikkiWines could you check out this and see what you think? https://github.com/Expensify/App/issues/27594#issuecomment-1723275238

**Comment by NikkiWines** [comment] 2023-09-22 05:48
Sorry for the delay. Agreed with @burczu, @hungvu193's proposal looks good

**Comment by NikkiWines** [comment] 2023-09-29 01:50
Yep, the PR getting merged was also delayed on my end so it could've been merged as early as Sept 25th - if this doesn't cause regressions we should provide the urgency bonus.

**Comment by Christinadobrzyn** [comment] 2023-10-10 19:44
Payouts due:

Issue Reporter: $50 @aman-atg (paid in Upwork)
Contributor: $500 + $250 @hungvu193 (paid in Upwork)
Contributor+: @burczu NA payment through contract

Eligible for 50% #urgency bonus? Y - based on https://github.com/Expensify/App/issues/27594#issuecomment-1740208213

Upwork job is [here](https://www.upwork.com/jobs/~0125eda6d35113e0f4).

This is all paid out so closing! Let me know if you need anything.

**Closed by Christinadobrzyn** 2023-10-10 19:44 UTC
Labels: External, Daily, Awaiting Payment
