### ISSUE TITLE
Web - Room - Paid policy isn't shown as an option under “Workspace”.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28046] opened 2023-09-22 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found wen executing PR** https://github.com/Expensify/App/pull/26982

## Action Performed:
1. Sign into OldDot, create or navigate to an existing paid policy. Save the policyID.
2. Run the following snippet to enabled chat rooms for the policy.
const policyID = '<policyID>';
API.policy_get({policyIDList: policyID}).then((response) => {
const policy = response.policies[policyID];
policy.areChatRoomsEnabled = true;
API.policy_save({policyID, value: policy});
3. Sign into NewDot (you'll need to sign out first because of the new reliable updates changes). FAB > New Room.

## Expected Result:
Verify the paid policy shows up as an option under "Workspace"

## Actual Result:
Paid policy isn't shown as an option under “Workspace”

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8e859eaf-542f-4f0c-8730-42ed3815bb17

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2023-09-25 13:40
Reproduced. @jasperhuangg, any insight on this one? It was discovered via https://github.com/Expensify/App/pull/26982

**Comment by bfitzexpensify** [comment] 2023-09-28 16:23
Bump on https://github.com/Expensify/App/issues/28046#issuecomment-1733735739 @jasperhuangg

**Comment by bfitzexpensify** [comment] 2023-10-02 21:46
@jasperhuangg thoughts on https://github.com/Expensify/App/issues/28046#issuecomment-1733735739?

**Comment by bfitzexpensify** [comment] 2023-10-03 16:26
Another bump here @jasperhuangg

**Comment by bfitzexpensify** [comment] 2023-10-06 18:49
@jasperhuangg not sure if you're seeing my bumps, so assigning it to you so it appears in your K2. Looking for your thoughts on https://github.com/Expensify/App/issues/28046#issuecomment-1733735739

**Comment by jasperhuangg** [comment] 2023-10-09 18:46
Ah, thanks for assigning me @bfitzexpensify. I wasn't receiving mention notifications for some reason. Taking a look.

**Comment by jasperhuangg** [comment] 2023-10-09 19:05
The QAer didn't follow the steps correctly. The policyID they entered has carets around it `<>`. Those are placeholders and shouldn't actually appear in the policyID.

In addition, I'm noticing some other problems, fixing those in a PR

**Comment by bfitzexpensify** [comment] 2023-10-09 23:01
Sweet, thanks man

**Comment by bfitzexpensify** [comment] 2023-10-27 16:53
Looks like https://github.com/Expensify/Web-Expensify/pull/39143 was deployed to prod a couple of weeks ago - I can't reproduce any more, so I think we're good to close this.

**Closed by bfitzexpensify** 2023-10-27 16:53 UTC
Labels: Reviewing, Daily, Bug
