### ISSUE TITLE
The user can briefly create a task without assigning someone.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21465] opened 2023-06-23 22:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into an account that has tasks enabled (tasks are in beta, so this'll probably in DEV).
2. Open a chat from the LHN (create one if it doesn't exist).
3. Click on the '+' sign in the composer and choose 'Assign task'.
4. Enter a title and optional description and then click 'Next' (ignore the premature error if it's still showing by the time this issue is on GH - I've already raised it in Slack).
5. Click on the green button at the bottom that says 'Confirm task' without changing anything.
## Expected Result: 
A task is not created and a warning is shown explaining why.
## Actual Result: 
A task is created briefly with a value of 0 shown inside the 'To' field. The task then disappears and is replaced by an infinite loading skeleton.
If you refresh the page after the infinite loading skeleton, you'll get a page that says, "Hmm... it's not here. You don't have access to this chat."

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/afa65353-89fb-48f7-b45f-d72c757b4a72

https://github.com/Expensify/App/assets/43996225/9df628f6-26e9-4fbe-b53a-41d69a8db1b8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687085875676199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2023-06-23 22:54
Closing since this is a dupe of this https://github.com/Expensify/App/issues/21361

**Closed by thienlnam** 2023-06-23 22:54 UTC
Labels: Daily, Bug
