### ISSUE TITLE
[HOLD #37519][$250] LHN - Group chat created via Split Bill is missing in LHN while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39708] opened 2024-04-05 12:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4477130&group_by=cases:section_id&group_order=asc&group_id=229063
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open app
2. Disable internet connection
3. Tap on FAB > Request Money
4. Select Manual tab
5. Write any amount and tap on continue button
6. Select two attendees or more
7. Complete the split bill
8. Navigate to LHN
9. If split does show, navigate to another chat to see if the split disappears. 

## Expected Result:
Created group chat should be displayed in LHN while user offline

## Actual Result:
Created group chat via Split Bill is missing in LHN when user offline. When user returned online, the group chat will appear in LHN.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bc6126b6-57ab-4b82-ac31-b174c6c2752d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c274d12ce7633c6</li>
        <li>Upwork Job ID: 1776410861693710336</li>
        <li>Last Price Increase: 2024-04-06</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2024-04-06 00:46
Added to the OP cuz my repro was a lil different
> 9. If split does show, navigate to another chat to see if the split disappears. 

@mananjadhav , let me know if you **don't** think this can be external.

**Comment by nkdengineer** [comment] 2024-04-06 08:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Created group chat via Split Bill is missing in LHN when user offline. When user returned online, the group chat will appear in LHN.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/libs/actions/IOU.ts#L2295), we're incorrectly setting the `notificationPreference` of the optimistically created group chat to `HIDDEN`, which makes it hide from the LHN. This is also inconsistent with the back-end which will return `notificationPreference` as `always` for the group chat when coming online.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/libs/actions/IOU.ts#L2295), do not set the `notificationPreference` of the optimistically created group chat to `HIDDEN`, so it will fallback to `always`

### What alternative solutions did you explore? (Optional)
NA

**Comment by mananjadhav** [comment] 2024-04-06 16:57
Thanks for updating the OP. I think this can be external because it's all offline but I'll check this on Monday.

**Comment by mallenexpensify** [comment] 2024-04-10 01:25
@mananjadhav , please review the proposal above.

**Comment by mananjadhav** [comment] 2024-04-10 17:45
@nkdengineer Your proposal didn't work for me. I am not sure how notification preference have an impact on the LHN.

**Comment by mananjadhav** [comment] 2024-04-12 15:49
@mallenexpensify I think we should we should this one for https://github.com/Expensify/App/issues/37519.

**Comment by mallenexpensify** [comment] 2024-04-12 22:18
Thanks @mananjadhav , done.  Removed `Help Wanted` and bumped to weekly.

**Comment by mallenexpensify** [comment] 2024-04-23 23:04
[PR for what we're held on](https://github.com/Expensify/App/pull/40271) is moving along

**Comment by mananjadhav** [comment] 2024-05-07 19:05
I think we're good to close this one. The linked PR fixes this and has been deployed to production.

**Comment by mananjadhav** [comment] 2024-05-08 17:08
Quick bump @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-05-09 18:11
Thanks @mananjadhav , I'm able to confirm the group chat shows in LHN on Web-Chrome-Staging
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/22508304/117a0f95-e948-4193-99b6-01fe549b63e2">

**Closed by mallenexpensify** 2024-05-09 18:11 UTC
Labels: External, Weekly, Bug
