### ISSUE TITLE
Dev - Copying text that has style adds lines above & below the copied text when pasting the text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24138] opened 2023-08-03 23:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Write in composer '>' followed by message
3. Send the message
4. Hover over the sent message & click on 'Copy to clipboard' icon
5. Paste the content to the composer
## Expected Result: 
Line shouldn't be added above and below the copied text
## Actual Result: 
Line is added above and below the copied text

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a65444d4-d720-4f02-8d86-aefd5812e85c

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Natnael-guchima
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690881943610289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2023-08-04 04:28
@youssef-lr - here's hoping you can reproduce this on DEV 🙏

**Comment by youssef-lr** [comment] 2023-08-07 23:14
Unable to reproduce this in dev. @kavimuru could you try again please?

**Comment by sophiepintoraetz** [comment] 2023-08-08 05:43
Sorry @youssef-lr - when you get the chance, can you add a video for reproduction? It means I can go back to the reporter to double-check.

**Comment by Natnael-Guchima** [comment] 2023-08-08 18:13
I am seeing this on Dev now. This might be a device specific issue. And I can't reproduce this issue on staging. If it is a bug, I think it should be reproducible on staging too by now. I think we can close this one @sophiepintoraetz

**Closed** 2023-08-10 20:50 UTC
Labels: Engineering, Daily, Needs Reproduction, Overdue, Bug

**Comment by youssef-lr** [comment] 2023-08-10 21:02
Sorry I missed your comment @sophiepintoraetz, I still can't reproduce this.

https://github.com/Expensify/App/assets/9680864/8a3b0e65-44fe-4d11-9388-fc61cf38b2e4

**Comment by kavimuru** [comment] 2023-08-11 21:29
@youssef-lr I can't test in dev
