### ISSUE TITLE
[HOLD for payment 2023-01-19] [$1000] Chat - New Group - The search box overlays the selected user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14001] opened 2023-01-05 01:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Click on the green + button
3. Click on the "New group" option
4. Start typing a search term
5. Select user
6. Then remove from search box

## Expected Result:
When selecting users, they are displayed on the top of the list with a green check mark on the right.

## Actual Result:
The user who has already been selected in the group is hiding behind the search box.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.48.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210679948-9e9d55dd-a67e-4055-a24d-3520d73bba41.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012de37194a5fa31d2</li>
        <li>Upwork Job ID: 1611089102897319936</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-01-05 19:55
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [x] The "bug" is actually a bug - confirmed here: https://expensify.slack.com/archives/C01SKUP7QR0/p1672939604697969
- [x] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [x] The bug is reproducible, following the reproduction steps.
  - [x] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [x] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  -  [x] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [x] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [x] The GH was created by an Expensify employee or a QA tester 
- [x] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [x] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [x] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by syedsaroshfarrukhdot** [comment] 2023-01-05 20:04
I believe this issue is related to auto scrolling of the option list as per the (comment)[https://github.com/Expensify/App/issues/12998#issuecomment-1351328344] here we are looking to redesign the UI/UX of options list it should be resolved with we can put it on hold till then i guess.

**Comment by allroundexperts** [comment] 2023-01-05 20:50
### Proposal
The issue is being caused by scrolling to the first `non selected` option whenever the search term changes.

## Fix
Following needs to be changed: 
```diff
diff --git a/src/components/OptionsSelector/BaseOptionsSelector.js b/src/components/OptionsSelector/BaseOptionsSelector.js
index 8e2668be2..671968e16 100755
--- a/src/components/OptionsSelector/BaseOptionsSelector.js
+++ b/src/components/OptionsSelector/BaseOptionsSelector.js
@@ -110,14 +110,7 @@ class BaseOptionsSelector extends Component {
             // If we just toggled an option on a multi-selection page, scroll to top
             if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
                 this.scrollToIndex(0);
-                return;
             }
-
-            // Otherwise, scroll to the focused index (as long as it's in range)
-            if (this.state.allOptions.length <= this.state.focusedIndex) {
-                return;
-            }
-            this.scrollToIndex(this.state.focusedIndex);
         });
     }
 
```

## Result
https://user-images.githubusercontent.com/30054992/210877370-7b8d19ee-b5c2-498d-8e7a-9aed874f5144.mov

**Comment by mollfpr** [comment] 2023-01-06 03:01
Thank you guys for the proposal!

@NicMendonca as per comment [here](https://github.com/Expensify/App/issues/14001#issuecomment-1372676164), do we want to hold this for the redesign?

cc @mountiny

**Comment by tienifr** [comment] 2023-01-06 04:16
# Proposal

## Problem
We are scrolling to the focused index and the focused index is assigned with `this.props.selectedOptions.length`
## Solution 1
We shouldn't scroll to the focused index and whenever `this.props.selectedOptions.length` is changed or `this.props.sections[1].data` (recent section) changed or `this.props.sections[2].data` (contact section) changed, we will scroll to top. Because when sections are changed (when text search is changed), the user should see new first options
In /Expensify/App/src/components/OptionsSelector/BaseOptionsSelector.js
```diff
componentDidUpdate(prevProps) {
        if (_.isEqual(this.props.sections, prevProps.sections)) {
            return;
        }

        const newOptions = this.flattenSections();
        const newFocusedIndex = this.props.selectedOptions.length;
        this.setState({
            allOptions: newOptions,
            focusedIndex: newFocusedIndex,
        }, () => {
            // If we just toggled an option on a multi-selection page, scroll to top
-            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
-                this.scrollToIndex(0);
-                return;
-            }

-            Otherwise, scroll to the focused index (as long as it's in range)
-            if (this.state.allOptions.length <= this.state.focusedIndex) {
-                return;
-            }
-             this.scrollToIndex(this.state.focusedIndex);
+         if (
+                this.props.selectedOptions.length !== prevProps.selectedOptions.length
+                || _.isEqual(this.props.sections[1].data, prevProps.sections[1].data)
+                || _.isEqual(this.props.sections[2].data, prevProps.sections[2].data)) {
+                this.scrollToIndex(0);
+            }
+       });
    }
```

## Solution 2
We shouldn't scroll to the focused index and whenever ` this.props.selectedOptions.length` is changed or the real text search value is updated, we will scroll to top
In /Expensify/App/src/components/OptionsSelector/BaseOptionsSelector.js
```diff
componentDidUpdate(prevProps) {
        if (_.isEqual(this.props.sections, prevProps.sections)) {
            return;
        }

        const newOptions = this.flattenSections();
        const newFocusedIndex = this.props.selectedOptions.length;
        this.setState({
            allOptions: newOptions,
            focusedIndex: newFocusedIndex,
        }, () => {
            // If we just toggled an option on a multi-selection page, scroll to top
-            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
+            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length || this.props.value !== prevProps.value) {
                this.scrollToIndex(0);
                return;
            }

-            Otherwise, scroll to the focused index (as long as it's in range)
-            if (this.state.allOptions.length <= this.state.focusedIndex) {
-                return;
-            }
-             this.scrollToIndex(this.state.focusedIndex);
    }
```
## Result


https://user-images.githubusercontent.com/113963320/210928818-05f145ff-ac7b-463f-a5e6-46fdf61daa13.mp4

**Comment by mountiny** [comment] 2023-01-06 09:12
@flodnv @NicMendonca @mollfpr Hmm, I would actually argue this is a bug, I think think that once you are ready to search for more people it is fine it is showing the recents. We allow up to 8 people to be selected for a group chat, so then you would only see the selected people when you want to select more, maybe from the recents field.

I would say this is not a bug, maybe we should open a discussion in #expensify-open-source to malign on this and create a regression test accordingly.

Or indeed fix this but endure that it works as we want.

**Comment by flodnv** [comment] 2023-01-06 09:24
Agreed, discussing here: https://expensify.slack.com/archives/C049HHMV9SM/p1672996492671499

**Comment by abdulrahuman5196** [comment] 2023-01-07 18:01
**Proposal**
IMO, Along with the current clear text scroll bug, in this current bug code place, I see we scroll to index 0, but set the focusedIndex state(highlighted row index) as the newFocusedIndex in the code. (We are scrolling to show different row but highlighting a different row). 
If we only just scroll to index 0 when clear the text also to particularly solve this issue, we would still highlight a different row (Row might even be hidden), which will create a new bug in this UI (Which is not happening now as currently it scroll to first unselected row and highlight the same).

For eg, Assume we have a list of 10 people, assuming view can only show 5 rows(different screen sizes can show higher or lower count). We have already selected 5 rows and we clear the search, now we scroll to index 0 as per requirement but set the highlighted row to be 6th row which would be hidden as per below code. Even if you press 'enter' now it only select the 6th row which is hidden from view.

https://github.com/Expensify/App/blob/b081ed14a5384447883f5962c4ca6bfffc070a58/src/components/OptionsSelector/BaseOptionsSelector.js#L103-L115

 **This is weird IMO as we are highlighting a different row but scrolling to a different row, if we just scroll to index 0 to solve this issue**

I have also posted a separate bug in the bug channel now to report the current bug. As we set the highlighted row to be different, there is always a possibility the highlighted row will be hidden when we scroll to 0 row which will also happen if we just fix clear text issue - https://expensify.slack.com/archives/C049HHMV9SM/p1673109991457219. 

**So I am proposing below solutions to solve this clear text issue without causing a new highlight issue bug.**


**Current behaviour:**

>What row should we highlight and scrolled after a user is selected?

Highlight = first row in unselected section, scrollTo = 0
>What row should we highlight and scrolled when we unselected a user?

Highlight = first row in unselected section, scrollTo = 0
>What row should we highlight and scrolled when user types in search?

Highlight = first row in unselected section, scrollTo = No scroll
>What row should we highlight and scrolled when user clears search?

Highlight = first row in unselected section, scrollTo = first row in unselected section
>What position should we scroll the highlighted row to (‘viewPosition’ key)?

Default

---

**Proposed Behaviour 1 (Best IMO):**

>What row should we highlight and scrolled after a user is selected?

Highlight = last selected row, scrollTo = last selected row
>What row should we highlight and scrolled when we unselected a user?

Highlight = 0, scrollTo = 0
>What row should we highlight and scrolled when user types in search?

Highlight = first row in unselected section, scrollTo = first row in unselected section
>What row should we highlight and scrolled when user clears search?

Highlight = 0, scrollTo = 0
>What position should we scroll the highlighted row to (‘viewPosition’ key)?

Default


```diff
--- a/src/components/OptionsSelector/BaseOptionsSelector.js
+++ b/src/components/OptionsSelector/BaseOptionsSelector.js
@@ -96,23 +96,22 @@ class BaseOptionsSelector extends Component {
     }
 
     componentDidUpdate(prevProps) {
-        if (_.isEqual(this.props.sections, prevProps.sections)) {
+        if (_.isEqual(this.props.sections, prevProps.sections) && _.isEqual(this.props.value, prevProps.value)) {
             return;
         }
 
         const newOptions = this.flattenSections();
-        const newFocusedIndex = this.props.selectedOptions.length;
+        let newFocusedIndex = this.props.selectedOptions.length;
+        if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
+            newFocusedIndex = prevProps.selectedOptions.length > this.props.selectedOptions.length ? 0 : this.props.selectedOptions.length - 1
+        } else if (_.isEmpty(this.props.value) && (this.props.value !== prevProps.value)) {
+            newFocusedIndex = 0;
+        }
         // eslint-disable-next-line react/no-did-update-set-state
         this.setState({
             allOptions: newOptions,
             focusedIndex: newFocusedIndex,
         }, () => {
-            // If we just toggled an option on a multi-selection page, scroll to top
-            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
-                this.scrollToIndex(0);
-                return;
-            }
-
             // Otherwise, scroll to the focused index (as long as it's in range)
             if (this.state.allOptions.length <= this.state.focusedIndex) {
                 return;
```


https://user-images.githubusercontent.com/46707890/211162716-49d2440f-53ab-493c-8bf0-45ec4f4489f1.mp4

---

**Proposal behaviour 2:**

>What row should we highlight and scrolled after a user is selected?

Highlight = 0, scrollTo = 0
>What row should we highlight and scrolled when we unselected a user?

Highlight = 0, scrollTo = 0
>What row should we highlight and scrolled when user types in search?

Highlight = first row in unselected section, scrollTo = first row in unselected section
>What row should we highlight and scrolled when user clears search?

Highlight = 0, scrollTo = 0
>What position should we scroll the highlighted row to (‘viewPosition’ key)?

Default

Code diff
```diff
--- a/src/components/OptionsSelector/BaseOptionsSelector.js
+++ b/src/components/OptionsSelector/BaseOptionsSelector.js
@@ -96,23 +96,21 @@ class BaseOptionsSelector extends Component {
     }
 
     componentDidUpdate(prevProps) {
-        if (_.isEqual(this.props.sections, prevProps.sections)) {
+        if (_.isEqual(this.props.sections, prevProps.sections) && _.isEqual(this.props.value, prevProps.value)) {
             return;
         }
 
         const newOptions = this.flattenSections();
-        const newFocusedIndex = this.props.selectedOptions.length;
+        let newFocusedIndex = this.props.selectedOptions.length;
+        if (this.props.selectedOptions.length !== prevProps.selectedOptions.length
+            || (_.isEmpty(this.props.value) && (this.props.value !== prevProps.value))) {
+            newFocusedIndex = 0;
+        }
         // eslint-disable-next-line react/no-did-update-set-state
         this.setState({
             allOptions: newOptions,
             focusedIndex: newFocusedIndex,
         }, () => {
-            // If we just toggled an option on a multi-selection page, scroll to top
-            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
-                this.scrollToIndex(0);
-                return;
-            }
-
             // Otherwise, scroll to the focused index (as long as it's in range)
             if (this.state.allOptions.length <= this.state.focusedIndex) {
                 return;
```

https://user-images.githubusercontent.com/46707890/211162737-2e391db7-2569-49f7-bf90-0f9b577efb27.mp4

---


**Proposal behaviour 3:**

>What row should we highlight and scrolled after a user is selected?

Highlight = first row in unselected section, scrollTo = first row in unselected section
>What row should we highlight and scrolled when we unselected a user?

Highlight = first row in unselected section, scrollTo = first row in unselected section
>What row should we highlight and scrolled when user types in search?

Highlight = first row in unselected section, scrollTo = first row in unselected section
>What row should we highlight and scrolled when user clears search?

Highlight = 0, scrollTo = 0
>What position should we scroll the highlighted row to (‘viewPosition’ key)?
Default


```diff
--- a/src/components/OptionsSelector/BaseOptionsSelector.js
+++ b/src/components/OptionsSelector/BaseOptionsSelector.js
@@ -96,23 +96,20 @@ class BaseOptionsSelector extends Component {
     }
 
     componentDidUpdate(prevProps) {
-        if (_.isEqual(this.props.sections, prevProps.sections)) {
+        if (_.isEqual(this.props.sections, prevProps.sections) && _.isEqual(this.props.value, prevProps.value)) {
             return;
         }
 
         const newOptions = this.flattenSections();
-        const newFocusedIndex = this.props.selectedOptions.length;
+        let newFocusedIndex = this.props.selectedOptions.length;
+        if ((_.isEmpty(this.props.value) && (this.props.value !== prevProps.value))) {
+            newFocusedIndex = 0;
+        }
         // eslint-disable-next-line react/no-did-update-set-state
         this.setState({
             allOptions: newOptions,
             focusedIndex: newFocusedIndex,
         }, () => {
-            // If we just toggled an option on a multi-selection page, scroll to top
-            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
-                this.scrollToIndex(0);
-                return;
-            }
-
             // Otherwise, scroll to the focused index (as long as it's in range)
             if (this.state.allOptions.length <= this.state.focusedIndex) {
                 return;
```

https://user-images.githubusercontent.com/46707890/211162750-a7946fd0-218f-409a-a331-131bb1164467.mp4

---


I think proposal 1 would have the best behaviour. But, If required we can also mix and match the above 3 to create different behaviour combination.


---


**Proposal with just clear text scroll fix** 

**Code diff**
```diff
--- a/src/components/OptionsSelector/BaseOptionsSelector.js
+++ b/src/components/OptionsSelector/BaseOptionsSelector.js
@@ -108,7 +108,8 @@ class BaseOptionsSelector extends Component {
             focusedIndex: newFocusedIndex,
         }, () => {
             // If we just toggled an option on a multi-selection page, scroll to top
-            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length) {
+            if (this.props.selectedOptions.length !== prevProps.selectedOptions.length
+                || (_.isEmpty(this.props.value) && (this.props.value !== prevProps.value))) {
                 this.scrollToIndex(0);
                 return;
             }
```

https://user-images.githubusercontent.com/46707890/211162770-02d9b3b8-a3ab-4367-99f5-431286707c30.mp4

**Comment by mollfpr** [comment] 2023-01-08 16:34
@Ollyws [proposal](https://github.com/Expensify/App/issues/14001#issuecomment-1372832211)'s looking good to me. The expected result will be to scroll to the top so the selected user is visible whenever the search box is cleared.

🎀 👀 🎀 C+ reviewed!

cc @flodnv @NicMendonca

**Comment by allroundexperts** [comment] 2023-01-08 16:41
@mollfpr My proposal does the same thing. Have you considered it?

**Comment by abdulrahuman5196** [comment] 2023-01-08 17:33
@mollfpr doesn't just scrolling to top without changing the highlight cause the issue I mentioned here - https://github.com/Expensify/App/issues/14001#issuecomment-1374553260

Are we ok with that behaviour?

**Comment by mollfpr** [comment] 2023-01-08 17:57
@allroundexperts Yes. In your proposal selecting an account and searching for another account by typing in the search box, the scroll position remains the same. I don't think we want that.

---

> For eg, Assume we have a list of 10 people, assuming view can only show 5 rows(different screen sizes can show higher or lower count). We have already selected 5 rows and we clear the search, now we scroll to index 0 as per requirement but set the highlighted row to be 6th row which would be hidden as per below code. Even if you press 'enter' now it only select the 6th row which is hidden from view.

Thanks for the detailed @abdulrahuman5196 but what you pointing out is another issue and we don't know yet if that will be an issue.

I don't mind after selecting an account the highlight option is the first row unselected option, this will be helpful if navigating through the options with the arrow key to go through the unselected options.

**Comment by allroundexperts** [comment] 2023-01-08 17:59
@mollfpr Are you sure we don't want that behaviour? Because In my opinion, it makes more sense to keep the selected item sticky throughout.

**Comment by mollfpr** [comment] 2023-01-08 18:09
> Because In my opinion, it makes more sense to keep the selected item sticky throughout.

@allroundexperts For example, if we have 7 selected options already and searching for another account will only give a smaller space visibility to show unselected options, am I correct? If is that so, I think this will be an issue in the future or even regression.

**Comment by allroundexperts** [comment] 2023-01-08 18:10
@mollfpr That makes sense. You are right. Thanks for the clarification!

**Comment by abdulrahuman5196** [comment] 2023-01-08 19:17
>Thanks for the detailed @abdulrahuman5196 but what you pointing out is another issue and we don't know yet if that will be an issue.

@mollfpr I am attaching a video where the issue i mentioned happens when we just scroll to index 0 when this.props.value is empty with the accepted proposal

https://user-images.githubusercontent.com/46707890/211214450-e2585765-ecfb-47af-87ca-9fb537a9f3eb.mp4




---
>I don't mind after selecting an account the highlight option is the first row unselected option, this will be helpful if navigating through the options with the arrow key to go through the unselected options.

Even if you press 'enter' after clearing the search text on the issue i mentioned, you would be selecting a hidden row from the view. Added the same case in the above video. Which is not happening now.

**Comment by mollfpr** [comment] 2023-01-09 01:36
@abdulrahuman5196 That will be a different issue than this. I think your suggested behavior will be considered in the list selection redesign, not in this issue.

cc @flodnv @NicMendonca

**Comment by flodnv** [comment] 2023-01-09 09:49
Thank you for the proposals and discussions everyone. I agree with @mollfpr, let's hire @Ollyws, @NicMendonca.

**Comment by flodnv** [comment] 2023-01-10 11:44
@sophiepintoraetz, seeing as @NicMendonca is out, can you please hire @Ollyws ?

@Ollyws feel free to start on the PR.

**Comment by mountiny** [comment] 2023-01-10 11:46
Just noting that the External Label creates a new Upwork job so we might have multiple jobs now (unless there was some fix added to this). We might want to clean that up @sophiepintoraetz 

If you want new BZ member, you can use the Bug autoassigner instead and the job wont be created @flodnv

**Comment by mollfpr** [comment] 2023-01-10 12:01
@Ollyws IMO that is intended.
https://github.com/Expensify/App/blob/2ee71ac9e16fec49e67fef4c541b00ea394426ce/src/components/OptionsSelector/BaseOptionsSelector.js#L98-L101

**Comment by mollfpr** [comment] 2023-01-10 12:08
@Ollyws I see that this will be your first PR in the repo could you follow this step [Begin coding your solution in a pull request](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request) to start? Thanks!

**Comment by mollfpr** [comment] 2023-01-10 12:13
Ahh sorry for that, I must be misspelling your name before. 😅

**Comment by flodnv** [comment] 2023-01-10 13:10
lol whoops thanks @mountiny 

Thanks for the PR @Ollyws

**Comment by sophiepintoraetz** [comment] 2023-01-11 03:48
@flodnv - can you confirm that Olly is to be paid $1000 + the PR merge bonus of 50% (i.e. $1500?)

**Comment by flodnv** [comment] 2023-01-11 10:10
Yes please 👍

**Comment by mollfpr** [comment] 2023-01-11 10:11
Will I get the bonus too? 😁

**Comment by flodnv** [comment] 2023-01-11 10:22
Yep 👍

**Comment by sophiepintoraetz** [comment] 2023-01-12 02:51
@Ollyws - contract for payment is with you
@mollfpr - you can apply for the job [here](https://www.upwork.com/ab/applicants/1611089102897319936/job-details) for $1500 also.

**Comment by mollfpr** [comment] 2023-01-12 03:05
@sophiepintoraetz I can't open the link.

**Comment by sophiepintoraetz** [comment] 2023-01-12 03:11
Sorry, try [this one!](https://www.upwork.com/jobs/~012de37194a5fa31d2)

**Comment by mollfpr** [comment] 2023-01-12 03:18
@sophiepintoraetz Applied, thank you!

**Comment by mollfpr** [comment] 2023-01-12 04:09
@sophiepintoraetz I think you should end the Upwork contract after the PR is in production and past the 7 days regression period 😅

Currently, the PR is still in staging but maybe later today or tomorrow will hit production.

**Comment by sophiepintoraetz** [comment] 2023-01-12 04:10
Ah, I am on auto-pilot mode - wow - let's hope a regression doesn't pop up 😅

**Comment by sophiepintoraetz** [comment] 2023-02-17 04:50
@flodnv @mollfpr shall we close this GH out? Or is there an offending PR we need to source here?

**Comment by mollfpr** [comment] 2023-02-17 11:15
@sophiepintoraetz @flodnv I don’t there’s a PR causing this regression. As mentioned in the Slack discussion, is more of a polish issue.

**Closed** 2023-02-17 19:52 UTC
Labels: Reviewing, External, Monthly, Bug
