### ISSUE TITLE
[$500] Inline codeblock with white spaces until the end of the first line after text  is displayed out of screen

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29408] opened 2023-10-12 02:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696951472944249

## Action Performed:
1. Open the app
2. Open any report
3. Write inline codeblock message start with backtick and few text and spaces till the end of 1st line in the composer  and closing backtick at last position of line
4. Send and observe that inline code block extends beyond message space limit and out of screen
## Expected Result: 
Message should not extend beyond message space limit and go out of screen
## Actual Result: 
inline code block extends beyond message space limit and out of screen
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/c4386859-685e-49af-96da-29a40d47c6ee

https://github.com/Expensify/App/assets/38435837/99ae5afd-300f-4e22-ba01-4ca0781c81e2

https://github.com/Expensify/App/assets/38435837/6cc83e51-ce67-46a0-86f3-0895ca358d04

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/7de38f7f-b4d1-4e77-8883-5d060efc8219

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef24d53e746def21</li>
        <li>Upwork Job ID: 1712289035004960768</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by Washyl** [comment] 2023-10-12 02:31
To display an inline code block with white spaces until the end of the first line after text, you can use HTML and CSS to style the code block accordingly.

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    .inline-code {
      white-space: pre;
    }
  </style>
  <title>Inline Code Example</title>
</head>
<body>
  <p>This is some text with an inline code block: <code class="inline-code">code block with white spaces until the end of the first line after text</code>. Continue with the rest of the text.</p>
</body>
</html>

the white-space: pre; CSS rule for the .inline-code class preserves white spaces and line breaks within the <code> element, making it display exactly as written. 
The text will not wrap to the next line, and any spaces or line breaks will be maintained until the end of the first line after the text. Adjust the content of the <code> element as needed.

**Comment by Washyl** [comment] 2023-10-12 02:35
To display an inline code block with white spaces until the end of the first line after text, you can use HTML and CSS to style the code block accordingly. Here's an example:

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    .inline-code {
      white-space: pre;
    }
  </style>
  <title>Inline Code Example</title>
</head>
<body>
  <p>This is some text with an inline code block: <code class="inline-code">code block with white spaces until the end of the first line after text</code>. Continue with the rest of the text.</p>
</body>
</html>
In this example, the white-space: pre; CSS rule for the .inline-code class preserves white spaces and line breaks within the <code> element, making it display exactly as written. The text will not wrap to the next line, and any spaces or line breaks will be maintained until the end of the first line after the text. Adjust the content of the <code> element as needed.

**Comment by Washyl** [comment] 2023-10-12 02:38
Contributor details
Your Expensify account email: nari19870670@gmail.com
Upwork Profile Link:https://www.upwork.com/freelancers/~0104ec48c16c99266e

**Comment by b4s36t4** [comment] 2023-10-12 04:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
nline codeblock with white spaces until the end of the first line after text is displayed out of screen
### What is the root cause of that problem?

We never had any styling for handling moving the things out of the screen for `InlineCodeBlock` component. We're just extending the styles we're getting from `react-native-html-renderer`

### What changes do you think we should make in order to solve the problem?

We need to add `whiteSpace` property with value `break-spaces` to let the message break (`pre`) tag into new line.

> As the message ends with all the spaces (` is at the end so we should render all the message)  we can't go with other values of `whiteSpace` which may contain some more issues.



### What alternative solutions did you explore? (Optional)
NA

<img width="705" alt="Screenshot 2023-10-12 at 10 03 54 AM" src="https://github.com/Expensify/App/assets/59088937/8cdb05f0-9dfe-45df-926a-a0665f8a9db9">

**Comment by gs3bopar** [comment] 2023-10-12 07:58
Contributor details
Your Expensify account email: gurkaransingh10@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0176028098f8a29acb

**Comment by abdulrahuman5196** [comment] 2023-10-15 05:41
@Washyl Kindly provide proposals as per our proposal template - https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md

**Comment by abdulrahuman5196** [comment] 2023-10-15 05:43
@b4s36t4 I am not able to fully understand the proposal. Could you provide references of what style you are suggesting to be updated? What place? Any code pointers?

**Comment by b4s36t4** [comment] 2023-10-15 05:53
<img width="1152" alt="Screenshot 2023-10-15 at 11 18 07 AM" src="https://github.com/Expensify/App/assets/59088937/71af27a3-d107-4df8-8f67-74a94be0e5f6">

here in this file https://github.com/Expensify/App/blob/3aadd3f328c117a36a53e1bd79e876b12a27880e/src/components/InlineCodeBlock/index.js

@abdulrahuman5196 

> need to test this on native devices for web/desktop it's working fine.

**Comment by abdulrahuman5196** [comment] 2023-10-15 07:27
>need to test this on native devices for web/desktop it's working fine.

@b4s36t4 Kindly test and add the above information to the proposal once ready. I will re-review.

**Comment by b4s36t4** [comment] 2023-10-15 12:17
@abdulrahuman5196 I think there is an inconsistency between native devices and web. In native devices we're stripping the the white-space.

What can do we here? make web remove space as well or update native devices to support spaces?
<img width="491" alt="Screenshot 2023-10-15 at 5 46 57 PM" src="https://github.com/Expensify/App/assets/59088937/80038324-1b8b-4ad5-b933-22ec67c85063">

**Comment by greg-schroeder** [comment] 2023-10-17 20:41
Apparently this is a dupe of https://github.com/Expensify/App/issues/29387

**Closed** 2023-10-19 00:59 UTC
Labels: External, Daily, Help Wanted, Bug
