### ISSUE TITLE
Dev: Web  - Console error when sending message after uploading attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22834] opened 2023-07-13 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a attachment
3. After sending send messages

## Expected Result:
Console error should not appear

## Actual Result:
Console error when sending message after uploading attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev  1.3.39-10
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7eeb5038-9864-4ccb-bc11-6644f11bfdef

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689191535627969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment] 2023-07-13 18:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Console error when sending message after uploading attachment

### What is the root cause of that problem?
This line is wrong:

https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/libs/actions/Report.js#L250

### What changes do you think we should make in order to solve the problem?
The line should be like this.
```javascript
        prevVisibleMessageText = Localize.translateLocal(lastVisibleMessage.lastMessageTranslationKey);
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pujan92** [comment] 2023-07-13 19:27
Dupe of https://github.com/Expensify/App/issues/22750

**Comment by stephanieelliott** [comment] 2023-07-18 07:29
Agree this is a dupe of the other issue. Closing!

**Closed by stephanieelliott** 2023-07-18 07:29 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
