### ISSUE TITLE
mWeb/Chrome - Infinite spinner after redirected back to NewDot and finishing the 2FA setup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13326] opened 2022-12-05 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #12424 

## Action Performed:
Prerequisite: User should have 2FA disabled in OldDot > Settings > Accounts

1. Go to URL https://staging.new.expensify.com/

2. Go to Settings -> Workspace -> Open any workspace (or create it, or create it if it doesn't exist)
3. Go to Connect Bank Account -> Connect manually
4. Enter routing number - 011401533, account number - 1111222233331111, and checkmark the "I accept the Expensify Terms of Service"
5. Enter correct company information and personal information
6. Checkmark both: "I accept the terms and conditions" and "I certify that the information provided is true and accurate"
7. Confirm the 2FA prompt
8. Click on "Secure Account"
9. Finish the 2FA setup. Upon clicking Finish

## Expected Result:
 After finishing the 2FA setup. Upon clicking Finish, you're redirected back to NewDot

## Actual Result:
I was redirected to OldDot mWeb, and after set up 2FA to NewDot app, where I see infinite spinner

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** could not verify
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/205694595-b760d85e-f4e1-492b-8c97-227b063e3e03.mp4

<img src="https://user-images.githubusercontent.com/43996225/205693453-dc0a7a62-1a3b-4900-bfa3-809a76ae2f71.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-12-05 19:31
This may have been caused by the ongoing server slowness

**Comment by francoisl** [comment] 2022-12-06 00:29
Yep I can't reproduce at the moment, could you try again please @kavimuru?

**Comment by kavimuru** [comment] 2022-12-06 20:48
@francoisl Will retest and update here shortly.

**Comment by kavimuru** [comment] 2022-12-07 17:44
@francoisl Sorry for the delay. Infinite loading is fixed, but after redirecting, it lands on `Connect to bank account` page instead of `Continue set up ` / `Start over `

https://user-images.githubusercontent.com/43996225/206254560-e43508d0-7b9e-4ca1-a6a8-930fd35ce7e3.mp4

**Comment by francoisl** [comment] 2022-12-07 17:58
Yeah I'm also unable to fully QA that PR, though I'm getting a different outcome than you. I posted in the PR and tagged the author [here](https://github.com/Expensify/App/pull/12424#issuecomment-1341354521).

**Comment by francoisl** [comment] 2022-12-08 18:33
We ended up reverting https://github.com/Expensify/App/pull/12424 yesterday, so that 2FA flow no longer exists (for now). I'd say we can close this.

**Closed** 2022-12-08 19:50 UTC
Labels: Daily, Overdue, Bug
