### ISSUE TITLE
[HOLD for payment via Newdot] [$1000] Web - Popover is covering the profile photo

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19453] opened 2023-05-23 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Settings
2. Click on Profile
3. Click on Profile photo

## Expected Result:
Popover is below the profile photo

## Actual Result:
 It is covering the profile photo

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (43)](https://github.com/Expensify/App/assets/93399543/982175f3-f812-43dd-8bc4-90d865c03c17)

![image (42)](https://github.com/Expensify/App/assets/93399543/65ad21de-afca-4604-908a-7aaccf529fe4)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aman-atg 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684405187865699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc0bf9674a11fb34</li>
        <li>Upwork Job ID: 1661229768425656320</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-05-24 04:35
Reproduced on web and desktop:

![image](https://github.com/Expensify/App/assets/59587260/5aa229aa-06c3-4107-89df-7658b59732e7)

![image](https://github.com/Expensify/App/assets/59587260/b4433d38-ecbd-4465-9b70-66f200d696bd)

**Comment by Santhosh-Sellavel** [comment] 2023-05-24 17:26
@iwiznia Is this worth addressing?

**Comment by iwiznia** [comment] 2023-05-24 17:38
hmmm I don't know, is it really a bug?

**Comment by Santhosh-Sellavel** [comment] 2023-05-24 17:45
It doesn't look like a bug to me either. Can you tag anyone or check internally?

**Comment by towkir** [comment] 2023-05-24 19:42
Doesn't really ring as a bug, when you click the profile photo, (if you don't have a preview feature for the profile photo) this should be the expected behavior, the other options you might have is to move the popover a bit down, in that case, it would cover the rest of the content.

**Comment by iwiznia** [comment] 2023-05-24 20:22
Ah got it, ok I agree it's a bug then. @Santhosh-Sellavel can you review the proposals please?

**Comment by Varunvaru524** [comment] 2023-05-25 12:34
# Proposal

## Please re-state the problem that we are trying to solve in this issue.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When we click on the edit profile picture in settings or in the workspace, if the profile picture is empty then the popover menu will be displayed normally, but when we upload a picture to the profile or the workspace then the popover menu will be shown on top of the profile picture itself as shown in the below screenshots


#### Without a profile picture in the profile section
![Before no pp](https://github.com/Expensify/App/assets/101904494/b81eba3e-0036-4c71-ba7a-b9930a927a66)


#### With a profile picture in the profile section
![Before with pp](https://github.com/Expensify/App/assets/101904494/014cef0b-5eea-47bd-9653-c7df59105907)


#### Without a profile picture in the Workspace section
![Before no wp](https://github.com/Expensify/App/assets/101904494/40d6fe7c-1ed4-4daa-b9f0-c1390315e5ad)


#### With a profile picture in the Workspace section
![before with wp](https://github.com/Expensify/App/assets/101904494/b3252105-f0b2-4101-a41a-6510c541c287)


## What is the root cause of that problem?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[createMenuPositionProfile()](https://github.com/Expensify/App/blob/main/src/styles/styles.js#L1217) function from styles is used to pass an object with properties horizontal and vertical to the prop [anchorPosition](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/ProfilePage.js#L105) of the component [AvatarWithImagePicker](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/ProfilePage.js#LL100C22-L100C43) to control the position of the components which is in the position absolute. 

But the problem is the vertical position is static with [250](https://github.com/Expensify/App/blob/main/src/styles/styles.js#L1219) and the horizontal position is dynamic as you can see [here](https://github.com/Expensify/App/blob/main/src/styles/styles.js#L1218). So when there is no profile picture the popover menu works perfectly fine because it has only one button inside i.e. upload photo, but when there is already a profile picture inside it will show you two buttons i.e. upload photo and remove photo, that's where this bug exists.


## What changes do you think we should make in order to solve the problem?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We should make the vertical property dynamic by adding conditional statements to the `createMenuPositionProfile()` function. we can do that by passing another argument to this function that knows whether the picture is present or not because now this function only takes one argument which is the current width of the window. 

This fixes the problem that the popover menu only hides the profile picture when there already a profile picture exists on the profile page and workspace page. The main important point is the `createMenuPositionProfile()` function is used only in two places which are the profile page and the workspace page so that it will not affect any other components in the application.

Below are the screenshots that this approach works

#### Without a profile picture in the profile section
![after no pp](https://github.com/Expensify/App/assets/101904494/7af19e3d-6d24-45b4-8c2b-b66cd9d828a1)


#### With a profile picture in the profile section
![after with pp](https://github.com/Expensify/App/assets/101904494/668ddc1e-64bd-4538-baa7-df15f3705d3b)


#### Without a profile picture in the Workspace section
![after no wp](https://github.com/Expensify/App/assets/101904494/bfb1c71b-983c-4b36-8eeb-dab36e0a1041)


#### Without a profile picture in the Workspace section
![after with wp](https://github.com/Expensify/App/assets/101904494/84b7d9cd-a971-43fd-9b81-de107514796e)


### What alternative solutions did you explore? (Optional)

1. I think we can also solve this by adding some more logic to [this](https://github.com/Expensify/App/blob/main/src/components/PopoverWithMeasuredContent.js#L161-L167) section. But this might cause more problems for the application because [this](https://github.com/Expensify/App/blob/main/src/components/PopoverWithMeasuredContent.js) component may have been used in other places of the application as well.
2. To build a completely different component for the profile picture popover section, because the current component is used in lot of other parts of the application as well and there is a lot of prop drilling happening in the current component

**Comment by Varunvaru524** [comment] 2023-05-25 12:50
Contributor details
Your Expensify account email: varunvaru524@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01967836eab3f36a29

**Comment by Santhosh-Sellavel** [comment] 2023-05-25 21:14
@huzaifa-99 Proposal looks good to me, as the root cause and solution look good to me.

**Comment by Santhosh-Sellavel** [comment] 2023-05-29 17:01
Waiting for CME

**Comment by iwiznia** [comment] 2023-05-30 18:14
If they are related and we can fix them both here, then I think that's fine, no? @Santhosh-Sellavel what do you think?

**Comment by kadiealexander** [comment] 2023-06-19 07:44
@jliexpensify thanks for issuing payment while I'm OOO! I've sent contracts to everyone [here](https://www.upwork.com/ab/applicants/1661229768425656320/hired).

**Comment by Santhosh-Sellavel** [comment] 2023-06-20 17:31
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18692
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18692/files#r1235590347
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A This should have been caught during review & testing.
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

@iwiznia I think we don't need regression testing here. Let me know your thoughts or differ with any of the above, thanks!

**Comment by iwiznia** [comment] 2023-06-20 17:44
I assume that we are already testing this flow in the regression tests, so adding this regression should be just saying `Check the popup appears below the photo` or something like that, no?

**Comment by Santhosh-Sellavel** [comment] 2023-06-20 18:06
@iwiznia 
Then the steps from PR look good to me.

### Regression Steps

1. Go to profile settings page /settings/profile - verify that on clicking the photo icon the popover is not covering the profile photo
2. Go to profile settings page /workspace/:id/settings - verify that on clicking the photo icon the popover is not covering the workspace photo
3. Go to a workspace details page /workspace/:id - verify that on clicking the 3-dots the popover is not covering the header

👍  or  👎 

cc: @jliexpensify

**Comment by jliexpensify** [comment] 2023-06-21 22:23
Paid @aman-atg and @huzaifa-99 - @Santhosh-Sellavel can you accept the offer? Cheers.

**Comment by jliexpensify** [comment] 2023-06-23 00:40
Bump @Santhosh-Sellavel 

![image](https://github.com/Expensify/App/assets/30815269/68ecd7f6-e4e4-4e5c-b783-669c7e175bf0)

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 19:22
@jliexpensify I'm just waiting for the internal process, please check [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1687451792686509?thread_ts=1686871517.189609&cid=C02NK2DQWUX)

**Comment by jliexpensify** [comment] 2023-06-24 02:43
Ohh got it - ping me when you're ready to be paid @Santhosh-Sellavel

**Comment by kadiealexander** [comment] 2023-06-25 23:10
Taking this back, thanks for your help @jliexpensify!!

**Comment by kadiealexander** [comment] 2023-06-29 00:20
Shifting this to weekly while we wait for the new payment process to be confirmed.

**Comment by Santhosh-Sellavel** [comment] 2023-07-09 20:19
Yet to request payment will update in a couple of days!

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 21:35
Requested on ND

**Comment by anmurali** [comment] 2023-07-18 18:00
Approved payment on ND

**Comment by iwiznia** [comment] 2023-07-21 20:17
Seems this is mostly ready, so not unassigning myself, but if this does not get closed, @kadiealexander  please unassign and re-assign another engineer since I am going on sabbatical

**Comment by Santhosh-Sellavel** [comment] 2023-07-21 20:22
We can close this nothing pending here!

**Closed** 2023-07-24 02:22 UTC
Labels: External, Weekly, Awaiting Payment, Bug
