### ISSUE TITLE
[PAID] [$250] Taxes - App crashes when visiting transaction thread with invalid tax rate on a fresh session

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39695] opened 2024-04-05 11:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin and employee are in the same Collect workspace.
- The Collect workspace has several tax rates.

1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat.
3. [Employee] Create manual request with a tax rate in workspace chat.
4. [Admin] On Old Dot, delete the tax rate selected in Step 3.
5. [Employee] Go to Settings > About > Troubleshoot > Clear cache and restart > Reset and refresh (relogin can also be done).
6. [Employee] Navigate to the transaction thread with invalid tax rate.

## Expected Result:
App should not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1379bb26-ad96-4409-a37d-5141d4c3240a

[Bug6438754_1712289000497!staging.new.expensify.com-1712288865325.txt](https://github.com/Expensify/App/files/14884132/Bug6438754_1712289000497.staging.new.expensify.com-1712288865325.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfd8b2886cedb8f1</li>
        <li>Upwork Job ID: 1776209471760666624</li>
        <li>Last Price Increase: 2024-04-05</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-05 11:24
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-05 11:25
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-05 11:25
Production 


https://github.com/Expensify/App/assets/115492554/4992224d-61a9-42cb-9681-d0878d8e8d59

**Comment by nkdengineer** [comment] 2024-04-05 11:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/a01b338bdbcd563ac4ef81bb1c7f629342624604/src/libs/TransactionUtils.ts#L628), we don't check if `taxRates` is defined or not before trying to get the `name`.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/a01b338bdbcd563ac4ef81bb1c7f629342624604/src/libs/TransactionUtils.ts#L628), if `taxRates` is undefined, early return undefined/empty.

### What alternative solutions did you explore? (Optional)
NA

**Comment by MonilBhavsar** [comment] 2024-04-05 11:36
Looks different to me @getusha

**Comment by shahinyan11** [comment] 2024-04-05 11:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Taxes - App crashes when visiting transaction thread with invalid tax rate on a fresh session
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/a01b338bdbcd563ac4ef81bb1c7f629342624604/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L860C34-L860C47), [here](https://github.com/Expensify/App/blob/a01b338bdbcd563ac4ef81bb1c7f629342624604/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L874C29-L874C42) and [here](https://github.com/Expensify/App/blob/a01b338bdbcd563ac4ef81bb1c7f629342624604/src/libs/TransactionUtils.ts#L628C49-L628C83) we do not get the `name` optionally
### What changes do you think we should make in order to solve the problem?
Use `?.name` instead

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-04-05 11:44
@MonilBhavsar Just checking if you're working on this directly or will select a contributor to quickly fix it?

Since I see you self-assigned but the issue still has `Help Wanted` label, so conflicting signals.

**Comment by MonilBhavsar** [comment] 2024-04-05 11:46
I had a look at both proposals and it misses some places where fix needs to be applied. So I am now working on this, given this is a deploy blocker. Thanks for the proposal though!

**Comment by nkdengineer** [comment] 2024-04-05 11:54
@MonilBhavsar I think we can handle the `some places where fix needs to be applied` part in the PR (assuming you're saying the solution looks correct but missing the permalinks to every place where the issue happens)

> There're other places where tax rate name is accessed unsafely like this too, and should be fixed similarly.

**Comment by MonilBhavsar** [comment] 2024-04-05 12:19
sorry, the proposal differed a lot from expected solution and since deploy blockers are very high priority issues, we would prefer complete proposals, so we could ship it as soon as possible without much back and forth during PR reviews.

**Comment by MonilBhavsar** [comment] 2024-04-05 14:52
Issue is fixed on staging!

Recording! https://drive.google.com/file/d/18ArPPsMyXBqOxaPYctpKX_W59uu9-mzr/view?usp=sharing

**Comment by strepanier03** [comment] 2024-04-15 23:48
@shubham1206agra - Please finish up the checklist when you have a chance and I'll finish up on my end once you do. Thanks!

**Comment by strepanier03** [comment] 2024-04-17 20:58
I'm fairly certain PR [reviews](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit) that don't require a lot of changes or testing should be $250, even prior to the price change that went into effect on April 6th.

**Comment by strepanier03** [comment] 2024-04-19 21:38
Thanks for the checklist @shahinyan11- I've paid out the contract and closed it in Upwork. Thanks again!

**Closed by strepanier03** 2024-04-19 21:38 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
