### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] Distance - Blank map preview on employee side when selecting distance rate with different unit

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51285] opened 2024-10-22 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+ck11020@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
1. Admin invited employee to workspace
2. Distance rates enabled in WS settings & Unit set to Miles in distance rates settings

Employee' side:
1. Navigate to staging.new.expensify.com
2. Click >> FAB >> Submit Expense >> Distance tab
3. Submit distance expense
4. Go to expense details page

Admin's side:
1. Go to WS settings >> Distance rates
2. Select settings option
3. Change the unit to Kilometer

Employee's side:
1. On the expense details page, select distance rate field
2. Select a different rate

## Expected Result:
When admin changes the distance unit setting, map preview for distance expense should update on employee side on selecting distance rate with different unit
However, map preview on admin's side in expense details page gets updated as expected

## Actual Result:
Blank map preview on employee side when selecting distance rate with different unit

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b4e0b82-dc67-4420-b963-b93f9371d21b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849108498732119693</li>
        <li>Upwork Job ID: 1849108498732119693</li>
        <li>Last Price Increase: 2024-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 104675461</li>
<li>nkdengineer | Contributor | 104675465</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by IuliiaHerets** [comment] 2024-10-22 18:48
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-10-23 09:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank map preview on employee side when selecting distance rate with different unit

### What is the root cause of that problem?
When we change the distance rate if the unit is changed, we will add `pendingFields.waypoints` to `updatedTransaction`

https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L283-L291


We override `pendingFields` here which causes `updatedTransaction.pendingFields` to be an empty object

https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L326


But `updatedTransaction` is only a shadow clone of `transaction` then `transaction` that is getting from `allTransactions` is updated when we use `lodashSet`. Then when optimistic data is merged `pendingFields.waypoints` is `update` in Onyx

https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L239

And this pendingFields isn't cleared in success data because `updatedTransaction.pendingFields` is an empty object which causes `clearedPendingFields` not to include `waypoint` field

https://github.com/Expensify/App/blob/f251dbcdfdafc492d9a9908cbf40e4630b7b6d9d/src/libs/actions/IOU.ts#L2738

After all, `pendingFields.waypoints` isn't cleared then the map view isn't shown here
https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/components/ReportActionItem/ReportActionItemImage.tsx#L86-L89

### What changes do you think we should make in order to solve the problem?
1. I guess we add `pendingFields.waypoints` here to gray out the distance field when we change the distance rate offline.

https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L283-L291

But `pendingFields.waypoints` is also used to check whether we're fetching the waypoints from the server or not then I think we should separate these cases to use two pendingFields

For this case, I think we can use `pendingFields.merchant` because only the display distance text is changed

https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L283-L291


```
<OfflineWithFeedback pendingAction={getPendingFieldAction('waypoints') || getPendingFieldAction('merchant')}> 
```
https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/components/ReportActionItem/MoneyRequestView.tsx#L309


2. We should update this line not to override the existing pending field that we updated at the logic [here](https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L283-L291)

```
updatedTransaction.pendingFields = {
        ...(updatedTransaction.pendingFields ?? {}),
        ....
        }
```
https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L326

3. We should use deep clone here by using `lodashCloneDeep` from `lodash/cloneDeep`

```
const updatedTransaction = lodashCloneDeep(transaction);
```
https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L239

### What alternative solutions did you explore? (Optional)
If we still want to display a blank view until the API is complete we can skip point 1 above

Or if we don't want to gray out the distance field when updating to a different unit, we can remove this line but we still need to deep clone the transaction to prevent the same case can happen in the feature.

https://github.com/Expensify/App/blob/e2d99b4416410a47655a6cba6edb8787dd3c000d/src/libs/TransactionUtils/index.ts#L291

**Comment by nkdengineer** [comment] 2024-10-29 19:54
@ishpaul777 Did you also change with the step 2 and 3 in my main proposal?

**Comment by nkdengineer** [comment] 2024-10-30 01:40
Thanks, let me check.

**Comment by nkdengineer** [comment] 2024-10-30 04:57
@ishpaul777 Found the problem, we need to update `pendingFields` of the transaction in optimistic correctly. The full test branch [here](https://github.com/nkdengineer/App/tree/fix/51285).

**Comment by twisterdotcom** [comment] 2024-11-18 17:03
Relabelling as Lauren is OOO now.

**Comment by Christinadobrzyn** [comment] 2024-11-19 02:45
@ishpaul777 do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-11-20 04:33
Thanks @ishpaul777! I paid out through Upwork based on this payment summary. 

- [X] Contributor: $250 @nkdengineer (paid in Upwork - https://www.upwork.com/nx/wm/workroom/38884927/overview)
- [X] Reviewer: $250 @ishpaul777 (paid in Upwork - https://www.upwork.com/nx/wm/workroom/39008204/overview)

Closing!

**Closed by Christinadobrzyn** 2024-11-20 04:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
