### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-09][$500] Fix offline distance requests

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#28289] opened 2023-09-27 03:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Click the green plus, request money, distance
3. Enter a valid address for start and finish waypoints
4. Verify that you can click next
5. Select a workspace
6. Verify that all information shows or is TBD
7. Click request
8. Verify that the report preview shows a pending receipt image with the amount and miles as TBD
9. Click the report preview
10. Verify that the request shows as distance, with the amount and miles as TBD
11. Click on the request
12. Verify that the request shows as distance, with the amount and miles as TBD
13. Go online
14. Verify that all pending data fills

## Expected Result:
All verifications pass

## Actual Result:
The first verification step fails

## Workaround:
Create requests online only

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://github.com/Expensify/App/assets/26260477/146a1ef9-f182-4ccf-92a7-4deda2fa6825

**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695786405195339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a10d251bbc7f89f6</li>
        <li>Upwork Job ID: 1706878203997462528</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-09-27 03:48
I'm going to push a quick fix to enable the next button, then we should fix the rest externally.

**Comment by Pujan92** [comment] 2023-09-27 04:27
> I'm going to push a quick fix to enable the next button, then we should fix the rest externally.

Is this regression from https://github.com/Expensify/App/pull/27989?

**Comment by ikevin127** [comment] 2023-09-27 13:48
I confirm that after @neil-marcellini's fix [#28292](https://github.com/Expensify/App/pull/28292) all verifications are passing and also all pending data fills upon getting back online but only if step **5. Select a workspace** is performed by selecting a workspace from the **Recents** suggestions.

If another participant is selected by email address instead of selecting a workspace from recents suggestions, then upon getting back online, the **CreateDistanceRequest** call errors with message **Report no longer exists** which makes the conversation dissappear and errors with **Hmm... it's not here** screen.

Can someone please update the **Expected result** for this issue if one is still needed ?

**Comment by neil-marcellini** [comment] 2023-09-28 06:47
We already fixed verification #4. I think verification steps from 10 and 12 are failing. Please submit proposals for that.

**Comment by neil-marcellini** [comment] 2023-09-28 06:49
This [bug](https://github.com/Expensify/App/issues/28289#issuecomment-1737439695) seems like a separate problem. It should only be possible to select a single workspace right now. Please report that separately.

**Comment by chiragsalian** [comment] 2023-09-28 17:19
Why is this issue a deploy blocker. Please add context when applying the label. From what i see the issue here occurs in production so there is no reason this should be a blocker. Additionally, remember to handle deploy blockers in an hourly manner (or at least finish them within a day), this issue has been a blocker for 2 days now.

**Comment by chiragsalian** [comment] 2023-09-28 17:32
I did a quick test on staging and i think the issue is resolved. I'm going to clear the deployblocker label.

**Comment by chiragsalian** [comment] 2023-09-28 17:41
Also i tested on production to compare.
> The first verification step fails

What is the first verification? Once i came online everything seemed to look fine for me. In terms of API i just see `CreateDistanceRequest` and that succeeds just fine for me once i got back online.
![image](https://github.com/Expensify/App/assets/14356145/08e3c787-0343-4b1f-ad77-571892361713)

The 3 loading report actions on the top look odd to me but other than that everything seems to look fine.

**Comment by paultsimura** [comment] 2023-09-28 21:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Distance request created offline is not treated as a distance request, but as manual.

### What is the root cause of that problem?
The reason for this is that we define the MoneyRequest as Distance here:

https://github.com/Expensify/App/blob/71c6450ae653a35f0b7411a116a4a08fd844dbdf/src/components/ReportActionItem/MoneyRequestPreview.js#L166

We do it based on the `transaction.comment`, which on the optimistic phase contains only request description and waypoints:

https://github.com/Expensify/App/blob/ad21933c05ab73283874e81d3c84cbdda4c79d1f/src/libs/TransactionUtils.js#L326-L330

### What changes do you think we should make in order to solve the problem?
We should determine if the transaction is a distance request based on the waypoints presence, not on `comment.type` (I have made it an early return because I didn't have enough time to check if we can fully replace the logic here or we should just use the early return):

```diff
function isDistanceRequest(transaction) {
+    if (hasWaypoints(transaction)) {
+        return true;
+    }

    const type = lodashGet(transaction, 'comment.type');
    const customUnitName = lodashGet(transaction, 'comment.customUnit.name');
    return type === CONST.TRANSACTION.TYPE.CUSTOM_UNIT && customUnitName === CONST.CUSTOM_UNITS.NAME_DISTANCE;
}
```

#### Result:

https://github.com/Expensify/App/assets/12595293/318f4d6a-3999-47b6-8f37-f25c1a04a12b


### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment] 2023-09-29 07:10
> Why is this issue a deploy blocker. Please add context when applying the label. From what i see the issue here occurs in production so there is no reason this should be a blocker.

@chiragsalian I made it a deploy blocker because the problem occurred on staging but not on production when I tested. Is that the context I should add when applying the label? Should I also justify the severity of the issue?

> Additionally, remember to handle deploy blockers in an hourly manner (or at least finish them within a day), this issue has been a blocker for 2 days now.

I did, in fact I put up a fix very quickly. I'm keeping this issue open because I'm also using it to fix the rest of offline distance requests. In the future I'll make a separate issue for the deploy blocker.

Sorry for forgetting to CP the fix.

**Comment by neil-marcellini** [comment] 2023-09-29 07:13
> What is the first verification? Once i came online everything seemed to look fine for me.

The steps for the deploy blocker are this, the first verification is step 4.
1. Go offline
2. Click the green plus, request money, distance
3. Enter a valid address for start and finish waypoints
4. Verify that you can click next

That is now fixed and steps 10 and 12 remain as problems.

**Comment by neil-marcellini** [comment] 2023-09-29 07:21
@paultsimura your [proposal](https://github.com/Expensify/App/issues/28289#issuecomment-1740018476) looks good and solves some of the problems. I realized that I already fixed this in another [draft PR](https://github.com/Expensify/App/pull/27204). Sorry about that.

Maybe you could check out that branch and see what the next root problems are following the test steps in the description? Or we can put the issue on HOLD for later.

**Comment by paultsimura** [comment] 2023-09-29 08:19
Hey @neil-marcellini, sure. I have found another bug with this offline flow. Should I write it here along with the proposal, or should we go the long way reporting it through slack?

**Comment by neil-marcellini** [comment] 2023-10-02 22:18
> Hey @neil-marcellini, sure. I have found another bug with this offline flow. Should I write it here along with the proposal, or should we go the long way reporting it through slack?

Yeah let's handle it here as long as it's relatively simple to reproduce in the offline flow.

**Comment by paultsimura** [comment] 2023-10-02 22:33
@neil-marcellini while waiting for the response here, I reported this as a separate bug: https://github.com/Expensify/App/issues/28554

**Comment by neil-marcellini** [comment] 2023-10-02 22:35
Ah ok that's alright. Please post your proposal for this one.

**Comment by paultsimura** [comment] 2023-10-02 22:42
> Ah ok that's alright. Please post your proposal for this one.

Is there anything specific left in this issue taking into account your first hot fix + your draft PR fix?

**Comment by neil-marcellini** [comment] 2023-10-05 21:18
There's a few points, but I think I'll just lump them in with the eReceipt PR.

**Comment by sakluger** [comment] 2023-10-12 06:46
Hey @neil-marcellini, I'm a little confused, who do we need to pay for this issue and how much? It looks like you reported and fixed the bug, do I just need to pay @mollfpr for reviewing the [PR](https://github.com/Expensify/App/pull/27204)?

**Comment by peterdbarkerUK** [comment] 2023-10-13 12:25
Hey @neil-marcellini - is [this](https://github.com/Expensify/App/issues/29535) a regression or a separate issue?

**Comment by neil-marcellini** [comment] 2023-10-13 16:01
> Hey @neil-marcellini, I'm a little confused, who do we need to pay for this issue and how much? It looks like you reported and fixed the bug, do I just need to pay @mollfpr for reviewing the [PR](https://github.com/Expensify/App/pull/27204)?

Yeah only C+ PR review payment is needed. @mollfpr did a good amount of review, but then was unresponsive so I had @mananjadhav finish it off. Maybe then can agree to split the payment? Or we pay @mananjadhav the full amount since he ultimately helped me to GSD.

**Comment by neil-marcellini** [comment] 2023-10-13 16:03
> Hey @neil-marcellini - is [this](https://github.com/Expensify/App/issues/29535) a regression or a separate issue?

Thanks for bringing it to my attention. I commented and closed it as a duplicate.

**Comment by sakluger** [comment] 2023-10-13 17:45
Thanks @neil-marcellini. Ideally you shouldn't need to bump, but it can help - since you didn't bump @mollfpr anywhere to finish reviewing, I think it's fair to split the $500 between the two reviewers. @mollfpr @mananjadhav does that sounds fair two you two?

**Comment by mananjadhav** [comment] 2023-10-13 18:04
It was an exception and @mollfpr did post an update [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1697033737404859) about their unavailability. I think am okay with the split here.

**Comment by sakluger** [comment] 2023-10-16 17:44
Okay, thanks @mananjadhav for the context. Both @mananjadhav and @mollfpr are eligible for payment via Manual Request, I'll post the payout summary below. Can you each let me know once you've completed the manual request so I can close the GH issue? Thanks!

**Summarizing payouts for this issue:**

Contributor+: @mananjadhav $250 (payable via Manual Request)
Contributor+: @mollfpr $250 (payable via Manual Request)

The overall $500 payment is being split between the two reviewers.

**Comment by JmillsExpensify** [comment] 2023-10-16 18:43
$250 payment approved for @mananjadhav based on summary above.

**Comment by JmillsExpensify** [comment] 2023-10-17 21:15
$250 payment approved for @mollfpr based on BZ summary.

**Comment by sakluger** [comment] 2023-10-23 20:01
All payments have been approved, closing the issue 👍

**Closed by sakluger** 2023-10-23 20:01 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
