### ISSUE TITLE
Web - Image zoom not working as expected after a page reload for extra long images - reported by @aswin-s

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8606] opened 2022-04-12 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Upload an extra long image like [this one](https://user-images.githubusercontent.com/7823358/132546765-0e41feb9-a06f-49c4-b3ba-2d52e96f87ae.jpg).
2. Wait for upload to finish.
3. Open the image by clicking on image preview in chat.
4. Zoom in on the image and check the zoom level. Image zooms properly and text is legible.
5. Now reload the app and navigate to same chat.
6. Tap on image attachment preview and try to zoom in.

## Expected Result:
Image zoom to behave exactly the same even after a page reload.

## Actual Result:
Image doesn’t zoom properly like it initially did. Unable to read the text as image doesn’t zoom in completely.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/162962633-d1f35673-f009-41b8-9044-e7247bc0f405.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aswin-s 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648545149732589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aswin-s** [comment] 2022-04-18 06:32
Reason:

This is due to a race condition due to the order in which `Image.getSize` and `onContainerLayoutChanged` gets invoked in `ImageView` component.


If image is cached already, Image.getSize callback gets called before `onContainerLayoutChangedEvent`

**Comment by mateocole** [comment] 2022-04-19 13:26
It looks like this issue is a duplicate of the mentioned issue in progress

**Closed** 2022-04-19 13:28 UTC
Labels: Weekly

**Comment by aswin-s** [comment] 2022-04-20 16:53
@mateocole mentioned issue is different one from the one reported above. I had mentioned this issue in the other thread just to point out that it would also impacting testing. I think this needs to be treated separately.
