### ISSUE TITLE
Conversation - There is a delay between user's conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34269] opened 2024-01-10 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log into Expensify on the main testing device as account A - On Incognito tab log in to another account B
2. From Account B send several message to Account A

## Expected Result:
The messages are received in real time

## Actual Result:
There is a big delay between user's conversation, message are not received in real time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f4cecc5c-3f35-4260-87fd-fbcfa717744c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment] 2024-01-10 19:27
Part of the issue seems to be that the chat is not scrolling on new messages, that is being handled in another issue, but the messages are slow, I am investigating.

**Comment by situchan** [comment] 2024-01-10 19:40
I am not able to reproduce "delay". Is it constantly reproducible?

**Comment by rlinoz** [comment] 2024-01-10 20:05
I think so, to the point where sometimes I don't get the message, although I don't think it is a frontend issue.

I will ask for a third person to reproduce to be sure.

**Comment by situchan** [comment] 2024-01-10 20:06
#34244 reached staging so this can be easily tested without needing to scroll manually

**Comment by rlinoz** [comment] 2024-01-10 20:25
It is not happening with new accounts though

**Comment by rlinoz** [comment] 2024-01-10 21:38
Asked for some help [here](https://expensify.slack.com/archives/C03TQ48KC/p1704921901446299)

**Comment by thienlnam** [comment] 2024-01-11 04:26
Removing the blocker - seems like they may be faster in production and it's a BE fix

**Comment by rlinoz** [comment] 2024-01-15 12:50
We already deployed App, Web-E and Auth since this issue was opened and prod is still working fast and reliably, so I am going to close this one.

**Closed by rlinoz** 2024-01-15 12:50 UTC
Labels: Engineering, Daily, Overdue, Bug
