### ISSUE TITLE
Web - Task - Confirmation page not skipped for assign task flow when accessed from QAB

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40719] opened 2024-04-22 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39413

## Action Performed:
Precondition: User A has created task skipping the assignee field. User has selected share somewhere option
1. Navigate to staging ND site
2. Tap FAB button
3. Select shortcut assign task
4. Enter task title & description

## Expected Result:
Assign Task flow skips the confirmation page when task flow accessed from QAB

## Actual Result:
Confirmation page not skipped for assign task flow when accessed from QAB

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fc5b2d76-eff2-499d-939f-babcc755297f

![image](https://github.com/Expensify/App/assets/93399543/1a421383-7cd5-40f0-bbff-adf76a3f16c3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-04-22 19:42
We think that this bug might be related to #vip-vsb

**Comment by chiragsalian** [comment] 2024-04-22 19:56
Not really a blocker. Looks like https://github.com/Expensify/App/pull/39413 is not working as expected and doesn't feel blocker worthy imo. Removing blocker label and reassigning issue to @Gonals since it's an issue with his PR. Feel free to let me know if you need any assistance with this.

**Comment by c3024** [comment] 2024-04-23 03:21
I think this is expected behaviour. Only when both assignee and share destination are selected does the QAB skip confirmation for tasks. In this case only share destination is selected.

**Comment by Gonals** [comment] 2024-04-23 10:16
>I think this is expected behaviour. Only when both assignee and share destination are selected does the QAB skip confirmation for tasks. In this case only share destination is selected.

Yep. I think that's fine for now. We can revisit this behavior down the line 🤷

**Closed by Gonals** 2024-04-23 10:16 UTC
Labels: Engineering, Daily
