### ISSUE TITLE
[$250] Android-Room-After creating room, entering @ not showing contact suggestions

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42766] opened 2024-05-29 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4585586
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab -- start chat
3. Create a new room
4. Enter @ and wait few seconds
5. Navigate to LHN
6. Navigate to room again
7. Keep cursor after @

## Expected Result:
After creating room, entering @ must show contact suggestions

## Actual Result:
After creating room, entering @ not showing contact suggestions but shown on revisit.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/73cbaa42-be63-4c4e-a7d3-51d38cba2924

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d65d15eadf82bb4</li>
        <li>Upwork Job ID: 1795831001903484928</li>
        <li>Last Price Increase: 2024-05-29</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102529959</li>
<li>ishpaul777 | Contributor | 102529960</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by m-natarajan** [comment] 2024-05-29 14:40
FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-29 14:41
We think that this bug might be related to #vip-vsb

**Comment by bondydaa** [comment] 2024-05-29 19:40
hmm the site has been pretty slow most of the day, if this relies on a network request that could explain it. or is it pretty consistent that first time `@` is type nothing is triggered?

**Comment by bondydaa** [comment] 2024-05-29 20:10
hmm okay was able to reproduce on android only. it doesn't look like you have to create a new room. i'm able to consistently reproduce by just going into any existing room and trying typing `@`. if i leave and go back into the same room then `@` triggers the list of members to show up.

**Comment by bondydaa** [comment] 2024-05-29 20:31
i think the code for this is roughly these components https://github.com/Expensify/App/blob/1490cecd7e099fe41052b2b8d4463ec94eb036ec/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L433

https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/Suggestions.tsx

I don't really see any recent changes in those files though.

There are these 2 PRs that had changes to the `ReportActionCompose.tsx` component but neither stand out to me as the root cause

https://github.com/Expensify/App/pull/42180
https://github.com/Expensify/App/pull/42615

**Comment by kbecciv** [comment] 2024-05-30 19:41
Issue is no longer reproduced after revert https://github.com/Expensify/App/pull/42843.

https://github.com/Expensify/App/assets/93399543/4949f773-0e5d-4e3e-8f19-ba3b4c3d715e

**Comment by bondydaa** [comment] 2024-05-30 21:00
@jliexpensify going to assign to you to double check and make sure payments are sorted. 

I think we only really need to pay @ishpaul777 here, @alitoshmatov wasn't online so didn't get a chance to really dive in and review anything. @puneetlath and @ishpaul777 basically worked through everything ❤️

**Comment by jliexpensify** [comment] 2024-05-30 22:03
Thanks for the heads up! In that case, lets unassign @alitoshmatov from this issue.

**Payment Summary**

- C+: @ishpaul777 $250

[Upwork job](https://www.upwork.com/jobs/~016d65d15eadf82bb4)

**Comment by jliexpensify** [comment] 2024-06-04 05:31
Hmm not overdue, right? Waiting for it to be deployed?

**Comment by fabOnReact** [comment] 2024-06-05 03:13
Can I apply for this job? Thanks

**Comment by tomekzaw** [comment] 2024-06-05 08:37
There were no Android-specific changes between `react-native-live-markdown@0.1.70` and `0.1.76` so I have no idea what could have caused this regression.

**Comment by fabOnReact** [comment] 2024-06-06 05:37
I quote Skalakid [comment](https://github.com/Expensify/App/issues/42755#issuecomment-2137438195).

>After a quick investigation I found out that the live markdown parser is using a different commit of expensify-common than E/App. 

>After a quick investigation I found out that the live markdown parser is using a different commit of expensify-common than E/App. Live Markdown parser uses a newer version of ExpeniMark that contains changes that block blockquote creation without space after 

>I will create PR that bumps the version in the Expensify App
>I pulled the latest main and E/App has a newer version of expensify-common than live markdown. I can't reproduce this issue now

Maybe with the latest version of expensify-common and react-native-live-markdown the issue will not reproduce anymore. I will verify this on Monday (unluckily now I have other commitments). Thanks

**Comment by bondydaa** [comment] 2024-06-10 15:20
Thanks @tomekzaw and @fabOnReact let me know if you need anything from me.

**Comment by fabOnReact** [comment] 2024-06-11 04:01
I tested and I can not reproduce this issue anymore. 

<video src="https://github.com/Expensify/App/assets/24992535/fe55416a-a9ba-4ac8-856d-74f37296bb2f" width="1000" />

**Comment by jliexpensify** [comment] 2024-06-12 00:11
There wasn't an actual regression here right? Also, what's the original PR? Melvin hasn't updated the date so just want to check everything has been deployed.

**Comment by jliexpensify** [comment] 2024-06-12 23:32
PR - https://github.com/Expensify/App/pull/42843 

Will pay out today, confirmed with Bondy no checklist needed.

**Comment by jliexpensify** [comment] 2024-06-13 02:06
Paid and job closed.

**Closed by jliexpensify** 2024-06-13 02:06 UTC
Labels: External, Engineering, Daily, Bug
