### ISSUE TITLE
[$500] Deeplinks - Previous chat opens when click on chat deeplink and sign out & sign in to app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31150] opened 2023-11-09 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open app
2. Navigate to any conversation
3. Send the deeplink message "[https://staging.new.expensify.com/concierge"](https://staging.new.expensify.com/concierge%22)
to the conversation
4. Click on the deeplink in the conversation
5. Clcik on Profile icon in LHN
6. Click on Sign Out
7. Sign In with the same account

## Expected Result:
The last opened conversation within deeplink should be displayed when Sign In with the same account

## Actual Result:
The previous opened conversation displays

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f072b3ed-5721-4d06-93ee-a452ea22df4c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114ab65213ca44cff</li>
        <li>Upwork Job ID: 1722677810558033920</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-09 18:12
Same RCA with https://github.com/Expensify/App/issues/30868

**Comment by jliexpensify** [comment] 2023-11-14 03:50
@eVoloshchak should we pop this on hold as per [this comment](https://github.com/Expensify/App/issues/31150#issuecomment-1804320340)?

**Comment by jliexpensify** [comment] 2023-11-17 00:32
Bump @eVoloshchak

**Comment by jliexpensify** [comment] 2023-11-20 00:06
Bumped @eVoloshchak on Slack [to confirm this](https://github.com/Expensify/App/issues/31150#issuecomment-1804320340)

**Comment by eVoloshchak** [comment] 2023-11-21 18:06
Tested @DylanDylann's draft [PR](https://github.com/Expensify/App/pull/31424) for https://github.com/Expensify/App/issues/30868, but our issue still persists 

The "Clicking on a deeplink" part isn't relevant to the issue, you can still reproduce it by simply signing Out and then back In, so the issues are similar (but aren't resolved by the same fix)

**Comment by DylanDylann** [comment] 2023-11-21 19:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Deeplinks - Previous chat opens when click on chat deeplink and sign out & sign in to app

### What is the root cause of that problem?
- When launching the app with the deeplink that does not contain reportID, we use the ```getLastAccessedReportID``` to get the report to display.
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.js#L63-L72
- In the above, the ```findLastAccessedReport``` is not working properly. 
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/libs/ReportUtils.js#L575-L581
- ```findLastAccessedReport``` uses ```sortReportsByLastRead```:
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/libs/ReportUtils.js#L263-L269 that will sort the reports by "lastReadTime". This is incorrect because the "lastReadTime" refers to the latest time the user read a new message, not the latest time the user visits a report. For example, if we read a new message A on 3/10/2023, and re-visit its report on 4/10/2023, the "lastReadTime" is still '3/10/2023'.

### What changes do you think we should make in order to solve the problem?
- We can create the ONYXKEYS.LAST_ACCESSED_REPORT_ID_BEFORE_LOGOUT to store the reportID that user opened before logging-out
- Then, once we signout, set the ONYXKEYS.LAST_ACCESSED_REPORT_ID_BEFORE_LOGOUT to the current reportID
- Then, update:
https://github.com/Expensify/App/blob/c6f922947f3c3ea283130d21addd15ed8ac660ec/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.js#L63
to:
```
const getLastAccessedReportID = (reports, ignoreDefaultRooms, policies, isFirstTimeNewExpensifyUser, openOnAdminRoom, reportIDBeforeLogout) => {
    if (reportIDBeforeLogout) {
        Onyx.merge(ONYXKEYS.REPORT_ID_BEFORE_LOGOUT, null);
        return reportIDBeforeLogout;
    }
...
```
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment] 2023-11-22 01:10
@eVoloshchak just updated my [proposal](https://github.com/Expensify/App/issues/31150#issuecomment-1821510491) in **What alternative solutions did you explore? (Optional)**, please help check

**Comment by eVoloshchak** [comment] 2023-11-27 12:00
@DylanDylann, since we only store `lastVisitedTime` locally, [this](https://github.com/Expensify/App/issues/31150#issuecomment-1821510491) would still work incorrectly across devices


1. Navigate to any conversation on **device A**
2. Send the deeplink message "[https://staging.new.expensify.com/concierge"](https://staging.new.expensify.com/concierge%22)
3. to the conversation
4. Click on the deeplink in the conversation
5. Open the app on **device B**
6. Notice another conversation is displayed

Can we store `lastVisitedTime` on the back end so we show the correct report on startup across devices/apps?

**Comment by DylanDylann** [comment] 2023-11-27 12:05
@eVoloshchak But it will have an issue in offline mode. And also should we consider the case "accross devices" that you mentioned?  There are a lot of issues related to the "refresh page" action and we are not considering the "across devices" case, for example https://github.com/Expensify/App/issues/31628

**Comment by jliexpensify** [comment] 2023-11-30 05:42
Bump @eVoloshchak please continue the convo!

**Comment by jliexpensify** [comment] 2023-11-30 23:46
Have bumped Eugene via Slack

**Comment by jliexpensify** [comment] 2023-12-05 04:35
Hey @eVoloshchak - I've bumped you in Slack but haven't heard back. Can you review the proposals in the next 48 hours? Otherwise, I will re-assign to another C+, thanks.

**Comment by jliexpensify** [comment] 2023-12-07 23:35
Hi @aimane-chnaif - hoping you can help us with this issue? Haven't heard from Eugene in a while so re-assigning.

Thanks!

**Comment by aldo-expensify** [comment] 2023-12-12 15:31
> I'd like to confirm with engineer if last opened report should open upon login across devices

I'm not really sure, I think its better to ask this in `#epensify-open-source`

**Comment by aldo-expensify** [comment] 2023-12-15 13:42
Asking here: https://expensify.slack.com/archives/C01GTK53T8Q/p1702647751622789

**Comment by jliexpensify** [comment] 2023-12-18 00:00
Thanks @aldo-expensify , have re-bumped so it doesn't get lost.

**Comment by aldo-expensify** [comment] 2023-12-18 14:33
Should we hold on https://github.com/Expensify/App/pull/31424 / https://github.com/Expensify/App/issues/30868 ?

**Comment by jliexpensify** [comment] 2023-12-28 04:28
Still on hold

**Comment by aldo-expensify** [comment] 2024-01-08 15:50
https://github.com/Expensify/App/pull/31424 reached production. I think it is time to UNHOLD and reevaluate what we have to do here.

**Comment by aldo-expensify** [comment] 2024-01-08 15:51
@lanitochka17 can you retest this and confirm if this is still an issue? 🙏

**Comment by aldo-expensify** [comment] 2024-01-08 21:08
Thanks @lanitochka17 !

I'll close this then. Feel free to reopen if someone manages to reproduce.

**Closed by aldo-expensify** 2024-01-08 21:08 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
