### ISSUE TITLE
[HOLD for payment 2022-11-16] [$250] Web - LHN - The modal key combination doubles when the window is resized

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12116] opened 2022-10-25 13:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12071

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click CTRL + I
4. Resize the window to a minimum

## Expected Result:
The modal key combination should not be duplicated

## Actual Result:
The modal key combination doubles when the window is resized

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.19.1

**Reproducible in staging?:** Yes

**Reproducible in production?:**  Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (16)](https://user-images.githubusercontent.com/93399543/197784541-b827eb6b-a072-4934-9ba0-869c4c501f00.png)
![image (15)](https://user-images.githubusercontent.com/93399543/197784543-30758162-b90c-4e77-a8b1-41dfd9ecffea.png)
![image (14)](https://user-images.githubusercontent.com/93399543/197784547-ec509218-430e-4ad8-a122-12e218677a06.png)

https://user-images.githubusercontent.com/93399543/197784805-b85f4839-ebe9-4990-8b9a-a4872ce22876.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment] 2022-10-25 16:11
I can reproduce this, and its can be external

**Comment by conorpendergrast** [comment] 2022-10-26 00:20
Internal job posting: https://www.upwork.com/ab/applicants/1585063293084028928/job-details
External job posting: https://www.upwork.com/jobs/~01d214c4cbd14da163

**Comment by hungvu193** [comment] 2022-10-26 04:18
<b>Proposal</b>
We need to check if current modal is already showed then decide to show the shortcut modal or not instead of showing it everytime.

<b>Solution</b>
Add the condition inside: `KeyboardShortcutsModal`: `componentDidMount` function:
```diff
componentDidMount() {
        const shortcutConfig = CONST.KEYBOARD_SHORTCUTS.SHORTCUT_MODAL;
        this.unsubscribeShortcutModal = KeyboardShortcut.subscribe(shortcutConfig.shortcutKey, () => {
-            KeyboardShortcutsActions.showKeyboardShortcutModal();
+            if (!this.props.isShortcutsModalOpen) {
+                KeyboardShortcutsActions.showKeyboardShortcutModal();
+           }
        }, shortcutConfig.descriptionKey, shortcutConfig.modifiers, true);
    }
```

https://user-images.githubusercontent.com/16502320/197933389-93f89136-cbd0-4be9-a6d2-429604116edf.mov

**Comment by conorpendergrast** [comment] 2022-10-27 03:36
@parasharrajat Over to you to review proposals!

**Comment by parasharrajat** [comment] 2022-10-27 17:01
Checking it.

**Comment by parasharrajat** [comment] 2022-10-28 14:42
Didn't get the time yesterday for it. It looks like a regression to me. Let me check that before checking the proposal.

**Comment by parasharrajat** [comment] 2022-10-31 12:54
I can't reproduce the issue. cc: @Expensify/applause

**Comment by hungvu193** [comment] 2022-10-31 13:00
> ~I can't reproduce the issue~. I can now. There is one step missing from reproduction.

you can try to use safari browser.

**Comment by parasharrajat** [comment] 2022-10-31 13:04
@0xmiroslav's proposal looks good to me. It is more optimized to move the whole `KeyboardShortcutsModal` to the Sidebar. Technically it adds extra rendering cost in ScreenWrapper as ScreenWrapper will be present on each screen. 

But @0xmiroslav your first PR is still in progress. Let's wait for that to be completed before you work on this (our policy). I will review that today.

cc: @luacmartins 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by luacmartins** [comment] 2022-10-31 15:18
Sounds good. @0xmiroslav please ping me once your other [PR](https://github.com/Expensify/App/pull/12098) has been merged so I can assign you to this issue.

**Comment by luacmartins** [comment] 2022-11-02 15:31
Still waiting on @0xmiroslav's [PR](https://github.com/Expensify/App/pull/12098) to be merged to assign them to this issue.

**Comment by luacmartins** [comment] 2022-11-03 17:24
@0xmiroslav's PR is merged. Assigning @0xmiroslav to implement [this proposal](https://github.com/Expensify/App/issues/12116#issuecomment-1291548767)

**Comment by conorpendergrast** [comment] 2022-11-07 04:27
Hired via Upwork: 

- [ ] @0xmiroslav (Contributor fixing the issue)
- [ ] @parasharrajat (Contributor+)

**Comment by luacmartins** [comment] 2022-11-07 14:10
@0xmiroslav im still around until Wednesday. Let’s try to get this merged before then!

**Comment by conorpendergrast** [comment] 2022-11-17 04:26
Today is the day. It's time to follow [these steps](https://stackoverflow.com/c/expensify/questions/7582).

This is the job:

- Internal job posting: https://www.upwork.com/ab/applicants/1585063293084028928/job-details
- External job posting: https://www.upwork.com/jobs/~01d214c4cbd14da163

I am paying: 
- [ ] @0xmiroslav (Contributor fixing the issue)
- [ ] @parasharrajat (Contributor+)

```
Important: Payment amounts are variable, dependent on when the PR was merged. Payment timeline all based on the day the contributor has an accepted proposal and is assigned to the Github issue
- Merged PR within 3 business days - 50% bonus
- Merged PR within 6 business days - 0% bonus
- Merged PR within 9 business days - 50% penalty
- No PR within 12 business days - Contract terminated

After you've reviewed the PR and issued payment, comment on the GH issue and include any bonuses or penalties and the total amount paid.
(the above was added on 2022-11-4, post in #bug-zero if you have questions)
```

Assignment happened on 2022-11-04, and the PR merged on 2022-11-08. With the weekend, that's within 3 business days. So, it's a 50% bonus. 

Paying $250.00 + 50% = $375 each. I'll do that tonight

**Comment by conorpendergrast** [comment] 2022-11-17 07:19
Contributors have been paid, contracts have been ended and job post has been removed. We're all done!

**Closed by conorpendergrast** 2022-11-17 07:19 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment
