### ISSUE TITLE
[$1000] Web - After leaving a room, I cannot find it again or create a room with the same name in the same workspace.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23866] opened 2023-07-29 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As the workspace creator, I made the room called #how-to-build-a-startup-within-a-startup-with-navan
2. I tried to input a whisper message and accidentally clicked “Leave Room”
3. I tried to find it in my search and cannot, and I cannot recreate a room with the same name in the same workspace.

## Expected Result:
 Be able to find the already created room or be able to recreate one using the same name. The fact I can’t do the latter makes me believe that the room was actually created since our system.

## Actual Result:
I cannot recreate the room or find it in my search history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (8)](https://github.com/Expensify/App/assets/93399543/8977cf92-d966-4af8-8dd0-4fc99e3eae22)

![image (7)](https://github.com/Expensify/App/assets/93399543/c3112df4-e5db-4517-99da-208f09f015bf)

![image (6)](https://github.com/Expensify/App/assets/93399543/343c641e-94cd-4fe8-90e6-a2ec11249e43)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @RobertLadue 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690572447528809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117599bc7b2a3f78b</li>
        <li>Upwork Job ID: 1685865890032615424</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-08-01 01:47
@robertKozik do you agree this is a back end/internal issue?

**Comment by robertKozik** [comment] 2023-08-01 08:01
@kadiealexander  I believe that it is indeed internal, but let me to double check that first

**Comment by robertKozik** [comment] 2023-08-01 10:17
Yes, I agree that this should be internal. Per @akamefi202's comment, and @c3024's root cause, the problem is probably located on the backend. When a user leaves a room, it cannot be searched by this user as the room is closed. On the other hand, the room cannot be recreated as the room with this name already exists - it's closed, not removed.

The @c3024 proposal is valuable, but it doesn't resolve the problem; it only removes the possibility of accidentally leaving the room, which is a good solution, but it's not in compliance with the expected behavior.

**Comment by RobertLadue** [comment] 2023-08-02 16:00
Was the room marked as closed because I was the only person in the room or is this action taken anytime someone leaves a room regardless of how many people are in it?

Feels weird that we would design it, so that anytime you left a room someone needs to re-link you back in to find it again.

**Comment by RobertLadue** [comment] 2023-08-02 16:57
@kadiealexander what's the process to get this back to our internal team? SaaStr is going to begin promoting the sessions and we are going to do speaker outreach starting early next week, so it'd be great if all the rooms worked 😅 

Only happened to two rooms luckily!

**Comment by amyevans** [comment] 2023-08-03 19:01
I believe the ability to search for rooms in your workspace that you are not apart of is polish coming in the UCR project (cc @MitchExpensify to confirm)

Were these public rooms @RobertLadue? If so, I think we can just find the report IDs (from logs or db query) and you can rejoin them via direct URL, and you'll be back in biz (I confirmed locally that this works).

And `#how-to-build-a-startup-within-a-startup-with-navan` was the name of one of the rooms, what was the other one you accidentally left?

**Comment by amyevans** [comment] 2023-08-03 19:29
Chatted through the rest with Bob in NewDot, we're all set here!

**Closed by amyevans** 2023-08-03 19:29 UTC
Labels: Engineering, Daily, Internal, Bug
