### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Auto suggestions for emoji is not sorted alphabetically

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50079] opened 2024-10-02 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727863255553599

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any DM
3. Type :disap in the compose box for emoji suggestions
## Expected Result:
Suggestions displayed are sorted alphabetically
## Actual Result:
Suggestions displayed are not sorted alphabetically
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (11)](https://github.com/user-attachments/assets/b08dbe63-c50e-4d34-9ad6-cdd38b205f23)

![Screenshot 2024-10-02 120356](https://github.com/user-attachments/assets/313c325c-f1bb-41d7-8021-3eb2ca93f08d)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841781443095645269</li>
        <li>Upwork Job ID: 1841781443095645269</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104528548</li>
<li>nkdengineer | Contributor | 104528551</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by nkdengineer** [comment] 2024-10-02 19:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Suggestions displayed are not sorted alphabetically

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/src/libs/EmojiUtils.ts#L423


[Here](https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/src/libs/EmojiUtils.ts#L423) we are calculating `nodes` based on the `text` entered by the user and the `keywords` defined in this [file](https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/assets/emojis/en.ts)



<img width="452" alt="Screenshot 2024-10-03 at 02 21 01" src="https://github.com/user-attachments/assets/67365b3c-7b5b-4161-8b09-426425dae445">

The reason when we enter `:dis` the 2 icons "melting_face" and "dotted_line_face" are displayed first is because they have the keyword "disappear" [here](https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/assets/emojis/en.ts#L108) and [here](https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/assets/emojis/en.ts#L120)

### What changes do you think we should make in order to solve the problem?


Since the `suggestEmojis` function is used in many other places, we should return the match sorted by the emoji name in this function [suggestEmojis](https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/src/libs/EmojiUtils.ts#L408)  

https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/src/libs/EmojiUtils.ts#L408

```
    return lodashSortBy(matching, (emoji) => !emoji.name.includes(emojiData[0].toLowerCase().slice(1)));
```

### What alternative solutions did you explore? (Optional)


https://github.com/user-attachments/assets/937de3b9-1ac2-45db-a734-5be850ac3e70

**Comment by suneox** [comment] 2024-10-03 16:03
@nkdengineer Your RCA is correct and detailed, but could you please double-check your implementation? When searching with only 2 characters, the result is incorrect 

https://github.com/user-attachments/assets/53fea1e5-fed1-46ed-bf80-bac137987d81

**Comment by nkdengineer** [comment] 2024-10-04 03:12
@suneox sorry for not being more clear in the proposal, I guess you missed update `matching` in [here](https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/src/libs/EmojiUtils.ts#L427) and [here](https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/src/libs/EmojiUtils.ts#L437)

Please check again

**Comment by suneox** [comment] 2024-10-04 15:13
> The expected behavior is Slack's behavior, which I think you are referencing as `prioritize those that more closely match the text.` @suneox

@flodnv Yes, that is the expected behavior I want to confirm, as the current expected behavior is confusing when compared to Slack’s behavior

Based on the expected behavior, we can proceed with @nkdengineer [proposal](https://github.com/Expensify/App/issues/50079#issuecomment-2389542612)

🎀 👀 🎀 C+ reviewed

**Comment by srikarparsi** [comment] 2024-10-04 20:17
Hi @hannojg! I saw [here](https://expensify.slack.com/archives/C049HHMV9SM/p1727868993992559?thread_ts=1727863255.553599&cid=C049HHMV9SM) that you were thinking about applying some findings with the recent search algorithm to emoji recommendations. Do you think you could provide a little more detail about that before we go through with the above [proposal](https://github.com/Expensify/App/issues/50079#issuecomment-2389542612)? It would definitely work but I'm not sure if there's a more performant way to do this.

**Comment by suneox** [comment] 2024-10-07 18:50
We’re still waiting for internal feedback about the order logic. The current selected [proposal](https://github.com/Expensify/App/issues/50079#issuecomment-2389542612) behaves like Slack, It only sorts by placing results that include the search text at the top.

https://github.com/user-attachments/assets/26c958f4-6d90-4665-9808-924f49e361af

**Comment by srikarparsi** [comment] 2024-10-11 18:40
Hey @hannojg! Friendly bump on this [message](https://github.com/Expensify/App/issues/50079#issuecomment-2394506239)

**Comment by adelekennedy** [comment] 2024-10-16 19:21
@hannojg bump again!

**Comment by nkdengineer** [comment] 2024-10-20 15:43
@hannojg please check this [comment](https://github.com/Expensify/App/issues/50079#issuecomment-2394506239) when you have a chance

**Comment by hannojg** [comment] 2024-10-21 06:31
Hey guys, sorry for being late to reply here!

The new suffix tree implementation which we'd like for the emoji search as well has just been merged, and I created a ticket for migrating it here:

- https://github.com/Expensify/App/issues/51148

For the new suffix tree implementation: the results are not guaranteed to be sorted / maintain the order they have been inserted in. So even with the suffix tree implementation we'd need to sort the results after the search.
So i think the suffix tree would still need any sorting mechanism as proposed here!

**Comment by srikarparsi** [comment] 2024-10-22 02:12
Sounds good, thanks @hannojg! We'll move forward with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/50079#issuecomment-2389542612)

**Comment by flodnv** [comment] 2024-11-14 14:57
What is the latest update here?

**Comment by adelekennedy** [comment] 2024-11-14 16:51
@suneox it looks like @srikarparsi left a comment on the PR a while ago that needs to addressed?

**Comment by suneox** [comment] 2024-11-14 23:49
> @suneox it looks like @srikarparsi left a comment on the PR a while ago that needs to addressed?

Yes, we’re still working on a PR to handle lost order in some use cases.

**Comment by srikarparsi** [comment] 2024-11-18 09:46
[PRs](https://github.com/Expensify/App/pull/51220#discussion_r1846180526) almost ready

**Comment by adelekennedy** [comment] 2024-11-30 22:03
Payouts due:

- [ ] Contributor: $250 @nkdengineer 
- [ ] Reviewer: $250 @suneox 

Upwork job is [here](https://www.upwork.com/nx/wm/offer/104528548).

**Closed** 2024-11-30 22:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
