### ISSUE TITLE
[Help Wanted] [$500] Web - Workspace - Infinite spinner is shown when new account creates a Free Plan

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31195] opened 2023-11-10 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to OD Expensify (with invalidated account)
2. Navigate to Settings -> Workspaces ->Group
3. Click Free plan
4. Verify new opened ND Expensify page

## Expected Result:
User is redirected to NewDot -> Workspace settings page

## Actual Result:
New Dot Expensify page is opened with infinite loading spinner and error shown in console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/176b1386-0b25-4e9c-97b4-7b63f557eb40

![Bug6271557_1699638639937!infinite_loading](https://github.com/Expensify/App/assets/78819774/b6782d28-9123-41df-89c6-65a4623e626c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01122d03775f699254</li>
        <li>Upwork Job ID: 1723040449741160448</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-11-13 20:44
I'm able to reproduce it and it's similar to [this](https://github.com/Expensify/App/issues/29372) issue.

<details>
<summary>MacOS: Firefox</summary>

https://github.com/Expensify/App/assets/56457735/4d888514-9c5a-4780-8816-14e4659d312a

</details>

The difference is that in this case, we don't have the desktop app installed hence this part of the code comes into play:
https://github.com/Expensify/App/blob/629c6de7f2d23e49b6ff6c460c7bf8f87f68b70a/src/libs/actions/App.ts#L507
which can be observed in the Networking tab as the `OpenOldDotLink` api call.

Given that in the video we can see the RHN of the workspace is opened initially then closed when the `OpenOldDotLink` is called which sets url to:

`
https://new.expensify.com/transition?accountID=16019534&email=kevin.bader96+8@gmail.com&shortLivedAuthToken={token}&exitTo=workspace/new&shouldForceLogin=false&ownerEmail=&makeMeAdmin=false&openOnAdminRoom=true
`

which causes the infinite spinner because the transition route is not properly handled by the navigator.

The problem is that compared to the web to desktop transition issue I mentioned, this one will be pretty much impossible to test externally given a proposal because it requires access to OldDot's repo in order to test a fix locally, therefore I think this should be handled internally.

**Comment by strepanier03** [comment] 2023-11-14 00:54
@allroundexperts - Do you agree this should be handled [internally](https://github.com/Expensify/App/issues/31195#issuecomment-1809072792)? I can update the labels if so.

**Comment by strepanier03** [comment] 2023-11-21 00:12
Bump @allroundexperts https://github.com/Expensify/App/issues/31195#issuecomment-1809370485

**Comment by allroundexperts** [comment] 2023-11-26 22:13
@strepanier03 I think this should be handled internally.

**Comment by strepanier03** [comment] 2023-11-27 19:58
Got it, thanks @allroundexperts - I've moved it internal and now we wait.

**Comment by strepanier03** [comment] 2023-12-04 22:32
We're good Melvin, waiting for someone to pick this up.

**Comment by strepanier03** [comment] 2023-12-04 22:33
All good Melvin, waiting for an internal team member to pick this up.

**Comment by strepanier03** [comment] 2023-12-07 17:30
Looking for internal volunteer still.

**Comment by strepanier03** [comment] 2023-12-11 17:22
Figured I'd give this another test and I think the issue here now is that to test this you need a private domain email as all new public email sign ups on Oldot redirect you to Newdot automatically now.

- Testing on public email = no reproduction - flow is now different
- Testing on private email = no reproduction - expected result happens

----

@allroundexperts - I can't repro this any longer and a change in the flow for public emails means you won't have an unvalidated account to test with either. 

Unless you can reproduce still, I would like to close this. What do you think?

**Comment by allroundexperts** [comment] 2023-12-11 23:56
Yes, I think we can close this @strepanier03!

**Closed** 2023-12-19 17:37 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Overdue, Bug
