### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] IOU - Workspace avatar shows 'U' avatar before reverting to actual avatar in IOU view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24325] opened 2023-08-09 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23043
## Action Performed:
1. Go to staging.new.expensify.com
2. Request money in a workspace chat
3. Click on the IOU preview
4. Click on the IOU again

## Expected Result:
The workspace avatar shows the correct avatar

## Actual Result:
The workspace avatar shows 'U' avatar before reverting to the actual avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.52.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8b6b330c-e8bf-44a5-a99c-8b70fedfa7c2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01698449a42b0e216c</li>
        <li>Upwork Job ID: 1689577432456220672</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26110136</li>
<li>StevenKKC | Contributor | 26110138</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-08-09 17:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace avatar shows 'U' avatar before reverting to actual avatar in IOU view.

### What is the root cause of that problem?
If we click IOU preview in the money request page, `onIOUPreviewPressed` is executed.
Since there is no child thread data in `Onyx`, app generates optimistic child thread data, and set the child thread's `policyID` to `CONST.POLICY.OWNER_EMAIL_FAKE`.
And then send `OpenReport` API to BE, and navigate to the child thread.
https://github.com/Expensify/App/blob/202f2ebbc52b8d8e41a26839807eaca5ea024568/src/components/ReportActionItem/MoneyRequestAction.js#L101-L121

Because the report's `policyID` is `CONST.POLICY.OWNER_EMAIL_FAKE`, `ReportUtils.getPolicyName` returns `Unavailable Workspace`, and then `ReportUtils.getWorkspaceAvatar` returns ` WorkspaceU`avatar.
So 'U' is shown in money request header.

After `OpenReport` API returns the thread report data, app showes the correct workspace avatar, since the thread has a corrrect `policyID`.

Therefore, workspace avatar shows 'U' avatar before reverting to actual avatar in IOU view.

### What changes do you think we should make in order to solve the problem?
We can set the optimistic child thread's `policyID` to correct value.
```js
    const thread = ReportUtils.buildOptimisticChatReport(
        participantAccountIDs,
        props.translate(ReportActionsUtils.isSentMoneyReportAction(props.action) ? 'iou.threadSentMoneyReportName' : 'iou.threadRequestReportName', {
            formattedAmount: ReportActionsUtils.getFormattedAmount(props.action),
            comment: props.action.originalMessage.comment,
        }),
        '',
-       CONST.POLICY.OWNER_EMAIL_FAKE,
+       lodashGet(props.iouReport, 'policyID', CONST.POLICY.OWNER_EMAIL_FAKE),
        CONST.POLICY.OWNER_ACCOUNT_ID_FAKE,
        false,
        '',
        undefined,
        undefined,
        CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS,
        props.action.reportActionID,
        props.requestReportID,
    );
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by kaomoua** [comment] 2023-08-10 11:51
Hi. I can not see the proposal of @situchan. But how was he assigned to this issue?
I am new here and I really don't know how to contribute to Expensify.

**Comment by kaomoua** [comment] 2023-08-10 11:52
Hi. I can not see the proposal of @situchan. But how was he assigned to this issue?
I am new here and I really don't know how to contribute to Expensify.

**Comment by kaomoua** [comment] 2023-08-10 12:50
@pradeepmdk You mean this issue is still available?

**Comment by situchan** [comment] 2023-08-10 12:51
@kaomoua as a new contributor, please review our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). As this GH has `Help Wanted` label, still open for proposals.

**Comment by kaomoua** [comment] 2023-08-10 12:53
https://github.com/Expensify/App/issues/16108
Could you please check this issue? I posted my proposal and can not see other ones.
But this issues was assigned to other developer.
What happened?

**Comment by StevenKKC** [comment] 2023-08-10 12:53
@situchan Thanks for your review. I have updated [my proposal](https://github.com/Expensify/App/issues/24325#issuecomment-1671871786).

**Comment by pradeepmdk** [comment] 2023-08-10 12:56
@kaomoua  only the `Help Wanted ` label we need to look that and check the guidelines [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). like this
![Screenshot 2023-08-10 at 6 26 06 PM](https://github.com/Expensify/App/assets/16595846/c928f7f6-0a08-486c-9c16-8321c0323f8b)

**Comment by situchan** [comment] 2023-08-10 12:57
@StevenKKC your root cause is correct. Does your solution work on paid IOU report as well?

**Comment by meedwire** [comment] 2023-08-10 13:11
Contributor details
Your Expensify account email: l.jeronimo12345@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/leonardos24

The bug seems to be a relatively simple issue. It appears to be a remnant of a previous state and is being caused by a delay in state updating. The state should be cleared during the transition, or the state update should be optimized so that the transition isn't noticeable. There are several ways to accomplish this, such as handling it within the click action itself, forcing the dismounting and remounting of the screen, or creating a new instance of the screen. With my in-depth understanding of these processes and strong technical abilities, I am well-equipped to tackle this issue, ensuring a seamless user experience.

**Comment by StevenKKC** [comment] 2023-08-10 13:11
@situchan I have tested on paid IOU report and works as well.

**Comment by situchan** [comment] 2023-08-14 05:16
@StevenKKC's [proposal](https://github.com/Expensify/App/issues/24325#issuecomment-1671871786) looks good to me. Fixing optimistic data is the only solution.
🎀 👀 🎀 C+ reviewed

**Comment by StevenKKC** [comment] 2023-08-14 19:39
@situchan PR https://github.com/Expensify/App/pull/24551 is ready for review.

**Comment by StevenKKC** [comment] 2023-08-30 09:50
@flaviadefaria Could you please process payment?

**Comment by situchan** [comment] 2023-08-30 10:07
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18760/files#r1310023010
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18760

This is minor UI bug and offline test is already in PR checklist. So no regression test is needed

**Comment by flaviadefaria** [comment] 2023-08-30 13:33
Thanks @situchan 
@StevenKKC I was OoO, will process payment now.

**Comment by flaviadefaria** [comment] 2023-08-30 13:35
Payment is as follow:
- No reporting bonus (bug reported by Applause)
- @StevenKKC = $1000 + $500 bonus = $1500 (UW)
- @situchan = $1000 + $500 bonus = $1500 (should request in ND)

**Comment by flaviadefaria** [comment] 2023-08-30 13:39
@StevenKKC has been paid. I'll switch this to weekly and close when @situchan has been paid.

**Comment by situchan** [comment] 2023-08-30 13:54
@flaviadefaria I am still using upwork. Already accepted offer made by Melvin - https://github.com/Expensify/App/issues/24325#issuecomment-1677113605

**Comment by flaviadefaria** [comment] 2023-09-01 12:29
@situchan I just paid you in UW. Closing this as completed.

**Closed by flaviadefaria** 2023-09-01 12:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
