### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Web - Login - Invisible text in Email field when logging out and selecting predictive option

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50460] opened 2024-10-08 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Log out of the account
3. Tap on the Email field on log in screen
4. Write one letter on it
5. Select the first available option tapping on notebook pad
6. Verify the selected Email is visible on the Email field

## Expected Result:
The selected Email, should be completely visible on the Email field on log in screen

## Actual Result:
After logging out, writing one letter on the Email field on log in screen and selecting any suggestion on the displayed list tapping on notebook pad, makes the text invisible on Email field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/3f1cca0b-520c-4ec3-b24d-b35594cdb32d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843820742054331617</li>
        <li>Upwork Job ID: 1843820742054331617</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104542745</li>
<li>klajdipaja | Contributor | 104542746</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment] 2024-10-08 18:34
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by naveen-bharathi** [comment] 2024-10-09 07:12
This can be fixed by adjusting/setting the -webkit-box-shadow property in the -webkit-autofill:active pseudo selector for the input. Additionally we can change the text color using the -webkit-text-fill-color property in the -webkit-autofill pseudo selector of the input element

**Comment by naveen-bharathi** [comment] 2024-10-09 07:15
Contributor details
Your Expensify account email: mail@naveenbharathi.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010081e698472127dc

**Comment by klajdipaja** [comment] 2024-10-09 09:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In sign in page the email from autofill is not visible in dark mode. 

NOTE: To reproduce this I had to set the Dark Mode on the expensify and then log out 
### What is the root cause of that problem?

Input filleds that are autofilled in dark mode have different styles that use the autofill selectors defined here in `DomUtils/index.ts#getAutofilledInputStyle`. In this styles we are overridinig the color of the input field from  `rgb(231, 236, 233);` to `#002E22` rendering the text invisible.

### What changes do you think we should make in order to solve the problem?
We need to remove this line in the styles:
https://github.com/Expensify/App/blob/933a865f9cefdda7927945b68e53f253a71691a4/src/libs/DomUtils/index.ts#L57
After that the text will have the same color as if the user had typed the email manually.
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-10-10 17:03
This seems to be fixed on staging.

Cannot repro this on dev and staging.

https://github.com/user-attachments/assets/40e64343-49f5-4789-a30d-d18b38bc4009

Can you please check this on staging? @lanitochka17

**Comment by klajdipaja** [comment] 2024-10-11 15:36
@c3024 I just tried on staging and was able to reproduce. 
See attached recording.

https://github.com/user-attachments/assets/ab00d6ea-2e58-42ec-931f-b751e8bded13

**Comment by lanitochka17** [comment] 2024-10-14 15:26
This issue is reproducible only in a different place

https://github.com/user-attachments/assets/934fed5a-c890-4160-99e7-46238580ec5a

**Comment by c3024** [comment] 2024-10-15 08:05
@klajdipaja 

Thank you, I can repro it now when changing the system theme.

I tried your solution and it did not work.

https://github.com/user-attachments/assets/3a94c0d7-abb5-4afe-b68a-f067eb45ef76

We are setting the auto-fill style globally in the `useEffect`. SignIn page has a fixed dark theme here.

https://github.com/Expensify/App/blob/7814eeddf74df2ea691b4dbf42696623310103cf/src/pages/signin/SignInPage.tsx#L347

so, the page stays dark even when theme changes to light.

But, some other instance of context can override the global auto-fill style due to the way the `useEffect` works. So, the light theme change triggers this `useEffect` in a different instance of context and changes the global auto-fill text style to dark.

Ideally, we should change the `useEffect` to affect only the children consuming the context instead of global scope.

An alternative is to somehow override the auto-fill style specifically in `SignInPageLayout` to always be of lighter text color (aka dark theme text color).

**Comment by klajdipaja** [comment] 2024-10-15 22:04
@c3024 An even better solution is to remove from the ThemeProvider the useEffect block below:
```
    useEffect(() => {
        DomUtils.addCSS(DomUtils.getAutofilledInputStyle(theme.text), 'autofill-input');
    }, [theme.text]);
```
And instead add this in `Expensify.tsx` as the container of all other pages to add the styling based the global `themeProvider` and in `SignInPageLayout.tsx` to add the styling based on the constant definition of the theme.

**Comment by klajdipaja** [comment] 2024-10-18 18:35
@c3024 that seems pretty strange to me because the css is added on the first render and if the user is logging out the SignInLayout would always render as a new instance. 

Maybe there's a css selector missing that does not cover the hovering of an auto fill input? 
I just tested this on chrome on MacOs and it works even with hovering. 

The root case of the bug was the rendering order of the two instances of the Theme provider. During logout the order was 1st the ThemeProvider in SignIn.tsx and then the one in App.tsx. If I refreshed the Sign In page the order was as expected App.tsx then SignIn

**Comment by klajdipaja** [comment] 2024-10-19 12:55
Ah I see. I cannot reproduce it in the way you have defined it but it does make sense that my solution might not work in that case.
Based on your solution with a minor tweak I have created this draft PR https://github.com/Expensify/App/pull/51117. Can you check if it works for your steps, for mine it works perfectly?

**Comment by c3024** [comment] 2024-10-21 06:50
Thanks, it works! Could you update the RCA and solution?

**Comment by c3024** [comment] 2024-10-21 10:52
@klajdipaja 's proposal [here](https://github.com/Expensify/App/issues/50460#issuecomment-2401819523) LGTM!

🎀 👀 🎀 C+ reviewed.

**Comment by klajdipaja** [comment] 2024-10-25 12:20
@c3024 PR is ready for review #51117

**Comment by kadiealexander** [comment] 2024-11-12 05:21
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by kadiealexander** [comment] 2024-11-12 05:26
Payouts due:

- [x] Contributor: $250 @klajdipaja [automatic offer](https://www.upwork.com/nx/wm/offer/104542746)
- [ ] Reviewer: $250 @c3024 [automatic offer](https://www.upwork.com/nx/wm/offer/104542745)

Upwork job is [here](https://www.upwork.com/jobs/~021843820742054331617).

**Comment by kadiealexander** [comment] 2024-11-13 03:24
@c3024 bump on the [checklist](https://github.com/Expensify/App/issues/50460#issuecomment-2454828463)!

**Comment by c3024** [comment] 2024-11-13 05:42
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: This was a too specific a bug that happens only for autocomplete fields when the theme is changed from system preferences. So, no specific PR can be held responsible.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: No, this was not a critical regression nor a discussion can be useful because this bug could not have been identified earlier.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- None

### Test:


1. Navigate to ND.
2. Log out of the account if logged in.
3. Go to MacOS System Settings > Appearance > Click on Light Mode
4. Go back to the ND tab in browser.
5. Tap on the Email field on log in screen.
6. Hover over an option in the autofill dropdown.
7. Verify that the text in the email field shows up clearly and its color is different from the background color of the email field.
8. Select an option in the autofill dropdown.
9. Verify that the text in the email field shows up clearly and its color is different from the background color of the email field.
10. Go to MacOS System Settings > Appearance > Click on Auto
11. Repeat steps 4 - 9 and verify the result
12. Go to MacOS System Settings > Appearance > Click on Dark
13. Repeat steps 4 - 9 and verify the result

Do we agree 👍 or 👎


</details>

**Comment by c3024** [comment] 2024-11-13 05:43
@kadiealexander , done. Thanks!

**Closed** 2024-11-14 03:26 UTC
Labels: External, Weekly, Awaiting Payment, Bug
