### ISSUE TITLE
[HOLD for payment 2023-08-01] [HOLD for payment 2023-07-28] Room - Deleted message and broken avatar displayed in header for threaded reply in public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23195] opened 2023-07-19 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23098
## Action Performed:
Prerequisite: user A created a public room
1. User A send a message to the public room
2. User A add a reply to the message to create a thread

## Expected Result:
Message is displayed as header ( in this case Hello) and no broken avatar image

## Actual Result:
Deleted message and broken avatar displayed as header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.0
 **Reproducible in staging?:** Yes
 
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6134457_Screen_Shot_2023-07-19_at_3 24 09_PM](https://github.com/Expensify/App/assets/78819774/b3205d54-475f-4703-9b8a-7b00ac5d0720)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by mountiny** [comment] 2023-07-19 21:01
@hannojg @0xmiroslav @fedirjh I think this might be related to the https://github.com/Expensify/App/pull/21406

**Comment by b4s36t4** [comment] 2023-07-19 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted message and broken avatar displayed in header for threaded reply in public room
### What is the root cause of that problem?

RCA for this issue lies here on this block.
https://github.com/Expensify/App/blob/cc51a0da258d93a0348a52dafccd6a7049edd81d/src/libs/ReportActionsUtils.js#L103-L108

If we observe the last line which we're using `lodash` to get particular report action but the items which we're getting is always gonna be empty.

```js
{} || {"key":"value"}
``` 
will always be `{}` same happening here.
https://github.com/Expensify/App/blob/cc51a0da258d93a0348a52dafccd6a7049edd81d/src/libs/ReportActionsUtils.js#L103
We're defining empty object here which is always the case lodash search on.

Means we're basically checking for parent Report action on an empty object `{}` which is resulting the following issue.

### What changes do you think we should make in order to solve the problem?

1. We can make `allReportActionsParam` as null or undefined.
2. We can use `isEmpty` function to determine on which object we're going to get parent report action.
3. We can pass `parentReportActions` from `HeaderView` component to here https://github.com/Expensify/App/blob/cc51a0da258d93a0348a52dafccd6a7049edd81d/src/libs/ReportUtils.js#L1122 and then pass it here https://github.com/Expensify/App/blob/cc51a0da258d93a0348a52dafccd6a7049edd81d/src/libs/ReportUtils.js#L1125 so that everything works seamlessly.



### What alternative solutions did you explore? (Optional)
NA

**Comment by jasperhuangg** [comment] 2023-07-19 21:38
This appears to be a regression from @hannojg's PR https://github.com/Expensify/App/pull/21406. 

I'll wait to see if they can fix it, otherwise I'll probably have to revert the PR.

**Comment by jasperhuangg** [comment] 2023-07-19 21:39
It looks like this is also affecting IOU reports: https://github.com/Expensify/App/issues/23202

**Comment by luacmartins** [comment] 2023-07-19 22:34
The issue seems to come from [this line](https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/libs/ReportActionsUtils.js#L107C17-L107C17). We pass `allReportActionsParam = {}` which is always truthy, so `allReportActionsParam || allReportActions` resolves to {} and we fail to get the correct action.

**Comment by jasperhuangg** [comment] 2023-07-19 22:34
@luacmartins it seems this is already going to be fixed in https://github.com/Expensify/App/pull/23206

**Comment by aldo-expensify** [comment] 2023-07-19 22:37
Yes, confirmed that it fixes that too:
<img width="1055" alt="image" src="https://github.com/Expensify/App/assets/87341702/667fb508-e75d-4309-82bf-23af60519879">

**Comment by aldo-expensify** [comment] 2023-07-19 23:07
Confirmed it is working now in staging:

<img width="1256" alt="image" src="https://github.com/Expensify/App/assets/87341702/4370b1fe-d631-4d39-800d-4da2ec5a0592">

**Comment by situchan** [comment] 2023-07-20 03:39
I first reported this bug in slack - https://expensify.slack.com/archives/C049HHMV9SM/p1689789076748419
Am I eligible for reporting bonus?

**Comment by aldo-expensify** [comment] 2023-07-20 16:55
@situchan confirmed. I'm not sure how it works in the case of deploy blockers, so I'll add `bug` to get a Bugzero team member to help out.

**Comment by aldo-expensify** [comment] 2023-07-20 16:56
@conorpendergrast I reopened this because they may be a bug reporting compensation to handle: https://github.com/Expensify/App/issues/23195#issuecomment-1643055115

**Comment by situchan** [comment] 2023-07-20 17:58
@fedirjh https://github.com/Expensify/App/issues/14816#issuecomment-1453532669

**Comment by conorpendergrast** [comment] 2023-07-26 08:42
@stitesExpensify Looks like there's nothing to pay here; can you fill out the C+ checklist and we'll close this out?

**Comment by stitesExpensify** [comment] 2023-07-26 15:09
Regression steps:

1. Create a public room
2. Send a message to the public room
3. Add a reply to the message to create a thread
4. In the thread, make sure the header has the correct title (the message that you threaded off of) and that the avatar shows correctly

**Comment by situchan** [comment] 2023-07-28 05:29
Based on https://github.com/Expensify/App/issues/23195#issuecomment-1644358372, I might still be eligible for reporting

**Comment by conorpendergrast** [comment] 2023-07-31 15:08
From the discussion [in this issue](https://github.com/Expensify/App/issues/14816#issuecomment-1453532669), that does not seem to be the case.

Regression test created: https://github.com/Expensify/Expensify/issues/304226

**Closed by conorpendergrast** 2023-07-31 15:08 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
