### ISSUE TITLE
Web -Chat - Extra rooms: admin and announce displayed after log in with owner account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11281] opened 2022-09-26 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when execute PR** https://github.com/Expensify/App/pull/10491

## Action Performed:
1. Go to staging.new.expensify.com
2. Create 3 accounts:
applausetester+workspace-admin@applause.expensifail.com/Feya86Katya
applausetester+workspace-employee@applause.expensifail.com/Feya86Katya
applausetester+workspace-owner@applause.expensifail.com/Feya86Katya
3. Login with in OldDot with applausetester+workspace-owner@applause.expensifail.com
and create workspace inviting applausetester+workspace-employee@applause.expensifail.com
as an employee and applausetester+workspace-admin@applause.expensifail.com as an admin.
4. Log in NewDot with applausetester+workspace-owner@applause.expensifail.com
account and check 3 policy expense chats, one for each workspace member, and two rooms: #announce and #admin

## Expected Result:
3 policy expense chats, one for each workspace member, and two rooms: #announce and #admin are displayed with owner account

## Actual Result:
Extra rooms: admin and announce displayed after log in with owner account

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![PR1](https://user-images.githubusercontent.com/93399543/192273030-b132f68a-5429-43e7-87d7-30aea8500c9e.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-09-26 17:39
In any event, workspace chats are still behind a beta, so we don't need to block deploy on this

**Comment by roryabraham** [comment] 2022-09-26 17:40
cc @trjExpensify @JmillsExpensify Can you buddy-check my above analysis of this issue please?

**Comment by JmillsExpensify** [comment] 2022-09-26 17:52
Agree we don't need to block a deploy.

**Comment by JmillsExpensify** [comment] 2022-09-26 17:53
For the workspace chats, can you check whether they were potentially created, just potentially don't show proactively in the LHN?

**Comment by roryabraham** [comment] 2022-09-26 17:53
> can you check whether they were potentially created, just potentially don't show proactively in the LHN?

Yes. I checked and they were not discoverable via search or request money pages

**Comment by roryabraham** [comment] 2022-09-26 17:54
Some more details over here: https://github.com/Expensify/App/pull/10491#issuecomment-1258404350

**Comment by aldo-expensify** [comment] 2022-09-26 17:55
Thanks for testing @roryabraham 

I understand that the **workspace-employee** (same as **workspace-admin** at the moment) should only see their policy expense chat, but I think this hides away if it is empty. I'll test again putting messages on each chat/room before closing the workspace. What I think is a bug is that the `#announce` room should have dissappeared for all non-admin/non-owner

**Comment by roryabraham** [comment] 2022-09-26 18:33
In any event, I think we should close this issue because I'm not able to reproduce it as written.

**Closed by roryabraham** 2022-09-26 18:33 UTC
Labels: Engineering, Daily
