### ISSUE TITLE
[$1000] Web - App crashes when leaving a room and quickly opening the room thread message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22309] opened 2023-07-05 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with userA's account and create a new public room
2. Share the room URL with userB and join the room from other browser
3. Send a message from userB in the room 
4. Click on “Reply in thread”
5. As userB, pin that thread 
6. As userB, now leave the room
7. As userB, quickly try to open the thread message again

## Expected Result:
The app should not crash when leaving a room and quickly opening the room thread message

## Actual Result:
The app crashes when leaving a room and quickly opening the room thread message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37.0
**Reproducible in staging?:** y
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/eb5211fc-2e25-4477-994e-5ff1d2b0693e

https://github.com/Expensify/App/assets/93399543/f7cac437-ab90-4c26-bfbb-9a3a1c96cd5f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688505226038469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d12aff4ab7fdf15</li>
        <li>Upwork Job ID: 1676886210538586112</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-07-06 09:28
Tested and reproduced. Updated the instructions to clarify which account to use for the last steps (userB)

<img width="1117" alt="image" src="https://github.com/Expensify/App/assets/5802477/bdff96bc-49f7-4563-a152-9571aa0b669e">

**Comment by chiragsalian** [comment] 2023-07-06 21:47
I'm pretty sure this issue has been solved and is fixed on staging from this [issue](https://github.com/Expensify/App/issues/22351). 

I think we should pay @ayazhussain79 for reporting the bug which was valid at the time and then close out this issue. Thoughts @conorpendergrast.

**Comment by conorpendergrast** [comment] 2023-07-07 09:20
This issue (https://github.com/Expensify/App/issues/22309) didn't get marked as a deploy blocker, and https://github.com/Expensify/App/issues/22351 did get marked as a deploy blocker. So https://github.com/Expensify/App/issues/22351 was prioritised and CP'ed to fix the issue immediately.

Given that, as @chiragsalian said, we'll pay @ayazhussain79 as the bug reporter (two different bugs, with the same root cause) and then will close out

**Comment by conorpendergrast** [comment] 2023-07-07 09:23
[Hiring page](https://www.upwork.com/ab/applicants/1676886210538586112/hired), offer sent to @ayazhussain79

**Comment by ayazhussain79** [comment] 2023-07-07 09:31
@conorpendergrast offer accepted, Thank you

**Comment by conorpendergrast** [comment] 2023-07-07 09:33
Paid, contract ended, all done

**Closed by conorpendergrast** 2023-07-07 09:33 UTC
Labels: External, Daily, Help Wanted, Bug
