### ISSUE TITLE
Contact methods - Green dot appears on Contact methods row on Profile page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28653] opened 2023-10-02 20:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new account
3. Enter the magic code
4. Go to Settings > Profile  Contact methods

## Expected Result:
There will be no green dot on the Contact methods row on Profile page as there is no changes made to the contact method

## Actual Result:
A green dot appears on Contact methods row on Profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7da2f902-84f9-4966-ae4b-0d5c827982f4

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-10-02 22:41
Dupe of https://github.com/Expensify/App/issues/28653

**Closed by mountiny** 2023-10-02 22:41 UTC
Labels: Engineering, Hourly, Bug
