### ISSUE TITLE
[HOLD for regression test] [$1000] Fix optimistic data for distance requests

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26518] opened 2023-09-01 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

# This issue is only present on the last main
# This issue requires an immediate action. If you're posting a proposal, make sure you can open a PR within 6 hours of proposal approval

## Action Performed:

1. Go to a workspace chat
2. Click "+" next to the text composer and click "Request money"
3. Click "Distance request" tab
4. Click "Start" and type any US address. Click any address suggestion.
5. Click "Finish" and and type any US address. Click any address suggestion. Make sure that the address is not the same address from Step 4.
6. Click "Next" and on the next page, click "Save"
7. Check that the data displayed is not correct (the amount is $0 for the distance request, for example)

_This is a bug reported [in this PR](https://github.com/Expensify/App/pull/25707#issuecomment-1702143728). Refer to that comment for screenshots_

## Expected Result:
The optimistic data should be the same as the distance request being created

## Actual Result:
The optimistic data it not correct

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ef448c9c160220d</li>
        <li>Upwork Job ID: 1697697328608083968</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>jeet-dhandha | Contributor | 26458547</li>
</ul></li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-09-01 19:53
I would also like to review the PR for this or even collaborate on the solution.

**Comment by hayata-suenaga** [comment] 2023-09-01 19:58
> I can be the C+ here if Santosh is not available.

@allroundexperts assigned you 🚀

**Comment by napster125** [comment] 2023-09-01 20:00
I can't reproduce it.

**Comment by BhuvaneshPatil** [comment] 2023-09-01 20:02
- This can be solved with #26514
The root cause of this is transaction being empty object in `MoneyRequestPreview`.

@mananjadhav is working on the above mentioned issue

**Comment by jeet-dhandha** [comment] 2023-09-01 20:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Displaying 0 in Distance Request.

### What is the root cause of that problem?
- The root cause of the problem is that the in `createDistanceRequest` function of `IOU.js` does not get amount and we pass initial amount as `0`.

https://github.com/Expensify/App/blob/7d9708a87a70eed61af520318a446794bae48d2f/src/libs/actions/IOU.js#L508-L513

### What changes do you think we should make in order to solve the problem?
- We can pass amount from `MoneyRequestConfirmPage.js` to `createDistanceRequest` function using `props.iou.amount`. But we will also need to update callback dependency else it will always pass `0`.

https://github.com/Expensify/App/blob/7d9708a87a70eed61af520318a446794bae48d2f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L145-L150

- Thus the onyx data will show correct amount.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by joh42** [comment] 2023-09-01 20:12
@jeet-dhandha beat me to it, that approach works for me as well

**Comment by jeet-dhandha** [comment] 2023-09-01 20:16
Adding it... 🧯 🙌 .

**Comment by BhuvaneshPatil** [comment] 2023-09-01 20:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
we are setting amouint as 0 by default in `createDistanceRequest`

### What alternative solutions did you explore? (Optional)
We shall pass the amount as `props.iou.amount`
```js

    const createDistanceRequest = useCallback(
        (selectedParticipants, trimmedComment) => {
            IOU.createDistanceRequest(props.report, selectedParticipants[0], trimmedComment, props.iou.created, props.iou.transactionID, props.iou.amount);
        },
        [props.report, props.iou.created, props.iou.transactionID, props.iou.amount],
    );
```

and here - 
```js
function createDistanceRequest(report, participant, comment, created, transactionID, amount = 0) {
    const {iouReport, chatReport, transaction, iouAction, createdChatReportActionID, createdIOUReportActionID, reportPreviewAction, onyxData} = getMoneyRequestInformation(
        report,
        participant,
        comment,
        amount,
        'USD',
        created,
        '',
        null,
        null,
        null,
        transactionID,
    );
    API.write(
        'CreateDistanceRequest',
        {
            comment,
            iouReportID: iouReport.reportID,
            chatReportID: chatReport.reportID,
            transactionID: transaction.transactionID,
            reportActionID: iouAction.reportActionID,
            createdChatReportActionID,
            createdIOUReportActionID,
            reportPreviewReportActionID: reportPreviewAction.reportActionID,
            waypoints: JSON.stringify(transaction.comment.waypoints),
            created,
        },
        onyxData,
    );
    Navigation.dismissModal(chatReport.reportID);
    Report.notifyNewAction(chatReport.reportID, userAccountID);
}
```

**Comment by jeet-dhandha** [comment] 2023-09-01 20:17
Added @allroundexperts .

**Comment by hayata-suenaga** [comment] 2023-09-01 20:29
> This can be solved with https://github.com/Expensify/App/issues/26270

I think although displaying skeleton will solve the issue temporarily, I think we eventually want to move the skeleton away.

I also love @jeet-dhandha's proposal! Assigning @jeet-dhandha

**Comment by michaelhaxhiu** [comment] 2023-09-01 20:30
🚀

**Comment by hayata-suenaga** [comment] 2023-09-01 20:31
@jeet-dhandha in your PR, could you also [handle this one](https://github.com/Expensify/App/pull/25707#issuecomment-1702143728)?

<img width="400" alt="Screenshot 2023-09-01 at 1 30 35 PM" src="https://github.com/Expensify/App/assets/98560306/642ed2d2-92df-4c80-b74d-f66a50d8c568">

**Comment by studentofcoding** [comment] 2023-09-01 20:31
Wow, Zip Zap!

**Comment by b4s36t4** [comment] 2023-09-01 20:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Fix optimistic date for distance requests
### What is the root cause of that problem?

There are few fields we're missing with optimistic data.

1. Amount
2. Merchant (defaults to `Request` we should have format like this `233.71 mi @ ₹0.655 / mi`)
3. Currency, it's default to `USD`
4. Comment (we're setting while doing manual request)

### What changes do you think we should make in order to solve the problem?
We need to pass all those details from here https://github.com/Expensify/App/blob/7d9708a87a70eed61af520318a446794bae48d2f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L145.


### What alternative solutions did you explore? (Optional)
NA

@allroundexperts @hayata-suenaga I think everybody is only thinking about money, but not about other fields, which would raise multiple regressions.

**Comment by jeet-dhandha** [comment] 2023-09-01 20:38
> @jeet-dhandha in your PR, could you also [handle this one](https://github.com/Expensify/App/pull/25707#issuecomment-1702143728)?
> 
> <img alt="Screenshot 2023-09-01 at 1 30 35 PM" width="400" src="https://user-images.githubusercontent.com/98560306/265121484-642ed2d2-92df-4c80-b74d-f66a50d8c568.png">

@hayata-suenaga Are you talking about the duplicate values as names ?

**Comment by b4s36t4** [comment] 2023-09-01 20:38
<img width="443" alt="Screenshot 2023-09-02 at 2 06 38 AM" src="https://github.com/Expensify/App/assets/59088937/2ded14a2-2c21-4949-98d6-5
<img width="567" alt="Screenshot 2023-09-02 at 2 06 56 AM" src="https://github.com/Expensify/App/assets/59088937/50665528-31d0-4761-9616-f8336e0edd79">
bdbc52cc320">


https://github.com/Expensify/App/assets/59088937/7ee13665-16cd-4564-a241-8dc115b89890

These attachments would help figuring out things.

**Comment by hayata-suenaga** [comment] 2023-09-01 20:38
@jeet-dhandha yep I think that's also an issue with optimistic update. I think that should be a workspace name

**Comment by jeet-dhandha** [comment] 2023-09-01 20:39
Yes but i wasn't able to reproduce it.

**Comment by b4s36t4** [comment] 2023-09-01 20:39
No proposal ever mentioned to update all the data optimistically, just about amount.

**Comment by hayata-suenaga** [comment] 2023-09-01 20:40
@jeet-dhandha could you send me what you're seeing?

> No proposal ever mentioned to update all the data optimistically, just about amount.

that's true I was quick to approve but I'm confident that @jeet-dhandha can figure out this one, too

**Comment by b4s36t4** [comment] 2023-09-01 20:41
I'm wondering how we're accepting proposals with just one quick fix?

**Comment by jeet-dhandha** [comment] 2023-09-01 20:42
<img width="419" alt="Screenshot 2023-09-02 at 2 12 00 AM" src="https://github.com/Expensify/App/assets/78416198/510260c8-86f8-4d60-ae08-264bb876aca2">
<img width="588" alt="Screenshot 2023-09-02 at 2 12 04 AM" src="https://github.com/Expensify/App/assets/78416198/6828571b-21f8-4106-8670-22594c65de85">

It looks like this currently.

**Comment by b4s36t4** [comment] 2023-09-01 20:44
No body bothered to re-search/debug what fields to add to optimistic data, all of them want to post their proposal just to get quick view and get assigned :(. 

Sorry If I'm talking rudely, but just saying the truth out-there. Even if we're in hurry to release the feature but without correct review about proposal may posses multiple regressions which could effect the whole feature.

**Comment by hayata-suenaga** [comment] 2023-09-01 20:49
@jeet-dhandha okay then we're fine with that. Just make sure that we double check it when we do PR review

**Comment by napster125** [comment] 2023-09-01 20:50
@b4s36t4 what about [this](https://github.com/Expensify/App/issues/26020#issuecomment-1698577934)?

**Comment by hayata-suenaga** [comment] 2023-09-01 20:51
@jeet-dhandha could you make sure that you pass all these fields when creating the optimistic data?

- Amount
- Merchant (defaults to Request we should have format like this 233.71 mi @ ₹0.655 / mi)
- Currency, it's default to USD
- Comment (we're setting while doing manual request)

**Comment by hayata-suenaga** [comment] 2023-09-01 20:52
> No body bothered to re-search/debug what fields to add to optimistic data, all of them want to post their proposal just to get quick view and get assigned :(.
> 
> Sorry If I'm talking rudely, but just saying the truth out-there. Even if we're in hurry to release the feature but without correct review about proposal may posses multiple regressions which could effect the whole feature.

@b4s36t4 you're absolutely right and this was partly my fault. I remember I also rejected your proposal in another GH issue just because you mentioned a wrong function name

**Comment by hayata-suenaga** [comment] 2023-09-01 20:53
I'm handling several issues related to this distance-requested features and I make mistakes often.

@b4s36t4 I really appreciate you pointing out these mistakes

**Comment by b4s36t4** [comment] 2023-09-01 20:54
@hayata-suenaga I strongly suggest we wait for sometime before just going assign to contributor. We're not investigating enough before assigning. We're in a hurry but that doesn't mean to do things in wrong way right? I'd be happy more than happy to help in-case you ever need one (I'll make sure I don't share my proposal though). But I hope we consider these points from next point.

**Comment by jeet-dhandha** [comment] 2023-09-01 20:55
> @jeet-dhandha could you make sure that you pass all these fields when creating the optimistic data?
> 
> * Amount
> * Merchant (defaults to Request we should have format like this 233.71 mi @ ₹0.655 / mi)
> * Currency, it's default to USD
> * Comment (we're setting while doing manual request)

Yes i can @hayata-suenaga .

**Comment by b4s36t4** [comment] 2023-09-01 20:55
I understand the hurry @hayata-suenaga. But it's so hurting to miss the things just like that. I hope one day you get to assign a feature request to me. Waiting for that issue to be create :) and get to assign for that.

**Comment by jeet-dhandha** [comment] 2023-09-01 21:04
For Merchant we can use `DistanceRequestUtils.getDistanceMerchant(distance, unit, rate, currency, translate)` from `MoneyRequestConfirmationList.js` and pass it as a parameter to `onConfirm` which is called in `MoneyRequestConfirmPage.js` and then access it from there.

**Comment by hayata-suenaga** [comment] 2023-09-01 21:36
@b4s36t4 what is the reason you did 👎 ?

if you could help us move this forward, we might be able to offer you a compensation for your work.

**Comment by b4s36t4** [comment] 2023-09-01 21:40
Nah, I feel he should do those things before proposing a solution. Not after someone pointed that out. Nothing sort of mistake or so.

I would love to help, but I don't think my intervention is needed here because we have multiple people reviewing I see neil and allrounderexperts are here. But once PR is up I would definitely try to review 😅.

**Comment by jeet-dhandha** [comment] 2023-09-01 21:40
@hayata-suenaga I would like to collaborate with @b4s36t4 on this one like i can half the bounty with him. 
- I will update the changes proposed by me in my PR and @b4s36t4 can create another PR for the changes he suggested.

**Comment by jeet-dhandha** [comment] 2023-09-01 21:41
> @hayata-suenaga I would like to collaborate with @b4s36t4 on this one like i can half the bounty with him.
> 
> * I will update the changes proposed by me in my PR and @b4s36t4 can create another PR for the changes he suggested.

How does this sound to you @b4s36t4 ?

**Comment by b4s36t4** [comment] 2023-09-01 21:43
Hey, @jeet-dhandha. It's ok you can proceed. I will help you in reviewing anyway (kind of revenge to find bugs 😁😁😁).

**Comment by b4s36t4** [comment] 2023-09-01 21:44
I'm just pointing that we should be doing our research fully, not just propose the solution first. 

I'm so sorry to wind up here. Will be leave this issue here. Thanks so much guys. Thanks a lot for understanding my concerns @hayata-suenaga.

**Comment by hayata-suenaga** [comment] 2023-09-01 21:59
Let's open a PR @jeet-dhandha

**Comment by jeet-dhandha** [comment] 2023-09-01 22:04
Yes creating one 👍

**Comment by neil-marcellini** [comment] 2023-09-01 22:19
Please be sure to fix and test [these bugs](https://github.com/Expensify/App/pull/25707#issuecomment-1702876998) in the PR as well.

**Comment by neil-marcellini** [comment] 2023-09-01 22:22
Also [this one](https://github.com/Expensify/App/pull/25707#issuecomment-1702835806). These are all related to optimistic data, but @jeet-dhandha if you feel that these bugs are too much for one PR please let me know and I can create a separate issue for whichever bugs you would like separated.

**Comment by jeet-dhandha** [comment] 2023-09-01 22:48
Let me check and get back on the issue from that PR.
- https://github.com/Expensify/App/pull/25707#issuecomment-1702835806

**Comment by jeet-dhandha** [comment] 2023-09-01 22:58
@neil-marcellini @hayata-suenaga I have created the PR and added the required code for amount, merchant and currency.

**Comment by hayata-suenaga** [comment] 2023-09-02 19:21
@jeet-dhandha Please make a follow up PR[ per this instruction](https://github.com/Expensify/App/pull/26536#discussion_r1313956946)

@michaelhaxhiu We will consider the issue to be complete when the follow-up PR ⬆️  is merged 🙇

**Comment by mountiny** [comment] 2023-09-03 10:52
@michaelhaxhiu Noting there was a regression from the PR as other payment flows were not tested https://github.com/Expensify/App/issues/26600

**Comment by michaelhaxhiu** [comment] 2023-09-15 16:56
This seems ready for payment. It was merged within 3 days, but the regression negates the bonus.

So we'll pay list price in this case:

- **contributor:** @jeet-dhandha $1000
- **C+:** @allroundexperts $1000
- **bug reporter:** n/a (hayata made this GH)

**Comment by michaelhaxhiu** [comment] 2023-09-15 16:59
Hmm allow me to review just to be sure

**Comment by michaelhaxhiu** [comment] 2023-09-15 17:00
Thanks for the correction, you are right. The times have changed!

<img width="992" alt="image" src="https://github.com/Expensify/App/assets/13206896/a435e7b5-3a62-4139-af66-853301761f9d">

**Comment by michaelhaxhiu** [comment] 2023-09-15 17:06
@allroundexperts do you intend to draft any regression test steps for this one, per the BZ checklist?

**Comment by michaelhaxhiu** [comment] 2023-09-15 17:16
thanks!

**Comment by michaelhaxhiu** [comment] 2023-09-15 17:56
@allroundexperts please request payment via newDot!

**Comment by michaelhaxhiu** [comment] 2023-09-20 17:19
internal QA regression test steps added here https://github.com/Expensify/Expensify/issues/318552

**Comment by michaelhaxhiu** [comment] 2023-09-20 17:19
Closing since all the steps are done here. @allroundexperts did you receive payment btw?

**Closed by michaelhaxhiu** 2023-09-20 17:19 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 12:58
$500 payment approved for @allroundexperts based on BZ summary.
