### ISSUE TITLE
[HOLD for payment 2024-05-22] [$250] Submit expense - Floating 'Lets go' Above Upload Recipient Statement When Dragging and Dropping Files

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40897] opened 2024-04-24 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.65-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to FAB > Submit Expense > Choose Manual.
2. Add amount > Choose user > Click three dots in the right corner.
3. Drag and drop the file onto the recipient. Notice that the "Lets go" text floats above the upload recipient statement.

## Expected Result:
When dragging and dropping files onto the recipient area, the "Let's Go" prompt should not float above the upload recipient statement. Instead, the upload recipient statement should be replaced by "Let's Go," similar to the behavior in the scan section.

## Actual Result:
The "Lets go" text floats above the upload recipient statement when dragging and dropping the file onto the recipient. this causes inconsistency with Scan section.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2fe29077-6865-4096-b30b-f43cecad92a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01316df55587475e87</li>
        <li>Upwork Job ID: 1786433047739318272</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by kbecciv** [comment] 2024-04-24 14:14
We think that this bug might be related to #vip-split

**Comment by kbecciv** [comment] 2024-04-24 14:14
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by alexpensify** [comment] 2024-04-26 21:03
This one is on my testing list, I should have an update soon.

**Comment by alexpensify** [comment] 2024-04-29 23:38
No update yet, I've been focused on other GHs.

**Comment by alexpensify** [comment] 2024-05-02 20:08
Closing - I'm unable to replicate the experience. The process loads correctly. 


![2024-05-02_13-07-39](https://github.com/Expensify/App/assets/8107070/664b8921-7dac-4773-9270-ac871f62b5d9)

**Comment by bernhardoj** [comment] 2024-05-03 06:04
@alexpensify you need to access the scan page from the manual confirmation page here (Add receipt)
<img width="416" alt="image" src="https://github.com/Expensify/App/assets/50919443/4b18dc1a-9bb0-47f3-b3cc-1123a1f93b2d">

The issue doesn't happen on the scan start page, but happens if you access it from the confirmation page

**Comment by alexpensify** [comment] 2024-05-03 15:03
## Heads up, I will be offline until Tuesday, May 7, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

--- 

I will test this one more when I get back online.

**Comment by alexpensify** [comment] 2024-05-03 15:04
Thanks for clarifying this step: 

>Navigate to FAB > Submit Expense > Choose Manual.

**Comment by alexpensify** [comment] 2024-05-03 16:33
I had a free minute before going OOO and followed the steps that @bernhardoj shared here: 

https://github.com/Expensify/App/issues/40897#issuecomment-2092361780

I confirmed there is an issue, @mollfpr can you please confirm if the proposal will fix this issue: 

![2024-05-03_09-28-55](https://github.com/Expensify/App/assets/8107070/b0a7e079-1b70-4c1e-9ed5-c4c533208622)

Thanks! Now, I'm going OOO and will be back Tuesday. 👋🏼

**Comment by mollfpr** [comment] 2024-05-03 19:13
Checking 👀

**Comment by mollfpr** [comment] 2024-05-06 12:25
@bernhardoj I'm inclined to expose the `isDraggingOver` from `StepScreenDragAndDropWrapper` and use it instead of use it as a fallback.

I think this value can't be used since we don't wrap the page with `DragAndDropProvider`.
https://github.com/Expensify/App/blob/92696df2a9f7e19e1d78035d3f12a4d7fb4223e5/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L65

What do you think?

**Comment by bernhardoj** [comment] 2024-05-06 12:45
I like that too, but my concern with that is the scan component in the money request start page will have 2 drag and drop providers.

1 in start page,
https://github.com/Expensify/App/blob/cd9a9ad735605624623ccf2ee4f9e6c0cda57af7/src/pages/iou/request/IOURequestStartPage.tsx#L138

and the other one is in StepScreenDragAndDropWrapper. That's why I put the fallback solution first. I think we can name the fallback value isDraggingOverWrapper

**Comment by bernhardoj** [comment] 2024-05-09 08:31
PR is ready

cc: @mollfpr

**Comment by alexpensify** [comment] 2024-05-10 23:07
@mollfpr please keep us posted if you are unable to review this PR. Thanks!

**Comment by mollfpr** [comment] 2024-05-11 15:36
PR approved 🚀

**Comment by alexpensify** [comment] 2024-05-13 21:51
Thanks, @arielgreen; sorry I associated it with the wrong project. My bad! 

@mollfpr thanks for the review.

**Comment by alexpensify** [comment] 2024-05-17 15:29
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

@miljakljajic  - While I'm offline, I need help here completing the payment process after this one clears the 7-day period on 2024-05-22. Thanks!

**Comment by miljakljajic** [comment] 2024-05-17 16:52
@bernhardoj has been hired on the upwork job. @mollfpr do we pay you via manual request, or in upwork?

**Comment by mollfpr** [comment] 2024-05-21 16:44
@miljakljajic I'll do a manual request, could you help with the payment summary? I'll finish the checklist ASAP. Thank you!

**Comment by miljakljajic** [comment] 2024-05-24 12:03
Of course. 

@mollfpr is owed 250 USD for their work reviewing this PR.

**Comment by mollfpr** [comment] 2024-05-28 17:40
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR was found.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open FAB > Submit expense
2. Enter any amount and select any participant
3. Press 3-dot on the confirmation page and select Add receipt
4. Drag a file over the page
5. Verify the instruction text (drag a receipt onto this page...) and that the icon is hidden
6. 👍 or 👎 

Only the web/desktop can drag a file
For mWeb/Android/iOS, verify you can still add a receipt

**Comment by alexpensify** [comment] 2024-05-28 23:35
I'm back online and taking over as the BZ member here. 

Tomorrow, I'll create the regression test GH based on today's update.

**Comment by alexpensify** [comment] 2024-05-30 22:38
Closing - The QA request has been created for this one. Thanks!

**Comment by JmillsExpensify** [comment] 2024-05-31 03:24
$250 approved for @mollfpr

**Comment by JmillsExpensify** [comment] 2024-08-01 03:20
@miljakljajic this payment will end up going through New Expensify. I've closed out the Upwork job since payment wasn't issued. Do you mind adding a payment summary for @bernhardoj?

**Comment by miljakljajic** [comment] 2024-08-01 08:15
Of course!

@bernhardoj is owed 250 USD for their work reviewing this issue.

**Closed by miljakljajic** 2024-08-01 08:15 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-01 20:17
$250 approved for @bernhardoj
