### ISSUE TITLE
[$500] IOU -In BNP page the currency symbol alone shown for a millisecond without amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26629] opened 2023-09-03 21:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap Split bill
4. Enter an amount
5. Tap Next
6. Tap Back

## Expected Result:
In split bill, BNP page, the currency symbol with amount must be shown when user tap back

## Actual Result:
The user can see in split bill BNP page, the currency symbol alone for a millisecond and then only shows entered amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2e3ed1d0-812a-4e86-ae48-a370b3b8bb85

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3c4fda715422964</li>
        <li>Upwork Job ID: 1699326274642403328</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-09-06 07:57
Applied External

**Comment by h0u554m** [comment] 2023-09-06 20:32
To improve the user experience, you can implement a loading mechanism where you check if the state is not empty. If it's not empty, you display the data. If it is empty, you show a loading indicator, and after a brief delay (e.g., 0.5 seconds or less), you can display a default value. This way, users are aware that data is being fetched, and they eventually see a default value if the data retrieval takes longer.

**Comment by h0u554m** [comment] 2023-09-06 20:34
Your Expensify account email: https://new.expensify.com/a/15606409
Upwork Profile Link: https://www.upwork.com/freelancers/~01d68a22e5d906bca6

**Comment by h0u554m** [comment] 2023-09-06 20:34
To improve the user experience, you can implement a loading mechanism where you check if the state is not empty. If it's not empty, you display the data. If it is empty, you show a loading indicator, and after a brief delay (e.g., 0.5 seconds or less), you can display a default value. This way, users are aware that data is being fetched, and they eventually see a default value if the data retrieval takes longer.

**Comment by sobitneupane** [comment] 2023-09-11 04:32
@h0u554m Can you please put your proposal in proper format. You can go through [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) and proposal in other issues for more details.

**Comment by h0u554m** [comment] 2023-09-11 16:16
To improve the user experience, you can implement a loading mechanism where you check if the state is not empty. If it's not empty, you display the data. If it is empty, you show a loading indicator, and after a brief delay (e.g., 0.5 seconds or less), you can display a default value. This way, users are aware that data is being fetched, and they eventually see a default value if the data retrieval takes longer.


Your Expensify account email: https://new.expensify.com/a/15606409
Upwork Profile Link: https://www.upwork.com/freelancers/~01d68a22e5d906bca6

**Comment by h0u554m** [comment] 2023-09-11 16:17
@sobitneupane

**Comment by sobitneupane** [comment] 2023-09-12 14:27
@h0u554m Can you please post your proposal in [this format](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md)

**Comment by h0u554m** [comment] 2023-09-12 14:35
Problem Statement:
Let's clarify the issue we're addressing here. The problem is displaying currency without a number for values less than 1 second, followed by displaying the number.

Root Cause Analysis:
The root cause of this issue is that the number is retrieved from the state, and it takes some time to fetch the number and display it alongside the currency.

Proposed Solution:
To resolve this issue, we should implement a loading state that waits until the entire page is ready to display the currency and number together.

Alternative Solutions Explored (Optional):
Other potential solutions could involve saving the state in local storage or reverting to the default state, i.e., displaying 0, when the number retrieval takes time.

**Comment by h0u554m** [comment] 2023-09-12 14:35
@sobitneupane

**Comment by sobitneupane** [comment] 2023-09-12 15:34
@h0u554m https://github.com/Expensify/App/issues/25727#issuecomment-1691776494 is a sample of expected proposal. You should link the file(permalink) where the issue exists. Why the line/ piece of code cause the issue? What is your proposed solution. Where will you perform the change? How will it solve the issue.

**Comment by s-alves10** [comment] 2023-09-13 11:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The currency symbol alone shown for a millisecond without amount when back to amount page

### What is the root cause of that problem?

We're using [AmountTextInput](https://github.com/Expensify/App/blob/main/src/components/AmountTextInput.js) in `MoneyRequestAmountForm`. As you can see below, `autoGrow` props is true and so `TextInput` component shows the input element after measures the size of the content.
https://github.com/Expensify/App/blob/2ed276bd562f183c0cb39582c73f9e19cda75db4/src/components/AmountTextInput.js#L45

This is the root cause

### What changes do you think we should make in order to solve the problem?

For this simple TextInput element, we can use `TextInput` from `react-native`
In order to measure content, introduce new state
```
    const [size, setSize] = useState({width: 0, height: 0});
    const inputStyle = [styles.iouAmountTextInput, styles.p0, styles.noLeftBorderRadius, styles.noRightBorderRadius];

    const isContentMeasured = size.width > 0 && size.height > 0;
    const visibleStyles = isContentMeasured ? [styles.hiddenElementOutsideOfWindow, styles.visibilityHidden] : [];
```

Show `Text` before size is measured, and then show `TextInput`
```
    return (
        <>
            {isContentMeasured && (
                <RNTextInput
                    showSoftInputOnFocus={false}
                    style={[...inputStyle, size]}
                    onChangeText={props.onChangeAmount}
                    value={props.formattedAmount}
                    placeholder={props.placeholder}
                    placeholderTextColor={themeColors.placeholderText}
                    keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}
                    blurOnSubmit={false}
                    selection={props.selection}
                    onSelectionChange={props.onSelectionChange}
                    accessibilityRole={CONST.ACCESSIBILITY_ROLE.TEXT}
                    onKeyPress={props.onKeyPress}
                    onFocus={() => Keyboard.dismiss()}
                    ref={(el) => {
                        textInputRef.current = el;
                        if (!props.forwardedRef) {
                            return;
                        }

                        if (_.isFunction(props.forwardedRef)) {
                            props.forwardedRef(el);
                            return;
                        }

                        // eslint-disable-next-line no-param-reassign
                        props.forwardedRef.current = el;
                    }}
                />
            )}
            <Text
                style={[...inputStyle, ...visibleStyles]}
                onLayout={(e) => setSize(e.nativeEvent.layout)}
            >
                {props.formattedAmount || props.placeholder}
            </Text>
        </>
    );
```

In order to prevent showing keyboard, introduce new ref
```
    const textInputRef = useRef(null);
    useEffect(() => {
        const appStateSubscription = AppState.addEventListener('change', (nextAppState) => {
            if (!nextAppState.match(/inactive|background/)) {
                return;
            }

            Keyboard.dismiss();
        });

        return () => {
            appStateSubscription.remove();
        };
    }, []);

    useEffect(() => {
        if (!textInputRef.current || !textInputRef.current.setAttribute || !isContentMeasured) {
            return;
        }
        textInputRef.current.setAttribute('inputmode', 'none');
    }, [isContentMeasured])
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/85455549-fc96-4bbb-bf92-1e9d94bc2532


</details>


### What alternative solutions did you explore? (Optional)

We can create a new component `SimpleTextInput` for `AmountTextInput`

**Comment by greg-schroeder** [comment] 2023-09-18 10:47
awaiting proposal review

**Comment by sobitneupane** [comment] 2023-09-18 11:26
@s-alves10 Can you confirm if this problem can still be replicated? I'm not able to reproduce it on my side.

https://github.com/Expensify/App/assets/25876548/9718d25c-d018-4ac1-8e1c-4a3e9a6efa93

**Comment by s-alves10** [comment] 2023-09-18 11:55
@sobitneupane 

Yes, this is still reproducible. This issue happens only for split bill, not request money.
Please try to test in a group chat

**Comment by sobitneupane** [comment] 2023-09-21 15:06
@s-alves10 I couldn't reproduce the issue with the split bill either.

https://github.com/Expensify/App/assets/25876548/3e11c59f-0789-406c-b452-623f22c08da5

**Comment by s-alves10** [comment] 2023-09-21 21:12
@sobitneupane 

I can see the bug in your recorded video when navigating back from selecting currency page

**Comment by greg-schroeder** [comment] 2023-09-25 07:23
Hmm.. maybe I'm not seeing it. At one timestamp in the video do you see the bug @s-alves10?

**Comment by s-alves10** [comment] 2023-09-25 08:39
I can see the bug between 13s ~ 14s

**Comment by sobitneupane** [comment] 2023-09-25 10:23
Thanks @s-alves10 I finally noticed the issue. 😀

It exists for only a fraction of a second. It is almost imperceptible. I don't think it is worth fixing.

**Comment by greg-schroeder** [comment] 2023-09-25 15:39
I had the timestamp and knew what the bug was and it still took me like 60 seconds to see it. Honestly I tend to agree. I'm going to close this.

**Closed by greg-schroeder** 2023-09-25 15:39 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
