### ISSUE TITLE
Android - Connect bank account - Unable to connect with Plaid option, page is skipping

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8947] opened 2022-05-11 17:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Go to Setting - Preferences
4. Enable Secure Staging server
5. Go to any Workspace
6. Tab connect Bank account
7. Tab Connect online with Plaid
8. Select Wells Fargo bank account
9. Tap user name: user_good
10. Tap password: pass_good
11. Tap Continue

## Expected Result:
Able to move into Company page

## Actual Result:
Unable to connect with Plaid, page is skipping

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.57.12

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** No, unable to verify VBA flow in Prod

**Email or phone of affected tester (no customers):** any expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167911151-38db584c-e238-4c45-93a1-592c2308b5c4.mp4

https://user-images.githubusercontent.com/93399543/167911206-65a6a958-997c-4ba1-95ca-d0a1857082a7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment] 2022-05-11 20:43
@luacmartins This issue is failing PR https://github.com/Expensify/App/pull/8808 - I'm adding the deploy blocker label since this behavior was not reproducible before. (we're unable to check if the issue is reproducible in prod bc the test credentials don't work there)

**Comment by luacmartins** [comment] 2022-05-11 21:54
Hmm I took a quick look at this one and I _think_ it may have been introduced [here](https://github.com/Expensify/App/pull/8858). It seems that dismissing the Plaid modal on mobile makes the app become active, firing the reconnect callbacks. I think that might create the bug with the navigation. Commenting [this line](https://github.com/Expensify/App/blob/42da9392c8b33545b77499a3053a6e4d1467221c/src/libs/actions/App.js#L120) out seems to fix the issue. I didn't spend too much time investigating this, so it's possible the cause is elsewhere.

We could just revert that PR for now if the goal is to get a deploy (since we haven't done so in ~3 weeks). If that ends up being the issue, I have a few ideas on how to solve it.

**Comment by chiragsalian** [comment] 2022-05-12 01:11
Cool looks like the others blockers are resolved. I could revert this but you have till tomorrow if you would like to investigate a different solution if you do not want to revert. QA is still working on the checklist (their ETA atm is to finish by tomorrow morning) so while they are working on it you can decide if you would rather revert of check another solution 🙂  let me know.

**Comment by sketchydroide** [comment] 2022-05-12 10:03
I've assigned you to the GH @luacmartins as you seem to be on top of it
If this is the only blocker, I would say that revert and then fix this withouth the added pressure would be better

**Comment by luacmartins** [comment] 2022-05-12 15:35
Trying to test this further.

**Comment by luacmartins** [comment] 2022-05-12 16:12
I did some more testing and I'm not sure that the PR I linked before is the issue anymore. Looking at other possibilities now.

**Comment by luacmartins** [comment] 2022-05-12 16:45
Nvm my previous comment. It seems that when we fire the reconnect callbacks this line empties the `achData` and `subStep`. It happens on mobile because the Plaid modal somehow puts the app in the background. I put up a quick fix here, I'll discuss this further with Marc once he's back since he's been leading these changes.

**Comment by chiragsalian** [comment] 2022-05-12 19:03
Hi @kbecciv, this should be resolved in version `1.1.57-15` or higher.
Can you retest and confirm? if its resolved feel free to close the issue.

**Comment by chiragsalian** [comment] 2022-05-12 23:41
Passed the checklist, closing isssue.

**Closed by chiragsalian** 2022-05-12 23:41 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
