### ISSUE TITLE
[$1000] Web - Settings -  Unwanted behaviour when click on browser back button after clicking the report a bug

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25412] opened 2023-08-17 15:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open the settings and go to about.
2. click on the report a bug, it goes to the concierge composer
3. Now, Click on the browser back button.
4. see the transitions occuring unpleasant to initial settings or about screen

## Expected Result:
Either it should have only one transition to initial settings or about screen.

## Actual Result:
it is giving the unpleasant transitions to initial settings or about screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d2949841-f43a-4449-a4ae-e6dcd6fe9305

https://github.com/Expensify/App/assets/115492554/fd6c52dc-0b7d-4f67-99cd-4fd48686b53a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @immadisetty-jaya-surya 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691135024865169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4a8c2a8b4824bff</li>
        <li>Upwork Job ID: 1692655236084695040</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-08-17 16:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we click on report a bug and browser back button the transition is weird

### What is the root cause of that problem?

We are not dismissing the about page from the stack when we go to the concierge chat, so when we go back it shows the about page breifly before going to the settings page

### What changes do you think we should make in order to solve the problem?

We should use Navigation.dismissModal before navigating to concierge chat

### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2023-08-18 21:51
Agreed that this looks like it should only pull up one menu and ideally the 'About' menu.

**Comment by immadisetty-jaya-surya** [comment] 2023-08-20 19:06
@garrettmknight I have reported this issue, please update my username in the description so melvin can do automation, thanks

**Comment by robertKozik** [comment] 2023-08-20 20:20
Hey @ShogunFire can you update your proposal per @garrettmknight [comment](https://github.com/Expensify/App/issues/25412#issuecomment-1684469125) ? So the about page would be available after the back action

**Comment by ShogunFire** [comment] 2023-08-20 22:53
Actually after reading the slack conversation this issue like others should have been tagged with [Tracking Browser back button] and it should be resolved by this PR https://github.com/Expensify/App/pull/24165 

I can't apply the patches so I still have the error but can someone try to reproduce after the patch ?

**Comment by shubham1206agra** [comment] 2023-08-21 15:16
Hello everyone
Temp logs
```
{
    "index": 1,
    "indexGetter": 1,
    "items": [
        {
            "path": "/r/1705808921226559",
            "id": "8hugcF4Du91dOHzCvk6-l",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "selected": "<<<<<<<",
            "path": "/settings",
            "id": "OGJAC-QkjFmJLEzjNjci6",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        }
    ]
}
createMemoryHistory.js:7 {
    "index": 2,
    "indexGetter": 2,
    "items": [
        {
            "path": "/r/1705808921226559",
            "id": "8hugcF4Du91dOHzCvk6-l",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/settings",
            "id": "OGJAC-QkjFmJLEzjNjci6",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "selected": "<<<<<<<",
            "path": "/settings/about",
            "id": "dVlBM7I6DvSCwR2sv5eeY",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        }
    ]
}
createMemoryHistory.js:7 {
    "index": 3,
    "indexGetter": 3,
    "items": [
        {
            "path": "/r/1705808921226559",
            "id": "8hugcF4Du91dOHzCvk6-l",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/settings",
            "id": "OGJAC-QkjFmJLEzjNjci6",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/settings/about",
            "id": "dVlBM7I6DvSCwR2sv5eeY",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "selected": "<<<<<<<",
            "path": "/r/7323501660300024",
            "id": "GhiTr-GpHH6SW8lA25iqS",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        }
    ]
}
createMemoryHistory.js:7 {
    "index": 3,
    "indexGetter": 3,
    "items": [
        {
            "path": "/r/1705808921226559",
            "id": "8hugcF4Du91dOHzCvk6-l",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/settings",
            "id": "OGJAC-QkjFmJLEzjNjci6",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/settings/about",
            "id": "dVlBM7I6DvSCwR2sv5eeY",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "selected": "<<<<<<<",
            "path": "/r/7323501660300024",
            "id": "GhiTr-GpHH6SW8lA25iqS",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        }
    ]
}
createMemoryHistory.js:7 {
    "index": 2,
    "indexGetter": 2,
    "items": [
        {
            "path": "/r/1705808921226559",
            "id": "8hugcF4Du91dOHzCvk6-l",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/settings",
            "id": "OGJAC-QkjFmJLEzjNjci6",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "selected": "<<<<<<<",
            "path": "/settings/about",
            "id": "dVlBM7I6DvSCwR2sv5eeY",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/r/7323501660300024",
            "id": "GhiTr-GpHH6SW8lA25iqS",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        }
    ]
}
createMemoryHistory.js:7 {
    "index": 2,
    "indexGetter": 2,
    "items": [
        {
            "path": "/r/1705808921226559",
            "id": "8hugcF4Du91dOHzCvk6-l",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/settings",
            "id": "OGJAC-QkjFmJLEzjNjci6",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "selected": "<<<<<<<",
            "path": "/settings/about",
            "id": "dVlBM7I6DvSCwR2sv5eeY",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "path": "/r/7323501660300024",
            "id": "GhiTr-GpHH6SW8lA25iqS",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        }
    ]
}
createMemoryHistory.js:7 {
    "index": 1,
    "indexGetter": 1,
    "items": [
        {
            "path": "/r/1705808921226559",
            "id": "8hugcF4Du91dOHzCvk6-l",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        },
        {
            "selected": "<<<<<<<",
            "path": "/settings",
            "id": "Ddpn6LV45RYRFw_ng7kjD",
            "state": "stack-bteljlS4gW7AcWp49NQpC"
        }
    ]
}
```

**Comment by WoLewicki** [comment] 2023-08-23 08:42
Could you check if it is still reproducible on the newest main @robertKozik and others? Seems like the issue is gone but maybe we are wrong.

**Comment by robertKozik** [comment] 2023-08-23 09:29
Can confirm - I cannot reproduce this issue on latest main (video attached)

https://github.com/Expensify/App/assets/61146594/9796ecce-e687-4ff2-8103-32f97ca506d3

**Comment by garrettmknight** [comment] 2023-08-25 14:10
Confirming it looks like it's been fixed. I'll still pay out @immadisetty-jaya-surya for reporting, but closing otherwise.

Summary of Payments:
- Reporter - @immadisetty-jaya-surya - $250 paid in Upwork.

**Comment by garrettmknight** [comment] 2023-08-25 14:13
Reopening - couldn't find the bug reporter's Upwork profile.

**Comment by immadisetty-jaya-surya** [comment] 2023-08-26 09:23
@garrettmknight i m surya ...itz my upwork profile 
profile link : https://www.upwork.com/freelancers/~0126183a58ad2d5be4
inform me if it doesn't open ..
thank you ... !!

**Comment by immadisetty-jaya-surya** [comment] 2023-08-28 16:28
yeah @garrettmknight i applied which you have been send...!!

**Comment by garrettmknight** [comment] 2023-08-28 16:52
Awesome, thanks! Offer sent.

**Comment by immadisetty-jaya-surya** [comment] 2023-08-28 18:00
@garrettmknight Accepted the offer [:-)

**Comment by garrettmknight** [comment] 2023-08-28 18:18
Nice, paid!

**Closed by garrettmknight** 2023-08-28 18:18 UTC
Labels: External, Daily, Help Wanted, Bug
