### ISSUE TITLE
[HOLD App#20630] [$1000] Web – DOB – Arrow button shows weird behavior when used with future dates.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21521] opened 2023-06-25 15:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open your profile.
2.	Click on "Settings".
3.	Click on "Personal Details".
4.	Click on "Date of Birth".
5.	Select the year 2018 and click on the right arrow to proceed to the next month after selecting the 31st of the current month.
6.	Notice that initially, it will jump to the next month. However, when you go back and select the date again, a "not allowed" sign appears over the arrow.
## Expected Result:
If the selected date is in the future, the "Not Allowed" sign should remain visible in the previous month.
## Actual Result:
The "Not Allowed" sign does not appear even if the selected date is in the future.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/db8afe18-6f21-4032-b1eb-2b80b7e3444f

https://github.com/Expensify/App/assets/43996225/050ca16f-acb3-4b5d-9539-c9fde82093cc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687253920451309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a703d7a35964ac71</li>
        <li>Upwork Job ID: 1673364633738194944</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-06-26 16:16
Looks like we already have one proposal up for review @0xmiroslav

**Comment by CallMeAmartya** [comment] 2023-06-27 12:35
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web – DOB – Arrow button shows weird behavior when used with future dates.
### What is the root cause of that problem?
![image](https://github.com/Expensify/App/assets/47215240/e48324ce-cfd8-49ee-a5ce-d94d2575f360)
### The solution
Here, we should change `moment(this.props.maxDate).endOf('month').startOf('day')` to `moment(this.props.maxDate).endOf('day')` as here the only purpose of this `hasAvailableDatesNextMonth` fxn seems to be to check whether the adding 1 month to the current date won't exceed the current date. 
### Result after change 
Testing on June 27, If I select May 27 I am able to move forward one month, but selecting May 28,29, etc wont allow me to click on the next month button.

https://github.com/Expensify/App/assets/47215240/f4798853-f7fe-4bfc-bf0a-087efa05a0e5

### What alternative solutions did you explore? (Optional)
NA

**Comment by CallMeAmartya** [comment] 2023-06-27 12:39
Contributor details
Your Expensify account email: amartyasen00077@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e0f36fff0755c57b

**Comment by lschurr** [comment] 2023-06-28 20:28
@0xmiroslav could you review the proposals here?

**Comment by CallMeAmartya** [comment] 2023-07-01 11:58
@0xmiroslav @lschurr any updates?

**Comment by CallMeAmartya** [comment] 2023-07-04 17:36
@0xmiroslav If I understood the problem correctly, the 'next month' button should be disabled if clicking on it (i.e adding 1 month to the selected date) results in a 'future' date. If that is the case, then this is still an issue as seen in the below clip.

https://github.com/Expensify/App/assets/47215240/b2d556ca-c430-458f-a76a-b4d5a6fe01ab

I tested this on the main branch on July 4. If on the calendar, I select a date after **June** 4, the button is not disabled, and clicking on it results in the warning text "Date should be before 2018-07-04". But the expected result says that the button itself should be disabled in such a case. Please clarify if my understanding is correct.

**Comment by lschurr** [comment] 2023-07-05 20:21
@0xmiroslav - do you have thoughts on @CallMeAmartya's question above?

**Comment by shawnborton** [comment] 2023-07-05 20:38
Hmm I feel like just paginating through the months doesn't/shouldn't actually select a date. So we shouldn't show any kind of error until the user actually selects a date inside of the month.

**Comment by shawnborton** [comment] 2023-07-05 20:42
I'm not so sure I agree. I would bring this up in the open source room for larger discussion though. cc @mountiny I feel like we chatted about something similar recently?

**Comment by mountiny** [comment] 2023-07-06 01:47
I agree with Shawn, there was a discussion in Slack but I cant find the link right now unfortunately which concluded that we should only select the date once user click on the specific date. Thats how majority of other datepickers work.

I would actually put this on hold for the datepicker refactor so we dont duplicate work https://github.com/Expensify/App/issues/20630

**Comment by lschurr** [comment] 2023-07-14 20:27
Still on hold I believe.

**Comment by lschurr** [comment] 2023-07-24 15:17
Has this one been fixed @fedirjh?

**Comment by lschurr** [comment] 2023-07-24 18:41
@usmantariq96 could you apply to the job here? https://www.upwork.com/jobs/~01a703d7a35964ac71

**Comment by usmantariq96** [comment] 2023-07-25 03:24
@lschurr applied for job
Thanks

**Comment by lschurr** [comment] 2023-07-25 17:59
Thanks! Offer sent @usmantariq96

**Comment by usmantariq96** [comment] 2023-07-25 18:12
Accepted with thanks

**Comment by lschurr** [comment] 2023-07-25 20:11
Paid and closing!

**Closed by lschurr** 2023-07-25 20:11 UTC
Labels: External, Weekly, Help Wanted, Bug
