### ISSUE TITLE
prod link is pointing to staging.new.expensify.com in the welcome email

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45106] opened 2024-07-09 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rushatgabhane 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720544851471489

## Action Performed:
1. User received an welcome email from expensify
2. Hover on the link next to "Reply to this message or respond at..."
## Expected Result:
The link points to new.expensify.com
## Actual Result:
The link is pointing to staging.new.expensify.com
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (7)](https://github.com/Expensify/App/assets/38435837/b8e62a82-3f79-43cf-94f8-87ea37ffde1a)

![Screenshot 2024-07-09 143924](https://github.com/Expensify/App/assets/38435837/b468950b-3369-459a-a887-3cecc4539884)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment] 2024-07-09 18:41
🎀👀🎀

Internal

**Comment by neil-marcellini** [comment] 2024-07-10 20:46
@CortneyOfstad I'm closing this since I don't think it's worth fixing. Real users won't be using or interacting with people using staging. Please re-open if you disagree.

**Closed by neil-marcellini** 2024-07-10 20:46 UTC
Labels: Daily, Bug

**Comment by rushatgabhane** [comment] 2024-07-10 23:39
> Real users won't be using or interacting with people using staging

@neil-marcellini ahh okay is that the root cause?
