### ISSUE TITLE
[UX Reliability] The LHN is out of sync across multiple platforms

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#48149] opened 2024-08-28 08:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-10
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1724780554260709

## Action Performed:
Break down in numbered steps

1. Use the app in multiple platforms using the same account
2. Notice the order of the LHN chats on each platform after some time

## Expected Result:
Describe what you think should've happened

the LHN order should stay at sync at all times across platforms. The onyx updates should ensure all clients have all the necessary data

## Actual Result:
Describe what actually happened

The LHN got out of sync

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by OlimpiaZurek** [comment] 2024-08-28 08:35
Hi! I'm Olimpia from Callstack and I would like to work on this issue.

**Comment by carlosmiceli** [comment] 2024-08-28 13:20
@mountiny since Olimpia picked it up, should I remain as reviewer? I think I only got one `AutoAssignerNewDotQuality` issue assigned so far, so not sure I remember how it works in this case.

**Comment by muttmuure** [comment] 2024-08-28 13:25
Here's an SO that will help out! https://stackoverflowteams.com/c/expensify/questions/19512

Olimpia will lead but may have questions about the back end that you will need to source answers for

**Comment by carlosmiceli** [comment] 2024-08-28 13:32
@muttmuure thanks man! I didn't connect the dots between Calstack <-> "agency engineer" in the SO, perfect. I'll support Olimpia in every way I can 💪

**Comment by OlimpiaZurek** [comment] 2024-08-29 14:51
I've been investigating this issue and have encountered difficulties reproducing it.

The LHN appears to be synced across various devices (I have checked both development and staging, as I do not have access to the hybrid app).

The only inconsistency I noticed is that when I receive a new message and then perform a "clear cache and restart on client" on one device, the message's unread status is cleared on this device but remains marked as "unread" on the other device, leading to an unsynced state across different devices.

I am still waiting for the exported Onyx state from David's devices so that I can analyze the data and determine the cause of this issue.

**Comment by carlosmiceli** [comment] 2024-08-29 15:06
@OlimpiaZurek Understood, it does seem that it's not happening lately since Jason said [here](https://expensify.slack.com/archives/C05LX9D6E07/p1724852175699749?thread_ts=1724780554.260709&cid=C05LX9D6E07) he doesn't see the issue anymore either. Let's give David until early next week to send us his Onyx state, or we can follow up with him then.

**Comment by carlosmiceli** [comment] 2024-09-02 13:17
Will follow up with David :)

**Comment by carlosmiceli** [comment] 2024-09-03 12:16
@OlimpiaZurek I see that David shared the onyx state, let me know if you have any questions!

**Comment by OlimpiaZurek** [comment] 2024-09-04 15:02
Daily update:

I started analyzing the Onyx state data across different platforms and environments using the files provided by David:

*  New Expensify app on Android
*  hybrid app
*   staging on desktop web, Chrome
*  mobile web Android Chrome staging

During the analysis, I noticed that most items were displayed in the correct order, but I identified some discrepancies in the Onyx state data for certain reports that are inconsistently displayed on the LHN across platforms.

Detailed examples of the issues observed:

- report_7177703019320414
    - Issue: This report is not displayed in the New Expensify app on Android, but is visible on other platforms.
    - Onyx State Data: The Onyx state data differs between the platforms:

New Expensify App (Android):

```json
"report_7177703019320414": {
  "isPinned": true
}
```
Other Platforms:
``` json
   "report_7177703019320414": {
    "reportID": "7177703019320414",
    "reportName": "",
    "type": "chat",
    "chatType": "policyExpenseChat",
    "ownerAccountID": 1,
    "managerID": 0,
    "policyID": "0CFE78B25EBE2A0A",
    "participants": {
      "1": {
        "hidden": false,
        "notificationPreference": "always"
      },
      "778531": {
        "hidden": false,
        "notificationPreference": "always"
      },
      "9645353": {
        "hidden": false,
        "notificationPreference": "always"
      },
      "10903701": {
        "hidden": false,
        "notificationPreference": "always"
      }
    },
    "participantAccountIDs": {},
    "visibleChatMemberAccountIDs": {},
    "isPinned": true,
    "lastReadTime": "2024-02-27 16:48:03.527",
    "lastReadSequenceNumber": 0,
    "lastVisibleActionCreated": "2024-02-27 13:50:10.163",
    "lastVisibleActionLastModified": "2024-02-27 13:50:10.163",
    "lastMessageText": "😉",
    "lastActionType": "ADDCOMMENT",
    "lastActorAccountID": 778531,
    "notificationPreference": "always",
    "stateNum": 0,
    "statusNum": 0,
    "oldPolicyName": "",
    "private_isArchived": "",
    "isOwnPolicyExpenseChat": true,
    "lastMessageHtml": "😉",
    "hasOutstandingChildRequest": false,
    "hasOutstandingChildTask": false,
    "policyName": "NewDot Test - Expensify US",
    "writeCapability": "all",
    "description": "",
    "total": 0,
    "unheldTotal": 0,
    "currency": "USD",
    "isWaitingOnBankAccount": false,
    "nonReimbursableTotal": 0,
    "isCancelledIOU": false,
    "avatarUrl": "",
    "errorFields": {}
  },
```

- report_1340070253236388 
	- Issue: This report is displayed only on the New Expensify app and not on other platforms.
	- Onyx State Data:  On other platforms, the report has the property `"notificationPreference": "hidden"`.
    
- report_3457340604597114 
	- Issue: This report is displayed on the New Expensify app but not on other platforms.
	-  Onyx State Data:  On New Expensify, the report has `"notificationPreference": "always"`, whereas on other platforms, it is marked as hidden.
	
- report_1424311336893618
    - Issue: report is displayed only on the web Android platform and does not appear in the Onyx state data on other platforms.
    
- report_68943617
    - Issue: This report is displayed on the web Android platform  but not on other platforms.
    -  Onyx State Data: on the web Android platform, the report has` "notificationPreference": "always"`, whereas on other platforms, it is marked as hidden.

Screenshots:
New Expensify:
<img width="370" alt="new_expensify" src="https://github.com/user-attachments/assets/b2814151-4447-4b7b-a0ec-f516b987b818">

Hybrid App:
<img width="370" alt="hybrid_app_" src="https://github.com/user-attachments/assets/a0ae0ef1-c6ad-4af3-a803-1b8f4c7bbcd7">

staging on desktop web, Chrome:
<img width="373" alt="web_desktop" src="https://github.com/user-attachments/assets/49a4718a-9a63-4263-8e58-a62aadc58493">

mobile web Android Chrome staging:
<img width="365" alt="web_android" src="https://github.com/user-attachments/assets/4e21be56-cd91-4430-a3b3-a57536574ff8">

Further investigation  into the data syncing and Onyx state update processes is needed to determine the exact root cause and resolve these discrepancies.

**Comment by carlosmiceli** [comment] 2024-09-06 14:38
Hi @OlimpiaZurek, thought I'd share this latest comment on slack: https://expensify.slack.com/archives/C05LX9D6E07/p1725631656709919

**Comment by carlosmiceli** [comment] 2024-09-09 14:21
Missing read time definitely is a great theory! Sharing on slack to see how to move forward 💪

**Comment by carlosmiceli** [comment] 2024-09-09 17:54
Moving this to internal to investigate what's happening with the payload that doesn't always include `lastReadTime`.

**Comment by carlosmiceli** [comment] 2024-09-10 19:34
[This](https://github.com/Expensify/App/issues/46835) upcoming PR may fix this, so will move this to Weekly and will monitor its development.

**Comment by carlosmiceli** [comment] 2024-09-19 19:20
Still waiting on the PR above.

**Comment by carlosmiceli** [comment] 2024-09-30 15:51
Seems like we're close to a solution here: https://expensify.slack.com/archives/C05LX9D6E07/p1727453029185229?thread_ts=1724780554.260709&cid=C05LX9D6E07

**Comment by jliexpensify** [comment] 2024-10-01 09:52
Just a heads up I'm OOO from 3rd to 14th, but I don't think anything is needed from me during this period. Feel free to reassign to another B0 if needed though!

**Comment by mountiny** [comment] 2024-10-09 15:37
Reapplied as Carlos already was tackling some other newdot quality task https://expensify.slack.com/archives/C05LX9D6E07/p1728325184832929

**Comment by johnmlee101** [comment] 2024-10-09 15:46
```
However, we currently de-duplicate requests related to ReconnectApp, so we may need to wait until the other requests refactor is complete to see the final results.
```
Seems like we're kind of holding on this?

**Comment by mountiny** [comment] 2024-10-09 16:03
So this happened already and @OlimpiaZurek shared [here](https://expensify.slack.com/archives/C05LX9D6E07/p1728470546901829?thread_ts=1724780554.260709&cid=C05LX9D6E07) that she was not able to reproduce. This was reported by @quinthar, so I suggest we ask him to keep an eye on this, and if it's still repro, note here. Otherwise we can close

**Comment by mountiny** [comment] 2024-10-14 01:52
David did some debugging on his case and found out some of the reordering is happening because the expense report name changes and in focus mode the reports are ordered alphabetically which makes these out of sync https://expensify.enterprise.slack.com/archives/C05LX9D6E07/p1728690899937859?thread_ts=1724780554.260709&channel=C05LX9D6E07&message_ts=1728690899.937859

**Comment by muttmuure** [comment] 2024-10-21 15:49
@adhorodyski please can I assign you? This is the CRITICAL quality issue that I am most concerned about progress over right now

**Comment by jliexpensify** [comment] 2024-10-28 02:44
Bump @adhorodyski to comment here!

**Comment by muttmuure** [comment] 2024-10-28 17:43
Going to close as Adam is working on the newer version of this issue [here](https://github.com/Expensify/App/issues/50696)

**Closed by muttmuure** 2024-10-28 17:43 UTC
Labels: Weekly, Internal, Bug, AutoAssignerNewDotQuality
