### ISSUE TITLE
[$250] Android - Mark down - App crashes when deleting text with mark down in a sentence with heading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46908] opened 2024-08-06 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Device keyboard must be Samsung keyboard
- Issue is not reproducible with Gboard
1. Launch New Expensify app
2. Go to chat
3. Type # hey _hey_
4. Double tap to select and highlight the second word with mark down _ hey _
5. Tap delete on Samsung keyboard

## Expected Result:
App will not crash

## Actual Result:
App crashes
This issue is only reproducible with Samsung keyboard and not Gboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b0bc1b8b-a385-4021-a81a-38a074fb0cb6

[logs (2).txt](https://github.com/user-attachments/files/16513750/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc8d3436a587add7</li>
        <li>Upwork Job ID: 1821616561702134137</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103818157</li>
<li>wildan-m | Contributor | 103818158</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-08-06 17:23
We think that this bug might be related to #Live Markdown

**Comment by lanitochka17** [comment] 2024-08-06 17:23
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-08-12 18:03
No proposals yet.

**Comment by isabelastisser** [comment] 2024-08-15 03:03
Still waiting for proposals.

**Comment by alitoshmatov** [comment] 2024-08-17 10:29
Waiting for proposals

**Comment by isabelastisser** [comment] 2024-08-21 17:29
No proposals yet.

**Comment by alitoshmatov** [comment] 2024-08-24 09:32
No proposals yet

**Comment by isabelastisser** [comment] 2024-08-28 01:49
Still waiting for proposals.

**Comment by isabelastisser** [comment] 2024-08-29 20:40
no proposals yet.

**Comment by wildan-m** [comment] 2024-09-03 07:49
[Proposal Updated](https://github.com/Expensify/App/issues/46908#issuecomment-2325767668)
- Add result video

**Comment by alitoshmatov** [comment] 2024-09-03 17:18
@wildan-m Thank you for your proposal, I think your RCA is correct and we can go with you solution

C+ reviewed 🎀 👀 🎀

**Comment by isabelastisser** [comment] 2024-09-03 18:33
We have chosen a proposal and are waiting for @neil-marcellini's review.

**Comment by neil-marcellini** [comment] 2024-09-04 18:21
> @wildan-m Thank you for your proposal, I think your RCA is correct and we can go with you solution
> 
> C+ reviewed 🎀 👀 🎀

Wow great job! Hiring

**Comment by wildan-m** [comment] 2024-09-05 08:55
@alitoshmatov The upstream PR is ready. https://github.com/Expensify/react-native-live-markdown/pull/469

**Comment by isabelastisser** [comment] 2024-09-10 19:26
@alitoshmatov @wildan-m, can you please provide an update? Thanks!

**Comment by wildan-m** [comment] 2024-09-10 21:28
@isabelastisser discussing optimal approach to avoid duplicate calls in upstream. https://github.com/Expensify/react-native-live-markdown/pull/469#issuecomment-2335002872

**Comment by tomekzaw** [comment] 2024-09-12 07:42
https://github.com/Expensify/react-native-live-markdown/pull/469 has just been merged

**Comment by wildan-m** [comment] 2024-09-12 07:47
Thank you, @tomekzaw!

@alitoshmatov @neil-marcellini Should we simply update the version in the E/App to apply it? I see that the live markdown version in E/App is not the latest. Are there specific steps to follow?

**Comment by tomekzaw** [comment] 2024-09-12 07:49
There's already a PR that bumps react-native-live-markdown here: https://github.com/Expensify/App/pull/48626

**Comment by wildan-m** [comment] 2024-09-12 07:54
@tomekzaw can we bump the version to [0.1.140](https://github.com/Expensify/react-native-live-markdown/releases/tag/0.1.140) there or we should temporarily create patch until that PR closed?

**Comment by tomekzaw** [comment] 2024-09-12 07:58
Let's avoid patches and bump directly to latest if possible

**Comment by tomekzaw** [comment] 2024-09-12 18:31
Should be fixed with https://github.com/Expensify/App/pull/48626

**Comment by alitoshmatov** [comment] 2024-09-12 21:51
Waiting for `react-native-live-markdown` bump on https://github.com/Expensify/App/pull/48626

**Comment by mvtglobally** [comment] 2024-09-13 16:40
Issue not reproducible during KI retests. (First week)

**Comment by wildan-m** [comment] 2024-09-16 21:00
Not overdue, The fix PR [passed the test](https://github.com/Expensify/App/pull/48626#issuecomment-2348728367) and is now live in production https://github.com/Expensify/App/pull/48626#issuecomment-2353604788.

**Comment by alitoshmatov** [comment] 2024-09-17 18:33
Not overdue. 

FYI: I was only involved on selecting proposal, I was not involved in reviewing corresponding PRs

**Comment by neil-marcellini** [comment] 2024-09-17 19:30
What's the next step here? What are we waiting for?

**Comment by alitoshmatov** [comment] 2024-09-18 12:48
We are in a regression period now. Solution went into production on 16th september

**Comment by isabelastisser** [comment] 2024-09-23 17:48
@neil-marcellini @alitoshmatov, it looks like this is ready for payment. Do we need a regression test?

**Comment by isabelastisser** [comment] 2024-09-26 20:19
The payments were processed in Upwork. All set!

**Closed by isabelastisser** 2024-09-26 20:19 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
