### ISSUE TITLE
[$250] Android - Chat - The inline block posted to the chat has gaps/breaks between words

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46411] opened 2024-07-29 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13.-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4775449
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open Android Expensify App
2. Login with any account
3. Go to any chat
4. Post message with inline block like `Block with some text`

## Expected Result:
The inline block is displayed correctly without issues or breaks

## Actual Result:
The inline block posted to the chat has gaps/breaks between words

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/35305740-d291-4e8a-b697-9f414d37f1ea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ada30930a7daf24</li>
        <li>Upwork Job ID: 1819335516900884107</li>
        <li>Last Price Increase: 2024-08-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by lanitochka17** [comment] 2024-07-29 13:30
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-29 13:31
We think that this bug might be related to https://github.com/orgs/Expensify/projects/91

**Comment by BartoszGrajdek** [comment] 2024-08-02 12:11
Hi, I'm Bartosz from SWM `react-native-live-markdown` team. I believe this issue is less related to the Live Markdown than it is to the E/App itself, but let's keep it in that project for now 👀 

cc @tomekzaw

**Comment by QichenZhu** [comment] 2024-08-07 02:28
I can't reproduce it on the `main` branch.

![2278c451-cbca-4412-823f-874bf500c0a6](https://github.com/user-attachments/assets/0ee9bdce-ef41-460b-a48a-553a35637968)

**Comment by sonialiap** [comment] 2024-08-07 10:28
I also cannot reproduce it on prod

**Comment by sonialiap** [comment] 2024-08-07 10:29
closing since it seems to be resolved

**Closed by sonialiap** 2024-08-07 10:29 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
