### ISSUE TITLE
[$1000] Web - Chat - Deleting an attachement from thread chat is not refelected when using back button from the browser

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25600] opened 2023-08-21 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. open any chat from LHN
3. click the + icon from the chat room
4. click add an attachment and then upload the file
5. open the thread from the file
6. send a text in the thread
7. deleted the attached file from thread and back to the main chat room using back button from the browser

## Expected Result:
the deleted attachment should be reflected

## Actual Result:
the deleted attachment is not reflected and it is reflected when refreshing or getting back to the room after switching the room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v.1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ee44a66b-b0fe-4ec5-8cb7-aa8559426382

https://github.com/Expensify/App/assets/115492554/04735a7c-3d27-4bc2-853a-a345cc0345b9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691680968470399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c849706e8d0359a2</li>
        <li>Upwork Job ID: 1693728422214217728</li>
        <li>Last Price Increase: 2023-08-21</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-08-21 20:54
Reproduced. Noting that this is only related to the native back button on the browser. It works if using the app's back button.

**Comment by shubham1206agra** [comment] 2023-08-22 09:16
Not able to repro

https://github.com/Expensify/App/assets/58412969/9620ade7-d5d6-4708-a080-d92a6341d7a0

**Comment by shubham1206agra** [comment] 2023-08-22 09:20
Only repro on production. Maybe fixed already.

**Comment by jjcoffee** [comment] 2023-08-22 09:32
@izarutskaya are you able to retest on staging?

**Comment by shubham1206agra** [comment] 2023-08-22 10:13
https://github.com/Expensify/App/assets/58412969/86fc08de-7ca1-4476-a84c-ea940cd90166

**Comment by misgana96** [comment] 2023-08-22 10:53
@jjcoffee It is only reproducible in production. I tested it on staging and It is not producible in staging.
/home/misgana/Videos/Screencasts/Screencast from 22-08-2023  1:51:23 ከሰዓት.webm

**Comment by jjcoffee** [comment] 2023-08-22 11:50
@joekaufmanexpensify I think we can close this as nobody can repro on staging!

**Comment by misgana96** [comment] 2023-08-22 12:27
I think the issue is fixed for a new release. It was reproduced for the old version. @jjcoffee @joekaufmanexpensify am I eligible for a report bonus?

**Comment by joekaufmanexpensify** [comment] 2023-08-22 12:41
Yep, confirmed this is working now. So no action needed here.

**Comment by joekaufmanexpensify** [comment] 2023-08-22 12:42
@misgana96 We appreciate you reporting this! But there wouldn't be a reporting bonus since we did not do anything to fix this bug as a result of this issue, since this was already being fixed elsewhere. Please let me know if you have any questions about this. Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-08-22 12:42
Closing as this is all set!

**Closed by joekaufmanexpensify** 2023-08-22 12:42 UTC
Labels: External, Daily, Help Wanted, Bug
