### ISSUE TITLE
[$1000] URL appears as html in thread title and alternate text in search page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20520] opened 2023-06-09 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send a website url
3. Hover and click on thread icon
4. See the header
5. Go to search and search "<a"
## Expected Result: 
Normal text should be shown
## Actual Result: 
URL shows in html format

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-09 at 10 24 33 AM](https://github.com/Expensify/App/assets/43996225/cb116830-48d1-449f-82cc-5022eb541157)

<img width="954" alt="Screenshot (367)" src="https://github.com/Expensify/App/assets/43996225/909d2c59-f21b-4f13-8877-2f19de99af99">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686286858935369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b674a204efbb9b04</li>
        <li>Upwork Job ID: 1671168762113949696</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-06-09 17:26
@grgia is out for the weekend, going to grab this.

**Comment by roryabraham** [comment] 2023-06-10 23:14
I confirmed that this bug is caused in the back-end. The root cause is that the text for the reportAction is being overwritten by HTML.

If you take these same actions offline, it will work.

**Comment by roryabraham** [comment] 2023-06-10 23:18
That means that, if it's not too late, this should actually be a deploy blocker for the API, not E/App.

**Comment by roryabraham** [comment] 2023-06-10 23:21
Going to create an internal deploy blocker

**Comment by roryabraham** [comment] 2023-06-10 23:23
Internal issue link: https://github.com/Expensify/Expensify/issues/291036

**Comment by roryabraham** [comment] 2023-06-10 23:56
PR to fix this ready here: https://github.com/Expensify/Web-Expensify/pull/37784

**Comment by roryabraham** [comment] 2023-06-10 23:57
@grgia requested your review on that PR because this issue was auto-assigned to you originally 😉

**Comment by roryabraham** [comment] 2023-06-12 22:52
This is fixed

**Comment by Puneet-here** [comment] 2023-06-16 07:06
> @roryabraham, is this eligible for the reporting compensation?

cc: @johncschuster

**Comment by roryabraham** [comment] 2023-06-17 02:03
Looks like @Puneet-here is eligible for the bug reporting bonus here.

**Comment by roryabraham** [comment] 2023-06-17 02:03
Sorry I didn't notice it earlier, @Puneet-here

**Comment by Puneet-here** [comment] 2023-06-17 19:32
No problem! Thanks for opening it again.

**Comment by roryabraham** [comment] 2023-06-19 19:02
@johncschuster last TODO here is paying out the reporting bonus

**Comment by johncschuster** [comment] 2023-06-20 14:50
Thanks for the callout, @roryabraham! I'll apply the `External` label now so the job can be created.

**Comment by johncschuster** [comment] 2023-06-20 14:51
Sorry for the ping, @sobitneupane. I applied the label just to have the job get created automatically. Nothing to do here!

**Comment by johncschuster** [comment] 2023-06-20 14:54
@Puneet-here I've just invited you to the job via Upwork. Can you ping me once you've accepted that?

**Comment by johncschuster** [comment] 2023-06-22 13:55
@Puneet-here friendly bump so I can issue you the reporting bonus!

**Comment by Puneet-here** [comment] 2023-06-22 19:19
Sorry for the delay. Just accepted the offer.

**Comment by Puneet-here** [comment] 2023-06-23 18:00
Thanks. We can close the issue @johncschuster

**Closed** 2023-06-26 17:21 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
