### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Web -  infinite loop on click of back button when go to connect bank account page of deleted policy

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23167] opened 2023-07-19 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Go to any policy > bank account
3. Copy the browser url
4. Go back to policy page and delete workspace
5. Paste the url in browser
6. Click on back button

## Expected Result:
 After clicking back button from "hmm... it's not here" page, we'd navigate to the Workspaces page (https://staging.new.expensify.com/settings/workspaces). Then, clicking back from there would navigate to the settings page. 

## Actual Result:
Infinite loop on click of back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.42-9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/24001481-04f8-4655-a6aa-559e6ce17563

https://github.com/Expensify/App/assets/93399543/4a57c001-500d-471a-b9d8-2eb7e25a6d8f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689684394065279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105141c978bfd9133</li>
        <li>Upwork Job ID: 1683596190818557952</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 25815017</li>
<li>ginsuma | Contributor | 25815018</li>
<li>gadhiyamanan | Reporter | 25815022</li>
</ul></li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-07-19 12:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Modal hides instead of going back to previous page (Workspace page) when user opens Connect bank account via a URL.

### What is the root cause of that problem?
We are not passing `onBackButtonPress` prop to the `HeaderWithBackButton` component here -
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/pages/ReimbursementAccount/ContinueBankAccountSetup.js#L42-L47

Due to this, when back button is clicked the default function for `onBackButtonPress` is used which uses default fallbackRoute - `ROUTES.HOME` and user returns to home screen -
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/components/HeaderWithBackButton/index.js#L25
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/libs/Navigation/Navigation.js#L99

### What changes do you think we should make in order to solve the problem?
We need to pass the `onBackButtonPress` to `HeaderWithBackButton` in `ContinueBankAccountSetup` -
```javascript
onBackButtonPress={() => Navigation.goBack(ROUTES.getWorkspaceInitialRoute(props.policyID))}
```

For this, we need to define a new prop `policyID` in `ContinueBankAccountSetup` of type `PropTypes.string` and pass `policyID` to `ContinueBankAccountSetup` from `ReimbursementAccountPage`.

### What alternative solutions did you explore? (Optional)
NA

**Comment by yh-0218** [comment] 2023-07-19 12:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - infinite loop on click of back button when go to connect bank account page of deleted policy
### What is the root cause of that problem?
Because of using `Navigation.navigate` for `FullPageNotFoundView` in `ReimbursementAccountPage`
### What changes do you think we should make in order to solve the problem?
We can remove `onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS)}` from `FullPageNotFoundView` in `ReimbursementAccountPage` to hide the model
### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2023-07-24 15:09
OOO for 10 days

**Comment by joekaufmanexpensify** [comment] 2023-07-24 21:53
Reproduced! I updated OP as the expected behavior here should be that when the user clicks back on the Hm, it's not here page, we navigate back to the workspaces page. And then if they click back from there, back to the Settings page.

**Comment by joekaufmanexpensify** [comment] 2023-07-25 12:58
Pending review of proposals

**Comment by joekaufmanexpensify** [comment] 2023-07-26 17:06
@situchan Could you provide an update on your review of these proposals when you have a chance?

**Comment by joekaufmanexpensify** [comment] 2023-07-28 12:46
Bumped in Slack.

**Comment by situchan** [comment] 2023-07-28 18:31
@ginsuma's [proposal](https://github.com/Expensify/App/issues/23167#issuecomment-1641985641) looks good to me. It's aligned with back button behavior of page not found view on other policy pages.
🎀 👀 🎀 C+ reviewed

**Comment by luacmartins** [comment] 2023-07-28 18:48
Agreed, [proposal](https://github.com/Expensify/App/issues/23167#issuecomment-1641985641) looks good.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 13:14
@situchan mind completing the BZ checklist here when you have a sec?

**Comment by situchan** [comment] 2023-08-09 14:39
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21819
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21819/files#r1288606613
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

We can now detect such issues in PR stage thanks to this new checklist item:

- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.

**Comment by joekaufmanexpensify** [comment] 2023-08-09 19:45
Great, thanks! BZ checklist is complete. All set to issue payment tomorrow.

**Comment by joekaufmanexpensify** [comment] 2023-08-09 19:46
This [qualified for a speed bonus](https://github.com/Expensify/App/issues/23167#issuecomment-1658942909), so we need to make the following payments: 

- @ginsuma $1,500 ($1,000 for PR, and $500 speed bonus). 
- @situchan $1,500 ($1,000 for C+ review, and $500 speed bonus). 
- @gadhiyamanan $250 for reporting bonus.

**Comment by joekaufmanexpensify** [comment] 2023-08-09 19:47
All three offers are accepted in Upwork, so we'll issue payment tomorrow, and then close this out!

**Comment by joekaufmanexpensify** [comment] 2023-08-10 13:04
@ginsuma $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-10 13:06
@situchan $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-10 13:06
@gadhiyamanan $250 sent and contract ended!

**Closed** 2023-08-10 13:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
