### ISSUE TITLE
[CRITICAL] Invite system messages appearing twice in invoice rooms

### ISSUE THREAD

**Issue by davidcardoza** [Expensify/App#42449] opened 2024-05-22 03:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/CSL3XBCCR/p1716319630613119

## Action Performed:
1. Send an invoice to a user
2. Open invoice room
3. Review system messages, the invite system message will sometimes appear twice, but not every time. 

## Expected Result:
There should only be one invite system message. 

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/6643649/06f7e4b5-e8fa-4b62-a324-1c8e0072922c)
![image](https://github.com/Expensify/App/assets/6643649/75789a71-b38b-4c9d-bfda-b39bf767b208)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment] 2024-05-22 10:05
Duplicate of https://github.com/Expensify/App/issues/41854

**Closed by cristipaval** 2024-05-22 10:05 UTC
Labels: Daily, Internal, Bug
