### ISSUE TITLE
[$500]  Wallet - Two default tagged bank account exist after adding the second one

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34774] opened 2024-01-19 00:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Expensify App
2. Log in
3. Navigate to Settings - Wallet
4. Add a bank account for example Chasebank
5. Repeat step 4 with another bank account for example Fidelity

## Expected Result:
Only one Default tagged bank account should exist

## Actual Result:
Default tagged 2 bank account exist after adding the second bank account unless navigate to other page and return

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a41bce4e-72ba-43f4-b65e-f67e050cf87a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df86e2c207d235f0</li>
        <li>Upwork Job ID: 1748142042333646848</li>
        <li>Last Price Increase: 2024-01-19</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28129024</li>
<li>brunovjk | Contributor | 28129025</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-19 00:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wallet - Two default tagged bank account exist after adding the second one

### What is the root cause of that problem?

We forgot to remove the previous default card in `makeDefaultPaymentMethod`.

### What changes do you think we should make in order to solve the problem?


Handle the previous default card and remove it.

**Comment by brunovjk** [comment] 2024-01-19 12:03
I think this is a backend issue.
When add a bank account, `isDeault` is always true:
![image](https://github.com/Expensify/App/assets/95647348/0b954707-810b-4eab-ac4b-4b8266dd68b0)

But seem to don't have a Pusher to return the updated values of `isDeault`, like we get when we navigate to other page and return

**Comment by ikevin127** [comment] 2024-01-19 15:09
# Proposal

## Please re-state the problem that we are trying to solve in this issue

2 bank accounts with Default badge can be seen after adding the second bank account until the user navigates away then opens the Wallet page again or performs refresh on web.

## What is the root cause of that problem?

When we add the first account (eg. Plaid Saving) this has the `isDefault: true` but it is not shown in the UI because of this function:

https://github.com/Expensify/App/blob/2a03320a054f0d9a28cffc1ee96fdde78700218a/src/pages/settings/Wallet/PaymentMethodList.js#L158

which filters the paymentMethods based on if there's any method with accountType `bankAccount` or `debitCard` then returns true if the lenght of the filtered array is > 1. This means that after we add the first account (eg. Plaid Saving) even though it has isDefault: true the badge won't be shown.

When we add the second account (eg. Plaid Checking), this will also be added with isDefault: true and because of the function mentioned above, both of them will display the Default badge since both have isDefault: true and now the filtered array length will be > 1 when called for each item.

## What changes do you think we should make in order to solve the problem?

Within `PaymentMethodList.js` we have the `filteredPaymentMethods` variable which contains the array of payment methods we list. Within this function we have the PaymentUtils.formatPaymentMethods utils function which takes both bankAccount and filteredCardList and returns the `combinedPaymentMethods`.

Add the following changes to the `PaymentUtils.formatPaymentMethods` utils function:
- find the first payment method by created date (when it was added) using 
```javascript
const firstMethodByDate = _.min(bankAccountList, (method) => new Date(method.accountData?.created ?? ''));
```
- if the payment method is found, alter the `isDefault` to only be true for that payment method using 
```javascript
combinedPaymentMethods.push({
        ...bankAccount,
        ...(typeof firstMethodByDate !== 'number' && {isDefault: bankAccount.methodID === firstMethodByDate.methodID}),
        // rest of the code
```

Implementing this change front-end wise ensures that when we add the second account, only one will have the Default badge and that one is the same one that will have the Default badge after Wallet re-fetch.

## Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/6cbade7d-c761-49a5-ae02-00362c929b12

</details>

### I also found some redundant code within `WalletPage.js` while debugging this issue:

```javascript
    useEffect(() => {
        PaymentMethods.openWalletPage();
    }, []);

    // and lower in the component

    useEffect(() => {
        if (network.isOffline) {
            return;
        }
        PaymentMethods.openWalletPage();
    }, [network.isOffline]);
```

and because we have both of them, when we navigate to the Wallet the `'OpenPaymentsPage'` is called twice.

<details>
<summary>OpenPaymentsPage being called twice</summary>

https://github.com/Expensify/App/assets/56457735/420a6640-df00-49b0-8149-2a2ad158ec0b

</details>

The first `useEffect` can be removed safely since the second one will do the job just fine when online.

## What alternative solutions did you explore? (Optional)

The alternative solution for this issue would be to trigger a pusher event when 'AddPersonalBankAccount' endpoint is called that will send the array with the correctly assigned isDefault: true as it happens when the Wallet is re-fetched by navigating away then returning to Wallet or by refreshing on web.

**Comment by MitchExpensify** [comment] 2024-01-19 20:17
Hmm I'm running into a "Missing translation" error when choosing the same Fidelity test account. Did you reproduce successfully @ikevin127 ?

**Comment by ikevin127** [comment] 2024-01-19 20:29
@MitchExpensify Yes I did, both on staging and local dev w/ staging api sandbox toggled on from Preferences.

It works w/ any account (I used gmail) using the sandbox credentials. Fidelity can be replaced w/ City Bank or any other.

If OP video is followed you'll get consistent reproduction of the issue.

**Comment by MitchExpensify** [comment] 2024-01-19 23:34
![IMG_1209B675D831-1](https://github.com/Expensify/App/assets/36425901/579865e0-6be1-462e-b09b-b575a45a512c)

**Comment by MitchExpensify** [comment] 2024-01-19 23:34
I get this no matter what bank I try with

**Comment by ikevin127** [comment] 2024-01-19 23:42
That's weird - most likely it's a generic BE error that doesn't have translation.
Try to reproduce on web maybe you'll have more luck - that's where I did it.

**Comment by s77rt** [comment] 2024-01-20 19:56
@MitchExpensify The missing translation message is something expected for now, it only occurs for expensify.com domain users. But it will be fixed (ref: https://expensify.slack.com/archives/C049HHMV9SM/p1705523289822429?thread_ts=1705435804.140879&cid=C049HHMV9SM)

**Comment by s77rt** [comment] 2024-01-20 21:05
This is a backend issue. Currently the BE always sets the default to the last added bank. If we add 2 banks, first request's response will have isDefault since it's the only one and second request's response will also have isDefault since it's the last added one. I don't know if this is intended, if it's not we can just set isDefault only for the first bank.

🎀 👀 🎀 C+ reviewed

**Comment by stitesExpensify** [comment] 2024-01-24 22:05
I think we should be using the server as the source of truth here. If the bank account comes back as the `isDefault` then all other bank account should not be the default. So I think the solution is to set `isDefault` to false for all other bank accounts in onyx if our response has `isDefault` as true. 

The only solution from the backend would be to always return all bank accounts which seems pretty inefficient

**Comment by brunovjk** [comment] 2024-01-24 22:18
> to set `isDefault` to false for all other bank accounts in onyx if our response has `isDefault` as true.

I will try this approach and update my proposal soon. Thanks @stitesExpensify.

**Comment by s77rt** [comment] 2024-01-25 14:43
@stitesExpensify Why is the server returning `isDefault = true` for newly added banks. We can have the server check if the user already have a default account then we should not set isDefault for the new one. That shouldn't be much work.

**Comment by brunovjk** [comment] 2024-01-25 23:16
Hi @s77rt and @stitesExpensify, I understand your concerns. I've wrote a proposal "_to set `isDefault` to `false` for all other bank accounts in onyx if our response has `isDefault` as true_." I'd love to hear your thoughts on this. Im still woudering about the Pusher, I dont know if make sense here.

**Comment by brunovjk** [comment] 2024-01-25 23:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Presence of two `default` tagged bank accounts after adding the second one in the Wallet section of the Expensify App.

### What is the root cause of that problem?
The root cause of the problem lies in the backend implementation. Currently, when adding a bank account, the backend always sets the default to the last added bank. This leads to discrepancies in the default tagging of bank accounts.

### What changes do you think we should make in order to solve the problem?
To address this issue, we propose modifying the [AddPersonalBankAccountPage](https://github.com/Expensify/App/blob/main/src/pages/AddPersonalBankAccountPage.js) and [addPersonalBankAccount](https://github.com/Expensify/App/blob/main/src/libs/actions/BankAccounts.ts#L154) to update the onyx store by setting `isDefault` to `false` for all other bank accounts if the response from the server indicates that the added bank account should be the default one.
- Update `AddPersonalBankAccountPage`  to fetch a `bankAccountList` from the `onyx` and pass it [here](https://github.com/Expensify/App/blob/ac94dc545a322de63375107e34e1ab31c26eaffe/src/pages/AddPersonalBankAccountPage.js#L75), something like:
    ```
    BankAccounts.addPersonalBankAccount(selectedPlaidBankAccount, bankAccountList);
    ```
- Update `BankAccounts.addPersonalBankAccount` to update the onyx, something like:
    ```
            // ... Existing optimistic data
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: ONYXKEYS.BANK_ACCOUNT_LIST,
                value: {
                    ..._.map(bankAccountList, () => ({ isDefault: false })),
                   [parameters.plaidAccountID]: { isDefault: true },
                },
            },
    ```

### What alternative solutions did you explore? (Optional)

**Comment by stitesExpensify** [comment] 2024-01-26 23:01
> Why is the server returning isDefault = true for newly added banks

This is intended behavior and has been this way for many years :)

The idea is that if you're adding an entirely new bank account, you probably switched banks and want to use the new one for payments/transfers

**Comment by s77rt** [comment] 2024-01-27 20:39
@ikevin127 Thanks for the proposal. Your RCA is correct. However the solution is s a workaround as Onyx will still have `isDefault` set to `true` for both accounts.

**Comment by s77rt** [comment] 2024-01-27 20:45
@brunovjk Thanks for the proposal. Your RCA is correct. Overall the solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34774#issuecomment-1911164240)

**Comment by ikevin127** [comment] 2024-01-27 20:59
Thanks for the review! 🚀

Considering what @stitesExpensify mentioned in their lastest comment I think the solution I proposed will fulfil the expected result of this issue if we were to go fkr a FE fix, in that we won't see 2 `Default` labels at once anymore when adding a new account while already having an existing one.

Upon refresh (calling OpenPaymentsPage) the BE already handles things such that only the latest added account will have the Default badge.

As a bonus to this I will also handle the issue of OpenPaymentsPage being called twice when opening the Wallet.

What do you guys think - should this be handled on the FE side or BE by making the pusher change it such thet once a new account is added w/ isDefault, all the other accounts' isDefault will be set to false ? ✌️


cc @s77rt @MitchExpensify

**Comment by ikevin127** [comment] 2024-01-27 21:30
Thanks for the review! 🚀

@brunovjk gg, make sure to handle the double `OpenPaymentsPage` call mentoned in my proposal 👍

**Comment by ikevin127** [comment] 2024-01-27 21:30
Thanks for the review! 🚀

@brunovjk gg, make sure to handle the double `OpenPaymentsPage` call mentioned in my proposal 👍

**Comment by brunovjk** [comment] 2024-01-28 02:01
@s77rt Thanks for the review, I expect to have PR ready at 02/01 EOD, we can discuss further there.

@ikevin127 Nice catch, should we create another PR for it?

**Comment by ikevin127** [comment] 2024-01-28 02:14
I don't see any issue including it in your PR since I was going to do the same♻️

As long as it's cool w/ the team handling this issue!🚀

**Comment by s77rt** [comment] 2024-01-28 15:30
@brunovjk Please don't raise a PR until being assigned

**Comment by brunovjk** [comment] 2024-01-28 16:54
ok :D thanks

**Comment by mvtglobally** [comment] 2024-01-30 04:59
Issue not reproducible during KI retests. (First week)

**Comment by brunovjk** [comment] 2024-01-30 14:14
> Issue not reproducible during KI retests. (First week)

Strange, I can still reproduce in Staging and in the last 'main'.

**Comment by brunovjk** [comment] 2024-01-31 22:32
PR Ready for Review

**Comment by MitchExpensify** [comment] 2024-02-27 18:31
How is the PR review coming along, @s77rt ?

**Comment by s77rt** [comment] 2024-02-27 18:35
@MitchExpensify The PR is closed. This requires a backend fix. @stitesExpensify will be working on this.

**Comment by brunovjk** [comment] 2024-02-27 18:35
[PR closed](https://github.com/Expensify/App/pull/35523#issuecomment-1925809539) since we are going with a backend solution.
It will also fix another [issue](https://github.com/Expensify/App/issues/35788#issuecomment-1952466682)

**Comment by MitchExpensify** [comment] 2024-02-28 23:13
Ok thanks, and is there any payment due here from your perspective @s77rt ?

**Comment by s77rt** [comment] 2024-02-28 23:28
@MitchExpensify No, no payment is due here

**Comment by brunovjk** [comment] 2024-04-16 20:45
I can still reproduce this issue in staging.

Sorry for the inconvenience @stitesExpensify but how are we with [the solution on the backend](https://github.com/Expensify/App/issues/35788#issuecomment-1952466682)?
The [issue similar](https://github.com/Expensify/App/issues/35788) to this was closed after an internal [discussion ](https://expensify.slack.com/archives/C01GTK53T8Q/p1711426558417769)in Slack, I don't have access, did you discuss anything about this issue here as well? If not, I wonder if it would be a good idea to continue working with @s77rt to implement a solution in FE.
Thank you very much.

**Comment by stitesExpensify** [comment] 2024-04-17 19:42
Yes. Just like that issue, unfortunately I don't think that this can be prioritized right now. Do you agree @MitchExpensify?

**Comment by MitchExpensify** [comment] 2024-04-22 00:31
Agree this isn't important to fix, happy to close

**Closed by MitchExpensify** 2024-04-22 00:31 UTC
Labels: Reviewing, Monthly, Internal, Bug
