### ISSUE TITLE
[$500] mWeb - Login - When magic code page is displayed, many of the page elements are missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37090] opened 2024-02-22 17:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** vdargentotest+mweb022024.2@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:** 

## Action Performed:
1. Go to https://staging.new.expensify.com/r/4098419659819887
2. Navigate to the top of the conversation
3. Tap on sign in
4. Enter an email address and tap on "Continue" button
5. Verify that only the top part of the page is fully visible
6. Tap on any of the input fields
7. Verify that the whole page is now completely visible

## Expected Result:
The magic code page should have all of its elements fully visible without the need to tap on the inputs

## Actual Result
Many of the page elements are missing until an input field is tapped

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1eeb3a96-a0fd-42f0-82e5-64a1c2436d9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acd63de5f6f153b1</li>
        <li>Upwork Job ID: 1760889422764716032</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-22 17:00
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment] 2024-02-23 05:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Login - When magic code page is displayed, many of the page elements are missing
### What is the root cause of that problem?
Regression 
### What changes do you think we should make in order to solve the problem?
Use `isSmallScreenWidth` from `useResponsiveLayout() ` instead  using `shouldUseNarrowLayout` [here](https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/pages/signin/SignInPageLayout/SignInPageContent.tsx#L58)

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-02-23 06:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
mWeb - Login - When magic code page is displayed, many of the page elements are missing
### What is the root cause of that problem?
Regression
### What changes do you think we should make in order to solve the problem?
Revert [this](https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/pages/signin/LoginForm/BaseLoginForm.tsx#L245C1-L261C22) part of code to previous version. Example below
```
  onBlur={() =>
      // This delay is to avoid the validate being called before google iframe is rendered to
      // avoid error message appearing after pressing google signin button.
      setTimeout(() => {
          if (firstBlurred.current || !Visibility.isVisible() || !Visibility.hasFocus()) {
              return;
          }
          firstBlurred.current = true;
          validate(login);
      }, 500)
  }
```
### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-23 06:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we go through the modal sign in flow, we break the layout when hiding the keyboard, and navigating to the next screen. In this ticket for example you can observe they hide the keyboard, and click next. The following page's layout is not adjusted and has green space where the keyboard is supposed to be. This is how the bug is reproduced in the sign in modal ( not scrolling on the report )

### What is the root cause of that problem?
this signin modal has shouldEnableMaxHeight for a layout that changes.. this prevents it from responding to the layout change. 

### What changes do you think we should make in order to solve the problem?
We can remove shouldEnableMaxHeight on the signin modal in order for it to respond to the changes again.

### What alternative solutions did you explore? (Optional)

**Comment by getusha** [comment] 2024-02-23 06:15
> Regression

@shahinyan11 could you specify which PR caused the regression?

**Comment by shahinyan11** [comment] 2024-02-23 06:20
> > Regression
> 
> @shahinyan11 could you specify which PR caused the regression?

Here the [commit](https://github.com/Expensify/App/commit/1bcc02ec155aac3f83fd157aa1ced07652f30270)

**Comment by jeremy-croff** [comment] 2024-02-23 06:22
> onBlur={() =>
>       // This delay is to avoid the validate being called before google iframe is rendered to
>       // avoid error message appearing after pressing google signin button.
>       setTimeout(() => {
>           if (firstBlurred.current || !Visibility.isVisible() || !Visibility.hasFocus()) {
>               return;
>           }
>           firstBlurred.current = true;
>           validate(login);
>       }, 500)
>   }

I'm still able to reproduce it with the rca steps I listed, after reverting this change.

**Comment by shahinyan11** [comment] 2024-02-23 06:35
Sorry my bad. @jeremy-croff  is right , My solution Is not work

**Comment by getusha** [comment] 2024-02-23 06:39
>this signin modal has shouldEnableMaxHeight for a layout that changes.. this prevents it from responding to the layout change.


@jeremy-croff looks like this was present for over 6 months.

**Comment by bernhardoj** [comment] 2024-02-23 06:50
Looks like caused by https://github.com/Expensify/App/issues/33546

Removing `shouldEnableMaxHeight` from `useWindowDimensions` solves the issue
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/components/ScreenWrapper.tsx#L130

**Comment by bernhardoj** [comment] 2024-02-23 07:57
yes, still reproducible on latest main

**Comment by getusha** [comment] 2024-02-28 09:15
@shubham1206agra i believe this PR is awaiting your review https://github.com/Expensify/App/pull/37147

**Comment by getusha** [comment] 2024-03-03 21:18
https://github.com/Expensify/App/pull/37147 merged and deployed to staging

**Comment by mvtglobally** [comment] 2024-03-05 04:50
Issue not reproducible during KI retests. (First week)

**Comment by kadiealexander** [comment] 2024-03-06 23:49
@getusha I think no one is needing payment here as this was a regression of https://github.com/Expensify/App/issues/33546 and was fixed and reviewed by the same people assigned to the OG issue, could you please confirm?

**Closed** 2024-03-12 02:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
