### ISSUE TITLE
[$250] Hybrid - iOS - RHP - RHP does not automatically close after selecting a category or tag

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53029] opened 2024-11-23 17:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisites:
Create a WS, include categories and tags, add 3 tags and categories each. Add to the employee policy. Use the new HT @applause.expensifail.com accounts.

Steps:
1. Open NewDot hybrid app
2. Log in to the employee account
3. Navigate to the WS room
4. Add a manual expense without a tag or category
5. Re-login
6. Navigate to the created expense from step 4
7. Try adding a category and tag

## Expected Result:
RHP should automatically close immediately after selecting a category or tag

## Actual Result:
RHP does not automatically close after the first selection of a category or tag when you re-enter the application.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fbcb1554-68db-43e8-bd5f-085969ca30e1

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861068508801624005</li>
        <li>Upwork Job ID: 1861068508801624005</li>
        <li>Last Price Increase: 2024-11-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by Pujan92** [comment] 2024-11-27 06:46
@isabelastisser  HybridApp issues need to be [internal](https://expensify.slack.com/archives/C02NK2DQWUX/p1732017895367369).

**Comment by isabelastisser** [comment] 2024-12-02 13:09
It is not overdue; waiting for the internal engineering assignment.

**Comment by isabelastisser** [comment] 2024-12-05 20:16
Not overdue.

**Comment by isabelastisser** [comment] 2024-12-09 15:23
Waiting for internal engineering assignment.

**Comment by isabelastisser** [comment] 2024-12-13 03:11
Waiting for internal engineering assignment.

**Comment by mvtglobally** [comment] 2024-12-14 05:05
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-12-18 19:52
@mvtglobally, can you please retest it? thanks!

**Comment by isabelastisser** [comment] 2024-12-20 21:32
### FYI, I will be OOO from Dec 23 to Jan 6, so please reassign the issue to another team member for urgency, IF needed.

**Comment by mvtglobally** [comment] 2024-12-21 02:32
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2024-12-30 04:49
Issue not reproducible during KI retests. (Third week)

**Comment by tgolen** [comment] 2024-12-31 17:25
I am not able to reproduce this either. Closing.

**Closed by tgolen** 2024-12-31 17:25 UTC
Labels: Daily, Internal, Help Wanted, Bug, Hot Pick
