### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Android -  Clicking on different option quickly opens many tabs

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23867] opened 2023-07-29 17:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click at your avatar
2. Click on different option quickly

## Expected Result:
The app should opens only the first clicked option

## Actual Result:
The app opens all the clicked options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/52db78a3-0aba-4e58-ab47-71a6f578efbd

https://github.com/Expensify/App/assets/93399543/b26137c1-3779-4ac9-878b-ab5441510ba1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688707995939759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e037ea65271ad6b</li>
        <li>Upwork Job ID: 1686148949072994304</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26033117</li>
<li>mejed-alkoutaini | Reporter | 26033119</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-07-31 22:57
Was able to repro on Daniel Silva's phone, I wasn't able to via BrowserStack. Seems like an External issue...

**Comment by muxriddinmuqimov77** [comment] 2023-08-01 06:50
Hey @kbecciv  @mananjadhav @mallenexpensify. 
I told this issue a long time ago (Here is the link: https://expensify.slack.com/archives/C049HHMV9SM/p1688707995939759),
but @kbecciv left and said "Not valid bud, device is OOS". It's been happening second time (Maybe more than 2 times) with me so far and I think it's not fair. I have so many bug reports that is left as couldn't reproduce. But These days I'm seeing some of these bug reports on issues list and added to Upwork (Other bug reporter as reporter role) that was already reported by me but left as some reasons. Is this fair?

**Comment by mananjadhav** [comment] 2023-08-03 05:46
Thanks for the proposals folks. I think I am going to post this on slack for discussion and get more 👀 on the approach we should take.

**Comment by mananjadhav** [comment] 2023-08-03 18:09
🎀 👀 🎀 C+ reviewed.

**Comment by kbecciv** [comment] 2023-08-26 14:46
Changed reporter name in GH, sorry confusion.

**Comment by mallenexpensify** [comment] 2023-09-05 02:30
I'm OOO this week so issuing payment a day early

Issue reporter: @muxriddinmuqimov77 paid $250 via Upwork
Contributor: @tienifr paid $1000 via Upwork
Contributor+: @mananjadhav is due $1000 via NewDot

**Comment by mallenexpensify** [comment] 2023-09-05 02:30
@mananjadhav can you fill out the BZ checklist and post here plz?

**Comment by muxriddinmuqimov77** [comment] 2023-09-05 05:33
@mallenexpensify I didn't get paid yet.

**Comment by mananjadhav** [comment] 2023-09-07 18:57
@mallenexpensify This couldn't be pinpointed to a specific PR. This was an lag in the App we fixed by adding a throttling/single thread execution.

Considering this is prevalent more on Android only. I don't think we need regression test steps.

**Comment by JmillsExpensify** [comment] 2023-09-10 11:39
$1,000 approved for payment via NewDot based on BZ summary.

**Comment by youssef-lr** [comment] 2023-09-11 03:25
Not overdue.

**Comment by mallenexpensify** [comment] 2023-09-11 06:35
@muxriddinmuqimov77 I assumed you were the below, is that not correct?  
<img width="339" alt="image" src="https://github.com/Expensify/App/assets/22508304/0c24a871-2564-4714-bc3f-b0d631f7ddc9">

**Comment by muxriddinmuqimov77** [comment] 2023-09-11 06:54
Not it is not me.

2023 sen 11, Dush, 11:35 Matt Allen ***@***.***>:

**Comment by mejed-alkoutaini** [comment] 2023-09-11 15:15
I reported this bug and received the payment for it, but for some reason the reporter changed to someone else, if this requires me to refund the payment, please let me know about the reason first and create a refund request through Upwork. note: the Upwork contract is already closed so not sure how that would work exactly

**Comment by muxriddinmuqimov77** [comment] 2023-09-14 04:28
Hey @mallenexpensify. Any updates?

**Comment by mallenexpensify** [comment] 2023-09-14 08:44
@muxriddinmuqimov77 hired, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~016e037ea65271ad6b
In the future, it's easier/better/faster if you apply via the job link when it's first posted (if you're not auto-hired via API) then for us to extend the job to you then have you accept then we have to pay.

**Comment by mallenexpensify** [comment] 2023-09-14 08:59
@mejed-alkoutaini I figured out the issue!  
This issue was originally created with you as the bug reported. It was then updated to @muxriddinmuqimov77 because they reported the bug before you
<img width="461" alt="image" src="https://github.com/Expensify/App/assets/22508304/2cf2a511-1eed-4736-9658-eadc038391e1">

vs
<img width="541" alt="image" src="https://github.com/Expensify/App/assets/22508304/2edaa51e-6c2e-4914-9a42-55d14c4b6198">

That said... @muxriddinmuqimov77 's bug reported wasn't acted up so, if you hadn't reported the bug again, we wouldn't have fixed it.  Therefore, I think it's fair to compensate for reporting the bug, you don't need to approve the refund I requested.  

reminder to self, payment owed is $250 for @muxriddinmuqimov77 for reporting, I think I hired them for $1000 by mistake.

**Comment by muxriddinmuqimov77** [comment] 2023-09-14 09:22
@mallenexpensify Will you send updated offer or update the amount after I accept the offer?

**Comment by mallenexpensify** [comment] 2023-09-14 09:42
New offer sent for $250 @muxriddinmuqimov77 !

**Comment by muxriddinmuqimov77** [comment] 2023-09-14 12:52
@mallenexpensify Accepted. Thanks!

**Comment by mejed-alkoutaini** [comment] 2023-09-14 13:34
@mallenexpensify I approved the refund 2 days ago, can you create a new milestone for it ?

**Comment by mallenexpensify** [comment] 2023-09-19 06:08
**Final payment recap**
Issue reporter: @mejed-alkoutaini paid $250 via Upwork (reasoning [above](https://github.com/Expensify/App/issues/23867#issuecomment-1719044689))
Issue reporter: @muxriddinmuqimov77 paid $250 via Upwork
Contributor: @tienifr paid $1000 via Upwork
Contributor+: @mananjadhav is due or paid $1000 via NewDot (I'm uncertain which, @JmillsExpensify approved the payment last week) 

@mejed-alkoutaini , I issued you a bonus on the original contract so it should show up for you, thanks for the patience. 

Finally.... @mananjadhav , can you please fill out the BZ [checklist above from above](https://github.com/Expensify/App/issues/23867#issuecomment-1698347370) so we can get this issue closed?

**Comment by mananjadhav** [comment] 2023-09-21 09:19
@mallenexpensify Please check my comment [here](https://github.com/Expensify/App/issues/23867#issuecomment-1710631050). Let me know if you need further information.

**Comment by mallenexpensify** [comment] 2023-09-25 08:27
Thanks @mananjadhav , closing

**Closed by mallenexpensify** 2023-09-25 08:27 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
