### ISSUE TITLE
New Expensify Crashing at Login

### ISSUE THREAD

**Issue by grgia** [Expensify/App#51222] opened 2024-10-22 06:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v9.0.52-0
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**Issue reported by:** @grgia
**Slack conversation:**
https://expensify.slack.com/archives/C049HHMV9SM/p1729574128664629

## Action Performed:
- [ ] Log into any account with magic code or magic code + auth code 

**Note: this does not impact google login**

## Expected Result:
Log in as normal

## Actual Result:
Web App Crashes, user is stuck on "uh oh something went wrong" page

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![image](https://github.com/user-attachments/assets/a3527419-a461-4025-a3ad-e218f70ca7e2)

console errors: 

```
react-dom.production.min.js:188 FirebaseError: Performance: Attribute value  is invalid. (performance/invalid attribute value).
    at je.putAttribute (index.esm2017.js:1165:33)
    at index.web.ts:25:19
    at Array.forEach (<anonymous>)
    at Object.startTrace (index.web.ts:24:32)
    at Object.start (Timing.ts:24:18)
    at ci (AuthScreens.tsx:248:16)
    at fo (react-dom.production.min.js:160:137)
    at vA (react-dom.production.min.js:289:337)
    at Il (react-dom.production.min.js:279:389)
    at pl (react-dom.production.min.js:279:320)
ds @ react-dom.production.min.js:188
Cs.i.componentDidCatch.n.callback @ react-dom.production.min.js:189
Hi @ react-dom.production.min.js:156
yA @ react-dom.production.min.js:260
IA @ react-dom.production.min.js:259
mA @ react-dom.production.min.js:258
(anonymous) @ react-dom.production.min.js:282
El @ react-dom.production.min.js:280
al @ react-dom.production.min.js:269
b @ scheduler.production.min.js:13
k @ scheduler.production.min.js:14
e.exports @ _invoke.js:5
p.<computed> @ _task.js:35
I @ _task.js:21
y @ _task.js:25
Show 15 more frames
Show less
```
```
[alrt] NewExpensify crash caught by error boundary - Performance: Attribute value  is invalid. (performance/invalid attribute value). - {"errorInfo":"{\"componentStack\":\"\\n    at ci (https://staging.new.expensify.com/783-f43f02ecb7442bab801f.bundle.js:1:771247)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at Suspense\\n    at Uo (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:176621)\\n    at h (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:646341)\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:650116\\n    at l (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:689589)\\n    at I (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:692113)\\n    at Yo (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:177081)\\n    at Ka (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:145387)\\n    at pr (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:185756)\\n    at div\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2211971\\n    at i (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:710096)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3255548)\\n    at ae (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:111245)\\n    at ce (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:112234)\\n    at i (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2416759)\\n    at div\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2211971\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2086117\\n    at n (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:1593704)\\n    at T (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3299295)\\n    at A (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2493744)\\n    at c (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2495867)\\n    at r (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2490890)\\n    at i (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2491636)\\n    at T (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2515935)\\n    at h (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:104196)\\n    at s (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:448395)\\n    at v (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:104791)\\n    at i (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2498120)\\n    at D (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:1259424)\\n    at c (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:4102768)\\n    at https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2414777\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at l (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2496670)\\n    at c (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2372623)\\n    at c (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2498803)\\n    at t.default (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3385069)\\n    at t.default (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3382100)\\n    at t.default (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3386440)\\n    at t.default (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3383846)\\n    at y (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3366728)\\n    at C (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3380567)\\n    at ua (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:139317)\\n    at pa (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:144241)\\n    at https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2324994\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at t (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2497633)\\n    at Oa (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:144524)\\n    at I (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:584115)\\n    at div\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2211971\\n    at A (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3530311)\\n    at f (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3531967)\\n    at Sa (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:144625)\\n    at i (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2446114)\\n    at d (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2445462)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at a (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2356999)\\n    at o (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:3348273)\\n    at o (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:710499)\\n    at L (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2358102)\\n    at o (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:710499)\\n    at div\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2211971\\n    at vr (https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:1168588)\\n    at d (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:2323482)\\n    at c (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:435660)\\n    at fr (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:192204)\\n    at Mr (https://staging.new.expensify.com/main-f0c0a855369992decad4.bundle.js:1:192241)\\n    at div\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2211971\\n    at div\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2211971\\n    at https://staging.new.expensify.com/vendors-3add3da828adbc84d4bb.bundle.js:2:2110243\"}"} 
```
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2024-10-22 06:53
Linked to https://github.com/Expensify/App/pull/51176

**Comment by IuliiaHerets** [comment] 2024-10-22 07:59
QA team was logged it already https://github.com/Expensify/Expensify/issues/437892

**Comment by techievivek** [comment] 2024-10-22 08:27
Closing the internal GH since it's a frontend regression.

**Comment by Beamanator** [comment] 2024-10-22 10:23
Fix working well in staging 👍

**Closed** 2024-10-22 14:50 UTC
Labels: Reviewing, Engineering, Weekly, Bug

**Comment by c3024** [comment] 2024-10-23 08:08
@grgia @lakchote 

I helped with the fix. Can bounty be considered here?

**Comment by c3024** [comment] 2024-10-30 14:18
@lakchote @grgia 

Can you please have a look at this [comment](https://github.com/Expensify/App/issues/51222#issuecomment-2431235719) when you get a chance? Thanks!

**Comment by grgia** [comment] 2024-10-30 17:01
> I helped with the fix and tested the PR. Can bounty be considered here?

I tested and pushed the fix to speed things along, so you were a great help with that! This is a weird case since that PR had no C+ and normally we'd have the original author/C+ fix it. Given that, I think $100 is fair for the review of this since we only tested for web. @OfstadC could you please help with C+ review payment to @c3024 for review of https://github.com/Expensify/App/pull/51226.

cc @lakchote

**Comment by OfstadC** [comment] 2024-10-31 13:05
So just to make sure, we are issuing $100 to @cdOut ? No one else needs payment here @grgia ? 😃

**Comment by c3024** [comment] 2024-10-31 13:27
$100 for me. cdOut is from an expert agency.

**Comment by cdOut** [comment] 2024-10-31 13:46
This might be a mistake as I haven't taken part in this issue as far as I remember.

**Comment by OfstadC** [comment] 2024-10-31 16:03
OMG I'm sorry - I tagged the wrong person accidentally 🤦‍♀️

**Comment by OfstadC** [comment] 2024-10-31 18:02
Offer sent here @c3024 - https://www.upwork.com/nx/wm/offer/104682989

**Comment by c3024** [comment] 2024-10-31 18:04
Accepted, thanks!

**Comment by OfstadC** [comment] 2024-10-31 18:06
## Payment Summary 
- Paid @c3024 $100 via Upwork

If payment needs to be issued to anyone else, feel free to ping me 😃
