### ISSUE TITLE
Setting - About - Extra space between components in about page @mdneyazahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10866] opened 2022-09-07 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app
2. Go to Settings
3. Click About

## Expected Result:
There should not be more spacing

## Actual Result:
Extra space between components in about page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.97.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="372" alt="Screenshot 2022-08-23 at 5 32 06 PM" src="https://user-images.githubusercontent.com/93399543/188892512-a56d1624-8efa-4d03-a31b-43c028416f96.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @mdneyazahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661256360362129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-09-07 13:46
### Proposal 

We need to remove styles.mb6 https://github.com/Expensify/App/blob/d037a999e5e20993c6ee3537be338e215654a751/src/pages/settings/AboutPage/AboutPage.js#L79

**Comment by michaelhaxhiu** [comment] 2022-09-14 10:41
I am 99.9% sure this is externally fixable, but let me apply the `engineer` label to make sure.

**Comment by michaelhaxhiu** [comment] 2022-09-14 10:41
PS I just reproduced this issue and it's certainly valid.

**Comment by tgolen** [comment] 2022-09-14 16:36
This is a great external issue and thanks for the early proposal, @Puneet-here. 

@Expensify/design Could you please weigh-in here on what the expected margin should be?

**Comment by shawnborton** [comment] 2022-09-14 16:42
I think this is fine as-is and it's been this way ever since we built this page. So I would vote to just close this one out.

**Comment by michaelhaxhiu** [comment] 2022-09-14 16:49
That's fair, closing for now! 

Note: I know we are all aware of this by now, but saying it juuuuust in case :) - if we feel this should be changed or improved even slightly, then it's worth the effort of paying the $250 for this lil fix.

**Closed by michaelhaxhiu** 2022-09-14 16:49 UTC
Labels: External, Engineering, Daily

**Comment by shawnborton** [comment] 2022-09-14 16:51
Fair point. But I think this is another example of where it would be really helpful to float this into the open source room first for visibility. I understand that's not currently part of Applause's process but I think it should be added.

**Comment by michaelhaxhiu** [comment] 2022-09-15 11:51
When you say float this into the room first, do you mean like have them post in the channel before they create the GH? Or something elsE?
