### ISSUE TITLE
Composer not auto-focused in Android app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18561] opened 2023-05-07 19:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat in chrome mweb
2. Open a chat in Android app

## Expected results: 
composer should be auto-focused and keyboard should open in both
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236698335-097fd6e9-3f57-4593-a716-6ea7e7c3c561.mp4

https://user-images.githubusercontent.com/43996225/236698339-77da98be-5f52-42b6-9162-007ad28ff651.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683393664167919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment] 2023-05-08 09:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer not auto-focused in Android app
### What is the root cause of that problem?
`willBlurTextInputOnTapOutside` in native is `false` while in web it is `true` so that if the chat isn't an empty chat, `autoFocus` is false.
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/libs/willBlurTextInputOnTapOutside/index.native.js#L1
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/pages/home/report/ReportActionCompose.js#L904
### What changes do you think we should make in order to solve the problem?
We should change `willBlurTextInputOnTapOutside` in native to return `true` or change autoFocus to `!this.props.modal.isVisible` If you don't want to blur input if `onTap` outside in native. 

### What alternative solutions did you explore? (Optional)
NA

**Comment by sakluger** [comment] 2023-05-08 18:30
While testing this issue out, I noticed that there is quite a bit of inconsistency around the auto-focus behavior.

- In both the Android and iOS apps, we never auto-focus when opening chats
- In mobile web, we auto-focus when you open a different chat from the LHN
- In mobile web, if you go to the LHN and then return to the same chat you were just in, we do not auto-focus.

I'm going to start a discussion in Slack to see what the expected behavior should be in all these cases.

**Comment by sakluger** [comment] 2023-05-08 19:29
@0xmiroslav thanks I think you're right! Closing this one.

**Closed by sakluger** 2023-05-08 19:29 UTC
Labels: Daily, Bug
