### ISSUE TITLE
Web - LHN - Console error when clicking FAB button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21944] opened 2023-06-30 11:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click on the green plus button (FAB)

## Expected Result:
No console error when clicking FAB button

## Actual Result:
Console error when clicking FAB button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (6)](https://github.com/Expensify/App/assets/93399543/59745158-d5ec-4329-8378-adbb588e33a6)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-06-30 11:17
Console error when clicking on emoji picker,  let me know if we need a separate bug for it. 

![image](https://github.com/Expensify/App/assets/93399543/fdec0147-6290-44ce-bfae-6b245813be1f)

**Comment by alitoshmatov** [comment] 2023-06-30 11:43
**Might be helpful**

Error is originating here: 
https://github.com/Expensify/App/blob/0a39078c39dc2b63ea36176bb061a7683d3d60f9/src/styles/StyleUtils.js#L711-L715

where `bgColor` is not in hexadecimal form but in rgba form, which is causing `hexadecimalToRGBArray` to return undefined.

This function is called here:
https://github.com/Expensify/App/blob/40708cb79964b4c3a09c6e6a671851c343ef6138/src/components/Modal/index.web.js#L33

This value is coming from here:
https://github.com/Expensify/App/blob/722ef008fd6caa8b3d13aa34cf246cf197c1f11f/src/libs/StatusBar/index.web.js#L4-L10

I think this bug was introduced in this PR: https://github.com/Expensify/App/pull/20805

**Comment by situchan** [comment] 2023-06-30 12:06
Dupe of https://github.com/Expensify/App/issues/21833 and already being worked there

**Comment by PauloGasparSv** [comment] 2023-06-30 13:51
> **Issue reported by:** Applause - Internal team

> Dupe of #21833 and already being worked there

Thks team, I'll close this as it is a Duplicate of https://github.com/Expensify/App/issues/21833 (similar to https://github.com/Expensify/App/issues/21952)

Also removing the `DeployBlocker` label from here since it's a regression and it started in https://github.com/Expensify/App/issues/20516

**Closed by PauloGasparSv** 2023-06-30 13:51 UTC
Labels: Engineering, Hourly
