### ISSUE TITLE
[$125] Android- Emojis -Some emojis are blacked out and seen with a square with skin tone in composer

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50929] opened 2024-10-16 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5088056&group_by=cases:section_id&group_order=asc&group_id=229070
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Open any chat.
3. Open the emoji picker.
4. Start scrolling down and verify each emoji is rendered correctly.
5. Select any and emoji that is displayed blacked out. (For example: :palm_up_hand:)
6. Verify the emoji is correctly displayed when added to compose box.

## Expected Result:
All the emojis in compose box should be displayed without any reduced opacity and should be correctly added to compose box when selected.

## Actual Result:
Some emojis are displayed blacked out in compose box and are displayed with a code and a square with the skin tone in compose box, when selected.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f74d99cd-839c-42a2-8523-9c6854db3565

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846719033693258327</li>
        <li>Upwork Job ID: 1846719033693258327</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104551467</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-10-16 17:52
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by teneeto** [comment] 2024-10-17 10:51
Hey! I'm Eto Olei from Callstack. I will like to take a look at this issue. Please assign it to me. Thanks!

**Comment by Anaslancer** [comment] 2024-10-17 21:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Some emojis are blacked out and seen with a square with skin tone in composer

### What is the root cause of that problem?
We are missing some emoji unicodes in the source code.

### What changes do you think we should make in order to solve the problem?
We should put the correct unicode in [here](https://github.com/Expensify/App/blob/04fc4db6b27b629b90dcd5c7dde531d00d3b83ff/assets/emojis/common.ts#L131).

### Contributor details
Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by Anaslancer** [comment] 2024-10-17 21:27
Updated, it works?

**Comment by greg-schroeder** [comment] 2024-10-23 09:07
Assigning to @teneeto from CS

**Comment by Anaslancer** [comment] 2024-10-23 11:24
@akinwale , @greg-schroeder Did you have a chance to review my proposal?

**Comment by Anaslancer** [comment] 2024-10-25 12:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Some emojis are blacked out and seen with a square with skin tone in composer

### What is the root cause of that problem?
We are missing some emoji unicodes in the source code.

### What changes do you think we should make in order to solve the problem?
We should put the correct unicode in [here](https://github.com/Expensify/App/blob/04fc4db6b27b629b90dcd5c7dde531d00d3b83ff/assets/emojis/common.ts#L131).

### What alternative solutions did you explore? (Optional)
If the browser(like Chrome, Safari) can not render the emoji unicode, we can add the svg file instead.

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by Anaslancer** [comment] 2024-10-25 12:02
Submit again [here](https://github.com/Expensify/App/issues/50929#issuecomment-2437599016), because bot says my proposal will be dismissed.

**Comment by teneeto** [comment] 2024-10-28 09:29
Working on this now. will provide more details as I continue.

**Comment by teneeto** [comment] 2024-10-31 07:59
Hi @akinwale, I paused a bit to finalise on another issue. I'll continue with this later today or first thing by tomorrow morning.

**Comment by greg-schroeder** [comment] 2024-11-01 17:16
Thanks @teneeto

**Comment by greg-schroeder** [comment] 2024-11-01 20:36
go away melvin

**Comment by teneeto** [comment] 2024-11-05 08:47
Hey Melvin, I still have an eye on this.

**Comment by teneeto** [comment] 2024-11-06 08:18
Sorry for the delays, but I just got freed up with some capacity to investigate this now. I'm currently investigating this and will share any outcome.

**Comment by teneeto** [comment] 2024-11-07 08:50
https://github.com/user-attachments/assets/85201f41-d157-466b-b5bf-bf91e889e2b7

Can we re-test to confirm this issue still happens? Although I haven't tested on real device (can't get my hands on my android device at the moment), but I did try on simulator and it seems to work perfectly.

**Comment by greg-schroeder** [comment] 2024-11-11 20:26
Pinging QA for a retest

**Comment by greg-schroeder** [comment] 2024-11-11 20:27
Go away melvin

**Comment by greg-schroeder** [comment] 2024-11-13 04:41
I also couldn't reproduce, so I'm going to close this as fixed elsewhere. Please reopen if you're able to reproduce.

**Closed by greg-schroeder** 2024-11-13 04:41 UTC
Labels: External, Daily, Bug, retest-weekly
