### ISSUE TITLE
[$500] [MEDIUM] mWeb – Thread – Missing cursor when start a thread in the request preview of workspace chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30689] opened 2023-11-01 12:37 UTC
On hold for https://github.com/Expensify/App/issues/15992

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Create an expense request in a workspace chat
4. Start a thread in the request preview

## Expected Result:
Cursor is active

## Actual Result:
Missing cursor when start a thread in the request preview of workspace chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/93399543/df604744-ea13-4618-9e34-ffe7ed9c98c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d26fe014dd5d92c1</li>
        <li>Upwork Job ID: 1719695171618611200</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-11-06 15:26
I agree with @bernhardoj; this looks like it's working as-designed. 

@kbecciv if you're seeing this as part of a QA test, could you link to that and I'll reopen and check? Thanks!

**Comment by FitseTLT** [comment] 2023-11-06 15:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose not auto-focusing when a user presses reply in thread on a request preview
### What is the root cause of that problem?
We are already calling the focus function on rely in thread here but the code is doing nothing. 

https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ContextMenu/ContextMenuActions.js#L138-L140
*** This line of code is not working for all cases whether it is a chat or request preview but the reason it is auto focusing for empty chat thread is the autofocus prop passed to `Compose` component (`shouldAutoFocus`) is true because `isEmptyChat` will be true, here
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L127-L128

This is because `focusComposerWithDelay` focuses a textInput ref that is passed to it in here
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L443-L445
which is already set before the user pressed reply in thread and when the user pressed the reply in thread it is navigated to the transaction thread route and the main composer is rerendered leaving the ref passed to `focusComposerWithDelay` pointing to an already unmounted text input so when the focus function is called by `runAfterInteraction` in `focusComposerWithDelay` here
https://github.com/Expensify/App/blob/b8f91a44ef938cb251543f37f9e7037ec090dcbb/src/libs/focusComposerWithDelay.ts#L22-L25
the compose will not focus because `textInput` is refering to the already unmounted text input element belonging to the screen that existed before pressing the reply in thread button 👍  .

### What changes do you think we should make in order to solve the problem?

The solution is to use the appropriate ref pointing to the current Compose text input element in side `focusComposerWithDelay`. And to do that we can use `ReportActionComposeFocusManager.composerRef` that is properly updated to the current compose text input by the ref setter function in `ComposerWithSuggestions` here
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L182-L192
So we will change 
https://github.com/Expensify/App/blob/b8f91a44ef938cb251543f37f9e7037ec090dcbb/src/libs/focusComposerWithDelay.ts#L9-L34
to
```
function focusComposerWithDelay(textInputRef: TextInput | null | undefined): FocusComposerWithDelay {
    /**
     * Focus the text input
     * @param [shouldDelay] Impose delay before focusing the text input
     */
    return (shouldDelay = false) => {
        // There could be other animations running while we trigger manual focus.
        // This prevents focus from making those animations janky.
        InteractionManager.runAfterInteractions(() => {
            const textInput = textInputRef || ReportActionComposeFocusManager.composerRef.current;

            if (!textInput || EmojiPickerAction.isEmojiPickerVisible()) {
                return;
            }

            if (!shouldDelay) {
                textInput.focus();
                return;
            }
            ComposerFocusManager.isReadyToFocus().then(() => {
                if (!textInput) {
                    return;
                }
                textInput.focus();
            });
        });
    };
}
```
And change 
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L444
to 
```
        focusComposerWithDelay()(shouldDelay);
```
as we no longer need to pass the textInput ref in this case. but we will need to pass for `ReportActionItemMessageEdit` as in here
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ReportActionItemMessageEdit.js#L361-L362

Lastly we will change 
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/components/Composer/index.js#L475-L481
to
```
  onFocus={(e) => {
                    if (canFocusInputOnScreenFocus())
                        ReportActionComposeFocusManager.onComposerFocus(() => {
                            if (!textInput.current) {
                                return;
                            }

```
this `onComposerFocus` is called to set the focus callback to fix [this issue](https://github.com/Expensify/App/issues/23898) which is related to focus a problem on web related to `ReportActionItemMessageEdit` losing focus to main composer after press LHN menu item. Hence, the fix will still hold as `canFocusInputOnScreenFocus()` will only exclude native and mWeb. But the reason we add this condition is because when the compose is focused this function is always called setting the wrong focus callback and relpy in thread will still not auto focus the second time we use it as setting the focus callback here will occur the first time we use relpy in thread which will have a successful auto focus 👍 .
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2023-11-06 16:00
@conorpendergrast @bernhardoj @Santhosh-Sellavel the case @bernhardoj [commented](https://github.com/Expensify/App/issues/30689#issuecomment-1789235599) is right when user presses on a request preview because they most probably want to set some fields and the auto focus will have a distrubing UX effect (b/c of the keyboard popup)  but when they select reply in thread they definitely definitely 💯  want to reply with a message on the transaction thread and they expect the compose to be auto focused. And also as I mentioned it in my proposal, the focus code here is just doing nothing 
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ContextMenu/ContextMenuActions.js#L138-L140
so the auto focusing is only working by this line that determines the auto focus prop passed to the `Compose` component.
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L127-L128
So auto focusing is not working for mWeb and native when we press reply in thread if it is a tranaction thread or non empty chat.
I think in both cases the expected behaviour is to auto-focus. And I strongly believe this issue should be fixed 💯  👍 .

**Comment by conorpendergrast** [comment] 2023-11-06 20:47
Hmm, yeah, this is a good point:

> when they select reply in thread they definitely definitely 💯 want to reply with a message on the transaction thread and they expect the compose to be auto focused

Ok, thanks - I agree that this is a behaviour we should change when they choose **Reply in thread**

**Comment by conorpendergrast** [comment] 2023-11-10 15:45
@Santhosh-Sellavel Given my rapid about-turn, does [this proposal work](https://github.com/Expensify/App/issues/30689#issuecomment-1795184581)?

**Comment by Santhosh-Sellavel** [comment] 2023-11-13 14:55
Sorry, I missed this one also unassigning this one due to less bandwidth!

**Comment by conorpendergrast** [comment] 2023-11-16 11:02
[Discussed in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1700132537083979), assigned to @allroundexperts!

**Comment by conorpendergrast** [comment] 2023-11-21 10:12
Yeah, good plan actually @0xmiroslav. Putting on hold for https://github.com/Expensify/App/issues/15992

**Comment by conorpendergrast** [comment] 2023-12-22 21:27
Still held on https://github.com/Expensify/App/issues/15992

**Comment by conorpendergrast** [comment] 2024-01-25 13:40
Same; held on https://github.com/Expensify/App/issues/15992

**Comment by conorpendergrast** [comment] 2024-01-29 16:42
Checking for the right wave, in [this internal channel](https://expensify.slack.com/archives/C05DWUDHVK7/p1706546515972349)

**Comment by muttmuure** [comment] 2024-02-19 15:31
That other issue is closed now, so I assume this can be unheld

**Comment by muttmuure** [comment] 2024-02-23 10:24
@allroundexperts does [this proposal look good to you](https://github.com/Expensify/App/issues/30689#issuecomment-1795184581)?

**Comment by allroundexperts** [comment] 2024-02-23 17:44
@FitseTLT Thanks for your proposal. I think your RCA is accurate and the proposed solution makes sense. However, I'm not able to understand the last part of it fully. Can you elaborate on why the last part is needed?

<img width="842" alt="Screenshot 2024-02-23 at 10 42 55 PM" src="https://github.com/Expensify/App/assets/30054992/7f44315f-e300-45a8-afcb-8bd1c0b27ef5">

**Comment by FitseTLT** [comment] 2024-02-23 17:51
@allroundexperts Without that part you can successfully auto focus on reply in thread after a fresh opening of the app (after refresh of the page) but after this first auto-focus the code here 
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/components/Composer/index.js#L473-L478
will reset our callback so now the auto-focus will not work except of course you refresh the page again. the code was added to solve the issue I already linked in my proposal but it should be applied for main composer it is only meant for `ReportActionItemMessageEdit`.

**Comment by FitseTLT** [comment] 2024-02-23 18:01
> Gotcha. I just applied the changes and its still not working for me. @FitseTLT Can you share a branch with the changes so I can test before giving a 👍 ?

Yep I think that's better

**Comment by FitseTLT** [comment] 2024-02-23 18:24
Here it is https://github.com/FitseTLT/App/tree/fix-auto-focus-on-reply-in-thread

**Comment by allroundexperts** [comment] 2024-02-25 18:38
Thanks for sharing the link @FitseTLT. 

@FitseTLT's [proposal](https://github.com/Expensify/App/issues/30689#issuecomment-1795184581) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by muttmuure** [comment] 2024-02-28 17:07
@FitseTLT please raise your PR when you are ready

**Comment by FitseTLT** [comment] 2024-03-04 11:57
Pr will be ready in 2 days

**Comment by muttmuure** [comment] 2024-03-07 11:49
@FitseTLT how are we doing?

**Comment by FitseTLT** [comment] 2024-03-07 11:51
Sorry @muttmuure will make it ready by EOD

**Comment by muttmuure** [comment] 2024-05-08 08:02
Old job expired. @FitseTLT I've sent you a new offer here: https://www.upwork.com/nx/wm/offer/102214608

**Comment by muttmuure** [comment] 2024-05-08 08:02
$500 to @allroundexperts for C+

**Comment by FitseTLT** [comment] 2024-05-08 19:37
@muttmuure Accepted the new offer

**Comment by FitseTLT** [comment] 2024-05-13 19:29
bump @muttmuure

**Comment by FitseTLT** [comment] 2024-05-15 17:33
bump for payment @muttmuure

**Comment by FitseTLT** [comment] 2024-05-22 17:22
bump for payment @muttmuure

**Comment by FitseTLT** [comment] 2024-06-06 15:47
bump @muttmuure for my payment pls

**Comment by muttmuure** [comment] 2024-06-12 09:30
Sorry, handling now

**Comment by muttmuure** [comment] 2024-06-12 09:31
Paid up

**Closed by muttmuure** 2024-06-12 09:31 UTC
Labels: Reviewing, Weekly, Bug
