### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250]  A newly created workspace's room crashes on the details page.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44410] opened 2024-06-25 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719335250993669

## Action Performed:
1. Create a new workspace and navigate to LHN.
2. Press FAB -> Start chat -> # Room.
3. Add a room name and select the newly created workspace.
4. Press the "Create room" button.
5. On the workspace room, press the header to navigate to the details page.
## Expected Result:
Room Details page should be loaded

## Actual Result:
Room Details page crashed
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/abfe7f15-f403-4f50-8426-2b978fc0c611

![Snip - New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/c1037c52-2d19-47db-9745-c732651ae54f)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c68edfdc6e18287a</li>
        <li>Upwork Job ID: 1806385412672282404</li>
        <li>Last Price Increase: 2024-06-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by bernhardoj** [comment] 2024-06-26 03:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Create a new room and open the details page will crash the app.

### What is the root cause of that problem?
As shown in the error log, the issue is the onyx key is changed from a collection key (report_) to a collection member key (report_-1). 
https://github.com/Expensify/App/blob/8f3e925d8044526f60669f06c2010842242c9511/src/pages/ReportDetailsPage.tsx#L82

Creating a new room will optimistically set the `parentReportID` to an empty string (the param before description).
https://github.com/Expensify/App/blob/8f3e925d8044526f60669f06c2010842242c9511/src/pages/workspace/WorkspaceNewRoomPage.tsx#L109-L123
https://github.com/Expensify/App/blob/8f3e925d8044526f60669f06c2010842242c9511/src/libs/ReportUtils.ts#L4580-L4581

Because it's an empty string, the onyx key becomes `report_`. The add workspace room API will later return the parentReportID as null which is to clear it from the onyx, so now, the onyx key becomes `report_-1`.

### What changes do you think we should make in order to solve the problem?

We can optimistically set the `parentReportID` to `null`,

OR

Use `||` instead of `??`.
https://github.com/Expensify/App/blob/8f3e925d8044526f60669f06c2010842242c9511/src/pages/ReportDetailsPage.tsx#L82

**Comment by jayeshmangwani** [comment] 2024-06-26 05:53
@johncschuster This issue is happening on staging and not on production; it is a deploy blocker

**Comment by mountiny** [comment] 2024-06-27 21:33
We need to pay $50 to @bernhardoj for identifying the fix

**Comment by johncschuster** [comment] 2024-07-08 14:14
# Payment Summary:
Contributor: @jayeshmangwani  - $250 - paid via Manual request (to be paid on/after July 10)
Bug Bounty: @bernhardoj - $50 - [paid via Upwork](https://www.upwork.com/nx/wm/offer/103031492) (see [comment](https://github.com/Expensify/App/issues/44410#issuecomment-2195698954) for decision to pay Bug Bounty)

**Comment by jayeshmangwani** [comment] 2024-07-08 14:18
> Contributor: @jayeshmangwani - $250 - paid via Manual request (to be paid on/after July 10)

@johncschuster No payment for me here, as I haven't reviewed the PR

**Comment by mountiny** [comment] 2024-07-08 21:11
Correct, only @bernhardoj

**Comment by mallenexpensify** [comment] 2024-07-09 00:50
Desktop is crashing when I click the header. I'm assuming it's a different bug but wanted to check here first. 


https://github.com/Expensify/App/assets/22508304/8dcc9c9a-d198-4fdb-a154-4630cd4033fe



Logs
[logs-2024-07-09 00_46_30.733.txt](https://github.com/user-attachments/files/16135689/logs-2024-07-09.00_46_30.733.txt)

**Comment by johncschuster** [comment] 2024-07-09 14:12
Thanks, @jayeshmangwani! I've updated the payment summary comment and will issue payment now since a bug bounty shouldn't be held on a deploy.

**Comment by bernhardoj** [comment] 2024-07-09 17:33
Requested in ND.

**Comment by johncschuster** [comment] 2024-07-09 17:56
Great! I've updated the comment above to reflect you will be paid via ND instead of Upwork. Thank you!

**Comment by JmillsExpensify** [comment] 2024-07-09 21:26
$50 approved for @bernhardoj

**Comment by mountiny** [comment] 2024-07-10 15:09
It's hard to say; the logs are not that helpful in case of a crash like this.

@mallenexpensify remember that anytime you get this crash, open the console and the reason for the crash will be written there, the logs shared are not the same. 

I think we can proceed and the crash should be reported in bug channel showing the console too

**Comment by johncschuster** [comment] 2024-07-11 14:32
I think Melvin is wrong about @bernhardoj's contributions (They identified a fix. I don't think they reviewed any PRs - checking on that.)

**Comment by bernhardoj** [comment] 2024-07-11 14:45
Yes, I don't review any PR. The payment is also already [approved](https://github.com/Expensify/App/issues/44410#issuecomment-2218759892).

**Comment by mallenexpensify** [comment] 2024-07-12 01:01
> remember that anytime you get this crash, open the console and the reason for the crash will be written there, the logs shared are not the same.

Thanks @mountiny , I was uncertain about this, kinda assumed we'd share errors in the logs we'd be sharing. I'll update the BZ team tomorrow too when I do an EOW post.

**Comment by johncschuster** [comment] 2024-07-12 13:52
Thanks @bernhardoj and @mallenexpensify! Ok, it sounds like we can close this then. Please let me know if I'm wrong!

**Closed** 2024-07-12 13:53 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
