### ISSUE TITLE
[$250] Chat - No unread marker when messages are marked unread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47375] opened 2024-08-14 04:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Send a few messages.
4. Mark any message as unread.

## Expected Result:
There will be unread marker.

## Actual Result:
There is no unread marker.
In self DM, when marking messages as unread, LHN report is not bolded.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5069cde6-c04f-49d0-b10d-ac6e004b692b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ccdc0ad6595b0550</li>
        <li>Upwork Job ID: 1823596684825360821</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103518252</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by IuliiaHerets** [comment] 2024-08-14 04:45
We think that this bug might be related to #vip-vsb

**Comment by nkdengineer** [comment] 2024-08-14 05:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no unread marker.
In self DM, when marking messages as unread, LHN report is not bolded.

### What is the root cause of that problem?
We return early if the report action comes from the current user here. It comes from this [PR](https://github.com/Expensify/App/pull/45797)

https://github.com/Expensify/App/blob/b7f7f1b4f36451b4e3a763ac717e1c8fd645ee5a/src/pages/home/report/ReportActionsList.tsx#L225-L228

In the past, we only checked this condition if `messageManuallyMarkedUnread` is `undefined`


### What changes do you think we should make in order to solve the problem?
We should bring `messageManuallyMarkedUnread` back and update the condition to check the unread as we do in the past [here](https://github.com/Expensify/App/pull/45797/files)

https://github.com/Expensify/App/blob/b7f7f1b4f36451b4e3a763ac717e1c8fd645ee5a/src/pages/home/report/ReportActionsList.tsx#L225-L228

### What alternative solutions did you explore? (Optional)
NA

**Comment by hungvu193** [comment] 2024-08-14 05:35
Reviewing shortly

**Comment by hungvu193** [comment] 2024-08-14 05:43
I agree with @nkdengineer proposal. Let's bring 
`messageManuallyMarkedUnread` back.

🎀 👀 🎀

**Comment by nkdengineer** [comment] 2024-08-14 06:24
Thanks, will raise a PR soon.

**Comment by nkdengineer** [comment] 2024-08-14 08:40
@hungvu193 The PR is [here](https://github.com/Expensify/App/pull/47393).

**Comment by hungvu193** [comment] 2024-08-14 08:42
Thanks. I'll review it shortly

**Comment by hungvu193** [comment] 2024-09-10 09:21
I think this issue is due for payment @kevinksullivan

**Comment by kevinksullivan** [comment] 2024-09-12 19:31
@hungvu193 did we get the regression this caused fixed, though?

**Comment by kevinksullivan** [comment] 2024-09-12 19:31
Looping in another BZ for your response as I am going OOO.

**Comment by hungvu193** [comment] 2024-09-13 07:24
> @hungvu193 did we get the regression this caused fixed, though?

I think it's fixed, I can seem to reproduce https://github.com/Expensify/App/issues/47481

https://github.com/user-attachments/assets/2413fd35-481a-4b53-9323-edc07b8d4885

**Comment by hungvu193** [comment] 2024-09-19 08:49
little bump @lschurr for the payment summary 😄

**Comment by lschurr** [comment] 2024-09-19 16:39
@iwiznia are you able to weigh in here? [Your comment](https://github.com/Expensify/App/issues/47375#issuecomment-2291708395) indicates that [the PR](https://github.com/Expensify/App/pull/47393) caused a regression, and that GH is still open: https://github.com/Expensify/App/issues/47481#top

**Comment by iwiznia** [comment] 2024-09-20 13:20
Applause said: 

> Issue was found when executing this PR https://github.com/Expensify/App/pull/47393

If it was not that PR, what caused the regression?

**Comment by nkdengineer** [comment] 2024-10-01 03:47
@iwiznia The current RCA of https://github.com/Expensify/App/issues/47481 comes from https://github.com/Expensify/App/pull/45797 because we don't return early in `shouldDisplayNewMarker` if we already have a unread marker.

**Comment by hungvu193** [comment] 2024-10-03 06:34
@lschurr Can you please post the payment summary here so we can close this one?

**Comment by lschurr** [comment] 2024-10-07 13:34
Payment summary:

- Contributor: $250 @nkdengineer ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38140694/overview))
- Reviewer: $250 @hungvu193 (please request in NewDot)

**Closed by lschurr** 2024-10-07 13:34 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by garrettmknight** [comment] 2024-10-08 18:20
$250 approved for @hungvu193
