### ISSUE TITLE
Web - Group participants missing for around 10-15 seconds after creating a new group DM

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21862] opened 2023-06-29 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in to New Expensify
2. Click the FAB > New Group
3. Enter the emails of 3 new users and create the group
4. Observe the group description

## Expected Result:
The group description should show the group participants' contact methods, and their avatars

## Actual Result:
The group contact participants' contact methods and avatars are all missing around around 10-15 seconds before finally appearing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] W / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (1)](https://github.com/Expensify/App/assets/93399543/9f5dcb24-eb4f-4f5b-8faf-9c9e91d8becb)
![image](https://github.com/Expensify/App/assets/93399543/f88fb727-195b-47f5-9e25-e49be838e011)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @S0W0A0T1
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687940833661759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2023-06-29 23:45
Hey @kbecciv, a few questions/comments:

1. I'm not able to reproduce this, the avatars flash for a fraction of a second, but then show up immediately
2. In the platforms section, you checked `W / Chrome`. What does `W` mean? I haven't seen that referenced before in platforms.

**Comment by sakluger** [comment] 2023-06-30 00:14
Ah, I see it's MacOS desktop. I'll update the description and try testing again.

**Comment by sakluger** [comment] 2023-07-01 00:28
I can't reproduce this at all, the group member details show up right away in all platforms for me.

**Comment by sakluger** [comment] 2023-07-01 00:32
Closing for now, I commented in the Slack thread asking for more details and we can reopen if we're able to reproduce.

**Closed by sakluger** 2023-07-01 00:32 UTC
Labels: Daily, Bug

**Comment by conorpendergrast** [comment] 2023-07-06 20:30
Assigning to myself to reproduce!

**Comment by conorpendergrast** [comment] 2023-07-10 14:09
I tried to reproduce, and this isn't happening again now. Closing!
