### ISSUE TITLE
[$500] iOS - Login - Visual flickering above the OS keyboard when typing in the login field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33338] opened 2023-12-20 10:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open the native app on iOS
2. Type email/phone in the login input field
3. Observe the flickering above the keyboard [if the flickering does not happen, background the app and reopen it]

## Expected Result:
No visual issue/flickering when typing in the login field

## Actual Result:
Visual flickering happen while typing the email/phone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6320389_1703024913225!Screen_Shot_2023-12-20_at_1 28 00_AM](https://github.com/Expensify/App/assets/115492554/d63643ae-f08b-453f-8353-222fd57e7c1b)

https://github.com/Expensify/App/assets/115492554/1e4ca0ac-65b1-4665-b7c9-08308527cf04

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190fa15c0c22e9427</li>
        <li>Upwork Job ID: 1737420927155322880</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-12-20 11:00
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Visual flickering of the keyboard is occuring while typing in the Phone or email field.

## What is the root cause of that problem?

As per https://github.com/facebook/react-native/issues/39411#issuecomment-1726601414

> It appears to be that at some point recently (pre iOS 17) a bug was introduced. Whenever secureTextEntry={false} and textContentType is set, various Text Input changes (typing, focus, etc...) will fire a native keyboardWillChangeFrame event that causes the keyboard to re-render.

## What changes do you think we should make in order to solve the problem?

Change the `BaseLoginForm.js` components [iOS only](https://reactnative.dev/docs/textinput#textcontenttype-ios) `textContentType` prop to `emailAddress`.

## Videos

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/56457735/e160f684-6855-44b9-b117-d1e816a6c290

</details>

**Comment by kameshwarnayak** [comment] 2023-12-21 04:49
I am not able to recreate this in the current main. I am using a simulator to test this. Should I test this GH issue on any particular iOS version?

**Comment by zanyrenney** [comment] 2023-12-22 13:20
I also can't reproduce this.

**Comment by zanyrenney** [comment] 2023-12-22 13:23
https://github.com/Expensify/App/assets/56830058/b9d48421-cece-4988-ab58-fb3fbe8977cd

closing as can't be reproduced.

**Comment by kbecciv** [comment] 2023-12-26 17:12
Issue is reproduced on build 1.4.17.1

https://github.com/Expensify/App/assets/93399543/e83a41e6-ed07-49a6-afbe-a82f0f6f6a89

**Comment by mvtglobally** [comment] 2024-01-03 05:50
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment] 2024-01-08 11:53
Thanks @fedirjh I agree. Closing!

**Closed by zanyrenney** 2024-01-08 11:53 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by fahadjaved1994** [comment] 2024-01-12 15:20
Greetings,

I encountered a similar issue with my client app, attributing it to iOS 17.1. However, I have successfully addressed the flickering problem in React Native. To provide clarity, I have attached a video demonstrating the issue and its subsequent resolution.

Should you require further details or assistance, please do not hesitate to reach out.

Flickering issue: https://github.com/Expensify/App/assets/34941166/cd3dbe30-7bbd-4f87-9e10-af6ccaec5fe2
Flickering fixed: https://github.com/Expensify/App/assets/34941166/b9156a24-6824-444b-810f-d7fdf245dd76
