### ISSUE TITLE
[$500]  Room - Web - Header shows changed Room name & room name on composer unchanged room name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35419] opened 2024-01-30 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline
2. Create a room
3. Change the name of the room
4. Take a note of room name on header and room name above the composer

## Expected Result:
Room name should be consistent

## Actual Result:
Inconsistency in Room name preview when change in offline mode.
Header shows changed Room name while room name above composer shows the first unchanged room name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/59607c7b-d624-4879-97b4-0b565af8ad41

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1afbac3cc3b8deb</li>
        <li>Upwork Job ID: 1752383443231072256</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28150301</li>
<li>esh-g | Contributor | 28150302</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-30 17:29
We think that this bug might be related to #vip-vsp. 
CC @quinthar

**Comment by esh-g** [comment] 2024-01-30 17:32
# Proposal

## Root cause
We are memoizing the `ReportActionItemCreated` component incorrectly.

## What changes should be made to fix this?
We should check if `report.name` changed in the memo

**Comment by adelekennedy** [comment] 2024-02-05 16:37
@Gonals will you review the [selected proposal?](https://github.com/Expensify/App/issues/35419#issuecomment-1921142521)

**Comment by adelekennedy** [comment] 2024-02-06 17:57
we have a selected proposal - just waiting for engineer review

**Comment by esh-g** [comment] 2024-03-04 15:54
@adelekennedy I think the payments for this issue are pending. The PR was deployed to prod 3 weeks ago.

**Comment by adelekennedy** [comment] 2024-03-04 16:11
@esh-g thank you! It looks like the automation failed for updating the title - settling payments now

**Comment by adelekennedy** [comment] 2024-03-04 16:17
@Ollyws it looks like you haven't accepted the offer on Upwork, once you do I can remit payment and will you take a look at the checklist below?

;;BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by adelekennedy** [comment] 2024-04-26 17:52
So sorry!! Paying this out now

**Closed** 2024-04-26 17:58 UTC
Labels: Reviewing, External, Monthly, Bug
