### ISSUE TITLE
[$500] Private Note - The note is not immediately saved, and the previous value persists

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28867] opened 2023-10-04 21:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.
2. Open any chat
3. Click on the header and go to Private notes
4. Go to My note > Notes
5. Add "test.in" and save.
6. Click on Notes > remove "test.in" and save.
7. Observe that the word briefly appears before being deleted.

## Expected Result:
The note should be immediately updated, and "test.in" should be removed upon saving

## Actual Result:
The previous value "test.in" briefly appears before being removed upon saving

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ebb3cb6b-cf25-4920-888f-91a5000530c0

https://github.com/Expensify/App/assets/93399543/7391c4fe-e753-46ba-a364-2f241acda3c2

https://github.com/Expensify/App/assets/93399543/12614511-96e9-4b0d-aa26-d0d66bb02c94

https://github.com/Expensify/App/assets/93399543/c1109200-608b-4bb2-9470-ca5d3dd9ba62

https://github.com/Expensify/App/assets/93399543/a458405c-7eb4-4709-b024-3839c29b0cb2

https://github.com/Expensify/App/assets/93399543/7104d664-bfe0-40c1-8d15-a430394b9751

https://github.com/Expensify/App/assets/93399543/bfc96af2-0003-402b-83d3-ec7aeb0b5f9d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696355362642349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7cb43c2f11fb8f9</li>
        <li>Upwork Job ID: 1709687858871480320</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-10-04 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private Note - The note is not immediately saved, and the previous value persists
### What is the root cause of that problem?

We render the links/html with a parent tag `comment` at all other places which does the work of adding required CSS styles/rendering.

Whereas at the `MenuItem` we're not doing it.

https://github.com/Expensify/App/blob/4975bcaed29845fcf9122bad33694fb9d0d5e307/src/pages/home/report/ReportActionItemFragment.js#L113

https://github.com/Expensify/App/blob/4975bcaed29845fcf9122bad33694fb9d0d5e307/src/components/MenuItem.js#L258


### What changes do you think we should make in order to solve the problem?

We need to wrap the title here 
https://github.com/Expensify/App/blob/4975bcaed29845fcf9122bad33694fb9d0d5e307/src/components/MenuItem.js#L258
 with `<comment>` tag which does add the required changes.

### What alternative solutions did you explore? (Optional)
NA

<img width="377" alt="Screenshot 2023-10-05 at 3 35 15 AM" src="https://github.com/Expensify/App/assets/59088937/4249eeb0-d89a-4551-99a9-bfec9f1f03c2">


https://github.com/Expensify/App/assets/59088937/c44a2607-44c1-46ca-a693-c62e8ab23302

**Comment by b4s36t4** [comment] 2023-10-04 22:13
Maybe some PR got merged which did resolved the issue.

**Comment by MaciejSWM** [comment] 2023-10-05 12:41
+1 I can't reproduce on fresh main but was able to reproduce on main from 2 days ago or so.

**Closed** 2023-10-06 22:42 UTC
Labels: External, Daily, Help Wanted, Bug
