### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] [Dupe detection] Tax field does not show the "Default" label on the confirmation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47975] opened 2024-08-24 22:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Track tax is enabled in Workspace settings > Distance rates > Settings.
- Distance rate has Tax rate and Tax reclaimable fields populated.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two same distance expenses with the same distance rate that has tax rate and tax reclaimable on.
4. Go to transaction thread of any submitted expense.
5. Note that Tax field has the "Default" label.
5. Click Review duplicates.
6. Click Keep this on (any).
7. Proceed to confirmation page.

## Expected Result:
Tax field will show the "Default" label on the confirmation page.

## Actual Result:
Tax field does not show the "Default" label on the confirmation page and instead shows "None" 

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ea6e4514-e527-4b48-9f17-21a88c6c7d21

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017284a9effe70faa8</li>
        <li>Upwork Job ID: 1828590697351581643</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104974640</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment] 2024-08-24 22:12
We think that this bug might be related to  #wave-control

**Comment by IuliiaHerets** [comment] 2024-08-24 22:13
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment] 2024-08-28 00:29
updated the repro steps slightly -- actual result shows `None` instead of the expected default rate.

**Comment by trjExpensify** [comment] 2024-08-28 00:33
and another one! CC: @dylanexpensify @pecanoro @parasharrajat @kubabutkiewicz

**Comment by pecanoro** [comment] 2024-08-29 08:42
@alitoshmatov Could you review the proposals when you have some time?

**Comment by pecanoro** [comment] 2024-08-29 12:33
Putting a HOLD here for now since it seems to be the same as https://github.com/Expensify/App/issues/47974

**Comment by pecanoro** [comment] 2024-08-30 09:46
I still think we should wait since the proposals are really similar, and they will need to be updated accordingly.

**Comment by stephanieelliott** [comment] 2024-09-11 02:42
Still holding on https://github.com/Expensify/App/issues/47974

**Comment by stephanieelliott** [comment] 2024-09-17 02:34
Still holding on https://github.com/Expensify/App/issues/47974

**Comment by pecanoro** [comment] 2024-09-17 15:22
Still holding

**Comment by stephanieelliott** [comment] 2024-09-25 19:24
Still holding on https://github.com/Expensify/App/issues/47974

**Comment by stephanieelliott** [comment] 2024-10-03 23:31
Im not able to reproduce this anymore -- can anyone else repro?

**Comment by stephanieelliott** [comment] 2024-10-09 00:02
Ok @Krishna2323 can you make any necessary updates to [your proposal](https://github.com/Expensify/App/issues/47975#issuecomment-2308874978), then let us know when it's ready so @alitoshmatov can review?

**Comment by stephanieelliott** [comment] 2024-10-11 04:37
Bump on the above @Krishna2323, did still want to work on this?

**Comment by stephanieelliott** [comment] 2024-10-16 06:17
Hey @Krishna2323 have you had a chance to update the proposal?

**Comment by stephanieelliott** [comment] 2024-10-26 01:05
> Hey @alitoshmatov can you review the updated proposal? https://github.com/Expensify/App/issues/47975#issuecomment-2308874978

Bump @alitoshmatov

**Comment by pecanoro** [comment] 2024-10-29 18:56
I am going to add the HOLD again until this one is merged since it will likely create conflicts: https://github.com/Expensify/App/pull/48958

**Comment by stephanieelliott** [comment] 2024-11-12 21:11
The blocking PR was deployed to prod yesterday. 

Taking off hold -- @alitoshmatov can you review the updated proposal? https://github.com/Expensify/App/issues/47975#issuecomment-2308874978

**Comment by pecanoro** [comment] 2024-11-18 15:56
@alitoshmatov Any updates?

**Comment by alitoshmatov** [comment] 2024-11-19 15:56
@Krishna2323 's proposal has correct RCA and solution also works. I think we can proceed with his proposal

C+ reviewed 🎀 👀 🎀

**Comment by pecanoro** [comment] 2024-11-19 18:09
@Krishna2323 Assigning you to the issue!

**Comment by stephanieelliott** [comment] 2024-11-26 05:20
Hey @alitoshmatov the PR is blocked on your review, can you take a look? https://github.com/Expensify/App/pull/52928

**Comment by alitoshmatov** [comment] 2024-12-10 19:58
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by stephanieelliott** [comment] 2024-12-11 01:05
Summarizing payment on this issue: 

 - Contributor: @Krishna2323 $250 via Upwork - PAID! 
 - Contributor+: @alitoshmatov $250 via ND - Please request! 
 
 Upwork job is here: https://www.upwork.com/jobs/~017284a9effe70faa8

**Closed by stephanieelliott** 2024-12-11 01:05 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-12-11 13:31
$250 approved for @alitoshmatov
