### ISSUE TITLE
IOU - It is not possible to select ‘Pay Elsewhere’ for payment in IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22855] opened 2023-07-14 00:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Mobile Chrome and go to staging.new.expensify.com
2. Login with any account
3. Open any thread with unpaid IOU
4. Select ‘Pay Elsewhere’ in payment methods

## Expected Result:
User can select "Pay elsewhere" in the payment methods

## Actual Result:
Selected "Pay Elsewhere" immediately reverts to "Pay with Expensify"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/78819774/4f9da1a3-c5b1-4449-b6cb-9c7aba292ff8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by zanyrenney** [comment] 2023-07-19 15:04
which device did you test this on ? @lanitochka17 ? i see the solution from @tienifr is for iOS but the OP says this occured on Android. Which device please so i can repro?

**Comment by zanyrenney** [comment] 2023-07-21 10:17
bump @lanitochka17 is this android or iOS, I can't reproduce on iOS.

**Comment by lanitochka17** [comment] 2023-07-21 20:54
@zanyrenney The Issue is reproduced on phones:
 Google Pixel 5 / Chrome
 Samsung Galaxy A32 / Chrome

**Comment by zanyrenney** [comment] 2023-07-24 16:08
Hmm i can't reproduce this on those devices on browserstack. It looks like there is a [PR elsewhere](https://expensify.slack.com/archives/C049HHMV9SM/p1689796892089749?thread_ts=1689718847.632719&cid=C049HHMV9SM) for this so I am going to close this out for now!

**Closed by zanyrenney** 2023-07-24 16:08 UTC
Labels: Daily, Overdue, Bug
