### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Tap with two fingers on Mark as done button opens assignee screen

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24192] opened 2023-08-07 02:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB -> Create task for someone
2. Go to task details -> Tap Mark as done button with two Fingers
Or
Tap and hold button click and Tap with other finger

## Expected Result:
It should not redirect to other screen & Button UI should stay single focus

## Actual Result:
1. It redirects to Assignee screen
2. Button darks out twice

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [X] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.50-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43995119/86266fc5-22d5-4089-ba86-6a9634e5e70c

https://github.com/Expensify/App/assets/43995119/617e0a83-c9f4-4ccd-acb5-9cd4db2266b6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690837745266379 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01828e7b9a9852bda3</li>
        <li>Upwork Job ID: 1688641968597434368</li>
        <li>Last Price Increase: 2023-08-07</li>
    </ul>
</details>

**Comment by Thanos30** [comment] 2023-08-08 08:53
@jasperhuangg Is there a reason behind the wrapping of the button with `PressableWithFeedbackin` in the `TaskHeaderActionButton` file?

I see the PR was created by you about a month ago, I just wanted to clarify the purpose of it in order to come up with a solution.

Thanks 🙏

**Comment by mollfpr** [comment] 2023-08-08 11:24
It looks like a regression from the task detail redesign PR https://github.com/Expensify/App/pull/20841.

IIRC, before the redesign, we can click the task header to assign a user to the task and the component used to wrap the display name and avatar. So it might be Jasper forget to remove the `PressableWithFeedback` for that.

As mentioned in @bernhardoj's proposal, I think we can safely remove it. Let's go with @bernhardoj [proposal](https://github.com/Expensify/App/issues/24192#issuecomment-1667201488) then.


🎀 👀 🎀 C+ reviewed!

**Comment by SosenWiosen** [comment] 2023-08-08 11:28
I agree with @bernhardoj that we should delete it. It looks like the Button to Mark as done was added in affa78c and @jasperhuangg just forgot to delete the PressableWithFeedback.

**Comment by ayazhussain79** [comment] 2023-08-10 19:02
@mollfpr can you please check this one we just need to remove onPress that is used in PressableWithFeedback
here was my bug with the solution:
https://expensify.slack.com/archives/C049HHMV9SM/p1691067227577719

### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Clicking the "Mark as Done" button opens the assignee page
### What is the root cause of that problem?
The issue seems to originate from the TaskHeaderActionButton.js file, specifically due to an extra onPress function that is causing the problem.
### What changes do you think we should make in order to solve the problem?
To resolve this issue, we need to remove the problematic onPress function:
`onPress={() => Navigation.navigate(ROUTES.getTaskReportAssigneeRoute(props.report.reportID))}`
### What alternative solutions did you explore? (Optional)

**Comment by ayazhussain79** [comment] 2023-08-10 19:04
you can open assignee page by clicking near to the Mark as done button
![Screenshot 2023-08-03 at 8 54 38 PM (1)](https://github.com/Expensify/App/assets/56740856/07a6bafe-0c43-4643-bc77-e00dfb8472c5)


![Screenshot 2023-08-03 at 8 36 35 PM (1)](https://github.com/Expensify/App/assets/56740856/6bbc7668-32e8-496a-b11b-d46a815f1122)

**Comment by sakluger** [comment] 2023-08-10 22:50
@jasperhuangg since this seems to have been caused by your PR, I'm assigning you based on the new "You break it you fix it" rule ([Slack thread](https://expensify.slack.com/archives/C056AV5V8UX/p1690245678485799)).

Jasper, if this isn't a regression from your PR, feel free to reassign!

**Comment by mollfpr** [comment] 2023-08-13 08:51
@ayazhussain79 It has the exact root cause, and on your proposal, I don't think we need to keep `PressableWithFeedback`.

**Comment by jasperhuangg** [comment] 2023-08-14 17:07
Gonna be fixing this internally, thanks for the bump @sakluger!

**Comment by sakluger** [comment] 2023-08-17 17:40
@jasperhuangg can you link your PR when it's ready?

Also, I removed @Gonals' assignment since you're handling this.

**Comment by sakluger** [comment] 2023-08-21 16:58
@jasperhuangg checking in - do you have a draft PR?

**Comment by jasperhuangg** [comment] 2023-08-21 17:11
@sakluger Yes I do! Haven't gotten around to testing it yet but plan to have something done today

**Comment by DinalJivani** [comment] 2023-09-05 17:32
@sakluger 
Offer accepted!

**Comment by sakluger** [comment] 2023-09-06 18:04
All paid, thanks!

**Closed by sakluger** 2023-09-06 18:04 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
