### ISSUE TITLE
[C+ checklist needs completion] [$500] Web - User cannot edit the large amount after creating the distance

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27255] opened 2023-09-12 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Set a big distance rate on a workspace (e.g.: 90000000)
2. Request money -> distance
3. Fill start and finish points
4. Select that workspace
5. Click on the requested money
6. Click on Amount

## Expected Result:
The user should be able to edit the  Amount

## Actual Result:
User cannot edit the large amount after creating the distance

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[big-rate.webm](https://github.com/Expensify/App/assets/93399543/8265b59a-3291-460c-8148-7235fef50559)

https://github.com/Expensify/App/assets/93399543/3263a4e5-3114-4005-960d-3ce0b153c2bc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694207504466369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-09-12 14:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User cannot edit large amounts after creating the distance.

### What is the root cause of that problem?
There is a string length limit set on the MoneyRequestAmountForm which prevents the ability to edit amounts greater than that limit.

### What changes do you think we should make in order to solve the problem?
Solution 1
Increase the length limit for the input field on MoneyRequestAmountForm.


### What alternative solutions did you explore? (Optional)

**Comment by b4s36t4** [comment] 2023-09-12 15:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - User cannot edit the large amount after creating the distance
### What is the root cause of that problem?

We have a hard limit on the IOU request Amount which we're checking before updating.

Here in this case even we're deleting the amount we're still checking limit which is causing the issue not to update the amount.

https://github.com/Expensify/App/blob/f57e5e25223487a949d8154e1b789ffdd0b160b6/src/pages/iou/steps/MoneyRequestAmountForm.js#L126

### What changes do you think we should make in order to solve the problem?

1. We can restrict the distance rate so that amount can be reduced a bit (although we had set limit it can be reduced some-more), but that would still raise issues.

2. Let user delete the amount even if the max-length (10) reached, using the length of `currentAmount` and `newAmount` we're getting from input.

> If we do this user can't edit the amount till he reaches the max-length condition, say he want to replace `0` with 1 he can't. the above solution just 
allow user to delete amount.

3. Or if we've reached max limit, i.e any distance request/scan receipt which we depends on scan or distance units set by workspace we don't let user edit the amount because they are pre-defined.

> This requires user to edit the workspace units which might require us to update all the existing requests to use the update units and update amount 
> for them as well





### What alternative solutions did you explore? (Optional)
NA

**Comment by jjcoffee** [comment] 2023-09-15 13:27
@greg-schroeder Are you able to find out what sort of BE validation of the amount length exists? Looks like `AMOUNT_MAX_LENGTH` was added quite a long time ago, so unsure if [this comment](https://github.com/Expensify/App/pull/5243#discussion_r708520178) still reflects the current state of the BE.

Leaning towards @akinwale's solution 2 here, as it makes sense to me that we'd not want to allow users to create such large distance requests in the first place, unless there's a good reason for it that I'm missing!

**Comment by b4s36t4** [comment] 2023-09-15 14:58
@jjcoffee I think restricting max amount for distance request require multiple changes. Also we have max distance limit & as well as limit on distance rate for workspace too. So I feel it's max distance is not thw way to go.

**Comment by jjcoffee** [comment] 2023-09-15 15:14
@b4s36t4 The main issue as I see it is that we can now make bigger money requests by making a distance request vs. manual request, which is inconsistent and leads to us not being able to edit the amount. So either there's a reason for allowing that (which I can't think of!), or we haven't implemented the right validation to stop this from happening (i.e. prevent a distance request from being created if it exceeds the max amount). Feel free to make a case if you disagree though!

**Comment by greg-schroeder** [comment] 2023-09-15 15:27
@jjcoffee I am not positive - can you take [that question](https://github.com/Expensify/App/issues/27255#issuecomment-1721283174) to Slack to discuss with the greater team?

**Comment by greg-schroeder** [comment] 2023-09-18 10:57
>Leaning towards @akinwale's solution 2 here, as it makes sense to me that we'd not want to allow users to create such large distance requests in the first place, unless there's a good reason for it that I'm missing!

Leaning more towards this myself the more I think about it

**Comment by jjcoffee** [comment] 2023-09-18 11:26
@greg-schroeder I've asked [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1695036347678279) to feel out if there are any differences of opinion.

**Comment by jjcoffee** [comment] 2023-09-22 15:57
[Bumped](https://expensify.slack.com/archives/C01GTK53T8Q/p1695398213101989?thread_ts=1695036347.678279&cid=C01GTK53T8Q) on Slack.

**Comment by greg-schroeder** [comment] 2023-09-25 07:32
Sounds good @jjcoffee

**Comment by jjcoffee** [comment] 2023-09-25 12:49
Okay no takers on Slack, but I'm pretty happy with the reasoning behind going with solution 2 on @akinwale's [proposal](https://github.com/Expensify/App/issues/27255#issuecomment-1715804534) anyway.

I don't think it makes sense to maintain two separate limits for manual requests and for distance requests, and I think the limit (`AMOUNT_MAX_LENGTH`) we have in place for manual requests is useful as it means we don't need to deal with an overflowing amount input. So going with a solution that maintains consistency with the existing limit is the most sensible.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2023-09-25 12:50
@b4s36t4 Also [mentioned](https://expensify.slack.com/archives/C01GTK53T8Q/p1695398360971979?thread_ts=1695036347.678279&cid=C01GTK53T8Q) on Slack an interesting point that the same issue could exist for scans, so it might be worth checking when raising the PR @akinwale.

**Comment by akinwale** [comment] 2023-09-25 14:27
@jjcoffee The scan receipt flow works differently here. You cannot enter an amount during the scan flow. The amount is only available after the receipt has finished scanning, so there's no point during the regular request money flow where we can prevent the scan from being completed.

**Comment by jjcoffee** [comment] 2023-09-25 14:32
@akinwale Ah yeah you're right, I'd imagine that'd be out of scope for this issue as we'd have to figure out some separate UX for the error _after_ scanning (and probably would require BE changes too).

**Comment by aldo-expensify** [comment] 2023-09-26 08:21
Assigning @akinwale

**Comment by akinwale** [comment] 2023-09-26 15:12
@jjcoffee My [PR](https://github.com/Expensify/App/pull/28266) is ready for review. Thanks.

**Comment by jjcoffee** [comment] 2023-09-27 15:20
Are we all happy with showing the `Invalid amount` error here? Just wondering since we're not really entering an amount. cc @greg-schroeder @aldo-expensify

![image](https://github.com/Expensify/App/assets/27287420/9397391e-9075-4e75-8301-b10aca228a05)

**Comment by b4s36t4** [comment] 2023-09-27 15:50
I think we might need a design review on this.

**Comment by greg-schroeder** [comment] 2023-10-12 16:42
processing

**Comment by greg-schroeder** [comment] 2023-10-12 16:52
@akinwale offer sent ($250)
@jjcoffee offer sent ($250)
@hichamcc offer sent ($50)

**Comment by akinwale** [comment] 2023-10-12 16:54
> @akinwale offer sent ($250) @jjcoffee offer sent ($250) @hichamcc offer sent ($50)

The regression that happened here couldn't have been caught during testing because it was due to a separate PR that was merged at the same time. Would the penalty still apply in this case?

cc @aldo-expensify

**Comment by jjcoffee** [comment] 2023-10-13 09:53
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - behaviour was always there
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Set a big distance rate on a workspace (e.g.: 90000000)
2. Open FAB -> Request money -> Distance
3. Set any start and finish points and continue
4. Verify that the "Invalid amount" error shows

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-10-13 10:06
@greg-schroeder Checklist complete!

Also agree with @akinwale - the regression penalty isn't meant to be applied if the review checklist was completed properly (per the C+ process doc at least!). The [other PR](https://github.com/Expensify/App/pull/28137#event-10525529823) could also be argued to have caused the regression since it was merged later than our one :smile:

**Comment by greg-schroeder** [comment] 2023-10-16 14:48
Okay I will review this either today or tomorrow

**Comment by greg-schroeder** [comment] 2023-10-19 00:47
All right I agree @jjcoffee and @akinwale. I'll send over a new offer to account for the difference.

**Comment by greg-schroeder** [comment] 2023-10-19 00:49
Filed regression test

**Closed by greg-schroeder** 2023-10-19 00:49 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by jjcoffee** [comment] 2023-10-19 09:51
@greg-schroeder Thanks - offer accepted!
