### ISSUE TITLE
[$1000] new senders time and details appears after reload

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23323] opened 2023-07-21 01:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. create two new users
2. from user1, send message to user2
3. from user2, send message to user1
4. from user1, go to chat screen with user2 and click on header to see details
5. does not show user2 details(like name, timezone etc.)
6. reload the page and again and click on header to see details(it will show user2 details)

## Expected Result: 
User 1 should be able to see User 2's details because User 2 already sent a message

## Actual Result:
User2's details appear after reload

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bcb4aba7-835e-4837-8d1a-cf9bbc03f290

https://github.com/Expensify/App/assets/43996225/b1f86802-120e-443e-bdaf-ac5e2367eacd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689766793943039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a72bb7f4a6d0b2a</li>
        <li>Upwork Job ID: 1685260209357422592</li>
        <li>Last Price Increase: 2023-08-05</li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-07-24 17:19
@kavimuru - im not able to test this based on the action steps - they're too confusing. can you try to re-write those so they're more clear? 

will you also confirm that you've been able to repro this on your end? thanks!

**Comment by maddylewis** [comment] 2023-07-26 00:46
bumping here - https://expensify.slack.com/archives/C049HHMV9SM/p1690332383906919?thread_ts=1689766793.943039&cid=C049HHMV9SM

**Comment by gadhiyamanan** [comment] 2023-07-27 06:19
@maddylewis try this steps:

1. create two new users
2. from user1, send message to user2
3. from user2, send message to user1
4. from user1, go to chat screen with user2 and click on header to see details
5. does not show user2  details(like name, timezone etc.)
6. reload the page and again and click on header to see details(it will show user2 details)

https://github.com/Expensify/App/assets/54790231/3bdb9b04-aa41-4940-8d2c-ac66f52a2a8b

**Comment by maddylewis** [comment] 2023-07-29 12:05
thanks @gadhiyamanan !

**Comment by b4s36t4** [comment] 2023-07-29 15:17
I think this is backend issue, when it's a new account we're not having any details regarding the user B. 
Even after having a conversation with `OpenPublicProfilePage` command still giving same details that it did previously.
<img width="458" alt="Screenshot 2023-07-29 at 8 40 29 PM" src="https://github.com/Expensify/App/assets/59088937/1a7ce7e3-8bcc-4383-8baa-5114184aced6">

I think there's no pusher data update happening here when User B sends the message. Ideally there should be a update happen for the `personalDetailsList` onyx key which is responsible for showing data in profilePage. `personalDetailsList` is getting updated to onyx by `openReport` command which is why it requires a refresh.
<img width="453" alt="Screenshot 2023-07-29 at 8 43 08 PM" src="https://github.com/Expensify/App/assets/59088937/91ce069c-2ef8-410c-9839-088aceff15da">

Maybe backend can update `OpenPublicProfilePage` API and till user opens the modal again API get's called and data will get updated, since we have the display being used maybe we can use `displayName` property to show user's email.

Showing timezone won't work here cause there's not timezone property on user's data.

**Comment by maddylewis** [comment] 2023-07-31 22:10
@robertKozik - will you take a look at the existing proposals when you have a chance? thanks!

**Comment by mvtglobally** [comment] 2023-08-02 16:47
Issue not reproducible during KI retests. (First week)

**Comment by maddylewis** [comment] 2023-08-06 18:36
since it sounds like this is no longer reproducible, im going to close this one out - https://github.com/Expensify/App/issues/23323#issuecomment-1662575203

**Closed by maddylewis** 2023-08-06 18:36 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by gadhiyamanan** [comment] 2023-08-06 18:39
@maddylewis this is still reproducible for me
