### ISSUE TITLE
[$2000] mWeb (Physical Devices Only) - The "Close account" button is hidden when the keyboard is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13995] opened 2023-01-04 21:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Navigate to Settings > Security
4. Enter the email in the input and tap on "close account"

## Expected Result:
User can enter email and close account without interference.

## Actual Result:
The "Close account" button is hidden when the keyboard is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome
- [ ] iOS / Safari

**Version Number:** 1.2.48.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210655292-f195898e-f190-4684-8101-f5f5893a72a7.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a8db25ed31d0e12</li>
        <li>Upwork Job ID: 1612585717274476544</li>
        <li>Last Price Increase: 2023-01-17</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-01-06 06:12
Can look into this one today

**Comment by jasperhuangg** [comment] 2023-01-06 06:16
Can't seem to reproduce:


https://user-images.githubusercontent.com/31285285/210941855-00529c4f-ac15-4da0-a76d-101afdbd6d59.mov

**Comment by sketchydroide** [comment] 2023-01-06 14:33
Could not reproduce either, I would say that this is probably not a bug, also seems like the sort of thing it might be worked with keyboard avoidance stuff...

**Comment by tjferriss** [comment] 2023-01-09 18:12
I was able to reproduce it, but I'm also not sure if this is really a bug.

![IMG_4847636A2A5E-1](https://user-images.githubusercontent.com/8292562/211377854-7101c55b-ec3f-462e-91ad-26817b98c5fc.jpeg)

**Comment by allroundexperts** [comment] 2023-01-10 01:29
Same as https://github.com/Expensify/App/issues/14057

**Comment by tjferriss** [comment] 2023-01-11 18:30
Left a comment in the other issue. Let's determine whether these are bugs worth fixing, than let's consolidate to one issue.

**Comment by tjferriss** [comment] 2023-01-11 18:30
Left a comment in the other issue. Let's determine whether these are bugs worth fixing, than let's consolidate to one issue.

**Comment by marcochavezf** [comment] 2023-01-17 00:35
Not overdue, we don't have an agreement yet on if this issue should be closed in favor of the other one or not.

**Comment by tjferriss** [comment] 2023-01-18 06:18
I'm asking for clarification in the Slack thread.

**Comment by tjferriss** [comment] 2023-01-18 17:44
Ok we're going to close this issue in favor of [#14057](https://github.com/Expensify/App/issues/14057).

**Closed by tjferriss** 2023-01-18 17:45 UTC
Labels: External, Daily, Help Wanted, Bug
