### ISSUE TITLE
[HOLD for payment 2023-12-06] [$500] Web - Profile - When selecting the last country or state extra space is displayed for a while

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31660] opened 2023-11-21 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Profile > Personal details > Address.
2. Click on the country and select "Zimbabwe."
3. Click on the country again and notice space below.
4. Now, select "United States" and choose the last state.
5. Click on the state again and notice extra space for a while

## Expected Result:
When selecting the last country or state, extra space should not be displayed below the country list or state

## Actual Result:
When selecting the last country or state, extra space is displayed for a while below the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4b3dd7cb-52d3-4859-9acc-ae487dff33f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e93d2572ea063da0</li>
        <li>Upwork Job ID: 1727075975932694528</li>
        <li>Last Price Increase: 2023-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 27786937</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by erquhart** [comment] 2023-11-21 21:31
@lanitochka17 the space looks uniform to me, am I missing something?

**Comment by Fralalala** [comment] 2023-11-22 01:42
## Proposal
Change the `maxToRenderPerBatch` value dependent on the window height.

### Please re-state the problem that we are trying to solve in this issue.
The number of initially rendered selection of countries is not enough to fill the screen.

### What is the root cause of that problem?
According to the code below, the specified number of selections to be rendered initially is `12` but for some reason is not visually being applied.

https://github.com/Expensify/App/blob/da549c0a45edb23fbe9616a9ce21915f291eabe4/src/components/SelectionList/BaseSelectionList.js#L453-L454

It seems that the number of components being visually rendered is determined by `maxToRenderPerBatch`.


### What changes do you think we should make in order to solve the problem?

To avoid hardcoding a bigger value to make sure the selection is initially filled, we can simply replace the value `5` with:
```Math.floor((window.innerHeight  - 129)/ 64)```.

Essentially this formula will calculate how much countries can be shown in the screen. 

Why do we subtract `window.innerHeight` with `129`? 
- 129 is the pixel height of the `Country` Header component plus the height of the Search input for countries.
<img width="269" alt="image" src="https://github.com/Expensify/App/assets/56753788/b28a1fc4-4661-4f90-a8b2-28d9f5af0d86">
<img width="247" alt="image" src="https://github.com/Expensify/App/assets/56753788/2f3c57ca-192e-418f-8e6c-6e224f8c1dbd">

Why do we divide by `64`?
- `64` is the height of a selectable country component
<img width="245" alt="image" src="https://github.com/Expensify/App/assets/56753788/8422c0be-1080-4ed7-a3c3-5c199938385a">

We then Math.floor it since we want a whole number since if the quotient is a decimal,  it would be impossible to render a component at a fraction.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by aum1618** [comment] 2023-11-22 06:15
***Proposal : Fix for this Issue***

**Source of the Problem**
The Initial Number of items being rendered for the list is small , not enough to fill the screen , causing this glitch while opening the country or state selection modal.


What is the root cause of that problem?
 the specified number of selections to be rendered initially is 12 which is small and not enough to fill the screen on every device size causing a glitch effect. 

```
 initialNumToRender={12} 
 maxToRenderPerBatch={5} 
```
It seems that the number of components being visually rendered is determined by maxToRenderPerBatch.

**Fix for the problem**
A bigger value can be passed to the section list.A number large enough to fill the screen that will stop this glitch from occuring that shows up for a while. 
We can also avoid just passing a large number statically and pass a more dynamic number that would be optimal for all screen sizes the general formula used would be  windowHeight/(height of countryItem)
.This will give us the exact number of items initally required to be rendered on the screen.

**Comment by burczu** [comment] 2023-11-22 11:04
@Fralalala I like your solution the most, but the idea to change the `BaseSelectionList` the way you propose is not good - this component is used by the `SelectionList` component, which is used in many places in the app, so this calculation should not be done there. Please update your proposal to address only the issue with the country selector in the personal details page.

**Comment by burczu** [comment] 2023-11-22 11:13
@Fralalala Yeah, it is also worth checking what @ZhenjaHorbach pointed.

**Comment by burczu** [comment] 2023-11-22 11:20
Alright, @ZhenjaHorbach you are right, but you wasn't very specific how to do it exactly and it was just some alternative solution. Please update your proposal too - putting everything together, we need here: 

1. to calculate the `maxRenderPerBatch` dynamicaly
2. to update the country selector, not the `BaseSelectionList` component

**Comment by aum1618** [comment] 2023-11-22 11:50
> @Fralalala I like your solution the most (calculating the `maxToRenderPerBatch` value based on the screen height is IMO a good idea), but the idea to change the `BaseSelectionList` the way you propose is not good - this component is used by the `SelectionList` component, which is used in many places in the app, so this calculation should not be done there. Please update your proposal to address only the issue with the country selector in the personal details page.

To solve this we can specify the num items inside the countryList and the State List  (Where we are seeing this issue) by calculating the number of items using onLayout and pass this as a prop to the SectionList .Then in the sectionList we can destructure this prop and give it an arbitrary value of 12  (the value already given to the list ) this way if no prop is passed it will behave as expected and the change will only apply to where we are seeing this issue. Something kind of like this
`
const SectionList =({maxToRenderPerBatch=12})=>{
`
Now if we pass the value from the CountryLsit the change will only be applied there

**Comment by aum1618** [comment] 2023-11-22 11:53
Contributor details
Your Expensify account email: muhammadumerabbas2005@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01dfc2b81b5151095d

**Comment by sonialiap** [comment] 2023-12-07 10:59
@burczu please complete the [checklist](https://github.com/Expensify/App/issues/31660#issuecomment-1831726699) :)

**Comment by burczu** [comment] 2023-12-11 09:25
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:

**https://github.com/Expensify/App/pull/27767**

* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

**https://github.com/Expensify/App/pull/27767/files#r1422160347**

* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**Not found**

* [x]  [@burczu] Determine if we should create a regression test for this bug.

**I don't think it's worth adding regression test for this issue - it was just UX fix and there was no impact on any important flow.**

* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@sonialiap] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sonialiap** [comment] 2023-12-11 14:10
Thanks, Bartek!

**Closed by sonialiap** 2023-12-11 14:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
