### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] PDFPasswordForm: Error message is not translated to Spanish when changing language.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22519] opened 2023-07-09 04:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login into any account in 2 tabs.
2. From the first tab, open any chat that has protected pdf.
3. Click on that pdf, click on Enter password and press Enter to show the error.
4. Now go to the second tab and change the language to Spanish. Go back to the first tab/
5. Notice that the error message is not translated to Spanish.
## Expected Result: 
Error message should be translated to Spanish.
## Actual Result: 
Error message is not translated to Spanish.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9f36f5de-ee42-41ec-af1e-b7ed307b0081

https://github.com/Expensify/App/assets/43996225/046a1c18-3d25-47f5-b54d-d5cc9a5e7a51

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688552173142719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b8b7b80ebb587bb</li>
        <li>Upwork Job ID: 1678425129565368320</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-09 04:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
PDFPasswordForm: Error message is not translated to Spanish when changing language.
### What is the root cause of that problem?
We're setting our error message as text inside `validate` function here:
https://github.com/Expensify/App/blob/15e547e3bceeb7bfe693f78fc8b90fdc28b1b32f/src/components/PDFView/PDFPasswordForm.js#L88-L90
And this method is only called when TextInput is blurred or when submitting Form. When user changed the language, `validate` function wasn't called, which caused the issue.
### What changes do you think we should make in order to solve the problem?
We can get rid of setting error as text, we should use the translation key instead. We need to update our `validate` function to use translation key:
```javascript
    validate() {
        if (!_.isEmpty(this.state.password)) {
            return true;
        }
        this.setState({
            validationErrorText: 'attachmentView.passwordRequired',
        });
        return false;
    }
```
Then create a function to get the current error text:
```javascript
    getErrorText() {
        if (this.props.isPasswordInvalid) {
            return this.props.translate('attachmentView.passwordIncorrect');
        }
        if (!_.isEmpty(this.state.validationErrorText)) {
            return this.props.translate(this.state.validationErrorText);
        }

        return '';
    }
```
And finally, use `getErrorText` to get current error text for the TextInput:
```javascript
const errorText = this.getErrorText();
<TextInput
   errorText={errorText}
/>
```

### What alternative solutions did you explore? (Optional)
We can add a check inside our componentDidUpdate for preferredLocale change and call the `validate` function to update the error message if we already had an error.

**Comment by DanutGavrus** [comment] 2023-07-09 09:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
PDFPasswordForm: Error message is not translated when changing language for both Spanish to English / English to Spanish.

### What is the root cause of that problem? https://github.com/Expensify/App/blob/0acd42d05003dde342caa03cd9a3c469a078e0cd/src/components/PDFView/PDFPasswordForm.js#L84-L92
1. `validate` method is called at button press;
2. `validate` method sets the state of the error with respect to the current language;
3. After changing the language, the component re-renders, but keeps the old state for the error.

### What changes do you think we should make in order to solve the problem?
**Set text** to the new language when text in old language is visible in `componentDidUpdate` method in `PDFPasswordForm.js`:
```js
// Password required error is visible in old language because preferred one was changed.
if (this.state.validationErrorText != '' && prevProps.preferredLocale != this.props.preferredLocale) {
  this.setState({
    validationErrorText: this.props.translate('attachmentView.passwordRequired'),
  });
}
```
I think it's better to only set the text in `componentDidUpdate` instead of calling the `validate` method, as it may change over time.

**Comment by CortneyOfstad** [comment] 2023-07-10 15:25
I was able to recreate this so getting eyes on this 👍

**Comment by narefyev91** [comment] 2023-07-10 15:38
Proposal from @kavimuru looks good to me https://github.com/Expensify/App/issues/22519#issuecomment-1627605291
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment] 2023-07-10 15:41
> > Proposal from @kavimuru looks good to me [#22519 (comment)](https://github.com/Expensify/App/issues/22519#issuecomment-1627605291) 🎀 👀 🎀 C+ reviewed
> 
> @narefyev91 Actually it's from me 😄 haha, Kavi posted it for the reporter

Yup will be nice - if next time someone from you will post slack link or anything else (where a discussion happened) - to indicate correct person to assign - because i may not have all context - who is who lol

**Comment by DanutGavrus** [comment] 2023-07-10 15:52
@narefyev91 
> Yup will be nice - if next time someone from you will post slack link or anything else (where a discussion happened) - to indicate correct person to assign - because i may not have all context - who is who lol  

I think there's both a Slack link with the discussion and the reporter's GitHub profile at the bottom of each issue which comes from Slack.

**Comment by johnmlee101** [comment] 2023-07-10 15:57
@NikkiWines not sure why you got assigned, but just FYI I'll take this over :D

**Comment by CortneyOfstad** [comment] 2023-07-13 13:02
Bump @johnmlee101 and @narefyev91 ^^^

**Comment by narefyev91** [comment] 2023-07-13 13:16
> Bump @johnmlee101 and @narefyev91 ^^^

I already reviewed PR 2 days ago

**Comment by CortneyOfstad** [comment] 2023-07-17 14:23
Thank you @narefyev91 👍

**Comment by CortneyOfstad** [comment] 2023-07-19 13:28
@narefyev91 any update on the checklist above?

**Comment by narefyev91** [comment] 2023-07-19 16:28
> @narefyev91 any update on the checklist above?

Hey! Sorry do not have a chance to complete checklist - i'm on vacation now https://expensify.slack.com/archives/C02NK2DQWUX/p1689181046746099 maybe @mountiny will help us here

**Comment by mountiny** [comment] 2023-07-19 20:31
@hungvu193 can you please handle the checklist as the author of the PR please? thanks

**Comment by CortneyOfstad** [comment] 2023-07-24 13:23
Thank you for the clarification!

**Comment by mountiny** [comment] 2023-07-24 13:41
What @hungvu193 said

**Comment by CortneyOfstad** [comment] 2023-07-25 17:26
Thanks for the confirmation! @hungvu193 paid you the reporting amount of $250, plus the contributor amount + the bonus ($1750). You should see that completed in Upwork. 

Any questions, just let me know! Closing this!

**Closed by CortneyOfstad** 2023-07-25 17:26 UTC
Labels: External, Daily, Awaiting Payment, Bug
