### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] Distance - Distance changes to incorrect value when waypoint is changed without saving

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41404] opened 2024-05-01 11:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a distance expense.
4. Go to transaction thread.
5. Click Distance.
6. Edit either the start or end location but do not save it.

## Expected Result:
Distance row in the background will not change because the new distance is not saved.

## Actual Result:
Distance row in the background changes and the distance is incorrect.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/84c4e661-19b9-4529-92db-eebb94c060db

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017033137f73d95d13</li>
        <li>Upwork Job ID: 1786471693874479104</li>
        <li>Last Price Increase: 2024-07-17</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103177064</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by izarutskaya** [comment] 2024-05-01 11:08
We think this issue might be related to the #collect project.

**Comment by abzokhattab** [comment] 2024-05-03 20:11
> Distance row in the background changes and the distance is incorrect.


Not reproducible:

https://github.com/Expensify/App/assets/59809993/933f67bf-66e8-4d22-88b9-cfb7d2dcfec3

**Comment by sonialiap** [comment] 2024-05-07 23:17
I can't reproduce either. Closing since three of us cannot reproduce this. Please reopen if it's still an issue

**Comment by izarutskaya** [comment] 2024-05-15 12:19
This issue is still reproducible 
Build 1.4.74-0

https://github.com/Expensify/App/assets/115492554/31bb2500-c426-49b5-8bfa-0244ce3cfbee

**Comment by sonialiap** [comment] 2024-05-21 09:41
Looking for proposals

**Comment by abzokhattab** [comment] 2024-05-22 07:26
still cannot reproduce i am having the same behaviour as in here: https://github.com/Expensify/App/issues/41404#issuecomment-2093695682

**Comment by eVoloshchak** [comment] 2024-05-23 08:26
Unable to reproduce the bug too

**Comment by sonialiap** [comment] 2024-05-28 11:13
@izarutskaya are you still able to reproduce this?

**Comment by sonialiap** [comment] 2024-06-04 14:27
Adding retest label to see if anyone can reproduce this still

**Comment by eVoloshchak** [comment] 2024-06-10 17:28
Not overdue, waiting to see if anyone else can reproduce this

**Comment by sonialiap** [comment] 2024-06-18 14:52
I'll test this tomorrow

**Comment by sonialiap** [comment] 2024-06-21 14:15
I can reproduce this on prod

https://github.com/Expensify/App/assets/17131195/12954cb3-5a7f-4cb2-9972-12fccc6fd03e

**Comment by sonialiap** [comment] 2024-06-21 14:16
Still reproducible. Looking for proposals

**Comment by sonialiap** [comment] 2024-06-26 10:38
looking for proposals

**Comment by sonialiap** [comment] 2024-07-02 13:26
asking for proposals in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1719926755565439)

**Comment by sonialiap** [comment] 2024-07-09 10:24
@eVoloshchak what do you think of the above proposal?

**Comment by eVoloshchak** [comment] 2024-07-14 21:22
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/41404#issuecomment-2208610984) does look good from a technical perspective, but I'm still unable to reproduce the issue on my end

@sonialiap, @nkdengineer, could you please share the exact steps you've used to reproduce this issue?

**Comment by nkdengineer** [comment] 2024-07-14 23:31
@eVoloshchak Did you enable P2PDistance beta?

**Comment by eVoloshchak** [comment] 2024-07-15 17:20
@nkdengineer, that did the trick, thank you!

Why does this work correctly if the request is submitted to a workspace, but incorrectly if it's submitted to a user? Is BE the difference?

**Comment by nkdengineer** [comment] 2024-07-15 17:32
@eVoloshchak This bug here happens when we edit the waypoint of distance request in the WS.

**Comment by nkdengineer** [comment] 2024-07-15 17:35
I just checked and it also happens for P2P distance.

**Comment by nkdengineer** [comment] 2024-07-15 18:14
This bug happens when P2P distance is enabled. If this beta is disabled, we display the merchant of transaction that isn't changed when we edit the waypoint.  When the beta is enabled, the distance is displayed as the quantity of transaction that is changed (about why it's changed I mentioned in my proposal) when we edit the waypoint. That is how the bug happens and it's not a BE issue.

**Comment by eVoloshchak** [comment] 2024-07-18 12:09
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/41404#issuecomment-2208610984) looks good to me!

🎀👀🎀 C+ reviewed!

**Comment by nkdengineer** [comment] 2024-07-19 03:53
@eVoloshchak The PR is [here](https://github.com/Expensify/App/pull/45744). Jest test is failed on the latest main.

**Comment by eVoloshchak** [comment] 2024-08-05 17:53
Not sure why automation didn't work, [PR](https://github.com/Expensify/App/pull/45744) was deployed to staging four days ago, waiting for it to be deployed to prod

**Comment by sonialiap** [comment] 2024-08-13 11:14
Payment summary:
- @eVoloshchak $250 please request in ND - please complete the [checklist](https://github.com/Expensify/App/issues/41404#issuecomment-2270331283)
- @nkdengineer $250 - paid in upwork ✔️

**Comment by sonialiap** [comment] 2024-08-16 12:40
@CortneyOfstad I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for @eVoloshchak to complete the checklist and then we need to submit a new regression test issue to QA

**Comment by Beamanator** [comment] 2024-08-19 18:29
bump @eVoloshchak

**Comment by eVoloshchak** [comment] 2024-08-20 16:28
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this, rather a limitation of the original implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A


**Regression Test Proposal**

Precondition: Enable `P2PDistance` beta

1. Create a distance request
2. Go to the combine report or transaction thread report
3. Click on distance
4. Select a new waypoint (do not click `Save`)
5. Verify that the distance in the money request view did not change


**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2024-08-20 17:22
$250 approved for @eVoloshchak

**Comment by CortneyOfstad** [comment] 2024-08-21 18:12
Thanks @JmillsExpensify!

**Comment by CortneyOfstad** [comment] 2024-08-21 18:13
## Payment Summary

@nkdengineer — paid $250 via Upwork
@eVoloshchak — paid $250 via NewDot

## Regression Test

https://github.com/Expensify/Expensify/issues/422310

**Closed by CortneyOfstad** 2024-08-21 18:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
