### ISSUE TITLE
[Refactor] Able to remove PayPal account while offline, when enabled wifi - account still present

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11260] opened 2022-09-24 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in any account
3. Go to Settings - Payments
4. Add Paypal account
5. Disable in internet connection
6. Remove the Paypal account while offline
7. Enable the internet connection

## Expected Result:
Paypal account should not be visible after enable the internet connection

## Actual Result:
Able to remove PayPal account while offline, when enabled wifi - account still present

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192101768-da1bd147-fd0f-4290-b202-b68a0fba39d0.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment] 2022-09-26 17:33
I can't reproduce this, but it can be external

**Comment by mountiny** [comment] 2022-09-26 19:17
Asked [in Slack](https://expensify.slack.com/archives/C02HWMSMZEC/p1664219831966539) for an internal employee to  investigate this.

**Comment by arosiclair** [comment] 2022-09-27 20:54
I can confirm this is an issue with API reads being executed before offline writes on reconnect. We're running `ReconnectApp` and `OpenPaymentsPage` before `DeletePayPalMeAddress` which causes the deleted paypal to be re-added before it is eventually removed again.

![Screen Shot 2022-09-27 at 4 51 01 PM](https://user-images.githubusercontent.com/6833644/192632802-0ba68359-60f4-4820-8fdd-f7a3b1cbb951.png)

Closing this in favor of https://github.com/Expensify/Expensify/issues/229696 which should fix the issue

**Closed by arosiclair** 2022-09-27 20:54 UTC
Labels: Engineering, Daily, Improvement, Internal
