### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Contact method - An error message is in English in Spanish account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21001] opened 2023-06-19 00:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Preferences -> Language -> Change language to Spanish
4. Go to Profile -> Contact method -> Open any unvalidated contact method
5. Write a wrong magic code

## Expected Result:
An error message is in Spanish

## Actual Result:
An error message is in English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6097924_1806](https://github.com/Expensify/App/assets/78819774/f1bab7cb-a2b0-44fe-b71b-1fd024c36895)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160ca5817cf9d9f89</li>
        <li>Upwork Job ID: 1671872446268678144</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-06-22 13:27
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/be1f7926-1955-4d24-83b3-419398583880">

**Comment by muttmuure** [comment] 2023-06-26 11:16
@hungvu193's proposal looks like a good start @mollfpr

**Comment by mollfpr** [comment] 2023-06-27 19:13
I think it's not worth using BE changes here. We already have the phrase for validating error `contacts.genericFailureMessages.validateSecondaryLogin`, but it displays the error message from the server instead.

**Comment by mollfpr** [comment] 2023-06-29 18:27
I agree with you @hoangzinh as I thought we could reuse the current phrase that we have.

Let's game on! The [proposal](https://github.com/Expensify/App/issues/21001#issuecomment-1613530240) from @hoangzinh looks good to me 🚀

**Comment by mollfpr** [comment] 2023-06-29 18:27
I agree with you @hoangzinh as I thought we could reuse the current phrase that we have.

Let's game on! The https://github.com/Expensify/App/issues/21001#issuecomment-1613530240 from @hoangzinh looks good to me 🚀

🎀 👀 🎀 C+ reviewed!

**Comment by Beamanator** [comment] 2023-07-03 10:52
Sorry for the delay, i was ooo last friday!

**Comment by mollfpr** [comment] 2023-07-18 04:37
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I can't make sure this, this might be related to an update in the BE.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression test should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Login with any account
2. Go to Settings -> Preferences -> Language -> Change language to English
3. Go to Profile -> Contact method -> Open any unvalidated contact method
4. Fill-in incorrect magic codes
5. **Verify** that it shows an invalid magic codes error in English
6. Go to Settings -> Preferences -> Language -> Change language to Spanish
7. Go to Profile -> Contact method -> Open previous unvalidated contact method in step 3
8. **Verify** that it shows an invalid magic code error in Spanish
9. 👍 or 👎

**Comment by mollfpr** [comment] 2023-07-18 04:40
Posting the calculation since Melvin forget about it

The issue assignment is on Jul 3, 2023, 6:52 PM GMT+8.

![Screenshot 2023-07-18 at 11 58 41](https://github.com/Expensify/App/assets/25520267/2d381283-6a8e-4abc-b263-4134872b6fc9)


PR merged is on Jul 6, 2023, 6:35 PM GMT+8.

![Screenshot 2023-07-18 at 11 58 22](https://github.com/Expensify/App/assets/25520267/7e4eb48b-6281-4b09-9da2-f74b1d10a587)


>So, July 6, 2023, 6:35 PM GMT+8 is approximately 2.958 days after July 3, 2023, 6:52 PM GMT+8, which is nearly 3 days later.

This is still eligible for the bonus.

**Comment by muttmuure** [comment] 2023-07-20 12:50
Everybody got paid

**Closed by muttmuure** 2023-07-20 12:50 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
