### ISSUE TITLE
Account - Unable to authenticate a new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46293] opened 2024-07-26 13:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in to new dot with a new Gmail account
2. Finish the onboarding flow
3. Once you are signed in navigate to Account Settings> Profile > Contact Method
4. Click on your contact method (has a GBR since the account is not verified yet)
5. Wait for the Magic Code to arrive in your Gmail
6. Click on "Didn't receive a magic code?"
7. A system message appears that a link has been resent
8. Wait for the Magic code to arrive
9. Repeat step 6 several times

## Expected Result:
Magic sign-in code is received when trying to authenticate a new account

## Actual Result:
Magic sign-in code is not received when trying to authenticate a new account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3c612d0b-16e6-400f-90fd-a74f9af72712

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2024-07-26 14:59
Reproduced on staging **v9.0.13-2**. No magic code is received from the contact method page but the code still works from the sign in page.

**Comment by arosiclair** [comment] 2024-07-26 15:25
On prod **v9.0.12-0**, opening the contact method page also does not send a magic code like it should. However, clicking  `Didn't receive a magic code?` does work. So the resend button not working is new.

**Comment by arosiclair** [comment] 2024-07-26 15:42
Alright switching the the prod API fixes the `Didn't receive a magic code?` link so this is definitely not an App blocker.

**Comment by arosiclair** [comment] 2024-07-26 16:06
I think this is probably due to https://github.com/Expensify/Web-Expensify/pull/42825 cc @dangrous

After creating a new account, we're calling `RequestContactMethodValidateCode` for the primary login, but this calls `UserAPI::requestSecondaryLoginValidationLink` with the new params we added which probably doesn't work.

**Comment by arosiclair** [comment] 2024-07-26 17:17
Alright I was able to reproduce in dev and reverting https://github.com/Expensify/Web-Expensify/pull/42825 fixed the issue. 

The root problem is that setting `isSecondaryLogin` and skipping [this block](https://github.com/Expensify/Auth/blob/1cb6d0d333e4b2320b8396d02cb160ee0a933744/auth/lib/Account.cpp#L896-L904) causes a `SetCashPassword` email notification to get queued [here](https://github.com/Expensify/Auth/blob/1cb6d0d333e4b2320b8396d02cb160ee0a933744/auth/lib/Account.cpp#L907). This doesn't work since that kind of email doesn't exist anymore (there's no template for it in Web-E) which makes sense since we don't support passwords anymore:

```
[alrt] [genintho] Notification_Utils - Unable to load template ~~ template: 'SetCashPassword' to: 'arosiclair+validate2@expensifail.com'
```

I'm going to post a PR to have this reverted.

**Comment by dangrous** [comment] 2024-07-26 17:33
oh i see, so even for a non-secondary account we're still sending that RequestContactMethodValidateCode command. I missed that that was for the primary as well.

Unfortunately checking whether or not it's the secondary in auth won't work because we use the same logic to send magic codes, as well as send validate codes, which shouldn't really be the case... But as it is, it may be tricky to split this up into the different cases (Magic code primary login, magic code secondary login, validation primary login, validation secondary login). I'll give it another go later today or more likely next week.

**Comment by arosiclair** [comment] 2024-07-26 17:58
CP request [here](https://expensify.slack.com/archives/C07J32337/p1722016596066059)

**Comment by arosiclair** [comment] 2024-07-26 18:01
> Unfortunately checking whether or not it's the secondary in auth won't work because we use the same logic to send magic codes, as well as send validate codes, which shouldn't really be the case...

IIRC "magic codes" and "validate codes" are all the same thing so I don't think we need to change any logic. Just change the email template depending on if its primary/secondary. I might be wrong though. @johnmlee101 or @NikkiWines would probably be helpful.

**Comment by dangrous** [comment] 2024-07-26 18:18
yeah it's more about the emails - I had managed to get the right one sent out for three out of the four cases, but missed the fourth one.

**Comment by NikkiWines** [comment] 2024-07-29 09:13
Yeah, there isn't really a difference between magic codes and validate codes - it's just newer and older terminology. Unsubscribe codes and the CTA codes are distinct though as they aren't time limited

**Comment by arosiclair** [comment] 2024-07-29 16:27
This was already fixed on staging so we should be all set

**Closed by arosiclair** 2024-07-29 16:27 UTC
Labels: Engineering, Daily, Overdue
