### ISSUE TITLE
Web - Secondary link unlinked from another device still appears in Contact Methods of first device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22337] opened 2023-07-06 11:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in New Dot
2. Add a secondary contact method and don't verify and stay at this page
3. Login in with this secondary email from another tab
4. Click on Unlink
5. Click on the email for unlinking received in email
6. Go back to first tab

## Expected Result:
Unlinked secondary contact method should not appear there (there should be some update by itself from backend) and we can still click on it to go to the magic code page

## Actual Result:
Unlinked secondary contact method still appears there and clears only on refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a0cb0977-2780-4ba5-b768-8c52abfd70f8

https://github.com/Expensify/App/assets/93399543/e7820828-f684-43df-b1c5-4071d8e76882

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1688522248037589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153730d549e0df868</li>
        <li>Upwork Job ID: 1681343771694870528</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-07-10 10:43
I couldn't prioritize this yet.

**Comment by isabelastisser** [comment] 2023-07-13 12:38
Reviewing this now.

**Comment by isabelastisser** [comment] 2023-07-13 12:56
I'm unable to reproduce this, it's not letting me verify my newly added contact method and not sending me an email with the link -- which is another issue.

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/31258516/a0dc4cbf-bcd7-46d1-b018-de408f4bfae5">


tagging another BZ team member to check if they can verify this.

**Comment by tjferriss** [comment] 2023-07-14 19:07
I was able to reproduce, but I'm not confident on what the actual expected behavior would be so I asked for a clarification [here](https://expensify.slack.com/archives/C03U7DCU4/p1689361635720589).

**Comment by tjferriss** [comment] 2023-07-18 16:44
Let's work on a fix here. I think we do in fact want the app to automatically update as the expected results outline.

**Comment by tjferriss** [comment] 2023-07-19 05:15
Huh I don't know why the `Internal` label didn't assign an Expensify engineer. I'm adding the `Engineering` label to have some internal review the issue. @grgia let me know if you're able to help here as according to @parasharrajat the solution requires backend help.

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 03:50
Unassigning @parasharrajat was initial C+ has more context here and got unassigned mistakenly I guess.

**Comment by tjferriss** [comment] 2023-07-24 22:59
>Is there more background I need to be aware of @tjferriss @parasharrajat?

I don't know :)

**Comment by tjferriss** [comment] 2023-08-01 22:10
@grgia can you weigh in here?

**Comment by bondydaa** [comment] 2023-08-03 15:15
i can take this one for ya

**Comment by bondydaa** [comment] 2023-08-03 15:15
I don't think this is a daily, assuming that the unlink actually happens in the backend properly and the user can't do anything with the secondary login.

**Comment by grgia** [comment] 2023-08-03 15:22
@bondydaa thank you!

**Comment by bondydaa** [comment] 2023-08-03 16:13
okay yep couldn't reproduce via staging either.

I know the primary account that I unlink from is showing production but that shouldn't matter since the unlink request comes from staging it should have hit staging API and ultimately this is pusher stuff at the API level we are relying on.


https://github.com/Expensify/App/assets/4073354/2cc0160a-56da-4787-b466-f73e9220c512

bumping the slack thread just to get some others to test again as well but pretty sure we can close this out.

**Comment by bondydaa** [comment] 2023-08-03 16:22
okay going to close this out, @c3024 can't reproduce it anymore either.

**Comment by bondydaa** [comment] 2023-08-03 16:26
hmm shoot, i thought the automation would have worked on close but now realize we typically only close after payment is done, asked about how to get this paid out here (private slack channel, sorry) https://expensify.slack.com/archives/C01SKUP7QR0/p1691079927914099. reopening for now while i wait to get it figured out.

**Comment by bondydaa** [comment] 2023-08-03 17:55
yep we should still pay out the reporting fee here, @tjferriss can you handle that please, I think since there was no PR associated with this there may not be any more automation for it. 

I see this comment where a job was created https://github.com/Expensify/App/issues/22337#issuecomment-1640571588 so I think we just need to get payment sent for reporting then?

**Comment by tjferriss** [comment] 2023-08-03 18:47
@c3024 can you please apply to the job on Upworks for payment? https://www.upwork.com/jobs/~0153730d549e0df868

**Comment by tjferriss** [comment] 2023-08-04 06:05
Payment has been sent via Upworks.

**Closed by tjferriss** 2023-08-04 06:05 UTC
Labels: Engineering, Daily, Internal, Bug
