### ISSUE TITLE
Chat - "Hmm.. It's not there" message arrive on click of message copied link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20766] opened 2023-06-14 18:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send a random message
3. Open the model on Right click and copy the message URL
4. Send that URL to the same user
5. Now click on that URL

## Expected Result:
There should be an open specific message

## Actual Result:
"Hmm.. It's not there" message show

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b82bf3a8-317b-4b5b-834b-0535e54b2e07

https://github.com/Expensify/App/assets/93399543/af8825e8-ff19-47c9-b3e5-4a5290392cbb

**Expensify/Expensify Issue URL:**

**Issue reported by:** @niravkakadiya25

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686215511405239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by petromoldovan** [comment] 2023-06-14 20:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User sees the "Hmm.. It's not there" error screen when clicking on an report action link.

### What is the root cause of that problem?
There is no route defined for such link:
`http://localhost:8080/r/6345468137089182/5056100523563216000`

This would be the route structure but it does not exist: `r/:reportID/:actionID`

App simply does not know where to navigate.

### What changes do you think we should make in order to solve the problem?
The least painful fix would be to change the way the action link is built and to pass the actionID as URL parameter:
`http://localhost:8080/r/6345468137089182?actionID=5056100523563216000`

In this way we are automatically navigated to the right report. In the `ReportActionsList.js` component I would check for the  `actionID` parameter in the URL and if it is present I would: 
1. scroll to the appropriate action 
2. I would highlight it shortly by changing the background color for a second.

### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment] 2023-06-15 03:58
Dupe of this https://github.com/Expensify/App/issues/17977.

**Comment by alexpensify** [comment] 2023-06-15 15:07
Thank you, I bumped the Slack 🧵 here to identify if we should close: 

https://expensify.slack.com/archives/C049HHMV9SM/p1686841574260389?thread_ts=1686215511.405239&cid=C049HHMV9SM

**Comment by alexpensify** [comment] 2023-06-15 23:25
Alright, closing this GH based on the convo above. The current behavior is the correct one but there will be updates in the future.

**Closed by alexpensify** 2023-06-15 23:25 UTC
Labels: Daily, Bug
