### ISSUE TITLE
[HOLD for payment 2023-08-08][$1000] Dev: Web - Thread report header displays no data & composer is hidden when clicking 'Reply in thread' icon while in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23646] opened 2023-07-26 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Send message
3. Open dev tools  & apply 'offline' network mode
4. Hover over the sent message & click on 'Reply in thread' icon

## Expected Result:
Thread header should display the threaded message & 'from' link, and composer should be visible

## Actual Result:
Thread header doesn't display the threaded message & 'from' link, and composer is not visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.45-8
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/83976b6e-098f-4faf-8e16-9308229cbe18

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690375363052749
https://expensify.slack.com/archives/C049HHMV9SM/p1690461910613649 (Similar bug)
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172d7253f196dfea5</li>
        <li>Upwork Job ID: 1684725080240574464</li>
        2023-07-28<li>Automatic offers: </li>
<ul>
<li>Natnael-guchima | Reporter | 25809101</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-26 14:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread report header displays no data & composer is hidden when clicking 'Reply in thread' icon while in offline mode.

### What is the root cause of that problem?
When reply in thread while in offline mode, `ReportUtils.buildOptimisticChatReport` is called.

We pass `CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS` to `ReportUtils.buildOptimisticChatReport`.
So `report.writeCapability` is set to `always`, but this value should be one of `all`, `admins`.
Therefore, the error is occured, and report is not fully displayed.

### What changes do you think we should make in order to solve the problem?
We should pass proper value to `ReportUtils.buildOptimisticChatReport` as below.
```js
	const newChat = ReportUtils.buildOptimisticChatReport(
		participantAccountIDs,
		lodashGet(parentReportAction, ['message', 0, 'text']),
		lodashGet(parentReport, 'chatType', ''),
		lodashGet(parentReport, 'policyID', CONST.POLICY.OWNER_EMAIL_FAKE),
		CONST.POLICY.OWNER_ACCOUNT_ID_FAKE,
		false,
		'',
		undefined,
		CONST.REPORT.WRITE_CAPABILITIES.ALL,
		CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS,
		parentReportAction.reportActionID,
		parentReportID,
	);
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by zanyrenney** [comment] 2023-07-27 15:36
I don't have a Dev environment, assigning eng to help with that step!

**Comment by bondydaa** [comment] 2023-07-28 00:38
hmm i don't understand, contributors don't have expensify vms either so I think what they mean is this is in `main` not on `staging` or `production` yet.

**Comment by Pujan92** [comment] 2023-07-28 12:14
Seems 3 places we need to correct https://github.com/Expensify/App/issues/23638#issuecomment-1651783608

**Comment by rezkiy37** [comment] 2023-07-28 13:33
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue, because I am the author of the [broken PR](https://github.com/Expensify/App/pull/21950).

**Comment by amyevans** [comment] 2023-07-28 14:02
As @rezkiy37 mentioned this is a regression from https://github.com/Expensify/App/issues/21456 so self-assigning

**Comment by Natnael-Guchima** [comment] 2023-07-28 14:04
Accepted the offer. Thanks

**Comment by rezkiy37** [comment] 2023-08-04 18:10
https://github.com/Expensify/App/pull/23919 was merged. Is the issue going to be closed?

**Comment by amyevans** [comment] 2023-08-04 20:25
Yeah I think we're okay to close. Typically we wait a week after deploy to prod before closing, but that's to handle payments, and I think since the bug reporter accepted the offer and no one else is due payment, we can close now.

**Comment by Natnael-Guchima** [comment] 2023-08-04 21:26
@amyevans an offer was sent to me & it is not settled yet https://github.com/Expensify/App/issues/23646#issuecomment-1655743193

**Comment by amyevans** [comment] 2023-08-04 22:20
Okay my bad 😅, thanks for pointing it out. Reopening so that @zanyrenney can handle that part.

**Comment by Natnael-Guchima** [comment] 2023-08-04 22:21
No worries 😁

**Comment by mananjadhav** [comment] 2023-08-10 04:03
@zanyrenney Did you get a chance to look at this? Once @Natnael-Guchima is paid, we can close this one out.

**Comment by zanyrenney** [comment] 2023-08-14 11:02
This is paid! Closing: 
![2023-08-14_12-02-34](https://github.com/Expensify/App/assets/56830058/113c6c06-02cd-4f4f-9897-aa953f070b6e)

**Closed by zanyrenney** 2023-08-14 11:02 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
