### ISSUE TITLE
[HOLD App #22500] DEV :  Incorrect tooltip on Invite members page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22513] opened 2023-07-09 03:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces > select any workspace
2. Go to Members > Invite
3. Hover user avatar in any option row
## Expected Result: 
Tooltip shows with avatar, email and display name
## Actual Result: 
Tooltip shows only avatar

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/16739372-2185-4213-b032-005e270f407c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688843540866699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2023-07-09 04:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect tooltip on Invite members page

### What is the root cause of that problem?
#21696 was reverted in recent PR. So when get icons without report, fallbackIcon returns -1 as id

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/ReportUtils.js#L807-L816

### What changes do you think we should make in order to solve the problem?
Add #21696 back:
```
function getIcons(report, personalDetails, defaultIcon = null, isPayer = false, defaultName = '', defaultAccountID = -1) {
    if (_.isEmpty(report)) {
        const fallbackIcon = {
            source: defaultIcon || Expensicons.FallbackAvatar,
            type: CONST.ICON_TYPE_AVATAR,
            name: defaultName,
            id: defaultAccountID,
        };
        return [fallbackIcon];
    }
```

**Comment by alexpensify** [comment] 2023-07-10 21:20
Not overdue, I was assigned when I was OOO

**Comment by alexpensify** [comment] 2023-07-11 21:10
I'm unable to replicate this experience on prod: 

![image](https://github.com/Expensify/App/assets/8107070/241bd125-6550-4a9b-994c-31db1df8dcc4)

Now, in Staging this is an issue: 

![image](https://github.com/Expensify/App/assets/8107070/9fc9f2bb-b2f2-439d-b0de-c20e84a6c431)

**Comment by alexpensify** [comment] 2023-07-11 21:14
@amyevans and @rushatgabhane - I think this is similar to https://github.com/Expensify/App/issues/22062#issue-1784646498 but wanted to double check before closing. If it's a different root cause, then I'll assign `External`. Thank you for your feedback!

**Comment by situchan** [comment] 2023-07-12 02:47
It's a different root cause. This is a regression from https://github.com/Expensify/App/pull/20512 but #22062 existed before.

**Comment by amyevans** [comment] 2023-07-12 15:38
It was added back in https://github.com/Expensify/App/pull/22500 cc @grgia

**Comment by situchan** [comment] 2023-07-12 15:45
I confirmed fixed on latest main.
Once it's deployed to staging, we can retest and close this.

**Comment by alexpensify** [comment] 2023-07-12 22:24
Thanks, I'm putting this one on Hold.

**Comment by situchan** [comment] 2023-07-17 01:32
https://github.com/Expensify/App/pull/22500 was deployed to production.
This is not reproducible anymore. We can close this.
I might be eligible for reporting bonus.

**Comment by alexpensify** [comment] 2023-07-18 20:21
I've confirmed that this is not reproducible. There is no bonus because the fix was already in the works before this GH. @amyevans can I get a buddy check if you agree with my summary? Thank you!

**Comment by alexpensify** [comment] 2023-07-18 22:02
@amyevans I should have asked my question differently. Did this GH help flag that we needed to revert? Thanks!

**Comment by amyevans** [comment] 2023-07-18 22:47
Oh honestly I don't know, I wasn't involved in that discovery. @0xmiroslav how did you uncover the bad merge conflict issue that led to https://github.com/Expensify/App/pull/22500?

**Comment by alexpensify** [comment] 2023-07-19 21:44
Ok, I've reviewed these points and feel like this GH didn't contribute to uncovering the regression. At this point, we should close but will leave it open until tomorrow if there are any remaining points to flag.

**Closed** 2023-07-21 19:53 UTC
Labels: Weekly, Needs Reproduction, Bug
