### ISSUE TITLE
[$1000] mWeb (Safari) - Chat - Selecting a room from search results opens in half of the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8396] opened 2022-03-31 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace if you don’t have one already using the FAB ➕ button -> New Workspace
2. Go to search
3. Search for any of the  rooms and open it.

## Expected Result:
The room opens and displays smoothly.

## Actual Result:
The room is shown shifted to the right, so it is not possible to view it completely or to perform any action in it.

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Mobile Web Safari

**Version Number:** 1.1.49 -0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** applausetester+le@applause.expensifail.com / Utest123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/161074232-3b0d38da-fd48-421b-8c22-37ec196614b0.mp4

<img src="https://user-images.githubusercontent.com/43996225/161074572-26f23aa1-573c-4298-85b7-f893e8a506ec.PNG" width="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-03-31 14:35
Seems like UI problem on MobilWeb. Making it external.

@kavimuru Would you be able to also add whether this happens only on iOS mobile web (Safari) or it also occurs on Android mobile web as this feels like it could be only in Safari. Thanks!

**Comment by kavimuru** [comment] 2022-04-01 14:44
@mountiny It works fine in android mWeb. Issue is only in iOS Safari.

https://user-images.githubusercontent.com/43996225/161286666-1597d222-c73b-422f-809a-f1941e436be1.mp4

**Comment by mountiny** [comment] 2022-04-03 10:15
Thanks for confirming @kavimuru, updated the issue just to clarify this for the contributors!

**Comment by mountiny** [comment] 2022-04-05 16:26
@stephanieelliott Bumping here for Exporting this one, thank you 🙇

**Comment by stephanieelliott** [comment] 2022-04-06 02:59
Posted to Upwork: https://www.upwork.com/jobs/~016be1280a5e18a4d5

**Comment by stephanieelliott** [comment] 2022-04-14 23:34
2x'd to $500: https://www.upwork.com/jobs/~016be1280a5e18a4d5

**Comment by stephanieelliott** [comment] 2022-04-22 03:11
2x'd to $1000: https://www.upwork.com/jobs/~016be1280a5e18a4d5

**Comment by rushatgabhane** [comment] 2022-04-26 01:45
@Expensify/contributor-plus wanna pick this up? I'll be OOO because school exams 📖👨‍🏫
No proposals yet

**Comment by rushatgabhane** [comment] 2022-04-26 18:42
@michaelhaxhiu you know what to do xD

**Comment by mananjadhav** [comment] 2022-04-30 21:53
Went through the history, waiting for proposals.

**Comment by parasharrajat** [comment] 2022-05-01 10:45
Based on RCT, this is a duplicate of https://github.com/Expensify/App/issues/8292. And we already have a proposal on 8292. we should close this.

**Comment by stephanieelliott** [comment] 2022-05-03 14:34
Thanks @parasharrajat! I agree, let's go ahead and close this in favor of the other issue.

**Closed by stephanieelliott** 2022-05-03 14:34 UTC
Labels: External, Engineering, Weekly, Help Wanted
