### ISSUE TITLE
Expensify Card - Toggle for Expensify Card is only locked after refreshing the page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49212] opened 2024-09-14 18:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49173
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace settings > More features.
4. Enable Expensify Card.
5. Go to Expensify Card.
7. Click Issue new card.
8. Go through bank account set up.
9. Issue new card to yourself.
10. After issuing new card, go to More features page.

## Expected Result:
The toggle for Expensify Card should be immediately locked (production behavior).

## Actual Result:
The toggle for Expensify Card is not immediately locked. It is only locked after refreshing the page.

Manual refresh is also required to unlock the toggle after deactivating Expensify Card.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fcac0eb9-7b95-4ceb-a0bc-ebeea88e3b4b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment] 2024-09-14 23:58
cc @VickyStash seems related to https://github.com/Expensify/App/pull/49173

**Comment by mountiny** [comment] 2024-09-15 22:40
@dominictb @Nodebrute we cannot do that as that would reintroduce the bug we had before. 

I think this is ok and we can revert to using the cardList once we merge the deploy the onyx fix https://github.com/Expensify/react-native-onyx/pull/581

**Comment by mountiny** [comment] 2024-09-21 07:56
This is not on hold any more.

@allgandalf @DylanDylann is this still a problem in the latest staging?

**Comment by mountiny** [comment] 2024-09-22 20:59
@allgandalf do you get that error on some account where this worked before or some new account you just created?

**Comment by DylanDylann** [comment] 2024-09-23 13:21
@allgandalf You can try on the new account and set up the bank account again

**Comment by DylanDylann** [comment] 2024-09-23 14:53
Let's me try

**Comment by DylanDylann** [comment] 2024-09-23 16:24
Can't reproduce. It seems this issue was fixed by https://github.com/Expensify/App/pull/49280

**Comment by mountiny** [comment] 2024-09-23 23:13
Perfect lets close then and see if this will come back eventually

**Closed** 2024-09-23 23:13 UTC
Labels: Engineering, Daily, Bug
