### ISSUE TITLE
[HOLD for payment 2022-08-11] [$500] Chat - Safari - Drag & Drop - Little "+ copy" icon doesn't appear consistently on Safari

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9485] opened 2022-06-17 16:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Open any chat
4. Drag & Drop an image within the chat

## Expected Result:
The user expects to see the "+" icon so that they know that this image can be uploaded this way

## Actual Result:
On Safari, The "+" icon does not show unless the user quickly moves the cursor
Note:  The "+" icon appears consistently on Chrome browser and on Desktop app

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web Mac Safari
- Desktop App

**Version Number:** 

**Reproducible in staging?:** 

**Reproducible in production?:** 

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
Both videos of Safari and chrome added

https://user-images.githubusercontent.com/43996225/174341935-5d91b393-232e-46c1-b053-cb9fc2399c84.mp4

https://user-images.githubusercontent.com/43996225/174341955-ebd32eb9-6d42-481e-838f-ff43d04a179a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment] 2022-06-28 20:47
Did a little investigating, bug is for all files, not just images on safari

**Comment by puneetlath** [comment] 2022-07-13 21:06
External Upwork job: https://www.upwork.com/jobs/~01b4c3fac00064e2ed
Internal Upwork job: https://www.upwork.com/ab/applicants/1547326531942969344/job-details

**Comment by puneetlath** [comment] 2022-07-19 15:13
Still waiting for proposals. Upping to $500.

**Comment by andrewlor** [comment] 2022-07-19 23:21
I have a proposal to fix this. The idea is to manipulate the cursor style for the entire document (or some other large element that is a parent of the chat view) based on events handled by `dragNDropListener` in the `Composer` component. Here is a short demo of it working.

https://user-images.githubusercontent.com/8475244/179864052-5ac02024-1e61-406f-87fb-317f16e39874.mov

**Comment by parasharrajat** [comment] 2022-07-20 12:03
@andrewlor Idea looks good to me. Could you please show us how will you do that?

We have an automated and standardized way how to handle the proposals, which helps us to stay efficient and on top of things. I would recommend checking out some we have an automated and standardized way how to handle the proposals, which helps us to stay efficient and on top of things. I would recommend checking out some previous jobs, which already got a contributor assigned to see how they posted the proposals. There is also [this part](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md?rgh-link-date=2022-07-19T09%3A31%3A19Z#propose-a-solution-for-the-job) in our contributor guidelines which you might find useful.

Please, also share the exact changes in code you had to make to fix this issue. You can see from all the other issues and contributors that we won't just take the code and run away, no need to worry about that :)

Thank you!, which already got a contributor assigned to see how they posted the proposals. There is also [this part](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md?rgh-link-date=2022-07-19T09%3A31%3A19Z#propose-a-solution-for-the-job) in our contributor guidelines which you might find useful.

Please, also share the exact changes in code you had to make to fix this issue. You can see from all the other issues and contributors that we won't just take the code and run away, no need to worry about that :)

Thank you!

**Comment by parasharrajat** [comment] 2022-07-20 15:27
> otherwise I'll wait to move forward with the PR.

Go through the Contributing guidelines https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md to understand the process.

**Comment by parasharrajat** [comment] 2022-07-20 16:07
> Not sure what I'm missing.
Nothing, you are on track. :+1: 

Looks like your proposal is what I was expecting. @andrewlor's [proposal](https://github.com/Expensify/App/issues/9485#issuecomment-1189643102) looks good to me.

@andrewlor Please test your solution on all possible platforms including different browsers(Firefox, chrome, safari).

cc: @puneetlath 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by andrewlor** [comment] 2022-07-21 16:22
Testing on all platforms. I could check on ios/android/mweb to make sure there isn't any regression while attaching files, but I'm pretty sure this should not be applicable as it should not be possible to drag and drop.

https://user-images.githubusercontent.com/8475244/180258593-3b622cd4-0394-4a35-b302-4a7def0ed2b8.mov

https://user-images.githubusercontent.com/8475244/180258607-827314b7-365e-4c9f-990e-e02cfc013f8d.mov

https://user-images.githubusercontent.com/8475244/180258613-56a47c0b-3b82-4e0d-bb01-53d78e0cad86.mov

https://user-images.githubusercontent.com/8475244/180258619-0926c469-5c76-4f42-94fd-c57c265bb2fc.mov

**Comment by parasharrajat** [comment] 2022-07-21 17:07
cc: @puneetlath https://github.com/Expensify/App/issues/9485#issuecomment-1190472729

**Comment by puneetlath** [comment] 2022-07-26 20:33
Sounds simple and straightforward to me.

**Comment by mvtglobally** [comment] 2022-08-09 04:39
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2022-08-11 20:30
Paid @andrewlor. Sent C+ contract to @parasharrajat.

**Comment by puneetlath** [comment] 2022-08-11 21:14
Everyone paid. Thanks for your contributions everyone!

**Closed by puneetlath** 2022-08-11 21:14 UTC
Labels: Exported, External, Engineering, Weekly, Awaiting Payment
