### ISSUE TITLE
Composer displays briefly when opening a deleted workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#16454] opened 2023-03-23 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Delete workspace
2. Open any room or workspace chat of the deleted workspace

## Expected Result:
Composer should not display when opening deleted

## Actual Result:
Composer briefly displays when opening deleted workspace

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.88-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/227269432-3e23d950-468b-416e-96b5-6e4a8c4f904c.mp4

https://user-images.githubusercontent.com/43996225/227269467-150c4950-dcc4-49eb-8655-edffd1207598.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1679581038766069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2023-03-23 21:54
Hmm, I cannot repro on v88-1 (Pixel 3a) or the desktop app.

**Comment by jliexpensify** [comment] 2023-03-23 21:59
Also asked Kadie to double check/verify and she cannot repro either: 

https://user-images.githubusercontent.com/30815269/227373813-222e35a2-7b3a-4cd5-a93f-a17b299c26c6.mp4

Could this be an internet connection thing? The behaviour doesn't seem consistent at all - you can see the chat switcher in @ayazhussain79 only some of the time.

**Comment by ayazhussain79** [comment] 2023-03-23 22:05
@jliexpensify I can still produce it try to reproduce it on the app. composer open for a while while opening delete workspace

**Comment by jliexpensify** [comment] 2023-03-23 22:09
Can you run a speedtest and share a screenshot here? Since Kadie and I both don't see this issue, we're theorising it could be the internate connection?

**Comment by kadiealexander** [comment] 2023-03-23 22:13
I've tried with the iPhone mobile app, couldn't reproduce there either:

https://user-images.githubusercontent.com/59587260/227376009-dbd6547e-a934-4ab4-ade1-e067573c9307.MP4

Here are my internet speed test results for reference:

![IMG_CFBBC9B4BAC3-1](https://user-images.githubusercontent.com/59587260/227376526-31af5139-1cad-4bde-804b-a09782410f0d.jpeg)

**Comment by ayazhussain79** [comment] 2023-03-24 13:53
@jliexpensify @kadiealexander  So it is due to internet speed, there should be something that composer should not show at low internet speed.

**Comment by ayazhussain79** [comment] 2023-03-24 13:54
@kavimuru can also reproduce it

**Comment by jliexpensify** [comment] 2023-03-26 21:33
@ayazhussain79 - so, just to confirm for my understanding:

1. You believe this specific issue is caused by a slow internet speed?
2. You think the actual issue is that the composer behaviour should be consistent (i.e. it shouldn't surface) whatever the internet speed?

**Comment by ayazhussain79** [comment] 2023-03-26 22:10
@jliexpensify i can't confirm its a internet speed issue, it shouldn't surface on deleted workspaces, whether its internet issue or not

**Comment by kadiealexander** [comment] 2023-03-26 22:15
@ayazhussain79 we are not sure either, we are asking for more information to narrow down what the cause of the issue is (because neither @jliexpensify or myself is experiencing it). 

Is your Expensify account set up as a high-traffic account?

**Comment by ayazhussain79** [comment] 2023-03-26 22:18
@kadiealexander no ma'am

**Comment by jliexpensify** [comment] 2023-03-26 22:19
I'm on v1.2.89-0 now (Pixel 3a and Chrome) and I can't repro this

**Comment by jliexpensify** [comment] 2023-03-26 22:43
@kavimuru and @ayazhussain79 - given that Kadie and I can't repro this across every platform on v89, I'm going to close this. Please re-open if you can come up with very clear reproduction steps and we'll test again.

**Closed by jliexpensify** 2023-03-26 22:44 UTC
Labels: Daily, Bug

**Comment by ayazhussain79** [comment] 2023-03-26 23:31
if you login and opened deleted workspace composer displayed but not 2nd time if you opened same deleted workspaces (in video)
https://user-images.githubusercontent.com/56740856/227811585-949589e7-b1ba-451b-9964-9e15ca9f88fe.mp4

**Comment by kadiealexander** [comment] 2023-03-27 00:08
Thanks for the updated video. Are you actually able to type anything into the compose box while it shows briefly? If not I don't think this is a bug, it's our regular loading screen.

**Comment by jliexpensify** [comment] 2023-03-27 00:24
I spent about 10 mins on various archived rooms trying to reproduce: I'd say that this occurs incredibly infrequently, and the only pattern/repro steps I have are:

1. Create new workspace and delete it
2. Click on archived #admins rooms to surface composer briefly

OR

1. Close Expensify Chat
2. Re-open Expensify chat and find any archived #admins room to surface composer briefly

Basically, the behaviour I'm seeing is that the composer will very briefly be generated with the "first" deletion of the workspace, or if Expensify Chat is re-opened.

**Comment by jliexpensify** [comment] 2023-03-27 00:26
I agree with Kadie - it isn't an actual bug, as you can only see a quick glimpse and you can't actually compose a message.
