### ISSUE TITLE
Ready to pay 2023-06-02 [$1000] Secondary login successfully unlinked' message doesn't disappear when typing in 'phone/email' input

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18685] opened 2023-05-09 22:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Add a secondary login account, and leave it unverified
2. Open new tab
3. Navigate to sign in page
4. Enter the unverified email address
5. Click on Unlink button
6. Open email account, click on 'the validation link here' to unlink the account
7. Verify 'Secondary login successfully unlinked' message is displayed
8. Start typing into 'Phone or email' input field

## Expected Result: 
'Secondary login successfully unlinked' should disappear as 'Account closed successfully' message disappears when deleting account
## Actual Result:'
Secondary login successfully unlinked' message doesn't disappear

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/98e6b80f-c0f9-445b-be94-f40dd8e78492

https://github.com/Expensify/App/assets/43996225/8be2194d-b5ee-417c-bb34-7186bc7ae8e6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683653458383499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5469364daf779e9</li>
        <li>Upwork Job ID: 1658883442798800896</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-05-10 05:09
We can remove this message when user start typing (on Text Change), but with browser that enable the auto-fill, it will also trigger the onTextChange, that will make this text disappear right after user open the page. So I think we should keep "Secondary login successfully unliked" message while user's typing, and remove it when we submit.

**Comment by Natnael-Guchima** [comment] 2023-05-10 05:19
Clearing message when typing in input field seems to be an expected behavior according to the expected behavior stated on line 10 of the image below. For closing account, "Account closed successfully" message is cleared when typing in input field. I think it should do the same for unlinking account since the messages for both flows are displayed in the same place. 

![237231692-47bfcd5e-9767-4002-94ca-4ee3208329a1.png](https://github.com/Expensify/App/assets/57330233/6106f835-6ab8-4ffc-952f-1a0218a6a1a8)

**Comment by garrettmknight** [comment] 2023-05-11 10:04
Reassigning since I'm headed OOO

**Comment by arielgreen** [comment] 2023-05-16 03:56
Working on this tomorrow!

**Comment by arielgreen** [comment] 2023-05-17 17:13
Reproduced, this is ready to be worked on

**Comment by dukenv0307** [comment] 2023-05-18 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
'Secondary login successfully unlinked' message doesn't disappear after unlinking account and type.

### What is the root cause of that problem?

In here https://github.com/Expensify/App/blob/cb6ba23ea1e99a3b332983568ee8e9aa0c2a09dd/src/pages/signin/LoginForm.js#L200, we show the `Secondary login successfully unlinked` by using `this.props.account.message`, but we're not clearing the account message when we type on text input. 

### What changes do you think we should make in order to solve the problem?

1. When text change, we need to check if it's autofilled by browser, if yes then we'll not clear the account message. We only clear it when text changes due to user input.

The approach to check if input is autofilled is already used here https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/components/TextInput/BaseTextInput.js#L134 in the code base.

We can introduce a new method somewhere common for reuse
```
isInputAutofilled(inputRef) {
        if (!inputRef.matches) {
            return false;
        }

        return inputRef.matches(':-webkit-autofill') || inputRef.matches(':autofill');
    }
```

2. Then we need to add logic to clear the account message upon user typing (but not autofill) to here https://github.com/Expensify/App/blob/cb6ba23ea1e99a3b332983568ee8e9aa0c2a09dd/src/pages/signin/LoginForm.js#L105

```
if (this.props.account.message && !isInputAutofilled(this.input)) {
    Session.clearAccountMessages();
}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by abdulrahuman5196** [comment] 2023-05-18 16:04
Thanks for the proposals. Will review these today.

**Comment by abdulrahuman5196** [comment] 2023-05-18 18:54
I see there are concerns around auto-fill case. But I don't see auto fill cases working properly already. for existing cases like error message or account deleted message, In firefox the message doesn't get removed during autofill but in chrome the message is removed during autofill.


https://github.com/Expensify/App/assets/46707890/6c343477-0d6f-4cd9-9307-da51af309b74


https://github.com/Expensify/App/assets/46707890/a74d2978-2826-46cc-bbc0-9de2b5f6583e

**Comment by abdulrahuman5196** [comment] 2023-05-18 19:14
@neil-marcellini  Need some of your inputs on the situation

Summary on the situation

For the initial issue creation, the reason is "Secondary login successfully unlinked" message doesn't get disappeared when we start typing. But we already have logic to remove other messages(account closed message) or errors when user starts typing and the solution be to handle another `message` prop in the same way as mentioned on the proposal - https://github.com/Expensify/App/issues/18685#issuecomment-1541881301

There are additional concerns around using onTextChange to remove the message, since it will be triggered on browser autofill case as well, so that the message will be immediately removed before user being able to see the message. But for our case in the existing logic, auto-fill doesn't have consistent behaviour across browsers as mentioned here - https://github.com/Expensify/App/issues/18685#issuecomment-1553492663. Seems to be an different issue to have consistent behaviour across browser.

So the questions are,
1) Should we try to solve this auto-fill concerns as part of this issue?
(I am fine either way for this)

2) If we are going to solve the auto-fill concerns here, Should we show the account specific messages in case of auto-fill email? Because the message could have been shown for `A` email but I could have `B` email autofilled in the browser. It might become a confusing case for user.
My preference is not to show message in case of auto-filled email. Or have logic to make sure the autofilled mail is same as the link origin mail and show the message(2nd half might be tricky to solve and not sure if its worth it).

**Comment by neil-marcellini** [comment] 2023-05-19 15:50
Interesting.
1. Let's not try to solve the autofill problem here, I think we should tackle that separately. Feel free to report that as a separate bug, but I'm not sure it's a priority.

So it sounds like we can go with @hoangzinh's [proposal](https://github.com/Expensify/App/issues/18685#issuecomment-1541881301). I actually like his alternate solution best.

**Comment by abdulrahuman5196** [comment] 2023-05-19 17:43
Thank you for the response @neil-marcellini. I had same thoughts but wanted to confirm anyways.

@hoangzinh proposal with alternate code change is good https://github.com/Expensify/App/issues/18685#issuecomment-1541881301 
(Both the change requested and alternate is pretty much same, with more of a PR adjustment in alternate)

🎀 👀 🎀 C+ reviewed
@neil-marcellini

**Comment by neil-marcellini** [comment] 2023-05-22 16:33
Not overdue, just hired.

**Comment by arielgreen** [comment] 2023-05-23 00:53
@hoangzinh @abdulrahuman5196 @Natnael-Guchima please be sure to apply to the Upwork posting [here](https://www.upwork.com/jobs/~01c5469364daf779e9).

**Comment by Natnael-Guchima** [comment] 2023-05-23 04:21
Applied. Thanks!

**Comment by neil-marcellini** [comment] 2023-05-23 17:03
Merged ✅

**Comment by arielgreen** [comment] 2023-05-25 02:40
Regression period

**Comment by arielgreen** [comment] 2023-05-26 02:04
Reassigning, OOO tomorrow/Monday.

**Comment by abdulrahuman5196** [comment] 2023-05-31 21:14
BZ checklist:
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This wasn't a regression bug. This requirement/functionality to clear `account.message` on text input was never identified. 

>Determine if we should create a regression test for this bug.
[@abdulrahuman5196] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Seems to be a very minor corner case change. It would beneficial not to create a regression test.

@neil-marcellini

**Comment by conorpendergrast** [comment] 2023-06-06 12:40
Looks like this was within the urgency bonus, so increasing the C and C+ by 50%

**Comment by abdulrahuman5196** [comment] 2023-06-06 12:53
@conorpendergrast  applied for job mentioned here https://github.com/Expensify/App/issues/18685#issuecomment-1558291770

**Comment by conorpendergrast** [comment] 2023-06-06 13:01
Three contracts sent, will pay as they're accepted 👍

**Comment by abdulrahuman5196** [comment] 2023-06-06 13:15
@conorpendergrast accepted the invite

**Comment by conorpendergrast** [comment] 2023-06-06 13:23
Paid @Natnael-Guchima and @abdulrahuman5196, waiting for @hoangzinh to accept the contract so I can pay

**Comment by conorpendergrast** [comment] 2023-06-06 15:36
All done. Closing this out, thanks all

**Closed by conorpendergrast** 2023-06-06 15:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
