### ISSUE TITLE
[HOLD for payment 2022-07-05] [$500] Sending messages while offline causes inconsistent margin on messages

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9249] opened 2022-05-31 05:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat 
2. send few messages 
3. Go offline 
4. Send few messages 
5. Go online receive few messages 

## Expected Result:
Messages should be aligned 

## Actual Result:
Sending messages while offline causes inconsistent margin on messages

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.65-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/171099814-9e22123b-31cb-40f2-9b7c-8f47f3abb055.mp4

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653328075693929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-05-31 15:13
This can be external!

**Comment by mallenexpensify** [comment] 2022-05-31 20:29
@tgolen , before posting a job, can you confirm that this offline-related issue is OK to work on while we're doing other offline work?

**Comment by luacmartins** [comment] 2022-05-31 22:45
Tim is ooo until next week. My two cents: this seems to be a purely UI related issue and should not interfere with any of the API and Offline refactors we are currently doing, so I think we can go ahead with it. I'm happy to wait for Tim's opinion or be proven wrong though.

**Comment by mallenexpensify** [comment] 2022-06-01 00:08
Thanks @luacmartins , my intention wasn't to second-guess your adding of the `External` label, I know we've been particular with offline-related issues.  Moving along! 
https://www.upwork.com/jobs/~016e0f7862d665f075

**Comment by allroundexperts** [comment] 2022-06-01 23:02
Couldn't reproduce this @luacmartins. Can you please confirm again?

**Comment by luacmartins** [comment] 2022-06-01 23:16
I couldn't reproduce it anymore either. @mvtglobally can you confirm if this is still reproducible?

**Comment by luacmartins** [comment] 2022-06-08 20:56
Still looking for proposals!

**Comment by mallenexpensify** [comment] 2022-06-09 23:08
Doubled price to $500
https://www.upwork.com/jobs/~016e0f7862d665f075

**Comment by sobitneupane** [comment] 2022-06-13 08:48
**Proposal:**
Reason: `marginRight` is passed in `imageStyles` prop from `ReportActionItemSingle` to `Avatar`. It is only used in `<Image />` component in `Avatar`.

So, to get rid off the issue, we should use `imageStyles` around `Icon` as well Or, we can use it in view that wraps both `<Image />` and `<Icon />`  component.

https://github.com/Expensify/App/blob/6bac9af7294877114f8bf9532ff7b8c46146c90d/src/components/Avatar.js#L65-L70
```diff
+<View style={this.props.imageStyles}>
    <Icon
        src={this.state.imageError ? this.props.fallbackIcon : this.props.source}
        height={iconSize}
        width={iconSize}
        fill={this.state.imageError ? themeColors.offline : this.props.fill}
    />
+</View>
```

**Comment by luacmartins** [comment] 2022-06-13 13:08
@sobitneupane I think adding a view to wrap both Image and Icon is the better solution. @rushatgabhane what do you think?

**Comment by rushatgabhane** [comment] 2022-06-13 13:16
> `marginRight` is passed in `imageStyles` prop to Avatar. It is only used in` <Image />` component in Avatar, but not by `<Icon />`

@sobitneupane Yeah, that's the root cause. Nice find! 

> I think adding a view to wrap both Image and Icon is the better solution

@luacmartins I agree as well! I like @sobitneupane's [proposal](https://github.com/Expensify/App/issues/9249#issuecomment-1153649295)
🎀 👀 🎀 C+ reviewed

**Comment by luacmartins** [comment] 2022-06-13 16:11
Agreed! @sobitneupane I'll assign you to this issue.

**Comment by mallenexpensify** [comment] 2022-06-13 20:40
Hired @rushatgabhane for C+ and @sobitneupane for the job, bumped to `Weekly`

**Comment by mallenexpensify** [comment] 2022-06-22 17:24
On staging as of two hours ago

**Comment by luacmartins** [comment] 2022-07-06 20:04
I believe this is good to be paid out!

**Comment by luacmartins** [comment] 2022-07-11 14:18
@mallenexpensify Is ooo until tomorrow. Payment should be issued once he’s back!

**Comment by luacmartins** [comment] 2022-07-13 21:36
Actually @mallenexpensify is ooo until August 13th. Reapplying the External label to assign someone new and process the payment!

**Comment by luacmartins** [comment] 2022-07-13 21:37
@Christinadobrzyn can you arrange the payments due for this fix? @mallenexpensify seems to be ooo until Aug 13. Thank you!

**Comment by Christinadobrzyn** [comment] 2022-07-13 23:10
Paid $500 to @rushatgabhane for C+ and $500 to @sobitneupane for the fix! Closed job and now closing this GH and complete.

**Closed by Christinadobrzyn** 2022-07-13 23:10 UTC
Labels: Exported, External, Engineering, Daily, Awaiting Payment
