### ISSUE TITLE
[HOLD for checklist] [$1000] Android - Details - When entering numbers on each line, 3 dots will be displayed on the second line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22453] opened 2023-07-07 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21553
## Action Performed:
1. Login to ND
2. Click on + icon and select Assign task option
3. Enter title and description(with multiple line ~30line)
4. Click on the Next button

## Expected Result:
The information entered in the second line should be displayed correctly without 3 dots. All other apps don't show the 3 dots

## Actual Result:
When entering numbers on each line, 3 dots will be displayed on the second line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6d02cc65-e5f3-4295-856a-5e3ae337ab68

![21553 android photo](https://github.com/Expensify/App/assets/78819774/93dd225f-242e-4fd8-b6ce-fe18205459ee)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f634e6d328dcb7fb</li>
        <li>Upwork Job ID: 1678879714211528704</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-07-10 19:51
Looks like a dupe of - https://github.com/Expensify/App/issues/21825#issuecomment-1629630958 asking

**Comment by Christinadobrzyn** [comment] 2023-07-11 21:31
You're right @allroundexperts - not related! 

I can only reproduce this on Android App: 

![image](https://github.com/Expensify/App/assets/51066321/85be629d-1611-4fec-9286-2db72deb6d09)

adding external

**Comment by srikarparsi** [comment] 2023-07-12 16:48
Looks good to me as well, thanks @allroundexperts and @narefyev91!

**Comment by Christinadobrzyn** [comment] 2023-07-12 17:27
@narefyev91 I'm not sure why you weren't automatically hired to this Upwork job but can you please send me your Upwork link so I can hire you as C+?

**Comment by narefyev91** [comment] 2023-07-13 06:47
> @narefyev91 I'm not sure why you weren't automatically hired to this Upwork job but can you please send me your Upwork link so I can hire you as C+?

@Christinadobrzyn Hey! I'm from Callstack - no needs any payments from Upwork

**Comment by Christinadobrzyn** [comment] 2023-07-14 18:18
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing the PR and then it'll be ready for payment based on https://www.upwork.com/ab/applicants/1678879714211528704/job-details

@allroundexperts make sure to accept the offer in Upwork https://www.upwork.com/jobs/~01f634e6d328dcb7fb

**Comment by greg-schroeder** [comment] 2023-07-24 18:33
@allroundexperts is a on NewDot payment beta, @narefyev91 is Call Stack, and the issue reporter was Applause. So, no payments actually need to be made via Upwork here. 🎉 

Just need the checklist completed @narefyev91!

**Comment by greg-schroeder** [comment] 2023-07-26 21:19
Waiting for checklist

**Comment by greg-schroeder** [comment] 2023-07-31 14:29
@narefyev91 / @allroundexperts can anyone take care of this checklist so we can close this out?

**Comment by greg-schroeder** [comment] 2023-08-01 17:27
hmm. I think you're right. It seems a bit too niche to be added as a recurring test in this manner. Appreciate your help with the checklist :)

**Closed by greg-schroeder** 2023-08-01 17:27 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-02 23:05
Reviewed [details](https://github.com/Expensify/App/issues/22453#issuecomment-1648402378) for @allroundexperts. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
