### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Web - Chat - Able to type in composer while popover is open

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25485] opened 2023-08-18 13:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Right click on any message
3. Write anything from keyboard
4. Observe composer

## Expected Result:

When any popover is open, composer should be blurred and not able to type in composer

The fix should not break the current behavior (when none of the popover or RHP modal is open, typing anything should focus on the composer automatically but not paste)

## Actual Result:
 You're able to type via the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ae1a5854-368d-4165-b79f-65080cdbd075

https://github.com/Expensify/App/assets/115492554/5556d548-bf5b-46f8-90ee-a5139b22ca5b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aimane

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691526238059509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fecf2f053b61b171</li>
        <li>Upwork Job ID: 1693637662419955712</li>
        <li>Last Price Increase: 2023-10-19</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27015731</li>
<li>mkhutornyi | Contributor | 27015733</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @maddylewis</details>

**Comment by tymatein** [comment] 2023-08-18 16:47
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - Able to type in composer while popover is open

### What is the root cause of that problem?
[PopoverWithoutOverlay](https://github.com/Expensify/App/blob/main/src/components/PopoverWithoutOverlay/index.js#L39) does not call the function [Modal.setModalVisibility](https://github.com/Expensify/App/blob/main/src/libs/actions/Modal.js#L48). Therefore the [ReportActionCompose](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L713C82-L713C106) doesn't know about any opened popup.

### What changes do you think we should make in order to solve the problem?
[PopoverWithoutOverlay](https://github.com/Expensify/App/blob/main/src/components/PopoverWithoutOverlay/index.js#L39) should call the function [Modal.setModalVisibility](https://github.com/Expensify/App/blob/main/src/libs/actions/Modal.js#L48). We can add optional prop `shouldSetModalVisibility` (default true) to disable calling the function Modal.setModalVisibility, as it is done in the [BaseModal](https://github.com/Expensify/App/blob/main/src/components/Modal/BaseModal.js#L113).

Then we can remove [this.state.isMenuVisible from ReportActionCompose](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L713C82-L713C106) because the condition `this.props.modal.isVisible` is sufficient.

### What alternative solutions did you explore? (Optional)
none

**Comment by maddylewis** [comment] 2023-08-21 14:57
@aimane-chnaif - i think option 2

**Comment by maddylewis** [comment] 2023-08-24 19:47
okay, gotcha. how would you like to proceed? let me know if you would like me to update the OP with those details you outlined here https://github.com/Expensify/App/issues/25485#issuecomment-1686507870

**Comment by bernisz** [comment] 2023-08-27 15:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - Able to type in composer while popover is open
### What is the root cause of that problem?
There is no check in *checkComposerVisibility* function that indicates if *ReportActionContextMenu* popover is open. 
### What changes do you think we should make in order to solve the problem?
##### Changes in ReportScreen.js
We can create a new flag *isReportActionContextMenuVisible* with setter that can be accessed by children using ReportScreenContext.Provider

##### Changes in ReportActionItem.js
In *showPopover* function add these lines: 
```javascript
// Hides older context menu when right-clicking on other action item
ReportActionContextMenu.hideContextMenu();

setIsReportActionContextMenuVisible(true);
```

Also need to update *toggleContextMenuFromActiveReportAction* function to handle *isReportActionContextMenuVisible* state when closing popover:
```javascript
const toggleContextMenuFromActiveReportAction = useCallback(() => {
        const activeReportAction = ReportActionContextMenu.isActiveReportAction(props.action.reportActionID);
        setIsContextMenuActive(activeReportAction);
        setIsReportActionContextMenuVisible(activeReportAction);
    }, [props.action.reportActionID, setIsContextMenuVisible]);
```

##### Changes in ComposerWithSuggestions.js
Update *checkComposerVisibility* function by adding *isReportActionContextMenuVisible* to condition:
```javascript
const {isReportActionContextMenuVisible} = useContext(ReportScreenContext);

const checkComposerVisibility = useCallback(() => {
        const isComposerCoveredUp = EmojiPickerActions.isEmojiPickerVisible() || isMenuVisible || isReportActionContextMenuVisible || modal.isVisible;
        return !isComposerCoveredUp;
    }, [isReportActionContextMenuVisible, isMenuVisible, modal.isVisible]);
```
## Result
[screen-capture.webm](https://github.com/Expensify/App/assets/52483754/132f17d6-d05d-47d5-bc1b-7d6e0d3c2b76)

## Note:

I noticed that now in main branch you can paste when popover is visible. Is this bug also included in this issue scope?

**Comment by bernisz** [comment] 2023-08-27 15:27
Contributor details
Your Expensify account email: bernardas.zukas@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e0c3c2f51c15da8b

**Comment by bernisz** [comment] 2023-08-28 20:07
## Proposal
[[Updated]](https://github.com/Expensify/App/issues/25485#issuecomment-1694693882)

**Comment by maddylewis** [comment] 2023-09-05 13:54
@aimane-chnaif - let me know how we're looking on proposals. i can adjust the bounty if necessary.

**Comment by tymatein** [comment] 2023-09-07 09:16
I'm not sure if you asked for the git-diff... Anyway the usage of PopoverProvider in ComposerWithSuggestions:
```diff
diff --git a/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js b/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js
index e5ab88b289..4a330cf36d 100644
--- a/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js
+++ b/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js
@@ -31,2 +31,3 @@ import useLocalize from '../../../../hooks/useLocalize';
 import compose from '../../../../libs/compose';
+import {PopoverContext} from '../../../../components/PopoverProvider';
 import withKeyboardState from '../../../../components/withKeyboardState';
@@ -81,3 +82,2 @@ function ComposerWithSuggestions({
     isComposerFullSize,
-    isMenuVisible,
     inputPlaceholder,
@@ -101,2 +101,3 @@ function ComposerWithSuggestions({
 }) {
+    const {isOpen: isPopoverOpen} = React.useContext(PopoverContext);
     const {preferredLocale} = useLocalize();
@@ -352,5 +353,6 @@ function ComposerWithSuggestions({
     const checkComposerVisibility = useCallback(() => {
-        const isComposerCoveredUp = EmojiPickerActions.isEmojiPickerVisible() || isMenuVisible || modal.isVisible;
+        const isInputFocused = textInputRef.current && textInputRef.current.isFocused();
+        const isComposerCoveredUp = modal.isVisible || (!isInputFocused && isPopoverOpen);
         return !isComposerCoveredUp;
-    }, [isMenuVisible, modal.isVisible]);
+    }, [modal.isVisible, isPopoverOpen]);
```

---
Regarding mentioned issue with caching of the handlePaste and handleWheel functions in the [Composer](https://github.com/Expensify/App/blob/3f9f1e6e2ce91468a536755f8d5830a2f77d7eaa/src/components/Composer/index.js#L399) component.

The `composer` component internally uses the `checkComposerVisibility` function, which is passed to it in `props`. The `checkComposerVisibility` function is called inside the `handlePaste` function, which is cached (useCallback) with the correct dependencies. But the `handlePaste` function is registered for the document's `paste` event inside useEffect without any dependencies (empty array). Which means that the outdated function `checkComposerVisibility` (the version from the component initialization) is called for the `paste` event.
Therefore, even if the input field is not focused and a popup is opened, the user is still able to paste text into the field.

This issue needs to be fixed to get the desired [behavior](https://github.com/Expensify/App/issues/25485#issuecomment-1686507870)

```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index cbd22cc39d..176335a9d5 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -367,36 +367,41 @@ function Composer({
         updateNumberOfLines();
     }, [updateNumberOfLines]);
 
+    useEffect(() => {
+        if (_.isFunction(forwardedRef)) {
+            forwardedRef(textInput.current);
+        }
+
+        return () => {
+            if (isReportActionCompose) {
+                return;
+            }
+            ReportActionComposeFocusManager.clear();
+        };
+    }, [isReportActionCompose, forwardedRef]);
+
     useEffect(() => {
         // we need to handle listeners on navigation focus/blur as Composer is not unmounting
         // when navigating away to different report
         const unsubscribeFocus = navigation.addListener('focus', () => document.addEventListener('paste', handlePaste));
         const unsubscribeBlur = navigation.addListener('blur', () => document.removeEventListener('paste', handlePaste));
 
-        if (_.isFunction(forwardedRef)) {
-            forwardedRef(textInput.current);
-        }
-
         if (textInput.current) {
             document.addEventListener('paste', handlePaste);
             textInput.current.addEventListener('wheel', handleWheel);
         }
 
         return () => {
-            if (!isReportActionCompose) {
-                ReportActionComposeFocusManager.clear();
-            }
             unsubscribeFocus();
             unsubscribeBlur();
             document.removeEventListener('paste', handlePaste);
-            // eslint-disable-next-line es/no-optional-chaining
+
             if (!textInput.current) {
                 return;
             }
             textInput.current.removeEventListener('wheel', handleWheel);
         };
-        // eslint-disable-next-line react-hooks/exhaustive-deps
-    }, []);
+    }, [navigation, handlePaste, handleWheel]);
 
     const handleKeyPress = useCallback(
         (e) => {
```

**Comment by tymatein** [comment] 2023-09-07 10:05
Ahh, sorry. 

I used `React.useContext` to get the `isOpen` variable of the `PopoverProvider`. However, for clarity in the rest of the code, I have renamed it to `isPopoverOpen`.

The `checkComposerVisibility` function should be changed:
* the explicit check if the emoji picker or composer menu is displayed should be removed in favour of `isPopoverOpen` from PopoverContext
* the check `isPopoverOpen` must be added
* the check `isInputFocused` must be added

**Comment by tymatein** [comment] 2023-09-07 15:45
Fixed issue:


https://github.com/Expensify/App/assets/134623449/87d15588-ec9b-402c-afe6-589e64ce4330

**Comment by maddylewis** [comment] 2023-09-11 13:14
@aimane-chnaif - let me know what we're thinking after this comment here https://github.com/Expensify/App/issues/25485#issuecomment-1712406801

**Comment by maddylewis** [comment] 2023-09-13 18:58
@aimane-chnaif - bump on the two previous comments

**Comment by maddylewis** [comment] 2023-09-18 18:14
> @maddylewis @aimane-chnaif this issue is now 4 weeks old and preventing us from maintaining WAQ, can you:
> 
> * Decide whether any proposals currently meet our guidelines and can be approved as-is today
> * If no proposals meet that standard, please take this issue internal and treat it as one of your highest priorities
> * If you have any questions, don't hesitate to start a discussion in #expensify-open-source
> 
> Thanks!

@aimane-chnaif - just want to make sure none of the existing proposals could work for this one. also, lmk if you want me to reach out in expensify-open-source to get a discussion started about this one.

**Comment by tymatein** [comment] 2023-09-18 19:31
The proposal https://github.com/Expensify/App/issues/25485#issuecomment-1684178531 is updated. The input field is blurred if any popup is opened.

**Comment by tymatein** [comment] 2023-09-22 11:29
@aimane-chnaif Thanks for your help, I moved the useEffect with input.blur from ComposerWithSuggestions into Composer. Proposal updated https://github.com/Expensify/App/issues/25485#issuecomment-1684178531

**Comment by maddylewis** [comment] 2023-09-27 21:15
@aimane-chnaif - lmk how proposal review is going - ty!

**Comment by maddylewis** [comment] 2023-10-02 13:26
@aimane-chnaif - lmk if you don't have the bandwidth for this one and i can pull in someone else 👍

**Comment by amyevans** [comment] 2023-10-03 23:59
Will take a look later today!

**Comment by tymatein** [comment] 2023-10-04 08:56
Proposal https://github.com/Expensify/App/issues/25485#issuecomment-1743233076 is not fixing this https://github.com/Expensify/App/issues/25485#issuecomment-1684208973

**Comment by maddylewis** [comment] 2023-10-16 17:02
moving to daily since payments are coming up

**Comment by maddylewis** [comment] 2023-10-19 13:35
Okay, payments were sent. 

@aimane-chnaif - will you take a look at this checklist when you get a chance - thanks! https://github.com/Expensify/App/issues/25485#issuecomment-1756774258

**Comment by maddylewis** [comment] 2023-10-23 02:41
my thinking there is that the proposal that was used, the review and implementation happened after the update was live. is that fair? lmk if that's not accurate.

**Comment by amyevans** [comment] 2023-10-25 13:29
Friendly bump @maddylewis for payment

**Comment by maddylewis** [comment] 2023-10-26 00:07
kk, ty for the breakdown @mkhutornyi. it sounds like i owe both @aimane-chnaif and @mkhutornyi an additional payment. 

can you clarify the urgency bonus? i have the following info - Contributor hired Oct 2 and PR merged Oct 9.

**Comment by maddylewis** [comment] 2023-10-28 02:52
Okay, sounds good! I sent both the Contributor and the C+ an additional $1k payment for this one. regression test steps added. closing!

**Closed by maddylewis** 2023-10-28 02:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
