### ISSUE TITLE
[payment due 8-27][$250] Expense - Mark as cash button only appears in combined report after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47084] opened 2024-08-08 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4835412
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to [applausetester+pendingreceipt@applause.expensifail.com](mailto:applausetester+pendingreceipt@applause.expensifail.com)
3. Go to report https://staging.new.expensify.com/r/8085254050283210
(the report has Mark as cash button)
4. Submit another expense
5. Click on the expense preview in the main chat to go to expense report
6. Right click on the expense submitted in Step 4 > Delete expense
7. Delete the expense in Step 4
8. Note that the combined report shows payment button instead of Mark as cash button
9. Refresh the page

## Expected Result:
In Step 8, the combined report should display Mark as cash button after the other expense is deleted

## Actual Result:
In Step 8, the combined report still displays payment button after the other expense is deleted
Mark as cash button only appears in the combined report after the report is refreshed (Step 9)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bfc5965b-ba9b-4e9e-a505-87f56515c13b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d4c9cdcd61832cf</li>
        <li>Upwork Job ID: 1823113857893584807</li>
        <li>Last Price Increase: 2024-08-12</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103529152</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-08 15:22
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-08 15:22
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-08-08 16:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 8, the combined report still displays payment button after the other expense is deleted
Mark as cash button only appears in the combined report after the report is refreshed (Step 9)

### What is the root cause of that problem?
The `Mask as cash` button is displayed if all transactions have RTER Violation.


https://github.com/Expensify/App/blob/e74866167ebd6bdbd994badd05ee80952b69f458/src/components/MoneyReportHeader.tsx#L306

https://github.com/Expensify/App/blob/e74866167ebd6bdbd994badd05ee80952b69f458/src/components/MoneyReportHeader.tsx#L109


When we delete a transaction, `allTransactions` isn't updated because the dependency is only `moneyRequestReport?.reportID`

https://github.com/Expensify/App/blob/e74866167ebd6bdbd994badd05ee80952b69f458/src/components/MoneyReportHeader.tsx#L101

Then `allHavePendingRTERViolation` is `false` and `Mask as cash` button doesn't appear until we refresh the page

### What changes do you think we should make in order to solve the problem?
We should add `transactions` [here](https://github.com/Expensify/App/blob/e74866167ebd6bdbd994badd05ee80952b69f458/src/components/MoneyReportHeader.tsx#L73) as a dependency of the `useMemo` here as we do for `ReportPreview` [here](https://github.com/Expensify/App/blob/d406254f3fc58a28c761cd353d4a4ac5cb81b427/src/components/ReportActionItem/ReportPreview.tsx#L123)


https://github.com/Expensify/App/blob/e74866167ebd6bdbd994badd05ee80952b69f458/src/components/MoneyReportHeader.tsx#L101

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-08-09 22:12
wave-control project for pending card receipts. CC: @yuwenmemon @JmillsExpensify

**Comment by Christinadobrzyn** [comment] 2024-08-12 21:46
I'm not sure if this can be external but we'll add a C+ to see what they think is best.

**Comment by Christinadobrzyn** [comment] 2024-08-14 18:55
hi @yuwenmemon I know you just got back but can you take a peek at this [review](https://github.com/Expensify/App/issues/47084#issuecomment-2285377780)? TY!

**Comment by Christinadobrzyn** [comment] 2024-08-20 21:04
[PR](https://github.com/Expensify/App/pull/47473) is in staging so getting close!

**Comment by Christinadobrzyn** [comment] 2024-08-27 20:58
Payment didn't trigger for this one. Looks like this can be paid today. 

Payouts due:

- [ ] Contributor: $250 @nkdengineer 
- [ ] Contributor+: $250 @parasharrajat (paid via NewDot)

@nkdengineer are you paid in NewDot? 
Do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-08-28 22:55
Regression test - https://github.com/Expensify/Expensify/issues/424176

Paid out based on this [payment summary ](https://github.com/Expensify/App/issues/47084#issuecomment-2313527404). Closing!

**Closed by Christinadobrzyn** 2024-08-28 22:55 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-09-02 12:01
$250 approved for @parasharrajat
