### ISSUE TITLE
Distance - Distance rate changes to personal expense distance rate after editing distance

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38299] opened 2024-03-14 12:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Create a new workspace.
3. Go to workspace chat.
4. Create a distance request.
5. Go to distance request details page.
6. Note that distance rate.
7. Click Distance.
8. Edit the distance and save it.

## Expected Result:
The distance rate for the new distance will follow the workspace distance rate.

## Actual Result:
The distance rate for the new distance follows the personal expense distance rate after changing distance.
If the distance request is edited on Collect workspace as employee, there will be a red dot next to transaction thread in LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/247b5019-7f96-473d-91ee-b0b218a4eb45

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-14 12:23
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-14 12:24
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by puneetlath** [comment] 2024-03-14 17:23
Looks like this is a back-end issue. @neil-marcellini I see you recently have been working on P2P distance. Any ideas about the cause?

**Comment by trjExpensify** [comment] 2024-03-14 18:13
If it's P2P Distance related that project is moving to #vip-vsb. 👍

**Comment by puneetlath** [comment] 2024-03-14 18:37
It actually affects workspace requests :(

**Comment by trjExpensify** [comment] 2024-03-14 18:54
Yeah, being discussed here: https://expensify.slack.com/archives/C07J32337/p1710440479773439

**Comment by nkuoch** [comment] 2024-03-14 21:12
[A fix](https://github.com/Expensify/Web-Expensify/pull/41281) has been sent to Web staging. Can you please re-test?

**Comment by neil-marcellini** [comment] 2024-03-15 10:10
Note that this bug also only occurs if your personal workspace and workspace requested from have different reporting currencies. The easiest way to reproduce is to change the currency of the workspace to something other than USD.

**Comment by puneetlath** [comment] 2024-03-15 13:58
Just tested and it looks like it's working properly now. Closing this out!

**Closed by puneetlath** 2024-03-15 13:58 UTC
Labels: Engineering, Daily, Bug
