### ISSUE TITLE
[PAY WENTAO - FEB 7th][$500] BNP - Black screen appears on transfer from BNP to Attendee screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31779] opened 2023-11-23 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to FAB> Request money
3. Add amount and click Next

## Expected Result:
Attendee screen should be display and no lagging and transfer error should be present

## Actual Result:
Black screen appears on transfer from BNP to Attendee screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/596d1b2e-85c1-4425-bb96-7c157c450104

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d583113b9a89a85a</li>
        <li>Upwork Job ID: 1727650719394332672</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27979335</li>
</ul></li>
    </ul>
</details>

**Comment by felix-lambert** [comment] 2023-11-23 18:07
I cannot reproduce the bug. Is there something i have been missing?

https://github.com/Expensify/App/assets/6106055/7be93b57-4b80-457e-85e7-8fcf0b6951be

**Comment by felix-lambert** [comment] 2023-11-23 18:09
Contributor details
Your Expensify account email: totoflavien45@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7ffb7510bab69aa?viewMode=1

**Comment by brunovjk** [comment] 2023-11-23 19:20
> I cannot reproduce the bug. Is there something i have been missing?
> 
>  Screen.Recording.2023-11-23.at.13.05.06.mov

I believe you successfully reproduced the error, and it appears to occur quite promptly. From my understanding of the 'issue,' there is a noticeable lag after selecting the amount. The lag in the "issue" reproduction video seems high, on my machine, it was moderate, and on yours, it seems to be very fast.

Additionally, there is an issue with the transition after selecting the amount. Currently, a black (or green) screen appears first, and then we proceed to select the participant. I was also able to reproduce this within a workspace, where after selecting the amount, participants are already selected, but the green screen remains in the middle of the transition.

My question for those with more experience is: why, in some scenarios, such as editing a field in a request for money, do the transitions occur like slides, smoothly sliding between pages? In other scenarios, the previous screen disappears, and a new one appears. In the case of this 'issue,' a green screen appears between the previous and next screens.

Thanks.

**Comment by jliexpensify** [comment] 2023-11-23 23:21
@izarutskaya curioous why you're testing on 1.4.2.0? I'm on staging and can see this issue on v1.4.3-1 - shouldn't you be testing on the most recent versions?

Anyway, I can repro this one - the lag is about 1 second.

**Comment by felix-lambert** [comment] 2023-11-24 02:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are experiencing a lag in transition effects within our application, most noticeably when interacting with a large number of contact entries. This issue affects the fluidity and responsiveness of the user interface, particularly during operations that involve the contact list.

### What is the root cause of that problem?
The root cause of this lag is the intensive computational demand of the `getOptions` function when processing a large dataset of contacts. Originally, this function took around 160ms to execute, which was significantly reduced to 15ms through optimization. Despite this improvement, the time required to process a high volume of contacts still contributes to the noticeable lag in the UI transitions.

### What changes do you think we should make in order to solve the problem?
To address this issue, we propose the following changes:
1. **Memoization of the `getOptions` Function**: By memoizing `getOptions`, we prevent redundant recalculations for repeated calls with identical arguments, reducing the load time from 160ms to 15ms.
2. **Optimization of Data Processing**: Streamlining operations within the function, such as loop conditions and data structure usage, for more efficient processing.

### What alternative solutions did you explore? (Optional)
**Pagination/Infinite Scroll**: Instead of loading all contacts at once, implementing pagination or an infinite scroll feature would load a smaller subset of contacts initially, with more loading as needed. This approach would significantly reduce the initial data load and improve UI responsiveness.

**Comment by jliexpensify** [comment] 2023-11-27 21:51
Bumping @ntdiary for reviews please!

**Comment by felix-lambert** [comment] 2023-11-28 15:01
Yes I agree. We can see how to add a delay so that the animation of the modal is finished before the invocation of the getOptions function. Do you want me to work on this issue?

**Comment by felix-lambert** [comment] 2023-11-29 02:56
Hey [ntdiary](https://github.com/ntdiary) sorry just discovering this great project :)

Was thinking of doing something like this >

```
useEffect(() => {
        const unsubscribe = navigation.addListener('transitionEnd', () => {

            // Code to execute after transition ends
            const res = OptionsListUtils.getFilteredOptions(
                reports,
                personalDetails,
                betas,
                searchTerm,
                participants, // ... other parameters
            );


            setNewChatOptions({
                recentReports: res.recentReports,
                personalDetails: res.personalDetails,
                userToInvite: res.userToInvite,
            });
        });

        return unsubscribe;
    }, [navigation]);
```

Don't hesitate if you need more details. I'm basically detecting when the animation of the transition is finished :)

**Comment by brunovjk** [comment] 2023-11-29 20:24
@ntdiary, I appreciate your answer. I'm currently in the process of testing approaches to ensure a seamless integration without introducing new bugs. I'll provide a detailed update as soon as I have a concrete async implementation.

While implementing asynchronous operations to address the transition lag, I noticed that the skeleton placeholder, which is typically rendered in other parts of the application during the processing of `getOptions`, is not appearing as expected in this specific issue. Do you have an idea why? Is it a expected behavior?

**Comment by felix-lambert** [comment] 2023-11-29 22:01
@brunovjk thanks I did :)

**Comment by brunovjk** [comment] 2023-11-30 15:00
## Proposal
[Updated](https://github.com/Expensify/App/issues/31779#issuecomment-1830039239)

**Comment by brunovjk** [comment] 2023-12-01 11:18
Thank you very much for the review @ntdiary.
I see, I also think it would be better if we can optimize `getOptions` function. I'm still working on it, I'll get back to you as soon as possible.

> By the way, I actually tested `didScreenTransitionEnd` two days ago. When the page is refreshed, both `transitionEnd` and `didScreenTransitionEnd` within the component does not work, causing the options not to be loaded.

Interesting, it makes sense, I'll continue with `getOptions` but I believe that the [MoneyRequestParticipantsPage](https://github.com/Expensify/App/blob/2e8de3ffd53f40139a927bc60461feadefe88d78/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js) and [MoneyRequestParticipantsSelector](https://github.com/Expensify/App/blob/2e8de3ffd53f40139a927bc60461feadefe88d78/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) logic should be reviewed,
`WorkspaceInvitePage` has a similar job and LGTM:
https://github.com/Expensify/App/blob/27fd4e24a5dfc859bcafcb4e749f9b857e6813d5/src/pages/workspace/WorkspaceInvitePage.js#L230-L236

**Comment by felix-lambert** [comment] 2023-12-04 14:53
To make sure getOptions is being called after refresh maybe we could do that

```
    useEffect(() => {
        setTimeout(() => {
            // Code to execute after transition ends
            const chatOptions = OptionsListUtils.getFilteredOptionsClone(
                reports,
                personalDetails,
                betas,
                searchTerm,
                participants,
                CONST.EXPENSIFY_EMAILS,

                // If we are using this component in the "Request money" flow then we pass the includeOwnedWorkspaceChats argument so that the current user
                // sees the option to request money from their admin on their own Workspace Chat.
                iouType === CONST.IOU.TYPE.REQUEST,

                // We don't want to include any P2P options like personal details or reports that are not workspace chats for certain features.
                !isDistanceRequest,
                // We don't want the user to be able to invite individuals when they are in the "Distance request" flow for now.
                // This functionality is being built here: https://github.com/Expensify/App/issues/23291
                !isDistanceRequest,
                true,
            );

            setNewChatOptions({
                recentReports: chatOptions.recentReports,
                personalDetails: chatOptions.personalDetails,
                userToInvite: chatOptions.userToInvite,
            });
        }, CONST.ANIMATED_TRANSITION);
    }, []);
```

The performance lag in theOptionsListUtils.js file is caused by the way the personalDetails object is handled. At [line 433](https://github.com/Expensify/App/blob/5bd6d8caa45d9a55f91087bf18f9ebb87c9a6c36/src/libs/OptionsListUtils.js#L121), there's a loop where [personalDetails](https://github.com/Expensify/App/blob/5bd6d8caa45d9a55f91087bf18f9ebb87c9a6c36/src/libs/OptionsListUtils.js#L469) is repeatedly accessed within each iteration. This object, being very large, leads to a heavy computational load. The issue is exacerbated because each loop iteration requires accessing this large object to retrieve values for the `createOption` function, resulting in significant performance degradation due to the intensive and repeated data processing involved.

To optimize the display of the contact list, I have a few options to propose for addressing the performance issue.

1. Necessity of All createOption Values: Assess whether it's essential to use all values from the createOption function for displaying the contact list. If not all values are necessary, this could reduce the computational load.
2. Alternative Data Handling Strategies: Avoiding personalDetails in the Loop: Explore methods to access the required values without passing the personalDetails object within the map loop. This could potentially alleviate the performance issue.
3. Server-side Data Flattening: Consider flattening the data on the server side before it's sent to the client. This approach could simplify the data structure, making it more efficient to process on the client side.
4. Implementing Pagination: Loading Contacts in Chunks: Implement a pagination system where only a subset of the contact list, say 50 contacts, is loaded initially. This can significantly reduce the initial data load.

Which of these approaches do you think would be the best to explore further?

**Comment by brunovjk** [comment] 2023-12-04 19:24
Thank you for the review, @ntdiary.

I agree that optimizing the `getOptions` function would be beneficial. However, there's a challenge – the loops inside `getOptions` seem to be causing lag, and their performance is dependent on the size of the contact list. While attempting to enhance the efficiency of `getOptions` and these loops, I've encountered difficulties. It's expected that the function may take longer if the database is extensive, and I've been exploring optimizations without much success. I believe by using the skeleton loading approach, as suggested, we can solve this issue.

However, we still face the problem of page reloading:

> By the way, I actually tested `didScreenTransitionEnd` two days ago. When the page is refreshed, both `transitionEnd` and `didScreenTransitionEnd` within the component do not work, causing the options not to load.

I've observed a similar situation in other parts of our app, where the contact list fails to load after a page refresh. For instance:

![image](https://github.com/Expensify/App/assets/95647348/efe41ed0-50bc-4712-9d99-130d8da12fc8)

This seems peculiar since:
```
return (
    <ScreenWrapper
    ...
    {({safeAreaPaddingBottomStyle, didScreenTransitionEnd}) => (
```
successfully loads when the page is refreshed. Any insights, @ntdiary and @felix-lambert?

@felix-lambert, I tested your latest proposal. IMP using a hardcoded delay with `setTimeout` introduces an arbitrary delay (`CONST.ANIMATED_TRANSITION`). While it may work in most cases, it's not foolproof, as the duration of the transition can vary. Depending on the timing of the transition, network conditions, or other factors, this solution may not be reliable in all scenarios.

**Comment by jliexpensify** [comment] 2023-12-04 23:58
Bumping @ntdiary

**Comment by brunovjk** [comment] 2023-12-05 13:21
> Still reviewing the updated proposal.

@ntdiary did you encounter the same problem, when we refresh the page and the list does not load, in other parts of the app? Thanks.

**Comment by lakchote** [comment] 2023-12-06 08:29
Thank you @ntdiary for your review! I do prefer to reuse the existing `didScreenTransitionEnd` variable too.

Let's focus on the first point which is the black screen during the transition.

Feel free to create separate issues for the two other points already mentioned.

@brunovjk's proposal LGTM 👍

**Comment by brunovjk** [comment] 2023-12-06 12:49
Thank you for the review @ntdiary and @lakchote.

I create a PR to use `didScreenTransitionEnd`.

But we still have the skeleton loading issue, it's not being triggered.
I checked and `isOptionsDataReady ` looks always `true`:

https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L225

I was thinking in move to a `useState` and control it only after transition end:

```
...
const [isOptionsDataReady, setIsOptionsDataReady] = useState(false);
...
     useEffect(() => {
        if (didScreenTransitionEnd) {
...
     setIsOptionsDataReady(ReportUtils.isReportDataReady() && OptionsListUtils.isPersonalDetailsReady(personalDetails))        
...
        }
    }, [betas, reports, participants, personalDetails, translate, searchTerm, setNewChatOptions, iouType, isDistanceRequest, didScreenTransitionEnd, setIsOptionsDataReady]);
```

What do you guys think?

**Comment by lakchote** [comment] 2023-12-08 09:14
> What do you guys think?

I'm fine with that, but let's hear @ntdiary's opinion on it too!

**Comment by brunovjk** [comment] 2023-12-12 10:09
Thank you for the feedback @ntdiary, makes senses, I liked tthe shouldShowOptions={didScreenTransitionEnd && isOptionsDataReady} approach.
Lets wait then :D

**Comment by brunovjk** [comment] 2023-12-14 19:24
@ntdiary and @lakchote the [refactored money request navigation](https://github.com/Expensify/App/pull/28618) was merged but the initial [issue](https://github.com/Expensify/App/issues/31779) remains.

I think we can apply the same [solution](https://github.com/Expensify/App/issues/31779#issuecomment-1830039239) proposed previously.

I updated [the PR](https://github.com/Expensify/App/pull/32665) to apply changes at new components used.

**Comment by brunovjk** [comment] 2024-01-08 18:13
We're still investigating, [PR](https://github.com/Expensify/App/pull/32665)

**Comment by brunovjk** [comment] 2024-01-31 12:19
Hello @jliexpensify the [PR](https://github.com/Expensify/App/pull/32665) that fixed this issue was [deployed today](https://github.com/Expensify/App/pull/32665#issuecomment-1918256318), but I didn't link the issue correctly over there, so the automation was already broken, and I didn't receive the **HOLD payment for 7 days** tag. Do you think I should do something or is everything ok? Thanks for your time.

**Comment by jliexpensify** [comment] 2024-01-31 23:01
Hi @brunovjk - we generally pay 7 days after deployment to `Production` and I'll do a payment summary as well.

So I would say the payout date would be the 7th Feb?

**Comment by brunovjk** [comment] 2024-01-31 23:06
Awesome! Thank you @jliexpensify

**Comment by brunovjk** [comment] 2024-01-31 23:07
Exactly. Awesome! Thank you @jliexpensify

**Comment by jliexpensify** [comment] 2024-01-31 23:27
Payment Summary

- Contributor: @brunovjk - $500
- C+: @ntdiary - $500

@ntdiary anything on the checklist that needs to be completed?

[NEW UPWORKS JOB](https://www.upwork.com/jobs/~01ec6f2deff5fc3d24)

**Comment by jliexpensify** [comment] 2024-02-08 01:17
Hi @ntdiary , can you accept the offer so I can pay you?

**Comment by jliexpensify** [comment] 2024-02-08 01:27
Paid @brunovjk

**Comment by jliexpensify** [comment] 2024-02-08 02:44
Hey @ntdiary - there was an error when I tried paying you, can you confirm your got the payment?

**Comment by jliexpensify** [comment] 2024-02-08 02:46
Actually I think I know the issue - I may have accidentally created a per-hour contract instead of one for the full amount. Going to end this contract and re-hire you, sorry!

**Comment by jliexpensify** [comment] 2024-02-08 02:48
@ntdiary sorry, re-hired you!

**Comment by jliexpensify** [comment] 2024-02-08 02:55
Paid and job closed!

Upworks is so frustrating, there's no way to change a contract from hourly to fixed amount after it's been accepted!

**Closed** 2024-02-08 02:55 UTC
Labels: Reviewing, External, Daily, Bug
