### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Workspace - Incorrect Behavior When Inviting Existing User with Capitalized Email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25636] opened 2023-08-22 00:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any workspace
2. Open the "Members" page within the workspace
3. Click the "Invite" button and invite a new user
4. Go back to the "Members" page
5. Attempt to invite the same user again, but this time, capitalize the first letter of the user's email address or write the email address entirely in capital letters
6. Observe the description that is displayed

## Expected Result:
The description should clearly state that the user is already a member of the workspace

## Actual Result:
 Instead of the expected message, it displays "No results found" when inviting the same user with capitalized email letters

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d15a8865-ed2f-469b-89dc-49b5bfa0ab9d

https://github.com/Expensify/App/assets/78819774/87d52df5-797a-4172-a68e-cef92c179198

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Habben101

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691797768663379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c78f3bb410f312f</li>
        <li>Upwork Job ID: 1696552547259813888</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26416348</li>
<li>Habben101 | Reporter | 26416352</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-08-22 00:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Incorrect Behavior When Inviting Existing User with Capitalized Email

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/c435734d8cf360e964e20eea1fb54c541f6fa7ea/src/pages/workspace/WorkspaceInvitePage.js#L187-L196

We don't lowercase the search value before validating it
### What changes do you think we should make in order to solve the problem?
we should lowercase searchvalue before validating like this
```
const searchValue = searchTerm.trim().toLowerCase();
```

### Result

<img width="818" alt="Screenshot 2023-08-18 at 14 50 59" src="https://github.com/Expensify/App/assets/141406735/5f64016b-cb3a-49fc-8ef4-6985f421f0b4">

**Comment by esh-g** [comment] 2023-08-22 00:45
# Proposal

## Please re-state the problem
There is a difference of error messages between uppercase and lowercase emails.

## What is the root cause of this problem?
We are not converting the `searchTerm` to lowercase while comparing it to the excluded participants.

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/pages/workspace/WorkspaceInvitePage.js#L188

## What changes should be made in order to solve this problem?
We should convert the `searchTerm` to lowercase before comparing which can be done like this:
```js
const searchValue = searchTerm.trim().toLowerCase();
```

This is approach is being used in other places as well, so I think we will be consistent in that approach.
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/OptionsListUtils.js#L638
https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/components/EmojiPicker/EmojiPickerMenu/index.js#L420

## What other alternative approach did you explore? (Optional)
None

**Comment by muttmuure** [comment] 2023-08-29 15:57
Added external

**Comment by jjcoffee** [comment] 2023-08-30 13:30
So we've got three duplicate proposals here, all with the correct RCA and solution. @DylanDylann's [proposal](https://github.com/Expensify/App/issues/25636#issuecomment-1687248609) happens to be the first so we can go with that!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by DylanDylann** [comment] 2023-08-31 04:41
@jjcoffee PR is ready for review

**Comment by DylanDylann** [comment] 2023-09-11 05:32
@muttmuure Are we eligible for a bonus timeline here? The C+ contributor (@jjcoffee ) approved PR from 2023-08-31 [here](https://github.com/Expensify/App/pull/26364#pullrequestreview-1605038246) But we freeze merged in 2 last weeks.

**Comment by jjcoffee** [comment] 2023-09-11 08:50
@DylanDylann I think so, as long as it was ready to merge within the usual 3 days (see [this comment](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1693932139.950359/1693932182.328959) on Slack).

**Comment by jjcoffee** [comment] 2023-09-18 12:22
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23490
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23490#issuecomment-1723297235
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - checklist item already exists to ensure test steps cover all possible scenarios**
- [x] Determine if we should create a regression test for this bug. **No - fairly edge case and so not high value enough**
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by jjcoffee** [comment] 2023-09-25 13:05
@muttmuure Gentle bump for payment here. Also, I think this may be due the timeliness bonus as it was only delayed due to the merge freeze (see [this comment](https://github.com/Expensify/App/issues/25636#issuecomment-1713195812)).

**Comment by techievivek** [comment] 2023-09-29 02:21
Gentle bump @muttmuure ^

**Comment by techievivek** [comment] 2023-10-02 10:28
Gentle bump @muttmuure ^^

**Comment by muttmuure** [comment] 2023-10-04 13:27
Getting to this now

**Comment by muttmuure** [comment] 2023-10-04 13:39
Offers sent, including urgency bonus

**Comment by jjcoffee** [comment] 2023-10-04 13:44
@muttmuure Thanks, offer accepted!

**Comment by techievivek** [comment] 2023-10-09 09:32
@muttmuure are we done with the payment here? Can we close the issue now?

**Comment by muttmuure** [comment] 2023-10-11 12:38
Handling

**Comment by muttmuure** [comment] 2023-10-11 12:41
Just waiting on @DylanDylann to accept, then we can close out

**Comment by DylanDylann** [comment] 2023-10-11 13:17
@muttmuure I've accepted, thank you!

**Comment by muttmuure** [comment] 2023-10-11 16:29
Paid!

**Closed by muttmuure** 2023-10-11 16:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
