### ISSUE TITLE
[HOLD for payment 2023-10-25] Transition from OldDot to NewDot is slow and shows blank screen for long time

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27418] opened 2023-09-14 07:27 UTC
### Problem

Coming from https://expensify.slack.com/archives/C05LX9D6E07/p1694668433572469?thread_ts=1694666491.998029&cid=C05LX9D6E07

When a new lead user signs up on OldDot and they want to chat with their setup specialist in NewDot, we use a transition to new.expensify.com to keep their session going in this new app.

However, this transition seems to got very slow now and blank page is shown for over 15 seconds which is terrible UX.

Seems like the issue is that on a first load we dont have proper data to show the reports

![image](https://github.com/Expensify/App/assets/36083550/5c6235a7-bdbd-4b5a-86e0-dad6a4732eca)
after refreshing it works fine 
![image](https://github.com/Expensify/App/assets/36083550/842e8543-13b0-46d3-8bb2-2209439ef122)

### Solution

Investigate why the onyx data is not correctly loaded upon making the transition and fix it

cc @staszekscp @koko57 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c534f630f870f749</li>
        <li>Upwork Job ID: 1709570879512326144</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by koko57** [comment] 2023-09-18 09:48
@mountiny I'm ready to help with this one 🙂

**Comment by mountiny** [comment] 2023-09-18 09:49
@koko57 will handle this one for us 🎖️

**Comment by koko57** [comment] 2023-09-18 17:28
Daily update: I'm still looking for the root cause, but I've noticed one strange thing - when the transition fails (I was logged in as a user A and wanted to log in as a user B) and I see the green empty screen the reports that are in the Onyx (like in the first screenshot) are the reports that should be displayed for the user A. 
![Screenshot 2023-09-18 at 19 23 44](https://github.com/Expensify/App/assets/28020445/fa670943-cae4-4aa8-947e-e1d451dcff1c)
The rest of the data like login, contact methods, email, etc are already populated with user B's data. Then after the refresh the reports stay in Onyx unchanged among the reports that should be displayed for the user B
![Screenshot 2023-09-18 at 19 23 51](https://github.com/Expensify/App/assets/28020445/25b07df2-eefc-4ea1-9fc0-ce3165bf3199)

I logged out of both accounts and logged in separately again. For user A I had 185 keys in Onyx and for user B I had 340.
When logged in as user A and trying to transition from the OldDot as a user B, after the failure and then refresh I had 489 keys in Onyx.

**Comment by koko57** [comment] 2023-09-19 16:53
Daily update: Although we're navigating to the report screen, report screen doesn't mount.
On OpenApp and OpeReport requests -  I tried to force both requests, but it didn't help. I'll continue looking into this issue tomorrow.

**Comment by mountiny** [comment] 2023-09-21 03:10
Thanks for the updates

**Comment by koko57** [comment] 2023-09-21 18:29
Daily update: (Sorry for not posting yesterday) unfortunately, not much progress here. I'm digging into the logOut - logIn as a new user flow. I've noticed that in this flow we're firing signOut twice: [here](https://github.com/Expensify/App/blob/b225b53829f8fa4ef5f7a75616469d1fc7d347b9/src/libs/actions/App.js#L376) and [here](https://github.com/Expensify/App/blob/d7205e540af4e666b02b0d4707594c52b5050ee6/src/libs/actions/Session/index.js#L81C14-L81C14). I wonder whether this flow could be simplified somehow? The ReportScreen is not mounting as well as SidebarLinksData - which is weird bc CentralPaneNavigator and BaseSidebarScreen both are.

**Comment by koko57** [comment] 2023-09-22 16:05
Daily update: today I asked Edu for some help, we both think it's possibly a navigation issue. I'll continue investigating it on Monday.

**Comment by mountiny** [comment] 2023-09-25 07:04
Investigation continues

**Comment by koko57** [comment] 2023-09-25 19:46
Not much progress here. I only discovered that removing [this](https://github.com/Expensify/App/blob/f5409e72f3517022421a98c7b0a9d8f7f075f06c/src/pages/LogOutPreviousUserPage.js#L33) from LogOutPreviousUserPage works but there's a glitch of the old user's chats at the beginning and there is some error in the session object after authenticating. As [I've mentioned before](https://github.com/Expensify/App/issues/27418#issuecomment-1730095533) we log out the user twice in the current flow. Maybe just simplifying it would fix the issue.

**Comment by koko57** [comment] 2023-09-27 14:28
I guess I've finally found the root cause - it's a problem with Onyx. I'm starting working on my proposal.

**Comment by mountiny** [comment] 2023-09-28 06:28
Great! Thanks!

**Comment by koko57** [comment] 2023-09-28 12:01
Working on a proposal, I have one solution on my mind, need to test it thoroughly. 🙂 If everything looks fine, maybe I'd be able to post the proposal tomorrow.

**Comment by koko57** [comment] 2023-09-29 11:00
Unfortunately, my solution doesn't work properly, I need to find another one 😞

**Comment by koko57** [comment] 2023-10-02 16:23
Came up with another solution, testing it now, but the first results look promising.

**Comment by koko57** [comment] 2023-10-03 16:25
Proposal is almost ready, probably will post it tomorrow.

**Comment by dylanexpensify** [comment] 2023-10-03 17:47
Yes, ty @koko57!

**Comment by koko57** [comment] 2023-10-04 10:18
Sorry, it took me so long 🙈 

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After transitioning from the OldDot to the NewDot the screen is empty (the sidebar and the main screen is displayed but with no content). The data is properly displayed only after refreshing the page. IMPORTANT NOTE: it happens only when user is logged in with another account than the one they want to transition from.

### What is the root cause of that problem?

The main cause that the sidebar data and the report screen data is not being loaded is because the withOnyx HOC is missing some essential keys for both the Report Screen and the Sidebar components to render them - the loading state stays true so the HOC returns null instead of the wrapped component. 
When the user is logged in on another account he is first being logged out (while still being on AuthScreens) then redirected to the LogInWithShortLivedAuthTokenPage to be then redirected back to the AuthScreens. This flow, in general, is not causing the problem but has a few flaws that actually do that. 

- When we’re on the AuthScreens the app tries to reconnect https://github.com/Expensify/App/blob/029d009731dcd3c44cd1321672b9672ef0d3d7d9/src/libs/Navigation/AppNavigator/AuthScreens.js#L166

- We are sending logOut request twice: once in the setUpPoliciesAndNavigate https://github.com/Expensify/App/blob/029d009731dcd3c44cd1321672b9672ef0d3d7d9/src/libs/actions/App.js#L375-L377 - when we hit the AuthScreens, then on LogOutPreviousUserPage https://github.com/Expensify/App/blob/029d009731dcd3c44cd1321672b9672ef0d3d7d9/src/pages/LogOutPreviousUserPage.js#L33 and this second time we actually start clearing the Onyx (and clearing takes some time, it’s an async action)
- after the SignInWithShortLivedAuthToken request AuthScreens are mounted again
- We’re redirected to report route, Sidebar and Report Screen should be mounted we don’t have enough data in Onyx, so the components are not mounted
 

### What changes do you think we should make in order to solve the problem?

I think that we should send the logOut request and startClearing the Onyx as soon as the AuthScreen mount. This way Onyx is cleared and populated with the necessary data faster - and the Sidebar and Report Screen components are mounting. 
To achieve that I would:
- move this lines https://github.com/Expensify/App/blob/029d009731dcd3c44cd1321672b9672ef0d3d7d9/src/libs/actions/App.js#L374-L377 to AuthScreens componentDidMount before this line https://github.com/Expensify/App/blob/d2c573fae7e3cba0173254ec78836ac65944ce2e/src/libs/Navigation/AppNavigator/AuthScreens.js#L162 (or even at the top)
- change signOut method to signOutAndRedirectToSignIn (because this one starts clearing the Onyx)
- Add a return after to prevent from firing all the methods below, because we don’t need them
- remove https://github.com/Expensify/App/blob/029d009731dcd3c44cd1321672b9672ef0d3d7d9/src/pages/LogOutPreviousUserPage.js#L32-L34 because we won’t need it anymore.
These changes in the code made transitioning from another account possible and I didn’t found any regression they would may cause.

### What alternative solutions did you explore? (Optional)
Could we possibly render the component if we don’t have the required keys? We usually pass default props for them.

**Comment by mountiny** [comment] 2023-10-04 14:07
Looks good to me, @allroundexperts what do you think of this proposal?

**Comment by mountiny** [comment] 2023-10-05 17:33
Thank you!

@koko57 can yuou please create a PR? I think we also wanted to speed up the transition when you are not logged in to other account, do you think that will get improved?

**Comment by koko57** [comment] 2023-10-06 07:03
@mountiny these changes are only affecting the flow with the user previously logged in on another account. So it won't have any impact on the previously not logged in user transition.

On the PR - I started working on it today, merged with the newest main, but I've noticed that something has changed and my solution is no longer working 🙁 I'll be investigating it today

**Comment by dylanexpensify** [comment] 2023-10-10 11:12
@koko57 mind giving us an update?

**Comment by koko57** [comment] 2023-10-10 11:21
PR is still under review

**Comment by koko57** [comment] 2023-10-18 12:11
@mountiny I saw this https://github.com/Expensify/App/issues/29849 and I'm on it. I know what's happening there but I need to find out why (bc it tested well, I wonder if there was some other changes that together with mine might have caused the issue)

**Comment by dylanexpensify** [comment] 2023-10-24 22:53
payment tomorrow!

**Comment by dylanexpensify** [comment] 2023-10-30 09:21
Payment Summary:

- Contributor+: @allroundexperts $500

Please apply!

**Comment by dylanexpensify** [comment] 2023-10-30 09:21
@allroundexperts mind completing checklist? 🙇‍♂️

**Comment by mountiny** [comment] 2023-10-30 11:55
Agreed, @allroundexperts did you request on newdot? Can we close this issue?

**Closed** 2023-10-30 12:30 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 21:55
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/27418#issuecomment-1784788004).
