### ISSUE TITLE
[$500]  Request Money -  Offline Receipt & Distance request to worspace don't show requestor name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28554] opened 2023-09-30 23:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Go to a chat with any workspace with which you don't have any IOU actions yes
3. Click "+" -> Request Money
4. Place a Receipt (or Distance) request
5. See the chat with newly created IOU report preview

## Expected Result:
The header of the report should show "{Workspace} & {user}"

## Actual Result:
The header shows only "{Workspace} &"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b5730d57-67d4-4d43-b801-aebb41f68a9a

https://github.com/Expensify/App/assets/78819774/3fd5e4b8-81f8-4ae6-960c-e2d1b48fa5b9

https://github.com/Expensify/App/assets/78819774/013a0283-5825-4fcd-913d-35af78fd69ed

https://github.com/Expensify/App/assets/78819774/0ee55291-6a35-42c0-be0e-820a378060d4

https://github.com/Expensify/App/assets/78819774/c3f6e930-1873-43a0-9a73-afe5b33edd66

https://github.com/Expensify/App/assets/78819774/0960a032-dac7-43ef-abe8-aac661ea4be5

https://github.com/Expensify/App/assets/78819774/15138a12-5f58-43a2-9f2c-7ac2f4a91784

**Expensify/Expensify Issue URL:**

**Issue reported by:** @paultsimura

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696025357358249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125018631320cc910</li>
        <li>Upwork Job ID: 1708258808024285184</li>
        <li>Last Price Increase: 2023-10-07</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-01 05:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When offline, the Receipt money request in a workspace doesn't show user name in the header.

### What is the root cause of that problem?

The root cause lies here:

https://github.com/Expensify/App/blob/5fd69da1cf05fef1a39fb64937ef15b0e8f163e2/src/pages/home/report/ReportActionItemSingle.js#L118

We are trying to show user details by iouReport.managerID, but the optimistic Expense reports don't have the managerID set (as it will be populated with the policy's owner ID later):

https://github.com/Expensify/App/blob/289411fbdf1c01dba68d13045814e81ea540f3c2/src/libs/ReportUtils.js#L2116-L2131

### What changes do you think we should make in order to solve the problem?

This change was introduced recently in order to avoid name duplication (explained in the comment). But if the report is an expense report, the first actor's name is always a workspace name:

https://github.com/Expensify/App/blob/5fd69da1cf05fef1a39fb64937ef15b0e8f163e2/src/pages/home/report/ReportActionItemSingle.js#L99-L102

So we can (and should) exclude the expense report from this managerID check and use iouReport.ownerAccountID :

```
const secondaryAccountId = !isWorkspaceActor && props.iouReport.ownerAccountID === actorAccountID ? props.iouReport.managerID : props.iouReport.ownerAccountID
```


Moreover, in case of policy expense reports, we shouldn't use the iouReport.managerID because it always will be the policy owner. So we can run into a situation when User A requested money from User B's workspace. And this header will show: "UserB's Workspace & User B" instead of "UserB's Workspace & User A"

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-10-01 05:32
@lanitochka17 don't I have the right of posting the first proposal in the thread of a bug if I reported it originally?

It was posted here: https://expensify.slack.com/archives/C049HHMV9SM/p1696027752529129?thread_ts=1696025357.358249&channel=C049HHMV9SM&message_ts=1696027752.529129

**Comment by pradeepmdk** [comment] 2023-10-01 09:05
@paultsimura I think @lanitochka17 forgot to post your proposal from Slack. if you have a proposal in Slack first you would be considered here.

**Comment by paultsimura** [comment] 2023-10-01 09:07
@pradeepmdk thanks, I just wanted to clarify this. No offense😌

**Comment by puneetlath** [comment] 2023-10-04 13:14
@situchan thoughts on the proposals/discussion?

**Comment by neil-marcellini** [comment] 2023-10-05 21:47
Never mind, this isn't specific to distance requests. It's also no longer reproducible on staging. I verified it with distance requests too. We can close this.

https://github.com/Expensify/App/assets/26260477/c3bddf23-e2e2-4405-aef9-685bab074495

**Comment by situchan** [comment] 2023-10-05 22:16
I am also not able to reproduce. We can close this

**Comment by paultsimura** [comment] 2023-10-05 23:33
This was indeed fixed by https://github.com/Expensify/App/pull/28350.

**Comment by puneetlath** [comment] 2023-10-09 15:29
Closing this out since the bug no longer exists.

**Closed by puneetlath** 2023-10-09 15:29 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
