### ISSUE TITLE
[$1000] [HOLD for payment]  'announce' room disapears from LHN when changing notification setting to 'Mute'

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23100] opened 2023-07-18 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Navigate to 'announce' room
3. Click on announce room header
4. Click on 'Settings'
5. Click on 'Daily'
6. Select 'Mute'
7. Select another report from LHN
## Expected Result: 
announce room shouldn't disappear from LHN
## Actual Result: 
announce room disappears from LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 2023-07-18 18-40-59.webm](https://github.com/Expensify/App/assets/43996225/520bde86-33b2-4529-97ad-8ff8b251ff19)

https://github.com/Expensify/App/assets/43996225/f9c43261-5cc9-448a-9094-48e7be56a11a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689695228630369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012515a6a4f4f10c96</li>
        <li>Upwork Job ID: 1683427723140796416</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-07-18 18:56
We're discussing [here](https://expensify.slack.com/archives/C03TQ48KC/p1689623753049399) on what the expected behavior is

**Comment by jasperhuangg** [comment] 2023-07-18 20:29
We cleared up that this is actually the expected behavior, not a bug, closing

https://expensify.slack.com/archives/C03TQ48KC/p1689709321825069?thread_ts=1689623753.049399&cid=C03TQ48KC

**Comment by Natnael-Guchima** [comment] 2023-07-18 21:21
@jasperhuangg it seems like there is another regression related this to issue. archived announce room is removed from LHN for participants too if admin set notification setting to mute before deleting the workspace. [achrived announce room disappears if admin has set notification setting to 'Mute' before deleting workspace](https://expensify.slack.com/archives/C049HHMV9SM/p1689714853867959). I am guessing that we don't want to delete announce room reports when deleting workspace.

**Comment by Natnael-Guchima** [comment] 2023-07-19 19:17
Hello @jasperhuangg, it seems like the PR that has caused this regression is reverted here ([Revert "Hide muted chats from LHN"](https://github.com/Expensify/App/pull/23037)), and the test steps seem to be similar to that I have reported here. This is to check if I am eligible for reporting bonus. 
Thanks.

**Comment by jasperhuangg** [comment] 2023-07-21 18:09
@laurenreidexpensify I forgot, but let's get @Natnael-Guchima paid out for the reporting bonus

**Comment by srikarparsi** [comment] 2023-07-24 02:59
Hey, just want to clarify that we're re-reverting this PR because of miscommunication so hiding announce rooms from the LHN when they are muted is expected behavior. I am good with paying @Natnael-Guchima the reporting bonus as well though since we also thought the same thing but it turns out that [this is not a bug.](https://expensify.slack.com/archives/C03TQ48KC/p1689709321825069?thread_ts=1689623753.049399&cid=C03TQ48KC)

**Comment by laurenreidexpensify** [comment] 2023-07-24 10:44
Just added external to get Upwork job up, pls ignore @mollfpr

**Comment by laurenreidexpensify** [comment] 2023-07-24 10:46
@Natnael-Guchima offer sent in Upwork

**Comment by Natnael-Guchima** [comment] 2023-07-24 10:51
Accepted the offer. Thanks @laurenreidexpensify

**Comment by laurenreidexpensify** [comment] 2023-07-24 10:58
Perfect - paid! closing

**Closed by laurenreidexpensify** 2023-07-24 10:58 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
