### ISSUE TITLE
All workspace members are showing with green avatar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11020] opened 2022-09-15 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and login
2. Go to settings
3. Go to workspace
4. Go to Manage members
5. Click on invite

## Expected Result:
Their own avatar should be shown

## Actual Result:
Only green avatar is shown

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.0-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Screenshot_20220915-151526_Chrome](https://user-images.githubusercontent.com/43996225/190502307-9c2ddb6f-e330-4d1d-8095-790c38d76f32.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-09-15 20:28
dupe of https://github.com/Expensify/App/issues/11019

**Comment by mvtglobally** [comment] 2022-09-15 20:29
@thesahindia  :) We rushed for it :)

**Closed by thesahindia** 2022-09-15 20:28 UTC
Labels: DeployBlockerCash, Engineering, Hourly
