### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Closing the receipt image user lands in transaction thread instead of expense report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50160] opened 2024-10-03 15:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727915131329509

## Action Performed:

1. Submit receipt expense
2. Make sure you had no other expenses on processing reports before
3. Wait for it to scan
4. On web, navigate to the workspace chat
5. Navigate to the expense report
6. Click on the receipt detail
7. Close the attachment modal
8. Note that you are not on the transaction thread report and not in the expense report

## Expected Result:
You should remain on the one-expense report view of the expense report
## Actual Result:
After going to the receipt detail, user is on the transaction thread which is confusing because the comments from the expense report are not visible
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/efeb338e-b249-4dc1-a49d-9a1d865a0305

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841980614903369906</li>
        <li>Upwork Job ID: 1841980614903369906</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 104256847</li>
<li>nkdengineer | Contributor | 104263005</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by nkdengineer** [comment] 2024-10-03 15:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After closing the receipt page, user redirects the user to the transaction thread report.


### What is the root cause of that problem?
When we open the receipt page, the report is the transaction thread report then use `dismissModal` with `reportID` param is the transaction thread report so we go back to the transaction thread report if we close this page.

https://github.com/Expensify/App/blob/efa3274237e9da1d4fdcea10db8f04458a3105e8/src/pages/TransactionReceiptPage.tsx#L54
### What changes do you think we should make in order to solve the problem?
We can simply use `dismissModal` without `reportID` or use `goBack` in this case

```
const onModalClose = () => {
    Navigation.dismissModal();
};
```
https://github.com/Expensify/App/blob/efa3274237e9da1d4fdcea10db8f04458a3105e8/src/pages/TransactionReceiptPage.tsx#L54

or we can check if the transaction thread is one transaction thread then we will pass `reportID` as `report.parentReportID`


```
Navigation.dismissModal(
    ReportUtils.isOneTransactionThread(report?.reportID ?? '-1', report?.parentReportID ?? '-1', parentReportAction) ? report?.parentReportID : report?.reportID,
);
```

https://github.com/Expensify/App/blob/efa3274237e9da1d4fdcea10db8f04458a3105e8/src/pages/TransactionReceiptPage.tsx#L54
### What alternative solutions did you explore? (Optional)

Or we can pass `backTo` param when we open the `TransactionReceiptPage` and then we will go back to the `backTo` param if it exists otherwise dismiss the modal

https://github.com/Expensify/App/blob/efa3274237e9da1d4fdcea10db8f04458a3105e8/src/pages/TransactionReceiptPage.tsx#L54

**Comment by mountiny** [comment] 2024-10-03 23:26
@situchan can you please review the above proposal? thanks!

**Comment by situchan** [comment] 2024-10-04 03:34
Proposed solutions work but I prefer using report.parentReportID if the transaction thread is one transaction thread.
Let's also make sure that the solution doesn't cause regression - https://github.com/Expensify/App/issues/49887
🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-10-04 07:48
@situchan Sure, my proposal will not change the logic in the case search page, only fix the case we open from report screen.

**Comment by bfitzexpensify** [comment] 2024-10-17 18:37
Payment complete to @nkdengineer 

@situchan, please complete the BZ checklist and I'll get your payment sorted!

**Comment by situchan** [comment] 2024-10-17 18:40
The bug existed for long time, not regression. Just we didn't consider this case while implementing one-expense transaction report.

### Regression Test Proposal
1. Submit receipt expense
2. Make sure you had no other expenses on processing reports before
3. Wait for it to scan
4. Navigate to the workspace chat
5. Navigate to the expense report
6. Click on the receipt detail
7. Close the attachment modal
8. Verify that: You should remain on the one-expense report view of the expense report

**Comment by bfitzexpensify** [comment] 2024-10-17 18:47
Thank you! Payments complete, let's close this out.

**Closed by bfitzexpensify** 2024-10-17 18:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
