### ISSUE TITLE
[HOLD push-to-page pattern] Web - Room Name - "Enter" key is not working for saving the new room name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10417] opened 2022-08-17 01:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Sign in with any expensify account
3. Create a workspace from the green plus (if needed)
4. Create a workspace room from the green plus (if needed)
5. Click the header of the workspace room to open the room details page
6. Click "Settings"
7. Rename the room and press "Enter" key on the keyboard

## Expected Result:
The Room Name must be saved

## Actual Result:
Nothing happens when you press the "Enter" key

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+ihchat4@applause.expensifail.com/Yulia1986Gerets

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/185013518-a1ff8ea3-8ca1-4711-b96f-c1e015c100c7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2022-08-18 23:36
Hi @trjExpensify @JmillsExpensify, just gut-checking here, I noticed the pattern for the save button on the Room Settings page is different than the Workspace General Settings page, shouldn't we use the same pattern for both pages?

<img width="947" alt="Screen Shot 2022-08-18 at 18 32 50" src="https://user-images.githubusercontent.com/6829422/185512757-21a78995-e37a-4fe7-9ec3-51c96117e322.png">

**Comment by trjExpensify** [comment] 2022-08-19 00:20
Yeah agreed, it should. I'm not entirely sure why the `Save` button was put there for user-created rooms, but with the push to page design it will be moved to the subsequent page.

**Comment by marcochavezf** [comment] 2022-08-19 17:58
> but with the push to page design it will be moved to the subsequent page.

Ah where can I find this design? Is that something that will be done in a design doc? Should we put this issue on hold?

**Comment by marcochavezf** [comment] 2022-08-22 09:33
I found out we're going [implement](https://expensify.slack.com/archives/C02HWMSMZEC/p1660603697810099?thread_ts=1656005936.435959&cid=C02HWMSMZEC) part of the "push-to-page" design in the Account Settings doc, so I'm going to put this issue on hold since it's better to come back this issue after the Account Settings is implemented.

**Comment by kevinksullivan** [comment] 2022-08-22 21:39
>are you "collecting" refactors for that somewhere?

@trjExpensify haven't collected the refactors yet, but I think that'll make sense as part of the rollout plan for the design doc, right?

**Comment by trjExpensify** [comment] 2022-08-23 10:32
Yep, makes sense. Just wondered if you were compiling in a holding issue somewhere or something.

**Comment by trjExpensify** [comment] 2022-08-23 10:36
>so I'm going to put this issue on hold since it's better to come back this issue after the Account Settings is implemented.

Yeah @marcochavezf, I agree with putting this on hold until account settings is implemented at least as a reference point.

**Comment by JmillsExpensify** [comment] 2022-08-23 10:59
Totally agree.

**Comment by johncschuster** [comment] 2022-10-18 20:17
This is still reproducible. I attempted to rename a Workspace room and click `Enter`, but the name didn't update. It only updated when I clicked the `Save` button.

@marcochavezf, do you feel this issue should still be on hold?

**Comment by marcochavezf** [comment] 2022-10-18 23:21
Hmm I put it on hold because we had the `Save` button beside the Room name input field, but seems it's no longer the case:

<img width="381" alt="Screen Shot 2022-10-18 at 18 15 40" src="https://user-images.githubusercontent.com/6829422/196562388-12538f4d-632a-4501-8ca2-8b85e25c7cd7.png">

@trjExpensify @JmillsExpensify could you confirm this button was removed in the Room chats?

If so I think it's fine to just fix the "Enter" key event for changing the Workspace name.

**Comment by johncschuster** [comment] 2022-10-19 00:02
The button hasn't been removed. I think you're just looking at a settings page that you do not have permission to change. When I tested earlier, the button to change the name of the room was still present.

**Comment by Puneet-here** [comment] 2022-10-19 05:18
@marcochavezf, names for default rooms (#admin, #annouce) can't be changed so the page doesn't have the save button. You will have to create a room through by selecting new room option at fab menu and you will see the save button when you go to the settings for that room.

**Comment by marcochavezf** [comment] 2022-10-21 01:22
Oh I see, thanks guys! Yeah, in that case, I think we should still put it on hold because the idea is to change the button on this page to the ["push-to-page" pattern](https://github.com/Expensify/App/issues/10417#issuecomment-1222100843):

<img width="1104" alt="Screen Shot 2022-10-20 at 20 19 54" src="https://user-images.githubusercontent.com/6829422/197089035-4bb58a5a-76e6-4395-83ef-565ec09f9917.png">

**Comment by johncschuster** [comment] 2022-10-21 20:57
Thanks for clarifying that. I'm going to downgrade the priority of this to `Weekly`, but will keep it open and bumping so it doesn't erode.

**Comment by johncschuster** [comment] 2022-10-25 20:51
Sorry Melv, I meant to downgrade this to `Weekly` on the last comment. Doin' it now.

**Comment by marcochavezf** [comment] 2022-10-27 01:43
Hey @johncschuster we can downgrade to `Monthly` because we're going to resume the Account Settings project once we wrap up the WA Quality project.

**Comment by marcochavezf** [comment] 2023-01-11 20:22
I'm going to re-open this one to still keep track of it

**Comment by johncschuster** [comment] 2023-02-17 16:56
@marcochavezf is there anything I can do to move this forward, or do you just want to keep this open to keep track of it?

**Comment by marcochavezf** [comment] 2023-02-17 19:11
Hi @johncschuster, I noticed the UI for the room settings was already updated:

<img width="980" alt="Screenshot 2023-02-17 at 13 06 29" src="https://user-images.githubusercontent.com/6829422/219764008-f748cba9-9850-4d47-9f32-0cbf262a0da9.png">

I think we can close this issue out since the original bug was already fixed.

**Comment by johncschuster** [comment] 2023-02-27 23:20
@marcochavezf Nice! I'll go ahead and close it. Thanks!

**Closed by johncschuster** 2023-02-27 23:20 UTC
Labels: Engineering, Monthly, Bug
