### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Web - Room - Stacked avatars on sign-in banner do not match and are misaligned in public room thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27523] opened 2023-09-15 12:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. As a user with custom photo, create a public room.
3. Send a message and send a reply in thread.
4. Copy the share code to the public room.
5. Paste the URL in incognito mode.
6. Click on the '1 Reply'.

## Expected Result:
On the sign-in banner, user avatar shows the custom avatar, and is aligned in place with the workspace avatar, which is the same way the stacked avatars in the header are aligned.

## Actual Result:
On the sign-in banner, user avatar is the default avatar instead of the custom avatar, and the avatar is not aligned in place with the workspace avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9d2ebf0f-12d9-4100-a6f6-59c8d35cc73e

<img width="1440" alt="Bug6201367_Screenshot_2023-09-15_at_17 44 57" src="https://github.com/Expensify/App/assets/115492554/7e0266c4-a737-4004-8bd8-a37c6044f093">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3957b30c63d0184</li>
        <li>Upwork Job ID: 1702742410241048576</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26877063</li>
<li>Pujan92 | Contributor | 26877065</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-09-15 15:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In anonymous footer banner subscript avatars aren't showing correctly

### What is the root cause of that problem?
For `SubscriptAvatar` we only apply either Small or Default size to the `containerStyle` but not consider the medium. Due to that, it has less `containerStyle(40px)` and the avatar inside it uses the passed size which is `medium(52px)` which leads to    the issue of placing the wrong subscript avatar.

https://github.com/Expensify/App/blob/2427a06ed24f0649e55c14dbf4ae1a2a9ebe2109/src/components/SubscriptAvatar.js#L42-L45

https://github.com/Expensify/App/blob/2427a06ed24f0649e55c14dbf4ae1a2a9ebe2109/src/components/SubscriptAvatar.js#L51

### What changes do you think we should make in order to solve the problem?

We can use the same function to get `containerStyles` which we used for `MultipleAvatars` by placing it in some util file. It gives/sets the correct `containerStyles` for passing the `medium` size.

https://github.com/Expensify/App/blob/2427a06ed24f0649e55c14dbf4ae1a2a9ebe2109/src/components/MultipleAvatars.js#L74-L92

<img width="1439" alt="Screenshot 2023-09-15 at 21 26 40" src="https://github.com/Expensify/App/assets/14358475/04bb044d-e5fc-40a5-907b-0f38fd1a168b">

**Comment by CortneyOfstad** [comment] 2023-09-18 13:55
@jjcoffee Thoughts on the proposal above? TIA!

**Comment by jjcoffee** [comment] 2023-09-19 16:08
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2023-09-20 12:45
@Pujan92 Thanks for the proposal! Maybe you missed this but there's a second issue here that if there's a custom avatar set we're displaying the default one instead. Could you address that in your proposal too?

**Comment by jjcoffee** [comment] 2023-09-22 16:04
Waiting on proposals that address both issues.

**Comment by jjcoffee** [comment] 2023-09-25 12:41
Thanks @Pujan92! Your updated [proposal](https://github.com/Expensify/App/issues/27523#issuecomment-1721510722) addresses both issues, so happy to go with it!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by srikarparsi** [comment] 2023-09-26 05:43
Cool, looks good to me as well, assigning you to the issue @Pujan92

**Comment by Pujan92** [comment] 2023-09-27 16:04
@jjcoffee [PR](https://github.com/Expensify/App/issues/28324) is ready for review!

**Comment by jjcoffee** [comment] 2023-09-28 16:40
@Pujan92 Thanks, will review tomorrow!

**Comment by CortneyOfstad** [comment] 2023-10-05 17:55
@jjcoffee any updates on this? Thanks!

**Comment by jjcoffee** [comment] 2023-10-06 08:37
@CortneyOfstad PR is approved by me, we're just waiting for some design feedback that @srikarparsi requested.

**Comment by CortneyOfstad** [comment] 2023-10-25 17:32
@jjcoffee @Pujan92 — both of you have been paid in Upwork, so you should be all set there!

@jjcoffee — when you have a chance, can you complete the checklist above? Thanks!

**Comment by jjcoffee** [comment] 2023-10-26 07:58
- The PR that introduced the bug has been identified. Link to the PR: **N/A - behaviour has always been there as far as I can tell.**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression test proposal**

1. As a user with custom avatar, create a public room.
2. Send a message and send a reply in thread.
3. Copy the share code to the public room.
4. Paste the URL in incognito mode.
5. Click on the '1 Reply'.
6. Verify that your custom avatar displays in the report footer and that the avatars are correctly aligned.

Do we agree 👍 or 👎

**Comment by CortneyOfstad** [comment] 2023-10-30 17:32
Regression test created [here](https://github.com/Expensify/Expensify/issues/331258) — so closing this out. Thanks all!

**Closed by CortneyOfstad** 2023-10-30 17:32 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
