### ISSUE TITLE
[$500] Workspace - Invite member - Member highlights on deselect all members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27377] opened 2023-09-13 16:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings> workspace
2. Create new workspace if not created
3. Go to members
4. Invite any 2 members
5. Click on select all check box
7. Deselect last selected member
8. Deselect second selected member

## Expected Result:
Member should not be highlights

## Actual Result:
Member highlights

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/75dc0bd5-e066-40c2-b3fc-5bdf71e0774b

https://github.com/Expensify/App/assets/93399543/c5ed47cf-13a6-4eb6-ae8d-ec7a49295e10

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694422514518809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0d617af5beeb293</li>
        <li>Upwork Job ID: 1702003634763894784</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26724768</li>
<li>akamefi202 | Contributor | 26724771</li>
<li>gadhiyamanan | Reporter | 26724774</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-09-13 18:15
@Christinadobrzyn I was duplicate assigned here, so un-assigning as this doesn't need two BZ members. We are fixing this [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1694596102747859?thread_ts=1694216537.643229&cid=C01SKUP7QR0)

**Comment by akamefi202** [comment] 2023-09-13 19:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Member highlights on deselect all members in workspace members page.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/7deca7a02a4f58bb1bb47b0689d478525558898f/src/components/SelectionList/BaseSelectionList.js#L173-L177

If the user deselects a member, `selectRow` function is called and the function focuses the next member in the list.

https://github.com/Expensify/App/blob/7deca7a02a4f58bb1bb47b0689d478525558898f/src/components/SelectionList/BaseSelectionList.js#L192-L200

This is implemented for selection keyboard shortcut to support continuous selection & deselection.
The code for this feature is written inside `selectRow` function and it will be called from `selectFocusedOption`.

But `selectRow` function is also called if the user select/deselect by click/press.
So the next member will be focused and we see current issue.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/4ff85db3bd2f6f30cd76a249eed82065d397f766/src/components/SelectionList/BaseSelectionList.js#L253-L259

I think we need to call `onSelectRow` function directly instead of calling `selectRow` function if the user select/deselect by click/press.
So the app will only toggle the item without moving focus to next item.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2023-09-14 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Member highlights on deselect all members in workspace members page.

### What is the root cause of that problem?
- Currently, we have a logic to auto-focus on the next available item when the users click/press on the item. The logic is like below:
https://github.com/Expensify/App/blob/4ff85db3bd2f6f30cd76a249eed82065d397f766/src/components/SelectionList/BaseSelectionList.js#L170-L190
https://github.com/Expensify/App/blob/4ff85db3bd2f6f30cd76a249eed82065d397f766/src/components/SelectionList/BaseSelectionList.js#L192-L200
https://github.com/Expensify/App/blob/4ff85db3bd2f6f30cd76a249eed82065d397f766/src/components/SelectionList/BaseSelectionList.js#L288-L293
- And this logic is called for both case: user select item and user deselect item, which lead to the bug: When user deselects the member, the next one is highlights

 
### What changes do you think we should make in order to solve the problem?
- In my opinion, I do not think it is a bug, just needs an improvement
- The logic "Auto focus on the next available item" is only useful when the user uses the ENTER key to select/deselect the items. So we can add the condition to appy this auto-focus logic: The device are desktop/desktop-web. Like below:
```
 const selectRow = (item, index) => {
        // In single-selection lists we don't care about updating the focused index, because the list is closed after selecting an item
        if (canSelectMultiple && !DeviceCapabilities.canUseTouchScreen()) {
                 // Auto-focus logic
         }

        onSelectRow(item);
    };

``` 
- Based on ```DeviceCapabilities.canUseTouchScreen()```, we maybe can check if the device is desktop or not
### What alternative solutions did you explore? (Optional)
- Also we can just apply the auto-focus next item in case user press the ENTER key to select the items like: 
```
 const selectRow = (item, index, isPressingEnter) => {
          if(isPressingEnterKey) { // Logic auto-focus here}
          onSelectRow(item)
}
```
- The isPressingEnter `s default value is false. So the clicking item does not auto-focus on next available item. In the callback function to handle ENTER press -  ```selectFocusedOption```, we will call selectRow with isPressingEnter is true

### Result
- First proposal: Mobile web

[Screencast from 14-09-2023 12:25:47.webm](https://github.com/Expensify/App/assets/141406735/7fd32001-a761-44c9-a6e3-7e23215f544a)

**Comment by s77rt** [comment] 2023-09-14 17:46
@akamefi202 Thanks for the proposal. Your RCA is correct and the solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/27377#issuecomment-1718163069)

**Comment by s77rt** [comment] 2023-09-14 17:46
@DylanDylann Thanks for the proposal. Your RCA is correct. The first solution i.e. the use of `DeviceCapabilities.canUseTouchScreen` does not seem correct for this case (the feature is related to keyboard not touchscreen) and the second solution is a pretty much the same as the one proposed by @akamefi202.

**Comment by DylanDylann** [comment] 2023-09-14 18:30
@s77rt I think based on DeviceCapabilities.canUseTouchScreen, we can know that whether the device is desktop or not. So only desktop device can use keyboard in this case, right?

**Comment by DylanDylann** [comment] 2023-09-14 18:36
@s77rt Also my 2nd proposal is different from @akamefi202. My proposal is to check if the user is pressing ENTER key, if true, apply the auto-focus logic. @akamefi202 `s proposal just uses onSelectRow function directly instead of calling selectRow function, so there is no auto-focus logic is applied

**Comment by Christinadobrzyn** [comment] 2023-09-14 20:19
Hey @techievivek can you take a peek at this https://github.com/Expensify/App/issues/27377#issuecomment-1719886245

**Comment by s77rt** [comment] 2023-09-14 20:41
@DylanDylann The `!DeviceCapabilities.canUseTouchScreen()` condition would be true on Web/Desktop, this won't change anything and the issue would be still reproducible on those platforms.

**Comment by DylanDylann** [comment] 2023-09-15 00:35
@s77rt why "this won't change anything and the issue would be still reproducible on those platforms."? In mobile, !DeviceCapabilities.canUseTouchScreen() will be false so the auto-focus logic is not applied based on my proposal. Please help give me more detail

**Comment by DylanDylann** [comment] 2023-09-15 02:02
Also, should we need to confirm whether the auto-focus on the item when deselecting item is intention or not @s77rt

**Comment by s77rt** [comment] 2023-09-15 13:20
@DylanDylann 

> why "this won't change anything and the issue would be still reproducible on those platforms."? In mobile, !DeviceCapabilities.canUseTouchScreen() will be false so the auto-focus logic is not applied

Right, but on Web/Desktop the issue would be still there. We need to fix the bug for all the platforms.


> should we need to confirm whether the auto-focus on the item when deselecting item is intention or not

It's intentional based on the code comments

**Comment by akamefi202** [comment] 2023-09-18 05:14
Thank you. The PR will be ready by tomorrow.

**Comment by akamefi202** [comment] 2023-09-26 09:02
@s77rt I closed the PR.

**Comment by Christinadobrzyn** [comment] 2023-09-26 15:58
Reached out to BZ about payment - https://expensify.slack.com/archives/C01SKUP7QR0/p1695743819720659

**Comment by Christinadobrzyn** [comment] 2023-09-26 16:39
Follow up from the team is to do a case-by-case evaluation of the work done on the GH and PR. 

@s77rt @akamefi202 @techievivek what do you think is fair payment for the work on this job/PR?

**Comment by s77rt** [comment] 2023-09-26 16:50
I think 50% would be fair for this case.

**Comment by Christinadobrzyn** [comment] 2023-09-29 22:30
Sounds good! Sorry, I'm a little lost here... The job was fixed elsewhere and we can close this, right?

How's this for payouts due:

Issue Reporter: $50 @gadhiyamanan 
Contributor: $250 @akamefi202 
Contributor+: $250 @s77rt 

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~01f0d617af5beeb293).

**Comment by akamefi202** [comment] 2023-10-03 05:11
@s77rt @Christinadobrzyn @techievivek 
Can we close this issue soon if everything is clear here?

**Comment by s77rt** [comment] 2023-10-03 14:56
@Christinadobrzyn Sorry I missed the question

> The job was fixed elsewhere and we can close this, right?

Yes. it was fixed here https://github.com/Expensify/App/pull/27246

**Comment by Christinadobrzyn** [comment] 2023-10-03 18:23
Thanks! Paid this out in Upwork based on https://github.com/Expensify/App/issues/27377#issuecomment-1741549948

Closing!

**Closed by Christinadobrzyn** 2023-10-03 18:23 UTC
Labels: Reviewing, External, Daily, Bug
