### ISSUE TITLE
[$1000] Members list doesn't reflect the correct participant number on the first visit to Members section

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21607] opened 2023-06-26 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start a new chat with a user who doesn't have a chat history with you
2. Verify 'Make sure you know this person before you respond.' concierge message is displayed
3. Hover over the message > click on 'Reply in thread' icon
4. Click on Chat header
5. Click on 'Members' button 
6. Repeat step 3 - 5 for the second time
## Expected Result: 
On the first visit to Members section, the members list should display two participants - the user & Concierge
## Actual Result: 
On the first visit to Members section, the members list displays only concierge

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/50300f2d-5186-492f-aaba-bee347580cee

https://github.com/Expensify/App/assets/43996225/e36e64f9-c8cf-4954-9245-4854108aa493

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687343832523429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d276920f2352da8</li>
        <li>Upwork Job ID: 1675937171085148160</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2023-07-03 18:39
Added the external label.

**Comment by alitoshmatov** [comment] 2023-07-04 14:18
When `openReport` request is made, backend is responding with a lot of data. It has a lot of items which contains newly created report data.
<img width="692" alt="Screenshot 2023-07-04 at 7 11 50 PM" src="https://github.com/Expensify/App/assets/59907218/2e2097c7-8815-40e1-b5f6-139039441697">

This is index 0 data and it is showing participants correctly
<img width="607" alt="Screenshot 2023-07-04 at 7 12 24 PM" src="https://github.com/Expensify/App/assets/59907218/12968882-f49b-4f38-8e3a-a5bc240698f4">

But as you can see at index 7 it is overriding participant data with just `concierge` 
<img width="680" alt="Screenshot 2023-07-04 at 7 12 42 PM" src="https://github.com/Expensify/App/assets/59907218/90a30619-45b9-4699-97ae-b7bd243a04b3">

**Comment by flaviadefaria** [comment] 2023-07-05 21:32
@0xmiroslav do you agree with @alitoshmatov?

**Comment by flaviadefaria** [comment] 2023-07-13 19:06
Friendly bump @0xmiroslav - If you think this is a backend issue then let's take it internally.

**Comment by flaviadefaria** [comment] 2023-07-17 09:43
Added the engineering label so that this can be taken internally.

**Comment by techievivek** [comment] 2023-07-18 08:23
Taking a look at it today.

**Comment by techievivek** [comment] 2023-07-21 06:48
This is a tricky case. It looks like we are doubling the response Onyx data but with updated values which don't match each other for this case. I can see a conversation around the same thing in Slack here https://expensify.slack.com/archives/C03TQ48KC/p1689905657861799

I am going to chime in to find a solution for this.

**Comment by techievivek** [comment] 2023-07-21 07:56
Started a convo on Slack to further discuss this with the team: https://expensify.slack.com/archives/C03TQ48KC/p1689924201903419

**Comment by techievivek** [comment] 2023-07-21 10:26
Looks like this is also a duplicate of https://github.com/Expensify/App/issues/21600. Should we just close this out? @flaviadefaria, I can help with the other one.

**Comment by techievivek** [comment] 2023-07-21 10:50
This is a bug with our backend code, as shown here https://github.com/Expensify/App/issues/21607#issuecomment-1620331695. If you observe, we have two `report_<reportID>` keys in the onyx response; the first report key seems to have the correct data, but the second one has incorrect data, which is what we eventually see in the UI. I have started a discussion to fix the Onyx response for `openReport`.

**Comment by techievivek** [comment] 2023-07-24 13:47
@flaviadefaria This is a duplicate of https://github.com/Expensify/App/issues/21600#issuecomment-1645363107, so we can close this out, and I will post an update on that issue.

**Comment by flaviadefaria** [comment] 2023-07-24 13:48
Sounds good, thanks!

**Closed by flaviadefaria** 2023-07-24 13:48 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Bug
