### ISSUE TITLE
[$500] Task - Deleted task gets highlighted and chat turns bold after deletion

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35100] opened 2024-01-24 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4235875
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Navigate to any chat and assign a task
3. Open the created task
4. Add a comment in the task conversation
5. Delete task
6. Navigate back to the chat and then to LHN

## Expected Result:
The "Deleted task" message in not highlighted and there is no change in chat

## Actual Result:
The "Deleted task" message is highlighted and the chat gets bold in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09045b8b-e598-4b59-8d55-50bbfa40387f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179cecbe3829d643a</li>
        <li>Upwork Job ID: 1750259088120512512</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-24 21:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When deleting a task, the parent chat report becomes unread.

### What is the root cause of that problem?
When canceling a task, we optimistically update the parent report's `lastVisibleActionCreated`, which marks the report as unread:

https://github.com/Expensify/App/blob/4db7b095495476cb45a6c9216027b66d7cfcb338/src/libs/actions/Task.ts#L791-L799

### What changes do you think we should make in order to solve the problem?
Comparing the optimistic data to the API response (which should be identical), the API response does not update the `lastVisibleActionCreated` of the parent report. I assume we shouldn't update it optimistically either.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-24 21:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When deleting a task, the parent chat report becomes unread.

### What is the root cause of that problem?
When canceling a task, we optimistically update the parent report's `lastVisibleActionCreated`, which marks the report as unread:

https://github.com/Expensify/App/blob/4db7b095495476cb45a6c9216027b66d7cfcb338/src/libs/actions/Task.ts#L791-L799

### What changes do you think we should make in order to solve the problem?
Comparing the optimistic data to the API response (which should be mostly identical), the API response does not update the `lastVisibleActionCreated` of the parent report.
And logically, this `CancelTask` operation only _modified_ the parent report action, it does not _create_ a new action in the parent report.
Therefore, we shouldn't update the `parentReport.lastVisibleActionCreated` optimistically. We only should update the `lastMessageText`:

```diff
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${parentReport?.reportID}`,
            value: {
                lastMessageText: ReportActionsUtils.getLastVisibleMessage(parentReport?.reportID ?? '', optimisticReportActions as OnyxTypes.ReportActions).lastMessageText ?? '',
-                lastVisibleActionCreated:
-                    ReportActionsUtils.getLastVisibleAction(parentReport?.reportID ?? '', optimisticReportActions as OnyxTypes.ReportActions)?.childLastVisibleActionCreated ?? 'created',
            },
        },
```

#### Result

https://github.com/Expensify/App/assets/12595293/c11537d1-4a8c-4513-84fa-3d81d0652917


### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment] 2024-01-24 21:39
@paultsimura [proposal](https://github.com/Expensify/App/issues/35100#issuecomment-1908947759) has the correct RCA and seems to work fine. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2024-01-25 19:23
Hi @tienifr!

Thank you pointing this out. I've reviewed your proposal and I think you're right, we should just revert back to the previous change instead. @marcochavezf Let's go with @tienifr's [proposal](https://github.com/Expensify/App/issues/35100#issuecomment-1909335659).

🎀 👀 🎀 C+ reviewed

**Comment by paultsimura** [comment] 2024-01-25 20:12
Good catch @tienifr💪🏽

**Comment by kubabutkiewicz** [comment] 2024-01-26 14:32
Hello guys, 
My PR introduced that bug  and I checked now that @tienifr solution is resolving only one issue which is **chat gets bold in LHN**. We also need to remove that line https://github.com/Expensify/App/blob/675b2c3088d01344a1b56e01e4e399d5fe96ac33/src/libs/actions/Task.ts#L770 since its causing this https://github.com/Expensify/App/blob/675b2c3088d01344a1b56e01e4e399d5fe96ac33/src/pages/home/report/ReportActionItem.js#L153 to `true` and this will cause that `Deleted task gets highlighted` because of those lines https://github.com/Expensify/App/blob/675b2c3088d01344a1b56e01e4e399d5fe96ac33/src/pages/home/report/ReportActionItem.js#L155-L158. Should I create a PR @allroundexperts since its my PR did this regression?

**Comment by allroundexperts** [comment] 2024-01-26 14:50
If its in the regression period, then I think you should create one.

**Comment by kubabutkiewicz** [comment] 2024-01-26 14:58
it is , so I am going to created one shortly. Thanks!

**Comment by allroundexperts** [comment] 2024-01-26 17:49
Update: Asked @akinwale to review the PR since it was within the regression period and he was the C+.

**Comment by dylanexpensify** [comment] 2024-01-29 11:56
TY @allroundexperts! @akinwale can you post an update please? 🙇‍♂️

**Comment by akinwale** [comment] 2024-01-29 13:03
> TY @allroundexperts! @akinwale can you post an update please? 🙇‍♂️

I'll review today.

**Comment by dylanexpensify** [comment] 2024-02-07 10:31
TY! @akinwale update please?

**Comment by akinwale** [comment] 2024-02-07 10:51
@dylanexpensify Review completed and the PR was merged. https://github.com/Expensify/App/pull/35252#event-11664416005

**Comment by dylanexpensify** [comment] 2024-02-13 20:22
Woooot!

**Comment by dylanexpensify** [comment] 2024-02-21 10:43
sure can!

**Comment by dylanexpensify** [comment] 2024-02-28 08:57
Agree, paying today!

**Comment by dylanexpensify** [comment] 2024-02-28 10:39
@tienifr paid out!

**Closed by dylanexpensify** 2024-02-28 10:39 UTC
Labels: Reviewing, External, Weekly, Bug
