### ISSUE TITLE
[$500] Web -  Unlimited API requests when image endpoint is giving 404

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26904] opened 2023-09-06 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report and attach an image.
2. Go to Chrome Dev Tools Network tab and disable cache & offline.
3. Open another report and reopen the report in which I attached the image.
4. Check if unlimited API requests are displayed in the console tab and image preview on the report enter an infinite re-render loop.

## Expected Result:
The image component should not enter an infinite re-render loop.

## Actual Result:
The image component should enter an infinite re-render loop.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b28edbd9-b137-4086-8533-23bf8e77879e

https://github.com/Expensify/App/assets/93399543/2e08a0ff-fbe4-4157-bbac-e404c8303633

**Expensify/Expensify Issue URL:**
**Issue reported by:** @napster125
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694029320303739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7adabaca13f7f62</li>
        <li>Upwork Job ID: 1699856040881467392</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

**Comment by napster125** [comment] 2023-09-06 20:15
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unlimited API requests when image endpoint is giving 404.
### What is the root cause of that problem?
We are encountering a lot of console errors due to incorrect usage of React.memo on the Image component.
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/components/Image/imagePropTypes.js#L10-L17
As you can see in this code snippet, source prop has two type so we need to consider this.
### What changes do you think we should make in order to solve the problem?
We need to change some code in Image component.
https://github.com/Expensify/App/blob/e460459ce0393edfcbda8ddbc5197a84b38bbac8/src/components/Image/index.js#L55
```
return prevProps.source === nextProps.source || prevProps.source.uri === nextProps.source.uri;
```
Additionally, we can add the "it's not here" page for this case.
### What alternative solutions did you explore? (Optional)
n/a

**Comment by Pluto0104** [comment] 2023-09-06 21:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unlimited API requests when image endpoint is giving 404.
### What is the root cause of that problem?
We are encountering a lot of console errors due to incorrect usage of `React.memo` on the Image component.
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/components/Image/imagePropTypes.js#L10-L17
As you can see in this code snippet, source prop has two type so we need to consider this.
### What changes do you think we should make in order to solve the problem?
We need to change some code in Image component.
https://github.com/Expensify/App/blob/e460459ce0393edfcbda8ddbc5197a84b38bbac8/src/components/Image/index.js#L55
```
return prevProps.source === nextProps.source || prevProps.source.uri === nextProps.source.uri;
```
Alternatively, we can add the "it's not here" page for this case.
### What alternative solutions did you explore? (Optional)
n/a

**Comment by kaushiktd** [comment] 2023-09-08 13:25
### Please re-state the problem that we are trying to solve in this issue.
Unlimited API requests when image endpoint is giving 404

### What is the root cause of that problem?
 the issue, is that there might have been a situation where onLoadStart was being triggered multiple times, leading to the re-render loop.

### What changes do you think we should make in order to solve the problem?
 Setting `isLoading` to false in this case prevents the component from entering the re-render loop.
the file link is below
https://github.com/Expensify/App/blob/main/src/components/ImageWithSizeCalculation.js#L74-L91

```
const {isOffline} = useNetwork();

   onLoadStart={() => {
                    if (isLoadedRef.current || isOffline) {
                        setIsLoading(false);
                    } else {
                        setIsLoading(true);
                    }
                }}
```
add this in line number 80. Setting `isLoading` to false in this case prevents the component from entering the re-render loop.


Video: https://drive.google.com/file/d/1Oia-tg6VXTaktknQ3vEV687jK189iJE9/view?usp=sharing

**Comment by slafortune** [comment] 2023-09-08 17:36
Not sure why you got assigned as well @greg-schroeder, since I'm going on sabbatical I'll just remove myself.

**Comment by jNembhard** [comment] 2023-09-09 01:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unlimited API requests when image endpoint is giving a 404.

### What is the root cause of that problem?
In the ```ImageWithSizeCalculation``` component, ```isImageCached``` is initialized with ```true``` and ```isLoading``` is initialized with ```false```. Later on in the component logic, the states are set and checked to determine whether or not an image is cached resulting in shorter load times.

the ```useEffect``` for ```isLoading``` and ```isImageCached``` states may not behave as expected. The implementation checks if ```isLoading``` is false and ```isLoadedRef.current``` is true before considering if the image as cached. However, image loading events can be asynchronous, and this approach may not guarantee accurate results.


### What changes do you think we should make in order to solve the problem?

Here:

```JSX
  const [isImageCached, setIsImageCached] = useState(true);
  const [isLoading, setIsLoading] = useState(false);
```
We can change the initial states of ```isImageCached``` to false and ```isLoading``` to true.

in the ```onError``` function, we can ```setIsLoading``` and ```setIsImageCached``` to false.

in the ```imageLoadedSuccessfully``` function, we can ```setIsLoading``` to false and ```setImageCached``` to true.

In the ```useEffect``` hook we want to check whether or not the image is cached after a loading delay of 200 milliseconds. If the image is not loaded (```isLoading``` is false) we ```setIsImageCached``` to false.

```useRef``` is used for persisting states across re-renders, but there may not be a need to make use of ```useRef``` because we can effectively manage the loading and caching states with ```useState``` that dictate the rendering behavior of this component.

In the Image component, we could check to see if the image is not cached and is currently loading. When image loads completely, we can set the caching value to true and the ```isLoading``` value to false.

**Comment by jNembhard** [comment] 2023-09-09 01:42
Contributor details
Your Expensify account email: jason.nembhard7@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01461ecd8247297516

**Comment by Pluto0104** [comment] 2023-09-09 06:25
@ntdiary yes, it works fine.

**Comment by Pluto0104** [comment] 2023-09-10 11:13
I apologize for the confusion. @ntdiary, I made an error in my proposal. I've now revised it. Could you please take a look [here](https://github.com/Expensify/App/issues/26904#issuecomment-1709177448)?

**Comment by Pluto0104** [comment] 2023-09-11 02:16
I apologize for the confusion. @ntdiary, I made an error in my proposal. I've now revised it. Could you please take a look [here](https://github.com/Expensify/App/issues/26904#issuecomment-1709177448)?

**Comment by kaushiktd** [comment] 2023-09-11 12:33
@ntdiary 
```
useEffect(() => {
    if (isLoadedRef.current || !isLoading || isOffline) {
        return;
    }

    let isUnmounted = false;
    const timeout = _.delay(() => {
        if (isUnmounted || !isLoading || isLoadedRef.current) {
            return;
        }
        setIsImageCached(false);
    }, 200);

    return () => {
        isUnmounted = true;
        clearTimeout(timeout);
    };
}, [isLoading, isImageCached, isOffline]);
```
The condition if (isLoadedRef.current || !isLoading || isOffline) checks if any of the following conditions is true:
isLoadedRef.current: The image is already loaded.
!isLoading: The image loading has already completed.
isOffline: The app is offline, indicating that we should not proceed with the timeout logic.
If any of these conditions is true, the code inside the useEffect will not execute, preventing the issue from occurring when the app is offline.

**Comment by Pluto0104** [comment] 2023-09-11 13:10
Absolutely, @ntdiary, you bring up a valid point. With my proposal, we can easily wrap the component with `withNetwork` without the need for any additional dependencies. This keeps the implementation clean and straightforward.

For example:

```js
export default React.memo(withNetwork()(ImageWithSizeCalculation));
```

This approach ensures that `ImageWithSizeCalculation` will be re-rendered whenever there is a change in the network status.

https://github.com/Expensify/App/assets/136573674/7fe6d0bb-83f7-4b9f-8d8c-153ccaa8e00a

**Comment by Pluto0104** [comment] 2023-09-13 02:43
@ntdiary, I appreciate your perspective, and I'm also a fan of hooks. However, I was wondering if my proposed solution might be incorrect or bad.

**Comment by Pluto0104** [comment] 2023-09-13 03:12
Hi @ntdiary, I noticed that we aren't employing `useMemo` for `props.url` in any other component that uses Image. I believe this might lead to a lack of consistency.

**Comment by Pluto0104** [comment] 2023-09-13 03:36
> @Pluto0104 can you give me an example?

https://github.com/Expensify/App/blob/2d5bea5b58079506337d21d2ba94a3e295882f94/src/components/ImageView/index.js#L257-L264
Regarding this code snippet, we're not utilizing `useMemo` for the image URL.

> The source here is not just props.url, it's the object, that why if we don't wrap it in useMemo, it will be re-created every time -> cause infinity loading

In this case, we might consider wrapping the Image component with `React.memo` as I mentioned in my proposal. I believe this approach is more efficient.

**Comment by Pluto0104** [comment] 2023-09-13 03:51
@ntdiary how do you think about ⬆️ ?

**Comment by Pluto0104** [comment] 2023-09-13 13:59
@ntdiary I had seen your [comment](https://github.com/Expensify/App/issues/26904#issuecomment-1713639832). I want to clarify that I didn't suggest using a loading animation. Currently, I am waiting for the design to be finalized. It appears that you have selected a proposal, but I would like to point out that the issue of accidental deletion of images on the server side is not addressed in [the proposed solution](https://github.com/Expensify/App/issues/26904#issuecomment-1711670525). This will cause infinite rerender.

**Comment by Pluto0104** [comment] 2023-09-14 09:58
> @Pluto0104, what does accidental deletion on the server side refer to?

What do you mean?

**Comment by Pluto0104** [comment] 2023-09-14 11:25
> @Pluto0104, eh, is this case related to this issue?

Yes, the title is "Web - Unlimited API requests when the image endpoint is giving a 404 error." Does that mean the image is not found, correct?

> And I'm also curious how you confirmed that https://github.com/Expensify/App/issues/26904#issuecomment-1711670525 would not be able to address this case. 😂

This solution is designed to handle only offline status. I'm interested in understanding how you reached the conclusion that the provided solution could address this particular case. Could you please provide more details?

**Comment by greg-schroeder** [comment] 2023-09-18 10:41
bump @ntdiary

**Comment by Pluto0104** [comment] 2023-09-18 14:26
@ntdiary it seems to be what I mentioned.

https://github.com/Expensify/App/assets/136573674/bff9f724-f5c6-4327-8893-8bb8dff73011

**Comment by greg-schroeder** [comment] 2023-09-25 07:24
Bumped linked slack discussion to see what's next

**Comment by greg-schroeder** [comment] 2023-09-25 08:39
Assigned @dannymcclain per team discussion for necessary asset <3

**Comment by dannymcclain** [comment] 2023-09-28 03:14
Asset attached! [Receipt Image Offline Placeholder.png.zip](https://github.com/Expensify/App/files/12745157/Receipt.Image.Offline.Placeholder.png.zip)

![Receipt Image Offline Placeholder](https://github.com/Expensify/App/assets/7516624/4ea14824-5780-4b50-b2be-57947cec4015)

**Comment by dannymcclain** [comment] 2023-09-29 02:04
LOL well that's no good! Here's the SVG: [Receipt_Placeholder.svg.zip](https://github.com/Expensify/App/files/12755276/Receipt_Placeholder.svg.zip)

The color for the icon is `green 700` (`#085239`) - should be baked into the SVG though, and the background color for the placeholder is `green 800` (`#002E22`).

**Comment by Pluto0104** [comment] 2023-10-02 18:51
@ntdiary It seems that you forgot [this comment](https://github.com/Expensify/App/issues/26904#issuecomment-1717693040). @kaushiktd's solution might not work in that case.

**Comment by cristipaval** [comment] 2023-10-07 18:12
Thanks @ntdiary for the rigorous review!

**Comment by kaushiktd** [comment] 2023-10-09 05:44
Thanks @ntdiary and @cristipaval

**Comment by kaushiktd** [comment] 2023-10-10 03:19
Awesome! No prob.

**Comment by greg-schroeder** [comment] 2023-10-19 00:41
Reviews continue on linked PR

**Comment by greg-schroeder** [comment] 2023-11-14 16:45
Work continues on linked PR - seems like it's been going a while, is there anything you need from Expensify team to help push this over the finish line?

**Comment by greg-schroeder** [comment] 2023-11-26 20:00
Hmm. I'm not sure if we can share access to that as it's an internal design doc, I am asking.

**Comment by greg-schroeder** [comment] 2023-12-19 01:35
Closing this per discussion in Slack.

**Comment by greg-schroeder** [comment] 2023-12-19 02:05
Discussing in Slack

**Comment by greg-schroeder** [comment] 2023-12-19 02:48
- @kaushiktd I'm sending you an offer for $250 (half the bounty of this issue) for the work you've done on the linked PR. Even though the issue was fixed elsewhere, we appreciate your effort here.
- Let’s split off the second part of this issue (improving the display of receipt fallback image) into a new issue and start fresh, as we don’t feel the current implementation is ideal 
- We can probably just close the linked PR and this issue

**Comment by greg-schroeder** [comment] 2023-12-19 02:52
Offer sent to @kaushiktd

**Comment by greg-schroeder** [comment] 2023-12-19 02:52
I'll pay that out as soon as you accept. Closing this accordingly!

**Closed by greg-schroeder** 2023-12-19 02:52 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug

**Comment by kaushiktd** [comment] 2023-12-19 02:54
> * I'm sending you an offer for $250 (half the bounty of this issue) for the work you've done on the linked PR. Even though the issue was fixed elsewhere, we appreciate your effort here.

That is a bummer! But alright. 
Also if you wish I can work on this issue for second part as I have worked so far on first part and second is relevant to this.

And I accepted the offer as well.

**Comment by kaushiktd** [comment] 2023-12-19 02:54
One more request, since I have not worked on Upwork for quite a long time, can you please give me nice rating with review? This will mean a lot to me.

**Comment by greg-schroeder** [comment] 2023-12-19 02:59
Yes of course - I left a 5 star review. I'll get it on my list to create the new issue for the other item. @ntdiary indicated we weren't in a great place for that yet so we want to split it out to get a more unified approach going

**Comment by kaushiktd** [comment] 2023-12-19 03:04
So can I submit solution of second part here OR will you create a new issue?
