### ISSUE TITLE
Editing card feed name doesn't work on mobile

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53515] opened 2024-12-04 03:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1733262075681289)

## Action Performed:
Prerequisite: User added a company card

1. Click settings for the added card
2. Click on the Card feed name 
3. Enter any name and save
4. Click the back arrow two times to view the company cards page

## Expected Result:
Entered name updated in the card feed name
## Actual Result:
Updated name not saved and default card name displayed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/e96c0ae9-beaf-4595-97de-1277d00147fa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VickyStash** [comment] 2024-12-04 08:32
I've tried with several feeds and wasn't able to reproduce the bug. Asked for more details in the [slack](https://callstack-hq.slack.com/archives/C06ML6X0W9L/p1733301099615739?thread_ts=1733262075.681289&cid=C06ML6X0W9L).

**Comment by VickyStash** [comment] 2024-12-04 15:00
**Updates:** 
It looks like it's a back-end issue. After feed name update the `OpenPolicyCompanyCardsPage` API call returns `companyCardNicknames` in the format:
```
 "companyCardNicknames": {
         "oauth": {
              "wellsfargo": {
                   "com": "test"
               }
          }
},
```
while app expects it to be

```
"companyCardNicknames": {
    "oauth.wellsfargo.com": "test"
}
```

**Comment by mallenexpensify** [comment] 2024-12-06 01:08
I believe this should fix it
- https://github.com/Expensify/Auth/pull/13450

cc @nkuoch and @mountiny who are on it.

**Comment by VickyStash** [comment] 2024-12-06 15:02
> https://github.com/Expensify/Auth/pull/13450

I think it got merged by @mountiny!

**Comment by joekaufmanexpensify** [comment] 2024-12-06 15:09
Yep, merged this morning

**Comment by VickyStash** [comment] 2024-12-09 22:52
@joekaufmanexpensify @mountiny Should this one be closed?

**Comment by mountiny** [comment] 2024-12-10 12:18
Yes, this is fixed

**Closed by mountiny** 2024-12-10 12:18 UTC
Labels: Reviewing, Daily, Bug
