### ISSUE TITLE
[$500] Settings - Delay Occurs When Navigating Back from Accounting Settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36888] opened 2024-02-20 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Click on "Profile."
2, Click on the "Back" button to return from the Accounting Settings

## Expected Result:
There should be no delay when navigating back from the Accounting Settings

## Actual Result:
A delay occurs when navigating back from the Accounting Settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/98026db9-d597-4d33-838f-f576729969df

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181bbb8ce76a8fa96</li>
        <li>Upwork Job ID: 1759948536551297024</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-02-20 14:43
Looks like regression from https://github.com/Expensify/App/pull/36309

**Comment by mvtglobally** [comment] 2024-03-05 04:50
Issue not reproducible during KI retests. (First week)

**Comment by srikarparsi** [comment] 2024-03-06 07:41
Agreed, can't reproduce it either. Closing this out.

**Closed by srikarparsi** 2024-03-06 07:41 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted
