### ISSUE TITLE
[$500] Android - Compose  box -App crashes on sending message in offline while page is loading

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30685] opened 2023-11-01 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile icon--preferences
3. Toggle on forced offline
4. Navigate back to LHN
5. Tap on a admin page with no activity and loading (or any page which is loading)
6. Send a message

## Expected Result:
App must not crash on sending message in offline while page is loading.

## Actual Result:
App crashes on sending message in offline while page is loading.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/87d028aa-2b31-4372-a3f5-23b9cf20a60e

[crash.txt](https://github.com/Expensify/App/files/13226782/crash.txt)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01459aaf4e457cbbe8</li>
        <li>Upwork Job ID: 1719691150728323072</li>
        <li>Last Price Increase: 2023-11-08</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-11-06 11:01
@burczu what do you think of the above proposals?

**Comment by burczu** [comment] 2023-11-06 11:41
@sonialiap I'm sorry - I was OOO last week. I'll be reviewing proposals soon.

**Comment by burczu** [comment] 2023-11-07 10:12
I've just tried to reproduce the issue but with no luck - how to do you get the loading state of the app while being offline? I'm opening the admin page but it loads normally even when forced offline...

**Comment by burczu** [comment] 2023-11-09 11:25
@tienifr Thanks for help!

I've checked one more time and seems it's not reproducible on the current `main`:

https://github.com/Expensify/App/assets/7771498/61c49c6c-662f-48fc-8160-f1b84f8b7605

Can someone else confirm it?

**Comment by sonialiap** [comment] 2023-11-13 13:28
>App crashes on sending message in offline while page is loading.

I just tested and my android app does not crash when I send a message to a loading #admins room while "force offline" is toggled. 

Since multiple people cannot reproduce. Closing

**Closed by sonialiap** 2023-11-13 13:28 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
